### ISSUE TITLE
Add items icon

### ISSUE THREAD

**Issue by peterhav** [Templarian/MaterialDesign#10]
Hello, I have a need for a generic "add items" icon. This icons should resemble the action to add one or more items to a collection (it could for example be an icon showing a number of blocks (top left), a basket (bottom) and a small arrow (top left to bottom) from the blocks into the basket).

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/basket-fill
http://materialdesignicons.com/icon/basket-unfill
