### ISSUE TITLE
Rounded icons not correctly rendered (web font)

### ISSUE THREAD

**Issue by nonninz** [Templarian/MaterialDesign#100]
Hi,

first of all thank you for your efforts.

I wanted to report that your fonts are not correctly rendered. Any Icon with a circular element in it is incorrectly rendered as a romboid.

This happens consistently with Chrome, Firefox and Safari.

I am attaching some screenshots to better explain the issue.

Example of a button:
![Example of a button](https://cloud.githubusercontent.com/assets/701816/5799820/12a97bd4-9fd7-11e4-99db-127adaf51d57.png)

Preview page from downloaded zip file:
![Preview page from downloaded zip file](http://i.imgur.com/oBNk2LP.png)

See for example: mdi-voicemail, mdi-bike, mdi-beats... Basically any icon with a circle in it.

**Comment by Templarian** [comment]
This was fixed yesterday in v0.7.33-alpha.

Please update.

**Comment by Templarian** [comment]
By the way if you want to read more: http://templarian.com/2015/01/18/material_design_icons_webfont_updates

It includes a screenshot from Chrome displaying the corrected icons.
