### ISSUE TITLE
Tweak/Wave Icon

### ISSUE THREAD

**Issue by ChristenEdmundson** [Templarian/MaterialDesign#1001]
I'm making a material design inkscape theme and can't make a tweak icon myself. the original icon looks like  wave, so a material design wave icon seems like the appropriate replacement. the original icon looks like this:
![capture](https://cloud.githubusercontent.com/assets/16363899/12539238/f11e2204-c2bb-11e5-9628-64273c37b3f4.PNG)

**Comment by PeterShaggyNoble** [comment]
[`waves`](https://materialdesignicons.com/icon/waves) has since been added - I think that should satisfy this request.
