### ISSUE TITLE
add material design icon file assignment from google

### ISSUE THREAD

**Issue by javicebrian** [Templarian/MaterialDesign#1002]
you can find it here:

https://storage.googleapis.com/material-icons/external-assets/v2/icons/svg/ic_assignment_black_24px.svg

**Comment by CoDEmanX** [comment]
We have Google's assignment icons in MDI, but they are called `clipboard-...`:

https://materialdesignicons.com/icon/clipboard-text

@Templarian: all of them should probably have an alias "assignment" and maybe also "task".

**Comment by javicebrian** [comment]
Great one, thanks!
Yeah, to add a alias with the original material name would be cool, but maybe just a label, so at least would be show during the searching.
