### ISSUE TITLE
newspaper-alt

### ISSUE THREAD

**Issue by imogenic** [Templarian/MaterialDesign#1003]
Designed a more "material" version of the newspaper icon. I would fork and add it myself, but I'm not at my main system right now.

<img width="213" alt="screen shot 2016-01-25 at 9 08 46 am" src="https://cloud.githubusercontent.com/assets/1940038/12553066/4d1b8178-c343-11e5-8d04-79e69a80a595.png">

**Comment by CoDEmanX** [comment]
I like it, but it's very similar to Google's newspaper icon. @Templarian?

I experimented with alternatives too, but it's not that great: ![newspaper](https://cloud.githubusercontent.com/assets/1309249/12553160/0d8a18fc-c376-11e5-9231-0640842032a6.png)

Please put the source SVG in your Dropbox, on your Google drive or similar and post a link.

**Comment by imogenic** [comment]
The idea was to be similar to Google's newspaper icon. I was using it in a project and over time realized it looked busy compared to the others. This version scales up the content while retaining the silhouette.

[SVG](https://drive.google.com/file/d/0Bxs0ce6dpaIiTFhTMnJDc2x4Y0E/view?usp=sharing)

**Comment by Templarian** [comment]
@imogenic I kind of agree the one in the pack is a little too busy. Might be a good idea to replace it.

@CoDEmanX Hmm... maybe instead of 3 lines 2? There might be a design here that would be a nice `-variant`.

**Comment by Templarian** [comment]
[![newspaper](https://materialdesignicons.com/icon/newspaper)](https://materialdesignicons.com/icon/newspaper)

I just replaced the official one. Since it fits nicer with the Material Design guidelines.

**Comment by imogenic** [comment]
@Templarian Why is Google credited on the official site and not me?
