### ISSUE TITLE
Incoming/Outgoing/Express Email

### ISSUE THREAD

**Issue by Sjennon** [Templarian/MaterialDesign#1004]
I noticed there are icons with that for phone, but not for email.

I would LOVE to use these!

**Comment by CoDEmanX** [comment]
What we have are inbox and outbox icons:

https://materialdesignicons.com/icon/inbox
https://materialdesignicons.com/icon/outbox

What we miss are just a tray with no arrow and multiple trays, which I already created:

https://github.com/Templarian/MaterialDesign/issues/420#issuecomment-127570399

**Comment by Sjennon** [comment]
Thanks for the reply. I was actually more thinking of the email icon itself and then incoming/outgoing arrow icons.

**Comment by CoDEmanX** [comment]
You mean like this?

![email-incoming](https://cloud.githubusercontent.com/assets/1309249/12584394/9dd0709c-c447-11e5-825f-26239c123fab.png) ![email-outgoing](https://cloud.githubusercontent.com/assets/1309249/12584395/9de791e6-c447-11e5-9010-6a3d34f7e988.png)

Seems overly literal to me...

**Comment by Sjennon** [comment]
Something like that would be great though.

**Comment by CoDEmanX** [comment]
Well, they can be added if Templarian is fine with it. I would reposition the arrows a bit though, maybe centered above the letter.

**Comment by Sjennon** [comment]
Perhaps similar to this one?

https://materialdesignicons.com/icon/email-secure

**Comment by CoDEmanX** [comment]
The arrow would be extremely small in that case, I think it could only be a triangle to be honest, which isn't as expressive as a full arrow.

**Comment by Sjennon** [comment]
Or
![image](https://cloud.githubusercontent.com/assets/6576878/12610952/b8c262ea-c4ea-11e5-98f2-d898e8007bb4.png)

**Comment by CoDEmanX** [comment]
Adding `email-express` to this request from #877

**Comment by CoDEmanX** [comment]
Outbox:

![grafik](https://user-images.githubusercontent.com/1309249/38642052-2446eb4e-3dd9-11e8-9753-b492133615ff.png)

Download: [outbox.zip](https://github.com/Templarian/MaterialDesign/files/1900446/outbox.zip)

Ref: https://github.com/Templarian/MaterialDesign/issues/420#issuecomment-126732936

**Comment by CoDEmanX** [comment]
Well, most `-box` icons use a 18x18 box. This is based on a Google icon, of which I assume that it is 20x20 originally.

**Comment by JamesCoyle** [comment]
Closing as we have `inbox` and I don't really see why we need send in a box...
