### ISSUE TITLE
d20 die

### ISSUE THREAD

**Issue by xaviergonz** [Templarian/MaterialDesign#1005]
A d20 die to go with the d6 die for rpgs

**Comment by CoDEmanX** [comment]
What?

**Comment by Templarian** [comment]
Yea, I think this is a pretty good icon to add.

@CoDEmanX Never play DnD or any D20 based RPG game?

**Comment by CoDEmanX** [comment]
Ah, got it. Was thinking microchips.

**Comment by Templarian** [comment]
[![dice-d4](https://materialdesignicons.com/icon/dice-d4)](https://materialdesignicons.com/icon/dice-d4) [![dice-d6](https://materialdesignicons.com/icon/dice-d6)](https://materialdesignicons.com/icon/dice-d6) [![dice-d8](https://materialdesignicons.com/icon/dice-d8)](https://materialdesignicons.com/icon/dice-d8) [![dice-d20](https://materialdesignicons.com/icon/dice-d20)](https://materialdesignicons.com/icon/dice-d20)

Need to make a `dice-d10` and `dice-d12`. I removed the `dice` icon from the pack by the way. It wasn't material and looked really out of place.

**Comment by CoDEmanX** [comment]
What about these two beauties?

![Imgur](http://i.imgur.com/ZMGxqUP.jpg)

**Comment by xaviergonz** [comment]
Maybe the d8 should be a bit more wide, but other than that those look gorgeous:+1: 

While at it maybe also a d100 (maybe a pair of d10 shapes with a 100 somewhere) and a d2 (maybe shaped like a circle (a coin))?

**Comment by stevesea** [comment]
came to log a new issue to add a d12, but it probably belongs as a comment here instead.

d12 are dodecahedrons, so it could be a '12' inside a pentagon shape?

**Comment by Templarian** [comment]
@stevesea I'm going to mark this issue as a bug since we have the general numbers now, but need to fix one.

**Comment by JamesCoyle** [comment]
A D12 would probably be a 12 within a decagon if we're keeping with the style of the D20. A D12 silhouette would be a decagon:

![image](https://user-images.githubusercontent.com/10384436/28222638-4d1e1892-68c0-11e7-9800-b8f9ee058d31.png)
