### ISSUE TITLE
Google Maps icon

### ISSUE THREAD

**Issue by anjocerdena** [Templarian/MaterialDesign#1006]
Contributing the Google Maps icon from the official app's notification, slightly tweaked to appear centered on canvas, and changed strokes from 3px to 2px for consistency.

[Google Maps.zip](https://github.com/Templarian/MaterialDesign/files/107748/Google.Maps.zip)

**Comment by Templarian** [comment]
[![google-maps](https://materialdesignicons.com/icon/google-maps)](https://materialdesignicons.com/icon/google-maps)
