### ISSUE TITLE
Spray 

### ISSUE THREAD

**Issue by RodrigoSantiago** [Templarian/MaterialDesign#1007]
Yes, just a spray , to complete the drawing's icons.

**Comment by Templarian** [comment]
Like a spray can? Can you post an example. Just so we design the right icon.

**Comment by GreenTurtwig** [comment]
[This](http://fay.iniminimo.com/vista_paint_pics/paintspray.gif), is how it looks in an older version of Microsoft Paint. I'm assuming that's what they want. :-)

**Comment by RodrigoSantiago** [comment]
I found some exemples: 

http://icons.iconarchive.com/icons/elegantthemes/beautiful-flat/64/spray-paint-icon.png

http://icons.iconarchive.com/icons/designcontest/vintage/64/Spray-icon.png

http://icons.iconarchive.com/icons/designcontest/outline/64/Spray-icon.png

**Comment by infanf** [comment]
![spray-can](https://cloud.githubusercontent.com/assets/8826710/12945958/3a0e6d38-cff1-11e5-9a75-4195bf093e46.png)
![spray-can-48](https://cloud.githubusercontent.com/assets/8826710/12945957/3a0d79fa-cff1-11e5-9f6d-57e1467a9c25.png)
![spray-can-96](https://cloud.githubusercontent.com/assets/8826710/12945959/3a149712-cff1-11e5-9759-5639667e9452.png)
[spray.zip](https://github.com/Templarian/MaterialDesign/files/124608/spray.zip)

**Comment by CoDEmanX** [comment]
@infanf: looks a bit like a fire extinguisher. I think it should be more like this:

![spray-can](https://www.iconexperience.com/_img/i_collection_png/64x64/plain/spray_can.png)

**Comment by Templarian** [comment]
Yea, it might be confused with an air horn can. Using small round balls might make it easier to identify.

**Comment by Templarian** [comment]
![spray](https://cloud.githubusercontent.com/assets/338885/15237488/eaffa9aa-1893-11e6-8fb6-b39f2f15ffc2.png)

Something like this maybe?

**Comment by Templarian** [comment]
[![spray](https://materialdesignicons.com/icon/spray)](https://materialdesignicons.com/icon/spray)

**Comment by CoDEmanX** [comment]
I like it!
