### ISSUE TITLE
api,support  #170

### ISSUE THREAD

**Issue by jayakrishnancn** [Templarian/MaterialDesign#1008]
api support #280

**Comment by Templarian** [comment]
Do you have an example?

**Comment by jayakrishnancn** [comment]
![api_img](https://cloud.githubusercontent.com/assets/12905670/12694388/5356f5b4-c752-11e5-8458-17957f737a46.png)
 something like this may be

**Comment by PeterShaggyNoble** [comment]
Closing as a duplicate of #574
