### ISSUE TITLE
Icon pool

### ISSUE THREAD

**Issue by cpalosrejano** [Templarian/MaterialDesign#1009]
Maybe like this one, but materialized :smile: 

![ic_pool_gray_dark_24dp](https://cloud.githubusercontent.com/assets/2341804/12697045/1011480a-c779-11e5-893c-1995882d13a8.png)

**Comment by Templarian** [comment]
[![pool](https://materialdesignicons.com/icon/pool)](https://materialdesignicons.com/icon/pool)

I'm not 100% sure on this one. If it looks "off" let me know and I'll reopen the issue. Tried a few different variations, so I may have been just looking at it too long.

**Comment by CoDEmanX** [comment]
I like it! Good job at reducing the details.
