### ISSUE TITLE
microphone and microphone-off does not align

### ISSUE THREAD

**Issue by sporsh** [Templarian/MaterialDesign#101]
Which makes the icon jump when used in a toggle setting:
![output_2wjtra](https://cloud.githubusercontent.com/assets/1416154/5817280/7f69c732-a0aa-11e4-8763-8a5c9e86d3cc.gif)

**Comment by Templarian** [comment]
That is definitely a bug. I'll try and get that fixed tonight.

**Comment by Templarian** [comment]
Fixed.

**Reminder:** The webfont is updated weekly on the weekends. I don't automate it since it's best to do a look through icons to make sure each release is stable.
