### ISSUE TITLE
Invoice Icon

### ISSUE THREAD

**Issue by sraijmakers** [Templarian/MaterialDesign#1010]
I dont see any icon that can be used for "Invoice"

This would be a good addition.

**Comment by infanf** [comment]
[invoice.zip](https://github.com/Templarian/MaterialDesign/files/124593/invoice.zip)
![invoice](https://cloud.githubusercontent.com/assets/8826710/12945779/fef005e6-cfef-11e5-877d-1638bfe3b6f4.png) ![invoice-48](https://cloud.githubusercontent.com/assets/8826710/12945780/ff097922-cfef-11e5-8050-77466adab8a0.png) ![invoice-96](https://cloud.githubusercontent.com/assets/8826710/12945781/ff14bd28-cfef-11e5-81e2-66b63d6b4c22.png)

**Comment by CoDEmanX** [comment]
`currency-usd` uses a different type of S, a small variant might be slightly better legible than this one?

**Comment by sraijmakers** [comment]
For european customers the € would be better :)

**Comment by Templarian** [comment]
Yea, for these types of icons it's best to not use a currency symbol and make it more global (can't have 10 different icons every time).

**Comment by CoDEmanX** [comment]
... if only more people knew the generic currency symbol:
https://en.wikipedia.org/wiki/Currency_sign_(typography)

**Comment by Templarian** [comment]
Removing the contribution label on this issue. Still not sure we have a good solution to this icon.

**Comment by atempel** [comment]
What about that? Same idea, but using Roboto from Google.
![image](https://cloud.githubusercontent.com/assets/6963140/17750509/3594cab2-6499-11e6-8fa5-204c2f5463e8.png)

**Comment by Templarian** [comment]
Yea, we're going to want to do this icon without a currency symbol if possible. Although I don't think we know what that would look like exactly. :confused:

**Comment by Anupheaus** [comment]
What about a page with coins on it, I might be wrong but doesn't every (or at least a good majority) of currencies have coins?  And people know that coins generally mean currency, so if you take the icon of the page above with the dollar sign on it and replace the dollar sign with coins, wouldn't that be generic enough?  Similar to http://www.infusionmobile.co.nz/wp-content/uploads/2012/12/invoice-icon.png icon but obviously more material design-esque :)

**Comment by PeterShaggyNoble** [comment]
[Here](https://icons8.com/web-app/6942/invoice)'s the Icons8 invoice icons, if it's any help.

**Comment by PeterShaggyNoble** [comment]
Google uses this icon for orders at https://store.google.com/, it might be suitable for invoice (and receipt) too.

[orders.zip](https://github.com/Templarian/MaterialDesign/files/1379011/orders.zip)

**Comment by c0nstant1n3** [comment]
![invoice](https://user-images.githubusercontent.com/7995668/35415899-e0c5e076-022f-11e8-8483-2b131fabf108.png)
![invoice 2x](https://user-images.githubusercontent.com/7995668/35415900-e0e1bf94-022f-11e8-86ea-2b368d96f7e6.png)
![invoice 3x](https://user-images.githubusercontent.com/7995668/35415901-e0fd5c7c-022f-11e8-9c44-9b7e55784ffa.png)
[invoice.svg.zip](https://github.com/Templarian/MaterialDesign/files/1665907/invoice.svg.zip)

**Comment by PeterShaggyNoble** [comment]
`receipt` has been of use to represent an invoice (see #2785) and is currency independent. Should we just run with that, give it an alias and close this out?

[![bill](https://user-images.githubusercontent.com/15157491/35908358-5341b3ac-0be8-11e8-9746-58dc57c92b0e.png)](https://materialdesignicons.com/icon/receipt)

**Comment by JamesCoyle** [comment]
I'm gonna close this out and recommend people use the receipt icon. If anyone has any other ideas that are universally recognisable please let us know.
