### ISSUE TITLE
Naming differences

### ISSUE THREAD

**Issue by NenadP** [Templarian/MaterialDesign#1012]
I wonder about naming differences between original google pack and this collection. Eg. "person" is being called "account". I assume google changed it on their end and resolution here is not to update cause it might break people's icons?

**Comment by Templarian** [comment]
The community version pre-dates the official one by a few months, so a lot of the naming was already in place. Not too big of an issue as developers are either using the official pack or the community one at this point.

I've put aliases in for a few of the icons to make searching easier, but I still have to alias a lot of the icons (it's a lower priority at the moment as I roll out some new features soon).
