### ISSUE TITLE
Bundling SVG

### ISSUE THREAD

**Issue by NenadP** [Templarian/MaterialDesign#1015]
Didn't investigate, but it would be a cool feature if one could select from icons available and then download them as single mdi.svg? Looking for the way to minimize svg library in production.

**Comment by PeterShaggyNoble** [comment]
If you're still in need of this, it can be done through [the sandbox](https://petershaggynoble.github.io/MDI-Sandbox/). Either filter the icons to just those you need and download the SVG via the menu in the search results or add the icons you need to your favourites and download from there.
