### ISSUE TITLE
Sensors icons

### ISSUE THREAD

**Issue by bladower** [Templarian/MaterialDesign#1016]
It would be nice to have the most common sensors icons. Now you have the compass, GPS, temperature ...

I suggest these: 
- [x] Accelerometer
- [x] gyro
- [x] [altimeter](https://materialdesignicons.com/icon/altimeter)
- [x] barometer
- [x] [heart rate meter](https://materialdesignicons.com/icon/heart-pulse)
- [x] pedometer - See #755
- [ ] cadence
- [x] [proximity](https://materialdesignicons.com/icon/map-marker-radius)
- [x] [indoor location](https://materialdesignicons.com/icon/home-map-marker)
- [x] [humidity](https://materialdesignicons.com/icon/water-percent)
- [x] [temperature](https://materialdesignicons.com/icon/thermometer-lines) / [variant](https://materialdesignicons.com/icon/thermometer)
- [x] [magnetometer](https://materialdesignicons.com/icon/compass) / [variant](https://materialdesignicons.com/icon/compass-outline)
- [x] [velocimeter](https://materialdesignicons.com/icon/speedometer) / [variant](https://materialdesignicons.com/icon/gauge)

Thank you for your attention. Good job!

**Comment by CoDEmanX** [comment]
I like the idea, but I don't have a clue how to depict them as icons that comply to the MD guidelines. Do you have any examples for the ones you want to see in MDI?

**Comment by bladower** [comment]
Thanks for the interest. I searched minimalistic icons that are very common in the scientific literature and the world of sport. I know that it is difficult to do it  comply MD guidelines. I understand that some may do and others do not...

What do you think?


![sensors_icons](https://cloud.githubusercontent.com/assets/17022501/12778753/d1cba7ae-ca64-11e5-99de-ee1fb2794911.PNG)

**Comment by CoDEmanX** [comment]
I edited your initial post. It now has a task list of the sensors you proposed, plus the ones from the picture.

We have an icon request for footsteps (#755), which will also fulfill yours for pedometer.

I'm not sure about gyro and barometer, they seem very similar to velocimeter. A gyro icon might suffer from the same problems as an atom icon: https://github.com/Templarian/MaterialDesign/issues/147#issuecomment-127758977

Google has a heart rate icon in Google Play Store: #1022

Accelerometer and altimeter should be easy to do. Proximity could be tricky, because it's easily confused with "wifi" or "target". Indoor location seem pretty specific, and may turn out to require too much details for our 24 square pixel icons.

**Comment by bladower** [comment]
It's okay.
The "footsteps" icon is fully valid for the pedometer. 
The "gauge" icon may be the same as the barometer.

I searched some more simple icons for gyro, but I know it's hard. 
![images](https://cloud.githubusercontent.com/assets/17022501/12811360/40193f7e-cb2c-11e5-8c4d-878fadfc0534.png)

I think the icon "map-marker-radius" could be used for the icon of the proximity. what do you think?
![prox](https://cloud.githubusercontent.com/assets/17022501/12811594/cde683ce-cb2d-11e5-8108-6d3cec116e56.png)

And the icon indoor location could be simplified a bit. 
![indoor](https://cloud.githubusercontent.com/assets/17022501/12811362/44c61042-cb2c-11e5-9c09-17af9bbf1a81.png)

I've also found on the website of Ant + many icons that might help.
https://www.thisisant.com/consumer/ant-101/activity-icons


what do you think?

**Comment by CoDEmanX** [comment]
True, gauge could be used for barometer and manometer.

The right-hand side gyro looks like it could work for us. I'll give it a try.

[map-marker-radius](https://materialdesignicons.com/icon/map-marker-radius) is indeed a good fit for proximity. In addition, Google's [wifi tethering](https://design.google.com/icons/#ic_wifi_tethering) icon could be used as well (part of #420). As third option, we could add the following ("target"):

![target](https://cloud.githubusercontent.com/assets/1309249/12812125/35d3852e-cb31-11e5-8ad1-6529b1b4edff.png) https://www.dropbox.com/s/ii9wxcapp3uol71/target.svg?dl=0

Indoor location:
![home-map-marker](https://cloud.githubusercontent.com/assets/1309249/12812429/4f041828-cb32-11e5-9703-9c10ee672018.png) https://www.dropbox.com/s/q0mxmlcntxf00qe/home-map-marker.svg?dl=0

Altimeter:
![altimeter](https://cloud.githubusercontent.com/assets/1309249/12812670/9a63b6c4-cb33-11e5-9f88-31aa900a4622.png) https://www.dropbox.com/s/79bvqmux8n27b0g/altimeter.svg?dl=0

**Comment by bladower** [comment]
I discovered a simpler way to see a gyroscope. The gyro sensors measure angular velocity, so in some cases they are drawn like a peg-top or totem.

![peg-top](https://cloud.githubusercontent.com/assets/17022501/12885283/0299f7a6-ce65-11e5-96f0-32e5ba104fca.png)

**Comment by Templarian** [comment]
[![altimeter](https://materialdesignicons.com/icon/altimeter)](https://materialdesignicons.com/icon/altimeter) [![bullseye](https://materialdesignicons.com/icon/bullseye)](https://materialdesignicons.com/icon/bullseye) [![home-map-marker](https://materialdesignicons.com/icon/home-map-marker)](https://materialdesignicons.com/icon/home-map-marker)

**Comment by CoDEmanX** [comment]
Regarding proximity, also see #1694

**Comment by MiguelAngelLV** [comment]
We need a "sensor" icon to groups all sensors too

**Comment by goyney** [comment]
Checking off accelerometer and gyro as both could potentially be represented by `rotate-orbit` or `axis-arrow`. I've aliased these icons.

**Comment by goyney** [comment]
Checking off barometer as it can be represented by `gauge`. Aliased it.

**Comment by goyney** [comment]
The only icon left on the list is `cadence`. I've seen this represented by a running person, a metronome, or a couple of arrows in a circle. We have answers to all these options, therefore I would say this issue has been fulfilled. Closing.
