### ISSUE TITLE
handcuffs

### ISSUE THREAD

**Issue by chriskobar** [Templarian/MaterialDesign#1017]
I do work with the US Courts in Washington, DC and we have a big need -- as I'm sure many other organizations do throughout the country -- for a set of icons representing elements of law enforcement and justice. Guns, badges, behind bars, bad guys, courts, handcuffs, bail, ankle bracelets, etc. I find it very difficult to find such things "out there," perhaps because there is simply a cultural bias in our community against guns and such. However, having such icons would be a big boon to federal, state, and local (and international) judicial and law enforcement customers.

**Comment by chriskobar** [comment]
Truth is, I would be happy to create them myself, but until I have the time I was hoping some other individual might know of some or put some together in the MD fashion.

**Comment by CoDEmanX** [comment]
An ankle bracelet seems very specific, but the rest appear quite useful in general to me. Not sure how feasible it is to create these in material design style though.

**Comment by goyney** [comment]
We also already have a gun.
[![pistol](https://materialdesignicons.com/icon/pistol)](https://materialdesignicons.com/icon/pistol)

**Comment by goyney** [comment]
Bad guy could be represented by `ninja`:
[![ninja](https://materialdesignicons.com/icon/ninja)](https://materialdesignicons.com/icon/ninja)

And courts by `bank`:
[![bank](https://materialdesignicons.com/icon/bank)](https://materialdesignicons.com/icon/bank)

**Comment by goyney** [comment]
I believe the only thing we don't have that might be useful from this request would be handcuffs. I'm renaming this issue to capture a request for that icon.

**Comment by PeterShaggyNoble** [comment]
One of the shield icons could also be used to represent a badge.

**Comment by JamesCoyle** [comment]
Need some ideas of what this would look like.

**Comment by goyney** [comment]
Whoops, accidentally removed a comment I thought was mine. 🤕 It asked for some potential examples. Anyways, here's my takes:

![image](https://user-images.githubusercontent.com/1015040/62843135-8f28d180-bc85-11e9-97c5-5f768cad9d16.png)![image](https://user-images.githubusercontent.com/1015040/62843145-99e36680-bc85-11e9-82aa-91b7a956ad23.png)

[handcuffs.zip](https://github.com/Templarian/MaterialDesign/files/3490868/handcuffs.zip)

**Comment by CoDEmanX** [comment]
@goyney I like 2. The chain has only 2 rings, how about adding a third similar to 1?

**Comment by JamesCoyle** [comment]
I'm insulted and also like the second one.

**Comment by goyney** [comment]
Dunno if it really adds anything besides more complexity. Thoughts?
![image](https://user-images.githubusercontent.com/1015040/62908308-623bf380-bd45-11e9-9c2e-8252e1acea44.png)

**Comment by CoDEmanX** [comment]
I agree, the cuffs would need to be moved into the margin to space out the chain rings. My vote goes to handcuffs-2.

**Comment by goyney** [comment]
[![handcuffs](https://materialdesignicons.com/icon/handcuffs)](https://materialdesignicons.com/icon/handcuffs)
