### ISSUE TITLE
Request for multiple specific Weather Icons to make the current set more variable

### ISSUE THREAD

**Issue by RobinSmits** [Templarian/MaterialDesign#1018]
Hi,

I would like to request multiple specific weather icons to expand the current weather icons and to be able to use them in my weather app.

I have the following requests:

1. Weather-PartlyCloudy-Fog = Combination of Weather-PartlyCloudly and Weather-Fog
2. Weather-PartlyCloudy-Rain = Combination of Weather-PartlyCloudly and Weather-Pouring/Rain(whatever fits best)
3. Weather-Lightning-Pouring = Combination of Weather-Lightning and Weather-Pouring
4. Weather-Lightning-Snow = Combination of Weather-Lightning and Weather-Snow
5. Weather-Night-PartlyCloudy = As Weather-PartlyCloudly but then with Moon and stars partially behind cloud.
6. Weather-Night-PartlyCloudy-Rain = Combination of the new Weather-Night-PartlyCloudy with Weather-Pouring/Rain(whatever fits best).
7. Weather-Night-Fog = Combination of Weather-Night and Weather-Fog

Please let me know if this would be possible.
I appreciate your work very much! :-)

Kind Regards, Robin.

**Comment by Templarian** [comment]
Might be related to #541. Have not looked through the list just yet.
