### ISSUE TITLE
Submitting some suggestions (Contribution)

### ISSUE THREAD

**Issue by pooley** [Templarian/MaterialDesign#1019]
Hey guys,

I wanted to contribute to the icon library myself. I needed some icons but did not find what I wanted so I edit those. 
_(please advise if I did something wrong, first post on Github !)_

5 icons are in the zip (svg format inside) : 

1.  **app-logout** : I've seen guys asking about a logout icon that respond to the [exit-to-app](https://materialdesignicons.com/icon/exit-to-app) icon. I took this one as a base but can't put the arrow outside of the outlined box since it will be out of bounds for material metrics, so I decided to let the arrow in what do you think ?
![app-logout](https://cloud.githubusercontent.com/assets/5587692/12777114/0bc2dad6-ca5b-11e5-8238-4441e3a5f774.png)

2. **camera-off** : the name talks by itself
![camera-off](https://cloud.githubusercontent.com/assets/5587692/12777115/0be89eec-ca5b-11e5-8fa6-b6c56c197b98.png)

3. **email-semi-outline** : This one is an another variant of mail icon but need this one in my design so maybe some guys out there will like this one.
![email-semi-outline](https://cloud.githubusercontent.com/assets/5587692/12777112/0bada4b8-ca5b-11e5-8d61-a89d80c39e61.png)

4. **erlenmeyer** : there are some icons like [beaker](https://materialdesignicons.com/icon/beaker) one, but I made this one a bit more icon guideline compliant, a variant that matches more my design needs.
![erlenmeyer](https://cloud.githubusercontent.com/assets/5587692/12777111/0bac4d02-ca5b-11e5-9a33-bab8ec54e7c1.png)

5. **no-credit-card**:  the name talks by itself too.
![no-credit-card](https://cloud.githubusercontent.com/assets/5587692/12777113/0bb18e16-ca5b-11e5-8da5-87e5fdc2bf50.png)

Here is the zip with svg inside :) (Hope it will be helpful for some of you guys)
[mdi-icons-submitted.zip](https://github.com/Templarian/MaterialDesign/files/115336/mdi-icons-submitted.zip)

**Comment by Templarian** [comment]
These look really nice. Not sure about the `erlenmeyer` (although I really need to rename beaker to something else in the pack, since they are not beakers... `flask` probably). It does fit pretty nicely, but not sure a variant is needed.

**Comment by pooley** [comment]
Thanks for your feedback. Hope to see them live soon ^^
Yeap, Erlenmeyer is a bit too specific. I think the same about the name, "flask", "chemistry" or even "lab".

Pleasure to contribute.

**Comment by Templarian** [comment]
[![camera-off](https://materialdesignicons.com/icon/camera-off)](https://materialdesignicons.com/icon/camera-off) [![credit-card-off](https://materialdesignicons.com/icon/credit-card-off)](https://materialdesignicons.com/icon/credit-card-off) [![email-variant](https://materialdesignicons.com/icon/email-variant)](https://materialdesignicons.com/icon/email-variant) [![email-open-outline](https://materialdesignicons.com/icon/email-open-outline)](https://materialdesignicons.com/icon/email-open-outline) [![login-variant](https://materialdesignicons.com/icon/login-variant)](https://materialdesignicons.com/icon/login-variant) [![logout-variant](https://materialdesignicons.com/icon/logout-variant)](https://materialdesignicons.com/icon/logout-variant)

Also `beaker-*` has been renamed to `flask-*`.

**Comment by pooley** [comment]
Hey why I'm not a contributor ? ^^ regarding your website you are the author, my aka is not mentionned above the 5 icons I push here ...

**Comment by Templarian** [comment]
@pooley There were only 4 accepted after modifications if I recall. Don't worry it's 5 whenever, you can submit them one at a time or all at once. So 1 more and I'll create a profile and assign these to it.
