### ISSUE TITLE
Comment Icon

### ISSUE THREAD

**Issue by Darwesh27** [Templarian/MaterialDesign#102]
There should be a comment icon like the one in facebook.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/comment-outline

Also added the one below, but I would advise the icon above. I'll be adding `-alert` and others similar to `message`.
http://materialdesignicons.com/icon/comment

**Comment by Darwesh27** [comment]
Cool.. :)

**Comment by Templarian** [comment]
Nevermind, I replaced the icons with slight variations. Then added others...

http://materialdesignicons.com/tag/comment

**Comment by Darwesh27** [comment]
Cool Icons.. Keep up the good work.. :+1:

**Comment by Darwesh27** [comment]
Ok this is actually out the scope of this issue but I didn't want to create a new one. I wanted to know if there can be any gifs on the website. I want a gif for signaling processing. Like the one google or facebook has..

**Comment by Templarian** [comment]
Nah, for that you could just use Adobe Fireworks or a tool that can make GIFs.

The more correct way would be to break up the SVG into 4 different paths (3 dot paths and the comment path in the background). Then you could use CSS3 Transforms on the fill-opacity.

This site is built off of vector assets to build out the Webfonts and various vector icons in many formats. The only rastered icons are for the PNGs for Android.

**Comment by Darwesh27** [comment]
Ok..

**Comment by CoDEmanX** [comment]
@Templarian: Android Vector Drawables support animations, don't they? Could probably be ported to CSS or CSS + JS, but from my experience, it's very sluggish on mobile phones. Even on desktops it can be jerky, but usually less than on smartphones.
E.g. http://product.voxmedia.com/2013/11/25/5426880/polygon-feature-design-svg-animations-for-fun-and-profit
