### ISSUE TITLE
directory tree (folder structure) icon

### ISSUE THREAD

**Issue by kleerkoat** [Templarian/MaterialDesign#1023]
request for icon representing a directory structure

**Comment by CoDEmanX** [comment]
Will probably not have that many details and should thus be usable for mono-hierarchies in general.

**Comment by PeterShaggyNoble** [comment]
`file-tree` or `sitemap` should cover this.

[![file-tree](https://user-images.githubusercontent.com/15157491/36742052-9d38b716-1bde-11e8-9308-dc07a8f02869.png)](https://materialdesignicons.com/icon/file-tree) [![sitemap](https://user-images.githubusercontent.com/15157491/36742106-bef01e58-1bde-11e8-932f-f1e52fc59a6f.png)](https://materialdesignicons.com/icon/sitemap)
