### ISSUE TITLE
VCard / contact icon

### ISSUE THREAD

**Issue by Thanix** [Templarian/MaterialDesign#1024]
I would like to request an icon that represents a contact (card), most commonly in connection to vCards:

![image](https://cloud.githubusercontent.com/assets/733248/12835295/33b59722-cbaf-11e5-9697-9c95a09136a5.png)
![image](https://cloud.githubusercontent.com/assets/733248/12835231/a7fc4488-cbae-11e5-87f6-7e053c705bb0.png)
![image](https://cloud.githubusercontent.com/assets/733248/12835235/b3f65706-cbae-11e5-8cd4-5efd3ef254b9.png)
![image](https://cloud.githubusercontent.com/assets/733248/12835249/d1467dfe-cbae-11e5-8d74-500482aab350.png)

The notches in the bottom appear to be an optional hat tip to the contact card holders of days gone by.

**Comment by infanf** [comment]
There is already an icon:
https://materialdesignicons.com/icon/contact-mail
Alternative:
![contact-card](https://cloud.githubusercontent.com/assets/8826710/12945649/3f8f742a-cfef-11e5-8355-2ccd79185464.png) ![contact-card-48](https://cloud.githubusercontent.com/assets/8826710/12945650/3faa8b16-cfef-11e5-8d6f-2c3f4e8430bb.png) ![contact-card-96](https://cloud.githubusercontent.com/assets/8826710/12945651/3fbc5bca-cfef-11e5-943c-af66c9854e21.png)

[contact-card.zip](https://github.com/Templarian/MaterialDesign/files/124583/contact-card.zip)

**Comment by Templarian** [comment]
[![account-card-details](https://materialdesignicons.com/icon/account-card-details)](https://materialdesignicons.com/icon/account-card-details)
