### ISSUE TITLE
Child Seat

### ISSUE THREAD

**Issue by crishnamohan** [Templarian/MaterialDesign#1025]
- [ ] Child Seat
- [x] Oxygen Cylinder
- [x] Priority
- [x] History

**Comment by CoDEmanX** [comment]
1: I assume you mean those for cars?

![Imgur](http://i.imgur.com/ppctgVF.jpg?1)

as opposed to bicycle child seats and child seat pads:

![Imgur](http://i.imgur.com/jWAwzoG.jpg?1) ![Imgur](http://i.imgur.com/Nu2WeZT.jpg?1)

2: I would like that one!

3: It's usually represented by an exclamation mark, and we have plenty of variants for that (search "alert")

4: Most icons that come up in a Google image search are already in MDI. Do you want something else? Please post an example.

**Comment by PeterShaggyNoble** [comment]
`gas cylinder` should cover O<sub>2</sub> cylinder. `history`, `priority-high` & `priority-low` already exist.

Leaving this open as a request for a child seat.

**Comment by goyney** [comment]
Child seat will be taken care of in #3795. Closing this issue because it has a lot of other fluff in it.
