### ISSUE TITLE
More food icons

### ISSUE THREAD

**Issue by vitorhugods** [Templarian/MaterialDesign#1027]
So, I and my friends are working on an app for my university.
We want to show our colleges a restaurant menu.
Some different food icons would be good.
- [ ] A [beef icon](https://cdn0.iconfinder.com/data/icons/foodix-square/128/foodix_steak-512.png).
- [ ] A [bean icon](http://www.thelouisianaroux.com/images/icon_01.jpg) would be clear and simple.
- [ ] [Fried-egg icon ](http://previews.123rf.com/images/mikefirsov/mikefirsov1205/mikefirsov120500002/13917064-Fried-Egg-Icon-illustration-Stock-Vector.jpg)is a good one for it.
- [ ] Any of these [salad icons](http://thumb7.shutterstock.com/display_pic_with_logo/2652973/255949465/stock-vector-vegetables-icon-set-vector-eps-255949465.jpg) is an excelent example.

Thanks to you guys already have an excelent Apple icon.

I really apreciate the help.

Thank you!

**Comment by goyney** [comment]
Fried egg is being tracked in #2944.

Also related: #725.

**Comment by JamesCoyle** [comment]
Gonna close this out. If you still need these icons, please open a new request for each of them so we can easily track them.

**Comment by CoDEmanX** [comment]
Google's extended set has several nice icons for different cuisines, we should those
