### ISSUE TITLE
New check icon

### ISSUE THREAD

**Issue by niteshkhatri** [Templarian/MaterialDesign#1028]
Hi guys. Can you please provide a new check icon like the one already available with minor change.

Reference icon which is already available on materialdesignicons.com
https://materialdesignicons.com/icon/checkbox-marked-circle-outline

Below icon is solid, I want it in line form with stroke.
https://materialdesignicons.com/icon/checkbox-marked-circle

I want the final icon to be like this
![image](https://cloud.githubusercontent.com/assets/7664984/12908957/f1ed7816-cf21-11e5-81dc-a1ea90e426fc.png)

I want the check mark to be completely inside the circle.

**Comment by niteshkhatri** [comment]
Please provide me this icon guys. I am waiting for your response.

**Comment by chrvasile** [comment]
Hope this is what you are looking for @niteshkhatri 
![checkbox-marked-circle-outline](https://cloud.githubusercontent.com/assets/17312269/13143358/91f508ba-d643-11e5-91ae-9a8bc8a6a650.png)

[checkbox-marked-circle-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/136177/checkbox-marked-circle-outline.svg.zip)

**Comment by niteshkhatri** [comment]
@chrvasile I have created the icon myself. Thank for your time anyway.

**Comment by Templarian** [comment]
@niteshkhatri Uhh... but you didn't share it. :disappointed:

[![check-circle](https://materialdesignicons.com/icon/check-circle)](https://materialdesignicons.com/icon/check-circle) [![check-circle-outline](https://materialdesignicons.com/icon/check-circle-outline)](https://materialdesignicons.com/icon/check-circle-outline)
