### ISSUE TITLE
Report Icon.

### ISSUE THREAD

**Issue by Darwesh27** [Templarian/MaterialDesign#103]
There should be an icon for reporting a post, or condemning one.

**Comment by Templarian** [comment]
Do you have an example for what this might look like? A hammer?

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/gavel Does this look right?

**Comment by Darwesh27** [comment]
O yes thats cool..

**Comment by Templarian** [comment]
Cool, I'm going to close this out. If you have any other suggestions feel free to make another issue. :smile:

Good luck with your apps!
