### ISSUE TITLE
Step Over (or Next)

### ISSUE THREAD

**Issue by Wombosvideo** [Templarian/MaterialDesign#1030]
Something like this: http://puu.sh/n1Jn7/985462dbfd.svg

**Comment by Wombosvideo** [comment]
When will you try and start creating this icon? I've already made one but I don't think you can use it because it doesn't match the wireframe I guess.

**Comment by CoDEmanX** [comment]
Is this semantically different from https://materialdesignicons.com/icon/debug-step-over ?

**Comment by Wombosvideo** [comment]
Dot is in middle but there should be another icon with one at beginning

**Comment by OlsonDev** [comment]
I Googled around for debug icons and the only one I see with a dot at the beginning is with PyCharm:

![image](https://cloud.githubusercontent.com/assets/308072/13790931/af596732-eab8-11e5-84c7-e7e4e01e25a1.png)

I'd argue PyCharm has the least intuitive debugging icons of any IDE I've seen...

I'm quite curious why the one @CoDEmanX suggested won't suffice.
