### ISSUE TITLE
Site search improvements?

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1031]
Some things which would be useful: 
- [ ] Linkable search terms, eg. https://materialdesignicons.com/#chart
- [ ] Multi-term search, eg. chart, line
- [ ] Not operation, eg. chart, !bar

**Comment by Templarian** [comment]
I refactored a lot of the site over the weekend (and updated every single library after a year). There were a lot of changes required to make everything work after the library updates.

It looks like search is pretty broken right now. I'm going to get this resolved tonight or tomorrow.

**Comment by Templarian** [comment]
I fixed the search speed a little bit. Now it's back to about the same performance as seen before the upgrade. Will need to get the rest of the features in though.

**Comment by JamesCoyle** [comment]
We also talked a while ago about categories to help make icons easier to find though ran into issues with how it would be implemented. The tag system is probably the best way to handle it though it feels like many icons haven't been tagged and there are tags missing. The current tag ui is also pretty hard to search through. 

I feel like the existing system needs some work. It has worked great up to this point but now there are so many icons it seems like it isn't really coping that well. I know it often takes me at least 10 minutes to find a particular icon as its hard to search for without knowing its name and I can't be sure the tags are accurate and will show it. 

A system which incorporates major categories such as 'Logos/Branding', 'Form Elements' etc would be useful. These would be major groups of icons that encompass a particular theme. Then there would also be standard tags below which act to group similar icons such as the battery icons or phone icons.

Both categories and tags would function in the same way but would be separate in the UI for clarity. Categories just act like tags attached to many icons. When clicked, a tag would be added to the list of filters. 

This system keeps all of the icons together alphabetically but allows for quickly removing icons which are not relevant. When a new icon is added to the database (however you store them) it would need to be categorized as one of the categories. It can also be added to one of the tags if it makes sense to do so.

**Comment by JamesCoyle** [comment]
@Templarian I've had some more thoughts about this issue and one thing which would help is to pull out certain icon groups into categories. I know consensus was against this but for some icons it really makes sense to do so. 

You have many icons which are named [type]-[variant] such as weather-sunset or folder-image. I think it would be much more logical to put these in groups so they are easier to locate. I would personally add groups to the top of the icon list which have a heading like 'Folder' and have all of the related icons in it. Then icons not placed in these groups will show as normal underneath them.
