### ISSUE TITLE
sort-variant-lock

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#1033]
Some programmes allow users to sort/order a list of items manually, but lock this option because it prevents the user to accidentally mess up. A 'sort lock' would be a nice toggle button, combining Google's [sort icon](https://design.google.com/icons/#ic_sort) with a lock ([similar to Pencil lock by Cody](https://materialdesignicons.com/icon/pencil-lock))

**Comment by infanf** [comment]
![sort-variant-lock](https://cloud.githubusercontent.com/assets/8826710/13034498/3da13004-d337-11e5-92bf-8c8a9fb7756f.png) ![sort-variant-lock-48](https://cloud.githubusercontent.com/assets/8826710/13034499/3da249d0-d337-11e5-9c99-76bcc50e11c6.png) ![sort-variant-lock-96](https://cloud.githubusercontent.com/assets/8826710/13034500/3da45036-d337-11e5-9c1c-0fb23081e0fd.png)
[sort-variant-lock.svg.zip](https://github.com/Templarian/MaterialDesign/files/129736/sort-variant-lock.svg.zip)

**Comment by keunes** [comment]
Nice. Just figured that to work as a toggle, two different states would be needed. As (if I'm not mistaken) the padding is slightly different from Google's, those two don't work together.
In the app I wanted to propose it to the developers, the currently use an open and closed lock:
![screenshot_2016-02-14-16-41-23-01](https://cloud.githubusercontent.com/assets/11229646/13034652/ad4645c6-d33b-11e5-8d1c-18600b458d91.jpeg)
![screenshot_2016-02-14-16-41-32-01](https://cloud.githubusercontent.com/assets/11229646/13034653/bba0d3b6-d33b-11e5-849e-4043be22a3d9.jpeg)

**Comment by Templarian** [comment]
[![sort-variant-lock](https://materialdesignicons.com/icon/sort-variant-lock)](https://materialdesignicons.com/icon/sort-variant-lock) [![sort-variant-lock-open](https://materialdesignicons.com/icon/sort-variant-lock-open)](https://materialdesignicons.com/icon/sort-variant-lock-open)

We've since standardized the lock modifier to a more material look.
