### ISSUE TITLE
Simple PC Component Icons?

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1034]
It would be kinda useful to have some basic icons for parts of a PC. Some parts are already done.
- [x] CPU (mdi-memory : looks more processor like to me)
- [x] RAM 
- [ ] GPU
- [ ] PSU
- [ ] SSD
- [x] Hard drive (mdi-harddisk)
- [ ] Motherboard
- [x] Case (mdi-desktop-tower)
- [ ] Case fans
- [ ] CPU cooler
# Some examples

I doubt it will be possible to get this level of detail but some examples of what they could look like.

CPU alternate
![image](https://cloud.githubusercontent.com/assets/10384436/13030865/f1a5c074-d2b0-11e5-9dab-0097d420f348.png)

Motherboard
![image](https://cloud.githubusercontent.com/assets/10384436/13030819/9a8cddfa-d2af-11e5-9782-a9ceb905ec60.png)

GPU & Other PCIE Cards
![image](https://cloud.githubusercontent.com/assets/10384436/13030829/d35df966-d2af-11e5-99c9-ce412702f90d.png)
![image](https://cloud.githubusercontent.com/assets/10384436/13030849/ad49a18e-d2b0-11e5-9e53-22affa3b7275.png)

Case fans (different to the existing fan icon)
![image](https://cloud.githubusercontent.com/assets/10384436/13030839/43d3133e-d2b0-11e5-91c4-7b67e3e0c5c9.png)

Cooler (Case fan with a bit extra)
![image](https://cloud.githubusercontent.com/assets/10384436/13030841/52bb7152-d2b0-11e5-8e97-23f0fb4291c1.png)

Ram
![image](https://cloud.githubusercontent.com/assets/10384436/13030847/a648c3ec-d2b0-11e5-9110-699cbe56d8fa.png)
![image](https://cloud.githubusercontent.com/assets/10384436/13030856/db5f5fb4-d2b0-11e5-805e-e9f61cb0687d.png)

PSU / Power cable
![image](https://cloud.githubusercontent.com/assets/10384436/13030871/20881dc4-d2b1-11e5-9d91-65ab55ec20b7.png)

A 3.5mm audio jack would be a good addition too.

**Comment by CoDEmanX** [comment]
There's already #444 regarding CPU / memory. Maybe we could remove the inner rectangle outline from Google's memory icon to make it more processor like? For memory, there's an Android 6 icon that needs to be added: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-152349331

Regarding PSU: we still need Google's ic_power icon to be merged as part of #420, also see #524.
You may use `power-socket` though:

[![power-socket](https://materialdesignicons.com/icon/power-socket)](https://materialdesignicons.com/icon/power-socket)

**Comment by CoDEmanX** [comment]
Google's icon for RAM is now available:
[![chip](https://materialdesignicons.com/icon/chip)](https://materialdesignicons.com/icon/chip)

**Comment by CoDEmanX** [comment]
SSD is also part of the following requests: #1230 #1078

**Comment by GreenTurtwig** [comment]
Geforce Experience beta had an update a while ago that changed the whole UI to material, along with the design change they even had some of their own "material" icons.  
![puush-linux 2016-08-15 at 04 58 30](https://cloud.githubusercontent.com/assets/15905797/17671817/da65e92a-6310-11e6-859a-344d1a5a9118.png) 
 (Sorry for the bad image, I don't have access to my laptop at the moment so had to use my desktop.)  
  
Personally I don't like their RAM icon, but I'll have a go at re-creating their GPU icon.

**Comment by GreenTurtwig** [comment]
:-)  
[gpu.zip](https://github.com/Templarian/MaterialDesign/files/430534/gpu.zip)

**Comment by Templarian** [comment]
[![gpu](https://materialdesignicons.com/icon/gpu)](https://materialdesignicons.com/icon/gpu)
