### ISSUE TITLE
Quora icon

### ISSUE THREAD

**Issue by juniorrojas** [Templarian/MaterialDesign#1035]
A Quora icon would be a great addition to the social icons in this collection
https://cdn4.iconfinder.com/data/icons/miu-flat-social/60/quora-128.png

**Comment by chrvasile** [comment]
Made two of them:
![quora-brand-circle](https://cloud.githubusercontent.com/assets/17312269/13196330/4b7def62-d7cb-11e5-9514-7a0eaf3a2c1b.png)
![quora-brand-off](https://cloud.githubusercontent.com/assets/17312269/13196331/4cb3ed32-d7cb-11e5-8962-001ab5dcdf8b.png)

And the archive with the SVG files:
[quora-brand.zip](https://github.com/Templarian/MaterialDesign/files/139092/quora-brand.zip)

**Comment by chrvasile** [comment]
Have you seen this @Templarian?

**Comment by goyney** [comment]
Processed submission from @chrvasile:
![image](https://user-images.githubusercontent.com/1015040/48988368-331c1e00-f0f3-11e8-99b0-6510fc82a449.png)
[quora.zip](https://github.com/Templarian/MaterialDesign/files/2613785/quora.zip)

**Comment by Templarian** [comment]
[![quora](https://materialdesignicons.com/icon/quora)](https://materialdesignicons.com/icon/quora)
