### ISSUE TITLE
Compare button is broken on the history page of website

### ISSUE THREAD

**Issue by aziz** [Templarian/MaterialDesign#1037]

**Comment by Templarian** [comment]
Oops, broke in the large site update last weekend. Forgot to test that button. Will be fixed tonight.

**Comment by Templarian** [comment]
May need to clear your cache to see the latest (`ctrl+shift+r`).

Thanks!

**Comment by CoDEmanX** [comment]
It's still broken after dozens of reloads ignoring the cache, but works fine in a private browsing tab. Man I hate Chrome for being extremely persistent and intransigent about cached content. It's really hard to get buggy stuff swept out there...
