### ISSUE TITLE
All

### ISSUE THREAD

**Issue by matthewpull** [Templarian/MaterialDesign#1038]
Very simple icon request: some way of depicting 'all'.

I'm not sure how this would be represented - perhaps some kind of asterisk - but I would like it for an 'All Messages' button for a web app I'm working on.

Thanks!

**Comment by Simran-B** [comment]
Wouldn't a message-multiple icon be a better fit? Otherwise it could be based on the regular expression icon.

**Comment by matthewpull** [comment]
Currently I have 3 sections: Active (with folder-plus), Archive (with archive) and All Messages (with folder). However, I want to break the archive section out into several sub folders, so that users can choose where to file their messages (rather than just a single archive folder for all of them). I want to use the 'folder' icon for each of those, so therefore cannot use it for 'All Messages'. I guess some kind of folder with an asterisk might be more appropriate, as that would keep as the icons as being folders.

What I currently have:
![image](https://cloud.githubusercontent.com/assets/13154300/13074313/b2961068-d49b-11e5-987a-cfb53b794825.png)

What I'll be changing it to:
![image](https://cloud.githubusercontent.com/assets/13154300/13074362/0b6da25a-d49c-11e5-8b04-d496e5e82f1c.png)

**Comment by CoDEmanX** [comment]
What about tray-multiple?
https://github.com/Templarian/MaterialDesign/issues/420#issuecomment-126732936

**Comment by CoDEmanX** [comment]
Maybe folder + multiply, similar to this?

[![multiplication-box](https://materialdesignicons.com/icon/multiplication-box)](https://materialdesignicons.com/icon/multiplication-box)

**Comment by CoDEmanX** [comment]
Doesn't work as well as I hoped it would: ![folder-all](https://cloud.githubusercontent.com/assets/1309249/14768969/d1e7a664-0a4e-11e6-8f1c-530bd8c5b088.png) ![folder-all2](https://cloud.githubusercontent.com/assets/1309249/14768970/d1e80578-0a4e-11e6-9c3b-e6c454085173.png)

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
