### ISSUE TITLE
mdi-account-multiple-minus

### ISSUE THREAD

**Issue by AliceCasari** [Templarian/MaterialDesign#1039]
There are various mdi-account icon, included mdi-account-multiple-plus icon, but there isn't the relative mdi-account-multiple-minus icon.
Is possible to create it?

**Comment by chrvasile** [comment]
Took a quick look at it today, hope this is what you were looking for.
![account-multiple-minus](https://cloud.githubusercontent.com/assets/17312269/13143625/764a1a2c-d645-11e5-8539-781d1ccb5046.png)

SVG file:
[account-multiple-minus.svg.zip](https://github.com/Templarian/MaterialDesign/files/136197/account-multiple-minus.svg.zip)

**Comment by Templarian** [comment]
[![account-multiple-minus](https://materialdesignicons.com/icon/account-multiple-minus)](https://materialdesignicons.com/icon/account-multiple-minus)
