### ISSUE TITLE
Checkered Flag icon request

### ISSUE THREAD

**Issue by six60** [Templarian/MaterialDesign#104]
Hi there, would you please be able to make a Checkered Flag icon? Or if you had a better idea for an icon to represent the end of a game.

Thanks.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/flag-checkered

Like that?

**Comment by six60** [comment]
Yes, that's excellent thank you Austin! 5 hours, wow :)

**Comment by Templarian** [comment]
I also added...

http://materialdesignicons.com/icon/flag-outline
http://materialdesignicons.com/icon/flag-variant
http://materialdesignicons.com/icon/flag-outline-variant

...rarely do I add just one icon. :smirk: 

:notes: hums 250 stock icons left to import :notes:

**Comment by six60** [comment]
Those wavy ones are awesome, would you be able to do a checkered wavy variant? No worries if you don't feel like it, it would be another icon to submit though :P

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/flag-checkered-variant

It didn't turn out that well tbh. I might remove it from the pack, so if you want it download it now.

**Comment by Templarian** [comment]
http://cl.ly/1N27473v090X -> http://materialdesignicons.com/custom

I've deleted this icon as it looks bad. :cry:

**Comment by six60** [comment]
Hey Austin, no worries about that, thanks for trying man :)

**Comment by Yuanruili** [comment]
@Templarian 
Hi, I made another try, pls see if it's ok~
[WavyFlagCheckered.zip](https://github.com/Templarian/MaterialDesign/files/2933549/WavyFlagCheckered.zip)
