### ISSUE TITLE
Contract icon

### ISSUE THREAD

**Issue by avalot** [Templarian/MaterialDesign#1040]
A simple icon for a "contract", ideally a simple shape that can be overlaid with status shapes (checkmark, question mark, 'x' mark, search, plus, etc.). I don't want to just use a generic document icon... any ideas?

**Comment by Simran-B** [comment]
Generic document + pen seems to be common, or a handshake (we already have a request for this).

**Comment by jfoxtail** [comment]
![documentsigned](https://cloud.githubusercontent.com/assets/8354098/14393878/15c6e0e4-fd7e-11e5-879c-2c09c12957b0.png)
![pen](https://cloud.githubusercontent.com/assets/8354098/14393885/1f7aa3c8-fd7e-11e5-9a6a-b34c7c30b0a4.png)

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #2151.
