### ISSUE TITLE
Icon Templates for Sketch

### ISSUE THREAD

**Issue by chrvasile** [Templarian/MaterialDesign#1041]
A quick template for us to be able to create icons in Sketch would be great to have.

**Comment by chrvasile** [comment]
It seems you can use the SVG templates and modify them a bit to fit the 24pxx24px

**Comment by Templarian** [comment]
I'm not a sketch user, but if you want to share your template with others I can put it with the other templates (that's how the Affinity Designer template was added).

**Comment by chrvasile** [comment]
Sure, there you go. This should do it :)

[Material Design Icons Sketch Template.zip](https://github.com/Templarian/MaterialDesign/files/137529/Material.Design.Icons.Sketch.Template.zip)

**Comment by Templarian** [comment]
Template looks great. Will get it added to the new contributor page / custom page.

**Comment by chrvasile** [comment]
Awesome, glad I could help
