### ISSUE TITLE
Becoming a contributor is disabled?

### ISSUE THREAD

**Issue by chrvasile** [Templarian/MaterialDesign#1042]
Is there a reason why becoming a contributor is disabled? I can only add an icon out of the five, and then the other four are still disabled and there is no option for me to add them. Is there something I am doing wrong, or is it just currently not possible to submit new icons?

**Comment by Templarian** [comment]
I'm getting rid of the contributor form (need to replace it with some explanation on how to use GitHub issues). Now that GitHub allows zip files it's easier to just have people submit icons through here (plus it makes it easier for the other contributors to review).

**Comment by chrvasile** [comment]
It makes sense. Will Contributor profiles disappear then? I always felt that there was some pride in that if you submitted many icons to the community.

**Comment by Templarian** [comment]
No, contributor profiles will probably only improve (probably will be featured on the new contributor page also). It's actually my favorite feature. I'm just going to remove the ability for contributors to add icons and edit icons at any time (this has been disabled for like 6 months already). The addition will be they can tag and alias _all_ icons.

Still a lot of random coding and refactoring to get this all ready though. For now I can manually add contributors. If you have some icons attach them and I can get them incorporated.

**Comment by chrvasile** [comment]
I plan on designing icons to answer requests, so I will upload them in different issues, like I did in #1028 and #1039 for instance.

**Comment by Templarian** [comment]
Just 3 more (try some of the harder ones. :smile:).
