### ISSUE TITLE
Webhook icon

### ISSUE THREAD

**Issue by alessandroliveri** [Templarian/MaterialDesign#1043]
Hi,
Is it possible to add a "webhook" icon? 
Something like this one: 
https://www.google.it/search?q=webhook+svg+icon&espv=2&rlz=1C5CHFA_enIT547IT547&biw=1280&bih=597&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjpwdL7r4HLAhVIwA4KHRA4DfAQ_AUIBigB#imgrc=a1te7n1lvHX1pM%3A

**Comment by chrvasile** [comment]
This should do it
![webhook_240](https://cloud.githubusercontent.com/assets/17312269/13172830/824d0798-d6fa-11e5-9ab5-b0849825e051.png)

And the SVG file:
[webhook.svg.zip](https://github.com/Templarian/MaterialDesign/files/137748/webhook.svg.zip)

**Comment by chrvasile** [comment]
@Templarian Does this make it through?

**Comment by Templarian** [comment]
[![webhook](https://materialdesignicons.com/icon/webhook)](https://materialdesignicons.com/icon/webhook)

**Comment by alessandroliveri** [comment]
Thanks!
