### ISSUE TITLE
Turtle Icon

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#1044]
Hi can you add animal icon specifically what i'm looking for is a 'turtle'

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37570588-f28bc2b0-2ac7-11e8-8557-d9a317760cf2.png)![image](https://user-images.githubusercontent.com/18645219/37570598-0a9e30b8-2ac8-11e8-8152-6cb0b6278816.png)
The right one is more recognizable at small size.

[Download link](https://github.com/Templarian/MaterialDesign/files/1823078/icons.zip)

**Comment by GreenTurtwig** [comment]
However the second is a tortoise, not a turtle. :-P

**Comment by CoDEmanX** [comment]
@Croutonix Have you tried adding a shell pattern to the right one? (lines would probably have to less than 2px)

**Comment by Croutonix** [comment]
The icon is already very recogizeable now, it don't see why that would be necessary.

**Comment by Templarian** [comment]
Still need to add tortoise (was just the last icon to get us to 250, so couldn't add 2).

**Comment by Templarian** [comment]
[![tortoise](https://materialdesignicons.com/icon/tortoise)](https://materialdesignicons.com/icon/tortoise)
