### ISSUE TITLE
Icons for Students

### ISSUE THREAD

**Issue by mrfaizanhaider** [Templarian/MaterialDesign#1046]
Modules & there Action Menus

Contacts
	- Create Contact
	- View Contacts
	- View Students
	
Student Programs
	- Create Student Program
	- View Student Programs
	
Admission Applications
	- Create Admission Application
	- View Admission Applications

Visa Applications
	- Create Visa Application
	- View Visa Applications

Accommodations
	- Create Accommodation
	- View Accommodations

Extensions
	- Create Extension
	- View Extensions

Deferments
	- Create Deferment
	- View Deferments
	
Calendar
	- Schedule Meeting 
	- Schedule Call  
	- Create Task  
	- Today

Calls
	- Log Call 
	- View Calls
	
Meetings
	- Schedule Meeting 
	- View Meetings
	
Tasks
	- Create Task
	- View Tasks

Notes
	- Create Note or Attachment
	- View Notes
	
Leads
	- Create Lead
	- View Leads
	
Campaigns
	- Create Campaign (Wizard) 
	- Create Campaign (Classic)
	- View Campaigns
	- View Newsletters
	- Create Email Template
	- View Email Templates
	- View Diagnostics
	
EmailTemplates
	- Create Email Template
	- View Email Templates
	- View My Email
	
Prospects
	- Create Target
	- View Targets
	
ProspectLists
	- Create Target List
	- View Target Lists
	
ew_Library
	- Create Library
	- View Libraries
	
Accounts
	- Create Account
	- View Accounts
	- Providers
	
Products
	- Create Product
	- View Products
	
Contratcs
	- Create Contratc
	- View Contratcs
	
Invoices
	- Create Invoice
	- View Invoices
	
KPI Management
	- Create KPI Management
	- View KPI Management

**Comment by Templarian** [comment]
A lot of these icons exist. Please take a minute to search the open issues and edit your post appropriately. Some of these are very specific and need example icons.

**Comment by Templarian** [comment]
Closing out this issue. Please re-open when more with more details. Thanks.
