### ISSUE TITLE
Off icons

### ISSUE THREAD

**Issue by simkepal** [Templarian/MaterialDesign#1047]
Cup and food off icons

**Comment by chrvasile** [comment]
I think this needs some extra clarification. Maybe find something similar on Google that you can show here?

**Comment by CoDEmanX** [comment]
I think this is meant as "not drinkable" and "not eatable".

**Comment by Templarian** [comment]
[![food-off](https://materialdesignicons.com/icon/food-off)](https://materialdesignicons.com/icon/food-off) [![cup-off](https://materialdesignicons.com/icon/cup-off)](https://materialdesignicons.com/icon/cup-off)
