### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by adibas03** [Templarian/MaterialDesign#1049]
Hi guys,

The google material design icons recently added new icons. https://design.google.com/icons/
What about incorporating them.
Some include: delete-forever, euro-symbol, restore-page, speaker-notes-off ... among others

**Comment by Templarian** [comment]
Duplicate #420.

**Comment by CoDEmanX** [comment]
I already added the 41 new icons to the spreadsheet to keep track of the progress.

**Comment by adibas03** [comment]
Great work, guys
