### ISSUE TITLE
Review Icon

### ISSUE THREAD

**Issue by Darwesh27** [Templarian/MaterialDesign#105]
Could there be any review Icon. i.e Google maps has reviews for different places..

**Comment by Templarian** [comment]
Do you have an example of what you are looking for? A star is most normally used for a review in Material Design.

**Comment by Darwesh27** [comment]
Actually in my case the review only consists of a paragraph. The star is usually used for a rating which is a separate thing in my case and I am using the star for that..  So I wanted to have something different for the text.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/comment-text-outline
