### ISSUE TITLE
flower-poppy

### ISSUE THREAD

**Issue by dstaflund** [Templarian/MaterialDesign#1050]
Hi there,

I am writing an Android app dealing with themes of remembrance and haven't been able to find icons for the following:
- [ ] obit
- [ ] rank
- [ ] poppy

**obit**: The date on which a person died.
I was originally looking for a cross or maybe gravestone but surprisingly couldn't find any icons for these -- except crosses having to do with hospitals, which is not quite the same.

**Rank**: That a person undertook military service.
I thought maybe a badge that you'd see on a soldier's chest.

**Poppy**: That a person died in battle
Not sure -- the image or outline of a poppy is needed.

Does anyone know if these might be available somewhere?  I am not artistically inclined myself, I am afraid.

Thanks,
Darryl

**Comment by CoDEmanX** [comment]
We should definitely add an icon for day of death. A Christian cross probably, although it's not necessarily recognized in areas with another predominant religion. A gravestone (without cross) might look a bit plain and ambiguous (rectangle with rounded corners at the top?)

A rank icon could look similar to:
[![trophy-award](https://materialdesignicons.com/icon/trophy-award)](https://materialdesignicons.com/icon/trophy-award)

Also common:
![Imgur](http://i.imgur.com/F1MMsco.png?1)

Meanwhile, you might wanna use:
[![seal](https://materialdesignicons.com/icon/seal)](https://materialdesignicons.com/icon/seal)

**Comment by Templarian** [comment]
Maybe adding that one as `military-rank-sergeant` would work. I don't think we need to add all the ranks, but still keeping the naming specific. Not sure about the others.

**Comment by CoDEmanX** [comment]
I agree that we shouldn't add all possible ranks (in Battlefield 4, they [have 140](http://battlefield.wikia.com/wiki/Battlefield_4_online_ranks)).

**Comment by OlsonDev** [comment]
What if the gravestone said RIP -- is that recognized internationally?

**Comment by CoDEmanX** [comment]
Hm yeah... I like the idea. But on the other hand, it's an English abbreviation and there are different sepulchral cultures in the world. Plus it makes me remember the classic Duke Nukem quote "Rest in pieces". I would still go for it, and add additional icons as the need arises.

**Comment by dstaflund** [comment]
I like the three-bar'd chevron type icon suggested above for rank -- I could only find the two-bar'd up/down chevrons used to indicate open/close or expand/collapse and it didn't quite look right.  For obit, I don't mind the gravestone idea but I wonder if it would raise connotations of Halloween.

**Comment by OlsonDev** [comment]
I think if the gravestone itself and the font were more "serious" in style, that concern could be squashed. For example, most Halloween clipart gravestones are either gothic themed or shaped how @CoDEmanX describes:

> rectangle with rounded corners at the top

However, what if the gravestone itself was simple/classy in shape?
![image](https://cloud.githubusercontent.com/assets/308072/13369938/ef28b9e4-dcc1-11e5-9393-7afb32d063d9.png)

... or something with more of a shoulder:
![image](https://cloud.githubusercontent.com/assets/308072/13370012/cc81db18-dcc2-11e5-877f-17ae60922b93.png)

Vectorized it may not be clear the shape is a gravestone but the "RIP" will drive the point home. Also, going with a wider/squattier stone, it should accommodate the text a little better.

Google Image searching "gravestone styles" yields good ideas.

**Comment by PeterShaggyNoble** [comment]
Rank is covered in #1083 and gravestone in #1559

Renaming this and leaving it open as a request for a poppy icon.

**Comment by Alekhen** [comment]
I took a stab at designing a poppy. What do you guys think of these? We probably don't need both in the library, just one.

[poppy.svg.zip](https://github.com/Templarian/MaterialDesign/files/1884799/poppy.svg.zip)
[poppy-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/1884798/poppy-variant.svg.zip)

![poppy](https://user-images.githubusercontent.com/1837101/38432560-11c44848-3985-11e8-94ca-65df5a6ed76d.png)

![poppy-variant](https://user-images.githubusercontent.com/1837101/38432566-156eeca0-3985-11e8-84e0-cdef70ece28f.png)

**Comment by dstaflund** [comment]
I like the first one -- it looks great.
Darryl
On 4/6/2018 at 10:27 AM, "Colton James Wiscombe"  wrote:

	I took a stab at designing a poppy. What do you guys think of these?
We probably don't need both in the library, just one. 

	poppy.svg.zip
 poppy-variant.svg.zip

**Comment by PeterShaggyNoble** [comment]
Of those 2, my vote goes to the second.

**Comment by CoDEmanX** [comment]
The left one needs a heavier notch to make it work at 24px IMO, can you try that? @Alekhen

**Comment by Alekhen** [comment]
How about this?
![poppy-24](https://user-images.githubusercontent.com/1837101/39138493-4775de7e-46dd-11e8-8e53-1815999c7002.png)
![poppy-lrg](https://user-images.githubusercontent.com/1837101/39138497-4930ca6c-46dd-11e8-95c6-ceef6ddf1723.png)
[poppy.svg.zip](https://github.com/Templarian/MaterialDesign/files/1939069/poppy.svg.zip)

**Comment by PeterShaggyNoble** [comment]
That one looks more like a buttercup to me; still think `poppy-variant` above is the best option so far.

**Comment by CoDEmanX** [comment]
The 24px preview looks odd. It looks better in this:

![grafik](https://user-images.githubusercontent.com/1309249/39236097-084ad7a8-4878-11e8-9397-2926c14a92e9.png)

But I agree, poppy-variant works better.

**Comment by Templarian** [comment]
I'm leaning toward the last one. The other's don't look quite right at 1:1 size.

[![flower-poppy](https://materialdesignicons.com/icon/flower-poppy)](https://materialdesignicons.com/icon/flower-poppy)
