### ISSUE TITLE
Brewery Icon

### ISSUE THREAD

**Issue by mikejones3** [Templarian/MaterialDesign#1051]
For all the awesome craft beer apps, we need a brewery icon and other beer related icons

**Comment by Templarian** [comment]
This might be related to issue #159. Do you have an example of what a brewery icon would look like. Due to the small size restrictions I'm not exactly sure what this would look like.

**Comment by Templarian** [comment]
I'm still not sure what this icon would be. Maybe use the [factory](https://materialdesignicons.com/icon/factory) icon?

Closing the issue. If anyone thinks of anything please comment/reopen the issue.

**Comment by mikejones3** [comment]
I would say a building with the big tanks next to it or coming out of it, kinda like this:

http://www.gunaxin.com/wp-content/uploads/2013/05/Dogfish-Head.jpg
