### ISSUE TITLE
Auto focus camera [AF]

### ISSUE THREAD

**Issue by smitt522** [Templarian/MaterialDesign#1053]
1. camera-focus-auto
2. camera-focus-auto-off

Example:
![Example icon 1](http://previews.123rf.com/images/blankstock/blankstock1409/blankstock140905581/31709892-Autofocus-photo-camera-sign-icon-AF-Settings-symbol-Circle-flat-button-with-shadow-Modern-UI-website-Stock-Photo.jpg)
![Example icon 2](https://www.colourbox.com/preview/11100607-autofocus-zone-sign-icon-photo-camera-settings.jpg)

**Comment by CoDEmanX** [comment]
We are missing focus strong by Google: https://design.google.com/icons/#ic_center_focus_strong (tracked in #420)

Aside from that, here are some additional creations of mine:

![account-focus](https://cloud.githubusercontent.com/assets/1309249/13229064/5f168086-d99f-11e5-8ad3-711c5bcefbbf.png) ![account-focus2](https://cloud.githubusercontent.com/assets/1309249/13229063/5f163ed2-d99f-11e5-9c20-1a019a6ff21d.png) ![account-focus3](https://cloud.githubusercontent.com/assets/1309249/13229067/5f1aa404-d99f-11e5-9a37-3d446a711f10.png) face tracking
![auto-focus2](https://cloud.githubusercontent.com/assets/1309249/13229065/5f1713d4-d99f-11e5-9a78-b2f85941c6af.png) ![auto-focus3](https://cloud.githubusercontent.com/assets/1309249/13229068/5f1b2d52-d99f-11e5-83ee-5d1859210085.png) auto-focus
![focus-area](https://cloud.githubusercontent.com/assets/1309249/13229069/5f2ceb1e-d99f-11e5-8b59-ea6baf653784.png) ![auto-focus](https://cloud.githubusercontent.com/assets/1309249/13229066/5f175268-d99f-11e5-94ca-de71fb5d4d93.png) focus area
![focus-field](https://cloud.githubusercontent.com/assets/1309249/13229070/5f2d3808-d99f-11e5-9903-236806b7472e.png) focus field (multi-point)
![focus-horizontal](https://cloud.githubusercontent.com/assets/1309249/13229073/5f337114-d99f-11e5-849f-f10ca0c620fa.png) ![focus-vertical](https://cloud.githubusercontent.com/assets/1309249/13229077/5f4b950a-d99f-11e5-9eeb-5b1379237f77.png) focus horizontal/vertical field
![focus-target](https://cloud.githubusercontent.com/assets/1309249/13229071/5f2eedec-d99f-11e5-9fc1-b8f3357230cd.png) ![focus-target2](https://cloud.githubusercontent.com/assets/1309249/13229074/5f36664e-d99f-11e5-82ed-c98d5e149a74.png) ![focus-target3](https://cloud.githubusercontent.com/assets/1309249/13229072/5f322f0c-d99f-11e5-90b6-d731820f9d1e.png) ![focus-target4](https://cloud.githubusercontent.com/assets/1309249/13229075/5f441334-d99f-11e5-943a-1658664449cf.png) focus target / spot / point
![focus-tracking](https://cloud.githubusercontent.com/assets/1309249/13229076/5f46a4be-d99f-11e5-99ff-51247da89011.png) ![focus-tracking2](https://cloud.githubusercontent.com/assets/1309249/13229078/5f4bdcfe-d99f-11e5-923e-d33a160ee672.png) focus tracking

**Comment by Templarian** [comment]
- [ ] `face-tracking` 3rd?
- [ ] `body-tracking` (1st from the first group)
- [ ] `auto-focus` 2nd? R = A in the first.
- [ ] `focus-area` 2nd
- [ ] `focus-field` yes
- [ ] `focus-horizontal-field`
- [ ] `focus-vertical-field` yes
- [ ] `focus-target` 4th. Could also be a simple circle in the center maybe.
- [ ] `focus-tracking` 2nd.

**Comment by CoDEmanX** [comment]
face-tracking could also be depicted with an actual face (smiley, or better https://design.google.com/icons/#ic_face), but I think it would have a bit too much details for MD. 3rd is probably the best.

Is there such a thing as **body** tracking? Maybe use it as icon for motion tracking? The human shape could use some fine-tuning, as in making it a bit taller/larger (1-2 px).

As for auto-focus, we should also try Roboto as font. Especially the A is likely easier to read.

Only the corners and a dot would be hardly distinguishable from https://materialdesignicons.com/icon/image-filter-center-focus I figure?

**Comment by CoDEmanX** [comment]
![account-focus1](https://cloud.githubusercontent.com/assets/1309249/13249763/6d3f7744-da26-11e5-9c93-04652109d8a0.png) ![account-focus4](https://cloud.githubusercontent.com/assets/1309249/13249764/6d40925a-da26-11e5-8c82-f40ad478dda6.png) better centered than earlier versions
![account-focus5](https://cloud.githubusercontent.com/assets/1309249/13249762/6d3e3564-da26-11e5-8a61-a39f56195f96.png) too much details as I expected
![auto-focus4](https://cloud.githubusercontent.com/assets/1309249/13249761/6d3dcffc-da26-11e5-8174-2b932facf425.png) actually a bit hard to read...
![focus-target5](https://cloud.githubusercontent.com/assets/1309249/13249760/6d3dcf2a-da26-11e5-8c66-3121c3967995.png) not that bad actually, although you might miss the tiny circle if the icon is used as overlay...
![focus-target6](https://cloud.githubusercontent.com/assets/1309249/13249759/6d3dc570-da26-11e5-9401-b8adb3add803.png) also-ran...

**Comment by mkosik** [comment]
in addition to face detection icon, I put together an icon for face recognition (not just detection & tracking), when the face is recognized
it might be a little complicated, any suggestions are wellcome
![ic_face_detection](https://cloud.githubusercontent.com/assets/2512454/14573294/758b6ee2-0354-11e6-9bdf-b3ec186b2e6b.png)
![ic_face_detected](https://cloud.githubusercontent.com/assets/2512454/14573297/78c43918-0354-11e6-8b01-6bb9b21fb477.png)

**Comment by CoDEmanX** [comment]
@mkosik: Can you provide your icons in SVG format?

**Comment by mkosik** [comment]
sure. sorry, there's no support for directly uploading SVGs on github, so here's a zip.
[face-detection.zip](https://github.com/Templarian/MaterialDesign/files/233457/face-detection.zip)

**Comment by MrGrigri** [comment]
There is also #3074

**Comment by goyney** [comment]
`image-filter-center-focus-strong` and `image-filter-center-focus-strong-outline` from Google were added. Face recognition was added in #3074.

Looks like all we need is a decision on which auto-focus icon to add. @CoDEmanX can you pick your best one and share it so we can discuss/add it. 😄

**Comment by goyney** [comment]
[![focus-auto](https://materialdesignicons.com/icon/focus-auto)](https://materialdesignicons.com/icon/focus-auto)[![focus-field](https://materialdesignicons.com/icon/focus-field)](https://materialdesignicons.com/icon/focus-field)
[![focus-field-horizontal](https://materialdesignicons.com/icon/focus-field-horizontal)](https://materialdesignicons.com/icon/focus-field-horizontal)[![focus-field-vertical](https://materialdesignicons.com/icon/focus-field-vertical)](https://materialdesignicons.com/icon/focus-field-vertical)

Coupled with the `image-filter-*` icons from Google, I think we hit everything here. If not, open up a new issue. 😄

**Comment by CoDEmanX** [comment]
@goyney What seems to be missing is the face tracking icons. Do we want to add any?

**Comment by goyney** [comment]
You mean like ‘face-recognition’?
[![face-recognition](https://materialdesignicons.com/icon/face-recognition)](https://materialdesignicons.com/icon/face-recognition)

**Comment by CoDEmanX** [comment]
Ah, that should suffice. Unless we want a separate "smile" detection icon.
