### ISSUE TITLE
Landing and Departure icons

### ISSUE THREAD

**Issue by aziz** [Templarian/MaterialDesign#1054]
![screen shot 2016-02-22 at 5 30 13 pm](https://cloud.githubusercontent.com/assets/3202/13224694/ffae00c0-d989-11e5-8e60-951d7816b9ad.png)
![screen shot 2016-02-22 at 5 30 25 pm](https://cloud.githubusercontent.com/assets/3202/13224693/ffac50a4-d989-11e5-84d1-a35fd23700f8.png)

**Comment by CoDEmanX** [comment]
Tracked in #420, rows 70 and 71 in the spreadsheet. Leaving this open as reminder.

**Comment by Templarian** [comment]
[![airplane-takeoff](https://materialdesignicons.com/icon/airplane-takeoff)](https://materialdesignicons.com/icon/airplane-takeoff) [![airplane-landing](https://materialdesignicons.com/icon/airplane-landing)](https://materialdesignicons.com/icon/airplane-landing)
