### ISSUE TITLE
rename icon without box 

### ISSUE THREAD

**Issue by xaviergonz** [Templarian/MaterialDesign#1055]
like the rename-box icon but without the box

**Comment by Templarian** [comment]
You may like the new https://materialdesignicons.com/icon/textbox icon that was added the other day.

I kind of want to ironically rename that `rename-box` icon to something else. It's more a writing icon. `writing`/`writing-box`.

**Comment by xaviergonz** [comment]
Ah, that one is even better :D Thank you
