### ISSUE TITLE
Need a template or prototype icon

### ISSUE THREAD

**Issue by jenious** [Templarian/MaterialDesign#1058]
Couldn't find anything in the existing list to stand for a template or prototype, which would be a version of a document that you could copy to modify.  Does anyone have any suggestions?

**Comment by CoDEmanX** [comment]
A dashed version of file-outline as template icon maybe?

[![file-outline](https://materialdesignicons.com/icon/file-outline)](https://materialdesignicons.com/icon/file-outline)

There is actually an icon `file-hidden` in the repository, but I can't find it on the website?! @Templarian 

![file-hidden](https://cloud.githubusercontent.com/assets/1309249/13256811/80aadc12-da4c-11e5-82f1-920f19561126.png)

**Comment by Templarian** [comment]
Hmm... not sure why the hidden icon isn't in there. Maybe I thought I added it after creating it. Will add it in.

**Comment by jenious** [comment]
Good suggestion - thanks!!

**Comment by jenious** [comment]
@templarian Could you please let me know when you've had a chance to upload the file-hidden icon?  Thanks!

**Comment by Templarian** [comment]
Maybe.

[![file-hidden](https://materialdesignicons.com/icon/file-hidden)](https://materialdesignicons.com/icon/file-hidden)

**Comment by jenious** [comment]
Thanks!
