### ISSUE TITLE
Icons for Git/hub actions

### ISSUE THREAD

**Issue by skamansam** [Templarian/MaterialDesign#1059]
I use Atom for all my coding, and I really like the flex-tool-bar plugin. As such, I would like material icons for all the git actions I use:
- [x] open-on-github:history [oct `history`](https://octicons.github.com/icon/history/) [MDI `history`](https://materialdesignicons.com/icon/history) Alias: `git-history`
- [ ] open-on-github:blame Alias: `git-blame`
- [ ] open-on-github:repository Alias: `git-repository`
- [x] open-on-github:issues [MDI `alert-circle-outline`](https://materialdesignicons.com/icon/alert-circle-outline) Alias: `git-issue`
- [x] open-on-github:file [MDI `file`](https://materialdesignicons.com/icon/file)
- [ ] open-on-github:branch-compare 
- [ ] git-compare [oct `git-compare`](https://octicons.github.com/icon/git-compare/)
- [ ] git-plus:commit
- [ ] git-blame:toggle
- [ ] git-plus:menu
- [ ] git-diff [oct `diff`](https://octicons.github.com/icon/diff/) `source-diff`

View Octicons: https://octicons.github.com/

**Comment by CoDEmanX** [comment]
Please post example icons for them.

**Comment by Templarian** [comment]
@skamansam I would like to get these added. If you could paste examples of each we can start creating them.

**Comment by JamesCoyle** [comment]
We already have: 

**History**
[![history](https://materialdesignicons.com/icon/history)](https://materialdesignicons.com/icon/history)

**Issue**
[![alert-circle-outline](https://materialdesignicons.com/icon/alert-circle-outline)](https://materialdesignicons.com/icon/alert-circle-outline)

**File**
[![file](https://materialdesignicons.com/icon/file)](https://materialdesignicons.com/icon/file)

**Repository**
[![book](https://materialdesignicons.com/icon/book)](https://materialdesignicons.com/icon/book)
Several variants of book are also available

We should add:
https://octicons.github.com/icon/git-branch/
https://octicons.github.com/icon/git-commit/
https://octicons.github.com/icon/git-compare/
https://octicons.github.com/icon/git-merge/
https://octicons.github.com/icon/git-pull-request/

But we need examples of `git-plus:menu`, `git-blame:toggle`, and `open-on-github:blame`. I'm not really sure what they should look like. You may find suitable icons are already available under different names. 

This reminds me. I really should update the tool-bar package with the latest version of MDI...

**Comment by Templarian** [comment]
A few of these exist (I've edited the issue above to include links to them and to the octicons). We should alias them `git-*`.

https://materialdesignicons.com/source-branch
https://materialdesignicons.com/source-merge
https://materialdesignicons.com/source-pull

**Comment by CoDEmanX** [comment]
There is also `radar`, which Google calls "track changes".
`delta` is also related, so is this contribution: https://github.com/Templarian/MaterialDesign/issues/1190#issuecomment-213414538

**Comment by CoDEmanX** [comment]
There is also `radar`, which Google calls "track changes".
`delta` is also related, so is this contribution: https://github.com/Templarian/MaterialDesign/issues/1190#issuecomment-213414538 (file compare /diff)

**Comment by JamesCoyle** [comment]
Closing this out as we now have a full set of `source-` icons as well as others that should mostly meet the requirements of this issue. If there is anything missing please open a new issue for each icon and provide example images so we can better track the progress.
