### ISSUE TITLE
Need Circle Plus and Circle minus icon

### ISSUE THREAD

**Issue by ananthpnj** [Templarian/MaterialDesign#1060]
Need Circle Plus and Circle minus icon

**Comment by CoDEmanX** [comment]
Do you mean these?

[![plus-circle-outline](https://materialdesignicons.com/icon/plus-circle-outline)](https://materialdesignicons.com/icon/plus-circle-outline) [![minus-circle-outline](https://materialdesignicons.com/icon/minus-circle-outline)](https://materialdesignicons.com/icon/minus-circle-outline)
[![plus-circle](https://materialdesignicons.com/icon/plus-circle)](https://materialdesignicons.com/icon/plus-circle) [![minus-circle](https://materialdesignicons.com/icon/minus-circle)](https://materialdesignicons.com/icon/minus-circle)

**Comment by ananthpnj** [comment]
ya that's one., thanks for your mail
