### ISSUE TITLE
The qq icon for China uers

### ISSUE THREAD

**Issue by MKFMIKU** [Templarian/MaterialDesign#1061]
![](http://i11.tietuku.com/0f6b001f73801bc3.jpg)
If you can add it, I think it will be helpful for many china users

**Comment by CoDEmanX** [comment]
> Tencent QQ is a Chinese **instant messaging** software service. QQ also offers a variety of services, including online social games, music, shopping, microblogging, movies, platform of games and group and voice chat.
>
> As of January 2015, there are 829 million active QQ accounts, with a peak of 176.4 million simultaneous online QQ users.

**Comment by Templarian** [comment]
I rejected this already once in #926. I'm okay adding it, but there is a lot of detail for a 20x20 icon area.

**Comment by MKFMIKU** [comment]
![qq 20160225084812](https://cloud.githubusercontent.com/assets/13622651/13306191/86c6c3a8-db9c-11e5-980e-f46096511f3d.jpg)
I think you could use it.

**Comment by Templarian** [comment]
[![qqchat](https://materialdesignicons.com/icon/qqchat)](https://materialdesignicons.com/icon/qqchat)
