### ISSUE TITLE
Broken cellphone

### ISSUE THREAD

**Issue by walker93** [Templarian/MaterialDesign#1062]
There are a lot of icons for cellphones, and it's ok, but I miss a broken cellphone icon.

**Comment by CoDEmanX** [comment]
Cellphone like the basic phone, or smartphone? Simply an off-version with a diagonal stroke?

**Comment by walker93** [comment]
Yeah, one for basic phone and one for smartphone would be great!

**Comment by marcbachmann** [comment]
I have no idea how to commit in here. So here is one.

```
<svg viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg">
    <path d="M6,8.27 L6,20.5 C6,21.8807119 7.11928813,23 8.5,23 L16.5,23 C17.6460222,23 18.6119397,22.2288802 18.9071966,21.1771966 L20.73,23 L22,21.72 L3.28,3 L2,4.27 L6,8.27 Z M15.73,18 L8,18 L8,10.27 L15.73,18 Z M6,3.592 L6,3.5 C6,2.11928813 7.11928813,1 8.5,1 L16.5,1 L16.5,1 C17.8807119,1 19,2.11928813 19,3.5 L19,16.592 L17,14.592 L17,4 L8,4 L8,5.592 L6,3.592 Z M12.5,22 C11.6715729,22 11,21.3284271 11,20.5 C11,19.6715729 11.6715729,19 12.5,19 C13.3284271,19 14,19.6715729 14,20.5 C14,21.3284271 13.3284271,22 12.5,22 Z"></path>
</svg>
```
![cellphone-iphone-off](https://cloud.githubusercontent.com/assets/431376/18838757/dc973118-8408-11e6-9b44-e29a1cb2e96f.png)

**Comment by CoDEmanX** [comment]
marc's icon is a good way to symbolize "no phones allowed" (i.e. no phone calls in cinema etc.)

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #3164
