### ISSUE TITLE
Error rendering mdi's while using columns

### ISSUE THREAD

**Issue by lomefin** [Templarian/MaterialDesign#1063]
I'm using bootstrap's .card-column which sets column-count: 3

When using this mode, and having an icon being shown at the second or later columns, they just don't appear. They are just missing. Sometimes, resizing the window I can get to see the icon or part of it.

This happens even if I wrap a different element (example: `<p class="mdi">Hello</p>`) just to check, and the content also "disappears".

**Comment by Templarian** [comment]
Can you post a codepen that replicates this?

Thanks!

**Comment by Templarian** [comment]
If someone can replicate this in a codepen please comment and I'll address the issue. For now I'm going to close the issue.
