### ISSUE TITLE
caduceus icon

### ISSUE THREAD

**Issue by AlexSchaeffer** [Templarian/MaterialDesign#1066]

**Comment by CoDEmanX** [comment]
Way too many details I'm afraid:

![images](https://cloud.githubusercontent.com/assets/1309249/13567571/47de7398-e45c-11e5-88f9-bc66d7c5aff9.png)

Perhaps the stethoscope works for your use case?

[![stethoscope](https://materialdesignicons.com/icon/stethoscope)](https://materialdesignicons.com/icon/stethoscope)

**Comment by PeterShaggyNoble** [comment]
Closing for the reason above.
