### ISSUE TITLE
task icons

### ISSUE THREAD

**Issue by lauff** [Templarian/MaterialDesign#1067]
for task, new task, completed task

**Comment by CoDEmanX** [comment]
Did you see the `clipboard` icons? There are multiple generic versions and a completed version. There is none so far for adding however.

@Templarian: How do you feel about adding the following?


![clipboard-outline-plus](https://cloud.githubusercontent.com/assets/1309249/13394355/30406a76-dee8-11e5-8b95-2a4474a9579f.png) ![clipboard-outline-minus](https://cloud.githubusercontent.com/assets/1309249/13394356/3040ea64-dee8-11e5-83ba-297313a3cc79.png) ![clipboard-outline-remove](https://cloud.githubusercontent.com/assets/1309249/13394354/30403f1a-dee8-11e5-9e17-a43b69d0a6f9.png) ![clipboard-outline-alert](https://cloud.githubusercontent.com/assets/1309249/13394351/303f9bf0-dee8-11e5-8f10-bf1800171d80.png) ![clipboard-outline-check](https://cloud.githubusercontent.com/assets/1309249/13394353/303fed6c-dee8-11e5-9421-ff5f1ebc5a9a.png) ![clipboard-outline-text](https://cloud.githubusercontent.com/assets/1309249/13394357/30597aac-dee8-11e5-987d-fe430099525a.png)
![clipboard-plus](https://cloud.githubusercontent.com/assets/1309249/13394359/305dabcc-dee8-11e5-94a9-672535fb807b.png) ![clipboard-minus](https://cloud.githubusercontent.com/assets/1309249/13394352/303fba18-dee8-11e5-8ccb-624724a54ab3.png) ![clipboard-remove](https://cloud.githubusercontent.com/assets/1309249/13394358/305a338e-dee8-11e5-9600-f99c22ab4666.png)

**Comment by Templarian** [comment]
I like the check outline (not a huge fan of the alert outline, but I don't think we can do better with the size constraints) and the `x` ones and maybe the text, but I think it is too specific to have a +/- for the clipboard.

Might just be me overthinking it though. It could get a little overkill having a +/- variant for every noun.

**Comment by CoDEmanX** [comment]
@Templarian Still want to add the check outline clipboard?

**Comment by Templarian** [comment]
@CoDEmanX Yea, we should probably add that one.

**Comment by JamesCoyle** [comment]
[clipboard-check-outline.zip](https://github.com/Templarian/MaterialDesign/files/1815137/clipboard-check-outline.zip)

How are those two? The original check mark on the filled icon didn't fit in the outline variant so I redid it.

**Comment by CoDEmanX** [comment]
clipboard-check-outline LGTM!

**Comment by JamesCoyle** [comment]
I'm not sure about the clipboard check icon as the check looks a bit small. I think I prefer it to be consistent with the outline variant though.

**Comment by CoDEmanX** [comment]
To use it as toggle? If it's a subtle change between both variants, then I wouldn't really care.

**Comment by CoDEmanX** [comment]
![unbenannt-1](https://user-images.githubusercontent.com/1309249/37465639-004a08bc-285c-11e8-987f-230787187ee4.gif) ![unbenannt-2](https://user-images.githubusercontent.com/1309249/37465694-1f8da58a-285c-11e8-8a19-b11c089a333b.gif)

**Comment by Templarian** [comment]
[![clipboard-check-outline](https://materialdesignicons.com/icon/clipboard-check-outline)](https://materialdesignicons.com/icon/clipboard-check-outline)
