### ISSUE TITLE
temple icon

### ISSUE THREAD

**Issue by romils1994** [Templarian/MaterialDesign#1070]

**Comment by CoDEmanX** [comment]
Greek temples seem to be common, like in

[![bank](https://materialdesignicons.com/icon/bank)](https://materialdesignicons.com/icon/bank)

Would be nice to have something else, like a Mayan temple.

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #1135 as it's not clear what sort of temple is being requested here.

**Comment by rshah1994** [comment]
Something similar to a hindu temple. Like a triangular flag on a Hut kind of structure.
