### ISSUE TITLE
Material Icons

### ISSUE THREAD

**Issue by melvinsalas** [Templarian/MaterialDesign#1071]
Material icons are beautifully crafted, delightful, and easy to use in your web, Android, and iOS projects. Please, add it.

[https://design.google.com/icons/index.html](https://design.google.com/icons/index.html)

**Comment by Templarian** [comment]
Duplicate #420.

**Comment by CoDEmanX** [comment]
This is a weird issue...

**Comment by Templarian** [comment]
:laughing:
