### ISSUE TITLE
Suggest icon: bridge

### ISSUE THREAD

**Issue by choxnox** [Templarian/MaterialDesign#1072]
Bridge as in a structure which people use to cross rivers or canyons.

**Comment by CoDEmanX** [comment]
It's part of #873 and I even posted an icon I created. Still waiting for feedback.

**Comment by choxnox** [comment]
Yeah, I've seen your post before submitting my suggestion. Let's hope we'll see some traction with this one.

**Comment by chrvasile** [comment]
Maybe this one will have more success?
![bridge](https://cloud.githubusercontent.com/assets/17312269/13672433/122e3974-e6d5-11e5-9eae-7fde25b04eff.png)

[bridge.zip](https://github.com/Templarian/MaterialDesign/files/167295/bridge.zip)

**Comment by Templarian** [comment]
[![bridge](https://materialdesignicons.com/icon/bridge)](https://materialdesignicons.com/icon/bridge)

@chrvasile Thanks for the icon! In the future please delete any extra points and align the points to 2px and not half points (sometimes half points are fine, but a majority of the lines should not be offset).
