### ISSUE TITLE
Suggest few religious icons

### ISSUE THREAD

**Issue by choxnox** [Templarian/MaterialDesign#1074]
We already have a `church` icon which is nice but we also need icons for other major religions.

### Islam

`mosque` icon such as:

<img src="https://cloud.githubusercontent.com/assets/1287099/13455876/60707a5a-e060-11e5-867c-f21543b0402d.png" width="64"> <img src="https://cdn4.iconfinder.com/data/icons/eldorado-building/40/mosque-512.png" width="64"> <img src="http://icons.iconarchive.com/icons/icons8/windows-8/512/Cultures-Mosque-icon.png" width="64">

`islamic` icon such as:

<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/1296-200.png" width="64">

### Judaism

`synagogue` icon such as:

<img src="https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/synagogue.png" width="64"> <img src="http://cache1.asset-cache.net/gc/489958618-synagogue-icon-flat-graphic-design-gettyimages.jpg?v=1&c=IWSAsset&k=2&d=4pQYavIoj4YuXqdskytwXUNaPdGdLPT2MgezAH3DLDLhm%2BEdTRxfOQqiHHFW1viJtUUF6R%2Fzus6TSf5sXxNvhg%3D%3D" width="128">

`jewish` icon such as:

<img src="https://image.freepik.com/free-icon/star-jewish-david_318-28592.jpg" width="64">

### Catholicism

We already have a `church` icon.

`catholic` icon such as:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/8/87/Christian_cross.svg/2000px-Christian_cross.svg.png" width="64">

### Orthodox

We already have a `church` icon.

`orthodox` icon such as:

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Orthodox_cross.svg/2000px-Orthodox_cross.svg.png" width="64">

**Comment by bradlis7** [comment]
Related to #259 

An ixthus (fish) icon would be nice.

![Ixthus](https://38.media.tumblr.com/avatar_5cb7490cac2e_64.png)

A cross isn't really specific to catholicism. maybe just religious-cross or christian-cross? I don't see a point in a separate orthodox cross myself, but maybe others do.

**Comment by zuck** [comment]
An `yin-yang` icon is already here, so I think this is a good suggestion...

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/38784385-1d1b5fea-40df-11e8-869f-5eca5a669baa.png)![image](https://user-images.githubusercontent.com/18645219/38784392-2fcae44e-40df-11e8-9cc8-d95c72c5635c.png)![image](https://user-images.githubusercontent.com/18645219/38784517-e719a6fc-40e0-11e8-83c9-d9a2dadc5662.png)![image](https://user-images.githubusercontent.com/18645219/38784521-f3276f38-40e0-11e8-9b19-df8f40fba281.png)![image](https://user-images.githubusercontent.com/18645219/38784525-054ab1ca-40e1-11e8-86e0-a3d8503d7ea5.png)
I tried judaism with 2px stroke and it doesn't work, the 6 triangle holes are too small.

**Comment by Templarian** [comment]
Awesome work on all of these! Kept all the names, but `christianity`. Most don't say the `ism`.

Also Catholicism/Orthodox being a subset should be good with the standard cross.
