### ISSUE TITLE
IconJar display names not correctly - adding .ijmap file

### ISSUE THREAD

**Issue by skalniak** [Templarian/MaterialDesign#1075]
When importing icons to Icon Jar names displayed are like unicode - it's difficult to filter them and look for right one. IconJar on twitter suggested to adding .ijmap file and that should solve the issue

**Comment by Templarian** [comment]
http://cdn.materialdesignicons.com/1.5.54-dev/ (preview)

http://cdn.materialdesignicons.com/1.5.54-dev/download.zip

I don't actually use icon jar (no Windows app), so let me know if this works or it needs any changes to make it easier to use.

**Comment by skalniak** [comment]
Still not working ![screen shot 2016-03-03 at 11 57 12](https://cloud.githubusercontent.com/assets/17589964/13492230/3770450e-e137-11e5-82f9-bfcf19c055bd.png)

**Comment by daveyheuser** [comment]
Hey, 

One of the guys behind Iconjar here :) I love that you've requested to add a .ijmap file to this icon set.
The reference to the font characters were in uppercase while the ones in the font were in lowercase. Here's the file, maybe you can verify if it works; http://d.pr/f/Cy4v

**Comment by skalniak** [comment]
Whoo hoo it works :dancers: :smiley:  
I wanted to look into .ijmap file and creaty it during the weekend but @Templarian was faster. I love you guys for such a fast reaction :heart: 

So @Templarian can you add .jimap file form @daveyheuser to package when you download the icon package?

![screen shot 2016-03-03 at 17 08 29](https://cloud.githubusercontent.com/assets/17589964/13500382/99e7864a-e162-11e5-86f7-7308819e1d15.png)

**Comment by Templarian** [comment]
Yea, on my side it was 5 lines of code to generate the file. :smile: and it's been on my todo list for a while (but had to wait until the fixed code points for each glyph was fixed). I'll fix the download above with this fix *tonight* and update this issue.

The official 1.5.54 release will not be out until this weekend after further testing. The webfont releases will not contain the `.ijmap`, but I'm going to be creating a designer focused font download (this will eventually update more regularly eventually 1:1 matching the sites icons as they are added/updated).

**Comment by Templarian** [comment]
@daveyheuser Thanks by the way for the really quick response! Awesome application (never actually used it, just heard good things).

**Comment by Templarian** [comment]
@skalniak [MaterialDesignIconsDesign.zip](http://cdn.materialdesignicons.com/1.5.54-dev/MaterialDesignIconsDesign.zip)

This is currently the official designer download. It includes all the SVG files also, but please test the font with the .ijmap. Thanks!

**Comment by Templarian** [comment]
https://materialdesignicons.com/design

The latest can be downloaded above from now on.
