### ISSUE TITLE
Suggest icon: IC chip pcb

### ISSUE THREAD

**Issue by lwrbakro** [Templarian/MaterialDesign#1077]
IC/chip
eg. https://image.freepik.com/free-icon/ic--integrated-circuit--michrochip--ios-7-symbol_318-39174.jpg

pcb
eg. http://us.123rf.com/450wm/dxinerz/dxinerz1506/dxinerz150602172/41375607-circuit-ic-processor-icon-vector-image-can-also-be-used-for-computer-and-hardware-suitable-for-use-o.jpg?ver=6

**Comment by CoDEmanX** [comment]
There's an icon for memory, although it looks more like a CPU:

[![memory](https://materialdesignicons.com/icon/memory)](https://materialdesignicons.com/icon/memory)

#1034 contains a request for another icon (CPU or RAM, however you interpret the existing one). There's an Android 6 icon for memory, which I re-created here:

![ram](https://cloud.githubusercontent.com/assets/1309249/10827014/c97b183a-7e6c-11e5-9931-50be7d98613e.png) https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-152349331

Would this fulfill your request for IC/chip?

As for PCB, that's an interesting example picture. I'll give that a try soon.

@Templarian: we could use an alias for the existing memory icon I guess

**Comment by Templarian** [comment]
[![chip](https://materialdesignicons.com/icon/chip)](https://materialdesignicons.com/icon/chip)
