### ISSUE TITLE
mdi-flask* icons not showing on web

### ISSUE THREAD

**Issue by ChalkPE** [Templarian/MaterialDesign#1080]
This happens when I put `<link rel="stylesheet" charset="utf-8" href="//cdn.materialdesignicons.com/1.4.57/css/materialdesignicons.min.css">` on `<head>` and used `<i class="mdi mdi-flask"></i>` on `<body>` :(

**Comment by Templarian** [comment]
In that version they are called `beaker` incorrectly. Enough science people got annoyed I was forced to rename them.

http://cdn.materialdesignicons.com/1.5.54-dev/ Is releasing today or tomorrow which will contain the `mdi-flask` correct naming.

**Comment by ChalkPE** [comment]
Great :smiley:
