### ISSUE TITLE
Need a few knitting icons

### ISSUE THREAD

**Issue by jenious** [Templarian/MaterialDesign#1082]
Has anyone seen a knitting needle, crochet hook, and/or yarn icon?  I could use all three for a project I'm working on.  Thanks in advance!

**Comment by Jargonius** [comment]
Here are a couple of versions of knitting needles.
![knitting_needles1](https://cloud.githubusercontent.com/assets/6412293/14369468/8ec100a2-fce2-11e5-8d06-62a8ce3e30d5.png)
![knitting_needles2](https://cloud.githubusercontent.com/assets/6412293/14369476/92d180a4-fce2-11e5-8ba9-7bee75e07ae2.png)

[knitting_needles.zip](https://github.com/Templarian/MaterialDesign/files/209371/knitting_needles.zip)

**Comment by Jargonius** [comment]
I'm going to try my hand at the yarn and the hook too.

**Comment by jenious** [comment]
Nice!

**Comment by Jargonius** [comment]
Thanks!

**Comment by CoDEmanX** [comment]
Looks more like nails to be honest. What's the pixel width? Can it be reduced?

**Comment by Jargonius** [comment]
I noticed it looked like nails too.  I'll work on it some more.  On that topic though.  Does anyone need a nails icon?

**Comment by CoDEmanX** [comment]
Hammer + nail maybe? Contributions are always welcome, just make sure they follow the MD guidelines and aren't extremely specific.

**Comment by Templarian** [comment]
I don't think this icon will fit in to the pack as it is probably too specific, so I'm going to close this issue out.
