### ISSUE TITLE
chevron-triple-*

### ISSUE THREAD

**Issue by RwbyChan2** [Templarian/MaterialDesign#1083]
Would really like to see this icon:
https://i.gyazo.com/137e7ec5bc297cda293a3dc1a906c00f.png

**Comment by CoDEmanX** [comment]
Looks like a duplicate of rank #1050

**Comment by PeterShaggyNoble** [comment]
This is `stat 3` from Google's extended icon set, which also includes the complementary `stat minus 3`.

![stat 3](https://user-images.githubusercontent.com/15157491/33947671-eae1ce4c-e01c-11e7-86d2-fb7dd709b2b3.png) ![stat minus 3](https://user-images.githubusercontent.com/15157491/33947702-059a58da-e01d-11e7-8e3e-2fbd644265c2.png)

**Comment by CoDEmanX** [comment]
Also: `chevron-triple-left` and `chevron-triple-right`

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48992638-e4787f00-f106-11e8-830a-a5377cf87f2b.png)![image](https://user-images.githubusercontent.com/1015040/48992646-ecd0ba00-f106-11e8-99d9-c94320fddbee.png)
![image](https://user-images.githubusercontent.com/1015040/48992649-f3f7c800-f106-11e8-8887-c0bc007d0967.png)![image](https://user-images.githubusercontent.com/1015040/48992654-fb1ed600-f106-11e8-940f-43223e4d0564.png)

[chevron-triple.zip](https://github.com/Templarian/MaterialDesign/files/2614041/chevron-triple.zip)

**Comment by Templarian** [comment]
Added.
