### ISSUE TITLE
Group by

### ISSUE THREAD

**Issue by Rejx93** [Templarian/MaterialDesign#1085]
A group by icon would be useful especially for grids.

**Comment by CoDEmanX** [comment]
Some experiments:

![group-by](https://cloud.githubusercontent.com/assets/1309249/13600094/f7deea32-e526-11e5-8470-0216d3e30324.png)
![group-by2](https://cloud.githubusercontent.com/assets/1309249/13600095/f7deecc6-e526-11e5-8eaa-a6d8922b74ff.png)
![group-by3](https://cloud.githubusercontent.com/assets/1309249/13600096/f7df0b7a-e526-11e5-91f4-f5037b75a0bb.png)
![group-by4](https://cloud.githubusercontent.com/assets/1309249/13600099/f7e64dd6-e526-11e5-8323-79b105c84ae5.png)
![group-by5](https://cloud.githubusercontent.com/assets/1309249/13600097/f7e33718-e526-11e5-94a7-6053c34d8f1e.png)
![group-by6](https://cloud.githubusercontent.com/assets/1309249/13600098/f7e38a56-e526-11e5-990b-79a68a460784.png)
![group-by7](https://cloud.githubusercontent.com/assets/1309249/13600100/f7f63160-e526-11e5-9285-9ee85fbe444c.png)

**Comment by Rejx93** [comment]
Thanks!

**Comment by CoDEmanX** [comment]
I don't like any of those. Anyone with a better idea?

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/68065613-efb23280-fcf9-11e9-805b-c1e1e54735c9.png)

Modified version of yours... hmm

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/68065635-2ee08380-fcfa-11e9-99dc-ad5f9e397d36.png)

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/72197067-7c295180-341d-11ea-8737-e01455ee4e38.png)

![grafik](https://user-images.githubusercontent.com/1309249/72197094-c90d2800-341d-11ea-8ebc-61be5dfb580b.png)

![grafik](https://user-images.githubusercontent.com/1309249/72197132-2f924600-341e-11ea-9a85-e69bf542d450.png)

The `format-list-text` icon is kinda what we try here isn't it?

![grafik](https://user-images.githubusercontent.com/1309249/72196966-7da64a00-341c-11ea-9f20-85eceb84041b.png)

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/72197180-c4953f00-341e-11ea-8657-8f7aff16eff2.png)

![grafik](https://user-images.githubusercontent.com/1309249/72197197-f4444700-341e-11ea-810b-6996c56cf6f6.png)

![grafik](https://user-images.githubusercontent.com/1309249/72197249-7e8cab00-341f-11ea-89eb-aceb71a0c432.png)

**Comment by goyney** [comment]
@Templarian @CoDEmanX What do we want to do with this issue? I see several suggestions but nothing concrete. Can we figure out which ones are the top choices and either add them or do a couple more iterations on them?

**Comment by goyney** [comment]
[![format-list-group](https://materialdesignicons.com/icon/format-list-group)](https://materialdesignicons.com/icon/format-list-group)
