### ISSUE TITLE
5 Icons: Batman, Goku, Illuminati, Grunt, alien

### ISSUE THREAD

**Issue by michelzf** [Templarian/MaterialDesign#1086]
List of icons:
- batman
- goku
- alien
- illuminati
- grunt

[5 icons.zip](https://github.com/Templarian/MaterialDesign/files/163304/5.icons.zip)

**Comment by Templarian** [comment]
Just an update so you don't think I'm ignoring this (I'm ignoring all issues). Free time has been eaten up working on a talk for Saturday. Will be working to get these icons in next week. :smile:

**Comment by GreenTurtwig** [comment]
The Goku icon might be good for other anime related things too :-)

**Comment by michelzf** [comment]
Ok Templarian,thanks.

**Comment by Templarian** [comment]
None of these match the Material Design guidelines. Some icons will not work in these guidelines and cannot be included (`batman`, `goku`, `grunt` will most likely never make it in).

https://www.google.com/design/spec/style/icons.html#icons-system-icons
