### ISSUE TITLE
[Icon Request] Verical align icons

### ISSUE THREAD

**Issue by Andrew1503** [Templarian/MaterialDesign#1088]
Looking for the google vertical alignment icons, and possibly horizontal equivalents.

https://design.google.com/icons/#ic_vertical_align_center

**Comment by CoDEmanX** [comment]
Tracked in #420 (rows 479-481), but I would like to see horizontal alignment icons too.

**Comment by Templarian** [comment]
[![format-vertical-align-top](https://materialdesignicons.com/icon/format-vertical-align-top)](https://materialdesignicons.com/icon/format-vertical-align-top) [![format-vertical-align-center](https://materialdesignicons.com/icon/format-vertical-align-center)](https://materialdesignicons.com/icon/format-vertical-align-center) [![format-vertical-align-bottom](https://materialdesignicons.com/icon/format-vertical-align-bottom)](https://materialdesignicons.com/icon/format-vertical-align-bottom) [![format-horizontal-align-left](https://materialdesignicons.com/icon/format-horizontal-align-left)](https://materialdesignicons.com/icon/format-horizontal-align-left) [![format-horizontal-align-center](https://materialdesignicons.com/icon/format-horizontal-align-center)](https://materialdesignicons.com/icon/format-horizontal-align-center) [![format-horizontal-align-right](https://materialdesignicons.com/icon/format-horizontal-align-right)](https://materialdesignicons.com/icon/format-horizontal-align-right)
