### ISSUE TITLE
Icon for move and resize

### ISSUE THREAD

**Issue by russellhealy** [Templarian/MaterialDesign#1090]
Icon to represent a toolbox in a drawing application where the user can modify x and y coordinates, and the width and height of a drawing widget.

The attached is a concept. It doesn't follow Material Design Guidelines
[move-and-resize.svg.zip](https://github.com/Templarian/MaterialDesign/files/166722/move-and-resize.svg.zip)

**Comment by CoDEmanX** [comment]
Hey @russellhealy, thanks for the contribution. Your icon does unfortunately not comply with the guidelines in its current form:

- Document dimensions are 128mm?! It must be a 24 by 24 pixels grid
- Strokes are not pixel-perfect, which is essential esp. for vertical and horizontal lines to look crisp
- Margins between the elements are too small (should be 2px, 1px in exceptional cases)
- Stroke terminals are rounded
- Corner radius lower than 2px on the inside of the rectangle

This is more like it, but the 1px strokes are actually too delicate:
![move-and-resize1](https://cloud.githubusercontent.com/assets/1309249/14803259/558b88e6-0b58-11e6-887f-ff6320a11318.png)

Some more experiments:
![move-and-resize2](https://cloud.githubusercontent.com/assets/1309249/14803277/770619f0-0b58-11e6-81bf-e4832b20a2a8.png)
![move-and-resize3](https://cloud.githubusercontent.com/assets/1309249/14803273/7705a4de-0b58-11e6-8188-9b7dd4b46d2f.png)
![move-and-resize4](https://cloud.githubusercontent.com/assets/1309249/14803276/77061dce-0b58-11e6-813e-908f5a5bf642.png)
![move-and-resize5](https://cloud.githubusercontent.com/assets/1309249/14803274/7705dbac-0b58-11e6-8c05-2dd27e823a6d.png)
![move-and-resize6](https://cloud.githubusercontent.com/assets/1309249/14803275/77060d0c-0b58-11e6-8edc-a69104766c76.png)
![move-and-resize7](https://cloud.githubusercontent.com/assets/1309249/14803278/7706398a-0b58-11e6-918d-f57227a22a0e.png)
![move-and-resize8](https://cloud.githubusercontent.com/assets/1309249/14803279/77205f7c-0b58-11e6-9a2c-f18023a38f75.png)
![move-and-resize9](https://cloud.githubusercontent.com/assets/1309249/14803283/77239886-0b58-11e6-99b4-3c4107574df5.png)
![move-and-resize10](https://cloud.githubusercontent.com/assets/1309249/14803280/77208b78-0b58-11e6-9d13-de2bb924b00d.png)
![move-and-resize11](https://cloud.githubusercontent.com/assets/1309249/14803281/7721cdd0-0b58-11e6-9cab-ad8db0fc69ec.png)
![move-and-resize12](https://cloud.githubusercontent.com/assets/1309249/14803282/772218c6-0b58-11e6-8a5c-8c70d906b571.png)

**Comment by russellhealy** [comment]
Hi @CoDEmanX 

I've done a bit of user testing, and fifth one on your list seems to be the best, the one with two arrows, and a bit more space around them than the one before it.

Thank you

Russell

**Comment by Templarian** [comment]
I think there is enough reason to justify that we add both. I've added the arrow version as a `-variant` with the same name.

[![move-resize](https://materialdesignicons.com/icon/move-resize)](https://materialdesignicons.com/icon/move-resize) [![move-resize-variant](https://materialdesignicons.com/icon/move-resize-variant)](https://materialdesignicons.com/icon/move-resize-variant)

**Comment by CoDEmanX** [comment]
There's actually an icon like this in Microsoft Office - should we change our icon?

![Office-2016-sidebar](https://itcatalog.grok.lsu.edu/image/39552.png)

**Comment by Templarian** [comment]
Agree lets change it.

**Comment by russellhealy** [comment]
I think the office one is not as good. It does not indicate location (X,Y coordinates) and it looks like maximize.

**Comment by CoDEmanX** [comment]
My interpretations are more like scale + move:

![move-and-resize13_ 1090](https://cloud.githubusercontent.com/assets/1309249/14904142/7c5fc73e-0da6-11e6-885b-3b837a3d9b00.png)

![move-and-resize14_ 1090](https://cloud.githubusercontent.com/assets/1309249/14904141/7c5fca68-0da6-11e6-9d9b-3c9fa0d01ebe.png)

**Comment by russellhealy** [comment]
The first of these looks best to me, the pattern in the box is more obviously "move". The second looks a bit closer to "maximize".

**Comment by russellhealy** [comment]
I have had feedback from a bunch of people that the fifth one on the list of "Some more experiments" above is the best one:


![](https://cloud.githubusercontent.com/assets/1309249/14803275/77060d0c-0b58-11e6-8edc-a69104766c76.png)

Can this be added to the icons collection?

Thank you

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/move-resize-variant

**Comment by russellhealy** [comment]
Great, thank you!
