### ISSUE TITLE
icon temperature c/f

### ISSUE THREAD

**Issue by fefroyo** [Templarian/MaterialDesign#1091]
one icon for temperature c/f click

**Comment by CoDEmanX** [comment]
Am I fantasizing or did a request for a °C/°F toggle exist before, but it now gone? I heard GitHub had a major breakdown and lost quite some data...

**Comment by Templarian** [comment]
There have been a few temperature type icons. Never just one with C/F on the same icon though.

**Comment by CoDEmanX** [comment]
I swear I've seen this request, and I usually tag them when I look at them... but maybe I was using my phone and did not tag it. That would explain it.

On the subject: I don't think C + F and two ° fit well within ~20 px.

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/temperature-celsius)](https://materialdesignicons.com/icon/temperature-celsius)[![](https://materialdesignicons.com/icon/temperature-fahrenheit)](https://materialdesignicons.com/icon/temperature-fahrenheit)

**Comment by GreenTurtwig** [comment]
Having both in one icon won't work with the size limitations. I suggest toggling between the two above.
