### ISSUE TITLE
Expand and compress icons

### ISSUE THREAD

**Issue by mpetkov** [Templarian/MaterialDesign#1092]
Expand and compress like the 2 from font-awesome:

http://fortawesome.github.io/Font-Awesome/icon/expand/
http://fortawesome.github.io/Font-Awesome/icon/compress/

**Comment by CoDEmanX** [comment]
Good idea!

**Comment by Templarian** [comment]
[![arrow-expand](https://materialdesignicons.com/icon/arrow-expand)](https://materialdesignicons.com/icon/arrow-expand) [![arrow-compress](https://materialdesignicons.com/icon/arrow-compress)](https://materialdesignicons.com/icon/arrow-compress)

**Comment by mpetkov** [comment]
@Templarian  - Thanks for adding it however could it also be added to the webfont? Or do I also need to create a ticket in that repo as well?
https://github.com/Templarian/MaterialDesign-Webfont

**Comment by Templarian** [comment]
Right now updates are released every few months. Doing a lot of travel and stuff at the moment. Eventually nightly automated builds will be coming. I need to clean up some more code now that the back end allows subfonting.

So, yea, right now you will have to wait.

**Comment by mpetkov** [comment]
@Templarian  - Sorry to bother you again but is there any update on when the npm module will be updated?

**Comment by Templarian** [comment]
@mpetkov I'll be working to get an update out shortly. I've got a lot of contribution icons that need to make it in. I'm probably going to release at `1.6.50`.
