### ISSUE TITLE
Sideway view of car

### ISSUE THREAD

**Issue by Golen87** [Templarian/MaterialDesign#1094]
I am interested in an icon of a standard car seen from the side. There isan icon of a truck seen from the side, and I would love to see a similar style of that but with a regular car rather than the currently existing front-view (car, car-connected and car-washed).

**Comment by chrvasile** [comment]
There you go
![car](https://cloud.githubusercontent.com/assets/17312269/13844758/04242cc8-ec3c-11e5-95d5-a89a9c82771e.png)

[car.svg.zip](https://github.com/Templarian/MaterialDesign/files/177741/car.svg.zip)

**Comment by CoDEmanX** [comment]
@chrvasile: it's not material-y enough I'm afraid

**Comment by GreenTurtwig** [comment]
And here we have four different styles of car:
[cars.zip](https://github.com/Templarian/MaterialDesign/files/973989/cars.zip)
![](https://puu.sh/vEmDG.png)
![](https://puu.sh/vEmFl.png)

![](https://puu.sh/vEmGa.png)
![](https://puu.sh/vEmGO.png)

![](https://puu.sh/vEmHo.png)
![](https://puu.sh/vEmHS.png)

![](https://puu.sh/vEmII.png)
![](https://puu.sh/vEmJy.png)

(There's also a Taxi side on view in there, basically just a regular car with a block on the top...)

**Comment by JamesCoyle** [comment]
Hatchback and sports variants would be good too. Hatchback would just be the normal without the back curve bit.

**Comment by GreenTurtwig** [comment]
Great idea!
![](https://puu.sh/vFAyb.png)
![](https://puu.sh/vFAzJ.png)

![](https://puu.sh/vFAB0.png)
![](https://puu.sh/vFAC7.png)
Moved the wheels a little up on the sports car.

[sportsAndHatchback.zip](https://github.com/Templarian/MaterialDesign/files/977284/sportsAndHatchback.zip)

**Comment by Templarian** [comment]
@GreenTurtwig Tweaked some of the windows to be `1.5dp`, but other were correct.

Added all 6 of these (too lazy to link the preview images for each). Thanks!
