### ISSUE TITLE
Dictionary icon

### ISSUE THREAD

**Issue by shankarcabus** [Templarian/MaterialDesign#1095]
How about a dictionary icon? Something like [Aa] or [A-Z] or [Abc]

**Comment by infanf** [comment]
![dictionary](https://cloud.githubusercontent.com/assets/8826710/13788773/777cf60c-eae1-11e5-8b8c-afde4eb2dd3d.png)
![dictionary-48](https://cloud.githubusercontent.com/assets/8826710/13788774/7784abae-eae1-11e5-91d9-641b55dc007b.png)
![dictionary-96](https://cloud.githubusercontent.com/assets/8826710/13788775/77880ba0-eae1-11e5-87cc-f1720cd09e73.png)
[dictionary.zip](https://github.com/Templarian/MaterialDesign/files/174530/dictionary.zip)

**Comment by Templarian** [comment]
[![dictionary](https://materialdesignicons.com/icon/dictionary)](https://materialdesignicons.com/icon/dictionary)
