### ISSUE TITLE
Adobe AEM/CQ

### ISSUE THREAD

**Issue by AndreasKarz** [Templarian/MaterialDesign#1096]
i think a great idea for admin boards

Like http://blogs.adobe.com/sunil/files/2015/02/icon.png  or https://pbs.twimg.com/profile_images/2165745233/Adobe_CQ_icon_RGB_512px_no_shadow.png

**Comment by CoDEmanX** [comment]
Both are brand icons by Adobe, aren't they?

**Comment by Templarian** [comment]
These might be far too niche of icons to include. I'm kind of on the side of rejecting this request.

@CoDEmanX What do you think?

**Comment by CoDEmanX** [comment]
Well, CQ is the old name, AEM the new one. But AEM is actually part of Adobe Marketing Cloud:
https://en.wikipedia.org/wiki/Adobe_Marketing_Cloud

We do have icons for WordPress, Drupal... but CQ/AEM/AMC don't appear very popular, so I would also say to reject this request.

**Comment by Templarian** [comment]
@AndreasKarz Once the projects get a little more popular we may include them. Right now it's going to be too niche for general use.
