### ISSUE TITLE
Scanner Icons

### ISSUE THREAD

**Issue by nverbeek** [Templarian/MaterialDesign#1099]
Would love to have a set of icons similar to the Bluetooth icons, but with a picture of a scanner. Scanner connected, connecting, disconnected.

**Comment by CoDEmanX** [comment]
Well, I see a point for having `scanner` and `scanner-off` (disconnected), but not `scanner-connected` and `scanner-connecting`...

**Comment by nverbeek** [comment]
We currently have a requirement to support different scanner types in our application. Some are USB, some are Bluetooth, others Wifi. For all non-wired scanners, there are times when the application is connecting, pairing, etc so thats where the "connecting" idea came from.  The use case for "connected" is just another extra differentiation, probably not as useful as the other 3.

**Comment by CoDEmanX** [comment]
I recommend to not use overly literal icons, but instead, use color, transparency and animation to indicate additional states. The connecting state could be the regular scanner icon that "blinks":

http://codepen.io/simran/pen/ZWLZbm

**Comment by GreenTurtwig** [comment]
Agree that we don't need connecting icons.

[![](https://user-images.githubusercontent.com/15905797/33997960-05f078ac-e0de-11e7-9848-937c421fbf60.png)](https://github.com/Templarian/MaterialDesign/files/1559639/scanner-off.zip)[![](https://user-images.githubusercontent.com/15905797/33997977-12b379cc-e0de-11e7-9bb7-21809e527d59.png)](https://github.com/Templarian/MaterialDesign/files/1559640/scanner-off2.zip)

**Comment by Templarian** [comment]
[![scanner](https://materialdesignicons.com/icon/scanner)](https://materialdesignicons.com/icon/scanner) [![scanner-off](https://materialdesignicons.com/icon/scanner-off)](https://materialdesignicons.com/icon/scanner-off)

**Comment by Templarian** [comment]
@GreenTurtwig By the way, we can always rotate the original if it's required. Earth was the only one we couldn't so far because of it wouldn't make sense.

**Comment by GreenTurtwig** [comment]
@Templarian Figured it was best to stay consistent, but nice to know.
