### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by simonharrer** [Templarian/MaterialDesign#1100]
A lot of searches have the option for toggling regex and case sensitivity. For regex, there is already an icon, but for case sensitivity, such an icon is missing. I would have in mind something like "aA" as an icon, similar to ".*" for the regex icon.

**Comment by CoDEmanX** [comment]
We do have an icon, but it only works in English (it's a word play): case-sensitive-alt

**Comment by simonharrer** [comment]
Good point. I would prefer an icon which also works in other cultural settings as well :)

**Comment by Templarian** [comment]
I think I'm going to delete that icon once we get a real one. My friend @r3volution11 snuck that one in. I maintain this project generally with a beer in my hand, so it happens (it's kind of punny). _\*sips beer\*_

An `Aa` icon might be too large. We might want to use `Ii` in serif.

:grin:

**Comment by jfoxtail** [comment]
![inputtext](https://cloud.githubusercontent.com/assets/8354098/14393621/b932f864-fd7c-11e5-9154-fab1ee7bbd9e.png)
...more of 'input text' but could suit you.

**Comment by goyney** [comment]
We now have `format-letter-case`, `format-letter-case-lower`, and `format-letter-case-upper`.

[![format-letter-case](https://materialdesignicons.com/icon/format-letter-case)](https://materialdesignicons.com/icon/format-letter-case)[![format-letter-case-lower](https://materialdesignicons.com/icon/format-letter-case-lower)](https://materialdesignicons.com/icon/format-letter-case-lower)
[![format-letter-case-upper](https://materialdesignicons.com/icon/format-letter-case-upper)](https://materialdesignicons.com/icon/format-letter-case-upper)

@simonharrer Do any of these solve your use case?

**Comment by simonharrer** [comment]
Awesome. Yes, that fits perfectly!
