### ISSUE TITLE
Not credited on MDI site

### ISSUE THREAD

**Issue by imogenic** [Templarian/MaterialDesign#1101]
In #1003 I provided an SVG for an improved version of Google's newspaper icon, but the icon is credited to Google.

**Comment by imogenic** [comment]
#1003

**Comment by Templarian** [comment]
Slight modification to the icon and we don't add contributes until 5 icons.

Remind me about this once you have 5 icons contributed and I'll get it contributed. I have a feature request issue somewhere to have multiple authors also that I need to get added, but it's a very low priority. Right now the focus is getting the backlog of icons added (close to 200'ish).
