### ISSUE TITLE
Gears Icon

### ISSUE THREAD

**Issue by jonas99y** [Templarian/MaterialDesign#1103]
A Icon that displays one ore several gears whould be nice.

**Comment by CoDEmanX** [comment]
We do have a single gear:
https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/cog.svg

@Templarian: cog and box-cog do not show up in search on the web site, something is broken.

**Comment by Templarian** [comment]
It was renamed a couple releases ago. Never renamed the source files.

https://materialdesignicons.com/icon/settings
https://materialdesignicons.com/icon/settings-box

I added an alias for `gear` / `gear-box` and `cog` / `cog-box` to help searching.

**Comment by CoDEmanX** [comment]
I can't find them on the website still, I tried cog, gear and settings...

**Comment by Templarian** [comment]
Oh wait, was this icon request was for multiple gears? Might be reading it wrong?

**Comment by CoDEmanX** [comment]
Search works again, with all the aliases. Single gear fulfilled, multiple gears still missing (common icon for services / daemons).

**Comment by CoDEmanX** [comment]
Cheered too soon, search is still broken - in Chrome on Android. No matter what I search, it's always an empty result set. The page has always been slow on mobile devices, but at least it worked. Chrome on Windows works nonetheless.

**Comment by PeterShaggyNoble** [comment]
Closing this in favour of #1262 which includes cntributions.
