### ISSUE TITLE
Quick HTML copy and paste

### ISSUE THREAD

**Issue by gytdau** [Templarian/MaterialDesign#1104]
When you are viewing a specific icon, you could have a box with the HTML code ready to copy and paste.

E.g. for `alarm`:

`<span class="mdi mdi-alarm"></span>`

It'd make life just a little bit easier.

**Comment by Templarian** [comment]
https://cdn.materialdesignicons.com/1.5.54/

Unfortunately I don't have the unicode values tied back to the site, but for now if you use the preview that comes with the webfont for this functionality. Clicking any of the icons will copy the character.
