### ISSUE TITLE
Suggest icon: Building/flat

### ISSUE THREAD

**Issue by thelittlefireman** [Templarian/MaterialDesign#1105]
a Building or a flat would be great.

thanks

**Comment by Templarian** [comment]
Do you have an example?

**Comment by CoDEmanX** [comment]
We have the following icons that resemble buildings:

[![home](https://materialdesignicons.com/icon/home)](https://materialdesignicons.com/icon/home) [![home-variant](https://materialdesignicons.com/icon/home-variant)](https://materialdesignicons.com/icon/home-variant) [![home-modern](https://materialdesignicons.com/icon/home-modern)](https://materialdesignicons.com/icon/home-modern) [![factory](https://materialdesignicons.com/icon/factory)](https://materialdesignicons.com/icon/factory) [![bank](https://materialdesignicons.com/icon/bank)](https://materialdesignicons.com/icon/bank) [![factory](https://materialdesignicons.com/icon/factory)](https://materialdesignicons.com/icon/factory) [![hospital-building](https://materialdesignicons.com/icon/hospital-building)](https://materialdesignicons.com/icon/hospital-building) [![store](https://materialdesignicons.com/icon/store)](https://materialdesignicons.com/icon/store) [![store-24-hour](https://materialdesignicons.com/icon/store-24-hour)](https://materialdesignicons.com/icon/store-24-hour)

**Comment by thelittlefireman** [comment]
like that : [http://simpleicon.com/wp-content/uploads/building-3.png](image)
![image](https://cloud.githubusercontent.com/assets/5165783/13904414/43293b28-eea0-11e5-9bc1-038f2e0c96e1.png)
![image](https://cloud.githubusercontent.com/assets/5165783/13904429/ad922600-eea0-11e5-81dd-01d17aeb4226.png)
![image](https://cloud.githubusercontent.com/assets/5165783/13904430/b20b923e-eea0-11e5-83de-a3c457e7fcdd.png)

**Comment by CoDEmanX** [comment]
I actually missed the one that looks similar to your examples:

[![domain](https://materialdesignicons.com/icon/domain)](https://materialdesignicons.com/icon/domain)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback.

@thelittlefireman, let us know if your request wasn't fulfilled by the icons above (or `city`) and we'll reopen this.

[![city](https://user-images.githubusercontent.com/15157491/33946958-120b4a22-e01b-11e7-82e9-e26c815f2520.png)](https://materialdesignicons.com/icon/city)

**Comment by thelittlefireman** [comment]
that's alright for me thanks :) 👍
