### ISSUE TITLE
Cellphone-basic has superfluous points (site download only)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#1106]
If you download the compressed SVG from the site, 8 out of 9 of the phone button squares got two points in the upper left corner in the exactly same spot. This isn't the case in the SVG file found in the repository.

On a side note: "SVG compressed" is a bit misleading, because there is also the SVGZ format. I vote to change it to "SVG optimized" or something along these lines.

**Comment by Templarian** [comment]
Renamed it to Optimized.

I'm not 100% sure I'm seeing it, can you explain.

```
M15,2A1,1 0 0,0 14,3V6H10C8.89,6 8,6.89 8,8V20C8,21.11 8.89,22 10,22H15C16.11,22 17,21.11 17,20V8C17,7.26 16.6,6.62 16,6.28V3A1,1 0 0,0 15,2
M10,8H15V13H10V8        /* Large Square display area cutout */
M10,15H11V16H10V15    /* Button 1, each is 3 points auto closing. */
M12,15H13V16H12V15
M14,15H15V16H14V15
M10,17H11V18H10V17
M12,17H13V18H12V17
M14,17H15V18H14V17
M10,19H11V20H10V19
M12,19H13V20H12V19
M14,19H15V20H14V19
Z
```

**Comment by CoDEmanX** [comment]
If I open the optimized SVG in InkScape, there are duplicate vertices:

![double-verts-1](https://cloud.githubusercontent.com/assets/1309249/13914936/dbca0130-ef51-11e5-9b7f-0b05ae4f6ab5.png)
![double-verts-2](https://cloud.githubusercontent.com/assets/1309249/13914937/dbf2462c-ef51-11e5-90ed-f6ae18069175.png)

Maybe the source should rather look like this?

```
M12,15H13V16H12Z
M14,15H15V16H14Z
```

and no single Z at the end?

**Comment by Templarian** [comment]
Fixed, but not fully fixed yet. It is a bug in the optimization script.

```
M 15,2C 14.446,2 14,2.446 14,3L 14,6L 10,6C 8.89199,6 8,6.8916 8,8L 8,20C 8,21.108 8.89199,22 10,22L 15,22C 16.1084,22 17,21.108 17,20L 17,8C 17,7.2589 16.5958,6.621 16,6.2754L 16,3C 16,2.446 15.554,2 15,2 Z M 10,8L 15,8L 15,13L 10,13L 10,8 Z M 10,15L 11,15L 11,16L 10,16L 10,15 Z M 12,15L 13,15L 13,16L 12,16L 12,15 Z M 14,15L 15,15L 15,16L 14,16L 14,15 Z M 10,17L 11,17L 11,18L 10,18L 10,17 Z M 12,17L 13,17L 13,18L 12,18L 12,17 Z M 14,17L 15,17L 15,18L 14,18L 14,17 Z M 10,19L 11,19L 11,20L 10,20L 10,19 Z M 12,19L 13,19L 13,20L 12,20L 12,19 Z M 14,19L 15,19L 15,20L 14,20L 14,19 Z
```

Becomes...

```
M15,2A1,1 0 0,0 14,3V6H10C8.89,6 8,6.89 8,8V20C8,21.11 8.89,22 10,22H15C16.11,22 17,21.11 17,20V8C17,7.26 16.6,6.62 16,6.28V3A1,1 0 0,0 15,2M10,8H15V13H10V8M10,15H11V16H10V15M12,15H13V16H12V15M14,15H15V16H14V15M10,17H11V18H10V17M12,17H13V18H12V17M14,17H15V18H14V17M10,19H11V20H10V19M12,19H13V20H12V19M14,19H15V20H14V19Z
```

Which as you can see converts ugly lines to the correct `V` and `H` values and removes the unnecessary `Z`, but does not account for lines that correctly close. You see `ZM` assumes a close since it starts a new segment.

Leaving this opened until I have time to fix it. Don't worry once I fix a bug in the optimization script it runs and flags all icons with similar issues.

**Comment by JamesCoyle** [comment]
Closing as I believe this has been fixed when we changed our optimization code to SVGO.
