### ISSUE TITLE
pets and pets-off

### ISSUE THREAD

**Issue by simkepal** [Templarian/MaterialDesign#1109]
Hello, Is it possible to create pets and pets-off icon. I would need it for if pets are allowed in the room or not.

Thank you

**Comment by Templarian** [comment]
Related to the #736 dog icon most likely.

**Comment by CoDEmanX** [comment]
I posted two icon variants (paw-off) over here: #1164

**Comment by PeterShaggyNoble** [comment]
`paw` and `paw-off` should fulfil this request.
