### ISSUE TITLE
"Load More" icon

### ISSUE THREAD

**Issue by robbypond** [Templarian/MaterialDesign#111]
I've been looking for a "Load More" icon but can seem to find one.

**Comment by Templarian** [comment]
Sorry, do you have an example of this?

**Comment by danielhickman** [comment]
All I have seen used is a refresh like icon, text, or and arrow

![load more google search](https://cloud.githubusercontent.com/assets/5341898/5868892/43348790-a265-11e4-9f50-f9c77f738cb3.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/reload
http://materialdesignicons.com/icon/refresh
