### ISSUE TITLE
Outline circular account.

### ISSUE THREAD

**Issue by awazgyawali** [Templarian/MaterialDesign#1110]
Demo:- ![ic_contact](https://cloud.githubusercontent.com/assets/10810343/13916200/42b36024-ef81-11e5-8633-871fa7f707b3.png)

**Comment by CoDEmanX** [comment]
Google uses such an icon for Android's Trusted Face feature:

![trusted_face](https://cloud.githubusercontent.com/assets/1309249/14044036/c79e5070-f28b-11e5-844f-6f09090db94b.png)

**Comment by awazgyawali** [comment]
Thanks for the site. 

But it would be awesome if someone draw an svg of the icon.

**Comment by jfoxtail** [comment]
![useroutlinecircle](https://cloud.githubusercontent.com/assets/8354098/14393555/69357012-fd7c-11e5-9a8c-9e874a4d2fa8.png)
![usersoutline](https://cloud.githubusercontent.com/assets/8354098/14393558/6d115d9a-fd7c-11e5-825e-882eec355e4b.png)
These are .pngs, but you could easily vectorize them.

**Comment by CoDEmanX** [comment]
I think the 1st one is the best: ![account-circle_ 1110](https://cloud.githubusercontent.com/assets/1309249/14904071/f47f70d0-0da5-11e6-8998-549a0560dcf2.png) ![account-circle2_ 1110](https://cloud.githubusercontent.com/assets/1309249/14904069/f47ec1c6-0da5-11e6-9ff3-086de74b170c.png) ![account-circle3_ 1110](https://cloud.githubusercontent.com/assets/1309249/14904070/f47eb460-0da5-11e6-877b-4cc682ab0bb3.png)

**Comment by MrGrigri** [comment]
Closing as `account-circle` and `account-circle-outline` have since been added.
