### ISSUE TITLE
git-branch and git-merge icon

### ISSUE THREAD

**Issue by lcristianiim** [Templarian/MaterialDesign#1111]
A 'git-branch' icon would be very useful. I am sorry I can not make it my self at the moment.

**Comment by Templarian** [comment]
Might be ideal to merge this with #1059.

**Comment by Templarian** [comment]
[![source-branch](https://materialdesignicons.com/icon/source-branch)](https://materialdesignicons.com/icon/source-branch)

I'm going to redo the rest of the `source-*` icons to be consistent.

**Comment by CoDEmanX** [comment]
So there's branch, fork and pull request, but we are still missing a merge icon. A mirrored branch icon would probably suffice.

**Comment by lcristianiim** [comment]
@Templarian the `source-branch` icon is so nice. Your cool.

**Comment by Templarian** [comment]
[![source-fork](https://materialdesignicons.com/icon/source-fork)](https://materialdesignicons.com/icon/source-fork) [![source-pull](https://materialdesignicons.com/icon/source-pull)](https://materialdesignicons.com/icon/source-pull) [![source-merge](https://materialdesignicons.com/icon/source-merge)](https://materialdesignicons.com/icon/source-merge)

**Comment by Simran-B** [comment]
Github has an icon to compare branches: https://octicons.github.com/icon/git-compare/
