### ISSUE TITLE
Icon for mathematical symbols such as square root

### ISSUE THREAD

**Issue by HyperGamers** [Templarian/MaterialDesign#1113]
It would be very useful if there were icons such as square root, angle, delta, sigma, gamma, sets, etc.
Would this be a possibility? I am mainly looking for a square root symbol though.

**Comment by CoDEmanX** [comment]
I actually worked on a square root icon when I did a pi symbol, but I didn't like it. We also need a boxed version in the same style.

**Comment by PeterShaggyNoble** [comment]
A lot of these have since been added so going to close this. If you're still in need of any, please open individual issues for each icon request, not forgetting to search the existing issues first.
