### ISSUE TITLE
Android App Store Icon

### ISSUE THREAD

**Issue by 00ec454** [Templarian/MaterialDesign#1116]
Please design the android app store Icon

**Comment by CoDEmanX** [comment]
We currently have

[![google-play](https://materialdesignicons.com/icon/google-play)](https://materialdesignicons.com/icon/google-play)

and also an icon, which is very similar, but not identical (the handle) to the Playstore icon:

[![shopping-music](https://materialdesignicons.com/icon/shopping-music)](https://materialdesignicons.com/icon/shopping-music)

@Templarian: to you intent to replace your icon with Google's icon? Row 150 in #420 spreadsheet.

**Comment by Templarian** [comment]
Sorry, what is the android store icon? I thought that was the Google Play icon?

**Comment by CoDEmanX** [comment]
The Play store icon as seen on the website corresponds to the google-play icon:

![google-play](https://cloud.githubusercontent.com/assets/1309249/14059092/5242fcca-f337-11e5-85ba-17aa1a6f362e.PNG)

But the app icon is a Google play bag:

![minimum-android-app-price](https://cloud.githubusercontent.com/assets/1309249/14059093/52439eb4-f337-11e5-8fc0-cbb3f17ebc63.jpg)

As system icon: https://design.google.com/icons/#ic_shop

**Comment by macx** [comment]
Google has refreshed their [play icons](http://officialandroid.blogspot.de/2016/04/a-new-look-for-google-play-family-of-apps.html).

**Comment by Templarian** [comment]
@macx I don't think we're going to be supporting those for obvious reasons. They look nice though.

**Comment by CoDEmanX** [comment]
@macx: Those are product icons, MDI is about system icons:
https://www.google.com/design/spec/style/icons.html

**Comment by macx** [comment]
@Templarian, @CoDEmanX I now. I just wanted to add the status for the records of this request.

**Comment by Templarian** [comment]
So, I think it's fine to close this issue and we can't do anything.

Let me know if this is not the case.

**Comment by CoDEmanX** [comment]
The stock playstore icon by Google needs still to be added
