### ISSUE TITLE
Matrix icon

### ISSUE THREAD

**Issue by PierfrancescoSoffritti** [Templarian/MaterialDesign#1117]
A [matrix](https://en.wikipedia.org/wiki/Matrix_(mathematics)) icon could be useful for many calculator apps.

**Comment by Templarian** [comment]
[![matrix](https://materialdesignicons.com/icon/matrix)](https://materialdesignicons.com/icon/matrix)

**Comment by CoDEmanX** [comment]
Nice one! Could you swap the digits though, to make it a 2D identity matrix?

```
[ 1 0 ]
[ 0 1 ]
```

**Comment by Templarian** [comment]
Good idea. Updated!
