### ISSUE TITLE
ICON : Personal Settings

### ISSUE THREAD

**Issue by venkata-oruganti** [Templarian/MaterialDesign#1121]
Adding Personal settings ICON would be very helpful.

**Comment by CoDEmanX** [comment]
Like #287? For example user + gear (account+cog)

**Comment by CoDEmanX** [comment]
How is this? ![account-settings](https://cloud.githubusercontent.com/assets/1309249/14769061/5b5f6e3a-0a50-11e6-9ea9-14b0cdcdf4a9.png)

**Comment by Templarian** [comment]
I like it, but we could also use dots in Material Design to signify a settings or other options.

![account-dots](https://cloud.githubusercontent.com/assets/338885/14769579/454554ae-0a21-11e6-8863-459093534ea4.png)

**Comment by CoDEmanX** [comment]
True... why didn't I think of that? In this particular case, I would add both variants however - a cog for settings is quite common, and just the three dots mean "more".

**Comment by Templarian** [comment]
I kind of agree in this instance it is so widely used icon I think we could make an exception (`account-dots` and `account-settings`). Share the vector for the cog one.

**Comment by CoDEmanX** [comment]
Great! Here it is: https://www.dropbox.com/s/ey3chhx5kqa369v/account-settings.design?dl=0

**Comment by CoDEmanX** [comment]
Hm, looks like you're losing icon parts systematically: the caps lock arrow in #1194 was missing its bottom part and the new account icons look like the base shape, no dots, no cog?!

**Comment by Templarian** [comment]
That's me messing up then getting distracted coding. Forgot to look at the icon before I hit add icon.

[![account-settings](https://materialdesignicons.com/icon/acccount-settings)](https://materialdesignicons.com/icon/acccount-settings) [![account-settings-variant](https://materialdesignicons.com/icon/acccount-settings-variant)](https://materialdesignicons.com/icon/acccount-settings-variant)
