### ISSUE TITLE
Add project to Bower

### ISSUE THREAD

**Issue by rgriffith** [Templarian/MaterialDesign#1124]
Are there any plans to add this project to Bower? 

Use case: building a subset of the icon font using the SVG files and Gulp, instead of using the webfont project which would include all possible icons. Adding the project to Bower would allow for easier maintenance of the full icon set.

**Comment by Templarian** [comment]
https://materialdesignicons.com/design For now.

Bower/NPM repos of just SVG files will be coming in a few months. I'm building out a system to automate this process.

**Comment by Templarian** [comment]
@rgriffith This repo will be automated; in that, any update to the icon pack will recreate and publish the icons. From others feedback I've noticed most want the very latest icons (so think `v1.0.####` incrementing constantly with each build). This repo will also contain an easy to parse output of all the meta data I store for each icon.

Is there a scenario you can think of where you would not want an always latest release of the SVG files?

**Comment by rgriffith** [comment]
In our case, we'd like to use Gulp to generate our own icon font that is a subset of the available icons. For instance, if we use 10% of the available icons the file size of the custom font would be much smaller than that of the full font that is available in the webfont repo.

My request for #1122 was sort of a workaround to this so we could at least generate CSS for a subset of the available icons, instead of being forces to use the CSS for all of them.

**Comment by rgriffith** [comment]
Didn't realize we could point to a repo (and specific commit) using Bower, so I technically this isn't really necessary. Though making it a Bower project would keep things much cleaner.
