### ISSUE TITLE
Brand icons for Hackernews, Flipboard, Buffer and Delicious

### ISSUE THREAD

**Issue by ripper2hl** [Templarian/MaterialDesign#1125]
Please add this brand icons 

* [Hackernews](http://fortawesome.github.io/Font-Awesome/icon/hacker-news/)
* [Flipboard](https://github.com/FortAwesome/Font-Awesome/issues/1382)
* [Buffer](https://github.com/FortAwesome/Font-Awesome/issues/2110)
* [Delicious](http://fortawesome.github.io/Font-Awesome/icon/delicious/)

**Comment by Templarian** [comment]
[![hackernews](https://materialdesignicons.com/icon/hackernews)](https://materialdesignicons.com/icon/hackernews) [![buffer](https://materialdesignicons.com/icon/buffer)](https://materialdesignicons.com/icon/buffer)

The other two do not have MD styled logos. You will need to use inline vectors for those.
