### ISSUE TITLE
Extract frame from video icon

### ISSUE THREAD

**Issue by migototo** [Templarian/MaterialDesign#1126]
Hello, could you please design extract frame from video for me? Thanks in advance.

**Comment by CoDEmanX** [comment]
Some experiments:

![extract-frame](https://cloud.githubusercontent.com/assets/1309249/14170454/26d4c9d8-f72e-11e5-983a-bb774760cd32.png)
![extract-frame2](https://cloud.githubusercontent.com/assets/1309249/14170452/26d1ce90-f72e-11e5-9643-a0aa405aef0f.png)
![extract-frame3](https://cloud.githubusercontent.com/assets/1309249/14170455/26e0012c-f72e-11e5-8f22-d943d9717b7e.png)
![film-single-frame](https://cloud.githubusercontent.com/assets/1309249/14170458/26e7f562-f72e-11e5-9317-81d52b5ff9c8.png)
![filmstrip-pause](https://cloud.githubusercontent.com/assets/1309249/14170457/26e400ce-f72e-11e5-8179-4a0af018daa6.png)
![filmstrip-pause2](https://cloud.githubusercontent.com/assets/1309249/14170456/26e318b2-f72e-11e5-8ef8-58e7c8917b3b.png)

But to be honest, I would go with the camera icon for "extract frame". It's seems to be quite common in video editing applications.

Nonetheless, freeze-frame and single-frame may still be worth to include (two different things).

**Comment by migototo** [comment]
Thank a lot for your support!

2016-03-31 15:50 GMT+07:00 CoDEmanX <notifications@github.com>:

**Comment by PeterShaggyNoble** [comment]
We have and [`image-filter-frames`](https://materialdesignicons.com/icon/image-filter-frames) and Google's [`now wallpaper`] icon is similar to @CoDEmanX's suggestions above.

![now wallpaper](https://user-images.githubusercontent.com/15157491/36898523-1a5f733e-1e13-11e8-8611-747f11e03b83.png)

**Comment by PeterShaggyNoble** [comment]
That icon has been added to Google's new stock icon set and renamed as `wallpaper`: https://material.io/tools/icons/?search=wallpaper&icon=wallpaper&style=baseline

**Comment by Templarian** [comment]
Added.
