### ISSUE TITLE
Possible new icons

### ISSUE THREAD

**Issue by sandmanx24** [Templarian/MaterialDesign#1127]
sports,fitness,yoga,runner,athlete,dance

**Comment by vcardins** [comment]
passport

**Comment by fxedel** [comment]
There's already a run icon: https://materialdesignicons.com/icon/run

**Comment by CoDEmanX** [comment]
See #757 and related issues linked in that issue. Google Fit has plenty sports icons, but they were not released by Google, and they are designed for a smaller pixel grid.

As for passport, would #578 do?

**Comment by lawloretienne** [comment]
dance icon

**Comment by PeterShaggyNoble** [comment]
I'm going to close this one out as a good few [sports icons](https://petershaggynoble.github.io/MDI-Sandbox/?categories=sport) have been added lately. If there are still any sports you would like to see included, please open new requests for each icon.

See also #1365 for dancing.
