### ISSUE TITLE
Speedometer has rounded stroke terminals

### ISSUE THREAD

**Issue by fxedel** [Templarian/MaterialDesign#1128]
The icon speedometer.svg has rounded stroke terminals at the two bottom line ends. According to the [Google material design guidelines](https://www.google.com/design/spec/style/icons.html#icons-system-icons), you should use squared stroke terminals instead of rounded ones.

**Comment by CoDEmanX** [comment]
It's a re-creation of a Google icon, as seen in a rendering in the MD specs. I'm not sure if we should change it if it's "stock". A comparison would be great beforehand.
