### ISSUE TITLE
Change Language

### ISSUE THREAD

**Issue by tnViking** [Templarian/MaterialDesign#1129]
An icon that simply tells you there's more languages to choose.
Like this icon ![Egon](https://i.bratteng.xyz/UrJpBglRxw.png)
or this ![Prison Island](https://i.bratteng.xyz/LBpWU5abYc.png)

**Comment by GreenTurtwig** [comment]
There's https://materialdesignicons.com/icon/translate ?

**Comment by tnViking** [comment]
Yes, of course!I couldn't find it last night then, thank you. 👻

**Comment by GreenTurtwig** [comment]
No problem :-D

**Comment by CoDEmanX** [comment]
We could use an alias / tag / keyword for search to make it come up if you type something with "language" I guess.

**Comment by Templarian** [comment]
Added `language` as an alias.
