### ISSUE TITLE
Cursor Icon Request

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#113]
A material themed cursor.

**Comment by Templarian** [comment]
One of the contributors mentioned these were missing the other day also.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/cursor-default
http://materialdesignicons.com/icon/cursor-default-outline

Adding a pointer icon also.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/cursor-pointer (rough draft)
