### ISSUE TITLE
Wolfram|Alpha Icon

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#1130]
It would be nice to have a Wolfram|Alpha icon for projects that are using the API e.t.c. :-)
![](http://www.sfu.ca/~jtmulhol/calculus-applets/images/icon-wolframalpha.png)

**Comment by CoDEmanX** [comment]
This is hardly possible as a small monochrome icon... maybe the Greek letter alpha (lower-case) instead?

**Comment by GreenTurtwig** [comment]
Him, yeah that seems like a better alternative :-)

**Comment by JamesCoyle** [comment]
As we've been a bit more lenient with the guidelines for some of the brand icons, something like this may be doable but I'm not sure it really scales down to 24px well enough. My badly made image with bitmap scaling loses a bit too much detail but SVG may handle better. 
![image](https://cloud.githubusercontent.com/assets/10384436/17650241/c8b0d7f6-6240-11e6-8818-86f351b419a6.png)

If not it might be worth aliasing the alpha icon so this issue can be closed. 
[![alpha](https://materialdesignicons.com/icon/alpha)](https://materialdesignicons.com/icon/alpha)

**Comment by GreenTurtwig** [comment]
Accidentally closed it while reading through my old "requests".

**Comment by Templarian** [comment]
Nah, this is just too much detail for the 24x24 size. It's a great site/service, but unfortunately won't fit.
