### ISSUE TITLE
market icon

### ISSUE THREAD

**Issue by newerton** [Templarian/MaterialDesign#1131]
https://cdn2.iconfinder.com/data/icons/picons-essentials/71/store-512.png
with one user or fruit

**Comment by CoDEmanX** [comment]
Maybe this? https://design.google.com/icons/#ic_store_mall_directory

**Comment by newerton** [comment]
@CoDEmanX Perfect! :+1:

**Comment by CoDEmanX** [comment]
It's already in MDI: https://materialdesignicons.com/icon/store

I'd like to keep this open however, because I think there could also be a market stand icon (to represent a small business).

**Comment by newerton** [comment]
@CoDEmanX Sorry! I had not found!

**Comment by MrGrigri** [comment]
I'm going to close this one.
