### ISSUE TITLE
Add Sigma and Lambda icons

### ISSUE THREAD

**Issue by bebenins** [Templarian/MaterialDesign#1132]
Std:  σ (sigma)
Ave:  λ (lambda)

**Comment by OlsonDev** [comment]
I hope this goes without saying, if these get added, they shouldn't be _named_ `standard-deviation` and `average`. :smile:

[Lambdas](https://en.wikipedia.org/wiki/Greek_letters_used_in_mathematics,_science,_and_engineering#.CE.9B.CE.BB_.28lambda.29) are used for _a lot_ more than averages; same goes for [sigma](https://en.wikipedia.org/wiki/Greek_letters_used_in_mathematics,_science,_and_engineering#.CE.A3.CF.83_.28sigma.29).

**Comment by bebenins** [comment]
Agreed.  Many folks can use them for different purposes.

**Comment by CoDEmanX** [comment]
There might be another request for Greek letters in general, and we should probably call them according to their Greek names (transliterated of course).

We can always add aliases if it facilitates the search.

**Comment by bebenins** [comment]
Ok, I didn't realize there was another request.  Feel free to close this one (or merge).
Thanks guys!

**Comment by CoDEmanX** [comment]
Sigma was requested in #1113, but other than that, there doesn't seem to be a request for lambda or any other Greek symbols. Therefore, let's keep this issue open.

**Comment by Fleker** [comment]
Wouldn't Greek symbols already be covered by a font?

**Comment by bebenins** [comment]
Yes, but font isn't exactly the same as a vector graphic packaged in this nice library.
For example, this icon library is integrated in this Material Design WPF library
https://github.com/ButchersBoy/MaterialDesignInXamlToolkit
and there's a common method of using icons (icon color, size, etc. is automatically handled by this library).  It's doable with font but it's a "hack" in that case

**Comment by Templarian** [comment]
[![sigma-lower](https://materialdesignicons.com/icon/sigma-lower)](https://materialdesignicons.com/icon/sigma-lower) [![lambda](https://materialdesignicons.com/icon/lambda)](https://materialdesignicons.com/icon/lambda)
