### ISSUE TITLE
New Icons for Temples

### ISSUE THREAD

**Issue by plunkertest** [Templarian/MaterialDesign#1135]
New icons similar to a Hindu Temple and Other Temples + Monuments would be good. Here are some links to follow up:
http://classroomclipart.com/images/gallery/Clipart/Religion/hindu-temple-clipart.jpg
http://thumbs.dreamstime.com/t/illustration-temple-3478087.jpg
https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTECdXhd3L4EqCgF2KWmK6BN3aW82DXihVLO6amPBWt6qJ_0auvXQ

**Comment by CoDEmanX** [comment]
There's another request for a (single) temple: #1070

**Comment by JamesCoyle** [comment]
I'm gonna close this one out as I'm not really sure it's possible to show this within the 24x24 grid. If anyone has any workable ideas please feel free to post them and we'll reopen.
