### ISSUE TITLE
Backpacker / Hiker

### ISSUE THREAD

**Issue by Fleker** [Templarian/MaterialDesign#1136]
A backpack icon would be a more human design compared to a box, to imply things like hiking, traveling, or studentry more than a briefcase.

**Comment by CoDEmanX** [comment]
Would the hiker icon from Google Maps work? (We don't have it yet)
https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-188516176

**Comment by Fleker** [comment]
Yeah I think that's relatively close

**Comment by derwaldgeist** [comment]
Would love to see it too. I think the hiker icon would work in some cases. But I would still love to see a backpack icon, too. I need it for a traveling app where backpacking is one of the types of travel. An icon for hiking wouldn't match here.

**Comment by CoDEmanX** [comment]
Google Maps app: ![hiker](https://cloud.githubusercontent.com/assets/1309249/13305037/c7b9efb4-db58-11e5-8698-2f4baea01011.png)

We don't have the source file unfortunately. It's also not in the browser version.

**Comment by David-Jackson** [comment]
So we have a couple of choices, the Google Fit app uses this hiking icon: 

![image](https://user-images.githubusercontent.com/11835431/45377335-488bac80-b5c8-11e8-9a95-b05b108f509d.png)
[google-fit-hiking.zip](https://github.com/Templarian/MaterialDesign/files/2372114/google-fit-hiking.zip)

While Google Maps uses something more like this: 

![image](https://user-images.githubusercontent.com/11835431/45377567-f9924700-b5c8-11e8-9b3f-f8b2a7fc877d.png)
[google-maps-hiking.zip](https://github.com/Templarian/MaterialDesign/files/2372115/google-maps-hiking.zip)

**Comment by JamesCoyle** [comment]
The maps one looks best IMO.

**Comment by PeterShaggyNoble** [comment]
I vote for the one from Maps, too; the other one is too stooped.

**Comment by goyney** [comment]
See also: #2473

**Comment by Templarian** [comment]
[![hiking](https://materialdesignicons.com/icon/hiking)](https://materialdesignicons.com/icon/hiking)
