### ISSUE TITLE
SOS Icon

### ISSUE THREAD

**Issue by gldraphael** [Templarian/MaterialDesign#1138]
Could add an SOS icon, or something on those lines to represent an emergency.

**Comment by Templarian** [comment]
Text based icons are not being included, but if you can link example images of pictographs that might work we can try and include those.

**Comment by gldraphael** [comment]
Something like this maybe?
<https://thenounproject.com/term/emergency/2039/>

**Comment by CoDEmanX** [comment]
I posted another example of an emergency light over here:
https://github.com/Templarian/MaterialDesign/issues/733#issuecomment-145871296

**Comment by PeterShaggyNoble** [comment]
[`alarm-light`](https://materialdesignicons.com/icon/alarm-light) has since been added.

See also [`alarm-bell`](https://materialdesignicons.com/icon/alarm-bell) and [`lifebuoy`](https://materialdesignicons.com/icon/lifebuoy).
