### ISSUE TITLE
Mixing Bowl Icon

### ISSUE THREAD

**Issue by Jargonius** [Templarian/MaterialDesign#1139]
I used the pharmacy icon as a base and modified it to make this first one.
![mixing bowl1](https://cloud.githubusercontent.com/assets/6412293/14300602/b4176692-fb4e-11e5-9fa3-c5ebe487e324.png)
I further refined the first one to create this one
![mixing bowl2](https://cloud.githubusercontent.com/assets/6412293/14300603/b417c8c6-fb4e-11e5-86fb-fb66b78bb44a.png)
I've now elongated the second design to make the icon a little bit more substantial. 
![mixing bowl3](https://cloud.githubusercontent.com/assets/6412293/14324400/dd9fad42-fbe1-11e5-8c2a-4eb0d1f6d00e.png)

[mixing_bowl.zip](https://github.com/Templarian/MaterialDesign/files/206853/mixing_bowl.zip)

**Comment by Jargonius** [comment]
I need to add the contribution label.

**Comment by PeterShaggyNoble** [comment]
Would the bowl from https://materialdesignicons.com/icon/food-variant do the job?

**Comment by Jargonius** [comment]
I did notice the similarity.  It's not quite the same but it could work.  I would make it a bit more substantial to use the available space and then it would look a lot like mine anyway.

**Comment by CoDEmanX** [comment]
@Jargonius: Do you want to give it a shot and create an icon based on the bowl seen in `food-variant`?

**Comment by Templarian** [comment]
[![bowl](https://materialdesignicons.com/icon/bowl)](https://materialdesignicons.com/icon/bowl)

Open an issue once you have 5 icons and I'll create and assign this over.
