### ISSUE TITLE
Spotlight Icon Request

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#114]
Good example of what I am looking for:
https://play.google.com/store/apps/details?id=com.motorola.avatar&hl=en

Diagonal variant would be nice. I am looking to use this in a timely manner. Any estimation of time to produce would be helpful.

**Comment by danielhickman** [comment]
P.S. I'll be donating later. Lovely work. Thanks a bunch

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/spotlight
http://materialdesignicons.com/icon/spotlight-beam (not really a fan of this icon, but can't think of how to design it differently).

You are officially the first person to donate (it has no effect on when icon requests get done). Thanks.
