### ISSUE TITLE
Control / Settings Icon

### ISSUE THREAD

**Issue by jimbojones007** [Templarian/MaterialDesign#1140]
An Icon, that shows that the user has control over the settings, similar to an Equalizer

**Comment by CoDEmanX** [comment]
Like this?
https://design.google.com/icons/#ic_tune

That one is one the TODO list of #420.

**Comment by jimbojones007** [comment]
Thanks, that does it indeed.

**Comment by Templarian** [comment]
[![tune](https://materialdesignicons.com/icon/tune)](https://materialdesignicons.com/icon/tune)
