### ISSUE TITLE
Add Run-To icon

### ISSUE THREAD

**Issue by bebenins** [Templarian/MaterialDesign#1142]
![image](https://cloud.githubusercontent.com/assets/16761301/14330676/b032e850-fc0f-11e5-9bb7-430fa7d2a939.png)

Something like ArrowDown but with a horizontal line on the bottom.  I'm not sure how else to represent Run To condition.  For example, I have a set of serial tests and I want an option to stop this sequence and any selected test (instead of running all tests).

Thank you

**Comment by OlsonDev** [comment]
I'm guessing this won't suffice but did you see https://materialdesignicons.com/icon/pause-octagon?

**Comment by bebenins** [comment]
That's actually what I'm using at the moment but it's not really a Pause but rather a Stop.

I could have used the stop sign shaped octagon if that was the only action I needed but I also need the ArrowDown (as pictured above) command that indicated to keep going.  So it would look better/more consistent if I had that combination above.
Thanks for the suggestion!

**Comment by CoDEmanX** [comment]
How about one of the following?

https://materialdesignicons.com/icon/download
https://materialdesignicons.com/icon/debug-step-into
https://materialdesignicons.com/icon/format-vertical-align-bottom

**Comment by OlsonDev** [comment]
Another way I've seen unit test runners approach it is two stacked+staggered play icons meaning "Run all" and a single one either meaning "Run just this test" or "Run this group of tests, but not all". Given your tests are serial, I'm not sure that applies...? Just a thought.

Or... @CoDEmanX's suggestions are all similar to your original request. :laughing:

**Comment by bebenins** [comment]
Man, I don't know how I missed those icons that already exist... My eyes were just glazing over (so many LOL) and I completely missed them.  I think I can make use of one of those!
Thanks all!

**Comment by bebenins** [comment]
Is there a way to close this issue?  I don't see this option for myself
