### ISSUE TITLE
Icons with Letters of the alphabet

### ISSUE THREAD

**Issue by Tonyo-Arg** [Templarian/MaterialDesign#1143]
The idea is a set of icons with the letters of the alphabet to synthesize very usable actions or events difficult to find as graphics

**Comment by Tonyo-Arg** [comment]
![a_on](https://cloud.githubusercontent.com/assets/18320381/14339823/033d4250-fc58-11e5-8900-55a1c7133ec3.gif)
![d_on - copia](https://cloud.githubusercontent.com/assets/18320381/14339826/03416934-fc58-11e5-9c62-a868c6944352.jpg)
![e_on](https://cloud.githubusercontent.com/assets/18320381/14339828/0341eb3e-fc58-11e5-8a1d-66766b30fc55.jpg)
![i_on](https://cloud.githubusercontent.com/assets/18320381/14339824/033fc408-fc58-11e5-8933-2818565ff28e.gif)
![n_on](https://cloud.githubusercontent.com/assets/18320381/14339827/03420a06-fc58-11e5-8326-50142f7b7928.gif)
![r_on](https://cloud.githubusercontent.com/assets/18320381/14339825/03414878-fc58-11e5-9b03-cb8c58859ee8.gif)
![t_on](https://cloud.githubusercontent.com/assets/18320381/14339829/03603698-fc58-11e5-8079-40ad475251fc.jpg)

**Comment by Tonyo-Arg** [comment]
Pruebas

**Comment by Tonyo-Arg** [comment]
![a_on](https://cloud.githubusercontent.com/assets/18320381/14339855/3eb9da8c-fc58-11e5-86c8-c979c701ef4d.gif)
![c_off](https://cloud.githubusercontent.com/assets/18320381/14339858/3ebc05c8-fc58-11e5-9bc7-1d4db9054e1b.jpg)
![d_off - copia](https://cloud.githubusercontent.com/assets/18320381/14339856/3ebacf1e-fc58-11e5-9910-0f02ad177a2b.jpg)
![e_on](https://cloud.githubusercontent.com/assets/18320381/14339859/3ebc515e-fc58-11e5-9e16-fbab361d45ee.jpg)
![i_on](https://cloud.githubusercontent.com/assets/18320381/14339860/3ebd7462-fc58-11e5-85ee-b4e9bda64009.gif)
![n_on](https://cloud.githubusercontent.com/assets/18320381/14339857/3ebbff38-fc58-11e5-8027-e90e61ea7a5d.gif)
![o_on](https://cloud.githubusercontent.com/assets/18320381/14339862/3edbea6e-fc58-11e5-9b68-085e73c675eb.gif)
![r_on - copia](https://cloud.githubusercontent.com/assets/18320381/14339863/3edd6b96-fc58-11e5-9ea3-c3f466c7b10c.gif)
![t_on](https://cloud.githubusercontent.com/assets/18320381/14339861/3edb7854-fc58-11e5-9fc5-a875614e355e.gif)

**Comment by Templarian** [comment]
Just for those that found this (probably the reason @Tonyo-Arg closed it, duplicate of #911).
