### ISSUE TITLE
optimised svg for text_field

### ISSUE THREAD

**Issue by nathanvv** [Templarian/MaterialDesign#1144]
https://design.google.com/icons/#ic_text_fields

**Comment by Templarian** [comment]
Had to do a double take. It is not the same as https://materialdesignicons.com/icon/format-size

**Comment by CoDEmanX** [comment]
Looks like it's simply mirrored.

I can't find it in our #420 spreadsheet... does Google call the file differently?

**Comment by Templarian** [comment]
https://design.google.com/icons/#ic_format_size and https://design.google.com/icons/#ic_text_fields

**Comment by CoDEmanX** [comment]
There's no "field" in the spreadsheet, I added it now in row 848.
