### ISSUE TITLE
Cooking Pot Icon

### ISSUE THREAD

**Issue by Jargonius** [Templarian/MaterialDesign#1145]
Here is my rendition of a pot.
![pot](https://cloud.githubusercontent.com/assets/6412293/14361176/fd47bdbc-fcb6-11e5-8b17-950913d2740c.png)
[pot.zip](https://github.com/Templarian/MaterialDesign/files/208907/pot.zip)

**Comment by Jargonius** [comment]
I need the contribution label again.

**Comment by CoDEmanX** [comment]
It could be even more minimalist for my taste. Maybe make the lid a simple rectangle, or remove it altogether and have some wavy strokes to depict water steam?

**Comment by Templarian** [comment]
If there was a way to get steam lines above it, that would probably work much nicer in cooking apps also.

**Comment by Jargonius** [comment]
I'll make a variant with the steam lines.

**Comment by CoDEmanX** [comment]
It doesn't work well at 24 pixels I'm afraid:

![cooking-pot](https://cloud.githubusercontent.com/assets/1309249/14412540/26419804-ff65-11e5-850b-8927d31bdf92.png) ![cooking-pot2](https://cloud.githubusercontent.com/assets/1309249/14412544/2644c876-ff65-11e5-9387-4e3b6058f8fd.png) ![cooking-pot3](https://cloud.githubusercontent.com/assets/1309249/14412542/2642d520-ff65-11e5-8d44-c3526b887e13.png) ![cooking-pot4](https://cloud.githubusercontent.com/assets/1309249/14412543/264422a4-ff65-11e5-94c8-3c6fbdc8ed65.png) ![cooking-pot5](https://cloud.githubusercontent.com/assets/1309249/14412541/2642911e-ff65-11e5-88f0-b3cd413774ac.png)

![cooking-pot](https://cloud.githubusercontent.com/assets/1309249/14412621/de1aa8c0-ff66-11e5-87cf-f25f06d9179c.png) ![cooking-pot2](https://cloud.githubusercontent.com/assets/1309249/14412617/de16b3c8-ff66-11e5-83cf-acf08e02912d.png) ![cooking-pot3](https://cloud.githubusercontent.com/assets/1309249/14412618/de16ff68-ff66-11e5-97c7-f35eac6147c1.png) ![cooking-pot4](https://cloud.githubusercontent.com/assets/1309249/14412619/de179a86-ff66-11e5-8c26-9919e3356e19.png) ![cooking-pot5](https://cloud.githubusercontent.com/assets/1309249/14412620/de189850-ff66-11e5-987e-e94af2889b81.png)

**Comment by Jargonius** [comment]
So what should I do?  Is my version good?

**Comment by CoDEmanX** [comment]
Different approach: ![cooking-pot6](https://cloud.githubusercontent.com/assets/1309249/14767902/286e4f1e-0a32-11e6-8cd7-1263ef6c021f.png) ![cooking-pot7](https://cloud.githubusercontent.com/assets/1309249/14767903/2884daea-0a32-11e6-9b0d-9ddd19fc6f5d.png)

**Comment by Templarian** [comment]
Actually I like that way more @CoDEmanX, nice iteration on the idea.

**Comment by Templarian** [comment]
[![pot](https://materialdesignicons.com/icon/pot)](https://materialdesignicons.com/icon/pot) [![pot-mix](https://materialdesignicons.com/icon/pot-mix)](https://materialdesignicons.com/icon/pot-mix)
