### ISSUE TITLE
Health Icons

### ISSUE THREAD

**Issue by kentonbmax** [Templarian/MaterialDesign#1146]
Icons with + or - in the middle. For starters using the shield.

**Comment by CoDEmanX** [comment]
Wouldn't that rather look like "add security"?

Can you give more detailed examples?

**Comment by kentonbmax** [comment]
Its all about context. Shield with different icons in the center and different colors, means different context. Other examples would be Dr. bag with + or - in the middle, and heart with pulse in middle.

**Comment by CoDEmanX** [comment]
I would find an icon "shield-plus" still confusing in a health context. Is it supposed to mean "add / increase health"? But that doesn't make sense, you can't add health to something other than characters in video games, and you can't become healthy just like that, with a click of your mouse...

A doctor's bag is hard to do in MD style, but a valid request. Shield plus/minus could probably be used in a few contexts, but @Templarian isn't keen to add lots of "add" and "remove" icon variants to MDI.

**Comment by GreenTurtwig** [comment]
These two should satisfy the request. :cat2:
[![](https://materialdesignicons.com/icon/medical-bag)](https://materialdesignicons.com/icon/medical-bag)[![](https://materialdesignicons.com/icon/heart-pulse)](https://materialdesignicons.com/icon/heart-pulse)

**Comment by CoDEmanX** [comment]
I came across a heart icon with a plus in the middle to represent benefits / additional health services in an HR software. `heart-pulse` doesn't cut, `medical-bag` does I guess but could be mistaken for "add to shopping bag".

![grafik](https://user-images.githubusercontent.com/1309249/72267011-99c60900-361f-11ea-8e43-787d91700551.png)

[heart-plus.zip](https://github.com/Templarian/MaterialDesign/files/4054242/heart-plus.zip)

**Comment by goyney** [comment]
@CoDEmanX See https://github.com/Templarian/MaterialDesign/issues/1512. We rejected this in the past.

**Comment by CoDEmanX** [comment]
That's a pretty different request:

> A heart with a small plus in the top-right corner to use for "Add to favorites"

**Comment by Templarian** [comment]
Yeah, this is probably fine to add. Just add the other variants `remove` and `minus`.

**Comment by goyney** [comment]
Adding plus, minus, and remove of `heart` and `heart-outline`.
