### ISSUE TITLE
Elder icons + Injuries icons

### ISSUE THREAD

**Issue by vitoralvesr** [Templarian/MaterialDesign#1147]
Could add icons that represents elder people and injuries?
I work in a Hospital and i need to represent elder people in an App that i'm developing.
About injuries i need something like "broken-leg", "broken-arm", etc., cause the elder can notify his(her) doctor if (s)he fell to ground.
Sorry about my english, btw.

**Comment by CoDEmanX** [comment]
To make this work at a native size of 24px (or rather 20), it would require a rather drastic depiction I'm afraid - can't get the picture of a stick figure out of my head, with the lower half of the arm disconnected and dangling around :anguished:

**Comment by vitoralvesr** [comment]
hahahahah i understand your point, may i have expressed myself wrong.
About a "broken-leg" i wanted to say 'someone with a "bandaged" leg', like when you broke some part of your body and the doctors involve that with some plaster (i don't know if in you country/city they use plaster for this. Understand plaster like a stabilizer(?)), not someone with an disconnected arm dangling around :sweat_smile::sweat_smile::sweat_smile:

**Comment by OlsonDev** [comment]
Why not just a picture of a leg, arm, etc.? Why does the icon have to imply "injured"?

**Comment by goyney** [comment]
Injuries icons will be added in #1416.
