### ISSUE TITLE
Contributions for consideration

### ISSUE THREAD

**Issue by jfoxtail** [Templarian/MaterialDesign#1148]
#contribution
![probe](https://cloud.githubusercontent.com/assets/8354098/14393707/29da498c-fd7d-11e5-96d7-8d4dd778189c.png)
![packageinstalled](https://cloud.githubusercontent.com/assets/8354098/14393715/3375237c-fd7d-11e5-86b3-775ae30727a1.png)
![saveas](https://cloud.githubusercontent.com/assets/8354098/14393719/3ca43992-fd7d-11e5-972c-f55b668b3e50.png)
![telecoil](https://cloud.githubusercontent.com/assets/8354098/14393727/46f1e14c-fd7d-11e5-9a74-f9a1de6cbe8a.png)
![subscriber](https://cloud.githubusercontent.com/assets/8354098/14393739/5337a360-fd7d-11e5-820c-7a705209c03b.png)
![ldap](https://cloud.githubusercontent.com/assets/8354098/14393804/ae105908-fd7d-11e5-85a6-b763034a0b13.png)

**Comment by Templarian** [comment]
Contributions need to be in the Material Design standard. Please post the name of the icons if this is a request. Thanks.

[Learn more about system icons here](https://www.google.com/design/spec/style/icons.html#icons-system-icons)

**Comment by CoDEmanX** [comment]
Furthermore, they should be provided as vector graphics in SVG format.
