### ISSUE TITLE
Irradescent light icon: name misspelled

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#1149]
There's an open issue upstream:
https://github.com/google/material-design-icons/issues/85

It seems that it has already been renamed:
https://design.google.com/icons/#ic_wb_iridescent

"fluorescent" appears to be more common than "iridescent" however:
http://www.digitalcameraworld.com/2014/01/31/white-balance-explained-how-your-camera-corrects-the-colour-of-different-kinds-of-lighting/

**Comment by Templarian** [comment]
Renamed (making it consistent with Google, so not renaming it to `fluorescent`).
