### ISSUE TITLE
Weibo social icon

### ISSUE THREAD

**Issue by he9qi** [Templarian/MaterialDesign#1150]
A Weibo (www.weibo.com) material icon would be nice! =)
here's svg sample: [weibo.svg.zip](https://github.com/Templarian/MaterialDesign/files/211926/weibo.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Closing this one out as a duplicate of #2235.

**Comment by MrGrigri** [comment]
Closing in favor of #2235.
