### ISSUE TITLE
Server Upgrade

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1151]
Due to increased users and future features we need _way more_ CPU.
- [ ] Setup environment on new host.
- [ ] Fully test all current features and cache still works.
- [ ] Stress test database calls.
- [ ] Switch DNS

**Comment by CoDEmanX** [comment]
Maybe it's possible to move some tasks to the client side to reduce the server load?

It can also help to reduce the number of requests to the web server and database - don't know what you already do behind the scenes though.

**Comment by Templarian** [comment]
There is very little request wise. My current host is still using hard disks and a single core. Simply moving to a host with SSD/2 core setup should speed things up.

I have some features coming in the future that will require more CPU.
