### ISSUE TITLE
New social icons

### ISSUE THREAD

**Issue by ezugo** [Templarian/MaterialDesign#1152]
Nice to have a  best friend (bff), just a friend, frenemy, acquaintance, enemy icons

**Comment by Templarian** [comment]
We probably need some example images for what these might look like.

**Comment by ezugo** [comment]
Unfortunately, I am not the best designer ...honestly not sure I know how it will look. Was relying on the great designers out there to provide some rendering...I can review ... is this doable?

**Comment by Templarian** [comment]
Nah, just go out on google images and find images you think would look kind of close. We'll do the rest. Just need to get a feel for what you mean. :smile:

**Comment by ezugo** [comment]
Sounds good. I will look it up and update this thread...Thanks

**Comment by JamesCoyle** [comment]
Possibly account multiple with a heart, checkmark, and cross would work?

**Comment by Templarian** [comment]
Closing this issue (cleaning up the backlog).

Please open individual icon requests for each of these if they are still needed (with examples).
