### ISSUE TITLE
Advance Export not responding

### ISSUE THREAD

**Issue by Alipoodle** [Templarian/MaterialDesign#1153]
I tried to open the Advance Export when I had my window tapped to 50% of the screen on Windows 10 but it failed to.  For some reason, when the site isn't taking up around 66% of my 1080p display the button won't respond...
It looks a little like this: 
![githuberror](https://cloud.githubusercontent.com/assets/17199186/14426688/8de91558-ffe8-11e5-8822-b1f0aa89b5aa.png)

However after giving Chrome a little more room it is opens.
![githuberror2](https://cloud.githubusercontent.com/assets/17199186/14426798/09ccaa7c-ffe9-11e5-99f2-4a924e1ed30c.png)

the one difference is that the Description is in line with the icons.

**Comment by Templarian** [comment]
Looks like the elements are overlapping each other. That's a bug.

I'm actually in the process of switching servers due to the site's increased traffic, but will try and get a fix in for this shortly.

**Comment by goyney** [comment]
This won't be an issue when the new site (#5161) is released, which is getting pretty close. We're not going to try and fix the old site anymore since it's going away. Closing.
