### ISSUE TITLE
Icon request: Restaurant table + chair

### ISSUE THREAD

**Issue by pjfsilva** [Templarian/MaterialDesign#1155]
For a kind of Point of sale app, it would be useful to have a restaurant table and a chair icon that works well in small sizes.

Some inspiration for table:
- https://icons8.com/web-app/543/table (maybe can even be further simplified so it works better in smaller sizes)
- https://www.iconfinder.com/icons/83022/table_icon#size=26

And for chair:
- https://www.iconfinder.com/icons/624743/chair_furniture_seat_sit_icon#size=32 (straight lines and simple integrates better with material design)
- https://www.iconfinder.com/icons/194608/chair_icon#size=32

**Comment by OlsonDev** [comment]
Those tables would violate this best practice:

![image](https://cloud.githubusercontent.com/assets/308072/14446616/b4a7044a-001d-11e6-9881-72ab9cc62f27.png)

A side-view would suffice, I think.

**Comment by CoDEmanX** [comment]
Related request: restaurant table #624

**Comment by goyney** [comment]
As CoDEmanX has linked, this issue is a duplicate of #624. Please follow that issue for when the icon is added to the library. Thanks!
