### ISSUE TITLE
Brand Icon Requests

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1157]
Just a few brand icons to consider adding:
- [ ] [Discogs](https://www.discogs.com/)
- [ ] [eBay](http://www.ebay.com/)
- [ ] [Ello](https://ello.co/)
- [ ] ~~[500px](https://500px.com/)~~ **[#532](https://github.com/Templarian/MaterialDesign/issues/532)**
- [ ] ~~[Flickr](https://www.flickr.com/)~~ **[#409](https://github.com/Templarian/MaterialDesign/issues/409)**
- [ ] [Goodreads](http://www.goodreads.com/)
- [ ] [Google Analytics](http://www.google.com/analytics/)
- [ ] [Image Comics](https://imagecomics.com/)
- [ ] [Just-Eat](http://www.just-eat.com/)
- [ ] [Lego](https://www.lego.com/)
- [ ] [MailChimp](http://mailchimp.com/)
- [ ] [Marvel](http://marvel.com/)
- [ ] [Meetup](http://www.meetup.com/)
- [ ] [MySQL](http://www.mysql.com/)
- [ ] [Netflix](https://www.netflix.com/)
- [ ] ~~[PayPal](https://www.paypal.com/)~~ **[#297](https://github.com/Templarian/MaterialDesign/issues/297)**
- [ ] [phpMyAdmin](https://www.phpmyadmin.net/)
- [ ] [Shopify](https://www.shopify.com/)
- [ ] ~~[TripAdvisor](https://www.tripadvisor.com/)~~ **[#331](https://github.com/Templarian/MaterialDesign/issues/331)**
- [ ] [Viber](http://www.viber.com/)
- [ ] [Yahoo](https://yahoo.com/)

**Comment by PeterShaggyNoble** [comment]
Added Ello, Lego, Netflix & Viber.

**Comment by albertogasparin** [comment]
Periscope would be nice too

**Comment by Templarian** [comment]
Going to close this issue out. We need to track each of these in separate issues or it's going to get messy to track. Reopening the Netflix icon suggestion.

**Comment by PeterShaggyNoble** [comment]
Do you want me to create individual issues for them, @Templarian or will you do it?

**Comment by Templarian** [comment]
@PeterShaggyNoble You can create issues for the remaining ones. Thanks!

**Comment by PeterShaggyNoble** [comment]
OK, leave it with me. I'll see if I can source SVGs for each while I'm at it, so might take a few days.

**Comment by PeterShaggyNoble** [comment]
OK, that's it for now.

- I can't find a decent version of the phpMyAdmin icon.
- Just-Eat have recently rebranded and their icon is now a wheel of colour, which obviously won't work. Unless we can just use the "J" from their logo.
- Mailchimp's monkey icon just isn't going to work at a small size.
- And, in hindsight, Image, Lego & Marvel may be too specific and beyond the scope of this project.
