### ISSUE TITLE
Round Comment Icon

### ISSUE THREAD

**Issue by pavanmehtamca** [Templarian/MaterialDesign#1159]
Roundish comment like is needed, like we used to have in Google talk for desktop

**Comment by PeterShaggyNoble** [comment]
[hangouts](https://materialdesignicons.com/icon/hangouts) might suit your needs, even if only as a stop-gap.

**Comment by pavanmehtamca** [comment]
I forgot to add comment like ICON.
something similar to 
![chat icon](https://cloud.githubusercontent.com/assets/15158552/14458440/c53b668c-00ce-11e6-953f-7b478e8acb7c.PNG)

**Comment by pavanmehtamca** [comment]
Oh yeah thanks for the help. It certainly helps.

**Comment by CoDEmanX** [comment]
Not sure about this, rectangular works way better for Material Design. It simply looks sharper on regular density screens.

**Comment by pavanmehtamca** [comment]
CodeManx, I don't disagree with you here. But the client's requirement is the rounded ones.
