### ISSUE TITLE
Please Add Arduino Icon

### ISSUE THREAD

**Issue by riaandeyzel** [Templarian/MaterialDesign#1160]
Good day

Please add an Arduino micro Controller Icon.
Link here: http://www.arduino.cc/

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/raspberrypi ?

They look pretty similar, you might be able to just use this one.

**Comment by riaandeyzel** [comment]
Thanks for the reply.

The Problem is I am using a Raspberry pi in my project as well, and already using that icon.

Kind regards,
Riaan

**Comment by CoDEmanX** [comment]
Maybe use the brand logos instead?

**Comment by riaandeyzel** [comment]
Thanks for the reply.

Where do I find the Brand Logos?.
I want the site to have the same style icons, and can not use other color icons.
I would like to use Material Design Icons.

**Comment by Templarian** [comment]
@riaandeyzel He means, we could add the Arduino logo (infinite symbol with +/- in it) instead of something that looks like the chip.

**Comment by Templarian** [comment]
It might be difficult but we could also add a raspberry pi logo in. Maybe rename raspberry pi to something more generic like `iot`.

**Comment by riaandeyzel** [comment]
Thanks for the reply.
I like the Idea of the "(infinite symbol with +/- in it) " for Arduino and the Raspberry Pi Logo for the Raspberry Pi.

**Comment by CoDEmanX** [comment]
There's going to be a generic icon in MDI that might fit: https://design.google.com/icons/#ic_developer_board

**Comment by Templarian** [comment]
[![developer-board](https://materialdesignicons.com/icon/developer-board)](https://materialdesignicons.com/icon/developer-board)
