### ISSUE TITLE
Missing Google icon: help-outline

### ISSUE THREAD

**Issue by smpldsgn** [Templarian/MaterialDesign#1162]
This important Google icon is somehow missing: Help-outline (https://design.google.com/icons/#ic_help_outline)

**Comment by CoDEmanX** [comment]
It's tracked in #420

**Comment by CoDEmanX** [comment]
[![help-circle-outline](https://materialdesignicons.com/icon/help-circle-outline)](https://materialdesignicons.com/icon/help-circle-outline)
