### ISSUE TITLE
Switch Icons 

### ISSUE THREAD

**Issue by kentonbmax** [Templarian/MaterialDesign#1163]
![image](https://cloud.githubusercontent.com/assets/15804484/14471371/429442d8-00bc-11e6-8fcd-629324fca8c0.png)

http://www.dpaonthenet.net/article/57615/IDEC-offers-emergency-stop-switches-in-a-box.aspx

**Comment by CoDEmanX** [comment]
So a physical switch, or more like something you would use in a circuit diagram?

**Comment by kentonbmax** [comment]
both. Look for emergency switch, toggle, and the Frankenstein switch...

**Comment by JamesCoyle** [comment]
We now have this:
[![](https://materialdesignicons.com/icon/electric-switch)](https://materialdesignicons.com/icon/electric-switch)

Gonna close this out for now unless someone can come up with a better way to show a physical switch in the small canvas we have.
