### ISSUE TITLE
cat-off / pets not allowed

### ISSUE THREAD

**Issue by simkepal** [Templarian/MaterialDesign#1164]
It would be great to have icon of cat not allowed. Like cup and cup-off or smoking and smoking-off.

**Comment by CoDEmanX** [comment]
I can see that for a dog icon, because they aren't allowed in supermarkets etc., and it can stand for "no pets" in general. But cat? How many people walk their cat?

**Comment by simkepal** [comment]
I need it for the button,if pets are allowed  or not allowed. Like in the
hotel,car,etc. For me it is the same if it is a dog,cat or anything....
13. apr. 2016 11:32 dop. je oseba "CoDEmanX" <notifications@github.com>
napisala:

**Comment by CoDEmanX** [comment]
I see. Since we don't have a dog icon yet, cat-off would be less of an effort. cow-off and fish-off would be funnier though.

**Comment by simkepal** [comment]
Yes... I know that there is no dog icon yet. That is why is asked for
cat-off icon :)

2016-04-13 12:23 GMT+02:00 CoDEmanX <notifications@github.com>:

**Comment by CoDEmanX** [comment]
Maybe rather a generic `paw-off`?

![paw-off](https://cloud.githubusercontent.com/assets/1309249/14770981/36eba086-0a7e-11e6-9354-64c0bb856bd4.png) ![paw-off2](https://cloud.githubusercontent.com/assets/1309249/14770982/37017762-0a7e-11e6-92fe-7bdf66c2d659.png)

Might have to be updated if my paw icons is replaced by Google's version.

**Comment by simkepal** [comment]
Uuuuu, great... I like that solution.

**Comment by simkepal** [comment]
When will this be available?

**Comment by Templarian** [comment]
[![paw-off](https://materialdesignicons.com/icon/paw-off)](https://materialdesignicons.com/icon/paw-off)
