### ISSUE TITLE
New icon

### ISSUE THREAD

**Issue by arts-unimelb** [Templarian/MaterialDesign#1168]
Would love to have a new icon like the one attached Thank you Marcus
![icon-new](https://cloud.githubusercontent.com/assets/1032902/14517883/b82b2f94-0255-11e6-861f-5b2682e4ea44.jpg)

**Comment by Templarian** [comment]
With the limited sizing it's going to look odd. This might be one of those things that your better using css for.

https://materialdesignicons.com/icon/new-box We do have the stock google new icon.

**Comment by CoDEmanX** [comment]
... which is not pixel-perfect by the way.

**Comment by Templarian** [comment]
I'm going to close out this issue as it's not ideal for an icon.
