### ISSUE TITLE
For indicating Tax Amount or for Showing Showing Tax Calculated Amount. 

### ISSUE THREAD

**Issue by Manikanta139** [Templarian/MaterialDesign#1169]
In some cases like payment calculations for labor or items which we purchased we should show tax amount in payment summary, for that if is there any icon to for tax amount it will mean a lot. Thanks

**Comment by Templarian** [comment]
Do you have an example of what this may look like (images can be linked to or pasted inline comments)? We try to use text as the last available option as to keep thing agnostic to localisations.

**Comment by PeterShaggyNoble** [comment]
Would https://materialdesignicons.com/icon/percent serve your needs?

**Comment by Manikanta139** [comment]
have a look at the image which i sent, in that image we can use % symbol instead of dollar. its only my suggestion.


![money_png3545](https://cloud.githubusercontent.com/assets/10823924/14524535/7ee9a7c8-0256-11e6-870d-a1f0503fc081.png)

**Comment by CoDEmanX** [comment]
How about something along these lines?

![tax](http://t2.gstatic.com/images?q=tbn:ANd9GcS8MoCJyCjixJuoObPuFYmH4ol4kk7uCxWYRrT79e0C8JbB1O2M109F)

**Comment by goyney** [comment]
See #338.

**Comment by PeterShaggyNoble** [comment]
The `margin` icon may also be suitable here:

[![margin](http://mdi.houseofdesign.ie/tools/preview/?icon=margin&action=link)](https://materialdesignicons.com/icon/margin)

**Comment by goyney** [comment]
Yes, `margin` is a good fit here. Considering we have that and the request in #338, I'm going to close this issue. Please follow #338 if you would like to know when that icon gets added to the library.
