### ISSUE TITLE
Reset to default

### ISSUE THREAD

**Issue by DavidEdwards** [Templarian/MaterialDesign#1171]
An icon indicating that pressing this button will result in a reset to standard defaults.

The closest I found on the repository was "history". It _works_, but I am not certain it is the best example.

**Comment by Simran-B** [comment]
Maybe one of the following?

https://design.google.com/icons/#ic_restore_page

[![undo-variant](https://materialdesignicons.com/icon/undo-variant)](https://materialdesignicons.com/icon/undo-variant) [![undo](https://materialdesignicons.com/icon/undo)](https://materialdesignicons.com/icon/undo) [![sync](https://materialdesignicons.com/icon/sync)](https://materialdesignicons.com/icon/sync) [![recycle](https://materialdesignicons.com/icon/recycle)](https://materialdesignicons.com/icon/recycle) [![close](https://materialdesignicons.com/icon/close)](https://materialdesignicons.com/icon/close) [![reply](https://materialdesignicons.com/icon/reply)](https://materialdesignicons.com/icon/reply) [![replay](https://materialdesignicons.com/icon/replay)](https://materialdesignicons.com/icon/replay) [![pencil-off](https://materialdesignicons.com/icon/pencil-off)](https://materialdesignicons.com/icon/pencil-off) [![backup-restore](https://materialdesignicons.com/icon/backup-restore)](https://materialdesignicons.com/icon/backup-restore) [![backspace](https://materialdesignicons.com/icon/backspace)](https://materialdesignicons.com/icon/backspace)

**Comment by DavidEdwards** [comment]
backup-restore seems the most applicable from this list.

The others convey going back to a previous state (undoing) and not necessarily to the original state.

**Comment by CoDEmanX** [comment]
Related reads:

- [Killing the cancel button on forms for good](http://uxmovement.com/forms/killing-the-cancel-button-on-forms-for-good/)
- [Reset and cancel buttons](https://www.nngroup.com/articles/reset-and-cancel-buttons/)
