### ISSUE TITLE
New icon: Mixcloud

### ISSUE THREAD

**Issue by Branded89** [Templarian/MaterialDesign#1172]
Hi guys,

I just love these icons, and have been using them is several projects so far.
I was wondering if anyone is able to add another social media icon for the Mixcloud service.

eg.
https://www.google.nl/search?q=mixcloud+icon&espv=2&biw=1381&bih=801&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjct4zc7pDMAhVySZoKHUscBRwQ_AUIBigB

Thanks in advance!

**Comment by Templarian** [comment]
[![mixcloud](https://materialdesignicons.com/icon/mixcloud)](https://materialdesignicons.com/icon/mixcloud)
