### ISSUE TITLE
contribution: new icon face detection scan

### ISSUE THREAD

**Issue by mkosik** [Templarian/MaterialDesign#1173]
Context: PlayServices include Vision API that enables scan / detection of Barcodes / QRs and Faces.
https://developers.google.com/vision/
But there are only 3 icons currently in collection: barcode-scan, credit-card-scan, qrcode-scan
I would like to contribute face-detection-scan.
![face-scan](https://cloud.githubusercontent.com/assets/2512454/14570104/bb5df708-0342-11e6-967f-65557c7b5cf6.png)

**Comment by CoDEmanX** [comment]
I actually created an icon just like yours for this request: #1053

**Comment by mkosik** [comment]
ack
