### ISSUE TITLE
Language icons for C/C++ and XAML

### ISSUE THREAD

**Issue by danwalmsley** [Templarian/MaterialDesign#1176]
- [ ] language-c
- [ ] language-cpp
- [x] language-xml
- [x] language-xaml

**Comment by CoDEmanX** [comment]
There's already an icon for XML: https://materialdesignicons.com/icon/xml

**Comment by Templarian** [comment]
[![xaml](https://materialdesignicons.com/icon/xaml)](https://materialdesignicons.com/icon/xaml)

**Comment by Templarian** [comment]
[![language-c](https://materialdesignicons.com/icon/language-c)](https://materialdesignicons.com/icon/language-c) [![language-cpp](https://materialdesignicons.com/icon/language-cpp)](https://materialdesignicons.com/icon/language-cpp)
