### ISSUE TITLE
Alternate Filter Icon

### ISSUE THREAD

**Issue by dietrichg** [Templarian/MaterialDesign#1179]
I know we already have several filter icons, but this one is becoming more prevalent as well.
https://cdn1.iconfinder.com/data/icons/video-controls/32/filter-128.png

**Comment by Templarian** [comment]
This type of `filter` is more akin to video editing or audio mixing. Hmm... might be a better name for it. I like it as an icon, but need a name that fits it.

**Comment by CoDEmanX** [comment]
`tune-vertical`?
https://design.google.com/icons/#ic_tune

It would also work with round "knobs" I guess

**Comment by dietrichg** [comment]
Okay I like `knobs`, and then, `knobs-vertical` ?

**Comment by CoDEmanX** [comment]
![tune_vertical_round_96](https://cloud.githubusercontent.com/assets/1309249/14803137/4603af3a-0b57-11e6-84f3-f060bd8fcb59.png)
![tune_vertical_round](https://cloud.githubusercontent.com/assets/1309249/14803135/45d834a4-0b57-11e6-8354-7c45971b6232.png) not as good as I thought, to be honest

![tune_vertical](https://cloud.githubusercontent.com/assets/1309249/14803136/45f252a8-0b57-11e6-9810-09d670bf6c41.png) this works my better

I submitted the last one as part of #420.

**Comment by OlsonDev** [comment]
I can't understand `TIT` in that icon. :-\

**Comment by CoDEmanX** [comment]
:smile: should we flip it, so it reads `ITI`?

**Comment by OlsonDev** [comment]
Is it possible to make it look good as `TTT`…? Wasn't sure if knob position was selected due to a spacing restriction.

**Comment by CoDEmanX** [comment]
Yeah, most likely because of the limited space. It is possible, but it feels a bit odd:

![tune_vertical4](https://cloud.githubusercontent.com/assets/1309249/14832520/015d7402-0bfb-11e6-90e4-c11fc9a910a2.png) ![tune_vertical3](https://cloud.githubusercontent.com/assets/1309249/14832521/0160bebe-0bfb-11e6-8aba-1835eb8c8ed2.png) ![tune_vertical2](https://cloud.githubusercontent.com/assets/1309249/14832519/015bca26-0bfb-11e6-83f1-a73c48f57d85.png)

**Comment by OlsonDev** [comment]
Hmm, yeah, a little odd but not horrible. Would it violate MD or be inconsistent to just do the line through? I dunno, I just wanted to point out the "obvious" "inappropriate" word in the proposed design.

**Comment by CoDEmanX** [comment]
You mean like this? ![tune_vertical7](https://cloud.githubusercontent.com/assets/1309249/14833813/4fd1b854-0c01-11e6-85c8-448594527d7d.png)

Kinda works as well. I'm not too worried about consistency in this case.

**Comment by OlsonDev** [comment]
Indeed, that's what I meant. I like it. *Shrugs* :smile:

**Comment by dietrichg** [comment]
I like that too. the connected lines scale well.

**Comment by Templarian** [comment]
[![tune-vertical](https://materialdesignicons.com/icon/tune-vertical)](https://materialdesignicons.com/icon/tune-vertical)

**Comment by dietrichg** [comment]
Can this be added to the cdn css?
