### ISSUE TITLE
Playing card icons (generic playing hand, clubs, spades, hearts, diamonds)

### ISSUE THREAD

**Issue by tieskedh** [Templarian/MaterialDesign#1180]
I want to use a icon for blackjack.
Of course black jack is to specific for an icon, but it would be great to have a card-game icon.
thanks in advance.

**Comment by CoDEmanX** [comment]
Derived from https://design.google.com/icons/#ic_style :

![cards](https://cloud.githubusercontent.com/assets/1309249/14764950/ebd317e4-09cb-11e6-9272-02c97d883e9a.png) ![cards-outline](https://cloud.githubusercontent.com/assets/1309249/14764951/ebe8a5a0-09cb-11e6-9c0d-2673ad60a189.png) ![cards-outline-pique](https://cloud.githubusercontent.com/assets/1309249/14764952/ebf9509e-09cb-11e6-96d1-f8899f6c3b24.png)

![cards](https://cloud.githubusercontent.com/assets/1309249/14764961/161009c2-09cc-11e6-8a1e-b254a2578187.png) ![cards-outline](https://cloud.githubusercontent.com/assets/1309249/14764962/1625585e-09cc-11e6-8a64-b5a4fcc29bea.png) ![cards-outline-pique](https://cloud.githubusercontent.com/assets/1309249/14764963/163ab7da-09cc-11e6-8d05-1bae271a2069.png)

**Comment by Templarian** [comment]
I like the design a lot, but maybe just using a diamond instead of a spade?

**Comment by CoDEmanX** [comment]
![cards-outline-diamond](https://cloud.githubusercontent.com/assets/1309249/14770927/2895fc68-0a7c-11e6-8112-efe7cc37344d.png) ?

**Comment by Templarian** [comment]
Yea, should work. Upload the 3 and I'll get them added.

**Comment by CoDEmanX** [comment]
Nr. 3: https://www.dropbox.com/s/akze5wes8owbqif/cards-outline-diamond.design?dl=0
The other two are included in the 2nd batch of #420 (2016-04-25_Conversion.zip).

**Comment by Templarian** [comment]
[![cards](https://materialdesignicons.com/icon/cards)](https://materialdesignicons.com/icon/cards) [![cards-outline](https://materialdesignicons.com/icon/cards-outline)](https://materialdesignicons.com/icon/cards-outline) [![cards-playing-outline](https://materialdesignicons.com/icon/cards-playing-outline)](https://materialdesignicons.com/icon/cards-playing-outline)

**Comment by CoDEmanX** [comment]
@Templarian: the diamond is missing?

**Comment by Templarian** [comment]
@CoDEmanX Fixed.

**Comment by JamesCoyle** [comment]
Gonna close this and use #1578 for the suit icons instead. Keep this as just generic playing card icons.
