### ISSUE TITLE
Flexibility Icon

### ISSUE THREAD

**Issue by jimbojones007** [Templarian/MaterialDesign#1182]
I only have a vague idea but I would be very happy to find an icon that shows "flexibility". This is my best idea so far: (https://www.iconfinder.com/icons/320304/arrow_arrows_creative_direction_down_grid_left_line_match_mix_move_outline_right_shape_up_icon#size=128)

**Comment by PeterShaggyNoble** [comment]
Would `call-split`, `shuffle` or `shuffle-variant` suit your needs? See also MrGrigri's `decision` icons in #2762.

**Comment by CoDEmanX** [comment]
An interesting take, Metro kind of design?

![grafik](https://user-images.githubusercontent.com/1309249/42603994-ad128792-8570-11e8-8c90-550c58772133.png)

The reusability is also interesting

**Comment by goyney** [comment]
@jimbojones007 Would any of the `arrow-decision-*` icons or `call-split`, `shuffle`, or `shuffle-variant` fulfill your use case?

**Comment by PeterShaggyNoble** [comment]
Going to close this one out due to lack of feedback.
