### ISSUE TITLE
summation

### ISSUE THREAD

**Issue by amfp** [Templarian/MaterialDesign#1183]
There is an icon like this??

https://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Greek_uc_sigma.svg/200px-Greek_uc_sigma.svg.png

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/sigma I think you mean sigma.

We may want to alias that icon as `summation` though.

**Comment by amfp** [comment]
yess. Thank you

**Comment by Templarian** [comment]
Reopening until I add the alias.

**Comment by amfp** [comment]
??

**Comment by Templarian** [comment]
@amfp Oh, so the site allows the search results to be aliased. For instance people search for the word `search` a lot so we show them the `magnify` icon.

I keep stats on all searches to make sure we handle the most common search results, but whenever someone has an issue finding an icon that should be easy to find we add an alias.

**Comment by Templarian** [comment]
Added `summation` as an alias for `sigma`.
