### ISSUE TITLE
Home / House / Housing icon

### ISSUE THREAD

**Issue by safaorhan** [Templarian/MaterialDesign#1184]
A simple house icon may satisfy lots of needs of designers/developers.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/home
https://materialdesignicons.com/icon/home-variant
https://materialdesignicons.com/icon/home-modern

I think is what you mean. To make it easier I've added an alias `house` to each. This should make searching in the future easier (`house` will show `home` icons).

**Comment by CoDEmanX** [comment]
There's also `domain`, which looks like a building complex:
https://materialdesignicons.com/icon/domain

Other buildings:
https://materialdesignicons.com/icon/hospital-building
https://materialdesignicons.com/icon/factory
https://materialdesignicons.com/icon/store-24-hour
https://materialdesignicons.com/icon/store

**Comment by CoDEmanX** [comment]
Another one:
https://materialdesignicons.com/icon/city
