### ISSUE TITLE
Auth0 Icon

### ISSUE THREAD

**Issue by ritdaw** [Templarian/MaterialDesign#1189]
Would be great to have an Auth0 icon, very simple in design so shouldn't be an issue :)

https://auth0.com/

Obviously the text would need to be removed.
![image](https://cloud.githubusercontent.com/assets/2089152/14701129/8212e258-079b-11e6-840c-2f54e9d39f17.png)

**Comment by PeterShaggyNoble** [comment]
I'm going to close this one out for now. Per our [contributing guidelines](https://github.com/Templarian/MaterialDesign/blob/master/CONTRIBUTING.md):
> Please note that, at this time, the only brand icons we accept requests for are popular social media sites/apps and widely used products/software.

We may revisit this issue in the future, if we decide to add a dedicated icon pack for brands.
