### ISSUE TITLE
Become a Contributor (disabled) Question

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#119]
What does "Become a Contributor (disabled)" mean? Is it that you are no longer accepting requests? I want to help out but my svg files that are the exact size as it specifies and the template is, they wont upload. I figured they were linked. Is there a way to become a contributor?

**Comment by Templarian** [comment]
Test them over at http://materialdesignicons.com/custom

Then embed a couple of the 24x24 PNG's into a reply to this issue and I'll send an invite.

I'm not going to enable the contributor submission form until Beta. Too many of the admin features are still in flux and testing. Plus I don't have a GUI for the submission screen coded, ha.

**Comment by Templarian** [comment]
Open the SVG file and ensure it is 24x24 when exported and there is only a single path tag. Before exporting select all your objects and combine them to a single path. :smile:

**Comment by Templarian** [comment]
@danielhickman By the way, this pack is 3rd Party. If you could please **not** too aggressively post it over at the official Repo that would be appreciated. I actually have already added every suggestion mentioned over there.

**Comment by danielhickman** [comment]
Ah okay thanks. I'll be back in a bit to see if that helped.

**Comment by danielhickman** [comment]
This still didn't work.
https://drive.google.com/file/d/0B21PBxxpUkt-bXFDZnVfUE1HZFU/view?usp=sharing

**Comment by danielhickman** [comment]
Oh there are multiple path tags. Darn.

**Comment by danielhickman** [comment]
I got one to work! Wow I had to take out all of the meta data AI and Inkscape puts in there

**Comment by danielhickman** [comment]
Linode Logos!

![ic_linode_box_black_24dp](https://cloud.githubusercontent.com/assets/5341898/5893749/f6818c62-a4a4-11e4-9736-5992be737829.png)
![ic_linode_circle_black_24dp](https://cloud.githubusercontent.com/assets/5341898/5893751/fbf2618a-a4a4-11e4-8713-9aba971e4f4f.png)

**Comment by Templarian** [comment]
Inkscape is exporting some extra stuff in their SVG file that shouldn't be there. It is also exporting with percents for width's which is odd. I'll have to do some modifications on my side to handle that.

Also, that is not Linode's logo. I know it's tempting to redo a logo, but you can't do that. It's their brand.

Linode would look like this:
![image](https://cloud.githubusercontent.com/assets/338885/5893777/c50701f0-a4b6-11e4-84de-43f28efaeadf.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/linode

I actually did add it also (if you become a contributor I'll switch it to your account).

**Comment by Templarian** [comment]
By the way, hit me up on Skype if you want to chat. Username: `templarian.com`
