### ISSUE TITLE
file-remove

### ISSUE THREAD

**Issue by sqrt** [Templarian/MaterialDesign#1190]
Equivalent to e.g. folder-plus, folder-remove, folder-move, folder-upload and folder-download; but for files instead of folders

**Comment by CoDEmanX** [comment]
file-compare would also be useful, e.g. file-multiple with plus and minus (git diff style)

**Comment by CoDEmanX** [comment]
![file-compare_ 1190](https://cloud.githubusercontent.com/assets/1309249/14904492/ca5de3ba-0da8-11e6-9506-8b24c2d48901.png) ![file-compare2_ 1190](https://cloud.githubusercontent.com/assets/1309249/14904493/ca77e4ea-0da8-11e6-953e-9c1fa58801cb.png) ![file-compare3_ 1190](https://cloud.githubusercontent.com/assets/1309249/14904494/ca7f40e6-0da8-11e6-9842-68606cb3792d.png) ?

**Comment by PeterShaggyNoble** [comment]
Options for all of these have since been added except `file-remove` so going to use this issue to track that one. See also @MrGrigri's contribution in #1240.

If there are any others you would like added, please open a new issue for each one.

**Comment by Templarian** [comment]
[![file-remove](https://materialdesignicons.com/icon/file-remove)](https://materialdesignicons.com/icon/file-remove)
