### ISSUE TITLE
emailStates

### ISSUE THREAD

**Issue by Betalos** [Templarian/MaterialDesign#1191]
show the states of email : is send is error

**Comment by CoDEmanX** [comment]
letter + exclamation mark perhaps?

**Comment by Betalos** [comment]
Yes and the other states is received and so on .but in general a letter with a mark

**Comment by GreenTurtwig** [comment]
Would these do?

[![](https://materialdesignicons.com/icon/email-alert)](https://materialdesignicons.com/icon/email-alert)[![](https://materialdesignicons.com/icon/inbox-arrow-down)](https://materialdesignicons.com/icon/inbox-arrow-down)[![](https://materialdesignicons.com/icon/inbox-arrow-up)](https://materialdesignicons.com/icon/inbox-arrow-up)

**Comment by Betalos** [comment]
well perhaps include the mark in the letter ???
