### ISSUE TITLE
fire-hydrant

### ISSUE THREAD

**Issue by kallam505** [Templarian/MaterialDesign#1192]
Hello, is there is any shapes for valve or fire hydrants ?

**Comment by mikechoch** [comment]
I have created 3 example Fire Hydrants for displaying a sort of status.
**There is the normal active fire hydrant:**
![fire_hydrant_active](https://user-images.githubusercontent.com/24537305/39142239-0e4a2d1a-46f8-11e8-8c6a-4f0ceeb71ae6.png)

**There is the inactive fire hydrant:**
![fire_hydrant_inactive](https://user-images.githubusercontent.com/24537305/39142253-14dd150c-46f8-11e8-8f9f-b1c9345dfa00.png)

**And there is the critical/ maintenance required fire hydrant:**
![fire_hydrant_critical](https://user-images.githubusercontent.com/24537305/39142278-2bd3a42e-46f8-11e8-8e56-9b2a87b49d28.png)

Maybe someone can draw inspiration from these or I can email my psd files and you can create the icon I am very busy and no longer working on the project I used them for.

**Comment by goyney** [comment]
Refocused this issue for the inclusion of a fire hydrant. See #3071 for an issue requesting a water valve.

**Comment by JamesCoyle** [comment]
Need to get a more materialized version of those examples vectorized.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/62843355-512cad00-bc87-11e9-8da4-f86051796911.png)![image](https://user-images.githubusercontent.com/1015040/62843364-5a1d7e80-bc87-11e9-8cae-714c9da75e48.png)
![image](https://user-images.githubusercontent.com/1015040/62843372-61dd2300-bc87-11e9-8955-8aa1ad580398.png)

[fire-hydrant.zip](https://github.com/Templarian/MaterialDesign/files/3490880/fire-hydrant.zip)

**Comment by CoDEmanX** [comment]
Should it be a bit less minecrafty perhaps?

![grafik](https://user-images.githubusercontent.com/1309249/62866824-1d4a9980-bd12-11e9-9cdc-f37797bc0ca9.png)

**Comment by goyney** [comment]
Fire hydrants are usually built up in layers of metal rings, which is why I went more pixelated with the edges, but we could smooth them out too. 🤷‍♂

**Comment by goyney** [comment]
[![fire-hydrant](https://materialdesignicons.com/icon/fire-hydrant)](https://materialdesignicons.com/icon/fire-hydrant)[![fire-hydrant-off](https://materialdesignicons.com/icon/fire-hydrant-off)](https://materialdesignicons.com/icon/fire-hydrant-off)
[![fire-hydrant-alert](https://materialdesignicons.com/icon/fire-hydrant-alert)](https://materialdesignicons.com/icon/fire-hydrant-alert)
