### ISSUE TITLE
Music icons

### ISSUE THREAD

**Issue by brunocalou** [Templarian/MaterialDesign#1193]
Hey, nice icons!

I would like to request more specific music icons, like a metronome and more instruments (acoustic guitar, bass, piano, ...)

**Comment by goyney** [comment]
All the suggested instruments exist in the library:

- **Metronome**
  - https://materialdesignicons.com/icon/metronome
  - https://materialdesignicons.com/icon/metronome-tick
- **Guitar/Bass**
  - https://materialdesignicons.com/icon/guitar-acoustic
  - https://materialdesignicons.com/icon/guitar-electric
  - https://materialdesignicons.com/icon/guitar-pick
  - https://materialdesignicons.com/icon/guitar-pick-outline
- **Piano**
  - https://materialdesignicons.com/icon/piano

**Comment by PeterShaggyNoble** [comment]
If you have any additional requests, please create a new issue for each icon you require.
