### ISSUE TITLE
Apple Keys

### ISSUE THREAD

**Issue by nmsmith22389** [Templarian/MaterialDesign#1194]
# Apple Keys
_Note: Some of these may exist already but these are very literal versions and may be of use._
### Command
![apple-command-key](https://cloud.githubusercontent.com/assets/8648114/14765984/c4adaa00-09bf-11e6-9029-de68c4f3f567.png)
![apple-command-key 2x](https://cloud.githubusercontent.com/assets/8648114/14765983/c49ac0e8-09bf-11e6-960b-b4061a730513.png)
![apple-command-key 3x](https://cloud.githubusercontent.com/assets/8648114/14765981/c40f650c-09bf-11e6-8228-609884bc407e.png)
SVG: [apple-command-key.svg](https://www.dropbox.com/s/6b5h0wdylhnqifd/apple-command-key.svg?dl=0)

### Option
![apple-option-key](https://cloud.githubusercontent.com/assets/8648114/14766011/be864d16-09c0-11e6-80e8-1418b0be7042.png)
![apple-option-key 2x](https://cloud.githubusercontent.com/assets/8648114/14766013/be871214-09c0-11e6-9a2e-2bf560ec847e.png)
![apple-option-key 3x](https://cloud.githubusercontent.com/assets/8648114/14766012/be86f1bc-09c0-11e6-83e4-dc140cd2fe2e.png)
SVG: [apple-option-key.svg](https://www.dropbox.com/s/yqr8qzjilqnq312/apple-option-key.svg?dl=0)

### Control
![apple-control-key](https://cloud.githubusercontent.com/assets/8648114/14766019/e56fa580-09c0-11e6-843d-f7c4fef3ce53.png)
![apple-control-key 2x](https://cloud.githubusercontent.com/assets/8648114/14766020/e581012c-09c0-11e6-9e6f-aa095d3000eb.png)
![apple-control-key 3x](https://cloud.githubusercontent.com/assets/8648114/14766021/e58111f8-09c0-11e6-9910-9cf39b2708d2.png)
SVG: [apple-control-key.svg](https://www.dropbox.com/s/dxoa9m2n9t7o5wr/apple-control-key.svg?dl=0)

### Shift
![apple-shift-key](https://cloud.githubusercontent.com/assets/8648114/14766024/009bd824-09c1-11e6-9eac-cc190ca19cd3.png)
![apple-shift-key 2x](https://cloud.githubusercontent.com/assets/8648114/14766026/00a8f52c-09c1-11e6-9f50-009b660ea596.png)
![apple-shift-key 3x](https://cloud.githubusercontent.com/assets/8648114/14766025/00a8c2c8-09c1-11e6-86e3-bf04f3bf0fa0.png)
SVG: [apple-shift-key.svg](https://www.dropbox.com/s/rw36dj2eyd6h5i8/apple-shift-key.svg?dl=0)

### Caps
![apple-caps-key](https://cloud.githubusercontent.com/assets/8648114/14766030/159b2c66-09c1-11e6-9a6c-f06f017745d2.png)
![apple-caps-key 2x](https://cloud.githubusercontent.com/assets/8648114/14766031/15adb958-09c1-11e6-9e90-b7b9da0ace84.png)
![apple-caps-key 3x](https://cloud.githubusercontent.com/assets/8648114/14766032/15adc7a4-09c1-11e6-92c9-a6c0b06f730b.png)
SVG: [apple-caps-key.svg](https://www.dropbox.com/s/2tstxtx7rr2rekj/apple-caps-key.svg?dl=0)

**Comment by CoDEmanX** [comment]
Two overlapping contributions (Apple command / option):
https://github.com/Templarian/MaterialDesign/issues/877#issuecomment-168178305
https://github.com/Templarian/MaterialDesign/issues/877#issuecomment-173553748

**Comment by Templarian** [comment]
[![apple-keyboard-command](https://materialdesignicons.com/icon/apple-keyboard-command)](https://materialdesignicons.com/icon/apple-keyboard-command) [![apple-keyboard-option](https://materialdesignicons.com/icon/apple-keyboard-option)](https://materialdesignicons.com/icon/apple-keyboard-option) [![apple-keyboard-control](https://materialdesignicons.com/icon/apple-keyboard-control)](https://materialdesignicons.com/icon/apple-keyboard-control) [![apple-keyboard-shift](https://materialdesignicons.com/icon/apple-keyboard-shift)](https://materialdesignicons.com/icon/apple-keyboard-shift) [![apple-keyboard-caps](https://materialdesignicons.com/icon/apple-keyboard-caps)](https://materialdesignicons.com/icon/apple-keyboard-caps)

**Comment by nmsmith22389** [comment]
Just a heads up... It look's like the bottom of the caps icon got chopped off when you put them up.

**Comment by CoDEmanX** [comment]
Yup, looks broken. I also noticed by looking at my own keyboard, that the two arrows should be of **equal height**:

![img_20160424_231226](https://cloud.githubusercontent.com/assets/1309249/14770502/80a57eb4-0a73-11e6-8456-4fb4700d0a3f.png)

I wonder where you found that Control key, I've never seen an Apple keyboard with such a key.

**Comment by Templarian** [comment]
Just got back, way too nice in Chicago today. 2 hour walk/run around the lake and zoo. :sunny: :sunglasses: 

Fixed (github images above cache for a bit will update eventually).

**Comment by nmsmith22389** [comment]
They don't ever put the control key icon on the keyboards but it is used when referring to the control key (i.e. a hotkey or shortcut)

I can also fix the shift key and reduce it in size if that helps, just let me know.

**Comment by CoDEmanX** [comment]
Templarian fixed it, see above icon previews. LGTM, do you have any objections?
