### ISSUE TITLE
IO Serial Port USB icons

### ISSUE THREAD

**Issue by amoamare** [Templarian/MaterialDesign#1195]
Looking to see some basic IO operation icons, serial port, USB, keyboard etc

**Comment by CoDEmanX** [comment]
Keyboards:

[![keyboard-variant](https://materialdesignicons.com/icon/keyboard-variant)](https://materialdesignicons.com/icon/keyboard-variant) [![keyboard](https://materialdesignicons.com/icon/keyboard)](https://materialdesignicons.com/icon/keyboard)

USB:
[![usb](https://materialdesignicons.com/icon/usb)](https://materialdesignicons.com/icon/usb)

Open request: Flash storage icons (pen drive / USB stick, classic SSD and perhaps M.2 card) - #1078 

Not sure how to depict a serial port in MD style... ![serial-port](https://cloud.githubusercontent.com/assets/1309249/14833682/cad0a9c6-0c00-11e6-97ad-5e848bcf1a33.png) ?

Ethernet cable maybe?
[![ethernet-cable](https://materialdesignicons.com/icon/ethernet-cable)](https://materialdesignicons.com/icon/ethernet-cable)

**Comment by Templarian** [comment]
[![serial-port](https://materialdesignicons.com/icon/serial-port)](https://materialdesignicons.com/icon/serial-port)

**Comment by CoDEmanX** [comment]
You actually added my horrible serial port icon xD

This is how my screen depicts it BTW:

![img_20160427_004829](https://cloud.githubusercontent.com/assets/1309249/14891331/8ecdaf52-0d66-11e6-96d4-5e79a6a347fc.jpg)

**Comment by Templarian** [comment]
@CoDEmanX I instantly knew that was a serial cable though... I think people still using them (which is rare) would recognize it.

**Comment by amoamare** [comment]
@Templarian , @CoDEmanX  your right it is very recognizable thanks for the addition.
