### ISSUE TITLE
Strike-trough icons with separate path

### ISSUE THREAD

**Issue by PhilLab** [Templarian/MaterialDesign#1197]
Is it possible to (auto-) convert all strike-trough icons like for example the following:

![microphone-off](https://cloud.githubusercontent.com/assets/1710255/14854800/68123084-0c91-11e6-8501-ca64225ebefa.png)

such that the strike-trough is a separate path to allow for quick modifications, e.g. like

![microphone-off](https://cloud.githubusercontent.com/assets/1710255/14854765/43f672fa-0c91-11e6-97bb-4e2ae46bf049.png)

**Comment by Templarian** [comment]
It was decided a while back that to make icons visually consistent the best approach was to create each `-off` icon by hand. So while we use a standard template we do modify the length of the slash and the pixel position slightly from icon to icon for visual consistency.

You could definitely overlay a slash and a line matching your background color to give a similar look though. If I had to guess I would say only 30% of the `-off` icons use the unmodified template slash with no size/position changes.
