### ISSUE TITLE
Chrome Dinosaur

### ISSUE THREAD

**Issue by GRRedWings** [Templarian/MaterialDesign#1198]
I would like to see something like the chrome dinosaur to show offline or not available.

https://medium.com/@rowena/connecting-to-a-user-with-no-connection-dea378f05b34#.hbx04m6fg

**Comment by Templarian** [comment]
Weird enough this is a duplicate #913. :laughing:

**Comment by GRRedWings** [comment]
Sounds like it's gaining steam then!
