### ISSUE TITLE
Humans

### ISSUE THREAD

**Issue by outre99** [Templarian/MaterialDesign#1199]
Man, Woman, Child, Children, Infant,  Old people

**Comment by Templarian** [comment]
A few of these exist and the others are already tracked in issues (with icons created just not inserted).

https://materialdesignicons.com/icon/human-child (note this is getting replaced with a different icon)
https://materialdesignicons.com/icon/baby
https://materialdesignicons.com/icon/human-male-female

Issue #420 / #505 should cover these and icons are will be inserted shortly.

Thanks!

**Comment by Templarian** [comment]
Just added the `human-male` and `human-female` icons by the way.

**Comment by outre99** [comment]
The child one looks like a box.
The baby is in very strange position
And the humans are together while there's a clear need to have a
separate one for a man and a woman.
There's needs to be a set of icons depicting people that is visually
consistent.

**Comment by CoDEmanX** [comment]
- Fat child: https://github.com/Templarian/MaterialDesign/issues/14#issuecomment-214053930
- Baby: well, how else would you depict it? This is not going to work in the same style as the toilet door icons.
- Templarian had separate icons for male and female added shortly before you replied
- Consistency: of course it would be great to have everything from granny to gay couple with pets and adopted children as a consistent icon set. But we are very limited by the MD icon guidelines, and someone has to do the actual work (for free).

**Comment by outre99** [comment]
On 04/28/2016 10:07 PM, CoDEmanX wrote:
>
>   * Fat child: #14 (comment)
>     <https://github.com/Templarian/MaterialDesign/issues/14#issuecomment-214053930>
>
>   * Baby: well, how else would you depict it? This is not going to
>     work in the same style as the toilet door icons.
>   * Templarian had separate icons for male and female added shortly
>     before you replied
>   * Consistency: of course it would be great to have everything from
>     granny to gay couple with pets and adopted children as a
>     consistent icon set. But we are very limited by the MD icon
>     guidelines, and someone has to do the actual work (for free).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/1199#issuecomment-215456527>
>

thanks,
- Fat child...  nothing to add to other comments
- an infant is usually wrapped with only a head showing.  this baby icon
looks like a grown man with a diaper.  not the audience we're trying to
attract.
- will take a look at the new icons, smaller size of which can work for
children.
-  i didn't mention anything about unusual family combination units,
just humans of different ages.

**Comment by Templarian** [comment]
The baby icon included is a standard infant icon from Google. So that one will stay for the baby.
We're not keeping the fat child icon. :laughing: That one will be replaced.
I think the 3 parent combination icons will be included also. `human-male-male-child` etc...
