### ISSUE TITLE
Payment method

### ISSUE THREAD

**Issue by user174** [Templarian/MaterialDesign#120]
Icons for payment methods such as PayPal, WebMoney, Yandex.Money.

**Comment by Templarian** [comment]
PayPal's logo doesn't work in a webfont, actually 95% of payment logos will not work at 24x24.

![image](https://cloud.githubusercontent.com/assets/338885/5913671/a28260fa-a5ad-11e4-9f7b-f4a418e065f4.png)

I'm kind of making a rule to not add any payment icons. Issue #69 is similar.

**Comment by user174** [comment]
Thanks
