### ISSUE TITLE
Icon for "similar items" as same as google play store

### ISSUE THREAD

**Issue by vishaliiita** [Templarian/MaterialDesign#1201]
See attached screenshot.
![screenshot_20160428-130305](https://cloud.githubusercontent.com/assets/3014949/14878557/ecd50494-0d41-11e6-9f12-06ae14ac48e7.png)

**Comment by CoDEmanX** [comment]
I tried to recreate it and uploaded it in the 2nd batch, #420. It doesn't look that good however, the Google playstore icons are not very MD compliant in general.

You may use the recently added cards icon, it has quite a similar shape and meaning to it.

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #982.
