### ISSUE TITLE
marker missing from webfont

### ISSUE THREAD

**Issue by chancezeus** [Templarian/MaterialDesign#1204]
On the website there is a marker icon available (https://materialdesignicons.com/icon/marker), but when I try to locate it in the webfont it does not seem to exist...

**Comment by Templarian** [comment]
https://materialdesignicons.com/history Looks like it was added on April 24th after the `1.5.54` release. I probably won't be doing another release for a few weeks unfortunately so you may have to use an inline vector until then.
