### ISSUE TITLE
Garden icons

### ISSUE THREAD

**Issue by EsmeW** [Templarian/MaterialDesign#1205]
Garden icons. Trees, flowers, fruits, vegetables ...

**Comment by CoDEmanX** [comment]
We already have the following (in case you missed some):

- flower
- nature (generic leaf tree)
- tree
- pine-tree
- image-filter-vintage
- fruit-apple
- barley
- hops
- carrot
- leaf
- tor (onion)

**Comment by insippo** [comment]
I need these too

**Comment by CoDEmanX** [comment]
@insippo What do you need exactly?

**Comment by PeterShaggyNoble** [comment]
@insippo, if you are in need of any icons not covered in @CoDEmanX's comment or by one of the many icons that have been added in the intervening 3 years then please create a new issue for each one.
