### ISSUE TITLE
Poison Icon

### ISSUE THREAD

**Issue by IamThePeter** [Templarian/MaterialDesign#1207]
I find it odd that there is no poison (or pirate) icon. May i suggest something like this:

http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/simple-black-square-icons-signs/127573-simple-black-square-icon-signs-warning-poison1.png

**Comment by Templarian** [comment]
I find it very odd also. I'm going to group this with the medical icons. We need to work on getting more medical related icons in.

Duplicate of #147
