### ISSUE TITLE
Missing icons from webfont and css

### ISSUE THREAD

**Issue by icalper** [Templarian/MaterialDesign#1208]
I noticed [account-settings](https://materialdesignicons.com/icon/account-settings) and [account-settings-variant](https://materialdesignicons.com/icon/account-settings-variant) are missing from both the webfont and the css. Im using the latest version (1.5.54)

**Comment by Templarian** [comment]
Please check the history page for the icons that are not currently synced into a release.

https://materialdesignicons.com/history

Next release will be in a few weeks.
