### ISSUE TITLE
Additional chart-* variations

### ISSUE THREAD

**Issue by kaifaust** [Templarian/MaterialDesign#1209]
@Templarian 
<img width="847" alt="preview" src="https://cloud.githubusercontent.com/assets/3498300/14999731/f6857ec2-113f-11e6-9e2c-378753382029.png">

[flow-cytometry-material-icons.zip](https://github.com/Templarian/MaterialDesign/files/247841/flow-cytometry-material-icons.zip)

**Comment by CoDEmanX** [comment]
Love that test tube!

**Comment by Templarian** [comment]
Just a heads up these are all being added shortly.

If you want to become a contributor please fill out the form (and post a square avatar picture or just let me know in a comment below if you want to use your github avatar): https://materialdesignicons.com/contribute

**Comment by kaifaust** [comment]
@Templarian I filled out the form a few weeks back, feel free to use my github profile pic!

**Comment by kaifaust** [comment]
Here's a few plot icons:

<img width="308" alt="plot icons" src="https://cloud.githubusercontent.com/assets/3498300/15103673/f3116162-1562-11e6-945f-c7f78e591288.png">



[plot-icons.zip](https://github.com/Templarian/MaterialDesign/files/254299/plot-icons.zip)

**Comment by Templarian** [comment]
Awesome!

[Insert excuse about work here, and state they will be added soon :sweat_smile:]

**Comment by Templarian** [comment]
https://materialdesignicons.com/contributor/Kai-Faust I added the 6 from your first post @kaifaust.

Will get the others added shortly. I don't think that contour plot will work. might need a different design for that type of chart. The scatter plot looks nice. Makes me think we need a scatter hex also.

**Comment by goyney** [comment]
The only icons left in this issue are chart additions, so I am renaming it appropriately.

**Comment by goyney** [comment]
Looks like we have everything here added.
