### ISSUE TITLE
Dartboard icon

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#1211]
Like this
https://cdn2.iconfinder.com/data/icons/productivity/256/Goals-512.png

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/bullseye Could the `bullseye` icon work for this?

**Comment by CoDEmanX** [comment]
Perhaps bullseye + some kind of arrow?

**Comment by matthew2402** [comment]
Ja bullseye with some kind of arrow would be great. Just the bullseye is not that what I want ;)

**Comment by PeterShaggyNoble** [comment]
Does #3049 fulfil this request?

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. If `bullseye-arrow` doesn't suit your needs, let us know and we'll revisit this issue.
