### ISSUE TITLE
Aerosol instruments (or general science and metrology)

### ISSUE THREAD

**Issue by jacobq** [Templarian/MaterialDesign#1213]
Does anyone have a recommendation for an icon to represent a **generic scientific instrument / measurement device**? (A microscope seems to be the closest thing, so I am watching https://github.com/Templarian/MaterialDesign/issues/1016 too) Or, even better but probably unlikely to exist already, any aerosol instruments, such as [CPC](https://en.wikipedia.org/wiki/Condensation_particle_counter), [DMA](https://en.wikipedia.org/wiki/Differential_mobility_analyzer), [SMPS](https://en.wikipedia.org/wiki/Scanning_mobility_particle_sizer), [particle mass analyzer](https://en.wikipedia.org/wiki/Particle_mass_analyser), etc?

I am writing software to interface with a variety of niche colloid/aerosol measurement devices that are basically sensors. Unfortunately, my design skills are on the novice side and most products just look like boxes with screens, which makes them easily confused with computers, tablets, etc. so I could use any and all advice from the design community. These devices are measuring properties of small particles (things in the air like dust, soot, etc. as well as water impurities like colloidal silica -- not subatomic particles like electrons), so maybe I could just draw some differently sized dots (e.g. similar to [the dust icon used with iMotion G6](http://www.diopso.com/sites/default/files/Cie/infinitus/Icons/Icon_-_Dust_proof.png)) flowing and mix in some kind of emblem indicating that they are being measured?  Are there some "standard" / well-recognized symbols for this? I have seen rulers, dial gauges, and even thermometers used for things like this but am concerned about creating something that just adds confusion. For now, I am planning to just use [Chris Litherland's desktop-tower icon](https://materialdesignicons.com/contributor/Chris-Litherland) since a desktop computer is actually a reasonable approximation to a complex "black box" generic device and there's no other icon or action relating to a computer in my application.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/microscope There is a microscope (just added) and scale icons.

I didn't read the second paragraph, but if you have example images that may help.

**Comment by jacobq** [comment]
I'm not sure if I've made these close enough to the Material Design guidelines, but here's what I came up with. From left to right: polydisperse aerosol (i.e. particles of various sizes), particle nebulization (i.e. spraying), particle [differential mobility analyzer](https://en.wikipedia.org/wiki/Differential_mobility_analyzer) (basically a tube with an electrode in the center), a [particle detector](https://en.wikipedia.org/wiki/Condensation_particle_counter) (dotted line is supposed to be representing a laser beam that gets interrupted by passing particles), and a [particle sizer](https://en.wikipedia.org/wiki/Particle_size) (these systems would be very complex to draw schematically so I've just attempted to express the idea of a size distribution by showing a gaussian function with increasingly larger dots below it.) 

![particle-icons](https://cloud.githubusercontent.com/assets/1633459/15263659/a496c018-1931-11e6-9054-c1b1ad51c5ea.png)
[particle-icons.zip](https://github.com/Templarian/MaterialDesign/files/264184/particle-icons.zip)

**Comment by jacobq** [comment]
@Templarian are you willing to accept these as contributions? If not, is there something wrong with them that I should seek to address?

**Comment by Templarian** [comment]
@jacobq On vacation will be spending time on the backlog shortly and will let you know.

But looking at them really quick they may be too detailed. Export them at the 1:1 24x24 when showing them inline in github issues. Makes it easier for me and the other contributors to do a visual check. Thanks.

**Comment by jacobq** [comment]
Thanks for the reply (I hope you didn't feel obligated to interrupt your vacation). I will try to reduce the level of detail in these and also export them at 24x24.

**Comment by PeterShaggyNoble** [comment]
Closing this out as these are going to be too niche to add.

**Comment by jacobq** [comment]
Fair enough
