### ISSUE TITLE
Tip for icon creation

### ISSUE THREAD

**Issue by DianaDias** [Templarian/MaterialDesign#1214]
Poderia ter algum ícone que indicasse um QRcode.
Ex. gostaria de ter um botão que tivesse uma **img** de qrcode para indicar que quando fosse clicado, abriria o leitor de qrcode.

> Could have any icon to indicate one QRcode .
> Ex . I would like to have a button that had an img of qrcode to indicate when it was clicked, would open the qrcode player.

**Comment by Templarian** [comment]
@DianaDias This icon exists: https://materialdesignicons.com/icon/qrcode

**Comment by DianaDias** [comment]
Obrigada, estava pesquisando neste local https://design.google.com/icons/ por isso não encontrei.

**Comment by Templarian** [comment]
@DianaDias Yea, the community icon pack here extends the icons provided by Google to help out.

https://github.com/google/material-design-icons/issues/7 Please upvote this issue for them to add an official icon.

**Comment by DianaDias** [comment]
Feito. Obrigada.
