### ISSUE TITLE
designer programs

### ISSUE THREAD

**Issue by vbaimas** [Templarian/MaterialDesign#1215]
It would be nice to include the official icons of design programs like : 
- Photoshop
- Illustrator
- InDesign
- Sketch

**Comment by CoDEmanX** [comment]
The Adobe icons are essentially two letters in a rectangle, not very recognizable and @Templarian  doesn't want text-only icons in MDI. The Sketch logo is a diamond with perspective, but perspective is discouraged in Material Design. We do have a "flat" diamond though.

**Comment by Templarian** [comment]
Yea, I've considered adding the `adobe-*` icons in the past. Even though they are just text, they are very useful in sites where showing different software. I'm going to say these would be fine to add if we can find a style that works nicely.

**Comment by vbaimas** [comment]
@CoDEmanX and @Templarian Thanks for the response. General i agree. In some cases theses icons are useful, as an example : A designer who want to describe the technologies that he know (in his personal website) with these icons. In material design is very "sensitive" to describe these technologies with icons, and in this point i wonder how will be this design.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
