### ISSUE TITLE
stop circle filled + stop circle outline

### ISSUE THREAD

**Issue by shawmanz32na** [Templarian/MaterialDesign#1218]
There are already icons for `play circle filled`, `play circle outline`, `pause circle filled`, and `pause circle outline`.

![circled play and pause actions](https://cloud.githubusercontent.com/assets/5596570/15226705/b4ef26e8-1838-11e6-8e6e-15d146ccf41b.PNG)

I'd love to see the equivalent icons for the "stop" action.

**Comment by CoDEmanX** [comment]
We should probably add more icons in that case, at least skip-next and skip-previous.

**Comment by CoDEmanX** [comment]
![skip-next-circle](https://cloud.githubusercontent.com/assets/1309249/15232752/9b153fb2-18a3-11e6-9028-25d1effda4f8.png) ![skip-next-circle-outline](https://cloud.githubusercontent.com/assets/1309249/15232747/9b11c0c6-18a3-11e6-947e-82f24c761a29.png)
![skip-previous-circle](https://cloud.githubusercontent.com/assets/1309249/15232748/9b121e7c-18a3-11e6-87d7-effca8955184.png) ![skip-previous-circle-outline](https://cloud.githubusercontent.com/assets/1309249/15232750/9b129050-18a3-11e6-8b8f-0110c0646952.png)
![stop-circle](https://cloud.githubusercontent.com/assets/1309249/15232751/9b145fb6-18a3-11e6-9b51-37e66dcf6da9.png) ![stop-circle-outline](https://cloud.githubusercontent.com/assets/1309249/15232749/9b124ffa-18a3-11e6-85f4-3f7d7de3884e.png)

https://www.dropbox.com/s/6j0c8wkqdmdv6qg/2016-05-13_Conversion.zip?dl=0

**Comment by shawmanz32na** [comment]
+1000 for the ultra-quick turnaround. Cheers!

**Comment by Templarian** [comment]
[![skip-next-circle](https://materialdesignicons.com/icon/skip-next-circle)](https://materialdesignicons.com/icon/skip-next-circle) [![skip-next-circle-outline](https://materialdesignicons.com/icon/skip-next-circle-outline)](https://materialdesignicons.com/icon/skip-next-circle-outline) [![skip-previous-circle](https://materialdesignicons.com/icon/skip-previous-circle)](https://materialdesignicons.com/icon/skip-previous-circle) [![skip-previous-circle-outline](https://materialdesignicons.com/icon/skip-previous-circle-outline)](https://materialdesignicons.com/icon/skip-previous-circle-outline)  [![stop-circle](https://materialdesignicons.com/icon/stop-circle)](https://materialdesignicons.com/icon/stop-circle) [![stop-circle-outline](https://materialdesignicons.com/icon/stop-circle-outline)](https://materialdesignicons.com/icon/stop-circle-outline)
