### ISSUE TITLE
Umbrella closed

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#1219]
I included an icon for this in [one of the icon packs](https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-215589687), and there's one in the Nova icons.

I just realized that it might be better to not have it upside down, but match the open umbrella icon, so that it works as toggle (AV on/off).

**Comment by JamesCoyle** [comment]
I think consistency is always better. Not really sure what I'd use it for but I'm sure someone would find a use.

**Comment by CoDEmanX** [comment]
umbrella on / off (animated): ![umbrella](https://cloud.githubusercontent.com/assets/1309249/15457050/6842cc44-2082-11e6-899a-ed08692ee809.gif)

On its own, it is easier recognizable the other way around though:

![umbrella-disabled](https://cloud.githubusercontent.com/assets/1309249/15457052/78ff080e-2082-11e6-8ff9-29f9c6183740.png) ![umbrella-disabled2](https://cloud.githubusercontent.com/assets/1309249/15457055/7ed11574-2082-11e6-90bf-d0ccbeaf15e1.png)

**Comment by JamesCoyle** [comment]
Do you still have the SVG?

**Comment by PeterShaggyNoble** [comment]
@JamesCoyle: https://www.dropbox.com/s/wf4jjxu07pammz7/2016-04-29_Conversion.zip?dl=0, from #505

**Comment by CoDEmanX** [comment]
It already has the modified handle (#2916):

[umbrella-disabled.zip](https://github.com/Templarian/MaterialDesign/files/1813427/umbrella-disabled.zip)

**Comment by CoDEmanX** [comment]
That was actually the up-side down version. Here's the other one:

[umbrella-disabled-up-optimized.zip](https://github.com/Templarian/MaterialDesign/files/1815389/umbrella-disabled-up-optimized.zip)

(did some manual rounding in the source file)

**Comment by Templarian** [comment]
[![umbrella-closed](https://materialdesignicons.com/icon/umbrella-closed)](https://materialdesignicons.com/icon/umbrella-closed)
