### ISSUE TITLE
Close/hide panel icon

### ISSUE THREAD

**Issue by ericpoulinnz** [Templarian/MaterialDesign#122]
Hi again,

I have a panel that comes up in the same way on on-screen keyboard does but instead of a keyboard it is a drawing area. It would be amazing if we had an icon like this one: http://materialdesignicons.com/icon/keyboard-close

The only change is instead of showing keyboard keys, have that area as one white box (the drawing pad).

Not sure if that's enough detail.

Thanks in advanced :)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/transcribe
http://materialdesignicons.com/icon/transcribe-close
http://materialdesignicons.com/icon/image-area
http://materialdesignicons.com/icon/image-area-close

Like these?

**Comment by ericpoulinnz** [comment]
I love them! Have used transcribe close for my current task. Thanks so much again
