### ISSUE TITLE
idea for icons

### ISSUE THREAD

**Issue by geogy** [Templarian/MaterialDesign#1220]
Hi! i think that you need an icon of shopping car and shopping car with things inside, something like products in the shopping car.

thanks for pay attention of my suggestion.

**Comment by Templarian** [comment]
@geogy Do you mean shopping _cart_? If so it exists... `cart`.

**Comment by ricardotda** [comment]
I suggest a medal / achievement icon.

**Comment by geogy** [comment]
oh yes, sorry about that; but i don't see the shopping cart with products inside, it's mean that if i select a product this basket is full. I think that it is not found on web site of icons.

**Comment by JamesCoyle** [comment]
Wouldn't using cart and cart outline work?

**Comment by geogy** [comment]
mmmm yes, i was not thinking about it, but it works to me, thanks for the answers!!! sorry if i made lose your time with these things. :+1:
