### ISSUE TITLE
Unity

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1221]
Unity Logo.

![image](https://cloud.githubusercontent.com/assets/338885/15278024/1b592608-1ad8-11e6-8133-7ad999e1b79d.png)

**Comment by TheManuz** [comment]
Made it!
![unity_24px](https://cloud.githubusercontent.com/assets/2032334/15359790/450abad6-1d0b-11e6-8c09-141b96fce2a3.png)
[Unity_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/270536/Unity_24px.svg.zip)

**Comment by Templarian** [comment]
[![unity](https://materialdesignicons.com/icon/unity)](https://materialdesignicons.com/icon/unity)
