### ISSUE TITLE
Super-user folder icon

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#1222]
Can you make a folder icon with a superuser icon in it?
For root folder.
Thanks in advance.

**Comment by CoDEmanX** [comment]
How would that superuser look like? Simply a crown subtracted from the folder base shape?

Or a folder with a star? (could also mean favorite folder)

**Comment by AravK** [comment]
Could it be a folder with a "#" inside? Something like what's in the CandyCons Android app

**Comment by JamesCoyle** [comment]
Folder with a hash makes the most sense and I like the idea of the favorites star too.

**Comment by goyney** [comment]
Had to go with a 1dp # on these, but luckily it is still identifiable at native resolution.

![image](https://user-images.githubusercontent.com/1015040/48817583-283d4400-ed15-11e8-9a0b-52a084c17fc9.png)![image](https://user-images.githubusercontent.com/1015040/48817588-2f645200-ed15-11e8-9e83-a8cf62fa226a.png)

[folder-super-user.zip](https://github.com/Templarian/MaterialDesign/files/2602550/folder-super-user.zip)

**Comment by Templarian** [comment]
[![folder-pound](https://materialdesignicons.com/icon/folder-pound)](https://materialdesignicons.com/icon/folder-pound) [![folder-pound-outline](https://materialdesignicons.com/icon/folder-pound-outline)](https://materialdesignicons.com/icon/folder-pound-outline)
