### ISSUE TITLE
Gap between icon `0xf1ca` and `0xf1c8`

### ISSUE THREAD

**Issue by code-mc** [Templarian/MaterialDesign#1223]
I'm aware of the changes to the way the font file is set up (icons not in order etc) but sadly there is a gap of 1 icon in between hex codes `0xf1ca` and `0xf1c8`. Is this intentional?

**Comment by Templarian** [comment]
The icon was probably deleted. I can replace it with a future icon and will now that I know there is a gap.

Not really a bug, but yea we should put an icon there to fill in the blank.

**Comment by code-mc** [comment]
I've been experimenting a bit and the gap so far only appears in the svg font.

**Comment by franciscofranco** [comment]
@Templarian is there any news on this bug? It's quite nasty.

**Comment by franciscofranco** [comment]
Bump...

**Comment by Templarian** [comment]
Sorry guys, this has been fixed in the background for the next release. The `creation` icon will fill that space. Hopefully I get get a few more bugs closed out quickly and release a version.

**Comment by Templarian** [comment]
Will be doing a release for 1.7.12 tomorrow to NPM/Bower. Attached is the zip and the CDN has the version.

https://cdn.materialdesignicons.com/1.7.12/
https://cdn.materialdesignicons.com/1.7.12/meta.json

[MaterialDesignIcons.zip](https://github.com/Templarian/MaterialDesign/files/424216/MaterialDesignIcons.zip)
