### ISSUE TITLE
email-plus

### ISSUE THREAD

**Issue by Tallyb** [Templarian/MaterialDesign#1225]
a mail envelope with a plus sign.

**Comment by mrsdohpaz** [comment]
Trying my hand at this one.
[email-outline-plus.svg.zip](https://github.com/Templarian/MaterialDesign/files/299636/email-outline-plus.svg.zip)


![email-outline-plus](https://cloud.githubusercontent.com/assets/7914791/15810398/0972d8ea-2b6c-11e6-9b67-b3d0dcab6d3e.png)

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33999213-bd8c62ac-e0e1-11e7-9253-213e45776b70.png)](https://github.com/Templarian/MaterialDesign/files/1559723/email-plus.zip)[![](https://user-images.githubusercontent.com/15905797/33999237-d20b77a4-e0e1-11e7-88a2-b4486c3f8d5a.png)](https://github.com/Templarian/MaterialDesign/files/1559724/email-plus-outline.zip)

**Comment by Templarian** [comment]
[![email-plus](https://materialdesignicons.com/icon/email-plus)](https://materialdesignicons.com/icon/email-plus) [![email-plus-outline](https://materialdesignicons.com/icon/email-plus-outline)](https://materialdesignicons.com/icon/email-plus-outline)
