### ISSUE TITLE
Icon suggestion - Company

### ISSUE THREAD

**Issue by jimbojones007** [Templarian/MaterialDesign#1226]
An icon to symbolize a company. Most likely a building but open for other possibilities as well. In my case I want people to register and create a profile of their company. Next follows a job profile. Thus just a plain list or something like it would not work. Also a factory building is not the desired solution.

**Comment by CoDEmanX** [comment]
We have the following two icons:

[![factory](https://materialdesignicons.com/icon/factory)](https://materialdesignicons.com/icon/factory) [![domain](https://materialdesignicons.com/icon/domain)](https://materialdesignicons.com/icon/domain)

@Templarian: how about adding `building` and `company` as tags to `domain`?

**Comment by jimbojones007** [comment]
Thanks for the feedback. Domain works for me. As a non native speaker, I
would have never found it though. The suggested tags would be good.

**Comment by Templarian** [comment]
- [ ] `building` ... domain
- [ ] `company` ... domain
- [ ] `industrial` ... factory
