### ISSUE TITLE
Icon suggestion - Workflow

### ISSUE THREAD

**Issue by jimbojones007** [Templarian/MaterialDesign#1227]
A simple icon to symbolize a work flow (in our case more communication flow)

**Comment by CoDEmanX** [comment]
In general, these might be suitable to represent "workflows":

https://materialdesignicons.com/icon/chart-timeline
https://materialdesignicons.com/icon/chart-gantt

For communication however, I'm not sure how to depict that.

Something more like this?
https://materialdesignicons.com/icon/sitemap

This is actually intended to be an icon for a debugger run, but works for you too:
![debugger2](https://cloud.githubusercontent.com/assets/1309249/15333129/b8e9a94c-1c68-11e6-8a41-1755f0204884.png)

**Comment by jimbojones007** [comment]
I was thinking either more like this:

https://www.iconfinder.com/icons/526869/planning_project_plan_sheme_workflow_icon#size=128

or see the attached that I just quickly patched together in PowerPoint.
(This is where the message with attachment icon would come into work as
well).

In our case we are offering a service in which you have a workflow that is
mainly supporting the communication between an HR Person, internal third
parties (hiring department) and the applicant but could include the
attachment of a CV or letter of reference. That's the message I want to
bring across in an ideal scenario.

It's just a suggestion though and off course I understand this is an open
source project and not an on demand design agency ;-)

Greetings from Berlin (Germany),

Daniel

**Comment by CoDEmanX** [comment]
Some experiments:

![workflow](https://cloud.githubusercontent.com/assets/1309249/15396601/1cb58c0a-1ddd-11e6-8ead-07747efca78d.png)
![workflow2](https://cloud.githubusercontent.com/assets/1309249/15396599/1cb13e34-1ddd-11e6-84fe-427ecd704f56.png)
![workflow3](https://cloud.githubusercontent.com/assets/1309249/15396600/1cb16cb0-1ddd-11e6-8a2e-e7e078c75965.png)

Greetings from Potsdam, Germany!

**Comment by jimbojones007** [comment]
I like the second version best. It's more or less symmetric or equaly
weighted.

So Klein ist die Welt.

Cheers, Daniel

**Comment by CoDEmanX** [comment]
`file-tree` might actually work as well for certain kinds of processes and communication flows.

**Comment by Templarian** [comment]
So you guys think `workflow` for this icon? Using the [2nd](https://github.com/Templarian/MaterialDesign/issues/1227#issuecomment-220337847) one. Given the size constraints it does a nice job of conveying a workflow.

**Comment by JamesCoyle** [comment]
The second one looks good to me. I also like the third one as an alternate as it represents more of a waterfall model. First one is too cramped really.

**Comment by CoDEmanX** [comment]
![workflow2](https://cloud.githubusercontent.com/assets/1309249/15457167/9e550a48-2084-11e6-9d42-a41a53cedc05.png)
![workflow2b](https://cloud.githubusercontent.com/assets/1309249/15457166/9e550836-2084-11e6-922e-881e3baf53be.png) with a bit more spacing at the arrow tail
![workflow3](https://cloud.githubusercontent.com/assets/1309249/15457173/c6fceaf6-2084-11e6-927d-3610aaa359ec.png)

https://www.dropbox.com/s/iaiigc1gtkj8lz6/2016-05-23_Conversion.zip?dl=0

**Comment by CoDEmanX** [comment]
Does the flowchart icon really represent the same thing?
