### ISSUE TITLE
Icon suggestion - Message with attachment

### ISSUE THREAD

**Issue by jimbojones007** [Templarian/MaterialDesign#1228]
Similar to the Message-draw or Message-image icon, I would love to see a message-attachment (paper clip) icon.

**Comment by CoDEmanX** [comment]
There are two paperclip icons already:

[![attachment](https://materialdesignicons.com/icon/attachment)](https://materialdesignicons.com/icon/attachment) [![paperclip](https://materialdesignicons.com/icon/paperclip)](https://materialdesignicons.com/icon/paperclip)

**Comment by jimbojones007** [comment]
I was more thinking like this:

https://materialdesignicons.com/icon/message-draw

Just with the paper clip inside.

**Comment by CoDEmanX** [comment]
The full size paperclip has a stroke width of less than 2 pixels already, I don't think it will fit inside the message base shape.
