### ISSUE TITLE
Icon request: abstract COM port (e.g. combination USB / serial)

### ISSUE THREAD

**Issue by jacobq** [Templarian/MaterialDesign#1229]
I would appreciate it if there were an icon that represented an arbitrary COM port (for example, could physically be over USB, a TTL UART, RS-232 connection, or Bluetooth). I like the serial-port icon and USB icon but am concerned that if I use just one or the other my users could get confused because they may be likely to think more concretely about their connection (because other, older software made a big deal out of these differences for some reason).

One way to go about this could just be taking some existing icons and combining them like this:
![usb-serial](https://cloud.githubusercontent.com/assets/1633459/15370960/dfbcf95c-1cfe-11e6-90cf-6a7b82657cc1.png)

Another might be to draw a [digital waveform resembling a serial frame](https://images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.ee.nthu.edu.tw%2Fjcliao%2Fmic97%2Fchap12R%2FF12_18.JPG&f=1) like this: 
![digital-serial-waveform](https://cloud.githubusercontent.com/assets/1633459/15373940/8ab8c7a6-1d0d-11e6-8757-8f937aab454e.png)
[digital-serial-waveform.zip](https://github.com/Templarian/MaterialDesign/files/271356/digital-serial-waveform.zip)

**Comment by Templarian** [comment]
This might be too specific for this icon pack. I rarely close icons for this reason, so I'll leave it up to discussion.

/cc @CoDEmanX

**Comment by jacobq** [comment]
I suppose it's not fair to try to slip all of the icons I want in my application into this project if they're not so useful to others.... Could you point me to some information about how I can make a custom build? (e.g. fork, add application-specific icons like https://github.com/Templarian/MaterialDesign/issues/1213#issuecomment-219177465 and generate the font) I have never used image, icon, or font automation tools before.
