### ISSUE TITLE
Icon Request : Mac OS X icon

### ISSUE THREAD

**Issue by SuicSoft** [Templarian/MaterialDesign#1231]

**Comment by CoDEmanX** [comment]
Hm, what icon do you actually mean? We have the apple-finder icon, which looks like the old OSX icon:

https://materialdesignicons.com/icon/apple-finder

**Comment by Templarian** [comment]
Yea, I think this would be finder. Not going to be adding the circle with the x inside. It's just too synonymous with close.

**Comment by SuicSoft** [comment]
@Templarian The close does not look like Mac OS X .In OS X the X is taller

**Comment by Templarian** [comment]
:grimacing:
