### ISSUE TITLE
file-eye

### ISSUE THREAD

**Issue by itsmeYudist** [Templarian/MaterialDesign#1232]
Can I request "mdi-view-file" icon, it's combine of file icon and eye icon.

regards,

Yudistira

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48817827-4b1c2800-ed16-11e8-8943-b5be56fc0292.png)![image](https://user-images.githubusercontent.com/1015040/48817834-52433600-ed16-11e8-9b7e-e6ab9048606e.png)

[file-view.zip](https://github.com/Templarian/MaterialDesign/files/2602569/file-view.zip)

**Comment by itsmeYudist** [comment]
@goyney , Thanks a lot 👍 👍 👍 👍

**Comment by Templarian** [comment]
Added both of these. 😃
