### ISSUE TITLE
Aliases for Google Photos icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#1233]
- [x] account-box --> selfie
- cellphone --> screenshot (skipped)
- [x] movie -> clapperboard
- [x] movie --> slate
- [x] [assistant](https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-179558442) --> creation (added https://materialdesignicons.com/icon/creation)

![image](https://cloud.githubusercontent.com/assets/1309249/15408938/df03e6b4-1e12-11e6-9c12-c36749de2365.png)

**Comment by Templarian** [comment]
[![creation](https://materialdesignicons.com/icon/creation)](https://materialdesignicons.com/icon/creation)
