### ISSUE TITLE
Amazon Alexa

### ISSUE THREAD

**Issue by CCOSTAN** [Templarian/MaterialDesign#1234]
An icon for the amazon echo.  Or alexa..  Or maybe a generic Virtual Voice Assistant?

**Comment by CoDEmanX** [comment]
https://design.google.com/icons/#ic_record_voice_over ?

**Comment by CCOSTAN** [comment]
I guess the official icon looks like this:

https://ifttt.com/recipes/341784-alexa-trigger-find-my-phone

**Comment by CCOSTAN** [comment]
![image](https://cloud.githubusercontent.com/assets/2160436/15414448/9643e58c-1e08-11e6-8afd-b87d66789dc7.png)

**Comment by ITSoftwareDev** [comment]
@CCOSTAN Is this what you're looking for?
![amazon-alexa](https://cloud.githubusercontent.com/assets/19522168/15562462/b3e1eeb2-22ff-11e6-83b6-6030d2b3680f.png)

[amazon-alexa.zip](https://github.com/Templarian/MaterialDesign/files/283402/amazon-alexa.zip)

**Comment by CCOSTAN** [comment]
Awesome!


On May 25, 2016, at 11:09 PM, Cristopher <notifications@github.com<mailto:notifications@github.com>> wrote:


@CCOSTAN<https://github.com/CCOSTAN> Is this what you're looking for?
[amazon-alexa]<https://cloud.githubusercontent.com/assets/19522168/15562462/b3e1eeb2-22ff-11e6-83b6-6030d2b3680f.png>

amazon-alexa.zip<https://github.com/Templarian/MaterialDesign/files/283402/amazon-alexa.zip>

-

**Comment by CCOSTAN** [comment]
Will this be added to the collection?

**Comment by CoDEmanX** [comment]
You could actually use the text-to-speech icon as generic icon for speech assistants:

[![text-to-speech](https://materialdesignicons.com/icon/text-to-speech)](https://materialdesignicons.com/icon/text-to-speech)

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/31054959-14ec7efe-a6b5-11e7-94dc-b3cd77d8eade.png)
![image](https://user-images.githubusercontent.com/15905797/31054976-3bc91eec-a6b5-11e7-9f77-ffe6404c0c6d.png)
[amazon-alexa.zip](https://github.com/Templarian/MaterialDesign/files/1347151/amazon-alexa.zip)

I've had this knocking around for a while but never uploaded it for some reason.

**Comment by augustin32** [comment]
I also made the variant with elipse, but looks not too recognizable at 1:1 resolution.
![alexa-variant24](https://user-images.githubusercontent.com/14167196/31054999-80a9935a-a6c6-11e7-9be8-abc39096efb3.png)
![alexa-variant36](https://user-images.githubusercontent.com/14167196/31055000-81cd79d6-a6c6-11e7-9526-87f94450d560.png)
![alexa-variant48](https://user-images.githubusercontent.com/14167196/31055004-83be36fe-a6c6-11e7-8172-28e32f883203.png)
[alexa-variant.zip](https://github.com/Templarian/MaterialDesign/files/1347155/alexa-variant.zip)

**Comment by GreenTurtwig** [comment]
@augustin32 It's best not to change brands icons/logos and instead centre them in a 20x20 area. https://github.com/Templarian/MaterialDesign/issues/2481

**Comment by E3V3A** [comment]
There are some design rules for the Alexa logos and icons, please check out these:
* https://developer.amazon.com/docs/alexa-voice-service/display-cards-tablets.html
* https://developer.amazon.com/docs/alexa-voice-service/logo-and-brand.html

**Comment by Templarian** [comment]
[![amazon-alexa](https://materialdesignicons.com/icon/amazon-alexa)](https://materialdesignicons.com/icon/amazon-alexa)

Assigned to the contributor account as all brand icons will be in the future.
