### ISSUE TITLE
Wireless speaker

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#1235]
I tried to match the style of `car-connected` at first, but it requires a smaller speaker icon. Then I followed the style of Google's `linked-camera`. It's the original speaker icon, moved 1px down:

![speaker-connected2](https://cloud.githubusercontent.com/assets/1309249/15411986/6f1bec5e-1e24-11e6-8813-0b4a95a9c6ad.png) ![speaker-connected](https://cloud.githubusercontent.com/assets/1309249/15411987/6f32c0aa-1e24-11e6-95a3-c37c32dec6bc.png) ![ic_speaker_24px](https://cloud.githubusercontent.com/assets/1309249/15412027/b493cb26-1e24-11e6-848d-574a70f622bb.png)

**Comment by Templarian** [comment]
[![speaker-wireless](https://materialdesignicons.com/icon/speaker-wireless)](https://materialdesignicons.com/icon/speaker-wireless)
