### ISSUE TITLE
Alert Empty | Alert Full

### ISSUE THREAD

**Issue by miguelamello** [Templarian/MaterialDesign#1238]
I like a bell as an alert icon for notification. 
My suggestion is a outlined bell for empty 
notification, and a filled bell for non-empty 
notification.

**Comment by JamesCoyle** [comment]
There is a variety of bell icons already available including filled and outline. Are you looking for something specific? Can you provide an example?

**Comment by miguelamello** [comment]
Hi James,

Is there? Well, I did not find it, please tell me where.
Anyway, I just have tried to help with an idea. I think
bells the best icon for notification, but as I've not found
them, I droped the line.

Regards,

Miguel Angelo Mello
Phone: +55 22 3053-5723
Mobile: +55 22 99998-3366
Skype: miguelamello
WhatsApp: 5522999983366
Hangout: miguelangelomello@gmail.com

**Comment by JamesCoyle** [comment]
[Bell](https://materialdesignicons.com/icon/bell)
[Bell outline](https://materialdesignicons.com/icon/bell-outline)
[Bell ring](https://materialdesignicons.com/icon/bell-ring)
[Bell ring outline](https://materialdesignicons.com/icon/bell-ring-outline)
[Bell off](https://materialdesignicons.com/icon/bell-off)
[Bell plus](https://materialdesignicons.com/icon/bell-plus)
[Bell sleep](https://materialdesignicons.com/icon/bell-sleep)

**Comment by miguelamello** [comment]
Ops, I really did not see them.
Sorry for that. Wish you the best.
Thank you.

Miguel Angelo Mello
Phone: +55 22 3053-5723
Mobile: +55 22 99998-3366
Skype: miguelamello
WhatsApp: 5522999983366
Hangout: miguelangelomello@gmail.com

**Comment by JamesCoyle** [comment]
No problem. Don't forget to close the issue. :)

**Comment by Templarian** [comment]
No problem. If you see any icons not included that you need please let us know.

By the way @miguelamello careful replying with email it includes your footer contact details (I deleted it out of the above comments).

**Comment by miguelamello** [comment]
ok.

Miguel Angelo Mello
Phone: +55 22 3053-5723
Mobile: +55 22 99998-3366
Skype: miguelamello
WhatsApp: 5522999983366
Hangout: miguelangelomello@gmail.com

**Comment by CoDEmanX** [comment]
@Templarian: add alert as tag to Bell Icons?
