### ISSUE TITLE
More File and Folder Icons

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1240]
Just a few icons I feel need merging with the file icon and folder icon. **The file icons also should have folder counterparts IMO.** I'm working on a file icon package for atom so these would be really useful. 
- [ ] Zip - [zip-box](https://materialdesignicons.com/icon/zip-box)
- [ ] Code - [code-braces](https://materialdesignicons.com/icon/code-braces)
- [ ] Information - [information](https://materialdesignicons.com/icon/information)
- [ ] Markdown - [markdown](https://materialdesignicons.com/icon/markdown)
- [ ] Presentation - file shaped version of [file-presentation-box](https://materialdesignicons.com/icon/file-presentation-box)
- [ ] Sheets - both a file and box version of the google sheets logo
- [ ] Settings  - [settings](https://materialdesignicons.com/icon/settings)
- [ ] Binary - just `01` or something
- [ ] Font - `Aa`?
- [ ] View - [eye](https://materialdesignicons.com/icon/eye)
- [ ] Superuser - [pound](https://materialdesignicons.com/icon/pound)
- [ ] File percent - #2384 

I'll add more here if required. If someone suggests any in other issues, reference this issue and I'll add them to this list. Hopefully that will help to reduce the number of open issues this repository has.

**Comment by JamesCoyle** [comment]
Added #1232

**Comment by JamesCoyle** [comment]
Added superuser and favorite from #1222

**Comment by ITSoftwareDev** [comment]
I use these in my WPF application. If suitable, you can use them.
They can also be made available on the site.

Sources in SVG format in the attached file.
![file-folder](https://cloud.githubusercontent.com/assets/19522168/15465543/51d8fad4-20d5-11e6-9b04-95be44ca537c.png)
[file-folder.zip](https://github.com/Templarian/MaterialDesign/files/277145/file-folder.zip)

**Comment by Templarian** [comment]
@ITSoftwareDev These are probably going to be too much detail for the 24x24 size while following the Guidelines, but a nice reference for ideas.

**Comment by CoDEmanX** [comment]
Network folder & protected folder: https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-191973385

Favorite folder is stock icon that needs to be added: https://design.google.com/icons/#ic_folder_special

Related: #270 (file / folder settings)

Some WIP icons:

![file-binary](https://cloud.githubusercontent.com/assets/1309249/15624441/4e5a741c-2488-11e6-87c6-966aaffcf068.png) binary file
![file-binary2](https://cloud.githubusercontent.com/assets/1309249/15624443/4e5b35fa-2488-11e6-8ba8-f6c586c9b6c5.png) binary file, smaller font
![file-braces](https://cloud.githubusercontent.com/assets/1309249/15624446/4e5eafc8-2488-11e6-9fdd-7284fae8de35.png) code file (braces), unfortunately not very crisp
![file-clock](https://cloud.githubusercontent.com/assets/1309249/15624442/4e5b4e6e-2488-11e6-9a17-c42a39ae66bc.png) log file / watched file? The clock looks off-center at larger scales.
![file-eye](https://cloud.githubusercontent.com/assets/1309249/15624444/4e5b8a0a-2488-11e6-8f7f-8e98c246ac1c.png) watched file
![file-hot](https://cloud.githubusercontent.com/assets/1309249/15624445/4e5c02dc-2488-11e6-90d5-e27f57d0e50a.png) hot file
![file-markdown](https://cloud.githubusercontent.com/assets/1309249/15624447/4e70910c-2488-11e6-8d2b-6ff8c179ddad.png) markdown file
![file-pound3](https://cloud.githubusercontent.com/assets/1309249/15624449/4e733038-2488-11e6-8d9c-6a3fcc999feb.png) superuser file
![file-special](https://cloud.githubusercontent.com/assets/1309249/15624448/4e730cf2-2488-11e6-9c1f-db51f849c985.png) special / favorite file
![folder-eye](https://cloud.githubusercontent.com/assets/1309249/15624451/4e74f2b0-2488-11e6-981d-cfe2e36ec796.png) watched folder
![folder-hot](https://cloud.githubusercontent.com/assets/1309249/15624450/4e74e86a-2488-11e6-8dab-8f092909bb88.png) hot folder
![folder-pound](https://cloud.githubusercontent.com/assets/1309249/15624452/4e755eb2-2488-11e6-9763-6189c3a0d245.png) superuser folder

**Comment by Templarian** [comment]
These look awesome!

Large `01` Binary looks more consistent. I think the code one looks fine, easy to tell it's code brackets and not `<>`. Clock looks odd, but I don't think there is an easy way to make it look nicer.

**Comment by JamesCoyle** [comment]
Added #1288

**Comment by JamesCoyle** [comment]
@Templarian Can we get these in the next release? Would be really useful for my atom file icon package for atom.

**Comment by CoDEmanX** [comment]
Which ones should I upload? I don't think I added any of them to the icon packages I uploaded.

**Comment by JamesCoyle** [comment]
Binary, code, and markdown are the ones I really need though I liked all of your WIP ones.

**Comment by MrGrigri** [comment]
Seems how this one is still open, I just had to use this one today. What about an add and delete file icon. Like these:

![add-file 4x](https://cloud.githubusercontent.com/assets/4528551/18570176/1a46e686-7b65-11e6-870d-6e971958841f.png) ![add-file](https://cloud.githubusercontent.com/assets/4528551/18570177/1a502f70-7b65-11e6-9913-02d9083e5ca4.png)

![file-remove 4x](https://cloud.githubusercontent.com/assets/4528551/18570191/35c5855c-7b65-11e6-8256-b129052fc5f7.png) ![file-remove](https://cloud.githubusercontent.com/assets/4528551/18570190/35c4434a-7b65-11e6-88c6-b38e17dbc323.png)

[add-file.zip](https://github.com/Templarian/MaterialDesign/files/475754/add-file.zip)

**Comment by Templarian** [comment]
@CoDEmanX Do you have the svg's for the ones you linked above. Back to catching up on the backlog and trying to close any issue with the contribution label.

**Comment by CoDEmanX** [comment]
https://github.com/Templarian/MaterialDesign/issues/1240#issuecomment-222284418

@Templarian Need to check on my old laptop if I still have the source files. Shall I share them all?

**Comment by Templarian** [comment]
[![file-remove](https://materialdesignicons.com/icon/file-remove)](https://materialdesignicons.com/icon/file-remove)

Closing this issue out. Lets try and create separate issues if they are still needed.
