### ISSUE TITLE
Life Ring/Support Icon Suggestion

### ISSUE THREAD

**Issue by dintendocoltd** [Templarian/MaterialDesign#1241]
A simple icon of a life ring to represent support would be good.

Something along the lines of this: http://fontawesome.io/icon/life-ring/ ?

**Comment by CoDEmanX** [comment]
I contributed one already:

https://github.com/Templarian/MaterialDesign/issues/873#issuecomment-208050697

It has yet to be added.

**Comment by Templarian** [comment]
Marking this as a duplicate. I see no reason not to include the one in #873 (oversight it hasn't been added yet). Marked it as a high priority.

**Comment by CoDEmanX** [comment]
@Templarian: I think we'll have to pay you for an extended weekend of icon adding :construction_worker:
