### ISSUE TITLE
Mac OS X Archive utility produces .cpgz files; The Unarchiver does not.

### ISSUE THREAD

**Issue by easyaspi314** [Templarian/MaterialDesign#1242]
With Archive Utility 10.10 (81) on OS X 10.11.4, when opening an archive created from Material Design Icons, I get a .cpgz.

The Unarchiver 3.10.1 (103) can successfully unzip the archive.

**Comment by Templarian** [comment]
For which download is this for?

**Comment by easyaspi314** [comment]
I have received it on downloading 5.x and 4.x action bar packs for cursor-move and account-search.

**Comment by Templarian** [comment]
Which browser are you currently using? And does another browser Firefox/Chrome/Safari have the same issue with the zip file?

**Comment by easyaspi314** [comment]
FF46.0.1
Checking browser now. Will edit.

**Comment by easyaspi314** [comment]
### I am 99% sure I figured it out. 

I was thinking about MIME types and using the `file --mime-type` command, I found that the faulty file is `application/octet-stream` instead of `application/zip`. 

We just need to assign a MIME type and we *should* be good.

**Comment by Templarian** [comment]
Oh, nice bug find/fix. Will work on getting this resolved.
