### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by kuldeepdhaka** [Templarian/MaterialDesign#1243]
README.md: "Expression Design is a __free software__ for designing vector assets."
That should be [freeware](https://en.wikipedia.org/wiki/Freeware).
> Freeware is proprietary software that is available for use at no monetary cost
> Freeware, although itself free of charge, may be intended to benefit its owner, e.g. by encouraging sales of a more capable version ("Freemium" or Shareware business model).

rewriting "Expression Design is a __freeware__ for designing vector assets." should be fine.
rewriting will clear all confusion for reader.

On the other hand, [free software](https://en.wikipedia.org/wiki/Free_software) is an altogether different thing.

**Comment by Templarian** [comment]
Fixed. By the way, I actually tried pretty hard to get Expression Design open sourced, but apparently it uses too many proprietary related things for it to be done. Still a pretty solid software for making basic icons.
