### ISSUE TITLE
Google Plus not correct

### ISSUE THREAD

**Issue by ErraticFox** [Templarian/MaterialDesign#1244]
right side of the google plus logo is not connected. https://materialdesignicons.com/icon/google-plus

**Comment by Templarian** [comment]
@ErraticFox Not sure I'm following what the issue is? "not connected"?

**Comment by ErraticFox** [comment]
The right side of the plus on the icon, the path is not a complete path (the ends are not connected). See here: https://jsfiddle.net/50f51obg/

**Comment by Templarian** [comment]
Oh this is actually by design during the optimization step unneeded connecting lines / Z entries are removed. I never really imagined anyone would be using the outlines, just filled shapes/fonts.
