### ISSUE TITLE
CDN SSL Support

### ISSUE THREAD

**Issue by jmfield2** [Templarian/MaterialDesign#1245]
Hello, We've been using the CDN in our project for a few months and recently switched to SSL-only where everything works fine on Desktop (Linux) Firefox and Chrome.  

However, Mobile Chrome (Android) refuses to use the materialdesignicons because of net::insecure_response likely caused by an incomplete certificate chain.  

SSLLabs confirms this issue: 
https://www.ssllabs.com/ssltest/analyze.html?d=cdn.materialdesignicons.com&hideResults=on

Also, the certificate is set to expire on the 1st of June, 2016 - in case you forgot :)

**Comment by Templarian** [comment]
This should be fixed this weekend. This is a known issue, but going to use this to track the SSL fixes.

Thanks for the link, personally I have like 0 knowledge on SSL. I seem to guess every-time I have to update it. :sweat_smile:

Very busy lately after the `v1.6.50` (for proof I haven't finished DOOM yet :cry:).

**Comment by Templarian** [comment]
By the way, I'll be moving to a paid solution most likely. The current solution was a quick fix a year ago when I setup the CDN, but now that it uses 400gb of bandwidth a month I'll find a real solution. :laughing:

**Comment by Templarian** [comment]
Small update, working on this today. Trying to do this with zero downtime. Testing it out with another domain right now to ensure I won't be taking the site down. I have 2 SSL certs to configure for the main domain and cdn. The new SSL cert will work on `99.3%` of devices, so should solve any isssues.

**Comment by Templarian** [comment]
Domain transferred. 2 SSL certs purchased (for materialdesignicons.com and cdn.materialdesignicons.com).

Will configure these tonight with MaxCDN / Hosting. Going to go outside for a beer... :beer: (it's like fuel for open source!)

**Comment by Templarian** [comment]
Okay, https://cdn.materialdesignicons.com/1.6.50/ is updated with the latest SSL cert and it works!

Ticket is placed for the SSL cert for MaterialDesignIcons.com and will be in shortly. Will close once that cert is tested.

**Comment by REJack** [comment]
I can confirm it works :+1:
No chain error yeah :smile:

**Comment by Templarian** [comment]
Website is now updated also. Thanks guys!

**Comment by barbeau** [comment]
@Templarian Thanks for fixing this!
