### ISSUE TITLE
social network site icon

### ISSUE THREAD

**Issue by betaconnect1** [Templarian/MaterialDesign#1248]
facebook, twitter, google plus, linkdin, github, pinterest, google doc . icon in those area will really help developer .

**Comment by CoDEmanX** [comment]
Except for Google docs, they all exist?!

[![facebook](https://materialdesignicons.com/icon/facebook)](https://materialdesignicons.com/icon/facebook) [![facebook-box](https://materialdesignicons.com/icon/facebook-box)](https://materialdesignicons.com/icon/facebook-box) [![facebook-messenger](https://materialdesignicons.com/icon/facebook-messenger)](https://materialdesignicons.com/icon/facebook-messenger) [![twitter](https://materialdesignicons.com/icon/twitter)](https://materialdesignicons.com/icon/twitter) [![twitter-box](https://materialdesignicons.com/icon/twitter-box)](https://materialdesignicons.com/icon/twitter-box) [![twitter-circle](https://materialdesignicons.com/icon/twitter-circle)](https://materialdesignicons.com/icon/twitter-circle) [![google-plus](https://materialdesignicons.com/icon/google-plus)](https://materialdesignicons.com/icon/google-plus) [![google-plus-box](https://materialdesignicons.com/icon/google-plus-box)](https://materialdesignicons.com/icon/google-plus-box) [![linkedin](https://materialdesignicons.com/icon/linkedin)](https://materialdesignicons.com/icon/linkedin) [![linkedin-box](https://materialdesignicons.com/icon/linkedin-box)](https://materialdesignicons.com/icon/linkedin-box) [![github-box](https://materialdesignicons.com/icon/github-box)](https://materialdesignicons.com/icon/github-box) [![github-circle](https://materialdesignicons.com/icon/github-circle)](https://materialdesignicons.com/icon/github-circle) [![pinterest](https://materialdesignicons.com/icon/pinterest)](https://materialdesignicons.com/icon/pinterest) [![pinterest-box](https://materialdesignicons.com/icon/pinterest-box)](https://materialdesignicons.com/icon/pinterest-box) [![slack](https://materialdesignicons.com/icon/slack)](https://materialdesignicons.com/icon/slack) [![trello](https://materialdesignicons.com/icon/trello)](https://materialdesignicons.com/icon/trello) [![discord](https://materialdesignicons.com/icon/discord)](https://materialdesignicons.com/icon/discord)

**Comment by JamesCoyle** [comment]
File-document-box works for Google Docs.

**Comment by Templarian** [comment]
Yep, I think we have all of these, so will close this issue out. Yep, discord was added in the latest release (`1.6.50`).

**Comment by CoDEmanX** [comment]
Sub-optimal at 24 pixels, but actually not too bad, @Templarian?

![file-google-docs](https://cloud.githubusercontent.com/assets/1309249/15621272/238ef49c-2460-11e6-968f-52a52a5d536a.png) docs
![file-google-spreadsheet](https://cloud.githubusercontent.com/assets/1309249/15621274/23929cfa-2460-11e6-9a92-f69e86abceb8.png) spreadshett
![file-google-presentation](https://cloud.githubusercontent.com/assets/1309249/15621277/2396c5dc-2460-11e6-8d05-a60f4d03cdfa.png) presentation
![file-google-forms](https://cloud.githubusercontent.com/assets/1309249/15621276/2396802c-2460-11e6-9091-df67ad0fe92d.png) forms
![file-google-drawings](https://cloud.githubusercontent.com/assets/1309249/15621275/239354ba-2460-11e6-8eb5-21130d42bddb.png) drawings
![file-google-drawings2](https://cloud.githubusercontent.com/assets/1309249/15621273/2391f9b2-2460-11e6-8a89-f8b62b52c4c1.png) drawings alternative

**Comment by JamesCoyle** [comment]
I'll add these to #1240.

**Comment by Templarian** [comment]
Yea, I think they kind of work.

`file-google-*` naming fine? I like the first drawing one by the way.
