### ISSUE TITLE
Icon Request: Thicker Line Icons (Check, X, Arrows, etc.)

### ISSUE THREAD

**Issue by ApotheoKing** [Templarian/MaterialDesign#1249]
It might be more appealing to see thicker icons that are made of just lines and not fuller shapes. These would be great for the toolbar, especially with darker custom themes. I personally would like these types of icons to all fit in the same dimensions so the check icon isn't taller than my back icon. This is purely for aesthetics.

**Comment by Templarian** [comment]
Do you have examples of what you mean by this?

**Comment by JamesCoyle** [comment]
The material guidelines state the stroke width should be two device pixels wide (with the exception of some extreme cases). Your suggestion would go against those guidelines and are therefore beyond the scope of this project. You are free to modify the icons yourself though.
