### ISSUE TITLE
"Around me" icon request

### ISSUE THREAD

**Issue by kyleparker** [Templarian/MaterialDesign#125]
If you have time, could you make some "around me" icons similar to these?

Thank you!

![lookaround_active](https://cloud.githubusercontent.com/assets/685946/5922614/03b34ad4-a61b-11e4-8874-98a95a031506.png)

![ic_guide](https://cloud.githubusercontent.com/assets/685946/5922603/f9bc8e28-a61a-11e4-8a89-d204402ea66b.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/rotate-3d
http://materialdesignicons.com/icon/map-marker-radius

Let me know if these will work or need modifications. Feel free to suggest others.
