### ISSUE TITLE
Icon Request: Subscription list

### ISSUE THREAD

**Issue by mantenie** [Templarian/MaterialDesign#1250]
I currently need an icon to list all subscriptions of a user. Has anyone an idea how to solve that?

**Comment by CoDEmanX** [comment]
The first picture that came to my mind:

![followers](http://www.infranken.de/storage/scl/ft/nachrichten/lokales/bad-kissingen/1783066_t1w454h300q75v34689_Bad_Kissingen_Symbolbild_pr.jpg?version=1432646452)

What kind of subscription is it though? Mailing list? Premium plan of a service?

**Comment by mantenie** [comment]
Subscriptions of items in an application. It's like following some content.

**Comment by CoDEmanX** [comment]
Spotify allows you to follow artists and playlists, but don't use any icon in their applications. I guess something with checkmarks could work though - `playlist-check`?

**Comment by mantenie** [comment]
Wow, good idea. Thanks.

**Comment by CoDEmanX** [comment]
@Templarian: `subscriptions` as alias / tag?

**Comment by Templarian** [comment]
Added.
