### ISSUE TITLE
"Update" & "Restore" icons

### ISSUE THREAD

**Issue by Ekidoxx** [Templarian/MaterialDesign#1251]
Besides [cached](https://materialdesignicons.com/icon/cached), [autorenew](https://materialdesignicons.com/icon/autorenew) and [history](https://materialdesignicons.com/icon/history), it would be great to have **[update](https://design.google.com/icons/#ic_update)** icon, especially since it was already created by Google...

Similiar with **[restore](https://design.google.com/icons/#ic_restore)** besides [backup-restore](https://materialdesignicons.com/icon/backup-restore)

**Comment by Templarian** [comment]
[![update](https://materialdesignicons.com/icon/update)](https://materialdesignicons.com/icon/update) [![restore](https://materialdesignicons.com/icon/restore)](https://materialdesignicons.com/icon/restore)

**Comment by Ekidoxx** [comment]
Thanks a lot!
