### ISSUE TITLE
bus-stop / bus-stop-covered / bus-stop-uncovered

### ISSUE THREAD

**Issue by JobsJr** [Templarian/MaterialDesign#1253]
Please add bus stop icon

**Comment by CoDEmanX** [comment]
You mean an H inside a circle outline?

**Comment by JamesCoyle** [comment]
Perhaps a `bus-square` icon? That's what the Google Maps icon for a bus stop looks like. It's quite a specific thing to fit into a 24x24px icon and there isn't really an international icon for it.

**Comment by goyney** [comment]
Google uses `subway-variant` to indicate bus stops.
[![subway-variant](https://materialdesignicons.com/icon/subway-variant)](https://materialdesignicons.com/icon/subway-variant)

We also have several `bus-*` icons.

I'm not sure what else we could possibly use to indicate this. I believe we should consider closing this request.

**Comment by PeterShaggyNoble** [comment]
Agreed with @goyney, closing this out.

If anyone *does* think of another way to represent a bus stop in a way that would be internationally recognised then please leave a comment with an example and we'll revisit this issue.

**Comment by MrGrigri** [comment]
I've got a couple of ideas that we could use to represent a `bus-stop` icon and one that could be used as a general `hail` icon for taxies and busses. I know that in other countries, one can hail a bus away from a designated stop.

![image](https://user-images.githubusercontent.com/4528551/51858625-69903800-22f2-11e9-823e-e2afc5a9a2a2.png) ![image](https://user-images.githubusercontent.com/4528551/51858876-fe933100-22f2-11e9-8746-22d37a447298.png)

![image](https://user-images.githubusercontent.com/4528551/51858693-904e6e80-22f2-11e9-8b44-0f1002662876.png)

---

[bus-stop.zip](https://github.com/Templarian/MaterialDesign/files/2804403/bus-stop.zip)

**Comment by MrGrigri** [comment]
I have created these after rethinking `bus-stop-uncovered` (#3851).

![image](https://user-images.githubusercontent.com/4528551/51863528-7dda3200-22fe-11e9-8c90-ad1131317534.png)

![image](https://user-images.githubusercontent.com/4528551/51863543-8a5e8a80-22fe-11e9-873e-c4fcd3deda0f.png) ![image](https://user-images.githubusercontent.com/4528551/51863704-ee814e80-22fe-11e9-85d8-9dc0d219f8be.png)

---

[bus-stop.zip](https://github.com/Templarian/MaterialDesign/files/2804783/bus-stop.zip)

**Comment by goyney** [comment]
I dunno about the hailing hand with all the other elements. By itself (the person), I think it makes sense for a `hail` icon, but with the sign and bench/awning, I don't know if it makes sense.

**Comment by MrGrigri** [comment]
I can see that, I'll update them real quick.

**Comment by goyney** [comment]
[![bus-stop](https://materialdesignicons.com/icon/bus-stop)](https://materialdesignicons.com/icon/bus-stop)[![bus-stop-covered](https://materialdesignicons.com/icon/bus-stop-covered)](https://materialdesignicons.com/icon/bus-stop-covered)[![bus-stop-uncovered](https://materialdesignicons.com/icon/bus-stop-uncovered)](https://materialdesignicons.com/icon/bus-stop-uncovered)
