### ISSUE TITLE
Swipe icons

### ISSUE THREAD

**Issue by vbaimas** [Templarian/MaterialDesign#1254]
Could use some navigation swipes, like:
- Swipe to left
- Swipe to right
- Diagonal swipe 

I think that these icons will be useful when the user want to navigate in swipe slider.

Thanks.

**Comment by Ekidoxx** [comment]
Maybe something like this:
![gestures](http://maxcdn.thedesigninspiration.com/wp-content/uploads/2012/10/gesture-icons-005.png)

**Comment by JamesCoyle** [comment]
Perhaps take some pointers from https://www.google.com/design/spec/patterns/gestures.html#gestures-touch-mechanics too?

**Comment by vbaimas** [comment]
@JamesCoyle i think that these pointers are using in mobile design and less in web.
@Ekidoxx yes something like this, but these icons are not clear, i don't like the index finger..

**Comment by Templarian** [comment]
One doesn't normally swipe with a cursor it is generally a trackpad/touch screen gesture. I don't think I've ever seen a cursor based application use swipe.

**Comment by JamesCoyle** [comment]
Can you give an example of what you are looking for?

**Comment by CoDEmanX** [comment]
Angular material supports swiping with cursor, but it's highly inconvenient to trigger the event with a mouse. It's also hard to discover.

**Comment by vbaimas** [comment]
Something like that..

![swipe](https://cloud.githubusercontent.com/assets/5068068/15703454/0005c2d0-27ee-11e6-937b-462ec99a7051.jpg)

**Comment by skolarianer** [comment]
What about that modification of official `touch app`

![ic_swipe](https://cloud.githubusercontent.com/assets/6286711/16986889/61f3f4e6-4e89-11e6-9a58-0a3bdee04cc1.png)

For some reason I can't attach the zip file?!

**Comment by MrGrigri** [comment]
Closing this issue out. Reference Issue [#1798](https://github.com/Templarian/MaterialDesign/issues/1798#event-935666593)
