### ISSUE TITLE
Icon Request: Deezer / iTunes / Tidal / Bandcamp 

### ISSUE THREAD

**Issue by markimeyer** [Templarian/MaterialDesign#1255]
Super usefull for musicians and record labels. I can design them but the Become a Contributor (https://materialdesignicons.com/contribute) option is disabled.

- Deezer:
Guidelines: https://cdns-files.dzcdn.net/developers/Deezer_GuidelinesUK_nov2011.pdf
Logo: https://cdns-files.dzcdn.net/developers/GREY-N&B_300dpi.zip

- Tidal:
Icon: http://memberdata.s3.amazonaws.com/hi/hitsdd/photos/hitsdd_photo_gal__photo_1464060291.png
I could do a normal and squared version.

- iTunes:
Icon: https://redalemeden.com/images/itunes/12-2-0.png

- Bandcamp:
Guidelines: https://bandcamp.com/buttons
Icons: https://bandcamp.com/img/buttons/bandcamp-button-circle-black.zip

**Comment by JamesCoyle** [comment]
If you want to have a go you can post them here.

**Comment by markimeyer** [comment]
@JamesCoyle should I upload the icons here as SVG?

**Comment by JamesCoyle** [comment]
If you just post PNGs and leave a link to an svg download @Templarian will sort it.

**Comment by markimeyer** [comment]
# Deezer

Is this ok?
SVG: https://www.dropbox.com/s/egs4w2ccepe3w76/mdi-deezer.svg?dl=0
![deezer-24](https://cloud.githubusercontent.com/assets/7417277/15690996/48f41996-2754-11e6-845a-0271f1c7943c.png)

**Comment by markimeyer** [comment]
# Bandcamp

## Normal
SVG: https://www.dropbox.com/s/amc9mmtlk1u25uh/bandcamp.svg?dl=0
PNG: ![bandcamp](https://cloud.githubusercontent.com/assets/7417277/15698613/65a9ae4e-2794-11e6-830e-2bab34dc28df.png)

## Circle
SVG: https://www.dropbox.com/s/n6c1nr1fz97z38h/bandcamp-circle.svg?dl=0
PNG: ![bandcamp-circle](https://cloud.githubusercontent.com/assets/7417277/15698619/75e566fe-2794-11e6-8c54-69fc9d110e97.png)

**Comment by Templarian** [comment]
Just a reminder... not all logos will get in (especially some of these smaller companies). I generally only add the large social media sites/services. :sweat_smile:

**Comment by markimeyer** [comment]
@Templarian Ok! I promise to only post super big companies :smile: 

Deezer is one of the biggest music streaming services, only second to Spotify! Available in more than 180 countries, super important for bands!
https://en.wikipedia.org/wiki/Deezer

Bandcamp is a really important streaming and sales website for independent bands and labels!
https://en.wikipedia.org/wiki/Bandcamp - http://mashable.com/2013/11/19/spotify-bandcamp/

These probably will be very used by bands :musical_note:

**Comment by markimeyer** [comment]
@Templarian Oh, I'm doing these icons because there aren't in Font Awesome and you guys accept colaborations, so I switched from FA to MDI in my projects. Probably I'll be posting a lot of icons for this repo :muscle:

**Comment by markimeyer** [comment]
# Tidal
PNG: ![tidal](https://cloud.githubusercontent.com/assets/7417277/15724873/1baca85e-2817-11e6-9707-94ba8aa8dc5e.png)
SVG: https://www.dropbox.com/s/7x9ku0385hpub4z/tidal.svg?dl=0

**Comment by Templarian** [comment]
[![bandcamp](https://materialdesignicons.com/icon/bandcamp)](https://materialdesignicons.com/icon/bandcamp) [![itunes](https://materialdesignicons.com/icon/itunes)](https://materialdesignicons.com/icon/itunes)

Deezer doesn't fit the style and tidal is way too niche of a service.

**Comment by ozgurg** [comment]
@Templarian Deezer changes its logo. Can you give another chance?

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
