### ISSUE TITLE
Can we have mdi-device-data-usage?

### ISSUE THREAD

**Issue by hacklover** [Templarian/MaterialDesign#1259]
Hi people!
"mdi-device-data-usage" icon comes from another icon pack about Material design.
Anyone can convert it? https://s3.amazonaws.com/kantan-dresssed-demos/demos/ives/blue_preview/007_icons@fa-lightbulb-o%252F004_mdi_icons.html

**Comment by JamesCoyle** [comment]
https://design.google.com/icons/#ic_data_usage

**Comment by CoDEmanX** [comment]
This will be added as part of #420, row 369 in the spreadsheet.

**Comment by hacklover** [comment]
Ok, thanks guys!
