### ISSUE TITLE
Icon request: Garage Door Open/Closed

### ISSUE THREAD

**Issue by 625alex** [Templarian/MaterialDesign#1261]
Thanks a million!

**Comment by alexefremo** [comment]
Here you go:

![ic_garage_closed_black_24px](https://cloud.githubusercontent.com/assets/3408199/18086581/0feac18c-6eca-11e6-9df7-22c709e41ea9.png)
![ic_garage_closed_black_48px](https://cloud.githubusercontent.com/assets/3408199/18086577/0fe5d5f0-6eca-11e6-9a7f-c1e287e6a090.png)
![ic_garage_opened_black_512px](https://cloud.githubusercontent.com/assets/3408199/18086579/0fe8c512-6eca-11e6-9c1d-8fd0c8a8e19a.png)

![ic_garage_opened_black_24px](https://cloud.githubusercontent.com/assets/3408199/18086580/0fe9a32e-6eca-11e6-94ce-aabbee149f32.png)
![ic_garage_opened_black_48px](https://cloud.githubusercontent.com/assets/3408199/18086578/0fe8028a-6eca-11e6-87c4-819b476df158.png)
![ic_garage_closed_black_512px](https://cloud.githubusercontent.com/assets/3408199/18086576/0fe5a710-6eca-11e6-8f11-bb275654360e.png)

**Comment by alexefremo** [comment]
More optimised (as for me) version:


![ic_garage_closed_black_24px](https://cloud.githubusercontent.com/assets/3408199/18086867/78660158-6ecb-11e6-9ee1-4a14e341d1ca.png)
![ic_garage_closed_black_48px](https://cloud.githubusercontent.com/assets/3408199/18086868/78687546-6ecb-11e6-98f6-765e49208548.png)
![ic_garage_closed_black_512px](https://cloud.githubusercontent.com/assets/3408199/18086866/78657dd2-6ecb-11e6-9bc4-8220c03766bf.png)

![ic_garage_opened_black_24px](https://cloud.githubusercontent.com/assets/3408199/18086863/7864581c-6ecb-11e6-8635-67978b76eeb3.png)
![ic_garage_opened_black_48px](https://cloud.githubusercontent.com/assets/3408199/18086864/78649dfe-6ecb-11e6-80a2-8350f7d0de53.png)
![ic_garage_opened_black_512px](https://cloud.githubusercontent.com/assets/3408199/18086865/7864b1fe-6ecb-11e6-8bba-8fad17334294.png)

**Comment by Templarian** [comment]
[![garage](https://materialdesignicons.com/icon/garage)](https://materialdesignicons.com/icon/garage) [![garage-open](https://materialdesignicons.com/icon/garage-open)](https://materialdesignicons.com/icon/garage-open)
