### ISSUE TITLE
Gears / Cogs (settings-multiple)

### ISSUE THREAD

**Issue by 625alex** [Templarian/MaterialDesign#1262]

**Comment by CoDEmanX** [comment]
Can you give examples?

**Comment by 625alex** [comment]
3 gears icon

https://rdstation-static.s3.amazonaws.com/images/landing_page/22600/left-side-image.jpg

2 gears icon

http://toyls.com/apps/metro/resources/gears.png

**Comment by CoDEmanX** [comment]
Hm, not liking the result:

![cog2](https://cloud.githubusercontent.com/assets/1309249/15798446/3eacface-2a39-11e6-92fb-fc914da8157b.png) ![cog3](https://cloud.githubusercontent.com/assets/1309249/15798447/3eae3042-2a39-11e6-8bad-520f357c7f8f.png)

**Comment by Ekidoxx** [comment]
Fontawesome also has [cog](http://fontawesome.io/icon/cog/) & [cogs](http://fontawesome.io/icon/cogs/)

**Comment by PeterShaggyNoble** [comment]
Google's extended icon set includes a cogs icon:

![manufacturing](https://user-images.githubusercontent.com/15157491/33936175-889d214e-dff6-11e7-9566-c1594801f56a.png)

**Comment by Templarian** [comment]
[![cogs](https://materialdesignicons.com/icon/cogs)](https://materialdesignicons.com/icon/cogs)
