### ISSUE TITLE
Icon request: Normal search icon

### ISSUE THREAD

**Issue by sero583** [Templarian/MaterialDesign#1265]
As we know them from anywhere.

**Comment by CoDEmanX** [comment]
Use the normal search and search for "search". The icon is called "magnify" and has an alias "search".

**Comment by sero583** [comment]
@CoDEmanX Oh, i'm very sorry, for this mistake!
I seeked and seeked it, but not seen and thouht it isn't avaible there and tryed with searching "Search", but nothing comed, so i thought, i could open a icon request.

**Comment by sero583** [comment]
@CodEmanX Noch vielen Dank für diese Auskunft von Ihnen! :)

**Comment by JamesCoyle** [comment]
@Templarian Would probably be a good idea to make the search term case insensitive.

**Comment by sero583** [comment]
@JamesCoyle Yeah, it would be great! :)

**Comment by CoDEmanX** [comment]
Awesome sero, thanks to you I realized that the search isn't broken in chrome for Android. I just happened to search for capitalized words on my mobile and the search is case-sensitive. Search results are actually the same on desktop.
