### ISSUE TITLE
accessibility

### ISSUE THREAD

**Issue by amfp** [Templarian/MaterialDesign#1267]
Representation of the **new accessibility icon**

![image](https://cloud.githubusercontent.com/assets/338885/15810695/d1b38576-2b66-11e6-97da-8f48a936370d.png)

**Comment by CoDEmanX** [comment]
Looks much like https://design.google.com/icons/#ic_accessibility
which is called `human` in MDI?

**Comment by Templarian** [comment]
I'm not sure this one is going to look right following the MDI guidelines. Might be best going with the more generic Google `human` icon.
