### ISSUE TITLE
New icon - credit card plus

### ISSUE THREAD

**Issue by mrsdohpaz** [Templarian/MaterialDesign#1268]
Love this library so I thought I'd submit a few myself that I will need eventually.

![credit-card-plus](https://cloud.githubusercontent.com/assets/7914791/15810448/af0336e2-2b6c-11e6-900e-33810fbec280.png)

[credit-card-plus.svg.zip](https://github.com/Templarian/MaterialDesign/files/299640/credit-card-plus.svg.zip)

**Comment by Templarian** [comment]
[![credit-card-plus](https://materialdesignicons.com/icon/credit-card-plus)](https://materialdesignicons.com/icon/credit-card-plus)
