### ISSUE TITLE
New icon - bank plus

### ISSUE THREAD

**Issue by rosemarystanley** [Templarian/MaterialDesign#1269]
![bank-plus](https://cloud.githubusercontent.com/assets/7914791/15810614/6920563a-2b6e-11e6-8942-61f8207de5c1.png)

[bank-plus.svg.zip](https://github.com/Templarian/MaterialDesign/files/299653/bank-plus.svg.zip)

**Comment by Templarian** [comment]
@mrsdohpaz Please add some a justification for new icons (we generally don't add icons with a plus unless there is a solid repeatable use case).

Thanks for the contribution!

**Comment by mrsdohpaz** [comment]
Gotcha. For example I'm working on some banking software that allows multiple accounts. So this would be an "add new account" icon.

**Comment by mrsdohpaz** [comment]
@Templarian Is there anywhere there is a guideline for what icons are typically accepted. I didn't really see that anywhere on the contribution page. Thanks!

**Comment by Templarian** [comment]
[![bank-plus](https://materialdesignicons.com/icon/bank-plus)](https://materialdesignicons.com/icon/bank-plus) [![bank-remove](https://materialdesignicons.com/icon/bank-remove)](https://materialdesignicons.com/icon/bank-remove) [![bank-minus](https://materialdesignicons.com/icon/bank-minus)](https://materialdesignicons.com/icon/bank-minus)
