### ISSUE TITLE
Create a Cheatsheet

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#127]
Create a Cheatsheet with all the icons and aliases. This should use the webfont for easy loading and quick searching. Generate static HTML page that can be saved.
- Really basic minimal design.
- Includes Aliases.
- Inline embed all SVG icons.
- Inline all CSS for the page.

**Comment by braginteractive** [comment]
:+1:

**Comment by Templarian** [comment]
It's been almost a year now since I opened this issue... not fully done yet, but you can preview the cheatsheet here: https://materialdesignicons.com/cheatsheet
