### ISSUE TITLE
Print Settings - Request

### ISSUE THREAD

**Issue by ButchMonkey** [Templarian/MaterialDesign#1270]
Would it be possible to add print settings icon?
Essentially a mix of the printer icon and the settings / gear icon.
(Example attached)

![printsettings](https://cloud.githubusercontent.com/assets/9367266/15829210/a6ef5c08-2c0a-11e6-85ba-eca2c3342a01.PNG)

Thanks in advance

**Comment by Templarian** [comment]
Yep, we've standardized on using 3 dots for all settings icons. Cog just doesn't work well with the Material Design guidelines and the size constraits.

**Comment by Templarian** [comment]
[![printer-settings](https://materialdesignicons.com/icon/printer-settings)](https://materialdesignicons.com/icon/printer-settings)
