### ISSUE TITLE
Font used within icons?

### ISSUE THREAD

**Issue by ButchMonkey** [Templarian/MaterialDesign#1271]
Not sure if this the correct place to ask, please remove if not.

I wish to create some material icons of my own - what font is used in icons such as  the exposure(+1,+2) icons or 1-6 "looks" icons by Google.

I noticed the fonts for these icons are different however, none of which are Roboto however

**Comment by CoDEmanX** [comment]
I'm not sure what they used, perhaps the old Roboto font?

**Comment by Templarian** [comment]
It's usually Roboto I think. Might be one of the bold variants in some cases.

**Comment by Templarian** [comment]
These are
