### ISSUE TITLE
24 / 7

### ISSUE THREAD

**Issue by AeonDave** [Templarian/MaterialDesign#1272]
it wolud be great if will be implemented a 24/7 icon.
something like this:

![10-128](https://cloud.githubusercontent.com/assets/7406886/15854713/9eab8980-2cab-11e6-8513-d38c2077db93.png)

Thank you

**Comment by CoDEmanX** [comment]
For 24/7 shops, there is `store-24-hour`.
Is that sufficient?

**Comment by Ekidoxx** [comment]
Somehow I wouldn't guess by the `store-24-hour` icon what it's supposed to mean/stand for, but it might be just me

**Comment by goyney** [comment]
Here's my attempt at your original idea, though it breaks all kinds of Material rules.
![image](https://user-images.githubusercontent.com/1015040/51010862-1d887980-1524-11e9-8735-9f5817291b39.png)
[24-hour.svg.zip](https://github.com/Templarian/MaterialDesign/files/2747931/24-hour.svg.zip)

I'll let @Templarian decide if it's acceptable or not.

---

`brightness-4` seems like the logical candidate for this type of icon. 
[![brightness-4](https://materialdesignicons.com/icon/brightness-4)](https://materialdesignicons.com/icon/brightness-4)

**Comment by JapanYoshi** [comment]
My attempt:
![image](https://user-images.githubusercontent.com/8707990/75335138-b15a0800-58d4-11ea-8e10-4b294fe42570.png)
```M 13 2.0488281 L 13 4.0683594 C 16.945834 4.5604428 20.002315 7.920947 20 12 C 19.9982 15.21385 18.083615 18.020202 15.28125 19.28125 L 13 17 L 13 22 L 18 22 L 16.777344 20.777344 C 19.905667 19.072882 21.999881 15.76409 22 12 C 22.000163 6.8150557 18.052775 2.5499588 13 2.0488281 z M 11 2.0546875 C 9.0540903 2.2515073 7.2006407 3.0135853 5.6757812 4.2617188 L 7.0976562 5.6835938 C 8.2341372 4.8002528 9.5841523 4.2499299 11 4.0703125 L 11 2.0546875 z M 4.2617188 5.6757812 C 3.0215729 7.1961552 2.2560737 9.0477531 2.0605469 11 L 4.0703125 11 C 4.2506937 9.5791884 4.8091932 8.2328539 5.6875 7.1015625 L 4.2617188 5.6757812 z M 6 8 L 6 10 L 9 10 L 9 11 L 8 11 C 6.8954305 11 5.9755982 11.895701 6 13 L 6 16 L 8 16 L 11 16 L 11 14 L 8 14 L 8 13 L 9 13 C 10.104569 13 11 12.104569 11 11 L 11 10 C 11 8.8954305 10.104569 8 9 8 L 6 8 z M 12 8 L 12 13 L 15 13 L 15 16 L 17 16 L 17 13 L 18 13 L 18 11 L 17 11 L 17 8 L 15 8 L 15 11 L 14 11 L 14 8 L 12 8 z M 2.0507812 13 C 2.2509862 14.952356 3.0212589 16.80264 4.265625 18.320312 L 5.6875 16.898438 C 4.8091931 15.767146 4.2506936 14.420812 4.0703125 13 L 2.0507812 13 z M 7.1054688 18.308594 L 5.6816406 19.732422 C 7.1996974 20.973622 9.0491695 21.741122 11 21.939453 L 11 19.929688 C 9.5801682 19.747488 8.2352312 19.187659 7.1054688 18.308594 z ```

**Comment by goyney** [comment]
[![hours-24](https://materialdesignicons.com/icon/hours-24)](https://materialdesignicons.com/icon/hours-24)
