### ISSUE TITLE
Jellyfish icon

### ISSUE THREAD

**Issue by cpalosrejano** [Templarian/MaterialDesign#1273]
Maybe like this one.
It seems flat.
![flat-jelly](https://cloud.githubusercontent.com/assets/2341804/15872064/d68445e4-2cf7-11e6-9580-c090f0d5fa63.png)

**Comment by RamakrishnaUX** [comment]
![jellyfish](https://cloud.githubusercontent.com/assets/8967337/16716540/c12c9a04-471c-11e6-9a7d-821c58577fe1.png)
[jellyfish.zip](https://github.com/Templarian/MaterialDesign/files/356228/jellyfish.zip)

**Comment by CoDEmanX** [comment]
It's unfortunately using the entire 24x24 pixels. Would need to be 20x20, and probably the tentacles a bit clearer separated.

**Comment by CoDEmanX** [comment]
Ah, it was only the canvas that had the wrong size. It works really nicely like this:

![image](https://user-images.githubusercontent.com/1309249/38773511-72cae352-404e-11e8-994b-5ddc283bce74.png)

[jellyfish.zip](https://github.com/Templarian/MaterialDesign/files/1911467/jellyfish.zip)

**Comment by Croutonix** [comment]
I would remove the reflection.

**Comment by goyney** [comment]
Added. 😄
