### ISSUE TITLE
Missing many Google stock icons from Material Design Icons 2.2.0

### ISSUE THREAD

**Issue by quietmint** [Templarian/MaterialDesign#1276]
Looks like you're missing most of the 41 Google stock icons added in [Material Design Icons 2.2.0 (released Feb 2016)](https://github.com/google/material-design-icons/releases/tag/2.2.0). For example, "**transfer within a station**" and "**restaurant**".

![transfer within a station](http://www.iconres.com/android/res/material_icons/external-assets/v4/icons/png/ic_transfer_within_a_station_black_48dp.png) ![restaurant](http://www.iconres.com/android/res/material_icons/external-assets/v4/icons/png/ic_restaurant_black_48dp.png)

**Comment by CoDEmanX** [comment]
See #420
