### ISSUE TITLE
Fuel Tanker Icon

### ISSUE THREAD

**Issue by mmasanova** [Templarian/MaterialDesign#1277]
Fuel Tanker Icon would be great, maybe something like this?

![image](https://cloud.githubusercontent.com/assets/5401152/15933209/c3477fb8-2e56-11e6-92c6-3a2b33a43539.png)

**Comment by ButchMonkey** [comment]
Also would like to see this, Thanks

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/51010169-24fa5380-1521-11e9-84df-fbd86f8baf33.png)
[tanker-truck.svg.zip](https://github.com/Templarian/MaterialDesign/files/2747879/tanker-truck.svg.zip)

**Comment by goyney** [comment]
[![tanker-truck](https://materialdesignicons.com/icon/tanker-truck)](https://materialdesignicons.com/icon/tanker-truck)
