### ISSUE TITLE
Icon Request: GitLab

### ISSUE THREAD

**Issue by Low012** [Templarian/MaterialDesign#1279]
A [GitLab](https://about.gitlab.com/) icon would be great!

Not sure if anything material can be created from their colored icon.
![favicon-160x160](https://cloud.githubusercontent.com/assets/11596220/15957225/e945249e-2eed-11e6-9423-3142f69d977b.png)

**Comment by Templarian** [comment]
Yea, I've thought about including it before, but they don't really have a black/white version of their logo which is kind of annoying. Even with just 2 colors the logo looks odd.

![2colors](https://cloud.githubusercontent.com/assets/338885/15993724/7edd7494-30b4-11e6-8bc1-0e4784917628.png)
![solid](https://cloud.githubusercontent.com/assets/338885/15993719/2c2712b4-30b4-11e6-98a4-a1345f3bf7da.png)

@CoDEmanX You think this is workable or agree this isn't possible?

**Comment by JamesCoyle** [comment]
How would it look with the dark orange triangles filled and the other ones outline?

**Comment by Templarian** [comment]
Good idea (about to get off a train, so can't mock it up), but that might be a good way to make it work in a monochrome design. I really want to include it, but simply turning it a solid black as you can see doesn't work well.

**Comment by JamesCoyle** [comment]
Yeah the silhouette is really not recognisable.

**Comment by GreenTurtwig** [comment]
http://fontawesome.io/icon/gitlab/  
Font Awesome has a GitLab icon, personally I'm not a fan of it. :-/

**Comment by Templarian** [comment]
I've reached out to GitLab on twitter on what they prefer or if they have a design: https://twitter.com/templarian/status/764180706855714820

See if they say anything.

**Comment by abuango** [comment]
Hi, I am with the Service Engineering team at GitLab. We do have a black and white logo, See Attached. And you can get others at : https://about.gitlab.com/press/ 
![stacked_wm_grayscale](https://cloud.githubusercontent.com/assets/2991038/17650386/5864a884-6244-11e6-89ff-58117ecb6489.png)
![wm_grayscale](https://cloud.githubusercontent.com/assets/2991038/17650387/5890e106-6244-11e6-97d2-e5058cc8355c.png)

**Comment by straurob** [comment]
The black and white logo mentioned by @abuango has a nice look. Is there any update on this icon request?

**Comment by PeterShaggyNoble** [comment]
@abuango, do you have a *single* colour version of the icon?

**Comment by abuango** [comment]
@PeterShaggyNoble We don't currently have a single colour logo. All available logos are here: https://about.gitlab.com/press/

**Comment by Templarian** [comment]
Closing this issue out as modifying the logo would go against the branding guidelines. Well reopen this if anything changes.

For anyone reading this in the future please use an inline SVG/Vector for the GitLab icon. 😸

**Comment by raniesantos** [comment]
Please stop arguing about the design and someone just design one [similar to this](https://fontawesome.com/v4.7.0/icon/gitlab) and be done with it.

**Comment by Templarian** [comment]
@raniesantos We have to follow the companies brand guidelines. We can't always include icons since any modification may be against said guidelines.

On the good news it looks like they seem to be fine with an outline version. Not seeing an approved version like Font Awesome's, but we can check.

https://about.gitlab.com/handbook/marketing/corporate-marketing/#the-gitlab-logo

@abuango Any input would be helpful (still have probably 2 weeks until the next release).

**Comment by MrGrigri** [comment]
This is the specific link to the outlined version: https://about.gitlab.com/handbook/marketing/corporate-marketing/#label-icons

**Comment by Templarian** [comment]
[![gitlab](https://materialdesignicons.com/icon/gitlab)](https://materialdesignicons.com/icon/gitlab)
