### ISSUE TITLE
Amazon and eBay Icon

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#128]

**Comment by Templarian** [comment]
eBay's logo doesn't really fit the style all that well... hmm.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/amazon
[ebay](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/ebay.svg) Not included since it is not really visible at that size.

You can use the svg file in http://materialdesignicons.com/custom
