### ISSUE TITLE
Icon Request :Meeting, Conference

### ISSUE THREAD

**Issue by Aexyn** [Templarian/MaterialDesign#1280]

**Comment by CoDEmanX** [comment]
This might work for us:

![meeting](http://downloadicons.net/sites/default/files/meeting-icon-27686.png)

I also created an icon for Google groups: #434

**Comment by PeterShaggyNoble** [comment]
[![account-group](https://user-images.githubusercontent.com/15157491/36853953-b1627486-1d67-11e8-9fe4-ebf287eebc67.png)](https://materialdesignicons.com/icon/account-group)
