### ISSUE TITLE
Icon Request: Processor/CPU, Memory/RAM, Disk/HDD, Network:Ethernet/WiFi

### ISSUE THREAD

**Issue by realies** [Templarian/MaterialDesign#1281]

**Comment by CoDEmanX** [comment]
CPU / RAM:

[![memory](https://materialdesignicons.com/icon/memory)](https://materialdesignicons.com/icon/memory) [![chip](https://materialdesignicons.com/icon/chip)](https://materialdesignicons.com/icon/chip)

Also related: developer boards (Raspberry Pi, Arduino, ...)

[![raspberrypi](https://materialdesignicons.com/icon/raspberrypi)](https://materialdesignicons.com/icon/raspberrypi)

Yet to be added (#420): https://design.google.com/icons/#ic_developer_board

Disk / HDD:

[![disk](https://materialdesignicons.com/icon/disk)](https://materialdesignicons.com/icon/disk) [![harddisk](https://materialdesignicons.com/icon/harddisk)](https://materialdesignicons.com/icon/harddisk) [![content-save](https://materialdesignicons.com/icon/content-save)](https://materialdesignicons.com/icon/content-save)

Related request: #1078 Flash storage icons

Ethernet / WiFi:

[![ethernet](https://materialdesignicons.com/icon/ethernet)](https://materialdesignicons.com/icon/ethernet) [![ethernet-cable](https://materialdesignicons.com/icon/ethernet-cable)](https://materialdesignicons.com/icon/ethernet-cable) [![lan](https://materialdesignicons.com/icon/lan)](https://materialdesignicons.com/icon/lan) [![lan-connect](https://materialdesignicons.com/icon/lan-connect)](https://materialdesignicons.com/icon/lan-connect) [![wifi](https://materialdesignicons.com/icon/wifi)](https://materialdesignicons.com/icon/wifi) [![router](https://materialdesignicons.com/icon/router)](https://materialdesignicons.com/icon/router) [![access-point-network](https://materialdesignicons.com/icon/access-point-network)](https://materialdesignicons.com/icon/access-point-network)

To be added (#420):

Hotspot - https://design.google.com/icons/#ic_wifi_tethering
Wifi signal - https://design.google.com/icons/#ic_network_wifi
