### ISSUE TITLE
Icon request: Add appointment, add time slot & user work schedule

### ISSUE THREAD

**Issue by jacobludvigsen** [Templarian/MaterialDesign#1282]
Hi, I am looking for 3 icons Add appointment, add time slot & user work schedule. Please see attached as inspiration to what im looking for.

Hope somebody can help :)

Thanks
Jacob
![screen shot 2016-06-10 at 15 31 32](https://cloud.githubusercontent.com/assets/19857980/15965877/ab70e03a-2f20-11e6-994f-b40b37e053a9.png)

**Comment by JamesCoyle** [comment]
We now have the following which can handle two of the three cases:

[![](https://materialdesignicons.com/icon/calendar-plus)](https://materialdesignicons.com/icon/calendar-plus)

[![](https://materialdesignicons.com/icon/account-clock
)](https://materialdesignicons.com/icon/account-clock)

If you still need the `clock-plus` icon please create a new request for it so we can better track it.
