### ISSUE TITLE
Stack of coins icon, like cash

### ISSUE THREAD

**Issue by jorisoudejans** [Templarian/MaterialDesign#1283]

**Comment by Templarian** [comment]
Duplicate #328.

**Comment by koppor** [comment]
#328 implemented two coins:

![grabbed_20160917-122918](https://cloud.githubusercontent.com/assets/1366654/18607621/62fc4aa6-7cd2-11e6-9758-b962c56b6b72.png)

Here, a stack of coins is wished. Example:

![grabbed_20160917-122829](https://cloud.githubusercontent.com/assets/1366654/18607618/5799ff46-7cd2-11e6-845a-a032c7332ee5.png)

The latter icon is very different from the other coins. I'm not sure if the [current coins icon](https://materialdesignicons.com/icon/coins) is really recognizable by users. A stack of coins seems to be more common for me.
