### ISSUE TITLE
Turnaround time on when contributors icons are added to the font set

### ISSUE THREAD

**Issue by jtanksley** [Templarian/MaterialDesign#1284]
Just wanted to know the turnaround time between being accepted as a contributor and being able to download the font set with said contributor's icons included?  I apologize in advance if this is the wrong place to post this as it's not an actual issue but I couldn't find a forum link in which I could ask this question.

Thanks in advance,

JT

**Comment by Templarian** [comment]
No problem. It varies heavily based on the communities interest in an issue. Release for the font are usually only done every 100 or so icons (this count includes adding official icons).

Right now I'm taking a minor break and on vacation, but will be adding more time soon to help knock down the backlog.
