### ISSUE TITLE
optimised svg for speaker notes off

### ISSUE THREAD

**Issue by nathanvv** [Templarian/MaterialDesign#1285]
https://design.google.com/icons/#ic_speaker_notes_off

**Comment by CoDEmanX** [comment]
What do you mean by optimized SVG? We don't even seem to have that icon in MDI...

**Comment by nathanvv** [comment]
Sorry meant to have a request for the new "SPEAKER NOTES OFF" icon ... https://design.google.com/icons/#ic_speaker_notes_off

**Comment by Templarian** [comment]
[![message-bulleted-off](https://materialdesignicons.com/icon/message-bulleted-off)](https://materialdesignicons.com/icon/message-bulleted-off) [![message-bulleted](https://materialdesignicons.com/icon/message-bulleted)](https://materialdesignicons.com/icon/message-bulleted)

**Comment by Templarian** [comment]
Also there is an alias for both those icons. `speaker-notes` / `speaker-notes-off`.
