### ISSUE TITLE
Weather pressure icon

### ISSUE THREAD

**Issue by arsaboo** [Templarian/MaterialDesign#1286]
Something like 

![image](https://cloud.githubusercontent.com/assets/18319734/15992002/d19edf62-308f-11e6-8472-c1a0d6a41dd3.png)

**Comment by JamesCoyle** [comment]
Would gauge work? We try not to make icons too specific as it is hard to fit enough detail in the small space and can often reduce recognition of the icon meaning.

**Comment by arsaboo** [comment]
Oh yeah....a simple gauge would be absolutely perfect.

**Comment by CoDEmanX** [comment]
There are already two fitting icons, gauge and speedometer.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/gauge
https://materialdesignicons.com/icon/speedometer
