### ISSUE TITLE
Heads / Tails Coin

### ISSUE THREAD

**Issue by jacksonrayhamilton** [Templarian/MaterialDesign#1287]
There is a set of icons for all six sides of a six-sided die and for other types of dice. I think a good complement, for the sake of gaming, would be icons for the two sides of a coin: "heads" and "tails."

I'm not exactly sure what the icons should look like. "Heads" seems easy, there would just be a silhouette of a person's head inside a circle; e.g., an [American penny](http://lincolnpennies.net/wp-content/uploads/2009/08/lincoln_penny_obverse1.jpg). I guess for "tails" we could put something like a snake, monkey or [dragon](http://english.stackexchange.com/questions/154584/where-does-the-term-heads-or-tails-come-from), since those animals have prominent tails. Another idea would be to use the [same animal, front and back](http://kafelia.files.wordpress.com/2008/09/elephant_coin.jpg?w%20300%20h%20153).

**Comment by PeterShaggyNoble** [comment]
I don't know that this is going to be easy to communicate seeing as coins differ from country to country and I don't think abstracting it (to use your elephant idea, for example) is going to help. I'd suggest just using a `H` and `T`  in a circle.

Leaving open for now, in case one of the icon designers have any ideas.

**Comment by jacksonrayhamilton** [comment]
Maybe a couple different coin designs mapping to a couple different significant cultures would suffice, too.

**Comment by JamesCoyle** [comment]
I'd suggest a coin with a head in it as it's pretty much universal. Then we could do with a more international icon for coin that doesn't use the dollar sign. Perhaps something like the Mario coins would be recognizable

**Comment by PeterShaggyNoble** [comment]
[`account-circle`](https://materialdesignicons.com/icon/account-circle) or [`account-circle-outline`](https://github.com/Templarian/MaterialDesign/issues/1110) for "heads", maybe?

**Comment by jacksonrayhamilton** [comment]
@PeterShaggyNoble Those icons’ usual purpose in the MD context makes them a little riskier for this dual purpose, but honestly I couldn’t imagine the “heads” icon looking much different.

If you give icons alias names, maybe you could alias “account-circle” as “coin-heads,” to complement our prospective “coin-tails” icon.

**Comment by PeterShaggyNoble** [comment]
I would say usage defines context, rather than the guidelines 😉 

Adding the `Alias` tag for when/if `coin-tails` is added.

**Comment by goyney** [comment]
I'd simply go with the letters. Used in the proper context, it should be easy to convey their meaning. Anything else gets significantly harder for the icon to actually mean something. Using `account-circle-outline` may work for heads, but there is no universal "tails" short of an actual tail, which I feel is really pushing it.

![image](https://user-images.githubusercontent.com/1015040/48786088-124b6700-ecb4-11e8-85f5-30839870c8c0.png)![image](https://user-images.githubusercontent.com/1015040/48786106-1d05fc00-ecb4-11e8-8e53-6d8d367b33aa.png)

[coin-faces.zip](https://github.com/Templarian/MaterialDesign/files/2600568/coin-faces.zip)

**Comment by jacksonrayhamilton** [comment]
@goyney Years ago I would have disagreed, but I eventually learned that English is becoming a universal language, so I’m not opposed to “H/T”.

**Comment by Templarian** [comment]
I'm going to be adding circle/circle-outline for all `alpha` icons. This will handle this issue I believe. there are too many uses cases for having a letter in a circle.

@jacksonrayhamilton Actually it goes against the guidelines we have to use letters to represent an icon, so I wouldn't add `coin-heads` as names. These can be aliases for `alpha-h-circle-outline` and `alpha-t-circle-outline`.

We do break this rule in very specific examples though where the English word is used across latin based languages.

**Comment by CoDEmanX** [comment]
FYI: In German it's "Kopf oder Zahl" (head or number), so neither a literal tail nor H/T work.

**Comment by jacksonrayhamilton** [comment]
Universality is a goal of this project yet this concept apparently cannot be represented universally.  Therefore the designer should choose symbols that work in the context of his culture.
