### ISSUE TITLE
icon for zip file

### ISSUE THREAD

**Issue by narottam-wittyparrot** [Templarian/MaterialDesign#1288]
icon for zip file is not available in google design.how to create zip icon similar for other google design icon

**Comment by PeterShaggyNoble** [comment]
[![zip-box](https://user-images.githubusercontent.com/15157491/36905644-c270c538-1e2b-11e8-9eca-3b8d2bfe32bc.png)](https://materialdesignicons.com/icon/zip-box)

**Comment by Waleedov** [comment]
That is not a ZIP file. Can we have something similar to this with ZIP?
https://materialdesignicons.com/icon/file-account

**Comment by JapanYoshi** [comment]
That is the official Google icon for a ZIP file. If you're unhappy with it, tough sh\*\*, go complain to Google's design department that you, as some random guy with a default profile pic, know better than those design professionals.
