### ISSUE TITLE
Home Security icon

### ISSUE THREAD

**Issue by arsaboo** [Templarian/MaterialDesign#1290]
Something like 
![image](https://cloud.githubusercontent.com/assets/18319734/16045615/399a74fe-3217-11e6-8adb-dc28f1ab2890.png) 
or 
![image](https://cloud.githubusercontent.com/assets/18319734/16045625/4382e08c-3217-11e6-82e5-ef138cbe3ca5.png)
or
![image](https://cloud.githubusercontent.com/assets/18319734/16045651/635b5c72-3217-11e6-8d98-bc9a76901cc1.png)

**Comment by RamakrishnaUX** [comment]
[homesecurity.pdf](https://github.com/Templarian/MaterialDesign/files/356037/homesecurity.pdf)

**Comment by RamakrishnaUX** [comment]
![homesecurity](https://cloud.githubusercontent.com/assets/8967337/16713899/7825064c-46d2-11e6-9748-056cb36dae82.png)
[homesecurity.zip](https://github.com/Templarian/MaterialDesign/files/356039/homesecurity.zip)

**Comment by arsaboo** [comment]
This looks good....

**Comment by Templarian** [comment]
[![security-home](https://materialdesignicons.com/icon/security-home)](https://materialdesignicons.com/icon/security-home)
