### ISSUE TITLE
History 'skip-next-circle'

### ISSUE THREAD

**Issue by neelayak** [Templarian/MaterialDesign#1291]
Reason:

[View History Item](http://materialdesignicons.com/history/DCBCA8F6-86EA-4C28-8F9F-8FF0BE91767A)

**Comment by Templarian** [comment]
@neelayak What appears to be wrong with the `skip-next-circle` icon?

**Comment by neelayak** [comment]
sorry sir i forgot about this issue

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. Although the last comment does imply that, whatever the issue was, it's no longer an issue.
