### ISSUE TITLE
Business-related icons: invoice, customers, costs, price, products, services, boss, contract, brand, debtor

### ISSUE THREAD

**Issue by javadKarbasian** [Templarian/MaterialDesign#1293]
plz make icon for biz entities like invoice,customers,costs,price,products,services,boss,contract,brand,debtor,

**Comment by JamesCoyle** [comment]
Do you have examples? We already have icons that would work for many of those.

**Comment by CoDEmanX** [comment]
Duplicate requests:
Invoice: #1010 
Contract: #1040 
Services: #1103 ?
Products: #991, #1186

**Comment by javadKarbasian** [comment]
and also tax.

**Comment by javadKarbasian** [comment]
you are right, there are some.
i could not find any for list below;
debtor 
tax

**Comment by PeterShaggyNoble** [comment]
`percent` or `margin` can be used to represent tax.

As no example of a `debtors` icon was provided, I'm going to close this one out. If you still have need of one, @javadKarbasian, please open a new issue and be sure to provide an example.
