### ISSUE TITLE
Patreon, HitBox

### ISSUE THREAD

**Issue by CrawfordK** [Templarian/MaterialDesign#1294]
Logos for Patreon and HitBox.

**Comment by GreenTurtwig** [comment]
Here is Patreon: 
[patreon.zip](https://github.com/Templarian/MaterialDesign/files/417085/patreon.zip)
Also there is currently an issue open for Patreon: https://github.com/Templarian/MaterialDesign/issues/609

**Comment by JamesCoyle** [comment]
Hitbox logo from their android app: 
![image](https://cloud.githubusercontent.com/assets/10384436/17650136/87697de6-623d-11e6-9d1a-39347f2083fb.png)

Seems like it would be simple enough to recreate. Nice to see a few active icon creators on here getting through some of the requests.

**Comment by GreenTurtwig** [comment]
Well, I've used MDI so much (and love it :-D) that I though it wouldn't be too hard to contribute some icons. Having fun with it so far. :-)  
I'll work on the Hitbox icon next.

**Comment by GreenTurtwig** [comment]
HitBox :cat2:  
[hitbox.zip](https://github.com/Templarian/MaterialDesign/files/417116/hitbox.zip)

**Comment by CrawfordK** [comment]
They both look awesome! :D

**Comment by GreenTurtwig** [comment]
Thanks. :heart: :-)

**Comment by Templarian** [comment]
[![patreon](https://materialdesignicons.com/icon/patreon)](https://materialdesignicons.com/icon/patreon)

Closing as hitbox isn't a thing anymore right?
