### ISSUE TITLE
Check box icon for 'waiting' todo task, eg checkbox with hourglass inside

### ISSUE THREAD

**Issue by ThomasH99** [Templarian/MaterialDesign#1295]
Todo tasks can have more states that just done (checked check box) and not-done (clear check box). 

Specifically, the task is started but in waiting state, e.g. waiting for something to happen like somebody to return a call, get an answer to an email etc. 

One way to visualize this could be a check box with an hourglass inside the box.

**Comment by CoDEmanX** [comment]
An hourglass will most certainly not fit inside the rectangle while staying material design compliant.

We could try to create a dashed outline version however.

**Comment by ThomasH99** [comment]
I'm not an expert (which I guess is why I have to ask for an icon instead of trying to make it myself ;-) but how about a simple outline something like this?
![image](https://cloud.githubusercontent.com/assets/16265939/16390159/b11137ea-3ca1-11e6-9a9d-6d5f33f48b41.png)

**Comment by PeterShaggyNoble** [comment]
This seems very specific and, as @CoDEmanX pointed out, pretty difficult to pull off. I'd suggest using one of the `hourglass` or `clock` icons on their own.
