### ISSUE TITLE
Check box icon for 'ongoing’ todo task, eg box with partly filled watch face inside (like ‘timelapse’ icon)

### ISSUE THREAD

**Issue by ThomasH99** [Templarian/MaterialDesign#1296]
Todo tasks can have more states that just done (checked check box) and not-done (clear check box). 

Specifically, the task has been started but is not finished yet. In a todo tool, such tasks should typically be highlighted since it is good practice to finish them before starting working on other tasks. 

One way to visualize this could be a check box with a partly filled watch face inside similar to the ‘timelapse’ icon.

**Comment by CoDEmanX** [comment]
We can try that. It would be a rectangular clock though...

Alternatively, one could place 3 dots inside the checkbox outline, or place a filled rectangle inside (indeterminate state, which is used in Windows for instance)

**Comment by ThomasH99** [comment]
Thanks for your answer. I think a clock inside a box would easily be confused with the many other clock symbols in material design. 
Three dots will also be seen by some as lack of action (like "not sure what to do next...").

Alternatively how about using a (double) circular arrow inside the check box, that seems to be a more universal symbol for something that is ongoing (google "icon ongoing"), a bit like this, but only in the square check box: 
![image](https://cloud.githubusercontent.com/assets/16265939/16389918/80c5912c-3ca0-11e6-964a-2bd324e65948.png)

**Comment by JamesCoyle** [comment]
I'm gonna close this out as there have been no contributions of a viable icon. I feel that `checkbox-indeterminate` would be a good option that would match the other checkbox styles and use of text or color could further indicate an in progress status. I don't really feel an icon can easily convey this on its own.
