### ISSUE TITLE
Check box icon for 'cancelled' todo task, eg box with ‘x’ inside

### ISSUE THREAD

**Issue by ThomasH99** [Templarian/MaterialDesign#1297]
Todo tasks can have more states that just done (checked check box) and not-done (clear check box). 

Specifically, a created task has been cancelled since it is no longer relevant, but should be kept for historical reasons.

One way to visualize this could be a check box with a cross or ‘x’ inside the box (similar to the ‘cancel’ symbol).

**Comment by CoDEmanX** [comment]
Considering the space restrictions, I doubt this will fit in our icon grid. It also adds visual noise. I would rather use either of the checkbox icons and give it a different color - e.g. dark gray if it can be used, and light gray if it was cancelled and can not be used anymore.

**Comment by ThomasH99** [comment]
Thanks for your answer. However, I don't understand why an x wouldn't fit inside when a 'v' does. Also, when you google "icon cancelled", it seems the common symbol for cancelled is an x, like here: 
![image](https://cloud.githubusercontent.com/assets/16265939/16390347/997b9d7c-3ca2-11e6-9f22-9065e4cac319.png).

A gray check box might work, but using color for this one task state might easily be missed since visually less explicit than the other states. 
Alternatively, the existing material check box with a '-' ("Indeterminate check box") might be used - only it contradicts the designated use...

**Comment by PeterShaggyNoble** [comment]
[![image](https://user-images.githubusercontent.com/15157491/36907874-a07900f2-1e31-11e8-85ad-a47631de12ba.png)](https://materialdesignicons.com/icon/close-box-outline)
