### ISSUE TITLE
UpLabs Icon

### ISSUE THREAD

**Issue by KeyonLulu** [Templarian/MaterialDesign#1298]
UpLabs icon, maybe only the "UP"
![](http://www.uplabs.com/assets/logo/uplabs/dark-65f6ba09a043224c13450f2f6ad6a27a26d22ba00e4f30d1f5f54000a4ed062d.png)

**Comment by tomiscat** [comment]
wow

**Comment by KeyonLulu** [comment]
@tomiscat What? You think nobody need it?

**Comment by tomiscat** [comment]
@KeyonLulu No,I don`t think that.I'm just saying.

**Comment by KeyonLulu** [comment]
@tomiscat Oh, ok. I misunderstood.

**Comment by JamesCoyle** [comment]
We don't generally accept requests for brand icons as they are often too specific so there is no guarantee this will be added.

**Comment by KeyonLulu** [comment]
@JamesCoyle Mh, I didn't know.

**Comment by Templarian** [comment]
Closing this issue out. Way too niche of an icon. Not that I don't love Matt's work with the community.
