### ISSUE TITLE
Icons with Single Letter A-Z and a-z

### ISSUE THREAD

**Issue by lalitrane234** [Templarian/MaterialDesign#1299]
New Icon Request - 
I need single letter as Icon (A to Z and a to z)

**Comment by Templarian** [comment]
I've rejected this a couple times, but there is plans to make another font specifically for A-Z a-z 0-9 and special characters. I'll use this issue to track it.

**Comment by abhiphirke** [comment]
I have requirement for such icons. Is this font added now? How to use them?

**Comment by Templarian** [comment]
@abhiphirke Still not added, we're a little busy on the 2.0 release at the moment. It's definitely something we want to include once there is more time.

**Comment by abhiphirke** [comment]
I am kind of an urgent need of such icons. I could also use one of the workarounds, but don't really want to that only for three letters P, A, R icons that I need. Is there a possibility that this will come up in near future?

**Comment by PeterShaggyNoble** [comment]
You could use [Roboto](https://fonts.google.com/specimen/Roboto) and/or [Noto](https://fonts.google.com/specimen/Noto+Sans) in the meantime; they're the fonts used in the [Material Design spec](https://material.io/guidelines/style/typography.html).

**Comment by MrGrigri** [comment]
In the meantime, I've got an Illustrator file that anyone can use that has the alphabet.


[template-alphabet.zip](https://github.com/Templarian/MaterialDesign/files/905976/template-alphabet.zip)

**Comment by Templarian** [comment]
We could start working on this shortly. I have the backend build system already configured to handle this, we just need to start making the glyphs at 24x24.

- Regular
- Box
- Outline

**Comment by MrGrigri** [comment]
This file might be of some use. It's all of the capital letters A-Z. Granted it's not Roboto and they follow the MD guidelines for icons. 

[template-alphabet.zip](https://github.com/Templarian/MaterialDesign/files/906094/template-alphabet.zip)

![alphabet 4x](https://cloud.githubusercontent.com/assets/4528551/24808139/f11a7648-1b77-11e7-808c-528b74b95144.png)

**Comment by JapanYoshi** [comment]
I whipped this up. Blue letters are alternates

1/2 intended size:
![material-tinyfont](https://cloud.githubusercontent.com/assets/8707990/25088972/8c49f694-23b5-11e7-890f-5a77baf46843.png)
Intended size:
![material-tinyfont2](https://cloud.githubusercontent.com/assets/8707990/25088973/8c5fe77e-23b5-11e7-8a48-0667c0ab868a.png)
10x intended size:
![material-tinyfont20](https://cloud.githubusercontent.com/assets/8707990/25088974/8c604908-23b5-11e7-9936-f49c1a1c4922.png)

**Comment by Templarian** [comment]
@JapanYoshi These look really nice. Good use of diagonals to keep them readable.

So the issue I run into right now is that the entire build system is configured for single width glyphs. Great for those that need these as `24x24`, but not so much if someone wants them as a font.

What I can do is import them each as a `24x24` then we can clean up the build process to support more "font" generation later on.

**Comment by JapanYoshi** [comment]
Or I could compile them into a .ttf or .otf

**Comment by Templarian** [comment]
We'll probably want to release them as SVG and a font. The new site we can generate a page to preview and download them.

https://github.com/sapegin/grunt-webfont I use this, but there might be other solutions by now, but not sure what settings it has for fonts (I've only used it for glyphs).

**Comment by fmeneuhe** [comment]
Finally, we will see an A-Z letters included  in MaterialDesign?

**Comment by Templarian** [comment]
@fmeneuhe It could be a little while and most likely it will be released as a standalone webfont. Definitely still something I want to include, but lower on the list.

**Comment by JamesCoyle** [comment]
What's the use case for these? Everything I can think of Google would just use Roboto for.

**Comment by CoDEmanX** [comment]
@JapanYoshi Can you share the SVG(s) of your font?

**Comment by Templarian** [comment]
@JapanYoshi When you get a second can you include the SVG's I'm going to try and get the webfont builder wired up to handle kerning data.

**Comment by Mancerrss** [comment]
A seperated font file is appreciated, tho it would be nice if these would be available on our repo or website tool too. What's the harm on including this to our 2000+ icons already

As I've said before we might need these for reference or quickly making another Material icons again, with the need for these letters. Its actually hard to define or guess how well construct it on the grid, since not all letters yet on the Alphabet is used in official Material design Iconography repo, what's the proper width, what corners should be rounded, how to pixel compensate it, how to construct it on different sizes and such. 

Yes the recommended is Roboto but for me thats the only need for that, but I guess these would be helpful for others too for more symbolic representation of an Alphabet or numeric icons. 

Ligatures or such other complex don't features aren't needed bc this aesthetic is almost mono like stencil type lettering. It's just blocky with some rounded corners on some. 

We just need someone to standardized this as an individual icons based on what we know or things we settled with

**Comment by GreenTurtwig** [comment]
@Mancerrss I'm working on that right now, your issue reminded me I needed to finish off the job.
Got letters and numbers in both 5x6 and 6x10 which match as close to Google's style as possible.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/45323275-8d6d0000-b542-11e8-9a05-4972686681e4.png)
[characters.zip](https://github.com/Templarian/MaterialDesign/files/2368317/characters.zip)

**Comment by Templarian** [comment]
Update on this we've started adding all of these. You can see the progress on the history page.

https://dev.materialdesignicons.com/history It does add a significant weight for webfont users, but we've decided webfont users will need to transition eventually anyway.

**Comment by GreenTurtwig** [comment]
[lower-case.zip](https://github.com/Templarian/MaterialDesign/files/2393962/lower-case.zip)

**Comment by MrGrigri** [comment]
I still don't think that lowercase should be added. They are difficult to recognize and the inconsistencies with throw it off.

**Comment by Templarian** [comment]
Closing this one out as we agreed lowercase is a bit much. We'll work on a full font in the future.
