### ISSUE TITLE
server-*

### ISSUE THREAD

**Issue by The0x539** [Templarian/MaterialDesign#130]
server-shield
server-plus
server-minus
server-network-shield
server-network-plus
server-network-minus

**Comment by Templarian** [comment]
I don't know what that means.

**Comment by The0x539** [comment]
Tight for room, even if some of the base icon gets cut off?

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/server-security

**Comment by The0x539** [comment]
http://materialdesignicons.com/icon/thumb-up

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/security-network
http://materialdesignicons.com/icon/plus-network
http://materialdesignicons.com/icon/minus-network
http://materialdesignicons.com/icon/close-network

**Comment by The0x539** [comment]
Noooot exactly what I meant, but sure, moar icons .

**Comment by Templarian** [comment]
It's hard to add that much detail to these small 24x24 icons :stuck_out_tongue_closed_eyes: 

I'll try.

**Comment by The0x539** [comment]
You added a shield to server, adding to server-network shouldn't be THAT much harder,  should it?

**Comment by Templarian** [comment]
I made it, but it looks like way too much for a single icon.

![server-security](https://cloud.githubusercontent.com/assets/338885/5991186/f9cbfddc-a9a2-11e4-97aa-76ce9c57f97e.png)

**Comment by The0x539** [comment]
Yeah, maaaaaaaybe scrap the server-network variants. Still the other couple, though.

**Comment by The0x539** [comment]
What about server-plus and server-minus?

**Comment by Templarian** [comment]
Adding a plus and minus next to every icon does not help, but I'll add those two.

**Comment by The0x539** [comment]
There's a use case in mind.

**Comment by Templarian** [comment]
https://www.youtube.com/watch?v=CRUSECQrpkA Watch this while I add them.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/server-plus
http://materialdesignicons.com/icon/server-minus
http://materialdesignicons.com/icon/server-remove
