### ISSUE TITLE
Future Improvements? 

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1300]
I'd like to start out by saying that I'm not expecting things to change overnight: I'm just putting some ideas out there for long term improvements of this project. I'm hoping this will maybe spark a bit of discussion and get some ideas flowing. I'm also happy to help out with these things, I'm not just suggesting work for others to do. :P

**Unicode range changes**
It's really not much of an issue but I was wondering if it would be worth adjusting the unicode values of the icons to make the webfont usable as an actual font. We already have a lot of icons that correspond with unicode icons and could be correctly positioned in the font rather than just placed randomly in the private use range. There are also plenty of unicode characters that aren't in MDI but should probably be included. This would allow the font to be used alongside Roboto as a true material design font solution providing icons for all of the emoji and other characters. 

I would also suggest partitioning the current private use range to group icons by type so users can choose to not include icons they don't need. An obvious candidate for this would be the brand icon group which consists of a lot of icons that many users may not want. This could also be extended in the future by providing a web app to allow specific icon selection that generates the `@font-face` rule with a custom `unicode-range`.

**Site changes**
My main thought is to update the UI in favor of a more material design look that reduces clutter and better organises icons. Currently the performance of the site is really quite awful. It usually takes a good 10-20 seconds to even become responsive and start showing icons and the search is also sluggish and doesn't always work correctly. I plan to put together a working concept or two when I have some time if there is any interest in this.

One thing that has been suggested in the past is the addition of groups of icons. I think this would really help to keep things organised but I understand that heavy grouping also makes things harder to find too. I'd suggest groups were implemented based more on the unicode type as suggested above. That means having groups such as brand icons, emoji, transport icons, arrows, math related icons etc. which split out large groups of 50+ icons to make them easier to find rather than grouping things into smaller groups and having too many headings breaking up the collection like on Google's icon page. This is something which would take a lot of thought but if done right would really help visual searches for icons.

As stated above, allowing users to create their own web font would be a great feature. The way I see it it the user would select which groups of the current webfont they want and generate a custom range so the browser only downloads the characters from the font the user wants. I'm sure this idea could be expanded and fleshed out with some more thought and ideas. 

I would also consider implementing icon requests into the site. This would give more control over what information users provide and could also better show which icons have already been requested. The system could better integrate into an icon database and requests could instantly be assigned unicode values, icon names and aliases and be tagged for contribution. This would allow contributors to see exactly what icons needed doing and add them. Currently there are a few hundred requests that are awaiting fulfillment and it's practically a chore for contributors to find a request they want to work on. This system would also allow for fast turnaround time getting icons usable as soon as they are ready.

**Comment by Templarian** [comment]
Lots of really good ideas. Just loaded the site in 3 seconds in Chrome, but I will say since I use SVG and inject all the icons at once browsers that don't handle SVG well will take a substantial amount of time to render. This can be addressed in a few ways to maximize performance.

Just a head up as you have probably seen my free time during the summer greatly reduces due to a lot of traveling / work / bars / etc. To fix this one thing I would really like to do shortly is get the source code for the site into GitHub (especially the AngularJS portion). This include also documenting all the API calls the server currently has.

Icon requests will always be managed through GitHub (I actually had a system at one point to manage them in the site, but it was all removed since maintaining that codebase got in the way of icons).

**Comment by JamesCoyle** [comment]
The actual site loads under 5 seconds usually in chrome but it's often 10-20 before it actually becomes usable. We definitely need to look at the icon loading and improve it. It actually seems to be working quite well at the moment but it will often be sluggish and annoying to use.

It makes sense that icons be requested on GitHub. I hadn't thought about the maintenance and what happens if something goes wrong with the system. Would still maybe be nice to have a section for icons that have been accepted as suggestions and will be added in the future.
