### ISSUE TITLE
"code" icon

### ISSUE THREAD

**Issue by nicolae-46-2** [Templarian/MaterialDesign#1305]
Need an icon that shows this "< / >"

**Comment by JamesCoyle** [comment]
I'm not sure it fits well in the small grid. We already have suitable options.

[![code-tags](https://materialdesignicons.com/icon/code-tags)](https://materialdesignicons.com/icon/code-tags)
[![code-brackets](https://materialdesignicons.com/icon/code-brackets)](https://materialdesignicons.com/icon/code-brackets)
[![code-braces](https://materialdesignicons.com/icon/code-braces)](https://materialdesignicons.com/icon/code-braces)

**Comment by Templarian** [comment]
[![xml](https://materialdesignicons.com/icon/xml)](https://materialdesignicons.com/icon/xml)

**Comment by JamesCoyle** [comment]
Oh right. Completely forgot about that one. Perhaps `code-tags-closing` alias would be a good idea?

**Comment by nicolae-46-2** [comment]
Thank you for the super fast reply and delivery !


On Tue, Jun 21, 2016 at 1:47 PM, James Coyle <notifications@github.com>
wrote:

> Oh right. Completely forgot about that one. Perhaps code-tags-closing
> alias would be a good idea?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/1305#issuecomment-227566886>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AKr88P9AJ93wHq90CUSql5lXqq0ByLItks5qOE34gaJpZM4I695Z>
> .
>



-- 
Nicolae Carabut
President and CEO 46&2 Inc.
www.fourty6et2.com
(M): +1 (​650) ​942-​9548
