### ISSUE TITLE
Achievement / Ribbon Icon - Google Play Games

### ISSUE THREAD

**Issue by ngage-tx** [Templarian/MaterialDesign#1306]
An achievement icon, like the Google Play Games icon for achievements.

**Comment by Templarian** [comment]
Do you have a screenshot of which icon this is? We have a crown and a few trophy icons in the pack.

**Comment by thunsaker** [comment]
Here's the official achievements icon:
![image](https://cloud.githubusercontent.com/assets/137686/16354764/609b21c0-3a55-11e6-96fb-7de17ea1ba8a.png)

From [Google Play Games Dev Guide](https://developers.google.com/games/services/branding-guidelines#optional-game-feature-icons)

**Comment by ngage-tx** [comment]
@thunsaker has the right one.

**Comment by CoDEmanX** [comment]
Looks much like

[![seal](https://materialdesignicons.com/icon/seal)](https://materialdesignicons.com/icon/seal)

**Comment by Templarian** [comment]
Needs an alias `ribbon`.

**Comment by Templarian** [comment]
Added.
