### ISSUE TITLE
Tire Icon

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#1308]
I'd like to have a material design style tire icon. If anyone is willing to do it I would greatly appreciate it. Thank you!

Icon example: 
![icon-tire-installation](https://cloud.githubusercontent.com/assets/20115084/16315360/41681c82-3982-11e6-8a0b-cf40b2662604.png)

**Comment by JamesCoyle** [comment]
What is the use case for it? That example doesn't work as it is three dimensional. Might be hard to show a tire in the material style.

**Comment by mrwater10** [comment]
I already thought that the three dimensional example might be problematic. Please ignore that example if this is impossible to design when following the md style guide.

The icon is meant to be used in a car service station software context where it would be used to describe all services that are related to tires (e.g. tire installations, flat repairs, rotations, storage, ...)

Btw: I'm currently using Google's "album" icon as a replacement but most people don't get that easily/directly.

**Comment by JamesCoyle** [comment]
Perhaps something with the rim and tire would be more recognisable. One of the icon contributors can probably weigh in more on that.

**Comment by mrwater10** [comment]
I would be perfectly fine with that. Thank you for considering it.

**Comment by JapanYoshi** [comment]
![path4158](https://cloud.githubusercontent.com/assets/8707990/17193410/d8edc022-548d-11e6-92d3-9a151a3fe9f9.png)
![path4159](https://cloud.githubusercontent.com/assets/8707990/17193412/da3f0896-548d-11e6-828d-93b691b7b11c.png)

**Comment by Templarian** [comment]
Not really seeing a tire. Might need to try a few variations.

**Comment by mrwater10** [comment]
That's more a wheel rim than a tire but it is a nice alternative if it is impossible to create a tire using the material style. I like the little version more though (as it has a black circle in the middle).

Thank you very much for your suggestion JapanYoshi.

**Comment by mrwater10** [comment]
@Templarian I'd like to know if you will consider adding @JapanYoshi 's tire icon to the collection. It's not a tire but way more recognizable than Google's Album icon for my intended purpose. Thanks!

**Comment by goyney** [comment]
Removing the Contribution label since no source SVG was provided.

**Comment by PeterShaggyNoble** [comment]
Added the `Alias` tag to remind us to alias this with the proper spelling when it gets added.

**Comment by Leinad4Mind** [comment]
Here is some ideas if that helps:
![image](https://i.imgur.com/NJNp0Ul.png)
![image2](https://i.imgur.com/sfei1U2.png)

**Comment by seanmitchell90** [comment]
Here's some explorations
<img width="664" alt="Tire exploration" src="https://user-images.githubusercontent.com/50327294/57230526-2a067580-6fde-11e9-9bd4-126273147859.png">

**Comment by seanmitchell90** [comment]
Here's some exploration
<img width="661" alt="Tire Exploration" src="https://user-images.githubusercontent.com/50327294/57230651-7356c500-6fde-11e9-8099-c3a545864771.png">

**Comment by goyney** [comment]
1 and 2 are wheels, I have no clue what 4 and 5 are. 3 is probably the closest to a "tire" we can get from this vantage point.

**Comment by seanmitchell90** [comment]
Just a note, the icons you say are more of a wheel icon, wheel is missing from the library as well

**Comment by mattcorner** [comment]
So a potential solution to this wheel vs. tire issue:

I propose that the 'car-tire-alert' icon is released as car-tire without the alert symbol. For anyone using an automotive application, they should be familiar with the cross section of a tyre, and its a symbol that is universally used on dashboards in vehicles worldwide.

**Comment by goyney** [comment]
`car-tire-alert` without the alert wouldn't make sense. The tire is partially deflated in that icon, so we'd have to straighten those lines out. Then it would just be part of a rectangle with notches at the bottom. I believe our best bet it option #3 from above.

**Comment by goyney** [comment]
[![tire](https://materialdesignicons.com/icon/tire)](https://materialdesignicons.com/icon/tire)
