### ISSUE TITLE
auto-pilot icon, for background services

### ISSUE THREAD

**Issue by GiagkiozisL** [Templarian/MaterialDesign#1309]

**Comment by JamesCoyle** [comment]
Can you provide an example of what that would look like?

**Comment by GiagkiozisL** [comment]
i was thinking a combination of a plane and a locker. Or a steering wheel.

**Comment by CoDEmanX** [comment]
Via Google image search:
![image](https://cloud.githubusercontent.com/assets/1309249/16375712/090856f8-3c5d-11e6-9597-ad5c360120e0.png)
![image](https://cloud.githubusercontent.com/assets/1309249/16375717/134a5382-3c5d-11e6-9bfd-1bb0a15b83d1.png)
![image](https://cloud.githubusercontent.com/assets/1309249/16375748/34e5f352-3c5d-11e6-8194-aa817f55d5b7.png)

**Comment by GreenTurtwig** [comment]
[plane-shield.zip](https://github.com/Templarian/MaterialDesign/files/417132/plane-shield.zip) :-)
![puush-linux 2016-08-14 at 06 07 27](https://cloud.githubusercontent.com/assets/15905797/17650637/0af6034e-624a-11e6-97d1-7e6a98867a31.png)
![puush-linux 2016-08-14 at 06 07 49](https://cloud.githubusercontent.com/assets/15905797/17650638/0c6363ca-624a-11e6-9de8-5f53bb53da15.png)

**Comment by Templarian** [comment]
[![plane-shield](https://materialdesignicons.com/icon/plane-shield)](https://materialdesignicons.com/icon/plane-shield)
