### ISSUE TITLE
Questions: Google Upload, and Renaming, etc

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#131]
I am making a file with all of the paths in a text document for automation purposes.
Do you have something like that? It would be very helpful to me but I am currently doing it myself, do worry about making it unless necessary for the website. 

Have you uploaded all of Google's icons yet? (I haven't been keeping track)
If not, will you be putting that you uploaded them in the history?

"1 The icon naming is not finalised, so expect icon names to change."
And if you rename icons, will that go under history as well?

Thanks,
Daniel

**Comment by Templarian** [comment]
All renaming of icons are automatically logged into the history page now. Contributors can't make changes without them showing up there now.

I could write an endpoint in about 1 minute that does that. If you let me know the format you need.

**Comment by Templarian** [comment]
Also, there are roughly 240 icons missing right now from the stock set. I'm slowly adding them.

**Comment by danielhickman** [comment]
Okay if you could write up something that makes a file that has this as an output:

icon-name path
(icon name with the usual dashes and not spaces, a space, and the everything in d="blah blah blah")

![image](https://cloud.githubusercontent.com/assets/5341898/5986631/e46ffb6c-a8b4-11e4-88cb-d89aa0b372a1.png)

**Comment by Templarian** [comment]
The endpoint below supports `{name}`, `{data}`, `{by}`. There is a `&start=` and `&end=` in there also, but your output was basic and does not use it.

http://materialdesignicons.com/api/custom/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B?format=%7Bname%7D+%7Bdata%7D%0D%0A

```text
{name} {data}

```

**Technical Note:** This is the compressed SVG data. It will not work in `grunt-webfont` using the node implementation. For that you need the node safe version.

**Comment by Templarian** [comment]
I'm writing this into the http://materialdesignicons.com/custom with an editor at the moment, should be up shortly.

Just in case you need to modify the output in the future.

**Comment by danielhickman** [comment]
Thanks so much. Appreciate your work.

**Comment by Templarian** [comment]
The form is now line. I've removed the link above as this will solve future issues way quicker without needing url encoding.

**Comment by danielhickman** [comment]
It doesn't look like there is a code for a new line in the form. Maybe you could add a \n for a newline

**Comment by Templarian** [comment]
Just use the enter key on your keyboard? That is how the .CSV example works. :smile:

**Comment by danielhickman** [comment]
Nah I put two enter lines after the default loop. I wanted to separate them
by line but they stick together one one line with not even a space.

**Comment by Templarian** [comment]
That was a bug. Good find. Fixed.
