### ISSUE TITLE
Smartwatch vibrating, making a noise icon

### ISSUE THREAD

**Issue by eddieberklee** [Templarian/MaterialDesign#1311]

**Comment by Templarian** [comment]
Basically https://materialdesignicons.com/icon/vibrate with the watch icon I suppose.

**Comment by GreenTurtwig** [comment]
Done. :smile_cat:  
![puush-linux 2016-08-07 at 12 23 27](https://cloud.githubusercontent.com/assets/15905797/17462103/eb615016-5c99-11e6-83f1-38c5b0558dd6.png)
[watch-vibrate.zip](https://github.com/Templarian/MaterialDesign/files/405465/watch-vibrate.zip)

**Comment by Templarian** [comment]
[![watch-vibrate](https://materialdesignicons.com/icon/watch-vibrate)](https://materialdesignicons.com/icon/watch-vibrate)

**Comment by eddieberklee** [comment]
You guyz are dope
