### ISSUE TITLE
Wooden Tower Icon

### ISSUE THREAD

**Issue by thunsaker** [Templarian/MaterialDesign#1312]
In putting together a worksheet for the [Pioneering Merit Badge](http://www.meritbadge.org/wiki/index.php/Pioneering) I created a wooden tower. It doesn't necessarily need to be wooden, it could just be a "tower".

![wooden-tower](https://cloud.githubusercontent.com/assets/137686/16347770/57775f8e-3a03-11e6-9323-57870fc150d0.png)

**Comment by thunsaker** [comment]
![wooden-tower-24](https://cloud.githubusercontent.com/assets/137686/16354702/f894acde-3a51-11e6-9b9f-2b1daadb04ea.png)
24px

Source: [wooden-tower.zip](https://github.com/Templarian/MaterialDesign/files/332898/wooden-tower.zip)

**Comment by CoDEmanX** [comment]
I'm not very happy about the tiny triangles enclosed by the strokes. Could you try to make the diagonal lines more regular?

**Comment by Templarian** [comment]
Yea, looks like a ladder when scaled at 24x24. To give it a more tower style one could put a sort of forest fire tower style design.

**Comment by thunsaker** [comment]
Attempted a [fire tower](https://duckduckgo.com/?q=fire+tower&kp=1&iar=images&iax=1&ia=images) based on the previous icon...it turned out looking like one of those lifeguard huts you see on beaches. Maybe it needs a window or an angled roof, thoughts?

![fire-tower-128](https://cloud.githubusercontent.com/assets/137686/16601741/a0ed07ae-42c3-11e6-8047-d9583087493d.png)
128px

![fire-tower-24](https://cloud.githubusercontent.com/assets/137686/16601744/a5114688-42c3-11e6-9478-ee3d7704c285.png)
24px

Source: [fire-tower.zip](https://github.com/Templarian/MaterialDesign/files/348752/fire-tower.zip)

**Comment by Templarian** [comment]
Yea, looking at it with fresh eyes I'm not seeing a tower when it is at 24x24 size. Might need to bring the support beams on the left and right in a pixel.

This may take a few variations to get right due to the perspective. Almost looks like diagonal train tracks, so the top part may need to have a bit more detail like you suggested.

**Comment by JamesCoyle** [comment]
I'd suggest a single cross between the legs rather than the double one in the earlier posts, and to angle the legs inwards a bit as Austin suggested. Then maybe try a couple of variations on the sloped roof idea though I'm concerned it may make it less generic and less reusable. Such an icon could be used as a hunting stand, lifeguard hut, firewatch house, etc. rather than being tied to one specific use case.

**Comment by thunsaker** [comment]
Alright, here are some more options:

### **A (Single Cross)**
![fire-tower-cross-128](https://cloud.githubusercontent.com/assets/137686/16626311/2818a1ae-435d-11e6-8a41-779ed05fe9ab.png)
128px

![fire-tower-cross-24](https://cloud.githubusercontent.com/assets/137686/16626310/2818641e-435d-11e6-897e-ce88f87a31de.png)
24px


### **B (Slanted Roof)**
![fire-tower-cross-angled-128](https://cloud.githubusercontent.com/assets/137686/16626568/65bf784c-435e-11e6-9ab6-4b6f676ebc55.png)
128px

![fire-tower-cross-angled-24](https://cloud.githubusercontent.com/assets/137686/16626313/281aece8-435d-11e6-88d5-38f4d3e44410.png)
24px


### **C (Angled Roof)**
![fire-tower-cross-roof-128](https://cloud.githubusercontent.com/assets/137686/16626595/7a2b46b2-435e-11e6-9a81-c56d1fe9dae2.png)
128px

![fire-tower-cross-roof-24](https://cloud.githubusercontent.com/assets/137686/16626314/281c5c5e-435d-11e6-927d-82a9ea600503.png)
24px

**Comment by Templarian** [comment]
That last one is awesome! But the second one is perfect also.

Maybe... `tower-fire` / `tower-beach`?

**Comment by Templarian** [comment]
[![tower-fire](https://materialdesignicons.com/icon/tower-fire)](https://materialdesignicons.com/icon/tower-fire) [![tower-beach](https://materialdesignicons.com/icon/tower-beach)](https://materialdesignicons.com/icon/tower-beach)
