### ISSUE TITLE
Medical Bag/First Aid Icon

### ISSUE THREAD

**Issue by thunsaker** [Templarian/MaterialDesign#1313]
This icon could be used to imply First Aid (kit) or simply a medical bag.

![medical-bag](https://cloud.githubusercontent.com/assets/137686/16347937/5b936788-3a04-11e6-91e3-a4f92e802362.png)
It looks really good in red. :100: 
![medical-bag-red](https://cloud.githubusercontent.com/assets/137686/16347956/8449c848-3a04-11e6-896e-392b6932fb89.png)

**Comment by thunsaker** [comment]
![medical-bag-24](https://cloud.githubusercontent.com/assets/137686/16354695/c4a46a5e-3a51-11e6-8814-6a3a5a16b2e3.png)
24px

Source: [medical-bag.zip](https://github.com/Templarian/MaterialDesign/files/332897/medical-bag.zip)

**Comment by JamesCoyle** [comment]
Would maybe make more sense to base it on the `shopping` icon to keep things consistent?

**Comment by thunsaker** [comment]
I used the `briefcase` icon as my base, then angled the sides to give it the look of a Dr's bag/tote. If we want to call this a **First Aid Kit** instead, it could work with either icon as a base. I'll get them both together for review.

**Comment by CoDEmanX** [comment]
BTW: we already have `pharmacy`:

[![pharmacy](https://materialdesignicons.com/icon/pharmacy)](https://materialdesignicons.com/icon/pharmacy)

**Comment by Templarian** [comment]
Yea, I think calling it `first-aid-kit` should be fine. Also alias it as `medical-bag`.

**Comment by skolarianer** [comment]
I would make the cross more bold. It looks more like a 'plus' than a cross.
See: https://commons.wikimedia.org/wiki/File:Flag_of_the_Red_Cross.svg

**Comment by Templarian** [comment]
@skolarianer We have to stay in the Material Design guidelines which enforces `2dp` width wherever possible for consistency. This icon will be included as it is currently designed, just need to get some free time.

**Comment by skolarianer** [comment]
> 2dp width wherever possible

@Templarian What about shortening the cross a bit while preserving the width of 2dp...

24px
![medical-bag](https://cloud.githubusercontent.com/assets/6286711/16563330/af7a88ea-4201-11e6-8c92-c2ea0fbdee55.png)

**Comment by JamesCoyle** [comment]
That looks good to me. Could the angle of the sides be optimised a bit to better align the pixels to the grid? Those lines don't look straight on my monitor.

**Comment by skolarianer** [comment]
BTW: Just checked the dimensions of the cross from `pharmacy`. It is also 8dp x 8dp.

**Comment by Simran-B** [comment]
![x](http://cloud.githubusercontent.com/assets/6286711/16563330/af7a88ea-4201-11e6-8c92-c2ea0fbdee55.png) looks a bit like "add weight" / "make heavier".

**Comment by Templarian** [comment]
@Simran-B Agreed using the smaller plus makes it look more like [weight](https://materialdesignicons.com/icon/weight)-plus. I think the first version is still the best to add.

**Comment by skolarianer** [comment]
But still needs some aligning. So...

Before:
![before](https://cloud.githubusercontent.com/assets/6286711/16565651/0f50eefa-420f-11e6-86e7-6abb1e08766b.png)

After:
![after](https://cloud.githubusercontent.com/assets/6286711/16565656/1ac2df14-420f-11e6-9a83-3872918f41db.png)

24px
![medical-bag_aligned_to _grid_24px](https://cloud.githubusercontent.com/assets/6286711/16565662/28d1bf3a-420f-11e6-9797-f4e6cd99352e.png)

48px
![medical-bag_aligned_to _grid_48px](https://cloud.githubusercontent.com/assets/6286711/16565676/31b7e700-420f-11e6-89e6-8cfc4ff45885.png)

ZIP: 
[medical-bag_aligned_to_grid.zip](https://github.com/Templarian/MaterialDesign/files/346573/medical-bag_aligned_to_grid.zip)

This version uses the smaller cross. Read the comment from @Simran-B too late.

**Comment by Templarian** [comment]
[![medical-bag](https://materialdesignicons.com/icon/medical-bag)](https://materialdesignicons.com/icon/medical-bag)

Aliased as `first-aid-kit`. I think medical bag is a little more descriptive.

By the way @skolarianer let me know when you hit 5 icons and I'll add a contributor account and assign this one over. I'm bad at keeping track generally.

**Comment by skolarianer** [comment]
@Templarian I’ll let you know, but in this case the credit is due to @thunsaker

**Comment by thunsaker** [comment]
@skolarianer thank you for the help refining the icon.

@templarian this puts me at 5 since we did 2 for #1312 (Tower Icon)!
