### ISSUE TITLE
Oar Icon (for a Boat, Canoe, Kayak, etc)

### ISSUE THREAD

**Issue by thunsaker** [Templarian/MaterialDesign#1314]
:notes: Row, row, row your boat, gently down the stream. :notes: 

![oar](https://cloud.githubusercontent.com/assets/137686/16347992/c3eb7b86-3a04-11e6-9d0e-f6edf29949f0.png)

**Comment by Templarian** [comment]
Do you have the SVG/AI file for this? You can attach .zip files to issues.

Also thanks for the preview image. Can you post 24x24 size also this allows for us to quickly see if it passes visually at 1x scale.

**Comment by thunsaker** [comment]
Sure thing, I have SVGs that were created with Inkscape. I'll get the preview and source files uploaded later today for all of my icons.

**Comment by thunsaker** [comment]
![oar-24](https://cloud.githubusercontent.com/assets/137686/16354643/76ba612e-3a4f-11e6-9bbd-79ea18587222.png)
24px

Looks like the oar handle is lost at that size. I'm open to feedback and making modifications.

Source: [oar.zip](https://github.com/Templarian/MaterialDesign/files/332892/oar.zip)

**Comment by JamesCoyle** [comment]
I'm not a fan of the bit on the end (bottom-left). It's a bit too much detail. Other than that it looks ok to me.

**Comment by CoDEmanX** [comment]
Maybe rotate it 180°, because that's the orientation you use it in?

**Comment by thunsaker** [comment]
Here's an updated version minus the handle and rotated.

![oar-no-handle-24](https://cloud.githubusercontent.com/assets/137686/16595642/0cfe4076-42a5-11e6-8298-43ab8e1dac10.png)
24px

![oar-no-handle-48](https://cloud.githubusercontent.com/assets/137686/16595650/1385c414-42a5-11e6-815d-22a9372a8a34.png)
48px

![oar-128](https://cloud.githubusercontent.com/assets/137686/16595702/6bb24860-42a5-11e6-860d-78a9839e1516.png)
128px

svg: [oar-no-handle.zip](https://github.com/Templarian/MaterialDesign/files/348390/oar-no-handle.zip)

**Comment by Templarian** [comment]
[![oar](https://materialdesignicons.com/icon/oar)](https://materialdesignicons.com/icon/oar)

Let me know when you're at 5 icons and I'll add a contributor account.

**Comment by thunsaker** [comment]
@templarian duly noted.
