### ISSUE TITLE
Bow Tie Icon

### ISSUE THREAD

**Issue by thunsaker** [Templarian/MaterialDesign#1315]
I was having a hard time deciding on rounded, pointy, or square bow tie, so I went with a combination of all three. This seemed to be the best version, but I'm up for changes.

![bow-tie](https://cloud.githubusercontent.com/assets/137686/16348091/523d08c8-3a05-11e6-8060-5e2a5351a41e.png)

![bowties-are-cool](https://cloud.githubusercontent.com/assets/137686/16348125/7f4f1f72-3a05-11e6-9a70-05970641d738.gif)

**Comment by thunsaker** [comment]
![bow-tie-24](https://cloud.githubusercontent.com/assets/137686/16354676/0aa92752-3a51-11e6-8274-caeb4faa9a65.png)
24px

Source: [bow-tie.zip](https://github.com/Templarian/MaterialDesign/files/332893/bow-tie.zip)

**Comment by CoDEmanX** [comment]
It doesn't look very material to me. Can you try to simplify the shape and increase the margin between elements?

**Comment by thunsaker** [comment]
Another attempt, simplified, spaced and aligned to the grid.

![bow-tie-simplified-128](https://cloud.githubusercontent.com/assets/137686/16597712/353d1bca-42af-11e6-9f87-fb3a4099ca27.png)
128px

![bow-tie-simplified-24](https://cloud.githubusercontent.com/assets/137686/16597715/39610b12-42af-11e6-8194-ee75c1691a20.png)
24px

svg: [bow-tie-simplified.zip](https://github.com/Templarian/MaterialDesign/files/348516/bow-tie-simplified.zip)

**Comment by JamesCoyle** [comment]
Thats my favorite so far.

**Comment by Templarian** [comment]
[![bow-tie](https://materialdesignicons.com/icon/bow-tie)](https://materialdesignicons.com/icon/bow-tie)

@thunsaker Let me know when you hit 5 icons and you'll be a contributor. :smile:

**Comment by thunsaker** [comment]
@Templarian Cool, cool. Will do, and happy to help!
