### ISSUE TITLE
Sports Icons (non American Football related)

### ISSUE THREAD

**Issue by pedroguedesamaral** [Templarian/MaterialDesign#1316]
Icon request

**Comment by Templarian** [comment]
@pedroguedesamaral We have a few like Australian football and a soccer ball. Are there more sports called football?

**Comment by pedroguedesamaral** [comment]
@Templarian specifically i was looking for a basketball =)

**Comment by Templarian** [comment]
:laughing:

(but a duplicate of #1057)
