### ISSUE TITLE
Create Select/Deselect All checkboxes icons

### ISSUE THREAD

**Issue by c-miller** [Templarian/MaterialDesign#132]
Create two new icons to represent Select All and Deselect All checkboxes.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/checkbox-multiple-blank
http://materialdesignicons.com/icon/checkbox-multiple-marked
http://materialdesignicons.com/icon/checkbox-multiple-blank-outline
http://materialdesignicons.com/icon/checkbox-multiple-marked-outline
