### ISSUE TITLE
Waiting queue

### ISSUE THREAD

**Issue by RueDeRennes** [Templarian/MaterialDesign#1320]
Whats the best way to visualize a Queue? I think this Icon is missing.

**Comment by Templarian** [comment]
The [playlist-check](https://materialdesignicons.com/icon/playlist-check) icon could work for that. Maybe one of the sort icons also.

The closest issue to this has a more literal senses of `first-in-first-out` idea of inventory... #1161

**Comment by CoDEmanX** [comment]
first-in-last-out could be adopted from the stackoverflow logo

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @RueDeRennes, if none of the suggested icons suit your needs, let us know (and maybe come up with an example of what you *are* looking for) and we'll revisit this issue.
