### ISSUE TITLE
need an icon for VIP

### ISSUE THREAD

**Issue by boybeak** [Templarian/MaterialDesign#1321]

**Comment by JamesCoyle** [comment]
What would you suggest such an icon look like?

These would probably be suitable:
[![crown](https://materialdesignicons.com/icon/crown)](https://materialdesignicons.com/icon/crown)[![diamond](https://materialdesignicons.com/icon/diamond)](https://materialdesignicons.com/icon/diamond)

**Comment by boybeak** [comment]
@JamesCoyle But I need one like this [https://materialdesignicons.com/icon/new-box](url)

**Comment by Templarian** [comment]
I'm going to mark this as rejected. To ensure the icons are as widely international as possible we're trying very carefully to not include any icons with text unless absolutely necessary.

`new-box` was added since it was stock Google. Thinking back it probably shouldn't have been included either.
