### ISSUE TITLE
Suggestion: Car-Types (Pool-Car, Rental Cars etc.)

### ISSUE THREAD

**Issue by migingreen** [Templarian/MaterialDesign#1322]
Hi there

First I want to thank you for your effort!

I can see a lot of different topics are already covered with icons, but what I'm missing (besides a tire - #1308) are car-types as symbols.
They should all be based on the standard 'car' symbol and indicate different types with the addition of certain elements.

Example Screenshot:
![car_icon_example](https://cloud.githubusercontent.com/assets/17497583/16416921/7dbea8e8-3d44-11e6-84a4-6345c70f3763.png)

My first attempt at combining two svgs for a pool-car:
(just rename .txt to .svg)
[pool_car.txt](https://github.com/Templarian/MaterialDesign/files/337106/pool_car.txt)

**Comment by JamesCoyle** [comment]
Can you expand on this with use cases for each icon?

**Comment by migingreen** [comment]
- [ ] Car fuel type Icons (Electric/Gas)

1. Car-Sharing Apps can use both icons for filter options (cars by fuel type)
2. Indicates car fuel type in lists & tooltips of fleet business systems (e.g. ERP & CMS)

- [ ] Car classification Icons - [Wikipedia: Car classification](https://en.wikipedia.org/wiki/Car_classification)

1. Users can filter cars by types in order to specify their desired model (e.g. Economy / Saloons / Off-roaders) on car selling platforms

- [ ] Car owning type Icons (Self Owned / Open-End Leasing / Closed-End Leasing)

1. Car fleets can contain a mixture of all types and needs to be filtered by each owning type in order to calculate certain costs of a fleet

- [ ] Car fleet type Icons ([Company Car](https://en.wikipedia.org/wiki/Take-home_vehicle) / [Pool Car](https://en.wikipedia.org/wiki/Fleet_vehicle))

1. Companies often own both types of cars. Company cars for the upper management and pool cars for service-workers (e.g. Fed-Ex Delivery Cars)


Ps: I'll try to add more concrete examples for each type if necessary but I hope you can see all the use cases :)

**Comment by PeterShaggyNoble** [comment]
1. Within the context of a car-related app, the likes of `ev-station`, `flash`, `fuel` and `gas-station` should be easily understood.
2. We've recently added a variety of different `car-*` icons. If there are any you feel are missing, please open a new issue for each one.
3 & 4. I think these are going toe be far too niche to include but `account`, `account-multiple` and/or `account-group` may work for differentiating between self-owned and "pool" cars.

**Comment by GreenTurtwig** [comment]
Also https://github.com/Templarian/MaterialDesign/issues/2476

**Comment by PeterShaggyNoble** [comment]
... And maybe #2662
