### ISSUE TITLE
Suggestion: Piano

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#1324]
I find it quite weird that there isn't an icon for a piano or a piano keyboard.

**Comment by RamakrishnaUX** [comment]
![piano](https://cloud.githubusercontent.com/assets/8967337/16716384/d0ba807a-4718-11e6-95a7-0e0d68bc8bfd.png)
[piano.zip](https://github.com/Templarian/MaterialDesign/files/356221/piano.zip)

**Comment by Templarian** [comment]
Looks nice!

Might look a bit like a comb, but in context I think everyone will recognize it. Need to work on getting more instruments in.

**Comment by Templarian** [comment]
@RamakrishnaUX After some thought and comparing it to other icons it may look too much like a comb. It's modified to better fit the Material Design guidelines.

[![piano](https://materialdesignicons.com/icon/piano)](https://materialdesignicons.com/icon/piano)

**Comment by JapanYoshi** [comment]
I think the black keys shouldn't stick out at the top. It looks really weird to me.

**Comment by Templarian** [comment]
Fixed. (image above updated cache to show latest).
