### ISSUE TITLE
Unshare

### ISSUE THREAD

**Issue by jandrei** [Templarian/MaterialDesign#1325]

**Comment by Templarian** [comment]
Do you have an example of what this would look like?

**Comment by Ekidoxx** [comment]
What about simply strikethrough [share](https://materialdesignicons.com/icon/share)/[share-variant](https://materialdesignicons.com/icon/share-variant) icon, just in the same way [eye](https://materialdesignicons.com/icon/eye) and [eye-off](https://materialdesignicons.com/icon/eye-off) are made?

**Comment by GreenTurtwig** [comment]
:cat2:
![puush-linux 2016-08-07 at 09 25 24](https://cloud.githubusercontent.com/assets/15905797/17465092/99df6b5a-5ce5-11e6-9f60-b84c3d5aac8f.png)
[share-off.zip](https://github.com/Templarian/MaterialDesign/files/405722/share-off.zip)

**Comment by hargagan** [comment]
It could be something like this :

![ic_action_unshare](https://user-images.githubusercontent.com/24852625/35073880-1717116a-fc11-11e7-81d1-b433c52cc0c1.png)

**Comment by PeterShaggyNoble** [comment]
The two icons communicate two different thinks; @GreenTurtwig's should be used in cases when content can't be shared and @hargagan's suggestion in cases when content has already been shared, in order to "unshare" it.

**Comment by goyney** [comment]
`share-off` and `share-off-outline` added. 😄
