### ISSUE TITLE
How to change default font size in SCSS?

### ISSUE THREAD

**Issue by un33k** [Templarian/MaterialDesign#1326]
site.scss includes the following:

```css
$mdi-font-path: "/assets/fonts" !default;
$mdi-font-size-base: 48px !default;
@import 'node_modules/mdi/scss/materialdesignicons.scss';
```
the font path take effect, however the default font size remains at 24px.

Usage:
```html
  <i class="mdi mdi-menu"></i>
```

Also, how to change the size via inline class?
Example for font-awsome is:
```html
<i class="fa fa-eye fa-2x"></i>
```

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Webfont/blob/master/scss/_variables.scss#L6

The way that `!default` works is that it is ignored if it is already set. So you need to put something like:

```sass
$mdi-font-path: "/assets/fonts";
$mdi-font-size-base: 48px;
@import 'node_modules/mdi/scss/materialdesignicons.scss';
```

**Comment by un33k** [comment]
`!default` is ignored in my style.scss as the variable has never been set.  Then in `materialdesignicons.scss` `!default` kicks in so variable redefinition is skipped.  So, in my case, with or without `!default` won't matter much.  Even without it, path takes effect but not font size.  I am puzzled by it for sure.

**Comment by Templarian** [comment]
You can `@import` the contents of `materialdesignicons.scss` to fix this I think. Not elegant, but should resolve your issue.
