### ISSUE TITLE
Flash with an eye for indicating FLASH_MODE_RED_EYE

### ISSUE THREAD

**Issue by skolarianer** [Templarian/MaterialDesign#1327]
Like "flash-auto" from google...
![flash-auto](https://cloud.githubusercontent.com/assets/6286711/16507340/7f9b51e8-3f29-11e6-8d51-03370599a926.png)

... but "A" replaced by "eye"
![eye](https://cloud.githubusercontent.com/assets/6286711/16507371/a803cf02-3f29-11e6-9ca3-f776fc8ab70d.png)

**Comment by skolarianer** [comment]
Ok... tried it on myself. I'm not very happy with the gap between the eye and the flash. A smaller gap doesn't look good at tiny sizes. And a bigger gap distorts the flash too much.
Actually the size of the gap equals the thickness of the white ring.

24px
![flash-red-eye_24](https://cloud.githubusercontent.com/assets/6286711/16508302/f9cc75b6-3f31-11e6-9b12-7b6e42a30f17.png)

48px
![flash-red-eye_48](https://cloud.githubusercontent.com/assets/6286711/16508317/1524e230-3f32-11e6-9e97-2a08b5445547.png)

SVG
[flash-red-eye.zip](https://github.com/Templarian/MaterialDesign/files/342606/flash-red-eye.zip)

**Comment by skolarianer** [comment]
Better alignment to grid. Also modified ring and gap. I've found no way to fullfil the 2dp width rule though. :-/

![flash-red-eye_grid](https://cloud.githubusercontent.com/assets/6286711/16566931/53bbf0a8-4219-11e6-97ff-cf7c56b7cccf.png)

24px
![flash-red-eye_24px](https://cloud.githubusercontent.com/assets/6286711/16566941/81ed9256-4219-11e6-90c5-c628e3a263b2.png)

48px
![flash-red-eye_48px](https://cloud.githubusercontent.com/assets/6286711/16566945/87faf1f2-4219-11e6-9422-7cd0e5db0469.png)

**Comment by Templarian** [comment]
Awesome (way behind on issues)!

[![flash-red-eye](https://materialdesignicons.com/icon/flash-red-eye)](https://materialdesignicons.com/icon/flash-red-eye)

@skolarianer Please let me know when you've hit 5 icons and I'll add you as a contributor. :smile:
