### ISSUE TITLE
Animal Icons

### ISSUE THREAD

**Issue by RowlandOti** [Templarian/MaterialDesign#1328]
It's been futile to find any animal related icons for a farm/animal app. Animalistic icons would come of aid e.g sheep, cow, chicken, rabbit, e.t.c. Or generally an icon to represent an animal. Thanks.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/cow
https://materialdesignicons.com/icon/pig
https://materialdesignicons.com/icon/cat
https://materialdesignicons.com/icon/paw

Closing as a duplicate of #947 as it tracks a very similar issue.

**Comment by RowlandOti** [comment]
@Templarian thanks for the links. It can be closed.
