### ISSUE TITLE
Letter in the Aplhabet icon set

### ISSUE THREAD

**Issue by CarlosCamposGalo** [Templarian/MaterialDesign#1332]
For some instances where flags in the form of letter icons are needed by the client just to signify a state in the process within the system.

The client want to have the following icons like below. A plain circle with a capital letter inside

![stack4](https://cloud.githubusercontent.com/assets/10153789/16537191/5f5e3394-402f-11e6-994a-c76c6ba09444.png)

**Comment by Templarian** [comment]
We're tracking this issue with #1299. It will most likely be a separate font.

This will most likely include Upper/Lower Letter in plain / circle / box versions.
