### ISSUE TITLE
delete-circle icon 

### ISSUE THREAD

**Issue by alessandroliveri** [Templarian/MaterialDesign#1333]
Hi, I would need a delete-circle icon as attached.
Thanks.

![schermata 2016-07-04 alle 14 49 56](https://cloud.githubusercontent.com/assets/4834881/16560933/9b092926-41f6-11e6-8246-3b46c986cdcd.png)

**Comment by Templarian** [comment]
[![delete-circle](https://materialdesignicons.com/icon/delete-circle)](https://materialdesignicons.com/icon/delete-circle)

**Comment by alessandroliveri** [comment]
Thanks 👍
