### ISSUE TITLE
Icon called "creation" doesn't work.

### ISSUE THREAD

**Issue by germansokolov13** [Templarian/MaterialDesign#1334]
I downloaded it via Bower. Bower.js says it's 1.6.50 but I can't find an icon called "creation". There is such an icon at https://materialdesignicons.com/ but it's not in the repo.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history

Looks like it was added after the 1.6.50. Will be in the next release.

**Comment by germansokolov13** [comment]
I thought all the icons at the site were present in the latest stable release.
