### ISSUE TITLE
Add-New-Filter icon

### ISSUE THREAD

**Issue by AndrewEastwood** [Templarian/MaterialDesign#1336]
I cannot find an icon that would show a funnel with plus sign.
Like that one: https://www.awicons.com/stock-icons/vista-artistic/preview/filter-add.png

**Comment by GreenTurtwig** [comment]
How's this? :cat2:
![puush-linux 2016-08-06 at 05 55 56](https://cloud.githubusercontent.com/assets/15905797/17458044/10f2be78-5bff-11e6-9af2-7aad6714b9bb.png)

**Comment by AndrewEastwood** [comment]
Yeah! That's exactly what I'm looking for

**Comment by GreenTurtwig** [comment]
[filter-plus.zip](https://github.com/Templarian/MaterialDesign/files/405100/filter-plus.zip)

If I've done anything wrong somebody should probably tell me. :-P  
First time "making" an icon. :smile_cat:

**Comment by AndrewEastwood** [comment]
neat

**Comment by GreenTurtwig** [comment]
New versions: 
[filter-plus.zip](https://github.com/Templarian/MaterialDesign/files/417162/filter-plus.zip)

**Comment by CoDEmanX** [comment]
The current filter icons are slightly rounded, whereas the filter plus isn't

**Comment by goyney** [comment]
`filter-plus(-outline)` and `filter-minus(-outline)` added! 😸
