### ISSUE TITLE
Nvidia GeForce Claw Icon

### ISSUE THREAD

**Issue by Pyroglyph** [Templarian/MaterialDesign#1337]
Something to represent NVidia (and also perhaps AMD). The full logo might look a bit odd in Material Design so I'd suggest just doing the claw something like in the images below.
![image](https://cloud.githubusercontent.com/assets/9498104/16597834/db77927a-42f2-11e6-8720-91970d519c73.png)
![image](https://cloud.githubusercontent.com/assets/9498104/16597882/0d1c6418-42f3-11e6-9a67-ef28a070636f.png)

**Comment by dietrichg** [comment]
Nice one. Also it just happens to be Issue 1337. :)

**Comment by Templarian** [comment]
Does AMD Radeon have a logo? Would probably be best to add these both at the same time.

**Comment by Pyroglyph** [comment]
I can't seem to find a specific Radeon logo that wouldn't look weird in MD, so if it is to be added, I guess the generic AMD logo (below0 would have to suffice. Also I didn't realise MD Icons was a social media based icon pack, I thought it was a community-driven pack that follows Google's design specification.

![image](https://cloud.githubusercontent.com/assets/9498104/16600907/70d5bc6c-4301-11e6-8501-e8b75bed8b1e.png)

**Comment by JamesCoyle** [comment]
We accept social media icons as they have a clear use case for share buttons but specific brand icons are usually not added. In this case I think these companies are large enough to warrant being added as they are tech companies and can be used for apps which deal with custom PCs etc. It's a shame the intel logo doesn't really fit with the style.

**Comment by Templarian** [comment]
I'm thinking about this more and going to mark it as rejected. While it definitely could be useful for some very niche uses I think it falls outside of our social media icons.

Inline SVG's can be used for these.
