### ISSUE TITLE
pdf-box

### ISSUE THREAD

**Issue by ajmihalic** [Templarian/MaterialDesign#1339]
Update the PDF file type to match those found in google drive for android.

**Comment by CoDEmanX** [comment]
Hm, we don't have a label for this kind of request...

Do you mean this? ![image](https://cloud.githubusercontent.com/assets/1309249/17440241/15f694ae-5b2c-11e6-8025-d5ecb36d9856.png)

**Comment by ajmihalic** [comment]
Yes, exactly that.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48992574-6caa5480-f106-11e8-8923-966307528284.png)
[pdf-box.svg.zip](https://github.com/Templarian/MaterialDesign/files/2614038/pdf-box.svg.zip)

**Comment by Templarian** [comment]
Added.
