### ISSUE TITLE
Emoticons

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#134]
- [x] basic
- [ ] angry
- [x] Evil
- [x] cool
- [ ] cry
- [ ] error
- [ ] laugh
- [ ] kiss
- [ ] shame
- [x] tongue
- [ ] wink
- [ ] wonder

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/emoticon-cool
http://materialdesignicons.com/icon/emoticon-tongue

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48729590-f5f0f100-ec05-11e8-8581-8bab5b8abe76.png)![image](https://user-images.githubusercontent.com/1015040/48729603-fdb09580-ec05-11e8-9a9c-6a91f0fbe790.png)
![image](https://user-images.githubusercontent.com/1015040/48729620-0acd8480-ec06-11e8-9b66-3f03992f82b9.png)![image](https://user-images.githubusercontent.com/1015040/48729627-11f49280-ec06-11e8-9477-b0584fbe76be.png)
[emoticons.zip](https://github.com/Templarian/MaterialDesign/files/2596747/emoticons.zip)

Not sure what you mean to convey with `error`, `shame`, or `wonder`. Examples?

**Comment by PeterShaggyNoble** [comment]
See also #1584

**Comment by goyney** [comment]
The 4 icons above should be named with `-outline`. I will work on creating filled versions of all emoticons we have in #1584, which will also need to do some renaming to support filled/outline, but the 4 above should be safe to add now.

**Comment by goyney** [comment]
Here's the four I proposed in both variations now:

![image](https://user-images.githubusercontent.com/1015040/48799493-48e5a980-ecd5-11e8-86c1-cbf8012ebfb8.png)![image](https://user-images.githubusercontent.com/1015040/48799519-5bf87980-ecd5-11e8-818a-08151c3f5feb.png)
![image](https://user-images.githubusercontent.com/1015040/48799507-526f1180-ecd5-11e8-895f-ac63b58adfeb.png)![image](https://user-images.githubusercontent.com/1015040/48799531-63b81e00-ecd5-11e8-9d30-651c3b899a0c.png)
![image](https://user-images.githubusercontent.com/1015040/48799543-73376700-ecd5-11e8-9455-a821d9edf7b5.png)![image](https://user-images.githubusercontent.com/1015040/48799559-79c5de80-ecd5-11e8-91af-f43134dd9463.png)
![image](https://user-images.githubusercontent.com/1015040/48799569-821e1980-ecd5-11e8-89b7-5464621703cd.png)![image](https://user-images.githubusercontent.com/1015040/48799583-89452780-ecd5-11e8-8dd1-55be604cf181.png)

[emoticons.zip](https://github.com/Templarian/MaterialDesign/files/2601388/emoticons.zip)

**Comment by Templarian** [comment]
Added. 😃
