### ISSUE TITLE
Suggestion : flashlight-wide (sample SVG included)

### ISSUE THREAD

**Issue by rob2d** [Templarian/MaterialDesign#1340]
Posting via the "Suggest an icon" link (hopefully this is the appropriate place). In any case, the mdi-flashlight seems to be taller and slimmer than most others and doesn't look too good on buttons and other UI elements in contrast to the rest of the set. Any possibility to flatten/widen these to be more like the rest of the material icon set? If there are tools I can use to learn to do this myself, I'm open to that too but was unsuccessful so far in the things I tried. 

Thanks!

**Comment by rob2d** [comment]
I edited the available SVG source but wasn't sure how to import into a font along with the other glyphs. Any help?

[mdi-flashlight-wide.zip](https://github.com/Templarian/MaterialDesign/files/358313/mdi-flashlight-wide.zip)

**Comment by Templarian** [comment]
I'm going to close out this issue as I don't think it's adoption will benefit enough users over the normal flashlight.

I forgot to add a design download for `1.6.50` I just noticed, but the last version can be downloaded here:

https://cdn.materialdesignicons.com/1.5.54/MaterialDesignIconsDesign.zip

**Comment by Templarian** [comment]
That zip contains all the webfont optimized SVG files. You can then use grunt-webfont or similar font generation (https://icomoon.io/) to generate the desired font files.

There is an issue opened to make the font generation easier to users.

**Comment by rob2d** [comment]
alright, well thanks for the help and patience! :) That's a really useful resource. Not sure if you're still paying attention to this thread, but if you happen to know if there are some custom settings causing variable heights on these exported icons after importing SVGs, would be great >_> I'll look around in the meantime. But in either case, I appreciate it!

**Comment by Templarian** [comment]
If you're exporting with grunt-webfont you will want to add these two options:

```
    autoHint: false,
    normalize: true,
```
