### ISSUE TITLE
email-edit

### ISSUE THREAD

**Issue by vaishali-ghayal** [Templarian/MaterialDesign#1341]
I need a icon for email signature and currently there is no icon for it. It would be great if icon for email signature or signature gets added, 
Thanks

**Comment by JamesCoyle** [comment]
Do you have an example of what that would look like?

I think we could do with a fountain pen and quill/feather.

**Comment by vaishali-ghayal** [comment]
Yes it would be great or check this as well http://www.iconarchive.com/show/mono-business-icons-by-custom-icon-design/signature-icon.html

**Comment by MrGrigri** [comment]
So I've come up with a couple that could make the cut. Let me know what y'all think.

![email-signature-at](https://cloud.githubusercontent.com/assets/4528551/17563960/eedcca8e-5eee-11e6-90c2-d0f07be7d892.png)
![email-signature-pen](https://cloud.githubusercontent.com/assets/4528551/17563961/eee0b202-5eee-11e6-8dd5-b5b8c1484421.png)
![email-signature-pencil](https://cloud.githubusercontent.com/assets/4528551/17563962/eee3e53a-5eee-11e6-82b7-cfecd5031ed9.png)

**Comment by goyney** [comment]
Removing Contribution label since no source SVG was provided.

**Comment by MrGrigri** [comment]
I believe this should be called `email-edit`. 

![image](https://user-images.githubusercontent.com/4528551/48987008-2d650f00-f0d8-11e8-99f2-74f59f954198.png) ![image](https://user-images.githubusercontent.com/4528551/48987017-3a81fe00-f0d8-11e8-824d-d575e7cde40a.png)

---

[email-signature.zip](https://github.com/Templarian/MaterialDesign/files/2613685/email-signature.zip)

**Comment by PeterShaggyNoble** [comment]
Should the envelope not be closed?

**Comment by MrGrigri** [comment]
Good point, I was just recreating my old ones that are more than 2 years old. I didn't even question that myself.

![image](https://user-images.githubusercontent.com/4528551/49094232-ffd8ac80-f222-11e8-980f-c6ee09f76a77.png) ![image](https://user-images.githubusercontent.com/4528551/49094261-14b54000-f223-11e8-9d4d-03b3163c842d.png)

---

[email-signature.zip](https://github.com/Templarian/MaterialDesign/files/2620757/email-signature.zip)

**Comment by Templarian** [comment]
I don't think edit is necessary for `email-open`. Added the regular email.

😃
