### ISSUE TITLE
WebRTC icon

### ISSUE THREAD

**Issue by PhilLab** [Templarian/MaterialDesign#1342]
A WebRTC icon would be nice, e.g. based on https://gist.github.com/xdumaine/08ff7b54996a86caf484

**Comment by PeterShaggyNoble** [comment]
I suspect this may be too detailed. Leaving open for now so the rest of the team can provide feedback.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by PeterShaggyNoble** [comment]
For brand icons beyond the scope of this project, try [Simple Icons](https://simpleicons.org/). Their 24*24 SVG icons should work well in conjunction with our library.
