### ISSUE TITLE
Police icon

### ISSUE THREAD

**Issue by rhroyston** [Templarian/MaterialDesign#1343]
For apps that enable people to identify and avoid police / speed traps / death!  Maybe a badge with exclamation point?

**Comment by Templarian** [comment]
So basically a https://materialdesignicons.com/icon/shield with ! inside of it. That could work for security uses also.

https://materialdesignicons.com/icon/shield-outline could also have it if it looks okay.

**Comment by rhroyston** [comment]
That could work.  I attached some ideas below:



​

On Tue, Jul 12, 2016 at 1:02 AM, Austin Andrews <notifications@github.com>
wrote:

> So basically a https://materialdesignicons.com/icon/shield with ! inside
> of it. That could work for security uses also.
>
> https://materialdesignicons.com/icon/shield-outline could also have it if
> it looks okay.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/1343#issuecomment-231945257>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AMKS-6CO4WvLytJL7f20VUPWkiZJVHC7ks5qUy31gaJpZM4JHfTb>
> .
>



-- 
- Ron Royston
  (504) 722-8412

**Comment by MrGrigri** [comment]
Here are a couple of ideas. @Templarian, I do still like the idea of a shield with an exclamation point though. I also understand that having the letter P inside of a shield does limit its translation across languages; however, a lot of languages that use the Roman alphabet have a 'p' as the initial letter for police. Look at [this](http://www.indifferentlanguages.com/words/police) for reference.

![police-hat](https://cloud.githubusercontent.com/assets/4528551/17566276/f1f2a474-5ef7-11e6-8fab-2915fdb350a3.png)
![police-shield](https://cloud.githubusercontent.com/assets/4528551/17566277/f1fd0d6a-5ef7-11e6-8570-8a047b219b3d.png)

**Comment by gamebusterz** [comment]
Adding a Icon with a star would be great. 
[https://cloud.githubusercontent.com/assets/6880188/19926670/d2aa2590-a11b-11e6-8fcf-604fac5fd4c4.png](url)

**Comment by Templarian** [comment]
@MrGrigri Yep, lets stay away from letters on icons. I like the police hat. Can we get a svg for that one.

**Comment by MrGrigri** [comment]
Sorry, I forgot about this one. Here is the file.

![police-hat](https://cloud.githubusercontent.com/assets/4528551/21662589/b9db2bd8-d297-11e6-9a36-6e7451c25c58.png)

[police.zip](https://github.com/Templarian/MaterialDesign/files/686069/police.zip)

**Comment by PeterShaggyNoble** [comment]
I don't know that a cap would work as they differ around the world.

**Comment by CoDEmanX** [comment]
On the other hand, there is no international symbol to represent "police", or if there is, then nobody seems to know about it.

**Comment by Templarian** [comment]
Yea, guys, not sure if there is a right symbol for this one. Moving this to backlog until we think this through more.

**Comment by PeterShaggyNoble** [comment]
Given the correct context, `alarm-light` could be an option.

**Comment by goyney** [comment]
Some other ideas:

![image](https://user-images.githubusercontent.com/1015040/62841761-d9a45100-bc79-11e9-9cec-db1263e9884e.png)![image](https://user-images.githubusercontent.com/1015040/62841769-e9239a00-bc79-11e9-8750-6242f226b200.png)
[police-badge.zip](https://github.com/Templarian/MaterialDesign/files/3490622/police-badge.zip)

---

![image](https://user-images.githubusercontent.com/1015040/62841806-36a00700-bc7a-11e9-8a50-dbc33ea9a421.png)![image](https://user-images.githubusercontent.com/1015040/62841812-3e5fab80-bc7a-11e9-93f0-6455287b739b.png)
[shield-star.zip](https://github.com/Templarian/MaterialDesign/files/3490624/shield-star.zip)

Think we should add `shield-star(-outline)` regardless.

**Comment by CoDEmanX** [comment]
The police badges are really nice! They seem familiar to me, eventhough the German police has nothing like it I believe... I might recognize this shape because of Need for Speed Most Wanted or a similar game 😄

**Comment by goyney** [comment]
Add `shield-star(-outline)`.

**Comment by MrGrigri** [comment]
I believe the `police-badge(-outline)` would work perfectly. I'm going to remove myself as the contributor and add @goyney.

**Comment by goyney** [comment]
[![police-badge](https://materialdesignicons.com/icon/police-badge)](https://materialdesignicons.com/icon/police-badge)[![police-badge-outline](https://materialdesignicons.com/icon/police-badge-outline)](https://materialdesignicons.com/icon/police-badge-outline)
