### ISSUE TITLE
Add metronome icon

### ISSUE THREAD

**Issue by lesilva00** [Templarian/MaterialDesign#1344]
Some icon that remember a new (digital) or old (analogical) metronome.

**Comment by Templarian** [comment]
Do you have an example (images can be pasted inline in comments).

**Comment by JapanYoshi** [comment]
![path4153](https://cloud.githubusercontent.com/assets/8707990/17193374/afcb7bda-548d-11e6-98da-488195e38797.png)![path4154](https://cloud.githubusercontent.com/assets/8707990/17193366/aa1cdd0a-548d-11e6-8fc2-e7908f79a50a.png) 

![path4152](https://cloud.githubusercontent.com/assets/8707990/17193395/c90f0eb8-548d-11e6-8c98-752f50deaf3f.png)![path4155](https://cloud.githubusercontent.com/assets/8707990/17193379/b7f34c66-548d-11e6-9e9c-36c1b81f0c0b.png)

**Comment by JamesCoyle** [comment]
Can you post the SVG for those?

**Comment by JapanYoshi** [comment]
[metronome.zip](https://github.com/Templarian/MaterialDesign/files/411090/metronome.zip)
There you go.

**Comment by JapanYoshi** [comment]
I see these have not been added.

**Comment by Templarian** [comment]
[![metronome](https://materialdesignicons.com/icon/metronome)](https://materialdesignicons.com/icon/metronome) [![metronome-tick](https://materialdesignicons.com/icon/metronome-tick)](https://materialdesignicons.com/icon/metronome-tick)
