### ISSUE TITLE
API: Download Icons / Lists

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1347]
> API that can be used to download/list icons?

From [twitter](https://twitter.com/varazir/status/751341324742295552).

**Comment by Templarian** [comment]
https://materialdesignicons.com/custom This can generate a file that you can use with all the icon data.

Right now I don't have public facing API's for this, but I'm working on a system to generate a meta.json file with all the required data after every release.

**Comment by mkarthi-cb** [comment]
Hi @Templarian can I use "https://materialdesignicons.com/custom" to generate only required icons with names. If its possible there is any document for that?

**Comment by Templarian** [comment]
https://cdn.materialdesignicons.com/1.8.36/meta.json

Still working on a nice way to bundle more of this for personal use, but for now you could use the above JSON file as it is included with the releases.

**Comment by mkarthi-cb** [comment]
Hi @Templarian  Thanks a lot. But I want only selected icons(may be 100 to 200 icons). There is any way to select icons and do export/download only those selected icons as web font? 

For example "http://fontello.com/" this guy allow me to choose icons and do export only the selected icons. There is any workaround ??

**Comment by PeterShaggyNoble** [comment]
You could use [IcoMoon](https://icomoon.io/) to create your own, custom font using the SVGs of the icons you need.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site/issues/17

Closing this issue out as it's being tracked above. The plan ideally is to release a library built off of `grunt-webfont` that can build a list of icons. To do this requires a lot more work though and planning. The build chain for MDI currently is rather complex and hacked together, but users will need only the basics.
