### ISSUE TITLE
keyboard icons

### ISSUE THREAD

**Issue by atsepkov** [Templarian/MaterialDesign#1348]
I'm looking for an "escape" key icon and can't seem to find it. I'd love an icon set for each keyboard key to use when telling user which shortcuts to use.

**Comment by Ekidoxx** [comment]
Oh yes, such icon set would be amazing

**Comment by casesandberg** [comment]
![image](https://cloud.githubusercontent.com/assets/4633636/20743497/9b548b96-b68b-11e6-80dc-01ff7347f8ea.png)

[keyboard-key-icons.zip](https://github.com/Templarian/MaterialDesign/files/621192/keyboard-key-icons.zip)

**Comment by JamesCoyle** [comment]
Can we have these as just the text? Not really sure how useful the black background would be to most people.

**Comment by atsepkov** [comment]
Wouldn't the background color be configurable (at least in the font version)?

**Comment by PeterShaggyNoble** [comment]
They'd need something to indicate they represent keys on a keyboard; I think an outline would work best.

**Comment by goyney** [comment]
Command should use the `apple-keyboard-command` icon, IMO.

**Comment by PeterShaggyNoble** [comment]
@goyney, that's not immediately identifiable to those that don't use Apple products.

**Comment by PeterShaggyNoble** [comment]
Oh, yeah, true. Sorry, hadn't had my caffeine yet!

**Comment by goyney** [comment]
We're actively trying to not include icons that are just letters. For these, while the letter combinations are obvious in their meaning for computer users, they can already be created by using our alpha set and positioning the letters you need together.

At this point, I vote to close this issue.

**Comment by JapanYoshi** [comment]
Esc can use an emergency exit icon.

Ctrl has an ISO symbol ⎈, but it's neither used or known.

Alt has an ISO symbol ⎇, but the one for Option (that upside down w/o the arrowhead) is more recognizable.

Command and Option can use the Mac symbols.

I'd also like a meta or compose key, but I've never used a Linux before so I can't help with that.
