### ISSUE TITLE
Plus sign with - music icon/playlist icon - in bottom right

### ISSUE THREAD

**Issue by bigworld12** [Templarian/MaterialDesign#1349]

**Comment by CoDEmanX** [comment]
We have playlist-plus. Do you also want a  music-note-plus icon?

**Comment by bigworld12** [comment]
oh yes please

**Comment by GreenTurtwig** [comment]
Is this good? :smile_cat: I put the plus on the side instead of bottom right to match the Bluetooth note icon.
![puush-linux 2016-08-07 at 09 23 38](https://cloud.githubusercontent.com/assets/15905797/17465084/53f338ba-5ce5-11e6-8724-9749ec2ff5fc.png)
[music-note-plus.zip](https://github.com/Templarian/MaterialDesign/files/405719/music-note-plus.zip)

**Comment by GreenTurtwig** [comment]
[music-note-plus.zip](https://github.com/Templarian/MaterialDesign/files/417156/music-note-plus.zip)
New version

**Comment by bigworld12** [comment]
very nice thanks @GreenTurtwig

**Comment by Templarian** [comment]
@bigworld12 Please don't close issues until they are added in. Thanks.

**Comment by bigworld12** [comment]
@Templarian ok sorry for that

**Comment by CoDEmanX** [comment]
@GreenTurtwig It's not on grid for some reason. I tried to center it visually better and this is the outcome:

![image](https://user-images.githubusercontent.com/1309249/38770217-8be8517e-400f-11e8-8cd5-bbb6ba1ceac3.png)

Plus is moved 1px down from center, music note shifted 1px to the right.

[music-note-plus.zip](https://github.com/Templarian/MaterialDesign/files/1910594/music-note-plus.zip)

**Comment by GreenTurtwig** [comment]
This including the filter-plus icon were done over a year ago. I need to go back and look at them at some point.

**Comment by Templarian** [comment]
[![music-note-plus](https://materialdesignicons.com/icon/music-note-plus)](https://materialdesignicons.com/icon/music-note-plus)
