### ISSUE TITLE
A bunch of icons

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#135]
- [x] Dice 1-6
- [x] Coffee 2 go
- [ ] Guitar
- [x] Bar/Line graph
- [x] Drag to sort list. Similar like "keyboard-caps"

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/dice

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/coffee-to-go

**Comment by CoDEmanX** [comment]
As for drag to sort, there's this:
https://materialdesignicons.com/icon/unfold-more

And also multiple drag indicators:
https://materialdesignicons.com/icon/drag
https://materialdesignicons.com/icon/drag-horizontal
https://materialdesignicons.com/icon/drag-vertical

Or do you mean something else @matthew2402?

**Comment by matthew2402** [comment]
Puh, that's a really old request;)
But they fit very well! Just forgot to check the box.

Close this issue cause the guitar icon has its own issue!
