### ISSUE TITLE
Medical icons

### ISSUE THREAD

**Issue by ArunPandiyan** [Templarian/MaterialDesign#1352]
need height, weight, blood pressure,

**Comment by JamesCoyle** [comment]
You could use these icons:
[![ruler](https://materialdesignicons.com/icon/ruler)](https://materialdesignicons.com/icon/ruler)[![weight](https://materialdesignicons.com/icon/weight)](https://materialdesignicons.com/icon/weight)[![gauge](https://materialdesignicons.com/icon/gauge)](https://materialdesignicons.com/icon/gauge)

**Comment by Templarian** [comment]
If you have some example for what these icons could be I'll reopen the issue. There is also a bathroom scale.

[![scale-bathroom](https://materialdesignicons.com/icon/scale-bathroom)](https://materialdesignicons.com/icon/scale-bathroom)

**Comment by ArunPandiyan** [comment]
Great Work. Thank you.
