### ISSUE TITLE
Pray Icon

### ISSUE THREAD

**Issue by TinasheMzondiwa** [Templarian/MaterialDesign#1353]
Need a Pray or Prayer Icon.

https://thenounproject.com/term/pray/76148/

**Comment by JamesCoyle** [comment]
The hard part with that is creating an icon that represents the action itself. I feel like we may end up adding a few variants for the methods of different religions.

**Comment by TinasheMzondiwa** [comment]
Maybe just 'two hands' icon for a start.
Would really appreciate, but I understand its a lot of work. 

Thanks

**Comment by Templarian** [comment]
This is going to be a little difficult to show at the 24x24 size. Looking at examples online and they kind of look like towers at smaller sizes. Hmm... is there another way to represent this (that is not tied to a single religion)?

**Comment by j2l** [comment]
+1

**Comment by jimmyff** [comment]
Yep, MDI is really lacking an icon(s) to represent prayer.

I personally think the hands together is the most iconic, however kneeling etc in addition to praying hands would be great.

More inspiration:

![prayer2](https://user-images.githubusercontent.com/298850/68030549-a50cc800-fcb1-11e9-8781-f40afd84556d.png)
![prayer1](https://user-images.githubusercontent.com/298850/68030550-a50cc800-fcb1-11e9-851d-9f837501db21.png)
![prayer6](https://user-images.githubusercontent.com/298850/68030543-a4743180-fcb1-11e9-9028-0943da5d6fd0.jpg)
![prayer5](https://user-images.githubusercontent.com/298850/68030544-a4743180-fcb1-11e9-9323-80ec14984d58.png)
![prayer4](https://user-images.githubusercontent.com/298850/68030547-a4743180-fcb1-11e9-9412-060cceb0a12d.jpg)

![prayer3](https://user-images.githubusercontent.com/298850/68030548-a4743180-fcb1-11e9-8254-57db5390dbbd.png)

**Comment by Xenomorph99** [comment]
The "folded hands" emoji is quite common: https://emojipedia.org/folded-hands/

<img src="https://user-images.githubusercontent.com/1837101/95626485-99845e00-0a37-11eb-87c7-be9ace7642cf.png" width="400" />

Personally, I'm not a fan of calling our icon `hands-folded`. I think `hands-pray` would be a more colloquial fit. Let's make sure to include the following aliases too: `hands-folded`, `namaste`, `please`, `prayer`, and `thank-you`.

I think adding the white space around the thumbs helps avoid the towers interpretation you brought up @Templarian.

![hands-pray-example](https://user-images.githubusercontent.com/1837101/95626886-655d6d00-0a38-11eb-8cfa-086771c889ea.png)

![hands-pray](https://user-images.githubusercontent.com/1837101/95626887-65f60380-0a38-11eb-886a-effdab9433d4.png)

[hands-pray.zip](https://github.com/Templarian/MaterialDesign/files/5357259/hands-pray.zip)

**Comment by temaprint** [comment]
there are options
check
https://icons8.com/icons/set/pray
<img src="https://img.icons8.com/color/50/000000/pray.png"/><img src="https://img.icons8.com/ios-filled/50/000000/pray.png"/>
or
<img src="https://img.icons8.com/color/50/000000/prayer.png"/><img src="https://img.icons8.com/emoji/50/000000/person-kneeling.png"/>

**Comment by JapanYoshi** [comment]
Having ``hands-pray`` and ``person-pray`` (like the pictograms for Prayer Rooms) would be a good solution methinks.

**Comment by danbaechtold** [comment]
Let's keep it simple and please (as a first step) just add folded-hands and raising-hands emojis counterparts: 
https://emojipedia.org/folded-hands/
https://emojipedia.org/raising-hands/

**Comment by goyney** [comment]
[![hands-pray](https://materialdesignicons.com/icon/hands-pray)](https://materialdesignicons.com/icon/hands-pray)
