### ISSUE TITLE
Wider battery-charging icon

### ISSUE THREAD

**Issue by NBonaparte** [Templarian/MaterialDesign#1354]
For some reason, the `battery-charging` icon is thinner than the other battery icons. Simply adding the charging symbol to the full battery symbol should fix this.

[https://www.dropbox.com/s/c12cdgrf2emo5aw/battery-charging-large.svg?dl=0](https://www.dropbox.com/s/c12cdgrf2emo5aw/battery-charging-large.svg?dl=0)

**Comment by Templarian** [comment]
Fixed, not sure how that happened to just that one... weird.

[![battery-charging](https://materialdesignicons.com/icon/battery-charging)](https://materialdesignicons.com/icon/battery-charging)

Thanks!
