### ISSUE TITLE
Brain icons

### ISSUE THREAD

**Issue by malinosqui** [Templarian/MaterialDesign#1355]
like these http://www.flaticon.com/search?word=brain

**Comment by RamakrishnaUX** [comment]
![brain](https://cloud.githubusercontent.com/assets/8967337/16761071/3fd5cf18-483c-11e6-9a0a-e190f2560fe9.png)
[brain.zip](https://github.com/Templarian/MaterialDesign/files/358905/brain.zip)

**Comment by Templarian** [comment]
@RamakrishnaUX Can you post that over in #526. I think this is in a better direction that the one in that issue.

Marking this as a duplicate.
