### ISSUE TITLE
Exit/Logout Icon.

### ISSUE THREAD

**Issue by buutqn** [Templarian/MaterialDesign#1360]
I'd love to have this icon. Also, it could be something like the Exit to App

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/exit-to-app
https://materialdesignicons.com/icon/logout
https://materialdesignicons.com/icon/logout-variant

**Comment by Templarian** [comment]
I think what you wanted was the logout icon which there are 2. If not can you please post an example image and I'll reopen the issue.
