### ISSUE TITLE
Support for Goggle's date_range icon

### ISSUE THREAD

**Issue by simonered** [Templarian/MaterialDesign#1361]
Can't find Google's **date_range** icon. Is it supported under other name?

**Comment by Templarian** [comment]
Looks like it wasn't included. Should be in the next release.

[![calendar-range](https://materialdesignicons.com/icon/calendar-range)](https://materialdesignicons.com/icon/calendar-range)

We use nouns so `date-*` is `calendar-*`.

Thanks!
