### ISSUE TITLE
Support ORCID icon

### ISSUE THREAD

**Issue by klemy202** [Templarian/MaterialDesign#1362]
Hi,
Is the [ORCID](http://orcid.org) icon supported ? This come from an very popular open source scientific project.
[There is the logo image source.](http://orcid.org/0000-0001-9411-1868)

Thanks in advance,

**Comment by Templarian** [comment]
Nope. We currently only support social media branded icons.

**Comment by klemy202** [comment]
Why this decision ?

**Comment by Templarian** [comment]
? It's not social media, so far too specific for most users. Think more Instagram / Twitter / etc. Rule we put in place a year ago, we might eventually retroactively remove some of the icons that don't follow this eventually. Just haven't gotten around to it.

For these types of icons we suggest users use inline SVG.

**Comment by klemy202** [comment]
Ok, I understand. Thanks for the advice !
