### ISSUE TITLE
Wish Icon

### ISSUE THREAD

**Issue by praveenkush12** [Templarian/MaterialDesign#1363]
I am wishing some one well.

**Comment by Templarian** [comment]
Do you have an example of what this would be exactly?

**Comment by Ekidoxx** [comment]
For some reason "dandelion clock" was my first thought, but it might be extremely hard to make it in material style and understandable... so maybe:
![Crossed fingers](https://cdn3.iconfinder.com/data/icons/casino-and-gambling-icons/414/Hand_Fingers_Crossed-2-128.png)

**Comment by JamesCoyle** [comment]
Crossed fingers would be a good addition IMO.

**Comment by CoDEmanX** [comment]
Looks painful :D

**Comment by MrGrigri** [comment]
What about more of a genie's lamp?

![wish](https://cloud.githubusercontent.com/assets/4528551/17445628/06eaea06-5b03-11e6-8088-892f258d057f.png)

**Comment by CoDEmanX** [comment]
Good thinking! Can you uploade a 24x24 pixel version, so we can see how it works at the native scale?

**Comment by MrGrigri** [comment]
Like this?

![wish alt](https://cloud.githubusercontent.com/assets/4528551/17448994/a7e295ec-5b14-11e6-8eac-2c48c675d552.png)

**Comment by JamesCoyle** [comment]
Can you post the SVG?

**Comment by MrGrigri** [comment]
Here's the zip file with the SVG. 

[wish.zip](https://github.com/Templarian/MaterialDesign/files/411230/wish.zip)

**Comment by goyney** [comment]
`oil-lamp` added.

Aliases `wish` and `genie-lamp` added.
