### ISSUE TITLE
Dancing Couple

### ISSUE THREAD

**Issue by jarhoax** [Templarian/MaterialDesign#1365]
First of all, nice work! I'm glad you provide such a huge icon library.

I would like to have an icon showing a dancing couple, as I'm developing an app for a dancing school. Thank you.

**Comment by lawloretienne** [comment]
+1

**Comment by terpro** [comment]
+1

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/89362145-193e2700-d69b-11ea-9e38-67863c70e183.png)
[dance-ballroom.svg.zip](https://github.com/Templarian/MaterialDesign/files/5025631/dance-ballroom.svg.zip)

**Comment by goyney** [comment]
Added.
