### ISSUE TITLE
Edit Icon

### ISSUE THREAD

**Issue by bolorundurowb** [Templarian/MaterialDesign#1366]
If it is possible, could you create an edit icon?

**Comment by REJack** [comment]
i use the [pencil](https://materialdesignicons.com/icon/pencil) icon for this

**Comment by Templarian** [comment]
@bolorundurowb I would instantly think the pencil icon for edit also. Did you have another icon in mind (you can inline paste images into comments)?

**Comment by bolorundurowb** [comment]
Thanks
