### ISSUE TITLE
Icon: DNA

### ISSUE THREAD

**Issue by Jonas-Drotleff** [Templarian/MaterialDesign#1368]

**Comment by Templarian** [comment]
![dna](http://s3.amazonaws.com/rapgenius/1374644032_tumblr_lxarxioCe31ql8i93o1_500.gif)

**Comment by JapanYoshi** [comment]
![path4152](https://cloud.githubusercontent.com/assets/8707990/17177334/d0d86c4e-544b-11e6-9afe-aa8b027d9960.png)
I'm still new to Material icons, but I tried my best.

**Comment by Templarian** [comment]
Looks nice, attach the svg in a zip.

**Comment by JapanYoshi** [comment]
[dna.zip](https://github.com/Templarian/MaterialDesign/files/387245/dna.zip)

**Comment by Templarian** [comment]
[![dna](https://materialdesignicons.com/icon/dna)](https://materialdesignicons.com/icon/dna)

Let me know when you have 5 icons @JapanYoshi and I'll create a contributor account (also set a github picture).
