### ISSUE TITLE
Limousine

### ISSUE THREAD

**Issue by bearoutthere** [Templarian/MaterialDesign#1369]
- [x] van
- [ ] helicopter
- [x] limo
- [ ] speed boat
- [x] cruise ship
- [ ] dive boat

**Comment by GreenTurtwig** [comment]
Limousine
![image](https://user-images.githubusercontent.com/15905797/32721965-3bf785da-c860-11e7-856b-0adfb64461e8.png)
![image](https://user-images.githubusercontent.com/15905797/32721975-47fccf2a-c860-11e7-90e7-c766a78db61c.png)
[car-limousine.zip](https://github.com/Templarian/MaterialDesign/files/1466481/car-limousine.zip)

**Comment by GreenTurtwig** [comment]
Van
[![](https://materialdesignicons.com/icon/van-utility)](https://materialdesignicons.com/icon/van-utility)[![](https://materialdesignicons.com/icon/van-passenger)](https://materialdesignicons.com/icon/van-passenger)

Helicopter
https://github.com/Templarian/MaterialDesign/issues/1367

Ferry
[![](https://materialdesignicons.com/icon/ferry)](https://materialdesignicons.com/icon/ferry)

**Comment by GreenTurtwig** [comment]
I'm going to separate this into an issue for just a limousine. If the other icons are still needed, it would be best to open individual issues.

**Comment by Templarian** [comment]
[![car-limousine](https://materialdesignicons.com/icon/car-limousine)](https://materialdesignicons.com/icon/car-limousine)
