### ISSUE TITLE
software and frameworks

### ISSUE THREAD

**Issue by jc-anguiano** [Templarian/MaterialDesign#1370]
hi, i guess that some icons like 3Dstudio, Maya, Modo, VueJS should be useful

**Comment by JamesCoyle** [comment]
We don't tend to include brand icons unless they are social networks (useful for share buttons). For these it is best to use inline SVG.

**Comment by jc-anguiano** [comment]
that make sense, thanks

2016-07-20 8:01 GMT-05:00 James Coyle <notifications@github.com>:
