### ISSUE TITLE
Support Wikipedia icon

### ISSUE THREAD

**Issue by klemy** [Templarian/MaterialDesign#1371]
# Type

Icon request
# Icon description

Wikipedia icon
# Link

https://en.wikipedia.org/wiki/Wikipedia_logo

**Comment by Templarian** [comment]
So like the "W"? Hmm... yea this might be a useful one.

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/wikipedia)](https://materialdesignicons.com/icon/wikipedia)
