### ISSUE TITLE
Icon: Airplane variations

### ISSUE THREAD

**Issue by GuiCavi** [Templarian/MaterialDesign#1372]
Just like map-marker has variations (plus, minus...), airplanes could have too.

:smile:

**Comment by CoDEmanX** [comment]
As in add airplane? What would you use that for?!

**Comment by GuiCavi** [comment]
semantically it can be used to indicate flies manipulation (airport system/sites)

:smile:

**Comment by GreenTurtwig** [comment]
![puush-linux 2016-08-14 at 06 22 30](https://cloud.githubusercontent.com/assets/15905797/17650708/351db0de-624c-11e6-8736-d1e2571f847a.png)
Personally I don't think they look that great. :-S
[airplane.zip](https://github.com/Templarian/MaterialDesign/files/417141/airplane.zip)

**Comment by JamesCoyle** [comment]
I'm edging towards rejecting this one as I'm not really seeing a use for them outside of air traffic control software which doesn't really focus on making things look pretty. The minus one looks more like a boarding tunnel and the plus looks like a plane flying below another plane. I feel like the meaning of such icons can be better conveyed by proper UI design and context along with the more generic plus and minus icons.

**Comment by GreenTurtwig** [comment]
I totally agree with that. :-)  
They just don't really fit in well at all.

**Comment by Templarian** [comment]
Yea, rejecting this one as it's too specific. Thanks though, probably should have closed this out earlier.

**Comment by GuiCavi** [comment]
Yeah, in my head it was nice, but I tried to draw it and meeeh. After thinking on it, I agree it's too specific.

Anyway, thanks for the great job.

:smile:
