### ISSUE TITLE
high cableway

### ISSUE THREAD

**Issue by adbstyle** [Templarian/MaterialDesign#1376]
hi
here's a high cableway icon as a contribution

![funicular-3](https://cloud.githubusercontent.com/assets/10384436/17106993/50d16446-5285-11e6-87ab-60b1f08634f3.png)

[ic_high_cableway_black_48px.zip](https://github.com/Templarian/MaterialDesign/files/377898/ic_high_cableway_black_48px.zip)

cheers adrian

**Comment by MrGrigri** [comment]
Also known as a gondola. I like it.

**Comment by Templarian** [comment]
[![gondola](https://materialdesignicons.com/icon/gondola)](https://materialdesignicons.com/icon/gondola)
