### ISSUE TITLE
Download Design Resources not working

### ISSUE THREAD

**Issue by barrymieny** [Templarian/MaterialDesign#1379]
The link to "Download Design Resources" on https://materialdesignicons.com/design redirects to https://cdn.materialdesignicons.com/1.6.50/MaterialDesignIconsDesign.zip with a `404 Not found`.

**Comment by Templarian** [comment]
Yea... noticed this the other day, need to fix this tomorrow. Heading to a festival at the moment.

https://cdn.materialdesignicons.com/1.5.54/MaterialDesignIconsDesign.zip (old version is here, but of course not ideal).

Thanks for reminding me!
