### ISSUE TITLE
running, swimming

### ISSUE THREAD

**Issue by christian160984** [Templarian/MaterialDesign#138]
- Running
- Walking
- Cycling
- Swimming

Many thanks.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/bike (already exists)
http://materialdesignicons.com/icon/walk (already exists)

Running and swimming will need to be added.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/run
http://materialdesignicons.com/icon/swim
