### ISSUE TITLE
Icon: Stop sign

### ISSUE THREAD

**Issue by abondzinskas** [Templarian/MaterialDesign#1380]
When you click the refresh button and you want stop refreshing

**Comment by JamesCoyle** [comment]
[![octagon](https://materialdesignicons.com/icon/octagon)](https://materialdesignicons.com/icon/octagon)[![stop](https://materialdesignicons.com/icon/stop)](https://materialdesignicons.com/icon/stop)

**Comment by Templarian** [comment]
We've been trying to not include icons with text as they are not easily localized. I think the octagon in this case should work. Let me know if we can add a symbol that might represent this better (example images can be pasted inline).
