### ISSUE TITLE
Physical Mail Icons

### ISSUE THREAD

**Issue by ingeniouslabs** [Templarian/MaterialDesign#1381]
Recently working with lob.com (physical mail api) having trouble finding icons that are differentiated from e-mail. 

Mailbox
Letter
Envelope (not used for email)

**Comment by Templarian** [comment]
There is a mailbox icon in the official set... https://design.google.com/icons/#ic_markunread_mailbox

Do you have an example of what a letter icon/envelop icon would be that doesn't look like their digital representation?

**Comment by Templarian** [comment]
Closing this issue as there hasn't been any activity for a while.
