### ISSUE TITLE
Icon: Search Icon (Text Search)

### ISSUE THREAD

**Issue by ganeshkbhat** [Templarian/MaterialDesign#1382]
Search Icon (Text Search) - depicting a magnifying glass is needed. Not there in the list.

**Comment by Templarian** [comment]
So like lines next to the [magnify](https://materialdesignicons.com/icon/magnify) icon to represent text?

I think users will assume that the magnify icon means search/filter by text match. Can you give a context where this might be needed (where a regular magnify icon wouldn't work)?

**Comment by ganeshkbhat** [comment]
I didnt notice this. This should be fine. Please close the issue log.
