### ISSUE TITLE
gif-box(-multiple)

### ISSUE THREAD

**Issue by sunshinetpu** [Templarian/MaterialDesign#1383]
Need an icon for GIF files.

**Comment by MrGrigri** [comment]
Like this:

![GIF](https://dl.dropboxusercontent.com/u/4863980/gif.png)

**Comment by CoDEmanX** [comment]
There's an official GIF icon by Google: https://design.google.com/icons/#ic_gif
#420

**Comment by MrGrigri** [comment]
That's true, however, I believe this is a good alternative. This matches their ["Picture as PDF"](https://design.google.com/icons/#ic_picture_as_pdf) icon.

**Comment by Simran-B** [comment]
Your example disappeared (Not Found) 😞 
I would include both to be honest. MDI has so many icons already, "size" shouldn't matter. Combining all official icons + our variants and community-designed ones would be my goal.

**Comment by CoDEmanX** [comment]
Your example disappeared (Not Found) 😞 
I would include both to be honest. MDI has so many icons already, "size" shouldn't matter. Combining all official icons + our variants and community-designed ones would be my goal.

**Comment by JapanYoshi** [comment]
``gif-multiple``?

**Comment by goyney** [comment]
@MrGrigri Your icon no longer shows up. We'll add the official Google GIF icon in #1451.

**Comment by JamesCoyle** [comment]
Repurposing this to add gif-box and a multiple variant assuming the text will fit into our box.

**Comment by goyney** [comment]
Google's GIF icon will not fit into our box for these. Closing this as we have an option for GIFs now.
