### ISSUE TITLE
Hamburger Icon

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#1385]
I tried my hand at making a hamburger icon. I don't know how to attach SVG files, so I exported it at three sizes.
![path4150](https://cloud.githubusercontent.com/assets/8707990/17160875/9c8dbe84-53e3-11e6-943b-c8dd6d8182fb.png)
![path4151](https://cloud.githubusercontent.com/assets/8707990/17160878/9e47e254-53e3-11e6-8ada-8fa70b23df10.png)
![path4152](https://cloud.githubusercontent.com/assets/8707990/17160879/9f823778-53e3-11e6-9362-ae385198c68a.png)

**Comment by Templarian** [comment]
Can we do something closer to the minimalist as seen in the [food](https://materialdesignicons.com/icon/food) icon.

http://templarian.com/2016/06/03/modern-day-hieroglyphics/ View the first slide in my talk about icons and you'll get an idea of the icon design that should be used for this. :smile:

**Comment by JapanYoshi** [comment]
![path4152](https://cloud.githubusercontent.com/assets/8707990/17161169/33a71b60-53e6-11e6-97d2-1a3eaf68c54b.png)
You mean like this? (including the bit of cheese)

**Comment by Templarian** [comment]
Yep, pretty much. Out for a run I think this would be a nice addition.

**Comment by JapanYoshi** [comment]
I'm still quite fond of the lettuce in the first version, though. I don't think there'd be a loss in including it as an alternate.

**Comment by Templarian** [comment]
Can you link the svg zip for this one. Also, I'm bad at keeping track remind me once I've added 5 of these and I'll assign them to your contributor account (set a github photo to make it easier, I'll just use that).

**Comment by JapanYoshi** [comment]
[burger.zip](https://github.com/Templarian/MaterialDesign/files/387656/burger.zip)

**Comment by Templarian** [comment]
[![hamburger](https://materialdesignicons.com/icon/hamburger)](https://materialdesignicons.com/icon/hamburger)

Thanks! Added.
