### ISSUE TITLE
Aeolian

### ISSUE THREAD

**Issue by ADVMOSCA** [Templarian/MaterialDesign#1386]
Aeolian

**Comment by JapanYoshi** [comment]
I don't know what you mean. Do you mean [the natural minor scale](https://en.wikipedia.org/wiki/Aeolian_mode)? [The Aeolian Islands](https://en.wikipedia.org/wiki/Aeolian_Islands)? [Something related to classical architecture](https://en.wikipedia.org/wiki/Aeolic_order)?

**Comment by ADVMOSCA** [comment]
I'm sorry, renewable energy, wind turbine blades

**Comment by PeterShaggyNoble** [comment]
Closing in favour of the more active #1672
