### ISSUE TITLE
kindergartens marker

### ISSUE THREAD

**Issue by omriLugasi** [Templarian/MaterialDesign#1389]
should be show with :
child and slide

**Comment by MrGrigri** [comment]
Do you mean like a playground?

**Comment by JapanYoshi** [comment]
![path4712](https://cloud.githubusercontent.com/assets/8707990/17391942/03a7897a-5a55-11e6-859f-fec836b5c32a.png)

Well, at least I tried.

**Comment by Templarian** [comment]
I'm going to close this icon as too specific. We can reopen it if there is a future reason it is needed.

**Comment by omriLugasi** [comment]
Yes, thank you it's look great!
