### ISSUE TITLE
Idea: Subscript and superscript

### ISSUE THREAD

**Issue by JonnyBurger** [Templarian/MaterialDesign#139]
Google provides a bunch of editor icons, but they don't provide the subscript or superscript icons they use. Actually it's very hard to find good icons for those 2 things on the internet.

They could look something like this: 
![bildschirmfoto 2015-02-05 um 00 32 20](https://cloud.githubusercontent.com/assets/1629785/6052082/daa8e7a6-acce-11e4-88cb-3afb0f586194.png)

**Comment by Templarian** [comment]
These already exist, they are called superscript and subscript:

http://materialdesignicons.com/icon/format-superscript
http://materialdesignicons.com/icon/format-subscript

**Comment by JonnyBurger** [comment]
wow, I am an idiot. how did i not find these

thank you for this, highly appreciated. awesome project
