### ISSUE TITLE
Ironing Board

### ISSUE THREAD

**Issue by nkgilley** [Templarian/MaterialDesign#1390]
- [x] washer
- [x] dryer
- [ ] detergent
- [x] iron
- [ ] iron board
- etc

**Comment by PeterShaggyNoble** [comment]
- `washing-machine` is already available.
- `tumble-dryer` is covered in #1625 scheduled to be added soon, for the next release.
- `iron` is being tracked in #2752.
- Can you open a new issue for `detergent` and provide an example?
- Any other icons you need besides the ones listed, please open a new issue for each one.

Leaving this one open as a request for an ironing board.

**Comment by JamesCoyle** [comment]
Need to come up with some ideas for this. I'm not sure how well it would work in the space given.

**Comment by Xenomorph99** [comment]
A side view like this might work. From above, the typical ironing board shape would probably look strange as an icon.

Not sure if we should call it `iron-board` or `ironing-board`, but we should include `laundry` and `wash` as aliases.

![ironing-board](https://user-images.githubusercontent.com/1837101/94310591-1cd18a00-ff37-11ea-93fa-7349a6c252ae.png)

[ironing-board.zip](https://github.com/Templarian/MaterialDesign/files/5285058/ironing-board.zip)

**Comment by goyney** [comment]
[![iron-board](https://materialdesignicons.com/icon/iron-board)](https://materialdesignicons.com/icon/iron-board)
