### ISSUE TITLE
Request: Douban icon

### ISSUE THREAD

**Issue by dongweiming** [Templarian/MaterialDesign#1394]
douban.com is a popular Chinese social media site,

you can find the icon on http://developers.douban.com/wiki/?title=resource

**Comment by MrGrigri** [comment]
Like this?

![douban](https://cloud.githubusercontent.com/assets/4528551/17557772/b667a1c4-5ed5-11e6-96ca-5d57f9962439.png)

[douban.zip](https://github.com/Templarian/MaterialDesign/files/411360/douban.zip)

**Comment by dongweiming** [comment]
@MrGrigri Looks nice!

**Comment by Templarian** [comment]
[![douban](https://materialdesignicons.com/icon/douban)](https://materialdesignicons.com/icon/douban)

**Comment by Templarian** [comment]
By the way @MrGrigri remind me when you hit 5 icons and I'll create an issue to add you as a contributor. :smile: I'm bad at keeping track.

**Comment by dongweiming** [comment]
@Templarian @MrGrigri  Thanks

**Comment by MrGrigri** [comment]
@Templarian, I've only got three contributions thus far...however, there are a couple that have not been added/approved as a contribution. I'm also working on a couple of others

- [x] [Douban](https://github.com/Templarian/MaterialDesign/issues/1394)
- [x] [Section](https://github.com/Templarian/MaterialDesign/issues/1420)
- [x] [Wish](https://github.com/Templarian/MaterialDesign/issues/1363)

I'm unsure of the following

- [ ] [Email Signature](https://github.com/Templarian/MaterialDesign/issues/1341)
- [ ] [Police](https://github.com/Templarian/MaterialDesign/issues/1343)

Let me know if I need to get y'all the .svg/.ai files.

**Comment by CoDEmanX** [comment]
I'm innocent!

![image](https://cloud.githubusercontent.com/assets/1309249/17642747/1dd81346-6153-11e6-99f0-463cb1880094.png)

**Comment by Templarian** [comment]
@CoDEmanX Oops, yea forgot to select my account when uploading. Will fix that when I switch it to his contributor account.
