### ISSUE TITLE
Treasure Chest

### ISSUE THREAD

**Issue by CrawfordK** [Templarian/MaterialDesign#1397]
Money bag, coins, treasure chest, etc

**Comment by Templarian** [comment]
Since we have #338 I'm going rename this to treasure chest to keep it from being a duplicate issue.

**Comment by JapanYoshi** [comment]
Dammit, I can't think of a way to express the roundness of the lid without changing the perspective, which is against Material Design guidelines. :(

**Comment by Templarian** [comment]
Yea, I was sketching something out earlier on a notepad at work. These ones are fun to think through. I think lines on the lid with a nice latch. The trick is to make it not look like a toolbox.

**Comment by JapanYoshi** [comment]
![treasure](https://cloud.githubusercontent.com/assets/8707990/17392499/ca43ee72-5a58-11e6-9b6e-d1be01cbcb8e.png)
This was my first try.

**Comment by CrawfordK** [comment]
Looks pretty legit to me!

**Comment by alexefremo** [comment]
Here's my version

![ic_treasure_chest_black_24px](https://cloud.githubusercontent.com/assets/3408199/18086027/4bebfe4c-6ec7-11e6-8482-346b45aeece9.png)
![ic_treasure_chest_black_48px](https://cloud.githubusercontent.com/assets/3408199/18086026/4bebbe50-6ec7-11e6-829e-6e8f213ca80a.png)
![ic_treasure_chest_black_512px](https://cloud.githubusercontent.com/assets/3408199/18086025/4bea2f40-6ec7-11e6-9cc3-e72a4786164a.png)

**Comment by koppor** [comment]
Coins are adressed in #328 and #1283

**Comment by Templarian** [comment]
[![treasure-chest](https://materialdesignicons.com/icon/treasure-chest)](https://materialdesignicons.com/icon/treasure-chest)

@alexefremo Let me know when you have 5 icons and I'll create a contributor account. Thanks!
