### ISSUE TITLE
Diabetes

### ISSUE THREAD

**Issue by InsanityOnABun** [Templarian/MaterialDesign#1398]
Maybe something like this:
http://icons.iconarchive.com/icons/icons8/windows-8/512/Healthcare-Diabetes-icon.png

Or this:
http://www.patientconnect.co.uk/includes/img/diabetes-icon-case-studies.png

**Comment by Templarian** [comment]
I think the first option would be best and more quickly recognizable at the smaller size.

**Comment by JamesCoyle** [comment]
[![cursor-pointer](https://materialdesignicons.com/icon/cursor-pointer)](https://materialdesignicons.com/icon/cursor-pointer)[![hand-pointing-right](https://materialdesignicons.com/icon/hand-pointing-right)](https://materialdesignicons.com/icon/hand-pointing-right)

Just found these two icons. Might be worth adjusting the cursor one to be like the pointing hand. It fits better with the thumb icons. Then it would be easy enough to add the teardrop shape for this icon.

**Comment by MrGrigri** [comment]
Here's one using the first option. I agree that the bottom will not work. 

![diabetes](https://cloud.githubusercontent.com/assets/4528551/18213316/daac5ebc-7104-11e6-885d-815ecdd68d74.png)

![diabetes 4x](https://cloud.githubusercontent.com/assets/4528551/18213324/e228381e-7104-11e6-9ac5-f97d34918719.png)

[diabetes.zip](https://github.com/Templarian/MaterialDesign/files/452636/diabetes.zip)

**Comment by JamesCoyle** [comment]
Any chance you can do one for the cursor too? Just the hand without a cuff would be great and a variant with a shorter finger would work nicely as `cursor-pointer-clicked`.

**Comment by MrGrigri** [comment]
Like this or did you want the drop of blood as well?

![cursor-pointer-alt](https://cloud.githubusercontent.com/assets/4528551/18214535/b5742908-710a-11e6-8090-3a79e3678299.png)

![cursor-pointer-alt 4x](https://cloud.githubusercontent.com/assets/4528551/18214542/b8d0415e-710a-11e6-9dbd-feafae3d505e.png)

**Comment by JamesCoyle** [comment]
That's perfect. Just brings a more standardised look to the `cursor-pointer` icon if @Templarian will update it.

**Comment by DavidEdwards** [comment]
Or perhaps a mixture of the two...

![diabetes](https://cloud.githubusercontent.com/assets/1585923/19190740/839a79cc-8c9f-11e6-937a-4f22758a76e6.png)

**Comment by iamsarker** [comment]
this is better 
![image](https://user-images.githubusercontent.com/5415001/37705242-8e09cf84-2d25-11e8-897c-f755e5285b78.png)

**Comment by CoDEmanX** [comment]
@iamsarker we need the SVG source file though

**Comment by MrGrigri** [comment]
@CoDEmanX, I believe he's referencing mine from above.

**Comment by CoDEmanX** [comment]
Oh, yeah 😅

**Comment by iamsarker** [comment]
@MrGrigri yes

**Comment by goyney** [comment]
[![diabetes](https://materialdesignicons.com/icon/diabetes)](https://materialdesignicons.com/icon/diabetes)
