### ISSUE TITLE
Skull icon (to indicate "danger" or "kill" action)

### ISSUE THREAD

**Issue by bebenins** [Templarian/MaterialDesign#1399]
I can't find anything suitable for Kill Task icon.
So I thought maybe something like this would be sufficient.

https://www.iconfinder.com/icons/176194/danger_dead_death_kill_killing_poison_skull_icon

**Comment by JapanYoshi** [comment]
Is this Material enough?
![path4153](https://cloud.githubusercontent.com/assets/8707990/17391345/39d2285c-5a50-11e6-840e-b30a19cde9b1.png)
![path4154](https://cloud.githubusercontent.com/assets/8707990/17391346/39d980ca-5a50-11e6-9253-e6c0bb1fdab0.png)

**Comment by Templarian** [comment]
Very material... hmm... it doesn't look quite right due to it being so material.

[![image](https://cloud.githubusercontent.com/assets/338885/17391401/67c8c18c-59db-11e6-8afb-164ad77784b6.png)](https://www.iconfinder.com/icons/1113579/danger_death_poison_skull_icon#size=128)

**Comment by JapanYoshi** [comment]
I based it off the skull icon for the "Sudden Death" icon for the osu! skin HueShift:
![selection-mod-suddendeath 2x](https://cloud.githubusercontent.com/assets/8707990/17391498/81b4dc22-5a51-11e6-9233-fd2cb1f374a6.png)
Not sure how to fix this one IMO, maybe move the eyeholes a bit upward?

**Comment by Templarian** [comment]
Yea, give me a bit; fixing an issue with the site tonight. Will play with a few ideas. This icon was requested in some of the medical icon requests also.

**Comment by JapanYoshi** [comment]
![path4153](https://cloud.githubusercontent.com/assets/8707990/17391651/d644cbd4-5a52-11e6-9058-ebd883c5dfc9.png)
![path4154](https://cloud.githubusercontent.com/assets/8707990/17391650/d632da64-5a52-11e6-9246-fb41a3f20d66.png)

**Comment by Templarian** [comment]
That actually turned out pretty nice just changing those elements a little. I think we can just add it like that. :smile_cat:

**Comment by JapanYoshi** [comment]
Okay, I'm exporting the file:
[skull.zip](https://github.com/Templarian/MaterialDesign/files/400927/skull.zip)

**Comment by Templarian** [comment]
Nice, I've finalized the next release, so this one probably won't make it in, but I'll setup your contributor account this weekend and assign the icons over that you've done so far for this next release.

**Comment by JapanYoshi** [comment]
Thanks a bunch!

**Comment by bebenins** [comment]
Wow thanks for such a quick turnaround guys!

**Comment by Templarian** [comment]
[![skull](https://materialdesignicons.com/icon/skull)](https://materialdesignicons.com/icon/skull)
