### ISSUE TITLE
Child icon

### ISSUE THREAD

**Issue by royale1223** [Templarian/MaterialDesign#14]
An icon for denoting a child, an icon denoting children.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/human-child

**Comment by CoDEmanX** [comment]
Looks like a fat child next to `human-male-female` :sweat_smile: 

I tried to make one that works well with the other one, but it got pretty small: ![human-child](https://cloud.githubusercontent.com/assets/1309249/14770963/86598166-0a7d-11e6-834d-49038dee633b.png)

The full family: ![human-family](https://cloud.githubusercontent.com/assets/1309249/14770964/8b4c73ae-0a7d-11e6-8bbb-ff59cb3cb913.png)

A slightly larger boy (?), not pixel-perfect, but neither is the male human in the Google icon: ![human-child2](https://cloud.githubusercontent.com/assets/1309249/14770967/a1626d56-0a7d-11e6-8bde-c65b5babe542.png)

**Comment by Templarian** [comment]
Agreed it does look like a fat person icon...  I like the full family icon, but may need to add like 3 variations to be politically correct. :sweat_smile:

I like that last one more than the current one we have for `human-child`. Could replace it.

**Comment by CoDEmanX** [comment]
That's exactly what I was thinking! And it's actually worse, we would need male-male-boy, male-male-girl, male-female-boy, male-female-girl, female-female-boy and female-female-girl :see_no_evil: 

Maybe it's better to make it pixel-perfect after all, what do you think?
https://www.dropbox.com/s/155jigh41sjb8zr/human-child2.design?dl=0

**Comment by CoDEmanX** [comment]
Maybe just these three? ![human-family-female-female-child_ 14](https://cloud.githubusercontent.com/assets/1309249/14904418/60f6eac0-0da8-11e6-8c42-93c60bf5d592.png) ![human-family-male-female-child_ 14](https://cloud.githubusercontent.com/assets/1309249/14904419/6110477c-0da8-11e6-8864-2832bf96cf3c.png) ![human-family-male-male-child_ 14](https://cloud.githubusercontent.com/assets/1309249/14904420/611da624-0da8-11e6-8932-ee51bc754ddd.png)

**Comment by Templarian** [comment]
Those 3 look good. Should cover 99% of use cases.
