### ISSUE TITLE
Image Off Icon

### ISSUE THREAD

**Issue by odahcam** [Templarian/MaterialDesign#1400]
An icon to use when an image could not be displayed.

**Comment by Templarian** [comment]
Two icons for this exist already. Let me know if these work, if not do you have an example of what this would look like?

https://materialdesignicons.com/icon/image-broken
https://materialdesignicons.com/icon/image-broken-variant

**Comment by JamesCoyle** [comment]
Those don't really look like images to me...

How about just the image icon with the 'off' line? It could be used as a placeholder when images fail to load as well as a toggle for images in some situations like disabling a background image on a chat window or turning off images to save data on mobile devices.

**Comment by odahcam** [comment]
I tried to make an image icon with the "off line", but the result was not so good as expected. @JamesCoyle described exactly what I'm thinking.

**Comment by odahcam** [comment]
Here is the icon:

``` svg
<svg version="1.1" id="image-off" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24;" xml:space="preserve">
    <path d="M19,3H6.8L21,17.2V5C21,3.9,20.1,3,19,3z"/>
    <path d="M3.3,2L2,3.3l1.1,1.1C3,4.6,3,4.8,3,5v14c0,1.1,0.9,2,2,2h14c0.2,0,0.4,0,0.6-0.1l0.1,0.1l0.3-0.3c0.3-0.2,0.5-0.4,0.6-0.6 l0.3-0.3L3.3,2z M5,18l3.5-4.5l2.5,3l1.9-2.4l3.9,3.9H5z"/>
</svg>
```
I have an AI editable copy too, but I couldn't send it here.

**Comment by Templarian** [comment]
@odahcam Zip will work as attachements. :smile:

**Comment by odahcam** [comment]
Thx @Templarian , here we go: [icons.zip](https://github.com/Templarian/MaterialDesign/files/413910/icons.zip)

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/image-off)](https://materialdesignicons.com/icon/image-off)
