### ISSUE TITLE
Drag and drop icons

### ISSUE THREAD

**Issue by mihnita** [Templarian/MaterialDesign#1402]
The https://materialdesignicons.com site has some (community contributed) icons for drag (search for "drag")
The look like a matrix of dots (sizes: 4x3, 2x5, 5x2)

But these "contradict" the google.com repository of Material Design icons:
   https://design.google.com/icons/#ic_reorder
and the Material Design spec:
    https://material.google.com/components/lists-controls.html#lists-controls-types-of-list-controls
(search for "Reorder", there is no direct link)

===

And is there a way to "mirror" here the icons at https://design.google.com/icons ?
So that we can have a "central, authoritative place" for Material Design icons?

Thank you,
Mihai

**Comment by Templarian** [comment]
We track the syncing of Google icons into this project in #420 (this project existed before Google open sourced their icons so the naming is more noun based here). Would be happy to include the reorder icon (probably with a naming change for vertical/horizontal). I think the dots fit nicer with the idea of moving a panel or object around a grid, so the reorder icons are still needed.

The goal isn't to sync all of the icons, but the ones people find most useful (some Google icons have been replaced by community icons for instance also).

I'll leave this issue opened to track the syncing of the `reorder` icon and the creation of a vertical variant.

**Comment by CoDEmanX** [comment]
@Templarian: there is a reorder icon in one of the icon packs I uploaded a while ago

**Comment by Templarian** [comment]
@CoDEmanX It's 4 rectangles... how will we ever reproduce such a complicated icon. :smirk:

**Comment by CoDEmanX** [comment]
Oh, I should haveb looked at the links in the initial post... I was thinking of what Google uses in Google Keep for reordering, which is 6 circles like for Braille.

**Comment by Templarian** [comment]
Just messing with you anyway. :laughing: Marked it for the next release. Going to keep this next release kind of small as it fixes some bugs. Will focus on the release after that as being a little larger icon count wise.

**Comment by mihnita** [comment]
I think my main complain is really that there is an official guide on how a drag-and-drop icon should look like (4 horizontal lines). And this repository does (1) not have that icon, but instead (2) something that is not "proper style"

Might be nice to go beyond "red rectangle = community contributions" and have (yet another) marker for "official Material Design guide"

===

And (now, that I got started :-) a way to add more than one keyword to an icon would be nice.

On the design.google.com site I can search for drag, and there is nothing. I have to somehow imagine that "order" or "reorder" would give me what I want. And on materialdesignicons.com I search for reorder, and there is nothing.

**Comment by Templarian** [comment]
@mihnita There is an alias system already built in, but there are only 100 or so icons with aliases (search `rupee` for instance bring sup the currency icon, or `search` shows `magnify`).

Yea, to be 100% honest the idea of this community icon pack is provide a few variations of every icon and leave it up to the designer/developer to choose the right icon. For this instance I wouldn't use the reorder icon for dragging a box around a grid... or resizing a panel's separator.

Filter is also an interesting icon (and the stats in the background show many prefer the filter icon) even if the guidelines want one to use the other icon.

**Comment by mihnita** [comment]
@Templarian

> provide a few variations of every icon and leave it up to the designer/developer to choose the right icon

I hear you :-)
But adding a hint saying "BTW, this icon is according to the Material Design guidelines" would help one choose the **right** icon.
Having all applications use the same icon as a handle for reordering items in a list is good for everybody (even if some official apps break the rule :-)

> I wouldn't use the reorder icon ... or resizing a panel's separator
I agree with you. That's why "reorder" is a better name than "drag" :-)
If I remember well, the MD has a recommendation for the resize handle too...

Mihai

**Comment by Templarian** [comment]
[![reorder-horizontal](https://materialdesignicons.com/icon/reorder-horizontal)](https://materialdesignicons.com/icon/reorder-horizontal) [![reorder-vertical](https://materialdesignicons.com/icon/reorder-vertical)](https://materialdesignicons.com/icon/reorder-vertical)

**Comment by CoDEmanX** [comment]
This is what Google uses in the Play Music app:

![image](https://cloud.githubusercontent.com/assets/1309249/17642844/5d17e9de-6156-11e6-9e40-b26fe23b18a6.png)
