### ISSUE TITLE
Indian Rupee symbol icon request

### ISSUE THREAD

**Issue by LOG-TAG** [Templarian/MaterialDesign#1403]
Indian Rupee symbol icon Material Design needed!!

it's not yet available in google Material Design icons ! https://github.com/google/material-design-icons/issues/371

**Comment by Templarian** [comment]
Existed for a while... https://materialdesignicons.com/icon/currency-inr There is also an alias in the search for 'rupee` what did you search for? I can add more aliases to make it easier to find.

**Comment by LOG-TAG** [comment]
aliases Indian rupee, Indian currency , Thanks for the link !
