### ISSUE TITLE
Bottle of soda full, empty and broke

### ISSUE THREAD

**Issue by chuyvad** [Templarian/MaterialDesign#1404]

**Comment by Templarian** [comment]
This is a bit too specific of an icon I'm thinking. Hmm... is there anyway you can use the cup icons?

**Comment by chuyvad** [comment]
Nop, my app manage bottles of soda so i need it.

Saludos

L.C.C. Vadillo León Jesús

**Comment by JapanYoshi** [comment]
I don't know what you mean by "broke", but I'm going to try making the soda bottles.

**Comment by chuyvad** [comment]
Thx. Like a bottle of glass broken

Saludos

L.C.C. Vadillo León Jesús

**Comment by JapanYoshi** [comment]
![path4711](https://cloud.githubusercontent.com/assets/8707990/17391448/2ac70bc4-5a51-11e6-9f84-528b089c3d6d.png)
Is this acceptable?

**Comment by Templarian** [comment]
@JapanYoshi The `off` slash goes the other way (not a big issue since this icon is symmetric).

**Comment by JapanYoshi** [comment]
@Templarian Oh, it's just the way I'm used to writing, seeing, and using it, so thanks for informing me about that info.

![path4711](https://cloud.githubusercontent.com/assets/8707990/17391617/8dc3a8bc-5a52-11e6-9177-858d0362fb39.png)
It looks a little off to me now... Should I shorten the slash?

(Or did you mean the white and black sections?)

**Comment by Templarian** [comment]
Yea, so if you look at some of the others on the site searching `off` you can see we shorten the slash based on how the icon is weighted. In this case it has a narrow top, so shortening it at the top and adding a little length would look more balanced.

**Comment by JapanYoshi** [comment]
![path4711](https://cloud.githubusercontent.com/assets/8707990/17391692/2a598fca-5a53-11e6-9e52-c86c3cb24d09.png)
![path4710](https://cloud.githubusercontent.com/assets/8707990/17391691/2a56cb50-5a53-11e6-9457-9d882d163d49.png)

Like so?

**Comment by Templarian** [comment]
Nah, not that much less. Just maybe a pixel less diagonal on the left side and a half a pixel longer on the right (based on [this one](https://github.com/Templarian/MaterialDesign/issues/1404#issuecomment-237458688)).

**Comment by JapanYoshi** [comment]
![path4711](https://cloud.githubusercontent.com/assets/8707990/17392011/6f681e90-5a55-11e6-9cd5-6ddbb37507ac.png)
![path4710](https://cloud.githubusercontent.com/assets/8707990/17392012/6f6d00b8-5a55-11e6-9db8-28eff62062ec.png)

**Comment by chuyvad** [comment]
All are perfect thx

**Comment by Templarian** [comment]
Nice. @JapanYoshi can I get the zip for these 3 to add.

**Comment by JapanYoshi** [comment]
[Pictures.zip](https://github.com/Templarian/MaterialDesign/files/402870/Pictures.zip)

**Comment by JapanYoshi** [comment]
Have you added these icons?

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #237.

**Comment by JapanYoshi** [comment]
rip me
