### ISSUE TITLE
yandex and yandex box

### ISSUE THREAD

**Issue by mennya** [Templarian/MaterialDesign#1405]

**Comment by ArsenBespalov** [comment]
+1

**Comment by Templarian** [comment]
@mennya @ArsenBespalov Is their logo a Y? I'm looking around for their branding guidelines and can't find them. Looks to be a Russian only service, so I'll assume you two speak Russian and can find either a vector of their logo or a guideline page. 😅 

Will add, but want to see the correct way to represent them in a single symbol (like Google is a G).

**Comment by JapanYoshi** [comment]
@Templarian I'm sure it's a Cyrillic Ya, which looks like a backwards R. [Reference](https://lh3.googleusercontent.com/aGm0ol9zDW_B6ywcckBMOmdIMmLr4qQBdhAA9_gDYwHRuU7nufrFrCFWEYDP0KUuKHg6=w300) [Reference](https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Yandex.svg/2000px-Yandex.svg.png) The logo is indeed a capital Y with an extended right arm in Latin-alphabet environments, but I've seen it represented with the Russian logo far more often.

Sidenote: It seems like VKontakte (ВКонтакте), a mainly Russian-speaking social network, has completely switched their icon from a Cyrillic version to the Latin "VK" by April 2016.

**Comment by mennya** [comment]
Here is the russian and english [logo](http://vectorlogofree.com/wp-content/uploads/2014/07/yandex.ru-vector-logo-free-download.png)
I think a capital Y will be fine.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
