### ISSUE TITLE
Marching Band / Parade

### ISSUE THREAD

**Issue by kmxworks** [Templarian/MaterialDesign#1408]
MUSICIANS!!! DIRECTORS !! PROFESIONS is very important

Icon of parade (one person)

http://www.demoulin.com/media/catalog/product/cache/1/image/1200x1200/9df78eab33525d08d6e5fb8d27136e95/2/0/2008-33D.png

Icon of Marching Band (Multiple persons)

http://media.gettyimages.com/vectors/marchingband-vector-id165497872?k=6&m=165497872&s=170667a&w=0&h=c1DtUgEYpntQ8GxJe5valuupSzo5cDZMnu_VtfJdw1A=

**Comment by JamesCoyle** [comment]
Haha. That's just mean @Templarian :P 

It's not really an easy icon to make in the material style as it would probably need quite a bit more detail than the guidelines allow. Unless someone wants to have a go and manages to get something legible I wouldn't get my hopes up. Inline SVG may be your best option for now.

**Comment by Templarian** [comment]
Ha. Yea, was bored at the office. Renamed the issue though, This is open source... nothing is urgent unless you're giving me beer. :laughing:

**Comment by kmxworks** [comment]
See See ! -> 
[http://www.flaticon.com/free-icon/march_103562#term=parade&page=1&position=3](http://www.flaticon.com/free-icon/march_103562#term=parade&page=1&position=3)

**Comment by kmxworks** [comment]
![imagen1](https://cloud.githubusercontent.com/assets/12957198/18011754/184a5dfc-6b7c-11e6-86a8-17353b6fba5d.png)


like this!!!

**Comment by JamesCoyle** [comment]
I'm gonna close this out as I don't believe there is a good way to show this within the 24dp grid we are constrained to. Thank you for your suggestion!
