### ISSUE TITLE
Icon for "code review" (e.g. gerrit)

### ISSUE THREAD

**Issue by simschla** [Templarian/MaterialDesign#1409]
https://www.gerritcodereview.com

maybe a bird shape for gerrit in specific or something generic representing "code-review"

**Comment by CoDEmanX** [comment]
Maybe the `glasses` icon would work ("proof-reading")?
Or `playlist-check`, as the lines could be interpreted as text in general.

Put this together, not too bad: ![code-review](https://cloud.githubusercontent.com/assets/1309249/17440464/01155e02-5b2d-11e6-8add-5da00b4117d3.png)

**Comment by Templarian** [comment]
@CoDEmanX I like that one. Nice and generic could work for a few uses.

**Comment by CoDEmanX** [comment]
https://dl.dropboxusercontent.com/u/39101475/MaterialDesignIcons/code-review.svg

**Comment by simschla** [comment]
looks awesome!

**Comment by Templarian** [comment]
[![code-tags-check](https://materialdesignicons.com/icon/code-tags-check)](https://materialdesignicons.com/icon/code-tags-check)
