### ISSUE TITLE
bag/purse

### ISSUE THREAD

**Issue by royvergara** [Templarian/MaterialDesign#141]
- [x] Shoe (tennis shoe, dress shoe, high heel)
- [ ] Bag (purse, athletic bag)
- [x] ~~Brands (listing)~~

**Comment by Templarian** [comment]
What is the "Brands (listing)"? If you mean brand logos, only logos that fit and are recognizable at the 24x24 size are being added.

**Comment by royvergara** [comment]
The context would be to communicate that you are navigating to a screen with an alphabetical list of brands. For example what would an icon look like if it were to link you to a page like this http://www.shopbop.com/actions/designerindex/viewAlphabeticalDesigners.action?folderID=2534374302167373

**Comment by Alekhen** [comment]
Removing the cross from the [medical bag](https://materialdesignicons.com/icon/medical-bag) from issue #1313 could work as a purse icon.

![purse](https://cloud.githubusercontent.com/assets/1837101/26474421/4a17c054-416e-11e7-86be-1572246eeb00.png)

 [purse.svg.zip](https://github.com/Templarian/MaterialDesign/files/1030436/purse.svg.zip)

**Comment by Alekhen** [comment]
Here's another option based on the [medical bag](https://materialdesignicons.com/icon/medical-bag) from issue #1313 , but with a taller handle.

<img width="187" alt="purse-alt" src="https://cloud.githubusercontent.com/assets/1837101/26474743/2609d3e4-4170-11e7-9432-ad9094d62e30.png">

[purse-alt.svg.zip](https://github.com/Templarian/MaterialDesign/files/1030448/purse-alt.svg.zip)

**Comment by goyney** [comment]
Preview of @Alekhen's contribution:
![image](https://user-images.githubusercontent.com/1015040/48685590-0ad97000-eb85-11e8-8425-922505480472.png)

**Comment by goyney** [comment]
`purse` and `purse-outline` added. 😄
