### ISSUE TITLE
I want to have icon that indicates exam or test

### ISSUE THREAD

**Issue by s1k3** [Templarian/MaterialDesign#1410]
I want to request an icon which will indicate the start of an exam of quiz

**Comment by CoDEmanX** [comment]
the **start** if an exam? How about `timer` or `clock-start`?

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. If the icons @CoDEmanX suggested don't suit your needs please comment with an example of what you *are* looking for and we will revisit this issue.
