### ISSUE TITLE
Fleet (multiple bus) icon

### ISSUE THREAD

**Issue by ayozebarrera** [Templarian/MaterialDesign#1411]
thanks!

**Comment by MrGrigri** [comment]
How does this look? To do more than one bus in an icon is very difficult. Even with this one I had to go slightly outside 2dpi frame, so the icon is actually 20X23

![fleet](https://cloud.githubusercontent.com/assets/4528551/18212268/77703454-70ff-11e6-8bb8-4b491f6a3aae.png)
![fleet 4x](https://cloud.githubusercontent.com/assets/4528551/18212272/807d4730-70ff-11e6-9ff3-37a91107b446.png)

[fleet.zip](https://github.com/Templarian/MaterialDesign/files/452589/fleet.zip)

**Comment by goyney** [comment]
[![bus-multiple](https://materialdesignicons.com/icon/bus-multiple)](https://materialdesignicons.com/icon/bus-multiple)
