### ISSUE TITLE
rsvp icon

### ISSUE THREAD

**Issue by bmasaiti** [Templarian/MaterialDesign#1412]
an icon for rsvping events

**Comment by CoDEmanX** [comment]
You could use `calendar-check` I guess. Other than that, the only thing that comes to mind is something like this:

![calendar-rsvp](https://cloud.githubusercontent.com/assets/1309249/17440058/3c058da4-5b2b-11e6-8fe4-fc917f0d1453.png)

**Comment by Templarian** [comment]
I think the calendar-check would work for RSVP. But we may want to add the calendar question mark icon.

**Comment by bmasaiti** [comment]
great I this will do it, but maybe needs to be supported by text , Im thinking another option maybe the rsvp word  itself but made into an icon

**Comment by JamesCoyle** [comment]
We never really accept text based icons as they usually don't translate well across languages or cultures.

**Comment by bmasaiti** [comment]
Ooh ok , you're right there

**Comment by CoDEmanX** [comment]
https://dl.dropboxusercontent.com/u/39101475/MaterialDesignIcons/calendar-rsvp.svg

**Comment by Templarian** [comment]
[![calendar-question](https://materialdesignicons.com/icon/calendar-question)](https://materialdesignicons.com/icon/calendar-question)

Alias: `calendar-rsvp`
