### ISSUE TITLE
permissions icon

### ISSUE THREAD

**Issue by vishnu1991** [Templarian/MaterialDesign#1413]
icon for permission

**Comment by CoDEmanX** [comment]
What kind of permission?

Please post some reference pictograms.

**Comment by vishnu1991** [comment]
![lock-icon](https://cloud.githubusercontent.com/assets/6689768/17445195/54c7a12a-5b61-11e6-99b1-628434a672eb.png)
like this

**Comment by CoDEmanX** [comment]
We already have two padlocks:

[![lock-outline](https://materialdesignicons.com/icon/lock-outline)](https://materialdesignicons.com/icon/lock-outline) [![lock](https://materialdesignicons.com/icon/lock)](https://materialdesignicons.com/icon/lock)

**Comment by JamesCoyle** [comment]
The Play store uses the shield icon
[![shield](https://materialdesignicons.com/icon/shield)](https://materialdesignicons.com/icon/shield)

**Comment by vishnu1991** [comment]
ok thanks!
