### ISSUE TITLE
Rupee icon

### ISSUE THREAD

**Issue by kmkarti** [Templarian/MaterialDesign#1415]
Indian rupee icon

**Comment by JamesCoyle** [comment]
Pretty sure this is the third request this week. Does it not come up if you search 'rupee'?

**Comment by CoDEmanX** [comment]
The alias is `rupee`, but if you search for `rupees`, it does obviously not find it. Upper-case letters do not work in general, so `Rupee` doesn't find it either.

[![currency-inr](https://materialdesignicons.com/icon/currency-inr)](https://materialdesignicons.com/icon/currency-inr)

**Comment by Templarian** [comment]
I'll try and fix some of this search issues this weekend. Yea, it's been happening a lot for this one icon.

**Comment by Templarian** [comment]
Fixed the search to ignore case. I assume they were searching for "Rupee" instead of lowercase.
