### ISSUE TITLE
a patient

### ISSUE THREAD

**Issue by Goniek** [Templarian/MaterialDesign#1416]
If possible could someone create a patient icon? Thank you.

**Comment by CoDEmanX** [comment]
Reminds me of #1147...

**Comment by Goniek** [comment]
Hi,

Not exactly what they are discussing. I meant more like the one attached but in material style. Thank you so much for responding.


[cid:e701d6ef-21fa-4b2c-9729-021fb4f507a2]


________________________________

**Comment by CoDEmanX** [comment]
Email attachments are not supported by GitHub, please paste/upload reference images via the website.

**Comment by alexefremo** [comment]
Maybe like this?

![ic_patient1_black_24px](https://cloud.githubusercontent.com/assets/3408199/18118027/cf784b72-6f6b-11e6-8e86-577a86f76b77.png)
![ic_patient1_black_48px](https://cloud.githubusercontent.com/assets/3408199/18118028/cf964668-6f6b-11e6-9d24-b40d88f5ff7b.png)
![ic_patient2_black_24px](https://cloud.githubusercontent.com/assets/3408199/18118030/cfae6072-6f6b-11e6-84f6-35ec008be60a.png)
![ic_patient2_black_48px](https://cloud.githubusercontent.com/assets/3408199/18118029/cfad3aa8-6f6b-11e6-8b74-ac13f7d2dd99.png)

**Comment by Goniek** [comment]
Hi Alex,

I really like them all. Does it mean that this icon could be available as font? Same way as the original material design icons are created?

Also, what are the rights to use it?
Thank you
Gosia


________________________________

**Comment by alexefremo** [comment]
you can have an SVG. it's free for use as i understand. as for font - dunno.

[icons.zip](https://github.com/Templarian/MaterialDesign/files/447158/icons.zip)

**Comment by JamesCoyle** [comment]
@Goniek when this icon is added you can download the webfont from https://materialdesignicons.com/ by clicking the download button in the upper right.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history Releases are generally every month to 2 months. So it might be a while until it is in the webfont since we just did a release.

**Comment by goyney** [comment]
I feel this are too specific. A patient is a person and that could have many ailments that don't manifest themselves physically. In that case, any of the `account-` icons could represent a patient in the proper context. I don't feel there is something here worth adding.

**Comment by goyney** [comment]
After a little bit of internal discussion, we're going to close this issue. If anyone comes up with some other ideas for how to represent a patient, please feel free to create a new issue with your ideas. Thanks for the suggestion!

**Comment by goyney** [comment]
Looks like Google came up with a solution for this, these have been added.

[![account-injury](https://materialdesignicons.com/icon/account-injury)](https://materialdesignicons.com/icon/account-injury)[![account-injury-outline](https://materialdesignicons.com/icon/account-injury-outline)](https://materialdesignicons.com/icon/account-injury-outline)
