### ISSUE TITLE
a drug / pill icon

### ISSUE THREAD

**Issue by Goniek** [Templarian/MaterialDesign#1417]
Could someone please create a pill as in pharmacy icon ? Thank you.

**Comment by MrGrigri** [comment]
How about one of these:

![pill_1](https://cloud.githubusercontent.com/assets/4528551/17446605/42585d36-5b07-11e6-9d5f-c46ba83aa35f.png)


![pill_2](https://cloud.githubusercontent.com/assets/4528551/17446604/42531dee-5b07-11e6-87cc-eb48d47984bd.png)

**Comment by CoDEmanX** [comment]
We already have `pill` and `pharmacy`:

[![pill](https://materialdesignicons.com/icon/pill)](https://materialdesignicons.com/icon/pill) [![pharmacy](https://materialdesignicons.com/icon/pharmacy)](https://materialdesignicons.com/icon/pharmacy)

Are they sufficient?

**Comment by Goniek** [comment]
That is great! I haven't seen those. Thank you very much.


________________________________

**Comment by Goniek** [comment]
Someone already pointed out that one already exist.

[cid:30afa6b9-d286-4a75-b2e7-fa5ec640b029]

Thank you very much for responding.


Gosia


________________________________
