### ISSUE TITLE
Goodreads icon

### ISSUE THREAD

**Issue by roshdlostgeek** [Templarian/MaterialDesign#1418]

**Comment by JamesCoyle** [comment]
We don't really accept brand icons unless they are well known social networks. I don't think good reads is broad enough or even really has a recognizable icon we could use.

**Comment by Templarian** [comment]
[![goodreads](https://materialdesignicons.com/icon/goodreads)](https://materialdesignicons.com/icon/goodreads)

After reevaluation this brand has been included.
