### ISSUE TITLE
School Bus Icon - side view

### ISSUE THREAD

**Issue by sykorax** [Templarian/MaterialDesign#1419]
would be nice :)

**Comment by alexefremo** [comment]
![ic_schoolbus_black_24px](https://cloud.githubusercontent.com/assets/3408199/18195187/b04469e0-7103-11e6-8543-a77db4158454.png)
![ic_schoolbus_black_48px](https://cloud.githubusercontent.com/assets/3408199/18195188/b0452862-7103-11e6-8a9e-0fe2fe8c5108.png)
![ic_schoolbus_black_128px](https://cloud.githubusercontent.com/assets/3408199/18195186/b043dfe8-7103-11e6-9ba3-a7a45a16e571.png)

**Comment by Templarian** [comment]
@alexefremo forgot to attach the file.

**Comment by GreenTurtwig** [comment]
North American school bus to match the regular style:
![](https://puu.sh/vEC15.png)
![](https://puu.sh/vEC29.png)
[bus-school.zip](https://github.com/Templarian/MaterialDesign/files/974627/bus-school.zip)

**Comment by Templarian** [comment]
[![bus-school](https://materialdesignicons.com/icon/bus-school)](https://materialdesignicons.com/icon/bus-school)
