### ISSUE TITLE
Section sign (§)

### ISSUE THREAD

**Issue by bradmont** [Templarian/MaterialDesign#1420]
I'd find a section sign (§) helpful. Thanks for all the great icons!

**Comment by MrGrigri** [comment]
Here's a quick example. 

![section](https://cloud.githubusercontent.com/assets/4528551/17556665/76dc67c8-5ed1-11e6-8fa0-2a721d93f6b0.png)
[section.zip](https://github.com/Templarian/MaterialDesign/files/411268/section.zip)

**Comment by Templarian** [comment]
I named it `format` section I assume it mainly will be used in terms of text.

[![format-section](https://materialdesignicons.com/icon/format-section)](https://materialdesignicons.com/icon/format-section)
