### ISSUE TITLE
Add JapanYoshi as Contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1421]
- [x] Add @JapanYoshi as a contributor.
- [x] Get details for contributor page on the site (twitter, name, photo).
- [ ] Assign all icons to contributor.

Which icons did you submit I'm going to assign them all over to your new account. Also, name and other details you would like on the site (I just put a placeholder name / text)? Most just use their photos or company logos.

https://materialdesignicons.com/contributor/JapanYoshi

**Comment by JapanYoshi** [comment]
Aside from the ones already attributed to me, [plastic bottles](https://github.com/Templarian/MaterialDesign/issues/1404), [metronome](https://github.com/Templarian/MaterialDesign/issues/1344#issuecomment-235729319), [tire](https://github.com/Templarian/MaterialDesign/issues/1308#issuecomment-235729431), and [hammer](https://github.com/Templarian/MaterialDesign/issues/1308#issuecomment-235729431). Plastic bottles are the only ones with your approval, though.
