### ISSUE TITLE
Linux Distributions

### ISSUE THREAD

**Issue by mappu** [Templarian/MaterialDesign#1422]
Hi,

Ubuntu is present. But, not other Linux distributions or other Free operating systems.

I would suggest
- [x] Arch
- [x] Debian
- [x] Fedora
- [x] Mint
- [x] Gentoo
- [x] Slackware
- [x] FreeBSD
- [ ] Haiku
- [ ] OpenBSD
- [ ] CentOS
- [ ] RHEL

Thanks

**Comment by Templarian** [comment]
Unfortunately some of these icons will not look good at 24x24, but we'll go through the list and see which work and which will not. But I'm fine adding the ones that look good or can be modified to a variant that will work.

**Comment by GreenTurtwig** [comment]
Would it be better to have them in a circle like the Ubuntu icon or just standalone?

**Comment by Templarian** [comment]
Standalone due to the 20 square area already being small.

**Comment by GreenTurtwig** [comment]
Here's Arch. :cat2:
[arch.zip](https://github.com/Templarian/MaterialDesign/files/415474/arch.zip)

**Comment by GreenTurtwig** [comment]
Gentoo
[gentoo.zip](https://github.com/Templarian/MaterialDesign/files/415505/gentoo.zip)

**Comment by GreenTurtwig** [comment]
Haiku seems to only have a text based logo, only way I could see that being turned into an icon is if the icon was a feather. :-/  
OpenBSD won't look good at 24x24 in my opinion, same with Red Hat and CentOS.  
:cat2:

**Comment by CoDEmanX** [comment]
Both icons contain "rchlinux" outside the canvas, this needs to be removed before adding.

**Comment by GreenTurtwig** [comment]
Ahh. :-P  
I'll put the new versions of them in a zip with the other ones later then. :-)

**Comment by GreenTurtwig** [comment]
Arch, Debian, Fedora, FreeBSD, Gentoo, Linux Mint and Slackware. :smile_cat: 
![puush-linux 2016-08-13 at 07 50 03](https://cloud.githubusercontent.com/assets/15905797/17644965/32032d9c-618f-11e6-91b5-f25a2df589dc.png)

[linux-icons.zip](https://github.com/Templarian/MaterialDesign/files/416719/linux-icons.zip)

**Comment by mappu** [comment]
Great work!

Looking at the website favicon for each operating system, i think i agree CentOS + OpenBSD will not look clear at 24x24 (also the same problem has SUSE/OpenSUSE).

**Comment by mappu** [comment]
For SVG i'm amateur. But here's Red Hat logo in black+white SVG [redhat_modified.zip](https://github.com/Templarian/MaterialDesign/files/416804/redhat_modified.zip)

with 24x24 preview:

![g3370](https://cloud.githubusercontent.com/assets/3959202/17646131/f95ee00e-620f-11e6-9675-e8bd637a889f.png)

derived from https://en.wikipedia.org/wiki/File:RedHat.svg . It's good to be accurate, but, i think the detailing is too small. It could maybe simplified by removing the top-most shading in the hat.

**Comment by JamesCoyle** [comment]
@GreenTurtwig For Haiku I think the green feather on their logo may be a good option. 

@mappu Perhaps if you could just extract the hat and align it to the grid better it would be clearer at 24x24. 

I've checked off the icons that have currently been contributed so it is clearer what still needs work though I'd suggest that @Templarian just close the issue after adding the current contributions. If there haven't been any contributions by then I doubt there ever will be. We've got the main ones anyway.

**Comment by GreenTurtwig** [comment]
Yeah, I'll have a go. Will probably have to tilt it horizontally. :-)

**Comment by jhonatandarosa** [comment]
![centos](https://cloud.githubusercontent.com/assets/5197201/22254083/c6a58108-e23a-11e6-94dd-f78b9edc4ebd.png)
centos.svg
[centos.zip](https://github.com/Templarian/MaterialDesign/files/727117/centos.zip)

**Comment by jhonatandarosa** [comment]
![haiku](https://cloud.githubusercontent.com/assets/5197201/22260222/8d7b17a2-e24f-11e6-8cd5-a41094119753.png)
haiku.svg
[haiku.zip](https://github.com/Templarian/MaterialDesign/files/727548/haiku.zip)

**Comment by jhonatandarosa** [comment]
![openbsd](https://cloud.githubusercontent.com/assets/5197201/22260566/d95feb2e-e250-11e6-9f0f-29984fa83820.png)
openbsd.svg
[openbsd.zip](https://github.com/Templarian/MaterialDesign/files/727570/openbsd.zip)

**Comment by jhonatandarosa** [comment]
![rhel](https://cloud.githubusercontent.com/assets/5197201/22260587/e865de62-e250-11e6-824b-9bda2cd1e911.png)
rhel.png
[rhel.zip](https://github.com/Templarian/MaterialDesign/files/727573/rhel.zip)

**Comment by visualpharm** [comment]
Here we go:

We've got FreeBSD
![free bsd-24](https://cloud.githubusercontent.com/assets/5383670/25546640/90732e76-2c29-11e7-85de-dec09883326d.png)
[Free BSD.svg.zip](https://github.com/Templarian/MaterialDesign/files/965527/Free.BSD.svg.zip)




SUSE

**Comment by visualpharm** [comment]
We've got also something that you didn't request directly: [SUSE](https://icons8.com/web-app/33535/suse) and [Manrdiva](https://icons8.com/web-app/33532/mandriva). Please let me know if you want it.

**Comment by Templarian** [comment]
[![freebsd](https://materialdesignicons.com/icon/freebsd)](https://materialdesignicons.com/icon/freebsd) [![gentoo](https://materialdesignicons.com/icon/gentoo)](https://materialdesignicons.com/icon/gentoo)

**Comment by Templarian** [comment]
[![arch](https://materialdesignicons.com/icon/arch)](https://materialdesignicons.com/icon/arch) [![debian](https://materialdesignicons.com/icon/debian)](https://materialdesignicons.com/icon/debian)

If someone can please cleanup the debian logo that would be a huge help. So many points that are not visible at the smaller sizes.

**Comment by Templarian** [comment]
[![slackware](https://materialdesignicons.com/icon/slackware)](https://materialdesignicons.com/icon/slackware) [![linux-mint](https://materialdesignicons.com/icon/linux-mint)](https://materialdesignicons.com/icon/linux-mint) [![fedora](https://materialdesignicons.com/icon/fedora)](https://materialdesignicons.com/icon/fedora)

Please create issues for red-hat and others. We need much lower point count for these to be included (almost didn't include debian for this reason, this needs to be fixed).
