### ISSUE TITLE
Nuke Icon

### ISSUE THREAD

**Issue by SeyoS** [Templarian/MaterialDesign#1423]
A nuke icon (like a nuclear explosion) is really missing !

That will be great to display beside a fatal error ;)

**Comment by GreenTurtwig** [comment]
How's this?  
![puush-linux 2016-08-08 at 05 54 36](https://cloud.githubusercontent.com/assets/15905797/17488438/5a6fefe2-5d91-11e6-87f3-8e8db64c503b.png)
[nuke.zip](https://github.com/Templarian/MaterialDesign/files/407294/nuke.zip)

**Comment by JamesCoyle** [comment]
Rad-ical. There's not mushroom for improvement there. It's the bomb!

**Comment by SeyoS** [comment]
Nice. I was thinking about something like this:
http://st2.depositphotos.com/1874273/7223/v/950/depositphotos_72236597-Mushroom-cloud-nuclear-explosion-icon.jpg

It's true that's it is not as readable as I thought it would be....

**Comment by GreenTurtwig** [comment]
@JamesCoyle THE PUNS! :joy_cat: 
@SeyoS Well hopefully this is goof enough :-)

**Comment by Templarian** [comment]
[![nuke](https://materialdesignicons.com/icon/nuke)](https://materialdesignicons.com/icon/nuke)

Slightly modified for the smaller 24x24 size.

**Comment by CoDEmanX** [comment]
The horizontal line looks off grid?
