### ISSUE TITLE
Pokémon GO icons

### ISSUE THREAD

**Issue by anjocerdena** [Templarian/MaterialDesign#1424]
Contributing Pokéstop and Pokémon Gym icons created from scratch based on Pokémon GO. Also made "add" varieties for use in mapping projects.

[Pokémon GO icons.zip](https://github.com/Templarian/MaterialDesign/files/411396/Pokemon.GO.icons.zip)

**Comment by JamesCoyle** [comment]
I personally wouldn't add these as they are very specific and would better lend themselves to inline SVG. Will have to see what @Templarian decides though.

**Comment by Templarian** [comment]
Agreed. We've had a [pokeball](https://materialdesignicons.com/icon/pokeball) for a while though.

**Comment by Templarian** [comment]
They are nice icons though @anjocerdena! Share them on twitter or host them somewhere. People may find them useful for their 3rd party pokemon apps.
