### ISSUE TITLE
queue of people

### ISSUE THREAD

**Issue by costa-xdaniel** [Templarian/MaterialDesign#1425]
fila de pessoas com três a cinco pessoas

**Comment by MrGrigri** [comment]
For those that don't speak Portuguese, @danie555costa said, "A line of people with three to five people."

I might add, that might be a bit complex for a 24x24 pixel icon. [Portuguese: Devo acrescentar, que pode ser um pouco complexo para um ícone de 24 por 24 pixels.]

**Comment by MrGrigri** [comment]
I'm going to close this one.

[PQ: Eu vou terminar esse questão]
