### ISSUE TITLE
Historic icon

### ISSUE THREAD

**Issue by cinemidia** [Templarian/MaterialDesign#1428]

**Comment by JamesCoyle** [comment]
Can you provide examples?

**Comment by GreenTurtwig** [comment]
Maybe something like:
![103348-200](https://cloud.githubusercontent.com/assets/15905797/17595255/2918eef8-5fe4-11e6-8f25-2758a1c2aaac.png)

**Comment by GreenTurtwig** [comment]
Here: 
[pillar.zip](https://github.com/Templarian/MaterialDesign/files/417131/pillar.zip)
I found a pillar worked the best. :-)
![puush-linux 2016-08-14 at 05 59 34](https://cloud.githubusercontent.com/assets/15905797/17650575/f7614d08-6248-11e6-9f85-97a3d5d92ead.png)
![puush-linux 2016-08-14 at 05 59 52](https://cloud.githubusercontent.com/assets/15905797/17650576/f880afc6-6248-11e6-894a-8410475fe9b8.png)

**Comment by CoDEmanX** [comment]
I tried something curly, but the canvas is simply too small. I like your approach!

**Comment by GreenTurtwig** [comment]
Thanks. :-)  
It's simple, but everything else I tried just wouldn't fit well.

**Comment by CoDEmanX** [comment]
I like it a bit better with the rounded rectangle in the middle. Shouldn't make much of a difference at normal scale, but I think it gives it a better look at larger scales.

**Comment by GreenTurtwig** [comment]
Gave the second bar rounded corners. :+1: 
[pillar.zip](https://github.com/Templarian/MaterialDesign/files/440786/pillar.zip)

**Comment by Templarian** [comment]
Aliased `historic`.

[![pillar](https://materialdesignicons.com/icon/pillar)](https://materialdesignicons.com/icon/pillar)
