### ISSUE TITLE
place-setting

### ISSUE THREAD

**Issue by exodan** [Templarian/MaterialDesign#1429]
Can we have:
- [x] Knife and fork - `silverware-fork-knife`
- [x] Knife and fork crossed - `silverware-variant`
- [ ] Knife, fork and plate
- [x] Bowl with spoon - `bowl`
- [x] Bowl with chopsticks - `rice`
- [ ] Fried egg - #2944
- [x] Croissant - `food-croissant`

**Comment by GreenTurtwig** [comment]
There is already a bowl with "spoon" icon: https://materialdesignicons.com/icon/bowl  
Google has crossed knife and spoon and knife and fork icons but haven't been added to MDI yet.

**Comment by Templarian** [comment]
The `silverware-*` icons (4 of them) exist.

**Comment by CoDEmanX** [comment]
We are lacking the restaurant icon though (fork + knife): https://design.google.com/icons/#ic_restaurant

**Comment by alexefremo** [comment]
What would you say about such croissant?

![ic_croissant_black_24px](https://cloud.githubusercontent.com/assets/3408199/18084903/5c239bc6-6ec2-11e6-93ae-c1be68027ccf.png)
![ic_croissant_black_48px](https://cloud.githubusercontent.com/assets/3408199/18084905/5c246dc6-6ec2-11e6-9256-8aeb9a892128.png)
![ic_croissant_black_512px](https://cloud.githubusercontent.com/assets/3408199/18084904/5c243d24-6ec2-11e6-994b-17e0be5494ac.png)

**Comment by exodan** [comment]
Looks good, but not sure it would be immediately clear what it's supposed to be. Maybe if it was more curved it would be better.

**Comment by alexefremo** [comment]
And if we try this way? 


![ic_croissant_black_24px](https://cloud.githubusercontent.com/assets/3408199/18085671/8e5cce66-6ec5-11e6-9762-291b8af4e26d.png)
![ic_croissant_black_48px](https://cloud.githubusercontent.com/assets/3408199/18085669/8e57c93e-6ec5-11e6-826d-d52c5c0e12c3.png)
![ic_croissant_black_512px](https://cloud.githubusercontent.com/assets/3408199/18085670/8e58af02-6ec5-11e6-9116-0dfc67f7406b.png)

**Comment by exodan** [comment]
Looks good, thanks!

**Comment by alexefremo** [comment]
You're welcome. Need an SVG?

**Comment by exodan** [comment]
Could be useful yeah.

**Comment by alexefremo** [comment]
Here
[ic_croissant_black.zip](https://github.com/Templarian/MaterialDesign/files/444584/ic_croissant_black.zip)

**Comment by exodan** [comment]
Thanks again!

**Comment by GreenTurtwig** [comment]
Looks great, at a smaller size it reminds me of an Nvidia Shield controller though. :-P

**Comment by visualpharm** [comment]
Hi there, here we go with everything missing but boiled egg. I've also thrown some extra ones.
![Food Icons by Icons8](https://cloud.githubusercontent.com/assets/5383670/25548807/eb1b275c-2c33-11e7-84b2-15622762e3f8.png)

[icons8 food icons material.zip](https://github.com/Templarian/MaterialDesign/files/965648/icons8.food.icons.material.zip)

If you guys some [more food icons](https://icons8.com/web-app/category/androidL/Food), we'd like to donate them.

**Comment by Templarian** [comment]
[![food-croissant](https://materialdesignicons.com/icon/food-croissant)](https://materialdesignicons.com/icon/food-croissant)

Marked the issue as high priority to get some of these others added.

**Comment by goyney** [comment]
The only thing missing for the original list is a place setting (fork, knife, plate). Updating issue to reflect that.

**Comment by goyney** [comment]
[![silverware-fork-knife](https://materialdesignicons.com/icon/silverware-fork-knife)](https://materialdesignicons.com/icon/silverware-fork-knife)

Alias of `place-setting` added.
