### ISSUE TITLE
Sport Icons

### ISSUE THREAD

**Issue by daallgeier** [Templarian/MaterialDesign#1430]
* climbing
* surfing
* skiing
* golf
* ...

**Comment by GreenTurtwig** [comment]
Google Fit seems to have all of these icons, and @CoDEmanX even asked about them: https://github.com/google/material-design-icons/issues/167 .  
But it seems like they haven't been officially added by Google yet. :crying_cat_face:

**Comment by JamesCoyle** [comment]
I believe we are still waiting on permission for use: 
https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-122299730

**Comment by CoDEmanX** [comment]
The problem is that the Google Fit icons were designed for a smaller grid of 18x18 pixels AFAIK.

**Comment by gabrielgrant** [comment]
@CoDEmanX According to [this page](https://lunarsaloon.com/work/google-iconography/) they were designed for 16x16
