### ISSUE TITLE
Home Icon

### ISSUE THREAD

**Issue by awadeyar** [Templarian/MaterialDesign#1432]
Hi,

Please make the home like this 
![home_tab](https://cloud.githubusercontent.com/assets/12082080/17613510/e755b030-607b-11e6-9bb9-7eb0ed0891f6.png)

Thanks and Regards,
Wadeyar

**Comment by Templarian** [comment]
[![home-outline](https://materialdesignicons.com/icon/home-outline)](https://materialdesignicons.com/icon/home-outline)
