### ISSUE TITLE
Slope icon request

### ISSUE THREAD

**Issue by dgngulcan** [Templarian/MaterialDesign#1433]
I have slope attribute in my app that I show with ascend descend information and couldn't find a slope icon that fits with material design.
That would be cool!
Sincerely

**Comment by JamesCoyle** [comment]
So just something like a right angle triangle aligned to the bottom of the icon?

**Comment by dgngulcan** [comment]
exactly @JamesCoyle

**Comment by CoDEmanX** [comment]
https://youtu.be/iNCuCo-AWwE comes to mind :D

**Comment by MrGrigri** [comment]
Here's an idea. Typically slope is determined by and show with a percentage marking. 10% is very common. 

![slope](https://cloud.githubusercontent.com/assets/4528551/18140678/ceb0b3a2-6f73-11e6-964d-b6924707f339.png)
![slope 4x](https://cloud.githubusercontent.com/assets/4528551/18140676/cea63a58-6f73-11e6-8bec-6e94a48e0c1e.png)

[slope.zip](https://github.com/Templarian/MaterialDesign/files/447973/slope.zip)

**Comment by JamesCoyle** [comment]
Perhaps we could have a blank one and a couple of common variants. `slope-uphill`, `slope-uphill-10`, `slope-downhill` etc.

**Comment by MrGrigri** [comment]
### Ok, so I've done four variants. [slope.zip](https://github.com/Templarian/MaterialDesign/files/448090/slope.zip)

| slope-uphill  	| slope-downhill  	| slope-uphill-10  	| slope-downhill-10  	|
|---	|---	|---	|---	|
| ![slope-uphill](https://cloud.githubusercontent.com/assets/4528551/18142763/439b20be-6f7c-11e6-9ced-5396eee97f3e.png)  	| ![slope-downhill](https://cloud.githubusercontent.com/assets/4528551/18142820/73e10b8a-6f7c-11e6-87e5-7d7916e2fbb2.png)  	| ![slope-uphill-10](https://cloud.githubusercontent.com/assets/4528551/18142969/30f01fae-6f7d-11e6-97a0-d7150db41305.png)  	| ![slope-downhill-10](https://cloud.githubusercontent.com/assets/4528551/18142991/42cbd330-6f7d-11e6-89c5-df42715e53e0.png)  	|
| ![slope-uphill 4x](https://cloud.githubusercontent.com/assets/4528551/18142764/43b292b2-6f7c-11e6-8879-cf923a214621.png)  	| ![slope-downhill 4x](https://cloud.githubusercontent.com/assets/4528551/18142821/73e8d39c-6f7c-11e6-83e7-6acd85528f5e.png)  	| ![slope-uphill-10 4x](https://cloud.githubusercontent.com/assets/4528551/18142970/310b590e-6f7d-11e6-9304-1e1fe9da9202.png)  	| ![slope-downhill-10 4x](https://cloud.githubusercontent.com/assets/4528551/18142990/42cb94b0-6f7d-11e6-99fd-ab8289f11167.png)  	|

**Comment by dgngulcan** [comment]
Thank you a lot @MrGrigri ! They look great!

**Comment by Templarian** [comment]
Okay, I think the `10%` grade might be a tad too niche, but the slope up/down seem fine.

[![slope-uphill](https://materialdesignicons.com/icon/slope-uphill)](https://materialdesignicons.com/icon/slope-uphill) [![slope-downhill](https://materialdesignicons.com/icon/slope-downhill)](https://materialdesignicons.com/icon/slope-downhill)
