### ISSUE TITLE
Roof icon

### ISSUE THREAD

**Issue by hisbvdis** [Templarian/MaterialDesign#1434]
Simple icon

![_318-28785](https://cloud.githubusercontent.com/assets/5147554/17642103/5a8e758e-6142-11e6-8d88-6fa40c82a82b.jpg)

**Comment by tarbax** [comment]
yes i want that

**Comment by goyney** [comment]
[![home-roof](https://materialdesignicons.com/icon/home-roof)](https://materialdesignicons.com/icon/home-roof)
