### ISSUE TITLE
Bot icon request

### ISSUE THREAD

**Issue by vishnu1991** [Templarian/MaterialDesign#1435]

**Comment by vishnu1991** [comment]
![robot_icon](https://cloud.githubusercontent.com/assets/6689768/17645751/2af2ca52-61cc-11e6-9af8-2dc741ecd6c4.jpg)
Something like this!

**Comment by GreenTurtwig** [comment]
How's this? :smile_cat: 
![puush-linux 2016-08-14 at 05 01 35](https://cloud.githubusercontent.com/assets/15905797/17650256/175513e0-6241-11e6-92f1-e3a7fb0b37c5.png)
![puush-linux 2016-08-14 at 05 04 05](https://cloud.githubusercontent.com/assets/15905797/17650258/265b5a52-6241-11e6-9af9-e88a24fa74a3.png)
[bot.zip](https://github.com/Templarian/MaterialDesign/files/417098/bot.zip)

**Comment by vishnu1991** [comment]
Cool ! 👍

**Comment by JamesCoyle** [comment]
It's best to leave these open so we can close them as they are added.

**Comment by Templarian** [comment]
[![robot](https://materialdesignicons.com/icon/robot)](https://materialdesignicons.com/icon/robot)
