### ISSUE TITLE
Increase Icons tags for better search

### ISSUE THREAD

**Issue by fhedayat** [Templarian/MaterialDesign#1436]
Hello
Search each icons very hard.
Please Increase each icon tags to make searching easier.

**Comment by JamesCoyle** [comment]
This is something that is being worked on. We do have an alias system which allows icons to have multiple names to make searching easier. An example of this is `rupee` which when searched for brings up the `currency-inr` icon. 

@Templarian It might be worth allowing icons to actually have different names in the CSS too so `mdi-rupee` would actually show the `mdi-currency-inr` icon.

**Comment by Templarian** [comment]
@JamesCoyle I really want to prevent CSS bloat, so will probably never being adding alias names to the CSS classes (there are already going to be 1700+ unique class names in the next release).

Yea, tagging will be a larger push after this next release. Going to close this as there are other issues in the backlog and it's more of an ongoing improvement.
