### ISSUE TITLE
Icon Request: instagram-box

### ISSUE THREAD

**Issue by Jonas-Drotleff** [Templarian/MaterialDesign#1438]
Most social media icons have a box version: facebook-box, twitter-box etc.

**Comment by Templarian** [comment]
Instagram is a box though, putting it into another box looks really odd at the small 24x24 size.

![24](https://cloud.githubusercontent.com/assets/338885/17650818/10e9fd0a-621d-11e6-90bb-015854ac8613.png) ![48](https://cloud.githubusercontent.com/assets/338885/17650822/2017872a-621d-11e6-8f79-191167088ca8.png)
