### ISSUE TITLE
3G and 4G icon request

### ISSUE THREAD

**Issue by vishnu1991** [Templarian/MaterialDesign#1439]

**Comment by onlinewebfonts** [comment]
Too much trouble, you can download this free svg icon.
https://www.onlinewebfonts.com/icon/

**Comment by GreenTurtwig** [comment]
https://puu.sh/qCn4r.png  
I might have a go at making 2G, HSPA and HSPA+ icons too.

**Comment by vishnu1991** [comment]
Thanks!

**Comment by vishnu1991** [comment]
@Templarian  please add these icons to the website.
Thanks!

**Comment by Templarian** [comment]
@vishnu1991 Please don't close issues until the icon is approved and included. Thanks.

**Comment by vishnu1991** [comment]
Oh ! sorry. I'll make sure next time!

**Comment by GreenTurtwig** [comment]
Done 2G, 3G, 4G, HSPA and HSPA+  
[mobile-data.zip](https://github.com/Templarian/MaterialDesign/files/418764/mobile-data.zip)

**Comment by CoDEmanX** [comment]
Hm, it's a text based icon, but since there are plans to also provide an alpha numeric font, maybe it can be added there?

**Comment by GreenTurtwig** [comment]
That might be a good idea. I don't think there's any other way to show mobile data connections.

**Comment by JamesCoyle** [comment]
Does text based really matter in this situation? It's not really possible to represent it without text. I feel like a two character maximum is pretty acceptable.

**Comment by Templarian** [comment]
In this situation it's globally recognized I believe, so it should be fine. Usually the text rule just applies to English words.

**Comment by CoDEmanX** [comment]
Well, depends. In German it is very uncommon to call it 2G, 3G and 4G. They are rather called GPRS/EDGE, UMTS/HSPA and LTE. On my Android phone, the signal strength indicator shows the appropriate letters (G, E, H, LTE, R = roaming).

**Comment by Templarian** [comment]
I've added the 5 icons (2G, 3G, 4G, HSPA and HSPA+). Lets wait and see if anyone requests the others.

[![signal-2g](https://materialdesignicons.com/icon/signal-2g)](https://materialdesignicons.com/icon/signal-2g) [![signal-3g](https://materialdesignicons.com/icon/signal-3g)](https://materialdesignicons.com/icon/signal-3g) [![signal-4g](https://materialdesignicons.com/icon/signal-4g)](https://materialdesignicons.com/icon/signal-4g) [![signal-hspa](https://materialdesignicons.com/icon/signal-hspa)](https://materialdesignicons.com/icon/signal-hspa-plus) [![signal-hspa](https://materialdesignicons.com/icon/signal-hspa-plus)](https://materialdesignicons.com/icon/signal-hspa-plus)
