### ISSUE TITLE
Publish icon is missing

### ISSUE THREAD

**Issue by kokun-7** [Templarian/MaterialDesign#1441]
It seems that the publish icon from Google's source set is missing.  Is this an oversight or by design?

**Comment by CoDEmanX** [comment]
It is tracked in #420, row 476 in the spreadsheet.

**Comment by kokun-7** [comment]
Thanks but i'm not sure what this means.  Will it be included in the published set?

**Comment by Templarian** [comment]
Eventually. Actually the next release is pretty close (busy with work stuff unfortunately at the moment).

**Comment by Templarian** [comment]
[![publish](https://materialdesignicons.com/icon/publish)](https://materialdesignicons.com/icon/publish)
