### ISSUE TITLE
Vertical Align + Text

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1448]
`format-text-vertical-*` `top` `middle` `bottom`.

**Comment by CoDEmanX** [comment]
Like
![image](https://cloud.githubusercontent.com/assets/1309249/17774875/050143ea-6556-11e6-8251-6616ee71eb17.png)
but for vertical alignment?

**Comment by alexefremo** [comment]
You mean like this?

![ic_format_text_vertical_top_black_24px](https://cloud.githubusercontent.com/assets/3408199/18115532/7ce376be-6f59-11e6-8e3b-e689ac33f1a1.png)
![ic_format_text_vertical_top_black_48px](https://cloud.githubusercontent.com/assets/3408199/18115531/7ce32ef2-6f59-11e6-97ac-e04fd3722548.png)
![ic_format_text_vertical_bottom_black_24px](https://cloud.githubusercontent.com/assets/3408199/18115529/7ce2fe28-6f59-11e6-9d99-2a84e784985f.png)
![ic_format_text_vertical_bottom_black_48px](https://cloud.githubusercontent.com/assets/3408199/18115528/7ce2e5b4-6f59-11e6-8331-75de3f74e803.png)
![ic_format_text_vertical_middle_black_24px](https://cloud.githubusercontent.com/assets/3408199/18115530/7ce31a16-6f59-11e6-8381-4d61f2c52df9.png)
![ic_format_text_vertical_middle_black_48px](https://cloud.githubusercontent.com/assets/3408199/18115533/7ce75824-6f59-11e6-8ee4-8769a4a10d6a.png)

**Comment by casesandberg** [comment]
![image](https://cloud.githubusercontent.com/assets/4633636/20741606/45bbb9c6-b680-11e6-81d3-e3e85fae42b8.png)

[format-text-vertical-icons.zip](https://github.com/Templarian/MaterialDesign/files/621105/format-text-vertical-icons.zip)

**Comment by PeterShaggyNoble** [comment]
It looks like these were covered in v1.9.32 with `format-align-bottom`, `format-align-middle` and `format-align-top`. Closing here.
