### ISSUE TITLE
Icon for Sign Up

### ISSUE THREAD

**Issue by Gopinathp** [Templarian/MaterialDesign#1449]
It will good to have an icon for user sign up, which can be used in toolbar in Android

**Comment by JamesCoyle** [comment]
What would that look like?

**Comment by MrGrigri** [comment]
Couldn't [account-plus](https://materialdesignicons.com/icon/account-plus) work?

**Comment by svdovichenko** [comment]
Here is login I did
![login-48](https://cloud.githubusercontent.com/assets/9030372/18234149/2261ded8-72c9-11e6-8ac8-71539654398d.png)
![login-24](https://cloud.githubusercontent.com/assets/9030372/18234151/2407d198-72c9-11e6-9b6f-9e6ab29acf76.png)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. If the icon @MrGrigri suggeted doesn't suit your needs, please comment with an example of what you *are* looking for and we'll revisit this issue.
