### ISSUE TITLE
Gif icon from Google icons

### ISSUE THREAD

**Issue by dnldsht** [Templarian/MaterialDesign#1451]
I wasn't able too find an alternative on your huge collection.
[here](https://design.google.com/icons/#ic_gif) is it.

**Comment by CoDEmanX** [comment]
We don't have the stock Google icon for GIF. Is it rejected because of text-only?

**Comment by GreenTurtwig** [comment]
I closed it because the stock icon was already requested as part of another GIF request.

**Comment by CoDEmanX** [comment]
#2504 is closed too however, thus reopening this one.

**Comment by GreenTurtwig** [comment]
Oops, totally missed that it was closed

**Comment by PeterShaggyNoble** [comment]
There's also #1383.

**Comment by GreenTurtwig** [comment]
Ahh, that's the issue I was thinking of. Was on mobile so couldn't check last night.

**Comment by goyney** [comment]
We'll use this issue for adding the GIF icon from the stock collection.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48992536-3076f400-f106-11e8-9650-6b9df5cba806.png)
[gif.svg.zip](https://github.com/Templarian/MaterialDesign/files/2614028/gif.svg.zip)

**Comment by Templarian** [comment]
[![gif](https://materialdesignicons.com/icon/gif)](https://materialdesignicons.com/icon/gif)
