### ISSUE TITLE
icon suggestion

### ISSUE THREAD

**Issue by mbwatson** [Templarian/MaterialDesign#1452]
How about a "no calculator: icon? This is very specific, I know, but no harm in making the request! Basically, this could simply be the calculator icon with a slash through it, as is done in music-note-off.

**Comment by CoDEmanX** [comment]
In what context would you use this icon? Would it stand for something like "price not available"?

**Comment by dbardi** [comment]
I'd like to see some lamp icons.  lamp, lamp-tall, lamp-wall, etc.
These would be nice to use in home assistant

**Comment by JamesCoyle** [comment]
Could be useful to show that a calculation was not available for certain financial or mathematical apps.

**Comment by Templarian** [comment]
I think this is a bit too specific. Not sure the icon makes much sense even in that context.

**Comment by mbwatson** [comment]
i am developing an app for teachers to create questions for their students. the icon would indicate that the question is to be completed without the help of a calculator. like i said, probably too specific.

**Comment by Templarian** [comment]
@mbwatson You can still use the SVG here: [calculator-off.zip](https://github.com/Templarian/MaterialDesign/files/429210/calculator-off.zip), but yea too specific. Good luck on your app.

**Comment by mbwatson** [comment]
Oh, duh yeah. That's great, thanks!
