### ISSUE TITLE
lamp icons needed

### ISSUE THREAD

**Issue by dbardi** [Templarian/MaterialDesign#1453]
I'd like to see some lamp icons. lamp, lamp-tall, lamp-wall, etc.
These would be nice to use in home assistant.
Ideas: https://thenounproject.com/term/lamp/

**Comment by GreenTurtwig** [comment]
How about this?  
![puush-linux 2016-08-22 at 03 29 02](https://cloud.githubusercontent.com/assets/15905797/17858353/44b2b0ee-687d-11e6-8e5b-90a9b3f855a8.png)
![puush-linux 2016-08-22 at 03 29 20](https://cloud.githubusercontent.com/assets/15905797/17858356/46759c02-687d-11e6-9b89-f88dbf6fdb5b.png)
[lamp.zip](https://github.com/Templarian/MaterialDesign/files/430371/lamp.zip)
  
I couldn't find a way to make the line connecting to the lamp shade look that nice in my opinion. It was either no blank space, 1dp or 2dp.

**Comment by CoDEmanX** [comment]
Nice, more minimal than my contribution: ![lamp](https://cloud.githubusercontent.com/assets/1309249/14412563/9a196ed2-ff65-11e5-9c50-f8ecf819dff4.png) https://github.com/Templarian/MaterialDesign/issues/873#issuecomment-208050697

**Comment by GreenTurtwig** [comment]
A actually like yours more. :-)

**Comment by Templarian** [comment]
[![lamp](https://materialdesignicons.com/icon/lamp)](https://materialdesignicons.com/icon/lamp)
