### ISSUE TITLE
Nintendo Network

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#1454]
Here's an icon for Nintendo Network, in my opinion this is a relevant icon to be added since some sites like Niconico allow you to sign in with Nintendo Network.  
[nintendo-network.zip](https://github.com/Templarian/MaterialDesign/files/430587/nintendo-network.zip)
![puush-linux 2016-08-22 at 05 00 22](https://cloud.githubusercontent.com/assets/15905797/17861766/4ad5797c-688a-11e6-9817-453b7a047139.png)
![puush-linux 2016-08-22 at 05 00 36](https://cloud.githubusercontent.com/assets/15905797/17861768/4bef763c-688a-11e6-9f67-053f1d1c95c4.png)

**Comment by Templarian** [comment]
I'm going to mark this as too specific at this time. Nice idea, but too niche of a sign in option.

**Comment by GreenTurtwig** [comment]
I'm going to have to agree with you. Although it is a sign in option, it's very rarely used, and even then, mostly in Japan. :cat2:

**Comment by JamesCoyle** [comment]
Well the SVG is there if anyone needs to inline it.

**Comment by GreenTurtwig** [comment]
Yep, hopefully someone will be able to find it if they really need it. :+1:
