### ISSUE TITLE
need dolby icon

### ISSUE THREAD

**Issue by randyerfan** [Templarian/MaterialDesign#1455]
need dolby icon plz

**Comment by GreenTurtwig** [comment]
Something like: https://components.xamarin.com/resources/icons/component-926/icon_114x114.png  ?

**Comment by MrGrigri** [comment]
Like this?

![dolby](https://cloud.githubusercontent.com/assets/4528551/17985730/4cf66b3e-6ad4-11e6-8663-546315205194.png)

[dolby.zip](https://github.com/Templarian/MaterialDesign/files/438046/dolby.zip)

**Comment by Templarian** [comment]
[![dolby](https://materialdesignicons.com/icon/dolby)](https://materialdesignicons.com/icon/dolby)
