### ISSUE TITLE
sort icon - up and down thin icon

### ISSUE THREAD

**Issue by joaool** [Templarian/MaterialDesign#1457]
sort icon - an empty  triangle up and empty triangle down (or empty losange)
To be used to inform the user that a up or down sort is available if the icon is clicked

**Comment by Templarian** [comment]
Just to clarify... it would be like an outline version of https://materialdesignicons.com/icon/menu-down / `menu-up` ?

**Comment by dylmye** [comment]
They may be thinking of `chevron-up` / `chevron-down`?

**Comment by Templarian** [comment]
[![menu-down-outline](https://materialdesignicons.com/icon/menu-down-outline)](https://materialdesignicons.com/icon/menu-down-outline) [![menu-up-outline](https://materialdesignicons.com/icon/menu-up-outline)](https://materialdesignicons.com/icon/menu-up-outline)
