### ISSUE TITLE
Facebook messenger icon

### ISSUE THREAD

**Issue by ompemi** [Templarian/MaterialDesign#146]
That would be great: https://play.google.com/store/apps/details?id=com.facebook.orca

**Comment by yasminal** [comment]
http://materialdesignicons.com/icon/facebook-messenger

**Comment by octojoerg** [comment]
Sorry, but this icon is not listed as file in the repo :/ 
![image](https://cloud.githubusercontent.com/assets/19168327/21685965/dd1d8f7e-d363-11e6-9f55-e5c4089c59d6.png)

**Comment by Templarian** [comment]
Odd. Added. By the way if you need the SVG files.

https://materialdesignicons.com/design (only updated to 1.7.12, since I'm redoing the build tools for the new site).

**Comment by octojoerg** [comment]
thanks!
