### ISSUE TITLE
Expand on note icons with note-multiple

### ISSUE THREAD

**Issue by dylmye** [Templarian/MaterialDesign#1460]
Possibly provide a multiple version of `note` / `note-outline` / `note-plus`?

Thanks for this pack :)

**Comment by Templarian** [comment]
[![note-multiple](https://materialdesignicons.com/icon/note-multiple)](https://materialdesignicons.com/icon/note-multiple) [![note-multiple-outline](https://materialdesignicons.com/icon/note-multiple-outline)](https://materialdesignicons.com/icon/note-multiple-outline)

I don't think we need a multiple for the `note-plus`. Generally we very rarely add `+` or minus to icons. Only very highly used use cases.
