### ISSUE TITLE
Veg Non Veg Icon

### ISSUE THREAD

**Issue by GauravGGTrilyo** [Templarian/MaterialDesign#1461]
It would be great to have a veg non veg icon

**Comment by Templarian** [comment]
Wouldn't the [leaf](https://materialdesignicons.com/icon/leaf) be used for that?

Maybe using [pig](https://materialdesignicons.com/icon/pig) for the non veg.

**Comment by Templarian** [comment]
Closing this issue out as I think that answers it. If not please let me know an example and we can work on getting the icon added to better represent this.

**Comment by JamesCoyle** [comment]
I think we could do to add more food icons at some point. People could then have a better selection and find what meets their needs.
