### ISSUE TITLE
Google Photos Icon

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#1463]
#352 I would like you to add the Google Photos and IMDb built in icons. Thanks in advance.

**Comment by CoDEmanX** [comment]
What icons would that be?

Also, what is the reference to issue 352 for?

**Comment by KastriotQ** [comment]
About the 352, in your website it says that it is supposed to mean "icon
request". As of google photos i'm actually stunned that you don't know the
icon (you're giving me the impression that you're probably an iphone user
lol), but anyway im gonna attach a picture of it. Please make it look like
built in. Thanks in advance ;) .

**Comment by JamesCoyle** [comment]
1. Where does it mention issue 352?
2. Email attachments aren't handled by github. You'll have to attach them manually on the github site.
3. Do you mean the windmill logo?

**Comment by KastriotQ** [comment]
Yes exactly, the windmill thing. About the 352 it's at the "Reference an
issue or pull request" button.

**Comment by Templarian** [comment]
#556 IMDB is a duplicate request. Renaming this issue to Google Photos.

**Comment by svdovichenko** [comment]
Here is google photo icon 
![template](https://cloud.githubusercontent.com/assets/9030372/18234022/6ce2b6ca-72c5-11e6-8406-44d68ace8e52.png)
![48](https://cloud.githubusercontent.com/assets/9030372/18234023/6ea81a40-72c5-11e6-93a5-c1d8c34791e5.png)

**Comment by KastriotQ** [comment]
Great, should i be expecting the update soon ?

**Comment by JamesCoyle** [comment]
We need an SVG version and the next release won't be for a while as we just had one.

**Comment by svdovichenko** [comment]
png 24 ,48 , svg
[googlephoto.zip](https://github.com/Templarian/MaterialDesign/files/454166/googlephoto.zip)

**Comment by GreenTurtwig** [comment]
Just thought I'd mention that Google has an icon for notifications from Google Photos, it's basically the same apart from the "flower petals" are separated instead of being one solid shape.  
Next time I get a notification I'll post an example. :cat2:

**Comment by Templarian** [comment]
[![google-photos](https://materialdesignicons.com/icon/google-photos)](https://materialdesignicons.com/icon/google-photos)

Note, since this is a Google logo we assign it to the Google account unlike other contributions.
