### ISSUE TITLE
piggy-bank

### ISSUE THREAD

**Issue by Depechie** [Templarian/MaterialDesign#1464]
You know, like this one : http://www.hancockins.com/upload/Piggy_Bank.jpg

**Comment by alexefremo** [comment]
![ic_piggy_bank_black_24px](https://cloud.githubusercontent.com/assets/3408199/18084037/2c14f900-6ebf-11e6-9742-82f8366b052f.png)

**Comment by Depechie** [comment]
Looking good already, maybe adding a small entry on top of the pig ?

**Comment by alexefremo** [comment]
Like this?

![ic_piggy_bank_black_24px](https://cloud.githubusercontent.com/assets/3408199/18084980/ab8120a8-6ec2-11e6-8d62-0455fb56cb54.png)
![ic_piggy_bank_black_48px](https://cloud.githubusercontent.com/assets/3408199/18084978/ab7bb294-6ec2-11e6-8953-9fe21baede6c.png)
![ic_piggy_bank_black_512px](https://cloud.githubusercontent.com/assets/3408199/18084979/ab808ba2-6ec2-11e6-9c71-712fb448b43c.png)

**Comment by alexefremo** [comment]
an SVG if you like it
[ic_piggy_bank.zip](https://github.com/Templarian/MaterialDesign/files/444592/ic_piggy_bank.zip)

**Comment by Depechie** [comment]
Awesome thx!!

**Comment by alexefremo** [comment]
You're welcome. Here's an SVG
[ic_piggy_bank.zip](https://github.com/Templarian/MaterialDesign/files/444700/ic_piggy_bank.zip)

**Comment by GreenTurtwig** [comment]
The tail could maybe a little bit thicker (Material is *usually* 2dp thick), but other than that it looks great. :-D  
Can't really think of any other way to make it better. :-)

**Comment by alexefremo** [comment]
This is version with 2dp thick :)


![ic_piggy_bank_black_24px](https://cloud.githubusercontent.com/assets/3408199/18115335/0cc6fb18-6f58-11e6-9777-b2b90cb9e923.png)
![ic_piggy_bank_black_48px](https://cloud.githubusercontent.com/assets/3408199/18115336/0cca0c40-6f58-11e6-8385-064798db2005.png)
![ic_piggy_bank_black_512px](https://cloud.githubusercontent.com/assets/3408199/18115337/0cca5740-6f58-11e6-84e6-6a04eee65d4a.png)
[ic_piggy_bank.zip](https://github.com/Templarian/MaterialDesign/files/446385/ic_piggy_bank.zip)

**Comment by goyney** [comment]
@alexefremo Nice contribution. I do think it needs some small tweaking, for example all the rounded terminators and the nose has a small bump underneath that could be smoothed out. Could you take another pass at this? Use http://dev.materialdesignicons.com/contribute/github to create a preview and make sure to upload your source SVG!

**Comment by alexefremo** [comment]
@goyney thanks! I'll upload it after correcting

**Comment by alexefremo** [comment]
[ic_piggy_bank_black_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/2614079/ic_piggy_bank_black_24px.svg.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49029417-884b4480-f172-11e8-909f-5b63ef4165e3.png)![image](https://user-images.githubusercontent.com/1015040/49029378-6ea9fd00-f172-11e8-8c08-e76df4efbf2d.png)

[pigs.zip](https://github.com/Templarian/MaterialDesign/files/2616569/pigs.zip)

**Comment by goyney** [comment]
[![pig-variant](https://materialdesignicons.com/icon/pig-variant)](https://materialdesignicons.com/icon/pig-variant)[![piggy-bank](https://materialdesignicons.com/icon/piggy-bank)](https://materialdesignicons.com/icon/piggy-bank)
