### ISSUE TITLE
rename-box: What is the google stock name?

### ISSUE THREAD

**Issue by epelc** [Templarian/MaterialDesign#1465]
I can't find the stock name for this icon. Is it missing from the stock project?

https://materialdesignicons.com/icon/rename-box

Also are there any plans to add stock google names to your google icons? So we can load them from google's package if needed?

**Comment by CoDEmanX** [comment]
It's called rate_review.
Do you mean add aliases on the site so you can find them under the original name, or also in CSS?

**Comment by epelc** [comment]
The rate_review stock one looks more like a message bubble.

Google Stock
![image](https://cloud.githubusercontent.com/assets/5204642/17974979/22881fdc-6ab6-11e6-8318-564f42a5927b.png)
MDI
![image](https://cloud.githubusercontent.com/assets/5204642/17975011/2ea1d13c-6ab6-11e6-9688-bd176996ac3a.png)



@CoDEmanX to add an alias or list it in the dialog when you click on an icon.

I find the names of icons easier in this package. But we load in the icons from the stock google project(we also load in some of your custom ones).

**Comment by CoDEmanX** [comment]
How could I miss that! The corresponding icon is called message-draw in MDI. The box icon doesn't seem to exist in Google's project...

**Comment by Templarian** [comment]
Yea, some of these are pulled from Google apps, we should probably document which Google apps they came from. If anyone knows I can add it to the description of this icon, but for now I'm going to close this issue.

It is a little confusing, but it makes sense to still attribute these to Google even if they are not in the official set but are in Google created apps.
