### ISSUE TITLE
Zhihu

### ISSUE THREAD

**Issue by benpigchu** [Templarian/MaterialDesign#1468]
https://zhihu.com/ is a popular question and answer website in China
https://static.zhihu.com/static/revved/img/ios/touch-icon-152.87c020b9.png

**Comment by MrGrigri** [comment]
Like this:

![zhihu 4x](https://cloud.githubusercontent.com/assets/4528551/18012185/aa1970da-6b75-11e6-8d2c-1b84e679196b.png)
![zhihu](https://cloud.githubusercontent.com/assets/4528551/18012147/7a5102e6-6b75-11e6-9f6f-56087217b5ab.png)

[zhihu.zip](https://github.com/Templarian/MaterialDesign/files/439667/zhihu.zip)

**Comment by benpigchu** [comment]
I think this icon doesn't look good

**Comment by MrGrigri** [comment]
We're going to close this out as we don't feel it's large enough of a social media outlet to support.
