### ISSUE TITLE
Google contributor has old logo

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#1469]
The icon for Google has the old styled logo still.
![puush-linux 2016-08-28 at 06 31 57](https://cloud.githubusercontent.com/assets/15905797/18035428/e646d082-6d4d-11e6-8b98-b84ca9520ab7.png)
It should probably be updated to reflect the logo change, possibly to Google Design's Twitter avatar: 
![1w1vkoj0](https://cloud.githubusercontent.com/assets/15905797/18035433/096d4438-6d4e-11e6-9cc0-0d56767f2251.png)

**Comment by Templarian** [comment]
Updated... https://materialdesignicons.com/contributor/Google
