### ISSUE TITLE
Science/Lab icons

### ISSUE THREAD

**Issue by ShawnWeaver** [Templarian/MaterialDesign#147]
Thanks for all your work on this new site - it's extremely useful and I really appreciate it.

I've got suggestions for a bunch of new science and lab-related icons that would be useful for applications I'm developing. This is what I can think of for now - I'll probably add more later.
- [x] Beaker (The current "beaker" icons are actually Erlenmeyer or conical flasks)
- [x] Test tube
- [x] Atom (e.g., http://icongal.com/gallery/image/5890/nuclear_atom_atomic.png)
- [x] Molecule/Compound (e.g., https://www.google.com/search?tbm=isch&q=Molecule)
- [x] Microscope
- [x] Radioactive
- [x] Biohazard
- [x] Bomb (or some sort of "explosive" icon)
- [x] Skull-and-crossbones (or a "toxic" icon)
- [ ] Blender/Mixer
- [x] Barrel
- [x] Gas Cylinder
- [ ] Goggles and/or lab coat
- [ ] Gloves
- [x] Hard hat

**Comment by yasminal** [comment]
http://materialdesignicons.com/icon/biohazard

**Comment by yasminal** [comment]
http://materialdesignicons.com/icon/radioactive

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/radioactive Was also added by @yasminal.

http://materialdesignicons.com/icon/barrel

**Comment by CoDEmanX** [comment]
Would https://github.com/Templarian/MaterialDesign/issues/210#issuecomment-124808095 work as beaker?

Hard hat like in http://materialdesignicons.com/icon/worker ?

**Comment by Templarian** [comment]
Tasks:

- [ ] So... we need to include these and rename `beaker-*` `flask-*`
- [ ] `hardhat` new icon

**Comment by CoDEmanX** [comment]
Atom is really hard, doesn't look right with 2px line width, but neither with lower::
![atom](https://cloud.githubusercontent.com/assets/1309249/9072283/889f8e50-3afa-11e5-9765-d397eb6bbb17.png) ![atom2](https://cloud.githubusercontent.com/assets/1309249/9072282/887c4382-3afa-11e5-83a7-2bbee8c403e4.png)

My measure-beaker turned into a test-tube:
![test-tube](https://cloud.githubusercontent.com/assets/1309249/9072462/9def5f5a-3afb-11e5-94f4-f19276c3803a.png) https://www.dropbox.com/s/ktxu4ac6d5jvpfi/test-tube.svg?dl=0

Safety glasses are usually depicted by a face silhouette wearing goggles, not sure if this could be made working with a geometric MD head... Until then, you could just use the sunglasses icon.

**Comment by CoDEmanX** [comment]
First shot at microscope:
![microscope](https://cloud.githubusercontent.com/assets/1309249/9088419/422409d8-3b90-11e5-8607-41eaadbe45f7.png)

**Comment by ShawnWeaver** [comment]
I had trouble with an atom icon as well because the details disappear at a small scale. An electron shell diagram would probably work better:
http://figures.boundless.com/12796/raw/hell-001-hydrogen-no-label.svg
https://upload.wikimedia.org/wikipedia/commons/3/3e/Electron_shell_010_Neon_-_no_label.svg

I really like the test tube. The microscope looks good... I'm just wondering if it looks a bit too much like a "G"...  Though judging from a Google search, that seems pretty common when it comes to microscope icons.

**Comment by CoDEmanX** [comment]
Would this work as gas bottle? ![gas-cylinder_ 147](https://cloud.githubusercontent.com/assets/1309249/14904462/97122dd6-0da8-11e6-8dc7-e8aee00ce511.png)

**Comment by ShawnWeaver** [comment]
That's exactly what I was thinking for a gas cylinder. Thanks!

**Comment by jacobq** [comment]
There is a nice test tube icon here: https://github.com/Templarian/MaterialDesign/issues/1209

**Comment by Templarian** [comment]
[![gas-cylinder](https://materialdesignicons.com/icon/gas-cylinder)](https://materialdesignicons.com/icon/gas-cylinder) [![microscope](https://materialdesignicons.com/icon/microscope)](https://materialdesignicons.com/icon/microscope)

**Comment by CoDEmanX** [comment]
Feel free to post microscope alternatives that look less like a G. We can always update icons.

**Comment by CoDEmanX** [comment]
Also note that a test tube icon was added:

[![test-tube](https://materialdesignicons.com/icon/test-tube)](https://materialdesignicons.com/icon/test-tube)

**Comment by LOG-TAG** [comment]
@CoDEmanX  we need this type of test tube icon 
![image](https://cloud.githubusercontent.com/assets/1190344/21492935/8646fbae-cc2e-11e6-9bd5-df96d76aaa48.png)

**Comment by Templarian** [comment]
@LOG-TAG It's called a flask.

[![flask](https://materialdesignicons.com/icon/flask)](https://materialdesignicons.com/icon/flask)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48731352-d8725600-ec0a-11e8-8ae5-7abf67529b67.png)![image](https://user-images.githubusercontent.com/1015040/48731368-df996400-ec0a-11e8-82e6-6864ff74685f.png)

[SCIENCE.zip](https://github.com/Templarian/MaterialDesign/files/2596864/SCIENCE.zip)

---

I believe gloves can be handled now by `hand`. With these two icons, this issue should be fulfilled.

**Comment by Templarian** [comment]
Added. 😃

**Comment by PeterShaggyNoble** [comment]
There's a typo in the name of the `safety-goggles` icon.

**Comment by Templarian** [comment]
^ Fixed @PeterShaggyNoble 🤣
