### ISSUE TITLE
speed omeder

### ISSUE THREAD

**Issue by fanno** [Templarian/MaterialDesign#1472]
prop early incorrect spelling , but a speedomender of something that looks like it. i have not seen any.

**Comment by Templarian** [comment]
Not sure I understand the request/question. Can you please clarify?

https://materialdesignicons.com/icon/speedometer

**Comment by fanno** [comment]
ofcause i just missed it ! sorry i did do search for "speed" odd it not show up.

sorry for wasting your time !

**Comment by fanno** [comment]
turns out i had typed sped =/ not speed ..

**Comment by Templarian** [comment]
No problem. Typing speed should have shown it.

You can use the chrome/firefox extensions to search icons also. They include the alias information also... https://chrome.google.com/webstore/detail/materialdesignicons-picke/edjaedpifkihpjkcgknfokmibkoafhme

**Comment by fanno** [comment]
indeed. ! sorry once again
