### ISSUE TITLE
ATM and POS icons

### ISSUE THREAD

**Issue by alexefremo** [Templarian/MaterialDesign#1473]
I made ATM snd POS Icons for my work purpose. You can take em if you want. Hope they'll suit all ideas of material.

![ic_pos_black_48px](https://cloud.githubusercontent.com/assets/3408199/18086286/9b9289ce-6ec8-11e6-9587-428d5c3a63ea.png)
![ic_atm_black_48px](https://cloud.githubusercontent.com/assets/3408199/18086287/9bad8fa8-6ec8-11e6-8334-02ab9a44dfea.png)
[pos_atm_svg_icons.zip](https://github.com/Templarian/MaterialDesign/files/444611/pos_atm_svg_icons.zip)

**Comment by PeterShaggyNoble** [comment]
Google have a text-based `atm` icon in their extended set but I'm not a fan of it, personally:

![atm](https://user-images.githubusercontent.com/15157491/36671968-8452859a-1af5-11e8-9579-d478e16115f8.png)

**Comment by PeterShaggyNoble** [comment]
That ATM icon has now been added to Google's new stock icon set: https://material.io/tools/icons/?search=atm&icon=atm&style=baseline

**Comment by goyney** [comment]
Here is the Stock `atm` icon:

![image](https://user-images.githubusercontent.com/1015040/48992436-acbd0780-f105-11e8-85c6-f7e34ad4d1d7.png)
[atm.svg.zip](https://github.com/Templarian/MaterialDesign/files/2614019/atm.svg.zip)

**Comment by goyney** [comment]
Here are the two Contributions from @alexefremo:
![image](https://user-images.githubusercontent.com/1015040/48992490-f73e8400-f105-11e8-9961-9330d0392458.png)![image](https://user-images.githubusercontent.com/1015040/48992495-002f5580-f106-11e8-9a5b-e5b38ec93722.png)
[atm-pos.zip](https://github.com/Templarian/MaterialDesign/files/2614025/atm-pos.zip)

**Comment by Templarian** [comment]
I'm wondering if there is a better way to depict an AT[M] Machine.

Added `atm` and `point-of-sale-machine`.

[![atm](https://materialdesignicons.com/icon/atm)](https://materialdesignicons.com/icon/point-of-sale) [![point-of-sale](https://materialdesignicons.com/icon/atm)](https://materialdesignicons.com/icon/point-of-sale)

**Comment by Templarian** [comment]
Closing this, lets see if anyone requests the `atm-machine`. Looks a little "odd".
