### ISSUE TITLE
settings_ethernet

### ISSUE THREAD

**Issue by breon** [Templarian/MaterialDesign#1474]
Hi there!
Please include "settings_ethernet" from the Google Material Design library.

https://material.io/icons/#ic_settings_ethernet

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48992405-84350d80-f105-11e8-9bf2-3ef965eb3756.png)
[brackets-settings.svg.zip](https://github.com/Templarian/MaterialDesign/files/2614016/brackets-settings.svg.zip)

**Comment by Templarian** [comment]
Feel like this icon is weird to represent settings? Not 100% sure if this icon is necessary.

**Comment by CoDEmanX** [comment]
It neither represents ethernet not settings well, but I see a use for it to represent transpilers or templating languages - the angled brackets stand for HTML elements and the dots for something in addition (logic?)We should add it IMO, but probably under a different name

**Comment by breon** [comment]
`settings_ethernet` is what the Material Design team named it. I would recommend that it maintains that name for discovery, but if alternate names are allowed, add whatever seem appropriate.

**Comment by PeterShaggyNoble** [comment]
@breon, if the name we give an icon doesn't match Google's then we add Google's as an alias so it can still be searched for.

**Comment by goyney** [comment]
We already have `code-tags`:
[![code-tags](https://materialdesignicons.com/icon/code-tags)](https://materialdesignicons.com/icon/code-tags)

The three dots in middle don't convey any meaning, IMO. I agree with @Templarian, I don't see a reason to add this.

**Comment by breon** [comment]
I submitted this request almost 3 years ago, to be used in a product that doesn't exist any more. The intent wasn't to invent some random icon, but to add an icon that Google themselves included in their Material Icon set. It's still there.
https://material.io/tools/icons/?icon=settings_ethernet&style=baseline

With regards to the three dots, it appears that there are several Material "settings" icons for various functions...on your site none the less. https://imgur.com/PqRREM8

It doesn't really matter to me much anymore. It's just more interesting that you choose to not include an official Material icon from the creators.
