### ISSUE TITLE
Request: no-search icon

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1476]
I need a no search results icon in one of my projects, so I created this. Essentially, I took the magnify-plus and made it an 'x' instead of a '+'. If you wanted to keep it consistent with the magnify icons, you could name it magnify-clear. 

![no-search 4x](https://cloud.githubusercontent.com/assets/4528551/18110882/51b516fe-6ed8-11e6-963d-802197695de7.png)
![no-search](https://cloud.githubusercontent.com/assets/4528551/18110884/53b6149e-6ed8-11e6-9842-977d2ede06fa.png)
[no-search.zip](https://github.com/Templarian/MaterialDesign/files/446124/no-search.zip)

**Comment by goyney** [comment]
This is was added at some point. `magnify-close`
