### ISSUE TITLE
Add MrGrigri as Contributer

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1477]
@Templarian, These are the icons that I have contributed to. What's the process for adding me as a contributor? Thanks for allowing me this awesome opportunity. 
- [X] ![dolby](https://cloud.githubusercontent.com/assets/4528551/18111270/705e3e84-6edb-11e6-882a-d893d745897e.png) [Dolby](https://github.com/Templarian/MaterialDesign/issues/1455)
- [X] ![douban](https://cloud.githubusercontent.com/assets/4528551/18111227/161d0df6-6edb-11e6-830b-d5ca94c64469.png) [Douban](https://github.com/Templarian/MaterialDesign/issues/1394)
- [X] ![section](https://cloud.githubusercontent.com/assets/4528551/18111236/23657d0e-6edb-11e6-921f-358c648d1899.png) [Section](https://github.com/Templarian/MaterialDesign/issues/1420)
- [X] ![wish](https://cloud.githubusercontent.com/assets/4528551/18111264/5f325d3e-6edb-11e6-9f72-db31bf0bd2c9.png) [Wish](https://github.com/Templarian/MaterialDesign/issues/1363)
- [X] ![zhihu](https://cloud.githubusercontent.com/assets/4528551/18111274/77fd21aa-6edb-11e6-9b61-a10ca0cfd1a7.png) [Zhihu](https://github.com/Templarian/MaterialDesign/issues/1468)

I'm still unsure on these:
- [ ] [Email Signature](https://github.com/Templarian/MaterialDesign/issues/1341)
- [ ] [Police](https://github.com/Templarian/MaterialDesign/issues/1343)

**Comment by Templarian** [comment]
Your contributor account was created the other day (probably noticed it), I just haven't assigned and added the icons just yet.

Busy with Fallout 4 at the moment (and will be on work/vacation stuff over the next 2 weeks, don't get frustrated that I'm ignoring this issue... I'll be ignoring all issues :sweat_smile:).

**Comment by MrGrigri** [comment]
@Templarian, don't rush, just have fun with Fallout 4. I also have NOT noticed my contributor account. Is there some sort of Wiki or will I be getting an email/notification?

**Comment by JamesCoyle** [comment]
Well there are 87 issues with contributions that haven't been closed yet @Templarian so not that much work for you when you get back. Probably be good to have a break. Have fun while it lasts! :P

**Comment by MrGrigri** [comment]
I'm going to close this as I guess I'm a contributor by now. 😉
