### ISSUE TITLE
Percentage area chart

### ISSUE THREAD

**Issue by toureh** [Templarian/MaterialDesign#1478]
Kinda like the area-spline, but one that fills the y-axis.

http://www.highcharts.com/demo/area-stacked-percent

![screen shot 2016-08-31 at 11 24 04 am](https://cloud.githubusercontent.com/assets/7913941/18132506/84511172-6f6d-11e6-9aba-07aabac99084.png)

**Comment by CoDEmanX** [comment]
Looks quite odd: ![chart-areaspline-filled](https://cloud.githubusercontent.com/assets/1309249/18133550/5e028392-6f9b-11e6-813d-d1a3886cdb62.png)

**Comment by JapanYoshi** [comment]
Yeah, mine too.
![rect4143](https://cloud.githubusercontent.com/assets/8707990/18417537/577f67f2-786e-11e6-812e-7c360fcbcf34.png)

**Comment by PeterShaggyNoble** [comment]
[`chart-line-stacked`](https://materialdesignicons.com/icon/chart-line-stacked) should fulfil this request.
