### ISSUE TITLE
Coupons icons

### ISSUE THREAD

**Issue by ashishkumawat** [Templarian/MaterialDesign#1479]

**Comment by GreenTurtwig** [comment]
Any idea about how this should look?  
I'm thinking of the ticker icon: https://materialdesignicons.com/icon/ticket  
with a percentage symbol in the middle.

**Comment by ashishkumawat** [comment]
I found these two icons from shutterstock and liked it, providing links that you can see
[1.](http://www.shutterstock.com/en/pic.mhtml?tpl=39422-174648&utm_source=39422&utm_medium=Affiliate&&irgwc=1&id=249172615&utm_campaign=Graphic%20resources%20SL)
[2.](http://www.shutterstock.com/en/pic.mhtml?utm_campaign=Graphic%20resources%20SL&id=295339496&irgwc=1&&utm_medium=Affiliate&utm_source=39422&tpl=39422-174648)

thanks for your quick reply.

**Comment by GreenTurtwig** [comment]
No problem. :-P  
The first one is similar to [paper-cut-vertical](https://materialdesignicons.com/icon/paper-cut-vertical), it's kind of hard to get text into a small size though (as well as being universal for different languages).
If your looking for one similar to the second one you could use the [tag icon](https://materialdesignicons.com/icon/tag).
  
I'll have a go at creating one based off my idea later though, that way there can be a specific "coupon" icon. :cat2:

**Comment by ashishkumawat** [comment]
Ok, I appreciate you suggestions and thought and after done with your idea please let me know. Thanks once again.

**Comment by GreenTurtwig** [comment]
:-)

**Comment by GreenTurtwig** [comment]
![puush-linux 2016-08-31 at 06 53 26](https://cloud.githubusercontent.com/assets/15905797/18140196/57c7e524-6fac-11e6-98e2-a1dfe4880d4f.png)
![puush-linux 2016-08-31 at 06 53 43](https://cloud.githubusercontent.com/assets/15905797/18140198/593b6c14-6fac-11e6-808f-519a540e7625.png)

[ticket-percent.zip](https://github.com/Templarian/MaterialDesign/files/447953/ticket-percent.zip)
(An alias for "ticket-percent" would be "coupon".  
Here, how's this? :-)

**Comment by ashishkumawat** [comment]
Yes its quite appealing can be better if cuts on edges are all around i think 6 is enough. 2, 2 on each horizontal sides.

**Comment by ashishkumawat** [comment]
I think your icon is very good. publish it

**Comment by GreenTurtwig** [comment]
You'll have to wait for @Templarian first, then it will be a while until the next release since there was just one. :-1:

**Comment by Templarian** [comment]
Added `ticket-percent` and alias `coupon`.

**Comment by ashishkumawat** [comment]
Awesome man, thanks
