### ISSUE TITLE
Cooking Icons

### ISSUE THREAD

**Issue by mrcritical** [Templarian/MaterialDesign#148]
I have some suggestions for cooking icons:

- Oven
- Recipe
- Meal
- Spoon
- Fork

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/stove
http://materialdesignicons.com/icon/silverware (would this work for spoon?)
http://materialdesignicons.com/icon/silverware-variant (would this work for fork?)

The others need to be added.

**Comment by mrcritical** [comment]
Odd I searched for stove and it had no results. But now it does. Weird.

I think silverware works well for most. Though a separate on with just a spoon would be good. It is often used to indicate the preparation of a recipe.

**Comment by mrcritical** [comment]
Also might be nice to have one that combines a spoon with a book to represent a cookbook (just an idea).

**Comment by mrcritical** [comment]
Btw, the food icon is similar to a meal, but the use of fast food might turn some people off if the desire of the icon is meant to represent a healthier meal.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/nutriton (this might work for a recipe)
http://materialdesignicons.com/icon/food-variant Completely agree, I think this will give a healthier view. It can viewed as milk and cereal or Orange Juice and Oatmeal, etc...
http://materialdesignicons.com/icon/silverware-fork
http://materialdesignicons.com/icon/silverware-spoon

Let me know if these don't work. I'd be happy to reopen the issue and add more. :smile:

Good luck on your app!

**Comment by mrcritical** [comment]
Yup. Those will work. Recipe is a hard one to show in an icon. Nutrition should work though. Thank you so much for your quick response and your contributions to the online community. They are very much appreciated.
