### ISSUE TITLE
LINE icons (the messaging app)

### ISSUE THREAD

**Issue by PingMetal** [Templarian/MaterialDesign#1481]
It would be appreciated to have icons for LINE the most used text messaging app in Japan. The app is used by all Japanese and Japanese businesses to reach customers.

Here is a link to the app's website:
http://line.me/en/

Example of icons:
https://www.iconfinder.com/icons/1181250/line_social_social_application_social_media_social_network_icon
https://www.iconfinder.com/icons/1181229/line_social_social_application_social_media_social_network_icon
https://www.iconfinder.com/icons/762303/browser_business_internet_line_money_online_web_icon
https://www.iconfinder.com/icons/710292/line_social_icon

Thank you,

**Comment by GreenTurtwig** [comment]
The problem is that it has text in the icon, this makes it harder to see at small sizes. :cat2:

**Comment by PingMetal** [comment]
Yes, you're right, but not that hard I think.
Just have a look at this page:
http://line.me/en/logo
There's an image there containing three icons, one is very small, looking at it I think you can tell what the icon is. You can recognize the app without problem.

**Comment by JamesCoyle** [comment]
https://www.iconfinder.com/icons/710292/line_social_icon#size=64

Even at 64x64 the icon is illegible. Gonna have to reject this unfortunately.

**Comment by JPMulder** [comment]
Why Reject it, Line is Massive in Asia. How difficult can it be. 
Look at this http://www.businessofapps.com/data/line-statistics/
They have 600mil registered users. https://expandedramblings.com/index.php/line-statistics/
Please create this icon.

**Comment by PeterShaggyNoble** [comment]
@JPMulder, at the time this was rejected because it wouldn't be legible at 20*20. Also, since then, we have started to reduce the number of brand icons we add, instead directing people to [Simple Icons](https://simpleicons.org/) ([repo](https://github.com/simple-icons/simple-icons)), a dedicated brand icon pack which, incidentally, already has an [icon for this brand](https://simpleicons.org/?q=line).

**Comment by nakorndev** [comment]
I don't want to be saying +1 as github's community doesn't like it. But for around the asia have many people using a LINE provider to connect & share with people. It would be nice if LINE was added.

Please add this icon, I know on other region may use WhatsApp or else, but please just simple icon for asia people so, +1 for this icon. Thanks. :)

**Comment by Templarian** [comment]
@nakorndev We're not adding brand icons anymore (and in 5.0 removing a lot of brands). You'll need to use Simple Icons for any brand icons. Simple Icons can handle this much better than us going forward.

Read more: http://dev.materialdesignicons.com/roadmap/brand-icons
