### ISSUE TITLE
Money/dollar Icon

### ISSUE THREAD

**Issue by JulianoPadilha** [Templarian/MaterialDesign#1483]

**Comment by GreenTurtwig** [comment]
There are already [coin](https://materialdesignicons.com/icon/coin), [dollar](https://materialdesignicons.com/icon/currency-usd), [cash](https://materialdesignicons.com/icon/cash) and [cash dollar](https://materialdesignicons.com/icon/cash-usd) icons. These should match your needs. :cat2:
