### ISSUE TITLE
Luggage Icon

### ISSUE THREAD

**Issue by chris-oswald** [Templarian/MaterialDesign#1484]
Lots of travel stuff, but no luggage icon.  Only thing close is a briefcase.

**Comment by svdovichenko** [comment]
Having fun , just created bagpack what you think
![bag_pack](https://cloud.githubusercontent.com/assets/9030372/18228158/7559e966-720e-11e6-8756-ca3e62cf9ca5.png)

**Comment by JamesCoyle** [comment]
Lines need to be 2dp thick.

**Comment by svdovichenko** [comment]
ok ty for letting me know will correct

**Comment by svdovichenko** [comment]
I think is should be correct now
![bag_pack](https://cloud.githubusercontent.com/assets/9030372/18228277/5141aa3a-7215-11e6-921a-d9d1e01980ca.png)

**Comment by svdovichenko** [comment]
Here this is what I come up with. 
svg + png
[Luggage.zip](https://github.com/Templarian/MaterialDesign/files/454183/Luggage.zip)

![bag-24](https://cloud.githubusercontent.com/assets/9030372/18234769/59e77f48-72dd-11e6-81f7-e9ed5a88f706.png)
![bag-48](https://cloud.githubusercontent.com/assets/9030372/18234768/59e64bf0-72dd-11e6-9bdf-81a8e24d4b53.png)

**Comment by chris-oswald** [comment]
I like both the backpack and luggage icons.  Thanks for providing!  I guess we'll see if they get included.

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #2473
