### ISSUE TITLE
Icon Category

### ISSUE THREAD

**Issue by svdovichenko** [Templarian/MaterialDesign#1485]
Here is example of my project where I used my category icon.
https://www.behance.net/gallery/42395201/YouTube-new-feature-Category
![category](https://cloud.githubusercontent.com/assets/9030372/18227870/dddbbeae-7201-11e6-966b-d84444ff3084.jpg)

**Comment by svdovichenko** [comment]
category 24, 48 png + svg
[category.zip](https://github.com/Templarian/MaterialDesign/files/454173/category.zip)
![category-24](https://cloud.githubusercontent.com/assets/9030372/18234647/eee25202-72d9-11e6-9ed5-59ead5ba34ab.png)
![category-48](https://cloud.githubusercontent.com/assets/9030372/18234648/f0c0097a-72d9-11e6-9e7a-6363b7e590dc.png)

**Comment by svdovichenko** [comment]
Category Icon fixed some things :)
![category-24](https://cloud.githubusercontent.com/assets/9030372/18234812/0adca1e8-72de-11e6-8ea5-12f860a1aa36.png)
![category-48](https://cloud.githubusercontent.com/assets/9030372/18234813/0adf7c10-72de-11e6-828d-ac6f1b1d0707.png)
[category.zip](https://github.com/Templarian/MaterialDesign/files/454190/category.zip)

**Comment by PeterShaggyNoble** [comment]
[`file-tree`](https://materialdesignicons.com/icon/file-tree) should fulfil this request.
