### ISSUE TITLE
Screen Lock Pattern

### ISSUE THREAD

**Issue by autost** [Templarian/MaterialDesign#1487]
How about this icon for Screen Lock Pattern
![screen lock pattern](https://cloud.githubusercontent.com/assets/6862930/18245965/fa6f345e-7370-11e6-8967-ca17b259895c.png)

**Comment by CoDEmanX** [comment]
Now we know how to unlock your phone ;)

Not sure if this works at 24x24 pixels...

**Comment by JapanYoshi** [comment]
![rect4141](https://cloud.githubusercontent.com/assets/8707990/18417518/b2ece430-786d-11e6-87b7-5f42a1495a2e.png)
Remake that works better at 24px

**Comment by JamesCoyle** [comment]
2x2 looks better IMO.

**Comment by Templarian** [comment]
[![lock-pattern](https://materialdesignicons.com/icon/lock-pattern)](https://materialdesignicons.com/icon/lock-pattern)
