### ISSUE TITLE
vacation, holiday, sick leave (for attendance reports)

### ISSUE THREAD

**Issue by igorushi** [Templarian/MaterialDesign#1488]

**Comment by GreenTurtwig** [comment]
The beach icon could probably be used for holiday: https://materialdesignicons.com/icon/beach

**Comment by igorushi** [comment]
@GreenTurtwig , thanks `beach` can be used for vacation, `ambulance` for sick leave, but I still have no idea for holiday (may be `bed` or `cake` but it still not that).

**Comment by MrGrigri** [comment]
What about [work building](https://materialdesignicons.com/icon/domain) with a slash through it. Would that work?

**Comment by igorushi** [comment]
Usually I don't destroy buildings during my holidays, but I like an idea that holiday is an anti work  :)
:+1:

**Comment by CoDEmanX** [comment]
![image](https://cloud.githubusercontent.com/assets/1309249/18294335/b2ea138c-7498-11e6-9c0f-134249101b49.png) ![image](https://cloud.githubusercontent.com/assets/1309249/18294323/a5387e2c-7498-11e6-82c7-481faeb248dc.png) ![image](https://cloud.githubusercontent.com/assets/1309249/18294340/bc7bdf7a-7498-11e6-8867-1e507b818c12.png)

**Comment by MrGrigri** [comment]
How about the following:

Work 
![work 4x](https://cloud.githubusercontent.com/assets/4528551/18318652/b6d8e864-74df-11e6-883c-8394abbde226.png) ![work](https://cloud.githubusercontent.com/assets/4528551/18318643/b168a446-74df-11e6-9aee-2f227c1483f0.png)

Work-Off
![work-off 4x](https://cloud.githubusercontent.com/assets/4528551/18318664/d0daabda-74df-11e6-909e-7034f122b55f.png) ![work-off](https://cloud.githubusercontent.com/assets/4528551/18318667/d4cbf884-74df-11e6-922a-e180a670db78.png)

**Comment by MrGrigri** [comment]
Or the option with a laptop:

![work-off-alt 4x](https://cloud.githubusercontent.com/assets/4528551/18318729/166e809a-74e0-11e6-8fd4-4ca23595f6cb.png) ![work-off-alt](https://cloud.githubusercontent.com/assets/4528551/18318721/1141fbf6-74e0-11e6-98b1-a54e8f0e7bc0.png)

**Comment by Templarian** [comment]
@MrGrigri I like the shovel icon, but the slash needs to be extended up further at the top and slightly at the bottom.

**Comment by MrGrigri** [comment]
Do you mean that the slash needs to be further away from the spade? Or that they just need to extend to the top left and bottom right of the slash itself?

**Comment by Templarian** [comment]
@MrGrigri Sorry, I meant the shovel is fine, but the `laptop-off` had the wrong slash. I've fixed and added `laptop-off` as a contribution from you. I need the SVG for shovel. Thanks!

[![laptop-off](https://materialdesignicons.com/icon/laptop-off)](https://materialdesignicons.com/icon/laptop-off)

**Comment by MrGrigri** [comment]
@Templarian Here is the Zip. That makes more sense now, thanks for handling it for me. I labeled them work and no-work.

[no-work.zip](https://github.com/Templarian/MaterialDesign/files/617262/no-work.zip)

**Comment by Templarian** [comment]
[![shovel](https://materialdesignicons.com/icon/shovel)](https://materialdesignicons.com/icon/shovel) [![shovel-off](https://materialdesignicons.com/icon/shovel-off)](https://materialdesignicons.com/icon/shovel-off)
