### ISSUE TITLE
Add icon scales

### ISSUE THREAD

**Issue by D0Gmatist** [Templarian/MaterialDesign#1489]
https://maxcdn.icons8.com/Share/icon/Science/scales1600.png

**Comment by MrGrigri** [comment]
Already exists [here](https://materialdesignicons.com/icon/scale-balance), [here](https://materialdesignicons.com/icon/scale-bathroom), and [here](https://materialdesignicons.com/icon/scale).

**Comment by D0Gmatist** [comment]
I'm sorry, I did not see)
