### ISSUE TITLE
Dice icons + FB messenger

### ISSUE THREAD

**Issue by yasminal** [Templarian/MaterialDesign#149]
An alternative to the dice icons asked for in #135 + Facebook messenger icon for #146 

http://bit.ly/1vkDlvD

**Comment by Templarian** [comment]
Invite sent. Please upload a 100x100 avatar and type in some information when you get a chance. This way you show up in the contributor list correctly. If you have any issues feel free to reply here. I'm always adding new feature so there is a good chance I may break stuff during the alpha.

Welcome aboard and thanks for helping out the open source design community. Developers really rely on it. :smile:

**Comment by Templarian** [comment]
@yasminal When you are exporting the icons, they are not exporting at the correct points. 2px rounded edges should always be processed through the optimization step as seen below.

I have a feeling the DPI setting is wrong (might be an issue in my template also. I don't use illustrator for icons, but I know others do and their imports seem to have correct coordinates. I'm going to research what could be causing this.

```
// Incorrect optimized path points...
M19.36,3H4.64C3.74,3 3,3.81 3,4.8V19.2C3,20.19 3.74,21 4.64,21H19.36C20.27,21 21,20.19 21,19.2V4.8C21,3.81 20.27,3 19.36,3M12,14C10.89,14 10,13.11 10,12C10,10.92 10.89,10 12,10A2,2 0 0,1 14,12A2,2 0 0,1 12,14Z

// Correct optimized path points...
M5,3H19A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5A2,2 0 0,1 3,19V5A2,2 0 0,1 5,3M12,10A2,2 0 0,0 10,12A2,2 0 0,0 12,14A2,2 0 0,0 14,12A2,2 0 0,0 12,10Z
```

One of the large optimizations is failing converting the curves `C` to arcs `A`.

Till I can find a solution I've simply updated your icons with corrected point data. This is exactly what the alpha is meant to find.

Track icon modifications here: http://materialdesignicons.com/history

**Comment by Templarian** [comment]
I'll be building out improvements to the compare tool after the updates to the font generation are done. Right now the `Characters` length is the only real identifier that there was a change, because visually the two icons are so similar.

![image](https://cloud.githubusercontent.com/assets/338885/6162797/3410b09c-b24e-11e4-8b5e-d2a1183ddd44.png)

**Comment by yasminal** [comment]
@Templarian I'm really not sure what it is; I tried recreating the dice icons and importing one on the portal, so that I ended up with this path instead:

`M5,3A2,2 0 0,0 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5A2,2 0 0,0 19,3H5M12,14A2,2 0 0,1 10,12A2,2 0 0,1 12,10C14,13.1 13.1,14 12,14Z`

Which is better but there are still some weird coordinates going on. I am fairly new to vector design though, so I might just be messing things up in Illustrator.

**Comment by Templarian** [comment]
I'm going to sit down this weekend and research the best way to fix this. The issue is that if a large number of icons are like this it bulks up the font size. The goal is to keep the point data as small as possible.

Hopefully there is a simple fix.
