### ISSUE TITLE
Infinite Symbol icon

### ISSUE THREAD

**Issue by manojkumar6** [Templarian/MaterialDesign#1491]
Required **Infinite** Symbol icon

**Comment by CoDEmanX** [comment]
Google's all-inclusive icon is basically that. I think it has yet to be added.

**Comment by Templarian** [comment]
I'm going to say this is both. Infinite is a closed loop and all-inclusive is a cut loop.

[![infinity](https://materialdesignicons.com/icon/infinity)](https://materialdesignicons.com/icon/infinity) [![all-inclusive](https://materialdesignicons.com/icon/all-inclusive)](https://materialdesignicons.com/icon/all-inclusive)
