### ISSUE TITLE
Subscribe / Unsubscribe

### ISSUE THREAD

**Issue by Glurt** [Templarian/MaterialDesign#1493]
This one might be quite difficult as there doesn't seem to be a standard icon for subscribe and unsubscribe but if you guys can think of one then it's likely that it could become the standard.

**Comment by MrGrigri** [comment]
I believe there are no standard icons because the words themselves are vague. We would need a bit more information as to which type of subscription this would refer to. E.g. Newspaper subscription. For that, I would use the [newspaper](https://materialdesignicons.com/icon/newspaper) icon with a plus/checkmark (subscribe) or close (unsubscribe) icon in the bottom right.

**Comment by Glurt** [comment]
What would you suggest for subscribing to a channel or a feed?

**Comment by MrGrigri** [comment]
For the RSS Feed, I would personally use the [rss](https://materialdesignicons.com/icon/rss) icon with a [plus](https://materialdesignicons.com/icon/plus) icon in the upper right. For the Channel, I would use the [cast](https://materialdesignicons.com/icon/cast) icon, and again, the plus icon in the upper right. I would then change the plus for a [close](https://materialdesignicons.com/icon/close) icon when removing/unsubscribing from the channel.

**Comment by MrGrigri** [comment]
Looking at this again, I believe that the [rss](https://materialdesignicons.com/icon/rss) icon would work best. As far as unsubscribe, I've created an rss-off icon. 

![rss](https://materialdesignicons.com/icon/rss) ![rss-off](https://user-images.githubusercontent.com/4528551/34572752-7265b054-f12f-11e7-9006-3bb5e003af54.png)

**Comment by caseytruelove** [comment]
What about something like this? I just made a variant off the email plus icon.


![email_subscribe](https://user-images.githubusercontent.com/16890791/46961998-02ff4b00-d070-11e8-9a11-a71be0b0de0a.jpg)
![email_unsubscribe](https://user-images.githubusercontent.com/16890791/46961999-0397e180-d070-11e8-8e42-de14f9d8077b.jpg)

**Comment by caseytruelove** [comment]
Here's a little better version of each:
![email_subscribe](https://user-images.githubusercontent.com/16890791/46967343-3e087b00-d07e-11e8-9b0d-312eb271f713.jpg)
![email_unsubscribe copy](https://user-images.githubusercontent.com/16890791/46967344-3e087b00-d07e-11e8-80d7-52afb48cde27.jpg)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/46968917-904b9b00-d082-11e8-846f-c50128f9cb19.png)![image](https://user-images.githubusercontent.com/1015040/46968931-9772a900-d082-11e8-8983-464c6e7156b3.png)
![image](https://user-images.githubusercontent.com/1015040/46968954-a3f70180-d082-11e8-8b71-3dbd273d41f2.png)![image](https://user-images.githubusercontent.com/1015040/46968969-ab1e0f80-d082-11e8-9249-fbd62a782d44.png)

[email-plus-minus.zip](https://github.com/Templarian/MaterialDesign/files/2479958/email-plus-minus.zip)

**Comment by goyney** [comment]
`email-plus` and `email-plus-outline` already exist:
![image](https://user-images.githubusercontent.com/1015040/46969138-17990e80-d083-11e8-9f74-9733720e14ca.png)![image](https://user-images.githubusercontent.com/1015040/46969128-0fd96a00-d083-11e8-8aa4-4ac75fc50e04.png)

**Comment by goyney** [comment]
Here's additions for the `email-minus` variation:
![image](https://user-images.githubusercontent.com/1015040/46969242-73fc2e00-d083-11e8-8374-8507203dff22.png)![image](https://user-images.githubusercontent.com/1015040/46969236-6d6db680-d083-11e8-8c97-3aaf8b2e9865.png)

[email-minus.zip](https://github.com/Templarian/MaterialDesign/files/2479975/email-minus.zip)

**Comment by MrGrigri** [comment]
This is great for 'email subscriptions'...however, not a general 'subscription'.

**Comment by goyney** [comment]
@MrGrigri Agreed. You're just too quick in responding for me to get this out:

![image](https://user-images.githubusercontent.com/1015040/46969522-52e80d00-d084-11e8-80f3-bf55952e0921.png)![image](https://user-images.githubusercontent.com/1015040/46969530-59768480-d084-11e8-86ef-64ae860336c9.png)

[newspaper-plus-minus.zip](https://github.com/Templarian/MaterialDesign/files/2479995/newspaper-plus-minus.zip)

**Comment by goyney** [comment]
FYI to @Templarian, there are 5 icons to add in this issue:

- [ ] rss-off
- [ ] email-minus
- [ ] email-minus-outline
- [ ] newspaper-plus
- [ ] newspaper-minus

**Comment by Templarian** [comment]
Added 😃
