### ISSUE TITLE
SVG assets of latest release

### ISSUE THREAD

**Issue by barrymieny** [Templarian/MaterialDesign#1494]
@Templarian when will the SVG assets from v1.7.22 be made available?

I'd like to start keeping [my Ruby gem](https://github.com/barrymieny/material_design_icons) version in step with your release versions.

**Comment by Templarian** [comment]
Just got back from vacation. Will try and get these updated shortly (so many emails to catch up on). Forgot to update the [design](https://materialdesignicons.com/design) page with the latest download.

**Comment by btimo** [comment]
Bump @Templarian

**Comment by Templarian** [comment]
😃 Yep... definitely need to do this. After I close on my Condo Friday and move in I'll be much more focused 😅. Hopefully I can find some time this weekend to quickly close out this issue. Top of my priority list!

**Comment by Templarian** [comment]
Issue #1759 has a link to the latest release that will be going out (it includes the CDN download for design assets).
