### ISSUE TITLE
Transparency icon

### ISSUE THREAD

**Issue by davioliveiira** [Templarian/MaterialDesign#1495]
![opacity](https://cloud.githubusercontent.com/assets/5223683/18374527/226238c0-7624-11e6-841f-d29668330ba0.jpeg)

**Comment by alexefremo** [comment]
As I know material icons don't have trasparency effect on any of them. So the 1st version is more "by rules" and the 2nd is as it "better" for my opinion

![ic_transparency_black_24px](https://cloud.githubusercontent.com/assets/3408199/18376006/7019981a-7674-11e6-9d83-206cd27d824e.png)
![ic_transparency2_black_24px](https://cloud.githubusercontent.com/assets/3408199/18376008/701c767a-7674-11e6-8bdf-13319da40544.png)

**Comment by JapanYoshi** [comment]
Doesn't the [opacity](https://materialdesignicons.com/icon/opacity) icon do its job?

Anyway, here's *my* take on opacity:
![rect4138](https://cloud.githubusercontent.com/assets/8707990/18417452/388576b8-786c-11e6-8f5a-dc760685b31f.png)
![rect4139](https://cloud.githubusercontent.com/assets/8707990/18417486/bfaffa78-786c-11e6-90c4-2b2173aeb7ad.png)
![rect4140](https://cloud.githubusercontent.com/assets/8707990/18417494/e24e5c14-786c-11e6-8276-b058600b70d3.png)
I think the third looks the most Material.

**Comment by CoDEmanX** [comment]
That's quite similar to https://design.google.com/icons/#ic_gradient

**Comment by PeterShaggyNoble** [comment]
Seems `opacity` and `gradient` are both suitable here so closing this out.

[![opacity](https://user-images.githubusercontent.com/15157491/33445906-4cf0d726-d5f6-11e7-8f81-f6361e192071.png)](https://materialdesignicons.com/icon/opacity) [![gradient](https://user-images.githubusercontent.com/15157491/33445992-8fb6dc04-d5f6-11e7-8809-31354b1470ec.png)](https://materialdesignicons.com/icon/gradient)

**Comment by EdnaldoNeimeg** [comment]
I realy need an "opacity" icon and neighter DROP and GRADIENT icons work for what i need.

Here's my suggestions: 

![opacity-1](https://user-images.githubusercontent.com/6233059/131428443-e22ee34e-3e03-4819-a4eb-93ae7f35fcc1.png)
![opacity-2](https://user-images.githubusercontent.com/6233059/131428444-544bb085-e75a-44be-b678-e66ed99d8237.png)
[opacity-icons.zip](https://github.com/Templarian/MaterialDesign/files/7080520/opacity-icons.zip)

**Comment by JapanYoshi** [comment]
> I realy need an "opacity" icon and neighter DROP and GRADIENT icons work for what i need.
> 
> Here's my suggestions:
> 
> ![opacity-1](https://user-images.githubusercontent.com/6233059/131428443-e22ee34e-3e03-4819-a4eb-93ae7f35fcc1.png)
> ![opacity-2](https://user-images.githubusercontent.com/6233059/131428444-544bb085-e75a-44be-b678-e66ed99d8237.png)
> [opacity-icons.zip](https://github.com/Templarian/MaterialDesign/files/7080520/opacity-icons.zip)

Neither complies with Material Design guidelines. Just use the `gradient` icon, as it is practically identical to your first suggestion.

**Comment by EdnaldoNeimeg** [comment]
Well, if you impose that it's not open for discussion...
We still don't have a decent opacity icon.

**Comment by JapanYoshi** [comment]
Well, what makes your off-model icon better, and why are the Material Design Icons *not* ✌decent✌?

**Comment by goyney** [comment]
Would any of the `blur` icons fit this?

[![blur](https://materialdesignicons.com/icon/blur)](https://materialdesignicons.com/icon/blur)[![blur-linear](https://materialdesignicons.com/icon/blur-linear)](https://materialdesignicons.com/icon/blur-linear)

---

The other option, which I kind of like, is to start a new `-opacity` trend. We can introduce `circle-opacity`. And then that answers the question on how to deal with #5884, where we could introduce `water-opacity`.

![image](https://user-images.githubusercontent.com/1015040/131522591-97fca0a2-4491-4172-a742-9adf5b71ccd6.png)![image](https://user-images.githubusercontent.com/1015040/131522644-ae7c01ff-bef4-40cc-8ee7-90afafaf3496.png)

**Comment by EdnaldoNeimeg** [comment]
What about this one?

![circle-opacity](https://user-images.githubusercontent.com/6233059/131695663-60fd8a2e-5779-4d09-b6e0-f9234142e8d2.png)

**Comment by goyney** [comment]
There's more complexity there, for sure, but I don't hate it. Several of the other contributors gave a thumbs up to my last suggestion, but we're waiting to cut the v6 release before adding more icons. Let's see if we get any feedback before I'm able to start adding new icons again, and we'll go from there. Thanks for the additional option!

**Comment by goyney** [comment]
[![circle-opacity](https://materialdesignicons.com/icon/circle-opacity)](https://materialdesignicons.com/icon/circle-opacity)[![square-opacity](https://materialdesignicons.com/icon/square-opacity)](https://materialdesignicons.com/icon/square-opacity)
