### ISSUE TITLE
Exam Icon (Test) needed

### ISSUE THREAD

**Issue by atul7398** [Templarian/MaterialDesign#1496]
it can be of two type 
1 : file type 
2: user writting exam

**Comment by alexefremo** [comment]
![ic_test_black_48px](https://cloud.githubusercontent.com/assets/3408199/18378766/3e226b34-7688-11e6-9cde-7d615134a835.png)
![ic_test2_black_48px](https://cloud.githubusercontent.com/assets/3408199/18378765/3e21172a-7688-11e6-9727-0378a6f2ff09.png)
![ic_test3_black_48px](https://cloud.githubusercontent.com/assets/3408199/18378767/3e2307f6-7688-11e6-8fd7-632e7e3e49f6.png)

**Comment by terreng** [comment]
How about something like this?

![image](https://user-images.githubusercontent.com/11605395/62893092-963ff600-bcfe-11e9-97fa-1420fc3261bf.png)
[exam-1.svg](https://github.com/terreng/samples/blob/master/exam-1.svg)

![image](https://user-images.githubusercontent.com/11605395/62893010-655fc100-bcfe-11e9-889a-712a8657a0e0.png)
[exam-2.svg](https://github.com/terreng/samples/blob/master/exam-2.svg)

**Comment by JapanYoshi** [comment]
“A+” is region-specific.

**Comment by terreng** [comment]
You're right. Maybe something like the [format-list-checks](http://materialdesignicons.com/icon/format-list-checks) icon?

**Comment by JapanYoshi** [comment]
I believe that would work, though modifications for the smaller size inside the document frame may be necessary.

**Comment by goyney** [comment]
Would our new `list-status` icon solve this use case?

[![list-status](https://materialdesignicons.com/icon/list-status)](https://materialdesignicons.com/icon/list-status)

**Comment by goyney** [comment]
We have a few options for this use case now, so I'm going to close this.
