### ISSUE TITLE
Discount, Sale Icon

### ISSUE THREAD

**Issue by SalElka** [Templarian/MaterialDesign#1497]
Icon suggestion: Maybe a price tag with a precentage symbol? Or a price tag with a star.

Great thanks!

**Comment by CoDEmanX** [comment]
[![sale](https://materialdesignicons.com/icon/sale)](https://materialdesignicons.com/icon/sale)

`discount` would be a meaningful alias.

**Comment by GreenTurtwig** [comment]
Also https://github.com/Templarian/MaterialDesign/issues/1479 could be used for similar things.

**Comment by Templarian** [comment]
Alias `discount` added to the `sale` icon.
