### ISSUE TITLE
SCSS and LESS

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#150]
This is partially coded already. It will be going into the next release. I'm using this issue to track progress and get review before pushing it out into the next font release.

- [x] SASS
- [x] SASS -> CSS
- [ ] LESS

**Comment by Templarian** [comment]
woff2 support completed. Implementing the rest of the SASS processing tonight. I'm going to update this issue tonight for reviewing the SASS. Need some feedback for the community.

**Comment by Templarian** [comment]
`v0.9.21-alpha` includes SASS. The next release will include the LESS support.

**Comment by javicebrian** [comment]
Hi @Templarian,

How is less implementation going? We need less to add some variables (like font path) and won't mind to collaborate.

Thanks,

J

**Comment by Templarian** [comment]
Pretty much non-existent. There seems to be little interest from the community. This is the first time anyone has mentioned LESS for like a year.

Will definitely take a pull request, but right now I'm really just focused on SASS as most of the open source projects have moved to it (also the webfont build process is built using SASS).

**Comment by Templarian** [comment]
Closing this issue. LESS will probably not be supported. It looks to be dying at this point.
