### ISSUE TITLE
GPS Unknown

### ISSUE THREAD

**Issue by dhivehi** [Templarian/MaterialDesign#1501]
Need a GPS off icon used in Google maps (as "ic_mylocation_off.png").
The icon can be viewed from this link: http://dhivehi.mv/images/ic_mylocation_off.png

**Comment by JamesCoyle** [comment]
Should be added as `crosshairs-unknown` to match existing icons.

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/62888643-93d89e80-bcf4-11e9-8ab5-711eecb8f5da.png)
[crosshairs-unknown.svg](https://github.com/terreng/samples/blob/master/crosshairs-unknown.svg)

**Comment by goyney** [comment]
Should be `crosshairs-question` with an alias of `unknown`.

**Comment by goyney** [comment]
[![crosshairs-question](https://materialdesignicons.com/icon/crosshairs-question)](https://materialdesignicons.com/icon/crosshairs-question)
