### ISSUE TITLE
Calendar icon with 24 as text

### ISSUE THREAD

**Issue by Abidhusain** [Templarian/MaterialDesign#1503]

**Comment by vishnu1991** [comment]
Is it ok?
![calendar-24](https://cloud.githubusercontent.com/assets/6689768/18606443/d84443b8-7ccd-11e6-8101-b0011a3a3bb1.png)
![calendar-48](https://cloud.githubusercontent.com/assets/6689768/18606444/d845604a-7ccd-11e6-98bd-6755e0d2e9dc.png)
[calendar_with_24.zip](https://github.com/Templarian/MaterialDesign/files/478003/calendar_with_24.zip)

**Comment by Abidhusain** [comment]
Yes @vishnu1991 , 
It is Perfect. 

Thanks for your valuable response.
