### ISSUE TITLE
bag-personal

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#1505]
Or a general bag icon

**Comment by MrGrigri** [comment]
I'm going to reopen this issue. All of the other `backpack` icon requests are for backpacking and not the bag itself. So I've decided to create one.

![backpack](https://user-images.githubusercontent.com/4528551/53037482-90e0ad80-3437-11e9-96d1-df1b3d775276.png) ![backpack-outline](https://user-images.githubusercontent.com/4528551/53037510-a3f37d80-3437-11e9-9dbd-20f38f30249a.png)

---
#### Files

[backpack.zip](https://github.com/Templarian/MaterialDesign/files/2881397/backpack.zip)

**Comment by goyney** [comment]
There are [backpack icons](https://github.com/Templarian/MaterialDesign/issues/2473#issuecomment-453172688) in the luggage issue from the Google set that have yet to be added.

**Comment by MrGrigri** [comment]
I thought that I saw them somewhere. I kind of like mine better, but I could be biased.

**Comment by goyney** [comment]
I like the bigger strap on yours, I'm not sure what the diamond's purpose is though.

**Comment by MrGrigri** [comment]
Most personal backpack have a brand/logo there.

**Comment by MrGrigri** [comment]
Here are some off variants as well

![bag-personal-off](https://user-images.githubusercontent.com/4528551/53038988-47925d00-343b-11e9-8b9f-3dbd325a3049.png) ![bag-personal-off-outline](https://user-images.githubusercontent.com/4528551/53039009-5711a600-343b-11e9-98cf-bf8f9c2e76e8.png)

---

### All Files

[bag-personal.zip](https://github.com/Templarian/MaterialDesign/files/2881484/bag-personal.zip)

**Comment by JamesCoyle** [comment]
These are so much better than Google's

**Comment by goyney** [comment]
Really like the `off` versions. I think I'd remove the diamond from the other versions though. Definitely better than Google's.

**Comment by Templarian** [comment]
Added. 😃
