### ISSUE TITLE
Money related

### ISSUE THREAD

**Issue by dbdevtop** [Templarian/MaterialDesign#1506]
Currency independent symbols for:
- [x] Budget - `sack`/`money-sack` #338
- [ ] Money spent
- [ ] Money saved - `piggybank` #1464
- [ ] Money lost
- [ ] Money donated
- [ ] Donate

**Comment by Templarian** [comment]
Do you have examples of each of these? You can paste inline images.

**Comment by JamesCoyle** [comment]
Yeah. The hard bit is currency independent. If I remember correctly there was another issue where we couldn't find a good solution for it.

**Comment by dbdevtop** [comment]
Too bad I have no examples yet at hand. 

Since I have no experience in graphic design I searched over [iconfinder](https://www.iconfinder.com/search/?q=budget&type=vector) and was overwhelmed by the variety of styles. 

If someone here is able to create icons in the Material Design taste I could make a list of inspirations I found.

**Comment by Templarian** [comment]
@dbdevtop We just need a general idea of what you are thinking. One of the contributors will create the icon in the correct style.

**Comment by dbdevtop** [comment]
Maybe this:
![14-09-_2016_17-11-20](https://cloud.githubusercontent.com/assets/22170617/18518666/34799ce8-7aa1-11e6-821b-1561348e2f90.jpg)

**Comment by alexefremo** [comment]
This is for budget:

![ic_budget_black_24px](https://cloud.githubusercontent.com/assets/3408199/18775597/49e8903e-817c-11e6-8d86-5ea48983f374.png)
![ic_budget_black_48px](https://cloud.githubusercontent.com/assets/3408199/18775596/49e45b7c-817c-11e6-801e-c55909f72692.png)

This is for money saved:

https://github.com/Templarian/MaterialDesign/issues/1464

**Comment by adrogon** [comment]
Please consider the ["currency sign"](https://en.wikipedia.org/wiki/Currency_sign_(typography)) when it comes to currency independent symbols.

Also opened #2030 for it to be added to the library.

**Comment by damianobarbati** [comment]
+1 for the budget icon, very much needed to indicate amount invested on something or available funds

**Comment by JamesCoyle** [comment]
Gonna close this out. If anyone still needs these icons and they aren't covered by other requests, please open a new issue for each so it can be better tracked. Please make sure to add an example of what the icon can look like that doesn't include currency symbols as we need to make sure icons are internationally recognizable.
