### ISSUE TITLE
bed-empty

### ISSUE THREAD

**Issue by truedem** [Templarian/MaterialDesign#1507]
Google's "bed" icon has a human in it so it's not usable for amount of beds for a real estate property: it can be deciphered as "amount of places for sleep" which is usually twice higher than amount of beds.

P.S. Thanks for your wonderful work!

**Comment by DavidEdwards** [comment]
Like this?

![bed1](https://cloud.githubusercontent.com/assets/1585923/19190240/b3f172ae-8c9c-11e6-80ae-32b5558f6c8b.png)

**Comment by truedem** [comment]
Both are fine.
(I've made variant without a blanket and pillow - it looks unhospitable)

**Comment by 1010451** [comment]
let me know when that side bed without human is avaliable

**Comment by 1010451** [comment]
is it possible to use our own icons on our app or they have to be inside icon font?
thx

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/31056085-358bb724-a6c4-11e7-8dc9-8e92fea7cf82.png)
![image](https://user-images.githubusercontent.com/15905797/31056089-401b4efc-a6c4-11e7-8ce4-35c2980a3cd2.png)
[bed-empty.zip](https://github.com/Templarian/MaterialDesign/files/1347244/bed-empty.zip)

**Comment by Templarian** [comment]
[![bed-empty](https://materialdesignicons.com/icon/bed-empty)](https://materialdesignicons.com/icon/bed-empty)

We may want to rename hotel eventually, not sure.
