### ISSUE TITLE
Door - icon request

### ISSUE THREAD

**Issue by truedem** [Templarian/MaterialDesign#1508]
Half-opened door could be very useful for "entrance", "exit" etc. buttons.

P.S. Thanks for the great site and icons!

**Comment by JamesCoyle** [comment]
Do you have any examples of how that can be shown with only two dimensions?

**Comment by truedem** [comment]
Like this for example:
https://cdn2.iconfinder.com/data/icons/mobile-interface-1/512/mobile_interface-01-512.png
or
http://image.flaticon.com/icons/svg/32/32567.svg
or
https://cdn0.iconfinder.com/data/icons/office-set-2/512/21-128.png

**Comment by JamesCoyle** [comment]
The problem is they use the third dimension by using perspective. We can't do that in material design.

**Comment by truedem** [comment]
This is hopeless then. Thanks for checking!
