### ISSUE TITLE
Stadium icon

### ISSUE THREAD

**Issue by dhivehi** [Templarian/MaterialDesign#1509]
Stadium icon needed

**Comment by MrGrigri** [comment]
How about this:

![asset 1 4x](https://cloud.githubusercontent.com/assets/4528551/18650681/9dbfe7f8-7e83-11e6-9618-045b4194affc.png)
![asset 1](https://cloud.githubusercontent.com/assets/4528551/18650682/9dc436d2-7e83-11e6-9371-ca233be3d7a3.png)

[stadium.zip](https://github.com/Templarian/MaterialDesign/files/481242/stadium.zip)

**Comment by alexefremo** [comment]
Or this:

![ic_stadium_black_24px](https://cloud.githubusercontent.com/assets/3408199/18775134/2ae2f6dc-8179-11e6-92ef-73440bbf9293.png)
![ic_stadium_black_48px](https://cloud.githubusercontent.com/assets/3408199/18775135/2ae8bd88-8179-11e6-9ba8-dd9e52551f53.png)

**Comment by Templarian** [comment]
The top one looks too much like a castle unfortunately @MrGrigri. Went with a modified version of @alexefremo's.

[![stadium](https://materialdesignicons.com/icon/stadium)](https://materialdesignicons.com/icon/stadium)
