### ISSUE TITLE
heart-plus

### ISSUE THREAD

**Issue by FiestaUSA** [Templarian/MaterialDesign#1512]
A heart with a small plus in the top-right corner to use for "Add to favorites"

**Comment by vishnu1991** [comment]
Is this ok?
![finder](https://cloud.githubusercontent.com/assets/6689768/18598919/24fc7938-7c73-11e6-9de6-7894111cfa56.png)

[heart_with_plus.zip](https://github.com/Templarian/MaterialDesign/files/477586/heart_with_plus.zip)

**Comment by GreenTurtwig** [comment]
Personally I don't think this is needed at all. All apps I've seen and used (even Google's own) use an outlined heart (or star) to add to favorites and become solid when added. :-)

**Comment by FiestaUSA** [comment]
Yeah that looks perfect! That was so quick!!

**Comment by JamesCoyle** [comment]
Yeah the icon is pretty redundant IMO. This use case can easily be solved using proper UI context and making use of the outline version and/or color. The SVG is there if you need it but I don't think this needs adding.
