### ISSUE TITLE
Smoke / Smog

### ISSUE THREAD

**Issue by xsorifc28** [Templarian/MaterialDesign#1513]
requesting

**Comment by RobertoGraham** [comment]
Smog:
![image](https://cloud.githubusercontent.com/assets/14958777/20938885/a1507876-bbe4-11e6-9a81-60775a7b5592.png)
[smog.zip](https://github.com/Templarian/MaterialDesign/files/634725/smog.zip)

**Comment by CoDEmanX** [comment]
I believe InkScape 0.91's strange way of handling the 90 to 96 dpi conversion messed up the SVG. I fixed that and put the icon back on grid. Also merged the shapes into a single path:

![image](https://user-images.githubusercontent.com/1309249/38770289-0068ffac-4011-11e8-8deb-302b77b0f7a0.png)

[smog.zip](https://github.com/Templarian/MaterialDesign/files/1910597/smog.zip)

**Comment by Templarian** [comment]
[![smog](https://materialdesignicons.com/icon/smog)](https://materialdesignicons.com/icon/smog)
