### ISSUE TITLE
Chromebox 

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#1515]
Modeled after the most popular model, the [ASUS Chromebox](http://i.imgur.com/EKBkSdf.jpg). This could be used in the[ Recent Tabs screen](http://i.imgur.com/aLWoza5.png) in Chrome for Android and iOS. Currently, Chromeboxes have the "[laptop-chromebook](https://materialdesignicons.com/icon/laptop-chromebook)" icon.

**Comment by k5cents** [comment]
Maybe something like [this](http://i.imgur.com/1DfFmdR.png)? I am really bad at this, it's my first attempt. I think the Chromebox alone isn't iconic enough.

**Comment by GreenTurtwig** [comment]
I was thinking about a Chrome logo in a an outlined box, but that just doesn't work. :-/  
Your design is actually pretty good, hopefully I'll figure out a way to make a similar one.

**Comment by JamesCoyle** [comment]
I'm gonna close this out as its a pretty niche product. The `google-chrome` icon could likely handle this.

[![](https://materialdesignicons.com/icon/google-chrome
)](https://materialdesignicons.com/icon/google-chrome)
