### ISSUE TITLE
Train station icon

### ISSUE THREAD

**Issue by qaisers** [Templarian/MaterialDesign#1518]

**Comment by Templarian** [comment]
Do you have an example of this (images can be pasted inline)?

**Comment by JamesCoyle** [comment]
Can we fit a person alongside the vehicles? I think that would be a good icon for boarding the various modes of transport. If I remember correctly we were struggling to find an international icon for a bus stop too.

**Comment by qaisers** [comment]
these the the closest icons that look meaninful. for bus stop and train
station.

also see related images

https://goo.gl/images/FOIHr2

**Comment by vishnu1991** [comment]
I think this would be perfect for  train station. 
![train-station icon](https://cloud.githubusercontent.com/assets/6689768/18751928/6d02ff42-80fe-11e6-95c8-418709dbaeb5.png)
Image Credit: https://thenounproject.com/term/train-station/20269/

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
