### ISSUE TITLE
speed

### ISSUE THREAD

**Issue by Ph1b** [Templarian/MaterialDesign#152]
Hey, it would be great to have an icon representing speed.
At the moment I'm using timelapse for my project, but that causes a lot confusion: https://raw.githubusercontent.com/Ph1b/MaterialAudiobookPlayer/master/audiobook/src/main/res/drawable-xxhdpi/ic_timelapse_white_24dp.png

**Comment by Templarian** [comment]
Do you mean like a Speedometer (added: http://materialdesignicons.com/icon/speedometer)?

I'm not sure if a vehicle metaphor you wanted, or would like 3 lines to the left of a clock work better?

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/clock-fast

**Comment by Ph1b** [comment]
Yeah, perfect! [Thanks a lot!](https://github.com/Ph1b/MaterialAudiobookPlayer/commit/d8357e7bf5cbb1e892a85421ba9373d96f7ef5d7)
