### ISSUE TITLE
NFC Tag Scan Icon

### ISSUE THREAD

**Issue by mdredmond** [Templarian/MaterialDesign#1520]

**Comment by Templarian** [comment]
@mdredmond As a learning opportunity and to make icons easy to find, is there another search term I could attach to make this easier to find on the site?

**Comment by mdredmond** [comment]
I was a bit boneheaded and actually didn't search for NFC.  I searched for 'scan' and saw nice icons for barcodes, QR codes, etc., but no NFC and just assumed it didn't exist.   It's been a long week and I'm tired.  You might add 'scan' but otherwise it's good.  Thanks for all of your contributions to this library.  It's amazing.
