### ISSUE TITLE
Register (as in, sign up) Icon

### ISSUE THREAD

**Issue by mdredmond** [Templarian/MaterialDesign#1521]

**Comment by GreenTurtwig** [comment]
This has been discussed before and it the "account-plus" icon was chosen as the most suitable. :-)

**Comment by Templarian** [comment]
@mdredmond If you have any examples or any other ideas of the look of this icon we can keep this issue opened, but if not we'll close it shortly.

**Comment by mdredmond** [comment]
Nope, account-plus is perfect.  I would suggest tagging it with 'register' but beyond that it's perfect.  Thanks!

**Comment by Templarian** [comment]
Alias `register` added to `account-plus`.
