### ISSUE TITLE
square root

### ISSUE THREAD

**Issue by jonescr3** [Templarian/MaterialDesign#1522]
something like sqrt(x) seen below -->
https://docs.google.com/drawings/d/145qNBjseB_tTljDXi2x8leFQ0T0FAius-qYeTOCBMOQ/edit

**Comment by Templarian** [comment]
I'm going to lump this in with the existing #180 issue.

**Comment by Templarian** [comment]
Marked it as high priority since we should have the rest in the pack for those doing mathematical applications which I assume is common.
