### ISSUE TITLE
Police station Icon

### ISSUE THREAD

**Issue by dineshoxilo** [Templarian/MaterialDesign#1525]

**Comment by JamesCoyle** [comment]
Need some ideas of what this would look like. Might be hard to pull off in the 24dp grid

**Comment by Xenomorph99** [comment]
I used [hospital-building](https://materialdesignicons.com/icon/hospital-building) and [police-badge](https://materialdesignicons.com/icon/police-badge) to come up with this idea:

![police-station](https://user-images.githubusercontent.com/1837101/95632459-ecafde00-0a42-11eb-907c-4d8d83ef9ac2.png)
[police-station.zip](https://github.com/Templarian/MaterialDesign/files/5357606/police-station.zip)

**Comment by temaprint** [comment]
many icons
look here
https://icons8.com/icons/set/police-station
<img src="https://img.icons8.com/metro/40/000000/police-station.png"/><img src="https://img.icons8.com/ultraviolet/40/000000/police-station.png"/><img src="https://img.icons8.com/office/40/000000/police-station.png"/>

**Comment by goyney** [comment]
[![police-station](https://materialdesignicons.com/icon/police-station)](https://materialdesignicons.com/icon/police-station)
