### ISSUE TITLE
Widgets icon

### ISSUE THREAD

**Issue by Danki567** [Templarian/MaterialDesign#1526]
Please create a widgets icon

**Comment by Templarian** [comment]
What does a widgets icon look like?

**Comment by GreenTurtwig** [comment]
I'm assuming something like the one on Android.
![screenshot_20160924-195504](https://cloud.githubusercontent.com/assets/15905797/18810545/35ea1556-8291-11e6-8956-80f6ff89a768.png)

**Comment by Templarian** [comment]
Frogot abotu that icon on that screen. Yea, we can get that official one added.

**Comment by Templarian** [comment]
[![widgets](https://materialdesignicons.com/icon/widgets)](https://materialdesignicons.com/icon/widgets)
