### ISSUE TITLE
Atom/Orbit Icon

### ISSUE THREAD

**Issue by firefly07** [Templarian/MaterialDesign#1527]
Please add an atom/orbit icon (could be used for both)

Example:
http://png.clipart.me/graphics/thumbs/174/black-vector-illustration-of-atom-icon-on-white_174523097.jpg

**Comment by DavidEdwards** [comment]
Carbon atomic shell?

![atom-carbon-shell](https://cloud.githubusercontent.com/assets/1585923/19189327/c49b3144-8c97-11e6-8b82-beb1e8cf6e21.png)

**Comment by casesandberg** [comment]
![image](https://cloud.githubusercontent.com/assets/4633636/20741336/70353c56-b67e-11e6-8ed9-56a63f57ffce.png)

[atom-icon.zip](https://github.com/Templarian/MaterialDesign/files/621087/atom-icon.zip)

**Comment by MrGrigri** [comment]
Is this a brand icon request or simply an atomic atom icon request? @casesandberg that looks like Atom's (The code editor) icon.

**Comment by Templarian** [comment]
Yea, that's their editor's logo, so we can't add that (and we generally only add social media logos). It will have to be a different design.

**Comment by RobertoGraham** [comment]
Orbit icon. I don't think it can be used for an atom icon.

![image](https://cloud.githubusercontent.com/assets/14958777/20870182/8c5f2968-ba7b-11e6-9369-4dd3283ad9f4.png)

[orbit.zip](https://github.com/Templarian/MaterialDesign/files/629920/orbit.zip)

**Comment by RobertoGraham** [comment]
Made a separate atom icon just in case
![image](https://cloud.githubusercontent.com/assets/14958777/20870466/7b07f050-ba80-11e6-8249-f9a07a9f6982.png)
[atom.zip](https://github.com/Templarian/MaterialDesign/files/629938/atom.zip)

**Comment by GriNAME** [comment]
Don't forget about [Atom](https://atom.io/) )))

**Comment by Templarian** [comment]
@RobertoGraham Let me know when you hit 5 icons and we'll assign you as a contributor.

[![atom](https://materialdesignicons.com/icon/atom)](https://materialdesignicons.com/icon/atom)

**Comment by Templarian** [comment]
You know what I actually really like the orbit icon also. Adding that one also.

[![orbit](https://materialdesignicons.com/icon/orbit)](https://materialdesignicons.com/icon/orbit)
