### ISSUE TITLE
Light viewing

### ISSUE THREAD

**Issue by AravK** [Templarian/MaterialDesign#1528]
Could you guys please make the site lightweight? I try viewing it from my RPi2B with Chromium, but it's veeeerrrryyyy slow. <b>Really</b> slow. COuld you please easen the strain on tiny computers? Perhaps clear off some extra elements?
And please make some sort of Linux/Win/etc. package to download icons(SVG, PNG, etc) at ease, with a search?

**Comment by Templarian** [comment]
This will be happening during the recode to Angular2. A couple years ago when I created the site it wasn't so bad when there were a lot fewer SVGs to render. SVG is a little more taxing to render.

http://cdn.materialdesignicons.com/1.7.22/ You can view it from the CDN also or the Chrome/Firefox web browser extensions (MaterialDesignIcons Picker).

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site this is going to be the repo going forward. I'll do an initial commit one of these days with the progress and starting structure. The goal of this site will be performance first.
