### ISSUE TITLE
Open Hand / Move icon

### ISSUE THREAD

**Issue by dietrichg** [Templarian/MaterialDesign#1529]
In addition to the 4 arrow move icon, we should also have an open hand "Move Tool" icon, like in most graphical application that involve panning.

**Comment by PeterShaggyNoble** [comment]
This is Google's [`pan tool`](https://material.io/icons/#ic_pan_tool) icon.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48992071-fd336580-f103-11e8-97bb-983503e6c47a.png)
[pan-tool.svg.zip](https://github.com/Templarian/MaterialDesign/files/2613999/pan-tool.svg.zip)

**Comment by Templarian** [comment]
Added! `hand-left` and `hand-right`.
