### ISSUE TITLE
Details icon

### ISSUE THREAD

**Issue by zhulduz** [Templarian/MaterialDesign#153]
Hello!
It would be great to add an icon "details".

Thanks.

**Comment by chrislitherland95** [comment]
Hi Zhulduz.
To represent this properly, it'd be best to know what details you are trying to convey and what the icon should represent.

**Comment by zhulduz** [comment]
It looks like this
http://google.github.io/material-design-icons/image/svg/ic_details_24px.svg

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/details

That is a weird stock icon. I added it, might rename it in the future and give it an alias. We'll see.
