### ISSUE TITLE
Truck trailer / cistern  icon

### ISSUE THREAD

**Issue by snuuve** [Templarian/MaterialDesign#1530]
Expamles:

http://securefleetmanagement.com.au/wp-content/uploads/2015/11/Truck-Icon-09.png

https://d30y9cdsu7xlg0.cloudfront.net/png/5087-200.png

**Comment by MrGrigri** [comment]
Here is one for a trailer, much like the [RV Hookup](https://design.google.com/icons/#ic_rv_hookup). I believe that a semi trailer would be too long and not recognizable in a 24X24 pixel icon.

![trailer](https://cloud.githubusercontent.com/assets/4528551/18885733/1ec5bd38-84aa-11e6-81cb-4948a23d2e81.png)

![trailer 4x](https://cloud.githubusercontent.com/assets/4528551/18885732/1eaf30c2-84aa-11e6-9641-a280c24d7f0c.png)

**Comment by GreenTurtwig** [comment]
Looks a little bit like a caravan with no windows, or a horse carrier to me as well. :-)

**Comment by CoDEmanX** [comment]
Maybe make the wheel a bit larger?

**Comment by MrGrigri** [comment]
This was my idea of a 'Uhaul' trailer approach, not a flat bed. 

![Uhaul Trailer](http://idolosol.com/images/u-haul-trailer-2.jpg)

**Comment by Templarian** [comment]
[![truck-trailer](https://materialdesignicons.com/icon/truck-trailer)](https://materialdesignicons.com/icon/truck-trailer)
