### ISSUE TITLE
Piggy Bank / Moneybox icon

### ISSUE THREAD

**Issue by mbocher** [Templarian/MaterialDesign#1533]
2 versions if possible, 1 full and 1 empty...

I think it's not necessary to place a currency on the coin (like dollars or euros).

Here is an example : https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/moneybox.png

Thank you,
Maxence

**Comment by GreenTurtwig** [comment]
There's already been a piggy bank icon requested and submitted here: https://github.com/Templarian/MaterialDesign/issues/1464 :-)
