### ISSUE TITLE
pencil-circle

### ISSUE THREAD

**Issue by eghernqvist** [Templarian/MaterialDesign#1535]
Just like delete-circle I think we should have a circle version of pencil-box.

**Comment by GreenTurtwig** [comment]
Here :-)
![puush-linux 2016-09-30 at 09 04 31](https://cloud.githubusercontent.com/assets/15905797/18984884/05b67e96-86ed-11e6-9ea6-d2e9dae66bd4.png)
![puush-linux 2016-09-30 at 09 05 03](https://cloud.githubusercontent.com/assets/15905797/18984888/07014484-86ed-11e6-929d-e4dd66f0cc76.png)
[pencil-circle.zip](https://github.com/Templarian/MaterialDesign/files/502386/pencil-circle.zip)

**Comment by Templarian** [comment]
[![pencil-circle](https://materialdesignicons.com/icon/pencil-circle)](https://materialdesignicons.com/icon/pencil-circle)
