### ISSUE TITLE
mushroom icon

### ISSUE THREAD

**Issue by HKV-Kim** [Templarian/MaterialDesign#1536]
mushroom

**Comment by GreenTurtwig** [comment]
Do you have any example and or examples of it's use? :cat:

**Comment by Templarian** [comment]
![image](https://cloud.githubusercontent.com/assets/338885/18970167/d2b0ca20-8655-11e6-8c54-9d68c8e9a1ed.png)?

**Comment by GreenTurtwig** [comment]
Ha, yeah! Totally want that as an icon now. :heart:

**Comment by HKV-Kim** [comment]
Thanks for everything

**Comment by HKV-Kim** [comment]
Thanks for everything! But I wanted a female icon series feelings expressed
on mushrooms: like, being in love, laugh, wow, infuriating, sad it looks
like on Facebook section. And this is a demo.

You can not edit emotion. That's pretty good

Vào 30-09-2016 05:31, "Nguyễn Kim" <nguyenkim.itvn@gmail.com> đã viết:

Thanks for everything

**Comment by HKV-Kim** [comment]
Vào 30-09-2016 05:50, "Nguyễn Kim" <nguyenkim.itvn@gmail.com> đã viết:

> Thanks for everything! But I wanted a female icon series feelings
> expressed on mushrooms: like, being in love, laugh, wow, infuriating, sad
> it looks like on Facebook section. And this is a demo.
>
> You can not edit emotion. That's pretty good
>
> Vào 30-09-2016 05:31, "Nguyễn Kim" <nguyenkim.itvn@gmail.com> đã viết:
>
> Thanks for everything
>
>
>
>

**Comment by HKV-Kim** [comment]
Hat multicolored design on it, and the same demo under the same demo I just
attach emotions as I said above. thank you

Vào 30-09-2016 06:10, "Nguyễn Kim" <nguyenkim.itvn@gmail.com> đã viết:

>
> Vào 30-09-2016 05:50, "Nguyễn Kim" <nguyenkim.itvn@gmail.com> đã viết:
>
>> Thanks for everything! But I wanted a female icon series feelings
>> expressed on mushrooms: like, being in love, laugh, wow, infuriating, sad
>> it looks like on Facebook section. And this is a demo.
>>
>> You can not edit emotion. That's pretty good
>>
>> Vào 30-09-2016 05:31, "Nguyễn Kim" <nguyenkim.itvn@gmail.com> đã viết:
>>
>> Thanks for everything
>>
>>
>>
>>

**Comment by JamesCoyle** [comment]
I'm closing this as it is way out of the scope of this project.

**Comment by HKV-Kim** [comment]
Why close??

Vào 30-09-2016 06:22, "James Coyle" <notifications@github.com> đã viết:

**Comment by JamesCoyle** [comment]
We are focused on making general purpose icons which follow material design guidelines and are free for use. From what I can gather you are asking for a set of emoticons or stickers with a particular style. That is not what this project covers. I'd suggest you look to hire a professional artist/graphic designer.

**Comment by Templarian** [comment]
A mushroom icon is also fairly difficult to show in a 24x24 monochrome style unfortunately.

**Comment by HKV-Kim** [comment]
Yes! I understand thanks for explanation. Thanks for everything

Vào 30-09-2016 06:28, "Austin Andrews" <notifications@github.com> đã viết:
