### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by christhoval06** [Templarian/MaterialDesign#1538]
I create an icon for a 
![webpage](https://cloud.githubusercontent.com/assets/7133189/18968703/af85abb6-864f-11e6-9834-f2c3c056ed59.png)

**Comment by christhoval06** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<svg width="20px" height="20px" viewBox="0 0 20 20" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    
    <title>shape</title>
    <desc>Created with Sketch.</desc>
    <defs></defs>
    <g id="iOS-&amp;-Android" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="about-us" transform="translate(-88.000000, -147.000000)" fill="#474747">
            <g id="template" transform="translate(85.000000, 144.000000)">
                <g id="Group">
                    <path d="M3,4.99079514 C3,3.89130934 3.89821238,3 4.99079514,3 L21.0092049,3 C22.1086907,3 23,3.89821238 23,4.99079514 L23,21.0092049 C23,22.1086907 22.1017876,23 21.0092049,23 L4.99079514,23 C3.89130934,23 3,22.1017876 3,21.0092049 L3,4.99079514 Z M4.62878788,8.125 L21.3712121,8.125 L21.3712121,21.125 L4.62878788,21.125 L4.62878788,8.125 Z M19.4015152,5.61142731 C19.4015152,5.20470974 19.7293698,4.875 20.1401515,4.875 C20.5480891,4.875 20.8787879,5.203843 20.8787879,5.61142731 L20.8787879,5.76357269 C20.8787879,6.17029026 20.5509332,6.5 20.1401515,6.5 C19.7322139,6.5 19.4015152,6.171157 19.4015152,5.76357269 L19.4015152,5.61142731 Z M17.4318182,5.61142731 C17.4318182,5.20470974 17.7596729,4.875 18.1704545,4.875 C18.5783921,4.875 18.9090909,5.203843 18.9090909,5.61142731 L18.9090909,5.76357269 C18.9090909,6.17029026 18.5812362,6.5 18.1704545,6.5 C17.7625169,6.5 17.4318182,6.171157 17.4318182,5.76357269 L17.4318182,5.61142731 Z M15.4621212,5.61142731 C15.4621212,5.20470974 15.7899759,4.875 16.2007576,4.875 C16.6086952,4.875 16.9393939,5.203843 16.9393939,5.61142731 L16.9393939,5.76357269 C16.9393939,6.17029026 16.6115392,6.5 16.2007576,6.5 C15.79282,6.5 15.4621212,6.171157 15.4621212,5.76357269 L15.4621212,5.61142731 Z M13.9848485,14.0833333 L20.3863636,14.0833333 L20.3863636,15.7083333 L13.9848485,15.7083333 L13.9848485,14.0833333 Z M13.9848485,16.7916667 L20.3863636,16.7916667 L20.3863636,20.0416667 L13.9848485,20.0416667 L13.9848485,16.7916667 Z M5.61363636,14.0833333 L13,14.0833333 L13,20.0416667 L5.61363636,20.0416667 L5.61363636,14.0833333 Z M5.61363636,9.20833333 L20.3863636,9.20833333 L20.3863636,13 L5.61363636,13 L5.61363636,9.20833333 Z" id="shape"></path>
                </g>
            </g>
        </g>
    </g>
</svg>

**Comment by Templarian** [comment]
This is covered by the application icon. Material Design aims at the minimalist representation so no buttons or extras. Just the window. It also makes it OS independent, thus more multipurpose.

[![application](https://materialdesignicons.com/icon/application)](https://materialdesignicons.com/icon/application)

**Comment by christhoval06** [comment]
ok
