### ISSUE TITLE
Icon for pdb (protein data bank) file

### ISSUE THREAD

**Issue by dhruvkb** [Templarian/MaterialDesign#1540]
Used to represent macromolecules like proteins on computer systems

**Comment by JamesCoyle** [comment]
This is way too specific for this project IMO. The only use case I see is in professional software systems in which the main focus is not simplistic UI design. It is also very difficult to show that within the limited space that is available (24x24px).

**Comment by dhruvkb** [comment]
I made an icon using two of your icons. If you feel that this icon is good enough, please add it to your repo.
[icon.zip](https://github.com/Templarian/MaterialDesign/files/503612/icon.zip)

**Comment by Templarian** [comment]
Agreed with @JamesCoyle. Sorry not all icons can be included.

If you have any requests that are more generic we can work on getting those added though. Thanks!
