### ISSUE TITLE
record-rec is not centered

### ISSUE THREAD

**Issue by PhilLab** [Templarian/MaterialDesign#1541]
The icon _record-rec_ is not centered

**Comment by JamesCoyle** [comment]
It may have just been moved slightly to better align the text with the pixel grid but I'm not too sure on that.

**Comment by Templarian** [comment]
[![record-rec](https://materialdesignicons.com/icon/record-rec)](https://materialdesignicons.com/icon/record-rec)

I don't think this is a bug, if I use the github preview feature with the grid it looks like the text is pixel perfect and the circle was adjusted 1 pixel to accommodate the text centering. Any alteration would cause the pixel alignment to be off.

I'll leave this issue opened for a little while if someone can design an alternative.
