### ISSUE TITLE
Bullhorn Outline

### ISSUE THREAD

**Issue by D0Gmatist** [Templarian/MaterialDesign#1543]
Add the speaker icon 

> http://image.prntscr.com/image/50610da2378b4b2da5d37541ce070d7e.png

**Comment by CoDEmanX** [comment]
We have a bullhorn icon: https://materialdesignicons.com/icon/bullhorn

**Comment by D0Gmatist** [comment]
outline

**Comment by MrGrigri** [comment]
I believe making the bullhorn that we already have into an outline wouldn't work visually. Look at the smallest one, and imagine it as an outline.

![bullhorn](https://materialdesignicons.com/icon/bullhorn)

**Comment by Templarian** [comment]
I think this icon might need to be resized slightly by 2px width. Right now it looks "off". Just something to look into.

**Comment by MrGrigri** [comment]
Here is an outlined version with the same/current dimensions of the current bullhorn.

![bullhorn-outline](https://user-images.githubusercontent.com/4528551/43995583-bd92b870-9d6d-11e8-9872-719516ea5924.png)

[bullhorn-outline.zip](https://github.com/Templarian/MaterialDesign/files/2280507/bullhorn-outline.zip)

**Comment by MrGrigri** [comment]
Based on #3463, here is a redesigned `bullhorn-outline`

![image](https://user-images.githubusercontent.com/4528551/45318916-971f4500-b4fb-11e8-9372-a377bbda77ae.png)

[Asset 4.zip](https://github.com/Templarian/MaterialDesign/files/2368076/Asset.4.zip)

**Comment by Templarian** [comment]
Done.
