### ISSUE TITLE
FAQ icon

### ISSUE THREAD

**Issue by ganeshjkulakarni** [Templarian/MaterialDesign#1544]

**Comment by GreenTurtwig** [comment]
Will https://materialdesignicons.com/icon/comment-question-outline work for that? :cat2:

**Comment by PeterShaggyNoble** [comment]
https://materialdesignicons.com/icon/help-circle & https://materialdesignicons.com/icon/help-circle-outline would also work.

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback from OP.
