### ISSUE TITLE
File delete icon

### ISSUE THREAD

**Issue by Lemick** [Templarian/MaterialDesign#1547]
I haven't found that icon :)

**Comment by GreenTurtwig** [comment]
There a quite a few delete icons? Won't https://materialdesignicons.com/icon/delete work?

**Comment by Lemick** [comment]
Thanks for your reply. Yeah it works, but I wanted something more specific (for deleting a file you've uploaded for example)

**Comment by Lemick** [comment]
I thought of a 'file' icon with a 'close' icon on it

**Comment by GreenTurtwig** [comment]
Yeah that could work. :smile_cat:  
There's already one with a check on it so another with a cross is logical.

**Comment by MrGrigri** [comment]
Like these found [here](https://github.com/Templarian/MaterialDesign/issues/1240)? Look at the bottom.

**Comment by Lemick** [comment]
Yeah thanks :)

**Comment by goyney** [comment]
Looks like `file-remove` was added in #1240.
