### ISSUE TITLE
ICON for Dinner,Desserts

### ISSUE THREAD

**Issue by rutvik-coditas** [Templarian/MaterialDesign#1549]
Please i need icons Desserts,Dinner,Lunch,Bar,Breakfast for IOS application.

Thank you

**Comment by JamesCoyle** [comment]
I'd really recommend sticking to the iOS interface for iOS apps. Material design is great but it would be really annoying to buy an android phone and then have a bunch of apps use the iOS style so it must also be annoying for Apple users to see Material Design apps. 

That being said, we do have a few food related icons which you can search for such as `bowl`, `food`, `food-apple`, and `beer` which may do what you want.

**Comment by goyney** [comment]
- Dessert - `cake`, `cupcake`, `cookie`, `ice-cream`
- Lunch/Dinner - `food`, `taco`, `rice`, `pizza`
- Breakfast - `apple`, `food-croissant`, `coffee`, `tea`
- Bar - `beer`, `glass-mug`, `bottle-wine`, `glass-wine`

Pretty sure we have all these covered. If you have suggestions for more specific icons, please open a new request for each individual idea. Thanks!
