### ISSUE TITLE
Right-click download is not working.

### ISSUE THREAD

**Issue by muffinjello** [Templarian/MaterialDesign#155]
Hello,

I used to be able to right click on icons and select a size/type to download (48x48, SVG, etc.). However, I just tried to do this right click download, and nothing happens. The default right click menu doesn't pop up either. The default right click menu does however pop up when clicking somewhere else.

Same results on Google Chrome and FireFox, so I don't think it's an issue on my side, but I'll give it a look later.

I really want to see the ability to download icons individually (no .zip) to come back - unzipping things and organizing things is just too much of a hassle. I'm usually just copy/pasting icons into photoshop, and this slows down my workflow quite a bit.

**Comment by Templarian** [comment]
That's a bug I completely recoded the modal window last week then got distracted rewriting the font generation to include SASS and LESS. Give me a minute to fix it.

Thanks for filing an issue. :smile:

**Comment by Templarian** [comment]
You can still right click on the individual icons for right now, but I'll have the fix in a couple of minutes for the modal screen.

![image](https://cloud.githubusercontent.com/assets/338885/6200559/75a2bf18-b443-11e4-8659-dc725d325654.png)

**Comment by Templarian** [comment]
Fixed. While I have someone here that uses this feature, are there any other formats or features you would like on the right click menu?
