### ISSUE TITLE
Phone Message (phone-message-outline?)

### ISSUE THREAD

**Issue by dintendocoltd** [Templarian/MaterialDesign#1551]
Would it possible to request a `mdi mdi-cellphone` icon but with a `mdi mdi-message-text` or `mdi message-text-outline` on the right hand side of it to portray a phone message.

I've also added a mockup/suggestion of what the icon should look like (apologies if this looks terrible, icon design isn't really my strong point);

![mdi mdi-phone-message-outline](https://cloud.githubusercontent.com/assets/7736654/19112053/936c6d48-8afa-11e6-9a1a-a91267729607.png)

**Comment by Templarian** [comment]
As a general rule we try to not combine icons with this much detail. I get the use case (cellphone message). But this could work with a lot less detail in the message bubble.

![cellphone-text](https://cloud.githubusercontent.com/assets/338885/19140150/ea106afa-8b4f-11e6-8c77-7db28a37ea4f.png) ![cellphone-text](https://cloud.githubusercontent.com/assets/338885/19140161/f869074c-8b4f-11e6-8522-faf77d737f22.png)

![cellphone-text](https://cloud.githubusercontent.com/assets/338885/19140216/8de7ddfc-8b50-11e6-963c-4d12a31ad652.png) ![cellphone-text](https://cloud.githubusercontent.com/assets/338885/19140212/8849cdd8-8b50-11e6-9dd1-00d876b37686.png)

**Comment by dintendocoltd** [comment]
@Templarian Ah, I see. The two you designed look pretty good (especially the first one).

When will it be possible to push this to the latest version of MDI?

**Comment by Templarian** [comment]
@dintendocoltd I can put these in the next day or two into the site, but the next MDI release won't be for a month or two. Lot of backlog to go through and I'm started into updating the site.

**Comment by AlexMichaelUX** [comment]
Hi, I'm working with a team of developers that have been using https://materialdesignicons.com/cheatsheet for their icons but we have run out of icons from this library. I would like to upload 10 new icons that I havedrawn in Illustrator for usage in the community and ultimately the team.

How do I do this?

What specification information is available to help me get it right?

How long does it take for icons to be available to the wider community?

Can I use any naming convention i.e. Honey-Doc, Honey-Requirements, Honey-Solutions. I want to do this so I can cluster the icons together to make it easier to find. 

Any help or advice will be much appreciated.

Alex

**Comment by Templarian** [comment]
@AlexMichaelUX Sorry, didn't see this earlier. Please create a new issue with them attached to the issue as a ZIP the icons will be reviewed. Names are usually picked based on the icon's noun it represents. Just know that icons usually have to be rather general in nature to be accepted.

**Comment by AlexMichaelUX** [comment]
Check out the attached icons your feedback will be much appreciated
[TestIcon.zip](https://github.com/Templarian/MaterialDesign/files/541085/TestIcon.zip)

**Comment by Templarian** [comment]
@AlexMichaelUX Please create a new issue for this.

**Comment by GreenTurtwig** [comment]
Needs to be left open until they are added. :-)

**Comment by Templarian** [comment]
[![cellphone-text](https://materialdesignicons.com/icon/cellphone-text)](https://materialdesignicons.com/icon/cellphone-text) [![cellphone-message](https://materialdesignicons.com/icon/cellphone-message)](https://materialdesignicons.com/icon/cellphone-message)
