### ISSUE TITLE
Open-access icon suggestion + contribution

### ISSUE THREAD

**Issue by AsafAgranat** [Templarian/MaterialDesign#1553]
Open access stands for unrestricted online access to published scholarly works, as stated in [its wiki](https://commons.wikimedia.org/wiki/Open_Access).
Would be good to have this icon added.

![open_access](https://cloud.githubusercontent.com/assets/22475067/19153495/7aebcf12-8bdf-11e6-8e1f-d8c8fc687c28.png)![open_access](https://cloud.githubusercontent.com/assets/22475067/19153467/5fa10236-8bdf-11e6-8d78-021928400793.png)

I've added an SVG (created with the AI template).
[open_access.zip](https://github.com/Templarian/MaterialDesign/files/513784/open_access.zip)

**Comment by PeterShaggyNoble** [comment]
Closing this out as too niche for now. We may revisit it if a dedicated pack for brand icons is ever added.
