### ISSUE TITLE
Icon request: Drives

### ISSUE THREAD

**Issue by AravK** [Templarian/MaterialDesign#1554]
hard-drive, pen-drive, hard-drive-multiple, pen-drive-multiple
Hard drive: Like a solid thin cuboid: [example](http://images.pcworld.com/images/article/2012/09/mypassportedgeformac-11404126.jpg)
Pen drive: [example](http://aaininternationalbd.com/wp-content/uploads/2015/06/transcend-4gb-pen-drive-ts4gjf500.jpg)

**Comment by DavidEdwards** [comment]
Hows this design for pen-drive?

![pen-drive](https://cloud.githubusercontent.com/assets/1585923/19187265/b339b612-8c8a-11e6-96b4-3f170ce122bb.png)

**Comment by JamesCoyle** [comment]
[![harddisk](https://materialdesignicons.com/icon/harddisk)](https://materialdesignicons.com/icon/harddisk)[![usb](https://materialdesignicons.com/icon/usb)](https://materialdesignicons.com/icon/usb)

I doubt multiple variants will work as we have limited space. 

Pen drive: #1078

**Comment by AravK** [comment]
@DavidEdwards That's awesome!

**Comment by AravK** [comment]
@JamesCoyle That's cool. but something like a big storage device is necessary, aside from the hard disk. I have a couple of 1-2TB drives lying around, but I have no good icon for hem, because I have been using the usb icon for pen drives

**Comment by DavidEdwards** [comment]
@AravK I can't add it - I'm not a contributor. However, here is the SVG for you to do what you want with:

https://drive.google.com/open?id=0BzAFlz5BiPVSbmVOd0FFbGM2OUE

**Comment by AravK** [comment]
@DavidEdwards Thanks! I'm working on making an icon theme for my RPi2B+, so this is a great help
