### ISSUE TITLE
pageview(-outline)

### ISSUE THREAD

**Issue by erstaeuble** [Templarian/MaterialDesign#1555]
Hi there! Love your icons. There are a couple of icons material has but they are not on your awesome list. https://design.google.com/icons/#ic_pageview and https://design.google.com/icons/#ic_keyboard_arrow_down as well as up left and right of that. I wasn't sure how to submit them. I was very confused when it wouldn't let me upload my svgs. I aslo didn't understand how to use it after that. 

Thanks so much for this wonderful set!

**Comment by JamesCoyle** [comment]
We have an issue here that collects stock Google icons. I'm currently on mobile which is really limited so can't do much at the moment.

@templarian Have you planned on adding an issue page to the new site? A page that tells people to search for the icon and then what action to take if it falls into certain categories. I feel like we should have a brand icon issue as well as the stock Google icon issue and maybe more as time goes on that the site links to. That way it reduces the number of issues. We can then list those suggestions on the site so people can see what has been suggested and what the status of those icons is.

**Comment by Templarian** [comment]
@JamesCoyle https://github.com/Templarian/MaterialDesign-Site/issues Submit an issue over here while everythings in the planning phase and I'm coding the base layer for the new site. The idea has come up before to show requested icons in an easier way for designers that don't use GitHub.

**Comment by goyney** [comment]
`keyboard-arrow-down` we have as `chevron-down`. Renaming this issue to add `pageview(-outline)`.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/60062387-018a2600-96c7-11e9-86dc-f8692863e521.png)![image](https://user-images.githubusercontent.com/1015040/60062395-0949ca80-96c7-11e9-8eec-77fa4c5ff1fb.png)

[pageview.zip](https://github.com/Templarian/MaterialDesign/files/3323161/pageview.zip)

**Comment by goyney** [comment]
[![card-search](https://materialdesignicons.com/icon/card-search)](https://materialdesignicons.com/icon/card-search)[![card-search-outline](https://materialdesignicons.com/icon/card-search-outline)](https://materialdesignicons.com/icon/card-search-outline)
