### ISSUE TITLE
new icons

### ISSUE THREAD

**Issue by AlexMichaelUX** [Templarian/MaterialDesign#1556]
Hi, I'm working with a team of developers that have been using https://materialdesignicons.com/cheatsheet for their icons but we have run out of icons from this library. I would like to upload 10 new icons that I have drawn in Illustrator for usage in the community and ultimately the team.

How do I do this?

What specification information is available to help me get it right?

How long does it take for icons to be available to the wider community?

Can I use any naming convention i.e. Honey-Doc, Honey-Requirements, Honey-Solutions. I want to do this so I can cluster the icons together to make it easier to find.

Any help or advice will be much appreciated.

Alex

**Comment by JamesCoyle** [comment]
Can you post examples of the icons here? They will need to follow the material design guidelines and not represent things which are too specific.

**Comment by AlexMichaelUX** [comment]
Here are the particular four icons I need but I am happy to support a hole section on testing with a further 10 icons if that helps. These are the four we need. If we can make them available to the hole community and ultimately my team, that would be much appreciated. Any chance that could happen?

The originals are all Illustrator can can be spat out as SVGs

![newicons](https://cloud.githubusercontent.com/assets/22684130/19240441/627728c0-8f02-11e6-9ece-216b94a35cd4.png)

**Comment by AlexMichaelUX** [comment]
How do I upload my SVG files to the service? 

Any pointers will be much apprecaited.

**Comment by AlexMichaelUX** [comment]
Hi, thanks for your feedback and apologise if I'm not using the conventions of this service but fully intend to learn how to use it. I have attached my SVG. Let me know what you think and if you would consider using them on your service so my guys can link to them.

**Comment by AlexMichaelUX** [comment]
[TestIcon.zip](https://github.com/Templarian/MaterialDesign/files/541078/TestIcon.zip)

**Comment by JamesCoyle** [comment]
Closing as we have similar icons already.

**Comment by goyney** [comment]
To expand on @JamesCoyle's closure, here are the icons you might consider for your four cases:

- Test Scenario - [file-check](https://materialdesignicons.com/icon/file-check)
- Requirements - [file-document](https://materialdesignicons.com/icon/file-document)
- Test Set - [file-multiple](https://materialdesignicons.com/icon/file-multiple)
- Solutions - [cube](https://materialdesignicons.com/icon/cube) (or cube-outline)
