### ISSUE TITLE
Uber Icon

### ISSUE THREAD

**Issue by boozelclark** [Templarian/MaterialDesign#1557]

**Comment by casesandberg** [comment]
![image](https://cloud.githubusercontent.com/assets/4633636/20740883/700844ce-b67b-11e6-86ce-152c8f253ad0.png)

[uber-icon.zip](https://github.com/Templarian/MaterialDesign/files/621061/uber-icon.zip)

**Comment by Templarian** [comment]
[![uber](https://materialdesignicons.com/icon/uber)](https://materialdesignicons.com/icon/uber)
