### ISSUE TITLE
Energy Meter Icon

### ISSUE THREAD

**Issue by cpelegrin** [Templarian/MaterialDesign#1558]
Thank you

**Comment by JamesCoyle** [comment]
[![gauge](https://materialdesignicons.com/icon/gauge)](https://materialdesignicons.com/icon/gauge)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @cpelegrin, if `gauge` doesn't suit your need please comment with more details and an example of what you *are* looking for and we'll revisit this issue.
