### ISSUE TITLE
Coffin / Gravestone

### ISSUE THREAD

**Issue by st-clair-clarke** [Templarian/MaterialDesign#1559]
Hi,
I was surprised to see no icon represent death or coffin etc. I am writing an application that has both birth date and death date, but cannot find something representing death.

I would like to request such an icon please.

Thanks.

NB. Awesome set of icons. Its ease of use makes it a great rival for fontawesome. Keep up the great work.

**Comment by JamesCoyle** [comment]
[![skull](https://materialdesignicons.com/icon/skull)](https://materialdesignicons.com/icon/skull)

**Comment by PeterShaggyNoble** [comment]
Depending on the use case, the skull might be too "quirky" or even insensitive. A headstone, possibly  with the lettering "RIP" might me more appropriate.

**Comment by PeterShaggyNoble** [comment]
`grave-stone` was added recently and `coffin` is coming soon.

**Comment by Templarian** [comment]
Added. 😄
