### ISSUE TITLE
children icon

### ISSUE THREAD

**Issue by jeancharlesamey** [Templarian/MaterialDesign#156]
- [ ] Children/kid

I would like to do it, but the function to submit icon is disabled on materialdesignicons.com
I made some icons btw a bomb, an empty bin, some dotted checkbox...

Best

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/human-child This one is in the pack, but I assume you mean something else.

If you upload them somewhere [in SVG] and link them in this issue I can review them and invite you as a contributor.

**Comment by jeancharlesamey** [comment]
Thanks, invite me or comment this set of icon or both
https://www.dropbox.com/sh/eumi8m23fsixe7d/AAAfrIB_KcE5q2W8Szkav6t4a?dl=0

**Comment by Templarian** [comment]
All of these will need modifications to match the Material Design style. The point data also needs to be optimized with cleaner point coordinates (lots of decimals in the SVG data path). This equates to a larger font.

Two solutions:
- I can list out the changes that need to be made (2px spacing, 2px rounded edges, points should try to stay to integers). You fix them up and attach them.
- I can recreate these icons and import them under my account (icons are getting a "Suggested by" that takes a GitHub username, so you will still be acknowledged).

**Comment by jeancharlesamey** [comment]
thanks for your comment,
I am ok to do on the changes, is there a notice in order to don"t miss a spec. ?

best

**Comment by Templarian** [comment]
http://www.google.com/design/spec/style/icons.html#icons-system-icons

The key is the all points should try to be on the pixel perfect 24x24 grid. All edges need to be exactly 2px (1px if needed). All spacing between any black filled region should contain a 2px space.

It's always a good idea to open the SVG afterwards to ensure the point data looks correct. The site's optimization scripts will handle rounding that may happen in the export ( 0.00001 = 0, 0.49333 = 0.5 etc...).

The Google design docs explain the design process in great detail with many great examples.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/human-child
https://materialdesignicons.com/icon/baby
