### ISSUE TITLE
Hierarchical list icon. Suggestion + contribution

### ISSUE THREAD

**Issue by AsafAgranat** [Templarian/MaterialDesign#1561]
Would be nice to have an icon that represents hierarchical list:

![hierarchical-list-1 4x](https://cloud.githubusercontent.com/assets/22475067/19220486/d004e282-8e36-11e6-9aad-607f19bdcba9.png)![hierarchical-list-1 1x](https://cloud.githubusercontent.com/assets/22475067/19220496/db164bf2-8e36-11e6-9728-21c97945bd66.png)

SVG: [hierarchical-list.zip](https://github.com/Templarian/MaterialDesign/files/518292/hierarchical-list.zip)

**Comment by JamesCoyle** [comment]
[![file-tree](https://materialdesignicons.com/icon/file-tree)](https://materialdesignicons.com/icon/file-tree)

**Comment by AsafAgranat** [comment]
@JamesCoyle thanks for your suggestion, but the icon represents a hierarchical file **tree**, while the rectangles in the icon represent folders. 
A hierarchical list differs in behavior from this by being a **list**, to start with, which means it is meant to be read as a list, often a flat list with visual indentation for each sub-item. This kind of list can be seen in typical ordered-lists and unordered lists (ul and ol tags) in HTML.

**Comment by moojbarber** [comment]
The tree icon is great, but I would a more hierarchical version.
1 box at the top, two boxes underneath.
Something a bit more like this, but with square lines.

![hierarchy](https://user-images.githubusercontent.com/10322790/33826697-c34a5194-de5d-11e7-8a40-7ff8dff5da1a.png)

Thanks in advance.

**Comment by PeterShaggyNoble** [comment]
Google's [extended set](https://petershaggynoble.github.io/MDI-Sandbox/extended/) includes the `segment` icon which might fulfill the original request.

![segment](https://user-images.githubusercontent.com/15157491/33827323-e278b48c-de5f-11e7-9301-c843a53c647d.png)

@moojbarber, see the [`sitemap` icon](https://materialsdesignicons.com/icon/sitemap).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48991972-9615b100-f103-11e8-85c4-6d9c58a6a8e3.png)
[segment.svg.zip](https://github.com/Templarian/MaterialDesign/files/2613992/segment.svg.zip)

**Comment by Templarian** [comment]
Added. 😃
