### ISSUE TITLE
Attempting to become a contributor fails 

### ISSUE THREAD

**Issue by Atomic-Cory** [Templarian/MaterialDesign#1562]
I have been attempting to become a contributor but signup will not accept my GitHub username and continue.

**Comment by Templarian** [comment]
Weird, will have to look into this. Really busy with stuff at the moment (closing on a condo+moving) so it will be a bit until I can focus on the backlog. I have a feeling it's related to another issue with email not functioning 100% correctly on that box.

**Comment by Atomic-Cory** [comment]
(Thumbs Up) I'll keep going on my list of icons for submission. Thanks

**Comment by JamesCoyle** [comment]
Closing as this is a manual process for the foreseeable future. This will likely be added to the new site once it goes live.
