### ISSUE TITLE
Icon For HandWriting

### ISSUE THREAD

**Issue by mirsalari** [Templarian/MaterialDesign#1564]
i need an icon for handwriting. thaaaaaaaaaanks

**Comment by CoDEmanX** [comment]
I guess Google's gesture icon would work: https://design.google.com/icons/#ic_gesture

**Comment by mirsalari** [comment]
maybe... thanks anyway :)

**Comment by JamesCoyle** [comment]
We also have 
[![pen](https://materialdesignicons.com/icon/pen)](https://materialdesignicons.com/icon/pen)

**Comment by mirsalari** [comment]
This one not bad ... Thanks 😊
