### ISSUE TITLE
Alternate wrench icon

### ISSUE THREAD

**Issue by PhilLab** [Templarian/MaterialDesign#1565]
An alternative to the current wrench icon would be nice, displaying an edged variant comparable to this one:
![action](https://cloud.githubusercontent.com/assets/1710255/19266125/65dc9454-8fa8-11e6-8866-d3cf42dc6b71.png)

**Comment by JamesCoyle** [comment]
What is the use-case for this

**Comment by PhilLab** [comment]
No general use case here, just comparable to the several ``variant`` icons provided by the community, e.g. for microphone, trophy or by Google (book-open-variant)

**Comment by JamesCoyle** [comment]
We tend not to include variants unless there is a use case for them.

**Comment by PeterShaggyNoble** [comment]
Closing as this as it doesn't seem necessary.
