### ISSUE TITLE
camera-add

### ISSUE THREAD

**Issue by jQuery2DotNet** [Templarian/MaterialDesign#1568]
Please provide add a photo icon like [google design icon](https://material.io/icons/#ic_add_a_photo)

![ic_add_a_photo_black_24dp_2x](https://cloud.githubusercontent.com/assets/11452784/19319156/3b6eae38-90c9-11e6-8ed3-313b20d9f9ee.png)

**Comment by sarod** [comment]
The provided link seems to be the wrong one. https://material.io/icons/#ic_add_a_photo  seems to be the one

**Comment by PeterShaggyNoble** [comment]
There's also `add photo alternate`  in Google's [extended icon set](https://petershaggynoble.github.io/MDI-Sandbox/extended/):

[![add-photo-alternate](https://user-images.githubusercontent.com/15157491/33126315-f5131cce-cf7b-11e7-90f0-8eedffea2560.png)](https://github.com/Templarian/MaterialDesign/files/1495842/add-photo-alternate.zip)

**Comment by GreenTurtwig** [comment]
And https://github.com/Templarian/MaterialDesign/issues/2339, which is more consistent.

**Comment by musicformellons** [comment]
I prefer the add_a_photo icon. Can it be included?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48991874-007a2180-f103-11e8-895d-268fa852d640.png)
[camera-add.svg.zip](https://github.com/Templarian/MaterialDesign/files/2613985/camera-add.svg.zip)

**Comment by goyney** [comment]
`camera-plus(-outline)` added. 😄
