### ISSUE TITLE
Assignment Flow

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1569]
I have just created this for my team and thought that it could be added here. Let me know what y'all think.

![assignment-flow](https://cloud.githubusercontent.com/assets/4528551/19325136/fc2082ac-9081-11e6-8501-0702b1daf2cf.png) ![assignment-flow 4x](https://cloud.githubusercontent.com/assets/4528551/19325135/fc1a6502-9081-11e6-92c0-305847586fd0.png)

[assignment-flow.zip](https://github.com/Templarian/MaterialDesign/files/525501/assignment-flow.zip)

**Comment by Templarian** [comment]
[![clipboard-flow](https://materialdesignicons.com/icon/clipboard-flow)](https://materialdesignicons.com/icon/clipboard-flow)
