### ISSUE TITLE
Icon for via-connection

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#157]
Example: You start at station A with the bus to station C but want to go there VIA station B.
Hope you know what I mean ;-)
- [ ] transit-connection

**Comment by jeancharlesamey** [comment]
http://materialdesignicons.com/icon/source-pull
something like this ?

**Comment by Templarian** [comment]
Probably like that, but it would need 3 dots, that would be `o-| o |-o`.

1 stop flight sort of deal, but with trains.

**Comment by matthew2402** [comment]
@Templarian Jepp you're right, 3 dots would be nice. Maybe higlight the middle one.

**Comment by CoDEmanX** [comment]
From a public transport website:
![route](https://cloud.githubusercontent.com/assets/1309249/9060618/cb1410b6-3ab5-11e5-97d6-033f3d56bf48.PNG)

So circles and outlined circles, connected by lines (could also be dots or dashed).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48730227-b4f9dc00-ec07-11e8-9567-9955aadb3f9b.png)![image](https://user-images.githubusercontent.com/1015040/48730234-bc20ea00-ec07-11e8-90e6-85f21fadf52b.png)

[transit-connection.zip](https://github.com/Templarian/MaterialDesign/files/2596774/transit-connection.zip)

**Comment by Templarian** [comment]
These both have their uses.

[![transit-connection](https://materialdesignicons.com/icon/transit-connection)](https://materialdesignicons.com/icon/transit-connection) [![transit-connection-variant](https://materialdesignicons.com/icon/transit-connection-variant)](https://materialdesignicons.com/icon/transit-connection-variant)
