### ISSUE TITLE
Font color

### ISSUE THREAD

**Issue by MichaelSavin** [Templarian/MaterialDesign#1570]
Like in google docs editor:
![image](https://cloud.githubusercontent.com/assets/1640229/19341704/01df9cde-9148-11e6-8283-711bf4901736.png)

**Comment by JamesCoyle** [comment]
[![format-color-text](https://materialdesignicons.com/icon/format-color-text)](https://materialdesignicons.com/icon/)format-color-text

**Comment by Templarian** [comment]
You need to use it in combination with the `color-helper` icon to create the whole icon with the line below it.
