### ISSUE TITLE
Icon for Training

### ISSUE THREAD

**Issue by mahivitsit** [Templarian/MaterialDesign#1572]
[Example Icon](http://www.freeiconspng.com/uploads/business-training-icon-8.png)

**Comment by JamesCoyle** [comment]
Could be a little tricky to fit it into the space we have.

**Comment by PeterShaggyNoble** [comment]
`teach` was added in the latest release which should fulfil this request.

[![teach](https://user-images.githubusercontent.com/15157491/36985096-432d3e7c-208e-11e8-97a8-991c088a9284.png)](https://materialdesignicons.com/icon/teach)
