### ISSUE TITLE
No Translation Icon

### ISSUE THREAD

**Issue by solomojo** [Templarian/MaterialDesign#1573]
Here is the icon package including an SVG, EPS, & PNG
[no_translate.zip](https://github.com/Templarian/MaterialDesign/files/527758/no_translate.zip)

**Comment by Templarian** [comment]
Needs to be the standard 24x24 size. I think we get the idea and can quickly create that one though.

https://materialdesignicons.com/icon/translate + slash.

**Comment by solomojo** [comment]
Awesome Thanks.

**Comment by solomojo** [comment]
Here's the icon in the proper size.
[no-translate.zip](https://github.com/Templarian/MaterialDesign/files/1442650/no-translate.zip)

**Comment by CoDEmanX** [comment]
It's hardly legible IMO

![image](https://user-images.githubusercontent.com/1309249/38770338-bb40730a-4011-11e8-805a-00241e40efcf.png)

**Comment by PeterShaggyNoble** [comment]
How does it look with the slash rotated?

**Comment by solomojo** [comment]
I tried the strike-through both ways. When it's flipped it looks like a symbol for double-byte (eg Japanese) or Latin (eg English) similar to n/a instead of symbolizing there is no translation available.  

Being in the translation industry, I see the normal translation icon so often that it's very recognizable with the strike-through.  I'm actually already using this icon in several apps I've designed and have had no confusion from clients using the apps.

**Comment by Templarian** [comment]
[![translate-off](https://materialdesignicons.com/icon/translate-off)](https://materialdesignicons.com/icon/translate-off)

@solomojo Thanks for the explanation! It helps us a lot when deciding the best icon. Working on trimming the backlog now, sorry it took so long to get it in. 😃 Added to the shared contributor account, but if you add 4 more I'll create a contributor account.
