### ISSUE TITLE
achievement icon

### ISSUE THREAD

**Issue by hummatli** [Templarian/MaterialDesign#1575]
I need achievement icon. But couldn't find it here

**Comment by GreenTurtwig** [comment]
You could use the trophy icon. :-)

**Comment by hummatli** [comment]
Yes your are right. Then we need achievement tag on that images )). How to do that?

**Comment by Templarian** [comment]
Aliases below were added. Searching will show these as results now.

- `trophy` ... `achievement`
- `trophy-award` ... `achievement-award`
- `trophy-variant` ... `achievement-variant`
- `trophy-outline` ... `achievement-outline`
- `trophy-variant-outline` ... `achievement-variant-outline`
