### ISSUE TITLE
Suggestion: Add color converter to repository

### ISSUE THREAD

**Issue by AravK** [Templarian/MaterialDesign#1576]
I am making an icon theme for my Raspi2B+ Mate Desktop based on these icons. I cloned the github repository(sparse) for the svg icons, but I needed them all in white. Being quite a newbie at `sed`, I spent 2 hours figuring out the correct regex to use to convert every single color code to #ffffff. I suggest that you add that as a command to use for anybody downloading the repository. Here it is: `sed -e 's/"\#[^"]*[0-9a-fA-F]"/"#ffffff"/g'`. Please replace `#ffffff` with whatever color is being used.

**Comment by Templarian** [comment]
The https://materialdesignicons.com/design has the optimized SVG assets. New features on the current site are on hold while we build out the new site. Definitely would be a nice addition to have as a download option.

https://github.com/Templarian/MaterialDesign-Site/issues/11
