### ISSUE TITLE
Can I use your icons to create your own package?

### ISSUE THREAD

**Issue by vaeum** [Templarian/MaterialDesign#1577]
I create React Component from svg icons

**Comment by JamesCoyle** [comment]
@Templarian may correct me on this but these icons are free to use how you wish. As long as you don't try to sell the icons or pass them off as your own work you should be fine. As always though, an attribution link is appreciated where possible so other people can use and contribute to this awesome project.

**Comment by Templarian** [comment]
What @JamesCoyle said is correct. Eventually we'll have a gallery of 3rd party controls that make use of the icons. The real goal is just to get people to use the icons in as many projects as possible. 😄
