### ISSUE TITLE
ICON for Home Automation

### ISSUE THREAD

**Issue by dkiran** [Templarian/MaterialDesign#1579]

**Comment by GreenTurtwig** [comment]
You could use the `home` icon?

**Comment by GreenTurtwig** [comment]
Seems like quite a few "home automation" icons are just home icons with signal bars inside.

**Comment by GreenTurtwig** [comment]
Not too sure about this one, but it seems alright. :-/
[home-automation.zip](https://github.com/Templarian/MaterialDesign/files/624264/home-automation.zip)
![puush-linux 2016-12-01 at 10 33 37](https://cloud.githubusercontent.com/assets/15905797/20790757/bdee5246-b7b1-11e6-97c6-661870a9fa95.png)
![puush-linux 2016-12-01 at 10 34 03](https://cloud.githubusercontent.com/assets/15905797/20790769/c3c37eee-b7b1-11e6-9d7b-90acdcf79a52.png)

**Comment by Templarian** [comment]
[![home-automation](https://materialdesignicons.com/icon/home-automation)](https://materialdesignicons.com/icon/home-automation)
