### ISSUE TITLE
Schedule, Event icon

### ISSUE THREAD

**Issue by royale1223** [Templarian/MaterialDesign#158]
A schedule and event icon would be nice. Calender icons can be used but something different would do better.
- [x] Schedule
- [ ] Event

**Comment by chrislitherland95** [comment]
Hey royale,

What did you have in mind for the "event" icon?

As for schedule, there already exists a "timetable" icon (http://materialdesignicons.com/icon/timetable), is that what you were looking for?

**Comment by CoDEmanX** [comment]
How is an event icon supposed to look like? Can't think of anything other than calendars...

Maybe calendar + exclamation mark?
![Imgur](http://i.imgur.com/dlur09N.png?1)

**Comment by royale1223** [comment]
Sadly, I have no idea. I ended up using a plain calendar icon.

**Comment by CoDEmanX** [comment]
Google seems to use this icon (calendar + highlighted day) to symbolize an event:
https://materialdesignicons.com/icon/calendar

**Comment by CoDEmanX** [comment]
![calendar-alert_ 158](https://cloud.githubusercontent.com/assets/1309249/14904101/2939511a-0da6-11e6-8445-2398cf69bd5b.png) could be used as icon for things that are overdue
![calendar-week-begin](https://cloud.githubusercontent.com/assets/1309249/14904102/2953c658-0da6-11e6-834e-dcdc0f356c98.png) beginning of week setting (inspired by Outlook for Android app)

**Comment by JamesCoyle** [comment]
Gonna go ahead and say that the variety of calendar icons will cover 'event'. I have to say it would be nice to have a calendar icon with numbered days on it though. Not really sure how it would be possible without adding 31 new icons though.

**Comment by MrGrigri** [comment]
Look at this thread: https://github.com/Templarian/MaterialDesign/issues/1641

**Comment by PeterShaggyNoble** [comment]
CLosing in favour of #1641.
