### ISSUE TITLE
Filled emoticon icons

### ISSUE THREAD

**Issue by krambertech** [Templarian/MaterialDesign#1584]
Hey! 

I've created emoticons filled with color. I needed them for my work project and thought that they can be useful for others.

They are in this google drive folder: https://drive.google.com/drive/folders/0B0vWLGIPYrA_RlJSams3VTNiWkk

Thank you!

**Comment by Templarian** [comment]
Running into an issue with this request... technically speaking the current emoji's are all `-outline`. For consistency sake, we would need to add filled versions and then add the filled at the regular. That or we simply don't include filled emojis. Not sure how needed these are?

**Comment by sleman** [comment]
-filled for new ones?

**Comment by PeterShaggyNoble** [comment]
We should probably revisit this now hat we're trying to include filled and outline variants of all icons.

**Comment by goyney** [comment]
The first thing we need to do is rename all existing emotions:
- [ ] `emoticon` -> `emoticon-outline` (`-outline` becomes attributed to Google)
- [ ] `emoticon-cool` -> `emoticon-cool-outline` (`-outline` becomes attributed to Austin Andrews)
- [ ] `emoticon-dead` -> `emoticon-dead-outline` (`-outline` becomes attributed to Google)
- [ ] `emoticon-devil` -> `emoticon-devil-outline` (`-outline` becomes attributed to Austin Andrews)
- [ ] `emoticon-excited` -> `emoticon-excited-outline` (`-outline` becomes attributed to Google)
- [ ] `emoticon-happy` -> `emoticon-happy-outline` (`-outline` becomes attributed to Gabriel)
- [ ] `emoticon-neutral` -> `emoticon-neutral-outline` (`-outline` becomes attributed to Austin Andrews)
- [ ] `emoticon-sad` -> `emoticon-sad-outline`(`-outline` becomes attributed to Gabriel)
- [ ] `emoticon-tongue` -> `emoticon-tongue-outline` (`-outline` becomes attributed to Austin Andrews)
---

Next, we'll add the new "filled" versions of all of these:
![image](https://user-images.githubusercontent.com/1015040/48800932-205fae80-ecd9-11e8-9de4-0136f318e92a.png)![image](https://user-images.githubusercontent.com/1015040/48800943-29e91680-ecd9-11e8-883f-68371ad71731.png)
![image](https://user-images.githubusercontent.com/1015040/48800955-2fdef780-ecd9-11e8-9bc3-9847c7a52c57.png)![image](https://user-images.githubusercontent.com/1015040/48800967-379e9c00-ecd9-11e8-8cfc-aa5cafb405ce.png)
![image](https://user-images.githubusercontent.com/1015040/48800978-3f5e4080-ecd9-11e8-9a6d-6f556ee31f1b.png)![image](https://user-images.githubusercontent.com/1015040/48800996-46854e80-ecd9-11e8-999f-0cfbd14480c7.png)
![image](https://user-images.githubusercontent.com/1015040/48801010-500eb680-ecd9-11e8-8215-9e73b27241db.png)![image](https://user-images.githubusercontent.com/1015040/48801024-5735c480-ecd9-11e8-94c3-1c95abc4ca59.png)
![image](https://user-images.githubusercontent.com/1015040/48801038-5f8dff80-ecd9-11e8-8647-c67640e581a4.png)

We'll also include an `outline` version of `emoticon-poop`. Take your pick on which one looks better.
![image](https://user-images.githubusercontent.com/1015040/48801070-6caaee80-ecd9-11e8-84f7-1d476980249d.png)![image](https://user-images.githubusercontent.com/1015040/48801302-007cba80-ecda-11e8-9a5e-cb876687c6c4.png)

[emoticons.zip](https://github.com/Templarian/MaterialDesign/files/2601480/emoticons.zip)

**Comment by Templarian** [comment]
All of these are in, and I edited the history log to reduce confusion. We've kept all the codepoints pointed at outline, so anyone hard coding them won't be confused.
