### ISSUE TITLE
format-quote but flipped horizontally

### ISSUE THREAD

**Issue by eddieberklee** [Templarian/MaterialDesign#1585]
I would do this myself since it seems simple but I just am not familiar enough with Sketch/Illustrator's export options

**Comment by Templarian** [comment]
When we add this one I'm going to opt to make the two changes below.

- [ ] Rename `format-quote` -> `format-quote-close`
- [ ] Add `format-quote-open`

**Comment by Simran-B** [comment]
How about `format-unquote` 😄  [format-unquote.zip](https://github.com/Templarian/MaterialDesign/files/544252/format-unquote.zip)

**Comment by PeterShaggyNoble** [comment]
This was addressed a while ago, in v1.9.32
