### ISSUE TITLE
New Album Icon

### ISSUE THREAD

**Issue by sleman** [Templarian/MaterialDesign#1587]
![dslr_template-editor_ui-design psd 200 icon_ new template rgb_8_ _ 2016-10-21 17 53 31](https://cloud.githubusercontent.com/assets/976380/19612902/4ff60438-97b7-11e6-9565-871f4437baf7.png)

**Comment by JamesCoyle** [comment]
I believe this could be handled with an `image-multiple-plus` icon or `image-album-plus`

[![](https://materialdesignicons.com/icon/image-multiple
)](https://materialdesignicons.com/icon/image-multiple)[![](https://materialdesignicons.com/icon/image-plus
)](https://materialdesignicons.com/icon/image-plus)

[![](https://materialdesignicons.com/icon/image-album
)](https://materialdesignicons.com/icon/image-album)

**Comment by goyney** [comment]
We've got lots of `plus` icons now. Take a look and see if any fit your needs. Let us know one way or another here.

**Comment by goyney** [comment]
Closing due to no response and there being several icons that can fit this use case now.
