### ISSUE TITLE
Save As icon

### ISSUE THREAD

**Issue by sleman** [Templarian/MaterialDesign#1588]
![dslr_template-editor_ui-design psd 200 icon_ new template rgb_8_ _ 2016-10-21 17 54 03](https://cloud.githubusercontent.com/assets/976380/19612919/62d82d24-97b7-11e6-8be9-d06fd93ef904.png)

**Comment by JamesCoyle** [comment]
I'd suggest the save icon with a pencil

**Comment by PeterShaggyNoble** [comment]
Duplicate of #1134
