### ISSUE TITLE
Align Icons ala Photoshop/Illustrator for Aligning Multiple Elements

### ISSUE THREAD

**Issue by sleman** [Templarian/MaterialDesign#1589]
![dslr_template-editor_ui-design psd 100 icons off rgb_8_ _ 2016-10-21 17 56 43](https://cloud.githubusercontent.com/assets/976380/19612998/d3eb2b10-97b7-11e6-85f0-ce25fe1bfe30.png)

Align:
- [ ] `format-align-top`
- [ ] `format-align-vertical-center`
- [ ] `format-align-bottom`
- [ ] `format-align-left`
- [ ] `format-align-horizontal-center`
- [ ] `format-align-right`

Distribute:
- [ ] `format-distribute-top`
- [ ] `format-distribute-vertical-center`
- [ ] `format-distribute-bottom`
- [ ] `format-distribute-left`
- [ ] `format-distribute-horizontal-center`
- [ ] `format-distribute-right`

**Comment by Templarian** [comment]
I've made most of these, but what are the names of these icons exactly?

Not 100% sure `selected` is the right term. `Multiple` is one of our special keywords in the naming scheme so maybe `items`?

**Comment by sleman** [comment]
Updated with recommendations based on Photoshop.

**Comment by Templarian** [comment]
Thanks @sleman!

**Comment by sleman** [comment]
Any eta?

**Comment by Templarian** [comment]
Sorry, Cubs keep winning. Soon. Updates are slower until my move is final.

**Comment by sleman** [comment]
Congrats to the Cubs! Anything I can do to help speed this up? Coffee, a donation perhaps :) ?

**Comment by Simran-B** [comment]
@Templarian Bump

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/65540862-3b431680-deda-11e9-9761-4a5c4015aba8.png)![image](https://user-images.githubusercontent.com/1015040/65540872-426a2480-deda-11e9-9fdc-e2d157954bb9.png)
![image](https://user-images.githubusercontent.com/1015040/65540891-48f89c00-deda-11e9-89b6-720ce29d6e5c.png)![image](https://user-images.githubusercontent.com/1015040/65540920-53b33100-deda-11e9-98ef-2856e66e697f.png)
![image](https://user-images.githubusercontent.com/1015040/65540949-5c0b6c00-deda-11e9-9a0a-57036232090a.png)![image](https://user-images.githubusercontent.com/1015040/65540962-64fc3d80-deda-11e9-8aba-f2eae999c0a3.png)

![image](https://user-images.githubusercontent.com/1015040/65540998-76dde080-deda-11e9-8a2f-5187ce44db85.png)![image](https://user-images.githubusercontent.com/1015040/65541017-7d6c5800-deda-11e9-8b63-fa105fb74708.png)
![image](https://user-images.githubusercontent.com/1015040/65541032-84936600-deda-11e9-93c4-4beefe1f8243.png)![image](https://user-images.githubusercontent.com/1015040/65541047-8c530a80-deda-11e9-962f-500f353f4dd7.png)
![image](https://user-images.githubusercontent.com/1015040/65541056-92e18200-deda-11e9-9eea-4e80808135c3.png)![image](https://user-images.githubusercontent.com/1015040/65541072-98d76300-deda-11e9-8c81-02307c396c91.png)

[align.zip](https://github.com/Templarian/MaterialDesign/files/3648907/align.zip)

**Comment by goyney** [comment]
All added.

**Comment by smeijer** [comment]
I think it would be nice to also have the `distribute-horizontal-spacing` and `distribute-vertical-spacing` icons.

Screenshot from figma:

![image](https://user-images.githubusercontent.com/1196524/90659331-d6588380-e244-11ea-8003-db826095d49a.png)
