### ISSUE TITLE
Beer Icons

### ISSUE THREAD

**Issue by emburaman** [Templarian/MaterialDesign#159]
It would be very appreciated to have Beer related icons such as:
- [x] Hops
- [x] Malt/Barley
- [x] Yeast
- Beer glass
  - [ ] Pilsner
  - [ ] Weissen
  - [x] Mug
  - [x] Flute
  - [x] Tulip
  - [x] Stange (cylinder).
  - [ ] Chalice
  - [ ] Goblet
  - [ ] Hexagonal
  - [ ] Thistle
  - [ ] Tankard
  - [x] Pint glass
  - [ ] Yard glass
- Beer Storage
  - [ ] bottle
  - [ ] can
  - [x] keg
- Brewing process
  - [ ] Mashing
  - [ ] Boiling
  - [ ] Filtering
  - [ ] Fermenting
  - [ ] Bottling

**Comment by Templarian** [comment]
These would all make an awesome addition to the pack. The size constraints is going to make some of these difficult. I've made beer glass ones [before](https://creativemarket.com/templarian/3324-Beer-Glasses) so very familiar with the differen types.

If you have an examples for the brewing process that would be very helpful.

**Comment by emburaman** [comment]
The below is an example of brewing process:



On Wed, Feb 18, 2015 at 1:42 PM, Austin Andrews <notifications@github.com>
wrote:

> These would all make an awesome addition to the pack. The size constraints
> is going to make some of these difficult. I've made beer glass ones before
> <https://creativemarket.com/templarian/3324-Beer-Glasses> so very
> familiar with the differen types.
>
> If you have an examples for the brewing process that would be very helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/159#issuecomment-74885797>
> .
>



-- 
*Lincoln Souza*
"Leadership is an opportunity to serve, not a trumpet call to
self-importance." - J.D.Walters

**Comment by Templarian** [comment]
Your reply to the email doesn't transfer into GitHub issues. Please copy and paste the images into the GitHub issue text area. It will insert the image.

**Comment by emburaman** [comment]
Sorry the inconvenience... still getting used to GitHub .

![image](https://cloud.githubusercontent.com/assets/2572753/6265280/8c706d20-b813-11e4-8794-92c916b5c9fa.png)

Some other images try the following: https://www.google.com.br/search?q=simplified+brewing+process&espv=2&biw=1366&bih=677&source=lnms&tbm=isch&sa=X&ei=f77lVN_qM8vhgwSVnoPYBQ&ved=0CAYQ_AUoAQ#tbm=isch&q=home+brewing+process&imgdii=_

**Comment by CoDEmanX** [comment]
Isn't this a pint glass?
https://materialdesignicons.com/icon/beer

**Comment by Templarian** [comment]
Yep.

**Comment by FernandoFranco** [comment]
The current glass-mug is so clean, i suggest to change to icon like this for beer mug.
![](https://cdn3.iconfinder.com/data/icons/food-and-drinks-icons/512/Beer-512.png)

**Comment by JamesCoyle** [comment]
Need to get that pup icon from Maps.

**Comment by CoDEmanX** [comment]
An approximate recreation:

![grafik](https://user-images.githubusercontent.com/1309249/62791300-28f94e80-bacd-11e9-80d9-8328f4b0b29c.png)

[pub2.zip](https://github.com/Templarian/MaterialDesign/files/3487036/pub2.zip)

Thanks for your help @JamesCoyle !

**Comment by goyney** [comment]
Added the new mug:
[![glass-mug-variant](https://materialdesignicons.com/icon/glass-mug-variant)](https://materialdesignicons.com/icon/glass-mug-variant)

Closing this now because we don't really want any more long running, multiple-request issues. If you need any other specifics from this issue, please open a separate issue for each individual request. Thanks!
