### ISSUE TITLE
Shape Icon

### ISSUE THREAD

**Issue by sleman** [Templarian/MaterialDesign#1590]
Existing shape icon has a plus and is not generic enough.

Suggesting:
![dslr_template-editor_ui-design psd 100 icons off rgb_8_ _ 2016-10-21 17 57 46](https://cloud.githubusercontent.com/assets/976380/19613012/ea47348a-97b7-11e6-980f-0156284f4a83.png)

**Comment by PeterShaggyNoble** [comment]
`drawing`, `drawing-box`, `shape` or `shape-outline` should fulfil this request.
