### ISSUE TITLE
Science Icons

### ISSUE THREAD

**Issue by phidias51** [Templarian/MaterialDesign#1591]
It would be nice to have some science-related icons like:

- compound structure (this could be a simple hexagon)
- a protein structure
- a DNA helix
- a 96-well plate
- a microscope

**Comment by JamesCoyle** [comment]
[![dna](https://materialdesignicons.com/icon/dna)](https://materialdesignicons.com/icon/dna)[![microscope](https://materialdesignicons.com/icon/microscope)](https://materialdesignicons.com/icon/microscope)

There is also a hexagon icon available. The others may be a bit too specific.

**Comment by Templarian** [comment]
I think the hexagon would probably suffice for that. Protein structure and 96-well plate are going to be too specific, might just have to find icons that are "close enough".
