### ISSUE TITLE
"Polymerized" Icon?

### ISSUE THREAD

**Issue by phidias51** [Templarian/MaterialDesign#1592]
I was wondering if there was a way for the website to automatically generated a "Polymerized" version of the icon.  Basically just wrapping the path in a ```<g id="some-icon-name">``` tag. 

It would also be nice if when you selected this format, you got a snippet that you could just copy into your icon-set.

If you select multiple-icons, it would be nice to generate an icon-set.

**Comment by Templarian** [comment]
https://materialdesignicons.com/getting-started has a download option for polymer (including legacy). Or are you talking about something else?

**Comment by phidias51** [comment]
According to the doc, that creates an mdi.html file containing all icons (not just the selected icons).  There are really two use cases here though:

1. Create an option that allows the user to view a code snippet that wraps the **path** for the icon in a **g** tag, and provides the appropriate ID.
2. Allow the user to select multiple icons (and optionally all icons) and generate an iconset suitable for a  Polymer project.

**Comment by Templarian** [comment]
By the way, yea that makes sense. This might be a feature we'll have to bake into v2 of the site. I've kind of put feature updates on hold with the current site.

If I get a few minutes I'll transfer this over to the new site repo to track the progress.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site/issues/13

Moving this issue to be tracked on the new site repo to keep things more organized.
