### ISSUE TITLE
New Universal Edit Icon 

### ISSUE THREAD

**Issue by trespas** [Templarian/MaterialDesign#1595]
A universal edit icon is still not present in the icon set. I've been using square + Pencil but it's not a solution. This is the icon needed:
![2016-10-23_17-56-59](https://cloud.githubusercontent.com/assets/16062063/19626275/3f1a77f8-994b-11e6-93fa-f32a5b79bf96.png)

Thanks in advance

**Comment by JamesCoyle** [comment]
[![pencil-box-outline](https://materialdesignicons.com/icon/pencil-box-outline)](https://materialdesignicons.com/icon/pencil-box-outline)
