### ISSUE TITLE
New icons request: Partly Cloudy Night and Tornado

### ISSUE THREAD

**Issue by mongeon** [Templarian/MaterialDesign#1597]
I'm developing an app with weather integration and want to add 2 more icons to the weather "theme":
- A partly cloudy at night. Same as with the weather-partlycloudy but with a moon
- Tornado: sometimes bad weather happen. (see what Adam have done here for inspiration: [climacons](http://adamwhitcroft.com/climacons/))

Thanks

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #541
