### ISSUE TITLE
Audio Artist Icons

### ISSUE THREAD

**Issue by h4h13** [Templarian/MaterialDesign#1598]

**Comment by Templarian** [comment]
Do you have an example of what this would look like?

**Comment by h4h13** [comment]
Beside artist name icon

https://plus.google.com/photos/105194484944232449951/album/6337038320153043425/6337043576601923378?sqid=116821616252548925340&ssid=66b44da3-5b3f-4fd1-ac12-8b9bff59b964

**Comment by GreenTurtwig** [comment]
Here you go. :cat2:
[file-account.zip](https://github.com/Templarian/MaterialDesign/files/624201/file-account.zip)
I centred it like `file-lock` instead of setting it to the side like in the screenshot.

**Comment by h4h13** [comment]
For preview icon (with out grey background)
![default_artist](https://user-images.githubusercontent.com/2574895/29738387-dcc73d08-8a3e-11e7-8d10-abf7931835e3.png)

**Comment by Templarian** [comment]
[![artist](https://materialdesignicons.com/icon/artist)](https://materialdesignicons.com/icon/artist)
