### ISSUE TITLE
Missed Google Material Design Icons

### ISSUE THREAD

**Issue by SuperITMan** [Templarian/MaterialDesign#1599]
Hello,

Firstly I want to thank you for your awesome work. 

I permit to let this comment because I'm currently switching my project from the sprites of Google to your mdi.svg. I remarks that you missed to add two Material Design Icons:
- The 3d_rotation -> https://design.google.com/icons/#ic_3d_rotation
- The all_out -> https://design.google.com/icons/#ic_all_out

Could you, please, add them to your set of icons. 

Thank you.
Regards.

**Comment by bjarnef** [comment]
Maybe also check all icons here https://material.io/icons/ marked with "new" .. e.g. euro symbol is missing.

**Comment by goyney** [comment]
Here are the two requested stock icons from the original request. The `euro` icon has been added from the reply.

![image](https://user-images.githubusercontent.com/1015040/48992298-083ac580-f105-11e8-8f3b-8839e93b5566.png)![image](https://user-images.githubusercontent.com/1015040/48992305-14bf1e00-f105-11e8-9518-c21e7520c3c8.png)
[stock.zip](https://github.com/Templarian/MaterialDesign/files/2614013/stock.zip)

**Comment by PeterShaggyNoble** [comment]
We'll either need to replace our existing `rotate-3d` icon or rename it as a variant.

**Comment by Templarian** [comment]
Added / updated. Renamed the current `rotate-3d` to variant.
