### ISSUE TITLE
I want to be a contributor!

### ISSUE THREAD

**Issue by chrislitherland95** [Templarian/MaterialDesign#160]
I've tidied up my icons and unified them into a single path. Let me know if there's something missing, i'm pretty sure they comply with MD.

http://1drv.ms/1CKPjS5

There's about 5 in there.

**Comment by Templarian** [comment]
These look great. I'll send the invite out tonight, I need to test the optimization scripts on your icons. None of the current icons use the "S" command in their path data. It should be fine, but the system could also puke if it doesn't like it.

**Comment by chrislitherland95** [comment]
Haha thanks. Let me know if it needs fixing and I can square it off. 
On Fri, Feb 20, 2015 at 5:58 am, Austin Andrews <notifications@github.com> wrote:These look great. I'll send the invite out tonight, I need to test the optimization scripts on your icons. None of the current icons use the "S" command in their path data. It should be fine, but the system could also puke if it doesn't like it.

**Comment by Templarian** [comment]
Your SVG files are not importing into the system correctly. I don't want to delay you becoming a contributor, so I'm sending your invite. I imported all your icons. Once you accept the invite and your account is created I'm simply going to transfer the icons to your account.

If you could share your email (I'll delete it from the comment once I send the invite).

![monitor-multiple](https://cloud.githubusercontent.com/assets/338885/6280766/b07c5a2a-b878-11e4-9f62-b0e5a0a46935.png) ![webcam](https://cloud.githubusercontent.com/assets/338885/6281371/b7d3a5b4-b885-11e4-9c9b-658e4c5ff252.png) ![deskphone](https://cloud.githubusercontent.com/assets/338885/6281413/b224f2c0-b886-11e4-956c-445ef17145b3.png) ![desktop-tower](https://cloud.githubusercontent.com/assets/338885/6281473/dcbde162-b887-11e4-903b-2350b780b44c.png) ![headset-dock](https://cloud.githubusercontent.com/assets/338885/6281726/f6e57682-b88b-11e4-8fed-56ea582f930d.png)

I had to modify the multiple monitor icon slightly as it does not really fit the style. Same with webcam.

**Comment by chrislitherland95** [comment]
chris
litherland
95
at
outlook
com

**Comment by chrislitherland95** [comment]
Those icons look awesome. I knew the dual monitor was incorrect, but what was the issue with the webcam (and how did you get it to output as a single path?) I had concentric circles on a previous version of the icon but I could not get it to unify into one path...

**Comment by Templarian** [comment]
I highly recommend the use of Expression Design 4. It's free since it got discontinued, but it exports really nice SVG files. It's missing some of the really advanced features of illustrator, but for this simple icon work it's great.

Invite sent.

**Comment by chrislitherland95** [comment]
Got the invite thanks. I'll look into ED4 for my icons. Does it support ICO by any chance? That'd be a great addition.

**Comment by Templarian** [comment]
Once your account is on, please take a moment to upload a 100x100 picture of yourself (preferably) or a company logo (double check that it looks nice in the circle).

Also fill in the other details listed there for the profile.

Expression Design does not support .ico because 99% of the time .ico each icon is hand crafted in the smaller sizes. There are nice free apps to do .ico.

**Comment by Templarian** [comment]
I can't transfer the icons until you register your account. Is it working? I often break stuff so it could be broken.

**Comment by chrislitherland95** [comment]
I'm pretty sure its registered. I logged in and submitted a profile pic and everything.
Sent using CloudMagic
On Sat, Feb 21, 2015 at 2:09 am, Austin Andrews <notifications@github.com> wrote:I can't transfer the icons until you register your account. Is it working? I often break stuff so it could be broken.

**Comment by Templarian** [comment]
I forgot you have 0 icons assigned so you wouldn't show up in the contributor list. Fixed.

https://twitter.com/MaterialIcons/status/568884791422128128

**Comment by Templarian** [comment]
By the way, your twitter on the profile is wrong. Might want to update that (you have a 95 at the end, I think you entered your github into the twitter field).

**Comment by chrislitherland95** [comment]
Oh thanks for the heads up. I'll update that now. 
On Sat, Feb 21, 2015 at 7:29 am, Austin Andrews <notifications@github.com> wrote:By the way, your twitter on the profile is wrong. Might want to update that (you have a 95 at the end, I think you entered your github into the twitter field).
