### ISSUE TITLE
Stretch

### ISSUE THREAD

**Issue by reinert** [Templarian/MaterialDesign#1600]
Hi, I created two svg icons: stretch-horizontal and stretch-vertical.

![stretch-vertical](https://cloud.githubusercontent.com/assets/1285494/19699699/bf170efa-9aca-11e6-8c7e-e39600852f56.png) ![stretch-horizontal](https://cloud.githubusercontent.com/assets/1285494/19699700/bf1d98b0-9aca-11e6-908e-cb01be646f5c.png)

How can I submit them?

**Comment by PeterShaggyNoble** [comment]
Do `arrow-expand-horizontal` and `arrow-expand-vertical` suit your needs?

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
