### ISSUE TITLE
log (math)

### ISSUE THREAD

**Issue by reinert** [Templarian/MaterialDesign#1601]
I created three log icons.

![log-ink-svg](https://cloud.githubusercontent.com/assets/1285494/19705298/18508bec-9ae2-11e6-9eba-a25f993a3527.png) ![log-ink-svg-1](https://cloud.githubusercontent.com/assets/1285494/19705297/184f414c-9ae2-11e6-8a9d-df172de23883.png) ![log-ink-svg-1-2](https://cloud.githubusercontent.com/assets/1285494/19705299/1858e120-9ae2-11e6-88ad-1236eaeb5a1f.png)

Would it be interesting for this project?

**Comment by JamesCoyle** [comment]
These need to be redone with our character set.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/62735383-0990f180-b9f9-11e9-902f-825db5084d1d.png)
[math-log.svg.zip](https://github.com/Templarian/MaterialDesign/files/3483537/math-log.svg.zip)

**Comment by goyney** [comment]
[![math-log](https://materialdesignicons.com/icon/math-log)](https://materialdesignicons.com/icon/math-log)
