### ISSUE TITLE
Beam.pro brand icon

### ISSUE THREAD

**Issue by mistermantas** [Templarian/MaterialDesign#1603]
Beam is a live streaming site which is mainly used by gamers. The site itself is not hugely popular compared to Twitch, but it was [bought by Microsoft not too long ago](https://blogs.microsoft.com/blog/2016/08/11/microsoft-acquires-beam-interactive-livestreaming-service/) and Xbox integration is supposedly coming in 2017. You can take a look at [Beam’s About page](https://beam.pro/about/features) which details what Beam has to offer.

The [brand guidelines are available on GitHub](https://github.com/WatchBeam/beam-branding-kit).

**Comment by Templarian** [comment]
Marking labels on this, but it's a pretty niche icon. Not rejecting, but don't expect it to get added soon.

https://github.com/WatchBeam/beam-branding-kit/blob/master/logos/svg/beam_ball_black.svg

**Comment by onlinemantas** [comment]
Is it *really* that niche nowadays, though? Microsoft purchased Beam, and Microsoft isn’t a niche company. Not at all. Maybe it’s time to reconsider this issue?

**Comment by mistermantas** [comment]
@Templarian Any update?

**Comment by JamesCoyle** [comment]
If someone wants to give it a go I'm sure we'll add it but contributors only tend to work on icons they'll find useful so the less common icons often fall through.

**Comment by mistermantas** [comment]
@JamesCoyle Hmm. How does one contribute an icon?

**Comment by JamesCoyle** [comment]
Just post the SVG path or a link to a download of the SVG here, preferably with a preview image.

**Comment by mistermantas** [comment]
Wasn't it already linked above? 404ing now, but the repository is still a-ok!

https://github.com/WatchBeam/beam-branding-kit

**Comment by Templarian** [comment]
[![beam](https://materialdesignicons.com/icon/beam)](https://materialdesignicons.com/icon/beam)
