### ISSUE TITLE
Car ECU icon

### ISSUE THREAD

**Issue by volpatorafael** [Templarian/MaterialDesign#1604]
Like https://t1.ftcdn.net/jpg/00/46/21/78/400_F_46217877_wijLdiNIga4PvrRjBgN8rECSK0SYEtF0.jpg

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/engine
https://materialdesignicons.com/icon/engine-outline

These two above exist. Marking it as a duplicate.
