### ISSUE TITLE
Project Icon

### ISSUE THREAD

**Issue by Chan4077** [Templarian/MaterialDesign#1605]
![Possible Project Icon](http://www.freeiconspng.com/uploads/project-icon-30.png)
Link: http://www.freeiconspng.com/uploads/project-icon-30.png

**Comment by Chan4077** [comment]
![Possible Project Icon](http://www.freeiconspng.com/uploads/project-icon-30.png)

**Comment by MrGrigri** [comment]
That would be a bit complicated for a 24X24 pixel icon. What about a hard hat?

**Comment by MrGrigri** [comment]
Something like this:

![projects 4x](https://cloud.githubusercontent.com/assets/4528551/19980354/4276163e-a1c3-11e6-9bfc-59181b418a75.png) ![projects](https://cloud.githubusercontent.com/assets/4528551/19980355/428b819a-a1c3-11e6-8e2a-05d9031485b5.png)

[project.zip](https://github.com/Templarian/MaterialDesign/files/569829/project.zip)

**Comment by JamesCoyle** [comment]
I like the idea of a pencil ruler combo too.

**Comment by phidias51** [comment]
What about something that looks like a Gantt chart?

**Comment by JamesCoyle** [comment]
[![chart-gantt](https://materialdesignicons.com/icon/chart-gantt)](https://materialdesignicons.com/icon/chart-gantt)

**Comment by phidias51** [comment]
If you removed the vertical bar, it would communicate better. The vertical bar makes it look like an Orthodox cross.

**Comment by CoDEmanX** [comment]
Inspired by GitHub's project icon: ![project](https://cloud.githubusercontent.com/assets/1309249/24749612/06c49366-1ac4-11e7-9eb1-80390f0393e0.png)

I had to push the rectangle 1px closer to the border on the right side to fit the 3 bars.

**Comment by PeterShaggyNoble** [comment]
@phidias51, `chart-gant` without the vertical bar is [`notifications-clear-all`](https://materialdesignicons.com/icon/notification-clear-all) flipped. And the icon @CoDEmanX suggested above is similar Google's `graph options` icon flipped.

![graph options](https://user-images.githubusercontent.com/15157491/37103231-a5de17b4-2221-11e8-8a33-ef57300bb136.png)

**Comment by CoDEmanX** [comment]
That graph options icon plus a flipped version would be nice additions IMO.

**Comment by CoDEmanX** [comment]
The outer bars should be longer than the middle one though. Maybe like this?

![image](https://user-images.githubusercontent.com/1309249/38770372-81df3212-4012-11e8-8ab5-1e15f66cd5e8.png)

[project.zip](https://github.com/Templarian/MaterialDesign/files/1910601/project.zip)

**Comment by CoDEmanX** [comment]
I find it easier to recognize if it's larger, but with only 1px margin on the right-hand side:

![grafik](https://user-images.githubusercontent.com/1309249/38997853-ae8fcdbe-43ee-11e8-8f5b-1cb293e9e417.png)
[project.zip](https://github.com/Templarian/MaterialDesign/files/1928524/project.zip)

**Comment by CoDEmanX** [comment]
Non-rounded works better IMO:

![grafik](https://user-images.githubusercontent.com/1309249/39070563-2a3851d4-44e4-11e8-8d79-8f95bb6e16f5.png)

[project2.zip](https://github.com/Templarian/MaterialDesign/files/1933450/project2.zip)

**Comment by CoDEmanX** [comment]
It's what GitHub uses and represents a kanban board. So maybe call it that instead?

**Comment by Chan4077** [comment]
I'm closing this issue since it's been resolved for me.

**Comment by PeterShaggyNoble** [comment]
See also #3299
