### ISSUE TITLE
Request - Text Area / Input

### ISSUE THREAD

**Issue by ButchMonkey** [Templarian/MaterialDesign#1606]
I'm creating a forms designer, similar to Visual Studio Forms.
I plan on using icons to represent the elements like this - https://snag.gy/CauMbV.jpg

Would it be possible to add a variant of "format-text" to show the difference between text input and text area?

Thanks

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/textbox ?

But we don't have one for `textarea`.

**Comment by ButchMonkey** [comment]
Thanks, might need review the tags as I couldn't find this when searching

**Comment by MrGrigri** [comment]
@Templarian what about this?

![textarea 4x](https://cloud.githubusercontent.com/assets/4528551/19982422/a2d7fba2-a1cb-11e6-8f31-aa71adcb8840.png) ![textarea](https://cloud.githubusercontent.com/assets/4528551/19982423/a2d8979c-a1cb-11e6-91a2-90d55844f173.png)

[textarea.zip](https://github.com/Templarian/MaterialDesign/files/569961/textarea.zip)

**Comment by ButchMonkey** [comment]
Looks good. Does it need the text cursor as well or is it its use clear?

**Comment by ButchMonkey** [comment]
@Templarian Any update on this?

Thanks

**Comment by PeterShaggyNoble** [comment]
Discussion of this icon has moved to #3533. Closing here.
