### ISSUE TITLE
Request - Silhouettes from icons

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#1607]
Hi there!

I'm not very practiced in designing icons myself.  So I wonder if someone here could make silhouettes version of the following icons for me:
https://materialdesignicons.com/icon/thermometer
https://materialdesignicons.com/icon/relative-scale
https://materialdesignicons.com/icon/test-tube

All I need is a opaque silhouette version of those icons. (like [circle](https://materialdesignicons.com/icon/checkbox-blank-circle) is a silhouette of [gauge](https://materialdesignicons.com/icon/gauge))

Thanks in advance.

**Comment by JamesCoyle** [comment]
Not really what these issues are intended for but I'll leave it here if someone feels like helping you out. If you look at an SVG tutorial you could probably learn what the letters mean in the path and be able to remove the ones you don't need quite easily. Will just take a bit of trial and error to get it right.

**Comment by Ch-Lo** [comment]
I requested them to make opaque/colored backgrounds and combine them with the corresponding icons. 
I figured out how to make them myself, using the method you descriped. I can post the resulting svg-paths if desired.

Request can be closed. Thanks for you help.
