### ISSUE TITLE
Police Badge Icon

### ISSUE THREAD

**Issue by gamebusterz** [Templarian/MaterialDesign#1608]
Please add a Police Badge Icon, something like this : 
![police badge-48](https://cloud.githubusercontent.com/assets/6880188/19926670/d2aa2590-a11b-11e6-8fcf-604fac5fd4c4.png)

**Comment by MrGrigri** [comment]
https://github.com/Templarian/MaterialDesign/issues/1343

**Comment by Templarian** [comment]
Marking as a duplicate, but I like the idea of a simple shield+star. The hat is also a nice idea. Discuss in the other thread.

**Comment by MrGrigri** [comment]
I too like the star.

**Comment by gamebusterz** [comment]
I'll make a comment on that thread as a reminder for the star.
