### ISSUE TITLE
Save icon

### ISSUE THREAD

**Issue by christian160984** [Templarian/MaterialDesign#161]
What icon is more accurate for the Save button?

- Check
- Down arrow
- Floppy
- Plus
...

**Comment by Templarian** [comment]
I think most use the [content-save](http://materialdesignicons.com/icon/content-save) icon. But remember it is kind of assumed things are saved on some screens, so it may not be needed at all.

Note though that if it is being uploaded to the cloud it might be more ideal to use a [cloud-upload](http://materialdesignicons.com/icon/cloud-upload) icon.
