### ISSUE TITLE
Request : Shared Folder

### ISSUE THREAD

**Issue by Lemick** [Templarian/MaterialDesign#1610]
A _folder_ icon with a _share-variant_ icon on it could be very useful (we only have a Google Drive icon..)

**Comment by ButchMonkey** [comment]
What about [folder-account](https://materialdesignicons.com/icon/folder-account) as google share a document is a person and a plus

**Comment by Lemick** [comment]
Nice ! Thanks for your reply :)

**Comment by PeterShaggyNoble** [comment]
@Lemick, are you still in need of the icon described in your original request?

**Comment by Lemick** [comment]
No, not anymore, thanks.
