### ISSUE TITLE
Format-Pilcrow <Paragraph Marker>

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1611]
I saw that there is already a [paragraph](https://materialdesignicons.com/icon/format-paragraph) in the repo, but it's not the same as a pilcrow. So I've come up with this. I believe that format-pilcrow would work best. It would match [format-section](https://github.com/Templarian/MaterialDesign/issues/1420).

![pilcrow](https://cloud.githubusercontent.com/assets/4528551/19935889/456f089c-a0e1-11e6-8dca-846c7abb9c8d.png) ![pilcrow 4x](https://cloud.githubusercontent.com/assets/4528551/19935890/456f8eac-a0e1-11e6-88a2-adac35125e0f.png)

**Comment by JamesCoyle** [comment]
Looks good to me. Don't forget to post the SVG.

**Comment by Templarian** [comment]
[![format-pilcrow](https://materialdesignicons.com/icon/format-pilcrow)](https://materialdesignicons.com/icon/format-pilcrow)
