### ISSUE TITLE
calendar-arrow-right

### ISSUE THREAD

**Issue by justinlawrence** [Templarian/MaterialDesign#1612]
Suggestion: a calendar icon containing a right arrow.

Thanks!

**Comment by PeterShaggyNoble** [comment]
Clock hands inside a reload icon could also work.

**Comment by PeterShaggyNoble** [comment]
[mdi-update](https://materialdesignicons.com/icon/update) was what I was thinking of above.

**Comment by terreng** [comment]
Here are some variations I tried out:

[![image](https://user-images.githubusercontent.com/11605395/61585688-1f587880-ab17-11e9-86ef-7dbf75b4a0f0.png)](https://github.com/terreng/samples/blob/master/calendar-reschedule-1.svg)[![image](https://user-images.githubusercontent.com/11605395/61585690-2f705800-ab17-11e9-9aee-95e6bbff9bf6.png)](https://github.com/terreng/samples/blob/master/calendar-reschedule-2.svg)
[![image](https://user-images.githubusercontent.com/11605395/61585691-38f9c000-ab17-11e9-8854-9c329334d172.png)](https://github.com/terreng/samples/blob/master/calendar-reschedule-3.svg)[![image](https://user-images.githubusercontent.com/11605395/61585694-444ceb80-ab17-11e9-9baf-82340590a4bb.png)](https://github.com/terreng/samples/blob/master/calendar-reschedule-4.svg)

**Comment by goyney** [comment]
Unfortunately, there's too much complexity in that clock for those to be considering Material.

**Comment by terreng** [comment]
A calendar containing a right arrow is more of a "move" action. The update icon does a much better job demonstrating rescheduling. If we're going to add one with a right arrow, would it also make sense to have one with a left arrow?

**Comment by terreng** [comment]
Here are two possible versions

![image](https://user-images.githubusercontent.com/11605395/62887895-0ea0ba00-bcf3-11e9-9a8b-abffb4121bd9.png)
[calendar-arrow-right.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-right.svg)

![image](https://user-images.githubusercontent.com/11605395/62887961-2d06b580-bcf3-11e9-9fac-c41ef5fa712b.png)
[calendar-arrow-right-2.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-right-2.svg)

**Comment by goyney** [comment]
Definitely the second one, need a left variant as well.

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/62889175-a6070c80-bcf5-11e9-83b2-71d19767830a.png)
[calendar-arrow-left.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-left.svg)

**Comment by goyney** [comment]
The arrows need to be better aligned to the grid in both cases.

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/62889704-c6839680-bcf6-11e9-8199-c6b0a0d7f2f6.png)
[calendar-arrow-right-3.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-right-3.svg)

![image](https://user-images.githubusercontent.com/11605395/62889747-d602df80-bcf6-11e9-90bc-1386bdcfa02e.png)
[calendar-arrow-left-2.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-left-2.svg)

**Comment by goyney** [comment]
The back edges of the arrow head and the arrow tail are still not on grid. 😕

**Comment by terreng** [comment]
I cut these out with an exacto-knife:

![image](https://user-images.githubusercontent.com/11605395/62891154-d355b980-bcf9-11e9-94d5-241d3e675539.png)
[calendar-arrow-left-3.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-left-3.svg)

![image](https://user-images.githubusercontent.com/11605395/62891116-be792600-bcf9-11e9-9a64-95d0675acdca.png)
[calendar-arrow-right-6.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-right-6.svg)

**Comment by goyney** [comment]
😄 I know you're trying, I hope I'm not frustrating you. What I mean is like this:

![image](https://user-images.githubusercontent.com/1015040/62891412-a4e4d800-bd13-11e9-88ff-90c70e908ab2.png)

Keeping lines on the grid make them not-blurry at the native size. Go back and look at the arrows in each of yours at the smallest size. We try to avoid that as much as possible, and with arrows like this its super easy to do that.

**Comment by terreng** [comment]
I understand completely. I present you my revised version:

![image](https://user-images.githubusercontent.com/11605395/62891941-e4072f00-bcfb-11e9-8a72-963be6e75271.png)

Features include:
- 25% more precise
- Done away with those pesky curves, slopes, or anything that isn't aligned to the grid
- Will never blur at native resolution

I had to make some sacrifices, but in the end I think the result speaks for itself.

All jokes aside, one of these two should work:

![image](https://user-images.githubusercontent.com/11605395/62892256-a7880300-bcfc-11e9-8502-a3b7725d06fe.png)
[calendar-arrow-right-7.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-right-7.svg)

![image](https://user-images.githubusercontent.com/11605395/62892356-ee75f880-bcfc-11e9-8f81-5740ea6b777f.png)
[calendar-arrow-right-8.svg](https://github.com/terreng/samples/blob/master/calendar-arrow-right-8.svg)

**Comment by JamesCoyle** [comment]
I like the smaller one the best.

**Comment by goyney** [comment]
The two examples provided has an arrow size in between what we'll actually add. The arrow in my example was taken from our existing arrows and will likely be the size we add.

**Comment by goyney** [comment]
[![calendar-arrow-left](https://materialdesignicons.com/icon/calendar-arrow-left)](https://materialdesignicons.com/icon/calendar-arrow-left)[![calendar-arrow-right](https://materialdesignicons.com/icon/calendar-arrow-right)](https://materialdesignicons.com/icon/calendar-arrow-right)

**Comment by justinlawrence** [comment]
Looks awesome, thanks everyone! Please add the word "reschedule" as an alias for this icon, so it comes up in the search.
