### ISSUE TITLE
All of the material icons look pixelated?

### ISSUE THREAD

**Issue by erstaeuble** [Templarian/MaterialDesign#1613]
All of the material icons look pixelated while all the others are crisp and clear. Was curious to see why this is and can we fix it? 

This one is an octagon scaled down to look like a circle.
![14954265_10154821456984994_77953557_o](https://cloud.githubusercontent.com/assets/10836909/19980576/f3ee4d62-a1d4-11e6-8fa1-02d63b30e5aa.jpg)

This one is the material circle.
![14958001_10154821453124994_1014472162_o](https://cloud.githubusercontent.com/assets/10836909/19980575/f3ecc6ea-a1d4-11e6-8e9f-335a324558f8.jpg)

**Comment by Templarian** [comment]
Probably nothing we can do on our end to fix this. Probably depends on how the OS is handling sizing. It probably looks nicer on 2x displays though. I suggest using SVG for these types as the font rendering engine's scaling may not adapt as nicely.

**Comment by erstaeuble** [comment]
Good to know thanks for the quick response.
