### ISSUE TITLE
Icon Request - TeX / LaTeX Icon

### ISSUE THREAD

**Issue by nmcardoso** [Templarian/MaterialDesign#1614]
LaTeX / TeX logo

**Comment by allen5261** [comment]
The zip is here：
[LaTeX.zip](https://github.com/Templarian/MaterialDesign/files/1186627/LaTeX.zip)

**Comment by goyney** [comment]
I do not think this works as an icon:

![image](https://user-images.githubusercontent.com/1015040/48992210-a11d1100-f104-11e8-8a3d-7d53e368ea66.png)

**Comment by goyney** [comment]
We've discussed this internally and decided to not add this logo to the library. Thanks for your suggestion.

**Comment by gilbertohasnofb** [comment]
@goyney would you then consider then adding a TeX icon? It might work better as an icon since it is not so wide:

![image](https://user-images.githubusercontent.com/5700795/49007377-3bac3d00-f163-11e8-8172-cdad5fde4c8c.png)

**Comment by goyney** [comment]
Still pretty indistinguishable. We're going to stand by our original decision.

![image](https://user-images.githubusercontent.com/1015040/49028813-453ca180-f171-11e8-9ccd-3768914a219c.png)
