### ISSUE TITLE
Reminder String icon (used by google keep to set new reminder)

### ISSUE THREAD

**Issue by hamadjowher7** [Templarian/MaterialDesign#1617]
Not sure why google icon (material.io/icons) doesn't have this. They use it in Google keep, though. See attached image.
![2e772219-f727-488a-a0bd-5944af342932](https://cloud.githubusercontent.com/assets/14961012/20030669/c338da9a-a38f-11e6-954e-39ea349e9308.jpg)

**Comment by JamesCoyle** [comment]
#518
