### ISSUE TITLE
Roku

### ISSUE THREAD

**Issue by mikenolet** [Templarian/MaterialDesign#1618]
Roku icon would be nice.

**Comment by GreenTurtwig** [comment]
This should be good enough, although Roku don't really have a logo themselves.
[roku.zip](https://github.com/Templarian/MaterialDesign/files/612818/roku.zip)
![puush-linux 2016-11-25 at 08 43 00](https://cloud.githubusercontent.com/assets/15905797/20619252/6a7101e2-b2eb-11e6-8663-3740de6c295d.png)
![puush-linux 2016-11-25 at 08 44 12](https://cloud.githubusercontent.com/assets/15905797/20619257/6cc4dec8-b2eb-11e6-8628-0cd4aeeebd30.png)

**Comment by Templarian** [comment]
Best to use a more generic logo for this one.

https://www.roku.com/about/trademark-guidelines
