### ISSUE TITLE
Hockey Stick

### ISSUE THREAD

**Issue by mikenolet** [Templarian/MaterialDesign#1620]
New Icon Suggestion - Hockey Stick

**Comment by PeterShaggyNoble** [comment]
`hockey-sticks` was added in the latest release.

[![hockey-sticks](https://user-images.githubusercontent.com/15157491/37413976-0fd1af68-27a0-11e8-804c-c593dfebd43b.png)](https://materialdesignicons.com/icon/hockey-sticks)
