### ISSUE TITLE
Icon request - facebook-workplace

### ISSUE THREAD

**Issue by Stians92** [Templarian/MaterialDesign#1622]
Hi,

Facebook recently launched "Facebook at work", and for the launch they went with a full rebranding.

"Facebook at work" is now called "Workplace", as can be seen [here](https://workplace.fb.com/).

[Here](https://marketplace.servicerocket.com/static/workplacebyfacebook_icon.png) is a high-res png of their new logo.

**Comment by PeterShaggyNoble** [comment]
I'm going to close this one out for now. Per our [contributing guidelines](https://github.com/Templarian/MaterialDesign/blob/master/CONTRIBUTING.md):
> Please note that, at this time, the only brand icons we accept requests for are popular social media sites/apps and widely used products/software.

We may revisit this issue in the future, if we decide to add a dedicated icon pack for brands.

**Comment by PeterShaggyNoble** [comment]
This has since been added in #3479
