### ISSUE TITLE
Zip code / PO Box Icon?

### ISSUE THREAD

**Issue by yassinelazaar** [Templarian/MaterialDesign#1623]

**Comment by JamesCoyle** [comment]
Something like `email` with a small `map-marker` in the corner?

**Comment by yassinelazaar** [comment]
Right now I'm using `map-marker-radius` but i thought that a mailbox would be more appropriate.

**Comment by PeterShaggyNoble** [comment]
[![mailbox](https://user-images.githubusercontent.com/15157491/36986923-032207a4-2093-11e8-8a32-c1729beeb927.png)](https://materialdesignicons.com/icon/mailbox)
