### ISSUE TITLE
Foursquare category icons

### ISSUE THREAD

**Issue by viettanbkdn** [Templarian/MaterialDesign#1624]
Could you please add 11 main category icons and 1 for custom category (for venue without category):
https://developer.foursquare.com/categorytree

**Comment by PeterShaggyNoble** [comment]
- [Arts & Entertainment](https://materialdesignicons.com/icon/ticket)
- [College & University](https://materialdesignicons.com/icon/school)
- [Event](https://materialdesignicons.com/icon/calendar)
- [Food](https://materialdesignicons.com/icon/silverware-variant)
- [Nightlife Spot](https://materialdesignicons.com/icon/martini)
- [Outdoors & Recreation](https://materialdesignicons.com/icon/tree) ([Alt](https://materialdesignicons.com/icon/pine-tree))
- [Professional & Other Places](https://materialdesignicons.com/icon/city) (Alts: [1](https://materialdesignicons.com/icon/bank), [2](https://materialdesignicons.com/icon/factory))
- [Residence](https://materialdesignicons.com/icon/home-variant) ([Alt](https://materialdesignicons.com/icon/home))
- [Shop & Service](https://materialdesignicons.com/icon/shopping)
- [Travel & Transport](https://materialdesignicons.com/icon/briefcase) ([Alt](https://materialdesignicons.com/icon/wallet-travel))

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback.

@viettanbkdn, if the icons above don't suit your needs, please let us know and we'll reopen the issue.
