### ISSUE TITLE
Washer and Dryer Icons

### ISSUE THREAD

**Issue by rpitera** [Templarian/MaterialDesign#1625]
For use in home automation systems that support MD Icons like Home Assistant.

**Comment by CoDEmanX** [comment]
washer as in washing machine or dishwasher? There should be an icon for the former already.

**Comment by rpitera** [comment]
Sorry, should have been more specific - clothes washer/washing machine.   There isn't an icon for either currently.

**Comment by assanges** [comment]
Should the project also include the washing labels? I guess that might helps?

**Comment by Templarian** [comment]
[![washing-machine](https://materialdesignicons.com/icon/washing-machine)](https://materialdesignicons.com/icon/washing-machine)

I don't know what the dryer would look like though. I assume the same?

**Comment by rpitera** [comment]
I'm currently using these PNGs in place of icons; perhaps it will give you an idea?
Dryer:
![orig dryer](https://cloud.githubusercontent.com/assets/19910294/20668599/a0fa8a0e-b53d-11e6-8a78-65ee982e5cdc.png)
Wsaher:
![orig washer](https://cloud.githubusercontent.com/assets/19910294/20668614/afeb08c2-b53d-11e6-8918-9d6e79d24601.png)

**Comment by GreenTurtwig** [comment]
![](https://puu.sh/vGFFr.png)
![](https://puu.sh/vGFHx.png)
[tumble-dryer.zip](https://github.com/Templarian/MaterialDesign/files/980127/tumble-dryer.zip)
Just @PeterShaggyNoble 's `wave` / [dry](https://github.com/Templarian/MaterialDesign/issues/2000) icon in a washing machine. Rough at a small scale. :-/

**Comment by vibrog** [comment]
With round line caps, based on the two above suggestions.
![tumble-dryer-24](https://user-images.githubusercontent.com/67639/29001340-f778bb98-7a87-11e7-8378-b474c999109c.png)
![tumble-dryer-96](https://user-images.githubusercontent.com/67639/29001339-f7786756-7a87-11e7-8edb-54526e62e585.png)
[tumble-dryer.svg.zip](https://github.com/Templarian/MaterialDesign/files/1202934/tumble-dryer.svg.zip)

**Comment by JamesCoyle** [comment]
@vibrog Strokes in material design terminate in flat edges.

**Comment by rpitera** [comment]
Coming up on a year since the initial request - I would just like to see these added.

**Comment by andreasjacobsen93** [comment]
Can we get @vibrog 's icon included? that would be awesome.

**Comment by hvbhome** [comment]
while you're at it, please add a dishwasher too ?

could be the same outlining with a set of dishes/silverware inside

**Comment by PeterShaggyNoble** [comment]
@hvbhome, see #2313.

**Comment by hvbhome** [comment]
ok cool! can we use these yet? I cant find them in the set on https://materialdesignicons.com

sorry, new on the forum here, please forgive me for asking the obvious...

**Comment by PeterShaggyNoble** [comment]
@hvbhome, when an icon has been added to the library, Templarian will generally post a preview of it (as with `washing-machine` above) and, if it was the only icon requested in that issue, close the issue out. So a general rule of thumb is no preview and/or an open issue means it hasn't been added yet. You can also keep an eye on the history page for updates on icons being added.

Having said that, you can download the linked zips from the relevant issues and use the SVGs while you're waiting for it to be added.

**Comment by Templarian** [comment]
[![tumble-dryer](https://materialdesignicons.com/icon/tumble-dryer)](https://materialdesignicons.com/icon/tumble-dryer)

Really should not have taken me this long, not sure how I kept overlooking this. The milestone tracking should definitely help.

**Comment by hvbhome** [comment]
thanks! very nice.
can't get it to show up yet, sure its named correctly, or will upload take some more time?
