### ISSUE TITLE
Rx icon for EHR/EMR 

### ISSUE THREAD

**Issue by clatimer** [Templarian/MaterialDesign#1627]
Please create a "Rx" icon for prescription medicines. 

Thanks!

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/20867175/37dd7380-ba36-11e6-9955-3715b5bacf05.png)

**Comment by MrGrigri** [comment]
I believe that would be too small at a 24x24 pixel scale.

**Comment by RobertoGraham** [comment]
24x24: 
![image](https://cloud.githubusercontent.com/assets/14958777/20867818/a646419a-ba44-11e6-9290-a08fea4d9b72.png)

Stroke width of 2 so in theory it should be legible

**Comment by Templarian** [comment]
@RobertoGraham Please zip and attach to a comment (this goes for all contributions).

**Comment by RobertoGraham** [comment]
[rx.zip](https://github.com/Templarian/MaterialDesign/files/629799/rx.zip)

**Comment by clatimer** [comment]
Thank you so much! This is amazing! ☺

**Comment by Templarian** [comment]
[![prescription](https://materialdesignicons.com/icon/prescription)](https://materialdesignicons.com/icon/prescription)
