### ISSUE TITLE
Project Icon

### ISSUE THREAD

**Issue by phidias51** [Templarian/MaterialDesign#1628]
It would be useful to have a "project" icon.  Perhaps something that looks a little like a gantt chart with a series of stair-step horizontal lines. You can see some examples here: https://www.google.com/search?q=gantt+chart+icon&espv=2&biw=1266&bih=656&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiEm66PnpzQAhVplVQKHQ0DBWMQ7AkIPA

**Comment by MrGrigri** [comment]
https://github.com/Templarian/MaterialDesign/issues/1605

**Comment by JamesCoyle** [comment]
[![chart-gantt](https://materialdesignicons.com/icon/chart-gantt)](https://materialdesignicons.com/icon/chart-gantt)
