### ISSUE TITLE
file-outline

### ISSUE THREAD

**Issue by DanielDestino** [Templarian/MaterialDesign#163]
Hi.

A outline version of the file icon would be appreciated, like they have in the font awsome icon set:
http://fortawesome.github.io/Font-Awesome/icon/file-o/

It is needed if you want to add the file extension of the file using CSS inside the icon for file types that does not have a icon.

- [ ] file-outline

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/file-outline
