### ISSUE TITLE
Icon Request – Charts

### ISSUE THREAD

**Issue by olebor** [Templarian/MaterialDesign#1630]
I would like to order 5 to 10 chart related icons. There might also be additional needs in the near feature.

I will provide the spec, and expect a cost and time estimate back. I need this as soon as possible.

**Comment by JamesCoyle** [comment]
This isn't a place to hire people. If you need specific icons for a project you are best looking elsewhere.

**Comment by olebor** [comment]
Hi,

Sorry for not being more specific.

I need multiple chart icons in addition to the ones already in the material design icons collection created by Mr Austin Andrews . And I want these new icons to be added to the collection as well if you guys want it in there. However, due to time constraints on my side I am willing to pay to get them made.

It was actually @Templarian himself that told a colleauge of mine to add an issue here (on twitter).

I am sorry if this was not the correct place to put this request

**Comment by CoDEmanX** [comment]
This project is open source and the contributors create and share icons voluntarily and free of charge. If you share your specs someone might give it a shot. Not sure if @Templarian would be up for freelance work?
