### ISSUE TITLE
Hook icon

### ISSUE THREAD

**Issue by tennisgent** [Templarian/MaterialDesign#1631]
As in a fishing hook, something like: http://images.clipartpanda.com/fishing-hook-clipart-fishing-hook-clipart-300x296.png

**Comment by MrGrigri** [comment]
Like these? Hook-on and hook-off (maybe?).

![hook 4x](https://cloud.githubusercontent.com/assets/4528551/20273993/75cda5de-aa50-11e6-8f87-ad9701b62b6c.png) ![hook](https://cloud.githubusercontent.com/assets/4528551/20273994/75d4d52a-aa50-11e6-9d70-268290e384a1.png)


![hook-off 4x](https://cloud.githubusercontent.com/assets/4528551/20274014/7f3db58c-aa50-11e6-99aa-a050cc162f75.png) ![hook-off](https://cloud.githubusercontent.com/assets/4528551/20274015/7f4f9eaa-aa50-11e6-81a6-6e3018f9d478.png)

[hook.zip](https://github.com/Templarian/MaterialDesign/files/589906/hook.zip)

**Comment by tennisgent** [comment]
Looks good! 👍

**Comment by CoDEmanX** [comment]
Maybe the pike can be made a litter bigger? It's a bit hard to see on normal density screens I feel.

**Comment by MrGrigri** [comment]
Here it is with a larger barb (I assume that's what you mean). 

![hook 4x](https://cloud.githubusercontent.com/assets/4528551/20318618/274aac8a-ab28-11e6-8c84-74bca102f6a4.png) ![hook](https://cloud.githubusercontent.com/assets/4528551/20318616/27479ec8-ab28-11e6-85f9-acf54af24d27.png)

![hook-off 4x](https://cloud.githubusercontent.com/assets/4528551/20318619/274c4450-ab28-11e6-8786-a4fe63dcbfad.png) ![hook-off](https://cloud.githubusercontent.com/assets/4528551/20318617/27486a9c-ab28-11e6-9957-fe352bfa9276.png)

[hook.zip](https://github.com/Templarian/MaterialDesign/files/592822/hook.zip)

**Comment by tennisgent** [comment]
The larger barb looks great. I really hate to be picky, but is it possible to make the eye of the hook a tad smaller? If not, I'm cool with it the way it is, but the eye seems slightly larger than it should be proportionally... 😃

**Comment by MrGrigri** [comment]
I tried that but it didn't look great.

**Comment by Templarian** [comment]
@tennisgent I think due to the Material Design style constraints some things have to be exaggerated to better fit the style. The loop in this case.

**Comment by tennisgent** [comment]
Sounds good! Thanks for all the good work! :)

**Comment by Templarian** [comment]
[![hook](https://materialdesignicons.com/icon/hook)](https://materialdesignicons.com/icon/hook) [![hook-off](https://materialdesignicons.com/icon/hook-off)](https://materialdesignicons.com/icon/hook-off)
