### ISSUE TITLE
music-note-outline

### ISSUE THREAD

**Issue by Axieum** [Templarian/MaterialDesign#1632]

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/60060626-82452400-96bf-11e9-8ee3-6ae47fa69be0.png)![image](https://user-images.githubusercontent.com/1015040/60060638-8b35f580-96bf-11e9-8711-fd70bf7fa23a.png)

[music-note-outline.zip](https://github.com/Templarian/MaterialDesign/files/3323061/music-note-outline.zip)

**Comment by goyney** [comment]
This issue will be addressed in #3263.
