### ISSUE TITLE
Icon cop/policeman

### ISSUE THREAD

**Issue by SeyoS** [Templarian/MaterialDesign#1633]
A missing Icon is a cop or a policeman like this one (https://materialdesignicons.com/icon/worker) but with an american cop hat (http://i.ebayimg.com/images/g/P~wAAOSwTA9X8lLD/s-l300.jpg).

**Comment by MrGrigri** [comment]
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/1343

**Comment by JamesCoyle** [comment]
I'd say this is a separate icon really though I'm not really sure where we are going with these worker variants. There are only a few professions that can be shown via hats: fireman's helmet, racing helmet, chef hat, maybe a beret, Don't really know what else you could include.

**Comment by SeyoS** [comment]
To my mind,it was to identify a security process in a funny way.
For example,I use the worker to identify an updating process

**Comment by assanges** [comment]
![police-checkered-clean-01](https://cloud.githubusercontent.com/assets/4113063/20645107/6dfd7e64-b48d-11e6-9bb6-9808c197f839.png)

You mean something like this?

**Comment by SeyoS** [comment]
Exactly ! Something to show authority or security purpose !
