### ISSUE TITLE
phone-off

### ISSUE THREAD

**Issue by savaka2** [Templarian/MaterialDesign#1634]
probably going to have to reverse the off slash though

**Comment by Templarian** [comment]
Just for clarity, what is this icon going to represent?

I'm mostly asking since I think `phone-hangup` might be a better choice. It's an odd icon to add a slash to, but we have broken the direction of the `off` slash a few times.

**Comment by savaka2** [comment]
If you need to separate ringtone and notification volumes, you'd use it to turn off ringtone volume

**Comment by GreenTurtwig** [comment]
Here:
[phone-off.zip](https://github.com/Templarian/MaterialDesign/files/612838/phone-off.zip)
The slash has been flipped to avoid removing detail. :cat2:

**Comment by PeterShaggyNoble** [comment]
Possible duplicate of #1062?

**Comment by CoDEmanX** [comment]
I guess phone-off would work for #1062 (broken cellphone) as well. Although I wonder in what way broken and in which situation to use it...

**Comment by Templarian** [comment]
[![phone-off](https://materialdesignicons.com/icon/phone-off)](https://materialdesignicons.com/icon/phone-off)
