### ISSUE TITLE
Icon Request - fast-book

### ISSUE THREAD

**Issue by erikdinh** [Templarian/MaterialDesign#1635]
Hi,

We are producing summarized contents of popular books and we call it fast book. We've been looking for an icon that reflects the term but haven't found it yet.

Could anyone replace the clock in this one: https://materialdesignicons.com/icon/clock-fast into a book? 

Thank you

**Comment by PeterShaggyNoble** [comment]
I'm going to close this out as being too niche, as it's only real use case, at the moment, is within your own product.
