### ISSUE TITLE
about icon

### ISSUE THREAD

**Issue by mahdimortazavi** [Templarian/MaterialDesign#1638]
about icon.
about app
about company

**Comment by Templarian** [comment]
There are a few "about" icons called `information`, `information-outline`, and `information-variant` that should suffice.

Do you have an example of what "about app" or "about company" would look like? I might suggest using a more general icon for these (building for a company for instance).

**Comment by Templarian** [comment]
Closing this issue out. If it gets more details we can reopen it.
