### ISSUE TITLE
Empty Trash Icon

### ISSUE THREAD

**Issue by bsinc** [Templarian/MaterialDesign#1639]
Icon to show the trash can is empty. Maybe the trash can with an outline, or something like this:

![full_recycle_bin-512](https://cloud.githubusercontent.com/assets/5923661/20318278/744710dc-ab1e-11e6-9567-6721478d77ef.png)

**Comment by Templarian** [comment]
[![delete-empty](https://materialdesignicons.com/icon/delete-empty)](https://materialdesignicons.com/icon/delete-empty)

I'm not sure this one looks right. Going to leave this open. There is probably a nicer way this could be designed.

**Comment by daanwintjes** [comment]
This is what I've come up with:

![trash-empty](https://cloud.githubusercontent.com/assets/26581209/25011319/3d49dea6-206d-11e7-82f7-0f22d6267e21.png)

**Comment by augustin32** [comment]
![delete-empty48](https://user-images.githubusercontent.com/14167196/28199612-a7767d8a-686f-11e7-86b2-8a973fe0d075.png)
![delete-empty24](https://user-images.githubusercontent.com/14167196/28199614-a7c259bc-686f-11e7-8e84-eb4e695bb2e9.png)
![delete-empty36](https://user-images.githubusercontent.com/14167196/28199615-a7c5548c-686f-11e7-944b-3d2d8318d3fc.png)
[delete-empty.zip](https://github.com/Templarian/MaterialDesign/files/1147443/delete-empty.zip)

**Comment by goyney** [comment]
We now have `delete-empty`, `delete-empty-outline`, and `delete-outline`.
