### ISSUE TITLE
Suggestion: Android Beam

### ISSUE THREAD

**Issue by jedld** [Templarian/MaterialDesign#164]
I would like an Icon that indicates that the current screen supports Android Beam file transfer

**Comment by Templarian** [comment]
Do you mean the NFC icon?

http://materialdesignicons.com/icon/nfc (logo)
http://materialdesignicons.com/icon/nfc-variant (this is probably what you mean).

**Comment by jedld** [comment]
Oh yeah, though I was thinking of something along the lines of two phones being held together 

http://www.samsung.com/us/system/support/content/2013/06/19/h11079/sbeam1.png

**Comment by chrislitherland95** [comment]
I agree that the NFC icon does not necessarily represent the user should touch the backs of the phones. Many users are unaware of the role of NFC in this process so a more practical example would be useful.

**Comment by jedld** [comment]
Yeah, looks like it will take more than an icon to illustrate android beam.

**Comment by chrislitherland95** [comment]
I would say so. Perhaps for consistency, you might be able to contrive the imagery from the Android Lollipop first time startup guide (where users are prompted to transfer information via Android Beam from a previous device). That would be OS consistent and fairly user obvious, without too much effort.

**Comment by Templarian** [comment]
I'm going to agree with @chrislitherland95 it would be the preferred UX to illustrate the action on the first use maybe pointing at the nfc-variant icon.

I started messing with a design, but I'm not sure this makes more sense than explaining Android's NFC icon (aka nfc-variant on the site).

![nfc-tap](https://cloud.githubusercontent.com/assets/338885/6342666/ee243146-bba1-11e4-925a-7fd0ceb3f5e1.png)

**Comment by Templarian** [comment]
On Windows they use this: Actually I actually think it fits really nice on Android also. The only issue is it is the NFC trademarked logo for Windows products.

http://www.nfcworld.com/wp-content/uploads/2012/03/microsoft-tap-and-do-nfc-logo.jpg
![image](https://cloud.githubusercontent.com/assets/338885/6342792/2f1476aa-bba4-11e4-8d2d-45278c634d71.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/nfc-tap
