### ISSUE TITLE
Event Icons

### ISSUE THREAD

**Issue by Rameshsam** [Templarian/MaterialDesign#1641]

**Comment by Templarian** [comment]
Generally a `calendar` is used for this and there are numerous. Do you have an example of what an "event" icon would look like (images can be pasted in comments)?

**Comment by PeterShaggyNoble** [comment]
Maybe a calendar with a star on it, similar to Foursquare's event icon?

![Event](https://ss0.4sqi.net/img/categories_v2/event/default_bg_32-c9c920d22c5e652116e0c732bf3dbd5d.png)

**Comment by MrGrigri** [comment]
Or the ticket icon is a good option. However, the star in a calendar is more of a favorite date/event.

![ticket](https://materialdesignicons.com/icon/ticket)

**Comment by MrGrigri** [comment]
@Templarian, Here is one that we could call `calendar-favorite`. 

![calendar-favorite 4x](https://cloud.githubusercontent.com/assets/4528551/20867875/44e945d4-ba0b-11e6-8e70-2f0804f4b953.png) ![calendar-favorite](https://cloud.githubusercontent.com/assets/4528551/20867874/44e81c04-ba0b-11e6-93b5-4a319d9aa4bf.png)

[calendar-favorite.zip](https://github.com/Templarian/MaterialDesign/files/629684/calendar-favorite.zip)

**Comment by PeterShaggyNoble** [comment]
Suggest aliasing this as `calendar-event` and `calendar-star` when it's added.

**Comment by CoDEmanX** [comment]
Moved the star slightly up to center it better, and to have the horizontal lines on grid:

![image](https://user-images.githubusercontent.com/1309249/38770416-31f4f056-4013-11e8-9317-40b4e18d7e76.png)

[calendar-favorite.zip](https://github.com/Templarian/MaterialDesign/files/1910608/calendar-favorite.zip)

**Comment by Templarian** [comment]
[![calendar-heart](https://materialdesignicons.com/icon/calendar-heart)](https://materialdesignicons.com/icon/calendar-heart) [![calendar-star](https://materialdesignicons.com/icon/calendar-star)](https://materialdesignicons.com/icon/calendar-star)
