### ISSUE TITLE
Open / Load File or Folder - Icon request

### ISSUE THREAD

**Issue by ButchMonkey** [Templarian/MaterialDesign#1645]
Something like an open folder maybe, similar to what Microsoft do?

**Comment by Templarian** [comment]
Do you have an example of what this icon looks like?

**Comment by ButchMonkey** [comment]
[Open Folder](https://cdn3.iconfinder.com/data/icons/medical-7-1/512/open_folder_blue-128.png)

**Comment by ButchMonkey** [comment]
As I said, not an artist :P

![folder-open](https://cloud.githubusercontent.com/assets/9367266/20462398/fc813780-af14-11e6-9a0e-589f0141c572.png)

**Comment by MrGrigri** [comment]
Google uses the following for an open and closed folder:

![folder-open](https://materialdesignicons.com/icon/folder) ![folder-closed](https://materialdesignicons.com/icon/folder-outline)

Google also specifically states that there should not be thin lines and uses an open folder as an example.

![materialguidelines](https://cloud.githubusercontent.com/assets/4528551/20499583/46c956bc-afef-11e6-9f4f-7220baf82b11.PNG)

**Comment by ButchMonkey** [comment]
I can't view the folder open/closed that you linked, however I think I might know as to which you are referencing.
To me, the Google open folder represents open as in the adjective. I am looking for an icon that conveys to open a folder or file.

As for the thin strokes, this was my suggestion to exaggerate the whitespace

**Comment by Templarian** [comment]
![folder-open](https://cloud.githubusercontent.com/assets/338885/20659809/8436da76-b50b-11e6-90bf-63ec37e506a5.png)
![folder-open-48](https://cloud.githubusercontent.com/assets/338885/20659811/86f6285c-b50b-11e6-9a21-290169953717.png)

I know it works, but I'm wondering if we're going against Material Design by adding a secondary Folder Open icon. Any opinions on this guys? (/cc @CoDEmanX @JamesCoyle, etc...).

**Comment by JamesCoyle** [comment]
My personal opinion is to stick to the guidelines. There are already a few icons in the pack I wouldn't use because of their dimensionality. They look out of place beside the other icons.

**Comment by CoDEmanX** [comment]
@Templarian that open folder icon looks pretty ugly to me, sorry 🙈
