### ISSUE TITLE
BPMN Additions

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#1646]
We are utilizing this icon library with a [BPMN ](http://www.bpmn.org/) product. While [most icons required in the BPMN spec](http://www.bpmb.de/index.php/BPMNPoster) can be handled by this icon library, there are a few variations and outliers that are important to us. I have created these 21 icons with the hope of contributing.

![summary](https://cloud.githubusercontent.com/assets/1015040/20444016/6004333a-ad9d-11e6-818c-e7cfe50c7c43.png)
[bpmn-icons.zip](https://github.com/Templarian/MaterialDesign/files/600786/bpmn-icons.zip)

**Comment by Templarian** [comment]
[![pentagon](https://materialdesignicons.com/icon/pentagon)](https://materialdesignicons.com/icon/pentagon) [![pentagon-outline](https://materialdesignicons.com/icon/pentagon-outline)](https://materialdesignicons.com/icon/pentagon-outline)

**Comment by Templarian** [comment]
[![plus-outline](https://materialdesignicons.com/icon/plus-outline)](https://materialdesignicons.com/icon/plus-outline) [![plus-box-outline](https://materialdesignicons.com/icon/plus-box-outline)](https://materialdesignicons.com/icon/plus-box-outline)

**Comment by Templarian** [comment]
[![asterisk](https://materialdesignicons.com/icon/asterisk)](https://materialdesignicons.com/icon/asterisk) [![tilde](https://materialdesignicons.com/icon/tilde)](https://materialdesignicons.com/icon/tilde)

**Comment by Templarian** [comment]
[![fast-foward-outline](https://materialdesignicons.com/icon/fast-forward-outline)](https://materialdesignicons.com/icon/fast-forward-outline) [![rewind-outline](https://materialdesignicons.com/icon/rewind-outline)](https://materialdesignicons.com/icon/rewind-outline)

**Comment by Templarian** [comment]
[![view-sequential](https://materialdesignicons.com/icon/view-sequential)](https://materialdesignicons.com/icon/view-sequential) [![view-parallel](https://materialdesignicons.com/icon/view-parallel)](https://materialdesignicons.com/icon/view-parallel)

**Comment by Templarian** [comment]
[![close-outline](https://materialdesignicons.com/icon/close-outline)](https://materialdesignicons.com/icon/close-outline) [![loop](https://materialdesignicons.com/icon/loop)](https://materialdesignicons.com/icon/loop)

**Comment by Templarian** [comment]
[![flash-outline](https://materialdesignicons.com/icon/flash-outline)](https://materialdesignicons.com/icon/flash-outline) [![rhombus](https://materialdesignicons.com/icon/rhombus)](https://materialdesignicons.com/icon/rhombus) [![rhombus-outline](https://materialdesignicons.com/icon/rhombus-outline)](https://materialdesignicons.com/icon/rhombus-outline)

I think the remaining are too specific for us to add, but we got a lot of them added. Thanks!

**Comment by goyney** [comment]
I'm confused. Did you just take what I contributed and take credit for them?

**Comment by Templarian** [comment]
Sorry, was going to create an issue for your contributor account wrapped up adding them at 3am last night and forgot. I usually break the contributor accounts into separate issues. It's how the system works in the background, I add the icons then assign them over once the account is created.

https://github.com/Templarian/MaterialDesign/projects/1 View the inprogress column.

**Comment by goyney** [comment]
Ah, okay. Sorry, didn't mean to sound rude, I was just confused. Thanks for adding them into the library.

Might I ask why you feel the other are too specific? I would think that brand icons would be too specific, but not dashed circles. Thanks!

**Comment by Templarian** [comment]
No problem definitely get where your coming from. 😄 

I was thinking the circles are more like format icons (thinking like excel). They probably have a different context in your use case though. Not sure how _general_ of a use case they would have for most. Usually we view use cases as "As a user I click this icon to _____."

**Comment by goyney** [comment]
As a user, I would like to have a dashed circle/thicker circle/double-dashed circle around my icon so that I can indicate different states in a workflow.

Explanation: We stack a lot of icons. (In a way similar to Font Awesome's stacks). So, we'll use the circle with a shape inside of it. There are cases when that circle needs to be thicker, dotted, not a circle (a pentagon or rhombus). That would be our use case.

**Comment by Templarian** [comment]
Didn't think about stacking icons. I think we can get these 4 added shortly (heading to the bar now, but will be working on icons more from [now on](http://templarian.com/2016/11/15/life-and-open-source/)).
