### ISSUE TITLE
Light bulb on icon

### ISSUE THREAD

**Issue by raburton** [Templarian/MaterialDesign#1647]
I'm looking for icons for a light on and off. The light bulb icons are nice but I tried to use the solid and the outline ones to differentiate between on and off and it's not really intuitive as to which one is which. Any chance someone could do a modification of the light bulb icons (ideally both solid and outline) to add some light rays to clearly indicate the light is on, like the white balance incandescent icon. Thanks.

**Comment by Chan4077** [comment]
[lightbulb-on.svg.zip](https://github.com/Templarian/MaterialDesign/files/606492/lightbulb-on.svg.zip)
[lightbulb-outline-on.svg.zip](https://github.com/Templarian/MaterialDesign/files/606491/lightbulb-outline-on.svg.zip)

**Comment by MrGrigri** [comment]
Here is what I was able to come up with. Essentially, I used the incandescent icon, flipped it, and made it work.

* lightbulb-off
![lightbulb-off 4x](https://cloud.githubusercontent.com/assets/4528551/20533234/0a884f22-b09a-11e6-9775-d6b408cccbb3.png) ![lightbulb-off](https://cloud.githubusercontent.com/assets/4528551/20533233/0a7715a4-b09a-11e6-9e4b-972ec84e01ad.png)

* lightbulb-on
![lightbulb-on 4x](https://cloud.githubusercontent.com/assets/4528551/20533236/0a951072-b09a-11e6-8475-d165aa76d541.png) ![lightbulb-on](https://cloud.githubusercontent.com/assets/4528551/20533235/0a8d7402-b09a-11e6-824a-2ac4679f6b4a.png)

* lightbulb-outline-off
![lightbulb-outline-off 4x](https://cloud.githubusercontent.com/assets/4528551/20533288/37cf18c6-b09a-11e6-9799-83c97cf38bdf.png) ![lightbulb-outline-off](https://cloud.githubusercontent.com/assets/4528551/20533289/37d761d4-b09a-11e6-9552-55c854cc7877.png)

* lightbulb-ouline-on
![lightbulb-outline-on 4x](https://cloud.githubusercontent.com/assets/4528551/20533319/4d660faa-b09a-11e6-8827-212e1e1498a4.png) ![lightbulb-outline-on](https://cloud.githubusercontent.com/assets/4528551/20533318/4d62faae-b09a-11e6-8740-e56deea309da.png)

[lightbulb.zip](https://github.com/Templarian/MaterialDesign/files/607009/lightbulb.zip)

**Comment by raburton** [comment]
That's fantastic thanks, the meaning of these next to each other will be much clearer.

Is there any chance you could do an export to DrawableVector format directly from Illustrator please? I've tried converting them with the usual online tools and one loses the second light ray from the left (only) on the outline version and the other I tried didn't even manage to make the outline one hollow!

**Comment by MrGrigri** [comment]
Do you mean like an SVG? If so, I included that in the zip. Either way, @Templarian will have to add them to the repo if he chooses to add them. He may want them tweaked a bit.

**Comment by raburton** [comment]
No it's an android format introduced at API21 (i.e. with material design) https://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html
All the icons on https://materialdesignicons.com/ can be downloaded in this format. In theory you can convert SVG to it easily enough (this is probably what the site does), but for some reason the online tools I've tied to do this have made errors converting these images. For example http://inloop.github.io/svg2android/ looses one of the light rays.
![missingray](https://cloud.githubusercontent.com/assets/433543/20554274/9e7f4308-b152-11e6-8912-8a8a6659d05e.png)

**Comment by Templarian** [comment]
Yea, I run the icons through an optimization step (ridiculous ugly mess of code that I hope never breaks, because I wrote most of it while drinking). I've added the two new icons below, not the ones above, more in the style of the official lightbulb icons.

[![lightbulb-on](https://materialdesignicons.com/icon/lightbulb-on)](https://materialdesignicons.com/icon/lightbulb-on) [![lightbulb-on-outline](https://materialdesignicons.com/icon/lightbulb-on-outline)](https://materialdesignicons.com/icon/lightbulb-on-outline)

Let me know if this style will work. I think toggling between them should still look pretty nice.

**Comment by Templarian** [comment]
By the way, while I think it's fine to have these also. You could use the outline to represent "on" also. A few apps do that.

**Comment by raburton** [comment]
@Templarian these are great. Thank you both for your effort!
I did originally try the outline and solid for on and off, but I took the solid as on and the outline as off because to me it made more sense that way. You can make an argument for each way around but my natural position was the opposite of yours, hence I thought something less ambiguous would be nice.
