### ISSUE TITLE
Add goyney as Contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1648]
Add @goyney as a contributor account and assign over various icons.

- [x] Add @goyney as a contributor.
- [x] Get details for contributor page on the site (twitter, name, photo).
- [x] Assign all icons to contributor. #1646

@goyney I need a small list of details. website, twitter, name, photo (prefer profile, or github is fine). Short bio.

In the new site this will be all editable by you, but for now until I get that online it's kind of static unfortunately.

**Comment by goyney** [comment]
Name: Michael Irigoyen
Twitter: @mririgo
You can use my GitHub profile photo. I don't have an active website anymore.

Thanks!

**Comment by Templarian** [comment]
https://materialdesignicons.com/contributor/Michael-Irigoyen 😃 

Welcome, hopefully you can stick around. We always need helping thinking of designs for the hundreds of suggestions.

**Comment by goyney** [comment]
Thanks, I will definitely try to help out.

P.S. I noticed I have a double @@ for some reason.

**Comment by Templarian** [comment]
Fixed.
