### ISSUE TITLE
Print Settings

### ISSUE THREAD

**Issue by hghahn** [Templarian/MaterialDesign#1649]
There is a closed thread  - Request #1270 reg. 'printer settings icon' from summer.
The proposal by another contributor was to add a printer icon with the three dots.
I am in need of this icon, however can't find this in the icon repository.
Is it still about to be published?

**Comment by ButchMonkey** [comment]
Hey, I'm the original poster. 
Here is my version of the icon in svg.

[print-settings.zip](https://github.com/Templarian/MaterialDesign/files/604925/print-settings.zip)

**Comment by Templarian** [comment]
That issue shouldn't have been closed. Reopening it and closing this one.
