### ISSUE TITLE
'Advanced' download only generates drawable-mdpi variant

### ISSUE THREAD

**Issue by Jaap-van-Hengstum** [Templarian/MaterialDesign#165]
I would like the advanced download to generate the complete set for all the dpi variants, i.e. drawable-mdpi, drawable-hdpi, drawable-xhdpi, etc. in the correct folders. Is that possible?

Also, the naming of the file is not conforming to the naming of the standard icon package. F.e. the 'account' icon is named 'account.png', should it be named 'ic_account_custom_24dp.png' or something like that?

**Comment by Templarian** [comment]
Good idea. I'll try and fix this up after work tonight.

**Comment by AAverin** [comment]
Is the feature to download full package of icons with a different color available already?
For example if I need some icon in red it would be great to download the whole pack of icons right away instead of doing it 1 by 1 via Advanced

**Comment by Templarian** [comment]
@AAverin When you say the whole pack, do you mean all 1000+ icons? The issue with that is generating all the assets is a bit CPU intensive. With the current traffic load large CPU spikes can cause issues for others accessing the site.

One option I've been looking into is a sort of "repeat" previous download as an option or a multi-select.

**Comment by AAverin** [comment]
No, I mean I want a filter icon, this one, for example.
If I pick 'Download package -> Android 4.x Action Bar' - I get white and grey icons for all screen sizes.
But what I want is red icons for all screen sizes.

To change the color I have to go to 'Advanced', but in Advanced Download button only allows to download single size.

I would like to have an option do download all screen sizes of an icon with a color that I am able to pick.

**Comment by Templarian** [comment]
Oh, yea that is being worked on. I'll try and get it working for the 4.x and 5.x packages.

**Comment by AAverin** [comment]
Cool, would be great to have this feature, thanks.
