### ISSUE TITLE
Pistol

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1651]
I came across this google image (not SVG) a couple of weeks before the U.S. Election. I was searching for the differences between the candidates and one of the categories was firearm control. Intuitively enough, I took a screen shot (pun intended) and was able to recreate it in Illustrator. The possible names might be; pistol, firearm, or crime. 

![pistol 4x](https://cloud.githubusercontent.com/assets/4528551/20580661/efb08794-b190-11e6-890f-d1e15ea7cf4a.png) ![pistol](https://cloud.githubusercontent.com/assets/4528551/20580662/efb0adaa-b190-11e6-9e1f-789c915db4d2.png)

[pistol.zip](https://github.com/Templarian/MaterialDesign/files/610122/pistol.zip)

**Comment by Templarian** [comment]
It's a good icon idea, but I'm wondering if we could make it more "material" styled. Not sure if it will look nice, but simplifying the trigger and the sights/handle.

**Comment by MrGrigri** [comment]
Maybe I didn't make it clear. This was an icon that Google used on their google search page when I was looking up the different candidates stances. It was amongst the other material icons; however, it was a WEBP file and not an SVG. So I took a screen shot and did the best that I could with that.

**Comment by Templarian** [comment]
Makes sense.

[![pistol](https://materialdesignicons.com/icon/pistol)](https://materialdesignicons.com/icon/pistol)
