### ISSUE TITLE
Haxe programming language icon

### ISSUE THREAD

**Issue by FoxelCode** [Templarian/MaterialDesign#1653]
It'd be nice to have an icon based on the logo for the Haxe programming language ([https://haxe.org/](url)).
They have the official coloured logo in .svg format here [https://haxe.org/foundation/branding.html](url).
There's also an outline version there, but I'm not sure if the lines are too thin to fit within the Material guidelines.
![](https://haxe.org/img/branding/haxe-logo-glyph.png)

**Comment by Templarian** [comment]
I'm not sure if this icon will work. In the end we would have to break their guidelines to incorporate it into the 24x24 size. All icons need to be easily recognizable at this size and I don't think this icon would be.
