### ISSUE TITLE
Add alexefremo as Сontributor

### ISSUE THREAD

**Issue by alexefremo** [Templarian/MaterialDesign#1657]
Hi, @Templarian ! As i know i already have 5 icons contributed:

- [x] #1397
- [ ] #1560
- [x] #1509
- [ ] #1464
- [ ] #1506
- [ ] #1473
- [ ] #1429
- [ ] #1416
- [x] #1261
- [ ] https://github.com/Templarian/MaterialDesign/issues/1448

But maybe it's only waiting for contribution.

**Comment by Templarian** [comment]
https://materialdesignicons.com/contributor/Alex-Efremo

Will take some time, but I'll get them all synced to your contributor account.

**Comment by alexefremo** [comment]
https://github.com/Templarian/MaterialDesign/issues/1261

One more contribution
