### ISSUE TITLE
Add firebase icon

### ISSUE THREAD

**Issue by jalasem** [Templarian/MaterialDesign#1658]
It will be of great use to the community if firebase icon is added to the icon library
![firebaselogo](https://cloud.githubusercontent.com/assets/7319749/20659320/3e61a2f0-b543-11e6-9076-c970470dfbd9.png)

**Comment by Templarian** [comment]
Do you know if they have a monochrome icon? Not seeing anything online from searching.

**Comment by thunsaker** [comment]
Looks as if monochrome is just outlines: https://dribbble.com/shots/2923288-Firebase-Console-New-Loading-Animation/attachments/606581

**Comment by MihroyRikkun** [comment]
I created an icon version of the Firebase logo. Based on the YouTube watermark of the Firebase Chanel. 
[firebase_icon.zip](https://github.com/Templarian/MaterialDesign/files/1290986/firebase_icon.zip)

**Comment by PeterShaggyNoble** [comment]
[This GitHub profile](https://github.com/firebase-ops) has a solid monochrome version of the logo and I also found [this outlined version](https://dribbble.com/shots/3041267-Firebase-Logo-Black-White).

**Comment by PeterShaggyNoble** [comment]
Single colour SVGs are available at https://firebase.google.com/brand-guidelines/

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/34994014-258d897e-faca-11e7-89e2-b880943e7102.png)](https://github.com/Templarian/MaterialDesign/files/1635508/firebase.zip)

**Comment by GreenTurtwig** [comment]
An official icon can be found here: https://www.gstatic.com/actions_on_google/console/170719/AOGIcons.woff2

**Comment by CoDEmanX** [comment]
@GreenTurtwig Did you take it from there? If not, can you provide an extracted icon?

**Comment by GreenTurtwig** [comment]
@codemanx The contribution an be was extracted from their logo before we found the AOGIcons files. @petershagynoble should have a page up in the sandbox with all the icons in the set.

**Comment by PeterShaggyNoble** [comment]
On my phone so can't do any optimisation or a zip file but here's the path data resultant in converting the AOG font file to SVG:

    M401 104l-146 -81q-15 -8 -30 0l-144 81l261 263q3 2 7 2q9 0 10 -8zM188 363l-91 -151l38 239q1 8 10 8q6 0 8 -5l43 -79zM278 338l-191 -192l145 246q3 6 9 6t8 -6z

![firebase](https://user-images.githubusercontent.com/15157491/38771426-27e18ad6-401b-11e8-83fb-228071a95e14.png)

**Comment by Templarian** [comment]
[![firebase](https://materialdesignicons.com/icon/firebase)](https://materialdesignicons.com/icon/firebase)
