### ISSUE TITLE
Add thunsaker as Contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1659]
Add @thunsaker as a contributor account and assign over various icons.

- [x] Add @thunsaker as a contributor.
- [x] Get details for contributor page on the site (twitter, name, photo).
- [x] Assign all icons to contributor.

@thunsaker I need a small list of details. website, twitter, name, photo (prefer profile, or github is fine). Short bio.

In the new site this will be all editable by you, but for now until I get that online it's kind of static unfortunately.

- [x] #1313 
- [x] #1314 
- [x] #1315
- [x] #1312 x 2

**Comment by thunsaker** [comment]
**Name**: Thomas Hunsaker
**Twitter**: [@thunsaker](http://twitter.com/thunsaker)
**Site**: http://thomashunsaker.com
**Bio**: Husband, Father, Dev.
**Photo**: GitHub profile

**Comment by Templarian** [comment]
Created https://materialdesignicons.com/contributor/Thomas-Hunsaker

**Comment by thunsaker** [comment]
Sweet, thanks!
