### ISSUE TITLE
woff2 font anchoring all icons to the left v0.9.21-alpha

### ISSUE THREAD

**Issue by MarcosPortugal** [Templarian/MaterialDesign#166]
![image](https://cloud.githubusercontent.com/assets/3464445/6360067/39c580e6-bc6f-11e4-9e41-2d7faea37cf7.png)

**Comment by Templarian** [comment]
Starting with version `v0.9.21-alpha` the CSS was redone to match font-awesome, so they could be more plug and play.

LumX should be centering the icons. Does adding `.mdi { text-align: center; }` fix this?

**Comment by MarcosPortugal** [comment]
Thanks for the quick reply! 

 Text-align: center does not fix it. Here's the css of the <i> tag:

 
![capture](https://cloud.githubusercontent.com/assets/3464445/6360213/4b5d4a90-bc70-11e4-92ac-696d6f98340e.JPG)

 And the <i> parent's css:

 
![capture](https://cloud.githubusercontent.com/assets/3464445/6360235/704c18c2-bc70-11e4-8a3a-055cc7b49344.JPG)

**Comment by chrislitherland95** [comment]
All icons on this site are centred. It looks like the icon space on your app is not symmetrical and therefore the icon will be displayed to the left according to text. I would suggest removing the label under the icon as this is unnecessary and contrary to material design, the icons should represent themselves. You might also find that the text is expanding the box and leaving the icon behind, as it were. Try removing the label (add this text as a long press hint), the box area for action icons should strictly be 24dp with 12dp padding on all sides. The app bar should centre this vertically and should be 52dp high.
Please refer to the "system icons" section of the specification for more information. 
http://www.google.com/design/spec/style/icons.html

**Comment by chrislitherland95** [comment]
Sorry. I misread your question.

**Comment by MarcosPortugal** [comment]
Yep, they are fine on the site, but they're not using the icons as a font. And well the label isn't really pertinent to the current case, is it? :smile:

**Comment by Templarian** [comment]
I figured it out, it's a bug in the woff2 export I think. This could be annoying to fix. I'll look at it after the bar tonight.

For now use a previous version.

**Comment by MarcosPortugal** [comment]
How previous? As in, which version broke it? And thanks!

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Webfont/tree/v0.8.82-alpha

**Comment by Templarian** [comment]
You lose woff2 support until I get it fixed.

**Comment by MarcosPortugal** [comment]
Thank you very much :smiley:

**Comment by Templarian** [comment]
I pushed a temporary fix with a woff2 file that works. `v0.9.22-alpha`. I have to figure out what is going on with the grunt-webfont package still.

**Comment by Templarian** [comment]
I'm going to close this issue since it is resolved. Debugging the font build issue tonight for future package deploys.

**Comment by MarcosPortugal** [comment]
Thank you for your work :)
