### ISSUE TITLE
Source Commit Icons

### ISSUE THREAD

**Issue by casesandberg** [Templarian/MaterialDesign#1661]
Commit Icons:
* source-commit
* source-commit-start
* source-commit-end
* source-commit-next-local
* source-commit-local
* source-commit-end-local
* source-commit-start-next-local

![image](https://cloud.githubusercontent.com/assets/4633636/20740930/d6748d4e-b67b-11e6-844c-8775dbf65df8.png)

[source-commit-icons.zip](https://github.com/Templarian/MaterialDesign/files/621063/source-commit-icons.zip)

**Comment by casesandberg** [comment]
source-commit fulfils one of the icons in https://github.com/Templarian/MaterialDesign/issues/1059

**Comment by Templarian** [comment]
[![source-commit](https://materialdesignicons.com/icon/source-commit)](https://materialdesignicons.com/icon/source-commit) [![source-commit-start](https://materialdesignicons.com/icon/source-commit-start)](https://materialdesignicons.com/icon/source-commit-start) [![source-commit-end](https://materialdesignicons.com/icon/source-commit-end)](https://materialdesignicons.com/icon/source-commit-end) [![source-commit-next-local](https://materialdesignicons.com/icon/source-commit-next-local)](https://materialdesignicons.com/icon/source-commit-next-local) [![source-commit-local](https://materialdesignicons.com/icon/source-commit-local)](https://materialdesignicons.com/icon/source-commit-local) [![source-commit-end-local](https://materialdesignicons.com/icon/source-commit-end-local)](https://materialdesignicons.com/icon/source-commit-end-local) [![source-commit-start-next-local](https://materialdesignicons.com/icon/source-commit-start-next-local)](https://materialdesignicons.com/icon/source-commit-start-next-local)
