### ISSUE TITLE
Add Case as a Contributor

### ISSUE THREAD

**Issue by casesandberg** [Templarian/MaterialDesign#1662]
![image](https://cloud.githubusercontent.com/assets/4633636/20748572/8cec76e6-b6a3-11e6-9b36-d8f33d3d9df3.png)

- [x] https://github.com/Templarian/MaterialDesign/issues/1557
- [ ] https://github.com/Templarian/MaterialDesign/issues/1448
- [ ] https://github.com/Templarian/MaterialDesign/issues/1348
- [ ] https://github.com/Templarian/MaterialDesign/issues/1697
- [x] https://github.com/Templarian/MaterialDesign/issues/1661
- [x] https://github.com/Templarian/MaterialDesign/issues/1664
- [x] https://github.com/Templarian/MaterialDesign/issues/1665
- [x] https://github.com/Templarian/MaterialDesign/issues/1668
- [x] https://github.com/Templarian/MaterialDesign/issues/1669

~~https://github.com/Templarian/MaterialDesign/issues/1527~~
~~https://github.com/Templarian/MaterialDesign/issues/1666~~
~~https://github.com/Templarian/MaterialDesign/issues/1667~~

**Comment by Templarian** [comment]
@casesandberg I'll put it here, because I noticed attached are all .sketch. I need .svg for icon submissions. Thanks!

**Comment by Templarian** [comment]
Reopening this issue. Still processing some of these. Also needs the SVG for the keyboard ones.

**Comment by casesandberg** [comment]
[keyboard-keys.zip](https://github.com/Templarian/MaterialDesign/files/647887/keyboard-keys.zip)

**Comment by casesandberg** [comment]
Any luck getting these added?
