### ISSUE TITLE
Alias People/Person icons

### ISSUE THREAD

**Issue by PaulWoitaschek** [Templarian/MaterialDesign#1663]
I faced a few times that names do not match the material desing page so I did not find some icons.

For example
https://material.io/icons/#ic_person and https://material.io/icons/#ic_people
are named
https://materialdesignicons.com/icon/account and https://materialdesignicons.com/icon/account-multiple

It would be great if the tags were updated so the search works

- [x] Alias `person` -> `account`
- [x] Alias `people` -> `account-multiple`

**Comment by Templarian** [comment]
MDI existed before the official icon pack by a few months (not many know this). We have a feature for this called Aliases that can solve this issue.

At the start of the project I went with more a noun consistency following a Font Awesome naming scheme. It makes more sense as the icon pack reaches as I predicted thousands of icons.

**Comment by Templarian** [comment]
Both these were aliases were added. If someone made me a list of all the aliases I could update them, but that might be a daunting task. I generally look through the top 500 searches every so often and verify icons exist for them or aliases.

**Comment by PeterShaggyNoble** [comment]
@Templarian, I've done [a *little* bit of work on aliasing](https://houseofdesign.ie/sandbox/mdi/), which I can send over if you let me know how you'd like it supplied. (Or you can just view the source, all the icons are at the end of the file).

**Comment by Templarian** [comment]
@PeterShaggyNoble If you want you can share it as a google sheet and I can sync them into our system.

Good to see anther project making use of [meta.json](https://cdn.materialdesignicons.com/1.7.22/meta.json) that we release. Hopefully we can find time to start tagging all the icons shortly. Right now tags have not really been heavily used for the newer icons.
