### ISSUE TITLE
cards-variant

### ISSUE THREAD

**Issue by casesandberg** [Templarian/MaterialDesign#1664]
![image](https://cloud.githubusercontent.com/assets/4633636/20746337/37e650a8-b69a-11e6-8c4d-45adb72a082d.png)

[cards-variant-icon.zip](https://github.com/Templarian/MaterialDesign/files/621361/cards-variant-icon.zip)

**Comment by Templarian** [comment]
[![cards-variant](https://materialdesignicons.com/icon/cards-variant)](https://materialdesignicons.com/icon/cards-variant)
