### ISSUE TITLE
npm logo

### ISSUE THREAD

**Issue by casesandberg** [Templarian/MaterialDesign#1665]
![image](https://cloud.githubusercontent.com/assets/4633636/20746723/ca737bc0-b69b-11e6-9f04-2a04c93f1111.png)

* npm
* npm-outline

[npm-icons.zip](https://github.com/Templarian/MaterialDesign/files/621389/npm-icons.zip)

**Comment by Templarian** [comment]
@casesandberg Can you attach the SVG file (or illustrator).

**Comment by Templarian** [comment]
[![npm](https://materialdesignicons.com/icon/npm)](https://materialdesignicons.com/icon/npm)
