### ISSUE TITLE
bitcoin

### ISSUE THREAD

**Issue by casesandberg** [Templarian/MaterialDesign#1667]
![image](https://cloud.githubusercontent.com/assets/4633636/20748049/831ad2b8-b6a1-11e6-83ef-700bab38db2c.png)

[bitcoin-icon.zip](https://github.com/Templarian/MaterialDesign/files/621489/bitcoin-icon.zip)

**Comment by GreenTurtwig** [comment]
I assume this would be like the `coin` icon, but with the Bitcoin logo not slanted. Since there is already a Bitcoin icon (`currency-btc`). :cat2:

**Comment by casesandberg** [comment]
Oh bizzare. Is there any way to tag the `currency-btc` icon with bitcoin? If you search for bitcoin nothing comes up. 

I will revise this with the more detailed B 

![image](https://cloud.githubusercontent.com/assets/4633636/20765003/79a078de-b6e5-11e6-8faf-3d9414e33817.png)

**Comment by Templarian** [comment]
We can add an Alias for bitcoin. The bitcoin currency symbol is not slanted, it is like most currency symbols.

We can't add circle icons for every currency (especially in these more niche icons).

**Comment by casesandberg** [comment]
Ok yeah, that makes sense

**Comment by Templarian** [comment]
Added.
