### ISSUE TITLE
heart-half

### ISSUE THREAD

**Issue by casesandberg** [Templarian/MaterialDesign#1668]
![image](https://cloud.githubusercontent.com/assets/4633636/20748216/271a4d8a-b6a2-11e6-86b0-ebc8f36f8f48.png)

[heart-half-icon.zip](https://github.com/Templarian/MaterialDesign/files/621496/heart-half-icon.zip)

**Comment by JamesCoyle** [comment]
Could be useful for voting systems or even game health indicators.

**Comment by MrGrigri** [comment]
Either bring the inside outline on the heart to a point or bring the vertical separator slightly to the right to join the inside outline's right corner. As of right now, it looks weird in the middle. 

Thoughts?

**Comment by Templarian** [comment]
[![heart-half-outline](https://materialdesignicons.com/icon/heart-half-outline)](https://materialdesignicons.com/icon/heart-half-outline) [![heart-half-part](https://materialdesignicons.com/icon/heart-half-part)](https://materialdesignicons.com/icon/heart-half-part) [![heart-half-part-outline](https://materialdesignicons.com/icon/heart-half-part-outline)](https://materialdesignicons.com/icon/heart-half-part-outline)

@MrGrigri Agreed. Modified above.
