### ISSUE TITLE
coffee-outline + variant

### ISSUE THREAD

**Issue by casesandberg** [Templarian/MaterialDesign#1669]
![image](https://cloud.githubusercontent.com/assets/4633636/20748530/616cc020-b6a3-11e6-9d40-0464000e3424.png)

* coffee-outline
* coffee-variant-outline

[coffee-outline-icons.zip](https://github.com/Templarian/MaterialDesign/files/621514/coffee-outline-icons.zip)

**Comment by Templarian** [comment]
[![coffee-outline](https://materialdesignicons.com/icon/coffee-outline)](https://materialdesignicons.com/icon/coffee-outline)

Not adding the variant. Just too subtle of the difference.
