### ISSUE TITLE
format-page-break

### ISSUE THREAD

**Issue by robalves-tpro** [Templarian/MaterialDesign#1670]
Hey guys, I need a pagebreak icon, I just created this in svg. It's possible to add on the repository?

![screen shot 2016-11-30 at 11 21 47](https://cloud.githubusercontent.com/assets/23474218/20750512/31484378-b6ef-11e6-9ae7-6f991fd0f6f9.png)

[page_break.svg.zip](https://github.com/Templarian/MaterialDesign/files/621636/page_break.svg.zip)

**Comment by Templarian** [comment]
![page-break](https://cloud.githubusercontent.com/assets/338885/20765606/a208aedc-b6f8-11e6-9d43-01ead473e1a8.png) ![page-break](https://cloud.githubusercontent.com/assets/338885/20765614/acc63bdc-b6f8-11e6-9089-18abb3deac92.png)

![page-break](https://cloud.githubusercontent.com/assets/338885/20765662/f1e768b2-b6f8-11e6-84c1-17897de45bf6.png) ![page-break](https://cloud.githubusercontent.com/assets/338885/20765657/e69b818c-b6f8-11e6-9a99-5fabd810b814.png) 

Two more ideas on this icon design. More Material Design styled.

**Comment by JamesCoyle** [comment]
There is also the one Google uses in Docs.
![image](https://cloud.githubusercontent.com/assets/10384436/20765815/db06323a-b72b-11e6-8264-7f4142fd34b4.png)

**Comment by Templarian** [comment]
Oh yea, was slowly getting to that. Yea, I like Google's design the most.

**Comment by Templarian** [comment]
[![format-page-break](https://materialdesignicons.com/icon/format-page-break)](https://materialdesignicons.com/icon/format-page-break)
