### ISSUE TITLE
wind-turbine

### ISSUE THREAD

**Issue by DubeauJL** [Templarian/MaterialDesign#1672]
Renewable Energy Icon such as:

 - Solar Panel
 - Wind Turbine

As Example:

_Without the yellow circle_
![](http://icons.iconarchive.com/icons/graphicloads/100-flat-2/256/wind-turbine-clean-renewable-energy-icon.png)

![](http://previews.123rf.com/images/rastudio/rastudio1504/rastudio150401085/38969981-Solar-Panel-icon-thin-line-for-web-and-mobile-modern-minimalistic-flat-design-Vector-dark-grey-icon--Stock-Vector.jpg)

**Comment by OctoberJemini** [comment]
Icon for the solar panel

![solar-panel24](https://user-images.githubusercontent.com/20706106/30608314-ec41d7a6-9d45-11e7-83da-353c61d7d15d.png)
![solar-panel32](https://user-images.githubusercontent.com/20706106/30608317-edacd1fe-9d45-11e7-8ee3-31fd0288fac3.png)
![solar-panel48](https://user-images.githubusercontent.com/20706106/30608359-0f1922ac-9d46-11e7-9aae-9aed68da8687.png)

[solar-panel.zip](https://github.com/Templarian/MaterialDesign/files/1315392/solar-panel.zip)

**Comment by kmohl** [comment]
Wind turbine icon.
![wind-turbine-outline](https://user-images.githubusercontent.com/24955518/31850075-e36d92a8-b64c-11e7-9c93-1af1775f1c89.png)
[wind-turbine-outline.zip](https://github.com/Templarian/MaterialDesign/files/1403932/wind-turbine-outline.zip)

**Comment by kmohl** [comment]
Solar panel icon.
![solar-panel-outline](https://user-images.githubusercontent.com/24955518/31850094-2adfe37a-b64d-11e7-84c7-01c07d772ce2.png)
[solar-panel-outline.zip](https://github.com/Templarian/MaterialDesign/files/1403933/solar-panel-outline.zip)

**Comment by kmohl** [comment]
Wind turbine icon.
![wind-turbine](https://user-images.githubusercontent.com/24955518/32165359-c88fad96-bd62-11e7-8c1e-7b7348434714.png)
[wind-turbine.zip](https://github.com/Templarian/MaterialDesign/files/1426746/wind-turbine.zip)

**Comment by kmohl** [comment]
Solar panel icon.
![solar-panel](https://user-images.githubusercontent.com/24955518/32166408-06b1640e-bd66-11e7-8e28-4c2ea546e8a0.png)
[solar-panel.zip](https://github.com/Templarian/MaterialDesign/files/1426823/solar-panel.zip)

**Comment by kmohl** [comment]
Solar panel v2.
![solar-panel-2](https://user-images.githubusercontent.com/24955518/32166565-8d1a1964-bd66-11e7-8436-cb617d3a2b96.png)
[solar-panel-2.zip](https://github.com/Templarian/MaterialDesign/files/1426835/solar-panel-2.zip)

**Comment by hvbhome** [comment]
maybe just have the mdi:home icon have an extra line on the roof, visualizing a side view of the panels? a bit like home-modern

**Comment by GreenTurtwig** [comment]
Google now has an icon for a wind turbine:
![image](https://user-images.githubusercontent.com/15905797/44350257-c27fb880-a496-11e8-81c9-1439ea46037b.png)

**Comment by goyney** [comment]
Going to repurpose this issue for `wind-turbine`. Please create a new issue for `solar-panel` if you still need it.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48991797-96617c80-f102-11e8-8adc-1a571b9bc947.png)
[wind-turbine.svg.zip](https://github.com/Templarian/MaterialDesign/files/2613980/wind-turbine.svg.zip)

**Comment by Templarian** [comment]
Added all 3 icons. `solar-panel`, `solar-panel-large`, and `wind-turbine`.

@kmohl Let me know when you have 5 icons and I'll assign these over to a contributor account. 😃

**Comment by PeterShaggyNoble** [comment]
@Templarian, looks like you missed `wind-turbine`.
