### ISSUE TITLE
timeline icon

### ISSUE THREAD

**Issue by joaosardinha** [Templarian/MaterialDesign#1673]
![](https://d30y9cdsu7xlg0.cloudfront.net/png/82341-200.png)

**Comment by JamesCoyle** [comment]
[![history](https://materialdesignicons.com/icon/history)](https://materialdesignicons.com/icon/history)

**Comment by Templarian** [comment]
@JamesCoyle Not sure I follow, where would they move. I think the position of the hands look fine (considering the size limitation).

**Comment by JamesCoyle** [comment]
The vertical hand isn't centered in the circle at all. Could do to be shifted to the right half a square or so.
