### ISSUE TITLE
Movements icon

### ISSUE THREAD

**Issue by Kolorbon** [Templarian/MaterialDesign#1674]
Icon that describes movements. Like in: A dance has X movements.

The cursor icons are the closest I found here, but they are too IT specific.

**Comment by cyber199** [comment]
Would, for example, a pair of shoe prints with circular arrows around them work, or is that too dance specific?

**Comment by MrGrigri** [comment]
Would `run` or `run-fast` work?

![run](https://materialdesignicons.com/icon/run) ![run-fast](https://materialdesignicons.com/icon/run-fast)

**Comment by Kolorbon** [comment]
@cyber199 it's too specific

@MrGrigri yes, thanks. I just can't imagine what else could fit.

In my case I need it to show the count of movements of a form (hyeong) in Taekwondo.

**Comment by PeterShaggyNoble** [comment]
Would the [`numeric-*` icons](http://mdi.houseofdesign.ie/?search=numeric) suit your needs?

**Comment by Kolorbon** [comment]
No, since the icon should tell that the numbers are the movements of the form. If there's no other way to display this, then I think that the `run` icon fits enough.

**Comment by PeterShaggyNoble** [comment]
You might get use out of `karate`, so.

[![](https://materialdesignicons.com/icon/karate)](https://materialdesignicons.com/icon/karate)

**Comment by Kolorbon** [comment]
Oh, yes, that could fit, thanks.

**Comment by PeterShaggyNoble** [comment]
If you can find the original issue (I'm on my phone, can't search), you can see the discussion that was had on the naming. An alias or two is to be added, I believe

**Comment by PeterShaggyNoble** [comment]
The alias `martial-arts` has been added to the `karate` icon.

@Kolorbon, can you confirm that the suggested icons fulfill your needs so we can close this issue out?

**Comment by Kolorbon** [comment]
@PeterShaggyNoble, yes, they do - can be closed.
