### ISSUE TITLE
Roomba Icon

### ISSUE THREAD

**Issue by xstrex** [Templarian/MaterialDesign#1677]
A roomba vacuum cleaner icon.

Similar to one of these: https://thumb9.shutterstock.com/display_pic_with_logo/256636/324946892/stock-vector-robotic-vacuum-cleaner-324946892.jpg

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/20866264/2527744e-ba21-11e6-8a0e-8ce1810e39c0.png)

I don't think the guidelines favour a 3D view

**Comment by RobertoGraham** [comment]
[roomba.zip](https://github.com/Templarian/MaterialDesign/files/629801/roomba.zip)

**Comment by xstrex** [comment]
That looks great, thank you!

**Comment by Templarian** [comment]
[![roomba](https://materialdesignicons.com/icon/roomba)](https://materialdesignicons.com/icon/roomba)

A nice addition for home automation icons. @RobertoGraham create an issue when you have 5 icons and I'll create you an account and assign these over.
