### ISSUE TITLE
Fire Variant

### ISSUE THREAD

**Issue by RobertoGraham** [Templarian/MaterialDesign#1678]
Could you add YouTube's "Hot" icon as a fire variant?

![image](https://cloud.githubusercontent.com/assets/14958777/20863211/59dd5606-b9bb-11e6-8885-dc67bd67c4c7.png)

**Comment by Templarian** [comment]
I think if we add this it should replace the original instead of being a variant. I like this design more than the current stock icon they call `whatshot`.

**Comment by JamesCoyle** [comment]
I'd agree with that. Not much point in having two icons that are so similar. 

I really wish Google would follow their own guidelines... The position of the cast icon is awful.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/30714723-d2b8ff90-9f0b-11e7-9456-68048522427f.png)
![image](https://user-images.githubusercontent.com/15905797/30714732-d9b8c6a4-9f0b-11e7-9041-dcf3e040abcf.png)
[fire.zip](https://github.com/Templarian/MaterialDesign/files/1322497/fire.zip)

From the YouTube desktop update.

**Comment by PeterShaggyNoble** [comment]
This has also since been added to Google's Material Icons Extended set:

[![youtube-trending](http://mdi.houseofdesign.ie/tools/preview/?icon=youtube-trending&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/)

**Comment by Templarian** [comment]
Replaced `fire` with this as it's generally a nicer icon.
