### ISSUE TITLE
Sign-direction

### ISSUE THREAD

**Issue by Rehanul** [Templarian/MaterialDesign#1679]
https://image.freepik.com/free-icon/address-signal_318-10768.jpg

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/20866635/66c87968-ba29-11e6-82e3-bc58cda16eed.png)

![image](https://cloud.githubusercontent.com/assets/14958777/20866642/9f41e00e-ba29-11e6-9da5-b69a3570c9c8.png)

**Comment by RobertoGraham** [comment]
[address-signal.zip](https://github.com/Templarian/MaterialDesign/files/629800/address-signal.zip)

**Comment by PeterShaggyNoble** [comment]
Would [mdi-routes](https://materialdesignicons.com/icon/routes) not cover this?

**Comment by CoDEmanX** [comment]
I posted some over here: https://github.com/Templarian/MaterialDesign/issues/528

**Comment by JamesCoyle** [comment]
Can we add this and alias it and the routes icon with sign and direction?

**Comment by Templarian** [comment]
[![sign-text](https://materialdesignicons.com/icon/sign-text)](https://materialdesignicons.com/icon/sign-text) [![sign-direction](https://materialdesignicons.com/icon/sign-direction)](https://materialdesignicons.com/icon/sign-direction)

**Comment by Templarian** [comment]
There is a alias also `sign-routes` for `routes`.
