### ISSUE TITLE
Bomb defused

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1680]
A defused or off variant would be useful.
[![bomb](https://materialdesignicons.com/icon/bomb)](https://materialdesignicons.com/icon/bomb)

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/20895903/54560418-bb13-11e6-9a79-00d3fd67d01b.png)
[bomb-off.zip](https://github.com/Templarian/MaterialDesign/files/631891/bomb-off.zip)

**Comment by Templarian** [comment]
@RobertoGraham To keep proportional the slash needs to extend further down on the right. Assuming your using one of the provided templates, extends the bottom right down further before combining the slash.

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/20897748/8c362518-bb1b-11e6-8f4b-fde19eda8ba2.png)
[bomb-off.zip](https://github.com/Templarian/MaterialDesign/files/632003/bomb-off.zip)

**Comment by JamesCoyle** [comment]
How about removing the sparks too?

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/20898478/633a4646-bb1e-11e6-84a5-d73c460ba75a.png)
[bomb-off-sparks.zip](https://github.com/Templarian/MaterialDesign/files/632049/bomb-off-sparks.zip)

**Comment by JamesCoyle** [comment]
Thanks! That's perfect for what I need.

**Comment by Templarian** [comment]
[![bomb-off](https://materialdesignicons.com/icon/bomb-off)](https://materialdesignicons.com/icon/bomb-off)
