### ISSUE TITLE
Nought?

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1681]
Would this be of any use? Made it to match the size of the `close` icon.
http://james-coyle.com/games/tic-tac-toe/noughtblack.svg

**Comment by CoDEmanX** [comment]
Looks like it is broken?

**Comment by JamesCoyle** [comment]
Ah yeah. I'll have to sort it. Do the SVGs need to be a single path or can they be different elements?

**Comment by CoDEmanX** [comment]
Single path

**Comment by CoDEmanX** [comment]
@JamesCoyle Looks like the file is gone
