### ISSUE TITLE
dove

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#1682]

**Comment by MrGrigri** [comment]
Will #2749 work?

**Comment by JamesCoyle** [comment]
![image](https://user-images.githubusercontent.com/10384436/62743159-41b82480-ba39-11e9-88a1-e01177cf871f.png)

**Comment by CoDEmanX** [comment]
Looks like it's on a leash xD

**Comment by goyney** [comment]
We've added `bird`. I don't think we're going to get into adding different species of birds. 🤣
