### ISSUE TITLE
Account Multiple Check

### ISSUE THREAD

**Issue by nwalasek** [Templarian/MaterialDesign#1683]
I need a combination of **account-check** and **account-multiple**.

Something similar to **account-multiple-plus** but with a checkmark instead. See this for a rough idea: https://thumb1.shutterstock.com/display_pic_with_logo/1246429/472964518/stock-vector-user-group-icon-management-business-team-leader-sign-social-media-teamwork-concept-check-mark-472964518.jpg

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/20919783/6dd1a0fa-bb95-11e6-9c62-95b9bc12d497.png)
[account-multiple-check.zip](https://github.com/Templarian/MaterialDesign/files/633393/account-multiple-check.zip)

**Comment by CoDEmanX** [comment]
`account-check` has the check mark on the other side, so I guess we should change this accordingly?

**Comment by Templarian** [comment]
Agreed, I'll move to the right when I add it.

**Comment by Templarian** [comment]
[![account-multiple-check](https://materialdesignicons.com/icon/account-multiple-check)](https://materialdesignicons.com/icon/account-multiple-check)
