### ISSUE TITLE
calendar-blank-multiple

### ISSUE THREAD

**Issue by frlinw** [Templarian/MaterialDesign#1684]
![image](https://cloud.githubusercontent.com/assets/11896237/20935868/d3064124-bbe0-11e6-9c26-56df87afc84d.png)

**Comment by MrGrigri** [comment]
@frlinw, do you not want this added?

**Comment by frlinw** [comment]
I did it myself (I create a new font on build time with selected icons from mdi + my own svg)

**Comment by MrGrigri** [comment]
That is an image and not an svg; which is what we need. If you have created the above-mentioned, please include it and we'll keep this issue open until it is added into the repo.

**Comment by JamesCoyle** [comment]
![image](https://user-images.githubusercontent.com/10384436/61280126-41689880-a7af-11e9-8254-d052ef6d25e5.png)

[calendar-blank-multiple.zip](https://github.com/Templarian/MaterialDesign/files/3396162/calendar-blank-multiple.zip)

**Comment by goyney** [comment]
[![calendar-blank-multiple](https://materialdesignicons.com/icon/calendar-blank-multiple)](https://materialdesignicons.com/icon/calendar-blank-multiple)
