### ISSUE TITLE
Digits

### ISSUE THREAD

**Issue by lawloretienne** [Templarian/MaterialDesign#1687]
I would like to see the Digits icon by Twitter, specifically a VectorDrawable.

**Comment by Templarian** [comment]
Do you have an image of what this looks like?

**Comment by lawloretienne** [comment]
![image](https://cloud.githubusercontent.com/assets/311187/21026338/02478b26-bd41-11e6-94f3-e6221c57016e.png)

**Comment by JamesCoyle** [comment]
https://get.digits.com/

**Comment by PeterShaggyNoble** [comment]
Closing this as [Digits is now shut down](https://get.digits.com/blog/digits-is-now-shut-down).
