### ISSUE TITLE
Delivery Truck

### ISSUE THREAD

**Issue by giooliveira** [Templarian/MaterialDesign#1691]
My suggestion for delivery truck 

![delivery-truck](https://cloud.githubusercontent.com/assets/670895/21055578/20e4c2e6-be19-11e6-9063-f243b3bc5b11.png)

SVG file added:
[delivery-truck.zip](https://github.com/Templarian/MaterialDesign/files/642633/delivery-truck.zip)

**Comment by MrGrigri** [comment]
I like it.

**Comment by CoDEmanX** [comment]
![](https://materialdesignicons.com/icon/truck-delivery) ?

**Comment by Templarian** [comment]
[![truck-fast](https://materialdesignicons.com/icon/truck-fast)](https://materialdesignicons.com/icon/truck-fast)

Tweaked to be more pixel perfect.
