### ISSUE TITLE
Missing google's MD icons

### ISSUE THREAD

**Issue by raonicaselli** [Templarian/MaterialDesign#1692]
Hi, there are quite a few icons from the Google icons website missing. 
Is there a way to add them to the font myself?
Missing icons that I need:
- description
- supervisor account
Thanks a lot!

**Comment by soumya92** [comment]
Also missing settings_ethernet

**Comment by CoDEmanX** [comment]
Also see #420

**Comment by PeterShaggyNoble** [comment]
My 👍 is for `supervisor_account`; find myself in need of it on a project I'm on at the moment.

**Comment by Templarian** [comment]
Closing this issue as we track issues individually. We've also added a lot of icons since this issue was created.
