### ISSUE TITLE
The `loop` icon doesn't show up in the stylesheet

### ISSUE THREAD

**Issue by trevorhreed** [Templarian/MaterialDesign#1693]
I found a `loop` icon in the website, but it doesn't show up in the latest stylesheet.

**Comment by Templarian** [comment]
Looks like it was added after the 1.7.22 release.

https://materialdesignicons.com/history

A release should be going out shortly that will sync the new icons.

**Comment by trevorhreed** [comment]
Ah, good to know. I didn't realize images showed up on the website before they were released.

**Comment by JamesCoyle** [comment]
Yeah I think that is an improvement we can make on the new site. Have a section showing icons coming in the next update. 

@Templarian can we not just set up an automatic release system that creates a new version once a day if icons were added?
