### ISSUE TITLE
leak_add, leak_remove (+aliases proximity sensor)

### ISSUE THREAD

**Issue by ambitmaster** [Templarian/MaterialDesign#1694]
![wifisyncing](https://cloud.githubusercontent.com/assets/22747149/21076963/2bb57f94-bf3b-11e6-8711-9a01fd242695.png)

**Comment by ambitmaster** [comment]
It does but just want another image.

Hälsningar
Alexander Mogren

Systemutvecklare mot geografiska informationssytem

Den 21 dec. 2016 5:21 PM skrev "Michael Richins" <notifications@github.com>:

**Comment by MrGrigri** [comment]
Are you wanting that Icon that you supplied at the top to be added?

**Comment by ambitmaster** [comment]
Yes if it's any good

Hälsningar
Alexander Mogren

Systemutvecklare mot geografiska informationssytem

Den 29 dec. 2016 19:40 skrev "Michael Richins" <notifications@github.com>:

**Comment by CoDEmanX** [comment]
There is a stock Google icon similar to this:

https://material.io/icons/#ic_leak_add

**Comment by CoDEmanX** [comment]
Both stock leak icons should be added and aliased, because they work for proximity sensor as well.

From a presentation slide: ![grafik](https://user-images.githubusercontent.com/1309249/39240592-88606ef6-4884-11e8-87e8-92f9f8ea4b42.png)

**Comment by goyney** [comment]
There are probably better names for these:
![image](https://user-images.githubusercontent.com/1015040/48990346-04567580-f0fc-11e8-8ba7-c9f1870db818.png)![image](https://user-images.githubusercontent.com/1015040/48990338-fe609480-f0fb-11e8-81c1-adb47a864be8.png)

[leak.zip](https://github.com/Templarian/MaterialDesign/files/2613901/leak.zip)

**Comment by Templarian** [comment]
Added both of these. 😃

**Comment by CoDEmanX** [comment]
I wonder if the diagonal stroke should be a bit longer...
