### ISSUE TITLE
timeline

### ISSUE THREAD

**Issue by curliq** [Templarian/MaterialDesign#1696]
https://material.io/tools/icons/?icon=timeline&style=baseline

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48991638-b7759d80-f101-11e8-803c-8a423b3e6e8b.png)
[timeline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2613967/timeline.svg.zip)

**Comment by curliq** [comment]
![image](https://user-images.githubusercontent.com/15181917/51431309-fe25d680-1c1e-11e9-88c3-0cb05be0ba8b.png)
This, or vertical, could be one option

**Comment by goyney** [comment]
@Templarian This is a Stock Google Icon, naming doesn't have to line up with what they have.

**Comment by clementmas** [comment]
> https://material.io/tools/icons/?icon=timeline&style=baseline

Is it possible to add this icon? I switched from Google icons to your library but I'm missing this one.

**Comment by Templarian** [comment]
Added. 😃 

[![chart-timeline-variant](https://materialdesignicons.com/icon/chart-timeline-variant)](https://materialdesignicons.com/icon/chart-timeline-variant)
