### ISSUE TITLE
Screenshot

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#1697]
`image-area` + `camera` (`camera` on right lower-right(or left)-hand side)

**Comment by casesandberg** [comment]
I tried adding both of those together and there is just far too much detail to try to fit in one icon. Does something simplified like this work for your needs?

![image](https://cloud.githubusercontent.com/assets/4633636/21192860/03f9f470-c1f8-11e6-8589-c2ff71f10699.png)

**Comment by AravK** [comment]
Yes, please. But if possible, could the `plus` be a `camera`?

**Comment by MrGrigri** [comment]
I believe that replacing the camera with a plus would be too small and unrecognizable. I believe what @casesandberg has done works great.

**Comment by MrGrigri** [comment]
@casesandberg we'll need a zip file with the svg.

**Comment by Templarian** [comment]
What should we name this icon?

`crop` + `select`
`select` + `rectangle`
????

**Comment by MrGrigri** [comment]
Maybe `select-area`.

**Comment by JamesCoyle** [comment]
Could we use the `select` icon as the base and have a plus and minus variant? Would be useful for tools that add to or remove from an existing selection.

**Comment by GreenTurtwig** [comment]
In Android P there's a new screenshot icon in the power menu:
![image](https://user-images.githubusercontent.com/15905797/37148523-aa703e8c-22c2-11e8-8ba8-9e8d22177910.png)

**Comment by PeterShaggyNoble** [comment]
`aspect ratio` would probably complement that for desktops.

[![aspect ratio](https://user-images.githubusercontent.com/15157491/37149375-a0184972-22c5-11e8-93be-3696af1a82ff.png)](https://material.io/icons/#ic_aspect_ratio)

**Comment by GreenTurtwig** [comment]
@PeterShaggyNoble Good point, might be a good idea to create icons for `monitor` and `laptop` too.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/37155146-08ca55a0-22da-11e8-8b5d-31779fa0327e.png)](https://github.com/Templarian/MaterialDesign/files/1793416/cellphone-screenshot.zip)

**Comment by CoDEmanX** [comment]
In Premiere Pro there's an option to export a frame, which uses a camera symbol.
The Windows Snipping tool uses a scissors symbol and some random circle.

Other common symbols:

![image](https://user-images.githubusercontent.com/1309249/37435213-b52d711c-27e2-11e8-8053-3e3cf2a71f53.png)
![image](https://user-images.githubusercontent.com/1309249/37435228-c714a8b4-27e2-11e8-8d5b-ae8d0f156c3e.png)

**Comment by Templarian** [comment]
[![cellphone-screenshot](https://materialdesignicons.com/icon/cellphone-screenshot)](https://materialdesignicons.com/icon/cellphone-screenshot) [![aspect-ratio](https://materialdesignicons.com/icon/aspect-ratio)](https://materialdesignicons.com/icon/aspect-ratio)

[![select-drag](https://materialdesignicons.com/icon/select-drag)](https://materialdesignicons.com/icon/select-drag) [![selection-drag](https://materialdesignicons.com/icon/selection-drag)](https://materialdesignicons.com/icon/selection-drag)
