### ISSUE TITLE
Icon: Java/Coffee

### ISSUE THREAD

**Issue by AravK** [Templarian/MaterialDesign#1699]
`language-java`: `coffee` + hot steam rising out (3 zig-zag lines)

**Comment by MrGrigri** [comment]
Here is my attempt...I believe that there isn't enough room to keep the saucer on the bottom. I have called it `language-java`, but it could have an alias of `coffee-hot`.

![language-java 4x](https://cloud.githubusercontent.com/assets/4528551/21396459/994e4d04-c75d-11e6-9a7b-0b5106fe6f48.png) ![language-java](https://cloud.githubusercontent.com/assets/4528551/21396460/994e3bc0-c75d-11e6-8818-0ef7a282c5d2.png)

[java-language.zip](https://github.com/Templarian/MaterialDesign/files/666815/java-language.zip)

**Comment by AravK** [comment]
It's awesome! Thanks!
