### ISSUE TITLE
Upload official Material Design Icons

### ISSUE THREAD

**Issue by AntoinePlu** [Templarian/MaterialDesign#17]
It could be great if you can upgrade the library with the last released of material design icons.
https://github.com/google/material-design-icons/

**Comment by CoDEmanX** [comment]
The total differs if you compare View the Contributers with [Google profile](https://materialdesignicons.com/contributor/Google), 795 vs. 1174.

Are you looking for help to add more official icons?

**Comment by Templarian** [comment]
This is being tracked in issue #420 now. There is an attached document.
