### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#170]
Icon | Example
------------ | -------------
WordPress | https://s.w.org/about/images/logos/wordpress-logo-notext-rgb.png
Drone / UAV | https://cdn3.iconfinder.com/data/icons/cars-and-delivery/512/quadcopter-512.png
Android Lollipop | In the first screenshots of Android Lollipop, they were taken from ABD or something and had a Lollipop icon in corner
Material Color Palette | Something symbolizing color on a material "stack" (https://lh3.ggpht.com/oeqMOTcEUd5mNfrqV6-AiQnD9nF0vFeQXoYBRXJ1U8p0pNQ1VpVuao34Gmae4g72Gso=w300)
Array (Programming) | Something like: [1,2,3]
String (Programming) | Something like: "s"

- [x] wordpress
- [x] drone
- [ ] android-lollipop
- [x] layers (might already exist)
- [x] code-array
- [x] code-string

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/wordpress
http://materialdesignicons.com/icon/layers (stock)
http://materialdesignicons.com/icon/layers-clear (stock)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/quadcopter
http://materialdesignicons.com/icon/code-array
http://materialdesignicons.com/icon/code-string

I'm not adding the android lollipop icon or the color pallet can be substituted with layer's icon.
