### ISSUE TITLE
please add icon for "feedback"

### ISSUE THREAD

**Issue by vinitthakertrilyo** [Templarian/MaterialDesign#1700]

**Comment by Templarian** [comment]
Do you have an example of what this would look like?

**Comment by vinitthakertrilyo** [comment]
I have few images in my mind for example 
1. user icon followed by an horn to denote that he is speaking something. You will find it in WhatsApp emoji.
2. finger touching the screen

Let me know you thought on it. See if you work something out otherwise I am using "pen" icon for feedback as of now.

**Comment by JamesCoyle** [comment]
Google uses
[![](https://materialdesignicons.com/icon/message-alert)](https://materialdesignicons.com/icon/message-alert)

**Comment by JamesCoyle** [comment]
Google uses
[![](https://materialdesignicons.com/icon/message-alert)](https://materialdesignicons.com/icon/message-alert)

**Comment by vinitthakertrilyo** [comment]
Thanks

**Comment by MrGrigri** [comment]
Google has also just added a new section in their material design that specifically discusses help and feedback. Found [here](https://material.io/guidelines/patterns/help-feedback.html#).

**Comment by vinitthakertrilyo** [comment]
Awesome! Thank you for your time.
