### ISSUE TITLE
Icon: folder-network, folder-documents, 

### ISSUE THREAD

**Issue by AravK** [Templarian/MaterialDesign#1701]
`folder-network`: `folder` with network line (like in `server-network`) underneath
`folder-documents`: `folder` with inverted `document` inside

**Comment by MrGrigri** [comment]
Here is `folder-network`. I'm not quite sure what you mean or what you are attempting to describe with `folder-document`. Could you elaborate, please?

![folder-network 4x](https://cloud.githubusercontent.com/assets/4528551/21394769/2d862020-c757-11e6-90d8-89daa529924b.png) ![folder-network](https://cloud.githubusercontent.com/assets/4528551/21394770/2d8b129c-c757-11e6-99c3-65e90e64ff93.png)

[folder-network.zip](https://github.com/Templarian/MaterialDesign/files/666715/folder-network.zip)

**Comment by AravK** [comment]
Just `folder` with `document` inside it

**Comment by CoDEmanX** [comment]
@MrGrigri I created that icon too xD
https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-191973385

It's probably contained in one of the icon packs I uploaded.

**Comment by Templarian** [comment]
[![folder-network](https://materialdesignicons.com/icon/folder-network)](https://materialdesignicons.com/icon/folder-network)

Please create another issue if the `folder-files` is still needed. Closing out some of these older issues with multiple requests.

**Comment by insign** [comment]
Sorry if I am wrong but, [folder-network](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/folder-network.svg) appears in the site and repo but not at the css and not [here](https://cdn.materialdesignicons.com/2.1.19/) too..

What am I missing?

**Comment by insign** [comment]
#2829
