### ISSUE TITLE
Vector drawable code of this bulb 

### ISSUE THREAD

**Issue by Rehanul** [Templarian/MaterialDesign#1702]
Leave shade of bulb if possible
![clean cut bub](https://cloud.githubusercontent.com/assets/24369630/21104220/b8e1d946-c0ab-11e6-89bd-051313c2d55f.png)

**Comment by Templarian** [comment]
Icons must be in the system style for this project.

http://materialdesignicons.com/icon/lightbulb
http://materialdesignicons.com/icon/lightbulb-outline
