### ISSUE TITLE
rotate-90

### ISSUE THREAD

**Issue by JackDrakkar** [Templarian/MaterialDesign#1705]
Icons can be rotated by 90 degree, but .mdi-rotate-90 also icon (by Goggle)

**Comment by Templarian** [comment]
Good find, surprised no one has reported this yet. On vacation this next week and should have some time to get a release out. Will be fixing it then.

Thanks!

**Comment by Templarian** [comment]
Thinking of renaming this to `format-rotate-90` or something.

**Comment by Templarian** [comment]
Closing this issue. It has been renamed and will be in the `1.8.xx` release.
