### ISSUE TITLE
Icon: eye-outline

### ISSUE THREAD

**Issue by alenz316** [Templarian/MaterialDesign#1707]
A simple eye outline that is less weighty than the current eye icon.

**Comment by Templarian** [comment]
[![eye-outline](https://materialdesignicons.com/icon/eye-outline)](https://materialdesignicons.com/icon/eye-outline) [![eye-outline-off](https://materialdesignicons.com/icon/eye-outline-off)](https://materialdesignicons.com/icon/eye-outline-off)

**Comment by alenz316** [comment]
You are awesome.

**Comment by alenz316** [comment]
@Templarian please add a donate button. I don't want to buy an icon pack, I just want to give you money. ;)

**Comment by Templarian** [comment]
@alenz316 Maybe in the future. Not on the roadmap right now, focus is building out the new site.

**Comment by alenz316** [comment]
@Templarian I understand. Thanks again for all you do!

**Comment by JamesCoyle** [comment]
One issue with donations would be how it would be split once hosting costs and further investments are covered in the event that donations actually exceed that amount. @Templarian is putting in a huge amount of time, effort, and resources into keeping the project going but there are also contributors that have put in a huge amount of time submitting new icons and moderating the issues section such as @CoDEmanX with around 200 icons submitted.

**Comment by Templarian** [comment]
@JamesCoyle One of the main reasons I don't have donations. Eventually (or never) we may figure out a way to handle this. New website first then we'll spend time to figure out a way to handle this.

**Comment by JamesCoyle** [comment]
Would probably have to be a system based on number of icons submitted perhaps with sliders so people can adjust who gets what.

**Comment by Templarian** [comment]
@JamesCoyle https://github.com/Templarian/MaterialDesign-Site/issues/15
