### ISSUE TITLE
GoodReads Icon

### ISSUE THREAD

**Issue by CeJienAJPC** [Templarian/MaterialDesign#1708]
Thanks for the Awesome icons everyone. Would love to have an SVG for **GoodReads**

**Comment by Templarian** [comment]
Their logo is a G? This might be too specific as a 'social media' icon that we allow. In these scenarios it is probably best to use an inline vector asset. Trying to keep the brand related icons to larger social media type icons.

**Comment by PeterShaggyNoble** [comment]
After reconsideration, this has been added.
