### ISSUE TITLE
center dot

### ISSUE THREAD

**Issue by eddieberklee** [Templarian/MaterialDesign#1709]
I come from a web background (now android) and I used to use the "center dot" a lot. I would edit the icons on my own but I don't have too much experience with SVGs. Would be nice to have one of the existing circles just made wayy smaller and centered.

Love this project you guys!

**Comment by Templarian** [comment]
I'm not 100% sure what you mean with the description? You mean a 4x4 dot in the center...

https://materialdesignicons.com/icon/dots-horizontal (but just the center one)? Or something else.

**Comment by eddieberklee** [comment]
More like just the  checkbox-blank-circle

But made really small and in the center. It's like this character: ·

**Comment by JamesCoyle** [comment]
I think just the center dot of `dots-horizontal` would be best for consistency.

**Comment by eddieberklee** [comment]
Ah, that's a good idea!

🙋

**Comment by MrGrigri** [comment]
Here is a 4X4 dot in the center. I have called it dot-single...but that's up for debate. 

![dot-single 4x](https://cloud.githubusercontent.com/assets/4528551/21394185/d90ce8d2-c754-11e6-8b33-9d582c8e4f97.png) ![dot-single](https://cloud.githubusercontent.com/assets/4528551/21394186/d912667c-c754-11e6-8e81-95f9011a12c1.png)

[dot-single.zip](https://github.com/Templarian/MaterialDesign/files/666672/dot-single.zip)

**Comment by eddieberklee** [comment]
Looking forward to seeing it on the website! (as I only use the
vectordrawable format for android)

**Comment by CoDEmanX** [comment]
There was something else in there. Here's a cleaner SVG:

![image](https://user-images.githubusercontent.com/1309249/38770482-08262258-4014-11e8-9902-438634109a17.png)

[dot-single.zip](https://github.com/Templarian/MaterialDesign/files/1910620/dot-single.zip)

Noteworthy: It only has 3 path points!

**Comment by Templarian** [comment]
This was added along with some other sizes.
