### ISSUE TITLE
Apple Icons?

### ISSUE THREAD

**Issue by TomasRekstad** [Templarian/MaterialDesign#171]
Can you please make some Apple icons? Like a Finder icon, Safari browser icon, quicktime icon and terminal icon? I use the icons in my dock, and your icons are the best! It would be much appreciated if you could!
![image](https://cloud.githubusercontent.com/assets/2771248/6374626/5904fde4-bd12-11e4-9ad3-976663613279.png)
![image](https://cloud.githubusercontent.com/assets/2771248/6374633/6653cb24-bd12-11e4-9e79-7e4359673297.png)
![image](https://cloud.githubusercontent.com/assets/2771248/6374659/92c8e8f6-bd12-11e4-8244-8763301b342e.png)
![image](https://cloud.githubusercontent.com/assets/2771248/6374666/a06dad52-bd12-11e4-96fd-6f46210d99d6.png)

- [ ] finder
- [ ] safari
- [ ] quicktime

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/console (exists, needs alias terminal added).
The others will need to be added.

Actually can I get a screenshot of your dock, just curious what that looks like.

**Comment by TomasRekstad** [comment]
Yes you can. But since my dock is in "early stages", I'm going to change some things in the future. e.g. colors :)

![screen](https://cloud.githubusercontent.com/assets/2771248/6375709/1e44dc4a-bd19-11e4-9e01-96f16041cce6.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/apple-finder
http://materialdesignicons.com/icon/quicktime
http://materialdesignicons.com/icon/apple-safari
