### ISSUE TITLE
Icon for a form 

### ISSUE THREAD

**Issue by janindu2r** [Templarian/MaterialDesign#1710]

**Comment by MrGrigri** [comment]
Does neither `file-document` or `file-document-box` work?

![file-document](https://materialdesignicons.com/icon/file-document) ![file-document-box](https://materialdesignicons.com/icon/file-document-box)

**Comment by PeterShaggyNoble** [comment]
[`textbox`](https://materialdesignicons.com/icon/textbox) could also work.

**Comment by Templarian** [comment]
I'm going to close this issue out. Feel free to reopen it if other ideas come up.
