### ISSUE TITLE
Icon request: Ice / Cold / Snowflake

### ISSUE THREAD

**Issue by Genestealer** [Templarian/MaterialDesign#1711]
Icon request: Ice / Cold / Snowflake
E.G. http://www.flaticon.com/free-icon/snowflake_63341
http://image.flaticon.com/icons/svg/63/63341.svg

![snowflake](https://cloud.githubusercontent.com/assets/5207490/21410493/0a481582-c7d9-11e6-8a77-2b72ab89fd17.png)

**Comment by MrGrigri** [comment]
How about this one?

![snowflake 4x](https://cloud.githubusercontent.com/assets/4528551/21409667/afd6df88-c798-11e6-9171-4235a4d34684.png) ![snowflake](https://cloud.githubusercontent.com/assets/4528551/21409666/afd3f354-c798-11e6-875f-d8d21a7c5b58.png)

[snowflake.zip](https://github.com/Templarian/MaterialDesign/files/667598/snowflake.zip)

**Comment by Genestealer** [comment]
That's nice, however convention is for 6 pointed snowflakes, would that be possible?

**Comment by MrGrigri** [comment]
With only a 24x24 pixel canvas at 1x, there really isn't room for 6 points.

**Comment by Genestealer** [comment]
![snowflake 1](https://cloud.githubusercontent.com/assets/5207490/21450551/1e1c98f4-c8f0-11e6-88ee-b56d12989251.png)
24x24, looks ok?

**Comment by JamesCoyle** [comment]
I think that works well. Not too detailed but easily recognisable.

**Comment by Genestealer** [comment]
Agreed, that's very good.

**Comment by Templarian** [comment]
[![snowflake](https://materialdesignicons.com/icon/snowflake)](https://materialdesignicons.com/icon/snowflake)
