### ISSUE TITLE
More light icons

### ISSUE THREAD

**Issue by jbcodemonkey** [Templarian/MaterialDesign#1712]
- [x] Hanging light `ceiling-light`
- [x] Chandelier
- [x] Under-cabinet light
- [ ] Landscape light
- [ ] Ceiling flood light `ceiling-light` ?
- [x] Wall sconce
- [ ] Lamp post
- [ ] Desk lamp

More table lamp options

**Comment by GreenTurtwig** [comment]
Ceiling Light:
![](https://puu.sh/tsYQO.png) ![](https://puu.sh/tsYTw.png)
Not exactly the best in my opinion, but it's more in like with what my lamp icon looked like.

**Comment by GreenTurtwig** [comment]
I do feel like some of these are quite specific, I'm guessing you wanted them for a home automation setup (Home Assistant?). I also reckon a lamp post would be quite hard to do, since they're so tall. A "close up" of the top of a gas lamp post could work, but that's a stretch, since most there's so many variations and they aren't that common.
![](http://www.finesgas.com/images/legendary-lighting-atlas-II-post.jpg)

**Comment by jbcodemonkey** [comment]
LOVE the ceiling light.

You are correct: looking to use these with HomeAssistant.

The post lamp is a good choice, would capture the vast majority of them.

**Comment by GreenTurtwig** [comment]
Great that you like it. :heart: 
You'll have to wait for @Templarian to add it.

I'll continue with trying out the different styles. :-)

**Comment by Templarian** [comment]
[![ceiling-light](https://materialdesignicons.com/icon/ceiling-light)](https://materialdesignicons.com/icon/ceiling-light)

**Comment by Templarian** [comment]
Oops, didn't mean to close it, just added the ceiling light.

**Comment by jbcodemonkey** [comment]
Thanks for adding that, looks really nice.

**Comment by jbcodemonkey** [comment]
mdi:ceiling-light works in Home Assistant 0.40.0, and it look awesome:

![image](https://cloud.githubusercontent.com/assets/4581542/23913786/671a4d1c-08ba-11e7-8310-98267cce7178.png)

**Comment by jbcodemonkey** [comment]
Here are possibilities for undercabinet lights and chandelier.

![image](https://cloud.githubusercontent.com/assets/4581542/23915105/7817ae9e-08be-11e7-9c58-04e61f53bcaf.png)

![image](https://cloud.githubusercontent.com/assets/4581542/23915141/8fbed914-08be-11e7-9b11-585b5cc176b2.png)


[lights.zip](https://github.com/Templarian/MaterialDesign/files/842234/lights.zip)

**Comment by GreenTurtwig** [comment]
![puush-linux 2017-06-09 at 02 31 16](https://user-images.githubusercontent.com/15905797/26977645-86d3ad88-4d20-11e7-9e78-39833f2aa481.png)
![puush-linux 2017-06-09 at 02 31 23](https://user-images.githubusercontent.com/15905797/26977649-885b007a-4d20-11e7-9bdb-84ae29d0a7e5.png)
![puush-linux 2017-06-09 at 02 31 34](https://user-images.githubusercontent.com/15905797/26977650-89b4fb88-4d20-11e7-96f3-17ad52f3f66c.png)
![puush-linux 2017-06-09 at 02 31 42](https://user-images.githubusercontent.com/15905797/26977654-8b3482a8-4d20-11e7-87cc-083fd5a32255.png)
[lights.zip](https://github.com/Templarian/MaterialDesign/files/1064168/lights.zip)

Working on a few more, thought I'd upload these real quick.

**Comment by jbcodemonkey** [comment]
@GreenTurtwig These are fantastic!

**Comment by GreenTurtwig** [comment]
I've decided I'm going to upload more of the light designs in this issue, better to keep them all in one place:
![puush-linux 2017-06-19 at 07 55 31](https://user-images.githubusercontent.com/15905797/27300950-712f6074-5529-11e7-96a2-a86ab142cc7d.png)
![puush-linux 2017-06-19 at 07 56 10](https://user-images.githubusercontent.com/15905797/27300955-742f59b4-5529-11e7-96a1-40cc125a9e31.png)
[spotlight-home.zip](https://github.com/Templarian/MaterialDesign/files/1086024/spotlight-home.zip)
Really not pleased with this one at all...

**Comment by costr** [comment]
I like the floor lamp. I came here to request that very icon.

**Comment by jbcodemonkey** [comment]
There are just great @GreenTurtwig!!

What about ceiling cans, recessed lighting? Everyone has that nowadays, and it's a tough one to depict.

**Comment by GreenTurtwig** [comment]
Yeah, we have some too.
It's a hard one, I guess the under cabinet icon could be used (or a slimmed down version at least...

**Comment by GreenTurtwig** [comment]
Re-made two of them, look much better now IMO:
![](https://puu.sh/wsvbl.png)
![](https://puu.sh/wsvd1.png)
[light-flat.zip](https://github.com/Templarian/MaterialDesign/files/1098871/light-flat.zip)
Named it `light-flat` so it can be used for multiple different kinds of light, e.g. flush ceiling lights, under-cabinet lights and display cabinet lights.

![](https://puu.sh/wsvhB.png)
![](https://puu.sh/wsvkg.png)
[spotlight-home.zip](https://github.com/Templarian/MaterialDesign/files/1098878/spotlight-home.zip)
I did say I wasn't pleased with this one before, well now I am. :smile_cat: 
Don't think this is a good name for it however.

And before I forget, just thought I should link in https://github.com/Templarian/MaterialDesign/issues/2044 as it's another type of light, good to keep track of stuff here.

**Comment by GreenTurtwig** [comment]
![](https://puu.sh/wBs2p.png)
![](https://puu.sh/wBs3u.png)
[wall-scone.zip](https://github.com/Templarian/MaterialDesign/files/1122483/wall-scone.zip)

![](https://puu.sh/wBs4s.png)
![](https://puu.sh/wBs4U.png)
[wall-scone-variant.zip](https://github.com/Templarian/MaterialDesign/files/1122488/wall-scone-variant.zip)

I don't like the variant, but it's really the only way to show a semicircle shaped light.

**Comment by kevin789900** [comment]
For home automation....

For landscape light, could we have a rotated spotlight beam so light beam faces up?
https://materialdesignicons.com/icon/spotlight-beam

Similar to lamp post, would like coach/carriage light, this is basic idea (they are used outside by doors)....
https://images-na.ssl-images-amazon.com/images/I/71HYTXVNFTL.gif

**Comment by CoDEmanX** [comment]
Sharing a lamp I created a while ago:

![image](https://user-images.githubusercontent.com/1309249/37407910-3c19beee-279b-11e8-8042-f84a606d49b4.png) [lamp.zip](https://github.com/Templarian/MaterialDesign/files/1811480/lamp.zip)

**Comment by jbcodemonkey** [comment]
That is a better lamp than #lamp.

#lamp2?

**Comment by Templarian** [comment]
Forgot to close this earlier. All of five of these have been added. 😸 Lot more lighting options for home automation users.

`spotlight-home` was added as `track-lighting`.

**Comment by chansearrington** [comment]
@Templarian can you add one of the chandeliers icons in this thread?

**Comment by euromem** [comment]
How about can lights? Like Lutron has them identified in the Caseta app. Or something that doesn't look like a ceiling light with a lampshade... I saw somewhere light-variant but cannot find it in Home Assistant.

**Comment by Templarian** [comment]
@euromem Fill out a new icon request. Be sure to include examples. We have a lot of open light icons right now in progress so make to search existing open issues. 👍
