### ISSUE TITLE
Contribution: Font

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#1714]
I don't know if a "change font" icon has been made already, but here's one I made.

![icon-font](https://cloud.githubusercontent.com/assets/8707990/21451289/5b8205d4-c941-11e6-8aa0-2ba1ca7b1cff.png)
![icon-font-x10](https://cloud.githubusercontent.com/assets/8707990/21451290/5d18a7ae-c941-11e6-9549-dbc8dc308ee4.png)
[font.zip](https://github.com/Templarian/MaterialDesign/files/670558/font.zip)

**Comment by Templarian** [comment]
[![format-font](https://materialdesignicons.com/icon/format-font)](https://materialdesignicons.com/icon/format-font)
