### ISSUE TITLE
Contribution: Dog Icon

### ISSUE THREAD

**Issue by faelmorais** [Templarian/MaterialDesign#1715]
I was in need of a dog icon, and since there isn't one available I've made one myself. Here are the files if anyone else needs it.

![dog](https://cloud.githubusercontent.com/assets/8621883/21454756/37a28e20-c902-11e6-8f8c-e0595d1e1085.png)

[Dog Icon.zip](https://github.com/Templarian/MaterialDesign/files/670840/Dog.Icon.zip)

**Comment by Templarian** [comment]
Definitely a nice look, but we may need to modify it a little to keep the lines more material. The tongue is too thin. Need a variation that does not contain this line, so it needs to be modified in someway to keep the idea.

**Comment by JamesCoyle** [comment]
I feel like the head should be circular to match other animal icons. We could really use a more complete set and I feel like they should be consistent as much as possible.

**Comment by MrGrigri** [comment]
I believe we could ditch this one since we have the other.

![dog](https://materialdesignicons.com/icon/dog)
