### ISSUE TITLE
Icon request Windows 10 pin/unpin icons

### ISSUE THREAD

**Issue by meshawn** [Templarian/MaterialDesign#1716]
I've been trying to find decent pin/unpin svg images that look like Windows 10 (pin/unpin shortcuts to the taskbar)

Actually, I have pin.  Just need unpin.

Pin:
M7 0 L7 1 L6 1 L6 8 L7 8 L7 9 L5 9 L5 5 L0 5 L0 4 L5 4 L5 0 L7 0 M15 1 L15 8 L13 8 L13 7 L14 7 L14 2 L13 2 L13 3 L8 3 L8 2 L13 2 L13 1 L15 1 M8 7 L8 8 L7 8 L7 7 L8 7 M13 6 L13 7 L8 7 L8 6 L13 6 M8 1 L8 2 L7 2 L7 1 L8 1 z

Thanks

**Comment by JamesCoyle** [comment]
We already have:
[![](https://materialdesignicons.com/icon/pin)](https://materialdesignicons.com/icon/pin)[![](https://materialdesignicons.com/icon/pin-off)](https://materialdesignicons.com/icon/pin-off)

**Comment by meshawn** [comment]
If you have, I can't find it.  -Thanks

**Comment by CoDEmanX** [comment]
Just search for pin on https://materialdesignicons.com/

**Comment by meshawn** [comment]
I was hoping for Windows 10 pin/unpin icons.  -Thanks

**Comment by JamesCoyle** [comment]
This is a Material Design iconset not a Metro UI iconset (or whatever they decided to call the new one).

**Comment by CoDEmanX** [comment]
True, thus keeping it closed.
