### ISSUE TITLE
battery-eco

### ISSUE THREAD

**Issue by rupinderjeet** [Templarian/MaterialDesign#1717]
An Icon that shows that this game or app is battery friendly.

**Comment by JamesCoyle** [comment]
Do you have an example of how this would be shown?

**Comment by rupinderjeet** [comment]
A battery icon with a plus sign maybe? I was thinking about a landscape battery and plus sign at right most position hiding 25% of battery. I will add an image later.

Or, were you asking about use case?

**Comment by rupinderjeet** [comment]
See [this](http://previews.123rf.com/images/juliarstudio/juliarstudio1512/juliarstudio151200518/49120262-Eco-energy-battery-icon-Battery-with-leaves-Colorful-ecology-symbol-on-a-blue-background-Stock-Vector.jpg) icon.

**Comment by CoDEmanX** [comment]
Maybe `battery-plus` would work as well? Another idea would be to add a checkmark...

**Comment by JamesCoyle** [comment]
I think this would be most recognisable as a battery with `leaf` as a modifier. 

[![](https://materialdesignicons.com/icon/battery
)](https://materialdesignicons.com/icon/battery)[![](https://materialdesignicons.com/icon/leaf
)](https://materialdesignicons.com/icon/leaf)

**Comment by bytrangle** [comment]
Just asking everyone visiting this thread: Is battery-eco the same as battery-friendly to you?

The example image given by OP seemed to refer to eco-friendly batteries. Battery-friendly, on the other hand, is a feature that can be displayed in a game/app to indicate that the app won't drain your battery so that your smartphone charge can last longer. A better name for that feature would be **battery-saving**.

**Comment by steodor** [comment]
@bytrangle not really sure on the semantics tbh, sorry

@JamesCoyle how's this?
![image](https://user-images.githubusercontent.com/4397338/107584066-80b5d000-6c04-11eb-82e1-e2fb295f2846.png)![image](https://user-images.githubusercontent.com/4397338/107584074-827f9380-6c04-11eb-8e06-394fa8e9c732.png)
[battery-leaf.zip](https://github.com/Templarian/MaterialDesign/files/5962207/battery-leaf.zip)

**Comment by goyney** [comment]
The leaf is not a modifier and doesn't really work. We've added `battery-sync(-outline)` for this use case. (I also recommend turning your icon green to indicate... well that's it's green! 😄 )

[![battery-sync](https://materialdesignicons.com/icon/battery-sync)](https://materialdesignicons.com/icon/battery-sync)
