### ISSUE TITLE
low inventory

### ISSUE THREAD

**Issue by mindnervestech** [Templarian/MaterialDesign#1719]
Need icon to show  low inventory.

**Comment by JamesCoyle** [comment]
How could we show this?

**Comment by Croutonix** [comment]
How about these ones:
<img src="https://cloud.githubusercontent.com/assets/18645219/21958091/1b99a06a-da73-11e6-9438-46d868f9be5a.png" width="256">
<img src="https://cloud.githubusercontent.com/assets/18645219/21958106/58c78ac4-da73-11e6-8d30-bb5c90880d15.png" width="256">
<img src="https://cloud.githubusercontent.com/assets/18645219/21958105/58c3f378-da73-11e6-8e21-681079ba5847.png" width="256">

PNG and SVG Files: [inventory_icons.zip](https://github.com/Templarian/MaterialDesign/files/706220/inventory_icons.zip)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @mindnervestech, if you comment with an example of what you're looking for, we'll revisit this issue.
