### ISSUE TITLE
plus-box-outline is missing in css

### ISSUE THREAD

**Issue by topvis** [Templarian/MaterialDesign#1720]
![image](https://cloud.githubusercontent.com/assets/5996531/21513966/c91e3c0e-cc8c-11e6-965a-ec92c0fae4a3.png) is missing in css.

By the way, is there a "minus-box-outline" icon? These will be useful for expanding/collapsing items in a tree view.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history Was added after the 1.7.22 release. Don't worry, we'll have a release out shortly. Just have a few issues to close.

**Comment by Templarian** [comment]
[![minus-box-outline](https://materialdesignicons.com/icon/minus-box-outline)](https://materialdesignicons.com/icon/minus-box-outline)

Also added the minus icon.

**Comment by topvis** [comment]
wow. that's fast. thanks!
