### ISSUE TITLE
Racing/Bike Helmet

### ISSUE THREAD

**Issue by TheSagarPatil** [Templarian/MaterialDesign#1721]
Hi, Please create these icons

Driver icon (i.e. a helmet),
A car icon
a stopwatch icon
letter icons like ABCD etc. and a fuel station icon

Thanks in advanced :)

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/gas-station)](https://materialdesignicons.com/icon/gas-station)[![](https://materialdesignicons.com/icon/car)](https://materialdesignicons.com/icon/car)[![](https://materialdesignicons.com/icon/timer)](https://materialdesignicons.com/icon/timer)

Letter icons have been discussed but are not likely to happen any time soon.

**Comment by MrGrigri** [comment]
The icon request for letters is a duplicate of [#911](https://github.com/Templarian/MaterialDesign/issues/911).

**Comment by MrGrigri** [comment]
Here is my attempt at a racing helmet.

![helmet](https://cloud.githubusercontent.com/assets/4528551/21556461/bfb458ae-cddd-11e6-9be7-5e5010bc373e.png)

[helmet.zip](https://github.com/Templarian/MaterialDesign/files/677962/helmet.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50987528-deccd200-14d7-11e9-9499-3026d35534f7.png)
[sports-motorsports.svg.zip](https://github.com/Templarian/MaterialDesign/files/2746545/sports-motorsports.svg.zip)

**Comment by Templarian** [comment]
[![racing-helmet](https://materialdesignicons.com/icon/racing-helmet)](https://materialdesignicons.com/icon/racing-helmet)

**Comment by PeterShaggyNoble** [comment]
Should this be assigned to Google?

**Comment by MrGrigri** [comment]
Yes, it should be.

**Comment by Templarian** [comment]
Ooops, completely missed that this was from the extended set. Will reassign.

**Comment by Templarian** [comment]
Fixed. Thanks for double checking. 👍
