### ISSUE TITLE
FAQ 

### ISSUE THREAD

**Issue by ekntrtmz** [Templarian/MaterialDesign#1722]

**Comment by Templarian** [comment]
What would this look like? Most use the `help` or one of the circle variants.

**Comment by ekntrtmz** [comment]
Some combination of ? and ! inside a speech bubble?

**Comment by JamesCoyle** [comment]
A '?!' icon could also indicate profanity.

**Comment by Templarian** [comment]
@JamesCoyle That's more `$#`. `?!` is more question response.

**Comment by ekntrtmz** [comment]
Also possible: ?i

**Comment by MrGrigri** [comment]
How about this?

![faq](https://cloud.githubusercontent.com/assets/4528551/21653310/b41fd01a-d26d-11e6-9d37-dc282ca5ea10.png)

[faq.zip](https://github.com/Templarian/MaterialDesign/files/685476/faq.zip)

**Comment by MrGrigri** [comment]
This is also a duplicate of [#1544](https://github.com/Templarian/MaterialDesign/issues/1544)

**Comment by ekntrtmz** [comment]
@MrGrigri Not exactly what I am looking for, but good as a start. Thanks.

**Comment by Templarian** [comment]
![faq](https://cloud.githubusercontent.com/assets/338885/21971282/bb8a3bc8-db74-11e6-95a4-6e5f274d6d10.png) ![faq](https://cloud.githubusercontent.com/assets/338885/21971288/c473d956-db74-11e6-8c16-35c983909376.png)

Something like this, still not sure on this design.

**Comment by MrGrigri** [comment]
Is that supposed to be the letter 'i' or the upside-down exclamation point for a Spanish exclamational phrase?

**Comment by Templarian** [comment]
`Question-Information`, wasn't sure if the alert was obvious as a `question-answer`. Maybe exclamation is better?

**Comment by MrGrigri** [comment]
I believe that an exclamation would be better. I just wish there was enough room to have one message bubble with a question mark (background) and the other to have the letter 'i' or an exclamation point (foreground). To symbolize a question-response situation.

**Comment by CoDEmanX** [comment]
@MrGrigri Yeah, there's not enough space: https://github.com/Templarian/MaterialDesign/issues/647#issuecomment-136004605

**Comment by Templarian** [comment]
Added. 😃  Alias of `faq` added along with the full name.
