### ISSUE TITLE
mdi-rotate-90 shows an icon instead of rotating

### ISSUE THREAD

**Issue by Phr33d0m** [Templarian/MaterialDesign#1723]
Hello, I was trying to rotate an icon by 90 degrees and found that mdi-rotate-90 is an actual defined icon so my chosen icon got replaced by it. Also the 90 rotation was applied which is ok.

```html
<md-icon md-font-icon="mdi mdi-chevron-right mdi-rotate-90"></md-icon>
```

Should show the chevron pointing down but is showing a different icon instead.

Regards.

PS: Yes I know chevron-down exists ;-).

**Comment by Templarian** [comment]
Will be fixed in the next release. 😅 

Duplicate #1705
