### ISSUE TITLE
Chat Settings

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1724]
I have created the following for a project at work. However, I still haven't decided which is better. But, I believe that we could use both. 

chat-settings-variant

![chat-settings-variant 4x](https://cloud.githubusercontent.com/assets/4528551/21550829/37b583ba-cdba-11e6-83df-d4cea220f3f7.png) ![chat-settings-variant](https://cloud.githubusercontent.com/assets/4528551/21550828/37b2fc26-cdba-11e6-96c6-e8dbd9d94c43.png)

chat-settings

![chat-settings 4x](https://cloud.githubusercontent.com/assets/4528551/21550839/3e6342b0-cdba-11e6-9349-b72198af990d.png) ![chat-settings](https://cloud.githubusercontent.com/assets/4528551/21550838/3e63480a-cdba-11e6-9fcd-2f47035a7ea4.png)

[chat-settings.zip](https://github.com/Templarian/MaterialDesign/files/677661/chat-settings.zip)

**Comment by JamesCoyle** [comment]
Three dots is usually prefered but in this case it seems like it could be mistaken for 'more messages' or 'person is currently writing message'.

**Comment by Templarian** [comment]
Agreed, in this _rare_ instance having the variant `message-settings` / `message-settings-variant` will be fine.

**Comment by Templarian** [comment]
[![message-settings](https://materialdesignicons.com/icon/message-settings)](https://materialdesignicons.com/icon/message-settings) [![message-settings-variant](https://materialdesignicons.com/icon/message-settings-variant)](https://materialdesignicons.com/icon/message-settings-variant)
