### ISSUE TITLE
variable

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1725]
Here is another icon that I am using to designate a variable. 

![variable 4x](https://cloud.githubusercontent.com/assets/4528551/21552956/77d7ea98-cdc2-11e6-90cd-e608a54fe0b0.png) ![variable](https://cloud.githubusercontent.com/assets/4528551/21552957/77dcfa74-cdc2-11e6-96ff-5366c32d53dd.png)

[variable.zip](https://github.com/Templarian/MaterialDesign/files/677765/variable.zip)

**Comment by Templarian** [comment]
@MrGrigri I like the idea, but we should use the more material parenthesis skewed.

[![code-parenthesis](https://materialdesignicons.com/icon/code-parentheses)](https://materialdesignicons.com/icon/code-parentheses)

**Comment by MrGrigri** [comment]
Like this? I kept the 'x' skewed because in math the x is typically italicized. 

![variable](https://cloud.githubusercontent.com/assets/4528551/21567659/fcd89d84-ce6a-11e6-9625-d6fb5bbac0cb.png)

[variable.zip](https://github.com/Templarian/MaterialDesign/files/678842/variable.zip)

**Comment by Templarian** [comment]
[![variable](https://materialdesignicons.com/icon/variable)](https://materialdesignicons.com/icon/variable)

Skewed the `( )` also by `6.0`.
