### ISSUE TITLE
Search Online icon

### ISSUE THREAD

**Issue by abdfahim** [Templarian/MaterialDesign#1726]
It'd be very nice to have a search online icon. This could be like a search magnifying glass on top of a globe.

**Comment by MrGrigri** [comment]
Here is my attempt. 

![search-web](https://cloud.githubusercontent.com/assets/4528551/21556623/3b948434-cddf-11e6-8f45-8a3f25fc40bf.png)

[search-web.zip](https://github.com/Templarian/MaterialDesign/files/677969/search-web.zip)

**Comment by Templarian** [comment]
I'm not really sure this icon is really needed. The regular magnify icon can be used to signify searching the web. Going to close this issue out, but let me know if you think there are scenarios where this is needed.

**Comment by abdfahim** [comment]
Well, I have a personal library management app where user can store book details. So, I have two conditions
1) User want to search through their own collection, for which I use the usual magnifying glass
2) User want to search online (e.g. Google Books/Amazon) for a particular book and subsequently can add that book to wishlist or collection. So, I need a button which distinguish this online search from local search of (1)

If that makes sense.

**Comment by abdfahim** [comment]
@MrGrigri that is very nice and intuitive, thanks for that. I'd love to know how can I export that in a Android 5.x package.

**Comment by MrGrigri** [comment]
@abdfahim, it will be added to the repo if @Templarian wants to add it -- which it looks like it will. Then you'll have to wait for the next release. When it's accepted and pushed to a new version, then this issue will be closed. At that point, it'll be just like any other icon in this pack (i.e. it'll be added as a font, SVG, etc.)

**Comment by Templarian** [comment]
[![search-web](https://materialdesignicons.com/icon/search-web)](https://materialdesignicons.com/icon/search-web)
