### ISSUE TITLE
moon icon

### ISSUE THREAD

**Issue by PiusNyakoojo** [Templarian/MaterialDesign#1727]
Please make a moon icon

**Comment by MrGrigri** [comment]
Does `weather-night` not work?

![weather-night](https://materialdesignicons.com/icon/weather-night)

**Comment by JapanYoshi** [comment]
I think ``weather-night`` should have an alias ``moon``, just so people can search up "moon" on the site and get that icon.

**Comment by PiusNyakoojo** [comment]
Yea that works, I just removed the stars to have the look I wanted :smile:

**Comment by PeterShaggyNoble** [comment]
Aliases `moon-and-stars` and `night-sky` added.

**Comment by bernardovs23** [comment]
`brightness-1`, `brightness-2` and `brightness-3` (maybe even `brightness-4`) should have the `moon` alias
