### ISSUE TITLE
Push button

### ISSUE THREAD

**Issue by bokub** [Templarian/MaterialDesign#1728]
I'm surprised there is no push button icon, something [like that](https://cdn3.iconfinder.com/data/icons/office-productivity-and-communication/400/Productivity-17-128.png)

**Comment by MrGrigri** [comment]
I have tried to come up with a push button icon that follows Material Design standards but, I have come up short.

**Comment by ButchMonkey** [comment]
Why not a combination of the hand icon and a circle.
More like [this](https://cdn4.iconfinder.com/data/icons/selection-and-cursors/128/Selection__cursors_cursor_tap_circle-512.png)

**Comment by bokub** [comment]
@ButchMonkey Something like that would be perfect

**Comment by MrGrigri** [comment]
Here is my take on this. However, I'm a little concerned that it might be confused with tapping or other gesture icons. But then again, maybe we could add a set of gesture icons using this one as a base. What are your thoughts @Templarian?

![push-button](https://cloud.githubusercontent.com/assets/4528551/22268223/f37ac586-e243-11e6-80ae-9b135df44470.png)

[push-button.zip](https://github.com/Templarian/MaterialDesign/files/728039/push-button.zip)

**Comment by MrGrigri** [comment]
I guess Google already has one called [touch-app](https://material.io/icons/#ic_touch_app) for this same purpose. So we might just want to use theirs.

**Comment by JapanYoshi** [comment]
Why not make a side view?

**Comment by MrGrigri** [comment]
@bokub does issue [#1798](https://github.com/Templarian/MaterialDesign/issues/1798#event-935666593) meet your needs? If so, we'll close this issue out.

**Comment by bokub** [comment]
Well, my original need was for a physical button (an Amazon dash to be precise), but the gesture-tap will fit right. 
Thanks fot

**Comment by bokub** [comment]
*Thanks for your help
