### ISSUE TITLE
dvr-live

### ISSUE THREAD

**Issue by RoopKumarReddy** [Templarian/MaterialDesign#173]
Request for 'Go Live' Icon for DVR recording functionality for Live video streams
- [ ] dvr-live

**Comment by CoDEmanX** [comment]
Does this fulfill the request?

[![record-rec](https://materialdesignicons.com/icon/record-rec)](https://materialdesignicons.com/icon/record-rec)

**Comment by GreenTurtwig** [comment]
The icon above should satisfy the request.
