### ISSUE TITLE
router (wired)

### ISSUE THREAD

**Issue by nickarellano** [Templarian/MaterialDesign#1731]
We have wireless router, it would be cool if someone could make a nice modem mdi icon.

**Comment by JamesCoyle** [comment]
So a version of `server-network` with just one box to match `router-wireless`.
[![](https://materialdesignicons.com/icon/server-network)](https://materialdesignicons.com/icon/server-network)[![](https://materialdesignicons.com/icon/router-wireless)](https://materialdesignicons.com/icon/router-wireless)

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/61858407-4cfe4280-aec6-11e9-9f43-045ce5fe4a1e.png)

[network-router.zip](https://github.com/Templarian/MaterialDesign/files/3430493/network-router.zip)

**Comment by goyney** [comment]
[![network-router](https://materialdesignicons.com/icon/network-router)](https://materialdesignicons.com/icon/network-router)
