### ISSUE TITLE
Icon request: plant

### ISSUE THREAD

**Issue by mjmare** [Templarian/MaterialDesign#1733]
as in the green growing stuff, not a factory

**Comment by Templarian** [comment]
Would leaf work for that? Or one of the tree icons. We don't have a potted plant icon if that is what you're looking for?

[![leaf](https://materialdesignicons.com/icon/leaf)](https://materialdesignicons.com/icon/leaf)

**Comment by PeterShaggyNoble** [comment]
[flower](https://materialdesignicons.com/icon/flower) might also work, depending on the use case.

**Comment by mjmare** [comment]
The leaf is nice, thanks!
