### ISSUE TITLE
Icon request: garden

### ISSUE THREAD

**Issue by mjmare** [Templarian/MaterialDesign#1734]

**Comment by PeterShaggyNoble** [comment]
Would [flower](https://materialdesignicons.com/icon/flower) suit your needs?

**Comment by mjmare** [comment]
Yes it would. OTOH some plant multiple would be nice ;-)
Thanks!

**Comment by Templarian** [comment]
I don't think with the space we'll be able to show it better than flower does. It'll end up looking like grass or a box of grass at 24x24.

**Comment by CoDEmanX** [comment]
Maybe the `flower` icon works? In Google Fit there is also an icon for this thingy:

![spray-23007886 1](https://cloud.githubusercontent.com/assets/1309249/22470600/22606bd0-e7d0-11e6-8054-843e78ec9f56.jpg)

It believe it is called "household activity", but we don't have it in MDI.
