### ISSUE TITLE
scale icon

### ISSUE THREAD

**Issue by xmavara** [Templarian/MaterialDesign#1735]
a scale icon to resize like unfold more icon but rotated

**Comment by PeterShaggyNoble** [comment]
Got an example of what you're looking for? There are a few icons available already that might cover your needs.

**Comment by xmavara** [comment]
scale icon something like this:
http://uploads.im/noCXD.jpg
i want an icon to resize like two way arrow.

**Comment by xmavara** [comment]
arrow-expand is not bad
i can rotate it -90°
anyway thanks
