### ISSUE TITLE
Space symbols

### ISSUE THREAD

**Issue by Foobin** [Templarian/MaterialDesign#1736]
Symbols for space/astronomy:
* Astronaut
* Rocket
* Space
* Planet
* Star
* Telescope

**Comment by Foobin** [comment]
I can't figure out how to add the icon request label to this post, sorry.

**Comment by PeterShaggyNoble** [comment]
[Rocket](https://materialdesignicons.com/icon/rocket) and [star](https://materialdesignicons.com/icon/star) (or [star-outline](https://materialdesignicons.com/icon/star-outline)) already exist, or there's [weather-sunny](https://materialdesignicons.com/icon/weather-sunny) and [white-balance-sunny](https://materialdesignicons.com/icon/white-balance-sunny), if you prefer.

**Comment by mcaminiti** [comment]
I would still like to see a telescope added. Would be nice to use it for some of the ISS spotting settings I have.

**Comment by Templarian** [comment]
@mcaminiti I'm going to close this issue. Can you open an issue for a `telescope` so we can track this one individually.

Thanks for searching by the way. 😃

**Comment by CoDEmanX** [comment]
See #3467
