### ISSUE TITLE
Bus outline

### ISSUE THREAD

**Issue by ayozebarrera** [Templarian/MaterialDesign#1737]

**Comment by MrGrigri** [comment]
I believe a bus outline would be quite dificult...but maybe someone here in the community can tackle that. Just as a reference, here is the bus icon.

![bus](https://materialdesignicons.com/icon/bus)

**Comment by Templarian** [comment]
Played with the idea and yea, this isn't really an icon that looks right as an outline.

**Comment by ayozebarrera** [comment]
Thanks for trying!
