### ISSUE TITLE
Missing zoom-in and zoom-out icons

### ISSUE THREAD

**Issue by octojoerg** [Templarian/MaterialDesign#1738]
I'm actually searching for the google "zoom in" and "zoom out" icons. Were they deleted form the set? you can still find them on official MI webpage:

![image](https://cloud.githubusercontent.com/assets/19168327/21611493/53d54f6e-d1cd-11e6-9494-c7d0256931bb.png)

I know, you have the filled zoom icons, like https://materialdesignicons.com/icon/magnify-plus, but I need the non-filled versions.

Thanks

**Comment by octojoerg** [comment]
maybe it need "Icon Request" label ;)

**Comment by octojoerg** [comment]
[zoom-in.zip](https://github.com/Templarian/MaterialDesign/files/687646/zoom-in.zip)
[zoom-out.zip](https://github.com/Templarian/MaterialDesign/files/687647/zoom-out.zip)

**Comment by Templarian** [comment]
[![magnify-plus-outline](https://materialdesignicons.com/icon/magnify-plus-outline)](https://materialdesignicons.com/icon/magnify-plus-outline) [![magnify-minus-outline](https://materialdesignicons.com/icon/magnify-minus-outline)](https://materialdesignicons.com/icon/magnify-minus-outline)

Added.
