### ISSUE TITLE
Food Icons

### ISSUE THREAD

**Issue by kylewludwig** [Templarian/MaterialDesign#1739]
Add a breakfast, lunch, dinner, and snack icon. A runner without the lines could be added, too.

**Comment by Templarian** [comment]
Do you have examples of what these would look like? Remembering the smaller size constraints.

**Comment by kylewludwig** [comment]
Here are a few examples from Iconfinder without the material design. I found very modern material design icons throughout Dribbble in different UI's.
Breakfast
<img width="157" alt="screen shot 2017-01-04 at 12 26 56 pm" src="https://cloud.githubusercontent.com/assets/24880524/21652289/19ef097c-d27a-11e6-998a-65e7d4beda0e.png">
Sandwich/Lunch
<img width="146" alt="screen shot 2017-01-04 at 12 27 41 pm" src="https://cloud.githubusercontent.com/assets/24880524/21652290/19f3dfe2-d27a-11e6-9355-ec5cc98d6bfd.png">
Soup
<img width="140" alt="screen shot 2017-01-04 at 12 29 26 pm" src="https://cloud.githubusercontent.com/assets/24880524/21652291/19f893d4-d27a-11e6-86f2-859a7e926b9e.png">
Entree/Dinner
<img width="127" alt="screen shot 2017-01-04 at 12 29 56 pm" src="https://cloud.githubusercontent.com/assets/24880524/21652292/19fea878-d27a-11e6-82f7-9dc650ad2d66.png">
Meat
<img width="143" alt="screen shot 2017-01-04 at 12 30 40 pm" src="https://cloud.githubusercontent.com/assets/24880524/21652293/1a04a908-d27a-11e6-865c-f70826a80793.png">
Runner/Activity Icon
<img width="128" alt="screen shot 2017-01-04 at 12 31 57 pm" src="https://cloud.githubusercontent.com/assets/24880524/21652294/1a0a1794-d27a-11e6-9366-1bad81eb5378.png">
And a snack icon. The protein/candy bar should be a longer rectangle
<img width="135" alt="screen shot 2017-01-04 at 12 33 42 pm" src="https://cloud.githubusercontent.com/assets/24880524/21652295/1a109880-d27a-11e6-88c2-b8e280d3ddde.png">

**Comment by MrGrigri** [comment]
Maybe this is a Google icon that isn't in the repo, I'll check, but there is an `ic_directions_run` found [here](https://material.io/icons/#ic_directions_run). 

Some of these would be too complicated for MD guidelines.

**Comment by choikath** [comment]
Will piggyback and add a request for a banana icon!

**Comment by dabell-cc** [comment]
While looking for meal/cooking icons it seems there's few open requests.
https://github.com/Templarian/MaterialDesign/issues/2100 asks for a chef's hat.
![image](https://user-images.githubusercontent.com/8835326/34432034-beaea742-ec41-11e7-94fd-ef388c366413.png)


I'd like to suggest a general meal icon such as 
![image](https://user-images.githubusercontent.com/8835326/34432026-a9627e90-ec41-11e7-996b-6eb36b6d391c.png)

**Comment by PeterShaggyNoble** [comment]
@dabell-cc, would `silverware-variant` suit your needs?

[![silverware-variant](https://user-images.githubusercontent.com/15157491/34479922-3b9dc7f8-efa1-11e7-8252-b747151583d4.png)
](https://materialdesignicons.com/icon/silverware-variant)

**Comment by goyney** [comment]
We have added a bunch of `food-` related icons since this issue was first filed. I'm going to close it due to inactivity. If there are any specific icons you'd like to see added, please create an issue for each icon. Thanks.
