### ISSUE TITLE
Horse

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#174]
Can you create a icon representing a horse?
Thanks in advance!
- [ ] horse

**Comment by goyney** [comment]
This icon can be found in Google Fit and will need to be recreated for inclusion in the library.
![horse](https://user-images.githubusercontent.com/1015040/48862687-14d1bd80-ed95-11e8-9cf6-7a1a1e3dde78.png)

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/48975366-8bdcaf80-f03c-11e8-9cfe-81fb5bb32bae.png)

[horse.svg.zip](https://github.com/Templarian/MaterialDesign/files/2612830/horse.svg.zip)

**Comment by xabi62** [comment]
Can you add an icon hor entire horse an not just the head ?
Like this one https://thumbs.dreamstime.com/z/web-139990293.jpg

**Comment by Xenomorph99** [comment]
[horse-icons.zip](https://github.com/Templarian/MaterialDesign/files/4909587/horse-icons.zip)
![87211128-46cec500-c2d5-11ea-9417-a0891f3d5800](https://user-images.githubusercontent.com/1837101/87257162-c2f01680-c455-11ea-881a-70bf065e16c0.png)
![87211127-45050180-c2d5-11ea-8101-25401abc46d7](https://user-images.githubusercontent.com/1837101/87257164-c4b9da00-c455-11ea-8766-700ae9aa6af8.png)

**Comment by Xenomorph99** [comment]
Here's a revised version that lines up more frequently to the grid. It avoids quarter pixels, but still lines up to half pixels in some areas. The legs in this version are 2.5 wide which forced me to shrink the neck a bit. I also changed the tail to help it feel more fluid. Let me know if you have any other recommendations. Once we get the base nailed down I'll update the rider and unicorn variants.
![horse](https://user-images.githubusercontent.com/1837101/88850432-9ef83900-d1a8-11ea-8035-b10fa3432e53.png)
[horse.zip](https://github.com/Templarian/MaterialDesign/files/4997331/horse.zip)

**Comment by goyney** [comment]
I think this is better, but I wonder if it's too narrow. Can you toy with it a bit more to make it wider 1dp on both sides?

**Comment by Xenomorph99** [comment]
I was running into problems with the tail when I stretched the width before, but I think I solved it. I left 3px above and below to give room to shift it down for the 'horse-human' and 'unicorn' variants.

In 'horse-human', I shifted the head circle to the right slightly to line it up with the grid. This gives the subtle impression that the human rider is facing the same direction as the horse.

Thanks for the feedback. Let me know if you have any other recommended adjustments.

![horse](https://user-images.githubusercontent.com/1837101/89259070-c30fac00-d5e6-11ea-9189-fa9405026d3e.png)
![horse-human](https://user-images.githubusercontent.com/1837101/89259069-c1de7f00-d5e6-11ea-9371-1036b49d17e4.png)

[horse-icons.zip](https://github.com/Templarian/MaterialDesign/files/5020370/horse-icons.zip)

**Comment by goyney** [comment]
These look a ton better! Nice work. Get that unicorn made and I'll get these added sometime today.

**Comment by Xenomorph99** [comment]
I uploaded the unicorn designs to #2739.

![horse-head](https://user-images.githubusercontent.com/1837101/89317587-cc2a6880-d63a-11ea-9833-e5e963200600.png)

Here's two options for the 'horse-head-variant'. Personally I like the simplicity of A, but B is similar to some of the concepts above.

![horse-head-variant-a](https://user-images.githubusercontent.com/1837101/89317579-caf93b80-d63a-11ea-83af-48d90ac7526e.png)
![horse-head-variant-b](https://user-images.githubusercontent.com/1837101/89317585-cb91d200-d63a-11ea-9df0-0674a9aac4e2.png)

[horse-head.zip](https://github.com/Templarian/MaterialDesign/files/5023190/horse-head.zip)

**Comment by goyney** [comment]
[![horse](https://materialdesignicons.com/icon/horse)](https://materialdesignicons.com/icon/horse)[![horse-human](https://materialdesignicons.com/icon/horse-human)](https://materialdesignicons.com/icon/horse-human)
[![horse-variant](https://materialdesignicons.com/icon/horse-variant)](https://materialdesignicons.com/icon/horse-variant)
