### ISSUE TITLE
Head, Body, Foot

### ISSUE THREAD

**Issue by AAronsson** [Templarian/MaterialDesign#1740]
I have a menu where I can design page-header, page-document/body and page-footer.

It could be a human head, and foot, and then also maybe body(torso). That could be fun.

Or a more page-head/foot like icon.

- [ ] page-layout-sidebar
- [ ] page-layout-head
- [ ] page-layout-body
- [ ] page-layout-footer

**Comment by Templarian** [comment]
Added `-sidebar` to the list and possible names.

**Comment by Templarian** [comment]
Idea... trying to think of a design idea that might work that doesn't have too much detail. What about:

![header](https://cloud.githubusercontent.com/assets/338885/21970140/65aaca7a-db69-11e6-939e-48914243947e.png) Header
![sidebar](https://cloud.githubusercontent.com/assets/338885/21970143/6c414fa8-db69-11e6-9e14-041d6f0691f6.png) Sidebar
![body](https://cloud.githubusercontent.com/assets/338885/21970147/717bd722-db69-11e6-8dba-cb8f0e96b6a5.png) Body
![footer](https://cloud.githubusercontent.com/assets/338885/21970149/75df39b2-db69-11e6-9c0d-05d74f1c6b1f.png) Footer

**Comment by MrGrigri** [comment]
I believe there should be a body with a blackened aside, like the one you have and the a full-width body for the occasions that there isn't an aside.

**Comment by Templarian** [comment]
That makes sense not all page layouts will use that 'aside' sidebar. @AAronsson was this the kind of idea you had in mind for this icon?

**Comment by AAronsson** [comment]
It looks really good!
My case was to a PDF-document that I will generate from templates. So in my case the body would be full-width.

**Comment by Templarian** [comment]
[![page-layout-header](https://materialdesignicons.com/icon/page-layout-header)](https://materialdesignicons.com/icon/page-layout-header) [![page-layout-body](https://materialdesignicons.com/icon/page-layout-body)](https://materialdesignicons.com/icon/page-layout-body) [![page-layout-footer](https://materialdesignicons.com/icon/page-layout-footer)](https://materialdesignicons.com/icon/page-layout-footer) [![page-layout-sidebar-left](https://materialdesignicons.com/icon/page-layout-sidebar-left)](https://materialdesignicons.com/icon/page-layout-sidebar-left) [![page-layout-sidebar-right](https://materialdesignicons.com/icon/page-layout-sidebar-right)](https://materialdesignicons.com/icon/page-layout-sidebar-right)
