### ISSUE TITLE
Google Stock Icon

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1741]
[ic_directions_run](https://material.io/icons/#ic_directions_run) is missing from the repo.

**Comment by Templarian** [comment]
We already have a run icon... called `run`.

[![run](https://materialdesignicons.com/icon/run)](https://materialdesignicons.com/icon/run)

**Comment by MrGrigri** [comment]
I understand that y'all have this one. But the issue was that the package is missing the google stock icon. But if you feel that this icon is sufficient or better then that's fine. I was just letting you know.

**Comment by JamesCoyle** [comment]
I prefer the Google variant TBH.

**Comment by Templarian** [comment]
Oh... hmm. Okay we can replace it then.

**Comment by Templarian** [comment]
[![run](https://materialdesignicons.com/icon/run)](https://materialdesignicons.com/icon/run)
