### ISSUE TITLE
security-account

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1742]
Here is another icon that I am using and I thought that the community could use. `security-account`.

![account-security](https://cloud.githubusercontent.com/assets/4528551/21656751/9ba79ed2-d27c-11e6-882e-6fe2474d3ca7.png)

[security-account.zip](https://github.com/Templarian/MaterialDesign/files/685741/security-account.zip)

**Comment by JamesCoyle** [comment]
I'd move the person down so the bottom line is level with the stroke at the bottom of the shield.

**Comment by MrGrigri** [comment]
I'm not following. The account outline is 2px away from all sides.

**Comment by JamesCoyle** [comment]
Something like this but that doesn't look as bad...
![image](https://user-images.githubusercontent.com/10384436/28441242-b86be404-6da1-11e7-80d7-256a10a6f17a.png)

Still haven't bothered learning how to use a vector editor for icons and my icon creator doesn't have bezier curve tools yet so I approximated by hand to show the general idea I had.

**Comment by MrGrigri** [comment]
Ah, I see. That makes sense. I'll get that fixed.

**Comment by Templarian** [comment]
[![security-account](https://materialdesignicons.com/icon/security-account)](https://materialdesignicons.com/icon/security-account)
