### ISSUE TITLE
GitHub/Octocat Logo 

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1743]
I feel like this has been discussed before but it's impossible to search for issues related to github apparently. Is there any way we can have a github logo that isn't a circle or box variant?

**Comment by Templarian** [comment]
Their logo is a circle and their branding mark is that circle octocat. I added the box one to match twitter/fb, but even that isn't in their guidelines. Octocat kind of looks odd when it's not the silhouette also.

**Comment by JamesCoyle** [comment]
I'm creating circular social icons on a site so the circle in a circle looks weird. It would be better with just Octocat that I could put in a gray circle to look like the Github logo.

How about something like this? https://octicons.github.com/icon/octoface/

**Comment by Templarian** [comment]
Yea, that's kind of what I meant by it looks "odd". Probably need to stick to the silhouette without the eyes.

**Comment by Templarian** [comment]
[![github-face](https://materialdesignicons.com/icon/github-face)](https://materialdesignicons.com/icon/github-face)
