### ISSUE TITLE
mdi-file-image-box is not showing up

### ISSUE THREAD

**Issue by msaiyaff** [Templarian/MaterialDesign#1745]
The icon - 'mdi-file-image-box' https://cdn.materialdesignicons.com/1.1.34/ is not showing up where other icons which i tried works at the same position.

**Comment by Templarian** [comment]
@msaiyaff Can you please modify this codepen to reproduce this bug you're setting.

http://codepen.io/anon/pen/MJYXvQ

**Comment by msaiyaff** [comment]
Hi @Templarian 
This particular icon 'mdi-file-image-box' is not working. Since it's working in the codepen for the same. So, I made a move to check my package.json file.
And, my bad I was using the version 1.7.22 and it doesn't have this **'mdi-file-image-box**' but the same icon as '**mdi-image**'.
It was an issue from my side which occurred because of referring to the 1.1.34 but using 1.7.22.
Thanks a lot for the consideration.
Closing the issue.
