### ISSUE TITLE
Edit account

### ISSUE THREAD

**Issue by archirex** [Templarian/MaterialDesign#1746]
I see add account/person, and remove, but no edit. Probably the generic person, behind a generic pencil (edit).

- [x] edit_person

**Comment by MrGrigri** [comment]
How about this?

![account-edit](https://cloud.githubusercontent.com/assets/4528551/21779640/bfafe9e6-d665-11e6-896c-3e12485fe198.png)

[account-edit.zip](https://github.com/Templarian/MaterialDesign/files/694434/account-edit.zip)

**Comment by archirex** [comment]
Looks good to me.

**Comment by Templarian** [comment]
[![account-edit](https://materialdesignicons.com/icon/account-edit)](https://materialdesignicons.com/icon/account-edit)
