### ISSUE TITLE
Google's own Restart icon

### ISSUE THREAD

**Issue by bebenins** [Templarian/MaterialDesign#1747]
With Android N Google introduced new "restart" icon.  This is how it looks (taken from my stock Nexus 6P):
![screenshot_20170106-152118](https://cloud.githubusercontent.com/assets/16761301/21731809/42143516-d424-11e6-82a7-5639af473d98.png)
 
Sorry, not sure how to add labels

**Comment by Templarian** [comment]
[![restart](https://materialdesignicons.com/icon/restart)](https://materialdesignicons.com/icon/restart)

**Comment by bebenins** [comment]
Sweet!  Thank you!
