### ISSUE TITLE
Leaderboard Icon

### ISSUE THREAD

**Issue by Agshin43** [Templarian/MaterialDesign#1749]

**Comment by MrGrigri** [comment]
Would `trophy` or `trophy-variant` or `chart-bar` not work?

![trophy](https://materialdesignicons.com/icon/trophy) ![trophy-variant](https://materialdesignicons.com/icon/trophy-variant) ![chart-bar](https://materialdesignicons.com/icon/chart-bar)

**Comment by PeterShaggyNoble** [comment]
`format-list-numbers` would be another option.

![](https://materialdesignicons.com/icon/format-list-numbers)

**Comment by Agshin43** [comment]
Thank you. But none of above is leaderboard icon. (https://maxcdn.icons8.com/windows8/PNG/512/Sports/leaderboard-512.png)

**Comment by Simran-B** [comment]
In that case have a look here: https://github.com/Templarian/MaterialDesign/issues/979

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #979.
