### ISSUE TITLE
duckduckgo

### ISSUE THREAD

**Issue by The0x539** [Templarian/MaterialDesign#175]
![image](https://cloud.githubusercontent.com/assets/7350294/6413493/9eab7b7c-be55-11e4-8f39-d266ac491e4a.png)
And please *try* not to butcher Dax like you did Tux. :P

- [ ] duckduckgo

**Comment by Templarian** [comment]
There is too much detail in the logo to match the small style.

![image](https://cloud.githubusercontent.com/assets/338885/6413858/008606fc-be59-11e4-8f5f-71da3f01bd4d.png)
