### ISSUE TITLE
Icon request : half filled circle

### ISSUE THREAD

**Issue by ThomasPfrimmer** [Templarian/MaterialDesign#1750]
please add an half filled circle icon : checkbox-blank-circle-half-outline. 
to have an intermediary value between checkbox-blank-circle and checkbox-blank-circle-outline.

Like heart-half-outline, but with a circle.

**Comment by JapanYoshi** [comment]
Why would you ever turn a radio button *half* on though?

**Comment by Templarian** [comment]
Yea, this seems a bit specific. Not sure this is a valid scenario for an icon. I'm going to close it out.

**Comment by topvis** [comment]
One scenario could be using a filled-circle, half-filled-circle and circle-outline to indicate the status of  done, in progress and not started. Currently I use a uni-code character "◒". It would be good to have an mdi icon for it.

**Comment by PeterShaggyNoble** [comment]
One use case would be a site I worked on a while ago that used circles for ratings and needed to be able to show half ratings.
