### ISSUE TITLE
Icon Request: New Releases (Stock Icon)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1751]
I've spotted [ic_new_releases](https://material.io/icons/#ic_new_releases) in a few Android apps recently but only now noticed it's missing from the library here.

**Comment by Templarian** [comment]
[![octagram](https://materialdesignicons.com/icon/octagram)](https://materialdesignicons.com/icon/octagram) [![alert-octagram](https://materialdesignicons.com/icon/alert-octagram)](https://materialdesignicons.com/icon/alert-octagram)
