### ISSUE TITLE
Icons delete-empty isn't part of the package

### ISSUE THREAD

**Issue by DblK** [Templarian/MaterialDesign#1754]
Here is a part of the CSS:
`.mdi-delete:before{content:"\F1C0"}.mdi-delete-circle:before{content:"\F682"}.mdi-delete-forever:before{content:"\F5E8"}.mdi-delete-sweep:before{content:"\F5E9"}.mdi-delete-variant:before{content:"\F1C1"}`

Can you add this icon in the main css?

**Comment by JamesCoyle** [comment]
It was added after the latest release. https://materialdesignicons.com/history

The next release should be pretty soon.

**Comment by DblK** [comment]
Thank for your reply, I will wait for the next release then.
