### ISSUE TITLE
appearance icon

### ISSUE THREAD

**Issue by litagandara** [Templarian/MaterialDesign#1756]
An icon for a section where the user can change the appearance of colours and text.
<img width="226" alt="screenshot 2017-01-10 15 31 25" src="https://cloud.githubusercontent.com/assets/4253733/21812208/08a9382a-d74a-11e6-96a5-bca43bc78429.png">
<img width="288" alt="screenshot 2017-01-10 15 31 16" src="https://cloud.githubusercontent.com/assets/4253733/21812209/08a9dfd2-d74a-11e6-8254-b67093de34f7.png">

**Comment by MrGrigri** [comment]
We will hopefully have [this](https://github.com/Templarian/MaterialDesign/issues/1714) icon for font. would that work?

**Comment by Templarian** [comment]
Closing this icon request as a duplicate and marking the other as high priority.
