### ISSUE TITLE
One-time Password Verification

### ISSUE THREAD

**Issue by sushantDhamanekar** [Templarian/MaterialDesign#1757]
How about otp verification icon?

**Comment by GreenTurtwig** [comment]
Do you have an example of this? Not really sure how you would represent it in "icon" form.

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @sushantDhamanekar, if you can provide an example, we will revisit this issue.

**Comment by matthieusieben** [comment]
Example posted here : https://github.com/Templarian/MaterialDesign/issues/6944
