### ISSUE TITLE
Release 1.8.36

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1759]
I have a list of icons required for this release. Started marking them with a high priority task.

There is one SCSS addition.

Is there anything we 100% require for this release going out. I have a free weekend coming up and plan to get the release out (over 100+ new icons).

**Comment by Templarian** [comment]
Been out the last few days with the flu. Still working on this, but might be pushed back a tiny bit. 😷

Feeling better now and catching up on the backlog.

**Comment by Templarian** [comment]
If you could help review this release, there are 114 new icons.

https://cdn.materialdesignicons.com/1.8.36/

There is also a CSS change. `.mdi::before { line-height: inherit; }` was added.

**Comment by Templarian** [comment]
The download for the latest design files is up also...

https://cdn.materialdesignicons.com/1.8.36/MaterialDesignIconsDesign.zip

**Comment by ButchMonkey** [comment]
Are the icons a different size since the last release? Even if I set `.mdi::before { line-height: inherit; }` to normal the seem off

**Comment by Templarian** [comment]
I purged the CDN cache and updated with a couple of minor tweaks. Updates to the design download also.

Now to work on the next release. 😄

**Comment by PeterShaggyNoble** [comment]
The [history page](https://materialdesignicons.com/history) isn't showing this release.

**Comment by Templarian** [comment]
Fixed, knew I forgot something. That's still a manual step. Thanks!
