### ISSUE TITLE
Multiples hexagons

### ISSUE THREAD

**Issue by ayozebarrera** [Templarian/MaterialDesign#1760]
Hi, i'm looking for an icon that represents multiples hexagons, or something like honey comb...

I saw the chart-scatterplot-hexbin icon but I don't need those bars... something like this would be great:

![hexs](https://cloud.githubusercontent.com/assets/6180188/21890912/ff31d07a-d8c7-11e6-914f-8fa0ca97e45f.png)
(this is chart-scatterplot-hexbin but I removed the bars for the screenshot)

Thankyou!

**Comment by Templarian** [comment]
[![hexagon-multiple](https://materialdesignicons.com/icon/hexagon-multiple)](https://materialdesignicons.com/icon/hexagon-multiple)

We already have a `chart-scatterplot-hexbin` icon.

[![chart-scatterplot-hexbin](https://materialdesignicons.com/icon/chart-scatterplot-hexbin)](https://materialdesignicons.com/icon/chart-scatterplot-hexbin)

**Comment by ayozebarrera** [comment]
Thanks, Yes I know we have the chart icon but I said those bars are not needed always

**Comment by Templarian** [comment]
It can be useful for games that use a hexagon tiles also. Why I kept the name more generic. 😄
