### ISSUE TITLE
syringe icon

### ISSUE THREAD

**Issue by resper** [Templarian/MaterialDesign#1761]
Searching for a syringe icon and other medical themed icons (nurse, doctor etc)

Greetings
Markus

**Comment by Templarian** [comment]
[![needle](https://materialdesignicons.com/icon/needle)](https://materialdesignicons.com/icon/needle)

?

**Comment by PeterShaggyNoble** [comment]
A few more medical icons:

![](https://materialdesignicons.com/icon/ambulance) ![](https://materialdesignicons.com/icon/heart-pulse) ![](https://materialdesignicons.com/icon/hospital) ![](https://materialdesignicons.com/icon/hospital-building) ![](https://materialdesignicons.com/icon/hospital-marker) ![](https://materialdesignicons.com/icon/pharmacy)  ![](https://materialdesignicons.com/icon/pill)  ![](https://materialdesignicons.com/icon/pulse)  ![](https://materialdesignicons.com/icon/stethoscope)

**Comment by resper** [comment]
Searched for syringe or injection. Thx for the fast reaction.

**Comment by Templarian** [comment]
@resper Reopening until I add the alias for `syringe` this will make it easier for future searches.

**Comment by GreenTurtwig** [comment]
Given alias `syringe`.
@Templarian seems you forgot. ;-)
