### ISSUE TITLE
network icon without anything inside

### ISSUE THREAD

**Issue by llkyull** [Templarian/MaterialDesign#1763]
Requesting a network icon without an x, -, or + as the fill

**Comment by Templarian** [comment]
[![network](https://materialdesignicons.com/icon/network)](https://materialdesignicons.com/icon/network) [![network-question](https://materialdesignicons.com/icon/network-question)](https://materialdesignicons.com/icon/network-question) [![network-download](https://materialdesignicons.com/icon/network-download)](https://materialdesignicons.com/icon/network-download) [![network-download](https://materialdesignicons.com/icon/network-download)](https://materialdesignicons.com/icon/network-download)

There were a couple missing ones that should have been added earlier also.
