### ISSUE TITLE
Contribution: Filter icon

### ISSUE THREAD

**Issue by burnmail123** [Templarian/MaterialDesign#1764]
I'm using filter icons with number 1,3:
[https://materialdesignicons.com/icon/numeric-1-box-multiple-outline](https://materialdesignicons.com/icon/numeric-1-box-multiple-outline)
[https://materialdesignicons.com/icon/numeric-3-box-multiple-outline](https://materialdesignicons.com/icon/numeric-3-box-multiple-outline)
 and I need also "Show all" icon in same style. So I created this one [http://imgur.com/a/O9huj](http://imgur.com/a/O9huj), as the empty box was not suitable for me.

Maybe you could add it to collection.

Greetings,
Patrik

**Comment by MrGrigri** [comment]
Number inside of a box, to me, doesn't symbolize a filter, but more the number of items.

**Comment by burnmail123** [comment]
Yeah, could be also that. Basically after click on that only 3 items will
be displayed. Therefore I needed something to display all of them.

**Comment by PeterShaggyNoble** [comment]
[`library books`](https://materialdesignicons.com/icon/library-books) should fulfil this request.
