### ISSUE TITLE
octahedron

### ISSUE THREAD

**Issue by Laim0n** [Templarian/MaterialDesign#1768]
We need quality material icon octahedron
Please

**Comment by MrGrigri** [comment]
Here is my attempt.

![octahedron](https://cloud.githubusercontent.com/assets/4528551/21993234/0c741376-dbd7-11e6-831a-f999704a3166.png)

[octahedron.zip](https://github.com/Templarian/MaterialDesign/files/709052/octahedron.zip)

**Comment by Templarian** [comment]
That's definitely an "odd" icon to represent in the MD style. I don't think there is a right way to handle this.

The above contribution by @MrGrigri is probably the closest we could get to this 3D representation.

**Comment by MrGrigri** [comment]
@Templarian My thoughts exactly

**Comment by Templarian** [comment]
I'm closing this as it's too specific right now without being included. Thanks @MrGrigri for the contribution.

**Comment by JapanYoshi** [comment]
Isn't there a d8 icon already? It was a 45° square with an 8 in it.

**Comment by PeterShaggyNoble** [comment]
You mean this?

![](https://materialdesignicons.com/icon/dice-d8)

**Comment by Laim0n** [comment]
![image](https://cloud.githubusercontent.com/assets/25152332/22989017/4488fec4-f3c5-11e6-9aae-79d7d790fa46.png)
material version, please

**Comment by Templarian** [comment]
Yea, the `dice-d8` needs to be a diamond shape, but should suffice for this icon. I don't think we have the room to do a true 3D shape.
