### ISSUE TITLE
Icon class page-layout-footer not working

### ISSUE THREAD

**Issue by gtzinos** [Templarian/MaterialDesign#1769]
I use more of your icons in my project but when i use class = "mdi mdi-page-layout-footer", icon not appear.

**Comment by ButchMonkey** [comment]
Doesn't look like this has been released yet.
You can see which icons have been added since the last release on the [history ](https://materialdesignicons.com/history)page.

**Comment by gtzinos** [comment]
Okay when you will release this icon ?

**Comment by gtzinos** [comment]
This icon is in your release history.

**Comment by gtzinos** [comment]
Yes, i can see that not released yet. Can you tell me when it will be released ?

**Comment by ButchMonkey** [comment]
Well... @Templarian hasn't announced it but....

I believe this is the link you want for CDN - http://cdn.materialdesignicons.com/1.8.36/css/materialdesignicons.min.css

**Comment by gtzinos** [comment]
Thank you !!!

**Comment by Templarian** [comment]
Nah, it's fine. Just going through testing phase right now. Bower/NPM will be updated in the next day or so once I have a second. So far everything looks okay.
