### ISSUE TITLE
screen-lock and screen-lock-off icon request

### ISSUE THREAD

**Issue by rabross** [Templarian/MaterialDesign#1770]
Request for icons representing if screen timeout is enabled or disabled.

**Comment by MrGrigri** [comment]
This is my best attempt. I believe that `screen-lock` and `screen-lock-off` would be a better terminology with it keeping the same idea. 

![screen-timeout](https://cloud.githubusercontent.com/assets/4528551/22037152/560afc5c-dcb3-11e6-88ea-cee309dab093.png) ![screen-timeout-off](https://cloud.githubusercontent.com/assets/4528551/22037151/560ad70e-dcb3-11e6-981c-938c3967e71d.png)

[screen-timeout.zip](https://github.com/Templarian/MaterialDesign/files/712149/screen-timeout.zip)

**Comment by rabross** [comment]
Thanks for the quick response.
Timeout may not have been the best description. What I mean is when the device sleeps/screen turns off after a certain period. So I was more thinking of an icon that could incorporate a clock or something that communicates a timeout.

**Comment by MrGrigri** [comment]
I tried it with a clock, stopwatch, and even hourglass; however, none of those looked good and they didn't scale down well enough to fit inside of or next to the laptop. When I think of a screen timeout I think of it locking. But I guess that's not always the case.

**Comment by JamesCoyle** [comment]
Android uses a filled version of cellphone with a circle in the middle. The circle changes from a 1/4 circle to  half circle to 3/4 circle depending on what screen on time is selected.

**Comment by MrGrigri** [comment]
@JamesCoyle That's very abstract and I don't believe that clearly designates a timeout.

**Comment by rabross** [comment]
It is a difficult behavior to capture.
@JamesCoyle That sounds interesting. Could you please link me to an example?

**Comment by MrGrigri** [comment]
What are the thoughts about renaming this thread to `screen-lock and screen-lock-off icon request` and having these two added into the repository? Then @rabross can implement @JamesCoyle's idea for a screen-timeout process.

**Comment by rabross** [comment]
@MrGrigri No problems from me

**Comment by waternexus** [comment]
@MrGrigri How did you make those sweet icon previews?!

**Comment by PeterShaggyNoble** [comment]
@waternexus, you can create a preview of any icon by linking to its page, thusly:

`![alt text](https://materialdesignicons.com/icon/icon-name)`

So, for exmaple:

`![Material Design format-quote icon](https://materialdesignicons.com/icon/format-quote)`

Outputs:

![format-quote](https://materialdesignicons.com/icon/format-quote)

**Comment by MrGrigri** [comment]
@waternexus, what @PeterShaggyNoble said is true for the Material Design Community icons, but the ones that I create and haven't been uploaded yet, I make the PNG and post it here. That's why they are blue and not gray. You can see this by clicking on the image and see where it takes you.

Use the syntax `![name](http://example.com/image.png)` for all images.

**Comment by Templarian** [comment]
[![monitor-lock](https://materialdesignicons.com/monitor-lock)](https://materialdesignicons.com/monitor-lock)
