### ISSUE TITLE
Viber icon

### ISSUE THREAD

**Issue by test55353** [Templarian/MaterialDesign#1771]
Guys

Could you make viber icon, please

Thank in advance,
You make BEST icon material design !!!!

**Comment by PeterShaggyNoble** [comment]
See [#1157](https://github.com/Templarian/MaterialDesign/issues/1157).

**Comment by test55353** [comment]
Thank Peter for the reference.

**Comment by Templarian** [comment]
We need to split that issue up into separate issues. Lets close out #1157 and make issues for the remaining ones.

**Comment by PeterShaggyNoble** [comment]
Wikimedia has an SVG of the full logo [here](https://upload.wikimedia.org/wikipedia/commons/d/d4/Viber_logo.svg).

**Comment by PeterShaggyNoble** [comment]
Official SVGs are now available [here](https://www.viber.com/brand-center/).

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
