### ISSUE TITLE
Icon: eye-outline (thinner)

### ISSUE THREAD

**Issue by ashughes** [Templarian/MaterialDesign#1772]
The recently added eye-outline icon (https://materialdesignicons.com/icon/eye-outline) feels too thick compared to other outline icons (e.g. https://materialdesignicons.com/icon/heart-outline or https://materialdesignicons.com/icon/comment-outline). I couldn't figure out how to link to just a search for "outline".

**Comment by Templarian** [comment]
That's odd, the outline is not 2px. I could have sworn I set the line width to 2px. This is a bug. Not sure how I didn't notice that (probably processing too many icons for the 1.8.36 release).

**Comment by Templarian** [comment]
This has been fixed for the 1.8.36 release that is going out tomorrow.
