### ISSUE TITLE
Ninja Icon Request

### ISSUE THREAD

**Issue by donhurickerby** [Templarian/MaterialDesign#1773]
Requesting a ninja icon. Thanks!

**Comment by MrGrigri** [comment]
Here are two that I came up with `ninja` and `ninja-vigilant`. I used the same eye position as face to keep them consistent. 


![ninja](https://cloud.githubusercontent.com/assets/4528551/22075296/ba899bba-dd68-11e6-9656-a1daa8341d2d.png) ![ninja-vigilant](https://cloud.githubusercontent.com/assets/4528551/22075295/ba84fd6c-dd68-11e6-99d7-d0c9e17cca26.png)

[ninja.zip](https://github.com/Templarian/MaterialDesign/files/714550/ninja.zip)

**Comment by donhurickerby** [comment]
This is excellent, thanks!

**Comment by Templarian** [comment]
I don't think we need two versions of `ninja`.  Kind of leaning toward the `jinja-vigilant` one. What do you two think?

@MrGrigri @donhurickerby ?

**Comment by JapanYoshi** [comment]
Maybe just use a shuriken (throwing star). That's simpler and more emblematic.

**Comment by MrGrigri** [comment]
@JapanYoshi I believe that a ninja would be useful for an alternative to incognito.

@Templarian I don't really have an opinion on which one get used. I believe that the `ninja-vigilant` could better represent both a ninja and vigilance. So maybe that one.

**Comment by PeterShaggyNoble** [comment]
My vote foes to `ninja-vigilant` too. Nice work, @MrGrigri.

**Comment by JapanYoshi** [comment]
Don't get me wrong, ``ninja`` looks perfectly good. But can't the borders of the eye opening be more pixel-aligned?

**Comment by Templarian** [comment]
[![ninja](https://materialdesignicons.com/icon/ninja)](https://materialdesignicons.com/icon/ninja)

Cleaned up the point data. Please double check before uploading @MrGrigri.

Awesome, thanks guys!
