### ISSUE TITLE
Update Nearby Icon

### ISSUE THREAD

**Issue by vicmns** [Templarian/MaterialDesign#1774]
Hey Guys, can you update the [google-nearby](https://materialdesignicons.com/icon/google-nearby) icon to the new one that google is using: [Nearby](https://developers.google.com/nearby/images/ic_nearby_white_2x_web_48dp.png)

Thanks in advance!

**Comment by MrGrigri** [comment]
How's this?

![google-nearby](https://cloud.githubusercontent.com/assets/4528551/22080595/617efa28-dd7d-11e6-940c-e3f60f0787a3.png)

[google-nearby.zip](https://github.com/Templarian/MaterialDesign/files/714885/google-nearby.zip)

**Comment by vicmns** [comment]
Perfect! Many thanks 👍

**Comment by Templarian** [comment]
[![google-nearby](https://materialdesignicons.com/icon/google-nearby)](https://materialdesignicons.com/icon/google-nearby)

Updated, not sure how this slipped through. Thanks!
