### ISSUE TITLE
Request: YouTube and Instagram Boxed

### ISSUE THREAD

**Issue by paulflo150** [Templarian/MaterialDesign#1775]
I am using the boxed version as social icons in emails, and it would be great to have a boxed version of the YouTube and Instagram icons as well so that they all look the same.

Thanks!

**Comment by Templarian** [comment]
I know it would be useful, but these icons do not really look or look nice in the smaller size (similarly why we rejected instagram-circle).

One suggestion would be to use the base icon and render the shape behind the various icons.
