### ISSUE TITLE
Xbox One Controller Battery Icon Request

### ISSUE THREAD

**Issue by zsKengren** [Templarian/MaterialDesign#1776]
I am looking for a couple of icons for the XBoxOne Controller Battery
* Controller Battery Full
* Battery Medium
* Battery Low
* Battery Empty
* Battery Unknown

I have taken a stab at creating them myself based on the current xbox controller and the battery icon already included in the project. I am not by any means an icon designer and didn't know my behind from my head when it came to using the templates.

ControllerBatteryFull: "M 39.544922 1066.5195 L 39.544922 1072.1172 L 34.869141 1072.1172 A 3.7228813 3.7228813 0 0 0 31.146484 1075.8418 L 31.146484 1087.0879 L 20.775391 1087.1328 C 19.834969 1086.2807 18.633453 1085.9302 17.359375 1085.8848 C 13.537143 1085.7483 9.0664062 1088.3516 9.0664062 1088.3516 L 7.8222656 1090.6523 L 7.1152344 1090.6523 C -4.198115 1114.2073 0.042543172 1122.5195 5.6992188 1122.5195 C 11.355893 1119.7484 13.478091 1113.5137 19.134766 1113.5137 L 31.146484 1113.334 L 31.146484 1118.7812 C 31.146484 1120.8247 32.825755 1122.502 34.869141 1122.502 L 61.013672 1122.502 A 3.7228813 3.7228813 0 0 0 64.736328 1118.7812 L 64.736328 1075.8418 C 64.736328 1073.7984 63.057055 1072.1172 61.013672 1072.1172 L 56.339844 1072.1172 L 56.339844 1066.5195 L 39.544922 1066.5195 z M 28.328125 1089.2656 C 29.860835 1089.2656 31.100161 1090.4624 31.146484 1091.9531 L 31.146484 1092.1211 C 31.100159 1093.6118 29.860835 1094.8086 28.328125 1094.8086 C 26.76608 1094.8086 25.498047 1093.5676 25.498047 1092.0371 C 25.498044 1090.5066 26.76608 1089.2656 28.328125 1089.2656 z "

ControllerBatteryMedium: "M 39.544922 1066.5195 L 39.544922 1072.1172 L 34.869141 1072.1172 A 3.7228813 3.7228813 0 0 0 31.146484 1075.8418 L 31.146484 1087.0879 L 20.775391 1087.1328 C 19.834969 1086.2807 18.633453 1085.9302 17.359375 1085.8848 C 13.537143 1085.7483 9.0664062 1088.3516 9.0664062 1088.3516 L 7.8222656 1090.6523 L 7.1152344 1090.6523 C -4.198115 1114.2073 0.042543172 1122.5195 5.6992188 1122.5195 C 11.355893 1119.7484 13.478091 1113.5137 19.134766 1113.5137 L 31.146484 1113.334 L 31.146484 1118.7812 C 31.146484 1120.8247 32.825755 1122.502 34.869141 1122.502 L 61.013672 1122.502 A 3.7228813 3.7228813 0 0 0 64.736328 1118.7812 L 64.736328 1075.8418 C 64.736328 1073.7984 63.057055 1072.1172 61.013672 1072.1172 L 56.339844 1072.1172 L 56.339844 1066.5195 L 39.544922 1066.5195 z M 36.746094 1077.7168 L 59.138672 1077.7168 L 59.138672 1091.2148 L 36.746094 1091.2148 L 36.746094 1077.7168 z M 28.328125 1089.2656 C 29.860835 1089.2656 31.100161 1090.4624 31.146484 1091.9531 L 31.146484 1092.1211 C 31.100159 1093.6118 29.860835 1094.8086 28.328125 1094.8086 C 26.76608 1094.8086 25.498047 1093.5676 25.498047 1092.0371 C 25.498044 1090.5066 26.76608 1089.2656 28.328125 1089.2656 z "

ControllerBatteryLow: "M 39.544922 1066.5195 L 39.544922 1072.1172 L 34.869141 1072.1172 A 3.7228813 3.7228813 0 0 0 31.146484 1075.8418 L 31.146484 1087.0879 L 20.775391 1087.1328 C 19.834969 1086.2807 18.633453 1085.9302 17.359375 1085.8848 C 13.537143 1085.7483 9.0664062 1088.3516 9.0664062 1088.3516 L 7.8222656 1090.6523 L 7.1152344 1090.6523 C -4.198115 1114.2073 0.042543172 1122.5195 5.6992188 1122.5195 C 11.355893 1119.7484 13.478091 1113.5137 19.134766 1113.5137 L 31.146484 1113.334 L 31.146484 1118.7812 C 31.146484 1120.8247 32.825755 1122.502 34.869141 1122.502 L 61.013672 1122.502 A 3.7228813 3.7228813 0 0 0 64.736328 1118.7812 L 64.736328 1075.8418 C 64.736328 1073.7984 63.057055 1072.1172 61.013672 1072.1172 L 56.339844 1072.1172 L 56.339844 1066.5195 L 39.544922 1066.5195 z M 36.746094 1077.7168 L 59.138672 1077.7168 L 59.138672 1104.5195 L 36.746094 1104.5195 L 36.746094 1077.7168 z M 28.328125 1089.2656 C 29.860835 1089.2656 31.100161 1090.4624 31.146484 1091.9531 L 31.146484 1092.1211 C 31.100159 1093.6118 29.860835 1094.8086 28.328125 1094.8086 C 26.76608 1094.8086 25.498047 1093.5676 25.498047 1092.0371 C 25.498044 1090.5066 26.76608 1089.2656 28.328125 1089.2656 z "

ControllerBatteryEmpty: "m 58.990234,1.9902344 v 7.5585937 h -6.3125 a 5.0267717,5.0267717 0 0 0 -5.027343,5.0273439 v 15.185547 l -14.003907,0.06055 C 32.376692,28.671689 30.75351,28.200059 29.033203,28.138672 23.872284,27.95451 17.835938,31.46875 17.835938,31.46875 L 16.15625,34.574219 H 15.201172 C -0.07453023,66.378768 5.6531639,77.603516 13.291016,77.603516 20.928867,73.861802 23.79379,65.443359 31.431641,65.443359 l 16.21875,-0.24414 v 7.355469 c 0,2.759055 2.268288,5.02539 5.027343,5.02539 h 35.300782 a 5.0267717,5.0267717 0 0 0 5.027343,-5.02539 V 14.576172 c 0,-2.759055 -2.268288,-5.0273439 -5.027343,-5.0273439 h -6.3125 V 1.9902344 Z M 55.210938,17.109375 H 85.447266 V 70.021484 H 55.210938 Z M 43.84375,32.703125 c 2.069521,0 3.744094,1.616077 3.806641,3.628906 v 0.226563 c -0.06255,2.01283 -1.73712,3.628906 -3.806641,3.628906 -2.109135,0 -3.820312,-1.675696 -3.820312,-3.742188 -10e-7,-2.06649 1.711177,-3.742187 3.820312,-3.742187 z"

ControllerBatteryUnknown: "M 39.544922 1066.5195 L 39.544922 1072.1172 L 34.869141 1072.1172 A 3.7228813 3.7228813 0 0 0 31.146484 1075.8418 L 31.146484 1087.0879 L 20.775391 1087.1328 C 19.834969 1086.2807 18.633453 1085.9302 17.359375 1085.8848 C 13.537143 1085.7483 9.0664062 1088.3516 9.0664062 1088.3516 L 7.8222656 1090.6523 L 7.1152344 1090.6523 C -4.198115 1114.2073 0.042543172 1122.5195 5.6992188 1122.5195 C 11.355893 1119.7484 13.478091 1113.5137 19.134766 1113.5137 L 31.146484 1113.334 L 31.146484 1118.7812 C 31.146484 1120.8247 32.825755 1122.502 34.869141 1122.502 L 61.013672 1122.502 A 3.7228813 3.7228813 0 0 0 64.736328 1118.7812 L 64.736328 1075.8418 C 64.736328 1073.7984 63.057055 1072.1172 61.013672 1072.1172 L 56.339844 1072.1172 L 56.339844 1066.5195 L 39.544922 1066.5195 z M 36.746094 1077.7168 L 59.138672 1077.7168 L 59.138672 1116.9043 L 36.746094 1116.9043 L 36.746094 1077.7168 z M 47.066406 1082.8516 C 45.816406 1082.8516 44.488281 1082.9948 43.082031 1083.2812 C 41.688802 1083.5547 40.536458 1083.8672 39.625 1084.2188 L 39.625 1088.2031 L 39.820312 1088.2031 C 40.549479 1087.7474 41.539063 1087.2982 42.789062 1086.8555 C 44.052083 1086.4128 45.386719 1086.1914 46.792969 1086.1914 C 48.36849 1086.1914 49.651042 1086.556 50.640625 1087.2852 C 51.643229 1088.0013 52.144531 1089.0951 52.144531 1090.5664 C 52.144531 1091.6862 51.936198 1092.6107 51.519531 1093.3398 C 51.102865 1094.056 50.516927 1094.7526 49.761719 1095.4297 C 49.136719 1096.0156 48.329427 1096.5951 47.339844 1097.168 C 46.363281 1097.7409 45.451823 1098.2682 44.605469 1098.75 L 44.605469 1104.707 L 48.101562 1104.707 L 48.101562 1100.3125 C 49.169271 1099.7005 50.178385 1099.069 51.128906 1098.418 C 52.079427 1097.7669 52.919271 1097.0703 53.648438 1096.3281 C 54.390625 1095.5599 54.989583 1094.681 55.445312 1093.6914 C 55.901042 1092.6888 56.128906 1091.5495 56.128906 1090.2734 C 56.128906 1088.0469 55.315104 1086.2565 53.6875 1084.9023 C 52.072917 1083.5352 49.865885 1082.8516 47.066406 1082.8516 z M 28.328125 1089.2656 C 29.860835 1089.2656 31.100161 1090.4624 31.146484 1091.9531 L 31.146484 1092.1211 C 31.100159 1093.6118 29.860835 1094.8086 28.328125 1094.8086 C 26.76608 1094.8086 25.498047 1093.5676 25.498047 1092.0371 C 25.498044 1090.5066 26.76608 1089.2656 28.328125 1089.2656 z M 44.429688 1108.3984 L 44.429688 1112.5195 L 48.414062 1112.5195 L 48.414062 1108.3984 L 44.429688 1108.3984 z "

**Comment by Templarian** [comment]
Can you please zip and attach the icons as .svg to save us some time previewing these.

**Comment by zsKengren** [comment]
I am really sorry if this is not exactly what you are looking for. I put the icon in the template that was provided on the site. 
[Icons.zip](https://github.com/Templarian/MaterialDesign/files/717767/Icons.zip)

**Comment by Templarian** [comment]
![image](https://cloud.githubusercontent.com/assets/338885/22127144/4a0d2ea8-de60-11e6-99b9-d8e61530e074.png)

I think you may have aligned these wrong or scaled them wrong. Could fix this, but it could take a while.

**Comment by zsKengren** [comment]
Does the svg not scale? Below is a picture of what i see.

![path3694](https://cloud.githubusercontent.com/assets/6874149/22127552/eea9a580-de61-11e6-9419-a902b2e4d61b.png)

**Comment by Templarian** [comment]
Nah, but each icon needs to be built off the MD [guidelines](https://material.io/guidelines/style/icons.html#icons-system-icons).

We can fix them before the are added, but was giving you the opportunity.

**Comment by Templarian** [comment]
[![xbox-controller-battery-alert](https://materialdesignicons.com/icon/xbox-controller-battery-alert)](https://materialdesignicons.com/icon/xbox-controller-battery-alert) [![xbox-controller-battery-unknown](https://materialdesignicons.com/icon/xbox-controller-battery-unknown)](https://materialdesignicons.com/icon/xbox-controller-battery-unknown) [![xbox-controller-battery-low](https://materialdesignicons.com/icon/xbox-controller-battery-low)](https://materialdesignicons.com/icon/xbox-controller-battery-low) [![xbox-controller-battery-medium](https://materialdesignicons.com/icon/xbox-controller-battery-medium)](https://materialdesignicons.com/icon/xbox-controller-battery-medium) [![xbox-controller-battery-full](https://materialdesignicons.com/icon/xbox-controller-battery-full)](https://materialdesignicons.com/icon/xbox-controller-battery-full) [![xbox-controller-battery-empty](https://materialdesignicons.com/icon/xbox-controller-battery-empty)](https://materialdesignicons.com/icon/xbox-controller-battery-empty)

**Comment by zsKengren** [comment]
I appreciate the opportunity to get them fixed but I really have no idea what I am doing. Honestly, this was the first time I have ever needed an icon made and in the future would love to learn more about icon making. I really appreciate you making the icons.

**Comment by Templarian** [comment]
Yours gave a good starting point. Feel free to suggest more in the future (I was in the middle of playing Xbox is why I added it, pretty useful for those that use the set for games).

**Comment by zsKengren** [comment]
For sure, I am not sure if you ever use your xbox controller for emulator but once i get my program onto github i will shoot you a link. It is basically a overlay screen for accessing different emulators and computer controls without having to use the keyboard.
