### ISSUE TITLE
Bucket

### ISSUE THREAD

**Issue by itspatricyall** [Templarian/MaterialDesign#1777]
Hey it would be very nice if was add to the project icons for milking process such:

- Hand milking
- Milking machine
- Milk bucket
- Full-body Cow

and etc.

Thank you

**Comment by Templarian** [comment]
These are very specific and difficult to make at the small size.

**Comment by PeterShaggyNoble** [comment]
I've updated the title of this to be a request for a bucket icon (or should we close this and open a new issue for a bucket?)

**Comment by Templarian** [comment]
Closing this out as `bucket` and `pail` were added. Agreed the others are going to be too specific.
