### ISSUE TITLE
Icon Request: Google Analytics

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1781]
A request for the [Google Analytics](https://analytics.google.com/analytics/web/) icon. SVG file can be found [here](https://ssl.gstatic.com/analytics/header/legacy/v1/ic_analytics.svg).

Branched from [#1157](https://github.com/Templarian/MaterialDesign/issues/1157).

**Comment by PeterShaggyNoble** [comment]
Here's a single colour SVG I extracted from that:

    <svg version="1.1" viewBox="0 0 192 192" xmlns="http://www.w3.org/2000/svg">
        <path d="M159.8,20h-27.7c-6.7,0-12.2,5.5-12.2,12.2V68l-40.1,0C73.3,68,68,73.3,68,79.9V120H31.9 c-6.6,0-11.9,5.3-11.9,11.9v28c0,6.6,5.3,11.9,11.9,12.1H120h12.2l0,0h27.7c6.7,0,12.2-5.5,12.2-12.2V32.2 C172,25.5,166.5,20,159.8,20z"/>
    </svg>

**Comment by Templarian** [comment]
[![google-analytics](https://materialdesignicons.com/icon/google-analytics)](https://materialdesignicons.com/icon/google-analytics)

**Comment by PeterShaggyNoble** [comment]
Ooo, my first contribution 🙂
