### ISSUE TITLE
Icon Request: MySQL

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1782]
Don't know if the [MySQL](https://www.mysql.com/) dolphin icon will fit within the MD guidelines.

Wikipedia has an [SVG](https://en.wikipedia.org/wiki/File:MySQL.svg) of the logo and official EPS files can be found [here](https://www.mysql.com/about/legal/logos.html).

Branched from [#1157](https://github.com/Templarian/MaterialDesign/issues/1157).

**Comment by MrGrigri** [comment]
I believe that it will not as well.

**Comment by PeterShaggyNoble** [comment]
Yeah, I'll close it for now.

**Comment by CoDEmanX** [comment]
Generic SQL logo used by Google: https://github.com/Templarian/MaterialDesign/issues/271#issuecomment-203333290

I think I submitted an icon based on that a long time ago...
