### ISSUE TITLE
Yahoo

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1783]
A request for the [Yahoo](https://www.yahoo.com/) icon. SVG file can be found [here](https://s.yimg.com/os/mit/media/p/common/images/favicon_new-7483e38.svg).

Branched from [#1157](https://github.com/Templarian/MaterialDesign/issues/1157).

**Comment by artursmirnov** [comment]
+1

**Comment by Templarian** [comment]
[![yahoo](http://materialdesignicons.com/icon/yahoo)](http://materialdesignicons.com/icon/yahoo)
