### ISSUE TITLE
Icon: math

### ISSUE THREAD

**Issue by AravK** [Templarian/MaterialDesign#1785]
Something like a square root with a cursive 'x' inside?

**Comment by MrGrigri** [comment]
Would [this](https://github.com/Templarian/MaterialDesign/issues/1725) work?

**Comment by PeterShaggyNoble** [comment]
There are a few other icons that might work to represent maths as well. Have look in the [symbols category of my sandbox](https://houseofdesign.ie/sandbox/mdi/?category=characters).

Some suggestions:

![](https://materialdesignicons.com/icon/division) ![](https://materialdesignicons.com/icon/equal) ![](https://materialdesignicons.com/icon/sigma)

**Comment by JapanYoshi** [comment]
An icon showing "±√" would probably be one of the better ways to concisely illustrate mathematics.

**Comment by PeterShaggyNoble** [comment]
Doing a little research and it looks to me like the most common ways to represent maths in an icon are pi, a calculator, sigma or a 2*2 grid containing some combination of the plus, minus, multiplcation, division & equals symbols.

**Comment by PeterShaggyNoble** [comment]
`square-root`has been added, fulfilling the original request.

![](https://materialdesignicons.com/icon/square-root)
