### ISSUE TITLE
Icon Request: Periscope

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1786]
A request for the [Periscope](https://www.periscope.tv/) icon. SVG file can be found [here](https://www.periscope.tv/v/images/largepin.svg) and EPS files are available on [this page](https://www.periscope.tv/press).

Branched from [#1157](https://github.com/Templarian/MaterialDesign/issues/1157#issuecomment-259186741) on behalf of @albertogasparin.

**Comment by GreenTurtwig** [comment]
Here: 
[periscope.zip](https://github.com/Templarian/MaterialDesign/files/726678/periscope.zip)

:smile_cat:

**Comment by Templarian** [comment]
[![periscope](https://materialdesignicons.com/icon/periscope)](https://materialdesignicons.com/icon/periscope)

Awesome!
