### ISSUE TITLE
Icon Request: Agreement, Assessment, Ticket, Coordinators

### ISSUE THREAD

**Issue by h4h13** [Templarian/MaterialDesign#1787]
i was thinking about these icons

**Comment by PeterShaggyNoble** [comment]
There are already a few ticket icons in the library. What did you have in mind for the others? Got any examples?

![](https://materialdesignicons.com/icon/ticket) ![](https://materialdesignicons.com/icon/ticket-account) ![](https://materialdesignicons.com/icon/ticket-confirmation)

**Comment by h4h13** [comment]
Hi, Movie, Metro, Bus etc.


________________________________

**Comment by goyney** [comment]
There are too many ideas flowing around in this issue. Additionally, we have icons that should solve each of the four original suggestions:

- Agreement - Any of the `signature(-*)` icons, `certificate`
- Assessment - `format-list-checks`, `format-list-checkbox`
- Ticket - See above
- Coordinators - `account-group`, `account-supervisor`, `account-tie`

And then the following three:

- Movie - `filmstrip`, `movie-roll`
- Metro - `subway`
- Bus - `bus(-*)`

If you have other icons you need that we don't have, please open up a new request, one per idea. Thanks!
