### ISSUE TITLE
Google Fit Scales Icons

### ISSUE THREAD

**Issue by MaximilianKeppeler** [Templarian/MaterialDesign#1788]

**Comment by Croutonix** [comment]
Like this?
![image](https://cloud.githubusercontent.com/assets/18645219/22179509/f0d84762-e023-11e6-9d87-6dcd30c27f55.png)

**Comment by MaximilianKeppeler** [comment]
I meant a "recording weight" - icon. Sorry. 

![screenshot_20170122-083107](https://cloud.githubusercontent.com/assets/15075376/22181919/a5636716-e097-11e6-88ef-52ab9a6655ac.png)

**Comment by PeterShaggyNoble** [comment]
That's a scale, not a weight. A few options you could use:

![](https://materialdesignicons.com/icon/scale-bathroom) ![](https://materialdesignicons.com/icon/speedometer) ![](https://materialdesignicons.com/icon/gauge) ![](https://materialdesignicons.com/icon/scale) ![](https://materialdesignicons.com/icon/scale-balance)

**Comment by MaximilianKeppeler** [comment]
Oh ok, then I searched after the wrong word. Thanks. (Thought I wish to have the Google Fit weight scale, since it does fit better.)

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/38939594-2fd9912c-4320-11e8-9afa-ea38aa209291.png)](https://github.com/Templarian/MaterialDesign/files/1924559/weight-fitness.zip)

**Comment by goyney** [comment]
This is a duplicate of #2547.
