### ISSUE TITLE
Exponent and Root

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1789]
I'm sure this was part of a request at some point but I can't seem to find these icons. An `x²` and `√x` would be really useful. Could also use a decimal point (the dot talked about in #1709 would work), and a degree symbol like `x°`.

**Comment by JamesCoyle** [comment]
#1522

**Comment by PeterShaggyNoble** [comment]
![](https://materialdesignicons.com/icon/format-superscript)

**Comment by JamesCoyle** [comment]
I knew I'd seen it somewhere. @Templarian can we alias with exponent and square?

**Comment by Templarian** [comment]
Please add the `alias` label for these types of issues. Need to focus on getting these in.

**Comment by Templarian** [comment]
Added `square-root` and the alias `exponent` added.

[![square-root](https://materialdesignicons.com/icon/square-root)](https://materialdesignicons.com/icon/square-root)
