### ISSUE TITLE
Upvote/Downvote

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1790]
We don't seem to have the solid style arrow commonly seen as upvote and downvote icons. Like upload and download but without the underline.

**Comment by vishnu1991** [comment]
@JamesCoyle  Maybe these icons can be used for upvote and downvote!?
![arrow-down-drop-circle-outline](https://cloud.githubusercontent.com/assets/6689768/22184574/4d26d368-e0fa-11e6-88bc-c6d671db657b.png)
![arrow-up-drop-circle-outline](https://cloud.githubusercontent.com/assets/6689768/22184575/4d26e2fe-e0fa-11e6-97ee-639039b41f1d.png)


[Upvote](https://materialdesignicons.com/icon/arrow-up-drop-circle-outline)
[Downvote](https://materialdesignicons.com/icon/arrow-down-drop-circle-outline)

**Comment by JamesCoyle** [comment]
There are plenty that could be used for it but we are missing a common style of arrow.

**Comment by Templarian** [comment]
What do you mean by a common style? I think it would depend on the application which style they went with. We added several new arrows in the latest release.

**Comment by Templarian** [comment]
Oh, you mean https://materialdesignicons.com/icon/arrow-down-bold-circle-outline without the circle styled. Yea, we don't have icons like that. Should probably add those.

**Comment by JamesCoyle** [comment]
Yup.

**Comment by Templarian** [comment]
@JamesCoyle I think you found a bug in the naming... `arrow-*-bold` icons should be called `arrow-*-thick`. We'll have to fix this in the next release along with adding `arrow-*-bold-box` variants that are missing.

**Comment by Templarian** [comment]
Below is the idea... need to add the other 3 directions/renames.

[![arrow-down-thick](https://materialdesignicons.com/icon/arrow-down-thick)](https://materialdesignicons.com/icon/arrow-down-thick) [![arrow-down-bold](https://materialdesignicons.com/icon/arrow-down-bold)](https://materialdesignicons.com/icon/arrow-down-bold) [![arrow-down-bold-box](https://materialdesignicons.com/icon/arrow-down-bold-box)](https://materialdesignicons.com/icon/arrow-down-bold-box) [![arrow-down-bold-box-outline](https://materialdesignicons.com/icon/arrow-down-bold-box-outline)](https://materialdesignicons.com/icon/arrow-down-bold-box-outline)

**Comment by Templarian** [comment]
https://materialdesignicons.com/history All renames are done and all 12 new arrow icons are in.
