### ISSUE TITLE
Highlighter icon

### ISSUE THREAD

**Issue by Mancerrss** [Templarian/MaterialDesign#1791]
Like this. Needed for drawing interface http://www.iconshock.com/img_vista/FLAT/text/jpg/highlighter_icon.jpg

**Comment by PeterShaggyNoble** [comment]
![](https://materialdesignicons.com/icon/marker)

**Comment by CoDEmanX** [comment]
Do we need an alias for this?

**Comment by PeterShaggyNoble** [comment]
Alias added.
