### ISSUE TITLE
Looking for Chart manipulation icons

### ISSUE THREAD

**Issue by bebenins** [Templarian/MaterialDesign#1792]
Hello,
I'm looking for a family of icons as pictured below.  This is standard Chart manipulation icons from National Instruments library.  Obviously they don't have to be identical but they need to look as if they came from the same "family".  We already have the Zoom In/Out buttons so that's not needed.
I started working on it using your template (in AI) but wanted to hear your opinions first.  I kinda have hard time with the actual chart plot line (massaging it to fit and look good).  The stroke size changes with size of the object and I'd like it to be uniform.
Anyway, comment welcome please!
Thanks!

![image](https://cloud.githubusercontent.com/assets/16761301/22184070/f715218e-e098-11e6-956c-85606f1411a5.png)

**Comment by CoDEmanX** [comment]
[![magnify-plus-outline](https://materialdesignicons.com/icon/magnify-plus-outline)](https://materialdesignicons.com/icon/magnify-plus-outline) [![magnify-minus-outline](https://materialdesignicons.com/icon/magnify-minus-outline)](https://materialdesignicons.com/icon/magnify-minus-outline)

For panning we only have the following at the moment:

[![cursor-move](https://materialdesignicons.com/icon/cursor-move)](https://materialdesignicons.com/icon/cursor-move)

Hm, strange that we don't have left-right (horizontal) and up-down (vertical) pointing arrows...

**Comment by PeterShaggyNoble** [comment]
One these might suit for "zoom to fit":

![](https://materialdesignicons.com/icon/arrow-expand) ![](https://materialdesignicons.com/icon/arrow-expand-all) ![](https://materialdesignicons.com/icon/fullscreen)

**Comment by CoDEmanX** [comment]
Meanwhile, panning icons and general purpose arrow icons pointing in 8 different directions are available.
So the question is if we want to add specific chart icons for zooming etc. (the last 4 examples in the original post).

**Comment by goyney** [comment]
I'm going to vote that the last 4 are too niche and can be served with other, more generic icons already included.

**Comment by CoDEmanX** [comment]
Meanwhile we added e.g. `arrow-top-left-bottom-right` and several `pan` icons, which should cover this.

![grafik](https://user-images.githubusercontent.com/1309249/61858782-12e17080-aec7-11e9-8b43-f7c63641cfab.png)
![grafik](https://user-images.githubusercontent.com/1309249/61858811-2096f600-aec7-11e9-9149-73003e8884a5.png)
![grafik](https://user-images.githubusercontent.com/1309249/61858838-2d1b4e80-aec7-11e9-81e2-de19c973b37c.png)
![grafik](https://user-images.githubusercontent.com/1309249/61858850-37d5e380-aec7-11e9-8898-dc39aa2698f9.png)

...
