### ISSUE TITLE
air-filter

### ISSUE THREAD

**Issue by mariniertje** [Templarian/MaterialDesign#1793]
environment parameters are used for automation of smart homes, and icons are required for the UI

Please add more icons related to environmental parameters and weather

Here is a great collection for more subtle variety in weather conditions and environmental parameters: https://erikflowers.github.io/weather-icons/

**Comment by CoDEmanX** [comment]
wi-alien?! 👽 

We already have a bunch of icons like that. What icons do you miss in particular?

**Comment by mariniertje** [comment]
Something that combines an icon for air (i.e. cloud or fan or wind) with an
icon for quality (not sure what would be best to use as a symbol/icon for
that).

It should be part of a weather/environment package, but haven't found an
icon yet that fits the bill and is unambiguous)

**Comment by Templarian** [comment]
That would probably be an alert of some sort. `!`. But cloud+alert just looks like a storm warning. Same with wind+alert. Not sure what would best represent it.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48365156-1a822180-e678-11e8-96f8-60c12074f9b0.png)
[air-filter.zip](https://github.com/Templarian/MaterialDesign/files/2572965/air-filter.zip)

**Comment by Templarian** [comment]
[![air-filter](https://materialdesignicons.com/icon/air-filter)](https://materialdesignicons.com/icon/air-filter)
