### ISSUE TITLE
Icon request: parcel delivery services

### ISSUE THREAD

**Issue by mariniertje** [Templarian/MaterialDesign#1794]
It would be awesome if you can add icons (logos) for all parcel delivery services, i.e.:

- [ ] USPS
- [ ] UPS
- [ ] FedEx
- [ ] TNT
- [ ] DPD
- [ ] DHL
- [ ] OnTrac
- [x] Amazon

**Comment by vishnu1991** [comment]
- [ ] USPS
- [ ] UPS
- [ ] FedEx
- [ ] TNT
- [ ] DPD
- [ ] DHL
- [ ] OnTrac
- [x] Amazon https://materialdesignicons.com/icon/amazon

**Comment by Templarian** [comment]
I'm not sure if this is something we can get in due to the size constraints.

**Comment by GreenTurtwig** [comment]
Also different countries have different couriers, all with their own branding guidelines, and some of their "icons" just wouldn't fit easily. (Royal Mail for example).

**Comment by Templarian** [comment]
Yea, I'm going to rejected this since there is no way we can add them all and if we can only add one or two it isn't really that useful. I would also say it's best to follow their guidelines and I doubt they allow presenting their logos as such small size.
