### ISSUE TITLE
Duplicate Icon burst-mode/camera-burst

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#1795]
I don't know if this is important, but I noticed "[burst-mode](https://materialdesignicons.com/icon/burst-mode)" and "[camera-burst](https://materialdesignicons.com/icon/camera-burst)" share the same icon. I just want to leave this information here.

**Comment by Templarian** [comment]
That is a bug. Thanks for pinting it out. camera-burst is the correct one. `burst-mode` will be removed eventually.

**Comment by PeterShaggyNoble** [comment]
This has been rectified.
