### ISSUE TITLE
Shield Half Outline

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#1796]
Here is 'shield-half-outline' that I found was missing.
[shield-half-outline.zip](https://github.com/Templarian/MaterialDesign/files/726773/shield-half-outline.zip)
![puush-linux 2017-01-24 at 01 25 55](https://cloud.githubusercontent.com/assets/15905797/22248949/e02cdbf0-e238-11e6-80fd-3aaf21d8bf7c.png)
![puush-linux 2017-01-24 at 01 26 31](https://cloud.githubusercontent.com/assets/15905797/22248954/e1b09d7c-e238-11e6-9492-3dd9cda2be11.png)

**Comment by CoDEmanX** [comment]
Out of curiosity: What do you use this variant for?

**Comment by JamesCoyle** [comment]
Useful for an armor durability scale in games.

**Comment by GreenTurtwig** [comment]
Yep, helpful to go together with the half heart, i.e. Minecraft. ;-)

**Comment by Templarian** [comment]
[![heart-half-full](https://materialdesignicons.com/icon/shield-half-full)](https://materialdesignicons.com/icon/shield-half-full)

We're getting a decent amount of RPG like icons.

**Comment by GreenTurtwig** [comment]
I'm beginning to think I should create a l web app with all of these, not sure for what yet though.

**Comment by JapanYoshi** [comment]
The shield and half-shield can be useful to notate network protection levels.
