### ISSUE TITLE
Not all Google icons are implemented

### ISSUE THREAD

**Issue by IchordeDionysos** [Templarian/MaterialDesign#1797]
I searched for `offline pin` but I didn't found it, same goes for `motorcycle`.

Would be great to implement them :D

**Comment by Templarian** [comment]
We have a different version before they added one it appears. https://materialdesignicons.com/motorbike

The `pin` icon probably won't be included. We generally do not include text based icons.

`offline` needs to be added, but will probably be called something else. Not sure that name fits that icon, but we can add a alias.

**Comment by IchordeDionysos** [comment]
Why don't you include all Google icons? 🤔

**Comment by IchordeDionysos** [comment]
Because of that I have to search on two different sites... :/

**Comment by Templarian** [comment]
We do most of them. Remember this project has been around longer than the official one 😄. We add icons and so does Google so there is always some not synced. We just sync in the ones the community finds useful rather than all of them. Continue to open issues for icons you need that are missing.

We alias icons to make finding the official ones easier also (our naming standards are much more noun based). The new site being build at the moment should solve some of these issues.

**Comment by carlosbensant** [comment]
Another icon which is missing is the `"touch app"` icon. Speaking of which, how do you decide which icons are included in the project?

**Comment by Templarian** [comment]
@carlosbensant Pure dictator style generally. But our awesome contributors have _often_ changed my mind. 😃

**Comment by CoDEmanX** [comment]
> Text based icons are not used because this pack is heavily internationally used. So English only icons are generally removed.

cough "case"-sensitive cough

![](https://materialdesignicons.com/icon/case-sensitive-alt)

**Comment by Templarian** [comment]
@CoDEmanX Punny, but yea we should remove that icon in an upcoming release.

**Comment by JamesCoyle** [comment]
@Templarian Perhaps it would be a good idea to go through the icons and make sure they all conform to the guidelines, are named appropriately, and add any missing icons and remove redundant ones. We would then release it as an MDI V2.0.0 along with the new site. I worry about removing/renaming too many icons between releases as its easy to change a file over to the new version but hard to check an entire project for icon errors if they aren't expected.

**Comment by CoDEmanX** [comment]
Visual Studio 2015:

![image](https://cloud.githubusercontent.com/assets/1309249/22622908/20dd7574-eb49-11e6-9680-55dab24575fa.png)

(case sensitive, match words, regex)

**Comment by Templarian** [comment]
@JamesCoyle I think we'll have maybe 2 releases before `v2.0.0` There will be 2k icons, if 4 of them get renamed in that time it should be fine. Most are either using static or npm defined resources, so it shouldn't impact too much (I'm still using `v1.7.22` at work).

There is still a lot to code before the new site releases I'm not sure the timetable for that yet.

@CoDEmanX Yea, I think replacing the icon and renaming it would be a good idea. That's a good icon `Aa`.

**Comment by PeterShaggyNoble** [comment]
`offline pin` is being tracked in #2520 and `motorcycle` in #2660 so closing this one out.
