### ISSUE TITLE
Touch Gestures

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1798]
I'm going to link to all of the other Issues that reference touch gestures. I have come up with a few of them. Let me know what y'all think.

`gesture-tap`, `gesture-double-tap`, `gesture-two-finger-tap`, `gesture-swipe-up`, `gesture-swipe-down`, `gesture-swipe-left`, `gesture-swipe-right`.

![gesture-tap](https://cloud.githubusercontent.com/assets/4528551/22271269/eb09500e-e250-11e6-8d69-1d611b2f6979.png) ![gesture-double-tap](https://cloud.githubusercontent.com/assets/4528551/22271274/eb12c6fc-e250-11e6-9bcd-04df2a899723.png) ![gesture-two-finger-tap](https://cloud.githubusercontent.com/assets/4528551/22271270/eb09c372-e250-11e6-8b6b-6b19d070f54c.png) ![gesture-two-finger-double-tap](https://cloud.githubusercontent.com/assets/4528551/22271429/bd9b4112-e251-11e6-8f60-dd9ec57a27d5.png) ![gesture-swipe-up](https://cloud.githubusercontent.com/assets/4528551/22271272/eb101b78-e250-11e6-9dc3-0c9b8a979003.png) ![gesture-swipe-down](https://cloud.githubusercontent.com/assets/4528551/22271273/eb108b30-e250-11e6-8e4c-a64e4dba7250.png) ![gesture-swipe-left](https://cloud.githubusercontent.com/assets/4528551/22271276/eb1f4ca6-e250-11e6-8373-43d9b46ec534.png) ![gesture-swipe-right](https://cloud.githubusercontent.com/assets/4528551/22271275/eb1e274a-e250-11e6-8b18-04dbf4fc32b3.png)

[gesture.zip](https://github.com/Templarian/MaterialDesign/files/728209/gesture.zip)

#1728 #1254 #282

**Comment by Templarian** [comment]
Wanted to design these for a while. These will work perfectly for those creating tutorial overlays etc.

**Comment by MrGrigri** [comment]
@Templarian, I tried other ones, but the just didn't work (e.g. pinch, spread, rotate, etc).

**Comment by Templarian** [comment]
[![gesture-double-tap](https://materialdesignicons.com/icon/gesture-double-tap)](https://materialdesignicons.com/icon/gesture-double-tap) [![gesture-swipe-down](https://materialdesignicons.com/icon/gesture-swipe-down)](https://materialdesignicons.com/icon/gesture-swipe-down)  [![gesture-swipe-left](https://materialdesignicons.com/icon/gesture-swipe-left)](https://materialdesignicons.com/icon/gesture-swipe-left)  [![gesture-swipe-right](https://materialdesignicons.com/icon/gesture-swipe-right)](https://materialdesignicons.com/icon/gesture-swipe-right)  [![gesture-swipe-up](https://materialdesignicons.com/icon/gesture-swipe-up)](https://materialdesignicons.com/icon/gesture-swipe-up)  [![gesture-tap](https://materialdesignicons.com/icon/gesture-tap)](https://materialdesignicons.com/icon/gesture-tap)  [![gesture-two-double-tap](https://materialdesignicons.com/icon/gesture-two-double-tap)](https://materialdesignicons.com/icon/gesture-two-double-tap)  [![gesture-two-tap](https://materialdesignicons.com/icon/gesture-two-tap)](https://materialdesignicons.com/icon/gesture-two-tap)
