### ISSUE TITLE
Offer (Hand)

### ISSUE THREAD

**Issue by andunix** [Templarian/MaterialDesign#1799]
For representing offers I would like to suggest an icon which look like a hand which offers something.

**Comment by CoDEmanX** [comment]
For "offering a deal" something with file + signature might also work, but that is tracked here: #1040

**Comment by CoDEmanX** [comment]
Google's `volunteer-activism` minus the heart:

![grafik](https://user-images.githubusercontent.com/1309249/62692120-59a78e00-b9d0-11e9-8a94-3a1b1645fc04.png)

**Comment by Templarian** [comment]
Needs to be centered, but I think this works for `offer` (no `ing`'s in naming).

**Comment by goyney** [comment]
[![offer](https://materialdesignicons.com/icon/offer)](https://materialdesignicons.com/icon/offer)
