### ISSUE TITLE
Calculator icons

### ISSUE THREAD

**Issue by yegorf1** [Templarian/MaterialDesign#180]
Mathematic operations to create calculator. I know about special symbols, but will be cool if you'll create icon pack.
- [x] multiplication
- [x] multiplication-box
- [x] division
- [x] division-box
- [ ] plus-minus
- [ ] plus-minus-box
- [ ] minus-plus
- [ ] minus-plus-box
- [x] exponent
- [ ] exponent-box
- [x] square-root
- [ ] square-root-box
- [x] pie (mmm... pie)
- [x] pie-box
- [x] equal
- [x] equal-box

**Comment by Templarian** [comment]
Please list each symbol you are looking for and an example image.

**Comment by yegorf1** [comment]
Basic math operations (-, +, ×, ÷) and these: ^, √, π

**Comment by Templarian** [comment]
The minus and plus exist (with box variants). I added tasks above with all the icons that will be created.

**Comment by CoDEmanX** [comment]
![pi](https://cloud.githubusercontent.com/assets/1309249/11769097/ba12b6b4-a1df-11e5-914e-fe9bd5089942.png) https://www.dropbox.com/s/yiztiqmblofi2nf/pi.design?dl=0
![pi-box](https://cloud.githubusercontent.com/assets/1309249/11769098/ba14799a-a1df-11e5-82d3-0b8547a1398e.png) https://www.dropbox.com/s/8e9gpv43ainrhmc/pi-box.design?dl=0

**Comment by Templarian** [comment]
[![pi](https://materialdesignicons.com/icon/pi)](https://materialdesignicons.com/icon/pi) [![pi-box](https://materialdesignicons.com/icon/pi-box)](https://materialdesignicons.com/icon/pi-box)

**Comment by CoDEmanX** [comment]
These should do for +/-: ![minus-plus_ 180](https://cloud.githubusercontent.com/assets/1309249/14904379/2d93358a-0da8-11e6-9f28-a1d53e1ed29c.png) ![plus-minus_ 180](https://cloud.githubusercontent.com/assets/1309249/14904381/2db6d3d2-0da8-11e6-80dc-cb80b6692a4f.png) ![minus-plus-box_ 180](https://cloud.githubusercontent.com/assets/1309249/14904380/2daa03be-0da8-11e6-8e23-0b7e58ffb182.png) ![plus-minus-box_ 180](https://cloud.githubusercontent.com/assets/1309249/14904382/2db8e3b6-0da8-11e6-91a4-46d98d521641.png)

**Comment by amoh-godwin** [comment]
Check out these for the pi [pi.zip](https://github.com/Templarian/MaterialDesign/files/1845317/pi.zip)
and pi-box [pi_box.zip](https://github.com/Templarian/MaterialDesign/files/1845318/pi_box.zip)

**Comment by yegorf1** [comment]
But Pi icons are already done

**Comment by amoh-godwin** [comment]
Yea, but this is more like an enhanced version.

**Comment by CoDEmanX** [comment]
Yours do not follow the Material Design guidelines @amoh-godwin

**Comment by amoh-godwin** [comment]
I know. Will make it 24px

**Comment by amoh-godwin** [comment]
Now they do

**Comment by amoh-godwin** [comment]
Here is square-root-box 
![artboard 1](https://user-images.githubusercontent.com/18188576/37981754-70739f16-31e6-11e8-87f2-1cbd8f373c5b.png)
[square-root-box.zip](https://github.com/Templarian/MaterialDesign/files/1852920/square-root-box.zip)

**Comment by Croutonix** [comment]
Here's all the missing icons:
![image](https://user-images.githubusercontent.com/18645219/37999191-ba1cc8fa-31ef-11e8-86b6-dcde69a9f711.png)![image](https://user-images.githubusercontent.com/18645219/37999185-b369d6b0-31ef-11e8-97ed-8ee2d291d3ab.png)![image](https://user-images.githubusercontent.com/18645219/37999200-ca1a67f8-31ef-11e8-9ee9-7b8241508a09.png)![image](https://user-images.githubusercontent.com/18645219/37999210-d74b6710-31ef-11e8-8931-202494315a5b.png)![image](https://user-images.githubusercontent.com/18645219/37999231-ea19637e-31ef-11e8-95fd-b6a30a89f650.png)![image](https://user-images.githubusercontent.com/18645219/37999278-206ca562-31f0-11e8-8fa0-d03003f406dc.png)![image](https://user-images.githubusercontent.com/18645219/37999303-3b1dc602-31f0-11e8-8859-ad4345f7cc5b.png)![image](https://user-images.githubusercontent.com/18645219/37999325-4d61a5f4-31f0-11e8-8db0-aa1b3f8c9082.png)![image](https://user-images.githubusercontent.com/18645219/37999335-5b9c6d16-31f0-11e8-9d61-a43b6ff7fe47.png)![image](https://user-images.githubusercontent.com/18645219/37999356-69dcf3c8-31f0-11e8-99d1-e84fe30655ba.png)

Minus or plus isn't really necessary, there is already plus or minus. The contrast icons that are already in the pack don't have the right shape. Also all mathematical comparison operators are missing, we only have those in boxes, and they look more programming related. There is also already an icon for a square operation, but not for exponent.

[Download link](https://github.com/Templarian/MaterialDesign/files/1854057/icons.zip)

**Comment by amoh-godwin** [comment]
There is still more functions not listed that are found on the calculator

**Comment by PeterShaggyNoble** [comment]
@amoh-godwin, if there are additional calculator icons, other than the ones covered here, that you you would like to request, please open a new issue for each one.

**Comment by amoh-godwin** [comment]
Why is the project not completed? It really bothers me.

**Comment by Templarian** [comment]
@amoh-godwin It really bothers me too. 🤣 

[![not-equal](https://materialdesignicons.com/icon/not-equal)](https://materialdesignicons.com/icon/not-equal) [![not-equal](https://materialdesignicons.com/icon/not-equal-variant)](https://materialdesignicons.com/icon/not-equal-variant) [![greater-than-or-equal](https://materialdesignicons.com/icon/greater-than-or-equal)](https://materialdesignicons.com/icon/greater-than-or-equal)  [![less-than-or-equal](https://materialdesignicons.com/icon/less-than-or-equal)](https://materialdesignicons.com/icon/less-than-or-equal) [![greater-than](https://materialdesignicons.com/icon/greater-than)](https://materialdesignicons.com/icon/greater-than)  [![less-than](https://materialdesignicons.com/icon/less-than)](https://materialdesignicons.com/icon/less-than)

**Comment by Templarian** [comment]
[![exponent-box](https://materialdesignicons.com/icon/exponent-box)](https://materialdesignicons.com/icon/exponent-box) [![exponent](https://materialdesignicons.com/icon/exponent)](https://materialdesignicons.com/icon/exponent)

**Comment by Templarian** [comment]
[![plus-minus-box](https://materialdesignicons.com/icon/plus-minus-box)](https://materialdesignicons.com/icon/plus-minus-box) [![plus-minus](https://materialdesignicons.com/icon/plus-minus)](https://materialdesignicons.com/icon/plus-minus) [![square-root-box](https://materialdesignicons.com/icon/square-root-box)](https://materialdesignicons.com/icon/square-root-box)

**Comment by amoh-godwin** [comment]
Love you guys
