### ISSUE TITLE
Symbols (a lá alphabetical & numeric)

### ISSUE THREAD

**Issue by EvoWizz** [Templarian/MaterialDesign#1801]
Could you make a "symbol" icon like the alphabetical and the numeric ones please ?

**Comment by Templarian** [comment]
Do you have an example of what that would look like?

https://materialdesignicons.com/icon/omega Some apps use the `omega` symbol for this.

**Comment by EvoWizz** [comment]
Well I was thinking of an icon that looks like that " #?@ " (for example)

**Comment by goyney** [comment]
Most implementations for "symbols" use the `sigma` or `omega` glyphs. For example, Google Docs:

![Screen Shot 2019-06-24 at 9 41 20 PM](https://user-images.githubusercontent.com/1015040/60062878-eb7d6500-96c8-11e9-957b-02fe799e1064.png)

Would those work? I don't think an icon with several random symbols is really going to work very well.

**Comment by EvoWizz** [comment]
Those would actually work, indeed!

This was meant to be for an old project which is now abandoned. But your idea seems better and might correspond to what people are actually looking for.
