### ISSUE TITLE
Restaurant & Restaurant Menu

### ISSUE THREAD

**Issue by nmcardoso** [Templarian/MaterialDesign#1802]
The following icons are available in the google repository but not here:

Icon | Url
---|---
![Restaurant](https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_restaurant_black_24px.svg) | https://material.io/icons/#ic_restaurant
![Restaurant Menu](https://storage.googleapis.com/material-icons/external-assets/v4/icons/svg/ic_restaurant_menu_black_24px.svg) | https://material.io/icons/#ic_restaurant_menu

In _material.io_ I can't download the icon as _Vector Drawable_. :confused:

**Comment by PeterShaggyNoble** [comment]
![](https://materialdesignicons.com/icon/silverware) ![](https://materialdesignicons.com/icon/silverware-variant)

Also:

![](https://materialdesignicons.com/icon/silverware-fork) ![](https://materialdesignicons.com/icon/silverware-spoon) ![](https://materialdesignicons.com/icon/food-fork-drink)

**Comment by Templarian** [comment]
You guys think it's worthwhile to add the fork knife net to eachother icon? Seems a bit of a duplicate in a different style. 😐

**Comment by PeterShaggyNoble** [comment]
I'd vote yes, but only because it's a stock Google icon.

**Comment by MrGrigri** [comment]
I'm torn between the two. But since it is a Stock Google Icon, then I'm leaning that way. But I'm ok with either decision.

**Comment by Templarian** [comment]
Okay we'll include it then. I wasn't really strong either way, might as well.

**Comment by JamesCoyle** [comment]
Would it be worth altering `food-fork-drink` to better match the style of the other icons?

**Comment by MrGrigri** [comment]
I see `food-fork-drink` as `restaurant-fast-food` and the google stock icon as just `restaurant`

**Comment by Templarian** [comment]
[![silverware-fork-knife](https://materialdesignicons.com/icon/silverware-fork-knife)](https://materialdesignicons.com/icon/silverware-fork-knife)
