### ISSUE TITLE
Takeaway Box

### ISSUE THREAD

**Issue by Enorio** [Templarian/MaterialDesign#1803]
One icon that doesn't exist is a take away icon. Like a mc'donalds happy meal box

**Comment by PeterShaggyNoble** [comment]
Would the `hamburger` icon suit your needs?

![](https://materialdesignicons.com/icon/hamburger)

Another couple of options could be:

![](https://materialdesignicons.com/icon/food) ![](https://materialdesignicons.com/icon/pizza)

**Comment by Enorio** [comment]
Doesnt work because what i want is not a fast food type

To make a brief description, i have an app for restaurants, and a fast food icon doesnt work very well xD
So i thought a box icon its more appropiate for this kind of apps

**Comment by PeterShaggyNoble** [comment]
Google have since added `takeout_dining` to Material Icons Extended:

[![takeout_dining](https://user-images.githubusercontent.com/15157491/64870523-5ccf1300-d63b-11e9-91a6-5af90e5179ba.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by Xenomorph99** [comment]
I just noticed that the outline version is displayed in Google Maps

![google-maps](https://user-images.githubusercontent.com/1837101/110149870-c7c65980-7d9b-11eb-957b-e0eadc11a2aa.png)

![google-maps-close-up](https://user-images.githubusercontent.com/1837101/110149859-c5fc9600-7d9b-11eb-917e-65888869ba3c.png)

**Comment by goyney** [comment]
[![food-takeout-box](https://materialdesignicons.com/icon/food-takeout-box)](https://materialdesignicons.com/icon/food-takeout-box)[![food-takeout-box-outline](https://materialdesignicons.com/icon/food-takeout-box-outline)](https://materialdesignicons.com/icon/food-takeout-box-outline)
