### ISSUE TITLE
Icon Request: Farfetch

### ISSUE THREAD

**Issue by ElDany90** [Templarian/MaterialDesign#1805]
Hi,

I need this brand icon to use in my webapp. 

Can you add it? I can provide icon in .svg or .ai

Otherwise there is a way to add it by myself?

Thank you

**Comment by MrGrigri** [comment]
Just post the SVG in a zip file here and it'll be reviewed by the community. That is a very specific and not too popular brand icon.

**Comment by Templarian** [comment]
Sorry, had to lookup what this was. Social media icons only.
