### ISSUE TITLE
Pressure icon

### ISSUE THREAD

**Issue by Imp5pa** [Templarian/MaterialDesign#1806]
Hello, please make pressure icon like the image.
![pressure](https://cloud.githubusercontent.com/assets/16856372/22341408/02b8fbcc-e3f1-11e6-8089-144956f55b5b.png)

**Comment by PeterShaggyNoble** [comment]
Would the `gauge` or `speedometer` icons suit?

![](https://materialdesignicons.com/icon/gauge) ![](https://materialdesignicons.com/icon/speedometer)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of response from OP.
