### ISSUE TITLE
library_edit and library_remove icon request

### ISSUE THREAD

**Issue by archirex** [Templarian/MaterialDesign#1807]
I see add library/photos, but no edit/remove. Probably the box with a shadow, behind a generic pencil (for edit) and behind a minus (for remove). An alternative could include the trash can instead of the minus, but it might not fit well.

- [ ] library_edit
- [ ] library_remove
- [ ] library_delete

**Comment by archirex** [comment]
How do I label this?

**Comment by CoDEmanX** [comment]
The owner and the contributors do that.

A general note: we try to avoid adding variants of each and every icon (something + plus, something + minus, something + ...). In many cases, it is better to use the generic add and remove icons instead of combinations anyway.

**Comment by goyney** [comment]
[![library-minus](https://materialdesignicons.com/icon/library-minus)](https://materialdesignicons.com/icon/library-minus)
[![close-box-multiple](https://materialdesignicons.com/icon/close-box-multiple)](https://materialdesignicons.com/icon/close-box-multiple)

I've added the `library-close` and `library-remove` aliases to `close-box-multiple` as well.
