### ISSUE TITLE
Icon Request > More Sports Icons + Club Icons

### ISSUE THREAD

**Issue by Bennith** [Templarian/MaterialDesign#1809]
Would be nice to have these in the collection.
Like "Ball" icons or badges icons

**Comment by CoDEmanX** [comment]
Please add what icons you would be interested in exactly, and add sample images if possible.

**Comment by Templarian** [comment]
Closing this issue. Please add more details and we'll reopen the issue. But I believe we have individual icon requests for most sports related icons.
