### ISSUE TITLE
map-marker-multiple Clipping mask isn't the same as the marker itself

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#181]
I think the pointy end of the lower marker was clipped in a funny way, the curvature doesn't match the top marker's side. I thought it should look more like this:
![map-marker-multiple](https://cloud.githubusercontent.com/assets/5341898/6428196/c79c8c08-bf4d-11e4-9dab-38d61915b5bd.png)
(the anchor was moved and make it look out of balance, I hope you get what I mean)

**Comment by Templarian** [comment]
![map-marker-multiple](https://cloud.githubusercontent.com/assets/338885/6428284/b220409a-bf61-11e4-9056-5b9eee7787f3.png)

Closer to this?

**Comment by danielhickman** [comment]
**Steps to Make What I thought looked nice:**
![map-marker-multiple1](https://cloud.githubusercontent.com/assets/5341898/6428424/2461fb6e-bf56-11e4-9db5-280b140abda5.png)
![map-marker-multiple2](https://cloud.githubusercontent.com/assets/5341898/6428422/2454be7c-bf56-11e4-9948-e5c6d69c783c.png)
![map-marker-multiple3](https://cloud.githubusercontent.com/assets/5341898/6428423/24574250-bf56-11e4-9166-2b90bd10480c.png)
![map-marker-multiple4](https://cloud.githubusercontent.com/assets/5341898/6428420/245315ea-bf56-11e4-946a-4f5c837793e4.png)
![map-marker-multiple5](https://cloud.githubusercontent.com/assets/5341898/6428421/24540630-bf56-11e4-9251-007833371249.png)
![map-marker-multiple6](https://cloud.githubusercontent.com/assets/5341898/6428418/24500e86-bf56-11e4-89c5-1b0b862414c7.png)
![map-marker-multiple7](https://cloud.githubusercontent.com/assets/5341898/6428419/24516e8e-bf56-11e4-9812-46acdd3d8ded.png)
Maybe the whitespace between the two should be even the whole way around.

**Comment by Templarian** [comment]
They use even spacing on all their icons. That is what the image I shown was doing. Simply using one to cut out the other leaves the top looking off.

http://cl.ly/image/2b1F2J3y1z1I
![image](https://cloud.githubusercontent.com/assets/338885/6428477/53c75d1e-bf69-11e4-90ff-99efe4e55b80.png)
