### ISSUE TITLE
printer-check

### ISSUE THREAD

**Issue by ruslanfedoseenko** [Templarian/MaterialDesign#1810]
For apps wihtch implement batch printing I need an icon with printer and a check mark or smth simular.
Thanks for you great work!

**Comment by ruslanfedoseenko** [comment]
I mean smth like this 
![image](https://cloud.githubusercontent.com/assets/4517707/22373760/47a9eab6-e4b4-11e6-9e65-565e11c83905.png)

**Comment by terreng** [comment]
Here are two possible check mark versions

![image](https://user-images.githubusercontent.com/11605395/62887131-80780400-bcf1-11e9-8337-b728e026aad3.png)
[printer-check-1.svg](https://github.com/terreng/samples/blob/master/printer-check-1.svg)

![image](https://user-images.githubusercontent.com/11605395/62887151-8f5eb680-bcf1-11e9-8b68-b9804b151bf2.png)
[printer-check-2.svg](https://github.com/terreng/samples/blob/master/printer-check-2.svg)

**Comment by goyney** [comment]
[![printer-check](https://materialdesignicons.com/icon/printer-check)](https://materialdesignicons.com/icon/printer-check)
