### ISSUE TITLE
Google Home Icon

### ISSUE THREAD

**Issue by kylerw** [Templarian/MaterialDesign#1811]
As seen in the Google Home App

**Comment by kylerw** [comment]
The voice activated speaker, icon.

**Comment by MrGrigri** [comment]
Like this one? If so multi-tone icons don't work.

![image](https://cloud.githubusercontent.com/assets/4528551/22377275/7b0ca916-e46e-11e6-8270-a1db863fd7ff.png)

**Comment by kylerw** [comment]
I would be ok with that one (basic tones) but I was thinking more along the lines of:

![image](https://cloud.githubusercontent.com/assets/370860/22377390/ed56620a-e46e-11e6-8f55-d8fc655b2eab.png)

**Comment by kylerw** [comment]
From the Play Store screenshots:

![image](https://cloud.githubusercontent.com/assets/370860/22377423/17ec85a8-e46f-11e6-899d-78baa262968d.png)

**Comment by CoDEmanX** [comment]
Looks like a short lipstick to me 💄

**Comment by ferdydek** [comment]
for Google Home App
[google-home-bw.zip](https://github.com/Templarian/MaterialDesign/files/920528/google-home-bw.zip)
(first time contribution, any instructions/info/directions welcomed)

**Comment by k5cents** [comment]
I like this for a home icon. Basically just a solid monotone version of the above. I think the shape is unique enough to be used over the regular "home" icon.

![home](https://cloud.githubusercontent.com/assets/18021678/26746665/004df054-47bf-11e7-9912-27d8f3d2ed65.png)

**Comment by kevinwilson1979** [comment]
This is the 24dp PNG that is used in Google's apps, in case it helps anyone looking to make a version of it.
![quantum_ic_google_home_grey600_24](https://cloud.githubusercontent.com/assets/7277690/26811125/c0163ac2-4a67-11e7-8092-58df2a3a429b.png)

**Comment by Templarian** [comment]
[![google-home](https://materialdesignicons.com/icon/google-home)](https://materialdesignicons.com/icon/google-home)
