### ISSUE TITLE
Waiter

### ISSUE THREAD

**Issue by Enorio** [Templarian/MaterialDesign#1813]
One icon that i see in other sites but not in here is this:

[![](https://user-images.githubusercontent.com/15157491/37039476-7fd14bb8-214f-11e8-8b49-65c4879c6e67.png)](http://icons.iconarchive.com/icons/icons8/android/512/Food-Waiter-icon.png)

**Comment by augustofontes** [comment]
+1

**Comment by PeterShaggyNoble** [comment]
We have the `room-service` icon, which should fulfil this request.
