### ISSUE TITLE
Icon Name Fixes

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1814]
I don't know how I made this mistake on two icons. But I noticed as I was writing the formal naming guidelines going forward. I know them pretty well, but it will be nice to have them written down.

- [x] `eye-outline-off` ... `eye-off-outline`
- [x] `cloud-outline-off` ... `cloud-off-outline`

**Comment by Templarian** [comment]
For anyone curious or wants to help the docs are in markdown format.

https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/contribute-naming.md You can edit directly in GitHub and submit pull requests if you want to help expand any of the pages.

**Comment by CoDEmanX** [comment]
Talking about icon names... what if wanted two variants of an icon? Would it be called `-variant2` or something? Or are you strictly against adding two alternatives?

**Comment by Templarian** [comment]
@CoDEmanX We generally would find another name to call it or really we try not to add it. `cake` is a great example of this.
