### ISSUE TITLE
I want useful icon 

### ISSUE THREAD

**Issue by eijidaiw** [Templarian/MaterialDesign#1815]

**Comment by brainscript** [comment]
**What?**

**Comment by JamesCoyle** [comment]
We want useful icon requests. Can you make it clear what it is you are requesting and provide an example?

**Comment by PeterShaggyNoble** [comment]
You can find almost 1900 useful icons right [here](https://materialdesignicons.com/)!

**Comment by CoDEmanX** [comment]
An icon that represents usefulness?!

**Comment by eijidaiw** [comment]
I want to the icons are meant to be useful.
I'm sorry I can not make you understand.

**Comment by Templarian** [comment]
This thread 😆

**Comment by CoDEmanX** [comment]
Is he asking how to use the MDI icons maybe?
