### ISSUE TITLE
HumbleBundle icon

### ISSUE THREAD

**Issue by brainscript** [Templarian/MaterialDesign#1816]
MDI already has a `steam` icon, but no [`humble-bundle`](https://humblebundle.com/) (which is quite popular) icon so far. Some lines of [the icon I extracted from their icon font](https://gist.github.com/brainscript/fe399dafcce203897963ab8357b45710) seem to be too thin in my eyes to fit into the icon pack and need to be modified a bit to make the icon look good when the it is used with a small font size.

<img src="https://cdn.rawgit.com/brainscript/fe399dafcce203897963ab8357b45710/raw/50bac23d8415948719c54be1bac98fd90e815f75/humble-bundle.svg" width="128">
<img src="https://cdn.rawgit.com/brainscript/fe399dafcce203897963ab8357b45710/raw/50bac23d8415948719c54be1bac98fd90e815f75/humble-bundle.svg" width="24">

There's also a load of unnecessary meta data in my SVG generated by Inkscape.

**Comment by Templarian** [comment]
We generally vector icons by hand to reduce extra point data.This looks like a fairly simple icon so it should reduce to the small size fine and still be visible.

**Comment by Templarian** [comment]
146 points to 52 points.

[![hubmle-bundle](https://materialdesignicons.com/icon/humble-bundle)](https://materialdesignicons.com/icon/humble-bundle)

**Comment by brainscript** [comment]
@Templarian Awesome, thanks! :smile:
