### ISSUE TITLE
Icon for invite

### ISSUE THREAD

**Issue by kishankhatri** [Templarian/MaterialDesign#1817]
Hi Friends, 

If you have a icon to be used for an INVITE of any sort, please do share.

Cheers!

**Comment by brainscript** [comment]
@kishankhatri What about these?
- [`account-plus`](https://materialdesignicons.com/icon/account-plus)
- [`account-multiple-plus`](https://materialdesignicons.com/icon/account-multiple-plus)
- [`email`](https://materialdesignicons.com/icon/email)
- [`contact-mail`](https://materialdesignicons.com/icon/contact-mail)

**Comment by Templarian** [comment]
I think the above are good suggestions. Please re-open with an example image if these will not work.

Thanks!
