### ISSUE TITLE
utilities missing :before

### ISSUE THREAD

**Issue by bartmelton** [Templarian/MaterialDesign#1818]
The utility classes, such as "mdi-flip-horizontal" need ":before" on them to affect the icon.

**Comment by Templarian** [comment]
That makes sense we will need to make this change in a future version. We've diverged slightly from `font-awesome` 2 versions ago. So we'll need to add the `::before` to each of these including the rotation classes.

**Comment by Templarian** [comment]
This was fixed already. Should have been closed.
