### ISSUE TITLE
File-account to complement folder-account

### ISSUE THREAD

**Issue by graemedownes** [Templarian/MaterialDesign#1819]
First off, great work!

Just wondering if you have any plans on creating a file icon with the account symbol similar to that of the [folder-account](https://materialdesignicons.com/icon/folder-account) icon. I'm creating a file explorer and it would be nice to use the "file-account" to signify a shared file as well.

Thanks

**Comment by Templarian** [comment]
[![file-account](https://materialdesignicons.com/icon/file-account)](https://materialdesignicons.com/icon/file-account)
