### ISSUE TITLE
Update Icon: Beats

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1820]
The [Beats by Dre](https://www.beatsbydre.com/) logo now has a circle in the centre, rather than a triangle. SVG can be found [here](http://demandware.edgesuite.net/aajh_prd/on/demandware.static/Sites-beats-IE-Site/-/en_IE/v1483648029504/images/Logo_01.svg).

![](https://materialdesignicons.com/icon/beats)

**Comment by Templarian** [comment]
Updated (after a day or so the above image's cache will update).
