### ISSUE TITLE
Icon Request: Realex Payments

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1821]
I've a feeling this one may be too specific and probably won't fit the MD style but I'm throwing it up on the off-chance.

SVGs can be found [here](https://www.realexpayments.com/wp-content/uploads/2015/06/rxp_logo1.svg) and [here](https://developer.realexpayments.com/assets/images/branding/realex/logo.svg)

**Comment by Templarian** [comment]
Think more social media type brand icons. This is too specific.

**Comment by PeterShaggyNoble** [comment]
Fair enough :thumbsup:

My own use case is for a website control panel but I can make do with a more generic icon.
