### ISSUE TITLE
Icon Request: Door

### ISSUE THREAD

**Issue by pmontgo33** [Templarian/MaterialDesign#1822]
Maybe a few different door images?

**Comment by CoDEmanX** [comment]
It's pretty hard to depict given the MD restrictions (no perspective!)

**Comment by MrGrigri** [comment]
Google MD specifications state "Don’t tilt, rotate, or make icons appear dimensional." There are a few exceptions to that rule like [archive](https://material.io/icons/#ic_archive) or our own [stadium](https://materialdesignicons.com/icon/stadium). What exactly are you going to use a door icon for?

**Comment by pmontgo33** [comment]
I'm using these icons in Home Assistant, and I was thinking for my back
door light it would be good to have a door as the icon.

Thanks for looking into this!

sent from my mobile device

**Comment by CoDEmanX** [comment]
Maybe along these lines:

![image](https://cloud.githubusercontent.com/assets/1309249/22516733/097d9f0c-e8a7-11e6-817f-c7f4c00f9dba.png)
![image](https://cloud.githubusercontent.com/assets/1309249/22516759/20bc4010-e8a7-11e6-910e-914b210d8c61.png)

**Comment by Templarian** [comment]
The second design actually fits pretty nice for MD.

**Comment by pmontgo33** [comment]
I like the first one better. Maybe something that looked like a 2 panel or
6 panel door? This is really not a huge deal to me, and I don't want to
make extra work for anyone. I was able to find basically every other icon I
needed and didn't see a door. Just figured I'd make the suggestion.

That being said I really appreciate how quickly you guys jumped on this.

-Pat

sent from my mobile device

**Comment by magicus** [comment]
I have a similar use case in Home Assistant, but I'd like to be able to differentiate between an open and a closed door.

Showing an open door seems problematic if you are not allowed to show any kind of dimensionality. :( On the other hand, there are icons like book-open-page-variant (from Google) which come close to depicting what I'd like to see in an open-door icon.

**Comment by JapanYoshi** [comment]
I made some door icons. Yes, I know not many doors open 180 degrees, but in Material Land they do. ;)

![door-closed](https://cloud.githubusercontent.com/assets/8707990/23705824/ee999eac-044e-11e7-9822-1880311b65a2.png)![door-open](https://cloud.githubusercontent.com/assets/8707990/23705826/ee9f5a36-044e-11e7-9592-994765b4cccc.png)
![door-closed 10x](https://cloud.githubusercontent.com/assets/8707990/23705825/ee9e45a6-044e-11e7-8d9d-93a7cfb590e4.png)![door-open 10x](https://cloud.githubusercontent.com/assets/8707990/23705827/eea3f636-044e-11e7-8eb1-6e03201748a0.png)

(Taller version that kiiiinda doesn't look the right size)

![door-closed](https://cloud.githubusercontent.com/assets/8707990/23705750/a49043f6-044e-11e7-9028-9502c6c483fd.png)![door-open](https://cloud.githubusercontent.com/assets/8707990/23705752/a498aeba-044e-11e7-91d0-2731241a6dfd.png)
![door-closed 10x](https://cloud.githubusercontent.com/assets/8707990/23705751/a4959b94-044e-11e7-97a3-2e9e001b5275.png)![door-open 10x](https://cloud.githubusercontent.com/assets/8707990/23705753/a49a004e-044e-11e7-8b47-b3a72f8d9a6f.png)

**Comment by JapanYoshi** [comment]
I'll make a simple door icon if it is necessary, like the closed door icon without the long bottom bar signifying the floor.

**Comment by lindsaymarkward** [comment]
Thank you. I'm looking for a door to signify "rooms" in Home Assistant. Open and Closed versions would be great.

**Comment by magicus** [comment]
@JapanYoshi I think it'd be useful to have three icons, "door" (without the bottom bar), "open-door" and "closed-door". I think your icons look very good, both the short and the tall versions. If anything, the door handle in the open version is very close to the edge, which makes it look a bit weird in small sizes.

**Comment by james-fry** [comment]
Hey folks.
I was after open/closed door icons too, and didnt see this thread and went and designed some too.

[door.zip](https://github.com/Templarian/MaterialDesign/files/924546/door.zip)

**Comment by metbril** [comment]
@james-fry Your example https://github.com/Templarian/MaterialDesign/issues/1822#issuecomment-294373555 has a 3D effect. Is this allowed in the style guide?

**Comment by metbril** [comment]
Example image:

## Closed
![closed](https://image.flaticon.com/icons/svg/59/59807.svg)

## Open 
![open](https://image.flaticon.com/icons/svg/59/59865.svg)

**Comment by metbril** [comment]
I am no designer at all, but why not keep it plain and simple. A closed door is visible as a black panel. An open door is just the surrounding door style. LIke this:

![door](https://cloud.githubusercontent.com/assets/559346/25693529/13afef3e-30aa-11e7-86c6-402bfb8fe2e5.png)

**Comment by JapanYoshi** [comment]
[door.zip](https://github.com/Templarian/MaterialDesign/files/975691/door.zip)
Sorry for the big delay. I've made a door by itself, as well as the two door icons I posted.

**Comment by coogle** [comment]
So quick question here - this icon is great but it doesn't actually appear when you search on the site - when does that actually happen?

**Comment by GreenTurtwig** [comment]
This issue is still open, so it hasn't been added to the set yet. There are quite a few issues with designing a "door" in material design.

**Comment by aderusha** [comment]
What remains to be done in order to make this happen?  As noted back in January, there are other examples where perspective has been used in the existing icon set for limited cases.  We have several submissions to chose from here in the thread.  What else needs to happen to get this approved?

**Comment by JapanYoshi** [comment]
Reposting my suggestion.
![](https://cloud.githubusercontent.com/assets/8707990/23705825/ee9e45a6-044e-11e7-8d9d-93a7cfb590e4.png)![](https://cloud.githubusercontent.com/assets/8707990/23705827/eea3f636-044e-11e7-8eb1-6e03201748a0.png)
[Download.](https://github.com/Templarian/MaterialDesign/files/975691/door.zip)

**Comment by mnl1121** [comment]
Any update on this? I want to use a door open/closed icon in Home Assistant. I like JapanYoshi's suggestion.

**Comment by Templarian** [comment]
[![door](https://materialdesignicons.com/icon/door)](https://materialdesignicons.com/icon/door) [![door-pen](https://materialdesignicons.com/icon/door-open)](https://materialdesignicons.com/icon/door-open) [![door-closed](https://materialdesignicons.com/icon/door-closed)](https://materialdesignicons.com/icon/door-closed)

Sorry for the delay everyone.

**Comment by james-fry** [comment]
Looks nice. thanks

**Comment by CoDEmanX** [comment]
Found this icon in Google calendar app:

![screenshot_20180116-111735_01](https://user-images.githubusercontent.com/1309249/34983988-9cae6bf6-faaf-11e7-8d85-9a565865e492.jpg)

**Comment by MrGrigri** [comment]
I still like ours better. 😄

**Comment by GreenTurtwig** [comment]
I personally like Google's design better, but it doesn't have "open" and "closed" variations like ours. :-P

**Comment by Templarian** [comment]
Specifically for the use of home automation I the open and closed distinction seems to be key for the usage.

I'm not sure if we need a more generic one though. Thoughts?

**Comment by MrGrigri** [comment]
I don't think so, If anything, I would add the floor to the current `door` icon like this.

![door](https://materialdesignicons.com/icon/door) ![image](https://user-images.githubusercontent.com/4528551/35010136-242610a2-fabf-11e7-8ed7-e6295d16140c.png)

[door.zip](https://github.com/Templarian/MaterialDesign/files/1636636/door.zip)

**Comment by GreenTurtwig** [comment]
I'd think it be best to add it as a variant, has a better design  personally.  
And yeah, updating the door icon as @MrGrigri has above seems like a good idea.

**Comment by JapanYoshi** [comment]
I'm all for that door update. Could work better with square corners, but might not. Material Design has a squared style now, so that Google icon might be from that.
