### ISSUE TITLE
Document Management Icons

### ISSUE THREAD

**Issue by larsm11** [Templarian/MaterialDesign#1823]
Icons for various document operations would be useful:
- Check-in document
- Check-out document
- Forward document
- Discard document (change)
- Approve document
- Acknowledge document (confirm that document has been read)

**Comment by CoDEmanX** [comment]
Check-in:
[![file-import](https://materialdesignicons.com/icon/file-import)](https://materialdesignicons.com/icon/file-import)

Check-out:
[![file-export](https://materialdesignicons.com/icon/file-export)](https://materialdesignicons.com/icon/file-export)

Foward:
[![file-send](https://materialdesignicons.com/icon/file-send)](https://materialdesignicons.com/icon/file-send)

Discard / change: not sure how this could look like. Couldn't find any existing file icon for these.

Approve:
[![file-check](https://materialdesignicons.com/icon/file-check)](https://materialdesignicons.com/icon/file-check)

Acknowledge: Maybe file + eye?

Related: https://github.com/Templarian/MaterialDesign/issues/1240#issuecomment-222284418

**Comment by larsm11** [comment]
Excellent.

Discard - maybe something with a stop sign or similar

**Comment by MrGrigri** [comment]
Here's an option for `file-discard`. 

For `file-acknowledge`, see this issue: https://github.com/Templarian/MaterialDesign/issues/1240. File with eye.

![file-discard](https://cloud.githubusercontent.com/assets/4528551/22712676/f60e3422-ed42-11e6-88c1-7e7b69ca10be.png)

[file-discard.zip](https://github.com/Templarian/MaterialDesign/files/759082/file-discard.zip)

**Comment by CoDEmanX** [comment]
Dunno if it's a glitch in the preview but it doesn't seem to be on grid.

The arrow tail looks a bit too thin at original size.

**Comment by Templarian** [comment]
^Fixed. Going to call this `file-undo`. But alias of `file-revert` and `file-discard`.

[![file-undo](https://materialdesignicons.com/icon/file-undo)](https://materialdesignicons.com/icon/file-undo)
