### ISSUE TITLE
Icons for calendar

### ISSUE THREAD

**Issue by KlausEichinger** [Templarian/MaterialDesign#1824]
here my suggestions for calendar icons:

- blank calendar
- calendar
- day calendar
- week calendar
- month calendar
- task calendar

**Comment by KlausEichinger** [comment]
You are the artist :)

Here I have a little inspiration. Hope it will help …
[link](https://www.eichinger-media.de/media/scribble.jpg)

**Comment by MrGrigri** [comment]
We already have `blank calendar`, `calendar`, `day calendar`, `week calendar`, `task calendar`.

![calendar-blank](https://materialdesignicons.com/icon/calendar-blank) ![calendar](https://materialdesignicons.com/icon/calendar) ![calendar-today](https://materialdesignicons.com/icon/calendar-today) ![calendar-range](https://materialdesignicons.com/icon/calendar-range) ![calendar-check](https://materialdesignicons.com/icon/calendar-check)

maybe we can add them as aliases.

- [ ] calendar-today with alias as calendar-day
- [ ] calendar-range with alias as calendar-week
- [ ] calendar-check with alias as calendar-task

**Comment by KlausEichinger** [comment]
Thank you for your answer. 

I'm working on an app where I need these icons as items in a menu bar. 

`calendar-blank` is fine.
`calendar` or `calendar-today` as today's calendar is also works.

A weekly calendar needs to recognize as a week calendar 5 or 7 dots not 3.
A monthly calendar needs to recognize as a month calendar 4 rows with 7 dots each row. (That would be imho that standard calendar. May be interpretable …)
A task or activities calendar means a place where you store places, times and tasks. That should the symbol show.

**Comment by MrGrigri** [comment]
We cannot have that many dots per Google Material Design Standards.

**Comment by MrGrigri** [comment]
Here are my two version for `calendar-month`, and `calendar-month-variant`.

![calendar-month](https://cloud.githubusercontent.com/assets/4528551/22517522/9c0c7848-e866-11e6-94c0-e4f4c87270cc.png) ![calendar-month-variant](https://cloud.githubusercontent.com/assets/4528551/22517523/a018aef2-e866-11e6-9c0f-16b51893463c.png)

**Comment by KlausEichinger** [comment]
Thank you for the efforts, but that doesn't fit my intention

**Comment by MrGrigri** [comment]
Here is an variant for `calendar-week`.

![calendar-week](https://cloud.githubusercontent.com/assets/4528551/22517956/19d1afb8-e868-11e6-9572-7a70e8a5a9f0.png)

[calendar-week.zip](https://github.com/Templarian/MaterialDesign/files/745584/calendar-week.zip)

Also, I believe that `calendar-favorite` would work for task/activity found [here](https://github.com/Templarian/MaterialDesign/issues/1641). Remember that this issue is still open and hasn't been added to the repo yet.

**Comment by KlausEichinger** [comment]
Sorry for the moment. I have to think about it :|

**Comment by CoDEmanX** [comment]
Google Calendar app:

![screenshot_20170201-173939](https://cloud.githubusercontent.com/assets/1309249/22523202/c6b9d858-e8be-11e6-957e-aaa70414c678.png)

Microsoft Outlook app (Calendar):

![screenshot_20170201-174053](https://cloud.githubusercontent.com/assets/1309249/22523201/c69e8ee0-e8be-11e6-84c5-4332c4615e3f.png)

![screenshot_20170201-174018](https://cloud.githubusercontent.com/assets/1309249/22523203/c6d52d6a-e8be-11e6-836f-66113e17617c.png)

**Comment by KlausEichinger** [comment]
Which one of these is self explanatory without the label?

**Comment by MrGrigri** [comment]
I believe Google Calendar is far too abstract and that Outlook did a good job. But honestly, what's wrong with the ones that I provided?

**Comment by KlausEichinger** [comment]
I agree with you 

> … that Outlook did a good job …

You are doing a great job with providing all these icons. Most of them I find best, uncontradicted. But in this way it doesn't fit my requirements. Thank you.

**Comment by MrGrigri** [comment]
@KlausEichinger, we will close this issue once the aliases and the other new icons are added.

@Templarian can we add the above-mentioned aliases as well as the new ones I've created. I believe that they will add more variety to the calendar choices.

**Comment by CoDEmanX** [comment]
- Overview: `view-stream`
- Day: `view-day`
- 3 days / week: `view-column` (alternatively, `view-week`)
- Month: `view-module`

**Comment by PeterShaggyNoble** [comment]
Aliases added.

**Comment by CoDEmanX** [comment]
A slightly better centered version of calendar-favorite is available over here: https://github.com/Templarian/MaterialDesign/issues/1641#issuecomment-381342163

First day of week (Sunday/Monday): [calendar-week-begin.zip](https://github.com/Templarian/MaterialDesign/files/1956880/calendar-week-begin.zip)

![grafik](https://user-images.githubusercontent.com/1309249/39387926-b81b9cfc-4a7c-11e8-908e-cebd6f435b3a.png)

**Comment by Templarian** [comment]
[![calendar-week](https://materialdesignicons.com/icon/calendar-week)](https://materialdesignicons.com/icon/calendar-week) [![calendar-week-begin](https://materialdesignicons.com/icon/calendar-week-begin)](https://materialdesignicons.com/icon/calendar-week-begin) [![calendar-alert](https://materialdesignicons.com/icon/calendar-alert)](https://materialdesignicons.com/icon/calendar-alert)
