### ISSUE TITLE
Bat

### ISSUE THREAD

**Issue by kylerw** [Templarian/MaterialDesign#1825]

**Comment by Templarian** [comment]
We can probably add a bat icon. Probably not a batman one though. 😃

**Comment by PeterShaggyNoble** [comment]
Batman was previously requested in #1086.

**Comment by CoDEmanX** [comment]
It was actually a contribution, but the icons did not match the MD guidelines. So leaving this request open.

**Comment by Templarian** [comment]
[![bat](https://materialdesignicons.com/icon/bat)](https://materialdesignicons.com/icon/bat)
