### ISSUE TITLE
Rounded Rectangle

### ISSUE THREAD

**Issue by stepheneldridge** [Templarian/MaterialDesign#1828]
Could use a rounded rectangle icon with grip handles like the vector-square

**Comment by MrGrigri** [comment]
How do you propose we show rounded corners with 'grip handles' on the corners?  Just for visual reference, here is the `vector-rectangle`. Showing rounded corners would be difficult. 

![vector-rectangle](https://materialdesignicons.com/icon/vector-rectangle)

**Comment by CoDEmanX** [comment]
Maybe similar to this, with only one handle + rounded rectangle?

![](https://materialdesignicons.com/icon/vector-circle-variant)

**Comment by Templarian** [comment]
![vector-radius](https://cloud.githubusercontent.com/assets/338885/22619929/42025014-eac5-11e6-8bc6-8ecdf5e97a90.png)
![vector-rectangle-radius](https://cloud.githubusercontent.com/assets/338885/22619945/a5aa5382-eac5-11e6-9750-e6ae8076d047.png)

???

**Comment by MrGrigri** [comment]
I like the first one

**Comment by Templarian** [comment]
[![vector-radius](https://materialdesignicons.com/icon/vector-radius)](https://materialdesignicons.com/icon/vector-radius)

@stepheneldridge Will this work for your needs?

**Comment by CoDEmanX** [comment]
We can really use `vector-radius`, but it doesn't really represent a "rounded rectangle tool" to me.

**Comment by Templarian** [comment]
@CoDEmanX Agreed, that's why I haven't closed it just yet, due to the size I'm having trouble designing something correct.

**Comment by goyney** [comment]
This issue seems stale and `vector-radius` seems like a good enough solution. Any reason to keep it open still?

**Comment by CoDEmanX** [comment]
There is also `rounded-corner`:

![grafik](https://user-images.githubusercontent.com/1309249/61857487-8fbf1b00-aec4-11e9-9400-184872e301a9.png)

**Comment by goyney** [comment]
Going to close this as it seems we have some options now. If there is another idea for another way to convey this, please open a new issue! Thanks!
