### ISSUE TITLE
Reload

### ISSUE THREAD

**Issue by St-uliana** [Templarian/MaterialDesign#1829]
It will be nice to have this icon.
![1](https://cloud.githubusercontent.com/assets/25503678/22546778/8132c8a8-e94f-11e6-9907-43faa5326232.png)

**Comment by PeterShaggyNoble** [comment]
Are you specifically looking for the 2 arrows in a circle? The stock Google icon for reload/refresh is this one:

![](https://materialdesignicons.com/icon/refresh)

Alternatively, there's also the `sync` icon:

![](https://materialdesignicons.com/icon/sync)

**Comment by St-uliana** [comment]
There are a lot of icons in circle, and in our progect we use exactly this style. Exept reloading. That's why we are specifically looking for the 2 arrows in a circle.

**Comment by CoDEmanX** [comment]
If you use custom icons in your project, then you could just take sync as basis, rotate it and add a circle outline around it.

**Comment by JamesCoyle** [comment]
This seems like it would be best implemented in the way @CoDEmanX suggests. It's really too specific to be added to the project.

**Comment by Templarian** [comment]
Scaling it down inside of a circle will be too small unfortunately to keep the 2dp guidelines. Would suggest what the others have said above.
