### ISSUE TITLE
Flashlight icon pls!

### ISSUE THREAD

**Issue by timothyjc** [Templarian/MaterialDesign#183]

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/flashlight

**Comment by timothyjc** [comment]
Not sure if I missed it, or you just did it now, either way, thank you very much.

**Comment by Templarian** [comment]
http://materialdesignicons.com/history

It's a new icon (I'm in the middle of closing issues and that was a simple one). You can always check the page above to see the latest changes. Good luck on your app.
