### ISSUE TITLE
BUG: Calendar-Range

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1830]
While in the other calendar thread, I noticed that `calendar-range` is down one pixel compared to the other calendar icons. Here is the comparison. 

![calendar-range](https://materialdesignicons.com/icon/calendar-range) ![calendar](https://materialdesignicons.com/icon/calendar)

**Comment by CoDEmanX** [comment]
good catch!

**Comment by Templarian** [comment]
Fixed... I'll open a bug this is in the official set also and hasn't been fixed.
