### ISSUE TITLE
Suggestion: British Pound

### ISSUE THREAD

**Issue by mpedigo** [Templarian/MaterialDesign#1833]
Would love to see the pound and other world currencies beyond USD and euro.

**Comment by PeterShaggyNoble** [comment]
It already does:
![](https://materialdesignicons.com/icon/currency-gbp)

As do a few others:
![](https://materialdesignicons.com/icon/currency-inr) ![](https://materialdesignicons.com/icon/currency-ngn) ![](https://materialdesignicons.com/icon/currency-rub) ![](https://materialdesignicons.com/icon/currency-try) ![](https://materialdesignicons.com/icon/currency-btc)

Are there any others you're specifically looking for?

**Comment by mpedigo** [comment]
Nope, that's perfect. Thanks for the update.
