### ISSUE TITLE
Twitter outline icon

### ISSUE THREAD

**Issue by RccnMarius** [Templarian/MaterialDesign#1834]
Please add Twitter outline icon

**Comment by PeterShaggyNoble** [comment]
Twitter's guidelines do not allow for an outlined icon - see p.7 of [this document](https://cdn.cms-twdigitalassets.com/content/dam/brand-twitter/asset-download-zip-files/Twitter_Brand_Guidelines.pdf).

**Comment by sirisian** [comment]
I'm using these icons and the twitter icon looks way too bold/distracting. Can you please reconsider this? (I don't care about the guidelines).

**Comment by goyney** [comment]
Looks like the link @PeterShaggyNoble shared is dead, here's the new one: https://about.twitter.com/content/dam/about-twitter/company/brand-resources/en_us/Twitter_Brand_Guidelines_V2_0.pdf

Literally the first item on Page 7:
![screen shot 2019-02-28 at 3 59 27 pm](https://user-images.githubusercontent.com/1015040/53598103-dc9b0180-3b71-11e9-867c-081a8dc1250a.png)

Sorry!

**Comment by JamesCoyle** [comment]
We cannot legally modify brand icons.

**Comment by sirisian** [comment]
Ah, didn't realize it was legal. In that case ignore me. I'll figure something else out.
![colorclash](https://user-images.githubusercontent.com/1320998/53598151-9a6dc200-3b69-11e9-860c-0551d6f6fb8c.png)

**Comment by JamesCoyle** [comment]
Perhaps a Twitter circle outline would work?
