### ISSUE TITLE
file-plus-outline

### ISSUE THREAD

**Issue by offvalley** [Templarian/MaterialDesign#1836]
I noticed the lack of these icons in one of my projects, therefor I've created a set of them in solid and outline design. The time 24h-icon i similar to mdi-history, but since it's about time - the arrow goes clockwise.

See attachment
[6-svg-icons.zip](https://github.com/Templarian/MaterialDesign/files/752433/6-svg-icons.zip)

Thanks for quick response Templarian, and a great starter kit for app dev!

**Comment by MrGrigri** [comment]
look at this thread for file-plus: https://github.com/Templarian/MaterialDesign/issues/1240

look at this thread for folder-open: https://github.com/Templarian/MaterialDesign/issues/1835

As far as `time-24`, I'm not sure. We'll see what others think.

**Comment by Templarian** [comment]
[![file-plus](https://materialdesignicons.com/icon/file-plus)](https://materialdesignicons.com/icon/file-plus)

**Comment by goyney** [comment]
There are 5 icons in the ZIP file from the original post:

- file-plus - Was added by @Templarian above
- file-plus-outline - Supplied version doesn't match @Templarian's, so see below for a new version of it
- folder-open-outline - Already included
- folder-open - Already included
- time-24h - Supplied icon matches the already included `history`, `update`, or `restore-clock`

Therefore, repurposing this issue to add `file-plus-outline`:
![image](https://user-images.githubusercontent.com/1015040/60063178-0b615880-96ca-11e9-8f3b-e03fd6012d4b.png)

[file-plus-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3323214/file-plus-outline.svg.zip)

**Comment by Templarian** [comment]
[![file-plus-outline](https://materialdesignicons.com/icon/file-plus-outline)](https://materialdesignicons.com/icon/file-plus-outline)
