### ISSUE TITLE
Distance between places

### ISSUE THREAD

**Issue by filipebezerra** [Templarian/MaterialDesign#1837]
Some icon inspired by some of these [from flaticon](http://www.flaticon.com/search?word=distance)

**Comment by CoDEmanX** [comment]
![image](https://cloud.githubusercontent.com/assets/1309249/22659406/cf48bf10-ec9d-11e6-9a40-21f44fcdf8c6.png) seems doable

**Comment by filipebezerra** [comment]
Yeah, that's right. Nice shot!

**Comment by filipebezerra** [comment]
@Templarian what kind of information do you need?

**Comment by Templarian** [comment]
@filipebezerra Basically needed to know more specifically which idea would fit best for you. Looks like we have an idea for it now.

**Comment by filipebezerra** [comment]
Cool, thanks for your great work buddy

**Comment by MrGrigri** [comment]
How about this?

![asset 38](https://cloud.githubusercontent.com/assets/4528551/22661713/a439a5ee-ec63-11e6-9ee4-d5baf9de5f31.png)

[distance-between.zip](https://github.com/Templarian/MaterialDesign/files/755584/distance-between.zip)

**Comment by filipebezerra** [comment]
I don't know @MrGrigri, but sincerely I liked @CoDEmanX icon.

**Comment by MrGrigri** [comment]
@filipebezerra all @CoDEmanX did was place one fo the images, you provided as a link, into this discussion. That icon, as is, is not to MD standards. I am trying for a more abstract approach with the filled-in and not filled-in circles. But ultimately, it's the community and @Templarian who decides. Here is another one that I'm trying out as well.

![distance-between-alt](https://cloud.githubusercontent.com/assets/4528551/22664756/48f710b6-ec6f-11e6-9b31-0bbc41818b0e.png)

[distance-between.zip](https://github.com/Templarian/MaterialDesign/files/755767/distance-between.zip)

**Comment by filipebezerra** [comment]
Right, the referred icons are just the Idea, we have to design an icon following the MD guidelines

**Comment by JapanYoshi** [comment]
Why not just one pin and a double-edged arrow underneath?

**Comment by filipebezerra** [comment]
Hey guys, any updates here?

**Comment by CoDEmanX** [comment]
This is the one we want to add (4 upvotes) by Griri. I removed the grouping with some invisible layer:

![image](https://user-images.githubusercontent.com/1309249/38770567-472d3ce2-4015-11e8-9335-28fd434a0f7a.png)

[distance-between-alt.zip](https://github.com/Templarian/MaterialDesign/files/1910631/distance-between-alt.zip)

**Comment by Templarian** [comment]
[![map-marker-distance](https://materialdesignicons.com/icon/map-marker-distance)](https://materialdesignicons.com/icon/map-marker-distance)

**Comment by Yuanruili** [comment]
@Templarian 
Tried another way. I feel it's not that 'tight' as the previous version. 
[Distance.zip](https://github.com/Templarian/MaterialDesign/files/2933512/Distance.zip)

**Comment by MrGrigri** [comment]
@Yuanruili, all icons need to be exported as a single compound path and can be used in our [preview generator](https://dev.materialdesignicons.com/contribute/github).

![distance](https://user-images.githubusercontent.com/4528551/53844020-a7bbef80-3f61-11e9-93f8-deb0e7f93b31.png)

---
#### Files
[Distance.zip](https://github.com/Templarian/MaterialDesign/files/2933542/Distance.zip)

**Comment by MrGrigri** [comment]
I do like this.

**Comment by Yuanruili** [comment]
@MrGrigri Thank you~

**Comment by JapanYoshi** [comment]
I feel like @MrGrigri's version adds a bit too much dimensionality, and is harder to parse than the simpler one.

**Comment by PeterShaggyNoble** [comment]
I agree with Yoshi, it's a bit too busy. Even with context it took me a second to see what it was supposed to be.
