### ISSUE TITLE
[Icon Request] combintion of arrows, "in & out" "forward & reverse"

### ISSUE THREAD

**Issue by csxdotcc** [Templarian/MaterialDesign#1838]
an icon like the _clipboard-flow_ without the clipboard,
symbol could describe accounting, post/enter/charge or to enter stock/inventory items/amounts,
unlike the diagonal _arrow-compress_ or video style arrows.
hope you get the idea despite the bad english ;)

**Comment by CoDEmanX** [comment]
I guess this?

[![swap-vertical](https://materialdesignicons.com/icon/swap-vertical)](https://materialdesignicons.com/icon/swap-vertical)

**Comment by csxdotcc** [comment]
thanks :-)
