### ISSUE TITLE
IE 10 not showing icons when font-size in rem

### ISSUE THREAD

**Issue by gabchang** [Templarian/MaterialDesign#1839]
I tried to define $mdi-font-size-base to 1rem but...

It's a known bug in IE10 that rem units are not supported in "font" shorthand declaration.
A simple solution is to split into single declarations.

@see _core.scss

Thanks !

**Comment by Templarian** [comment]
This will be fixed in a future release. I know of the issue, but due to the rare use of `rem` I completely forgot to fix it in the last release. Good that we have an issue for it now.

**Comment by JamesCoyle** [comment]
I believe this has been fixed for a while. Please reopen if it is still an issue.

**Comment by goyney** [comment]
Even if it's not fixed, IE10 was taken out of support by Microsoft in March of 2017 and would not be worth the time to make fixes for a dead browser.
