### ISSUE TITLE
Icon Request: Yammer Icon

### ISSUE THREAD

**Issue by devriesb13** [Templarian/MaterialDesign#1840]
Hi There, can you please create a yammer icon when you can.

**Comment by CoDEmanX** [comment]
![image](https://cloud.githubusercontent.com/assets/1309249/22690208/f08e987e-ed34-11e6-87aa-70d383917eda.png)

**Comment by MrGrigri** [comment]
Used their favicon as an idea. Does this work?

![yammer](https://cloud.githubusercontent.com/assets/4528551/22701424/da6ae4a4-ed1a-11e6-9992-be5de7a49731.png)

[yammer.zip](https://github.com/Templarian/MaterialDesign/files/758380/yammer.zip)

**Comment by devriesb13** [comment]
Yes that works for me. Thank you

**Comment by Templarian** [comment]
[![yammer](https://materialdesignicons.com/icon/yammer)](https://materialdesignicons.com/icon/yammer)
