### ISSUE TITLE
Icon Request: Drone icon

### ISSUE THREAD

**Issue by vishnu1991** [Templarian/MaterialDesign#1841]
For reference:
![38946796-quadcopter-simple-icon-on-white-background--stock-vector-drone](https://cloud.githubusercontent.com/assets/6689768/22678939/3cfebaec-ed24-11e6-8995-91e5cc262c66.jpg)

Source: http://previews.123rf.com/images/tkacchuk/tkacchuk1504/tkacchuk150400152/38946796-Quadcopter-simple-icon-on-white-background--Stock-Vector-drone.jpg

[P.S: I have gone thru https://materialdesignicons.com/icon/drone ]

**Comment by CoDEmanX** [comment]
[![quadcopter](https://materialdesignicons.com/icon/quadcopter)](https://materialdesignicons.com/icon/quadcopter)

**Comment by MrGrigri** [comment]
I like it, but it might be a little difficult to distinguish at 1x. But I don't believe that should stop it from being added as a contribution.

**Comment by Templarian** [comment]
@MrGrigri That's already an icon.
