### ISSUE TITLE
Store icon (Google Play Store)

### ISSUE THREAD

**Issue by MarioUnoDueTreQuattro** [Templarian/MaterialDesign#1842]
There isn't the store icon, like this -> http://imgur.com/a/yw6sr

**Comment by CoDEmanX** [comment]
https://material.io/icons/#ic_shop

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/shopping-music Kind of close, could just replace this one probably with the stock one.

**Comment by wopian** [comment]
Hasn't the Google Play Store has been (roughly) [this](https://materialdesignicons.com/icon/google-play) for a couple of years now?

**Comment by Templarian** [comment]
Good question, is this a legacy icon? Or is the shopping bag + play symbol used somewhere else.

Seems confusing to have it in the pack if it's a legacy icon.

**Comment by PeterShaggyNoble** [comment]
`play prism` is included in the Extended icon set.

![play prism](https://user-images.githubusercontent.com/15157491/38502672-ec10111a-3c07-11e8-9053-4d6e7b407cd4.png)

**Comment by JamesCoyle** [comment]
Closing as we have a Google play icon
