### ISSUE TITLE
Add pencil-circle-outline icon

### ISSUE THREAD

**Issue by sesm** [Templarian/MaterialDesign#1844]
While 'pencil-circle' icon is present, it's counterpart 'pencil-circle-outline' is clearly missing.
Please add it. Thanks!
![pencil-circle-outline96](https://cloud.githubusercontent.com/assets/1313744/22697966/846a0a42-ed6c-11e6-93e8-6b3e42089a93.png)
![pencil-circle-outline48](https://cloud.githubusercontent.com/assets/1313744/22697969/8620972a-ed6c-11e6-81e5-d1b97244e6e0.png)
![pencil-circle-outline24](https://cloud.githubusercontent.com/assets/1313744/22697971/87472484-ed6c-11e6-9be7-84ce37700ce0.png)
[pencil-circle-outline.zip](https://github.com/Templarian/MaterialDesign/files/758066/pencil-circle-outline.zip)

**Comment by Templarian** [comment]
[![pencil-circle-outline](https://materialdesignicons.com/icon/pencil-circle-outline)](https://materialdesignicons.com/icon/pencil-circle-outline)

@sesm Let me know when you hit 5 icons and I'll create a contributor account and assign the icon over (there are tons of open issues to contribute to they go by quick).
