### ISSUE TITLE
add sticker icon

### ISSUE THREAD

**Issue by bimemto** [Templarian/MaterialDesign#1845]
please add sticker icon like this
https://dl2.pushbulletusercontent.com/fumDNWhQ348enFqFpRg2CUIBxGf3NfuN/croppedScreenshot_1486542107889_.png

**Comment by CoDEmanX** [comment]
We have a generic sticker icon:

[![sticker](https://materialdesignicons.com/icon/sticker)](https://materialdesignicons.com/icon/sticker)

But I think we could actually use the sticker icon with a face, which is used in Google Hangouts:

![image](https://cloud.githubusercontent.com/assets/1309249/22735112/a673d50a-edf8-11e6-8ae6-25d67b4fc7ef.png)

**Comment by Templarian** [comment]
Yep, that would be a nice variant. The current sticker was a more literal representation. Google's is nicer for chat context.

**Comment by CoDEmanX** [comment]
Looks a bit weird at 24 pixels, but it should be pretty accurate:

![sticker-emoji](https://cloud.githubusercontent.com/assets/1309249/22756365/2d66edd8-ee47-11e6-9455-71a91320a598.png) [sticker-emoji.zip](https://github.com/Templarian/MaterialDesign/files/761878/sticker-emoji.zip)

**Comment by bimemto** [comment]
thank you all. But it would be nicer if I can search sticker icon with a face on https://materialdesignicons.com/

**Comment by Templarian** [comment]
@bimemto Takes me until usually the weekend to get free time to get these synced into the site.

[![sticker-emoji](https://materialdesignicons.com/icon/sticker-emoji)](https://materialdesignicons.com/icon/sticker-emoji)

**Comment by bimemto** [comment]
@Templarian that's great! Thank you for your contribution
