### ISSUE TITLE
Icon Request : Challenge and/or duel

### ISSUE THREAD

**Issue by dgngulcan** [Templarian/MaterialDesign#1846]
As for Reference
![](https://cdn3.iconfinder.com/data/icons/business-marketing-4/64/MISSION-128.png)

![](https://cdn0.iconfinder.com/data/icons/computer-gaming/140/duel_swords_fighting_versus_vs_fight_challenge-128.png)

**Comment by MrGrigri** [comment]
Does `sword` not work?

![sword](https://materialdesignicons.com/icon/sword)

**Comment by dgngulcan** [comment]
@MrGrigri it represents more like damage or weapon in my humble opinion

**Comment by MrGrigri** [comment]
Here's a quick attempt.

![sword-cross](https://cloud.githubusercontent.com/assets/4528551/22756440/594d55ce-ee04-11e6-95d3-a90523f36803.png)

[sword-cross.zip](https://github.com/Templarian/MaterialDesign/files/761882/sword-cross.zip)

**Comment by Templarian** [comment]
Looks good, this reminds me we need to add more RPG icons.

**Comment by dgngulcan** [comment]
@Templarian more RPG icons would be nice :) we are developing a cycling tracker app that is highly involved with RPG aspect and using https://materialdesignicons.com/ as an icon source since we don't have an illustrator. We also would want to give attribution but couldn't find any attribution terms.

PS: Google play link of the app: https://play.google.com/store/apps/details?id=life.paxira.app

**Comment by JamesCoyle** [comment]
If you want to give attribution, a link to [materialdesignicons.com](materialdesignicons.com) in an about section would be more than enough. We maintain this project because its awesome and we get to use everything we make in our own projects.

**Comment by dgngulcan** [comment]
@JamesCoyle sure thing! it's awesome indeed.

**Comment by Templarian** [comment]
[![sword-cross](https://materialdesignicons.com/icon/sword-cross)](https://materialdesignicons.com/icon/sword-cross) [![summit](https://materialdesignicons.com/icon/summit)](https://materialdesignicons.com/icon/summit)
