### ISSUE TITLE
Hashtag icon

### ISSUE THREAD

**Issue by Saketme** [Templarian/MaterialDesign#185]
Thank you for the amazing icons. I have a request for a "Hashtags" icon for my app. I'm currently using a bookmark icon instead, but it doesn't fit well. :)

- [x] pound (alias hashtag)
- [x] pound-box (alias hashtag-box)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/pound (alias `hashtag`)
http://materialdesignicons.com/icon/pound-box (alias `hashtag-box`)

**Comment by Saketme** [comment]
Sorry for this late reply, thank you :)
