### ISSUE TITLE
enable-background SVG attribute depreciated

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1850]
I have come across a frustrating issue that I believe needs to be addressed if it hasn't already been discussed. As of right now, each icon has an `enable-background` property with the `new` keyword in order to create a canvas of 24x24 pixels instead of having an empty `rect` tag.

This property has been depreciated and there are several apps that do not allow for imports of these icons. Mainly Figma, and Adobe XD. I have filed a concern with Adobe and they have said that because that property is [depreciated](https://www.w3.org/TR/filter-effects/#AccessBackgroundImage), they will not support it. 

This might be better for a 2.0 release, but I'm not one to make that decision.

**Comment by Templarian** [comment]
@MrGrigri We don't export with that property in the design files...

https://materialdesignicons.com/design

The source SVG files have it, but that's from the application I use to export them. I would suggest using the design files rather than the ones in the repo.

**Comment by MrGrigri** [comment]
This doesn't solve the problem of using an icon in a prototyping tool quickly by dragging and dropping an SVG into the program (the `.design` files don't work with these tools).  The steps that I have to do are create and empty rectangle, group the SVG and the rectangle, and then center the SVG on the rectangle. I know that it's not much and I agree on the `Low Priority` label, but is there a possibility export the SVGs differently?

**Comment by Templarian** [comment]
Nah, I meant using the .svg files from the /design page. Was busy at the office, should have been more specific. The new website will focus on user not using the resources in the git repo.

The design download is generated off of the font system's SVG files which are optimized for the minimum number of points.

**Comment by MrGrigri** [comment]
I forgot about this issue...I do not believe it is an issue anymore. I'm going to close this out.
