### ISSUE TITLE
sports icons

### ISSUE THREAD

**Issue by turboc1208** [Templarian/MaterialDesign#1851]
baseball fields
basketball arena
football stadium
ice rink
baseball bat
baseball
football
basketball
football helmet
golf club

you get the idea

**Comment by PeterShaggyNoble** [comment]
Football helmet already exists:

![](https://materialdesignicons.com/icon/football-helmet)

And there are a few options for football, depending on which variation you're referring to:

![](https://materialdesignicons.com/icon/football-australian) ![](https://materialdesignicons.com/icon/football) ![](https://materialdesignicons.com/icon/soccer)

For the arenas & stadiums, do you have examples of what you're looking for? I don't know how you'd differentiate between each, especially at icon sizes. I'd suggest a single, general purpose stadium icon, such as [this](https://icons8.com/web-app/6457/arena).

**Comment by turboc1208** [comment]
Aaah arena. That's one term I didn't search for. That will work great.
Thanks

**Comment by MrGrigri** [comment]
We already have `stadium`

![stadium](https://materialdesignicons.com/icon/stadium)

**Comment by PeterShaggyNoble** [comment]
I'm going to close this one out as a good few [sports icons](https://petershaggynoble.github.io/MDI-Sandbox/?categories=sport) have been added lately. If there are still any sports you would like to see included, please open new requests for each icon.
