### ISSUE TITLE
Tray Icon

### ISSUE THREAD

**Issue by SkyEngine-OSP** [Templarian/MaterialDesign#1852]
if possible, can i request for a tray icon ? thank you.

**Comment by PeterShaggyNoble** [comment]
What sort of tray are you looking for? Would `inbox` or any of its variations suit your needs?

![](https://materialdesignicons.com/icon/inbox) ![](https://materialdesignicons.com/icon/inbox-arrow-down) ![](https://materialdesignicons.com/icon/inbox-arrow-up)

**Comment by SkyEngine-OSP** [comment]
oh. i think inbox would do the work. thank you 👍
