### ISSUE TITLE
(CSS font) Some box icons are not of the same size

### ISSUE THREAD

**Issue by Tyrrrz** [Templarian/MaterialDesign#1854]
https://jsfiddle.net/7u7yvqc6/

As you can see from this example, account-box and vk-box are smaller than the other three.

**Comment by Templarian** [comment]
That is definitely a bug. They should all be `18dp` squared. Good find!

**Comment by Templarian** [comment]
Updated `twitter-box`, `linkedin-box`, `github-box`, `facebook-box`.

**Comment by Tyrrrz** [comment]
Nice, thank you.

That history tracker looks really awesome btw. Just a bit weird seeing "Google modified" on original material design icons.

**Comment by Templarian** [comment]
That's a bug I've just been too lazy to fix. It should show my account modifying it. Will address it in the new site. Not doing any updates on this old site.

I have a full history log in the database I'm not showing. Hopefully I can display this in the new site's change logs.

**Comment by PeterShaggyNoble** [comment]
While on the subject of the history, one thing that's missing from it that would be nice to see on the new site, if possible, is when the name of an icon is changed or when an icon is removed and its name recycled as an alias of another icon.
