### ISSUE TITLE
CPU Icon

### ISSUE THREAD

**Issue by CrawfordK** [Templarian/MaterialDesign#1856]
An icon that says "CPU" with rounded corners made to look like an actual (minimalist) CPU!

**Comment by PeterShaggyNoble** [comment]
Would either of these do you?

![](https://materialdesignicons.com/icon/chip) ![](https://materialdesignicons.com/icon/memory)

**Comment by MrGrigri** [comment]
We refrain from using letters. This is an internationalized icon pack. There are a few exceptions for well-known objects and CPU isn't one of them.

**Comment by Templarian** [comment]
I think the `chip` icon should work pretty well to represent a CPU. Even the memory could work as it's rather general. The `developer-board` icon might also work.

[![developer-board](https://materialdesignicons.com/icon/developer-board)](https://materialdesignicons.com/icon/developer-board)
