### ISSUE TITLE
Starred list

### ISSUE THREAD

**Issue by ursusursus** [Templarian/MaterialDesign#1858]
I would like an icon that depicts starred list. Much like the play list or other variations with symbol on the right and 3 stripes on the left

**Comment by GreenTurtwig** [comment]
[playlist-star.zip](https://github.com/Templarian/MaterialDesign/files/777589/playlist-star.zip)
Here! :-)  

![image](https://cloud.githubusercontent.com/assets/15905797/22983493/2f7d02c6-f39a-11e6-9eef-10ed349bb9a5.png)
![image](https://cloud.githubusercontent.com/assets/15905797/22983513/3d48b788-f39a-11e6-9436-5fb0b3168811.png)


While designing this, I found out that Google have updated their icon for `playlist-play`, no longer has extra long "bars". This will need to be updated on MDI.

**Comment by MrGrigri** [comment]
I like the idea...however, I believe that the star in unrecognizable at 1x. Could the star be enlarged a bit?

**Comment by GreenTurtwig** [comment]
Yeah I agree on that, the main problem is the star has such thin corners.  
I spent quite a while trying out variations again, here's an updated version.
[playlist-star.zip](https://github.com/Templarian/MaterialDesign/files/777908/playlist-star.zip)

**Comment by Templarian** [comment]
[![playlist-star](https://materialdesignicons.com/icon/playlist-star)](https://materialdesignicons.com/icon/playlist-star)
