### ISSUE TITLE
Google Play Music icons

### ISSUE THREAD

**Issue by BedrockDev** [Templarian/MaterialDesign#1859]
Please make a material icon version of [Google Play Music icon](https://en.wikipedia.org/wiki/File:Play_music_triangle.svg).

I was trying to make it material-like, but it was too hard to make it single-colored.

**Comment by GreenTurtwig** [comment]
The Papirus icon theme has an icon for GPMDP's (Google Play Music Desktop Player) panel icon.
Taking inspiration from it would be a good idea.
https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/blob/master/Papirus/22x22/panel/gpmdp-tray.svg

**Comment by PeterShaggyNoble** [comment]
Yeah, making that a single colour would be tricky. I've seen a few other icon packs just use the note on its own, though, so that might do you.

![](https://materialdesignicons.com/icon/music-note) ![](https://materialdesignicons.com/icon/music-circle)

**Comment by BedrockDev** [comment]
Thanks, I think I can use the Papirus icon.
