### ISSUE TITLE
I need the icon GRIDVIEW

### ISSUE THREAD

**Issue by anticafe** [Templarian/MaterialDesign#186]
Sometimes we need an GRIDVIEW icon to toggle between listview/gridview. Please help me.

**Comment by Templarian** [comment]
http://materialdesignicons.com/tag/view

I think you could use one of the `view-` icons? If not can you link to a reference image.

**Comment by anticafe** [comment]
Thank you. I think `view-dashboard` or `view-module` are fit for GRIDVIEW icon

**Comment by anticafe** [comment]
Please close this issue yourself, or keep it if you still would like to make a new GRIDVIEW icon :)

**Comment by Templarian** [comment]
If I made one it would look like `grid-module`. Can't see a reason to add another. Best to use the stock. :smile:
