### ISSUE TITLE
Therapy / Psychologist Icon Idea

### ISSUE THREAD

**Issue by Paragrimm** [Templarian/MaterialDesign#1860]
https://thenounproject.com/term/psychology/11424/

Hey, I've searched for a proper psychologist/therapy Icon, but the icon that matches the most for me is the yin-yang icon. A Meditation Icon would be awesome aswell!

Thanks for your great work!

**Comment by goyney** [comment]
We added a ton of `head-*` icons in past releases that are similar to your suggestions in the link. We also have `meditation`. Gonna consider this issue resolved.
