### ISSUE TITLE
CDN available?

### ISSUE THREAD

**Issue by splitbrain** [Templarian/MaterialDesign#1861]
Is there a way to dynamically embed single SVGs from a central location? Preferably through some CDN?

**Comment by splitbrain** [comment]
To answer my own question there are these two services which should work:

* https://rawgit.com/
* https://gitcdn.xyz/

**Comment by Templarian** [comment]
By the way the icons in the repo are the "source" SVG. We don't currently CDN the production SVG files.

https://materialdesignicons.com/design Contains the optimized for web SVG files matching the version release.

**Comment by splitbrain** [comment]
Can you explain the difference between the source and production SVGs? Is it just unneeded headers and stuff? Or would I find non-single path SVGs in the source tree?

**Comment by Templarian** [comment]
So all SVG's in the source branch are single path. But I actually run a very complicated hand coded process to optimize the SVG path data to play nicer with the font generation software. This optimization step cuts down file size up  to 50% for some of the path data.

I don't know if there is a huge asking to retrieve individual SVG files from the CDN. What exactly do you need the SVG files for? Are you using them with like an img tag?

**Comment by splitbrain** [comment]
In this case I'm working on a wiki template. Wiki users shall have an easy way to use icons in the navigation. They can reference locally uploaded SVGs, but realistically few will ever create their own files. Instead I want them to have the possibility to simply give a file name of one of the MD icons, it will be automatically downloaded and used. Since each install will only use a handful of icons but each will probably use different icons, it makes no sense to bundle them all with the template.

So as long as the files are single path, it should be fine for my usecase (I have some simple cleanup on my end as well).

**Comment by Templarian** [comment]
That's a little specific. Not sure if it's worth the effort to maintain with each release. Just thinking what would happen in the long term if MaxCDN stops sponsorship. Right now it's just used for the webfont/meta.json/design package download. Going to keep it as simple as possible.

We'll see in the future if priorities changes. Will keep it in mind though.
