### ISSUE TITLE
Safari problems with optimization

### ISSUE THREAD

**Issue by snuuve** [Templarian/MaterialDesign#1862]
I found that Safari has some problem with scrolling big numbers of icons.
When i disabled `transform` on `.mdi:before` scrolling works perfect :)

Here are some records:

With transform: https://drive.google.com/open?id=0B8McMGbHHZI9dXVkY1RhWFJEcFE

Without transform: https://drive.google.com/open?id=0B8McMGbHHZI9UTMxUlYxTmp4Wjg

**Comment by Templarian** [comment]
I see that FontAwesome has removed that line of CSS. It's in there to fix a bug with FireFox, but I think it may be safe now to remove that line.

Marking this as a bug for the next release.

**Comment by Templarian** [comment]
This change has been made in the build tools and will be in `v1.9.32` releasing in a couple hours.
