### ISSUE TITLE
Publish Document / View Published Doc / Modify Published Doc

### ISSUE THREAD

**Issue by resecleaver** [Templarian/MaterialDesign#1863]
Looking for three icons for publishing documents: 

   - Publish Document (i could possibly use the bullhorn for this) 
   - View Published Document (maybe a bullhorn on a file?) 
   - Modify Published document (maybe a bullhorn on a file with a + sign or a pencil?) 

I was thinking it could include a 
and then either variations of the bullhorn or volume icons on it , and maybe a bullhorn with a plus sign or something?

**Comment by JapanYoshi** [comment]
Publish could just be the send or share icon, or a Document with an up arrow.

**Comment by resecleaver** [comment]
@JapanYoshi that could work also, but that implies upload rather than publish to end users to me. what are your thoughts on the others?

**Comment by JapanYoshi** [comment]
I tried combining ``globe`` with an up arrow. Will this work?
![globe upload tiny](https://cloud.githubusercontent.com/assets/8707990/23090317/fc0a05a0-f5de-11e6-8457-91f2fb44257e.png)
![globe upload](https://cloud.githubusercontent.com/assets/8707990/23090318/fd74bf48-f5de-11e6-90aa-5a3ecbb8d14c.png)

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
