### ISSUE TITLE
desk icon

### ISSUE THREAD

**Issue by pauldgifford** [Templarian/MaterialDesign#1865]
can anyone create a work desk icon or two? 

https://www.google.ca/search?q=desk+icon&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjc3Pr17o_SAhXq6oMKHX47DVYQ7AkIPA&biw=2560&bih=1289#tbm=isch&q=work+desk+icon

**Comment by PeterShaggyNoble** [comment]
Would `chair-school`  be any use to you?

![](https://materialdesignicons.com/icon/chair-school)

**Comment by pauldgifford** [comment]
it kinda looks like a high chair for my kid...

**Comment by PeterShaggyNoble** [comment]
OK, something along the lines of [this](https://icons8.com/web-app/32131/pc-on-desk) would probably work best, so, to conform to the Material Design guidelines and for clarity at smaller sizes.

**Comment by PeterShaggyNoble** [comment]
Closing n favour of #2536 which includes contributions.
