### ISSUE TITLE
Signal-off | Icon request

### ISSUE THREAD

**Issue by snuuve** [Templarian/MaterialDesign#1866]
Same as `mdi-wifi-off` but made of `mdi-signal-variant`

**Comment by GreenTurtwig** [comment]
Here we go! Had to try different positions of the slash, but I think it turned out pretty good. :-)
[signal-off.zip](https://github.com/Templarian/MaterialDesign/files/777349/signal-off.zip)

**Comment by snuuve** [comment]
I need this icon for "no GPS signal", you made a "no GPRS signal" :D

**Comment by Templarian** [comment]
[![signal-off](https://materialdesignicons.com/icon/signal-off)](https://materialdesignicons.com/icon/signal-off)
