### ISSUE TITLE
Todoist icon (Suggestion)

### ISSUE THREAD

**Issue by alexmuench** [Templarian/MaterialDesign#1867]
Hi, I'm a designer from Todoist and wanted to suggest the Todoist icon in case people want to add an option to integrate our app. I'm attaching the original icon as svg file.
[todoist.svg.zip](https://github.com/Templarian/MaterialDesign/files/777099/todoist.svg.zip)

**Comment by Templarian** [comment]
We only include Social Media icons at the moment. If this changes we'll reopen this issue.

Thanks for the suggestion and looks like a nice app!

(If you're curious we may be removing some brand icons that fall outside of this before the 2.0 release, been busy with the new site though)
