### ISSUE TITLE
Loading Icon

### ISSUE THREAD

**Issue by krambertech** [Templarian/MaterialDesign#1869]
Hi!

I lack of loading icon. Something to add spinning animation and create quick and simple loader, for example, inside button or input.

I've already created an svg. Here you can find it: https://drive.google.com/drive/folders/0B5grXaOjT059Wld6U2xEbUJ1ODA?usp=sharing

Examples of use:

![kapture 2017-02-16 at 9 16 31](https://cloud.githubusercontent.com/assets/10474869/23011431/9f231efa-f429-11e6-8643-864641fd717b.gif)
![kapture 2017-02-16 at 9 20 20](https://cloud.githubusercontent.com/assets/10474869/23011432/a1350938-f429-11e6-877a-e3f1d3b71574.gif)
![kapture 2017-02-16 at 9 22 48](https://cloud.githubusercontent.com/assets/10474869/23011434/a3480c70-f429-11e6-9e08-5f1beb390e39.gif)

Thank you!

**Comment by Templarian** [comment]
[![loading](https://materialdesignicons.com/icon/loading)](https://materialdesignicons.com/icon/loading)

Keeping this opened until I have the SCSS updates in for `mdi-spin`.

**Comment by Templarian** [comment]
Done `mdi-spin` will be in the next release. It works like font awesome.

**Comment by krambertech** [comment]
Cool! Thanks!

**Comment by JamesCoyle** [comment]
For anyone that finds it useful a spinner is really easy to make with pure CSS. https://jsfiddle.net/41w39g95/

**Comment by PeterShaggyNoble** [comment]
And, just to add to the collection, here's a Material-style SVG: https://jsfiddle.net/petershaggynoble/jk9eejaa/

**Comment by Templarian** [comment]
Yep, these are probably the recommended way, but these loader spin should work as a quick replacement for those coming from font awesome. 😸

**Comment by krambertech** [comment]
Actually I find it useful when using to replace icons in the text field or button. As quick inline loading indication

Very nice to use with React like this:
```js
const searchTextField = (
  <TextField
    leftIcon={loading ? <Icon spinning type="loading" /> : <Icon type="search" />}
    placeholder="Search..."
    value={search}
    onChange={this.handleSearch}
  />
);

```

Of course, for page (or section) loader there are much better options :)

**Comment by MrGrigri** [comment]
Just as a mention, the only issue with @PeterShaggyNoble solution is that the is no support for IE animations on SVG elements. Support discussed here: http://caniuse.com/#feat=svg-smil

**Comment by PeterShaggyNoble** [comment]
If that were the worst thing IE was guilty of, I'd be a very happy man!

**Comment by md5** [comment]
> Done `mdi-spin` will be in the next release. It works like font awesome.

@Templarian Which commit was it added in? I can't seem to find it.

**Comment by Templarian** [comment]
@md5 It was added to the build tools, it will be visible in the next release in the dist repo [here](https://github.com/Templarian/MaterialDesign-Webfont). Please track #1891 for the release of `v1.9.xx`.

**Comment by kospl** [comment]
Great icon, thanks!
