### ISSUE TITLE
Task / project progress icon

### ISSUE THREAD

**Issue by Thoum** [Templarian/MaterialDesign#1870]
Hi, here a suggestion for task/project progress icon.

Explanations : This icon will toggle a sidebar to access the summary of the different project with the percentage of completion.

I think something similar to the FontAwesome one would do the trick (illustration of progress bars), but if you have a better idea, don't hesitate ! 😄 
<img width="133" alt="capture d ecran 2017-02-16 a 13 29 14" src="https://cloud.githubusercontent.com/assets/8930517/23021387/f3db689a-f44b-11e6-81fc-260039e57264.png">

Thanks !

**Comment by terreng** [comment]
I think the [format-list-checks](http://materialdesignicons.com/icon/format-list-checks) icon would work in this case.

**Comment by CoDEmanX** [comment]
There are several fitting icons:
- circle-slice-*
- hexagon-slice-*
- clipboard-*
- chart-gantt
- chart-timeline
- chart-waterfall
- bulletin-board
- clock-start
- format-list-*
- timetable

There is also dip-switch, which is pretty similar to what FA has, but rotated 90°. I wonder if it's worth to add a variant of that...
