### ISSUE TITLE
Icon: Android head

### ISSUE THREAD

**Issue by Vogete** [Templarian/MaterialDesign#1871]
Hi!
I thought maybe a head only android icon would be great.

![android_head_min2](https://cloud.githubusercontent.com/assets/16021671/23038977/399863c0-f48c-11e6-9901-ba9f60a2014f.png)
![android_head_min](https://cloud.githubusercontent.com/assets/16021671/23038962/2a7e20dc-f48c-11e6-9aab-e4ecea0862db.png)
[android_head.zip](https://github.com/Templarian/MaterialDesign/files/781403/android_head.zip)

**Comment by Templarian** [comment]
[![android-head](https://materialdesignicons.com/icon/android-head)](https://materialdesignicons.com/icon/android-head)
