### ISSUE TITLE
Google Icon: Reset Password

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1872]
I found [this icon](https://ssl.gstatic.com/apps/cpanel/resources/img/reset-password-24.svg) in [G Suite](https://gsuite.google.com/) for resetting a user's password and thought it could be useful to include it in the library - I know I, for one, would have a use for it.

**Comment by Templarian** [comment]
[![lock-reset](https://materialdesignicons.com/icon/lock-reset)](https://materialdesignicons.com/icon/lock-reset)

Aliased with `password-reset`.
