### ISSUE TITLE
Dice Icon

### ISSUE THREAD

**Issue by eddieberklee** [Templarian/MaterialDesign#1873]
Something like https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/dice.png

**Comment by PeterShaggyNoble** [comment]
There are a few die icons available already showing all 6 numbers (replace the number at the end of the URL to change the number):

![](https://materialdesignicons.com/icon/dice-1)

Are you specifically looking for an icon showing two dice?

**Comment by eddieberklee** [comment]
Yep, cause individually (at least for me) it doesn't portray the sense of "random" or "shuffle". They're just individual dice

**Comment by MrGrigri** [comment]
@Templarian I believe that the dice-1 through dice-6, dice-d4, dice-d6, dice-d8, and dice-d20 need to have their name adjusted to 'die' (singular) instead. And then have die-3d. This will allow for dice to be used correctly with this icon.  What are your thoughts?

![dice](https://cloud.githubusercontent.com/assets/4528551/23222870/78f82b82-f8e6-11e6-834b-feee986fd952.png)

[dice.zip](https://github.com/Templarian/MaterialDesign/files/794236/dice.zip)

**Comment by JamesCoyle** [comment]
At this point it would be better to just name this `dice-multiple`. It's probably better for search if the names remain as dice.

**Comment by Templarian** [comment]
The really nit-picky person in me wants to rename them, but I think simply calling this `dice-multiple` will suffice.

Also we need a `dice-d10` to complete the set.

**Comment by Templarian** [comment]
[![dice-multiple](https://materialdesignicons.com/icon/dice-multiple)](https://materialdesignicons.com/icon/dice-multiple)

**Comment by PeterShaggyNoble** [comment]
Should the corner of the "knockout" be rounded to match the corners of the dice?

**Comment by MrGrigri** [comment]
@PeterShaggyNoble, no they shouldn't. If you read up on the [MD guidelines](https://material.io/guidelines/style/icons.html#icons-system-icons) this is considered a counter stroke.
