### ISSUE TITLE
Stack Chart

### ISSUE THREAD

**Issue by KumaresanSubramaniam** [Templarian/MaterialDesign#1874]
Stack chart icon not available

**Comment by PeterShaggyNoble** [comment]
What do you mean by "stack chart"? From my Googling, one of these should suit you:

![](https://materialdesignicons.com/icon/chart-line) ![](https://materialdesignicons.com/icon/chart-areaspline)

**Comment by Templarian** [comment]
Stack chart is like a bar chart with sections. Yea, we don't have it.

**Comment by Templarian** [comment]
[![chart-bar-stacked](https://materialdesignicons.com/icon/chart-bar-stacked)](https://materialdesignicons.com/icon/chart-bar-stacked)

**Comment by JapanYoshi** [comment]
I think this may be closer to what OP meant.
![chart-stack2](https://cloud.githubusercontent.com/assets/8707990/23090362/359741c4-f5e0-11e6-939a-bcd50633b72d.png)
![chart-stack](https://cloud.githubusercontent.com/assets/8707990/23090363/381f8320-f5e0-11e6-9c4f-5160931fd8e4.png)

**Comment by Templarian** [comment]
@JapanYoshi Move the lines to be a little more lower (2 pixels for the two left points) for the top section and yea, that will work good for a `chart-line-stacked`?

(don't forget to attach the icon file)

**Comment by JapanYoshi** [comment]
I'm not sure what you mean. Could you clarify?

**Comment by Templarian** [comment]
[![chart-line-stacked](https://materialdesignicons.com/icon/chart-line-stacked)](https://materialdesignicons.com/icon/chart-line-stacked)

Like above. Assigned to you. 👍
