### ISSUE TITLE
Not available: N/A -icon

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#1875]
Not available: N/A -icon

**Comment by Templarian** [comment]
Unfortunately [this would be a useful icon, but] it doesn't translate across languages. The icon pack needs to be targeting as many languages as possible.

I've marked this with a label for us to track these. There is plans to add these in a "helper" icon pack that includes additional language specific icons.

**Comment by Templarian** [comment]
If you can think of an icon to represent this that doesn't rely on text we can work on getting it in. 😄

**Comment by wopian** [comment]
There's already an icon that represents N/A - although not the text form.

https://materialdesignicons.com/icon/block-helper

**Comment by Templarian** [comment]
@wopian Yea, that was added really early on before we started enforcing guidelines (these will be in writing when the new site launches). There will be stories eventually to retroactively alter these icons over time. 👍
