### ISSUE TITLE
Fuel Icon

### ISSUE THREAD

**Issue by xstrex** [Templarian/MaterialDesign#1876]
Icon Request: Fuel

Like this, or something similar: https://cdn2.iconfinder.com/data/icons/fuel/154/danger-fuel-drop-128.png

**Comment by Templarian** [comment]
That looks like the `fire` icon. That should work for this use, unless you need a liquid fuel canister or something. Let us know and we'll reopen.

[![fire](https://materialdesignicons.com/icon/fire)](https://materialdesignicons.com/icon/fire)

**Comment by xstrex** [comment]
Some kind of liquid-fuel icon would be nice to have. In the shape of a drop, but containing a gas pump handle, or flame.

**Comment by JapanYoshi** [comment]
![gastank](https://cloud.githubusercontent.com/assets/8707990/23090424/1fce4f1c-f5e1-11e6-99ff-ceeffc8db7df.png)
![gastank10x](https://cloud.githubusercontent.com/assets/8707990/23090425/1fdbf216-f5e1-11e6-8d01-48a04ef87740.png)
I made a gas tank. Not sure if this will better suit your needs or not.

**Comment by Templarian** [comment]
I like the idea, not sure it's fully recognizable at the smaller size. Hmm... but that is the shape so not sure.

**Comment by xstrex** [comment]
What about something like this style: http://us.123rf.com/450wm/uvaconcept/uvaconcept1409/uvaconcept140901397/31725477-oil-and-gas-industry-iillustration.jpg

**Comment by MrGrigri** [comment]
@JapanYoshi a lot of fuel cans have that 'x' cutout in the middle. Like this: https://cdn1.iconfinder.com/data/icons/industry-2/96/Fuel-512.png

**Comment by JamesCoyle** [comment]
Yeah the German 'Jerry can' design is probably the most recognizable. We also have the `oil` icon which could be used as inspiration for a close up on the nozzle of the `gas-station` icon.

**Comment by PeterShaggyNoble** [comment]
The `barrel` could also work, depending on context:

![](https://materialdesignicons.com/icon/barrel)

**Comment by JapanYoshi** [comment]
![gastank](https://cloud.githubusercontent.com/assets/8707990/25698400/a5dceb74-30f9-11e7-9b22-cce6fe001d8b.png)
![gastank10x](https://cloud.githubusercontent.com/assets/8707990/25698401/a61b1a2a-30f9-11e7-9be5-987a225f44ec.png)
Any better?
![gastank](https://cloud.githubusercontent.com/assets/8707990/25698505/08504170-30fa-11e7-81e7-3b77f5ac738a.png)
![gastank20x](https://cloud.githubusercontent.com/assets/8707990/25698506/0857d818-30fa-11e7-8a5e-0f19eb89da2c.png)

**Comment by JamesCoyle** [comment]
That looks great IMO.

**Comment by Templarian** [comment]
Yea, that top one is perfect @JapanYoshi. 👍

**Comment by JamesCoyle** [comment]
Perhaps a variant with just have a cap on it rather than the spout though?

**Comment by MrGrigri** [comment]
I like the top one

**Comment by Templarian** [comment]
[![fuel](https://materialdesignicons.com/icon/fuel)](https://materialdesignicons.com/icon/fuel)
