### ISSUE TITLE
Sticker Design Feedback

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1878]
As we reach `v2.0.0` there is some some marketing work being done with the new site design and other things. One of those is stickers.

![image](https://cloud.githubusercontent.com/assets/338885/23095829/370b3042-f5d6-11e6-8b70-44a232ea9371.png)
(--- is the cut line).

I was going to go with something complex, but then decided since this is Material Design keep it simple. I'm working with someone I know at sticker mule. So there may be a variant light.

![image](https://cloud.githubusercontent.com/assets/338885/23095951/ba720864-f5d8-11e6-981d-d0c7d2a42d77.png)

Won't be sending this to the printer until  probably next week, so open to feedback until then.

**Comment by r3volution11** [comment]
How about having stickers in different colors? Perhaps 10 or so from the main Material Design spectrum.

**Comment by MrGrigri** [comment]
I do like the bottom one better. What would be the colors of the light one? Just the reverse?

**Comment by Templarian** [comment]
Yea, was thinking MDI = White on Blue; and MDI Light = Blue on White.

MDI regular may be just a bit thicker. The top image is the `vector-square`, but agree it's too bold.

The issue with doing multiple colors is Sticker Mule doesn't do that (and it gets more annoying handing them out at events).

**Comment by JamesCoyle** [comment]
I'd prefer the top one if it had a bit more whitespace around it. I think it only looks too bold because of the ratio of white to blue. Does it have to be hexagonal? I'd have thought round would make more sense for material design.

**Comment by Templarian** [comment]
Okay tweaked and redesigned with feedback. Not sure if I'll two two variants or not, but below are the designs (remember --- is the cut line).

![image](https://cloud.githubusercontent.com/assets/338885/23104242/7f9612e6-f68f-11e6-9f3c-9ed172bca3fd.png)

![image](https://cloud.githubusercontent.com/assets/338885/23104255/c654d4b0-f68f-11e6-911e-10d453909eab.png)

**Comment by Templarian** [comment]
Just ordered the proofs for these. Can't wait to do the full order in a few weeks.

**Comment by JapanYoshi** [comment]
Just a thought, why are they hexagons? They should be rounded squares IMO.

**Comment by Templarian** [comment]
@JapanYoshi Yea, thought abut it also, but hexagons are "hip" I think for open source projects. Just kind of following others.

**Comment by JapanYoshi** [comment]
Why follow others when you can follow Material Design guidelines, amirite?

**Comment by Templarian** [comment]
Sent these off to the printers today.
