### ISSUE TITLE
Plugin for Android Studio

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#188]
Found this on GitHub: https://github.com/konifar/android-material-design-icon-generator-plugin
It's just an idea to create a plugin for Android Studio of this database.

**Comment by Templarian** [comment]
That is a pretty cool plugin. It's a little outside of my scope though. If you want I would be happy to partner with that developer to maybe get the community icons added. Open an issue on their github seeing if the developer is interested. I'm a little busy with icon requests and features for the site, so it would mostly be on their end.

There might be a small issue in that the naming used on this site does not match the official naming on all icons (obviously when I convert icons I just add the `ic_ + name + dp + png`, but the actual names given are more generic and less android specific in many cases for the stock icons).

**Comment by Templarian** [comment]
I'm going to close this for now, link to this issue and I'll reopen it if they are interested. Maybe a drop down to select between "stock" and community.
