### ISSUE TITLE
New fax icon

### ISSUE THREAD

**Issue by Sunpay** [Templarian/MaterialDesign#1883]
The current fax icon contains the word "fax" on it. 
I would like a fax icon without words.
Perhaps something like a phone and printer combined.

Something like [this](https://www.bing.com/images/search?view=detailV2&ccid=98ziU1Lq&id=9D3BB29CD3D8173C275F9117F8FF10C49CF3A8AF&q=fax+icon+svg&simid=608047433512977208&selectedIndex=0&ajaxhist=0 )

**Comment by Templarian** [comment]
Actually we're working to get rid of English specific text based icons with actual glyphs. We should actually replace the `fax` icon completely.

![image](https://cloud.githubusercontent.com/assets/338885/23192458/20cad4aa-f869-11e6-9159-4a3436c6f932.png)

**Comment by Sunpay** [comment]
Hi Austin

That’s really great news.

The question is when?

Alan Macdonald
Sunpay Pty Ltd
10/61 Burnett St, Buderim, Qld, 4556
P: (07) 5456 2631 | M: 0415 431 540 | F: (07) 5302 6439 | W: www.sunpay.com.au<http://www.sunpay.com.au/>
________________________________
Disclaimer: This e-mail and any attachments are confidential and are intended solely for the use of the individual or entity to whom it is addressed. If you are not the intended recipient, any use, dissemination, forwarding, printing, or copying of this e-mail and any attachments is strictly prohibited. If you have received this e-mail in error, please telephone our Office on (07) 5456 2631 or by reply e-mail to the sender. Please destroy the original transmission and its contents.
________________________________

**Comment by Templarian** [comment]
@Sunpay Maybe something like:

[![fax](https://materialdesignicons.com/icon/fax)](https://materialdesignicons.com/icon/fax)

**Comment by Sunpay** [comment]
I would make the phone to the left bigger as it isn’t obvious to me that this is a phone.

Perhaps extend it to the top and bottom of the printer icon

**Comment by Templarian** [comment]
Maybe the phone icon above the printer type icon might be better.

**Comment by Sunpay** [comment]
Yes, give it a try and perhaps even provide both options, phone on top and phone and phone on left side.

However, I think that the phone on the left side is more consistent with actual fax machines and existing fax icons.

Some inspiration: http://www.flaticon.com/free-icons/fax_572
