### ISSUE TITLE
Bezier Icon

### ISSUE THREAD

**Issue by matham** [Templarian/MaterialDesign#1884]
Hey,

Can a bezier icon be added? Some example images can be seen [here](https://medium.com/sketch-app/mastering-the-bezier-curve-in-sketch-4da8fdf0dbbb#.672afnjia).

Thanks!

**Comment by PeterShaggyNoble** [comment]
This any use?

![](https://materialdesignicons.com/icon/vector-curve)

**Comment by matham** [comment]
Did you forget to include something? I don't see anything but your text in your post.

**Comment by MrGrigri** [comment]
try this [link](https://materialdesignicons.com/icon/vector-curve) instead. There is an icon `vector-curve` already in the pack.

**Comment by matham** [comment]
Thanks, that's perfect.

I did go through the tag groups one by one, but didn't see it. Maybe there should be a way to more easily tag icons with multiple names so that e.g. you could find it under bezier? 

Also, the vector tag only currently links to one thing; `vector-square` but it probably should link to everything that comes up when you search for vector (I hadn't realized that's what I should have searched for).

**Comment by JamesCoyle** [comment]
We already have an aliasing system and have been discussing icon discovery for over a year at this point. The tagging system we have currently has been pretty neglected and doesn't really cover all of the icons it should anymore. We're hoping to have some improvements in the new version of the site which is currently in development.

**Comment by PeterShaggyNoble** [comment]
Alias added.
