### ISSUE TITLE
VSCO Icon

### ISSUE THREAD

**Issue by wildramen** [Templarian/MaterialDesign#1886]
I noticed the VSCO icon is not there. 

They do have a page dedicated for logo: [VSCO Share](https://vsco.co/user/share)

**Comment by Templarian** [comment]
This is going to be too niche in terms of social media.

If we go back and create a brand icon pack in the future we'll look for the labels.

**Comment by PeterShaggyNoble** [comment]
Here's the path for a 24*24 icon, if needed in the future:

    <path d="M12,0.003c-6.627,0-12,5.373-12,12s5.373,12,12,12c6.627,0,12-5.373,12-12S18.627,0.003,12,0.003z M18.642,16.455l-1.592-1.221c0.381-0.594,0.662-1.257,0.814-1.969l1.986,0.261C19.644,14.593,19.228,15.585,18.642,16.455z M12,20.003c-0.185,0-0.366-0.015-0.547-0.028l0.262-1.987c0.095,0.005,0.189,0.014,0.286,0.014c0.639,0,1.254-0.102,1.831-0.287 l0.765,1.846C13.781,19.843,12.91,20.003,12,20.003z M7.53,18.634l1.222-1.592c0.594,0.383,1.258,0.666,1.971,0.821l-0.262,1.988 C9.393,19.642,8.401,19.223,7.53,18.634z M12,17.003c-2.757,0-5-2.243-5-5s2.243-5,5-5c2.757,0,5,2.243,5,5S14.757,17.003,12,17.003 z M4,12.003c0-0.189,0.015-0.374,0.028-0.559l1.987,0.262C6.01,11.805,6,11.902,6,12.003c0,0.632,0.099,1.241,0.281,1.814 l-1.846,0.765C4.157,13.771,4,12.906,4,12.003z M6.143,10.713L4.154,10.45c0.21-1.063,0.629-2.052,1.216-2.92l1.592,1.221 C6.58,9.343,6.298,10.004,6.143,10.713z M12,4.003c0.183,0,0.363,0.015,0.544,0.028l-0.262,1.987 C12.188,6.012,12.095,6.003,12,6.003c-0.635,0-1.247,0.1-1.821,0.283L9.414,4.44C10.227,4.161,11.094,4.003,12,4.003z M16.455,5.362 l-1.221,1.592c-0.591-0.379-1.251-0.659-1.959-0.812l0.262-1.987C14.598,4.362,15.587,4.778,16.455,5.362z M17.986,12.272 C17.99,12.182,18,12.093,18,12.003c0-0.642-0.103-1.259-0.29-1.839L19.557,9.4C19.839,10.217,20,11.09,20,12.003 c0,0.179-0.015,0.354-0.027,0.531L17.986,12.272z M20.389,8.763c-0.221-0.573-0.497-1.117-0.825-1.626l1.618-1.176 c0.448,0.679,0.816,1.413,1.106,2.185L20.389,8.763z M19.17,8.477l-1.847,0.765c-0.33-0.636-0.772-1.202-1.298-1.679l1.218-1.588 C18.042,6.67,18.698,7.52,19.17,8.477z M16.88,4.447c-0.509-0.329-1.054-0.606-1.626-0.829l0.617-1.899 c0.772,0.292,1.506,0.66,2.185,1.11L16.88,4.447z M14.302,3.311c-0.58-0.153-1.182-0.249-1.802-0.283v-2 c0.834,0.038,1.644,0.166,2.42,0.381L14.302,3.311z M11.5,3.028c-0.62,0.034-1.222,0.13-1.802,0.283L9.079,1.409 c0.776-0.214,1.586-0.343,2.421-0.381V3.028z M8.746,3.619C8.173,3.841,7.629,4.118,7.12,4.448L5.944,2.829 c0.679-0.449,1.413-0.818,2.185-1.11L8.746,3.619z M8.491,4.824l0.765,1.847C8.62,6.999,8.052,7.438,7.574,7.962L5.986,6.744 C6.683,5.948,7.533,5.295,8.491,4.824z M4.436,7.137C4.108,7.646,3.832,8.19,3.611,8.763L1.711,8.146 C2.002,7.374,2.37,6.64,2.818,5.961L4.436,7.137z M3.305,9.715c-0.152,0.579-0.247,1.181-0.28,1.799h-2 c0.037-0.833,0.164-1.642,0.377-2.417L3.305,9.715z M3.026,12.514c0.035,0.618,0.131,1.219,0.284,1.798L1.408,14.93 c-0.214-0.775-0.343-1.583-0.382-2.416H3.026z M3.619,15.263c0.222,0.571,0.499,1.114,0.828,1.622l-1.618,1.176 c-0.449-0.677-0.817-1.41-1.109-2.18L3.619,15.263z M4.818,15.505l1.847-0.765c0.329,0.64,0.77,1.21,1.296,1.69l-1.218,1.587 C5.945,17.319,5.289,16.466,4.818,15.505z M7.132,19.565c0.508,0.328,1.051,0.603,1.622,0.824l-0.617,1.899 c-0.77-0.29-1.503-0.658-2.18-1.105L7.132,19.565z M9.705,20.696c0.578,0.152,1.178,0.247,1.795,0.281v2 c-0.832-0.038-1.639-0.166-2.414-0.379L9.705,20.696z M12.5,20.977c0.617-0.034,1.217-0.129,1.795-0.281l0.618,1.903 c-0.774,0.213-1.581,0.341-2.413,0.379V20.977z M15.247,20.389c0.571-0.221,1.114-0.497,1.621-0.824l1.176,1.618 c-0.677,0.447-1.409,0.815-2.18,1.105L15.247,20.389z M15.519,19.176l-0.765-1.847c0.639-0.331,1.208-0.774,1.688-1.303l1.588,1.218 C17.332,18.045,16.48,18.703,15.519,19.176z M19.554,16.885c0.329-0.508,0.605-1.051,0.828-1.622l1.899,0.617 c-0.292,0.771-0.66,1.503-1.109,2.18L19.554,16.885z M20.69,14.312c0.154-0.579,0.25-1.179,0.284-1.798h2 c-0.039,0.833-0.167,1.641-0.382,2.416L20.69,14.312z M20.975,11.514c-0.033-0.619-0.128-1.22-0.28-1.8l1.903-0.618 c0.213,0.776,0.341,1.584,0.377,2.418H20.975z M20.593,5.153L18.98,6.325c-0.385-0.473-0.817-0.906-1.289-1.293l1.171-1.613 C19.501,3.932,20.081,4.513,20.593,5.153z M5.138,3.42l1.171,1.613C5.837,5.419,5.405,5.852,5.02,6.325L3.407,5.153 C3.919,4.513,4.498,3.932,5.138,3.42z M3.419,18.867l1.612-1.172c0.385,0.471,0.817,0.901,1.289,1.286l-1.171,1.613 C4.51,20.083,3.93,19.505,3.419,18.867z M18.851,20.594l-1.171-1.613c0.472-0.384,0.904-0.815,1.289-1.286l1.613,1.171 C20.07,19.505,19.49,20.083,18.851,20.594z"/>
