### ISSUE TITLE
Icon Request: YouTube Icon

### ISSUE THREAD

**Issue by YahyaElharony** [Templarian/MaterialDesign#1887]
I shocked when I didn't find a YouTube icon!
Please try to add it as soon as possible.

**Comment by wopian** [comment]
It's https://materialdesignicons.com/icon/youtube-play 😉

**Comment by YahyaElharony** [comment]
Oh, How! 😄 
I searched for it by " youtube " keyword and toggled the tags and it didn't exist in the " Social " tag.
Anyway, thanks @wopian  for your efforts! ❤️
