### ISSUE TITLE
Incorrect Names In preview.html (heart-half-*)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1888]
In the preview.html file included with the webfont download, the following icons are named incorrectly:

- [ ] `mdi-heart-half-part` should be `mdi-heart-half`.
- [ ] `mdi-heart-half-outline` should be `mdi-heart-half-full`.
- [ ] `mdi-heart-half-part-outline` should be `mdi-heart-half-outline`.

**Comment by Templarian** [comment]
@PeterShaggyNoble These won't be reflected until the next release. I renamed them last week getting ready for the `v1.9.xx` release.

**Comment by Templarian** [comment]
If you're curious why it's to better match with Material Design Icons light and the naming just seems confusing.

**Comment by PeterShaggyNoble** [comment]
I figured the might have been renamed since the last release but posted just in case.
