### ISSUE TITLE
Remove package-variant?

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1892]
[![](https://materialdesignicons.com/icon/package-variant)](https://materialdesignicons.com/icon/package-variant)[![](https://materialdesignicons.com/icon/package-variant-closed)](https://materialdesignicons.com/icon/package-variant-closed)

These really don't fit the material style at all as they use dimensionality.

**Comment by Templarian** [comment]
I know, but it's useful and I actually use this icon at work. 📦 

I agree it doesn't fit as well, but it's useful for those wanting a more literal shipping box.
