### ISSUE TITLE
Family

### ISSUE THREAD

**Issue by jethro-2018** [Templarian/MaterialDesign#1894]
Icon Request: Family

Something like this: http://www.flaticon.com/free-icon/family_284134#term=family&page;=1&position;=1

**Comment by PeterShaggyNoble** [comment]
Something like [this](https://icons8.com/icons/11194/family-man-woman) might work better at smaller sizes.

**Comment by rtvb** [comment]
I would opt for multiple variations:

- man-woman-kid
- man-woman
- man-man
- woman-woman
- man-kid
- woman-kid

**Comment by PeterShaggyNoble** [comment]
See also Google's `account child` icons.

![account child invert](https://user-images.githubusercontent.com/15157491/37103472-3b9ff86c-2222-11e8-9153-8cb9484750e7.png) ![image](https://user-images.githubusercontent.com/15157491/37103495-4c5268c0-2222-11e8-8ccb-825cb3a63c14.png)

**Comment by metbril** [comment]
This would be an extension to the current `human-male-woman` icon

**Comment by PeterShaggyNoble** [comment]
Going to close this out as, between #3015 and the icons above which were added in #3413, this request should be covered.

**Comment by metbril** [comment]
#3015 does not yet cover a family, eg male-female-kid

**Comment by Templarian** [comment]
@metbril Might be difficult at the small size to fit 3 people in.
