### ISSUE TITLE
Tweeter icon

### ISSUE THREAD

**Issue by xrshck** [Templarian/MaterialDesign#1896]

**Comment by PeterShaggyNoble** [comment]
What's Tweeter? Or do you mean the type of speaker?

![](https://materialdesignicons.com/icon/speaker)

**Comment by xrshck** [comment]
sorry, i mean twitter

**Comment by PeterShaggyNoble** [comment]
It exists already:

![](https://materialdesignicons.com/icon/twitter) ![](https://materialdesignicons.com/icon/twitter-box)
