### ISSUE TITLE
Safe Icon

### ISSUE THREAD

**Issue by davcpas1234** [Templarian/MaterialDesign#1897]
Would if be possible to add a safe icon, similar to the one below?

![](https://maxcdn.icons8.com/Share/icon/Finance//safe1600.png)

**Comment by JapanYoshi** [comment]
![safe](https://cloud.githubusercontent.com/assets/8707990/24079977/4cc02a78-0cd8-11e7-990a-708aba48858b.png)
![safe 10x](https://cloud.githubusercontent.com/assets/8707990/24079978/4cc64e6c-0cd8-11e7-8bf1-96107970a495.png)

**Comment by MrGrigri** [comment]
Idk, those hinges look out of place. What about a handle instead?

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/32164111-627f17fa-bd56-11e7-8e21-6d34a701cb0c.png)
![image](https://user-images.githubusercontent.com/15905797/32164126-6c0f44ca-bd56-11e7-8b5f-36900aa6d288.png)
[safe.zip](https://github.com/Templarian/MaterialDesign/files/1426689/safe.zip)

**Comment by Templarian** [comment]
[![safe](https://materialdesignicons.com/icon/safe)](https://materialdesignicons.com/icon/safe)
