### ISSUE TITLE
Default Clock app like Timer Icon

### ISSUE THREAD

**Issue by niteshvuliv** [Templarian/MaterialDesign#1898]
Hi Team, the sand timer icon currently on the site is not as good as the one in default clock app.

![image](https://cloud.githubusercontent.com/assets/18456055/23346517/dd88068e-fcc0-11e6-80aa-6607dc0b80b3.png)

I need this icon for one of my project. Kindly provide me the same. Moreover, it will also be a good asset for the site.

**Comment by Templarian** [comment]
[![timer-sand](https://materialdesignicons.com/icon/timer-sand)](https://materialdesignicons.com/icon/timer-sand) [![timer-sand-full](https://materialdesignicons.com/icon/timer-sand-full)](https://materialdesignicons.com/icon/timer-sand-full) [![timer-sand-empty](https://materialdesignicons.com/icon/timer-sand-empty)](https://materialdesignicons.com/icon/timer-sand-empty)
