### ISSUE TITLE
Fat arrows

### ISSUE THREAD

**Issue by timmutton** [Templarian/MaterialDesign#190]
I'd love to have "fat" arrows (especially an up arrow for my usecase)

- [x] arrow-up-bold
- [x] arrow-down-bold
- [x] arrow-left-bold
- [x] arrow-right-bold

**Comment by Templarian** [comment]
![arrow-down](https://cloud.githubusercontent.com/assets/338885/6434117/4f92dec4-c047-11e4-9739-214cae35a398.png) ![arrow-down-bold](https://cloud.githubusercontent.com/assets/338885/6434122/5bff4512-c047-11e4-8790-f9f226d8353f.png)

Do you mean bold like the above style?

**Comment by timmutton** [comment]
ooh, yes thats perfect

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/arrow-up-bold
http://materialdesignicons.com/icon/arrow-down-bold
http://materialdesignicons.com/icon/arrow-right-bold
http://materialdesignicons.com/icon/arrow-left-bold
