### ISSUE TITLE
Okta Icon

### ISSUE THREAD

**Issue by joeltobey** [Templarian/MaterialDesign#1901]
It would be nice to have this for the optional log in button

**Comment by MrGrigri** [comment]
What exactly is Okta? Is this [their](https://www.okta.com/) site? What is their icon; a circle?

**Comment by joeltobey** [comment]
Yes, that's their site. It's a thicker circle than what I currently see.

**Comment by joeltobey** [comment]
We use it for Single Sign On. So I'm planning on having a button with the circle icon and "Log in using Okta".

**Comment by Templarian** [comment]
Closed this out, but thought I left a comment. My bad (processing a lot of issues lately across various repos).

I think Okta is going to be too specific/generic for the pack. For these we suggest using an inline SVG or Vector Drawable depending on your platform.

Thanks for the icon request, sorry again for not leaving a comment.
