### ISSUE TITLE
currency-eth

### ISSUE THREAD

**Issue by iamtpage** [Templarian/MaterialDesign#1902]
Would it be possible to add an Ethereum icon?  We have a bitcoin one, and ethereum is the next largest crypto-currency

Picture:
https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a2bcf4f8-9a5d-4f85-873b-cf94ce537eb0.png
![image](https://cloud.githubusercontent.com/assets/8901422/23445472/ae51a9ac-fe09-11e6-8e25-bb3b3b354dd0.png)

**Comment by JapanYoshi** [comment]
I've literally never heard of this until today. I don't think it is of any value.

**Comment by iamtpage** [comment]
Hi there, 

To back up my claims above I have provided some links:

https://coinmarketcap.com -  this site has all the major crypto currency listed as well as their market cap value. You can see that ethereum is the second most popular by far, and over time this popularity will grow. 

https://www.coinbase.com - this site is the world's most popular site to buy and sell crypto-currency. The website and the mobile app both focus on Bitcoin and Ethereum. The website also has a link on it's homepage with an explanation on Ethereum if you would like to learn more. 

https://www.ethereum.org - the home page, where you can read how it works and what is possible to do with it. 

Please consider adding this to MDI, it would be a major benefit to myself (and others) as well as preventing us from having to use something other than MDI for icons. We're great fans of MDI and appreciate all the hard work you guys do!

**Comment by PeterShaggyNoble** [comment]
I'd concur with @JapanYoshi.

However, it it were to be included as a currency icon, the symbol they use is a capital xi: Ξ ([Source](https://forum.ethereum.org/discussion/1007/the-symbol-for-ether-is)).

**Comment by JamesCoyle** [comment]
Do any major sites accept it as payment? If we start adding new cryptocurrencies people are just gonna be requesting their favorite currencies constantly. I don't think this is used enough to warrant an icon just yet but once it has developed and sites start accepting it we can reconsider.

**Comment by Templarian** [comment]
Closing this one out as its far too niche for this icon pack.

**Comment by Templarian** [comment]
Wait, does this have a nice black glphy (solid color)?

We might be able to add this.

**Comment by iamtpage** [comment]
Templarian,

I appreciate that you are reconsidering, and please forgive me for not being familiar with what a glphy is.  I have searched for a few examples of the icon with a solid color and found these:

https://www.shareicon.net/ether-ethereum-eth-117397 (Also has SVG files as well as different sizes)

![image](https://www.shareicon.net/download/128x128//2016/07/08/117397_eth_512x512.png)

And I managed to find this one:

https://static.tildacdn.com/tild3166-6662-4339-b933-363732356333/logoiconblack.png

![image](https://static.tildacdn.com/tild3166-6662-4339-b933-363732356333/logoiconblack.png)

Are either one of these acceptable?

**Comment by PeterShaggyNoble** [comment]
Their [favicon](https://www.ethereum.org/favicon.ico) is a single colour version of the @iamtpage originally posted.

**Comment by Templarian** [comment]
I think we can add this one. Reopening the issue. Might need a more 24x24 optimized glyph.

**Comment by PeterShaggyNoble** [comment]
There are a couple of SVGs in their GitHub repo that might be of use: https://github.com/ethereum/ethereum.org/tree/master/public/images

**Comment by GreenTurtwig** [comment]
![puush-linux 2017-06-14 at 02 42 13](https://user-images.githubusercontent.com/15905797/27135195-d4d52168-510f-11e7-8926-bc131106d7f1.png)
![puush-linux 2017-06-14 at 02 42 19](https://user-images.githubusercontent.com/15905797/27135197-d6316a30-510f-11e7-907b-47646f8fb9cd.png)
[currency-eth.zip](https://github.com/Templarian/MaterialDesign/files/1074750/currency-eth.zip)

**Comment by Templarian** [comment]
[![currency-eth](https://materialdesignicons.com/icon/currency-eth)](https://materialdesignicons.com/icon/currency-eth)
