### ISSUE TITLE
Updated "Sandbox"

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1903]
I hope it's OK to post this here as it's not an "issue" but, for the few that were using or interested in my sandbox, I've just finished giving it a major overhaul and it can now be found at http://mdi.houseofdesign.ie/.

I've given it a bit more of a "Material-y" look, changed the colouring to match that of the MDI site and made it easier to access some of the features, such as direct linking to categories & search results.

The vast majority of the work was behind the scenes with the JavaScript being rewritten from scratch and loaded chock full of ES6 goodies! For that reason, I'm afraid it's Chrome only. I'll also be adding the ability to export/import favourites from `localStorage` soon.

Once that's done, the main focus will be on categorising (tagging) and aliasing everything and feeding that work back into the MDI project.

Anyway, hopefully someone will find it useful. Feedback would be most welcome.

Oh, and, as an added bonus ... **[Shazam](http://mdi.houseofdesign.ie/light/)!**

**Comment by MrGrigri** [comment]
This is a great site, however, where are the attributions to the designer?

**Comment by PeterShaggyNoble** [comment]
The primary purpose for this project (at least initially) was as a replacement for [preview.html](https://cdn.materialdesignicons.com/1.8.36/) to make it easier for my designer to find the icons he needed. The contributor info isn't necessary there but there are links throughout to the main site and its individual icon pages.

**Comment by PeterShaggyNoble** [comment]
The ability to export your favourite icons from and import them to `localStorage` has been added; useful if you're using this on a regular basis in multiple browsers. Importing won't overwrite any existing favourites, just add to them.

**Comment by Templarian** [comment]
Awesome, as I work on the new site hopefully we can get some more community involvement and these features in. Once I'm back from vacation I'll get the latest code committed.

https://github.com/Templarian/MaterialDesign-Site

Let me know if there is any metadata you need in the json.

**Comment by PeterShaggyNoble** [comment]
Thanks, @Templarian.

I'll be rebuilding my JS object tomorrow to include the IDs (for possible future use) & authors (need to figure out where/how to display them on the page) and to include the aliases properly.

One thing I've added to my object which might be useful to add to meta.json is keywords; terms people might use to search for an icon but which wouldn't qualify as aliases. For example, `cigarette` would work as an alias of `smoking` but not necessarily for `smoking-off. If it were added as a keyword, though, it would allow `smoking-off` to be returned when someone searched for `cigarette`.

**Comment by PeterShaggyNoble** [comment]
I've just finished off a major upgrade which allows "unreleased (as yet)" icons to be included and given them [their own section](http://mdi.houseofdesign.ie/?category=soon) to highlight that they're not yet available.

Next on my todo list is to start working with the icon API to improve & expand the options for downloading individual icon files (@templarian, do you know yet how the new API is going to be handling the Light icons or will it be a separate API).

I could also do with a bit of feedback on the favourites; currently they work with the icon name but, with the recent addition of the IDs to the JS object, using them instead is an option. Both options, though, come with pros and cons:
- Using the name allows re-purposed icons (e.g., `orbit`) to be removed from a user's favourites but that also means that renamed icons (e.g., `download-network`) are removed also.
- Using IDs instead reverses that issue; renamed icons remain in favourites but so do re-purposed icons.
- Using IDs has the additional downside of not being able to "share" favourites between the regular and light versions of the page, as the IDs for the Light icons differ from those in the regular set.
I'm leaning towards continuing to use names but I'd like to know what others think.

**Comment by JapanYoshi** [comment]
I think the size slider should have shortcuts at 24px, 48px, 72px, etc. sizes.

**Comment by PeterShaggyNoble** [comment]
Yeah, I've been thinking about that; limiting it to the size options available in the CSS. I'll add it to my todo list.

**Comment by Templarian** [comment]
I'm going to open up access this weekend to allow you guys to alias and tag icons (and if I get time there is an option to set related icons).

We need to get the meta.json file more complete for the 2.0 release. This should give your app more useful data @PeterShaggyNoble (plus the new site needs it to view correctly).

**Comment by PeterShaggyNoble** [comment]
Lots of updates to this over the past few days, mainly in optimisation. It also has a new address (https://petershaggynoble.github.io/MDI-Sandbox/) and a new category for "retired" icons, for people who may still have use for them.

**Comment by MrGrigri** [comment]
You should add a 'copy SVG data' which will copy the path data for the icon selected.

**Comment by PeterShaggyNoble** [comment]
Good idea, @MrGrigri; I'll add that to tomorrow's list.
