### ISSUE TITLE
Icons missing from Github repo

### ISSUE THREAD

**Issue by rgriffith** [Templarian/MaterialDesign#1904]
Minor, but I can't seem to locate the [selection icon](https://materialdesignicons.com/icon/selection) that is on the website in the Github repo. At least, it's not in master and my assumption was the website is reflecting the master branch.

**Comment by PeterShaggyNoble** [comment]
I ran a script on the SVG directory and found a few other files that were missing:

- account-star
- account-star-variant
- biohazard
- bookmark-plus-outline
- briefcase-check
- calendar-multiple-check
- case-sensitive-alt
- chart-line-stacked
- close-box
- close-box-outline
- comment-multiple-outline
- firefox
- format-quote
- format-wrap-square
- format-wrap-tight
- format-wrap-top-bottom
- format-wrap-inline
- github-circle
- google-circles-group
- guitar-electric
- guitar-pick
- guitar-pick-outline
- heart-half-full
- houzz
- image-multiple
- loading
- lock-open
- lock-open-outline
- lock-pattern
- math-compass
- motorbike
- nutrition
- phone-settings
- regex
- selection
- ticket
- toggle-switch
- trophy
- trophy-award
- trophy-variant
- unfold-less
- unfold-more
- vibrate
- view-grid
- wrap

**Comment by Templarian** [comment]
Most of these are due to renames that were not fixed in the repo. Need to go through this list and rename the source files from the old names.

**Comment by Templarian** [comment]
`selection` and `selection-off` are in the repo now. I also updated the point count to fix some issues with the selection icon's SVG data. Don't mix these up with the `select` icons these are used for difference uses.

Going to leave this issue opened until I've fixed these other icon issues in the repo.

**Comment by PeterShaggyNoble** [comment]
Added `white-balance-iridescent` to the list.

**Comment by rgriffith** [comment]
Thank you for correcting the issue @PeterShaggyNoble, much appreciated.

**Comment by gytdau** [comment]
Oh, this looks to be related to #1927.

**Comment by PeterShaggyNoble** [comment]
Not quite, @gytdau; see my reply to you on #1927 for more information.

**Comment by PeterShaggyNoble** [comment]
Checked a few off the list and added a couple more.

@templarian, let me know if you'd like me to send you the link to my test script.
