### ISSUE TITLE
Cancel icon seems to be missing from the css file?

### ISSUE THREAD

**Issue by Anupheaus** [Templarian/MaterialDesign#1905]
Using v1.8.36 but the cancel icon does not appear to be working?

**Comment by PeterShaggyNoble** [comment]
See #1864.

**Comment by RogerPMH** [comment]
In the meantime you might use mdi-block-helper, it's basically the same icon as Google's cancel.

**Comment by PeterShaggyNoble** [comment]
Thanks, @RogerPMH; I should have pointed that out myself.

![](https://materialdesignicons.com/icon/block-helper)
