### ISSUE TITLE
Update Icons: smoking & smoking-off

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1906]
The [smoking](https://material.io/icons/#ic_smoking_rooms) and [smoking-off](https://material.io/icons/#ic_smoke_free) stock icons have been changed.

**Comment by Templarian** [comment]
I kind of like the more minimal design then the one they added.

Not sure if this is an upgrade to the existing design.

**Comment by CoDEmanX** [comment]
The ones we have in MDI are an original design by me. By the time of creation, Google did not have such icons.On 04-Mar-2017 06:45, Austin Andrews <notifications@github.com> wrote:I kind of like the more minimal design then the one they added.
Not sure if this is an upgrade to the existing design.

**Comment by PeterShaggyNoble** [comment]
Could we add the Google ones as variants, maybe?

**Comment by Templarian** [comment]
It will probably be fine just using the current two icons. Too minor of a difference.

**Comment by wopian** [comment]
imo the 2 Google ones look far nicer 🤔

**Comment by Templarian** [comment]
[![smoking](https://materialdesignicons.com/icon/smoking)](https://materialdesignicons.com/icon/smoking) [![smoking-off](https://materialdesignicons.com/icon/smoking-off)](https://materialdesignicons.com/icon/smoking-off)
