### ISSUE TITLE
Google Maps Navigation

### ISSUE THREAD

**Issue by jonnywright** [Templarian/MaterialDesign#1909]
The navigation icons from Google Maps (not to be confused with app navigation icons) in vector drawable format would be awesome

![Icons](https://i.stack.imgur.com/U92RD.png)

**Comment by JamesCoyle** [comment]
Could probably add some of the basic ones like turn/bear left/right and uturn but the roundabout ones might be a bit much. Could also just add these as generic arrow icons that mimic the arrows available in unicode.

**Comment by CoDEmanX** [comment]
From Google Maps APK:

![grafik](https://user-images.githubusercontent.com/1309249/62775534-34864e80-baa8-11e9-9bd4-33cd062fae38.png)


[google_maps_navigation.zip](https://github.com/Templarian/MaterialDesign/files/3486085/google_maps_navigation.zip)

**Comment by CoDEmanX** [comment]
There are also two-tone ones, but we can't really add them at this point.

**Comment by goyney** [comment]
There are a lot of icons in this request and we have a good number of them. If there a specific icons needed, please open a single request per icon we don't have for consideration. Thanks.
