### ISSUE TITLE
Google Search Icon Request

### ISSUE THREAD

**Issue by jaredrummler** [Templarian/MaterialDesign#191]
Please add the search icon: https://github.com/google/material-design-icons/blob/master/action/svg/design/ic_search_24px.svg

The path from the SVG linked above did not work with a `VectorDrawable` on Android. I created a new SVG in Illustrator and it worked great:

```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="24dp"
    android:viewportHeight="24"
    android:viewportWidth="24"
    android:width="24dp" >

    <path
        android:fillColor="#000"
        android:pathData="M15.5,14h-0.8l-0.3-0.3c1-1.1,1.6-2.6,1.6-4.2C16,5.9,13.1,3,9.5,3S3,5.9,3,9.5S5.9,16,9.5,16c1.6,0,3.1-0.6,4.2-1.6l0.3,0.3v0.8l5,5l1.5-1.5L15.5,14z M9.5,14C7,14,5,12,5,9.5S7,5,9.5,5S14,7,14,9.5S12,14,9.5,14z" />

</vector>
```

**Comment by Templarian** [comment]
The search icon exists, many icon names have been slightly altered I'll add an alias for that to make seaching easier.

http://materialdesignicons.com/icon/magnify

Click the `</>` drop down and view the vector drawable. It is also generated in the 5.x download package.
```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
       android:height="24dp"
       android:width="24dp"
       android:viewportWidth="24"
       android:viewportHeight="24">
    <path android:fillColor="#000" android:pathData="M9.5,3A6.5,6.5 0 0,1 16,9.5C16,11.11 15.41,12.59 14.44,13.73L14.71,14H15.5L20.5,19L19,20.5L14,15.5V14.71L13.73,14.44C12.59,15.41 11.11,16 9.5,16A6.5,6.5 0 0,1 3,9.5A6.5,6.5 0 0,1 9.5,3M9.5,5C7,5 5,7 5,9.5C5,12 7,14 9.5,14C12,14 14,12 14,9.5C14,7 12,5 9.5,5Z" />
</vector>
```

**Comment by Templarian** [comment]
Added the alias `search` to the `magnify` icon. I'm going to close this. Let me know if you have any issues.

**Comment by jaredrummler** [comment]
Ah. I missed it. Thanks.

**Comment by Templarian** [comment]
Np, it's an open issue #90. Might try to get through that bug this week since it will probably come up a lot.
