### ISSUE TITLE
Approval Icon

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#1914]
Here is an approval icon I am using in my own project. If you want to add it to the repo, I believe that others will take advantage. I used the octagram and a checkmark. Almost like a 'seal of approval' icon. It could be called `check-octagram`, `approval`, `approve`, or `certify`; with any of the others as aliases. 

#### approval
![approval](https://cloud.githubusercontent.com/assets/4528551/23633857/a6506156-0284-11e7-90fd-1d4567219284.png)

[approval.zip](https://github.com/Templarian/MaterialDesign/files/822755/approval.zip)

**Comment by Templarian** [comment]
[![approval](https://materialdesignicons.com/icon/approval)](https://materialdesignicons.com/icon/approval)

**Comment by PeterShaggyNoble** [comment]
I suggest aliasing this as `decagram-check`.

**Comment by Templarian** [comment]
Done. 👍
