### ISSUE TITLE
Loading Missing from webfont.

### ISSUE THREAD

**Issue by ddeakes** [Templarian/MaterialDesign#1917]
https://materialdesignicons.com/icon/loading

Loading icon is missing from the webfont... is there a branch that might have it in? Or anyway I can manually compile it in?

Thanks.

**Comment by Templarian** [comment]
It's coming in the `v1.9.xx` release. Please reference #1891 for progress.

(we've added a lot of icons recently and new features so this is going to be a big release before `v2.x.xx`

**Comment by Templarian** [comment]
https://materialdesignicons.com/history To see the icons added after `v1.8.36`'s release.

**Comment by PeterShaggyNoble** [comment]
In the meantime, to manually build a font with `loading` included, you can download the webfont files & the SVG for the `loading` and then use [IcoMoon](https://icomoon.io/) to create your own font files.
