### ISSUE TITLE
currency-jpy or currency-cny

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#1918]
The Japanese Yen and Chinese Yuan / Renminbi share the same symbol. I have made a Material Icon for it. I may adjust the diagonal strokes later.

![currency-jpy](https://cloud.githubusercontent.com/assets/8707990/23706337/20fda7a6-0451-11e7-91bb-59dfdb58d9b3.png)
![currency-jpy 10x](https://cloud.githubusercontent.com/assets/8707990/23706338/2100ee2a-0451-11e7-8258-7109554e7c25.png)

**Comment by JapanYoshi** [comment]
There, I slightly thickened the diagonal strokes up to exactly 2 pixels. :)

![currency-jpy](https://cloud.githubusercontent.com/assets/8707990/23706411/63b07cf4-0451-11e7-957d-20ee920f5ade.png)
![currency-jpy 10x](https://cloud.githubusercontent.com/assets/8707990/23706412/63d3d168-0451-11e7-8e94-5a44a0edd99a.png)

Here's the ZIP file!
[currency-jpy.zip](https://github.com/Templarian/MaterialDesign/files/827759/currency-jpy.zip)

**Comment by Templarian** [comment]
I thought we had that, but weird it's not there. 😕 Seems odd we didn't have that before.

**Comment by wopian** [comment]
It's missing a couple other major currencies too:
- Swiss franc (₣)
- Korean won (₩)

**Comment by JapanYoshi** [comment]
![currency-chf](https://cloud.githubusercontent.com/assets/8707990/24024956/a0b66168-0afa-11e7-8687-25b8ce2e839c.png)![currency-krw](https://cloud.githubusercontent.com/assets/8707990/24024957/a2566356-0afa-11e7-8aee-bcfceb19017d.png)
![currency-chf 10x](https://cloud.githubusercontent.com/assets/8707990/24024959/a45310fa-0afa-11e7-8a73-72834c54a103.png)![currency-krw 10x](https://cloud.githubusercontent.com/assets/8707990/24024960/a6e794e4-0afa-11e7-8f5e-8f551f2d76e9.png)

**Comment by Templarian** [comment]
@JapanYoshi CAn you link the zip for those two. Thanks!

**Comment by JapanYoshi** [comment]
[material-currency.zip](https://github.com/Templarian/MaterialDesign/files/849518/material-currency.zip)
I got lazy and zipped an Inkscape SVG (which has layers). Hope it works

**Comment by Templarian** [comment]
[![currency-twd](https://materialdesignicons.com/icon/currency-twd)](https://materialdesignicons.com/icon/currency-twd) [![currency-chf](https://materialdesignicons.com/icon/currency-chf)](https://materialdesignicons.com/icon/currency-chf) [![currency-jpy](https://materialdesignicons.com/icon/currency-jpy)](https://materialdesignicons.com/icon/currency-jpy) [![currency-krw](https://materialdesignicons.com/icon/currency-krw)](https://materialdesignicons.com/icon/currency-krw) [![currency-cny](https://materialdesignicons.com/icon/currency-cny)](https://materialdesignicons.com/icon/currency-cny)

Even though they are the same symbol I made it two different characters in the system.

Thanks @JapanYoshi!
