### ISSUE TITLE
CCTV security camera

### ISSUE THREAD

**Issue by metbril** [Templarian/MaterialDesign#1919]
Something similar like this:

http://www.flaticon.com/search?word=cctv

**Comment by PeterShaggyNoble** [comment]
Would `camcorder` suit your needs?

![](https://materialdesignicons.com/icon/camcorder)

**Comment by Templarian** [comment]
CCTV would be useful for those using Home Assistant probably.

**Comment by GreenTurtwig** [comment]
Many different styles of camera means it's going to have to be almost universal.  
I'm personally leaning towards having a "dome" shaped camera and "regular" CCTV camera styled icons.

**Comment by rtvb** [comment]
I need it for use with home automation software. Intended use is for security cam so wall cam or dome will do for me. Dome is probably prettier. 

Camcorder is for other purposes, not mine.

**Comment by PeterShaggyNoble** [comment]
A few from Icons8 for inspiration: https://icons8.com/web-app/for/androidL/cctv

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/23918726/f93e2bb0-08eb-11e7-984d-ba4865f2d65c.png)

[cctv.zip](https://github.com/Templarian/MaterialDesign/files/842465/cctv.zip)

**Comment by Templarian** [comment]
[![cctv](https://materialdesignicons.com/icon/cctv)](https://materialdesignicons.com/icon/cctv)

Slight delay in getting this added. 😸
