### ISSUE TITLE
Mail Icons: Open Envelope, and envelope with REPLY and FORWARD arrows

### ISSUE THREAD

**Issue by wwahmed** [Templarian/MaterialDesign#192]
I noticed hat we have a couple of icons based on 'envelopes' (found by searing for tags: mail). 

Submitting this as a request to create companion icons for these, one with open envelope (indicating READ email), and envelope with Forward or Replied arrows (Similar to how we see in Outlook)..

Thanks

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/email-open
http://materialdesignicons.com/icon/reply
http://materialdesignicons.com/icon/reply-all
http://materialdesignicons.com/icon/forward
