### ISSUE TITLE
Request: Waves

### ISSUE THREAD

**Issue by rtvb** [Templarian/MaterialDesign#1920]
Waves icon

Example:

![](https://image.flaticon.com/icons/svg/3/3491.svg)

**Comment by CoDEmanX** [comment]
See my related contribution: https://github.com/Templarian/MaterialDesign/issues/873#issuecomment-208050697

**Comment by rtvb** [comment]
If that icon is going to be released this request can be closed.

**Comment by JamesCoyle** [comment]
@CoDEmanX Would probably be worth just posting the SVGs for those icons in separate issues so they actually get added.

**Comment by Templarian** [comment]
[![waves](https://materialdesignicons.com/icon/waves)](https://materialdesignicons.com/icon/waves)
