### ISSUE TITLE
Windsock

### ISSUE THREAD

**Issue by metbril** [Templarian/MaterialDesign#1921]
Example:

![](https://image.flaticon.com/icons/svg/116/116217.svg)

**Comment by rtvb** [comment]
For use with personal weather station and or weather data in home automation setup.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/89366641-4099f180-d6a5-11ea-982f-210026f7a1c9.png)
[windsock.svg.zip](https://github.com/Templarian/MaterialDesign/files/5025864/windsock.svg.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/89367087-33c9cd80-d6a6-11ea-8ce6-044037400edf.png)
[windsock.svg.zip](https://github.com/Templarian/MaterialDesign/files/5025881/windsock.svg.zip)

**Comment by goyney** [comment]
Added the second variant.
