### ISSUE TITLE
Does not work on IE11 browser

### ISSUE THREAD

**Issue by karolisgrinkevicius** [Templarian/MaterialDesign#1922]
None of icons are visible using Microsoft Edge (IE11).
Link: https://materialdesignicons.com/bootstrap
![mdi-bootstrap](https://cloud.githubusercontent.com/assets/9420403/23791147/9eb349fa-058a-11e7-95b0-008df7ecb70d.PNG)

**Comment by PeterShaggyNoble** [comment]
Do you mean Edge or Internet Explorer or both (Note: they are different browsers)?

Everything works fine in both browsers; can you check if you have any plugins installed that might be blocking the fonts from being loaded? Opening your dev console will allow you to see if they are being downloaded from the server.

**Comment by karolisgrinkevicius** [comment]
Actually both of them. Anyway you were right. Something is wrong on my specific machine since it works well on VM. Unfortunately Edge does not throw any error about not rendered webfont.

**Comment by PeterShaggyNoble** [comment]
@karolisgrinkevicius, whats was the problem? In case it ever comes up here again.

**Comment by karolisgrinkevicius** [comment]
@PeterShaggyNoble didn't figure yet. Once I figure it out I'll let you know in this threat.

**Comment by Templarian** [comment]
@karolisgrinkevicius Your security policies on external requests may be set too high. It may be blocking the CDN request of external assets on `https://`.

These security settings are shared between IE/Edge (I believe?). I'll be updating those docs for the new site with a codepen like the Bootstrap 4 docs.

**Comment by karolisgrinkevicius** [comment]
No it's not to be honest. But something is set mysterious on environment. Don't make any updates until I figure what is wrong on my bloody windows space.

**Comment by PeterShaggyNoble** [comment]
Have a look at [this FontAwesome issue](https://github.com/FortAwesome/Font-Awesome/issues/8472) and the issues it links to, it might be of some help to you.

**Comment by karolisgrinkevicius** [comment]
Since I can reproduce this issue only in my current job's work space it's not a huge problem. But the interesting part is that I don't get any errors in IE11.
