### ISSUE TITLE
octagram is decagram

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#1923]
I don't know how this is handled here, but aren't the octagram-icons ([alert](https://materialdesignicons.com/icon/alert-octagram), [plain](https://materialdesignicons.com/icon/octagram), [outline](https://materialdesignicons.com/icon/octagram-outline) )actually decagrams? I'm just wondering about the naming or the geometry correctness. If this is intended for some reasons please ignore this post.

**Comment by Templarian** [comment]
Counting is hard... 😟... not sure how we managed this one. Apparently I shouldn't be making icons late at night. We probably need to fix this, but it's going to cause some breakage.

I'm kind of surprised I slipped up naming this, I changed the style while designing this and liked the look of the 10 points over 8 and never changed the name.

**Comment by JamesCoyle** [comment]
Needed a bit of a chuckle. :P

**Comment by PeterShaggyNoble** [comment]
I had to count to check!

**Comment by Templarian** [comment]
This has been fixed. There are now octa/deca icons.
