### ISSUE TITLE
Any ideas for Novell and GroupWise?

### ISSUE THREAD

**Issue by amfp** [Templarian/MaterialDesign#1924]
Any ideas for Novell and GroupWise?

1.- GroupWise
![image](http://www.onlight.com/wp-content/uploads/GroupWise_Logo.jpg)
![image](http://img10.deviantart.net/222b/i/2003/42/3/d/novell_groupwise_icons.jpg)

2.- Novell
![image](https://cloud.githubusercontent.com/assets/10002982/23812488/a844d78e-05d2-11e7-81c5-294dca00a879.png)
![image](https://www.file-extensions.org/imgs/app-icon/128/2176/novell-netware-icon.png)

**Comment by JapanYoshi** [comment]
What are they and what do they do?

**Comment by amfp** [comment]
Novell: https://es.wikipedia.org/wiki/Novell
GroupWise:  https://en.wikipedia.org/wiki/GroupWise

**Comment by JapanYoshi** [comment]
I think this is one of those “way too specific brand icons” issues. Until I can get some kind of confirmation that there's a lot of demand for these services, I suggest closing this issue.

**Comment by PeterShaggyNoble** [comment]
I'd agree that they're beyond the scope of the project. Brand icons are generally limited to the more popular social networks.
