### ISSUE TITLE
Medal icon

### ISSUE THREAD

**Issue by amfp** [Templarian/MaterialDesign#1925]
There is this icon?

Example:
![image](https://maxcdn.icons8.com/windows8/PNG/512/Military/medal-512.png)

![image](https://cloud.githubusercontent.com/assets/10002982/23813361/72460a5a-05d6-11e7-90b1-8c78556e013c.png)
![image](https://cloud.githubusercontent.com/assets/10002982/23813374/81281a4a-05d6-11e7-81ea-67642fa55761.png)

**Comment by PeterShaggyNoble** [comment]
Would either of these do you?

![](https://materialdesignicons.com/icon/seal) ![](https://materialdesignicons.com/icon/trophy-award)

**Comment by amfp** [comment]
perfect ! Thank you!
