### ISSUE TITLE
Guitar Icons Too Complex?

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#1926]
I feel like the current ``guitar-electric`` icon could benefit from a lot of simplification and the addition of an acoustic variant.

Reference:
![](https://maxcdn.icons8.com/Android_L/PNG/512/Music/rock_music-512.png)

The electric variant could be that stereotypical triangular guitar, to represent rock music.

**Comment by Templarian** [comment]
Agreed it would be nice to replace the existing one as it looks out of place.

**Comment by JapanYoshi** [comment]
![materialguitar](https://cloud.githubusercontent.com/assets/8707990/23975203/b9c354dc-0a22-11e7-97fb-b93a94529419.png)![materialguitar2](https://cloud.githubusercontent.com/assets/8707990/23975205/b9c854fa-0a22-11e7-8352-7f04d9e38ec6.png)
![materialguitar 10x](https://cloud.githubusercontent.com/assets/8707990/23975204/b9c79e2a-0a22-11e7-9096-98d85a39d589.png)![materialguitar2 10x](https://cloud.githubusercontent.com/assets/8707990/23975206/b9cce47a-0a22-11e7-838b-27f6f16d9524.png)

**Comment by Templarian** [comment]
Really like these two. SVG? Can add them as I work through some final issues in the `1.9.xx` release.

**Comment by JapanYoshi** [comment]
It would be nice to have a bass guitar icon too, though I don't know how that would work.

[Pictures.zip](https://github.com/Templarian/MaterialDesign/files/846552/Pictures.zip)

**Comment by Templarian** [comment]
[![guitar-acoustic](https://materialdesignicons.com/icon/guitar-acoustic)](https://materialdesignicons.com/icon/guitar-acoustic) [![guitar-electric](https://materialdesignicons.com/icon/guitar-electric)](https://materialdesignicons.com/icon/guitar-electric)

**Comment by MrGrigri** [comment]
@JapanYoshi the only way we could symbolize different guitar types is maybe icons of just the headstocks. If I come up with some good ideas, then I'll just create a new 'issue' to track it.
