### ISSUE TITLE
Stylesheet does not have all of the unfold icons listed

### ISSUE THREAD

**Issue by gytdau** [Templarian/MaterialDesign#1927]
`unfold-less-horizontal`, `unfold-more-horizontal`, `unfold-less-vertical`, and `unfold-more-vertical` aren't in the stylesheet served from the CDN. However, the horizontal versions are mappped to `unfold-less` and `unfold-more`. This is quite peculiar.

**Comment by PeterShaggyNoble** [comment]
These will be added in the next release, including the name changes. Please see https://materialdesignicons.com/history for the full list of icons added since the last release and #1891 for updates on the next release.

**Comment by PeterShaggyNoble** [comment]
These will be added in the next release, including the name changes. Please see https://materialdesignicons.com/history for the full list of icons added since the last release and #1891 for updates on the next release.
