### ISSUE TITLE
Arrow icon with stairs and elevator

### ISSUE THREAD

**Issue by gercobrandwijk** [Templarian/MaterialDesign#1928]
Good afternoon,

I would like to have some more icons with stairs and elevators, so I can use them for giving directions in a building.

I was thinking of the following combinations:
- [arrow-top-right](https://materialdesignicons.com/icon/arrow-top-right) combined with [stairs](https://materialdesignicons.com/icon/stairs)
- [arrow-top-right](https://materialdesignicons.com/icon/arrow-top-right) combined with [stairs](https://materialdesignicons.com/icon/stairs) but horizontally flipped (or: horizontally flipped [stairs](https://materialdesignicons.com/icon/stairs) with [arrow-top-left](https://materialdesignicons.com/icon/arrow-top-left))
- [arrow-bottom-left](https://materialdesignicons.com/icon/arrow-bottom-left) combined with [stairs](https://materialdesignicons.com/icon/stairs)
- [arrow-bottom-left](https://materialdesignicons.com/icon/arrow-bottom-left) combined with [stairs](https://materialdesignicons.com/icon/stairs) horizontally flipped (or: horizontally flipped [stairs](https://materialdesignicons.com/icon/stairs) with [arrow-bottom-right](https://materialdesignicons.com/icon/arrow-bottom-right))
- [arrow-up](https://materialdesignicons.com/icon/arrow-up) combined with [elevator](https://materialdesignicons.com/icon/elevator) (instead of 1 arrow up, 1 arrow down, I would like 2 up arrows, or 1 up arrow in the middle)
- [arrow-down](https://materialdesignicons.com/icon/arrow-down) combined with [elevator](https://materialdesignicons.com/icon/elevator) (instead of 1 arrow up, 1 arrow down, I would like 2 down arrows, or 1 down arrow in the middle)

What do you think of this? 

Or is this already possible with the SVG overlay? Perhaps for the stairs (but than I need to decrease the size of the arrows to get a good fit), but for the elevator will be difficult, because the elevator includes already the arrows...

Thanks in advance!

**Comment by PeterShaggyNoble** [comment]
Reopening this as I believe some these may be useful to have.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/70681239-56632e00-1c60-11ea-8bd0-f72a78d865f8.png) ![image](https://user-images.githubusercontent.com/338885/70681248-5f53ff80-1c60-11ea-8648-0b546470a0f6.png)

**Comment by gercobrandwijk** [comment]
Looking good!

**Comment by Templarian** [comment]
Those are just copy and pastes from https://www.aiga.org/symbol-signs for reference.

**Comment by Templarian** [comment]
Added. `stairs-up` and `stairs-down`.

**Comment by Templarian** [comment]
Added the elevator ones also. Wasn't a fan of this variant for elevator that as made while thinking of different designs. Still not a huge fan of our elevator icons.

![image](https://user-images.githubusercontent.com/338885/70774482-08bdf280-1d40-11ea-983a-d3f9e2b87214.png)

**Comment by goyney** [comment]
@Templarian Is there something left to do on this issue?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/73586244-718c3600-4478-11ea-87aa-239995daa6d6.png)
[elevator-passenger.svg.zip](https://github.com/Templarian/MaterialDesign/files/4142107/elevator-passenger.svg.zip)

**Comment by goyney** [comment]
[![elevator-passenger](https://materialdesignicons.com/icon/elevator-passenger)](https://materialdesignicons.com/icon/elevator-passenger)
