### ISSUE TITLE
Request: Project Icon

### ISSUE THREAD

**Issue by geniusbabak** [Templarian/MaterialDesign#1929]
It is sometime that I'm looking for a good icon resembling a "Project".
Would you please give it a try?

**Comment by CoDEmanX** [comment]
How about chart-timeline or chart-gantt?calendar-check, clipboard-check, playlist-check or related might also work for you.

**Comment by Chan4077** [comment]
See #1605

**Comment by geniusbabak** [comment]
@CoDEmanX 
I'm using all those already, it is a project management tool! ;)
