### ISSUE TITLE
Door icon

### ISSUE THREAD

**Issue by JensRoggeband** [Templarian/MaterialDesign#193]
An awesome icon would be a door, something like

![ic_locations](https://cloud.githubusercontent.com/assets/8440839/6452682/a91d7594-c137-11e4-92ff-4c781ac47209.png)

**Comment by CoDEmanX** [comment]
Maybe a close-up of a door handle?
Otherwise it wouldn't be very recognizable (perspective is discouraged in MD icon guidelines)

**Comment by PeterShaggyNoble** [comment]
Closing this in favour of the more recent and more active #1822.
