### ISSUE TITLE
Contribution: Gerdau Icon

### ISSUE THREAD

**Issue by Dssdiego** [Templarian/MaterialDesign#1930]
I want to contribute to the community with this Icon:

RESULT PNG:
![gerdau_mdi](https://cloud.githubusercontent.com/assets/7061445/23828651/615a2d52-06b7-11e7-80b8-585c029d65c4.png)

ZIP FILE (.ai + .svg):
https://trello-attachments.s3.amazonaws.com/58c4bcbd2fb515895f0c1107/58c4bcd3ecdce56ff84c26b5/48bface6bc0df7ce4cceeefd955375b8/gerdau.zip

**Comment by Dssdiego** [comment]
Put the .zip file with a link because GitHub blocked to put .zip file here

**Comment by JapanYoshi** [comment]
I don't think there's a lot, or any, demand for a Material icon for a Brazilian steel company. This is a job for SVG drawables, not this repo.

**Comment by Dssdiego** [comment]
It is a worldwide company.

See the locations: https://www.gerdau.com/en/who-we-are/global-presence
