### ISSUE TITLE
map-marker-outline

### ISSUE THREAD

**Issue by erioernesto02** [Templarian/MaterialDesign#1931]
Please, make mark-map outline.
thank.

**Comment by RobertoGraham** [comment]
![image](https://cloud.githubusercontent.com/assets/14958777/23951011/d04e3b98-0984-11e7-87c0-f94c41e6f73f.png)

[map-marker-outline.zip](https://github.com/Templarian/MaterialDesign/files/844643/map-marker-outline.zip)

**Comment by Templarian** [comment]
[![map-marker-outline](https://materialdesignicons.com/icon/map-marker-outline)](https://materialdesignicons.com/icon/map-marker-outline)

**Comment by Theo-Schusterjunge** [comment]
Hope I'm not just doing something wrong … but could it be that the font file (materialdesignicons-webfont.ttf) doesn't contain the map-marker-outline icon?
I re-downloaded the package today and scrolled the font through quite carefully but couldn't find it :/
Any help?

**Comment by JamesCoyle** [comment]
@Theo-Schusterjunge It will be available in the next release. We are working on making this clearer for the new website and should hopefully have more frequent releases in the future too. I believe @Templarian is currently finalizing the next version ready for release soon.

**Comment by Theo-Schusterjunge** [comment]
Ah great! Thanks :)
