### ISSUE TITLE
baseball icon please

### ISSUE THREAD

**Issue by turboc1208** [Templarian/MaterialDesign#1932]
need a baseball please

**Comment by Templarian** [comment]
As we're splitting up some of the icon requests I'm going to leave this open to track `baseball` and edit other sports related icon requests mentioning baseball.

**Comment by PeterShaggyNoble** [comment]
These were added over the weekend with #2839. Closing here.

[![baseball](https://user-images.githubusercontent.com/15157491/36670854-8678c694-1af1-11e8-989d-79ae8abf1531.png)](https://materialdesignicons.com/icon/baseball) [![baseball-bat](https://user-images.githubusercontent.com/15157491/36670885-a834370a-1af1-11e8-974b-5ca8af52188b.png)](https://materialdesignicons.com/icon/baseball-bat)
