### ISSUE TITLE
Add RobertoGraham as contributor

### ISSUE THREAD

**Issue by RobertoGraham** [Templarian/MaterialDesign#1934]
[Two here, Atom and Orbit](https://github.com/Templarian/MaterialDesign/issues/1527)
[Rx](https://github.com/Templarian/MaterialDesign/issues/1627)
[Roomba](https://github.com/Templarian/MaterialDesign/issues/1677)
[Bomb-off](https://github.com/Templarian/MaterialDesign/issues/1680)

**Comment by Templarian** [comment]
Awesome! Just need some information for your profile page ([example](https://materialdesignicons.com/contributor/Austin-Andrews)).

100x100 profile image.
twitter
github (will assume this one)
Short description

**Comment by RobertoGraham** [comment]
![me](https://cloud.githubusercontent.com/assets/14958777/23909197/042920ac-08ce-11e7-907b-34d99870ea04.png)

https://twitter.com/RobertoGrrraham

Desc: 20. Europe. React, PHP, Java. Read more.

**Comment by Templarian** [comment]
@RobertoGraham https://materialdesignicons.com/contributor/Roberto-Graham

Welcome, hopefully stick around and help us close out more icons. The 5 icons are assigned over.

Eventually I'll be opening up some feature on the site for contributors, until then everything is done in the issues to be as public as possible with changes.

Thanks!

**Comment by PeterShaggyNoble** [comment]
The [history page](https://materialdesignicons.com/history) is still showing @Templarian as contributor for @RobertoGraham's icons.

**Comment by Templarian** [comment]
@PeterShaggyNoble Minor bug in the history page (right now it requires DB edits to fix), will have to fix it in the new site. Modified it with my account so the top one is actually correct for a db point. The other 3 need to be manually edited.

**Comment by JapanYoshi** [comment]
I just assumed that until you're added officially as a contributor Templarian "takes credit for" the icons lol

**Comment by Templarian** [comment]
@JapanYoshi Created a new account called "Contributors" that will take credit from now on. Before it was mostly lazyness I think only around 20 or less are from others. Although @CoDEmanX will probably catch up to me eventually as I shift my focus on site features rather than new icons after 2k.

Now to think of a `100x100` avatar for this "Contributor" user.

**Comment by JapanYoshi** [comment]
Why not just ``account-multiple``? https://materialdesignicons.com/icon/account-multiple
