### ISSUE TITLE
Icon for unseen content

### ISSUE THREAD

**Issue by patelatharva** [Templarian/MaterialDesign#1936]
There should be an icon for unseen content. Similar to this one:
https://cdn4.iconfinder.com/data/icons/basic-1/64/basic_eye_closed-512.png

**Comment by CoDEmanX** [comment]
There are already eye-off and eye-outline-off. I think this can be closed.

**Comment by PeterShaggyNoble** [comment]
![](https://materialdesignicons.com/icon/eye-off) ![](https://materialdesignicons.com/icon/eye-off-outline)
