### ISSUE TITLE
Update Icon: chart-pie

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1937]
The `chart-pie` icon could do with being updated to match Google's: https://material.io/icons/#ic_pie_chart

There's also an `-outline` variation: https://material.io/icons/#ic_pie_chart_outlined

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53061969-3eca7700-348d-11e9-8410-ba6ce0dbb89f.png)
Current is in outline, proposed new is white.

[chart-pie.svg.zip](https://github.com/Templarian/MaterialDesign/files/2882763/chart-pie.svg.zip)

**Comment by Templarian** [comment]
Updated / Assigned. 😃
