### ISSUE TITLE
BBFC Ratings

### ISSUE THREAD

**Issue by RobertoGraham** [Templarian/MaterialDesign#1939]
Maybe filled and outline variants?

![image](https://cloud.githubusercontent.com/assets/14958777/24006043/8dcd31b4-0a62-11e7-8ebe-b1f8847f9f65.png)

**Comment by PeterShaggyNoble** [comment]
Much as I'd like to see these added too, I think they're too specific; if they were added then we'd open ourselves up to requests for the equivalent icons from other countries (I'd be the first in, looking for the Irish ones! 😆).

Also, I'm not sure these particular ones would work as single colour icons, the colour is important in communicating the rating at a glance.

**Comment by RobertoGraham** [comment]
Well-reasoned.

**Comment by Templarian** [comment]
Going to agree, these are a tad too specific. Useful, but too generic at the small size (loses the meaning too much). 😄

**Comment by PeterShaggyNoble** [comment]
You could "roll your own" by layering text over the existing shape icons, which comes with the added benefit of being able to make them multi-coloured.
