### ISSUE TITLE
Double decker and articulated buses

### ISSUE THREAD

**Issue by Pika3323** [Templarian/MaterialDesign#1940]
Similar to the existing bus icon, but for double decker and articulated buses.

**Comment by GreenTurtwig** [comment]
A front view won't fit very well in the space constraints.
Regular bus, double decker and articulated:

Regular (side on view)
![](https://puu.sh/vEAVT.png)
![](https://puu.sh/vEAXl.png)

Double decker
![](https://puu.sh/vEAZN.png)
![](https://puu.sh/vEB0E.png)
I assume you know what I based this on. :cat2:
Yes, I know the cabin is on the right, not the left. But to keep all the vehicles consistent it's on the left instead.

Articulated
![](https://puu.sh/vEBcb.png)
![](https://puu.sh/vEBdr.png)
Articulated End
![](https://puu.sh/vEBDL.png)
![](https://puu.sh/vEBFE.png)
Not happy with this one at all, but having such a long bus in one icon like this isn't really possible without separating it. Added a back end to it in case anyone wanted that. :man_shrugging:

**Comment by Templarian** [comment]
Maybe like a jagged receipt type end. ^^^^ ?

Not sure the current design works for that style of bus.

**Comment by GreenTurtwig** [comment]
Yeah, that's the main reason I didn't like it. I'll give it a try tommorow. :cat2:

**Comment by GreenTurtwig** [comment]
![puush-linux 2017-05-04 at 08 53 18](https://cloud.githubusercontent.com/assets/15905797/25694608/48c2ad36-30a7-11e7-9d29-23dd2169f59b.png)
![puush-linux 2017-05-04 at 08 53 54](https://cloud.githubusercontent.com/assets/15905797/25694619/5219b0f0-30a7-11e7-896d-2192390a43c3.png)
[bus-articulated.zip](https://github.com/Templarian/MaterialDesign/files/975477/bus-articulated.zip)
It's certainly better.

**Comment by JamesCoyle** [comment]
The rear would only have one wheel just to the left of the halfway mark on that section.

**Comment by GreenTurtwig** [comment]
Good call, looks way better.
![](https://puu.sh/vFB1L.png)
![](https://puu.sh/vFB4L.png)
[bus-articulated-end.zip](https://github.com/Templarian/MaterialDesign/files/977308/bus-articulated-end.zip)

**Comment by GreenTurtwig** [comment]
[buses.zip](https://github.com/Templarian/MaterialDesign/files/977314/buses.zip)

**Comment by Templarian** [comment]
Yea, these look really nice! Will get them in shortly.

**Comment by Templarian** [comment]
[![bus-side](https://materialdesignicons.com/icon/bus-side)](https://materialdesignicons.com/icon/bus-side) [![bus-articulated-front](https://materialdesignicons.com/icon/bus-articulated-front)](https://materialdesignicons.com/icon/bus-articulated-front) [![bus-articulated-end](https://materialdesignicons.com/icon/bus-articulated-end)](https://materialdesignicons.com/icon/bus-articulated-end) [![bus-double-decker](https://materialdesignicons.com/icon/bus-double-decker)](https://materialdesignicons.com/icon/bus-double-decker)
