### ISSUE TITLE
factory-smoke / factory-on

### ISSUE THREAD

**Issue by metbril** [Templarian/MaterialDesign#1941]
I would like to suggest an alternative icon for the current factory icon. This would be the current icon, with smoke coming from the chimney. I intend to use this in Home Assistant for a pollution or air quality indicator.

Suggested filename: `factory-smoke` or `factory-on`.

## Current icon:
https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/factory.svg

## Example:

![](https://image.flaticon.com/icons/svg/360/360350.svg)

**Comment by PeterShaggyNoble** [comment]
Possible duplicate of #1513?

**Comment by metbril** [comment]
Not sure if it’s a duplicate but they are family. My use case is pollution.

**Comment by CoDEmanX** [comment]
In that case, it should depict a chimney / cooling tower + cloud I guess?

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by PeterShaggyNoble** [comment]
The icon requested in #1513 has since been added as `smog`.
