### ISSUE TITLE
3 New Icon Requests: Dog, Reservation and Dog Rescue Centre

### ISSUE THREAD

**Issue by ldthompson** [Templarian/MaterialDesign#1942]
Hello,

I understand that the icons that I am requesting are niche but it would greatly help me out. These will be used on a website launching soon, so please help! 

Dog - it would be great if a dog icon could be made, alternatively something that represents a dog is just as useful e.g a bone or dog collar 

Placing Reservations - I know there are a lot of icons for payment, such as the carts and bank cards etc, however they don't really suit my needs. I am looking something that would suit placing reservations on dogs - I know this is a hard one and very niche, if this can't be done I will probably use the 'tag-outline' icon instead.

Dog rescue centre - this is something similar to the 'home' icon but again dog related. 

Thanks

**Comment by MrGrigri** [comment]
We already have a bone icon. As for the other, those might be a little too specific and complicated.
![bone](https://materialdesignicons.com/icon/bone).

**Comment by Ch-Lo** [comment]
There are already other animal icons, so a dog would be nice.
For reservation [tag](https://materialdesignicons.com/icon/tag) may do the job.
Maybe [security-home](https://materialdesignicons.com/icon/security-home) would do as "rescue center". If your page is about dogs the context should be clear and no dog related icon is needed, imo.

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @ldthompson, if the above suggestions don't suit your needs, please provide some examples of what you *are* looking for and we'll revisit this issue.

Dog itself is a duplicate of #736.
