### ISSUE TITLE
New Icon request

### ISSUE THREAD

**Issue by lakshit1001** [Templarian/MaterialDesign#1943]
Hey can we have a new icon like this 
to show science or the word "everything" or "overall"
https://i0.wp.com/kitabee.in/wp-content/uploads/2016/02/feature-icon-2.png?resize=100%2C100

**Comment by wopian** [comment]
https://github.com/Templarian/MaterialDesign/issues/1527#issuecomment-286315668 would be ideal for this imo 👍

**Comment by PeterShaggyNoble** [comment]
That's already available:

![](https://materialdesignicons.com/icon/atom)
