### ISSUE TITLE
Icon Request: Eventbrite

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1944]
This may fall outside the scope of brand icons that can be added as it's not a social network and I don't know if the same is true in other countries (if not, this request can probably be closed as being too regional) but here in Ireland, a lot of companies are starting to use [Eventbrite](https://www.eventbrite.com/) to sell tickets to their events, rather than Ticketmaster. One of the generic ticket icons would, of course, do the job when linking to an Eventbrite page but an icon of their "E" would help inform site visitors exactly where the link is taking them. I haven't been able to find an SVG of their logo yet but their press pack, with a few PNGs in it, can be downloaded [here](https://www.eventbrite.com/press/).

**Comment by Templarian** [comment]
I think this could be added. It's not a traditional social media icon, but is used heavily enough that it would be useful to see.

**Comment by MrGrigri** [comment]
Here is my attempt.

![eventbrite](https://cloud.githubusercontent.com/assets/4528551/24867273/ef8b7cb0-1dc9-11e7-86ef-ab90d829cd9a.png)

[eventbrite.zip](https://github.com/Templarian/MaterialDesign/files/910423/eventbrite.zip)

**Comment by Templarian** [comment]
[![eventbrite](https://materialdesignicons.com/icon/eventbrite)](https://materialdesignicons.com/icon/eventbrite)

**Comment by PeterShaggyNoble** [comment]
Thanks for that @MrGrigri and thanks for adding it @Templarian.
