### ISSUE TITLE
simple usage

### ISSUE THREAD

**Issue by 1010451** [Templarian/MaterialDesign#1945]
Hi.
How can i use materialdesignicons-webfont like i'm using MaterialIcons-Regular?
I want to add minimum code as possible.
Is really necessary to have css file "materialdesignicons.css" included on my project?

Regads,
André

**Comment by PeterShaggyNoble** [comment]
You could include the font in your stylesheet using `@font-face`, add the rules for the `.mdi::before` pseudoclass and then extract only the classes for the icons you need from the MDI CSS file:

    @font-face{
        font-family "Material Design Icons";
        src url("/path/to/materialdesignicons-webfont.eot?v=1.8.36");
        src url("/path/to/materialdesignicons-webfont.eot?#iefix&v=1.8.36") format("embedded-opentype"),url("/path/to/materialdesignicons-webfont.woff2?v=1.8.36") format("woff2"),url("/path/to/materialdesignicons-webfont.woff?v=1.8.36") format("woff"),url("/path/to/materialdesignicons-webfont.ttf?v=1.8.36") format("truetype"),url("/path/to/materialdesignicons-webfont.svg?v=1.8.36#materialdesigniconsregular") format("svg");
        font-weight:normal;
        font-style:normal;
    }
    .mdi::before{
        display:inline-block;
        font:normal normal normal 24px/1 "Material Design Icons";
        font-size:inherit;
        text-rendering:auto;
        line-height:inherit;
        -webkit-font-smoothing:antialiased;
        -moz-osx-font-smoothing:grayscale;
        transform:translate(0, 0);
    }
    /* Add the icons you want to use below; for example... */
    .mdi-access-point::before{content:"\f002";}

Depending on your usage, you might also need to add the rules for sizes, colours, flipping, rotating and spinning (coming in the next release), which can be found at the end of the stylesheet.

Alternatively, you could add a custom attribute to your HTML elements, using the entities for the values and add the `content` property to the `.mdi::before` pseudoclass. That way, you wouldn't need to worry about adding rules for any additional icons you might wish to use in the future.

    @font-face{
        font-family "Material Design Icons";
        src url("/path/to/materialdesignicons-webfont.eot?v=1.8.36");
        src url("/path/to/materialdesignicons-webfont.eot?#iefix&v=1.8.36") format("embedded-opentype"),url("/path/to/materialdesignicons-webfont.woff2?v=1.8.36") format("woff2"),url("/path/to/materialdesignicons-webfont.woff?v=1.8.36") format("woff"),url("/path/to/materialdesignicons-webfont.ttf?v=1.8.36") format("truetype"),url("/path/to/materialdesignicons-webfont.svg?v=1.8.36#materialdesigniconsregular") format("svg");
        font-weight:normal;
        font-style:normal;
    }
    .mdi::before{
        content:attr(data-icon);
        display:inline-block;
        font:normal normal normal 24px/1 "Material Design Icons";
        font-size:inherit;
        text-rendering:auto;
        line-height:inherit;
        -webkit-font-smoothing:antialiased;
        -moz-osx-font-smoothing:grayscale;
        transform:translate(0, 0);
    }
    
    <span class="mdi" data-icon="&#xf002;">access-point</span>

**Comment by Templarian** [comment]
Yea, 99% of the css file is codepoint data with names. Using the codepoints with `content: "\F002";` is fine as long as there is a font-family assigned.

https://cdn.materialdesignicons.com/1.8.36/ has the codepoints with a single click to copy to clipboard.
