### ISSUE TITLE
Password icon.

### ISSUE THREAD

**Issue by blueglue** [Templarian/MaterialDesign#1946]
[password.pdf](https://github.com/Templarian/MaterialDesign/files/855222/password.pdf)

**Comment by MrGrigri** [comment]
That submission is too elongated. Would any of these not work?

![lock](https://materialdesignicons.com/icon/lock) ![lock-outline](https://materialdesignicons.com/icon/lock-outline) ![lock-open](https://materialdesignicons.com/icon/lock-open) ![lock-open-outline](https://materialdesignicons.com/icon/lock-open-outline)

**Comment by blueglue** [comment]
Yes, thank you, but I need to indicate a password type input, not exactly an unlock or login.

BlueMail<http://www.bluemail.me/r?b=9226> -pal küldve
2017. márc. 20.-n, 15:59-kor, Michael Richins <notifications@github.com<mailto:notifications@github.com>> ezt írta:

That submission is too elongated. Would any of these not work?

[lock]<https://camo.githubusercontent.com/ca7abb9eb0d501337b959fd1f4a4ef36911f48ae/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f6c6f636b> [lock-outline] <https://camo.githubusercontent.com/b01c1e668be576f58b6d4a3553ee5ea0d3aa97c5/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f6c6f636b2d6f75746c696e65>  [lock-open] <https://camo.githubusercontent.com/05956da8b489aa7a0abb9cf045549cb5ac762545/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f6c6f636b2d6f70656e>  [lock-open-outline] <https://camo.githubusercontent.com/a1aa0f57e719b347085c2bc39aaaa6d2e1d6bd59/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f6c6f636b2d6f70656e2d6f75746c696e65>

**Comment by MrGrigri** [comment]
What about something like this?

![image](https://cloud.githubusercontent.com/assets/4528551/24107912/b3ed12b4-0d51-11e7-88c9-26e81f0b5e17.png)

![image](https://cloud.githubusercontent.com/assets/4528551/24107889/9e8193fa-0d51-11e7-8bd1-1434c6c8770a.png)

**Comment by blueglue** [comment]
Yes, this is good, thanks. Will this be official? Can I found it in the collection?

BlueMail<http://www.bluemail.me/r?b=9226> -pal küldve
2017. márc. 20.-n, 16:44-kor, Michael Richins <notifications@github.com<mailto:notifications@github.com>> ezt írta:

What about something like this?

[image]<https://cloud.githubusercontent.com/assets/4528551/24107912/b3ed12b4-0d51-11e7-88c9-26e81f0b5e17.png>

[image]<https://cloud.githubusercontent.com/assets/4528551/24107889/9e8193fa-0d51-11e7-8bd1-1434c6c8770a.png>

**Comment by MrGrigri** [comment]
@blueglue, there is an approval process, I'll tag this thread and include the SVG. For the meantime, feel free to grab the SVG and use it in your project. 

[textbox-password.zip](https://github.com/Templarian/MaterialDesign/files/855944/textbox-password.zip)

**Comment by Templarian** [comment]
[![textbox-password](https://materialdesignicons.com/icon/textbox-password)](https://materialdesignicons.com/icon/textbox-password)
