### ISSUE TITLE
Request: donut-small donut-large

### ISSUE THREAD

**Issue by frlinw** [Templarian/MaterialDesign#1947]
https://material.io/icons/#ic_donut_large

**Comment by PeterShaggyNoble** [comment]
Could you open a separate issue for the suggested renamings, please?

**Comment by MrGrigri** [comment]
@frlinw, do you not want this added?

**Comment by frlinw** [comment]
It seems `chart-donut` has been added (apr 6th 2017). I don't know why it's different from the stock but it's not worth it to have a duplicate
