### ISSUE TITLE
Countries and Continents

### ISSUE THREAD

**Issue by naco-siren** [Templarian/MaterialDesign#1951]

**Comment by PeterShaggyNoble** [comment]
Would the `earth` or `earth-box` icons suit your needs? If not, please provide more details on what you're looking for.

![](https://materialdesignicons.com/icon/earth) ![](https://materialdesignicons.com/icon/earth-box)

**Comment by naco-siren** [comment]
Icons like these:
https://thenounproject.com/localdomain/collection/continents/?oq=continents&cidx=4
https://thenounproject.com/marvdrock/collection/countries-solid/?oq=countries&cidx=10

**Comment by PeterShaggyNoble** [comment]
They're far too detailed to be represented in a Material style at a small size, unfortunately - compare the level of detail in them to the 2 icons I posted above.

**Comment by JapanYoshi** [comment]
Hold on, maybe I can caricaturise the continents in the Material style, like how the ``globe`` caricaturises North and South America.

**Comment by PeterShaggyNoble** [comment]
@JapanYoshi, did you make any progress on this? If not, we should probably close it again.
