### ISSUE TITLE
Request Icon: All Icon Media Player related to IOS 

### ISSUE THREAD

**Issue by kristoff2016** [Templarian/MaterialDesign#1952]

**Comment by PeterShaggyNoble** [comment]
There are already plenty of media player control icons available. Which ones, specifically, are you looking to have added?

**Comment by kristoff2016** [comment]
Here in link for example
https://scontent-kut2-1.cdninstagram.com/t51.2885-15/e35/16788901_412862662396113_229077372131868672_n.jpg

Thank you for help

**Comment by PeterShaggyNoble** [comment]
They're all there:

![](https://materialdesignicons.com/icon/repeat) ![](https://materialdesignicons.com/icon/shuffle) ![](https://materialdesignicons.com/icon/skip-next) ![](https://materialdesignicons.com/icon/skip-previous)

**Comment by kristoff2016** [comment]
Thank you so much
