### ISSUE TITLE
"More" in circle

### ISSUE THREAD

**Issue by Shakenbeer** [Templarian/MaterialDesign#1953]
Horizontal dots in circle. Here is an example I've created for myself. I've added archive with svg as well. 
[ic_more_20px.zip](https://github.com/Templarian/MaterialDesign/files/857667/ic_more_20px.zip)

![try1](https://cloud.githubusercontent.com/assets/5087719/24141498/45eca226-0e2c-11e7-9800-df1153a2ec13.png)

**Comment by Templarian** [comment]
[![dots-vertical-circle](https://materialdesignicons.com/icon/dots-vertical-circle)](https://materialdesignicons.com/icon/dots-vertical-circle) [![dots-horizontal-circle](https://materialdesignicons.com/icon/dots-horizontal-circle)](https://materialdesignicons.com/icon/dots-horizontal-circle)

To keep the proportions correct the inner circles are `3dp`.
