### ISSUE TITLE
Rename Network Icons

### ISSUE THREAD

**Issue by frlinw** [Templarian/MaterialDesign#1954]
- [x] `network-upload` > `upload-network`
- [x] `network-download` > `download-network`
- [x] `network-question` > `help-network`

**Comment by PeterShaggyNoble** [comment]
Updated to include `close-network`.

**Comment by Templarian** [comment]
I'm wondering if we should treat network as a modifier (so `*-network`) rather than a root type. I view it more like a modify to an existing root icon.

**Comment by PeterShaggyNoble** [comment]
Should `network-download`, `network-question` and `network-upload` be renamed, so?

It's tricky when an icon name has to be made up solely of modifiers.

Maybe some more guidelines are needed as to the order of modifiers in icon names to keep naming consistent, especially if the new site is going to allow contributors to add new icons directly. If, for example, a plus was added to the shield of the `security-network` icon, should that be named `security-network-plus` or `security-plus-network`?

**Comment by frlinw** [comment]
`plus` is a root and a modifier. You can find it as `plus-outline` and `calendar-plus`.
It's the same case for network : `network-download`, `security-network`, `network-plus`
And it make sense for the user.

With network as a modifier, icon name should be `plus-box-network`...

**Comment by Templarian** [comment]
Since we follow the naming standard everywhere else I think we should enforce it here also even if `plus-box-network` seems longer.

@PeterShaggyNoble It would be `security-plus-network` I believe.

**Comment by Templarian** [comment]
Renamed for the `1.9.28` release.
