### ISSUE TITLE
A/B Testing

### ISSUE THREAD

**Issue by Sjennon** [Templarian/MaterialDesign#1955]
Not sure if I am blind or it doesn't exist, but it would be great if there would be a material A/B testing icon, or something to represent this!

Just something simple like this without the colors?
![image](https://cloud.githubusercontent.com/assets/6576878/24151968/78dae6f2-0e4a-11e7-94b8-3e2f70a84962.png)

Thanks for your great work!

**Comment by Sjennon** [comment]
Or like, this one:

![image](https://cloud.githubusercontent.com/assets/6576878/24203270/8dfb097e-0f15-11e7-88d1-3887f134dfc7.png)

But without the fan and change the C into a B.

**Comment by MrGrigri** [comment]
Would any of these work?

![image](https://cloud.githubusercontent.com/assets/4528551/24204304/a30ec694-0edd-11e7-91ed-3bdc94b0fd99.png) ![image](https://cloud.githubusercontent.com/assets/4528551/24204314/ad896160-0edd-11e7-89d4-9ee4e8c84f66.png)

Or you can go with something a little more abstract; which Material tends to do.

![arrange-bring-forward](https://materialdesignicons.com/icon/arrange-bring-forward)

**Comment by Sjennon** [comment]
I think this one would be perfect
https://cloud.githubusercontent.com/assets/4528551/24204314/ad896160-0edd-11e7-89d4-9ee4e8c84f66.png

**Comment by MrGrigri** [comment]
Or there is this one:

![image](https://cloud.githubusercontent.com/assets/4528551/24204645/be660af0-0ede-11e7-93f3-76da7bec7aef.png)

**Comment by Sjennon** [comment]
Oh I like that one too! I think either will work :D

**Comment by MrGrigri** [comment]
Let the voting begin. 1st (:+1:), 2nd (:smile:), or 3rd (:heart:)?

![image](https://cloud.githubusercontent.com/assets/4528551/24205011/ce2b72e4-0edf-11e7-91f0-c24f2bb9494a.png)

**Comment by mxzinteract** [comment]
❤️

**Comment by PeterShaggyNoble** [comment]
Of those 3, my vote goes to the second but I think something similar to the "A/C" would work better.

`call-split` could be another option, too:

![](https://materialdesignicons.com/icon/call-split)

**Comment by Sjennon** [comment]
I think that could be a temporary option, though I highly prefer an actual A/B one.

**Comment by MrGrigri** [comment]
Based on feedback, we'll go with the first one. Here are the linked files.

![ab-testing](https://cloud.githubusercontent.com/assets/4528551/24308227/ca26b146-108c-11e7-815c-7ad631a3bc50.png)

[ab-testing.zip](https://github.com/Templarian/MaterialDesign/files/868827/ab-testing.zip)

**Comment by CoDEmanX** [comment]
The letters look kind of odd. Not sure about language conflict. In math, you use Latin and Greek symbols even if you're Chinese.

**Comment by goyney** [comment]
This needs to be updated to use the `alpha-*` letters.

**Comment by MrGrigri** [comment]
Updated.

![image](https://user-images.githubusercontent.com/4528551/48987095-fe9b6880-f0d8-11e8-9a62-fbbe419c45c3.png)

---

[ab-testing.zip](https://github.com/Templarian/MaterialDesign/files/2613687/ab-testing.zip)

**Comment by MrGrigri** [comment]
I do not believe that this will be a language conflict as programming is done primarily in English.

**Comment by goyney** [comment]
[![ab-testing](https://materialdesignicons.com/icon/ab-testing)](https://materialdesignicons.com/icon/ab-testing)
