### ISSUE TITLE
Envelope

### ISSUE THREAD

**Issue by djibe** [Templarian/MaterialDesign#1956]

**Comment by MrGrigri** [comment]
Maybe there needs to be an alias, but there are plenty of envelopes. Just search for `mail` and you'll find them all. Here are a couple of examples:

![email](https://materialdesignicons.com/icon/email) ![email-open](https://materialdesignicons.com/icon/email-open) ![email-variant](https://materialdesignicons.com/icon/email-variant)

**Comment by MrGrigri** [comment]
I believe this has been handled.
