### ISSUE TITLE
Contributor Swag - Request Form

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#1957]
Contributors (even the ones of you without GitHub contributor status, 5+ icons) I need you to please fill out the form below.

https://docs.google.com/forms/d/e/1FAIpQLSccTb8bvMvBBB8-eRrWpUAF3A1hVV9SCcwhupd9346FgW0deA/viewform?usp=sf_link

![20170322_131218](https://cloud.githubusercontent.com/assets/338885/24213778/a177d4c8-0f01-11e7-8828-714d5a5d641a.jpg)

For international shipping know this could be delayed as I figure out logistics, but I'll try and get them out promptly after v2.0's release.

Thanks everyone.

**Comment by GreenTurtwig** [comment]
I submitted, let me know if it went through.👍  
  
I really appreciate you sending these out! Just means I'll have to get a frame now, thank you so much. 🐈

**Comment by PeterShaggyNoble** [comment]
Done.

Thanks, @Templarian and thanks for letting me be involved.

**Comment by JamesCoyle** [comment]
How's this going? Any progress on the poster design?

**Comment by Templarian** [comment]
Poster scripts to generate and render the poster are done. I'm just tweaking the icons that will be visible. Choosing to exclude some before the final render. Poster will contain 2040 icons (40 Columns, 51 Rows).

If you matte the poster when framed it's formatted to hide the bottom row assuming an even matte border. It's how I plan to frame it for work and my wall at home.

[View the Debug Export](https://cdn.materialdesignicons.com/poster/poster-draft2.svg) (not the final colors, but layout). The numbers/boxes/color overlays are just debug.

**Comment by JamesCoyle** [comment]
So like so?
![image](https://user-images.githubusercontent.com/10384436/27004951-3f3bd838-4e0b-11e7-9f53-0c6379c44b39.png)


I do have a potential improvement you could make. Create a script to output the icon as a grayscale bitmap and then add all pixel values together and determine what percentage of the bitmap is filled. That determines how dark or light the icon will appear to be in relation to its neighbors and can be used to position the icons on the grid so that from a distance it looks like the MDI logo.

**Comment by JamesCoyle** [comment]
Just working on this idea a little. It would require determining the darkest 272 icons to position in the blue area and then position the rest in the white area (plus or minus a row where needed). 
![image](https://user-images.githubusercontent.com/10384436/27005068-5ff38d2a-4e0e-11e7-90e3-5b7557991e3d.png)

**Comment by Templarian** [comment]
We can definitely do that in a script since I already have the data in imagemagick. Will see after the test print how it looks in person on a `18x24`, could be more noticeable due to the size.

**Comment by Templarian** [comment]
By the way I sent this out to the printers last Friday for the test print. Set the wrong font for the bottom text, but mostly using this to see how good the print quality is.

Below is a PNG export (2040 icons). The print was sent over in all vector. 😄 

![poster](https://user-images.githubusercontent.com/338885/27919390-28f1331c-6237-11e7-859a-4d7309eb546e.png)

**Comment by MrGrigri** [comment]
@Templarian, will both the stickers and poster be released together?

**Comment by Templarian** [comment]
@MrGrigri Yep, for contributors the stickers will arrive in the tube. For just stickers I have those now, could send those out now, just need some free time. 😩

**Comment by Templarian** [comment]
http://i.imgur.com/mEvn52i.jpg This looks better in person with the margins. I actually like it a lot in the dark grey with white background.

**Comment by Templarian** [comment]
http://templarian.com/2017/07/31/material-design-icons-poster/

Guys, I'm sending out the bulk order this weekend. The default for the contributors will be grey'ish blue with white icons.

If you want white, please comment below (no difference, just not ordering many of the whites with off black icons).

**Comment by JamesCoyle** [comment]
I'm not sure which I like best. They both look awesome!

**Comment by MrGrigri** [comment]
I prefer the dark blue-grey with white icons personally, but they both look awesome. Thanks for doing this man.

**Comment by GreenTurtwig** [comment]
Same here, I just can't decide! I'll have to go with the blue-grey too aswell though, if only so it will stand out among other things on the wall.  
And once again, thank you so much. 🐱

**Comment by Templarian** [comment]
I have all the items packaged and ready to ship. Sent out one since I had the phone number, but if you could quickly fill out the phone number, if not I'll ship it without one tomorrow and will just email the tracking codes.

https://docs.google.com/forms/d/e/1FAIpQLSelDD4SMQTi37aNvpD2FSfLep5zM6IcZcsvhNWO0d8agWfrJQ/viewform?usp=sf_link

![20170822_092100](https://user-images.githubusercontent.com/338885/29589182-e31b4f6a-8759-11e7-915f-c17320db1f54.jpg)

Thanks!

**Comment by Templarian** [comment]
I have Michael, James, Rowan. I'll be sending these out tonight when I get home from work. Rest will ship with my number.

Will check the form tonight before updating the Fedex labels.

**Comment by MrGrigri** [comment]
@Templarian, thanks for the swag. I just got back from training and I noticed that the package was open and the 2 cards and four hexagon stickers were missing. The 2 Tetris stickers and poster were still there and not damaged. If you happen to have an extra that would be great. If not, no problems.

**Comment by Templarian** [comment]
@MrGrigri Yours was shipped without the stickers since it came directly from the printers (was cheaper). So was the @JapanYoshi's. All the UK posters will be going out shortly, haven't had a second to go over there and drop them off.

**Comment by Templarian** [comment]
@MrGrigri Oh wait, nvm. Mixing up people. Your's was US, yea I can send those, have extras.

**Comment by MrGrigri** [comment]
Thanks. The poster is awesome; now...where to put it!?

**Comment by JamesCoyle** [comment]
Did you get the UK stuff shipped? Haven't received any tracking info yet and hasn't arrived yet if you have.

**Comment by Templarian** [comment]
I have them sitting at home in a pile, just need to not be lazy and take them to USPS. Will try and do it this week.

**Comment by JamesCoyle** [comment]
Ah ok. :P
