### ISSUE TITLE
Icon "pencil-circle-outline" not included

### ISSUE THREAD

**Issue by KatzeKahn** [Templarian/MaterialDesign#1959]
Hi,

it seems that the "pencil-circle-outline" icon is not included in v1.8.36.

Greetz
Hans

Reason:
[View History Item](http://materialdesignicons.com/history/2D6ED7E6-1A63-4C79-91F8-0350FE26076F)

**Comment by PeterShaggyNoble** [comment]
It will be added in the next release, which you can track [here](https://github.com/Templarian/MaterialDesign/issues/1891). You can also view all icons that have been added or updated since the last release [here](https://materialdesignicons.com/history).
