### ISSUE TITLE
Microphone Icon

### ISSUE THREAD

**Issue by samdarcy42** [Templarian/MaterialDesign#196]
I could really use a microphone icon, not a "radio" mic per say, more of a music mic like: 

![mic](https://cloud.githubusercontent.com/assets/11177516/6498990/9df6a2e0-c2c1-11e4-9d13-0f0ac1f8e642.jpg)

Thanks!

- [ ] microphone-variant

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/microphone-variant

**Comment by samdarcy42** [comment]
Thanks! That is exactly what I need!

**Comment by Templarian** [comment]
A `-off` variant was added also.
