### ISSUE TITLE
XMPP Icon

### ISSUE THREAD

**Issue by andrewnenakhov** [Templarian/MaterialDesign#1960]
Icon for XMPP protocol https://xmpp.org/ , adapted to have all points aligned to pixel grid
[XMPP.svg.zip](https://github.com/Templarian/MaterialDesign/files/868215/XMPP.svg.zip)

**Comment by Templarian** [comment]
[![xmpp](https://materialdesignicons.com/icon/xmpp)](https://materialdesignicons.com/icon/xmpp)

Took a while, knocking through the backlog, but this one got in. 😅  Thanks!
