### ISSUE TITLE
spartan

### ISSUE THREAD

**Issue by nvasilov** [Templarian/MaterialDesign#1961]
![image](https://cloud.githubusercontent.com/assets/17977727/24309541/e867159a-10d4-11e7-8f18-5e2e13f5be07.png)

**Comment by MrGrigri** [comment]
Are you specifically looking for a spartan or just a knight's helmet? 

I believe this could be tied to https://github.com/Templarian/MaterialDesign/issues/1935

**Comment by nvasilov** [comment]
I like '300 spartances' movie and I found the logo of this company (http://www.spartanrecoveries.com/). I was looking something like that in vector format, for my small android application... it is not related to knight's helmet... sorry for my english

**Comment by PeterShaggyNoble** [comment]
I don't know that it would be possible to make this fit the MD guidelines. Leaving open for now for feedback from the rest of the team.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
