### ISSUE TITLE
relationship tree and activity icon

### ISSUE THREAD

**Issue by sayantansinha** [Templarian/MaterialDesign#1962]
It would be really nice if we can have a specific relationship tree icon which would depict relationships or tree or both.
Also, a specific activity icon would also make more sense which would drive more on the depiction of company or business activities

**Comment by PeterShaggyNoble** [comment]
Would `file-tree` suit your needs for a relationship tree?

[![](https://materialdesignicons.com/icon/file-tree)](https://materialdesignicons.com/icon/file-tree).

Can you elaborate on or provide an example of what you're looking for in the activity icon?

**Comment by PeterShaggyNoble** [comment]
Closing this due to a lack of response.
