### ISSUE TITLE
DJ

### ISSUE THREAD

**Issue by lawloretienne** [Templarian/MaterialDesign#1963]
https://icons8.com/web-app/5731/dj

**Comment by PeterShaggyNoble** [comment]
Especially at smaller sizes, that one looks like someone sitting cross-legged to me. I think a record might work better to represent a DJ but that could be context-dependent.

**Comment by goyney** [comment]
We have things, such as `headphones`, `album`, and `record-player` which could all be contextually used for a DJ.

@lawloretienne Would any of these be sufficient for your request?

**Comment by JapanYoshi** [comment]
I've just fiddled around trying to make a DJ deck icon, but there's just not enough space to put both a scratcher and a fader (like the one in ``tune``) inside a rectangle.

**Comment by goyney** [comment]
Don't think this is going to work in the space we have. I'd recommend taking a look at some of the other icons that would contextually work with a DJ. If you have another idea, we can always take another shot at it. Just comment back here. Thanks for the suggestion!
