### ISSUE TITLE
Download only required icons as web font

### ISSUE THREAD

**Issue by mkarthi-cb** [Templarian/MaterialDesign#1965]
Hello There,

There is any way to download only required(set of) icons as web font. Instead of using all the icons?

-Thanks in advance.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site/issues/17

https://materialdesignicons.com/design Contains all the optimized SVG files for the latest release.

We'll be working to have a standard build process available after the release of the new website.
