### ISSUE TITLE
file-spreadsheet-box

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#1966]
We have the Google Docs and Google Slides icons but not one for Google sheets.

I pulled this one from the Google Drive android APK. They also use a little table instead of the T in larger icons, but I think this one looks nice at all sizes.

![google_sheets](https://cloud.githubusercontent.com/assets/18021678/24376203/11de47dc-1309-11e7-8a74-c67df9ad253f.png)

**Comment by PeterShaggyNoble** [comment]
This is available in the [extended stock icon set](https://petershaggynoble.github.io/MDI-Sandbox/extended/) as `drive spreadsheet`.

[![drive-spreadsheet](https://user-images.githubusercontent.com/15157491/33124333-78baae8c-cf74-11e7-9993-235f415deec0.png)](https://github.com/Templarian/MaterialDesign/files/1495667/drive-spreadsheet.zip)

**Comment by k5cents** [comment]
@PeterShaggyNoble Any chance the extended set will get advance export functionality? I primarily use these icons as PNGs and the advance export feature is a godsend.

**Comment by PeterShaggyNoble** [comment]
It's a possibility but it'd be low priority. A few of the extended icons have been already been added, there're more to come before the next release and, eventually, they'll all be available here and to use in the advanced export.

In the meantime, you could "hack" the icon editor in the [sandbox](https://petershaggynoble.github.io/MDI-Sandbox/) to use any icon you want by inspecting the `path` node in the editor preview and replacing the value of the `d` attribute with the path data of the icon you want to edit. Note that if you're copying path data from the extended icons linked above then you'll also need to copy the `transform` attribute across as well.

**Comment by PeterShaggyNoble** [comment]
I went ahead and created a [new icon editor](https://petershaggynoble.github.io/MDI-Sandbox/editor/) that allows you to feed it the path data of an SVG to create a PNG from. It currently only works with 24*24 SVGs and 512*512 SVGs that are vertically flipped, but that should be enough to cover the [stock](https://github.com/google/material-design-icons/), community & [extended](https://petershaggynoble.github.io/MDI-Sandbox/extended/) icons.

**Comment by Templarian** [comment]
[![google-spreadsheet](https://materialdesignicons.com/icon/google-spreadsheet)](https://materialdesignicons.com/icon/google-spreadsheet)
