### ISSUE TITLE
Icon request: Statistic

### ISSUE THREAD

**Issue by dontbyte** [Templarian/MaterialDesign#1967]
Maybe something like:
https://www.iconfinder.com/icons/973349/analysis_arrow_chart_graph_growth_increase_statistic_icon

**Comment by brainscript** [comment]
If you just need an icon for statistics, you can use [`chart-line`](https://materialdesignicons.com/icon/chart-line).
If you need to show the trend, there are [`trending-down`](https://materialdesignicons.com/icon/trending-down), [`trending-neutral`](https://materialdesignicons.com/icon/trending-neutral) and [`trending-up`](https://materialdesignicons.com/icon/trending-up).

**Comment by dontbyte** [comment]
chart-line fits perfectly, thank you very much @brainscript!
