### ISSUE TITLE
Reset

### ISSUE THREAD

**Issue by dontbyte** [Templarian/MaterialDesign#1968]
Just an icon for reset, like "lock-reset" / "password-reset" but without the lock.

**Comment by brainscript** [comment]
What about [`backup-restore`](https://materialdesignicons.com/)?

**Comment by dontbyte** [comment]
yes, thanks @brainscript! Is it possible to add multiple tags to an icon so that it's easier to find?

**Comment by PeterShaggyNoble** [comment]
`replay` and `undo-variant` would be other options you could use.

![](https://materialdesignicons.com/icon/replay) ![](https://materialdesignicons.com/icon/undo-variant)

**Comment by GreenTurtwig** [comment]
Perhaps there should be another icon based on `backup-restore` but without the dot in the centre, simply named restore.

**Comment by GreenTurtwig** [comment]
[restore.zip](https://github.com/Templarian/MaterialDesign/files/881453/restore.zip)

**Comment by Templarian** [comment]
I guess I have to rename the current icon to `restore-clock` and this can be `restore`.

**Comment by Templarian** [comment]
[![restore](https://materialdesignicons.com/icon/restore)](https://materialdesignicons.com/icon/restore)
