### ISSUE TITLE
Prefered Polymer Usage?

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#1970]
So there are one or two really old issues about this but I've not seen anything in the way of progress. Have we decided on the best way to use MDI with Polymer?

Currently I can only find the download for `mdi.html` buried away deep in the documentation and installing it manually is a pain when it comes to updating. Is there an easy way to get `mdi.html` via bower instead of manually downloading it and adding it and/or do we have a better solution yet?

**Comment by JamesCoyle** [comment]
Also noticed the import in `mdi.html` seems broken. 

File structure:
```
bower_components
| mdi
| | mdi.html
```

Import:
```
<link rel="import" href="../bower_components/iron-iconset-svg/iron-iconset-svg.html">
```

The path ends up being `bower_components/bower_components/iron-iconset-svg/iron-iconset-svg.html`.

**Comment by Templarian** [comment]
@JamesCoyle I don't currently use Polymer, those files were quickly created a long time ago to solve an issue. If you want to help a ton and write the documentation for the new site and let me know what needs to be changed for these files I can fix the issue.

https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/getting-started-polymer.md

I can make a distribution repo and a Bower/NPM repo and permission you to them if this is something you want to help with?

Repo: `MaterialDesign-Polymer` NPM/Bower: `mdi-polymer`

**Comment by Templarian** [comment]
@JamesCoyle What is your NPM username?

I registered the org `@MaterialDeisign` and this might be useful to start adding you guys to it to help manage this stuff.

**Comment by JamesCoyle** [comment]
Just created one as `jamescoyle`. I'll try help out where I can but I've been pretty busy with my final year at uni so don't have much free time at the minute. Just handed in one of the final bits of coursework I have left so taking a couple of days off this weekend to relax. :P

I'm not really sure what the best way to implement it would actually be. The current method of shoving all of the SVGs into a file works well enough but just feels wrong. It's really wasteful on network resources considering most of the icons won't be used and isn't particularly good when we update the iconset as the entire file has to be redownloaded and re-cached. It would be much better if we could request individual SVGs for each icon that could then be cached but then you have the issue of the number of individual requests on initial load and also the issue that icons can't be added at runtime. 

It's a tough one as we have to consider both the efficiency of our users projects as well as the resource usage on MDI's servers. As the icon set grows the former becomes a much bigger issue but pretty much every solution would end up with more usage on the CDN. 

I definitely think going forward we should provide some sort of development tools which can optimise icon usage in projects. Libraries for PHP, Python, NodeJS etc would probably be the best way to tackle the issue as they don't require the person using the icons to implement a custom optimization but still provide flexibility should they have a specific requirement. I'd probably provide tools that can request data from our servers and maintain a database of icons on theirs. Then provide a library which HTML resources can be preprocessed through and have SVG icons inserted by looking them up in the database. Obviously this isn't gonna work for Polymer though (and probably some other situations).

**Comment by Templarian** [comment]
That's okay, yea, I've been apprehensive adding additional packages for this exact reason. It would be super wasteful for someone to include all the icons. We're even getting to the point where adding all the icons in the webfont, but I'm going to quietly work on a solution for that after the site launch.

I know eventually we're going to need a solution to let users login and generate packages, but that's a whole project in itself. Yea, lets keep this open, and maybe a polymer user can think of a nice solution.

For Angular 2 I'll be releasing a component to help with this, but it works by letting a user simply append the icons they are actively using in a list.

**Comment by JamesCoyle** [comment]
The main issue is how to deal with icons inserted at runtime. It's easy enough for a user to generate a custom package and eventually we can provide tools to do so but it then leaves them limited if they need to use icons that are inserted after initial load. They would need every page on their site to include all of the icons used on the site so it isn't really saving all that much in terms of resources. It's probably better to use our CDN and benefit from cross site caching in that case. It's a shame we can't just get everyone to install the font by default. :P 

I think we need to think about what we want to achieve, what limitations we have, and how we can best meet the needs of users. It's really one of those unsolvable issues as we have to balance network usage, server usage, and caching ability. It would be great to provide individual SVG resources as they could be individually cached but browsers are still awful at parallelization of requests (until HTTP2 is standard everywhere). The best option is probably to implement multiple different systems. 

- All icons together in one package (WebFont, SVG, Polymer etc)
- Individual SVGs (annoying for users to work with on a large scale but great for the odd icon)
- Customized packages (requires site features - might end up having to be a premium service)
- An API to request SVG paths (allows for customizable performance optimizations)

I don't really know how you are currently storing icons but personally I'd be maintaining a database of SVG paths in a table and then linking those to icon names etc in other tables. We could then provide an API to allow users to request SVG paths as JSON or CSV files. This would then allow for the creation of libraries for specific platforms/languages that could request icons and cache them locally in a lookup table. It could even allow icons to have multiple names (so users could use google's icon names or aliases) when using this API (obviously our icon packages would use the default MDI names).

**Comment by JamesCoyle** [comment]
Now 2.0 is out it's probably time we made a start on a polymer release... Still not entirely sure how best to implement it though. Making it easy to use either means the app will be unable to handle dynamically added content that has icons in, or it will have to include every icon. 

I'm not really sure whether it would be that much of an issue just including them all as caching would handle subsequent page loads and it isn't really THAT big of a file. I think just a script to generate a new mdi.html file for each release uploaded to bower would do the trick.
