### ISSUE TITLE
Drama masks

### ISSUE THREAD

**Issue by fraaalk** [Templarian/MaterialDesign#1972]
It would be nice to have an icon which looks like the mask of the phantom of the opera, or a carnival mask or 2 mask from venice.

**Comment by PeterShaggyNoble** [comment]
The tragedy and comedy masks would be a nice addition too.

**Comment by Per4merKC** [comment]
When you search Google Maps, you can see there is an icon for "Theatre" which shows comedy/tragedy masks.  This would be a great addition to the MDI set.

**Comment by augustin32** [comment]
Theatre Masks/Drama Masks :)
![drama-masks24](https://user-images.githubusercontent.com/14167196/31048228-a9559664-a621-11e7-822d-05a25aa27032.png)
![drama-masks36](https://user-images.githubusercontent.com/14167196/31048229-ab37a378-a621-11e7-9938-c4d98b500fda.png)
![drama-masks48](https://user-images.githubusercontent.com/14167196/31048230-acefb8f4-a621-11e7-8b14-8fbe0c7b56dc.png)
[drama-masks.zip](https://github.com/Templarian/MaterialDesign/files/1346659/drama-masks.zip)

**Comment by CoDEmanX** [comment]
The sad face is sadly not facing the beholder 😞

**Comment by bastienlemaitre** [comment]
Any new ?

**Comment by Templarian** [comment]
@bastienlemaitre It wasn't assigned a milestone so it kept getting overlooked. Thanks for the heads up.

**Comment by Templarian** [comment]
[![drama-masks](https://materialdesignicons.com/icon/drama-masks)](https://materialdesignicons.com/icon/drama-masks)
