### ISSUE TITLE
Icon Request: Customer support

### ISSUE THREAD

**Issue by bimemto** [Templarian/MaterialDesign#1973]
It would be nice to have an icon for customer services, customer supporter. Maybe something like this

<img width="511" alt="screen shot 2017-03-29 at 3 53 16 pm" src="https://cloud.githubusercontent.com/assets/393472/24446596/44542f7a-1498-11e7-95c2-3d547e6c9679.png">

**Comment by PeterShaggyNoble** [comment]
That already exists as `headset`.

![](https://materialdesignicons.com/icon/headset)
