### ISSUE TITLE
Getting to work in a webpacked scss file

### ISSUE THREAD

**Issue by Anupheaus** [Templarian/MaterialDesign#1975]
Sorry if I'm being completely dumb here but I'm really struggling to see what I am doing wrong.  I've installed the package using `npm install` (I manually wrote the dependency into the package.json).  I know it is installed, it is in my `node_modules` directory.

I'm creating a webpage now (in TypeScript) and using webpack to package the files together and I've got a sass-loader working with that too. 
So here is the line in TypeScript that imports my `.scss` file:
```TypeScript
import './styles.scss'
```

And here is the `styles.scss`:
```SASS
@mixin renderIcon($name) {	
	&::before {
		font: normal normal normal 24px/1 'Material Design Icons';
		content: char(nth($hexes, index($names, $name)));
	}
}
```
This is a variation of what is on your [getting started page](https://materialdesignicons.com/getting-started).

When webpack parses it though, it says `Undefined variable: $hexes`.

How do I get the scss file to know about the $hexes variable please?

**Comment by Templarian** [comment]
Didn't have time to look into this until now, but those docs are very out of date.

https://github.com/Templarian/MaterialDesign-Webfont/blob/master/scss/_variables.scss

We've restructured the code, will need to update that page.

Updated is below... but you might as well use `mdi('account')` if you are including the functions.

```
char(map-get($mdi-icons, $name));
```
