### ISSUE TITLE
New item Doors

### ISSUE THREAD

**Issue by turboc1208** [Templarian/MaterialDesign#1976]
I see you have a glass door.  

How about a solid open and closed door.  Like a traditional door showing door frame a thin white line inside it framing the actual door and a door knob of some type.  and a door frame with the door open maybe 45 degrees or something.

**Comment by Templarian** [comment]
Duplicate of #1822

**Comment by PeterShaggyNoble** [comment]
`glassdoor`, by the way, is a [brand icon](http://glassdoor.com).
