### ISSUE TITLE
Single-Message Icon from Google's Android Messages

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#1977]
This icon from the updated Android Messages aka Google Messenger. 

![single_message](https://cloud.githubusercontent.com/assets/18021678/24484179/dd6a9352-14ca-11e7-9ec5-326b7cf90ef5.png)

It's present on both the App Icon and used as the status bar icon. The icon for multiple messages would also be nice.

**Comment by PeterShaggyNoble** [comment]
Does `message-text` fit your needs?

![](https://materialdesignicons.com/icon/message-text)

**Comment by Templarian** [comment]
@PeterShaggyNoble I think this is a logo request more than an icon. Hmm... yea we can add it.

`google-messages` since that's the current name (one of their countless message apps).

**Comment by k5cents** [comment]
@Templarian Actually, Google Messenger is now [Android Messages](https://play.google.com/store/apps/category/GAME).

@PeterShaggyNoble I'm currently using the single-message icon, which is essentially the same thing, but it bugs me that it's not the exact one used by Google.

**Comment by Templarian** [comment]
@k5cents Oh, you're right, what a weird name for that app. I have it installed, but it just says "messages" under the icon.

Guess I could call it `android-messages`. Should be fine, just odd that Google named it like that.

**Comment by Templarian** [comment]
Added. 😃
