### ISSUE TITLE
Bee

### ISSUE THREAD

**Issue by endlessbux** [Templarian/MaterialDesign#1978]
I cannot find a bee icon, it would be great if this was in your iconset

**Comment by PeterShaggyNoble** [comment]
From Google's Material Icons Extended set:

[![emoji_nature](http://mdi.houseofdesign.ie/tools/preview/?icon=emoji_nature&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50987300-49314280-14d7-11e9-88a4-0c05ca0846fb.png)![image](https://user-images.githubusercontent.com/1015040/50987309-51897d80-14d7-11e9-92c4-d5f26c5576d7.png)

[bee.zip](https://github.com/Templarian/MaterialDesign/files/2746524/bee.zip)

**Comment by JamesCoyle** [comment]
Probably best to alias `fly` too.

**Comment by goyney** [comment]
[![bee](https://materialdesignicons.com/icon/bee)](https://materialdesignicons.com/icon/bee)[![bee-flower](https://materialdesignicons.com/icon/bee-flower)](https://materialdesignicons.com/icon/bee-flower)
