### ISSUE TITLE
Camera Specs

### ISSUE THREAD

**Issue by kumvert** [Templarian/MaterialDesign#1979]
I really need more camera icons, such as: Metering Mode Icon Sets (image attached), and Panorama Format Icon. Thanks! I need this when I want to provide camera information for image previews.

![metering modes explained - www mommatography com](https://cloud.githubusercontent.com/assets/26806388/24533643/b017e5e8-158e-11e7-9409-262dba0289b9.jpeg)

**Comment by kumvert** [comment]
Hey so I designed the icons myself on Apple Keynote haha, do these look good? I tried combining the Canon, Nikon, and other camera metering modes as well as iOS and Android metering modes and I came up with 4 universal modes. Are there any modes that I should add? Do these icons look good?

![metering_matrix](https://cloud.githubusercontent.com/assets/26806388/24561084/145f93da-160b-11e7-8c0c-356cb1dcbf14.jpeg)
![metering_center weighted](https://cloud.githubusercontent.com/assets/26806388/24560885/22548e10-160a-11e7-8e67-55e459ee145f.jpeg)
![metering_partial](https://cloud.githubusercontent.com/assets/26806388/24560887/2257861a-160a-11e7-8cd6-702ba25bc47e.jpeg)
![metering_spot](https://cloud.githubusercontent.com/assets/26806388/24560886/2255c230-160a-11e7-9686-073b6bbecc00.jpeg)

**Comment by Templarian** [comment]
We can tweak these and get them in... for future reference the rectangles need to be 20 width not 24. You might be the first contributor to use a slide show app to make their icons. 😄 

![image](https://cloud.githubusercontent.com/assets/338885/24561312/de647d58-160b-11e7-9450-ac5fc9cc166c.png) ![image](https://cloud.githubusercontent.com/assets/338885/24561284/c60c5f5a-160b-11e7-9860-b151ec8aedbe.png)

From the MD Guidelines on icons: https://material.io/guidelines/style/icons.html#icons-system-icons

**Comment by kumvert** [comment]
my mistake! yes I read the material design guide but I guess I looked over that detail, sorry! Yes I'm only just learning how to design so I don't want to pay for adobe and my trial ended. 😂

**Comment by kumvert** [comment]
Is this better?

![metering_center weighted](https://cloud.githubusercontent.com/assets/26806388/24561976/a7b53bd2-160e-11e7-9e15-44e4df9febcd.jpeg)
![metering_matrix](https://cloud.githubusercontent.com/assets/26806388/24561979/a7bf5da6-160e-11e7-8aa0-59962debcbf4.jpeg)
![metering_partial](https://cloud.githubusercontent.com/assets/26806388/24561978/a7bad9e8-160e-11e7-90ec-04d1b773779b.jpeg)
![metering_spot](https://cloud.githubusercontent.com/assets/26806388/24561977/a7ba1cba-160e-11e7-8ee0-ae0f4671d70f.jpeg)

**Comment by Templarian** [comment]
[![camera-metering-center](https://materialdesignicons.com/icon/camera-metering-center)](https://materialdesignicons.com/icon/camera-metering-center) [![camera-metering-partial](https://materialdesignicons.com/icon/camera-metering-partial)](https://materialdesignicons.com/icon/camera-metering-partial) [![camera-metering-matrix](https://materialdesignicons.com/icon/camera-metering-matrix)](https://materialdesignicons.com/icon/camera-metering-matrix) [![camera-metering-spot](https://materialdesignicons.com/icon/camera-metering-spot)](https://materialdesignicons.com/icon/camera-metering-spot)
