### ISSUE TITLE
Shop/Store

### ISSUE THREAD

**Issue by natnayr** [Templarian/MaterialDesign#1980]
Thank you for your lovely icons, i've been using them religiously in my android app.

Would like a shop/store icon similar to the garage-open sign but in a shop-look

**Comment by PeterShaggyNoble** [comment]
![](https://materialdesignicons.com/icon/store) ![](https://materialdesignicons.com/icon/store-24-hour)

**Comment by natnayr** [comment]
Cheers, thanks!!
