### ISSUE TITLE
Cloud Rest API

### ISSUE THREAD

**Issue by FernandoFranco** [Templarian/MaterialDesign#1981]
Would like a cloud, but with a code-braces inside plz

**Comment by kumvert** [comment]
something like this? I'm not a contributor but I wanted to see if this is what you were going for.

![cloud rest api 001](https://cloud.githubusercontent.com/assets/26806388/24566628/c7791a40-161f-11e7-93e0-9adcab5e8b30.jpeg)

**Comment by FernandoFranco** [comment]
Yes, but replacing "<>" to "{ }"

**Comment by MrGrigri** [comment]
@FernandoFranco I believe that curly brackets would be too noisy.

**Comment by JamesCoyle** [comment]
I agree. The cloud is already bigger than it ideally should be (supposed to be a 2 square wide border around the icon).

**Comment by Templarian** [comment]
@JamesCoyle The cloud is the right size as per the official set to look proportionally right. But I kind of agree also the `<>` look nice. We may need another way other than `{}` as it will be too cramped to represent a JSON Rest API in the cloud.

**Comment by wopian** [comment]
While `<>` does look nice, it is in no way synonymous of REST or json:api.

**Comment by GreenTurtwig** [comment]
Got a cloud icon similar to what @kumvert posted here:
[cloud-code-tags.zip](https://github.com/Templarian/MaterialDesign/files/905055/cloud-code-tags.zip)

I know it doesn't represent the request in question, but I thought it looked nice. :wink:

**Comment by rtvb** [comment]
A REST API could also be xml, so that would be <>.

**Comment by kumvert** [comment]
sorry this took so long, I finally have a day off haha. what about this?

![cloud rest api 001](https://cloud.githubusercontent.com/assets/26806388/24886348/88c7e946-1e19-11e7-8dac-8391a38e5bcf.jpeg)

**Comment by kumvert** [comment]
sorry this took so long, I finally have a day off haha. what about this?

![cloud rest api 001](https://cloud.githubusercontent.com/assets/26806388/24886376/ad421fda-1e19-11e7-8399-29410efb5e5d.jpeg)

**Comment by FernandoFranco** [comment]
Perfect

**Comment by MrGrigri** [comment]
This is great. Can we get SVG's for both? I believe that we can have both as `api-json` and `api-xml`.

**Comment by kumvert** [comment]
I don't have a program that can do that!! This was made using Keynote 😅 but I provided a grid to make it easier to recreate

**Comment by GreenTurtwig** [comment]
I posted the SVG for the first one earlier FYI. Gonna work on getting the second one "converted" over tomorrow. 🐈

**Comment by MrGrigri** [comment]
@kumvert can you by change use [inkscape](https://inkscape.org/en/)? It's free.

**Comment by kumvert** [comment]
I will look into it thank you!

**Comment by Templarian** [comment]
[![cloud-braces](https://materialdesignicons.com/icon/cloud-braces)](https://materialdesignicons.com/icon/cloud-braces) [![cloud-tags](https://materialdesignicons.com/icon/cloud-tags)](https://materialdesignicons.com/icon/cloud-tags)

- [ ] Alias `cloud-json`
- [ ] Alias `cloud-xml`
