### ISSUE TITLE
Parking in Poi

### ISSUE THREAD

**Issue by snuuve** [Templarian/MaterialDesign#1982]
Icon request: "Parking in Poi"

![parking-in-poi 3x](https://cloud.githubusercontent.com/assets/9519759/24615440/8bbe2eca-188e-11e7-83bb-a3e66bb9972d.png)

**Comment by MrGrigri** [comment]
I don't even know what that means? Do you have a link or something? On another note, we try to avoid icons that are in English. We're trying to make this a multilingual pack.

**Comment by snuuve** [comment]
POI = Point of interest.

In my App, i have two notifications : 
 - Vehicles that park/stop in POI
 - Vehicles that park/stop out of POI (here im using alone P icon)

**Comment by wopian** [comment]
The parking symbol is essentially universally the 'P' sign as its part of ISO 7001.

**Comment by PeterShaggyNoble** [comment]
Closing this as would seem to be too niche.

@snuuve, if you van provide a more general use case outside the context of your app, we can revisit this issue.
