### ISSUE TITLE
Icon of a Driver or Chauffeur

### ISSUE THREAD

**Issue by sachingawas** [Templarian/MaterialDesign#1984]

**Comment by rtvb** [comment]
What is your purpose? I would prefer a more generic driver icon, without a chauffeur hat or motor helmet.

![](https://cdn1.iconfinder.com/data/icons/occupations-3/100/07-512.png)

![](http://icons.iconarchive.com/icons/icons8/windows-8/512/Transport-Driver-icon.png)

![]()

![]()

**Comment by PeterShaggyNoble** [comment]
Would the `steering` icon suit your needs?

![](https://materialdesignicons.com/icon/steering)

**Comment by sachingawas** [comment]
Certainly. It looks nice.

Sachin Gavas | UX
