### ISSUE TITLE
You're missing Google's gesture icon

### ISSUE THREAD

**Issue by AnthonySmith** [Templarian/MaterialDesign#1985]
I thought you had all Google's Material Design icons but you're missing a few including:

https://material.io/icons/#ic_gesture

**Comment by Templarian** [comment]
[![gesture](https://materialdesignicons.com/icon/gesture)](https://materialdesignicons.com/icon/gesture)

Unfortunately since we just released yesterday it's going to be a while until this sees a release in the webfont, but it's in the system now.
