### ISSUE TITLE
Update version number on download modal

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1986]
The button in the modal for downloading the webfont on the website is still showing the version as 1.8.36.

![image](https://cloud.githubusercontent.com/assets/15157491/24656816/dab3a9da-193b-11e7-9b34-390e41c3b372.png)

**Comment by Templarian** [comment]
You're just cached, but that text should be white. What browser is that?

Hard refresh to clear your cache.

**Comment by PeterShaggyNoble** [comment]
I had force refreshed a couple of times; it must be cached somewhere along the line to me, so.

The text is white in the default and `:hover` states; that's the `:active`/`:focus` state above.

**Comment by Templarian** [comment]
Oh that's a more minor bug, goes in the large pile of site issues not worth fixing until the new site is online.
