### ISSUE TITLE
euro-coin

### ISSUE THREAD

**Issue by echthard** [Templarian/MaterialDesign#1987]
You have a coin with a dollar sign, but not with a euro sign.

**Comment by melvinsalas** [comment]
Yes, It's [currency-eur](https://materialdesignicons.com/icon/currency-eur).

**Comment by melvinsalas** [comment]
close

**Comment by echthard** [comment]
No, that's something different. Why should I close this request? 

A coin is something different than a sign itself. Currency is not similar to money.

**Comment by melvinsalas** [comment]
I see...

We don't need a euro-coin, We should request a cent-coin...

It's most International, Am I right?

**Comment by echthard** [comment]
Well, maybe there are use cases for a coin with the number 1 inside. But I would like to express money and don't think the paper bills are right. 

The icon I'm looking for is for "saving money". The coin with the dollar sign seems cool, but we use euros in NL. 

So my opion is that both coins would be usefull.

**Comment by melvinsalas** [comment]
You need 1 icon like [this](https://cdn2.iconfinder.com/data/icons/picons-basic-1/57/basic1-079_piggy_bank_saving-512.png)

**Comment by Templarian** [comment]
@echthard As more currencies get added leading up to the `v2.x` a decision was not add anymore currencies specific symbols (same goes with icons with text which are being replaced). This reduces the need to create all the variations for each.

I would recommend using a SVG/Vector drawable for this use or the [coins](https://materialdesignicons.com/icon/coins) icon.

Thanks!

**Comment by Templarian** [comment]
@melvinsalas The contributor team will close issues if needed. 😄
