### ISSUE TITLE
Icon for page-divider <hr> tag, image gallery upload, Image + text (side by side) 

### ISSUE THREAD

**Issue by ganesharulanantham** [Templarian/MaterialDesign#1988]
A light intuitive icon for all below buttons. 

<img width="421" alt="screen shot 2017-04-05 at 1 15 32 am" src="https://cloud.githubusercontent.com/assets/3982074/24675596/65eabf28-199d-11e7-91d2-993d8ec7d6ef.png">

**Comment by PeterShaggyNoble** [comment]
Many of these exist already.

**Comment by JamesCoyle** [comment]
If you still need these, please open individual requests for each icon.
