### ISSUE TITLE
Data usage icon

### ISSUE THREAD

**Issue by savaka2** [Templarian/MaterialDesign#1989]
I would like to see the data usage icon ([this](http://i.cubeupload.com/QgiPeZ.png))

**Comment by MrGrigri** [comment]
Are you referring to the Google MD Icon `data-usage` found [here](https://material.io/icons/#ic_data_usage)?

**Comment by savaka2** [comment]
Yes

**Comment by MrGrigri** [comment]
![data-usage](https://cloud.githubusercontent.com/assets/4528551/24711072/297bd038-19dc-11e7-9e9f-1c028cd45204.png)

[data-usage.zip](https://github.com/Templarian/MaterialDesign/files/899722/data-usage.zip)

**Comment by savaka2** [comment]
ok thanks

**Comment by JamesCoyle** [comment]
We'll close when the icon is added

**Comment by savaka2** [comment]
ok

**Comment by savaka2** [comment]
When I open the svg it is [this](http://i.cubeupload.com/E9c7Lm.png)

**Comment by MrGrigri** [comment]
I don't understand how that's happening. Even when I download it for myself, the SVG is fine. What program are you using to view the SVG?

**Comment by savaka2** [comment]
inkscape

**Comment by MrGrigri** [comment]
That's weird...try chrome.

**Comment by MrGrigri** [comment]
![image](https://cloud.githubusercontent.com/assets/4528551/24726998/991a34ea-1a11-11e7-9c04-f256d89bb0ab.png)

What version of Inkscape are you using? I'm using the latest (0.92.1 r15371).

**Comment by savaka2** [comment]
0.91 maybe that's it?

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/chart-arc exists.

Are you guys fine with me calling this `chart-donut` (we may have a variant with an inner circle).

**Comment by MrGrigri** [comment]
I'm fine with `chart-donut`, but keep an alias for `data-usage` because that's the google term. I'll try to get a filled in version as well tonight.

**Comment by MrGrigri** [comment]
Ok, I believe that they should be `chart-donut` and `chart-donut-outline`, or that's what I've named them.

![chart-donut](https://cloud.githubusercontent.com/assets/4528551/24737860/146becd2-1a4f-11e7-8a14-3d0bd8a4cd07.png) ![chart-donut-outline](https://cloud.githubusercontent.com/assets/4528551/24737859/146b36ca-1a4f-11e7-98d0-573ea97e8e7c.png)

[chart-donut.zip](https://github.com/Templarian/MaterialDesign/files/901471/chart-donut.zip)

**Comment by Templarian** [comment]
That's just a pie chart, a donut chart has inner "rings".

**Comment by Templarian** [comment]
[![chart-donut](https://materialdesignicons.com/icon/chart-donut)](https://materialdesignicons.com/icon/chart-donut) [![chart-donut-variant](https://materialdesignicons.com/icon/chart-donut-variant)](https://materialdesignicons.com/icon/chart-donut-variant)

- [ ] Alias `chart-doughnut`
- [ ] Alias `chart-doughnut-variant`
- [ ] Alias `data-usage`

**Comment by PeterShaggyNoble** [comment]
Google have a [donut chart icon](https://material.io/icons/#ic_donut_large) that differs from their data usage one, as well as [this variant](https://material.io/icons/#ic_donut_small).

**Comment by MrGrigri** [comment]
Ha, you're right. I guess I was tired and your inner circle didn't make sense at the time. Oh well.
