### ISSUE TITLE
Rename and edit text icons

### ISSUE THREAD

**Issue by ashughes** [Templarian/MaterialDesign#199]
Google has an existing icon for [*rename*](http://materialdesignicons.com/icon/rename-box), however it doesn't really feel like rename to me. Unfortunately I can't really think of something much better. Maybe some thing like "T|" (a T and a cursor, or an A and a cursor).

At the very least, it would be nice to have a version of Google's rename icon that's not in a box (the inverse of the current icon).

It would also be great to have an icon for editing or changing text. This might be the same icon, but I could see it possibly being different.

- [x] rename
- [x] edit text

**Comment by CoDEmanX** [comment]
You can use the pencil:
https://materialdesignicons.com/icon/pencil

I posted a more traditional text cursor here:
https://github.com/Templarian/MaterialDesign/issues/270#issuecomment-125912536

**Comment by CoDEmanX** [comment]
[![cursor-text](https://materialdesignicons.com/icon/cursor-text)](https://materialdesignicons.com/icon/cursor-text)

[![textbox](https://materialdesignicons.com/icon/textbox)](https://materialdesignicons.com/icon/textbox)

Closing, because there are multiple viable options.
