### ISSUE TITLE
Thinner outter stroke on Chrome icon

### ISSUE THREAD

**Issue by Korszulak** [Templarian/MaterialDesign#1990]
![google-chrome](https://cloud.githubusercontent.com/assets/8146570/24686479/d503845e-1979-11e7-8ad3-08e9b27a05a2.png)

**Comment by Templarian** [comment]
Unfortunately this style won't fit in the MD guidelines. Try submitting the suggestion to MDI Light which will be open sourcing shortly and is much closer to this style.

https://github.com/Templarian/MaterialDesignLight
