### ISSUE TITLE
Remove currency-chf

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1991]
Although ₣ is a generic currency symbol for Francs, it's not actually used a symbol for the Swiss Franc - they instead use CHF or Fr.

With the French Franc being long defunct, the only currency I can find (with an admittedly quick search) that that does use the ₣ symbol at all is the Rwandan Franc (RWF) but they primarily use FRw and, even when the Franc symbol *is* used, it's written as R₣.

I propose, therefore, that `currency-chf` be renamed as `currency-franc`.

**Comment by Templarian** [comment]
If no one really uses it do we even need to include it? Sounds like we might as well delete it.

**Comment by PeterShaggyNoble** [comment]
I'd say it's probably safe to remove it, @Templarian, unless you have usage stats that say it should be kept.

It was never officially used to represent the French nor Belgian Franc and, after some more research, it isn't used to represent *any* current Franc, either.

**Comment by Templarian** [comment]
I do have stats...
![image](https://user-images.githubusercontent.com/338885/38686672-7a8c39ee-3e3a-11e8-9f8a-f18e18a8c9c8.png)

**Comment by JamesCoyle** [comment]
I'm for removing this one too. No point in having currencies that aren't actually used.

**Comment by goyney** [comment]
Removed!
