### ISSUE TITLE
currency-cny and currency-jpy share same symbol

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#1992]
Is it intentional that [currency-cny](https://materialdesignicons.com/icon/currency-cny) and [currency-jpy](https://materialdesignicons.com/icon/currency-jpy) look the same? Wouldn't an alias work here also?

**Comment by PeterShaggyNoble** [comment]
Yes, it was intentional; see #1918.

**Comment by Templarian** [comment]
The reason why I included 2 is because aliases don't reflect in the CSS. Assuming someone wants to map 3 character codes to a symbol this is more intuitive.
