### ISSUE TITLE
Money icon

### ISSUE THREAD

**Issue by perrosnk** [Templarian/MaterialDesign#1993]
Icon request: money

**Comment by MrGrigri** [comment]
Do the following not work?

![Cash](https://materialdesignicons.com/icon/cash) ![Cash 100](https://materialdesignicons.com/icon/cash-100) ![Cash Multiple](https://materialdesignicons.com/icon/cash-multiple) ![Cash USD](https://materialdesignicons.com/icon/cash-usd)

**Comment by perrosnk** [comment]
I searched on the website (https://materialdesignicons.com/) but could find them. Could you please share a link?

**Comment by PeterShaggyNoble** [comment]
Search for the names under the image previews.

There are also the coin icons:

![](https://materialdesignicons.com/coin/) ![](https://materialdesignicons.com/coins/)

As well as the currency icons (search for "currency").

**Comment by MrGrigri** [comment]
@perrosnk just search for `cash` instead.
