### ISSUE TITLE
TfL Logo

### ISSUE THREAD

**Issue by dintendocoltd** [Templarian/MaterialDesign#1996]
Hi,

Is it possible to get a Transport for London (TfL) logo? https://tfl.gov.uk/cdn/static/assets/icons/favicon-160x160.png

The only issue is with this potential design is that TfL uses the same varient of this logo for each of their transport services (such as Underground, Buses, Trams etc.).

**Comment by PeterShaggyNoble** [comment]
This could be beyond the scope of this project; brand icons, in general, are limited to major social networks these days. Although the argument could be made that this is a transportation icon more than it is a brand icon.

Would the existing transportion icons be any use to you? They would help you differentiate between each mode of transport.

![](https://materialdesignicons.com/icon/bus) ![](https://materialdesignicons.com/icon/subway) ![](https://materialdesignicons.com/icon/subway-variant) ![](https://materialdesignicons.com/icon/train) ![](https://materialdesignicons.com/icon/tram)

**Comment by GreenTurtwig** [comment]
If you **really** need one you can use this SVG:
[tfl.zip](https://github.com/Templarian/MaterialDesign/files/905392/tfl.zip)
But per their guidelines, you should really be using a blue version of the logo.

**Comment by Templarian** [comment]
Marking this as too specific. Logos really need to stick to the large social media. Eventually we may make a separate brand set and we'll go back through these closed issues, but right now it's not a priority.

Thanks for the suggestion!
