### ISSUE TITLE
Update to double colon syntax for pseudo-elements

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#1997]
Given that IE8 was the only browser that ever required the incorrect single colon syntax for CSS pseudo-elements and that IE8's [global usage](http://caniuse.com/#feat=css-gencontent) is currently at 0.36% (low enough for [StatCounter](http://gs.statcounter.com/) to lump it in with "other" browsers), I suggest updating the CSS files to use the correct double colon syntax for the v2.x release - `.mdi:before` becomes `.mdi::before`, and so on.

**Comment by Templarian** [comment]
Yep, was holding off this change until 2.0, almost made it in `1.9.32`, but didn't seem right for people using more relaxed version matches in their npm/bower.

**Comment by JamesCoyle** [comment]
I've added this to 4.0 as this should have been in ages ago...

**Comment by goyney** [comment]
This was done for 3.9.
