### ISSUE TITLE
Request: alarm

### ISSUE THREAD

**Issue by rtvb** [Templarian/MaterialDesign#1998]
For use with home automation. An **alarm** symbol. Some examples:

![](https://image.freepik.com/free-icon/police-light_318-64596.jpg)
![](https://cdn4.iconfinder.com/data/icons/web-app-media-contact-and-essential-simple-fill/512/Alarm_Danger_Light-512.png)
![](http://www.myiconfinder.com/uploads/iconsets/256-256-d126274718a0e884768ab345d31b53c0-alert.png)
![](http://www.iconninja.com/files/137/368/14/alarm-icon.png)

**Comment by MrGrigri** [comment]
Here is my attempt at two of them. One is a firehouse (bell) style, and the other is a light style.

![alarm-bell](https://cloud.githubusercontent.com/assets/4528551/24810564/ed5591d4-1b7f-11e7-8a9e-c4cd1675a069.png) ![alarm-light](https://cloud.githubusercontent.com/assets/4528551/24810563/ed54b124-1b7f-11e7-8675-fe322386b103.png)


[alarm.zip](https://github.com/Templarian/MaterialDesign/files/906216/alarm.zip)

**Comment by Templarian** [comment]
Naming `alarm-firehouse` (?) and `alarm-light`.

**Comment by MrGrigri** [comment]
Sounds good to me

**Comment by PeterShaggyNoble** [comment]
Or `alarm-bell` for the first?

**Comment by Templarian** [comment]
That might be better.

**Comment by rtvb** [comment]
I like both nut only need the second ;)

Do they comply to material design guidelines?

I would personally prefer them without the shining rays.

**Comment by Templarian** [comment]
[![alarm-light](https://materialdesignicons.com/icon/alarm-light)](https://materialdesignicons.com/icon/alarm-light) [![alarm-bell](https://materialdesignicons.com/icon/alarm-bell)](https://materialdesignicons.com/icon/alarm-bell)
