### ISSUE TITLE
Advanced color picker

### ISSUE THREAD

**Issue by ashughes** [Templarian/MaterialDesign#200]
There's already a [palette](http://materialdesignicons.com/icon/palette) icon, which I think is good for choosing a color from a set of standard colors.

It would be great to have an icon that represents choosing a color from an "advanced" color picker like this:

![Advanced color picker](http://3.bp.blogspot.com/-T-MY1UbBtoY/T_N9V9zpN3I/AAAAAAAABE4/BztbLj1R8Ak/s1600/device-2012-07-04-010312.png)

- [ ] advanced color picker

**Comment by Templarian** [comment]
There are 2 [eyedropper](http://materialdesignicons.com/icon/eyedropper) [icons](http://materialdesignicons.com/icon/eyedropper-variant). Would those work? If not I would suggest using either using the:

http://materialdesignicons.com/icon/border-color
http://materialdesignicons.com/icon/format-color-fill
Which is used with the http://materialdesignicons.com/icon/color-helper

**Comment by Templarian** [comment]
Let me know if these don't work by the way, I'm not sure what this icon would look like exactly.

**Comment by ashughes** [comment]
Unfortunately I don't feel like any of those capture "advanced color picker". However, I'm also not sure what an appropriate icon would look like. I was hoping others might have some ideas.

Right now, we use this icon, but I don't love it:
![advanced color picker icon](https://dl.dropboxusercontent.com/u/1718000/ic_action_colors_advanced_enabled.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/pallet-advanced

This is just a rough idea. I would like some input before I close this issue out.

**Comment by ashughes** [comment]
I like where you're going with it. I don't love the triangle selector at the bottom...maybe use the same negative space selector on the bottom as you do on the right?

**Comment by Templarian** [comment]
Yea, I agree. The triangle slider adds too much complexity.

**Comment by Templarian** [comment]
http://materialdesignicons.com/history You can compare the difference here.
