### ISSUE TITLE
Smoke

### ISSUE THREAD

**Issue by metbril** [Templarian/MaterialDesign#2000]
For use in home automation. Applicable for smoke detectors or air quality. 90 degrees rotated version of waves icon.

https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/waves.svg

**Comment by PeterShaggyNoble** [comment]
How's this?

[dry.svg](http://mdi.houseofdesign.ie/svg/dry.svg)

**Comment by rtvb** [comment]
![](http://mdi.houseofdesign.ie/svg/dry.svg)

**Comment by goyney** [comment]
@PeterShaggyNoble Your link is broken.

Removing the Contribution label.

**Comment by PeterShaggyNoble** [comment]
@goyney, fixed.

**Comment by goyney** [comment]
Here is the preview of @PeterShaggyNoble's contribution, fixed to align to the grid:
![image](https://user-images.githubusercontent.com/1015040/49033716-e16ca580-f17d-11e8-9fa6-b06cebf917ef.png)
[dry.svg.zip](https://github.com/Templarian/MaterialDesign/files/2616824/dry.svg.zip)

**Comment by JamesCoyle** [comment]
Would it be worth making the waves more arc based? These freeform curves don't really look that material to me.

**Comment by goyney** [comment]
This is a rotating 90 degrees version of our old `waves` icon, which was replaced. I agree with @JamesCoyle 100%. Also see https://github.com/Templarian/MaterialDesign/issues/2812, because it suffers the same issue. Perhaps we can improve both?

**Comment by JamesCoyle** [comment]
I feel it should be more like the ones in the hot tub icon:

[![](https://materialdesignicons.com/icon/hot-tub
)](https://materialdesignicons.com/icon/hot-tub)

**Comment by goyney** [comment]
This icon and #2812 both could use the same TLC. 😄 Moving to the Backlog for now.

**Comment by goyney** [comment]
Here's another idea, based off the smoke/steam pattern we've used in many icons now.

![image](https://user-images.githubusercontent.com/1015040/88748361-d4584480-d11e-11ea-84a8-0c610b6aee74.png)
[smoke.svg.zip](https://github.com/Templarian/MaterialDesign/files/4992058/smoke.svg.zip)

**Comment by goyney** [comment]
Added in v6.
