### ISSUE TITLE
Camera roll icon

### ISSUE THREAD

**Issue by r1si** [Templarian/MaterialDesign#2001]
Hi all! There is some camera roll icon?
here the googole one:
![ic_camera_roll_black_24dp](https://cloud.githubusercontent.com/assets/6353773/24836039/d6273b1e-1d11-11e7-8142-4559beb229b7.png)

but I can't find it in your wonderful library
Thanks a lot

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/film

We can add an alias for this to make it easier to find.

**Comment by GreenTurtwig** [comment]
Given alias.
