### ISSUE TITLE
Paper Scroll

### ISSUE THREAD

**Issue by dgngulcan** [Templarian/MaterialDesign#2002]
I needed a paper scroll icon to use with a virtual contract creation in app,
Some suggestions are bellow;

![](http://clipart-library.com/images/6cr5B75oi.jpg)

![](https://thumbs.dreamstime.com/z/vintage-scroll-paper-1599572.jpg)

![](http://www.clipartkid.com/images/688/14-old-scroll-paper-free-cliparts-that-you-can-download-to-you-YLztxb-clipart.jpeg)

**Comment by PeterShaggyNoble** [comment]
Would the `script` icon suit your needs?

![](https://materialdesignicons.com/icon/script)

**Comment by dgngulcan** [comment]
Yes it would, thank you!
