### ISSUE TITLE
trophy-broken

### ISSUE THREAD

**Issue by dgngulcan** [Templarian/MaterialDesign#2003]
A broken trophy icon to represent state of lost

may be this
https://materialdesignicons.com/icon/trophy 
broken like this
https://materialdesignicons.com/icon/heart-broken

**Comment by nkspappas** [comment]
@dgngulcan I've tried what you suggested.

<img width="125" alt="screen shot 2017-05-16 at 19 20 41 copy" src="https://cloud.githubusercontent.com/assets/22625723/26118045/2950f6e6-3a71-11e7-97d8-d7e42d75e181.png">

You can find the .svg in the following link:
> https://www.dropbox.com/sh/w8laog5xe9yclr2/AAAHnGwPbJk_gboQqlucxSeha?dl=0

**Comment by dgngulcan** [comment]
Thank you @nkspappas, looks sharp!

**Comment by nkspappas** [comment]
@dgngulcan anytime!

@Templarian if it passes your standards, feel free to add it on the materialdesignicons collection. :bowtie:

**Comment by CoDEmanX** [comment]
Preview & SVG with merged paths:

![image](https://user-images.githubusercontent.com/1309249/38770776-5a5040c8-4018-11e8-89cf-df9c4555cc61.png)

[trophy-broken.zip](https://github.com/Templarian/MaterialDesign/files/1910651/trophy-broken.zip)

**Comment by Templarian** [comment]
[![trophy-broken](https://materialdesignicons.com/icon/trophy-broken)](https://materialdesignicons.com/icon/trophy-broken)

@nkspappas Sorry took a bit, but eventually got it added. Please let me know when you hit 5 icons and I'll setup a contributor user.
