### ISSUE TITLE
HDR Camera icon

### ISSUE THREAD

**Issue by r1si** [Templarian/MaterialDesign#2004]
I think that HDR filter icon is very strange ( it looks good only for mountain :D)
So I have do two simple icon that descrive HDR camera effect.

[hdr_icons.zip](https://github.com/Templarian/MaterialDesign/files/908541/hdr_icons.zip)

Thanks a lot for your set!

**Comment by GreenTurtwig** [comment]
Google does have an icon in the same style (both on and off) for their official Camera app, we should probably get these added.
![image](https://cloud.githubusercontent.com/assets/15905797/24918629/f410e8fa-1ed8-11e7-824f-6c609b46b854.png)

**Comment by PeterShaggyNoble** [comment]
Is there a language concflict? Or is that an internationally recognised symbol, even in different alphabets?

**Comment by GreenTurtwig** [comment]
It's more an abbreviation than symbol, but yes, it's used in languages with different scripts.

**Comment by r1si** [comment]
ok, so can added it?

**Comment by Templarian** [comment]
Yea, this falls into more of a stock icon. Should be fine to add. Probably useful for other uses like show descriptions etc.

**Comment by r1si** [comment]
Here the google official icon!
https://material.io/icons/#ic_hdr_off
https://material.io/icons/#ic_hdr_on

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48989866-27802580-f0fa-11e8-9f14-a69260207552.png)![image](https://user-images.githubusercontent.com/1015040/48989875-31098d80-f0fa-11e8-8a87-ea6fcf0bdf0f.png)

[hdr.zip](https://github.com/Templarian/MaterialDesign/files/2613882/hdr.zip)

**Comment by Templarian** [comment]
Added `hdr` and `hdr-off`.
