### ISSUE TITLE
Chilli

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2006]
To indicate the spiciness of foods on a menu, for example.

**Comment by kumvert** [comment]
How do these look?

![chili-mild](https://cloud.githubusercontent.com/assets/26806388/24921207/a3f8a62e-1eaf-11e7-891f-408f8f8b885a.jpeg)
![chili-medium](https://cloud.githubusercontent.com/assets/26806388/24921211/a74cc030-1eaf-11e7-8184-120a0442c2ff.jpeg)
![chili-spicy](https://cloud.githubusercontent.com/assets/26806388/24921213/a9db3e26-1eaf-11e7-9dc5-06ce8c6900c5.jpeg)

**Comment by MrGrigri** [comment]
I fell as though the zig-zag lines are too distracting. When I see a serrano pepper (which is the common pepper used in spicy illustrations), I see more of a definitive stem and a bump at the top.

**Comment by kumvert** [comment]
I will fix those issues! I agree with the zig zag, it doesn't appear natural.

**Comment by kumvert** [comment]
okay, hopefully I addressed all the issues, and I have to say this definitely looks more like a pepper! I was having trouble when I wanted to overlap the icons, do these work? or how should I adjust the overlap?

![google design icons 001](https://cloud.githubusercontent.com/assets/26806388/24931493/1a891346-1ed3-11e7-8020-cd3d105750ba.jpeg)
![google design icons 002](https://cloud.githubusercontent.com/assets/26806388/24931496/1e3bbafc-1ed3-11e7-97a2-15da09f32a17.jpeg)
![google design icons 003](https://cloud.githubusercontent.com/assets/26806388/24931502/2101ef0e-1ed3-11e7-9f42-b0756ef0a85d.jpeg)

**Comment by Templarian** [comment]
[![chili-mild](https://materialdesignicons.com/icon/chili-mild)](https://materialdesignicons.com/icon/chili-mild) [![chili-medium](https://materialdesignicons.com/icon/chili-medium)](https://materialdesignicons.com/icon/chili-medium) [![chili-hot](https://materialdesignicons.com/icon/chili-hot)](https://materialdesignicons.com/icon/chili-hot)
