### ISSUE TITLE
Nearby Hospitals

### ISSUE THREAD

**Issue by premacck** [Templarian/MaterialDesign#2007]
a floating action button type icon which opens mapsActivity and shows nearby hospitals

**Comment by PeterShaggyNoble** [comment]
Would the ` hospital-marker` icon suit your needs?

![](https://materialdesignicons.com/icon/hospital-marker)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @premacck, if the icon above, `hospital` or `hospital-building` don't suit you needs, let us know and we'll revisit this issue.
