### ISSUE TITLE
Discord Icon Variant

### ISSUE THREAD

**Issue by mehcode** [Templarian/MaterialDesign#2009]
Could we have an icon that is just the inner graphic in the Discord icon? I'd like to have a nice circle icon.

![icon-discord](https://cloud.githubusercontent.com/assets/753919/24886996/ac060f02-1e0d-11e7-8315-a0f1c6cb9048.png)

**Comment by Templarian** [comment]
Unfortunately their branding guidelines do not allow this. We suggest using SVG/vector drawables for icons outside the set (but in this case maybe rethink the icons use as it really isn't allowed).

https://discordapp.com/branding

**Comment by mehcode** [comment]
Fair enough.
