### ISSUE TITLE
Air condition thermometar

### ISSUE THREAD

**Issue by mvujica** [Templarian/MaterialDesign#201]
Air condition icon like this:

![thermometer](https://cloud.githubusercontent.com/assets/11364617/6541569/33cab850-c4da-11e4-9f43-84077b66e4fc.png)

- [ ] thermometer-ac

**Comment by Templarian** [comment]
That is going to be a little too much detail, but I'm sure one of the contributors will think of something that fits.

**Comment by CoDEmanX** [comment]
Yeah, it's too much detail...
![ac](https://cloud.githubusercontent.com/assets/1309249/8984900/ca54d7bc-36d4-11e5-88aa-82ce5624ac11.png) https://www.dropbox.com/s/v7h4l3mwrji6lzn/ac.svg?dl=0

But what about something more like this?
![Imgur](http://i.imgur.com/0BVEVFh.jpg)

**Comment by CoDEmanX** [comment]
Is it just me or do the blades look odd?
![ac3](https://cloud.githubusercontent.com/assets/1309249/9073152/ce063d72-3aff-11e5-83b0-40d5e7b8ff5b.png)

**Comment by Templarian** [comment]
I really like that version. Blades look fine'ish. I don't know if it would be worth making them curve back more or not.

**Comment by CoDEmanX** [comment]
Derived from Google's toys icon:
![ac4](https://cloud.githubusercontent.com/assets/1309249/9073744/ebf5144e-3b03-11e5-99fb-a3a0f555c3f6.png) https://www.dropbox.com/s/2jaegn497q1nc8a/ac4.svg?dl=0

And the other one you seen above:
https://www.dropbox.com/s/u539rg0fmu94tlv/ac3.svg?dl=0

**Comment by CoDEmanX** [comment]
Two more tries:
![ac5](https://cloud.githubusercontent.com/assets/1309249/9147208/5bc62576-3d64-11e5-931b-deba7e2e61b9.png) slightly overlapping blades, based on ellipse not circle [Dropbox](https://www.dropbox.com/s/na7d79jw4fcuazs/ac5.svg?dl=0)
![ac6](https://cloud.githubusercontent.com/assets/1309249/9147209/5bc64d12-3d64-11e5-9f52-56fe443480e7.png) derived from Templarian's fan (which btw. reminds me of a ship's propeller) [Dropbox](https://www.dropbox.com/s/klllfdfx5dy8mlv/ac6.svg?dl=0)

As you may have noticed, I mirrored the blades. A fan should rotate clockwise IMO, hence the change.

**Comment by Templarian** [comment]
I kind of like the last version more eventhough it does look like a propeller blade it looks more like a fan.

**Comment by Templarian** [comment]
[![air-conditioner](https://materialdesignicons.com/icon/air-conditioner)](https://materialdesignicons.com/icon/air-conditioner)
