### ISSUE TITLE
Add kumvert as Contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2010]
@kumvert Need some data from you below:

- [x] Name: 
- [x] Twitter: 
- [x] Website (if wanted): 
- [x] Image (if github, just say github): 
- [x] Description:

Your current icons are indexed under the "contributors" account until I get time to switch these over.
https://materialdesignicons.com/contributor/Contributors

**Comment by kumvert** [comment]
Hey!

- Andy Martinez
- @kumvert
- (no website)
- GitHub
- Prospective ux designer

**Comment by Templarian** [comment]
Let me know which need to be assigned over. Right now I just assigned the two I knew of.

Closing the issue, but reopen with any others. 😄 

(Sorry this took so long 😿 )

**Comment by PeterShaggyNoble** [comment]
Icons to be assigned to @kumvert:
- [ ] #1979 - Camera metering
- [ ] #2006 - Chillis

**Comment by Templarian** [comment]
Done. Thanks!
