### ISSUE TITLE
CO2

### ISSUE THREAD

**Issue by 0x4C4A** [Templarian/MaterialDesign#2011]
This would fit in well with the thermometer and humidity icons, since CO2 is another variable IoT smart house devices can measure. Could be something along the lines of a cloud with CO2 written inside it.
I.E.
![image](https://cloud.githubusercontent.com/assets/8605099/24911473/b616eb62-1ed3-11e7-9332-b7156190cda1.png)

**Comment by GreenTurtwig** [comment]
![image](https://cloud.githubusercontent.com/assets/15905797/24917325/b55ee2aa-1ed4-11e7-9787-c2db43fd232b.png)
![image](https://cloud.githubusercontent.com/assets/15905797/24917349/c5ab0cc4-1ed4-11e7-9f20-4d0c0e2e56a2.png)
It's pretty hard fitting text into a cloud, but this should do.
In my opinion though, it would be more readable if the text was standalone, and not in a cloud. :cat2:

**Comment by MrGrigri** [comment]
I too believe that it should stand alone, not in a cloud. And since it's a chemical compound, I don't believe that we need to worry about linguistic differences since The IUPAC (The International Union of Pure and Applied Chemistry) has their main language as English. 

@GreenTurtwig Could you provide a visual without the cloud and make the text a bit bigger?

**Comment by PeterShaggyNoble** [comment]
Also agreed that it should just be "CO<sub>2</sub>" without the cloud.

And @MrGrigri is correct that there is no language conflict, which can be confirmed [here](http://www.ptable.com/).

**Comment by GreenTurtwig** [comment]
Huh, I did upload a plain text version along side the cloud, wonder why it didn't show.
Anyway, here's the plain text version:

![image](https://cloud.githubusercontent.com/assets/15905797/24924476/d9816ee2-1eec-11e7-89e3-9d156e4181f4.png)
![image](https://cloud.githubusercontent.com/assets/15905797/24924498/e7610252-1eec-11e7-94d7-f93d7b3a3a2f.png)
[co2.zip](https://github.com/Templarian/MaterialDesign/files/914323/co2.zip)
@MrGrigri The text on this one is regular height, well apart from the subscript "2". :cat:

**Comment by Templarian** [comment]
[![periodic-table-c02](https://materialdesignicons.com/icon/periodic-table-c02)](https://materialdesignicons.com/icon/periodic-table-c02)

**Comment by 0x4C4A** [comment]
Icon name should be CO2 (cee - oh - two), not C02 (cee - zero - two).

**Comment by Templarian** [comment]
Fixed, watching the new MTK3 on Netflix apparently is a bit distracting. Not even sure how I did that. 😆
