### ISSUE TITLE
mailbox-*

### ISSUE THREAD

**Issue by psfales** [Templarian/MaterialDesign#2012]
I believe the only mailbox icon has the flag up.  How about a similar icon with the flag down

**Comment by GreenTurtwig** [comment]
This could probably be improved upon, but the simple solution would just be this:
![image](https://cloud.githubusercontent.com/assets/15905797/24918294/d3676b70-1ed7-11e7-9d09-ec3bd1ed34f5.png)
![image](https://cloud.githubusercontent.com/assets/15905797/24918300/d9d8c0e4-1ed7-11e7-9d49-c827f9839624.png)
[mailbox-closed.zip](https://github.com/Templarian/MaterialDesign/files/913847/mailbox-closed.zip)

**Comment by CoDEmanX** [comment]
My first thought was "what kind of scale icon is that?". It's a little hard to grasp​ if you don't know what it is supposed to be.

**Comment by GreenTurtwig** [comment]
My thoughts exactly on the normal Google "mailbox" too.

**Comment by PeterShaggyNoble** [comment]
Hmm ... does an outlined flag work any better?

![image](https://cloud.githubusercontent.com/assets/15157491/24968089/02ac7110-1fa4-11e7-941f-5d27bb5c6da8.png) ![image](https://cloud.githubusercontent.com/assets/15157491/24968116/1a35a6e4-1fa4-11e7-90be-3d4f4c5ae2e2.png)

**Comment by MrGrigri** [comment]
I don't like that at all. I believe that @GreenTurtwig did a great job and that in context it'll work.

**Comment by GreenTurtwig** [comment]
@PeterShaggyNoble Yeah, I tried that, as well as having just the lower half outlined. Tried quite a few combinations of things actually, but the simple solution always looked the best which is a shame.

**Comment by kumvert** [comment]
what about an inverted mailbox? I mean flag down essentially means there's no mail, so the mailbox could also be outlined? but honestly @GreenTurtwig has the best iteration I think.

![material design icons 001](https://cloud.githubusercontent.com/assets/26806388/24974405/a0322208-1f87-11e7-9442-2f4ee6928734.jpeg)

**Comment by CoDEmanX** [comment]
Isn't it missing a foot to stand on?

**Comment by GreenTurtwig** [comment]
No, the he stock photography icon doesn't have that.

**Comment by MrGrigri** [comment]
This is one that I came across. I know that we generally don't do perspective, but I believe it's needed for this icon. We have discussed it amongst ourselves and feel this one will work.

![image](https://user-images.githubusercontent.com/4528551/48568298-4aba0200-e8bc-11e8-9920-66fdabf95b47.png) ![image](https://user-images.githubusercontent.com/4528551/48568329-5ad1e180-e8bc-11e8-8808-ace246c2bad0.png)
![image](https://user-images.githubusercontent.com/4528551/48568516-d03db200-e8bc-11e8-8c59-6bcb91f62589.png) ![image](https://user-images.githubusercontent.com/4528551/48568528-d895ed00-e8bc-11e8-93ab-38bac6444be4.png)

---

[mailbox.zip](https://github.com/Templarian/MaterialDesign/files/2586287/mailbox.zip)

**Comment by Templarian** [comment]
No secret that I hate the current mailbox icon. So replaced the existing one and added these new ones.

Great work on these @MrGrigri! 😸

**Comment by Templarian** [comment]
For anyone that finds this, yes they break the perspective rule, but in this scenario I believe it's fine to correctly convey the individual variations in an easy way.

**Comment by PeterShaggyNoble** [comment]
Seeing as the old one was a stock icon should we not include it somewhere?
