### ISSUE TITLE
Icon suggestion: sailing boat

### ISSUE THREAD

**Issue by glaprida** [Templarian/MaterialDesign#2013]

**Comment by Legoracers** [comment]
Yes would love a boat or sailing boat icon.

**Comment by PeterShaggyNoble** [comment]
@Legoracers, would `ferry` suit your requirements?

[![ferry](https://materialdesignicons.com/icon/ferry)](https://materialdesignicons.com/icon/ferry)

**Comment by Legoracers** [comment]
@petershaggynoble Yes it would! Thank didn't see that one.

**Comment by PeterShaggyNoble** [comment]
CLosing in favour of #2365, which includes a contribution.
