### ISSUE TITLE
Icon suggestion: Distance traveled (with car)

### ISSUE THREAD

**Issue by Advil-Robin** [Templarian/MaterialDesign#2014]

**Comment by PeterShaggyNoble** [comment]
Would `highway` or `road-variant` suit your needs? If not could you provide an example of what you're looking for?

[![](https://materialdesignicons.com/icon/highway)](https://materialdesignicons.com/icon/highway) [![](https://materialdesignicons.com/icon/road-variant)](https://materialdesignicons.com/icon/road-variant)

**Comment by Advil-Robin** [comment]
I used the `road-variant` icon, wich looked for me the best solution.

The best icon I could think of was a car with some "dust" behind it or so, I don't know, just something like a car that drives on a road or so, but `road-variant` will fulfill my needs.

**Comment by MrGrigri** [comment]
Would this thread work for you? #1837

**Comment by Advil-Robin** [comment]
Worked. -closed
