### ISSUE TITLE
Clapperboard open

### ISSUE THREAD

**Issue by bernzrdo** [Templarian/MaterialDesign#2015]

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33427905-da96ad54-d5be-11e7-8159-8cd25ef021cc.png)](https://github.com/Templarian/MaterialDesign/files/1517505/movie-open.zip)

**Comment by goyney** [comment]
Removing the Contribution label since no source SVG was provided.

**Comment by goyney** [comment]
[![movie-open](https://materialdesignicons.com/icon/movie-open)](https://materialdesignicons.com/icon/movie-open)[![movie-open-outline](https://materialdesignicons.com/icon/movie-open-outline)](https://materialdesignicons.com/icon/movie-open-outline)
