### ISSUE TITLE
Crosshair icon

### ISSUE THREAD

**Issue by gmikhail** [Templarian/MaterialDesign#2016]

**Comment by PeterShaggyNoble** [comment]
Two options exist for this already:

[![](https://materialdesignicons.com/icon/crosshairs-gps)](https://materialdesignicons.com/icon/crosshairs-gps) [![](https://materialdesignicons.com/icon/target)](https://materialdesignicons.com/icon/target)

**Comment by gmikhail** [comment]
Thank you! Target - that's what I was looking for.
