### ISSUE TITLE
Hand delivering

### ISSUE THREAD

**Issue by waister** [Templarian/MaterialDesign#2018]
Icon with hand delivering money or box.

**Comment by PeterShaggyNoble** [comment]
Closely related to #1799.

**Comment by JamesCoyle** [comment]
Could perhaps use some example imagery. Not sure how this would fit into the 24dp grid.

**Comment by CoDEmanX** [comment]
There is `takeout-dining` in the Google extended set:

![grafik](https://user-images.githubusercontent.com/1309249/62810131-4c3bf200-bafd-11e9-8daf-e2898a4f592f.png)

Could also be something along the line of this:

![grafik](https://user-images.githubusercontent.com/1309249/62810356-fae03280-bafd-11e9-9fe2-1b3487da9e0f.png)

**Comment by goyney** [comment]
While this issue was posted first, a duplicate exists with much more examples and potential additions. I'm going to close this in favor of that issue. Please follow it for updates.

#5678
