### ISSUE TITLE
passenger van

### ISSUE THREAD

**Issue by bearoutthere** [Templarian/MaterialDesign#2019]

**Comment by PeterShaggyNoble** [comment]
Do you have an example of what you're looking for?

**Comment by GreenTurtwig** [comment]
![](https://puu.sh/vz58P.png)
![](https://puu.sh/vz5eY.png)
How about this? I based it around the [VW T4](https://en.wikipedia.org/wiki/Volkswagen_Transporter_(T4))


Also thought I'd go ahead and make a normal van icon while I was at it.
![](https://puu.sh/vz5gf.png)
![](https://puu.sh/vz5h8.png)

**Comment by Templarian** [comment]
I think both could work good. One is more that you would give candy out of and the other is a passenger van. `van-passenger`, `van-utility`.

[![van-utility](https://materialdesignicons.com/icon/van-utility)](https://materialdesignicons.com/icon/van-utility) [![van-passenger](https://materialdesignicons.com/icon/van-passenger)](https://materialdesignicons.com/icon/van-passenger)

(Yes I aliased `van-utility` as `van-candy`)

**Comment by bearoutthere** [comment]
Brilliant.  Thank you.

**Comment by GreenTurtwig** [comment]
No problem, I actually enjoyed this one myself. :cat:
