### ISSUE TITLE
Add bower.json to npm

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#202]
https://github.com/Templarian/MaterialDesign/issues/66#issuecomment-77704564

- [ ] package.json in bower.json
- [ ] bower.json in package.json

**Comment by ritz078** [comment]
Since this is also available on npm , I think there should also be a package.json

**Comment by Templarian** [comment]
You can now `bower install mdi` or `npm install mdi` for `v0.9.72-alpha`.

NPM:
![image](https://cloud.githubusercontent.com/assets/338885/6633873/8acef480-c91d-11e4-9675-4b8216a52223.png)

Bower:
![image](https://cloud.githubusercontent.com/assets/338885/6633889/d26ab07c-c91d-11e4-818d-c67ceb263cc6.png)
