### ISSUE TITLE
Cursor with trail

### ISSUE THREAD

**Issue by sparaoh** [Templarian/MaterialDesign#2020]
Made this for a personal project, but I figured I'd submit it here

[cursor-default-trail.zip](https://github.com/Templarian/MaterialDesign/files/924702/cursor-default-trail.zip)
![asset 3](https://cloud.githubusercontent.com/assets/27653594/25075899/4dcbad02-22ea-11e7-950d-cd4da51a7466.png)

**Comment by sparaoh** [comment]
Here's an updated version that uses the gesture icon as the "trail". Probably makes more sense to call it cursor-gesture or something of the like

[cursor-outline-gesture.zip](https://github.com/Templarian/MaterialDesign/files/931497/cursor-outline-gesture.zip)
![asset 1](https://cloud.githubusercontent.com/assets/27653594/25159490/20acbf88-247e-11e7-80f4-fc517bf84308.png)

**Comment by CoDEmanX** [comment]
![image](https://user-images.githubusercontent.com/1309249/38770856-839db9c8-4019-11e8-94a7-95deac72b302.png)

The gesture stroke looks kinda irregular at larger sizes. Is it necessary for legibility to do that?

**Comment by Templarian** [comment]
Maybe as `cursor-default-gesture` ?

**Comment by goyney** [comment]
The cursor itself looks like it doesn't have a consistent stroke either.

**Comment by goyney** [comment]
[![cursor-default-gesture](https://materialdesignicons.com/icon/cursor-default-gesture)](https://materialdesignicons.com/icon/cursor-default-gesture)[![cursor-default-gesture-outline](https://materialdesignicons.com/icon/cursor-default-gesture-outline)](https://materialdesignicons.com/icon/cursor-default-gesture-outline)
