### ISSUE TITLE
Icon for zip file

### ISSUE THREAD

**Issue by chinmay-amuratech** [Templarian/MaterialDesign#2022]

**Comment by JapanYoshi** [comment]
How do you miss [this](https://materialdesignicons.com/icon/zip-box)?!

**Comment by chinmay-amuratech** [comment]
No. Not this one.
I would rather go with the icon of windows zip file or ubuntu's zip file.
Never mind. For now I'm using the one you shared. Thanks. :+1:

**Comment by PeterShaggyNoble** [comment]
Closing as a duplicate of #1288.
