### ISSUE TITLE
BBC iPlayer Icon

### ISSUE THREAD

**Issue by wizbowes** [Templarian/MaterialDesign#2023]
Just the i and play - like the white part [on this version:](https://cdn.dribbble.com/users/9173/screenshots/1792010/iplayer_icon_1x.jpg)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @wizbowes. Unfortunately, this icon would be beyond the current scope of this project. However, it may be revisted in the future should a dedicated set of brand icons ever be released.

**Comment by wizbowes** [comment]
Hi Peter,

So I noticed that there were both Netflix and Amazon icons already as part of the project.  For future reference, can I ask why iPlayer would be beyond the scope of the project but these are not?

**Comment by Templarian** [comment]
@wizbowes Most brand icons are for social media. Netflix and Amazon are included due to the popularity and use on online. iPlayer might be too niche for this reason.

We recommend using an inline vector for icons that are not included (SVG or vector drawable).

**Comment by wizbowes** [comment]
Thanks Peter.

iPlayer is on course for over 4 billion plays this year.  Although it has a limited geographical availability, I'm not sure it classes as niche.  Whilst I wouldn't try to insist anybody made this icon I still don't really understand why the request would be closed rather than just leaving it open to see if somebody wanted to help.

That said, although disappointed, I'd like to thank you for your work on this great resource.

**Comment by Templarian** [comment]
@wizbowes We look at the use cases for people using the icons also. iPlayer even with it's geographical niche, it's not heavily used on 3rd party websites that may include this set of icons.

It would be like us including crackle, or similar video platform's logo. Sure it has a large user base, but it's not externally linked heavily enough to garner a dedicated icon.

In the future we may create a brand icon pack that includes these brand icons (it's been discussed as a side project after the alpha numeric set is complete).
