### ISSUE TITLE
Some icons from Google's collection seem to be missing

### ISSUE THREAD

**Issue by 0x4C4A** [Templarian/MaterialDesign#2025]
For example:
- [Euro](https://material.io/icons/?q=euro#ic_euro_symbol)
- [Multiline-chart](https://material.io/icons/?q=euro#ic_multiline_chart)
- [Pie-chart](https://material.io/icons/?q=euro#ic_pie_chart)

The multiline-chart was added with 2.2.0 (that's 9. Feb 2016), however the same update seems to have also contained delete-forever. Which is in fact present in MDI. What's going on here?

**Comment by PeterShaggyNoble** [comment]
`currency-eur` and `chart-pie` exist already, although the latter could probably be updated to match Google's (see #1937). Leaving this open as a request for `chart-multiline`. Not all stock icons have been (nor nescessarily will be) added here; if you come across any more you would like to see included then please open an issue for them, as per the following [comment](https://github.com/Templarian/MaterialDesign/issues/1797#issuecomment-274933826) from @Templarian:

> Remember this project has been around longer than the official one 😄. We add icons and so does Google so there is always some not synced. We just sync in the ones the community finds useful rather than all of them. Continue to open issues for icons you need that are missing.

[![](https://materialdesignicons.com/icon/currency-eur)](https://materialdesignicons.com/icon/currency-eur) [![](https://materialdesignicons.com/icon/chart-pie)](https://materialdesignicons.com/icon/chart-pie)

**Comment by 0x4C4A** [comment]
Oh, I see, thank you!
I'd like to request the addition of [show-chart](https://material.io/icons/#ic_show_chart) too then.

I think it'd make sense to alias the icons you listed to the names Google assigned to them, since people might miss them, just like I did.

**Comment by Templarian** [comment]
[![chart-line-variant](https://materialdesignicons.com/icon/chart-line-variant)](https://materialdesignicons.com/icon/chart-line-variant)
