### ISSUE TITLE
Icon update: folder-move

### ISSUE THREAD

**Issue by frlinw** [Templarian/MaterialDesign#2026]
folder-move icon is the only one (from folder icons collection) with inside item stick on the left
 
![image](https://cloud.githubusercontent.com/assets/11896237/25129730/966d19e6-243f-11e7-9e3a-8c8f1dfcd0d3.png)

Updated icon from google drive :
![image](https://cloud.githubusercontent.com/assets/11896237/25129617/1a8398e6-243f-11e7-93e6-1e45a5c7ec51.png)

**Comment by Templarian** [comment]
[![folder-move](https://materialdesignicons.com/icon/folder-move)](https://materialdesignicons.com/icon/folder-move)

Thanks @frlinw!
