### ISSUE TITLE
invalid package.json, main should not reference an html file

### ISSUE THREAD

**Issue by timfish** [Templarian/MaterialDesign#2027]
Currently `"main": "preview.html"` [which is not strictly valid](https://docs.npmjs.com/files/package.json#main). Any libraries which traverse `package.json` and `main` to try and trace JavaScript paths will fail.

**Comment by Templarian** [comment]
Yea, we'll change that before the `v2.0`, might have been okay many versions ago. Looks like that has been that way since the start of the project over 2 years ago.

**Comment by timfish** [comment]
Thanks, 

Reported solely because [aurelia-cli](https://github.com/aurelia/cli) fails importing `mdi` due to this.

**Comment by Templarian** [comment]
@timfish Until we have this in the next release, might want to see if they can more gracefully handle this (or submit them a PR). We are not expecting to release `2.0` for at least 2 months.

**Comment by Templarian** [comment]
This has been removed for the next release. We're working on more official components for `react`/`angular` shortly that should integrate nicely for developers.

The release should go out shortly.
