### ISSUE TITLE
Crossed hammers

### ISSUE THREAD

**Issue by snuuve** [Templarian/MaterialDesign#2028]
Crossed hammers like icon in tachographs (meaning work).
![hammers](https://cloud.githubusercontent.com/assets/9519759/25179517/87d107dc-250a-11e7-957c-2cd1a1d915e7.png)

**Comment by goyney** [comment]
Would this solve your use case?

![image](https://user-images.githubusercontent.com/1015040/72487796-27028c80-37dd-11ea-8720-cc5c3c981c6d.png)
[hammer-wrench.svg.zip](https://github.com/Templarian/MaterialDesign/files/4068997/hammer-wrench.svg.zip)

**Comment by goyney** [comment]
[![hammer-wrench](https://materialdesignicons.com/icon/hammer-wrench)](https://materialdesignicons.com/icon/hammer-wrench)[![hammer-screwdriver](https://materialdesignicons.com/icon/hammer-screwdriver)](https://materialdesignicons.com/icon/hammer-screwdriver)
