### ISSUE TITLE
Icon suggestion: Dailymotion

### ISSUE THREAD

**Issue by LouisBellinger** [Templarian/MaterialDesign#2029]
Hello

That would be nice to have a dailymotion icon (youtube's already there so, might seems logical to add Dailymotion)

Here are the brand assets: http://press.dailymotion.com/?page_id=346

**Comment by nkspappas** [comment]
Because github does not allow svg file in comments I have just uploaded 3 alternatives for a dailymotion icon on the following link: 
> https://www.dropbox.com/sh/62bmwk127cj8r0h/AAD_kJFKZM3ck9cr7uVhkbg1a?dl=0
@Templarian if it any of them passes your standards, feel free to add it on the materialdesignicons collection. :bowtie:

**Comment by MrGrigri** [comment]
This will not work because of their misuse standards. We cannot guarantee that it will always be a white letter with a blue background.

**Comment by nkspappas** [comment]
@MrGrigri true, I didn't check their guidelines...

**Comment by MrGrigri** [comment]
I'm going to close this issue. @LouisBellinger, if they ever change their branding guidelines, then we could reopen this issue.
