### ISSUE TITLE
Cloud storage icons

### ISSUE THREAD

**Issue by ashughes** [Templarian/MaterialDesign#203]
- [x] Google Drive
- [x] Dropbox
- [x] Box
- [x] OneDrive
- [ ] SugarSync
- [x] Amazon Cloud Drive
- [ ] ~~Bitcasa~~
- [ ] ~~Copy~~
- [ ] CrashPlan
- [ ] Backblaze
- [ ] OwnCloud

Others?

**Comment by Templarian** [comment]
I'm going to flag this as high priority because most applications will need these in some capacity.

**Comment by Templarian** [comment]
I checked off the ones I added to the list. Those are the ones that I felted needed to be in the next release.

I should note, that most of the companies have strict use clauses on their logos/brands. So hopefully people read those before using these.

**Comment by Templarian** [comment]
The remaining icons will make it in the next release. `v0.9.72-alpha` now contains 5 storage icons currently checked off.

**Comment by JamesCoyle** [comment]
Are we still adding the rest of these?

**Comment by GreenTurtwig** [comment]
I'll be doing OwnCloud soon (mainly because I use it :-P)

**Comment by goyney** [comment]
None of the existing icons are in the [Simple Icons](https://simpleicons.org/) library, just FYI.

- SugarSync's icon is a detailed bird that I don't know how we'd translate to a single path.
- Bitcasa [was shut down in 2017](https://en.wikipedia.org/wiki/Bitcasa), so we don't need to add it.
- Copy [was discontinued in 2016](https://copy.com/), so we don't need to add it.
- CrashPlan: 
![image](https://user-images.githubusercontent.com/1015040/48863617-f1f4d880-ed97-11e8-936b-72b0c1f6e9ba.png)
[crashplan.zip](https://github.com/Templarian/MaterialDesign/files/2605468/crashplan.zip)
- Backblaze:
![image](https://user-images.githubusercontent.com/1015040/48863734-5c0d7d80-ed98-11e8-925a-5afc742b8658.png)
[backblaze.zip](https://github.com/Templarian/MaterialDesign/files/2605472/backblaze.zip)
- Owncloud:
![image](https://user-images.githubusercontent.com/1015040/48864208-dab6ea80-ed99-11e8-94d7-64830ededb42.png)
[owncloud.zip](https://github.com/Templarian/MaterialDesign/files/2605496/owncloud.zip)

**Comment by PeterShaggyNoble** [comment]
I'd argue that the remaining ones are too niche for inclusion.

**Comment by Templarian** [comment]
Agreed, the remaining ones are going to be too niche for us to add.
