### ISSUE TITLE
Icon suggestion: Currency sign

### ISSUE THREAD

**Issue by adrogon** [Templarian/MaterialDesign#2030]
Some currencies do not come with a symbol of their own and use either some letters or the ISO 4217 code.

For these, the default ["currency sign"](https://en.wikipedia.org/wiki/Currency_sign_(typography)) can be used: ¤

One advantage is that its typography is pretty much Material Design already.

I would suggest adding it to the library as `currency`.

**Comment by MrGrigri** [comment]
Like this:

![currency-sign](https://cloud.githubusercontent.com/assets/4528551/25186998/0fd0aa10-24df-11e7-8943-24f4bb032e7f.png)

[currency-sign.zip](https://github.com/Templarian/MaterialDesign/files/935408/currency-sign.zip)

**Comment by PeterShaggyNoble** [comment]
Suggest aliasing this as `scarab`.

**Comment by MrGrigri** [comment]
I would go with `currency-scarab`

**Comment by Templarian** [comment]
[![currency-sign](https://materialdesignicons.com/icon/currency-sign)](https://materialdesignicons.com/icon/currency-sign)
