### ISSUE TITLE
Icon suggestion: Home Assistant logo

### ISSUE THREAD

**Issue by redskinwashingtons** [Templarian/MaterialDesign#2031]
[See top left here](https://home-assistant.io). Obviously with a lot less actual lines. The home icon kind of works but it's just not _it_.

**Comment by Templarian** [comment]
Someone go chat with their community to design something up that is _approved_. Right now there is too much detail in their logo.

**Comment by redskinwashingtons** [comment]
I mean, I'll take the shape of the house, and like two lines and two dots. Or do you mean that that would be not allowed?

**Comment by Templarian** [comment]
@redskinwashingtons Check with them if they are okay with modification of their logo. Most brands are not okay with this (and why we can't include their logo). Let them know the reason and your suggestion.

**Comment by redskinwashingtons** [comment]
Check this out: https://home-assistant.io/blog/2015/03/08/new-logo/

Would the far right one work?

**Comment by robbiet480** [comment]
Might want to check out our [assets repo](https://github.com/home-assistant/home-assistant-assets).

**Comment by balloob** [comment]
Source of our small logo is here: https://github.com/home-assistant/home-assistant-assets/blob/master/logo_v2-small.psd

**Comment by Templarian** [comment]
Next release isn't for a while, so gives a bit of time to review the version I've added. I tweaked the provided logo a lot to make it look slightly nicer at 24x24 for those viewing on non-HDPI displays.

[![home-assistant](https://materialdesignicons.com/icon/home-assistant)](https://materialdesignicons.com/icon/home-assistant)
