### ISSUE TITLE
Icon suggestion: Door, Window

### ISSUE THREAD

**Issue by redskinwashingtons** [Templarian/MaterialDesign#2032]

**Comment by PeterShaggyNoble** [comment]
Door is a dupe of #1822 and 2 window icons already exist:

[![window-closed](https://materialdesignicons.com/icon/window-closed)](https://materialdesignicons.com/icon/window-closed) [![window-open](https://materialdesignicons.com/icon/window-open)](https://materialdesignicons.com/icon/window-open)
