### ISSUE TITLE
Icon suggestion: Minimize , Maximize, Restore

### ISSUE THREAD

**Issue by essuraj** [Templarian/MaterialDesign#2033]

**Comment by PeterShaggyNoble** [comment]
These all exist already and are easily found by searching for the relevant terms:

[![window-maximize](https://materialdesignicons.com/icon/window-maximize)](https://materialdesignicons.com/icon/window-maximize) [![window-minimize](https://materialdesignicons.com/icon/window-minimize)](https://materialdesignicons.com/icon/window-minimize) [![window-restore](https://materialdesignicons.com/icon/window-restore)](https://materialdesignicons.com/icon/window-restore)
