### ISSUE TITLE
Icon suggestion: GameWisp

### ISSUE THREAD

**Issue by Mhyrtas** [Templarian/MaterialDesign#2035]
https://d32y8axfzs6sv8.cloudfront.net/2.4.2017.4.13.1R/img/gw_logo_gray.png

**Comment by PeterShaggyNoble** [comment]
Unfortunately, this would be beyond the current scope of this project but it may be revisited in the future if a dedicated pack of brand icons is ever released.

**Comment by Mhyrtas** [comment]
I thought that because it was somehow related to Twitch and that Twitch icon is already there. :( I guess Im gonna have to wait or find a workaround. Thank you!
