### ISSUE TITLE
Sticky notes icon!

### ISSUE THREAD

**Issue by JunedS** [Templarian/MaterialDesign#2038]
Hi, This is an amazing project which provides huge list of material icons and for free. Keep up the good work.
Can we have sticky icon as I don't see the same in the list. I am sure this icon will be useful!

**Comment by CoDEmanX** [comment]
This looks like a sticky note to me:

https://materialdesignicons.com/icon/note-outline

**Comment by Templarian** [comment]
Yep, Going to close. Note icons should suffice for this.

**Comment by JunedS** [comment]
Yes I am currently using this one. But IMHO shouldnt a sticky note icon look like this?

[http://www.clipartbest.com/cliparts/jix/oeX/jixoeXz7T.png](url)

**Comment by Templarian** [comment]
@JunedS Due to the size constraints we generally got for the more minimal design.
