### ISSUE TITLE
network settings

### ISSUE THREAD

**Issue by lechuckcaptain** [Templarian/MaterialDesign#204]
- [ ] STATIC proxy / settings
- [ ] PAC proxy / settings
- [x] VPN / settings

**Comment by Templarian** [comment]
Do you have examples for these? VPN I have an idea, but not the other two.

**Comment by lechuckcaptain** [comment]
You are right, in fact it's difficult to find guidelines for this sort of settings. 

Usually for a STATIC proxy settings you can find something like that (similar to the server-network icon):

* <img src="http://www.softwarecrew.com/wp-content/uploads/2014/01/ChrisPCAnonymousProxy200-175.png" height="50" />
* <img src="http://www.vpngids.nl/wp-content/uploads/proxy.png" height="50" />
* <img src="http://connectivity.opentext.com/common/images/articles/server_network.png" height="50" />

For a PAC proxy settings I would suggest to add to the STATIC proxy settings icon some other visual information, like a URL, or a Script, or a generic text document.

**Comment by CoDEmanX** [comment]
Google's [ic_settings_ethernet](http://www.google.com/design/icons/#ic_settings_ethernet)
Google's [ic_vpn_lock](http://www.google.com/design/icons/#ic_vpn_lock)

Microsoft's VPN icon: 
![microsoft_vpn](https://cloud.githubusercontent.com/assets/1309249/8761404/a0f908da-2d50-11e5-9e96-b9cb82587b05.png)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/vpn

Other two icons need to be added part of the stock still.

**Comment by goyney** [comment]
From what I can see, there really is no fundamental different between and Static proxy and a Auto-config proxy, except for how they are configured. In either case, there does not seem to be a set standard on how a proxy is identified visually, though I see many icons with arrows going many ways.

I believe `arrow-decision` would satisfy the use case for a proxy.

@lechuckcaptain Can you chime in on whether or not that would solve your use case?

**Comment by lechuckcaptain** [comment]
> From what I can see, there really is no fundamental different between and Static proxy and a Auto-config proxy, except for how they are configured. In either case, there does not seem to be a set standard on how a proxy is identified visually, though I see many icons with arrows going many ways.
> 
> I believe `arrow-decision` would satisfy the use case for a proxy.
> ![image](https://user-images.githubusercontent.com/1015040/48816925-1efea800-ed12-11e8-89ce-a737c790dcc5.png)
> 
> @lechuckcaptain Can you chime in on whether or not that would solve your use case?

Looks fine to me!

**Comment by goyney** [comment]
Cool, we'll add an alias of `proxy` to `arrow-decision` so it is more easily findable moving forward.

**Comment by CoDEmanX** [comment]
I that case, `arrow-decision-auto` can be used for auto-proxy.

**Comment by goyney** [comment]
@CoDEmanX Good catch, aliases added.
