### ISSUE TITLE
phonelink-ring 

### ISSUE THREAD

**Issue by ashleydzick** [Templarian/MaterialDesign#2040]
From Material Design: https://material.io/icons/#ic_phonelink_ring

![ic_phonelink_ring_black_24dp_2x](https://cloud.githubusercontent.com/assets/5489882/25347894/0823b0f8-28e2-11e7-8f92-cce325083d05.png)

**Comment by goyney** [comment]
This icon is already included in the set as `cellphone-sound`.

[![cellphone-sound](https://materialdesignicons.com/icon/cellphone-sound)](https://materialdesignicons.com/icon/cellphone-sound)
