### ISSUE TITLE
New Google Wallet Icon

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2041]
A few years back, Google updated the Google Wallet icon to sharpen the edges. The one we have here is still the old rounded version. 

![new_gw](https://cloud.githubusercontent.com/assets/18021678/25358010/e3e0e982-290d-11e7-9df9-322bf89a3040.png)

![quantum_ic_wallet_product_white_24](https://cloud.githubusercontent.com/assets/18021678/25358078/2b0cf148-290e-11e7-8cd6-a7b34070bf4b.png)

**Comment by Templarian** [comment]
Do you by chance have the SVG for this or a link to it?

**Comment by k5cents** [comment]
@Templarian I do not. I pulled that grey icon from the Google Wallet apk. The file name is "quantum_ic_wallet_product_white_24" that's all I know.

I don't know if it'd be better to use that version (solid) or put spaces between the lines _a la_ the google-wallet icon we have now

**Comment by Templarian** [comment]
NP, we can trace it or find it online then. Was just checking if there was a vector.

**Comment by Templarian** [comment]
[![google-wallet](https://materialdesignicons.com/icon/google-wallet)](https://materialdesignicons.com/icon/google-wallet)
