### ISSUE TITLE
WordPress Icon is very different from official logos

### ISSUE THREAD

**Issue by nickmomrik** [Templarian/MaterialDesign#2042]
The proportions in the WordPress icon are all wrong. Can this get updated to match the official logo? Official logos can be found at https://wordpress.org/about/logos/

**Comment by Templarian** [comment]
We can look into that, might be a legacy version of their logo also. Not sure it's probably been in the pack for 2 years now.

**Comment by Templarian** [comment]
Yea, they updated their logo a while back. Good catch noticing that.

[![wordpress](https://materialdesignicons.com/icon/wordpress)](https://materialdesignicons.com/icon/wordpress)
