### ISSUE TITLE
Folder with attachments

### ISSUE THREAD

**Issue by paslavsky** [Templarian/MaterialDesign#2043]
Hi,

I'm looking icon for a folder with attachments, something like this: 
<img width="141" alt="folder_attachment" src="https://cloud.githubusercontent.com/assets/6594920/25362621/c4186008-295d-11e7-9e58-bd5f67f91072.png">

**Comment by MrGrigri** [comment]
From a UX perspective, I don't quite understand why you'd need this. All folders have attachments or something inside them. I would suggest using `folder-text` or `folder-text-outline` for folders that have content. Closing this for now. If you have any suggestions or further reasoning, let us know.
