### ISSUE TITLE
Icon Request: Philips Hue LED Light Strip

### ISSUE THREAD

**Issue by eximo84** [Templarian/MaterialDesign#2044]
Icon like this:

https://www.howtogeek.com/wp-content/uploads/2016/04/IMG_1803_stomped.jpg

**Comment by PeterShaggyNoble** [comment]
This seems *very* specific to me.

**Comment by eximo84** [comment]
Does it make it less "specific" if you say "generic LED strip" icon?  The set already has various bulbs and a sidelight and ceiling light icon.

**Comment by Templarian** [comment]
Nah, it's fine, I think Peter just meant it was a very specific icon. But that's fine, LED light strips are becoming a lot more popular (my new kitchen once it's remodeled will have them).

**Comment by JamesCoyle** [comment]
Would be useful for home automation purposes and things like PC system info which often have lighting now.

**Comment by metbril** [comment]
I second an icon for 'LED strip' (or even more generic: 'ribbon').

**Comment by GreenTurtwig** [comment]
Well, here we go :cat2::
![](https://puu.sh/woDvK.png)
![](https://puu.sh/woDwU.png)
[led-strip.zip](https://github.com/Templarian/MaterialDesign/files/1086002/led-strip.zip)

**Comment by Templarian** [comment]
[![led-strip](https://materialdesignicons.com/icon/led-strip)](https://materialdesignicons.com/icon/led-strip)
