### ISSUE TITLE
Icon lockers

### ISSUE THREAD

**Issue by cyndymt** [Templarian/MaterialDesign#2045]
Hi, is possible use this icon "lockers", attached he SVG, I hope it works.
![lockers](https://cloud.githubusercontent.com/assets/28006816/25386760/d56df7be-299e-11e7-87e3-b8a73689f168.jpg)
[lockers.svg.zip](https://github.com/Templarian/MaterialDesign/files/955113/lockers.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Can you try one with a single locker? With the 3, it's a little too much detail.

**Comment by cyndymt** [comment]
Attached two options with two and one lockers
[two-lockers.svg.zip](https://github.com/Templarian/MaterialDesign/files/958339/two-lockers.svg.zip)
[one-locker.svg.zip](https://github.com/Templarian/MaterialDesign/files/958340/one-locker.svg.zip)

**Comment by cyndymt** [comment]
Files work?

**Comment by Templarian** [comment]
Probably. Will get them synced in shortly. Busy at work before the MS Build conference all next week. 😄

**Comment by cyndymt** [comment]
Aaah ok
Thanks!

**Comment by Templarian** [comment]
Redesigned, and added. Thanks!

[![locker](https://materialdesignicons.com/icon/locker)](https://materialdesignicons.com/icon/locker) [![locker-multiple](https://materialdesignicons.com/icon/locker-multiple)](https://materialdesignicons.com/icon/locker-multiple)

**Comment by cyndymt** [comment]
Great thank you!

**Comment by cyndymt** [comment]
Hi, i putted the icon in mi site, but not displayed :(

**Comment by PeterShaggyNoble** [comment]
@cyndymt, it won't be added to the webfont until the next release.

**Comment by cyndymt** [comment]
Ok, and when would that be?

2017-05-04 11:21 GMT-03:00 Peter Noble <notifications@github.com>:

**Comment by Templarian** [comment]
Probably a month. We did the latest release pretty recently. Next release is `2.0.x` (so 2000 icons).

**Comment by cyndymt** [comment]
Ok, thanks!
Regards

2017-05-04 11:39 GMT-03:00 Austin Andrews <notifications@github.com>:

**Comment by cyndymt** [comment]
Hi, sorry for asking again, but when added de icon "locker", I need to use it  :´(

**Comment by Templarian** [comment]
You can always use inline vectors until it's added. I'll be doing a release shortly. I don't think I have any high priority icons holding it up.

**Comment by cyndymt** [comment]
I'm trying to add it in my site, but it's not displayed.

**Comment by shroudedcode** [comment]
@cyndymt Obviously it's not being displayed ... it's not yet released, what do you expect? @Templarian said you could use inline vectors if you really needed the icons.  Just download and embed (or directly include) the SVG file of the icon into your code.

**Comment by cyndymt** [comment]
OK, thanks for the explanation; the problem is that I'm using WordPress, where the process of getting an online icon from materialdesignicons.com is already implemented.

**Comment by shroudedcode** [comment]
@cyndymt Then you'll have to wait until the new version gets released.

**Comment by cyndymt** [comment]
Ok, thanks!

**Comment by cyndymt** [comment]
@Templarian sorry for asking again and again, but when the new version will ready?

**Comment by Templarian** [comment]
@cyndymt Soon™ Need to fix some issues with the build process after the server migration.

**Comment by cyndymt** [comment]
@Templarian Thanks!

**Comment by cyndymt** [comment]
@Templarian I'm still waiting :(

**Comment by JamesCoyle** [comment]
@cyndymt They are included in the latest version which is available now.  

Pestering us doesn't make us want to get an icon added any faster. The contributors here are all voluntary and maintain this project in our spare time and we have absolutely no obligation to anyone to create and upload any of these icons.

**Comment by cyndymt** [comment]
@JamesCoyle if you think that asking once a month for a few months is pestering, ok, i'm pestering. I know that you have no obligation whatsoever, but I would like you to keep your word.
Thank you for your kind answer.
