### ISSUE TITLE
thermometer-lines alternate

### ISSUE THREAD

**Issue by skimj** [Templarian/MaterialDesign#2046]
Would you consider including an alternate thermomer-lines icon? Here is an svg of my concept: [thermometer-lines-simple.zip](https://github.com/Templarian/MaterialDesign/files/955989/thermometer-lines-simple.zip)

The most common thermometer symbol that I see is similar to thermometer-lines but with the bulb portion "filled" as opposed to an outline and then with three graduation lines on one side only and above the bulb.

For example, the automotive dash symbol: google image search: [water temperature symbol](https://www.google.com/search?q=water+temperature+symbol&tbm=isch&tbo=u&source=univ&sa=X). The wavy lines specifically indicate "water" and the graduation marks are connected to the thermometer. Also, google image search: [thermometer symbol](https://www.google.com/search?q=thermometer+symbol&tbm=isch&tbo=u&source=univ&sa=X)

**Comment by kumvert** [comment]
something like this?

![thermometer-lines-alternate 012](https://cloud.githubusercontent.com/assets/26806388/25402926/0ac73b0c-29c0-11e7-9f03-3b040f33e4e8.jpeg)

**Comment by skimj** [comment]
Yes, but I would suggest dropping the very bottom measurement mark.

**Comment by JamesCoyle** [comment]
I'm gonna close this out. I don't really feel it is worth adding such a similar variant to the ones we already have.
