### ISSUE TITLE
Thought bubble

### ISSUE THREAD

**Issue by karlinnolabs** [Templarian/MaterialDesign#2048]
No icon for thought bubble in here.

**Comment by Templarian** [comment]
[![thought-bubble](https://materialdesignicons.com/icon/thought-bubble)](https://materialdesignicons.com/icon/thought-bubble)

Not sure if I like this design, might tweak it later. Leaving issue the open.

**Comment by karlinnolabs** [comment]
How about this?

[thought-bubble.svg.zip](https://github.com/Templarian/MaterialDesign/files/960975/thought-bubble.svg.zip)

**Comment by karlinnolabs** [comment]
![thought-bubble](https://cloud.githubusercontent.com/assets/19834601/25475258/12f397f2-2b2e-11e7-91d4-1def5fce32b1.png)
PNG for preview

**Comment by Templarian** [comment]
[![thought-bubble-outline](https://materialdesignicons.com/icon/thought-bubble-outline)](https://materialdesignicons.com/icon/thought-bubble-outline)

Trying to make it still look "bubble'y" at 24x24 size.

**Comment by Templarian** [comment]
Closing out this issue. We may come back to it later on if other designs ideas come up.

**Comment by JapanYoshi** [comment]
That latest idea looks nice though.
