### ISSUE TITLE
Theme color

### ISSUE THREAD

**Issue by christian160984** [Templarian/MaterialDesign#205]
I don't know if there is an icon for the Theme Color. If it does not exist, thank you.

**Comment by Templarian** [comment]
Do you have an example? I think the water icon might be best for this use.

**Comment by christian160984** [comment]
I had thought use invert-colors icon or a personalized icon with a palette

**Comment by GreenTurtwig** [comment]
Closing this as `palette` is often used to represent changing themes.
[![](https://materialdesignicons.com/icon/palette)](https://materialdesignicons.com/icon/palette)

**Comment by PeterShaggyNoble** [comment]
Some other options:
- `brush`
- `format-color-fill` (w/ `color-helper`)
- `format-paint`
- `invert-colors`
- `spray`

There's also `shape-outline`, which Google call `theme`.
