### ISSUE TITLE
Government and Politician Icon

### ISSUE THREAD

**Issue by tanushree57** [Templarian/MaterialDesign#2050]
Government related icons (maybe parliament house) and something representing a politician

**Comment by adrogon** [comment]
Isn't `bank` already a good match for parliament?

**Comment by PeterShaggyNoble** [comment]
Yeah, `bank`  would work well for government/parliament.

[![bank](https://materialdesignicons.com/icon/bank)](https://materialdesignicons.com/icon/bank)

For politician, maybe `account` with a tie/suit or a handshake icon.

**Comment by tanushree57** [comment]
@adrogon  yes bank would work for parliament.
@PeterShaggyNoble yes I think an account icon with a tie/suit would be really nice. It could also double up as a businessman

**Comment by PeterShaggyNoble** [comment]
That would be covered by #1356, so I'm going to close this issue out in favour of that one.

**Comment by JapanYoshi** [comment]
Just as a reference, Kurzgesagt represents “law” with the § sign inside a scroll.
