### ISSUE TITLE
Usable font for design software

### ISSUE THREAD

**Issue by RaphyRaph** [Templarian/MaterialDesign#2053]
Is there a version of the font that can be used in design software like Sketch? One that doesn't use unicode characters to render the glyphs? As you can see below, the Material Design glyph font from Google is readable, and is easier to use. 

![artboard 2](https://cloud.githubusercontent.com/assets/3810802/25527045/875ffde8-2c0e-11e7-8962-d7b3c58ac582.png)

**Comment by Templarian** [comment]
https://materialdesignicons.com/design (has support of iconjar, Mac only).
https://github.com/Templarian/MaterialDesign-SVG (optimized SVG files same as above).

We have no plans to support ligatures.

**Comment by Waleedov** [comment]
The design link is down, could you please reupload?
https://cdn.materialdesignicons.com/4.4.95/MaterialDesignIconsDesign.zip
