### ISSUE TITLE
Caravan

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2054]
Realised there is no caravan icon, so went ahead and used @MrGrigri 's trailer as a base.

![](https://puu.sh/vz5v9.png)
![](https://puu.sh/vz5wA.png)
[caravan.zip](https://github.com/Templarian/MaterialDesign/files/965025/caravan.zip)

**Comment by Templarian** [comment]
[![caravan](https://materialdesignicons.com/icon/caravan)](https://materialdesignicons.com/icon/caravan)

Thanks!
