### ISSUE TITLE
Clear

### ISSUE THREAD

**Issue by ginlime** [Templarian/MaterialDesign#2055]
Simply show clearing something, e.g. clear forms.
![clear_small](https://cloud.githubusercontent.com/assets/3253790/25564094/eb8586b6-2de5-11e7-8f37-1a68a704b1b4.png)
![clear](https://cloud.githubusercontent.com/assets/3253790/25564093/e0ce7516-2de5-11e7-96b9-362af0f67249.png)  
[clear.zip](https://github.com/Templarian/MaterialDesign/files/966705/clear.zip)

**Comment by GreenTurtwig** [comment]
Thinking this should be called `vanish` rather than clear.

**Comment by Templarian** [comment]
Yea, agreed. I'm not sure `clear` is the right name for this, but it is a needed icon.

**Comment by ginlime** [comment]
Oh, indeed.
I agree with your naming!

**Comment by Templarian** [comment]
[![vanish](https://materialdesignicons.com/icon/vanish)](https://materialdesignicons.com/icon/vanish)

Let me know when you hit 5 icons and I'll assign it over to a contributor account.

Thanks!
