### ISSUE TITLE
Different professions

### ISSUE THREAD

**Issue by naco-siren** [Templarian/MaterialDesign#2056]

**Comment by Templarian** [comment]
@naco-siren Do you have a list or example image of what you mean? Could be difficult to do with the size restriction.

**Comment by naco-siren** [comment]
<img width="267" alt="screen shot 2017-04-30 at 11 41 30 pm" src="https://cloud.githubusercontent.com/assets/8222638/25572230/c0523d4a-2dfe-11e7-90ac-54908a24c723.png">

**Comment by MrGrigri** [comment]
I believe that this will be very difficult given our size and mono color constraints.

**Comment by JamesCoyle** [comment]
#2104
