### ISSUE TITLE
Paper clip diagonal

### ISSUE THREAD

**Issue by 2hamed** [Templarian/MaterialDesign#2057]
Could there be a diagonal paper clip icon?

**Comment by 2hamed** [comment]
Something like this, but more material type.
![attach-paperclip-diagonal-symbol_318-61913](https://cloud.githubusercontent.com/assets/537522/25607372/79d2ce74-2f2b-11e7-8695-6f4b4f920d30.jpg)

**Comment by Templarian** [comment]
There are 2 paperclip icons already (`attachment` being the other). I would suggest just rotating it. If you're using the webfont `mdi-rotate-45`.

Might be a tad overkill including rotated variations.
