### ISSUE TITLE
Forklift icon

### ISSUE THREAD

**Issue by ToX82** [Templarian/MaterialDesign#2058]
I think that a forklift icon could be useful. Something like those icons, but in a material design :)

https://www.google.com/search?q=forklift+icon

**Comment by GreenTurtwig** [comment]
This should be good enough, but IMO I don't like it that much:
![puush-linux 2017-05-03 at 09 43 43](https://cloud.githubusercontent.com/assets/15905797/25653784/53383c20-2fe6-11e7-863c-c0a7157a8f98.png)
![puush-linux 2017-05-03 at 09 52 22](https://cloud.githubusercontent.com/assets/15905797/25653787/560adde0-2fe6-11e7-8283-ca28575c160b.png)
[forklift-truck.zip](https://github.com/Templarian/MaterialDesign/files/972840/forklift-truck.zip)
I've been doing a few vehicle icons lately...

**Comment by Templarian** [comment]
[![forklift](https://materialdesignicons.com/icon/forklift)](https://materialdesignicons.com/icon/forklift)
