### ISSUE TITLE
Door Open and Close Icons

### ISSUE THREAD

**Issue by skalavala** [Templarian/MaterialDesign#2059]
Wouldn't it be wonderful to have two beautiful icons that represent **Door Open** and **Door Close** statuses? I see that there is a "glassdoor" icon, but no icon that represents real doors. Thx!

**Comment by GreenTurtwig** [comment]
Duplicate of: https://github.com/Templarian/MaterialDesign/issues/1822
And the `glassdoor` is the icon for the website Glassdoor. :cat:
