### ISSUE TITLE
Headphones Off

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2060]
Appears there was no icon for `headphones-off` but was for `headset`. :-/
![puush-linux 2017-05-03 at 10 18 24](https://cloud.githubusercontent.com/assets/15905797/25654694/f96187a2-2fe9-11e7-9bf3-eea6cef4c2ae.png)
![puush-linux 2017-05-03 at 10 18 31](https://cloud.githubusercontent.com/assets/15905797/25654698/fabe2326-2fe9-11e7-8438-97c39214302c.png)
[headphones-off.zip](https://github.com/Templarian/MaterialDesign/files/972895/headphones-off.zip)

**Comment by Templarian** [comment]
[![headphones-off](https://materialdesignicons.com/icon/headphones-off)](https://materialdesignicons.com/icon/headphones-off)

@GreenTurtwig Thanks for cleaning up the extra points, really makes this go quicker. 😃
