### ISSUE TITLE
Public CDN?

### ISSUE THREAD

**Issue by ToX82** [Templarian/MaterialDesign#2061]
I see that you have a CDN here: https://cdn.materialdesignicons.com/1.8.36/

But is it a public CDN, meaning that everyone can use it on their own websites? If not, do you plan to have it in the future? (jsDelivr, maxcdn or else)

**Comment by Templarian** [comment]
Yea, it's a public CDN. It's sponsored by MaxCDN, thousands use it. We still recommend self hosting, but yea tons of people/companies use it.
