### ISSUE TITLE
Icon suggestion: Paypal

### ISSUE THREAD

**Issue by CarloFavero** [Templarian/MaterialDesign#2064]
A simple Paypal icon, to be used in a contact page. I'd like it to work well with other contact icons such as "home" "phone" "instagram" "facebook" and so on. Thank you!

Maybe it could work with the darker blue in black and the light blue outlined, without bothering the transparency effect:

<img width="111" alt="schermata 2017-05-04 alle 11 18 03" src="https://cloud.githubusercontent.com/assets/21282454/25697482/63e89422-30bb-11e7-8dbf-07613edd6359.png">

**Comment by GreenTurtwig** [comment]
This has been requested quite a lot now, unfortunately it's been decided it's not possible to be added (although it would be really great to have). :crying_cat_face: 
https://github.com/Templarian/MaterialDesign/issues/297 is there if and when there are any changes.
