### ISSUE TITLE
Popsicle / Ice Pop

### ISSUE THREAD

**Issue by KIQ19** [Templarian/MaterialDesign#2067]
I need an ice cream icon, something like this: https://d30y9cdsu7xlg0.cloudfront.net/png/4926-200.png

**Comment by nkspappas** [comment]
What about this one, @KIQ19 ?

![ice_cream](https://cloud.githubusercontent.com/assets/22625723/26129755/3c02d6a0-3a9a-11e7-88d8-ab53aa989e93.png)
![ice_cream_128](https://cloud.githubusercontent.com/assets/22625723/26129845/ad2a529a-3a9a-11e7-8248-17926ff03718.png)

svg file here: https://www.dropbox.com/sh/jzjd2qsacufiqya/AACucy2o2Px-qdqQNy2qPiuPa?dl=0

**Comment by KIQ19** [comment]
@nkspappas This looks very specific for popsicles, I'm looking for a more generic icon for ice cream

**Comment by CoDEmanX** [comment]
I created two ice cream icons a while ago: https://github.com/Templarian/MaterialDesign/issues/873#issuecomment-208050697

**Comment by Templarian** [comment]
`ice-cream` was added, but still need to add `popsicle`.

**Comment by GreenTurtwig** [comment]
Might be worth giving `popsicle` the alias `ice-lolly` and or `ice-pop`.

**Comment by CoDEmanX** [comment]
Which is the preferred design of both contributions?

**Comment by CoDEmanX** [comment]
I think mine is too small without rotation:

![image](https://user-images.githubusercontent.com/1309249/38770894-0a07533e-401a-11e8-9455-339b8301579d.png)

**Comment by goyney** [comment]
Cleaned up version of @nkspappas's:
![image](https://user-images.githubusercontent.com/1015040/52985349-753ac000-33c1-11e9-9080-a71ec0d10eda.png)
[popsicle.svg.zip](https://github.com/Templarian/MaterialDesign/files/2877929/popsicle.svg.zip)

**Comment by JapanYoshi** [comment]
I still think we should either rotate it 45° or not at all.

**Comment by goyney** [comment]
`ice-pop` added. 😄
