### ISSUE TITLE
"Classic" TV and desktop

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2068]
Phone has a `classic`/retro variation, so why not the TV and desktop too. :cat2:

![puush-linux 2017-05-04 at 03 26 52](https://cloud.githubusercontent.com/assets/15905797/25708388/3db15abe-30de-11e7-9b5c-3594095ce0ea.png)
![puush-linux 2017-05-04 at 03 27 14](https://cloud.githubusercontent.com/assets/15905797/25708393/42fde3c0-30de-11e7-89fc-34211b7eefe3.png)

![puush-linux 2017-05-04 at 03 27 37](https://cloud.githubusercontent.com/assets/15905797/25708422/5e86c5e4-30de-11e7-8aff-cac10bdf2155.png)
![puush-linux 2017-05-04 at 03 27 50](https://cloud.githubusercontent.com/assets/15905797/25708425/606b42d6-30de-11e7-8493-a8b0a72d2920.png)
Based on the IBM 5150 (could use more detail, not that they would show at a small size :-/)

[classic.zip](https://github.com/Templarian/MaterialDesign/files/976453/classic.zip)

**Comment by Templarian** [comment]
Probably naming these `television-classic` and `desktop-classic`.

We need a alias these `computer` and `tv` now that I think about it.

**Comment by GreenTurtwig** [comment]
Yeah, that's what I named them. 🐈

**Comment by Templarian** [comment]
@GreenTurtwig Lets pretend I read. 😆

**Comment by GreenTurtwig** [comment]
Haha, of course. 😸

**Comment by Templarian** [comment]
Was in Seattle all last week, one of the events I attended was at the Living Computer Museum. Kind of cool to see all the old computer still working.

[![television-classic](https://materialdesignicons.com/icon/television-classic)](https://materialdesignicons.com/icon/television-classic) [![desktop-classic](https://materialdesignicons.com/icon/desktop-classic)](https://materialdesignicons.com/icon/desktop-classic)

Aliased `tv-classic` and `computer-classic`.
