### ISSUE TITLE
ear icon

### ISSUE THREAD

**Issue by karlinnolabs** [Templarian/MaterialDesign#2069]
seems there's no ear in there, I did have one - I'll try and dig it out

**Comment by Templarian** [comment]
Yea, we need to work on adding accessibility icons. We've added a few, but we have no deaf ones at the moment/blind at the moment.

**Comment by MrGrigri** [comment]
Like the MD one? https://material.io/icons/#ic_hearing

**Comment by Templarian** [comment]
[![ear-hearing](https://materialdesignicons.com/icon/ear-hearing)](https://materialdesignicons.com/icon/ear-hearing)
