### ISSUE TITLE
Group Icon

### ISSUE THREAD

**Issue by nwtgck** [Templarian/MaterialDesign#207]
I would like to use group icon.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/account-multiple

Or do you mean something else?

**Comment by nwtgck** [comment]
Yes, I do. The image is like the following.

http://materialdesignicons.com/icon/google-circles-extended

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/google-circles-group

Let me know if this works. Eventually I might rename these to just circles. Not sure yet.

**Comment by nwtgck** [comment]
Thank you
