### ISSUE TITLE
Cheque

### ISSUE THREAD

**Issue by soundmarrow** [Templarian/MaterialDesign#2070]
I'd love to have credit card brand icons (Visa, Mastercard, Amex, Discover, Diners Club, JCB), as well as a check icon. Thanks!

**Comment by PeterShaggyNoble** [comment]
See #367 for details on why individual credit card icons won't be added.

**Comment by GreenTurtwig** [comment]
@soundmarrow Do you mean a credit card with a check mark, or a paper cheque/check?

**Comment by soundmarrow** [comment]
I was thinking of graphic of a paper bank cheque/check.

**Comment by bcluff50** [comment]
I would like to have a graphic of a paper bank check as well.

**Comment by defbrett** [comment]
![ic_cheque_black_48px](https://user-images.githubusercontent.com/34491761/33909714-68ddf960-df41-11e7-8cec-1f307e6e38af.png)
Paper Check/Cheque Icon would be great. I tried to create one myself, but can't seem to simplify it in Inkscape.

**Comment by PeterShaggyNoble** [comment]
Here's Google's chequebook icon:

[![checkbook](https://user-images.githubusercontent.com/15157491/38925337-364492ce-42f7-11e8-9a46-d116e790b408.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by PeterShaggyNoble** [comment]
[![checkbook](https://user-images.githubusercontent.com/15157491/44394948-636e8200-a530-11e8-97f0-3fc92a02df2d.png)](https://materialdesignicons.com/icon/checkbook)
