### ISSUE TITLE
Mastodon

### ISSUE THREAD

**Issue by metbril** [Templarian/MaterialDesign#2073]
Mastodon is the new, hot, open source and federated social network.

Repo: https://github.com/tootsuite/mastodon
Main instance: https://mastodon.social

To be able to create "share"  etc. icons for a weblog, it would be great if the application icon is included in MDI.

Example/original: https://github.com/tootsuite/mastodon/blob/1.3-stable/app/assets/images/logo.svg

![Alt text](https://cdn.rawgit.com/tootsuite/mastodon/1.3-stable/app/assets/images/logo.svg)

**Comment by Dissem** [comment]
The logo recently changed, the new one is here: https://github.com/tootsuite/mastodon/blob/master/app/javascript/images/logo.svg
or
https://github.com/tootsuite/mastodon/blob/master/app/javascript/images/logo_alt.svg
for the more compact one.

![Mastodon Logo](https://github.com/tootsuite/mastodon/raw/master/app/javascript/images/logo.svg?sanitize=true)
or
![Mastodon Logo](https://github.com/tootsuite/mastodon/raw/master/app/javascript/images/logo_alt.svg?sanitize=true)

**Comment by MrGrigri** [comment]
We try to keep to main social networks. Mastodon itself claims to be a niche social network on their home page.

**Comment by PeterShaggyNoble** [comment]
Closing this for the reason @MrGrigri stated above. Can be revisited if Mastodon ever becomes more popular.

**Comment by jelv** [comment]
"Can be revisited if Mastodon ever becomes more popular."

Mastodon has grown to 1.069.702 users on 1913 servers that have posted 192 million toots. https://dashboards.mnm.social/dashboard/db/mastodon-network-overview?refresh=1h&orgId=1&from=now-7d&to=now

I think it's time to add the Mastodon icon.

**Comment by connyduck** [comment]
Yes please! I need a mastodon icon too!

**Comment by PeterShaggyNoble** [comment]
A single path SVG can be found [here](https://github.com/tootsuite/mastodon/blob/master/app/javascript/images/logo_transparent.svg).

**Comment by Templarian** [comment]
Due to changing times, we'll be adding this icon in the next release.

**Comment by Templarian** [comment]
[![mastodon](https://materialdesignicons.com/icon/mastodon)](https://materialdesignicons.com/icon/mastodon) [![mastodon-variant](https://materialdesignicons.com/icon/mastodon-variant)](https://materialdesignicons.com/icon/mastodon-variant)
