### ISSUE TITLE
Icons in 16x16?

### ISSUE THREAD

**Issue by AravK** [Templarian/MaterialDesign#2074]
Some icon SVGs in the Linux Adwaita icon theme are 16x16 pixels. So when I try to use these (awesome) icons they're badly resized? Can I get some icons in 16x16??? Can I resize them myself?

**Comment by Templarian** [comment]
These are really not ideal for 16x16. You could open the SVG's (download via the site) and resize them. The advanced export lets one generate png files, but resizing them down less than 24x24 will look blurry.

There are probably other icon packs that are more optimized for the smaller size (font awesome for instance).
