### ISSUE TITLE
Machine(ry)

### ISSUE THREAD

**Issue by mwiikned** [Templarian/MaterialDesign#2077]
I was thinking that a good icon to have could be one representing machinery. Whether it is a table saw, drill press, ect.

**Comment by goyney** [comment]
@mwiikned  We now have `circular-saw`, `hand-saw`, `sawblade`. Do any of these fulfill your request?

**Comment by mwiikned** [comment]
The saw icons definitely are a step in the right direction and I will most likely make use of the circular-saw. I believe something more towards that heavy/large machine would still be useful. Something like a table-saw might even be a good addition off of that saw blade theme.

**Comment by JamesCoyle** [comment]
We need to get some examples of what this could look like. It might be hard to come up with generic machinery.

**Comment by goyney** [comment]
Agreed. If you want to request specific heavy machinery icons, please open new issues for each idea.
