### ISSUE TITLE
Missing icon: External link

### ISSUE THREAD

**Issue by cjmaxik** [Templarian/MaterialDesign#2078]
http://fontawesome.io/icon/external-link/

![l9y9ho0 1](https://cloud.githubusercontent.com/assets/1501705/25838134/e324bfc8-34d4-11e7-9d2b-3b6f191f0c44.png)

**Comment by JapanYoshi** [comment]
A quick search would have done it, but ok I guess. https://materialdesignicons.com/icon/open-in-new

**Comment by cjmaxik** [comment]
Yep, my fault.

**Comment by CoDEmanX** [comment]
We have it under a different name:https://materialdesignicons.com/icon/open-in-new
