### ISSUE TITLE
Icon request: external link

### ISSUE THREAD

**Issue by Theo-Schusterjunge** [Templarian/MaterialDesign#2079]
An icon with an arrow pointing out of the top right corner of a square would be super helpful! :)

**Comment by JapanYoshi** [comment]
You could have taken all the time you took to modify the post to [perform a quick search.](https://materialdesignicons.com/icon/open-in-new)

@Templarian Can we just add “external” as a key word in the description of this icon? Another person asked for the same icon just days ago.

**Comment by Theo-Schusterjunge** [comment]
Boy, I'm really sorry—believe me, of course I _did_ search for it first, but didn't find it. Call me stupid, but I just came up with all the wrong keywords … and scrolling through the great amount of icons I just missed it.
And sorry again for trying to label my issue properly. I don't have a lot of experience with GitHub yet.

**Comment by Theo-Schusterjunge** [comment]
Boy, I'm really sorry—believe me, of course I _did_ search for it first, but didn't find it. Call me stupid, but I just came up with all the wrong keywords … and scrolling through the great amount of icons I just missed it.
And sorry again for trying to label my issue properly. I don't have a lot of experience with GitHub yet.

**Comment by JamesCoyle** [comment]
Can we alias with external and link?

**Comment by Templarian** [comment]
Yea, we can. Reopening.

**Comment by Templarian** [comment]
Alias added `external-link`. This way link or external in the search will find it.

@Theo-Schusterjunge No problem, yea not an obvious name, hopefully this solves it for others searching in the future.

**Comment by Theo-Schusterjunge** [comment]
@Templarian Thanks! This really helps :)
