### ISSUE TITLE
Missing icons (i.e. dropbox)

### ISSUE THREAD

**Issue by noctivityinc** [Templarian/MaterialDesign#208]
Love what you guys are doing but not sure how to deal with missing icons.  I searched your list and dropbox has an icon there.  When I downloaded the package, dropbox is missing.

How do we deal with missing icons from the css?

**Comment by Templarian** [comment]
Once I verify all icons are correct I do a webfont release. Thousands use the icon set so each release needs to be checked.

Next release is tonight or tomorrow. I'll close this after the release.

http://materialdesignicons.com/history to see new icons since last release.

**Comment by noctivityinc** [comment]
Excellent!  Ive starred the repo and added it to my watch list to get notified.  Thanks!

**Comment by Templarian** [comment]
Got busy with some work things, I'll be committing the update tonight. Font export checks out. Just need to close out another issue #202 first.

**Comment by Templarian** [comment]
You can now `bower install mdi` or `npm install mdi` for `v0.9.72-alpha`.
