### ISSUE TITLE
Circular social icons

### ISSUE THREAD

**Issue by yenyrubiano** [Templarian/MaterialDesign#2080]
The only social icon that has a circular version is Twitter. Can you please create a circular version for Facebook and LinkedIn? Thanks!

**Comment by Templarian** [comment]
Due to branding guidelines on various brand/social media icons, we recommend putting a circle around their icons rather than modifying the logos to be circles.

We probably shouldn't even include the twitter one tbh. Might be on the list of icons to clean up in the future.

**Comment by MahmoudAymann** [comment]
@yenyrubiano here can find what you need [https://iconmonstr.com](https://iconmonstr.com)
