### ISSUE TITLE
Unicode for icons

### ISSUE THREAD

**Issue by azurh** [Templarian/MaterialDesign#2081]
Where can I find unicode for a given icon? I'm going to use the ttf file in an Android app and want to reference the webfont via unicodes. Example `&#xf271` or just `f271`.

**Comment by PeterShaggyNoble** [comment]
You can find them in the `preview.html` file included with the download, which can also be accessed [here](https://cdn.materialdesignicons.com/1.9.32/). Alternatively, you could grab them from [my sandbox](http://mdi.houseofdesign.ie/), if you prefer.
