### ISSUE TITLE
Game Icons

### ISSUE THREAD

**Issue by raphatorres89** [Templarian/MaterialDesign#2083]
Hello,

I sugest icons of games, like swords, potions, helmet, buckler and other things...

It will help my new site.

Thanks!

---

- [x] sword - https://materialdesignicons.com/icon/sword
- [x] shield - https://materialdesignicons.com/icon/shield
- [ ] helmet - #2807
- [x] potion - https://materialdesignicons.com/icon/flask
- [ ] bow
- [x] skull - https://materialdesignicons.com/icon/skull
- [x] key - https://materialdesignicons.com/icon/key
- [ ] mace
- [ ] fireball
- [ ] staff

**Comment by Templarian** [comment]
We have swords, flasks. We're adding more RPG related icons. Do you have examples of what these might look like?

**Comment by raphatorres89** [comment]
I think sword, shield, helmet, potion, bow, skull, key, mace, fireball, staff...
things like these.
thanks for the answer ;)

**Comment by goyney** [comment]
- [x] sword - https://materialdesignicons.com/icon/sword
- [x] shield - https://materialdesignicons.com/icon/shield
- [ ] helmet
- [x] potion - https://materialdesignicons.com/icon/flask
- [ ] bow
- [x] skull - https://materialdesignicons.com/icon/skull
- [x] key - https://materialdesignicons.com/icon/key
- [ ] mace
- [ ] fireball - Could use https://materialdesignicons.com/icon/fire rotated
- [ ] staff

**Comment by goyney** [comment]
We have many of these now, such as `sword`, `shield`, `flask`, `key`, `skull`...

The ones we are missing are all weapon related (bow, mace, axe, staff, spear)... Those are being tracked in #1935.
