### ISSUE TITLE
Icon request: Heat, cool, hot, cold

### ISSUE THREAD

**Issue by Br3nda** [Templarian/MaterialDesign#2085]
I used mdi for home automation. Some icons for heating and cooling of a room would be super useful.

**Comment by JapanYoshi** [comment]
So, thermometer + up/down arrow?

**Comment by Br3nda** [comment]
or heat coming out of a vent
maybe: fire / ice / snowflake

example use case:
- the tab/link that leads to where you control heat/cool actions. generic is awesome.
- or an indication that something is too hot / too cold.

**Comment by bhargavgv** [comment]
There's already a [fire](https://materialdesignicons.com/icon/fire) and [snowflake](https://materialdesignicons.com/icon/snowflake) icon, but i think an ice icon would be a good idea.

**Comment by Br3nda** [comment]
thermometer with up and down is good.
fire is a bit to alarming to see on homeautomation etc. It's possibly best used to mean actual fire.

**Comment by goyney** [comment]
These were added in `3.5`:

[![thermometer-chevron-up](https://materialdesignicons.com/icon/thermometer-chevron-up)](https://materialdesignicons.com/icon/thermometer-chevron-up)[![thermometer-chevron-down](https://materialdesignicons.com/icon/thermometer-chevron-down)](https://materialdesignicons.com/icon/thermometer-chevron-down)
