### ISSUE TITLE
Icon request: Terminal

### ISSUE THREAD

**Issue by odin3** [Templarian/MaterialDesign#2086]
Please add terminal icon

**Comment by Templarian** [comment]
Would console work?

[![console](https://materialdesignicons.com/icon/console)](https://materialdesignicons.com/icon/console)

**Comment by JamesCoyle** [comment]
Do we have a version without the window?

**Comment by Templarian** [comment]
@JamesCoyle Not that I'm aware of. Couldn't hurt.

**Comment by Templarian** [comment]
[![console-line](https://materialdesignicons.com/icon/console-line)](https://materialdesignicons.com/icon/console-line)
