### ISSUE TITLE
Icon request: Fidget spinner

### ISSUE THREAD

**Issue by bhargavgv** [Templarian/MaterialDesign#2088]
Can you please add a fidget spinner icon?

**Comment by Templarian** [comment]
Kids these days and their little toys. 😹 This is going to be a little too specific for the icon pack at this time.

Thanks for the suggestion.

**Comment by bhargavgv** [comment]
@Templarian You're right. 
😀

**Comment by PeterShaggyNoble** [comment]
I had to Google what it was. It made me angry! 😆

**Comment by bhargavgv** [comment]
LOL

-- 
-Bhargav Garre Venkata

**Comment by ButchMonkey** [comment]
Sorry to necro this issue but - 
Google have their own fidget spinner icon that is used as the loading spinner on any youtube video that is related to fidget spinners

http://svgshare.com/i/31t.svg

**Comment by JamesCoyle** [comment]
![](https://media.giphy.com/media/1M9fmo1WAFVK0/giphy.gif)

**Comment by bhargavgv** [comment]
@ButchMonkey That would be good to add to the icon pack, but I don't think I need this icon anymore.

**Comment by ButchMonkey** [comment]
I'm not suggesting that it's added but found it funny that google would add it

**Comment by PeterShaggyNoble** [comment]
> That would be good to add to the icon pack, but I don't think I need this icon anymore.

The fickleness of youth!
