### ISSUE TITLE
Heatmap Icons

### ISSUE THREAD

**Issue by yim0331** [Templarian/MaterialDesign#2092]
As heatmap is largely used for the a graphical representation of data , I wish to have heatmap icons.

**Comment by PeterShaggyNoble** [comment]
Do you have an example of what they might look like, @yim0331? Something like [Icons8's one](https://icons8.com/icon/set/heat%20map/androidL), maybe?

**Comment by yim0331** [comment]
Yes, the Icons8's one looks good.

Sang-il Yim

**Comment by JamesCoyle** [comment]
Would this work?
[![](https://materialdesignicons.com/icon/chart-bubble)](https://materialdesignicons.com/icon/chart-bubble)

**Comment by JamesCoyle** [comment]
Icons8 version as reference:
![image](https://user-images.githubusercontent.com/10384436/62718320-8625cf00-b9fd-11e9-9b20-908b01991918.png)

**Comment by bernaferrari** [comment]
This looks like Google Assistant. I usually associate heat maps with squares instead of circles, but this is personal, a circle would be perfectly fine.

**Comment by goyney** [comment]
`chart-scatter-plot` is extremely similar to the provided example.
[![chart-scatter-plot](https://materialdesignicons.com/icon/chart-scatter-plot)](https://materialdesignicons.com/icon/chart-scatter-plot)

**Comment by Xenomorph99** [comment]
I don't think there's a good way to create a Material Design icon representing a heat map like you've asked for. Heat maps like the one you showed above, @bernaferrari, rely on color and opacity to convey meaning. Material Design icons don't have color and they don't use opacity.

Here's some icons already in our library that might work for you instead:

- [gradient](https://materialdesignicons.com/icon/gradient)
- [blur](https://materialdesignicons.com/icon/blur)
- [blur-radial](https://materialdesignicons.com/icon/blur-radial)
- [blur-linear](https://materialdesignicons.com/icon/blur-linear)
- [grain](https://materialdesignicons.com/icon/grain)
- [google-podcast](https://materialdesignicons.com/icon/google-podcast)
