### ISSUE TITLE
Wrench with a small clock

### ISSUE THREAD

**Issue by alvaroc1** [Templarian/MaterialDesign#2093]
Representing scheduled maintenance.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/42565115-78ff5f46-84fa-11e8-9fa3-edf9ea3e96af.png)](https://github.com/Templarian/MaterialDesign/files/2183983/wrench-clock.zip)

**Comment by CoDEmanX** [comment]
The overlapping looks odd, and the wrench shape is a bit hard to recognize at native size. Maybe use a slightly smaller clock, or perhaps move the wrench to the top left corner and place the clock at the bottom?

**Comment by Templarian** [comment]
Agreed, not sure I like the look of the overlap.

**Comment by Simran-B** [comment]
Using the standard modifier placement and the wrench from the `tools` icon as base:

![image](https://user-images.githubusercontent.com/7819991/136043471-b7c9fb7f-93a0-44ef-899d-a1ee9f007ad7.png)

Different wrench orientation:

![image](https://user-images.githubusercontent.com/7819991/136048051-26694ee5-e1c4-472e-9eb6-68ef087fd8a3.png)

Using a sandblock instead (doesn't work well as a modifier nor do the cutouts looks good):

![image](https://user-images.githubusercontent.com/7819991/136046957-9e94872d-988e-40cc-bba3-cb9e02ba3ace.png) ![image](https://user-images.githubusercontent.com/7819991/136046879-fc23bcbc-77a8-4d69-81cb-eb2228543fd5.png)

[wrench-clock.zip](https://github.com/Templarian/MaterialDesign/files/7286884/wrench-clock.zip)

**Comment by goyney** [comment]
Yeah, I've tried with the standard clock, but wondered if too much of the wrench was covered to make sense. I definitely don't like the hourglasses for the same reasons you point out.

I wonder if you're on to something with changing the orientation of the wrench. Wonder if we should try a couple more attempts doing that.

**Comment by Simran-B** [comment]
I guess just up right works:

![image](https://user-images.githubusercontent.com/7819991/136057165-3725f77b-ddd5-4f89-ae37-958277932045.png)

[wrench-clock5.zip](https://github.com/Templarian/MaterialDesign/files/7287262/wrench-clock5.zip)

**Comment by goyney** [comment]
[![wrench-clock](https://materialdesignicons.com/icon/wrench-clock)](https://materialdesignicons.com/icon/wrench-clock)
