### ISSUE TITLE
bus-articulated-front improvment

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#2095]
I think [the icon](https://materialdesignicons.com/icon/bus-articulated-front) would look better if the back wheel is left out (like the front wheel is missing in [bus-articulated-end](https://materialdesignicons.com/icon/bus-articulated-end)). 
I also think both would benefit if they are a bit more centered and not strechted so much.

**Comment by JamesCoyle** [comment]
The bus would collapse in the middle if the front didn't have two axles... 
![image](https://cloud.githubusercontent.com/assets/10384436/26247877/c4eb3a3a-3c97-11e7-94cd-fb19e584159c.png)
