### ISSUE TITLE
Suggested Material Icon: Hourglass

### ISSUE THREAD

**Issue by fractalbob** [Templarian/MaterialDesign#2098]
How about an hourglass icon, to display the passage of time?

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/timer-sand
https://materialdesignicons.com/icon/timer-sand-full
https://materialdesignicons.com/icon/timer-sand-empty

- [ ] Alias `timer-sand` as `hourglass`
- [ ] Alias `timer-sand-full` as `hourglass-full`
- [ ] Alias `timer-sand-empty` as `hourglass-empty`

Marking this as needing an alias.

**Comment by GreenTurtwig** [comment]
Given aliases.
