### ISSUE TITLE
scale, rule

### ISSUE THREAD

**Issue by christian160984** [Templarian/MaterialDesign#210]
- [x] Scale
- [x] Rule

**Comment by Templarian** [comment]
http://materialdesignicons.com/scale
http://materialdesignicons.com/ruler
http://materialdesignicons.com/scale-bathroom

**Comment by CoDEmanX** [comment]
Google got an icon that could be used as ruler (#420) :
http://www.google.com/design/icons/#ic_straighten

And my try at a beaker with scales as a generic measurement icon:
![measure-beaker](https://cloud.githubusercontent.com/assets/1309249/8888228/5b01f3a0-32a5-11e5-9e09-5316fc054974.png) https://www.dropbox.com/s/g3sj6be3ys39fhg/measure-beaker.svg?dl=0

**Comment by Templarian** [comment]
[![beaker](https://materialdesignicons.com/icon/beaker)](https://materialdesignicons.com/icon/beaker)
