### ISSUE TITLE
Girl face

### ISSUE THREAD

**Issue by JosefKatic** [Templarian/MaterialDesign#2101]
Hello, there is already an icon with a face but what about to create a icon with a face of women/girl actually the same face but with long hairs.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/60144514-ac1a4b80-9790-11e9-8860-d141e65d1f02.png)
[face-woman.svg.zip](https://github.com/Templarian/MaterialDesign/files/3327802/face-woman.svg.zip)

**Comment by goyney** [comment]
[![face-woman](https://materialdesignicons.com/icon/face-woman)](https://materialdesignicons.com/icon/face-woman)[![face-woman-outline](https://materialdesignicons.com/icon/face-woman-outline)](https://materialdesignicons.com/icon/face-woman-outline)
