### ISSUE TITLE
Unicode Emoji (Faces)

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#2102]
If you want one of these icons to be made, please make a separate issue and reference this issue. We can then use that issue to monitor the progress of its addition to the icon set.

---

There are so many requests for icons which would fall into the unicode emoji range so I figured it was maybe worth creating a list of the unicode emoji. I'd suggest linking relevant issues here and marking as duplicates.

`N/a` in the `MDI Name` column denotes that we do not plan to support that icon as it doesn't fit in well with the Material Design guidelines.

# Positive
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F600 | 😀 | Grinning face | 
U+1F601 | 😁 | Grinning face with smile |
U+1F602 | 😂 | Face with tears of joy | 
U+1F923	| 🤣 | Rolling on the floor laughing | 
U+263A | ☺ | Smiling face |
U+1F603 | 😃 | Smiling face with open mouth | 
U+1F604 | 😄 | Smiling face with open mouth & smiling eyes | emoticon-excited
U+1F605 | 😅 | Smiling face with open mouth & cold sweat | 
U+1F606 | 😆 | Smiling face with open mouth & closed eyes | 
U+1F609 | 😉 | Winking face | 
U+1F60A | 😊 | Smiling face with smiling eyes | 
U+1F60B | 😋 | Face savouring delicious food | 
U+1F60E | 😎 | Smiling face with sunglasses | emoticon-cool
U+1F60D | 😍 | Smiling face with heart-eyes | 
U+1F618 | 😘 | Face blowing a kiss | 
U+1F617	| 😗 | Kissing face |
U+1F619	| 😙 | Kissing face with smiling eyes |
U+1F61A | 😚 | Kissing face with closed eyes |
U+1F642 | 🙂| Slightly smiling face | emoticon-happy
U+1F917 | 🤗| Hugging face | 
U+1F929 | 🤩 | Star-struck |
U+1F607	| 😇 | Smiling face with halo | 

# Neutral
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F914 | 🤔 | Thinking face | 
U+1F928 | 🤨 | Face with raised eyebrow |
U+1F610 | 😐 | Neutral face | emoticon-neutral
U+1F611 | 😑 | Expressionless face | 
U+1F636 | 😶 | Face without mouth | 
U+1F60F | 😏 | Smirking face | 
U+1F623 | 😣 | Persevering face | 
U+1F625 | 😥 | Disappointed but relieved face | 
U+1F62E | 😮 | Face with open mouth | 
U+1F910 | 🤐 | Zipper-mouth face | 
U+1F62F | 😯 | Hushed face | 
U+1F62A | 😪 | Sleepy face | 
U+1F62B | 😫 | Tired face |
U+1F634 | 😴 | Sleeping face | 
U+1F60C | 😌 | Relieved face | 
U+1F61B | 😛 | Face with stuck out tongue | emoticon-tongue
U+1F61C	| 😜 | Face with stuck-out tongue & winking eye |
U+1F61D | 😝 | Face with stuck-out tongue & closed eyes | 
U+1F924 | 🤤 | Drooling face | 
U+1F612 | 😒 | Unamused face | 
U+1F613 | 😓 | Face with cold sweat | 
U+1F614	| 😔 | Pensive face | 
U+1F615 | 😕 | Confused face | 
U+1F643	| 🙃 | Upside-down face |
U+1F911	| 🤑 | Money-mouth face | 
U+1F632	| 😲 | Astonished face | 
U+1F92B	| 🤫 | Shushing face | 
U+1F92D	 | 🤭 | Face with hand over mouth | 

# Negative
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+2639 | ☹ | Frowning face | 
U+1F641 | 🙁 | Slightly frowning face | emoticon-sad
U+1F616 | 😖 | Confounded face | 
U+1F61E | 😞 | Disappointed face | 
U+1F61F | 😟 | Worried face | 
U+1F624 | 😤 | Face with steam from nose | 
U+1F622	| 😢 | Crying face | 
U+1F62D	| 😭 | Loudly crying face | 
U+1F626	| 😦 | Frowning face with open mouth | 
U+1F627	| 😧 | Anguished face | 
U+1F628	| 😨 | Fearful face | 
U+1F629 | 😩 | Weary face | 
U+1F92F	| 🤯 | Exploding head | 
U+1F62C	| 😬 | Grimacing face | 
U+1F630	| 😰 | Face with open mouth & cold sweat | 
U+1F631	| 😱 | Face screaming in fear | 
U+1F633	| 😳 | Flushed face | 
U+1F92A	| 🤪 | Crazy face | 
U+1F635	| 😵 | Dizzy face | 
U+1F621	| 😡 | Pouting face | 
U+1F620	| 😠 | Angry face | 
U+1F92C	| 🤬 | Face with symbols over mouth | 
U+1F925	| 🤥 | Lying face | 

# Sick
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F637 | 😷 | Face with medical mask | 
U+1F912 | 🤒 | Face with thermometer | 
U+1F915 | 🤕 | Face with head bandage | 
U+1F922 | 🤢 | Nauseated face |
U+1F92E | 🤮 | Face vomiting | 
U+1F927 | 🤧 | Sneezing face | 

# Other 
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F913	| 🤓 | Nerd face | 
U+1F9D0	| 🧐 | Face with monocle |
U+1F608	| 😈 | Smiling face with horns | emoticon-devil
U+1F47F	| 👿 | Angry face with horns | 
U+1F479	| 👹 | Ogre | 
U+1F47A	| 👺 | Goblin |
U+1F480	| 💀 | Skull | 
U+2620	| ☠ | Skull and crossbones | 
U+1F47B	| 👻 | Ghost | 
U+1F47D	| 👽 | Alien | 
U+1F47E	| 👾 | Alien monster | 
U+1F916	| 🤖 | Robot | 
U+1F4A9	| 💩 | Pile of poo | emoticon-poop

**Comment by PeterShaggyNoble** [comment]
https://github.com/Templarian/MaterialDesign/issues/2103#issuecomment-357473771
