### ISSUE TITLE
Unicode Animals and Nature

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#2103]
If you want one of these icons to be made, please make a separate issue and reference this issue. We can then use that issue to monitor the progress of its addition to the icon set.

---

Lots of requests for animal icons so this is the list of animals available in the unicode character set. I've just stuck to the faces to keep it simple. 

*Icon has face and non-face variant 

# Mammals
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F435* | 🐵 | Monkey face | 
U+1F648	| 🙈 | See-no-evil monkey | 
U+1F649	| 🙉 | Hear-no-evil monkey | 
U+1F64A	| 🙊 | Speak-no-evil monkey | 
U+1F98D | 🦍 | Gorilla | 
U+1F436* | 🐶 | Dog face | 
U+1F429	| 🐩 | Poodle | 
U+1F43A	| 🐺 | Wolf | 
U+1F98A | 🦊 | Fox | 
U+1F431* | 🐱 | Cat | cat
U+1F63A	| 😺 | Smiling cat face with open mouth | 
U+1F638	| 😸 | Grinning cat face with smiling eyes | 
U+1F639	| 😹 | Cat face with tears of joy | 
U+1F63B	| 😻 | Smiling cat face with heart-eyes | 
U+1F63C	| 😼 | Cat face with wry smile | 
U+1F63D	| 😽 | Kissing cat face with closed eyes | 
U+1F640	| 🙀 | Weary cat face | 
U+1F63F	| 😿 | Crying cat face | 
U+1F63E	| 😾 | Pouting cat face | 
U+1F981	| 🦁 | Lion | 
U+1F42F* | 🐯 | Tiger |  
U+1F406	| 🐆 | Leopard | 
U+1F434* | 🐴 | Horse | 
U+1F984	| 🦄 | Unicorn | 
U+1F993 | 🦓 | Zebra | 
U+1F98C	| 🦌 | Deer | 
U+1F42E* | 🐮 | Cow | cow
U+1F402 | 🐂 | Ox | 
U+1F403	| 🐃 | Water buffalo | 
U+1F437* | 🐷 | Pig | pig
U+1F417	| 🐗 | Boar | 
U+1F40F	| 🐏 | Ram | 
U+1F411 | 🐑 | Ewe | 
U+1F410	| 🐐 | Goat | 
U+1F42A	| 🐪 | Camel |
U+1F42B	| 🐫 | Two-humped camel | 
U+1F992	| 🦒 | Giraffe | 
U+1F418	| 🐘 | Elephant | 
U+1F98F	| 🦏 | Rhinoceros | 
U+1F42D* | 🐭 | Mouse | 
U+1F400	| 🐀 | Rat | 
U+1F439	| 🐹 | Hamster | 
U+1F430* | 🐰 | Rabbit | 
U+1F43F	| 🐿 | Chipmunk | 
U+1F994	| 🦔 | Hedgehog | 
U+1F987	| 🦇 | Bat | 
U+1F43B	| 🐻 | Bear | 
U+1F428	| 🐨 | Koala | 
U+1F43C	| 🐼 | Panda | panda

# Birds
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F983	| 🦃 | Turkey | 
U+1F414	| 🐔 | Chicken | 
U+1F413	| 🐓 | Rooster | 
U+1F423	| 🐣 | Hatching chick | 
U+1F424* | 🐤 | Baby chick | 
U+1F426 | 🐦 | Bird | 
U+1F427	| 🐧 | Penguin | 
U+1F54A	| 🕊 | Dove | 
U+1F985	| 🦅 | Eagle | 
U+1F986	| 🦆 | Duck | duck
U+1F989	| 🦉 | Owl | owl

# Amphibians and Reptiles
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F438	| 🐸 | Frog | 
U+1F40A	| 🐊 | Crocodile | 
U+1F422	| 🐢 | Turtle | 
U+1F98E	| 🦎 | Lizard | 
U+1F40D	| 🐍 | Snake | 
U+1F432* | 🐲 | Dragon |
U+1F995	| 🦕 | Sauropod |
U+1F996	| 🦖 | T-Rex | 

# Marine animals
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F433	| 🐳 | Spouting whale |
U+1F40B	| 🐋 | Whale | 
U+1F42C	| 🐬 | Dolphin | 
U+1F41F	| 🐟 | Fish | fish
U+1F420	| 🐠 | Tropical fish | 
U+1F421	| 🐡 | Blowfish | 
U+1F988	| 🦈 | Shark | 
U+1F419	| 🐙 | Octopus | 
U+1F41A	| 🐚 | Spiral shell | 
U+1F980	| 🦀 | Crab | 
U+1F990	| 🦐 | Shrimp | 
U+1F991	| 🦑 | Squid | 

# Bugs
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F40C	| 🐌 | Snail | 
U+1F98B	| 🦋 | Butterfly | 
U+1F41B | 🐛 | Bug | bug
U+1F41C	| 🐜 | Ant | 
U+1F41D | 🐝 | Bee |
U+1F41E	| 🐞 | Ladybug | 
U+1F997	| 🦗 | Cricket | 
U+1F577	| 🕷 | Spider | 
U+1F578	| 🕸 | Spiderweb | 
U+1F982	| 🦂 | Scorpion | 

# Flowers 
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F490	| 💐 | Bouquet | 
U+1F338	| 🌸 | Cherry blossom | 
U+1F4AE	| 💮 | White flower | 
U+1F3F5	| 🏵 | Rosette | 
U+1F339	| 🌹 | Rose |
U+1F940	| 🥀 | Wilted flower | 
U+1F33A	| 🌺 | Hibiscus | 
U+1F33B	| 🌻 | Sunflower |
U+1F33C	| 🌼 | Blossom | 
U+1F337	| 🌷 | Tulip | 

# Plants
Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F331	| 🌱 | Seedling | 
U+1F332	| 🌲 | Evergreen | pine-tree
U+1F333	| 🌳 | Deciduous | tree
U+1F334	| 🌴 | Palm | 
U+1F335	| 🌵 | Cactus | 
U+1F33E	| 🌾 | Sheaf of rice | 
U+1F33F	| 🌿	| Herb | 
U+2618	| ☘ | Shamrock | 
U+1F340	| 🍀 | Four leaf clover | 
U+1F341	| 🍁 | Maple leaf | 
U+1F342	| 🍂 | Fallen leaf | 
U+1F343	| 🍃 | Leaf fluttering in wind |
U+1F344 | 🍄 | Mushroom | #2158

**Comment by GreenTurtwig** [comment]
We should consider giving some aliases too, for example:
Turtle - Tortoise (should probably be renamed rather than given an alias, or be given the alias of "turtle")
Blowfish - Pufferfish
Bug - Centipede
Ladybug - Ladybird

**Comment by JamesCoyle** [comment]
Definitely. We are gonna have to sort out a logical way to name everything.

**Comment by Templarian** [comment]
Going to close out this issue, I know a lot of work went into the table, but lets try and track one icon per issue. Also a lot of these may/will be difficult at the small mono-color size.
