### ISSUE TITLE
Unicode Professions (Job Roles)

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#2104]
If you want one of these icons to be made, please make a separate issue and reference this issue. We can then use that issue to monitor the progress of its addition to the icon set.

---

I figured I may as well continue with these categories as I've seen so many requests for most of these icons that never seem to get anywhere. It's helpful having a place where they can all be collected together and maybe have some progress made.

These ones get a bit more complex when it comes to the unicode character as they utilize modifiers. I'm just including the standard variant of each profession with male and female counterparts as skintone doesn't matter for monotone icons. I'm sure gender will also be too hard to show for most of these but I've included it for completeness. 

I've not included a lot of the general 'person' icons as they aren't particularly professions though I suppose `person getting massage` and `person getting haircut` could represent masseuse and hairdresser/barber. If anyone thinks this list can be added to, let me know. 

Sports have not been included as they are better suited to their own category. There are also a few fantasy style characters like zombie, genie, elf, etc. which I'm not sure whether to add here or keep separate. 

Unicode | Icon | Description | MDI Name
--- | --- | --- | ---
U+1F920 | 🤠 | Cowboy | #2247
U+1F921	| 🤡 | Clown | 
U+1F468 U+200D U+2695 U+FE0F | 👨‍⚕️ | Male health worker | #2245
U+1F469 U+200D U+2695 U+FE0F | 👩‍⚕️ | Female health worker | #2621
U+1F468 U+200D U+1F393 | 👨‍🎓 | Male student | 
U+1F469 U+200D U+1F393 | 👩‍🎓 | Female student | 
U+1F468 U+200D U+1F3EB | 👨‍🏫 | Male teacher | #2724 
U+1F469 U+200D U+1F3EB | 👩‍🏫 | Female teacher | 
U+1F468 U+200D U+2696 U+FE0F | 👨‍⚖️ | Male judge |
 U+1F469 U+200D U+2696 U+FE0F | 👩‍⚖️ | Female judge | 
U+1F468 U+200D U+1F33E | 👨‍🌾 | Male farmer |
U+1F469 U+200D U+1F33E | 👩‍🌾 | Female farmer | 
U+1F468 U+200D U+1F373 | 👨‍🍳 | Male cook |  #2100
U+1F469 U+200D U+1F373 | 👩‍🍳 | Female cook | 
U+1F468 U+200D U+1F527 | 👨‍🔧 | Male mechanic | 
U+1F469 U+200D U+1F527 | 👩‍🔧 | Female mechanic | 
U+1F468 U+200D U+1F3ED | 👨‍🏭 | Male factory worker |
U+1F469 U+200D U+1F3ED | 👩‍🏭 | Female factory worker | 
U+1F468 U+200D U+1F4BC | 👨‍💼 | Male office worker | 
U+1F469 U+200D U+1F4BC | 👩‍💼 | Female office worker | 
U+1F468 U+200D U+1F52C | 👨‍🔬 | Male scientist | 
U+1F469 U+200D U+1F52C | 👩‍🔬 | Female scientist | 
U+1F468 U+200D U+1F4BB | 👨‍💻 | Male technologist | 
U+1F469 U+200D U+1F4BB | 👩‍💻 | Female technologist | 
U+1F468 U+200D U+1F3A4 | 👨‍🎤 | Male singer | 
U+1F469 U+200D U+1F3A4 | 👩‍🎤 | Female singer | 
U+1F468 U+200D U+1F3A8 | 👨‍🎨 | Male artist | 
U+1F469 U+200D U+1F3A8 | 👩‍🎨 | Female artist | 
U+1F468 U+200D U+2708 U+FE0F | 👨‍✈️ | Male pilot |
U+1F469 U+200D U+2708 U+FE0F | 👩‍✈️ | Female pilot | 
U+1F468 U+200D U+1F680 | 👨‍🚀 | Male astronaut/cosmonaut | 
U+1F469 U+200D U+1F680 | 👩‍🚀 | Female astronaut/cosmonaut |
U+1F468 U+200D U+1F692 | 👨‍🚒 | Male firefighter |
U+1F469 U+200D U+1F692 | 👩‍🚒 | Female firefighter | 
U+1F46E | 👮 | Police officer |
U+1F575	| 🕵 | Detective | 
U+1F482	| 💂 | Guard | 
U+1F477	| 👷 | Construction worker |
U+1F934	| 🤴 | Prince | 
U+1F478	| 👸 | Princess | 
U+1F385	| 🎅 | Santa |

**Comment by PeterShaggyNoble** [comment]
https://github.com/Templarian/MaterialDesign/issues/2103#issuecomment-357473771
