### ISSUE TITLE
Volume-off-variant

### ISSUE THREAD

**Issue by andrewnenakhov** [Templarian/MaterialDesign#2105]
Existing [volume off](https://materialdesignicons.com/icon/volume-off) icon takes a bit too much space and is hard to use in some contexts. Several social networks use a more slim version of the same idea: [volume-off-variant](https://github.com/Templarian/MaterialDesign/files/1022735/volume-off-variant.svg.zip)

**Comment by JamesCoyle** [comment]
All of our icons take up exactly the same amount of space. They are all designed to fit into a 24x24px grid that can then be scaled as required.

**Comment by andrewnenakhov** [comment]
@JamesCoyle this one should do better:
![volume-off-variant 1x](https://cloud.githubusercontent.com/assets/2351903/26363271/fd3aedee-3ff9-11e7-9ca5-c7635662b0f0.png)

Updated svg:
[volume-off-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/1022788/volume-off-variant.svg.zip)

**Comment by JamesCoyle** [comment]
It's still gonna be the exact same width as the current icon. It might be worth adding `volume-off-low`, `volume-off-medium`, and `volume-off-high` variants to show the volume level if the user were to unmute but I'll let @Templarian decide on that one.

**Comment by andrewnenakhov** [comment]
@JamesCoyle icon blocks are 24x24 of course, however, in some contexts currently existing icon looks too bulky and heavy, while slim one is much better: 
![2017-05-23 21 07 21](https://cloud.githubusercontent.com/assets/2351903/26363893/f75bd6e8-3ffb-11e7-8807-35f246594dcc.png)

**Comment by CoDEmanX** [comment]
The counter stroke should be on the other side (i.e. "top")

**Comment by andrewnenakhov** [comment]
Tried that, looks worse for our use case.

**Comment by CoDEmanX** [comment]
Do you happen to have that one still around? Would like to take a look.

**Comment by andrewnenakhov** [comment]
@CoDEmanX I don't have drawn image on hand, however, it's easy to explain why we opted to use different stroke direction - the one used in other similar icons makes lower left part of icon so much heavier than upper right, and it looks unbalanced.

**Comment by goyney** [comment]
@andrewnenakhov Hate to nitpick, but all of our other `off` variants have the white cut-out above the line, not below. I believe we should match our style, even if the source icon is different. Could you please update your contribution, we plan on adding this icon in this next release.

**Comment by andrewnenakhov** [comment]
@goyney @CoDEmanX did a cut out below. I think it's really not nice:

[volume-off-variant-2.svg.zip](https://github.com/Templarian/MaterialDesign/files/2814272/volume-off-variant-2.svg.zip)

![image](https://user-images.githubusercontent.com/2351903/52009832-b09a4b00-24f5-11e9-9ddc-d9d98ca556ea.png)

Still, to me previous version looks so much better:
![image](https://user-images.githubusercontent.com/2351903/52009981-1b4b8680-24f6-11e9-8534-b78d28fc0ec7.png)

**Comment by Templarian** [comment]
The slash can be extended so it doesn't look as attached to the bottom half. The cut out is always above and never below for consistency, but I think extending the slash should look okay

**Comment by andrewnenakhov** [comment]
With slighly longer cutout:
![image](https://user-images.githubusercontent.com/2351903/52010523-91042200-24f7-11e9-8c05-4865facb06a5.png)
[volume-off-variant-2.svg.zip](https://github.com/Templarian/MaterialDesign/files/2814323/volume-off-variant-2.svg.zip)

With a slightly longer and bigger cutout and stroke to better match [volume-off](https://materialdesignicons.com/icon/volume-off) icon. 
![image](https://user-images.githubusercontent.com/2351903/52010818-41722600-24f8-11e9-9d46-ffd0ca764ec3.png)
[volume-off-variant-4.svg.zip](https://github.com/Templarian/MaterialDesign/files/2814339/volume-off-variant-4.svg.zip)

**Comment by Templarian** [comment]
We never deviate from the `2dp` rule (it's kind of what makes an MD icon), but the 3rd should work okay for now.

**Comment by andrewnenakhov** [comment]
@Templarian calculating coordinates to make an exactly 2dp wide diagonal line is a pain, and rotating rectangle bars 45º and subtracting it from a shape is... well... hard to do really precise. I really dislike not precise things. Current cutout is 1,77dp, hard to do better without putting vertexes on really odd coordinates.

**Comment by Templarian** [comment]
- Make two 2x10 rectangles and rotate 45deg.
- Subtract the top rectangle
- Union the bottom one.
- Remove unnecessary points.
- Set the nudge amount for your keyboard keys to 0.25 pixels.
- Now you can select the bottom right two points and move them down + right to extend the line.
- Same can be done to the top left of the slash.

I have considered making tutorials about how I design icons in various softwares. Each has different tricks that make things easier.

**Comment by goyney** [comment]
Using our official template:
![image](https://user-images.githubusercontent.com/1015040/52012523-c59cbd00-24a8-11e9-9a19-305cb92b2b66.png)

[volume-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/2814425/volume-off.svg.zip)

**Comment by Templarian** [comment]
Yea, the official template is a nice starting point, but in this case it does need to be moved up and the length of the slash needs to be shorted by `1dp` on either end.

**Comment by andrewnenakhov** [comment]
@Templarian of course I understand how to rotate and subract/union. It just vertexes that don't fall on more or less nice coordinates that bother me. 

@goyney this latest variant does not look nice at all. Can hardly 'read' this image as a crossed out speaker.

**Comment by Templarian** [comment]
[![volume-variant-off](https://materialdesignicons.com/icon/volume-variant-off)](https://materialdesignicons.com/icon/volume-variant-off)
