### ISSUE TITLE
Adjust emoticon-poop to be less Apple flavored.

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#2107]
[![](https://materialdesignicons.com/icon/emoticon-poop)](https://materialdesignicons.com/icon/emoticon-poop)

Currently it's based heavily on the Apple/iOS version of the emoticon. Can we perhaps adjust it to make it more Material? For a start I feel the eyes should be round and the icon as a whole could be simplified a bit. 

Here is Google's current emoticon:

![image](https://cloud.githubusercontent.com/assets/10384436/26363815/1ab56342-3fda-11e7-9e58-92a23828ab4b.png)

**Comment by Templarian** [comment]
Sure, if someone wants to trace it or extract the vector from the font (not sure if it's online somewhere).

**Comment by Flitskikker** [comment]
I got the font from my phone, but all emoji are actually bitmaps, unfortunately.

Also note the new Android O version:
https://emojipedia.org/pile-of-poo/

**Comment by JamesCoyle** [comment]
I think the one I posted looks better for a flat icon set. It's simple and looks good next to the other emoticons.

**Comment by GreenTurtwig** [comment]
And I know I'm not that only one who dislikes Google's new emoji...

**Comment by GreenTurtwig** [comment]
Wasn't hard at all:
![](https://puu.sh/w7F23.png)
![](https://puu.sh/w7F2H.png)
[emoticon-poop.zip](https://github.com/Templarian/MaterialDesign/files/1045092/emoticon-poop.zip)

**Comment by Templarian** [comment]
Updated.

@GreenTurtwig You're listed on the site as the one that edited it, but the current site doesn't show icon history. New site addresses this.
