### ISSUE TITLE
Dip-switch icon requested

### ISSUE THREAD

**Issue by BlackWitcher** [Templarian/MaterialDesign#2108]
Hello, can you add icon for dip-switch, please.
Dip-switch is hardware switcher with some pins. For example, it looks like this:
![image](https://cloud.githubusercontent.com/assets/3014189/26391515/c1b3a1f4-406b-11e7-8447-339a07073fda.png)

Icon for example too (not material):
![image](https://cloud.githubusercontent.com/assets/3014189/26391588/0e04dcbc-406c-11e7-816b-e4ddae9aae4f.png) 
![image](https://cloud.githubusercontent.com/assets/3014189/26391600/182f959c-406c-11e7-8f93-6d5af679f8a5.png)
![image](https://cloud.githubusercontent.com/assets/3014189/26391615/27cbbc38-406c-11e7-805e-add4e1fb1c4a.png)

Thanks in advance!

**Comment by Templarian** [comment]
[![dip-switch](https://materialdesignicons.com/icon/dip-switch)](https://materialdesignicons.com/icon/dip-switch)

Made it similar to the last example. It's a little difficult to represent in the small 24x24 size. Hopefully this works, if not we can reopen and try some other designs.

**Comment by BlackWitcher** [comment]
Austin, it's looks very nice! It's thats I needs. Very grateful to you, thanks!
