### ISSUE TITLE
Graduation Cap icon request

### ISSUE THREAD

**Issue by iHaruku** [Templarian/MaterialDesign#2109]
I would like a graduation cap icon. Something similar to Font Awesome:
![image](https://cloud.githubusercontent.com/assets/7127557/26421285/7d129ed8-4093-11e7-8daf-750ed18e4f98.png)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/school

We need to add an alias. Keeping this issue opened until it's added to the system.

**Comment by iHaruku** [comment]
Thanks!

**Comment by Templarian** [comment]
Alias is added. `graduation-cap`, should help people find it from now on.
