### ISSUE TITLE
database-remove, database-refresh, database-settings

### ISSUE THREAD

**Issue by snuuve** [Templarian/MaterialDesign#2112]
More icons for database icon:

Remove:
http://downloadicons.net/sites/default/files/delete-database-icon-27858.png

Refresh:
https://identitatdigital.upc.edu/gcredencials/img/boto_recuperar.png

Config:
http://www.cadtec.dees.ufmg.br/img/data_configuration.png

**Comment by MrGrigri** [comment]
Closing this issue in favor of #3716
