### ISSUE TITLE
locker and locker-multiple do not work

### ISSUE THREAD

**Issue by kraeki** [Templarian/MaterialDesign#2113]
Hi there,

I am trying to use the `locker` icon, but somehow it does not work. Am I missing anything?

The icons got installed using `npm install mdi`. This is how I am using it:
```
<!-- works perfectly -->
<i class="mdi mdi-book-multiple-variant"></i>

<!-- not working  -->
<i class="mdi mdi-locker"></i> 
<i class="mdi mdi-locker-multiple"></i>
```

Is it still supported? At least it is listed here: https://materialdesignicons.com/tag/community

Other icons work perfectly.

Regards,
kraeki

**Comment by PeterShaggyNoble** [comment]
They will be available in the next release. See the [history page](https://materialdesignicons.com/history) for the list of icons added since the last release. You can follow the updates on the next release [here](https://github.com/Templarian/MaterialDesign/issues/1983).

**Comment by JamesCoyle** [comment]
@Templarian Is this gonna be made clearer on the new site? We get a lot of people confused about how releases work.

**Comment by Templarian** [comment]
@JamesCoyle Yea, still haven't figured this out, we'll need to put some kind of [DRAFT] type label with a description. We currently have about 100 icons not synced in. Ideally I need to be doing releases more frequently.
