### ISSUE TITLE
Icon Request: HD & UHD, Stereo & 5.1

### ISSUE THREAD

**Issue by andrewkelly83** [Templarian/MaterialDesign#2114]
A couple of icons for different video formats, HD & UHD are probably all that's needed

Similarly, one that says 5.1 and another for ST would be useful.

- [x] HD `high-definition`
- [x] SD `standard-definition`
- [x] UHD, `ultra-high-definition`
- [x] Stereo
- [x] Surround Sound (stock Google), `surround-sound`
- [x] 3.1 (still a common setup), `surround-sound`
- [x] 5.1, `surround-sound-5-1`
- [x] 7.1, `surround-sound-7-1`
- [x] 3D, `video-3d` (we can't start icon names with numbers)

**Comment by Templarian** [comment]
@andrewkelly83 Updated your issue with a list and a few others we need to add. Kind of surprised we don't have these already.

**Comment by Templarian** [comment]
So I'm in the process of adding all of these, but is there a standard way to represent stereo? Speaker? Headphones?

Maybe just add a `surround-sound-2-1` (yea weird name, but consistent).

**Comment by PeterShaggyNoble** [comment]
[`volume-high`](http://mdi.houseofdesign.ie/?icon=volume-high) is the norm, I think, @Templarian. But you'll occasionally see it represented with two facing away from each other.

**Comment by Templarian** [comment]
All of these have been added! 😸

**Comment by andrewkelly83** [comment]
@Templarian just had a look at these and they are great and exactly what I need, agree that two volume-high facing away from each other is the best representation of stereo.

Great work though

**Comment by CoDEmanX** [comment]
This is the only logo that comes to mind...

![surround](https://upload.wikimedia.org/wikipedia/en/thumb/0/0f/Dolby-Surround.svg/1280px-Dolby-Surround.svg.png)

**Comment by andrewkelly83** [comment]
This is the kind of thing I think shows stereo, I did this with two volume-high icons back to back as suggested by @PeterShaggyNoble 

![stereo](https://cloud.githubusercontent.com/assets/25012022/26588288/cd23a22e-454c-11e7-8dd1-3083e8aacb6b.png)

**Comment by Templarian** [comment]
We already have the https://materialdesignicons.com/icon/dolby icon.

Hmm... yea 2 channels. Needs to be thinner somehow.

**Comment by andrewkelly83** [comment]
@Templarian thoughts on this, I've just overlapped them, perhaps too much, maybe there needs to be a bit more horizontal in teh middle.

![stereo](https://cloud.githubusercontent.com/assets/25012022/26620581/4e29363e-45db-11e7-976e-8807bed59c80.png)

**Comment by JapanYoshi** [comment]
Back to back isn't the way to go, methinks.
