### ISSUE TITLE
icon suggestion: ring, necklace, fruits and ...

### ISSUE THREAD

**Issue by emanf** [Templarian/MaterialDesign#2118]
hi,

icon suggestion:
- Ring
- Necklace
- Fruits
- Vegetables
- Cloth
- Company
- Pipe
- Carpet
- Toilet

thanks for your awesome work

**Comment by JamesCoyle** [comment]
Could you split this up into individual requests please? Cloth and carpet may be hard to do. Ring was just added. Fruit and veg need to be more specific (I will be posting another unicode list for those soon). Company could be represented by `domain` or one of the other building icons.

**Comment by emanf** [comment]
> Could you split this up into individual requests please?

sure. i wil and i will add some ideas for these icons too.
