### ISSUE TITLE
Air Horn

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#2119]
It could be an interesting addition. Some casual social network apps might benefit from that, methinks.

**Comment by Templarian** [comment]
@JapanYoshi Is that like https://materialdesignicons.com/icon/bullhorn ?

**Comment by Alekhen** [comment]
It makes sense to have both an air horn and a bull horn icon representing two distinct real world objects, however they would probably carry a similar meaning when used in an interface (i.e. "pay attention" or "look at this").

That being said, here's a design I threw together for this request.

![air-horn](https://cloud.githubusercontent.com/assets/1837101/26524075/1aa0183a-42e5-11e7-820d-1f0e0fee6842.png)

[air-horn.svg.zip](https://github.com/Templarian/MaterialDesign/files/1033772/air-horn.svg.zip)

**Comment by Templarian** [comment]
[![air-horn](https://materialdesignicons.com/icon/air-horn)](https://materialdesignicons.com/icon/air-horn)
