### ISSUE TITLE
fan

### ISSUE THREAD

**Issue by dgmltn** [Templarian/MaterialDesign#212]
I'd like to see an icon for a fan; something like this. I'd want to be able to animate/rotate this about its center too:
https://cdn2.iconfinder.com/data/icons/gears-wheels-blades/512/fan-512.png

The request is related to this one:
https://github.com/Templarian/MaterialDesign/issues/201

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/fan

**Comment by dgmltn** [comment]
Thanks!
