### ISSUE TITLE
Beauty / Fashion

### ISSUE THREAD

**Issue by alkahtani** [Templarian/MaterialDesign#2121]
beauty and fashion icons

**Comment by alkahtani** [comment]
okay , i tried to find icons related to beauty "Makeup " such as "hair , nails ,cutting ,..etc but with no luck , in addition to these icons  the services provided by salons also need icons , i don't know if this enough or more info required .

**Comment by PeterShaggyNoble** [comment]
I'm going to close this one out due to inactivity and because it doesn't provide any concrete examples.

@alkahtani, if you're still in need of these icons, please open a new issue with an example for each one you require. Don't forget to search the existing icons and issues first.
