### ISSUE TITLE
[Feat] Download Icon Package like material.io/icons 

### ISSUE THREAD

**Issue by AlirezaAkbarix** [Templarian/MaterialDesign#2123]
Thanks for your nice works.
How can I download icons like `https://material.io/icons/`? 
I'm using `Xamarin` to develop so I can't use vectors, now I have 2 options:

1. Use `Android 4.x Actionbar` that gives me transparented icons which is deprecated in material design
2. Use `Android 5.x` that gives me many of icons and I have to remove most of them to have folders like the top one to copy to the project.

So how can I have only `100%` black or white icons like what I can have in option 1?

**Comment by CoDEmanX** [comment]
All of the icons are monochrome. Do you mean that there must not be a transparent background / no alpha layer?

**Comment by Templarian** [comment]
Not sure I follow. You can right click any icon and download, or click on an icon and select any size png from the "Icon" drop down to get black or white icons in 24, 36, or 48.

Weird that Xamarin Forms wouldn't support vector.

**Comment by AlirezaAkbarix** [comment]
Of curse not!! please take a look at [Google Material icon site](https://material.io/icons/) and see if you choose (e.g.) 24dp size, it'll give you all related size (drawable-hdpi/drawable-mdpi/drawable-xdpi,...) folders, but in your really nice project, in 2 conditions I'm able to download other sizes (I explained both of them and their disadvantages in description).
SFMBE.

**Comment by Templarian** [comment]
Oh, you want a simplified download with just a subset of the files. So there are API's for this in the new site, we don't have those in the legacy site. So this feature will have to hold off until the new site.

https://github.com/Templarian/MaterialDesign-Site/issues/6 This story will handle this. Pretty much allows us to modify the front end to generate any file combination on the fly.
