### ISSUE TITLE
incoming , outgoing and internal memo [ Documents ]

### ISSUE THREAD

**Issue by BeSaRa** [Templarian/MaterialDesign#2124]
hello , there is a way to make icon for incoming and outgoing [document] like a document with arrow up,down and for internal memo display the 2 arrow around it.

**Comment by PeterShaggyNoble** [comment]
Would `file-import` and `file-export` suit your needs?

[![file-import](https://materialdesignicons.com/icon/file-import)](https://materialdesignicons.com/icon/file-import) [![file-export](https://materialdesignicons.com/icon/file-export)](https://materialdesignicons.com/icon/file-export)

**Comment by Templarian** [comment]
Closing this issue. Please add more details and we'll reopen the issue.

**Comment by BeSaRa** [comment]
Dear @Templarian  
i'm sorry for my late reply.
we have a system working with documents ,  name it Correspondence Management System -> 
It is used for correspondence between departments ... if management wants to send Documents to another department through this system
The types of correspondence are three
(incoming- outgoing- internal memo) concerning the documents.
I want icon that shows well for each of these types.

**Comment by Templarian** [comment]
Just saw this, uhh... might be best to use a different icon for internal memo. Like one of the `note` icons.
