### ISSUE TITLE
Real Time Text

### ISSUE THREAD

**Issue by uchchishta** [Templarian/MaterialDesign#2127]
Request:
 The Real Time Text or Fast Text logo/icon ![](http://www.realjabber.org/r3tf/FastText-logo_50.png) in Material with the style of  ![](https://cdn.rawgit.com/Templarian/MaterialDesign/607b2e6e/icons/svg/truck-fast.svg) (melting fast) and material "font" ![material letters?](https://cloud.githubusercontent.com/assets/25387925/26678306/90a71b44-46ed-11e7-86be-d5ef9f81f120.png) italic "T"

**Comment by GreenTurtwig** [comment]
http://www.realtimetext.org/standard-graphics

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
