### ISSUE TITLE
Google Assistant Icon

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2128]
I'd love an icon for the Google Assistant bubbles icon:

![google_assistant_logo](https://cloud.githubusercontent.com/assets/18021678/26698038/407aec96-46e2-11e7-8f4b-2916c044713d.png)

This is the icon the assistant uses to identify itself in conversation:

![assistant_screenshot](https://cloud.githubusercontent.com/assets/18021678/26698057/52e9fbb0-46e2-11e7-89e4-4b0311bb40df.png)

**Comment by Flitskikker** [comment]
Three suggestions:

![screen shot 2017-06-02 at 15 19 06](https://cloud.githubusercontent.com/assets/3516155/26727356/de58d7ec-47a6-11e7-8f8e-f35d7b2cbf90.png)

![screen shot 2017-06-02 at 15 18 59](https://cloud.githubusercontent.com/assets/3516155/26727364/e309ad48-47a6-11e7-99ee-e0f152daf42f.png)

[google-assistant.zip](https://github.com/Templarian/MaterialDesign/files/1047773/google-assistant.zip)

**Comment by k5cents** [comment]
I think I like the second one best. Most true to the original. Although, I could see the third being used just as an exaggerated version to make the difference in bubble size clear at a small icon size.

**Comment by Templarian** [comment]
[![google-assistant](https://materialdesignicons.com/icon/google-assistant)](https://materialdesignicons.com/icon/google-assistant)

Assigned to the Google account. Thanks!
