### ISSUE TITLE
Hulu Brand Icon

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2129]
The Hulu "h" (without the box) from their icon would be awesome. We have Netflix, so I don't see why this shouldn't be added.

![hulu](https://cloud.githubusercontent.com/assets/18021678/26702723/51b39f46-46f4-11e7-9b09-16c171bc8dc4.png)

**Comment by Alekhen** [comment]
How does this look?
![hulu](https://user-images.githubusercontent.com/1837101/27246322-158e1260-52ae-11e7-8ed3-76f92b79a7a6.png)
![hulu-24](https://user-images.githubusercontent.com/1837101/27246327-17b95d9c-52ae-11e7-8e38-821e7a808dc2.png)
[hulu.svg.zip](https://github.com/Templarian/MaterialDesign/files/1082055/hulu.svg.zip)

**Comment by k5cents** [comment]
Bump?

**Comment by Templarian** [comment]
[![hulu](https://materialdesignicons.com/icon/hulu)](https://materialdesignicons.com/icon/hulu)

Thanks! @Alekhen Remind me when you have 5 contributions.

**Comment by Alekhen** [comment]
@Templarian I've got 5 contributions now:
hulu (this ticket)
rice #2147 
soy #2147 
ring #2152 
message alert outline #2116
