### ISSUE TITLE
Getting Started: SVG's / Vector Drawables for Legacy Android

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#213]
Explain using the SVG files to support legacy Android applications (pre 21 api).

SVG: https://github.com/trello/victor
Vector Drawables: https://github.com/telly/MrVector

**Comment by JamesCoyle** [comment]
Is this even worth doing at this point? I feel like most apps that care about UI enough to use these icons will only be supporting Lollipop and above.
