### ISSUE TITLE
SSL Certificate has expired.

### ISSUE THREAD

**Issue by Kyle-Mendes** [Templarian/MaterialDesign#2131]
This makes materialdesignicons.com and the CDNs not load for all of mdi.

**Comment by Templarian** [comment]
Yea, it's stuck in an inprogress state. Should start working again shortly with the updated cert.

**Comment by Templarian** [comment]
It's definitely updated. My server shows 4th June 2018 as the expire date. Hopefully it refreshes shortly.

**Comment by Templarian** [comment]
Seems to work okay now. CDN still isn't working. Looking into that one right now.

**Comment by Templarian** [comment]
The CDN's cert isn't valid until the 2nd, that's why that one isn't working. 😿 Should work sometime tomorrow.

**Comment by Templarian** [comment]
Awesome, CDN is working with the new cert also (I keep these on 2 different certs).

**Comment by Kyle-Mendes** [comment]
Thank you for the swift response!
