### ISSUE TITLE
Microsoft Exchange

### ISSUE THREAD

**Issue by cacapis** [Templarian/MaterialDesign#2132]
Hi there, I would really appreciate if you could add a Microsoft Exchange icon like this:
[Icon](https://c.s-microsoft.com/en-us/CMSImages/ExchangeLaunchIcon2013.jpg?version=88145122-7090-fd3b-b45b-982849c426fc)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
