### ISSUE TITLE
Encyclopedia Icon

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#2133]
I took the dictionary icon and swapped out the "a-z" for the information-outline icon

![encyclopedia 1](https://cloud.githubusercontent.com/assets/18021678/26748465/fcfb734c-47cb-11e7-9651-9d8c44367ad7.png)

I'm going to use this for a Wikipedia icon for my phone, but though I'd submit it here if anybody wanted to make a .svg out of it for the collection. I didn't measure out the placing or anything, and the edges are super soft (I only have a flash based editor to work with).

**Comment by terreng** [comment]
Is this still something we're interested in?

![image](https://user-images.githubusercontent.com/11605395/53676114-ea748380-3c52-11e9-849d-db54bc70a399.png)
[book-information.svg](https://github.com/terreng/samples/blob/master/book-information.svg)

**Comment by goyney** [comment]
[![book-information-variant](https://materialdesignicons.com/icon/book-information-variant)](https://materialdesignicons.com/icon/book-information-variant)
