### ISSUE TITLE
add SASS and Java icons

### ISSUE THREAD

**Issue by Elwin1010** [Templarian/MaterialDesign#2136]
Sass is becoming more and more popular, and Java is just another nice language icon to have 😉 

Btw, great work so far on the icon font. Told all my mates about it and now everyone uses it 😄

**Comment by shroudedcode** [comment]
The **Java** one was already requested multiple times (#1699, #1502, #271).

**Sass** is a new suggestion and I'd be interested in it too.
There's a `.ZIP` of vector logos including the "S" on their ["Brand guidelines" page](http://sass-lang.com/styleguide/brand).

![](http://sass-lang.com/assets/img/styleguide/seal-color-aef0354c.png)

**Comment by Templarian** [comment]
[![sass](https://materialdesignicons.com/icon/sass)](https://materialdesignicons.com/icon/sass)
