### ISSUE TITLE
Wall

### ISSUE THREAD

**Issue by xaviergonz** [Templarian/MaterialDesign#2139]
A wall, perhaps could be made out of bricks or something

**Comment by shroudedcode** [comment]
@xaviergonz Something similar to this?

![](https://d30y9cdsu7xlg0.cloudfront.net/png/782-200.png)

**Comment by xaviergonz** [comment]
@shroudedcode yep, pretty much spot on I'd say

**Comment by Templarian** [comment]
[![wall](https://materialdesignicons.com/icon/wall)](https://materialdesignicons.com/icon/wall)
