### ISSUE TITLE
Sizes

### ISSUE THREAD

**Issue by dovahkiin98** [Templarian/MaterialDesign#214]
why so many icons? like why can't i choose one size for the icon i want, and one color, i either have to download one size or one color

**Comment by Templarian** [comment]
I assume you mean you want to download the Android 4.x or Android 5.x package with all the icons with the color selected in the Advanced setting. If so there is an open issue for this.

https://github.com/Templarian/MaterialDesign/issues/165

Let me know if this is a duplicate. I'll be working on closing 165 out this weekend (maybe St Patrick's weekend might delay that ha).

**Comment by Templarian** [comment]
I'm going to assume this is a duplicate since there was no reply. Still coding this feature. Hopefully I'll have time to get it into the beta release this weekend.
