### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by xaviergonz** [Templarian/MaterialDesign#2140]
There are 2 move/resize variants, but not a resize one (which could be like the move/resize variants but without the outer arrow)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/arrow-all

Can you post an example. Not sure I understand without a visual.

**Comment by xaviergonz** [comment]
Like this https://materialdesignicons.com/icon/move-resize-variant or this https://materialdesignicons.com/icon/move-resize but without the top-left arrow (which indicates move)

**Comment by xaviergonz** [comment]
@Templarian do you need further info?

**Comment by PeterShaggyNoble** [comment]
You could rotate [`open-in-new`](https://materialdesignicons.com/icon/open-in-new) 90 degrees.

**Comment by Templarian** [comment]
[![resize](https://materialdesignicons.com/icon/resize)](https://materialdesignicons.com/icon/resize)
