### ISSUE TITLE
Follow icon request

### ISSUE THREAD

**Issue by im4eversmrt** [Templarian/MaterialDesign#2141]

**Comment by shroudedcode** [comment]
@im4eversmrt What do you imagine a "follow" icon to look like?

**Comment by vcantu** [comment]
I think you could use this icon
![account-plus](https://user-images.githubusercontent.com/13156162/27215620-20f3b22c-5240-11e7-943b-d7433580caa3.png)

**Comment by MrGrigri** [comment]
I agree with @vcantu, and you could also use a more creepy version. 

![account-multiple](https://materialdesignicons.com/icon/account-multiple)

**Comment by im4eversmrt** [comment]
Cool , that will do the job. Thanks appreciate it.
