### ISSUE TITLE
Announcement Icon

### ISSUE THREAD

**Issue by awazgyawali** [Templarian/MaterialDesign#2142]
I would love to have announcement icon which as a mic with some spikes that represents something it coming out of it. Example icon https://thumb1.shutterstock.com/display_pic_with_logo/4384864/447697270/stock-vector-bullhorn-vector-icon-megaphone-or-loudspeaker-sign-announce-symbol-447697270.jpg

**Comment by CoDEmanX** [comment]
We have such an icon already: https://materialdesignicons.com/icon/bullhorn

Another alias wouldn't harm.

**Comment by Templarian** [comment]
Added the alias `announcement`. 😸
