### ISSUE TITLE
New Icon Request: Theatre Icons Set

### ISSUE THREAD

**Issue by SubinVs** [Templarian/MaterialDesign#2143]
Working in theatre project to show the seat availability. Searching for concession icons, parking icons, Signage icons and theatre related icon set.

**Comment by shroudedcode** [comment]
Here are a few icons that might interest you:
- [`parking`](https://materialdesignicons.com/icon/parking)
- [`sign-direction`](https://materialdesignicons.com/icon/sign-direction)
- [`routes`](https://materialdesignicons.com/icon/routes)
- [`seat-recline-normal`](https://materialdesignicons.com/icon/seat-recline-normal)
- [`theater`](https://materialdesignicons.com/icon/theater)
- [`popcorn`](https://materialdesignicons.com/icon/popcorn)

If there are any icons missing that you need, let us know.

**Comment by GreenTurtwig** [comment]
Note the `theater` icon should really be given the alias of `theatre`. :cat2:

**Comment by derwaldgeist** [comment]
The theater icon looks like a movie theater. I am looking for a traditional theater, which could by symbolized by masks, similar to this: https://i.pinimg.com/originals/6c/28/c1/6c28c1644b26303b67cd2879355e8d0a.png

**Comment by PeterShaggyNoble** [comment]
@derwaldgeist, see #1972 for the masks
