### ISSUE TITLE
cheatsheet list in text file

### ISSUE THREAD

**Issue by alizarei95** [Templarian/MaterialDesign#2145]
Hi , can i find a text file with name and hex entities of all icons?

**Comment by Templarian** [comment]
http://cdn.materialdesignicons.com/1.9.32/meta.json

If you need something a little more updated...
https://materialdesignicons.com/custom Needs to be updated for the new website to support more of the features found in the database. For now use the meta.json and a script of your choice to generate a cheatsheet. Or use the http://cdn.materialdesignicons.com/1.9.32/ Cheatsheet.

**Comment by alizarei95** [comment]
no i am using this font in Android Studio and i can use only hex values , so i need hex values , any idea?
@Templarian
