### ISSUE TITLE
Corn, Rice, Soybean, Soy Sauce

### ISSUE THREAD

**Issue by agustinsivoplas** [Templarian/MaterialDesign#2147]
I would like icons like rice, soyabean, corn, all about commodities.

- [ ] rice
- [ ] soybean
- [x] corn

**Comment by Templarian** [comment]
Some of these are going to be a little difficult to design at the small size, but we'll see what the community can create.

**Comment by thunsaker** [comment]
Found some time today to play around with icons. Thought I'd pop in with a few Corn suggestions.

<img width="1250" alt="screen shot 2017-06-13 at 16 24 54" src="https://user-images.githubusercontent.com/137686/27108974-f208428a-5054-11e7-88d9-37c1e06e8480.png">

I'm partial to 5 personally.

![corn-kernels-alt-2-small](https://user-images.githubusercontent.com/137686/27109000-1038b8de-5055-11e7-8ac5-5b9901b95656.png)
at 24px

SVG/PNG Files: [mdi-corn.zip](https://github.com/Templarian/MaterialDesign/files/1073142/mdi-corn.zip)

**Comment by JamesCoyle** [comment]
I like it but I don't like the angle created between the leaves. Also kinda related to #2103.

**Comment by MrGrigri** [comment]
In my opinion, I believe that these requests are a bit too specific and difficult to create. @thunsaker, you've done a greate job with the only one that could be easily represented. I mean, you could use an oval for rice and a circle for soybean.

**Comment by agustinsivoplas** [comment]
Agreed with @MrGrigri you did a great work @thunsaker

**Comment by thunsaker** [comment]
@JamesCoyle are you thinking that the leaves should overlap more? or have a sharper angle?

@MrGrigri, @agustinsivoplas: We *could* leverage the [`barrel`](https://materialdesignicons.com/icon/barrel) icon, by removing the oil symbol, it could be repurposed for any commodity. Wheat can be transported in barrels/drums, right?

I was also thinking some kind of gunny sack or bag could represent large quantities of rice/wheat/grain/whatever without specifying the contents with a symbol.

I threw this together in like 5 mins, so, please be kind. 😃 
![commodity-sack](https://user-images.githubusercontent.com/137686/27142755-ebe95a1a-50e0-11e7-86df-c076670a8f84.png)

![commodity-sack-24](https://user-images.githubusercontent.com/137686/27142763-ee74f1d6-50e0-11e7-9de9-103985d19bfd.png)
24px

**Comment by JamesCoyle** [comment]
I feel like the angle becomes too acute. Should create a shallower V IMO.

**Comment by thunsaker** [comment]
@JamesCoyle made a few alterations to the husks as well as the kernel lines
<img width="1124" alt="screen shot 2017-06-15 at 10 53 48" src="https://user-images.githubusercontent.com/137686/27194827-f3e6f6b8-51b8-11e7-8274-99c18a0b3a4f.png">
I'm leaning toward 7 now 

![corn-husk-1-small](https://user-images.githubusercontent.com/137686/27195043-f17f8592-51b9-11e7-9aa9-bb415fa38774.png)
6 @24px

![corn-husk-2-small](https://user-images.githubusercontent.com/137686/27195051-fc35223a-51b9-11e7-9ca0-5f3950324630.png)
7 @24px

**Comment by JamesCoyle** [comment]
I think 7 is pretty spot on. Feels more geometric.

**Comment by thunsaker** [comment]
I cleaned it up a little bit, here it is on a grid.
<img width="656" alt="screen shot 2017-06-15 at 12 53 35" src="https://user-images.githubusercontent.com/137686/27199139-cbbaa6c4-51c9-11e7-8bae-e97c2ad80d4b.png">

Here's the "final" image and svg: 
[corn2.zip](https://github.com/Templarian/MaterialDesign/files/1078856/corn2.zip)

**Comment by Alekhen** [comment]
How about this for rice?

![rice](https://user-images.githubusercontent.com/1837101/27244890-e811c942-52a5-11e7-8a56-ecb579012d93.png)

![rice-24](https://user-images.githubusercontent.com/1837101/27244921-12f2dee4-52a6-11e7-96d7-a58418caa6be.png)

[rice.svg.zip](https://github.com/Templarian/MaterialDesign/files/1081959/rice.svg.zip)

**Comment by Alekhen** [comment]
I don't know how you could do an icon to represent soy without it looking like peas or beans. I created this icon representing soy sauce which could be used in an abstract way to represent soy as a commodity.

![soy](https://user-images.githubusercontent.com/1837101/27245961-a4e59616-52ab-11e7-8f84-c95764aa68e8.png)

![soy-24](https://user-images.githubusercontent.com/1837101/27245964-aa2df0d2-52ab-11e7-9da4-b18f01164604.png)

[soy.svg.zip](https://github.com/Templarian/MaterialDesign/files/1082020/soy.svg.zip)

**Comment by thunsaker** [comment]
I'm back! What are we waiting for? 😃

**Comment by Templarian** [comment]
[![rice](https://materialdesignicons.com/icon/rice)](https://materialdesignicons.com/icon/rice) [![soy-sauce](https://materialdesignicons.com/icon/soy-sauce)](https://materialdesignicons.com/icon/soy-sauce) [![corn](https://materialdesignicons.com/icon/corn)](https://materialdesignicons.com/icon/corn)

**Comment by Templarian** [comment]
@thunsaker Don't forget to simplify icons to a single path when uploading for contribution. Takes me a minute more when adding them to remove extra point data.

@Alekhen Let me know when you reach 5 icons in the system by opening an issue so I can create a contributor account.

**Comment by Templarian** [comment]
Might be useful to look into this, but I think it's fine in context with an application. More of a localization issue for developers to deal with if we can't find a nice representation. 🍚
