### ISSUE TITLE
Ballot icon

### ISSUE THREAD

**Issue by stfield** [Templarian/MaterialDesign#2149]
I was working with some other icons from the site, and created a ballot (or vote) icon using the google wallet membership icon as a basis. I wasn't able to find one (unless I just missed an obvious alias) in the collection so I thought that I'd post it here (as an illustrator-editable pdf) if you wanted to add it.

[ballot.zip](https://github.com/Templarian/MaterialDesign/files/1082486/ballot.zip)

**Comment by PeterShaggyNoble** [comment]
See also: `how to vote` from Google's Material Icons Extended set.

![how to vote](https://user-images.githubusercontent.com/15157491/36143159-37020520-10a2-11e8-8b0e-4b7e608e3674.png)

**Comment by Templarian** [comment]
[![ballot](https://materialdesignicons.com/icon/ballot)](https://materialdesignicons.com/icon/ballot) [![ballot-outline](https://materialdesignicons.com/icon/ballot-outline)](https://materialdesignicons.com/icon/ballot-outline) [![vote](https://materialdesignicons.com/icon/vote)](https://materialdesignicons.com/icon/vote) [![vote-outline](https://materialdesignicons.com/icon/vote-outline)](https://materialdesignicons.com/icon/vote-outline)
