### ISSUE TITLE
Google plus box size

### ISSUE THREAD

**Issue by StephaneRob** [Templarian/MaterialDesign#2150]
google-plus-box is bigger than other social icons (box version).

<img width="304" alt="screen shot 2017-06-12 at 10 04 57" src="https://user-images.githubusercontent.com/4135765/27024427-c50d2196-4f56-11e7-977a-0b4c9bd1a6ce.png">

**Comment by Templarian** [comment]
Good catch, marking as high priority to fix before the next release.

**Comment by Templarian** [comment]
Fixed!

[![google-plus-box](https://materialdesignicons.com/icon/google-plus-box)](https://materialdesignicons.com/icon/google-plus-box)

**Comment by StephaneRob** [comment]
Will it be in the next release?

**Comment by Templarian** [comment]
@StephaneRob Yes, which should be shortly, just refectoring the build to drop support for legacy devices/browsers in `2.x`.
