### ISSUE TITLE
Document-Edit / Contract

### ISSUE THREAD

**Issue by ricardorado9** [Templarian/MaterialDesign#2151]
Something related to a contract between two parts

**Comment by shroudedcode** [comment]
@ricardorado9 Something like this?

![](https://cdn0.iconfinder.com/data/icons/files-documents/512/YPS__file_document_to_sign_signature_signed_sign_sheet_contract_paper_page_text-512.png)

**Comment by ricardorado9** [comment]
yeah

**Comment by GreenTurtwig** [comment]
![puush-linux 2017-06-22 at 11 26 11](https://user-images.githubusercontent.com/15905797/27429661-c28345ce-573d-11e7-8b37-5246644938e3.png)
![puush-linux 2017-06-22 at 11 26 19](https://user-images.githubusercontent.com/15905797/27429663-c45b581e-573d-11e7-8222-fa39112adffb.png)
[contract.zip](https://github.com/Templarian/MaterialDesign/files/1094432/contract.zip)

**Comment by MrGrigri** [comment]
Idk if that is within the guidelines for MD. They say "don’t break the container’s boundary with elements". So those two lines cannot extend to the edge like that.

**Comment by GreenTurtwig** [comment]
Also should probable name it `document edit`, and give the alias `contract`.

**Comment by JamesCoyle** [comment]
The guidelines don't actually state anything that would deal with this case: a modifier icon intersecting the main icon. The cut out area isn't actually the container boundary so that rule doesn't really apply. In this case I prefer the first option as it doesn't affect the original icon as much.

**Comment by GreenTurtwig** [comment]
Here's another revised version:
![puush-linux 2017-06-23 at 09 17 57](https://user-images.githubusercontent.com/15905797/27472859-f4127918-57f4-11e7-9efa-947ec3651c6a.png)
![puush-linux 2017-06-23 at 09 18 10](https://user-images.githubusercontent.com/15905797/27472862-f59dea7e-57f4-11e7-83c8-5c77b3e1f49e.png)
[contract2.zip](https://github.com/Templarian/MaterialDesign/files/1097183/contract2.zip)
I actually prefer the second one to be honest. :-/
Would be good to get some more opinions on these designs.

**Comment by JamesCoyle** [comment]
Can the pencil be moved to the bottom corner any more than it is? Might be a case where we utilize the 2px border for added detail.

**Comment by GreenTurtwig** [comment]
I could move it down by one, but it just makes it look worse in my opinion, I tried a few different pencil positions before.
![puush-linux 2017-06-23 at 11 14 27](https://user-images.githubusercontent.com/15905797/27477862-6543b4c0-5805-11e7-8bd8-a154c138b461.png)
![puush-linux 2017-06-23 at 11 14 35](https://user-images.githubusercontent.com/15905797/27477865-67009b84-5805-11e7-89ed-c6ef4477c8d7.png)
![puush-linux 2017-06-23 at 11 15 10](https://user-images.githubusercontent.com/15905797/27477868-68af3f08-5805-11e7-9f9c-5cb28fff3b24.png)

**Comment by ricardorado9** [comment]
This design would also be interesting

![image](https://user-images.githubusercontent.com/20613795/27484630-8b11b96a-57ef-11e7-95f7-5cdd529535a3.png)

**Comment by MrGrigri** [comment]
The handshake it too detailed and would be lost in the corner of the icon like that. Remember that these have to be recognizable at a 24x24 pixel size. I don't even think that a handshake is even possible with MD standards by itself at that size.

**Comment by Templarian** [comment]
[![file-document-edit](https://materialdesignicons.com/icon/file-document-edit)](https://materialdesignicons.com/icon/file-document-edit)
