### ISSUE TITLE
Wedding Ring

### ISSUE THREAD

**Issue by coolmyll** [Templarian/MaterialDesign#2152]
A material design wedding ring icon would be nice

http://images.clipartpanda.com/wedding-ring-clipart-db0ff6e293b94596811d85f5795a2e9f_p_400.png

**Comment by Alekhen** [comment]
How about something like this?
![diamond-ring](https://user-images.githubusercontent.com/1837101/27094961-350dcf90-5029-11e7-868b-a1f45a0c880b.png)
[diamond-ring.svg.zip](https://github.com/Templarian/MaterialDesign/files/1072262/diamond-ring.svg.zip)

**Comment by Alekhen** [comment]
Here's an alternate version.
![diamond-ring-alt](https://user-images.githubusercontent.com/1837101/27095118-d5ae079e-5029-11e7-94c7-0b6d55ee57db.png)
[diamond-ring-alt.svg.zip](https://github.com/Templarian/MaterialDesign/files/1072268/diamond-ring-alt.svg.zip)

**Comment by MrGrigri** [comment]
I believe that the outline would get lost at 24x24. Very good though.

**Comment by coolmyll** [comment]
Nice and clean. Will check about the size when I get home.

**Comment by Templarian** [comment]
@Alekhen Let me know when you hit 5 icons and I'll create/transfer this to a contributor account.

[![ring](https://materialdesignicons.com/icon/ring)](https://materialdesignicons.com/icon/ring)
