### ISSUE TITLE
Nintendo Switch

### ISSUE THREAD

**Issue by ViperRNMC** [Templarian/MaterialDesign#2153]
Hi, i like to request a nintendo switch icon.

**Comment by GreenTurtwig** [comment]
![puush-linux 2017-06-13 at 10 57 04](https://user-images.githubusercontent.com/15905797/27077214-398f0d1a-5027-11e7-8506-2c1696c5b342.png)
![puush-linux 2017-06-13 at 10 57 10](https://user-images.githubusercontent.com/15905797/27077215-399877a6-5027-11e7-90a5-8bf481400dd1.png)
[nintendo-switch.zip](https://github.com/Templarian/MaterialDesign/files/1070980/nintendo-switch.zip)
Here we go. :cat:

**Comment by ViperRNMC** [comment]
nice!

**Comment by Templarian** [comment]
[![nintendo-switch](https://materialdesignicons.com/icon/nintendo-switch)](https://materialdesignicons.com/icon/nintendo-switch)

Due to the "switch" name I kept the prefix `nintendo-` as suggested.

**Comment by PeterShaggyNoble** [comment]
Should `wii` & `wiiu` be renamed with the `nintendo-` prefix, so, for consistency?
