### ISSUE TITLE
send-circle

### ISSUE THREAD

**Issue by cachapa** [Templarian/MaterialDesign#2154]
This is a simple merge of the "send" arrow inside a filled circle.
I needed it for a project and was surprised to learn that it doesn't exist yet, so I made my own.

[send-circle.zip](https://github.com/Templarian/MaterialDesign/files/1071996/send-circle.zip)

**Comment by JamesCoyle** [comment]
The SVG you attached is just the send arrow.

**Comment by cachapa** [comment]
Sorry /facepalm

[send-circle.zip](https://github.com/Templarian/MaterialDesign/files/1073697/send-circle.zip)

**Comment by CoDEmanX** [comment]
Maybe the send symbol is a tiny bit too small?

![image](https://user-images.githubusercontent.com/1309249/38771027-0d5eb2e6-401c-11e8-85c9-df6ea866c9ac.png)

**Comment by Templarian** [comment]
Added `send-circle` and `send-circle-outline`.
