### ISSUE TITLE
ESL icon

### ISSUE THREAD

**Issue by wildramen** [Templarian/MaterialDesign#2155]
Clear brand guidelines: https://www.eslgaming.com/brand

![esl_styleguide_2015_logo](https://user-images.githubusercontent.com/21983456/27093410-3c1301de-506f-11e7-864e-e2f1a6ed0257.jpg)

**Comment by JamesCoyle** [comment]
I'm kinda edging towards this being too obscure.

**Comment by Templarian** [comment]
Yea, this is going to be to specific for this icon pack. Marking as a brand icon / rejected so we can reference it later if we create a brand icon pack in the future.
