### ISSUE TITLE
cannabis leaf

### ISSUE THREAD

**Issue by campsafari** [Templarian/MaterialDesign#2157]
giving the momentum legalization is taking place and more and more apps, websites etc will be built in this context it would be nice to have it as a part of this awesome lib

**Comment by Templarian** [comment]
I think I already made this somewhere will look around and add it.

**Comment by Templarian** [comment]
[![cannabis](https://materialdesignicons.com/icon/cannabis)](https://materialdesignicons.com/icon/cannabis)
