### ISSUE TITLE
Mushroom icon

### ISSUE THREAD

**Issue by chris-thorn** [Templarian/MaterialDesign#2158]
First submission - please let me know if format is incorrect!

Do I need to list aliases as well?

# Mushroom

![mushroom](https://user-images.githubusercontent.com/3541291/27183945-6a95bd52-51d8-11e7-9d79-12caaf10bc7f.png)

[mushroom.svg.zip](https://github.com/Templarian/MaterialDesign/files/1077782/mushroom.svg.zip)

**Comment by JamesCoyle** [comment]
I think we could use a mario style button mushroom with and without spots. This looks great but is just a bit to detailed to fit in with the rest of the icons IMO. Generally curves are kept as simple as possible and spots are circular.

**Comment by chris-thorn** [comment]
Thanks for the feedback!

I'll have another go and resubmit something soon :-)

Chris

---- On Thu, 15 Jun 2017 16:58:27 +0100 notifications@github.com wrote ----

I think we could use a mario style button mushroom with and without spots. This looks great but is just a bit to detailed to fit in with the rest of the icons IMO. Generally curves are kept as simple as possible and spots are circular.

**Comment by JamesCoyle** [comment]
Awesome. :) It looks fantastic and would be great as a logo for something but it's just a bit too detailed to fit in with the material icons. If you haven't already it's probably worth reading the [icon guidelines](https://material.io/guidelines/style/icons.html#icons-system-icons).

**Comment by chris-thorn** [comment]
Hi, I've had another go!

I must admit I'd not looked at the icon guidelines you linked to, but I've tried to follow them with this set of icons.

Any comments?

## mushroom
![mushroom](https://user-images.githubusercontent.com/3541291/27220027-96cdda46-527b-11e7-832d-2375b16ab1c2.png)

## mushroom-spot
![mushroom-spot](https://user-images.githubusercontent.com/3541291/27220035-9a1b9350-527b-11e7-963c-555442dac7ae.png)

## mushroom-o
![mushroom-o](https://user-images.githubusercontent.com/3541291/27220037-9c133ca8-527b-11e7-8c4e-24079edb955d.png)

## mushroom-spot-o
![mushroom-spot-o](https://user-images.githubusercontent.com/3541291/27220045-a0aaa256-527b-11e7-98aa-813aaec73572.png)

[mushroom.svg.zip](https://github.com/Templarian/MaterialDesign/files/1080297/mushroom.svg.zip)
[mushroom-spot.svg.zip](https://github.com/Templarian/MaterialDesign/files/1080298/mushroom-spot.svg.zip)
[mushroom-o.svg.zip](https://github.com/Templarian/MaterialDesign/files/1080296/mushroom-o.svg.zip)
[mushroom-spot-o.svg.zip](https://github.com/Templarian/MaterialDesign/files/1080299/mushroom-spot-o.svg.zip)

**Comment by MrGrigri** [comment]
I don't know how I feel about the dot. But the filled-in and outline versions I like.

**Comment by chris-thorn** [comment]
Yeah I'm not sure about the version with the spot. Probably just makes the icon somewhat unclear at low resolutions.

**Comment by JamesCoyle** [comment]
It could do with two or three spots really.

**Comment by chris-thorn** [comment]
OK, what about these for the one with spots?

In trying to maintain a 2px stroke width, the positions of the spots differ between the solid and outline versions.

## mushroom-spot
![mushroom-spot](https://user-images.githubusercontent.com/3541291/27373680-253cc0b0-5661-11e7-8a32-3e553b6761f8.png)

## mushroom-spot-o
![mushroom-spot-o](https://user-images.githubusercontent.com/3541291/27373686-27e32ee4-5661-11e7-9dab-9c35e815ad1f.png)

[mushroom-spot.svg.zip](https://github.com/Templarian/MaterialDesign/files/1090757/mushroom-spot.svg.zip)
[mushroom-spot-o.svg.zip](https://github.com/Templarian/MaterialDesign/files/1090758/mushroom-spot-o.svg.zip)

Chris

**Comment by MrGrigri** [comment]
I believe that is better, but could be even better. What about circles that are not the same size and not mirroring each other?

**Comment by chris-thorn** [comment]
... and this is where my complete lack of artistic vision comes to the fore!

I think I'm just getting hung up on my interpretation of the [Material Design icon guidelines](https://material.io/guidelines/style/icons.html#icons-system-icons) - I don't want to make features that are too fine and fiddly, but sticking to heavy geometric 2px-wide strokes etc means I keep sacrificing detail.

But I'll have another go later and produce a couple more ideas!

**Comment by MrGrigri** [comment]
Yeah, MD guidelines are quite tricky and icons are more abstract than concrete. Good luck.

**Comment by Templarian** [comment]
Yea, I think the latest ones above work good, they don't look like lamps. 😄 

[![mushroom](https://materialdesignicons.com/icon/mushroom)](https://materialdesignicons.com/icon/mushroom) [![mushroom-outline](https://materialdesignicons.com/icon/mushroom-outline)](https://materialdesignicons.com/icon/mushroom-outline)

@chris-thorn I simplified the path count and assigned them to the contributor account. Once you have 5 icons in the system please let me know.
