### ISSUE TITLE
It would be great to have the following icons developed

### ISSUE THREAD

**Issue by sukhrobik** [Templarian/MaterialDesign#2159]
Animals, Antiques, Apartments, Appliances, Auto Parts, Auto Services, Autos, Clothing, Electronics, Food, Free Stuff, Furniture, General Stuff, Home & Garden, Home Services, Jewelry, Jobs, Media, Music, Real Estate, Services, Sports, Tickets, Tools, Toys & Games, Boat, RV.

**Comment by shroudedcode** [comment]
@sukhrobik I don't think your list is of great use to the team. The suggestions are way too vague and some of these categories don't even make sense, what do you mean by "Free Stuff" and "General Stuff"? How to represent "Jobs"? What do you mean by "Autos"? Different car models? I mean, we already have quite a few vehicle icons including `car`, `bus`, `truck`, etc. Some categories are also too niche to be included, like "Auto Parts" and "Jewelry".

Icon suggestions are much more useful when they address a specific single icon with examples, links to their particular brand guideline pages (in the case of a brand icon), possible use cases and maybe also a sketch of how you imagine the icon to look like.

Your list isn't even a list of icons, it's a list of categories and simply posting it here and expecting the developers to just make them seems a bit sullen in my opinion. Remember that these are volunteers working on this project which everyone can use for free.

**Comment by JamesCoyle** [comment]
We already have icons for a lot of things you have listed. There are issues for other things currently waiting for submissions too. First search our currently available icons for what you need. If you can't find anything try searching the issues here for a similar icon and post your own issue for a **specific icon** if it hasn't yet been requested.

**Comment by JamesCoyle** [comment]
#2103 and #2104 are somewhat relevant here but you still need to open an issue for each icon so we can track it's progress.

**Comment by Templarian** [comment]
Thanks @JamesCoyle was going to close this earlier but in meetings all morning.

As said these need to be separated into separate issues so they can be tracked easier (it also makes grouping duplicate requests easier).
