### ISSUE TITLE
instruments, rocket

### ISSUE THREAD

**Issue by bobrocke** [Templarian/MaterialDesign#216]
Speedometer

- Automobile instrument cluster
- [x] Rocketship

Disk platter stack (to symbolize a database)

**Comment by Templarian** [comment]
Two of these already exist:
http://materialdesignicons.com/icon/speedometer
http://materialdesignicons.com/icon/database (search database there are others)

**Comment by bobrocke** [comment]
Cool. But I didn't know I could search. How?

**Comment by bobrocke** [comment]
Never mind. I found the fairly obvious search icon. Duh.

**Comment by Templarian** [comment]
Or CTRL+F. :smile: 

The contributors will try and add the others.

**Comment by Templarian** [comment]
I added the [rocket](http://materialdesignicons.com/icon/rocket), but 'Automobile instrument cluster' is going to have too much detail for the small icons size.
