### ISSUE TITLE
New Icons Request/Contribution: Political Party Elephant & Donkey

### ISSUE THREAD

**Issue by vcantu** [Templarian/MaterialDesign#2162]
Hi, I'm working on a couple of icons for an app I am working on involving politics.

Here is the elephant scaled up:
![elephant](https://user-images.githubusercontent.com/13156162/27216064-1e2be94a-5242-11e7-9c5a-f57c6ab95031.png)
Elephant 24px
![elephant_24px](https://user-images.githubusercontent.com/13156162/27216100-414665a4-5242-11e7-85c4-0254632ad3ae.png)

Here is the donkey scaled up:
![donkey](https://user-images.githubusercontent.com/13156162/27216118-4d4f8c36-5242-11e7-8d8c-1bb9dc46be9d.png)
Donkey 24px
![donkey_24px](https://user-images.githubusercontent.com/13156162/27216125-557389e4-5242-11e7-9f37-6d6f51db6e40.png)

P.S. - I've never contributed here before so I'm unfamiliar with the process

**Comment by MrGrigri** [comment]
Just add the svg file here (you'll have to zip it). And it's always nice if you can remove redundant points. But that's it. I like these a lot.

**Comment by vcantu** [comment]
Thanks! here is the zip file
[donkey&elephant.zip](https://github.com/Templarian/MaterialDesign/files/1081352/donkey.elephant.zip)

**Comment by Templarian** [comment]
[![elephant](https://materialdesignicons.com/icon/elephant)](https://materialdesignicons.com/icon/elephant) [![donkey](https://materialdesignicons.com/icon/donkey)](https://materialdesignicons.com/icon/donkey)

@vcantu Assigned to the contributor account, let me know when you hit 5 icons in the system.
