### ISSUE TITLE
New Icons Request: Email Sent | Email Received | Email User Request

### ISSUE THREAD

**Issue by madEng84** [Templarian/MaterialDesign#2163]
I think these can be useful, not only for me
Suddently I'm not familiar with Illustrator, Photoshop 

![schermata 2017-06-16 alle 12 05 04](https://user-images.githubusercontent.com/2088831/27222316-1442c008-528c-11e7-9d70-1ac29da27ad6.png)
![schermata 2017-06-16 alle 12 05 00](https://user-images.githubusercontent.com/2088831/27222315-143d2b0c-528c-11e7-8a3a-eed09b5bbd54.png)

**Comment by MrGrigri** [comment]
Here is my attempt at some email actions. 

![email-receive](https://user-images.githubusercontent.com/4528551/27805124-efb98728-5fef-11e7-8c9e-9c6cad96cfbb.png) ![email-send](https://user-images.githubusercontent.com/4528551/27805125-efc118da-5fef-11e7-913a-614cb5c8da12.png)

[email-actions.zip](https://github.com/Templarian/MaterialDesign/files/1120371/email-actions.zip)

**Comment by PeterShaggyNoble** [comment]
Would any of the [`inbox-*` icons](http://mdi.houseofdesign.ie/?search=inbox) work for you for sent/received? And how about `contact-mail` for "email user"?

[![](https://materialdesignicons.com/icon/contact-mail)](https://materialdesignicons.com/icon/contact-mail)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @madEng84, if the suggested icons don't suit your needs, let us know and we'll revisit this issue.

**Comment by CoDEmanX** [comment]
Related: https://github.com/Templarian/MaterialDesign/issues/1004#issuecomment-175068022

**Comment by madEng84** [comment]
They are perfect but i don't need them anymore
