### ISSUE TITLE
Necklace Icon

### ISSUE THREAD

**Issue by emanf** [Templarian/MaterialDesign#2165]
#2118
example: https://cdn1.iconfinder.com/data/icons/jewery/500/necklace-512.png

**Comment by MrGrigri** [comment]
Here is my attempt. 

![necklace](https://user-images.githubusercontent.com/4528551/27875926-4841f01e-6172-11e7-9b50-6c1cd56c5b9e.png)

[necklace.zip](https://github.com/Templarian/MaterialDesign/files/1125438/necklace.zip)

**Comment by PeterShaggyNoble** [comment]
Would a string of pearls be more immediately recognisable? Probably wouldn't work under MD guidelines, though.

**Comment by MrGrigri** [comment]
Idk, I believe this is an icon that needs to be in context, and more than likely would be.

**Comment by goyney** [comment]
Added! 😄
