### ISSUE TITLE
Fruit Icon

### ISSUE THREAD

**Issue by emanf** [Templarian/MaterialDesign#2166]
#2118 
example: https://www.shareicon.net/data/512x512/2015/12/30/695523_food_512x512.png
or combination of some other fruit.

**Comment by MrGrigri** [comment]
Will the apple icon not work?

![foot-apple](https://materialdesignicons.com/icon/food-apple)

**Comment by emanf** [comment]
the apple will work kind of but what i need for my purpose combination of some fruit

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52747770-a7f44b00-2fb2-11e9-98bf-55eadbf8dbbb.png)![image](https://user-images.githubusercontent.com/1015040/52747786-b17db300-2fb2-11e9-89d8-d3e5be2e4a6b.png)
![image](https://user-images.githubusercontent.com/1015040/52747795-b93d5780-2fb2-11e9-9eb6-4414293d3cd0.png)![image](https://user-images.githubusercontent.com/1015040/52747804-bfcbcf00-2fb2-11e9-813a-7004727baf28.png)
![image](https://user-images.githubusercontent.com/1015040/52747826-c8bca080-2fb2-11e9-868a-9154be8aa411.png)![image](https://user-images.githubusercontent.com/1015040/52747840-cfe3ae80-2fb2-11e9-873d-cf884fa76074.png)

[fruit.zip](https://github.com/Templarian/MaterialDesign/files/2862427/fruit.zip)

**Comment by MrGrigri** [comment]
I believe the cherries should just be round.

**Comment by goyney** [comment]
Updated.

**Comment by JapanYoshi** [comment]
I personally have never seen a cherry with (or represented with) leaves on the end of the stem. Remove them?
Also, the lemon has a distinct enough shape that the slice probably isn't necessary.

**Comment by CoDEmanX** [comment]
The lemon looks a bit squeezed to me, make make it bit rounder?

**Comment by goyney** [comment]
The nubs get lost a native size and it is not totally clear what it is, the slice helps define that.

Also, it was model from a picture of a lime, so that is the correct ratios.

**Comment by PeterShaggyNoble** [comment]
Could the circles of the cherries be a little bit bigger?

**Comment by CoDEmanX** [comment]
Why do the circles look distored, especially in the outline variant of graphs?

**Comment by goyney** [comment]
Erm, that's a good question. I will fix that shortly.

**Comment by goyney** [comment]
@CoDEmanX Export rounding error. Thanks for the catch, it's fixed.

**Comment by JamesCoyle** [comment]
I especially like the `folder-zip-outline` fruit! Great stuff!

The cutout on the left cherry doesn't look quite right to me. Shouldn't the glossy highlights also have squared ends not rounded?

**Comment by goyney** [comment]
D'oh. 😆 

There are several other icons in which we show a gloss that uses the round ends. Considering the object is round, I think it makes more sense. But, I can do a pass with square ends to see how it looks.

The cutout is a 2dp stroke off the right cherry. Do you have a suggestion on what else to try there?

**Comment by JamesCoyle** [comment]
For some reason it just doesn't seem like it follows the curve of the right one. What if you move the cherries slightly closer?

**Comment by goyney** [comment]
Here's some new cherry variations based on the cherries being closer together:

![image](https://user-images.githubusercontent.com/1015040/61308491-61538880-a7be-11e9-91e2-7d1bf44103fb.png)![image](https://user-images.githubusercontent.com/1015040/61308505-67e20000-a7be-11e9-97a3-2273b37d520c.png)
![image](https://user-images.githubusercontent.com/1015040/61308522-6e707780-a7be-11e9-8c4f-41c9254d34f2.png)

[more-cherries.zip](https://github.com/Templarian/MaterialDesign/files/3397894/more-cherries.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61314286-5868b400-a7ca-11e9-80cd-53993bcdbdf9.png)
[fruit-cherries-awesome.svg.zip](https://github.com/Templarian/MaterialDesign/files/3398240/fruit-cherries-awesome.svg.zip)

**Comment by JamesCoyle** [comment]
I like that one a lot more. Good job! 😁

**Comment by goyney** [comment]
[![fruit-cherries](https://materialdesignicons.com/icon/fruit-cherries)](https://materialdesignicons.com/icon/fruit-cherries)
[![fruit-citrus](https://materialdesignicons.com/icon/fruit-citrus)](https://materialdesignicons.com/icon/fruit-citrus)
[![fruit-grapes](https://materialdesignicons.com/icon/fruit-grapes)](https://materialdesignicons.com/icon/fruit-grapes)
[![fruit-grapes-outline](https://materialdesignicons.com/icon/fruit-grapes-outline)](https://materialdesignicons.com/icon/fruit-grapes-outline)
[![fruit-pineapple](https://materialdesignicons.com/icon/fruit-pineapple)](https://materialdesignicons.com/icon/fruit-pineapple)
[![fruit-watermelon](https://materialdesignicons.com/icon/fruit-watermelon)](https://materialdesignicons.com/icon/fruit-watermelon)
