### ISSUE TITLE
Cloth Icon

### ISSUE THREAD

**Issue by emanf** [Templarian/MaterialDesign#2168]
#2118 
example1: http://durableroofingsolutions.com/wp-content/uploads/2017/03/001-roll.svg
example2:https://housecare.tokyo/assets/towels-32d9ddb542f8e2156127fced76b9a3e1586011519bcb5c21d0201e4aead2f674.png

**Comment by PeterShaggyNoble** [comment]
Could you elaborate on your use case for these? The perspective in your examples violates the MD guidelines but without the perspective, they're probably not identifiable. Some context could help with the creation of alternatives.

**Comment by emanf** [comment]
i have an app that contains a lot of shops, i want to show my users those shops with certain icon, the shop that selling only cloths or ..., i can't use STORE icon for all of them so i need this icon for it

**Comment by MrGrigri** [comment]
Would #2227 work?

**Comment by emanf** [comment]
> Would #2227 work?
i need something more specific for my purpose, it kind of hard to recognize

**Comment by PeterShaggyNoble** [comment]
[Here](https://icons8.com/icon/7215/cloth)'s Icons8's cloth icon for reference. To me, #2227 would better communicate a cloth shop. To trow a few other ideas out there, would a pair of scissors (which we already have), a sewing machine or a mannequin work?

[![](https://materialdesignicons.com/icon/content-cut/)](https://materialdesignicons.com/icon/content-cut/)

**Comment by emanf** [comment]
@PeterShaggyNoble 
[Here](https://icons8.com/icon/30722/polishing-cloth)'s Icons8's polishing cloth icon. (what i need)
i already used this cutter icon for Barber shop :)

**Comment by MrGrigri** [comment]
The problem with using a bold of fabric is it has to have perspective, thus violating [MD Guidelines](https://material.io/guidelines/style/icons.html#icons-system-icons). 

![image](https://user-images.githubusercontent.com/4528551/31448867-b218cdfe-ae62-11e7-9de6-82521d99dda0.png)

**Comment by emanf** [comment]
> The problem with using a bold of fabric is it has to have perspective, thus violating MD Guidelines.

oh, i forgot about that.
what about something like [this](https://thumb9.shutterstock.com/display_pic_with_logo/2696557/532053412/stock-vector-towel-red-flat-icon-on-white-background-532053412.jpg)? (without flower)

**Comment by CoDEmanX** [comment]
Example for mannequin from #873:

![grafik](https://user-images.githubusercontent.com/1309249/38640429-869aeade-3dd4-11e8-914d-8ba9a0aac070.png)

**Comment by steodor** [comment]
Hi @emanf, i know it's an old issue and basically your initial request cannot be integrated as-is, but i found something close: [https://thenounproject.com/term/dish-cloth/](https://thenounproject.com/term/dish-cloth/). So, would this work?
![image](https://user-images.githubusercontent.com/4397338/108392981-dfd69e80-721b-11eb-8ad2-c83df064923b.png)
[dish-cloth.zip](https://github.com/Templarian/MaterialDesign/files/6004565/dish-cloth.zip)

**Comment by goyney** [comment]
I think `receipt` without the text lines would be perfect for this.

[![receipt](https://materialdesignicons.com/icon/receipt)](https://materialdesignicons.com/icon/receipt)

I think we should:
- [ ] Rename `receipt` to `receipt-text`.
- [ ] Add a new version without the text lines.
- [ ] Alias the new `receipt` with `cloth`.

**Comment by goyney** [comment]
Completed.
