### ISSUE TITLE
Carpet Icon

### ISSUE THREAD

**Issue by emanf** [Templarian/MaterialDesign#2169]
#2118 
example1: https://d30y9cdsu7xlg0.cloudfront.net/png/122408-200.png
example2: http://www.steamatic.ca/images/icon-carpet-cleaning-nettoyage-tapis.png
example3: https://maxcdn.icons8.com/Share/icon/Household//carpet1600.png

**Comment by MrGrigri** [comment]
How about this?

![carpet](https://user-images.githubusercontent.com/4528551/27797456-fb4ab64a-5fca-11e7-8cc0-12212887cf68.png)


[carpet.zip](https://github.com/Templarian/MaterialDesign/files/1119888/carpet.zip)

**Comment by emanf** [comment]
> How about this?

it is really nice.

**Comment by CoDEmanX** [comment]
At 24 pixels, it kinda looks like a piece of wood or metal with toothing and a nut symbol in the center 😕

**Comment by MrGrigri** [comment]
I believe this icon would have to be consumed in-context.

**Comment by Templarian** [comment]
Agreed, should it be rotated?

**Comment by goyney** [comment]
[![rug](https://materialdesignicons.com/icon/rug)](https://materialdesignicons.com/icon/rug)
