### ISSUE TITLE
Pipe Icon

### ISSUE THREAD

**Issue by emanf** [Templarian/MaterialDesign#2171]
#2118
example1: https://d30y9cdsu7xlg0.cloudfront.net/png/61289-200.png
example2: https://d30y9cdsu7xlg0.cloudfront.net/png/582275-200.png

**Comment by JamesCoyle** [comment]
I like the U-bend idea as it seems like it would be most recognisable as a pipe. Would also maybe help with #2104 as an icon to represent plumbers.

**Comment by MrGrigri** [comment]
Here are two that I came up with; connected and disconnected. 

![pipe-disconnect](https://user-images.githubusercontent.com/4528551/27393117-9c5c9892-5665-11e7-8362-d7bc861274c2.png) ![pipe-connect](https://user-images.githubusercontent.com/4528551/27393118-9c69281e-5665-11e7-84d2-5620631ccff6.png)

[pipe.zip](https://github.com/Templarian/MaterialDesign/files/1092052/pipe.zip)

**Comment by Templarian** [comment]
[![pipe](https://materialdesignicons.com/icon/pipe)](https://materialdesignicons.com/icon/pipe) [![pipe-disconnected](https://materialdesignicons.com/icon/pipe-disconnected)](https://materialdesignicons.com/icon/pipe-disconnected)
