### ISSUE TITLE
School Building icon

### ISSUE THREAD

**Issue by jsingh-jasmeet** [Templarian/MaterialDesign#2173]

**Comment by GreenTurtwig** [comment]
Would [domain](https://materialdesignicons.com/icon/domain) do? Or do you need something more specific.

**Comment by jsingh-jasmeet** [comment]
Hey,

Sorry for the late reply. Just lost this mail in a bunch of emails. On
second thought, domain does seem fine. I can work with that. Thank you very
much.

**Comment by Alekhen** [comment]
What are your thoughts on these? I think the double doors make them feel more like public buildings.

Elementary school with 1 door:
![elementary-school-1-24](https://user-images.githubusercontent.com/1837101/30844374-01b10322-a24c-11e7-9107-a795f0eab1dc.png)
![elementary-school-1](https://user-images.githubusercontent.com/1837101/30844380-08673f10-a24c-11e7-8a61-39fe4ad5a60e.png)

Elementary school with 2 doors:
![elementary-school-2-24](https://user-images.githubusercontent.com/1837101/30844413-21efcbe6-a24c-11e7-8895-18d8f5ee189a.png)
![elementary-school-2](https://user-images.githubusercontent.com/1837101/30844424-271713a4-a24c-11e7-87e7-210ba03f6a72.png)

High school with 1 door:
![high-school-1-24](https://user-images.githubusercontent.com/1837101/30844433-3464bda4-a24c-11e7-9e72-35366f1706b7.png)
![high-school-1](https://user-images.githubusercontent.com/1837101/30844435-372db5ea-a24c-11e7-9c20-b96e8b6e0a4b.png)

High school with 2 doors:
![high-school-2-24](https://user-images.githubusercontent.com/1837101/30844440-3f1b1a54-a24c-11e7-83db-c84a0c47cdc8.png)
![high-school-2](https://user-images.githubusercontent.com/1837101/30844443-42b0c51a-a24c-11e7-9714-1ff59d9e0a19.png)

[schools.svg.zip](https://github.com/Templarian/MaterialDesign/files/1331932/schools.svg.zip)

**Comment by PeterShaggyNoble** [comment]
@Alekhen, people outside America wouldn't identify those icons with schools. If you showed them to me without context, my best guesses would be that the first 2 were some sort of military building and the second 2 were, maybe, town halls.

@jsingh-jasmeet, would the `school` icon suit your needs?

[![](https://materialdesignicons.com/icon/school)](https://materialdesignicons.com/icon/school)

**Comment by PeterShaggyNoble** [comment]
Closing this out as the original request was fulfilled by the `domain` icon and we also have the `school` icon.
