### ISSUE TITLE
Wifi signal icons

### ISSUE THREAD

**Issue by onexuan** [Templarian/MaterialDesign#2174]
Request: 4 or 5 kinds of Wifi signal icons, From strong to weak

**Comment by GreenTurtwig** [comment]
Google now appears to have a [similar icon](https://material.io/icons/#ic_wifi) to https://materialdesignicons.com/icon/wifi now. We should probably get that added and shifted to the Google account.

Here are all the variants (including off), all based of the Google design:
[wifi.zip](https://github.com/Templarian/MaterialDesign/files/1089041/wifi.zip)

**Comment by JamesCoyle** [comment]
Can we have transparency based icons to use too? I'm sure we've discussed this at some point. It would be nice to have the full size quarter circle to use as the background and then the smaller quarter circles to swap in to show the signal strength. It would also be great to have the cross and exclamation mark variants too.

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #586.
