### ISSUE TITLE
Bluetooth Battery

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2175]
Something like either of these, perhaps? I'm partial to the first, but other bluetooth icons (like phone and music note) put the BT icon next to the main icon.

![battery_1](https://user-images.githubusercontent.com/18021678/27308467-aea07856-551c-11e7-910e-65f4d660fe6b.png)
![battery_2](https://user-images.githubusercontent.com/18021678/27308469-afec46cc-551c-11e7-9d56-a18c935347c9.png)

Then again, a battery icon next to a headset or speaker icon might also satisfy my needs.

**Comment by GreenTurtwig** [comment]
[battery-bluetooth.zip](https://github.com/Templarian/MaterialDesign/files/1088687/battery-bluetooth.zip)
Ended up using both designs, used the first as a variant, the rest are identical to the charging icons but have the Bluetooth symbol next to them instead. This is very similar to how Apple designed the Bluetooth battery indicator in iOS 10.

**Comment by GreenTurtwig** [comment]
[headphones-speaker-bluetooth.zip](https://github.com/Templarian/MaterialDesign/files/1088706/headphones-speaker-bluetooth.zip)
And here are the headphone and speaker icons with the Bluetooth symbol, could be useful in some situations. We already have a "phone" version, so these should fit well, might be worth getting keyboard and mouse versions done too. :cat2:

**Comment by k5cents** [comment]
These look awesome! Yeah, keyboard and mouse battery indicators could also be super useful.

**Comment by Templarian** [comment]
[![headphones-bluetooth](https://materialdesignicons.com/icon/headphones-bluetooth)](https://materialdesignicons.com/icon/headphones-bluetooth) [![speaker-bluetooth](https://materialdesignicons.com/icon/speaker-bluetooth)](https://materialdesignicons.com/icon/speaker-bluetooth)

**Comment by Templarian** [comment]
http://dev.materialdesignicons.com/history

Would take too long to link all the previews.

**Comment by Templarian** [comment]
[![mouse-bluetooth](https://materialdesignicons.com/icon/mouse-bluetooth)](https://materialdesignicons.com/icon/mouse-bluetooth)

**Comment by kakawait** [comment]
Sorry to revive the thread.

The Bluetooth icon with battery, from my personal point of view, I think battery and bluetooth may be same height? Example from Android icon

![Screenshot_20210626-205849~2](https://user-images.githubusercontent.com/275609/123699071-22aa2200-d85f-11eb-8b38-93f8b4eee996.jpg)

**Comment by Templarian** [comment]
We kept the smaller size to make it consistent across all the bluetooth accessories.

![image](https://user-images.githubusercontent.com/338885/123737558-c77d2d00-d868-11eb-99ee-ee54ebff6be1.png)

**Comment by kakawait** [comment]
> We kept the smaller size to make it consistent across all the bluetooth accessories.
> 
> ![image](https://user-images.githubusercontent.com/338885/123737558-c77d2d00-d868-11eb-99ee-ee54ebff6be1.png)
> 

Sound legit. Thanks for clarification
