### ISSUE TITLE
Money and Payment Icons

### ISSUE THREAD

**Issue by aksth** [Templarian/MaterialDesign#2177]
Money Icons and Payment Icons need

**Comment by GreenTurtwig** [comment]
We already have loads of money related icons, currency symbols, notes, coins, e.t.c.
It would be helpful to know **exactly** what you want. :cat2

**Comment by damianobarbati** [comment]
@GreenTurtwig I agree with @aksth : I mean, I was looking on https://materialdesignicons.com/
for the following:
- money
- coin
- check
- transfer
- transaction
- payment

And I didn't find anything like  💵💰 or anything which seems like an "amount" of money :\

**Comment by JamesCoyle** [comment]
Might need some aliases then. `cash` and `coin` both work fine.

**Comment by PeterShaggyNoble** [comment]
@damianobarbati: See [here](http://mdi.houseofdesign.ie/?category=money).

If there's anything specific you can't find, though, let us know. With examples, if possible.

**Comment by PeterShaggyNoble** [comment]
Yes, although mine is updated a *lot* slower!

**Comment by CoDEmanX** [comment]
Cross-post, because original issue #2501 was closed:

In my online banking, for transactions they use this: ![image](https://user-images.githubusercontent.com/1309249/31473016-5790a0c4-aef2-11e7-8579-79d5e1a82863.png)

**Comment by MrPostie** [comment]
Also the contactless payment icon would be great. It looks like the wifi icon.
![contactless](https://user-images.githubusercontent.com/10062082/46292492-544c0c80-c591-11e8-99e7-fc2dc713d712.png)

**Comment by PeterShaggyNoble** [comment]
@MrPostie, could you create a new issue for that one, please?

**Comment by PeterShaggyNoble** [comment]
I'm going to close this out as we already have plenty of icons on this subject. If you have any follow up requests for specific icons, please create a new issue for each one.
