### ISSUE TITLE
Water outline and dew point

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2178]
![](https://puu.sh/wpuE7.png)
![](https://puu.sh/wpuEN.png)
<br>
![](https://puu.sh/wpuFE.png)
![](https://puu.sh/wpuGl.png)
[dew-point-and-water-outline.zip](https://github.com/Templarian/MaterialDesign/files/1088770/dew-point-and-water-outline.zip)
Needed a dew point icon for a project I'm working on, so made this one up.

**Comment by Ch-Lo** [comment]
The second one already exists( [opacity](https://materialdesignicons.com/icon/opacity) ).

**Comment by GreenTurtwig** [comment]
Ahh, never seen that before. Although it's more of a blob shape compared to the water droplet. Might try some water droplets next to a thermometer and see how that turns out.

**Comment by Templarian** [comment]
[![water-outline](https://materialdesignicons.com/icon/water-outline)](https://materialdesignicons.com/icon/water-outline)
