### ISSUE TITLE
Double Chevron Icons

### ISSUE THREAD

**Issue by bobrocke** [Templarian/MaterialDesign#218]
- [ ] chevron-double-left
- [ ] chevron-double-right
- [ ] chevron-double-up
- [ ] chevron-double-down

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/chevron-double-left
http://materialdesignicons.com/icon/chevron-double-right
http://materialdesignicons.com/icon/chevron-double-down
http://materialdesignicons.com/icon/chevron-double-up

**Comment by bobrocke** [comment]
Thanks!

Are these now part of the web font and .css download?

Or do I have to add them to my set in some way? How?
