### ISSUE TITLE
[CRITICAL] Material Design Icons Site/CDN Offline

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2180]
I know about the site being offline. My webhost messed up and I have no idea what they exactly did to break it right now. Hopefully they respond to the ticket shortly.

Until then I have no idea why the box throwing 500 on all of the apps/support apps.

**Comment by GreenTurtwig** [comment]
This might be helpful in the meantime; it showed me a message saying they were "switching/upgrading the server" or something or other. :cat2:

**Comment by Templarian** [comment]
Yea, I wasn't given notice to what this entails until after it had been done. They moved to another server, but I assumed this was just a copy of the instance to new hardware.

I'm hoping the ticket lets me know more about what they did and ways to fix it (the site is just regular PHP, it doesn't have anything hardware related, so I think they messed up one of the configs moving it).

**Comment by GreenTurtwig** [comment]
What a pain in the arse, let's hope they respond quickly... 👍

**Comment by JamesCoyle** [comment]
Surely if you migrate to another server you redirect traffic to the new one gradually to make sure it works correctly and then take the old one offline. DDoS attacks or prolonged power outages should really be the only things that can cause downtime at a datacenter.

**Comment by Templarian** [comment]
Yea, how they did this is really bad. Hopefully they can switch it back to the other box and give me a port to figure out what is wrong with this box.

**Comment by Templarian** [comment]
Not happy with how my hosting company handled this in the slightest, but the site is back online. May need to do more testing tomorrow, but wasn't around until now to look into things.

### Technical Details
It was related to a CGI setting in the `.htaccess` file. This is all configured back when the server was setup, but conflicts with the new server apparently. No idea why, but will research more this weekend.
