### ISSUE TITLE
Icon request: R

### ISSUE THREAD

**Issue by sebastian-raubach** [Templarian/MaterialDesign#2182]
It would be great to see an R logo: `language-r`

**Comment by MrGrigri** [comment]
What are you requesting exactly; just the letter?

**Comment by GreenTurtwig** [comment]
I presume just the logo.
https://commons.wikimedia.org/wiki/File:R_logo.svg

**Comment by MrGrigri** [comment]
Yeah, but what is that for? It doesn't seem like anything we would add; too specific.

**Comment by GreenTurtwig** [comment]
It's the logo, just like Python and Ruby have logos. It represents the brand.

**Comment by MrGrigri** [comment]
I guess there are quite a few computer languages out there. I don't believe that this one is popular enough to include. Thoughts?

**Comment by GreenTurtwig** [comment]
It's still quite fairly used (about as much as Go currently), the more the merrier in my opinion. I don't think there's any harm in adding it.

**Comment by GreenTurtwig** [comment]
![puush-linux 2017-06-22 at 11 32 14](https://user-images.githubusercontent.com/15905797/27429847-849fcfd8-573e-11e7-94cb-e1bfe77b2148.png)
![puush-linux 2017-06-22 at 11 32 21](https://user-images.githubusercontent.com/15905797/27429854-86102dd6-573e-11e7-8aa5-9077176e6e87.png)
[language-r.zip](https://github.com/Templarian/MaterialDesign/files/1094445/language-r.zip)
Just resized their logo. :woman_shrugging:

**Comment by sebastian-raubach** [comment]
R is one place above Go just now:
https://www.tiobe.com/tiobe-index/

I agree that we can't add all the languages in the world, though.

**Comment by Templarian** [comment]
It's popular enough to add.

[![language-r](https://materialdesignicons.com/icon/language-r)](https://materialdesignicons.com/icon/language-r)
