### ISSUE TITLE
Micro SD Card

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2183]
![puush-linux 2017-06-21 at 01 35 06](https://user-images.githubusercontent.com/15905797/27384393-960bd3ec-5686-11e7-9eb3-7b8bea0a3400.png)
![puush-linux 2017-06-21 at 01 35 24](https://user-images.githubusercontent.com/15905797/27384396-97b45930-5686-11e7-9453-677eb9cf7742.png)
[micro-sd.zip](https://github.com/Templarian/MaterialDesign/files/1091473/micro-sd.zip)
Odd there was no Micro variant of the SD card considering how widely used they are. :cat2:

**Comment by Templarian** [comment]
Yea, odd, we have an SD card, but no microSD card.

[![micro-sd](https://materialdesignicons.com/icon/micro-sd)](https://materialdesignicons.com/icon/micro-sd)
