### ISSUE TITLE
Passport

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2187]
I mocked these up to use an icon for the [Mobile Passport android app](https://play.google.com/store/apps/details?id=us.mobilepassport). 

However, I can't quite get the look I want; maybe an airplane or some text is needed?

![passport2](https://user-images.githubusercontent.com/18021678/27409681-c0d58f08-56b0-11e7-9935-67e0423933fd.png)
![passport1](https://user-images.githubusercontent.com/18021678/27409682-c0d5e5b6-56b0-11e7-9083-d118604636ee.png)
![passport3](https://user-images.githubusercontent.com/18021678/27409811-5e962450-56b1-11e7-86cd-8a442220b1b5.png)

**Comment by GreenTurtwig** [comment]
![puush-linux 2017-06-22 at 09 47 06](https://user-images.githubusercontent.com/15905797/27425284-d3508d0c-572f-11e7-8c38-1c0c20b7e520.png)
![puush-linux 2017-06-22 at 09 47 14](https://user-images.githubusercontent.com/15905797/27425289-d62f7a06-572f-11e7-808e-f24cf671c4ec.png)
[passport.zip](https://github.com/Templarian/MaterialDesign/files/1094156/passport.zip)

How about something like this? Went through quite a few variations, but I think this one looked the best. :cat2:

**Comment by Templarian** [comment]
[![passport](https://materialdesignicons.com/icon/passport)](https://materialdesignicons.com/icon/passport)
