### ISSUE TITLE
Advanced Export broken

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#2189]
Click an icon (e.g. [home](https://materialdesignicons.com/icon/home)) > Advanced Export > Button [Icon].

Instead of offering a download, the following error occures:

Fatal error: Class 'Imagick' not found in /home/templarian/webapps/materialdesignicons/api/endpoints.php on line 1656

**Comment by GreenTurtwig** [comment]
Duplicate https://github.com/Templarian/MaterialDesign/issues/2181
