### ISSUE TITLE
Home icon inside circle

### ISSUE THREAD

**Issue by bentraynham** [Templarian/MaterialDesign#2193]
I would like to contribute an icon to this library, but I can't figure out how. I have this icon in SVG format. Can someone tell me how it can be added to the icon set?
<img width="662" alt="screen shot 2017-06-22 at 12 23 26 pm" src="https://user-images.githubusercontent.com/901123/27444852-9f382708-5745-11e7-959f-a2bed199f83f.png">

**Comment by JamesCoyle** [comment]
Just post a link here to an SVG download.

**Comment by bentraynham** [comment]
Thanks @JamesCoyle! Here is a link to the SVG file: http://btrayn.com/home-circle.svg

**Comment by Templarian** [comment]
@bentraynham Modified for better pixel alignment. Assigned under the contributor account. Let me know once you have 5 icons in the system.

[![home-circle](https://materialdesignicons.com/icon/home-circle)](https://materialdesignicons.com/icon/home-circle)
