### ISSUE TITLE
Send Encrypted Icon

### ISSUE THREAD

**Issue by andrewnenakhov** [Templarian/MaterialDesign#2194]
Standard 'Send' Icon with added lock to show that message will be sent securely. 

[send-encrypted.svg.zip](https://github.com/Templarian/MaterialDesign/files/1095503/send-encrypted.svg.zip)

**Comment by JamesCoyle** [comment]
I personally don't think it's the best idea really. That information should really be shown with some other UI element rather than the send button. Generally icons should only be single purpose and showing a conversation is encrypted as well as acting as the send icon could be confusing for the user.

**Comment by andrewnenakhov** [comment]
@JamesCoyle we use this icon to good effect in [Xabber](https://github.com/redsolution/xabber-android), it uses less space than having a separate icon and it gives a clear indication that outgoing message is encrypted. 

And there are already similar icons [pencil lock](https://materialdesignicons.com/icon/pencil-lock) and [phone locked](https://materialdesignicons.com/icon/phone-locked)

**Comment by MrGrigri** [comment]
Personally, those two specific icons at that scale that you have it, don't work together and doesn't follow MD style. The lock would have to be larger.

**Comment by MrGrigri** [comment]
Would the email-secure icon work?

![email-secure](https://materialdesignicons.com/icon/email-secure)

**Comment by andrewnenakhov** [comment]
> Personally, those two specific icons at that scale that you have it, don't work together and doesn't follow MD style. The lock would have to be larger.

That's just a matter of taste. I did a larger lock, looked too bad and obscured paper plane send shape far too much. Anyway, that's how it'll look in Xabber:
![screenshot_20170623-194327](https://user-images.githubusercontent.com/2351903/27487610-ab6ba41a-584d-11e7-8abc-efc8e6a92dda.png)
![screenshot_20170623-194854](https://user-images.githubusercontent.com/2351903/27487612-ad5f4a10-584d-11e7-8b97-2e075c1faf31.png)

It gives a very clear indication of encryption state and we don't think that email icon will work in that context, so Xabber will be using this icon anyway, whether it'll be accepted into main  repository or not.

**Comment by MrGrigri** [comment]
This follows the same pattern as the 'email-secure' icon, and IMO is the best option. 

![send-secure](https://user-images.githubusercontent.com/4528551/27487825-114dfdde-57f2-11e7-903f-ffff973554dc.png)

[send-secure.zip](https://github.com/Templarian/MaterialDesign/files/1098181/send-secure.zip)

**Comment by MrGrigri** [comment]
By having the lock in the bottom right corner, it visually get's lost. In the top right corner, it's easier to identify it as a lock.

**Comment by andrewnenakhov** [comment]
@MrGrigri I haven't seen send-secure icon before, however, I find it to be a bit too ugly for my taste. What I tried was to preserve a 'send' arrow shape as much as possible, and your variant makes point appear more broken. Maybe it'll look better if you take lock closer to arrow by 1px both vert and horiz and leave gap just 1 px wide..

**Comment by MrGrigri** [comment]
The `send-secure` icon is one that I just created and not in the repo. Per MD standards, the lock is a cut-out and that's how it works with this style. Cut-outs are two pixels, not one.

**Comment by andrewnenakhov** [comment]
@MrGrigri would you care to point to said MD standard? There are too many counter examples to what you are saying.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/27489040-52467cfe-57f6-11e7-9a61-9ce94a5e40e3.png) 
![image](https://user-images.githubusercontent.com/4528551/27489066-6dac33bc-57f6-11e7-9eeb-3320b0434f9e.png) ![image](https://user-images.githubusercontent.com/4528551/27489116-9ac7b43e-57f6-11e7-9cdb-2aaa94f94802.png) ![image](https://user-images.githubusercontent.com/4528551/27489141-b9094840-57f6-11e7-8de1-16e9214eff78.png)

**Comment by andrewnenakhov** [comment]
@MrGrigri That's guideline for strokes, not cut outs. And actually, this rule is violated on the very icon you supplied - on "phonelink lock" icon above cut outs around lock are clearly just 1 px.

**Comment by MrGrigri** [comment]
IMO the one-pixel cut-out below is just silly. The `phonelink` icon above is shown as an exemption example. The phone would appear less like a phone with a two-pixel cut-out. However, I'm willing to do what the community and owners of this repo feel are best. 

![send-secure-opt2](https://user-images.githubusercontent.com/4528551/27489705-c2d712a6-57f8-11e7-90fb-512558107acb.png) ![send-secure](https://user-images.githubusercontent.com/4528551/27489802-2ebfe3bc-57f9-11e7-8af9-f093cf34a542.png)

**Comment by andrewnenakhov** [comment]
@MrGrigri I'd try moving lock in 1px cut out maybe 2 or 3 px to the left, that'd make it look better. I actually did try having locks on top and putting it to design of app, end result looked worse to me. Don't have access to computer to show it out now.

**Comment by GreenTurtwig** [comment]
@andrewnenakhov Stroke, cut-out, they both mean the same thing, the draft follows the guidelines fine. Google always has exceptions with its designs (just look at the YouTube app...) and it drives me mad, especially with some of their icons (like [phonelink-lock](https://material.io/icons/#ic_phonelink_lock) and [network-check](https://material.io/icons/#ic_network_check). But I agree with @MrGrigri, having a one pixel stroke just looks odd in this scenario.

**Comment by andrewnenakhov** [comment]
@GreenTurtwig there are always exceptions in design because world does not follow some strict set of rules. Actually this icon with lock on top does not look well to me at all, but when it's on bottom it serves to achieve what we need much better. And having a bigger gap there looks not well because padlock shackle is thinner than 1px itself, having it a 2ps stroke would look ridiculous. 

Anyway it all came to taste differences. Our app would use 1st variant because, well, I like it more. Thanks everyone, @GreenTurtwig @MrGrigri

**Comment by GreenTurtwig** [comment]
There are exceptions because they **are** guidelines after all. :wink: 
While I agree the lock looks much better on the bottom rather than the top, I disagree with the fact the stroke should only be 1 pixel, it just looks too odd like that.
It would be fantastic to have more people give feedback on this. :+1:

**Comment by JamesCoyle** [comment]
For what possible reason would some messages in the chat be encrypted and others not? Doing things that way is just confusing for the user. It is better to go the WhatsApp route and show a message in the chat log itself when messages go from encrypted to plain or vice versa or show a lock icon next to the sent time indicator.

I personally don't feel this icon works at all.

**Comment by MrGrigri** [comment]
I could see this. For example, all emails at my work sent internally are not encrypted; because we have our own server and it never leaves the building. However, all email traffic sent outside is encrypted. So this would just be an indicator (or reminder) to the user that the email is going to be encrypted and that the recipient needs to have the key.

**Comment by andrewnenakhov** [comment]
@JamesCoyle actually our users asked for this. 

XMPP encryption works differently from whatsapp, and you can't show encryption status of a yet unsent message in message log, cause... it's not yet in log!
(we DO show if a message was encrypted or not in log, though, next to a time indicator)

The reason why users want it is because encryption in XMPP is much more user controlled and also can be enabled by different clients, so as a developers we have much less control of what happens and how different connected clients react to encryption - and we have to adapt to all situations like disabling of encryption by remote party. In that case we do display a blip in message log but a person who is busy typing an answer might easily miss it - and here a modified icon comes in handy. If encryption session is broken icon will be stripped of a lock and user will have a better chance to take notice.

**Comment by Templarian** [comment]
[![send-secure](https://materialdesignicons.com/icon/send-secure)](https://materialdesignicons.com/icon/send-secure)

Reading through this thread it seems like we're not sure if the icon is needed. I'm going to add it, but it is niche. I've moved the lock to the bottom right since it doesn't "require" clipping the `send` path.

If it helps I do agree secure/unsecure should be shown in a different way. I think this is outside of what the user should see in a UI.

Let me know if this work or doesn't and I'll reopen.

**Comment by andrewnenakhov** [comment]
@Templarian can't say I really like it since it was the first thing I tried - and it looked somewhat detached from send shape, that's why I decided for lock to clip on send path. But it's up to you, I guess.
