### ISSUE TITLE
Recent icon and Equalizer icon

### ISSUE THREAD

**Issue by kongsonida** [Templarian/MaterialDesign#2195]

**Comment by MrGrigri** [comment]
Will [tune](https://materialdesignicons.com/icon/tune) or [tune-vertical](https://materialdesignicons.com/icon/tune-vertical) not work?

![image](https://user-images.githubusercontent.com/4528551/27456854-c2afaa66-575f-11e7-8bbc-5a4202875b69.png) 
![image](https://user-images.githubusercontent.com/4528551/27456873-d4a6df32-575f-11e7-9a57-169084ae2f9a.png)

**Comment by GreenTurtwig** [comment]
And we also have the [history](https://materialdesignicons.com/icon/history) icon to represent `recent`.
[![](https://materialdesignicons.com/icon/history)](https://materialdesignicons.com/icon/history)

**Comment by Templarian** [comment]
Closing this out. If these don't work we'll reopen the issue. You can inline paste images as examples to give us a better context/idea of what you're looking for.
