### ISSUE TITLE
Paragraph icon

### ISSUE THREAD

**Issue by casperschou** [Templarian/MaterialDesign#2197]
A paragraph symbol as an icon, used for legal notes etc.

https://thumb7.shutterstock.com/display_pic_with_logo/3621995/404346211/stock-vector-paragraph-symbol-section-vector-icon-404346211.jpg

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/format-section)](https://materialdesignicons.com/icon/format-section)

**Comment by BeatriceFendt** [comment]
Hi @JamesCoyle, @casperschou and @Templarian,
is the legal icon already available? Which is the original issue for this icon request?

**Comment by PeterShaggyNoble** [comment]
@BeatriceFendt, follow the link in James' comment.

**Comment by BeatriceFendt** [comment]
I cannot see James' comment 🤔

![comment](https://user-images.githubusercontent.com/34834134/34584913-e699d144-f19d-11e7-806b-276f6991fa64.PNG)

**Comment by Templarian** [comment]
@BeatriceFendt I can see it, it's an image of an icon. Might have been a hickup with GitHub's image cache.

![image](https://user-images.githubusercontent.com/338885/34585105-062009dc-f164-11e7-84dc-2d16987b1034.png)

^ This image.

**Comment by BeatriceFendt** [comment]
Perfect, thanks @Templarian 😎
