### ISSUE TITLE
Journal/Diary

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2199]
I mocked this up to use as an icon for the [Journal app](https://chrome.google.com/webstore/detail/journey-diary-journal/jlncjaehedpdoinepaejmlpbmdkgmpog?hl=en), but it could work as a general journal/diary icon. 

I took the book icon and added the lock from the folder-lock to the book icon. I'm working with shitty web image editors, but if somebody could polish it up I think it'd make a good addition to the library.

![journal](https://user-images.githubusercontent.com/18021678/27481202-6e461408-57e9-11e7-8d9f-e95c39996c12.png)

**Comment by MrGrigri** [comment]
Plop the SVG in a zip here.

**Comment by k5cents** [comment]
Unfortunately, I don't have the .svg or any way to even make one. I only own Chrome OS devices with no real photo editing software. I use websites like https://www.photopea.com/ and https://pixlr.com/editor/ for all my editing needs.

**Comment by MrGrigri** [comment]
We should call it `book-secure` to match the other books. 

![book-secure](https://user-images.githubusercontent.com/4528551/27488254-a14c0c36-57f3-11e7-8697-11ca101200d8.png)

[book-secure.zip](https://github.com/Templarian/MaterialDesign/files/1098229/book-secure.zip)

**Comment by k5cents** [comment]
Do you think that lock looks better than the one used on the `folder-lock` and `file-lock`? I like the way the curved edges match up on yours, but I think the squarer icon works a little better at the small size needed to fit _inside_ the book icon. 

Thanks, though. Whichever you prefer!

**Comment by MrGrigri** [comment]
You're probably right, with the `folder-lock` icon, we can have an unsecure version as well. 

![book-secure-variant](https://user-images.githubusercontent.com/4528551/27490321-0f8c6b76-57fb-11e7-8734-478063d1eee3.png) ![book-unsecure-variant](https://user-images.githubusercontent.com/4528551/27490320-0f8c0ab4-57fb-11e7-8422-5fc4ea7c902b.png)

[book-secure.zip](https://github.com/Templarian/MaterialDesign/files/1098375/book-secure.zip)

**Comment by Templarian** [comment]
I like these additions! Could use these at work.

[![book-secure](https://materialdesignicons.com/icon/book-secure)](https://materialdesignicons.com/icon/book-secure) [![book-unsecure](https://materialdesignicons.com/icon/book-unsecure)](https://materialdesignicons.com/icon/book-unsecure)
