### ISSUE TITLE
Icon suggestion: geolocation icon

### ISSUE THREAD

**Issue by balteo** [Templarian/MaterialDesign#220]

**Comment by Templarian** [comment]
These icons already exist, unless you're thinking of another icon.

http://materialdesignicons.com/icon/crosshairs
http://materialdesignicons.com/icon/crosshairs-gps

Or any of the map-marker icons.

**Comment by balteo** [comment]
I meant something like that:
http://megaicons.net/static/img/icons_sizes/8/178/64/maps-and-geolocation-marker-icon.png

2015-03-15 0:28 GMT+01:00 Austin Andrews <notifications@github.com>:

**Comment by balteo** [comment]
Sorry! Ignore my previous mail...

2015-03-15 12:24 GMT+01:00 Julien Martin <balteo@gmail.com>:

**Comment by Templarian** [comment]
No problem good that you found the icon. I think `geolocation` is actually the `crosshairs-gps` icon. If I get bored I'll add a alias for those searching in the future.

`pin` is the `map-marker` icon that you were looking for. I'll add an alias for `map-pin` to `map-marker`.

**Comment by balteo** [comment]
Thanks Austin!

2015-03-15 20:30 GMT+01:00 Austin Andrews <notifications@github.com>:
