### ISSUE TITLE
Redo email-outline

### ISSUE THREAD

**Issue by JelleBlaauw** [Templarian/MaterialDesign#2200]
Hi,

Could you please redo the email-outline icon? The line thickness is all wrong and it looks blurry too. The email-open-outline looks perfect, however. Perhaps that one could be used to fix it.

Thanks.

**Comment by GreenTurtwig** [comment]
The flap is correct, as in it is the inverse of the normal email icon. However I agree it doesn't look that good compared to the opened email icon. The design could definitely be improved.

**Comment by Flitskikker** [comment]
Here's a more (optically) correct version, where the flap is as thick as the outline.

[email-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/1098382/email-outline.svg.zip)

**Comment by MrGrigri** [comment]
Good catch.

**Comment by Templarian** [comment]
Fixed. Thanks @JelleBlaauw  / @Flitskikker!
