### ISSUE TITLE
Has someone already sugested a brain icon?

### ISSUE THREAD

**Issue by daganox** [Templarian/MaterialDesign#2201]

**Comment by shroudedcode** [comment]
@daganox If there would be a [lmgtfy.com](https://lmgtfy.com) for GitHub repository searches I would have probably used it to respond. **Yes**, someone has already suggested that - seven people in total, six of them not able to use a search function. Please make sure to **_always_ search** before asking. That saves everyone time.

:arrow_right: The currently open issue is #526. Press :+1: there, you can close this issue.

**Comment by MrGrigri** [comment]
#526

**Comment by PeterShaggyNoble** [comment]
@shroudedcode, please bear in mind that search is not available on GitHub's mobile site. Obviously that doesn't account for *all* dupes but I'm sure it accounts for some of them.

**Comment by GreenTurtwig** [comment]
If people use Chrome they can request the desktop site. There's also a button at the bottom of the page to switch.
