### ISSUE TITLE
Print Preview Icon

### ISSUE THREAD

**Issue by AlexLnz** [Templarian/MaterialDesign#2204]
A print preview icon is needed.

Suggestions:
* magnifying glass over sheet of paper
* magnifiying glass over printer

**Comment by MrGrigri** [comment]
Will `file-find` work? Either way, we should add an alias of `print-preview`.

![file-find](https://materialdesignicons.com/icon/file-find)

**Comment by GreenTurtwig** [comment]
Hmm, I always see a printer with a magnifying glass used as a print preview icon. But a document or file with a magnifying glass as just a regular "preview" icon.

**Comment by MrGrigri** [comment]
I've seen print preview represented as above. But I too have seen it with a printer.

**Comment by MrGrigri** [comment]
What are y'all's thought on this one? I did place it on the left-hand side because there is more detail in the printer on the right-hand side. 

![print-preview](https://user-images.githubusercontent.com/4528551/27552003-e2366090-5a62-11e7-990f-4c0b2683b588.png)

[print-preview.zip](https://github.com/Templarian/MaterialDesign/files/1102963/print-preview.zip)

**Comment by AlexLnz** [comment]
@MrGrigri I would prefer your first suggestion, the file-find because it's a clear and simple approach. For me it's easier to recognize than the printer. But that's a personal preference of course.

What about having a outlined version of the magnifying glasses and the sheet? In this way "print preview" would look different than "file find".
The filled one would be file then, while the outlined will be paper. Does that make sense?

**Comment by Alekhen** [comment]
Would it not make sense to simply add the [eye](https://materialdesignicons.com/icon/eye) icon to the [file](https://materialdesignicons.com/icon/file) following the same pattern as the [file-cloud](https://materialdesignicons.com/icon/file-cloud) icon? Something like this:

![print-preview](https://user-images.githubusercontent.com/1837101/27645063-705e562c-5be2-11e7-9e7a-ace64cff3956.png)
![print-preview-small](https://user-images.githubusercontent.com/1837101/27645062-705dcb4e-5be2-11e7-8cd3-72725a7cb487.png)

[print-preview.svg.zip](https://github.com/Templarian/MaterialDesign/files/1109209/print-preview.svg.zip)

**Comment by Templarian** [comment]
Some good suggestions, but I think simply aliasing the existing icon will be the best solution.

`file-find` ... `print-preview`

@Alekhen Good idea, but might be too abstract of a connection.
