### ISSUE TITLE
IoT  icons

### ISSUE THREAD

**Issue by boyantsonev** [Templarian/MaterialDesign#2206]
would be useful for IoT projects containing objects like sensors, gateways, consumption:

temperature
humidity
electricity usage
water usage
gas usage
motion
flood
on/off
vibration
light
current
gateway
battery
signal strength

**Comment by Templarian** [comment]
Most of these exist (some with very similar names). Can you please search and narrow down your icon requests to a single icon per issue. Including example images (pasted inline) can help us more easily design and add the icon.

Thanks!
