### ISSUE TITLE
Edit History

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2207]
I've come across a specific requirement for an icon representing version control history. It needed to be more than just the [history](https://materialdesignicons.com/icon/history) icon already in the pack so I created this one. What are y'all's thoughts?

![edit-history](https://user-images.githubusercontent.com/4528551/27606863-169ff9b8-5b3f-11e7-8089-0a9db50392c9.png)

[edit-history.zip](https://github.com/Templarian/MaterialDesign/files/1106574/edit-history.zip)

**Comment by andrewnenakhov** [comment]
Not really great.

**Comment by JapanYoshi** [comment]
Don't quite like it either.

**Comment by Templarian** [comment]
Agreed... not really a fan of this. Going to close this issue. Please reopen if another design is created.
