### ISSUE TITLE
Website search is really slow on Google Chrome for MacOS

### ISSUE THREAD

**Issue by felipefpx** [Templarian/MaterialDesign#2208]
This project is awesome and it helps me a lot, but everytime I try to search for an icon the website completely stops for 3~6 seconds to show the filtered icons.

**Comment by JamesCoyle** [comment]
It is loading all of the SVG icons so takes a long time to render them all. We have been working on this issue for a while now with a completely new site that should fix these issues when it goes live.

**Comment by Templarian** [comment]
@felipefpx https://github.com/Templarian/MaterialDesign-Site/issues New site is in progress (busy, but slowly working on it).

You can use the Chrome/Firefox extensions also "MaterialDesignIcons Picker".

**Comment by PeterShaggyNoble** [comment]
[This](http://mdi.houseofdesign.ie/) may be of use to you in the meantime, while the new site is being worked on.
