### ISSUE TITLE
File Icon - Path Not Closed

### ISSUE THREAD

**Issue by Alekhen** [Templarian/MaterialDesign#2209]
The path of the inner triangle on the [file](https://materialdesignicons.com/icon/file) icon is not closed.

![file-annotated](https://user-images.githubusercontent.com/1837101/27644694-6b39f152-5be1-11e7-960f-b3c60d73da6d.png)

Here's the fixed SVG: [file.svg.zip](https://github.com/Templarian/MaterialDesign/files/1109174/file.svg.zip)

**Comment by Templarian** [comment]
@Alekhen As far as I know a segment followed by a `M` auto closes in SVG.

```
M13,9V3.5L18.5,9M6,2C4.89,2 4,2.89 4,4V20A2,2 0 0,0 6,22H18A2,2 0 0,0 20,20V8L14,2H6Z
                ^ Is equivelent to ZM
```

The SVG optimization only includes the final required "closepath".

https://www.w3.org/TR/SVG/paths.html#PathDataClosePathCommand

Is there a reason why this is needed?

**Comment by Alekhen** [comment]
I see. Just an observation when I opened the SVG in Adobe Illustrator that path wasn't closed. If it's not an issue from a code standpoint then great.
