### ISSUE TITLE
The Google G

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2210]
The `google` icon uses the G letter from "The Google Logotype", but Google itself uses their "Google G" icon in the Android O settings menu. Its the G they use on [Google app icon](https://lh3.googleusercontent.com/DKoidc0T3T1KvYC2stChcX9zwmjKj1pgmg3hXzGBDQXM8RG_7JjgiuS0CLOh8DUa7as=w300-rw) and other places where it's just the G and not the full word.

![g](https://user-images.githubusercontent.com/18021678/27701071-b9af561e-5ccd-11e7-94d1-625881564ee4.png)

See their ["Evolving the Google Identity" blog post](https://design.google/library/evolving-google-identity/) for more.

**Comment by MrGrigri** [comment]
Which one do you need? There are two. `google-glass` is a bit thinner though.

![google](https://materialdesignicons.com/icon/google) ![google-glass](https://materialdesignicons.com/icon/google-glass)

**Comment by k5cents** [comment]
I think both of those are thinner than the G in the Android O settings, on the app, and on the back of the Pixel. 

I'm suggesting, if possible, that the `google` icon be made thicker to match the icon and not just the letter.

**Comment by Templarian** [comment]
I think that would make it inconsistent with the existing icons (3dp, moving it to a 4dp as shown looks too bold). This is also a Google stock icon.

**Comment by k5cents** [comment]
I get that it's not the one provided by Google, but obviously it's used by Google (in their own flagship operating system). I understand if it doesn't get added, just thought I'd mention the fact that it's different than the one they now seem to be using.

**Comment by Templarian** [comment]
So, maybe as `google-bold`, but I don't think replacing the existing one is the best move if we do add it.
