### ISSUE TITLE
Alias "User" for all "Account" Icons

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#2212]
Can we get a corresponding "user"-alias for all the account icons? Currently nothing shows up, when searching for "user". I would suggest adding "user-xxx" alias for every "account-xxx" icon. 

Do you need a list of all icons in question or can this be done by some automatic task (dont know how this is wokring here)?

**Comment by Templarian** [comment]
Yea, we can add it to all these icons. Will be working to expand the aliases.

**Comment by PeterShaggyNoble** [comment]
All aliases added.
