### ISSUE TITLE
Icon Request: Zoom to Selection

### ISSUE THREAD

**Issue by skawaii** [Templarian/MaterialDesign#2213]
A zoom to selection icon would be welcomed. I took a stab at creating something for my project and am fine sharing it, if desired (although I make no claims at being a designer, I did try to follow the MD guidelines).

![image](https://user-images.githubusercontent.com/4439/27750866-b0ccfdaa-5da7-11e7-96fa-22f0a432e3d5.png)

**Comment by JamesCoyle** [comment]
I'd go with a combination of these two:
[![](https://materialdesignicons.com/icon/select)](https://materialdesignicons.com/icon/select)[![](https://materialdesignicons.com/icon/magnify)](https://materialdesignicons.com/icon/magnify)

Also @Templarian, why do we have two different icons for selection? There is the one above and:
[![](https://materialdesignicons.com/icon/selection)](https://materialdesignicons.com/icon/selection)

**Comment by MrGrigri** [comment]
Do you mean a 'zoom-to-selection' as a cursor? Where you can just click or click and drag an area to zoom to.

**Comment by skawaii** [comment]
@MrGrigri Yes, exactly. Click a button, click + drag over an area. zoom into the selected area. Something that would work well as both a button in a toolbar and the cursor would be ideal.

@JamesCoyle Those two icons together definitely would work well. I considered trying something with thsoe, but the one I made was easier for me to make with my novice Sketch skills.

**Comment by JamesCoyle** [comment]
Ah in that case I'd recommend just drawing one of the magnify icons next to whatever icon you use as a cursor for now. We should maybe add a full set of cursors as icons.

**Comment by MrGrigri** [comment]
Here are two that I put together as `magnify-minus-cursor` and `magnify-plus-cursor`.

![magnify-minus-cursor](https://user-images.githubusercontent.com/4528551/27875160-7e10fbd4-616f-11e7-8d3d-d997baa11fc8.png) ![magnify-plus-cursor](https://user-images.githubusercontent.com/4528551/27875159-7e102ef2-616f-11e7-91f7-c1d30fc5367b.png)

[magnify.zip](https://github.com/Templarian/MaterialDesign/files/1125388/magnify.zip)

**Comment by NovapaX** [comment]
While we're drawing magnifying glasses, can we add a 'reset-zoom' icon?
Something like this: 
![54041-200](https://user-images.githubusercontent.com/411716/37020259-7d046cd2-211b-11e8-948b-0c10a0d3c5ca.png)
or this:
<img width="157" alt="schermafbeelding 2018-03-06 om 08 50 40" src="https://user-images.githubusercontent.com/411716/37020263-80ac18bc-211b-11e8-942f-08d257df2c0b.png">

**Comment by PeterShaggyNoble** [comment]
@NovapaX, `find-replace` should cover that but, if not, please create a new issue for it.

**Comment by Templarian** [comment]
Added the `magnify-plus-cursor` and `magnify-minus-cursor`. Please create new issues for any others. Thanks.
