### ISSUE TITLE
Activity Icon

### ISSUE THREAD

**Issue by dintendocoltd** [Templarian/MaterialDesign#2215]
I understand that there was already a request for an activity icon (https://github.com/Templarian/MaterialDesign/issues/1962), but the request didn't specify the design style of the activity icon, and the last response to the issue was on April 10th.

So, I would like to request an activity icon, similar/along the lines of this: 
![activity-512](https://user-images.githubusercontent.com/7736654/27790742-c056c064-5fe9-11e7-8678-cb5cb089f598.png)

Thanks

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/pulse)](https://materialdesignicons.com/icon/pulse)
