### ISSUE TITLE
Service/Give icon

### ISSUE THREAD

**Issue by mazza094** [Templarian/MaterialDesign#2216]
I was looking for a service icon and i found a cool idea

[url](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTs2FjkXUu_ZIQjaf29bqqbzteEoJKoBJ19a7D_LjM21ugM1NqjOJ7nvg)

As you can see in the linked image would be cool to have the icon of the gesture.
Maybe with a gear on it to represent a given service.

F.

**Comment by MrGrigri** [comment]
That would be difficult at a 24x24 pixel canvas. The cog itself at that size is barely recognizable. 

Would `headset` not do the job; customer service.

![headset](https://materialdesignicons.com/icon/headset)

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #1799 which requests a more generic version of this; I think the hand with a cog is going to be too specific for inclusion.

See also #2018.
