### ISSUE TITLE
Icon Creator App Features - Needs Community Feedback

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#2219]
Figured I'd make a start on an in browser icon editor that could potentially allow people without vector editor experience to create material icons. Currently it just shows a grid and lets you type in the SVG path manually and automatically updates the result. 

![image](https://user-images.githubusercontent.com/10384436/27828301-733492dc-60b3-11e7-9d25-b0108d3fd336.png)

I was hoping to take this much further than just this 5 minute concept but thought it would be best to ask the community what features would be useful to have. 

Planned features:
- Ghost icon so you can sketch over an existing design
- Better error handling
- Multiple size views
- Different render modes (so you can see the stroked path or the final filled result with no stroke)
- Export tools

I'd also like to make the process of creating the icon simpler by providing tools to input each command. This would be some sort of process which handles each command as a separate stage that can be easily edited rather than it being one long string. This would likely allow points to be selected based on mouse input and allow commands to be easily swapped out such as swapping the different curves and optimizing horizontal/vertical lines. 

If anyone has any suggestions/feedback please let me know. I'll post an update once I have time to get it to an alpha state.

**Comment by Templarian** [comment]
Pick and place shapes might be easier for some to work with. The only issue is combining the vector shapes in a nice way to get a single path in the end.

Really even if it gives a messy SVG with a bunch of groups it could get people thinking of ideas quickly (only takes a few clicks to flatten and remove the extra point data).

**Comment by JapanYoshi** [comment]
* MD icon grid.
* Shape tools.
* Layers for alts.
* 2px strokes.
* (Automatic) counter stroke.
