### ISSUE TITLE
Is there an easy way to add new icons to the icon font?

### ISSUE THREAD

**Issue by bobrocke** [Templarian/MaterialDesign#222]
How would I go about doing that? It appears that icons are added faster than the font can be updated.

**Comment by Templarian** [comment]
To generate your own font you can use the grunt webfont package with the `node` generation (FontForge mode will work also, but I've used the `node` mode to generate on my server). You may have noticed that when downloading SVG's on the site there are webfont safe svg files. Those are specially tailored to convert nicely in most font packages.

https://github.com/sapegin/grunt-webfont

You can also use http://icomoon.io

## Update Schedule

I think there might be some slight confusion. The font is updated weekly after I scan the changes from the community. It's more of a verification that everything looks good before. This small quality control window ensures that the thousands of users of the font will not update and see everything broken. :smile: 

Technically speaking there is a way to generate subfonts in the site, but I need to complete the UI for it. I only have the backend completed.

**Comment by bobrocke** [comment]
OK. I was more interested in adding new Material Design Icons to the material design icon font. If it's updated weekly, that might work fine. What day of the week are the new font files available?

**Comment by Templarian** [comment]
Depends on how many beers on have on Saturday. But usually Saturday or Sunday. This week's I did on Wednesday since I had exactly 50 new icons in the set.

**Comment by bobrocke** [comment]
I see. :)

I just wanted to get at the new Markdown and Double Chevron icons (from inside the icon font files).

**Comment by bobrocke** [comment]
Would it be possible to automate the font creation process so that once a new icon was accepted into the set, perhaps on merging a pull request, the icon font would be updated, too.

When the font is updated, is there a way to get notification so that I can update my site's version, too?

**Comment by Templarian** [comment]
This already coded, but there is a bug in the Woff2 creation that I'm still debugging.

**Comment by bobrocke** [comment]
Are you expecting to update the icon font with all the new icons tomorrow?

**Comment by Templarian** [comment]
Today, I'm working on it right now. Adding a few new icons before the Beta release. I'll try to get the font updated in the various locations before I finish up the marketing stuff.

**Comment by Templarian** [comment]
`v1.0.8-beta` is released.

**Comment by bobrocke** [comment]
Great! I'll head to the download button now. Thanks!

**Comment by bobrocke** [comment]
I see that the icon set is at v1.0.62b while the font is still at v1.0.8b.

When do you expect the next font update that rolls in the new icons?

**Comment by Templarian** [comment]
It's updated, just forgot to update the site's text.
