### ISSUE TITLE
Not accepting contributions?

### ISSUE THREAD

**Issue by jonohunt** [Templarian/MaterialDesign#2221]
I've made some icons (8) and looked at submitting them, but saw on the [Contribute page](https://materialdesignicons.com/contribute) that it  says 'disabled' for contributing icons.

Does that mean you're not accepting new icons to be submitted? Or that you **are** accepting new icons, but aren't wanting to make any more people 'contributors'?

**Comment by JamesCoyle** [comment]
Just post an issue saying what icon you are contributing and provide a link to download the SVG in that issue.

**Comment by jonohunt** [comment]
Thanks, will do.
