### ISSUE TITLE
Request Loading icon

### ISSUE THREAD

**Issue by dalearn** [Templarian/MaterialDesign#2224]
We don't have a loading icon (or the various stages of a loading spinner).  Can we make one?

**Comment by MrGrigri** [comment]
Does [loading](https://materialdesignicons.com/icon/loading) not work?

![loading](https://materialdesignicons.com/icon/loading)

**Comment by dalearn** [comment]
not as far as I can tell, it appears to only be a small fraction of the necessary icons!  probably 4 or 8 needed at least

**Comment by JamesCoyle** [comment]
The Google loading spinner is a complex animation of four separate SVG layers. It's really well beyond the scope of this project. I'd recommend going to the webcomponents website and taking the code from the paper-spinner repository.

**Comment by MrGrigri** [comment]
Look at #1869 for more details. This icon can be used with a linear CSS transform property value of rotate.

**Comment by Templarian** [comment]
@dalearn What other loading icon styles are you looking for (example images)?

Since these icons follow the Material Design guidelines I'm kind of thinking it might be best to just have the MD styled `loading` icon.
