### ISSUE TITLE
Split

### ISSUE THREAD

**Issue by bennypowers** [Templarian/MaterialDesign#2225]
There's a split-stream icon here: https://material.io/icons/#ic_call_split

What I'd like is a split section/region/clip/block icon. something like: 

https://maxcdn.icons8.com/Share/icon/p1em/arrows//split_horizontal1600.png

**Comment by MrGrigri** [comment]
I did both vertical and horizontal version. Do these meet your needs?

![split-vertical](https://user-images.githubusercontent.com/4528551/27920165-ff9e0658-6230-11e7-8e1b-1d1c15d2bf9f.png) ![split-horizontal](https://user-images.githubusercontent.com/4528551/27920166-ffa60ba0-6230-11e7-8d0d-06e58d630915.png)

[split.zip](https://github.com/Templarian/MaterialDesign/files/1128436/split.zip)

**Comment by Templarian** [comment]
[![arrow-split-vertical](https://materialdesignicons.com/icon/arrow-split-vertical)](https://materialdesignicons.com/icon/arrow-split-vertical) [![arrow-split-horizontal](https://materialdesignicons.com/icon/arrow-split-horizontal)](https://materialdesignicons.com/icon/arrow-split-horizontal)
