### ISSUE TITLE
Incorrect Contribution

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2226]
I have noticed a couple of icons of mine that we're contributed incorrectly.

- [x] Douban #1394
- [x] Section #1420

![image](https://user-images.githubusercontent.com/4528551/27922314-da9e5842-6237-11e7-8af2-84b003ee6252.png) 
![image](https://user-images.githubusercontent.com/4528551/27922669-09017146-6239-11e7-9477-0e3cb1201523.png)

**Comment by Templarian** [comment]
My bad, always need to double check which account I have selected when clicking the upload button. Will fix this!

**Comment by Templarian** [comment]
Fixed.
