### ISSUE TITLE
fabric-swatch

### ISSUE THREAD

**Issue by brimba** [Templarian/MaterialDesign#2227]
I'm missing a symbol for samples of cut materials. 
Could be used in all shops that offer free samples of fabrics, carpet, wallpaper, ligaments ... 
We would need it in our shop for natural fiber fabrics.

![sample-icon](https://user-images.githubusercontent.com/18737169/27946905-1733c564-62f4-11e7-8e51-86e63f0b8df8.png)

**Comment by steodor** [comment]
Hi @brimba, i know i'm a few years late to the party :) but do any of these fit the bill?
![image](https://user-images.githubusercontent.com/4397338/108347726-89e90300-71e9-11eb-9c69-a7cdf9dd8abc.png)![image](https://user-images.githubusercontent.com/4397338/108347742-8d7c8a00-71e9-11eb-8068-c2de9edceb0e.png)![image](https://user-images.githubusercontent.com/4397338/108347748-8f464d80-71e9-11eb-9eb7-e7d693dffedc.png)
[fabric-swatch.zip](https://github.com/Templarian/MaterialDesign/files/6002317/fabric-swatch.zip)

**Comment by goyney** [comment]
This will be covered by #2168. Closing as a duplicate.

**Comment by brimba** [comment]
Hi, yes, little late, but better than never 😉

Swatch 2 would work pretty well!

Thanks

Ludwig

Mobil gesendet
