### ISSUE TITLE
cash-check

### ISSUE THREAD

**Issue by mariovials** [Templarian/MaterialDesign#2228]
a dollar with a little check 
PLEASE

**Comment by Templarian** [comment]
Due to supporting so many currencies this would have to be the more generic dollar (not the USD/AUD $ symbol).

**Comment by mariovials** [comment]
Of course, a currency sign is enough

**Comment by vcantu** [comment]
How's this?
for cash and cash-multiple
![cash-check demo](https://user-images.githubusercontent.com/13156162/27998171-7af9e2d4-64bd-11e7-811c-7c2edecdcc65.png)

[cash-check_svgs.zip](https://github.com/Templarian/MaterialDesign/files/1134134/cash-check_svgs.zip)

**Comment by vcantu** [comment]
Or with the checkmark lined up with the circle
![cash-check-demo](https://user-images.githubusercontent.com/13156162/27998260-036698b8-64c0-11e7-84e1-ab4ac3d18a17.png)
[cash-check-linedup_svgs.zip](https://github.com/Templarian/MaterialDesign/files/1134141/cash-check-linedup_svgs.zip)

**Comment by mariovials** [comment]
YESS!! Thank!!

**Comment by mariovials** [comment]
can you add this to master?

**Comment by MrGrigri** [comment]
I still don't know if this works out at a 24x24 size.

**Comment by PeterShaggyNoble** [comment]
Shouldn't the tick be in the bottom right?

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
