### ISSUE TITLE
Newly added and uppdated icons

### ISSUE THREAD

**Issue by ericlindesvard** [Templarian/MaterialDesign#2230]
Hi, I use the library as a web font using the link tag in head.

There are a lot of icons from the history list not avalible this way. For example mdi-emoticon-poop which was updated about a month ago.

What is the delay time for the icons to show up?

**Comment by Templarian** [comment]
A server migration caused some issues with the build tools (along with other things that were more visible). A release should be going out shortly. Learn more: #1983.

(Not home a lot during the summer since it's been so nice out).
