### ISSUE TITLE
Message Group Icon

### ISSUE THREAD

**Issue by andrewnenakhov** [Templarian/MaterialDesign#2232]
Came accoss the need to represent group chat as opposed to chat with single person. Thus, created an icon based on [message-text](https://materialdesignicons.com/icon/message-text) shape:

![message-group 1x](https://user-images.githubusercontent.com/2351903/28014305-9be33edc-6585-11e7-9994-c8b31ff2ebbc.png)
![message-group 2x](https://user-images.githubusercontent.com/2351903/28014274-7b1d4f44-6585-11e7-8cc8-6415619cbc05.png)

[message-group.svg.zip](https://github.com/Templarian/MaterialDesign/files/1135181/message-group.svg.zip)

I've also made some other variants but they look somewhat worse, so I didn't settle on them:
![message-group-variant](https://user-images.githubusercontent.com/2351903/28014435-098f362a-6586-11e7-9d63-964320179ab2.png)
![message-group-variant2](https://user-images.githubusercontent.com/2351903/28014441-0e378c0e-6586-11e7-92dc-fe6a9ddaeaa9.png)

If someone likes them, however, i might expand on these.

**Comment by MrGrigri** [comment]
Personally, I like the bottom one.

**Comment by Ch-Lo** [comment]
What about a group-icon (maybe [this](https://materialdesignicons.com/icon/account-multiple)) in a speech bubble? Might look cleaner then three speech bubbles combined. (We dont have such icon yet).

**Comment by andrewnenakhov** [comment]
@MrGrigri bottom one has an advantage because just 2 bubbles do not really represent "group chat" since any chat requires at least two participants. However, it's wide, ugly and uses all 24px, so I more or less settled on 2 bubble variant. It might work for us since this icon will be represented alongside simple [message-text](https://materialdesignicons.com/icon/message-text) icon, and might be useful in some other cases. 

Btw, for interested here, I also did some more variants. 

![message-group-variants](https://user-images.githubusercontent.com/2351903/28066260-b88da89e-6655-11e7-9145-bc1ff09425ca.png)
![message-group-variants 2x](https://user-images.githubusercontent.com/2351903/28066263-bb345944-6655-11e7-9e89-a2798c9f2b72.png)

Second one looks like a good contender, however, third and fourth are the same with gutter not 2px but 1 and 1.5 - migth look good too.

**Comment by andrewnenakhov** [comment]
Attached a vector of variant 2 from above, with just slightly bigger lines:
![message-group-variant 1x](https://user-images.githubusercontent.com/2351903/28067014-d0d4ab3e-6658-11e7-8712-77e16d13d686.png)
![message-group-variant 2x](https://user-images.githubusercontent.com/2351903/28067020-d2efa1b2-6658-11e7-81b5-bf81de1d1208.png)

[message-group-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/1138735/message-group-variant.svg.zip)

**Comment by andrewnenakhov** [comment]
Turns out, there is already a similar [Forum](https://materialdesignicons.com/icon/forum) icon, it's just hard to find it by it's name. Maybe this icon submission is a bit redundant.

**Comment by andrewnenakhov** [comment]
Taking some inspiration from [Forum](https://materialdesignicons.com/icon/forum) Icon I finally settled on this:
[message-group-variant2.svg.zip](https://github.com/Templarian/MaterialDesign/files/1150360/message-group-variant2.svg.zip)
![message-group-variant2 1x](https://user-images.githubusercontent.com/2351903/28239782-309aaa64-698d-11e7-84ef-52bc75d3176c.png)
![message-group-variant2 2x](https://user-images.githubusercontent.com/2351903/28239783-338ae5ae-698d-11e7-82b6-27225a8c1633.png)

The reasoning is that this icon is needed for me to be alongside [message-text](https://materialdesignicons.com/icon/message-text) icon, and Forum didn't sit well next to it, so I expanded message bubbles and added some lines. We'll definitely stick with this one in our app. As for adding it to collection, I leave judgement to @Templarian

**Comment by JamesCoyle** [comment]
Proposing we use forum and perhaps add a variant with lines of text. 
[![](https://materialdesignicons.com/icon/forum)](https://materialdesignicons.com/icon/forum)

**Comment by andrewnenakhov** [comment]
@JamesCoyle I tried 2 lines on forum icon, does not really look good, especially near the message-text icon. At least, does not look good for our design.

**Comment by Templarian** [comment]
Aliased as `message-group`.
