### ISSUE TITLE
Sina Weibo icon

### ISSUE THREAD

**Issue by 531149907** [Templarian/MaterialDesign#2235]
Sina weibo logo/icon:

example: https://upload.wikimedia.org/wikipedia/en/6/6e/Sina_Weibo.svg

And thanks for creating such beautiful icons!

**Comment by augustin32** [comment]
Is this good?
![sina-weibo24](https://user-images.githubusercontent.com/14167196/28230438-bd9ced58-68ef-11e7-85cd-01811a39edbb.png)
![sina-weibo36](https://user-images.githubusercontent.com/14167196/28230443-c14402de-68ef-11e7-9f50-8bbcd71dd2b7.png)
![sina-weibo48](https://user-images.githubusercontent.com/14167196/28230447-c5ee81a6-68ef-11e7-8092-73148296ed2f.png)

[sina-weibo.zip](https://github.com/Templarian/MaterialDesign/files/1149660/sina-weibo.zip)

**Comment by 531149907** [comment]
Thank you，Augustin！The icon is great！

**Comment by MrGrigri** [comment]
@531149907, Wait for us to close the issue. We use it to track it being added and implemented into the code.

**Comment by Templarian** [comment]
[![sina-weibo](https://materialdesignicons.com/icon/sina-weibo)](https://materialdesignicons.com/icon/sina-weibo)
