### ISSUE TITLE
Request: cargo ship

### ISSUE THREAD

**Issue by sarahr4888** [Templarian/MaterialDesign#2237]
The transportation icons are great, but missing any variations on boats, except for the ferry, which looks kind of like a tugboat or small coast guard craft. 

Attached is an example of what the few icons I've seen tend to look like. Thanks!
![cargoship](https://user-images.githubusercontent.com/30124016/28128952-51bde96c-66e6-11e7-942e-82ebc93dc7d0.png)

**Comment by JamesCoyle** [comment]
Would this suit your needs?
[![ferry](https://materialdesignicons.com/icon/ferry)](https://materialdesignicons.com/icon/ferry)

The example you've provided is too detailed for the material spec unfortunately. I don't think we'd be able to do much better than ferry.

**Comment by Templarian** [comment]
Alias added `cargo-ship`.
