### ISSUE TITLE
Currency (KZT) Kazakhstan tenge

### ISSUE THREAD

**Issue by YerlenZhubangaliyev** [Templarian/MaterialDesign#2239]
Currency KZT (Kazakhstan tenge)

![tenge](https://f.cloud.github.com/assets/1582996/1500046/471cae78-486b-11e3-8b21-d6ed941cba81.png)

http://www.unicode.org/L2/L2008/08116-n3392-tenge.pdf

http://www.fileformat.info/info/unicode/char/20b8/index.htm

**Comment by augustin32** [comment]
![tenge24](https://user-images.githubusercontent.com/14167196/28219246-019fcbf0-68c4-11e7-88a8-edfcc466b799.png)
<img width="18" alt="tenge36" src="https://user-images.githubusercontent.com/14167196/28219248-032bdb44-68c4-11e7-88b2-f06326396c89.png">
![tenge48](https://user-images.githubusercontent.com/14167196/28219254-05de3800-68c4-11e7-91b3-7e70fa3cee96.png)

[tenge.zip](https://github.com/Templarian/MaterialDesign/files/1148920/tenge.zip)

**Comment by PeterShaggyNoble** [comment]
Looking at FA issue @YerlenZhubangaliyev opened for this, it seems to be in fairly high demand; 60 comments and 17 👍s so I'm gonna label this as High Priority.

**Comment by Templarian** [comment]
[![currency-kzt](https://materialdesignicons.com/icon/currency-kzt)](https://materialdesignicons.com/icon/currency-kzt)
