### ISSUE TITLE
Fountain

### ISSUE THREAD

**Issue by felix63** [Templarian/MaterialDesign#2240]
Hi. I would like to have an icon for a fountain. Something like: http://icons.iconarchive.com/icons/icons8/windows-8/512/City-Fountain-icon.png

**Comment by augustin32** [comment]
![fountain24](https://user-images.githubusercontent.com/14167196/28217542-1e009636-68be-11e7-8d9e-c657ce91be88.png)
![fountain36](https://user-images.githubusercontent.com/14167196/28217543-1fa62636-68be-11e7-9fb0-b85a3805d8f0.png)
![fountain48](https://user-images.githubusercontent.com/14167196/28217548-21c2fce6-68be-11e7-81eb-72714028c3a2.png)

[fountain.zip](https://github.com/Templarian/MaterialDesign/files/1148793/fountain.zip)

**Comment by CoDEmanX** [comment]
Isn't it better recognizable without the gap at the bottom?

![image](https://user-images.githubusercontent.com/1309249/38771410-4845dbf8-4023-11e8-9310-b821e0cbd77b.png)

**Comment by Templarian** [comment]
[![fountain](https://materialdesignicons.com/icon/fountain)](https://materialdesignicons.com/icon/fountain)
