### ISSUE TITLE
Angles (e.g., swing & elevation)

### ISSUE THREAD

**Issue by xhermes** [Templarian/MaterialDesign#2244]
i tried searching but i can't find any icons to represent angles. :）

**Comment by augustin32** [comment]
What about these?
![swing-angle24](https://user-images.githubusercontent.com/14167196/28236807-b81374ee-6938-11e7-9bf3-dc6f6d77ccbf.png) ![elevation-angle24](https://user-images.githubusercontent.com/14167196/28236810-bb23e006-6938-11e7-97a0-b03645f0066b.png)
![swing-angle36](https://user-images.githubusercontent.com/14167196/28236811-c06c5ad4-6938-11e7-816e-f4e884292fc2.png) ![elevation-angle36](https://user-images.githubusercontent.com/14167196/28236813-c3135850-6938-11e7-85fd-b776c5d446dc.png)
![swing-angle48](https://user-images.githubusercontent.com/14167196/28236815-cc3ed850-6938-11e7-81d8-436178d931b7.png) ![elevation-angle48](https://user-images.githubusercontent.com/14167196/28236817-ce9d78fe-6938-11e7-8c19-73a4f9c62ca4.png)

[angles.zip](https://github.com/Templarian/MaterialDesign/files/1150106/angles.zip)

**Comment by xhermes** [comment]
simple and clear, many thanks. 👍

**Comment by augustin32** [comment]
Glad to help :-)

**Comment by MrGrigri** [comment]
I believe that we need to break this down into the three common angles. 

- [ ] Acute (less than 90º)
- [ ] Right (90º)
- [ ] Obtuse (more than 90º)

**Comment by JapanYoshi** [comment]
![path4173](https://user-images.githubusercontent.com/8707990/28364793-674b01a0-6cc9-11e7-8542-5c536618ef07.png)
![path4174](https://user-images.githubusercontent.com/8707990/28364794-67539e50-6cc9-11e7-8c92-1b787a4c1d24.png)
![path4175](https://user-images.githubusercontent.com/8707990/28364795-6765ee52-6cc9-11e7-9cd3-35994ed1cd6a.png)
[angle.zip](https://github.com/Templarian/MaterialDesign/files/1158931/angle.zip)

**Comment by MrGrigri** [comment]
@JapanYoshi, those look great but I only see the acute angle in that zip.

**Comment by JapanYoshi** [comment]
Oh, it's a layered SVG I made on Inkscape. If you don't have a vector
editor, I'll consolidate each layer later, but I've submitted Inkscape SVGs
before and gotten my icons in MDI.

**Comment by MrGrigri** [comment]
I did open it in Illustrator...and yeah, they're there; my bad. Also, I noticed that they are not optimized. You have both paths and lines not joined. It makes converting them to other formats much simpler. Also, the angle marker should be a radius with the center point being the joint of the two lines. 

[angle.zip](https://github.com/Templarian/MaterialDesign/files/1159624/angle.zip)

**Comment by CoDEmanX** [comment]
As three separate files:

[angle.zip](https://github.com/Templarian/MaterialDesign/files/1910724/angle.zip)

**Comment by PeterShaggyNoble** [comment]
Should the inner part of `angle-right` not be an arc also?

**Comment by GreenTurtwig** [comment]
No, right angles are represented by a square.
