### ISSUE TITLE
Doctor icon

### ISSUE THREAD

**Issue by emami7495** [Templarian/MaterialDesign#2245]

**Comment by augustin32** [comment]
Tried to put the cross in center, but it doesn't look good in small resolutions
![doctor24](https://user-images.githubusercontent.com/14167196/28247290-381db0b6-6a36-11e7-9120-12313f9b44ad.png)
![doctor36](https://user-images.githubusercontent.com/14167196/28247293-3a25c218-6a36-11e7-9448-1975fc56c44c.png)
![doctor48](https://user-images.githubusercontent.com/14167196/28247295-3c770612-6a36-11e7-99da-c53ca70ef67e.png)

![doctor-variant24](https://user-images.githubusercontent.com/14167196/28247332-d24ed994-6a36-11e7-9c9c-deea7f162d1c.png)
![doctor-variant36](https://user-images.githubusercontent.com/14167196/28247333-d46ef4b6-6a36-11e7-9e71-bd68f137e661.png)
![doctor-variant48](https://user-images.githubusercontent.com/14167196/28247334-d6ce7a60-6a36-11e7-8739-8babe844da89.png)

[doctor.zip](https://github.com/Templarian/MaterialDesign/files/1150994/doctor.zip)

**Comment by emami7495** [comment]
Thank you very much for the time you spend, an interesting icon :)

**Comment by Ch-Lo** [comment]
I really like this doc-icon:
[http://fontawesome.io/icon/user-md/](http://fontawesome.io/icon/user-md/)

**Comment by CoDEmanX** [comment]
The variant (2nd) looks pretty good

**Comment by Templarian** [comment]
[![doctor](https://materialdesignicons.com/icon/doctor)](https://materialdesignicons.com/icon/doctor)
