### ISSUE TITLE
Cowboy icon

### ISSUE THREAD

**Issue by augustin32** [Templarian/MaterialDesign#2247]
Cowboy icon for issue #2104
![cowboy24](https://user-images.githubusercontent.com/14167196/28247822-0ca9e6c4-6a41-11e7-8e21-ff52664b4e3c.png)
![cowboy36](https://user-images.githubusercontent.com/14167196/28247823-0e09dd08-6a41-11e7-8bbc-c5f4c44c81de.png)
![cowboy48](https://user-images.githubusercontent.com/14167196/28247825-0fda29ee-6a41-11e7-95ea-70b6a667e164.png)

[cowboy.zip](https://github.com/Templarian/MaterialDesign/files/1151029/cowboy.zip)

**Comment by Templarian** [comment]
Added. 😃
