### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by Mauronic** [Templarian/MaterialDesign#2250]
Like the add note icon in google calendar

**Comment by JamesCoyle** [comment]
![image](https://user-images.githubusercontent.com/10384436/28292569-7a8bb45e-6b47-11e7-98b6-943dd82e4a52.png)

Preview isn't the best but figured these were simple enough to throw together. 

[text.svg](http://james-coyle.com/svg/text.svg)
[text-short.svg](http://james-coyle.com/svg/text-short.svg)

**Comment by PeterShaggyNoble** [comment]
`notes` is available in Google's Extended icon set and there's also `subject` & `short text` in the stock icons, which are similar.

![notes](https://user-images.githubusercontent.com/15157491/37151239-8472b462-22cc-11e8-9c32-b77447a5ae6f.png) [![subject](https://user-images.githubusercontent.com/15157491/37151143-424b6d72-22cc-11e8-8ef8-97b426c840cb.png)](https://material.io/icons/#ic_subject) [![short text](https://user-images.githubusercontent.com/15157491/37151196-68d214b4-22cc-11e8-92be-9ab153ff2df2.png)](https://material.io/icons/#ic_short_text)

**Comment by Alekhen** [comment]
Here's a screenshot from google calendar where they're using the "notes" icon.

<img width="651" alt="google-calendar-notes" src="https://user-images.githubusercontent.com/1837101/37170017-e9799f02-22c6-11e8-82f6-e28997d5dcf6.png">

Notice how the third line in the icon only extends to the midpoint and not the 3/4 mark like the "short-text" icon discussed above. It's also wider at 18px as opposed to 16px. Perhaps we could call this icon "text-note"?

![text-note-24](https://user-images.githubusercontent.com/1837101/37170596-7a4a238e-22c8-11e8-8da8-d5c7187c19ef.png)
![text-note](https://user-images.githubusercontent.com/1837101/37170600-7d8ac512-22c8-11e8-80e4-0c13c719a7d8.png)
[text-note.svg.zip](https://github.com/Templarian/MaterialDesign/files/1794407/text-note.svg.zip)

**Comment by Mauronic** [comment]
Looks good :)

**Comment by Templarian** [comment]
`text`, `text-short`, and `text-subject`

[![text](https://materialdesignicons.com/icon/text)](https://materialdesignicons.com/icon/text) [![text-short](https://materialdesignicons.com/icon/text-short)](https://materialdesignicons.com/icon/text-short) [![text-subject](https://materialdesignicons.com/icon/text-subject)](https://materialdesignicons.com/icon/text-subject)
