### ISSUE TITLE
How to load selected icons only

### ISSUE THREAD

**Issue by MikeElghali** [Templarian/MaterialDesign#2251]
Hi,

Is it possible to load a set of selected icons only and not the entire font library?

Thanks.

Regards.

**Comment by JamesCoyle** [comment]
You can load the Svgs for the ones you want.

**Comment by MikeElghali** [comment]
OK, so i need to download them separately ?

**Comment by JamesCoyle** [comment]
Currently yes. If you're using a lot of icons and/or often add more icons I'd recommend just using the full font and set up caching unless you are inlining the SVG in HTML.

**Comment by MikeElghali** [comment]
Nice, thank you for the help!
