### ISSUE TITLE
Flowchart

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2253]
I have come across a need for a workflow icon. This might have something to do with #1227. Here was my creation for a Flowchart.

![flowchart](https://user-images.githubusercontent.com/4528551/28327913-10b4dd7a-6ba2-11e7-8463-cd79c5a4e84b.png)

[flowchart.zip](https://github.com/Templarian/MaterialDesign/files/1156537/flowchart.zip)

**Comment by JapanYoshi** [comment]
This looks overly complicated...

**Comment by Ch-Lo** [comment]
Maybe just remove the upper bubble? I think this would simplity it a lot.

**Comment by MrGrigri** [comment]
Removed and I also changed the path from 2px to 1.5px. 

![flowchart-simple](https://user-images.githubusercontent.com/4528551/28428687-54a9e908-6d37-11e7-9889-d44edc1c4e33.png)

[flowchart.zip](https://github.com/Templarian/MaterialDesign/files/1163051/flowchart.zip)
