### ISSUE TITLE
Contribution: Travis CI Icon

### ISSUE THREAD

**Issue by shroudedcode** [Templarian/MaterialDesign#2254]
An icon for the continuous integration service @travis-ci!
The icon is based on the header logo on https://travis-ci.org/. I simplified it and unioned it together.

![Travis CI](https://user-images.githubusercontent.com/29176678/28339597-e0c5b7a4-6c0c-11e7-9ff4-c00eb82dfd47.PNG)
![Travis CI](https://user-images.githubusercontent.com/29176678/28339549-b825f16a-6c0c-11e7-805a-1bdc3aa25b82.PNG)
![Travis CI](https://user-images.githubusercontent.com/29176678/28339498-934a2ac8-6c0c-11e7-9a13-0d2c059f8ffb.PNG)

[travis-ci.svg.zip](https://github.com/Templarian/MaterialDesign/files/1157280/travis-ci.svg.zip)

**Comment by k5cents** [comment]
Simply too complicated for this style, in my opinion. Not sure if it's even popular enough to warrant such an icon?

**Comment by MrGrigri** [comment]
I agree this is way out of the scope of Material Designed icons.

**Comment by shroudedcode** [comment]
@k5cents @MrGrigri It's definitely popular enough in my opinion. @gulpjs, @babel, @webpack, @sass and many more open-source projects use it. @facebook, @twitter and @heroku also use it for their CI.

I agree though that my current icon might be still too complex. You can obviously have a try at simplifying it if you want.

**Comment by JapanYoshi** [comment]
Yeah nah, this doesn't look right or needed in the scope of MDI. I don't even know what the heck a continuous integration service is.

**Comment by shroudedcode** [comment]
@JapanYoshi

**Comment by wopian** [comment]
👍 The lack of (highly) popular developer-oriented services outside the random selection of JS frameworks and VSCs keeps preventing me from using this 😞

**Comment by JapanYoshi** [comment]
God, this is Ethereum all over again.

**Comment by JamesCoyle** [comment]
Using an icon that actually reflects the projects status would be much better from a users standpoint. No one knows what this is unless they have set up a project that uses it.
