### ISSUE TITLE
Moon icon

### ISSUE THREAD

**Issue by saiichihashimoto** [Templarian/MaterialDesign#2255]
Could the stroke on #1727 be sharper like the moon in `theme-light-dark`? It currently doesn't fit too well with the other material design icons...

**Comment by GreenTurtwig** [comment]
Moon icon from the YouTube redesign, alongside https://github.com/Templarian/MaterialDesign/issues/2367.
[moon.zip](https://github.com/Templarian/MaterialDesign/files/1268433/moon.zip)

**Comment by goyney** [comment]
@GreenTurtwig I am unable to find this icon in any Google icon set or the YouTube application. I'm not sure this is a stock icon.

Would this issue be resolved by #2603?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49038624-7a55ed80-f18b-11e8-821a-27ebd33b8b1d.png)
[moon.svg.zip](https://github.com/Templarian/MaterialDesign/files/2617124/moon.svg.zip)

**Comment by goyney** [comment]
Added all 8 phases of the moon in #2603. Not sure we need another, slightly angled, waning crescent. :)
