### ISSUE TITLE
Shield with check mark

### ISSUE THREAD

**Issue by RyderMais** [Templarian/MaterialDesign#2256]

**Comment by wopian** [comment]
https://materialdesignicons.com/icon/verified

**Comment by JamesCoyle** [comment]
Needs aliasing shield but I can't add labels on mobile.

**Comment by Ch-Lo** [comment]
I suggest "shield-check" as alias, so its found by "check" and "shield".

**Comment by Templarian** [comment]
Done. Thanks!
