### ISSUE TITLE
arrow-collapse-all not working

### ISSUE THREAD

**Issue by iHaruku** [Templarian/MaterialDesign#2258]
I'm using version 1.9.32. The code I used was `<i class="mdi mdi-arrow-collapse-all"></i>` and it doesn't seem like there is any CSS for that class.

**Comment by JamesCoyle** [comment]
It's named `arrow-compress-all` in that version. It has been renamed for the next release.

**Comment by Templarian** [comment]
By the way @iHaruku next release will be out shortly, just remember to rename it. Only 2 icons were renamed in the next release. This was one. #1983
