### ISSUE TITLE
H(eading)1 ... H(eading)6 and P(aragraph) icons for editor 

### ISSUE THREAD

**Issue by kpgarrod** [Templarian/MaterialDesign#226]
These are often used in embedded editors and would be nice to have

- [x] format-header-pound
- [x] format-header-1
- [x] format-header-2
- [x] format-header-3
- [x] format-header-4
- [x] format-header-5
- [x] format-header-6
- [x] format-paragraph

**Comment by Templarian** [comment]
![format-bold](https://cloud.githubusercontent.com/assets/338885/6746292/d8c18cd6-ce93-11e4-9f38-e3af5215958f.png) ![format-italic](https://cloud.githubusercontent.com/assets/338885/6746286/d293f5f6-ce93-11e4-8b62-7e4aa8ba76bc.png) ![format-paragraph](https://cloud.githubusercontent.com/assets/338885/6746314/20f3738e-ce94-11e4-98a1-16ffa3a4a41a.png) ![header-pound](https://cloud.githubusercontent.com/assets/338885/6746202/620244ba-ce92-11e4-91d6-4b2e66d54ef4.png) ![header-1](https://cloud.githubusercontent.com/assets/338885/6746203/67525df6-ce92-11e4-972d-0db898538ceb.png) ![header-3](https://cloud.githubusercontent.com/assets/338885/6746204/6a4b4d88-ce92-11e4-80af-5cdcb1299c65.png) ![header-4](https://cloud.githubusercontent.com/assets/338885/6746205/6c6b3646-ce92-11e4-8536-0d517ce499b7.png) ![header-5](https://cloud.githubusercontent.com/assets/338885/6746233/e65f6e90-ce92-11e4-9bba-0929b03cb15f.png) ![header-6](https://cloud.githubusercontent.com/assets/338885/6746206/6ed68d0e-ce92-11e4-8577-ba96aa5b5912.png)

Above are the rough drafts. I placed bold and italic in the mix to show the difference.

I'm going to ask feedback from the other contributors, but would like to hear your feedback also.

**Comment by Templarian** [comment]
![format-bold](https://cloud.githubusercontent.com/assets/338885/6763675/acc03e3a-cf55-11e4-9fbf-43fb4f98d016.png) ![format-italic](https://cloud.githubusercontent.com/assets/338885/6763676/aff651ca-cf55-11e4-8216-2c671e815f5d.png) ![format-paragraph](https://cloud.githubusercontent.com/assets/338885/6763677/b2fb46f0-cf55-11e4-8a5c-a9bcb8d0c111.png) ![header-pound](https://cloud.githubusercontent.com/assets/338885/6763687/c7f6b4c2-cf55-11e4-8ac7-bd7418283b17.png) ![header-1](https://cloud.githubusercontent.com/assets/338885/6763678/b520e6a6-cf55-11e4-864f-1cca5a932e6a.png) ![header-2](https://cloud.githubusercontent.com/assets/338885/6763680/b87a5530-cf55-11e4-8172-07a825bb5282.png) ![header-3](https://cloud.githubusercontent.com/assets/338885/6763681/bacb2882-cf55-11e4-83f5-091fb372cfd3.png) ![header-4](https://cloud.githubusercontent.com/assets/338885/6763682/bcfe16be-cf55-11e4-8b04-4a015fc09a5e.png) ![header-5](https://cloud.githubusercontent.com/assets/338885/6763683/bee02fa8-cf55-11e4-9a5b-b392b62dd016.png) ![header-6](https://cloud.githubusercontent.com/assets/338885/6763685/c197c51c-cf55-11e4-8046-80f2922f81a5.png)

Revised are above. The `format-paragraph` and `format-header-5` got revised.

**Comment by kpgarrod** [comment]
Thanks very much for the swift response. The icons look great - no feedback
from my side.
