### ISSUE TITLE
Filled gift icon

### ISSUE THREAD

**Issue by Jonie90** [Templarian/MaterialDesign#2261]
I wish for a filled gift icon, thanks!

**Comment by MrGrigri** [comment]
This one is a bit tricky. Does this do the trick?

![gift-filled](https://user-images.githubusercontent.com/4528551/28429091-b5a3beea-6d38-11e7-88d9-196fa3defe5f.png)

[gift.zip](https://github.com/Templarian/MaterialDesign/files/1163083/gift.zip)

**Comment by PeterShaggyNoble** [comment]
When (if) this is added, it should probably be named `gift` with the current icon renamed as `gift-outline`.

**Comment by CoDEmanX** [comment]
Slightly modified:

![image](https://user-images.githubusercontent.com/1309249/38771597-39505bde-4026-11e8-9018-a68dd854dc19.png)
[gift-filled.zip](https://github.com/Templarian/MaterialDesign/files/1910742/gift-filled.zip)

**Comment by Templarian** [comment]
Renamed `gift` to `gift-outline`. Added this as a new icon with the name `gift`.
