### ISSUE TITLE
View Comfy Icon

### ISSUE THREAD

**Issue by saiichihashimoto** [Templarian/MaterialDesign#2263]
The [view comfy](https://material.io/icons/#ic_view_comfy) icon would be wonderful.

**Comment by PeterShaggyNoble** [comment]
We should probably also add [`view compact`](https://material.io/icons/#ic_view_compact) at the same time.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49035449-c3ee0a80-f182-11e8-9ec6-ff9dacdfd3d6.png)
[view-comfy.svg.zip](https://github.com/Templarian/MaterialDesign/files/2616937/view-comfy.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Outlined version of `view -comfy` plus both versions of `view compact`. Don't much like the outlined versions, though.

[![view-comfy-outline](https://user-images.githubusercontent.com/15157491/49089751-219e5780-f254-11e8-881a-f59a083560c1.png)](https://github.com/Templarian/MaterialDesign/files/2620461/view-comfy-outline.zip)

[![view-compact](https://user-images.githubusercontent.com/15157491/49090026-c456d600-f254-11e8-90be-e64ba46a32a1.png)](https://github.com/Templarian/MaterialDesign/files/2620473/view-compact.zip) [![view-compact-outline](https://user-images.githubusercontent.com/15157491/49090097-ee0ffd00-f254-11e8-9f9c-b5a9797b7ff4.png)](https://github.com/Templarian/MaterialDesign/files/2620475/view-compact-outline.zip)

**Comment by Templarian** [comment]
Added the three, except `view-comfy-outline`, just doesn't correctly represent what the original looks like.

**Comment by magisters-org** [comment]
Seems like this icon dosn't exist in builded styles. Can't find .mdi-view-comfy in cheatsheet and styles, but homepage have this icon in filtered list. Any help will be appreciated :)

**Comment by Templarian** [comment]
@magisters-org This is in the `3.6.xx` milestone which is unreleased.

https://dev.materialdesignicons.com/history is the easiest way to see if an icon is in a release. We do about one release every month.
