### ISSUE TITLE
Missing Material.io Icons

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#2265]
I noticed the https://material.io/icons/ repo has quite a few icons not on this site. Here are just a few I pulled to use for my own use:

- [x] [ic_golf_course_black_24px.zip](https://github.com/Templarian/MaterialDesign/files/1163979/ic_golf_course_black_24px.zip)
- [ ] [ic_live_tv_black_24px.zip](https://github.com/Templarian/MaterialDesign/files/1163981/ic_live_tv_black_24px.zip)
- [ ] [ic_ondemand_video_black_24px.zip](https://github.com/Templarian/MaterialDesign/files/1163980/ic_ondemand_video_black_24px.zip)
- [x] [ic_style_black_24px.zip](https://github.com/Templarian/MaterialDesign/files/1163984/ic_style_black_24px.zip)
- [ ] [ic_tap_and_play_black_24px.zip](https://github.com/Templarian/MaterialDesign/files/1163982/ic_tap_and_play_black_24px.zip)
- [ ] [ic_devices_other_black_24px.zip](https://github.com/Templarian/MaterialDesign/files/1163983/ic_devices_other_black_24px.zip) - See #3079

I also noticed some like the `gavel`, `paw`, `motorcycle`, and `router` varry from those the contributors here have created.

Just something I noticed!

**Comment by goyney** [comment]
Here are the 3 missing stock icons in this issue:

![image](https://user-images.githubusercontent.com/1015040/49035304-60fc7380-f182-11e8-88aa-2074aa2ae837.png)![image](https://user-images.githubusercontent.com/1015040/49035312-68238180-f182-11e8-9922-a0871b31ddce.png)
![image](https://user-images.githubusercontent.com/1015040/49035345-7ec9d880-f182-11e8-9f26-013eca5d4017.png)

[stock.zip](https://github.com/Templarian/MaterialDesign/files/2616927/stock.zip)

**Comment by PeterShaggyNoble** [comment]
`devices_other` is being tracked in #3079

**Comment by Templarian** [comment]
`cellphone-nfc` and `television-play` added. The `television-live` was not added as "classic" TV with antenna's is not what we consider modern enough. Would suggest using `television-play` for either.
