### ISSUE TITLE
Indian currency off 

### ISSUE THREAD

**Issue by sachinuthale** [Templarian/MaterialDesign#2266]
Need a Indian currency icon like: currency-usd-off

**Comment by augustin32** [comment]
![rupee24](https://user-images.githubusercontent.com/14167196/28460645-91698f30-6e1b-11e7-9e40-0665716e0971.png)
<img width="18" alt="rupee36" src="https://user-images.githubusercontent.com/14167196/28460653-95106c30-6e1b-11e7-9dca-76863cefd674.png">
![rupee48](https://user-images.githubusercontent.com/14167196/28460655-975d23ac-6e1b-11e7-898d-225fccb33566.png)

[rupee.zip](https://github.com/Templarian/MaterialDesign/files/1165244/rupee.zip)

**Comment by augustin32** [comment]
"Off" variant doesn't look too good.
![rupee-off24](https://user-images.githubusercontent.com/14167196/28460883-c73eaf9a-6e1c-11e7-827f-1ea40a3253dc.png)
![rupee-off36](https://user-images.githubusercontent.com/14167196/28460885-c9672662-6e1c-11e7-852c-a723e2fafe3d.png)
![rupee-off48](https://user-images.githubusercontent.com/14167196/28460886-cbab45e8-6e1c-11e7-8f93-05cad4cebdce.png)

[rupee-off.zip](https://github.com/Templarian/MaterialDesign/files/1165265/rupee-off.zip)

**Comment by JamesCoyle** [comment]
Line would go the other way.

**Comment by augustin32** [comment]
![rupee-off48](https://user-images.githubusercontent.com/14167196/28462573-79920424-6e24-11e7-845c-be8931a24144.png)
![rupee-off24](https://user-images.githubusercontent.com/14167196/28462572-71d436f8-6e24-11e7-9dee-c46d0fd3dc1d.png)
![rupee-off36](https://user-images.githubusercontent.com/14167196/28462565-6adede3e-6e24-11e7-90c1-0958f19d66ff.png)

[rupee-off.zip](https://github.com/Templarian/MaterialDesign/files/1165402/rupee-off.zip)

**Comment by eyantra-admin** [comment]
Thank you !! This is perfect

**Comment by sachinuthale** [comment]
Thank you !! This is perfect

**Comment by k5cents** [comment]
The line slashing the other way kind of makes it look more like some Japanese character than an "off" state icon.

**Comment by Templarian** [comment]
Unfortunately we're not going to be adding this icon as it would have to be done to every currency.

As we add more currencies we're trying to keep these as singular as possible.
