### ISSUE TITLE
Tor Off

### ISSUE THREAD

**Issue by xubiod** [Templarian/MaterialDesign#2267]
I thought that this would be in the list, but was surprised not to see it, so I made my own.

![tor-off](https://user-images.githubusercontent.com/7144210/28466434-6a3c1c32-6dfa-11e7-9aa0-98bb3862fc7b.png)
![tor-off2x](https://user-images.githubusercontent.com/7144210/28466436-6a3d69ca-6dfa-11e7-8019-85185bdbb377.png)
![tor-off3x](https://user-images.githubusercontent.com/7144210/28466435-6a3d340a-6dfa-11e7-8963-6367b4f3424e.png)

[tor-off.zip](https://github.com/Templarian/MaterialDesign/files/1165681/tor-off.zip)

**Comment by MrGrigri** [comment]
The problem with this icon is that TOR is a brand and doesn't follow the MD guidelines. So combining the two looks out-of-place.

**Comment by Templarian** [comment]
Agreed this is going to be too specific of an icon. Thanks for the suggestion though.
