### ISSUE TITLE
Trackpad Off/Locked

### ISSUE THREAD

**Issue by xubiod** [Templarian/MaterialDesign#2268]
Previews: 
![trackpad-off](https://user-images.githubusercontent.com/7144210/28473264-d7931878-6e11-11e7-9ba5-f40c93086289.png)
![trackpad-off2x](https://user-images.githubusercontent.com/7144210/28473265-d796ff38-6e11-11e7-9562-15df49dc8760.png)
![trackpad-off3x](https://user-images.githubusercontent.com/7144210/28473263-d792c382-6e11-11e7-9a3e-6161ff70b31a.png)

[trackpad-off.zip](https://github.com/Templarian/MaterialDesign/files/1166174/trackpad-off.zip)

**Comment by Templarian** [comment]
Trackpad lock may make more sense contextually. 🤔

**Comment by xubiod** [comment]
@Templarian I tried, but someone more experienced could do it better.

![trackpad-locked](https://user-images.githubusercontent.com/7144210/28475501-848a087c-6e1a-11e7-9b54-e26ac0b794b3.png)
![trackpad-locked2x](https://user-images.githubusercontent.com/7144210/28475500-8484959a-6e1a-11e7-803a-5307dcfa7b75.png)
![trackpad-locked3x](https://user-images.githubusercontent.com/7144210/28475502-848c6a90-6e1a-11e7-8955-3b9df9f1a341.png
[trackpad-locked.zip](https://github.com/Templarian/MaterialDesign/files/1166291/trackpad-locked.zip)

**Comment by Templarian** [comment]
We have a standard lock that should look fine with a 2px cut out around it.

**Comment by JamesCoyle** [comment]
There is a specific lock shape we use for when a lock is a sub icon.

**Comment by xubiod** [comment]
@Templarian @JamesCoyle Is this lock icon that is the subicon? It looks better than my lock, and it's Google's icon for locked.

![trackpad-locked-alt](https://user-images.githubusercontent.com/7144210/28485254-3c752c16-6e46-11e7-9211-5c90a26deb21.png)
![trackpad-locked-alt2x](https://user-images.githubusercontent.com/7144210/28485255-3c765e38-6e46-11e7-82e2-911e90f60a15.png)
![trackpad-locked-alt3x](https://user-images.githubusercontent.com/7144210/28485256-3c794832-6e46-11e7-935c-d599852eb685.png)
[trackpad-locked.zip](https://github.com/Templarian/MaterialDesign/files/1166921/trackpad-locked.zip)

**Comment by xubiod** [comment]
I moved the lock a bit and it looks better.

![trackpad-locked-alt](https://user-images.githubusercontent.com/7144210/28485488-fa89703a-6e47-11e7-801c-1aa85a8da837.png)
![trackpad-locked-alt2x](https://user-images.githubusercontent.com/7144210/28485487-fa866ca0-6e47-11e7-81f4-3a9fd2bcf24c.png)
![trackpad-locked-alt3x](https://user-images.githubusercontent.com/7144210/28485486-fa8441b4-6e47-11e7-99b7-9baab6e7dc70.png)

[trackpad-locked.zip](https://github.com/Templarian/MaterialDesign/files/1166938/trackpad-locked.zip)

**Comment by CoDEmanX** [comment]
Without the circle, with 1 and 2 pixels margin (the latter has the trackpad moved up 1px to avoid cutting the trackpad field open):

![image](https://user-images.githubusercontent.com/1309249/38771719-53721172-4028-11e8-9c78-86bc9d036957.png)

![image](https://user-images.githubusercontent.com/1309249/38771715-3f062066-4028-11e8-885a-c311cef5add7.png)

[trackpad-lock.zip](https://github.com/Templarian/MaterialDesign/files/1910764/trackpad-lock.zip)

**Comment by Templarian** [comment]
[![trackpad-lock](https://materialdesignicons.com/icon/trackpad-lock)](https://materialdesignicons.com/icon/trackpad-lock)
