### ISSUE TITLE
vue.js logo

### ISSUE THREAD

**Issue by ParsCasts** [Templarian/MaterialDesign#2269]
Would you please add the icon of some famous web technologies to your web font ?
such as laravel , Vue.js or apache ? #iconRequest

**Comment by Templarian** [comment]
@ParsCasts Renamed this issue, can you please create individual icon requests (double check they don't already exist). We track 1 icon per issue.

**Comment by Templarian** [comment]
[![vuejs](https://materialdesignicons.com/icon/vuejs)](https://materialdesignicons.com/)

**Comment by rafaelpimpa** [comment]
I'm trying to use the icon with the ``2.0.46`` version but doesn't seen to work.

```
<i class="mdi mdi-vuejsmdi-48px"></i>
```

Every other icon is working fine.

**Comment by Templarian** [comment]
@rafaelpimpa We're working on the next release. This icon was added after the `2.0.46` release.

https://materialdesignicons.com/history

**Comment by rafaelpimpa** [comment]
Ok thanks for the info!
