### ISSUE TITLE
Venmo

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2270]
I pulled the Venmo logotype from their [brand style guide](http://brand.venmo.com/styleguide) and isolated the V.

Although, they may prefer we box it like `twitter-box` to match their [shortened logo mark](http://brand.venmo.com/img/logo-mark.png).

![venmo](https://user-images.githubusercontent.com/18021678/28492880-1b6896d2-6ed9-11e7-9e72-47f61e8828d8.png)

[venmo.svg.zip](https://github.com/Templarian/MaterialDesign/files/1167474/venmo.svg.zip)

**Comment by k5cents** [comment]
Still needs to be fitted to the MD guidelines. I am not quite at that level of skill/technology yet.

**Comment by MrGrigri** [comment]
Branded icons don't get materialized. Just make sure that they are centered and fit inside the 20x20 area.

**Comment by Templarian** [comment]
I'm going to be replacing the vine icon with this icon and renaming it in the system for the next release.

Vine is already pretty much dead, can't see any reason why to keep it in the icon pack.

**Comment by Templarian** [comment]
[![venmo](https://materialdesignicons.com/icon/venmo)](https://materialdesignicons.com/icon/venmo)
