### ISSUE TITLE
Scroll lock

### ISSUE THREAD

**Issue by AdrianVovk** [Templarian/MaterialDesign#2272]
I'd like a scroll lock icon for my keyboard (see layout here [Keyboard-Layout-Editor](http://www.keyboard-layout-editor.com/##@_name=CoolerMaster%20MasterKeys%20S%20PBT&author=Adrian%20Vovk&background_name=PBT%20Black&style=background-image%2F:%20url('%2F%2Fbg%2F%2Fplastic%2F%2Fpbt-black.png')%2F%3B%3B&radii=7px&switchMount=cherry&switchBrand=cherry&switchType=MX1A-F1xx&plate:true&css=%2F@font-face%20%7B%0A%20%20font-family%2F:%20%22font-linux%22%2F%3B%0A%20%20%2F%2F*src%2F:%20url(%22https%2F:%2F%2F%2F%2Fraw.githubusercontent.com%2F%2FLukas-W%2F%2Ffont-linux%2F%2Fmaster%2F%2Fassets%2F%2Ffont-linux.eot%3F%23iefix%22)%20format(%22embedded-opentype%22),*%2F%2F%0A%20%20src%2F:%20url(%22https%2F:%2F%2F%2F%2Fraw.githubusercontent.com%2F%2FLukas-W%2F%2Ffont-linux%2F%2Fmaster%2F%2Fassets%2F%2Ffont-linux.woff%22)%20format(%22woff%22)%2F%3B%0A%20%20%2F%2F*src%2F:%20url(%22https%2F:%2F%2F%2F%2Fraw.githubusercontent.com%2F%2FLukas-W%2F%2Ffont-linux%2F%2Fmaster%2F%2Fassets%2F%2Ffont-linux.ttf%22)%20format(%22truetype%22)%2F%3B*%2F%2F%0A%20%20%2F%2F*src%2F:%20url(%22https%2F:%2F%2F%2F%2Fraw.githubusercontent.com%2F%2FLukas-W%2F%2Ffont-linux%2F%2Fmaster%2F%2Fassets%2F%2Ffont-linux.svg%23font-linux%22)%20format(%22svg%22)%2F%3B*%2F%2F%0A%20%20font-weight%2F:%20400%2F%3B%0A%20%20font-style%2F:%20normal%2F%3B%0A%7D%0A.fl%20%7B%0A%20%20%20font-family%2F:%20%22font-linux%22%2F%3B%0A%20%20%20font-style%2F:%20normal%2F%3B%0A%20%20%20font-size%2F:%201em%2F%3B%0A%7D%0A%2F@font-face%20%7B%0A%20%20%20%20font-family%2F:%20MaterialDesignIcons%2F%3B%0A%20%20%20%20src%2F:%20url(%22https%2F:%2F%2F%2F%2Fraw.githubusercontent.com%2F%2FTemplarian%2F%2FMaterialDesign-Webfont%2F%2Fmaster%2F%2Ffonts%2F%2Fmaterialdesignicons-webfont.woff2%22)%20format(%22woff2%22)%2F%3B%0A%20%20%20%20font-weight%2F:%20400%2F%3B%0A%20%20%20%20font-style%2F:%20normal%2F%3B%0A%7D%0A.mdi%20%7B%0A%20%20%20%20font-family%2F:%20MaterialDesignIcons%2F%3B%0A%20%20%20%20font-style%2F:%20normal%2F%3B%0A%20%20%20%20font-size%2F:%201em%2F%3B%0A%7D%0A%0A.fl-distro%2F:after%20%7B%20content%2F:%20%22%5Cf10d%22%2F%3B%20%7D%0A.mdi-esc%2F:after%20%7B%20content%2F:%20%22%5CF46E%22%2F%3B%7D%0A.mdi-fn%2F:after%20%7B%20content%2F:%20%22%5CF295%22%2F%3B%7D%0A.mdi-ctrl%2F:after%20%7B%20content%2F:%20%22%5CF143%22%2F%3B%7D%0A.mdi-shift%2F:after%20%7B%20content%2F:%20%22%5CF636%22%2F%3B%7D%0A.mdi-alt%2F:after%20%7B%20content%2F:%20%22%5CF635%22%2F%3B%7D%0A.mdi-caps%2F:after%20%7B%20content%2F:%20%22%5CF30E%22%2F%3B%7D%0A.mdi-return%2F:after%20%7B%20content%2F:%20%22%5CF311%22%2F%3B%7D%0A.mdi-backspace%2F:after%20%7B%20content%2F:%20%22%5CF06E%22%2F%3B%7D%0A.mdi-insert%2F:after%20%7B%20content%2F:%20%22%5CF5E7%22%2F%3B%20%7D%0A.mdi-delete%2F:after%20%7B%20%0A%20%20%20%20content%2F:%20%22%5CF06E%22%2F%3B%0A%20%20%20%20transform%2F:%20rotate(180deg)%2F%3B%0A%20%20%20%20display%2F:%20inline-block%2F%3B%0A%7D%0A.mdi-home%2F:after%20%7B%20%0A%20%20%20%20content%2F:%20%22%5CF312%22%2F%3B%0A%20%20%20%20transform%2F:%20rotate(180deg)%2F%3B%0A%20%20%20%20display%2F:%20inline-block%2F%3B%0A%7D%0A.mdi-end%2F:after%20%7B%20content%2F:%20%22%5CF312%22%2F%3B%20%7D%0A.mdi-pgup%2F:after%20%7B%20%0A%20%20%20%20content%2F:%20%22%5CF312%22%2F%3B%0A%20%20%20%20transform%2F:%20rotate(270deg)%2F%3B%0A%20%20%20%20display%2F:%20inline-block%2F%3B%0A%7D%0A.mdi-pgdn%2F:after%20%7B%20%0A%20%20%20%20content%2F:%20%22%5CF312%22%2F%3B%20%0A%20%20%20%20transform%2F:%20rotate(90deg)%2F%3B%0A%20%20%20%20display%2F:%20inline-block%2F%3B%0A%7D%0A%0A.mdi-playpause%2F:after%20%7B%20content%2F:%20%22%5CF40E%22%2F%3B%20%7D%0A.mdi-next%2F:after%20%7B%20content%2F:%20%22%5CF4AD%22%2F%3B%20%7D%0A.mdi-volup%2F:after%20%7B%20content%2F:%20%22%5CF75C%22%2F%3B%20%7D%0A.mdi-stop%2F:after%20%7B%20content%2F:%20%22%5CF4DB%22%2F%3B%20%7D%0A.mdi-prev%2F:after%20%7B%20content%2F:%20%22%5CF4AE%22%2F%3B%20%7D%0A.mdi-voldown%2F:after%20%7B%20content%2F:%20%22%5CF75D%22%2F%3B%20%7D%0A%0A.mdi-up%2F:after%20%7B%20content%2F:%20%22%5CF05D%22%2F%3B%7D%0A.mdi-down%2F:after%20%7B%20content%2F:%20%22%5CF045%22%2F%3B%7D%0A.mdi-left%2F:after%20%7B%20content%2F:%20%22%5CF04D%22%2F%3B%7D%0A.mdi-right%2F:after%20%7B%20content%2F:%20%22%5CF054%22%2F%3B%7D%0A%0A.mdi-once%2F:after%20%7B%20content%2F:%20%22%5CF6EA%22%2F%3B%20%7D%0A.mdi-toggle%2F:after%20%7B%20content%2F:%20%22%5CF6E3%22%2F%3B%20%7D%0A.mdi-held%2F:after%20%7B%20content%2F:%20%22%5CF456%22%2F%3B%20%7D%0A%0A.mdi-winlock%2F:after%20%7B%20content%2F:%20%22%5CF33E%22%2F%3B%20%7D%0A.mdi-rec%2F:after%20%7B%20content%2F:%20%22%5CF44A%22%2F%3B%20%7D%0A.mdi-delMacro%2F:after%20%7B%20content%2F:%20%22%5Cf1c0%22%2F%3B%20%7D%0A%0A.mdi-pause%2F:after%20%7B%20content%2F:%20%22%5CF3E4%22%2F%3B%20%7D%0A.mdi-scrlk%2F:after%20%7B%20content%2F:%20%22%5CF33E%22%2F%3B%20%7D%0A.mdi-screenshot%2F:after%20%7B%20content%2F:%20%22%5CF293%22%2F%3B%20%7D%3B&@_c=%232b2c2e&t=%23ffffff&a:7&f:5%3B&=%3Ci%20class%2F='mdi%20mdi-esc'%3E%3C%2F%2Fi%3E&_x:1&f:3%3B&=F1&=F2&=F3&=F4&_x:0.5&a:4&fa@:0&:0&:0&:1%3B%3B&=%0A%0A%0A1x%0A%0A%0A%0A%0A%0AF5&=%0A%0A%0A2x%0A%0A%0A%0A%0A%0AF6&=%0A%0A%0A4x%0A%0A%0A%0A%0A%0AF7&=%0A%0A%0A8x%0A%0A%0A%0A%0A%0AF8&_x:0.5%3B&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-winlock'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0AF9&_a:7%3B&=F10&_a:4%3B&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-rec'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0AF11&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-delMacro'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0AF12&_x:0.25&f:5&fa@:0&:0&:0&:1%3B%3B&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-once'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-screenshot'%3E%3C%2F%2Fi%3E&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-toggle'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-scrlk'%3E%3C%2F%2Fi%3E&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-held'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-pause'%3E%3C%2F%2Fi%3E%3B&@_y:0.5&a:5&f:3%3B&=~%0A%60&=!%0A1&=%2F@%0A2&=%23%0A3&=$%0A4&=%25%0A5&=%5E%0A6&=%2F&%0A7&=*%0A8&=(%0A9&=)%0A0&=%2F_%0A-&=+%0A%2F=&_a:7&f:4&w:2%3B&=%3Ci%20class%2F='mdi%20mdi-backspace'%3E%3C%2F%2Fi%3E&_x:0.25&a:4&f:5&fa@:0&:0&:0&:1%3B%3B&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-playpause'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-insert'%3E%3C%2F%2Fi%3E&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-next'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-home'%3E%3C%2F%2Fi%3E&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-volup'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-pgup'%3E%3C%2F%2Fi%3E%3B&@_a:7&w:1.5%3B&=%3Ci%20class%2F='kb%20kb-Line-Start-End'%3E%3C%2F%2Fi%3E&_f:3%3B&=Q&=W&=E&=R&=T&=Y&=U&=I&=O&=P&_a:5%3B&=%7B%0A%5B&=%7D%0A%5D&_w:1.5%3B&=%7C%0A%5C&_x:0.25&a:4&f:4&fa@:0&:0&:0&:2%3B%3B&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-stop'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-delete'%3E%3C%2F%2Fi%3E&_f:5&fa@:0&:0&:0&:1%3B%3B&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-prev'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-end'%3E%3C%2F%2Fi%3E&=%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-voldown'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0A%0A%3Ci%20class%2F='mdi%20mdi-pgdn'%3E%3C%2F%2Fi%3E%3B&@_a:7&w:1.75%3B&=%3Ci%20class%2F='mdi%20mdi-caps'%3E%3C%2F%2Fi%3E&_f:3%3B&=A&=S&=D&_n:true%3B&=F&=G&=H&_n:true%3B&=J&=K&=L&_a:5%3B&=%2F:%0A%2F%3B&=%22%0A'&_a:7&f:5&w:2.25%3B&=%3Ci%20class%2F='mdi%20mdi-return'%3E%3C%2F%2Fi%3E&_x:0.25&c=%23cccccc&t=%23000000%0A%23ffffff%0A%0A%0A%0A%0A%237f7f7f&a:5&f:3&fa@:0&:1&:0&:0&:0&:0&:2%3B&d:true%3B&=%0A%3Ci%20class%2F='fa%20fa-circle'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0AC&_t=%23000000%0A%23616161%0A%0A%0A%0A%0A%237f7f7f&f2:1&d:true%3B&=%0A%3Ci%20class%2F='fa%20fa-circle'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0AS&_f2:1&d:true%3B&=%0A%3Ci%20class%2F='fa%20fa-circle'%3E%3C%2F%2Fi%3E%0A%0A%0A%0A%0AG%3B&@_c=%232b2c2e&t=%23ffffff&a:7&f:5&w:2.25%3B&=%3Ci%20class%2F='mdi%20mdi-shift'%3E%3C%2F%2Fi%3E&_f:3%3B&=Z&=X&=C&=V&=B&=N&=M&_a:5%3B&=%3C%0A,&=%3E%0A.&=%3F%0A%2F%2F&_a:7&f:5&w:2.75%3B&=%3Ci%20class%2F='mdi%20mdi-shift'%3E%3C%2F%2Fi%3E&_x:1.25%3B&=%3Ci%20class%2F='mdi%20mdi-up'%3E%3C%2F%2Fi%3E%3B&@_w:1.25%3B&=%3Ci%20class%2F='mdi%20mdi-ctrl'%3E%3C%2F%2Fi%3E&_w:1.25%3B&=%3Ci%20class%2F='fl%20fl-distro'%3E%3C%2F%2Fi%3E&_w:1.25%3B&=%3Ci%20class%2F='mdi%20mdi-alt'%3E%3C%2F%2Fi%3E&_f:3&w:6.25%3B&=&_f:5&w:1.25%3B&=%3Ci%20class%2F='mdi%20mdi-alt'%3E%3C%2F%2Fi%3E&_w:1.25%3B&=%3Ci%20class%2F='fl%20fl-distro'%3E%3C%2F%2Fi%3E&_w:1.25%3B&=%3Ci%20class%2F='mdi%20mdi-fn'%3E%3C%2F%2Fi%3E&_w:1.25%3B&=%3Ci%20class%2F='mdi%20mdi-ctrl'%3E%3C%2F%2Fi%3E&_x:0.25%3B&=%3Ci%20class%2F='mdi%20mdi-left'%3E%3C%2F%2Fi%3E&=%3Ci%20class%2F='mdi%20mdi-down'%3E%3C%2F%2Fi%3E&=%3Ci%20class%2F='mdi%20mdi-right'%3E%3C%2F%2Fi%3E))

Could anyone contribute? I'm thinking about a lock with a vertical up-down arrow, but I'm not a designer so I'd be happy to see something better. For the escape I was thinking [this](https://upload.wikimedia.org/wikipedia/commons/d/d1/ISOIEC-9995-7-029--ISO-7000-2029--Symbol-for-Escape.svg) but in material design.

**Comment by JamesCoyle** [comment]
I might try have a go at some of these at some point as one of my many ongoing projects is a custom mechanical keyboard that needs legends for the keys. Not sure when I'll have a chance though.

**Comment by PeterShaggyNoble** [comment]
Escape is also covered in #1348

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/63067616-cdb8c900-bedd-11e9-8914-ec0bad257c89.png)
![image](https://user-images.githubusercontent.com/1015040/63067625-d5786d80-bedd-11e9-9a93-0e3f4f251df0.png)

[arrow-lock.zip](https://github.com/Templarian/MaterialDesign/files/3504022/arrow-lock.zip)

**Comment by goyney** [comment]
[![arrow-horizontal-lock](https://materialdesignicons.com/icon/arrow-horizontal-lock)](https://materialdesignicons.com/icon/arrow-horizontal-lock)[![arrow-vertical-lock](https://materialdesignicons.com/icon/arrow-vertical-lock)](https://materialdesignicons.com/icon/arrow-vertical-lock)
