### ISSUE TITLE
Icons for UpLabs sections

### ISSUE THREAD

**Issue by anjocerdena** [Templarian/MaterialDesign#2273]
Contributing icons for different sections of UpLabs for people who want to link there. These are custom Material redo of the official icons which do not exist in 24×24 sizes.

[UpLabs icons.zip](https://github.com/Templarian/MaterialDesign/files/1167858/UpLabs.icons.zip)

**Comment by MrGrigri** [comment]
The problem with this request is UpLabs is constantly changing their UI and icons. For now, this is what they are using to symbolize the different groups. 

![image](https://user-images.githubusercontent.com/4528551/28689526-284cc410-72d3-11e7-9108-4ae01c17117e.png)

**Comment by PeterShaggyNoble** [comment]
We have all those icons already, bar the 3D one but `video-3d` would probably suffice for that. Or am I missing something?
