### ISSUE TITLE
tags and changelog

### ISSUE THREAD

**Issue by graingert** [Templarian/MaterialDesign#2274]
please tag and provide a changelog for each version

**Comment by graingert** [comment]
ah woops I found the tags and release notes here: https://github.com/Templarian/MaterialDesign-Webfont

**Comment by Templarian** [comment]
http://templarian.com/2017/07/24/material-design-icons-v2-0-46/

(still typing it out, rough draft)

**Comment by Templarian** [comment]
@jacobq http://templarian.com/2018/10/20/material-design-icons-3-0-39/

You can also view the history log: http://dev.materialdesignicons.com/history
