### ISSUE TITLE
Localized variations of local_atm

### ISSUE THREAD

**Issue by anjocerdena** [Templarian/MaterialDesign#2276]
Contributing localized variations of the [local_atm icon](https://material.io/icons/#ic_local_atm) for different currencies. Initial set includes those for:

- [x] [Bitcoin](https://en.wikipedia.org/wiki/Bitcoin)/[Thai Baht](https://en.wikipedia.org/wiki/Thai_baht)
- [x] [Indian Rupee](https://en.wikipedia.org/wiki/Indian_rupee_sign)
- [x] [Philippine Peso](https://en.wikipedia.org/wiki/Philippine_peso_sign)
- [x] [Pound](https://en.wikipedia.org/wiki/Pound_sign)
- [x] [Won](https://en.wikipedia.org/wiki/Won_sign)

[cash with currency icons.zip](https://github.com/Templarian/MaterialDesign/files/1170530/cash.with.currency.icons.zip)

**Comment by JamesCoyle** [comment]
We can't add every currency for each icon that requires it unfortunately. We have the currency icons for each currency available and any other icons are to avoid region specific icons.

**Comment by anjocerdena** [comment]
Hi @JamesCoyle @Templarian,

I'm asking for a reconsideration of this contribution, with the addition of circle, outline, and filled variants of each. I can't mention how many times I've needed a localized version of the cash icon because the dollar sign is a poor representation of the local currency. I believe representation matters in finance or transaction-related products and the existing dollar-biased icons just don't cut it in many common use cases. 'Cash' and 'cash-100' aren't always usable either because they're not generic enough in design (in fact, they still look a lot like US banknotes). They don't even read as cash in many cultures. I think representation—especially in these times—is enough reason to forego the region-specific restriction, if that is a rule. There are many icons with the $ sign, so I don't see how other currency symbols can't be fairly represented in the same way. Please reconsider.

[cash and currency icons.zip](https://github.com/Templarian/MaterialDesign/files/4870838/cash.and.currency.icons.zip)
