### ISSUE TITLE
"Empty List" icon

### ISSUE THREAD

**Issue by rGunti** [Templarian/MaterialDesign#2278]
An icon that represents an empty list, e.g. for a message like "No items found".

**Comment by Ch-Lo** [comment]
Could [playlist-remove](https://materialdesignicons.com/icon/playlist-remove) work?
It could become hard to come up with an icon representing nothing...

**Comment by rGunti** [comment]
Okay, that could be working. I've searched for an icon which does not conflict with "Delete Item".
[playlist-minus](https://materialdesignicons.com/icon/playlist-minus) could do that if I'd use [playlist-remove](https://materialdesignicons.com/icon/playlist-remove) for "No items".
