### ISSUE TITLE
History

### ISSUE THREAD

**Issue by chrislitherland95** [Templarian/MaterialDesign#228]
Reason:
That icon is ancient (2010 and before), I wouldn't use it for "Office365" (https://www.google.com.au/search?q=office+2007&espv=2&biw=1504&bih=872&source=lnms&tbm=isch&sa=X&ei=bqgKVevvBIjk8gXsuYKIDA&ved=0CAcQ_AUoAg#tbm=isch&q=office+2010+box&revid=1496977912)

New (2013+) office Icon looks like: http://products.office.com/en-AU/ (much cleaner, simpler) 

[View History Item](http://materialdesignicons.com/history/3F187B21-BA40-498A-9230-F29907E970C9)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/office

I replaced and renamed `office-365` to just `office`.

**Comment by Templarian** [comment]
Thanks by the way! :smile:
