### ISSUE TITLE
SASS Relative URLs do not work correctly when using mdi bower package in Rails asset pipeline/Sprockets

### ISSUE THREAD

**Issue by nuclearpidgeon** [Templarian/MaterialDesign#2282]
Our company has been trying to use this package within the Ruby on Rails framework (through its 'Asset Pipeline', which is powered by [Sprockets](https://github.com/rails/sprockets)). We've found that, at the moment, the way the font files in the `mdi` bower package for this project are sourced - with relative paths in `src: url()` - causes Sprockets to be unable to trace the font files properly as dependencies, so they don't get included in the asset precompilation process (and consequently don't show up when we deploy on our production servers).

I wasn't able to find an easy way to update the [webfont package itself](https://github.com/Templarian/MaterialDesign-Webfont) to fix the issue without refactoring the whole way the files are stored (see the 'Long-term solution' section) . However I did find a temporary workaround:

## Rails temporary workaround

* writing a custom Rails-centric copy of `_path.scss` (see below)
* using a custom index file that imports everything except `_path` from `mdi` like in the `scss/materialdesignicons.scss`, and then our custom `_path` file instead.

Here's whats in that custom `_path.scss` file. `asset_path()` is the Sprockets helper method for locating an asset file.

```sass
// This file has been copied from mdi and modified as outlined below. Using the
// package default version of this _path.scss file causes path resolution
// issues, especially in Production.
//
// Modifications:
//
// * "?v=" query string has been removed from the paths in url() directives, as
//   Sprockets handles versioning itself with asset fingerprinting
// * url() directives have also been updated to use sprocket's asset_helper
//   with an explicit basename for reaching into the mdi package. This makes
//   sure that Sprockets can find and work with all the font files properly,
//   and that it will pick up the font files as dependencies when precompiling
//   assets

@font-face {
  font-family: '#{$mdi-font-name}';
  src: url(asset_path('mdi/fonts/#{$mdi-filename}-webfont.eot'));
  src: url(asset_path('mdi/fonts/#{$mdi-filename}-webfont.eot?#iefix')) format('embedded-opentype'),
       url(asset_path('mdi/fonts/#{$mdi-filename}-webfont.woff2')) format('woff2'),
       url(asset_path('mdi/fonts/#{$mdi-filename}-webfont.woff')) format('woff'),
       url(asset_path('mdi/fonts/#{$mdi-filename}-webfont.ttf')) format('truetype'),
       url(asset_path('mdi/fonts/#{$mdi-filename}-webfont.svg##{$mdi-filename}#{$mdi-font-weight}')) format('svg');
  font-weight: normal;
  font-style: normal;
}
```

## Long-term solution

I did also look into modifying the webfont package to support Sprockets - you can see a WIP approach to it here: https://github.com/Templarian/MaterialDesign-Webfont/compare/master...captur3d:sprockets-port . The main problem is that I couldn't get it to work without refactoring the whole folder tree to follow a more Sprockets-friendly layout.

My reference for implementing Sprockets support was the [bootstrap-sass package](https://github.com/twbs/bootstrap-sass). If you look in [bootstrap-sass/assets/stylesheets/_bootstrap-sprockets.scss](https://github.com/twbs/bootstrap-sass/blob/5d6b2ebba0c2a5885ce2f0e01e9218db3d3b5e47/assets/stylesheets/_bootstrap-sprockets.scss), you can see that they define a boolean flag variable and two path-finder functions that wrap calling the corresponding helpers in Sprockets. Then in [bootstrap-sass/assets/stylesheets/bootstrap/_glyphicons.scss](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_glyphicons.scss), there's an if check for the boolean flag that determines whether to use the asset helper methods, or whether to just use `url()` directly.

As alluded to earlier, the final problem I hit was that to make it to work properly entirely inside this webfont package (i.e. so we wouldn't need any custom code inside our Rails project), we'd need to add some kind of base `mdi` or `materialdesignicons` folder that everything else would live under, and probably also introduce the `assets/stylesheets`-style directory layout that would wrap that folder as well. Whilst adding the `mdi/` prefix (like we did in our custom `_path.scss` file) works within Rails, it relies on that being the name of the package/the name of the folder that package is copied/checked out into, which is a bit flimsy. This package/repo itself will probably need its own `mdi` folder to make everything work properly.

Making this directory structure change seemed somewhat of a breaking change for non-Sprockets users, so I figured it would be better to just write all this up in case anyone else comes along to use this package in Rails, and mention it to the package author to see if it was worth taking any further. It could be worth at least linking to this issue from the README for Rails users? Similar to the Apache Cordova exception I spotted there already.

---

_This issue was raised in response to feedback from the package maintainer on the webfont github project - see https://github.com/Templarian/MaterialDesign-Webfont/issues/36_

**Comment by Templarian** [comment]
Skimmed the above text, but couldn't you just overwrite the `$mdi-font-path` variable in https://github.com/Templarian/MaterialDesign-Webfont/blob/master/scss/_variables.scss ?

I've done this on a few projects when including the icons in my SCSS compilation.

**Comment by Templarian** [comment]
You might want to look into how people do this for Font Awesome, as this package has a very similar structure as theirs to make it easier for devs.

**Comment by nuclearpidgeon** [comment]
@Templarian I haven't looked at this again since I raised that first issue, but from memory of that time, overriding `$mdi-font-path` only worked in development. For some reason the asset pipeline still didn't pick up that it needed to copy the font files in the asset precompile.

If I can find the time to pick this issue up again, I'll try and reproduce the issue with a simple example Rails app.

Thanks for the suggestion of Font Awesome - I was thinking at the time that it would be useful to look at one or two more Sass packages to see how they work in Rails, but bootstrap was the only other main one we had that I thought of.
