### ISSUE TITLE
Where are "official icon set" icons?

### ISSUE THREAD

**Issue by damianobarbati** [Templarian/MaterialDesign#2288]
As stated in the README `This repo also contains converted icons from Google's official icon set.`

Are you sure about this? :|

**Comment by Templarian** [comment]
Not sure I understand the question. Can you clarify?

**Comment by JamesCoyle** [comment]
It contains around 750 icons from Google's icon pack. We don't always use the name Google does. If there is an icon missing request it.

**Comment by damianobarbati** [comment]
Thanks for replying and sorry for being not clear!
I was comparing icons on https://materialdesignicons.com/ with icons on https://material.io/icons/ but in the former I don't see the latter included.
For instance: where is this icon https://material.io/icons/#ic_3d_rotation?

I'm just asking because right now I'm merging both but if the official icon set is already included I don't need to!

**Comment by Templarian** [comment]
Missing icons are marked with the `google stock icon` label. #1599

There are probably a few missing, we left out a few random ones, will get them added. Was a low priority in the past, now that we're at 2.x we should add the handful of missing ones.

**Comment by Templarian** [comment]
Added it as the first bullet point for #2280 to call.

**Comment by damianobarbati** [comment]
Oh I see. That's why I could find only a few official ones in the repo.
I did try to match the first row of official action icons and I could find only one xD

Do you plan to merge them all any soon? 🤔
This could be very handy since I'm managing a repo for `material-ui` including them all.

**Comment by CoDEmanX** [comment]
See the Google spreadsheet in #420, all missing Google icons should be listed there.
