### ISSUE TITLE
Chart Home

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2289]
In reference to #2275, this is an icon for home analytics, assistance, etc. I believe that it should be called `chart-home` so that it's grouped with the chart icons, and have the aliases of analytics and assistant.

![home-analytics](https://user-images.githubusercontent.com/4528551/28686934-28370070-72ca-11e7-9a1f-a70d9849bb2a.png)

[home-analytics.zip](https://github.com/Templarian/MaterialDesign/files/1180952/home-analytics.zip)

**Comment by Templarian** [comment]
Added. 😃
