### ISSUE TITLE
`Minions' icon

### ISSUE THREAD

**Issue by allen5261** [Templarian/MaterialDesign#2291]
Could you please add a series of `Minions' such as ![Image of minions](https://gss3.bdstatic.com/7Po3dSag_xI4khGkpoWK1HF6hhy/baike/c0%3Dbaike272%2C5%2C5%2C272%2C90/sign=d75c31ffa74bd11310c0bf603bc6cf6a/728da9773912b31baf9818a58c18367adbb4e142.jpg)

**Comment by k5cents** [comment]
lmao

**Comment by JapanYoshi** [comment]
No.

**Comment by Templarian** [comment]
lol
