### ISSUE TITLE
globe

### ISSUE THREAD

**Issue by 4a-j** [Templarian/MaterialDesign#2298]

**Comment by MrGrigri** [comment]
There is already a globe. There are two to choose from. We'll add an alias of `globe`.

![earth](https://materialdesignicons.com/icon/earth) ![earth-box](https://materialdesignicons.com/icon/earth)

**Comment by JamesCoyle** [comment]
Why do we even have earth-box? 😂

**Comment by MrGrigri** [comment]
I guess it's more of a map than a globe...but yeah, kind of weird.

**Comment by Templarian** [comment]
Better than `earth-flat` 😅 

Added the alias `globe`.

**Comment by 4a-j** [comment]
D'oh! I also tried "world" and "map" but didn't think of "earth". Thanks.
