### ISSUE TITLE
New Icon = RELAY Contacts

### ISSUE THREAD

**Issue by SMOCULETZ** [Templarian/MaterialDesign#2299]
It would be nice to be able to show Relay Contacts Open & Relay Contacts Closed. And with all of its variants : **S**ingle **P**ole **S**ingle **T**hrow (**SPST**), **S**ingle **P**ole **D**ouble **T**hrow (**SPDT**), **D**ouble **P**ole **S**ingle **T**hrow (**DPST**), **D**ouble Pole **D**ouble **T**hrow (**DPDT**) ... etc. The "real world" symbols are : 

![io26](https://user-images.githubusercontent.com/22129404/28764963-f1c919f6-75d0-11e7-8d6d-7e0592105c28.gif)

I have no design skills but I'm sure you can make them look beautiful ! Thanks.

**Comment by Templarian** [comment]
It's a cool idea, but far too specific for this icon pack unfortunately.

Thanks for the suggestion.
