### ISSUE TITLE
Icon: Increase/Decrease font size 

### ISSUE THREAD

**Issue by Vahhab** [Templarian/MaterialDesign#2300]
Icons for books readers to increase/decrease size of text fonts is recommended.

**Comment by JapanYoshi** [comment]
[Please search before asking.](https://materialdesignicons.com/icon/format-size)

**Comment by Vahhab** [comment]
I need one icon for increase text size and another one is for decrease font size. The one you have noticed should be paired with other views/controls to let user select desired text size.
