### ISSUE TITLE
table-column

### ISSUE THREAD

**Issue by smourier** [Templarian/MaterialDesign#2302]
There are existing actions related to a table column, but not a simple table column. I think it could be taken from one of the action, with the small action glyph removed and the 3 blocks centered.

**Comment by Templarian** [comment]
[![table-row](https://materialdesignicons.com/icon/table-row)](https://materialdesignicons.com/icon/table-row) [![table-column](https://materialdesignicons.com/icon/table-column)](https://materialdesignicons.com/icon/table-column)
