### ISSUE TITLE
IEC/IEEE Power Statuses

### ISSUE THREAD

**Issue by robcresswell** [Templarian/MaterialDesign#2304]
There's already a "power" icon, but no equivalent "power-off" with the usual diagonal strike.

**Comment by GreenTurtwig** [comment]
I am I bit hesitant with this one, as the standby/power symbol is a used to toggle state.
Icons to represent "power on" and "power off" would be:
![](https://thumbs.dreamstime.com/t/power-switches-off-position-red-large-detailed-isolated-macro-closeup-61089004.jpg)

**Comment by MrGrigri** [comment]
I'm with @GreenTurtwig on this one. What exactly would this icon be used for? Could it be achieved using another method or icon?

**Comment by k5cents** [comment]
I'm imagining some use-case where a toggle would either turn on or off power to a device. With some icon like `flash` and `flash-off` indicating whether or not power is being delivered.

**Comment by JamesCoyle** [comment]
Do we not have power-on and power-off variants? I feel like we should cover all of the IEC/IEEE power icons https://en.wikipedia.org/wiki/Power_symbol

**Comment by MrGrigri** [comment]
So I would consider this a breaking change. I have redesigned the [power](https://materialdesignicons.com/icon/power) icon, and I believe that it should be renamed as well. I will include a checklist here with the desired name and aliases. This will also satisfy #2255, #1727, and #456

- [ ] `power-standby` [`IEC 60417-5009`, `IEEE 1621`, `power-on`]
- [ ] `power-on` [`IEC 60417-5007`]
- [ ] `power-off` [`IEC 60417-5008`]
- [ ] `power-cycle` [`IEC 60417-5010`, `power-on-off`, `power-restart`]
- [ ] `power-sleep` [`moon`, `night`]

### Power Standby
![power-standby](https://user-images.githubusercontent.com/4528551/28891050-68a669be-7786-11e7-93a0-de0cc38a776b.png)

### Power On
![power-on](https://user-images.githubusercontent.com/4528551/28891052-68aee210-7786-11e7-8b9b-d27f9241ef80.png)

### Power Off
![power-off](https://user-images.githubusercontent.com/4528551/28891100-93a05972-7786-11e7-99d3-d4bcf314a4ee.png)

### Power Cycle
![power-cycle](https://user-images.githubusercontent.com/4528551/28891051-68a94238-7786-11e7-92f2-b55a323c6307.png)

### Power Sleep
![power-sleep](https://user-images.githubusercontent.com/4528551/28891053-68be4d7c-7786-11e7-9441-ad9041ba02b2.png)

**Comment by MrGrigri** [comment]
[data-compress.zip](https://github.com/Templarian/MaterialDesign/files/1195363/data-compress.zip)

**Comment by JamesCoyle** [comment]
Wrong zip file :P

**Comment by Ch-Lo** [comment]
Just want to mention we already have an "power off"-icon: [circle-outline](https://materialdesignicons.com/icon/circle-outline) (which seems to be identical with [checkbox-blank-circle-outline](https://materialdesignicons.com/icon/checkbox-blank-circle-outline) btw).

**Comment by robcresswell** [comment]
My original intention was to use them to indicate servers being powered on or off. A green "power" and then a light grey "power-off" with a diagonal strike though it, similar to how "flash" and "power-plug" work. However, it looks like using "power" and "circle-outline" would be sensible, and fit the standard above.

**Comment by Ch-Lo** [comment]
You could also the power-plug-icons. 
And because we already have outline circles, I dont see, why we should not have a power-off icon with stroke!?

**Comment by MrGrigri** [comment]
[power-symbols.zip](https://github.com/Templarian/MaterialDesign/files/1197712/power-symbols.zip)

**Comment by MrGrigri** [comment]
@Ch-Lo The `power-off` has a diameter of 18 pixels and the `radiobox-blank` has a diameter of 20; so they are not the same. 

![power-off](https://user-images.githubusercontent.com/4528551/28929930-82ca6392-782e-11e7-97fb-18a7085aec07.png)

![radiobox-blank](https://materialdesignicons.com/icon/radiobox-blank)

**Comment by robcresswell** [comment]
The only problem at the moment with using circle-outline and power is that they have different sized circles, so you have to scale them different to make it appear consistent, which isn't pleasant in code. In the proposed icons above, they are more consistent. I'm currently using flash and flash off, but it'd still be nice to use actual power buttons.

**Comment by Templarian** [comment]
[![power-standby](https://materialdesignicons.com/icon/power-standby)](https://materialdesignicons.com/icon/power-standby) [![power-cycle](https://materialdesignicons.com/icon/power-cycle)](https://materialdesignicons.com/icon/power-cycle) [![power-on](https://materialdesignicons.com/icon/power-on)](https://materialdesignicons.com/icon/power-on) [![power-off](https://materialdesignicons.com/icon/power-off)](https://materialdesignicons.com/icon/power-off) [![power-sleep](https://materialdesignicons.com/icon/power-sleep)](https://materialdesignicons.com/icon/power-sleep)
