### ISSUE TITLE
Icon Request: Poker Chip

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2306]

**Comment by MrGrigri** [comment]
I've got four to choose from. I don't believe that all should be added. 

![poker-chip](https://user-images.githubusercontent.com/4528551/28940087-be5701dc-7850-11e7-866b-60beabdbf357.png) ![poker-chip-diamond](https://user-images.githubusercontent.com/4528551/28940086-be544366-7850-11e7-93f8-9e91df5bd866.png) ![poker-chip-outline](https://user-images.githubusercontent.com/4528551/28940088-be5759c0-7850-11e7-8664-07bb29fe953e.png) ![poker-chip-usd](https://user-images.githubusercontent.com/4528551/28940089-be6ad4aa-7850-11e7-9bf6-d16ccc6c8e07.png)

[poker-chip.zip](https://github.com/Templarian/MaterialDesign/files/1198378/poker-chip.zip)

**Comment by k5cents** [comment]
I think the `poker-chip-diamond` version is probably the most easily recognizable as a poker chip. 

Thanks, man, these are great. I can see a few uses for these, so I definitely think one of them should be added.

**Comment by Templarian** [comment]
[![poker-chip](https://materialdesignicons.com/icon/poker-chip)](https://materialdesignicons.com/icon/poker-chip)

**Comment by JamesCoyle** [comment]
How about a filled variant with the diamond as a negative?

**Comment by Templarian** [comment]
Might look better tbh. Reopening the issue.

**Comment by MrGrigri** [comment]
Here is a filled in version. I believe that it's a good idea to have both. 

![poker-chip](https://user-images.githubusercontent.com/4528551/29903773-dffea13c-8dc2-11e7-94fa-e0e125b187d0.png)

[poker-chip.zip](https://github.com/Templarian/MaterialDesign/files/1265609/poker-chip.zip)

**Comment by Templarian** [comment]
Replaced. As this is already a niche icon. I've just replaced the current one to simplify it.
