### ISSUE TITLE
Glassdoor new logo

### ISSUE THREAD

**Issue by infanf** [Templarian/MaterialDesign#2307]
Glassdoor seem to have updated their logo.
![glassdoor-24](https://user-images.githubusercontent.com/8826710/28925043-f82ae618-7863-11e7-9da0-2e260b93d9a6.png)
![glassdoor-48](https://user-images.githubusercontent.com/8826710/28925044-f82f0428-7863-11e7-95cc-d6005324b433.png)
![glassdoor-96](https://user-images.githubusercontent.com/8826710/28924955-b7a441f2-7863-11e7-8602-423454cdaeb7.png)

Updated Icon is attached
[glassdoor.zip](https://github.com/Templarian/MaterialDesign/files/1197385/glassdoor.zip)

**Comment by Templarian** [comment]
[![glassdoor](https://materialdesignicons.com/icon/glassdoor)](https://materialdesignicons.com/icon/glassdoor)
