### ISSUE TITLE
Contribution: Chase Bank

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2308]
It's a little rough on the sizing/cropping, but here's an .svg for the Chase Bank icon. 

Perhaps a little too niche for this collection, but I needed it myself so I figured I'd post it here and see if ya'll wanted to add it.

[chase-bank.zip](https://github.com/Templarian/MaterialDesign/files/1198452/chase-bank.zip)

**Comment by Templarian** [comment]
Yea, we're not going to be accepting bank iconography. There are just too many of them (same goes for credit card logos).

Thanks for the suggestion.
