### ISSUE TITLE
Google Icon toc Missing

### ISSUE THREAD

**Issue by ispecimen-lgiacalone** [Templarian/MaterialDesign#2310]
In Google's Icon Set, there is the icon "toc" (https://material.io/icons/#ic_toc). It seems to be missing from MaterialDesignIcons. It would be great if it could be included.

**Comment by Templarian** [comment]
[![table-of-contents](https://materialdesignicons.com/icon/table-of-contents)](https://materialdesignicons.com/icon/table-of-contents)

Alias of `toc` was also added.
