### ISSUE TITLE
Fireworks icon

### ISSUE THREAD

**Issue by silas229** [Templarian/MaterialDesign#2312]
Please add a fireworks icon

**Comment by augustin32** [comment]
![firework24](https://user-images.githubusercontent.com/14167196/28995022-5044f298-79e6-11e7-9d8b-f7cc0c9b38ff.png)
![firework36](https://user-images.githubusercontent.com/14167196/28995023-51ec274c-79e6-11e7-8de8-b194d8ff6cb8.png)
![firework48](https://user-images.githubusercontent.com/14167196/28995026-5452a66e-79e6-11e7-938c-ec1bd5615a34.png)

[firework.zip](https://github.com/Templarian/MaterialDesign/files/1202316/firework.zip)

**Comment by JapanYoshi** [comment]
Looks like a fire cracker more than anything

**Comment by JamesCoyle** [comment]
Looks like a firework to me...

**Comment by PeterShaggyNoble** [comment]
`vanish` might be suitable for some purposes.

[![](https://materialdesignicons.com/icon/vanish)](https://materialdesignicons.com/icon/vanish)

**Comment by Templarian** [comment]
Added. 😃
