### ISSUE TITLE
Dishwashing machine icon

### ISSUE THREAD

**Issue by vibrog** [Templarian/MaterialDesign#2313]
A symbol for a dishwasher machine.
For use in home automation systems that support MD Icons like Home Assistant.
Attached is a suggestion.

![dishwasher-24](https://user-images.githubusercontent.com/67639/29001173-ce693238-7a81-11e7-85f4-7de8eba4a8ef.png)
![dishwasher-96](https://user-images.githubusercontent.com/67639/29001174-ce696bea-7a81-11e7-943f-4c57d18fcc66.png)
[dishwasher.svg.zip](https://github.com/Templarian/MaterialDesign/files/1202920/dishwasher.svg.zip)

**Comment by JamesCoyle** [comment]
Icons need to adhere to these guidelines: https://material.io/guidelines/style/icons.html#icons-system-icons

**Comment by k5cents** [comment]
What about taking the `washing-machine` icon and replacing the tumbling clothes with some dish iconography?

Some mock-ups:

![dishwasher3](https://user-images.githubusercontent.com/18021678/29008285-6ddd5cbc-7ae2-11e7-89db-64d3c63b0e5e.png)
![dishwasher2](https://user-images.githubusercontent.com/18021678/29008287-6dde6a6c-7ae2-11e7-9e85-1e945aae113f.png)
![dishwasher](https://user-images.githubusercontent.com/18021678/29008286-6dddcd00-7ae2-11e7-9f80-8d5e90c35bbe.png)

**Comment by Brausmith** [comment]
I like @k5cents idea for some consistency. Maybe even a version with some wavy lines (i.e. wind/air) for a clothes dryer too.
I too need a washing machine icon for Home Assistant.

**Comment by PeterShaggyNoble** [comment]
@Brausmith, see #1625 for clothes dryer.

**Comment by GreenTurtwig** [comment]
Google now has an icon for a dishwasher:
![image](https://user-images.githubusercontent.com/15905797/44350021-4eddab80-a496-11e8-84cb-86e7883bc722.png)

**Comment by PeterShaggyNoble** [comment]
[![dishwasher](https://user-images.githubusercontent.com/15157491/44391479-e5a67880-a527-11e8-8693-dab4e09ef559.png)](https://materialdesignicons.com/icon/dishwasher)
