### ISSUE TITLE
Chart Scatter

### ISSUE THREAD

**Issue by farkasnorbert90** [Templarian/MaterialDesign#2316]
I'd like to request a new chart icon only with dots.

![linedotplot](https://user-images.githubusercontent.com/16883722/29031769-8ea470d6-7b8f-11e7-8311-f85581919a67.png)

**Comment by JamesCoyle** [comment]
We could do with a `chart-scatter` icon for sure. You should be aware however that the graph you provided as an example should be a bar graph.

**Comment by JamesCoyle** [comment]
Closed #498 in favor of this as the link in that issue no longer works.

**Comment by CoDEmanX** [comment]
There is a contribution following the existing chart icons over here:
https://github.com/Templarian/MaterialDesign/issues/1209#issuecomment-217773216

**Comment by PeterShaggyNoble** [comment]
See also Google's `scatter_plot` icon, requested in #3640.

[![scatter_plot](http://mdi.houseofdesign.ie/tools/preview/?icon=scatter-plot&action=launch)](https://material.io/tools/icons/?search=scatter_plot&icon=scatter_plot&style=baseline)

**Comment by goyney** [comment]
Google's stock icons:
![image](https://user-images.githubusercontent.com/1015040/49034952-61483f00-f181-11e8-8577-4e84feb5c27a.png)![image](https://user-images.githubusercontent.com/1015040/49034962-67d6b680-f181-11e8-8a11-24e17f9247ae.png)

A new `chart` variation I created based on the stock icon:

![image](https://user-images.githubusercontent.com/1015040/49034994-7fae3a80-f181-11e8-93b9-50bf709b8678.png)

[scatter.zip](https://github.com/Templarian/MaterialDesign/files/2616904/scatter.zip)

**Comment by Templarian** [comment]
Added. 😃
