### ISSUE TITLE
Update & Rename: youtube-play

### ISSUE THREAD

**Issue by suraj021** [Templarian/MaterialDesign#2317]
Material icons for various social networking sites logo.

**Comment by JamesCoyle** [comment]
We have plenty of social icons already. If you have anything specific in mind please open a more specific request and provide examples.

**Comment by suraj021** [comment]
I was searching specifically for a YouTube icon, but what we have here is a youtube play button only and no logo.

**Comment by k5cents** [comment]
I've definitely noticed how `youtube-play` is not the same shape as the regular YouTube icon. It's a little less wide and more thick, which works better for a MD icon, but not as a brand icon.

**Comment by PeterShaggyNoble** [comment]
This is the official icon overlaid with ours in red:

![youtube-play](https://user-images.githubusercontent.com/15157491/37152378-0c4c0344-22d1-11e8-98ef-44bc9648b9d9.png)

**Comment by Templarian** [comment]
@PeterShaggyNoble Where did you get that official one? That attach it.

**Comment by PeterShaggyNoble** [comment]
@Templarian, it's `video youtube` from [the extended set](https://petershaggynoble.github.io/MDI-Sandbox/extended/). Can't do a zip file on my phone but I included one in #2591.

**Comment by PeterShaggyNoble** [comment]
We could probably rename this as `youtube` at the same time, with `youtube-play` as an alias.

**Comment by Templarian** [comment]
Updated/Renamed/Aliased.
