### ISSUE TITLE
backspace-outline new icon

### ISSUE THREAD

**Issue by cheriejw** [Templarian/MaterialDesign#2318]
Just another option, since the backspace is already available.

Attached icon.
[Back.pdf](https://github.com/Templarian/MaterialDesign/files/1209256/Back.pdf)

Thank you.

**Comment by Templarian** [comment]
Adding the high priority. Will add a filled / outline version. Need these at work myself.

**Comment by PeterShaggyNoble** [comment]
`backspace-outline` was added in #3242. Closing here.
