### ISSUE TITLE
File delete (minus) icon needed 

### ISSUE THREAD

**Issue by BlackWitcher** [Templarian/MaterialDesign#2319]
Hello!
When I try to find icons by "file" tag, I see many useful icons but there is no icons that means "delete" or "remove" file.
For example, I need icon like this but with minus sign:
![file-plus 2](https://user-images.githubusercontent.com/3014189/29107960-69dff192-7ce5-11e7-8b76-93d142069f76.png)

Or with file icon instead folder (finally it will be icon with file icon and "x" sign):
![folder-remove 1](https://user-images.githubusercontent.com/3014189/29107984-8dca877a-7ce5-11e7-8d02-e21d02b54638.png)

I hope this icons will be usefull not for me only.

Thanks in advance!

**Comment by JamesCoyle** [comment]
#1240
