### ISSUE TITLE
train/flight class icon

### ISSUE THREAD

**Issue by rohanaggarwal** [Templarian/MaterialDesign#232]
Person sitting on a chair

- [ ] seat (stock google in v2)
- [ ] seat-reserved

**Comment by Templarian** [comment]
I started a google doc if you want to help it is attached to issue #420.

I'm going to close all the stock google issues and add them to the list.

**Comment by CoDEmanX** [comment]
Which icon exactly does this issue refer to? This one?
https://design.google.com/icons/#ic_airline_seat_recline_normal

I can't remember a stock google icon for seat-reserved... We should re-open this as icon request if there is not.
