### ISSUE TITLE
Icon for Price 

### ISSUE THREAD

**Issue by chinmoydash** [Templarian/MaterialDesign#2320]

**Comment by augustin32** [comment]
Don't spam the issues section.

**Comment by augustin32** [comment]
![price24](https://user-images.githubusercontent.com/14167196/29117363-912e239c-7d06-11e7-92da-2655fcb2888e.png)
![price36](https://user-images.githubusercontent.com/14167196/29117365-934a5768-7d06-11e7-8d28-c4bee5617f47.png)
![price48](https://user-images.githubusercontent.com/14167196/29117369-953d809a-7d06-11e7-8a32-4ae52d302f54.png)

[price.zip](https://github.com/Templarian/MaterialDesign/files/1211129/price.zip)

**Comment by JamesCoyle** [comment]
I personally would suggest just using a larger type to display the actual price to increase the perceived importance. The use of a currency symbol is enough to denote that it is the price of the item and I feel adding an icon would just add clutter to the UI. 

Of course that depends on what you're actually doing with it so I may be missing a possible use-case for such an icon.

**Comment by PeterShaggyNoble** [comment]
If you're dealing with a single currency then the icon for that currency might work for you - see all currency icons [here](http://mdi.houseofdesign.ie/?search=currency).

If not then the `tag` icon (or one of its variants) could do the job.

[![](https://materialdesignicons.com/icon/tag)](https://materialdesignicons.com/icon/tag)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of response. @chinmoydash, if the icons suggested above don't suit your needs, let us know and we'll revisit this issue.
