### ISSUE TITLE
KML & KMZ Icon Request

### ISSUE THREAD

**Issue by donhurickerby** [Templarian/MaterialDesign#2323]
Requesting a KML and KMZ icon. I've seen the KML one on the google earth web app. Could be as simple as they have it:  
![screen shot 2017-08-09 at 1 24 54 pm](https://user-images.githubusercontent.com/4519182/29142244-2ec03c7c-7d06-11e7-98ff-3c62377282ed.png)

One for KML and another for KMZ please.

Thanks!

**Comment by Templarian** [comment]
Going to mark this as too niche/specific. Probably best to use a more generalized `download` or file icon.
