### ISSUE TITLE
Icons for hotel check in and check out

### ISSUE THREAD

**Issue by edwoollard** [Templarian/MaterialDesign#2324]
Would be great to see icons for a user to check in to a hotel as well as check out.

**Comment by TheChilliPL** [comment]
How could it look?

**Comment by JapanYoshi** [comment]
![hotel-checkin](https://user-images.githubusercontent.com/8707990/30249152-dc1d9122-9678-11e7-8182-9b043c5786fb.png)

I tried doing stuff with Google's "hotel" icon, but ended up making a "go to sleep" icon.

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @edwoollard, if you can provide examples, we'll revisit this issue.

**Comment by CoDEmanX** [comment]
From a Google search:

![image](https://user-images.githubusercontent.com/1309249/37435093-3d7838be-27e2-11e8-9a47-4fb3dc0d653c.png)

That's a lot to fit into 24px however.

**Comment by PeterShaggyNoble** [comment]
Would a desk bell work? On a related note, have we figured out yet if Google's `room-service` icon is supposed to be a desk bell or a covered tray?!

**Comment by CoDEmanX** [comment]
Huh, always interpreted it as a desk bell. But covered tray makes a lot of sense actually.

**Comment by PeterShaggyNoble** [comment]
Me too, @CoDEmanX; it was only when I went to alias it as `desk-bell` that I realised that maybe it was supposed to be a tray. We just need to decide whether we want it to serve as both or add a separate icon for a bell.

**Comment by CoDEmanX** [comment]
How would you make it distinct anyway?

**Comment by HassanMehmood1992** [comment]
Hi we can make something along this line for checking in and out. 
![image](https://user-images.githubusercontent.com/17563392/62204529-6445a000-b39e-11e9-804c-f0a26d2493dc.png)
![image](https://user-images.githubusercontent.com/17563392/62200256-1331ae00-b396-11e9-99f5-39572a4c2706.png)

**Comment by CoDEmanX** [comment]
The existing `clock-in` and `clock-out` icons should work quite well:

![grafik](https://user-images.githubusercontent.com/1309249/62247352-ec02cd00-b3e5-11e9-9769-46103b753cd5.png) ![grafik](https://user-images.githubusercontent.com/1309249/62247366-f3c27180-b3e5-11e9-9517-195632d39e37.png)

There are also `login` and `logout` with kind of a door.

What could be useful would be generic in and out icons, like:

![grafik](https://user-images.githubusercontent.com/1309249/62247872-11440b00-b3e7-11e9-85b3-83459b16409b.png) ![grafik](https://user-images.githubusercontent.com/1309249/62247849-025d5880-b3e7-11e9-84e6-3effe566e30d.png)

Doesn't work that great though IMO.
