### ISSUE TITLE
Floorplan / blueprint icon

### ISSUE THREAD

**Issue by james-fry** [Templarian/MaterialDesign#2325]
As a home assistant home automation user I found the need for a floorplan icon, but there is nothing suitable in MDI.
Here's one I rolled. It would be nice if it can be added to MDI.

[floorplan.zip](https://github.com/Templarian/MaterialDesign/files/1213052/floorplan.zip)

**Comment by james-fry** [comment]
![image](https://user-images.githubusercontent.com/5823294/29146782-0355a02c-7d5b-11e7-9cbd-9ebef78a4f69.png)

**Comment by james-fry** [comment]
Thanks for the tagging. Please can you also tag with home assistant.

**Comment by Templarian** [comment]
[![floor-plan](https://materialdesignicons.com/icon/floor-plan)](https://materialdesignicons.com/icon/floor-plan)

Made a small exception for the 2px line width for this since it looks more "correct" in this instance.

**Comment by james-fry** [comment]
Thanks for including.
