### ISSUE TITLE
Icon Request - Shipping/Order Status Icons

### ISSUE THREAD

**Issue by kcrossman** [Templarian/MaterialDesign#2326]
See http://www.webalys.com/nova/
I can't find any icons that look like cardboard boxes for shipping/order purposes. If these were added to the pack I would be grateful.

**Comment by kcrossman** [comment]
Thanks, these look good.

**Comment by kcrossman** [comment]
if you can make them slightly different than the nova pack that would be nice, but thanks.

**Comment by Templarian** [comment]
We're trying our best not to include cut outs of every icon. We can add a general box/trolly/etc, but most of these won't be included unfortunately.

- [ ] trolly
- [ ] trolly-full
- forklift exists already in a more "material design"
- truck exists [...]
- [ ] truck-time (needs to match current truck)
- [ ] conveyor-belt
- [ ] garage-full
- [ ] box-delivery (name needs to be something else)
- [ ] package-arrow-up
- [ ] package-arrow-down
- [ ] 3D Move

We're a _lot_ stricter with the guidelines than Nova, so this limits us a little.

**Comment by JamesCoyle** [comment]
I do like the boxes in the first icon. Don't use perspective but are still recognizable.

**Comment by MrGrigri** [comment]
I like the idea of using the `package` icon for some of these. It doesn't add too much perspective, but just enough.

![package](https://materialdesignicons.com/icon/package)

**Comment by kcrossman** [comment]
@Templarian Adding an open cardboard box or cardboard box with a + and a closed cardboard box would be sufficient, if possible.

**Comment by kcrossman** [comment]
Here is another pack that has boxes:
https://www.shutterstock.com/image-vector/set-black-flat-icons-about-shopping-210911638?irgwc=1&utm_medium=Affiliate&utm_campaign=Graphic%20resources%20SL&utm_source=39422&utm_term=
![image](https://user-images.githubusercontent.com/9127996/29193558-1bba7d58-7de3-11e7-8284-0929e9734fad.png)

**Comment by PeterShaggyNoble** [comment]
@kcrossman those 2 boxes exists as `package-variant` & `package-variant-closed`

[![](https://materialdesignicons.com/icon/package-variant)](https://materialdesignicons.com/icon/package-variant) [![](https://materialdesignicons.com/icon/package-variant-closed)](https://materialdesignicons.com/icon/package-variant-closed)

**Comment by kcrossman** [comment]
This issue can be closed. I don't suspect any more additions are going to be added. Thanks for the contributions.
