### ISSUE TITLE
Robot vacuum

### ISSUE THREAD

**Issue by dannyhanes** [Templarian/MaterialDesign#2327]
https://home-assistant.io/components/neato/

**Comment by Templarian** [comment]
Renaming it to be more generic. Probably will end up looking like a roomba, but both a pretty much the same thing.

**Comment by james-fry** [comment]
There is already roomba icon. Would there be a need for generic and manufacturer specific?

**Comment by dannyhanes** [comment]
Honestly, the roomba icon doesn't make me think "vacuum". I am perfectly ok with a generic looking vacuum icon. Something my kids could look at and say, "Yup, thats a vacuum." lol I just requested Neato since that's what I have.

**Comment by james-fry** [comment]
Agree, My comment was more that a generic icon should probably be instead of a plethora of manufacturer specific icons.
Reason being that (as you say) the icons are not immediately identifiable as the devices.

**Comment by GreenTurtwig** [comment]
Hoover has been requested over here: https://github.com/Templarian/MaterialDesign/issues/2217
I'll rename this to "Neato vacuum" to keep things separate. :-)

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/29834046-8794c6ee-8ce5-11e7-84ef-0338b81fd003.png)
![image](https://user-images.githubusercontent.com/15905797/29834055-92ec4b8e-8ce5-11e7-810f-9a96bcc310bd.png)
[neato.zip](https://github.com/Templarian/MaterialDesign/files/1261082/neato.zip)

I don't like the amount of empty space, but it's recognisable as a Neato. It could definitley do with some revising.

**Comment by dannyhanes** [comment]
Nice! I think if you got rid of the lower left square, and then moved the bottom circle up a little, it would look a little better. Make it more symmetrical.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/29834517-f79975d8-8ce6-11e7-9dd3-1ee1fc041c49.png)
![image](https://user-images.githubusercontent.com/15905797/29834543-0d024008-8ce7-11e7-8948-236a55498124.png)
[neato2.zip](https://github.com/Templarian/MaterialDesign/files/1261106/neato2.zip)
No idea why I initially gave the circle a 1px gap, but 2px definitely looks better.

![image](https://user-images.githubusercontent.com/15905797/29834633-614ee454-8ce7-11e7-96ca-f232c1f5c39f.png)
![image](https://user-images.githubusercontent.com/15905797/29834657-71edaaf2-8ce7-11e7-8a5a-ab9c64e52b64.png)
[neato3.zip](https://github.com/Templarian/MaterialDesign/files/1261128/neato3.zip)
I kept the square LCD as I like the extra detail.

**Comment by dannyhanes** [comment]
I am definitely partial to neato2. The square for me throws off the symmetry lol Looks good though!

**Comment by GreenTurtwig** [comment]
Yeah, would be great to get feedback from other people.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign/issues/2368#issuecomment-326180469

I think it's going to be too niche to include all these icons. Having 1 generic might be best.

**Comment by JapanYoshi** [comment]
``robot-vacuum`` and ``robot-vacuum-variant``?

**Comment by Templarian** [comment]
@JapanYoshi Yea, that definitely could work due to the different shape (round vs flat front).

**Comment by JapanYoshi** [comment]
Definitely. We also have the option of giving them the aliases ``roomba`` and ``neato`` if feasible.

**Comment by Templarian** [comment]
Renamed https://materialdesignicons.com/icon/robot-vacuum and added...

[![robot-vacuum-variant](https://materialdesignicons.com/icon/robot-vacuum-variant)](https://materialdesignicons.com/icon/robot-vacuum-variant)
