### ISSUE TITLE
Reconcile

### ISSUE THREAD

**Issue by MasterRam** [Templarian/MaterialDesign#2329]
Reconcile Icon

[![Reconcile](http://icons.iconarchive.com/icons/icons8/windows-8/256/Editing-Compare-icon.png)](http://icons.iconarchive.com/icons/icons8/windows-8/256/Editing-Compare-icon.png)

#1538

**Comment by MrGrigri** [comment]
Would `compare` not work?

![compare](https://materialdesignicons.com/icon/compare)

**Comment by PeterShaggyNoble** [comment]
[`file-compare`](https://materialdesignicons.com/icon/file-compare) has also been added and will be available in the next release.

@MasterRam, if neither of those icons suit your needs, let us know and we'll revisit this issue.
