### ISSUE TITLE
destroy/build icon

### ISSUE THREAD

**Issue by davisf** [Templarian/MaterialDesign#233]
Context: gamification apps for actions like "destoroy/build this object"
- [x] build
- [ ] destroy

**Comment by CoDEmanX** [comment]
Google's wrench icon should work for build, not sure about destroy...
Probably one of these: https://github.com/Templarian/MaterialDesign/issues/365

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @davisf, if `wrench` and `bomb` don't suit your needs,  please open new issues for each icons and include examples of what you're looking for.
