### ISSUE TITLE
Wired and Wireless Earbuds

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#2330]
Something like these perhaps:

- [Wired](http://icons.iconarchive.com/icons/iconsmind/outline/512/Earphones-icon.png)
- [Wireless](https://cdn0.iconfinder.com/data/icons/household-items-2/100/airpod2-512.png)

**Comment by GreenTurtwig** [comment]
Example:
![](https://img.gadgethacks.com/img/80/69/63602973698461/0/pick-your-own-status-bar-icons-for-wired-bluetooth-headphones.w1456.jpg)

**Comment by Xenomorph99** [comment]
I took the example @GreenTurtwig found, cleaned it up, and built upon it. How do you guys feel about these designs?

I tried stretching the top part of the earbud "stem" wider to align to the pixel grid, but unfortunately it felt too fat. Making it more narrow didn't work either. The "wire" is 2 dps wide on the left and I was forced to keep the same width on the right. I think these are reasonable exceptions to the pixel grid rule.

![earbuds](https://user-images.githubusercontent.com/1837101/98273642-b7b67e80-1f4f-11eb-97ca-c13e8b42010a.png)
![earbuds-wireless](https://user-images.githubusercontent.com/1837101/98273638-b7b67e80-1f4f-11eb-9bc3-8c7bf886b496.png)
![earbuds-variant](https://user-images.githubusercontent.com/1837101/98273630-b6855180-1f4f-11eb-8157-3809d5bb4a62.png)
![earbuds-wireless-variant](https://user-images.githubusercontent.com/1837101/98273636-b71de800-1f4f-11eb-8085-fe2841586bbb.png)

## `-off` modifier

I chose to reflect the line in `earbuds-off` and `earbuds-wireless-off` to avoid the tiny artifacts you can see in the example.

![earbuds-wireless-off-example](https://user-images.githubusercontent.com/1837101/98274881-37911880-1f51-11eb-88b0-4fc24527946d.png)

![earbuds-off](https://user-images.githubusercontent.com/1837101/98273623-b5ecbb00-1f4f-11eb-9965-a68eac63ff8c.png)
![earbuds-wireless-off](https://user-images.githubusercontent.com/1837101/98273632-b71de800-1f4f-11eb-8657-b4bc5f3b1565.png)
![earbuds-variant-off](https://user-images.githubusercontent.com/1837101/98273626-b6855180-1f4f-11eb-916d-5559195ad864.png)
![earbuds-wireless-variant-off](https://user-images.githubusercontent.com/1837101/98273634-b71de800-1f4f-11eb-89a1-3477a1c2a780.png)

## `-outline` modifier

![earbuds-outline](https://user-images.githubusercontent.com/1837101/98273669-bd13c900-1f4f-11eb-979c-ef60317de3bb.png)
![earbuds-wireless-outline](https://user-images.githubusercontent.com/1837101/98273676-be44f600-1f4f-11eb-801a-82b8f51fc01d.png)
![earbuds-variant-outline](https://user-images.githubusercontent.com/1837101/98273673-bdac5f80-1f4f-11eb-8cfa-4301645776a3.png)
![earbuds-wireless-variant-outline](https://user-images.githubusercontent.com/1837101/98273680-bedd8c80-1f4f-11eb-9b41-b48ae44b8d83.png)

## `-off-outline` modifier

![earbuds-off-outline](https://user-images.githubusercontent.com/1837101/98273667-bc7b3280-1f4f-11eb-806c-38f2887e7a9c.png)
![earbuds-wireless-off-outline](https://user-images.githubusercontent.com/1837101/98273675-bdac5f80-1f4f-11eb-8f55-2e1acdfb2b97.png)
![earbuds-variant-off-outline](https://user-images.githubusercontent.com/1837101/98273671-bd13c900-1f4f-11eb-867c-cdbb7eada326.png)
![earbuds-wireless-variant-off-outline](https://user-images.githubusercontent.com/1837101/98273678-be44f600-1f4f-11eb-9dcd-36f097606dbc.png)

## Zip download

[earbuds.zip](https://github.com/Templarian/MaterialDesign/files/5495895/earbuds.zip)

**Comment by goyney** [comment]
[![earbuds](https://materialdesignicons.com/icon/earbuds)](https://materialdesignicons.com/icon/earbuds)[![earbuds-off](https://materialdesignicons.com/icon/earbuds-off)](https://materialdesignicons.com/icon/earbuds-off)
[![earbuds-outline](https://materialdesignicons.com/icon/earbuds-outline)](https://materialdesignicons.com/icon/earbuds-outline)[![earbuds-off-outline](https://materialdesignicons.com/icon/earbuds-off-outline)](https://materialdesignicons.com/icon/earbuds-off-outline)
