### ISSUE TITLE
upload-multiple

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2331]
Need to create an icon that represents uploading multiple files at once.

**Comment by buutqn** [comment]
[upload-multiple-files-1.zip](https://github.com/Templarian/MaterialDesign/files/1244093/upload-multiple-files-1.zip)
![upload-multiple-files-1](https://user-images.githubusercontent.com/15644387/29598308-73132996-879e-11e7-894d-02befc772f00.png)



[upload-multiple-files-2.zip](https://github.com/Templarian/MaterialDesign/files/1244094/upload-multiple-files-2.zip)
![upload-multiple-files-2](https://user-images.githubusercontent.com/15644387/29598310-7863103c-879e-11e7-9cff-f5758a536ddd.png)

**Comment by MrGrigri** [comment]
Why not keep it consistent to Google's own upload icon

![upload-multiple](https://user-images.githubusercontent.com/4528551/29623002-2ebc49b4-87e2-11e7-8550-c8d3775c7f4a.png)

[upload-multiple.zip](https://github.com/Templarian/MaterialDesign/files/1245898/upload-multiple.zip)

**Comment by Templarian** [comment]
Nice designs @buutqn, bug going to go with the more Material Design / minimalist design.

[![upload-multiple](https://materialdesignicons.com/icon/upload-multiple)](https://materialdesignicons.com/icon/upload-multiple)

Will be using this one at work once it's released. 😄
