### ISSUE TITLE
Icon request: Zoroastrian symbols

### ISSUE THREAD

**Issue by KamronAsh** [Templarian/MaterialDesign#2336]
I need the **Zoroastrian** symbols, please add to MDI

**Farvahar:** https://commons.wikimedia.org/wiki/Category:Faravahar
**Atar:** https://commons.wikimedia.org/wiki/Category:Fire_(Zoroastrianism)

**Comment by Templarian** [comment]
Closing as too specific of a request, especially at 24x24 size.
