### ISSUE TITLE
Dashcoin

### ISSUE THREAD

**Issue by Isaachi1** [Templarian/MaterialDesign#2337]
I would like you to add the Dashcoin virtual currency icon.
[https://www.dash.org](https://www.dash.org)

**Comment by augustin32** [comment]
![dash24](https://user-images.githubusercontent.com/14167196/29498317-ec29dca6-8601-11e7-8dd9-e295b34bdeb5.png)
![dash36](https://user-images.githubusercontent.com/14167196/29498318-ed1e6d02-8601-11e7-8851-125b6fc11de7.png)
![dash48](https://user-images.githubusercontent.com/14167196/29498319-ee86ee44-8601-11e7-86c2-417907fe9c98.png)
[dash.zip](https://github.com/Templarian/MaterialDesign/files/1237346/dash.zip)

**Comment by Isaachi1** [comment]
Thank You!

**Comment by JapanYoshi** [comment]
I know you already did it and all, but @augustin32, is this *really* within the scope of MDI? I've literally never heard of Dashcoin, and I've even heard of Ethereum.

**Comment by Templarian** [comment]
Will keep the issue opened, but it may be too niche at the moment to include.

**Comment by PeterShaggyNoble** [comment]
8 months later and Dashcoin still hasn't come close to our criterion for adding cryptocurrencies of 100k transactions per day so going to close this out. We will revisit it when putting together a dedicated icon pack for brands.
