### ISSUE TITLE
burglar / thief / criminal 

### ISSUE THREAD

**Issue by damianobarbati** [Templarian/MaterialDesign#2338]
Ideas:
. hat like => 
![hat](https://user-images.githubusercontent.com/2225869/29498225-b55f8aea-85f7-11e7-8ef0-8e7a9eed8393.png)
. eyes covered like => 
![19180-200](https://user-images.githubusercontent.com/2225869/29498232-cb2dfeb0-85f7-11e7-8848-47a2b58dda62.png)

A popular symbol would be the lupin / jigen shape.

**Comment by MrGrigri** [comment]
I've taken the `ninja` icon I did and inverted it. What are y'all's thoughts?

![thief](https://user-images.githubusercontent.com/4528551/29783097-54b940e2-8bdc-11e7-83b3-af71ea797ca1.png)

[thief.zip](https://github.com/Templarian/MaterialDesign/files/1257504/thief.zip)

**Comment by Templarian** [comment]
More of a raccoon shaped eye covering might be ideal. 🤔

**Comment by damianobarbati** [comment]
@MrGrigri my 2 cents: I think the typical thief hat it's all that's missing.
<img width="179" alt="screen shot 2017-08-30 at 10 52 31" src="https://user-images.githubusercontent.com/2225869/29863929-75b8d5dc-8d71-11e7-95cd-613c3db3794c.png">

**Comment by JamesCoyle** [comment]
I agree though would be nice to keep it in line with the emoji icons.

**Comment by Alekhen** [comment]
Here's a couple ideas. I used [emoticon-neutral](https://materialdesignicons.com/icon/emoticon-neutral) as the base and the inverted eyes from [skull](https://materialdesignicons.com/icon/skull) to help the design to still hold up when it's small. I like the one with the crooked mouth best.

Straight mouth:
![thief-1-24](https://user-images.githubusercontent.com/1837101/30845007-b39aa488-a24e-11e7-9582-ada42a724e8a.png)
![thief-1](https://user-images.githubusercontent.com/1837101/30845013-b857b416-a24e-11e7-94a5-a1fa384c4422.png)

Crooked mouth:
![thief-2-24](https://user-images.githubusercontent.com/1837101/30845019-c13e1f20-a24e-11e7-914f-c39a112887ec.png)
![thief-2](https://user-images.githubusercontent.com/1837101/30845022-c492cc3e-a24e-11e7-860a-7d9b620396a3.png)

[thief.svg.zip](https://github.com/Templarian/MaterialDesign/files/1331971/thief.svg.zip)

**Comment by damianobarbati** [comment]
@Alekhen it looks more like a ninja to me, but it's a personal opinion :)

**Comment by goyney** [comment]
We added `robber` in #3409.

[![robber](https://materialdesignicons.com/icon/robber)](https://materialdesignicons.com/icon/robber)
