### ISSUE TITLE
Icon Request: Add image

### ISSUE THREAD

**Issue by bckp1993** [Templarian/MaterialDesign#2339]
Similar to note-plus or library-plus but its purpose is to add new image.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/29745147-8db891ae-8aab-11e7-9ec3-963cf89de413.png)
![image](https://user-images.githubusercontent.com/15905797/29745151-9ee05610-8aab-11e7-83ce-2287e8a882e6.png)
[image-plus.zip](https://github.com/Templarian/MaterialDesign/files/1253974/image-plus.zip)

**Comment by PeterShaggyNoble** [comment]
See also `add photo alternate` in the [extended icon set](https://petershaggynoble.github.io/MDI-Sandbox/extended/).

[![add-photo-alternate](https://user-images.githubusercontent.com/15157491/33935172-e5836d72-dff2-11e7-9de4-fd8776d26d5b.png)](https://github.com/Templarian/MaterialDesign/files/1495842/add-photo-alternate.zip)

**Comment by Templarian** [comment]
[![image-plus](https://materialdesignicons.com/icon/image-plus)](https://materialdesignicons.com/icon/image-plus)
