### ISSUE TITLE
Mansion / Boss

### ISSUE THREAD

**Issue by 12nick12** [Templarian/MaterialDesign#2341]
Icon for Mansion or boss

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/29745084-81470adc-8aaa-11e7-9166-5077ecd6f113.png)
![image](https://user-images.githubusercontent.com/15905797/29745088-93dbdc86-8aaa-11e7-9685-b241438faaad.png)
[business-person.zip](https://github.com/Templarian/MaterialDesign/files/1253970/business-person.zip)

Made real quick, I do feel the tie is a bit too small.

**Comment by MrGrigri** [comment]
Imo, this is lost at 1x.

**Comment by Tarilonte** [comment]
My contribution to boss/businessman
![image](https://user-images.githubusercontent.com/29761068/38948164-1bf2ae1a-4315-11e8-84d2-ba26a230b74f.png)
[businessman.zip](https://github.com/Templarian/MaterialDesign/files/1925114/businessman.zip)

**Comment by goyney** [comment]
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/354.
