### ISSUE TITLE
soccer-field

### ISSUE THREAD

**Issue by buutqn** [Templarian/MaterialDesign#2342]
![soccer-field](https://user-images.githubusercontent.com/15644387/29597282-07e938a0-8798-11e7-88ba-263f23afe43a.png)
[soccer-field.zip](https://github.com/Templarian/MaterialDesign/files/1244027/soccer-field.zip)

I just created this in Vectr.com because i need it in my project...

Dunno how to add labels...

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/29744902-1dd268e2-8aa6-11e7-867e-57cf515b5fc9.png)
![image](https://user-images.githubusercontent.com/15905797/29744903-25eafb52-8aa6-11e7-9704-64e25b71feee.png)
[football-pitch.zip](https://github.com/Templarian/MaterialDesign/files/1253953/football-pitch.zip)

**Comment by buutqn** [comment]
This one is perfect. Will it be added to the icons at https://materialdesignicons.com/?

**Comment by Templarian** [comment]
Alias added for `football-pitch`. We may want to add this to some of the others to make it easier to find. Added `football` to `soccer` also.

[![soccer-field](https://materialdesignicons.com/icon/soccer-field)](https://materialdesignicons.com/icon/soccer-field)
