### ISSUE TITLE
Code Tag - Alternate

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2344]
Need something that we more then just a no comparison symbol.

![code-tag-alt](https://user-images.githubusercontent.com/20706106/29631679-6ad125ba-880e-11e7-948d-cdd93e104aa3.png)
[code-tag-alt.zip](https://github.com/Templarian/MaterialDesign/files/1246546/code-tag-alt.zip)

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/xml)](https://materialdesignicons.com/icon/xml)
The `xml` icon is very similar in appearance, does it suffice?
