### ISSUE TITLE
Code Icon Pack

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2345]
Icons for: JAVA, SQL, and Eclipse Packages

I attempted, but i think they might need a little help

![code-package](https://user-images.githubusercontent.com/20706106/29633921-e574d9f4-8815-11e7-92fd-549110dc9f88.png)
![code-tag-java](https://user-images.githubusercontent.com/20706106/29633922-e575a2b2-8815-11e7-98ab-96a888e345d2.png)
![code-tag-sql](https://user-images.githubusercontent.com/20706106/29633923-e5760b6c-8815-11e7-9c9d-87af4730b0e5.png)
[Code Package.zip](https://github.com/Templarian/MaterialDesign/files/1246711/Code.Package.zip)

**Comment by PeterShaggyNoble** [comment]
Duplicate of #271
