### ISSUE TITLE
SourceMap is misaligned: font-family != '#{$mdi-font-name}'

### ISSUE THREAD

**Issue by max-ott** [Templarian/MaterialDesign#2347]
Importing Material Design CSS results in misaligned SourceMap.

I'm importing the latest Material Design Icon sheet into a project via
@import url("https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css");

In Chrome Version 60.0.3112.101 (Official Build) (64-bit) I'm getting the following error display in the console:

LiveSASS failed to start: https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css.map
SourceMap is misaligned: font-family != '#{$mdi-font-name}'
compiled: https://cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css:1:41
source: https://cdn.materialdesignicons.com/2.0.46/scss/_path.scss:2:16

**Comment by Templarian** [comment]
This was fixed many versions ago, completely forgot to close the issue.
