### ISSUE TITLE
Single File API

### ISSUE THREAD

**Issue by splitbrain** [Templarian/MaterialDesign#2348]
It would be great to have an API to request a single icon by name. Poking a bit at  the website this seems to be easy to implement:

The Advanced download mechanism already provides a way to create a PNG icon from URL parameters. Eg. https://materialdesignicons.com/api/download/4F013652-22DE-48CF-886B-A0FB995E8B41/FFFFFF/1/FFFFFF/0/48

And there's also a way to request info about a single icon: https://materialdesignicons.com/api/icon/4F013652-22DE-48CF-886B-A0FB995E8B41 where the data field seems to contain the raw SVG path.

Now all is that is missing is mapping an icon name like `access-point` to it's ID `4F013652-22DE-48CF-886B-A0FB995E8B41`

All the needed info is available in https://materialdesignicons.com/api/package/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B (with the package ID being available at https://materialdesignicons.com/api/init).

So what I'm saying is all the parts are already there, but to download a single SVG or PNG programmatically one currently has to go through downloading the whole package data first. It would be great if the icon and download API would provide a way to access the data via the icon name.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site/issues/6

Closing to keep discussions about the new site in that repo. Keeping this repo for just legacy site and icons.
