### ISSUE TITLE
airplane-outline

### ISSUE THREAD

**Issue by lolsheeplol** [Templarian/MaterialDesign#2349]
I'm moving the icons in my company's app to google-material icons, but I am missing one icon that previously came from SimpleLineIcons which is the airplane-outline icon.  

We use outline icons for the bottom bar in our app, they are all outline icons.  We have a tab for flights, and the solid airplane is just out of place.

**Comment by JamesCoyle** [comment]
It wouldn't really fit in well with the material design guidelines as the original is already really thin. Very few icons are suited to outline variants. 

The [Nova icon pack](http://www.webalys.com/nova/) has a couple of material like icons that may work though.

**Comment by GreenTurtwig** [comment]
Yeah unfortunately this isn't possible, even with a 1.5px border like [account-multiple-outline](https://materialdesignicons.com/icon/account-multiple-outline) uses. You can see what it looks like below, not very good. :-(

![image](https://user-images.githubusercontent.com/15905797/29744610-948f6580-8aa0-11e7-9235-5527d13f34dd.png)
![image](https://user-images.githubusercontent.com/15905797/29744611-a3ae3d48-8aa0-11e7-9bf1-92e441888d28.png)
[airplane-outline.zip](https://github.com/Templarian/MaterialDesign/files/1253938/airplane-outline.zip)

I've attached it just in case you want to use it.
