### ISSUE TITLE
Invoice icons [close]

### ISSUE THREAD

**Issue by jecsham** [Templarian/MaterialDesign#2351]
Some icons that I need for my company.

Content pack:

- file check outline
- Invoice outline
- Invoice outline check
- database magnify

[icons.zip](https://github.com/Templarian/MaterialDesign/files/1253344/icons.zip)

**Comment by jecsham** [comment]
Icons have been created by me, recycling existing icons.

**Comment by GreenTurtwig** [comment]
`file-check-outline`

![image](https://user-images.githubusercontent.com/15905797/29744466-021f1ec8-8a9d-11e7-9bf1-0163502a3ee0.png)
![image](https://user-images.githubusercontent.com/15905797/29744469-07496ec6-8a9d-11e7-882c-7c3f453bad11.png)
[file-check-outline.zip](https://github.com/Templarian/MaterialDesign/files/1253922/file-check-outline.zip)

**Comment by PeterShaggyNoble** [comment]
Invoicing is a duplicate of #1010.

Renaming this as "Database-Magnify".

**Comment by GreenTurtwig** [comment]
Style taken from @MrGrigri https://github.com/Templarian/MaterialDesign/issues/2665.

[![](https://user-images.githubusercontent.com/15905797/33991224-af2b5c5c-e0c5-11e7-9cad-4574864b5185.png)](https://github.com/Templarian/MaterialDesign/files/1559055/database-search.zip)

**Comment by PeterShaggyNoble** [comment]
@jecsham, please leave this open until it has been added to the site.

**Comment by jecsham** [comment]
@PeterShaggyNoble Sure.

**Comment by Templarian** [comment]
[![database-search](https://materialdesignicons.com/icon/database-search)](https://materialdesignicons.com/icon/database-search)
