### ISSUE TITLE
create an icon for About us

### ISSUE THREAD

**Issue by msayanece** [Templarian/MaterialDesign#2354]

**Comment by jecsham** [comment]
You can use information icon

**Comment by JamesCoyle** [comment]
Plenty of icons you could use in that situation: 
[![](https://materialdesignicons.com/icon/information)](https://materialdesignicons.com/icon/information)[![](https://materialdesignicons.com/icon/help-circle)](https://materialdesignicons.com/icon/help-circle)[![](https://materialdesignicons.com/icon/account-card-details)](https://materialdesignicons.com/icon/account-card-details)[![](https://materialdesignicons.com/icon/sign-text)](https://materialdesignicons.com/icon/sign-text)

**Comment by msayanece** [comment]
Thanks man, actually finding icons by a name are very difficult
