### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by msayanece** [Templarian/MaterialDesign#2355]

**Comment by msayanece** [comment]
should be like this...

![](http://www.uniqueengineers.com/images/Terms-and-Conditions.jpg)

**Comment by GreenTurtwig** [comment]
Very similar design to https://github.com/Templarian/MaterialDesign/issues/2151
Might be worth closing this issue.

**Comment by msayanece** [comment]
Thanks Green. That could be a work around.
