### ISSUE TITLE
create an icon for change password

### ISSUE THREAD

**Issue by msayanece** [Templarian/MaterialDesign#2357]

**Comment by MrGrigri** [comment]
Will `lock-reset` work for you?

![lock-reset](https://materialdesignicons.com/icon/lock-reset)

**Comment by msayanece** [comment]
Thanks a lot man, It is what was needed.

**Comment by PeterShaggyNoble** [comment]
There's also the `textbox-password` and `account-key` icons that may be of use to you.

[![](https://materialdesignicons.com/icon/textbox-password)](https://materialdesignicons.com/icon/textbox-password) [![](https://materialdesignicons.com/icon/account-key)](https://materialdesignicons.com/icon/account-key)
