### ISSUE TITLE
New GitHub label

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2358]
@Templarian and @JamesCoyle, what are y'all's thought on adding a new GitHub label for icons that have a contribution and are finalized and ready to get added. My suggestion would be `icon finalized`. And then we could add a direct link to the post on the issue that is the finalized icon.

**Comment by Templarian** [comment]
@MrGrigri Use High Priority for those please. I'm doing a small release right when I get back from New Orleans next week and will be adding a handful of icons (there is a bug in the `meta.json` that needs to be resolved).

**Comment by Templarian** [comment]
@MrGrigri Oh yea, lets use the `Needs more Information` after a week of no reply add the `consider closing` label.

**Comment by MrGrigri** [comment]
Maybe we should add a Wiki for the labels and the process to getting an icon added. thoughts?

**Comment by GreenTurtwig** [comment]
Personally I hardly ever read GitHub wikis, as it's not that obvious they're there and so I never realise one exists. The README would probably be a better place, it needs more info on how to submit a suggestion anyhow.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign/blob/master/CONTRIBUTING.md

You guys can make direct edits to document above. 😄 Agreed, no one really uses GitHub wiki's.

**Comment by JamesCoyle** [comment]
Wiki's are great for the more complex libraries and things like that which need proper documentation but they are almost always linked to in the readme anyway.

**Comment by Templarian** [comment]
@JamesCoyle Probably something we can look into for the new site (when I actually get time to focus on that, so happy it's almost winter).
