### ISSUE TITLE
wave/surf/ocean/tide

### ISSUE THREAD

**Issue by FletchNZ** [Templarian/MaterialDesign#2360]
I was looking an icon for wave/surf/ocean/tide/sea type thing (specifically tide), I was expecting a half crescent type wave icon but couldnt fine one.

**Comment by derwaldgeist** [comment]
I am looking for an icon for a surfboard.

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/waves)](https://materialdesignicons.com/icon/waves)
