### ISSUE TITLE
please add arrow up and down

### ISSUE THREAD

**Issue by Sumith-Roshan** [Templarian/MaterialDesign#2361]
<Path Width="44" Height="46.5" Canvas.Left="16" Canvas.Top="14.75" Stretch="Fill" Fill="#FF000000" Data="F1 M 52,54L 44,54L 44,29.25L 35.9999,37.25L 35.9999,26.75L 48,14.75L 59.9999,26.75L 59.9999,37.25L 52,29.25L 52,54 Z M 23.9999,22L 31.9999,22L 31.9999,46.75L 40,38.75L 40,49.25L 27.9999,61.25L 16,49.25L 16,38.75L 23.9999,46.75L 23.9999,22 Z "/>

**Comment by GreenTurtwig** [comment]
We already have a large selection of arrows to represent both up and down, could one of these work?

![image](https://user-images.githubusercontent.com/15905797/29820592-e83a4344-8cbc-11e7-84e3-4fc903007d05.png)
Searching for "arrow up" will give you these results.

**Comment by Templarian** [comment]
I think the `swap-vertical` might be the one you're looking for.

[![swap-vertical](https://materialdesignicons.com/icon/swap-vertical)](https://materialdesignicons.com/icon/swap-vertical)

**Comment by Sumith-Roshan** [comment]
Yes I was.. @Templarian  Thank you :)
