### ISSUE TITLE
Double circle / Ripple

### ISSUE THREAD

**Issue by ginlime** [Templarian/MaterialDesign#2363]
In Japan, we use a circle for "good".
And, a doubled circle means "better".
This can be used for "ripple", I think.

![double_circle_s](https://user-images.githubusercontent.com/3253790/29856714-aba85348-8d8f-11e7-8272-470226083df0.png)
![double_circle_l](https://user-images.githubusercontent.com/3253790/29856719-b44fa0a0-8d8f-11e7-8361-b0c5478d8649.png)
[double_circle.zip](https://github.com/Templarian/MaterialDesign/files/1262491/double_circle.zip)

**Comment by JapanYoshi** [comment]
~~Maybe we could add a flower circle icon~~

**Comment by ginlime** [comment]
@JapanYoshi 
Oh, I see...
Cherry blossom mark, too! :)

**Comment by Templarian** [comment]
Named it `circle-double`, but I don't think `outline` makes sense for this one.
