### ISSUE TITLE
Sailing Boat (and boat in general)

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#2365]
Looking for an icon for sailing. Couldn't find a generic boat either.

**Comment by JamesCoyle** [comment]
We have ferry which still needs aliasing as I couldn't find it without #1913 
[![](https://materialdesignicons.com/icon/ferry)](https://materialdesignicons.com/icon/ferry)

**Comment by derwaldgeist** [comment]
Yep, I saw the ferry. But I needed a ship that is run by an individual, i.e. a motor yacht or a sailing ship. In my use-case, the app is about traveling styles.

**Comment by GreenTurtwig** [comment]
Something as simple as below could work:
![puush-linux 2017-09-20 at 08 28 55](https://user-images.githubusercontent.com/15905797/30663541-e496d472-9e42-11e7-8bb4-1a592fac5757.png)
![puush-linux 2017-09-20 at 08 29 16](https://user-images.githubusercontent.com/15905797/30663544-e63cda60-9e42-11e7-8a16-1368822e2ba3.png)
[sailing.zip](https://github.com/Templarian/MaterialDesign/files/1318976/sailing.zip)

**Comment by derwaldgeist** [comment]
That would be just awesome!

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/50836293-df723680-1326-11e9-98e8-5493cc4da6ae.png)

[ic_sailing_white_fill.svg.zip](https://github.com/Templarian/MaterialDesign/files/2737102/ic_sailing_white_fill.svg.zip)

**Comment by Templarian** [comment]
That Google fit icon has a lot of unnecessary detail. Going to go with the simplest path.

Added 😃
