### ISSUE TITLE
Youtube Creator Studio

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2367]
![youtube_creator_studio](https://user-images.githubusercontent.com/1309249/29894272-0e8d309c-8dd5-11e7-83b1-cf83014635b9.png) [youtube_creator_studio.zip](https://github.com/Templarian/MaterialDesign/files/1265042/youtube_creator_studio.zip)

Found on YouTube (new MD design), minimally edited to remove a strange kink on the right side.

**Comment by Templarian** [comment]
[![youtube-creator-studio](https://materialdesignicons.com/icon/youtube-creator-studio)](https://materialdesignicons.com/icon/youtube-creator-studio)
