### ISSUE TITLE
Xiaomi Robot Vac Icon

### ISSUE THREAD

**Issue by Kanga-Who** [Templarian/MaterialDesign#2368]
Hey guys,

I would love to see a Xiaomi Robot Vac icon. I have no idea on working with vectors, or I would have a go myself at tackling it.

This is the image I have in mind to work from. Thanks in advance!
![xiaomi vac](https://user-images.githubusercontent.com/28994223/29905246-c82d2d10-8e50-11e7-895d-bf484d0a888c.png)

**Comment by Templarian** [comment]
I think I'm going to be renaming the `roomba` to `robot-vacuum` in the next release. These are too niche to have icons for each one. I'll keep the vector sources in this repo, but not the pack.

Would this be fine for your use?

**Comment by Kanga-Who** [comment]
I see your point. A generic robot vac icon would be good, one that doesn't necessarily look like any one in particular, but is recognizable as a robot vac.

I'm currently using 'currency-sign', but will try the 'roomba' icon. Thanks for your help.

**Comment by lance36** [comment]
Came here looking for a robot vacuum icon. +1 for rename
