### ISSUE TITLE
Gradle Icon

### ISSUE THREAD

**Issue by ArnyminerZ** [Templarian/MaterialDesign#2369]
It would be great to have an Android Gradle Icon.

**Comment by MrGrigri** [comment]
Are you referring to [this](https://gradle.org/) website?

**Comment by ArnyminerZ** [comment]
![gradle](https://user-images.githubusercontent.com/12086466/29935754-322e8446-8e80-11e7-9275-ed39004cf297.png)
This logo. Only the logo, not the text

**Comment by MrGrigri** [comment]
It appears to me that Gradle has changed their logo to an elephant. If that is the case, then what you are wanting will not get added.

**Comment by Templarian** [comment]
We won't be adding Build tools, there are just too many of them out there.
