### ISSUE TITLE
Bottle icon

### ISSUE THREAD

**Issue by RobbySmet** [Templarian/MaterialDesign#237]
I need a soda bottle icon. 
Something like this : 

![183014546](https://cloud.githubusercontent.com/assets/2357099/6804448/f43bc410-d23d-11e4-843a-c702d7364557.jpg)
- [ ] bottle

**Comment by Templarian** [comment]
Hopefully it has some context around it. Most will think beer first.

**Comment by RobbySmet** [comment]
I need it for a bottle of tonic (I'm making a gin application) so it would need to look something like this:
![fever-tree_mediterranean_1](https://cloud.githubusercontent.com/assets/2357099/6806977/17638fdc-d24c-11e4-9610-7f39df7b955e.jpg)

**Comment by CoDEmanX** [comment]
Maybe some other types of bottles too? Plastic bottle, baby bottle, vine bottle...

**Comment by GreenTurtwig** [comment]
A "soda" bottle has been submitted in https://github.com/Templarian/MaterialDesign/issues/1404 now. :-)

**Comment by MrGrigri** [comment]
I've got two styles for us to choose from. 

![bottle-soda-classic](https://user-images.githubusercontent.com/4528551/36216345-bfa80c16-116b-11e8-8498-f08942871810.png) ![bottle-soda](https://user-images.githubusercontent.com/4528551/36216442-131036da-116c-11e8-9545-342aeafc7475.png)

[bottle-soda.zip](https://github.com/Templarian/MaterialDesign/files/1724884/bottle-soda.zip)

**Comment by JamesCoyle** [comment]
I'll try have a play with these to see if I can get them closer to the bottle-wine icon.

**Comment by CoDEmanX** [comment]
The concave sharp of the classic bottle is almost gone at 24px size 😞

**Comment by MrGrigri** [comment]
I've refactored the icons. I also tried an outlined variant of the classic bottle, but it didn't work.

![image](https://user-images.githubusercontent.com/4528551/61307628-e5504500-a7ab-11e9-8c33-13263c43db5f.png)
![image](https://user-images.githubusercontent.com/4528551/61307657-f6995180-a7ab-11e9-842b-51257c837b39.png) ![image](https://user-images.githubusercontent.com/4528551/61307923-69a2c800-a7ac-11e9-9811-74f4f1822da6.png)

---
#### Files

Files have been pre-optimized.
[bottle-soda.zip](https://github.com/Templarian/MaterialDesign/files/3397863/bottle-soda.zip)

**Comment by goyney** [comment]
[![bottle-soda](https://materialdesignicons.com/icon/bottle-soda)](https://materialdesignicons.com/icon/bottle-soda)
[![bottle-soda-outline](https://materialdesignicons.com/icon/bottle-soda-outline)](https://materialdesignicons.com/icon/bottle-soda-outline)
[![bottle-soda-classic](https://materialdesignicons.com/icon/bottle-soda-classic)](https://materialdesignicons.com/icon/bottle-soda-classic)
