### ISSUE TITLE
Table Settings

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2372]
Needed an image for Timetable Setting.

![timetable-settings 16x16](https://user-images.githubusercontent.com/20706106/29972172-2e4024ba-8ef9-11e7-824e-69884633d0cc.png)
![timetable-settings 48x48](https://user-images.githubusercontent.com/20706106/29972174-2e55128a-8ef9-11e7-80a9-ce35b2b146b9.png)
![timetable-settings 128x128](https://user-images.githubusercontent.com/20706106/29972173-2e410db2-8ef9-11e7-8581-dd2284a5c8c5.png)

[timetable-settings.zip](https://github.com/Templarian/MaterialDesign/files/1270400/timetable-settings.zip)

**Comment by JamesCoyle** [comment]
I'm not sure if we want to add this to the iconset. We can't add a settings variant for every icon and this seems a little on the niche side of things.

**Comment by OctoberJemini** [comment]
Complete understand.  What if it was converted to just Table Settings, so its a little more board?

**Comment by JamesCoyle** [comment]
That would probably be more multipurpose. :)

**Comment by OctoberJemini** [comment]
Table Settings

![table-settings 24x24](https://user-images.githubusercontent.com/20706106/29975393-315f1b1e-8f04-11e7-8e0c-bf0a51e33c2b.png)
![table-settings 48x48](https://user-images.githubusercontent.com/20706106/29975391-315bf2d6-8f04-11e7-8742-2c27e30451a2.png)
![table-settings 128x128](https://user-images.githubusercontent.com/20706106/29975392-315d1bde-8f04-11e7-96f0-22f1b139c989.png)

[table-settings.zip](https://github.com/Templarian/MaterialDesign/files/1270624/table-settings.zip)

**Comment by MrGrigri** [comment]
I know that I for one could use this in a project

**Comment by JamesCoyle** [comment]
I could see it being helpful for applications that use a data-grid view or a complex table but allow the user to alter column settings etc.

**Comment by Templarian** [comment]
[![table-settings](https://materialdesignicons.com/icon/table-settings)](https://materialdesignicons.com/icon/table-settings)

Agreed the more generic table will get more use. 😸 

@OctoberJemini If/when you hit 5 icons let me know and I'll create you a contributor account (tons of open issues, relatively easy to hit 5).

**Comment by MrGrigri** [comment]
@Templarian, the icon looks like it's 2 pixels down.
