### ISSUE TITLE
weight-lb

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#2373]
Seeing that kilogram was the world standard, it seemed weird that we have an icon specifying that it's the world standard, but no icon specifying that it's the finicky American one. So I went to correct that issue (and also make it in MD-native letters, not Roboto).

![weight-kg-lb](https://user-images.githubusercontent.com/8707990/29972276-f00e8274-8f6e-11e7-9e5b-fac712783f1f.png)
![weight-kg-lb-big](https://user-images.githubusercontent.com/8707990/29972275-f00db1f0-8f6e-11e7-87dd-13977c027fa3.png)
[weight-kg-lb.zip](https://github.com/Templarian/MaterialDesign/files/1270359/weight-kg-lb.zip)

**Comment by JapanYoshi** [comment]
Bump.

**Comment by Templarian** [comment]
Updated/Added. 😸
