### ISSUE TITLE
Grocery

### ISSUE THREAD

**Issue by Per4merKC** [Templarian/MaterialDesign#2376]
I would love to have an icon for a grocery store.  Perhaps a grocery bag?

**Comment by k5cents** [comment]
We have `shopping` and `cart`. Will those not work?

**Comment by MrGrigri** [comment]
Or `store`

![store](https://materialdesignicons.com/icon/store)

**Comment by Per4merKC** [comment]
For my purpose, shopping and store did not work; however, I totally overlooked the cart and it's variants!  :)  CART works for me!
