### ISSUE TITLE
Jenkins CI Icon

### ISSUE THREAD

**Issue by mikimn** [Templarian/MaterialDesign#2377]
Jenkins is a CI most of the developer community uses to deploy and maintain projects. When I find myself building a custom material dashboard for my company, I would also like to have a reference there to the Jenkins server, and therefore, a Jenkins icon is needed, and I think would be useful for entire community! It also shouldn't be that difficult as it would be basically just outlining their logo.
This is an image for reference:

![jenkins-ci_512](https://user-images.githubusercontent.com/1588118/29989909-ea4216fc-8f7e-11e7-993a-83b53d11bda0.png)

**Comment by JamesCoyle** [comment]
Too specific and far from material spec.
