### ISSUE TITLE
More Groceries/Food Items

### ISSUE THREAD

**Issue by GeorgeWL** [Templarian/MaterialDesign#2378]
I'm by no means expecting everything, that would just be ridiculous, but maybe some extra food items would be quite good. Think there's 6 currently, which already is quite a good amount, but more the merrier.

Making a material design shopping list and was thinking about this as a thing just as a bit of flavour to the design that if it recognises a term it will put the icon next to it 😃

**Comment by JamesCoyle** [comment]
The best idea would be to create issues for individual icons that you need. Try provide reference material too.

**Comment by GeorgeWL** [comment]
well,  its more of a general request though rather than a explicit one. 
@jamescoyle

**Comment by JamesCoyle** [comment]
Yeah and it's been requested plenty before but no one contributes unless it's a specific icon on something they need themselves. That's why we say requests should be for a single icon only. It's easier to track, gauge interest on, and contribute to an issue when you know exactly what the icon should be.

**Comment by bonti** [comment]
I want one icon to signify Groceries.
And a separate icons for each of the categories like Dairy, Produce, Meat etc.... Should I submit separate requests for the different categories of groceries? I apologize in advance for being a bit clueless, as this is the first time I am commenting on this board.

**Comment by Templarian** [comment]
Some of these icon requests may already exist, but yes it may seem like your annoying us, but it's actually easier for us to manage as individual issue requests. Don't forget to search first.
