### ISSUE TITLE
Some Google Material Icons are missing

### ISSUE THREAD

**Issue by paul70078** [Templarian/MaterialDesign#2379]

**Comment by PeterShaggyNoble** [comment]
If you have a list of specific icons you'd like to see added, please provide it. Be sure to check the existing [Stock Google Icon issues](https://github.com/Templarian/MaterialDesign/issues?q=label%3A%22Stock+Google+Icon%22) first, though, to avoid duplicates.

**Comment by paul70078** [comment]
I've found the icons by the spreadsheet with conflicting icons. Please include a link to the spreadsheet in the reademe :)
