### ISSUE TITLE
Icon request: Fan

### ISSUE THREAD

**Issue by mhalak** [Templarian/MaterialDesign#2380]
It would be great to have some icons for fans, ceiling fan, ventilation and such...

**Comment by walkoffhomerun** [comment]
will these not work:
https://materialdesignicons.com/icon/fan
https://materialdesignicons.com/icon/air-conditioner

**Comment by mhalak** [comment]
Actually these are just fine, but when I searched "fan" there were no results.

Good idea on asterisk . This can be useful as well.
Thx
