### ISSUE TITLE
icons not displaying but show as available

### ISSUE THREAD

**Issue by walkoffhomerun** [Templarian/MaterialDesign#2381]
using material icons version 2.0.46 which is the current version available as of the writing of this post

"golf" does NOT appear when trying to use.  it shows as a Google created icon should be part of the original material icons
https://materialdesignicons.com/icon/golf

"hot-tub"....same as above.  Another google created font not working
https://materialdesignicons.com/icon/hot-tub

"floor-plan" does show in the available icons and shows when searched for but does NOT appear when trying to use
https://materialdesignicons.com/icon/floor-plan

**Comment by GreenTurtwig** [comment]
All those icons were recently added to the set and so will be available in the next release.
You can check the history here: https://materialdesignicons.com/history

**Comment by ivanjaros** [comment]
I find this also very strange. Icons are shown in the list but actually do not exist in the css.

**Comment by JamesCoyle** [comment]
The icons are available for SVG usage but the font is released periodically. The new site will make things clearer. Files should be downloaded from the site and not GitHub.

**Comment by ivanjaros** [comment]
So when's the next "release"?

**Comment by Templarian** [comment]
@ivanjaros Soon™... or might actually be a bit. It's taking longer than normal to get cold outside... all these nice days are messing with my open source time. 😿

**Comment by JamesCoyle** [comment]
When it's ready. If you need the icons now just use inline SVG.

**Comment by PeterShaggyNoble** [comment]
@ivanjaros, if you have an urgent need for a particular icon that has yet to be added to the font, you could use something like [Icomoon](https://icomoon.io/) to build a custom font.
