### ISSUE TITLE
Change ownership

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#2382]
I'm looking for an icon which symbolizes changing in ownership (of real estates). 
The idea of our customer is 2 people with tophat and interchange-arrow like in [account-switch](https://materialdesignicons.com/icon/account-switch). But I think 2 persons with tie or one person with tophat/tie like in [account-convert](https://materialdesignicons.com/icon/account-convert) would also work.
We currently use the  [account-switch](https://materialdesignicons.com/icon/account-switch)-icon which does not statisfy our customer, because the ownership-aspect is not strong enough.

These are just suggestions. Any other icon representing a switch/change of a powerful person (boss, admin, owner) is also highly appreciated.

Let me use this request to highlight the aspect, that we miss icons for people with authority like "boss" or "admin" in general.

**Comment by TheChilliPL** [comment]
I'll try that tomorrow

**Comment by Ch-Lo** [comment]
@TheChilliPL : Do you have some results yet? =)

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
