### ISSUE TITLE
file-percent

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#2384]
So, I'm looking for icon of school grade, like this, for example
![file](https://user-images.githubusercontent.com/18823939/30036681-c79224e2-91b5-11e7-9093-6d5cec7fe453.png)

**Comment by augustin32** [comment]
![school-grade24](https://user-images.githubusercontent.com/14167196/30073268-df4d1f2c-9275-11e7-89b8-7f4629a9df86.png)
![school-grade36](https://user-images.githubusercontent.com/14167196/30073273-e203ad08-9275-11e7-8109-282c3087050e.png)
![school-grade48](https://user-images.githubusercontent.com/14167196/30073278-e458d150-9275-11e7-886e-9e7b2302084a.png)
[school-grade.zip](https://github.com/Templarian/MaterialDesign/files/1278260/school-grade.zip)

**Comment by MrGrigri** [comment]
Does `format-annotation-plus` not work?

![format-annotation-plus](https://materialdesignicons.com/icon/format-annotation-plus)

**Comment by MrGrigri** [comment]
@augustin32, the width between the text and side of the document is not 2 pixels.

**Comment by augustin32** [comment]
@MrGrigri, sorry for that, but without 1 pixel space  the icon is unreadable at 1x resolution

**Comment by MrGrigri** [comment]
Correct, that's why I have asked @TheChilliPL, if `format-annotation-plus` would work. I do not believe that his suggestion of a file + 'A+' will work with MD.

**Comment by augustin32** [comment]
@MrGrigri, from now i will be more accurate with guidelines and search for alternatives that already's on the site, thanks :)

**Comment by Ch-Lo** [comment]
I just want to remember, that not all countries use letters for grades...

**Comment by JapanYoshi** [comment]
File + percent could work though.

**Comment by MrGrigri** [comment]
@Ch-Lo that's another reason why I don't believe that his suggestion would work. @JapanYoshi, I do believe that would work.

![file-percent](https://user-images.githubusercontent.com/4528551/30117051-595e8cf4-92dc-11e7-87b6-1838165c8708.png)

[file-percent.zip](https://github.com/Templarian/MaterialDesign/files/1281403/file-percent.zip)

**Comment by JamesCoyle** [comment]
UK did when I was sitting exams but now they are switching to numbers and we already use numbers for university degrees. Localisation is always an issue. #1240

**Comment by TheChilliPL** [comment]
Okay, format-annotations-plus will work ;)

**Comment by TheChilliPL** [comment]
But wait a second, I'm learning how to make icons, and I made pretty nice icon for it, I will upload it in a moment

**Comment by TheChilliPL** [comment]
Alright, "A" letter looks a little bit strange, but anyway - here it is

![school-grade](https://user-images.githubusercontent.com/18823939/30241183-8607df68-957e-11e7-9bed-4900c2896a0a.png)
[school-grade.zip](https://github.com/Templarian/MaterialDesign/files/1289876/school-grade.zip)

**Comment by JapanYoshi** [comment]
Those letters aren't according to Material Design specifications.

**Comment by TheChilliPL** [comment]
Whoops

**Comment by Templarian** [comment]
[![file-percent](https://materialdesignicons.com/icon/file-percent)](https://materialdesignicons.com/icon/file-percent)
