### ISSUE TITLE
Truck and Wrench check-Icons

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#2385]
We needed a truck-check and a wrench-check icons for our project. So I upload them here to get them a chance to become part of this amazing project. ;)

![truck-check](https://user-images.githubusercontent.com/23208271/30049097-7d154b88-9219-11e7-92b3-a0f8afb01cbd.png)
![wrench-check](https://user-images.githubusercontent.com/23208271/30049100-81c2ce4e-9219-11e7-9d88-5fc9881f2c3f.png)

[truck-wrench-check.zip](https://github.com/Templarian/MaterialDesign/files/1276374/truck-wrench-check.zip)

**Comment by MrGrigri** [comment]
I do not believe that `wrench-check` would confom to MD. What are you looking for UI-wise with it?

**Comment by JamesCoyle** [comment]
They seem too specialized for mdi tbh.

**Comment by Ch-Lo** [comment]
`wrench-check` is used for a done hardeware installation.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by PeterShaggyNoble** [comment]
`truck-check` has since been added.
