### ISSUE TITLE
Gold Ingot

### ISSUE THREAD

**Issue by AlvaroR156** [Templarian/MaterialDesign#2386]
A nice ingot block, single and stacked. Can be used as a savings or currency icon.

**Comment by augustin32** [comment]
![gold-stack24](https://user-images.githubusercontent.com/14167196/30073686-6114d210-9277-11e7-8de7-5d9510184bb6.png)
![gold-stack36](https://user-images.githubusercontent.com/14167196/30073692-632461c4-9277-11e7-8fba-32f3b4bab1de.png)
![gold-stack48](https://user-images.githubusercontent.com/14167196/30073695-6534ac62-9277-11e7-8582-70c750c9fca8.png)
[gold-stack.zip](https://github.com/Templ
arian/MaterialDesign/files/1278281/gold-stack.zip)

**Comment by CoDEmanX** [comment]
Hm, could also be a pyramid. Maybe articulate the gaps a bit more?

**Comment by CoDEmanX** [comment]
Cross-posting #3937:

![grafik](https://user-images.githubusercontent.com/1309249/53692092-3249f680-3d8a-11e9-9368-324feed34d69.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/68005755-478e6200-fc44-11e9-8f7a-7a05eba96b96.png)

Hows this?

**Comment by Templarian** [comment]
Added.
