### ISSUE TITLE
toothbrush-electric

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2388]
Needed an electric toothbrush icon for something I'm working on so made these real quick. Not the best in my opinion as it's difficult to design an icon for something as thin as a toothbrush, but they get the point across.

![image](https://user-images.githubusercontent.com/15905797/30084578-dd9e37be-928a-11e7-88dc-0f27ed540104.png)
![image](https://user-images.githubusercontent.com/15905797/30084592-e712f14a-928a-11e7-99c7-b7c6608b1192.png)

![image](https://user-images.githubusercontent.com/15905797/30085232-7346ef34-928d-11e7-8cf1-6b6b0b4f19bf.png)
![image](https://user-images.githubusercontent.com/15905797/30085238-7ac701fe-928d-11e7-84ab-390b6de33f10.png)

![image](https://user-images.githubusercontent.com/15905797/30084603-f66ff048-928a-11e7-8586-5e871ad2d1aa.png)
![image](https://user-images.githubusercontent.com/15905797/30084612-fca68a26-928a-11e7-9857-23ec0233ad6f.png)

[toothbrushes.zip](https://github.com/Templarian/MaterialDesign/files/1279066/toothbrushes.zip)

**Comment by MrGrigri** [comment]
IDK, IMO these do not stand alone. You'd have to be told that they are toothbrushes.

**Comment by GreenTurtwig** [comment]
Totally agree, as I said before it's difficult to make designs for something thin with Material Designs limitations. They (sort of) work in context though, the electric toothbrush is the only one I'm currently using.

**Comment by JamesCoyle** [comment]
Toothbrush tracked in #4282 

Using this for the electric variant but should both be similar designs for consistency.

**Comment by CoDEmanX** [comment]
Note the 3dp corner radius and the upper terminal being shifted 0.5dp into the margin in the 2nd, which helps recognizability IMO:

![grafik](https://user-images.githubusercontent.com/1309249/62863698-e1abd180-bd09-11e9-895c-9be8fc282406.png)

![grafik](https://user-images.githubusercontent.com/1309249/62863677-d193f200-bd09-11e9-8bdb-9087c193a205.png)

Just for the sack of comparison one which would be inconsistent with the analog toothbrush:

![grafik](https://user-images.githubusercontent.com/1309249/62863815-364f4c80-bd0a-11e9-877a-ae4b33240db2.png)

[toothbrush-electric.zip](https://github.com/Templarian/MaterialDesign/files/3492218/toothbrush-electric.zip)

**Comment by CoDEmanX** [comment]
With individual bristles for reference:

![grafik](https://user-images.githubusercontent.com/1309249/62865016-9dbacb80-bd0d-11e9-8263-9ef6dc661686.png)

[toothbrush-electric4.zip](https://github.com/Templarian/MaterialDesign/files/3492315/toothbrush-electric4.zip)

**Comment by CoDEmanX** [comment]
Adding a mixed filled and outlined variant only for now:

![grafik](https://user-images.githubusercontent.com/1309249/62905350-69c1c380-bd6a-11e9-8ae6-585bdefb1a67.png)
