### ISSUE TITLE
Healthcare Icons

### ISSUE THREAD

**Issue by sakyadas** [Templarian/MaterialDesign#2389]
Hi, can u make ICONS for Telehealth, EMR(Electronic Medical Record ), Communication

**Comment by MrGrigri** [comment]
Would `folder-plus` work? The icons that I'm seeing for EMR is a folder or computer with the medical cross on it (or plus).

![folder-plus](https://materialdesignicons.com/icon/folder-plus)

**Comment by sakyadas** [comment]
Ya MrGrigri thaks for your reply, it will work

**Comment by sakyadas** [comment]
How can i use it as a font icon?

**Comment by Templarian** [comment]
@sakyadas https://materialdesignicons.com/getting-started Explains the steps to use the webfont.

If you mean a font file... you can use the https://materialdesignicons.com/design download.
