### ISSUE TITLE
Add icons from DocumentsUi

### ISSUE THREAD

**Issue by jaredrummler** [Templarian/MaterialDesign#239]
There is no vector drawable for them but the following icons would match up with the other google icons:

https://github.com/android/platform_frameworks_base/blob/master/packages/DocumentsUI/res/drawable-xxxhdpi/ic_doc_spreadsheet_am_alpha.png
![ic_doc_spreadsheet_am_alpha](https://cloud.githubusercontent.com/assets/6203389/6843216/0a8c14ec-d35e-11e4-855f-6cf2626de86e.png)

https://github.com/android/platform_frameworks_base/blob/master/packages/DocumentsUI/res/drawable-xxxhdpi/ic_doc_pdf_alpha.png
![ic_doc_pdf_alpha](https://cloud.githubusercontent.com/assets/6203389/6843222/1ca1668c-d35e-11e4-9e85-60bf7b0785d8.png)

https://github.com/android/platform_frameworks_base/blob/master/packages/DocumentsUI/res/drawable-xxxhdpi/ic_doc_font_alpha.png
![ic_doc_font_alpha](https://cloud.githubusercontent.com/assets/6203389/6843228/273b576a-d35e-11e4-876f-1fcb59d52c63.png)

https://github.com/android/platform_frameworks_base/blob/master/packages/DocumentsUI/res/drawable-xxxhdpi/ic_doc_codes_alpha.png
![ic_doc_codes_alpha](https://cloud.githubusercontent.com/assets/6203389/6843230/2fe0da0c-d35e-11e4-83f6-13999d0f78ec.png)

https://github.com/android/platform_frameworks_base/blob/master/packages/DocumentsUI/res/drawable-xxxhdpi/ic_doc_apk_alpha.png
![ic_doc_apk_alpha](https://cloud.githubusercontent.com/assets/6203389/6843236/3bbe80ea-d35e-11e4-9e9b-077423df7d74.png)

https://github.com/android/platform_frameworks_base/blob/master/packages/DocumentsUI/res/drawable-xxxhdpi/ic_doc_audio_alpha.png
![ic_doc_audio_alpha](https://cloud.githubusercontent.com/assets/6203389/6843241/43674fac-d35e-11e4-8894-73c976961431.png)
- [ ] file-spreadsheets-box
- [ ] xml-box
- [ ] font-format-box
- [ ] android-box

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/headphones-box already exists
http://materialdesignicons.com/icon/file-pdf-box already exists

The others exist just not in `-box` styles. Will have to see how these size.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
