### ISSUE TITLE
Google's child-care

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#2390]
I was looking for an icon that stands for "birthplace" or "birthdate".

I found "baby" and "baby-buggy". For my purpose, the buggy looks best, but I would rather prefer a baby that is shown from the front and maybe also has a pacifier / dummy in its face. Would look a bit more cute and to the point.

**Comment by MrGrigri** [comment]
I believe that what you are suggesting is not in line with MD guidelines and may be too specific. Typically, a calendar is used for dates; even birthdates.

**Comment by JamesCoyle** [comment]
I think a baby emoji would work as in icon but a full baby wouldn't really fit.

**Comment by derwaldgeist** [comment]
@JamesCoyle I was thinking about something like this:
https://www.flaticon.com/free-icon/baby-head-outline-with-pacifier_29952

@MrGrigri Problem is: That might work for the birthday (though it causes problems if you need the calendar for other purposes). But how would you symbolise a birthplace?

**Comment by MrGrigri** [comment]
Another option for a birthday icon is `cake` and it's variants. For birthplace, I would use `hospital-marker`.

![cake](https://materialdesignicons.com/icon/cake) ![hospital-marker](https://materialdesignicons.com/icon/hospital-marker)

**Comment by JamesCoyle** [comment]
Google seems to have the icon shown here: 
![image](https://user-images.githubusercontent.com/10384436/30289826-51c3ae82-9725-11e7-8916-d09f0d0ad5d8.png)

Could also include that awesome dining icon too.

**Comment by augustin32** [comment]
What do you think?
![baby-front24](https://user-images.githubusercontent.com/14167196/31049692-e2d9c63e-a640-11e7-9e93-e1202508ae17.png)
![baby-front36](https://user-images.githubusercontent.com/14167196/31049693-e4a59704-a640-11e7-93f6-361d1fa020c3.png)
![baby-front48](https://user-images.githubusercontent.com/14167196/31049694-e5de6f24-a640-11e7-8e5a-2cfba7d398a6.png)
[baby-front.zip](https://github.com/Templarian/MaterialDesign/files/1346766/baby-front.zip)

**Comment by derwaldgeist** [comment]
@augustin32: Hey, that's a lovely baby :-)

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49034792-ea12ab00-f180-11e8-809d-bd1f78540022.png)
[baby-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/2616889/baby-variant.svg.zip)

**Comment by CoDEmanX** [comment]
Should be called `baby-variant-outline` I guess?

BTW: There is also a `mother-nurse` icon which might be suitable.

**Comment by Templarian** [comment]
That icon is terrifying.

[![baby-face-outline](https://materialdesignicons.com/icon/baby-face-outline)](https://materialdesignicons.com/icon/baby-face-outline)
