### ISSUE TITLE
Genius icon

### ISSUE THREAD

**Issue by Chan4077** [Templarian/MaterialDesign#2392]
I was looking for an icon that looks like the genius product icon.

![Genius product icon](https://images.genius.com/8ed669cadd956443e29c70361ec4f372.1000x1000x1.png)

[More info about Genius](https://genius.com/Genius-about-genius-annotated)

**Comment by MrGrigri** [comment]
IMO, that does not illustrate a genius, `glasses` do.

![glasses](https://materialdesignicons.com/icon/glasses)

**Comment by Templarian** [comment]
This is going to be too specific for the icon pack at the moment. Mostly only including large social media brands.

**Comment by JapanYoshi** [comment]
@MrGriGri Not a literal genius, silly—it's the Website formerly known as Rap Genius that annotates and explains song lyrics, rap lyrics, poems, and more.
