### ISSUE TITLE
flag-checkered-variant

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#2393]
It's in this SVG repo, but not included in the Sass file.

Should be located here:
https://github.com/Templarian/MaterialDesign-Webfont/blob/master/scss/_variables.scss#L784

**Comment by MrGrigri** [comment]
`flag-checkered-variant` has been removed in January of 2015. Please refer to #104 for more details. 

Marking this as a bug because It's still in the SVG repo.

**Comment by Templarian** [comment]
If someone wants to redesign it. Unmarking as a bug and marking as an icon request.

**Comment by Yuanruili** [comment]
If it's ok?
[flag-checkered-variant.zip](https://github.com/Templarian/MaterialDesign/files/2941662/flag-checkered-variant.zip)
![image](https://user-images.githubusercontent.com/12135487/53963231-285b2700-40ed-11e9-9c6b-b9741ce9c4da.png)

**Comment by PeterShaggyNoble** [comment]
@Yuanruili, the [MD design guidelines](https://material.io/design/iconography/system-icons.html) don't allow for perspective, unfortunately.

**Comment by Yuanruili** [comment]
I do feel confused about this principle: 
'Make icons face forward.' 
'Don’t tilt, rotate, or make icons appear dimensional.'
 I found some icons, and think they all somehow appear dimensional. 
![image](https://user-images.githubusercontent.com/12135487/54032167-222e7e80-41b1-11e9-9aa7-16ac1964e6ad.png)
![image](https://user-images.githubusercontent.com/12135487/54032180-31adc780-41b1-11e9-8e85-87e9e5b37159.png)
![image](https://user-images.githubusercontent.com/12135487/54032302-85201580-41b1-11e9-9b4a-a0dff61378aa.png)
![image](https://user-images.githubusercontent.com/12135487/54032343-9ec15d00-41b1-11e9-997f-35f753a9ddfa.png)

**Comment by CoDEmanX** [comment]
There are some exceptions, most notably by Google itself. In some cases it's simply impossible to depict a thing without perspective because it lacks a distinct enough shape in front and side view. It should be a last resort however and the style should still feel "material".

**Comment by goyney** [comment]
Closing because the `Consider Closing` tag was added more than 30 days ago.
