### ISSUE TITLE
ecobee icon

### ISSUE THREAD

**Issue by nickgreen239** [Templarian/MaterialDesign#2395]
I found a closed request stating "It's going to be a little too specific and niche of an icon to add each of the thermostats. Closing this issue out." However there is a Nest thermostat icon. If possible I would like a simple generic ecobee icon added. I will attach a basic example.
![ecobee icon](https://user-images.githubusercontent.com/31744578/30181678-026ace9c-93e2-11e7-914a-ec1c048356b4.png)

**Comment by Templarian** [comment]
To be fair I think we're going to slowly remove these specifically named home automation icons and replace them with more generic icons.

The robot vacuums is a good example, the next release will generalize and include a `roomba` looking one and a variant. Thermostats will probably follow the same pattern. See: #2327 

Thanks for the suggestion, we're always revamping how we tailor the icon pack. 😄

**Comment by nickgreen239** [comment]
That would actually be a better solution. I look forward to seeing some good generic home automation icons. I would definitely use a few.

**Comment by GreenTurtwig** [comment]
Yep, just like the vacuum, it would be good to have a "square" variant. As not all thermostats look like Nests. :-P

I should probably give that a go later...
