### ISSUE TITLE
Icon Request : talkback unit

### ISSUE THREAD

**Issue by jmitchell10** [Templarian/MaterialDesign#2397]
Would like an icon that represents a talk-back unit.  Similar to attached png but no colour
![5](https://user-images.githubusercontent.com/22744799/30209501-57f514e0-9490-11e7-856a-dc7522a91323.png)

**Comment by PeterShaggyNoble** [comment]
Could you provide some more information on this please? I can't infer from your post nor from the image what this icon is and what it might be used for. (Although, I did forget my glasses today! 😆)

**Comment by JamesCoyle** [comment]
It might be a little too specific really. Would microphone work?
[![](https://materialdesignicons.com/icon/microphone)](https://materialdesignicons.com/icon/microphone)

**Comment by jmitchell10** [comment]
Apologies for not responding sooner, I'm going to close this request as it is now no longer required.  Thanks

**Comment by PeterShaggyNoble** [comment]
@jmitchell10, could you provide a bit more info on what it was you *were* looking for anyway? Others may have a use for it.

**Comment by jmitchell10** [comment]
@PeterShaggyNoble initially i was looking for something that would represent one of these 

![talkback](https://user-images.githubusercontent.com/22744799/31614213-7e99ef8e-b27d-11e7-8e40-852470e0a0fd.jpg)
