### ISSUE TITLE
radiation-off

### ISSUE THREAD

**Issue by cyber199** [Templarian/MaterialDesign#2398]
I would like to request a radiation-off or no-radiation icon that would act as an opposite to the existing radiation icon.  The icon itself would consist of the standard radioactivity hazard trefoil with a "no" diagonal stroke through it.  The icon could be used mainly as a game asset, perhaps as a pin on a map or as a status effect icon, though it could also be used in similar situations as the existig radiation icon.

![radioactivematerialoff](https://user-images.githubusercontent.com/5619889/30215586-5b469278-94a8-11e7-811d-1840ea44e7e2.png)

**Comment by cyber199** [comment]
I realise this could be a niche icon, but I felt it might make sence to have an opposite to the existing radiation icon.

**Comment by TheChilliPL** [comment]
So, well, i tried, but I think it looks a lil' bit strange

![radioactive-off](https://user-images.githubusercontent.com/18823939/30240714-fb936efe-9575-11e7-9ff1-903ff9ef1658.png)
[radioactive-off.zip with SVG](https://github.com/Templarian/MaterialDesign/files/1289831/radioactive-off.zip)

**Comment by MrGrigri** [comment]
You should try having the slash 30° instead of 45°. This could be a design over function type of scenario.

**Comment by TheChilliPL** [comment]
Alright, I'll try that in a minute

**Comment by TheChilliPL** [comment]
Alright, it looks like this
![radioactive-off-alt](https://user-images.githubusercontent.com/18823939/30241331-b32301d2-9581-11e7-88be-2041f21cf1e1.png)
[radioactive-off-alt.zip](https://github.com/Templarian/MaterialDesign/files/1289885/radioactive-off-alt.zip)

**Comment by Templarian** [comment]
Let's try to stay away from the 30° slash if possible. While it might be ideal, I think the 45° slash is still the best option.

**Comment by TheChilliPL** [comment]
@Templarian Yeah, besides, black line (from template) when rotated like that, is partly outside bounding box

**Comment by jacobq** [comment]
Would it work any better to have another white line below the slash? I would like to use this icon in an application that controls a soft x-ray ionization source.

**Comment by MrGrigri** [comment]
@jacobq , that's not part of MD Guidelines. IMO, I don't much care for this icon.

**Comment by JamesCoyle** [comment]
Usually the absence of the icon means radiation 'off'. Could also use a disabled state for the icon.

**Comment by jacobq** [comment]
@JamesCoyle, yes, that is what we are currently doing (using color & brightness/disabled state to differentiate). It just seemed like it would be nice to have something more explicit like a different icon. I'm trying to avoid ambiguity for our users who might, for example, be confused by a red radiation symbol not knowing whether it indicates that there is a fault related to the x-ray source or that the x-ray source is active.

**Comment by Templarian** [comment]
[![radioactive-off](https://materialdesignicons.com/icon/radioactive-off)](https://materialdesignicons.com/icon/radioactive-off)

**Comment by Templarian** [comment]
Added the aliases `radiation` and `radiation-off`.
