### ISSUE TITLE
settings-mixer

### ISSUE THREAD

**Issue by adrogon** [Templarian/MaterialDesign#2399]
![settings-mixer](https://user-images.githubusercontent.com/12794458/30225926-16251894-94cc-11e7-98e7-7a349d7594e0.jpg)

The `settings-mixer` icon looks like a channel mixer table, and conveys the idea of "settings" better than the usual "gear" icon (imho).

Although not listed as part of their Material Icons, Google already uses it.
Here is the SVG from their Photos product, thought that would help:
```
<svg>
<path d="M3 17v2h6v-2H3zM3 5v2h10V5H3zm10 16v-2h8v-2h-8v-2h-2v6h2zM7 9v2H3v2h4v2h2V9H7zm14 4v-2H11v2h10zm-6-4h2V7h4V5h-4V3h-2v6z"></path>
</svg>
```

**Comment by GreenTurtwig** [comment]
We already have it here: https://materialdesignicons.com/icon/tune

[![https://materialdesignicons.com/icon/tune](https://materialdesignicons.com/icon/tune)](https://materialdesignicons.com/icon/tune)

But yeah, it really should get `equalizer-variant` and `settings-tune` aliases. 🐈

**Comment by adrogon** [comment]
Oh, thank you for pointing that out, I really tried hard to find it though :disappointed:

**Comment by GreenTurtwig** [comment]
That's why we need aliases. :-P

**Comment by Templarian** [comment]
Added the alias `mixer-settings`. I need to add quick way for people to suggest aliases. Coming Soon™
