### ISSUE TITLE
Thermostat square variant

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2400]
Just a square variant of the thermostat icon, as with the robot vacuum icons it would be good to have two (or more) variants. https://github.com/Templarian/MaterialDesign/issues/2395

![image](https://user-images.githubusercontent.com/15905797/30228742-e71be3ec-94d6-11e7-92f6-540889524362.png)
![image](https://user-images.githubusercontent.com/15905797/30228745-ee4948c6-94d6-11e7-8b25-f42c21ff71e6.png)

![image](https://user-images.githubusercontent.com/15905797/30228751-f85ffb02-94d6-11e7-9ef7-50b3424b2aa5.png)
![image](https://user-images.githubusercontent.com/15905797/30228761-01294be4-94d7-11e7-8608-90897242b98c.png)

[thermostat-box.zip](https://github.com/Templarian/MaterialDesign/files/1288956/thermostat-box.zip)

Not sure on a 2px border or 3px border (current thermostat icon has 3px).

**Comment by Templarian** [comment]
Thanks @GreenTurtwig, will be getting these in/renamed before the next release.

**Comment by GreenTurtwig** [comment]
No problem. 🐈

**Comment by Templarian** [comment]
[![thermostat-box](https://materialdesignicons.com/icon/thermostat-box)](https://materialdesignicons.com/icon/thermostat-box)
