### ISSUE TITLE
OS X icon

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#2402]
So, I came up with an idea to start making material design icons.
First icon I made (ever) is here

OS X icon

![osx](https://user-images.githubusercontent.com/18823939/30240561-21f628b4-9573-11e7-80f2-db185d436b70.png)
[osx.zip](https://github.com/Templarian/MaterialDesign/files/1289814/osx.zip)

Do you have any suggestions for me to make icons better?

**Comment by GreenTurtwig** [comment]
OS X is now simply known as macOS since last year and anyone wanting to differentiate platforms would use the Apple logo. This may be a bit too niche, especially with the name change.

**Comment by Templarian** [comment]
Yep, going to mark this as too niche. Mac users are going to recognize the Apple logo similar to the Windows/Linux penguin/distros. Also as said above, it's now called MacOS.
