### ISSUE TITLE
Cloud-alert icon

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#2403]
So, I made cloud-error icon, and here it is
![cloud-error](https://user-images.githubusercontent.com/18823939/30241704-f0b4743e-9588-11e7-844f-9c39724dd9ca.png)
[cloud-error.zip](https://github.com/Templarian/MaterialDesign/files/1289908/cloud-error.zip)

**Comment by Templarian** [comment]
[![cloud-alert](https://materialdesignicons.com/icon/cloud-alert)](https://materialdesignicons.com/icon/cloud-alert)
