### ISSUE TITLE
Comment-question + comment-remove icons

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#2404]
![comment-question](https://user-images.githubusercontent.com/18823939/30241806-da3291da-958a-11e7-80b3-69c7b5b95f95.png)
[comment-question.zip](https://github.com/Templarian/MaterialDesign/files/1289915/comment-question.zip)

![comment-remove](https://user-images.githubusercontent.com/18823939/30241807-db2a8444-958a-11e7-8687-581fccd5e941.png)
[comment-remove.zip](https://github.com/Templarian/MaterialDesign/files/1289916/comment-remove.zip)

**Comment by petermonte** [comment]
I would add the remaining `comment-` icons on non outline version.
[mdi-comment-.zip](https://github.com/Templarian/MaterialDesign/files/1321819/mdi-comment-.zip)

**Comment by PeterShaggyNoble** [comment]
These have since been added in #2593.
