### ISSUE TITLE
Rename flag-outline-variant to flag-variant-outline

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2405]
As per the naming guidelines this breaks the current rules.

The `-outline` modifier needs to always be at the end. The docs for the new site go into depth about the naming guidelines if you want to learn more:

https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/contribute-naming.md

**Comment by JamesCoyle** [comment]
I'd personally have the order as
- off
- multiple
- outline 
- variant

**Comment by Templarian** [comment]
Yea, just trying to keep it consistent, but some have to be in the order shown. I think `-variant` and `-outline` are probably interchangeable, but `-multiple` and `-off` are not.

- `-multiple` is a addition modifier.
- `-off` is a addition modifier.
- `-variant` is a style modifier.
- `-outline` is a style modifier.

**Comment by JamesCoyle** [comment]
I think variant should be at the end as we might have a rare case where we want a variant of an outline icon.

**Comment by Templarian** [comment]
It would be a variant of a the base icon. I don't think we will ever have an `-outline` without a non-outline. That would probably be confusing.
