### ISSUE TITLE
gesture-double-tap icon

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#2406]
Here it is
![gesture-double-tap](https://user-images.githubusercontent.com/18823939/30242867-3e9732e8-959f-11e7-8af0-ffb33850eff2.png)
[gesture-double-tap.zip](https://github.com/Templarian/MaterialDesign/files/1290018/gesture-double-tap.zip)

[(old version png)](https://user-images.githubusercontent.com/18823939/30242831-19868eaa-959e-11e7-85a5-3ad0620b1c0e.png)
[(old version svg)](https://github.com/Templarian/MaterialDesign/files/1290007/gesture-double-tap.zip)

**Comment by TheChilliPL** [comment]
Oh, and by the way, outer circle is not optimised, it has a lot of points

**Comment by TheChilliPL** [comment]
I'm optimizing right now (and moving down a little bit so it don't go beyond 2 px bounding box)

**Comment by TheChilliPL** [comment]
Alright, now optimized

**Comment by Templarian** [comment]
@TheChilliPL Thanks, we're going to be displaying point count on the new site also. Hopefully this helps as we go through existing icons and cleaning up any extra point data.

**Comment by TheChilliPL** [comment]
No problem 😄

**Comment by TheChilliPL** [comment]
@Templarian By the way, I think I'm gonna add here many icons - should I make separate issue for each or one with many icons?

**Comment by TheChilliPL** [comment]
(and if I will make "off" version of some "variant", should I name it "x-off-variant" or "x-variant-off"?)

**Comment by Templarian** [comment]
@TheChilliPL If they are just `-off` put them in the same issue. But split icons into separate issues. It makes it easier for the contribution team to give feedback and to view the tweaks/progress. 😄 

Thanks for asking!

**Comment by Templarian** [comment]
@TheChilliPL Just opened your SVG file. I don't see a difference from the current one (yours is 179 points also 😨 vs the current 80 points).

Closing the issue as I'm not sure I see any errors in the current path data.
