### ISSUE TITLE
NFC off icons

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#2407]
![nfc-off](https://user-images.githubusercontent.com/18823939/30243010-eded6dd2-95a1-11e7-84a4-6bccd9711a5a.png)
![nfc-variant-off](https://user-images.githubusercontent.com/18823939/30243103-fcc3762a-95a2-11e7-863d-c9042f8894bd.png)
[Old variant](https://user-images.githubusercontent.com/18823939/30243012-eec3a00a-95a1-11e7-995a-cbb364b1924f.png)

[nfc-off.zip (both default and variant)](https://github.com/Templarian/MaterialDesign/files/1290048/nfc-off.zip)
[Old version](https://github.com/Templarian/MaterialDesign/files/1290033/nfc-off.zip)

**Comment by Templarian** [comment]
The line needs to extend past the top/bottom to conform with the MD guidelines for the second.

**Comment by TheChilliPL** [comment]
@Templarian I told you I'm gonna add many icons 😆
I'll add more tomorrow
(By the way thanks for maintaining the best icon pack I've ever found ;) )

**Comment by TheChilliPL** [comment]
@Templarian Updated 😃

**Comment by mueller-ma** [comment]
I would also like to see an icon for "NFC searching".

**Comment by PeterShaggyNoble** [comment]
@mueller-ma, could you create a new issue for that, please, and include an example and, if possible, a use-case?

**Comment by mueller-ma** [comment]
Done: #3955

**Comment by Templarian** [comment]
Added both. 😃
