### ISSUE TITLE
Format header plus/minus

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#2408]
Last two for today
format-header-minus
![format-header-minus](https://user-images.githubusercontent.com/18823939/30243175-8411f6f0-95a4-11e7-82af-0bf29657cd59.png)
format-header-plus
![format-header-plus](https://user-images.githubusercontent.com/18823939/30243177-84e8211c-95a4-11e7-8933-051b3d2e185b.png)

[format-header-plus-minus.zip (both plus and minus)](https://github.com/Templarian/MaterialDesign/files/1290054/format-header-plus-minus.zip)

**Comment by MrGrigri** [comment]
We're trying to avoid icons with text.

**Comment by JamesCoyle** [comment]
I vote these replace header-increase and decrease.

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/format-header-increase)](https://materialdesignicons.com/icon/format-header-increase) [![](https://materialdesignicons.com/icon/format-header-decrease)](https://materialdesignicons.com/icon/format-header-decrease)
