### ISSUE TITLE
Document icons

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#241]
- [ ] file-document-seal - A document seal in upper or lower right corner
- [ ] file-document-check - A check in the corner

**Comment by Templarian** [comment]
What do you mean by a "hook" in the corner?

**Comment by matthew2402** [comment]
check-icon in the corner

**Comment by CoDEmanX** [comment]
![file-check](https://cloud.githubusercontent.com/assets/1309249/8963724/de97d19c-3621-11e5-892a-ceb49f48fb26.png) https://www.dropbox.com/s/yna01av15st8vpv/file-check.svg?dl=0

Too little space to make it better IMO:
![file-seal](https://cloud.githubusercontent.com/assets/1309249/8963725/de98f1c6-3621-11e5-8fd5-f32c984b07e0.png) https://www.dropbox.com/s/fedztswucq38763/file-seal.svg?dl=0

**Comment by Templarian** [comment]
The 2nd one looks a little off. I get what you are trying for, but not sure it works.

**Comment by CoDEmanX** [comment]
Check mark taken from account-check, which is slightly smaller (this time done in Expression Design):
![file-check expression-design](https://cloud.githubusercontent.com/assets/1309249/9635697/fc6e6a28-5197-11e5-8342-517dc8373d41.png) https://www.dropbox.com/s/tcf65b6grwak79p/file-check.design?dl=0

**Comment by Templarian** [comment]
[![file-check](https://materialdesignicons.com/icon/file-check)](https://materialdesignicons.com/icon/file-check)

**Comment by CoDEmanX** [comment]
So no more efforts for document + seal?

**Comment by Templarian** [comment]
[![seal](https://materialdesignicons.com/icon/seal)](https://materialdesignicons.com/icon/seal) ?

**Comment by CoDEmanX** [comment]
What if we took that star and subtracted it from document?

**Comment by matthew2402** [comment]
They are great. Thanks!
