### ISSUE TITLE
xbox-controller-battery-charging

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#2410]
![xbox-controller-battery-charging](https://user-images.githubusercontent.com/18823939/30247671-af76968c-9619-11e7-8e85-840c50e428f9.png)
[SVG: xbox-controller-battery-charging.zip](https://github.com/Templarian/MaterialDesign/files/1290394/xbox-controller-battery-charging.zip)

**Comment by Templarian** [comment]
[![xbox-controller-battery-charging](https://materialdesignicons.com/icon/xbox-controller-battery-charging)](https://materialdesignicons.com/icon/xbox-controller-battery-charging)
