### ISSUE TITLE
Rectangular gamepad-variant

### ISSUE THREAD

**Issue by bliemli** [Templarian/MaterialDesign#2411]
I was looking for an icon looking like a NES controller. So something like the gamepad-variant icon but in rectangular shape.

**Comment by TheChilliPL** [comment]
Almost done, I'll send it in couple of minutes

**Comment by TheChilliPL** [comment]
![nes-controller](https://user-images.githubusercontent.com/18823939/30248772-b61d0b6e-962e-11e7-8624-4a5df1d3b7a6.png)
[SVG: nes-controller.zip](https://github.com/Templarian/MaterialDesign/files/1290477/nes-controller.zip)

**Comment by TheChilliPL** [comment]
@Templarian nes-controller

**Comment by bliemli** [comment]
Wow, looks great, exactly what I was looking for! Thanks so much!

**Comment by k5cents** [comment]
Actually, Google already has this icon. It's called [videogame_asset](https://material.io/icons/#ic_videogame_asset).

![ic_videogame_asset_black_48dp_2x](https://user-images.githubusercontent.com/18021678/30251417-13c663e8-962d-11e7-8cb2-140eef43468f.png)

[ic_videogame_asset_black_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/1290752/ic_videogame_asset_black_24px.svg.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49034679-a5870f80-f180-11e8-8643-345489cf3374.png)![image](https://user-images.githubusercontent.com/1015040/49034698-addf4a80-f180-11e8-9954-9709f84aad91.png)

[gamepad-square-variant.zip](https://github.com/Templarian/MaterialDesign/files/2616883/gamepad-square-variant.zip)

**Comment by Templarian** [comment]
Added. 😃
