### ISSUE TITLE
video-classic

### ISSUE THREAD

**Issue by mikegchambers** [Templarian/MaterialDesign#2412]
![camera-film](https://user-images.githubusercontent.com/6299739/30256549-0617c67a-96ef-11e7-94fa-53beedd34e55.png)

[camera-film.svg.zip](https://github.com/Templarian/MaterialDesign/files/1291192/camera-film.svg.zip)

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/30273809-776a484a-96f2-11e7-9eb9-97f82708dee7.png)
![image](https://user-images.githubusercontent.com/15905797/30273822-8562c198-96f2-11e7-9d62-a27bc70eecae.png)
[camera-film.zip](https://github.com/Templarian/MaterialDesign/files/1292451/camera-film.zip)
It's alright. :-/

**Comment by mikegchambers** [comment]
Happy to adjust with feedback, or have adjusted.  :)

**Comment by GreenTurtwig** [comment]
Ahh, I was commenting on the SVG I attached above, it should be ready to go. :+1:

**Comment by mikegchambers** [comment]
Thanks.  So just to help me out for next time.  What was wrong with the SVG from my original post?

**Comment by MrGrigri** [comment]
It should be one compound path only. It should not just be centered visually (which yours is) but try to align points to the pixel grid. I also believe that we should use the video icon to keep it consistent. I also suggest we name it `vintage-film` or `video-vintage`. 

![camera-vintage](https://user-images.githubusercontent.com/4528551/30298876-50911678-970a-11e7-8821-9968ff71d023.png)

[camera-vintage.zip](https://github.com/Templarian/MaterialDesign/files/1294188/camera-vintage.zip)

**Comment by GreenTurtwig** [comment]
`video-classic` would probably be best, as we have a few "old" variants of a few other icons.

**Comment by mikegchambers** [comment]
Thanks.  I see the process.  Looking good.

**Comment by mikegchambers** [comment]
What happens now?  Do I need to do something? :)

**Comment by Templarian** [comment]
@mikegchambers Nope, I'll be working on the backlog this weekend. Should be in shortly.

**Comment by Templarian** [comment]
[![video-vintage](https://materialdesignicons.com/icon/video-vintage)](https://materialdesignicons.com/icon/video-vintage)

Didn't want to confuse it with camera, so renamed to `video-`
