### ISSUE TITLE
aws (Amazon Web Services)

### ISSUE THREAD

**Issue by mikegchambers** [Templarian/MaterialDesign#2413]
![aws](https://user-images.githubusercontent.com/6299739/30256768-67a0163a-96f0-11e7-8ff1-0ef49f71903a.png)

[aws.svg.zip](https://github.com/Templarian/MaterialDesign/files/1291214/aws.svg.zip)

**Comment by goyney** [comment]
The provided icon is the not the official logo of AWS.

![image](https://user-images.githubusercontent.com/1015040/49034566-550fb200-f180-11e8-9ea2-18f11cc5e071.png)
[aws.svg.zip](https://github.com/Templarian/MaterialDesign/files/2616879/aws.svg.zip)

**Comment by Templarian** [comment]
Added.
