### ISSUE TITLE
Atlassian Iconography Updates

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2414]
https://www.atlassian.com/blog/announcements/our-bold-new-brand

**Comment by PeterShaggyNoble** [comment]
I gave these a try, don't know if they turned out well enough.

[atlassian.zip](https://github.com/Templarian/MaterialDesign/files/1422495/atlassian.zip)

**Comment by Templarian** [comment]
Updated the three of these logos/brands. Thanks!

**Comment by MrGrigri** [comment]
I believe that the Atlassian logo should be added. I'll reopen this issue as this is the original.

**Comment by MrGrigri** [comment]
Atlassian Brand Logo

![atlassian](https://user-images.githubusercontent.com/4528551/32800056-9d79abd6-c936-11e7-92be-712f4da71f12.png)

![atlassian 1x](https://user-images.githubusercontent.com/4528551/32800069-a09e1c52-c936-11e7-9110-ce2adf352301.png)

[atlassian.zip](https://github.com/Templarian/MaterialDesign/files/1472244/atlassian.zip)

**Comment by Templarian** [comment]
[![atlassian](https://materialdesignicons.com/icon/atlassian)](https://materialdesignicons.com/icon/atlassian)
