### ISSUE TITLE
One way / bidirectional, return, 2 way / multi city

### ISSUE THREAD

**Issue by sukhvi** [Templarian/MaterialDesign#2416]
1. One way
2. Bidirectional , Return , 2 way
3. Multi city

**Comment by CoDEmanX** [comment]
Traffic signs for one-way are pretty different internationally. These are the German ones:

![grafik](https://user-images.githubusercontent.com/1309249/39387794-043a68da-4a7c-11e8-94c1-ed9461ea7212.png)

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
