### ISSUE TITLE
Pin Outline

### ISSUE THREAD

**Issue by DubeauJL** [Templarian/MaterialDesign#2419]
The pin icon from google but outline.

**Comment by Mihroy** [comment]
[pin-outline.zip](https://github.com/Templarian/MaterialDesign/files/1301221/pin-outline.zip)

**Comment by DubeauJL** [comment]
Thanks for the reply!

Will it be added to the font eventually?

**Comment by Templarian** [comment]
@DubeauJL Next release for the webfont won't be for a little while. These will be added shortly to the website, but for now you can use the vectors inline until they get into the webfont. 😺

**Comment by Mancerrss** [comment]
@Templarian Every when is the webfont updated btw? Also is there any mechanism or auto updater that we could use so we could make our webfont updated everytime?

**Comment by GreenTurtwig** [comment]
It's also called `keep outline` in the extended set.

**Comment by PeterShaggyNoble** [comment]
![keep outline](https://user-images.githubusercontent.com/15157491/38486723-c5db401e-3bd5-11e8-9b59-79368495982b.png)

**Comment by Templarian** [comment]
[![pin-outline](https://materialdesignicons.com/icon/pin-outline)](https://materialdesignicons.com/icon/pin-outline) [![pin-off-outline](https://materialdesignicons.com/icon/pin-off-outline)](https://materialdesignicons.com/icon/pin-off-outline)

@Mihroy Let me know when you have 5 icons and I'll create a contributor account. We're cutting down the contribution backlog a lot right now. So hopefully there won't be long gaps like this between adding contributions.
