### ISSUE TITLE
Add Ethereum / Other Crypto

### ISSUE THREAD

**Issue by kylerschin** [Templarian/MaterialDesign#2420]
Hello! I would like to request the addition of Ethereum. Thanks.

**Comment by JapanYoshi** [comment]
Ethereum has been requested and added here already under the name ``currency-eth``. https://github.com/Templarian/MaterialDesign/issues/1902

**Comment by JapanYoshi** [comment]
Ethereum has been requested and added here already under the name ``currency-eth``. https://github.com/Templarian/MaterialDesign/issues/1902
