### ISSUE TITLE
Add multiple

### ISSUE THREAD

**Issue by touhidrahman** [Templarian/MaterialDesign#2421]
A double plus icon where one 'plus sign' is shadowed behind another. This icon will help to denote add/create multiple items.

**Comment by Mihroy** [comment]
![add-multiple](https://user-images.githubusercontent.com/18070845/30455367-f1517eee-999f-11e7-9aee-cf107d2660d9.png) ![add-multiple-outline](https://user-images.githubusercontent.com/18070845/30455373-f78e8860-999f-11e7-844d-aa175265d04b.png)


[add-multiple.zip](https://github.com/Templarian/MaterialDesign/files/1304543/add-multiple.zip)

**Comment by MrGrigri** [comment]
Would `library-plus` work?

![library-plus](https://materialdesignicons.com/icon/library-plus)

**Comment by PeterShaggyNoble** [comment]
Would `plus-circle-multiple-outline` suit?

[![](https://materialdesignicons.com/icon/plus-circle-multiple-outline)](https://materialdesignicons.com/icon/plus-circle-multiple-outline)

**Comment by PeterShaggyNoble** [comment]
Closing due to a lack of response. @touhidrahman, if neither of the icons above suit your needs, let us know and we'll revisit this issue.
