### ISSUE TITLE
"Karate" icon is missing from webfont package download 2.0.46 

### ISSUE THREAD

**Issue by WhatFreshHellIsThis** [Templarian/MaterialDesign#2423]
It's not in the CSS, not sure where else it's missing.
You can see the issue at a glance here:
https://cdn.materialdesignicons.com/2.0.46/
Search for karate, it's not there.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history Looks like it was added recently. Will be in the next release, for now just use inline vector.

**Comment by WhatFreshHellIsThis** [comment]
I'm confused, why show items on the main page that are not actually representative of what can be downloaded?  That seems just plain wrong.

**Comment by Templarian** [comment]
@WhatFreshHellIsThis Not everyone uses the webfont. A lot use the SVG / Vector drawables. The new site under development right now will make this much easier as it has a version toggle. This should help people using the webfont (it will still default to showing all icons).

**Comment by WhatFreshHellIsThis** [comment]
Ok, thank you.

I think I understand now what's happening, I just assumed there was some kind of automated build process that would update the webfont download regularly and thought it was broken in some way, but it sounds like someone has to manually build it when they get around to it and it's not a high priority due to logs showing that few people download the webfont.
