### ISSUE TITLE
'bell' and 'bell-off' not consistent with other bells

### ISSUE THREAD

**Issue by vcantu** [Templarian/MaterialDesign#2424]
![Image from MDI site](https://user-images.githubusercontent.com/13156162/30468604-1405fc8e-99a1-11e7-8195-0b46a1884859.png)

Google's Icons for 'bell' and 'bell-off' are not updated on MDI, they still have the old "pointy" ends when they should have rounded ends

This is what they should look like (from the google site)
![Image from Google MD Site](https://user-images.githubusercontent.com/13156162/30468684-74549a14-99a1-11e7-9867-b53c795f57fd.png)

**Comment by Templarian** [comment]
Fixed. Thanks!
