### ISSUE TITLE
Numbers in Circles

### ISSUE THREAD

**Issue by sothea64** [Templarian/MaterialDesign#2425]
Icon for number like 1 to 9 with circle or any other design would be really helpful!! :)

**Comment by JapanYoshi** [comment]
bruh you deadass serious rn
![image](https://user-images.githubusercontent.com/8707990/30472554-57e0eb36-9a40-11e7-93cf-0c0472a89718.png)

**Comment by MrGrigri** [comment]
Although, should we have circle versions? I believe they'd be useful; notifications especially.

**Comment by MrGrigri** [comment]
So here are my contributions for the circle variants. The only one that I don't like is 9+ on the outline variant. But then again, I don't really like the 9+ for the square ones as well. 

[numeric-circle.zip](https://github.com/Templarian/MaterialDesign/files/1307646/numeric-circle.zip)

**Comment by CoDEmanX** [comment]
The margin would work much better with a rounded corner:

![image](https://user-images.githubusercontent.com/1309249/38772613-a5f32a18-403b-11e8-9baa-f90e79be5658.png)

**Comment by Templarian** [comment]
These have all been added. We're not really worry about variations now, so we've started adding a lot of variants like this.
