### ISSUE TITLE
icon request: callback

### ISSUE THREAD

**Issue by tretli** [Templarian/MaterialDesign#2426]
Wishing a phone icon that indicates callback. 

A phone with a returning arrow or similar. 

![image](https://user-images.githubusercontent.com/4906083/30480272-4a587c30-9a19-11e7-87c7-785601cef28e.png)

**Comment by MrGrigri** [comment]
I called it `phone-return`, but that is mute. 

![phone-return](https://user-images.githubusercontent.com/4528551/30498877-a2f0e494-9a15-11e7-96f4-8111ca5319d6.png)

[phone-return.zip](https://github.com/Templarian/MaterialDesign/files/1307502/phone-return.zip)

**Comment by Templarian** [comment]
[![phone-return](https://materialdesignicons.com/icon/phone-return)](https://materialdesignicons.com/icon/phone-return)
