### ISSUE TITLE
Light version of icons

### ISSUE THREAD

**Issue by alizarei95** [Templarian/MaterialDesign#2427]
Hello and thank you for this great job, we are using these icons in our android apps but in mobile phones , the icons appear strong , is there any way to use a light version of these icons?

**Comment by JapanYoshi** [comment]
Buy it.

**Comment by alizarei95** [comment]
@JapanYoshi which it?

**Comment by Templarian** [comment]
It's going to be open source, but not just yet. For now you can buy the light version (subset of the full pack, mostly just the most used)...

https://creativemarket.com/templarian/348441-Material-Design-Icons-Light

I've been building the backend to support both eventually with mapping. Eventually I'll be expanding on this icon set heavily trying to fill in all the gaps.

Compare: https://codepen.io/templarian/pen/bgQxzL
