### ISSUE TITLE
Knives

### ISSUE THREAD

**Issue by augustin32** [Templarian/MaterialDesign#2429]
Kitchen knife
![knife24](https://user-images.githubusercontent.com/14167196/30522497-7d68fcf0-9bd9-11e7-8fef-b67cd7f88a3e.png)
![knife36](https://user-images.githubusercontent.com/14167196/30522498-7d6d1bdc-9bd9-11e7-9790-8f258cffe3b5.png)
![knife48](https://user-images.githubusercontent.com/14167196/30522499-818cb75e-9bd9-11e7-8d27-89280e706964.png)
Military knife
![knife-military24](https://user-images.githubusercontent.com/14167196/30522500-819c9c82-9bd9-11e7-859d-db78069a9a62.png)
![knife-military36](https://user-images.githubusercontent.com/14167196/30522501-834f70c2-9bd9-11e7-8811-328ef184249e.png)
![knife-military48](https://user-images.githubusercontent.com/14167196/30522502-862e020e-9bd9-11e7-8eac-1230a9f049d5.png)
[knifes.zip](https://github.com/Templarian/MaterialDesign/files/1309191/knifes.zip)

**Comment by CoDEmanX** [comment]
Maybe like this?

![image](https://user-images.githubusercontent.com/1309249/38772799-5c7a9e76-403f-11e8-9fdd-8db864480dee.png)

Something is odd with the canvas sizes and scaling. Tried to correct this here:

[knives.zip](https://github.com/Templarian/MaterialDesign/files/1911188/knives.zip)

**Comment by Templarian** [comment]
[![knife](https://materialdesignicons.com/icon/knife)](https://materialdesignicons.com/icon/knife) [![knife-military](https://materialdesignicons.com/icon/knife-military)](https://materialdesignicons.com/icon/knife-military)
