### ISSUE TITLE
Become a contributor

### ISSUE THREAD

**Issue by YarmoM** [Templarian/MaterialDesign#243]
Hey,
I got some icons that I'd like to add to MDI, but the form is disabled and doesn't allow me to upload more than one icon... Is that a bug?
(Chrome 43 on Ubuntu 14.04)
- [ ] attach icons
- [ ] icons pass review
- [ ] explain the current open issues in the contributor portal
- [ ] invite email sent

**Comment by Templarian** [comment]
Nah, I have it disabled while I work on some other issues. Test them in the [custom](http://materialdesignicons.com/custom) page to make sure they are valid. Then if you could just upload them somewhere in a zip and I'll review them. Little manual of a process at the moment.

**Comment by Templarian** [comment]
Just checking in. No rush. Were you still interested in becoming a contributor?

I'm out this weekend due to the holiday, but will have time next week to process it through and get you added if you are still interested.

**Comment by YarmoM** [comment]
Thanks, and yes, I am still interested though I am pretty busy at this moment, I'll try to get back at you next week! Have a nice holiday!

**Comment by ecols33** [comment]
I would like to. Where do I send a .zip ?

**Comment by Templarian** [comment]
Create an issue and attach it (dropbox, etc...). Just attach the .svgs, make sure they work in http://materialdesignicons.com/custom
