### ISSUE TITLE
Language icon

### ISSUE THREAD

**Issue by sebastian-raubach** [Templarian/MaterialDesign#2430]
Before I start: I'm aware of this icon here: https://materialdesignicons.com/icon/translate and there's absolutely nothing wrong with that icon.

However, there seems to be a trend to use the icon provided on this website to represent languages:
http://www.languageicon.org/

That icon has been chosen in a contest to come up with a new icon to represent language.

Would it be possible to have the above icon as an alternative to the language/translate icon that's already available?

**Comment by Templarian** [comment]
The icon needs to be modified to match the Material Design guidelines and be visible at the smaller 24 pixel size (there is a bit of detail that would be lost). The MD guidelines also suggest that no icon have a perspective view.

It's a good suggestion, but wouldn't conform with the guidelines and the other icons in the pack. Thanks!
