### ISSUE TITLE
Icon request: Xamarin icon

### ISSUE THREAD

**Issue by kimdv** [Templarian/MaterialDesign#2431]
A Xamarin icon would be nice!

**Comment by augustin32** [comment]
Solid icon
![xamarin24](https://user-images.githubusercontent.com/14167196/30547748-dd7b8b66-9c98-11e7-934b-f11147228ad4.png)
![xamarin36](https://user-images.githubusercontent.com/14167196/30547754-dfc778f8-9c98-11e7-9bd8-f14b842edb12.png)
![xamarin48](https://user-images.githubusercontent.com/14167196/30547757-e0feab60-9c98-11e7-8f3c-f9c56f29f1ce.png)
Outline icon
![xamarin-outline24](https://user-images.githubusercontent.com/14167196/30547759-e29f29cc-9c98-11e7-9289-4c721ad5a83b.png)
![xamarin-outline36](https://user-images.githubusercontent.com/14167196/30547773-ebef2720-9c98-11e7-8215-0f83e491ba5d.png)
![xamarin-outline48](https://user-images.githubusercontent.com/14167196/30547764-e6030458-9c98-11e7-85dd-a08dfd19eed4.png)
[xamarin.zip](https://github.com/Templarian/MaterialDesign/files/1311043/xamarin.zip)

**Comment by kimdv** [comment]
That was fast! 

Thank you very much! 💯

**Comment by Templarian** [comment]
[![xamarin](https://materialdesignicons.com/icon/xamarin)](https://materialdesignicons.com/icon/xamarin) [![xamarin-outline](https://materialdesignicons.com/icon/xamarin-outline)](https://materialdesignicons.com/icon/xamarin-outline)
