### ISSUE TITLE
Add augustin32 as Contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2432]
https://materialdesignicons.com/contributor/Augustin-Ursu

Eventually contributors will be able to edit these pages, but for now it's a one off issue.

Twitter, Photo 100x100, Short Bio.

**Comment by Templarian** [comment]
^ @augustin32

**Comment by augustin32** [comment]
So...i need to make a bio and put a link to my twitter account in my GitHub profile?

**Comment by Templarian** [comment]
@augustin32 Just comment with a photo, twitter (optional), and short bio text (less than ~200 characters).

Use to let contributors edit this info, but I'm rewriting all the endpoints and the previous ones are all broken due to db changes.

**Comment by augustin32** [comment]
![image](https://user-images.githubusercontent.com/14167196/30772736-8d90a50c-a06a-11e7-8362-71df683ad994.png)
My name is Augustin Ursu. I was born in Moldova. I know well Photoshop and Affinity designer. I have pasion to design UI's, logos, edit photos, make icons and draw.

**Comment by Templarian** [comment]
Cool, still syncing in icons. Closing the issue as the account is setup.
