### ISSUE TITLE
Add PayPal icon

### ISSUE THREAD

**Issue by hypernova7** [Templarian/MaterialDesign#2433]
add PayPal icon `<i class="mdi mdi-paypal"></i>`

**Comment by JapanYoshi** [comment]
This has been requested a total of 9 other times, and no, it cannot be done because the PayPal company literally doesn't allow you to use a one-color version of their logo. See here: https://github.com/Templarian/MaterialDesign/issues/297

**Comment by JapanYoshi** [comment]
Please make a new request for each new icon request; even if you did, I'm willing to bet that they would be too niche and outside the scope of this project.

**Comment by hypernova7** [comment]
Ok
