### ISSUE TITLE
Battery Charging Wireless

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2434]
I'm going to be labeling these as `battery-charging-wireless-*` because I believe that it should represent a battery that is being charged wirelessly. However, if the community believes that doesn't fit, then we can discuss that. The below list represents the ones that are included in the zip file and I'm only going to show a couple of images for reference. I also believe that we should alias them with 'Qi' as the popular standard for wireless charging.

- [x] battery-charging-wireless-empty or battery-charging-wireless-outline
- [x] battery-charging-wireless-10
- [x] battery-charging-wireless-20
- [x] battery-charging-wireless-30
- [x] battery-charging-wireless-40
- [x] battery-charging-wireless-50
- [x] battery-charging-wireless-60
- [x] battery-charging-wireless-70
- [x] battery-charging-wireless-80
- [x] battery-charging-wireless-90
- [x] battery-charging-wireless-full or battery-charging-wireless-100
- [x] battery-charging-wireless-alert

![battery-charging-wireless-50](https://user-images.githubusercontent.com/4528551/30601146-765e69f4-9d1e-11e7-803e-c56edf2c24e2.png) ![battery-charging-wireless-alert](https://user-images.githubusercontent.com/4528551/30601147-76969004-9d1e-11e7-95e2-514e60a65f44.png)

[battery-wireless.zip](https://github.com/Templarian/MaterialDesign/files/1314834/battery-wireless.zip)

**Comment by Templarian** [comment]
Added! 🐱
