### ISSUE TITLE
Qi (Wireless Charging)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2435]
I'm not sure if we want to add this or not, but I'll leave this up to the community. Qi (pronounced: /tʃiː/ CHEE) is the popular standard for wireless charging. I could see this icon used to symbolize Qi Certified products on an eCommerce site. 

![qi](https://user-images.githubusercontent.com/4528551/30602084-ca9d6d88-9d20-11e7-8a4d-6fe482350429.png)

[qi.zip](https://github.com/Templarian/MaterialDesign/files/1314893/qi.zip)

**Comment by Templarian** [comment]
[![qi](https://materialdesignicons.com/icon/qi)](https://materialdesignicons.com/icon/qi)
