### ISSUE TITLE
Icon request: Ionic icons

### ISSUE THREAD

**Issue by kimdv** [Templarian/MaterialDesign#2436]
http://ionicframework.com

**Comment by MrGrigri** [comment]
Couldn't you just rotate `orbit`?

![orbit](https://materialdesignicons.com/icon/orbit)

**Comment by kimdv** [comment]
hmm, I can't see it ? 😄

**Comment by PeterShaggyNoble** [comment]
I extracted this path info from [their own SVG font](http://ionicframework.com/fonts/ionicons.svg):

    M208 284c51 0 92 -41 92 -92s-41 -92 -92 -92s-92 41 -92 92s41 92 92 92zM302 323c0 24 20 44 44 44s44 -20 44 -44s-20 -43 -44 -43s-44 19 -44 43zM397 278c12 -26 19 -55 19 -86c0 -115 -93 -208 -208 -208s-208 93 -208 208s93 208 208 208c34 0 67 -8 95 -23 c-9 -7 -16 -17 -20 -27c-23 11 -48 17 -75 17c-97 0 -175 -78 -175 -175s78 -175 175 -175s175 78 175 175c0 24 -4 46 -13 67c11 4 20 11 27 19z
