### ISSUE TITLE
Cordova

### ISSUE THREAD

**Issue by kimdv** [Templarian/MaterialDesign#2437]
https://cordova.apache.org

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/30753122-4e589106-9fb6-11e7-8d6e-d8ca48782ad7.png)
![image](https://user-images.githubusercontent.com/15905797/30753141-5e2dc286-9fb6-11e7-8dbb-d6658176a862.png)
[cordova.zip](https://github.com/Templarian/MaterialDesign/files/1325068/cordova.zip)

**Comment by kimdv** [comment]
Awesome !! 🎉🎉🎉

**Comment by Templarian** [comment]
[![cordova](https://materialdesignicons.com/icon/cordova)](https://materialdesignicons.com/icon/cordova)
