### ISSUE TITLE
Folder-open icon missing?

### ISSUE THREAD

**Issue by KlasJohnsson** [Templarian/MaterialDesign#2439]
Hi,

I cannot seem to find the folder-open icon in PackIconMaterial. I do find correspodning ones (FolderOpen) in PackIconFontAwesome and PackIconModern however. Is it missing in PackIconMaterial?

Regards,
Klas

**Comment by PeterShaggyNoble** [comment]
For anyone who may come across this issue in the future:

[![](https://materialdesignicons.com/icon/folder-open)](https://materialdesignicons.com/icon/folder-open)
