### ISSUE TITLE
Pound Currency

### ISSUE THREAD

**Issue by Chris-Aranha** [Templarian/MaterialDesign#244]
I notice you have dollar and euro currency icons. But you do not have pounds the British currency.

http://s.icons8.com/wp-content/uploads/2013/10/GBP-128.png

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/currency-cad

**Comment by Templarian** [comment]
Edited that message, accidentally typed cad, was thinking I should probably add one for their monopoly looking money.
