### ISSUE TITLE
A "Required" Icon

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2440]
I needed a "required" icons for form field.  Also designed this to look good a smaller pixel sizes as well (ie 12px)

![required-circle12](https://user-images.githubusercontent.com/20706106/30652671-fd29a3bc-9df6-11e7-8c63-02c08d737e82.png)

![required-circle16](https://user-images.githubusercontent.com/20706106/30652673-fe7a62c4-9df6-11e7-947b-05565ef77c79.png)

![required-circle32](https://user-images.githubusercontent.com/20706106/30652675-fff3f5a2-9df6-11e7-975b-bd2e2f3867ac.png)

![required-circle48](https://user-images.githubusercontent.com/20706106/30652678-017d9acc-9df7-11e7-9894-79bbf3236bc4.png)

[required-circle.zip](https://github.com/Templarian/MaterialDesign/files/1318281/required-circle.zip)

**Comment by MrGrigri** [comment]
We are trying to stay away from letters unless they are recognizable in all languages. Do you have any other suggestions as to what symbolizes `required`

**Comment by MrGrigri** [comment]
Typically the `asterisk` icon is used. 

![asterisk](https://materialdesignicons.com/icon/asterisk)

**Comment by JamesCoyle** [comment]
Personally I'd mark any fields that are optional with a text label.

**Comment by Templarian** [comment]
I think asterisk is usually the symbol used (even if isn't an icon). Closing this issue as I think it's a standard representation of required.

**Comment by OctoberJemini** [comment]
Completely understand that language conflict, but I had a very specific need for system that required an R in a red circle.  Thanks
