### ISSUE TITLE
Icon request: handicap icon

### ISSUE THREAD

**Issue by Lamba92** [Templarian/MaterialDesign#2441]
Well, the title is self explaining

**Comment by Lamba92** [comment]
There is already one in the Google Material Library called ic_accessible_black

**Comment by MrGrigri** [comment]
Just as a reference here, the icon is called `wheelchair-accessibility`. This icon differs from Material Design Icons, and for a good reason. [The Accessible Icon Project](http://accessibleicon.org/) was created to demonstrate a more positive and active individual.

![wheelchair-accessibility](https://materialdesignicons.com/icon/wheelchair-accessibility)
