### ISSUE TITLE
Update 'format-page-break' icon

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2443]
Google has updated their 'Page break' icon today in Google Docs. 

![format-page-break](https://materialdesignicons.com/icon/format-page-break)

![image](https://user-images.githubusercontent.com/4528551/30709234-cee4d7d8-9ebe-11e7-8237-6e9c32c58f02.png)

**Comment by k5cents** [comment]
It actually looks like a lot of the icons on slides, sheets, and docs were changed/fixed to match MD guidelines. In generally they all seem... thicker?

**Comment by MrGrigri** [comment]
Yeah, I caught them in the middle of an update. I opened one document this morning and then another a little while later. The later had the update and the former did not.

**Comment by GreenTurtwig** [comment]
Should probably have a look through the UI and check for any changes/additions. Noticed a few so far, one for `reset-image` and an official Google Keep icon for example.

**Comment by GreenTurtwig** [comment]
All icons are in one sprite sheet here: https://ssl.gstatic.com/docs/common/material_common_sprite27.svg

**Comment by MrGrigri** [comment]
So looking at their image, it's only 14 X 16 pixels. We could make one that is larger and looks better IMO. I'll show all three here.

3 Dashes

![format-page-break 4 dash](https://user-images.githubusercontent.com/4528551/30714104-e4dafa30-9ece-11e7-9cf3-5c907607e755.png)

4 Dashes

![format-page-break 4 dash _1](https://user-images.githubusercontent.com/4528551/30714105-e4dc732e-9ece-11e7-8292-1f60a58beac6.png)

Google Original

![page-break](https://user-images.githubusercontent.com/4528551/30714106-e4dcd756-9ece-11e7-84ed-7395ebe6ac03.png)

**Comment by GreenTurtwig** [comment]
Yeah, I agree with giving it a resize. Should keep it more inline with the other `file` icons.

**Comment by CoDEmanX** [comment]
4 dashes looks great!

**Comment by Templarian** [comment]
[![format-page-break](https://materialdesignicons.com/icon/format-page-break)](https://materialdesignicons.com/icon/format-page-break)

**Comment by Templarian** [comment]
It's basically the Google icon. I think we could argue, but it's same derived icon. Prefer the 4 even dots than 3.

**Comment by CoDEmanX** [comment]
4 dashes is quite different from Google's version though, also the overall proportions.
