### ISSUE TITLE
Power socket Australia

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2444]
![image](https://user-images.githubusercontent.com/15905797/30710057-35a9d99a-9efc-11e7-9096-27db8607d602.png)
![image](https://user-images.githubusercontent.com/15905797/30710077-41ebccf4-9efc-11e7-97ff-49f39ce930e8.png)
[power-socket-au.zip](https://github.com/Templarian/MaterialDesign/files/1322230/power-socket-au.zip)

Named `power-socket-au`, but this type of socket is also used in New Zealand, China, Argentina, e.t.c.

**Comment by JamesCoyle** [comment]
Should alias these with their official type names and maybe the other major regions.

**Comment by GreenTurtwig** [comment]
The IEC has names and more info here: http://www.iec.ch/worldplugs

**Comment by PeterShaggyNoble** [comment]
Personally, I think we'd be better renaming them with their official names and adding aliases for various regions as necessary.

**Comment by GreenTurtwig** [comment]
They're not "official" per-se, just the letters the IEC have given them. But yeah, we should change the names as some regions use the same socket.

**Comment by Templarian** [comment]
I'll rename them for this next release and add this new one.

**Comment by Templarian** [comment]
[![power-socket-au](https://materialdesignicons.com/icon/power-socket-au)](https://materialdesignicons.com/icon/power-socket-au)

**Comment by angelofan** [comment]
![image](https://user-images.githubusercontent.com/20255750/86304277-feface80-bc40-11ea-8e2b-4eb98ccf5fe4.png)

https://www.iec.ch/worldplugs/typeL.htm
