### ISSUE TITLE
TV remote / Remote variant

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2445]
Needed a more specific remote icon for TVs, so cooked this up real quick. Should probably be given the name `remote-variant`.
![image](https://user-images.githubusercontent.com/15905797/30710298-04afc2ea-9efd-11e7-838f-8c30482ac093.png)
![image](https://user-images.githubusercontent.com/15905797/30710303-0b26229a-9efd-11e7-9891-eca1069c9174.png)
[remote-tv.zip](https://github.com/Templarian/MaterialDesign/files/1322243/remote-tv.zip)

**Comment by Templarian** [comment]
[![remote-tv](https://materialdesignicons.com/icon/remote-tv)](https://materialdesignicons.com/icon/remote-tv)
