### ISSUE TITLE
YouTube TV

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2446]
I'd love a YouTube TV icon. 

This is the latest icon they've been using
![yttv](https://user-images.githubusercontent.com/18021678/30718939-bbc0f6e2-9eef-11e7-8d42-856d4497f2fb.png)

This is their old icon
![yttv_og](https://user-images.githubusercontent.com/18021678/30718940-bbca9bc0-9eef-11e7-979c-c1eaefcd6258.jpg)

Here's what it looks like in the YouTube menu.
![yttv_menu](https://user-images.githubusercontent.com/18021678/30718967-ceda0e26-9eef-11e7-928d-079b4186844f.png)

I might even prefer a simple `television` with `play` inside.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/30750316-0e49a94a-9fae-11e7-88bf-41f93d95964b.png)
![image](https://user-images.githubusercontent.com/15905797/30750324-17523ee4-9fae-11e7-97d8-b8b765dafc8b.png)

![image](https://user-images.githubusercontent.com/15905797/30750346-292729f4-9fae-11e7-9282-03b85b140232.png)
![image](https://user-images.githubusercontent.com/15905797/30750355-304dc6f2-9fae-11e7-972b-716576e686ba.png)
[television-play-pause.zip](https://github.com/Templarian/MaterialDesign/files/1324916/television-play-pause.zip)

**Comment by MrGrigri** [comment]
@GreenTurtwig, those are great, but this request is a brand icon. You should put those in a new request with all of the variants; 'stop', 'fast forward', etc.

**Comment by k5cents** [comment]
I actually like the `television-play` one as and icon _for_ YouTube TV. It's not technically a brand icon, but fits more closely with the other MD icons. I think I'll use that one, but still think we should add Google's version to the repo as the official YT TV icon.

**Comment by GreenTurtwig** [comment]
We don't have YouTube TV or Red over here in the UK, so I can't grab the SVGs from the site. Would be handy if someone who has access could post them. :+1:

**Comment by k5cents** [comment]
I can't seem to find the icon anywhere on the YouTube or YouTube TV websites. But, here's the .png they use in the YouTube .apk file. Not incredibly useful, I know. 

![ic_youtube_u](https://user-images.githubusercontent.com/18021678/30752661-fb4edffe-9f8a-11e7-929f-4b817d1dc2f4.png)

**Comment by GreenTurtwig** [comment]
You should be able to open the menu, right click the icon and select "Inspect" in Chrome.

**Comment by k5cents** [comment]
The "YouTube" menu I reference in my original post is in the Android App. 

This is the menu of the website. I don't see the YouTube TV icon anywhere.

![screenshot 2017-09-22 at 11 49 42 am](https://user-images.githubusercontent.com/18021678/30753056-3587781a-9f8c-11e7-8c13-d6960dddb68a.png)

![screenshot 2017-09-22 at 11 51 36 am](https://user-images.githubusercontent.com/18021678/30753146-7697bb58-9f8c-11e7-9516-28768d0ad0fd.png)

**Comment by GreenTurtwig** [comment]
Ahh, my mistake. The first screenshot looked like it was from the web. Has a slightly similar layout. :-S

**Comment by PeterShaggyNoble** [comment]
I found an SVG of the current icon and tried to edit it myself; not sure how optimal it is so here are a few versions that someone more capable than I may be able to work with.

- [Original from YouTube](https://petershaggynoble.github.io/MDI-Sandbox/svg/original/youtube-tv.svg)
- [Edited to knock the play icon out of the screen](https://petershaggynoble.github.io/MDI-Sandbox/svg/edited/youtube-tv.svg)
- [Optimised with SVGOMG](https://petershaggynoble.github.io/MDI-Sandbox/svg/optimised/youtube-tv.svg)

**Comment by Templarian** [comment]
[![youtube-tv](https://materialdesignicons.com/icon/youtube-tv)](https://materialdesignicons.com/icon/youtube-tv)
