### ISSUE TITLE
Restaurant

### ISSUE THREAD

**Issue by renzobianchi** [Templarian/MaterialDesign#2447]
It would be great more icons related to restaurants, cooking, chef, etc.

**Comment by MrGrigri** [comment]
Could you please provide some examples of what you are looking for?

**Comment by renzobianchi** [comment]
Something like these:

<img width="148" alt="restaurant_location" src="https://user-images.githubusercontent.com/8013787/30754309-9f898b52-9f98-11e7-9c7a-7ad5f2184f25.png">
<img width="128" alt="delivery_2" src="https://user-images.githubusercontent.com/8013787/30754310-9f900b3a-9f98-11e7-8e5c-63b7dc9b00ab.png">
<img width="145" alt="delivery_1" src="https://user-images.githubusercontent.com/8013787/30754311-9f91fff8-9f98-11e7-858d-8004d6d4c077.png">
<img width="124" alt="cooking" src="https://user-images.githubusercontent.com/8013787/30754312-9f9386ac-9f98-11e7-88d3-fbb6ac9f186a.png">

**Comment by PeterShaggyNoble** [comment]
`motorbike` & `pot` already exist. `waiter` is being tracked in #1813 and `chef` in #659.

Leaving this open for now as a request for a restaurant icon (although one of the `silverware` icons should cover it). @renzobianchi, if you're in need of any icons beyond that, please open a new issue for each one.

**Comment by goyney** [comment]
So, we have... `moped`, `motorbike`, `room-server(-outline)`, `chef-hat`, `silverware` (and several variants), and  `table-chair`. I think something ought to work for a restaurant there. 😄
