### ISSUE TITLE
Certificate options

### ISSUE THREAD

**Issue by kaurkaur** [Templarian/MaterialDesign#2449]
Please add certificate options.
Examples:
certificate-add/certificate-new/certificate-create
certificate-remove
certificate-withdraw

thanks

**Comment by kaurkaur** [comment]
certificate-remove/certificate-off
![image](https://pp.userapi.com/c840734/v840734358/9b01/kH4iVCdvTZ8.jpg)

**Comment by JamesCoyle** [comment]
We can't add modifiers to every icon in the pack. You're better off creating a specific UI that deals only with certificates and then use the plus/minus/delete icons within that context.

**Comment by gabrielgrant** [comment]
@JamesCoyle agreed in general that for a certificate add/remove UI, simple add/remove buttons should be used. But I imagine this icon is also used for SSL certificates, where having a "no certificate" icon would be very relevant (no idea if that's anything to do with the context of the original request, though)
