### ISSUE TITLE
Add overlay on font (i.e. plus sign)

### ISSUE THREAD

**Issue by lulumetro** [Templarian/MaterialDesign#245]
Hi, the truth is that I don´t know if it´s possible what I asking for, (in fact I think it´s not possible, but asking is for free :) ) but it would be great if there was a way  to set an overlay to each icon when using the font, more specifically something related to CRUD actions, that is, if I choose an icon for an entity in my web (i.e the briefcase icon), it would be great a way to programmatically set the plus and minus sign over the icon to represent the add and delete operations, instead of having to create new icons and refactoring the font... what do you think? I need to go to bed perhaps? :z: 

Great job anyway and many thanks for your time! :+1:

**Comment by Templarian** [comment]
You could just add a small SVG plus symbol next to any of the icons. Overlaying a plus symbol wouldn't work for all the icons. Sometimes it might even mess with the original meaning.

I actually have a rule no plus / minus overlay unless they make sense (or every icon would have one).

![plus](https://cloud.githubusercontent.com/assets/338885/6883746/33aeeb14-d58a-11e4-8795-12638f72d9e1.png)

**Comment by lulumetro** [comment]
Hi, many thanks for your answer, I'm actually more a backend guy than a frontend one, could you provide some code on how to achieve that result? I have no experience working with SVGs, but it looks promising!
Many thanks again!

**Comment by Templarian** [comment]
I didn't test it, but something basic like (you may have to `vertical-align:middle;` it, not sure):

```html
<i class="mdi mdi-bell"></i><svg width="10" height="24" viewBox="0 0 10 24"><path fill="#000000" d="M9,11H6V8H4V11H1V13H4V16H6V13H9V11Z "/></svg>
```
