### ISSUE TITLE
Can you add a set of stopwatch icons?

### ISSUE THREAD

**Issue by hlaurent** [Templarian/MaterialDesign#2450]

**Comment by MrGrigri** [comment]
Could you please be more specific and add a couple of examples?

**Comment by hlaurent** [comment]
Hi,

Something like the attached one.

Thanks

2017-09-22 16:53 GMT+02:00 Michael Richins <notifications@github.com>:

**Comment by MrGrigri** [comment]
I don't see any attached icons

**Comment by PeterShaggyNoble** [comment]
Do `timer` and `timer-off` suit your needs?

[![](https://materialdesignicons.com/icon/timer)](https://materialdesignicons.com/icon/timer) [![](https://materialdesignicons.com/icon/timer-off)](https://materialdesignicons.com/icon/timer-off)

**Comment by hlaurent** [comment]
Perfect!!

Thanks a lot.

Henri

2017-10-05 17:29 GMT+02:00 Peter Noble <notifications@github.com>:
