### ISSUE TITLE
television-pause

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2453]
https://github.com/Templarian/MaterialDesign/issues/2446 Separated issue.

![image](https://user-images.githubusercontent.com/15905797/30750316-0e49a94a-9fae-11e7-88bf-41f93d95964b.png)
![image](https://user-images.githubusercontent.com/15905797/30750324-17523ee4-9fae-11e7-97d8-b8b765dafc8b.png)

![image](https://user-images.githubusercontent.com/15905797/30750346-292729f4-9fae-11e7-9282-03b85b140232.png)
![image](https://user-images.githubusercontent.com/15905797/30750355-304dc6f2-9fae-11e7-972b-716576e686ba.png)
[television-play-pause.zip](https://github.com/Templarian/MaterialDesign/files/1324916/television-play-pause.zip)

**Comment by Templarian** [comment]
[![television-pause](https://materialdesignicons.com/icon/television-pause)](https://materialdesignicons.com/icon/television-pause) [![television-stop](https://materialdesignicons.com/icon/television-stop)](https://materialdesignicons.com/icon/television-stop)
