### ISSUE TITLE
Football Club, Football Team, Sports Team

### ISSUE THREAD

**Issue by ziyafenn** [Templarian/MaterialDesign#2455]
Hi guys! Would be great to have an icon representing a sports team. I see it like a badge/shield in a sports logo shapes i would say. 

Thanks in advance!

**Comment by GreenTurtwig** [comment]
Would a t-shirt do for you?
[![](https://materialdesignicons.com/icon/tshirt-crew)](https://materialdesignicons.com/icon/tshirt-crew)

We also have a football pitch if it would come in handy :cat2::
[![](https://materialdesignicons.com/icon/soccer-field)](https://materialdesignicons.com/icon/soccer-field)

**Comment by ziyafenn** [comment]
I actually thought using football pitch as an alternative. But t-shirt it's also great! Thanks, i'll use it as long as there nothing better. Cheers!

**Comment by MrGrigri** [comment]
There is also `football-helmet`.

![football-helmet](https://materialdesignicons.com/icon/football-helmet)

**Comment by PeterShaggyNoble** [comment]
@ziyafenn, what "flavour" of football are you referring to? As demonstrated here, the word means different things to different people; soccer to @GreenTurtwig, American Football to @MrGrigri and, to me, it's rugby (or gaelic, depending on context).

**Comment by PeterShaggyNoble** [comment]
Going to close this one out.

@ziyafenn, if you come up with another way to represent this in an icon, please comment with an example and we'll re-open the issue.
