### ISSUE TITLE
fan control icons

### ISSUE THREAD

**Issue by finity69x2** [Templarian/MaterialDesign#2457]
Nice to have some fan control icons.

Most fans have 3 speeds and an off state.

Maybe a small, medium & large fan icon. Or thin thru thick fan blades. For off it could be a fan icon with a slash thru it.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/30867716-a3de761a-a2d4-11e7-84d4-761ec661388f.png)
![image](https://user-images.githubusercontent.com/15905797/30867729-ab6c5f78-a2d4-11e7-8736-dd8f01f56c5e.png)
[fan-off.zip](https://github.com/Templarian/MaterialDesign/files/1333652/fan-off.zip)

**Comment by finity69x2** [comment]
Thanks! worked perfectly.

**Comment by Templarian** [comment]
[![fan-off](https://materialdesignicons.com/icon/fan-off)](https://materialdesignicons.com/icon/fan-off)

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33170108-f8ce4d7a-d03e-11e7-9d9d-920e49cfdea5.png)](https://github.com/Templarian/MaterialDesign/files/1498821/fan-speed-down.zip)
[![](https://user-images.githubusercontent.com/15905797/33170159-2f4fd9a4-d03f-11e7-89a4-6603862f7c20.png)](https://github.com/Templarian/MaterialDesign/files/1498822/fan-speed-up.zip)

**Comment by PeterShaggyNoble** [comment]
Should the fan in those not match the existing `fan` icon?

[![fan](https://user-images.githubusercontent.com/15157491/33170851-cb180f1c-d041-11e7-86af-9d0b2c411b73.png)](https://materialdesignicons.com/icon/fan)

**Comment by GreenTurtwig** [comment]
As in turned 45° to the left to match the position of the regular icon? Perhaps.

**Comment by PeterShaggyNoble** [comment]
And also the "hole" in the middle.

I think rotating the on in `speed-down` 45deg counter-clockwise and the other 45deg clockwise might help communicate the icons' intent.

**Comment by JamesCoyle** [comment]
I think a full arrow would look better and would better match existing variants.

**Comment by goyney** [comment]
We should probably follow the `thermometer` variants:

![image](https://user-images.githubusercontent.com/1015040/62828940-74d8f000-bbc0-11e9-92bc-067439ea0c87.png)![image](https://user-images.githubusercontent.com/1015040/62828944-7bfffe00-bbc0-11e9-949b-88991bb747e5.png)
![image](https://user-images.githubusercontent.com/1015040/62828947-83270c00-bbc0-11e9-86e9-86f3beaeabea.png)![image](https://user-images.githubusercontent.com/1015040/62828952-8a4e1a00-bbc0-11e9-81c7-951cbb72d073.png)
![image](https://user-images.githubusercontent.com/1015040/62828955-91752800-bbc0-11e9-932e-bcc13c33b4c4.png)

[fans.zip](https://github.com/Templarian/MaterialDesign/files/3489484/fans.zip)

**Comment by bmsec** [comment]
Fan running and fan speed icons
[fan-icons.svg.zip](https://github.com/Templarian/MaterialDesign/files/4266653/fan-icons.svg.zip)

**Comment by goyney** [comment]
[![fan-chevron-up](https://materialdesignicons.com/icon/fan-chevron-up)](https://materialdesignicons.com/icon/fan-chevron-up)[![fan-chevron-down](https://materialdesignicons.com/icon/fan-chevron-down)](https://materialdesignicons.com/icon/fan-chevron-down)
[![fan-plus](https://materialdesignicons.com/icon/fan-plus)](https://materialdesignicons.com/icon/fan-plus)[![fan-minus](https://materialdesignicons.com/icon/fan-minus)](https://materialdesignicons.com/icon/fan-minus)
[![fan-remove](https://materialdesignicons.com/icon/fan-remove)](https://materialdesignicons.com/icon/fan-remove)[![fan-alert](https://materialdesignicons.com/icon/fan-alert)](https://materialdesignicons.com/icon/fan-alert)
[![fan-speed-1](https://materialdesignicons.com/icon/fan-speed-1)](https://materialdesignicons.com/icon/fan-speed-1)[![fan-speed-2](https://materialdesignicons.com/icon/fan-speed-2)](https://materialdesignicons.com/icon/fan-speed-2)
[![fan-speed-3](https://materialdesignicons.com/icon/fan-speed-3)](https://materialdesignicons.com/icon/fan-speed-3)

**Comment by bednim** [comment]
hi - sorry to revive old thread - could I please ask for fan 4-5-6? Aircons and whole home ventilation units got so many fan steps...

thank you kindly!
