### ISSUE TITLE
Triangle Warning Sign

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#2458]
My flight itinerary contained this diagram.

![image](https://user-images.githubusercontent.com/8707990/30797647-1a5b2e3e-a21a-11e7-8145-85ef9367d921.png)

I tried to recreate this to make a simplified/condensed itinerary for myself. I used ``briefcase`` for luggage drop, ``walk`` for boarding gate, and ``airplane-takeoff`` for takeoff, but I couldn't find a triangular sign icon. I decided to use ``close-octagon`` for this purpose, but I think a triangular exclamation point sign would be a common icon and it should definitely be included in MDI.

**Comment by GreenTurtwig** [comment]
We have them already. :-P
https://materialdesignicons.com/icon/alert
https://materialdesignicons.com/icon/alert-outline

**Comment by JapanYoshi** [comment]
Welp, I was searching for "triangle", "sign", and "warning". ¯\\\_(ツ)\_/¯

**Comment by JamesCoyle** [comment]
Alias with warning if we haven't already requested it. I'm sure I've come across this issue like 5 times at this point myself. :P

**Comment by PeterShaggyNoble** [comment]
Suggest aliasing all `alert-*` icons as `warning-*` as well as all `*-alert` icons as `*-warning`.

**Comment by PeterShaggyNoble** [comment]
The aliases above have all been added.
