### ISSUE TITLE
Request: 'compass arrow'

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#2459]
Hi all,

Thanks for your great contributions to the world of web & design! :D
I am looking for something like this: https://github.com/amitjakhu/dripicons/blob/master/SVG/direction.svg
Or in words: an icon that indicates the direction of travel or compass north in a navigation app.

Would be great if this could be included in the Material Dasign Icons suite :)

**Comment by GreenTurtwig** [comment]
[![https://materialdesignicons.com/icon/navigation](https://materialdesignicons.com/icon/navigation)](https://materialdesignicons.com/icon/navigation)

We should give this an alias.

**Comment by keunes** [comment]
Oh, great, thanks 👍 
I think I searched for arrow and compass, if with those words it would show up, that'd be great I think.

**Comment by JamesCoyle** [comment]
Knew we had it somewhere...

**Comment by GreenTurtwig** [comment]
Given the alias `arrow-compass`.
