### ISSUE TITLE
Alternative Sort Icons

### ISSUE THREAD

**Issue by jaxatto** [Templarian/MaterialDesign#2460]
The sort icons available aren't very legible at small sizes.

Available sort icons:
![screen shot 2017-09-25 at 11 53 02 am](https://user-images.githubusercontent.com/6673768/30820691-4e15f79a-a1e8-11e7-8db7-8b1c1319722a.png)

Our design is using these 3 icons from Font Awesome, but we don't really want to include the library just for this. We're going to use some SVG or CSS alternative for now, but it'd be really nice to have these icons in MDI.

![screen shot 2017-09-25 at 11 53 58 am](https://user-images.githubusercontent.com/6673768/30820721-648a981e-a1e8-11e7-833d-73ed07e27b58.png)
![screen shot 2017-09-25 at 11 53 19 am](https://user-images.githubusercontent.com/6673768/30820727-68a0b76c-a1e8-11e7-9292-660b75b8e2cd.png)
![screen shot 2017-09-25 at 11 53 23 am](https://user-images.githubusercontent.com/6673768/30820729-68c9a9f6-a1e8-11e7-934d-58b62eecc072.png)
![screen shot 2017-09-25 at 11 53 26 am](https://user-images.githubusercontent.com/6673768/30820728-68b5cc06-a1e8-11e7-90bb-b939ca63dd18.png)

These are fairly similar to the menu icons, we just need an up/down together?

![screen shot 2017-09-25 at 11 55 37 am](https://user-images.githubusercontent.com/6673768/30820760-82e24b90-a1e8-11e7-9eb3-851c3da0362c.png)

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/30872822-43d74daa-a2e3-11e7-84c0-82fd3794f109.png)
![image](https://user-images.githubusercontent.com/15905797/30872833-4e617ba6-a2e3-11e7-8ece-22989b145e7d.png)
[menu-swap.zip](https://github.com/Templarian/MaterialDesign/files/1334029/menu-swap.zip)

![image](https://user-images.githubusercontent.com/15905797/30872880-6c3c97f0-a2e3-11e7-9d8a-fdabfeae0408.png)
![image](https://user-images.githubusercontent.com/15905797/30872886-7363a546-a2e3-11e7-9400-9045887ac4d2.png)
[menu-swap-outline.zip](https://github.com/Templarian/MaterialDesign/files/1334032/menu-swap-outline.zip)

**Comment by JamesCoyle** [comment]
Alias menu icons with arrow?

**Comment by jacquelynchastain** [comment]
@GreenTurtwig's response is great. How do we go about getting this into the library?

**Comment by jaxatto** [comment]
Any movement on this?

**Comment by PeterShaggyNoble** [comment]
@JamesCoyle: done as part of adding aliases for all the stock names.

**Comment by Templarian** [comment]
We just finalized the 2.1.19 release yesterday that will be going out. So, this will make it into the next release, going to try and make this next one quicker.

**Comment by Templarian** [comment]
[![menu-swap](https://materialdesignicons.com/icon/menu-swap)](https://materialdesignicons.com/icon/menu-swap) [![menu-swap-outline](https://materialdesignicons.com/icon/menu-swap-outline)](https://materialdesignicons.com/icon/menu-swap-outline)

Eventually after several switched milestones we do add icons. Sorry about that.
