### ISSUE TITLE
Pickaxe

### ISSUE THREAD

**Issue by mencargo** [Templarian/MaterialDesign#2461]
More manual labor icons, like pickaxe, shovel-pickaxe cross, ...

**Comment by MrGrigri** [comment]
Here is my attempt at a pickaxe.

![pickaxe](https://user-images.githubusercontent.com/4528551/30874770-8ff6b73c-a2ae-11e7-8a32-8b08045c658e.png)

[pickaxe.zip](https://github.com/Templarian/MaterialDesign/files/1334167/pickaxe.zip)

**Comment by JapanYoshi** [comment]
The part at the intersection could be vastly simplified.

**Comment by MrGrigri** [comment]
I did try that, but it didn't look like a pickaxe. Giving it weight in the intersection helped a lot.

**Comment by JamesCoyle** [comment]
Have you tried getting rid of the larger square on the top and just having a 1dp extension of the shaft. Then underneath have a more tapered design.

Something more like this:

![image](https://user-images.githubusercontent.com/10384436/30975807-17dd89e2-a46b-11e7-84f7-523a97b74eaa.png)

**Comment by mark-monserrat** [comment]
I'm not confident with this one, but I want to give a try 🤣 🤣 🤣 
![pickaxe-preview](https://user-images.githubusercontent.com/8490508/30990027-5db2b4bc-a4d2-11e7-8b95-01cce4230db9.png)
[pickaxe.svg.zip](https://github.com/Templarian/MaterialDesign/files/1342319/pickaxe.svg.zip)

**Comment by Templarian** [comment]
[![pickaxe](https://materialdesignicons.com/icon/pickaxe)](https://materialdesignicons.com/icon/pickaxe)
