### ISSUE TITLE
Office Building

### ISSUE THREAD

**Issue by mencargo** [Templarian/MaterialDesign#2462]
Icons for tall buildings, office, variants of mdi-domain

**Comment by GreenTurtwig** [comment]
Could you give us some examples?

**Comment by MrGrigri** [comment]
We do have `domain` which has aliases of building and company. Does this work?

![domain](https://materialdesignicons.com/icon/domain)

**Comment by mencargo** [comment]
Hey @MrGrigri, my post states that I'm aware of that icon (mdi-domain), I'm requesting some variants, similar to: (@GreenTurtwig)
http://fontawesome.io/icon/building/
http://fontawesome.io/icon/building-o/

The current mdi-domain doesn't seem "clear" enough in my opinion, so I'm asking for some variants.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/30873703-0c8e6862-a2e6-11e7-9f87-214d880f66c5.png)
![image](https://user-images.githubusercontent.com/15905797/30873724-183ab594-a2e6-11e7-8430-bd10df3ad772.png)
[office.zip](https://github.com/Templarian/MaterialDesign/files/1334078/office.zip)

![image](https://user-images.githubusercontent.com/15905797/30873764-35b18f4e-a2e6-11e7-97dc-df0ebe5260b6.png)
![image](https://user-images.githubusercontent.com/15905797/30873779-40d002c0-a2e6-11e7-9b22-f8c8612c0287.png)
[office2.zip](https://github.com/Templarian/MaterialDesign/files/1334079/office2.zip)

I think I prefer the door size on the second one.

**Comment by MrGrigri** [comment]
I prefer the second one.

**Comment by Templarian** [comment]
[![office-building](https://materialdesignicons.com/icon/office-building)](https://materialdesignicons.com/icon/office-building)
