### ISSUE TITLE
Sensor

### ISSUE THREAD

**Issue by RobSenix** [Templarian/MaterialDesign#2464]

**Comment by MrGrigri** [comment]
What kind of sensor are you looking for? Some can be accomplished with `access-point`, `radio-tower`, or even `gauge`

![access-point](https://materialdesignicons.com/icon/access-point) ![radio-tower](https://materialdesignicons.com/icon/radio-tower) ![gauge](https://materialdesignicons.com/icon/gauge)

**Comment by MrGrigri** [comment]
Material Design tends to be a little more abstract with its icons.

**Comment by RobSenix** [comment]
This would be for something like a proximity sensor.  I'm using the "remote" icon now.  Something similar with the radiating pattern pointing down would work.

**Comment by MrGrigri** [comment]
Do you have any suggestions?

**Comment by k5cents** [comment]
I think he's looking for something as simple as this:

![sensor](https://user-images.githubusercontent.com/18021678/30942867-5b83cf90-a3bb-11e7-8173-552cfd5c5e5e.png)

**Comment by PeterShaggyNoble** [comment]
Would the `radar` icon suit your needs, maybe?

[![](https://materialdesignicons.com/icon/radar)](https://materialdesignicons.com/icon/radar)

**Comment by LinuxLover9** [comment]
The k5cents suggestion would be appropriate.

**Comment by PeterShaggyNoble** [comment]
@LinuxLover9, try the `remote` icon:

[![](https://materialdesignicons.com/icon/remote)](https://materialdesignicons.com/icon/remote)

**Comment by k5cents** [comment]
The problem with `remote` is the waves emanate from the device rather than being read *by* the device, as would happen with a sensor. A simple flip of the waves would give a whole new meaning to the icon.

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. See also #1016 and #2499.
