### ISSUE TITLE
Theme Park (Ferris Wheel)

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#2465]
Could be symbolised by a ferris wheel or a roller coaster.

**Comment by augustin32** [comment]
Ferris Wheel
![ferris-wheel24](https://user-images.githubusercontent.com/14167196/30978735-1edbac06-a484-11e7-83fb-404807b8369d.png)
![ferris-wheel36](https://user-images.githubusercontent.com/14167196/30978740-21f252be-a484-11e7-8252-baf44fca25ed.png)
![ferris-wheel48](https://user-images.githubusercontent.com/14167196/30978743-22f740b6-a484-11e7-873b-5b2830e034af.png)
[ferris-wheel.zip](https://github.com/Templarian/MaterialDesign/files/1341640/ferris-wheel.zip)

**Comment by mark-monserrat** [comment]
how about a carousel :)
![theme-park-preview](https://user-images.githubusercontent.com/8490508/30989191-67f8c504-a4cf-11e7-8400-6f824046be2a.png)
[theme-park.svg.zip](https://github.com/Templarian/MaterialDesign/files/1342251/theme-park.svg.zip)

**Comment by MrGrigri** [comment]
@mark-monserrat, I believe that is too detailed for MD.

**Comment by JamesCoyle** [comment]
Looks ok except for the cover which is using perspective. Needs to be a flat design.

**Comment by derwaldgeist** [comment]
Thanks for your suggestions. I‘d say the carousel is cool in itself, but I wouldn’t associate it with a theme park.

**Comment by MrGrigri** [comment]
I just found this in the newly redesigned Google Maps. I couldn't find an SVG so I had to recreate it.

![image](https://user-images.githubusercontent.com/4528551/41950307-c0b5ae2c-7982-11e8-8a0a-a8472eff2ecc.png)

[ferris-wheel.zip](https://github.com/Templarian/MaterialDesign/files/2139647/ferris-wheel.zip)

**Comment by Templarian** [comment]
[![ferris-wheel](https://materialdesignicons.com/icon/ferris-wheel)](https://materialdesignicons.com/icon/ferris-wheel)

Slightly tweaked the stock one. The cut outs are not common and looked a bit off.
