### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by MigliS** [Templarian/MaterialDesign#2467]
Following icon requests:
- Postfix
- Spamassassin
- Dovecot
- Amavis
- Clamav

**Comment by JapanYoshi** [comment]
I have never heard of any of those proper nouns. Closing as too niche.

**Comment by MigliS** [comment]
Excuse me, but this can't be :)
Maybe first check what it is before closing my issue.

Thanks alot.

**Comment by JamesCoyle** [comment]
They are way too niche...

**Comment by PeterShaggyNoble** [comment]
> Maybe first check what it is before closing my issue.
That's the problem, @MigliS, we have to check what they are.

To elaborate: MDI only includes selected brand icons, with the main criteria being that they are well known brands. Unfortunately, given that of the 3 people that have commented on this issue none of us have heard of any of the brands you have requested, they cannot be considered well known enough for inclusion.

Note, though, that there has been discussion in the past in creating a separate icon pack dedicated to brand icons. Should that ever come to fruition then this request will be revisited.

**Comment by MigliS** [comment]
Thank you for your answer.
I hope so, this would be very great!
