### ISSUE TITLE
mobile hotspot

### ISSUE THREAD

**Issue by savaka2** [Templarian/MaterialDesign#2469]
It would be used to indicate the mobile hotspot/portable hotspot/wifi tethering
It would probably look like a phone with wifi arcs from it like one of these:
![hotspot 1](https://user-images.githubusercontent.com/15303941/30967063-fd66e9a6-a428-11e7-85e0-a69cf7f5e7a4.png)![hotspot 2](https://user-images.githubusercontent.com/15303941/30967065-fd6e74a0-a428-11e7-996b-43db5e8290f2.png)

**Comment by mark-monserrat** [comment]
![mobile-hotspot-preview](https://user-images.githubusercontent.com/8490508/30987123-78541cfc-a4c8-11e7-9ac8-50a180597496.png)
[mobile-hotspot.svg.zip](https://github.com/Templarian/MaterialDesign/files/1342119/mobile-hotspot.svg.zip)

**Comment by MrGrigri** [comment]
To make the points smaller, could you square-off the phone where the cut-out of the signal overlaps? At that small, the circular cut-out, as opposed to a rectangular, is not noticeable. But I like the design.

**Comment by savaka2** [comment]
maybe make one that looks like a [generic phone](https://materialdesignicons.com/icon/cellphone) instead of an [iPhone](https://materialdesignicons.com/icon/cellphone-iphone)?

**Comment by mark-monserrat** [comment]
![mobile-hotspot-preview](https://user-images.githubusercontent.com/8490508/30988177-180bb8e2-a4cc-11e7-998e-82935e49b27a.png)
[mobile-hotspot-generic.svg.zip](https://github.com/Templarian/MaterialDesign/files/1342181/mobile-hotspot-generic.svg.zip)

**Comment by MrGrigri** [comment]
Swee @mark-monserrat, thanks.

**Comment by augustin32** [comment]
![mobile-hotspot24](https://user-images.githubusercontent.com/14167196/31052544-128cb5cc-a690-11e7-8a01-25cf84ca8128.png)
![mobile-hotspot36](https://user-images.githubusercontent.com/14167196/31052545-13d3254c-a690-11e7-9417-85bda14f1f89.png)
![mobile-hotspot48](https://user-images.githubusercontent.com/14167196/31052546-151bec22-a690-11e7-876d-7189c740a48f.png)
[mobile-hotspot.zip](https://github.com/Templarian/MaterialDesign/files/1346970/mobile-hotspot.zip)

**Comment by GreenTurtwig** [comment]
Just to note google use this in Android:
![image](https://user-images.githubusercontent.com/15905797/31056015-5d6e41d6-a6c3-11e7-870f-a6735577b9ce.png)

**Comment by Templarian** [comment]
[![cellphone-wireless](https://materialdesignicons.com/icon/cellphone-wireless)](https://materialdesignicons.com/icon/cellphone-wireless)
