### ISSUE TITLE
Designer TTF w/ Cheat Sheet

### ISSUE THREAD

**Issue by gejoreni** [Templarian/MaterialDesign#247]
There is no way to just select a glyph and copy the unicode glyph so I can paste it in my design files. or am I just missing it?
- [x] Designer TTF
- [ ] Cheat Sheet

**Comment by Templarian** [comment]
Technically the Webfonts are not for design work. You see those generate alphabetically so every release actually shifts the unicode numbering.

This is a very important use case that I've started coding out. It will be a TTF specifically aimed at designers with fixed unicode numbering. For now be careful using the webfont in design work.

**Comment by gejoreni** [comment]
Got it, thanks a bunch! - in mean time if you could generate a sheet with
all the SVGs on one page. I could easily use that. Is that possible?

**Comment by Templarian** [comment]
If you right click any icon it will give you the SVG file you can simply drag into illustrator. :smile:

**Comment by Templarian** [comment]
Coding this up, unlike the Webfont the download for the TTF will be 1:1 with the icon pack. As each icon is added/updated the font will update. This has been requested outside of GitHub in the past, so I'm trying to get it in to prevent people from resorting to webfonts.

There are some design changes that will be going into the site to better describe to designers not to download the webfont.

**Comment by gejoreni** [comment]
Another huge thing for designers is "sticker sheets" I've gone through the
trouble making one using Google's SVG resources but it lacks all of the
necessary community icons. If you could somehow export all of the SVGs to 1
sheet, I would be happy to organize it and make a
http://materialdesignicons.com/ branded sticker sheet. bringing in the
compressed SVGs 1by1 would take a very long time. Anyway, if someone can at
least get all of the SVGS on one sheet - I'll do the rest.

**Comment by Templarian** [comment]
If you could explain what a SVG sticker sheet is I could write a script to automate the generation.

**Comment by gejoreni** [comment]
Sure, basically it is a svg page that has all of the SVG icons on it
(properly named) and in their appropriate types ie. communication,
navigation social etc. basically designers can have a page or a artboard in
their design with all the icons that they can search, cut and paste from
very quickly. It would be best if each icon was already placed in a  48 px
box -  but that's not so important. Hope that clears it up a little. below
is a screen shot of a simple one I made for sketch.[image: Inline image 1]

**Comment by Templarian** [comment]
MDI has actual tagging instead simple categories, but I can show the aliases. That would probably be 10x more helpful.

**Comment by gejoreni** [comment]
A lot of times, designers aren't 100% sure which icon is the best, and
therefor need to do a visual search, which is why categories is helpful.
but honestly a full, searchable, sticker sheet is 95% everything else is
icing.

**Comment by CoDEmanX** [comment]
Both, generic categories and aliases seem important.

Google's icons come with a category already (their icons are organized in subfolders in their GitHub repo). Every icon is in one category only. Every icon can have several aliases for enhanced search-ability, but their should still be one primary classification (=category).

In a document store, aliases could be stored as an array of string, with the first element to be the category. In a relational DBMS, a column `order` could be used. It does require some special code however. (server-side or in application). Not sure if a Set would work, as order may not be guaranteed.

**Comment by Templarian** [comment]
https://materialdesignicons.com/design

Designer TTF can be downloaded above along with all the SVGs. The cheatsheet is still a work in progress, but the preview.html includes the hex codes now.

**Comment by gejoreni** [comment]
on a mac - the .zip extracts to a .zip.cpgz - then back to a zip. It seems
like an infinite loop. Not sure if I'm missing something.

**Comment by CoDEmanX** [comment]
Works just fine on Windows. Do you have some weird application installed that turns zip into cpgz?

**Comment by Templarian** [comment]
@gejoreni #1242 Found the cause of this on Macs. Looks like something I can fix eventually.
