### ISSUE TITLE
Law weights 

### ISSUE THREAD

**Issue by telwagang** [Templarian/MaterialDesign#2470]

**Comment by JamesCoyle** [comment]
Do you mean?
[![](https://materialdesignicons.com/icon/scale-balance)](https://materialdesignicons.com/icon/scale-balance)

**Comment by telwagang** [comment]
yes more modern and material ?

**Comment by Templarian** [comment]
Are you asking if it can be more Material Design'ish? Not sure that's possible. It's already pretty minimal.

**Comment by CoDEmanX** [comment]
We could make it a digital scale xD

**Comment by telwagang** [comment]
a digital scale.? as in what i meant early more minimal and less boring.. is that makes sense

**Comment by GreenTurtwig** [comment]
Just thought I'd mention we have a normal kitchen scale and a bathroom scale too:
[![](https://materialdesignicons.com/icon/scale)](https://materialdesignicons.com/icon/scale)[![](https://materialdesignicons.com/icon/scale-bathroom)](https://materialdesignicons.com/icon/scale-bathroom)

But yeah, it would be nice to have a digital kitchen scale, similar to the one in Webalys' pack: https://www.iconfinder.com/icons/850199/scale_weight_icon

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
