### ISSUE TITLE
Food Variant: Asian

### ISSUE THREAD

**Issue by mark-monserrat** [Templarian/MaterialDesign#2472]
I would like to propose a food-variant-asian icon:
![food-variant-asian-preview](https://user-images.githubusercontent.com/8490508/31000597-4e827e4a-a50f-11e7-87ec-7c0357250fbf.png)
[food-variant-asian.svg.zip](https://github.com/Templarian/MaterialDesign/files/1343063/food-variant-asian.svg.zip)

**Comment by MrGrigri** [comment]
We already have `rice`.

![rice](https://materialdesignicons.com/icon/rice)

**Comment by Templarian** [comment]
Marking as a duplicate / closing.
