### ISSUE TITLE
Luggage Icons

### ISSUE THREAD

**Issue by mark-monserrat** [Templarian/MaterialDesign#2473]
I noticed that there are icons of briefcase which I think is more related to business concept. I would like to propose a luggage icon set which are more related to travel:
![luggage-icon-preview](https://user-images.githubusercontent.com/8490508/31001379-d829bde2-a515-11e7-9b00-5bc465b533b6.png)
[luggage-icon-set.zip](https://github.com/Templarian/MaterialDesign/files/1343131/luggage-icon-set.zip)

**Comment by JapanYoshi** [comment]
I think a sideways view would be more recognizable as a luggage bag.
![circle4178](https://user-images.githubusercontent.com/8707990/31016969-34c9d1fa-a56a-11e7-84fe-40d278641cc7.png)
![circle4179](https://user-images.githubusercontent.com/8707990/31016970-34d5d220-a56a-11e7-94ab-3c68f83abef4.png)

**Comment by JapanYoshi** [comment]
The diagonal one is possibly more recognizable.
![circle4179](https://user-images.githubusercontent.com/8707990/31017243-2fb0829e-a56b-11e7-8fc5-825a4b741489.png)
![circle4178](https://user-images.githubusercontent.com/8707990/31017244-30034b5a-a56b-11e7-97ff-c21c78d0a711.png)

**Comment by PeterShaggyNoble** [comment]
Context can help define an icon - use `briefcase` on a travel website and it will be recognised and interpreted as a suitcase.

**Comment by PeterShaggyNoble** [comment]
[![image](https://user-images.githubusercontent.com/15157491/33136601-8a64a754-cf9d-11e7-9ade-2790c60017fe.png)](https://github.com/Templarian/MaterialDesign/files/1496637/trip.zip)

**Comment by MrGrigri** [comment]
I found this one on [Google Flights](https://flights.google.com).

![image](https://user-images.githubusercontent.com/4528551/50578310-7c981100-0df5-11e9-9217-048987aa24a5.png)

[svg](https://www.gstatic.com/flights/app/2x/carry_on_restricted_grey700_24dp.svg)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50984252-6c57f400-14cf-11e9-9341-5f66d63e4de2.png)![image](https://user-images.githubusercontent.com/1015040/50984264-74b02f00-14cf-11e9-9f4c-09c57f1719e4.png)
![image](https://user-images.githubusercontent.com/1015040/50984282-7f6ac400-14cf-11e9-858d-b1b850a76c69.png)![image](https://user-images.githubusercontent.com/1015040/50984295-8a255900-14cf-11e9-8f50-5ec7348ed4ef.png)
![image](https://user-images.githubusercontent.com/1015040/50984312-95788480-14cf-11e9-8129-8019c39dbb76.png)

[luggage.zip](https://github.com/Templarian/MaterialDesign/files/2746349/luggage.zip)

**Comment by MrGrigri** [comment]
I believe for consistency sake, they should all be labeled `bag-*`.

**Comment by goyney** [comment]
[![bag-carry-on](https://materialdesignicons.com/icon/bag-carry-on)](https://materialdesignicons.com/icon/bag-carry-on)[![bag-carry-on-off](https://materialdesignicons.com/icon/bag-carry-on-off)](https://materialdesignicons.com/icon/bag-carry-on-off)
[![bag-checked](https://materialdesignicons.com/icon/bag-checked)](https://materialdesignicons.com/icon/bag-checked)

**Comment by goyney** [comment]
Leaving open for now because we need to rename `carry-on-bag-check` to `bag-carry-on-check`.

**Comment by Templarian** [comment]
Renamed. ✔️
