### ISSUE TITLE
Face Variant: Agent

### ISSUE THREAD

**Issue by mark-monserrat** [Templarian/MaterialDesign#2474]
I would like to propose a variant of face icon which ensembles an agent's face. This can be used as customer service representative, cockpit pilot, command center, a DJ, an event organizer, etc.
![face-agent-icon](https://user-images.githubusercontent.com/8490508/31001952-07a07d64-a51a-11e7-975a-ed4d1b9f583a.png)
[face-agent-icon.svg.zip](https://github.com/Templarian/MaterialDesign/files/1343179/face-agent-icon.svg.zip)

**Comment by MrGrigri** [comment]
I would add the aliases of customer service and support.

**Comment by PeterShaggyNoble** [comment]
Possible dupe of #1654.

**Comment by MrGrigri** [comment]
I would redirect and close the other issue here because this one already has a contribution.

**Comment by Templarian** [comment]
[![face-agent](https://materialdesignicons.com/icon/face-agent)](https://materialdesignicons.com/icon/face-agent)

Took a while, but added. Once you get 5 icons let me know and I'll assign these to a contributor account.

**Comment by PeterShaggyNoble** [comment]
Aliases added.
