### ISSUE TITLE
Atmospheric Gases

### ISSUE THREAD

**Issue by Snowda** [Templarian/MaterialDesign#2475]
Hello, I'm currently looking to put icons beside Oxygen, Nitrogen, Carbon Monoxide and Methane (and a more niche Hydrogen Sulfide if possible) readings for atmospheric gas measurement and field work safety applications.

Something along the lines of "O2", "N2", "CO", "CH4" & "H2S" in a similar layout to periodic-table-co2 from #2011 would be perfect!

**Comment by GreenTurtwig** [comment]
I suggest renaming `periodic-table-co2` to `chemical-formula-co2` as CO2 is a compound, not an element. This would also make sense as O2 and N2 are molecules not elements.

**Comment by MrGrigri** [comment]
I agree with you @GreenTurtwig, however, I also believe that this request could open up a can of constant chemical formula requests.

**Comment by GreenTurtwig** [comment]
I also thought the same thing, however as O2 and N2 are the two most common gases on Earth it makes sense to include them. Also including CO could be useful for Carbon Monoxide detectors and such.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/31025338-398c4c8e-a53a-11e7-9bf1-975d2f90980b.png)
![image](https://user-images.githubusercontent.com/15905797/31025344-4123f3e8-a53a-11e7-86f2-eabe590a85cd.png)

![image](https://user-images.githubusercontent.com/15905797/31025358-4d1be070-a53a-11e7-99cd-561386cb9f75.png)
![image](https://user-images.githubusercontent.com/15905797/31025366-547f2836-a53a-11e7-93c3-2ad8e77446c4.png)

![image](https://user-images.githubusercontent.com/15905797/31025378-5e80e342-a53a-11e7-855f-5a635f6af9de.png)
![image](https://user-images.githubusercontent.com/15905797/31025391-66214402-a53a-11e7-8ca6-ad1abee6fc9c.png)

![image](https://user-images.githubusercontent.com/15905797/31025400-6f07bd26-a53a-11e7-9746-dfe49f07b56a.png)
![image](https://user-images.githubusercontent.com/15905797/31025410-76fb02cc-a53a-11e7-8269-7e4ef90bcbab.png)
[chemical-formulas.zip](https://github.com/Templarian/MaterialDesign/files/1345006/chemical-formulas.zip)

**Comment by JamesCoyle** [comment]
Personally I think we should release the alphanumeric font as an actual font so people can just use that to create any they want. Then release these as vector-only.

**Comment by Templarian** [comment]
I agree, but for some of these more specific ones it is useful. At least for the really common ones.

**Comment by JamesCoyle** [comment]
I feel like N₂O, H₂O, CO₂, and O₂ would be most recognizable/usable in non-scientific contexts. Maybe NaCl but can't fit that in an icon.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/31046746-29170706-a5f6-11e7-990f-b07b5b221ad5.png)
![image](https://user-images.githubusercontent.com/15905797/31046747-31e467a2-a5f6-11e7-8c58-3b8834133349.png)
[chemical-formula-h2o.zip](https://github.com/Templarian/MaterialDesign/files/1346478/chemical-formula-h2o.zip)

![image](https://user-images.githubusercontent.com/15905797/31046752-4d0fad70-a5f6-11e7-80ab-41f3219c895f.png)
![image](https://user-images.githubusercontent.com/15905797/31046753-52b08614-a5f6-11e7-940e-d134cc73a28e.png)
[chemical-formula-n2o.zip](https://github.com/Templarian/MaterialDesign/files/1346479/chemical-formula-n2o.zip)

Yeah, NaCl is too long to fit:
![image](https://user-images.githubusercontent.com/15905797/31046759-74d91f9e-a5f6-11e7-9c7a-0034f60bc974.png)

**Comment by CoDEmanX** [comment]
Maybe we should create a complete set of upper- and lowercase material-ish letters for people, as a separate project?

**Comment by Templarian** [comment]
@CoDEmanX It's in the plans (and has already been created). Going to upload it as a separate package so it isn't lumped into MDI and can use more correct codepoints.

**Comment by Templarian** [comment]
Also, @CoDEmanX https://join.slack.com/t/materialdesignicons/shared_invite/enQtMjQ2Njk2MzYyODcwLTEyYTRlNjRlNDEzMjQ4ZmEwOWE0YTMyNDEwNDE2YmM4N2VmMTVlYzUzYWYxNjg5YmExNGI2OGVhODU3Njk0YTk join us on slack if you can.

**Comment by Spirituss** [comment]
Hello, I'm currently looking for icons to indicate air quality. The next icons are wanted:

PM25 (could be performed as cloud with small points inside or just text)
PM10 (could be performed as cloud with bold points inside or just text)
CO (not CO2!)
SO2
NO2

**Comment by JapanYoshi** [comment]
![pm2 5png](https://user-images.githubusercontent.com/8707990/60249393-1dc8d580-9908-11e9-8523-5a17de7a5b73.png)![spm](https://user-images.githubusercontent.com/8707990/60249395-1dc8d580-9908-11e9-9f92-e80f972bc101.png)![pm10](https://user-images.githubusercontent.com/8707990/60249394-1dc8d580-9908-11e9-8864-3c5b5d832e42.png)
Not sure if these are what you want, but here are some icons based on Google's ``cloud``

**Comment by Snowda** [comment]
@JapanYoshi I think he meant dots to look like debris floating in the air to represent "Particulate Matter" (PM) rather than a dot making "2.5" denoting a 25 value.

Also, now this is very pedantic, but S would just be Sulfur (S) rather than Sulfur Dioxide (SO2).

**Comment by Spirituss** [comment]
> ![pm2 5png](https://user-images.githubusercontent.com/8707990/60249393-1dc8d580-9908-11e9-8523-5a17de7a5b73.png)![spm](https://user-images.githubusercontent.com/8707990/60249395-1dc8d580-9908-11e9-9f92-e80f972bc101.png)![pm10](https://user-images.githubusercontent.com/8707990/60249394-1dc8d580-9908-11e9-8864-3c5b5d832e42.png)
> Not sure if these are what you want, but here are some icons based on Google's `cloud`

@Snowda is right regarding my initial expectations, but the icons you suggest for PM2.5 and PM10 look acceptable. May be you can just add some empty dots on the clouds to make them more looking like cloud of dust but not like storm cloud.

As for atmospheric gases, the option which @GreenTurtwig proposed earlier for O2, N2, etc. looks also acceptable. But it important to visualize the whole chemical formula (like CO2) but not any simplified option (like CO or S, which you used on cloud), because, like for CO and CO2, it can be very different gases and it important to understand which one I see in the application.

**Comment by Spirituss** [comment]
@JamesCoyle 
For PM25 and PM10 it could be something like dots on the icons ```mdi:chart-scatter-plot``` and ```mdi:chart-scatter-plot-hexbin``` respectively.

**Comment by Spirituss** [comment]
Please, specify actual milestone, since 4.2.95 doesn't contain above mentioned icons.
I would also inquire ozone icon, since O3, NO2, SO2, CO - are kind of "standard" set of atmospheric gases that can be observed via world meteo stations like http://aqicn.org or https://darksky.net or https://weather.com. A lot of users of "smart home" uses MDI icons set, expecting these icons.

**Comment by goyney** [comment]
We're likely not going to be included a bunch of chemical formulas. There's way too many and is a slippery slope for continuing to add more when most are extremely niche. We have a full alphabetic and numeric set in the library which can easily be used to create any combination of letter and numbers. That's why those were added. I'm moving for this issue to be closed.

**Comment by PeterShaggyNoble** [comment]
I agree with @goyney - closing this out.

**Comment by Spirituss** [comment]
> We're likely not going to be included a bunch of chemical formulas. There's way too many and is a slippery slope for continuing to add more when most are extremely niche. We have a full alphabetic and numeric set in the library which can easily be used to create any combination of letter and numbers. That's why those were added. I'm moving for this issue to be closed.

Could you please provide me with link to this alphabetic and numeric set? I can't find it. Thanks!

**Comment by Stefano0042** [comment]
Interesting debate, I would like to point out  an "home assistant" related issue about "mdi:moleule-co" and "mdi:molecule-co2" 
Both are not rendered at all in the lovelace cards, "mdi:molecule" on the other hand is trouble free.
Thank you.

**Comment by goyney** [comment]
> Interesting debate, I would like to point out an "home assistant" related issue about "mdi:moleule-co" and "mdi:molecule-co2"
> Both are not rendered at all in the lovelace cards, "mdi:molecule" on the other hand is trouble free.
> Thank you.

Home Assistant has not updated to v5.0 of MDI yet, as far as I know. The old names were `periodic-table-co(2)`.

**Comment by Stefano0042** [comment]
@goyney 
clear, problem solved. Thank you.
