### ISSUE TITLE
Album should be given the alias Vinyl

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2477]
[![](https://materialdesignicons.com/icon/album)](https://materialdesignicons.com/icon/album)

**Comment by PeterShaggyNoble** [comment]
I'd suggest `record` too but we're already using that as an icon name.

**Comment by JamesCoyle** [comment]
Surely it doesn't matter if aliases overlap?

**Comment by PeterShaggyNoble** [comment]
@JamesCoyle, see [here](https://github.com/Templarian/MaterialDesign-Site/issues/26).

**Comment by JamesCoyle** [comment]
I don't see how it's an issue. @templarian surely it doesn't matter if multiple icons have the same alias as long as their actual names used to refer to the icons are unique.

**Comment by CoDEmanX** [comment]
Aliases, as in auxiliary names to improve discoverability, should be added as much as possible IMO. Even if it's interpreting the icon in a completely new way, as long as it suits other purposes.

**Comment by Templarian** [comment]
@PeterShaggyNoble @JamesCoyle Fixed that issue. Definitely shouldn't have said that.

**Comment by GreenTurtwig** [comment]
Given the aliases `vinyl` and `record`.
