### ISSUE TITLE
SVG webfont seems to be malformed

### ISSUE THREAD

**Issue by Kolorbon** [Templarian/MaterialDesign#2478]
I wanted to use the icons as ligatures, therefore I imported the SVG file (from the downloadable webfont) into IcoMoon. There the icons were rectangular (32x24) instead of square (24x24).

Then I converted the provided TTF file to SVG, reimported it and the icons had a square size of 24x24. Is this intended, or a bug (mdi, IcoMoon)?

**Comment by Templarian** [comment]
Might be a bug in our export, I'm not sure anyone uses the SVG font, we'll be dropping it from the build soon as we move away from legacy support.

For custom webfont builds you can also use: https://github.com/Templarian/MaterialDesign-SVG

The above repo is for third party builds and libraries and updates when MDI updates.
