### ISSUE TITLE
notebook icon

### ISSUE THREAD

**Issue by gabrielgrant** [Templarian/MaterialDesign#2479]
Perhaps something like https://material.io/icons/#ic_event_note but with the outer box rotated 90 degrees?

**Comment by gabrielgrant** [comment]
here's a take on what i'm thinking, modified from the "book" icon:
[notebook.svg.zip](https://github.com/Templarian/MaterialDesign/files/1346153/notebook.svg.zip)

(for some reason GitHub isn't letting me attach SVG files directly: "We don't support that file type"). I see you don't generally want pull requests, but let me know if that would be easier to review

**Comment by gabrielgrant** [comment]
That feels pretty small and cramped. Here's another version with only three rings that breathe a bit better:
![notebook 3](https://user-images.githubusercontent.com/493968/31042996-1a376e3e-a569-11e7-9f0d-61dffa3361af.png)
Enlarged:
![notebook 3 large](https://user-images.githubusercontent.com/493968/31042997-1a37b15a-a569-11e7-8cc3-21304c75ed1e.png)

SVG:
[notebook.3.svg.zip](https://github.com/Templarian/MaterialDesign/files/1346159/notebook.3.svg.zip)

**Comment by gabrielgrant** [comment]
with a window to possibly make it look more "notebook-ey"?
![notebook 3 window large](https://user-images.githubusercontent.com/493968/31043089-c56f99e2-a56a-11e7-9cd3-ac8f1b9b011d.png)
![notebook 3 window](https://user-images.githubusercontent.com/493968/31043090-c573290e-a56a-11e7-969e-3e6de8ea0006.png)
[notebook.3.window.svg.zip](https://github.com/Templarian/MaterialDesign/files/1346162/notebook.3.window.svg.zip)

**Comment by gabrielgrant** [comment]
A couple more variations:

Blank page:
![notebook 3 blank large](https://user-images.githubusercontent.com/493968/31043155-15788998-a56c-11e7-8aa2-16e3505d595f.png)
![notebook 3 blank](https://user-images.githubusercontent.com/493968/31043154-157840dc-a56c-11e7-99f5-63abddbd81b6.png)
[notebook.3.blank.svg.zip](https://github.com/Templarian/MaterialDesign/files/1346183/notebook.3.blank.svg.zip)

And with lines:

![notebook 3 lines large](https://user-images.githubusercontent.com/493968/31043156-15791e58-a56c-11e7-944d-df6fab3c46b1.png)
![notebook 3 lines](https://user-images.githubusercontent.com/493968/31043153-1577e0d8-a56c-11e7-81b9-fd6cedc78b19.png)
[notebook.3.lines.svg.zip](https://github.com/Templarian/MaterialDesign/files/1346182/notebook.3.lines.svg.zip)

**Comment by GreenTurtwig** [comment]
Yeah, GitHub doesn't like SVGs so you have to ZIP them.

How's this?
![image](https://user-images.githubusercontent.com/15905797/31046555-70127176-a5f2-11e7-8372-89b6797b7f3f.png)
![image](https://user-images.githubusercontent.com/15905797/31046557-7998675a-a5f2-11e7-931a-fc42ee8d263f.png)
[notebook.zip](https://github.com/Templarian/MaterialDesign/files/1346457/notebook.zip)

**Comment by gabrielgrant** [comment]
I changed to three rings, because the fourth felt a bit cramped. Yours is more visible at small size, though, because the rings are simpler. 

Here's another take on yours with only three binding rings:

[notebook.simple.3.svg.zip](https://github.com/Templarian/MaterialDesign/files/1346506/notebook.simple.3.svg.zip)
![notebook simple 3 large](https://user-images.githubusercontent.com/493968/31046957-df1ec31c-a5b6-11e7-870d-1a72df1b5474.png)
![notebook simple 3](https://user-images.githubusercontent.com/493968/31046958-df1fc3e8-a5b6-11e7-9469-1522f687cafd.png)

**Comment by GreenTurtwig** [comment]
Definitely looks better with three, I feel like it's instantly recognisable now. :cat2:

**Comment by gabrielgrant** [comment]
Sweet :)

what do you think about bookmark vs lines vs window within it?

**Comment by GreenTurtwig** [comment]
I personally prefer the bookmark as it stays consistent with the other book related icons. :cat2:

**Comment by gabrielgrant** [comment]
makes sense :+1:

**Comment by gabrielgrant** [comment]
shall i clean up that version i just posted (to at least remove the Inkscape cruft), or would you rather re-create?

**Comment by gabrielgrant** [comment]
(i'm not sure what the canonical format is -- it seems there's both an `.svg` and a `.design` for each icon, but I'm on linux, so I don't think i can convert to `.design` format)

**Comment by JamesCoyle** [comment]
Inkscape can output as `Optimized SVG` which is probably the best choice.

**Comment by gabrielgrant** [comment]
Two files in here: inkscape's "Optimized SVG" and a hand-edited version of that output that strips out some additional unneeded metadata

[notebook.simple.3.optimized.zip](https://github.com/Templarian/MaterialDesign/files/1346539/notebook.simple.3.optimized.zip)

**Comment by Templarian** [comment]
[![notebook](https://materialdesignicons.com/icon/notebook)](https://materialdesignicons.com/icon/notebook)

**Comment by gabrielgrant** [comment]
Thanks a lot for getting this merged!
