### ISSUE TITLE
Vector image naming does not work with Android Studio

### ISSUE THREAD

**Issue by Chris-Aranha** [Templarian/MaterialDesign#248]
This is a simple problem but Android Studio will not compile the app when vector images are named as "numeric-3-box.xml" since this breaks the naming convention.... in order for the file to work on a layout the file name needs to have underscores such as the one shown here "numeric_3_box.xml". All vector images when downloading via MDI have "-" instead of "_". I hope this helps.

**Comment by Templarian** [comment]
I'll get that fixed tonight. I actually don't develop Android applications so I without people telling me these kind of issues I won't know about them, so thanks for taking the time to open an issue!

Wonder what everyone else has been doing. I assume manually renaming it. :disappointed:

**Comment by Templarian** [comment]
Fixed.

And then some. Anywhere you could download a SVG, you can now download the Vector Drawable by itself.
