### ISSUE TITLE
Guy Fawkes mask

### ISSUE THREAD

**Issue by tobieeniafe** [Templarian/MaterialDesign#2480]
mask icons, anonymous mask, drama mask etc

**Comment by GreenTurtwig** [comment]
There's already a request for drama masks here: https://github.com/Templarian/MaterialDesign/issues/1972
A Guy Fawkes mask may be too detailed for MDI, any reason why you specifically need one?

**Comment by augustin32** [comment]
Guy Fawkes Mask, pretty legible
![guy-fawkes-mask24](https://user-images.githubusercontent.com/14167196/31048013-abde23e6-a61d-11e7-8b45-4c315e5270bb.png)
![guy-fawkes-mask36](https://user-images.githubusercontent.com/14167196/31048015-ad444f08-a61d-11e7-9b45-a16a8ef294b3.png)
![guy-fawkes-mask48](https://user-images.githubusercontent.com/14167196/31048016-ae61b25e-a61d-11e7-9e0a-7210e5f7fe36.png)
[guy-fawkes-mask .zip](https://github.com/Templarian/MaterialDesign/files/1346640/guy-fawkes-mask.zip)

**Comment by tobieeniafe** [comment]
I'm creating an app about arts and there's no better icon for representing drama the masks

**Comment by GreenTurtwig** [comment]
@augustin32 Haha, that's brilliant!

@tobieeniafe I was more asking why you wanted a Guy Fawkes/anonymous mask. :-P

**Comment by augustin32** [comment]
And here's the Theatre Masks/Drama Masks :)
![drama-masks24](https://user-images.githubusercontent.com/14167196/31048228-a9559664-a621-11e7-822d-05a25aa27032.png)
![drama-masks36](https://user-images.githubusercontent.com/14167196/31048229-ab37a378-a621-11e7-9938-c4d98b500fda.png)
![drama-masks48](https://user-images.githubusercontent.com/14167196/31048230-acefb8f4-a621-11e7-8b14-8fbe0c7b56dc.png)
[drama-masks.zip](https://github.com/Templarian/MaterialDesign/files/1346659/drama-masks.zip)

**Comment by GreenTurtwig** [comment]
Google had this on maps:
![screenshot_20170930-185829_01](https://user-images.githubusercontent.com/15905797/31048258-954e2524-a611-11e7-8a5e-4b82ab37baa9.jpg)
I need to try and grab it at some point.

**Comment by tobieeniafe** [comment]
@GreenTurtwig it doesn't hurt to have it innit 😁

**Comment by GreenTurtwig** [comment]
Or course not, I was just wondering what I could be used for. :-P

**Comment by augustin32** [comment]
Not too recongizable as drama masks.
![drama-masks-variant24](https://user-images.githubusercontent.com/14167196/31048331-6df8c9c2-a623-11e7-9832-1e70e1cb307f.png)
![drama-masks-variant36](https://user-images.githubusercontent.com/14167196/31048332-6f550d94-a623-11e7-8e51-b9c0614fd7af.png)
![drama-masks-variant48](https://user-images.githubusercontent.com/14167196/31048333-7136d5c0-a623-11e7-9aec-56df5ceb3d4a.png)

**Comment by GreenTurtwig** [comment]
@augustin32 You should post the drama masks over at: https://github.com/Templarian/MaterialDesign/issues/1972

**Comment by augustin32** [comment]
Ok, posted.

**Comment by Templarian** [comment]
[![guy-fawkes-mask](https://materialdesignicons.com/icon/guy-fawkes-mask)](https://materialdesignicons.com/icon/guy-fawkes-mask)

**Comment by MrGrigri** [comment]
I love it...I believe it would be a good icon for anonymity.
