### ISSUE TITLE
Amazon Alexa Icon

### ISSUE THREAD

**Issue by juergenschubert** [Templarian/MaterialDesign#2481]
Icon I can use within HomeAssistant for my Alexa automation. mdi.alexa

**Comment by juergenschubert** [comment]
Icon I can use within HomeAssistant for my Alexa automation. mdi.alea

**Comment by akentner** [comment]
me too

**Comment by augustin32** [comment]
In a elipse shape, it just doesn't look recognizable at 1:1 resolution
![alexa24](https://user-images.githubusercontent.com/14167196/31054570-b518cae2-a6bd-11e7-94b0-9a4b63aefd10.png)
![alexa36](https://user-images.githubusercontent.com/14167196/31054571-bd352540-a6bd-11e7-97ea-13726a9e5fb2.png)
![alexa48](https://user-images.githubusercontent.com/14167196/31054572-be82867c-a6bd-11e7-91ad-4e0c80f094ac.png)

**Comment by GreenTurtwig** [comment]
Closing as duplicate of https://github.com/Templarian/MaterialDesign/issues/1234
