### ISSUE TITLE
bulletproof-vest

### ISSUE THREAD

**Issue by augustin32** [Templarian/MaterialDesign#2482]
Bulletproof Vest (recreated from icons8 variant)
![bulletproof-vest24](https://user-images.githubusercontent.com/14167196/31054960-db6465a0-a6c5-11e7-8908-ea41d5da51a7.png)
![bulletproof-vest36](https://user-images.githubusercontent.com/14167196/31054961-dc4ef76e-a6c5-11e7-93d7-99f3b7a47cbf.png)
![bulletproof-vest48](https://user-images.githubusercontent.com/14167196/31054962-dd1adcda-a6c5-11e7-86ae-56762a0a91f5.png)
[bulletproof-vest.zip](https://github.com/Templarian/MaterialDesign/files/1347154/bulletproof-vest.zip)

**Comment by GreenTurtwig** [comment]
It looks almost identical to Icons8s and not really sure about copyright e.t.c.

![image](https://user-images.githubusercontent.com/15905797/31055947-a01eb37c-a6c2-11e7-99c5-20ec191da0a7.png)
https://icons8.com/icon/30761/bulletproof-vest

Also @augustin32 why do all your SVGs have a 6x6 viewbox?

**Comment by augustin32** [comment]
@GreenTurtwig i don't know why it have 6x6 viewbox.

**Comment by CoDEmanX** [comment]
I wonder if copyright even applies, might be below the threshold of originality because it's really just a few strokes, but not a lawyer.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
