### ISSUE TITLE
Horseshoe

### ISSUE THREAD

**Issue by whitelizard** [Templarian/MaterialDesign#2483]
A horse shoe to represent "horses" or "stable", and turn it as a "U" and it can also be used for "luck"

https://encrypted.google.com/search?q=horseshoe&safe=off&hl=en&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_yLj98c_WAhXobZoKHe2GAjUQ_AUICigB&biw=1855&bih=990#imgrc=LQzt7oSJ07iW0M:

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/42601600-2ae41024-8534-11e8-9711-4cdf60410a19.png)

[horseshoe.zip](https://github.com/Templarian/MaterialDesign/files/2186347/horseshoe.zip)

**Comment by CoDEmanX** [comment]
The square shape like ends could be better aligned to grid I guess?

**Comment by goyney** [comment]
The rectangles are perfect 4x3 blocks. The entire icon is centered vertically, offsetting it by half a pixel.

**Comment by goyney** [comment]
I don't know what you're asking. The entire artwork was centered on the artboard to equalize white space. The height of the artwork is 21px, 1.5px white space on top and bottom.

**Comment by Templarian** [comment]
Agree with @CoDEmanX This should be fixed to exact points at the top to give it a more MD look on the grid.

**Comment by goyney** [comment]
Updated.

**Comment by CoDEmanX** [comment]
Comparison of both versions at native size, 96ppi, zoomed to 800% (nearest neighbor algorithm)
- Left: pixel perfect
- Right: off-grid

![grafik](https://user-images.githubusercontent.com/1309249/42736186-040f7034-8862-11e8-9238-d2eb2cf8dde5.png)

**Comment by Templarian** [comment]
[![horseshoe](https://materialdesignicons.com/icon/horseshoe)](https://materialdesignicons.com/icon/horseshoe)
