### ISSUE TITLE
Timeline / Activites

### ISSUE THREAD

**Issue by BRoy98** [Templarian/MaterialDesign#2484]
An icon that represents timeline or activities. Maybe like this:
<img src="https://d30y9cdsu7xlg0.cloudfront.net/png/83843-200.png"  width="200" height="200" />
<img src="https://maxcdn.icons8.com/Share/icon/nolan/Data//timeline1600.png"  width="200" height="200" />

**Comment by GreenTurtwig** [comment]
We already have several "list" type icons:
[![](https://materialdesignicons.com/icon/format-list-bulleted)](https://materialdesignicons.com/icon/format-list-bulleted)[![](https://materialdesignicons.com/icon/format-list-bulleted-type)](https://materialdesignicons.com/icon/format-list-bulleted-type)
[![](https://materialdesignicons.com/icon/format-list-checks)](https://materialdesignicons.com/icon/format-list-checks)[![](https://materialdesignicons.com/icon/view-list)](https://materialdesignicons.com/icon/view-list)

Would one of these not do, and if so, do you have any better examples?

**Comment by BRoy98** [comment]
All these icons represent "list". I think there should be a linking line between these bullets like the first image. That would look better for a "timeline" icon.

**Comment by PeterShaggyNoble** [comment]
@BRoy98, I'm guessing `chart-timeline` doesn't suit your needs?

[![](https://materialdesignicons.com/icon/chart-timeline)](https://materialdesignicons.com/icon/chart-timeline)

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/format-line-spacing)](https://materialdesignicons.com/icon/format-line-spacing)

Also have the source control icons that could be of use.

**Comment by CoDEmanX** [comment]
There are some Google Cloud product icons, which would actually work quite well:

![image](https://user-images.githubusercontent.com/1309249/31473273-ba59bc80-aef3-11e7-93b1-e94f23356ee5.png)
![image](https://user-images.githubusercontent.com/1309249/31473289-cff7d81a-aef3-11e7-8619-0158c375e2be.png)
![image](https://user-images.githubusercontent.com/1309249/31473296-d8b91be4-aef3-11e7-9291-37de5a144be3.png)
![image](https://user-images.githubusercontent.com/1309249/31473316-f1ef1802-aef3-11e7-9181-5df593cd74d1.png)

**Comment by BRoy98** [comment]
@PeterShaggyNoble @JamesCoyle I already provided two icons that represents how I want the icon to be look like.  `chart-timeline` can be a workaround but this really do not suit in my application.

**Comment by BRoy98** [comment]
@GreenTurtwig I think I have provided enough information about the icon. Please review the `Needs More Information` tag ☺

**Comment by GreenTurtwig** [comment]
Ahh sorry, forgot to remove that. 🐈

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/46684600-86242b00-cbb0-11e8-9e7e-96c6f4255f01.png) ![image](https://user-images.githubusercontent.com/4528551/46684611-93d9b080-cbb0-11e8-8e5e-cd907b6bce94.png) ![image](https://user-images.githubusercontent.com/4528551/46684636-a94eda80-cbb0-11e8-99c9-0ba703c11693.png) ![image](https://user-images.githubusercontent.com/4528551/46684672-c683a900-cbb0-11e8-8a75-6cd3ad516549.png)

[timeline.zip](https://github.com/Templarian/MaterialDesign/files/2461391/timeline.zip)

**Comment by PeterShaggyNoble** [comment]
This is what Google use:

[![timeline](http://mdi.houseofdesign.ie/tools/preview/?icon=timeline&action=launch)](https://material.io/tools/icons/?search=timeline&icon=timeline)

**Comment by MrGrigri** [comment]
That to me doesn't say 'timeline', it says 'line chart'

**Comment by Templarian** [comment]
Added the timeline icons above. We can probably add several others in the future in a similar style.
