### ISSUE TITLE
Rename car-convertable

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2487]
Sorry for the extended absence, been distracted by other things lately. Looks like I've got a good bit to catch up on.

Anyway, `car-convertable`  needs to be renamed to `car-convertible`.

**Comment by GreenTurtwig** [comment]
That's a mistake on my part, don't know how I could have missed that. :-P

**Comment by PeterShaggyNoble** [comment]
@GreenTurtwig, I was blaming @Templarian for the typo - you should have said nothing! 😆

**Comment by GreenTurtwig** [comment]
Well I did make the mistake, he just didn't catch it. 😉

**Comment by Templarian** [comment]
It's a car that is convert-able. 😹 

[![car-convertible](https://materialdesignicons.com/icon/car-convertible)](https://materialdesignicons.com/icon/car-convertible)
