### ISSUE TITLE
world icon?

### ISSUE THREAD

**Issue by serdam55** [Templarian/MaterialDesign#2488]
hello, is possible integrate a world icon? like this: https://icons8.com/icon/52650/globe

thanks

**Comment by GreenTurtwig** [comment]
We have:
[![](https://materialdesignicons.com/icon/earth)](https://materialdesignicons.com/icon/earth)
[![](https://materialdesignicons.com/icon/earth-box)](https://materialdesignicons.com/icon/earth-box)
