### ISSUE TITLE
Unverified Icon

### ISSUE THREAD

**Issue by Rethic** [Templarian/MaterialDesign#2489]
We currently have a "verified" icon that appears as a shield with a check mark within it.

Can we get an "unverified" icon that uses the same shield but with an "X" mark within it?

**Comment by Atalonica** [comment]
Hello this is my suggestion to your request. @Rethic 
![unverified](https://user-images.githubusercontent.com/25279380/31442328-57068fc6-ae96-11e7-81aa-18cd6aad4092.png)
(icon is white, download to see).

**Comment by MrGrigri** [comment]
@Atalonica I don't believe that the checkmark is recognizable with the slash. 

![unverified](https://user-images.githubusercontent.com/4528551/31449597-8bbf1d96-ae64-11e7-8039-afdfe30a2da8.png)

![unverified-show](https://user-images.githubusercontent.com/4528551/31449600-8eb64c22-ae64-11e7-891b-955d657e95b2.png)

[unverified.zip](https://github.com/Templarian/MaterialDesign/files/1376137/unverified.zip)

**Comment by Rethic** [comment]
Thank you, Atalonica. But I do think Michael's shield with the X is easier to distinguish.

**Comment by Templarian** [comment]
[![security-off](https://materialdesignicons.com/icon/security-off)](https://materialdesignicons.com/icon/security-off) [![security-close](https://materialdesignicons.com/icon/security-close)](https://materialdesignicons.com/icon/security-close)
