### ISSUE TITLE
ZoomControls in/out buttons

### ISSUE THREAD

**Issue by Mirandadevs** [Templarian/MaterialDesign#249]
ZoomControls in/out buttons

**Comment by Templarian** [comment]
These exist: [magnify-minus](http://materialdesignicons.com/icon/magnify-minus) [magnify-plus](http://materialdesignicons.com/icon/magnify-plus).

That or [plus-circle](http://materialdesignicons.com/icon/plus-circle) and [minus-circle](http://materialdesignicons.com/icon/minus-circle).
