### ISSUE TITLE
Like icon doesn't exist

### ISSUE THREAD

**Issue by rijomonr** [Templarian/MaterialDesign#2491]

**Comment by mark-monserrat** [comment]
There is:

https://materialdesignicons.com/icon/thumb-up
https://materialdesignicons.com/icon/thumb-up-outline

**Comment by mark-monserrat** [comment]
Maybe this calls for an alias: 'like' (thumb-up) and 'dislike' (thumb-down)

**Comment by GreenTurtwig** [comment]
Aliases:
- `thumb-up` - `like`
- `thumb-down` - `dislike`
- `thumb-up-outline` - `like-outline`
- `thumb-down-outline` - `dislike-outline`
- `thumbs-up-down` - `like-dislike`
