### ISSUE TITLE
Phone icons from Android Device Manager

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2493]
Extracted from https://www.google.com/android/find

![image](https://user-images.githubusercontent.com/15905797/31285847-557febba-aab4-11e7-9572-3d968dbad8f9.png)
![image](https://user-images.githubusercontent.com/15905797/31285818-48cf1eea-aab4-11e7-98ad-1438b08a1b9e.png)

![image](https://user-images.githubusercontent.com/15905797/31285874-68a56d96-aab4-11e7-8b60-413fcc248d30.png)
![image](https://user-images.githubusercontent.com/15905797/31285890-70f46664-aab4-11e7-9b56-c66e24dd81d6.png)

![image](https://user-images.githubusercontent.com/15905797/31285907-7ab4685c-aab4-11e7-9338-d9771e173c0d.png)
![image](https://user-images.githubusercontent.com/15905797/31285915-810c157e-aab4-11e7-8f41-bd8fb3149a24.png)

![image](https://user-images.githubusercontent.com/15905797/31286225-6eb80eea-aab5-11e7-9921-a38ac1a81a9a.png)
![image](https://user-images.githubusercontent.com/15905797/31286231-7673dbd2-aab5-11e7-99f3-1c907372940f.png)

[phone-manage.zip](https://github.com/Templarian/MaterialDesign/files/1363194/phone-manage.zip)

**Comment by PeterShaggyNoble** [comment]
Looks like these have either since been added to the Stock set or we simply overlooked them at the time.

**Comment by CoDEmanX** [comment]
They are in the stock set indeed: https://material.io/icons/#ic_phonelink_erase etc.

![grafik](https://user-images.githubusercontent.com/1309249/39241038-ed137798-4885-11e8-8c8c-c158e202ede9.png)

And they are actually in the old spreadsheet from #420:

![grafik](https://user-images.githubusercontent.com/1309249/39241138-31e25c22-4886-11e8-89b5-895330adc9e6.png)

**Comment by Templarian** [comment]
[![cellphone-lock](https://materialdesignicons.com/icon/cellphone-lock)](https://materialdesignicons.com/icon/cellphone-lock) [![cellphone-settings-variant](https://materialdesignicons.com/icon/cellphone-settings-variant)](https://materialdesignicons.com/icon/cellphone-settings-variant)

**Comment by Templarian** [comment]
[![cellphone-erase](https://materialdesignicons.com/icon/cellphone-erase)](https://materialdesignicons.com/icon/cellphone-erase) [![cellphone-sound](https://materialdesignicons.com/icon/cellphone-sound)](https://materialdesignicons.com/icon/cellphone-sound)
