### ISSUE TITLE
router settings icon 

### ISSUE THREAD

**Issue by huajianjiang** [Templarian/MaterialDesign#2494]
we have some other settings icon, so why not router-settings icon?
![_20171007011223](https://user-images.githubusercontent.com/12984573/31289793-a552a95a-aafc-11e7-9575-3fae8f53bcb9.png)
thx

**Comment by GreenTurtwig** [comment]
Could be useful.
Just to mention, Google has a different icons for `router` than us.

**Comment by k5cents** [comment]
@GreenTurtwig Is anybody planning an audit of the MDI repo? Lots of inconsistencies with the official Google set like that. Some we do better, a lot we do worse. Even if we do slightly better I think there's something to be said to sticking to the source.

**Comment by PeterShaggyNoble** [comment]
@k5cents, a lot of that is due to the fact that this project predates the first official release from Google. If there are any specific icons that you feel would benefit from being updated to Google's stock icons, the best thing to do would be to open an issue for them.

**Comment by MrGrigri** [comment]
What if we added a new property on the icon that stated the Google name? Or we could add the Google name as an alias.

**Comment by CoDEmanX** [comment]
I would love if MDI could be used as a drop-in replacement of what Google offers, plus additional icons and variants...

**Comment by Templarian** [comment]
Their naming convention is very inconsistent... I think the idea is there, but might be more hassle as both grow.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/42566680-4239354a-84ff-11e8-9c48-2acf3dfe72d7.png)](https://github.com/Templarian/MaterialDesign/files/2184076/router-settings.zip)

**Comment by Templarian** [comment]
[![router-wireless](https://materialdesignicons.com/icon/router-wireless)](https://materialdesignicons.com/icon/router-wireless) [![router-wireless-settings](https://materialdesignicons.com/icon/router-wireless-settings)](https://materialdesignicons.com/icon/router-wireless-settings)
