### ISSUE TITLE
Open hand pointing right icon

### ISSUE THREAD

**Issue by flash76** [Templarian/MaterialDesign#2496]
There should be an icon with a hand open (for a handshake) pointing both left and right.

**Comment by goyney** [comment]
You could use `hand` rotated in each direction.

**Comment by PeterShaggyNoble** [comment]
There's also the recently added `charity` icon which might suit your needs:

[![charity](http://mdi.houseofdesign.ie/tools/preview/?icon=charity&action=link)](https://materialdesignicons.com/icon/charity)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @flash76, if neither @goyney's suggestion nor the `charity` icon suit your needs the please leave a comment and we'll revisit this issue.
