### ISSUE TITLE
Volleyball

### ISSUE THREAD

**Issue by agersoncgps** [Templarian/MaterialDesign#2497]
Looks like you have most major sports, but not this one. "google-chrome" and "google-earth" are close ;-)

![download-1](https://user-images.githubusercontent.com/336441/31322922-c3bb13ec-ac6d-11e7-9944-384edb213e58.png)
![download](https://user-images.githubusercontent.com/336441/31322923-c545a420-ac6d-11e7-9499-692d5ee28368.png)

**Comment by PeterShaggyNoble** [comment]
We could probably get away with aliasing this as waterpolo, too.

**Comment by PeterShaggyNoble** [comment]
Would the recently added `basketball` icon pass as a volleyball?

[![basketball](https://user-images.githubusercontent.com/15157491/33443702-1ff63c30-d5f0-11e7-97e8-fc878d5fc5ec.png)](https://materialdesignicons.com/icon/basketball)

**Comment by augustin32** [comment]
Volleyball
![volleyball24](https://user-images.githubusercontent.com/14167196/33795386-20bfcfb4-dce9-11e7-8939-a39f59cb2ee9.png)
![volleyball36](https://user-images.githubusercontent.com/14167196/33795388-22126174-dce9-11e7-9fce-c499b339d901.png)
![volleyball48](https://user-images.githubusercontent.com/14167196/33795389-2353f192-dce9-11e7-9020-9d1b18ef7265.png)
Volleyball Filled
![volleyball-filled24](https://user-images.githubusercontent.com/14167196/33795391-26143464-dce9-11e7-8b8b-3a732519d902.png)
![volleyball-filled36](https://user-images.githubusercontent.com/14167196/33795393-27c1e482-dce9-11e7-90cb-d511449af78c.png)
![volleyball-filled48](https://user-images.githubusercontent.com/14167196/33795398-2f7e6e16-dce9-11e7-951d-5a4328903633.png)
[volleyball.zip](https://github.com/Templarian/MaterialDesign/files/1544638/volleyball.zip)

**Comment by Templarian** [comment]
[![volleyball](https://materialdesignicons.com/icon/volleyball)](https://materialdesignicons.com/icon/volleyball)
