### ISSUE TITLE
Night/Light theme mode buttons or switch button

### ISSUE THREAD

**Issue by Mirandadevs** [Templarian/MaterialDesign#250]
Night/Light theme mode buttons or switch button

**Comment by Templarian** [comment]
Do you have an example of what this might look like?

**Comment by Mirandadevs** [comment]
http://www.lantus.com/images/hcp/large_icon_night_day.gif
http://www.cctv.co.th/image/bosch/bosch-icon-DayNight.png
http://www.bezpiecznie.com/gps/becker/icon_Day_Night.gif

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/theme-light-dark

Rough idea... not sure.

**Comment by CoDEmanX** [comment]
This one is quite nice too:

[![compare](https://materialdesignicons.com/icon/compare)](https://materialdesignicons.com/icon/compare)

**Comment by CoDEmanX** [comment]
Youtube has a dark / light theme toggle, which is similar but not identical to `brightness-4`:

![grafik](https://user-images.githubusercontent.com/1309249/42735752-df772670-8859-11e8-8633-c681902094d9.png)

Blue: Youtube's toggle icon
Orange overlay: brightness-4

Using the brightness icon base shape, here are three different re-creations: [theme-light-dark-variant.zip](https://github.com/Templarian/MaterialDesign/files/2195885/theme-light-dark-variant.zip)

1. Circle size like in the brightness icons, which is larger compared to Youtube's icon scaled down to the same base shape size
2. Smaller circle, to match the propertions of the Youtube icon
3. The original counter-shape subtracted from the base shape. Note that the "moon" in Youtube's icon was not created by subtracting a vertically center circle from another circle. The former circle is slightly moved up, and the corners of the moon have been tweaked or some precision loss occurred:

![grafik](https://user-images.githubusercontent.com/1309249/42735916-e5181ffa-885c-11e8-9635-f5835da2ace8.png)

![grafik](https://user-images.githubusercontent.com/1309249/42735948-59580ace-885d-11e8-8cbf-752de3ab2c00.png)
![grafik](https://user-images.githubusercontent.com/1309249/42735945-45ebeb2c-885d-11e8-86a0-42c15f7ec477.png)
![grafik](https://user-images.githubusercontent.com/1309249/42735937-27ea5adc-885d-11e8-8bf9-88367482e225.png)

**Comment by JamesCoyle** [comment]
Added aliases to existing icons so closing this out.
