### ISSUE TITLE
Alias Request: dribbble -> basketball

### ISSUE THREAD

**Issue by agersoncgps** [Templarian/MaterialDesign#2500]
The "dribble" icon looks like a "basketball" to me and would be a much more common search term.

**Comment by PeterShaggyNoble** [comment]
That's a brand icon and, as such, should only be used to represent [Dribble](https://dribbble.com/) (in the same way the Twitter icon should only be used to represent Twitter and not be used as a generic bird).

We have an open request for a basketball icon already (#1057) so I'm going to close this as a duplicate of that.
