### ISSUE TITLE
Refund

### ISSUE THREAD

**Issue by daviscodesbugs** [Templarian/MaterialDesign#2501]
**A card, currency, and/or bill denoting a return or refund.**

Examples:
![](https://www.wirecard.com/fileadmin/user_upload/wirecard/ContentIcons/W_P_CreditCardProcessing_RGB_920x690_weiss.png)
![](https://image.flaticon.com/icons/svg/31/31140.svg)
![](https://d30y9cdsu7xlg0.cloudfront.net/png/658720-200.png)

**Comment by daviscodesbugs** [comment]
This looks excellent!
We use the standard [credit card](https://materialdesignicons.com/icon/credit-card) icon to denote payment. Could you foresee a use case for a hybrid of the card and the "undo" circle like you did with the `cash-usd` symbol?

**Comment by MrGrigri** [comment]
After discussing it with the contributors, we've decided not to use the USD sign.  So I've created one for cash return and card return. Thoughts?

![cash-return](https://user-images.githubusercontent.com/4528551/31397349-fcc35d08-ada2-11e7-81cb-d4baaa70502d.png) ![card-return](https://user-images.githubusercontent.com/4528551/31397348-fca9850e-ada2-11e7-8b51-c5856dfbda21.png)

![cash-return](https://user-images.githubusercontent.com/4528551/31397391-2378445e-ada3-11e7-9950-4dbff6bd6b7d.png) ![card-return](https://user-images.githubusercontent.com/4528551/31397390-23631aa2-ada3-11e7-88ce-e065677d23a8.png)


[cash-usd-refund.zip](https://github.com/Templarian/MaterialDesign/files/1372605/cash-usd-refund.zip)

**Comment by JamesCoyle** [comment]
Could also use the left one for cashback/rebate and the right one for refund.

**Comment by CoDEmanX** [comment]
Some inspiration:

In my online banking, they use this icon:

![image](https://user-images.githubusercontent.com/1309249/31473000-40f46684-aef2-11e7-802a-d852c7528731.png)

For transactions they use this:

![image](https://user-images.githubusercontent.com/1309249/31473016-5790a0c4-aef2-11e7-8579-79d5e1a82863.png)

**Comment by daviscodesbugs** [comment]
I think the cash return and card return icons are great!

**Comment by Templarian** [comment]
[![credit-card-refund](https://materialdesignicons.com/icon/credit-card-refund)](https://materialdesignicons.com/icon/credit-card-refund) [![cash-refund](https://materialdesignicons.com/icon/cash-refund)](https://materialdesignicons.com/icon/cash-refund)
