### ISSUE TITLE
Cryptocurrencies

### ISSUE THREAD

**Issue by adrianTNT** [Templarian/MaterialDesign#2503]
Not sure how suggestions work but ...
Is it possible to get icons like PayPal and cryptocurrencies like Bitcoin and others ?

**Comment by JamesCoyle** [comment]
Do a search of the site and the issues...

**Comment by GreenTurtwig** [comment]
PayPal is a duplicate of: https://github.com/Templarian/MaterialDesign/issues/297
We already have Bitcoin and Ethereum.
[![](https://materialdesignicons.com/icon/currency-btc)](https://materialdesignicons.com/icon/currency-btc)[![](
https://materialdesignicons.com/icon/currency-eth)](https://materialdesignicons.com/icon/currency-eth)
Do you have any other a cryptocurrencies in mind?

**Comment by PeterShaggyNoble** [comment]
`currency-eth` could probably do with being aliased with its full name.

**Comment by adrianTNT** [comment]
Ooops, I did a search in list for "bitcoin" but there is an existent icon "btc", my bad. 
It was the btc that I needed most and paypal (that I see above it has a request).
Thank you all.

**Comment by JapanYoshi** [comment]
This is how I felt reading *yet another* PayPal request (before realizing the full currency name alias problem).
![Uploading Cuphead-Journalist.png…]()

**Comment by PeterShaggyNoble** [comment]
Strange, `currency-btc` is aliased as `bitcoin` so it should have shown up in your search.

**Comment by adrianTNT** [comment]
@PeterShaggyNoble yes, unless you search by CTRL+F in preview.html from downloaded zip file :)

**Comment by PeterShaggyNoble** [comment]
@adrianTNT, you might find [this](https://petershaggynoble.github.io/MDI-Sandbox/) of use, so.

**Comment by volrath911** [comment]
any MDI icons on other crypto currencies? Ripple maybe, QTUM? others?

**Comment by JamesCoyle** [comment]
We're only gonna consider accepting currencies that have over 100,000 transactions per day. Anything lower than that is way too niche at the moment.

**Comment by MrGrigri** [comment]
That's a good benchmark for now.

**Comment by JamesCoyle** [comment]
Unique transactions as tracked here: https://bitinfocharts.com

**Comment by GreenTurtwig** [comment]
`currency-eth` has been given the alias `ethereum`.
