### ISSUE TITLE
Icon Request: GIF

### ISSUE THREAD

**Issue by muigukenneth** [Templarian/MaterialDesign#2504]
Can you please add this icon ? Example of GIF
![ic_gif](https://user-images.githubusercontent.com/4389000/31387929-ea9ff24e-add4-11e7-93d6-730feb789347.png)
 image

**Comment by PeterShaggyNoble** [comment]
We try to avoid adding language-specific icons as best we can. `animation` could be an option but if you let us know your use-case, we might be able to point you towards a more suitable icon.

[![](https://materialdesignicons.com/icon/animation)](https://materialdesignicons.com/icon/animation)

**Comment by muigukenneth** [comment]
@PeterShaggyNoble I wanted to use any icon that represents a gif image. Any suggestions from this archive?

**Comment by CoDEmanX** [comment]
It's actually a stock Google icon and should be added IMO #1451
