### ISSUE TITLE
can not find non-orange icons at material.io/icons/

### ISSUE THREAD

**Issue by musicformellons** [Templarian/MaterialDesign#2506]
For example on the mdi site I see three cake icons (non orange):
1) cake
2) cake-variant
3) cake-layered

which the popup says are from google. On the material.io/icons/ site and in the google repo I only find one cake icon called 'cake', which is similar to the 'cake-variant' on the mdi site.

Are there original google material icons that are elsewhere to be found, because I am confused? I would also expect the names to be similar for similar icons.

**Comment by Templarian** [comment]
Google has tons of icons they do not provide through their open source package. Since Google still produced them we still attribute them correctly.

This project existed before material.io existed 😸 So the icon may have already existed with that name, so we added it as a variant.
