### ISSUE TITLE
YouTube Gaming

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2507]
Came across the YouTube Gaming icon while looking for the YouTube TV one, thought someone might have a use for it. Again, it'll probably need some work before it can be added (if it's to be added), so here are 3 versions ([Zip](https://github.com/Templarian/MaterialDesign/files/1376255/youtube-gaming.zip)):

- [Original from YouTube](https://petershaggynoble.github.io/MDI-Sandbox/svg/original/youtube-gaming.svg)
- [Edited to a single path](https://petershaggynoble.github.io/MDI-Sandbox/svg/edited/youtube-gaming.svg)
- [Optimised with SVGOMG](https://petershaggynoble.github.io/MDI-Sandbox/svg/optimised/youtube-gaming.svg)

**Comment by Templarian** [comment]
[![youtube-gaming](https://materialdesignicons.com/icon/youtube-gaming)](https://materialdesignicons.com/icon/youtube-gaming)
