### ISSUE TITLE
RFID icons

### ISSUE THREAD

**Issue by neorevx** [Templarian/MaterialDesign#2508]
Hi,

Here are some little suggestions (RFID icons):

rfid single tag
rfid multiple tags
rfid device (managment device)
rfid write tag
rfid read tag
rfid lock tag
rfid kill tag
rfid error tag

Thank you.

**Comment by PeterShaggyNoble** [comment]
Can you provide examples, please? I suspect some, if not most, of these could be covered by existing icons.

**Comment by neorevx** [comment]
I don't know if exists some standard icon. I guess not.

RFID tag remeber to me a label tag
![image](https://user-images.githubusercontent.com/21008550/31454455-debe6c32-ae8b-11e7-893c-b5b1d87b0480.png)
**with RF wave** 
![image](https://user-images.githubusercontent.com/21008550/31454504-09ac30fa-ae8c-11e7-8c9c-4b3fb909d1d0.png)
or something like
![image](https://user-images.githubusercontent.com/21008550/31454041-892d1f12-ae8a-11e7-8d35-262182f0a6b6.png)

RFID device remeber me @Google remote icon: 
![image](https://user-images.githubusercontent.com/21008550/31454428-ca26e4a2-ae8b-11e7-85d6-12a08ad7407c.png)

Versions suggestions:
**multiple**: rfid tag stacked;
**write**: tag with up arrow;
**read**: tag with down arrow;
**lock/unlock**: tag with padlock (closed/opened);
**kill** and **error:** tag with "X".

What do you think?

**Comment by MrGrigri** [comment]
All of the following already exist:

![tag](https://materialdesignicons.com/icon/tag) ![wifi](https://materialdesignicons.com/icon/wifi) ![nfc-variant](https://materialdesignicons.com/icon/nfc-variant) ![remote](https://materialdesignicons.com/icon/remote) ![tag-multiple](https://materialdesignicons.com/icon/tag-multiple) ![tag-remove](https://materialdesignicons.com/icon/tag-remove)

As far as 'write', 'read', and 'lock/unlock'; they seem a bit too specific.

**Comment by neorevx** [comment]
Hi, thank you.

Well, except
https://user-images.githubusercontent.com/21008550/31454041-892d1f12-ae8a-11e7-8d35-262182f0a6b6.png
all others I got from repository.

I did not found nfc-variant before. It seems correct for rfid.
But multiple tag and "tag-remove" don't.
The image of "tag-multiple" is like label tags, not rfid tags.

**write, read, lock/unlock and kill** are commands for rfid tags.
It's is specific for rfid tag, but not specific for a project.
You can write, read, lock and kill generic writeable rfid tags.

**Comment by MrGrigri** [comment]
It seems to me you need to rethink your UI. If everything is concentrated around RFID, then you could use more generic icons for everything. In other words, you could use a lock, and unlock icon because the user will know that you are locking and unlocking a RFID tag. Does that make sense?

**Comment by neorevx** [comment]
It's make sense for project based on RFIDs.
My project is not concentrated around RFID. I'm devloping an application to manage tire in vehicles.
Some tires has RFID tag and it should be read.
But there is a lot of anothers operations on my device and app: read pressure, read tread depth, fill tire mark, manage position, ... only read option will be confuse.

But your post about "nfc-variant" icon help me a lot. Thank you.
Some icons I explained only for suggestions :D

**Comment by CoDEmanX** [comment]
@MrGrigri wouldn't actions related to RFID be carried out in a certain section of your UI, or maybe even a popup window or something similar?

I think it would be better to use the `nfc-variant` icon for that component, and use generic icons for deletion etc. for all actions related to RFID.

Can you share some wireframes of the intended interface?

**Comment by MrGrigri** [comment]
@CoDEmanX I believe you meant to tag @neorevx.
