### ISSUE TITLE
Switch Account (Variant)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2510]
Lifted this off YouTube, if anyone wants it ([Zip](https://github.com/Templarian/MaterialDesign/files/1378959/switch-account.zip)):

- [Original](https://petershaggynoble.github.io/MDI-Sandbox/svg/original/switch-account.svg)
- [Optimised with SVGOMG](https://petershaggynoble.github.io/MDI-Sandbox/svg/optimised/switch-account.svg)

![account-switch-variant](https://user-images.githubusercontent.com/15157491/34716672-734f555e-f528-11e7-89f1-8c1ac9b9bc14.png)

**Comment by Templarian** [comment]
[![account-box-multiple](https://materialdesignicons.com/icon/account-box-multiple)](https://materialdesignicons.com/icon/account-box-multiple)
