### ISSUE TITLE
Replace camcorder in favor of video

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2512]
The icon to represent video is in the set twice:
[![](https://materialdesignicons.com/icon/video)](https://materialdesignicons.com/icon/video)[![](https://materialdesignicons.com/icon/camcorder)](https://materialdesignicons.com/icon/camcorder)

**Comment by JamesCoyle** [comment]
Haha. Maybe we could alter camcorder a bit to make it look more like a handheld camcorder instead.

**Comment by goyney** [comment]
We have 3 variants of `camcorder`. We have way more variants of `video`. Therefore, we need to do the following:

- [ ] Remove `camcorder`
- [ ] Rename `camcorder-box` => `video-box`
- [ ] Rename `camcorder-off` => `video-off`
- [ ] Rename `camcorder-box-off` => `video-box-off`
- [ ] Alias `video` => `camcorder`
- [ ] Alias `video-box` => `camcorder-box`
- [ ] Alias `video-off` => `camcorder-off`
- [ ] Alias `video-box-off` => `camcorder-box-off`

**Comment by Templarian** [comment]
Agree with this change. Just replace `camcorder` with another icon. Feel free to do this in this release.

**Comment by Templarian** [comment]
Camcorder could be changed to an icon like:

![image](https://user-images.githubusercontent.com/338885/73604471-02d1da00-4557-11ea-998e-ad221d2d6125.png) ![image](https://user-images.githubusercontent.com/338885/73604477-18df9a80-4557-11ea-845d-d3d3b6338a9e.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/73604626-4d545600-4559-11ea-8ddf-e5f760a6ef79.png)

**Comment by goyney** [comment]
Updated `camcorder`. Renamed all other `camcorder` variants `video`.
