### ISSUE TITLE
Several battery-charging percentages missing

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2513]
`battery-charging-outline`, `battery-charging-10`, `battery-charging-50` and `battery-charging-70` are missing from the set. Both the other battery icons (normal and wireless charging) have related icons.

**Comment by Templarian** [comment]
This is why I shouldn't be adding icons late at night. Fixed.

[![battery-charging-10](https://materialdesignicons.com/icon/battery-charging-10)](https://materialdesignicons.com/icon/battery-charging-10) [![battery-charging-50](https://materialdesignicons.com/icon/battery-charging-50)](https://materialdesignicons.com/icon/battery-charging-50) [![battery-charging-70](https://materialdesignicons.com/icon/battery-charging-70)](https://materialdesignicons.com/icon/battery-charging-70) [![battery-charging-outline](https://materialdesignicons.com/icon/battery-charging-outline)](https://materialdesignicons.com/icon/battery-charging-outline)
