### ISSUE TITLE
Record Circle (+Outline)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2514]
To go with the other control icons with `circle(-outline)` variants, if anyone needs them.

[record-circle.zip](https://github.com/Templarian/MaterialDesign/files/1382359/record-circle.zip)

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX, this is for media player controls, rather than a vinyl record.

**Comment by Templarian** [comment]
Added. 😃
