### ISSUE TITLE
Add map / remove map

### ISSUE THREAD

**Issue by xaviergonz** [Templarian/MaterialDesign#2515]
Like https://materialdesignicons.com/icon/map but with a '+' and a '-' to its side

**Comment by PeterShaggyNoble** [comment]
Thanks to @GreenTurtwig for the help on these.

[map-plus-minus.zip](https://github.com/Templarian/MaterialDesign/files/1394122/map-plus-minus.zip)

**Comment by xaviergonz** [comment]
Awesome! are they going to be added to the repo?

**Comment by Templarian** [comment]
[![map-plus](https://materialdesignicons.com/icon/map-plus)](https://materialdesignicons.com/icon/map-plus) [![map-minus](https://materialdesignicons.com/icon/map-minus)](https://materialdesignicons.com/icon/map-minus)

@PeterShaggyNoble Did @GreenTurtwig make these or you? Not sure how to interpret your comment above.

**Comment by GreenTurtwig** [comment]
They're @petershaggynoble 's. 🐈
