### ISSUE TITLE
message-clock

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#2517]
I'm thinking the `message-text` and/or `message-image` with the `timer-sand` or `timer` icons either inside the bubble or down in the corner (kind of as seen on `email-secure`).

With the prevalence of timed encrypted text messages and snapchat-esque timed photo messaging, I can see a use fort these types of icons.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/63066551-a6abc880-bed8-11e9-9ec3-7bd5775bf66f.png)
![image](https://user-images.githubusercontent.com/1015040/63066559-add2d680-bed8-11e9-8e06-c001e01aa551.png)

[message-text-clock.zip](https://github.com/Templarian/MaterialDesign/files/3503944/message-text-clock.zip)

**Comment by kiernann** [comment]
Completely forgot about this! Very nice. Any chance of getting the `message-image` version?

**Comment by goyney** [comment]
[![message-text-clock](https://materialdesignicons.com/icon/message-text-clock)](https://materialdesignicons.com/icon/message-text-clock)[![message-text-clock-outline](https://materialdesignicons.com/icon/message-text-clock-outline)](https://materialdesignicons.com/icon/message-text-clock-outline)

Cannot add the `image` variant. Too much of the `image` is cut off by the clock to and it makes it indistinguishable.
