### ISSUE TITLE
Double / Single Bed

### ISSUE THREAD

**Issue by thinkwareltd** [Templarian/MaterialDesign#2519]
Icon for master bedroom, bed 1, bed 2, bed 3, bed 4, bed 5
so bed 1-5 = single bed with digit indicating 1,2,3,4 or 5

Useage: Home automation to signify master bedroom (double), bedroom 1, bedroom 2...5

Any thoughts?

**Comment by Templarian** [comment]
We don't really add numeric icons. Just `-multiple` and singular.

Not sure on the design to show double/full/king/queen though. Might be a way.

**Comment by thinkwareltd** [comment]
Was thinking a bed with two persons for double/full/king/queen/master bedroom
Was thinking single bed for other bedrooms possibly

**Comment by Templarian** [comment]
That might be easier to represent.

**Comment by FezVrasta** [comment]
I like the icon used in the Hue app. 

![image](https://user-images.githubusercontent.com/5382443/39959662-3f38d986-5615-11e8-805c-895c56c02666.png)

**Comment by CoDEmanX** [comment]
![bed-love](https://user-images.githubusercontent.com/1309249/40001242-189b6cd8-578e-11e8-8618-9b309f98afe7.png)

¯\\\_(ツ)\_/¯

**Comment by PeterShaggyNoble** [comment]
These are Google's new `king_bed` and `single_bed` icons:

[![king_bed](https://user-images.githubusercontent.com/15157491/52490723-49e3f400-2bbd-11e9-9d7c-e30bef1897b6.png)](https://github.com/Templarian/MaterialDesign/files/2845902/king-bed.zip) [![single_bed](https://user-images.githubusercontent.com/15157491/52490756-5ec08780-2bbd-11e9-8de0-5ada9bd0af35.png)](https://github.com/Templarian/MaterialDesign/files/2845906/single-bed.zip)

**Comment by MrGrigri** [comment]
I think we could use the style on the right as an outlined variant, the style on the left as the filled variant, and use the widths as the two sizes. Thoughts?

**Comment by PeterShaggyNoble** [comment]
Agreed. I also suggest we use the one on the right as a double bed and then remove the partition on the headboard and make it a bit narrower to be a single bed.

**Comment by MrGrigri** [comment]
Yes.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/52496205-fc9d5d80-2b8f-11e9-9d14-29f1af52e9cd.png) ![image](https://user-images.githubusercontent.com/4528551/52496234-0d4dd380-2b90-11e9-9c00-e9d93f3a2f23.png)

![image](https://user-images.githubusercontent.com/4528551/52496322-41c18f80-2b90-11e9-86f1-8562a154bae1.png) ![image](https://user-images.githubusercontent.com/4528551/52496343-4dad5180-2b90-11e9-9bd6-867821facf86.png)

![image](https://user-images.githubusercontent.com/4528551/52496368-5ef65e00-2b90-11e9-993b-acaadc55a2c7.png) ![image](https://user-images.githubusercontent.com/4528551/52496391-6f0e3d80-2b90-11e9-88dc-4bc5f3525c39.png)

![image](https://user-images.githubusercontent.com/4528551/52496428-82b9a400-2b90-11e9-9935-b8b8254fc2ad.png) ![image](https://user-images.githubusercontent.com/4528551/52496459-949b4700-2b90-11e9-82e6-09ab73a0da6e.png)

---
#### SVG

[bed.zip](https://github.com/Templarian/MaterialDesign/files/2846256/bed.zip)

**Comment by Templarian** [comment]
The single bed is probably going to be too narrow. It almost looks like luggage.

**Comment by MrGrigri** [comment]
I believe context will help.

**Comment by CoDEmanX** [comment]
The single beds 2dp wider look much more like beds:

![grafik](https://user-images.githubusercontent.com/1309249/53642668-99ed2e00-3c32-11e9-8c70-b8a6b7a7a70f.png)
![grafik](https://user-images.githubusercontent.com/1309249/53642720-a4a7c300-3c32-11e9-9212-938feb83b18c.png)

[bed-single-2dp-wider.zip](https://github.com/Templarian/MaterialDesign/files/2919680/bed-single-2dp-wider.zip)

If it's too hard to see the differences in width then we could consider to add arrows to queen/king size beds... but not really a fan of that idea:

![grafik](https://user-images.githubusercontent.com/1309249/53643171-afaf2300-3c33-11e9-8fec-12e594995536.png)
![grafik](https://user-images.githubusercontent.com/1309249/53643303-03217100-3c34-11e9-962d-37c80fe4c114.png)

**Comment by MrGrigri** [comment]
Yeah, I tried to help distinguish the two by changing the headboard style.

**Comment by goyney** [comment]
All 4 sizes in filled and outline variants added. Used @CoDEmanX's singles.
