### ISSUE TITLE
Offline Pin / Downloaded

### ISSUE THREAD

**Issue by ursusursus** [Templarian/MaterialDesign#2520]
Id like to suggest a spin on the download icon, representing downloadED state. Download icon is a down arrow with underline, downloaded icon should be checkmark with underline

(I think chrome does this)

Thanks!

**Comment by PeterShaggyNoble** [comment]
This is [`offline pin`](https://material.io/icons/#ic_offline_pin) from the stock icons.

**Comment by ursusursus** [comment]
that will do, thanks!

**Comment by GreenTurtwig** [comment]
We'll leave this open until it has been added to the set. 🐈

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49034326-a9fef880-f17f-11e8-9edc-ce94abdee34d.png)![image](https://user-images.githubusercontent.com/1015040/49034362-c7cc5d80-f17f-11e8-9d68-08892e555278.png)

[check-underline-circle.zip](https://github.com/Templarian/MaterialDesign/files/2616867/check-underline-circle.zip)

**Comment by Templarian** [comment]
Added. Also added `check-underline`.
