### ISSUE TITLE
Robot Lawnmower

### ISSUE THREAD

**Issue by trycoon** [Templarian/MaterialDesign#2522]
A robotmower icon would be nice. Could be used in robotmower apps and home automation softwares.
https://www.google.se/search?q=robot+mower&source=lnms&tbm=isch

**Comment by kmohl** [comment]
Maybe something like this?

![robot-mower-outline](https://user-images.githubusercontent.com/24955518/31822690-df612dbc-b5a9-11e7-9588-df627f276d79.png)
[robot-mower-outline.zip](https://github.com/Templarian/MaterialDesign/files/1402019/robot-mower-outline.zip)

**Comment by itchaboy** [comment]
Here's something I put together. Could use work/adjusting.

[robomower.zip](https://github.com/Templarian/MaterialDesign/files/1418617/robomower.zip)

**Comment by trycoon** [comment]
Thanks @kmohl, it's actually quite cute, but I wouldn't say it resambles a robotmower. I asked the guys at work what they thing it represent, and they was thinking about a car, someone said Wall-E (https://www.google.se/search?q=wall-e&source=lnms&tbm=isch) which is a bit closer but none thought about a mower. Maybe we could save it as a generic robot instead? Thanks for the effort!

**Comment by trycoon** [comment]
@itchaboy Thanks, that more like the thing I'm looking for.

**Comment by itchaboy** [comment]
@trycoon Thanks! Just tried to copy the general shape you see shape, turns out I got the guidelines wrong... Gonna post another soon.

**Comment by kmohl** [comment]
Thanks @trycoon, I wanted it to look more quirky but now I did it as closes as could to the real thing, respecting the material guidelines. I didn't quite succeed in my previous attempt, hope I did it this time. What do you think?
![robomower](https://user-images.githubusercontent.com/24955518/32095262-de408f8c-bb02-11e7-846c-f6c7fe4d9988.png)
[robomower.zip](https://github.com/Templarian/MaterialDesign/files/1421312/robomower.zip)

**Comment by itchaboy** [comment]
@kmol I like this one! Not bad. Though I'd like to see what it'd look like a little thinner virtically.

**Comment by trycoon** [comment]
I agree with @itchaboy, Its a bit on the high side. Robot mowers do look different between the brands, but its quite common that they are flat with big wheels at the back and smaller ones at the front. The body of the mower usually get a bit slimmer towards the front of the mower. Example: http://www.autolawnmow.com/wp-content/uploads/2014/08/Robot-Lawn-Mower-S510.jpg

**Comment by kmohl** [comment]
@trycoon I too agree with @itchaboy, thinner is better. Initially, I wanted to avoid the front wheel to keep the shape as simple as possible, but it looks better with the wheel, so I here it is.
![robomower](https://user-images.githubusercontent.com/24955518/32163635-32bfbe8c-bd5d-11e7-9617-e6a370fe3613.png)
[robomower.zip](https://github.com/Templarian/MaterialDesign/files/1426651/robomower.zip)

**Comment by itchaboy** [comment]
@trycoon Very nice! I think that fits the bill nicely.

**Comment by Templarian** [comment]
Added to the general contributor account. @kmohl let me know when you have 5 icons so I can create a contributor account.
