### ISSUE TITLE
Curtains (Open and Closed)

### ISSUE THREAD

**Issue by mories76** [Templarian/MaterialDesign#2523]
Would be nice to see some icons for Curtains open and closed, for use in Home Automation software.

**Comment by itchaboy** [comment]
So I made a couple. My first time, so critiques are very much welcome.

[curtains.zip](https://github.com/Templarian/MaterialDesign/files/1418555/curtains.zip)

![curtain-closed](https://user-images.githubusercontent.com/23114700/32055734-9b233600-ba30-11e7-98a1-1e9f9aecb954.png)
![curtain-closed-alternative](https://user-images.githubusercontent.com/23114700/32055736-9b341236-ba30-11e7-9af0-ec03dd2cb925.png)
![curtain-open](https://user-images.githubusercontent.com/23114700/32055737-9b454a56-ba30-11e7-8337-8069b29c0b2a.png)

**Comment by MrGrigri** [comment]
I'm sorry, but those are not MD at all. Could you try something more simple?

**Comment by itchaboy** [comment]
Really? I thought I followed them... the strokes end in flat edges, the widths are 1px, (at least the top one follows this) Could you be more specific about what doesn't work so that I can change them?

**Comment by MrGrigri** [comment]
> "Each icon is reduced to its minimal form, with every idea edited to its essence. The designs ensure readability and clarity even at small sizes."
[MD Guidelines](https://material.io/guidelines/style/icons.html#icons-system-icons)

In essence, they need to be simplified, yet still recognizable. All widths are 2dp (or 2 pixels), not one, with only a few exceptions for optical corrections. 

When I first saw the icons in the email - without looking at the title - I thought they were some sort of pillar, not curtains. I believe that this icon is going to be very difficult to make following the guidelines.

**Comment by MrGrigri** [comment]
I am by no means saying your icons are not good. After looking at what they represent, I could identify them as such. All I'm saying is they don't fit the guidelines.

**Comment by itchaboy** [comment]
2px not 1... gotcha. I will try to simplify, I see how that can become difficult.

**Comment by itchaboy** [comment]
@MrGrigri Are widths between strokes also supposed to be 2px?

**Comment by JamesCoyle** [comment]
This is a tough one really. Playing around I was thinking maybe something like this could work but it's still pretty hard to recognize and still uses 1px strokes. 

![image](https://user-images.githubusercontent.com/10384436/32063148-5dfe60e0-ba6e-11e7-9c4e-65c328a7eedc.png)![image](https://user-images.githubusercontent.com/10384436/32063158-63250600-ba6e-11e7-9cb9-04d945fa3914.png)
![image](https://user-images.githubusercontent.com/10384436/32063254-97ebc680-ba6e-11e7-8903-23a598261042.png)![image](https://user-images.githubusercontent.com/10384436/32063259-9b97b6d6-ba6e-11e7-8bbd-2ac310cd666e.png)

**Comment by itchaboy** [comment]
Here's what I went with, has one 1px stroke for signifying blinds/curtains in my opinion vs. something more generic like a pillar.

[curtains v2.zip](https://github.com/Templarian/MaterialDesign/files/1419105/curtains.v2.zip)

**Comment by GreenTurtwig** [comment]
Something like this is instantly recognisable: https://www.iconfinder.com/icons/1699467/curtain_theater_theatre_icon

**Comment by pangit99** [comment]
Would love to see some curtains in the official MD library!

**Comment by P-Verbrugge** [comment]
Any progress on this? Looking for icons myself too.

**Comment by steodor** [comment]
I see there's still demand, so i'd like to start based on @GreenTurtwig's suggestion. What do you think?
![image](https://user-images.githubusercontent.com/4397338/108437911-e33b4b80-7256-11eb-8b7a-f2a63422eced.png)![image](https://user-images.githubusercontent.com/4397338/108437914-e5050f00-7256-11eb-9895-75caa9c927db.png)
[curtains.zip](https://github.com/Templarian/MaterialDesign/files/6006685/curtains.zip)

**Comment by steodor** [comment]
Oh, and an open variant with a larger gap between curtains at the top:
![image](https://user-images.githubusercontent.com/4397338/108438330-bdfb0d00-7257-11eb-9fcf-6bb0e63d2931.png)
[curtains-open-2.zip](https://github.com/Templarian/MaterialDesign/files/6006709/curtains-open-2.zip)

**Comment by pangit99** [comment]
Yes, very nice. Personally I prefer the second version with the larger gap

**Comment by steodor** [comment]
@pangit99 yeah, me too, but i think they can be even better if the top part of the side curtains wouldn't be straight but instead would follow the curves of the top part. I will try to do that these days if i get some time, stay tuned :)

**Comment by steodor** [comment]
Ok, so i managed to tweak the icons a bit. I also renamed the open ones and switched them around, so now `curtains-open` are the fully open curtains with the big gap at the top, while the one with the small gap is now `open-variant`. Although the latter is not a great fit for home automation (hence variant), i feel it would still make sense for the library as it may be a better fit in other scenarios (aliased maybe like `theater` or `stage-curtains` or something, not sure).
![image](https://user-images.githubusercontent.com/4397338/108673794-f7987600-74ec-11eb-9f6b-7f62519888a4.png)![image](https://user-images.githubusercontent.com/4397338/108673811-febf8400-74ec-11eb-9cd6-d92be350a2a5.png)![image](https://user-images.githubusercontent.com/4397338/108673817-01ba7480-74ed-11eb-9877-3ee03f97080e.png)
### SVG: [curtains.zip](https://github.com/Templarian/MaterialDesign/files/6020029/curtains.zip)

**Comment by bessarabov** [comment]
Super! Thank you for your work! Really hope to see that icons in the nearest mdi release.

**Comment by Mariusthvdb** [comment]
though romantic case these are, they are a bit over the top for a more business like setting.
something  like reorder-vertical but then more fletched out to use the full icon width for closed, and only left and right side (clear in the middle) for opened would be very welcome too? 
They would have the additional option of representing vertical 'lamellen' (slats?)


see:

![VVB_1483_1 2e16d0ba fill-1680x580](https://user-images.githubusercontent.com/33354141/115253765-fbcbc300-a12c-11eb-8893-9fc7daf04836.jpg)

should I ask in a separate issue, or is it allowed to be additional here?
thanks for considering

**Comment by goyney** [comment]
[![curtains](https://materialdesignicons.com/icon/curtains)](https://materialdesignicons.com/icon/curtains)[![curtains-closed](https://materialdesignicons.com/icon/curtains-closed)](https://materialdesignicons.com/icon/curtains-closed)

**Comment by pangit99** [comment]
Finally! Thanks!
