### ISSUE TITLE
ER Diagram Symbols

### ISSUE THREAD

**Issue by ra-V-en** [Templarian/MaterialDesign#2524]
It would be nice to see Icons for Relationship on Database-Tables. I search them for an Web-Application

**Comment by MrGrigri** [comment]
Would the closed issue #989 work? These represent the different table joinings.

**Comment by ra-V-en** [comment]
I have found some Ideas here:

[https://s3.amazonaws.com/nettuts/636_mysql/relationshipSymbols.png](
https://s3.amazonaws.com/nettuts/636_mysql/relationshipSymbols.png)

**Comment by MrGrigri** [comment]
The problem with those icons is they are arrows; from one DB entry to another. In other words, they would require a this with that type approach in the UI and not a stand-alone approach. 

The small example where this approach would work is a legend in some sort of GUI. If this is what you are needing then I believe it could be considered.

**Comment by ra-V-en** [comment]
Yes, this is what I need

**Comment by MrGrigri** [comment]
[Here](//www.lucidchart.com/pages/ER-diagram-symbols-and-meaning#section-2) is the reference for ERD (Entity-Relationship Diagram) Symbols.

**Comment by PeterShaggyNoble** [comment]
Duplicate of #720
