### ISSUE TITLE
Icon Request: HackerRank

### ISSUE THREAD

**Issue by twrl** [Templarian/MaterialDesign#2525]
An icon for HackerRank would be handy. Their logo is at https://hrcdn.net/hackerrank/assets/brand/h_mark_sm-2b74ffcaf85d7091a6301c30d6c411c5.svg 

![HackerRank](https://hrcdn.net/hackerrank/assets/brand/h_mark_sm-2b74ffcaf85d7091a6301c30d6c411c5.svg)

**Comment by MrGrigri** [comment]
I believe this will be too niche for this repo.

**Comment by PeterShaggyNoble** [comment]
I agree with @MrGrigri; too niche for inclusion at this time. It may be revisited, though, should a dedicated brand icon pack be created.

**Comment by mahmoudmubarak** [comment]
Based on having some specialized icons to add in tech-resumes, having HackRank icon may be very useful. Hope you can reconsider it.

**Comment by PeterShaggyNoble** [comment]
For those in *need* of this icon, it's [available on Simple Icons](https://simpleicons.org/?q=hackerrank).
