### ISSUE TITLE
Printer off

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2526]
[printer-off.zip](https://github.com/Templarian/MaterialDesign/files/1388149/printer-off.zip)

**Comment by Templarian** [comment]
[![printer-off](https://materialdesignicons.com/icon/printer-off)](https://materialdesignicons.com/icon/printer-off)

**Comment by Templarian** [comment]
@CoDEmanX By the way, agreed. I extended the line 1dp in both directions.
