### ISSUE TITLE
Form elements

### ISSUE THREAD

**Issue by lirui0407** [Templarian/MaterialDesign#2527]
I viewed all of MaterialDesign icons,I noticed that there were less icons represent Form Elements such as Inputbox symbol/single or multi Options symbol/Number toggle symbol/Color Picker symbol/Date Picker symbol/Range picker toggle symbol……
Please consider add them.
:)

**Comment by PeterShaggyNoble** [comment]
We have all of these already:

- [Input](https://materialdesignicons.com/icon/textbox) ([Password input](https://materialdesignicons.com/icon/textbox-password))
- [Options](https://materialdesignicons.com/icon/format-list-checks) (or [various checkboxes](https://petershaggynoble.github.io/MDI-Sandbox/?filter=checkbox))
- [Various numbers](https://petershaggynoble.github.io/MDI-Sandbox/?filter=num)
- [Colour picker](https://materialdesignicons.com/icon/eyedropper)
- [Various calendars](https://petershaggynoble.github.io/MDI-Sandbox/?filter=calendar)
- [`toggle-switch`](https://materialdesignicons.com/icon/toggle-switch) (or [`toggle-switch-off`](https://materialdesignicons.com/icon/toggle-switch-off)) should would for range input, if used in context.

If any of these *don't* suit your needs, let us know (with examples) what you are looking for and we'll reopen this issue.
