### ISSUE TITLE
Marital Status

### ISSUE THREAD

**Issue by HeySmartySukh** [Templarian/MaterialDesign#2528]
Marriage Status

**Comment by PeterShaggyNoble** [comment]
Would `ring` or `account-multiple` suit your needs? If not, please provide an example of what you're looking for.

[![](https://materialdesignicons.com/icon/ring)](https://materialdesignicons.com/icon/ring) [![](https://materialdesignicons.com/icon/account-multiple)](https://materialdesignicons.com/icon/account-multiple)

**Comment by PeterShaggyNoble** [comment]
@HeySmartySukh, could you provide more information and some examples, please?

**Comment by CoDEmanX** [comment]
There are symbols in genealogy:

![image](https://user-images.githubusercontent.com/1309249/37433752-71190ed2-27dd-11e8-98cc-a591f40d569d.png)

Translation:

- born
- baptized
- died
- buried
- divorced
- extramarital connection
- married
- extramarital birth
- engaged
- dead birth
- fallen (killed in action)

In older publications you might also find the following symbols:
- baptized
- married
- buried
- born
- died

**Comment by JapanYoshi** [comment]
Some I could find:
born - ``asterisk`` or ``multiplication``
baptized - ``tilde``
buried - ``crop-landscape``
married - ``set-none``
engaged - ``checkbox-blank-circle-outline`` or ``circle-outline`` or ``panorama-fisheye`` or ``radiobox-blank``

**Comment by goyney** [comment]
Since we never got any more information on the original request, I'm going to close this. @HeySmartySukh, if you still need something from this request, feel free to elaborate more and we'll consider reopening it. Thanks!
