### ISSUE TITLE
Separate thumbs-up / thumbs-down

### ISSUE THREAD

**Issue by xaviergonz** [Templarian/MaterialDesign#2530]
Like https://materialdesignicons.com/icon/thumbs-up-down but separated into two icons

**Comment by GreenTurtwig** [comment]
I don't mean to be rude but, did you do a search?

[![](https://materialdesignicons.com/icon/thumb-up)](https://materialdesignicons.com/icon/thumb-up)[![](https://materialdesignicons.com/icon/thumb-down)](https://materialdesignicons.com/icon/thumb-down)
[![](https://materialdesignicons.com/icon/thumb-up-outline)](https://materialdesignicons.com/icon/thumb-up-outline)[![](https://materialdesignicons.com/icon/thumb-down-outline)](https://materialdesignicons.com/icon/thumb-down-outline)

**Comment by xaviergonz** [comment]
My bad, I searched for "thumbs-up" instead of "thumb-up" 😢

**Comment by GreenTurtwig** [comment]
Haha, no worries. More be worth giving them an alias.

**Comment by xaviergonz** [comment]
Or maybe implementing fuzzy search on the site :)

**Comment by PeterShaggyNoble** [comment]
Aliases added.
