### ISSUE TITLE
Set terminology for table join icons

### ISSUE THREAD

**Issue by gabrielgrant** [Templarian/MaterialDesign#2533]
the table join icons added in #989 seems like they should be aliased using set and relational algebra terminology

specifically:
set-all -> set-union; set-or; full-outer-join
set-center -> set-intersection; set-and; inner-join
set-center-right -> right-outer-join
set-left -> difference-left
set-left-center -> left-outer-join
set-left-right -> exclusion; set-xor
set-none -> set-null; set-not(?)
set-right -> difference-right

**Comment by Templarian** [comment]
When these get aliased. I think prefixing `sql-` might help a little.

**Comment by gabrielgrant** [comment]
yes, for the "join" options. these are also useful for set operations that don't actually have anything to do with SQL, so not sure the prefix is needed for the set terminology options (though i guess it doesn't hurt, does it?)

**Comment by PeterShaggyNoble** [comment]
Anything missing/incorrect on the list below?

Icon | Alias
--- | ---
set-all | set-or
set-all | set-union
set-all | sql-full-outer-join
set-center | set-and
set-center | set-intersection
set-center | sql-inner-join
set-center-right | sql-right-outer-join
set-left | difference-left
set-left-center | sql-left-outer-join
set-left-right | exclusion
set-left-right | set-xor
set-none | set-not
set-none | set-null
set-right | difference-right
