### ISSUE TITLE
notebook-multiple

### ISSUE THREAD

**Issue by gabrielgrant** [Templarian/MaterialDesign#2534]
[notebook-multiple.plain.svg.zip](https://github.com/Templarian/MaterialDesign/files/1397119/notebook-multiple.plain.svg.zip)
![notebook-multiple](https://user-images.githubusercontent.com/493968/31754411-40373dfc-b44c-11e7-8e47-e278df4309d0.png)
![notebook-multiple large](https://user-images.githubusercontent.com/493968/31754412-4066de0e-b44c-11e7-8d32-7f7d585cca1b.png)

**Comment by gabrielgrant** [comment]
Based on the [notebook](https://materialdesignicons.com/icon/notebook) and [note-multiple](https://materialdesignicons.com/icon/note-multiple) icons

FWIW, spent longer than I care to admit playing with the two sets of notebook bindings to get them to not interact in a way that ended up looking like a jumbled mess. Also tried one or the other as a flat line, and a few other combinations. This looks a bit weird when viewed at large size, but seems fairly reasonable at small scale to my eye. Certainly open to suggestions (and happy to post some other, clearly-bad options if people are curious)

**Comment by gabrielgrant** [comment]
Sweet, thanks!

**Comment by Templarian** [comment]
Added.

[![notebook-multiple](https://materialdesignicons.com/icon/notebook-multiple)](https://materialdesignicons.com/icon/notebook-multiple)
