### ISSUE TITLE
workspace/desktop

### ISSUE THREAD

**Issue by gabrielgrant** [Templarian/MaterialDesign#2535]
A couple options:

I think I prefer this one:
![workspace](https://user-images.githubusercontent.com/493968/31755817-53607cd2-b455-11e7-907d-68042d51644a.png)
![workspace large](https://user-images.githubusercontent.com/493968/31755816-52e3a4aa-b455-11e7-93cf-5031930df1a7.png)

This one follows the guidelines more pedantically and uses a 2dp outline on the paper, but it feels too heavy to me:
![workspace 2dp-paper](https://user-images.githubusercontent.com/493968/31755813-5160c086-b455-11e7-867c-9d94ef196da3.png)
![workspace 2dp-paper large](https://user-images.githubusercontent.com/493968/31755815-5218300e-b455-11e7-8522-c1ec6c1b5a12.png)

Note that I only cut the paper's outline above the pencil in the second one because it felt too crowded without, but i don't think it's really needed on the 1dp paper version

**Comment by gabrielgrant** [comment]
Another option with a cut above on 1dp paper and a better aspect-ratio on the paper sheet

![workspace 1dp-paper-cut-aspect large](https://user-images.githubusercontent.com/493968/31756030-800ad100-b456-11e7-8d1a-8caa6db8c8e0.png)
![workspace 1dp-paper-cut-aspect](https://user-images.githubusercontent.com/493968/31756031-8065e964-b456-11e7-9894-dbc16330d0c4.png)

**Comment by gabrielgrant** [comment]
One more option (bigger pen)

![workspace large-pen](https://user-images.githubusercontent.com/493968/31756262-fdc4f390-b457-11e7-9c60-0a1b09f4edaf.png)
![workspace large-pen large](https://user-images.githubusercontent.com/493968/31756265-fe89b27a-b457-11e7-8fac-d11f7e87e647.png)

**Comment by gabrielgrant** [comment]
...aaand same, but with a 2dp cut on the outer workspace border for the pen
![workspace large-pen-2dp-cut large](https://user-images.githubusercontent.com/493968/31756353-80d76bf0-b458-11e7-8581-7ae62c0dd744.png)
![workspace large-pen-2dp-cut](https://user-images.githubusercontent.com/493968/31756354-8173cb3a-b458-11e7-90fd-ca6152fc571d.png)

**Comment by GreenTurtwig** [comment]
I seem to remember seeing that design before, can't exactly remember where, if you could provide some images of where it's used that would be great. :cat2:

Anyway, here's a similar a design used in a quite a few Linux desktop manager.
![image](https://user-images.githubusercontent.com/15905797/31765273-c108e574-b4bb-11e7-98e7-f0ecd856d3c4.png)
![image](https://user-images.githubusercontent.com/15905797/31765289-cc9c4de0-b4bb-11e7-8f10-d9a13187d216.png)
[desktop-appearance.zip](https://github.com/Templarian/MaterialDesign/files/1397910/desktop-appearance.zip)

**Comment by gabrielgrant** [comment]
Not exactly a paragon of good design, so a little embarrassed to admit this, but i think i'd first seen this basic icon idea in some old version of windows (XP? 95? not sure): 
![image](https://user-images.githubusercontent.com/493968/31799819-43ad0dd6-b4f1-11e7-9c94-9d549af50bce.png)

**Comment by GreenTurtwig** [comment]
Ahh! So that's where I recognised it from, been a looong time since I've used XP.

Was updated to the current style in Vista.
![thumb_14339683180desktop](https://user-images.githubusercontent.com/15905797/31799938-3b6bf49a-b535-11e7-91c5-7998d4460542.png)
_From Win10_

**Comment by gabrielgrant** [comment]
Ah, interesting. Yea, most examples seem to have moved from using a physical desktop/workspace metaphor to just showing a computer/OS desktop. I created this because I was looking for something to represent the concept of a "workspace" which _isn't_ a computer/OS desktop

**Comment by GreenTurtwig** [comment]
Yeah, almost everyone seems to use a similar design now. It works well, but it's obviously not what you wanted. Xfce uses for squares inside another square to represent workspaces, might be with having a look at how different desktop mangers and icon packs represent it.

**Comment by GreenTurtwig** [comment]
Is it a physical workspace you need or a virtual one (computers)? Physical could be done with someone sitting at a desk.

**Comment by gabrielgrant** [comment]
Yup, also submitted a couple desk icon options while trying out different ideas :) #2536

The workspace I'm talking about is digital, and yes, that does sometimes seem to often be represented by a collection of boxes (representing different windows, i guess?), but in this case it isn't really a multi-window thing, it's more of a single section of the application for work/experimentation, so i think i'm leaning towards the icon proposed in this issue (probably the last one [here](https://github.com/Templarian/MaterialDesign/issues/2535#issuecomment-337808291) as my best option

**Comment by gabrielgrant** [comment]
This is my preferred version: 
![workspace large-pen-2dp-cut plain-large](https://user-images.githubusercontent.com/493968/45177941-5b763980-b1e2-11e8-8c27-6e2dbb4c93e0.png)
![workspace large-pen-2dp-cut plain](https://user-images.githubusercontent.com/493968/45177945-5d3ffd00-b1e2-11e8-95e9-23adb55b2962.png)
[workspace.large-pen-2dp-cut.plain.svg.zip](https://github.com/Templarian/MaterialDesign/files/2358330/workspace.large-pen-2dp-cut.plain.svg.zip)

**Comment by MrGrigri** [comment]
I believe that this icon does not make sense, nor does it really look like it belongs in the pack. My suggestion would be to use the following. I would use the name `monitor-screenshot` to be consistent with `cellphone-screenshot` with the aliases of `workspace` and `desktop`. 

![monitor-screenshot](https://user-images.githubusercontent.com/4528551/45182329-2536bb00-b1de-11e8-8a06-5ac9bed85bf6.png)


[monitor-screenshot.zip](https://github.com/Templarian/MaterialDesign/files/2358596/monitor-workspace.zip)

**Comment by MrGrigri** [comment]
Reference #1697

**Comment by gabrielgrant** [comment]
While i think the icon you propose serves the purpose of a computer desktop well, it doesn't satisfy the need for a representation of a physical workspace

**Comment by PeterShaggyNoble** [comment]
`monitor-screenshot` has been added.

**Comment by gabrielgrant** [comment]
Any specific requests/suggestions to either improve the icon I posted, or provide an alternative representation of a workspace?

**Comment by goyney** [comment]
I have to agree with @MrGrigri. I don't feel the other icon with the pencil makes sense. Since `monitor-screenshot` has been added, I'm going to consider we close this issue.

**Comment by gabrielgrant** [comment]
While I agree the monitor-screenshot icon is useful, I don't really follow how it fulfills the need of representing a workspace - the two concepts seem pretty orthogonal to me. To reiterate: I'm not suggesting this be used as a "show (operating-system) desktop" icon, but rather to represent a "workspace" which _isn't_ a computer/OS desktop

**Comment by gabrielgrant** [comment]
Seems the version I posted before was a raw output. Here's an optimized version: 

[workspace.large-pen-2dp-cut.optimized.svg.zip](https://github.com/Templarian/MaterialDesign/files/2990730/workspace.large-pen-2dp-cut.optimized.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Preview:

![workspace](https://user-images.githubusercontent.com/15157491/54819461-db05ba80-4c93-11e9-8942-fa1fa612e2c5.png)

**Comment by MrGrigri** [comment]
I guess the problem I have with this icon is the 1px box representing the paper.

**Comment by gabrielgrant** [comment]
@MrGrigri mind explaining a bit more? is it that you think it isn't clear what the box is supposed to be representing? or is the concern more that the paper doesn't match stylistically?

As a solution, do you think it should be removed? or just brought into line with the 2dp width standard?

As I noted with this version above, I recognize that it's more in keeping with the standard, but it also just felt kind of heavy:

![workspace 2dp-paper](https://user-images.githubusercontent.com/493968/31755813-5160c086-b455-11e7-867c-9d94ef196da3.png)
![workspace 2dp-paper large](https://user-images.githubusercontent.com/493968/31755815-5218300e-b455-11e7-8522-c1ec6c1b5a12.png)

There seemed to already be a fair number of other exceptions to the 2dp rule, so thought the thinner one was better, but could do up a version of the 2dp with the larger pencil, if you think that'd be an improvement?

**Comment by MrGrigri** [comment]
I was saying that I don't like the paper at all.

**Comment by goyney** [comment]
We currently have `square-edit-outline` which is similar to the proposed icon, without the extra complexity.

[![square-edit-outline](https://materialdesignicons.com/icon/square-edit-outline)](https://materialdesignicons.com/icon/square-edit-outline)

---

Material guidelines state, _"Each icon is reduced to its minimal form, expressing essential characteristics,"_ and icons _"...ensure readability and clarity, even at small sizes."_

In the proposed icon, the extra box doesn't really provide value, especially at native resolution. Additionally, the pencil kind of gets lost because of its size. That all being said, we've had some discussions around this specific issue internally and have decided we don't think this icon would be a good fit for the library.

Thank you for your suggestion.
