### ISSUE TITLE
Desk

### ISSUE THREAD

**Issue by gabrielgrant** [Templarian/MaterialDesign#2536]
two options on two axes: light or dark; wider overhang (not quite leaving the full 2dp border) or not

Dark/not wide:
![desk-dark large](https://user-images.githubusercontent.com/493968/31758675-3ef8b3c8-b463-11e7-95c1-011262e334b1.png)
![desk-dark](https://user-images.githubusercontent.com/493968/31758676-3f31f854-b463-11e7-91da-9a2edd65439c.png)
Dark/wide:
![desk-dark-wide](https://user-images.githubusercontent.com/493968/31758677-3f8be24c-b463-11e7-8a93-59b47c28cd2e.png)
![desk-dark-wide large](https://user-images.githubusercontent.com/493968/31758678-4029ac52-b463-11e7-8765-ef62fc484d56.png)
Light/wide:
![desk-light-wide large](https://user-images.githubusercontent.com/493968/31758680-40e4d086-b463-11e7-8086-0e1cf1e69570.png)
![desk-light-wide](https://user-images.githubusercontent.com/493968/31758683-42871c3c-b463-11e7-97d2-f296624c242c.png)
Light/not wide:
![desk-light large](https://user-images.githubusercontent.com/493968/31758681-41e05398-b463-11e7-8921-dcf057a231f8.png)
![desk-light](https://user-images.githubusercontent.com/493968/31758682-42376f0c-b463-11e7-8552-97b4fa380a67.png)

I also tried it with rounded handles, somewhat similar to the one on the [archive icon](https://materialdesignicons.com/icon/archive), but i don't think it looks very good at small scale:

![desk-round-handle](https://user-images.githubusercontent.com/493968/31758934-56f26144-b464-11e7-98e6-82c4d84f2459.png)

![desk-round-handle](https://user-images.githubusercontent.com/493968/31758889-1fdb2aa6-b464-11e7-8c2f-4a099459e0da.png)

**Comment by JapanYoshi** [comment]
I feel like the nonwide desks would work, albeit with non-rounded desktop edges.

**Comment by goyney** [comment]
Removed the Contribution label because no source SVG files were provided.

**Comment by gabrielgrant** [comment]
Happy to post a cleaned-up SVG, if someone wants to weigh in on which I should clean

**Comment by Templarian** [comment]
Added. Sorry for this getting lost in the backlog. We're working quickly to make this happen less.

This was added to the shared contributor account. Let me know when you're at 5 icons and we'll create a contributor account. 👍
