### ISSUE TITLE
request: money safe

### ISSUE THREAD

**Issue by adrianTNT** [Templarian/MaterialDesign#2537]
Money safe icon ? 
I could not find an alias when searching from site.
Or any recommended icon to use for "withdraw" ?
Thank you.

**Comment by PeterShaggyNoble** [comment]
`credit-card` could serve your purposes for a withdrawal icon but there is currently no safe icon. Would `bank` or `wallet` suit your need in the meantime?

[![](https://materialdesignicons.com/icon/credit-card)](https://materialdesignicons.com/icon/) [![](https://materialdesignicons.com/icon/bank)](https://materialdesignicons.com/icon/bank) [![](https://materialdesignicons.com/icon/wallet)](https://materialdesignicons.com/icon/)

**Comment by adrianTNT** [comment]
Thanks for the suggestion, I didn't thought of wallet, but I think it it not very intuitive. 
And I need it for a bitcoin withdraw service that has a name similar to "no banks", so the bank icon would not work for me :) I will look around some more and maybe use the BTC currency icon.

**Comment by Templarian** [comment]
We have a `safe` request also. #1897 But not sure if that works for this request.

**Comment by adrianTNT** [comment]
Duplicate of #1897

**Comment by adrianTNT** [comment]
Something like this would work well in my case:
https://thumb1.shutterstock.com/display_pic_with_logo/4230679/514037338/stock-vector-money-vault-safe-vault-security-icon-safety-icon-514037338.jpg 
And it probably helps to have it also as "vault" alias.

**Comment by GreenTurtwig** [comment]
Closing as safe request is available at https://github.com/Templarian/MaterialDesign/issues/1897
