### ISSUE TITLE
folder-up

### ISSUE THREAD

**Issue by ForestTree** [Templarian/MaterialDesign#254]
File system navigation - to upper (parent) directory icon will be nice.
Something like this:
http://www.iconarchive.com/show/blue-bits-icons-by-icojam/folder-arrow-up-icon.html
or simple version:
http://www.iconarchive.com/show/outline-icons-by-iconsmind/Up-2-2-icon.html
Thanks
- [ ] folder-up

**Comment by RYO-Software** [comment]
I use a folder-up modified image for this.
Is simple and effective :)

![file_type_is_folder_up](https://cloud.githubusercontent.com/assets/2010101/7050200/ea862fb2-de1f-11e4-90c6-1d1136d9b434.png)

**Comment by CoDEmanX** [comment]
@Templarian: do you have a preference?

![folder_up_variant2](https://cloud.githubusercontent.com/assets/1309249/8761268/7856a1ce-2d48-11e5-83ce-a5e1645a54c4.png)
![folder_up](https://cloud.githubusercontent.com/assets/1309249/8761269/7856afc0-2d48-11e5-87b8-9a5dfba3cc07.png)
![folder_up_variant](https://cloud.githubusercontent.com/assets/1309249/8761270/78576096-2d48-11e5-9f5d-1e970b736dfc.png)

**Comment by CoDEmanX** [comment]
`folder-move` but with the arrow pointing left might also work, although it's a bit unconventional (rather folder-back than folder-up).

Another variant, which I like the most so far: ![folder_up_variant3](https://cloud.githubusercontent.com/assets/1309249/14768011/491494be-0a35-11e6-99de-7e4b72b3f3b8.png)

**Comment by AlexanderOtavka** [comment]
@CoDEmanX I like that variant too.  Any chance you could post an SVG of that, or maybe get it on the materialdesignicons.com site?

**Comment by Templarian** [comment]
@CoDEmanX I like the last one you posted the most. Lets get that one added.

**Comment by CoDEmanX** [comment]
@Templarian: it should be contained in one of the icon packs I provided.

**Comment by PeterShaggyNoble** [comment]
[`folder-upload`](https://materialdesignicons.com/icon/folder-upload) should fulfil this request, given the correct context.

A rotated [`subdirectory-arrow-left`](https://materialdesignicons.com/icon/subdirectory-arrow-left) might also be of use.
