### ISSUE TITLE
LastPass

### ISSUE THREAD

**Issue by jirkaxxl** [Templarian/MaterialDesign#2540]
LastPass icon / logo: https://www.lastpass.com

**Comment by MrGrigri** [comment]
![lastpass](https://user-images.githubusercontent.com/4528551/31783845-eb19bbda-b4bc-11e7-8bae-942a867da768.png)

![lastpass-show](https://user-images.githubusercontent.com/4528551/31783848-ed52470a-b4bc-11e7-8fb3-e36d50f80bf2.png)

[lastpass.zip](https://github.com/Templarian/MaterialDesign/files/1399331/lastpass.zip)

**Comment by k5cents** [comment]
I've been using `lock-open` and `textbox-password` in my app drawer to represent LastPass. Just some options other than the brand icon.

**Comment by Templarian** [comment]
So, `lastpass` replaced `rdio` since that died a while ago.

[![lastpass](https://materialdesignicons.com/icon/lastpass)](https://materialdesignicons.com/icon/lastpass)

**Comment by MrGrigri** [comment]
@Templarian, I believe you contributed this one to yourself. :)

**Comment by Templarian** [comment]
@MrGrigri Fixed. Switching between accounts a lot yesterday.
