### ISSUE TITLE
Icon request/submission: AdBlock Plus & uBlock Origin

### ISSUE THREAD

**Issue by jirkaxxl** [Templarian/MaterialDesign#2542]
AdBlock Plus icon / logo: https://adblockplus.org/

uBlock Origin icon / logo: https://addons.mozilla.org/cs/firefox/addon/ublock-origin/

**Comment by JamesCoyle** [comment]
We rarely add brands that aren't social networks. If it doesn't fit in a share widget it's probably not gonna be added.
