### ISSUE TITLE
ad-blocking symbol

### ISSUE THREAD

**Issue by jirkaxxl** [Templarian/MaterialDesign#2543]
General symbol for advertising blocking (no brand)

**Comment by MrGrigri** [comment]
Wouldn't either `octagon` or `octagon-outline` work?

![octagon](https://materialdesignicons.com/icon/octagon) ![octagon-outline](https://materialdesignicons.com/icon/octagon-outline)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback.

**Comment by CoDEmanX** [comment]
We also provide the following:

![do-not-disturb](https://materialdesignicons.com/icon/do-not-disturb) ![block-helper](https://materialdesignicons.com/icon/block-helper)
