### ISSUE TITLE
Google's Security icon, with exclamation mark and warning label

### ISSUE THREAD

**Issue by NitrodeXXer** [Templarian/MaterialDesign#2544]

**Comment by PeterShaggyNoble** [comment]
Are you looking for the `shield` icon with the exclamation mark on it?

[![](https://materialdesignicons.com/icon/shield)](https://materialdesignicons.com/icon/shield)

**Comment by PeterShaggyNoble** [comment]
Something like this?

[shield-alert.zip](https://github.com/Templarian/MaterialDesign/files/1402041/shield-alert.zip)

**Comment by lattam** [comment]
Hello, 
could you please include the shield with exclamation mark in the icon library ? I really need some icon of "security risk" and this one would be perfect.

Thank you very much!

**Comment by CoDEmanX** [comment]
Hm, do we need both, "!" and "x"?

https://github.com/Templarian/MaterialDesign/issues/2489#issuecomment-335847264

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX, generally "!" is used for warnings and "x" for errors.

**Comment by Templarian** [comment]
Added. Also outline is assigned you @PeterShaggyNoble. 😃
