### ISSUE TITLE
Google Fit: weight-log, weight-gain, and weight-loss

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2547]
Extracted from the Google Fit apk file.

![ic_weight_off](https://user-images.githubusercontent.com/18021678/31838437-d648b262-b5aa-11e7-9faf-1aa2a0fb406d.png)
![ic_weight_gain](https://user-images.githubusercontent.com/18021678/31838472-f945905a-b5aa-11e7-9ea4-4587466360f1.png)
![ic_weight_lost](https://user-images.githubusercontent.com/18021678/31838473-f954163e-b5aa-11e7-8a66-0da40a255372.png)

**Comment by kylerchin** [comment]
could be simplified. i think the ticks hurts the eyes
+1

**Comment by PeterShaggyNoble** [comment]
See also #1788

**Comment by goyney** [comment]
I believe we cover this use case with our set of `gauge-*` icons and don't see a reason for another variation of them.

**Comment by PeterShaggyNoble** [comment]
Cross-posting @GreenTurtwig's version from #1788:

[![scale-fitness](https://user-images.githubusercontent.com/15905797/38939594-2fd9912c-4320-11e8-9afa-ea38aa209291.png)](https://github.com/Templarian/MaterialDesign/files/1924559/weight-fitness.zip)

**Comment by goyney** [comment]
We're going to close this in favor of our `gauge-*` icons.
