### ISSUE TITLE
notebook icon missing from npm package

### ISSUE THREAD

**Issue by b-gran** [Templarian/MaterialDesign#2548]
### Description
The latest version of the NPM package is missing the notebook icon.
There's no entry for it in the css file.

Version `2.0.46` specifically is missing `notebook`.

### Reproduction
* Install the `mdi` NPM package (version `2.0.46` or greater) via `npm install`
* Open `node_modules/mdi/css/materialdesignicons.css`
* Observe that no entry for `notebook` is present

**Comment by PeterShaggyNoble** [comment]
That icon was added after the last release, it will be available in the next release. See the [history page](https://materialdesignicons.com/history) for more details and please search the existing issues for answers/duplicates before creating a new issue.

**Comment by nnmrts** [comment]
Okay, uhm, dumb question maybe, but when will the next release come? And how do you or anyone else decide when it will be here?

**Comment by PeterShaggyNoble** [comment]
There is no set schedule for releases; they happen when they happen. That said, the next one should be fairly soon - you can track it in #2667. The new website currently under development should, hopefully, allow for more frequent releases.

**Comment by nnmrts** [comment]
Okay, thank you!

However, it would be awesome if in the README.MD and/or on the website was some sort of indicator that shows you if an icon is in the current release or not; or maybe just a link to that issue #2667 (or to the next issue when 2.1 is released...) Personally, when I browse the icons materialdesignicons.com, I expect them to be in my installed npm package. Another solution might be to only display already released icons on the website, but I think my first suggestion seems better, so one can download icons specifically even if they aren't released officially.

Just my little feedback, to explain my confusion with this.

**Comment by nnmrts** [comment]
Okay, I just found https://materialdesignicons.com/cheatsheet.

This seems to show the icons related to release version. But not really. :D
Unreleased icons only have a lower opacity. There's no information what this lowered opacity actually means.

Also, the cheatsheet isn't really the starting point when someone is browsing for icons, imo.

**Comment by PeterShaggyNoble** [comment]
Development of that particular cheatsheet was abandoned; it's continued presence on the site was an oversight.

The icons gallery on the new site, however, will include the same ability to filter icons by release version.
