### ISSUE TITLE
landscape-to-portrait, portrait-to-landscape

### ISSUE THREAD

**Issue by imogenic** [Templarian/MaterialDesign#255]
Existing reference icons: rotate-left-variant, rotate-right-variant
- [ ] landscape-to-portrait
- [ ] portrait-to-landscape

**Comment by dotbran** [comment]
Existing reference icons: rotate-left-variant, rotate-right-variant

**Comment by CoDEmanX** [comment]
How exactly are they supposed to look like? The existing icons seem fine to me. If you place two icons depicting a shallow and a narrow rectangle, that should work.
