### ISSUE TITLE
Home-Plus, Home-Minus

### ISSUE THREAD

**Issue by simplejidad** [Templarian/MaterialDesign#2550]
Home icon, with no door, instead containing a plus sign, also same but minus sign.

**Comment by PeterShaggyNoble** [comment]
Not sure about the positioning of the symbols on these.

[home-plus-minus.zip](https://github.com/Templarian/MaterialDesign/files/1415242/home-plus-minus.zip)

**Comment by simplejidad** [comment]
These are perfect, thank you so much!

**Comment by simplejidad** [comment]
I can't really get them to work with android though, do you have the xml
files?

**Comment by Templarian** [comment]
@simplejidad The XML files are basically just SVG path data. You could just copy it into the template below...

```xml
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:height="24dp"
    android:width="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">
    <path android:fillColor="#000" android:pathData="data here" />
</vector>
```
(replace `data here` with `<path d="data here">` from the SVG.

**Comment by simplejidad** [comment]
Tanks again

**Comment by Templarian** [comment]
[![home-plus](https://materialdesignicons.com/icon/home-plus)](https://materialdesignicons.com/icon/home-plus) [![home-minus](https://materialdesignicons.com/icon/home-minus)](https://materialdesignicons.com/icon/home-minus)
