### ISSUE TITLE
RAM, GPU and Screen,  icons

### ISSUE THREAD

**Issue by dovahkiin98** [Templarian/MaterialDesign#2551]
I would like to request 2 new icons, RAM, GPU and Screen Icons

**Comment by GreenTurtwig** [comment]
We have icons for memory and monitors already:
[![](https://materialdesignicons.com/icon/chip)](https://materialdesignicons.com/icon/chip)[![](https://materialdesignicons.com/icon/monitor)](https://materialdesignicons.com/icon/monitor)

A GPU has been contributed over here: https://github.com/Templarian/MaterialDesign/issues/1034

Great username by the way. :-P

**Comment by PeterShaggyNoble** [comment]
There's also the `memory` icon, which might be of use to you:

[![](https://materialdesignicons.com/icon/memory)](https://materialdesignicons.com/icon/memory)

**Comment by dovahkiin98** [comment]
There are monitors but none is a screen of a mobile device, and the memory
icon looks very much like the chip icon

**Comment by GreenTurtwig** [comment]
What do you mean by "mobile device"? We have icons for phones, tablets and laptops, all of which have displays.

**Comment by MrGrigri** [comment]
![cellphone](https://materialdesignicons.com/icon/cellphone) ![cellphone-android](https://materialdesignicons.com/icon/cellphone-android) ![cellphone-iphone](https://materialdesignicons.com/icon/cellphone-iphone) ![cellphone-basic](https://materialdesignicons.com/icon/cellphone-basic)

**Comment by JamesCoyle** [comment]
Duplicate of #1034
