### ISSUE TITLE
anchor

### ISSUE THREAD

**Issue by mittcoats** [Templarian/MaterialDesign#2554]
I wish I had an anchor icon. Something like this: 
![image](https://user-images.githubusercontent.com/8129570/31923149-256be636-b847-11e7-929f-8d19154fe0db.png)

**Comment by Templarian** [comment]
It's called `anchor`. 😕 

[![anchor](https://materialdesignicons.com/icon/anchor)](https://materialdesignicons.com/icon/anchor)

**Comment by mittcoats** [comment]
Whoa, thanks for pointing out my oversight! Sorry for adding unneeded issue
