### ISSUE TITLE
table-large-add, table-large-remove

### ISSUE THREAD

**Issue by zTrap** [Templarian/MaterialDesign#2556]

**Comment by goyney** [comment]
`table-add` and `table-remove` will be added in https://github.com/Templarian/MaterialDesign/issues/3313.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48668028-a7cad900-eab1-11e8-9ea6-fc4d7ba3288f.png)![image](https://user-images.githubusercontent.com/1015040/48668032-c3ce7a80-eab1-11e8-8414-7126561363c0.png)


[table-large.zip](https://github.com/Templarian/MaterialDesign/files/2592466/table-large.zip)

**Comment by goyney** [comment]
[![table-large-plus](https://materialdesignicons.com/icon/table-large-plus)](https://materialdesignicons.com/icon/table-large-plus)[![table-large-remove](https://materialdesignicons.com/icon/table-large-remove)](https://materialdesignicons.com/icon/table-large-remove)
