### ISSUE TITLE
run-fast

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2558]
Might be a good idea to fix the run-fast icon so it looks like the run icon's person that was updated a long time back.

**Comment by MrGrigri** [comment]
![run-fast 1x](https://user-images.githubusercontent.com/4528551/32011427-0203685a-b972-11e7-915a-5b21ee4d3107.png)

![run-fast](https://user-images.githubusercontent.com/4528551/32011430-05b6b588-b972-11e7-88cd-749e21b5530e.png)

[run-fast.zip](https://github.com/Templarian/MaterialDesign/files/1415418/run-fast.zip)

**Comment by Templarian** [comment]
[![run-fast](https://materialdesignicons.com/icon/run-fast)](https://materialdesignicons.com/icon/run-fast)
