### ISSUE TITLE
malogrado

### ISSUE THREAD

**Issue by Wesley-smn** [Templarian/MaterialDesign#2559]
I want an icon to illustrate when somebody is a malogrado!

**Comment by Templarian** [comment]
Does malogrado = sick? Do you have an example?

**Comment by MrGrigri** [comment]
![thermometer](https://materialdesignicons.com/icon/thermometer) ![thermometer-lines](https://materialdesignicons.com/icon/thermometer-lines)

**Comment by Wesley-smn** [comment]
it's something like "ill-fated" person, but i loved this thermometer! thaaanks!!!

**Comment by PeterShaggyNoble** [comment]
Could you provide a bit more context? When I first saw this request, I thought `skull` could do the job but it may not be suitable.

[![](https://materialdesignicons.com/icon/skull)](https://materialdesignicons.com/icon/skull)

**Comment by MrGrigri** [comment]
@Wesley-smn, do these icons fit your needs? So we can close this issue.

**Comment by Wesley-smn** [comment]
Sorry for the late, but yes, that icon fit my needs, thank all of you!
