### ISSUE TITLE
Bonzi Buddy Icon

### ISSUE THREAD

**Issue by economike** [Templarian/MaterialDesign#256]
I would like to request a bonzi buddy icon. I feel this icon would help me greatly in my daily workflow. 

http://en.wikipedia.org/wiki/BonziBuddy
http://vignette2.wikia.nocookie.net/ideas/images/6/64/Bonzibuddy-32779.jpg/revision/latest?cb=20140510161240

**Comment by CoDEmanX** [comment]
Maybe a monkey, but an icon for an adware / spyware?!

**Comment by JamesCoyle** [comment]
Nice to see the High Priority label being put to good use. XD
