### ISSUE TITLE
View-Quilt-Variant

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2560]
Found this on Google Keep earlier, an alternative `view-quilt` (or `view-grid`) icon. The original was only 20x20 so I just increased the canvas size to 24x24.

[view-quilt-variant.zip](https://github.com/Templarian/MaterialDesign/files/1414092/view-quilt-variant.zip)

**Comment by Templarian** [comment]
[![view-dashboard-variant](https://materialdesignicons.com/icon/view-dashboard-variant)](https://materialdesignicons.com/icon/view-dashboard-variant)
