### ISSUE TITLE
Weather icon or Morning, Afternoon, Evening, Night Icon would be nice to add!

### ISSUE THREAD

**Issue by ArunPandiyan** [Templarian/MaterialDesign#2565]
I've been using morning icon (actually the icon is brightness icon) now its changed it seems. i can't find in google stock iconset anymore.

**Comment by PeterShaggyNoble** [comment]
Any of [these](https://petershaggynoble.github.io/MDI-Sandbox/?filter=brightness) or [these](https://petershaggynoble.github.io/MDI-Sandbox/?categories=weather) suit your needs? If not, please provide examples.

All brightness icons are still in the stock set, by the way.

**Comment by ArunPandiyan** [comment]
Thanks ! its better
