### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by Maur0V** [Templarian/MaterialDesign#2567]
an icon with  money or currency and clock  togheter
thanks

**Comment by MrGrigri** [comment]
What would you need this for? Could you please include some example usage or examples of what it should look like.

**Comment by PeterShaggyNoble** [comment]
Using one of the `currency-*` icons would mean doing it for all those icons which wouldn't be feasible and the `cash` icon is too small to layer anything on top of it so, as @MrGrigri said, a bit of context might help us pick a payment related icon that could be modified, or come up with a completely new one.

**Comment by Maur0V** [comment]
hi to all. I'll  need it to identify a pre-paid, time based service. some think like " you pay  then you have some time of work"

**Comment by MrGrigri** [comment]
I believe this request is a little too specific and will be quite difficult to make recognizable at a 24x24 size.

**Comment by PeterShaggyNoble** [comment]
Closing as a duplicate of #389 which includes some samples.
