### ISSUE TITLE
Icon Suggestions

### ISSUE THREAD

**Issue by starrychloe** [Templarian/MaterialDesign#2568]
I suggest the following icons:

Show | Edit | Remind | Approve | Reject | Destroy

You already have Edit. Destroy could be aliased to Delete.

**Comment by Templarian** [comment]
Show = `eye`. Probably alias `show`/`hide` to `eye`/`eye-off`.

Do you have an example for the others?

**Comment by starrychloe** [comment]
Yes, Remind means to send a reminder. Approve means the approve the user. Reject means to reject the user. Destroy means to delete the user.

**Comment by PeterShaggyNoble** [comment]
On my phone so can't (be bothered to!) link these up but for the rest try:

- Edit: `pencil` (don't know why that isn't aliased already)
- Remind: `note-*` or `format-list-checks` (there's also an open issue requesting Google Keep's reminder icon with a few SVGs)
- Approve: `check-*` or `approval`
- Reject: `close-*` or `minus-*`
- Destroy: ... `bomb`?

**Comment by PeterShaggyNoble** [comment]
After seeing your comment ... have you tried searching for `user` or `account`?

**Comment by MrGrigri** [comment]
The reminder icon is tracked here: #518.

**Comment by PeterShaggyNoble** [comment]
Alias `edit` has been added to `pencil`.

**Comment by justinlawrence** [comment]
Agreed with @PeterShaggyNoble, can we add an Alias `approve` to `approval`?

**Comment by PeterShaggyNoble** [comment]
Alias added, @justinlawrence.

Closing this issue out due to lack of further feedback from. @starrychloe, if none of the suggested icons bove fulfil your original request then please open new issues for each icon you still require and include examples.
