### ISSUE TITLE
reddit - icon request

### ISSUE THREAD

**Issue by mufc4martin** [Templarian/MaterialDesign#257]
Could someone please make a reddit icon? Maybe something like the head of the alien?
You might find these files helpful: http://www.reddit.com/about/alien/

**Comment by Templarian** [comment]
This was already added and removed by a vote. It's design does not fit into the pack. You can put:

https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/reddit.svg

into: http://materialdesignicons.com/custom

**Comment by Templarian** [comment]
Eventually I may have a place where we store the "rejected" icons.
