### ISSUE TITLE
remove sorting

### ISSUE THREAD

**Issue by brainloc** [Templarian/MaterialDesign#2570]
I see that you have sorting covered asc and desc but I have a case where I need to remove a sort. Like the sort icon, but rather than the arrow next to the rows showing the sort direction, maybe an 'X' next to the rows to show that you are deleting the sort?

**Comment by PeterShaggyNoble** [comment]
Hmm ... It'd probably be a tight fit to squeeze an `X` in there. Although, it might work if placed in the bottom right of the `sort-variant` icon.

Would it be understood within the context of your application if you replaced the sort icon with one of the `close-*` icons?

**Comment by peddersen** [comment]
Here's a solution I would suggest: 
![image](https://user-images.githubusercontent.com/6444714/38988305-0765bdd4-43d3-11e8-8aa0-78ba5408544e.png)
It's actually the sort-variant with the x icon in the bottom right. I will probably use it in an application, as the close icons won't fit.

**Comment by goyney** [comment]
[![sort-variant-remove](https://materialdesignicons.com/icon/sort-variant-remove)](https://materialdesignicons.com/icon/sort-variant-remove)
