### ISSUE TITLE
Alternate Filter Icons

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2572]
I am attempting to come up with another type of filter icon.  The biggest issue that I have is that the current filter icons are already being used for other purposes, and 508 compliance say that an icon cannot be reused for a different purpose in the same system.  So, since i am already using 3 different filter icons, i need a 4th distinct icon for filtering.
![filter-48px](https://user-images.githubusercontent.com/20706106/32279582-89ddf966-beef-11e7-9c12-4e657366cf52.png)
[circle-filter.zip](https://github.com/Templarian/MaterialDesign/files/1434428/circle-filter.zip)

**Comment by PeterShaggyNoble** [comment]
This seems very specific to your use-case to me - are there any other usages you can suggest for this icon?

**Comment by OctoberJemini** [comment]
It is somewhat specific, but there is really only 2 filter options that are current available, but if you dont think it helpful, I completely understand.

**Comment by PeterShaggyNoble** [comment]
Would `tune` or `tune-vertical` suit your needs at all?

**Comment by OctoberJemini** [comment]
Not really, I never particularly liked tunes for filters, they get confused with settings to much.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
