### ISSUE TITLE
image-off for image just like already existing video-off for video

### ISSUE THREAD

**Issue by lucasmaj** [Templarian/MaterialDesign#2573]

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/32718618-8cefcb9c-c855-11e7-85c4-b5c9a69b39d6.png)
![image](https://user-images.githubusercontent.com/15905797/32718626-93b8fbd8-c855-11e7-983a-ccca321c5aa0.png)
[image-off.zip](https://github.com/Templarian/MaterialDesign/files/1466253/image-off.zip)

It doesn't really look that great. :-/


Would `camera-off` work?
[![](https://materialdesignicons.com/icon/camera-off)](https://materialdesignicons.com/icon/camera-off)

**Comment by Templarian** [comment]
[![image-off](https://materialdesignicons.com/icon/image-off)](https://materialdesignicons.com/icon/image-off)

Might be able to rethink this later, but for now I think it's good enough.
