### ISSUE TITLE
tune and tune-vertical differ in style

### ISSUE THREAD

**Issue by timfish** [Templarian/MaterialDesign#2575]
![image](https://user-images.githubusercontent.com/1150298/32296701-3411eaa2-bf4d-11e7-9202-1bb89daf4de4.png)

**Comment by PeterShaggyNoble** [comment]
See the discussion in #1179 on this.

**Comment by Templarian** [comment]
Hmm... wondering if we should fix this or not.

**Comment by PeterShaggyNoble** [comment]
We probably should, to be consistent with Google's `instant mix` icon.

![instant-mix](https://user-images.githubusercontent.com/15157491/33136781-fc60b956-cf9d-11e7-96f3-abcd1a4fa1a7.png)

**Comment by goyney** [comment]
`tune-vertical` was updated.
[![tune-vertical](https://materialdesignicons.com/icon/tune-vertical)](https://materialdesignicons.com/icon/tune-vertical)

Leaving open as `tune-vertical` needs to be reassigned to Google.

**Comment by goyney** [comment]
Reassigned.
