### ISSUE TITLE
Preview icon

### ISSUE THREAD

**Issue by santoshpati** [Templarian/MaterialDesign#2576]

**Comment by PeterShaggyNoble** [comment]
Thanks for the request. However, we'll need more detail than that.

Would `eye`, `file-find` or `magnify` suit your needs?

[![](https://materialdesignicons.com/icon/eye)](https://materialdesignicons.com/icon/eye) [![](https://materialdesignicons.com/icon/file-find)](https://materialdesignicons.com/icon/file-find) [![](https://materialdesignicons.com/icon/magnify)](https://materialdesignicons.com/icon/magnify)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback,
