### ISSUE TITLE
New Icon Idea: Four Squares - similar to the Apps icon (which has 9 squares)

### ISSUE THREAD

**Issue by swremick** [Templarian/MaterialDesign#2578]
![pasted image at 2017_11_03 02_50 pm](https://user-images.githubusercontent.com/33359082/32393579-740ce558-c0b0-11e7-93a6-0c2abd76d8bf.png)

**Comment by PeterShaggyNoble** [comment]
Sounds like you're looking for `view-grid`:

[![](https://materialdesignicons.com/icon/view-grid)](https://materialdesignicons.com/icon/view-grid)

**Comment by Templarian** [comment]
I think this is exactly that icon, so closing this issue. Let use know and we'll reopen the issue. 😃
