### ISSUE TITLE
Drop Down List

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2579]
need something for `<select>` tag or drop down lists.  I cannot get it clean, but i think you get the idea

![path24](https://user-images.githubusercontent.com/20706106/32396565-1dea1432-c0bc-11e7-8f6c-b2a3cfc2d832.png)
![path48](https://user-images.githubusercontent.com/20706106/32396570-1f9ffb3e-c0bc-11e7-8c1e-473be9c3f554.png)
[drop-down-list.zip](https://github.com/Templarian/MaterialDesign/files/1442517/drop-down-list.zip)

**Comment by OctoberJemini** [comment]
I think i got it addressed

![path24](https://user-images.githubusercontent.com/20706106/32397191-f5e23eb2-c0be-11e7-8dec-7d2767d1f5c7.png)
![path48](https://user-images.githubusercontent.com/20706106/32397193-f7fc3702-c0be-11e7-865b-50a9adc23e89.png)
[drop-down-list.zip](https://github.com/Templarian/MaterialDesign/files/1442567/drop-down-list.zip)

**Comment by goyney** [comment]
I don't get "select box" from the second icon, and the first is lost at native resolution.

We use `chevron-down-box-outline` to indicate select menus in many cases. Would that work for you?

**Comment by goyney** [comment]
Closing because `Needs More Information` was added quite a while ago. I believe `chevron-down-box(-outline)` solves the "dropdown menu" use case pretty easily.

**Comment by goyney** [comment]
This will be added in #4979.
