### ISSUE TITLE
Candidates for vector simplification

### ISSUE THREAD

**Issue by darosh** [Templarian/MaterialDesign#2580]
**Edit**: renaming issue, adding `codepen` and `basecamp`

_Picking most critical from report of [high number of close control points](https://darosh.github.io/material-icons-bundle/#/?icon=codepen&group=Detail&grid=5&community=true)._

## [dice-d10](https://materialdesignicons.com/icon/dice-d10)

can probably reuse better shape of zero from dice-d20.

![image](https://user-images.githubusercontent.com/297320/32403775-e1a0a144-c142-11e7-8fed-a4a6f03bbcaa.png)![image](https://user-images.githubusercontent.com/297320/32403782-fe6e73d2-c142-11e7-9ff7-90108280fa3e.png)

## [codepen](https://materialdesignicons.com/icon/codepen)

![image](https://user-images.githubusercontent.com/297320/32613384-12bf2a6c-c56b-11e7-9fbb-98a55006f19e.png)

## [basecamp](https://materialdesignicons.com/icon/basecamp)

![image](https://user-images.githubusercontent.com/297320/32613951-7053ae04-c56c-11e7-8272-a8c892edc1a8.png)

**Comment by Templarian** [comment]
Revectored these by hand cutting down the point count by hundreds (redrew basecamp since it was so bad).
