### ISSUE TITLE
Icons for: service-desk, gender-neutral and meeting

### ISSUE THREAD

**Issue by Bracba** [Templarian/MaterialDesign#2581]
#

Hi,

I'd like to submit these three icons.

Bracba

![gender-neutral](https://user-images.githubusercontent.com/33094631/32406109-b45c1fee-c172-11e7-8629-63bc9e739af1.jpg)
![meeting](https://user-images.githubusercontent.com/33094631/32406110-b4722690-c172-11e7-8b52-90fbb753e806.jpg)
![service-desk](https://user-images.githubusercontent.com/33094631/32406111-b4867726-c172-11e7-883d-b6eb033d863c.jpg)

**Comment by MrGrigri** [comment]
Could you please divide these into three separate issues; or just two more and rename this one to one fo the requested?

**Comment by ElPodge** [comment]
This is the ones I'm looking for. How can I get them ?

**Comment by goyney** [comment]
`account-group` can be used for meetings:
[![account-group](https://materialdesignicons.com/icon/account-group)](https://materialdesignicons.com/icon/account-group)

I've added `human-non-binary`.
[![human-non-binary](https://materialdesignicons.com/icon/human-non-binary)](https://materialdesignicons.com/icon/human-non-binary)
