### ISSUE TITLE
Better sort alpha/sort numeric icons

### ISSUE THREAD

**Issue by heath3n** [Templarian/MaterialDesign#2583]
It would be great if we could get ascending and descending sort icons for alpha and numeric sorts.

Font Awesome has what I'm talking about but the serif font is decidedly not Material:

![sort_desc](https://user-images.githubusercontent.com/8888204/32416761-916ff802-c21c-11e7-984e-21a21f0afac0.PNG)

**Comment by goyney** [comment]
These were created by @SamueleDassatti.

![image](https://user-images.githubusercontent.com/1015040/52185612-3a486200-27ef-11e9-9186-6d81be400097.png)![image](https://user-images.githubusercontent.com/1015040/52185614-42080680-27ef-11e9-9beb-f4523966b21d.png)

[sort-alphabetical.zip](https://github.com/Templarian/MaterialDesign/files/2826204/sort-alphabetical.zip)

**Comment by goyney** [comment]
These appear to be variations on our current `sort-alphabetical`.

[![sort-alphabetical](https://materialdesignicons.com/icon/sort-alphabetical)](https://materialdesignicons.com/icon/sort-alphabetical)

In my opinion, the "AZ" shouldn't move. Additionally, I disagree with flipping the letters in the `desc` variation.

**Comment by goyney** [comment]
[![sort-alphabetical-ascending](https://materialdesignicons.com/icon/sort-alphabetical-ascending)](https://materialdesignicons.com/icon/sort-alphabetical-ascending)
[![sort-alphabetical-descending](https://materialdesignicons.com/icon/sort-alphabetical-descending)](https://materialdesignicons.com/icon/sort-alphabetical-descending)

**Comment by JapanYoshi** [comment]
Are we going to remake these icons using our alphabetical icons? This seems out of place now in my opinion

**Comment by goyney** [comment]
No, because the base icon is Google's.
