### ISSUE TITLE
Sensor icon

### ISSUE THREAD

**Issue by LinuxLover9** [Templarian/MaterialDesign#2584]
Would be cool to have a sensor icon for IoT sensors, usable for the ESP8266.

Thanks in advance.

**Comment by JamesCoyle** [comment]
Can you provide an example of what it should look like?

**Comment by PeterShaggyNoble** [comment]
Duplicate of #2464?

**Comment by LinuxLover9** [comment]
OK, yes this appears to be a duplicate.
Thank you.
