### ISSUE TITLE
input settings

### ISSUE THREAD

**Issue by uwap** [Templarian/MaterialDesign#2586]
There is not icon for input settings yet. Google has settings_input_component which is mainly what I need. Can someone convert it or design a similar icon for input selection?

**Comment by dwolfx** [comment]
Here you have the icon in SVG, you can put it directly in your html file. Will work.

Pay attention to change the "YOUR-COLOR" in the code

`<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path style="fill: YOUR-COLOR;" d="M5 2c0-.55-.45-1-1-1s-1 .45-1 1v4H1v6h6V6H5V2zm4 14c0 1.3.84 2.4 2 2.82V23h2v-4.18c1.16-.41 2-1.51 2-2.82v-2H9v2zm-8 0c0 1.3.84 2.4 2 2.82V23h2v-4.18C6.16 18.4 7 17.3 7 16v-2H1v2zM21 6V2c0-.55-.45-1-1-1s-1 .45-1 1v4h-2v6h6V6h-2zm-8-4c0-.55-.45-1-1-1s-1 .45-1 1v4H9v6h6V6h-2V2zm4 14c0 1.3.84 2.4 2 2.82V23h2v-4.18c1.16-.41 2-1.51 2-2.82v-2h-6v2z"/></svg>`

Is this what you want to?

**Comment by Templarian** [comment]
[![video-input-component](https://materialdesignicons.com/icon/video-input-component)](https://materialdesignicons.com/icon/video-input-component)
