### ISSUE TITLE
fleur-de-lis

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#2587]
Something like this:

![fleur-de-lis](https://user-images.githubusercontent.com/18021678/32466861-685c470e-c316-11e7-80b4-e7f156c084ad.gif)

Need it to represent scouting organizations.

**Comment by PeterShaggyNoble** [comment]
@k5cents, why the closure? Tricky as it may be to Materialise that, it's worth leaving it open for consideration.

**Comment by k5cents** [comment]
I just personally no longer need it. Upon further consideration I feel like it would definitely be difficult to materialize and would serve little purpose.

**Comment by Templarian** [comment]
I actually think it might be useful to have. Reopening this issue as it could be included without materializing it.

**Comment by Croutonix** [comment]
From #4688
[![fleur-de-lys](https://user-images.githubusercontent.com/18645219/71378200-fe4bf600-2594-11ea-92ec-86f6d4e5888f.png)](https://github.com/Templarian/MaterialDesign/files/3996126/fleur-de-lys.zip)
```text
M12 2S9 4 9 7s2 5 2 9h-1s0-2-1-4c-2-4-6-2-6 1s2 3 2 3c0-3 3.5-3 3.5 0H7v2h3.5L9 20s1 1 2 0l1 2 1-2c1 1 2 0 2 0l-1.5-2H17v-2h-1.5c0-3 3.5-3 3.5 0 0 0 2 0 2-3s-4-5-6-1c-1 2-1 4-1 4h-1c0-4 2-6 2-9s-3-5-3-5z
```

**Comment by goyney** [comment]
[![fleur-de-lis](https://materialdesignicons.com/icon/fleur-de-lis)](https://materialdesignicons.com/icon/fleur-de-lis)
