### ISSUE TITLE
Presence Icons for Smart Home Use

### ISSUE THREAD

**Issue by hblaschka** [Templarian/MaterialDesign#2589]
There is a need for a pack of icons representing Presence (of one or several people) at home, including an empty house icon representing non-presence.

**Comment by PeterShaggyNoble** [comment]
Would the `account-*` and `home-*` icons not do the job? If not, could you provide examples of what you're looking for?

**Comment by hblaschka** [comment]
A combination of both...
Sth. like this 
![6e084a09-cbb7-4f1c-8d37-c0ff6a1b8f24](https://user-images.githubusercontent.com/30728567/32680714-419efe00-c66c-11e7-81d2-ec1ffc6513da.jpeg)

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/32717567-02fdb730-c852-11e7-8a1c-36a8272d48f7.png)
![image](https://user-images.githubusercontent.com/15905797/32717591-0f7ce0b2-c852-11e7-8b93-bf2e47346ea0.png)
[home-account.zip](https://github.com/Templarian/MaterialDesign/files/1466170/home-account.zip)

**Comment by hblaschka** [comment]
here we are.. Thanx @GreenTurtwig

**Comment by Templarian** [comment]
[![home-account](https://materialdesignicons.com/icon/home-account)](https://materialdesignicons.com/icon/home-account)
