### ISSUE TITLE
Religous Establishment Icon

### ISSUE THREAD

**Issue by tmack8001** [Templarian/MaterialDesign#259]
Have a need for this type of icon in a mapping application I'm making to mark points of interest "religious" with a custom icon.

**Comment by Templarian** [comment]
Do you  have an example for this? Trying to think of a generic "religious" icon, but I don't know if there is a symbol for that. Obviously the little church wouldn't work because that has a cross on the top.

**Comment by CoDEmanX** [comment]
Every religion needs a separate icon I guess, or at least every target audience. For Western countries, the a Christian cross should do and is used on printed maps everywhere.

Some findings:

![114-128](https://cloud.githubusercontent.com/assets/1309249/8752392/fb1c12aa-2cb3-11e5-9273-99b753f540e3.png)
![icon-2worship](https://cloud.githubusercontent.com/assets/1309249/8752391/fb1a9c68-2cb3-11e5-88ed-9d8003c3884e.png)
![icon-worship](https://cloud.githubusercontent.com/assets/1309249/8752393/fb577796-2cb3-11e5-9605-2a8211bf4910.png)

The latter would also make a good icon for "politics" (see #508)

**Comment by MrGrigri** [comment]
Closing this out in favor for #1074, Let us know if that doesn't work for you.
