### ISSUE TITLE
Icons Request

### ISSUE THREAD

**Issue by BenjAlessandro** [Templarian/MaterialDesign#2590]
Hello! I need icons about animals and pets.
Please! This is for a StartUp proyect in my university.
I waiting for a response. Thanks! Bye

**Comment by k5cents** [comment]
There's `paw`.

**Comment by PeterShaggyNoble** [comment]
As well as `paw`, we have a number of icons for individual animals, which you can see [here](https://petershaggynoble.github.io/MDI-Sandbox/?categories=nature). If none of those suit your needs, could you please provide more detail (with examples) of what your looking for?

**Comment by PeterShaggyNoble** [comment]
Closing this due to lack of feedback. @BenjAlessandro, if you provide the requested information, we'll reopen this. Please search the existing issues first though to make sure your request(s) aren't already covered.
