### ISSUE TITLE
workflow

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#2592]
Icon to represent a workflow or flowchart.
![workflow](https://user-images.githubusercontent.com/1015040/32638938-73c366f6-c58f-11e7-9b60-f2ee9fb07f3f.png)
[workflow.zip](https://github.com/Templarian/MaterialDesign/files/1459754/workflow.zip)

**Comment by waternexus** [comment]
How did you make that cool preview?

**Comment by goyney** [comment]
Closing as I feel this icon's purpose is already captured in `sitemap`. Additionally, `sitemap` has been aliased to `flowchart` and `workflow`.
