### ISSUE TITLE
Icon request - comment-question

### ISSUE THREAD

**Issue by mgigirey** [Templarian/MaterialDesign#2593]
There is already comment-question-outline icon but not comment-question without outline.

**Comment by Templarian** [comment]
[![comment-question](https://materialdesignicons.com/icon/comment-question)](https://materialdesignicons.com/icon/comment-question) [![comment-remove](https://materialdesignicons.com/icon/comment-remove)](https://materialdesignicons.com/icon/comment-remove)

If anyone views in the future confused, the remove icon replaced an accidentally duplicate icon discussed in #1795.
