### ISSUE TITLE
Icon: web-box

### ISSUE THREAD

**Issue by samthecodingman** [Templarian/MaterialDesign#2596]
This is simply a reshape of the existing `blank-box` and `web` icons. It felt odd having `facebook-box`, `twitter-box`, etc but nothing to describe a website with that had a similar theme.

Personally, I think it may need some tweaks at the 24p resolution. ![mdi-web-box](https://user-images.githubusercontent.com/17465738/32697069-8fcba09a-c7db-11e7-9f35-f8a3a9d05865.png)

![mdi-web-box-show](https://user-images.githubusercontent.com/17465738/32697071-93a45d56-c7db-11e7-992f-1b11b22b1a52.png)

[mdi-web-box.zip](https://github.com/Templarian/MaterialDesign/files/1464433/mdi-web-box.zip)

**Comment by goyney** [comment]
Added!
[![web-box](https://materialdesignicons.com/icon/web-box)](https://materialdesignicons.com/icon/web-box)
