### ISSUE TITLE
icon market stocks

### ISSUE THREAD

**Issue by huuhung2305** [Templarian/MaterialDesign#2599]
you have ideal about market stocks like ticker, price ticker, charter capital........

**Comment by PeterShaggyNoble** [comment]
Would any of the [trending](https://petershaggynoble.github.io/MDI-Sandbox/?filter=trending) or [chart](https://petershaggynoble.github.io/MDI-Sandbox/?filter=chart) icons suit your needs?

**Comment by PeterShaggyNoble** [comment]
See also the recently added `finance` icon:

[![image](https://user-images.githubusercontent.com/15157491/33483749-3903065c-d697-11e7-8443-18014f679f0a.png)](https://materialdesignicons.com/icon/finance)

**Comment by JamesCoyle** [comment]
Closing this as there are no examples of what these should look like and we already have several suitable icons for finance.
