### ISSUE TITLE
Expand Icon

### ISSUE THREAD

**Issue by pruthvirajha** [Templarian/MaterialDesign#260]

**Comment by Templarian** [comment]
Do you mean unfold icons (these are there, there is also a expand/collapse icon already there)? Or something else?

http://materialdesignicons.com/icon/unfold-more
http://materialdesignicons.com/icon/unfold-less

**Comment by Templarian** [comment]
I'm going to close this, if these do not work let me know with an example and I'll reopen the issue.

Good luck on your apps.
