### ISSUE TITLE
gate-open

### ISSUE THREAD

**Issue by kovacsguido** [Templarian/MaterialDesign#2600]
Hi! The MDI is contains a gate icon (in closed state), and i need an opened gate icon also. Thanks!
Bye

**Comment by PeterShaggyNoble** [comment]
That could be a tricky one; see #1822 for the discussion on how to portray an open door.

**Comment by sbonsing** [comment]
Hi
These are icons for a sliding gate i made
![closed](https://user-images.githubusercontent.com/38169194/44306496-74ee4780-a3d3-11e8-94ae-6a0be5126ced.png)
![open](https://user-images.githubusercontent.com/38169194/44306497-7586de00-a3d3-11e8-837d-911e5cd6f642.png)

**Comment by saboaua** [comment]
![sliding gate-01](https://user-images.githubusercontent.com/33001915/59853910-d3f85200-933f-11e9-853d-c72e9933cef2.png)

Any progress on this request, as looking for something similar.

**Comment by CoDEmanX** [comment]
We have `garage` icons:

![grafik](https://user-images.githubusercontent.com/1309249/62945103-5d774e00-bdde-11e9-8540-595778aca711.png)

Maybe something like that?

![grafik](https://user-images.githubusercontent.com/1309249/62946046-3ae63480-bde0-11e9-80a7-98f676d96200.png)

![grafik](https://user-images.githubusercontent.com/1309249/62946020-2b66eb80-bde0-11e9-91c8-721123083cb4.png)

![grafik](https://user-images.githubusercontent.com/1309249/62945997-1ee29300-bde0-11e9-8f49-4bfb66c27a69.png)

![grafik](https://user-images.githubusercontent.com/1309249/62945952-0d00f000-bde0-11e9-850c-013e5158a73b.png)

This would only work together with the existing `gate` icon:

![grafik](https://user-images.githubusercontent.com/1309249/62946661-6cabcb00-bde1-11e9-9789-6cda769145db.png)

![grafik](https://user-images.githubusercontent.com/1309249/62946696-7b927d80-bde1-11e9-84dd-0d44a22d990b.png)

**Comment by goyney** [comment]
Honestly think `gate-open` is the best option from above.

**Comment by CoDEmanX** [comment]
I thought of adding an arrow to `gate-open` to make it clearer, but it looked odd.

The other gate icons are actually not needed anymore, we have `window-shutter-*` icons staged for release already:

![window-shutter](https://user-images.githubusercontent.com/1309249/63207765-fbfbfb80-c0cb-11e9-900e-1c610ee6ef61.png)

https://github.com/Templarian/MaterialDesign/issues/2766

**Comment by CoDEmanX** [comment]
Maybe something like this?

![grafik](https://user-images.githubusercontent.com/1309249/63231858-f87a8880-c221-11e9-9a9a-94ca40ac224d.png)

[gate-open2.zip](https://github.com/Templarian/MaterialDesign/files/3513700/gate-open2.zip)

**Comment by CoDEmanX** [comment]
Slightly improved:

![grafik](https://user-images.githubusercontent.com/1309249/63231933-f664f980-c222-11e9-9a37-a06120b2cf23.png)

[gate-open3.zip](https://github.com/Templarian/MaterialDesign/files/3513705/gate-open3.zip)

**Comment by goyney** [comment]
Those don’t say open to me. I’m not sure what they say... “gate up”?

**Comment by CoDEmanX** [comment]
Right half of gate is open, arrow is supposed to say "please enter". Maybe remove the arrow and just leave half of the gate?

**Comment by saboaua** [comment]
I'm using the gate option for now, but i have a sliding gate and what looking for an sliding gate icon

**Comment by CoDEmanX** [comment]
Arrow modifier is moved 1dp down. Might wanna move the gate up rather (but also in the base icon then).

![grafik](https://user-images.githubusercontent.com/1309249/63257774-d06b4380-c27a-11e9-9636-b4af17539b7f.png)

[gate-arrow.zip](https://github.com/Templarian/MaterialDesign/files/3515322/gate-arrow.zip)

**Comment by goyney** [comment]
[![gate-open](https://materialdesignicons.com/icon/gate-open)](https://materialdesignicons.com/icon/gate-open)[![gate-arrow-right](https://materialdesignicons.com/icon/gate-arrow-right)](https://materialdesignicons.com/icon/gate-arrow-right)
