### ISSUE TITLE
Material Icons Extended

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2602]
https://petershaggynoble.github.io/MDI-Sandbox/extended/

List of icons already included. Some should be either replaced or given a variant, others I feel we have the better design and some are identical.

**I** = Identical
**U** = Updated Google Icon
- [ ] https://github.com/Templarian/MaterialDesign/issues/3812 `rotate-3d` - `360`
- [ ] `human` - `accessibility-new` Variant as arms are stretched upwards slightly.
- [x] `phone-plus` - `add-call` **I**
- [ ] `message-plus` - `add-comment` Should be given `message-reply-plus`
- [x] https://github.com/Templarian/MaterialDesign/issues/2339 - `add-photo-alternate`
- [x] https://github.com/Templarian/MaterialDesign/issues/2277 - `allo` | *Added*
- [x] `at` - `alternate-email` | *Updated and assigned to Google*
- [ ] `menu-left` - `arrow-left` **I**
- [ ] `menu-right` - `arrow-right` **I**
- [x] https://github.com/Templarian/MaterialDesign/issues/1598 - `artist` | *Added*
- [ ] `google-drive` - `attach-drive` and `drive` **I**
- [ ] `collage` - `auto-awesome-mosaic` **I**
- [ ] `animation` - `auto-awesome-animation` **I**
- [ ] `auto-fix` - `auto-fix` **I**
- [ ] `book-open-page-variant` - `auto-stories` **I**
- [ ] `chart-bar` - `bar-chart` and `finance` 
- [ ] `barcode` - `barcode`
- [ ] `barcode-scan` - `barcode-scanner`
- [ ] `check` - `bigtop-done` **I**
- [ ] `bookmark-outline` - `bookmark-outline` **I**
- [ ] `calendar-blank` - `calendar-today` **I**
- [ ] https://github.com/Templarian/MaterialDesign/issues/1824 - `calendar-view-day`
- [ ] `google-cardboard` - `cardboard`
- [ ] `checkbox-blank-outline` - `check-box-outline-blank` **I**
- [ ] `check-circle-outline` - `check-circle-outline`
- [ ] `google-chrome` - `chromecast` **I**
- [ ] `google-circles` - `circles` **I**
- [ ] `plus-circle-outline` - `circles-add` **I**
- [ ] `google-circles-extended` - `circles-ext` **I**
- [ ] `google-circles-communities` - `communities` **I**
- [ ] `thermometer` - `device-thermostat`
- [ ] `ferry` - `directions-ferry` **I**
- [ ] `paw` - `dogfood`
- [ ] `file` - `draft` and `drive-file` **I**
- [ ] `headphones-box` - `drive-audio` **I**
- [ ] `file-document-box` - `drive-document` **I**
- [ ] `drawing-box` - `drive-drawing` **I**
- [ ] `rename-box` - `drive-file-rename` **I**
- [ ] `image` - `drive-image` **I**
- [ ] `google-keep` - `drive-keep`
- [ ] `file-excel-box` - `drive-ms-excel` **I**
- [ ] `file-powerpoint-box` - `drive-ms-powerpoint` **I**
- [ ] `file-word-box` - `drive-ms-word` **I**
- [ ] `file-pdf-box` - `drive-pdf`
- [ ] `file-document` - `file-text`
- [ ] `movie` - `drive-movie` **I**
- [ ] `zip-box` - `drive-zip` **I** 
- [ ] `google-earth` - `earth` **U**
- [ ] `flask-empty` - `experiment`
- [ ] `food` - `fast-food`
- [ ] `heart-outline` - `favourite-outline` **I**
- [ ] `file-multiple` - `file-copy`
- [ ] `image-filter-frames` - `filter-frames` **I**
- [ ] `fish` - `fishfood`
- [ ] `folder-google-drive` - `folder-mydrive` **I**
- [ ] `format-textdirection-l-to-r` - `format-textdirection-l-to-r` **I**
- [ ] `format-textdirection-r-to-l` - `format-textdirection-r-to-l` **I**
- [ ] `fullscreen-exit` - `fullscreen-exit` **I**
- [ ] `garage` - `garage-door`
- [ ] `music-circle` - `genres`
- [ ] `google-glass` - `glass` **I**
- [ ] `gmail` - `gmail` **I**
- [ ] `google` - `google` **U**
- [ ] `google-assistant` - `google-assistant` **U**
- [x] `https://github.com/Templarian/MaterialDesign/issues/1811` - `google-home`
- [ ] `google-plus` - `google-plus` **I**
- [ ] `share` - `googleplus-reshare` **I**
- [ ] `coffee` - `googler-desk`
- [ ] `hangouts` - `hangouts` **I**
- [ ] `headset` - `headset-mic` **I**
- [ ] `headset-off` - `headset-off`
- [ ] `close-circle-outline` - `highlight-remove`
- [ ] `timer-sand-empty` - `hourglass-empty` **I**
- [ ] `dice-3` - `ifl`
- [ ] `account-box` - `inbox-contacts` **I**
- [ ] `incognito` - `incognito` and `incognito-circle`
- [ ] `eraser-variant` - `ink-eraser` **I**
- [ ] `marker` - `ink-highlighter` **I**
- [ ] `grease-pencil` - `ink-marker` **I**
- [ ] `pen` - `ink-pen`
- [ ] `tune-vertical` - `instant-mix`
- [ ] `invert-colors` - `invert-colors-on` **I**
- [ ] `apple-ios` - `ios` **I**
- [ ] `pin` - `keep`
- [ ] `pin-off` - `keep-off`
- [ ] `dots-horizontal` - `keyboard-control`
- [ ] `lightbulb-outline` - `lightbulb-outline` **I**
- [ ] `link-off` - `link-off`
- [ ] `airplane` - `local-airport` **I**
- [ ] `ticket` - `local attraction`
- [ ] `printer` - `local-print-shop`
- [ ] `google-maps` - `maps` **U**
- [ ] `window-maximize` - `maximize`
- [ ] `window-minimize` - `minimize`
- [ ] `cash-100` - `money`
- [ ] `music-off` - `music-off`
- [ ] `google-nearby` - `nearby` **U**
- [ ] `nest-protect` - `nest-protect` **I**
- [ ] `nest-thermostat` - `nest-thermostat` **I**
- [ ] `newspaper` - `news`
- [ ] `bell-sleep` - `notifications-paused`
- [ ] `widgets` - `now-widgets` **I**
- [ ] `flag-outline` - `outlined-flag` **U**
- [ ] `google-photos` - `photos` **U**
- [ ] `panorama` - `planner-banner-ad-ls` **I**
- [ ] `pulse` - `planner-review`
- [ ] `play-circle-outline` - `play-circle-outline` **I**
- [ ] `google-controller` - `play-games` **U**
- [ ] `google-play` - `play-prism` **U**
- [ ] `blogger` - `post-blogger` **I**
- [ ] `facebook-box` - `post-facebook`
- [ ] `google-plus-box` - `post-gplus` **I**
- [ ] `instagram` - `post-instagram`
- [ ] `linkedin-box` - `post-linkedin` **I**
- [ ] `pinterest-box` - `post-pinterest` **I**
- [ ] `tumblr` - `post-tumblr` **I**
- [ ] `twitter-box` - `post-twitter` **I**
- [ ] `power-plug-off` - `power-off`
- [ ] `steering` - `search-hands-free`
- [ ] `emoticon-happy` - `sentiment-satisfied-alt`
- [ ] `settings-box` - `settings-applications` **I**
- [ ] `star-outline` - `star-outline` **I**
- [ ] `chevron-up` - `stat-1` **I**
- [ ] `chevron-double-up` - `stat-2` **I**
- [ ] `chevron-down` - `stat-minus-1` **I**
- [ ] `chevron-double-down` - `stat-minus-2` **I**
- [ ] `sticker-emoji` - `sticker` **I**
- [ ] `gauge` - `swap-driving-apps-wheel` **I**
- [ ] `bullseye` - `target`
- [ ] `thumb-down` - `thumb-down-alt` **I**
- [ ] `thumb-up` - `thumb-up-alt` **I**
- [ ] `trophy` - `trophy`
- [ ] `plus-circle-outline` - `unknown-3`
- [ ] `minus-circle-outline` - `unknown-4`
- [ ] `youtube-play` - `video-youtube` *Should probably be changed to just* `youtube`
- [x] `google-wallet` - `wallet-product` **I** | *Nothing*
- [x] `waves` - `waves` | *Kept community version*
- [x] `youtube-creator-studio` - `youtube-creator` **U** | *Updated*
- [x] `auto-towing` | Added https://materialdesignicons.com/icon/towing
- [x] `ladybug` `ladybird` | Added https://materialdesignicons.com/icon/ladybug
- [x] `arrow-collapse-vertical`
- [x] `arrow-collapse-horizontal`
- [x] `arrow-expand-vertical`
- [x] `arrow-expand-horizontal`

**Comment by PeterShaggyNoble** [comment]
Good work, @GreenTurtwig; gave me a decent jumping off point for [the spreadsheet](https://docs.google.com/spreadsheets/d/1xPws00mcVx_thr3qD8j9UosZYdcD3brQkFBpZZbMQ3E/#gid=2133229631)

**Comment by GreenTurtwig** [comment]
No problem. 🐈

**Comment by Templarian** [comment]
Any that or identical, we just need to make sure we have aliases entered. I'll work on the icons if someone else wants to check those off. 😃

**Comment by PeterShaggyNoble** [comment]
Aliases added for the newly added icons. I should be able to get on to some more aliasing of Google names later on today.

**Comment by k5cents** [comment]
This is the icon Google uses for `finance` on their Inbox by Gmail service.

<img width="24" alt="finance" src="https://user-images.githubusercontent.com/18021678/32984302-dd4f7716-cc71-11e7-959d-73ff64e2b5b9.png">

Slightly different from the one listed above.

**Comment by PeterShaggyNoble** [comment]
@k5cents, can you submit that as a separate request/contribution so it doesn't get lost in the shuffle here?

**Comment by PeterShaggyNoble** [comment]
Google have added a few more icons to this set which I've added to [the sandbox's preview file](https://petershaggynoble.github.io/MDI-Sandbox/extended/):

![compress](https://user-images.githubusercontent.com/15157491/34987952-e25fbd80-fab4-11e7-8f50-408568f679b3.png) [![edit-off](https://user-images.githubusercontent.com/15157491/34988012-2115b3b8-fab5-11e7-8c32-571cc46438fd.png)](https://materialdesignicons.com/icon/pencil-off) ![expand](https://user-images.githubusercontent.com/15157491/34988084-56ab4d6c-fab5-11e7-82ef-00f4961d203d.png) ![filter-list-alt](https://user-images.githubusercontent.com/15157491/34988137-893e8a8c-fab5-11e7-9808-37a7ea2c4f92.png)
 ![switches](https://user-images.githubusercontent.com/15157491/34987681-ed115bae-fab3-11e7-87da-44cccc30c174.png) ![universal-currency-alt](https://user-images.githubusercontent.com/15157491/34987745-2e645f0c-fab4-11e7-8f0a-314c3eb7a0d3.png) ![youtube-improve-tv](https://user-images.githubusercontent.com/15157491/34987848-7e4f26a0-fab4-11e7-8b1d-5013a577e98f.png) ![youtube-linked-tv](https://user-images.githubusercontent.com/15157491/34987901-acf1c242-fab4-11e7-8c42-9208e7b02ada.png) ![youtube-miniplayer-tv](https://user-images.githubusercontent.com/15157491/34987793-58e52df6-fab4-11e7-89d8-9e86ef499a64.png)

**Comment by Templarian** [comment]
I wonder if we should replace and update our filter icons with this version. I kind of like the round design.

**Comment by PeterShaggyNoble** [comment]
Google have added 4 more icons, including a door:

![add link](https://user-images.githubusercontent.com/15157491/36151824-b9fbc7ea-10c0-11e8-8b03-c44ec9b4c9b2.png) ![domain disabled](https://user-images.githubusercontent.com/15157491/36151849-d9cefcd6-10c0-11e8-89a8-79b122bbd1b0.png) ![meeting room](https://user-images.githubusercontent.com/15157491/36151874-f380ad00-10c0-11e8-85d5-e82727431960.png) ![no meeting room](https://user-images.githubusercontent.com/15157491/36151912-0dd6e11a-10c1-11e8-8e63-f365be9c115f.png)

Also, their `edit-off` icon mentioned above and in red below differs slightly from our `pencil-off` (in grey) but I don't know if it's worth updating:

![pencil-off vs. edif off](https://user-images.githubusercontent.com/15157491/36152032-6fc0b554-10c1-11e8-96bf-4098f8cfb7af.png)

**Comment by PeterShaggyNoble** [comment]
They've added a glyph to the `expand all` ligature:

![expand all](https://user-images.githubusercontent.com/15157491/36385527-ad68eea8-158a-11e8-9387-157772463d8f.png)

**Comment by PeterShaggyNoble** [comment]
They've also added a glyph to the `collapse all` ligature now, as well as a new `express campaign` icon:

![collapse all](https://user-images.githubusercontent.com/15157491/36972509-507a3de0-2067-11e8-9d28-997417a55fbd.png) ![express campaign](https://user-images.githubusercontent.com/15157491/36972545-6e446f26-2067-11e8-81ff-e0b3f857f61a.png)

**Comment by GreenTurtwig** [comment]
A lot of new icons have since been added. To save time and not have such a long list here are the icons that need to be updated, reassigned, added as a variant, or not added at all, the rest can just be added with adequate name changes.

- `inbox-multiple` needs to be updated to match `all inbox`
- `phone-plus` is identical to `add ic call`
- `arrow-down-bold` and `arrow-up-bold` need updating and reassigning to match `arrow upward alt` and `arrow downward alt` alongside the other `arrow-[direction]-bold` icons too.
- `format-color-fill` is identical to `colors`
- `contacts` needs `contacts product` added as a variant
- `close-octagon` needs to be reassigned as `dangerous` is identical?
- `star-outline` is identical to `favourite news`
- `web` is identical to`headline`
- `home` needs `home filled` added as a variant
- Don't add `imagesearch roller`
- `checkbox-multiple-marked` needs updating and reassigning to match `library add check`
- `view-list` needs to be replaced by `lists` or added as a variant?
- `logout` needs updating and reassigning to match `logout`
- `stove` needs updating and reassigning to match `oven`
- `shield` is identical to `shield`
- `speedometer` needs updating and reassigning to match `speed`
- `account-box-multiple` needs updating to match `switch account`
- `pound` needs updating and reassigning to match `tag`
- `toggle-switch-off` is identical to `toggle off`
- `toggle-switch` is identical to `toggle-on`
- `motorbike` needs `two wheeler` added as a variant. (Be aware we already need to update `motorbike` to match a previous Google design.)
- `cash` needs updating and reassigning to match `universal currency`
- `file-upload-outline` needs updating and reassigning to match `upload file`

**Comment by PeterShaggyNoble** [comment]
To follow up on a few of @GreenTurtwig's points above:
- `colors` sits higher on the canvas than `format_color_fill` to accommodate `color-helper`.
- Is `contacts_product` not just an inconsistent variant of `account-circle`?
- `favorite_news` and `headline` are a slightly different size to `star-outline` & `web` but I don't think that warrants updating them.
- I think a case can be made for having *both* `oven` and `stove` - a stove is typically free-standing and may also have a hob on top while an oven is typically wall mounted.
- `account-box-multiple` was lifted straight from YouTube - just another damned Google inconsistency! 🙄
- There are a couple of other options for `cash` in the set: `money` and `universal_currency_alt`.

**Comment by goyney** [comment]
This issue is way too large to accurately manage any of the icons or requests within. I am recommending we close it and start curating the Extended Set for icons we want to add and create issues for each one individually.
