### ISSUE TITLE
Moon phases

### ISSUE THREAD

**Issue by bjj** [Templarian/MaterialDesign#2603]
Representing moon phases (full, waxing crescent, quarter, etc) would be clean and easy with circles and arcs.  It would work in a clear context of "this is a moon phase".  Is that acceptable for MDI, or would each individual icon need to read as the moon?

**Comment by Templarian** [comment]
Related to #2255 (both are different requests, but similar, so leaving this open).

**Comment by Templarian** [comment]
These are a little related to `brightness-` but need to have the rest of them. hmm... might be a bit till we get around to these.

**Comment by bjj** [comment]
I can easily make moon phase icons suitable for using in a moon phase indicator (which is what I want).  But it's hard to make moon phases that could stand alone.  If that's okay, I'll make the simple versions.

**Comment by Templarian** [comment]
Yea, the 8 icons required are simple, was more of a priority issue to get them added.

- [ ] 1 `moon-first-quarter`
- [ ] 2 `moon-waxing-crescent`
- [ ] 3 `moon-new` (outline circle?)
- [ ] 4 `moon-waning-crescent`
- [ ] 5 `moon-last-quarter`
- [ ] 6 `moon-waning-gibbous`
- [ ] 7 `moon-full` (solid circle?)
- [ ] 8 `moon-waxing-gibbous`

young/old are going to be too specific probably for most uses.

**Comment by goyney** [comment]
Moon cycles:
![image](https://user-images.githubusercontent.com/1015040/33466925-32dc1ab6-d61f-11e7-81bd-599b731c0000.png)
![image](https://user-images.githubusercontent.com/1015040/33467177-9adb4a82-d620-11e7-8894-49ce0c3b6a8d.png)
![image](https://user-images.githubusercontent.com/1015040/33466946-5495ae38-d61f-11e7-9e1e-bb3bc16c28d3.png)
![image](https://user-images.githubusercontent.com/1015040/33466957-61d207b8-d61f-11e7-83c1-f1f16a6da523.png)
![image](https://user-images.githubusercontent.com/1015040/33466966-6e3e85b2-d61f-11e7-8f28-5856b7733b33.png)
![image](https://user-images.githubusercontent.com/1015040/33466976-7c8c2b38-d61f-11e7-9f17-db6cbe01327a.png)
![image](https://user-images.githubusercontent.com/1015040/33466997-88af4ef4-d61f-11e7-80ae-bcf6b476683b.png)
![image](https://user-images.githubusercontent.com/1015040/33467162-8ac72de6-d620-11e7-926a-d90140997c8c.png)

Obviously, `moon-full` and `moon-new` are just `brightness-1` and `checkbox-blank-circle-outline`, respectively.

**Comment by goyney** [comment]
Here is a ZIP of all the moon phase SVGs from my previous post: [moon-phases.zip](https://github.com/Templarian/MaterialDesign/files/1525599/moon-phases.zip)

**Comment by goyney** [comment]
Added!
