### ISSUE TITLE
Scuba Diving related icons 

### ISSUE THREAD

**Issue by DaleOShea** [Templarian/MaterialDesign#2605]
Hi, 

Putting in a request for any icons that could be used related to scuba diving/ diving. 

Thank you

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/50836390-19dbd380-1327-11e9-9998-9d10255a3b91.png)

[ic_scuba_diving_white_fill.svg.zip](https://github.com/Templarian/MaterialDesign/files/2737105/ic_scuba_diving_white_fill.svg.zip)

Adding the `Alias` label too so we can add `snorkel` related aliases.

**Comment by MrGrigri** [comment]
Closing this in favor of #3873
