### ISSUE TITLE
Weather Forecast

### ISSUE THREAD

**Issue by puytr** [Templarian/MaterialDesign#2606]
In order to make a weather "card" in Home Asssistant, it would be useful to have a forecast icon if you would like to use multiple sources for weather forecasts.

Thanks,
Richard

**Comment by PeterShaggyNoble** [comment]
Would none of the [weather related icons](https://petershaggynoble.github.io/MDI-Sandbox/?categories=weather) work? If not, could you provide an example of what you're looking for?

**Comment by puytr** [comment]
@PeterShaggyNoble Thank you. Of course that is possible. Currently I use mdi:weather-cloudy (which is a little cloud). It should be an icon that applies for day and night and encompass all weather conditions. I came across [this](url
![image](https://user-images.githubusercontent.com/17453141/32962932-9ae87808-cbce-11e7-9d7f-f6103a46e44b.png). Maybe not perfect, but a start.
)

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/weather-partly-snowy-rainy
)](https://materialdesignicons.com/icon/weather-partly-snowy-rainy)
