### ISSUE TITLE
Oil and Gas Industry Icons

### ISSUE THREAD

**Issue by jgraygi** [Templarian/MaterialDesign#2607]
It would be nice to have some oil and gas industry specific icons.  i.e. Oil Well, Oil Tank, Gas Well etc.

**Comment by GreenTurtwig** [comment]
We currently have:
[![](https://materialdesignicons.com/icon/factory)](https://materialdesignicons.com/icon/factory)[![](https://materialdesignicons.com/icon/factory)](https://materialdesignicons.com/icon/barrel)
But we could certainly do with some more industry related icons. :cat2:

**Comment by goyney** [comment]
This issue is very open-ended and considering we have a few icons around this industry in the library already, I'm going to close this. If you have suggestions for specific icons around this topic, please open an issue for each icon you'd like to see added. Thanks!
