### ISSUE TITLE
Whistle

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2608]
A simple whistle icon.

![asset 6 1x](https://user-images.githubusercontent.com/4528551/32968824-ec1a4c12-cb9f-11e7-86e0-b1b7845304db.png)

![whistle](https://user-images.githubusercontent.com/4528551/32968827-ef2a78f0-cb9f-11e7-9b7c-3ec19642cc2b.png)

[whistle.zip](https://github.com/Templarian/MaterialDesign/files/1483832/whistle.zip)

**Comment by samirmember** [comment]
+1

**Comment by CoDEmanX** [comment]
Slightly tweaked:

![image](https://user-images.githubusercontent.com/1309249/38773109-e496d85a-4045-11e8-8477-ed008f44e22f.png)
[whistle.zip](https://github.com/Templarian/MaterialDesign/files/1911305/whistle.zip)

**Comment by Templarian** [comment]
This one needs to be brought in about a pixel on the top and bottom to make it smaller.

**Comment by Templarian** [comment]
[![whistle](https://materialdesignicons.com/icon/whistle)](https://materialdesignicons.com/icon/whistle)
