### ISSUE TITLE
Controller Connected / Disconnected

### ISSUE THREAD

**Issue by j4c3** [Templarian/MaterialDesign#261]
A pair of icons for a gaming controller would be nice.  Either Connected/Disconnected, or Enable/Disable.

I threw together a mockup using the Google Play controller, something similar, maybe?

![controllerdisconnected](https://cloud.githubusercontent.com/assets/4007204/6987670/8584e47a-d9fe-11e4-8e68-05da0d54837d.png)
![controllerconnected](https://cloud.githubusercontent.com/assets/4007204/6987678/a79426d4-d9fe-11e4-8659-8bb468ba4e9d.png)

**Comment by Templarian** [comment]
You could use the `xbox-controller` / `xbox-controller-off`. But I'll work on adding the `google-play-games` / `google-play-games-off` icons.

http://materialdesignicons.com/icon/xbox-controller
http://materialdesignicons.com/icon/xbox-controller-off

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/google-controller
http://materialdesignicons.com/icon/google-controller-off
