### ISSUE TITLE
Update Microsoft File Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2612]
The letters used used in `file-excel`, `file-powerpoint` and `file-word` differ from the ones in `file-*-box`, which are the ones MS use.

[![](https://materialdesignicons.com/icon/file-excel)](https://materialdesignicons.com/icon/file-excel) [![](https://materialdesignicons.com/icon/file-excel-box)](https://materialdesignicons.com/icon/file-excel-box)

**Comment by khornberg** [comment]
I edited svg of the `file-excel` and created another called `file-excel-outline` that use the `X` from the `file-excel-box`.
I have not run the svg through an optimizer.

[file-excel-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/1552215/file-excel-outline.svg.zip)
[file-excel.svg.zip](https://github.com/Templarian/MaterialDesign/files/1552216/file-excel.svg.zip)

**Comment by khornberg** [comment]
Is there work already being done on these?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53062308-68d06900-348e-11e9-9c6c-55802dea95dd.png)![image](https://user-images.githubusercontent.com/1015040/53062327-77b71b80-348e-11e9-9ae6-2a73f8559af9.png)
![image](https://user-images.githubusercontent.com/1015040/53062372-99b09e00-348e-11e9-9390-bca54a834ac7.png)

Our current is the outline.

[ms-files.zip](https://github.com/Templarian/MaterialDesign/files/2882786/ms-files.zip)

**Comment by Templarian** [comment]
Updated!
