### ISSUE TITLE
Flex icon request

### ISSUE THREAD

**Issue by puhfista** [Templarian/MaterialDesign#2613]
💪 

Thanks!

**Comment by Yuanruili** [comment]
@PeterShaggyNoble 
Made it both filled and outline version~
![image](https://user-images.githubusercontent.com/12135487/53956777-d4e0dd00-40dc-11e9-9883-bd41e7f98889.png)

[Flex.zip](https://github.com/Templarian/MaterialDesign/files/2941194/Flex.zip)

![image](https://user-images.githubusercontent.com/12135487/53956807-ee822480-40dc-11e9-9984-b2c79c95f98b.png)

[FlexOutline.zip](https://github.com/Templarian/MaterialDesign/files/2941195/FlexOutline.zip)

**Comment by JamesCoyle** [comment]
Need to fix the outline version so it is one contiguous area.

**Comment by goyney** [comment]
[![arm-flex](https://materialdesignicons.com/icon/arm-flex)](https://materialdesignicons.com/icon/arm-flex)[![arm-flex-outline](https://materialdesignicons.com/icon/arm-flex-outline)](https://materialdesignicons.com/icon/arm-flex-outline)
