### ISSUE TITLE
Rabbit

### ISSUE THREAD

**Issue by FabienSaulier** [Templarian/MaterialDesign#2614]
i was thinking to pets

**Comment by PeterShaggyNoble** [comment]
Related to #2590. Leaving this one open as it is requesting specific animals.

**Comment by GreenTurtwig** [comment]
Dog: https://github.com/Templarian/MaterialDesign/issues/736
Bird: https://github.com/Templarian/MaterialDesign/issues/895

Will use this issue for a rabbit icon. :cat2:

**Comment by Templarian** [comment]
Yea, we need more food icons. 😀

**Comment by augustin32** [comment]
![rabbit24](https://user-images.githubusercontent.com/14167196/33528751-438dc52a-d86e-11e7-8a78-ac9d4f8be22d.png)
![rabbit36](https://user-images.githubusercontent.com/14167196/33528752-44b84344-d86e-11e7-94ca-2c1a24399131.png)
![rabbit48](https://user-images.githubusercontent.com/14167196/33528753-45feef0a-d86e-11e7-92a9-97f299fca018.png)
[rabbit.zip](https://github.com/Templarian/MaterialDesign/files/1525066/rabbit.zip)

**Comment by FabienSaulier** [comment]
Thanks! The rabbit is very recognizable, gj !

**Comment by Templarian** [comment]
[![rabbit](https://materialdesignicons.com/icon/rabbit)](https://materialdesignicons.com/icon/rabbit)

We might want to make it more material design eventually, but works for now.

**Comment by PeterShaggyNoble** [comment]
Alias `bunny` added.
