### ISSUE TITLE
group of people

### ISSUE THREAD

**Issue by dgsioux** [Templarian/MaterialDesign#2615]
group of people for networking/peeers

**Comment by PeterShaggyNoble** [comment]
Try `account-multiple`:

[![](https://materialdesignicons.com/icon/account-multiple)](https://materialdesignicons.com/icon/account-multiple) [![](https://materialdesignicons.com/icon/account-multiple-outline)](https://materialdesignicons.com/icon/account-multiple-outline)

**Comment by PeterShaggyNoble** [comment]
Closing this out due to lack of feedback. If the icons above don't suit your needs, let us know and provide a bit more detail on what you are looking for with examples.
