### ISSUE TITLE
exhibitor booth

### ISSUE THREAD

**Issue by dgsioux** [Templarian/MaterialDesign#2616]
table or booth

**Comment by PeterShaggyNoble** [comment]
Got any examples? Given the right context, `map` *could* conceivably pass for an exhibitor's stand. Tables have proven to be tricky in the past - see #624, #1155 & #1292).

[![](https://materialdesignicons.com/icon/map)](https://materialdesignicons.com/icon/map)

**Comment by PeterShaggyNoble** [comment]
Closing dues to lack of feedback. @dgsioux, if you can provide an example of what you're looking for, we'll revisit this issue.
