### ISSUE TITLE
Mosque

### ISSUE THREAD

**Issue by sfaquadri** [Templarian/MaterialDesign#2617]
a mosque (place of worship).

Thanks

**Comment by PeterShaggyNoble** [comment]
See #1074.

Going to leave this one open as it's a request for an individual icon.

**Comment by JamesCoyle** [comment]
Need some examples of what this would look like.

**Comment by Xenomorph99** [comment]
@sfaquadri, I'm assuming this is the type of icon you're requesting? You didn't provide any examples.

<img width="150" alt="3" src="https://user-images.githubusercontent.com/1837101/97042991-1848c300-152f-11eb-9809-f715c8ebcdbc.png">
<img width="150" alt="2" src="https://user-images.githubusercontent.com/1837101/97042993-1979f000-152f-11eb-81bc-079730e3e72f.png">
<img width="150" alt="1" src="https://user-images.githubusercontent.com/1837101/97043001-1b43b380-152f-11eb-8c8e-cce798ec6d71.png">

**Comment by sfaquadri** [comment]
yes, thank you

**Comment by Xenomorph99** [comment]
How do these look? Is the dome too wide or does it look correct?

![mosque](https://user-images.githubusercontent.com/1837101/97045326-cace5500-1532-11eb-8aa4-2252528ce8bd.png)
![mosque-variant](https://user-images.githubusercontent.com/1837101/97045325-cace5500-1532-11eb-9d29-6fb449e3723f.png)

[mosque.zip](https://github.com/Templarian/MaterialDesign/files/5431419/mosque.zip)

**Comment by ablbol** [comment]
Hi, any update on this?

**Comment by goyney** [comment]
[![mosque](https://materialdesignicons.com/icon/mosque)](https://materialdesignicons.com/icon/mosque)
