### ISSUE TITLE
Moon Phases

### ISSUE THREAD

**Issue by declankenny** [Templarian/MaterialDesign#2618]
New moon, Waxing crescent, First quarter, Waxing gibbous, Full moon, Waning gibbous, Last quarter, and Waning crescent

**Comment by declankenny** [comment]
I can't seem to add a label, but this should be flagged as an Icon Request.

**Comment by PeterShaggyNoble** [comment]
Please search before posting requests for new icons; #2603 is still on the first page of issues here.
