### ISSUE TITLE
Stacked Coins

### ISSUE THREAD

**Issue by Hirshitha** [Templarian/MaterialDesign#2619]
Plz provide a stacked coins logo

**Comment by PeterShaggyNoble** [comment]
See #328 & #1283.

Given the correct context, `database` could conceivably pass for a stack of coins:

[![image](https://user-images.githubusercontent.com/15157491/33171872-d35d19f2-d045-11e7-8346-6356677eb6b7.png)](https://materialdesignicons.com/icon/database)

**Comment by k5cents** [comment]
I was actually just thinking about asking for this.

![image](https://user-images.githubusercontent.com/18021678/33297894-75dd986e-d3b1-11e7-935e-22862ad406f7.png)

`database` is close, but skewing them a little might help. I think leaving off ridges and symbols is fine.

**Comment by MrGrigri** [comment]
Again, just use `coins`? Remember that Google MD discourages skewing and perspective. This has been requested several times as @PeterShaggyNoble mentioned. 

![coins](https://materialdesignicons.com/icon/coins)

**Comment by goyney** [comment]
Considering we have `coins` and perspective is not within the guidelines for Material, we're going to close this issue. Thank you for your suggestion.
