### ISSUE TITLE
account-multiple-plus-outline, account-plus-outline, forum-outline

### ISSUE THREAD

**Issue by kishankhatri** [Templarian/MaterialDesign#2620]
Can anyone help me create Outline Icon set (PSD and SVG) for the three icons as shown below?

Thanks!

![account-multiple-plus](https://user-images.githubusercontent.com/17797960/33164439-c7d382a6-d06d-11e7-8dd3-77218ba5950e.png)

![forum](https://user-images.githubusercontent.com/17797960/33164512-202d95a4-d06e-11e7-8b4d-0a250657bec3.png)

![account-plus](https://user-images.githubusercontent.com/17797960/33164522-27f10cc6-d06e-11e7-8e36-6d4aeb7f0599.png)

**Comment by PeterShaggyNoble** [comment]
It's already available, did you try searching for it?

![](https://materialdesignicons.com/icon/account-multiple-plus)

**Comment by kishankhatri** [comment]
Hi Peter, I'm looking for Line Icons. Similar to the one below but for the three specific icons suggested in original ticket.

![account-multiple-outline](https://user-images.githubusercontent.com/17797960/33165149-b8396c40-d070-11e7-9a4a-b286398de3a2.png)

**Comment by PeterShaggyNoble** [comment]
Ah, sorry, you mean *out*line. It's also not clear that you're looking for all 3 icons as outlined variants.

**Comment by kishankhatri** [comment]
Thanks Peter for correcting. Initially, I wanted to raise separate tickets, but then put all into one and forgot to update the text message. :-)

**Comment by PeterShaggyNoble** [comment]
Would `comment-multiple-outline` suit your needs while you wait form `forum-outline`?

[![](https://materialdesignicons.com/icon/comment-multiple-outline)](https://materialdesignicons.com/icon/comment-multiple-outline)

**Comment by kishankhatri** [comment]
@PeterShaggyNoble Actually, we're using the forum icon for opening the chat tab in our mobile app. I've seen the comment-multiple-outline icon before doesn't connect well with the design.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33172898-c3b6b8f6-d049-11e7-8d33-2d3a607cabf2.png)](https://github.com/Templarian/MaterialDesign/files/1499005/account-plus-outline.zip)

**Comment by kishankhatri** [comment]
@GreenTurtwig This is amazing! Thanks a lot! Can I request for one more? #greedy 

Line Icon Account Multiple Plus 

![account-multiple-plus](https://user-images.githubusercontent.com/17797960/33174336-8fbeda58-d092-11e7-8de3-9a6302fa499b.png)

**Comment by GreenTurtwig** [comment]
Great, glad you like them. :+1: :cat2:

As for `account-multiple-plus-outline`, I'm not a fan personally as the sizing is off. :-/
[![](https://user-images.githubusercontent.com/15905797/33178475-2d72a69c-d05e-11e7-8129-e034b8e6675d.png)](https://github.com/Templarian/MaterialDesign/files/1499577/account-multiple-plus-outline.zip)

**Comment by Templarian** [comment]
[![account-plus-outline](https://materialdesignicons.com/icon/account-plus-outline)](https://materialdesignicons.com/icon/account-plus-outline) [![forum-outline](https://materialdesignicons.com/icon/forum-outline)](https://materialdesignicons.com/icon/forum-outline) [![account-multiple-plus-outline](https://materialdesignicons.com/icon/account-multiple-plus-outline)](https://materialdesignicons.com/icon/account-multiple-plus-outline)
