### ISSUE TITLE
Nurse

### ISSUE THREAD

**Issue by TheMainCoder** [Templarian/MaterialDesign#2621]
#430 Like pill icon, doctor icon, nurse icon, medicine icon, etc...
💊 
👨‍⚕️

**Comment by PeterShaggyNoble** [comment]
Pill already exists. Doctor is a dupe of #2245 (See also #2104). There are also a number of other medical-related icons you can search for. If you have any requests for specific icons, please create individual issues for them.

Leaving this open as a request for a nurse icon.

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/pill)](https://materialdesignicons.com/icon/pill)

**Comment by goyney** [comment]
We have `doctor`. A `nurse` icon wouldn't be much different. I don't want to explicitly add an assumed gender to the icon, which could potentially be the only change. For now, I think this issue is fulfilled.
