### ISSUE TITLE
Content-save outline

### ISSUE THREAD

**Issue by Warricktan** [Templarian/MaterialDesign#2622]
Could anyone please create a content-save outline that we could use for 'save as draft'. Thank you.

**Comment by Warricktan** [comment]
Great job. Is it possible to make the hole smaller. I think that's why it looks a little unusual. I imagine the hole will still touch the bottom line but that should be ok. Thank you.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/33246417-bb6b041c-d2d9-11e7-97ba-dddeb26beddd.png)

Like this? Will add in a few.

**Comment by Warricktan** [comment]
Great. Many thanks

**Comment by Templarian** [comment]
[![content-save-outline](https://materialdesignicons.com/icon/content-save-outline)](https://materialdesignicons.com/icon/content-save-outline)

**Comment by PeterShaggyNoble** [comment]
Hmm ... I wonder would it work if the "hole" was moved up from the bottom line.

**Comment by Templarian** [comment]
@PeterShaggyNoble Might, I wasn't 100% on this outline variant's design.
