### ISSUE TITLE
Table formatting when locking a risk

### ISSUE THREAD

**Issue by Warricktan** [Templarian/MaterialDesign#2623]
The locking ans unlocking of a record displays a bullet pointed note below the item Created Date  Last Modified By and LastModifiedBy. It does not display all columns

**Comment by PeterShaggyNoble** [comment]
@Warricktan, did you mean to post this here or to another repository?

If you did mean to post it here, please elaborate on the problem you're reporting and we'll reopen this issue.

**Comment by Warricktan** [comment]
@PeterShaggyNoble, sorry wrong repository. User error :) The joys of testing with too many windows open. Thanks.
