### ISSUE TITLE
Update thumbs-up-down?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2624]
There's a point in the `thumbs-up-down` path that breaks the boundaries of the SVG. I'm not sure if it's intentional or not but I've attached an updated version below. Or does the whole path need to be shifted up by half a point, maybe?

[![](https://user-images.githubusercontent.com/15157491/33207785-f59148ec-d106-11e7-981d-8ff066f1697f.png)](https://github.com/Templarian/MaterialDesign/files/1501428/thumbs-up-down.zip) ![](https://user-images.githubusercontent.com/15157491/33207761-da467d82-d106-11e7-880d-a9d2e57a7d40.png)

**Comment by GreenTurtwig** [comment]
Instead of modifying the thumb, couldn't the whole path be moved up to align with the top?

**Comment by JamesCoyle** [comment]
I'd move it all up half a unit to align it to the grid and vertically center it.

**Comment by Templarian** [comment]
[![thumbs-up-down](https://materialdesignicons.com/icon/thumbs-up-down)](https://materialdesignicons.com/icon/thumbs-up-down)

Fixed 😄

**Comment by PeterShaggyNoble** [comment]
Tested all other icons and this was the only one to break the boundaries of the `viewbox` :)
