### ISSUE TITLE
Icons with aliases missing

### ISSUE THREAD

**Issue by agersoncgps** [Templarian/MaterialDesign#2625]
When I download the complete icon set for 2.0.46 it appears to be missing some icons that you display on the home page. It have noticed in both cases the missing icons have aliases. Not sure if that is the pattern or not. I could not find either of these included in the set as detailed in https://cdn.materialdesignicons.com/2.0.46/

<img width="808" alt="screenshot 2017-11-24 11 13 48" src="https://user-images.githubusercontent.com/336441/33218253-ea6d8450-d109-11e7-8ed9-041981ddb861.png">
<img width="1080" alt="screenshot 2017-11-23 15 58 41" src="https://user-images.githubusercontent.com/336441/33218254-ea80fdb4-d109-11e7-8a0e-c31fb6cef69a.png">

**Comment by PeterShaggyNoble** [comment]
Both those icons, along with any other icons and aliases added since v2.0.46 was released, will be available in the next release.

Please remember to search the existing issues before creating new ones.

**Comment by agersoncgps** [comment]
Is there a place to see when an icon was added or to what release it belongs to. Wouldn't it make sense to put a "not released badge" on the icon details screen to cut down on confusion?

**Comment by PeterShaggyNoble** [comment]
See the [history page](https://materialdesignicons.com/history/) for details of all changes.

**Comment by Templarian** [comment]
@agersoncgps The new site under development has a flag for this. Still a lot of work left till it's online though. It's a reference to the font table basically checks if it has an assigned codepoint... so it won't reflect if the icon was renamed/modified/or anything like that, but should be good enough for quickly seeing new icons.
