### ISSUE TITLE
Is this still actively maintained?

### ISSUE THREAD

**Issue by sonic0002** [Templarian/MaterialDesign#2626]
Checked the website and it seems there is no new release for quite sometime now. Are you still building the js files which could be downloaded and integrated into web apps directly?

**Comment by PeterShaggyNoble** [comment]
Not only is this project actively maintained but it's growing. Yes, full releases are rather ... "erratic"(?) but there's a lot of work being put in on many fronts right now, including a new site (which should, hopefully, allow for more regular releases) with lots of new APIs, a push to add the remaining stock icons, aliasing everything we can and a brand new categorisation/tagging system, among many other things. All in all, the future is very, very bright for MDI and we hope you'll stick with us to see everything to come :)

**Comment by Templarian** [comment]
Learn more: #2280
