### ISSUE TITLE
Create Dresser Icon

### ISSUE THREAD

**Issue by broox** [Templarian/MaterialDesign#2628]
A Dresser or Chest of Drawers would be handy for some home automation platforms.

**Comment by goyney** [comment]
[![dresser](https://materialdesignicons.com/icon/dresser)](https://materialdesignicons.com/icon/dresser)[![dresser-outline](https://materialdesignicons.com/icon/dresser-outline)](https://materialdesignicons.com/icon/dresser-outline)
