### ISSUE TITLE
[Site] Add search for tags 

### ISSUE THREAD

**Issue by retyui** [Templarian/MaterialDesign#2629]
Why is your search a little functional?
![image](https://user-images.githubusercontent.com/4661784/33257777-6e680644-d368-11e7-9296-79b7f58394f5.png)

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site

The current site isn't getting upgrades and is in a code frozen state as the open source version is being developed. Please enter any requests in the above repo. You can see on the dev box the tag filter (very rough implementation). http://dev.materialdesignicons.com/icons/social-media

Thanks!
