### ISSUE TITLE
select-ellipse, select-free, select-fuzzy, select-by-color

### ISSUE THREAD

**Issue by keeferrourke** [Templarian/MaterialDesign#263]
Icon request for different types of selection. If you're familiar with Photoshop or GIMP, you'd be aware of how important different types of selection are. Iconography for each of these types of selection should also be simple and distinct.

An example from GIMP:
![](http://a.pomf.se/dytxxs.png)
left to right:
- [x] select-ellipse
- [x] select-free
- [x] select-fuzzy
- [x] select-by-color

**Comment by Templarian** [comment]
I renamed the icons so they are all `select-` (also no `u`, sorry we use the incorrect spelling in this icon set :stuck_out_tongue_closed_eyes:).

**Comment by CoDEmanX** [comment]
select-fuzzy could just be a general purpose wand, select-by-color seems too difficult and specialized to me. I'm all for select-rectangle and select-ellipse. Free selection could be called select-lasso, or at least we tagged with `lasso`.

**Comment by mooce** [comment]
select-lasso would be super useful

**Comment by Templarian** [comment]
Added high priority label to this one, and the current Milestone so it isn't overlooked.

**Comment by Louistwee** [comment]
### select ellipse
![image](https://user-images.githubusercontent.com/27563848/44910833-f378ac80-ad24-11e8-88bf-aae00c84d9d0.png)
``M 12 5.9980469 C 11.661344 5.9980469 11.329253 6.0136251 11 6.0371094 L 11 8.0625 C 11.329902 8.0339095 11.656616 7.9980469 12 7.9980469 C 12.343602 7.9980469 12.670531 8.0316409 13 8.0605469 L 13 6.046875 C 12.669641 6.0229725 12.340157 5.9980469 12 5.9980469 z M 9 6.3359375 C 8.2908738 6.4995054 7.6199888 6.718749 7 6.9921875 L 7 9.2441406 C 7.5684557 8.9058422 8.2429408 8.6186116 9 8.40625 L 9 6.3359375 z M 15 6.3457031 L 15 8.4160156 C 15.750341 8.6294845 16.434087 8.9071531 17 9.2441406 L 17 7 L 17.013672 7 C 16.391501 6.7242045 15.711386 6.5113366 15 6.3457031 z M 5 8.2109375 C 4.0808201 8.9734221 3.3958487 9.9209239 3.1289062 11 L 5 11 L 5 8.2109375 z M 19 8.2109375 L 19 11 L 20.869141 11 C 20.602314 9.9213926 19.91857 8.9732579 19 8.2109375 z M 3.1269531 13 C 3.3931108 14.08115 4.0786935 15.029872 5 15.792969 L 5 13 L 3.1269531 13 z M 19 13 L 19 15.791016 C 19.920248 15.028205 20.605136 14.080337 20.871094 13 L 19 13 z M 7 14.757812 L 7 17.009766 C 7.6183135 17.282466 8.2937578 17.492155 9 17.65625 L 9 15.585938 C 8.2496299 15.372007 7.56591 15.094664 7 14.757812 z M 17 14.757812 C 16.430855 15.095486 15.756496 15.382806 15 15.595703 L 15 17.666016 C 15.71211 17.501632 16.380551 17.27381 17.003906 17 L 17 17 L 17 14.757812 z M 13 15.941406 C 12.67019 15.970089 12.343384 16.005859 12 16.005859 C 11.656505 16.005859 11.329424 15.972375 11 15.943359 L 11 17.955078 C 11.330197 17.978904 11.66013 18.003906 12 18.003906 C 12.338656 18.003906 12.670814 17.988328 13 17.964844 L 13 15.941406 z ``
### select ellipse 2
![image](https://user-images.githubusercontent.com/27563848/44910941-4eaa9f00-ad25-11e8-8916-19aa2cc524f7.png)

``M 12 5.9980469 C 11.661344 5.9980469 11.329253 6.0136251 11 6.0371094 L 11 8.0625 C 11.329902 8.0339095 11.656616 7.9980469 12 7.9980469 C 12.343602 7.9980469 12.670531 8.0316409 13 8.0605469 L 13 6.046875 C 12.669641 6.0229725 12.340157 5.9980469 12 5.9980469 z M 9 6.3359375 C 8.2908738 6.4995054 7.6199888 6.718749 7 6.9921875 L 7 9 L 7.4863281 9 C 7.9458792 8.7711105 8.4409458 8.5630695 9 8.40625 L 9 6.3359375 z M 15 6.3457031 L 15 8.4160156 C 15.551406 8.5728882 16.046716 8.7757237 16.505859 9 L 17 9 L 17 7 L 17.013672 7 C 16.391501 6.7242045 15.711386 6.5113366 15 6.3457031 z M 4.2109375 9 C 3.6987639 9.5963327 3.3108587 10.264484 3.1289062 11 L 5 11 L 5 9 L 4.2109375 9 z M 19 9 L 19 11 L 20.869141 11 C 20.687267 10.264803 20.300672 9.5964355 19.789062 9 L 19 9 z M 3.1269531 13 C 3.3079781 13.735335 3.6938047 14.403922 4.2050781 15 L 5 15 L 5 13 L 3.1269531 13 z M 19 13 L 19 15 L 19.791016 15 C 20.302768 14.403742 20.689966 13.73575 20.871094 13 L 19 13 z M 7 15 L 7 17.009766 C 7.6183135 17.282466 8.2937578 17.492155 9 17.65625 L 9 15.585938 C 8.4469966 15.428275 7.9503603 15.224981 7.4902344 15 L 7 15 z M 16.515625 15 C 16.055366 15.2291 15.559426 15.438267 15 15.595703 L 15 17.666016 C 15.71211 17.501632 16.380551 17.27381 17.003906 17 L 17 17 L 17 15 L 16.515625 15 z M 13 15.941406 C 12.67019 15.970089 12.343384 16.005859 12 16.005859 C 11.656505 16.005859 11.329424 15.972375 11 15.943359 L 11 17.955078 C 11.330197 17.978904 11.66013 18.003906 12 18.003906 C 12.338656 18.003906 12.670814 17.988328 13 17.964844 L 13 15.941406 z ``
### select ellipse 3
![image](https://user-images.githubusercontent.com/27563848/44911029-a3e6b080-ad25-11e8-9c7a-f49d65586aec.png)
``M 12 5.9980469 C 11.661344 5.9980469 11.329253 6.0136251 11 6.0371094 L 11 8 L 11.96875 8 C 11.979447 7.9999313 11.989271 7.9980469 12 7.9980469 C 12.010738 7.9980469 12.020544 7.9999356 12.03125 8 L 13 8 L 13 6.046875 C 12.669641 6.0229725 12.340157 5.9980469 12 5.9980469 z M 7 7 L 7 9 L 7.4863281 9 C 7.9458792 8.7711105 8.4409458 8.5630695 9 8.40625 L 9 7 L 7 7 z M 15 7 L 15 8.4160156 C 15.551406 8.5728882 16.046716 8.7757237 16.505859 9 L 17 9 L 17 7 L 15 7 z M 4.2109375 9 C 3.6987639 9.5963327 3.3108587 10.264484 3.1289062 11 L 5 11 L 5 9 L 4.2109375 9 z M 19 9 L 19 11 L 20.869141 11 C 20.687267 10.264803 20.300672 9.5964355 19.789062 9 L 19 9 z M 3.1269531 13 C 3.3079781 13.735335 3.6938047 14.403922 4.2050781 15 L 5 15 L 5 13 L 3.1269531 13 z M 19 13 L 19 15 L 19.791016 15 C 20.302768 14.403742 20.689966 13.73575 20.871094 13 L 19 13 z M 7 15 L 7 17 L 9 17 L 9 15.585938 C 8.4469966 15.428274 7.9503603 15.224981 7.4902344 15 L 7 15 z M 16.515625 15 C 16.055366 15.2291 15.559426 15.438267 15 15.595703 L 15 17 L 17 17 L 17 15 L 16.515625 15 z M 11 16 L 11 17.955078 C 11.330197 17.978904 11.66013 18.003906 12 18.003906 C 12.338656 18.003906 12.670814 17.988328 13 17.964844 L 13 16 L 12.091797 16 C 12.060541 16.00057 12.03152 16.005859 12 16.005859 C 11.967797 16.005859 11.93818 16.000557 11.90625 16 L 11 16 z ``
### select ellipse 4
![image](https://user-images.githubusercontent.com/27563848/44911098-fb851c00-ad25-11e8-99ea-9748e352e150.png)
``M 12 5.9980469 C 11.661344 5.9980469 11.329253 6.0136251 11 6.0371094 L 11 8 L 11.96875 8 C 11.979447 7.9999313 11.989271 7.9980469 12 7.9980469 C 12.010738 7.9980469 12.020544 7.9999356 12.03125 8 L 13 8 L 13 6.046875 C 12.669641 6.0229725 12.340157 5.9980469 12 5.9980469 z M 9 6.3359375 C 8.2908738 6.4995054 7.6199888 6.718749 7 6.9921875 L 7 8 L 9 8 L 9 6.3359375 z M 15 6.3457031 L 15 8 L 17 8 L 17 7 L 17.013672 7 C 16.391501 6.7242045 15.711386 6.5113366 15 6.3457031 z M 4.2109375 9 C 3.6987639 9.5963327 3.3108587 10.264484 3.1289062 11 L 5 11 L 5 9 L 4.2109375 9 z M 19 9 L 19 11 L 20.869141 11 C 20.687267 10.264803 20.300672 9.5964355 19.789062 9 L 19 9 z M 3.1269531 13 C 3.3079781 13.735335 3.6938047 14.403922 4.2050781 15 L 5 15 L 5 13 L 3.1269531 13 z M 19 13 L 19 15 L 19.791016 15 C 20.302768 14.403742 20.689966 13.73575 20.871094 13 L 19 13 z M 7 16 L 7 17.009766 C 7.6183135 17.282466 8.2937578 17.492155 9 17.65625 L 9 16 L 7 16 z M 11 16 L 11 17.955078 C 11.330197 17.978904 11.66013 18.003906 12 18.003906 C 12.338656 18.003906 12.670814 17.988328 13 17.964844 L 13 16 L 12.091797 16 C 12.060541 16.00057 12.03152 16.005859 12 16.005859 C 11.967797 16.005859 11.93818 16.000557 11.90625 16 L 11 16 z M 15 16 L 15 17.666016 C 15.71211 17.501632 16.380551 17.27381 17.003906 17 L 17 17 L 17 16 L 15 16 z ``

## Overview
![image](https://user-images.githubusercontent.com/27563848/44910833-f378ac80-ad24-11e8-88bf-aae00c84d9d0.png)
![image](https://user-images.githubusercontent.com/27563848/44910941-4eaa9f00-ad25-11e8-8916-19aa2cc524f7.png)
![image](https://user-images.githubusercontent.com/27563848/44911029-a3e6b080-ad25-11e8-9c7a-f49d65586aec.png)
![image](https://user-images.githubusercontent.com/27563848/44911098-fb851c00-ad25-11e8-99ea-9748e352e150.png)

**Comment by goyney** [comment]
@Louistwee It is preferred to attach a ZIP file with the SVG(s) in it as to not clutter up the issues with a bunch of path data.

**Comment by Louistwee** [comment]
### select lasso 1
![image](https://user-images.githubusercontent.com/27563848/44916527-41e27700-ad36-11e8-8ee2-30f6b6d51999.png)
[Path.txt](https://github.com/Templarian/MaterialDesign/files/2340284/Path.txt)

**Comment by Louistwee** [comment]
Wand
![image](https://user-images.githubusercontent.com/27563848/44920656-ccc86f00-ad40-11e8-97ac-2b8cf2b629d4.png)
[Path.txt](https://github.com/Templarian/MaterialDesign/files/2340594/Path.txt)

**Comment by PeterShaggyNoble** [comment]
Here's Google's new `lasso_select` icon:

[![lasso-select](http://mdi.houseofdesign.ie/tools/preview/?icon=lasso-select&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by goyney** [comment]
Note to @Templarian: Looks like `lasso` and `select-color` from @Louistwee and `lasso-select` should be added from Google.

**Comment by Templarian** [comment]
[![select-color](https://materialdesignicons.com/icon/select-color)](https://materialdesignicons.com/icon/select-color)

**Comment by goyney** [comment]
`lasso` (Louistwee) and `lasso-select` (Google) are the last two to add here.

**Comment by goyney** [comment]
`lasso` and `selection-ellipse-arrow-inside` have been added. 😄
