### ISSUE TITLE
Icon USB-stick and DVD

### ISSUE THREAD

**Issue by Kessi** [Templarian/MaterialDesign#2631]

**Comment by PeterShaggyNoble** [comment]
`disk` should cover DVD and USB stick is a duplicate of #1078. If they're not what you're looking for, please provide more detail and we'll reopen this issue.

[![disk](https://user-images.githubusercontent.com/15157491/33272405-f4604c3e-d381-11e7-97d3-2e04ae100fca.png)](https://materialdesignicons.com/icon/disk)
