### ISSUE TITLE
More "account-xxx" icons

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#2632]
Hi! More icons for account (e.g. https://materialdesignicons.com/icon/account-check) would be nice. Thanks in advance!

- [ ] account-coffee (with https://materialdesignicons.com/icon/coffee)
- [ ] account-cancel (with https://materialdesignicons.com/icon/cancel)
- [ ] account-home (with https://materialdesignicons.com/icon/home

**Comment by GreenTurtwig** [comment]
`account-coffee` is probably way too specific.

[![](https://materialdesignicons.com/icon/home-account)](https://materialdesignicons.com/icon/home-account)

Not sure about `account-cancel`.

If it's a UI with only one purpose (i.e. adding accounts) it would be better to just use the standard `coffee`, `cancel` and `home` icons.

**Comment by PeterShaggyNoble** [comment]
Would `account-remove` work as `account-cancel`?

Can you provide a use case for `account-coffee`?

**Comment by matthew2402** [comment]
I need something that indicates a break so coffee fits perfectly I think but can be something else. And to keep that with the same style I thought so about "home" and "cancel" as well

Usecase:
I have three buttons where the user can either set itself as "in break", "not available" and "home".

**Comment by MrGrigri** [comment]
I believe you need to rethink your UI. If all three actions imply actions to an employee, having a home, coffee, and ban icon should convey the message properly.
