### ISSUE TITLE
Scooter / Moped / Vespa

### ISSUE THREAD

**Issue by casperschou** [Templarian/MaterialDesign#2634]
Searching for a material design icon, something like this, but in the official Google style - somewhere in between the existing Bike-icon and the Motorcycle-icon.
![moped](https://user-images.githubusercontent.com/9927518/45406952-4ed16580-b668-11e8-8fca-c3790cd2a16b.png)

**Comment by casperschou** [comment]
Still needing this :)

**Comment by PeterShaggyNoble** [comment]
Would the icon requested in #2660 suit your needs?

**Comment by casperschou** [comment]
No, not really. I am not looking for a bike or motorcycle icon.

**Comment by PeterShaggyNoble** [comment]
Here's Google's take on it:

[![delivery-dining](https://user-images.githubusercontent.com/15157491/54348150-618d1d00-4640-11e9-85d7-d15cca517513.png)](https://github.com/Templarian/MaterialDesign/files/2965800/delivery-dining.zip)

**Comment by casni** [comment]
Thanks Peter, you da man!
Not exactly the style I was expecting from Google, but okay... :)

**Comment by PeterShaggyNoble** [comment]
It's was added to their Material Icons Extended font yesterday. You can preview all the icons in that set [here](https://petershaggynoble.github.io/MDI-Sandbox/extended/).

**Comment by mohamadsalari** [comment]
i think this one could help. i design it by myself. pixel perfect
![vespa_delivery](https://user-images.githubusercontent.com/53234803/61740977-25fc1f80-ada5-11e9-8f59-45a698050c60.png)

**Comment by mohamadsalari** [comment]
> No, not really. I am not looking for a bike or motorcycle icon.

if this one is good for you, just put your email here to send it for you
![vespa_delivery](https://user-images.githubusercontent.com/53234803/61741136-770c1380-ada5-11e9-8a08-ccc6bedebdf0.png)

**Comment by goyney** [comment]
[![moped](https://materialdesignicons.com/icon/moped)](https://materialdesignicons.com/icon/moped)
