### ISSUE TITLE
Add Alekhen as Contributor

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2635]
@Alekhen, could you provide us with the following info, please?

- [ ] Name: 
- [ ] Twitter: 
- [ ] Website (if wanted): 
- [ ] Image (if github, just say github): 
- [ ] Description/Short Bio:

@Templarian, the following icons will need to be assigned over:
- [ ] [`hulu`](https://materialdesignicons.com/icon/hulu) (#2129)
- [ ] `message-alert-outline` (#2116)
- [ ] [`rice`](https://materialdesignicons.com/icon/rice) (#2147)
- [ ] [`ring`](https://materialdesignicons.com/icon/ring) (#2152)
- [ ] [`soy-sauce`](https://materialdesignicons.com/icon/soy-sauce) (#2147)

**Comment by Templarian** [comment]
Just in case he had notifications off, I sent him an email.

**Comment by Alekhen** [comment]
@Templarian Good thing you did haha I've been busy and haven't been paying attention to notifications.

Name: Colton Wiscombe
Twitter: http://twitter.com/coltonwiscombe
Website: http://coltonjameswiscombe.com
Image: Same as github and twitter account
Description/Short Bio: I help brands connect to people in meaningful ways by blending innovation with practicality to solve problems and create unique experiences.

**Comment by Templarian** [comment]
Brand icons are going to be reassigned to the the shared contributor account (wip for this release), but all others were transferred over.

Welcome! https://materialdesignicons.com/contributor/Colton-Wiscombe
