### ISSUE TITLE
Toolbox Icon

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2636]
Toolbox icon

[![image](https://user-images.githubusercontent.com/15157491/33325931-8d471b3e-d44b-11e7-8a88-aefdf499596c.png)](https://github.com/Templarian/MaterialDesign/files/1510275/toolbox.zip)

**Comment by PeterShaggyNoble** [comment]
See also Google's `service toolbox` icon:

![service toolbox](https://user-images.githubusercontent.com/15157491/33325004-03e4a700-d449-11e7-85b2-ccba04ab45b4.png)

**Comment by OctoberJemini** [comment]
That would work as well.  When do we expect to have that in the collection?

**Comment by Templarian** [comment]
@OctoberJemini It was one of their newest icons in the extended set. We're slowly adding them. Using this issue to track this specific one.

**Comment by Templarian** [comment]
[![toolbox-outline](https://materialdesignicons.com/icon/toolbox-outline)](https://materialdesignicons.com/icon/toolbox-outline) [![toolbox](https://materialdesignicons.com/icon/toolbox)](https://materialdesignicons.com/icon/toolbox)
