### ISSUE TITLE
Contributor access

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#2638]
Hello, I am a contributor (15+ icons). According to the information on contributors, I should have been granted access to the site to help tag and create more icons, however I was never given this information/access. How can I get that?

**Comment by Templarian** [comment]
Follow me on twitter, I'll DM you the slack channel invite.

**Comment by goyney** [comment]
I followed this afternoon. My Twitter handle is @mririgo. Thanks!
