### ISSUE TITLE
youtube and vimeo icons

### ISSUE THREAD

**Issue by 7immy** [Templarian/MaterialDesign#264]
would be awesome to include youtube and vimeo to the list :)

- [ ] youtube
- [ ] vimeo

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/vimeo
http://materialdesignicons.com/icon/youtube-play (already exists)

If you want the full YouTube logo, that doesn't fit the icon pack's style, but can be downloaded below:

https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/youtube.svg

Then simply place it into: http://materialdesignicons.com/custom

**Comment by Templarian** [comment]
I should mention why I didn't simply place the "You" above the "Tube", their guidelines do not allow that and I don't want to ignore that.
