### ISSUE TITLE
New icon: Salesforce

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#2640]
An icon for Salesforce.

As per the CONTRIBUTING document:
> "Please know that social media icons or **largely used products** are the only brand icons we allow."

![salesforce](https://user-images.githubusercontent.com/1015040/33345899-e2579292-d45b-11e7-90d3-6290a6ecf6dd.png)
[salesforce.zip](https://github.com/Templarian/MaterialDesign/files/1511718/salesforce.zip)

**Comment by Templarian** [comment]
Yea, safe to say they are large enough. 😆 Will add shortly.

**Comment by Templarian** [comment]
[![salesforce](https://materialdesignicons.com/icon/salesforce)](https://materialdesignicons.com/icon/salesforce)
