### ISSUE TITLE
Materialize currency-btc

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2641]
I feel as thought the current `currency-btc` icon feels more like a brand icon than a currency icon. The other currencies like `currency-usd` and `currency-gbp` are like materialized version of their unicode equivalents ($, £). 

The current `currency-btc` is more an un-materialized brand icon (like `office`, `skype`, or `telegram`)

I don't know if Bitcoin is popular enough to deserve _two_ icons, but I feel like a more material `currency-` type icon should be added.

Here are the unicode characters for a few currencies:
![unicode](https://user-images.githubusercontent.com/18021678/33353451-f1831c94-d47b-11e7-9475-440c1c2e304e.png)
Here are the material icons we have:
![mdi](https://user-images.githubusercontent.com/18021678/33353452-f18ce030-d47b-11e7-8160-44fdfde5abd2.png)
You can see how the bitcoin icon we have is more similar to the brand icon than one used to actually represent a _unit_ of bitcoin:
![image](https://user-images.githubusercontent.com/18021678/33353475-0ad7dbbc-d47c-11e7-8d5c-8bea55bc4d78.png)

**Comment by Templarian** [comment]
Agree with this decision to make the currency the more general version and the brand separate.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/33359589-2557aa58-d495-11e7-99fc-32f1fb37e15b.png)

This look Material Design enough?

**Comment by GreenTurtwig** [comment]
First one, definitely.

**Comment by PeterShaggyNoble** [comment]
First one for me too.

Although, I've never understood why Bitcoin (and now Ethereum) was considered to be a currency here, instead of a brand like; just chalked it down to something going over my head!

**Comment by k5cents** [comment]
Probably the first one for me as well. 

@PeterShaggyNoble You could say "I own ₿1.0045" and use a symbol in a completely different context than you would when representing the _idea_ of Bitcoin has a brand/technology.

**Comment by k5cents** [comment]
I might even suggest the current brand-like Bitcoin logo be tilted to match the [Bitcoin.org](https://bitcoin.org) logo (included in my original post), maybe enclosed within a circle?

**Comment by Templarian** [comment]
Done.

[![currency-btc](https://materialdesignicons.com/icon/currency-btc)](https://materialdesignicons.com/icon/currency-btc)
