### ISSUE TITLE
Add bitcoin-brand

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2643]
As per #2641, the _current_ `currency-btc` icon might need to be tilted enclosed in a circle to match the official [Bitcoin.org](https://bitcoin.org/en/) logo and distinguish from the actual currency icon.

![image](https://user-images.githubusercontent.com/18021678/33390542-3b7b9546-d504-11e7-96f6-02929d3a39a7.png)

From the [Bitcoin.org glossary](https://bitcoin.org/en/vocabulary):

> Bitcoin (with capitalization) is used when describing the concept of Bitcoin, or the entire network itself. e.g. "I was learning about the Bitcoin protocol today."

vs

> bitcoin (without capitalization) is used to describe bitcoins as a unit of account. e.g. "I sent ten bitcoins today."; it is also often abbreviated BTC or XBT.

In terms of icons, you'd use `bitcoin-logo` when referring to the first and `currency-btc` when referring to the second.

Attached is the raw version they use on their header logotype on [Bitcoin.org](https://bitcoin.org/en/).

[bitcoin-brand.zip](https://github.com/Templarian/MaterialDesign/files/1514916/bitcoin-brand.zip)

**Comment by Templarian** [comment]
[![bitcoin](https://materialdesignicons.com/icon/bitcoin)](https://materialdesignicons.com/icon/bitcoin)

Probably best to keep the original "B". Bitcoin doesn't have a true "official" logo, just a symbol. People can apply a rotation/circle if needed.
