### ISSUE TITLE
Accessories

### ISSUE THREAD

**Issue by ShahnazK** [Templarian/MaterialDesign#2645]
Please create this one.

**Comment by PeterShaggyNoble** [comment]
Please elaborate, with examples.

**Comment by goyney** [comment]
Are you talking about Windows Accessories? If so, there are already variations of the more common ones:

**Paint:**
[![](https://materialdesignicons.com/icon/palette)](https://materialdesignicons.com/icon/palette)

**Calendar:**
[![](https://materialdesignicons.com/icon/calendar)](https://materialdesignicons.com/icon/calendar)

**Calculator:**
[![](https://materialdesignicons.com/icon/calculator)](https://materialdesignicons.com/icon/calculator)

**Notepad:**
[![](https://materialdesignicons.com/icon/notebook)](https://materialdesignicons.com/icon/notebook)

**Comment by ShahnazK** [comment]
No, I am not referring Windows Accessories. I need the icons for a product accessories. e.g. mobile phone accessories, car accessories, etc.
RegardsShahnaz

    On ‎Friday‎, ‎01‎ ‎December‎ ‎2017‎ ‎07‎:‎31‎:‎16‎ ‎IST, Michael Irigoyen <notifications@github.com> wrote:  
 
 
Are you talking about Windows Accessories? If so, there are already variations of the more common ones:

Paint:


Calendar:


Calculator:


Notepad:

**Comment by GreenTurtwig** [comment]
That still doesn't really help much. :-/  
Could you give some examples of what you're looking for?

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @ShahnazK, if you can provide an example of what you're looking for then we'll revisit this issue.
