### ISSUE TITLE
Desk Phone

### ISSUE THREAD

**Issue by vegarda** [Templarian/MaterialDesign#2646]
With dialpad, handset, display

[desk phone | google images](https://www.google.no/search?newwindow=1&safe=off&biw=1920&bih=989&tbm=isch&sa=1&ei=G8QfWoeeJsOB6AT95KhQ&q=desk+phone&oq=desk+phone&gs_l=psy-ab.3..0i67k1j0l9.2220.2220.0.2498.1.1.0.0.0.0.105.105.0j1.1.0....0...1c.1.64.psy-ab..0.1.103....0.QE-c7gltHJM)

**Comment by PeterShaggyNoble** [comment]
Would `phone-classic` work for you?

[![phone-classic](https://user-images.githubusercontent.com/15157491/33422885-1c4e4e10-d5af-11e7-9020-989932332fcd.png)](https://materialdesignicons.com/icon/phone-classic)

**Comment by GreenTurtwig** [comment]
It's called `deskphone`?

[![](https://materialdesignicons.com/icon/deskphone)](https://materialdesignicons.com/icon/deskphone)

**Comment by PeterShaggyNoble** [comment]
D'oh! Thanks, @GreenTurtwig. Hadn't had my caffeine yet!

**Comment by GreenTurtwig** [comment]
Haha, brilliant. :-P
