### ISSUE TITLE
Logistics icons

### ISSUE THREAD

**Issue by BGehrels** [Templarian/MaterialDesign#2649]
It would be great to have some more icons related to logistics/shipping:
- cargo container (#2062)
- container vessel (could also be reused as docker icon)
- docks (maybe a pier with water/wave and a crane)
- airport
- palets

**Comment by goyney** [comment]
Here's a couple I've been working on:

![image](https://user-images.githubusercontent.com/1015040/33465506-3770a55a-d616-11e7-98a1-3270d18569ee.png)
![image](https://user-images.githubusercontent.com/1015040/33465509-3c2ab964-d616-11e7-90f9-09bc947204e0.png)

**Comment by JamesCoyle** [comment]
Pallet doesn't work as we can't show 3d elements (with some exceptions).

**Comment by goyney** [comment]
@JamesCoyle Can you elaborate?

**Comment by JamesCoyle** [comment]
The material guidelines state: "Don’t tilt, rotate, or make icons appear dimensional."

https://material.io/guidelines/style/icons.html#icons-system-icons

**Comment by goyney** [comment]
I guess there is this, but that looks more like a grid. Or a garage door, or something...

![image](https://user-images.githubusercontent.com/1015040/33467547-3454779a-d623-11e7-8032-bc131015ae4f.png)

**Comment by JamesCoyle** [comment]
How about a side on view? Maybe with a box on it?

**Comment by goyney** [comment]
Meh.
![image](https://user-images.githubusercontent.com/1015040/33467808-3e89ea54-d625-11e7-82ff-ee223a26722a.png)

**Comment by goyney** [comment]
Here are finals of a few of the ones I came up with:
[![image](https://user-images.githubusercontent.com/1015040/33535226-4185dd42-d87a-11e7-8f2e-4d73cae047a7.png)](https://github.com/Templarian/MaterialDesign/files/1525586/airport.zip)

[![image](https://user-images.githubusercontent.com/1015040/33535266-86890400-d87a-11e7-8efb-d7d28702ab3e.png)](https://github.com/Templarian/MaterialDesign/files/1525594/pier.zip)

[![image](https://user-images.githubusercontent.com/1015040/33535279-90a8b0f2-d87a-11e7-9110-aab457ddfe45.png)](https://github.com/Templarian/MaterialDesign/files/1525596/pier-crane.zip)

**Comment by BGehrels** [comment]
Wow @goyney , those look amazing. Clear, precise and beautiful, especially the airport icon. 

Regarding the piers, i'm a bit unsure if they may be a bit ambiguous: Since the water is below the build-up structure, it may look like a swimming object (oil drilling platform, working ponton, ...) to some viewers. 

I tried around a bit with your final version of pier crane and came up with this scribble: It moves the water from below the pier to the area next to the pier.
[pier-crane.zip](https://github.com/Templarian/MaterialDesign/files/1529419/pier-crane.zip)
May be this makes it even more precise?

**Comment by goyney** [comment]
@BGehrels I think I would disagree. The version with the water allows the icon to represent many things, as you stated, such as a oil platform, working pontoon, or a crane on a pier. Allowing one icon to serve several generic meanings keeps the library from having several variations of one type of icon that, in my opinion, just clutters the library for marginal gain.

Of course, that is my two cents. :)

**Comment by Templarian** [comment]
[![airport](https://materialdesignicons.com/icon/airport)](https://materialdesignicons.com/icon/airport) [![crane](https://materialdesignicons.com/icon/crane)](https://materialdesignicons.com/icon/crane) [![pier](https://materialdesignicons.com/icon/pier)](https://materialdesignicons.com/icon/pier) [![pier-crane](https://materialdesignicons.com/icon/pier-crane)](https://materialdesignicons.com/icon/pier-crane)

**Comment by Templarian** [comment]
Please create another issue for the pallet icon. We'll need to think through that. Not a fan of the 3D perspective, but not sure.
