### ISSUE TITLE
chart-candlesticks, chart-ohlc, chart-hexagon

### ISSUE THREAD

**Issue by dmitrykvochkin** [Templarian/MaterialDesign#265]
Would be useful to have "chart type" icons like:
Candlesticks, OHLC bars, Line, etc

![chartiecons](https://cloud.githubusercontent.com/assets/5006598/7023921/f9408e98-dd30-11e4-9616-0cd08926d8cf.png)
- [ ] chart-candlesticks (financial chart usually)
- [ ] chart-ohlc (Open-high-low-close)
- [ ] chart-hexagon

**Comment by Templarian** [comment]
Line chart exists (`chart-line`). The others need to be added though. I added hex to your list also since I need that for a client's project.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
