### ISSUE TITLE
dolly

### ISSUE THREAD

**Issue by awmottaz** [Templarian/MaterialDesign#2650]
I would like a dolly/hand-truck icon. Here are a few ideas:

![Plain dolly](https://www.myaccountingcourse.com/inventory/images/inventory-definition.png)

![Hefty dolly](https://www.trekglobal.com/wp-content/uploads/icon-inventory.png)

![With person](http://www.windscrm.com/static/index/img/icon_inventory.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/33466356-5d44ee58-d61b-11e7-8d35-811142e2d474.png)

**Comment by goyney** [comment]
[![image](https://user-images.githubusercontent.com/1015040/33535331-03ae3ee6-d87b-11e7-8dd5-255e3f96ab21.png)](https://github.com/Templarian/MaterialDesign/files/1525598/hand-truck.zip)

**Comment by awmottaz** [comment]
Looks great! Thanks, @goyney!

**Comment by CoDEmanX** [comment]
From the game Pizza Connection 3: ![image](https://user-images.githubusercontent.com/1309249/38044533-61073874-32ba-11e8-9ec8-1b7cb69e611c.png)

**Comment by Templarian** [comment]
Added. 😄  Also added the alias `hand-truck`.
