### ISSUE TITLE
Sunscreen Bottle 

### ISSUE THREAD

**Issue by aershov24** [Templarian/MaterialDesign#2651]

**Comment by MrGrigri** [comment]
Idk, if this will work out the way that you want. The best that I could come up with (maybe others will do better), isn't really all that recognizable at 1x.

![image](https://user-images.githubusercontent.com/4528551/33896762-e41c1e48-df20-11e7-8f10-1bcb3c745613.png)

**Comment by PeterShaggyNoble** [comment]
A slightly more abstract option could be to layer `block-helper` over `weather-sunny`:

![sun-block](https://user-images.githubusercontent.com/15157491/33897178-b1fdff76-df5c-11e7-94f4-d010631cf5f1.png)

**Comment by MrGrigri** [comment]
I believe they both still suffer from lack of recognition at 1x.

**Comment by goyney** [comment]
@aershov24 Would the icons proposed in https://github.com/Templarian/MaterialDesign/issues/3225 solve your use case?

**Comment by goyney** [comment]
Closing because the `Needs More Info` label was added a week ago with no response. We've since added `shield-sun(-outline)` which should serve the use case of shielding, blocking, or screening the sun in proper context. Thank you for your suggestion.
