### ISSUE TITLE
layers-triple

### ISSUE THREAD

**Issue by vieb84** [Templarian/MaterialDesign#2653]
Like existing [double layer](https://materialdesignicons.com/icon/layers), except with 3 layers instead of 2

**Comment by PeterShaggyNoble** [comment]
You *could* (ab)use the `buffer` brand icon:

[![buffer](https://user-images.githubusercontent.com/15157491/33492898-55ba79b4-d6b6-11e7-8f4f-9d4c09175845.png)](https://materialdesignicons.com/icon/buffer)

**Comment by Templarian** [comment]
We should probably make a standard layer variant for this use case. 😄

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33658289-13b74364-da74-11e7-9dd3-43d2b3a6a47e.png)](https://github.com/Templarian/MaterialDesign/files/1534875/layers-triple.zip)

**Comment by goyney** [comment]
[![layers-triple](https://materialdesignicons.com/icon/layers-triple)](https://materialdesignicons.com/icon/layers-triple)[![layers-triple-outline](https://materialdesignicons.com/icon/layers-triple-outline)](https://materialdesignicons.com/icon/layers-triple-outline)
