### ISSUE TITLE
Cycle fast icon

### ISSUE THREAD

**Issue by roshanrajaratnam** [Templarian/MaterialDesign#2655]
Cycle fast similar to existing run fast icon

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33657887-9b964c6e-da72-11e7-92d5-ed5aef1d4676.png)](https://github.com/Templarian/MaterialDesign/files/1534836/bike-fast.zip)

**Comment by roshanrajaratnam** [comment]
looks great!

**Comment by goyney** [comment]
I think I would have the "speed lines" follow the contour of the biker's back. They seem weird with square terminals and aren't consistent with other similar icons, like `clock-fast`.

**Comment by goyney** [comment]
[![bike-fast](https://materialdesignicons.com/icon/bike-fast)](https://materialdesignicons.com/icon/bike-fast)
