### ISSUE TITLE
Crown Icon

### ISSUE THREAD

**Issue by augustin32** [Templarian/MaterialDesign#2657]
The crown icon found in YouTube chat ![image](https://user-images.githubusercontent.com/14167196/33528514-426d00ec-d86a-11e7-9015-51c213530759.png)
(and i know that there is already a crown icon in the set)
![crown24](https://user-images.githubusercontent.com/14167196/33528506-1fd6b276-d86a-11e7-93bd-bf201a6e3c6d.png)
![crown36](https://user-images.githubusercontent.com/14167196/33528508-20c61e24-d86a-11e7-8ac4-cfaf344dac7f.png)
![crown48](https://user-images.githubusercontent.com/14167196/33528509-22435712-d86a-11e7-8616-e20170410a01.png)
[Crown.zip](https://github.com/Templarian/MaterialDesign/files/1525039/Crown.zip)

**Comment by Templarian** [comment]
I'm just going to close this out as I think the current one should be fine for this use.

I'll reopen if there is an objection.
