### ISSUE TITLE
Disabled shuffle

### ISSUE THREAD

**Issue by ploxiz** [Templarian/MaterialDesign#2658]
Should be pretty straightforward.

A crossed
![shuffle](https://www.materialui.co/materialIcons/av/shuffle_grey_192x192.png)

Would've suggested the same thing for the repeat icon, but it has already been done by @Templarian (repeat-off).

**Comment by PeterShaggyNoble** [comment]
`shuffle-disabled` already exists. If you're looking for `shuffle-off`, that wouldn't work as it would be too visually similar to `shuffle`. See a past discussion on this in #862.

[![suffle-disabled](https://user-images.githubusercontent.com/15157491/33544968-a2a1faf2-d8d4-11e7-856d-39b6785c94b9.png)](https://materialdesignicons.com/icon/shuffle-disabled)
