### ISSUE TITLE
New Icon:  Geofence

### ISSUE THREAD

**Issue by dstaflund** [Templarian/MaterialDesign#2659]
Hi there,

I am developing a geofencing application and think Geofence would be a great icon.  There appears to be some consensus on which the icon would look like, i.e.:

![maps-geo-fence-icon](https://user-images.githubusercontent.com/3826103/33575429-d97c60a6-d8f9-11e7-9e81-967b4ba60923.png)

but I haven't been able to find it amongst Google's Material Design icon library or your own.  Even Icon8 doesn't seem to have it -- at least searches on 'geofence' couldn't find it.

Thanks,
Darryl

**Comment by Templarian** [comment]
[![map-marker-radius](https://materialdesignicons.com/icon/map-marker-radius)](https://materialdesignicons.com/icon/map-marker-radius)

Duplicate.

**Comment by PeterShaggyNoble** [comment]
That's `map-marker-radius`.

[![](https://materialdesignicons.com/icon/map-marker-radius)](https://materialdesignicons.com/icon/map-marker-radius)

**Comment by dstaflund** [comment]
Thank you so much. :-)
