### ISSUE TITLE
Dislike Icon

### ISSUE THREAD

**Issue by onooma** [Templarian/MaterialDesign#266]
Hi there

How about dislike icon?
A bar on Heart icon

- [ ] heart-break

**Comment by CoDEmanX** [comment]
Isn't that too much a symbol for broken love?
For dislike, I would use thumbs-down or a strike-through star.
A heart with a diagonal line through might also work, at least there are less fine details than in a broken heart icon.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/heart-broken This already exists. Not sure why it wasn't closed.
