### ISSUE TITLE
Update motorbike icon

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2660]
We should probably update the contributed icon with the one from Google's set: https://material.io/icons/#ic_motorcycle

There is also a variant of this icon for Google Maps in India:
![dqqclb_vaaaoa48](https://user-images.githubusercontent.com/15905797/33657395-17d45746-da71-11e7-8d62-c664625696cb.jpg)

**Comment by PeterShaggyNoble** [comment]
We could rename ours to `motorcyclist` or `motorbiking` or something.

**Comment by k5cents** [comment]
@PeterShaggyNoble Ours just looks weird tbh. I say replace it with Google's altogether. Looks like a guy in some kind of side-car.

**Comment by Templarian** [comment]
[![motorbike](https://materialdesignicons.com/icon/motorbike)](https://materialdesignicons.com/icon/motorbike)
