### ISSUE TITLE
A Few Icons from Analytics

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2661]
Lifted the following icons out of Google Analytics; haven't even attempted to optimise them 'cause I suck at that! 😆 ~Could swear we have `export` already but was too tired to find it!~ (A-ha, it's `save alt`from the [extended set](https://petershaggynoble.github.io/MDI-Sandbox/extended/).)

[![customisation](https://user-images.githubusercontent.com/15157491/33662367-71dbae58-da83-11e7-9b98-f9f29b9ed4e3.png) ![acquisition](https://user-images.githubusercontent.com/15157491/33662387-811222d0-da83-11e7-8b18-009f3350a63d.png) ![export](https://user-images.githubusercontent.com/15157491/33662412-920a826c-da83-11e7-86ec-42750afd574b.png) ![intelligence](https://user-images.githubusercontent.com/15157491/33662453-b58a7a26-da83-11e7-8a67-30373980fbc2.png)](https://github.com/Templarian/MaterialDesign/files/1535174/analytics.zip)

**Comment by nikolaysm** [comment]
?

**Comment by Templarian** [comment]
[![atom-variant](https://materialdesignicons.com/icon/atom-variant)](https://materialdesignicons.com/icon/atom-variant)

**Comment by goyney** [comment]
[![view-grid-plus](https://materialdesignicons.com/icon/view-grid-plus)](https://materialdesignicons.com/icon/view-grid-plus)[![merge](https://materialdesignicons.com/icon/merge)](https://materialdesignicons.com/icon/merge)
