### ISSUE TITLE
Car-multiple and Commute

### ISSUE THREAD

**Issue by Stas-tolpekin** [Templarian/MaterialDesign#2662]
![car 3x](https://user-images.githubusercontent.com/9248954/33769189-0ae044b4-dbde-11e7-97af-78958b628353.png)
something such it

**Comment by PeterShaggyNoble** [comment]
If you're looking for an icon to represent traffic in the meantime, Google use `traffic-light` on Google Maps.

[![traffic-light](https://user-images.githubusercontent.com/15157491/33772970-56535cba-dc2e-11e7-844e-1d789c869a3d.png)](https://materialdesignicons.com/icon/traffic-light)

**Comment by Stas-tolpekin** [comment]
@PeterShaggyNoble thanks, but I look up an icon for vehicles list.

**Comment by MrGrigri** [comment]
I had to make the car more narrow in order for the second to fit properly. Remember, this is just a draft and subject to change.

![image](https://user-images.githubusercontent.com/4528551/33851577-a1b8493e-de74-11e7-8c45-c38c41aff2f2.png)

[car-multiple.zip](https://github.com/Templarian/MaterialDesign/files/1549237/car-multiple.zip)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/33860623-f14206bc-de96-11e7-9143-61dbeefa68ce.png)

**Comment by PeterShaggyNoble** [comment]
See also: Google's `commute` icon. (I *knew* I'd seen a stock icon similar to this somewhere!)

![commute](https://user-images.githubusercontent.com/15157491/34050995-d2ec7abe-e1b4-11e7-9526-b8e819c73503.png)

**Comment by CoDEmanX** [comment]
Commute is a nice one. Should be tagged with train, car, public transport etc. (had a really hard time to find its name)

**Comment by Templarian** [comment]
[![car-multiple](https://materialdesignicons.com/icon/car-multiple)](https://materialdesignicons.com/icon/car-multiple) [![train-car](https://materialdesignicons.com/icon/train-car)](https://materialdesignicons.com/icon/train-car)
