### ISSUE TITLE
Filtering Bug

### ISSUE THREAD

**Issue by saiichihashimoto** [Templarian/MaterialDesign#2663]
Repro Steps:

1. Click the Drop Down for "Tags" in the search bar.
2. Click any tag that contains a ```/``` (```Alert / Error```, for example)
3. Notice the URL flicker.
4. Nothing occurs.

This happens for *all* tags with a ```/```. Attempting to manually enter the URL with a ```Alert%20%2F%20Error``` has no effect.

**Comment by PeterShaggyNoble** [comment]
Thanks, @saiichihashimoto. We're aware of this bug which arose from a change to how icons are categorised for the new site. It's on the to-do list to fix but development focus is firmly on the new site.

**Comment by Templarian** [comment]
I can fix this, I have a new column with a URL safe, just need to switch the two endpoints over to use that column. `Alert / Error` = `alert`.

http://dev.materialdesignicons.com/icons/alert Dev server shows how this works now.

**Comment by Templarian** [comment]
This has been resolved on the current site.
