### ISSUE TITLE
Penguin

### ISSUE THREAD

**Issue by augustin32** [Templarian/MaterialDesign#2664]
Replacement for current penguin/linux icon from the set. 
![penguin24](https://user-images.githubusercontent.com/14167196/33782581-f3548f60-dc61-11e7-90a0-19e9b6d8f9ea.png)
![penguin36](https://user-images.githubusercontent.com/14167196/33782583-f4c4957a-dc61-11e7-9fab-dcae35f7cd46.png)
![penguin48](https://user-images.githubusercontent.com/14167196/33782585-f5e1e854-dc61-11e7-9a7e-353ecc588396.png)
[penguin.zip](https://github.com/Templarian/MaterialDesign/files/1543682/penguin.zip)

**Comment by PeterShaggyNoble** [comment]
See also [#2591 (comment)](https://github.com/Templarian/MaterialDesign/issues/2591#issuecomment-343542984).

**Comment by augustin32** [comment]
@PeterShaggyNoble And what's the problem? Is it that the penguin doesn't look like Tux?

**Comment by PeterShaggyNoble** [comment]
#2940 covers the Linux icon, leaving this open as a suggestion for a new `penguin` icon.

**Comment by Templarian** [comment]
Added. 😃
