### ISSUE TITLE
Table Search

### ISSUE THREAD

**Issue by arvindthyagarajan** [Templarian/MaterialDesign#2665]
Would be good to add a table-search icon to go with the "set" that table-edit is in.
Something to this effect?
![table-search](https://user-images.githubusercontent.com/436579/33785287-2f6ee5ca-dc19-11e7-9be3-25ce69af6cce.png)
@Templarian 
Gracias!!

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/33894952-7e1971da-df1c-11e7-8fde-1f6e77998fd1.png)

[table-search.zip](https://github.com/Templarian/MaterialDesign/files/1552341/table-search.zip)

**Comment by Templarian** [comment]
[![table-search](https://materialdesignicons.com/icon/table-search)](https://materialdesignicons.com/icon/table-search)
