### ISSUE TITLE
Chromecast Connecting Icons

### ISSUE THREAD

**Issue by chances** [Templarian/MaterialDesign#2666]
Icons for use as the connecting state for a Chromecast Cast Button.

![cast-connecting-1](https://user-images.githubusercontent.com/635049/33801837-d98a00f4-dd1c-11e7-91be-7333c4d678fb.png) `cast-connecting-1`
![cast-connecting-2](https://user-images.githubusercontent.com/635049/33801838-d9a03fcc-dd1c-11e7-8410-191eb4070544.png) `cast-connecting-2`
![cast-connecting-3](https://user-images.githubusercontent.com/635049/33801839-d9b60bc2-dd1c-11e7-8e1f-d7dd56d5b5eb.png) `cast-connecting-3`

[cast-connecting.zip](https://github.com/Templarian/MaterialDesign/files/1545303/cast-connecting.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for contributing, @chances. Note, though, that we require icons to be monotone as all SVGs use just a single path.

**Comment by GreenTurtwig** [comment]
Removing the transparent parts could work, however it doesn't look that great.

![](https://user-images.githubusercontent.com/15905797/33895957-927ff7f6-df59-11e7-9587-e218e58db7e5.png)![](https://user-images.githubusercontent.com/15905797/33895977-9f8270f0-df59-11e7-9301-7fb34f5be99a.png)![](https://user-images.githubusercontent.com/15905797/33896006-ae22220e-df59-11e7-860f-c37b14caf391.png)
[cast-connecting.zip](https://github.com/Templarian/MaterialDesign/files/1552449/cast-connecting.zip)

**Comment by goyney** [comment]
This will be doable once we support two-tone icons in the future.

**Comment by goyney** [comment]
We're going to close this for now because two-tone icons are pretty far out on our roadmap.
