### ISSUE TITLE
Upside down light bulb

### ISSUE THREAD

**Issue by chocomega** [Templarian/MaterialDesign#2669]
Hi
Unless I missed it, is it possible to add upside down light bulb icons ?
I would like to differentiate light bulbs on ceiling / on the floor for example.
Thanks

**Comment by MrGrigri** [comment]
Just use CSS to transform the icon 180deg. Would that not work?

**Comment by MrGrigri** [comment]
Also, there is an issue thread #1712 for these icons.

**Comment by chocomega** [comment]
I use the icons with https://home-assistant.io/ so I don't have control over CSS
I may use ceiling-light for now but the existing lightbulb icons rotated by 180 would be great.

**Comment by Templarian** [comment]
While I see the use of the icon I'm not really thinking this is a good idea to add this icon. Really don't want to make rotating icons a normal thing. There was a time where we were only going to include one arrow style degree and require the community to handle it.
