### ISSUE TITLE
comment-next, comment-previous

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#2670]
![image](https://user-images.githubusercontent.com/1015040/33851041-c68656b6-de83-11e7-9385-75312df9d2e8.png)
![image](https://user-images.githubusercontent.com/1015040/33851061-d4fc52c2-de83-11e7-9dfb-593999e4c31b.png)
![image](https://user-images.githubusercontent.com/1015040/33851905-80daa88a-de86-11e7-8c61-756569171159.png)
![image](https://user-images.githubusercontent.com/1015040/33851895-77e43a8e-de86-11e7-880a-5841d7a79c09.png)
[comment-next-previous.zip](https://github.com/Templarian/MaterialDesign/files/1789877/comment-next-previous.zip)
Create with the intended use of a Track Changes interface, similar to Microsoft Word.

**Comment by goyney** [comment]
Outlined versions:

![image](https://user-images.githubusercontent.com/1015040/33851895-77e43a8e-de86-11e7-880a-5841d7a79c09.png)
![image](https://user-images.githubusercontent.com/1015040/33851905-80daa88a-de86-11e7-8c61-756569171159.png)
[comment-next-previous-outline.zip](https://github.com/Templarian/MaterialDesign/files/1549252/comment-next-previous-outline.zip)

**Comment by goyney** [comment]
I would like to bump the priority on this request please. :)

**Comment by Templarian** [comment]
[![comment-arrow-right](https://materialdesignicons.com/icon/comment-arrow-right)](https://materialdesignicons.com/icon/comment-arrow-right) [![comment-arrow-right-outline](https://materialdesignicons.com/icon/comment-arrow-right-outline)](https://materialdesignicons.com/icon/comment-arrow-right-outline) [![comment-arrow-left](https://materialdesignicons.com/icon/comment-arrow-left)](https://materialdesignicons.com/icon/comment-arrow-left) [![comment-arrow-left-outline](https://materialdesignicons.com/icon/comment-arrow-left-outline)](https://materialdesignicons.com/icon/comment-arrow-left-outline)
