### ISSUE TITLE
Investor (account-dollar)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2671]
Found on [Crunchbase](https://www.crunchbase.com/):

![image](https://user-images.githubusercontent.com/1309249/33860143-91b144ce-ded7-11e7-924f-fcc4b412fcd8.png)

[investor.zip](https://github.com/Templarian/MaterialDesign/files/1549769/investor.zip)

**Comment by goyney** [comment]
The use of the USD sign makes me not want to add that icon. Can you think of another way to indicate an investor?

**Comment by CoDEmanX** [comment]
We have account-star, which might be okay, otherwise maybe add an account-crown icon (could be used for patrons as well I guess)?

**Comment by goyney** [comment]
Closing because the `Consider Closing` label was added quite a while ago. We don't like adding icons with the `$` for localization reasons. If you can think of another way to indicate an investor, please feel free to comment and we'll reconsider this issue. Thanks.
