### ISSUE TITLE
Request tracking

### ISSUE THREAD

**Issue by kannalu16** [Templarian/MaterialDesign#2672]
Hi 

I would like to suggest an idea for "Request tracker" or "Request STatus", "Requests history"...

**Comment by PeterShaggyNoble** [comment]
Can you provide some context/a use case and examples? There are a few existing icons that *could* fulfil your requests.

**Comment by kannalu16** [comment]
I am more than happy to see existing ones. But what I am looking into is my app makes lot of service calls so I want to create a collection of calls and see how much each cal is taking. Something like a fiddler

**Comment by goyney** [comment]
I'd take a look at the following:

- Request Tracker - https://materialdesignicons.com/icon/format-list-checks
- Request Status - https://materialdesignicons.com/icon/progress-check
- Request History - https://materialdesignicons.com/icon/history

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. If none of the icons @goyney suggested suit your needs, please provide some examples of what you are looking for and reopen this issue.
