### ISSUE TITLE
Folder Setting (Cog/Gear)

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2673]
Need a folder with a gear/icon

![folder24](https://user-images.githubusercontent.com/20706106/33898098-63c05df8-df35-11e7-9258-c2cbe312535b.png)
![folder48](https://user-images.githubusercontent.com/20706106/33898099-65aacd10-df35-11e7-8669-63e56017104c.png)
![folder96](https://user-images.githubusercontent.com/20706106/33898101-6710cc72-df35-11e7-95f0-18f2ba0d9db4.png)

[folder-settings.zip](https://github.com/Templarian/MaterialDesign/files/1552590/folder-settings.zip)

**Comment by GreenTurtwig** [comment]
https://github.com/Templarian/MaterialDesign/issues/270

**Comment by MrGrigri** [comment]
Closing this in favor of #270
