### ISSUE TITLE
Google Train

### ISSUE THREAD

**Issue by MissingL-tter** [Templarian/MaterialDesign#2676]
Didn't really know what to title this but I figure the naming should be congruent with google's naming when referencing the icons they created. For example...

The subway icons are correctly labeled:
- [google subway](https://material.io/icons/#ic_subway) is labeled as [subway ](https://materialdesignicons.com/icon/subway) on MDI
- [google directions_subway](https://material.io/icons/#ic_directions_subway) is labeled as [subway_variant](https://materialdesignicons.com/icon/subway-variant) on MDI

But the train icons aren't because google's actual train icon is missing from the site:

- [google train](https://material.io/icons/#ic_train) is not available on MDI
- [google directions_railway](https://material.io/icons/#ic_directions_railway) is labeled as [train](https://materialdesignicons.com/icon/train) on MDI

**Comment by PeterShaggyNoble** [comment]
This project predates the official release by a number of months, as such there were no names to go by. Google's icon naming is also rarely intuitive, frequently inconsistent and often confusing, whereas MDI names follow a naming convention. Where possible/necessary, though, the names of all the stock icons have been added as aliases. If you spot any that are missing, please let us know.

**Comment by Templarian** [comment]
So we need to add Google's Train icon as `train-variant` ?

**Comment by MissingL-tter** [comment]
To most accurately represent the source I think that Google's Train should be added as `train` and the current `train` changed to `train-variant`.

But yeah, adding google's train as `train-variant` would suffice.

For future reference: Is there a better place to request the addition of a google icon that is missing?

**Comment by Templarian** [comment]
That would probably be a good solution. Might just do that.

This is the correct place. Create an issue for each missing icon separately. We don't add all of them, but do our best to add the ones the community needs.

**Comment by PeterShaggyNoble** [comment]
I prefer the look of their `train` over their `directions railway` (our `train`) so I'd vote the same way as @MissingL-tter.

Stock icons do get added regularly (along with icons from Google's extended set) but there are also a lot of other requests to deal with, which is why they're not all included yet. If there are any in particular you need, create a new issue for each.

**Comment by JamesCoyle** [comment]
Need to get this added/changed.

**Comment by Templarian** [comment]
[![train](https://materialdesignicons.com/icon/train)](https://materialdesignicons.com/icon/train) [![train-variant](https://materialdesignicons.com/icon/train-variant)](https://materialdesignicons.com/icon/train-variant)

Finally got around to wrapping this updated/added.
