### ISSUE TITLE
Using ligatures by icon name via *.ttf

### ISSUE THREAD

**Issue by sthlm58** [Templarian/MaterialDesign#2677]
I wanted to use materialdesignicons-webfont.ttf as my ligatures font, i.e. use them the same way as I use Google's MaterialIcons-Regular.ttf.

That means, after typing icon's name (e.g. `add`) I want an actual `+` icon to be visible. Instead I only see my typed-in text.

Is that something easily doable?

**Comment by Templarian** [comment]
#1013 We're playing with the idea, but it may be a while. Updating our build tools is causing a few icons to render wrong.

It's a rather low priority at the moment.
