### ISSUE TITLE
Wrong location icon

### ISSUE THREAD

**Issue by kostaskoufogiannis** [Templarian/MaterialDesign#2678]
Something like this

https://cdn3.iconfinder.com/data/icons/map/500/wrong-512.png

**Comment by GreenTurtwig** [comment]
[![imag](https://user-images.githubusercontent.com/15905797/33989618-02dcb388-e0c0-11e7-8005-3d9466e27f0b.png)](https://github.com/Templarian/MaterialDesign/files/1558955/map-marker-remove.zip)[![](https://user-images.githubusercontent.com/15905797/33989638-1311f678-e0c0-11e7-9770-3e28270d25cc.png)](https://github.com/Templarian/MaterialDesign/files/1558958/map-marker-remove2.zip)

**Comment by PeterShaggyNoble** [comment]
The first one is more consistent with Google's labelled markers.

**Comment by MrGrigri** [comment]
I don't know our current ones are to the side, like the second one.

![map-marker-minus](https://materialdesignicons.com/icon/map-marker-minus) ![map=marker-plus](https://materialdesignicons.com/icon/map-marker-plus)

**Comment by PeterShaggyNoble** [comment]
Yeah, we should probably update those at some stage to match Google's (see [`add location`](https://material.io/icons/#ic_add_location) and [`edit location`](https://material.io/icons/#ic_edit_location), for example).

The extended set includes an icon called `not listed location`, which might be suitable here, too.

![not listed location](https://user-images.githubusercontent.com/15157491/34004553-1bd82af4-e0f0-11e7-8f08-5fd645f237ea.png)

**Comment by MrGrigri** [comment]
@PeterShaggyNoble good point.

**Comment by JamesCoyle** [comment]
I much prefer the modifier within the icon than to the side. If they were used on a map the small external icon could be easily lost in the maps details.

**Comment by MrGrigri** [comment]
I agree I was just merely making a consistency point.

**Comment by Templarian** [comment]
Added. 😃
