### ISSUE TITLE
help-network should be renamed to question-network

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2679]
`help-network` doesn't use `question` as other icons do. (`calendar-question` and `comment-question`).

**Comment by Templarian** [comment]
Yea, looks like it's `help` when it's a base icon and `question` when it is a modifier.

**Comment by PeterShaggyNoble** [comment]
Added the `Alias` label too to remind us to alias with `help-network` after renaming.

**Comment by Templarian** [comment]
Not renaming for the reason I gave earlier. I've updated the docs to explain this.
