### ISSUE TITLE
calendar multiple

### ISSUE THREAD

**Issue by RYO-Software** [Templarian/MaterialDesign#268]
Hello,
Please, add a icon like "calendar-check" but multiple.
Thanks

- [ ] calendar-multiple-check

**Comment by Templarian** [comment]
Multiple calendars or multiple checks?

**Comment by RYO-Software** [comment]
Múltiple calendars are preferred :)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/calendar-multiple
http://materialdesignicons.com/icon/calendar-multiple-check
