### ISSUE TITLE
Shutdown icon

### ISSUE THREAD

**Issue by phoomin2012** [Templarian/MaterialDesign#2680]
Like this
![screen shot 2560-12-14 at 22 53 04](https://user-images.githubusercontent.com/2673599/34001076-9d5037a8-e121-11e7-98b0-b94af98902a2.png)

**Comment by PeterShaggyNoble** [comment]
It already exists as `power`.

[![power](https://user-images.githubusercontent.com/15157491/34001755-bd33546c-e0e8-11e7-9908-7293fcc9698b.png)](https://materialdesignicons.com/icon/power)

**Comment by MrGrigri** [comment]
View #2304 for more details on this.

**Comment by PeterShaggyNoble** [comment]
Alias added.
