### ISSUE TITLE
Update Currency-Eth and Add Ethereum

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2681]
Similar to the update for Bitcoin in v2.1.19, `currency-eth` needs to be replaced with a capital xi (`Ξ`), with the current icon being repurposed as a brand icon.

**Comment by PeterShaggyNoble** [comment]
Finally; an icon so simple even I can manage it! 😆

We should alias this as `xi` as well.

[![currency-eth](https://user-images.githubusercontent.com/15157491/34042050-c57e6e40-e192-11e7-8d2b-a5226a1406be.png)](https://github.com/Templarian/MaterialDesign/files/1562631/currency-eth.zip)

**Comment by JapanYoshi** [comment]
At this aspect ratio, also looks like the Chinese ideogram for 3 (三). XD

**Comment by PeterShaggyNoble** [comment]
@Templarian, should this be reassigned to me now?

**Comment by Templarian** [comment]
Fixed.
