### ISSUE TITLE
1password

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2682]
I believe we should add 1Password as a branded icon.

![image](https://user-images.githubusercontent.com/4528551/34004449-267beb70-e0b5-11e7-8f9e-c7f3ddb9040d.png)

[1password.zip](https://github.com/Templarian/MaterialDesign/files/1560116/1password.zip)

**Comment by jecsham** [comment]
Old style icon

**Comment by GreenTurtwig** [comment]
@jecsham What do you mean? Other than the circle cut outs not being triangles, this is their current logo.

**Comment by MrGrigri** [comment]
I took the icon they use for their chrome extension.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/34113163-0b63ef1c-e3cc-11e7-8494-21d1f1334694.png)

**Comment by BeatriceFendt** [comment]
An icon for the [open-source](https://github.com/bitwarden) [Bitwarden](https://bitwarden.com/) would be amazing too 👌🏻

**Comment by MrGrigri** [comment]
@BeatriceFendt, would [shield-half-full](https://materialdesignicons.com/icon/shield-half-full) work? Also, if you want an icon request, just submit an issue after fully searching the existing/closed issues. That way it can be tracked more efficiently. Thanks.

![shield-half-full](https://materialdesignicons.com/icon/shield-half-full)

**Comment by BeatriceFendt** [comment]
Thanks @MrGrigri. I will use that for now. Additionally, I openend https://github.com/Templarian/MaterialDesign/issues/2722. 👍

**Comment by Templarian** [comment]
Small issue, we can't name icons starting with a number. I wonder if naming it `onepassword` would be fine. Aliases can have numbers.

**Comment by Templarian** [comment]
[![onepassword](https://materialdesignicons.com/icon/onepassword)](https://materialdesignicons.com/icon/onepassword)

Alias `1password` was also added.
