### ISSUE TITLE
speedometer-slow 

### ISSUE THREAD

**Issue by b-jazz** [Templarian/MaterialDesign#2683]
I want to allow the user to pick "slow", "medium", or "fast" option on my website, but could only find the speedometer to relate the speed of something. The current speedometer could be considered speedometer-fast. A mirror of that could be a speedometer-slow and a new icon with the needle pointing straight up could be a speedometer-medium.

**Comment by jecsham** [comment]
That would be great!

**Comment by PeterShaggyNoble** [comment]
As an alternative, you could use `walk`, `run` and `run-fast`.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/34074058-585207a6-e29f-11e7-841d-70a6532153f2.png)](https://github.com/Templarian/MaterialDesign/files/1565078/speedometer-slow.zip)[![](https://user-images.githubusercontent.com/15905797/34074071-77735ec8-e29f-11e7-88b5-de6152527cda.png)](https://github.com/Templarian/MaterialDesign/files/1565077/speedometer-medium.zip)

**Comment by b-jazz** [comment]
Fits perfectly with the existing speedometer icon. I'm not sure how much you care about the rounded stroke issue though: https://github.com/Templarian/MaterialDesign/issues/1128

**Comment by JamesCoyle** [comment]
I feel we should fix the terminals and get these added.

**Comment by JamesCoyle** [comment]
@GreenTurtwig Can we get these with the square terminals (including the existing icon)?

**Comment by Templarian** [comment]
Added.
