### ISSUE TITLE
Blu-ray

### ISSUE THREAD

**Issue by timoabend** [Templarian/MaterialDesign#2684]

**Comment by GreenTurtwig** [comment]
As in the Blu-Ray logo?  
We would have to add the logos for CD, DVD, e.t.c. all of which won't look that great at 1x.

**Comment by PeterShaggyNoble** [comment]
Although, if you just need something to represent a Blu-Ray disc then `disk` should suffice.

[![disk](https://materialdesignicons.com/icon/disk)](https://materialdesignicons.com/icon/disk)

**Comment by timoabend** [comment]
Yes, I chose mdi:disk. But I thought it would be a nice suggestion since there is lots of brands in Material Design Icons.
