### ISSUE TITLE
Vivaldi

### ISSUE THREAD

**Issue by ClickHereForCake** [Templarian/MaterialDesign#2685]
You should add a vivaldi icon

**Comment by PeterShaggyNoble** [comment]
[![violin](https://materialdesignicons.com/icon/violin)](https://materialdesignicons.com/icon/violin)

**Comment by GreenTurtwig** [comment]
@PeterShaggyNoble They meant the web browser Vivaldi. :-P
https://vivaldi.com

**Comment by PeterShaggyNoble** [comment]
Oh. Never heard of it!

Given that it doesn't register on StatCounter, it's probably too obscure for inclusion at this time.
