### ISSUE TITLE
Smart Lock

### ISSUE THREAD

**Issue by pauldgifford** [Templarian/MaterialDesign#2686]
http://august.com/wp-content/uploads/2015/08/house_asl_icon.png

**Comment by pauldgifford** [comment]
http://august.com/

**Comment by Templarian** [comment]
The same way we are going to renaming `roomba` (see: #2327), I think we should keep the "smart lock" as generic as possible (with variant designs).

Most of the large lock companies have smart locks now and there are many startups. Should be able to have a basic design that is easily identifiable as a `smart-lock` or dialpad / key fob.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/34829489-c57e211e-f6d8-11e7-850d-2ee1c2d1e124.png)](https://github.com/Templarian/MaterialDesign/files/1622886/lock-smart.zip)

The most common style is a keypad with a traditional lock below.

**Comment by Templarian** [comment]
[![lock-smart](https://materialdesignicons.com/icon/lock-smart)](https://materialdesignicons.com/icon/lock-smart)
