### ISSUE TITLE
Sonarr & Radarr

### ISSUE THREAD

**Issue by kylearoberts** [Templarian/MaterialDesign#2689]
Could use the icons for [Sonarr](https://sonarr.tv) & [Radarr](https://radarr.video/).

**Comment by MrGrigri** [comment]
As per our [contributing guidelines](https://github.com/Templarian/MaterialDesign/blob/master/CONTRIBUTING.md), this will not be accepted.

> Please know that social media icons or largely used products are the only brand icons we allow.
