### ISSUE TITLE
Box Icon

### ISSUE THREAD

**Issue by OSXyZ** [Templarian/MaterialDesign#269]
Hello all and thanks for doing such a great job with these icons. 
First of all, I'd love to support the development of new ones as there's a need. 

If someone could please share a Paypal link or something, I'd happily contribute for anyone's time to help with some icon designs. 

I could use a box icon to indicate "inventory" for a project I'm working on. 
A solid and line version would be really appreciated. 

(Note: Not to be confused with box.com's logo, this should be something a bit more distinguished that their logo.)

Feel free to refer to the uploaded images for an idea and get in touch at osandi@me.com when it's been added to the repo. 

Osandi

![box_open](https://cloud.githubusercontent.com/assets/392313/7051993/b2e83364-dde0-11e4-8af5-123d8d8fd3d0.png)

**Comment by Templarian** [comment]
I assume something like the [cube](http://materialdesignicons.com/icon/cube) icon with flaps.

**Comment by OSXyZ** [comment]
Yeah, I think that could work. 

Osandi

**Comment by Templarian** [comment]
Would the `package` icon that is in the pack close this issue, but are you looking specifically for more of the cube shape?

http://materialdesignicons.com/icon/package (there is a download/upload one also).

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/package-variant
