### ISSUE TITLE
file-download

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#2692]
![image](https://user-images.githubusercontent.com/1015040/34363652-0e754184-ea4c-11e7-88b0-066fda002d15.png)
![image](https://user-images.githubusercontent.com/1015040/34363640-fe30d180-ea4b-11e7-9cbd-c3309308315a.png)

[file-download.zip](https://github.com/Templarian/MaterialDesign/files/1579635/file-download.zip)

**Comment by Templarian** [comment]
[![file-download](https://materialdesignicons.com/icon/file-download)](https://materialdesignicons.com/icon/file-download) [![file-download-outline](https://materialdesignicons.com/icon/file-download-outline)](https://materialdesignicons.com/icon/file-download-outline)
