### ISSUE TITLE
Icon request: an empty without anything, just like whitespace

### ISSUE THREAD

**Issue by 3axap4eHko** [Templarian/MaterialDesign#2694]

**Comment by PeterShaggyNoble** [comment]
You could use any icon for this and set its colour to match your background or set its opacity. If you're using the webfont, there's even a special class that uses the `solid` icon to do exactly what you want; you can find it at the end of `preview.html`.

**Comment by 3axap4eHko** [comment]
@PeterShaggyNoble what if I don't know my background color and in my react-native application I don't have classes. What I 100% sure that if I display empty symbol, it will work.

**Comment by PeterShaggyNoble** [comment]
Are you using the webfont or SVGs?

**Comment by Templarian** [comment]
The `mdi-blank` does this and was introduced a few versions ago.

https://cdn.materialdesignicons.com/2.1.19/ Search for `mdi-blank`

But you can really use any icon as they all have monospace size. I just used the solid since it made the most sense.
