### ISSUE TITLE
Unicode Logo

### ISSUE THREAD

**Issue by DragonVirus** [Templarian/MaterialDesign#2695]
![unicode_logo_bnw](https://user-images.githubusercontent.com/1311765/34294928-2264bce4-e739-11e7-82cf-7ad0823ec529.png)

[Unicode_logo_bnw.svg.zip](https://github.com/Templarian/MaterialDesign/files/1582213/Unicode_logo_bnw.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Could you provide a use case for this?

**Comment by DragonVirus** [comment]
@PeterShaggyNoble In my use case, I want to use this to show an app is unicode supported or not. I was thinking to add as custom icon but then i think other might need it too.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49038318-9dcc6880-f18a-11e8-8e39-f146992833f9.png)
[unicode.svg.zip](https://github.com/Templarian/MaterialDesign/files/2617109/unicode.svg.zip)

**Comment by Templarian** [comment]
Added. :smile:
