### ISSUE TITLE
Computer measuring

### ISSUE THREAD

**Issue by Ofaim** [Templarian/MaterialDesign#2696]
Hey guys!
I would very much like to use an icon that represent "Your website status" (it's a tab on my app, mainly detailing speed and availability).
The so-called "website" can be only one page, so I don't think that server-based icons are the best fit.

I thought of something like a computer screen (or something else representing "a site") with a speedometer pointer on one of the corners, maybe?

Thanks a lot, your icons are the best!!

**Comment by PeterShaggyNoble** [comment]
Would the `speedometer` or `gauge` icons not be understood on their own within the context of your app? There's also the stock [`web` icon](https://material.io/icons/#ic_web) which might be of use.

**Comment by Ofaim** [comment]
Hey, thank you for the answer :)
No, I spent a lot of time searching before opening an issue here...
All of those doesn't "measure the computer vitals".
The `speedometer` and `gauge` measuring nothing if you don't have the right context in your app, and the `web icon` relates to design more than anything else (because of all the squares).

For example, this icon is clearly measuring something that is Wi-Fi related:
![image](https://user-images.githubusercontent.com/34773792/34510502-05f95060-f05d-11e7-8655-fe0eab190428.png)


For my app (and I believe that others can use it as well!) I need to measure something that is website related (preferably, but not server related!) or computer related.

I'll appreciate any other suggestion (or of course an icon haha).
Thanks!!

**Comment by goyney** [comment]
Measure what exactly? "Measure something that is website related" doesn't really mean anything? Measure network speed? Measure HDD read speed? Measure WiFi speed (as in your example)?

My issue is, no matter your answer, all of these things seem overly specific. @PeterShaggyNoble's suggestion of using `gauge-*` or `speedometer` seem like the best options for your use case.

I'm going to suggest we close this issue, unless you can come back with a more concrete example of what you're looking for.

**Comment by PeterShaggyNoble** [comment]
Agreed with @goyney, closing this out.

@Ofaim, if you can provide a more concrete example of the icon you're looking for or even the concept you're trying to represent then please leave a comment and we'll revisit this issue.
