### ISSUE TITLE
Table View

### ISSUE THREAD

**Issue by buchmiller** [Templarian/MaterialDesign#2697]
Similar to table-edit and this one, but with an eye in the corner: https://github.com/Templarian/MaterialDesign/issues/2665

**Comment by terreng** [comment]
I tried my best to make this work

![image](https://user-images.githubusercontent.com/11605395/53611283-d2cdca00-3b82-11e9-86ba-0a260b8a373b.png)
[table-view.svg](https://github.com/terreng/samples/blob/master/table-view.svg)

**Comment by goyney** [comment]
[![table-eye](https://materialdesignicons.com/icon/table-eye)](https://materialdesignicons.com/icon/table-eye)
