### ISSUE TITLE
file and folder settings icons

### ISSUE THREAD

**Issue by BjErkan** [Templarian/MaterialDesign#270]
- [x] account-admin
- [x] rename
- [ ] attributes

**Comment by Templarian** [comment]
Do you have an example for any of these? Mostly not sure about the `attributes` icon (I have a slight idea, but maybe a use case where you are using this would help).

Would the [rename-box](http://materialdesignicons.com/icon/rename-box) work for rename?

**Comment by BjErkan** [comment]
Austin,
We are considering using icons from your website. You have gotten back to us faster than anyone we have done business with yet. We would be happy to pay for some custom icon work. Are you interested?
On Apr 8, 2015 12:41 PM, Austin Andrews <notifications@github.com> wrote:Do you have an example for any of these? Mostly not sure about the attributes icon (I have a slight idea, but maybe a use case where you are using this would help).

Would the rename-box work for rename?

**Comment by BjErkan** [comment]
Hello, Austin.  My name is Boyd Edmondson, and I am BJ’s business partner.  BJ just had to leave, so I’m going to attempt to respond on his behalf.

Yes, I think we could use the rename-box icon for “rename”.

The “attributes” icon is for representing file attributes, such as date/time stamp, access permissions, thumbnail image, etc.  We currently are using this:

[cid:image001.png@01D07207.8B88CBC0]

That appears above the column where attributes are displayed.  We then have sub image icons for choosing how much detail to display for the attributes, using “low”, “medium”, “high”, with these icons:  [cid:image002.png@01D07208.43D82D10] , [cid:image003.png@01D07208.43D82D10] , [cid:image004.png@01D07208.43D82D10] .


Better still, below is an image of the images we are currently using, and their names hint at what they are used for.  We hope to replace these place holder images with images from MaterialDesignIcons.com.  If there are no MaterialDesignIcons.com icons that map directly to ours, or some acceptable similar one, then we desire to have some created that fulfil that role/function and match the style of the other MaterialDesignIcons.com.

[cid:image005.png@01D07208.5D517A30]

Boyd

**Comment by Templarian** [comment]
Your attached images from emails do not get transferred into GitHub. You can paste images or drag and drop them.

**Comment by CoDEmanX** [comment]
Google's supervisor icon might work for account-admin, otherwise there's the crown icon.

Renaming is usually depicted by a [pencil](https://materialdesignicons.com/icon/pencil).

For file attributes, maybe file + cog or file + ...?

**Comment by CoDEmanX** [comment]
Another way to depict *rename*:
![Editing-Rename-Icon](http://icons.iconarchive.com/icons/icons8/ios7/48/Editing-Rename-icon.png)

**Comment by CoDEmanX** [comment]
Text edit cursor icon:
![text-cursor](https://cloud.githubusercontent.com/assets/1309249/8955352/27db7678-35ec-11e5-9232-ebaa27f18b67.png) https://www.dropbox.com/s/fcwlq7ik1ac0uma/text-cursor.svg?dl=0

**Comment by BjErkan** [comment]
Hello Austin,I would like to talk to you about a project. I need some 60-100 icons for a java application that is material design inspired. 
I an willing to pay well for it. 
per icon or for the whole project. 
Time is of the essence. 
Feel free to call me on my cell.425-329-5913Cheers,
B.J. ErkanUnilogical.com



     On Thursday, April 9, 2015 10:40 PM, Austin Andrews <notifications@github.com> wrote:
   

 Your attached images from emails do not get transferred into GitHub. You can paste images or drag and drop them.—

**Comment by CoDEmanX** [comment]
Is that 100 completely new icons, or will you use existing ones as well?

**Comment by BjErkan** [comment]
Thanks for getting back to me so fast, Austin.
I'm not sure. We may be able to use existing if they fit our style enough.
If you accept the job we can install the beta app so you can see it.
Or I can take screen shots and write explanations of each function.

On Oct 2, 2015 12:27 PM, CoDEmanX <notifications@github.com> wrote:Is that 100 completely new icons, or will you use existing ones as well?

**Comment by Templarian** [comment]
@BjErkan That wasn't me that was Cody, but if you wanted to work with @CoDEmanX on this that's fine. I'm not freelancing icons at the moment and he's easily the most active contributors on this project. Definitely qualified also, but up to him if he wants to freelance a project like this.

**Comment by BjErkan** [comment]
Ok Cody, are you interested?
On Oct 2, 2015 5:02 PM, Austin Andrews <notifications@github.com> wrote:@BjErkan That wasn't me that was Cody, but if you wanted to work with @CoDEmanX on this that's fine. I'm not freelancing icons at the moment and he's easily the most active contributors on this project. Definitely qualified also, but up to him if he wants to freelance a project like this.

**Comment by CoDEmanX** [comment]
I'm interested and essentially available in 2 days. I admit that I'm not a professional (icon) designer, but if you like [my contributions](https://materialdesignicons.com/contributor/Cody) and don't require 100 icons derived from organic-shaped objects (these are really tricky to get right), send me some details to codemanx at gmx de.

**Comment by CoDEmanX** [comment]
Maybe these would work as depictions of file attributes / folder settings in general?

![file-settings](https://cloud.githubusercontent.com/assets/1309249/14770946/010fc8c6-0a7d-11e6-9aac-ebe67cd9a8e6.png) ![folder-settings](https://cloud.githubusercontent.com/assets/1309249/14770947/011037f2-0a7d-11e6-8bbd-c51c2c8c82b4.png)

**Comment by CoDEmanX** [comment]
More file / folder settings icon variants:

![file-settings2](https://cloud.githubusercontent.com/assets/1309249/15624405/7e190520-2487-11e6-9a47-57be9f260c9c.png) ![file-settings4](https://cloud.githubusercontent.com/assets/1309249/15624407/7e1be4d4-2487-11e6-930f-05b33c6f7da6.png) ![file-settings3](https://cloud.githubusercontent.com/assets/1309249/15624406/7e1aeb92-2487-11e6-868d-54736d535567.png) ![folder-settings2](https://cloud.githubusercontent.com/assets/1309249/15624408/7e1cbf30-2487-11e6-8b36-e72a068abb32.png)

**Comment by goyney** [comment]
This issue seems to be stale. Let's renew it so we can get the request addressed and this issue closed.

The three original icons requested were:
- `account-admin`
  - @BjErkan - Can you eloborate on what you envisioned for this icon or if you still need it? We have plenty of `account-*` icons that may already fulfill this use case. (e.g. `security-account`)
- `rename`
  - @BjErkan - `textbox` is usually used for this case (my company uses it for rename in several places). Is this sufficient for you? (We should also alias `textbox` to `rename`.)
- `file-attributes`
  - @CoDEmanX - Can you create actual contributions for the file/folder icons you suggested? I would lean more towards the cog so that icons are at the same x,y coordinates of all other file/folder icons.

**Comment by CoDEmanX** [comment]
Are there any examples of the dots inside the main shape? Maybe that's in option in exceptional cases?

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX, the only `*-settings` icon which deviates from having `settings-helper` below the base icon is `phone-settings`.

**Comment by PeterShaggyNoble** [comment]
Looking through the rest of them, we have, in the past, adjusted the vertical position of the base icon (e.g., `bluetooth-settings` & `cellphone-settings`) so there is precedent if we want to do the same for `file-settings`.

**Comment by goyney** [comment]
@CoDEmanX Can you attach your file/folder settings SVGs so we can get this slated for a milestone? Thanks!

**Comment by CoDEmanX** [comment]
The sanest option is to move the file base icon up if I look the alternatives:

![grafik](https://user-images.githubusercontent.com/1309249/61860344-19251c00-aeca-11e9-8d67-10f448ddabe5.png) ![grafik](https://user-images.githubusercontent.com/1309249/61860412-32c66380-aeca-11e9-9b5b-4e1d7e9f2346.png) ![grafik](https://user-images.githubusercontent.com/1309249/61860511-5ee1e480-aeca-11e9-8a87-d85394820d3d.png) ![grafik](https://user-images.githubusercontent.com/1309249/61860546-702af100-aeca-11e9-83cb-7f4c19d8a426.png) ![grafik](https://user-images.githubusercontent.com/1309249/61860678-a10b2600-aeca-11e9-8a4a-3f6a8f5d7d07.png)

![grafik](https://user-images.githubusercontent.com/1309249/61860769-c4ce6c00-aeca-11e9-8bcc-3af27b865fe0.png) ![grafik](https://user-images.githubusercontent.com/1309249/61860792-d0219780-aeca-11e9-919e-4c8a17bd44f2.png) ![grafik](https://user-images.githubusercontent.com/1309249/61860805-dadc2c80-aeca-11e9-8d8b-a562b2d4d097.png)


![grafik](https://user-images.githubusercontent.com/1309249/61860709-acf6e800-aeca-11e9-80eb-cbb00e8746bc.png) ![grafik](https://user-images.githubusercontent.com/1309249/61860738-b8e2aa00-aeca-11e9-8924-b3fd27faaf1f.png)

With cog:

![grafik](https://user-images.githubusercontent.com/1309249/61861465-44106f80-aecc-11e9-858d-b9d6964d674c.png) ![grafik](https://user-images.githubusercontent.com/1309249/61861534-6efac380-aecc-11e9-9362-8348f7835b77.png) ![grafik](https://user-images.githubusercontent.com/1309249/61861520-64402e80-aecc-11e9-806c-92b2d2d11a08.png)

![grafik](https://user-images.githubusercontent.com/1309249/61861597-93ef3680-aecc-11e9-9f9f-a60fe69ff58a.png) ![grafik](https://user-images.githubusercontent.com/1309249/61861558-7cb04900-aecc-11e9-8354-7431fadb3f61.png) ![grafik](https://user-images.githubusercontent.com/1309249/61861582-8934a180-aecc-11e9-9938-c1625b6c4f8d.png)

[file-folder-settings.zip](https://github.com/Templarian/MaterialDesign/files/3430709/file-folder-settings.zip)

**Comment by annymosse** [comment]
@CoDEmanX  really they're beautiful icons fit the material design(1/2),thanks so much

**Comment by goyney** [comment]
Yeah, the file needs to get moved up if we want to use the three dot modifier.

**Comment by goyney** [comment]
The names of these will hinge on https://github.com/Templarian/MaterialDesign/issues/4271.

**Comment by JamesCoyle** [comment]
I'm renaming this to track just these settings icons. Should we create a new issue for `file-information`?

**Comment by goyney** [comment]
[![file-settings](https://materialdesignicons.com/icon/file-settings)](https://materialdesignicons.com/icon/file-settings)
[![file-settings-outline](https://materialdesignicons.com/icon/file-settings-outline)](https://materialdesignicons.com/icon/file-settings-outline)
[![file-settings-variant](https://materialdesignicons.com/icon/file-settings-variant)](https://materialdesignicons.com/icon/file-settings-variant)
[![file-settings-variant-outline](https://materialdesignicons.com/icon/file-settings-variant-outline)](https://materialdesignicons.com/icon/file-settings-variant-outline)

[![folder-settings](https://materialdesignicons.com/icon/folder-settings)](https://materialdesignicons.com/icon/folder-settings)
[![folder-settings-outline](https://materialdesignicons.com/icon/folder-settings-outline)](https://materialdesignicons.com/icon/folder-settings-outline)
[![folder-settings-variant](https://materialdesignicons.com/icon/folder-settings-variant)](https://materialdesignicons.com/icon/folder-settings-variant)
[![folder-settings-variant-outline](https://materialdesignicons.com/icon/folder-settings-variant-outline)](https://materialdesignicons.com/icon/folder-settings-variant-outline)
