### ISSUE TITLE
Icon Request: Font size increase/decrease

### ISSUE THREAD

**Issue by 2hamed** [Templarian/MaterialDesign#2700]
Please consider adding icons for font size increase and decrease.  
Example: 
![increase-font-size-icon-27787](https://user-images.githubusercontent.com/537522/34322316-14a5c1a6-e839-11e7-8bdd-ecc63e88cdd5.png)

**Comment by MrGrigri** [comment]
Would [format-annotation-plus](https://materialdesignicons.com/icon/format-annotation-plus) work for increase? I would be really simple to swap a minus symbol.

![format-annotation-plus](https://materialdesignicons.com/icon/format-annotation-plus)

**Comment by MrGrigri** [comment]
Here is what it would look like.

![image](https://user-images.githubusercontent.com/4528551/34488432-c37ba75a-ef95-11e7-953b-01ead918efb4.png)

[format-annotation-minus.zip](https://github.com/Templarian/MaterialDesign/files/1597886/format-annotation-minus.zip)

**Comment by PeterShaggyNoble** [comment]
See also: `format-size`

[![format-size](https://user-images.githubusercontent.com/15157491/34490137-c8a766ba-efd6-11e7-8850-39d7ff4a3cb5.png)](https://materialdesignicons.com/icon/format-size)

**Comment by goyney** [comment]
These have been added:

- [`format-font-size-increase`](https://materialdesignicons.com/icon/format-font-size-increase)
- [`format-font-size-decrease`](https://materialdesignicons.com/icon/format-font-size-decrease)
