### ISSUE TITLE
Police Spain

### ISSUE THREAD

**Issue by jneivil** [Templarian/MaterialDesign#2702]
https://upload.wikimedia.org/wikipedia/commons/thumb/4/42/Emblem_of_the_Spanish_Civil_Guard.svg/1200px-Emblem_of_the_Spanish_Civil_Guard.svg.png

**Comment by k5cents** [comment]
This is way too nice and way too intricate.

**Comment by PeterShaggyNoble** [comment]
See #1343 for a generic police icon.
