### ISSUE TITLE
table-merge-cells

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#2703]
![image](https://user-images.githubusercontent.com/1015040/34363609-a6a7728e-ea4b-11e7-8065-5980aa8463f7.png)
[table-merge-cells.svg.zip](https://github.com/Templarian/MaterialDesign/files/1587805/table-merge-cells.svg.zip)

**Comment by Templarian** [comment]
[![table-merge-cells](https://materialdesignicons.com/icon/table-merge-cells)](https://materialdesignicons.com/icon/table-merge-cells)
