### ISSUE TITLE
cloud-merge-up & cloud-merge-down

### ISSUE THREAD

**Issue by opus1269** [Templarian/MaterialDesign#2704]
Like cloud-upload, cloud-sync etc. but using the merge-type icon inside.

I think of cloud-sync as a two way operation - both the local and remote files would change for instance.

cloud-merge-down would be a one-way operation - the remote file contents would be merged into the local file contents.

There should be two icons: a cloud-merge-up and cloud-merge-down where the up would merge into the cloud and the down would merge into the local.   the merge-type icon could just be flipped vertically for the two types.

**Comment by JamesCoyle** [comment]
Might be a bit difficult squeezing that inside the icon.

**Comment by GreenTurtwig** [comment]
Yeah, if they wont be confused with anything else it's best to just use the standard `merge` icons.

**Comment by opus1269** [comment]
If it won't fit in the cloud, could you add a merge-type that is reflected vertically? That way I could differentiate between an upload merge and download merge.

**Comment by GreenTurtwig** [comment]
We tend not to add icons that are just another icon rotated, although there are a lot of exceptions to that...  
Could you not just flip the `merge-type` icon?

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
