### ISSUE TITLE
SVG license questions: MIT, SIL Apache ?

### ISSUE THREAD

**Issue by WideAngleDe** [Templarian/MaterialDesign#2705]
I'm a bit confused about the license for the SVG fonts:

https://github.com/Templarian/MaterialDesign-SVG/blob/master/LICENSE list an MIT license for the SVG fonts v2.1.19.

But,
https://github.com/Templarian/MaterialDesign/blob/master/license.txt lists the:
a) SIL OPEN FONT LICENSE Version 1.1 - 26 February 2007
and the for the Google fonts the 
b) Apache License 2.0 (via link: https://github.com/google/material-design-icons/blob/master/LICENSE)

My questions:
a) Shouldn't the MaterialDesign-SVG LICENSE  be the same as the MaterialDesign license.txt ?
     At least for the SVG files as they are derived form the SIL and Apache license files and can not? 
     Note: The few JSON files can be still MIT. 
     Or do I miss anything here?

In case I'm right with a)
b) Which SVG files are under the SIL OPEN FONT LICENSE ? and 
    Which are under the Apache License 2.0 ? 
    This is not clear.

**Comment by JamesCoyle** [comment]
The web-font and icons maintained in this repository is covered by the Open Font Licence. The SVG assets, documentation, and other site assets and data are covered by the MIT Licences of their respective repositories except where such assets are property of Google LLC, in which case those assets are covered under the Apache Licence with any modifications then being covered by the MIT Licence.

There aren't really any major differences between these licences anyway. The SVG data is released under MIT so third party tools don't have to employ the Open Font Licence which wouldn't make much sense. The SVG assets available publicly on the site ARE covered by the Open Font Licence as far as I'm aware.

**Comment by Templarian** [comment]
http://dev.materialdesignicons.com/license dev server has a License page we need to work on.

Yea, SIL won't work for the SVG since they are used by third party developers for various build tools and other things. I think the current licensing is correct, but we may need to work on the FAQ a little to explain the "Google" icons.

To be honest we should probably spend a little longer looking into this. It's been a rather low priority for me in the past since the goal was to open the SVG's to let third parties go nuts with tooling.

(on vacation, so it might take me longer than normal to respond, keeping this issue opened)

**Comment by WideAngleDe** [comment]
Sorry to push but the opens around the licenses start to become a showstopper to use the icons in the project I work on. Without a clean license clarification/resolution I will have to move to alternative icon sets before going online. Unfortunately as this icon set is great.

A simple resolution might be (if possible) that bitmap and SVGs will get aligned with the by Google's selected Apache 2.0 license.

**Comment by Templarian** [comment]
@WideAngleDe Discussed with the team and this will take a while to figure out. We'll be focusing on it in the future after the new site launch in a few months.

I would suggest using Google's MD Icons or Font Awesome 5 (+Pro) if the MIT / Apache 2 license combination are incompatible with your guidelines. We often find these two licenses are equally accepted, so it will be a while to solve for the small number where it is not compatible.

Thanks!

**Comment by goyney** [comment]
Please see #5480. We will be handling the license ambiguity in the v5.6 release.
