### ISSUE TITLE
Icon Request: vector-ellipse

### ISSUE THREAD

**Issue by jfuehner** [Templarian/MaterialDesign#2706]
I have a need for a **_ellipse_** icon to be used for a mapping interface. Presently, there are a collection of **vector-** icons which includes circle, rectangle, etc but none for ellipse.

Thanks!

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/34420260-43ae980e-ebce-11e7-9339-7d71a779df19.png)

Like this?

**Comment by jfuehner** [comment]
Well, technically an oval is different than an ellipse. You can visually see the difference in this image...

https://goo.gl/images/9pNg8r

When in terms of geometry there is also a difference from a mathematical perspective.

**Comment by Templarian** [comment]
Definitely meant to type ellipse yesterday (just typo'ed in the preview text field).

[![vector-ellipse](https://materialdesignicons.com/icon/vector-ellipse)](https://materialdesignicons.com/icon/vector-ellipse)

I think representing it with two anchor points makes sense. Let me know if this is not the case and I'll reopen the issue. 😃

**Comment by jfuehner** [comment]
@templarian, the anchor points look fine. I think the circle needs to be squished more to look like an ellipse...
