### ISSUE TITLE
3 People

### ISSUE THREAD

**Issue by dev-myatminsoe** [Templarian/MaterialDesign#2707]
There is an icon for 2 people. But there was an icon for 3 people. I can't find it anymore. Here's a xxhdpi version of that icon. (It's a white icon on transparent background)
![ic_people](https://user-images.githubusercontent.com/6258919/34413516-63bc4fe4-ec12-11e7-9f3a-b91d46be9ce5.png)

**Comment by GreenTurtwig** [comment]
![imag](https://user-images.githubusercontent.com/15905797/34934971-34884ad2-f9d4-11e7-9c21-a7384ee56312.png)![](https://user-images.githubusercontent.com/15905797/34934987-424ec42a-f9d4-11e7-9e62-c7d426ff149b.png)

[account-multiple-variant.zip](https://github.com/Templarian/MaterialDesign/files/1630985/account-multiple-variant.zip)

**Comment by MrGrigri** [comment]
I believe the second one -- where the front silhouette is larger.

**Comment by PeterShaggyNoble** [comment]
I concur.

**Comment by GreenTurtwig** [comment]
Yeah, I agree with that.  
Not sure how we would name this, `account-multiple-variant`could work but I don't agree with it personally.

**Comment by GreenTurtwig** [comment]
How about `account-group`?

**Comment by WebSavvyGuy** [comment]
I would also like to see this icon made.

**Comment by jeffshaver** [comment]
I would like this one as well

**Comment by PeterShaggyNoble** [comment]
It's already available and will be included in the next release.

[![](https://materialdesignicons.com/icon/account-group)](https://materialdesignicons.com/icon/account-group)

**Comment by ziyafenn** [comment]
Hey Guys, if you compare the height of this icon to the other on one line, this one has stands out due to height size. Is there any way to fix this?

Here is an example
https://www.dropbox.com/s/5v8ax5aidyyb3k3/Screenshot%202018-06-26%2011.53.32.png?dl=0

**Comment by ziyafenn** [comment]
@Templarian any update?

**Comment by Templarian** [comment]
Updated. 😃 Sorry that took so long.
