### ISSUE TITLE
Picture-in-Picture

### ISSUE THREAD

**Issue by tyler-austin** [Templarian/MaterialDesign#2709]
something similar to the watermark icon but better suited for overview maps and mini maps

**Comment by PeterShaggyNoble** [comment]
See the stock [`picture in picture`](https://material.io/icons/#ic_picture_in_picture) and [`picture in picture alt`](https://material.io/icons/#ic_picture_in_picture_alt) icons.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49038163-27c80180-f18a-11e8-8583-81d70042ff95.png)![image](https://user-images.githubusercontent.com/1015040/49038179-2eef0f80-f18a-11e8-904d-6de9256906a1.png)
![image](https://user-images.githubusercontent.com/1015040/49038191-37474a80-f18a-11e8-8d35-22f3a53ab407.png)![image](https://user-images.githubusercontent.com/1015040/49038202-3f06ef00-f18a-11e8-8c5c-a2f0b25f46b5.png)

[pip.zip](https://github.com/Templarian/MaterialDesign/files/2617099/pip.zip)

**Comment by Templarian** [comment]
Added these 4, but with more specific naming. `picture-in-picture-top-right-outline` for example.
