### ISSUE TITLE
Programming languages icons

### ISSUE THREAD

**Issue by GuiCavi** [Templarian/MaterialDesign#271]
It would be nice some html5, css3, js, Ajax, php, java, sql's and others.
Thanks :)
- [x] language-html5
- [x] language-css3
- [x] language-javascript
-  ajax (is this really needed?)
- [x] language-php
- [x] language-csharp
- [x] language-java
- [ ] language-sql
- [x] language-swift
- [x] language-python
- [x] language-python-text
- ...

**Comment by GuiCavi** [comment]
Sorry... It's "js" instead of "já"

**Comment by Templarian** [comment]
Added a couple of these.

**Comment by GuiCavi** [comment]
They are realy awesome. Thanks :smile:

**Comment by CoDEmanX** [comment]
As for Java, the officla logo is:

![Imgur](http://i.imgur.com/mjpmkJE.png?1)

But I doubt cup or cup + text are possible - so text only? In brand font face or materialized letters?

**Comment by Templarian** [comment]
I have the java one in vector already (text and cup), but it doesn't look nice at the small size.

**Comment by CoDEmanX** [comment]
PHP has been fulfulled: https://materialdesignicons.com/icon/language-php

A material-y SQL logo I found on http://www.looker.com/partners/google:
![google_cloud_sql_v0001](https://cloud.githubusercontent.com/assets/1309249/14137108/8d38b3ce-f666-11e5-8b11-020249ef7871.png)

**Comment by GreenTurtwig** [comment]
I submitted Swift here: https://github.com/Templarian/MaterialDesign/issues/969

**Comment by MrGrigri** [comment]
Here was my attempt at [language-java](https://github.com/Templarian/MaterialDesign/issues/1699)

**Comment by Croutonix** [comment]
Here's a Lua icon if anyone's interested:
![image](https://user-images.githubusercontent.com/33690959/37377136-9a6a8d36-26fe-11e8-90bd-9d9b5a62443f.png)
![image](https://user-images.githubusercontent.com/18645219/37377337-b6a8e5c8-26ff-11e8-9837-121ca779f3af.png)

[Download link](https://github.com/Templarian/MaterialDesign/files/1809167/icon.zip)

**Comment by Templarian** [comment]
[![language-lua](https://materialdesignicons.com/icon/language-lua)](https://materialdesignicons.com/icon/language-lua)

**Comment by SarinManS** [comment]
![image](https://user-images.githubusercontent.com/26505215/44302560-d3231800-a34a-11e8-96b6-c91031daa77b.png)

[language-java.zip](https://github.com/Templarian/MaterialDesign/files/2299815/language-java.zip)

**Comment by Templarian** [comment]
@SarinManS Just saw this.

[![language-java](https://materialdesignicons.com/icon/language-java)](https://materialdesignicons.com/icon/language-java)
