### ISSUE TITLE
fingerprint-off

### ISSUE THREAD

**Issue by othomas** [Templarian/MaterialDesign#2711]
Would be interested to have an icon "fingerprint off" , complementary to "fingerprint".
Could be useful to indicate that a fingerprint scanner is disconnected or sth like that.

**Comment by MrGrigri** [comment]
I'm not sure if I like this and there might be a better solution UI wise...however, here it is.

![image](https://user-images.githubusercontent.com/4528551/34490287-a8a2b192-ef9c-11e7-9bef-6172aa93788f.png)

[fingerprint-off.zip](https://github.com/Templarian/MaterialDesign/files/1598010/fingerprint-off.zip)

**Comment by CoDEmanX** [comment]
@MrGrigri Is it based on Google's fingerprint icon, or the MDI version?

![image](https://user-images.githubusercontent.com/1309249/37412127-9a3eb0e8-27a4-11e8-8b1c-3ca5656653da.png)

**Comment by MrGrigri** [comment]
This is based on the MDI I believe.

**Comment by Templarian** [comment]
Can't remember if it was modified for point count reasons. Let me double check this before adding this one.

**Comment by CoDEmanX** [comment]
I created the MDI version from a PNG of Google's icon before they released the SVG. We should update ours to theirs IMO: #2919

**Comment by Templarian** [comment]
Added. 😃
