### ISSUE TITLE
Network Attached Server

### ISSUE THREAD

**Issue by mads03dk** [Templarian/MaterialDesign#2712]
An icon with a nas server or synology would be nice

**Comment by PeterShaggyNoble** [comment]
Would `server-network` not serve this purpose? If not, could you provide an example?

[![server-network](https://user-images.githubusercontent.com/15157491/34479593-9a04ec2e-ef9f-11e7-86b0-2ab52b2072fe.png)](https://materialdesignicons.com/icon/server-network)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback and in favour of #2913, which includes a contribution.
