### ISSUE TITLE
Ripple (XRP) 

### ISSUE THREAD

**Issue by frittes** [Templarian/MaterialDesign#2713]
Icon for crypto currency RIPPLE.

Thanks in advance.

**Comment by PeterShaggyNoble** [comment]
I'm going to label this one as low priority for now as, while it does currently meet our criterion of 100k transactions per day, it has been around for 3 years now so its present popularity could well just be a "flash in the pan". Also, while I don't pretend (or want) to know anything about "cryptocurrencies", the fact that it's only worth US$2 probably isn't a good indicator of its continued popularity.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/34561268-0e25b564-f141-11e7-9d46-b3ed42f240af.png)](https://github.com/Templarian/MaterialDesign/files/1603163/ripple.zip)

**Comment by JamesCoyle** [comment]
Ripple has a ton of transactions per day now so I feel like it meets our usage criteria.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
