### ISSUE TITLE
about.me

### ISSUE THREAD

**Issue by yshalsager** [Templarian/MaterialDesign#2714]
An icon for https://about.me/
I think one like favicon will be cool
https://cdn.about.me/images/icons/favicon/favicon.ico

**Comment by PeterShaggyNoble** [comment]
about.me usage seems to be [declining](https://www.quantcast.com/measure/about.me) so this may not get added but brand assets can be found [here](https://about.me/assets).

**Comment by Templarian** [comment]
Yea, I think of it the same way as myspace or AOL. I'm going to close this out and mark as rejected. We have a future project to make a random brands webfont in the future and will use these labels to find them.
