### ISSUE TITLE
Money Settings

### ISSUE THREAD

**Issue by Maur0V** [Templarian/MaterialDesign#2718]
Hi, i'm lookin for an icon like   cash  having a small gear in a corner to be used for something like setting money value/price 
thank's to all

**Comment by MrGrigri** [comment]
Settings specific to items in this pack are generally represented with three dots under the item instead of using the cog -- with a couple of exceptions of course. Settings for money might be a little to niche for this project.

**Comment by PeterShaggyNoble** [comment]
Maybe `credit-card` with the 3 dots underneath, to represent payment settings?

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
