### ISSUE TITLE
Bubble Size

### ISSUE THREAD

**Issue by DaredArt** [Templarian/MaterialDesign#2719]
![bubble size](https://user-images.githubusercontent.com/35063122/34516508-53abe66e-f077-11e7-989a-7829e092d587.png)
![bubble size 2x](https://user-images.githubusercontent.com/35063122/34516509-53ca8bc8-f077-11e7-9f46-67e3c7d36cfd.png)

**Comment by MrGrigri** [comment]
What would this be used for?

**Comment by goyney** [comment]
No more information was ever provided about this request, so we're going to close it. Please comment providing the requested information if you'd like this request reconsidered. Thanks!
