### ISSUE TITLE
Multiple Translations Icon

### ISSUE THREAD

**Issue by solomojo** [Templarian/MaterialDesign#2721]
Here is a multiple-translations icon
[multiple-translations.zip](https://github.com/Templarian/MaterialDesign/files/1602081/multiple-translations.zip)

**Comment by MrGrigri** [comment]
I'm not such a fan of the design. I believe it's too small and doesn't follow MD with 2px offsets and spacing.

**Comment by goyney** [comment]
Preview of @solomojo's contribution:
![image](https://user-images.githubusercontent.com/1015040/63067796-a7475d80-bede-11e9-9179-bad44f511913.png)

**Comment by goyney** [comment]
I agree with @MrGrigri, this doesn't work because it becomes indistinguishable at native resolution.
