### ISSUE TITLE
Bitwarden

### ISSUE THREAD

**Issue by BeatriceFendt** [Templarian/MaterialDesign#2722]
I would love to have an icon for the [open-source](https://github.com/bitwarden) [Bitwarden](https://bitwarden.com/) password management solution

Example: https://github.com/bitwarden/website/blob/master/images/icons/android-chrome-512x512.png

**Comment by PeterShaggyNoble** [comment]
I'm going to close this one out for now. Per our [contributing guidelines](https://github.com/Templarian/MaterialDesign/blob/master/CONTRIBUTING.md):
> Please note that, at this time, the only brand icons we accept requests for are popular social media sites/apps and widely used products/software.

We may revisit this issue in the future, if we decide to add a dedicated icon pack for brands.
