### ISSUE TITLE
Controller D-Pad directions

### ISSUE THREAD

**Issue by risingwolf21** [Templarian/MaterialDesign#2723]
It would be great if someone designs controller buttons. Like an A-Button, a B-Button and a Cursor. Like the ones from an old GameBoy

**Comment by PeterShaggyNoble** [comment]
`gamepad` already exists. For `A` and `B`, you could simply layer the characters over one of the many circle icons. See #1299 for further discussion on letter "icons".

[![gamepad](https://user-images.githubusercontent.com/15157491/34608373-f212810c-f20f-11e7-984d-2a4be95dcff6.png)](https://materialdesignicons.com/icon/gamepad)

**Comment by GreenTurtwig** [comment]
See https://github.com/Templarian/MaterialDesign/issues/2411

**Comment by Templarian** [comment]
Adding the Alpha-Numeric tag so we can track this when we have more time to build out the Letters and Numbers font. We would have to look into circle/box designs for these.

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/34821730-943702fe-f6bc-11e7-8dee-bdaf1d5fd186.png)![](https://user-images.githubusercontent.com/15905797/34821749-9e607f76-f6bc-11e7-8366-c5087a0f5372.png)

![](https://user-images.githubusercontent.com/15905797/34821920-112e7814-f6bd-11e7-822e-ce5805edd0cf.png)![](https://user-images.githubusercontent.com/15905797/34821938-22b9b62a-f6bd-11e7-8e94-457897be7a2a.png)![](https://user-images.githubusercontent.com/15905797/34821955-2e937ada-f6bd-11e7-999f-70f72418aacf.png)![](https://user-images.githubusercontent.com/15905797/34821965-34a1f10e-f6bd-11e7-86c8-fddc941f8572.png)

![](https://user-images.githubusercontent.com/15905797/34822646-8f70c194-f6bf-11e7-9273-669b04547a97.png)![](https://user-images.githubusercontent.com/15905797/34822392-b192b724-f6be-11e7-8c37-2f71a8fa8334.png)![](https://user-images.githubusercontent.com/15905797/34822833-2e207852-f6c0-11e7-802a-ef48e87a61d5.png)![](https://user-images.githubusercontent.com/15905797/34822857-3c6726ea-f6c0-11e7-9195-8c78eaf84da2.png)![](https://user-images.githubusercontent.com/15905797/34822898-5d57cc60-f6c0-11e7-89fa-13f6e60bc29b.png)

[xbox-controller-buttons.zip](https://github.com/Templarian/MaterialDesign/files/1622298/xbox-controller-buttons.zip)

**Comment by GreenTurtwig** [comment]
Might need to think about the names. The A, B, X, Y and d-pad buttons are also used for Nintendo consoles, not only Xbox.  
Also, as @PeterShaggyNoble showed above, the PlayStation d-pad is named `gamepad`.

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/34823174-66c357dc-f6c1-11e7-8409-87b423af3db5.png)![](https://user-images.githubusercontent.com/15905797/34823190-720f02f8-f6c1-11e7-87e3-b2fdcb2dd1e1.png)![](https://user-images.githubusercontent.com/15905797/34823205-7ac1d9c0-f6c1-11e7-9ed1-de2360e16de9.png)![](https://user-images.githubusercontent.com/15905797/34823216-856c3b90-f6c1-11e7-9113-46f22852b03c.png)

[playstation-controller-dpad.zip](https://github.com/Templarian/MaterialDesign/files/1622315/playstation-controller-dpad.zip)

**Comment by CoDEmanX** [comment]
It's pretty blurry. Maybe there's another way to make it pixel perfect?

![image](https://user-images.githubusercontent.com/1309249/38773184-e6fad0aa-4046-11e8-8845-3f8a7b607145.png)

**Comment by goyney** [comment]
The A, B, X, and Y buttons are now covered by the `alpha-*-circle` icons. I really don't think we need the D-pad direction designations.

**Comment by goyney** [comment]
We'll use this issue to track the four D-Pad directions contributed by @GreenTurtwig.

**Comment by JapanYoshi** [comment]
![dpad](https://user-images.githubusercontent.com/8707990/53690089-a21ea800-3daf-11e9-906a-98f05fc8dcff.png)
![dpad2](https://user-images.githubusercontent.com/8707990/53690090-a21ea800-3daf-11e9-9de0-d8ebd8e6fdd1.png)
![dpad-outline](https://user-images.githubusercontent.com/8707990/53690091-a21ea800-3daf-11e9-874c-8d41bfed25a1.png)
![dpad-outline2](https://user-images.githubusercontent.com/8707990/53690092-a2b73e80-3daf-11e9-9c95-056b4a5ba55e.png)
![dpad-right](https://user-images.githubusercontent.com/8707990/53690093-a2b73e80-3daf-11e9-8a0c-11e65c117391.png)
![dpad-right2](https://user-images.githubusercontent.com/8707990/53690094-a2b73e80-3daf-11e9-87bb-4aa2d6549cb4.png)
![switch-button-right](https://user-images.githubusercontent.com/8707990/53690095-a34fd500-3daf-11e9-8fa5-ed900dfe7fb3.png)
![switch-button-right2](https://user-images.githubusercontent.com/8707990/53690096-a34fd500-3daf-11e9-92d0-9e9023596dba.png)
I made some Nintendo Switch style stuff just to try it.

**Comment by Templarian** [comment]
Added. Not 100% sure on the naming, but wanted to keep it generic.
