### ISSUE TITLE
Attendance

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2724]
I don't know if this is the best name; maybe instruct or teach. However, here is an icon for that.

![attendance](https://user-images.githubusercontent.com/4528551/34622055-d90a531c-f208-11e7-9aa6-3e73d43ff578.png)

[attendance.zip](https://github.com/Templarian/MaterialDesign/files/1607480/attendance.zip)

**Comment by Templarian** [comment]
I like the icon, but yea, not the right name. `instructor` / `teacher` or something. Any other ideas?

**Comment by PeterShaggyNoble** [comment]
It's a tricky one, alright. I'd have said `presentation` if we didn't already have an icon for that.

**Comment by GreenTurtwig** [comment]
I would go with `teacher` considering `presentation` is already being used.

**Comment by JamesCoyle** [comment]
#2104

**Comment by JamesCoyle** [comment]
Whoops.. 

Yeah I think teacher with a few aliases for professor etc.

**Comment by MrGrigri** [comment]
Yeah, I believe `teach` as a verb and not the noun. Just like we have `run` and not `running`.

**Comment by Templarian** [comment]
[![teach](https://materialdesignicons.com/icon/teach)](https://materialdesignicons.com/icon/teach)
