### ISSUE TITLE
home-alert

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2725]
Here is a home-alert concept for home automation/IoT.

![image](https://user-images.githubusercontent.com/4528551/34624399-5de78c0e-f212-11e7-92a2-b5c904078818.png)

[home-alert.zip](https://github.com/Templarian/MaterialDesign/files/1607648/home-alert.zip)

**Comment by Templarian** [comment]
[![home-alert](https://materialdesignicons.com/icon/home-alert)](https://materialdesignicons.com/icon/home-alert)
