### ISSUE TITLE
Confluence

### ISSUE THREAD

**Issue by ramzimaalej** [Templarian/MaterialDesign#2727]

**Comment by goyney** [comment]
We already have `jira`:
[![jira](https://materialdesignicons.com/icon/jira)](https://materialdesignicons.com/icon/jira)

Here is one for `confluence`:
![image](https://user-images.githubusercontent.com/1015040/49037845-50033080-f189-11e8-8687-c244ed8611b5.png)

[confluence.svg.zip](https://github.com/Templarian/MaterialDesign/files/2617089/confluence.svg.zip)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
