### ISSUE TITLE
DumDarac

### ISSUE THREAD

**Issue by cachopawa** [Templarian/MaterialDesign#2728]
dumdarac.com
Free Social Platform

**Comment by GreenTurtwig** [comment]
I've personally never heard of it before and I doubt many others have either, I could find very little information online. This is definitely too niche to include.  
  
Also, I have no idea how they're getting away with using Google assets:
![](https://user-images.githubusercontent.com/15905797/34664344-452e3e18-f453-11e7-82b6-d9041cce74ff.png)
(I do find it funny how Project Tango is being used for applications.)
