### ISSUE TITLE
Pie, Arc chart icon

### ISSUE THREAD

**Issue by QuadFlask** [Templarian/MaterialDesign#273]
Pie char icon 

![https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQfiTWZSj1RM-haaZ8hUIjFI4OmerTbv-IXtoyaU4wLhbZuZTfF5w](https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQfiTWZSj1RM-haaZ8hUIjFI4OmerTbv-IXtoyaU4wLhbZuZTfF5w)

Arc chart icon

![https://camo.githubusercontent.com/7e8a4a3c938c21d032d44d999edd781b6e146f2a/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d50416e64726f696443686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f7069656368617274312e706e67](https://camo.githubusercontent.com/7e8a4a3c938c21d032d44d999edd781b6e146f2a/68747470733a2f2f7261772e6769746875622e636f6d2f5068696c4a61792f4d50416e64726f696443686172742f6d61737465722f73637265656e73686f74732f73696d706c6564657369676e5f7069656368617274312e706e67)

or, is there already exist similar?

- [ ] chart-pie
- [ ] chart-arc

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/chart-pie
http://materialdesignicons.com/icon/chart-arc
