### ISSUE TITLE
Google Home Mini

### ISSUE THREAD

**Issue by UserNAMEPersonThingy** [Templarian/MaterialDesign#2731]
Google Home Mini and light strip icon please.

**Comment by UserNAMEPersonThingy** [comment]
Maybe something similar to these:
![google-home-mini](https://user-images.githubusercontent.com/26513182/34758023-3917f63c-f629-11e7-8211-5e5ae6a9b81c.png)
![light-strip](https://user-images.githubusercontent.com/26513182/34758088-8adba540-f629-11e7-9aed-c3c5dd91d9d9.png)

**Comment by GreenTurtwig** [comment]
We already have an LED strip.
[![](https://materialdesignicons.com/icon/led-strip)](https://materialdesignicons.com/icon/led-strip)

Personally I don't believe we should add devices like the Mini, we only have the Home as it's a stock Google icon. If we do decide to end up adding it, that would mean we would also have to add icons for the Max and smart displays for example. Not event mentioning all the Echo devices like the Gen 1, Gen 2, Dot, Show and Spot. It would be best to just use the Google Assistant or Amazon Alexa icons for smart speakers.

**Comment by PeterShaggyNoble** [comment]
The Google Home Mini looks quite similar to `dots-horizontal-circle`:

[![dots-horizontal-circle](https://user-images.githubusercontent.com/15157491/34766115-57ccf548-f5eb-11e7-98c0-52322ff2d396.png)](https://materialdesignicons.com/icon/dots-horizontal-circle)

**Comment by Templarian** [comment]
This is a tad too specific for right now. Closing this issue.

There is way too many devices on the market and they release a new one every other day.
