### ISSUE TITLE
Phone rotate orientation one way icon

### ISSUE THREAD

**Issue by TeaStar** [Templarian/MaterialDesign#2732]
An icon request to represent rotating the phone from portrait -> landscape and visa versa. For example:
https://www.iconfinder.com/icons/1588818/design_development_device_orientation_landscape_portrait_vertical_icon

I see an existing icon for phone rotation but the arrows go both ways.

Ideally 2 new icons will be created representing rotating the phone from portrait -> landscape and landscape -> portrait.

**Comment by MrGrigri** [comment]
How are these?

![image](https://user-images.githubusercontent.com/4528551/34734926-d33c0fb4-f52a-11e7-9118-8e6fe6363d7d.png) ![image](https://user-images.githubusercontent.com/4528551/34734943-e146a574-f52a-11e7-9b13-bf3ed8415b29.png)

[phone-rotate.zip](https://github.com/Templarian/MaterialDesign/files/1616110/phone-rotate.zip)

**Comment by TeaStar** [comment]
Yes they look great! Only comment: would a home button make it more recognizable as a phone? I know phone manufactures are moving away from home buttons so maybe keep them as they are.

**Comment by Templarian** [comment]
[![phone-rotate-landscape](https://materialdesignicons.com/icon/phone-rotate-landscape)](https://materialdesignicons.com/icon/phone-rotate-landscape) [![phone-rotate-portrait](https://materialdesignicons.com/icon/phone-rotate-portrait)](https://materialdesignicons.com/icon/phone-rotate-portrait)
