### ISSUE TITLE
Light Switch

### ISSUE THREAD

**Issue by naofireblade** [Templarian/MaterialDesign#2734]
An icon for a light switch would be really nice to use in home automation software like home assistant. The current dip-switch does not represent a light switch very well. 

Maybe versions for single/double light switches and EU/US variants would make this complete.

Example for double light switch EU:
![grafik](https://user-images.githubusercontent.com/12081369/34715888-7470115c-f52e-11e7-882c-14df57cd82f6.png)

**Comment by MrGrigri** [comment]
Idk if at first sight if that would convey a light switch.

**Comment by naofireblade** [comment]
It does in germany :) . This seems very region specific. You consider this as a light switch?

![image](https://user-images.githubusercontent.com/12081369/34742310-ff21f142-f585-11e7-86dc-2f7878a90aa3.png)

**Comment by MrGrigri** [comment]
@naofireblade, that's not what I'm talking about. In the US, we have all kinds of light switches, including both of the above mentioned. What I am saying, is if you were to show the first icon to someone, without them knowing what it is supposed to be/represent, they will have a difficulty identifying it. The first icon could be a window, a box in a container, etc.

**Comment by AbFarid** [comment]
Yes, we really need a light switch. Perhaps something like this (just a quick edit):

![light-switch](https://user-images.githubusercontent.com/8946919/34907311-44043e94-f885-11e7-9345-28dffe9ce061.png)

**Comment by naofireblade** [comment]
Thanks for your reply. I think side view would not fit because a button icon is something you could really press in the ui. That feels weird with a side view icon.
I know the given examples are not perfect. Maybe no perfect ones exist but this icon is really missing in any home automation ui.

**Comment by MrGrigri** [comment]
Me personally, I would use `lightbulb` and `lightbulb-outline` for the on and off states.

![lightbulb](https://materialdesignicons.com/icon/lightbulb) ![lightbulb-outline](https://materialdesignicons.com/icon/lightbulb-outline)

**Comment by AbFarid** [comment]
Switch does not necessarily turns on/off a lamp, so a lightbulb icon is not the solution.

**Comment by MrGrigri** [comment]
@AbFarid, this request is for a 'light switch'...so yeah, it would. If it were for just a switch, I would suggest the [toggle-switch](https://materialdesignicons.com/icon/toggle-switch) icon.

**Comment by naofireblade** [comment]
Yeah the toggle-switch is the closest match.

**Comment by naofireblade** [comment]
Request ist for light-switch because thats the name for the switch on the wall. The switch itself is not a lightbulb. A lightbulb is a totally different object (usally under the ceiling :D ).

**Comment by MrGrigri** [comment]
Then I would go with [toggle-switch](https://materialdesignicons.com/icon/toggle-switch).

**Comment by PeterShaggyNoble** [comment]
@GreenTurtwig has found a Google icon that should fulfil this request.

**Comment by kacboy** [comment]
@PeterShaggyNoble @GreenTurtwig Where, which?

**Comment by GreenTurtwig** [comment]
Finally got around to recreating it. This is the icon used in Google Assistant.

[![](https://user-images.githubusercontent.com/15905797/39867701-1554ab54-544e-11e8-81eb-7a0ddd7b3661.png)](https://github.com/Templarian/MaterialDesign/files/1991461/light-switch.zip)

**Comment by Templarian** [comment]
I actually like this one and it's probably a good use of the 1dp line.

[![light-switch](https://materialdesignicons.com/icon/light-switch)](https://materialdesignicons.com/icon/light-switch)
