### ISSUE TITLE
hd-box

### ISSUE THREAD

**Issue by ekkash** [Templarian/MaterialDesign#2735]
Hi, great work on this project! It's amazing.

Hopefully a small request, an icon similar to the [video-4k-box](https://materialdesignicons.com/icon/video-4k-box) and the [new-box](https://materialdesignicons.com/icon/new-box) although with the text "HD".

What d'ya reckon?

Regards,
Ashley

**Comment by MrGrigri** [comment]
We have HD, but it's not in a box.

![high-definition](https://materialdesignicons.com/icon/high-definition)

**Comment by MrGrigri** [comment]
Also look at #2114.

**Comment by PeterShaggyNoble** [comment]
That's one of the stock icons:

[![hd](https://user-images.githubusercontent.com/15157491/34766328-f429382a-f5eb-11e7-882c-4f7206979844.png)](https://material.io/icons/#ic_hd)

**Comment by Templarian** [comment]
[![high-definition-box](https://materialdesignicons.com/icon/high-definition-box)](https://materialdesignicons.com/icon/high-definition-box)
