### ISSUE TITLE
System Include Icon

### ISSUE THREAD

**Issue by OctoberJemini** [Templarian/MaterialDesign#2737]
Need an icon to represent system includes, which would be anything from CSS, JS, PHP, ASP.net, etc.

![code-brackets-24](https://user-images.githubusercontent.com/20706106/34777768-5eacc5fc-f5e9-11e7-92fe-b55d99ccd5ca.png)
![code-brackets-48](https://user-images.githubusercontent.com/20706106/34777772-60490574-f5e9-11e7-95c6-a04e606240b7.png)

[include.zip](https://github.com/Templarian/MaterialDesign/files/1619189/include.zip)

**Comment by PeterShaggyNoble** [comment]
Would `code-brackets` on its own suffice?

[![code-brackets](https://user-images.githubusercontent.com/15157491/34778367-129d1960-f615-11e7-9df9-c61e67d2c4db.png)](https://materialdesignicons.com/icon/code-brackets)

**Comment by OctoberJemini** [comment]
Yes and know... typically that would be a code reference, i need something very specific for include reference.  

Update Icons to be cleaner
[include.zip](https://github.com/Templarian/MaterialDesign/files/1619253/include.zip)

**Comment by OctoberJemini** [comment]
I think you might be right... to much of a niche case to include in the library... please disregard

**Comment by MrGrigri** [comment]
The `attachment` and `paperclip` icons are typically associated with the term 'include'.

![attachment](https://materialdesignicons.com/icon/attachment) ![paperclip](https://materialdesignicons.com/icon/paperclip)

**Comment by Templarian** [comment]
Closing this out as it's going to be too niche.

We can reopen in the future if a more general icon is suggested.
