### ISSUE TITLE
Video doorbell

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2738]
[![](https://user-images.githubusercontent.com/15905797/34831536-278d2002-f6df-11e7-8c55-5b7b321c79cf.png)](https://github.com/Templarian/MaterialDesign/files/1623070/doorbell-video.zip)

**Comment by Templarian** [comment]
[![doorbell-video](https://materialdesignicons.com/icon/doorbell-video)](https://materialdesignicons.com/icon/doorbell-video)
