### ISSUE TITLE
Unicorn

### ISSUE THREAD

**Issue by ghalimi** [Templarian/MaterialDesign#2739]
Profile of unicorn' head looking to the right.

**Comment by PeterShaggyNoble** [comment]
Out of curiosity: why specifically facing right?

**Comment by ghalimi** [comment]
Looking to the future maybe?

**Comment by JamesCoyle** [comment]
Need to use the icon we add for #174 as the base to stay consistent.

**Comment by Xenomorph99** [comment]
[unicorn.svg.zip](https://github.com/Templarian/MaterialDesign/files/4909590/unicorn.svg.zip)
![87211747-3409bf80-c2d8-11ea-919f-f90e48463cf4](https://user-images.githubusercontent.com/1837101/87257172-def3b800-c455-11ea-8fe4-9610ad483fe1.png)

**Comment by Xenomorph99** [comment]
Here's another iteration.

![unicorn](https://user-images.githubusercontent.com/1837101/89259216-1255dc80-d5e7-11ea-94c5-fcf4bebc82ca.png)

[unicorn.zip](https://github.com/Templarian/MaterialDesign/files/5020379/unicorn.zip)

**Comment by Xenomorph99** [comment]
Similar to #174, here's a head variant for the unicorn.

![unicorn-head](https://user-images.githubusercontent.com/1837101/89317884-3fcc7580-d63b-11ea-9183-945fdb42771a.png)

[unicorn-head.zip](https://github.com/Templarian/MaterialDesign/files/5023211/unicorn-head.zip)

**Comment by goyney** [comment]
[![unicorn](https://materialdesignicons.com/icon/unicorn)](https://materialdesignicons.com/icon/unicorn)[![unicorn-variant](https://materialdesignicons.com/icon/unicorn-variant)](https://materialdesignicons.com/icon/unicorn-variant)
