### ISSUE TITLE
Bullhorn Icon

### ISSUE THREAD

**Issue by cyberlake** [Templarian/MaterialDesign#274]
Having bullhorn icon would be really good. Something like
https://www.google.ie/search?q=bullborn&source=lnms&tbm=isch&sa=X&ei=eZMmVcnFG87kasGlgPgC&ved=0CAgQ_AUoAg&biw=2133&bih=1076&dpr=0.9#tbm=isch&q=bullhorn+icon

- [ ] bullhorn

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/bullhorn
