### ISSUE TITLE
Web site issues with links and search field

### ISSUE THREAD

**Issue by vanowm** [Templarian/MaterialDesign#2740]
Hello. Not sure if this is correct place submit issues regarding website...

1) A lot of links are impossible to open in new tab/window (even link to github) It ignores CTRL + Click or Middle click that normally used to open links in new tab)

2) home/end keys don't work in search field

3) Advance Export - doesn't have good explanation what's working and what's not. Anything that is not "package" can be considered as "single icon", but evidently only export of .png image is currently supported. Perhaps removing the buttons that don't work, would solve this issue.

**Comment by Templarian** [comment]
This is all being worked on in the new site/repo that is in progress (and open source). If you could please open issues in that repo so we can track them separate from the icons (there is a dev build at http://dev.materialdesignicons.com/ running also, note all cache is disabled, so some endpoints may seem to hang, this is just temporary for testing).

Advanced export is a massive feature that will be getting a UX overhaul (I really just started hacking features on without much thought put into the UX).

https://github.com/Templarian/MaterialDesign-Site
