### ISSUE TITLE
Watch variant (square)

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2742]
[![](https://user-images.githubusercontent.com/15905797/34934313-ebbc3ba8-f9d1-11e7-949e-e318a123ca74.png)](https://github.com/Templarian/MaterialDesign/files/1630919/watch-variant.zip)

**Comment by Templarian** [comment]
[![watch-variant](https://materialdesignicons.com/icon/watch-variant)](https://materialdesignicons.com/icon/watch-variant)
