### ISSUE TITLE
Leak Icon

### ISSUE THREAD

**Issue by pmontgo33** [Templarian/MaterialDesign#2744]
Looking for an icon to represent a leak sensor in Home Assistant. Maybe dripping water from a faucet or pipe?

**Comment by JamesCoyle** [comment]
We have `water-pump`:
[![](https://materialdesignicons.com/icon/water-pump)](https://materialdesignicons.com/icon/water-pump)

**Comment by pmontgo33** [comment]
I've used water pump in home Assistant before for my sprinkler system. I think for a leak icon we can do better

**Comment by GreenTurtwig** [comment]
You suggested "dripping water from a faucet", the icon above is exactly that.  
If a pipe is specifically needed it would be best to stay consistent with [`https://materialdesignicons.com/icon/pipe`](https://materialdesignicons.com/icon/pipe).

**Comment by pmontgo33** [comment]
Here are some I found via Google search:

https://d30y9cdsu7xlg0.cloudfront.net/png/53019-200.png
https://d30y9cdsu7xlg0.cloudfront.net/png/192016-200.png
http://freeflaticons.com/wp-content/uploads/2014/09/pipe-copy-1411474992kgn84.png

The third one is more consistent as you said, but I think it is the least descriptive of a leak.

**Comment by MrGrigri** [comment]
Would `pipe-disconnected` work?

![pipe-disconnected](https://materialdesignicons.com/icon/pipe-disconnected)

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/35392490-f9e60f00-01d9-11e8-8d89-db10d6f977a4.png)](https://github.com/Templarian/MaterialDesign/files/1664258/pipe-leak.zip)
Not a fan. :-/

**Comment by Templarian** [comment]
I think this is a useful icon, I'm going to add the one above for now. We can always replace it later.

[![pipe-leak](https://materialdesignicons.com/icon/pipe-leak)](https://materialdesignicons.com/icon/pipe-leak)
