### ISSUE TITLE
YouTube playback speed icon

### ISSUE THREAD

**Issue by bernaferrari** [Templarian/MaterialDesign#2745]
It would be nice to see this in your icons:
![youtube-video-speed](https://user-images.githubusercontent.com/351125/34948919-a8ac07fc-f9f5-11e7-83cf-caa8318abf61.jpg)

This is the icon isolated. It is called "quantum_ic_slow_motion_video_grey600_24" internally.
![quantum_ic_slow_motion_video_grey600_24](https://user-images.githubusercontent.com/351125/34949654-d547b3f4-f9f7-11e7-874f-9b3bcbe0e2bf.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/34958564-b46d9b88-f9ef-11e7-8bc6-e4c1aad3a825.png)

[play-speed.zip](https://github.com/Templarian/MaterialDesign/files/1632805/play-speed.zip)

**Comment by JamesCoyle** [comment]
Added play circle outline for reference. I think we should try match that style.

**Comment by bernaferrari** [comment]
In case it helps, it looks very similar to the current slow motion video icon, except for the play at center. So if you have it near, might make things easier.
BTW, great work!

**Comment by MrGrigri** [comment]
Here is an updated version:

![image](https://user-images.githubusercontent.com/4528551/34998887-7bb0f91c-fa9d-11e7-9630-ee68f8b2c340.png)

[play-speed.zip](https://github.com/Templarian/MaterialDesign/files/1635883/play-speed.zip)

**Comment by bernaferrari** [comment]
I have a question, is there any reason or anything missing, since this has not being merged?

**Comment by Templarian** [comment]
[![play-speed](https://materialdesignicons.com/icon/play-speed)](https://materialdesignicons.com/icon/play-speed)

I have a bad habit of ignoring stuff now if it doesn't have a milestone. Added it.
