### ISSUE TITLE
Peace symbol

### ISSUE THREAD

**Issue by LiadIdan** [Templarian/MaterialDesign#2749]
![211-peace](https://user-images.githubusercontent.com/19666213/35041321-ffabb08c-fb8c-11e7-9212-ada4ab03a5e5.png)

**Comment by MrGrigri** [comment]
A little surprising that we don't have this one.

![image](https://user-images.githubusercontent.com/4528551/35051554-bcd185cc-fb62-11e7-83d9-b91a28522d2c.png)

[peace.zip](https://github.com/Templarian/MaterialDesign/files/1639591/peace.zip)

**Comment by Templarian** [comment]
Also surprised this didn't exist already.

[![peace](https://materialdesignicons.com/icon/peace)](https://materialdesignicons.com/icon/peace)
