### ISSUE TITLE
d12 die

### ISSUE THREAD

**Issue by absorr** [Templarian/MaterialDesign#2751]
This is building off of the pre-existant die icons sparked by a [previous issue](https://github.com/Templarian/MaterialDesign/issues/1005).

The d12 die is common for tabletop RPG's and should be included with the others.

**Comment by MrGrigri** [comment]
Idk about this one. To match the others, it needs to be a decahedron, but with 10 points, it looks more like a circle. However, if we use the flat face of a pentagon, then it looks better.

![image](https://user-images.githubusercontent.com/4528551/35063267-d6550098-fb83-11e7-92ed-e1345131f341.png) ![image](https://user-images.githubusercontent.com/4528551/35063288-e4070010-fb83-11e7-8db3-6822218f4394.png)

[dice-d12.zip](https://github.com/Templarian/MaterialDesign/files/1640369/dice-d12.zip)

**Comment by absorr** [comment]
The other ones use the face as well, so it works to use the pentagon

**Comment by MrGrigri** [comment]
Ok, we'll go with the pentagon faced icon. Use the `dice-d12.zip` file from above.

![image](https://user-images.githubusercontent.com/4528551/35070422-7a42f2ee-fb9a-11e7-80d6-fed862eed94b.png)

**Comment by Templarian** [comment]
[![dice-d12](https://materialdesignicons.com/icon/dice-d12)](https://materialdesignicons.com/icon/dice-d12)
