### ISSUE TITLE
Iron icon

### ISSUE THREAD

**Issue by RobRum** [Templarian/MaterialDesign#2752]
Would be great to get an icon for an iron, especially for use in HomeAssistant

![example-iron](https://user-images.githubusercontent.com/2320705/35063628-8df75436-fbbf-11e7-8a25-5cad473c3504.png)

**Comment by RobRum** [comment]
Example iron icon from https://thenounproject.com/term/iron/148493/

**Comment by eleumas** [comment]
please, add iron icon :)

**Comment by gex64** [comment]
still nothing ?

**Comment by Templarian** [comment]
Doesn't look like anyone has tried their hand at designing this one yet. Some of these more niche icons take a little longer @gex64.

**Comment by guiumb** [comment]
Dear All, there are some good news about iron?

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73597873-46b1e880-4531-11ea-97bc-951635e160ce.png)

**Comment by nilsfast** [comment]
Complains?

**Comment by gex64** [comment]
great

**Comment by JamesCoyle** [comment]
Looks more like a curling stone to me. Needs less rounded corners.

**Comment by gex64** [comment]
please add iron icon  to repository

**Comment by skank01** [comment]
i agree fot an icon 👍

**Comment by quinnter** [comment]
![Screenshot 2021-01-14 at 22 07 36](https://user-images.githubusercontent.com/45169425/104654987-ec178b00-56b4-11eb-95c1-9c6fb11a58db.png)

 Could something like this work better?

**Comment by gex64** [comment]
Perfect

**Comment by guiumb** [comment]
nice one!

**Comment by nils-fast** [comment]
I don't think that it would fit the [Material Design Guidelines.](https://material.io/design/iconography/system-icons.html#system-icon-metrics)
![image](https://user-images.githubusercontent.com/58486458/104695643-5d832800-570d-11eb-9b67-298b3c4b705c.png)

**Comment by quinnter** [comment]
Sorry for any confusion, I didn't make this but I grabbed this image as a reference!  I still think  it's better than having it on its side? I would have made a new request but I saw this one was still open

**Comment by nils-fast** [comment]
But still, an icon like this would probably not comly with the guidelines. I think your image would look better than my design.

**Comment by zumheulen** [comment]
Wanted in 2018 and still no iron symbol three years later? What's wrong with you? do you wear your laundry wrinkled? :-)

**Comment by rohamishop** [comment]
> 
> 
> Would be great to get an icon for an iron, especially for use in HomeAssistant
> 
> ![example-iron](https://user-images.githubusercontent.com/2320705/35063628-8df75436-fbbf-11e7-8a25-5cad473c3504.png)

hello dear friend
how can i add iron steam icon in Material design library?

**Comment by goyney** [comment]
[![iron](https://materialdesignicons.com/icon/iron)](https://materialdesignicons.com/icon/iron)[![iron-outline](https://materialdesignicons.com/icon/iron-outline)](https://materialdesignicons.com/icon/iron-outline)
