### ISSUE TITLE
NativeScript icon

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2753]
https://www.nativescript.org/

![image](https://user-images.githubusercontent.com/1309249/35099890-f72dcb3e-fc59-11e7-9569-f2998fe2add9.png)

Some attempts:

![native-script](https://user-images.githubusercontent.com/1309249/35099833-c24830b2-fc59-11e7-9714-6769d728a6dc.png) ![native-script-small](https://user-images.githubusercontent.com/1309249/35099834-c261b078-fc59-11e7-91bf-911fd0e62610.png) ![native-script-small-4px-rounding](https://user-images.githubusercontent.com/1309249/35099879-eb3ee3ee-fc59-11e7-8380-1e1736721242.png)

I can share a cleaned up SVG if we decide to include it.

**Comment by Templarian** [comment]
We can get this added if someone wants to clean up a 24x24 (where the box is 18x18).

**Comment by Templarian** [comment]
[![nativescript](https://materialdesignicons.com/icon/nativescript)](https://materialdesignicons.com/icon/nativescript)

I just traced it really quick and assigned it to the contributor generic account.
