### ISSUE TITLE
Smart home hub

### ISSUE THREAD

**Issue by czingosz** [Templarian/MaterialDesign#2754]
![broadlink_04](https://user-images.githubusercontent.com/35568708/35103288-b5aa95b4-fc65-11e7-8fce-4ec8b7d42972.png)

**Comment by GreenTurtwig** [comment]
We don't usually include very specific devices like the Broadlink hub, however it might be worth having a "smart home hub" icon with a couple variants so I'll rename this issue.

**Comment by goyney** [comment]
"Smart home hub" is overly generic. What what that even look like? I think this is an improbable concept for a single icon. Unless someone comes up with some examples of what this might look like, I'm going to close this.
