### ISSUE TITLE
Server-Lock

### ISSUE THREAD

**Issue by fxmountain** [Templarian/MaterialDesign#2755]
server + lock
![server-lock](https://user-images.githubusercontent.com/30648730/35109065-9088bc42-fc75-11e7-85e1-f5db39f3f6d2.jpg)

[server-lock.zip](https://github.com/Templarian/MaterialDesign/files/1643616/server-lock.zip)

**Comment by PeterShaggyNoble** [comment]
We already have a `server-security` icon:

[![server-security](https://user-images.githubusercontent.com/15157491/35109501-78392f70-fc6e-11e7-8ef3-86d491b44ee1.png)](https://materialdesignicons.com/icon/server-security)

**Comment by fxmountain** [comment]
I think it does not represent SSL

**Comment by PeterShaggyNoble** [comment]
The `lock` icon by itself is generally used to represent that (and is what Google use for [HTTPS](https://material.io/icons/#ic_https)). Renaming this as `server-lock`.

[![lock](https://user-images.githubusercontent.com/15157491/35109981-ae74e8ee-fc6f-11e7-8f16-85d48906e2d1.png)](https://materialdesignicons.com/icon/lock)
