### ISSUE TITLE
vBulletin and XenForo Icon Request

### ISSUE THREAD

**Issue by VashFiery** [Templarian/MaterialDesign#2757]
Looking for vBulletin and XenForo images to be added to this set.

![vbulletin](https://user-images.githubusercontent.com/35671079/35200101-cebdd5ba-fecd-11e7-8ecf-2093668fbcb9.jpg)

**Comment by PeterShaggyNoble** [comment]
Is vBulletin still as popular as it once was (~10+ years ago)? If it is then it may be worth adding.

XenForo, on the other hand, is probably going to be far too obscure.

**Comment by Templarian** [comment]
While these are popular they are still very niche. I'm marking these are rejected so that we can use the `brand`+`rejected` labels if we ever go back and create a "other brands" icon pack that has been discussed numerous times now.
