### ISSUE TITLE
[site] Indicator for community icons not working

### ISSUE THREAD

**Issue by nnmrts** [Templarian/MaterialDesign#2760]
When browsing the icons on materialdesignicons.com, there is this sentence in the top section:
![screenshot4](https://user-images.githubusercontent.com/20396367/35225111-add08748-ff87-11e7-9553-4ee3fb90e6b2.png)

This works as expected, as shown here:
![screenshot2](https://user-images.githubusercontent.com/20396367/35224982-48854144-ff87-11e7-8bef-729695a2cd55.png)

But after a couple of seconds it jumps to a way lighter orange:
![screenshot3](https://user-images.githubusercontent.com/20396367/35224984-48aaceb4-ff87-11e7-89d8-100e38465fc6.png)

Browser: Chromium 63.0.3239.84
OS: Linux Debian 9.3 (32-Bit)

And, to continue the discussion from #2548, there is no indicator if an icon is already released or not. In my opinion, there should be one. I don't know. A light blue border or something like that.

And then the sentence should be:
"Hello! Need some icons? Have a look below. The [orange] icons are from the community, the [blue] icons are not officially released yet."

**Comment by JamesCoyle** [comment]
All work is now focused on the new site and non-breaking issues on the current site will likely not be worked on.
