### ISSUE TITLE
Decision

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2762]
An app I'm working on I needed a `decision` icon and this is what I came up with. Thoughts?

![image](https://user-images.githubusercontent.com/4528551/35249717-4227b47c-ff90-11e7-9be1-67425b9ac3bc.png)

[decision.zip](https://github.com/Templarian/MaterialDesign/files/1653922/decision.zip)

**Comment by GreenTurtwig** [comment]
I'd remove the circle at the bottom to make it less similar in style to the Git icons.  
Like:
[![](https://materialdesignicons.com/icon/call-merge)](https://materialdesignicons.com/icon/call-merge)

**Comment by MrGrigri** [comment]
I debated that, but I kept it because I wanted to represent an origin and a decision.

**Comment by PeterShaggyNoble** [comment]
Would a filled circle suffice to differentiate it from the Git icons?

**Comment by MrGrigri** [comment]
Thanks @PeterShaggyNoble, that looks better. Here are the two that I'm using. One for an auto decision and the other is for a manual decision. Again, we don't have to include them...just thought that the community could use them.

![image](https://user-images.githubusercontent.com/4528551/35358424-d3fc0b1c-0113-11e8-8b46-1ed9e0700159.png) ![image](https://user-images.githubusercontent.com/4528551/35358398-c6612e42-0113-11e8-83c0-53126567d9f9.png)

[decision.zip](https://github.com/Templarian/MaterialDesign/files/1661764/decision.zip)

**Comment by GreenTurtwig** [comment]
Yeah, that definitely looks better.  
And yeah, as you stated, auto might be too specific.

**Comment by Templarian** [comment]
[![arrow-decision](https://materialdesignicons.com/icon/arrow-decision)](https://materialdesignicons.com/icon/arrow-decision) [![arrow-decision-outline](https://materialdesignicons.com/icon/arrow-decision-outline)](https://materialdesignicons.com/icon/arrow-decision-outline) [![arrow-decision-auto](https://materialdesignicons.com/icon/arrow-decision-auto)](https://materialdesignicons.com/icon/arrow-decision-auto) [![arrow-decision-auto-outline](https://materialdesignicons.com/icon/arrow-decision-auto-outline)](https://materialdesignicons.com/icon/arrow-decision-auto-outline)
