### ISSUE TITLE
CAD

### ISSUE THREAD

**Issue by esamk** [Templarian/MaterialDesign#2764]
An icon for generic CAD-files.
A CAD icon would be useful for example in directory/folder/content listings everywhere.
CAD icon could be, for example, the MathCompass icon superimposed on the File icon.

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/35287618-a3cabcb8-005a-11e8-9393-ab521f66c0f6.png)![](https://user-images.githubusercontent.com/15905797/35287643-b7c70b04-005a-11e8-9f99-f88a77462ed2.png)
[file-cad.zip](https://github.com/Templarian/MaterialDesign/files/1656754/file-cad.zip)

**Comment by esamk** [comment]
That's exactly what I had in my mind. 
And look at the speed... I mean a few hours after my request it is all done.
GreebTurtwig, Awesome! You're the man!

**Comment by MrGrigri** [comment]
Remember that that is still a 'Work in Progress'. This issue will be closed once it's added to this repository.

**Comment by esamk** [comment]
MrGrigri, 

Sure. I was just amazed things happened so quickly.  It's not a norm, I can assure you :)

**Comment by esamk** [comment]
GreenTurtwig

Do you think it would be possible to have both outlined (your draft) and filled versions of these icons?
Sorry, I didn't put this in my original request, but it just dawned on me.

**Comment by GreenTurtwig** [comment]
I was stupid and totally forgot we already had the `android-studio` icon so I've redone the icons with the current `android-studio` icon.
[file-cad.zip](https://github.com/Templarian/MaterialDesign/files/1663847/file-cad.zip)
  
@esamk Unfortunately it won't be possible to make outlined variants, there just isn't enough space and detail will be lost.

**Comment by goyney** [comment]
Added! 😄
