### ISSUE TITLE
math-compass redesign

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2765]
Wasn't a fan of the current `math-compass` icon, so decided to create one from scratch based off the Android Studio logo.

[![](https://materialdesignicons.com/icon/math-compass)](https://materialdesignicons.com/icon/math-compass)[![](https://user-images.githubusercontent.com/15905797/35285197-a9ebb742-0054-11e8-882e-08956073437b.png)](https://github.com/Templarian/MaterialDesign/files/1656600/math-compass.zip)

**Comment by MrGrigri** [comment]
I would like to see them both, as they are both used differently. The one we have now is more of a scribe compass and the other is a locking compass.

**Comment by PeterShaggyNoble** [comment]
I don't know that's it's different enough from our existing `android-studio` icon to warrant including it separately.

**Comment by GreenTurtwig** [comment]
Yep, I'm stupid. I didn't search for some reason and @Templarian totally forgot he designed one. :-P  
  
[![](https://materialdesignicons.com/icon/android-studio)](https://materialdesignicons.com/icon/android-studio)

**Comment by GreenTurtwig** [comment]
Added alias `math-compass-variant`.
