### ISSUE TITLE
window-shutter

### ISSUE THREAD

**Issue by thijsdejong** [Templarian/MaterialDesign#2766]
Hey there,

Would love to have an Icon specifically for window shutter for use in Home Assistant. Kind of like a mix between garage and window icon.

```window-shutter-open```
```window-shutter-closed```

Kind regards!

**Comment by PeterShaggyNoble** [comment]
Would `blinds` suit your needs, or serve as a stopgap, at least?

[![blinds](https://user-images.githubusercontent.com/15157491/35342956-560798a8-0121-11e8-8847-4848eaf0eec8.png)](https://materialdesignicons.com/icon/blinds)

**Comment by bakedraccoon** [comment]
Hey there,

Unfortunately, no. They are these things:
![image](https://user-images.githubusercontent.com/25135566/35343096-07fa8b62-012a-11e8-99a3-90a7ba5ee90c.png)

Therefore I would say that is not really a valid option.

Kind regards

**Comment by idevo89** [comment]
In line with `garage`

![image](https://user-images.githubusercontent.com/48392636/55836366-98126680-5b1e-11e9-9187-f687d52a4e18.png)![image](https://user-images.githubusercontent.com/48392636/55836437-cb54f580-5b1e-11e9-8a29-6c6399ec435f.png)
![image](https://user-images.githubusercontent.com/48392636/55836509-f9d2d080-5b1e-11e9-8f14-68ba28f93f88.png)
[window-shutter.zip](https://github.com/Templarian/MaterialDesign/files/3061045/window-shutter.zip)

**Comment by goyney** [comment]
[![window-shutter](https://materialdesignicons.com/icon/window-shutter)](https://materialdesignicons.com/icon/window-shutter)[![window-shutter-open](https://materialdesignicons.com/icon/window-shutter-open)](https://materialdesignicons.com/icon/window-shutter-open)[![window-shutter-alert](https://materialdesignicons.com/icon/window-shutter-alert)](https://materialdesignicons.com/icon/window-shutter-alert)
