### ISSUE TITLE
jquery logo

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#2767]
Might be useful to have this since we have all the other icons. Useful in resumes and job posting screens listing skills or pages showing supported libraries/integrations.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/35446639-93c9fabc-0272-11e8-9546-259b23a60e2e.png)

[jquery.zip](https://github.com/Templarian/MaterialDesign/files/1668188/jquery.zip)

**Comment by PeterShaggyNoble** [comment]
@MrGrigri, they themselves use the icon without the typography.

**Comment by Templarian** [comment]
[![jquery](https://materialdesignicons.com/icon/jquery)](https://materialdesignicons.com/icon/jquery)

**Comment by MrGrigri** [comment]
I believe you attributed this one to yourself by accident. ;)
