### ISSUE TITLE
Old man

### ISSUE THREAD

**Issue by jabrera** [Templarian/MaterialDesign#2769]
Hi,

It would be awesome to add human-old icon. Something like [this](data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBwgHBgkIBwgKCgkLDRYPDQwMDRsUFRAWIB0iIiAdHx8kKDQsJCYxJx8fLT0tMTU3Ojo6Iys/RD84QzQ5OjcBCgoKDQwNGg8PGjclHyU3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3Nzc3N//AABEIAHgAeAMBIgACEQEDEQH/xAAcAAACAgMBAQAAAAAAAAAAAAAAAQIIBQYHBAP/xABFEAABAQYEAwUEBgYJBQAAAAABAgADBBEhMQUSQVEGB2ETIjKBoRRCYnFSgpGys8EIFTM1N7EjVGNyg5KTwuEWJDQ2U//EABQBAQAAAAAAAAAAAAAAAAAAAAD/xAAUEQEAAAAAAAAAAAAAAAAAAAAA/9oADAMBAAIRAxEAPwDt5MqmzLNK/kwqhn6NGwrUH0YJZj9Zgk2F9WjL3ZzP0tmL0sRruwSzTsKC7GcXPh3aNCJ2A03YmPFLyYJZjqKmzeXE8ShMKgH0diUQiGh3Kczx68MgB+daSuS3ooBpW3RuHfpG4u/TEYVgyVHsMiol4PpqnlTP5SV9rB7sW59wjmJKMJwR9EOQSO1iH4dFXUJALbNwRzXwbimLRAPHbzD4954HT5QKXh2SrfoQOk2rD69Gk7eKdLC3ailaSClaTIpIsQWC7ebU20YmRe5s2F4NxR7jPCmFYnEyL6JhUKeSFCuXeI85tmLUNZ67MEsxt7zGadri7KVcuv0mV+kvVgmDO1mGSamYp0ZMDUZGl2iNctzfo0lXkKHdoitqSvW7Ad3LIfs92DUDNbRiYInIy2YsJmqTpswO573i0YrOY8WzK1DU6NF68Q5drW8eJdpQkqW8WZBIFyejBIWOXzbkvP7haIxLDYXHcPdF6qASpEQhImeyJnmHRJnPoZ6NgeMudkd+sVw3CiHLqDQZe0vnWZb07gGgHzE/k2e5X814jiDFXeC4+6dJinoPs8Q4TlS8IEylSdDIUIowV+I1Gre/A8HjsdxRxhmFuS+iX6pAaJGqidALktZ7FOWnB2KRJiYrBXKXiySTDvFugfmEEDzbMYBwzgvDjpTnBsOcQpWAFLQJrWBbMozJ8ywffAcMd4LgsDhkOorTCOEOcxHiyiU/M182yA+GxuyloPFqd2L1Fhet2AkJS9zRi8s31aMTpmI7uzFvFWdq2YJJ8VfFswwmhkalhgFVIFg0bitALUu0l2mrw6tEzl3p9GB1Jn72zFqi502YrOviZVnIeLVgKAEDwm52bj3P/ixcHCOeGoF4QuJT2sWpJr2c+6jzIJPQdW7CK+Gcp1ao/MTE1YtxxjUUTQRS3TuvuIORPokMGues/RvpDxD6FiHT+FeqdPnSwt29QZKSoVBB0aCUqWoJdpJUTLKLktunMDl1iPBrqEiVqMTBP3aAt6kfsn0u8k9JzkWDtfK3mA44vw8w8WpDvGYdH9O7AkHqbdokbbjQ/MNvdhlHh32al+E4jF4PiMPiOHvlOIqHXndPE6H8wRQjUGTWn5fcaQfGWD9u6yuoxyAIuFnVCtxuk6Hy0YNpMiJGg3YvU0IsN2CRlmfDowZgjNc2YCxzVzbMWtWd+jGsh492epy395gaaGQqN2GEfD4WTA1Urc7NGgtIz02aSr93xMv7s56sC1y+rFxKgA13YEpU8DBt3phOjAxU7SlRqYY2SrGY8m5iXkz9Ytc8XGa86Sal+NfviPnb2l594sHo4WAVxNg4UKGOcA9e+Gt9ieHwmKwL/D8QcpfwsQkoeJXqD/I7HRqg8K/+0YNP+vOJf6ga5B1+gwVQ5i8DxnBeLdkrO/w5+SYSJI8Q+iqXvD1v8sPwxj8fwzjTjFMMeZXroyUk+F4jVChqD/zcNbTiLBIHiLCH+GYq67SGfCQl4kK0UDooaNVrjLgvFuEsRfQ8c4eLhQr+ijEOz2b1OlbA7g2+wsFneEeJYHivBXWKYcaK7r1yTNTleqT9vmCC2akBQVBF9m5fyAwWLw3hiKjogZUYi9S8cIJ9xIlmO0zP7G6iPhtqwL4Z6+Ji+wA9WKS/s2Z+LyYGmpmaHZkzTfvSzMMArax3aN6Ckr9WkrrZo3vSVmB6TApsysJmoOmzFbkd7QM7VTVWrACkga/k1L8ZpjMeT/WXn3i10E0Mk1GvRqX41++Y8i/tLz7xYPRwqJcUYMTrHuPvpa5E6z0nZqSIUUKCkKIUDOYMiC1reWHFQ4s4Wh4t4sKxBxJxFJ+MDxfWFftGjBttpUBBt0bR+dlOWmLA1OZx+Mht5tUVOraLzspy0xYJtmcfjIYMjyvry+wECh9kFfMttFDWgAuN21flhXl9gIVb2RP8y20Xqq4sGA+Iin0WLDcG1bM63l3tmQp4a79GCSaGRqd2GEXkDNO7Jga9zbZl86zszVQz12aM5dZ36MBWx8WhYvQeLU7sfDOY3YuJGg33YGK+G2oal+M/vmOlQ+0vPvFroCpmaEUk1LsZObF47b2l5X6xYPIKinm27cpOLP8Apbil2qIehGHRsnETM0RXurP9036Et6OFeFDxHy4xyJhXQViGHRSXzrKO8tGTvo+yoG4G7aD130YLt38NDr1bR+dn8NMWKaDM4/GQz5OY49x7gWEXFPM8RBqVCvFTqrLLLPrlKfm0edteWmLE0OZxT/GQwZHlfTl9gOao9lEh5ltpt4qnRtW5X05fYCRU+yCnmW2i1BUHXZgNZe9uxe2l6sS93T6TFCBOQlbqwSTWotsyZpqqZodmGAVel2jvlnP3mkqtLdWjcStL1YASlT9nswfi8OjGuaX1WLVvPTZg8WOxwwvBY/EHp/8AFhnj4fVST+TUx0E7NabnJGqgeXWLF3VT5LtzPYKWAfSbVZO8vJgsh+j9Aey8DvIqVYuLWs9Upkn+aS3AeJsO/VHEWJYalJSIWKeOkAmuUKOX0k1puXEB+ruBMDh8nZkQiHi0kS7y++Z+am4Vz2w32Lj5+/SkhMc4dv8AzAyH7vqwbV+jfiQzYzha1f8AziXaetUq/wBrbrzt/hri2a+Zx+MhuNcj49UFzDgnYHci3Txwv/KVD1SG7Lzspy0xYXq4r/jIYMjyv/h/gWW/siZ/KZbaBrlnLVtX5X15fYEAZf8AaCvmW2ihFgANN2ApL4GNs3kxrml9Vi3WfowSTfveJhhNDK/VhgahOhsyyk30swwwEjf3tGMpFRcsMMGPx7BYTHsHicKxBBVCxKcq5GRBnMKB3BAI+Tcrw/kLBusVS+xDGnsTApVMuEOOzWsTsVZrbyE/kwwwdjS7CEpSkBISJJAEgG1DmJy/guN4Vx2z9cJHQ0w5iEJzAA3SpOo1vP1ZMMGL5e8qYPhDEDiT+NMfHpSUuldlkQ6BoSBMzMqTm208a8OjijhmMwb2gw4iMpD3JmylKgoU1E0sMMHo4Xwb9RcPQGEdt2whHId9ply5yLmWjZTKTU3FmGGAkb6sZSLa3YYYGBKgswwwwf/Z)

**Comment by Naesstrom** [comment]
Didn't see your example in the comment above, but what about something like these?
![old-man-icon](https://user-images.githubusercontent.com/6575206/35862460-0b9d7960-0b4c-11e8-8d40-9c99d18b1032.png)![old-woman-icon](https://user-images.githubusercontent.com/6575206/35862463-0e1bde3e-0b4c-11e8-88b9-826ab4512ad5.png)
[old-people-icons.zip](https://github.com/Templarian/MaterialDesign/files/1699243/old-people-icons.zip)

**Comment by JamesCoyle** [comment]
We probably wanna use `human` as the base for this:
[![](https://materialdesignicons.com/icon/human)](https://materialdesignicons.com/icon/human)

**Comment by goyney** [comment]
[![human-cane](https://materialdesignicons.com/icon/human-cane)](https://materialdesignicons.com/icon/human-cane)
