### ISSUE TITLE
Sound note

### ISSUE THREAD

**Issue by massimo85** [Templarian/MaterialDesign#277]
It would be nice something like  this : 
https://www.google.it/search?q=music+note&tbm=isch&tbo=u&source=univ&sa=X&ei=eY4nVcrXLcagsAH51IHQBQ&ved=0CCEQsAQ&biw=1280&bih=672#imgrc=p4C3g1MEErpQvM%253A%3BqToGueEceAU3mM%3Bhttps%253A%252F%252Fcdn2.iconfinder.com%252Fdata%252Ficons%252Finverticons-stroke-vol-4%252F32%252Fmusic_note-512.png%3Bhttp%253A%252F%252Fimgarcade.com%252F1%252Fmusic-note-icon-png%252F%3B512%3B512

And also the same icon with a cross bar indicating "no sound"

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/music-note

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/music-note-off
