### ISSUE TITLE
Customs icon

### ISSUE THREAD

**Issue by Doeke** [Templarian/MaterialDesign#2770]
I don't think there's anything like that yet, here's an example:

![image](https://user-images.githubusercontent.com/240530/35334493-e5753c0c-0112-11e8-9a67-65328875c704.png)

**Comment by MrGrigri** [comment]
Would [passport](https://materialdesignicons.com/icon/passport) work?

![passport](https://materialdesignicons.com/icon/passport)

**Comment by Doeke** [comment]
My use case is for customs clearance of cargo, I don't think passport fits.

Alternatively a stamp icon might work for my use case, something like this but filled

![image](https://user-images.githubusercontent.com/240530/35394475-28338bfe-01e8-11e8-8632-addbf49bd848.png)

**Comment by MrGrigri** [comment]
The stamp request would be a duplicate of #621.

**Comment by PeterShaggyNoble** [comment]
Closing as a dupe of #621, which now includes a contribution.
