### ISSUE TITLE
Light chain

### ISSUE THREAD

**Issue by naofireblade** [Templarian/MaterialDesign#2772]
An icon for a light chain would be nice :) 

![image](https://user-images.githubusercontent.com/12081369/35352428-29a4ef18-0144-11e8-9405-196a7a43e6a4.png)

**Comment by uwap** [comment]
I would love to see them in mdi

**Comment by PeterShaggyNoble** [comment]
@uwap, you can help bump this request up on our list of priorities by giving the original request a 👍.

**Comment by hulkhaugen** [comment]
This might be pushing the guidelines, but this is what I was able to pull off:

![image](https://user-images.githubusercontent.com/1409758/55680210-f10fae00-5916-11e9-8dbb-636e3f1129b7.png)

This and a few more are available at: https://github.com/hulkhaugen/hass-bha-icons, i'm hoping for them to be included in MDI eventually.

**Comment by goyney** [comment]
These were added in a previous issue:
[![string-lights](https://materialdesignicons.com/icon/string-lights)](https://materialdesignicons.com/icon/string-lights)
