### ISSUE TITLE
Gauge speed/level

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2774]
Levels for the `gauge` icon, also edited the original as it was a little off:
![](https://user-images.githubusercontent.com/15905797/35395249-c4ea6fa0-01e1-11e8-8df4-8a387458abd3.png)

![](https://user-images.githubusercontent.com/15905797/35395001-11fb4090-01e1-11e8-9684-32144fe4ca9b.png)![](https://user-images.githubusercontent.com/15905797/35395085-43c9ee3c-01e1-11e8-93a4-30ab2ea7349f.png)![](https://user-images.githubusercontent.com/15905797/35395103-56db20fe-01e1-11e8-8b96-e2fe0b1358ca.png)![](https://user-images.githubusercontent.com/15905797/35395127-676ee8ce-01e1-11e8-9d7b-fb5e77269ee3.png)

[gauge.zip](https://github.com/Templarian/MaterialDesign/files/1664438/gauge.zip)

**Comment by Templarian** [comment]
What about `gauge-empty`, `gauge-full`, `gauge-low` for the new 3 icons.

I'm not a fan of the numbering.

**Comment by MrGrigri** [comment]
`gauge-empty`, `gauge-low`, `gauge-half`, and `gauge-full` because there are four.

**Comment by GreenTurtwig** [comment]
I agree with all of them apart from `gauge-half` (as the needle doesn't point halfway), however much it will drive my crazy having just a `gauge` icon.

**Comment by Templarian** [comment]
[![gauge](https://materialdesignicons.com/icon/gauge)](https://materialdesignicons.com/icon/gauge) [![gauge-empty](https://materialdesignicons.com/icon/gauge-empty)](https://materialdesignicons.com/icon/gauge-empty) [![gauge-low](https://materialdesignicons.com/icon/gauge-low)](https://materialdesignicons.com/icon/gauge-low) [![gauge-full](https://materialdesignicons.com/icon/gauge-full)](https://materialdesignicons.com/icon/gauge-full)
