### ISSUE TITLE
Fix size attribute name for Polymer iron-iconset-svg

### ISSUE THREAD

**Issue by c727** [Templarian/MaterialDesign#2778]
iron-iconset-svg uses `size="24"` instead of `iconSize="24`

```xml
<iron-iconset-svg name="my-svg-icons" size="24">
  <svg>
    <defs>
      <g id="shape">
        <rect x="12" y="0" width="12" height="24" />
        <circle cx="12" cy="12" r="12" />
      </g>
    </defs>
  </svg>
</iron-iconset-svg>
```
linkt to file:
http://materialdesignicons.com/api/download/polymer/v1/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B
reference:
https://www.webcomponents.org/element/PolymerElements/iron-iconset-svg

**Comment by balloob** [comment]
@Templarian where is the source for the polymer elements generator so we can issue a PR?

**Comment by Templarian** [comment]
@balloob Sorry, will fix this tonight. Unfortunately until v2 of the site goes live the current endpoints are not open source.

Never feel like you're annoying us, if we seem to be ignoring something it is probably because it slipped by. Just comment and it will get the teams attention.

**Comment by c727** [comment]
It's not critical as 24px is the default size all in all, I only noticed it while I was playing around with iconsets :smile:

**Comment by Templarian** [comment]
This has been fixed. Sorry it took so long, hopefully with the new site going open source these things will be solved much quicker. 😸
