### ISSUE TITLE
Typo on the Contribute website

### ISSUE THREAD

**Issue by TefiC** [Templarian/MaterialDesign#2780]
Hi! There is a typo on the https://materialdesignicons.com/contribute website.

- On the box at the top right corner of the screen, where it says **Not a Designer?**, suggestions is written as _suggetions_.

**Comment by MrGrigri** [comment]
For reference:

![image](https://user-images.githubusercontent.com/4528551/35530747-383b2b8a-04f2-11e8-9f48-aba30dda448e.png)

**Comment by Templarian** [comment]
Fixed. Might be cached for a bit.
