### ISSUE TITLE
level-down

### ISSUE THREAD

**Issue by tomsihap** [Templarian/MaterialDesign#2781]
A level-down icon could be useful when dealing with file trees interfaces.

![fa-leveldown from fontawesome.io](https://user-images.githubusercontent.com/6191094/35618903-a1730fa6-067c-11e8-8fe8-e0c837305b16.PNG)

**Comment by 0x4C4A** [comment]
Isn't [subdirectory-arrow-right ![image](https://user-images.githubusercontent.com/8605099/35629254-c9a3766c-06a6-11e8-9118-0f9520d71b69.png)](https://materialdesignicons.com/icon/subdirectory-arrow-right) and [subdirectory-arrow-left  ![image](https://user-images.githubusercontent.com/8605099/35629219-b8c35c18-06a6-11e8-945c-e39d880e1ce3.png)](https://materialdesignicons.com/icon/subdirectory-arrow-left) pretty much what you're looking for? Remember, you can rotate and/or flip these icons too - https://materialdesignicons.com/getting-started

**Comment by tomsihap** [comment]
They definitely are! I've looked for "level", "down", I didn't think searching for "arrow".
