### ISSUE TITLE
Mouse scroll(wheel)

### ISSUE THREAD

**Issue by 0x4C4A** [Templarian/MaterialDesign#2782]
An icon to depict scrolling with three variations - 
- Up
- Down
- Both (as pictured in the example)

![image](https://user-images.githubusercontent.com/8605099/35627663-47321426-06a2-11e8-8be8-0ce8c19ba7f9.png)

**Comment by goyney** [comment]
Maybe related: #2272.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/63068160-26896100-bee0-11e9-8b69-dfbe8dd1239f.png)
![image](https://user-images.githubusercontent.com/1015040/63068175-2e490580-bee0-11e9-9d51-0c0c52fc7f91.png)
![image](https://user-images.githubusercontent.com/1015040/63068187-3608aa00-bee0-11e9-8b19-eaf7b6773d71.png)

[mouse-scroll.zip](https://github.com/Templarian/MaterialDesign/files/3504056/mouse-scroll.zip)

**Comment by JapanYoshi** [comment]
Doesn't really convey the “scroll” part IMO. I'd interpret these as moving the whole mouse up and down.

**Comment by goyney** [comment]
[![mouse-move-vertical](https://materialdesignicons.com/icon/mouse-move-vertical)](https://materialdesignicons.com/icon/mouse-move-vertical)
[![mouse-move-up](https://materialdesignicons.com/icon/mouse-move-up)](https://materialdesignicons.com/icon/mouse-move-up)[![mouse-move-down](https://materialdesignicons.com/icon/mouse-move-down)](https://materialdesignicons.com/icon/mouse-move-down)
