### ISSUE TITLE
Additional Gesture Icons

### ISSUE THREAD

**Issue by 0x4C4A** [Templarian/MaterialDesign#2783]
Since the pack already contains very similiar icons, I wanted to suggest adding the following versions:

- Swipe vertically: Would be a combination of gesture-swipe-up + gesture-swipe-down (should have a vertical arrow with points on both ends)
![gesture-swipe-up](https://user-images.githubusercontent.com/8605099/35628203-d4a16c48-06a3-11e8-8103-d7aeeb6c1c41.png) 
![gesture-swipe-down](https://user-images.githubusercontent.com/8605099/35628199-d29a61e8-06a3-11e8-9361-d1bb6026034d.png)

- Swipe horizontally: Would be a combination of gesture-swipe-left + gesture-swipe-right (should have a horizontal arrow with points on both ends)
![image](https://user-images.githubusercontent.com/8605099/35628080-7b59c90a-06a3-11e8-89c2-c04b3cc72f72.png)
![image](https://user-images.githubusercontent.com/8605099/35628090-80ec4000-06a3-11e8-892f-16790b245f48.png)

- Swipe vertically - two finger variant:
Same as vertically but with the gesture-two-tap hand as base.
![gesture-two-tap](https://user-images.githubusercontent.com/8605099/35628269-06e334a2-06a4-11e8-9ba6-147ef731fe00.png)

- Swipe horizontally - two finger variant:
Same as two-tap vertical swipe, only with accordingly rotated arrow.

- Pinch fingers
Could take the gesture-tap as base and add the circles around the index finger & thumb and add icons to depict finger movement together. 
![image](https://user-images.githubusercontent.com/8605099/35628419-87981c20-06a4-11e8-8515-b13222cdc04d.png)
Something similiar to this:
![image](https://user-images.githubusercontent.com/8605099/35628397-738e73dc-06a4-11e8-82f6-1997fe7aca0a.png)

- Spread fingers
Similiar to pinch, only arrows in opposite direction.

**Comment by PeterShaggyNoble** [comment]
The first 4 `gesture-swipe-<direction>` icons exist already.

**Comment by 0x4C4A** [comment]
Seems I didn't express my intent clearly enough.
I referenced the existing icons because I need a combination that shows swiping in both directions (i.e. the icons should have an arrow pointing in both directions similiar to: ![image](https://user-images.githubusercontent.com/8605099/35629479-681f47ee-06a7-11e8-95f3-5b6614dedf81.png)).

**Comment by MrGrigri** [comment]
You have to remember that you are working with a 24x24 max size and it starts to get really difficult designing a recognizable hand and gestures at that size.

**Comment by JamesCoyle** [comment]
It should be possible to combine the arrows in the first four.

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/35685226-026e9b2e-0761-11e8-9d3a-46037ad89f53.png)![](https://user-images.githubusercontent.com/15905797/35685244-0da2bc3c-0761-11e8-87ca-c8b8a033842a.png)
[gesture-swipe.zip](https://github.com/Templarian/MaterialDesign/files/1685981/gesture-swipe.zip) ?

**Comment by MrGrigri** [comment]
I thought he wanted a pinching and spreading gestures?

**Comment by JamesCoyle** [comment]
Rotating gesture-tap by 30 degrees or so (some angle which works with pixel grid) and adding the circle to the thumb is a good idea for pinch gestures. Could try fit in a diagonal dual arrow in one of the corners too.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/35741658-a4bae614-07f5-11e8-9210-c1d4580ae544.png) ![image](https://user-images.githubusercontent.com/4528551/35741708-b2588d30-07f5-11e8-916b-8076bfa0b1ba.png)

[gesture-2.zip](https://github.com/Templarian/MaterialDesign/files/1689903/gesture-2.zip)

**Comment by 0x4C4A** [comment]
Looks pretty good, but maybe rotate the arrows to 45 degrees? Might be a bit more clear that way.

**Comment by Templarian** [comment]
[![gesture-swipe-horizontal](https://materialdesignicons.com/icon/gesture-swipe-horizontal)](https://materialdesignicons.com/icon/gesture-swipe-horizontal) [![gesture-swipe-vertical](https://materialdesignicons.com/icon/gesture-swipe-vertical)](https://materialdesignicons.com/icon/gesture-swipe-vertical)

**Comment by Templarian** [comment]
Diagonal is going to look odd, I think most will understand the pinch/spread from the arrows being up/down.

[![gesture-spread](https://materialdesignicons.com/icon/gesture-spread)](https://materialdesignicons.com/icon/gesture-spread) [![gesture-pinch](https://materialdesignicons.com/icon/gesture-pinch)](https://materialdesignicons.com/icon/gesture-pinch)
