### ISSUE TITLE
Create Custom Icon on materialdesignicons.com not working

### ISSUE THREAD

**Issue by JanRueger** [Templarian/MaterialDesign#2784]
Sorry, I don't really know if this is the right place to post this issue, but didn't find any more suitable place to do so.

When I tried to create a custom icon, I ran into an issue that can most easily be describaed as "lack of response". I tried this on four different computers and on Chrome, Firefox and Edge as browsers. What I couldn't do is switch to another network to see if any network settings are blocking this, but our firm is pretty lenient on internet restrictions so I don't think this might be a problem.

When I try to drag/drop or select an svg to convert to an icon by clicking the "import SVG icon" button, the site used to show the resulting icon#s preview on the left while it displayed the name in the textbox on the right. All it does now is change the mouse cursor to "cannot click", which presumably means the import process fails.

So, the steps to reproduce the error would be:
- download any icon from the material design page (eg account.svg) as an svg
- switch to the custom page
- under "custom icon export", click the button "import SVG icon" and select the downloaded icon
result: no productive reaction from the site

Thanks in advance,
Jan

**Comment by Templarian** [comment]
This is the right place. The upload button is broken. I'll need to put a quick fix in for this once I get a moment. Thanks for reporting the bug.

**Comment by Templarian** [comment]
Sorry for the huge delay. This has been fixed.
