### ISSUE TITLE
bill icon

### ISSUE THREAD

**Issue by gatity** [Templarian/MaterialDesign#2785]
hi please create bill icon

**Comment by Templarian** [comment]
Do you mean like. the `cash` icons? ...

[![cash](https://materialdesignicons.com/icon/cash)](https://materialdesignicons.com/icon/cash) [![cash-multiple](https://materialdesignicons.com/icon/cash-multiple)](https://materialdesignicons.com/icon/cash-multiple) [![cash-100](https://materialdesignicons.com/icon/cash-100)](https://materialdesignicons.com/icon/cash-100)

**Comment by MrGrigri** [comment]
Or do you mean `invoice`? #1010

**Comment by PeterShaggyNoble** [comment]
Or did you mean a restaurant/bar bill? `receipt` could cover that:

[![bill](https://user-images.githubusercontent.com/15157491/35908358-5341b3ac-0be8-11e8-9746-58dc57c92b0e.png)](https://materialdesignicons.com/icon/receipt)

**Comment by gatity** [comment]
tnx. i meant invoice, reciept is good for me
