### ISSUE TITLE
Greenhouse

### ISSUE THREAD

**Issue by Naesstrom** [Templarian/MaterialDesign#2788]
Suggestion for greenhouse icon: 
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/1694178/Archive.zip)
![artboard 1](https://user-images.githubusercontent.com/6575206/35792715-c177dab8-0a4e-11e8-86b2-1c4f4139252b.png)

**Comment by jhil** [comment]
## Preview

![image](https://user-images.githubusercontent.com/2228347/104681409-7eb52b80-56af-11eb-94d1-b1a38f7cf4fe.png)

A few other explorations I didn't like as much:
<img width="2203" alt="Screenshot 2021-01-14 at 21 27 50@2x" src="https://user-images.githubusercontent.com/2228347/104681457-9d1b2700-56af-11eb-8e85-5791e526a0d4.png">


## Zip Download

[greenhouse.zip](https://github.com/Templarian/MaterialDesign/files/5818432/greenhouse.zip)

**Comment by Templarian** [comment]
I like the one you suggested, but the 3rd one in the bottom might be a little better. When I picture a green house it often has that look.

I'm just thinking the first one sort of looks like a tent with the center line.

**Comment by goyney** [comment]
[![greenhouse](https://materialdesignicons.com/icon/greenhouse)](https://materialdesignicons.com/icon/greenhouse)

**Comment by jhil** [comment]
Thanks for adding this! Can the `Agriculture` tag be used as well?
