### ISSUE TITLE
Wine-related icons

### ISSUE THREAD

**Issue by MaridProject** [Templarian/MaterialDesign#2790]
Please create winery, wine cellar, wine rack, wine bottle (etc.) icons. I think it would be great for some kind of projects including online wine shops, winery equipment shops, restaurants, cafe, bodegas, etc.

**Comment by MrGrigri** [comment]
That seems very niche.

**Comment by Templarian** [comment]
A general icon for wine might be a good idea. Like a wine glass or something.

**Comment by MrGrigri** [comment]
We already have a `glass-flute` and `glass-tulip`. Do we want more than that?

![glass-flute](https://materialdesignicons.com/icon/glass-flute) ![glass-tulip](https://materialdesignicons.com/icon/glass-tulip)

**Comment by MrGrigri** [comment]
Here is my attempt at a `glass-wine`. I took the same stem and foot of the tulip and flute glasses. 

![image](https://user-images.githubusercontent.com/4528551/35867023-f3124ee2-0b15-11e8-89bc-b427d4ba98bd.png)

[glass-wine.zip](https://github.com/Templarian/MaterialDesign/files/1699608/glass-wine.zip)

**Comment by JamesCoyle** [comment]
What about a glass-cocktail?

**Comment by PeterShaggyNoble** [comment]
We could do with a wine bottle, too. And there's an [app for wine](https://play.google.com/store/apps/details?id=vivino.web.app), similar to and more popular than Untappd, that we could consider adding.

@JamesCoyle:

[![martini](https://user-images.githubusercontent.com/15157491/35907921-2eb756d2-0be7-11e8-865b-e17678f421f4.png)](https://materialdesignicons.com/icon/martini)

**Comment by JamesCoyle** [comment]
Ah thought we had one somewhere.

**Comment by PeterShaggyNoble** [comment]
It's aliased as `cocktail` (and `local-bar`); should we add `glass-cocktail` too?

**Comment by JamesCoyle** [comment]
Should we rename it maybe? Seems a bit weird having everything be glass-* but that one being different.

**Comment by Templarian** [comment]
@JamesCoyle I kind of agree renaming it. I used the stock name instead of following the regular naming scheme.

**Comment by Templarian** [comment]
[![glass-wine](https://materialdesignicons.com/icon/glass-wine)](https://materialdesignicons.com/icon/glass-wine)

Lets create a new issue if we want a wine bottle. I'm creating an issue to rename `martini` (it's overally specific for that icon).
