### ISSUE TITLE
clipboard-pulse

### ISSUE THREAD

**Issue by koystinen** [Templarian/MaterialDesign#2792]
Very simple: Take standard clipboard icon and add standard pulse to make new one clipboard-pulse :-)

in another words: it is just like clipboard-plus, but with pulse instead of plus.

**Comment by CoDEmanX** [comment]
I created one a while ago:

https://github.com/Templarian/MaterialDesign/issues/873#issuecomment-208050697

**Comment by koystinen** [comment]
@CoDEmanX this is almost what have in mind, however to match the theme of clipboard icons in material theme, the clipboard should stay of the solid color, and pulse be transparent in it so that i can be exported to black/white themes.  (See current clipboard-check, clipboard-alert)
Your icon is more... clipboard-outline-pulse :-)

**Comment by Templarian** [comment]
I think we would be fine having both variants. I'll inverse it before uploading `clipboard-pulse` and `clipboard-pulse-outline`.

**Comment by Templarian** [comment]
[![clipboard-pulse](https://materialdesignicons.com/icon/clipboard-pulse)](https://materialdesignicons.com/icon/clipboard-pulse) [![clipboard-pulse-outline](https://materialdesignicons.com/icon/clipboard-pulse-outline)](https://materialdesignicons.com/icon/clipboard-pulse-outline)
