### ISSUE TITLE
Help Icon :: Lifebouy Ring

### ISSUE THREAD

**Issue by Continuum81** [Templarian/MaterialDesign#2793]
It occurs to me that there isn't a clear "help" icon that is suitable when linking to a support department for example. The traditional lifebouy ring / donut would be a better fit than anything containing a question-mark from the current icon-set. The question mark icons, I feel, are more context driven help indicators, rather than an icon indicating general help.

I would suggest the icon of a lifebouy ring be created with the standard contrasted/striped pattern (it usually exists as a two-tone of red and white when shown in colour), with the optional potential of adding an encompassing string which can either be illustrated over the ring itself (creating a void) or surrounding the ring sometimes shown as 4 "ears" that loop away from the ring.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign/issues/873#issuecomment-208050697

We have it created, just need to add it.

**Comment by Templarian** [comment]
[![lifebuoy](https://materialdesignicons.com/icon/lifebuoy)](https://materialdesignicons.com/icon/lifebuoy)
