### ISSUE TITLE
Add aliases to pill

### ISSUE THREAD

**Issue by iamsarker** [Templarian/MaterialDesign#2794]
medicine

**Comment by Naesstrom** [comment]
There's already a icon named "[Pill](https://materialdesignicons.com/icon/pill)", if that works maybe they can add a tag for it

**Comment by iamsarker** [comment]
50% full fill would be better. Please tag with medicine as well as capsule.

**Comment by MrGrigri** [comment]
- [ ] Add Medicine
- [ ] Add Capsule

**Comment by PeterShaggyNoble** [comment]
The above aliases have been added.
