### ISSUE TITLE
currency-bdt (Bangladeshi-taka)

### ISSUE THREAD

**Issue by iamsarker** [Templarian/MaterialDesign#2795]
Please check this [Currency of Bangladeshi Taka](https://commons.wikimedia.org/wiki/File:Taka_(Bengali_letter).svg)
Sometimes, we have to use Font Awesome for this icon. Really, That should be help us

**Comment by MrGrigri** [comment]
Here is my attempt to make it material. @iamsarker, you are the expert to know if this is still recognizable with this materialized form.

![image](https://user-images.githubusercontent.com/4528551/35870490-07b4abe8-0b1f-11e8-9df4-88e62b5f942a.png)

[currency-bdt.zip](https://github.com/Templarian/MaterialDesign/files/1699857/currency-bdt.zip)

**Comment by iamsarker** [comment]
Thanks. Almost there, please change just bit more. Please increase the height.
![taka_ bengali_letter svg](https://user-images.githubusercontent.com/5415001/35895032-d901b84c-0bdf-11e8-8985-aa6791fd9006.png)

**Comment by Templarian** [comment]
The height is restricted by the alignment of the other currency symbols. Might need to tweak the proportion of somewhere else. It's actually already kind of taller compared to the norm.

For reference...
[![currency-chf](https://materialdesignicons.com/icon/currency-chf)](https://materialdesignicons.com/icon/currency-chf) [![currency-usd](https://materialdesignicons.com/icon/currency-usd)](https://materialdesignicons.com/icon/currency-usd)  [![currency-eur](https://materialdesignicons.com/icon/currency-eur)](https://materialdesignicons.com/icon/currency-eur)  [![currency-jpy](https://materialdesignicons.com/icon/currency-jpy)](https://materialdesignicons.com/icon/currency-jpy)

**Comment by iamsarker** [comment]
Ok. So, please tweak in these area..
![icon](https://user-images.githubusercontent.com/5415001/35895453-abdbdb66-0be1-11e8-81ba-71ac18944017.png)

**Comment by MrGrigri** [comment]
@iamsarker could you elaborate? Does the circle at the end need to be smaller? The top really shouldn't be tapered at all. I believe that will pull away from Material Design.

**Comment by iamsarker** [comment]
If so then keep it.
Thanks for your efforts.

**Comment by JamesCoyle** [comment]
Might be worth getting examples in a sans-serif font.

**Comment by Templarian** [comment]
https://en.wikipedia.org/wiki/Bangladeshi_taka The symbol here and in most of the fonts I've looked at show a the line crossing above the tail.

Once again it's not a currency many of us are familiar with and we want to get this right. _Really_ rough idea overlaying the Segoe UI font's symbol, something where the tail is below.

![image](https://user-images.githubusercontent.com/338885/35951771-767eab9a-0c42-11e8-9151-aec4fa79562c.png)

**Comment by iamsarker** [comment]
**MrGrigri**'s proposed icon is better.

**Comment by MrGrigri** [comment]
Here is my second take on the Unicode character. I went with an unconventional 1.5-pixel width.

![image](https://user-images.githubusercontent.com/4528551/35984382-8c18d7ea-0cb1-11e8-85b2-4dac27c57937.png)

![asset 5 4x](https://user-images.githubusercontent.com/4528551/35984423-a411e9cc-0cb1-11e8-9a1f-87c4cd88d7d6.png)

**Comment by Templarian** [comment]
I like the look of yours and it follows the general symbol a little nicer. Might be the preview but it looks a little off the grid. 1.5 width lines should still be anchored on one side to a point (never the center).

**Comment by MrGrigri** [comment]
Your right.

![image](https://user-images.githubusercontent.com/4528551/35984953-bc2adc52-0cb2-11e8-918b-d2617871afba.png)

[currency-bdt.zip](https://github.com/Templarian/MaterialDesign/files/1707907/currency-bdt.zip)

**Comment by Templarian** [comment]
Bottom is slightly off, but I'll tweak that myself quick before uploading.

@iamsarker What do you think?

**Comment by MrGrigri** [comment]
I updated it.

**Comment by iamsarker** [comment]
@Templarian you are right about the bottom. By the way, it's looking good.

**Comment by Templarian** [comment]
[![currency-bdt](https://materialdesignicons.com/icon/currency-bdt)](https://materialdesignicons.com/icon/currency-bdt)

Thanks everyone that worked to get this currency added. 😄

**Comment by iamsarker** [comment]
Thanks.... please aliases to 'Taka'

**Comment by Templarian** [comment]
Added the alias `taka`. 😸

**Comment by iamsarker** [comment]
you are great man..... thanks again.

**Comment by iamsarker** [comment]
One more things brother, this icon is not available at [https://pencil.evolus.vn/Downloads.html](https://pencil.evolus.vn/Downloads.html)

**Comment by Templarian** [comment]
Should be able to use the SVG files from the website now or eventually from https://github.com/Templarian/MaterialDesign-SVG once the new version is out.

**Comment by iamsarker** [comment]
ok thanks
