### ISSUE TITLE
video-2d

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#2796]
Suggestion for already existing `video-3d` icon.

**Comment by hazalozturk** [comment]
I thought this might be consistent with the other video icons. 

[video-3D.svg.zip](https://github.com/Templarian/MaterialDesign/files/1708076/video-3D.svg.zip)

**Comment by MrGrigri** [comment]
All videos are 2d. What's the point of this icon?

**Comment by Templarian** [comment]
Probably more of a toggle between the two. Could be used to switch views in a webGL view or something.

**Comment by matthew2402** [comment]
@MrGrigri Example: Videos in cinemas can be in 3D or 2D (I know this is not correct but many people distinguish like that)

**Comment by MrGrigri** [comment]
IMO, I would use the [video](https://materialdesignicons.com/icon/video) icon as the `2d` and then the `video-3d-variant` as the `3d` version.

![video](https://materialdesignicons.com/icon/video) ![video-3d-variant](https://user-images.githubusercontent.com/4528551/36264573-4dc38638-122a-11e8-8ef3-dedaebb4b16a.png)

[video-3d-variant.zip](https://github.com/Templarian/MaterialDesign/files/1728255/video-3d-variant.zip)

**Comment by Templarian** [comment]
Added. 😃
