### ISSUE TITLE
network-media

### ISSUE THREAD

**Issue by rulingspear** [Templarian/MaterialDesign#2798]
![image](https://user-images.githubusercontent.com/7701663/35978502-9d673bb2-0cee-11e8-974d-fec3e5dbb0c9.png)

Something that can indcate a media source or hub on a network

**Comment by MrGrigri** [comment]
Here you go. I called it `network-media`.

![image](https://user-images.githubusercontent.com/4528551/35986188-a159f55e-0cb5-11e8-9911-3d4c8dae1fbe.png)

[network-media.zip](https://github.com/Templarian/MaterialDesign/files/1707985/network-media.zip)

**Comment by JamesCoyle** [comment]
Can we make these play triangles equilateral?

**Comment by MrGrigri** [comment]
I took the triangle from `play-box-outline`.

**Comment by Templarian** [comment]
[![play-network](https://materialdesignicons.com/icon/play-network)](https://materialdesignicons.com/icon/play-network)

The box is part of the `network` modifier.
