### ISSUE TITLE
cashier

### ISSUE THREAD

**Issue by LuisEduNasc** [Templarian/MaterialDesign#2800]
A icon that means close a supermarket cashier

**Comment by PeterShaggyNoble** [comment]
See also #850

**Comment by LuisEduNasc** [comment]
When i need to close a cashier from a store in tehe end of the day for exemple

**Comment by Templarian** [comment]
😃 Example as in an image. Use google images and copy and paste it into the comment box. This will give us an idea. 😹

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @LuisEduNasc, if you can provide an example image of what you're looking for then we can revisit this issue.
