### ISSUE TITLE
lightbulb-group

### ISSUE THREAD

**Issue by user897943** [Templarian/MaterialDesign#2801]
to represent a group of lights for home automation

**Comment by PeterShaggyNoble** [comment]
Possible duplicate of #2772?

**Comment by rxritalin** [comment]
Im pretty sure what he is suggesting is a group of light bulb like as follows. 
I was actually going to submit this already, so Ill do so here. 

![image](https://user-images.githubusercontent.com/3268460/36351136-1bfa84d0-1473-11e8-8c8b-25b52512b2d9.png)
![image](https://user-images.githubusercontent.com/3268460/36351154-3e416cca-1473-11e8-94e8-1c62d5c0293b.png)


[Light Group.zip](https://github.com/Templarian/MaterialDesign/files/1734641/Light.Group.zip)

**Comment by user897943** [comment]
rxritalin described exactly what I mean.

**Comment by Templarian** [comment]
This needs a different design. Maybe with just two bulbs. `light-bulb-multiple`.

**Comment by goyney** [comment]
These were added in another issue with several variants (e.g. `off`, `outline`, etc.)
[![lightbulb-group](https://materialdesignicons.com/icon/lightbulb-group)](https://materialdesignicons.com/icon/lightbulb-group)
