### ISSUE TITLE
mastodon

### ISSUE THREAD

**Issue by jelv** [Templarian/MaterialDesign#2802]
Reopen of https://github.com/Templarian/MaterialDesign/issues/2073

"Can be revisited if Mastodon ever becomes more popular."

Mastodon has grown to 1.069.702 users on 1913 servers that have posted 192 million toots. [https://dashboards.mnm.social/dashboard/db/mastodon-network-overview?refresh=1h&orgId=1&from=now-7d&to=now](Source)

I think it's time to add the Mastodon icon.

**Comment by PeterShaggyNoble** [comment]
@jelv, the original issue will be reopened when Mastodon becomes popular enough. Please post your data there instead.
