### ISSUE TITLE
Wine Bottle

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2805]
Creating a separate issue for this one which was brought up in #2790

**Comment by MrGrigri** [comment]
Here is a bottle 'O wine!

![image](https://user-images.githubusercontent.com/4528551/36214190-0bce752c-1166-11e8-900f-9d607158f558.png)

[bottle-wine.zip](https://github.com/Templarian/MaterialDesign/files/1724707/bottle-wine.zip)

**Comment by Templarian** [comment]
Needs something more, to define it. Like a label square or something.

**Comment by JamesCoyle** [comment]
The bottom curves seem too rounded to me. I'd maybe go 1dp radius.

**Comment by MrGrigri** [comment]
I believe this will be an icon that needs to be in and not out of context. 

![image](https://user-images.githubusercontent.com/4528551/36217208-13d7b5be-116e-11e8-88e4-ff45fcd7cf07.png)

[bottle-wine.zip](https://github.com/Templarian/MaterialDesign/files/1724956/bottle-wine.zip)

**Comment by Templarian** [comment]
You might be right, that doesn't help too much. Solid might be the best unless someone else has ideas.

**Comment by JamesCoyle** [comment]
I was thinking more this shape:
![image](https://user-images.githubusercontent.com/10384436/36219327-e5c166fc-11ae-11e8-9154-8329d71d3920.png)

**Comment by PeterShaggyNoble** [comment]
I think @JamesCoyle's first option works best.

**Comment by MrGrigri** [comment]
Yeah, @JamesCoyle's is better. What about adding a cork line.

**Comment by JapanYoshi** [comment]
I think a non-tapered spout would be

**Comment by JapanYoshi** [comment]
I tthinrs a non-tapered spout woulr be more .ohesive to Material icons.

**Comment by Templarian** [comment]
[![bottle-wine](https://materialdesignicons.com/icon/bottle-wine)](https://materialdesignicons.com/icon/bottle-wine)
