### ISSUE TITLE
New Brand Icon: Accusoft

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#2808]
![image](https://user-images.githubusercontent.com/1015040/36130605-a244642a-103b-11e8-8332-97da28555b29.png)

[accusoft.zip](https://github.com/Templarian/MaterialDesign/files/1718378/accusoft.zip)

**Comment by Templarian** [comment]
Social Media only. Closing, we'll use the rejected label to find these when/if we build a brand database.

**Comment by goyney** [comment]
@Templarian I highly consider that, considering this is including in Font Awesome: https://fontawesome.com/icons/accusoft?style=brands

**Comment by Templarian** [comment]
[![accusoft](https://materialdesignicons.com/icon/accusoft)](https://materialdesignicons.com/icon/accusoft)
