### ISSUE TITLE
Update Account Icons for Consistency

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2809]
I think we should update the following icons to be consistent with other variants in the set, including `account-edit` and `account-settings`.

- [x] `account-check` (see Google's `how to reg` icon below)
- [ ] `account-key`
- [ ] `account-minus`
- [ ] `account-plus`
- [ ] `account-remove`
- [ ] `account-star`

And maybe `account-multiple-minus` and `account-multiple-plus` too?

![how to reg](https://user-images.githubusercontent.com/15157491/36144333-a894cc7e-10a5-11e8-80f7-488fa722bfba.png)

**Comment by goyney** [comment]
@PeterShaggyNoble Do we still need to do this? I see you added the `Consider Closing` tag a while back.

**Comment by PeterShaggyNoble** [comment]
I added the `Consider Closing` label to this as it conflicted with the changes in #3694.

If we're going to keep the modifiers to the left, rater than bottom right then this one can be closed.

**Comment by goyney** [comment]
Looks like we're keeping the account modifiers to the left, so closing this one.
