### ISSUE TITLE
Go-kart icons

### ISSUE THREAD

**Issue by Filipews** [Templarian/MaterialDesign#281]
Yes, I am talking about the small four-wheeled vehicle! =)
- [x] Go-kart icon
- [x] Go-kart track icon
- [ ] Go-kart mechanical issue flag*

*its usually a black flag with a white cicle in it

**Comment by MrGrigri** [comment]
I believe that `go-kart-flag` is a little too niche for this project.

![image](https://user-images.githubusercontent.com/4528551/49116460-ddfb1c00-f25a-11e8-9e6a-02a76bad03e4.png) ![image](https://user-images.githubusercontent.com/4528551/49116482-ece1ce80-f25a-11e8-894d-0c93a023308f.png)

---

[go-kart.zip](https://github.com/Templarian/MaterialDesign/files/2622117/go-kart.zip)

**Comment by Templarian** [comment]
Added the two. Agreed a regular `flag-checkered` should should be fine for this.
