### ISSUE TITLE
Anvil

### ISSUE THREAD

**Issue by sjeakins** [Templarian/MaterialDesign#2810]

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/36642736-d5f00344-1a11-11e8-9748-2eb80201e341.png)

[icon.zip](https://github.com/Templarian/MaterialDesign/files/1756166/icon.zip)

**Comment by Templarian** [comment]
[![anvil](https://materialdesignicons.com/icon/anvil)](https://materialdesignicons.com/icon/anvil)
