### ISSUE TITLE
electrical-kilowatt

### ISSUE THREAD

**Issue by EXTRAMINER** [Templarian/MaterialDesign#2815]
I need an icon for the energy something like a `kWh `for kilowatt per hour
Thank you

**Comment by EXTRAMINER** [comment]
Here's an icon that I've made

[kWh.zip](https://github.com/Templarian/MaterialDesign/files/1725662/kWh.zip)

**Comment by EXTRAMINER** [comment]
How can I upload my icon, or I must wait the admin?

**Comment by MrGrigri** [comment]
These icons will not be added at this moment. If you are just wanting a single letter, please use a font for that. Electrical symbols are very complicated, there are dozens of them, and are too niche for this icon project. This issue will be closed but could reopen if we find a better solution.
