### ISSUE TITLE
electrical-ampere

### ISSUE THREAD

**Issue by EXTRAMINER** [Templarian/MaterialDesign#2816]
I need an icon for the current something like `A` for ampere
Thank you

**Comment by EXTRAMINER** [comment]
Here's an icon that I've made

[A.zip](https://github.com/Templarian/MaterialDesign/files/1725660/A.zip)

**Comment by EXTRAMINER** [comment]
How can I upload my icon, or I must wait the admin?

**Comment by Templarian** [comment]
No reason to post in every issue (the team gets a notification in slack). We'll get around to these shortly after the team has verified each icon (contribution label will be added after that).

**Comment by EXTRAMINER** [comment]
Ah ok, thank you very much and sorry. I am newbie and I don't know how GitHub works, sorry again, I will wait,do you know how many time it need?

**Comment by MrGrigri** [comment]
These icons will not be added at this moment. If you are just wanting a single letter, please use a font for that. Electrical symbols are very complicated, there are dozens of them, and are too niche for this icon project. This issue will be closed but could reopen if we find a better solution.
