### ISSUE TITLE
spin-reverse

### ISSUE THREAD

**Issue by infanf** [Templarian/MaterialDesign#2818]
I just ran into this issue when using mdi-spin with the sync icon. The arrows point counterclockwise but it spins clockwise.
It would be great if this could be added to the CSS:

```
.mdi-spin-reverse:before {
    -webkit-animation: mdi-spin-reverse 2s infinite linear;
    animation: mdi-spin-reverse 2s infinite linear;
}

@-webkit-keyframes mdi-spin-reverse {
    0% {
        -webkit-transform: rotate(359deg);
        transform: rotate(359deg);
    }
    100% {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg);
    }
}

@keyframes mdi-spin-reverse {
    0% {
        -webkit-transform: rotate(359deg);
        transform: rotate(359deg);
    }
    100% {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg);
    }
}
```

**Comment by Templarian** [comment]
Almost every icon is setup to spin clockwise. Adding a reverse spin seems a tad underused. If someone needs it I would say they could just write their own solution.

I'm not against putting this in the documentation.

**Comment by PeterShaggyNoble** [comment]
In this specific instance, an alternative would be to use the `autorenew` icon instead.

![autorenew](https://user-images.githubusercontent.com/15157491/51996541-e1a25d80-24ac-11e9-95e1-bdfd1e07e34f.png)

**Comment by JamesCoyle** [comment]
Closing this out as the solution is trivial to implement and we are no longer recommending the icon font for web use.
