### ISSUE TITLE
Touch gesture icons

### ISSUE THREAD

**Issue by jjoseba** [Templarian/MaterialDesign#282]
- [ ] touch-tap
- [ ] touch-double-tap
- [ ] touch-pinch
- etc

Example: ![img](http://emilychang.com/blog/wp-content/uploads/2010/04/touchgesture-550x500.png)

**Comment by Templarian** [comment]
I'm 99% sure these won't look right at 24x24 and thus wouldn't fit into the icon set.

**Comment by MrGrigri** [comment]
Closing this issue out. Reference [#1798](https://github.com/Templarian/MaterialDesign/issues/1798#event-935666593)
