### ISSUE TITLE
piston

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2821]
I've been in need of a piston icon. Which one do Y'all like more?

![image](https://user-images.githubusercontent.com/4528551/36324092-8d0ba2b2-1310-11e8-9f37-889441788e22.png) ![piston-angle](https://user-images.githubusercontent.com/4528551/36324077-817a6744-1310-11e8-970b-f782714da4e1.png)

[piston.zip](https://github.com/Templarian/MaterialDesign/files/1732487/piston.zip)

**Comment by GreenTurtwig** [comment]
Definitely the first one, not a fan of the rod being angled. Also the cap shouldn't shouldn't have lines coming out of it. Out of curiosity, what would it look like having a 1px gap between the top and bottom halves of the piston?

**Comment by wardl895** [comment]
I agree with greenturtwig, the head should have lines either side to "Box" it in.... however i do like the angled design, only reason is to me the non-angled looks too much like the server-network icon :)

**Comment by MrGrigri** [comment]
Like this?

![image](https://user-images.githubusercontent.com/4528551/36346225-ca4e7734-13f7-11e8-8e60-ef1904be7ec7.png)

**Comment by GreenTurtwig** [comment]
The cap still has the lines coming off it, they don't have those. Otherwise having the gap where it was previously suits the design better. :cat2:

**Comment by MrGrigri** [comment]
![piston](https://www.google.com/search?q=piston&safe=active&rlz=1CDGOYI_enUS639US639&hl=en-US&prmd=isnv&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjg-ej5gq7ZAhUN3WMKHYDKCSsQ_AUIESgB&biw=375&bih=591#imgrc=hlHfIfoXdSrXTM:)

**Comment by MrGrigri** [comment]
Here is the SVG for the one on the right. 

[piston.zip](https://github.com/Templarian/MaterialDesign/files/1734932/piston.zip)

**Comment by Templarian** [comment]
[![piston](https://materialdesignicons.com/icon/piston)](https://materialdesignicons.com/icon/piston)
