### ISSUE TITLE
Icon-request: Patreon

### ISSUE THREAD

**Issue by Albiwalbi** [Templarian/MaterialDesign#2823]
Maybe add an icon for Patreon?

**Comment by PeterShaggyNoble** [comment]
This is a duplicate of #1294.

**Comment by Albiwalbi** [comment]
Yeah, came across that one, but it's the old logo, I was looking for an updated version :)

**Comment by Templarian** [comment]
[![patreon](https://materialdesignicons.com/icon/patreon)](https://materialdesignicons.com/icon/patreon)
