### ISSUE TITLE
All icons contributions in opened issues

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#2824]
There seems to be a lot of opened issues that have good contributions which aren't added in the repo yet. I made a python script to download all of them, I got 576 icons. I think it would be a good thing to add a few of them and close issues.

[icons.zip](https://github.com/Templarian/MaterialDesign/files/1735047/icons.zip)
[python script.zip](https://github.com/Templarian/MaterialDesign/files/1735054/python.script.zip)

**Comment by Templarian** [comment]
Yep, we're making progress on the backlog at the moment. The new site is taking some of the focus away at the moment.

We use the labels to find add icons, but thanks for the scripts.
