### ISSUE TITLE
Icon for computer vision

### ISSUE THREAD

**Issue by agustinsivoplas** [Templarian/MaterialDesign#2827]
Some Ideas:

1) https://www.xerox.com/sites/default/files/AOC_Naila_eye_machine.jpg

2) 
<img width="191" alt="screen shot 2018-02-20 at 15 37 28" src="https://user-images.githubusercontent.com/1648539/36442280-ff029740-1653-11e8-9242-fd381cef9b16.png">

Many thanks!

**Comment by MrGrigri** [comment]
You must understand that these icons are a max size of 24 by 24 pixels. Those examples are too detailed. Do you have anything else in mind? What is this used for?

**Comment by agustinsivoplas** [comment]
I like the eye with gear, also I understand your point, and you are right. 

By definition, computer vision tasks include methods for acquiring, processing, analyzing and understanding digital images, and extraction of high-dimensional data from the real world in order to produce numerical or symbolic information, e.g., in the forms of decisions.

So three dots does not represent the definition.

**Comment by MrGrigri** [comment]
I opened #2828 to handle specifically `eye-settings`. We believe this might be too niech for a project and in your case, you should use an `eye` alone with some text as a discriptor.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
