### ISSUE TITLE
Missing folder-network icon in css, but appers in the site

### ISSUE THREAD

**Issue by insign** [Templarian/MaterialDesign#2829]
Sorry if I am wrong but, [folder-network](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/folder-network.svg) appears in the site and repo but not at the css and not [here](https://cdn.materialdesignicons.com/2.1.19/) too..

What am I missing?

**Comment by PeterShaggyNoble** [comment]
It will be available in the next release.

Don't forget to search existing issues before creating new ones.

**Comment by insign** [comment]
I'm really sorry, I searched before.
