### ISSUE TITLE
Icons for Groceries:

### ISSUE THREAD

**Issue by bonti** [Templarian/MaterialDesign#2830]
It would be great if there were icons for Dairy, Produce, Meat/Seafood, Grains etc. 
I am prototyping for a grocery app in android, and it would very helpful.

**Comment by MrGrigri** [comment]
The best idea would be to create issues for individual icons that you need. Try to provide reference materials as well. This has already been requested at #2378.

**Comment by PeterShaggyNoble** [comment]
[Here](https://petershaggynoble.github.io/MDI-Sandbox/?categories=food) are all the food & drink related icons currently available.
