### ISSUE TITLE
comment-multiple-text

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#2831]
I would love a _filled_ version of `comment-multiple` (as in, not outline) with the text, as in `comment-text`

**Comment by MrGrigri** [comment]
I figured I'd fill in the gaps. Here are `comment-multiple`, `comment-text-multiple`, and `comment-text-multiple-outline`.

![image](https://user-images.githubusercontent.com/4528551/36514427-a3780976-1731-11e8-817b-3a5d8d90c82f.png) ![image](https://user-images.githubusercontent.com/4528551/36514801-89e29632-1733-11e8-9040-eaad91e21852.png) ![image](https://user-images.githubusercontent.com/4528551/36514784-73d62912-1733-11e8-9896-a3051287476f.png)

[comment-multiple.zip](https://github.com/Templarian/MaterialDesign/files/1746315/comment-multiple.zip)

**Comment by k5cents** [comment]
Looks good! With so many alternatives, maybe the site should have one icon and then some kind of expanded menu for all the alternatives (outline, multiple, alternates, etc). Just a thought I had.

**Comment by Templarian** [comment]
[![comment-multiple](https://materialdesignicons.com/icon/comment-multiple)](https://materialdesignicons.com/icon/comment-multiple) [![comment-text-multiple](https://materialdesignicons.com/icon/comment-text-multiple)](https://materialdesignicons.com/icon/comment-text-multiple) [![comment-text-multiple-outline](https://materialdesignicons.com/icon/comment-text-multiple-outline)](https://materialdesignicons.com/icon/comment-text-multiple-outline)
