### ISSUE TITLE
YouTube Trending

### ISSUE THREAD

**Issue by azhsetiawan** [Templarian/MaterialDesign#2832]
I would like to add trending from YouTube, as alternative to Google whatshot

<img width="306" alt="screen shot 2018-02-22 at 3 00 55 pm" src="https://user-images.githubusercontent.com/3045602/36527001-dc8038f4-17e2-11e8-9271-e646e34f8a6b.png">

[trending.zip](https://github.com/Templarian/MaterialDesign/files/1747072/trending.zip)

**Comment by PeterShaggyNoble** [comment]
See #1678, which includes a contribution.
