### ISSUE TITLE
Garage half closed/open

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#2834]
Currently there is a open and a closed garage, but no closing garage.
https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/garage.svg
https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/garage-open.svg
Maybe the same icon with 2 blocks?

**Comment by MrGrigri** [comment]
What would the point of this be? Are you temporarily showing the state of a garage?

**Comment by mueller-ma** [comment]
Yes. I want to use it for openHAB. openHAB has a semi closed door: http://demo.openhab.org:8080/icon/garagedoor?state=50&format=svg

**Comment by MrGrigri** [comment]
I understand that, but when would you, UI speaking, have a garage door that is semi-closed? They are either open, closed, opening, or closing? I could maybe see an icon to represent the action of close and open, but not a time when it's just half-way open.

**Comment by Templarian** [comment]
I could see an alert for a garage door being "ajar". But just a half opened seems specific. Maybe partially opened with an alert symbol.

**Comment by mueller-ma** [comment]
It would be used while the door is closing or opening.

**Comment by MrGrigri** [comment]
@Templarian like this? In fact, I believe we should add this one.

![image](https://user-images.githubusercontent.com/4528551/36608744-f3e2b21a-1887-11e8-83ba-89c1d754b2f5.png)

[garage-alert.zip](https://github.com/Templarian/MaterialDesign/files/1752639/garage-alert.zip)

@mueller-ma, in your case, I would animate that icon which is beyond the scope of this repo. IMO, opening and closing of a garage are quick and the UI should not need to represent that; unless using an animation. Personally, I would animate the three slats on the garage in sequence with a pause at the open/closed state.

**Comment by Templarian** [comment]
Yea, I like that for a door ajar use case. And I agree the use case of it animating half way is a little too specific.

**Comment by mueller-ma** [comment]
I want to build a material icon set for openHAB, so I have to replace all current icons. When you have a garage door that sends it open state in percent to openHAB, the icon would change rapidly going through all 10 available icons (from open to closed). So I would really like to see a half open non-animated icon. Thanks for your effort.

**Comment by MrGrigri** [comment]
@mueller-ma, I doubt this will be added, but here is an SVG -- not a font -- you could use. 

![image](https://user-images.githubusercontent.com/4528551/36613129-d2c8089c-1895-11e8-981b-5e6886c3647c.png)

[garage-half.zip](https://github.com/Templarian/MaterialDesign/files/1752931/garage-half.zip)

**Comment by mueller-ma** [comment]
I couldn't find icons for about 10 openHAB icons. Should I open an issue for each icon or post a list?

**Comment by PeterShaggyNoble** [comment]
One for each, please. Although, you can group variants (e.g., `garage-open`, `garage-closed`) in a single issue if you like. Don't forget to search existing issues first.
