### ISSUE TITLE
garage-alert

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2835]
I opened this issue to separate it from #2834. 

![image](https://user-images.githubusercontent.com/4528551/36614110-dc7068fa-1898-11e8-82cf-b8f745e3ef32.png)

[garage-alert.zip](https://github.com/Templarian/MaterialDesign/files/1752999/garage-alert.zip)

**Comment by Templarian** [comment]
[![garage-alert](https://materialdesignicons.com/icon/garage-alert)](https://materialdesignicons.com/icon/garage-alert)
