### ISSUE TITLE
mqtt

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [Templarian/MaterialDesign#2838]

**Comment by MimbaMonkeyHouse** [comment]
You may find more info here: [(https://mosquitto.org)]
There is an icon here: [https://mosquitto.org/images/mosquitto-text-side-28.png]
Maybe that would work without the text?

**Comment by GreenTurtwig** [comment]
That would represent Mosquito, an MQTT broker, not the MQTT protocol itself. The best we could do would be to modify the logo, although I don't know how good that'll look.  
  
![](http://mqtt.org/new/wp-content/uploads/2011/08/mqttorg-glow.png)

**Comment by MimbaMonkeyHouse** [comment]
True. I guess 90% of users use the Mosquitto implementation. Maybe I should request this instead? That icon looks great too!

**Comment by Templarian** [comment]
Going to close this out. Both of these brands are going to be a little niche and not easily recognizable at the small size. You could probably use a more generic icon like `signal-variant`.
