### ISSUE TITLE
Sports Icon

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#2839]
I had made a previous attempt to contribute a few icons but this time I followed the material design guidelines as best as I could. Hope you like them.

![image](https://user-images.githubusercontent.com/18645219/36636816-b6b477d8-199b-11e8-904b-3910e82ead6c.png)![image](https://user-images.githubusercontent.com/18645219/36636809-abd20704-199b-11e8-9fba-d0603dd2007b.png)![image](https://user-images.githubusercontent.com/18645219/36636831-044a3b36-199c-11e8-9b78-9fbdbf6eb557.png)![image](https://user-images.githubusercontent.com/18645219/36642585-67f05f30-1a0f-11e8-81eb-6fe5b2e82b45.png)![image](https://user-images.githubusercontent.com/18645219/36636839-2cf26770-199c-11e8-9929-b732b7b6df32.png)![image](https://user-images.githubusercontent.com/18645219/36636846-4737a334-199c-11e8-81d0-84a1f90ab600.png)

Download: [icons.zip](https://github.com/Templarian/MaterialDesign/files/1756138/icons.zip)

**Comment by Templarian** [comment]
Are these from the an any Google apps, if so we have to assign them to the Google account?

This is also more than 5 icons, so I need to make a contributor account and assign these to it. Will create an issue to track this in a moment.

[![badminton](https://materialdesignicons.com/icon/badminton)](https://materialdesignicons.com/icon/badminton) [![baseball](https://materialdesignicons.com/icon/baseball)](https://materialdesignicons.com/icon/baseball) [![baseball-bat](https://materialdesignicons.com/icon/baseball-bat)](https://materialdesignicons.com/icon/baseball-bat) [![curling](https://materialdesignicons.com/icon/curling)](https://materialdesignicons.com/icon/curling) [![hockey-puck](https://materialdesignicons.com/icon/hockey-puck)](https://materialdesignicons.com/icon/hockey-puck) [![hockey-sticks](https://materialdesignicons.com/icon/hockey-sticks)](https://materialdesignicons.com/icon/hockey-sticks)

**Comment by Croutonix** [comment]
No, I made all of them. Thanks for the contributor status!
