### ISSUE TITLE
money icon 

### ISSUE THREAD

**Issue by kelewele-pimp** [Templarian/MaterialDesign#284]
Can you pleas add a money icon.. It would really help. cheers

- [x] cash
- [x] cash-usd (rename `cash`)

**Comment by Templarian** [comment]
It already exists... `cash`, `coin`, and the `currency-*`.

Let me know if you mean something else and I'll reopen the issue.

**Comment by kelewele-pimp** [comment]
oh ok.. i need something like a paper icons..

**Comment by Templarian** [comment]
I'm not sure what that means.

**Comment by kelewele-pimp** [comment]
sorry i mean something like this 
http://www.icons4android.com/icon/1563

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/cash
http://materialdesignicons.com/icon/cash-multiple
(and `cash` renamed to `cash-usd`)

**Comment by kelewele-pimp** [comment]
wow thanks a million pal! keep the good job up!
