### ISSUE TITLE
Water heater

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [Templarian/MaterialDesign#2843]
Icon for a water heater could be nice.

Attached is the one I use on my floorplan. The color of the flame changes according to power usage.

[water-heater.svg.zip](https://github.com/Templarian/MaterialDesign/files/1757451/water-heater.svg.zip)

**Comment by GreenTurtwig** [comment]
Would https://github.com/Templarian/MaterialDesign/issues/2900 do?
