### ISSUE TITLE
Icon for electrical water pump

### ISSUE THREAD

**Issue by MimbaMonkeyHouse** [Templarian/MaterialDesign#2844]
The icon for water pump represents a manual/hand water pump. Having one for a motorized pump could be nice as well.

I use a box with a fan/propeller inside on my floorplan (attached). Probably not the best way to portray this, but I ran out of ideas...
[pump.svg.zip](https://github.com/Templarian/MaterialDesign/files/1757464/pump.svg.zip)

**Comment by MrGrigri** [comment]
I believe this could be difficult to represent.

**Comment by goyney** [comment]
We have `fan` and `water-pump`. Introducing electricity to either of these doesn't really change the meaning the icon conveys. We would need to be overly literal in an icon to represent this which would go against Material guidelines. In short, MrGrigri is correct, this will be very difficult to represent in a meaningful way. I'm going to close this issue as too niche to be added, but if you think of other ways this could be represented in the future, please comment back here. Thanks.
