### ISSUE TITLE
Clipboard icons not vertically centred

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2846]
`clipboard-pulse` needs to be shifted down a point in order to vertically centre it. See below with `clipboard-pulse-outline` overlaid in red:

![clipboard-pulse](https://user-images.githubusercontent.com/15157491/36682586-5f8bf1ce-1b13-11e8-9613-630336ba90e6.png)

**Comment by Templarian** [comment]
Good eye, not sure how I did that. 😫 Will fix it this week before the release.

**Comment by JapanYoshi** [comment]
I feel that the icon is more *visually* centered before than after shifting down.

**Comment by PeterShaggyNoble** [comment]
Yoshi's comment prompted me to check the rest of the `clipboard` icons and, bar `clipboard-flow`, they're all sitting one point too high as well.

**Comment by JamesCoyle** [comment]
I think we need to decide how these should be displayed before changing anything. Do we keep them the same as the box icons but with the loop on top? Do we have them match the current `clipboard` icon and squash it down? Or do we vertically center the icon? I think personally I prefer the consistency of keeping it the same size as the box icons.

[![](https://materialdesignicons.com/icon/account-box)](https://materialdesignicons.com/icon/account-box)[![](https://materialdesignicons.com/icon/clipboard-text)](https://materialdesignicons.com/icon/clipboard-text)[![](https://materialdesignicons.com/icon/clipboard)](https://materialdesignicons.com/icon/clipboard)![clipboard-pulse](https://user-images.githubusercontent.com/15157491/36682586-5f8bf1ce-1b13-11e8-9613-630336ba90e6.png)

**Comment by Templarian** [comment]
Closing this issue as the pulse clipboard is correct.

**Comment by PeterShaggyNoble** [comment]
Does that mean `clipboard-pulse-outline` and `clipboard-flow` need to be shifted *up* one point, then?

**Comment by JamesCoyle** [comment]
The clipboard icons are not consistent so need fixing...

**Comment by JamesCoyle** [comment]
Here are the icons which need adjusting. Might need cleaning up a bit.
[Clipboard.zip](https://github.com/Templarian/MaterialDesign/files/1804354/Clipboard.zip)

**Comment by Templarian** [comment]
Fixed. 😃
