### ISSUE TITLE
Icon for Polygon Stroke

### ISSUE THREAD

**Issue by brockhicks** [Templarian/MaterialDesign#2847]
The only icons I could find related to a polygon's stroke/outline are pen icons, which typically denote an "edit mode". It would be very useful for graphic design and mapping applications to have an icon for a polygon's stroke, either along the lines of how Adobe Illustrator, the industry standard, denotes it, or a pen icon that also includes a stroke. 

**EXAMPLES**
![image](https://user-images.githubusercontent.com/19536706/36690989-da0abdca-1ae8-11e8-90da-9851862d7a06.png)

![image](https://user-images.githubusercontent.com/19536706/36690978-d1605680-1ae8-11e8-8a3b-c2234811e339.png)

**Comment by PeterShaggyNoble** [comment]
To provide a couple of options, would one of the [`arrange`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=arrange) or [`vector`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=vector) icons work? Or, maybe, [`gesture`](https://materialdesignicons.com/icon/gesture)?

**Comment by brockhicks** [comment]
@PeterShaggyNoble The arrange icons are along the right track, only issue is that it has the "stroke" behind the "fill", so to me at least this puts the focus on the fill instead of the stroke. I found one backup option:
![image](https://user-images.githubusercontent.com/19536706/36745257-c6b834a8-1ba3-11e8-9397-e765f45a2c3d.png)

**Comment by brockhicks** [comment]
@PeterShaggyNoble Yes, it will work. But I would advocate for more icons for mapping and cartography like this in general.

**Comment by goyney** [comment]
Since your immediate needs were solved, I'm going to close this issue. If you think of more mapping/cartography icons you would like to see added, please open an issue for each independent icon. Thank you!
