### ISSUE TITLE
Pallet

### ISSUE THREAD

**Issue by BGehrels** [Templarian/MaterialDesign#2848]
As Part of #2649 a few ideas were collected how to iconize a cargo pallet.

Since this icon was hard to show without some 3D-tilt, @Templarian asked to split it into a seperate issue.

Some thoughts:
- What makes a pallet special is that you can move a plethora of differently shaped, but stackable objects at once on a common platform. Thats a  property reflected various other palet icons:   [1](https://previews.123rf.com/images/bobnevv/bobnevv1602/bobnevv160200070/52212689-pallet-icon-pallet-logo-pallet-symbol-cargo-icon-isolated-pallet-with-various-cargo-icon-minimal-des.jpg), [2](https://media.gettyimages.com/vectors/cardboard-boxes-on-a-wood-pallet-icon-vector-id466745620)
- Pyramids of equally shaped parcels can be found quite often and give a nice sense of symmetry while still giving a feeling of improvised packaging: [3](https://thenounproject.com/term/pallet/957605/).
- Icons with just one box on top of the pallet seem to drag the optical focus from the pallet to the load, representing more of a parcel/package then a pallet [4](https://thenounproject.com/term/pallet/214763/), [5](https://www.iconexperience.com/g_collection/icons/?icon=wooden_pallet_box), [6](https://www.iconexperience.com/o_collection/icons/?icon=wooden_pallet_box)
- The same holds true for very cubically packed pallets [7](https://glstock.com/graphic/4280014-cardboard-package-boxes-on-pallet-icon)

**Comment by PeterShaggyNoble** [comment]
Of those presented above, I think `3` is the clear winner for me.

In the interests of keeping this issue self-contained, here are the options @goyney provided in #2649.

![](https://user-images.githubusercontent.com/1015040/33466001-1ae39052-d619-11e7-8e3e-e87a9a77c2b2.png) ![](https://user-images.githubusercontent.com/1015040/33467547-3454779a-d623-11e7-8032-bc131015ae4f.png) ![](https://user-images.githubusercontent.com/1015040/33467808-3e89ea54-d625-11e7-82ff-ee223a26722a.png)

**Comment by JamesCoyle** [comment]
I prefer that last one. Needs to be in context though.

**Comment by JapanYoshi** [comment]
I like the corrugated side on the first one. Perhaps modhify ``pallet-alternate-2`` using that shape, while also adding more boxes on top.

**Comment by steodor** [comment]
@JapanYoshi how about this? i'm not quite pleased with it yet, but is it going in the right direction?
![image](https://user-images.githubusercontent.com/4397338/108984432-97dece00-7698-11eb-9e32-9a8a587ff07a.png)
[pallet.zip](https://github.com/Templarian/MaterialDesign/files/6035115/pallet.zip)

**Comment by JapanYoshi** [comment]
Looks quite nice. Maybe the legs on the pallet could be a little shorter, since right now the pallet looks as tall as the boxes on it?

**Comment by steodor** [comment]
Yes, that's true, but i have yet to figure out a way of doing that while keeping the icon centered and not doing half-pixel stuff because it looks awful at native resolution. The worst thing i see are the boxes which take all the focus away from the pallet, i mean, taking a step back and looking at it i'm thinking stacked boxes first, then i see they're on top of, well, something :) i'll try to explore this direction a bit further, maybe i can make the boxes more inconspicuous and drive the focus more towards the pallet.

**Comment by steodor** [comment]
Ok, so if we cut 1dp off the sides and bottom of the pallet, it does look better and now the boxes get to be the same size as well:
![image](https://user-images.githubusercontent.com/4397338/109000702-ba7ae200-76ac-11eb-8666-15cd82b6d934.png)

Next, we could open up the boxes...
![image](https://user-images.githubusercontent.com/4397338/109000902-f01fcb00-76ac-11eb-84c9-d6c9335674f1.png)

...have a single dotted line box...
![image](https://user-images.githubusercontent.com/4397338/109000978-062d8b80-76ad-11eb-9eaf-281395c3df97.png)

...or no box at all:
![image](https://user-images.githubusercontent.com/4397338/109001020-10e82080-76ad-11eb-8fe6-216b891cb714.png)

Well, i tried, but honestly none of these is even remotely as suggestive as the first icon on the thread, the one with perspective. Anyway, if any of these fit the bill for you, you can always directly use the paths from the attached zip file:
### [pallet.zip](https://github.com/Templarian/MaterialDesign/files/6035971/pallet.zip)

**Comment by JapanYoshi** [comment]
What about one big box, smaller than the width of the pallet, but about twice as tall as the pallet?

**Comment by steodor** [comment]
Like this?
![image](https://user-images.githubusercontent.com/4397338/109011940-2283f500-76ba-11eb-90da-1e9319a5900f.png)
[pallet-5.zip](https://github.com/Templarian/MaterialDesign/files/6036483/pallet-5.zip)

**Comment by JapanYoshi** [comment]
Yeah, that looks good to me! I think the box can be expanded downwards 1 or 2 dp, as it looks like it’s levitating as it stands.

**Comment by steodor** [comment]
![image](https://user-images.githubusercontent.com/4397338/109013091-6a574c00-76bb-11eb-90b0-528cefd44609.png)
[pallet-6.zip](https://github.com/Templarian/MaterialDesign/files/6036540/pallet-6.zip)

**Comment by goyney** [comment]
At native size, these all look that a "measurement" of the box. See `human-male-height` for an example. It's not exactly the same, but its meaning is still fuzzy to me. That's why this issue has been open so long, I don't know what the right answer is.

**Comment by JapanYoshi** [comment]
The thicker feet on [this](https://github.com/Templarian/MaterialDesign/issues/2848#issuecomment-784961210) makes the pallet look less like a ruler, IMO.

**Comment by steodor** [comment]
@goyney i hear you, and i see how none of these icons belong in the library, i'm not satisfied with them either. But maybe if in a particular app's context their meaning is more clear, then someone can use the paths directly, that was my goal for now :) as far as the library is concerned though i have no idea what a good `pallet` icon would look like (except the perspective one which is great, but...), any thoughts?

**Comment by goyney** [comment]
[![shipping-pallet](https://materialdesignicons.com/icon/shipping-pallet)](https://materialdesignicons.com/icon/shipping-pallet)
