### ISSUE TITLE
Icon for Sublime Text

### ISSUE THREAD

**Issue by musa11971** [Templarian/MaterialDesign#2849]
An icon for Sublime Text text editor 

![Reference](https://i.imgur.com/YfEH5Ri.png)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @musa11971. At this time, though, we are only adding logos for major social media networks. There also doesn't seem to be an official single colour version of this logo without the shadow.

We'll revisit this issue, though, if a dedicated brands icon pack is ever added.
