### ISSUE TITLE
Icon participate in the event

### ISSUE THREAD

**Issue by lcpereira** [Templarian/MaterialDesign#285]
Hi, 

You could create something to "participate in the event"?

I thought about something like http://goo.gl/B1iycq but it could be something, something you identify join too :)

Thanks!

**Comment by Templarian** [comment]
At the small size it will look like someone having a thumb war. Do you have any other ideas?

**Comment by Templarian** [comment]
By the way I think a calendar with a check mark might work for this?

**Comment by lcpereira** [comment]
True, I'd be really strange.

I liked the idea of using the calendar, I thought of using the "calendar-check" to participate, the "calendar-remove" out and need a calendar empty when not participating. Could make a calendar without that call in the Middle? Create a blank medium?

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/calendar-blank

**Comment by lcpereira** [comment]
Very good! Thank you and congratulations for the work.

**Comment by CoDEmanX** [comment]
Also see #308, it's basically a duplicate.
