### ISSUE TITLE
Television needs to be updated

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2850]
Our `television` icon is 2 points narrower than Google's (overlaid in red below) *and* our own `television-guide` and `television-off` icons.

![television](https://user-images.githubusercontent.com/15157491/36735699-a9c7fce0-1bce-11e8-9eec-bb6009616498.png)

**Comment by Croutonix** [comment]
Why doesn't Google follow their own guidelines of a 2px border? I've seen that in many of their icons.

**Comment by Templarian** [comment]
@Croutonix https://material.io/guidelines/style/icons.html#icons-product-icons The section on keyline shapes describes this. It's often to keep a consistent proportion, especially if an icon has a narrower height.

**Comment by Templarian** [comment]
[![television](https://materialdesignicons.com/icon/television)](https://materialdesignicons.com/icon/television)
