### ISSUE TITLE
watch-export-variant

### ISSUE THREAD

**Issue by BCNelson** [Templarian/MaterialDesign#2851]
Export icon for the watch-variant
![watch-export-variant](https://user-images.githubusercontent.com/5659892/36750186-271f3d26-1bba-11e8-9e1b-95dcb37e0831.png)
[watch-export-variant.zip](https://github.com/Templarian/MaterialDesign/files/1764382/watch-export-variant.zip)

**Comment by Templarian** [comment]
[![watch-export-variant](https://materialdesignicons.com/icon/watch-export-variant)](https://materialdesignicons.com/icon/watch-export-variant)
