### ISSUE TITLE
watch-import-variant

### ISSUE THREAD

**Issue by BCNelson** [Templarian/MaterialDesign#2852]
Import icon for the watch-variant
![watch-import-variant](https://user-images.githubusercontent.com/5659892/36750270-5b28c420-1bba-11e8-98c2-ef3ca2e37454.png)
[watch-import-variant.zip](https://github.com/Templarian/MaterialDesign/files/1764387/watch-import-variant.zip)

**Comment by Templarian** [comment]
[![watch-import-variant](https://materialdesignicons.com/icon/watch-import-variant)](https://materialdesignicons.com/icon/watch-import-variant)
