### ISSUE TITLE
Can't find the icons mdi-security-account and mdi-account-group in the css

### ISSUE THREAD

**Issue by Martijnk70** [Templarian/MaterialDesign#2853]

**Comment by Templarian** [comment]
These were added after the last release and will be going out shortly in the next release.

https://materialdesignicons.com/history

**Comment by ziyafenn** [comment]
Can please someone update, when it's going to be available to use?

**Comment by PeterShaggyNoble** [comment]
@ziyafenn, please make sure you are using the latest version of MDI - it was added in v2.1.99 and the latest version is 2.2.43.
