### ISSUE TITLE
ssh

### ISSUE THREAD

**Issue by BCNelson** [Templarian/MaterialDesign#2855]
ssh icon

![ssh](https://user-images.githubusercontent.com/5659892/36799363-40b64b34-1c6a-11e8-9939-65743b6a7da5.png)
[ssh.zip](https://github.com/Templarian/MaterialDesign/files/1767948/ssh.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution. Unfortunately it's not too legible at 24*24, though.

I think the standard `lock` icon, `security-network` or `server-security` are probably the best options for conveying this.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/36803236-ea64f2a4-1cae-11e8-9a7a-a694e29b4d66.png)](https://github.com/Templarian/MaterialDesign/files/1768200/ssh.zip)
Don't like the limited space for the "S", but that's what it would look like in Google's smaller style.

**Comment by Templarian** [comment]
[![ssh](https://materialdesignicons.com/icon/ssh)](https://materialdesignicons.com/icon/ssh)

**Comment by CoDEmanX** [comment]
It's barely legible at 24px. Isn't there enough space to make the letters larger and align them better to the grid?

**Comment by GreenTurtwig** [comment]
Unfortunately no, that's the style of text Google use, any larger wouldn't give it enough space and also be inconsistent with other icons. We could potentially move everything over .5px though.

**Comment by CoDEmanX** [comment]
Yeah, moving it half a pixel to the left(?) should improve it.
