### ISSUE TITLE
Hurricane

### ISSUE THREAD

**Issue by smasongarrison** [Templarian/MaterialDesign#2856]
I'm working on a project with weather events (such as hurricanes, tornado, etc), and I noticed that there are only a few weather-related icons. 

Suggestions: 

- Hurricane (https://thenounproject.com/term/hurricane/26833/)
- Tornado (https://thenounproject.com/search/?q=tornado&i=3919)

**Comment by Templarian** [comment]
Tornado is tracked here, can probably add it and close that issue. #541

Going to rename this to `Hurricane`.

**Comment by Templarian** [comment]
[![hurricane](https://materialdesignicons.com/icon/hurricane)](https://materialdesignicons.com/icon/hurricane)

**Comment by PeterShaggyNoble** [comment]
Should it be named `weather-hurricane`, for consistency?

**Comment by Templarian** [comment]
Fixed. 🐱
