### ISSUE TITLE
Invisible icon

### ISSUE THREAD

**Issue by Kyonru** [Templarian/MaterialDesign#2858]
An empty icon with all the same dimensions that the other icons, this is for some very specific use cases.

**Comment by PeterShaggyNoble** [comment]
A few general options:
- Use class name `mdi-blank` in the webfont (which is `mdi-solid` with `visibility:hidden`).
- Use an empty 24*24 SVG.
- Use *any* of the icons and set the `opacity` to 0.

Of course there are many more ways of achieving the same result specific to any given situation.

**Comment by Templarian** [comment]
Right now this is not possible with our current build system. Empty path data throws an error in the font generation and this varies based on use cases. I think this should be handled by a component/wrapping element depending on the environment it's being used.
