### ISSUE TITLE
No .mdi-reminder class in materialdesignicons.css

### ISSUE THREAD

**Issue by RavenHursT** [Templarian/MaterialDesign#2859]
Was sooooo excited to see this: https://materialdesignicons.com/icon/reminder

But then quickly got 😢 when I did quick search for `mdi-reminder` and go nothing....

**Comment by Templarian** [comment]
https://materialdesignicons.com/history

It was added after the last release. We're working on the current release right now (wrapping up a few small bugs before publishing).
