### ISSUE TITLE
Update garage icons to match Google's

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2860]
Google has a garage icon in the extended set, we should probably switch replace out design with theirs. As the extended set contains several Google Assistant smart home device icons it's likely this is the icon they'll use when support for garage doors is added in the future.

![](https://user-images.githubusercontent.com/15905797/36871743-18ea6fc2-1d9b-11e8-834a-341f19561542.png)

Updated icons:

[![](https://user-images.githubusercontent.com/15905797/36872023-e2931db0-1d9b-11e8-89d9-398ae2d71f7a.png)](https://github.com/Templarian/MaterialDesign/files/1772940/garage-open.zip)[![](https://user-images.githubusercontent.com/15905797/36871879-7a19d724-1d9b-11e8-8fe8-74afa9e94e9d.png)](https://github.com/Templarian/MaterialDesign/files/1772932/garage-alert.zip)

The way the alert version stretches out to the edge isn't great, but to match Google's design it unfortunately has to.

**Comment by Templarian** [comment]
As discussed on slack, having the designs differ from house more helps distinguish them more easily.
