### ISSUE TITLE
Update fridge icons to match Google's

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2861]
Google's fridge icon, named `kitchen` in the standard set:
![](https://user-images.githubusercontent.com/15905797/36872718-1d9c1f40-1d9e-11e8-9994-c4b3ed53a0b7.png)

Updated icons:
![](https://user-images.githubusercontent.com/15905797/36873005-1d3488d4-1d9f-11e8-952b-827dfbdd10ba.png)
![](https://user-images.githubusercontent.com/15905797/36873030-2fc772ea-1d9f-11e8-8abb-dda4b755ff2f.png)![](https://user-images.githubusercontent.com/15905797/36873042-3b71500c-1d9f-11e8-9a18-46072a8d81db.png)

[fridge.zip](https://github.com/Templarian/MaterialDesign/files/1773000/fridge.zip)

**Comment by Templarian** [comment]
So it's one pixel wider and maybe a `fridge-outline` ?

**Comment by GreenTurtwig** [comment]
Yeah, it's wider and without legs. Similar to the `washing-machine` icon.

**Comment by Templarian** [comment]
I like the legs... it matches the stove.

**Comment by GreenTurtwig** [comment]
To stay consistent across all kitchen icons we need do decide whether to have legs on them or not.

**Comment by Templarian** [comment]
I like the little legs. Not sure we should replace this icon. It goes with the stove icon nicely.
