### ISSUE TITLE
Smoke detector 

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#2864]
https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/smoking.svg doesn't suit in my case.

**Comment by PeterShaggyNoble** [comment]
`nest-protect` is a smoke detector, which should soon be replaced by a more generic one. Will that suit your needs?

[![nest-protect](https://user-images.githubusercontent.com/15157491/36906624-4fe27248-1e2e-11e8-934d-c0b766eb1437.png)](https://materialdesignicons.com/icon/nest-protect)

**Comment by mueller-ma** [comment]
Just searched for "nest protect" and thought this is a speaker :)
Most smoke detectors are round, so this icon isn't easy to recognize.

**Comment by Ch-Lo** [comment]
I also needed a smoke detector a while ago and helped myself out with [blur-radial](https://materialdesignicons.com/icon/blur-radial). Fits pretty well for our needs.

**Comment by Xenomorph99** [comment]
Here's the submissions that were in the duplicate issue:

![fire-sensor](https://user-images.githubusercontent.com/1837101/94170848-cccac880-fe4d-11ea-9f05-b55609ee1fd5.png)
![fire-sensor-off](https://user-images.githubusercontent.com/1837101/94170847-cc323200-fe4d-11ea-8485-b295318eff6c.png)

![smoke-detector-outline](https://user-images.githubusercontent.com/1837101/94170854-ce948c00-fe4d-11ea-8039-a72c288754cf.png)

![smoke-detector-off](https://user-images.githubusercontent.com/1837101/94170852-cdfbf580-fe4d-11ea-8bde-d1d35a6b9632.png)
![smoke-detector-off-outline](https://user-images.githubusercontent.com/1837101/94170851-cdfbf580-fe4d-11ea-8f91-e95231b82835.png)

![smoke-detector-fire](https://user-images.githubusercontent.com/1837101/94170850-cd635f00-fe4d-11ea-85bb-11563fb4090b.png)
![smoke-detector-fire-outline](https://user-images.githubusercontent.com/1837101/94170849-cccac880-fe4d-11ea-8636-63a252c4dca9.png)

[smoke-detector-and-fire-sensor.zip](https://github.com/Templarian/MaterialDesign/files/5277536/smoke-detector-and-fire-sensor.zip)

**Comment by goyney** [comment]
[![smoke-detector](https://materialdesignicons.com/icon/smoke-detector)](https://materialdesignicons.com/icon/smoke-detector)[![smoke-detector-off](https://materialdesignicons.com/icon/smoke-detector-off)](https://materialdesignicons.com/icon/smoke-detector-off)
[![smoke-detector-outline](https://materialdesignicons.com/icon/smoke-detector-outline)](https://materialdesignicons.com/icon/smoke-detector-outline)[![smoke-detector-off-outline](https://materialdesignicons.com/icon/smoke-detector-off-outline)](https://materialdesignicons.com/icon/smoke-detector-off-outline)
[![smoke-detector-variant](https://materialdesignicons.com/icon/smoke-detector-variant)](https://materialdesignicons.com/icon/smoke-detector-variant)[![smoke-detector-variant-off](https://materialdesignicons.com/icon/smoke-detector-variant-off)](https://materialdesignicons.com/icon/smoke-detector-variant-off)
