### ISSUE TITLE
Lawnmower

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#2865]
An old school one, no duplicate of #2522

**Comment by henriquecm** [comment]
![mdi_lawnmoner](https://user-images.githubusercontent.com/15136037/38451281-945c628a-3a03-11e8-9273-97bb719228d9.png)

[mdi_lawnmoner.zip](https://github.com/Templarian/MaterialDesign/files/1886051/mdi_lawnmoner.zip)

**Comment by goyney** [comment]
Already exists:
[![mower](https://materialdesignicons.com/icon/mower)](https://materialdesignicons.com/icon/mower)[![mower-bag](https://materialdesignicons.com/icon/mower-bag)](https://materialdesignicons.com/icon/mower-bag)
