### ISSUE TITLE
Electricity

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#2867]
I already used "power", "power socket" and "power plug" for other purposes. Maybe a lightning (without cloud)

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/flash)](https://materialdesignicons.com/icon/flash)

**Comment by mueller-ma** [comment]
@GreenTurtwig I cannot see your comment. Can you link the icon?

**Comment by PeterShaggyNoble** [comment]
It's the [`flash` icon](https://materialdesignicons.com/icon/flash), which is aliased as `lightning`. I'm going to add the alias `electricity` as this is the second request this week,

**Comment by mueller-ma** [comment]
I'm sorry, I just used github's "Find file". I didn't know about the aliases on the website.

**Comment by PeterShaggyNoble** [comment]
Ah, in that case you should note that the SVGs in this repository aren't the production ones; use the ones on the website or in the [MaterialDesign-SVG](https://github.com/Templarian/MaterialDesign-SVG) repo.
