### ISSUE TITLE
account-edit

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#287]
- [ ] account-edit

**Comment by JamesCoyle** [comment]
I'm bumping this up as we just had another request for it and honestly I'm surprised it doesn't already exist.

**Comment by CoDEmanX** [comment]
We have two icons for user settings (user + cog and user + 3 dots)

**Comment by Templarian** [comment]
Please mark these as high priority when you see fit. I'm bar jumping most days during the summer so this is my list I'll use to set milestones (not joking bar jumping right now and your emails are showing up).

**Comment by Templarian** [comment]
[![account-edit](https://materialdesignicons.com/icon/account-edit)](https://materialdesignicons.com/icon/account-edit)
