### ISSUE TITLE
Needle about to pop a balloon

### ISSUE THREAD

**Issue by moi90** [Templarian/MaterialDesign#2870]

**Comment by PeterShaggyNoble** [comment]
Could you provide a use-case for this?

**Comment by PeterShaggyNoble** [comment]
See also #1534

**Comment by moi90** [comment]
The icon could stand for a situation, where a concept contains other nested concepts. This parent concept is then "popped" to draw the child concepts to the same level. I guess, one could use `group` / `ungroup` for this.

**Comment by PeterShaggyNoble** [comment]
Yeah, as a representation of that concept, I think and needle and balloon would be too abstract.
