### ISSUE TITLE
GHS hazard pictograms

### ISSUE THREAD

**Issue by moi90** [Templarian/MaterialDesign#2871]
https://en.wikipedia.org/wiki/GHS_hazard_pictograms

**Comment by Templarian** [comment]
These are going to be very difficult to represent in the size. We have some of the basic radiation/hazard icons.

Do you have examples for these that are more minimalistic in design?

**Comment by moi90** [comment]
As far as I understand, these pictograms are standardized. I don't know if someone made simplified versions...

**Comment by JamesCoyle** [comment]
In this case, using the actual icons is going to be pretty much mandatory for most use cases. If you don't need the actual icons then we have alternatives for several already.

### Harmful
[![](https://materialdesignicons.com/icon/exclamation)](https://materialdesignicons.com/icon/exclamation)[![](https://materialdesignicons.com/icon/alert)](https://materialdesignicons.com/icon/alert)

### Explosive
[![](https://materialdesignicons.com/icon/bomb)](https://materialdesignicons.com/icon/bomb)

### Flammable
[![](https://materialdesignicons.com/icon/fire)](https://materialdesignicons.com/icon/fire)

### Infectious
[![](https://materialdesignicons.com/icon/biohazard)](https://materialdesignicons.com/icon/biohazard)

### Radioactive
[![](https://materialdesignicons.com/icon/radioactive)](https://materialdesignicons.com/icon/radioactive)

### Poisonous 
[![](https://materialdesignicons.com/icon/skull)](https://materialdesignicons.com/icon/skull)

**Comment by Templarian** [comment]
Closing as I don't think the additions are going to be possible. I'll reopen if we need to add more general icons that could represent these.
