### ISSUE TITLE
shaker

### ISSUE THREAD

**Issue by coogle** [Templarian/MaterialDesign#2873]
Random need: An icon of a "shaker" tipped and shaking flakes out. Used in Home automation systems for an automatic fish feeder.

**Comment by PeterShaggyNoble** [comment]
Note that Google use a variation of [`fish`](https://materialdesignicons.com/icon/fish) as their `fishfood` icon.

![image](https://user-images.githubusercontent.com/15157491/36971283-33865736-2063-11e8-89d8-8c462982fc6f.png)

**Comment by GreenTurtwig** [comment]
@PeterShaggyNoble "Fishfood" is actually a term used internally at Google. It's similar to ["dog food"](https://en.m.wikipedia.org/wiki/Eating_your_own_dog_food) but for extremely early releases.  
  
"Dogfood" is represented by a paw, "fishfood" by the fish above and "debug" by a beetle.

**Comment by PeterShaggyNoble** [comment]
Thanks, @GreenTurtwig, that's my "something new" for today sorted already 😄

**Comment by GreenTurtwig** [comment]
Wonderful :cat2:

**Comment by goyney** [comment]
We've recently added some shakers.

[![shaker](https://materialdesignicons.com/icon/shaker)](https://materialdesignicons.com/icon/shaker)[![shaker-outline](https://materialdesignicons.com/icon/shaker-outline)](https://materialdesignicons.com/icon/shaker-outline)
