### ISSUE TITLE
Issue with Google's dollar sign icon

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#2874]
Google's dollar sign icon is not centered horizontally and the 2px stroke width is not consistent. So I made a new icon with all nodes on exact coordinates and with consistent stroke width, here's the comparison of the two (I centered Google's icon to compare):

![image](https://user-images.githubusercontent.com/18645219/36954496-755fd51a-1ff0-11e8-9b1c-34c23d2409ef.png)

I needed a stroke version of the dollar sign to make other icons with it but smaller and by scaling it down I lost the 2px width,

SVG files for the icon, the comparison and the stroke version: [icon.zip](https://github.com/Templarian/MaterialDesign/files/1779277/icon.zip)

**Comment by Templarian** [comment]
The `currency-usd-off` icon was also fixed. Thanks @Croutonix!
