### ISSUE TITLE
Voltmeter

### ISSUE THREAD

**Issue by jurisbandenieks** [Templarian/MaterialDesign#2878]
Need an icon for measuring Volts, as in Voltmeter.
Something like this:
https://image.freepik.com/free-vector/iec-volt-meter-symbol_17-1117000631.jpg

**Comment by PeterShaggyNoble** [comment]
I think one of the device symbols in the gallery you linked to would communicate this much better and I'm pretty sure we already have an open issue for a similar, if not identical, icon. I'll see if I can find it in a few minutes ...

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
