### ISSUE TITLE
electric switch

### ISSUE THREAD

**Issue by jurisbandenieks** [Templarian/MaterialDesign#2879]
Need an icon for electric switch.
Like:
[![](https://user-images.githubusercontent.com/15157491/37030657-accea0a0-2133-11e8-943d-d3bffeb0df35.png)](https://cdn2.iconfinder.com/data/icons/electric-circuits-linear-black/614/4087_-_Switch-256.png)

**Comment by PeterShaggyNoble** [comment]
See also #1163

**Comment by GreenTurtwig** [comment]
Google's switch design in Android P:
![image](https://user-images.githubusercontent.com/15905797/37400143-db9e6070-277b-11e8-868a-d1ec3dc935ee.png)

**Comment by Louistwee** [comment]
### Opening: 30deg
![image](https://user-images.githubusercontent.com/27563848/44907423-2799a080-ad18-11e8-9047-0026fe34b1ff.png)

``M 14.328125 6.5 L 7.953125 10.244141 A 2 2 0 0 0 7 10 A 2 2 0 0 0 5.2714844 11 L 2 11 L 2 13 L 5.2695312 13 A 2 2 0 0 0 7 14 A 2 2 0 0 0 9 12 A 2 2 0 0 0 8.9980469 11.955078 L 15.273438 8.3320312 L 14.328125 6.5 z M 17 10 A 2 2 0 0 0 15 12 A 2 2 0 0 0 17 14 A 2 2 0 0 0 18.728516 13 L 22 13 L 22 11 L 18.730469 11 A 2 2 0 0 0 17 10 z M 7 11 A 1 1 0 0 1 7.8417969 11.458984 L 7.8457031 11.464844 A 1 1 0 0 1 8 12 A 1 1 0 0 1 7 13 A 1 1 0 0 1 6 12 A 1 1 0 0 1 7 11 z M 17 11 A 1 1 0 0 1 18 12 A 1 1 0 0 1 17 13 A 1 1 0 0 1 16 12 A 1 1 0 0 1 17 11 z ``


### Opening: 45deg
![image](https://user-images.githubusercontent.com/27563848/44907640-ed7cce80-ad18-11e8-9988-a521f5b9d0c7.png)

``M 12.699219 4.8339844 L 7.5371094 10.072266 A 2 2 0 0 0 7 10 A 2 2 0 0 0 5.2714844 11 L 2 11 L 2 13 L 5.2695312 13 A 2 2 0 0 0 7 14 A 2 2 0 0 0 9 12 A 2 2 0 0 0 8.9355469 11.509766 L 14.085938 6.359375 L 12.699219 4.8339844 z M 17 10 A 2 2 0 0 0 15 12 A 2 2 0 0 0 17 14 A 2 2 0 0 0 18.728516 13 L 22 13 L 22 11 L 18.730469 11 A 2 2 0 0 0 17 10 z M 7 11 A 1 1 0 0 1 7.7167969 11.302734 L 7.7226562 11.308594 A 1 1 0 0 1 8 12 A 1 1 0 0 1 7 13 A 1 1 0 0 1 6 12 A 1 1 0 0 1 7 11 z M 17 11 A 1 1 0 0 1 18 12 A 1 1 0 0 1 17 13 A 1 1 0 0 1 16 12 A 1 1 0 0 1 17 11 z ``

**Comment by Louistwee** [comment]
### Closed - 1
![image](https://user-images.githubusercontent.com/27563848/44908081-734d4980-ad1a-11e8-810c-b7328d2d5fc7.png)

``M 15.503906 8.5859375 L 8.3769531 10.550781 A 2 2 0 0 0 7 10 A 2 2 0 0 0 5.2714844 11 L 2 11 L 2 13 L 5.2695312 13 A 2 2 0 0 0 7 14 A 2 2 0 0 0 8.9414062 12.474609 L 15.457031 10.728516 A 2 2 0 0 0 15 12 A 2 2 0 0 0 17 14 A 2 2 0 0 0 18.728516 13 L 22 13 L 22 11 L 18.730469 11 A 2 2 0 0 0 17 10 A 2 2 0 0 0 15.884766 10.341797 L 15.503906 8.5859375 z M 7 11 A 1 1 0 0 1 8 12 A 1 1 0 0 1 7 13 A 1 1 0 0 1 6 12 A 1 1 0 0 1 7 11 z M 17 11 A 1 1 0 0 1 18 12 A 1 1 0 0 1 17 13 A 1 1 0 0 1 16 12 A 1 1 0 0 1 17 11 z ``
### Closed - 2
![image](https://user-images.githubusercontent.com/27563848/44908199-e951b080-ad1a-11e8-806a-1da27e230e27.png)
``M 7 10 A 2 2 0 0 0 5.2714844 11 L 2 11 L 2 13 L 5.2695312 13 A 2 2 0 0 0 7 14 A 2 2 0 0 0 8.7285156 13 L 15.269531 13 A 2 2 0 0 0 17 14 A 2 2 0 0 0 18.728516 13 L 22 13 L 22 11 L 18.730469 11 A 2 2 0 0 0 17 10 A 2 2 0 0 0 15.271484 11 L 8.7304688 11 A 2 2 0 0 0 7 10 z M 7 11 A 1 1 0 0 1 8 12 A 1 1 0 0 1 7 13 A 1 1 0 0 1 6 12 A 1 1 0 0 1 7 11 z M 17 11 A 1 1 0 0 1 18 12 A 1 1 0 0 1 17 13 A 1 1 0 0 1 16 12 A 1 1 0 0 1 17 11 z ``

**Comment by CoDEmanX** [comment]
Any chance to get the circles bigger?

**Comment by Templarian** [comment]
[![electric-switch](https://materialdesignicons.com/icon/electric-switch)](https://materialdesignicons.com/icon/electric-switch)
