### ISSUE TITLE
Ko-Fi

### ISSUE THREAD

**Issue by NOMADE55** [Templarian/MaterialDesign#2883]
Dunno how big is Ko-Fi at the moment, but seems to be an alterantive to patreon with a few followers.

[Ko-Fi Website](https://ko-fi.com/)

**Comment by JapanYoshi** [comment]
I can attest to the popularity of Ko-Fi, as someone who occasionally goes on Tumblr ~~and FurAffinity, shut up~~.

**Comment by PeterShaggyNoble** [comment]
It's not quite popular enough for us to consider adding it at this time but is does look like it's currently experiencing some massive growth. Labelling as "Low Priority" for now, rather than "Rejected", so we can keep an eye on it.

**Comment by NOMADE55** [comment]
True!

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
