### ISSUE TITLE
Philips Hue lights

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#2884]
Would it be possible to convert the Hue icon pack available at https://developers.meethue.com/documentation/icon-pack?

all in .svg or .pdf

Several very nice icons could be used and turned into a icon: mdi:hue-light etc etc

Cheers,
Marius

![hue_go](https://user-images.githubusercontent.com/33354141/37085094-786ffa5e-21f4-11e8-919c-f61f54a364ae.png)
![hue_go_outline](https://user-images.githubusercontent.com/33354141/37085219-c549819c-21f4-11e8-9681-ca6363b8f772.png)

**Comment by JapanYoshi** [comment]
1) I can't see that page, and I doubt anyone else here can.

2) From what I can see, that icon isn't Material-compliant.

3) There are a lot of icons here on MDI if you search for "light".

**Comment by PeterShaggyNoble** [comment]
@hvbhome, we generally only include generic device icons. We already have a few in the collection, as @JapanYoshi mentioned, and we also have a few other open issues requesting different types of lighting icons, including #1712, #1826, #2772 & #2801.

**Comment by hvbhome** [comment]
thanks guys,

not sure if i can still reply, since @JapanYoshi closed...

i know several lights are available, using them even, but would love to distinguish in the Home-Assistant setup. Since all icons in the IconPack are available as .svg i would have thought it rather possible to convert. 

Appreciate the generic principle, but maybe market-leader could be another one ;-)

Will try to crop down the current image and set it as entity_picture. Could you please point me to the specs of the MDI icons? image size and colors specifically?

Cheers,
Love customizing using mdi!

![schermafbeelding 2018-03-07 om 13 15 12](https://user-images.githubusercontent.com/33354141/37091768-a1c29b86-2209-11e8-8e68-e327bb19e3ea.jpg)

**Comment by PeterShaggyNoble** [comment]
Icons should conform to [Google's guidelines](https://material.io/guidelines/style/icons.html), specifically those for [system icons](https://material.io/guidelines/style/icons.html#icons-system-icons).
