### ISSUE TITLE
file-compare

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#2886]
Similar to `compare`, but specific to files or documents.
![image](https://user-images.githubusercontent.com/1015040/37102531-02d784ea-21f6-11e8-80cd-5e4abc34e6f2.png)
[file-compare.zip](https://github.com/Templarian/MaterialDesign/files/1789778/file-compare.zip)

**Comment by Templarian** [comment]
[![file-compare](https://materialdesignicons.com/icon/file-compare)](https://materialdesignicons.com/icon/file-compare)
