### ISSUE TITLE
account-heart

### ISSUE THREAD

**Issue by patrickabkarian** [Templarian/MaterialDesign#2888]
[account-heart.svg.zip](https://github.com/Templarian/MaterialDesign/files/1792322/account-heart.svg.zip)
seems missing

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/37155378-d90ae646-22b0-11e8-9ad7-d36d735a0d33.png)
[account-heart.zip](https://github.com/Templarian/MaterialDesign/files/1793427/account-heart.zip)

**Comment by PeterShaggyNoble** [comment]
Should the heart be on the left?

**Comment by goyney** [comment]
@PeterShaggyNoble Yes, I think you are right. This matches `account-star`, for example. I've updated the contribution to match that style.

**Comment by Templarian** [comment]
[![account-heart](https://materialdesignicons.com/icon/account-heart)](https://materialdesignicons.com/icon/account-heart)
