### ISSUE TITLE
Request: Cogs

### ISSUE THREAD

**Issue by feralheart** [Templarian/MaterialDesign#2889]
Need an icon with more cogs, like this:

![Cogs](https://image.freepik.com/free-icon/cogs-one-big-and-two-small_318-41835.jpg)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request but this is a duplicate of #1262.

**Comment by feralheart** [comment]
@PeterShaggyNoble I see. And when will be available in this package, too?

**Comment by Templarian** [comment]
@feralheart Marked that other issue as high priority so it doesn't get ignored.
