### ISSUE TITLE
New icons don't exist

### ISSUE THREAD

**Issue by GuiCavi** [Templarian/MaterialDesign#289]
I tryed to download from NPM and manual download, but the last icon added is 'mdi-format-paragaph'.
I can't understand... :cry:

**Comment by Templarian** [comment]
I need to publish an update. Actually I fixed the build process three days ago so it will be a lot quicker from now on (if I don't get lazy). The build process regenerates the entire branch (it's what the future subfont generation tool will use).

Should have time tonight to get an update published.

**Comment by GuiCavi** [comment]
Oh, now I understand haha
Tought my NPM had a bug :sweat_smile:

**Comment by Templarian** [comment]
Didn't get it in last night, was trying to resolve #279 before publishing. This weekend it will be updated.
