### ISSUE TITLE
Feature request: Split and merge icons

### ISSUE THREAD

**Issue by feralheart** [Templarian/MaterialDesign#2890]
I want to split some icons to half and place it next to each other like in this stock photo:

![StockPhoto from ShutterSctock](https://i.stack.imgur.com/ULp19.jpg)

I want `mdi-options` to the left and `mdi-format-text` to the right.

Is there any method for that now or will be in the future?

**Comment by PeterShaggyNoble** [comment]
Are you using SVGs or the webfont?

**Comment by Templarian** [comment]
We're planning to have a codepen examples section shortly with examples of how to use the icons. This would be a little too custom to include in the `scss`, but I'm sure there is a small snippet to mask and overlay them.

**Comment by PeterShaggyNoble** [comment]
Here are 3 quick options I came up with while waiting for @feralheart to reply: https://codepen.io/PeterShaggyNoble/pen/GxKzbz

The first uses two single path SVGs with their `viewbox`, `width` & `height` properties edited. The second uses a single SVG with two paths and `clipPath`s. The third use the webfont with custom classes.

**Comment by feralheart** [comment]
I'm using webfont

**Comment by PeterShaggyNoble** [comment]
See option 3 in my Pen above, so.

**Comment by feralheart** [comment]
Thank you :)
