### ISSUE TITLE
settings-outline

### ISSUE THREAD

**Issue by efrenba** [Templarian/MaterialDesign#2892]
Hi there,

I would like a couple of icons (vector drawable), both outline style:
-Map marker
-Settings (gear)

thanx...

**Comment by Templarian** [comment]
Can you rename this and make a separate issue for one of these requests (one icon per issue).

**Comment by PeterShaggyNoble** [comment]
`map-marker-outline` already exists.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/37177534-bdca18b0-22ed-11e8-9c04-efe11c2785ac.png)
[settings-outline.zip](https://github.com/Templarian/MaterialDesign/files/1794894/settings-outline.zip)

**Comment by MrGrigri** [comment]
Idk if I like that as an outline.

**Comment by efrenba** [comment]
I didn't see the map-marker
Thank u goyney and thank u everyone

**Comment by PeterShaggyNoble** [comment]
https://materialdesignicons.com/icon/map-marker-outline

What were you searching for that you couldn't find it?

**Comment by MrGrigri** [comment]
If you don't want this added then close it again. But we keep the issues open until they are added to the pack.

**Comment by efrenba** [comment]
oh sorry I closed the issue because I thought it ended there. Of course I agree the icon be added.

**Comment by Templarian** [comment]
[![settings-outline](https://materialdesignicons.com/icon/settings-outline)](https://materialdesignicons.com/icon/settings-outline)

**Comment by Templarian** [comment]
@goyney I went back and redid the vector, there were a lot point issues in the vector provided. Make sure to remove any unnecessary points in the vector prior to uploading.
