### ISSUE TITLE
microphone-plus and microphone-minus

### ISSUE THREAD

**Issue by swmarks** [Templarian/MaterialDesign#2894]
I'd envision this being the standard microphone with a + or - on the right similar to the volume-plus and volume-minus icons that are already part of this project. This would be useful for buttons to raise or lower microphone gain.

**Comment by MrGrigri** [comment]
Here you go.

![image](https://user-images.githubusercontent.com/4528551/37182600-489d026c-22ef-11e8-88bf-025b37328623.png) ![image](https://user-images.githubusercontent.com/4528551/37182577-31206926-22ef-11e8-86b1-bacf5754f6b8.png)

[microphone-plus.zip](https://github.com/Templarian/MaterialDesign/files/1795146/microphone-plus.zip)

[microphone-minus.zip](https://github.com/Templarian/MaterialDesign/files/1795145/microphone-minus.zip)

**Comment by swmarks** [comment]
This is exactly what I had in mind. Thank you!

**Comment by Templarian** [comment]
[![microphone-minus](https://materialdesignicons.com/icon/microphone-minus)](https://materialdesignicons.com/icon/microphone-minus) [![microphone-plus](https://materialdesignicons.com/icon/microphone-plus)](https://materialdesignicons.com/icon/microphone-plus)
