### ISSUE TITLE
Calendar edit

### ISSUE THREAD

**Issue by tretli** [Templarian/MaterialDesign#2895]
a calendar icon with a pencil indicating that you could edit the calendar entry. 

like your Table Edit. icon but with calendar 

example: 
![image](https://user-images.githubusercontent.com/4906083/37206516-2efd3656-2399-11e8-877b-0b4eebc638ad.png)

**Comment by MrGrigri** [comment]
Would this suffice?

![image](https://user-images.githubusercontent.com/4528551/37223099-b62e9e88-238c-11e8-9aee-e1fa81a2648d.png)

[calendar-edit.zip](https://github.com/Templarian/MaterialDesign/files/1797940/calendar-edit.zip)

**Comment by Templarian** [comment]
[![calendar-edit](https://materialdesignicons.com/icon/calendar-edit)](https://materialdesignicons.com/icon/calendar-edit)

**Comment by tretli** [comment]
Excellent. Thanks.

On 10 Mar 2018 17:55, Austin Andrews <notifications@github.com> wrote:

[calendar-edit]<https://materialdesignicons.com/icon/calendar-edit>
