### ISSUE TITLE
Button and Quick Reply Button

### ISSUE THREAD

**Issue by feralheart** [Templarian/MaterialDesign#2896]
I'm looking for some icons what I can use for "add button" and "add quick reply" buttons.
[These](https://scontent.fbud1-1.fna.fbcdn.net/v/t39.2365-6/14175277_1582251242076612_248078259_n.png?oh=e1605d92d0f51564ef7ff95cc814d05b&oe=5B0740D6) are quick replies.

**Comment by PeterShaggyNoble** [comment]
`reply` should cover "quick reply" and Google's `buttons alt` might do the job for "add button". If these don't suit your needs then please provide some examples of what you *are* looking for; I couldn't see anything in your screenshot that communicated either of these things.

![buttons alt](https://user-images.githubusercontent.com/15157491/37207272-26587df8-2394-11e8-9e54-36b660ee2d63.png)

**Comment by feralheart** [comment]
The quick response button is those small bubbles (for example on the first one the "Small" "Medium" "Large" buttons).
This `buttons-alt` looks promising, but when will it be available?

**Comment by PeterShaggyNoble** [comment]
The problem with those buttons is they're not a fixed size; they need to be 24*24. The best way to achieve them is to style them yourself.

**Comment by Templarian** [comment]
I'm leaning toward this being very niche. It's a rounded rectangle with a +... hmm, seems too generic.

**Comment by PeterShaggyNoble** [comment]
I suspect Google's intended use for `buttons alt` might be something to do with configuration settings for game controllers.

**Comment by CoDEmanX** [comment]
The + is not grid-aligned BTW.

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX, that could be down to the way I converted it (running the WOFF2 file through an SVG converter) and/or the preview generator scaling the resulting SVG down.

**Comment by CoDEmanX** [comment]
It seems to be perfectly centered though, and the base shape is grid-aligned. Maybe that's the reason? One would have to increase or decrease the base shape by 1px to center the plus.

**Comment by OctoberJemini** [comment]
I think a button would be an awesome icon.  There are icons for all the other form elements, why not have one for Buttons

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
