### ISSUE TITLE
Bug: image

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#2897]
I believe that the SVG for [`image`](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/image.svg) is incorrect when compared to the font.

The font is on the left and the SVG is on the right.

![image](https://user-images.githubusercontent.com/4528551/37221650-ea1c4e2a-2387-11e8-895e-f104839fe4cb.png)

**Comment by Templarian** [comment]
The working directory doesn't reflect renames, I sometimes forget to rename them in the working repo. Will need to rename this one.

Also we need to make it more obvious that `mdi-svg` is production SVG's and not this repo.

**Comment by PeterShaggyNoble** [comment]
I updated [this list](https://github.com/PeterShaggyNoble/MDI-Sandbox/blob/master/iconupdates.md) last week.
