### ISSUE TITLE
seat-recline-empty 

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#2899]
Would be wonderful if we could have he below icons, for specializing work and living setups...

seat-recline-empty
desk-light
desk-chair

**Comment by Templarian** [comment]
Do you have examples of what these might look like? (reference/example images can be pasted inline)

**Comment by hvbhome** [comment]
not really, i use the seat-recline-extra now, maybe just take out the human on it ;-)

also as an example i use this for desk-chair (maybe should have said office-chair?)
![aandeslag](https://user-images.githubusercontent.com/33354141/37246252-70051b38-24a6-11e8-93e4-7fcbe393ad50.png)

haven't got a desk-light at hand, but something along the lines of:

![schermafbeelding 2018-03-10 om 21 43 23](https://user-images.githubusercontent.com/33354141/37246574-1c38fe10-24ac-11e8-8760-1fa2dd5dc235.jpg)

while we're at it, i need an induction cooking plate too ;-)

![schermafbeelding 2018-03-10 om 22 07 44](https://user-images.githubusercontent.com/33354141/37246732-7e0a0154-24af-11e8-8f8c-38fea66a971e.jpg)

**Comment by CoDEmanX** [comment]
> maybe just take out the human on it

It will be hardly recognizable without human I'm afraid. That's actually the reason why Google added humans.

**Comment by hvbhome** [comment]
lol. must admit its not the best of icons, even with a human ;-) no first world problem .

**Comment by PeterShaggyNoble** [comment]
@hvbhome, could you please separate these 4 requests into individual issues?

**Comment by hvbhome** [comment]
> @hvbhome, could you please separate these 4 requests into individual issues?

will do, thanks

**Comment by goyney** [comment]
I don't think this is something we're going to add. Thanks for the suggestion.
