### ISSUE TITLE
Angular-material

### ISSUE THREAD

**Issue by pbhowmic** [Templarian/MaterialDesign#290]
How can I use the icon set with [angular-material](https://github.com/angular/material). Can you provide an example? I really don't want to have to download icons on by one, it's much easier to use the icon as a set.

**Comment by Templarian** [comment]
I'm not really familiar with the project. I'm more a bootstrap person (where the icons are easy to drop in).

Just looking at the code for the `mdIcon` [directive](https://github.com/angular/material/blob/master/src/components/icon/iconDirective.js) you can tell it just places the font glyph in the template. So just do something simple like:

```xml
<md-icon md-font-icon="mdi-account"></md-icon>
```

**Comment by tuhoojabotti** [comment]
I would like to use svg version so that you can add colours to the icons if you wish. Using md-svg-icon, but the repository doesn't contain a suitable svg file and the polymer version contains html imports and so. It would be nice to have a svg set that works with $mdIconProvider: https://material.angularjs.org/#/api/material.components.icon/service/$mdIconProvider

**Comment by Templarian** [comment]
The SVG's are provided through the site. Right click or click on any icon and click Download SVG from the drop down.

**Comment by tuhoojabotti** [comment]
@Templarian But it would be convenient to have a spritesheet generated from all the icons. Then I just have to register the sprite with $mdIconProvider and I can reference icons by name.

I guess I could make my own svg sprite manually and copy icons there as I need them.

See: https://github.com/google/material-design-icons/tree/master/sprites

**Comment by Templarian** [comment]
Making a sprite sheet with all of the icons would be pretty large and overkill. Eventually the site will be getting a kind of drag and drop font creator (that could very easily create a sprite sheet). It will remember the icons and save it in a `/set/2jk23e` url fashion for future sharing and tweaking.

Until then I would advise just right clicking and viewing the SVG and copying it and pasting it into you file. Or a way cleaner idea, use the webfont. :smile:
