### ISSUE TITLE
Boiler

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#2900]
Couldn't find any references in the icon requests for these missing icons:

central heating
boiler
solar-boiler

other than mdi:radiator
maybe these would be nice to add:

![zonneboiler-icon](https://user-images.githubusercontent.com/33354141/37276365-cb4472c8-25e1-11e8-9da7-7e6949361713.png)

![home-energy](https://user-images.githubusercontent.com/33354141/37276035-fa0ae3ea-25e0-11e8-81b8-3b8d4f6e0c00.jpg)
![home-heating](https://user-images.githubusercontent.com/33354141/37276036-fa24bdba-25e0-11e8-8837-c4a2571b396e.jpg)

![boiler](https://user-images.githubusercontent.com/33354141/37276258-8822ffb4-25e1-11e8-9289-bbabdad1ac85.png)
![boilerinstallation](https://user-images.githubusercontent.com/33354141/37276259-883c7be2-25e1-11e8-8bdb-b7c6ed2e0919.png)
![central-heater](https://user-images.githubusercontent.com/33354141/37276260-8858cf86-25e1-11e8-9141-2581f1314b70.png)
![heating](https://user-images.githubusercontent.com/33354141/37276261-887746b4-25e1-11e8-8a11-6195a7347a26.png)

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/37399710-61a6826c-277a-11e8-963d-eea4777709e7.png)](https://github.com/Templarian/MaterialDesign/files/1810801/boiler.zip)

**Comment by MimbaMonkeyHouse** [comment]
Yup, that would work for me!

**Comment by quietmint** [comment]
I think this looks far too much like a smartphone, not a water heater (e.g., camera-rear and camera-rear-variant)

**Comment by CoDEmanX** [comment]
It reminds me more of a diode or some similar electronic circuit component

**Comment by PeterShaggyNoble** [comment]
Context is important 😉

**Comment by GreenTurtwig** [comment]
Yup, it's an extremely difficult thing to represent and as most boilers are just white boxes on a wall or in a cupboard there isn't much to go on. Given the right context inside an app or website it'll make more sense what it is.

**Comment by MimbaMonkeyHouse** [comment]
I like the icon I'm using:
![water-heater](https://user-images.githubusercontent.com/35156237/37768478-be8c3c30-2e08-11e8-9ab3-ada3124f3633.png)

**Comment by goyney** [comment]
[![water-boiler](https://materialdesignicons.com/icon/water-boiler)](https://materialdesignicons.com/icon/water-boiler)
