### ISSUE TITLE
icon request: phone, towel and iron

### ISSUE THREAD

**Issue by eleumas** [Templarian/MaterialDesign#2902]
Is possible add the phone icon,  the towel icon and iron icon please? Thanks.

**Comment by Templarian** [comment]
Can you please break up these requests into separate issues. Also there are many phone icons included, so may need to include a picture (can't think of what you would mean if it wasn't one of the others included).

Images can be pasted into comments.

**Comment by PeterShaggyNoble** [comment]
Please search the existing issues first, as well; we definitely have an open request for `iron` and I'm pretty sure we have one for `towel`.

**Comment by eleumas** [comment]
My icons are been request . I close my issue.

**Comment by PeterShaggyNoble** [comment]
See #2752 for `iron` and #2168 or #2374 for `towel`.
