### ISSUE TITLE
Inbox multiple (tray)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2903]
As seen in Gmail app

![tray-multiple](https://cloud.githubusercontent.com/assets/1309249/9059423/15a8dba4-3aaa-11e5-8b04-1c3451fa85bd.png)

[tray-multiple.zip](https://github.com/Templarian/MaterialDesign/files/1804837/tray-multiple.zip)

Related: #486

**Comment by Templarian** [comment]
[![inbox-multiple](https://materialdesignicons.com/icon/inbox-multiple)](https://materialdesignicons.com/icon/inbox-multiple)
