### ISSUE TITLE
Middleware or Middleware Folder

### ISSUE THREAD

**Issue by maaraaji** [Templarian/MaterialDesign#2904]

**Comment by CoDEmanX** [comment]
@maaraaji What kind of middleware? Please post example icons if possible.

**Comment by MrGrigri** [comment]
These could possibly be a representation of middleware. 

![image](https://user-images.githubusercontent.com/4528551/37530146-8e5a8756-28fe-11e8-88f4-c466a223e6c6.png) ![image](https://user-images.githubusercontent.com/4528551/37530278-cc994aac-28fe-11e8-8d5b-65990df2187d.png)

**Comment by maaraaji** [comment]
Thank you very much for the response & making progress on my request. If we have the above mentioned icon on top of a folder icon, I hope it will be a perfect one. I am looking for an folder icon representation to group the middleware classes (ex. React Thunk like middleware or Express js next) and to use it in VS Code's material icon folder themes.

**Comment by goyney** [comment]
[![middleware](https://materialdesignicons.com/icon/middleware)](https://materialdesignicons.com/icon/middleware)[![middleware-outline](https://materialdesignicons.com/icon/middleware-outline)](https://materialdesignicons.com/icon/middleware-outline)
