### ISSUE TITLE
Bag, Grab Bag, Back Pack, Ruck Sack

### ISSUE THREAD

**Issue by rowex099** [Templarian/MaterialDesign#2905]
No real bag centric iconography here. Would love some variety around a "bag" theme.

**Comment by Templarian** [comment]
Paper grocery bag with handles **or** like a bag of gold aka sack design?

**Comment by PeterShaggyNoble** [comment]
We have a couple of open issues for different types of bags including #338, #1136 and #2473. We also have one for a money bag that I can't seem to find at the moment.

**Comment by rowex099** [comment]
I'm thinking more of a backpack. I was able to find a money bag but that's too specific. I'm looking for the generic idea of a bag you carry something around in. Backpack is pretty gender neutral, purses tend to not be but could still be useful.

**Comment by PeterShaggyNoble** [comment]
Thanks for the clarification; this would be a duplicate of #1136, so.
