### ISSUE TITLE
Mortgage or rent

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#2907]
A mortgage or rent icon.
![image](https://user-images.githubusercontent.com/18645219/37377382-f54df282-26ff-11e8-91b2-56baed27bb9e.png)

[Download link](https://github.com/Templarian/MaterialDesign/files/1809190/icon.zip)

**Comment by Templarian** [comment]
[![home-currency-usd](https://materialdesignicons.com/icon/home-currency-usd)](https://materialdesignicons.com/icon/home-currency-usd)

By the way this may not make it to a release. Also tweaked the vector to be more pixel perfect (still not perfect, but close).

**Comment by Croutonix** [comment]
2px strikethrough is definitively better, but yours got ugly curves in the middle of the $.

**Comment by Templarian** [comment]
Fixed it, the preview above should have updated.
