### ISSUE TITLE
Car insurance or security

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#2908]
![image](https://user-images.githubusercontent.com/18645219/37377880-ecbdee62-2702-11e8-86ea-65c3a28cf952.png)

[Download link](https://github.com/Templarian/MaterialDesign/files/1809225/icon.zip)

**Comment by Croutonix** [comment]
What about this:
![image](https://user-images.githubusercontent.com/18645219/37401503-9b28c7b4-275e-11e8-9445-94c1a5aba145.png)

**Comment by CoDEmanX** [comment]
Left one works better for me. Could you do a variant of it with rectangle shaped tires (no rounding)?

**Comment by Croutonix** [comment]
The left one is definitively better when icon is large but for the smallest one I prefer the one on the right.
[![image](https://user-images.githubusercontent.com/18645219/37429634-526896b0-27a6-11e8-8a39-f8b01fd1e4ec.png)](https://github.com/Templarian/MaterialDesign/files/1813005/icon.zip)
Rounded tires is better I think.

**Comment by CoDEmanX** [comment]
I agree, rounded works better. Thanks for the try nonetheless.

**Comment by CoDEmanX** [comment]
@Templarian `car-insurance-1` LGTM

**Comment by goyney** [comment]
[![shield-car](https://materialdesignicons.com/icon/shield-car)](https://materialdesignicons.com/icon/shield-car)

This one, unfortunately, does not work in an `-outline` variant.
