### ISSUE TITLE
Strava

### ISSUE THREAD

**Issue by dbybanez** [Templarian/MaterialDesign#2909]
Would it be possible to create a Strava logo icon? https://www.strava.com/

![image](https://user-images.githubusercontent.com/1309249/37431987-249e1396-27d7-11e8-938e-9a90896aa376.png)

Thanks.

**Comment by PeterShaggyNoble** [comment]
Thanks for the request. Do you have any data on the number of active users Strava has, to help us determine if it meets our criteria for adding brand icons?

**Comment by PeterShaggyNoble** [comment]
Brand assets are [here](https://blog.strava.com/press/assets/).

**Comment by RobRum** [comment]
Strava doesn't release exact user count figures, but has "[10's of millions of users](http://uk.businessinsider.com/interview-strava-ceo-james-quarles-social-network-2017-12)" and "[gains a million new members every 45 days](https://www.theverge.com/2017/5/2/15511118/strava-fitness-tracking-app-athlete-posts-social-network)" according to company interviews.

[](url)

**Comment by Templarian** [comment]
[![strava](https://materialdesignicons.com/icon/strava)](https://materialdesignicons.com/icon/strava)

**Comment by macx** [comment]
Strava is THE social platform for Athletes worldwide, its Icon is missing in this library. Any reasons, @Templarian? Could you please reopen this issue?

**Comment by JapanYoshi** [comment]
@macx MDI has since removed most brand icons. Try SimpleIcons instead.

**Comment by Templarian** [comment]
@macx If we wouldn't get a lot of push back I would have removed all the social media icons in 6.0. Right now it's just easier to not let anymore get in. We forgot to remove `telegram` and we already got a lot of push back in #5409.

Stava is awesome, and SimpleIcons includes all these in similar packaged formats (JS, webfont, etc) and all their competitors. This way we're not being selective.

**Comment by macx** [comment]
Yes, makes sense. Thanks for reporting.
