### ISSUE TITLE
Remote desktop

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2911]
![remote-desktop](https://cloud.githubusercontent.com/assets/1309249/13510220/e20960d8-e18f-11e5-9cc3-f28d400230c7.png) [remote-desktop.zip](https://github.com/Templarian/MaterialDesign/files/1811331/remote-desktop.zip)

Ref: #369

**Comment by Templarian** [comment]
[![remote-desktop](https://materialdesignicons.com/icon/remote-desktop)](https://materialdesignicons.com/icon/remote-desktop)
