### ISSUE TITLE
LDAP / protected folder

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2912]
![image](https://user-images.githubusercontent.com/1309249/37406386-56411712-2797-11e8-8ae9-b2de4c12b945.png) [folder-key.zip](https://github.com/Templarian/MaterialDesign/files/1811350/folder-key.zip)

Or combined with a networked folder, but a bit too detailed IMO:

![network-folder-key](https://user-images.githubusercontent.com/1309249/37406560-bd00ae22-2797-11e8-820a-dfe435fb4652.png) [network-folder-key.zip](https://github.com/Templarian/MaterialDesign/files/1811384/network-folder-key.zip)

Ref: #369

**Comment by Templarian** [comment]
[![folder-key](https://materialdesignicons.com/icon/folder-key)](https://materialdesignicons.com/icon/folder-key) [![folder-key-network](https://materialdesignicons.com/icon/folder-key-network)](https://materialdesignicons.com/icon/folder-key-network)
