### ISSUE TITLE
NAS device

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2913]
Inspired by how some Synology NAS models look like

![nas](https://user-images.githubusercontent.com/1309249/37407518-2046ad72-279a-11e8-8284-9ebb0fdcdbee.png) [nas.zip](https://github.com/Templarian/MaterialDesign/files/1811450/nas.zip)

**Comment by PeterShaggyNoble** [comment]
See also #698, #2712 and #2842.

**Comment by Templarian** [comment]
[![nas](https://materialdesignicons.com/icon/nas)](https://materialdesignicons.com/icon/nas)

Alias for `network-attached-storage` also.
