### ISSUE TITLE
Update icon "group"

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2914]
Make the rectangles square. Looks cleaner IMO:

![group-objects](https://user-images.githubusercontent.com/1309249/37408338-276bfaec-279c-11e8-9d63-ff73f56ef2fc.png) [group-objects.zip](https://github.com/Templarian/MaterialDesign/files/1811507/group-objects.zip)

Current:

![group](https://materialdesignicons.com/icon/group)

**Comment by PeterShaggyNoble** [comment]
Overlay for comparison:

![group](https://user-images.githubusercontent.com/15157491/37408640-6913a65a-2794-11e8-924d-2fa6f5d3784b.png)

**Comment by Templarian** [comment]
[![group](https://materialdesignicons.com/icon/group)](https://materialdesignicons.com/icon/group)
