### ISSUE TITLE
Update icon "percent"

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2915]
Thicker diagonal line to match the visual weight of the circles better:

![percent](https://user-images.githubusercontent.com/1309249/37408585-ab9246aa-279c-11e8-8b43-22a2c2ce7895.png) [percent.zip](https://github.com/Templarian/MaterialDesign/files/1811527/percent.zip)

Current:

![percent](https://materialdesignicons.com/icon/percent)

**Comment by PeterShaggyNoble** [comment]
Overlay for comparison:

![percent](https://user-images.githubusercontent.com/15157491/37408852-dcfdf70a-2794-11e8-80de-1e81ecbbd1a6.png)

Personally, though, I've always preferred the style of our `margin` icon.

**Comment by CoDEmanX** [comment]
Hm yeah, margin without arrow head would match the percent symbol on my keyboard much better.

The current percent symbol is somewhat constructed geometrically. Maybe update this one and add the other as variant?

**Comment by Templarian** [comment]
[![percent](https://materialdesignicons.com/icon/percent)](https://materialdesignicons.com/icon/percent)

**Comment by CoDEmanX** [comment]
@PeterShaggyNoble You still want that variant?

**Comment by PeterShaggyNoble** [comment]
I think it looks better, yeah, what do the rest of you think?

**Comment by Templarian** [comment]
Updated the margin icon to be more geometric.

**Comment by CoDEmanX** [comment]
@Templarian Peter actually liked the original margin and wanted a variant of it without the arrow head as percent-variant 🙈 

![image](https://user-images.githubusercontent.com/1309249/37746038-7da53e6e-2d78-11e8-8c43-d063ecf0ccd9.png)

So probably like this:

![percent-variant](https://user-images.githubusercontent.com/1309249/37746262-ac85d67a-2d79-11e8-9f1d-7fd730bf03ad.png) [percent-variant.zip](https://github.com/Templarian/MaterialDesign/files/1835776/percent-variant.zip)
