### ISSUE TITLE
Update icons "umbrella" and "umbrella-outline"

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2916]
Two more pixels at the end of the handle:

![umbrella](https://user-images.githubusercontent.com/1309249/37409157-e77f8ac8-279d-11e8-9f38-08cfb7a0a844.png) ![umbrella-outline](https://user-images.githubusercontent.com/1309249/37409158-e7c3636a-279d-11e8-824f-8deb83aaab44.png) [umbrella.zip](https://github.com/Templarian/MaterialDesign/files/1811567/umbrella.zip)

![image](https://user-images.githubusercontent.com/1309249/37410478-094fc3a4-27a1-11e8-935f-ef33b11c2fe6.png)
![umbrella-outline 1](https://user-images.githubusercontent.com/1309249/37410669-602233ce-27a1-11e8-8f62-7794b33a5eef.png)

**Comment by Templarian** [comment]
[![umbrella](https://materialdesignicons.com/icon/umbrella)](https://materialdesignicons.com/icon/umbrella) [![umbrella-outline](https://materialdesignicons.com/icon/umbrella-outline)](https://materialdesignicons.com/icon/umbrella-outline)
