### ISSUE TITLE
Update icon "history"

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2917]
Updated by Google: https://material.io/icons/#ic_history

![ic_history_24px](https://user-images.githubusercontent.com/1309249/37409517-cd2bd306-279e-11e8-9bee-d84ca451067c.png) [ic_history_24px.zip](https://github.com/Templarian/MaterialDesign/files/1811596/ic_history_24px.zip)

Current:

![history](https://materialdesignicons.com/icon/history)

**Comment by Templarian** [comment]
[![history](https://materialdesignicons.com/icon/history)](https://materialdesignicons.com/icon/history)
