### ISSUE TITLE
Update icons "tab", "tab-plus" and "tab-unselected"

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2918]
`tab` and `tab-unselected` were updated upstream. I included an update for our the plus icon as well:

![ic_tab_plus_24px](https://user-images.githubusercontent.com/1309249/37410948-f15dbe4e-27a1-11e8-9fd5-95fb855a05e4.png) ![image](https://user-images.githubusercontent.com/1309249/37410980-01e3a742-27a2-11e8-8a92-76a493258d3e.png) ![image](https://user-images.githubusercontent.com/1309249/37411008-121a06ce-27a2-11e8-8d4d-eabd175b4828.png) [ic_tab.zip](https://github.com/Templarian/MaterialDesign/files/1811709/ic_tab.zip)

![image](https://user-images.githubusercontent.com/1309249/37411303-ce05ae4c-27a2-11e8-96e1-ecc8ef2723de.png)
![image](https://user-images.githubusercontent.com/1309249/37411169-74f112f6-27a2-11e8-84b2-369f24dcb2ee.png)
![image](https://user-images.githubusercontent.com/1309249/37411349-e6f99562-27a2-11e8-9fde-20dbe2541816.png)

**Comment by Templarian** [comment]
[![tab](https://materialdesignicons.com/icon/tab)](https://materialdesignicons.com/icon/tab) [![tab-unselected](https://materialdesignicons.com/icon/tab-unselected)](https://materialdesignicons.com/icon/tab-unselected) [![tab-plus](https://materialdesignicons.com/icon/tab-plus)](https://materialdesignicons.com/icon/tab-plus)
