### ISSUE TITLE
Update icon "fingerprint"

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2919]
We have a re-creation, but Google released the original later:

![image](https://user-images.githubusercontent.com/1309249/37412578-78676176-27a5-11e8-9ee8-32c1a9862a63.png) [ic_fingerprint_24px.zip](https://github.com/Templarian/MaterialDesign/files/1811813/ic_fingerprint_24px.zip)

![image](https://user-images.githubusercontent.com/1309249/37412496-5078aec2-27a5-11e8-969c-bc9724115aaa.png)

Ref: https://github.com/Templarian/MaterialDesign/issues/420#issuecomment-341151813

**Comment by Templarian** [comment]
[![fingerprint](https://materialdesignicons.com/icon/fingerprint)](https://materialdesignicons.com/icon/fingerprint)
