### ISSUE TITLE
calendar-question

### ISSUE THREAD

**Issue by epelc** [Templarian/MaterialDesign#292]
It'd be nice if there was a calendar with a question mark for unknown dates.

- [ ] calendar-question

**Comment by md5** [comment]
I'd like to have this icon as well. I think something like `.calendar-check` with a question mark instead of a check would work well.

**Comment by md5** [comment]
I grabbed the question mark from `.help-outline` and threw it into `.calendar-check` here: https://gist.github.com/md5/f7c35f17532975d8bf4201f735200e9e

I think the question mark should be a bit thicker, but it seems like a reasonable start.

**Comment by CoDEmanX** [comment]
Closing it here, because there will be such an icon for RVSP'ing: #1412
