### ISSUE TITLE
Update icon "playlist-remove"

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2920]
The gap should not be as wide as it currently is:

![playlist-remove](https://user-images.githubusercontent.com/1309249/37413946-629b30a4-27a8-11e8-8d07-e32f9f6f0ed2.png) [playlist-remove.zip](https://github.com/Templarian/MaterialDesign/files/1811899/playlist-remove.zip)

![image](https://user-images.githubusercontent.com/1309249/37413894-48c6b32e-27a8-11e8-91e2-19b6d206812f.png)

**Comment by Templarian** [comment]
[![playlist-remove](https://materialdesignicons.com/icon/playlist-remove)](https://materialdesignicons.com/icon/playlist-remove)
