### ISSUE TITLE
Braille

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2921]
This is actually the drag handle found in the Google Keep app:

![image](https://user-images.githubusercontent.com/1309249/37433249-71423ff2-27db-11e8-90a1-ea6048f4b715.png)

Ref: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-188516176

**Comment by PeterShaggyNoble** [comment]
Google call it `drag indicator` in the extended icon set.

**Comment by JapanYoshi** [comment]
Combine this with a finger icon?

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/40729555-de07255e-63e9-11e8-9bed-969aa95e8cf3.png)

[braille.zip](https://github.com/Templarian/MaterialDesign/files/2054526/braille.zip)

**Comment by Templarian** [comment]
[![braille](https://materialdesignicons.com/icon/braille)](https://materialdesignicons.com/icon/braille)]
