### ISSUE TITLE
Problems using typeface file

### ISSUE THREAD

**Issue by rcherem** [Templarian/MaterialDesign#2923]
As an interface designer, I often use this project typeface file in softwares such as Illustrator, Photoshop and Figma. In this situation, I always face two problems:

1. **Character mapping usually changes with each version.** Whenever I install an updated typeface file, the icons change and hence I need to convert them to vector or replace all the characters in a project. This could be improved if character mapping was maintained through versions.
2. **No character in the cheatsheet.** To find some icon, I'm forced to search visually using Adobe Illustrator's character navigation, without the help of tags and names. This could be improved if there were on the cheat sheet the icon character (instead of just svg), ready to be copied and pasted.

Despite these issues, I really love the project and am grateful, because it has greatly facilitated my work. Thank you!

**Comment by Templarian** [comment]
1. Codepoints are fixed across version releases.
2. https://cdn.materialdesignicons.com/2.1.99/ Probably not obvious, if you click on the icon itself it will copy the character.

We're solving this on the new site with the ability to, copy the character, codepoint, or SVG vector path for the quick ability to paste into your favorite application.

The minute figma allows 3rd party integrations we'll be creating a first party extension/addon.

**Comment by Templarian** [comment]
Should mention the preview above on the CDN will be getting a search feature in the next release ideally (with alias support, and later on tag). We're trying to make offline support a little more friendly.

https://github.com/Templarian/MaterialDesign-Site Is the repo for the new site under development.

**Comment by rcherem** [comment]
That's a great help: https://cdn.materialdesignicons.com/2.1.99/ 

Thank u!

**Comment by Templarian** [comment]
The new site will make this all much more obvious, we're doing a lot of planning. We know this is confusing right now. The feedback helps a lot concrete this planning was needed.

Thanks!

**Comment by PeterShaggyNoble** [comment]
That cheatsheet is included with the webfont as `preview.html`, by the way, if you need an offline copy.

You might also find [my sandbox](https://petershaggynoble.github.io/MDI-Sandbox/) of use as a stopgap, while the changes & updates Templarian mentioned are being worked on.
