### ISSUE TITLE
Mining icon

### ISSUE THREAD

**Issue by Epiqa** [Templarian/MaterialDesign#2924]
Hi, we work at mining industry and i was looking for a icon in material design, i think is a good idea because mining is a big industry

**Comment by PeterShaggyNoble** [comment]
Would `shovel` or `worker` suit your needs? If not, could you provide an example of what you're looking for?

**Comment by Epiqa** [comment]
worker or pickaxe i think! thanks for a quickly answer

**Comment by PeterShaggyNoble** [comment]
See #2461 for a request for a pickaxe.

**Comment by Epiqa** [comment]
oh, my bad, but a worker would be a perfect choise too, thanks!

**Comment by PeterShaggyNoble** [comment]
Oop, sorry, my first comment wasn't clear: `shovel` & `worker` exist already. I think we have an open request for a hard hat icon, too, if that'd be of use?

[![](https://materialdesignicons.com/icon/shovel)](https://materialdesignicons.com/icon/shovel) [![](https://materialdesignicons.com/icon/worker)](https://materialdesignicons.com/icon/worker)

**Comment by CoDEmanX** [comment]
Pickaxe would still be a nice addition 
![image](https://user-images.githubusercontent.com/1309249/37627817-939f58e2-2bd6-11e8-9a41-a42d80e4b279.png)

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #2461.

@Epiqa, if there are any other mining related icons you'd like to request, other than those discussed here, please create a new issue for each one.
