### ISSUE TITLE
network-console

### ISSUE THREAD

**Issue by BornToBeRoot** [Templarian/MaterialDesign#2925]
Hi,

maybe a bit specific, but it would be great having a modern putty icon.

![image](https://user-images.githubusercontent.com/16019165/37541889-85554d22-295c-11e8-9356-e030e1ea5c9a.png)

Greetings

**Comment by Templarian** [comment]
Probably could use one of the `lan-*` icons. Just need to flip it horizontally.

**Comment by GreenTurtwig** [comment]
Or #2855

**Comment by BornToBeRoot** [comment]
@Templarian I already used the LanConnect icon for some other stuff...

@GreenTurtwig I think can take the SSH icon. 

But maybe it would still be great having this icon.

**Comment by MrGrigri** [comment]
This is a lot of detail for a 24 x 24-pixel icon with a minimum of 2-pixel lines.

**Comment by MrGrigri** [comment]
I would personally use `console`.

![console](https://materialdesignicons.com/icon/console)

**Comment by MrGrigri** [comment]
@Templarian, what about a `network-console`?

![image](https://user-images.githubusercontent.com/4528551/37542831-20e5b2d2-2925-11e8-8cee-bd223118ce3f.png)

**Comment by MrGrigri** [comment]
I'm going to change the name of this issue to `network-console`. @BornToBeRoot, if this still doesn't work please let us know.

[network-console.zip](https://github.com/Templarian/MaterialDesign/files/1825422/network-console.zip)

**Comment by BornToBeRoot** [comment]
I asked for a PuTTY icon because i would use it in my application:

![image](https://user-images.githubusercontent.com/16019165/37622549-3bf92320-2bc2-11e8-8d61-c3eac8cd5bc7.png)

I currently use another icon from the mahapps.iconpacks (where your libary is included).
https://github.com/MahApps/MahApps.Metro.IconPacks

I think i will switch to this icon: https://github.com/Templarian/MaterialDesign/issues/2855 when it's available.

**Comment by Templarian** [comment]
[![console-network](https://materialdesignicons.com/icon/console-network)](https://materialdesignicons.com/icon/console-network)

**Comment by Templarian** [comment]
Closed 2855.
