### ISSUE TITLE
Fire engine icon

### ISSUE THREAD

**Issue by leMaik** [Templarian/MaterialDesign#2927]
It'd be great to have an icon for a fire engine :fire_engine: , since there already is one for the ambulance :ambulance:

I don't know what it should look like, though. Maybe like the ambulance but with a rolled up tube instead of the +? :thinking:

**Comment by Croutonix** [comment]
Here's what I tried:
![image](https://user-images.githubusercontent.com/18645219/37560690-65d40936-2a13-11e8-8b9b-7f2d6f152689.png)![image](https://user-images.githubusercontent.com/18645219/37560662-f7c734f4-2a12-11e8-9fbf-b285709a0812.png)
The first one is better I think. Neither are pixel perfect, but not far from it.

[Download link](https://github.com/Templarian/MaterialDesign/files/1822169/icons.zip)

**Comment by Templarian** [comment]
The first one is great. The second one would be more of a transporting flammable materials (which I don't think it needed).

**Comment by Templarian** [comment]
[![fire-truck](https://materialdesignicons.com/icon/fire-truck)](https://materialdesignicons.com/icon/fire-truck)

**Comment by leMaik** [comment]
@Croutonix Wow, that was fast. Thank you _very_ much, the icon is great! :fire_engine:
