### ISSUE TITLE
Speaker

### ISSUE THREAD

**Issue by tomhv9** [Templarian/MaterialDesign#2928]
I cant find the icon for speaker when making a call

**Comment by Templarian** [comment]
Do you have an example of what this would look like?

**Comment by tomhv9** [comment]
Example attached for speaker icon

Tom

**Comment by Templarian** [comment]
@tomhv9 Emails replies do not work, you have to use GitHub's comment box.

**Comment by tomhv9** [comment]
Attachment didn't work, it looks like a speaker with some sound waves coming off it...like this 🔊

**Comment by Templarian** [comment]
`volume-high` is the icon you're looking for in the set.

[![volume-high](https://materialdesignicons.com/icon/volume-high)](https://materialdesignicons.com/icon/volume-high)

Going to keep this opened since we should probably add some aliases for `audio`/`speaker` to these.

**Comment by PeterShaggyNoble** [comment]
`speakerphone` and `speakerphone-off` for `volume-off`, maybe?

**Comment by GreenTurtwig** [comment]
`phone-in-talk` maybe?

**Comment by tomhv9** [comment]
Volume high is the one... Thanks everyone

**Comment by MrGrigri** [comment]
I'm going to close this then as the issue appears to be resolved.

**Comment by MrGrigri** [comment]
Reopening to add aliases to the following:

- [ ] volume-low: `audio`, `speaker`
- [ ] volume-medium:  `audio`, `speaker`
- [ ] volume-high: `audio`, `speaker`
- [ ] volume-off: `audio-off`, `speaker-off`

**CONTRIBUTORS** please amend the list.

**Comment by Templarian** [comment]
That should be fine for now, I think most will be searching for speakerphone. So I added that to `volume-high`.
