### ISSUE TITLE
Information request: Convert custom icons to ttf

### ISSUE THREAD

**Issue by halirutan** [Templarian/MaterialDesign#2931]
For [JabRef](https://github.com/JabRef/jabref), we need some icons that are not available. I created them with the MaterialDesign template that is available for Illustrator. Now, I have a bunch of SVG files and I used [Glypher](https://glyphter.com/) to turn them into a TTF. The process works nicely and by implementing the `GlyphIcon` interface, we could easily include them in the application.

However, the size of the icons is a tiny bit off compared to the MatericalDesign icons. I looked at the TTF you provide and it says in the comments

> Generated by svg2ttf from Fontello project.

I installed this, but it seems my Illustrator SVG files are not having the `<font>` tag. Additionally, I have each glyph in a separate SVG like you have on the GitHub repository. `svg2ttf` however seems to expect an overall SVG that contains all glyphs.

**Question:** Can you elaborate on how exactly you convert the SVG files (or artboards in Illustrator) to the TTF that is provided?

**Comment by Templarian** [comment]
https://github.com/sapegin/grunt-webfont

We actually use this to build the various webfonts. The SVG paths in the repo here are not ideal for building the webfont. You would want to use https://github.com/Templarian/MaterialDesign-SVG

I would suggest just using something like icomoon.io to generate things as they make it really easy.

**Comment by halirutan** [comment]
Thank you for the answer. After a lot of trial and error, I found the issue. Using icomoon (instead of glypher) and setting the *Grid* to 24, as suggested on your webpage, solved the problem. If someone else runs into trouble, I have published a [small tutorial](https://github.com/JabRef/jabref/wiki/Cusome-SVG-Icons-for-JabRef) in our wiki about the process.

**Comment by Templarian** [comment]
Awesome, I've book marked this to look at as we build out the guide for building the webfont locally. Ideally we're going to provide an NPM package that does this all, but it will be a bit. We've found icomoon to be a great work around so far.

https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/guide-webfont.md

**Comment by halirutan** [comment]
@Templarian A guide and especially a package for doing this automatically would be awesome. As soon as you have something working, I would highly appreciate if you would ping me somehow so that I get a notification.
