### ISSUE TITLE
icons for home automation, lamps and lights

### ISSUE THREAD

**Issue by hulkhaugen** [Templarian/MaterialDesign#2932]
If anyone is up for it, i would like to see the following icons:
- Floor lamp, like the existing lamp icon, just taller and with 3 legs for instance, want it to stand out from the regular lamp.
- Wall lamp, just a simple wall mounted lamp.
- Downlights/spotlights, i'm imagining a circle from an angle with three beams going down.
- LED lights in a row, suggesting LED strips or decorative x-mas lights

**Comment by GreenTurtwig** [comment]
#1712 has the the first three and the fourth already exists.  
  
[![](https://materialdesignicons.com/icon/led-strip)](https://materialdesignicons.com/icon/led-strip)

**Comment by PeterShaggyNoble** [comment]
The fourth might also be covered by #2772

**Comment by hulkhaugen** [comment]
Hmm, so they are made, but are not a part of the mdi package? Does that mean i would have to add them manually, like put the icon in a local folder and reference it. Or are they in a que to be added to the mdi package?

**Comment by PeterShaggyNoble** [comment]
That would be a "yes" on both counts; they *are* pending addition and, in the meantime, you *could* use the SVGs included in #1712.

**Comment by Templarian** [comment]
I'll get these added shortly, tracking them as the next ones I'll add tonight so they get into this next release.
