### ISSUE TITLE
Sausage

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#2933]
Saw this in a shopping center:

![image](https://user-images.githubusercontent.com/1309249/37627575-57679c0a-2bd5-11e8-9bf8-670f093751e0.png)

**Comment by Croutonix** [comment]
Here's what I tried:
![image](https://user-images.githubusercontent.com/18645219/37689557-2990f64e-2c7c-11e8-9bfa-d2631bf97c05.png)![image](https://user-images.githubusercontent.com/18645219/37689762-5d196e28-2c7d-11e8-9d1a-0c4a94f7ac16.png)
Second one is probably better at small size.

And hot-dog was missing too:
![image](https://user-images.githubusercontent.com/18645219/37689752-4cb8588c-2c7d-11e8-94c8-9964d44b9896.png)

[Download link](https://github.com/Templarian/MaterialDesign/files/1831692/icons.zip)

**Comment by Templarian** [comment]
Probably `sausage-2`, but I think we can do better with the hot dog. Lets open another issue for this one.

[![sausage](https://materialdesignicons.com/icon/sausage)](https://materialdesignicons.com/icon/sausage)

**Comment by SvenVdv** [comment]
@Templarian Hey Austin, I'm using the sausage icon for our fermentation project. Could you also add a sausage-off (like the cheese-off) icon for this one? 🙏 🙇

**Comment by goyney** [comment]
@SvenVdv Can you please open a new request to track that?
