### ISSUE TITLE
filter icon like this:

### ISSUE THREAD

**Issue by protonhs** [Templarian/MaterialDesign#2934]
Filter icon or parameter icon
https://www.iconfinder.com/icons/325048/filter_icon#size=256

**Comment by PeterShaggyNoble** [comment]
That's `tune-vertical` and we also have a horizontal variant called `tune`.

[![tune](https://user-images.githubusercontent.com/15157491/37647901-64502b62-2c25-11e8-9426-26bb1708d614.png)](https://materialdesignicons.com/icon/tune) [![tune-vertical](https://user-images.githubusercontent.com/15157491/37647953-81e494f6-2c25-11e8-9f87-4911c65982c3.png)](https://materialdesignicons.com/icon/tune-vertical)

**Comment by protonhs** [comment]
Thank you!
