### ISSUE TITLE
Proxy Icons

### ISSUE THREAD

**Issue by Celebrated** [Templarian/MaterialDesign#2935]
Hello,
I was wanted to find some Proxy Icons like (HTTP/Socks5) but i failed!
Would be useful and are really missing icons!

Thanks!

**Comment by PeterShaggyNoble** [comment]
Do you have examples of what you're looking for?

**Comment by Celebrated** [comment]
Nah! Unfortunately, i have no idea for that

**Comment by PeterShaggyNoble** [comment]
Some suggestions of existing icons after a quick Google search:

- `database`
- `door-open`
- `lan`
- `lan-connect`
- `lan-pending`
- `lock`
- `server`
- `server-network`
- `vpn`
- `web`

If none of those suit your needs then we really are going to need some examples of what you are looking for.

**Comment by Celebrated** [comment]
@PeterShaggyNoble Great suggestions!

- lan-connect
- server-network
These icons seems good to me
