### ISSUE TITLE
Event Plus Icon

### ISSUE THREAD

**Issue by eduardoalcantara** [Templarian/MaterialDesign#2936]
I would like to suggest an Event icon with a plus inside. For when user needs to create new event.

**Comment by PeterShaggyNoble** [comment]
We already have a `calendar-plus` icon. Or were you looking for something else? Can you provide an example, if so?

**Comment by Templarian** [comment]
Added an alias called `event-plus` to make searching easier.

**Comment by Templarian** [comment]
Added `event-*` to all the `calendar-*` icons.
