### ISSUE TITLE
Variant on editor border icons

### ISSUE THREAD

**Issue by BrainFeeder** [Templarian/MaterialDesign#2937]
I'ld like to suggest a variant on the `border-top/right/bottom/left` icons.
The existing icons all have the dots in the middle (inner borders). It might come in handy to have them without the inner border dots. (e.g. In our project we are using them to add/remove borders to/from divs)

**Comment by Templarian** [comment]
[![border-top-variant](https://materialdesignicons.com/icon/border-top-variant)](https://materialdesignicons.com/icon/border-top-variant) [![border-right-variant](https://materialdesignicons.com/icon/border-right-variant)](https://materialdesignicons.com/icon/border-right-variant) [![border-bottom-variant](https://materialdesignicons.com/icon/border-bottom-variant)](https://materialdesignicons.com/icon/border-bottom-variant) [![border-left-variant](https://materialdesignicons.com/icon/border-left-variant)](https://materialdesignicons.com/icon/border-left-variant) [![border-none-variant](https://materialdesignicons.com/icon/border-none-variant)](https://materialdesignicons.com/icon/border-none-variant) [![border-all-variant](https://materialdesignicons.com/icon/border-all-variant)](https://materialdesignicons.com/icon/border-all-variant)

**Comment by BrainFeeder** [comment]
Awesome :+1:

**Comment by PeterShaggyNoble** [comment]
You can track the next release [here](https://github.com/Templarian/MaterialDesign/issues/2872) and [here](https://github.com/Templarian/MaterialDesign/milestone/14).
