### ISSUE TITLE
Lungs & Stomach

### ISSUE THREAD

**Issue by iamsarker** [Templarian/MaterialDesign#2939]
Icon request for:

- [ ] Lungs
- [ ] Stomach
- [x] Blood - Included as `water`. See also #473.
- [x] Doctor - Included as `doctor`

![lungs](https://user-images.githubusercontent.com/5415001/37698109-2caf429c-2d0b-11e8-9a70-5589fb7e9e12.png) ![stomach](https://user-images.githubusercontent.com/5415001/37698094-1498d006-2d0b-11e8-917b-4062507309a7.png) ![blood](https://user-images.githubusercontent.com/5415001/37698126-429c708e-2d0b-11e8-85cd-4fde6d61f637.png)

**Comment by PeterShaggyNoble** [comment]
`water` should cover blood (but see also #473 and #1398) and `doctor` is being tracked in #2245.

**Comment by iamsarker** [comment]
please alias

**Comment by goyney** [comment]
Here's an attempt at the missing two:
![image](https://user-images.githubusercontent.com/1015040/61600701-fcee5a00-abff-11e9-8787-03bbd336566b.png)![image](https://user-images.githubusercontent.com/1015040/61600707-0677c200-ac00-11e9-8a08-10db96d4e2ef.png)

[organs.zip](https://github.com/Templarian/MaterialDesign/files/3415376/organs.zip)

**Comment by goyney** [comment]
[![lungs](https://materialdesignicons.com/icon/lungs)](https://materialdesignicons.com/icon/lungs)[![stomach](https://materialdesignicons.com/icon/stomach)](https://materialdesignicons.com/icon/stomach)
