### ISSUE TITLE
Mountain Icon

### ISSUE THREAD

**Issue by Zangoran** [Templarian/MaterialDesign#294]
- [ ] Mountain

Preferably Mt. Everest

**Comment by Templarian** [comment]
Would the stock icon `image-filter-hdr` work?

**Comment by Zangoran** [comment]
Yes it would! I had no idea that one existed. Thanks!

**Comment by Templarian** [comment]
Awesome. I'll add an alias to it of `mountain`. That way when people search mountain they will find it.
