### ISSUE TITLE
Replace Linux (penguin)

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2940]
[![](https://user-images.githubusercontent.com/15905797/37719960-2b168766-2d1e-11e8-9802-da10c3ae5617.png)](https://github.com/Templarian/MaterialDesign/files/1833981/linux.zip)

Found at https://getoutline.org

**Comment by Templarian** [comment]
[![linux](https://materialdesignicons.com/icon/linux)](https://materialdesignicons.com/icon/linux)
