### ISSUE TITLE
receiver

### ISSUE THREAD

**Issue by fnolis** [Templarian/MaterialDesign#2941]
I'm thinking of a receiver, like in home theatres and entertainment systems. I would like to use it in a home automation system where I control a receiver.

<img width="306" alt="screen shot 2018-03-21 at 16 36 11" src="https://user-images.githubusercontent.com/866136/37719963-8e3c5e08-2d26-11e8-8461-0abb18f2865b.png">
<img width="204" alt="screen shot 2018-03-21 at 16 41 18" src="https://user-images.githubusercontent.com/866136/37720055-c052c6e8-2d26-11e8-9bae-275965fb1bff.png">
<img width="191" alt="screen shot 2018-03-21 at 16 41 02" src="https://user-images.githubusercontent.com/866136/37720056-c08bfa08-2d26-11e8-8596-7cf705d20731.png">
<img width="196" alt="screen shot 2018-03-21 at 16 40 55" src="https://user-images.githubusercontent.com/866136/37720057-c0a80360-2d26-11e8-8c52-3d630458d51f.png">

**Comment by Templarian** [comment]
The first receiver image would probably work well for a starting point. 0_o

**Comment by MrGrigri** [comment]
Here is my attempt.

![image](https://user-images.githubusercontent.com/4528551/37742904-3927179e-2d2d-11e8-9e03-fd687be8271e.png)

``` XML
<path d="M20,7H4C2.9,7,2,7.9,2,9v6c0,1.1,0.9,2,2,2h1v1c0,0.6,0.4,1,1,1h2c0.6,0,1-0.4,1-1v-1h6v1c0,0.6,0.4,1,1,1h2
c0.6,0,1-0.4,1-1v-1h1c1.1,0,2-0.9,2-2V9C22,7.9,21.1,7,20,7z M14,12.5H4v-3h10V12.5z M18,13c-1.1,0-2-0.9-2-2s0.9-2,2-2s2,0.9,2,2
S19.1,13,18,13z M6,15H4v-1h2V15z M10,15H8v-1h2V15z M14,15h-2v-1h2V15z"/>
```

**Comment by CoDEmanX** [comment]
The circle and the rectangle on its left look washed out at 24px as they are not on grid... What if you make it flatter or taller and place these shapes pixel perfect?

**Comment by PeterShaggyNoble** [comment]
The feet are throwing me a bit; how would it look without them?

**Comment by fnolis** [comment]
I would prefer to have to equally bog circles on each side as this is the most common appearence. One for source and one for volume. (Top and bottom example images)

**Comment by fnolis** [comment]
And the legs should probably be there still but half height

**Comment by fnolis** [comment]
ic... :/ is there an editor or something that I can use to send in own examples and contribute to the content? Guess I have to dig in to the guidelines first anyway.

**Comment by GreenTurtwig** [comment]
@fnolis [Guidelines](https://material.io/guidelines/style/icons.html#icons-system-icons) and you can use [Inkscape](https://inkscape.org) as an editor.

**Comment by MrGrigri** [comment]
Here it is with the on-grid. @fnolis, with regards to the dual radial dials, it looked too much like a car front bumper. And without the feet, it looks like a tape deck. 

![image](https://user-images.githubusercontent.com/4528551/37783225-8ed096ba-2dba-11e8-98c4-de1fd5de4d51.png)


``` SVG
<svg version="1.1" width="24px" height="24px" viewBox="0 0 24 24">
  <path d="M20,7H4C2.9,7,2,7.9,2,9v6c0,1.1,0.9,2,2,2h1v1c0,0.6,0.4,1,1,1h2c0.6,0,1-0.4,1-1v-1h6v1c0,0.6,0.4,1,1,1h2
c0.6,0,1-0.4,1-1v-1h1c1.1,0,2-0.9,2-2V9C22,7.9,21.1,7,20,7z M14,12H4v-2h10V12z M18,13c-1.1,0-2-0.9-2-2s0.9-2,2-2s2,0.9,2,2
S19.1,13,18,13z M6,15H4v-1h2V15z M10,15H8v-1h2V15z M14,15h-2v-1h2V15z"/>
</svg>
```

**Comment by Templarian** [comment]
[![audio-video](https://materialdesignicons.com/icon/audio-video)](https://materialdesignicons.com/icon/audio-video)
