### ISSUE TITLE
tourney_bracket

### ISSUE THREAD

**Issue by jpfgit** [Templarian/MaterialDesign#2942]
This icon would be used along with the other sports icons already present. It would be useful for leading users to tournament schedules, results or brackets. Here's an idea of what I'm requesting. Thanks for your consideration!
![tourney-bracket](https://user-images.githubusercontent.com/37632809/37728715-035362a4-2d09-11e8-89d6-57c7850cbaf3.png)

**Comment by PeterShaggyNoble** [comment]
Would the `sitemap` icon (rotated) suit your needs?

**Comment by jpfgit** [comment]
Yes. I think that could actually work pretty well. Thanks for the suggestion

**Comment by MrGrigri** [comment]
The problem with `sitemap` is it's a three-in one-out flow. I believe we should just add one.

![image](https://user-images.githubusercontent.com/4528551/37742203-3c32b5fe-2d2a-11e8-95bb-42905599733e.png)

**Comment by GreenTurtwig** [comment]
Here's one that doesn't base the design off `sitemap`:
[![](https://user-images.githubusercontent.com/15905797/38460186-e12790f4-3aac-11e8-87e2-c0e7175efa8d.png)](https://github.com/Templarian/MaterialDesign/files/1886718/tournament.zip)

**Comment by Templarian** [comment]
[![tournament](https://materialdesignicons.com/icon/tournament)](https://materialdesignicons.com/icon/tournament)
