### ISSUE TITLE
Transport consolidation icons

### ISSUE THREAD

**Issue by kheijboer** [Templarian/MaterialDesign#2943]
Add consolidation icons for the Transport section.
For example:
![master](https://user-images.githubusercontent.com/37655311/37761656-8cd3175c-2dba-11e8-8c35-1aa8d339a365.png)  Master
![house](https://user-images.githubusercontent.com/37655311/37761658-8cf1f636-2dba-11e8-9c0b-65fa019aaf6c.png)  House
![consolidation](https://user-images.githubusercontent.com/37655311/37761659-8d207808-2dba-11e8-8c07-8496d26c8512.png)  Consolidation

**Comment by PeterShaggyNoble** [comment]
Can you provide a bit more context on what these might be used for?

**Comment by kheijboer** [comment]
Hello,



We are developing software for forwarding and transportation. In our
software system we need some icons for consolidation. I have copied part of
our help text to help you understand what consolidation is:

* Consolidation*: If the Consolidation tab is available, consolidation
(groupage) is available in your system. It is possible to combine multiple
shipment legs into one Master shipment. When you click this tab, the
Consolidation planning form is opened.



* Master*: A Master shipment contains one or more House shipments. The
Master shipment can be addressed from one agent to another. These
consolidated shipments are ultimately the least expensive method of
shipping for the individual shippers and consignees. The duration of
transportation to the final destination may well be considerable longer
when compared to a direct shipment, this is because the agent needs to
accumulate several shipments with the same or similar places of departure
and destination in order to build a greater volume and weight which results
in a lower price per chargeable kilo from the carrier. Most agents offer a
midweek and a weekend service consolidation. A house shipment delivered to
the airline on a Thursday, for example, will wait until the weekend
consolidation, shipping on a Saturday or Sunday.



* House*: A House shipment can be combined with other shipments into a
Consolidated shipment (Master). The goal of creating house shipments is to
consolidate multiple house shipments under a single master shipment,
because the greater the combined total weight/volume of the shipments, the
more favorable the rates for transport costs. The name House shipment
derives from the fact that the shipment is an "in-house transport" and will
be processed between shipper and agents and consignee.





Another example of consolidation definitions can be found on (there are
many more):

https://www.globalnegotiator.com/international-trade/dictionary/consolidated-shipment/

http://www.businessdictionary.com/definition/consolidated-shipment.html

http://blog.chrobinson.com/global-transportation/freight-consolidation-bridging-gap-ltl-full-truckload-2/



In the Material design icons we could not find any icons that we could use
for this, that’s why my request.





Met vriendelijke groeten / With best regards,

Karin Heijboer
*Consultancy*



*[image: image001]Cargo Data Systems bv*
Emmerblok 33
4751 XE Oud Gastel
The Netherlands
(+31 165 56 56 67
› karin@cds-nl.com <support@cds-nl.com>
ü www.cds-nl.com
Chamber of Commerce: 34073371

We trade according to our standard delivery conditions
<http://www.cds-nl.com/voorwaarden/FENIT-AV-2003-ENG.pdf>. (Copy available
upon request)
All prices are in Euro's excluding VAT and installation, except where
mentioned otherwise.

The information in this e-mail is confidential and is legally privileged.
It is intended solely for the addressee. Access to this e-mail by anyone
else is unauthorised. If you are not the intended recipient, any
disclosure, copying, distribution or any action taken or omitted in
reliance on it, is prohibited and may be unlawful. Whilst all reasonable
steps are taken to ensure the accuracy and integrity of information and
data transmitted electronically and to preserve the confidentiality there
of, no liability or responsibility whatsoever is accepted if information or
data is, for whatever reason, corrupted or does not reach its intended
destination.





*Van:* Peter Noble <notifications@github.com>
*Verzonden:* Thursday, March 22, 2018 12:19
*Aan:* Templarian/MaterialDesign <MaterialDesign@noreply.github.com>
*CC:* kheijboer <karin@cds-nl.com>; Author <author@noreply.github.com>
*Onderwerp:* Re: [Templarian/MaterialDesign] Transport consolidation icons
(#2943)



Can you provide a bit more context on what these might be used for?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Templarian/MaterialDesign/issues/2943#issuecomment-375268948>,
or mute the thread

**Comment by Templarian** [comment]
I'm going to mark this as too niche for the general icon pack.

Thanks for the in depth explanation, but might be best to use vector for these more one-off icons in your application.
