### ISSUE TITLE
fried-egg

### ISSUE THREAD

**Issue by samuelesantoni** [Templarian/MaterialDesign#2944]
Hi! I would like have the eggs something icon like this:
![egg02](https://user-images.githubusercontent.com/19838074/37771174-13395dda-2dd7-11e8-8b11-3f611552d540.png)
![egg01](https://user-images.githubusercontent.com/19838074/37771175-1358ca30-2dd7-11e8-8ee2-7a91727c0712.png)
Thanks!

**Comment by PeterShaggyNoble** [comment]
Thanks for the request. Could you open a separate issue for the easter egg, though, please?

**Comment by goyney** [comment]
We do have `egg`, but we do not have any cooked variations. Updating the title to reflect that.

**Comment by goyney** [comment]
[![egg-fried](https://materialdesignicons.com/icon/egg-fried)](https://materialdesignicons.com/icon/egg-fried)
