### ISSUE TITLE
solder-station / soldering-iron

### ISSUE THREAD

**Issue by dkraft** [Templarian/MaterialDesign#2946]
![stock-vector-soldering-iron-icon-vector-746813752](https://user-images.githubusercontent.com/23946/37794863-3101a234-2de9-11e8-84bc-7e409bbc2f19.jpg)

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37870737-b67ce12c-2faa-11e8-90d1-41fa54af37df.png)
The fumes could be improved and the tip is hard to see at the smallest size

[Download link](https://github.com/Templarian/MaterialDesign/files/1844940/icon.zip)

**Comment by CoDEmanX** [comment]
Looks a bit like a pipette. Maybe make the handle a bit narrower and also use maybe 1 or 1.5 pixel width for the smoke lines?

**Comment by Croutonix** [comment]
Another try:
[![image](https://user-images.githubusercontent.com/18645219/38320134-b9c17ae6-3801-11e8-9879-8f0bf8cd1c14.png)](https://github.com/Templarian/MaterialDesign/files/1876621/icon.zip)
Maybe there too much details this time. Also the tip is still hard to see and the fumes are too thin.

**Comment by CoDEmanX** [comment]
Yeah it feels like a bit too much, although the cable adds to the recognizability and the smoke it better than in the first version.

**Comment by MiguelAngelLV** [comment]
Is the icon added yet?

**Comment by goyney** [comment]
Hmm, the first one looks more like an eye-dropper, the second one isn't very Material. I think we'll need to see some other options for this to get included. Moving it to the Backlog until that happens.

**Comment by CoDEmanX** [comment]
My take with some modified smoke from the smoking icon:

![grafik](https://user-images.githubusercontent.com/1309249/61855629-bb400680-aec0-11e9-9a7f-50ec73ea46c6.png)

[soldering-iron.zip](https://github.com/Templarian/MaterialDesign/files/3430336/soldering-iron.zip)

**Comment by goyney** [comment]
[![soldering-iron](https://materialdesignicons.com/icon/soldering-iron)](https://materialdesignicons.com/icon/soldering-iron)
