### ISSUE TITLE
share-outline

### ISSUE THREAD

**Issue by rsandrea** [Templarian/MaterialDesign#2949]
we have a like outlined, comment outlined, I would like to see a share outlined :D

**Comment by PeterShaggyNoble** [comment]
I'd imagine this one would be tricky with the arrow's tapered end.

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37870528-640f2318-2fa6-11e8-95fb-382a6b6e3713.png)
It doesn't look too bad

[Download link](https://github.com/Templarian/MaterialDesign/files/1844925/icon.zip)

**Comment by Templarian** [comment]
[![share-outline](https://materialdesignicons.com/icon/share-outline)](https://materialdesignicons.com/icon/share-outline)
