### ISSUE TITLE
Tooth (solid)

### ISSUE THREAD

**Issue by jonnyborg** [Templarian/MaterialDesign#2951]
Used in list items to call out a dental provider. For use with consistency of solid iconography.

Make the following icon a solid vs outline.

<img width="72" alt="screen shot 2018-03-23 at 11 16 43 am" src="https://user-images.githubusercontent.com/16577242/37838261-d59c45c0-2e8d-11e8-8e42-4e6b230b8377.png">

**Comment by Templarian** [comment]
Will be able to do this one quick as it's just removing the inside path. Agreed it might be good to have both since it's a common icon for health apps.

**Comment by PeterShaggyNoble** [comment]
The existing one should be renamed as `tooth-outline`, though.

**Comment by Templarian** [comment]
[![tooth](https://materialdesignicons.com/icon/tooth)](https://materialdesignicons.com/icon/tooth)
