### ISSUE TITLE
phone-edit

### ISSUE THREAD

**Issue by Alexanderdorow** [Templarian/MaterialDesign#2952]
I need an icon with a phone and a pencil together to demonstrate that that phone was edited

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37870473-3dfde39a-2fa5-11e8-8cdf-a120324fc1e8.png)![image](https://user-images.githubusercontent.com/18645219/37870503-c155724e-2fa5-11e8-9184-f94b39847596.png)

[Download link](https://github.com/Templarian/MaterialDesign/files/1844924/icons.zip)

**Comment by GreenTurtwig** [comment]
@Alexanderdorow what is your use case for the icon? Ideally this design shouldn't be needed at all, with the right context a regular pencil icon would do.

**Comment by MrGrigri** [comment]
@GreenTurtwig I agree. We cannot add an edit pencil to every icon. I would consider closing this one.

**Comment by CoDEmanX** [comment]
At some point we might wanna think about a separate "did not make it" icon set 😄

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by julienreszka** [comment]
I have a modal where I want to display that you're editing your phone number.
Is it possible to reopen this? I would be interested in having a phone-edit icon especially the second one.
