### ISSUE TITLE
Chandelier icon

### ISSUE THREAD

**Issue by rainlance** [Templarian/MaterialDesign#2954]
How about a Chandelier icon?

**Comment by Templarian** [comment]
I'm going to close this issue as a duplicate of #1712 since we have designs created.

Could use more feedback in that open issue if these designs would work for you or if variants are needed. We know lighting is a large use of Home Automation.

**Comment by rainlance** [comment]
Sorry for the late answer: The ceiling-light and floor-lamp are perfect. Thank you !
