### ISSUE TITLE
Racquet

### ISSUE THREAD

**Issue by MoritzBru** [Templarian/MaterialDesign#2957]
It would be great to introduce a racquet icon that could be used for a variety of sports like squash or badminton.
Examples:
- https://fontawesome.com/icons/racquet?style=solid
- https://icons8.com/icon/34125/racket

**Comment by terpro** [comment]
I would for sure benefit from this icon

**Comment by Yuanruili** [comment]
@MoritzBru There is a recquet icon for tennis, or you mean having a 'general' icon for multiple racquet sports?
https://materialdesignicons.com/icon/tennis

**Comment by PeterShaggyNoble** [comment]
Closing as this should be covered by the recently added `tennis` icon.
