### ISSUE TITLE
boiler icon

### ISSUE THREAD

**Issue by gyengus** [Templarian/MaterialDesign#2958]
I would like an icon for boiler.
Some example: https://www.google.hu/search?q=boiler+icon&rlz=1C5CHFA_enHU695HU698&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwj8x_Ctl4raAhXlF5oKHdoRAr4QsAQIJg&biw=1679&bih=865

**Comment by PeterShaggyNoble** [comment]
This is a duplicate of #2900.

**Comment by GreenTurtwig** [comment]
Not to be rude, but did you search (or even look at them first page of issues). :-)
