### ISSUE TITLE
Update: apple-finder

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2960]
Line ends are now rounded and the dividing line is contained within the box. I haven't been able to find an official SVG but there's a PNG [here](https://support.apple.com/en-ie/HT201732).

**Comment by Templarian** [comment]
Moving this to the backlog until we have a vector.

**Comment by PeterShaggyNoble** [comment]
I unearthed this with a bit more Googling: https://tecior.deviantart.com/art/Finder-Icon-Vector-ai-svg-639321397

**Comment by goyney** [comment]
There is not an official vector of this that I can find. Here's my attempt on the updated logo:

![image](https://user-images.githubusercontent.com/1015040/58277915-d085a100-7d68-11e9-8758-65ef018f1bf2.png)

Here's the comparison vs. our current:
![image](https://user-images.githubusercontent.com/1015040/58277957-e6936180-7d68-11e9-9aef-d8ee34f9e239.png)

[apple-finder.svg.zip](https://github.com/Templarian/MaterialDesign/files/3213690/apple-finder.svg.zip)

**Comment by goyney** [comment]
[![apple-finder](https://materialdesignicons.com/icon/apple-finder)](https://materialdesignicons.com/icon/apple-finder)
