### ISSUE TITLE
Update: google-earth

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2962]
New icon is included in [Material Icons Extended](https://petershaggynoble.github.io/MDI-Sandbox/extended/) and SVG is linked below.

[![earth](https://user-images.githubusercontent.com/15157491/37919563-1d860714-311c-11e8-8305-ac98001ba059.png)](https://github.com/Templarian/MaterialDesign/files/1475146/earth.zip)

**Comment by Templarian** [comment]
[![google-earth](https://materialdesignicons.com/icon/google-earth)](https://materialdesignicons.com/icon/google-earth)
