### ISSUE TITLE
Update & Rename: google-glass

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2963]
Google Glass is now just [Glass](https://www.x.company/glass/) and they use the "A" from [their logo](https://github.com/Templarian/MaterialDesign/files/1461537/glass.zip) as their icon.

However, Google are still using their thinner "G" for it in [Material Icons Extended](https://petershaggynoble.github.io/MDI-Sandbox/extended/).

**Comment by Templarian** [comment]
Closing this as we'll probably just end up removing this icon eventually if they never announce a 2.0.
