### ISSUE TITLE
Update: google-maps

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2964]
New icon is included in [Material Icons Extended](https://petershaggynoble.github.io/MDI-Sandbox/extended/) and SVG is linked below.

[![maps](https://user-images.githubusercontent.com/15157491/37920316-6e974abc-311e-11e8-90aa-774ff43ee3a7.png)](https://github.com/Templarian/MaterialDesign/files/1475166/maps.zip)

**Comment by Templarian** [comment]
This might just be an internal one. Lets wait until they update the one in their stock pack.

**Comment by GreenTurtwig** [comment]
While the extended design is better, the current one we have is what is currently used for notifications by Google Maps on Android. We could always add it as a variant though.

**Comment by GreenTurtwig** [comment]
Hang on a sec, I was wrong. They've updated the app and use the extended design now too. We should probably update this then. 🐈
![screenshot_20180401-232441__01](https://user-images.githubusercontent.com/15905797/38178136-176b40a0-3604-11e8-8fff-26418171e14e.png)

**Comment by Mancerrss** [comment]
Do you guys keep the older version of a certain Stock Material Google icon in some sort of older version repo? Do you guys just overwrite it?

**Comment by Templarian** [comment]
@Mancerrss We overwrite it when we believe that the old icon has been deprecated. Which it looks like they have done with this one.

[![google-maps](https://materialdesignicons.com/icon/google-maps)](https://materialdesignicons.com/icon/google-maps)

You can always go back in the GitHub history though.
