### ISSUE TITLE
Update: google-photos

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2965]
New icon is included in [Material Icons Extended](https://petershaggynoble.github.io/MDI-Sandbox/extended/) and SVG is linked below.

[![photos](https://user-images.githubusercontent.com/15157491/37920546-0d3adc9c-311f-11e8-8aab-3b514b6b1102.png)](https://github.com/Templarian/MaterialDesign/files/1475167/photos.zip)

**Comment by Templarian** [comment]
[![google-photos](https://materialdesignicons.com/icon/google-photos)](https://materialdesignicons.com/icon/google-photos)
