### ISSUE TITLE
Location Disabled Icon

### ISSUE THREAD

**Issue by DavidCRivera** [Templarian/MaterialDesign#2967]
Another stock Google icon: https://material.io/icons/#ic_location_disabled

Need it for my app, and kind of surprised it's missing... Any chance it could be added?

Thanks!

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49037706-f1d64d80-f188-11e8-9c02-e188a5473109.png)
[crosshairs-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/2617083/crosshairs-off.svg.zip)
