### ISSUE TITLE
Death Star

### ISSUE THREAD

**Issue by Alekhen** [Templarian/MaterialDesign#2968]
I've got a fun internal project at my company I'm working on and would love to use a death star icon.

What do you guys think of these?

![image](https://user-images.githubusercontent.com/1837101/37936329-5b99b4ba-3112-11e8-954a-e5288553b5fd.png)
![image](https://user-images.githubusercontent.com/1837101/37936374-862aceb2-3112-11e8-8cbe-468b6c1ae29c.png)

[death-star.svg.zip](https://github.com/Templarian/MaterialDesign/files/1849743/death-star.svg.zip)
[death-star-construction.svg.zip](https://github.com/Templarian/MaterialDesign/files/1849744/death-star-construction.svg.zip)

**Comment by MrGrigri** [comment]
That horizontal cutout would have to be 2px tall. But I love it

**Comment by Alekhen** [comment]
Here's the updated Death Star icons with a 2px equator instead of 1px. Thanks @MrGrigri, I like this updated version better after seeing it.

![image](https://user-images.githubusercontent.com/1837101/37981649-7cc1e272-31ab-11e8-9711-ed43acf80d38.png)
![image](https://user-images.githubusercontent.com/1837101/37981689-92a6e614-31ab-11e8-83c5-4b893f87169f.png)

[death-star.svg.zip](https://github.com/Templarian/MaterialDesign/files/1852916/death-star.svg.zip)
[death-star-construction.svg.zip](https://github.com/Templarian/MaterialDesign/files/1852915/death-star-construction.svg.zip)

**Comment by Alekhen** [comment]
I'm not sure if it should be called "death star construction" or "death star in progress" or "death star partial". Do you guys have any recommendations?

**Comment by MrGrigri** [comment]
I would call it `death-star-variant`.

**Comment by Templarian** [comment]
[![death-star](https://materialdesignicons.com/icon/death-star)](https://materialdesignicons.com/icon/death-star) [![death-star-variant](https://materialdesignicons.com/icon/death-star-variant)](https://materialdesignicons.com/icon/death-star-variant)
