### ISSUE TITLE
Icon representing two columns of text

### ISSUE THREAD

**Issue by PierreClementCazon** [Templarian/MaterialDesign#2969]
Good morning,

I'm looking for an icon equivalent to this image :
![icon-suggest](https://user-images.githubusercontent.com/36991574/37955171-26cdb5ec-31a8-11e8-8c33-542bc27322b3.png)

If anyone is available to do it, I thank them in advance for their help !

**Comment by PeterShaggyNoble** [comment]
[![format-columns](https://user-images.githubusercontent.com/15157491/37957946-14dd0262-31a7-11e8-9840-6ac1b57aa030.png)](https://github.com/Templarian/MaterialDesign/files/1851250/format-columns.zip)

**Comment by Templarian** [comment]
[![format-columns](https://materialdesignicons.com/icon/format-columns)](https://materialdesignicons.com/icon/format-columns)
