### ISSUE TITLE
Paypal Icon

### ISSUE THREAD

**Issue by don-kakashi** [Templarian/MaterialDesign#297]
Hello,

I would like to know if it is possible to have a Paypal icon.

thank you
- [ ] paypal-above
- [ ] paypal-below.

**Comment by Templarian** [comment]
Due to the two toned nature of the icon this is not possible at this time. Although, I guess I could make it two icons and have them overlap?

I wonder if that would suffice.

**Comment by Templarian** [comment]
![paypal](http://www.underconsideration.com/brandnew/archives/paypal_2014_logo_detail.png)

See how it overlaps, if it is solid it just looks like a blob.

**Comment by Idresign** [comment]
I see, thank you very much for the help.

**Comment by Templarian** [comment]
That was a question @Idresign. Would having 2 layers work for your use case? Naming them something like: `paypal-above` and `paypal-below`.

**Comment by Idresign** [comment]
Oh sorry, I thought I understood it is not possible.
It would not help having two layers as long as it is not the exact representation of paypal logo
It would not be possible to have this version of logo, because it is not the official one, right? 
![paypal-icon-614x460](https://cloud.githubusercontent.com/assets/6286315/7238528/0e1d0964-e771-11e4-8d3c-3316db5e7ec4.png)

**Comment by Templarian** [comment]
Correct, using that logo is against their branding guidelines and I don't want to promote its use.

Their logo is one of the most annoying to fit into an icon set. For the webfont I've been thinking of adding it in. `mdi-paypal` will automatically combine the two glyphs with opacity.

**Comment by Idresign** [comment]
Alright! it would really help if you could combine paypal-above and paypal-below, in different opacity. If I understood well your solution.

**Comment by Templarian** [comment]
Issue #409 explains how this will go into the next release.

**Comment by infanf** [comment]
Tada! Maybe?
![paypal](https://cloud.githubusercontent.com/assets/8826710/12293220/4b1ca280-b9f2-11e5-9d0d-2d98eb867863.png)
![paypal-48](https://cloud.githubusercontent.com/assets/8826710/12293222/4b2151e0-b9f2-11e5-9c62-fe934b2643fd.png)
![paypal-96](https://cloud.githubusercontent.com/assets/8826710/12293221/4b1f9dbe-b9f2-11e5-99e1-dc99538e0f09.png)
[PayPal.zip](https://github.com/Templarian/MaterialDesign/files/88772/PayPal.zip)

**Comment by CoDEmanX** [comment]
Still against their branding guidelines

**Comment by infanf** [comment]
An if we call it double-p ;)

**Comment by Idresign** [comment]
Looks good, but their branding guidelines that concerns me X)

**Comment by kurisubrooks** [comment]
Would something like this work?

![image](https://cloud.githubusercontent.com/assets/6291467/24631585/351aad0c-1904-11e7-97e5-b845a8f70dab.png)

```xml
<svg viewBox="0 0 16 16">
    <g>
        <path d="M4.5 1a.623.623 0 0 0-.615.525L2.15 12.528S2 13 2.43 13h2.767l.584-3.48v-.003a.62.62 0 0 1 .615-.524H7.67c2.507 0 4.47-1.234 5.045-4.18.017-.088.032-.173.045-.256.17-1.09-.002-1.83-.59-2.5C11.522 1.317 10.35 1 8.85 1z" />
        <path d="M13.596 5.373c-.36 1.475-1.067 2.653-2.067 3.426-1.086.837-2.442 1.194-3.86 1.194h-.955L6.043 14H5.04l-.1.62a.33.33 0 0 0 .326.38H7.53a.543.543 0 0 0 .536-.46l.024-.114.426-2.705.027-.15a.545.545 0 0 1 .54-.46h.337c2.193 0 3.91-.89 4.412-3.467.176-.903.11-1.67-.236-2.27z" opacity=".5" />
    </g>
</svg>
```

Might need a bit of cleanup.

**Comment by Templarian** [comment]
@kurisubrooks Thanks, unfortunately it goes against their branding guidelines to use any variation of their logo.

https://www.paypal.com/us/webapps/mpp/logo-center

We would recommend using SVG or vector drawables depending on the platform you are targeting.

I'm going to close this issue since there is no ideal solution for this to be included.

**Comment by GreenTurtwig** [comment]
PayPal use a logo similar to the ones suggested above on their card reader, PayPal Here:
![image](https://user-images.githubusercontent.com/15905797/33806291-ff811198-ddbd-11e7-8ee9-52272a3fb1ee.png)

**Comment by GreenTurtwig** [comment]
Been a long time coming, needs a fair bit of optimisation but uploading as is at the moment:

[![](https://user-images.githubusercontent.com/15905797/36812231-67257d40-1cc8-11e8-8bfd-39581bfa43bf.png)](https://github.com/Templarian/MaterialDesign/files/1768798/paypal.zip)

**Comment by Templarian** [comment]
[![paypal](https://materialdesignicons.com/icon/paypal)](https://materialdesignicons.com/icon/paypal)

**Comment by vstyler96** [comment]
Is there any chance to have this icon again? :o

**Comment by goyney** [comment]
No. Use [SimpleIcons][2].

[2]: https://simpleicons.org/
