### ISSUE TITLE
64-bit icon request

### ISSUE THREAD

**Issue by dreasn** [Templarian/MaterialDesign#2970]
64-bit

**Comment by PeterShaggyNoble** [comment]
Can you provide an example of what that would look like, please?

**Comment by Mancerrss** [comment]
What about simply a boxed, unboxed & that processor shape icon with "64-" "32-" text into it, plus another instance with just "64B" & "32B" text to it

**Comment by Mancerrss** [comment]
@henriquecm Why not make the processor shape much smaller, rounded corners and the chip insulation & brackets be much longer and only 3 on each sides

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/38435625-1b8a6e58-39ca-11e8-9198-a006ea3508fc.png)![](https://user-images.githubusercontent.com/15905797/38435649-2ff8dcf8-39ca-11e8-9ee8-809b5697c186.png)![](https://user-images.githubusercontent.com/15905797/38435676-4a0b63b8-39ca-11e8-9f0f-649e12349e08.png)
[bits.zip](https://github.com/Templarian/MaterialDesign/files/1885057/bits.zip)

I still need to work on the small font, so included two variations of the number three.

**Comment by Mancerrss** [comment]
It looks good now. Very inline with stock Material icons

**Comment by CoDEmanX** [comment]
With two more rounded corners and the bar in 4 half a pixel lower:

![image](https://user-images.githubusercontent.com/1309249/38486276-d2077536-3bdc-11e8-9848-caa8012466e1.png)

**Comment by GreenTurtwig** [comment]
I purposely didn't round the corners to keep in line with the design of the current larger numbers Google use, me and @jamescoyle had a discussion about rounding the ends of the number three but decided against it. Also the bar in four was at that height as that's also the position of it in the letter H, albeit in this situation it looks a little better .5px down

**Comment by JamesCoyle** [comment]
TBH I personally think the rounded corners look better. Just looked a bit weird at larger sizes.

**Comment by CoDEmanX** [comment]
No matter the size, the 6 looks really strange to me without the rounding at the top right corner. It approximates the curvy nature of a common 6. It's similar with the 3: The common shape of it is like two half circle outlines, so it would make sense to use rounding in the middle to make it look less "blocky". However, it kinda works without too, unlike with the 6.

**Comment by dreasn** [comment]
I think the "bit" word should be included.

**Comment by JamesCoyle** [comment]
@dreasn there is no way that would ever fit.

**Comment by goyney** [comment]
`cpu-32-bit` and `cpu-64-bit` added. 😄
