### ISSUE TITLE
Remove: google-plus-box

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2971]
New icon is included in [Material Icons Extended](https://petershaggynoble.github.io/MDI-Sandbox/extended/) and SVG is linked below. Image on the right our the current version overlaid on Google's, for comparison.

[![post-gplus](https://user-images.githubusercontent.com/15157491/37959117-3dda5554-31aa-11e8-838d-336532baa513.png)](https://github.com/Templarian/MaterialDesign/files/1475178/post-gplus.zip) ![](https://user-images.githubusercontent.com/15157491/37959141-5938e3a6-31aa-11e8-9bd9-f1cb8fdf8c05.png)

**Comment by goyney** [comment]
Since Google Plus was discontinued, I think we should just remove the icon.

**Comment by PeterShaggyNoble** [comment]
@goyney, it sounds like they're going to be keeping [Google+ Create](https://plus.google.com/create) open so there may still be a use case for it.

Regardless, I don't think we *should* remove it until they shut the service down in August.

**Comment by goyney** [comment]
> Due to low user engagement and disclosed software design flaws that potentially allowed outside developers access to personal information of its users, the Google+ developer API was discontinued on March 7, 2019 and Google+ was shut down for business use and consumers on April 2, 2019. It is still in use as Google+ for Enterprise for internal corporate social networks who are users of G-Suite.

Considering it is still potentially used in G-Suite environments and it is technically a stock Google icon, albeit a brand icon, I believe we should still update this.

**Comment by Templarian** [comment]
This goes against the guidelines. Box icons are all 18dp square with 2dp rounded corners.

Going to close this also because meh, it's google plus no one will notice. 🤣

**Comment by goyney** [comment]
Reopening. We should remove `google-plus-box`. Google+ still remains for G Suite users, but its not a consumer product anymore and there is no reason for a box variant.

**Comment by goyney** [comment]
Removed `google-plus-box`.
