### ISSUE TITLE
Update: houzz & houzz-box

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2972]
Houzz [updated their logo](http://blog.houzz.com/post/171594460643/a-logo-redesign-for-houzz) the other week. SVG is [here](https://github.com/Templarian/MaterialDesign/files/1851484/houzz.zip) or EPS & PNG files can be dowloaded [here](https://www.houzz.com/logoGuidelines).

![houzz](https://user-images.githubusercontent.com/15157491/37959539-4421051a-31ab-11e8-9539-831a78a63a88.png) ![houzz-box](https://user-images.githubusercontent.com/15157491/37959557-4d6f1c1a-31ab-11e8-8542-5bbec211b0bc.png)

**Comment by Templarian** [comment]
Updated. 😄 Their new logo is so much better!
