### ISSUE TITLE
Onion Skin Icon request

### ISSUE THREAD

**Issue by derrideanauthor** [Templarian/MaterialDesign#2973]
In animation programs such as flash or the like there is an onionskin function which allows for users to see adjacent frames in low opacity on the current frame's workspace. I have been using mdi-checkbox-multiple-blank-circle-outline for my application - almost similar to Flash's, but might be misunderstood.
I have been thinking of replacing it with a home made icon of a cross sectioned onion like some other apps use. Problem is, its not very material design.

Animation icons in general would be a nice addition:

- onion skin
- add keyframe
- add frame
- move frame (forwards, backwards)
- play, pause
- animation preview 
- GIF file, PNG File
- sprite sheet, sprite
- frame sequence 

I will try submit designs if I get around to making them. 

Thanks all
Walt

**Comment by PeterShaggyNoble** [comment]
Would one of the [`arrange` icons](https://petershaggynoble.github.io/MDI-Sandbox/?filter=arrange) suit your needs?

A lot of the others are already available but, for any that aren't, could you open a separate issue for each one, please?

**Comment by GreenTurtwig** [comment]
We also have Tor:
[![](https://materialdesignicons.com/icon/tor)](https://materialdesignicons.com/icon/tor)

**Comment by PeterShaggyNoble** [comment]
`animation` or `camera-burst` could work as well.

[![animation](https://user-images.githubusercontent.com/15157491/37977799-7011c82c-31dc-11e8-9adb-40f596e784b9.png)](https://materialdesignicons.com/icon/animation) [![camera-burst](https://user-images.githubusercontent.com/15157491/37976718-0568db84-31da-11e8-8827-19ab4aebdcbf.png)](https://materialdesignicons.com/icon/camera-burst)

**Comment by CoDEmanX** [comment]
Seen an icon with three circles somewhere. Definitely bending the guidelines:

![onion-skinning-2](https://user-images.githubusercontent.com/1309249/38045858-4f40e9b0-32be-11e8-9a03-7f537c5ee923.png)
![onion-skinning](https://user-images.githubusercontent.com/1309249/38045859-4f5dc30a-32be-11e8-8328-91470f5a93b1.png)

**Comment by MrGrigri** [comment]
- [ ]  `tor` icon should be aliased as `onion`

**Comment by MrGrigri** [comment]
There is also `layers`.

![layers](https://materialdesignicons.com/icon/layers)

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX's comment reminded me that Google have these in Material Icons Extended:

![animation](https://user-images.githubusercontent.com/15157491/38078864-80c2eaf2-3335-11e8-88d1-3d362e30630c.png) ![masked transitions](https://user-images.githubusercontent.com/15157491/38078908-a17872a8-3335-11e8-93d7-c6465376e986.png)

**Comment by Templarian** [comment]
[![transition](https://materialdesignicons.com/icon/transition)](https://materialdesignicons.com/icon/transition) [![transition-masked](https://materialdesignicons.com/icon/transition-masked)](https://materialdesignicons.com/icon/transition-masked)

**Comment by Templarian** [comment]
Closing please create individual issues for requests so they can be tracked more easily for any of these remaining requests.
