### ISSUE TITLE
Update: opera

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2974]
SVG is [here](https://github.com/Templarian/MaterialDesign/files/1852430/opera.zip) ([Source](https://dev.opera.com/images/logo.svg)).

![opera](https://user-images.githubusercontent.com/15157491/37974925-016aa85e-31d6-11e8-9d99-363a53c0ec8e.png)

**Comment by Templarian** [comment]
[![opera](https://materialdesignicons.com/icon/opera)](https://materialdesignicons.com/icon/opera)
