### ISSUE TITLE
Update: pandora

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2975]
I haven't been able to find an official SVG but PNGs can be downloaded [here](http://investor.pandora.com/CustomPage/4247784/Index?KeyGenPage=1073752142).

![pandora](https://user-images.githubusercontent.com/15157491/37976091-943d0fda-31d8-11e8-9e97-e9820c9bba42.png)

**Comment by Templarian** [comment]
[![pandora](https://materialdesignicons.com/icon/pandora)](https://materialdesignicons.com/icon/pandora)
