### ISSUE TITLE
Update: pinterest & pinterest-box

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2976]
While ours match the style of Google's, we should probably update them to match the official icon. SVG [here](https://github.com/Templarian/MaterialDesign/files/1457950/pinterest.zip).

![pinterest](https://user-images.githubusercontent.com/15157491/37980770-cd6636b4-31e3-11e8-962a-3175b1d05194.png)

**Comment by Templarian** [comment]
We would need to match the max size for a circle so 20x20. (I can resize it)

**Comment by PeterShaggyNoble** [comment]
Yeah, I just lifted that one straight off their site.

**Comment by Templarian** [comment]
Updated both.
