### ISSUE TITLE
Update: steam

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2978]
Steam updated their icon a while ago, removing the leftmost circle and increasing the size of the crank, among other tweaks. Couldn't find an SVG but there's a link to some AI files in their [brand guidelines](https://steamcdn-a.akamaihd.net/steamcommunity/public/images/steamworks_docs/english/Steam_Guidelines_1217.pdf).

See also #2720 for a request for `steam-box`.

**Comment by Templarian** [comment]
[![steam](https://materialdesignicons.com/icon/steam)](https://materialdesignicons.com/icon/steam) [![steam-box](https://materialdesignicons.com/icon/steam-box)](https://materialdesignicons.com/icon/steam-box)
