### ISSUE TITLE
Update: vk, vk-box & vk-circle

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#2979]
VK(ontakte) "streamlined" their icon a while ago; SVG [here](https://github.com/Templarian/MaterialDesign/files/1852951/vk.zip).

**Comment by CoDEmanX** [comment]
Download: [vk-new.zip](https://github.com/Templarian/MaterialDesign/files/1877478/vk-new.zip)

![image](https://user-images.githubusercontent.com/1309249/38332182-a65450c4-3855-11e8-896d-31117f783c84.png)
![image](https://user-images.githubusercontent.com/1309249/38332215-bbf60666-3855-11e8-8fbd-376245559c49.png)
![image](https://user-images.githubusercontent.com/1309249/38332245-d0d5f0be-3855-11e8-87e0-edd5d4ffac90.png)

**Comment by Templarian** [comment]
Fixed. Thanks, saved me a lot of time with these already vectored.
