### ISSUE TITLE
folder-outline-lock

### ISSUE THREAD

**Issue by doc-rj** [Templarian/MaterialDesign#298]
It would be nice to have a folder-outline icon with a lock symbol inside, to represent a locked folder. The folder-outline icon is from Google.

- [ ] folder-outline-lock

Thanks!

**Comment by Templarian** [comment]
Folder outline means... opened. So it would be a locked opened folder? Seems like an odd icon. It's provided below, but not added to the community pack yet.

http://materialdesignicons.com/icon/folder-lock
[folder-outline-lock.svg](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/folder-outline-lock.svg) -> [Custom Icon Export](http://materialdesignicons.com/custom)

I might be over thinking this, but I'll add to the official pack if you could explain why it fits.

**Comment by doc-rj** [comment]
Didn't realize folder-outline means folder open. So, folder-lock is what I need. Looks like you just added that one.

**Comment by Templarian** [comment]
Awesome. Good luck on your apps!
