### ISSUE TITLE
tag-minus

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2980]
Certainly odd that we never added this.
[![](https://user-images.githubusercontent.com/15905797/38023553-88847a5a-327a-11e8-9ce3-4eb3ee6afa0b.png)](https://github.com/Templarian/MaterialDesign/files/1855550/tag-minus.zip)

**Comment by Templarian** [comment]
[![tag-minus](https://materialdesignicons.com/icon/tag-minus)](https://materialdesignicons.com/icon/tag-minus)
