### ISSUE TITLE
ticket-outline

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2981]
[![](https://user-images.githubusercontent.com/15905797/38023660-d5a45922-327a-11e8-9443-05e3ccd04a08.png)](https://github.com/Templarian/MaterialDesign/files/1855560/ticket-outline.zip)

**Comment by Templarian** [comment]
[![ticket-outline](https://materialdesignicons.com/icon/ticket-outline)](https://materialdesignicons.com/icon/ticket-outline)
