### ISSUE TITLE
voice-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#2983]
Hi,
Customizing several input_booleans i ran into the following missing icons:

mdi:Home is available, well sort of. though mdi:home isn't really an 'at home' icon.  Away isn't ?

mdi:Hometheater is available (using it in the category entertainment appliances for the main set) hometheater-off isn't. (compare tv, speaker, etc)

mdi:Voice is available, Voice-off isn't.. use text-to-speech-off now, which suffices, but isn't perfect for this representation
![schermafbeelding 2018-03-28 om 12 48 51](https://user-images.githubusercontent.com/33354141/38024896-b5096458-3286-11e8-82e9-dbf52b2593cd.jpg)
![schermafbeelding 2018-03-28 om 12 49 01](https://user-images.githubusercontent.com/33354141/38024897-b53ab580-3286-11e8-9d8d-98e58e5cdf1f.jpg)

need something for Motion detector -off also , using eye-off now, but maybe something next to run(-fast) would be possible.
![schermafbeelding 2018-03-28 om 12 49 10](https://user-images.githubusercontent.com/33354141/38024910-be8c7a10-3286-11e8-9b93-b37aa0dd9889.jpg)
![schermafbeelding 2018-03-28 om 12 49 19](https://user-images.githubusercontent.com/33354141/38024912-beb9d7d0-3286-11e8-92a3-08809bcfcb07.jpg)

please also consider mdi:desktop-mac, laptop-mac etc. Think of all appliances and devices.
Same technique for all: slash the available ones... ;-)

**Comment by PeterShaggyNoble** [comment]
Material Icons Extended includes a `voice over off` icon so let's use this issue to track that one and can you please open new issues for `run-off` and any others you may require?

![voice over off](https://user-images.githubusercontent.com/15157491/38300524-ec23fd22-37f4-11e8-8c8f-16b61f7c67cd.png)

**Comment by hvbhome** [comment]
thanks, I didn't know that. Where can we find Material Icons Extended?

did find this https://material.io/icons/  record-voice-over which looks a lot like mdi:voice...

**Comment by Croutonix** [comment]
https://petershaggynoble.github.io/MDI-Sandbox/extended/

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49037612-b0de3900-f188-11e8-8b0e-55697af434ea.png)
[voice-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/2617078/voice-off.svg.zip)

**Comment by Templarian** [comment]
This was added since we needed one more icon to fix a bug in `3.7.94`.
