### ISSUE TITLE
cupcake

### ISSUE THREAD

**Issue by naiveaiguy** [Templarian/MaterialDesign#2984]
A variation on the cake icon without the candle that looks more like a cupcake.

Here's a reference I found in a premium icon pack (http://www.webalys.com/nova/ultimate-pack.html). Not sure if it's ok to use then, but still:

<img width="31" alt="screen shot 2018-03-28 at 7 29 44 pm" src="https://user-images.githubusercontent.com/8231396/38033830-8b43d5ee-32be-11e8-8f8d-254f2f43a1ef.png">

**Comment by Croutonix** [comment]
[![image](https://user-images.githubusercontent.com/18645219/38318004-614956ae-37fc-11e8-80a9-faff856861dc.png)](https://github.com/Templarian/MaterialDesign/files/1876492/icon.zip)

**Comment by Templarian** [comment]
@Croutonix The bottom is a little too pointed.

**Comment by Croutonix** [comment]
I changed it.

**Comment by Croutonix** [comment]
And while I'm at it why not muffin too:
[![image](https://user-images.githubusercontent.com/18645219/38321405-98220654-3805-11e8-96d9-8e03a79b4b6d.png)](https://github.com/Templarian/MaterialDesign/files/1876710/muffin.zip)

**Comment by Templarian** [comment]
[![cupcake](https://materialdesignicons.com/icon/cupcake)](https://materialdesignicons.com/icon/cupcake) [![muffin](https://materialdesignicons.com/icon/muffin)](https://materialdesignicons.com/icon/muffin)
