### ISSUE TITLE
MIDI connector

### ISSUE THREAD

**Issue by obiwanjacobi** [Templarian/MaterialDesign#2985]
Perhaps a bit like the existing video-input-svideo but with the typical 5 pin DIN MIDI connector.

**Comment by GreenTurtwig** [comment]
Hmm, that could be a useful one to have.

**Comment by obiwanjacobi** [comment]
Yes, you could expand on the MIDI topic more if you wish:
MIDI connector filled
MIDI connector outline
MIDI connector crossed (not available)
MIDI connectors with numbers 1-16 (MIDI channels)
MIDI connector with arrow pointing outward (output)
MIDI connector with arrow pointing inward (input)
MIDI File format (.mid)
MIDI System Exclusive (SysEx)

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/38164026-ec57f21e-34f5-11e8-89f0-fca35cca8ab2.png)](https://github.com/Templarian/MaterialDesign/files/1865539/midi-connector.zip)

**Comment by GreenTurtwig** [comment]
We should also alias with `din-5-pin`

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/38164171-1c85e8b8-34f8-11e8-88a7-55794fa89a70.png)](https://github.com/Templarian/MaterialDesign/files/1865555/midi.zip)

Making this reminded me I still have to sort out the font.

**Comment by obiwanjacobi** [comment]
Why not use the real logo as a style guide for the text?
https://www.schoolofelectronicmusic.com/wp-content/uploads/2013/11/midi-logo.png

Characteristic of the DIN 5 pin plug/connector is the little notch at the top.
https://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/DIN-5_Diagram.svg/455px-DIN-5_Diagram.svg.png

[2c]

**Comment by Templarian** [comment]
[![midi](https://materialdesignicons.com/icon/midi)](https://materialdesignicons.com/icon/midi)

**Comment by Templarian** [comment]
[![midi](https://materialdesignicons.com/icon/midi-input)](https://materialdesignicons.com/icon/midi-input)
