### ISSUE TITLE
Owntracks

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#2986]
![owntracks](https://user-images.githubusercontent.com/33354141/38057619-51b92302-32e0-11e8-808d-aad05ffe6ed1.png)

thx,
Marius

**Comment by PeterShaggyNoble** [comment]
Is this a brand icon? Or what's its use case?

**Comment by hvbhome** [comment]
yes it is, and its for using the Owntracks states in HomeAssistant.
![schermafbeelding 2018-03-29 om 10 52 25](https://user-images.githubusercontent.com/33354141/38079471-4605623c-333f-11e8-8247-e40b8a0a5415.jpg)

**Comment by PeterShaggyNoble** [comment]
Owntracks is not a popular enough for us to add at this time. We suggest using one of the `map-marker-*` icons instead. As Owntracks is a Geofencing app (I'm told), `map-marker-radius` would probably be the best fit.

We may revisit this should a dedicated brand icon pack ever be created.
