### ISSUE TITLE
Home Security icons

### ISSUE THREAD

**Issue by arsaboo** [Templarian/MaterialDesign#2992]
It will be great to have icons indicating the different security modes. Typical modes are:

1. Armed
2. Disarmed or Standby
3. Night or Home 

Here's one option:
![image](https://user-images.githubusercontent.com/18319734/38122796-58879b26-33a5-11e8-947d-a0c29cf3dca1.png)

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/38144388-7f16846a-3412-11e8-913b-351ac6f3fa74.png)![image](https://user-images.githubusercontent.com/18645219/38144408-8ef8479c-3412-11e8-9439-2018fb3bd250.png)
[Download link](https://github.com/Templarian/MaterialDesign/files/1864062/icons.zip)

**Comment by Templarian** [comment]
[![home-lock](https://materialdesignicons.com/icon/home-lock)](https://materialdesignicons.com/icon/home-lock) [![home-lock-open](https://materialdesignicons.com/icon/home-lock-open)](https://materialdesignicons.com/icon/home-lock-open)
