### ISSUE TITLE
Tumble dryer

### ISSUE THREAD

**Issue by dnuc** [Templarian/MaterialDesign#2993]
Would be great to have an icon for a tumble dryer. A combination of the already existing washing-machine and this icon: https://cdn4.iconfinder.com/data/icons/hotel-facilities-2/500/dryer-128.png

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, however this is a duplicate of #1625. The icon is scheduled for addition in the next release.

**Comment by dnuc** [comment]
Sorry for the duplicate request. Lookig forward for the next release :)
