### ISSUE TITLE
AND logic gate

### ISSUE THREAD

**Issue by isaacgg** [Templarian/MaterialDesign#2995]
And also OR, XOR, NOT...
I think it would be nice to have this icons, to use it with advanced custom filters

**Comment by PeterShaggyNoble** [comment]
Could you provide examples of what these might look like? Would they not be best represented using standard characters?

**Comment by isaacgg** [comment]
@PeterShaggyNoble I meant something like @Croutonix 's icon, (Thanks by the way!). Although maybe you are right and it would be more intuitive to use just words

**Comment by JapanYoshi** [comment]
I beg to differ. Circuit board icons are universally understood and serve to be more recognizable, especially in conjunction with the other gates (OR, XOR, NOT, NAND, NOR). I also suggest removing the tiny legs at either side, since 3+ input gates exist.

**Comment by JapanYoshi** [comment]
![](http://hydrogen.physik.uni-wuppertal.de/hyperphysics/hyperphysics/hbase/electronic/ietron/gate.gif)
These are the basic logic gate icons used in logic circuit design. AND gates are the outline of a square sitting flush against a semicircle; OR gates are more aerodynamic-looking, with the flat side of the AND curving inward, and the point also being sharpened somewhat. NOT gates (also known as “Inverting Buffer”) are a triangle pointing at a circle.

**Comment by JapanYoshi** [comment]
![](https://www.portalprogramas.com/imagenes/programas/en/667/4667_2.jpg)
Here they are in action in a program called Logisim that emulates a logic circuit. The gates have 5 legs (especially apparent in the OR and XOR gates) because, by default, Logisim uses 5-input gates.

**Comment by Croutonix** [comment]
The wires make the gate more recognizable, that's why I put them.

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/38150283-3370dac8-342c-11e8-8530-ce23211ddbd9.png)![image](https://user-images.githubusercontent.com/18645219/38150290-3e642156-342c-11e8-9ebc-10a652a035eb.png)![image](https://user-images.githubusercontent.com/18645219/38150302-4f5bbad2-342c-11e8-90b7-c64e2a8e5c8b.png)![image](https://user-images.githubusercontent.com/18645219/38150329-61b206aa-342c-11e8-9d4e-0785f1c2b0e0.png)![image](https://user-images.githubusercontent.com/18645219/38150339-7036099c-342c-11e8-8097-b116b54458be.png)![image](https://user-images.githubusercontent.com/18645219/38150346-7e45ba6e-342c-11e8-8771-330177e67a08.png)![image](https://user-images.githubusercontent.com/18645219/38150357-91df1ab6-342c-11e8-9f5a-7549194a4188.png)
Actually, better without wires, it would have been nearly impossible to make XNOR with them.

[Download link](https://github.com/Templarian/MaterialDesign/files/1864546/icons.zip)

**Comment by Templarian** [comment]
I really think these need to have wires even if they are 1.5 width. They are not as obvious to read without them. hmm. 🙃

**Comment by Croutonix** [comment]
The problem is not with the wire width but length, there is no space available horizontally. I gave it a try with a 1px horizontal margin instead of 2px.
![image](https://user-images.githubusercontent.com/18645219/38162928-b9ad8014-34b8-11e8-91ec-caf9b92a7dad.png)

The other gates are in the [download](https://github.com/Templarian/MaterialDesign/files/1865436/icons.zip).

**Comment by JapanYoshi** [comment]
I like the wireless ones a lot better. They feel more Material, and context would provide the identification of the shapes as gates anyway.

**Comment by Templarian** [comment]
Added the ones without wires. 😄

**Comment by Croutonix** [comment]
The XOR is stretched vertically compared to the other ones is this normal?
[![image](https://user-images.githubusercontent.com/18645219/38203343-f891aa52-366c-11e8-98c0-64b9bd969e89.png)](https://materialdesignicons.com/icon/gate-xor)

**Comment by JapanYoshi** [comment]
No. The previous draft had it right.

**Comment by Templarian** [comment]
No idea how that happened during export. Might have typo'ed while exporting. Will fix this tonight.

**Comment by Templarian** [comment]
Fixed. Like it never happened. 😴
