### ISSUE TITLE
Axe

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#2996]
![image](https://user-images.githubusercontent.com/18645219/38144638-9d6928f4-3413-11e8-8de9-bda36e915559.png)
[Download link](https://github.com/Templarian/MaterialDesign/files/1864078/icons.zip)

**Comment by GreenTurtwig** [comment]
What would it look like with a straight handle, should really try to keep all the tool related icons consistent.

**Comment by Templarian** [comment]
[![axe](https://materialdesignicons.com/icon/axe)](https://materialdesignicons.com/icon/axe)
