### ISSUE TITLE
Updated caravan

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#2999]
[![](https://user-images.githubusercontent.com/15905797/38163767-6ce8ce1c-34f1-11e8-8dd2-63a22928999c.png)](https://github.com/Templarian/MaterialDesign/files/1865508/caravan.zip)

Updated caravan icon to match `rv-hookup` in the stock set.

**Comment by Templarian** [comment]
[![caravan](https://materialdesignicons.com/icon/caravan)](https://materialdesignicons.com/icon/caravan)
