### ISSUE TITLE
icon-request: test-tube-empty and test-tube-off

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#3001]
please make a test-tube-empty (only outline of the test-tube) and a test-tube-off (slash)
needed for several test-setup, where current test-tube serves the On setting perfectly, but also need an Empty, and an Off state.

thanks,
Marius

**Comment by Templarian** [comment]
[![test-tube-empty](https://materialdesignicons.com/icon/test-tube-empty)](https://materialdesignicons.com/icon/test-tube-empty) [![test-tube-off](https://materialdesignicons.com/icon/test-tube-off)](https://materialdesignicons.com/icon/test-tube-off)

Have a good 🐰

**Comment by Templarian** [comment]
@CoDEmanX I only left them because of a toggle state. I deleted them then put them back. Could go either way.
