### ISSUE TITLE
kettle-empty

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3002]
wow, thanks for the immediate test-tube icons, magic and very beautiful!

since your at it .....

please consider kettle-empty and water-pump-outline (or -off, or -empty) too? Maybe a slash instead of a drop..as an extra visual trigger?

Same reason as with coffee, need them filled and empty ;-)

happy easter to you all!
cheers,
Marius

**Comment by Templarian** [comment]
Please keep issue requests to one icon per request. Makes it easier for us to manage.

**Comment by hvbhome** [comment]
ok sorry will do.
need to file an extra request or are you ok for this once...

**Comment by Templarian** [comment]
Yep, more details: https://github.com/Templarian/MaterialDesign/blob/master/CONTRIBUTING.md

**Comment by Croutonix** [comment]
Would that work for an empty kettle?
[![image](https://user-images.githubusercontent.com/18645219/38323096-50826ed8-380a-11e8-8606-0f850126ca72.png)](https://github.com/Templarian/MaterialDesign/files/1876828/icon.zip)

**Comment by Mancerrss** [comment]
What if another version without that reflection, that wasn't allowed on the guidelines. So just like an outlined kettle

**Comment by CoDEmanX** [comment]
Should we remove it from the filled variant as well? It does make it easier to recognize, but it would work without in the outline version I think.

**Comment by goyney** [comment]
Added!
[![kettle-outline](https://materialdesignicons.com/icon/kettle-outline)](https://materialdesignicons.com/icon/kettle-outline)
