### ISSUE TITLE
Icon round arrow

### ISSUE THREAD

**Issue by nicandnic** [Templarian/MaterialDesign#3003]
Hi!
I needed them. I made them. How can I upload them?

**Comment by Templarian** [comment]
Zips can be uploaded in comments. But round goes against the MD guidelines so we'll not be able to add them. Could be useful for others.

http://dev.materialdesignicons.com/contribute/github You can use this to generate previews.

**Comment by Templarian** [comment]
@nicandnic ? Still would like to see them. If you have a minute please upload them in a comment.

**Comment by nicandnic** [comment]
I'm sorry I did not know how to use the link. I attach an image.
Sorry for the delay-
I used the SVG template that is here: https://materialdesignicons.com/contribute
![inkscape_2018-04-03_09-41-50](https://user-images.githubusercontent.com/5815170/38249887-94b8f5fa-3723-11e8-87db-952ebe183119.png)

**Comment by nicandnic** [comment]
The idea is seven days later, a week later. or changing the direction of the arrow, seven days before, one week before.
A specific period of time to the past or the future.

**Comment by Templarian** [comment]
Oh that's what you meant. But this might be too specific to add at this time. We usually try to stay away for numerical `*-#` style icons. We have a few of the basics. We have plans to add numerical/alpha fonts that might address this nicer.

Closing at this time, but feel free to suggest/contribute other icons in the future.
