### ISSUE TITLE
water-pump-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3004]
please consider creating an water-pump-outline (or -off, or -empty) icon.

might take the drop out signaling the water is finished ;-)

or just slash it, 

Thanks,
Marius

**Comment by hvbhome** [comment]
Perfect!

**Comment by PeterShaggyNoble** [comment]
If we *are* going to add this, I think it will need to be one of those exceptions when we rotate the slash given how close it sits to the pump in the upper left corner. Flipping the base icon might be an alternative (as we did with `scanner` recently) but I suspect the slash might obscure too much of the tap.

**Comment by CoDEmanX** [comment]
As far as I remember, Google uses a slightly longer slash in certain icons where it would otherwise end at or close to the border of the base icon.

**Comment by goyney** [comment]
[![water-pump-off](https://materialdesignicons.com/icon/water-pump-off)](https://materialdesignicons.com/icon/water-pump-off)
