### ISSUE TITLE
AC DC signs

### ISSUE THREAD

**Issue by redskinhu** [Templarian/MaterialDesign#3006]
Hello

Like this
https://qph.ec.quoracdn.net/main-qimg-92f6f6607cd340ffd296de7426f67081.webp

Thanks

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/38305559-40545532-37db-11e8-9ab5-6d57edf2c903.png)![image](https://user-images.githubusercontent.com/18645219/38305542-328782b2-37db-11e8-8977-aa34b665b617.png)
[Download link](https://github.com/Templarian/MaterialDesign/files/1875529/icons.zip)

**Comment by Croutonix** [comment]
AC icon with less nodes
[![image](https://user-images.githubusercontent.com/18645219/38763103-f233080a-3f62-11e8-8c58-da2baa83df47.png)](https://github.com/Templarian/MaterialDesign/files/1909908/icon.zip)

**Comment by CoDEmanX** [comment]
If the icon is supposed to symbolize a sine wave, then it doesn't quite cut it:

![grafik](https://user-images.githubusercontent.com/1309249/38763219-0386c0b8-3f97-11e8-8a17-3d44dd1feefb.png)

**Comment by redskinhu** [comment]
Hi

Just a question, when will they be available?

Thx
T

**Comment by Templarian** [comment]
@redskinhu They were not tagged in a milestone so they were left in the void. I'll add them to the next milestone.

**Comment by redskinhu** [comment]
Thanks

**Comment by CoDEmanX** [comment]
Is there a tool to construct an accurate sine wave path?

**Comment by Croutonix** [comment]
Yes you can plot functions but you'll end up with a lot of nodes and a similar result. 
And yes the first AC icon was better I think.

**Comment by Templarian** [comment]
[![current-ac](https://materialdesignicons.com/icon/current-ac)](https://materialdesignicons.com/icon/current-ac) [![current-dc](https://materialdesignicons.com/icon/current-dc)](https://materialdesignicons.com/icon/current-dc)

Redid the vector for the `current-ac` minimal point data while keeping the shape.
