### ISSUE TITLE
(no) motion sensor/detected

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3007]
please consider a motion detection icon, in on and /off status. Maybe something like this:

![20180403_133304879_ios](https://user-images.githubusercontent.com/33354141/38257104-f32a6240-375f-11e8-89e3-1a4f6d317dd8.jpg)

close-up:
![schermafbeelding 2018-04-03 om 16 56 45](https://user-images.githubusercontent.com/33354141/38257167-0be4ad2c-3760-11e8-96cd-609209f6d72f.jpg)

using mdi:run-fast now, which is approaching the purpose, but above would be even better? Hope it is a viable suggestion.
Obviously, -off situation would have the radiation slashed ;-)
Cheers,
Marius

**Comment by Templarian** [comment]
I'm wondering if we should have floor sensors and wall sensors. This makes me think ceiling motion lights or something.

**Comment by CoDEmanX** [comment]
@Templarian Any idea how to depict that?

**Comment by PeterShaggyNoble** [comment]
This was added over the weekend:

[![motion-sensor](https://user-images.githubusercontent.com/15157491/51477062-2b899600-1d7f-11e9-86b3-4cd10f682769.png)](https://materialdesignicons.com/icon/motion-sensor)

**Comment by Tiebe** [comment]
would anyone be able to make an off version of this? I am making a switch and would like it to change between on and off!
