### ISSUE TITLE
Calories-icon

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#301]

**Comment by Templarian** [comment]
What does a calories icon look like?

**Comment by matthew2402** [comment]
Sorry just forgot to add the example-.-'

https://www.endomondo.com/gfx/campaign/home/calories_icon.png

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/fire ?

**Comment by matthew2402** [comment]
Hah perfekt, didn't see this ;)

**Comment by Templarian** [comment]
No problem, there are a lot of icons, easy to overlook.

**Comment by CoDEmanX** [comment]
Google uses a separate icon for calories burned (different from their fire icon) in Google Fit app:
![Imgur](http://i.imgur.com/9WKJ1Z2.jpg?1)
