### ISSUE TITLE
coffee-off/coffee-off-outline

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3010]
please consider 
- coffee-empty (coffee-outline with a low level line) 

and 

- coffee-off (coffee-outline with a slash)

goal is obvious:

coffee-off: machine is off
coffee-empty: machine is on but out of water

real life use cases, and very important ones.... ;-)

Cheers,
Marius

**Comment by henriquecm** [comment]
Here the icons

![mdi_coffee](https://user-images.githubusercontent.com/15136037/38403556-a70226a0-393a-11e8-9f68-b6118359ab14.png)

[coffee.zip](https://github.com/Templarian/MaterialDesign/files/1882695/coffee.zip)

**Comment by goyney** [comment]
[![coffee-off](https://materialdesignicons.com/icon/coffee-off)](https://materialdesignicons.com/icon/coffee-off)[![coffee-off-outline](https://materialdesignicons.com/icon/coffee-off-outline)](https://materialdesignicons.com/icon/coffee-off-outline)
