### ISSUE TITLE
If I am using the font glyph installed on my PC, where can I just copy the character of that icon on our glyph guide website?

### ISSUE THREAD

**Issue by Mancerrss** [Templarian/MaterialDesign#3012]
Tried so hard but all I can see is the details, export options, advanced exports options and that's all? Isn't there really a character that I can just copy on our website, isn't there a feature of that already or not yet. If there's not it's ridiculous that we still don't have that yet. Please we should have that on our website

Like for an [emoji](https://emojipedia.org), for example I don't have a font glyph tool to pick an icon or character on that, I can just use the website to copy the character back to my design tool.

**Comment by JohannesPertl** [comment]
New cheatsheet link: https://pictogrammers.github.io/@mdi/font/6.5.95/

**Comment by Templarian** [comment]
@JohannesPertl That is generally fine, but for those installing the font always use the Desktop Font files.

https://github.com/Templarian/MaterialDesign-Font That includes a cheatsheet and is updated more regularly.
