### ISSUE TITLE
Google Duo

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3013]
Allo was added in #2277 but there was also a Duo icon included in that issue which we have yet to add. Below is @MrGrigri's original contribution on the left and my own attempt at removing the camera on the right, for consistency with the Allo icon.

[![google-duo](https://user-images.githubusercontent.com/15157491/38373104-54268680-38e8-11e8-9502-f04ecef142ea.png)](https://github.com/Templarian/MaterialDesign/files/1173828/google.-.duo.zip) [![google-duo](https://user-images.githubusercontent.com/15157491/38373190-8d26b90a-38e8-11e8-8ea9-59aaa266f11e.png)](https://github.com/Templarian/MaterialDesign/files/1880505/google-duo.zip)

**Comment by CoDEmanX** [comment]
Well, the Allo icon we have is somewhat wrong. The outer shape is integral part of the icon:

![image](https://user-images.githubusercontent.com/1309249/38773309-54e91d4a-4049-11e8-811f-24eca582de0d.png)

If we were to match the duo icon, then we would end up with `camcorder` only. The other way around, we would need to keep the Duo icon with the camcorder, but add the outer shape to our Allo icon.

**Comment by GreenTurtwig** [comment]
@codemanx The Allo icon we currently have is correct, it's what Google use for notifications. Duo just uses `camcorder` for it's notifications, so we should probably add an alias rather than going with the contributions above. 🐈

**Comment by PeterShaggyNoble** [comment]
Google have added their own Duo icon to the new icon set:

[![duo](https://user-images.githubusercontent.com/15157491/39876088-3acd72b4-546a-11e8-9ce4-2c2b52c71b50.png)](https://material.io/tools/icons/?search=duo&icon=duo&style=baseline)

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
