### ISSUE TITLE
Doctor

### ISSUE THREAD

**Issue by sodiqOladeni** [Templarian/MaterialDesign#3014]
drug, medication intake, intake

**Comment by PeterShaggyNoble** [comment]
Can you elaborate, please and provide an example? We already have a `pill` icon.

[![pill](https://user-images.githubusercontent.com/15157491/38377590-29186a52-38f3-11e8-8387-114e13a4afb1.png)](https://materialdesignicons.com/icon/pill)

**Comment by sodiqOladeni** [comment]
https://fontawesome.com/icons/user-md?style=solid

**Comment by PeterShaggyNoble** [comment]
Duplicate of #2245
