### ISSUE TITLE
Human icons

### ISSUE THREAD

**Issue by henriquecm** [Templarian/MaterialDesign#3015]
I made some human icons, 9 in total:

- male-male
- female-female
- male-boy
- female-boy
- male-girl
- female-girl
- boy-boy
- boy-girl
- girl-girl

![human-icons](https://user-images.githubusercontent.com/15136037/38402444-aa163a14-3932-11e8-9515-1e84bc5837ee.png)

[human icons.zip](https://github.com/Templarian/MaterialDesign/files/1882595/human.icons.zip)

**Comment by Templarian** [comment]
These will be added in the next release. Adding the high priority label so it isn't skipped.

**Comment by Templarian** [comment]
I left off the `kid-kid` combinations as it's a tad too specific. Added the others to the contributor account. You can see them on the history page. http://dev.materialdesignicons.com/history

If you want a contributor account let me know since this technically is more than 5 icons.

**Comment by henriquecm** [comment]
I would like the contributor account, I have many icons that I started working on but didn't have time to finish, and others that I have submitted.
