### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by henriquecm** [Templarian/MaterialDesign#3017]
A podcast icon

![podcast](https://user-images.githubusercontent.com/15136037/38402734-b54fc57e-3934-11e8-92b0-6f7fd7ee7f73.png)

[podcast.zip](https://github.com/Templarian/MaterialDesign/files/1882628/podcast.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for the request. However this is a duplicate of #1303.
