### ISSUE TITLE
Cart icons

### ISSUE THREAD

**Issue by henriquecm** [Templarian/MaterialDesign#3018]
Cart Icons:

- cart-arrow-down
- cart-arrow-up
- cart-minus
- cart-remove
- cart-check
- cart-settings
- cart-info-circle
- cart-info

Edit 1: I forgot to merge the shapes

Edit 2: cart-settings looked weird when exported with 1 decimal only, so I exported with 2.

![mdi_cart](https://user-images.githubusercontent.com/15136037/38402804-55aa2dc0-3935-11e8-8aa9-1100973a103f.png)

[cart.zip](https://github.com/Templarian/MaterialDesign/files/1882655/cart.zip)

**Comment by PeterShaggyNoble** [comment]
See also #775

**Comment by goyney** [comment]
Closing as a duplicate of #775.
