### ISSUE TITLE
Science, Chemistry, Biology icons

### ISSUE THREAD

**Issue by henriquecm** [Templarian/MaterialDesign#3019]
24 icons:

- ~~atom_alt (the that exists now doesn't look very good in some cases)~~ - Exists as [`atom`](https://materialdesignicons.com/icon/atom)
- ~~atom_alt_2 (this looks like atom ide but it also could be used)~~ - Exists as [`atom`](https://materialdesignicons.com/icon/atom)
- ~~syringe~~ - Exists as [`needle`](https://materialdesignicons.com/icon/needle)
- ~~beaker_empty~~ - Exists as [`beaker`](https://materialdesignicons.com/icon/beaker)
- ~~beaker_full~~ - See #3774
- ~~electron_nucleus~~ - Exists as [`orbit`](https://materialdesignicons.com/icon/orbit)
- test_tube_rack
- ~~test_tube_empty~~ - Exists as [`test-tube-empty`](https://materialdesignicons.com/icon/test-tube-empty)
- ~~test_tube_full~~ - Exists as [`test-tube`](https://materialdesignicons.com/icon/test-tube)
- ~~flask_full~~ - Exists as [`flask`](https://materialdesignicons.com/icon/flask)
- graduated_cylinder
- burner
- round_flask_empty
- round_flask_reaction
- round_flask_full
- ~~mortar_pestle~~ - Exists as [`bowl`](https://materialdesignicons.com/icon/bowl)
- tongs
- ~~funnel_outline~~ - Exists as [`filter`](https://materialdesignicons.com/icon/filter-outline)
- ~~funnel~~ - Exists as [`filter`](https://materialdesignicons.com/icon/filter)
- rna
- virus
- bacteria
- hiv
- ~~ebola~~ - Exists as [`gesture`](https://materialdesignicons.com/icon/gesture)
- carbon_bond

![mdi-science](https://user-images.githubusercontent.com/15136037/38404195-aee0fa78-393e-11e8-88bc-913c17caa3fd.png)

[science.zip](https://github.com/Templarian/MaterialDesign/files/1882752/science.zip)

**Comment by CoDEmanX** [comment]
We already have icons in MDI for syringe, atom, test tubes, empty beaker, pot mix, filters.

The remaining ones need to be revised IMO, e.g. some rounded corners should go.

**Comment by henriquecm** [comment]
But the current atom icon, don't resemble what people usually are accustomed to an atom symbol, which has 3 ellipses.
The second atom icon can be used as atom icon and the Atom editor icon.
The funnel, beaker, test tube, I didn't check before, I was making them without paying too much attention.

**Comment by PeterShaggyNoble** [comment]
- The problem with having 3 orbits in the `atom` icon (to my eye at least) is that it's a lot of detail, which gets lost at 24*24.
- We won't be adding the Atom editor icon; see #1527 for more on that.
- `syringe` already exists.
- `beaker` already exists.
- We could probably do with adding `beaker-full` (maybe as `breaker`, renaming the existing one as `beaker-empty`) but it would need to match the design of the existing icon.
- `orbit` should cover `electron_nucleus`.
- `test-tube-rack` could probably be useful to some people but it needs a bit of work.
- `test-tube` and `test-tube-empty` already exist.
- We already have 4 variations of `flask`.
- Like `test-tube-rack`, the 5 icons on the 3rd row could be useful to some people but, again, they'll need a bit of work.
- `bowl` should cover `mortar-pestle`. We could alias that.
- `tongs`: see above comment on `test-tube-rack`.
- `funnel` already exists as `filter`. I'll add aliases to those shortly.

The icons on the last line are mixed up, I think; it looks like there's one missing, but:
- Would `dna` work for the first one, or is it something completely different?
- The second, the third and last ones need to be clarified (what they represent and what they could be used for.
- `gesture` should work for the 4th one.

Requests for large collections of icons tend to get lost in the ether after a few of them have been added so, to help us track them better, could you edit this issue down to a request for a single icon, please, and open a new one for each additional request not covered above? You can group the round flasks into a single issue as they're directly related to each other.

**Comment by CoDEmanX** [comment]
> Like DNA, RNA is assembled as a chain of nucleotides, but unlike DNA it is more often found in nature as a **single-strand folded onto itself**, rather than a paired double-strand.

Furthermore, RNA has a different uracil instead of thymine as one of its four nucleobases. And of course other functions than DNA. The icon looks good to me.

I don't think order is mixed up, look actually correct like this:

![grafik](https://user-images.githubusercontent.com/1309249/38741073-61a41c08-3f39-11e8-8eac-a95f0f621006.png)

Virus can apparently be depicted like that, but also very similar to a bacterium:

![grafik](https://user-images.githubusercontent.com/1309249/38740983-19f8fac2-3f39-11e8-8b60-a1fa7431714f.png)

I guess the top part represents the capsid (virus hull) with DNA inside. Not sure what the other lines correspond to.

![grafik](https://user-images.githubusercontent.com/1309249/38741180-9a1a9792-3f39-11e8-9640-dc63197aafa9.png)

**Comment by JamesCoyle** [comment]
Closing this out. Please open individual issues for any missing icons.
