### ISSUE TITLE
weight-gram

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#302]
Check the example: http://www.decowoerner.com/images/contentUploads/pictures/500_599/562/www/101000/562_669_00-1-0-00.jpg

Thanks for adding this! :)
- [x] weight
- [x] weight-kilogram
- [x] weight-pound
- [ ] weight-gram

**Comment by epelc** [comment]
+1 Here's another nice example
![image](https://cloud.githubusercontent.com/assets/5204642/7481754/72c8dfa2-f340-11e4-923b-bf3ef82121ff.png)

Also a dumbbell style one might be good too.

**Comment by PeterShaggyNoble** [comment]
Renaming as `weight-gram` with `weight-pound` tracked in #2373.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48685853-a28b8e00-eb86-11e8-84e7-2a1292e43e7e.png)
[weight-gram.zip](https://github.com/Templarian/MaterialDesign/files/2593746/weight-gram.zip)

**Comment by Templarian** [comment]
Added `weight-gram`.
