### ISSUE TITLE
home-currency-eur

### ISSUE THREAD

**Issue by lucasvdh** [Templarian/MaterialDesign#3020]
I'd love to see an icon like the `home-currency-usd` but with a euro sign. The purpose of the icon would be the same as `home-currency-usd` but a European version of it.

Basically a combination of the following two icons:
![home-currency-usd](https://user-images.githubusercontent.com/4311594/38409101-654078f2-3980-11e8-9710-151a95a9c980.png)  ![currency-eur](https://user-images.githubusercontent.com/4311594/38409106-6907d5a2-3980-11e8-9eb3-e9ed05a13a06.png)

**Comment by Templarian** [comment]
We're actually going to rework this icon to remove the usd $ symbol. Still thinking this through, but making currency versions will not be feasible.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
