### ISSUE TITLE
Latitude

### ISSUE THREAD

**Issue by GlennFernandes** [Templarian/MaterialDesign#3023]
An icon to display the latitude of a location for a property of an OTA. Could not find a suitable example for it.

**Comment by GlennFernandes** [comment]
I've created a an icon for it already. Not sure if its up to the mark. I'll upload it here either way
[latitude_dash.zip](https://github.com/Templarian/MaterialDesign/files/1885234/latitude_dash.zip)
[latitude.zip](https://github.com/Templarian/MaterialDesign/files/1885235/latitude.zip)

**Comment by goyney** [comment]
@MrGrigri Should we make a distinct longitude one as well? I know it's simply a 90 degree turn.

**Comment by PeterShaggyNoble** [comment]
How would a single, dashed line look?

**Comment by CoDEmanX** [comment]
Like the vertical lines dashed in Grigri's version, but the circle as-is?

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX, yes, but just a single line across the equator.

**Comment by goyney** [comment]
> @CoDEmanX, yes, but just a single line across the equator.

That would be an `equator` icon, IMO.

**Comment by goyney** [comment]
[![latitude](https://materialdesignicons.com/icon/latitude)](https://materialdesignicons.com/icon/latitude)
