### ISSUE TITLE
Longitude

### ISSUE THREAD

**Issue by GlennFernandes** [Templarian/MaterialDesign#3024]
An icon to display the longitude of a location for a property of an OTA. Could not find a suitable example for it. This is a continuation of issue #3023

**Comment by GlennFernandes** [comment]
I've created a an icon for it already. Not sure if its up to the mark.
[longitude_dash.zip](https://github.com/Templarian/MaterialDesign/files/1885256/longitude_dash.zip)
[longitude.zip](https://github.com/Templarian/MaterialDesign/files/1885257/longitude.zip)

**Comment by goyney** [comment]
[![longitude](https://materialdesignicons.com/icon/longitude)](https://materialdesignicons.com/icon/longitude)
