### ISSUE TITLE
New Pill icon

### ISSUE THREAD

**Issue by dominique-debert** [Templarian/MaterialDesign#3030]
For those who need medical icons. More to come.
[pill.ai.zip](https://github.com/Templarian/MaterialDesign/files/1888928/pill.ai.zip)

**Comment by CoDEmanX** [comment]
Wrong size (30x30) and we already have a pill icon. This one is more minimal, but I'm not convinced that this is still recognizable enough:

![image](https://user-images.githubusercontent.com/1309249/38490567-ba9a5dca-3be9-11e8-8d35-7bba970f440f.png)

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
