### ISSUE TITLE
account-medical

### ISSUE THREAD

**Issue by dominique-debert** [Templarian/MaterialDesign#3031]
[account-medical.ai.zip](https://github.com/Templarian/MaterialDesign/files/1888986/account-medical.ai.zip)

**Comment by CoDEmanX** [comment]
Imports into InkScape as 30x30 pixels, but even if scaled down, the plus symbol is still not grid-aligned:

![image](https://user-images.githubusercontent.com/1309249/38490443-660629ba-3be9-11e8-8bfb-93ec5b455eb3.png)

**Comment by goyney** [comment]
Considering the provided icon doesn't follow material standards, we already have an account with a "plus" or "cross" (`account-plus`) and there is the request for a doctor (#2245), I'm going to close this issue.
