### ISSUE TITLE
format-text-rotate

### ISSUE THREAD

**Issue by chuanyinglily** [Templarian/MaterialDesign#3034]
![fsicon7](https://user-images.githubusercontent.com/38234899/38533419-c0cd6c06-3cab-11e8-8732-e44eb1f90f2e.png)

this icon usually used in h5 app ,so you can take my advice .thanks.

**Comment by PeterShaggyNoble** [comment]
We have [a number of `*-align-*` icons](https://petershaggynoble.github.io/MDI-Sandbox/?filter=align) already and I don't see what this one would add to them - could you provide a use-case for it that isn't covered by the existing icons?

**Comment by chuanyinglily** [comment]
![1](https://user-images.githubusercontent.com/38234899/38606316-3f8cb310-3da8-11e8-9b59-7c36965c3182.png)
![2](https://user-images.githubusercontent.com/38234899/38606476-b1ac622e-3da8-11e8-8a2c-056ee4a708bd.png)
![3](https://user-images.githubusercontent.com/38234899/38606486-b510be74-3da8-11e8-8571-a9c1bbd20769.png)
this is a h5 editor. this icon is not an align icon . it is a arrangement icon

**Comment by CoDEmanX** [comment]
I think it's this one in particular:

![grafik](https://user-images.githubusercontent.com/1309249/38762971-3e7441cc-3f93-11e8-9224-b2887f096c89.png)

It doesn't rotate the text, but rather places characters in a column

`ABCD`

to
```
A
B
C
D
```

Note that these icons are in the extended set (text rotate *): https://petershaggynoble.github.io/MDI-Sandbox/extended/

**Comment by chuanyinglily** [comment]
I just need to arrange the text. So either the vertical cat or the horizontal.

**Comment by chuanyinglily** [comment]
yes,it is similar but if i want to turn horizontal to vertical ,how should i do . So I hope you can make an icon according to my picture.

**Comment by PeterShaggyNoble** [comment]
Generally you'd toggle between the two so it's clear what will happen when the icon is clicked.

![text rotate vertical](https://user-images.githubusercontent.com/15157491/38805513-f86288e2-416d-11e8-8fbe-fd3f92898018.png) ![text rotation none](https://user-images.githubusercontent.com/15157491/38805676-9ab3ceb2-416e-11e8-85ae-3560d2810422.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49037331-f5b5a000-f187-11e8-9049-e36c4c509f21.png)![image](https://user-images.githubusercontent.com/1015040/49037357-036b2580-f188-11e8-8177-df3fce888205.png)
![image](https://user-images.githubusercontent.com/1015040/49037364-08c87000-f188-11e8-8d50-c407e105a414.png)![image](https://user-images.githubusercontent.com/1015040/49037377-0f56e780-f188-11e8-9912-dd5dc3a3ae8b.png)
![image](https://user-images.githubusercontent.com/1015040/49037411-25fd3e80-f188-11e8-9cf1-37f2c2ba1af1.png)

[format-text-rotate.zip](https://github.com/Templarian/MaterialDesign/files/2617064/format-text-rotate.zip)

**Comment by PeterShaggyNoble** [comment]
The extended icon set also includes angled versions of this:

[![text_rotation_angledown](http://mdi.houseofdesign.ie/tools/preview/?icon=text_rotation_angledown&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/) [![text_rotation_angleup](http://mdi.houseofdesign.ie/tools/preview/?icon=text_rotation_angleup&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by goyney** [comment]
Yes, @PeterShaggyNoble, good find. We should add those 2 as well. They are very useful in spreadsheet applications.

**Comment by goyney** [comment]
[![format-text-rotation-none](https://materialdesignicons.com/icon/format-text-rotation-none)](https://materialdesignicons.com/icon/format-text-rotation-none)
[![format-text-rotation-vertical](https://materialdesignicons.com/icon/format-text-rotation-vertical)](https://materialdesignicons.com/icon/format-text-rotation-vertical)
[![format-text-rotation-up](https://materialdesignicons.com/icon/format-text-rotation-up)](https://materialdesignicons.com/icon/format-text-rotation-up)
[![format-text-rotation-down](https://materialdesignicons.com/icon/format-text-rotation-down)](https://materialdesignicons.com/icon/format-text-rotation-down)
[![format-text-rotation-down-vertical](https://materialdesignicons.com/icon/format-text-rotation-down-vertical)](https://materialdesignicons.com/icon/format-text-rotation-down-vertical)
[![format-text-rotation-angle-up](https://materialdesignicons.com/icon/format-text-rotation-angle-up)](https://materialdesignicons.com/icon/format-text-rotation-angle-up)
[![format-text-rotation-angle-down](https://materialdesignicons.com/icon/format-text-rotation-angle-down)](https://materialdesignicons.com/icon/format-text-rotation-angle-down)
