### ISSUE TITLE
Sqaure, saw, sine, triangle wave

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3036]
Something like this for digital:

![digital-serial-waveform](https://cloud.githubusercontent.com/assets/1633459/15373940/8ab8c7a6-1d0d-11e6-8757-8f937aab454e.png)

![grafik](https://user-images.githubusercontent.com/1309249/38639371-36ca598e-3dd1-11e8-803a-93422ce0e8cf.png)

Analog would be like a sine curve I guess?

A combination of both could represent analog/digital converters, such as for audio signals (also vice versa).

**Comment by Croutonix** [comment]
See #3006 for analog sine wave.

**Comment by CoDEmanX** [comment]
Maybe `current-ac` can be used for analog signal as well.

![grafik](https://user-images.githubusercontent.com/1309249/38639287-ff4f537e-3dd0-11e8-9b8d-fadf7eb37002.png)

In that case, it would be nice to make the digital signal icon somewhat similar.

**Comment by CoDEmanX** [comment]
Nice work. Wave 3 is not fully on grid though, so not sure.

Now that I think about it, we could also use interpolation icons:

![grafik](https://user-images.githubusercontent.com/1309249/38763170-2ecb7972-3f96-11e8-81e5-048c857562b5.png)

**Comment by Louistwee** [comment]
![image](https://user-images.githubusercontent.com/27563848/44868483-34bc7e00-ac8b-11e8-8e54-321433986201.png)

**Comment by goyney** [comment]
Thanks, @Louistwee, for creating a new issue for the bezier curve: https://git.jpg.com/preditor/preditor/merge_requests/375/diffs

**Comment by JamesCoyle** [comment]
Could do to replace that current-ac with an actual mathematical sinewave

**Comment by goyney** [comment]
If we're going to add those four, we need contributions to add them. Pulling this back in the Backlog until that happens.

**Comment by goyney** [comment]
This issue will be address in #4346. Even though that's the duplicate, there are contributions there, so going to close this one.
