### ISSUE TITLE
How do I search/filter for an icon by a string?

### ISSUE THREAD

**Issue by blord-fullscreen** [Templarian/MaterialDesign#3037]
Looking at:

https://materialdesignicons.com

I miss the search/filter functionality of something like icomoon (search bar prominently at the top):

https://icomoon.io/app/#/select

Even if you don't/can't/won't build something like that, at least label the icons with their file names so that in-page browser based search can work. I spend way too much time trying to figure out what is where is this repo.

Thanks for listening.

**Comment by Templarian** [comment]
I'm not sure I understand? The search bar searches across "name" and the list of aliases assigned to every icon.

We even map `ctrl+f` to map to the search box.

Either way we're working on the new site so closing out this issue.

http://dev.materialdesignicons.com/icons (all cache is set to 5 minute expire on that box, so may take a second to load if someone hasn't hit that box in 5 minutes).
