### ISSUE TITLE
Cloud-Question

### ISSUE THREAD

**Issue by Qeis984** [Templarian/MaterialDesign#3039]
I have a idea, a icon of unknown weather. Cloud with ? symbol at front it.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/42590547-1e6bd0f6-8512-11e8-8b29-db82880652a1.png)

[cloud-question.zip](https://github.com/Templarian/MaterialDesign/files/2185641/cloud-question.zip)

**Comment by Templarian** [comment]
[![cloud-question](https://materialdesignicons.com/icon/cloud-question)](https://materialdesignicons.com/icon/cloud-question)
