### ISSUE TITLE
Bookmark-check, Bookmark-plus (Play Store style )

### ISSUE THREAD

**Issue by matejkepes** [Templarian/MaterialDesign#304]
![11130778_10205679839268185_199401809_n 1](https://cloud.githubusercontent.com/assets/1282545/7310021/daaf58cc-ea25-11e4-87c5-05dd4aa96657.jpg)
![11169011_10205679839548192_1304129914_n 1](https://cloud.githubusercontent.com/assets/1282545/7310026/e4995c48-ea25-11e4-98f1-3774ea3cb7d7.jpg)

Thank you :)

**Comment by Templarian** [comment]
Do you have a screenshot?

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/bookmark-outline-plus
http://materialdesignicons.com/icon/bookmark-plus
http://materialdesignicons.com/icon/bookmark-check
