### ISSUE TITLE
Duplicate currency

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#3040]
`currency-cny` is the same as `currency-jpy`. Shouldn't this be an alias instead? There are a few more duplicate icons that I had noticed but I don't remember which.

**Comment by JapanYoshi** [comment]
This is intentional, possibly to prepare for a time when Chinese Yuan and Japanese Yen no longer share the same symbol.

**Comment by PeterShaggyNoble** [comment]
One use case for including it as both CNY & JPY is to avoid the need for conditionals in your code.
