### ISSUE TITLE
chevron-triple-left

### ISSUE THREAD

**Issue by asilberschneider** [Templarian/MaterialDesign#3042]
[chevron-triple-left.zip](https://github.com/Templarian/MaterialDesign/files/1898582/chevron-triple-left.zip)
Proposed Usage: Breadcrumb which indicates that some levels are skipped/not shown
![image](https://user-images.githubusercontent.com/3582566/38614329-03a7c6c0-3d8d-11e8-8a3f-3887ae8594a2.png)

**Comment by PeterShaggyNoble** [comment]
We already have an open request for `chevron-triple-up` in #1083, which includes a stock icon. As this is directly related, let's use that issue to track all 4.
