### ISSUE TITLE
Message-Secure

### ISSUE THREAD

**Issue by koystinen** [Templarian/MaterialDesign#3043]
"Message-Secure" as standard message icon with little lock used to indicate everything secure, like
Send-Secure or Email-Secure

**Comment by koystinen** [comment]
@CoDEmanX Bravo! 
This responses in this community never ceases to amaze me!

**Comment by MrGrigri** [comment]
Shouldn't all messages be secure?

**Comment by goyney** [comment]
[![message-lock](https://materialdesignicons.com/icon/message-lock)](https://materialdesignicons.com/icon/message-lock)[![message-text-lock](https://materialdesignicons.com/icon/message-text-lock)](https://materialdesignicons.com/icon/message-text-lock)
