### ISSUE TITLE
Globe (3D scale model of Earth)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3044]
![grafik](https://user-images.githubusercontent.com/1309249/38640650-27444aac-3dd5-11e8-8784-438e56a5dd85.png)

Download: [globe2.zip](https://github.com/Templarian/MaterialDesign/files/1900343/globe2.zip)

Ref: #873

**Comment by Templarian** [comment]
[![globe-model](https://materialdesignicons.com/icon/globe-model)](https://materialdesignicons.com/icon/globe-model)
