### ISSUE TITLE
vector-link

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3045]
![grafik](https://user-images.githubusercontent.com/1309249/38641107-76660476-3dd6-11e8-9a88-f07d5947b278.png)

Download: [vector-link.zip](https://github.com/Templarian/MaterialDesign/files/1900374/vector-link.zip)

Ref: #873

**Comment by goyney** [comment]
[![vector-link](https://materialdesignicons.com/icon/vector-link)](https://materialdesignicons.com/icon/vector-link)
