### ISSUE TITLE
pan-variant (vertical, horizontal, four-way)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3046]
As seen in e.g. Chrome when panning / scrolling with middle mouse button:

![grafik](https://user-images.githubusercontent.com/1309249/38645938-3d176600-3de6-11e8-89e5-ef97b9201559.png)
![grafik](https://user-images.githubusercontent.com/1309249/38645947-4c8297c2-3de6-11e8-863d-59343247d9e6.png)
![grafik](https://user-images.githubusercontent.com/1309249/38645962-5aa76580-3de6-11e8-8b60-8d84768eb441.png)

Download: [pan-variant.zip](https://github.com/Templarian/MaterialDesign/files/1900677/pan-variant.zip)

**Comment by PeterShaggyNoble** [comment]
The Extended icon set includes yet another variation:

[![control camera](https://user-images.githubusercontent.com/15157491/38665209-b88d7476-3e33-11e8-8b33-a88fd2002744.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by CoDEmanX** [comment]
So vertical and horizontal panning is off the table?

**Comment by PeterShaggyNoble** [comment]
Sorry, @CoDEmanX, should have scrolled up to the original post before closing this. Reopened.

**Comment by Templarian** [comment]
Wait, the icon I added was a different icon. I didn't even know about that one. I'll modify it to match these others for consistency.

**Comment by Templarian** [comment]
[![pan](https://materialdesignicons.com/icon/pan)](https://materialdesignicons.com/icon/pan) [![pan-vertical](https://materialdesignicons.com/icon/pan-vertical)](https://materialdesignicons.com/icon/pan-vertical) [![pan-horizontal](https://materialdesignicons.com/icon/pan-horizontal)](https://materialdesignicons.com/icon/pan-horizontal) [![camera-control](https://materialdesignicons.com/icon/camera-control)](https://materialdesignicons.com/icon/camera-control)

**Comment by CoDEmanX** [comment]
This is what Firefox uses for scrollwheel panning BTW:
![grafik](https://user-images.githubusercontent.com/1309249/46012192-b8ba2800-c0c8-11e8-8954-6d370eb41fa9.png)

Chrome is monochrome (no pun intended):
![grafik](https://user-images.githubusercontent.com/1309249/46012282-00d94a80-c0c9-11e8-942d-b835ae2f9c62.png)

And scrollwheel panning in Chrome in action (zoom 2x):
![2018-09-25 13-49-39 mp4](https://user-images.githubusercontent.com/1309249/46013101-80681900-c0cb-11e8-8555-3c8cc8427e44.gif)

Maybe add these as 8 directional icons as well? Could be useful as navigation buttons for streetview style apps or as cursors like in Chrome.

**Comment by Templarian** [comment]
Agreed, don't worry about making them, I'll add them.

**Comment by Templarian** [comment]
These were added, forgot to close the issue.
