### ISSUE TITLE
satellite-uplink

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3047]
Any interest in adding this?

![uplink](https://cloud.githubusercontent.com/assets/1309249/14904343/f3b931c0-0da7-11e6-866a-2d1ba360cbde.png)

Seen such an icon in a GPS app, which displays it while GPS is active.

**Comment by Templarian** [comment]
Yea, I think it's useful enough maybe add a tiny line to show it's attached to the ground. Satellite tv style.

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/38769311-15708c40-4001-11e8-8c58-08a302203ee1.png)

Download: [uplink2.zip](https://github.com/Templarian/MaterialDesign/files/1910463/uplink2.zip)

**Comment by Templarian** [comment]
[![satellite-uplink](https://materialdesignicons.com/icon/satellite-uplink)](https://materialdesignicons.com/icon/satellite-uplink)
