### ISSUE TITLE
Antenna variants? (Send signal)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3048]
Do we want a variant of `access-point` like Nova has? They also have one which broadcasts "up":

![grafik](https://user-images.githubusercontent.com/1309249/38646813-cd77082e-3de9-11e8-8c32-561f7bfe4427.png) ![grafik](https://user-images.githubusercontent.com/1309249/38646818-d20b52f0-3de9-11e8-947b-a8495b2cdcf9.png)

**Comment by goyney** [comment]
[![antenna](https://materialdesignicons.com/icon/antenna)](https://materialdesignicons.com/icon/antenna)
