### ISSUE TITLE
bullseye-arrow

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3049]
Seen this in the wild for a button "precision". Could be used as a bit more specific variant of `bullseye` for e.g. target marketing:

![grafik](https://user-images.githubusercontent.com/1309249/38650310-67b79e7e-3dfb-11e8-8345-a96bf2757a49.png)

Download: [target-arrow.zip](https://github.com/Templarian/MaterialDesign/files/1900935/target-arrow.zip)

**Comment by Templarian** [comment]
[![bullseye-arrow](https://materialdesignicons.com/icon/bullseye-arrow)](https://materialdesignicons.com/icon/bullseye-arrow)

**Comment by PeterShaggyNoble** [comment]
Alias `target-arrow` added.
