### ISSUE TITLE
pulse icon

### ISSUE THREAD

**Issue by justinlawrence** [Templarian/MaterialDesign#305]
examples are here: http://glyphsearch.com/?query=pulse

here's a screenshot:
![screenshot 2015-04-24 09 33 08](https://cloud.githubusercontent.com/assets/1521183/7315401/f6ac7f3e-ea64-11e4-8382-45051e20b953.png)

- [ ] pulse

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/pulse

**Comment by justinlawrence** [comment]
Wow, that's incredible! Thanks guys!!
