### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by bernaferrari** [Templarian/MaterialDesign#3050]
Google Material Components Catalog sample for iOS includes this icon, which is very nice to represent a "demo". So, I think it would be nice to see it (or even a variation from it) in your library.

<img width="58" alt="screen shot 2018-04-12 at 00 31 48" src="https://user-images.githubusercontent.com/351125/38655084-e9a16f9a-3de8-11e8-834b-1b82cee19b56.png">

[demo.pdf](https://github.com/Templarian/MaterialDesign/files/1901214/demo.pdf)

**Comment by CoDEmanX** [comment]
Is the circle outline part of the icon? I would suggest ot drop it.

**Comment by bernaferrari** [comment]
Yeah, but I also think dropping it wouldn't hurt. It is easy to make a round corner later if the developer so desires.

**Comment by goyney** [comment]
[![cellphone-play](https://materialdesignicons.com/icon/cellphone-play)](https://materialdesignicons.com/icon/cellphone-play)
