### ISSUE TITLE
Google Maps plus code

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3051]
So called "plus codes" seem to be identifiers for places. Dunno if something like a geohash is encoded in there.

![grafik](https://user-images.githubusercontent.com/1309249/38673714-64f8f3fc-3e52-11e8-91e6-8949c3ec29ba.png)

Can't think of other use cases though.

**Comment by PeterShaggyNoble** [comment]
[Here](https://plus.codes/static/about/images/utils/pc-logo.svg)'s an SVG of their logo but I'd day it'll be a good while before this takes off. Tried to find my home address and it gave me a code that covered 91 units in my estate! That's if it takes off at all, [we tried to do it here](https://www.eircode.ie/) and it fell flat on it's face.

**Comment by PeterShaggyNoble** [comment]
Google have now added this to Google Maps.

**Comment by GreenTurtwig** [comment]
The original post included a screenshot from Maps, it's been in for quite a while. :-P

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
