### ISSUE TITLE
Tram side view (Google Maps)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3052]
This is used instead of https://material.io/icons/#ic_tram in the route description:

![grafik](https://user-images.githubusercontent.com/1309249/38674072-7ec9f51e-3e53-11e8-81b1-6834510e9d42.png)

![grafik](https://user-images.githubusercontent.com/1309249/38675200-35ad9cba-3e57-11e8-9fa6-56b6e62a3819.png)

Download: [tram_sideview.zip](https://github.com/Templarian/MaterialDesign/files/1902940/tram_sideview.zip)

**Comment by goyney** [comment]
[![tram-side](https://materialdesignicons.com/icon/tram-side)](https://materialdesignicons.com/icon/tram-side)
