### ISSUE TITLE
Meeting Room

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3053]
An alternative to our door icon from Google's extended icon set.

[![meeting room](https://user-images.githubusercontent.com/15157491/38689065-7b8be0fa-3e72-11e8-88e4-177686b40f01.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/) [![no meeting room](https://user-images.githubusercontent.com/15157491/38689086-8f0f2754-3e72-11e8-8776-34f71342504b.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by GreenTurtwig** [comment]
We've been discussing replacing the current door icons with these but we need more feedback on the closed design, specifically the size and position of the door, so posting these here.

![](https://user-images.githubusercontent.com/15905797/38691894-0f88fea8-3e7a-11e8-8494-2be604d5c6ec.png)![](https://user-images.githubusercontent.com/15905797/38691909-1d193e5c-3e7a-11e8-8efd-602387969675.png)

**Comment by CoDEmanX** [comment]
They look oddly like a free-standing doors, but no clue how to improve on that.

**Comment by goyney** [comment]
I feel our current doors are perfectly fine and these are not needed, especially since we've added a couple variations on our current doors (such as `-lock`).

**Comment by CoDEmanX** [comment]
I do like the Google door, and especially the availability of the strikethrough variant. This is used in Google Calender for booking rooms for instance.

**Comment by goyney** [comment]
We are not going to add a new door style at this time.
