### ISSUE TITLE
credit-card-settings

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3054]
Created this for #2718 then realised it doesn't quite suit what @Maur0V is looking for.

[![image](https://user-images.githubusercontent.com/15157491/38690438-064e585a-3e76-11e8-8b9d-9ce955551beb.png)](https://github.com/Templarian/MaterialDesign/files/1904093/credit-card-settings.zip)

**Comment by Templarian** [comment]
[![credit-card-settings](https://materialdesignicons.com/icon/credit-card-settings)](https://materialdesignicons.com/icon/credit-card-settings)
