### ISSUE TITLE
Departure Board

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3055]
I'm going to need this on an upcoming site and thought others might find it useful too.

[![departure board](https://user-images.githubusercontent.com/15157491/38691031-85fa349c-3e77-11e8-905b-630a76b7ee51.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by GreenTurtwig** [comment]
We also have `timetable` :cat2:

[![](https://materialdesignicons.com/icon/timetable)](https://materialdesignicons.com/icon/timetable)

**Comment by PeterShaggyNoble** [comment]
The use case on the site I'll be working on is to indicate what time the bus leaves on a day trip. `clock` alone would do the job nicely, but I felt `departure board` communicated better.

**Comment by Templarian** [comment]
Obviously called it `bus-clock` but we have an alias added also.

[![bus-clock](https://materialdesignicons.com/icon/bus-clock)](https://materialdesignicons.com/icon/bus-clock)
