### ISSUE TITLE
Request: Icons from Google Camera

### ISSUE THREAD

**Issue by shmshd12** [Templarian/MaterialDesign#3056]
![screenshot_20180413-234532](https://user-images.githubusercontent.com/11484121/38754976-18ae5450-3f75-11e8-9e71-7c275da5d9b1.png)

Google have new icons in the Google Camera app which is not yet available in [Google's Icons page](https://material.io/icons/). Icons are as follow:

- Camera photo back
- Camera photo front
- Camera video back
- Camera video front
- Video Stabilization

**Comment by Templarian** [comment]
[![video-stabilization](https://materialdesignicons.com/icon/video-stabilization)](https://materialdesignicons.com/icon/video-stabilization) [![camera-account](https://materialdesignicons.com/icon/camera-account)](https://materialdesignicons.com/icon/camera-account) [![camera-image](https://materialdesignicons.com/icon/camera-image)](https://materialdesignicons.com/icon/camera-image) [![video-account](https://materialdesignicons.com/icon/video-account)](https://materialdesignicons.com/icon/video-account) [![video-image](https://materialdesignicons.com/icon/video-image)](https://materialdesignicons.com/icon/video-image)
