### ISSUE TITLE
desk-chair

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3058]
as title,
please consider adding a dedicated desk-chair (office-chair)

![37246252-70051b38-24a6-11e8-93e4-7fcbe393ad50](https://user-images.githubusercontent.com/33354141/38769393-d010dee6-4002-11e8-8c61-ce8e8ab1e924.png)

**Comment by goyney** [comment]
Google has [`event-seat`](https://material.io/tools/icons/?search=sea&icon=event_seat&style=baseline) (which we should probably add).

Here's a variation on it to make it more desk-like:
![image](https://user-images.githubusercontent.com/1015040/41947526-09180e6e-7986-11e8-8288-38819332ebee.png)

**Source:** [desk-chair.zip](https://github.com/Templarian/MaterialDesign/files/2139467/desk-chair.zip)

**Comment by goyney** [comment]
[![chair-rolling](https://materialdesignicons.com/icon/chair-rolling)](https://materialdesignicons.com/icon/chair-rolling)
