### ISSUE TITLE
Search improvements - Search by Tags

### ISSUE THREAD

**Issue by justinlawrence** [Templarian/MaterialDesign#306]
It is quite difficult to find icons. Glypsearch do a great job of this search, having tagged most of the icons with many different words.

As per http://glyphsearch.com/?query=pulse

* They search tags (it would also be cool to be able to tag).
* They search on soundex as well.

Thanks!

**Comment by Templarian** [comment]
There is a functionality built in to alias icons at the moment, but few icons have aliases. There is an open issue for this, #90.

Currently the site does not search based on an tag information.

**Comment by CoDEmanX** [comment]
If I search for `question`, `help-circle` is found. Looks like aliases are searched too. Can't this issue be closed?

**Comment by Templarian** [comment]
Yea. I need to add more aliases to various icons, but yes the feature is complete.
