### ISSUE TITLE
Simplified currencies

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#3060]
Some currencies had a lot of nodes so I simplified them and made the nodes and bezier handles pixel perfect (or rounded to 0.5) The path lengths are cut in half or more, with little to no visual difference.

21 nodes -> 24 nodes
![image](https://user-images.githubusercontent.com/18645219/38769320-06bc3d70-3fcf-11e8-8b31-981223f0eb15.png)

28 nodes -> 16 nodes
![image](https://user-images.githubusercontent.com/18645219/38769463-cb4ed79a-3fd1-11e8-9257-e969b70951f4.png)

25 nodes -> 17 nodes
![image](https://user-images.githubusercontent.com/18645219/38769618-c111e996-3fd3-11e8-8484-b9bda44aa39e.png)

[Download link](https://github.com/Templarian/MaterialDesign/files/1910516/icons.zip)

**Comment by CoDEmanX** [comment]
@Croutonix There is quite a different in `currency-gbp`. Is that intended, or was it an outdated version of the original icon that you used by accident in the comparison?

**Comment by Croutonix** [comment]
It's intended to fix the bottom part that was very thin, made it 2px. Also I stretched it by 0.5px to make it centered.
