### ISSUE TITLE
arrow-collapse-horizontal not on grid

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3061]
[![arrow-collapse-horizontal](https://materialdesignicons.com/icon/arrow-collapse-horizontal)](https://materialdesignicons.com/icon/arrow-collapse-horizontal)

The vertical variant is shifted up to be on grid. Here is an adjusted one vertically centered and shifted to the right to be pixel perfect: [arrow-collapse-vertical.zip](https://github.com/Templarian/MaterialDesign/files/1910706/arrow-collapse-vertical.zip)

![image](https://user-images.githubusercontent.com/1309249/38771366-3c5b0e72-4022-11e8-8fd6-8225db0f420c.png)

**Comment by Templarian** [comment]
I really have to stop drinking when working on icons (or maybe it wasn't enough, will test). Fixed.

[![icon](https://materialdesignicons.com/icon/arrow-collapse-horizontal)](https://materialdesignicons.com/icon/arrow-collapse-horizontal)
