### ISSUE TITLE
Cleanup: Debian

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3063]
Creating this issue for tracking purposes so it doesn't get forgotten about.

> If someone can please cleanup the debian logo that would be a huge help. So many points that are not visible at the smaller sizes.

**Comment by GreenTurtwig** [comment]
Removed all the floaty bits:
[![](https://user-images.githubusercontent.com/15905797/38871629-4f7c0406-4249-11e8-8eda-8ee91b01f915.png)](https://github.com/Templarian/MaterialDesign/files/1919791/debian.zip)

**Comment by Templarian** [comment]
[![debian](https://materialdesignicons.com/icon/debian)](https://materialdesignicons.com/icon/debian)
