### ISSUE TITLE
Settings Helper

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3064]
Nothing fancy or urgent but it might be handy to add a `settings-helper` icon at some stage.

[![settings-helper](https://user-images.githubusercontent.com/15157491/38806422-1692043e-4171-11e8-9f7f-d8135ccd4945.png)](https://github.com/Templarian/MaterialDesign/files/1915025/settings-helper.zip)

**Comment by Templarian** [comment]
Added.
