### ISSUE TITLE
CentOS (Linux)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3065]
Separating this out from #1422 for tracking purposes.

Here's @jhonatandarosa's contribution from that issue: [centos.zip](https://github.com/Templarian/MaterialDesign/files/727117/centos.zip).

> We need much lower point count for these to be included

**Comment by goyney** [comment]
[![centos](https://materialdesignicons.com/icon/centos)](https://materialdesignicons.com/icon/centos)
