### ISSUE TITLE
Haiku (Linux)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3066]
Separating this out from #1422 for tracking purposes.

Here's @jhonatandarosa's contribution from that issue: [haiku.zip](https://github.com/Templarian/MaterialDesign/files/727548/haiku.zip).

> We need much lower point count for these to be included

**Comment by goyney** [comment]
I'm unable to find the provided "logo" anywhere in Haiku's official resources. Their logo appears to be their full wordmark with feathers within the letters. Unfortunately, that is not something we'll be able to add. Sorry.
