### ISSUE TITLE
Red Hat (Linux)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3068]
Separating this out from #1422 for tracking purposes.

Here's @jhonatandarosa's contribution from that issue: [rhel.zip](https://github.com/Templarian/MaterialDesign/files/727573/rhel.zip).

> We need much lower point count for these to be included

**Comment by PeterShaggyNoble** [comment]
Preview of the file linked above:

![red-hat](https://user-images.githubusercontent.com/15157491/50600864-5f714a00-0eaa-11e9-96c3-981a206803e0.png)

**Comment by goyney** [comment]
[![redhat](https://materialdesignicons.com/icon/redhat)](https://materialdesignicons.com/icon/redhat)
