### ISSUE TITLE
Typos in Aliases

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3069]
Spotted a few typos in aliases while working with meta.json earlier:

- [x] **`airplane`**:  `airplanemode active` -> `airplanemode-active`
- [x] **`airplane-off`**:  `airplanemode inactive` -> `airplanemode-inactive`
- [x] **`brightness-6`**: `brightness medium` -> `brightness-medium`
- [x] **`flash-outline`**: `lighning-bolt-outline` -> `lightning-bolt-outline`

And `announcement` is duplicated on `message-alert`.

**Comment by Templarian** [comment]
Fixed. 😸
