### ISSUE TITLE
Newsletter icon

### ISSUE THREAD

**Issue by dgngulcan** [Templarian/MaterialDesign#3070]
I needed a newsletter icon and newspaper icon did not match in my case. Hence, I'm suggesting an icon for newsletter like below;

![image](https://user-images.githubusercontent.com/1465496/38868350-ba091c80-4214-11e8-8475-a87f1b246e0f.png)

Cheers!

**Comment by PeterShaggyNoble** [comment]
Hmm ... Tricky one, but I think the first works better.

**Comment by MrGrigri** [comment]
Yeah, the first one is better.

**Comment by goyney** [comment]
[![email-newsletter](https://materialdesignicons.com/icon/email-newsletter)](https://materialdesignicons.com/icon/email-newsletter)
