### ISSUE TITLE
Data Type Icons

### ISSUE THREAD

**Issue by christoth** [Templarian/MaterialDesign#3072]
Would it be possible to create basic data type icons? i.e.:
- String
- Integer
- Decimal
- Boolean
- Date
- Time
- DateTime / Timestamp
- Object
- Array

Thanks in advance!

**Comment by goyney** [comment]
I believe most of these can be represented by icons we currently have.

- String - `alphabetical`
- Integer - `numeric`
- Decimal - This is the only "missing" one. You could use `circle-small`, `decimal-increase`, or `decimal-decrease`.
- Boolean - `toggle-switch-off`
- Date - `calendar`
- Time - `clock` or `clock-outline`
- DateTime / Timestamp - `calendar-clock`
- Object - `code-braces`
- Array - `code-brackets`

**Comment by goyney** [comment]
Closing this issue because it has become stale. Please let us know if you have other suggestions around this idea by creating new issues for each separate suggestion. Thanks!
