### ISSUE TITLE
ic_important_devices

### ISSUE THREAD

**Issue by bseib** [Templarian/MaterialDesign#3073]
Would be nice to add this existing Google material icon `ic_important_devices`: https://material.io/icons/#ic_important_devices

![ic_important_devices_black_24dp_2x](https://user-images.githubusercontent.com/1313561/38889321-5a7578da-424c-11e8-80f7-9bc7afd2600c.png)

[ic_important_devices_black_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/1921125/ic_important_devices_black_24px.svg.zip)

**Comment by Templarian** [comment]
[![monitor-cellphone](https://materialdesignicons.com/icon/monitor-cellphone)](https://materialdesignicons.com/icon/monitor-cellphone) [![monitor-cellphone-star](https://materialdesignicons.com/icon/monitor-cellphone-star)](https://materialdesignicons.com/icon/monitor-cellphone-star)

Alias added to both.
