### ISSUE TITLE
face-recognition

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3074]
I've got an idea for a facial recognition icon.

![image](https://user-images.githubusercontent.com/4528551/38889545-4769d61a-423c-11e8-8ed1-e3bb7008793a.png)

[face-recognition.zip](https://github.com/Templarian/MaterialDesign/files/1921138/face-recognition.zip)

**Comment by Templarian** [comment]
[![https://materialdesignicons.com/icon/face-recognition](https://materialdesignicons.com/icon/face-recognition)](face-recognition)
