### ISSUE TITLE
Lock variant with clearly opened latch

### ISSUE THREAD

**Issue by NovapaX** [Templarian/MaterialDesign#3075]
The current locks (open and closed) look very similar, especially when viewed on a bit smaller size/screen. When used in home automation this is not really desirable, as a lock state should be really clear obviously.

May I suggest a `lock-open-variant` with an open latch that is rotated? Like this:
<img width="150" alt="image" src="https://user-images.githubusercontent.com/411716/38890352-646cd948-4281-11e8-8b89-17457f41ab1d.png">

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/38925375-5ad588c8-42f7-11e8-9d02-c1b70af95ae8.png)](https://github.com/Templarian/MaterialDesign/files/1923420/lock-open-variant.zip)

**Comment by MrGrigri** [comment]
The lock upper part is far too small compared to the body part.

**Comment by NovapaX** [comment]
Yes. I think so too.
But it is in line with the other locks. (But maybe they’re wrong too...)

**Comment by GreenTurtwig** [comment]
It is, Google didn't design the lock to be positioned like this after all. To make it any bigger would mean being inconsistent with the other lock icons and pushing right up against the edges, neither of which are great.

**Comment by PeterShaggyNoble** [comment]
Do we need a `lock-open-variant-outline` to match?

**Comment by GreenTurtwig** [comment]
We do, I totally forgot about it yesterday. :-S

**Comment by MrGrigri** [comment]
Why not just shrink the body of the lock?

**Comment by GreenTurtwig** [comment]
Because then it would be inconsistent with the regular lock icon.

**Comment by MrGrigri** [comment]
I believe that'd be okay because it's not the regular lock. It's a variant and ours...not Google's.

**Comment by GreenTurtwig** [comment]
That's another problem, the body in the design above is shifted over 1px otherwise the lock would go off the canvas.

**Comment by MrGrigri** [comment]
My vote is to not include this icon, nor any variant. IMO, the Google version is just fine and in order to accommodate this icon request, we'd have to create each or it's variants.

**Comment by NovapaX** [comment]
The body having a different location for both open and closed is almost inevitable.
What’s the policy regarding animation handles (like giving seperate paths an identifier)

**Comment by NovapaX** [comment]
The difference in the default icons is just to small for the icons to serve as a visual indicator.

**Comment by MrGrigri** [comment]
You could always try the following combination if you feel there isn't enough of a visual indicator. Or you could ditch this icon pack and create your own animation that is suitable for the situation. A single path SVG can be animated in chrome with just CSS BTW (I know that's not practical until all browsers get on board). [Here](https://codepen.io/MrGrigri/pen/mqeXpe) is my CodePen for that.

![lock](https://materialdesignicons.com/icon/lock) ![lock-open-outline](https://materialdesignicons.com/icon/lock-open-outline)

**Comment by NovapaX** [comment]
yes, that might work too. 👍

**Comment by Tarilonte** [comment]
IMO, google's 'lock_open' icon puts the design above the usability.
I imagine that lock icons are used in situations where confusion need to be avoided at any cost.
Google's open and closed locks are way too similar to be safe for using.

**Comment by goyney** [comment]
[![lock-open-variant](https://materialdesignicons.com/icon/lock-open-variant)](https://materialdesignicons.com/icon/lock-open-variant)[![lock-open-variant-outline](https://materialdesignicons.com/icon/lock-open-variant-outline)](https://materialdesignicons.com/icon/lock-open-variant-outline)
