### ISSUE TITLE
Warehouse

### ISSUE THREAD

**Issue by Tarilonte** [Templarian/MaterialDesign#3076]
An icon to add to the buildings collection.

![image](https://user-images.githubusercontent.com/29761068/38906054-b5d9b126-428a-11e8-8a37-906fde1f22b7.png)
[logistic-shed-building.zip](https://github.com/Templarian/MaterialDesign/files/1922101/logistic-shed-building.zip)

**Comment by Tarilonte** [comment]
It's a contribution. I made this icon =)

**Comment by MrGrigri** [comment]
Is there a reason why the 'materials' (five cubes) are one-pixel above the floor of the warehouse?

**Comment by MrGrigri** [comment]
And the contribution label will be applied when we decide on a final icon.

**Comment by Tarilonte** [comment]
The boxes are positioned 1pixel above the container because it looks better in smaller sizes. 
Sometimes, perfectly aligned elements ann perfect geometric shapes create an odd feeling to the viewer.
For example, the new "G" from Google's logo isn't a perfect circle.

![image](https://user-images.githubusercontent.com/29761068/38962276-eabecd1e-4342-11e8-9dc7-a8cece252129.png)

**Comment by goyney** [comment]
Here's an actual preview of @Tarilonte's icon:
![image](https://user-images.githubusercontent.com/1015040/48789221-91439e00-ecba-11e8-80c9-014e5939a5ef.png)

An an adjusted version with the "boxes" on the ground level:
![image](https://user-images.githubusercontent.com/1015040/48789241-9c96c980-ecba-11e8-9069-a045a37603a6.png)

I would pick the second option.

**Comment by MrGrigri** [comment]
I believe we need to try and have 2-pixel spacing as much as possible. So these boxes could be separated more. Thoughts?

**Comment by goyney** [comment]
Here's what @MrGrigri is proposing:
![image](https://user-images.githubusercontent.com/1015040/48790423-4a0adc80-ecbd-11e8-85cf-c82538f76d8a.png)

[warehouse-alt-2.zip](https://github.com/Templarian/MaterialDesign/files/2600813/warehouse-alt-2.zip)

**Comment by goyney** [comment]
Here is what @MrGrigri is proposing:
![image](https://user-images.githubusercontent.com/1015040/48790532-91916880-ecbd-11e8-9e4d-b4054a069e96.png)
[warehouse-alt-2.zip](https://github.com/Templarian/MaterialDesign/files/2600815/warehouse-alt-2.zip)

**Comment by goyney** [comment]
[![warehouse](https://materialdesignicons.com/icon/warehouse)](https://materialdesignicons.com/icon/warehouse)
