### ISSUE TITLE
businessman

### ISSUE THREAD

**Issue by Tarilonte** [Templarian/MaterialDesign#3077]
businessman icon
[businessman.zip](https://github.com/Templarian/MaterialDesign/files/1922107/businessman.zip)

![image](https://user-images.githubusercontent.com/29761068/38906132-19baab1e-428b-11e8-95b1-e44218038478.png)

**Comment by GreenTurtwig** [comment]
Duplicate of https://github.com/Templarian/MaterialDesign/issues/2341
Please post your contribution over there. :cat2:
