### ISSUE TITLE
Devices Other

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3079]
#3073 reminded me of this stock icon which could be handy:

[![devices other](https://user-images.githubusercontent.com/15157491/38925682-3f4c6dfa-42f8-11e8-9153-1a6e4fb261da.png)](https://github.com/Templarian/MaterialDesign/files/1923451/devices_other.zip)

**Comment by goyney** [comment]
[![devices](https://materialdesignicons.com/icon/devices)](https://materialdesignicons.com/icon/devices)
