### ISSUE TITLE
Events icons

### ISSUE THREAD

**Issue by naXa777** [Templarian/MaterialDesign#308]
It would be nice to have icons that somehow illustrate a response to "Are you attending to the event?"

- [ ] event-yes
- [ ] event-no
- [ ] event-maybe

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/calendar-check
https://materialdesignicons.com/icon/calendar-remove
+ another calendar icon with a question mark maybe?

Or use
https://materialdesignicons.com/icon/check
https://materialdesignicons.com/icon/close
https://materialdesignicons.com/icon/help
in a event-ish / calendary context (or their circle variants).

**Comment by Templarian** [comment]
I'm going to mark this as closed. I think any of the above icons would work for the status of an event.

Let me know if this is not the case and it will be reopened.
