### ISSUE TITLE
image-album-multiple

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3080]
Icon for albums in Google Photos.
[![](https://user-images.githubusercontent.com/15905797/38927491-d7bbeae8-42fd-11e8-9063-7d2f9c20e0f9.png)](https://github.com/Templarian/MaterialDesign/files/1923602/image-album-variant.zip)

**Comment by PeterShaggyNoble** [comment]
Also included in the Stock set as `collections bookmark`.

**Comment by goyney** [comment]
We have several `book-multiple` icons that share the same style. `book-multiple-variant` is a loner. As I said in my last comment, I suggest we replace it with the Google icon and rename/reattribute it.

![image](https://user-images.githubusercontent.com/1015040/53062672-89e58980-348f-11e9-9797-95087139817d.png)
Our current is the outline.

[book-multiple-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/2882804/book-multiple-variant.svg.zip)

**Comment by Templarian** [comment]
[![book-multiple-variant](https://materialdesignicons.com/icon/book-multiple-variant)](https://materialdesignicons.com/icon/book-multiple-variant)
