### ISSUE TITLE
swap-circle

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3081]
Found in Google Photos.
[![](https://user-images.githubusercontent.com/15905797/38927625-4ba84014-42fe-11e8-966d-5d096e8e54b5.png)](https://github.com/Templarian/MaterialDesign/files/1923619/swap-circle.zip)

**Comment by PeterShaggyNoble** [comment]
Also included in the Extended icon set as `swap horizontal circle`.

**Comment by PeterShaggyNoble** [comment]
And there's a complimentary `swap vertical circle` in the Stock set.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49036577-111fab80-f186-11e8-8f00-32a58a1b5124.png)![image](https://user-images.githubusercontent.com/1015040/49036588-18df5000-f186-11e8-82ea-d146e99132bd.png)
![image](https://user-images.githubusercontent.com/1015040/49036598-20065e00-f186-11e8-8979-c9d10c340c83.png)![image](https://user-images.githubusercontent.com/1015040/49036609-25fc3f00-f186-11e8-98c5-70c9633d0534.png)

[swap-circle.zip](https://github.com/Templarian/MaterialDesign/files/2617010/swap-circle.zip)

**Comment by goyney** [comment]
[![swap-horizontal-circle](https://materialdesignicons.com/icon/swap-horizontal-circle)](https://materialdesignicons.com/icon/swap-horizontal-circle)[![swap-horizontal-circle-outline](https://materialdesignicons.com/icon/swap-horizontal-circle-outline)](https://materialdesignicons.com/icon/swap-horizontal-circle-outline)
[![swap-vertical-circle](https://materialdesignicons.com/icon/swap-vertical-circle)](https://materialdesignicons.com/icon/swap-vertical-circle)[![swap-vertical-circle-outline](https://materialdesignicons.com/icon/swap-vertical-circle-outline)](https://materialdesignicons.com/icon/swap-vertical-circle-outline)
