### ISSUE TITLE
image-filter-variant

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3082]
Found in Google Photos.
[![](https://user-images.githubusercontent.com/15905797/38927856-ec00bb22-42fe-11e8-9470-4175e98bfda2.png)](https://github.com/Templarian/MaterialDesign/files/1923650/image-filter-variant.zip)

**Comment by MrGrigri** [comment]
IMO, this is beyond abstract and would in no way represent an image filter.

**Comment by MrGrigri** [comment]
Either way, I don't see how that's any sort of filter

**Comment by JamesCoyle** [comment]
Its a filter in terms of image editing where you add an effect (represented by the stars) to an image.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49036413-acfce780-f185-11e8-9899-1a17a9125306.png)
[image-auto-adjust.svg.zip](https://github.com/Templarian/MaterialDesign/files/2617002/image-auto-adjust.svg.zip)

**Comment by goyney** [comment]
[![image-auto-adjust](https://materialdesignicons.com/icon/image-auto-adjust)](https://materialdesignicons.com/icon/image-auto-adjust)
