### ISSUE TITLE
format-list-checkbox

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3083]
From Google Keep.
[![](https://user-images.githubusercontent.com/15905797/38929573-adf29d68-4304-11e8-9cd5-77e1b758adca.png)](https://github.com/Templarian/MaterialDesign/files/1923770/format-list-checkbox.zip)

**Comment by Templarian** [comment]
[![format-list-check](https://materialdesignicons.com/icon/format-list-checkbox)](https://materialdesignicons.com/icon/format-list-checkbox)
