### ISSUE TITLE
Update google-assistant

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3084]
This is the official Google Assistant icon found within Allo.
Comparison below to our design.
[![](https://user-images.githubusercontent.com/15905797/38935215-b1c52544-4315-11e8-8754-cef7c324b01c.png)](https://github.com/Templarian/MaterialDesign/files/1924194/google-assistant.zip)

**Comment by PeterShaggyNoble** [comment]
That'll learn me to check the extended icons by eye!

**Comment by GreenTurtwig** [comment]
I just thought I'd do a brief comparison since I remembered we got our own contribution a while back. ;-)
