### ISSUE TITLE
Update and reassign dumbbell

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3085]
Google has a dumbbell icon name `fitness center` in the stock set. We should replace ours and reassign to Google.
https://material.io/icons/#ic_fitness_center

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53062761-e2b52200-348f-11e9-8f08-b75ba665bd2c.png)
Ours current is the outline.

[dumbbell.svg.zip](https://github.com/Templarian/MaterialDesign/files/2882815/dumbbell.svg.zip)

**Comment by Templarian** [comment]
[![dumbbell](https://materialdesignicons.com/icon/dumbbell)](https://materialdesignicons.com/icon/dumbbell)
