### ISSUE TITLE
prize

### ISSUE THREAD

**Issue by Tarilonte** [Templarian/MaterialDesign#3088]
prize icon suggestion

![image](https://user-images.githubusercontent.com/29761068/38962759-2201b014-4345-11e8-9499-aa9583f9bbb3.png)
[prize.zip](https://github.com/Templarian/MaterialDesign/files/1926089/prize.zip)

**Comment by MrGrigri** [comment]
Would #790 work? 

Also, we have a [tool](https://petershaggynoble.github.io/MDI-Sandbox/preview/) that allows you to specify a path and it generates the preview icon for you to copy.

**Comment by CoDEmanX** [comment]
The contribution has the icon on a 25x25 background, so not sure how it is supposed to be placed on the 24x24 canvas. It looks good at larger sizes anyway, but it isn't particularly legible at normal size.

**Comment by Tarilonte** [comment]
I'll correct the canvas dimensions and then submit the file again.

**Comment by MrGrigri** [comment]
After looking at @Tarilonte, It didn't really align with the grid much when shrunk down to a 24x24 pixel area. Here it is after I touched it up a bit. Credit can still be given to him as he designed it.

![image](https://user-images.githubusercontent.com/4528551/48809555-4a699e80-ece2-11e8-9a1c-e07173b16731.png)

 ---

[ribbon.zip](https://github.com/Templarian/MaterialDesign/files/2601995/ribbon.zip)

**Comment by PeterShaggyNoble** [comment]
See also Google's `license` icon from Material Icons Extended (although I definitely prefer @MrGrigri's):

[![license](https://user-images.githubusercontent.com/15157491/49225904-26dade00-f3dd-11e8-86dc-cb6e65693526.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by goyney** [comment]
[![seal-variant](https://materialdesignicons.com/icon/seal-variant)](https://materialdesignicons.com/icon/seal-variant)[![license](https://materialdesignicons.com/icon/license)](https://materialdesignicons.com/icon/license)
