### ISSUE TITLE
Wrong attribution for social icons?

### ISSUE THREAD

**Issue by asadovsky** [Templarian/MaterialDesign#309]
The following icons are listed as "by Google" (not community contributions):
http://materialdesignicons.com/icon/facebook-box
http://materialdesignicons.com/icon/twitter-box
http://materialdesignicons.com/icon/google-plus-box
http://materialdesignicons.com/icon/pinterest

However, they are nowhere to be found in the authoritative material design repository.
For example: https://github.com/google/material-design-icons/search?utf8=%E2%9C%93&q=twitter+in%3Apath&type=Code

Perhaps the attribution is wrong for these?

**Comment by Templarian** [comment]
Those are from their previous icon pack before the released the official set. Didn't even notice they were not in the current official set.

**Comment by Templarian** [comment]
Since they are just company logo's I wouldn't even worry about the license if that is what you were curious about. I don't think an icon pack even even require attribution use of a companies logo. That wouldn't really make sense.
