### ISSUE TITLE
Cricket

### ISSUE THREAD

**Issue by danasfash** [Templarian/MaterialDesign#3090]
I need a cricket ball or person icon

**Comment by goyney** [comment]
This icon can be found in Google Fit and will need to be recreated for inclusion in the library.
![cricket](https://user-images.githubusercontent.com/1015040/48862636-f4a1fe80-ed94-11e8-8604-a963cfdb6328.png)

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/48975297-f2f96480-f03a-11e8-9633-0542a26ad9ce.png)

[cricket.svg.zip](https://github.com/Templarian/MaterialDesign/files/2612826/cricket.svg.zip)

**Comment by PeterShaggyNoble** [comment]
From Google's Material Icons Extended set:

[![sports_cricket](http://mdi.houseofdesign.ie/tools/preview/?icon=sports_cricket&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50979873-7117aa80-14c5-11e9-8617-16fc4ab45e9a.png)
[sports-cricket.svg.zip](https://github.com/Templarian/MaterialDesign/files/2746062/sports-cricket.svg.zip)
