### ISSUE TITLE
Google classroom icon

### ISSUE THREAD

**Issue by Isetnt2** [Templarian/MaterialDesign#3091]
Would like to see a google classroom icon,

**Comment by CoDEmanX** [comment]
Isn't that pretty much like https://petershaggynoble.github.io/MDI-Sandbox/?icon=account-group ?

Otherwise it would need to be added as brand icon, but I'm not sure if it meets the MDI requirements. It has too many details for a generic icon IMO.

**Comment by GreenTurtwig** [comment]
Here's the guidelines: https://developers.google.com/classroom/brand

The main issue is the transparent people in the background.

**Comment by PeterShaggyNoble** [comment]
Duplicate of #1950.
