### ISSUE TITLE
check-network / network-off

### ISSUE THREAD

**Issue by donhurickerby** [Templarian/MaterialDesign#3093]
An icon similar to the __close-network__ instead with a check inside. Can be used to signify a state of node on the network, or an action like check node state.

Thanks.

**Comment by MrGrigri** [comment]
I believe both of these would be useful.

![image](https://user-images.githubusercontent.com/4528551/39062790-e21ccc9e-4485-11e8-9d4e-5a9019ae9616.png) ![image](https://user-images.githubusercontent.com/4528551/39063106-fde2894a-4486-11e8-9ae6-45f6a343b2ed.png)

[check-network.zip](https://github.com/Templarian/MaterialDesign/files/1932888/check-network.zip)
[network-off.zip](https://github.com/Templarian/MaterialDesign/files/1932887/network-off.zip)

**Comment by CoDEmanX** [comment]
Some old discussion over here: https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-141575044

Instead of an off variant, how about something like this?

![grafik](https://user-images.githubusercontent.com/1309249/39075871-5782c462-44f8-11e8-9f7c-87aeacd56567.png)

**Comment by MrGrigri** [comment]
We already have a `server-network-off` so I feel that it is consistent.

**Comment by goyney** [comment]
Slight update to @MrGrigri's to make these consistent with each other and others already in the library:
![image](https://user-images.githubusercontent.com/1015040/48323817-fed93580-e5fb-11e8-938d-0b9baae551d0.png)![image](https://user-images.githubusercontent.com/1015040/48323826-07ca0700-e5fc-11e8-96fc-2252fda2e1df.png)
[network-off.zip](https://github.com/Templarian/MaterialDesign/files/2570341/network-off.zip)

And the outline variant of check:
![image](https://user-images.githubusercontent.com/1015040/48323840-203a2180-e5fc-11e8-9cb3-77e2de7dfb55.png)
[check-network-outline.zip](https://github.com/Templarian/MaterialDesign/files/2570339/check-network-outline.zip)

**Comment by Templarian** [comment]
All 4 are added. 😃
