### ISSUE TITLE
example + library icon

### ISSUE THREAD

**Issue by Chan4077** [Templarian/MaterialDesign#3094]
This "example" icon can be used for documentation websites which show some form of link/button for an example. In my case, I'm trying to add such an icon to my app as example use cases.

For the "library" icon, I'm trying to use it to show a library for software purposes.

**Comment by PeterShaggyNoble** [comment]
Do you have an example (pun partially intended!) of what that might look like? Would one of the `information` icons do the job?

**Comment by CoDEmanX** [comment]
"Example" is probably too generic. We have several options for something more specific:

- a light bulb if you want to show the user some ideas for own stuff
- for a list of things which are possible a simple check mark should do
- a quote mark or a speech bubble if you present what other people did with your product (testimonials)
- if it's code example then probably the console icon: ![grafik](https://user-images.githubusercontent.com/1309249/39070954-873c2abc-44e5-11e8-8b50-2ae32483c38d.png)
- for interactive content, a play button would work (triangle pointing to the right-hand side)
- maybe the shape icon to represent a concept of multiple components working together? ![grafik](https://user-images.githubusercontent.com/1309249/39071081-0909db3e-44e6-11e8-9c4f-0c3e1dd15c33.png)

**Comment by Chan4077** [comment]
@CoDEmanX Yup. I was looking for the console icon.

Anyways, I still need a library icon to show software libraries like APIs, etc.

**Comment by PeterShaggyNoble** [comment]
Again, can you provide an example of what that might look like. I can think of a few of ways to represent it (some using existing icons like `cogs` and `xml`, some requiring a new icon like `library-code-tags`) but they may not necessarily be what you're looking for.

**Comment by goyney** [comment]
Closing because this issue has become stale. If you have other suggestions for new icons, please open a separate issue for each. Thank you!
