### ISSUE TITLE
Some icons I didn't find

### ISSUE THREAD

**Issue by AAronsson** [Templarian/MaterialDesign#3096]
Progress - The status of where in process the user is. Some steps are finished and some are not. When showing the status in short it would be nice with a progress-icon. (Could be a progressbar half full or something)
Awaiting approval - Waiting for admin to approve. 
User Terms - terms of usage. Some kind of legal document. (A paper with text on it)
Agreement - Maybe use the same as user terms.
PDFSymbols - More PDF-symbols. (pdf-in ring, only symbol and outline versions of those already existing.)
Numbers in ring - Yes I can use css to style this, but it doesn't center perfectly. But good enough maybe.

And all icons should have outline versions and a ring version with and without outline :-)

**Comment by GreenTurtwig** [comment]
Can you please split these into individual issues along with some examples. Also do a search before hand, for example we already have an issue open for your last suggestion, #2425. :cat2:
