### ISSUE TITLE
Progress

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3098]
As requested in #3096.

![](https://user-images.githubusercontent.com/15905797/39087017-d011f6ac-4591-11e8-858b-00df9cbc52f0.png)![](https://user-images.githubusercontent.com/15905797/39087021-e670dc10-4591-11e8-9ffc-4fd26f3d2d06.png)
[progress.zip](https://github.com/Templarian/MaterialDesign/files/1934800/progress.zip)

Prefer the second one myself.

**Comment by AAronsson** [comment]
That was a tricky one. 
Personally I was thinking of a bar, but I realize that it wouldn't be more clear.

Of these two the one to the right is best I think.

**Comment by PeterShaggyNoble** [comment]
I'll buck the trend and say I prefer the first one!

**Comment by CoDEmanX** [comment]
My vote goes to the first as well, because with the smaller checkmark the emphasis is on the circle, which is important here.

**Comment by Templarian** [comment]
[![progress-upload](https://materialdesignicons.com/icon/progress-upload)](https://materialdesignicons.com/icon/progress-upload) [![progress-download](https://materialdesignicons.com/icon/progress-download)](https://materialdesignicons.com/icon/progress-download) [![progress-check](https://materialdesignicons.com/icon/progress-check)](https://materialdesignicons.com/icon/progress-check)
