### ISSUE TITLE
clock-check

### ISSUE THREAD

**Issue by AAronsson** [Templarian/MaterialDesign#3099]
Waiting for admin to approve.

Maybe a clock and a check. Like clock-alert

**Comment by goyney** [comment]
Not sure if I care for the way the check looks on the non-outlined version:
![image](https://user-images.githubusercontent.com/1015040/45645571-e2eb6480-ba8e-11e8-813a-ac7c6606a157.png)![image](https://user-images.githubusercontent.com/1015040/45645581-ec74cc80-ba8e-11e8-9d49-baf52e05daea.png)

[clock-check.zip](https://github.com/Templarian/MaterialDesign/files/2389980/clock-check.zip)

**Comment by goyney** [comment]
Here's two more using the check from the extended set:

![image](https://user-images.githubusercontent.com/1015040/45646196-a3257c80-ba90-11e8-8c6b-433237584658.png)![image](https://user-images.githubusercontent.com/1015040/45646215-ab7db780-ba90-11e8-8ae0-9e2a216dbceb.png)

[clock-check-variant.zip](https://github.com/Templarian/MaterialDesign/files/2390023/clock-check-variant.zip)

**Comment by goyney** [comment]
[![clock-check](https://materialdesignicons.com/icon/clock-check)](https://materialdesignicons.com/icon/clock-check)[![clock-check-outline](https://materialdesignicons.com/icon/clock-check-outline)](https://materialdesignicons.com/icon/clock-check-outline)
