### ISSUE TITLE
iOS Export

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#31]
Export iOS compatible assets.

**Comment by abdu292** [comment]
Please add iOS export option. Can we have it included within icon package bundle download (as "material.io/icons" does?)

**Comment by JamesCoyle** [comment]
Best to add this to the new site feature list? Personally I don't think people should use material icons on iOS as iOS apps should follow the iOS theming guidelines.

**Comment by abdu292** [comment]
Thanks @JamesCoyle However I don't necessarily agree as one could see this site is not limited to material icons (which is amazingly great and beautiful), rather provides options to export to XAML for windows, colorized icons etc. And so, having an option to export to iOS would be a great addition (the official materil.io/icons actually gives an iOS icons folder as well when you download the icons package)

Also developers like me who develop apps for all the platforms i.e. Android, iOS & Windows will greatly benefit from this & save a lot of time. Thanks a bunch!

**Comment by Templarian** [comment]
This will have to be a feature of the new site as I've stopped all current development on the current site and shifted work to the new site.

I'm doing a lot of work on the new export file API's and will work to include these. Should be possible with the "image" API's I'm working with behind the scenes.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site/issues/6

Closing this out. This issue will have to be addressed here.

**Comment by abdu292** [comment]
@Templarian Thank you so much!

**Comment by jkmathew** [comment]
@Templarian , is this feature implemented?. Couldn't find way to export icons for iOS in http://dev.materialdesignicons.com/icon/ too
