### ISSUE TITLE
Bookmark delete icon

### ISSUE THREAD

**Issue by DaniGuardiola** [Templarian/MaterialDesign#310]
- [ ] bookmark-remove

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/bookmark-remove

**Comment by DaniGuardiola** [comment]
That was quick!

**Comment by DaniGuardiola** [comment]
Just found out that the icon is not available on the svg folder of this repo, can you please add it? thanks!

**Comment by Templarian** [comment]
You should use the SVG files provided from the site not the repo. The ones in the repo are the raw unoptimized SVG paths.

I pushed my latest changes.

**Comment by DaniGuardiola** [comment]
Thanks for the clarification.
How can I download and keep updated the whole library?

**Comment by Templarian** [comment]
That's coming eventually ([IconBook](http://www.iconbook.io/)). Right now just view the [history](http://materialdesignicons.com/history) page.

**Comment by DaniGuardiola** [comment]
Looks awesome. By the moment, could you give me some tips on getting the icons? The path, maybe? I think i can get the list from the history. I need to do all this programatically. Also, any idea for detecting which icons are from google?

All these is because i'm building a framework, and i'm making your icons available

**Comment by DaniGuardiola** [comment]
Btw, will iconbook support CLI and some repo managing/updating system?

**Comment by Templarian** [comment]
The first release of IconBook will probably not have a CLI. http://materialdesignicons.com/custom can give you a list of all the icons with the path data (this is directly from the database, and is not synced with the Webfont count).

You can use the `{author}` variable, if it is `Google` it is well `Google`. Any other name is a contributor.

A few frameworks use the icons, I know [LumX](http://ui.lumapps.com) does, but they just use the Webfont.

**Comment by DaniGuardiola** [comment]
Awesome!

Check DaniGuardiola/Paperkit for the framework (it's being re-built so you won't find any usable code at the moment, but you can see an example from the old code on this app i'm building: https://chrome.google.com/webstore/detail/wikilist-wikipedia-list/empnicnlhbkpkcajiojedphnlepmjdfg).

Take care!
