### ISSUE TITLE
User terms, Legal paper, Agreement

### ISSUE THREAD

**Issue by AAronsson** [Templarian/MaterialDesign#3100]
Could be the same but could also be some alternatives.

Suggestions 
Paper with lines and a check down to right
A clean paper with lines.
Paper with a pen and a signature at bottom. Could be hard to do in such a small resolution.

**Comment by PeterShaggyNoble** [comment]
Possible duplicate of #2151?

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
