### ISSUE TITLE
More Pdf alternatives

### ISSUE THREAD

**Issue by AAronsson** [Templarian/MaterialDesign#3101]
Pdf in a ring. with and without outline
Clean Pdf symbol
Outline version of file-pdf-box

**Comment by goyney** [comment]
[![adobe-acrobat](https://materialdesignicons.com/icon/adobe-acrobat)](https://materialdesignicons.com/icon/adobe-acrobat)[![file-pdf-box-outline](https://materialdesignicons.com/icon/file-pdf-box-outline)](https://materialdesignicons.com/icon/file-pdf-box-outline)

We're not going to add circular variations of our `file-` type icons.
