### ISSUE TITLE
LTE / VoLTE

### ISSUE THREAD

**Issue by evil37** [Templarian/MaterialDesign#3103]
make icon for LTE and VoLTE

**Comment by CoDEmanX** [comment]
There is `signal-4g`. LTE could be done in the same style, as text icon.

Is this the official VoLTE logo?

![grafik](https://user-images.githubusercontent.com/1309249/39236447-398bb3b8-4879-11e8-84c1-4603f53d195f.png)

I would rather combine phone + "LTE" as text to be honest, but it seems pretty niche. Following Google's SIP icon https://material.io/icons/#ic_dialer_sip it would look like this:

![grafik](https://user-images.githubusercontent.com/1309249/39236847-267791f6-487a-11e8-99cc-c31604842f55.png)

[phone-lte.zip](https://github.com/Templarian/MaterialDesign/files/1946321/phone-lte.zip)

**Comment by goyney** [comment]
LTE is a 4g standard, meaning that our `signal-4g` icon should handle any use cases at a general level. We've already rejected this in the past and I still don't see a reason to include it at this point in time.
