### ISSUE TITLE
npm-variant

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3104]
When used with some other icons our `npm` icon looks quote small so I suggest adding `npm-variant` that just uses the `n` from their logo, as they do themselves in their favicon, possibly also with `-box` and `circle` variants.

![](https://user-images.githubusercontent.com/15157491/39199062-83afef16-47e0-11e8-8e30-56c0e76ae717.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/39199343-7c31a53e-47a6-11e8-9f58-e0013520408e.png)

[npm-variant.zip](https://github.com/Templarian/MaterialDesign/files/1943600/npm-variant.zip)

**Comment by CoDEmanX** [comment]
Would be easier to recognize as a boxed version IMO:

![grafik](https://user-images.githubusercontent.com/1309249/39235982-c0436e8e-4877-11e8-87c1-a7e5efea6c60.png)

[npm-variant.zip](https://github.com/Templarian/MaterialDesign/files/1946275/npm-variant.zip)

**Comment by PeterShaggyNoble** [comment]
Yeah, I think you're right @CoDEmanX.

**Comment by MrGrigri** [comment]
I used their favicon from their website...since it's a brand icon, I would go with the first one.

**Comment by CoDEmanX** [comment]
The boxed N is the first letter from their full logo, except that we are restricted to monochrome and can't fill the inner part...

**Comment by CoDEmanX** [comment]
Sure, why not

**Comment by Templarian** [comment]
[![npm-variant](https://materialdesignicons.com/icon/npm-variant)](https://materialdesignicons.com/icon/npm-variant-outline) [![npm-variant](https://materialdesignicons.com/icon/npm-variant-outline)](https://materialdesignicons.com/icon/npm-variant-outline)

**Comment by MrGrigri** [comment]
I believe both of these were incorrectly contributed to the general 'contributors' account.
