### ISSUE TITLE
greeting card

### ISSUE THREAD

**Issue by shalabi67** [Templarian/MaterialDesign#3106]
looking for a set of greeting cards, send card, receive card, greeting card.

**Comment by PeterShaggyNoble** [comment]
This could be tricky; off the top of my head, I can't think of a way to represent it without relying on perspective, which the Material Design guidelines don't allow. Do you have any examples, yourself?

**Comment by CoDEmanX** [comment]
The upcoming postage stamp icon might work:
https://github.com/Templarian/MaterialDesign/issues/418#issuecomment-378710604

**Comment by Croutonix** [comment]
[![image](https://user-images.githubusercontent.com/18645219/39674222-793d99f4-5116-11e8-933c-3ad44ae124c5.png)](https://github.com/Templarian/MaterialDesign/files/1977696/icon.zip)

**Comment by CoDEmanX** [comment]
Looks a bit strange, like a sculpture or something if you don't know the context. Furthermore, I would read it as love letter, not greeting card.

**Comment by jhil** [comment]
[![email-heart-outline](https://materialdesignicons.com/icon/email-heart-outline)](https://materialdesignicons.com/icon/email-heart-outline) [![email-open-heart-outline](https://materialdesignicons.com/icon/email-open-heart-outline)](https://materialdesignicons.com/icon/email-open-heart-outline)
