### ISSUE TITLE
Photo outline icon

### ISSUE THREAD

**Issue by debjitk** [Templarian/MaterialDesign#3107]
Can we have a photo or photos outline icon please.

**Comment by PeterShaggyNoble** [comment]
Sounds like you're looking for the `image-filter` icon.

**Comment by debjitk** [comment]
Probably. But flat rather than the elevated option.

Sent from my iPhone

On 25-Apr-2018, at 2:43 AM, Peter Noble <notifications@github.com<mailto:notifications@github.com>> wrote:


Sounds like you're looking for the image-filter icon.

**Comment by PeterShaggyNoble** [comment]
Yes, we could do with adding a singular `image-outline` too.

The alias `image-multiple-outline` has been added to `image-filter` anyway.

**Comment by Templarian** [comment]
[![image-outline](https://materialdesignicons.com/icon/image-outline)](https://materialdesignicons.com/icon/image-outline)
