### ISSUE TITLE
Re-engageable

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3108]
Seen in a talk about progressive web apps (PWA):

![grafik](https://user-images.githubusercontent.com/1309249/39234910-d40be53e-4874-11e8-9e6f-35ed7146bc6f.png)

It's kinda strange, but wanted to share it anyway. Maybe there's another context it could work in? Something like a telephone survey?

**Comment by PeterShaggyNoble** [comment]
It's very similar to `comment-processing` and `message-processing`.

**Comment by CoDEmanX** [comment]
True, but they don't really convey "come back for more".

**Comment by PeterShaggyNoble** [comment]
There's also `page control` from the Extended icon set, which is somewhat similar. No idea why they used 4 circles instead of 3!

![page control](https://user-images.githubusercontent.com/15157491/39238144-6963f07c-4875-11e8-916f-deeb3348da51.png)

**Comment by MrGrigri** [comment]
Wouldn't `message-processing` work?

![message-processing](https://materialdesignicons.com/icon/message-processing)

**Comment by CoDEmanX** [comment]
It's not quite the same notion. The page control thingy is interesting, but yeah, why 4 instead of 3 much more legible circles? 🙈

**Comment by GreenTurtwig** [comment]
I suppose four makes more sense to represent a carousel on the web. Having three may confuse users? I don't know, this is Google after all.

**Comment by JamesCoyle** [comment]
I'm gonna close this out as it's pretty specific and hard to show in an icon. I'm not really sure why you would want this either as it doesn't relate to an action or 'thing' which is what icons are generally used for.
