### ISSUE TITLE
Image Search

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3109]
From the Extended icon set

[![image search](https://user-images.githubusercontent.com/15157491/39235528-010b536e-486e-11e8-8466-66ae38d51a96.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by MrGrigri** [comment]
I don't like how ours are now inconsistent with the Google Stock one. Our `table-search` and `database-search` icon have the magnifying glass on the bottom.

**Comment by Templarian** [comment]
[![image-search](https://materialdesignicons.com/icon/image-search)](https://materialdesignicons.com/icon/image-search) [![image-search-outline](https://materialdesignicons.com/icon/image-search-outline)](https://materialdesignicons.com/icon/image-search-outline)
