### ISSUE TITLE
Football Icon

### ISSUE THREAD

**Issue by Zangoran** [Templarian/MaterialDesign#311]
- [x] Football
- [ ] Helmet

**Comment by Templarian** [comment]
You nicely list your location on your profile as "Earth", so I'll have to ask. Football being the round one or the oval'ish one?

**Comment by Zangoran** [comment]
Opps, sorry. The ovalish one. (The american one)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/football
http://materialdesignicons.com/icon/football-helmet

**Comment by Zangoran** [comment]
Thanks!
