### ISSUE TITLE
Sun and Moon

### ISSUE THREAD

**Issue by Ampsicora** [Templarian/MaterialDesign#3110]
Would be nice have an icon with the sun and moon together

**Comment by CoDEmanX** [comment]
There is a `theme-light-dark` icon:

![grafik](https://user-images.githubusercontent.com/1309249/39240490-3572b258-4884-11e8-9eca-20f42c1ad899.png)

**Comment by PeterShaggyNoble** [comment]
Ah-ha! I knew we had something like that! Could probably do with aliasing it as `sun-moon-stars`.

**Comment by CoDEmanX** [comment]
There's no icon in the style of the weather icons however. `weather-sunny-night` would be kinda strange, but could possible be used for a weather app or sun and moon phase thingy. There would not be a slash like in the theme icon.
