### ISSUE TITLE
text_select_handle_left, Right, Middle

### ISSUE THREAD

**Issue by muslimmuda15** [Templarian/MaterialDesign#3111]

**Comment by CoDEmanX** [comment]
You mean these? ![abc_text_select_handle_middle_mtrl_light](https://user-images.githubusercontent.com/1309249/39241252-881e0866-4886-11e8-880c-54266c2aacd6.png)

![abc_text_select_handle_left_mtrl_light](https://user-images.githubusercontent.com/1309249/39241251-8804ef7a-4886-11e8-8e6e-869317a4f829.png) ![abc_text_select_handle_right_mtrl_light](https://user-images.githubusercontent.com/1309249/39241253-883b8e86-4886-11e8-9ca1-2fbe9964fa64.png)

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/39302554-f1e913e8-494a-11e8-815a-cb7e9c0189f7.png)![](https://user-images.githubusercontent.com/15905797/39302575-ffcfc9b6-494a-11e8-98e1-6a1736305771.png)![](https://user-images.githubusercontent.com/15905797/39302610-1b98693c-494b-11e8-9e22-6e5dd83666af.png)

`text-select-handle` had to pushed down a bit or it would have gone off the canvas.
[text-select-handle.zip](https://github.com/Templarian/MaterialDesign/files/1950854/text-select-handle.zip)

**Comment by CoDEmanX** [comment]
FWIW: The true size of the select handle is 28.5 x 35 dp, and the other two are 29 x 29 dp.

I'm not sure about the usefulness of these as icons. Should they be aligned on the grid somehow? Like the left handle in the top right corner? It would make it a bit easier to position them if you want to use them as actual text selection handles, but it would still require an odd scale ratio (1.6111).

**Comment by Templarian** [comment]
This is more of a UI element... not really something an icon like our set should be used for probably.

I would assume it would make more sense to bake in an SVG. Closing this one.
