### ISSUE TITLE
Play - Strikethrough/Off

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3112]
A `play` already exists but what about a `play-strikethrough` or `play-off` icon like `credit-card-off`?

**Comment by JamesCoyle** [comment]
What would be the usecase? Surely just using the stop icon on showing the play icon in a disabled state would suffice?

**Comment by CoDEmanX** [comment]
Video unable to play because of unsupported codec, insufficient bandwidth or DRM? Or if the resource is not available, similar to the broken image icon but for video.

**Comment by matthew2402** [comment]
Yep, exactly. In my case if the resource is not available. A disabled icon does not separate that much in a list of videos where others are not disabled.

**Comment by MrGrigri** [comment]
Why not just disable the button (both visually and physically). I still don't see that as good UX practice.

**Comment by CoDEmanX** [comment]
Maybe simply `exclamation` if it's in a list with a lot of play icons?

**Comment by matthew2402** [comment]
I'd really prefer a `play-off` icon here since I tried various icons including `exclamation` and they all looked odd in the list. I guess a `play-off` icon looks (similar but) better here.

**Comment by CoDEmanX** [comment]
I tried various slash lengths and placements, but it keeps looking odd...

![grafik](https://user-images.githubusercontent.com/1309249/39387352-68bd1012-4a79-11e8-94e3-e3c40dc679ef.png)


Even worse:

![grafik](https://user-images.githubusercontent.com/1309249/39387698-53025e74-4a7b-11e8-8065-5e2853488cca.png)

Don't like it, but better than the others:

![grafik](https://user-images.githubusercontent.com/1309249/39387740-a4aad22e-4a7b-11e8-964a-c58be9740ceb.png)

**Comment by MrGrigri** [comment]
Yeah, not a fan at all. Just a bad UX pattern in general.

**Comment by JapanYoshi** [comment]
A more general file version of https://materialdesignicons.com/icon/image-broken-variant could be useful too.

**Comment by goyney** [comment]
Thanks for the suggestion. I'm going to close this request because the use-case is too obscure. We also don't want to promote bad user experience. 😉
