### ISSUE TITLE
settings overscan (+alias fullscreen)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3113]
https://material.io/icons/#ic_settings_overscan

Works better as fullscreen icon than the existing `fullscreen` if it's not used as action:

![grafik](https://user-images.githubusercontent.com/1309249/39240947-99cb1302-4885-11e8-9999-df11d176678a.png)

**Comment by PeterShaggyNoble** [comment]
Since added to Google's stock icons:

[![settings-overscan](https://user-images.githubusercontent.com/15157491/45296459-fd0acd00-b4f9-11e8-802d-ed3e2fbf5498.png)](https://material.io/tools/icons/?search=settings_overscan&icon=settings_overscan&style=baseline)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49036208-13cdd100-f185-11e8-9684-adcbdb799e4b.png)
[overscan.svg.zip](https://github.com/Templarian/MaterialDesign/files/2616989/overscan.svg.zip)

**Comment by goyney** [comment]
[![overscan](https://materialdesignicons.com/icon/overscan)](https://materialdesignicons.com/icon/overscan)
