### ISSUE TITLE
Hallway

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3114]
Presumably used in home automation to represent the room but could also be used to represent an image gallery.

[![hallway](https://user-images.githubusercontent.com/15157491/39242020-87d527b4-4880-11e8-95d4-7ceab64d9289.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by PeterShaggyNoble** [comment]
Their `gallery` icon is even more abstract!

![gallery](https://user-images.githubusercontent.com/15157491/39396146-c5786b78-4ae0-11e8-8687-9c86d04c7536.png)

**Comment by CoDEmanX** [comment]
Looks much like origami

**Comment by PeterShaggyNoble** [comment]
As it's from the Extended set, I suspect it may be an incomplete icon that snuck in, much like the `unknown *` ones.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49036140-df5a1500-f184-11e8-8fd8-46bb5a6ea8ec.png)
[image-frame.svg.zip](https://github.com/Templarian/MaterialDesign/files/2616985/image-frame.svg.zip)

**Comment by Templarian** [comment]
Added.
