### ISSUE TITLE
musical.ly

### ISSUE THREAD

**Issue by elisabeth21** [Templarian/MaterialDesign#3115]
Would be nice have an icon for the social network musical.ly :)
![75af7d16-b28e-11e6-80d7-a811336ce5d3](https://user-images.githubusercontent.com/2110875/39243550-1c428b64-488e-11e8-8c13-643c4a042322.jpg)

**Comment by PeterShaggyNoble** [comment]
Brand guidelines [here](https://www.musical.ly/en-US/branding).

Do you have or know of any usage data for musical.ly to help us determine if it meets our criteria for adding brand icons?

**Comment by JapanYoshi** [comment]
let musical.ly fucking die already

**Comment by PeterShaggyNoble** [comment]
After consideration, musical.ly does not currently meet our criteria for the addition of brand icons and, as such, will not be added at this time. However, we will revisit this issue when we get around to creating a dedicated icon pack for brands.
