### ISSUE TITLE
file-document-outline

### ISSUE THREAD

**Issue by naofireblade** [Templarian/MaterialDesign#3117]
An outline version of the file-document icon would be much appreciated. The filled one does not fit all ui designs.

So a combination of these two:

![file-document](https://user-images.githubusercontent.com/12081369/39294531-4553d400-493c-11e8-83bc-8819c792e504.png)
![file-outline](https://user-images.githubusercontent.com/12081369/39294532-456d9624-493c-11e8-8af1-9afda61374df.png)

**Comment by GreenTurtwig** [comment]
Annoyingly there isn't enough space for a 2px gap between the two lines of text on the file one.

![](https://user-images.githubusercontent.com/15905797/39302045-392054c6-4949-11e8-9149-6e867948cdb1.png)![](https://user-images.githubusercontent.com/15905797/39302170-9d75b4fc-4949-11e8-904e-de7b38db52b6.png)
[file-document-outline.zip](https://github.com/Templarian/MaterialDesign/files/1950811/file-document-outline.zip)

**Comment by naofireblade** [comment]
Wow! Thanks for the fast realization. The gap might be a little bit odd but I think you already provided the best solution.

**Comment by MrGrigri** [comment]
IMO, these parts of the dog-ear look funny.

![image](https://user-images.githubusercontent.com/4528551/39373643-75ca4852-4a05-11e8-8085-033b60fac720.png)

**Comment by CoDEmanX** [comment]
Well, it makes the dog-ear look better at small sizes. Here's a preview with the edges flush to the inner borders:

![grafik](https://user-images.githubusercontent.com/1309249/39382882-693c2dd2-4a67-11e8-9a4c-cf4c1a015d08.png)

**Comment by GreenTurtwig** [comment]
No idea why @templarian made the corner smaller.
@codemanx you should probably open a new issue to update the existing `file-outline`.

**Comment by CoDEmanX** [comment]
It does make it look more folded and I like it.

**Comment by GreenTurtwig** [comment]
Either that or you used the existing line from the normal `file` icon. Not sure which one I prefer now.

**Comment by naofireblade** [comment]
Can you estimate when this will be included in a relase?

**Comment by GreenTurtwig** [comment]
Google's new outline design allows us to have a 2px gap. :smile_cat: 
[![](https://user-images.githubusercontent.com/15905797/40111217-1a97e09e-58fa-11e8-8a53-78ddeae65c93.png)](https://github.com/Templarian/MaterialDesign/files/2008608/file-document-outline.zip)

**Comment by Templarian** [comment]
[![file-document-outline](https://materialdesignicons.com/icon/file-document-outline)](https://materialdesignicons.com/icon/file-document-outline)

**Comment by naofireblade** [comment]
The icons are visible on materialdesignicons.com but not part of the download package 2.4.85. Is that correct?
