### ISSUE TITLE
keyboard-outline

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3118]
This is the new keyboard icon that has shown up in Google Assistant.

[![](https://user-images.githubusercontent.com/15905797/39300944-60b572e0-4945-11e8-8adb-8fb9fa34b08c.png)](https://github.com/Templarian/MaterialDesign/files/1950736/keyboard-outline.zip)

**Comment by Templarian** [comment]
[![keyboard-outline](https://materialdesignicons.com/icon/keyboard-outline)](https://materialdesignicons.com/icon/keyboard-outline)
