### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3119]
I know we discussed adding this when we first discovered the Extended set, but I can't remember whether we decided we should or not.

[![material design](https://user-images.githubusercontent.com/15157491/39303423-f0b549e4-494d-11e8-9bac-b9b682b6883f.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by Templarian** [comment]
[![material-design](https://materialdesignicons.com/icon/material-design)](https://materialdesignicons.com/icon/material-design)

So meta.
