### ISSUE TITLE
Contact us

### ISSUE THREAD

**Issue by AlirezaDroid** [Templarian/MaterialDesign#312]
there is not any relative icon for "contact us" and this is a bad struggle to select a suit icon for it.

**Comment by Templarian** [comment]
Usually people use the email icon for that type of stuff. Unless you can link me to an example I'm not sure what else means contact us.

**Comment by AlirezaDroid** [comment]
Forget contact us icon!
I'm surprised of your response speed!
Thanks dude, your amazing :)

**Comment by Templarian** [comment]
I'm just about to crash for the night, so if you had sent this 10 minutes later it would have been 8 hours later. You just had good timing. :stuck_out_tongue: 

If you need any other icons feel free to create another issue in the future.
