### ISSUE TITLE
Phabricator logo

### ISSUE THREAD

**Issue by felixfbecker** [Templarian/MaterialDesign#3120]
<img width="735" alt="image" src="https://user-images.githubusercontent.com/10532611/39351776-6e2daf4c-49b7-11e8-80d6-9bb2e8daa943.png">

**Comment by Templarian** [comment]
Agreed it's probably going to be too niche at this time. The products/services you listed are generally more widely known and used day-to-day so their icons are needed in websites/apps. A better comparison would be like Atlassian suite (which we include a few of), as it's it's an industry standard.

For this icon probably better to use the SVG or vector asset.

**Comment by vanesa** [comment]
Hi! I saw that fontawesome now has a Phabricator icon: https://fontawesome.com/icons?d=gallery&q=phabricator . Could you reconsider your decision? Would love to see it in the mdi collection for us to use. Thank you!

**Comment by PeterShaggyNoble** [comment]
Reopening this at @Templarian's request so we can reassess whether or not it now falls within the scope of this project, which shouldn't be taken as a guarantee that it *will* be added.

If anyone (cc: @TimDiekmann) can source an SVG of their logo, that would help speed up the process if we do decide to add it.

In the event that we decide to reject it again, I recommend requesting it from [Simple Icons](https://simpleicons.org/), a dedicated library of brand icons, as well.

**Comment by TimDiekmann** [comment]
So far I only found a PNG (#4380) but I'll do further research on it. Thanks for reopening!

**Comment by TimDiekmann** [comment]
https://www.pngtosvg.com/ gave me a pretty good result with the linked PNG. Should I do a PR?

**Comment by Templarian** [comment]
Yeah, that isn't going to be an optimal svg. Also we don't take PRs for this project. Everything is handled through external tooling.

**Comment by goyney** [comment]
This is a brand logo, so we absolutely need to following their branding guidelines (if any). Additionally, we will need an *officially* sourced SVG or vector-based version of the logo for inclusion.

**Comment by PeterShaggyNoble** [comment]
Had a dig through their GH repo and couldn't find one. We may need to reach out to them.

**Comment by TimDiekmann** [comment]
I have sent an email to their support.

**Comment by goyney** [comment]
This issue has been stagnant for several months now. We can't act unless we have something official. Considering we don't have a source logo and it is on the niche side, we're going to reclose this until a time in which we have enough information to potentially act on it.
