### ISSUE TITLE
database-import / database-export

### ISSUE THREAD

**Issue by velasarius** [Templarian/MaterialDesign#3124]
Hello team! I'd like to suggest a slight variation to the Import / Export icons, called Data Import and Data Export. As the difference in names suggest, the Data Import / Export icons specifically address data. Whereas the standard icons are universally understood to mean import and export of many different content types, for example, graphics, videos, audio, files, etc. My suggestion for a specific data type is a simple alteration to the current icons. Create a variant where the square housing of the current icons is not square but in the shape of data base icon. The database icon has an oval top resembling the top of the disk layers, and oval bottom edges. The center of the icon can resemble the current square variant with the arrows entering / exiting. The name of the new variant should appear next to the current standard icon. Import-Data, etc.  -- thanks amigos!

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/39479443-7bc99760-4d22-11e8-9a51-3ad72b505eb2.png) ![image](https://user-images.githubusercontent.com/4528551/39479467-8d174468-4d22-11e8-87ef-93fb9c5d69d3.png)

[database-import.zip](https://github.com/Templarian/MaterialDesign/files/1964231/database-import.zip)

**Comment by Templarian** [comment]
[![database-import](https://materialdesignicons.com/icon/database-import)](https://materialdesignicons.com/icon/database-import) [![database-export](https://materialdesignicons.com/icon/database-export)](https://materialdesignicons.com/icon/database-export)

**Comment by GreenTurtwig** [comment]
Also see https://github.com/Templarian/MaterialDesign/issues/1304
