### ISSUE TITLE
Icon names inconsistent with material.io names

### ISSUE THREAD

**Issue by IanLondon** [Templarian/MaterialDesign#3125]
Hey firstly thank you for this super useful project!

https://materialdesignicons.com/ has different names for icons than https://material.io/icons/.

For example, `alert` on this project is `warning` on material.io, and `alert-circle` here is `error` on material.io.

It makes it confusing to communicate icons, I need to specify whether I'm talking about material.io names or materialdesignicons.com names. It would be really helpful if the names were to match.

**Comment by Templarian** [comment]
This project existed before the official set from Google so the naming follows more inline with Font Awesome.

Not something we'll be investing time into. Most use either the official set or the community. We don't recommend mixing them.

**Comment by Templarian** [comment]
We have 73 open issues to sync in some missing icons. Hopefully will have this small difference resolved shortly (both packs add icons continuously, so there is sometimes a lag).

http://dev.materialdesignicons.com/issues (dev site).
