### ISSUE TITLE
Icon Request - Unreal Engine 4 `ue4-solid`

### ISSUE THREAD

**Issue by alexchicn** [Templarian/MaterialDesign#3126]
I found the game engine - unity, but not unreal engine 4. So I built a new icon `ue4-solid` by an icon [from here](https://commons.wikimedia.org/wiki/File:Unreal_Engine_4_logo_and_wordmark.svg) and optimised it.

![ic_ue4_solid_black_48dp](https://user-images.githubusercontent.com/2211006/39394666-33be271e-4b07-11e8-9bb5-3a4a87782805.png)

[ue4-solid.zip](https://github.com/Templarian/MaterialDesign/files/1957521/ue4-solid.zip)

**Comment by alexchicn** [comment]
Just found the unreal engine 4's logo was changed in [official website](https://www.unrealengine.com/en-US/branding).

So I update it:
![ic_ue4_solid_black_48dp](https://user-images.githubusercontent.com/2211006/39395255-0df1512a-4b0f-11e8-9f38-c39a9834761a.png)
[ue4-solid.zip](https://github.com/Templarian/MaterialDesign/files/1957571/ue4-solid.zip)

**Comment by CoDEmanX** [comment]
None of the approved logos comes without the circle border:
https://www.unrealengine.com/en-US/branding/

**Comment by Templarian** [comment]
[![unreal](https://materialdesignicons.com/icon/unreal)](https://materialdesignicons.com/icon/unreal)
