### ISSUE TITLE
Lock-clock (Gmail confidential mode)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3127]
https://www.gstatic.com/images/icons/material/system/2x/lock_clock_white_48dp.png

![grafik](https://user-images.githubusercontent.com/1309249/39395561-40a8304a-4ae0-11e8-856c-0fc09b4facc0.png)

[lock-clock.zip](https://github.com/Templarian/MaterialDesign/files/1957586/lock-clock.zip)

**Comment by Templarian** [comment]
[![lock-clock](https://materialdesignicons.com/icon/lock-clock)](https://materialdesignicons.com/icon/lock-clock)
