### ISSUE TITLE
Auto-meal

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3128]
[auto-meal.zip](https://github.com/Templarian/MaterialDesign/files/1957597/auto-meal.zip)

![grafik](https://user-images.githubusercontent.com/1309249/39395681-90fa334e-4ae1-11e8-9b94-ec4b7cff9331.png)

Ref: #866

**Comment by goyney** [comment]
Not sure about the name, but it's better then `auto-meal`. 😆 
[![silverware-clean](https://materialdesignicons.com/icon/silverware-clean)](https://materialdesignicons.com/icon/silverware-clean)
