### ISSUE TITLE
Milestone

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3129]
We have `sign-direction`, but not too sure it fits the abstract concept of "milestone". I suggest to add below icon, or alias the existing one.

![grafik](https://user-images.githubusercontent.com/1309249/39395708-1fd0338e-4ae2-11e8-8ebc-8a7fb0893ae7.png)

[milestone.zip](https://github.com/Templarian/MaterialDesign/files/1957602/milestone.zip)

Ref: #528

**Comment by goyney** [comment]
`flag-triangle` is very often used to signify a milestone as well.

**Comment by goyney** [comment]
Considering the GitHub milestone icon is similar to @CoDEmanX, I think we should add it.

**Comment by CoDEmanX** [comment]
I know this `flag-triangle` style icon from Outlook, where it stands for reminders. A generic `flag` icon is also a bit off. I am for adding my propsed icon as I haven't seen any good existing alternatives.

**Comment by goyney** [comment]
Alias `milestone` added to `sign-direction`.
