### ISSUE TITLE
Mobile-devices (tablet-cellphone)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3130]
Similar to `cellphone-link`, but with a tablet instead of a laptop.

![grafik](https://user-images.githubusercontent.com/1309249/39395756-f6808b0e-4ae2-11e8-945f-887564ea2183.png)

[mobile_devices.zip](https://github.com/Templarian/MaterialDesign/files/1957608/mobile_devices.zip)

Ref: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-179558442

**Comment by Templarian** [comment]
[![tablet-cellphone](https://materialdesignicons.com/icon/tablet-cellphone)](https://materialdesignicons.com/icon/tablet-cellphone)
