### ISSUE TITLE
ov-gif (create animation)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3131]
I believe this was used in older versions of the Google Photos app to create GIFs from image series, or perhaps it was used as indicator GIFs that were automatically created from burst shots.

![grafik](https://user-images.githubusercontent.com/1309249/39395804-78cee132-4ae3-11e8-8425-b264dc886297.png)

[ov_gif.zip](https://github.com/Templarian/MaterialDesign/files/1957611/ov_gif.zip)

Ref: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-179558442

**Comment by Templarian** [comment]
Need another name for this one. Not calling it `ov-gif` as that's confusing. 🤔

**Comment by CoDEmanX** [comment]
I believe that I found it with this name in their repository, but I don't know if there's another "official" name for it.

Maybe call it something like animation-burst-image? Or animation-gif.

**Comment by GreenTurtwig** [comment]
I'd say `animation-variant`. There's a burst image icon in Photos, did a quick search and couldn't find it in an issue though.

**Comment by CoDEmanX** [comment]
`animation-play` would be another option

**Comment by Templarian** [comment]
[![animation-play](https://materialdesignicons.com/icon/animation-play)](https://materialdesignicons.com/icon/animation-play)

If we add this one do you think we the official one still? `animation-variant` and `animation-play-variant`?

**Comment by CoDEmanX** [comment]
Seems kind of redundant to add from the shapes used, but it would still be nice as addition to the burst icon we have, but to create a looping GIF from the shots. The burst icon doesn't seem to use rounding on the two vertical bars.

**Comment by JamesCoyle** [comment]
I'm gonna close this one out as it seems pretty redundant. `camera-burst-play` doesn't really make much sense.
