### ISSUE TITLE
star-face

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3132]
Icon used in the specs as counter example: "Don’t apply human characteristics to inanimate objects."

I like this fella anyway.

![grafik](https://user-images.githubusercontent.com/1309249/39395837-08dc1c40-4ae4-11e8-9a5f-5c1baeb67c05.png)

[star-face.zip](https://github.com/Templarian/MaterialDesign/files/1957620/star-face.zip)

Ref: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-170745882

**Comment by JamesCoyle** [comment]
I think it would actually be good for kids apps

**Comment by GreenTurtwig** [comment]
Yep, it's the icon they use in the Play Store for "family" apps. 🐈

**Comment by Templarian** [comment]
[![star-face](https://materialdesignicons.com/icon/star-face)](https://materialdesignicons.com/icon/star-face)
