### ISSUE TITLE
Select-group

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3133]
Found in the components sticker sheet for Illustrator. It guess it stands for "select group".

![grafik](https://user-images.githubusercontent.com/1309249/39396035-1580cc72-4ae7-11e8-9991-9c8b73d65dcb.png)

[select-group.zip](https://github.com/Templarian/MaterialDesign/files/1957654/select-group.zip)

Ref: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-193475317

**Comment by goyney** [comment]
Added, but accidentally assigned to myself. Needs to be reassigned to Google.

**Comment by goyney** [comment]
Reassigned.
