### ISSUE TITLE
magnify-close

### ISSUE THREAD

**Issue by Bennith** [Templarian/MaterialDesign#3134]
Using the classic search/magnifying glass icon bit with strike through as to inform user searched failed.

**Comment by PeterShaggyNoble** [comment]
Would a `magnify-alert` icon not be more suitable to represent a failed search?

**Comment by MrGrigri** [comment]
I use a `magnify-close` (not included in one of my projects) to represent this.

![image](https://user-images.githubusercontent.com/4528551/39435736-6359be0e-4c59-11e8-8ddf-c0c1539fa17b.png)

**Comment by MrGrigri** [comment]
I'm going to change this name to `magnify-close` in order to keep with standards.

![image](https://user-images.githubusercontent.com/4528551/39583162-b4a866ca-4eac-11e8-8d55-05653dc261a7.png)

[magnify-close.zip](https://github.com/Templarian/MaterialDesign/files/1971330/magnify-close.zip)

**Comment by Templarian** [comment]
[![magnify-close](https://materialdesignicons.com/icon/magnify-close)](https://materialdesignicons.com/icon/magnify-close)
