### ISSUE TITLE
set-top-box device

### ISSUE THREAD

**Issue by garyt72** [Templarian/MaterialDesign#3135]
Requesting one or more variants of set top box / Stereo / Receiver / DVR etc icons

**Comment by Templarian** [comment]
Duplicate of #2941

Would these work? If not can you please post some more examples on the above issue. It's slated for the next release.

**Comment by garyt72** [comment]
That would be good for receiver, but I was also thinking of something a little smaller / thinner like this:
![image](https://image.shutterstock.com/image-vector/set-top-box-modern-icon-260nw-613060469.jpg)
and maybe a BD or DVD player icon something like this:
![image](https://static.thenounproject.com/png/143857-200.png)

**Comment by Templarian** [comment]
[![disk-player](https://materialdesignicons.com/icon/disk-player)](https://materialdesignicons.com/icon/disk-player)

Still need a set top. But what about above for a generic disk player?

**Comment by Templarian** [comment]
[![set-top-box](https://materialdesignicons.com/icon/set-top-box)](https://materialdesignicons.com/icon/set-top-box) [![record-player](https://materialdesignicons.com/icon/record-player)](https://materialdesignicons.com/icon/record-player)

**Comment by garyt72** [comment]
Nice!!  Thank you!

**Comment by CoDEmanX** [comment]
The disk player can't actually fit the disk 😄

Nice work though. I wonder if the receiver contribution should avoid rounding for the feet.
