### ISSUE TITLE
database-search

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3136]
This is in response to #3109 and the shape, size, and location of the magnifying glass. I have updated the `database-search` icon to match the stock google icon. We have also discussed that the location still needs to be at the bottom for recognition purposes. 

Here is the current (left) and new (right). The new magnifying glass allows for the data stack to remain in the center.

![image](https://user-images.githubusercontent.com/4528551/39477418-7cf56458-4d1c-11e8-9156-e11987860a2d.png) ![image](https://user-images.githubusercontent.com/4528551/39477387-698a3a74-4d1c-11e8-84a7-0c6da91e86ab.png)

**Comment by MrGrigri** [comment]
[database-search.zip](https://github.com/Templarian/MaterialDesign/files/1964237/database-search.zip)

**Comment by Templarian** [comment]
Fixed. 😃
