### ISSUE TITLE
table-search

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3137]
This is in response to #3109 and the shape, size, and location of the magnifying glass. I have updated the table-search icon to match the stock google icon. We have also discussed that the location still needs to be at the bottom for recognition purposes.

Here is the current (left) and new (right). The new magnifying glass allows for the table to remain in the center.

![image](https://user-images.githubusercontent.com/4528551/39477915-f95a8086-4d1d-11e8-814d-22d540808c55.png) ![image](https://user-images.githubusercontent.com/4528551/39477900-ec8828f4-4d1d-11e8-8c0e-2d536b2d92a2.png)

**Comment by MrGrigri** [comment]
[table-search.zip](https://github.com/Templarian/MaterialDesign/files/1964236/table-search.zip)

**Comment by Templarian** [comment]
[![table-search](https://materialdesignicons.com/icon/table-search)](https://materialdesignicons.com/icon/table-search)
