### ISSUE TITLE
progress-clock

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3138]
With the new `progress` icons, I thought this might come in handy too:

[![progress-clock](https://user-images.githubusercontent.com/15157491/39478183-9340616c-4d59-11e8-87e1-8e7dbe1c8242.png)](https://github.com/Templarian/MaterialDesign/files/1964148/progress-clock.zip)

**Comment by Templarian** [comment]
[![progress-clock](https://materialdesignicons.com/icon/progress-clock)](https://materialdesignicons.com/icon/progress-clock)
