### ISSUE TITLE
mood-bad

### ISSUE THREAD

**Issue by LiadIdan** [Templarian/MaterialDesign#3140]
Hi guys!
It would be great to have more emojis mood icons such: confused, surprised, worry, angry, proud, etc...
btw, I couldn't find the "mood bad" icon from material design icons.

**Comment by PeterShaggyNoble** [comment]
See #134 for a list of already requested smileys. If any you are looking for are not included on that list, please open an individual request for each one so we can track them better. If you can provide examples that would help too (what would `proud` look like, for example).

Going to leave this one open as a request for Google's `mood bad` icon.

**Comment by goyney** [comment]
Google's stock `mood_bad` icon:
![image](https://user-images.githubusercontent.com/1015040/49035949-517e2a00-f184-11e8-82e1-5da63e6ed1f7.png)

My creation of a filled version:
![image](https://user-images.githubusercontent.com/1015040/49035967-5cd15580-f184-11e8-93ad-1013a6a55f42.png)

[emoticon-frown.zip](https://github.com/Templarian/MaterialDesign/files/2616972/emoticon-frown.zip)

**Comment by PeterShaggyNoble** [comment]
The mouth on the outline version needs to come up half a point.

See Google's `sentiment_very_dissatisfied_outline`, for example:

![sentiment_very_dissatisfied_outline](https://user-images.githubusercontent.com/15157491/49090898-983c5480-f256-11e8-92c5-87cecbdaafab.png)

**Comment by CoDEmanX** [comment]
Looks like a comic depiction of someone dying / being dead rather than bad mood / dissatisfaction to me.I would rather call these Emojis dissatisfied / bad mood: ☹️😞

**Comment by goyney** [comment]
[![emoticon-frown](https://materialdesignicons.com/icon/emoticon-frown)](https://materialdesignicons.com/icon/emoticon-frown)[![emoticon-frown-outline](https://materialdesignicons.com/icon/emoticon-frown-outline)](https://materialdesignicons.com/icon/emoticon-frown-outline)
