### ISSUE TITLE
adobe

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3142]
Find it difficult to believe we don't have Adobe's icon. Their original is exactly 24 pixels wide, so I scaled it down to 20 pixels. 

![image](https://user-images.githubusercontent.com/4528551/39594710-b2a03ce0-4eca-11e8-8e25-8b1b6cc38c86.png)

[adobe.zip](https://github.com/Templarian/MaterialDesign/files/1972094/adobe.zip)

**Comment by CoDEmanX** [comment]
Shouldn't hurt to shift it down a bit to align the top border with the grid

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/39634940-52895e9a-4f79-11e8-9829-ac92d2a6ca0c.png)

[adobe.zip](https://github.com/Templarian/MaterialDesign/files/1974874/adobe.zip)

**Comment by CoDEmanX** [comment]
How can I say this... [Wrong Direction - One Thing](https://youtu.be/NIyFLF2OBm4)? 😅

There's a lot of white space at the bottom, making it visually lighter down there. In cases where one could either shift the shape up or down for grid alignment with the same amount of (sub)pixels, I would go for the visually lighter side to center it better.

**Comment by MrGrigri** [comment]
I went up because the Adobe logo is intended to have the most white-space at the bottom.

**Comment by CoDEmanX** [comment]
You mean like interpreting is this way?

![grafik](https://user-images.githubusercontent.com/1309249/39676327-ea79a728-5168-11e8-8ebf-5283f2b6c9cb.png)

**Comment by MrGrigri** [comment]
More like this...The wihite-space at the bottom is larget at the top.

![image](https://user-images.githubusercontent.com/4528551/39678147-9dc1919e-5144-11e8-81bb-b61c00b88a27.png)

**Comment by Templarian** [comment]
[![adobe](https://materialdesignicons.com/icon/adobe)](https://materialdesignicons.com/icon/adobe)
