### ISSUE TITLE
Security Lock

### ISSUE THREAD

**Issue by Alekhen** [Templarian/MaterialDesign#3143]
While I could use [security](https://materialdesignicons.com/icon/security), it would be nice to have a 'security-lock' icon in the library. I could then use it to represent car anti-theft devices in the app I'm designing.

I grabbed the lock shape from [phone-locked](https://materialdesignicons.com/icon/phone-locked) and followed the pattern used in [security-home](https://materialdesignicons.com/icon/security-home) to create this new icon.

![image](https://user-images.githubusercontent.com/1837101/39605621-8e15c54c-4eee-11e8-8df5-ad91e714dbd3.png)

[security-lock.svg.zip](https://github.com/Templarian/MaterialDesign/files/1972846/security-lock.svg.zip)

**Comment by CoDEmanX** [comment]
A slightly larger lock would be nice to be on grid

**Comment by Croutonix** [comment]
I think you should use the same lock path as either [`folder-lock`](https://materialdesignicons.com/icon/folder-lock) or [`wifi-strength-lock`](https://materialdesignicons.com/icon/wifi-strength-4-lock)

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/39665849-2a8d2dbc-5092-11e8-8b97-d14ac541e4d2.png)![](https://user-images.githubusercontent.com/15905797/39665853-35313b64-5092-11e8-9ce9-632b5585ddc6.png)![](https://user-images.githubusercontent.com/15905797/39665857-488286dc-5092-11e8-9b12-56bf597f4249.png)
[lock-shield.zip](https://github.com/Templarian/MaterialDesign/files/1976891/lock-shield.zip)

**Comment by Croutonix** [comment]
Yes definitively the second one.

**Comment by Alekhen** [comment]
I'd originally played with the fat lock like you did in the first one, but it doesn't work. The second one works, but feels a little low on the shield and the arch doesn't look like it lines up with the grid. I'd still recommend using the second one I put together.

**Comment by PeterShaggyNoble** [comment]
Yeah, I prefer @Alekhen's second one too.

**Comment by CoDEmanX** [comment]
Moving the lock up is a good idea, maybe just one pixel or two.

**Comment by Alekhen** [comment]
I shifted the lock up one pixel. I think it feels more balanced now especially at smaller sizes.

I think we need to keep the name of the icon as 'security-lock' so it matches the naming convention of [security](https://materialdesignicons.com/icon/security), [security-account](https://materialdesignicons.com/icon/security-account), [security-home](https://materialdesignicons.com/icon/security-home), and [security-network](https://materialdesignicons.com/icon/security-network).

Here's the revised icon:

![security-lock](https://user-images.githubusercontent.com/1837101/39824402-79836850-536c-11e8-9ca7-7120f1b7b4ca.png)

[security-lock-2.svg.zip](https://github.com/Templarian/MaterialDesign/files/1988504/security-lock-2.svg.zip)

**Comment by E3V3A** [comment]
@Alekhen  But now it doesn't look like a lock anymore. But more like a suitcase. The RH icon from @GreenTurtwig seem more balanced in that regard.

**Comment by Templarian** [comment]
[![security-lock](https://materialdesignicons.com/icon/security-lock)](https://materialdesignicons.com/icon/security-lock)
