### ISSUE TITLE
Paint bucket

### ISSUE THREAD

**Issue by xavigarcia** [Templarian/MaterialDesign#3144]
![paintbucket](https://user-images.githubusercontent.com/2465208/39636191-cd616978-4fbf-11e8-9c36-39dc9e083d3b.gif)
Thanks

**Comment by PeterShaggyNoble** [comment]
See `format-color-fill`:

[![format-color-fill](https://user-images.githubusercontent.com/15157491/39637100-f58afdac-4fb9-11e8-83a8-b8cff26e9598.png)](https://materialdesignicons.com/icon/format-color-fill)
