### ISSUE TITLE
OnStar Logo

### ISSUE THREAD

**Issue by Alekhen** [Templarian/MaterialDesign#3145]
This brand icon would be useful on automotive websites. I don't think we need to include both versions in the library, just one. However, here are two versions to decide between.

![image](https://user-images.githubusercontent.com/1837101/39640915-bc3edab2-4f89-11e8-8843-120e4bf83425.png)

![image](https://user-images.githubusercontent.com/1837101/39640963-d33c1e6e-4f89-11e8-9653-305ad53b93a1.png)

[onstar.svg.zip](https://github.com/Templarian/MaterialDesign/files/1975263/onstar.svg.zip)
[onstar-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/1975262/onstar-variant.svg.zip)

**Comment by MrGrigri** [comment]
I don't believe this is too niche for this project. What were you intending to use this for?

**Comment by Alekhen** [comment]
Car dealership software and websites indicating whether or not a vehicle is equipped with OnStar.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/39665972-2f73af48-5094-11e8-800a-d2edc8091f9b.png)](https://github.com/Templarian/MaterialDesign/files/1976909/sos.zip)

I would suggest an SOS icon instead as OnStar is primarily an American service. It does appear in other countries but only really on Opel cars (Vauxhall and Holden).

**Comment by MrGrigri** [comment]
@GreenTurtwig, I wouldn't do that because he's wanting to establish a branded feature. 

@Alekhen, I believe this is too niche for this project and we are limiting the amount of branded logos in this pack.

**Comment by Templarian** [comment]
I'm leaning toward the side of this being too niche. I'm marking it as brand rejected but leaving the contribution tag.

I think we're going to go through and add a lot of these shortly, but will leave them out of the webfont. So don't read into the rejected tag too much.
