### ISSUE TITLE
Car Dealership

### ISSUE THREAD

**Issue by Alekhen** [Templarian/MaterialDesign#3146]
I need an icon to represent a car dealership. I put together two options. I prefer option 1, but can't decide if that's the best option for the library.

![car-dealership](https://user-images.githubusercontent.com/1837101/39643029-ac875066-4f90-11e8-80a8-c742296b22f9.png)
Option 1

![car-dealership 1](https://user-images.githubusercontent.com/1837101/39643037-ae594c50-4f90-11e8-8f99-e04745ddd94e.png)
Option 2

[dealership-thin.svg.zip](https://github.com/Templarian/MaterialDesign/files/1975404/dealership-thin.svg.zip)
[dealership-thick.svg.zip](https://github.com/Templarian/MaterialDesign/files/1975403/dealership-thick.svg.zip)

**Comment by PeterShaggyNoble** [comment]
I don't think this one is going to translate internationally.

**Comment by Alekhen** [comment]
I beg to differ. Automotive manufacturers have taken the same car dealership experience, including their branded signage and showrooms, all over the world. For example, a Nissan dealership in Los Angeles will look look just like a Nissan dealership in Indonesia. A Mercedes dealership in Germany will look just like a Mercedes dealership in Argentina. etc.

**Comment by Alekhen** [comment]
I just used this icon in a project I'm working on and Option 2 matches the material library best.

**Comment by goyney** [comment]
I get more of a "car wash" vibe from these icons.

**Comment by goyney** [comment]
After some internal discussions about this issue, I think we're going to reject these icons. They don't universally say "car dealership." Something like `car-multiple` would serve the use case for an establishment that sells cars.
