### ISSUE TITLE
heart-circle

### ISSUE THREAD

**Issue by derRAV3N** [Templarian/MaterialDesign#3147]
Hey there.

I think it's missing a heart-circle icon, just the normal heart icon, but with an circle around it, like star-circle.

Greetings,
Raphael

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/39665897-2125ae7e-5093-11e8-9d4d-96b982b43f3d.png)![](https://user-images.githubusercontent.com/15905797/39665903-2f635d74-5093-11e8-8aed-03c58482243d.png)
[heart-circle.zip](https://github.com/Templarian/MaterialDesign/files/1976897/heart-circle.zip)

**Comment by Templarian** [comment]
[![heart-circle](https://materialdesignicons.com/icon/heart-circle)](https://materialdesignicons.com/icon/heart-circle) [![heart-circle-outline](https://materialdesignicons.com/icon/heart-circle-outline)](https://materialdesignicons.com/icon/heart-circle-outline)
