### ISSUE TITLE
Party

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3148]
🎉

searched for a party icon, but wasn't able to find one?
more specifically this icon that pops up when HomeAssistant has a new version.
Would be way cool if we could have that.
cheers,
Marius

**Comment by CoDEmanX** [comment]
What HomeAssistant are you talking about? https://www.home-assistant.io/ ?

**Comment by hvbhome** [comment]
sorry, yes, thats the one.

**Comment by CoDEmanX** [comment]
Can you post a screenshot?

**Comment by hvbhome** [comment]
I fear you’re right 
However,
Banners, hats and flags would work, or a variant cake-party....

**Comment by goyney** [comment]
We have plenty of icons that could be used to indicate a party:

![image](https://user-images.githubusercontent.com/1015040/48455931-1d216b80-e78b-11e8-8bfe-febb71d5b5cb.png)![image](https://user-images.githubusercontent.com/1015040/48455950-2f030e80-e78b-11e8-9d6d-500734adde1c.png)

There's also a couple other cake variations, or things like `wine` or `bow-tie` which could be used to indicate something more formal. Would any of these work?

**Comment by Templarian** [comment]
I think we might be able to still do one similar to the party popper maybe?

Also ever since IT it's difficult to view balloons the same. 😨

**Comment by PeterShaggyNoble** [comment]
Here's Google's take on it:

[![celebration](https://user-images.githubusercontent.com/15157491/54347666-55ed2680-463f-11e9-950e-c60b971a753b.png)](https://github.com/Templarian/MaterialDesign/files/2965770/celebration.zip)

**Comment by eman1986** [comment]
hope to see this available soon 😁

**Comment by goyney** [comment]
[![party-popper](https://materialdesignicons.com/icon/party-popper)](https://materialdesignicons.com/icon/party-popper)
