### ISSUE TITLE
TeamSpeak 3

### ISSUE THREAD

**Issue by kaziu687** [Templarian/MaterialDesign#3149]
Hi, It will be nice to see teamspeak 3 icon in materialdesign.

![teamspeak](https://www.teamspeak.com/assets/images/logos/teamspeak_small.png)

**Comment by Templarian** [comment]
If someone has time to remove the points. Right now the vector is far too large... 278 points.

![image](https://user-images.githubusercontent.com/338885/39954176-608d5318-5580-11e8-8f95-4489b09252e2.png)
[teamspeak.zip](https://github.com/Templarian/MaterialDesign/files/1997327/teamspeak.zip)

**Comment by augustin32** [comment]
But it is not legible at 1:1 resolution

**Comment by GreenTurtwig** [comment]
Quite a large amount of users are or already have switched to Discord. A generic headset icon could always be used as an alternative.

**Comment by Templarian** [comment]
I'm going to lean that way and agree that this is probably going to be too detailed unless they have a more general icon for us to add. Closing this issue out.
