### ISSUE TITLE
Alphabetical

### ISSUE THREAD

**Issue by eevleevs** [Templarian/MaterialDesign#315]
I use this one instead of abc. I made it, feel free to copy if you like.

https://dl.pushbulletusercontent.com/aW2ApTsnef4WWURIYlZInjKqPPJx0Lmb/ab.png
https://dl.pushbulletusercontent.com/FxulHk8xYavGwLTabacxllIHESpwI3Hl/ab.xcf

**Comment by Templarian** [comment]
I like the idea, but alpha and beta could confuse users for symbols.

Thanks for the suggestion and please don't hesitate to submit icon requests! :smile:
