### ISSUE TITLE
Hand click alias for gesture-tap

### ISSUE THREAD

**Issue by iamsarker** [Templarian/MaterialDesign#3150]
interactive icon

![interactive_icon svg](https://user-images.githubusercontent.com/5415001/39671960-87970a08-5143-11e8-8126-20b421cc00a4.png)

**Comment by CoDEmanX** [comment]
We could use an alias I guess

**Comment by Templarian** [comment]
Added the Alias `interaction-tap` and `interaction-double-tap` (`gesture-double-tap`)
