### ISSUE TITLE
Dynamics Icon

### ISSUE THREAD

**Issue by seanmcne** [Templarian/MaterialDesign#3153]
Would you be able to add a new icon for Microsoft Dynamics (very similar to the Azure icon).  And example is here: https://pbs.twimg.com/profile_images/785630384545370112/QamP2h84.jpg 

![image](https://user-images.githubusercontent.com/2292260/39721331-1013c9d8-51f4-11e8-85fb-3d207a487f7f.png)

**Comment by Templarian** [comment]
[![microsoft-dynamics](https://materialdesignicons.com/icon/microsoft-dynamics)](https://materialdesignicons.com/icon/microsoft-dynamics)

**Comment by seanmcne** [comment]
Excellent - thanks Austin, always amazed at the quick turnaround!
