### ISSUE TITLE
Heaters

### ISSUE THREAD

**Issue by gabglus** [Templarian/MaterialDesign#3154]
Hi, 

Couldn't find any references in the icon requests for these missing icons:

- Radiator
- Infrared Heater
- Patio Heater
- Air Heater

![image](https://user-images.githubusercontent.com/19849374/39725641-27635798-5212-11e8-970c-d55e87de2fde.png)

![image](https://user-images.githubusercontent.com/19849374/39725681-4f08fb40-5212-11e8-96f3-8baeb147cc29.png)

![image](https://user-images.githubusercontent.com/19849374/39725708-608d6c98-5212-11e8-99cb-3b258c48230d.png)

![image](https://user-images.githubusercontent.com/19849374/39725933-0d0da992-5213-11e8-9fc0-d6e47c70055b.png)

**Comment by PeterShaggyNoble** [comment]
Radiator already exists. Could you edit this issue down to a single request and then open separate issues for the others, please, so we can better track each one?

[![radiator](https://user-images.githubusercontent.com/15157491/39749671-3eeab462-52ab-11e8-9d3a-a5a771d3f2f4.png)](https://materialdesignicons.com/icon/radiator)
