### ISSUE TITLE
video-plus / video-call

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3156]
Google recently added their `video call` icon to YouTube's header as a link to create a video or post.

[![video call](https://user-images.githubusercontent.com/15157491/39754004-a3af2f10-52b8-11e8-90eb-4b9f960322ce.png)](https://github.com/google/material-design-icons/blob/master/av/svg/production/ic_video_call_24px.svg)

**Comment by Templarian** [comment]
[![video-plus](https://materialdesignicons.com/icon/video-plus)](https://materialdesignicons.com/icon/video-plus) [![video-minus](https://materialdesignicons.com/icon/video-minus)](https://materialdesignicons.com/icon/video-minus)
