### ISSUE TITLE
Trowel

### ISSUE THREAD

**Issue by lucas-dolsan** [Templarian/MaterialDesign#3157]
Icon request for a trowel

that mason thingy

here are some examples: 
[trowel images google search](https://www.google.com.br/search?q=trowel&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjmi6P4lvbaAhWEx5AKHUO_AFwQ_AUICigB&biw=1745&bih=885)

**Comment by Croutonix** [comment]
Might be hard to do without perspective.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/45644084-b9303e80-ba8a-11e8-95e7-a0fc25e86ce3.png)
[trowel.zip](https://github.com/Templarian/MaterialDesign/files/2389885/trowel.zip)

**Comment by PeterShaggyNoble** [comment]
I would have assumed that this was a request for a gardening trowel, rather than a finishing trowel. @lucas-dolsan, can you confirm, please?

**Comment by lucas-dolsan** [comment]
> I would have assumed that this was a request for a gardening trowel, rather than a finishing trowel. @lucas-dolsan, can you confirm, please?

yeah, kinda like [this image](https://images.homedepot-static.com/productImages/eeafb1ff-7f53-4f54-8a45-1e11e73edabd/svn/anvil-brick-trowels-57490-64_1000.jpg), with a narrow pointy end. I imagine it's pretty hard to draw this image as an icon.

**Comment by MrGrigri** [comment]
IMO, this icon is too niche for this project.

**Comment by goyney** [comment]
Closing because the `Consider Closing` label was added a while ago now with no new ideas.
