### ISSUE TITLE
home-climate

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3158]
as topic
searched but couldn't find any reference, either to existing icons, or requests?
If so: please consider making the mdi:home with a thermometer or fan inside?

**Comment by PeterShaggyNoble** [comment]
Would thermometer or fan not do the job by themselves, within the context of a home automation project?

**Comment by hvbhome** [comment]
Using that indeed right now, it's just that i was trying to juxtapose it to the outside climate settings, using that too....
Also, in a tabbed view with home-assistant, home-security, home-location, and home-heart, it would really fit extremely nicely...

**Comment by DocCoding** [comment]
![image](https://user-images.githubusercontent.com/22134144/40511243-60e7bc08-5f9f-11e8-8046-853c64bd87df.png)
Here's what I quickly drafted. I'm not 100% sure about the length of the thermometer, maybe it'll end up 1dp shorter.

**Comment by hvbhome** [comment]
cool!
would it be possible to have the slightest hint of the scale, as in mdi:thermometer-lines? Or is that to small to accommodate. 
the regular mdi:thermometer has a filling in the top that mimics the quicksilver in the scale. maybe have it shorter and a pixel wider to enable that? 
Not sure but it indeed seems just out of proportion (nitpicking here, no first world problems of course...)

**Comment by DocCoding** [comment]
I tried it with the filling or a scale, but both look out of place, are too detailed or would not go along with the MD icon guidelines.

**Comment by boehan** [comment]
Proposal for an outline version:
![image](https://user-images.githubusercontent.com/7279415/59303781-380f7c00-8c97-11e9-8e3d-c4f2b5b7a085.png)

[home-climate-outline.zip](https://github.com/Templarian/MaterialDesign/files/3278415/home-climate-outline.zip)

**Comment by goyney** [comment]
[![home-thermometer](https://materialdesignicons.com/icon/home-thermometer)](https://materialdesignicons.com/icon/home-thermometer)[![home-thermometer-outline](https://materialdesignicons.com/icon/home-thermometer-outline)](https://materialdesignicons.com/icon/home-thermometer-outline)

**Comment by Mariusthvdb** [comment]
Thx!

**Comment by Mariusthvdb** [comment]
please see https://github.com/Mariusthvdb/custom-icons where I added the rejected home-climate and home-climate-outline, ofc credited both the authors and this discussion in the Pr.

**Comment by goyney** [comment]
I'd be cautious about how you name those. They look more like keyholes then thermometers, which is why we added the versions we did.
