### ISSUE TITLE
baby-bottle

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3159]
Found on Google IO 2018 Maps page. This could possible be optimized. It's not even 2dp width strokes nore was it on-grid. I fixed the on-grid part, but the stroke could possibly be tweeked. 

![image](https://user-images.githubusercontent.com/4528551/39770150-78ef0cda-52ab-11e8-9799-8c293db86dd1.png)

[baby-bottle.zip](https://github.com/Templarian/MaterialDesign/files/1984828/baby-bottle.zip)

**Comment by MrGrigri** [comment]
Here is my own version as the Google stock doesn't follow MD guidelines. I stuck with a 1.5-pixel wide stroke as a 2-pixel stroke didn't work. I've also changed the name to `bottle-baby`.

![image](https://user-images.githubusercontent.com/4528551/61247902-3a8a4900-a70f-11e9-8b0b-f119b3866b4a.png)
![image](https://user-images.githubusercontent.com/4528551/61247919-45dd7480-a70f-11e9-9b83-3227833ff5eb.png)

---
#### Files
[bottle-baby.zip](https://github.com/Templarian/MaterialDesign/files/3394140/bottle-baby.zip)

**Comment by goyney** [comment]
I think we should stick with `baby-bottle` since we have several other icons that start with `baby-*`.

**Comment by goyney** [comment]
What would the solid version look like with the nipple outlined? I think it gets lost at native resolution.

**Comment by MrGrigri** [comment]
Just the nipple, or the lid as well?

**Comment by goyney** [comment]
🤔 I'm not sure, actually.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/61250041-f51c4a80-a713-11e9-94ac-37283214615e.png)

**Comment by MrGrigri** [comment]
Added.
