### ISSUE TITLE
account-check-variant

### ISSUE THREAD

**Issue by Huntajames** [Templarian/MaterialDesign#316]
Would be great to have some icons to represent government bodies, positions, voting, ballots, etc.

**Comment by PeterShaggyNoble** [comment]
Google has a few voting related icons in its Material Icons Extended set. We already have a variant of `how to reg` called `account-check`.

![how-to-reg](https://user-images.githubusercontent.com/15157491/36143422-ff7dca34-10a2-11e8-981d-fab6b2742ad8.png) ![how to vote](https://user-images.githubusercontent.com/15157491/36143262-8970f53c-10a2-11e8-898e-6fe824fac36b.png) ![where to vote](https://user-images.githubusercontent.com/15157491/36143311-a82aaa72-10a2-11e8-9a09-ebb1e7462f00.png)

**Comment by MrGrigri** [comment]
`vote` and `vote-outline` have been added and `map-marker-check` is being tracked in #3673. So this issue is going to be used to track an `account-check-variant`.

**Comment by Templarian** [comment]
[![account-check](https://materialdesignicons.com/icon/account-check)](https://materialdesignicons.com/icon/account-check) [![account-check-outline](https://materialdesignicons.com/icon/account-check-outline)](https://materialdesignicons.com/icon/account-check-outline)
