### ISSUE TITLE
dog-service

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3160]
Just as a reference to what Google has on the Google IO Maps page. I do not believe this icon follows the MD guidelines.

![image](https://user-images.githubusercontent.com/4528551/39770894-a266cd94-52ad-11e8-8bdf-699a43844e49.png)

[service-animal.zip](https://github.com/Templarian/MaterialDesign/files/1984868/service-animal.zip)

**Comment by PeterShaggyNoble** [comment]
Tricky to identify what it is at 24*24.

**Comment by GreenTurtwig** [comment]
Yeah, these map icons weren't designed for MD.

**Comment by Templarian** [comment]
[![dog-service](https://materialdesignicons.com/icon/dog-service)](https://materialdesignicons.com/icon/dog-service)
