### ISSUE TITLE
Automotive Transmission

### ISSUE THREAD

**Issue by Alekhen** [Templarian/MaterialDesign#3161]
I need an icon to represent a car transmission. Here's some ideas I played around with inspired by [file-tree](https://materialdesignicons.com/icon/file-tree) and [sitemap](https://materialdesignicons.com/icon/sitemap).

<img width="450" alt="concepts" src="https://user-images.githubusercontent.com/1837101/39772869-90f07cbc-52b3-11e8-892f-b14a462c1d48.png">

I think this version fits the library best.

![transmission](https://user-images.githubusercontent.com/1837101/39772977-e72d5bae-52b3-11e8-89b6-97f769759eaf.png)

[transmission.svg.zip](https://github.com/Templarian/MaterialDesign/files/1985011/transmission.svg.zip)

**Comment by goyney** [comment]
Added as `car-shift-pattern`.
[![car-shift-pattern](https://materialdesignicons.com/icon/car-shift-pattern)](https://materialdesignicons.com/icon/car-shift-pattern)
