### ISSUE TITLE
New MD Icon Styles

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3163]
The team here at MDI are currently discussing the new updates to the [MD Guidelines](https://material.io/tools/icons/) and the new icon styles available. We will be deciding how best to take on the task of converting our library of icons and where this project will go from here. 

We look forward to the future of Material Design and can't wait to help you realize your awesome design ideas in the near future!

---

#### Update May 10th, 2018
Our immediate concerns are to continue adding new stock google icons and expand our range of filled and outline variants whilst continuing to add icon requests. We are looking into support for the two-tone variant once the new site goes live and rounded and sharp will likely follow soon after.

New contributions now require both a filled and outline variant where appropriate. Feel free to open requests for missing outline icons as needed to help us focus our time on getting icons which are most useful to you added faster. You can help to prioritize requests by adding a thumbs up reaction. 

We thank you for your patience as our small team work to merge all of the new icons.

**Comment by GreenTurtwig** [comment]
#### List of `outline` variants that need updating

MDI name on left and stock name on right (`outline` has been stripped from the names).
- `account-box` - `account_box`
- `account-multiple` - `people` **Variant**
- `account-multiple-plus`  **Update**
- `account` - `person` **Variant**
- `account-plus` - `person_add` **Variant**
- `cart` - `shopping_cart` **Reassign**
- `check-circle` - `check_circle` **Reassign**
- `clipboard-check` - `assignment_turned_in` **Reassign**
- `clipboard` **Update**
- `clipboard-pulse` **Update**
- `coffee` - `local_cafe` **Reassign**
- `compass` - `explore` **Reassign**
- `content-save` - `save` **Reassign**
- `email` - `email` **Reassign**
- `eye` - `remove_red_eye` **Reassign**
- `eye-off` **Update**
- `eye-plus` **Update**
- `eye-settings` **Update**
- `fast-forward` - `fast_forward` **Reassign**
- `file` - `insert_drive_file` **Reassign**
- `file-download` **Update**
- `flag` - `flag` **Reassign**
- `folder` - `folder` (Existing icon should be renamed to `folder-open`)
- `folder-multiple` **Update**
- `forum` - `forum` **Variant**
- `home` - `home` **Reassign**
- `map-marker` - `place` **Reassign**
- `minus-box` - `indeterminate_check_box` **Reassign**
- `note` - `note` **Reassign**
- `note-multiple **Update**
- `note-plus` **Update**
- `plus-box` - `add_box` **Reassign**
- `rewind` - `fast_rewind` **Reassign**
- `settings` - `settings` **Reassign**
- `thumb-down` - `thumb_down` **Reassign**
- `thumb-up` - `thumb_up` **Reassign**

**Variant**: Create a new variant with the old design.
**Update**: *Community* icon that needs to be updated to match the new style.
**Reassign**: Needs to be reassigned to Google **and** updated, not just reassigned.

**Comment by PeterShaggyNoble** [comment]
Google always called our `folder-outline` icon `folder_open`. If we are going to rename it, though, we'll need to give our `folder-open` the `variant` modifier.

**Comment by PeterShaggyNoble** [comment]
List of icons in the new set that were not previously included in the original or extended sets:

- `all_inbox`
- `battery_20`
- `battery_30`
- `battery_50`
- `battery_60`
- `battery_80`
- `battery_90`
- `battery_charging_20`
- `battery_charging_30`
- `battery_charging_50`
- `battery_charging_60`
- `battery_charging_80`
- `battery_charging_90`
- `bookmarks`
- `cast_for_education`
- `desktop_access_disabled`
- `duo`
- `explore_off`
- `label_off`
- `person_add_disabled`
- `print_disabled`
- `signal_cellular_0_bar`
- `signal_cellular_1_bar`
- `signal_cellular_2_bar`
- `signal_cellular_3_bar`
- `signal_cellular_connected_no_internet_0_bar`
- `signal_cellular_connected_no_internet_1_bar`
- `signal_cellular_connected_no_internet_2_bar`
- `signal_cellular_connected_no_internet_3_bar`
- `signal_wifi_0_bar`
- `signal_wifi_1_bar`
- `signal_wifi_1_bar_lock`
- `signal_wifi_2_bar`
- `signal_wifi_2_bar_lock`
- `signal_wifi_3_bar`
- `signal_wifi_3_bar_lock`
- `star_rate`
- `toggle_off`
- `toggle_on`
- `twotone`

(I'll come back to this later and mark off the ones we already have)

**Comment by Ch-Lo** [comment]
Did not found the "delete circle outline" on the lists above, which has already an issue here #2309

**Comment by PeterShaggyNoble** [comment]
@Ch-Lo, that's because `delete-circle` isn't a stock Google icon, which is what we're tracking here.

**Comment by goyney** [comment]
This thread is very complex and I'm working on cleaning it up. I'm locking it so new information cannot be added to it. If there is a Google Stock Icon we're missing or we have but is out-of-date, please create a new issue, one per icon. Thank you!
