### ISSUE TITLE
cellphone-off

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#3164]
as topic.
please add cellphone-off

we have cellphone-erase (which is something else) and cellphone-link-off, but no cellphone-off.

in use case here, would be very clear when none of the phones in the household is 'home', and situations for individual phones being offline.

cheers,
Marius

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/39821339-3fc516f6-5365-11e8-83ba-177215b7c35e.png)

[cellphone-off.zip](https://github.com/Templarian/MaterialDesign/files/1988256/cellphone-off.zip)

**Comment by PeterShaggyNoble** [comment]
Google have a `mobile off` icon in the Extended set, which was also added to the stock set with yesterday's update:

[![mobile off](http://mdi.houseofdesign.ie/tools/preview/?icon=mobile-off&action=open-in-new)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by hvbhome** [comment]
Thanks!
Too bad it isnt an iPhone,
 but you wont hear me nitpicking;-)
Cool. So fast .
Cheers

**Comment by Templarian** [comment]
[![cellphone-off](https://materialdesignicons.com/icon/cellphone-off)](https://materialdesignicons.com/icon/cellphone-off)
