### ISSUE TITLE
Court hammer

### ISSUE THREAD

**Issue by adendiamond** [Templarian/MaterialDesign#3165]

**Comment by CoDEmanX** [comment]
It's called gavel: https://materialdesignicons.com/icon/gavel

We have a custom icon, but Google has one too:
https://material.io/tools/icons/?search=gavel&icon=gavel&style=baseline

Ours could be renamed to `gavel-variant` and the stock one added.

**Comment by adendiamond** [comment]
Thanks very much

**Comment by Templarian** [comment]
Not really a fan of the stock design. They might have over-minimal'ized it maybe?

Added the alias `court-hammer`.

**Comment by GreenTurtwig** [comment]
I actually prefer the stock design, it's simple but you can still tell what it is. eBay uses it in their Android app and I always thought it fit in nicely with the other icons in the menu. 🐈
