### ISSUE TITLE
fan-variant

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3166]
We should get the stock icon `toys` added as a variant to `fan` as it's the icon Google use to represent fans in Assistant.

![](https://user-images.githubusercontent.com/15905797/39867912-1f32b142-544f-11e8-848c-c1777cdf7806.png)

**Comment by Templarian** [comment]
I think we had a design like this, but went with a more literal design in the end. Not against just adding it `fan-variant`.

Not really sure if it's needed though?

**Comment by PeterShaggyNoble** [comment]
Given that Google call it `toys`, I think it's supposed to be a pinwheel.

**Comment by CoDEmanX** [comment]
Isn't it also called whirligig?

**Comment by PeterShaggyNoble** [comment]
Added in #3395.
