### ISSUE TITLE
General Device

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3167]
Google use this icon from their Extended icon set in home automation to represent devices they don't have a specific icon for, might be handy to be able to point people to it while they wait for their request to be fulfilled or if they request an overly niche device that we don't have a good alternative for.

[![general device](http://mdi.houseofdesign.ie/tools/preview/?icon=general-device&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by Templarian** [comment]
That's a very vague looking icon. I think we should just work to keep adding specific icons. I'm sure it would be better to use another icon that is close than this.

**Comment by Templarian** [comment]
I'm going to close this issue as too generic. Thought about it for a while and it's just too generic visually (even for the use or representing a "device").
