### ISSUE TITLE
cabinet, pantry, storage, provisions...

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3169]
icon request for a representation of the topic.
Couldn't find any of the above so please consider creating an icon for at least a cupboard, or cabinet.

variants with books, and plates etc come to mind

not sure if i should file requests for all of the above or not,

cheers,
Marius

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/40079807-f3aaf62a-5880-11e8-9856-2dddf825658b.png)![](https://user-images.githubusercontent.com/15905797/40079834-061709c0-5881-11e8-826c-5c8eb2ddc9c8.png)![](https://user-images.githubusercontent.com/15905797/40079851-14e4beb6-5881-11e8-9cbd-a42369eb6144.png)![](https://user-images.githubusercontent.com/15905797/40079869-226812a4-5881-11e8-9c14-cab3ac6fcb84.png)
[cupboard.zip](https://github.com/Templarian/MaterialDesign/files/2006459/cupboard.zip)

@Templarian will likely rename them to `closet`.

**Comment by Templarian** [comment]
Closets are usually built into the wall. This would be a wardrobe. 😏

**Comment by GreenTurtwig** [comment]
Still trying to understand what you guys call stuff. :smile_cat:

**Comment by hvbhome** [comment]
Nice!
Maybe make an open cabinet with shelves?

**Comment by hvbhome** [comment]
using the mdi:window-open now which with a little bit of imagination can be seen as a cabinet without doors, and some items on the shelves ;-)

just saying small adjustments could be enough to make a 'real' cabinet. Or 'Vitrine' (open cabinet with glass shelves/doors....

maybe only the 2 little feet would be enough?

Have the same for a book-cabinet with some books filled shelves and we're done!
Cheers,
Marius

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/40281782-6da0484c-5c5d-11e8-88bb-ae1a85aef9ca.png)![](https://user-images.githubusercontent.com/15905797/40281789-77b212f2-5c5d-11e8-8e22-4ced6a8030d6.png)![](https://user-images.githubusercontent.com/15905797/40281791-829766b8-5c5d-11e8-8162-bb696f71b301.png)![](https://user-images.githubusercontent.com/15905797/40281796-91b478de-5c5d-11e8-95ba-bd218e8b880a.png)
[cupboard.zip](https://github.com/Templarian/MaterialDesign/files/2020516/cupboard.zip)

**Comment by goyney** [comment]
[![wardrobe](https://materialdesignicons.com/icon/wardrobe)](https://materialdesignicons.com/icon/wardrobe)[![wardrobe-outline](https://materialdesignicons.com/icon/wardrobe-outline)](https://materialdesignicons.com/icon/wardrobe-outline)
[![cupboard](https://materialdesignicons.com/icon/cupboard)](https://materialdesignicons.com/icon/cupboard)[![cupboard-outline](https://materialdesignicons.com/icon/cupboard-outline)](https://materialdesignicons.com/icon/cupboard-outline)

**Comment by CoDEmanX** [comment]
The 2px gap between the wardrobe halves make it look really disconnected. Should there be a continuous outline?

![grafik](https://user-images.githubusercontent.com/1309249/61850092-ac068c00-aeb3-11e9-991d-fa73fdb76b3a.png)

The dresser only has a single pixel gap, but here is a variation with a full outline:

**Comment by goyney** [comment]
@CoDEmanX You've actually started the trend without the border with `fridge`. There's also a few Google made icons without the border as well. I think if we change anything, we should make the gap on the wardrobe 1dp instead of 2dp, but I think I prefer the look without the border. If we want to use the border, then I think we need to locate and update icons, such as `fridge` to match.

**Comment by CoDEmanX** [comment]
Well... 🙃The wardrobe and dresser apply it to the longer side though. I guess that makes it stand out a lot more. Maybe it's enough to reduce the gap to 1dp in such cases?
