### ISSUE TITLE
Percent, Margin and Transfer Icons

### ISSUE THREAD

**Issue by iang0ld** [Templarian/MaterialDesign#317]
Have a look at the image.

![icons-ideas](https://cloud.githubusercontent.com/assets/8695534/7343332/b5f19776-ed03-11e4-913d-1b7c3d2a958f.jpg)

- [ ] transfer
- [ ] percent-margin

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/margin
http://materialdesignicons.com/icon/transfer
