### ISSUE TITLE
Node-RED Icon

### ISSUE THREAD

**Issue by james-fry** [Templarian/MaterialDesign#3170]
[Node-red](https://nodered.org/) is a "Flow-based programming for the Internet of Things" that is starting to be used a lot in home automation - e.g with home assistant.
A node-red icon would be useful to the HA community.

Sample Icon:
![node-red](https://user-images.githubusercontent.com/5823294/39971211-73e3e29a-56ef-11e8-84a3-9ab952314475.png)

**Comment by maltaisn** [comment]
[![image](https://user-images.githubusercontent.com/33690959/39972500-617cca64-56df-11e8-80e4-c2df6b0b7a2a.png)](https://github.com/Templarian/MaterialDesign/files/1999000/icon.zip)

**Comment by Croutonix** [comment]
[![image](https://user-images.githubusercontent.com/33690959/39972500-617cca64-56df-11e8-80e4-c2df6b0b7a2a.png)](https://github.com/Templarian/MaterialDesign/files/1999000/icon.zip)

**Comment by james-fry** [comment]
Looks great!
Thanks!

**Comment by Reflectin88** [comment]
Any idea when this will be available ?

**Comment by james-fry** [comment]
@goyney please can you let us know approx when 3.7 will drop? Thanks!

**Comment by redskinhu** [comment]
I'm looking forward to it.

**Comment by james-fry** [comment]
It would be great to see this in MDI soon... This is becoming a standard platform for home automation.

**Comment by goyney** [comment]
We're actually starting to move away from adding brand icons to MDI. I don't think this icon is likely to be added. We're recommending people start to utilize [SimpleIcons ](https://simpleicons.org/)for their brand icons needs since that is a library dedicated to brand icons. I'd recommend opening a request over there.

**Comment by redskinhu** [comment]
Hello

The problem is: Home Assistant supports only MDI icons.

Thx
T

**Comment by james-fry** [comment]
This is indeed a problem. Home assistant is a prolific user of MDI and there are people who contribute to both projects. If you look at the tags you can see that home automation is the 2nd largest tag set (by a considerable margin) after... logos :)

**Comment by goyney** [comment]
[Our intentions have already been made clear to the Home Assistant project](https://community.home-assistant.io/t/material-design-icons-simpleicons-add-support-for-simpleicons-library/108765) about our future with brand icons and it is to our understanding that they have already begun steps to support SimpleIcons, in addition to MDI. When that will be available is up to them.

We plan on making a more official announcement about our future with brand icons soon, so look out for that. But I can say that as MDI continues to rapidly grow, brand icons really do not fit the mission of MDI to provide _Material_ icons. SimpleIcons' only focus is brand icons, so using them for that purpose really makes sense.

**Comment by james-fry** [comment]
Thanks for taking the time to explain. I raised a feature request on the forum.

https://community.home-assistant.io/t/support-simpleicons/111554

**Comment by redskinhu** [comment]
Thanks.

**Comment by james-fry** [comment]
haha @redskinhu you beat me to it to request the nodered icon over at simpleicons ;)

**Comment by redskinhu** [comment]
My HA menu looks like an edentulous child without the Node-RED icon....
![Screenshot_20190416-110421_Chrome Canary](https://user-images.githubusercontent.com/34792633/56217318-ef529280-605a-11e9-8f7c-ffa40922f68b.jpg)
I waiting for it long time ago.

And I need to request ESPHome and Cloud9 icons too. But I'll wait until the Simpleicons implemented to the HA.

**Comment by james-fry** [comment]
There are a few usable MDI icons (barely though) - I use vector-polyline but I dont love it.
I think that HA should also make it easier to use a custom SVG icon - I dont see ESPhome being at the top of anyones list to add to an iconset as its very niche + I am pretty sure the icon wont meet MDI design criteria.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
