### ISSUE TITLE
Subtitle 

### ISSUE THREAD

**Issue by MARGELANI** [Templarian/MaterialDesign#3171]
Icon for Movie/TV Show **Subtitles**, and **BluRay**.

**Comment by GreenTurtwig** [comment]
https://material.io/tools/icons/?search=sub&icon=subtitles&style=baseline

We should get the stock subtitles icon added (including the outlined version).

**Comment by Templarian** [comment]
[![subtitles](https://materialdesignicons.com/icon/subtitles)](https://materialdesignicons.com/icon/subtitles) [![subtitles-outline](https://materialdesignicons.com/icon/subtitles-outline)](https://materialdesignicons.com/icon/subtitles-outline)
