### ISSUE TITLE
system-update

### ISSUE THREAD

**Issue by peddersen** [Templarian/MaterialDesign#3172]
Seems like the original Material icon [`system_update`](https://material.io/tools/icons/?search=system_update&icon=system_update&style=baseline) is missing. 
![baseline_system_update_black_18dp](https://user-images.githubusercontent.com/6444714/39983784-347083e2-5759-11e8-853e-1d1a9b818856.png)

**Comment by Templarian** [comment]
[![cellphone-arrow-down](https://materialdesignicons.com/icon/cellphone-arrow-down)](https://materialdesignicons.com/icon/cellphone-arrow-down)
