### ISSUE TITLE
cellphone-information

### ISSUE THREAD

**Issue by peddersen** [Templarian/MaterialDesign#3173]
Seems like this original Material icon is missing here? 
![baseline_perm_device_information_black_48dp](https://user-images.githubusercontent.com/6444714/39983973-db832810-5759-11e8-9368-35a2cab8c2cc.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61244310-e9328780-a717-11e9-8778-4156bd3ea9a3.png)
[cellphone-information.svg.zip](https://github.com/Templarian/MaterialDesign/files/3393946/cellphone-information.svg.zip)

**Comment by goyney** [comment]
Added!
[![cellphone-information](https://materialdesignicons.com/icon/cellphone-information)](https://materialdesignicons.com/icon/cellphone-information)
