### ISSUE TITLE
Authy

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#3175]
![image](https://user-images.githubusercontent.com/18021678/40027767-82e75bae-57a9-11e8-8dc1-a102e00c0180.png)
![image](https://user-images.githubusercontent.com/18021678/40027779-9c9eed46-57a9-11e8-9279-3a056aaa6bb8.png)

**Comment by PeterShaggyNoble** [comment]
I'm going to reject this as it doesn't currently meet our criteria for inclusion as it's not a well-known social media brand nor a massively popular software brand. We may revisit this issue, though, if a dedicated brand icon set gets released.

See #3183 for a generic 2FA icon.
