### ISSUE TITLE
Wallet with plus

### ISSUE THREAD

**Issue by sukhvi** [Templarian/MaterialDesign#3176]

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/40069624-cdacab98-5863-11e8-9698-9ca126cc30b3.png)![](https://user-images.githubusercontent.com/15905797/40069659-e273d902-5863-11e8-84ba-476f5fec0cc2.png)
[wallet-plus.zip](https://github.com/Templarian/MaterialDesign/files/2005782/wallet-plus.zip)

**Comment by goyney** [comment]
[![wallet-plus](https://materialdesignicons.com/icon/wallet-plus)](https://materialdesignicons.com/icon/wallet-plus)[![wallet-plus-outline](https://materialdesignicons.com/icon/wallet-plus-outline)](https://materialdesignicons.com/icon/wallet-plus-outline)
