### ISSUE TITLE
comment-plus

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3177]
We have `comment-plus-outline` but not `comment-plus`.

[![comment-plus](http://mdi.houseofdesign.ie/tools/preview/?name=comment-plus&action=download&path=M9,22A1,1%200%200,1%208,21V18H4A2,2%200%200,1%202,16V4C2,2.89%202.9,2%204,2H20A2,2%200%200,1%2022,4V16A2,2%200%200,1%2020,18H13.9L10.2,21.71C10,21.9%209.75,22%209.5,22V22H9ZM11,6V9H8V11H11V14H13V11H16V9H13V6H11Z)](https://github.com/Templarian/MaterialDesign/files/2004503/comment-plus.zip)

**Comment by MrGrigri** [comment]
Here you go.

![image](https://user-images.githubusercontent.com/4528551/40074263-66682a0c-5836-11e8-8a8e-b533bd936700.png)

[comment-plus.zip](https://github.com/Templarian/MaterialDesign/files/2006106/comment-plus.zip)

**Comment by Templarian** [comment]
[![comment-plus](https://materialdesignicons.com/icon/comment-plus)](https://materialdesignicons.com/icon/comment-plus)
