### ISSUE TITLE
WebMoney

### ISSUE THREAD

**Issue by Yanovsky** [Templarian/MaterialDesign#3178]
Icons are required for web payment providers. Such as WebMoney, PayPal, KIWI, Yandex, Sendy Pay, AliPay

**Comment by PeterShaggyNoble** [comment]
- `paypal` already exists
- `yandex` is a duplicate of #1405

The rest are probably too obscure for inclusion at this time.

**Comment by goyney** [comment]
Going to close this issue. If there are specific pay providers you'd like to see added, please create a separate issue for each one. Thanks!
