### ISSUE TITLE
Patio Heater Icon

### ISSUE THREAD

**Issue by gabglus** [Templarian/MaterialDesign#3180]
Hi,

It will be nice add a Patio Heater icon

![image](https://user-images.githubusercontent.com/19849374/40065538-ac308c1e-5827-11e8-8357-938b9003366a.png)

**Comment by goyney** [comment]
It seems like there is a lot of detail required to really indicate what this is at 24x24. Here's two attempts to consider:

![image](https://user-images.githubusercontent.com/1015040/45642438-28576400-ba86-11e8-9baa-b245e791b240.png)![image](https://user-images.githubusercontent.com/1015040/45642445-32796280-ba86-11e8-9669-b4bc1554a80c.png)

[patio-heaters.zip](https://github.com/Templarian/MaterialDesign/files/2389773/patio-heaters.zip)

**Comment by CoDEmanX** [comment]
👍 for variant 2. Variant 1 looks more like a fancy street lamp.

**Comment by goyney** [comment]
[![patio-heater](https://materialdesignicons.com/icon/patio-heater)](https://materialdesignicons.com/icon/patio-heater)
