### ISSUE TITLE
Air Heater

### ISSUE THREAD

**Issue by gabglus** [Templarian/MaterialDesign#3181]
Hi, 

It will be nice add  an Air Heater icon

![image](https://user-images.githubusercontent.com/19849374/40065588-bfc68ab2-5827-11e8-8e2f-b5d076bd575e.png)

**Comment by goyney** [comment]
I think `radiator` already hits this one.

Most space heaters look either like fans or radiators. Some kind of look like speakers with a grill across the font, but that doesn't really translate to Material design.

[![image](https://user-images.githubusercontent.com/1015040/45642856-8c2e5c80-ba87-11e8-8e7d-eeef68a5d4de.png)](https://materialdesignicons.com/icon/radiator)

**Comment by PeterShaggyNoble** [comment]
Google's `air-purifier` icon could probably also pass for a heater.

![](http://mdi.houseofdesign.ie/tools/preview/?icon=air-purifier)

**Comment by goyney** [comment]
Adding a reminder to alias this with `heater` when it is added.

**Comment by Templarian** [comment]
@PeterShaggyNoble Where did you see an `air-purifier` icon?

**Comment by PeterShaggyNoble** [comment]
@Templarian, it's in their extended icon set: https://petershaggynoble.github.io/MDI-Sandbox/extended/

![air_purifier](https://user-images.githubusercontent.com/15157491/51476835-98506080-1d7e-11e9-9e25-ce2dc297f805.png)

**Comment by Templarian** [comment]
[![air-purifier](https://materialdesignicons.com/icon/air-purifier)](https://materialdesignicons.com/icon/air-purifier)
