### ISSUE TITLE
Update and reassign `current-dc`

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3182]
An icon for DC current already exists in the stock set named `power_input`. We should update and reassign the `current-dc` icon to match Google's.

![](https://user-images.githubusercontent.com/15905797/40068506-ba337950-5860-11e8-8651-2a258da99abd.png)

**Comment by Croutonix** [comment]
It's not centered though, I would make the center dash wider.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53063191-5146af80-3491-11e9-994a-112995ac45b8.png)
Our current is outline.

[current-dc.svg.zip](https://github.com/Templarian/MaterialDesign/files/2882843/current-dc.svg.zip)

**Comment by Templarian** [comment]
Updated. I'm just going to keep it assigned since it's still not really stock.
