### ISSUE TITLE
Two Factor Authentication (2FA)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3183]
We could do with a generic icon to represent 2-factor authentication.

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/40073720-93dc782e-586f-11e8-8a82-cab2e72c236e.png)![](https://user-images.githubusercontent.com/15905797/40073748-a0086860-586f-11e8-9aec-b9371489f595.png)![](https://user-images.githubusercontent.com/15905797/40073764-aca4b916-586f-11e8-8cd8-47741ee192f4.png)![](https://user-images.githubusercontent.com/15905797/40073772-b99da59c-586f-11e8-9dde-22df4d9d336b.png)
[2fa.zip](https://github.com/Templarian/MaterialDesign/files/2006074/2fa.zip)


Me and @PeterShaggyNoble had a few ideas, but we're not totally sure.

**Comment by GreenTurtwig** [comment]
That's what I was thinking too. In a settings screen it should be obvious what it represents, assuming the user knows what 2FA is of course. :cat2:

**Comment by PeterShaggyNoble** [comment]
`lock-2` (with a few aliases) gets my vote, too but, like @MrGrigri, I think `cellphone-key` would be good to have as well.

Another option for those looking for a solution in the meantime could be the existing `security-lock` icon.

**Comment by Templarian** [comment]
[![two-factor-authentication](https://materialdesignicons.com/icon/two-factor-authentication)](https://materialdesignicons.com/icon/two-factor-authentication) [![cellphone-key](https://materialdesignicons.com/icon/cellphone-key)](https://materialdesignicons.com/icon/cellphone-key)

**Comment by dennisvanlith** [comment]
Shouldn't there be a difference but also a similarity icon between 2fa by **sms** (text message) or 2fa by **Authentication App**, (like Unloq or Google Authenticator)

**Comment by dennisvanlith** [comment]
In the near future you could also have 2FA by fingerprint, irisscan. Also consider MFA versions. Multiple Factor Authentication.
