### ISSUE TITLE
video-input-scart

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3185]
[![](https://user-images.githubusercontent.com/15905797/40110254-7026b92a-58f7-11e8-8500-4e2d747c2750.png)](https://github.com/Templarian/MaterialDesign/files/2008538/video-input-scart.zip)

**Comment by MrGrigri** [comment]
Since this is a legacy port and only used in Europe, I don't think this should be added.

**Comment by GreenTurtwig** [comment]
It may be outdated with lots of modern devices using HDMI, but SCART is very much still used here. In Japan the connector is known as JP-21, although with a different pinout. Besides, we already have icons for both S-Video and composite/component.

**Comment by GreenTurtwig** [comment]
Originally it had a cable coming out, that was way better. Unfortunately we have size limitations so I just went without like the HDMI icon does.

**Comment by CoDEmanX** [comment]
It's a bit better with 2px border, but I would still not use it at native size.

![scart](https://user-images.githubusercontent.com/1309249/40130634-eee507fe-5937-11e8-893e-ab91c82b345e.png)

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/40175199-4f2cd5fa-59cf-11e8-93cb-d60b7a66564e.png)

---
![](https://user-images.githubusercontent.com/15905797/40175122-12b1b5dc-59cf-11e8-9dec-594791881f54.png)![](https://user-images.githubusercontent.com/15905797/40175152-22ae70ec-59cf-11e8-8e29-4614c7ee4610.png)

---
![](https://user-images.githubusercontent.com/15905797/40175313-9b00c7de-59cf-11e8-95f4-4fdf21edecb8.png)![](https://user-images.githubusercontent.com/15905797/40175348-b7e0dbe6-59cf-11e8-95e0-e6e18b87cc65.png)![](https://user-images.githubusercontent.com/15905797/40175390-d6d36604-59cf-11e8-8e87-cbbc04545ddf.png)

---
![](https://user-images.githubusercontent.com/15905797/40175403-e691bbc2-59cf-11e8-8d5b-755d885318bf.png)![](https://user-images.githubusercontent.com/15905797/40175433-fe5282a0-59cf-11e8-84d8-61a92e80065b.png)![](https://user-images.githubusercontent.com/15905797/40175453-0fafeee8-59d0-11e8-8cd7-d0330c7aa1ec.png)

---
![](https://user-images.githubusercontent.com/15905797/40175486-28453bde-59d0-11e8-8bad-5ef05de29ebe.png)![](https://user-images.githubusercontent.com/15905797/40175512-419b9006-59d0-11e8-8bbe-61dbf3e4d726.png)![](https://user-images.githubusercontent.com/15905797/40175536-523e3652-59d0-11e8-910e-efa54245e704.png)

**Comment by GreenTurtwig** [comment]
The connector could work if we managed to make it smaller. I tried making it smaller and adding the cable, but it made it look even stranger.

Personally I prefer:
![image](https://user-images.githubusercontent.com/15905797/40175621-a5902a68-59d0-11e8-97e7-871bf1fd867a.png)

**Comment by CoDEmanX** [comment]
I prefer this one at large scale:

![](https://user-images.githubusercontent.com/15905797/40175199-4f2cd5fa-59cf-11e8-93cb-d60b7a66564e.png)

but it doesn't work in small. Therefore my vote also goes to

![image](https://user-images.githubusercontent.com/15905797/40175621-a5902a68-59d0-11e8-97e7-871bf1fd867a.png)

**Comment by goyney** [comment]
@GreenTurtwig Can you share your SVG of the winner so it can be added? 😄

**Comment by GreenTurtwig** [comment]
[video-input-scart3.zip](https://github.com/Templarian/MaterialDesign/files/3423895/video-input-scart3.zip)
Hopefully that's the right file, over a year old.

**Comment by goyney** [comment]
[![video-input-scart](https://materialdesignicons.com/icon/video-input-scart)](https://materialdesignicons.com/icon/video-input-scart)
