### ISSUE TITLE
Window variant

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3189]
![](https://user-images.githubusercontent.com/15905797/40283319-43333530-5c74-11e8-9615-d13f64d23bc5.png)![](https://user-images.githubusercontent.com/15905797/40283326-54de234e-5c74-11e8-9a48-99613ff112ad.png)![](https://user-images.githubusercontent.com/15905797/40283413-a604a2ec-5c75-11e8-936a-2e81395f9105.png)

---
![](https://user-images.githubusercontent.com/15905797/40283338-796ff908-5c74-11e8-8404-72396013782a.png)![](https://user-images.githubusercontent.com/15905797/40283351-b117dd9e-5c74-11e8-84ff-43a39ff33093.png)![](https://user-images.githubusercontent.com/15905797/40283355-bfa0eaae-5c74-11e8-9e4b-8711086ee461.png)
![](https://user-images.githubusercontent.com/15905797/40283360-cc751624-5c74-11e8-8ea9-a0e960e3615b.png)![](https://user-images.githubusercontent.com/15905797/40283369-dab4fab0-5c74-11e8-977c-52092ad633ed.png)
[windows.zip](https://github.com/Templarian/MaterialDesign/files/2020682/windows.zip)

**Comment by MrGrigri** [comment]
Idk about the vast amounts of perspective.

**Comment by DocCoding** [comment]
I believe all open variants vilate the material [design icon guidelines](https://material.io/design/iconography/system-icons.html#system-icon-metrics). They state to not "tilt, rotate, or make icons appear dimensional."

**Comment by Templarian** [comment]
Yea, I've been very hesitant to add these since they do break that guideline.

**Comment by GreenTurtwig** [comment]
It's very difficult to do without adding perspective. Making the outward opened windows flat would not only look odd but also mean that the window frame itself would have to be made smaller to accommodate which would look silly on the closed design.
Also keep in mind that Google go against their own guidelines all the time, for example with `book-open-page-variant`.

**Comment by goyney** [comment]
Way too much rule breaking in this thread. Going to close it for now.
