### ISSUE TITLE
wrench icon

### ISSUE THREAD

**Issue by shiftmore** [Templarian/MaterialDesign#319]
something like this would be great:
http://fortawesome.github.io/Font-Awesome/icon/wrench/

- [ ] wrench

**Comment by CoDEmanX** [comment]
There's an official wrench, `ic_build`, yet to be added to MDI:
![build](https://raw.githubusercontent.com/google/material-design-icons/master/action/drawable-xxxhdpi/ic_build_black_24dp.png)

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/wrench
