### ISSUE TITLE
Foodcost Icon

### ISSUE THREAD

**Issue by xbandx68** [Templarian/MaterialDesign#3190]
[foodcost.zip](https://github.com/Templarian/MaterialDesign/files/2023799/foodcost.zip)

**Comment by MrGrigri** [comment]
At 1x, it looks like steam on top of the burger.

**Comment by PeterShaggyNoble** [comment]
What purpose would this icon serve? `receipt` should do the job to represent a bill.

![receipt](https://user-images.githubusercontent.com/15157491/40550726-dcde0d7e-6032-11e8-910c-ffefbb2d2207.png)

**Comment by goyney** [comment]
Preview of the icon contributed by @xbandx68:
![image](https://user-images.githubusercontent.com/1015040/41946988-feebd9be-7982-11e8-86bf-9f75acf4af11.png)

**Comment by MrGrigri** [comment]
I still feel that at 1x it looks like a steaming burger. Plus food-cost is typically represented with just dollar signs.

**Comment by goyney** [comment]
The provided contribution is way to busy to convey the cost of food at 1x size. We recommend using the `receipt` icon or one of the `currency-*` icons in combination with `hamburger`, etc. If you have other ideas, please feel free to create a new issue.
