### ISSUE TITLE
Toggle buttons

### ISSUE THREAD

**Issue by jmlusiardo** [Templarian/MaterialDesign#3191]
toggle_on and toggle_off icons have changed it's style.

https://material.io/tools/icons/?icon=toggle_off&style=baseline

Of you want check also the rest, mabye there are other changes.

**Comment by Templarian** [comment]
[![toggle-switch](https://materialdesignicons.com/icon/toggle-switch)](https://materialdesignicons.com/icon/toggle-switch) [![toggle-switch-outline](https://materialdesignicons.com/icon/toggle-switch-outline)](https://materialdesignicons.com/icon/toggle-switch-outline) [![toggle-switch-off](https://materialdesignicons.com/icon/toggle-switch-off)](https://materialdesignicons.com/icon/toggle-switch-off) [![toggle-switch-off-outline](https://materialdesignicons.com/icon/toggle-switch-off-outline)](https://materialdesignicons.com/icon/toggle-switch-off-outline)
