### ISSUE TITLE
Update on current official material icons

### ISSUE THREAD

**Issue by jmlusiardo** [Templarian/MaterialDesign#3192]
Some icons changed on this new release of Material Design (for example, toggle_on and toggle_off icons).

It would be nice to have the actual official MD iconography. This can be done easily?

**Comment by JamesCoyle** [comment]
See #3163.

**Comment by Templarian** [comment]
@jmlusiardo `v2.4.85` just went out. This does not include all the updates. Hopefully we'll get most of this resolved in the next release for those needing some of the newly added icons.

**Comment by PeterShaggyNoble** [comment]
In the meantime, @jmlusiardo, if there are any specific icons you would like to see added, please open an individual issue for each one.
