### ISSUE TITLE
license link wrong

### ISSUE THREAD

**Issue by tooomm** [Templarian/MaterialDesign#3193]
After https://github.com/Templarian/MaterialDesign/commit/4456d09a1dd147033fc5ba820c773c6c587a9c68 the link on the webpage hasn't been updated.

If you click on the `Download` button the upcoming layover still links to the old license file on the lower right:
![untitled](https://user-images.githubusercontent.com/9874850/40410888-2735493e-5e6f-11e8-9b20-e3dcd588ae31.png)

**Comment by Templarian** [comment]
Fixed. Thanks for the heads up!
