### ISSUE TITLE
keyboard-shortcut

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3194]
Idk how we could accomplish this, but it would be nice to have a single icon to represent keyboard shortcuts.

**Comment by JapanYoshi** [comment]
Would a cloverleaf Command key/icon be too Apple-specific?

**Comment by JapanYoshi** [comment]
![shortcut-key-1](https://user-images.githubusercontent.com/8707990/40572697-138f3d70-60f6-11e8-9dca-1c76f10d4d6b.png)
![shortcut-key-2](https://user-images.githubusercontent.com/8707990/40572698-13c0ad1a-60f6-11e8-9d3d-ec2464535867.png)
![shortcut-key-10](https://user-images.githubusercontent.com/8707990/40572699-1451e816-60f6-11e8-97de-b7e344c80683.png)
![shortcut-key-outline](https://user-images.githubusercontent.com/8707990/40572700-1483b1d4-60f6-11e8-8d69-a5d42bf59a57.png)
![shortcut-key-outline-2](https://user-images.githubusercontent.com/8707990/40572701-152fdd74-60f6-11e8-8db8-e3ecdeeec96f.png)
![shortcut-key-outline-10](https://user-images.githubusercontent.com/8707990/40572702-159804e4-60f6-11e8-8cae-072f30d6f9d7.png)

**Comment by Templarian** [comment]
That's more of a key than a shortcut and is only in one OS. Not sure what icon it would be other than maybe the keyboard.

**Comment by MrGrigri** [comment]
What about a `keyboard-settings` icon.

![image](https://user-images.githubusercontent.com/4528551/40994804-82647f64-68ba-11e8-8724-408df8e732e4.png) ![image](https://user-images.githubusercontent.com/4528551/40994767-63166bfe-68ba-11e8-8ab0-de3a8411acef.png)

[keyboard-settings.zip](https://github.com/Templarian/MaterialDesign/files/2073512/keyboard-settings.zip)

**Comment by PeterShaggyNoble** [comment]
An example of an instance where [`settings-helper`](https://github.com/Templarian/MaterialDesign/issues/3064) might be handy 😉

**Comment by Templarian** [comment]
@PeterShaggyNoble Good idea, but I like the idea of including `-settings` as a dedicated modifier.

**Comment by Templarian** [comment]
[![keyboard-settings](https://materialdesignicons.com/icon/keyboard-settings)](https://materialdesignicons.com/icon/keyboard-settings) [![keyboard-settings-outline](https://materialdesignicons.com/icon/keyboard-settings-outline)](https://materialdesignicons.com/icon/keyboard-settings-outline)
