### ISSUE TITLE
Mark as unread (Gmail)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3195]
[mark_as_unread.zip](https://github.com/Templarian/MaterialDesign/files/2032513/mark_as_unread.zip)

![grafik](https://user-images.githubusercontent.com/1309249/40446359-3b9d58c0-5ecf-11e8-8664-6eb237bd5ba1.png)

Recreated from a PNG. Pixel coverage is not 100% identical, but pretty close. The different might originate from using different rasterizers actually...

![mark_as_unread_black_48dp](https://user-images.githubusercontent.com/1309249/40446220-c80e1e12-5ece-11e8-978e-3197d61b8bb1.gif)

**Comment by PeterShaggyNoble** [comment]
This was recently added to Material Icons Extended:

[![mark-as-unread](http://mdi.houseofdesign.ie/tools/preview/?icon=mark-as-unread&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by Templarian** [comment]
[![email-mark-as-unread](https://materialdesignicons.com/icon/email-mark-as-unread)](https://materialdesignicons.com/icon/email-mark-as-unread)
