### ISSUE TITLE
PowerShell

### ISSUE THREAD

**Issue by brhinescot** [Templarian/MaterialDesign#3196]
PowerShell icon to go with the other code icons.

**Comment by GreenTurtwig** [comment]
Would these not do?
[![](https://materialdesignicons.com/icon/console)](https://materialdesignicons.com/icon/console)[![](https://materialdesignicons.com/icon/console-line)](https://materialdesignicons.com/icon/console-line)

**Comment by CoDEmanX** [comment]
Their actual logo looks pretty much like our console icons:

https://github.com/PowerShell/PowerShell/blob/master/assets/Powershell_256.png

**Comment by Templarian** [comment]
[![powershell](https://materialdesignicons.com/icon/powershell)](https://materialdesignicons.com/icon/powershell)
