### ISSUE TITLE
Update and reassign thermometer to Google

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3197]
![](https://user-images.githubusercontent.com/15905797/40485425-60f8b48e-5f56-11e8-92f9-6038cb3e3194.png)

Personally I prefer Google's design without the lines.
![](https://user-images.githubusercontent.com/15905797/40485527-ac307086-5f56-11e8-9118-7731b0f80329.png)![](https://user-images.githubusercontent.com/15905797/40485472-8b5b2b58-5f56-11e8-8626-75db82421a86.png)![](https://user-images.githubusercontent.com/15905797/40485497-96f5178a-5f56-11e8-8eca-32e45d6edc75.png)
[thermometer.zip](https://github.com/Templarian/MaterialDesign/files/2035296/thermometer.zip)

**Comment by CoDEmanX** [comment]
Without lines it could also be some kind of lever viewed from the front, but it should work without in context.

**Comment by goyney** [comment]
This will be addressed in #3291.
