### ISSUE TITLE
Consent (GDPR)

### ISSUE THREAD

**Issue by dennisvanlith** [Templarian/MaterialDesign#3199]
As for today May 25th. There is a new legislation in town called the European GDPR. In this legislation there's a lot to do with consent and I was looking for an icon that would differentiate a consen between likes, agree or simple checkmarks. Nothing comes close. Any ideas from a creative mind?

**Comment by PeterShaggyNoble** [comment]
In the interests of ease of recognition clarity, I would highly recommend using a `checkbox` icon with an appropriate label or, if you need to offer the options to accept or decline, then a `check` or `close` icon, again with appropriate labels.

**Comment by MrGrigri** [comment]
I would actually just use their logo. I don't believe that there is any reason for us to create a very niche icon when you could just youse theirs.

**Comment by Templarian** [comment]
After the 30+ emails looks like all of this should be resolved shortly. I'm not sure we need a specific icon outside of the regular checkbox or various security icons.
