### ISSUE TITLE
Azure DevOps

### ISSUE THREAD

**Issue by ryanwinter** [Templarian/MaterialDesign#3201]
Visual Studio Team Services
https://www.visualstudio.com/team-services/

**Comment by goyney** [comment]
This service has been renamed "Azure DevOps" and this is the logo for it:

![image](https://user-images.githubusercontent.com/1015040/58255821-d5802b80-7d3b-11e9-9c33-73cb089569a0.png)

Considering this is a development tool, it meets the criteria to still be added, [despite our recent announcement about brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/58275259-9b765000-7d62-11e9-8873-663a34220ebc.png)
[azure-devops.svg.zip](https://github.com/Templarian/MaterialDesign/files/3213544/azure-devops.svg.zip)

**Comment by goyney** [comment]
[![azure-devops](https://materialdesignicons.com/icon/azure-devops)](https://materialdesignicons.com/icon/azure-devops)
