### ISSUE TITLE
Add aliases to 'unfold-*' icons

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3202]
Add aliases to 'unfold-*' icons

Add `Chevron` to:
- [ ] `unfold-less-horizontal`
- [ ] `unfold-less-vertical`
- [ ] `unfold-more-horizontal`
- [ ] `unfold-more-vertical`

Add `collapse` to: 
- [ ] `unfold-less-horizontal`
- [ ] `unfold-less-vertical`

Add `expand` to: 
- [ ] `unfold-more-horizontal`
- [ ] `unfold-more-vertical`

**Comment by PeterShaggyNoble** [comment]
Aliases added.
