### ISSUE TITLE
Sort icons are "broken"

### ISSUE THREAD

**Issue by sstativa** [Templarian/MaterialDesign#3203]
I believe the idea behind sort icons is wrong. I personally "read" both icons as "sort from largest to smallest" and it does not matter which direction the allow is pointed.

Don't you think these icons should be similar to FontAwesome icons?

**Comment by Templarian** [comment]
I actually thought about changing this a while back, but got distracted.

So I'm leaning to agree with you on this. Lets get a few others opinions on this:

[![sort-ascending](https://materialdesignicons.com/icon/sort-ascending)](https://materialdesignicons.com/icon/sort-ascending) [![sort-descending](https://materialdesignicons.com/icon/sort-descending)](https://materialdesignicons.com/icon/sort-descending)

**Comment by JapanYoshi** [comment]
The arrows are quite confusing. Why not just fix its direction?
![sortup](https://user-images.githubusercontent.com/8707990/40572615-d1f9033e-60f3-11e8-908b-794365d1b84c.png)
![sortdown](https://user-images.githubusercontent.com/8707990/40572616-d3aa9530-60f3-11e8-9872-07a18ffc12c5.png)

**Comment by goyney** [comment]
Arrows (or arrow variations) are the standard for indicating sort, so I believe we need to keep an arrow. I believe the best course of action would be to change the arrow but leave any "context lines" the same in both icons. Line 2 in @sstativa would be my vote.

**Comment by goyney** [comment]
This has been addressed.

[![sort-ascending](https://materialdesignicons.com/icon/sort-ascending)](https://materialdesignicons.com/icon/sort-ascending)[![sort-descending](https://materialdesignicons.com/icon/sort-descending)](https://materialdesignicons.com/icon/sort-descending)
