### ISSUE TITLE
https://materialdesignicons.com/ is down

### ISSUE THREAD

**Issue by max-ott** [Templarian/MaterialDesign#3205]
https://materialdesignicons.com/ is down and CSS file is not getting delivered. I'm getting a `502` server error: `Failed to load resource: the server responded with a status of 502 ()`

https://cdn.materialdesignicons.com/2.3.54/css/materialdesignicons.min.css

**Comment by Templarian** [comment]
@max-ott Yep. My host is having issues with one of their racks and are investigating the issue. Hopefully it will be back online in a moment.

**Comment by Templarian** [comment]
~45minutes so far offline. No update from their support other than it's being looked into. It's affecting multiple boxes.

https://statusblog.webfaction.com/2018/05/28/nginx-urgent-maintenance-on-web505-web517-and-web630/

**Comment by Templarian** [comment]
Resolved.
