### ISSUE TITLE
Update video-4k-box

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3206]
Looks like the icon has had an update in the stock set, the K is now a slightly different shape.

![image](https://user-images.githubusercontent.com/15905797/40621630-88b85d34-6295-11e8-8deb-1980cb92111b.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53063343-bf8b7200-3491-11e9-98d7-de1f9fcbf2b8.png)
Our current is outline.

[video-4k-box.svg.zip](https://github.com/Templarian/MaterialDesign/files/2882850/video-4k-box.svg.zip)

**Comment by Templarian** [comment]
Fixed. Nice eye.
