### ISSUE TITLE
clock-outline not part of mdi-css

### ISSUE THREAD

**Issue by alxndrstffn** [Templarian/MaterialDesign#3207]
When upgrading to the newest version of mdi I still can't find http://dev.materialdesignicons.com/icon/clock-outline in the materialdesignicons.css. 

Am I missing something here?

**Comment by PeterShaggyNoble** [comment]
Are you sure you're using the latest version of MDI, v2.4.85?

Which version of the webfont are you using - standalone, CDN or NPM?

**Comment by alxndrstffn** [comment]
When I did:
```$ yarn list @mdi/font
yarn list v1.6.0
warning Filtering by arguments is deprecated. Please use the pattern option instead.
└─ @mdi/font@2.4.85
✨  Done in 0.97s.
```
it seems I have the newest icon-set. But I was still looking at 

the old directory 
```./node_modules/mdi/css/materialdesignicons.css``` 

instead of 
```./node_modules/@mdi/font/css/materialdesignicons.css ```

Sorry for the trouble.
