### ISSUE TITLE
Disk and partition add remove icon

### ISSUE THREAD

**Issue by codeparksoftware** [Templarian/MaterialDesign#3210]
Hi ，
i have looked your icon pack and they are very nice.
 i think there should be partition-disk add &remove icons.
Good jobs

**Comment by MrGrigri** [comment]
The partition ones might be a bit more tricky.  A chart icon with a `plus` and `remove` icon might work.

`harddisk-plus` and `harddisk-remove`

![image](https://user-images.githubusercontent.com/4528551/40922209-df223ee0-67ce-11e8-99ec-f3f9ba880637.png) ![image](https://user-images.githubusercontent.com/4528551/40922232-edf3d794-67ce-11e8-96a2-67aea1c0617b.png)

[harddisk.zip](https://github.com/Templarian/MaterialDesign/files/2068570/harddisk.zip)

**Comment by codeparksoftware** [comment]
thanks for your interesting and I hope partition ones will be made in a short time.

thanks a lot


________________________________
Gönderen: Michael Richins <notifications@github.com>
Gönderildi: 4 Haziran 2018 Pazartesi 17:15
Kime: Templarian/MaterialDesign
Bilgi: codeparksoftware; Author
Konu: Re: [Templarian/MaterialDesign] Disk and partition add remove icon (#3210)


The partition ones might be a bit more tricky. A chart icon with a plus and remove icon might work.

harddisk-plus and harddisk-remove

[image]<https://user-images.githubusercontent.com/4528551/40922209-df223ee0-67ce-11e8-99ec-f3f9ba880637.png>

[https://user-images.githubusercontent.com/4528551/40922209-df223ee0-67ce-11e8-99ec-f3f9ba880637.png]

[image]<https://user-images.githubusercontent.com/4528551/40922232-edf3d794-67ce-11e8-96a2-67aea1c0617b.png>

[https://user-images.githubusercontent.com/4528551/40922232-edf3d794-67ce-11e8-96a2-67aea1c0617b.png]

harddisk.zip<https://github.com/Templarian/MaterialDesign/files/2068570/harddisk.zip>

**Comment by MrGrigri** [comment]
After conversing with the team, I placed the `plus` and `remove` icons 1-pixel too much to the top and right. This is the corrected position.

![image](https://user-images.githubusercontent.com/4528551/40930569-3d86300c-67e5-11e8-97cc-2b32455398aa.png) ![image](https://user-images.githubusercontent.com/4528551/40930534-2ebac36c-67e5-11e8-9a00-07b418ff666f.png)

[harddisk.zip](https://github.com/Templarian/MaterialDesign/files/2069198/harddisk.zip)

**Comment by codeparksoftware** [comment]
Thank you for the information.



________________________________
Gönderen: Michael Richins <notifications@github.com>
Gönderildi: 4 Haziran 2018 Pazartesi 19:52
Kime: Templarian/MaterialDesign
Bilgi: codeparksoftware; Author
Konu: Re: [Templarian/MaterialDesign] Disk and partition add remove icon (#3210)


After conversing with the team, I placed the plus and remove icons 1-pixel too much to the top and right. This is the corrected position.

[image]<https://user-images.githubusercontent.com/4528551/40930569-3d86300c-67e5-11e8-97cc-2b32455398aa.png>

[https://user-images.githubusercontent.com/4528551/40930569-3d86300c-67e5-11e8-97cc-2b32455398aa.png]

[image]<https://user-images.githubusercontent.com/4528551/40930534-2ebac36c-67e5-11e8-9a00-07b418ff666f.png>

harddisk.zip<https://github.com/Templarian/MaterialDesign/files/2069198/harddisk.zip>

**Comment by goyney** [comment]
[![harddisk-plus](https://materialdesignicons.com/icon/harddisk-plus)](https://materialdesignicons.com/icon/harddisk-plus)[![harddisk-remove](https://materialdesignicons.com/icon/harddisk-remove)](https://materialdesignicons.com/icon/harddisk-remove)
