### ISSUE TITLE
CDN URL returns "Privacy Error"

### ISSUE THREAD

**Issue by infusedmj** [Templarian/MaterialDesign#3211]
Just would like to raise this up. The CDN URL 
https://cdn.materialdesignicons.com/2.4.85/css/materialdesignicons.min.css returns an SSL Error:

Screenshot: 
![image](https://user-images.githubusercontent.com/1175294/40882314-31bbff3a-6719-11e8-8412-707760cbdaca.png)

**Comment by Templarian** [comment]
I'll resolve this tomorrow morning. I'm away from my machine until then. Had a small issue renewing the cert thought I had it applied to all the subdomains.

**Comment by Templarian** [comment]
This has been resolved. I apparently renewed a different subdomain certificate instead of the one I have dedicated for the `cdn.*.com` domain. This will take a minute to go into effect.

**Comment by infusedmj** [comment]
Thank you very much for your fast resolution on this.

**Comment by Templarian** [comment]
Usually quicker, but was no where near my laptop for most of the weekend. 🤣 🌞 

Thanks for opening the issue!
