### ISSUE TITLE
Admin panel

### ISSUE THREAD

**Issue by Joshfindit** [Templarian/MaterialDesign#3213]
*Note: Suggestion is the rectangle area only, **not** the computer monitor*

![](http://www.softbit.tech/wp-content/uploads/2016/11/icon_admin_panel@4x.png)

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR2t4biRuERWqSF6g39cxaDfsQNJ3XO5-mRAl4QmBoXANwYpJbs)

![](https://image.shutterstock.com/image-vector/admin-panel-vector-icon-260nw-623159702.jpg)

![](http://laoblogger.com/images/monitoring-clipart-2.jpg)

**Comment by MrGrigri** [comment]
Would the [wrench](https://materialdesignicons.com/icon/wrench) or [settings](https://materialdesignicons.com/icon/settings) icon not work?

**Comment by Joshfindit** [comment]
@MrGrigri I would say no:

An admin panel is a collection of tools, and the admin panel itself would normally contain it's own settings and wrench icons for different functions.

**Comment by Joshfindit** [comment]
Coming back to this, I would say dead giveaways for an admin panel from a distance: sidebar on the left, separated panels on the right that each contain a text block or some sort of graph/chart.

**Comment by MrGrigri** [comment]
Well, out of these two, I prefer the first. 

![image](https://user-images.githubusercontent.com/4528551/41051032-3cdb4e9c-6972-11e8-840f-0fba21259329.png) ![image](https://user-images.githubusercontent.com/4528551/41051056-4ca51e70-6972-11e8-9b74-ef28db117400.png)

[desktop-mac-admin.zip](https://github.com/Templarian/MaterialDesign/files/2077156/desktop-mac-admin.zip)

**Comment by PeterShaggyNoble** [comment]
Would `view-dashboard-variant` or `view-quilt` (or one of the other [`view-*`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=view) icons) not do the job here?

![view-dashboard-variant](https://user-images.githubusercontent.com/15157491/41111694-ae405372-6a74-11e8-8f8f-c98097174a4a.png) ![view-quilt](https://user-images.githubusercontent.com/15157491/41111662-8442e788-6a74-11e8-9ddd-55ab664ab76d.png)

**Comment by Templarian** [comment]
[![monitor-dashboard](https://materialdesignicons.com/icon/monitor-dashboard)](https://materialdesignicons.com/icon/monitor-dashboard) [![desktop-mac-dashboard](https://materialdesignicons.com/icon/desktop-mac-dashboard)](https://materialdesignicons.com/icon/desktop-mac-dashboard)
