### ISSUE TITLE
Greek symbols

### ISSUE THREAD

**Issue by shehezard** [Templarian/MaterialDesign#3215]

**Comment by MrGrigri** [comment]
You are going to have to be a bit more specific. Are you asking for a specific Greek character?

![alpha](https://materialdesignicons.com/icon/alpha) ![beta](https://materialdesignicons.com/icon/beta) ![delta](https://materialdesignicons.com/icon/delta) ![lambda](https://materialdesignicons.com/icon/lambda) ![pi](https://materialdesignicons.com/icon/pi) ![sigma](https://materialdesignicons.com/icon/sigma) ![omega](https://materialdesignicons.com/icon/omega)

**Comment by MrGrigri** [comment]
We might want to add `greek` as an alias to these icons.

**Comment by PeterShaggyNoble** [comment]
Suggest `greek-alphabet` as the alias.

**Comment by shehezard** [comment]
@MrGrigri @PeterShaggyNoble 
Yes, exactly. The entire greek alphabet, like in MS Word.
Both for the capital (uppercase) and simple (lowercase) letterings. Eg: delta is both Δ (capital) and δ (capital)
![image](https://user-images.githubusercontent.com/20703436/44330148-7cbff180-a490-11e8-8934-80146984ee96.png)

**Comment by MrGrigri** [comment]
Idk if we'd add each Greek letter for the same reason we are not adding every Latin letter. Please refer to #1299 as a reference. I'm going to close this for now and if we decide to add it in the future, we'll add them.

**Comment by shehezard** [comment]
I saw the greek characters. Thank you Sir! 😃

**Comment by PeterShaggyNoble** [comment]
We already have a `delta` icon, which @MrGrigri included in his comment:

[![delta](http://mdi.houseofdesign.ie/tools/preview/?icon=delta&action=link)](https://materialdesignicons.com/icon/delta)
