### ISSUE TITLE
Image Move Icon

### ISSUE THREAD

**Issue by debjitk** [Templarian/MaterialDesign#3216]
Image Move icon similar to Image Plus icon

**Comment by MrGrigri** [comment]
Like this?

![image](https://user-images.githubusercontent.com/4528551/40985501-8050c908-68a1-11e8-8a8c-be87e0dc9967.png)

[image-move.zip](https://github.com/Templarian/MaterialDesign/files/2072949/image-move.zip)

**Comment by MrGrigri** [comment]
Like `image-search`, I have revisited this icon and I feel that the cutout and arrow should be in the top-right corner.

![image](https://user-images.githubusercontent.com/4528551/41257405-ef46ba42-6d89-11e8-8c93-de90aef718fc.png)

[image-move.zip](https://github.com/Templarian/MaterialDesign/files/2091759/image-move.zip)

**Comment by Templarian** [comment]
[![image-move](https://materialdesignicons.com/icon/image-move)](https://materialdesignicons.com/icon/image-move)
