### ISSUE TITLE
Google Lens

### ISSUE THREAD

**Issue by k5cents** [Templarian/MaterialDesign#3217]
![image](https://user-images.githubusercontent.com/18021678/40982214-b1917e46-68aa-11e8-9e01-baed1b624db5.png)

**Comment by PeterShaggyNoble** [comment]
Included in Google's Extended icon set.

[![google-lens](https://user-images.githubusercontent.com/15157491/40983595-eb167b76-68d7-11e8-941d-230666c85d52.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by Templarian** [comment]
[![google-lens](https://materialdesignicons.com/icon/google-lens)](https://materialdesignicons.com/icon/google-lens)
