### ISSUE TITLE
Velocity

### ISSUE THREAD

**Issue by felpin** [Templarian/MaterialDesign#3218]

**Comment by MrGrigri** [comment]
Cutting through the complicated algorithm of velocity, essentially it's speed. So why wouldn't `speedometer` or one of the `gauge-*` variants work?

![speedometer](https://materialdesignicons.com/icon/speedometer) ![gauge](https://materialdesignicons.com/icon/gauge)

**Comment by MrGrigri** [comment]
Even `run-fast` would work.

![run-fast](https://materialdesignicons.com/icon/run-fast)
