### ISSUE TITLE
account-minus-outline

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3219]
Just noticed we don't have an `account-minus-outline` icon.

[![account-minus-outline](https://user-images.githubusercontent.com/15157491/41091811-5a8cfd28-6a3f-11e8-8996-7a67ddb0d28a.png)](https://github.com/Templarian/MaterialDesign/files/2079886/account-minus-outline.zip)

**Comment by Templarian** [comment]
[![account-minus-outline](https://materialdesignicons.com/icon/account-minus-outline)](https://materialdesignicons.com/icon/account-minus-outline) [![account-remove-outline](https://materialdesignicons.com/icon/account-remove-outline)](https://materialdesignicons.com/icon/account-remove-outline)
