### ISSUE TITLE
Drag and drop icon

### ISSUE THREAD

**Issue by philippeluickx** [Templarian/MaterialDesign#322]
Something to indicate an element is draggable.

https://cdn1.iconfinder.com/data/icons/interface-4/96/Cursor-Move-512.png

- [ ] cursor-move (alias `move`)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/arrow-all
http://materialdesignicons.com/icon/cursor-move

**Comment by philippeluickx** [comment]
Thanks!
