### ISSUE TITLE
Request for ozone o3 icon

### ISSUE THREAD

**Issue by frittes** [Templarian/MaterialDesign#3222]
Hi,

it would be nice to have an icon for ozone.

Like the co2 (periodic-table-co2) for o3.

Thanks.

**Comment by MrGrigri** [comment]
As discussed in #2475, we're not going to add every chemical compound as that could get crazy.

**Comment by frittes** [comment]
Ok, but ozone is relevant for weather data.

**Comment by Spirituss** [comment]
I join the request, since O3, NO2, SO2, CO - are kind of "standard" set of atmospheric gases that can be observed via world meteo stations like http://aqicn.org or https://darksky.net or https://weather.com. A lot of users of "smart home" uses MDI icons set, expecting icons above mentioned.

**Comment by Spirituss** [comment]
I support this request.
