### ISSUE TITLE
"sun umbrella (protection)"

### ISSUE THREAD

**Issue by WideAngleDe** [Templarian/MaterialDesign#3225]
Would be good to have also an icon for "sun umbrella (protection)". There is a sunglasses icon already.

**Comment by PeterShaggyNoble** [comment]
Would `beach` (which is aliased as `parasol`) not suit your needs?

**Comment by WideAngleDe** [comment]
I thought more of an icon like this:
https://www.iconfinder.com/icons/1056103/day_out_line_protect_protection_sun_sunny_uv_icon

Anyhow was this request more a suggestion only to enhance the icon stock.

**Comment by PerthTotty** [comment]
What about something like this?
![sun-protection](https://user-images.githubusercontent.com/40835272/42455709-471961ec-8393-11e8-960b-c0f70dfe3ce4.png)
![sun-protection-outline](https://user-images.githubusercontent.com/40835272/42455713-48fdc66a-8393-11e8-88a7-3bb8b89bd8ef.png)
[sun-protection.zip](https://github.com/Templarian/MaterialDesign/files/2176513/sun-protection.zip)

**Comment by goyney** [comment]
Do these work, or do the sun's rays get lost?
![image](https://user-images.githubusercontent.com/1015040/62591470-9de64180-b89d-11e9-937f-4cb8b989767e.png)![image](https://user-images.githubusercontent.com/1015040/62591453-958e0680-b89d-11e9-81e1-dc9f4df424c8.png)

[shield-sun.zip](https://github.com/Templarian/MaterialDesign/files/3475026/shield-sun.zip)

**Comment by MrGrigri** [comment]
Those work

**Comment by MrGrigri** [comment]
This might be able to solve #2651

**Comment by goyney** [comment]
[![shield-sun](https://materialdesignicons.com/icon/shield-sun)](https://materialdesignicons.com/icon/shield-sun)[![shield-sun-outline](https://materialdesignicons.com/icon/shield-sun-outline)](https://materialdesignicons.com/icon/shield-sun-outline)
