### ISSUE TITLE
"(analog) photo enlarger"

### ISSUE THREAD

**Issue by WideAngleDe** [Templarian/MaterialDesign#3226]
Would be good to have an "(analog) photo enlarger" icon to be able show the difference to 'printers'.

**Comment by MrGrigri** [comment]
Could you please explain what you mean by this, please?

**Comment by brocococonut** [comment]
I believe they mean something like this:
![Analog photo enlarger](https://www.fotoimpex.de/shop/images/products/main/VP350.jpg)

They're used to enlarge a projection of film onto photographic paper to then be developed in a darkroom.

I don't think it's entirely necessary to have one in the icon set due to their relative obscurity these days.

**Comment by MrGrigri** [comment]
Yeah, if that's the case then that more than likely will not get added.

**Comment by WideAngleDe** [comment]
My request/suggestion is for sure not the most important ever. 

BUT e.g. offer multiple companies still 
photographic prints on classic photosensitive photo paper from Fuji, Kodak, Ilford.
See e.g.: https://us.whitewall.com/photo-lab/photo-print

In contrast to ink jet prints:
See e.g.: https://us.whitewall.com/photo-lab/prints/print-photo/hahnemuehle-fine-art

For sure are in volume production today no more classic enlargers used. Instead (laser)
 light 'printers'. But I agree that it is a limited market.

Anyhow: Key differentiation is still two complete different technologies: Light  <> Ink.

And last not least are CPUs and other chips are still produced with enlarging technologies:
See: https://en.wikipedia.org/wiki/Photolithography
See: https://www.google.de/search?q=photolithography+silicon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjUheHFrO7bAhViG5oKHSxZCfMQ_AUICigB&biw=1404&bih=810

**Comment by goyney** [comment]
This seems like a very niche icon/use case. Additionally, it doesn't really translate well to an icon, as seen here:
![image](https://user-images.githubusercontent.com/1015040/46389083-04a73700-c69e-11e8-967a-63b2384ddcec.png)

I think we're going to close this request. Thank you for the suggestion.
