### ISSUE TITLE
Did you remove Apple PNG export?

### ISSUE THREAD

**Issue by lolgear** [Templarian/MaterialDesign#3227]
Hi!

I can not find simple package download for Apple png assets.

Was it removed?

**Comment by lolgear** [comment]
@Templarian 

Apple Assets with PNGs:

item.imageset/
item@1x~universal.png
item@2x~universal.png
item@3x~universal.png
Contents.json
 
Whole image package with images of original size, 2x and 3x would be nice.
If it exists then extra option in `export package` is preferable.

**Comment by davcpas1234** [comment]
@Templarian would be great to have this feature added

**Comment by goyney** [comment]
What is the use case for this request? Why couldn't this be handled within your own gulp/grunt/webpack/other taskrunner with the `@mdi/svg` package?

**Comment by davcpas1234** [comment]
@goyney, thanks for coming back. The best use case i can give would be consistent developer experience, all other major platform/formats are offered. (Android, .PNG, .SVG etc.) This would give a one stop portal without the need for additional 3rd party frameworks.

**Comment by goyney** [comment]
I still don't understand. Why would you _choose_ to use a PNG image over the SVG?

Also, we already have the option to download the icons as PNGs in various sizes from the website:
![Screen Shot 2019-04-12 at 5 23 15 PM](https://user-images.githubusercontent.com/1015040/56067037-b018fe80-5d47-11e9-9d25-eb56069a656b.png).

There is no such thing as "Apple PNG," they're PNGs. If you need them in very specific sizes, I believe that is something you would need to generate for your application.

**Comment by davcpas1234** [comment]
The reason I ask is because Google provide a compiled `.imageset` which contains standard, @2x and @3x .png  for 16, 24, 32 and 48pt sizes.

To have the community set compiled the same just makes better sense.

(I must acknoldge that I myself only have 1 day experience developing for iOS and have 10 years+ Android. So I'm happy to accept if there is a better way, just following the option that Google provide)

**Comment by goyney** [comment]
Closing because the `Consider Closing` tag was added more than 30 days ago.
