### ISSUE TITLE
file-alert and file-alert-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3228]
![image](https://user-images.githubusercontent.com/1015040/41306307-b0c46ab6-6e43-11e8-9985-0b56aa59bc07.png)
![image](https://user-images.githubusercontent.com/1015040/41306298-a6b4a040-6e43-11e8-8aa5-8698744f509f.png)
[file-alert.zip](https://github.com/Templarian/MaterialDesign/files/2095123/file-alert.zip)

**Comment by MrGrigri** [comment]
the exclamation needs to be 2-pixels wide. This might look better with the document moved to the left 2-pixels and then the exclamation on the right of the document.

**Comment by goyney** [comment]
@MrGrigri That really doesn't match the style of any other "file" type icon. We can either fatten the exclamation point in place or move it within the context of the document.

Examples:

![screen shot 2018-06-11 at 5 08 29 pm](https://user-images.githubusercontent.com/1015040/41257266-370f2642-6d9a-11e8-8542-afb9a76e5801.png)
![screen shot 2018-06-11 at 5 09 16 pm](https://user-images.githubusercontent.com/1015040/41257267-37295a3a-6d9a-11e8-8fd7-8ff66665ff88.png)

**Comment by GreenTurtwig** [comment]
We are, yes. It's on the big to-do list for the new stock icons.

**Comment by goyney** [comment]
@GreenTurtwig Where can I find the new `file-outline`? I don't see it on Google's official icon listing.

**Comment by GreenTurtwig** [comment]
You just select the "Outlined" style on the left hand side of the page.

**Comment by goyney** [comment]
Right, but which icon are we using as the base? lol, There is no "file," "document," or anything of the like. There are some that look like the previous file icons, such as `note_add`.

@Templarian, maybe you can chime in? Which "file" icon are we using as the base for these changes?

**Comment by GreenTurtwig** [comment]
It's called `insert_drive_file`.

**Comment by goyney** [comment]
Updated using the new style.

**Comment by Templarian** [comment]
[![file-alert](https://materialdesignicons.com/icon/file-alert)](https://materialdesignicons.com/icon/file-alert) [![file-alert-outline](https://materialdesignicons.com/icon/file-alert-outline)](https://materialdesignicons.com/icon/file-alert-outline)
