### ISSUE TITLE
ISSUU - Digital Publishing Platform for Magazines, Catalogs ...

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#323]
ISSUU - Digital Publishing Platform for Magazines, Catalogs ...
https://pbs.twimg.com/profile_images/509490629777162240/0m27ctiz.jpeg

**Comment by Templarian** [comment]
Company logos are not something that will be included in the pack. Basically social media only.

Feel free to submit other icon requests though.
