### ISSUE TITLE
5G Signal

### ISSUE THREAD

**Issue by LukasWieditz** [Templarian/MaterialDesign#3230]
Icon for 5G signal strength, analogous to 4G, etc.

**Comment by Templarian** [comment]
Still have a little while until it's rolled out at the end of the year, but yea we should probably plan ahead that users will need it.

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/41347551-e8a09fd6-6f01-11e8-9174-416e42e33198.png)](https://github.com/Templarian/MaterialDesign/files/2097822/signal.zip)

The folder also contains the other icons with the correct style of G.

**Comment by Templarian** [comment]
[![signal-5g](https://materialdesignicons.com/icon/signal-5g)](https://materialdesignicons.com/icon/signal-5g)
