### ISSUE TITLE
arrow-bold-outline - Full Set

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3231]
A new outline variation of arrows, based on the `arrow-bold` set created by @Templarian. This set includes all cardinal and ordinal directions. It also includes two multidirectional icons in the cardinal directions.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41323746-886d685c-6e7e-11e8-9443-531d96defb8a.png)
![image](https://user-images.githubusercontent.com/1015040/41323752-940e8dee-6e7e-11e8-86fa-146e033dd9f0.png)
![image](https://user-images.githubusercontent.com/1015040/41323770-abe23858-6e7e-11e8-86c4-ce7130020d8d.png)
![image](https://user-images.githubusercontent.com/1015040/41323791-cefc3bf4-6e7e-11e8-884e-d4c31e4e4c2f.png)

![image](https://user-images.githubusercontent.com/1015040/41323727-70f165c0-6e7e-11e8-809b-58f93b926cfb.png)
![image](https://user-images.githubusercontent.com/1015040/41323738-7cf442a2-6e7e-11e8-8e96-51426e9488d7.png)
![image](https://user-images.githubusercontent.com/1015040/41323776-b8d8787e-6e7e-11e8-994b-a3ee43381682.png)
![image](https://user-images.githubusercontent.com/1015040/41323783-c2e8a8d4-6e7e-11e8-9b8a-80a23995dddb.png)

![image](https://user-images.githubusercontent.com/1015040/41323799-d9440722-6e7e-11e8-8a91-47bb61434077.png)
![image](https://user-images.githubusercontent.com/1015040/41323762-a1e4465c-6e7e-11e8-9eec-fb3a5d6c66b3.png)
---

**Source:** [arrow-bold-outline.zip](https://github.com/Templarian/MaterialDesign/files/2096214/arrow-bold-outline.zip)

**Comment by Templarian** [comment]
Added.
