### ISSUE TITLE
arrow-thick - Ordinal Directions

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3232]
Four more additions to the `arrow-thick` variation of arrows created by @Templarian. This set includes the four ordinal directions.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41323936-9cf21cea-6e7f-11e8-90ef-4155744cdd6e.png)
![image](https://user-images.githubusercontent.com/1015040/41323947-ae0cff0e-6e7f-11e8-8686-ba70b29b345e.png)
![image](https://user-images.githubusercontent.com/1015040/41323957-b8f10a1e-6e7f-11e8-97d5-338775905696.png)
![image](https://user-images.githubusercontent.com/1015040/41323964-c29f2f00-6e7f-11e8-9668-86b1bc0d7d0b.png)

---

**Source:** [arrow-thick.zip](https://github.com/Templarian/MaterialDesign/files/2096222/arrow-thick.zip)

**Comment by Templarian** [comment]
Added.
