### ISSUE TITLE
Additional Spiritual/Religious Icons

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3233]
Three additions spiritual/religious icons.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41324045-5315d37c-6e80-11e8-8047-9b9f22a93ba5.png)
![image](https://user-images.githubusercontent.com/1015040/41324036-448401a8-6e80-11e8-87e8-93036f3c09aa.png)
![image](https://user-images.githubusercontent.com/1015040/41324074-7aa15c90-6e80-11e8-85d3-ba985778ecec.png)

---

**Source:** [spiritual.zip](https://github.com/Templarian/MaterialDesign/files/2096228/spiritual.zip)

**Comment by Templarian** [comment]
Added these three. 😃
