### ISSUE TITLE
clock-time-outline - Full Set

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3234]
Twelve icons variating on the already existent `clock` (which is 4 o'clock) for each of the hours.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41324157-08df163c-6e81-11e8-88bc-772d1c01bdc2.png)
![image](https://user-images.githubusercontent.com/1015040/41324175-2250e488-6e81-11e8-994a-191549201893.png)
![image](https://user-images.githubusercontent.com/1015040/41324177-2aec0eb0-6e81-11e8-9d37-dd57c14371fd.png)
![image](https://user-images.githubusercontent.com/1015040/41324185-33870778-6e81-11e8-822a-1f7a7a160e03.png)
![image](https://user-images.githubusercontent.com/1015040/41324186-3bb3faaa-6e81-11e8-8d74-8d7a5032f93f.png)
![image](https://user-images.githubusercontent.com/1015040/41324189-44f9ff2e-6e81-11e8-98dc-d4846386dc15.png)
![image](https://user-images.githubusercontent.com/1015040/41324198-4d40f304-6e81-11e8-816f-58886302eab6.png)
![image](https://user-images.githubusercontent.com/1015040/41324207-56fcdfde-6e81-11e8-8cdf-6c130fa8e933.png)
![image](https://user-images.githubusercontent.com/1015040/41324215-6037089a-6e81-11e8-93c5-c1f6f3f9972e.png)
![image](https://user-images.githubusercontent.com/1015040/41324220-68808436-6e81-11e8-97b9-1db82670dde0.png)
![image](https://user-images.githubusercontent.com/1015040/41324227-71a34274-6e81-11e8-9b07-1e7142bcda37.png)
![image](https://user-images.githubusercontent.com/1015040/41324234-7b59f6fa-6e81-11e8-8bcb-e052144063f9.png)

---

**Source:** [clock-time-outline.zip](https://github.com/Templarian/MaterialDesign/files/2096236/clock-time-outline.zip)

**Comment by MrGrigri** [comment]
Idk if we need to add every hour as a clock variant...

**Comment by Templarian** [comment]
Agreeing with this, it's probably out of scope. It's nice, but seems kind of overkill.

Closing this one out.

**Comment by PeterShaggyNoble** [comment]
Would it be worth creating a `clock-face` icon and then `clock-hand-hour` & `clock-hand-minute` icons that could be overlaid on top of it and rotated as necessary?

**Comment by CoDEmanX** [comment]
That would essentially be a circle and two strokes, each as separate icon. I would rather script a clock with SVG and some JS.

**Comment by goyney** [comment]
These have all been added and will be available in 5.2.
