### ISSUE TITLE
star - New Variations

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3235]
Several new star variations.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/43853713-ed098a86-9b0e-11e8-8a2c-ec7dcbf24bf7.png)![image](https://user-images.githubusercontent.com/1015040/43853739-f767265a-9b0e-11e8-8dd4-c618909887f1.png)
![image](https://user-images.githubusercontent.com/1015040/43853754-024c2188-9b0f-11e8-8d5a-c5669df61bc0.png)![image](https://user-images.githubusercontent.com/1015040/43853770-0a763a9c-9b0f-11e8-8ef3-669ff20ef0d2.png)
![image](https://user-images.githubusercontent.com/1015040/43853788-1472c920-9b0f-11e8-9cbd-4f108ae7553f.png)![image](https://user-images.githubusercontent.com/1015040/43853800-1bacd83e-9b0f-11e8-8c4e-6132eed4c5fd.png)

---

**Source:**[stars.zip](https://github.com/Templarian/MaterialDesign/files/2271247/stars.zip)

**Comment by Templarian** [comment]
`octagram` / `decagram` I think is basically `starburst`. Could just add an alias?

Any reason not to have a 3 point outline?

**Comment by goyney** [comment]
Yeah, I think those are good aliases. I'll get outlines of the other two today.

**Comment by Templarian** [comment]
Added. Thanks!
