### ISSUE TITLE
snail-mail

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3236]
![image](https://user-images.githubusercontent.com/1015040/41324577-32748764-6e83-11e8-9626-f19c43c8956f.png)

---

**Source:** [mail.zip](https://github.com/Templarian/MaterialDesign/files/2096258/mail.zip)

**Comment by PeterShaggyNoble** [comment]
See also #2012

**Comment by Templarian** [comment]
Added. 😃
