### ISSUE TITLE
numeric - New Variation

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3237]
The number 10 in the numeric series in both variations.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41324623-88c7fc5e-6e83-11e8-84c0-8bbcbefa0a7b.png)
![image](https://user-images.githubusercontent.com/1015040/41324627-91459292-6e83-11e8-9f2c-190e0b6db72b.png)

---

**Source:** [numeric-10-box.zip](https://github.com/Templarian/MaterialDesign/files/2096263/numeric-10-box.zip)

**Comment by PeterShaggyNoble** [comment]
@Templarian, you've assigned theseto the wrong Michael in the database.
