### ISSUE TITLE
hand - New Variations

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3238]
New variations on the already existing `hand` icons, including new pointing directions and the gestures for "okay," "peace," and "wave" or "stop."

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41324690-f4e645f8-6e83-11e8-9b8e-2ed2b86b8de5.png)
![image](https://user-images.githubusercontent.com/1015040/41324694-ff58ce8e-6e83-11e8-9feb-a7ac078088fd.png)
![image](https://user-images.githubusercontent.com/1015040/41324698-092890fc-6e84-11e8-81fa-d914c6829a1f.png)
![image](https://user-images.githubusercontent.com/1015040/41324710-244629a8-6e84-11e8-98d3-b56e7cc369f0.png)
![image](https://user-images.githubusercontent.com/1015040/41324723-3a26ec6c-6e84-11e8-8379-53e576fa3b44.png)
![image](https://user-images.githubusercontent.com/1015040/41353697-fe3e794c-6eea-11e8-9e46-84c4bc99274b.png)
![image](https://user-images.githubusercontent.com/1015040/41324736-4cd888fc-6e84-11e8-86da-16bfb6b3fca6.png)

---

**Source:** [hand.zip](https://github.com/Templarian/MaterialDesign/files/2098242/hand.zip)

**Comment by MrGrigri** [comment]
The `hand-peace` icon looks off to me...

**Comment by goyney** [comment]
Alternate `hand-peace` added as I recently learned about the V-sign in the UK. 😛 It's not quite Material though, so if anyone wants to take a stab at it, feel free.

**Comment by PeterShaggyNoble** [comment]
Seeing as it's only regionally "offensive" and *how* offensive it is is entirely subjective, I don't think we should worry too much about the ambiguity of `hand-peace` - context will dictate intent. Different hand gestures and signs are "offensive" or rude in different cultures too.

After all (and especially these days!) you're going to find someone who's "offended" by pretty much anything you can think of!

**Comment by Templarian** [comment]
Added. Reversed the names for `hand-peace` and `hand-peace-variant` The norm is palm out in the US. Back of the hand is offensive or aggressive.
