### ISSUE TITLE
New shape variations

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3239]
New variations on the already existing square, circle, and rhombus icons. Also, an additional "diamonds" type icon of a split rhombus.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

**SPECIAL NOTE**: The use-case for the resized versions of the circle and square or for when they are used as bullets in unordered lists. In the specific case of a Wingdings replacement font, the size of the icon comes directly from the glyph, making it necessary. While it may be necessary in a compiled Wingdings replacement font, it may not necessary to include them in MDI, but I am providing them for sake of completion.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41324881-3307644c-6e85-11e8-9354-bc925b21d7a0.png)
![image](https://user-images.githubusercontent.com/1015040/41324885-3b48ad14-6e85-11e8-861a-8b7589671b0e.png)
![image](https://user-images.githubusercontent.com/1015040/41324898-4f01d4fc-6e85-11e8-87f0-0c9b2c459b72.png)
![image](https://user-images.githubusercontent.com/1015040/41324953-982081a6-6e85-11e8-87db-0e267cbcedc4.png)
![image](https://user-images.githubusercontent.com/1015040/41324909-5ff49056-6e85-11e8-8846-0b63cc105a9c.png)
![image](https://user-images.githubusercontent.com/1015040/41354998-644eb6ea-6eee-11e8-9c63-9d5d0eaf5b6a.png)
![image](https://user-images.githubusercontent.com/1015040/41355029-7f6c71d8-6eee-11e8-91e5-f0351536539e.png)
![image](https://user-images.githubusercontent.com/1015040/41324916-6ce2e808-6e85-11e8-83cf-a7e455c34843.png)

---

**Source:** [shapes.zip](https://github.com/Templarian/MaterialDesign/files/2098341/shapes.zip)

**Comment by PeterShaggyNoble** [comment]
See also #1709

**Comment by Templarian** [comment]
Added all above except the diamond.
