### ISSUE TITLE
glasses, sunglasses, sale

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#324]
- [ ] glasses
- [ ] sunglasses
- [x] sale

**Comment by CoDEmanX** [comment]
How does a sale icon look like?!

**Comment by metalla030** [comment]
https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/sale.png

**Comment by CoDEmanX** [comment]
I gave it a shot:

![glasses2](https://cloud.githubusercontent.com/assets/1309249/8828671/ac0fe1f8-3093-11e5-83be-a9a309a293ad.png)
![glasses-sun2](https://cloud.githubusercontent.com/assets/1309249/8828673/ac1f5e80-3093-11e5-8cd7-3384eb6d282d.png)
![sale](https://cloud.githubusercontent.com/assets/1309249/8828672/ac1bf880-3093-11e5-9a31-4a4d1282fe90.png)

**Comment by Templarian** [comment]
Those look awesome!

**Comment by metalla030** [comment]
I like it

**Comment by metalla030** [comment]
I like it

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/sale

Waiting for the vectors for from @CoDEmanX for the 2 other icons.

**Comment by CoDEmanX** [comment]
Original Illustrator file: https://www.dropbox.com/s/4lw22hwmtu146zh/glasses.ai?dl=0
Glasses (glasses-outline?): https://www.dropbox.com/s/bfac9o48hirpb8a/glasses.svg?dl=0
Sunglasses (glasses-sun?): https://www.dropbox.com/s/yq9ctoawnjh3oqj/glasses-variant.svg?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/glasses
https://materialdesignicons.com/icon/sunglasses

Thanks!
