### ISSUE TITLE
help-rhombus

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3240]
New help icon variations.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---
![image](https://user-images.githubusercontent.com/1015040/41352421-6c694b12-6ee7-11e8-8f30-0b20858decc7.png)
![image](https://user-images.githubusercontent.com/1015040/41325016-f48f5020-6e85-11e8-8899-0d1e220e45b6.png)

---

**Source:** [help-rhombus.zip](https://github.com/Templarian/MaterialDesign/files/2098152/help-rhombus.zip)

**Comment by PeterShaggyNoble** [comment]
Shouldn't we add a filled version, too?

**Comment by goyney** [comment]
@PeterShaggyNoble Agreed, added.

**Comment by Templarian** [comment]
[![help-rhombus](https://materialdesignicons.com/icon/help-rhombus)](https://materialdesignicons.com/icon/help-rhombus) [![help-rhombus-outline](https://materialdesignicons.com/icon/help-rhombus-outline)](https://materialdesignicons.com/icon/help-rhombus-outline)
