### ISSUE TITLE
file-document-box Variation & file-cabinet

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3241]
New variations on `file-document-box` and the addition of a file cabinet.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41325071-4c0d88da-6e86-11e8-806e-73e095228fac.png)
![image](https://user-images.githubusercontent.com/1015040/41325083-5629b5fa-6e86-11e8-80a4-2eb783a4c5d6.png)

---

**Source:** [files.zip](https://github.com/Templarian/MaterialDesign/files/2096302/files.zip)

**Comment by Templarian** [comment]
[![file-document-box-multiple](https://materialdesignicons.com/icon/file-document-box-multiple)](https://materialdesignicons.com/icon/file-document-box-multiple) [![file-document-box-multiple-outline](https://materialdesignicons.com/icon/file-document-box-multiple-outline)](https://materialdesignicons.com/icon/file-document-box-multiple-outline) [![file-cabinet](https://materialdesignicons.com/icon/file-cabinet)](https://materialdesignicons.com/icon/file-cabinet)
