### ISSUE TITLE
backspace-reverse

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3242]
New variations of the `backspace` icon.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41352746-3d4022ce-6ee8-11e8-98e5-8fe9f82d553b.png)
![image](https://user-images.githubusercontent.com/1015040/41352761-47bc8620-6ee8-11e8-8781-4525d5e3479e.png)
![image](https://user-images.githubusercontent.com/1015040/41352773-51b0e96e-6ee8-11e8-8325-fc277f1cae23.png)

---

**Source:** [backspace.zip](https://github.com/Templarian/MaterialDesign/files/2098170/backspace.zip)

**Comment by JapanYoshi** [comment]
Tweaking these to make them fit with [Google's stock backspace](https://materialdesignicons.com/icon/backspace) might be necessary, but I can see them being used in screen keyboards.

**Comment by goyney** [comment]
@JapanYoshi Didn't see that one when these were created. I will refactor to match.

**Comment by goyney** [comment]
These have been updated to match the existing `backspace`.

**Comment by PeterShaggyNoble** [comment]
See also #2318

**Comment by JapanYoshi** [comment]
Because backspace and delete are two different distinct keys. @terpro

**Comment by Templarian** [comment]
[![backspace-outline](https://materialdesignicons.com/icon/backspace-outline)](https://materialdesignicons.com/icon/backspace-outline)

**Comment by goyney** [comment]
Normally, I wouldn't ask about the reverse, but I think it could be useful for RTL languages.

**Comment by Templarian** [comment]
Added. 😃
