### ISSUE TITLE
scissors-cutting

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3243]
Variation on `content-cut`. It depicts the scissors angled, as if cutting, with part of one blade cropped out.

A use-case for this would be to create a dotted-line area of a printed document that states to "cut here."

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41325257-5bde7a66-6e87-11e8-80ff-36612076b105.png)

---

**Source:** [scissors-cutting.zip](https://github.com/Templarian/MaterialDesign/files/2096319/scissors-cutting.zip)

**Comment by Templarian** [comment]
I'm going to say this is very similar to the scissor icon's use in some cases. Closing.

**Comment by CoDEmanX** [comment]
What if there was a dashed line to indicate where to cut along? Like:

![grafik](https://user-images.githubusercontent.com/1309249/42604558-b4369894-8573-11e8-84db-1c3ee83e4a91.png)

![grafik](https://user-images.githubusercontent.com/1309249/42604568-c256ea82-8573-11e8-9201-4276440e42b1.png)

**Comment by goyney** [comment]
Too literal. You can use the scissors icon and place it on a dashed line to achieve the same effect. I agree with @Templarian.

**Comment by Templarian** [comment]
Actually adding a dotted/dashed line might be useful.

**Comment by goyney** [comment]
@Templarian Like this?

![image](https://user-images.githubusercontent.com/1015040/43731794-a89bd634-997d-11e8-8c7b-755dec7ae605.png)

**Source:** [scissors-cutting.zip](https://github.com/Templarian/MaterialDesign/files/2263501/scissors-cutting.zip)

**Comment by goyney** [comment]
Added in 2.6.95.
