### ISSUE TITLE
chevron-box - Full Set

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3244]
A full set of chevron icons encased in a box.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

---

![image](https://user-images.githubusercontent.com/1015040/41325434-465dac38-6e88-11e8-820a-6a2ed61e25c0.png)
![image](https://user-images.githubusercontent.com/1015040/41325440-4f38fa24-6e88-11e8-9958-04d6e548a16c.png)
![image](https://user-images.githubusercontent.com/1015040/41325443-579cbcfa-6e88-11e8-8152-681c86c558db.png)
![image](https://user-images.githubusercontent.com/1015040/41325448-610fa31a-6e88-11e8-9580-2b4880119977.png)
![image](https://user-images.githubusercontent.com/1015040/41325453-6c9103c8-6e88-11e8-85c5-99b594afc272.png)
![image](https://user-images.githubusercontent.com/1015040/41325461-7457fdf0-6e88-11e8-9e21-ec4582110963.png)
![image](https://user-images.githubusercontent.com/1015040/41325469-7c44b40e-6e88-11e8-881f-60afad36b4cf.png)
![image](https://user-images.githubusercontent.com/1015040/41325476-85c2a8ba-6e88-11e8-9707-af6751ce0a11.png)

---

**Source:** [chevron-box.zip](https://github.com/Templarian/MaterialDesign/files/2096342/chevron-box.zip)

**Comment by Templarian** [comment]
I actually could use these at work, so definitely would be nice to have.

(would take too long to link each one, but they are all added)
