### ISSUE TITLE
FCC

### ISSUE THREAD

**Issue by joegasper** [Templarian/MaterialDesign#3246]
Information Technology Equipment (I.T.E.) Symbols

These are the icons you find on the backs of power supplies, TVs, and most other electronic equipment. Labels are often printed very small or laser written and require scalable vector images.

Examples: FCC, CE, RoHS, UL, WEEE, Double-Insulated, Indoor Use Only, Alternating current, Direct current, etc.

https://www.fcc.gov/general/logos-fcc
https://www.ni.com/support/cert/prod_cert_details.htm
https://www.cnet.com/news/certification-marks-decoded/
https://gizmodo.com/5966087/what-the-strange-symbols-on-your-gadgets-mean/
https://www.jameco.com/Jameco/marketing/agency-symbols.html
https://files.support.epson.com/docid/cpd4/cpd42641/source/notices/reference/safety_symbols_list.html
http://incompliancemag.com/wp-content/uploads/2014/03/1311_F1_fig1.png
https://community.croma.com/t5/Knowledge-Base/Always-wondered-what-the-symbols-mean/ba-p/1440
https://ledcorporations.com/regulatory-product-certification-marks-ul-etl-ce-csa-energy-star-and-dlc/
https://www.mullanlighting.com/symbols

Thanks for considering.

**Comment by JapanYoshi** [comment]
Since those icons mostly concern themselves with hardware, not software, I doubt that MDA will have incentive enough to include those.

**Comment by PeterShaggyNoble** [comment]
To help us track these better, can you edit this down to a single icon request and then create individual requests for the rest? Don't forget to search existing icons and issues first (we already have AC & DC icons, for example)

Also note that we don't add regional (brand) icons, such as the FCC logo.

**Comment by MrGrigri** [comment]
I believe since these are regulatory branded icons we shouldn't add these. Mainly because whenever your device is registered with these agencies, their logo, and not a recreation, is needed.

**Comment by Templarian** [comment]
^ I'm going to 100% agree with what @MrGrigri said. This is all on a legal level outside of what I feel comfortable including in the pack. It's also fairly specific.
