### ISSUE TITLE
Alias Religious Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3247]
Leaving this here as a reminder to myself to alias the religious icons with each symbol's name as well as the religion's adjective (e.g., `dharmachakra` & `religion-buddhist` for `buddhism`) when I get a few minutes later in the week. Unless someone else gets to it in the meantime!

**Comment by JapanYoshi** [comment]
Also tag them with ``religion``?

**Comment by PeterShaggyNoble** [comment]
Good point, @JapanYoshi - updated my original reminder.

**Comment by goyney** [comment]
The `hinduism` symbol is actually called the "om" symbol, which is what I originally searched for and did not find.

Might want to add "cross" to `christianity` as well.

**Comment by PeterShaggyNoble** [comment]
Aliases added.
