### ISSUE TITLE
Zip Disk

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3248]
![](https://user-images.githubusercontent.com/15905797/41346931-1205d028-6f00-11e8-89b4-4b00e50d6efa.png)![](https://user-images.githubusercontent.com/15905797/41346953-22d69cc0-6f00-11e8-87fa-fa6f2038fd9f.png)
[zip-disk.zip](https://github.com/Templarian/MaterialDesign/files/2097795/zip-disk.zip)

**Comment by PeterShaggyNoble** [comment]
If it's a choice, my vote goes to the first.

**Comment by GreenTurtwig** [comment]
@petershaggynoble They're both used, Zip disks come in two different shapes. 😺

**Comment by PeterShaggyNoble** [comment]
I remember 😉 I just think, as an icon, the first is more instantly recognisable as a ZIP disk.

**Comment by Templarian** [comment]
[![zip-disk](https://materialdesignicons.com/icon/zip-disk)](https://materialdesignicons.com/icon/zip-disk)
