### ISSUE TITLE
flower-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3249]
Include the `local_florist` outline icon from the stock Google set as `flower-outline` to complement our already existing `flower`.

**Comment by GreenTurtwig** [comment]
Google already has an outlined variant in the stock set.
https://material.io/tools/icons/?icon=local_florist&style=outline

**Comment by goyney** [comment]
Nice catch, disregard my contribution and let's get their version in.

**Comment by Templarian** [comment]
[![flower-outline](https://materialdesignicons.com/icon/flower-outline)](https://materialdesignicons.com/icon/flower-outline)
