### ISSUE TITLE
Window Titlebar Icons

### ISSUE THREAD

**Issue by efeerdogru** [Templarian/MaterialDesign#325]
Hi,

If titlebar icons added it'll be very useful.

- [x] window-close
- [x] window-minimize
- [x] window-maximize
- [x] window-restore

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/window-close
http://materialdesignicons.com/icon/window-minimize
http://materialdesignicons.com/icon/window-maximize
http://materialdesignicons.com/icon/window-restore
