### ISSUE TITLE
Worker icon variants

### ISSUE THREAD

**Issue by gabrielafern** [Templarian/MaterialDesign#3250]
Worker icon variants, we need it ASAP for our system

[Icono-worker.zip](https://github.com/Templarian/MaterialDesign/files/2101881/Icono-worker.zip)

**Comment by MrGrigri** [comment]
I believe that merely having an `account-plus`, `account-edit` and `account-check` would suffice. I believe that if it's a unified enough UI, the context of adding, editing, or verifying a working could be understood.

**Comment by goyney** [comment]
Thank you for the request. Since this is a very niche use-case and we have a set of icons that can clearly denote the actions you are intending, we're going to close this issue.
