### ISSUE TITLE
view-outline icons

### ISSUE THREAD

**Issue by Mish325** [Templarian/MaterialDesign#3253]
Hi,

Can we have an outline icon for the view-dashboard icon? Something like below.

![outline-dashboard](https://user-images.githubusercontent.com/19853627/41453893-18b01834-7095-11e8-83a5-2e97ab96ec66.png)

Thanks.

**Comment by PeterShaggyNoble** [comment]
Google recently added this: https://material.io/tools/icons/?search=dashboard&icon=dashboard&style=outline

We also need to add the `outline` variants of their other `view` icons.

**Comment by Mish325** [comment]
Thanks a lot

**Comment by Templarian** [comment]
[![view-dashboard-outline](https://materialdesignicons.com/icon/view-dashboard-outline)](https://materialdesignicons.com/icon/view-dashboard-outline)
