### ISSUE TITLE
Mini SD

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3254]
Totally forgot Mini SD was a thing.
[![](https://user-images.githubusercontent.com/15905797/41473812-416f13f2-70b2-11e8-9203-9685f76ef421.png)](https://github.com/Templarian/MaterialDesign/files/2106397/mini-sd.zip)

**Comment by Templarian** [comment]
[![mini-sd](https://materialdesignicons.com/icon/mini-sd)](https://materialdesignicons.com/icon/mini-sd)
