### ISSUE TITLE
8/5.5 inch floppy

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3255]
[![image](https://user-images.githubusercontent.com/15905797/41473928-9365ba26-70b2-11e8-8edc-75814eacc80e.png)](https://github.com/Templarian/MaterialDesign/files/2106410/floppy-disk-variant.zip)

Also redesigned `floppy` to be a little smaller and flipped.
[![](https://user-images.githubusercontent.com/15905797/41474018-ce5a62f8-70b2-11e8-87c2-d0de8f0b1e65.png)](https://github.com/Templarian/MaterialDesign/files/2106413/floppy-disk.zip)

**Comment by Templarian** [comment]
[![floppy-variant](https://materialdesignicons.com/icon/floppy-variant)](https://materialdesignicons.com/icon/floppy-variant) [![floppy](https://materialdesignicons.com/icon/floppy)](https://materialdesignicons.com/icon/floppy)
