### ISSUE TITLE
8-Track

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3256]
[![](https://user-images.githubusercontent.com/15905797/41474097-037067d0-70b3-11e8-963c-671bb3324bd8.png)](https://github.com/Templarian/MaterialDesign/files/2106417/8-track.zip)

**Comment by PeterShaggyNoble** [comment]
We'd need to call this `eight-track` - icon names can't begin with a number.

**Comment by Templarian** [comment]
[![eight-track](https://materialdesignicons.com/icon/eight-track)](https://materialdesignicons.com/icon/eight-track)
