### ISSUE TITLE
Cassette

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3257]
[![](https://user-images.githubusercontent.com/15905797/41474199-4ef5aef4-70b3-11e8-8084-11fb6e5a4ad2.png)](https://github.com/Templarian/MaterialDesign/files/2106424/cassette.zip)

**Comment by Templarian** [comment]
[![cassette](https://materialdesignicons.com/icon/cassette)](https://materialdesignicons.com/icon/cassette)
