### ISSUE TITLE
VHS and Betamax

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3258]
Not really a fan of either of these, but it's the best you can do without showing the little flap at the top.
[![](https://user-images.githubusercontent.com/15905797/41474326-9542bbf4-70b3-11e8-844f-6f9a6e84e302.png)](https://github.com/Templarian/MaterialDesign/files/2106437/vhs.zip)[![](https://user-images.githubusercontent.com/15905797/41474359-ae4ca9a2-70b3-11e8-81b9-698129500463.png)](https://github.com/Templarian/MaterialDesign/files/2106443/betamax.zip)

**Comment by Templarian** [comment]
[![vhs](https://materialdesignicons.com/icon/vhs)](https://materialdesignicons.com/icon/vhs) [![betamax](https://materialdesignicons.com/icon/betamax)](https://materialdesignicons.com/icon/betamax)
