### ISSUE TITLE
LaserDisc

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3259]
Basically just a larger CD shape. :cat2: 
[![](https://user-images.githubusercontent.com/15905797/41474475-fcce6fc0-70b3-11e8-8a9a-aa58af0a6f7d.png)](https://github.com/Templarian/MaterialDesign/files/2106447/laserdisc.zip)

**Comment by Templarian** [comment]
I like the idea of this one, but lets just say people can use the disc icon.
