### ISSUE TITLE
Tree Icon

### ISSUE THREAD

**Issue by crsosa** [Templarian/MaterialDesign#326]
I can't find a single tree icon anywhere #49 

- [ ] tree

**Comment by Templarian** [comment]
So not a `pine-tree` like the one there now, but a more `tree` tree?

**Comment by crsosa** [comment]
exactly, more tree tree

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/tree

Let me know if this looks right.

**Comment by crsosa** [comment]
yeah! it looks great. Thanks
