### ISSUE TITLE
MiniDisc

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3260]
Another hard one.
[![](https://user-images.githubusercontent.com/15905797/41474591-48a836ba-70b4-11e8-98fa-aa9a80a7eb4d.png)](https://github.com/Templarian/MaterialDesign/files/2106453/minidisc.zip)

**Comment by Templarian** [comment]
[![minidisc](https://materialdesignicons.com/icon/minidisc)](https://materialdesignicons.com/icon/minidisc)
