### ISSUE TITLE
Beacon

### ISSUE THREAD

**Issue by arcarruda** [Templarian/MaterialDesign#3261]

**Comment by goyney** [comment]
Can you provide some examples of what you are looking for?

Would something like [`radio-tower`](https://materialdesignicons.com/icon/radio-tower) or [`access-point`](https://materialdesignicons.com/icon/access-point) work?

**Comment by goyney** [comment]
Thank you for the request. Between `radio-tower`, `access-point`, and they newly added `lighthouse`, I feel we have an option that can indicate a beacon in several different contexts. We're going to go ahead and close this issue.

If none of these options suits your needs, feel free to comment with more details.
