### ISSUE TITLE
Lighthouse

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3262]
Two options for a lighthouse, inspired by the recent "beacon" post when looking for things to suggest as a potential beacon.

**Option 1:**
![image](https://user-images.githubusercontent.com/1015040/41494072-75dda7be-70dc-11e8-8973-383602347b44.png)
![image](https://user-images.githubusercontent.com/1015040/41494087-9c2b9cc8-70dc-11e8-80fc-8f31457c8a36.png)

**Option 2:**
![image](https://user-images.githubusercontent.com/1015040/41494092-ad866d36-70dc-11e8-99f9-246e946f5508.png)
![image](https://user-images.githubusercontent.com/1015040/41494097-b725cb7a-70dc-11e8-8b6e-a7813a9528b5.png)

**Source:** [lighthouses.zip](https://github.com/Templarian/MaterialDesign/files/2107765/lighthouses.zip)

**Comment by MrGrigri** [comment]
I would forego the stripes all together and have the base be solid with a cut-out at the top of the base.

**Comment by Templarian** [comment]
[![lighthouse](https://materialdesignicons.com/icon/lighthouse)](https://materialdesignicons.com/icon/lighthouse) [![lighthouse-on](https://materialdesignicons.com/icon/lighthouse-on)](https://materialdesignicons.com/icon/lighthouse-on)
