### ISSUE TITLE
Suite of Music Icons

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3263]
Instead of splitting this across several requests in the backlog, I've grouped all my work for seriously expanding the presence of music related icons here.

---

~Here is all icons included in this package: [Music Suite.zip](https://github.com/Templarian/MaterialDesign/files/2107860/Music.Suite.zip)~

Here is the newly updated, organized, and preoptimized pack:
[Music Suite.zip](https://github.com/Templarian/MaterialDesign/files/3409184/Music.Suite.zip)

**Updated:**
- [x] music-note
- [x] music-note-off
- [x] music-note-plus
- [x] music-note-bluetooth
- [x] music-note-bluetooth-off
- [x] music-note-sixteenth
- [x] music-note-eighth
- [x] music-note-quarter
- [x] music-note-half
- [x] music-note-whole

**Added by me:**
- [x] music-note-outline
- [x] music-note-off-outline
- [x] music-note-dotted-sixteenth
- [x] music-note-dotted-eighth
- [x] music-note-dotted-quarter
- [x] music-note-dotted-half
- [x] music-note-dotted-whole
- [x] music-sharp
- [x] music-double-sharp
- [x] music-flat
- [x] music-double-flat
- [x] music-natural
- [x] music-rest-sixteenth
- [x] music-rest-eighth
- [x] music-rest-quarter
- [x] music-rest-half
- [x] music-rest-whole

**Added by JapanYoshi:**
- [x] music-clef-alto
- [x] music-clef-bass
- [x] music-clef-treble

---

Foremost, Google's music icon has been updated and ours is outdated:
![image](https://user-images.githubusercontent.com/1015040/41494251-bef0c236-70de-11e8-9c6e-ed13f5be7677.png)
(The new Google stock icon is the shadow.)

This will affect both `music-note` and `music-note-bluetooth`, so I've updated those four icons:
![image](https://user-images.githubusercontent.com/1015040/41494329-bfc91824-70df-11e8-9dcf-b1c4a56d9eb1.png) ![image](https://user-images.githubusercontent.com/1015040/41494331-c8317cea-70df-11e8-8742-15f3b88b953e.png)
![image](https://user-images.githubusercontent.com/1015040/41494339-ece3343e-70df-11e8-8213-669f571051ef.png) ![image](https://user-images.githubusercontent.com/1015040/41494342-f4e092c6-70df-11e8-8e85-339e23b71fcb.png)

It also affects `music-note-plus`:
![image](https://user-images.githubusercontent.com/1015040/61505345-7857cd80-a9ac-11e9-906f-99c8d17b019a.png)

---

Second, the manuscript lines through all the existing note variations, with the addition of them not matching Google's new style, had me recreate all of them. I also included the dotted variations of each.

![image](https://user-images.githubusercontent.com/1015040/41494558-bcd98100-70e2-11e8-86ac-d2b20959709a.png) ![image](https://user-images.githubusercontent.com/1015040/41494560-c5edee7a-70e2-11e8-90e0-db35fba1a7e1.png)
![image](https://user-images.githubusercontent.com/1015040/41494565-d6766b5a-70e2-11e8-8d0d-e55da5d92306.png) ![image](https://user-images.githubusercontent.com/1015040/41494574-ea057102-70e2-11e8-9938-b923eb0037bf.png)
![image](https://user-images.githubusercontent.com/1015040/41494577-fb5bedaa-70e2-11e8-8a91-8a787878b386.png)![image](https://user-images.githubusercontent.com/1015040/41494579-059ed17e-70e3-11e8-8a5f-f8b74a840dc5.png)
![image](https://user-images.githubusercontent.com/1015040/41494581-1283b5b2-70e3-11e8-8542-5cac4ddb300e.png) ![image](https://user-images.githubusercontent.com/1015040/41494583-1ae58ca8-70e3-11e8-9d50-c8e9f3a893bf.png)
![image](https://user-images.githubusercontent.com/1015040/41494588-24b1514a-70e3-11e8-9a56-532d5f3117ec.png) ![image](https://user-images.githubusercontent.com/1015040/41494593-30622988-70e3-11e8-8f10-83fc7fda528d.png)

---

Here's additional outline versions of Google's stock `music-note` icon that we're missing:
![image](https://user-images.githubusercontent.com/1015040/61505513-0e8bf380-a9ad-11e9-8ebb-72506006e746.png)![image](https://user-images.githubusercontent.com/1015040/61505524-19468880-a9ad-11e9-9172-52812828d040.png)

---

In line with the notes, I've created and added the accidental symbols:
![image](https://user-images.githubusercontent.com/1015040/41494797-29762dfa-70e7-11e8-9f96-7caa8e1f9d53.png) ![image](https://user-images.githubusercontent.com/1015040/41494799-34623fe2-70e7-11e8-9285-e2ed3f30fe99.png)
![image](https://user-images.githubusercontent.com/1015040/41494803-40146ec8-70e7-11e8-8e84-69126c9dcb8b.png) ![image](https://user-images.githubusercontent.com/1015040/41494805-4929d1a6-70e7-11e8-884d-c8cb98381d7f.png)
![image](https://user-images.githubusercontent.com/1015040/41494808-54d52fd2-70e7-11e8-878e-edf3df2e007b.png)

---

I've also added the rest symbols:
![image](https://user-images.githubusercontent.com/1015040/61505293-4a728900-a9ac-11e9-9f12-0a98eb00353e.png)![image](https://user-images.githubusercontent.com/1015040/61505264-362e8c00-a9ac-11e9-9a2a-6b6f9e2683bd.png)
![image](https://user-images.githubusercontent.com/1015040/61505274-3fb7f400-a9ac-11e9-81bb-58b295b1b343.png)![image](https://user-images.githubusercontent.com/1015040/41495082-1a906552-70ed-11e8-8ddc-bec140ffc276.png)
![image](https://user-images.githubusercontent.com/1015040/41495085-24a608d0-70ed-11e8-9b7d-aa99bef3e4cf.png)

---

~And lastly, the clefs:~
See https://github.com/Templarian/MaterialDesign/issues/3263#issuecomment-513048885 for much better clefs made by @JapanYoshi.

**Comment by MrGrigri** [comment]
This might be more than needed as I don't see anyone using MDI as a form of writing music.

**Comment by Templarian** [comment]
Could be useful in an application for music though. Agreed with all of these, will try and work on them this weekend.

**Comment by MrGrigri** [comment]
I believe that my issue is the inconsistencies. The `music-clef-treble` and `-base` might be 2px wide, but their shape is not right. Those two would be difficult to make Material. The `music-rest-quarter`, `-eighth`, and `-sixteenth` are drawn correctly and are not material. All of the others are great.

There are only two reasons why you'd use the variants of all of these would be to teach music or to compose/read music. The former could work, but in all actuality, you should teach the real symbols and not the Materialized ones. The later shouldn't ever happen with these. Nobody is going to read music with these icons.

**Comment by JapanYoshi** [comment]
Fortunately I have both a musical background and a design background, so I attempted to redraw the clefs.
![clef-c](https://user-images.githubusercontent.com/8707990/60251705-64b8ca00-990c-11e9-9a06-27848d9c4587.png)
![clef-f](https://user-images.githubusercontent.com/8707990/60251707-64b8ca00-990c-11e9-9198-ec97017878fb.png)
![clef-g](https://user-images.githubusercontent.com/8707990/60251709-64b8ca00-990c-11e9-82b1-1fd9ba0c535e.png)
[clef.zip](https://github.com/Templarian/MaterialDesign/files/3333746/clef.zip)

**Comment by goyney** [comment]
Here are the three clefs from JapanYoshi, cleaned up, merged, and aligned to the grid:
![image](https://user-images.githubusercontent.com/1015040/61501681-640cd400-a99e-11e9-9bdd-c582df5b6e6b.png)![image](https://user-images.githubusercontent.com/1015040/61501691-6a9b4b80-a99e-11e9-8136-42944437e5f2.png)
![image](https://user-images.githubusercontent.com/1015040/61501697-71c25980-a99e-11e9-8edb-5c1efc09585a.png)

[clefs.zip](https://github.com/Templarian/MaterialDesign/files/3408939/clefs.zip)

**Comment by goyney** [comment]
All icons have been pre-optimized and organized since this thread is pretty large. Please see the very top of the first post for the ZIP file.

**Comment by goyney** [comment]
> The `music-rest-quarter`, `-eighth`, and `-sixteenth` are drawn correctly and are not Material.

These have been improved upon. 😄

**Comment by goyney** [comment]
Add the 3 clefs: `music-clef-treble`, `music-clef-bass`, and `music-clef-alto`.
Updated all existing icons that needed updating.

All that remains are the new additions.

**Comment by goyney** [comment]
All added! 😄
