### ISSUE TITLE
ghost-off

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#3265]
as in request for baseball-glove, I'd need the opposite of a mdi:Ghost, something with bust ;-)
using the baseball-bat root now to hit the Ghosts, but a buster would be the obvious way to go..

![schermafbeelding 2018-06-18 om 13 16 07](https://user-images.githubusercontent.com/33354141/41533244-72ae41f0-72fa-11e8-922c-b2f69d1ffd1d.jpg)

i know this can't be official, but a mdi:ghost-off might be an option?

![iur](https://user-images.githubusercontent.com/33354141/41533341-b5f5a41c-72fa-11e8-83d9-d67d76b8eebc.jpeg)

**Comment by MrGrigri** [comment]
I doubt this icon will get added. But here is the SVG if you want it.

![image](https://user-images.githubusercontent.com/4528551/41559958-e0cdc860-7302-11e8-8f5d-72b1557e9609.png)

[ghost-off.zip](https://github.com/Templarian/MaterialDesign/files/2112868/ghost-off.zip)

**Comment by hvbhome** [comment]
Should be! Magic !
Thanks 👍

**Comment by Templarian** [comment]
[![ghost-off](https://materialdesignicons.com/icon/ghost-off)](https://materialdesignicons.com/icon/ghost-off)

**Comment by hvbhome** [comment]
thx!
