### ISSUE TITLE
itch.io

### ISSUE THREAD

**Issue by momoproject** [Templarian/MaterialDesign#3266]
Would be nice to have a itch.io icon, the site is a major market place for small developers (games, assets, comics, applications and tools).

Basically a Steam for indie projects.

Some reference links:
- [Wikipedia](https://en.wikipedia.org/wiki/Itch.io)
- [itch.io](https://itch.io)

I actually have edited and made this one using their [presskit](https://itch.io/press-kit/). The SVG, if you want, is [HERE](https://drive.google.com/open?id=1wZQYLoJe6DUMgK-DIZI58mJy3i7Hby5V).

![itch io](https://user-images.githubusercontent.com/40412640/41633242-3f8ba248-7414-11e8-86c1-8ee7668cb75e.png)

Thanks for your time.

**Comment by Templarian** [comment]
Marking this as too specific at this time.

Eventually we're going to go back through and add a more of a general brand icon pack to fill the void (we use the rejected label + brand label to track these).
