### ISSUE TITLE
upsidedown-star

### ISSUE THREAD

**Issue by athlonit** [Templarian/MaterialDesign#3267]
A star rotated 180 degrees.

**Comment by goyney** [comment]
You can apply the `mdi-rotate-180` class to rotate any icon 180°. More information on helper methods can be found here: https://materialdesignicons.com/getting-started

**Comment by GreenTurtwig** [comment]
Yeah, we already reject horizontally flipped icons and the use cases for this suggestion are going to be extremely small at best. Thabks for the request regardless. 🦊
Closing this issue.
