### ISSUE TITLE
Bookmark remove/off

### ISSUE THREAD

**Issue by terpro** [Templarian/MaterialDesign#3268]
I'm looking for an icon to represent removing a bookmark. I know the bookmark-remove icon already exists, I am looking for a bookmark-outline icon with a line through it (Like in the star-off icon or television-off).

This is what it would look like:
![Bookmark off/remove icon](https://terrenprogramming.com/github/bookmark_remove.png)

**Comment by goyney** [comment]
I don't think that is really visually identifiable. I would suggest we keep the current pattern we have and add a minus variation to act as the opposite of our plus versions, like so:

![image](https://user-images.githubusercontent.com/1015040/41677889-9c592ae4-7497-11e8-9840-67cff4d67b9b.png) ![image](https://user-images.githubusercontent.com/1015040/41677907-a5593594-7497-11e8-8d97-8f6e535ed2e0.png)

**Source:** [bookmark-minus.zip](https://github.com/Templarian/MaterialDesign/files/2120610/bookmark-minus.zip)

**Comment by terpro** [comment]
I would like the icon with a line through it like in the image I added. I have already used the star_off icon, and this icon would provide consistency with how my product represents removing things.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/41678926-7bc0d586-749a-11e8-917f-8b0dbed19e7a.png) ![image](https://user-images.githubusercontent.com/1015040/41678914-723a8fa2-749a-11e8-88c7-16aa459572f3.png)

**Source:** [bookmark-off.zip](https://github.com/Templarian/MaterialDesign/files/2120669/bookmark-off.zip)

**Comment by terpro** [comment]
Looks fantastic!

**Comment by Templarian** [comment]
Added all 4. 😺
