### ISSUE TITLE
Fix headphones-off and headset-off

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3269]
For some reason, `headphones-off` and `headset-off` are the two of four icons with the "off" strikethrough going the opposite direction. I have fixed these two here:

![image](https://user-images.githubusercontent.com/1015040/41679837-8232ad38-749d-11e8-9d78-b7e8ee0803d8.png) ![image](https://user-images.githubusercontent.com/1015040/41679861-a013bfa4-749d-11e8-84ee-ff6a4c4d95dd.png)

**Source:** [Headphones and Headset.zip](https://github.com/Templarian/MaterialDesign/files/2120758/Headphones.and.Headset.zip)

**Comment by goyney** [comment]
I feel we should be consistent.

**Comment by PeterShaggyNoble** [comment]
Google have a `headphones-off` icon with the slash correctly angled so we should probably go with that.

**Comment by goyney** [comment]
I will update the globes later this evening and create a new post for them.

**Comment by MrGrigri** [comment]
I believe that `earth-off`, `earth-box-off`, and `headset-off` should remain with the slash going from the top right corner to the bottom left so that the detail is more visible.

**Comment by MrGrigri** [comment]
We do not have to be consistent with everything. Especially if it's for the better understanding of the icon.

**Comment by goyney** [comment]
I disagree. The whole purpose of the Material guidelines are to keep things consistent. Additionally, the flipped versions above are not any more or less identifiable, so we should err on the side of consistency.

**Comment by GreenTurtwig** [comment]
While I agree we should flip these, we definitely shouldn't do that for the `earth` icons. Having that detail is important to recognising the icon.

**Comment by Templarian** [comment]
Done. 😺

**Comment by MrGrigri** [comment]
Thanks for the compromise on the `headset-off`. ;)
