### ISSUE TITLE
package-variant-closed

### ISSUE THREAD

**Issue by crsosa** [Templarian/MaterialDesign#327]
Not the cloud box logo, but an actual box

- [ ] package-variant-closed

**Comment by Templarian** [comment]
Search `package` on the site. Is that what you meant?

**Comment by crsosa** [comment]
Oh! I didn't see them, but it would be more representative if the box, or package is closed.

**Comment by Templarian** [comment]
Like the http://materialdesignicons.com/icon/cube or http://materialdesignicons.com/icon/cube-outline ?

**Comment by crsosa** [comment]
Yes, but I think you could make the flaps visible drawing a line in the top. my guess

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/package-variant-closed
