### ISSUE TITLE
french doors, double doors, or sliding doors

### ISSUE THREAD

**Issue by HanOnGit** [Templarian/MaterialDesign#3270]

**Comment by GreenTurtwig** [comment]
This is going to be difficult to design as an icon, we would need both `closed` and `open` variants. While `closed` should be fine, `open` would have to be scaled down a bit and also doesn't represent open double doors very well as you can see below. I'd suggest just sticking with the regular door icons.

![image](https://user-images.githubusercontent.com/15905797/41714040-f5c078f8-7546-11e8-851e-8b1b0e95baf9.png)

**Comment by HanOnGit** [comment]
How does it look with just one side open?
________________________________

**Comment by goyney** [comment]
After some discussion, we're going to go ahead and close this issue. Sliding doors are difficult to represent in a small 24x24 grid in their various states. Additionally, the `door` icons can be used to represent an entryway.
