### ISSUE TITLE
spreadsheet missing from MaterialDesign-Webfont

### ISSUE THREAD

**Issue by arnaudvalle** [Templarian/MaterialDesign#3271]
Hello there 👋 

Looks like the `spreadsheet` icon is in the [repo](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/spreadsheet.svg) but is not in the [Webfont](https://github.com/Templarian/MaterialDesign-Webfont/blob/master/scss/_variables.scss#L784).

Any chance of fixing it?

Many thanks,

**Comment by goyney** [comment]
Duplicate of: https://github.com/Templarian/MaterialDesign/issues/1966

**Comment by PeterShaggyNoble** [comment]
Note that this is development repo, not the production repo - you can find that [here](https://github.com/Templarian/MaterialDesign-SVG).

**Comment by arnaudvalle** [comment]
Ok thanks for the clarification 👍
