### ISSUE TITLE
printer-bluetooth

### ISSUE THREAD

**Issue by stillie** [Templarian/MaterialDesign#3272]
May I suggest a bluetooth printer icon?

I was thinking something like a printer with the bluetooth icon overlaying the top left corner of the printer, where the printer is still visible but has the bluetooth icon overlaying it.

Something like this:
![image](https://user-images.githubusercontent.com/8945355/41765322-07194e28-7604-11e8-91e0-4f33f9f37e1f.png)

**Comment by MrGrigri** [comment]
Would [printer-settings](https://materialdesignicons.com/icon/printer-settings) not work for you? All settings icons in Material Design get the three dots at the bottom. Also, the printer icon is too wide to just stick the Bluetooth icon next to it. What about `printer-wireless`, would that work?

![printer-settings](https://materialdesignicons.com/icon/printer-settings) ![image](https://user-images.githubusercontent.com/4528551/41782796-780485d2-75f8-11e8-86f1-c7f1451fcc5b.png)

[printer-wireless.zip](https://github.com/Templarian/MaterialDesign/files/2128035/printer-wireless.zip)

**Comment by MrGrigri** [comment]
We feel that this icon will not work. please refer to #3275 as we feel that would represent both Bluetooth and wireless.
