### ISSUE TITLE
Material icons codes

### ISSUE THREAD

**Issue by chodik** [Templarian/MaterialDesign#3273]
Hi, i can not find material icon codes anywhere. Can you help ?
I need code of this icon **message-text-outline**

Here is link https://materialdesignicons.com/icon/message-text-outline

Thanks

**Comment by PeterShaggyNoble** [comment]
If you mean the codepoints, have a look at the `preview.html` "cheatsheet" included with the webfont and also [available on the CDN](https://cdn.materialdesignicons.com/2.4.85/).

**Comment by chodik** [comment]
Thank i try it but not work. I want add this in to Xenforo 2.0.7.

I add this  <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">
in to PAGE CONTAINER in to head section.

And this in to EXTRA.css

.node--forum .node-icon i:before{
    font-family: 'Material Icons';
    content: "\e0c9";}

This icon of message work  \e0c9

But i need this icon message-text-outline  and code of this icon not work for me, nothing show,

Can you help ?

**Comment by MrGrigri** [comment]
That link is for the Official Google Material Design Icons, not this community-driven (and older) repository.

**Comment by chodik** [comment]
Ah ok, so can you tell me how i can fix it ? Or what code i must use. Thanks

**Comment by MrGrigri** [comment]
I will direct you to our [getting started](https://materialdesignicons.com/getting-started) page.

**Comment by chodik** [comment]
I try it, propably i must do it bad.  https://xenforo.com/community/threads/using-custom-icons-for-node-icons.142002/

I want do this same icon like this  https://www.themehouse.com/xenforo/2/themes/ui-x/demo

I have in head this lines

` <link href="https://fonts.googleapis.com/icon?family=Material+Icons"rel="stylesheet">`
`<link href="css/materialdesignicons.min.css" media="all" rel="stylesheet" type="text/css" />`

In ftp i upload pack of your fonts in to folder /fonts

in EXTRA.CLASS i add 

```
.node--forum .node-icon i:before{
    font-family: 'Material Icons';
    content: "\e0c9";}
```

**Comment by goyney** [comment]
@chodik You are still linking to the official Google Material Icons repository. If you want to use that repository, only the icons found [on their website](https://material.io/tools/icons/?style=baseline) are available for your use.

This repository is a community-driven one in which we have extended Google's default. If you want to use our repository (which I am assuming you do), then you need to [download our icon package](https://github.com/Templarian/MaterialDesign-Webfont/archive/master.zip), [install it via npm](https://www.npmjs.com/package/@mdi/font), or use our [CDN](https://cdn.materialdesignicons.com/2.4.85/).

**Comment by chodik** [comment]
Thank you for your explanation, but I can not do this myself.
It's too complicated for me. I need to replace just one icon that's all.

I have no experience with the installation you describe.

**Comment by chodik** [comment]
Thank you for your explanation, but I can not do this myself.
It's too complicated for me. I need to replace just one icon that's all.

I have no experience with the installation you describe

**Comment by Templarian** [comment]
You can use our CDN as said, but all of our code-points are different. The font family is `Material Design Icons`.

`//cdn.materialdesignicons.com/2.4.85/css/materialdesignicons.min.css`

http://cdn.materialdesignicons.com/2.4.85

**Comment by chodik** [comment]
Thanks for help. But i cant do this. I must find anyone who can and do this for me.

Best solution will be for me is add webfont link in to code to your icons.

And in this code in my css i add any code number from  [](http://cdn.materialdesignicons.com/2.4.85)

Other variants for me is most complicated  :D
