### ISSUE TITLE
printer-wireless

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3275]
In response to #3272, I'm putting my contribution for a `printer-wireless` icon here.

![image](https://user-images.githubusercontent.com/4528551/41782796-780485d2-75f8-11e8-86f1-c7f1451fcc5b.png)

[printer-wireless.zip](https://github.com/Templarian/MaterialDesign/files/2128035/printer-wireless.zip)

**Comment by Templarian** [comment]
[![printer-wireless](https://materialdesignicons.com/icon/printer-wireless)](https://materialdesignicons.com/icon/printer-wireless)
