### ISSUE TITLE
Icon for Hi-Res, Low-Res, Mid-Res label

### ISSUE THREAD

**Issue by donutydonuts** [Templarian/MaterialDesign#3276]
Hi, I was wondering if we have pictures for the labels 'Hi-Res' / 'Low-Res' / 'Mid-Res'. Or maybe a High/Low/Mid label?

**Comment by goyney** [comment]
We have HQ: https://materialdesignicons.com/icon/quality-high

![image](https://user-images.githubusercontent.com/1015040/41946499-d0b5a32e-7980-11e8-9667-49f5eb210c3b.png) ![image](https://user-images.githubusercontent.com/1015040/41946503-dba3897c-7980-11e8-8ec4-2fc70bc31107.png)

**Source:** [quality.zip](https://github.com/Templarian/MaterialDesign/files/2139397/quality.zip)

**Comment by Templarian** [comment]
@goyney Don't forget to remove any extra point data and correct any defects (fixed the issues). The `q` in `mq` was off and the `L` had a lot of extra point data (and was slightly off).

[![quality-medium](https://materialdesignicons.com/icon/quality-medium)](https://materialdesignicons.com/icon/quality-medium) [![quality-low](https://materialdesignicons.com/icon/quality-low)](https://materialdesignicons.com/icon/quality-low)

**Comment by goyney** [comment]
@Templarian 

Sorry for the 
![image](https://user-images.githubusercontent.com/1015040/41983051-fd850686-79fa-11e8-8db6-516dd78746bf.png)
icons. I blame the drinks.
