### ISSUE TITLE
google-authenticator

### ISSUE THREAD

**Issue by kkaplita** [Templarian/MaterialDesign#3278]
Google authenticator

**Comment by MrGrigri** [comment]
Because of its multi-tone palette, this icon might be hard to represent with the MD Guidelines.

**Comment by PeterShaggyNoble** [comment]
I had a look around their Authenticator repos and couldn't find a single colour version of the logo. It _does_ seem to be very reliant on the multiple shades of grey and the shadow so I don't think this one will be possible.

My first thought on seeing this request was of the `apps_policy` icon from the Extended set, but it's quite different.

![apps_policy](https://user-images.githubusercontent.com/15157491/41964971-4b05f328-79f3-11e8-9d6a-bd30f92e9f10.png)

**Comment by GreenTurtwig** [comment]
Yeah this is going to be too specific, there are loads of 2FA solutions, I use Authy myself.
`two-factor-authentication` should feet your needs instead.

[![](https://materialdesignicons.com/icon/two-factor-authentication)](https://materialdesignicons.com/icon/two-factor-authentication)
