### ISSUE TITLE
Square-edit-outline icon not working

### ISSUE THREAD

**Issue by Mish325** [Templarian/MaterialDesign#3279]
Hi,

I tried to use this icon several times but it's not displaying. But other icons are displaying fine. Here's the code.

`<i class="mdi mdi-square-edit-outline"></i>`

Am I missing something?

**Comment by PeterShaggyNoble** [comment]
Please ensure you are using the latest version of Material Design Icons; `square-edit-outline` was added in v2.3.54 and the current version is v2.4.85.

**Comment by Mish325** [comment]
Hi @jecsham,

Here's the code. Am I missing anything?

`<i class="mdi mdi-square-edit-outline color-primary"></i>`

**Comment by Mish325** [comment]
Hi @PeterShaggyNoble,

I think the version I'm using is  v2.2.43. I installed the package using ` npm install mdi`. Do I need to update the version?

**Comment by jecsham** [comment]
@Mish325 You need update
The command for install the last version is `npm install @mdi/font`

**Comment by Mish325** [comment]
@jecsham Thanks a lot. Now it's working fine 👍
