### ISSUE TITLE
Coins icon

### ISSUE THREAD

**Issue by LEONeso** [Templarian/MaterialDesign#328]
Coins demo: http://vk.cc/3KFVoe

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/coin There is an icon called coin, do you need it to be more generic not using the $ ?

**Comment by Templarian** [comment]
Oh wait, you mean multiple coins?

**Comment by derRAV3N** [comment]
I think yes, he means multiple Icons, I would also like to have a md icon like this:
![coin icon](https://cloud.githubusercontent.com/assets/12349529/7784188/c98a1f66-015c-11e5-8645-299690f9b466.png)

**Comment by LEONeso** [comment]
Yes.

**Comment by CoDEmanX** [comment]
http://www.google.com/design/icons/#ic_toll ?

**Comment by Templarian** [comment]
[![coins](https://materialdesignicons.com/icon/coins)](https://materialdesignicons.com/icon/coins)
