### ISSUE TITLE
Call platform icon

### ISSUE THREAD

**Issue by PierreClementCazon** [Templarian/MaterialDesign#3280]
Hi,

![capture](https://user-images.githubusercontent.com/36991574/41896972-4fdf87ec-7926-11e8-8859-8355274bd308.PNG)

I need an icon like that, if anyone has a few minutes.

Thank you in advance.

**Comment by GreenTurtwig** [comment]
Could you give us a use case for this icon? :fox_face:

**Comment by PierreClementCazon** [comment]
For example for VOIP software.

**Comment by GreenTurtwig** [comment]
We already have `phone-voip` and I'd suggest just using the headset icon if the page requires it.

[![](https://materialdesignicons.com/icon/phone-voip)](https://materialdesignicons.com/icon/phone-voip)

**Comment by PierreClementCazon** [comment]
That's not really what we want. Is it not possible to add the screen icon to the headset icon? It's for an online call platform.

**Comment by goyney** [comment]
After some discussion, we don't feel that this icon request would work in the library. For one, shrinking the headset down to that size doesn't follow material guidelines.

Icons should be supplementary to the context in which they exist. That isn't to say that icons can't be very specific in some situations, but we feel that the specificity between a headset and a computer monitor with a headset doesn't provide any added value.

The [`headset`](https://materialdesignicons.com/icon/headset) icon would probably be your best bet for your use case.

Closing this issue.
