### ISSUE TITLE
Heart multiple

### ISSUE THREAD

**Issue by peterpp** [Templarian/MaterialDesign#3283]
I suggest to create icon heart-multiple and maybe heart-multiple-outline. They will be analogical to file-multiple, alarm-multiple, checkbox-multiple-blank-outline, etc.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/41988284-9c860d08-7a09-11e8-8201-6d6d8016c3f5.png) ![image](https://user-images.githubusercontent.com/1015040/41988307-af48564e-7a09-11e8-9df5-94a90243c2c3.png)


**Source:** [hearts.zip](https://github.com/Templarian/MaterialDesign/files/2142177/hearts.zip)

**Comment by Templarian** [comment]
[![heart-multiple](https://materialdesignicons.com/icon/heart-multiple)](https://materialdesignicons.com/icon/heart-multiple) [![heart-multiple-outline](https://materialdesignicons.com/icon/heart-multiple-outline)](https://materialdesignicons.com/icon/heart-multiple-outline)
