### ISSUE TITLE
Roman Numerals

### ISSUE THREAD

**Issue by AkeelHaider** [Templarian/MaterialDesign#3284]

**Comment by Templarian** [comment]
We have a policy that numbers can only go from 0-9, so we could add 1-10 I think for roman numerals.

**Comment by goyney** [comment]
@Templarian Would we really need 1-10 though? Wouldn't we just need I, V, X, L, C, D, and M? You could piece the icons together then to count up pretty high. And, that is only 7 icons as opposed to 10.

**Comment by MrGrigri** [comment]
If I am not mistaken, you couldn't just piece them together as they are written together with no spaces...except for when typed, then there is only a minimal gap.

**Comment by goyney** [comment]
Depends on how the icons are designed and how the implementer kerns them, I would think.

**Comment by MrGrigri** [comment]
The problem that we'll run into with that route is with the width (e.g. 8: VIII).

**Comment by MrGrigri** [comment]
I believe that we would have to create them at 1pixel wide.

**Comment by goyney** [comment]
[![alpha-i](https://materialdesignicons.com/icon/alpha-i)](https://materialdesignicons.com/icon/alpha-i)![image](https://user-images.githubusercontent.com/1015040/53690073-8379cc00-3d31-11e9-9cfa-f140699cdd95.png)
![image](https://user-images.githubusercontent.com/1015040/53690076-896fad00-3d31-11e9-98c2-3f1aebac7535.png)![image](https://user-images.githubusercontent.com/1015040/53690077-9096bb00-3d31-11e9-95a7-ef29eda61a9a.png)
[![alpha-v](https://materialdesignicons.com/icon/alpha-v)](https://materialdesignicons.com/icon/alpha-v)![image](https://user-images.githubusercontent.com/1015040/53690078-97bdc900-3d31-11e9-8099-d8b621fbeac0.png)
![image](https://user-images.githubusercontent.com/1015040/53690080-9d1b1380-3d31-11e9-97dc-a2e7d4e504ff.png)![image](https://user-images.githubusercontent.com/1015040/53690081-a310f480-3d31-11e9-963e-264506f03411.png)
![image](https://user-images.githubusercontent.com/1015040/53690083-a99f6c00-3d31-11e9-830e-2b45a073c0be.png)[![alpha-x](https://materialdesignicons.com/icon/alpha-x)](https://materialdesignicons.com/icon/alpha-x)

[roman-numerals.zip](https://github.com/Templarian/MaterialDesign/files/2922689/roman-numerals.zip)

**Comment by goyney** [comment]
All added.
