### ISSUE TITLE
Rose/deceased/in memory of icon

### ISSUE THREAD

**Issue by Amagi82** [Templarian/MaterialDesign#3287]
Right now we lack a good icon to represent a deceased individual. A rose could represent that concept nicely, and also work for anyone who wants a flower besides the current daisy-looking google flower. 

Something like a simplified version of this could work nicely:

https://image.shutterstock.com/display_pic_with_logo/1310731/124207522/stock-vector-red-rose-124207522.jpg

In a similar vein, a tombstone icon could also be useful.

**Comment by MrGrigri** [comment]
You could always use a religious symbol (e.g. cross, Star of David, etc.)

**Comment by CoDEmanX** [comment]
Common motives for (Christian) tombstones are also: - praying hands- angels- wreaths

**Comment by MrGrigri** [comment]
Here is an option. This is probably more of a tulip than a rose, but nonetheless. 

![image](https://user-images.githubusercontent.com/4528551/42175676-7d2616d2-7de3-11e8-9e3d-e636da844d80.png) ![image](https://user-images.githubusercontent.com/4528551/42175665-722546a4-7de3-11e8-830e-ab36b8004e81.png)

[flower-rose.zip](https://github.com/Templarian/MaterialDesign/files/2156000/flower-rose.zip)

**Comment by GreenTurtwig** [comment]
Definitely a tulip. This is going to be hard to do without a top down perspective.

**Comment by PeterShaggyNoble** [comment]
We should try to avoid any overtly religious iconography for this one.

See also #1050 and #1559

**Comment by Templarian** [comment]
[![flower-tulip](https://materialdesignicons.com/icon/flower-tulip)](https://materialdesignicons.com/icon/flower-tulip) [![flower-tulip-outline](https://materialdesignicons.com/icon/flower-tulip-outline)](https://materialdesignicons.com/icon/flower-tulip-outline)

Keeping the issue opened, just adding these two.
