### ISSUE TITLE
Briefcase add/plus

### ISSUE THREAD

**Issue by KeyonLulu** [Templarian/MaterialDesign#3288]
Just like the normal briefcase icon, but with a plus, maybe inside the bag, like briefcase-check

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/42102158-1d45bc10-7b93-11e8-86dc-3ffcb27b1169.png) ![image](https://user-images.githubusercontent.com/1015040/42102169-2706b880-7b93-11e8-898b-e99f16467927.png)
![image](https://user-images.githubusercontent.com/1015040/42102186-30170614-7b93-11e8-8c9d-c3edb5367a0f.png)

**Source:** [briefcases.zip](https://github.com/Templarian/MaterialDesign/files/2150044/briefcases.zip)

**Comment by Templarian** [comment]
Can we put these in the corner? Adding them into the center might give the wrong meaning. Like medical.

**Comment by Templarian** [comment]
Added.
