### ISSUE TITLE
Reopen folder/project

### ISSUE THREAD

**Issue by silas229** [Templarian/MaterialDesign#3289]
Hi, 
it would be great if there was an icon to reopen the folder / project (oriented on the [folder-search](https://materialdesignicons.com/icon/folder-search) icon).

Like this:
![folder-reopen](https://user-images.githubusercontent.com/23215125/42104123-ba99053e-7bcb-11e8-9ab7-c53d01ddffd2.png)

**Comment by goyney** [comment]
You mean like the arrow in the circle around the clock, but on the search glass?

**Comment by silas229** [comment]
No, I just mean that the icon should look something like the folder-search icon (as shown on the sketch)

**Comment by goyney** [comment]
See also #3299.

**Comment by goyney** [comment]
We've added a variation of this idea in #3299. Closing.
