### ISSUE TITLE
message-text and message-text-ouline

### ISSUE THREAD

**Issue by mlazzari-tribecube** [Templarian/MaterialDesign#329]
Same as comment-text and comment-text-outline but using message as a base icon

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/message-text
http://materialdesignicons.com/icon/message-text-outline

**Comment by mlazzari-tribecube** [comment]
Thanks, that's awesome! When am I going to find the updated webfont?

2015-05-06 3:52 GMT+02:00 Austin Andrews <notifications@github.com>:

> Closed #329 <https://github.com/Templarian/MaterialDesign/issues/329>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/329#event-297813245>.
>



-- 
Manuel Lazzari

Senior Software Engineer | Tribecube
manuel.lazzari@tribecube.com | www.tribecube.com

**Comment by Templarian** [comment]
I'm not entirely sure. Probably this weekend. I've been doing every 50 icons, but we'll see.

**Comment by mlazzari-tribecube** [comment]
Awesome, thanks!

2015-05-06 18:53 GMT+02:00 Austin Andrews <notifications@github.com>:

> I'm not entirely sure. Probably this weekend. I've been doing every 50
> icons, but we'll see.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/329#issuecomment-99536159>
> .
>



-- 
Manuel Lazzari

Senior Software Engineer | Tribecube
manuel.lazzari@tribecube.com | www.tribecube.com
