### ISSUE TITLE
thermometer  level gradient

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3291]
HI,

wouldn't it be cool (and very convenient) to have a set of thermometer icons, just like the battery percentage icons, with lets say 4 or 5 levels if filled level-scales?

right now the thermometer has a filled top part 
![schermafbeelding 2018-07-01 om 00 23 27](https://user-images.githubusercontent.com/33354141/42129446-fb7ae988-7cc4-11e8-812f-90fd6af82246.jpg)

while it should of course start getting filled-up from the bottom..... 

please consider creating that starting with a half filled bottom part (the bigger round bit) and go up in 4 or 5 stages? Up to a completely filled thermometer. And have an outline -variant.

thermometer (filled completely)
thermometer-outline (empty)
thermometer-10, -20, -30 etc

thx!
Marius

**Comment by PerthTotty** [comment]
.... like this ... ?
![thermometer-set](https://user-images.githubusercontent.com/40835272/42335018-45a4b170-807f-11e8-9eab-3469424e5588.png)
[thermometer-set.zip](https://github.com/Templarian/MaterialDesign/files/2167361/thermometer-set.zip)

**Comment by hvbhome** [comment]
Cool, and Yes , only black and white switched .

Black is the fluid in the thermometer...? Filling from bottom to top;-)

**Comment by PerthTotty** [comment]
but if you look at the original thermometer icon - the fluid is white ...
But of course, I could do it the other way ...

**Comment by hvbhome** [comment]
Wow, yes!
Make an extra one right on the top of the bottom circle ?

**Comment by PerthTotty** [comment]
![thermometer-set](https://user-images.githubusercontent.com/40835272/42336559-5e79da4a-8084-11e8-9a0a-0f1a9ec60c42.png)
[thermometer-set.zip](https://github.com/Templarian/MaterialDesign/files/2167478/thermometer-set.zip)

**Comment by hvbhome** [comment]
Magic! Thank you !👍

**Comment by goyney** [comment]
@PerthTotty Considering the original thermometer icon is a stock icon from Google, we should follow it's color scheme. The "mercury" or liquid in the thermometer should be white.

**Comment by hvbhome** [comment]
would understand if you'd comply, but google isn't always right..... ;-)

make a lines variant too?

![schermafbeelding 2018-07-05 om 22 54 26](https://user-images.githubusercontent.com/33354141/42347517-6ad2c4ec-80a6-11e8-953b-6f6dce23f72b.jpg)

next step in temperature automation ! so cool (or hot, all depending...) thx.

**Comment by goyney** [comment]
What do the lines tell you that the other thermometer doesn't? I don't feel that would be a worthwhile addition.

**Comment by hvbhome** [comment]
its just to follow the available thermometer and thermometer-lines available right now..

tbh, currently I use the 2 variants, to distinguish several settings from each other. Just gives the user this extra little variation in the frontend, that can be useful. eg, temp inside (no lines) and outside (lines)

By no means pushing.. sorry if i came over too strongly. thought it could be relatively easy to add..

**Comment by GreenTurtwig** [comment]
Also see #3197

**Comment by PerthTotty** [comment]
Just to get it right ...
Corresponding to your https://materialdesignicons.com/ the thermometer[-lines] icons are from "Austin Andrews" and not from google - or am I wrong?

**Comment by PeterShaggyNoble** [comment]
While I agree that using the black to represent the rising mercury definitely looks better and clearer, we do need to maintain consistency with Google.

Also, I definitely don't think we need that many different levels of mercury. Six, at the *very* most should be enough: empty, bulb half full, bulb full, tube one third full, tube two thirds full and completely full.

**Comment by Templarian** [comment]
I really think this is far too specific for a thermometer icon as it's all relative. Maybe a thermometer alert?

**Comment by PerthTotty** [comment]
like this?
![thermometer-alert](https://user-images.githubusercontent.com/40835272/42805986-8ed775e4-89ad-11e8-91b6-42fa7fd37a3c.png)
[thermometer-alert.zip](https://github.com/Templarian/MaterialDesign/files/2200853/thermometer-alert.zip)

**Comment by hvbhome** [comment]
> thermometer icon as it's all relative. @Templarian 

as an example ive added this screenshot with customized colorings on the same icon. How much more insightful would it be if an icon with changing level would be an option. Especially considering it will rise another 10 degrees again today, and the difference between these 2 alone will be more than 15  degrees celsius

![schermafbeelding 2018-07-17 om 10 45 53](https://user-images.githubusercontent.com/33354141/42806527-f4ff48dc-89ae-11e8-9a88-724fb189edc9.jpg)



thats exactly why this icon in several stages could be of such added value, indicating in one glance the relative temp, and indeed if its nearing the alert zone.
Just as with the battery level.

@PerthTotty 
very nice indeed 👍

**Comment by goyney** [comment]
@PerthTotty I think having the exclamation point in the thermometer isn't as recognizable at smaller implementations of the icon. What about putting the point next to the thermometer, like `account-alert` or `disc-alert`?

**Comment by PerthTotty** [comment]
Do you really think that this would make it more recognizable?

**Comment by GreenTurtwig** [comment]
Yes, it definitely makes it more recognisable. Also it's best to stay consistent with other icons.

[![](https://user-images.githubusercontent.com/15905797/42823274-17491dd4-89d5-11e8-94f4-8e73ec9c3a1c.png)](https://github.com/Templarian/MaterialDesign/files/2202026/thermometer-alert.zip)

**Comment by PerthTotty** [comment]
But if you take a look at https://materialdesignicons.com/ and search for "alert" you'll see that 11 of 12 icons by google have a central exclamation mark. Only "disc-alert" has it place on the right ...

**Comment by MrGrigri** [comment]
I agree with @GreenTurtwig and @goyney about the placement of the exclamation. At 1x the exclamation inside the thermometer is unrecognizable. We should also keep the mercury white as well to stay consistent with Google's icon; even if it doesn't look as good. Maybe Google will oneday become consistent and make up their mind as to what the `thermometer` icon should look lke.

I do feel that we should only have three levels and one alert. `thermometer-low`, `thermometer`, and `thermometer-high`.

![image](https://user-images.githubusercontent.com/4528551/42835269-a32e78f0-89b5-11e8-834c-7bee8034a84a.png) ![thermometer](https://materialdesignicons.com/icon/thermometer)  ![image](https://user-images.githubusercontent.com/4528551/42835291-aef976da-89b5-11e8-9e56-7092d08eab99.png) ![image](https://user-images.githubusercontent.com/4528551/42835527-44fbd074-89b6-11e8-903b-bfd31fb876ca.png)

[thermometer.zip](https://github.com/Templarian/MaterialDesign/files/2202733/thermometer.zip)

**Comment by CoDEmanX** [comment]
Is the exclamation mark the same height in other icons? Feels like it should be a little taller

**Comment by DankRadon** [comment]
Here is my version that has an inverse fill level...

<img width="326" alt="thermomter-10--100" src="https://user-images.githubusercontent.com/30132107/44305493-30fd3300-a33e-11e8-86cc-249ee5250a88.png">

**thermomter-10**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v0V9.9h1.8v0.9v0c0.5,0.2,1,0.5,1.3,1c0.3,0.4,0.5,1,0.5,1.6
	C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-20**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v0v-0.7V9.9V9h1.8v0.9v0.3v0.7v0c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-30**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1V8.1h1.8v1.7v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-40**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1V7.3h1.8v2.5v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-50**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1V6.3h1.8v3.5v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-60**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V5.4h1.8v0.4v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-70**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V4.5h1.8v1.3v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-80**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V4V3.6h1.8V4v1.8v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-90**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V4V2.7h1.8V4v1.8v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-100**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V4V1.8h1.8V4v1.8v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**Comment by goyney** [comment]
All of our existing thermometers have been inverted so the "mercury" is the filled area. Also added the `high` and `low` variants.

[![thermometer-low](https://materialdesignicons.com/icon/thermometer-low)](https://materialdesignicons.com/icon/thermometer-low)[![thermometer-high](https://materialdesignicons.com/icon/thermometer-high)](https://materialdesignicons.com/icon/thermometer-high)
