### ISSUE TITLE
“Error: This at-rule is not allowed here.” when trying to import Material Icons SCSS

### ISSUE THREAD

**Issue by khpeek** [Templarian/MaterialDesign#3292]
As described in [this StackOverflow question](https://stackoverflow.com/questions/51129426/error-this-at-rule-is-not-allowed-here-importing-material-design-icons-scss), I'm working on an accordion in which I'd like to toggle an icon between `<i class="mdi mdi-chevron-up"></i>` and `<i class="mdi mdi-chevron-down"></i>` based on the value of the `aria-expanded` attribute of the parent `button`.

To this end, I'd like to import Material Design's source SCSS and use `@extend .mdi-chevron-up`. I have a `scss/main.scss` file which contains the following lines:

```
@import "../node_modules/bootstrap/scss/bootstrap";
@import "../node_modules/@mdi/font/scss/variables";
@import "../node_modules/@mdi/font/scss/materialdesignicons";
```
However, if I try this I get the following error (from a `grunt watch` command):

```
>> File "scss/main.scss" changed.
Running "sass:dist" (sass) task
Error: This at-rule is not allowed here.
        @return unquote("\"\\#{$character-code}\"");
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  node_modules/@mdi/font/scss/_functions.scss 3:9           root stylesheet
  node_modules/@mdi/font/scss/materialdesignicons.scss 3:9  @import
  scss/main.scss 3:9                                        root stylesheet
Warning: Exited with error code 65 Use --force to continue.

Aborted due to warnings.
```

Here is my `Gruntfile.js`:
```
module.exports = function(grunt) {

  grunt.initConfig({
    pkg: grunt.file.readJSON('package.json'),
    sass: {                              // Task
      dist: {                            // Target
        files: {                         // Dictionary of files
          'stylesheets/main.css': 'scss/main.scss',       // 'destination': 'source'
        }
      }
    },
    watch: {
      scripts: {
        files: ['**/*.scss'],
        tasks: ['sass'],
      },
    },
  });

  grunt.loadNpmTasks('grunt-contrib-sass');
  grunt.loadNpmTasks('grunt-contrib-watch');

  grunt.registerTask('default', ['sass']);

};
```

and here are the dependencies in my `package.json`:
```
  "dependencies": {
    "@mdi/font": "^2.2.43",
    "bootstrap": "^4.1.1"
  },
  "devDependencies": {
    "grunt": "^1.0.3",
    "grunt-contrib-sass": "^1.0.0",
    "grunt-contrib-watch": "^1.1.0"
  }
}
```
Any idea how I can work around this problem? )I have actually done something similar using Materialize, in which the icons are determine by the _content_ of the `<i>` elements, which is easily changed using `::before` and `::after`, so I feel like it should be achievable with Material Design as well).

**Comment by Templarian** [comment]
That offending line is a hack to work across legacy versions of some SCSS processors, but should work in the latest ones fine. I don't really have time to check into all of this.

What version of SASS do you have installed? That `char` function is bunch of checks for legacy support and various fallbacks to support 3 different versions of SASS. 😨 

```scss
@function char($character-code) {
    @if function-exists("selector-append") {
        @return unquote("\"\\#{$character-code}\"");
    }

    @if "\\#{'x'}" == "\\x" {
        @return str-slice("\x", 1, 1) + $character-code;
    }
    @else {
        @return #{"\"\\"}#{$character-code + "\""};
    }
}

@function mdi($name) {
    @if map-has-key($mdi-icons, $name) == false {
        @warn "Icon #{$name} not found.";
        @return "";
    }
    @return char(map-get($mdi-icons, $name));
}
```

**Comment by PeterShaggyNoble** [comment]
The suggested fix on SO also seems to be to upgrade to the latest version of SCSS.

**Comment by Templarian** [comment]
Closing this out as it sounds solved?
