### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by PratikshaDalal** [Templarian/MaterialDesign#3293]
Hello,
Is it possible to create an icon for "Checkout" (related to shopping cart checkout) please?

Thanks
Pratiksha

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/42169905-4c56a0fa-7dd2-11e8-874a-5a65b3ce18cd.png)

[cart-checkout.zip](https://github.com/Templarian/MaterialDesign/files/2155597/cart-checkout.zip)

**Comment by PeterShaggyNoble** [comment]
Would none of the existing cart or basket icons (which are typically used to represent this) suit your needs?

**Comment by MrGrigri** [comment]
I believe this is just a fancier way or representing 'move to the next step' in the purchasing process, not checking out yet.

**Comment by Templarian** [comment]
Added, still not sure this is a great icon for this one. `cart-arrow-right` to be more generic.
