### ISSUE TITLE
format-font-size-increase/decrease

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3294]
![image](https://user-images.githubusercontent.com/1015040/42225126-cde5333e-7ea9-11e8-82ed-befc30b9f968.png) ![image](https://user-images.githubusercontent.com/1015040/42225159-da8a5074-7ea9-11e8-9423-e1cd5668364c.png)

[format-font-size.zip](https://github.com/Templarian/MaterialDesign/files/2159715/format-font-size.zip)

**Comment by PeterShaggyNoble** [comment]
Huh, would've sworn we already had these but, nope, just `format-size`. Should we use a `T` here instead of an `A` to be consistent with that one?

**Comment by goyney** [comment]
I don't think we should use the `T`. As a UX person, the `T` always has bugged me and I don't feel like I am alone.

This library itself includes a `format-strikethrough-variant` to not use the `T`. Everywhere else, the `A` is used, color, family, format. Google uses the `T` for size (in my opinion) because it was the only way to fit to capital letters (besides an `I`, which might not be as easily identifiable) in a 24px square.

Lastly, Word uses the `A` in this case and I feel that is much more identifiable of what the icon represents.
![screen shot 2018-07-06 at 8 34 06 am](https://user-images.githubusercontent.com/1015040/42379243-15427f98-80f8-11e8-9218-3411ff5e2dd3.png)

**Comment by Templarian** [comment]
Just in case it comes up, why I didn't change it to a caret. That may confuse it with a dropdown.

[![format-font-size-increase](https://materialdesignicons.com/icon/format-font-size-increase)](https://materialdesignicons.com/icon/format-font-size-increase) [![format-font-size-decrease](https://materialdesignicons.com/icon/format-font-size-decrease)](https://materialdesignicons.com/icon/format-font-size-decrease)

**Comment by goyney** [comment]
Exactly why I didn't use the caret. ;)
