### ISSUE TITLE
format-small-caps

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3296]
Alternatively, this may be named `format-size-reverse` and have an alias for small caps.

![image](https://user-images.githubusercontent.com/1015040/42226181-4e6b1c42-7eac-11e8-8fed-3fdf5dee570d.png)

[format-small-caps.zip](https://github.com/Templarian/MaterialDesign/files/2159795/format-small-caps.zip)

**Comment by MrGrigri** [comment]
Why not just slap a negative translate? `transform: translateX(-100%);`

**Comment by goyney** [comment]
Yeah, that makes more sense.
