### ISSUE TITLE
page-layout-marginals

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3297]
Inverse to `page-layout-body` to indicate both header and footer, as opposed to each marginal separately in `page-layout-header` and `page-layout-footer`.

![image](https://user-images.githubusercontent.com/1015040/42228249-7b10ee34-7eb1-11e8-8512-f700678fbb5a.png)

[page-layout-marginals.zip](https://github.com/Templarian/MaterialDesign/files/2159956/page-layout-marginals.zip)

**Comment by PeterShaggyNoble** [comment]
Or, simply, just `page-layout` :wink:

**Comment by goyney** [comment]
[![page-layout-header-footer](https://materialdesignicons.com/icon/page-layout-header-footer)](https://materialdesignicons.com/icon/page-layout-header-footer)
