### ISSUE TITLE
Drone similar to Airplane icon...

### ISSUE THREAD

**Issue by jfuehner** [Templarian/MaterialDesign#3298]
Would love to see the addition of a drone icon similar to the airplane icon. The current drone icon the vehicle is not very prominent...

**Comment by MrGrigri** [comment]
We do have `quadcopter` as well.

![quadcopter](https://materialdesignicons.com/icon/quadcopter)

**Comment by jfuehner** [comment]
Was kind of hoping for something that looked a bit more like a predator type drone

**Comment by MrGrigri** [comment]
It has been decided to not add this request because then it will open a rabbit-hole of other aircraft models to be added with their silhouettes. If you want the current drone icon to be modified, then open a new issue.
