### ISSUE TITLE
Project Icon...

### ISSUE THREAD

**Issue by jfuehner** [Templarian/MaterialDesign#3299]
Would love to see a project icon addition to MD. Something perhaps similar to...

https://thenounproject.com/term/projects/1327109/

**Comment by goyney** [comment]
Would something like [`folder-edit`](https://materialdesignicons.com/icon/folder-edit) not meet your needs?

**Comment by jfuehner** [comment]
Doesn't well, I guess that's doable but it doesn't really communicate what the intent is of the icon very well...

**Comment by goyney** [comment]
The only difference between `folder-edit` and your example is the inclusion of a ruler. I'm not sure I would think "projects" from either icon.

Perhaps you have another suggestion/example?

**Comment by jfuehner** [comment]
Perhaps something like this which has a time element?

https://www.google.com/imgres?imgurl=http%3A%2F%2Fwww.foresightfint.org%2FImages%2Fproject.png&imgrefurl=http%3A%2F%2Fwww.foresightfint.org%2F&docid=vMJE35pY8JaT0M&tbnid=dH16OnuZ3A-o0M%3A&vet=12ahUKEwjDy6qapIPcAhUvxVkKHaFTCB84yAEQMygwMDB6BAgBEDE..i&w=512&h=512&client=firefox-b&bih=1034&biw=933&q=project%20icon&ved=2ahUKEwjDy6qapIPcAhUvxVkKHaFTCB84yAEQMygwMDB6BAgBEDE&iact=mrc&uact=8

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/42234186-b342f710-7ec1-11e8-91c7-746bfc36fda1.png)

[folder-clock.zip](https://github.com/Templarian/MaterialDesign/files/2160320/folder-clock.zip)

**Comment by jfuehner** [comment]
I like it! Any chance the folder could be slightly open with paper showing in the folder as the last link showed? I think the paper adds a bit more to the story.

**Comment by goyney** [comment]
Material guidelines state that icons should not try to appear dimensional. All of our folder icons are in a "closed" state to follow that guideline. We do have a `folder-open` icon, but that was a conscious exception because it is such a widely and commonly used UI element.

**Comment by GreenTurtwig** [comment]
@goyney The clock shouldn't have a cut out around. Only the search, plus, minus and remove variants have that.

**Comment by goyney** [comment]
@GreenTurtwig That works fine when the underlying icons is an outline, but in this case, it didn't look very good.

**Comment by CoDEmanX** [comment]
Maybe make the clock a little larger? I noticed that Google's clock-lock icon has a clock in a different size than other icons to balance it better

**Comment by GreenTurtwig** [comment]
Yeah, it's slightly larger. I have one of the exact correct size on my laptop so I'll send it to you in the morning @goyney.

**Comment by goyney** [comment]
If you guys are talking about making the clock bigger on the alt icon, then I'll let you two have at it. I think that variation is terrible.

**Comment by GreenTurtwig** [comment]
Alright then @goyney . :+1: 

[![](https://user-images.githubusercontent.com/15905797/42627141-14ebb5d4-85c4-11e8-8cd7-635fd3e77dde.png)](https://github.com/Templarian/MaterialDesign/files/2188120/folder-clock.zip)

**Comment by CoDEmanX** [comment]
Much better!

**Comment by Templarian** [comment]
[![folder-clock](https://materialdesignicons.com/icon/folder-clock)](https://materialdesignicons.com/icon/folder-clock) [![folder-clock-outline](https://materialdesignicons.com/icon/folder-clock-outline)](https://materialdesignicons.com/icon/folder-clock-outline)
