### ISSUE TITLE
Partnership or Partners / Handshake

### ISSUE THREAD

**Issue by ugochukwu** [Templarian/MaterialDesign#330]
This icon would consist of two hands engaged in a handshake.

**Comment by RafaelPradoLima** [comment]
If it helps, font awesome already has a handshake icon perhaps you could use as inspiration: https://fontawesome.com/icons/handshake?style=solid. Looking forward for this one.

**Comment by SarinManS** [comment]
There are a lot of icon requests regarding handshake, so I didn't know where to post this.

But here's just my take on it (ver 1)

![image](https://user-images.githubusercontent.com/26505215/43710110-67733466-998e-11e8-854d-5880993e3164.png)
[handshake.zip](https://github.com/Templarian/MaterialDesign/files/2262021/handshake.zip)

**Comment by goyney** [comment]
Those are some pretty long proximal phalanges. :)

I think there is too much detail in that icon, @SarinManS. I'd try removing as much extra detail around the fingers as possible.

**Comment by SarinManS** [comment]
Made a little adjustments here... don't if it completely works though
Ver 2
![image](https://user-images.githubusercontent.com/26505215/43759707-cb60d31e-9a3f-11e8-8733-8122fd2fc951.png)

A little of both in this one
Ver3
![image](https://user-images.githubusercontent.com/26505215/43759822-231822ec-9a40-11e8-9e2b-437f9ff677c1.png)

**Comment by PeterShaggyNoble** [comment]
We could alternatively use or modify Google's new `super chat for good` icon for this.

[![super chat for good](https://user-images.githubusercontent.com/15157491/44277808-c667cc80-a243-11e8-8520-629e25b708df.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by goyney** [comment]
The `charity` icon (super-chat-for-good) was added. @ugochukwu Does this icon work for your use case?

**Comment by vorant94** [comment]
so, how is it going with handshake icon now?

**Comment by CoDEmanX** [comment]
I thought there was an icon by Google, but I can't find it. Maybe I'm confusing it with super-chat-for-good or volunteer-activism...

![grafik](https://user-images.githubusercontent.com/1309249/62691373-d6d20380-b9ce-11e9-97ed-e62de453476c.png)

**Comment by flaviomsb** [comment]
> The `charity` icon (super-chat-for-good) was added. @ugochukwu Does this icon work for your use case?

First off, the icon library is amazing. 

The issue with "charity" is the heart shape that expresses a different idea from a "closed deal".  

Could you please re-open this?

**Comment by goyney** [comment]
This is reopened, but I'm putting the Needs More Info tag on it, which will slate it to be closed again if we can't make more progress on what this should look like and how it will work in the Material style. None of the proposed contributions so far meet those requirements, so if you can provide some other examples of what "partnership" might look like, please comment back with those suggestions.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/66959251-2fed9180-f027-11e9-8ef2-15ded1e52df9.png)

[handshake.zip](https://github.com/Templarian/MaterialDesign/files/3736404/handshake.zip)

**Comment by MrGrigri** [comment]
Or with smaller wrist corners

![image](https://user-images.githubusercontent.com/4528551/66959513-c6ba4e00-f027-11e9-9830-531a6bb82170.png)

---

[handshake-v2.zip](https://github.com/Templarian/MaterialDesign/files/3736415/handshake-v2.zip)

**Comment by MrGrigri** [comment]
Added:

![handshake](https://materialdesignicons.com/icon/handshake)
