### ISSUE TITLE
University OR College Icon

### ISSUE THREAD

**Issue by IbadurRehman14** [Templarian/MaterialDesign#3300]
Hello there
I would like to suggest a icon for University or College.

![university-icon](https://user-images.githubusercontent.com/40762312/42262073-c2ddb554-7f87-11e8-8a62-f99428c0f226.png)

**Comment by MrGrigri** [comment]
Would `school` not work for you? 

![school](https://materialdesignicons.com/icon/school)

**Comment by PeterShaggyNoble** [comment]
Duplicate of #2173 and #3282
