### ISSUE TITLE
map legend

### ISSUE THREAD

**Issue by PerthTotty** [Templarian/MaterialDesign#3302]
I'ld like to suggest an icon for **map legend**
(This was requested long time ago and closed without a result)

![map-legend](https://user-images.githubusercontent.com/40835272/42288424-ebf8a808-7fba-11e8-9218-c984e5c7983e.png)

[map-legend.zip](https://github.com/Templarian/MaterialDesign/files/2163898/map-legend.zip)

**Comment by MrGrigri** [comment]
I love this idea.

**Comment by PeterShaggyNoble** [comment]
I really like this one too, definitely better than the suggestions I pulled from The Noun Project for #2529.

Out of curiousity, though, how would it look with the legend in the map's left-hand panel?

**Comment by GreenTurtwig** [comment]
I'm still more a fan of `format-list-bulleted-type` personally.

**Comment by PerthTotty** [comment]
A left and a right version ...
![map-legend-left](https://user-images.githubusercontent.com/40835272/42374727-5e3cbf12-8119-11e8-91f4-cbf77d979127.png)
[map-legend.zip](https://github.com/Templarian/MaterialDesign/files/2170103/map-legend.zip)

**Comment by PeterShaggyNoble** [comment]
Hmm ... can't decide between the 2 now! :laughing: But I think I'm leaning towards the original.

By the way, you can use [the Sandbox](https://petershaggynoble.github.io/MDI-Sandbox/)'s [preview generator](https://petershaggynoble.github.io/MDI-Sandbox/preview/) to create previews of your icons.

**Comment by PerthTotty** [comment]
cool - thanks

**Comment by MrGrigri** [comment]
I believe in left-to-right languages like English, the legend should be on the left. And then for right-to-left languages like Arabic, they can just rotate it 180deg. 

As a side note, @PerthTotty we have a couple of tools for creating an image for previews. 

* [New MDI site](http://dev.materialdesignicons.com/contribute/github)
* @PeterShaggyNoble [site](https://petershaggynoble.github.io/MDI-Sandbox/preview)

![image](https://user-images.githubusercontent.com/4528551/42386838-dd44601a-80fd-11e8-9251-f2c860f1876c.png)

**Comment by Templarian** [comment]
[![map-legend](https://materialdesignicons.com/icon/map-legend)](https://materialdesignicons.com/icon/map-legend)

@PerthTotty Once you hit 5 icons, I'll switch these form the shared contributor account (I or one of the others will create an issue to track this when it happens).
