### ISSUE TITLE
swiss official / governmental use

### ISSUE THREAD

**Issue by PerthTotty** [Templarian/MaterialDesign#3303]
I'ld like to suggest an icon for swiss official or governmental use
(This icon corresponses to the rules (CD-Bund) of Federal Chancellery [FCh])

![swiss-official](https://user-images.githubusercontent.com/40835272/42289592-ab27d866-7fc0-11e8-89c5-f510d86b3a65.png)

[swiss-official.zip](https://github.com/Templarian/MaterialDesign/files/2163998/swiss-official.zip)

**Comment by MrGrigri** [comment]
I believe this is going to fall under the same guidelines as #3246.

**Comment by PeterShaggyNoble** [comment]
Also, outside currencies, we try to avoid adding region-specific icons like this; we'd need to start adding the equivalent for every country if we added this one.

**Comment by PerthTotty** [comment]
okay
