### ISSUE TITLE
layers-outline

### ISSUE THREAD

**Issue by PerthTotty** [Templarian/MaterialDesign#3304]
... as used by google in e. g. google maps mobile

![layers-outline](https://user-images.githubusercontent.com/40835272/42290687-1ef5f060-7fc7-11e8-88da-10fb37312f9b.png)

[layers-outline.zip](https://github.com/Templarian/MaterialDesign/files/2164102/layers-outline.zip)

**Comment by PeterShaggyNoble** [comment]
Available [here](https://material.io/tools/icons/?search=layers&icon=layers&style=outline).
