### ISSUE TITLE
threema

### ISSUE THREAD

**Issue by PerthTotty** [Templarian/MaterialDesign#3305]
threema IM

![threema](https://user-images.githubusercontent.com/40835272/42322852-471521e6-805e-11e8-99e9-6496ee151c0d.png)
[threema.zip](https://github.com/Templarian/MaterialDesign/files/2166503/threema.zip)

**Comment by GreenTurtwig** [comment]
Duplicate of https://github.com/Templarian/MaterialDesign/issues/3224
Please do a search before creating an issue. 🦑

**Comment by PerthTotty** [comment]
Sorry

**Comment by GreenTurtwig** [comment]
No worries. :-)
