### ISSUE TITLE
Add Designer cheatsheet

### ISSUE THREAD

**Issue by SimonFricker** [Templarian/MaterialDesign#3306]
As a designer I want to view all icons on a webpage so that I can copy the symbol and use it in my design software. 

Something like this:
https://fontawesome.com/cheatsheet?from=io

Allows designers to quickly copy icons and use it in their designs when using the font installed on the system.

**Comment by GreenTurtwig** [comment]
We have one available here: https://materialdesignicons.com/cdn/2.4.85
🐈

**Comment by SimonFricker** [comment]
Its very hard to find, could you add a link on the homepage?

**Comment by PeterShaggyNoble** [comment]
It's also included with the font download as `preview.html`.

**Comment by SimonFricker** [comment]
Can you allow users to copy the icon from the homepage?

**Comment by PeterShaggyNoble** [comment]
@SimonFricker, active development on the current version of the site has ceased in favour of a brand new site coming soon, which will include many new features.

In the meantime, you can make use of `preview.html`, the copy on the CDN or [the Sandbox](https://petershaggynoble.github.io/MDI-Sandbox/).

**Comment by Templarian** [comment]
Added a shortcut at the very top of the site to the CDN's cheatsheet.
