### ISSUE TITLE
security-account outline

### ISSUE THREAD

**Issue by ziyafenn** [Templarian/MaterialDesign#3307]
Hey guys. Would be great if someone would add the alternative, outlined version for `security-account` icon.

I made it in Sketch, here is an example:
![team](https://user-images.githubusercontent.com/314302/42346643-a4a18224-80a3-11e8-8957-1fcbda2ef958.png)

Thanks in advance.

**Comment by PerthTotty** [comment]
![security-account-outline](https://user-images.githubusercontent.com/40835272/42369982-dd7f1cba-810b-11e8-9a75-18bfea96e377.png)
[security-account-outline.zip](https://github.com/Templarian/MaterialDesign/files/2169714/security-account-outline.zip)

**Comment by GreenTurtwig** [comment]
@PerthTotty Thanks for your contribution, however outlines must be 2px wide. Also as the existing `security-account` icon was based on `account-circle` it only makes sense to base the outlined variant off it to be consistent.

[![](https://user-images.githubusercontent.com/15905797/42373792-e41ccf48-810d-11e8-9c5a-683f4402bd60.png)](https://github.com/Templarian/MaterialDesign/files/2170043/security-account-outline.zip)

**Comment by PerthTotty** [comment]
You're right - SORRY

**Comment by PeterShaggyNoble** [comment]
No apology necessary, @PerthTotty, @GreenTurtwig was just steering you in the right direction so that, hopefully, you'll become a more regular contributor here.

**Comment by Templarian** [comment]
[![security-account-outline](https://materialdesignicons.com/icon/security-account-outline)](https://materialdesignicons.com/icon/security-account-outline)

Thanks guys! And yea @PerthTotty there are hundreds [more like thousands] of icons we could use help on. Only need 5 to get a contributor account on the site.
