### ISSUE TITLE
shading

### ISSUE THREAD

**Issue by PerthTotty** [Templarian/MaterialDesign#3308]
What about a "shading" icon?
![shading](https://user-images.githubusercontent.com/40835272/42384800-40b70e76-813b-11e8-9fd5-ed966dcbea03.png)
[shading.zip](https://github.com/Templarian/MaterialDesign/files/2170883/shading.zip)

**Comment by PeterShaggyNoble** [comment]
This icon actually already exists as `texture`. Should we alias is as `shading`?

**Comment by MrGrigri** [comment]
I see `blur-linear` as more of a shade than `texture`.

**Comment by PerthTotty** [comment]
upps - sorry.
I just didn't see texture ...

**Comment by PeterShaggyNoble** [comment]
And not forgetting `gradient`, too.
