### ISSUE TITLE
Multi Sensor

### ISSUE THREAD

**Issue by DelukaDZ** [Templarian/MaterialDesign#3309]
Just something a  found for a multie sensor icon
![fa0bbe9b-56f9-4345-8748-1ac810717fb9](https://user-images.githubusercontent.com/18242339/42417968-52773788-8296-11e8-906d-6c97db2e2fb1.png)

**Comment by DelukaDZ** [comment]
I see myself using it In hassio for a tab with all my sensors power battery motion and ping sensors

**Comment by goyney** [comment]
I'd recommend [`video-input-antenna`](https://materialdesignicons.com/icon/video-input-antenna) for your use case.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by MiguelAngelLV** [comment]
I think that icon will be perfect for me. I need a "sensors group" and this icon, with signal and emisor is very representative.
