### ISSUE TITLE
booking.com

### ISSUE THREAD

**Issue by marco-piccolino** [Templarian/MaterialDesign#331]
- ~tripadvisor~ (See #1301)
- [ ] bookingcom

**Comment by PeterShaggyNoble** [comment]
TripAdvisor SVG can be found [here](https://static.tacdn.com/img2/icons/ta_square.svg).

I think the Booking.com one might be too specific and would be covered by the more generic hotel icon.

![](https://materialdesignicons.com/icon/hotel)

**Comment by CoDEmanX** [comment]
TripAdvisor was actually my inspiration for our owl icon:

[![owl](https://materialdesignicons.com/icon/owl)](https://materialdesignicons.com/icon/owl)

**Comment by JamesCoyle** [comment]
Gonna close this one out as I can't see a way to actually make it recognisable.
