### ISSUE TITLE
Pi-Hole Icon Request

### ISSUE THREAD

**Issue by jmart518** [Templarian/MaterialDesign#3310]

**Comment by Templarian** [comment]
Closing as too niche. We generally only add brand icons for social media.

**Comment by pmontgo33** [comment]
I disagree this is too niche. You have the Kodi icon. A lot of home assistant users integrate pi hole somehow into their system, and the logo would make it look cleaner.

**Comment by Templarian** [comment]
Changed our minds. 😃 

[![pi-hole](https://materialdesignicons.com/icon/pi-hole)](https://materialdesignicons.com/icon/pi-hole)
