### ISSUE TITLE
Searching icon On Website

### ISSUE THREAD

**Issue by aligoren** [Templarian/MaterialDesign#3311]
Hi. Firstly thanks for your all effort to publish these useful icons.

I'm using MDI on my project. When I try to search for something with **"i", "ş"**, **"ğ"** or similar letters I get an error. The key event suddenly stopping. If I try with copy/paste letters it works.

So, I can't search with the Turkish keyboard characters. Also, I can't search with i. For example, I'm trying to write picture. but it convert to **pcture**

The below image explains what i'm saying.

![image](https://user-images.githubusercontent.com/4205423/42439094-8e55a74c-836a-11e8-9e4b-231a2bbb7e6c.png)

**Comment by goyney** [comment]
To be fair, none of our icons (or their aliases) have any special characters in any of them, so searching with diacritical characters won't ever really work.

Does sound like we have a script error in the search though that is preventing the input of characters.

**Comment by aligoren** [comment]
Thanks for your answer. Ok "ğ" and "ş" characters are coming from Turkish. What about "i" character? Thanks.

**Comment by Templarian** [comment]
I can probably just remove the keyboard restriction entirely to solve this. I have it primarily there since the search is very basic (the new site does not have this and will handle partial matching).

**Comment by aligoren** [comment]
Thanks. This page look better :)  http://dev.materialdesignicons.com/icons

**Comment by PeterShaggyNoble** [comment]
This seems to have been resolved.

**Comment by ozgurg** [comment]
The problem continues.
No problem on http://dev.materialdesignicons.com/icons
Look at this GIF:
![hover-card](https://user-images.githubusercontent.com/6717356/62252226-e368c180-b3fa-11e9-93d4-016371fd1202.gif)

**Comment by Templarian** [comment]
Let me remove the keyboard restriction tonight for this @ozgurg, still working on the new site (but it's mostly admin/tooling, so all the public pages are half done on the dev box).

**Comment by ozgurg** [comment]
@Templarian Thank you. I forgot to tell you. This problem happens only on Chrome.

**Comment by Templarian** [comment]
@ozgurg Fixed. I am now also treating accent characters as their non-accent. So `poínt` will be the same as `point`.

Let me know if you run into any issues. Thanks!
