### ISSUE TITLE
table-add/table-remove

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3313]
![image](https://user-images.githubusercontent.com/1015040/42460953-453ad016-836d-11e8-8e2e-ca1f717c56da.png) ![image](https://user-images.githubusercontent.com/1015040/42460967-4fc4818a-836d-11e8-92c7-f66cbee2b42b.png)

[table-add-remove.zip](https://github.com/Templarian/MaterialDesign/files/2176938/table-add-remove.zip)

**Comment by Templarian** [comment]
@goyney I think you put the plus and the x far too up and to the left. It should be down in the corner on both.

**Comment by Templarian** [comment]
@goyney Even further in the corner. Like `eye-plus`.

**Comment by Templarian** [comment]
Added.
