### ISSUE TITLE
Resize

### ISSUE THREAD

**Issue by arfeus1** [Templarian/MaterialDesign#3314]
I would like to suggest to add a missing Resize icon, like in this pictures:
[example-1](https://www.iconfinder.com/icons/325035/full_resize_icon)
[example-2](https://www.iconfinder.com/icons/614101/change-size_design_line-icon_resize_scale_scale-tool_tool_icon)

Personally, I prefer the first variant.

**Comment by Templarian** [comment]
Closed. ^ View that icon for the icon that was just added.
