### ISSUE TITLE
Broken URL website

### ISSUE THREAD

**Issue by blendsdk** [Templarian/MaterialDesign#3315]
Hi,

The following URL on the wesite is broken
https://cdn.materialdesignicons.com/2.5.94/MaterialDesignIconsDesign.zip

**Comment by Templarian** [comment]
Ooops, with yesterday's release I completely forgot to upload that file to the CDN. My bad, will do that right when I get home.

https://github.com/Templarian/MaterialDesign-SVG If you need the SVG's right now.

**Comment by blendsdk** [comment]
No worries.

**Comment by Templarian** [comment]
@blendsdk What in the design files were you using? SVG, TTF?

Rewriting this download file right now and wondering what is useful.

**Comment by blendsdk** [comment]
@Templarian Thank you. I using SVG

**Comment by davwheat** [comment]
Can we close this? It's almost a year old :P
