### ISSUE TITLE
Why the padding?

### ISSUE THREAD

**Issue by joshnoe** [Templarian/MaterialDesign#3316]
What is the purpose of the padding around the icons? Shouldn't these be cropped to the edge of the icon?

There are a few downsides to this padding. For example, it needs to now be taken into account when sizing the icons, because the actual icons are always smaller than the icon-with-padding.

FWIW I'm using these in a WPF app.

**Comment by MrGrigri** [comment]
There is no padding. The icons are centered (either visually or physically) on a 24x24-pixel artboard. This is per MD specifications. Could you please elaborate?

**Comment by MrGrigri** [comment]
Are you using the font or the SVGs?

**Comment by Templarian** [comment]
https://material.io/design/iconography/system-icons.html

The guidelines can explain better than us. They go into great detail about the grid and proportions.

**Comment by joshnoe** [comment]
In other words, there is space around the icons, they don't take up the entire 24x24-pixel artboard.

**Comment by joshnoe** [comment]
I'm using SVGs

**Comment by joshnoe** [comment]
@Templarian Thanks for this. From what I can see reading this spec, the justification is that sidebars may cover the 4 pixels around the edges of the icons.

> Icon content should remain inside of the live area, which is the region of an image that is unlikely to be hidden from view (such as when sidebars appear upon scrolling).

Seems like it would create more hassle than it's worth, but I'm sure Google knows what they're doing 😄

**Comment by Templarian** [comment]
@joshnoe https://material.io/design/iconography/system-icons.html#grid-keyline-shapes This section.

Basically to keep a consistent visual look when the icons are read horizontally or vertically. Icons are usually used in lists or in menu bars so this becomes very important.

I would recommend reading through the guidelines in more detail as they will help better integrate the MD System icons.

https://github.com/MahApps/MahApps.Metro.IconPacks Also, might want to use this if you're using WPF (not a WPF dev myself, but I know most use this).

**Comment by JamesCoyle** [comment]
If you want material design elements you can also use the Material Design XAML project which also uses our icons.
