### ISSUE TITLE
Book multiple plus

### ISSUE THREAD

**Issue by jamesotey** [Templarian/MaterialDesign#3317]
Book multiple with +.

**Comment by PerthTotty** [comment]
Like this?

![book-multiple-plus](https://user-images.githubusercontent.com/40835272/42576693-4c9f802e-8523-11e8-962e-818c40e2c4ae.png)
![book-multiple-minus](https://user-images.githubusercontent.com/40835272/42576698-4e2af680-8523-11e8-8c3a-a7c5d2803ed6.png)
![book-multiple-delete](https://user-images.githubusercontent.com/40835272/42576704-50ebd6fa-8523-11e8-9b90-cc8a88e90b6f.png)
[book-multiple.zip](https://github.com/Templarian/MaterialDesign/files/2184755/book-multiple.zip)

**Comment by jamesotey** [comment]
Yep, perfect!

**Comment by PerthTotty** [comment]
You're right - it should be named book-multiple-close ...

**Comment by Templarian** [comment]
Any `x` is called `*-remove`.

[![book-multiple-plus](https://materialdesignicons.com/icon/book-multiple-plus)](https://materialdesignicons.com/icon/book-multiple-plus) [![book-multiple-minus](https://materialdesignicons.com/icon/book-multiple-minus)](https://materialdesignicons.com/icon/book-multiple-minus) [![book-multiple-remove](https://materialdesignicons.com/icon/book-multiple-remove)](https://materialdesignicons.com/icon/book-multiple-remove)

**Comment by Templarian** [comment]
Also added `book-remove`.

**Comment by Templarian** [comment]
@PerthTotty let me know when you have 5 icons in the system and I'll setup a contributor account for you. Thanks!
