### ISSUE TITLE
restaurant

### ISSUE THREAD

**Issue by dgproductions88** [Templarian/MaterialDesign#3319]
I know there was a 'restaurant' icon request but i need the one is in material labeled as 'restaurant' no 'silverware'.

Thanks and regards

**Comment by PerthTotty** [comment]
could you add a screenshot of that icon?

**Comment by goyney** [comment]
https://material.io/tools/icons/?search=res&icon=restaurant&style=baseline

**Comment by PeterShaggyNoble** [comment]
If that is the icon being requested then this is a duplicate of #1802.

**Comment by Templarian** [comment]
Added and aliased.
