### ISSUE TITLE
Schedule Icon

### ISSUE THREAD

**Issue by dedevillela** [Templarian/MaterialDesign#332]
![icone-horario](https://cloud.githubusercontent.com/assets/3102096/7498929/be93a786-f3fa-11e4-9882-c326104142b9.png)

- [ ] calendar-clock

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/calendar-clock

**Comment by dedevillela** [comment]
Nice! When will this update be available on the WordPress Plug-in?

Kind regards,
Andre

**Comment by Templarian** [comment]
I have a couple icons left until I do a webfont update. It will probably be done by this weekend.

The Wordpress Plug-in is managed by someone else. Not sure what his plans are for keeping the plugin up to date.
