### ISSUE TITLE
content-move

### ISSUE THREAD

**Issue by kaspereden** [Templarian/MaterialDesign#3320]
There is a folder move icon, i would love a content move icon

**Comment by PerthTotty** [comment]
but how should this icon look like?

**Comment by goyney** [comment]
We have [`file-send`](https://materialdesignicons.com/icon/file-send), which is very similar. Does that work?

**Comment by kaspereden** [comment]
I thought of something like: [image-move](https://materialdesignicons.com/icon/image-move) but then more generic like content/file

**Comment by Templarian** [comment]
[![file-move](https://materialdesignicons.com/icon/file-move)](https://materialdesignicons.com/icon/file-move)
