### ISSUE TITLE
dog

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3321]
Since MDI is obviously a bunch of `cat` lovers, here's a `dog`. (I cannot believe we didn't have one!)

![image](https://user-images.githubusercontent.com/1015040/42588205-2371a0fa-850b-11e8-84ac-1d35bcb0fed5.png)

[dog.zip](https://github.com/Templarian/MaterialDesign/files/2185487/dog.zip)

**Comment by MrGrigri** [comment]
#736
