### ISSUE TITLE
Site is slow in Safari 11.1.2

### ISSUE THREAD

**Issue by lolgear** [Templarian/MaterialDesign#3322]
Site is so slow in Safari 11.1.2.
Loading is slow, search is slow, opening tags is slow.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site

New site is being built to address this. Lots of work still to do.

**Comment by Templarian** [comment]
Use the cheatsheet for now if you need faster perf.

**Comment by JivanRoquet** [comment]
Update: site is slow in Chrome v74.
Loading is slow, search is slow, opening tags is slow.

**Comment by goyney** [comment]
See: https://github.com/Templarian/MaterialDesign/issues/3322#issuecomment-404252351

**Comment by Templarian** [comment]
@JivanRoquet Yeah, it's really bad now that we're approaching 4k icons. I need to invest more time into working on the new site. Definitely still on my todo list.

**Comment by richardaum** [comment]
I'd love to help to improve performance but I don't know how. How could I be a contributor?

**Comment by Templarian** [comment]
It's gotten even worse after we broke 4k icons and are now above 4600.

@richardaum New site is fully open source: https://github.com/Templarian/MaterialDesign-Site

You can also use the chrome / firefox extension: https://chrome.google.com/webstore/detail/materialdesignicons-picke/edjaedpifkihpjkcgknfokmibkoafhme
