### ISSUE TITLE
keybase

### ISSUE THREAD

**Issue by danielkdewar** [Templarian/MaterialDesign#3323]
Example icon in Font Awesome

https://fontawesome.com/icons/keybase?style=brands

![icon_512x512 2x](https://user-images.githubusercontent.com/19851124/42672540-9809e682-8634-11e8-8567-fa57ef618894.png)

**Comment by CoDEmanX** [comment]
> Keybase is a new and free security app for mobile phones and computers. For the geeks among us: it's open source and powered by public-key cryptography.
>
> Keybase is for anyone. Imagine a Slack for the whole world, except end-to-end encrypted across all your devices. Or a Team Dropbox where the server can't leak your files or be hacked.

So a communication/social tool, but it doesn't seem to be very popular - just heard of it for the first time.

**Comment by PeterShaggyNoble** [comment]
Only ~50k downloads on Google Play so far. This one's going to be too obscure for us to add at this stage. If it does gain some traction in the future then leave a comment here and we'll revisit it.
