### ISSUE TITLE
Feature search (generic icon with loupe)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3324]
Seen the solid icon on YouTube and extracted the path. They call it feature-search, but it could also be used as generic icon to search inside stuff. I created an outline version as well:

![grafik](https://user-images.githubusercontent.com/1309249/42691183-428d298a-86a7-11e8-8489-bdbab8b6508e.png) ![grafik](https://user-images.githubusercontent.com/1309249/42691194-590dc0ca-86a7-11e8-80fd-4e10bff44305.png)

SVGs: [feature-search.zip](https://github.com/Templarian/MaterialDesign/files/2192570/feature-search.zip)

**Comment by Templarian** [comment]
Added.
