### ISSUE TITLE
Heater

### ISSUE THREAD

**Issue by haufes** [Templarian/MaterialDesign#3325]
Looking for an icon for a heater

**Comment by Templarian** [comment]
Would the `radiator` icon work for this? If not can you please link to or paste images for us to get a better idea.

[![radiator](https://materialdesignicons.com/icon/radiator)](https://materialdesignicons.com/icon/radiator)

**Comment by haufes** [comment]
I was looking for an icon for my pool heater. I was thinking about something like this
https://www.freepik.com/free-icon/fire-flaming-outline_749065.htm

**Comment by Templarian** [comment]
You mean like `fire`?

[![fire](https://materialdesignicons.com/icon/fire)](https://materialdesignicons.com/icon/fire)

**Comment by haufes** [comment]
lol, sure.

**Comment by PeterShaggyNoble** [comment]
Alias `heater` added to `radiator` and `flame` to `fire`.
