### ISSUE TITLE
Museum

### ISSUE THREAD

**Issue by kyay** [Templarian/MaterialDesign#3326]
a museum icon

**Comment by Templarian** [comment]
Can you please link to some examples of what this icon might look like.

**Comment by PeterShaggyNoble** [comment]
Would the `bank` icon not be suitable here?

![bank](https://user-images.githubusercontent.com/15157491/42733857-58f48174-8831-11e8-9531-45a174132e20.png)

**Comment by MrGrigri** [comment]
Also, check out #3114 for a gallery, picture type icon.

**Comment by goyney** [comment]
Going to close this since no further information was provided and the `bank` icon should be a suitable icon for the use case.
