### ISSUE TITLE
Search in shop

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3327]
Found in Google Maps web app: ![grafik](https://user-images.githubusercontent.com/1309249/42754214-f5d5ec22-88f3-11e8-8b60-0b3bb76e258c.png)

I used `shopping-music` for the base shape, which is slightly different from theirs, but it's close:

![grafik](https://user-images.githubusercontent.com/1309249/42754765-01f3cb80-88f6-11e8-87c5-d6dfd5b10442.png)

[shop-search.zip](https://github.com/Templarian/MaterialDesign/files/2197307/shop-search.zip)

I also tried with the loupe 1px further down, but then it loses recognizability:

![grafik](https://user-images.githubusercontent.com/1309249/42754706-cdcd7518-88f5-11e8-87fb-e649f8e8869e.png)

**Comment by MrGrigri** [comment]
Why not follow our new search standard like this? The first one looks like a lock, so I added the other handle to the second. 


![image](https://user-images.githubusercontent.com/4528551/42772044-627c35ce-88e6-11e8-84d5-0c608d2a5d9e.png) ![image](https://user-images.githubusercontent.com/4528551/42772072-7af3632a-88e6-11e8-8264-e5a67a725144.png)

[shopping-search.zip](https://github.com/Templarian/MaterialDesign/files/2198541/shopping-search.zip)

**Comment by CoDEmanX** [comment]
The first looks quite much like a lock + loupe ("search password"?). The second works better IMO, eventhough I don't like the overlap.

**Comment by goyney** [comment]
Went with the variant that matches our already existing `shopping`.
[![shopping-search](https://materialdesignicons.com/icon/shopping-search)](https://materialdesignicons.com/icon/shopping-search)
