### ISSUE TITLE
Cursor pointer icon

### ISSUE THREAD

**Issue by GRA0007** [Templarian/MaterialDesign#3328]
It seems that the proportions of the cursor-pointer icon don't look quite right. The index finger looks much too thick compared to the other fingers. On that note, it would be great to have some other cursors added such as the loading cursor (hourglass) and the suite of arrow cursors for resizing.
![image](https://user-images.githubusercontent.com/8862273/42761624-73669fe4-8951-11e8-8f8d-4e25ec6fd86f.png)

**Comment by CoDEmanX** [comment]
There's the `reminder` icon from which we could remove the knot...

![grafik](https://user-images.githubusercontent.com/1309249/42789228-546a3ad4-8964-11e8-8b14-62dcc044b43a.png)

It uses the entire 24x24 pixels however, unlike the current `cursor-pointer`. Might require some tweaking.

**Comment by PeterShaggyNoble** [comment]
Google also have a `reminders_alt` icon in the Extended set, which is just a smaller variant. We already have some [`timer-sand` icons](https://petershaggynoble.github.io/MDI-Sandbox/?filter=hourglass) which are aliased as `hourglass` as well as a myriad of [arrow icons](https://petershaggynoble.github.io/MDI-Sandbox/?categories=arrows) to choose from for "resizing".

![reminders_alt](https://user-images.githubusercontent.com/15157491/42823371-45f6170e-89d5-11e8-8eb6-38240d81de43.png)

**Comment by Templarian** [comment]
I'm all for updating with `reminder-alt` (minus the ribbon) if everyone think that looks good.

Opinions?

**Comment by MrGrigri** [comment]
Here it is with the `reminders-alt` icon.

![cursor-pointer](https://user-images.githubusercontent.com/4528551/43149147-fec2e53e-8f23-11e8-84c4-1369fd199049.png)

[cursor-pointer.zip](https://github.com/Templarian/MaterialDesign/files/2224309/cursor-pointer.zip)

**Comment by JamesCoyle** [comment]
I'm sure we already did this at some point but can't remember what issue it was in.

**Comment by Templarian** [comment]
Updated.
