### ISSUE TITLE
Evaluation Icon

### ISSUE THREAD

**Issue by dedevillela** [Templarian/MaterialDesign#333]
![icone-avaliacoes](https://cloud.githubusercontent.com/assets/3102096/7498998/327de198-f3fb-11e4-9a29-8de0eda32737.png)

**Comment by CoDEmanX** [comment]
Looks like clipboard + share to me.
Does this work for you?
https://materialdesignicons.com/icon/clipboard-check

Or maybe a combination of chart-line and a check mark?

**Comment by PeterShaggyNoble** [comment]
I believe `clipboard-pulse` and/or `clipboard-pulse-outline` should fulfil this request so going to close it out.

[![clipboard-pulse](https://user-images.githubusercontent.com/15157491/36682362-c6424b44-1b12-11e8-8741-89b765ec38aa.png)](https://materialdesignicons.com/icon/clipboard-pulse) [![clipboard-pulse-outline](https://user-images.githubusercontent.com/15157491/36682405-eee2bb56-1b12-11e8-828d-788c09f7932f.png)](https://materialdesignicons.com/icon/clipboard-pulse-outline)
