### ISSUE TITLE
Contribution: MIDI Icon

### ISSUE THREAD

**Issue by JeffersonBledsoe** [Templarian/MaterialDesign#3330]
Commonly used in music apps.

I based this off the settings_input_svideo icon currently in the repo and adapted it to be a MIDI icon

![midi_material_icon](https://user-images.githubusercontent.com/30210785/42787261-a4bf5fd6-8951-11e8-8df6-271c7329cb81.png)
[Midi_Material_Icon.svg.zip](https://github.com/Templarian/MaterialDesign/files/2199555/Midi_Material_Icon.svg.zip)

**Comment by Templarian** [comment]
Already exists `midi-port`

**Comment by GreenTurtwig** [comment]
We already have `midi-port`. 🐈
