### ISSUE TITLE
clipboard-text-outlined

### ISSUE THREAD

**Issue by buntupana** [Templarian/MaterialDesign#3331]

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/42825742-e8353b20-899f-11e8-9337-bd617a01bb74.png)

[clipboard-text-outline.zip](https://github.com/Templarian/MaterialDesign/files/2202196/clipboard-text-outline.zip)

**Comment by Templarian** [comment]
Need to simplify it more with just two lines of text.

[![clipboard-text-outline](https://materialdesignicons.com/icon/clipboard-text-outline)](https://materialdesignicons.com/icon/clipboard-text-outline)

**Comment by PeterShaggyNoble** [comment]
Google's `clipboard-outline` is slightly different to ours: https://material.io/tools/icons/?search=assignment&icon=assignment&style=outline

**Comment by MrGrigri** [comment]
All of their clipboard-outline-*icons are different.
