### ISSUE TITLE
butterfly

### ISSUE THREAD

**Issue by pyrosmiley** [Templarian/MaterialDesign#3332]
Didn't see an open issue for this, and -- to my surprise!-- there's not really anything similar yet. Didn't have anything fancy in mind, but here's a couple examples that were along what I was expecting. 
![environmentalsvg-01-512](https://user-images.githubusercontent.com/11056798/42866252-ad67c322-8a31-11e8-9236-a20a52bc61fb.png)
and
![butterfly_icon_ noun_project svg](https://user-images.githubusercontent.com/11056798/42866266-b4ea17e4-8a31-11e8-90ff-8bcfb09c67ef.png)

Sadly I have absolutely no experience making icons or I'd make one myself.

**Comment by PerthTotty** [comment]
![butterfly](https://user-images.githubusercontent.com/40835272/43890539-57e6da26-9bc7-11e8-89d2-d139aca4029e.png)
[butterfly.zip](https://github.com/Templarian/MaterialDesign/files/2273584/butterfly.zip)

**Comment by PerthTotty** [comment]
"Just a try" ;-)

**Comment by goyney** [comment]
I don't think that's really distinguishable as a butterfly.

**Comment by SarinManS** [comment]
Tried a few concepts for this one

Ver-1
![image](https://user-images.githubusercontent.com/26505215/44302482-63f8f400-a349-11e8-9bad-796af6aa41b2.png)

Ver-2
![image](https://user-images.githubusercontent.com/26505215/44302494-8ab72a80-a349-11e8-8fe0-158a0b594186.png)

Ver-3
![image](https://user-images.githubusercontent.com/26505215/44302499-9c003700-a349-11e8-89d5-587cfcbaa5c2.png)

[Butterfly-1.zip](https://github.com/Templarian/MaterialDesign/files/2299806/Butterfly-1.zip)
[Butterfly-2.zip](https://github.com/Templarian/MaterialDesign/files/2299807/Butterfly-2.zip)
[Butterfly-3.zip](https://github.com/Templarian/MaterialDesign/files/2299808/Butterfly-3.zip)

**Comment by goyney** [comment]
Still don't think this is very distinguishable. Moving to the `Backlog` until we get a few more ideas.

**Comment by filipkaniatest** [comment]
I would like to request it as well!

**Comment by Nico0302** [comment]
What du you think about this design:

![butterfly](https://user-images.githubusercontent.com/28566744/88776200-f638e200-d185-11ea-996a-9042bf21563f.png)

[butterfly.zip](https://github.com/Templarian/MaterialDesign/files/4995330/butterfly.zip)

**Comment by goyney** [comment]
I like it! Would like to see a filled version as well, that would definitely be `butterfly-outline`.

**Comment by Nico0302** [comment]
I shifted the dots 1db away from the center for the filled version:
![butterfly (1)](https://user-images.githubusercontent.com/28566744/88817979-7a0ec080-d1be-11ea-9418-69ccb1fa3e71.png)

[butterfly.zip](https://github.com/Templarian/MaterialDesign/files/4995666/butterfly.zip)

**Comment by goyney** [comment]
[![butterfly](https://materialdesignicons.com/icon/butterfly)](https://materialdesignicons.com/icon/butterfly)[![butterfly-outline](https://materialdesignicons.com/icon/butterfly-outline)](https://materialdesignicons.com/icon/butterfly-outline)
