### ISSUE TITLE
Module(s)

### ISSUE THREAD

**Issue by Hrnkas** [Templarian/MaterialDesign#3333]
I would need an Icon to represent one or more modules of a Licence.
Explanation: Our software is modular, and customers can buy additional modules according to their needs. I need an Icon to show if someone has no Modules (Empty icon), one Module (one box/point/item) or multiple Modules (3-4 boxes/poins/items).

My Idea:

One Module:
|-  -|
|o -|

Multiple Modules
|o o|
|o o|

I hope you understand what I mean.

**Comment by PeterShaggyNoble** [comment]
My first thought when reading through your description was that the [`numeric-*-box` icons](https://petershaggynoble.github.io/MDI-Sandbox/?filter=numeric) would be ideal for this.

**Comment by Hrnkas** [comment]
@PeterShaggyNoble it would be, if we depicted precise number of modules. We just want to distinguish between base users, who have no additional modules, and those who do.

**Comment by goyney** [comment]
@Hrnkas The use case you're trying to fulfill is pretty niche. There are several icons in our library that could meet your needs, such as the number icons (as previously suggested), [`box`](https://materialdesignicons.com/icon/box) and [`box-multiple`](https://materialdesignicons.com/icon/box-multiple), or perhaps even [`hexagon`](https://materialdesignicons.com/icon/hexagon) and [`hexagon-multiple`](https://materialdesignicons.com/icon/hexagon-multiple).

Thanks for the suggestions, but we're going to close this issue for now.
