### ISSUE TITLE
Add general purpose advance/percentage icon set

### ISSUE THREAD

**Issue by memeplex** [Templarian/MaterialDesign#3334]
One idea is to make this set similar to the battery set but with the outline being a simple, non battery-shaped, rectangle.

Another idea is for the outline to be a circle and the different percentages/levels to be indicated as in a pie chart.

Finally, it could be an hexagonal outline with six states represented by a progression of triangles.

**Comment by SarinManS** [comment]
Something like this?

![circle-progress](https://user-images.githubusercontent.com/26505215/43716158-c8660f3c-99a2-11e8-93e4-127dd46bd4e8.jpg)
![hexagon-progress](https://user-images.githubusercontent.com/26505215/43716159-c8af7c58-99a2-11e8-9761-9ed027b884ae.jpg)

**Comment by goyney** [comment]
@SarinManS Did you create those? If so, please upload the SVGs in a ZIP file and attach them so we can consider them to be added.

**Comment by memeplex** [comment]
They're beautiful! I didn't expect that much! I like the first set the
most, specially because of the separation between the circle and its
contents.

**Comment by Templarian** [comment]
I like the hexagon, but agree, it might look nicer with a similar separation.

**Comment by SarinManS** [comment]
Sorry forgot to attach the ZIP earlier.

Modified the hexagon to have a similar gap from the stroke.
Here's a sample.
![icon-hexagon-progress](https://user-images.githubusercontent.com/26505215/43768231-93af64b4-9a56-11e8-9c4b-c6c0039f58a5.jpg)

Here are both of them.

[circle-progress.zip](https://github.com/Templarian/MaterialDesign/files/2265817/circle-progress.zip)
[hexagon-progress.zip](https://github.com/Templarian/MaterialDesign/files/2265865/hexagon-progress.zip)

**Comment by Templarian** [comment]
https://materialdesignicons.com/contributor/SarinManS You can see them on your contributor page, not going to individually link the previews. 😹

**Comment by goyney** [comment]
Looks like hex slice 5 is wrong.

**Comment by Templarian** [comment]
Fixed, accidentally exported over it apparently. Was in a rush earlier to leave the cafe.

**Comment by SarinManS** [comment]
Thanks guys

**Comment by PeterShaggyNoble** [comment]
`hexagon-slice-5` is still wrong! 😜

**Comment by memeplex** [comment]
How can I get these icons? I use the Nerd Font pack but I'm unable to find them in their cheat sheet (looking for circle or slice). Neither am I able to find them in Material Design Icons list. The only place where they seem to be available is https://materialdesignicons.com/contributor/SarinManS.

**Comment by PeterShaggyNoble** [comment]
If any icons (bar those waiting official release) are missing from something being provided by a third party then that's something that needs to be brought up with that third party, which I see you've already done.

Looking at their repo, they seem to be using MDI v2.1.19 while the latest release is v3.4.93 so there are nearly 1400(!) icons missing from their collection. I'd suggest using one of our official releases instead to ensure you always have access to the latest icons or, at least, a third party that stays up-to-date with new releases.
