### ISSUE TITLE
ip

### ISSUE THREAD

**Issue by e-krebs** [Templarian/MaterialDesign#3336]
the simplest would probably be to the existing **phone-voip** icon and remove the phone from it.

**Comment by MrGrigri** [comment]
![network-ip](https://user-images.githubusercontent.com/4528551/43213611-46f30fca-8ff4-11e8-8241-221ff6a7227b.png)

[network-ip.zip](https://github.com/Templarian/MaterialDesign/files/2228669/network-ip.zip)

**Comment by Templarian** [comment]
Added as `ip` and `ip-network`.
