### ISSUE TITLE
Request for Whatsapp logo with filled color

### ISSUE THREAD

**Issue by sandeepchougule** [Templarian/MaterialDesign#3337]
Example : http://www.iconarchive.com/show/android-l-icons-by-dtafalonso/WhatsApp-icon.html
Or suggest me how to apply it on existing whatsapp icon ?

**Comment by GreenTurtwig** [comment]
This isn't something we're going to add, WhatsApp's guidelines state not to modify or recolour their logo thus we won't be adding a variant.
