### ISSUE TITLE
bug-check

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3339]
I needed this for a project.

![image](https://user-images.githubusercontent.com/4528551/43090294-37c0a94a-8e64-11e8-8d35-5f9be6bb5d4e.png) ![image](https://user-images.githubusercontent.com/4528551/43090822-b2a45c14-8e65-11e8-9b20-20db2aaa06b2.png)

[bug-check.zip](https://github.com/Templarian/MaterialDesign/files/2220239/bug-check.zip)

**Comment by Templarian** [comment]
[![bug-check](https://materialdesignicons.com/icon/bug-check)](https://materialdesignicons.com/icon/bug-check) [![bug-check-outline](https://materialdesignicons.com/icon/bug-check-outline)](https://materialdesignicons.com/icon/bug-check-outline)
