### ISSUE TITLE
bug-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3340]
In the enduring effort to make outlined versions.

![image](https://user-images.githubusercontent.com/4528551/43090977-2989dc96-8e66-11e8-8a87-61713bf3ffac.png)

[Asset 7.zip](https://github.com/Templarian/MaterialDesign/files/2220250/Asset.7.zip)

**Comment by Templarian** [comment]
[![bug-outline](https://materialdesignicons.com/icon/bug-outline)](https://materialdesignicons.com/icon/bug-outline)
