### ISSUE TITLE
Suggested icon - bongs

### ISSUE THREAD

**Issue by shig2k1** [Templarian/MaterialDesign#3343]
I see a cannabis leaf, but no paraphernalia. Attached are 2 bongs for your consideration - I'm using these in an app
[bongs.zip](https://github.com/Templarian/MaterialDesign/files/2223723/bongs.zip)

**Comment by goyney** [comment]
Thank you for the contribution.

We've discussed internally and while the cannabis leaf has many uses for maps, cafes, etc., we feel these icons are way too niche to include in the library.
