### ISSUE TITLE
engine-off

### ISSUE THREAD

**Issue by mhoberhausen** [Templarian/MaterialDesign#3344]
Created a engine off icon based on the current engine icon (and the style of a WiFi off icon) that would look nicely with the current set
![image](https://user-images.githubusercontent.com/3298763/43143026-d6b0b39c-8f27-11e8-9c28-50ca52d6c0c2.png)

SVG Path:
M23,9v10h-3v-3h-2v2.2L7.8,8H10V6H7V4h8v2h-3v2h6v4h2V9H23z M4.1,5.8L3.5,6.4L6,9l-1,1v3H3v-3H1v8h2v-3h2v3h3l2,2h7l1.8,1.8
	l0.7-0.7L4.1,5.8z

Zip contains .svg file
[disable-engine.zip](https://github.com/Templarian/MaterialDesign/files/2223960/disable-engine.zip)

**Comment by MrGrigri** [comment]
For reference, you can use our [beta site](http://dev.materialdesignicons.com/contribute/github) to generate a preview like this.

![image](https://user-images.githubusercontent.com/4528551/43212973-9f9cb83a-8ff2-11e8-9d98-f4b6a5d53050.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/43721578-226a2104-9961-11e8-918e-fd2212b7b7a8.png) ![image](https://user-images.githubusercontent.com/1015040/43721598-34b5b8d2-9961-11e8-91de-a713ec5f7bfa.png)

**Source:** [engine-off.zip](https://github.com/Templarian/MaterialDesign/files/2262859/engine-off.zip)

**Comment by mhoberhausen** [comment]
Look's great!

**Comment by Templarian** [comment]
Added. 😄
