### ISSUE TITLE
Puzzle-Outline

### ISSUE THREAD

**Issue by KillerBLS** [Templarian/MaterialDesign#3345]
Hi guys, 
I really like Google's puzzle icon, but can you make it **outline**? :) It would be very helpful
Thanks

![image](https://user-images.githubusercontent.com/7825871/43188987-2efba9c2-8ffe-11e8-89d7-f81727beb365.png)

**Comment by PeterShaggyNoble** [comment]
[![puzzle-outline](https://user-images.githubusercontent.com/15157491/43190478-0a853dfe-8ff1-11e8-8906-0a5baddf1a3c.png)](https://material.io/tools/icons/?search=extension&icon=extension&style=outline)

**Comment by MrGrigri** [comment]
Idk about the protrusions being cut into like that. I know that it's a stock google icon, but couldn't we fill those in?

**Comment by Templarian** [comment]
Kind of agree, it looks a little odd.

**Comment by KillerBLS** [comment]
I hope you make it better :)

**Comment by jesseflorig** [comment]
I think it would look a lot better if the inside edges had rounded corners to match the exterior

**Comment by Templarian** [comment]
[![puzzle-outline](https://materialdesignicons.com/icon/puzzle-outline)](https://materialdesignicons.com/icon/puzzle-outline)
