### ISSUE TITLE
file-upload

### ISSUE THREAD

**Issue by fantoine** [Templarian/MaterialDesign#3346]
It could be nice to have something like the [file-download](https://materialdesignicons.com/icon/file-download) icon, but with the arrow pointing to the top.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/43212782-2aca883e-8ff2-11e8-81b6-c326e7ebe270.png)
![image](https://user-images.githubusercontent.com/4528551/43212802-39317680-8ff2-11e8-87a7-7eda98e36839.png)

[file-upload.zip](https://github.com/Templarian/MaterialDesign/files/2228614/file-upload.zip)

**Comment by fantoine** [comment]
Perfect! :+1:

**Comment by Templarian** [comment]
[![file-upload](https://materialdesignicons.com/icon/file-upload)](https://materialdesignicons.com/icon/file-upload) [![file-upload-outline](https://materialdesignicons.com/icon/file-upload-outline)](https://materialdesignicons.com/icon/file-upload-outline)
