### ISSUE TITLE
UV Icon

### ISSUE THREAD

**Issue by MadMax1412** [Templarian/MaterialDesign#3347]
I would like an icon for UV for my UV Sensor.  

I imagine it would look like the "Wave" icon, but rather than horizontal waves, ones at say 45 degrees.

Thanks in advance.

**Comment by MrGrigri** [comment]
This was the first thing that came to my mind. It could also be used for solar power.

![image](https://user-images.githubusercontent.com/4528551/43239418-5c3774f6-904f-11e8-88e7-64274ed83f0c.png)

[uv-sensor.zip](https://github.com/Templarian/MaterialDesign/files/2230312/uv-sensor.zip)

**Comment by MadMax1412** [comment]
I like your first one, but could I make a suggestion please.  Could you turn the arc in the bottom right corner around?  As it stands, it looks more like something radiating upwards towards the sun.

I wish I had skills to draw :-)

**Comment by Templarian** [comment]
[![solar-power](https://materialdesignicons.com/icon/solar-power)](https://materialdesignicons.com/icon/solar-power)

**Comment by MrGrigri** [comment]
those are sensor waves (much like WiFi) not energy coming from the sun.

**Comment by Templarian** [comment]
Maybe like a solar collector dish? Not sure the wireless looks right for a sensor.

**Comment by MadMax1412** [comment]
MrGrigri,

Apologies.  I took them to be the UV rays and thought they would look better coming from the sun.

**Comment by terreng** [comment]
From #4060, which has been closed in favour of this one.

![image](https://user-images.githubusercontent.com/11605395/54649896-461f7900-4a69-11e9-85c0-1fccd1f7eee7.png)
[ultraviolet.svg](https://github.com/terreng/samples/blob/master/ultraviolet.svg)

![image](https://user-images.githubusercontent.com/11605395/54650061-e2e21680-4a69-11e9-8fd8-50548cc3d89a.png)
[ultraviolet-2.svg](https://github.com/terreng/samples/blob/master/ultraviolet-2.svg)

**Comment by goyney** [comment]
I'm not sure if those will work. We're trying to avoid letters in icons to convey meaning as much as possible. Additionally, in either case, the letters are lost at native resolution.

**Comment by PeterShaggyNoble** [comment]
I _think_* "UV" is one of those terms with enough international recognition that we could add it.

(*I'm trying to picture suncream bottles in countries I've been to where the word or term for "ultraviolet" in the native language can't also be abbreviated to "UV"!)

**Comment by goyney** [comment]
Regardless, UV is lost at native resolution, so I don't think we'll be adding those ones.

**Comment by goyney** [comment]
Would the recently added `shield-sun(-outline)` work?

[![shield-sun](https://materialdesignicons.com/icon/shield-sun)](https://materialdesignicons.com/icon/shield-sun)[![shield-sun-outline](https://materialdesignicons.com/icon/shield-sun-outline)](https://materialdesignicons.com/icon/shield-sun-outline)

**Comment by goyney** [comment]
[![sun-wireless](https://materialdesignicons.com/icon/sun-wireless)](https://materialdesignicons.com/icon/sun-wireless)[![sun-wireless-outline](https://materialdesignicons.com/icon/sun-wireless-outline)](https://materialdesignicons.com/icon/sun-wireless-outline)
