### ISSUE TITLE
It could be nice to have something like the icon, For sort some content

### ISSUE THREAD

**Issue by kavdhesh** [Templarian/MaterialDesign#3348]
[](url)

![sort_icon](https://user-images.githubusercontent.com/12409705/43255147-a6ee3556-90e6-11e8-85f0-9aba35b4eb37.png)

**Comment by goyney** [comment]
Would our existing sort icons not suit your needs?
https://materialdesignicons.com/icon/sort
https://materialdesignicons.com/icon/sort-ascending
https://materialdesignicons.com/icon/sort-descending
https://materialdesignicons.com/icon/sort-alphabetical
https://materialdesignicons.com/icon/sort-numeric

**Comment by Templarian** [comment]
The icon that you're looking for is probably `swap-vertical`. I think this style isn't as obvious or consistent with Material Design.
