### ISSUE TITLE
CDN Support

### ISSUE THREAD

**Issue by GuiCavi** [Templarian/MaterialDesign#335]
Is there a way to use the font on Codepen (free account)?

- [x] MaxCDN Sponsored Account.
- [x] Host Material Design Icons Webfont on a CDN

**Comment by Templarian** [comment]
Material Design Icons is not hosted on a CDN at this time. It is being looked into. I'm renaming your issue and making it the request for a CDN.

**Comment by GuiCavi** [comment]
Thanks, that's what I wanted to say haha

**Comment by vanthome** [comment]
+1
http://www.bootstrapcdn.com/
Would probably host it.

**Comment by Templarian** [comment]
Update on this issue... MaxCDN is sponsoring, but it will still take me a bit to get it all wired up.

**Comment by Templarian** [comment]
The CDN is live (DNS may be propagating still). I have to redesign the site still to point to the CDN.

http://cdn.materialdesignicons.com/1.0.62/
http://cdn.materialdesignicons.com/1.1.34/ (unreleased)

**Comment by chester1000** [comment]
@Templarian looks like CDN is lagging many icons behind (at least since a83e3d0). Could we get it updated?

**Comment by Templarian** [comment]
I just haven't updated the webfont in a while. Been rather busy. I'll try and get to it this weekend. Lots of new icons and redsigns (even the rather ugly new Medium logo is in there).

**Comment by chester1000** [comment]
Thanks - really appreciate it! Yeah, I have no idea what they were thinking...

**Comment by CoDEmanX** [comment]
Maybe create a separate repo to push production icons to, in a timely fashion and tag often?
Am 15.10.2015 6:40 nachm. schrieb Damian Mee <notifications@github.com>:Thanks - really appreciate it! Yeah, I have no idea what they were thinking...

**Comment by chester1000** [comment]
@Templarian any update on that?

**Comment by Templarian** [comment]
Nope. Maybe tomorrow, need to fix the font generation. Kind of in the middle of updates to the script that handles the font generation. Busy week haven't really had time to work on much open source stuff.

**Comment by chester1000** [comment]
If the script is OS and you point me to it I might be able to help.

**Comment by Templarian** [comment]
The whole icon platform is closed source unfortunately. Thanks for the offer though. Eventually I will have a more basic open source version as a grunt task (but it would be another thing to maintain). Mostly need to focus on just OS icons.

**Comment by chester1000** [comment]
@Templarian Has anyone reported this already (the font just fails to load on an https website):

<img width="599" alt="screen shot 2015-10-30 at 02 00 09" src="https://cloud.githubusercontent.com/assets/526657/10827443/0282ed50-7eaa-11e5-8733-d727af8ddf31.png">

Firefox 41.0.2; OSX

**Comment by Templarian** [comment]
@chester1000 Can't reproduce that at the moment. I tested in Chrome and Firefox and the both report the certificate as valid. It doesn't expire until 6/1/2016 also.

Not sure what could be the issue on your end. MaterialDesignIcons.com uses the same certification, so if you couldn't see the CDN the site wouldn't work since it is HTTPS only.

**Comment by REJack** [comment]
@chester1000 Which OSX version are you using? and is your date/time correct in OSX?

**Comment by REJack** [comment]
@chester1000 i can reproduce that problem. Its a problem from Firefox on OSX, Mozilla added some CA Certs in the Windows Version but not in the OSX Version. and thank for the hint.

@Templarian you can fix the problem for all OSX Firefox Users. You need to add both CA certs ('StartCom Certification Authority' and 'StartCom Class 1 Primary Intermediate Server CA') in your server cert.

I had the same problem with a GeoTrust cert and fixed it with this solution, i dont know but i think i got wrong CA certs von GeoTrust.

**Comment by chester1000** [comment]
@Templarian 

https://materialdesignicons.com/ works indeed

<img width="573" alt="screen shot 2015-10-30 at 04 09 59" src="https://cloud.githubusercontent.com/assets/526657/10830723/3a34f8da-7ebc-11e5-9076-a654e41883a5.png">

However https://cdn.materialdesignicons.com/1.2.65/css/materialdesignicons.min.css 

<img width="568" alt="screen shot 2015-10-30 at 04 09 53" src="https://cloud.githubusercontent.com/assets/526657/10830732/4ebdcc78-7ebc-11e5-8362-22751856c290.png">

@REJack 10.11 Beta (15A279b); time is correct.

Also, both Mobile Opera and Chrome fail to load said file:
![screenshot_20151030-041523](https://cloud.githubusercontent.com/assets/526657/10830877/14ee06ec-7ebd-11e5-8535-236b61c99f28.png) ![screenshot_20151030-041544](https://cloud.githubusercontent.com/assets/526657/10830878/14eed626-7ebd-11e5-94d2-dff7d0103aed.png)

Android Marshmallow; Nexus 6; Chrome, Chrome Beta and Chrome Dev.

**Comment by CoDEmanX** [comment]
Looks OK in Chrome for Android 46 on Nexus 5 Android 6.0, no security warning for me?!

**Comment by chester1000** [comment]
I thought it might be a network issue, but I get the same error when connecting via wifi/4g and two different VPN providers to different countries.

@CoDEmanX have you tested it on this exact url: https://cdn.materialdesignicons.com/1.2.65/css/materialdesignicons.min.css ?

**Comment by CoDEmanX** [comment]
Yep, takes me straight to the css code:

![14461523117680](https://cloud.githubusercontent.com/assets/1309249/10831935/b23384a2-7e88-11e5-823c-d9dd3dba589c.jpg)

**Comment by REJack** [comment]
@chester1000 check on you firefox if you have the certs 'StartCom Certification Authority' and 'StartCom Class 1 Primary Intermediate Server CA' in your Firefox Certificate Manager

Open the Certificate Manager (Tools => Options => Advanced => Encryption => View Certificates)

**Comment by chester1000** [comment]
@REJack I see this:

<img width="465" alt="screen shot 2015-10-30 at 20 35 10" src="https://cloud.githubusercontent.com/assets/526657/10845777/d18326b0-7f45-11e5-9637-8b9eff654b4e.png">

**Comment by REJack** [comment]
first of all another ISP or over a VPN would not fix the problem, root & ca certs are every time in the Browser Application and/or Operator System (Safari on OSX use OSX certs).
My OSX Firefox only has the first 3 but on my Safari i have the same like in windows.

i dont know but i think i found the SSL error, the CA Cert that is in the Page Certs added is [the old one](https://github.com/cloudflare/cfssl_trust/blob/master/intermediate_ca/StartComClass1PrimaryIntermediateServerCA-alt.crt) and OSX Safari and my Firefox on Windows have [the new one](https://github.com/cloudflare/cfssl_trust/blob/master/intermediate_ca/StartComClass1PrimaryIntermediateServerCA.crt). 
if Templarian can change the old CA cert with the new CA cert on his page the problem could be fixed :smile: 

To check which CA cert is on the page, i used the [GnuTLS Transport Layer Security Library](http://www.gnutls.org/download.html) ``gnutls-cli --print-cert materialdesignicons.com``

**Comment by REJack** [comment]
@chester1000 you can try to add [the new CA Cert](https://github.com/cloudflare/cfssl_trust/blob/master/intermediate_ca/StartComClass1PrimaryIntermediateServerCA.crt) in your Firefox it could fix your problem, i think you have the old one in your Certificate Manager

**Comment by chester1000** [comment]
@REJack I was only entertaining the possibility of it being caused by ISP or something country-related (I'm currently in Taiwan), as that seems to be the only thing _Firefox¹ on Mac_ and _Opera and Chromes on Android_ have in common. MITM might've been the reason why certs got invalidated.

¹ - Chrome, Safari and Opera work great.

--- 

Why would I have an old cert? How do those get updated or, in this case, left behind?

Also, I'm more concerned about ppl visiting my websites, I wouldn't assume, they'll all start adding certs on their machines ;).

**Comment by REJack** [comment]
Its a failure from Mozilla Firefox only on OSX there are many certs missing. But a Webhoster can prevent this failure.
> ¹ - Chrome, Safari and Opera work great.

First the certs get updated on Software Updates. 
Second this is not really a old cert but it has been renewed and its still there because its still vaild.
Thrid i know that Firefox save some CA certs on Page visit without prompt.
> Why would I have an old cert? How do those get updated or, in this case, left behind?

I understand you, if Templarian change the CA certs ppl would need to add the cert.
> Also, I'm more concerned about ppl visiting my websites, I wouldn't assume, they'll all start adding certs on their machines ;).

i dont know but i fixed this kind of problem on a page from a customer.
> > I had the same problem with a GeoTrust cert and fixed it with this solution, i dont know but i think i got wrong CA certs from GeoTrust. 

did you add the new cert in your Firefox? it could be proof of my consideration :sweat_smile:

**Comment by Templarian** [comment]
So, the CDN is using the same cert since it was setup back in June. I don't know if that helps.

I know like 0% about SSL except for the steps to install it on my server. Just let me know if there is something I need to do on my end of things, but right now this sounds like a very specific localized issue.

**Comment by REJack** [comment]
@Templarian can you change the CA Certs on your server? If yes, could you add [this CA Cert](https://github.com/cloudflare/cfssl_trust/blob/master/intermediate_ca/StartComClass1PrimaryIntermediateServerCA.crt) to your Cert, if it wouldn't work i'm quiet :smile:

**Comment by chester1000** [comment]
@REJack I don't want to hide the issue on my machine, I would like to solve it for end users. If that's not possible ATM I'd rather leave my machine in a broken state, so I can observe once it somehow gets fixed.

@Templarian Looks like that issue might be either really rare or somehow specific to me. As I am not able to pinpoint a shared condition between FF on OSX and Opera and Chromes on Android, **I suggest just leaving it as is and closing this topic here.** 

Let's not close the topic of updating the WebFont, though :stuck_out_tongue_winking_eye:

**Comment by REJack** [comment]
@Templarian pls look at [this page](https://www.sslshopper.com/ssl-checker.html#hostname=cdn.materialdesignicons.com).

> The certificate is not trusted in all web browsers. You may need to install an Intermediate/chain certificate to link it to a trusted root certificate. Learn more about this error. You can fix this by following StartCom's Certificate Installation Instructions for your server platform. Pay attention to the parts about Intermediate certificates.

**Comment by chester1000** [comment]
Yup, that seems legit. Certification chain is incomplete [(more details)](https://www.ssllabs.com/ssltest/analyze.html?d=cdn.materialdesignicons.com), one of [those](https://goo.gl/CAqaHr) might help.

**Comment by REJack** [comment]
On the page i posted is a help link too for StartCom Certificates.

**Comment by Templarian** [comment]
Hey guys looks like your right. I'll be getting this resolved tomorrow.

I just have to send them the various updated SSL related files. At the office, so don't do it right now.

**Comment by chester1000** [comment]
@Templarian Really happy to hear that! Also, thank you for updating the webfont :)
