### ISSUE TITLE
Build instructions for WebFont?

### ISSUE THREAD

**Issue by pjfsilva** [Templarian/MaterialDesign#3351]
Sometimes new icons are added without issuing a new release (which is normal) but it raises the question of how can we manually build the WebFont based on the latest icons commited to this project?

It seems #1542 tried to address this marginally but it seems it never reached anywhere. 

I'm sure the author knows the specific steps on how he builds the project and uploads a new version to webfont so why not just share them, even if some manual process s required? That way we can possibly also help on the tooling.

Of course ideally it should also have an automatic build process for each icon commit but that's a different beast :)

**Comment by Templarian** [comment]
The build process is fully automated (except for assigning a codepoint, which is set before each release and tied to the version of the release). I just haven't had time to setup the steps for a nightly build.

It's actually a really hacky blend of `node`/`php`/`grunt`/`grunt-webfont` and some other stuff. But the entire webfont can be built with node + grunt + grunt-webfont. Most of the other stuff is just for the preview.html file.

Now that we have the `@mdi/svg` package this should be something we can document and write. I just haven't had time. Note this `MaterialDesign` repo's SVG files will not work with `grunt-webfont` only the ones in the database will (which are the same as `@mdi/svg`).

https://github.com/Templarian/MaterialDesign-Site/blob/master/src/content/guide-webfont.md I actually started to document it for the new site, but got distracted.

The new site has more detailed docs we're working on like: http://dev.materialdesignicons.com/guide/wcag

**Comment by Templarian** [comment]
Closing this issue please keep discussions in #1542. I'll try and find some time eventually to get this documented. I really want to upgrade all my tooling, but last time I tried I ran into so many headaches I gave up and focused on the icons again.

Just note, the webfont is not the future of this project. We're going to stress to everyone that they use the SVG files. The release of https://github.com/Templarian/MaterialDesign-JS will push this along with the future components. 😄
