### ISSUE TITLE
Contain

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3352]
`contain`, `contain-start`, and `contain-end`

![image](https://user-images.githubusercontent.com/4528551/43329637-369ecf20-917e-11e8-8267-876137fe7acd.png) ![image](https://user-images.githubusercontent.com/4528551/43329653-40f5e026-917e-11e8-9d03-b08f8aff8dd3.png) ![image](https://user-images.githubusercontent.com/4528551/43329663-486f9cb6-917e-11e8-808c-1cfb3d35ef11.png)

[contain.zip](https://github.com/Templarian/MaterialDesign/files/2236309/contain.zip)

**Comment by Templarian** [comment]
[![contain](https://materialdesignicons.com/icon/contain)](https://materialdesignicons.com/icon/contain) [![contain-start](https://materialdesignicons.com/icon/contain-start)](https://materialdesignicons.com/icon/contain-start) [![contain-end](https://materialdesignicons.com/icon/contain-end)](https://materialdesignicons.com/icon/contain-end)
