### ISSUE TITLE
front side Baby icon need 

### ISSUE THREAD

**Issue by vosidiy** [Templarian/MaterialDesign#3354]
something like 
https://cloud.githubusercontent.com/assets/3604751/2745408/bff7703c-c735-11e3-89ae-40fa21be9434.png

**Comment by goyney** [comment]
@vosidiy Can you please let us know if #2390 would fulfill your needs for this request?

**Comment by PeterShaggyNoble** [comment]
Going to close this in favour of #2390 for now due to lack of feedback.

@vosidiy, if that one doesn't suit our needs please leave a comment and reopen the issue.
