### ISSUE TITLE
comment-eye(-outline)

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3356]
![image](https://user-images.githubusercontent.com/1015040/43546803-8e588d0a-95a7-11e8-9ce6-3ee17694eb9a.png) ![image](https://user-images.githubusercontent.com/1015040/43546771-80502b6e-95a7-11e8-9049-664f560dfa2a.png)

*Source:* [comment-view.zip](https://github.com/Templarian/MaterialDesign/files/2251014/comment-view.zip)

*EDIT:* I meant `comment-eye`.

**Comment by Templarian** [comment]
[![comment-eye](https://materialdesignicons.com/icon/comment-eye)](https://materialdesignicons.com/icon/comment-eye) [![comment-eye-outline](https://materialdesignicons.com/icon/comment-eye-outline)](https://materialdesignicons.com/icon/comment-eye-outline)
