### ISSUE TITLE
Glyphs "apps" and "truck" have issues

### ISSUE THREAD

**Issue by ThomasKeil** [Templarian/MaterialDesign#3357]
The glyphs "apps" and "truck" seem to have issues, I can't convert them with grunt-webfont/fontforge to a ttf, fontforge just hangs.

Upon searching for the reason I found out that the SVGs have contours that aren't closed. 
![auswahl_232](https://user-images.githubusercontent.com/1055202/43567935-9eaf9bc6-9633-11e8-9536-03a296041ec9.png)
![auswahl_233](https://user-images.githubusercontent.com/1055202/43568011-d2f84c2a-9633-11e8-8a82-166cf0a24ff6.png)

Closing them in Inkscape fixed that for me.
I'm not quite sure if that is the correct approach, but if it is: do you want a pull request for those files?

**Comment by Templarian** [comment]
Closing as not an issue. This is part of our SVG optimization step to cut down on point count.

I use the grunt-webfont with node without the fontforge dependency. Might look into that instead.

**Comment by Templarian** [comment]
You might be able to automate this with a relatively easy regex. Basically we move to (`M`) instead of closing path points. I think adding Z before each of the `M` might close the paths?

Not 100% sure though.

**Comment by MrGrigri** [comment]
That should close each of the paths.

**Comment by Templarian** [comment]
Guys, I think I'm going to update `@mdi/util` with a helper function to close paths. /cc @macx

Reopening this issue so we can track the progress. Eventually I want to add a NPM package called `@mdi/font-custom` that handles the entire flow of creating a custom webfont that will make use of these updates.

**Comment by macx** [comment]
@Templarian Wohow, great news. Keep on updating.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Webfont-Build

Lets try and work on this together. Submit Issues and PR's above. I've added the basics to generate a directory called `icons` that contains "fixed" paths.

Basically run `npm run buildIcons && npm run _your script_` in a new command. Looking for PRs. I'll help making sure the SVG data is compatible. The current `buildIcons` command should handle most icons, but there may be edge cases.

**Comment by goyney** [comment]
This is not something we are interested in doing. Part of the optimization process is to remove unneeded points and paths. This is even more important now as we cross 4000 unique icons. Thank you for your suggestion.
