### ISSUE TITLE
city-variant

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3358]
`city-variant-outline` and `city-variant`

I don't care too much about `city-variant`, it's not consistant with the outline which I prefer. Maybe we could add the outlined version.

![image](https://user-images.githubusercontent.com/4528551/43592661-4de4f6be-9633-11e8-8419-55f4ff1f179b.png) ![image](https://user-images.githubusercontent.com/4528551/43593298-a52b02f0-9634-11e8-86b0-8a146c55ce82.png)

[city-variant.zip](https://github.com/Templarian/MaterialDesign/files/2254044/city-variant.zip)

**Comment by Templarian** [comment]
[![city-variant](https://materialdesignicons.com/icon/city-variant)](https://materialdesignicons.com/icon/city-variant) [![city-variant-outline](https://materialdesignicons.com/icon/city-variant-outline)](https://materialdesignicons.com/icon/city-variant-outline)
