### ISSUE TITLE
file-multiple

### ISSUE THREAD

**Issue by DouglasCF** [Templarian/MaterialDesign#336]
- [ ] file-multiple

**Comment by CoDEmanX** [comment]
Like this?
![file-multiple](https://cloud.githubusercontent.com/assets/1309249/8761436/f3da3a82-2d51-11e5-9b5b-4c01588499e7.png)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/file-multiple

**Comment by DouglasCF** [comment]
Nice! Thanks!
