### ISSUE TITLE
radiator-off

### ISSUE THREAD

**Issue by ltjessem** [Templarian/MaterialDesign#3362]
How about a `radiator-off` icon to compliment `radiator`, identical icon but without the heat radiating from the top.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/43717525-dab2fac6-9955-11e8-98a9-d8477d7fa1ae.png)

**Source:** [radiator-off.zip](https://github.com/Templarian/MaterialDesign/files/2262575/radiator-off.zip)

**Comment by ltjessem** [comment]
Yes the one with the slash definitely fits with the current actions. Personally, I can see myself using both, one as a "radiator-disabled" and the jeep as "radiator-off"

**Comment by Templarian** [comment]
[![radiator-off](https://materialdesignicons.com/icon/radiator-off)](https://materialdesignicons.com/icon/radiator-off) [![radiator-disabled](https://materialdesignicons.com/icon/radiator-disabled)](https://materialdesignicons.com/icon/radiator-disabled)
