### ISSUE TITLE
bank-transfer

### ISSUE THREAD

**Issue by SarinManS** [Templarian/MaterialDesign#3363]
Icons to indicate a transaction from/to a bank.

![image](https://user-images.githubusercontent.com/26505215/43685617-06db135c-98d6-11e8-8529-e2287b5238ff.png)
![image](https://user-images.githubusercontent.com/26505215/43685619-13686174-98d6-11e8-8204-5bfeda9ddc83.png)
![image](https://user-images.githubusercontent.com/26505215/43685624-2ca3432a-98d6-11e8-94f5-0b2f66437df1.png)

[bank-transfer.zip](https://github.com/Templarian/MaterialDesign/files/2260264/bank-transfer.zip)
[bank-receive.zip](https://github.com/Templarian/MaterialDesign/files/2260262/bank-receive.zip)
[bank-send.zip](https://github.com/Templarian/MaterialDesign/files/2260263/bank-send.zip)

**Comment by Templarian** [comment]
@SarinManS Let me know when you have 5 icons and I'll transfer them from the contributor account and create one for you.

[![bank-transfer-out](https://materialdesignicons.com/icon/bank-transfer-out)](https://materialdesignicons.com/icon/bank-transfer-out) [![bank-transfer-in](https://materialdesignicons.com/icon/bank-transfer-in)](https://materialdesignicons.com/icon/bank-transfer-in) [![bank-transfer](https://materialdesignicons.com/icon/bank-transfer)](https://materialdesignicons.com/icon/bank-transfer)
