### ISSUE TITLE
target-alternate

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3366]
An alternate to the current `target` (which is a circle). These both can alternatively be used for registration marks in printing. I also suggest adding aliases to each of them with "registration marks".

![image](https://user-images.githubusercontent.com/1015040/43749668-06a5e856-99c3-11e8-9533-640a43d75161.png)

**Source:** [target-alternate.zip](https://github.com/Templarian/MaterialDesign/files/2264643/target-alternate.zip)

**Comment by Templarian** [comment]
[![target-variant](https://materialdesignicons.com/icon/target-variant)](https://materialdesignicons.com/icon/target-variant)
