### ISSUE TITLE
format-annotation-minus

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3367]
Missing alternative to our existing `format-annotation-plus`.

![image](https://user-images.githubusercontent.com/1015040/43750374-1b84caf0-99c6-11e8-9711-0b8a1c1a5775.png)

**Source:** [format-annotation-minus.zip](https://github.com/Templarian/MaterialDesign/files/2264701/format-annotation-minus.zip)

**Comment by Templarian** [comment]
[![format-annotation-minus](https://materialdesignicons.com/icon/format-annotation-minus)](https://materialdesignicons.com/icon/format-annotation-minus)
