### ISSUE TITLE
ampersand/et

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3368]
An ampersand and an et symbol (both symbolizing "and").

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

Comments and suggestions are welcome.

![image](https://user-images.githubusercontent.com/1015040/43937697-3d463e30-9c2d-11e8-918f-8d4f85ec4700.png)![image](https://user-images.githubusercontent.com/1015040/43752201-1a8faab8-99ce-11e8-976e-830b7ccdfa6c.png)

**Source:** [and.zip](https://github.com/Templarian/MaterialDesign/files/2276489/and.zip)

**Comment by Templarian** [comment]
Not a huge fan of that `&`. Not sure if `et` makes sense to add (also not sure what it means).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/43810078-e2a1f28a-9a83-11e8-9b02-0a257b050cb2.png)

I agree. I considered just using the Roboto font's & as an icon, but thought that would be cheating.

**Comment by MrGrigri** [comment]
Sorry, I've been camping for the last week and just got back. I'll give it a go.

**Comment by Templarian** [comment]
[![et](https://materialdesignicons.com/icon/et)](https://materialdesignicons.com/icon/et) [![ampersand](https://materialdesignicons.com/icon/ampersand)](https://materialdesignicons.com/icon/ampersand)
