### ISSUE TITLE
Create henriquecm a Contributor Account

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3369]
Add a contributor account with the various icons below.

- Name you want
- Twitter (optional)
- Avatar (will use your GitHub just let me know)

- [ ]  Assign `human` icons.

@henriquecm ^ What other ones have we added? Want to make sure I don't forget any.

**Comment by goyney** [comment]
`ear-hearing-off` is his but was accidentally attributed to me.

**Comment by henriquecm** [comment]
Name: Henrique César Madeira
Twitter: I have but don't really use.
Avatar: I just uploaded a new avatar on github.

I think that just humans and ear-hearing-off were added.

**Comment by Templarian** [comment]
https://materialdesignicons.com/contributor/Henrique-C%C3%A9sar-Madeira

Eventually you'll have the ability to edit this stuff, but it's till not done. Until then keep submitting icons and you'll see them on your profile above.
