### ISSUE TITLE
flight-rotation

### ISSUE THREAD

**Issue by mvnmin** [Templarian/MaterialDesign#3370]
Would like an icon for the **airline industry** that would suggest a **flight-rotation**.  These are crew instances where they 'rotate' from one location to another & may often switch locations or crews.

**Comment by mvnmin** [comment]
[flight-rotation.zip](https://github.com/Templarian/MaterialDesign/files/2270910/flight-rotation.zip)

Here's an example for review/approval.

**Comment by goyney** [comment]
Can you create a preview of the glyph here? http://dev.materialdesignicons.com/contribute/github

**Comment by mvnmin** [comment]
Sure! Looking at the process now. (~sorry i missed that).

**Comment by mvnmin** [comment]
@goyney  Not sure I follow how to. (My image is more complex than a single svg path. It has polygon points also.).

**Comment by Templarian** [comment]
Without looking at the image, just select all the paths and union and re-export as SVG will give one `<path>` tag.

**Comment by goyney** [comment]
@mvnmin We deal in a singular path data for icons. I've opened up your file and there are several things you'll need to consider when preparing it for submission.

First, take a look at Google's guidelines: https://material.io/design/iconography/system-icons.html#design-principles. It looks like you have a few lines that are thinner than the 2dp recommendation.

Secondly, convert all your strokes to shapes and then union everything. If you have shapes that don't intersect, you may also need to select everything and convert it all to a compound path. You'll know you did it right when the outputted SVG contains a single `<path>` element.

Last, copy and paste the content of the `d` attribute from the `<path>` element into that site to generate a preview. Copy and paste the preview image into a post here and make sure to upload a copy of the new SVG!

Hope that helps get you started!

**Comment by MrGrigri** [comment]
So, I'm not a fan of this one. I't seams too niech for our project. I would use `clipboard-flow` personally. 

![image](https://user-images.githubusercontent.com/4528551/43979775-0ac97d06-9ca9-11e8-85c6-19a3436d37a5.png)

Path:
```XML
<path d="M21,18a3.1,3.1,0,0,1-6.2,0A3.07,3.07,0,0,1,16,15.57a5.24,5.24,0,0,0-2-2.08c-1.61-.92-3.83-.89-6.58.07a2.19,2.19,0,1,1-.6-1.91c3.32-1.13,6.07-1.11,8.2.12A7.23,7.23,0,0,1,17.9,14.9,3.1,3.1,0,0,1,21,18ZM12.2,6.45a6.94,6.94,0,0,0-2.62.77l-1-1.76a9,9,0,0,1,3.36-1Zm-4,1.84a9.53,9.53,0,0,0-1.58,2.36l-1.78-.9A11.39,11.39,0,0,1,6.72,6.91ZM21.5,6A2.8,2.8,0,0,1,16,6.63a14.06,14.06,0,0,0-1.85-.22l.12-2c.63,0,1.31.12,2,.23A2.8,2.8,0,0,1,21.5,6ZM20,6a1.3,1.3,0,1,0-1.3,1.3A1.3,1.3,0,0,0,20,6Z"/>
```

**Comment by goyney** [comment]
I think this fits in with our `transit-connection` icons, but I'm not sure what to name it.

**Comment by goyney** [comment]
Added as `transit-detour`.
[![transit-detour](https://materialdesignicons.com/icon/transit-detour)](https://materialdesignicons.com/icon/transit-detour)
