### ISSUE TITLE
@mdi/js is not usable in Node.js

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3372]
The `@mdi/js` package is great for the client, but fails to work in Node.js.

Simply including the package and logging its contents in CommonJS format causes a syntax error.

```
const mdi = require('@mdi/js');
console.log(mdi);
```

```
export var mdiAccessPoint = "M4.93,4.93C3.12,6.74 2,9.24 2,12C2,14.76 3.12,17.26 4.93,19.07L6.34,17.66C4.89,16.22 4,14.22 4,12C4,9.79 4.89,7.78 6.34,6.34L4.93,4.93M19.07,4.93L17.66,6.34C19.11,7.78 20,9.79 20,12C20,14.22 19.11,16.22 17.66,17.66L19.07,19.07C20.88,17.26 22,14.76 22,12C22,9.24 20.88,6.74 19.07,4.93M7.76,7.76C6.67,8.85 6,10.35 6,12C6,13.65 6.67,15.15 7.76,16.24L9.17,14.83C8.45,14.11 8,13.11 8,12C8,10.89 8.45,9.89 9.17,9.17L7.76,7.76M16.24,7.76L14.83,9.17C15.55,9.89 16,10.89 16,12C16,13.11 15.55,14.11 14.83,14.83L16.24,16.24C17.33,15.15 18,13.65 18,12C18,10.35 17.33,8.85 16.24,7.76M12,10C10.9,10 10,10.9 10,12C10,13.1 10.9,14 12,14C13.1,14 14,13.1 14,12C14,10.9 13.1,10 12,10Z";
^^^^^^

SyntaxError: Unexpected token export
```

Also, utilizing Node.js v10's new experimental support for ES modules fails to work.

```
import * as mdi from '@mdi/js';
console.log(mdi);
```

Same syntax error as above.

If I go into the `node_modules` folder and make a copy of `mdi.js` to `mdi.mjs` and change my import to be `import * as mdi from '@mdi/js/mdi.mjs';`, I am able to load the library fine. This is because Node 10 requires any files being imported as ES modules to have the `*.mjs` file extension.

---

From what I have read, there are two options.

1. The code in `@mdi/js` can be turned into CommonJS format. That would allow it to be imported and/or required both in ES format/CommonJS format, respectively. This would also allow the package to be used in any version of Node.js. This is probably the best option.
2. Have the code that generates the `mdi.js` file also generate a `mdi.mjs` file for use. That can be used server-side via `import * as mdi from '@mdi/js/mdi.mjs';`. This option would only support Node.js v10 with ES modules enabled.

**Comment by Templarian** [comment]
Looks like the package in preview fixed this. Just wanted to give an update on this issue that starting with `v2.6.95` we'll be offering a CommonJS implementation.
