### ISSUE TITLE
close a tab

### ISSUE THREAD

**Issue by MrKuip** [Templarian/MaterialDesign#3373]
There is an icon 'tab-plus' .
I need an icon that closes a tab

**Comment by goyney** [comment]
What about any variation of the `close` icon?

**Comment by MrKuip** [comment]
Yes
 that would be great

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/43980274-c93c6284-9caa-11e8-8d05-2809b6f79b22.png)

```
<path d="M3,3A2,2 0 0,0 1,5V19A2,2 0 0,0 3,21H21A2,2 0 0,0 23,19V5A2,2 0 0,0 21,3H3M3,5H13V9H21V19H3V5M7,13V15,H15,V13Z"/>
```

**Comment by Templarian** [comment]
[![tab-remove](https://materialdesignicons.com/icon/tab-remove)](https://materialdesignicons.com/icon/tab-remove) [![tab-minus](https://materialdesignicons.com/icon/tab-minus)](https://materialdesignicons.com/icon/tab-minus)
