### ISSUE TITLE
briefcase-edit

### ISSUE THREAD

**Issue by theminanaji** [Templarian/MaterialDesign#3374]
I work in finance software and we use the briefcase to denote a financial portfolio. it would be useful to have a `pencil` icon overlaid onto `briefcase` to make `briefcase-edit` . (just like `folder-edit`)

I've designed one to use in my mocks in the time being. But my devs strictly use the icons part of the material design community icons. 

![image](https://user-images.githubusercontent.com/9604139/43924886-bf3b0e8c-9bf3-11e8-96c8-155957d52115.png)

here's the svg: [briefcase-edit.svg.zip](https://github.com/Templarian/MaterialDesign/files/2275861/briefcase-edit.svg.zip)

**Comment by goyney** [comment]
All of our other briefcase icons use a circular cut-out in the corner. Could you try that out? I think keeping things consistent would be better.

**Comment by theminanaji** [comment]
shucks--I was actually trying to keep things consistent with the folder-edit since we use that too
![image](https://user-images.githubusercontent.com/9604139/43927600-11c08fb2-9bfc-11e8-97d8-cc6f3072958e.png)

which, I suppose folders also have circle cutouts for search:
![image](https://user-images.githubusercontent.com/9604139/43927557-f096881e-9bfb-11e8-8570-776483190046.png)

since folders have both straight and circle cutouts--any chance briefcase can have different cutouts too?

**Comment by goyney** [comment]
Hmm, that's a good point. The other modifiers on folders are actually in the folder, not cut-out. I'm not sure then, I'll let @Templarian make the call.

**Comment by Templarian** [comment]
Pencil doesn't use the circle cut out. So looks right to me.

**Comment by Templarian** [comment]
[![briefcase-edit](https://materialdesignicons.com/icon/briefcase-edit)](https://materialdesignicons.com/icon/briefcase-edit)

**Comment by theminanaji** [comment]
great--thank you!
