### ISSUE TITLE
Expand and collapse all icon

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3375]
You can google search, but this icon is usually 3 cascaded squares (top left to bottom right direction) with a + or - in the last square. This is used above tree controls generally to expand or collapse all items.

(This is different than the library plus icon).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/43926853-852e9f28-9bf9-11e8-81d5-ca301c2c376a.png)![image](https://user-images.githubusercontent.com/1015040/43926862-8ef30558-9bf9-11e8-848e-584f41a4a54b.png)
![image](https://user-images.githubusercontent.com/1015040/43926866-995fdd72-9bf9-11e8-9a2e-dd328f16386c.png)![image](https://user-images.githubusercontent.com/1015040/43926886-a1d99c2c-9bf9-11e8-9b11-ab92e939d7db.png)

And bonus:
![image](https://user-images.githubusercontent.com/1015040/43926927-ce4409dc-9bf9-11e8-872e-6ba5c91b395e.png)

We'll want to alias these immediately with `collapse-all(-outline)` and `expand-all(-outline)`.

**Source:** [animation.zip](https://github.com/Templarian/MaterialDesign/files/2275960/animation.zip)

**Comment by Templarian** [comment]
I added these as `collapse-all` and `expand-all`.

[![collapse-all](https://materialdesignicons.com/icon/collapse-all)](https://materialdesignicons.com/icon/collapse-all) [![collapse-all-outline](https://materialdesignicons.com/icon/collapse-all-outline)](https://materialdesignicons.com/icon/collapse-all-outline) [![expand-all](https://materialdesignicons.com/icon/expand-all)](https://materialdesignicons.com/icon/expand-all) [![expand-all-outline](https://materialdesignicons.com/icon/expand-all-outline)](https://materialdesignicons.com/icon/expand-all-outline)  [![animation-outline](https://materialdesignicons.com/icon/animation-outline)](https://materialdesignicons.com/icon/animation-outline) [![animation-play-outline](https://materialdesignicons.com/icon/animation-play-outline)](https://materialdesignicons.com/icon/animation-play-outline)
