### ISSUE TITLE
Foxte Icon

### ISSUE THREAD

**Issue by NovaGL** [Templarian/MaterialDesign#3376]
Not sure if this will be accepted but it's pay tv Australia icon so I think it would be good for people to use in home assistant

[Foxtel Icon](https://github.com/Templarian/MaterialDesign/files/2277540/foxtel.zip)

**Comment by Templarian** [comment]
Social Media only icons at the moment. We're using the Brand / Rejected to track a future any Brand goes icon pack (so don't read into it too far).
