### ISSUE TITLE
select-compare

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3377]
![image](https://user-images.githubusercontent.com/1015040/43972126-677f16ee-9ca1-11e8-8562-485b1b411a8f.png)

**Source:** [inspect.zip](https://github.com/Templarian/MaterialDesign/files/2278824/inspect.zip)

**Comment by MrGrigri** [comment]
Wouldn't `compare` work?

![compare](https://materialdesignicons.com/icon/compare)

**Comment by Templarian** [comment]
@MrGrigri It's used in gallery.io, so might as well add it in addition.

**Comment by Templarian** [comment]
Maybe `compare-variant` ?

**Comment by goyney** [comment]
We also have `file-compare`, which matches `compare` in style. This new icon is unique in the dotted line and the way the split occurs on the left side.

**Comment by MrGrigri** [comment]
To me, it doesn't symbolize `inspect`

**Comment by Templarian** [comment]
Agreed, it really doesn't mean `inspect`, so naming it `compare-variant` may make more sense.

**Comment by Templarian** [comment]
`select-compare` ?

**Comment by Templarian** [comment]
[![select-compare](https://materialdesignicons.com/icon/select-compare)](https://materialdesignicons.com/icon/select-compare)
