### ISSUE TITLE
bag

### ISSUE THREAD

**Issue by MrGlenThomas** [Templarian/MaterialDesign#3379]
like the medical-bag, but just a bag that is not medical (without the +)

**Comment by JamesCoyle** [comment]
![image](https://user-images.githubusercontent.com/10384436/44026626-9181cf30-9eeb-11e8-8c4f-87a07b9d1c41.png)

[bag.zip](https://github.com/Templarian/MaterialDesign/files/2282608/bag.zip)

**Comment by MrGlenThomas** [comment]
Beautiful! 😍

**Comment by JamesCoyle** [comment]
I always forget to change the icon name in the preview... 😂

**Comment by goyney** [comment]
This is a duplicate of submission in #141 by @Alekhen.
