### ISSUE TITLE
Inventory/Sack

### ISSUE THREAD

**Issue by derRAV3N** [Templarian/MaterialDesign#338]
something like these, but material:
![866125](https://cloud.githubusercontent.com/assets/12349529/7541395/623cc19a-f5b5-11e4-8237-32460c35f74d.png)
![156032](https://cloud.githubusercontent.com/assets/12349529/7541426/a495bf74-f5b5-11e4-97d7-33dbb536d31c.png)
- [ ] bag

**Comment by Templarian** [comment]
[![sack](https://materialdesignicons.com/icon/sack)](https://materialdesignicons.com/icon/sack) [![sack-percent](https://materialdesignicons.com/icon/sack-percent)](https://materialdesignicons.com/icon/sack-percent)
