### ISSUE TITLE
Z-Wave

### ISSUE THREAD

**Issue by rckingsley** [Templarian/MaterialDesign#3380]
Many of us are using MDI icons for home automation and such, and would really appreciate having a Z-Wave icon.  I've seen several iterations of Z-Wave icons, but anything will help.  Thanks.

**Comment by SarinManS** [comment]
![image](https://user-images.githubusercontent.com/26505215/44131668-571a3f32-a074-11e8-9c12-e392805fca39.png)
[zwave.zip](https://github.com/Templarian/MaterialDesign/files/2289209/zwave.zip)

**Comment by Templarian** [comment]
[![z-wave](https://materialdesignicons.com/icon/zwave)](https://materialdesignicons.com/icon/zwave)
