### ISSUE TITLE
shopify

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#3382]
![image](https://user-images.githubusercontent.com/1086448/44016698-777d4e9a-9ef3-11e8-9ac8-2b76cd9e610b.png)

**Comment by SarinManS** [comment]
![image](https://user-images.githubusercontent.com/26505215/44029531-59e2b8fa-9f1d-11e8-8ad2-884defd6239e.png)

![image](https://user-images.githubusercontent.com/26505215/44029468-24b1d7ba-9f1d-11e8-9ace-1a353f39994b.png)

[shopify-ver1.zip](https://github.com/Templarian/MaterialDesign/files/2282801/shopify-ver1.zip)
[shopify-ver2.zip](https://github.com/Templarian/MaterialDesign/files/2282802/shopify-ver2.zip)

**Comment by goyney** [comment]
Social Media only icons at the moment. We're using the Brand / Rejected to track a potential future Brand icon pack.

**Comment by PeterShaggyNoble** [comment]
Reopening this as Shopify is well known enough and, as an icon, useful enough for us to add despite not being a social media icon.

**Comment by Templarian** [comment]
[![shopify](https://materialdesignicons.com/icon/shopify)](https://materialdesignicons.com/icon/shopify)
