### ISSUE TITLE
Zend Framework

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#3384]
![image](https://user-images.githubusercontent.com/1086448/44016933-682604c2-9ef4-11e8-942e-6fe97da587b8.png)

**Comment by Templarian** [comment]
[![zend](https://materialdesignicons.com/icon/zend)](https://materialdesignicons.com/icon/zend)

Assigned to the shared contributor account with the Brands. I created a contributor account for you. Hopefully one of these counts. 😜
