### ISSUE TITLE
Typo-3

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#3386]
![image](https://user-images.githubusercontent.com/1086448/44017160-f8fb3846-9ef4-11e8-9a99-cbb641d2ae8c.png)

**Comment by SarinManS** [comment]
This should do
![image](https://user-images.githubusercontent.com/26505215/44023358-dbaa7134-9f09-11e8-874c-6684d6c22306.png)
[typo3.zip](https://github.com/Templarian/MaterialDesign/files/2282400/typo3.zip)

**Comment by goyney** [comment]
Social Media only icons at the moment. We're using the Brand / Rejected to track a potential future Brand icon pack.
