### ISSUE TITLE
.net (dot-net)

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#3388]
![image](https://user-images.githubusercontent.com/1086448/44017335-8f74bbbc-9ef5-11e8-8f75-bf63964a6b58.png)

**Comment by goyney** [comment]
Leaving this open since its for a programming language.

**Comment by Templarian** [comment]
[![dot-net](https://materialdesignicons.com/icon/dot-net)](https://materialdesignicons.com/icon/dot-net)

**Comment by PeterShaggyNoble** [comment]
Should this be assigned to the "Contributors" account?
