### ISSUE TITLE
HTML file icon

### ISSUE THREAD

**Issue by GuiCavi** [Templarian/MaterialDesign#339]
Others file extensions icons, for example:

![html-icon](https://cloud.githubusercontent.com/assets/7794819/7543279/9e277086-f599-11e4-8fda-ace9e3ad879c.png)

- [ ] file-xml

**Comment by Templarian** [comment]
99% of icons do not have text in them. This will most likely be a file-xml icon with `<>` to signify tags.

**Comment by GuiCavi** [comment]
Yeah, used the image just for example :smile:

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/file-xml
