### ISSUE TITLE
java

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#3392]
![image](https://user-images.githubusercontent.com/1086448/44017630-9d1e5178-9ef6-11e8-9a77-6d372a1bc76b.png)

**Comment by SarinManS** [comment]
![image](https://user-images.githubusercontent.com/26505215/44025972-487ccf26-9f11-11e8-96d9-3b205a481d3e.png)
[java.zip](https://github.com/Templarian/MaterialDesign/files/2282564/java.zip)

**Comment by SarinManS** [comment]
Here's a sample
![java](https://user-images.githubusercontent.com/26505215/44028218-e60a4ba4-9f18-11e8-8eb6-b5abbe105e34.jpg)
For some reason it comes really damaged in the GitHub Icon Preview

[java.zip](https://github.com/Templarian/MaterialDesign/files/2282711/java.zip)

**Comment by goyney** [comment]
Leaving this open since its for a programming language.

**Comment by MrGrigri** [comment]
This is already being tracked with #271

**Comment by PeterShaggyNoble** [comment]
@SarinManS, can you add your contribution to #271, please?
