### ISSUE TITLE
hand-writing

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3394]
A variation on the `hand` set of icons to indicate writing or signing.

**NOTE:** These icons were created as part of a MDI Wingdings project I am working on and _do not_ need to be added to the library if deemed they are unwanted or superfluous.

The reference wingding is: 
![screen shot 2018-08-13 at 12 51 21 pm](https://user-images.githubusercontent.com/1015040/44045800-b0641578-9ef7-11e8-9be8-0910f5e585da.png)

Comments and suggestions are welcome.

![image](https://user-images.githubusercontent.com/1015040/44045695-521ca67e-9ef7-11e8-9d94-dd52b3dc8fdd.png)

**Source:** [hand-writing.zip](https://github.com/Templarian/MaterialDesign/files/2283903/hand-writing.zip)

**Comment by JamesCoyle** [comment]
Has a bit too much dimensionality I think. Maybe if the fingers didn't intersect with the pencil?

**Comment by MrGrigri** [comment]
I'm not a fan of this icon. I believe there are many other ways to signify handwriting.

**Comment by goyney** [comment]
Yeah, I think we can handle this now with `draw`, which is a much better icon. Going to close this.
