### ISSUE TITLE
check-thick

### ISSUE THREAD

**Issue by cakonze** [Templarian/MaterialDesign#3396]
Same as 'Check' icon, but in bold style, or some like the 'Check outline' but filled.

**Comment by MrGrigri** [comment]
Idk if I like this.

![image](https://user-images.githubusercontent.com/4528551/44054237-4a11a5ee-9eff-11e8-9eb5-045ee26a9296.png)

```xml
<path="M19.78,2.2L24,6.42L8.44,22L0,13.55L4.22,9.33L8.44,13.55L19.78,2.2"/>
```

**Comment by goyney** [comment]
I don't see a use case for this.

**Comment by MrGrigri** [comment]
After further discussion with the team, we feel that this icon does not follow the Material Design guidelines and does not represent our project
