### ISSUE TITLE
Lamp-On

### ISSUE THREAD

**Issue by jcreynolds** [Templarian/MaterialDesign#3397]
It would be nice to have lamp on, floor lamp on and desk lamp on.

**Comment by jcreynolds** [comment]
Add ceiling-light-on to the list as well.

**Comment by PerthTotty** [comment]
Like this?

![desk-lamp-on](https://user-images.githubusercontent.com/40835272/44222393-a6250880-a184-11e8-98f7-fd30ae24fbb1.png)
![lamp-on](https://user-images.githubusercontent.com/40835272/44222395-a6bd9f00-a184-11e8-9773-449ea850e233.png)
![floor-lamp-on](https://user-images.githubusercontent.com/40835272/44222396-a6bd9f00-a184-11e8-83c3-812a4afe4510.png)
[lamp-on.zip](https://github.com/Templarian/MaterialDesign/files/2294490/lamp-on.zip)

**Comment by goyney** [comment]
After some internal discussion, we don't believe adding "on" variations of all the lights really makes sense. The state of a light is determined by the toggle switch, not by the light itself. Thank you for your request, and for your contribution @PerthTotty, but we are going to close this issue.

**Comment by jcreynolds** [comment]
The icons in my case are being used for a home automation dashboard the icon on the tile is the off variation for the light. When I'm the on state it would be nice to have a he on variation. I ask that you reconsider the on variations for each light as you have it for both styles of lightbulbs.
