### ISSUE TITLE
Classic Desktop with Tower

### ISSUE THREAD

**Issue by leMaik** [Templarian/MaterialDesign#3399]
TL;DR: An alternative desktop-classic with a tower left/right to the screen would be awesome. :+1: 

Rationale: 
I need to distinguish various computer types for a project. Currently, there are some laptop variants and desktop-classic and tower. Tower looks more like a server, and people born after 2000 won't know what that horizontal bar below the screen in desktop-classic is. :sweat_smile: 

Thanks for your great work!

**Comment by Templarian** [comment]
Got it `desktop-not-so-classic`.

`desktop-monitor-tower` probably.

**Comment by SarinManS** [comment]
I made one with rounded corners to match with **remote-desktop**
![image](https://user-images.githubusercontent.com/26505215/44249664-a5d24f00-a210-11e8-92a3-b3c2b7dc5eb2.png)
![image](https://user-images.githubusercontent.com/26505215/44249740-f8ac0680-a210-11e8-9d1d-04ef8857a29e.png)

[Desktop-RC.zip](https://github.com/Templarian/MaterialDesign/files/2296102/Desktop-RC.zip)
[Desktop.zip](https://github.com/Templarian/MaterialDesign/files/2296106/Desktop.zip)

**Comment by Templarian** [comment]
[![desktop-tower-monitor](https://materialdesignicons.com/icon/desktop-tower-monitor)](https://materialdesignicons.com/icon/desktop-tower-monitor)

Bolded it a bit, trying to keep back the `1dp` line.
