### ISSUE TITLE
bell-settings

### ISSUE THREAD

**Issue by lorencs** [Templarian/MaterialDesign#3401]
Just adding a mini cogwheel to the bell icon, to be used for alert/alarm settings. I did a quick svg mockup by combining the mini cog from account settings icon with the bell icon:

![image](https://user-images.githubusercontent.com/2807805/44169105-ad6aea00-a090-11e8-81d0-e75c70e8fab5.png)
### SVG:
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
	<g>
		<g>
			<path d="M15.098,11.452c0.677-0.303,1.406-0.509,2.17-0.6V9.478c0-3.331-2.322-6.12-5.425-6.857V1.883
				c0-0.898-0.729-1.627-1.627-1.627S8.587,0.984,8.587,1.883v0.738C5.473,3.358,3.163,6.147,3.163,9.478v5.968l-2.17,2.17v1.085
				h9.665c-0.006-0.126-0.01-0.254-0.01-0.382c0-0.616,0.075-1.215,0.214-1.789c0,0,0.435-1.749,1.576-3.077
				C13.738,11.938,15.098,11.452,15.098,11.452z"/>
			<path d="M10.791,19.785H8.045c0,1.199,0.972,2.17,2.17,2.17c0.438,0,0.844-0.13,1.185-0.353
				C11.124,21.033,10.917,20.424,10.791,19.785z"/>
		</g>
		<path d="M23.325,19.751l-1.161-0.89c0.021-0.185,0.043-0.358,0.043-0.543c0-0.184-0.011-0.357-0.043-0.542l1.15-0.89
			c0.098-0.086,0.13-0.228,0.065-0.347l-1.085-1.877c-0.065-0.141-0.207-0.141-0.348-0.141l-1.334,0.542
			c-0.292-0.195-0.586-0.38-0.922-0.51l-0.206-1.432c-0.012-0.13-0.13-0.228-0.25-0.228h-2.17c-0.141,0-0.26,0.098-0.282,0.228
			l-0.206,1.432c-0.327,0.142-0.64,0.315-0.922,0.51l-1.346-0.542c-0.119,0-0.261,0-0.337,0.141l-1.084,1.877
			c-0.065,0.12-0.043,0.261,0.065,0.347l1.15,0.89c-0.022,0.185-0.033,0.358-0.033,0.542c0,0.185,0.011,0.358,0.033,0.543
			l-1.15,0.89c-0.098,0.087-0.13,0.228-0.065,0.347l1.084,1.877c0.065,0.141,0.207,0.141,0.337,0.141l1.346-0.542
			c0.282,0.195,0.585,0.379,0.922,0.51l0.206,1.432c0.022,0.13,0.13,0.228,0.282,0.228h2.17c0.12,0,0.238-0.098,0.26-0.228
			l0.207-1.432c0.325-0.141,0.619-0.315,0.911-0.51l1.334,0.542c0.141,0,0.283,0,0.358-0.141l1.085-1.877
			C23.455,19.979,23.422,19.838,23.325,19.751z M18.149,19.947c-0.912,0-1.627-0.728-1.627-1.628c0-0.899,0.729-1.627,1.627-1.627
			s1.627,0.728,1.627,1.627S19.048,19.947,18.149,19.947z"/>
	</g>
</svg>`

![image](https://user-images.githubusercontent.com/2807805/44169178-df7c4c00-a090-11e8-858a-24bf93ce38c8.png)
### SVG:
`<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
	<g>
		<g>
			<path d="M10.647,18.319c0-0.616,0.075-1.215,0.214-1.789H5.333V9.478c0-2.712,2.17-4.883,4.882-4.883s4.882,2.17,4.882,4.883
				v1.974c0.677-0.303,1.406-0.509,2.17-0.6V9.478c0-3.331-2.322-6.12-5.425-6.857V1.883c0-0.898-0.729-1.627-1.627-1.627
				S8.587,0.984,8.587,1.883v0.738C5.473,3.358,3.163,6.147,3.163,9.478v5.968l-2.17,2.17v1.085h9.665
				C10.651,18.575,10.647,18.447,10.647,18.319z"/>
			<path d="M10.791,19.785H8.045c0,1.199,0.972,2.17,2.17,2.17c0.438,0,0.844-0.13,1.185-0.353
				C11.124,21.033,10.917,20.424,10.791,19.785z"/>
		</g>
		<path d="M23.325,19.751l-1.161-0.89c0.021-0.185,0.043-0.358,0.043-0.543c0-0.184-0.011-0.357-0.043-0.542l1.15-0.89
			c0.098-0.086,0.13-0.228,0.065-0.347l-1.085-1.877c-0.065-0.141-0.207-0.141-0.348-0.141l-1.334,0.542
			c-0.292-0.195-0.586-0.38-0.922-0.51l-0.206-1.432c-0.012-0.13-0.13-0.228-0.25-0.228h-2.17c-0.141,0-0.26,0.098-0.282,0.228
			l-0.206,1.432c-0.327,0.142-0.64,0.315-0.922,0.51l-1.346-0.542c-0.119,0-0.261,0-0.337,0.141l-1.084,1.877
			c-0.065,0.12-0.043,0.261,0.065,0.347l1.15,0.89c-0.022,0.185-0.033,0.358-0.033,0.542c0,0.185,0.011,0.358,0.033,0.543
			l-1.15,0.89c-0.098,0.087-0.13,0.228-0.065,0.347l1.084,1.877c0.065,0.141,0.207,0.141,0.337,0.141l1.346-0.542
			c0.282,0.195,0.585,0.379,0.922,0.51l0.206,1.432c0.022,0.13,0.13,0.228,0.282,0.228h2.17c0.12,0,0.238-0.098,0.26-0.228
			l0.207-1.432c0.325-0.141,0.619-0.315,0.911-0.51l1.334,0.542c0.141,0,0.283,0,0.358-0.141l1.085-1.877
			C23.455,19.979,23.422,19.838,23.325,19.751z M18.149,19.947c-0.912,0-1.627-0.728-1.627-1.628c0-0.899,0.729-1.627,1.627-1.627
			s1.627,0.728,1.627,1.627S19.048,19.947,18.149,19.947z"/>
	</g>
</svg>`

**Comment by Templarian** [comment]
@lorencs Settings icons are required to use the `...`

Eventually we'll delete the `account-settings-variant`. Just have not gotten around to it, it was added many years ago by mistake.

**Comment by MrGrigri** [comment]
I was looking at the current `bell` and `bell-outline` and they are quite different.

![image](https://user-images.githubusercontent.com/4528551/44170690-5287c180-a095-11e8-9ac2-b3f247d780c2.png)

**Comment by lorencs** [comment]
Yeah it's a rough mockup, I just included the svg if anyone wanted to use it / fix it up.

**Comment by Templarian** [comment]
Agreed, this might be worth closing then as all the variations look "odd".

**Comment by julienreszka** [comment]
I was about to request the exact same icon but found this thread.
Can anyone recommend me an alternative to `bell-settings` with a cog since it was rejected?
Something that would explicitly symbolise the action to open notifications settings?
