### ISSUE TITLE
bell inconsistentcies

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3402]
All of the `bell-*` icons are inconsistent. 

![image](https://user-images.githubusercontent.com/4528551/44171301-22412280-a097-11e8-9dec-b515b3fe6ef2.png)

Here are all of the `bell-*` icons corrected to fit the `bell-plus` model.

- [x] `bell`
- [x] `bell-outline`
- [x] `bell-off`
- [x] `bell-off-outline` (NEW)
- [x] `bell-plus`
- [x] `bell-plus-outline` (NEW)
- [x] `bell-ring`
- [x] `bell-ring-outline`
- [x] `bell-sleep`
- [x] `bell-sleep-outline` (NEW)

They are all based off of the new `bell` and `bell-outline` layouts.

![bell](https://user-images.githubusercontent.com/4528551/44174382-34738e80-a0a0-11e8-81c9-44b056792c91.png) ![bell-outline](https://user-images.githubusercontent.com/4528551/44174438-62f16980-a0a0-11e8-9013-6f318dd85af3.png)

There are a couple of new ones.

![bell-off-outline](https://user-images.githubusercontent.com/4528551/44174562-c2e81000-a0a0-11e8-8bd4-047e72e28897.png) ![bell-plus-outline](https://user-images.githubusercontent.com/4528551/44174595-d2ffef80-a0a0-11e8-958f-779e0125567b.png) ![bell-sleep-outline](https://user-images.githubusercontent.com/4528551/44174622-e90db000-a0a0-11e8-8541-5342b84673b5.png)

[bell.zip](https://github.com/Templarian/MaterialDesign/files/2291789/bell.zip)

**Comment by Templarian** [comment]
Unbellievable.
