### ISSUE TITLE
Island / Palm Tree

### ISSUE THREAD

**Issue by CarlosAlbertoUFS** [Templarian/MaterialDesign#3403]
Hello guys!  How about creating an icon of a desert island? This icon would serve to show a characteristic that "there is nothing here". This function is useful for showing a user, for example, that his query to a bank did not return anything, but not because of an error, but because there was nothing even to return. This soothes the user.

**Comment by MrGrigri** [comment]
Would `beach` work?

![beach](https://materialdesignicons.com/icon/beach)

**Comment by goyney** [comment]
Just my two cents, but showing a user an icon to state to someone that their query to a bank did not return anything isn't good user experience; it doesn't indicate that something is wrong. Personally, I would use any of the `error` variants.

**Comment by MrGrigri** [comment]
Empty states are a tricky situation. And a small 24x24 icon is not a good representation of an empty state.

**Comment by CoDEmanX** [comment]
Would probably help to disconnect the tree from the island. Not sure if I like the branches.

**Comment by goyney** [comment]
I do not believe the proposed icon indicates "island" to me. I may take a stab at this one tomorrow.

**Comment by MrGrigri** [comment]
Idk how I feel about the palm tree. 😕

**Comment by Templarian** [comment]
Yea, it needs to be more geometric.

**Comment by goyney** [comment]
Updated icons with more geometry(!!) used on the palm fronds. :)
![image](https://user-images.githubusercontent.com/1015040/48819384-bfa69500-ed1d-11e8-9654-ac0fcc087e04.png)![image](https://user-images.githubusercontent.com/1015040/48819395-cb925700-ed1d-11e8-8c4c-8801784de850.png)

[tropical.zip](https://github.com/Templarian/MaterialDesign/files/2602644/tropical.zip)

**Comment by goyney** [comment]
[![island](https://materialdesignicons.com/icon/island)](https://materialdesignicons.com/icon/island)
[![palm-tree](https://materialdesignicons.com/icon/palm-tree)](https://materialdesignicons.com/icon/palm-tree)
