### ISSUE TITLE
Poor icon quality in @mdi/svg?

### ISSUE THREAD

**Issue by macx** [Templarian/MaterialDesign#3404]
I'm using @mdi/svg and `grunt-webfont` to create my very own (and small) icon-font. Turns out, that some icons get weired results. I opened calendar.svg for example and could clearly see, that there were a path was not closed. Closed it and used it again in my task, I got a perfect result.

Is there a way to force contributers to close all paths in their icons? Or do you have other ideas?

![icon-comparsion](https://user-images.githubusercontent.com/84112/44205857-18332880-a158-11e8-8c48-408a379295c2.png)

![image 2018-08-16 at 2 19 41 pm](https://user-images.githubusercontent.com/84112/44208027-816a6a00-a15f-11e8-8b08-7a2c1da574a4.png)

**Comment by MrGrigri** [comment]
Please take a look at #3357. This is part of our SVG optimization step to cut down on point count.
