### ISSUE TITLE
Led-Strip-Lightened

### ISSUE THREAD

**Issue by uwap** [Templarian/MaterialDesign#3405]
The Led-Strip Icon is really nice but I would also love a "lightened" version of the icon like for the lightbulb and lightbulb-on icons. The lighting could look like the mdi-white-balance-iridescent lighting.

**Comment by goyney** [comment]
We're going to close this issue for the same reason as https://github.com/Templarian/MaterialDesign/issues/3397#issuecomment-413610948. Thank you for your suggestion.
