### ISSUE TITLE
Robber eye mask

### ISSUE THREAD

**Issue by steinmaerivoet** [Templarian/MaterialDesign#3409]
![image](https://user-images.githubusercontent.com/8308610/44303410-a2d67c00-a340-11e8-9204-62796d675194.png)

**Comment by PeterShaggyNoble** [comment]
Or, to give it its proper name: `domino-mask`.

**Comment by andrewnenakhov** [comment]
Based it on Mozilla's private mode icon, I found that it works much better inverted:

v1, white on black:

![private-mode 3x](https://user-images.githubusercontent.com/2351903/44437660-9a966f00-a5d4-11e8-866f-c63af55d3067.png)
![private-mode 2x](https://user-images.githubusercontent.com/2351903/44437661-9c603280-a5d4-11e8-9766-43d83db5f3c1.png)
![private-mode](https://user-images.githubusercontent.com/2351903/44437662-9e29f600-a5d4-11e8-825c-f8f650c071e5.png)

[private-mode.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308566/private-mode.svg.zip)

v2, black on white:

![private-mode-variant 3x](https://user-images.githubusercontent.com/2351903/44437678-ae41d580-a5d4-11e8-9bbb-4d069bce95a6.png)
![private-mode-variant 2x](https://user-images.githubusercontent.com/2351903/44437679-b00b9900-a5d4-11e8-9828-f14173223b60.png)
![private-mode-variant](https://user-images.githubusercontent.com/2351903/44437681-b3068980-a5d4-11e8-8744-a36cd6c85483.png)

[private-mode-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308569/private-mode-variant.svg.zip)

v3, a slightly smaller circle:

![private-mode-variant2 3x](https://user-images.githubusercontent.com/2351903/44437689-c3b6ff80-a5d4-11e8-96e6-cf80824b4c6a.png)
![private-mode-variant2 2x](https://user-images.githubusercontent.com/2351903/44437690-c580c300-a5d4-11e8-8367-19a6f4b69d72.png)
![private-mode-variant2](https://user-images.githubusercontent.com/2351903/44437696-c9ace080-a5d4-11e8-9fc3-4c7b027e3b23.png)

[private-mode-variant2.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308570/private-mode-variant2.svg.zip)

**Comment by goyney** [comment]
See https://github.com/Templarian/MaterialDesign/issues/2338.

**Comment by goyney** [comment]
[![robber](https://materialdesignicons.com/icon/robber)](https://materialdesignicons.com/icon/robber)[![domino-mask](https://materialdesignicons.com/icon/domino-mask)](https://materialdesignicons.com/icon/domino-mask)
