### ISSUE TITLE
Missing Google Material Design Icon

### ISSUE THREAD

**Issue by nkoterba** [Templarian/MaterialDesign#341]
We are switching over to use the MDI font set but can't seem to locate this standard google material design icon in MDI.

When we search by 'open' or 'new' nothing appears.  We have also looked through the iconset on the preview page.

Is this icon included in the set? https://github.com/google/material-design-icons/blob/master/action/svg/production/ic_open_in_new_48px.svg

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/open-in-new

It was missing. It will be in the next webfont package build that might actually be later today if I can add 8 more community icons. View the [history](http://materialdesignicons.com/history) page it will update when the webfont package is updated.

**Comment by nkoterba** [comment]
@Templarian Thanks for the quick turnaround!  Appreciate it and look forward to using the webfont package!
