### ISSUE TITLE
thermometer-10 through 100

### ISSUE THREAD

**Issue by DankRadon** [Templarian/MaterialDesign#3410]
Similar to the battery icons...

<img width="326" alt="thermomter-10--100" src="https://user-images.githubusercontent.com/30132107/44305493-30fd3300-a33e-11e8-86cc-249ee5250a88.png">

**thermomter-10**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v0V9.9h1.8v0.9v0c0.5,0.2,1,0.5,1.3,1c0.3,0.4,0.5,1,0.5,1.6
	C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-20**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v0v-0.7V9.9V9h1.8v0.9v0.3v0.7v0c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-30**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1V8.1h1.8v1.7v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-40**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1V7.3h1.8v2.5v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-50**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1V6.3h1.8v3.5v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-60**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V5.4h1.8v0.4v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-70**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V4.5h1.8v1.3v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-80**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V4V3.6h1.8V4v1.8v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-90**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V4V2.7h1.8V4v1.8v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**thermomter-100**
`<path d="M8.4,11.3c-0.3-0.6-0.7-1.1-1.3-1.5V2.7c0-0.8-0.3-1.4-0.8-1.9C5.9,0.3,5.2,0,4.5,0S3.1,0.3,2.6,0.8
	C2.1,1.3,1.8,1.9,1.8,2.7v7.1c-0.6,0.4-1,0.9-1.3,1.5c-0.3,0.6-0.5,1.3-0.5,2c0,1.3,0.5,2.3,1.3,3.1c0.9,0.8,1.9,1.3,3.2,1.3
	c1.3,0,2.3-0.5,3.2-1.3c0.9-0.8,1.3-1.9,1.3-3.1C8.9,12.6,8.8,11.9,8.4,11.3z M6.4,15.3C5.9,15.8,5.2,16,4.5,16s-1.4-0.3-1.9-0.8
	c-0.5-0.5-0.8-1.1-0.8-1.9c0-0.6,0.2-1.1,0.5-1.6c0.3-0.4,0.8-0.8,1.3-1v-1v-4v0V4V1.8h1.8V4v1.8v0v4v1c0.5,0.2,1,0.5,1.3,1
	c0.3,0.4,0.5,1,0.5,1.6C7.1,14.1,6.9,14.8,6.4,15.3z"/>`

**Comment by Templarian** [comment]
http://dev.materialdesignicons.com/contribute/github By the way you can use this to generate previews.

Related to: #3291.

**Comment by goyney** [comment]
As @Templarian stated, this is related to #3291... it's actually a duplicate. Please check that issue out and add your contributions there so we can keep all the related discussions together. Closing.
