### ISSUE TITLE
Replace

### ISSUE THREAD

**Issue by Doodlemandk** [Templarian/MaterialDesign#3411]
Hi there

We needed a replace file icon for our software at work. And we already use this icon set. So I thought, why not make one and hope you guys will include it in the set :)

![replace_file_1](https://user-images.githubusercontent.com/8899935/44308616-524f3500-a3b9-11e8-8ee0-eebd999b1403.png)

![replace_file_2](https://user-images.githubusercontent.com/8899935/44308617-524f3500-a3b9-11e8-8ae9-42da604c78f7.png)

I made two suggestions.

[replace.zip](https://github.com/Templarian/MaterialDesign/files/2303566/replace.zip)

**Comment by MrGrigri** [comment]
Would `content-duplicate` work?

![content-duplicate](https://materialdesignicons.com/icon/content-duplicate)

**Comment by MrGrigri** [comment]
After thinking about this, I have come up with a possible solution.

![document replace](https://user-images.githubusercontent.com/4528551/44352341-56369200-a461-11e8-9477-8c8696e1e604.png)

[document-replace.zip](https://github.com/Templarian/MaterialDesign/files/2303104/document-replace.zip)

**Comment by Templarian** [comment]
Is it a `duplicate` or a `replace`? I like it, just want to use the correct name.

**Comment by MrGrigri** [comment]
We should be consistent no matter what. I feel that `replace` makes more sense than `duplicate`. I would rename the current one with `content-replace` and then keep the name of the new one as is.

**Comment by Templarian** [comment]
[![file-replace-outline](https://materialdesignicons.com/icon/file-replace-outline)](https://materialdesignicons.com/icon/file-replace-outline) [![file-replace](https://materialdesignicons.com/icon/file-replace)](https://materialdesignicons.com/icon/file-replace)
