### ISSUE TITLE
Uppercase

### ISSUE THREAD

**Issue by Louistwee** [Templarian/MaterialDesign#3412]
Sugestions: https://duckduckgo.com/?q=+icon+uppercase&ia=images

**Comment by goyney** [comment]
`format-size` or `format-title` should serve this purpose, depending on the context.

For example, we use `format-title` for "All Caps" and a horizontally flipped `format-title` for "Small Caps".

**Comment by goyney** [comment]
We decided internally that we still want to make an icon for this case. Reopening.

**Comment by Templarian** [comment]
A lower case T is a `t` 😜 Not sure why it would be a slightly smaller T.

**Comment by Louistwee** [comment]
Here is a lower case icon:
![image](https://user-images.githubusercontent.com/27563848/44913626-3db25b80-ad2e-11e8-860e-6df0266347b6.png)
``m16,3c0,1,0,2,0,3c-4,0,-8,0,-12,0c0,0.67,0,1.33,0,2c4,0,8,0,12,0c0,1,0,2,0,3c1.33,-1.33,2.67,-2.67,4,-4c-1.33,-1.33,-2.67,-2.67,-4,-4ZM7.23,9c-1.41,4,-2.82,8,-4.23,12c0.52,0,1.05,0,1.57,0c0.38,-1.11,0.76,-2.23,1.14,-3.34c1.68,0,3.35,0,5.03,0c0.38,1.11,0.76,2.23,1.14,3.34c0.55,0,1.1,0,1.65,0C12.12,17,10.71,13,9.3,9c-0.69,0,-1.38,0,-2.06,0Zm0.99,1.39c0.68,1.96,1.36,3.93,2.04,5.89c-1.36,0,-2.72,0,-4.09,0c0.68,-1.96,1.36,-3.93,2.05,-5.89Zm9.94,1.38c-0.89,0.1,-2.25,0.01,-2.84,0.57c0,0.46,0,0.92,0,1.38c1.37,-0.46,2.91,-0.9,4.34,-0.38c0.64,0.1,1.4,1.9,0.37,1.73c-1.65,0.16,-3.55,0.08,-4.82,1.36c-1.12,1.28,-0.8,3.61,0.71,4.43c1.44,0.79,3.27,0.28,4.48,-0.75c0.23,-0.08,0.05,0.63,0.11,0.88c0.49,0,0.97,0,1.46,0c-0.01,-2.17,0.02,-4.35,-0.02,-6.52c-0.01,-1.26,-0.99,-2.34,-2.18,-2.53c-0.52,-0.12,-1.06,-0.16,-1.6,-0.16Zm2.34,4.5c0,0.84,0,1.67,0,2.51c-1.05,0.89,-2.59,1.44,-3.86,0.76c-0.89,-0.62,-0.73,-2.24,0.27,-2.67c1.11,-0.55,2.4,-0.46,3.6,-0.59Z``

**Comment by Templarian** [comment]
[![format-letter-case](https://materialdesignicons.com/icon/format-letter-case)](https://materialdesignicons.com/icon/format-letter-case) [![format-letter-case-upper](https://materialdesignicons.com/icon/format-letter-case-upper)](https://materialdesignicons.com/icon/format-letter-case-upper)  [![format-letter-case-lower](https://materialdesignicons.com/icon/format-letter-case-lower)](https://materialdesignicons.com/icon/format-letter-case-lower)
