### ISSUE TITLE
Remove account-settings-variant

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3413]
Years ago we let this icon slip through. Now that we have more strict guidelines this icon needs to be removed. 💀 

I would rather replace the code point with an `account-*` icon. If someone can think of an idea let me know.

**Comment by Templarian** [comment]
[![account-details](https://materialdesignicons.com/icon/account-details)](https://materialdesignicons.com/icon/account-details)

The others above have been added also.

**Comment by PeterShaggyNoble** [comment]
The alias `user-settings-variant` will need to be removed from `account-details`.

**Comment by jrlow** [comment]
> Now that we have more strict guidelines this icon needs to be removed.

Where can these stricter guidelines be found? I did not see it in the contributor guidelines.

**Comment by Templarian** [comment]
@JRLowther https://dev.materialdesignicons.com/contribute/icon-naming

**Comment by PeterShaggyNoble** [comment]
@JRLowther, specifically https://dev.materialdesignicons.com/contribute/icon-naming#naming-settings
