### ISSUE TITLE
caps-lock

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3414]
![image](https://user-images.githubusercontent.com/1015040/44365262-4639a500-a497-11e8-8792-95815c7a9444.png)

**Source:** [caps-lock.zip](https://github.com/Templarian/MaterialDesign/files/2303876/caps-lock.zip)

**Comment by Templarian** [comment]
[![caps-lock](https://materialdesignicons.com/icon/caps-lock)](https://materialdesignicons.com/icon/caps-lock)
