### ISSUE TITLE
account-cog-icon

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#3415]
I currently saw the setting-details icon got changed. Can we get the old account-cog-icon back as "account-settings-variant" or something? On the one hand I understand the adaption to google. On the other hand I used it to display technical accounts or bots. So I think there are use cases where such an icon is useful. 

Path of the old icon (I don't know how to embedd icons, sorry.)
`<path style="fill: rgba(0, 0, 0, 0.5)" ng-attr-d="{{iconDataBefore}}" d="M9,4A4,4 0 0,0 5,8A4,4 0 0,0 9,12A4,4 0 0,0 13,8A4,4 0 0,0 9,4M9,14C6.33,14 1,15.33 1,18V20H12.08C12.03,19.67 12,19.34 12,19C12,17.5 12.5,16 13.41,14.8C11.88,14.28 10.18,14 9,14M18,14C17.87,14 17.76,14.09 17.74,14.21L17.55,15.53C17.25,15.66 16.96,15.82 16.7,16L15.46,15.5C15.35,15.5 15.22,15.5 15.15,15.63L14.15,17.36C14.09,17.47 14.11,17.6 14.21,17.68L15.27,18.5C15.25,18.67 15.24,18.83 15.24,19C15.24,19.17 15.25,19.33 15.27,19.5L14.21,20.32C14.12,20.4 14.09,20.53 14.15,20.64L15.15,22.37C15.21,22.5 15.34,22.5 15.46,22.5L16.7,22C16.96,22.18 17.24,22.35 17.55,22.47L17.74,23.79C17.76,23.91 17.86,24 18,24H20C20.11,24 20.22,23.91 20.24,23.79L20.43,22.47C20.73,22.34 21,22.18 21.27,22L22.5,22.5C22.63,22.5 22.76,22.5 22.83,22.37L23.83,20.64C23.89,20.53 23.86,20.4 23.77,20.32L22.7,19.5C22.72,19.33 22.74,19.17 22.74,19C22.74,18.83 22.73,18.67 22.7,18.5L23.76,17.68C23.85,17.6 23.88,17.47 23.82,17.36L22.82,15.63C22.76,15.5 22.63,15.5 22.5,15.5L21.27,16C21,15.82 20.73,15.65 20.42,15.53L20.23,14.21C20.22,14.09 20.11,14 20,14M19,17.5A1.5,1.5 0 0,1 20.5,19A1.5,1.5 0 0,1 19,20.5C18.16,20.5 17.5,19.83 17.5,19A1.5,1.5 0 0,1 19,17.5Z"></path>`

**Comment by goyney** [comment]
Related to https://github.com/Templarian/MaterialDesign/issues/3413.

**Comment by Templarian** [comment]
Not going to be including this icon in the pack since we're following a one `settings` depiction.

There is probably a different way we can represent this... like the `robot` icon (or by adding a new icon).
