### ISSUE TITLE
Email Check

### ISSUE THREAD

**Issue by andrewnenakhov** [Templarian/MaterialDesign#3417]
An email icon for verified email. Follows same pattern as [email-plus](https://materialdesignicons.com/icon/email-plus) icon, but with a check. 

![email-check 3x](https://user-images.githubusercontent.com/2351903/44434177-2f906c80-a5c3-11e8-8697-7b918c92c1e4.png)
![email-check 2x](https://user-images.githubusercontent.com/2351903/44434178-31f2c680-a5c3-11e8-874a-0aea26ca51d5.png)
![email-check](https://user-images.githubusercontent.com/2351903/44434179-34552080-a5c3-11e8-953a-c884f99707a1.png)

[email-check.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308339/email-check.svg.zip)

**Comment by Templarian** [comment]
[![email-check](https://materialdesignicons.com/icon/email-check)](https://materialdesignicons.com/icon/email-check)

Let me know when you have 5 icons and I'll get you setup with a contributor account.
