### ISSUE TITLE
Email Check Outline

### ISSUE THREAD

**Issue by andrewnenakhov** [Templarian/MaterialDesign#3418]
An email icon for verified email. Follows same pattern as [email-plus](https://materialdesignicons.com/icon/email-plus-outline) icon, but with a check.
![email-check-outline 3x](https://user-images.githubusercontent.com/2351903/44434336-058b7a00-a5c4-11e8-9d0d-d964bc75ea94.png)
![email-check-outline 2x](https://user-images.githubusercontent.com/2351903/44434344-07edd400-a5c4-11e8-9c9e-1634cb602a77.png)
![email-check-outline](https://user-images.githubusercontent.com/2351903/44434349-0ae8c480-a5c4-11e8-85cb-2fcb42cbef2e.png)
[email-check-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308351/email-check-outline.svg.zip)

**Comment by Templarian** [comment]
[![email-check-outline](https://materialdesignicons.com/icon/email-check-outline)](https://materialdesignicons.com/icon/email-check-outline)

Let me know when you have 5 icons and I'll get you setup with a contributor account.
