### ISSUE TITLE
database-check

### ISSUE THREAD

**Issue by andrewnenakhov** [Templarian/MaterialDesign#3419]
Yet another derivative icon to represent consistent database, in a way similar to [database-plus](https://materialdesignicons.com/icon/database-plus) icon. 

![database-check 3x](https://user-images.githubusercontent.com/2351903/44435947-edb7f400-a5cb-11e8-85a0-f209d9a2cf0f.png)
![database-check 2x](https://user-images.githubusercontent.com/2351903/44435949-ef81b780-a5cb-11e8-9a43-c4e2095cd34b.png)
![database-check](https://user-images.githubusercontent.com/2351903/44435954-f3153e80-a5cb-11e8-982d-1f8273116916.png)

[database-check.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308466/database-check.svg.zip)

**Comment by Templarian** [comment]
[![database-check](https://materialdesignicons.com/icon/database-check)](https://materialdesignicons.com/icon/database-check)
