### ISSUE TITLE
database-secure

### ISSUE THREAD

**Issue by andrewnenakhov** [Templarian/MaterialDesign#3420]
Yet another derivative icon, similar to [email-secure](https://materialdesignicons.com/icon/email-secure), but with database. Might be useful to represent encrypted database.

![database-secure 3x](https://user-images.githubusercontent.com/2351903/44436038-6454f180-a5cc-11e8-81c3-6af826247d85.png)
![database-secure 2x](https://user-images.githubusercontent.com/2351903/44436040-66b74b80-a5cc-11e8-8f1a-5136391be411.png)
![database-secure](https://user-images.githubusercontent.com/2351903/44436042-6919a580-a5cc-11e8-9137-50a322b11d07.png)

Not too sure on positioning (lock shape too high?), might be better to push shape 1px down. 

[database-secure.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308476/database-secure.svg.zip)

**Comment by Templarian** [comment]
Look at `trackpad-lock` might be better in the bottom right.

(going for a run, so won't be as quick to add this one)

**Comment by andrewnenakhov** [comment]
Well, a while ago we had a discussion on lock positioning in issue #2194, where it was first suggested to place lock on the top. I did a couple of variants with lock on bottom:

v1:
![database-secure-variant 3x](https://user-images.githubusercontent.com/2351903/44436556-49d04780-a5cf-11e8-9c56-1ee66692e266.png)
![database-secure-variant 2x](https://user-images.githubusercontent.com/2351903/44436558-4c32a180-a5cf-11e8-815a-2aca4e700714.png)
![database-secure-variant](https://user-images.githubusercontent.com/2351903/44436561-4dfc6500-a5cf-11e8-8584-6fa03ac1f7ca.png)

[database-secure-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308499/database-secure-variant.svg.zip)

v2:

![database-secure-variant2 3x](https://user-images.githubusercontent.com/2351903/44436586-76845f00-a5cf-11e8-8bf6-76898e974db3.png)
![database-secure-variant2 2x](https://user-images.githubusercontent.com/2351903/44436588-797f4f80-a5cf-11e8-9183-303f62cf02e7.png)
![database-secure-variant2](https://user-images.githubusercontent.com/2351903/44436590-7c7a4000-a5cf-11e8-9a0f-ae1e0af6f3cf.png)
[database-secure-variant2.svg.zip](https://github.com/Templarian/MaterialDesign/files/2308502/database-secure-variant2.svg.zip)

Of these two, v2 is probably a better looking one, and it does not break top of database icon shape, making it easier to recognise. So I think that it's a better overall icon.

**Comment by goyney** [comment]
@andrewnenakhov You can use http://dev.materialdesignicons.com/contribute/github to generate previews for new contributions in the future.

**Comment by andrewnenakhov** [comment]
@goyney oh, so *that's* how you guys make these nice previews! Thanks. I'd suggest covering this information in wiki or in information on how to submit contributions.

**Comment by goyney** [comment]
@andrewnenakhov The information is available on the new site, so once that goes live, it will be available! That generator is actually the WIP new site.

**Comment by andrewnenakhov** [comment]
@goyney I think I'd like an option to drag .svg files there instead of extracting and pasting path data. I think My developers can add it fast if nobody minds it.

**Comment by MrGrigri** [comment]
I'm just going to say this...shouldn't all databases be secure. I know that not all are, but what would this be for?

**Comment by andrewnenakhov** [comment]
@MrGrigri for example, in android you can encrypt your Realm or SQLite database with additional encryption, and, optionally, with password.

**Comment by Templarian** [comment]
[![database-lock](https://materialdesignicons.com/icon/database-lock)](https://materialdesignicons.com/icon/database-lock)

**Comment by Templarian** [comment]
By the way, I'll get your icons transferred over shortly https://materialdesignicons.com/contributor/Andrew-Nenakhov
