### ISSUE TITLE
Add andrewnenakhov as a contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3422]
Add @andrewnenakhov as a contributor and transfer icons over.

https://materialdesignicons.com/contributor/Andrew-Nenakhov

If you have a twitter account I can link it above. Eventually you'll be able to edit the page, but not yet.

**Comment by PeterShaggyNoble** [comment]
Icons to be assigned:

- [ ] `database-check`
- [x] `database-lock`
- [ ] `email-check`
- [ ] `email-check-outline`

**Comment by goyney** [comment]
All assigned.
