### ISSUE TITLE
Origin Icon

### ISSUE THREAD

**Issue by ziyafenn** [Templarian/MaterialDesign#3424]
Hello guys. 

There are already PS and Xbox icon, but [Origin](https://en.wikipedia.org/wiki/Origin_(digital_distribution_software)#/media/File:Origin.svg) is missing!

Could you please add it. 

P.S. there is a similar rejected topic:
https://github.com/Templarian/MaterialDesign/issues/664

Thanks.

**Comment by goyney** [comment]
We're tracking issues with the Brand Icon label for a potential new brand-specific icon pack in the future.

**Comment by Templarian** [comment]
I reopened the other request. Actually let's try and get these added
