### ISSUE TITLE
YiJing(I Ching) symbols

### ISSUE THREAD

**Issue by Leroy-X** [Templarian/MaterialDesign#3426]
Hello, Very thanks for MaterialDesignIco at first, I am very hope add the YiJing symbols, please let's me make some introduction.

The Yijing is the foundation of Chinese traditional culture, and affected for 5,000 years, even longer. maybe lots know the Taichi(YinYang) symbols, and they have more.  e.g. congenital eight trigrams and acquired eight trigrams, and the Sixty-four, and the HeTu & LuoShu, TianGan and DiZhi. I am very sorry, and I don't know how to depict in English, and my English is bad too :D.

Some symbols like this:

![7490634](https://user-images.githubusercontent.com/13515498/44639106-ae830c00-a9ec-11e8-9072-c8cc987d2a90.jpg)
Maybe should to remove the text, just keep symbols, of course, they have lots symbols , but I think we just keep some classic symbols is good enough.

If you agree to add this symbols, I can help you to make the vector files, yeah I am good at the adobe illustrator. I am very hope to add this.

Thanks again.

**Comment by MrGrigri** [comment]
Thanks, @Leroy-X for the recommendation. However, these are too niche for this project. If in the future, there is a need, we would be glad to add these. 

---

[Reference](https://en.wikipedia.org/wiki/Yijing_Hexagram_Symbols)
