### ISSUE TITLE
Recessed / Can Light

### ISSUE THREAD

**Issue by dannyhanes** [Templarian/MaterialDesign#3427]
Would love to see an icon like the one shown below. Maybe include a bulb in some way? Using the Lovelace UI in HomeAssistant, entity icons are more important than ever. Thanks!

![untitled](https://user-images.githubusercontent.com/3778687/44679360-c2d50200-aa08-11e8-8160-a739e9707f21.png)

**Comment by Templarian** [comment]
Do you have an example that isn't in a perspective format? It's against the Material Design guidelines unfortunately.

**Comment by dannyhanes** [comment]
> Do you have an example that isn't in a perspective format? It's against the Material Design guidelines unfortunately.

Ahh so the icon can't be at an angle like that? Hmm...i'll see if I can drum up a better example.

**Comment by GreenTurtwig** [comment]
Duplicate of https://github.com/Templarian/MaterialDesign/issues/1826

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/wall-sconce-flat)](https://materialdesignicons.com/icon/wall-sconce-flat)
