### ISSUE TITLE
heart-plus, star-plus

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#343]
http://st.depositphotos.com/2229436/2380/v/450/depositphotos_23801173-16-web-pictogram-set.-Loupe-user-star-heart-with-plus-delete-check-mark-minus-sign.-Simple-black-icon-with-colored-element-on-white.-Solid-plain-flat-minimal-style.-Vector-illustration-in-8-eps.jpg
- [ ] heart-plus
- [ ] star-plus

**Comment by Templarian** [comment]
What does Herz mean?

**Comment by REJack** [comment]
Herz is in german hearth

**Comment by Templarian** [comment]
So, probably means `heart` which makes sense looking at the picture. :+1:

**Comment by metalla030** [comment]
Thanks for the correction

**Comment by CoDEmanX** [comment]
What's the meaning anyway?
If you want to express "add to favorites", why not use a filled and an outlined version for both states, or just the filled and change its color / opacity on state changes?

**Comment by metalla030** [comment]
filled and outlined is good.
I had found no better image to view.

**Comment by metalla030** [comment]
not colored

**Comment by CoDEmanX** [comment]
So the following

https://materialdesignicons.com/icon/heart
https://materialdesignicons.com/icon/heart-outline

https://materialdesignicons.com/icon/star-outline
https://materialdesignicons.com/icon/star-half
https://materialdesignicons.com/icon/star-outline

work for you? If so, I would close the issue. I don't think we should add too may composite icons...

**Comment by metalla030** [comment]
the plus sign is very desirable for me

**Comment by JamesCoyle** [comment]
Closing as I don't really see the use case if the UI is designed correctly.
