### ISSUE TITLE
Power Strip

### ISSUE THREAD

**Issue by mdcostas** [Templarian/MaterialDesign#3430]
Hello, there is no power-strip.
Regards.

**Comment by mdcostas** [comment]
If they work, but it's not a power strip, I thought there might be a more characteristic icon of a power strip.

**Comment by Louistwee** [comment]
this?
![image](https://user-images.githubusercontent.com/27563848/44866370-50248a80-ac85-11e8-98e0-ff2f4196caea.png)
M6 13 A2.5 2.5 0 1 1 6 18 A2.5 2.5 0 1 1 6 13 Z M5 15 L5 16 L4 16 L4 15 Z M7 15 L7 16 L8 16 L8 15 Z M12 13 A2.5 2.5 0 1 1 12 18 A2.5 2.5 0 1 1 12 13 Z M10 15 L10 16 L11 16 L11 15 Z M13 16 L14 16 L14 15 L13 15 Z M18 13 A2.5 2.5 0 1 1 18 18 A2.5 2.5 0 1 1 18 13 Z M16 16 L17 16 L17 15 L16 15 Z M19 16 L20 16 L20 15 L19 15 Z M3 14 L3 17 L2 17 L2 14 Z M2 12 Q1 12 1 13 L1 18 Q1 19 2 19 L20 19 Q21 19 21 18 L21 16 L21 16 Q23 16 23 14 L23 11 Q23 9 21 9 L3 9 Q2 9 2 8 L2 7 Q2 6 3 6 L10 6 L12 8 L14 8 L14 7 L16 7 L16 6 L14 6 L14 5 L16 5 L16 4 L14 4 L14 3 L12 3 L10 5 L3 5 Q1 5 1 7 L1 8 Q1 10 3 10 L21 10 Q22 10 22 11 L22 14 Q22 15 21 15 L21 13 Q21 12 20 12 L2 12

**Comment by MrGrigri** [comment]
Thanks for the contribution. However, the MD Guidelines state that one-pixel width is discouraged and this is full of them. Just look at the 1x version and it's not clean and instantly recognizable. This is the fear of adding such a wide element to a 24x24-pixel icon.

**Comment by goyney** [comment]
Too much detail is required for a such a large object in a small 24px grid. Too much detail already goes against the Material guidelines. Additionally, there are multiple types of electrical sockets.

**Comment by goyney** [comment]
We're going to close this issue due to the fact that we already have several `power-socket-*` variations that should suit the purpose of indicating power sources and because of the other issues raised in previous comments. Thank you for the suggestion.
