### ISSUE TITLE
mother-nurse

### ISSUE THREAD

**Issue by flaviaguaresi** [Templarian/MaterialDesign#3431]
Hi! I haven't seen any open issue for this topic. 

I have a suggest, something like the image.

![icone_amamentacao](https://user-images.githubusercontent.com/42809140/44794885-cf2f9b00-ab7f-11e8-825f-ea0c277e7d1b.jpg)

**Comment by MrGrigri** [comment]
Would this be for a Mother's Lounge?

**Comment by flaviaguaresi** [comment]
Something like that! I need to use a specific functionality for breastfeeding.

**Comment by MrGrigri** [comment]
We have decided to rename this icon to `mother-nurse` to follow our naming scheme.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48296348-a66f3000-e463-11e8-8b04-20d471bbb9ca.png)
[mother-nurse.zip](https://github.com/Templarian/MaterialDesign/files/2568021/mother-nurse.zip)

**Comment by Templarian** [comment]
[![mother-nurse](https://materialdesignicons.com/icon/mother-nurse)](https://materialdesignicons.com/icon/mother-nurse)
