### ISSUE TITLE
calculator-variant

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3432]
![image](https://user-images.githubusercontent.com/4528551/44804474-a529a900-ab7e-11e8-9900-c8a1db00532a.png)

[calculator-variant.zip](https://github.com/Templarian/MaterialDesign/files/2333127/calculator-variant.zip)

**Comment by Templarian** [comment]
[![calculator-variant](https://materialdesignicons.com/icon/calculator-variant)](https://materialdesignicons.com/icon/calculator-variant)
