### ISSUE TITLE
Transmission Tower

### ISSUE THREAD

**Issue by oengenheiro** [Templarian/MaterialDesign#3434]
I'd like to suggest transmission tower icon.

**Comment by PeterShaggyNoble** [comment]
Try the `radio-tower` icon.

**Comment by oengenheiro** [comment]
Thank you for your help, but `radio-tower` it's different what I need. I'm talking about electricity transmission towers.

**Comment by MrGrigri** [comment]
What would be the purpose of this request? And is this what you are talking about?

![electricity transmission tower](https://user-images.githubusercontent.com/4528551/44862378-cd291300-ac37-11e8-8c5e-fc3f91a23ab6.png)

**Comment by MrGrigri** [comment]
@oengenheiro, qual é o objetivo deste grafico?

**Comment by CoDEmanX** [comment]
I guess something along:

![grafik](https://user-images.githubusercontent.com/1309249/45591695-05c82c80-b95a-11e8-95d7-ff2eaee50baf.png)
![grafik](https://user-images.githubusercontent.com/1309249/45591699-0c56a400-b95a-11e8-9ba6-2881610433fd.png)

**Comment by dgomes** [comment]
The purpose of this icon is to identity an energy source.

Example: An IoT/SmartHouse software (personally thinking Home Assistant) can show energy supplied from local installed solar panels (mdi:solar-power) from the energy supplied from the public energy grid (insert name of the proposed icon)

**Comment by VDRainer** [comment]
I'm also looking for this icon.
The first suggestion from @CoDEmanX would be nice.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48296094-cf41f600-e460-11e8-9fff-935ce15e651b.png)
[transmission-tower.zip](https://github.com/Templarian/MaterialDesign/files/2567999/transmission-tower.zip)

**Comment by dgomes** [comment]
great work @goyney! thank you soo much for addressing this issue 😄 

Can I possibly suggest you make the top horizontal crossarms thinner ?

**Comment by MrGrigri** [comment]
MD guidelines require 2-pixel width lines. So, I don't believe so.

**Comment by Templarian** [comment]
[![transmission-tower](https://materialdesignicons.com/icon/transmission-tower)](https://materialdesignicons.com/icon/transmission-tower)
