### ISSUE TITLE
vector-bezier

### ISSUE THREAD

**Issue by Louistwee** [Templarian/MaterialDesign#3436]
![image](https://user-images.githubusercontent.com/27563848/44868970-aa751980-ac8c-11e8-8d57-9a8f6bca6b26.png)
Path:
``M 100 340 C 280 340 160 100 380 100 L 380 140 C 200 140 320 380 100 380 Z M 260 120 L 140 120 Q 140 140 120 140 L 100 140 Q 80 140 80 120 L 80 100 Q 80 80 100 80 L 120 80 Q 140 80 140 100 L 300 100 Q 280 100 260 120 Z M 180 380 L 340 380 Q 340 400 360 400 L 380 400 Q 400 400 400 380 L 400 360 Q 400 340 380 340 L 360 340 Q 340 340 340 360 L 220 360 Q 200 380 180 380 Z M 380 360 L 380 380 L 360 380 L 360 360 Z M 100 100 L 100 120 L 120 120 L 120 100 ``

**Comment by goyney** [comment]
We already have [`vector-curve`](https://materialdesignicons.com/icon/vector-curve). This is a good contribution, but should probably be named `vector-curve-variant` and aliased `bezier` like that one is.

**Comment by Templarian** [comment]
`vector-bezier` ^

**Comment by Templarian** [comment]
For consistency the handles should be circles.

**Comment by Louistwee** [comment]
ok I will fix that and a question: should there be handles at the ends to?

**Comment by MrGrigri** [comment]
For visual reference:

![vector-curve](https://materialdesignicons.com/icon/vector-curve)

**Comment by Templarian** [comment]
Nah, adding more handles will complicate it too much.

**Comment by Louistwee** [comment]
![image](https://user-images.githubusercontent.com/27563848/44873361-4f492400-ac98-11e8-9b92-44d84b4f0a4b.png)

**Comment by MrGrigri** [comment]
What if you squared off the ends of the lines connecting to the curve? I understand that you're following the correct cutout principle.

![image](https://user-images.githubusercontent.com/4528551/44873466-9104ab00-ac55-11e8-917c-528e0df87573.png)

**Comment by Templarian** [comment]
I like the way it's handled right now with the curved ends. Gives a cleaner connection.

**Comment by Louistwee** [comment]
idk what looks beter.
![image](https://user-images.githubusercontent.com/27563848/44873600-fc23a100-ac98-11e8-8c09-07eec4fabbee.png)

**Comment by Louistwee** [comment]
Final version:
![image](https://user-images.githubusercontent.com/27563848/44874578-e5cb1480-ac9b-11e8-893e-91068cd9964a.png)
``M 7.5,4 a 1.5,1.5 0 0 0 -1.5,1.5 1.5,1.5 0 0 0 1.5,1.5 1.5,1.5 0 0 0 1.4121094,-1 H 13 c 0.666667,-0.66667 1.333333,-1 2,-1 H 8.9121094 a 1.5,1.5 0 0 0 -1.4121094,-1 z m 11.5,1 c -11,0 -5,12 -14,12 v 2 c 11,0 5,-12 14,-12 z m -2.5,12 a 1.5,1.5 0 0 0 -1.412109,1 H 11 c -0.666667,0.66667 -1.3333333,1 -2,1 h 6.087891 a 1.5,1.5 0 0 0 1.412109,1 1.5,1.5 0 0 0 1.5,-1.5 1.5,1.5 0 0 0 -1.5,-1.5 z``

**Comment by goyney** [comment]
Let @Templarian close the issue once he adds it to the library.

**Comment by Templarian** [comment]
[![vector-bezier](http://materialdesignicons.com/icon/vector-bezier)](http://materialdesignicons.com/icon/vector-bezier)

**Comment by Templarian** [comment]
@Louistwee http://dev.materialdesignicons.com/contribute/github You can use this generate previews quickly from single paths. 😄
