### ISSUE TITLE
Setup Louistwee as a Contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3437]
Need to setup @Louistwee on the site. This will allow us to assign icons to your account.

Do you have a twitter and a preferred name/profile image (GitHub image?).

**Comment by Templarian** [comment]
http://materialdesignicons.com/contributor/Louistwee

**Comment by Louistwee** [comment]
I don't have a twitter and my preferred name is Louistwee so nothing must change for now. I will let you know when I want something to change.

**Comment by Templarian** [comment]
Sounds good. Eventually contributors will have the ability to edit this information, but it's on the backlog as low priority. http://dev.materialdesignicons.com has resource for contributors.

- http://dev.materialdesignicons.com/history
- http://dev.materialdesignicons.com/contribute/icon-naming
- http://dev.materialdesignicons.com/contribute
- http://dev.materialdesignicons.com/contribute/github

I'm wrapping up the `v2.7.94` release for this weekend so there is a small delay in adding new icons until next week. Every ~100 icons is a release (which is about once a month at this rate).
