### ISSUE TITLE
Bulldozer

### ISSUE THREAD

**Issue by Louistwee** [Templarian/MaterialDesign#3438]
![](https://user-images.githubusercontent.com/27563848/44877824-6c382400-aca5-11e8-9858-7c8f4a459e7e.png)
Path:
M 4,4.999672 c -0.5522847,0 -1,0.4477153 -1,1 v 4 1 c -0.4578817,4.53e-4 -0.8569625,0.311833 -0.96875,0.755859 v 3.216797 H 2.2871094 C 2.647753,14.369908 3.2978799,14.000762 4,13.999672 h 9 c 0.702112,10e-4 1.352346,0.370256 1.713,0.972656 h 1.318625 l -0.02344,-2.972656 h -0.0078 c 0,-0.552285 -0.448404,-0.972426 -1,-1 H 13 v -2 c 0,-0.5522847 -0.447715,-1 -1,-1 -0.552285,0 -1,0.4477153 -1,1 v 2 H 9 v -5 c 0,-0.5522847 -0.4477153,-1 -1,-1 z m 1,2 h 2 v 3 1 1 H 5 v -1 z M 17,11 v 8 h 5 V 18 L 19,17 18,11 Z M 4,15 c -1.1045695,0 -2,0.89543 -2,2 0,1.10457 0.8954305,2 2,2 h 9 c 1.104569,0 2,-0.89543 2,-2 0,-1.10457 -0.895431,-2 -2,-2 z

**Comment by MrGrigri** [comment]
I believe the part between the track and body of the bulldozer should be two pixels.

**Comment by Louistwee** [comment]
![image](https://user-images.githubusercontent.com/27563848/44943243-430db580-adc3-11e8-81bd-8b763309006e.png)
[Path.txt](https://github.com/Templarian/MaterialDesign/files/2342125/Path.txt)

**Comment by Templarian** [comment]
[![bulldozer](https://materialdesignicons.com/icon/bulldozer)](https://materialdesignicons.com/icon/bulldozer)
