### ISSUE TITLE
Chat icon

### ISSUE THREAD

**Issue by kweij** [Templarian/MaterialDesign#3439]
I'm missing a general chat icon.

I suppose it would look something like 2 slightly smaller `message-text` icons overlaying each other. One comming from the left, one comming from the right. The top one should offset somewhat to the bottom right.

Currntly only the `wechat` icon represents a chat, but it's branded.

**Comment by kweij** [comment]
It is indeed! Thanks

**Comment by Templarian** [comment]
@kweij We're also going to be adding this style #3489
