### ISSUE TITLE
electric resistor

### ISSUE THREAD

**Issue by Louistwee** [Templarian/MaterialDesign#3440]
### Resistor 1
![image](https://user-images.githubusercontent.com/27563848/44909573-31bf9d00-ad20-11e8-8a88-672f742dbef1.png)
``M 10.576172 6.5 A 0.57142857 0.5 0 0 0 10.003906 7 L 10 7 L 7.7148438 15 L 7.2929688 13.523438 A 2 2 0 0 0 8 12 A 2 2 0 0 0 6 10 A 2 2 0 0 0 4.2695312 11 L 2 11 L 2 13 L 4.2714844 13 A 2 2 0 0 0 6 14 A 2 2 0 0 0 6.2792969 13.978516 L 7.140625 16.994141 A 0.57142857 0.5 0 0 0 7.140625 17.005859 A 0.57142857 0.5 0 0 0 7.7128906 17.505859 A 0.57142857 0.5 0 0 0 8.2832031 17.005859 A 0.57142857 0.5 0 0 0 8.2832031 17 L 8.2851562 17 L 10.572266 9 L 12.857422 17 L 12.861328 17 A 0.57142857 0.5 0 0 0 12.861328 17.001953 A 0.57142857 0.5 0 0 0 13.433594 17.501953 A 0.57142857 0.5 0 0 0 14.003906 17.001953 A 0.57142857 0.5 0 0 0 14.003906 16.984375 L 16.285156 9 L 16.707031 10.476562 A 2 2 0 0 0 16 12 A 2 2 0 0 0 18 14 A 2 2 0 0 0 19.730469 13 L 22 13 L 22 11 L 19.728516 11 A 2 2 0 0 0 18 10 A 2 2 0 0 0 17.720703 10.021484 L 16.857422 7.0019531 A 0.57142857 0.5 0 0 0 16.857422 7 A 0.57142857 0.5 0 0 0 16.285156 6.5019531 A 0.57142857 0.5 0 0 0 15.714844 7 A 0.57142857 0.5 0 0 0 15.714844 7.0019531 L 13.427734 15 L 11.146484 7.0136719 A 0.57142857 0.5 0 0 0 11.146484 7 A 0.57142857 0.5 0 0 0 10.576172 6.5 z M 6 11 A 1 1 0 0 1 7 12 A 1 1 0 0 1 6 13 A 1 1 0 0 1 5 12 A 1 1 0 0 1 6 11 z M 18 11 A 1 1 0 0 1 19 12 A 1 1 0 0 1 18 13 A 1 1 0 0 1 17 12 A 1 1 0 0 1 18 11 z ``
### Resistor 2
![image](https://user-images.githubusercontent.com/27563848/44909784-f2de1700-ad20-11e8-866a-18075a9cac0e.png)

``M 10.575893,6.5 a 0.57142857,0.5 0 0 0 -0.571429,0.5 H 10 l -2.2857143,8 -1.1428571,-4 H 2 v 2 h 4 l 1.140625,3.99414 a 0.57142857,0.5 0 0 0 0,0.0117 0.57142857,0.5 0 0 0 0.5714286,0.5 0.57142857,0.5 0 0 0 0.5714286,-0.5 0.57142857,0.5 0 0 0 0,-0.006 h 0.00223 l 2.2857148,-8 2.285714,8 h 0.0045 a 0.57142857,0.5 0 0 0 0,0.002 0.57142857,0.5 0 0 0 0.571428,0.5 0.57142857,0.5 0 0 0 0.571429,-0.5 0.57142857,0.5 0 0 0 0,-0.0176 l 2.28125,-7.98438 1.142857,4 H 22 v -2 h -4 l -1.142857,-3.99805 a 0.57142857,0.5 0 0 0 0,-0.002 0.57142857,0.5 0 0 0 -0.571429,-0.49805 0.57142857,0.5 0 0 0 -0.571428,0.49805 0.57142857,0.5 0 0 0 0,0.002 l -2.285715,7.99805 -2.28125,-7.98633 a 0.57142857,0.5 0 0 0 0,-0.0137 0.57142857,0.5 0 0 0 -0.571428,-0.5 z``

**Comment by CoDEmanX** [comment]
In the first one, the space between the elements it a bit small. They kinda melt together at native size.

**Comment by Templarian** [comment]
[![resistor](https://materialdesignicons.com/icon/resistor)](https://materialdesignicons.com/icon/resistor) [![resistor-nodes](https://materialdesignicons.com/icon/resistor-nodes)](https://materialdesignicons.com/icon/resistor-nodes)

Added more space with a `1.5dp` circle.
