### ISSUE TITLE
Applicant Icon, Application Icon, Introducer Icon, Learner Icon

### ISSUE THREAD

**Issue by FarzadSole** [Templarian/MaterialDesign#3441]
I've searched all over the web and even in TheNounProject website, but there doesn't seem to be one for:-

1. Applicant
2. Application
3. Introducer
4. Learner

Thanks

**Comment by Templarian** [comment]
Do you have any examples for these for the team to look at to get an idea of what they might look like as a starting point? Even descriptions of what they might depict.

**Comment by FarzadSole** [comment]
Yes sure :)
Learner, introducer could be a person asking for a handshake or perhaps just handshake icon on its own would do it.
Application, this could simply be an application form with some checkboxes and writeups.

**Comment by CoDEmanX** [comment]
So 1+2 would be one icon, and 3+4 another?

Sounds like #330 and #2151 would partially fulfill these requests.

**Comment by goyney** [comment]
It seems like the other issues linked in this thread will fulfill this request. Closing.
