### ISSUE TITLE
content-save-settings-outline

### ISSUE THREAD

**Issue by ruslang02** [Templarian/MaterialDesign#3442]
Made an SVG, combined "content-save-settings" and "content-save-outline".

[content-save-settings-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2342297/content-save-settings-outline.svg.zip)

**Comment by Templarian** [comment]
[![content-save-settings-outline](https://materialdesignicons.com/icon/content-save-settings-outline)](https://materialdesignicons.com/icon/content-save-settings-outline)
