### ISSUE TITLE
language-spoken

### ISSUE THREAD

**Issue by Wefneck** [Templarian/MaterialDesign#3445]
Requesting language-spoken
It could be like the comment-search icon but with a globe instead of a magnifying glass.

**Comment by PeterShaggyNoble** [comment]
Could you provide a use case for this icon? Would `translate`, `earth` or `web` not suffice on their own?

**Comment by Wefneck** [comment]
I was going to use it with a suite of other icons that may already use the globe on it's own for "web". The context is to indicate the languages spoken by a cheuffeur driver. The globe on it's own might represent that the vehicle has on board internet. I could see this being used for other service staff indications like a hotel check-in, disability services or home visit doctors etc.

**Comment by MrGrigri** [comment]
Personally, I would use the `translate` icon.

**Comment by PeterShaggyNoble** [comment]
`forum` could also be an option as, with the right context, it could represent a conversation.

**Comment by Wefneck** [comment]
The voice icon could work. I didn't see that one before. Is there a way to contribute to the keyword tagging on the icon search so that more options are uncovered when searching?

**Comment by PeterShaggyNoble** [comment]
Not presently, @Wefneck, but the new site currently in development will allow people to suggest aliases. In the meantime, if you *do* have any suggestions, please create issues for them.

`voice` is currently aliased as `record-voice-over`, `speak`, `talk`, `speaking` & `talking` - do you have any others that you think should be added?

**Comment by goyney** [comment]
Closing since this issue hasn't been touched in quite some time, it seems like `voice` worked for the Wefneck, and `voice` has been aliased appropriately.
