### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by mateusppereira** [Templarian/MaterialDesign#3447]
[Sample image](https://visualpharm.com/assets/899/Track%20Order-595b40b65ba036ed117d0cc3.svg)

**Comment by PeterShaggyNoble** [comment]
Try the `map-marker-distance` icon.

[![map-marker-distance](http://mdi.houseofdesign.ie/tools/preview/?icon=map-marker-distance&action=link)](https://materialdesignicons.com/icon/map-marker-distance)

**Comment by mateusppereira** [comment]
@PeterShaggyNoble This one works for me, but the other one suggested by @Templarian would be better.

Thanks!

**Comment by Templarian** [comment]
Both of these were added.
