### ISSUE TITLE
peanut

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3448]
Need an icon to represent a product has peanuts.

**Comment by Ch-Lo** [comment]
To be honest I would not be able to guess this icon. Maybe making it diagonal helps? Also gowing with a grid instead of the dots may help also!?
https://image.flaticon.com/icons/svg/129/129995.svg

**Comment by goyney** [comment]
[![peanut](https://materialdesignicons.com/icon/peanut)](https://materialdesignicons.com/icon/peanut)[![peanut-outline](https://materialdesignicons.com/icon/peanut-outline)](https://materialdesignicons.com/icon/peanut-outline)
[![peanut-off](https://materialdesignicons.com/icon/peanut-off)](https://materialdesignicons.com/icon/peanut-off)[![peanut-off-outline](https://materialdesignicons.com/icon/peanut-off-outline)](https://materialdesignicons.com/icon/peanut-off-outline)
