### ISSUE TITLE
send-variant

### ISSUE THREAD

**Issue by gjdownes** [Templarian/MaterialDesign#3449]
Kindly include a new Send variant to match the new Android Messages icon.

![image](https://user-images.githubusercontent.com/103374/45007047-dd3f4a80-afc9-11e8-97ae-a91beecb1435.png)

Keep up the great work.

**Comment by Templarian** [comment]
Got a screenshot?

**Comment by MrGrigri** [comment]
Is that the same as the 'rounded' version on MD Icons? https://material.io/tools/icons/?search=send&icon=send&style=round

**Comment by gjdownes** [comment]
Yep, that's the one.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/45039472-f0c9d000-b020-11e8-9475-cbd66ce78a36.png)

[send-variant.zip](https://github.com/Templarian/MaterialDesign/files/2349145/send-variant.zip)

**Comment by PeterShaggyNoble** [comment]
Going to close this out for now as we're currently focused on adding the outline variants of existing icons. Round and sharp are going to be a good bit down the road.
