### ISSUE TITLE
Sitemap-outline

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3450]
Found on https://search.google.com/search-console?hl=en

![grafik](https://user-images.githubusercontent.com/1309249/45113727-6df16400-b14b-11e8-8f28-a0e523731bba.png)

[sitemap-outline.zip](https://github.com/Templarian/MaterialDesign/files/2354089/sitemap-outline.zip)

It's not pixel-perfect. It can be shifted 0.5px to the left to make it crisper, but then the free space inside the rectangles will not be aligned. Maybe make it smaller altogether to get it on grid?

**Comment by Templarian** [comment]
I'm thinking of closing this one since it's kind of "off" pixel wise.

**Comment by CoDEmanX** [comment]
What about the icon in general? We can tweak it to be on-grid.

**Comment by CoDEmanX** [comment]
Wait, is there a filled variant somewhere? Our sitemap icon is way different, and better fitting for sitemap IMO. This Google icon is more like a file tree or hierarchical structure, which could also be useful. Shouldn't be too hard to create a full set of all the variants.

**Comment by PeterShaggyNoble** [comment]
@CodeManX, you're correct; this is our `file-tree` icon, which is why I retitled the issue.

![](http://mdi.houseofdesign.ie/tools/preview/?icon=file-tree)
