### ISSUE TITLE
Minus-one

### ISSUE THREAD

**Issue by cpelegrin** [Templarian/MaterialDesign#3451]
include "-1" icon

**Comment by PeterShaggyNoble** [comment]
Google have one in their extended icon set that we could use:

![](http://mdi.houseofdesign.ie/tools/preview/?icon=exposure-minus-1)

**Comment by goyney** [comment]
Should this be the Extended Set version or a version of our numeric 1?

**Comment by goyney** [comment]
Our font:
![image](https://user-images.githubusercontent.com/1015040/62588701-b4d46600-b894-11e9-8da7-c253e55a0d23.png)

_vs_

Google's Extended:
![image](https://user-images.githubusercontent.com/1015040/62588746-d9304280-b894-11e9-82b0-e17bfe436c35.png)

**Comment by MrGrigri** [comment]
I personally believe we should use ours.

**Comment by goyney** [comment]
[![numeric-negative-1](https://materialdesignicons.com/icon/numeric-negative-1)](https://materialdesignicons.com/icon/numeric-negative-1)
