### ISSUE TITLE
External Link

### ISSUE THREAD

**Issue by fromA-Z** [Templarian/MaterialDesign#3452]
I see Google's already has it but it would be really useful if you included it in yours also

**Comment by goyney** [comment]
Do you mean...

[![image](https://user-images.githubusercontent.com/1015040/45165221-55706080-b1c2-11e8-8432-3369b6b91b98.png)](https://materialdesignicons.com/icon/link
)

**Comment by Templarian** [comment]
I don't see anything in their pack called "external link". We have an alias for `open-in-new`.

[![open-in-new](https://materialdesignicons.com/icon/open-in-new)](https://materialdesignicons.com/icon/open-in-new)

**Comment by PeterShaggyNoble** [comment]
They call theirs `launch`, which we have as a separate icon.

**Comment by MrGrigri** [comment]
There is also `open-in-app`.

**Comment by Templarian** [comment]
Closing this issue. Let us know if these don't work. Please paste an example image or detailed description and we'll reopen.
