### ISSUE TITLE
check-in with calendar icon and check-out with calendar

### ISSUE THREAD

**Issue by greguintow** [Templarian/MaterialDesign#3454]

**Comment by Templarian** [comment]
Do you have an example? Images can be pasted in comments.

**Comment by MrGrigri** [comment]
What about something like this?

![image](https://user-images.githubusercontent.com/4528551/45304320-13eaf880-b4d5-11e8-8e08-346466156e68.png) ![image](https://user-images.githubusercontent.com/4528551/45304352-26653200-b4d5-11e8-80d4-c2b32de217f0.png)

[calendar-checkin.zip](https://github.com/Templarian/MaterialDesign/files/2367071/calendar-checkin.zip)

**Comment by goyney** [comment]
I don't know if I like the `checkout` variation, the arrow cutout feels weird.

**Comment by Templarian** [comment]
Agreed we may went to use the [corner arrows](https://dev.materialdesignicons.com/contribute/icon-naming) maybe or find a different way to do the cut out.

I like the arrow inside but the checkout may need to be an angled cut out.

**Comment by CoDEmanX** [comment]
Looks better with the up and down arrows, but I don't think I would use them for like hotel check-in and -out. It's more like import and export to/from calender. For check-in / -out time, there are `clock-in` and `clock-out`.

**Comment by Templarian** [comment]
[![calendar-export](https://materialdesignicons.com/icon/calendar-export)](https://materialdesignicons.com/icon/calendar-export) [![calendar-import](https://materialdesignicons.com/icon/calendar-import)](https://materialdesignicons.com/icon/calendar-import)

**Comment by greguintow** [comment]
Yes, is like that what I want thanks very much.

Em seg, 10 de set de 2018 às 11:41, Michael Richins <
notifications@github.com> escreveu:

**Comment by greguintow** [comment]
Sorry, to answer so late

Em dom, 16 de set de 2018 às 17:06, Thunder Dance <thunderdance6@gmail.com>
escreveu:
