### ISSUE TITLE
So many lost icons on Google Play Categories

### ISSUE THREAD

**Issue by Mancerrss** [Templarian/MaterialDesign#3456]
There's so many lost Material design iconography in the Google Play's sa Categories, from Apps, to Games, Movies, Newsstand and Music. I hope you guys able to add them all to our repository. 

I'm sick and tired of Google not updating their Icon tool nor their repo so we better just do it ourselves

**Comment by Templarian** [comment]
Most of these exist they may just have more generic names. If you can link to specific ones we're missing that would be helpful. Closing for now since I'm not sure which ones you're specifically requesting.

**Comment by PeterShaggyNoble** [comment]
See also #1022
