### ISSUE TITLE
Feedback & Testimonials icon

### ISSUE THREAD

**Issue by Mukeshkrjha** [Templarian/MaterialDesign#3461]
Hi,

Please **create a icon pack for feedback and testimonials**. I think it is completely missing as of now.

Thanks
Regards,
Mukesh

**Comment by Mukeshkrjha** [comment]
Yes, I'm aware of them but it would nice to have more collection. For
reference please check attached one.
[image: testimonial (1).png]

**Comment by Templarian** [comment]
@Mukeshkrjha Email attachments don't work. Please paste the image into a comment.

**Comment by Mukeshkrjha** [comment]
PFA

![image](https://user-images.githubusercontent.com/2878088/45318268-f8760100-b559-11e8-9625-0e6e5564e4a5.png)

**Comment by Mukeshkrjha** [comment]
Cool :)

**Comment by goyney** [comment]
[![comment-quote](https://materialdesignicons.com/icon/comment-quote)](https://materialdesignicons.com/icon/comment-quote)[![comment-quote-outline](https://materialdesignicons.com/icon/comment-quote-outline)](https://materialdesignicons.com/icon/comment-quote-outline)
