### ISSUE TITLE
Update Google Fit Icon

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3462]
Google has rebranded their [Google Fit](https://www.google.com/fit/) icon.

**Comment by David-Jackson** [comment]
![google-fit](https://user-images.githubusercontent.com/11835431/45374587-93092b00-b5c0-11e8-8662-85eebe4e3403.png)

[google-fit.zip](https://github.com/Templarian/MaterialDesign/files/2371930/google-fit.zip)

**Comment by David-Jackson** [comment]
Thanks for the tip @MrGrigri.

![image](https://user-images.githubusercontent.com/11835431/45376861-e9796800-b5c6-11e8-8cbc-826e99b85722.png)

[google-fit.zip](https://github.com/Templarian/MaterialDesign/files/2372063/google-fit.zip)

**Comment by MrGrigri** [comment]
Thanks.

**Comment by Templarian** [comment]
[![google-fit](https://materialdesignicons.com/icon/google-fit)](https://materialdesignicons.com/icon/google-fit)
