### ISSUE TITLE
Redesigned bullhorn

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3463]
[![](https://user-images.githubusercontent.com/15905797/45314677-47a43d80-b52a-11e8-97e2-3a936e81a067.png)](https://github.com/Templarian/MaterialDesign/files/2367794/megaphone.zip)

**Comment by Templarian** [comment]
Done, both this one and `outline` are in. I assigned them both to Google due to the kind of derived nature.

**Comment by CoDEmanX** [comment]
How about a sharp and a rounded variant?

![grafik](https://user-images.githubusercontent.com/1309249/45590868-5718f180-b943-11e8-881f-eed5b0fde304.png)

![grafik](https://user-images.githubusercontent.com/1309249/45591148-ca256680-b949-11e8-84c2-4568dba9a9db.png)

The rounded one uses a corner radius of 2px, which I think is the correct one to use, although it looks like a slightly smaller radius compared to the bottom corners.

[megaphone.zip](https://github.com/Templarian/MaterialDesign/files/2386140/megaphone.zip)

**Comment by CoDEmanX** [comment]
Forgot about two-tone... I checked a two-tone icon from Google, and what they use is apparently a secondary path for the fill, with no color set (defaults to black) and a style `opacity: 0.3`. So here's my attempt at a two-toned base style megaphone:

![grafik](https://user-images.githubusercontent.com/1309249/45591180-6a2fbf80-b94b-11e8-9ab4-a2e360716619.png)

![grafik](https://user-images.githubusercontent.com/1309249/45591175-381e5d80-b94b-11e8-818e-1792fd5d75fd.png)

[megaphone-two-tone.zip](https://github.com/Templarian/MaterialDesign/files/2386154/megaphone-two-tone.zip)

**Comment by Templarian** [comment]
@CoDEmanX We don't support the round and sharp at this time. Just regular and outline. We may revise that in the future.
