### ISSUE TITLE
ArtStation Icon (Brand)

### ISSUE THREAD

**Issue by NOMADE55** [Templarian/MaterialDesign#3464]
This is not really my "creation" since it's a brand logo.
I'm attaching the .svg

Hope it's okay.
[artstation.zip](https://github.com/Templarian/MaterialDesign/files/2368190/artstation.zip)

**Comment by Templarian** [comment]
[![artstation](https://materialdesignicons.com/icon/artstation)](https://materialdesignicons.com/icon/artstation)

All brand logo's are assigned to the shared contributor account anyway.
