### ISSUE TITLE
account-admin 

### ISSUE THREAD

**Issue by hvbhome** [Templarian/MaterialDesign#3465]
HI,
Searched the archive for admin requests and did find these. But they we never fulfilled, as far as I can see. There's the Crown  and the supervisor (which is rather abstract showing 2 people...) but no account-admin with, let me suggest, as others have done before i think, the regular account with a cogwheel.
Would be really helpful to add that to the other available account variants, hope you would consider,
thx!

a bit like this:

![](https://i.pinimg.com/736x/5d/ef/9e/5def9e6a539f1d70d8b513130b6a4e93--configuration-administration.jpg)

obviously in the MDI style

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/contribute/icon-naming

Cogs are not used for settings in MD. `...` are.

**Comment by Templarian** [comment]
@hvbhome Those are cogs not settings icons. 😛

The team came to the decision a few releases ago to remove any settings icons with cogs (there was one) and replace them with dots. So unfortunately this will not be added.

**Comment by PeterShaggyNoble** [comment]
If you *really* need this icon, it's still available in [the Sandbox](https://petershaggynoble.github.io/MDI-Sandbox/). However, I'd personally suggest using one of the [`account-supervisor`](https://petershaggynoble.github.io/MDI-Sandbox/?filter=supervisor) icons for this purpose.

**Comment by hvbhome** [comment]
Yes, thats exactly what I was looking for, 🙏 

The google supervisor is rather silly tbh, and has no visual clue to an admin at all, imho.
This is what’s needed indeed. Hope to be able to get HomeAssistant use it natively. 

Thanks again for saving it for me ;-)

**Comment by hvbhome** [comment]
well. I can use the icon, though not as Homeassistant handles its icons, but as an entity_picture. Which means all nice things we can do with the icons aren't an option. with this as result:

![schermafbeelding 2018-09-12 om 07 56 50](https://user-images.githubusercontent.com/33354141/45405045-a3bdad80-b661-11e8-9fd6-c3b2fb1cd794.jpg)

Hope you can see i _really_ need it @PeterShaggyNoble ;-) and therefor still hope with all powers in me...you might  want to reconsider retiring (!) the icon. ..Please?

**Comment by PeterShaggyNoble** [comment]
If Home Assistant doesn't offer you the ability to use individual icons then that's something you would need to take up with them.
