### ISSUE TITLE
dog-service fix

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3466]
Thinking about it more, I believe the `dog-service` needs to be fixed. I removed the collar and added the straps for the vest. Thoughts?

![image](https://user-images.githubusercontent.com/4528551/45385139-3d874b00-b5cd-11e8-99c6-4d4431f04b75.png) ![image](https://user-images.githubusercontent.com/4528551/45384978-dec1d180-b5cc-11e8-9a4f-753a212679de.png)

[dog-service-updated.zip](https://github.com/Templarian/MaterialDesign/files/2372560/dog-service-updated.zip)

**Comment by goyney** [comment]
Too much detail, IMO. Just drop the collar and straps perhaps?

**Comment by PeterShaggyNoble** [comment]
I'd say keep the collar for consistency with `dog-side`.

**Comment by MrGrigri** [comment]
I'm okay with either, I just thought I was more correct to have the straps instead of the collar. @Templarian, thoughts?

**Comment by CoDEmanX** [comment]
Little experiment:

![grafik](https://user-images.githubusercontent.com/1309249/45591242-5a18df80-b94d-11e8-9eb7-d161de726392.png)

**Comment by MrGrigri** [comment]
Going to close this out as the current one should suffice.
