### ISSUE TITLE
telescope

### ISSUE THREAD

**Issue by mcaminiti** [Templarian/MaterialDesign#3467]
A telescope icon to be used for star events or tracking information would be nice to have. 
![th](https://user-images.githubusercontent.com/11096302/45387839-e8533580-b5dc-11e8-88ea-21b44c1b598a.jpeg)
![city-telescope-icon](https://user-images.githubusercontent.com/11096302/45387841-eab58f80-b5dc-11e8-848a-c2aeea36d439.png)

Example images attached of what it could look like.

**Comment by SarinManS** [comment]
How is this?

![image](https://user-images.githubusercontent.com/26505215/45467410-2cf6e200-b73f-11e8-9aa6-a36776c6a4a6.png)
[Telescope.zip](https://github.com/Templarian/MaterialDesign/files/2377709/Telescope.zip)

**Comment by mcaminiti** [comment]
Perfect!

**Comment by MrGrigri** [comment]
@SarinManS, you beat me to it. ;)

**Comment by Templarian** [comment]
[![telescope](https://materialdesignicons.com/icon/telescope)](https://materialdesignicons.com/icon/telescope)
