### ISSUE TITLE
playlist-note

### ISSUE THREAD

**Issue by dieisraels** [Templarian/MaterialDesign#3468]
I miss the official icon "queue_music":
https://material.io/tools/icons/?search=music&icon=queue_music&style=baseline

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/46388814-71213680-c69c-11e8-9dc7-11028858ad2a.png)

[playlist-music.zip](https://github.com/Templarian/MaterialDesign/files/2440473/playlist-music.zip)

**Comment by Templarian** [comment]
[![playlist-music](https://materialdesignicons.com/icon/playlist-music)](https://materialdesignicons.com/icon/playlist-music) [![playlist-music-outline](https://materialdesignicons.com/icon/playlist-music-outline)](https://materialdesignicons.com/icon/playlist-music-outline)
