### ISSUE TITLE
Alias New Alphanumeric Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3469]
A reminder for myself to add aliases to the new `alpha-*` & `numeric-*` icons when I have time.

- [x] `alphabet-*`
- [x] `alphabet-*-box`
- [x] `letter-*`
- [x] `letter-*-box`
- [x] `number-*`
- [x] `numeric-[word]`

**Comment by Templarian** [comment]
I'm going to be adding `*-box` versions of all of these also. So just a heads up.

**Comment by PeterShaggyNoble** [comment]
Done
