### ISSUE TITLE
Icon Request: admin 

### ISSUE THREAD

**Issue by mddanishansari** [Templarian/MaterialDesign#3470]
I would like to request new icon for **admin** as I didn't found in\t in the cheatsheet.

I saw #270  but it's pretty much dried.

Examples of **admin**  could be something like this:

![](https://cdn.onlinewebfonts.com/svg/img_325788.png)

OR 

![](https://static.thenounproject.com/png/228840-200.png)

Pretty bad examples but that's what I found.

**Comment by MrGrigri** [comment]
There is already a `security-account`, `account-settings`, and `account-supervisor`. Notice that MD does not use the cog as an identifier for settings, they use three dots.

![security-account](https://materialdesignicons.com/icon/security-account) ![account-settings](https://materialdesignicons.com/icon/account-settings) ![account-supervisor](https://materialdesignicons.com/icon/account-supervisor)

**Comment by PeterShaggyNoble** [comment]
See also #3413, #3415 and #3465.
