### ISSUE TITLE
How do I add the first 5 icons?

### ISSUE THREAD

**Issue by burndragon** [Templarian/MaterialDesign#3471]
I have created a few different icons I would like to add but do not see an area in which to do so.

**Comment by PeterShaggyNoble** [comment]
Create an individual issue for each here - related icons (e.g., icons with modifiers or variants) can be grouped in the same issue and we'll take it from there.

**Comment by Templarian** [comment]
@burndragon http://dev.materialdesignicons.com/contribute/github You can use this to create fancy previews. 😃
