### ISSUE TITLE
barn

### ISSUE THREAD

**Issue by burndragon** [Templarian/MaterialDesign#3473]
barn icon
![barn](https://user-images.githubusercontent.com/43213826/45439973-c9a67a80-b680-11e8-9d57-69c95ba70ff9.png)
[barn.svg.zip](https://github.com/Templarian/MaterialDesign/files/2376088/barn.svg.zip)

**Comment by SarinManS** [comment]
This might work better
![image](https://user-images.githubusercontent.com/26505215/45608934-3b156d00-ba75-11e8-91bd-1050a404249d.png)
[barn.zip](https://github.com/Templarian/MaterialDesign/files/2387529/barn.zip)

**Comment by Templarian** [comment]
@SarinManS I think this needs to be sized down to 18x18, 20dp is too large proportionally.

**Comment by SarinManS** [comment]
Yup, I see what you mean.
![image](https://user-images.githubusercontent.com/26505215/45665127-20073380-bb2f-11e8-939d-54686a20a514.png)
[barn.zip](https://github.com/Templarian/MaterialDesign/files/2391220/barn.zip)

**Comment by Templarian** [comment]
[![barn](https://materialdesignicons.com/icon/barn)](https://materialdesignicons.com/icon/barn)

Assigned this one to the shared contributor account since it was very closely derived from @burndragon's.
