### ISSUE TITLE
chevron-*-circle

### ISSUE THREAD

**Issue by francisschmaltz** [Templarian/MaterialDesign#3475]
Full set of chevron icons that are enclosed in a circle.

- [ ] `chevron-up-circle`
- [ ] `chevron-right-circle`
- [ ] `chevron-down-circle`
- [ ] `chevron-left-circle`

**Comment by francisschmaltz** [comment]
Looks good!

**Comment by Templarian** [comment]
Added all 8 icons. Thanks @SarinManS! 😺
