### ISSUE TITLE
Uber Logo 2018

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3476]
It's another year so Uber has done another full rebrand.

https://www.uber.design/case-studies/rebrand-2018

**Comment by David-Jackson** [comment]
![image](https://user-images.githubusercontent.com/11835431/45495287-f8842580-b740-11e8-952d-62630f9a50a4.png)

![image](https://user-images.githubusercontent.com/11835431/45495351-1a7da800-b741-11e8-9a6b-bd8a8f23a555.png)

![image](https://user-images.githubusercontent.com/11835431/45495332-12be0380-b741-11e8-8aae-d2d81e89441f.png)

[uber.zip](https://github.com/Templarian/MaterialDesign/files/2379752/uber.zip)

**Comment by PeterShaggyNoble** [comment]
Hmm ... not very legible at 24*24. Can you try the first one with the path width increased to 20?

**Comment by David-Jackson** [comment]
![image](https://user-images.githubusercontent.com/11835431/45496794-42223f80-b744-11e8-9654-6d97bcbf1217.png)

Still not super legible at 24px. The other thing mentioned in the rebranding is the ["U"](https://www.uber.design/case-studies/rebrand-2018#section-3), but I haven't seen any usages of it as an icon: 

![image](https://user-images.githubusercontent.com/11835431/45497406-b7dadb00-b745-11e8-8f2a-5e2e35d4ad12.png)

[uber.zip](https://github.com/Templarian/MaterialDesign/files/2379909/uber.zip)

**Comment by MrGrigri** [comment]
Yeah, let's not use the 'U' for their logo. I believe the 'Uber' text that is 20-pixels wide is best. No need to add the variants. Also, could you align the baseline to the grid...preferably down?

**Comment by Templarian** [comment]
Agreed with @MrGrigri. Thanks @David-Jackson, will get this updated tonight. Need at add Lyft also.

**Comment by Templarian** [comment]
[![uber](https://materialdesignicons.com/icon/uber)](https://materialdesignicons.com/icon/uber)
