### ISSUE TITLE
Lyft

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3477]
Taken from their [press page](https://www.lyft.com/press) and adapted to the 24x24-pixel profile.

![image](https://user-images.githubusercontent.com/4528551/45500408-d50aac00-b73b-11e8-8c71-60b2ac6915dd.png)

[lyft.zip](https://github.com/Templarian/MaterialDesign/files/2380100/lyft.zip)

**Comment by Templarian** [comment]
[![lyft](https://materialdesignicons.com/icon/lyft)](https://materialdesignicons.com/icon/lyft)
