### ISSUE TITLE
automation

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3478]
![image](https://user-images.githubusercontent.com/4528551/45507112-68e57380-b74e-11e8-8368-500cc3a85577.png)

[automation.zip](https://github.com/Templarian/MaterialDesign/files/2380515/automation.zip)

**Comment by CoDEmanX** [comment]
Maybe alias with industrial-robot?

**Comment by Templarian** [comment]
Since the name of the icon can be represented by a noun `robot-industrial` probably works nicer for this.

[![robot-industrial](https://materialdesignicons.com/icon/robot-industrial)](https://materialdesignicons.com/icon/robot-industrial)
