### ISSUE TITLE
Workplace by Facebook

### ISSUE THREAD

**Issue by oneillsp96** [Templarian/MaterialDesign#3479]
![image](https://user-images.githubusercontent.com/7624535/45557231-20d85680-b80b-11e8-9ba1-33708d1a5f0a.png)

**Comment by David-Jackson** [comment]
![image](https://user-images.githubusercontent.com/11835431/45564931-00ff5d80-b820-11e8-8240-e97591fa640f.png)

[facebook-workplace.zip](https://github.com/Templarian/MaterialDesign/files/2384254/facebook-workplace.zip)

**Comment by Templarian** [comment]
[![facebook-workplace](https://materialdesignicons.com/icon/facebook-workplace)](https://materialdesignicons.com/icon/facebook-workplace)

@David-Jackson Just a heads up so there isn't any confusion. Brand icons are assigned to the shared contributor account. But I still count it toward the 5 required for getting a contributor page setup. 😃
