### ISSUE TITLE
Natural mating

### ISSUE THREAD

**Issue by dabielkabuto** [Templarian/MaterialDesign#348]
Will be thankful for a mating icon. Not for humans, I mean any animal mating. My app records matings for pedigree purposes.

**Comment by Templarian** [comment]
Do you have an example?

**Comment by dabielkabuto** [comment]
For example: https://www.iconfinder.com/search/?q=reproduction

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/reproduction

I couldn't get 2 bunnies into the small icon to look right, but if you're targeting the web you can use the below CSS animation.

http://codepen.io/templarian/pen/LVZwRx
