### ISSUE TITLE
Injection

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [Templarian/MaterialDesign#3480]
Injection icon

**Comment by PeterShaggyNoble** [comment]
Sounds like you're looking for the `needle` icon. I'll alias it as `injection` momentarily.

[![needle](http://mdi.houseofdesign.ie/tools/preview/?icon=needle&action=link)](https://materialdesignicons.com/icon/needle)

**Comment by PeterShaggyNoble** [comment]
Alias added. 

@iAmAndroidDeveloper, can you confirm that this was the icon you were looking for so we can close this issue out or provide more information and an example if not.

**Comment by CoDEmanX** [comment]
Even in the sense of dependency injection, it would kinda make sense to use the needle icon.

**Comment by iAmAndroidDeveloper** [comment]
yes , thanks man, 

good work , keep it up......>
