### ISSUE TITLE
spaghetti/noodles

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#3481]
Would love to have access to cuisine/food type icons:

- [x] Asian - `rice`
- [ ] Italian - 
- [x] Mexican - `taco`
- [x] Burgers - `hamburger`
- [x] Pizza - `pizza`
- [ ] Noodles - 

For inspiration, you can see the list of restaurant types and their icons
https://developer.foursquare.com/docs/resources/categories

Thanks!

**Comment by SarinManS** [comment]
Mexican taco
[food-mexican.zip](https://github.com/Templarian/MaterialDesign/files/2391368/food-mexican.zip)
![image](https://user-images.githubusercontent.com/26505215/45667557-66619000-bb39-11e8-9b8e-8061d3d6da5e.png)

**Comment by JamesCoyle** [comment]
Icons can't be dimensional. We also already have a pizza icon and a bowl of rice.

**Comment by SarinManS** [comment]
How does this look?

![image](https://user-images.githubusercontent.com/26505215/45682879-683f4980-bb61-11e8-959b-197e90dcd1cf.png)

**Comment by SarinManS** [comment]
@PeterShaggyNoble Can't unsee it now 😆

**Comment by CoDEmanX** [comment]
The first one isn't too bad IMO, it's kind of has pseudo-perspective, like a flattened ortographic view. Google did some similar icons:

![grafik](https://user-images.githubusercontent.com/1309249/45949178-4d565480-bffb-11e8-8f15-2be625407bda.png) ![grafik](https://user-images.githubusercontent.com/1309249/45949212-72e35e00-bffb-11e8-9138-0500d2165edd.png)

**Comment by goyney** [comment]
All but Italian and noodles have been added. Updating this issue to request a noodle-type icon that may server both.

**Comment by JamesCoyle** [comment]
Google maps has some icons which might be relevant:
![image](https://user-images.githubusercontent.com/10384436/62744244-9a89bc00-ba3d-11e9-87fd-b7ed574be0ab.png)

**Comment by goyney** [comment]
My recreation from that screenshot:
![image](https://user-images.githubusercontent.com/1015040/63068811-9d275e00-bee2-11e9-8985-420ef9c04ba9.png)
[food-italian.svg.zip](https://github.com/Templarian/MaterialDesign/files/3504093/food-italian.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Here's Google's version of it, from Material Icons Extended (and with @goyney's version overlaid for comparison):

[![dinner-dining](https://user-images.githubusercontent.com/15157491/63092133-99ceb980-bf58-11e9-97da-8d1a3ba4f4da.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/) ![image](https://user-images.githubusercontent.com/15157491/63092162-bb2fa580-bf58-11e9-83d9-562b3debfcd1.png)

**Comment by goyney** [comment]
Well, I didn't do too bad there, did I? 😆 

We'll obviously use Google's version.

**Comment by goyney** [comment]
[![noodles](https://materialdesignicons.com/icon/noodles)](https://materialdesignicons.com/icon/noodles)
