### ISSUE TITLE
Icons not attributed

### ISSUE THREAD

**Issue by SarinManS** [Templarian/MaterialDesign#3482]
Hi

Some of the icons I made and uploaded are listed under the contributors tag  but don't appear under my tag. I don't know if they are yet to be verified or if the final version wasn't mine... so just wanted to know :)

Icons:
- [x] bank-transfer
- [x] bank-transfer-in
- [x] bank-transfer-out
- language-ruby-on-rails
- laravel
- shopify
- symfony
- z-wave
- zend

Thanks guys.

**Comment by PeterShaggyNoble** [comment]
Note that brand icons are always assigned to the community "Contributor" account, so it's just the first 3 that need to be reassigned to you.

On the subject of reassigning icons: `uber` also needs to be updated to the "Contributor" account.

**Comment by Templarian** [comment]
Updated the list above with the 3 that need to be set. Yea, I've slowly been reassigning all the brand icons as I have time to the contributor account. I don't have a UI for that so each has to be done by hand in the DB.

**Comment by SarinManS** [comment]
Oh didn't know about the brand icon. Thanks guys

**Comment by goyney** [comment]
`windows-classic` is attributed to me. Probably should be updated to the Contributor account as well.

**Comment by Templarian** [comment]
Fixed. 😃
