### ISSUE TITLE
Ubisoft (Uplay)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3483]
Reposted request for a [Uplay](https://uplay.ubi.com/) from #664.

**Comment by David-Jackson** [comment]
![image](https://user-images.githubusercontent.com/11835431/45622949-ba924480-ba53-11e8-8092-48ca7de0ca4a.png)

[uplay.zip](https://github.com/Templarian/MaterialDesign/files/2388555/uplay.zip)

This is technically the Ubisoft logo. Do we want to include the the "UPLAY" text in the icon?

**Comment by PeterShaggyNoble** [comment]
We should probably name it `ubisoft`, so, and alias it as `uplay`.

**Comment by Templarian** [comment]
[![ubisoft](https://materialdesignicons.com/icon/ubisoft)](https://materialdesignicons.com/icon/ubisoft)
