### ISSUE TITLE
GOG.com

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3484]
Reposted request for a [GOG.com](https://www.gog.com/) from #664.

**Comment by David-Jackson** [comment]
![image](https://user-images.githubusercontent.com/11835431/45622486-25428080-ba52-11e8-85fc-ff71adc4daaa.png)

[gog.zip](https://github.com/Templarian/MaterialDesign/files/2388488/gog.zip)

**Comment by Templarian** [comment]
@David-Jackson When formatting icons, try and remove all the extra points. Got it down to `190` it was like `316` somehow.

[![gog](https://materialdesignicons.com/icon/gog)](https://materialdesignicons.com/icon/gog)
