### ISSUE TITLE
filter-remove-variant

### ISSUE THREAD

**Issue by waister** [Templarian/MaterialDesign#3485]
Add icon filter variant close/cancel, opposition to filter-variant.

**Comment by David-Jackson** [comment]
Using the existing `filter-remove` as an example:

![image](https://user-images.githubusercontent.com/11835431/45625098-152e9f00-ba5a-11e8-86c6-90766945824d.png)

[filter-remove-variant.zip](https://github.com/Templarian/MaterialDesign/files/2388673/filter-remove-variant.zip)

**Comment by goyney** [comment]
[![filter-variant-remove](https://materialdesignicons.com/icon/filter-variant-remove)](https://materialdesignicons.com/icon/filter-variant-remove)
