### ISSUE TITLE
read-more

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3486]
I'm not quite sure what to call this, but it's to symbolize that there is more to read.

![image](https://user-images.githubusercontent.com/4528551/45654092-72951100-ba97-11e8-95b0-644f1692409f.png)

[readmore.zip](https://github.com/Templarian/MaterialDesign/files/2390498/readmore.zip)

**Comment by Templarian** [comment]
Maybe we could make a page next and a page previous type icon with these. I also like the `read-more` idea of this icon.

**Comment by MrGrigri** [comment]
How about adding `read-more` as an alias and then adding the two as `page-next` and `page-previous`.

![image](https://user-images.githubusercontent.com/4528551/46303571-6f0a8b00-c569-11e8-8899-075dce2bf80a.png) ![image](https://user-images.githubusercontent.com/4528551/46303595-847fb500-c569-11e8-8fdb-ef4e8893a741.png)

![image](https://user-images.githubusercontent.com/4528551/46303646-9c573900-c569-11e8-99b5-30ad2362664d.png) ![image](https://user-images.githubusercontent.com/4528551/46303660-a9742800-c569-11e8-80d9-d14490db12ac.png)

[page-next__page-previous.zip](https://github.com/Templarian/MaterialDesign/files/2434908/page-next__page-previous.zip)

**Comment by Templarian** [comment]
Added. 😺
