### ISSUE TITLE
alphabetical-off

### ISSUE THREAD

**Issue by danik121** [Templarian/MaterialDesign#3487]
example
![untitled](https://user-images.githubusercontent.com/8233518/45738338-6a041e00-bbf0-11e8-9091-e99fafefbfcf.png)

please add icon not contain

**Comment by MrGrigri** [comment]
Please be a bit more descriptive, e.g. give examples and use cases.

**Comment by MrGrigri** [comment]
Here is the `-off` version of our current `alphabetical` icon.

![image](https://user-images.githubusercontent.com/4528551/46302384-243b4400-c566-11e8-926a-5a2c93aac212.png)

However, I believe This isn't that recognizable. So I decided to make it all caps with the new alphabet.

![image](https://user-images.githubusercontent.com/4528551/46302465-5f3d7780-c566-11e8-8914-7167f7824e9b.png)![image](https://user-images.githubusercontent.com/4528551/46302478-6795b280-c566-11e8-945c-ea63ab364282.png)

[alphabetical-off.zip](https://github.com/Templarian/MaterialDesign/files/2434832/alphabetical-off.zip)

**Comment by goyney** [comment]
[![alphabetical-off](https://materialdesignicons.com/icon/alphabetical-off)](https://materialdesignicons.com/icon/alphabetical-off)[![alphabetical-variant](https://materialdesignicons.com/icon/alphabetical-variant)](https://materialdesignicons.com/icon/alphabetical-variant)[![alphabetical-variant-off](https://materialdesignicons.com/icon/alphabetical-variant-off)](https://materialdesignicons.com/icon/alphabetical-variant-off)
