### ISSUE TITLE
Unwrap

### ISSUE THREAD

**Issue by vanesa** [Templarian/MaterialDesign#3488]
Antipode to the wrap icon: https://materialdesignicons.com/icon/wrap

Suggestion (credit goes to @leosuccarferre): 

![image](https://user-images.githubusercontent.com/9110008/45706029-0a463e00-bb30-11e8-9816-aa5e256145c9.png)

SVG:
```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<g>
	<rect x="8" y="13.3" width="32" height="5.3"/>
	<rect x="8" y="45.3" width="32" height="5.3"/>
	<polygon points="56,32 45.3,24 45.3,29.3 8,29.3 8,34.7 45.3,34.7 45.3,40 	"/>
</g>
</svg>
```

**Comment by PeterShaggyNoble** [comment]
You could flip the `backburger` icon to achieve this.

![](http://mdi.houseofdesign.ie/tools/preview/?icon=backburger)

**Comment by vanesa** [comment]
I would prefer it being more similar to the wrap icon as the suggestion above.

**Comment by MrGrigri** [comment]
I believe either your suggestion or a `wrap-off` version would work.

**Comment by vanesa** [comment]
@MrGrigri Can you point me to the wrap-off version? I can't find it in the collection.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/45707785-1258aa80-bb3d-11e8-8ee3-aa62d93aa936.png)

[wrap-off.zip](https://github.com/Templarian/MaterialDesign/files/2394048/wrap-off.zip)

**Comment by MrGrigri** [comment]
![wrap-disabled](https://user-images.githubusercontent.com/4528551/45708322-57311100-bb3e-11e8-8075-59386d1f93f8.png)

[wrap-disabled.zip](https://github.com/Templarian/MaterialDesign/files/2394071/wrap-disabled.zip)

**Comment by MrGrigri** [comment]
All credit for this icon should go to @vanesa. Thanks for your contribution.

**Comment by vanesa** [comment]
Thank you! When will it be released?

**Comment by Templarian** [comment]
[![wrap-disabled](https://materialdesignicons.com/icon/wrap-disabled)](https://materialdesignicons.com/icon/wrap-disabled)

@vanesa Assigned to the shared contributor account. Once they have 5 icons we create a contributor page. This is on the website, but won't be released for another month probably as we get ready for the `3.x.xx` release.
