### ISSUE TITLE
Chat-*

### ISSUE THREAD

**Issue by vanesa** [Templarian/MaterialDesign#3489]
Rounder version of the message icon/chat-bubble:
https://materialdesignicons.com/icon/message

Suggestion:
![image](https://user-images.githubusercontent.com/9110008/45707174-05cf5480-bb33-11e8-8253-82ba9ca6a057.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/45731265-4fa05500-bb9c-11e8-8fb7-8041135809ac.png) ![image](https://user-images.githubusercontent.com/338885/45731282-62b32500-bb9c-11e8-8e68-f377bf3fe06e.png)

Do these look aligned correctly?

**Comment by Templarian** [comment]
[![chat](https://materialdesignicons.com/icon/chat)](https://materialdesignicons.com/icon/chat) [![chat-alert](https://materialdesignicons.com/icon/chat-alert)](https://materialdesignicons.com/icon/chat-alert) [![chat-processing](https://materialdesignicons.com/icon/chat-processing)](https://materialdesignicons.com/icon/chat-processing)

Added the 2 main modifiers. We'll eventually get them all added. Let us know if any are needed more immediately in a new issue and will try and add them.
