### ISSUE TITLE
Platzi

### ISSUE THREAD

**Issue by jecsham** [Templarian/MaterialDesign#3490]
Platzi icon

![descarga](https://user-images.githubusercontent.com/10292582/45710534-7cc51700-bb4c-11e8-97ae-d8e6ac2e307a.png)

(Only the isotype)

**Comment by David-Jackson** [comment]
![image](https://user-images.githubusercontent.com/11835431/45713825-09c49c00-bb5e-11e8-8728-73dba6011284.png)

[platzi.zip](https://github.com/Templarian/MaterialDesign/files/2394364/platzi.zip)

**Comment by Templarian** [comment]
This one falls outside of the scope of icons we provide in the pack.

Eventually we may add Brands/Logo's like this. We use the Rejected tag to track these.

**Comment by jecsham** [comment]
@Templarian Ok, no problem.
Thanks @David-Jackson for the svg, I'm going to use it if it doesn't bother you.
