### ISSUE TITLE
Repository

### ISSUE THREAD

**Issue by vanesa** [Templarian/MaterialDesign#3494]
Repository Icon

Suggestions:

![image](https://user-images.githubusercontent.com/9110008/45771961-5a3e0700-bbfb-11e8-8131-a8c69e2b075f.png)
```<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 64 64" style="enable-background:new 0 0 64 64;" xml:space="preserve">
<title>Icons 400</title>
<g>
	<path d="M23,22.4c1.3,0,2.4-1.1,2.4-2.4s-1.1-2.4-2.4-2.4c-1.3,0-2.4,1.1-2.4,2.4S21.7,22.4,23,22.4z"/>
	<path d="M35,26.4c1.3,0,2.4-1.1,2.4-2.4s-1.1-2.4-2.4-2.4s-2.4,1.1-2.4,2.4S33.7,26.4,35,26.4z"/>
	<path d="M23,42.4c1.3,0,2.4-1.1,2.4-2.4s-1.1-2.4-2.4-2.4s-2.4,1.1-2.4,2.4S21.7,42.4,23,42.4z"/>
	<path d="M50,16h-1.5c-0.3,0-0.5,0.2-0.5,0.5v35c0,0.3-0.2,0.5-0.5,0.5h-27c-0.5,0-1-0.2-1.4-0.6l-0.6-0.6c-0.1-0.1-0.1-0.2-0.1-0.4
		c0-0.3,0.2-0.5,0.5-0.5H44c1.1,0,2-0.9,2-2V12c0-1.1-0.9-2-2-2H14c-1.1,0-2,0.9-2,2v36.3c0,1.1,0.4,2.1,1.2,2.8l3.1,3.1
		c1.1,1.1,2.7,1.8,4.2,1.8H50c1.1,0,2-0.9,2-2V18C52,16.9,51.1,16,50,16z M19,20c0-2.2,1.8-4,4-4c1.4,0,2.8,0.8,3.5,2
		c1.1,1.9,0.4,4.3-1.5,5.4V33c1-0.6,2.3-0.9,4-0.9c1,0,2-0.5,2.8-1.3C32.5,30,33,29.1,33,28v-0.6c-1.2-0.7-2-2-2-3.5
		c0-2.2,1.8-4,4-4c2.2,0,4,1.8,4,4c0,1.5-0.8,2.7-2,3.5h0c-0.1,2.1-0.9,4.4-2.5,6c-1.6,1.6-3.4,2.4-5.5,2.5c-0.8,0-1.4,0.1-1.9,0.3
		c-0.2,0.1-1,0.8-1.2,0.9C26.6,38,27,38.9,27,40c0,2.2-1.8,4-4,4s-4-1.8-4-4c0-1.5,0.8-2.7,2-3.4V23.4C19.8,22.7,19,21.4,19,20z"/>
</g>
</svg>
```

or similar to icons8's:
![image](https://user-images.githubusercontent.com/9110008/45771985-6fb33100-bbfb-11e8-8132-b27bb745ff2c.png)

Prefer first suggestion.

**Comment by goyney** [comment]
Perhaps something like this (using our `book` icons):

![image](https://user-images.githubusercontent.com/1015040/45773912-9c764100-bc19-11e8-9a44-27f5badc9d57.png)

[repository.zip](https://github.com/Templarian/MaterialDesign/files/2398323/repository.zip)

**Comment by vanesa** [comment]
@goyney Thank you! Is it possible to make the tag on the top smaller? It's a bit dominant IMHO.

**Comment by Templarian** [comment]
@vanesa It's a base icon with a modifier. Unfortunately base icon's can't be modified as they have to conform with the others.

**Comment by vanesa** [comment]
Ok, then maybe no tag at all. How about sth like this: 
![image](https://user-images.githubusercontent.com/9110008/45840408-ba03e300-bccb-11e8-90ab-25a34c1989b4.png)

**Comment by goyney** [comment]
The problem with using the `-multiple` version of a box or rectangle is that the available width of the box/rectangle doesn't allow enough space for `branch` to be distinguishable at 24x24 resolution.

![image](https://user-images.githubusercontent.com/1015040/45841155-eed16380-bce6-11e8-8708-7a2b6afd862b.png)

**Comment by PeterShaggyNoble** [comment]
Hmm ... I seem to remember an issue a while back where we'd decided to alias the existing `book` icon as `repository` ...

**Comment by Templarian** [comment]
[![source-repository](https://materialdesignicons.com/icon/source-repository)](https://materialdesignicons.com/icon/source-repository) [![(source-repository-multiple](https://materialdesignicons.com/icon/source-repository-multiple)](https://materialdesignicons.com/icon/source-repository-multiple)
