### ISSUE TITLE
Car Door

### ISSUE THREAD

**Issue by MarcoMata82** [Templarian/MaterialDesign#3497]
Hi guys I think it will be useful. Something like this:
![122424-200](https://user-images.githubusercontent.com/43468412/45873624-2f86b680-bd93-11e8-8552-60c3653afccb.png)

**Comment by PeterShaggyNoble** [comment]
Could you provide a use case for this?

**Comment by Templarian** [comment]
[![car-door](https://materialdesignicons.com/icon/car-door)](https://materialdesignicons.com/icon/car-door)
