### ISSUE TITLE
menu-open

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3498]
From the last update of Material Icons Extended.

[![menu-open](http://mdi.houseofdesign.ie/tools/preview/?icon=menu-open&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by Templarian** [comment]
[![menu-close](https://materialdesignicons.com/icon/menu-close)](https://materialdesignicons.com/icon/menu-close)

Named it `menu-close`... I'm not sure how that icon would be `menu-open`.

**Comment by PeterShaggyNoble** [comment]
I took the `open` in Google's name to be an adjective rather than a verb.

**Comment by Templarian** [comment]
Oh... interesting. Yea, lets rename this one to open then.

**Comment by Templarian** [comment]
Renamed.
