### ISSUE TITLE
import, export

### ISSUE THREAD

**Issue by igorushi** [Templarian/MaterialDesign#350]
It could be great to have icons for "import" and "export"

- [ ] import
- [ ] export

**Comment by Templarian** [comment]
Do you mean like a file import and export?

**Comment by igorushi** [comment]
Ups, missed your comment. If it's posible to make more general icons not exactly files then one can combine those icons with concreate entity (like file, db, etc).

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/import
https://materialdesignicons.com/icon/export

Let me know if these work. I think the box is the most generic way to represent it. Using a circle was also an option, but could be confused with grouping.

**Comment by igorushi** [comment]
Awesome :)
