### ISSUE TITLE
Quota

### ISSUE THREAD

**Issue by David-Jackson** [Templarian/MaterialDesign#3500]
Icon found from Google API Console (See #3491). 

![image](https://user-images.githubusercontent.com/11835431/45882236-81bbdd80-bd7b-11e8-9fd9-38d1e04abcef.png)

[quota.zip](https://github.com/Templarian/MaterialDesign/files/2405389/quota.zip)

**Comment by goyney** [comment]
Materialized version:
![image](https://user-images.githubusercontent.com/1015040/62588584-3e376880-b894-11e9-803f-8a26240bafcc.png)

[quota.svg.zip](https://github.com/Templarian/MaterialDesign/files/3474848/quota.svg.zip)

Discussing what to call this.

**Comment by goyney** [comment]
After discussion, we decided to call this icon rejected. 😝
