### ISSUE TITLE
Cryptographic Keys

### ISSUE THREAD

**Issue by David-Jackson** [Templarian/MaterialDesign#3501]
Another from Google API Console.

![image](https://user-images.githubusercontent.com/11835431/45883660-ad40c700-bd7f-11e8-854c-b9c1d85e7413.png)

[cryptographic-key.zip](https://github.com/Templarian/MaterialDesign/files/2405486/cryptographic-key.zip)

**Comment by Templarian** [comment]
The shield needs to be updated to conform with `shield-outline`.

We'll need to add two icons for this request. `shield-key` and `shield-key-outline`.

**Comment by Templarian** [comment]
Also, if you're curious. A lot of the official apps don't follow Material Design so we have to tweak them. Not all of Google's designers read the documentation. 🤔

**Comment by Templarian** [comment]
[![shield-key](https://materialdesignicons.com/icon/shield-key)](https://materialdesignicons.com/icon/shield-key) [![shield-key-outline](https://materialdesignicons.com/icon/shield-key-outline)](https://materialdesignicons.com/icon/shield-key-outline)
