### ISSUE TITLE
Battle.net

### ISSUE THREAD

**Issue by joyfreak** [Templarian/MaterialDesign#3502]

**Comment by Templarian** [comment]
@joyfreak Do you have an example image?

**Comment by joyfreak** [comment]
https://icons8.com/icon/23802/battle.net

**Comment by Templarian** [comment]
[![battlenet](https://materialdesignicons.com/icon/battlenet)](https://materialdesignicons.com/icon/battlenet)

**Comment by joyfreak** [comment]
Thank you!
