### ISSUE TITLE
account-target

### ISSUE THREAD

**Issue by raminrahimzada** [Templarian/MaterialDesign#3503]
![aim_icon](https://user-images.githubusercontent.com/27096288/45921723-c3c64b80-be6f-11e8-8fa1-de8176da4f42.png)

**Comment by CoDEmanX** [comment]
Is there reason why the person silhouette  is 9 wide and half a pixel off-grid?
The shape from `folder-account` is 8 wide and pixel-perfect.

![grafik](https://user-images.githubusercontent.com/1309249/45948948-3b27e680-bffa-11e8-8743-1b027fee84d4.png) ![grafik](https://user-images.githubusercontent.com/1309249/45948954-3fec9a80-bffa-11e8-90a4-5967bb61a037.png)

**Comment by Templarian** [comment]
@CoDEmanX My bad, working on a few icons at once and forgot to go back before exporting. 😿

**Comment by Templarian** [comment]
Updated.
