### ISSUE TITLE
power & power-standby are too similar

### ISSUE THREAD

**Issue by bbbenji** [Templarian/MaterialDesign#3504]

**Comment by MrGrigri** [comment]
The `power-standby` follows the IEC 60417-5009 standard, whereas the `power` icon was designed by Google.

**Comment by MrGrigri** [comment]
I don't think that this is a bug or that we will do anything about this one.

**Comment by MrGrigri** [comment]
See issue #2304

**Comment by Templarian** [comment]
Yea, they are similar that's intentional. Use the one that fits best for your use case.
