### ISSUE TITLE
Gluten-free (barley-off)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3505]
A striketrough grain appears to be a common icon for "glutenfree". Here are some variations with the strokes in slightly different positions:

![grafik](https://user-images.githubusercontent.com/1309249/45948443-4b3ec680-bff8-11e8-851f-2698623f2f45.png) ![grafik](https://user-images.githubusercontent.com/1309249/45948456-5a257900-bff8-11e8-88a0-fe860fcc29d5.png)
![grafik](https://user-images.githubusercontent.com/1309249/45948470-66a9d180-bff8-11e8-9d18-a67191f8c618.png) ![grafik](https://user-images.githubusercontent.com/1309249/45948485-775a4780-bff8-11e8-89db-c225d8820039.png)

Variant 2 avoids small details at the bottom right of the crop, which I think is the way to go.

[barley-off.zip](https://github.com/Templarian/MaterialDesign/files/2410539/barley-off.zip)

**Comment by Templarian** [comment]
[![barley-off](https://materialdesignicons.com/icon/barley-off)](https://materialdesignicons.com/icon/barley-off)
