### ISSUE TITLE
pagseguro

### ISSUE THREAD

**Issue by geraldolsribeiro** [Templarian/MaterialDesign#3508]
Payment gateway brand.
[pagseguro.zip](https://github.com/Templarian/MaterialDesign/files/2413630/pagseguro.zip)

![pagseguro](https://user-images.githubusercontent.com/3185022/45990835-7eb13d80-c058-11e8-99a6-767835a3d101.png)

Reference:
![pagseguro logo](http://blogpagseguro.com.br/wp-content/uploads/2011/04/Logo-Cifrao.jpg)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
