### ISSUE TITLE
stripe

### ISSUE THREAD

**Issue by geraldolsribeiro** [Templarian/MaterialDesign#3509]
Stripe Brand

[stripe.zip](https://github.com/Templarian/MaterialDesign/files/2413643/stripe.zip)

![stripe](https://user-images.githubusercontent.com/3185022/45991078-8e7d5180-c059-11e8-8bf4-6102679dd62d.png)

**Comment by PeterShaggyNoble** [comment]
We won't be able to add this one as Stripe do not allow their logo/icon to be distributed. They issued [Iconfinder](https://www.iconfinder.com/) with a take-down notice earlier this year.
