### ISSUE TITLE
card-minus

### ISSUE THREAD

**Issue by nimaho** [Templarian/MaterialDesign#3511]

**Comment by PeterShaggyNoble** [comment]
Do you mean `credit-card-minus`?

**Comment by MrGrigri** [comment]
If this is what @nimaho is wanting then we can add these. This also revealed that `card-add` is not using the proper add-modifier (current in white and new in grey). All though, I'm not a fan of the proper cutout on this one, particulary on the top-right part.

![image](https://user-images.githubusercontent.com/4528551/46168188-fea3f700-c254-11e8-93e7-df085fe68eac.png) ![image](https://user-images.githubusercontent.com/4528551/46168212-0cf21300-c255-11e8-9589-452983abf182.png)

[card-remove.zip](https://github.com/Templarian/MaterialDesign/files/2425490/card-remove.zip)

![image](https://user-images.githubusercontent.com/4528551/46168399-9acdfe00-c255-11e8-885e-38d495d813ea.png)

[card-add.zip](https://github.com/Templarian/MaterialDesign/files/2425503/card-add.zip)

**Comment by MrGrigri** [comment]
Small correction. Ignore the previous contribution. [card-remove.zip](https://github.com/Templarian/MaterialDesign/files/2425853/card-remove.zip)

![image](https://user-images.githubusercontent.com/4528551/46173250-f488f500-c262-11e8-935e-37271a27d6cc.png) ![image](https://user-images.githubusercontent.com/4528551/46173268-fe125d00-c262-11e8-884f-7a98abfe7ff6.png) ![image](https://user-images.githubusercontent.com/4528551/46173457-8c86de80-c263-11e8-8dc5-875708100b7c.png)

**Comment by goyney** [comment]
These are being address/added in #3740.
