### ISSUE TITLE
Google My Business

### ISSUE THREAD

**Issue by Johnnybike** [Templarian/MaterialDesign#3513]
Can not find Google My Business icon ?

**Comment by Johnnybike** [comment]
[https://www.google.com.br/search?q=google+my+business&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjql5-N19bdAhUL0lMKHRjFC9YQ_AUICigB&biw=1920&bih=956](url)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/46033761-94f4e300-c0c4-11e8-8519-8aa113cb1104.png)

**Comment by Johnnybike** [comment]
Ok man.

How can I use this icon on my site ?

**Comment by Johnnybike** [comment]
Okay, as soon as it's available please notify me. Because I have an interest to use, grateful !

**Comment by Johnnybike** [comment]
This link is official and direct from the google my business app :

[https://www.gstatic.com/bfe/images/favicon/gmb-favicon_v3.ico](url)

**Comment by Vitaly-V** [comment]
I would like to have "google my business" icon too.

**Comment by goyney** [comment]
I really don't think this icon works and Google has not released any official versions of it monochrome, nor any branding guidelines around it. I'm of the opinion that we do not add it.

However, here is another variant I created just in case @Templarian feels differently:
![image](https://user-images.githubusercontent.com/1015040/58274760-8cdb6900-7d61-11e9-8892-ad7947c116f2.png)
[gmb.svg.zip](https://github.com/Templarian/MaterialDesign/files/3213520/gmb.svg.zip)

**Comment by goyney** [comment]
[![google-my-business](https://materialdesignicons.com/icon/google-my-business)](https://materialdesignicons.com/icon/google-my-business)
