### ISSUE TITLE
Single file for SVGs

### ISSUE THREAD

**Issue by FrederickE** [Templarian/MaterialDesign#3516]
I am unable to get a single file that contains all the SVGs for use on  AngularJS 1.x. The docs shows a file named 'mdi.svg' and I can't find it anywhere to download. Has materialdesignicon dropped support for AngularJs 1.x?

**Comment by Templarian** [comment]
Oops, will fix in a moment. Thought I had copied that link over.

**Comment by Templarian** [comment]
https://www.npmjs.com/package/@mdi/angular-material

I linked a API generated version, but I need to update the documentation for Angular Material.

**Comment by FrederickE** [comment]
Thank you very much. The file is now available in the docs.
