### ISSUE TITLE
database-edit

### ISSUE THREAD

**Issue by hansena** [Templarian/MaterialDesign#3517]
Requesting a new icon to extend database icons to include edit icon matching that of other subjects.
![database-edit](https://user-images.githubusercontent.com/15346521/46088479-7a7d4100-c17a-11e8-985f-a1dc4998f811.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/46167740-da93e600-c253-11e8-98c4-1fd5eef15abd.png)

[database-edit.zip](https://github.com/Templarian/MaterialDesign/files/2425445/database-edit.zip)

**Comment by Templarian** [comment]
[![database-edit](https://materialdesignicons.com/icon/database-edit)](https://materialdesignicons.com/icon/database-edit)
