### ISSUE TITLE
book-cover like a account-box-outline

### ISSUE THREAD

**Issue by lukfcb** [Templarian/MaterialDesign#3518]

**Comment by MrGrigri** [comment]
We'll need some more information, please!

**Comment by PeterShaggyNoble** [comment]
Do you mean [`book-outline`](https://material.io/tools/icons/?search=book&icon=book&style=outline)?

**Comment by Templarian** [comment]
[![book-outline](https://materialdesignicons.com/icon/book-outline)](https://materialdesignicons.com/icon/book-outline)
