### ISSUE TITLE
deathly-hallows

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3519]
Because I'm a Potterhead, I would like to add a `deathly-hallows` icon. I tried this at 2-pixel width, but that didn't look good so I broke from consistency and made it at 1-pixel width. 🤓 

![image](https://user-images.githubusercontent.com/4528551/46172069-b3431600-c25f-11e8-9680-c6a82ec921a4.png)

[deathly-hallows.zip](https://github.com/Templarian/MaterialDesign/files/2425764/deathly-hallows.zip)

**Comment by Templarian** [comment]
Anyway to make this `2px` or `1.5px`?

**Comment by MrGrigri** [comment]
At 2-pixel width, it's not recognizable imo.

![image](https://user-images.githubusercontent.com/4528551/46489369-68c31b80-c7c2-11e8-86ee-a73505b3a6e8.png)

At 1.5-pixel width, it's better, but not as recognizable as 1-pixel width.

![image](https://user-images.githubusercontent.com/4528551/46489404-855f5380-c7c2-11e8-91c3-aeb8f4ad1af8.png)

[deathly-hallows.zip](https://github.com/Templarian/MaterialDesign/files/2447266/deathly-hallows.zip)

**Comment by Templarian** [comment]
Added the 1.5px.
