### ISSUE TITLE
Eye-circle

### ISSUE THREAD

**Issue by pavelmlejnek** [Templarian/MaterialDesign#3521]
Hello,

it would help me a lot to have an mdi-eye-circle icon (just the same as other *-circle icons).

 Thank you in advance

**Comment by MrGrigri** [comment]
Like this?

![image](https://user-images.githubusercontent.com/4528551/46217202-9b6e9f00-c2fe-11e8-9362-36dac39e38d4.png) ![image](https://user-images.githubusercontent.com/4528551/46217242-b3deb980-c2fe-11e8-9782-9847670f3f49.png)

[eye-circle.zip](https://github.com/Templarian/MaterialDesign/files/2428720/eye-circle.zip)

**Comment by pavelmlejnek** [comment]
Exactly 👍 thank you very much.

**Comment by Templarian** [comment]
[![eye-circle](https://materialdesignicons.com/icon/eye-circle)](https://materialdesignicons.com/icon/eye-circle) [![eye-circle-outline](https://materialdesignicons.com/icon/eye-circle-outline)](https://materialdesignicons.com/icon/eye-circle-outline)
