### ISSUE TITLE
All PUBG icons(like guns, avtar)

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [Templarian/MaterialDesign#3522]

**Comment by Templarian** [comment]
@iAmAndroidDeveloper Can you post images for each of these. Not really familiar with the game.

**Comment by PeterShaggyNoble** [comment]
Also, please create individual issues for each distinct group of icons to allow us to track the requests better.

**Comment by Templarian** [comment]
Closing this out as I'm not seeing any replies and this seems awfully open ended.

As said above, try and create single specific issues focused on one icon with examples.
