### ISSUE TITLE
account-arrow-left

### ISSUE THREAD

**Issue by Coffeemate** [Templarian/MaterialDesign#3527]
Would like to contribute: icon showing that someone follows you or an incoming friend request.
Keywords: account, user, arrow, left, follow, request, incoming.

![example-1](https://user-images.githubusercontent.com/4212685/46243698-ab11e480-c3df-11e8-9198-feb5f44a89a4.png)

![icon-example-filled](https://user-images.githubusercontent.com/4212685/46243853-e52fb600-c3e0-11e8-9615-e52b2f282c24.png)

![icon-example-outline](https://user-images.githubusercontent.com/4212685/46243856-e8c33d00-c3e0-11e8-9a9e-a9872fee38db.png)

[icon-arrow-left.zip](https://github.com/Templarian/MaterialDesign/files/2430472/icon-arrow-left.zip)

**Comment by Templarian** [comment]
[![account-arrow-left](https://materialdesignicons.com/icon/account-arrow-left)](https://materialdesignicons.com/icon/account-arrow-left) [![account-arrow-left-outline](https://materialdesignicons.com/icon/account-arrow-left-outline)](https://materialdesignicons.com/icon/account-arrow-left-outline)
