### ISSUE TITLE
account-arrow-right

### ISSUE THREAD

**Issue by Coffeemate** [Templarian/MaterialDesign#3528]
Would like to contribute: icon showing that user follows someone or an outgoing friend request.
Keywords: account, user, arrow, right, following, request, outgoing.

![example-1](https://user-images.githubusercontent.com/4212685/46244031-75222f80-c3e2-11e8-870c-4d9a259d70be.png)

![icon-example-filled](https://user-images.githubusercontent.com/4212685/46244035-79e6e380-c3e2-11e8-99d3-219f5f0ff577.png)

![icon-example-outline](https://user-images.githubusercontent.com/4212685/46244036-7eab9780-c3e2-11e8-87d1-df209ff3c51b.png)

[account-arrow-right.zip](https://github.com/Templarian/MaterialDesign/files/2430474/account-arrow-right.zip)

**Comment by Templarian** [comment]
http://dev.materialdesignicons.com/contribute/icon-naming Have a look at the arrow cutout guidelines for this issue and the other.

**Comment by Templarian** [comment]
[![account-arrow-right](https://materialdesignicons.com/icon/account-arrow-right)](https://materialdesignicons.com/icon/account-arrow-right) [![account-arrow-right-outline](https://materialdesignicons.com/icon/account-arrow-right-outline)](https://materialdesignicons.com/icon/account-arrow-right-outline)

You have a contributor page now that these are linked to.

**Comment by Templarian** [comment]
@Coffeemate Documentation, the new getting started pages need a lot of work and are all in markdown.

Yea, I don't have a way for one to edit that stuff yet (there use to be a way but all of those endpoints are completely broken at the moment). Will get to that eventually.
