### ISSUE TITLE
garage-ajar

### ISSUE THREAD

**Issue by vontrapp** [Templarian/MaterialDesign#3529]
I need another garage door icon for when the door is neither open nor closed. My sensors report these three states. I'm tempted to use the garage-alert icon as that is very close to what I want (just without the '!' next to it), but then I also want to use the alert for when my sensors aren't reporting at all, or in some other error condition.

It doesn't have to be called '-ajar', and in fact if there were simply garage-nn like with batteries with several (or only the 3) stages that would work great!

**Comment by goyney** [comment]
We've already have had discussions around this exact scenario as pointed out by @MrGrigri. As a Home Assistant user tracking my own garage door, I do not see value in added a variation of `garage-alert` without the exclamation. Based on the earlier conversation, and the `garage-alert` icon we have for this exact scenario, I'm going to close this issue.

**Comment by vontrapp** [comment]
Alert is for something amiss.

Half open is for, well... half open. It is a different state.

**Comment by vontrapp** [comment]
One example is if I'm brewing in the garage and I intentionally put the door 1 foot open. This is not an error or in motion or anything else. The garage is neither open nor is it closed. It's in the middle. Period.

And again, I would like to use the garage-alert specifically for non-reporting sensors (mqtt LwT)

**Comment by MrGrigri** [comment]
IMO, the current `garage-alert` could still be used when the door is ajar. Then you could use the `alert` icon to represent the mqtt errors. I say this because, at the end of the day, you don't want your garage door ajar, you want it closed.
