### ISSUE TITLE
Vertical and horizontal drag handles

### ISSUE THREAD

**Issue by MagicIndustries** [Templarian/MaterialDesign#353]
Could use drag handles for drawers, so the user can see they can swipe to expand them for example. The kind of handle I'm thinking of is generally a couple of rows of 4 small dots.

- [ ] drag-vertical
- [ ] drag-horizontal
- [ ] resize-corner-bottom-right

**Comment by Templarian** [comment]
Funny enough I made this icon at work because it was missing form the pack and then forgot to add it officially. I'll get these added this weekend.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/drag
http://materialdesignicons.com/icon/drag-vertical
http://materialdesignicons.com/icon/drag-horizontal
http://materialdesignicons.com/icon/resize-corner-bottom-right

**Comment by MagicIndustries** [comment]
Perfect, thanks :)
