### ISSUE TITLE
radio-fm / radio-am

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3530]
FM and AM icons for radio bands.

**Comment by goyney** [comment]
I know it's technically a brand, but this seemed missing.

![image](https://user-images.githubusercontent.com/1015040/46388619-4f737f80-c69b-11e8-973f-1d41ca41a983.png)
[xm.zip](https://github.com/Templarian/MaterialDesign/files/2440446/xm.zip)

Could be aliased satellite-radio as well.

**Comment by Templarian** [comment]
@goyney https://en.wikipedia.org/wiki/XM_Satellite_Radio#/media/File:XM_Satellite_Radio_logo.svg We would probably have to use this brand icon for that.

**Comment by MrGrigri** [comment]
Yeah, I would stick with the branded icon and just call it `xm` because it’s technically not a radio band.

**Comment by goyney** [comment]
Technically, anything wireless is over some sort of radio band. :) I'm fine with using the official brand icon though if we find it useful to add.

**Comment by PeterShaggyNoble** [comment]
From the linked Wikipedia article:
> On January 13, 2011, XM Satellite Radio, Inc. was dissolved as a separate entity ...

Also, for me, it would have fallen into the category of too region-specific, anyway.

**Comment by Templarian** [comment]
Added `radio-fm` and `radio-am`.
