### ISSUE TITLE
Code of Conduct and Contribution Guidelines

### ISSUE THREAD

**Issue by edoamenze** [Templarian/MaterialDesign#3531]
Hello, I just recently joined GitHub and noticed that this repository doesn't have a Code of Conduct or a Contribution Guidelines document. I would highly recommend you to add these documents to your repository to allow other diverse members - like myself - of the community to contribute to the project.

I look forward to hearing your response.
- Edo

**Comment by Templarian** [comment]
Duplicate of #1052

**Comment by PeterShaggyNoble** [comment]
And contribution guidelines will be available on the new site [here](https://dev.materialdesignicons.com/contribute), [here](https://dev.materialdesignicons.com/contribute/icon-naming) & [here](https://dev.materialdesignicons.com/contribute/site)
