### ISSUE TITLE
Sports

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3532]
Icon request for other sports (example as link behind the name):

- [ ] [Squash](https://cdn3.iconfinder.com/data/icons/common-sports/4096/squash-512.png)
- [ ] [Alpine skiing](https://static.thenounproject.com/png/260-200.png)
- [ ] [Biathlon](https://static.thenounproject.com/png/29525-200.png)
- [ ] [Bobsleigh](https://image.flaticon.com/icons/svg/38/38369.svg)
- [ ] [Nordic combined skiing](https://cdn1.vectorstock.com/i/1000x1000/44/75/nordic-combined-icon-vector-2014475.jpg)
- [ ] [Snowboard](https://cdn3.iconfinder.com/data/icons/common-sports/4096/snowboarding-512.png)
- [ ] [Short track](http://www.haipic.com/icon/22106/22106.png)
- [ ] [Speed skating](https://d30y9cdsu7xlg0.cloudfront.net/png/29531-200.png)
- [ ] [Skeleton](https://d30y9cdsu7xlg0.cloudfront.net/png/30059-200.png)
- [ ] [Luge](https://static.thenounproject.com/png/30058-200.png)
- [ ] [Figure skating](https://d30y9cdsu7xlg0.cloudfront.net/png/215262-200.png)
- [ ] Formula E (Racing car with an "E"?)
- [ ] [Handball](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS_1f9VxRJpIk89N_3nd8yZxgBKpkdR3ZE49TrWTPQSyPXRyCGb)
- [ ] [Horse racing](https://image.freepik.com/free-icon/silhouette-of-a-man-riding-a-horse_318-27519.jpg)
- [ ] [Snooker](https://cdn2.iconfinder.com/data/icons/sport-ii/95/13-512.png)
- [x] [Poolbillard](https://image.shutterstock.com/image-vector/billiards-8ball-pool-flat-icon-260nw-272557283.jpg)
- [ ] [Ski jumping](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRC1soyxFLGXf_usUECR3B5KrK4d4KclPmT18wA0qgisVrcpm0t)
- [ ] [Boxing](https://cdn2.iconfinder.com/data/icons/sports-6/128/boxing-512.png)
- [x] [Kickboxing](https://image.flaticon.com/icons/svg/39/39574.svg)
- [ ] [Wrestling](https://www.shareicon.net/download/2015/11/08/668884_arts.svg)

Some sports might be similar for an icon such as snooker and poolbillard so I am not sure if it makes sense for an separate icon...

**Comment by Templarian** [comment]
Do you have examples of these? Preferably small examples we can use as a reference?

**Comment by MrGrigri** [comment]
This is a very comprehensive list. Could you please create an issue for each one so that we can track each one individually?

**Comment by PeterShaggyNoble** [comment]
Note that some of these will be too niche for us to add while others will end up being too similar to others at 24*24 to warrant separate icons.

**Comment by matthew2402** [comment]
Sure, if it is too similar I am fine if it won't be added.

**Comment by Templarian** [comment]
@matthew2402 Thanks for going through the effort of creating all the issues. It helps us more individually track designs and progress easier. Hopefully we can get some rough designs and these added one by one. Might take a bit, but it would be useful to have all of these sports related icons.
