### ISSUE TITLE
multiline-text-box

### ISSUE THREAD

**Issue by cassiss** [Templarian/MaterialDesign#3533]
Similar to the single line text box, but explicitly multi-line.
An idea would be to have the text cursor only partially inside the field or to show a scroll bar with the text box

**Comment by MrGrigri** [comment]
I believe I like this better than issue #1606 

![image](https://user-images.githubusercontent.com/4528551/49102163-52bb5f80-f235-11e8-97fc-691e5db93da0.png)

---

[textarea-new.zip](https://github.com/Templarian/MaterialDesign/files/2621304/textarea-new.zip)

**Comment by MrGrigri** [comment]
Like this:

![image](https://user-images.githubusercontent.com/4528551/49106883-97e58e80-f241-11e8-84b5-a3294d23605f.png)

---

[textarea-new2.zip](https://github.com/Templarian/MaterialDesign/files/2621590/textarea-new2.zip)

**Comment by goyney** [comment]
Whoops, sorry, no I mean your idea with the one from #1606, with the drag arrow in the corner.

**Comment by MrGrigri** [comment]
I don't think that would work with the text cursor as well. But I'm liking the last one.

**Comment by CoDEmanX** [comment]
![textarea](https://user-images.githubusercontent.com/4528551/49102163-52bb5f80-f235-11e8-97fc-691e5db93da0.png)

I like the approach, but isn't the box too large? Can't it be shrunk and the size of the text cursor be reduced?

**Comment by MrGrigri** [comment]
That's why I like the second one because it's like a zoomed in version. where the cursor is the same size.

**Comment by goyney** [comment]
[![textarea](https://materialdesignicons.com/icon/textarea)](https://materialdesignicons.com/icon/textarea)
