### ISSUE TITLE
Update eventbrite logo

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3534]
Eventbrite's logo has changed.

https://www.eventbrite.com/

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/46305246-27d2c900-c56e-11e8-8936-f5e7e2711349.png)

[eventbrite-update.zip](https://github.com/Templarian/MaterialDesign/files/2434990/eventbrite-update.zip)

**Comment by PeterShaggyNoble** [comment]
Aw, I liked their old icon.

**Comment by Templarian** [comment]
[![eventbrite](https://materialdesignicons.com/icon/eventbrite)](https://materialdesignicons.com/icon/eventbrite)
