### ISSUE TITLE
Polycom icons

### ISSUE THREAD

**Issue by tekreme73** [Templarian/MaterialDesign#3536]
Brand logo
![polycom](https://www.videoconferencingaustralia.com.au/wp-content/uploads/2016/03/polycom-logo-1-700x500.jpg)

Iconic phone style (three-legged phone)
![polycom](https://www.onedirect.fr/media/catalog/product/cache/3/image/600x/9df78eab33525d08d6e5fb8d27136e95/r/e/realpresence-trio-tb-com-650x500-enus.jpg)

**Comment by PeterShaggyNoble** [comment]
This icon is beyond the current scope of this project; only major social media networks and commonly known brands are being added at this time.
