### ISSUE TITLE
Squash

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3538]
Example:

![](https://user-images.githubusercontent.com/15157491/46868382-0ef4ce00-ce20-11e8-929a-deb704f50d50.png)

**Comment by PeterShaggyNoble** [comment]
A generic looking racquet icon that could represent all racquet sports might be best.

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/48975261-b62d6d80-f03a-11e8-9862-d896830d4e31.png)

[squash.svg.zip](https://github.com/Templarian/MaterialDesign/files/2612824/squash.svg.zip)

**Comment by goyney** [comment]
I feel like #3796 covers this. I'll add a reminder there to alias `squash` as well.
