### ISSUE TITLE
Skiing

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3539]
Example:

![](https://user-images.githubusercontent.com/15157491/46868313-d0f7aa00-ce1f-11e8-8362-9f779a8cb3bd.png)

**Comment by goyney** [comment]
This icon can be found in Google Fit and will need to be recreated for inclusion in the library.
![skiing](https://user-images.githubusercontent.com/1015040/48862850-86aa0700-ed95-11e8-8106-7db4a9435720.png)

**Comment by goyney** [comment]
These are the raw extracted icons from Google Fit involving skiing.

**_They ARE NOT ready for inclusion in the library and need to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/50806332-2b3fc400-12c4-11e9-8c30-82e02fec6dd2.png)![image](https://user-images.githubusercontent.com/1015040/50806350-372b8600-12c4-11e9-9cff-33e038f93273.png)
![image](https://user-images.githubusercontent.com/1015040/50806368-44487500-12c4-11e9-9877-65ffba95c39a.png)

[skiing.zip](https://github.com/Templarian/MaterialDesign/files/2734985/skiing.zip)

**Comment by alexeigs** [comment]
How far down the road are we with a skiing / downhill / ski alpine icon?

**Comment by goyney** [comment]
I've cleaned these three icons up to match our other icons of similar style.

![image](https://user-images.githubusercontent.com/1015040/72032716-3eca9580-325e-11ea-9fb7-691a48471a41.png)![image](https://user-images.githubusercontent.com/1015040/72032683-28243e80-325e-11ea-9316-38298d3f1ab1.png)
![image](https://user-images.githubusercontent.com/1015040/72032702-34a89700-325e-11ea-866c-f4370b2810e4.png)

[ski.zip](https://github.com/Templarian/MaterialDesign/files/4038289/ski.zip)

**Comment by matthew2402** [comment]
Wow nice, thanks!

**Comment by JamesCoyle** [comment]
Shouldn't the skis on the cross country one be 1.5dp to match the others?

**Comment by goyney** [comment]
They're not technically 1.5dp (they look weird that think compared to the person's legs), but I did update them to match the height of the skis of the other. Good catch.

![image](https://user-images.githubusercontent.com/1015040/72072130-4a987500-32bb-11ea-9998-6d3c0d9fb48c.png)

[ski.zip](https://github.com/Templarian/MaterialDesign/files/4040596/ski.zip)

**Comment by goyney** [comment]
[![ski](https://materialdesignicons.com/icon/ski)](https://materialdesignicons.com/icon/ski)[![ski-water](https://materialdesignicons.com/icon/ski-water)](https://materialdesignicons.com/icon/ski-water)
[![ski-cross-country](https://materialdesignicons.com/icon/ski-cross-country)](https://materialdesignicons.com/icon/ski-cross-country)

**Comment by MrGrigri** [comment]
`ski-cross-country` should have polls. Currently, it looks like snow shoeing.

**Comment by PeterShaggyNoble** [comment]
And the arm & rope of the `ski-water` icon should be horizontal rather than angled up.
