### ISSUE TITLE
Biathlon

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3540]
Example:

![](https://user-images.githubusercontent.com/15157491/46868475-567b5a00-ce20-11e8-829d-d8b612649939.png)

**Comment by goyney** [comment]
This icon can be found in Google Fit and will need to be recreated for inclusion in the library.
![biathlon](https://user-images.githubusercontent.com/1015040/48862887-9d505e00-ed95-11e8-9f52-58f8d28b7b35.png)

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/48975241-6ea6e180-f03a-11e8-935a-b6a37c0f7bd5.png)

[biathlon.zip](https://github.com/Templarian/MaterialDesign/files/2612821/biathlon.zip)

**Comment by Templarian** [comment]
[![biathlon](https://materialdesignicons.com/icon/biathlon)](https://materialdesignicons.com/icon/biathlon)

Quickly altered. Can probably be updated in the future.

**Comment by Yuanruili** [comment]
@Templarian
Made another version~
[Biathlon.zip](https://github.com/Templarian/MaterialDesign/files/2933492/Biathlon.zip)
