### ISSUE TITLE
Snowboard

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3543]
Example:

![](https://user-images.githubusercontent.com/15157491/46868583-b8d45a80-ce20-11e8-84d4-631af17bbb24.png)

**Comment by goyney** [comment]
This icon can be found in Google Fit and will need to be recreated for inclusion in the library.
![snowboarding](https://user-images.githubusercontent.com/1015040/48862810-6bd79280-ed95-11e8-8ea5-1d6a7f142af6.png)

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/48975228-11129500-f03a-11e8-94f4-19bb318060a6.png)
[snowboarding.zip](https://github.com/Templarian/MaterialDesign/files/2612817/snowboarding.zip)

**Comment by alexeigs** [comment]
Any updates on the inclusion in the library?

**Comment by goyney** [comment]
I've recreated this in a style which matches our other icons of the same style.

![image](https://user-images.githubusercontent.com/1015040/72033308-f57b4580-325f-11ea-8301-123730d6c590.png)

[snowboard.svg.zip](https://github.com/Templarian/MaterialDesign/files/4038331/snowboard.svg.zip)

**Comment by JamesCoyle** [comment]
I feel like the board needs to be 1.5dp and have squared ends to match the skis in #3539

**Comment by goyney** [comment]
Yeah, I agree with that. Here's an updated version:

![image](https://user-images.githubusercontent.com/1015040/72072250-86cbd580-32bb-11ea-81cf-19bc7778e6cd.png)
[snowboard.svg.zip](https://github.com/Templarian/MaterialDesign/files/4040609/snowboard.svg.zip)

**Comment by goyney** [comment]
[![snowboard](https://materialdesignicons.com/icon/snowboard)](https://materialdesignicons.com/icon/snowboard)
