### ISSUE TITLE
Skating

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3548]
Example:

![](https://user-images.githubusercontent.com/15157491/46868771-56c82500-ce21-11e8-9c81-1b3cbddcc933.png)

**Comment by goyney** [comment]
This icon can be found in Google Fit and will need to be recreated for inclusion in the library.
![skating](https://user-images.githubusercontent.com/1015040/48862751-3a5ec700-ed95-11e8-9c2a-0ab1c91c29d6.png)

**Comment by goyney** [comment]
Here is the Google Fit icon fixed. The grey path is the original Fit icon.
![image](https://user-images.githubusercontent.com/1015040/48975142-8c734700-f038-11e8-9473-fa9b8ec75925.png)

[skate.zip](https://github.com/Templarian/MaterialDesign/files/2612810/skate.zip)

**Comment by goyney** [comment]
Here is the Google Fit icon corrected for this library. (The grey path is the original Fit icon.)
![image](https://user-images.githubusercontent.com/1015040/48975174-0c99ac80-f039-11e8-9f5b-ea98f9f83f9e.png)

Additionally, he's two more icons based of this one I created:
![image](https://user-images.githubusercontent.com/1015040/48975192-2dfa9880-f039-11e8-845a-f8f4a038cbed.png)![image](https://user-images.githubusercontent.com/1015040/48975194-36eb6a00-f039-11e8-9b43-e3ffc303fa81.png)

[skates.zip](https://github.com/Templarian/MaterialDesign/files/2612814/skates.zip)

**Comment by Templarian** [comment]
Added the three icons. 😃

**Comment by matthew2402** [comment]
Nice! Thank you 😃
