### ISSUE TITLE
Handball

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3549]
Example:

![](https://user-images.githubusercontent.com/15157491/46868360-f4225980-ce1f-11e8-8683-295470631409.png)

**Comment by PeterShaggyNoble** [comment]
Would `volleyball` work?

[![volleyball](http://mdi.houseofdesign.ie/tools/preview/?icon=volleyball&action=link)](https://materialdesignicons.com/icon/volleyball)

**Comment by matthew2402** [comment]
Unfortunately no since I am working on an app for sports and already have these icons for its kind.

**Comment by MrGrigri** [comment]
I believe this one might be too niche for this project.

**Comment by PeterShaggyNoble** [comment]
Probably tricky to differentiate it from the 2 above, as well.

**Comment by JamesCoyle** [comment]
what about a soccer outline variant?

**Comment by matthew2402** [comment]
I guess this should work but cannot totally image how it will like like.

**Comment by matthew2402** [comment]
This is also an good alternative 👍

**Comment by goyney** [comment]
This icon can be found in Google Fit and will need to be recreated for inclusion in the library.
![handball](https://user-images.githubusercontent.com/1015040/48862730-2f0b9b80-ed95-11e8-8b09-f6a33dcaf230.png)

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/48975207-8f226c00-f039-11e8-954d-94731cf909c9.png)

[handball.zip](https://github.com/Templarian/MaterialDesign/files/2612816/handball.zip)

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/48982400-c9434a80-f0d9-11e8-80bc-7da9a2c6a16c.png)](https://github.com/Templarian/MaterialDesign/files/2613305/handball.zip)

**Comment by PeterShaggyNoble** [comment]
From Google's Material Icons Extended set:

[![sports_handball](http://mdi.houseofdesign.ie/tools/preview/?icon=sports_handball&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50987437-a62cf880-14d7-11e9-965e-4e778ac309f8.png)
[sports-handball.svg.zip](https://github.com/Templarian/MaterialDesign/files/2746535/sports-handball.svg.zip)

**Comment by goyney** [comment]
[![handball](https://materialdesignicons.com/icon/handball)](https://materialdesignicons.com/icon/handball)
