### ISSUE TITLE
Boxing

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3553]
[Example](https://cdn2.iconfinder.com/data/icons/sports-6/128/boxing-512.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/46388370-92ccee80-c699-11e8-83ed-26b2662869c5.png)
[boxing-glove.zip](https://github.com/Templarian/MaterialDesign/files/2440428/boxing-glove.zip)

**Comment by Templarian** [comment]
[![boxing-gloves](https://materialdesignicons.com/icon/boxing-gloves)](https://materialdesignicons.com/icon/boxing-gloves)
