### ISSUE TITLE
Kickboxing

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3554]
[Example](https://image.flaticon.com/icons/svg/39/39574.svg)

**Comment by PeterShaggyNoble** [comment]
`karate` should cover this one.

[![karate](http://mdi.houseofdesign.ie/tools/preview/?icon=karate&action=link)](https://materialdesignicons.com/icon/karate)

**Comment by matthew2402** [comment]
Ah nice, this works (didn't search for `karate`) 👍

**Comment by PeterShaggyNoble** [comment]
Going to leave this open to remind us to alias it as `kickboxing` and maybe `kickboxer`, too.

It could probably cover a myriad of other martial arts, too, so if anyone has any suggestions, leave a comment.

**Comment by goyney** [comment]
Alias `kickboxing` added to `karate`.
