### ISSUE TITLE
Wrestling

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#3555]
Example:

![](https://user-images.githubusercontent.com/15157491/46868807-7a8b6b00-ce21-11e8-9545-2bb66c895084.png)

**Comment by awshifts** [comment]
I second this request we do a lot of wrestling in this family and spend a lot of time at several clubs. Would be awesome for some icons. 
![youth-wrestling-illustration_csp58595822](https://user-images.githubusercontent.com/34609736/62154322-74914880-b2d4-11e9-9347-3f5cafe8d434.jpg)

**Comment by goyney** [comment]
Would this work?
[![kabaddi](https://materialdesignicons.com/icon/kabaddi)](https://materialdesignicons.com/icon/kabaddi)

**Comment by awshifts** [comment]
Looks like an attempt at a single or double leg takedown.. I'll take it :)  That guy needs better form but it works for me thanks

**Comment by goyney** [comment]
I think we're going to alias this icon "wrestling" and close this issue.

**Comment by goyney** [comment]
Alias added!
