### ISSUE TITLE
flag-modifiers

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3556]
I've recently come across a need for adding and removing a flag in an application. Here are all three modifiers for `flag`: `flag-plus`, `flag-remove`, and `flag-minus`.

---

~~[flag-plus](https://user-images.githubusercontent.com/4528551/46368984-d9412f80-c63e-11e8-8df6-309e4ba38e88.png) [flag-remove](https://user-images.githubusercontent.com/4528551/46369013-ecec9600-c63e-11e8-9630-7df46d9be445.png) [flag-minus](https://user-images.githubusercontent.com/4528551/46369117-26bd9c80-c63f-11e8-9156-13650736c9d7.png)~~

~~[flag-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2439211/flag-modifiers.zip)~~

**Comment by MrGrigri** [comment]
Moved the flag to the left one pixel. However, I kept the modifiers in the same place for consistency reasons.

![image](https://user-images.githubusercontent.com/4528551/46429824-9cd80700-c704-11e8-9964-f09c497baad0.png) ![image](https://user-images.githubusercontent.com/4528551/46429876-b8dba880-c704-11e8-8a77-2bbb72cc4ef0.png) ![image](https://user-images.githubusercontent.com/4528551/46429851-ab262300-c704-11e8-89ac-493d458a2220.png)

[flag-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2443220/flag-modifiers.zip)

**Comment by Templarian** [comment]
Added. 😸
