### ISSUE TITLE
Please reconsider before immediately closing as duplicate: GitLab

### ISSUE THREAD

**Issue by raniesantos** [Templarian/MaterialDesign#3557]
I have seen #1279 and the conversations in it that bore no fruit.

Just design one [similar to this](https://fontawesome.com/v4.7.0/icon/gitlab) and be done with it.

**Comment by Templarian** [comment]
@raniesantos Looks like they've relaxed their guidelines a little more to allow use. This was not the case before. Closing this issue and reopening the main issue.
