### ISSUE TITLE
car-electric

### ISSUE THREAD

**Issue by WoosterInitiative** [Templarian/MaterialDesign#3558]
Just a simple icon showing an EV

Something like https://www.flaticon.com/premium-icon/electric-car_242847#term=electric%20car&page=1&position=25 maybe, but a better looking car.

**Comment by goyney** [comment]
We also have `ev-station`, but it looks like we have nothing indicating a car ran on electricity.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/46615737-35400400-cad6-11e8-9762-6c52246eb29f.png)

[car-electric.zip](https://github.com/Templarian/MaterialDesign/files/2456396/car-electric.zip)

**Comment by MrGrigri** [comment]
After looking at `car-wash`, I believe that size would be better. 

![image](https://user-images.githubusercontent.com/4528551/46629660-e5c1fe00-cafe-11e8-8b7a-c76e37ed5e22.png)

[car-electric-large.zip](https://github.com/Templarian/MaterialDesign/files/2457450/car-electric-large.zip)

**Comment by Templarian** [comment]
[![car-electric](https://materialdesignicons.com/icon/car-electric)](https://materialdesignicons.com/icon/car-electric)
