### ISSUE TITLE
arrow curved

### ISSUE THREAD

**Issue by lkoeln** [Templarian/MaterialDesign#3559]
Arrows that indicate steps in a process

**Comment by lkoeln** [comment]
Sure, I didn't know that there is such a great tool! 👍

![image](https://user-images.githubusercontent.com/11266750/46493796-91becd00-c811-11e8-95aa-f8ade89faffd.png)

![image](https://user-images.githubusercontent.com/11266750/46493831-a13e1600-c811-11e8-8fc9-b038d000457f.png)

![image](https://user-images.githubusercontent.com/11266750/46493909-cd599700-c811-11e8-9ece-7641eb75e8c5.png)

![image](https://user-images.githubusercontent.com/11266750/46493761-7b187600-c811-11e8-983c-de92d2ac8e74.png)

**Comment by MrGrigri** [comment]
I believe they should all go in one direction (e.g. counter-clockwise).

**Comment by PeterShaggyNoble** [comment]
See also the existing `undo` & `redo` icons.

**Comment by goyney** [comment]
Yeah, I think `undo` and `redo` capture this use case. If you need the other two, a simple rotation of 90 degrees would work.

**Comment by lkoeln** [comment]
That's true. I looked for this icon by searching for "Arrow" and couldn't find it there. Is it possible to add this icon to the other arrows as well?

**Comment by goyney** [comment]
I've added the `arrow` alias to `undo`, `undo-variant`, `redo`, and `redo-variant`.
