### ISSUE TITLE
Vkontakte icon

### ISSUE THREAD

**Issue by kybarg** [Templarian/MaterialDesign#356]
Like font-awesome`s one http://fortawesome.github.io/Font-Awesome/icon/vk/

**Comment by Templarian** [comment]
Russian Facebook it appears.

http://materialdesignicons.com/icon/vk

**Comment by kybarg** [comment]
Thanks

**Comment by Templarian** [comment]
Random update, that was like the 182nd most searched keyword for the month. Always takes one person to open an issue. That's 50 searches a day for that 1 icon!

**Comment by Templarian** [comment]
@giovannilaperna We removed most brand logos back in the 4.0 release few years ago. Too much legal headaches, so we recommend [Simple Icons](https://simpleicons.org/). They do a much better job keeping everything up to date.
