### ISSUE TITLE
List of all icon names

### ISSUE THREAD

**Issue by touficbatache** [Templarian/MaterialDesign#3564]
Hi!
Thanks for this amazing library. How can I get a list of all icon names? For example, all the ones inside https://github.com/Templarian/MaterialDesign/tree/master/icons/svg. Something like that:
`{VECTOR_SQUARE,ACCESS_POINT,ACCESS_POINT_NETWORK,ACCOUNT}`
Thanks!

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-SVG

You're looking for this repo. You can also write scripts to generate your own JSON files described in this blog post. We'll be converting this into a guide in the docs shortly.

http://templarian.com/2018/04/13/scripting-with-nodejs-and-material-design-icons/

**Comment by Templarian** [comment]
Sorry, to be specific it's the `meta.json` file in that repo. 😄

**Comment by touficbatache** [comment]
With JS and the Chrome console I exported the list of icons: `$scope.icons` to a file 😃

Thanks anyway @Templarian

**Comment by Templarian** [comment]
That also works. We generate the `meta.json`/`svg` files at the same time as the font builds. The `meta.json` basically is a dump of our DB for third party utilities and libraries.

**Comment by touficbatache** [comment]
Oh yeah, that's exactly `$scope.icons`'s content. I used JS to capitalize, replace `-` with `_` and just have the names...
Have you heard of [this library](https://github.com/code-mc/material-icon-lib)? I am submitting a PR to update it 😃

**Comment by Templarian** [comment]
Yep, he's been supporting it forever. If you're looking for a quick PR for `Hacktoberfest` and to help out android devs. Would be cool to have a quick section explaining that library and linking to it on our android docs (click the edit on github button).

http://dev.materialdesignicons.com/getting-started/android

**Comment by touficbatache** [comment]
There you go! 😃 https://github.com/Templarian/MaterialDesign-Site/pull/65

**Comment by touficbatache** [comment]
Hey @grandhisubrahmanyam35, take a look here :smiley: https://github.com/Templarian/MaterialDesign-SVG

**Comment by Templarian** [comment]
@grandhisubrahmanyam35 Were you looking specifically in the docs anywhere? We may need to link to the `meta.json` there for future users.

Sorry about that, we're still working on the documentation, it's one of our top goals to make the getting started earlier to understand.

**Comment by PeterShaggyNoble** [comment]
It's also available on the CDN at http://cdn.materialdesignicons.com/3.0.39/meta.json
