### ISSUE TITLE
Collection icon

### ISSUE THREAD

**Issue by siulca** [Templarian/MaterialDesign#3573]
How about an icon that symbolizes a collection? 

Examples of collections:
- card collection
- stamp collection
- sticker book

**Comment by MrGrigri** [comment]
Please give us an example of how you would like this visualized.

**Comment by siulca** [comment]
Sorry, I'm not quite sure, I'm not a designer. Maybe some sort of little booklet symbolizing a sticker book?

**Comment by PeterShaggyNoble** [comment]
Do any of the existing [book icons](https://petershaggynoble.github.io/MDI-Sandbox/?filter=book) suit your needs?

One of the [cards icons](https://petershaggynoble.github.io/MDI-Sandbox/?filter=cards) might cover a card collection and see #418 for a stamp icon.

**Comment by siulca** [comment]
The generic 'cards' one is suitable. The book icons look too much like a regular book and not a sticker booklet. But I guess you can't add much detail at that size. These will do, thank you.

**Comment by MrGrigri** [comment]
Closing this unless you decide they don't work.
