### ISSUE TITLE
ios-share

### ISSUE THREAD

**Issue by garygrubb** [Templarian/MaterialDesign#3574]
This is a suggestion for a new icon, the iphone share icon which is usually found at the bottom of the safari browser. It looks like [this](https://goo.gl/images/6tfvpf).

**Comment by goyney** [comment]
We already have `export`, which could simply be rotated:

![image](https://user-images.githubusercontent.com/1015040/46613046-2bbb9980-cae0-11e8-86c1-7a21cfa19328.png)

**Comment by goyney** [comment]
Or we could potentially add an already rotated version:

![image](https://user-images.githubusercontent.com/1015040/46613114-6ae9ea80-cae0-11e8-9d74-dbd78d8c9e0e.png)

No idea what to call it though.

**Comment by goyney** [comment]
Looks like this icon is included in Google's extended set as `ios-share`.

![image](https://user-images.githubusercontent.com/1015040/46613755-04fe6280-cae2-11e8-8bc9-dbaf49ebd70d.png)

**Comment by garygrubb** [comment]
Thanks. I will use the rotated export for now. I did not notice it earlier.

**Comment by Templarian** [comment]
[![export-variant](https://materialdesignicons.com/icon/export-variant)](https://materialdesignicons.com/icon/export-variant)

Probably best to keep this not specific if they ever change their icon.
