### ISSUE TITLE
Icons To Be Reassigned (v3.0.x)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3575]
We're getting closer to having all brand icons assigned to the Contributors' account; the list below should take care of the last few. If anyone spots any other icons that need to be reassigned prior to the release of v3.0.x, please edit them into the list.

## Assign to Austin Andrews
- [x] `currency-btc` (also needs to be removed from the brands tag)
## Assign to Contributors
- [x] `airplay`
- [x] `apple-finder`
- [x] `apple-ios`
- [x] `bluetooth`
- [x] `clippy`
- [x] `facebook-box`
- [x] `instagram`
- [x] `language-c`
- [x] `language-cpp`
- [x] `language-csharp`
- [x] `language-css3`
- [x] `language-html5`
- [x] `language-java`
- [x] `language-javascript`
- [x] `language-lua`
- [x] `language-php`
- [x] `language-python`
- [x] `language-python-text`
- [x] `language-r`
- [x] `language-swift`
- [x] `language-typescript`
- [x] `linkedin-box`
- [x] `pinterest-box`
- [x] `pokeball`
- [x] `polymer`
- [x] `tumblr`
- [x] `tumblr-box`
- [x] `twitter-box`
- [x] `xaml`
## Assign to Google
- [x] `google-circles-group` 
- [x] `language-go`
## Assign to Peter Noble
- [x] `currency-eth` (also needs to be removed from the brands tag)

**Comment by Templarian** [comment]
I'm going to assign all the currency icons to Contributor to make it consistent. I think we've got most of them.

Will work to get these in tonight. Want to get all these breaking changes in before `3.0.xx`.
