### ISSUE TITLE
JSX

### ISSUE THREAD

**Issue by chinchang** [Templarian/MaterialDesign#3576]
JSX is a file extension for a file containing JSX code.

**Comment by Templarian** [comment]
I like how you think that describes it. 🤣 

But yea, my day job is React (just prefer Angular for side projects).

So like the text or does JSX have an icon now-a-days. In VS Code they use the react logo which we have already.

**Comment by chinchang** [comment]
Different VSCode themes show it differently. One is react logo, like you mentioned. Or it could be like the JS logo (JS text written inside a square), but JSX written instead JS.

**Comment by MrGrigri** [comment]
https://github.com/jsx/jsx/issues/9

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/46642750-52102200-cb3e-11e8-9153-6a11e731d1b6.png)

Something like this?

**Comment by Templarian** [comment]
@MrGrigri https://github.com/facebook/jsx is the correct repo, no idea what the jsx repo is.

**Comment by goyney** [comment]
I think the React logo is the standard for recognizing JSX files. I would suggest using `react` instead of coming up with our own thing.

**Comment by Templarian** [comment]
Kind of agree with @goyney on this unless someone feels strongly I'll just close this issue out.

**Comment by chinchang** [comment]
You guys are damn quick! Thanks! React logo makes sense.
