### ISSUE TITLE
karotz

### ISSUE THREAD

**Issue by hobbe** [Templarian/MaterialDesign#3577]
Provide an icon for [Karotz](https://en.wikipedia.org/wiki/Nabaztag#Karotz) (p.k.a. [Nabaztag](https://en.wikipedia.org/wiki/Nabaztag)), the smart connected object in the shape of a rabbit.

The goal is to represent this connected object in IT landscapes and home automation applications, just like a NAS or Raspberry Pi.

A common representation is:
![karotz](https://user-images.githubusercontent.com/312886/46659750-d2be3500-cbb5-11e8-9707-ff2510eb2870.png)

**Comment by goyney** [comment]
This seems pretty niche and the icon suggestion provided looks more like a skyscraper than a rabbit.

**Comment by MrGrigri** [comment]
Yeah, I'm going to close this out as it's too niche.
