### ISSUE TITLE
1up

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3580]
Since we're nerding out right now:

![image](https://user-images.githubusercontent.com/1015040/46678040-c041fc80-cbb1-11e8-9ee6-854c63555c24.png)

[1up.zip](https://github.com/Templarian/MaterialDesign/files/2460949/1up.zip)

**Comment by Templarian** [comment]
Needs to be reduced to 18x18 preferably, but 20x20 might work.

**Comment by goyney** [comment]
Updated.

**Comment by Templarian** [comment]
[![one-up](https://materialdesignicons.com/icon/one-up)](https://materialdesignicons.com/icon/one-up)
