### ISSUE TITLE
diamond

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3583]
I understand that we already have a `diamond`. But I'm suggesting that we rename `diamond` to `diamond-stone` and then add a `diamond` and `diamond-outline` icons. This is best to represent a super something. I'm using it currently in a new app to represent a 'super-step' as opposed to just a regular step.

![image](https://user-images.githubusercontent.com/4528551/46681970-9f75a900-cba9-11e8-9db7-39d069f2e8e8.png) ![image](https://user-images.githubusercontent.com/4528551/46682026-c03dfe80-cba9-11e8-9c21-d09d13b8718e.png) ![image](https://user-images.githubusercontent.com/4528551/46682005-b61c0000-cba9-11e8-8667-b330b9d01938.png)

[diamond.zip](https://github.com/Templarian/MaterialDesign/files/2461192/diamond.zip)

**Comment by Templarian** [comment]
Added. 😃
