### ISSUE TITLE
swap-bold

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3584]
`swap-horizontal-bold` and `swap-vertical-bold` from Google Maps. 

![image](https://user-images.githubusercontent.com/4528551/46683766-40fef980-cbae-11e8-95ae-ac7530208972.png) ![image](https://user-images.githubusercontent.com/4528551/46683776-48260780-cbae-11e8-942a-cc66538f9af3.png)

[swap-bold.zip](https://github.com/Templarian/MaterialDesign/files/2461319/swap-bold.zip)

**Comment by Templarian** [comment]
Added. 😃
