### ISSUE TITLE
Danmaku (aka flying comments)

### ISSUE THREAD

**Issue by 01010101lzy** [Templarian/MaterialDesign#3587]
I made 8 icons for situations involving Danmaku (Chinese: 弹幕; Japanese: 弾幕) (aka flying comments), similar to that in Bilibili's mobile client and website. They are filled and outline version of *danmaku*, *danmaku (turned) off*, and two versions of *danmaku settings*. (Maybe I should put them in separate issues?)

These two pics are use cases for the icons. Both are screenshots from Bilibili.

![default](https://user-images.githubusercontent.com/10259119/46800064-1d43db00-cd89-11e8-85f8-7b2612a3dbe6.png)
![default](https://user-images.githubusercontent.com/10259119/46800665-030afc80-cd8b-11e8-9a2f-cbb5516815eb.png)

And This is what I made:

![default](https://user-images.githubusercontent.com/10259119/46800035-0bface80-cd89-11e8-92dc-dd57407e526e.png)

Separate svg icons as well as the original Affinity Designer file are packed up in a zip here: 
[181011-danmaku-icons.zip](https://github.com/Templarian/MaterialDesign/files/2468649/181011-danmaku-icons.zip)

**Comment by GreenTurtwig** [comment]
Nah, if the icons are similar it's best to keep them in the same issue, you're good. :+1: 

I'm not sure how well these icons convey danmaku, upon first glace they look to represent bullet pointed lists rather than comments. I know that NicoNico uses a regular comment icon like below, so perhaps we should get some `off` and `settings` variants of that instead?
[![](https://materialdesignicons.com/icon/comment)](https://materialdesignicons.com/icon/comment)

**Comment by Templarian** [comment]
I'm leaning to just call these `card-*`. They could be used for several uses.

**Comment by Templarian** [comment]
@01010101lzy Awesome, you can find your contributor page here. I'll be opening up the ability to edit this info shortly. http://materialdesignicons.com/contributor/Rynco-Li

Just a note, on the outline if you view the corner inner points on the left they have curve points. Had to remove those as it increases the font size. Just double check this for future icons. Few minor tweaks on some of the points you'll notice, but very minor. Really great job for a first contribution.

I also added 2 blank `card` icons and 2 `card-text` icons. So you have 10 icons so far. 😺 

[![card](https://materialdesignicons.com/icon/card)](https://materialdesignicons.com/icon/card) [![card-outline](https://materialdesignicons.com/icon/card-outline)](https://materialdesignicons.com/icon/card-outline) [![card-text](https://materialdesignicons.com/icon/card-text)](https://materialdesignicons.com/icon/card-text) [![card-text-outline](https://materialdesignicons.com/icon/card-text-outline)](https://materialdesignicons.com/icon/card-text-outline)
etc...

Open issues for any future icons. Thanks!

**Comment by 01010101lzy** [comment]
@Templarian Thanks! 

---


> Just a note, on the outline if you view the corner inner points on the left they have curve points. Had to remove those as it increases the font size.

![default](https://user-images.githubusercontent.com/10259119/46900027-2ab6ad80-cece-11e8-87ab-1ee52a411079.png)

Do you mean these curves? They are probably flaws in Affinity Designer when adding up curves. I will check them more precisely next time.

Thanks again!

**Comment by Templarian** [comment]
Yep those. NP, working on adding validation tooling to catch those so the system won't let it upload. Right now I'm still doing a lot of manual checking on each before upload.
