### ISSUE TITLE
Discussion: RTL Icons

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3589]
We've had this discussion internally a couple times, but I want to have a public discussion about how we should handle RTL icons.

A few options discussed in the past...

- Most icons can be flipped
- Adding a top level modifier for `*-rtl`

Could go either way, not sure how much of a need there is because right now we don't really localize anything for RTL. I don't want to use site metrics for this as it's going to be very biased.

**Comment by MrGrigri** [comment]
For reference, [here](https://material.io/design/usability/bidirectionality.html#mirroring-layout) is the link for bidirectionality on the MD Guidelines site. They cover a lot and I believe we need to maintain their thought process.

**Comment by MrGrigri** [comment]
With that in mind, I believe, for the most part, the icons with text representation would be the ones with an `-rtl` modifier. 

![image](https://user-images.githubusercontent.com/4528551/48809758-307c8b80-ece3-11e8-9758-58679336f2b1.png) ![image](https://user-images.githubusercontent.com/4528551/48809898-c7494800-ece3-11e8-8398-40d940e92227.png)

**Comment by Templarian** [comment]
Agreed, these seem like very easy additions for the team to make. I'm creating a label `RTL`, please tag icon requests and I'll try my best to ensure they can included as soon as possible.

I'll also mark them as a Style in the database `rtl`. That way we can easily see all of them.

**Comment by PeterShaggyNoble** [comment]
I'd also be of the opinion that if an icon can simply be flipped (e.g., `format-list-bulleted`) then we don't need to add an `rtl` variant of it but if it can't (e.g., `format-list-numbered`) then we should.

And we should probably alias all `rtl` icons with `right-to-left`, too.

**Comment by JamesCoyle** [comment]
Closing this as we are now handling RTL as necessary.
