### ISSUE TITLE
Wallet Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3590]
![image](https://user-images.githubusercontent.com/10384436/46904138-9b15fc80-ced7-11e8-88c3-8e8cc1e414be.png)
[wallet-outline.zip](https://github.com/Templarian/MaterialDesign/files/2475335/wallet-outline.zip)

**Comment by Templarian** [comment]
[![wallet-outline](https://materialdesignicons.com/icon/wallet-outline)](https://materialdesignicons.com/icon/wallet-outline)
