### ISSUE TITLE
Clipboard Account Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3593]
![image](https://user-images.githubusercontent.com/10384436/46904411-85a2d180-cedb-11e8-9d4f-e76a2e6c71f9.png)
[clipboard-account-outline.zip](https://github.com/Templarian/MaterialDesign/files/2475355/clipboard-account-outline.zip)

**Comment by Templarian** [comment]
I didn't like the spacing around the account, so went with a solid version.
