### ISSUE TITLE
Clipboard Arrow Right + Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3597]
![image](https://user-images.githubusercontent.com/10384436/46904510-f1d20500-cedc-11e8-9081-80fccec2a678.png)![image](https://user-images.githubusercontent.com/10384436/46904470-85ef9c80-cedc-11e8-9c71-3f0cbb547d8a.png)

[clipboard-arrow-right.zip](https://github.com/Templarian/MaterialDesign/files/2475368/clipboard-arrow-right.zip)

**Comment by Templarian** [comment]
Added. 😃
