### ISSUE TITLE
Clipboard Check + Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3598]
![image](https://user-images.githubusercontent.com/10384436/46904542-8fc5cf80-cedd-11e8-967e-ccc7fea9b95d.png)![image](https://user-images.githubusercontent.com/10384436/46904544-a5d39000-cedd-11e8-9acd-33d320ef19e0.png)

[clipboard-check.zip](https://github.com/Templarian/MaterialDesign/files/2475371/clipboard-check.zip)

**Comment by Templarian** [comment]
Not a fan of their variation (mostly with the top hole/cutout for outline.

going to keep our variation for this.
