### ISSUE TITLE
Cloud Upload Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3600]
![image](https://user-images.githubusercontent.com/10384436/46904617-0dd6a600-cedf-11e8-9a8b-e5df24a47fa4.png)
[cloud-upload.zip](https://github.com/Templarian/MaterialDesign/files/2475377/cloud-upload.zip)

**Comment by Templarian** [comment]
[![cloud-upload-outline](https://materialdesignicons.com/icon/cloud-upload-outline)](https://materialdesignicons.com/icon/cloud-upload-outline)
