### ISSUE TITLE
Wrench Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3601]
![image](https://user-images.githubusercontent.com/10384436/46904659-9ce3be00-cedf-11e8-9e55-b7e432c9f551.png)
[wrench-outline.zip](https://github.com/Templarian/MaterialDesign/files/2475380/wrench-outline.zip)

**Comment by Templarian** [comment]
[![wrench-outline](https://materialdesignicons.com/icon/wrench-outline)](https://materialdesignicons.com/icon/wrench-outline)
