### ISSUE TITLE
Calendar Blank Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3602]
![image](https://user-images.githubusercontent.com/10384436/46904691-49be3b00-cee0-11e8-984f-247ba96baf32.png)
[calendar-blank-outline.zip](https://github.com/Templarian/MaterialDesign/files/2475381/calendar-blank-outline.zip)

**Comment by Templarian** [comment]
[![calendar-blank-outline](https://materialdesignicons.com/icon/calendar-blank-outline)](https://materialdesignicons.com/icon/calendar-blank-outline)

@JamesCoyle The size of that icon is wrong for some reason?

**Comment by JamesCoyle** [comment]
Odd. Must just be Google being Google...
