### ISSUE TITLE
Calander Range Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3605]
![image](https://user-images.githubusercontent.com/10384436/46904783-7c1c6800-cee1-11e8-827b-4d5f6ecba349.png)
[calendar-range-outline.zip](https://github.com/Templarian/MaterialDesign/files/2475392/calendar-range-outline.zip)

**Comment by Templarian** [comment]
[![calendar-range-outline](https://materialdesignicons.com/icon/calendar-range-outline)](https://materialdesignicons.com/icon/calendar-range-outline)
