### ISSUE TITLE
Compass Off + Outline

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3610]
![image](https://user-images.githubusercontent.com/10384436/46904913-a5d68e80-cee3-11e8-92ff-d90adb3ea7b1.png)![image](https://user-images.githubusercontent.com/10384436/46904917-bab32200-cee3-11e8-9739-d3f7ea874d84.png)
[compass-off-outline.zip](https://github.com/Templarian/MaterialDesign/files/2475412/compass-off-outline.zip)

**Comment by Templarian** [comment]
Something was very wrong with those two vectors... not sure why they are so many points. Fixed though.

Added both. 😃
