### ISSUE TITLE
View Split Pane

### ISSUE THREAD

**Issue by johngrimsey** [Templarian/MaterialDesign#3615]
<img width="23" alt="screen shot 2018-10-13 at 16 31 51" src="https://user-images.githubusercontent.com/898591/46907105-8e100200-cf05-11e8-9aec-c6c5e4022ff6.png">

Cheers

**Comment by PeterShaggyNoble** [comment]
This is Google's `vertical_split` icon. They also have a `horizontal_split` one.

[![vertical_split](http://mdi.houseofdesign.ie/tools/preview/?icon=vertical-split&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/) [![horizontal_split](http://mdi.houseofdesign.ie/tools/preview/?icon=horizontal-split&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by JamesCoyle** [comment]
Will add the SVGs when I get home

**Comment by JamesCoyle** [comment]
[view-split.zip](https://github.com/Templarian/MaterialDesign/files/2479791/view-split.zip)

**Comment by johngrimsey** [comment]
@JamesCoyle Thanks man I'd missed that

**Comment by Templarian** [comment]
[![split-vertical](https://materialdesignicons.com/icon/split-vertical)](https://materialdesignicons.com/icon/split-vertical) [![split-horizontal](https://materialdesignicons.com/icon/split-horizontal)](https://materialdesignicons.com/icon/split-horizontal)
