### ISSUE TITLE
Fuse

### ISSUE THREAD

**Issue by marrobHD** [Templarian/MaterialDesign#3616]
Fuse

**Comment by marrobHD** [comment]
![img_20181016_105952](https://user-images.githubusercontent.com/29308361/47004902-dfe99f80-d132-11e8-8670-1f252eea3321.jpg)

**Comment by MrGrigri** [comment]
You mean like an electrical fuse?

**Comment by goyney** [comment]
Maybe something like this?

![image](https://user-images.githubusercontent.com/1015040/48368681-6c2fa980-e682-11e8-9f5e-1879d9c9bfd1.png) ![image](https://user-images.githubusercontent.com/1015040/48368702-7ce01f80-e682-11e8-804d-ca2af5f51304.png)

[fuse.zip](https://github.com/Templarian/MaterialDesign/files/2573223/fuse.zip)

**Comment by Templarian** [comment]
Added both. 😃
