### ISSUE TITLE
New Home Outline

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3617]
It appears in the new Google Home‏ app
![the icon](https://user-images.githubusercontent.com/16443111/46917876-650a7280-cfd4-11e8-9d1c-891030608983.png)

**Comment by PeterShaggyNoble** [comment]
Here's the solid version to go with it.

[![home_filled](http://mdi.houseofdesign.ie/tools/preview/?icon=home-filled&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by Templarian** [comment]
Updated / Added as `home-variant` and `home-variant-outline`.
