### ISSUE TITLE
account-group-outline

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3618]

**Comment by ofekashery** [comment]
I would be happy if someone could help me by create this icon quickly

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/47046455-063c2900-d18d-11e8-8697-e6533e1b28ea.png)](https://github.com/Templarian/MaterialDesign/files/2484847/account-group-outline.zip)

**Comment by ofekashery** [comment]
Wow, excellent!

**Comment by ofekashery** [comment]
@Templarian When will it be on the site?

**Comment by Templarian** [comment]
Soon™

**Comment by Templarian** [comment]
[![account-group-outline](https://materialdesignicons.com/icon/account-group-outline)](https://materialdesignicons.com/icon/account-group-outline)
