### ISSUE TITLE
Suggestions box icon

### ISSUE THREAD

**Issue by mevcloud** [Templarian/MaterialDesign#362]
Thx!
- [ ] suggestion

**Comment by cvsguimaraes** [comment]
Please provide an example...

**Comment by mevcloud** [comment]
http://teamripped.com/wp-content/uploads/2014/02/suggestions.jpg

A box with a vote comming in

**Comment by CoDEmanX** [comment]
I would use a light bulb, which is a common metaphor for an idea, invention, ...
https://materialdesignicons.com/icon/lightbulb-outline

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/message-alert)](https://materialdesignicons.com/icon/message-alert)

Google uses this for send feedback.

**Comment by Templarian** [comment]
Closing this issue as we clean up the backlog.
