### ISSUE TITLE
mdi-discord-box

### ISSUE THREAD

**Issue by raniesantos** [Templarian/MaterialDesign#3620]
For context, I want to put a Discord icon in my footer beside a twitter-box and github-box icon.

The regular Discord icon looks out of place beside those other two.

**Comment by raniesantos** [comment]
Going slightly off-topic...

To avoid having to make new icons like this for simple variations, you could implement a 'stack' class like font-awesome.

Advantages:

- Less icon requests like this one (honestly I want to request a gitlab-box icon too after seeing the gitlab icon in the commits)
- reduce package size due to fewer css classes

**Comment by PeterShaggyNoble** [comment]
Looking at [their brand guidlines](https://discordapp.com/branding), it doesn't look like we'll be able to add this one:

> Please do not edit, change, distort, recolor, or reconfigure the Discord logo

Stacking is currently available in the [React module](https://github.com/Templarian/MaterialDesign-React/).

**Comment by goyney** [comment]
Agreed, we cannot add this variation as it goes against Discord's branding guidelines.

**Comment by Templarian** [comment]
@raniesantos We're working on first party packages for Vue and Angular right now to handle stacking also. The webfont may get support, but we're still not 100% sure if this will make a release anytime soon.
