### ISSUE TITLE
shield-cross

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3623]
![image](https://user-images.githubusercontent.com/1015040/46991345-90c05200-d0d3-11e8-8d81-626600d2785d.png)![image](https://user-images.githubusercontent.com/1015040/46991351-9a49ba00-d0d3-11e8-9eed-3d20a6d65ba2.png)

[shield-cross.zip](https://github.com/Templarian/MaterialDesign/files/2481326/shield-cross.zip)

**Comment by Templarian** [comment]
Added 😃
