### ISSUE TITLE
skull-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3624]
![image](https://user-images.githubusercontent.com/1015040/46991405-d54bed80-d0d3-11e8-991e-b221d37306d9.png)![image](https://user-images.githubusercontent.com/1015040/46991386-c49b7780-d0d3-11e8-8815-46daea31af03.png)

Wanted to keep the eyes and nose lined up at the same x,y positioning.

[skull-outline.zip](https://github.com/Templarian/MaterialDesign/files/2481329/skull-outline.zip)

**Comment by Templarian** [comment]
[![skull-outline](https://materialdesignicons.com/icon/skull-outline)](https://materialdesignicons.com/icon/skull-outline)
