### ISSUE TITLE
skull-crossbones

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3625]
![image](https://user-images.githubusercontent.com/1015040/46991454-062c2280-d0d4-11e8-80c5-4cfe58f3709d.png)![image](https://user-images.githubusercontent.com/1015040/46991457-10e6b780-d0d4-11e8-80f9-e43450744cd4.png)

Not sure about the outline version of this one, looking for feedback/suggestions. Again, wanted to keep the eyes and nose lined up at the same x,y position.

[skull-crossbones.zip](https://github.com/Templarian/MaterialDesign/files/2481336/skull-crossbones.zip)

**Comment by MrGrigri** [comment]
I believe its modern name is `jolly-roger`. We should add that as an alias or swap the names.

**Comment by GreenTurtwig** [comment]
@mrgrigri Jolly Roger is the name of the flag, skull and crossbones is the symbol, thus correct here. But yeah, we should add that as an alias.

**Comment by Templarian** [comment]
[![skull-crossbones](https://materialdesignicons.com/icon/skull-crossbones)](https://materialdesignicons.com/icon/skull-crossbones) [![skull-crossbones-outline](https://materialdesignicons.com/icon/skull-crossbones-outline)](https://materialdesignicons.com/icon/skull-crossbones-outline)
