### ISSUE TITLE
Trakt

### ISSUE THREAD

**Issue by caffeinatedMike** [Templarian/MaterialDesign#3626]
I would love to see an official Material Design icon for the Trakt.tv logo. 

![Trakt.tv Icon](https://trakt.tv/assets/logos/header@2x-09f929ba67b0964596b359f497884cd9.png)

The website provides a Branding resource page [here](https://trakt.tv/branding) where they provide vector & pixel images in a zipped folder. So, I imagine it should be relatively easy to incorporate the icon (for those that know how to). 

Direct Zip Link for their Logo can be downloaded using [this link](https://walter.trakt.tv/logos/trakt-logos-icon.zip)

**Comment by PeterShaggyNoble** [comment]
This is currently beyond the scope of the project, being too niche/obscure. We may revisit this issue if we decide to release a dedicated icon pack for brand icons.
