### ISSUE TITLE
dots-horizontal-circle-outline and dots-vertical-circle-outline 

### ISSUE THREAD

**Issue by justinlawrence** [Templarian/MaterialDesign#3628]
just like dots-horizontal-circle and dots-vertical-cirlce, but with an outline instead of a fill. Thanks!

![screenshot 2018-10-16 at 23 55 22](https://user-images.githubusercontent.com/1521183/47052118-fcbbbc80-d19e-11e8-96b7-08f1803b1be7.png)
![screenshot 2018-10-16 at 23 56 20](https://user-images.githubusercontent.com/1521183/47052159-2379f300-d19f-11e8-8194-a07116526003.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/47062623-bc5b3f00-d19c-11e8-964b-03a197b35972.png)

I think you meant to make it 20x20 like above.

**Comment by justinlawrence** [comment]
Yes, please. 🙏

**Comment by MrGrigri** [comment]
Yes, @Templarian, I guess I didn't pay attention enough.

**Comment by Templarian** [comment]
[![dots-horizontal-circle-outline](https://materialdesignicons.com/icon/dots-horizontal-circle-outline)](https://materialdesignicons.com/icon/dots-horizontal-circle-outline) [![dots-vertical-circle-outline](https://materialdesignicons.com/icon/dots-vertical-circle-outline)](https://materialdesignicons.com/icon/dots-vertical-circle-outline)
