### ISSUE TITLE
folder-plus-outline

### ISSUE THREAD

**Issue by justinlawrence** [Templarian/MaterialDesign#3629]
Just like folder-outline, but with a plus. Just like the plus on folder-plus.

![screenshot 2018-10-17 at 00 04 30](https://user-images.githubusercontent.com/1521183/47052447-4062f600-d1a0-11e8-9904-e3f2e5ea5767.png)

Thanks!

**Comment by MrGrigri** [comment]
Please see the [guidelines](http://dev.materialdesignicons.com/contribute/icon-naming#overlay) for the `*-plus` modifier.

**Comment by MrGrigri** [comment]
[Here](https://material.io/tools/icons/?search=folder&icon=create_new_folder&style=outline) is the google `folder-plus-outline` icon.

**Comment by justinlawrence** [comment]
Thanks Michael. I'm confused. We use the icons in the
https://materialdesignicons.com library. Are you saying we should use both
libraries? I wasn't actually suggesting a design for the icon—I was just
giving a rough approximation.

Thanks

**Comment by MrGrigri** [comment]
No, this is a Google stock icon and it's only a reference for the team to contribute it to Google instead of me; for instance. It'll get added if the team feels it's worth adding. Does that make sense?

**Comment by Templarian** [comment]
[![folder-plus-outline](https://materialdesignicons.com/icon/folder-plus-outline)](https://materialdesignicons.com/icon/folder-plus-outline) [![folder-star-outline](https://materialdesignicons.com/icon/folder-star-outline)](https://materialdesignicons.com/icon/folder-star-outline) [![folder-account-outline](https://materialdesignicons.com/icon/folder-account-outline)](https://materialdesignicons.com/icon/folder-account-outline) [![folder-remove-outline](https://materialdesignicons.com/icon/folder-remove-outline)](https://materialdesignicons.com/icon/folder-remove-outline)

**Comment by justinlawrence** [comment]
You guys/girls are awesome, thanks!
