### ISSUE TITLE
Sugestion: Edit column icons

### ISSUE THREAD

**Issue by cafenroy** [Templarian/MaterialDesign#363]
edit the available column to show in a grid or excel like table.

- [x] table-edit
- [x] table-column-plus-after
- [x] table-column-plus-before
- [x] table-column-width
- [x] table-column-remove
- [x] table-row-height
- [x] table-row-plus-before
- [x] table-row-plus-after
- [x] table-column-remove

**Comment by cvsguimaraes** [comment]
Please provide some examples...

**Comment by Templarian** [comment]
I updated your issue with tasks, let me know if I missed any.

**Comment by cafenroy** [comment]
The "table-edit" is exactly what I where looking for!!

Tanks!

**Comment by Templarian** [comment]
Glad that helped. I've added the other 8 icons related to this issue.
