### ISSUE TITLE
Rocks, Boulders

### ISSUE THREAD

**Issue by siteturbo** [Templarian/MaterialDesign#3630]
Rocks, Boulders, Falling Rocks

**Comment by MrGrigri** [comment]
I do not believe this would be a good icon to add. Most 'falling rock' signs have a car next to a cliff with rocks coming down. I do not believe that 24x24 pixel size is big enough for that kind of detail.

**Comment by Ch-Lo** [comment]
Here is a version without car or cliff.
[](https://www.schilder-versand.com/assets/gfx/product/300x300/steinschlag-aufstellung-rechts-verkehrsschild-vz-101-15-21743-p7n01-1504267622.jpg)

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
