### ISSUE TITLE
Google DFP Icon

### ISSUE THREAD

**Issue by mikebpech** [Templarian/MaterialDesign#3632]
Please include the google DFP icon

It looks like this; 
https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjD57WMpJDeAhWmnuAKHZjGAW4QjRx6BAgBEAU&url=https%3A%2F%2Fwww.townnews365.com%2Fnews_room%2Fbookmark-these-dfp-resources-and-tools-today%2Farticle_b3076368-dc00-11e6-a7f2-7333932bda18.html&psig=AOvVaw1GI1slct1gZAW6EM2zgnCi&ust=1539962122462241

**Comment by goyney** [comment]
The nature of that icon is going to make it extremely difficult to create. I also cannot find any information on this logo or the branding requirements around it.

**Comment by mikebpech** [comment]
Fair Enough, it might not even be the correct logo.. They seem to change it quite often.
