### ISSUE TITLE
Wheat

### ISSUE THREAD

**Issue by burndragon** [Templarian/MaterialDesign#3633]
An icon that represents a wheat head

![element_wheat](https://user-images.githubusercontent.com/43213826/47169113-4b18aa80-d2c8-11e8-9ef2-e769de8e6ba9.png)

![element_wheat_big](https://user-images.githubusercontent.com/43213826/47169244-9a5edb00-d2c8-11e8-9d14-7eda0777dbab.png)

**Comment by burndragon** [comment]
barley and wheat are not the same when working with agriculture products.

**Comment by Templarian** [comment]
Definitely get that, but they are basically the same icon visibly. Not sure how to show them differently. Any ideas?

**Comment by MrGrigri** [comment]
I do not believe that there is a way to visually distinguish them at a 24x24 dimension.

**Comment by Templarian** [comment]
Closing this one out. Definitely use text in situations where it needs to be distinguished. I don't think any normal person would know the difference from a small icon.
