### ISSUE TITLE
video-outline

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3635]

**Comment by PeterShaggyNoble** [comment]
`video-outline` and `video-off-outline` can be found [here](https://material.io/tools/icons/?search=videocam&style=outline).

**Comment by Templarian** [comment]
[![video-outline](https://materialdesignicons.com/icon/video-outline)](https://materialdesignicons.com/icon/video-outline) [![video-off-outline](https://materialdesignicons.com/icon/video-off-outline)](https://materialdesignicons.com/icon/video-off-outline)
