### ISSUE TITLE
basketball-hoop

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3641]
Since the NBA has started this week, I thought I'd suggest a couple. I'm not sure how I feel about the non-outlined version.

![image](https://user-images.githubusercontent.com/4528551/47249281-2824ee00-d3cf-11e8-8705-e54b450d3a45.png) ![image](https://user-images.githubusercontent.com/4528551/47249293-3d018180-d3cf-11e8-94d9-fe9d7e072180.png)

[basketball-hoop.zip](https://github.com/Templarian/MaterialDesign/files/2497686/basketball-hoop.zip)

**Comment by MrGrigri** [comment]
I believe this one is better for the normal `basketball-hoop`.

![image](https://user-images.githubusercontent.com/4528551/47260260-201f8980-d475-11e8-8a05-55f66f1e5e18.png) ![image](https://user-images.githubusercontent.com/4528551/47260263-30376900-d475-11e8-922f-fb7120076a68.png)

[basketball-hoop.zip](https://github.com/Templarian/MaterialDesign/files/2498517/basketball-hoop.zip)

**Comment by Templarian** [comment]
Was just about to comment that the filled version looked a little off. Agreed the new one looks more consistent.

**Comment by Templarian** [comment]
Added. 😃
