### ISSUE TITLE
progress-alert

### ISSUE THREAD

**Issue by renehankel** [Templarian/MaterialDesign#3643]
[progress 000 procent alert.zip](https://github.com/Templarian/MaterialDesign/files/2501208/progress.000.procent.alert.zip)

**Comment by MrGrigri** [comment]
For reference:

![image](https://user-images.githubusercontent.com/4528551/48214151-93157500-e33c-11e8-978e-f8f5da47622b.png)

**Comment by MrGrigri** [comment]
I believe we should add a `progress-alert` icon based on the `progress-check` design.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/48216383-d2929000-e341-11e8-8481-04a107f51deb.png)

[progress-alert.zip](https://github.com/Templarian/MaterialDesign/files/2562849/progress-alert.zip)

**Comment by Templarian** [comment]
[![progress-alert](https://materialdesignicons.com/icon/progress-alert)](https://materialdesignicons.com/icon/progress-alert)
