### ISSUE TITLE
progress-timer-sand

### ISSUE THREAD

**Issue by renehankel** [Templarian/MaterialDesign#3649]
[progress 050 procent waiting.zip](https://github.com/Templarian/MaterialDesign/files/2501255/progress.050.procent.waiting.zip)

**Comment by MrGrigri** [comment]
For reference:

![image](https://user-images.githubusercontent.com/4528551/48214636-9a894e00-e33d-11e8-9690-53c2e3dbc55e.png)

**Comment by MrGrigri** [comment]
Removing the `contribution` label as this does not yet follow our guidelines for a single compound path or MD guidelines for not using 2-pixel width lines.

**Comment by MrGrigri** [comment]
We are going to close this issue as we feel progress and a sand clock are one and the same.
