### ISSUE TITLE
progress 50 percent

### ISSUE THREAD

**Issue by renehankel** [Templarian/MaterialDesign#3650]
[progress 050 procent.zip](https://github.com/Templarian/MaterialDesign/files/2501260/progress.050.procent.zip)

**Comment by MrGrigri** [comment]
For reference:

![image](https://user-images.githubusercontent.com/4528551/48214422-1e8f0600-e33d-11e8-89e3-ec638a94cd79.png)

**Comment by MrGrigri** [comment]
Closing this as we already have the `progress-check` icon.

![progress-check](https://materialdesignicons.com/icon/progress-check)
