### ISSUE TITLE
progress-wrench

### ISSUE THREAD

**Issue by renehankel** [Templarian/MaterialDesign#3651]
[progress 075 procent progress.zip](https://github.com/Templarian/MaterialDesign/files/2501307/progress.075.procent.progress.zip)

**Comment by MrGrigri** [comment]
For reference:

![image](https://user-images.githubusercontent.com/4528551/48214448-35355d00-e33d-11e8-937d-c1576d81f435.png)

**Comment by MrGrigri** [comment]
Removing the `contribution` label as this does not yet follow our guidelines for a single compound path.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48385940-6fe12180-e6be-11e8-8247-482d5eeb33e2.png)
[progress-wrench.zip](https://github.com/Templarian/MaterialDesign/files/2574339/progress-wrench.zip)

**Comment by MrGrigri** [comment]
I still don't see a need for this to be a `progress-*` icon. Is this supposed to represent progress settings? If that's the case it doesn't follow MD guidelines for `settings`.

**Comment by Templarian** [comment]
I viewed it as repair progress and added it. 😃
