### ISSUE TITLE
Rename Security Icons to Shield-*

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#3654]
- [x] `verified` to `shield-check`
- [x] `security-account` to `shield-account`
- [x] `security-account-outline` to `shield-account-outline`
- [x] `security-close` to `shield-remove` (uhh... oops)
- [x] `security-home` to `home-shield`
- [x] `security-lock` to `shield-lock`
- [x] `security-off` to `shield-off`

Need to add:

- ~~`shield-off-outline`~~ See #3693.

**Comment by Templarian** [comment]
Updated your comment with several more.

**Comment by PeterShaggyNoble** [comment]
If `shield` is then base icon then `plane-shield` should probably be renamed `shield-plane`, too.

And some others we need to consider:
- `security`
- `security-network`
- `server-security`

**Comment by PeterShaggyNoble** [comment]
Oh, and shouldn't `shield-close` be `shield-remove`?

**Comment by JamesCoyle** [comment]
^ Yup

**Comment by goyney** [comment]
@PeterShaggyNoble I think I'd vote for `security, `security-network`, and `server-security` to remain since they use the _security_-variant of the shield.

@JamesCoyle `shield-outline` added in #3693.

**Comment by Templarian** [comment]
Agreed. Checkboard should all be left `security`.
