### ISSUE TITLE
Idea: account-location base icon style

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3655]
Thinking we should 

- [ ] convert the `account-location` into a root icon style
- or
- [ ] Restyle it into the `tooltip` format.

**Comment by MrGrigri** [comment]
I would change it to `tooltip-account`.

**Comment by PeterShaggyNoble** [comment]
To throw a potential spanner in the works, Google have a circle variant of this:

[![location_history](http://mdi.houseofdesign.ie/tools/preview/?icon=location-history&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by Templarian** [comment]
I like it, but I want to say that the bottom point isn't large enough, it needs to be `1dp` lower and wider.

What do you think @PeterShaggyNoble?

**Comment by Templarian** [comment]
Renamed `account-location` and modified to `tooltip-account`.
