### ISSUE TITLE
Bus Seat Icon 

### ISSUE THREAD

**Issue by fa16mscs0004** [Templarian/MaterialDesign#3657]
I need this kind of icon
![629421-2004534 green](https://user-images.githubusercontent.com/36853351/47413352-806d3e80-d787-11e8-966d-04197d8930d9.png)

**Comment by MrGrigri** [comment]
Would the stock Google [icon](https://material.io/tools/icons/?search=event&icon=event_seat&style=baseline) `event_seat` work?

![image](https://user-images.githubusercontent.com/4528551/47446177-e782f700-d777-11e8-8613-00e241a6f31f.png)

**Comment by Templarian** [comment]
[![seat](https://materialdesignicons.com/icon/seat)](https://materialdesignicons.com/icon/seat) [![seat-outline](https://materialdesignicons.com/icon/seat-outline)](https://materialdesignicons.com/icon/seat-outline)
