### ISSUE TITLE
Drag Corner Icon

### ISSUE THREAD

**Issue by solomojo** [Templarian/MaterialDesign#3658]
Here's an icon to go along with the drag icons.  This one is intended for dragging the corner of a box to resize it. 

[![drag-corner.zip](http://mdi.houseofdesign.ie/tools/preview/?path=M7,19v-2h2v2H7%20M11,19v-2h2v2H11%20M15,19v-2h2v2H15%20M11,15v-2h2v2H11%20M15,15v-2h2v2H15%20M15,11V9h2v2H15&name=drag-corner&action=download)](https://github.com/Templarian/MaterialDesign/files/2515937/drag-corner.zip)

**Comment by PeterShaggyNoble** [comment]
Would it better represent a corner if it was moved to the bottom right corner of the 20*20 canvas?

**Comment by MrGrigri** [comment]
We already have that icon; it's called `resize-bottom-right`.

![resize-bottom-right](https://materialdesignicons.com/icon/resize-bottom-right)

**Comment by MrGrigri** [comment]
We need to add the alias `drag` to that icon.

- [ ] add alias.
