### ISSUE TITLE
Rooms Icon

### ISSUE THREAD

**Issue by comealivedev** [Templarian/MaterialDesign#3659]
Amount of rooms in an establishment. i.e Hotel Rooms

**Comment by PeterShaggyNoble** [comment]
The `hotel` icon is generally used to represent a hotel room. If that doesn't suit your needs then please provide an example of what you're looking for,

[![hotel](http://mdi.houseofdesign.ie/tools/preview/?icon=hotel&action=link)](https://materialdesignicons.com/icon/hotel)

**Comment by Templarian** [comment]
Closing as no additional information was given. Please reopen with more info or description for this request.
