### ISSUE TITLE
cool icon Time

### ISSUE THREAD

**Issue by LEONeso** [Templarian/MaterialDesign#366]
Demo: http://prntscr.com/77moxy

**Comment by Templarian** [comment]
Which icon is the one you are referring to in that picture?

**Comment by LEONeso** [comment]
http://prntscr.com/77psqd

**Comment by Templarian** [comment]
Please link me to the license file that these icons fall under and I'll see if they can be added. If not please reach out to the creator and see if they would like to become a contributor.

**Comment by LEONeso** [comment]
http://www.andreaswikstrom.com/work/time/

**Comment by Templarian** [comment]
The license is `NoDerivatives`. Please contact them and reference this issue if you would like them to become a contributor.

Closing the issue for now.
