### ISSUE TITLE
Bathrooms Icon

### ISSUE THREAD

**Issue by comealivedev** [Templarian/MaterialDesign#3660]
Bathroom icon. For example, "Amount of bathrooms" in real estate or "Bathrooms Available" at an event?

**Comment by PeterShaggyNoble** [comment]
One (or more) of `toilet`, `shower` or `human-male-female` should be suitable here. If not then please provide an example of what you're looking for.

**Comment by goyney** [comment]
Closing this issue because we have several icons already that indicate a bathroom. If you have another idea or suggestion for alternative ways a bathroom can be represented, please feel free to comment and reopen.
