### ISSUE TITLE
Diameter

### ISSUE THREAD

**Issue by jacobq** [Templarian/MaterialDesign#3661]
I would like to be able to express the concept of [circular or spherical size](https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.sew4home.com%2Fsites%2Fdefault%2Ffiles%2F1693-Circle-Parts.png&f=1), i.e. radius or diameter. I'm toying with using `mdi-google-circles`, `mdi-null`, `mdi-arrow-expand` or `mdi-arrow-expand-horizontal` in the mean time, but I think that might be confusing.

A more clear icon might have a circle with double-ended arrow inside or outside (possibly with leader lines)
![example from iconfinder](https://user-images.githubusercontent.com/1633459/47663434-0237e000-db6b-11e8-8d25-1855df267e83.png)
Another possibility would be to show circles of different sizes, e.g. 
![image](https://user-images.githubusercontent.com/1633459/47664103-58f1e980-db6c-11e8-95d4-ad839908a8ba.png)
I'm not sure how to express this neatly in a "material design way", but I hope someone would be willing to take a go at it.

In engineering drawings this is often called out like this:
![example of callout in engineering drawing](https://user-images.githubusercontent.com/1633459/47663680-7c686480-db6b-11e8-9498-1574db51e6f3.png)
![radius](https://user-images.githubusercontent.com/1633459/47663973-14fee480-db6c-11e8-807d-6371d8c4c576.png)

**Comment by PeterShaggyNoble** [comment]
Given the context would the `circle` or `circle-outline` icons not communicate this?

**Comment by jacobq** [comment]
@PeterShaggyNoble Thanks for the suggestions, but no, I don't think those are good candidates in this case. While they are circular, there is nothing about them that indicates which property is of interest either by variation (e.g. different sizes) or indication (e.g. arrow across diameter). Plus this is in the context of a form, which makes them too easily confused with option/radio buttons or bullets/decoration.

**Comment by MrGrigri** [comment]
I believe a simple outlined circle with a slash (which is the official drafting symbol) would suffice. 

![image](https://user-images.githubusercontent.com/4528551/48006427-a7eed000-e0d2-11e8-8ae7-f2911c05335a.png)

[diameter.zip](https://github.com/Templarian/MaterialDesign/files/2548972/diameter.zip)

**Comment by jacobq** [comment]
@MrGrigri Well, that's why I am using [`mdi-null`](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/null.svg) for now. It is very similar. It just has the unfortunate side-effect of looking like a ["no symbol"](https://en.wikipedia.org/wiki/No_symbol) and, of course, null / empty set.

**Comment by MrGrigri** [comment]
`null` is not a circle, and this one is.

**Comment by Templarian** [comment]
I can add this one, but I think we should have a more representation of it also. Same for `radius`.

**Comment by MrGrigri** [comment]
Ok, so what about these?

![image](https://user-images.githubusercontent.com/4528551/48008910-d28f5780-e0d7-11e8-92ac-9124af34cf83.png) ![image](https://user-images.githubusercontent.com/4528551/48008949-eaff7200-e0d7-11e8-8404-5e6fcd7f4458.png) ![image](https://user-images.githubusercontent.com/4528551/48008996-09fe0400-e0d8-11e8-9e42-373cfc3b502b.png)

[diameter.zip](https://github.com/Templarian/MaterialDesign/files/2549423/diameter.zip)

**Comment by Templarian** [comment]
Exactly! I'll get these added tonight.

**Comment by MrGrigri** [comment]
Ok, one more time. I forgot that we're trying to do outlined variants.

![image](https://user-images.githubusercontent.com/4528551/48009345-cc4dab00-e0d8-11e8-9e73-fa6263eea1d7.png) ![image](https://user-images.githubusercontent.com/4528551/48009381-dd96b780-e0d8-11e8-8e6c-85cc0a685b68.png) ![image](https://user-images.githubusercontent.com/4528551/48009423-f010f100-e0d8-11e8-99a3-14b2c314df2d.png) ![image](https://user-images.githubusercontent.com/4528551/48009450-fc954980-e0d8-11e8-8552-379d3f3abb7d.png) ![image](https://user-images.githubusercontent.com/4528551/48009487-0fa81980-e0d9-11e8-92fd-101dc06204b8.png)

[diameter.zip](https://github.com/Templarian/MaterialDesign/files/2549442/diameter.zip)

**Comment by jacobq** [comment]
@MrGrigri thanks for all of your effort! `diameter-outline` looks exactly like what I'd like to use. My only point of feedback with these is that `radius` looks somewhat like a clock. I am not sure how one would go about remedying that though.

**Comment by MrGrigri** [comment]
I don't because our `clock` has two hands. I could be confused with the `timer` icon though. However, context plays a huge role.

**Comment by Templarian** [comment]
Added all 5. 😺 

The will be in the `3.1.xx` release.
