### ISSUE TITLE
Go lang

### ISSUE THREAD

**Issue by praneetloke** [Templarian/MaterialDesign#3662]
I have looked through the existing issues and couldn't find a request for Google's Go lang.

[Here's](https://blog.golang.org/go-brand) a link to the glang's brand. And here's a preview of the logo from their page.

![logos](https://user-images.githubusercontent.com/1466314/47668785-9a7f9600-db66-11e8-8525-22108b4d8483.jpg)

**Comment by Templarian** [comment]
This already exists. It's called. `language-go`. 😶
