### ISSUE TITLE
the Israeli new Shekel  the ILS currency symbol ₪ 

### ISSUE THREAD

**Issue by dannizi25** [Templarian/MaterialDesign#3663]
the Israeli new Shekel  the ILS currency symbol
 ₪

**Comment by ofekashery** [comment]
Yes!!

**Comment by MrGrigri** [comment]
Better picture:

![shekel](https://user-images.githubusercontent.com/4528551/47746899-bbbab200-dc4c-11e8-8250-7bb6f666d64b.png)

**Comment by Templarian** [comment]
Oops, I must have never submitted that comment yesterday closing this issue. Yep, was added yesterday. 😄

**Comment by dannizi25** [comment]
in what ver of CDN ?

**Comment by goyney** [comment]
@dannizi25 It'll be available the next time we release, which will be the 3.1.x version.
