### ISSUE TITLE
Airballoon Outline

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3664]

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48974876-89755800-f032-11e8-91c8-99b7d45890bb.png)

[airballoon-outline.zip](https://github.com/Templarian/MaterialDesign/files/2612781/airballoon-outline.zip)

**Comment by PeterShaggyNoble** [comment]
Will also need to be aliased as `hot-air-balloon-outline`.

**Comment by goyney** [comment]
[![airballoon-outline](https://materialdesignicons.com/icon/airballoon-outline)](https://materialdesignicons.com/icon/airballoon-outline)
