### ISSUE TITLE
FIRST icon

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3665]
![image](https://user-images.githubusercontent.com/16443111/47698790-60230100-dc19-11e8-9a65-67c683358f0d.png)

[first-brand-separate-elements-all-formats.zip](https://www.firstinspires.org/sites/default/files/uploads/resource_library/brand/first-brand-separate-elements-artwork-files.zip), use the `FIRSTicon_OneColorTM.eps`

Brand Center: https://www.firstinspires.org/brand
Brand Guidelines: https://www.firstinspires.org/sites/default/files/uploads/resource_library/first-brand-guidelines-web-2015.pdf

(_FIRST_ is a non-profit organization that encourages children and teenagers to engage in science and technology)

**Comment by PeterShaggyNoble** [comment]
Sorry, but this is too niche and too detailed for us to add at this time.

**Comment by ofekashery** [comment]
Why? I'm sure it will have many uses.
Has all the necessary files

**Comment by JamesCoyle** [comment]
Only a handful of MDI users would actually use this and there is far too much detail to fit into a 24x24 pixel icon. We generally only accept brand icons from major social networks and other social tools which you can create profiles for.

**Comment by PeterShaggyNoble** [comment]
For brand icons beyond the scope of this project, try [Simple Icons](https://simpleicons.org/). Their 24*24 SVG icons should work well in conjunction with our library.
