### ISSUE TITLE
currency-usd with circle outline around it

### ISSUE THREAD

**Issue by stevegula** [Templarian/MaterialDesign#3667]
like check-circle-outline

**Comment by PeterShaggyNoble** [comment]
This exists already as `coin`. I'll alias it as `currency-usd-circle-outline` shortly.

[![coin](http://mdi.houseofdesign.ie/tools/preview/?icon=coin&action=link)](https://materialdesignicons.com/icon/coin)

**Comment by PeterShaggyNoble** [comment]
Alias added.
