### ISSUE TITLE
Vibrate Off

### ISSUE THREAD

**Issue by FANMixco** [Templarian/MaterialDesign#3668]
I designed this icon for my own purposes and consider can be used for other people too.

![picture1 2](https://user-images.githubusercontent.com/1666156/47840816-cf365c00-ddb7-11e8-968f-564a135ba38c.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/47882864-7f27bb80-ddf0-11e8-9dcc-7b9abe2ed606.png) ![image](https://user-images.githubusercontent.com/4528551/47882871-8cdd4100-ddf0-11e8-8063-801fa76ed333.png)

[vibrate-off.zip](https://github.com/Templarian/MaterialDesign/files/2540287/vibrate-off.zip)
