### ISSUE TITLE
How to modify the size of icon in angular material ？

### ISSUE THREAD

**Issue by Tian-Hun** [Templarian/MaterialDesign#3669]

**Comment by Templarian** [comment]
@Tian-Hun I'm not familiar with Angular Material, but it looks like the docs say to use CSS at the bottom of the Angular Material section (someone else wrote that doc). We accept PR's for any documentation to help improve it.

http://dev.materialdesignicons.com/getting-started/angular

Closing this question as that should answer the question. 😃
