### ISSUE TITLE
Visa, MasterCard, Amex and other major credit card icons

### ISSUE THREAD

**Issue by ajensenpyp** [Templarian/MaterialDesign#367]
Could you please add the major credit card icons

**Comment by Templarian** [comment]
These have too much detail to be included nicely into the pack while respecting the guidelines.

**Comment by Templarian** [comment]
As a work around I would suggest using vectors from a outside icon pack. :smile:

**Comment by cvsguimaraes** [comment]
This was [rejected on font-awesome](https://github.com/FortAwesome/Font-Awesome/issues/1009) as well.
You can use [this icons](http://www.rb.cm/brandfont/) and pack them together using [icomoon](https://icomoon.io/).

**Comment by ajensenpyp** [comment]
FontAwsome has all the payment icons.
http://fortawesome.github.io/Font-Awesome/icons/






*ANDREW JENSEN*
Front End Developer / UX Designer

Office: (385) 275-0480 <3852750480> ext. 235
Cell: (702) 588-9339 <7025889339>
ajensen@pickyourplum.com
www.pickyourplum.com

**Comment by Templarian** [comment]
@ajensenpyp Yep, Dave backtracked on it shortly after it getting rejected I believe. This will not be the case. :smile:

(looks like @cvsguimaraes edited their original message to correct this oversight, but you saw it from the email)

**Comment by ajensenpyp** [comment]
sorry about that.  Thanks




*ANDREW JENSEN*
Front End Developer / UX Designer

Office: (385) 275-0480 <3852750480> ext. 235
Cell: (702) 588-9339 <7025889339>
ajensen@pickyourplum.com
www.pickyourplum.com
