### ISSUE TITLE
Maple Leaf / Autumn

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3671]
please consider the 4 seasons Spring, Summer, Fall, Winter?

couldn't find a previous search, which surprised me tbh...
Sorry if I overlooked anything ?

**Comment by PeterShaggyNoble** [comment]
Some of the usual icons used to represent the seasons include `flower` for Spring, `weather-sunny` for Summer, `leaf` for Autumn and `snowflake` for Winter. If you have any other suggestions please let us know, with examples if possible.

**Comment by MrGrigri** [comment]
Yeah, I believe all of these would suffice for representing the seasons. All though, I believe a maple or oak leave would be better for fall.

**Comment by MrGrigri** [comment]
Something like this maybe.

![image](https://user-images.githubusercontent.com/4528551/48007707-70cdee00-e0d5-11e8-8a8c-a499d22b0c9b.png)

[Asset 6.zip](https://github.com/Templarian/MaterialDesign/files/2549335/Asset.6.zip)

**Comment by Mariusthvdb** [comment]
I had not realized that, and think you are right suggesting the icons you do. Thank you.
One suggestion left if I may, a leaf upside down would indicate falling leaves for fall. If that could be the maple leaf, so  much the better.

**Comment by Templarian** [comment]
[![leaf-maple](https://materialdesignicons.com/icon/leaf-maple)](https://materialdesignicons.com/icon/leaf-maple)

Canadian's will like that one. A "fall leaf" not sure for that one, will leave this open.

**Comment by Templarian** [comment]
Probably need 1 for an oak tree. Although maple works too.

**Comment by MrGrigri** [comment]
Yeah, I thought about doing an oak one as well. Idk if it would be recognizable at 1x as much as the maple leaf. That's why I went with maple instead.

**Comment by PeterShaggyNoble** [comment]
Closing here as the original request has been fulfilled.
