### ISSUE TITLE
map-marker-check

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3673]
One of Google's that was found today.

![image](https://user-images.githubusercontent.com/4528551/48005637-29456300-e0d1-11e8-995e-66317e09e158.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/48005696-5265f380-e0d1-11e8-99a0-3bc0ab69e2ef.png)

```M12 2c3.86 0 7 3.14 7 7 0 5.25-7 13-7 13S5 14.25 5 9c0-3.86 3.14-7 7-7zm-1.53 12L17 7.41 15.6 6l-5.13 5.18L8.4 9.09 7 10.5l3.47 3.5z```

**Comment by PeterShaggyNoble** [comment]
Google call this `where_to_vote` - pretty sure it's come up before.

**Comment by MrGrigri** [comment]
[map-marker-check.zip](https://github.com/Templarian/MaterialDesign/files/2548976/map-marker-check.zip)

**Comment by MrGrigri** [comment]
Yes... #316

**Comment by Templarian** [comment]
[![map-marker-outline](https://materialdesignicons.com/icon/map-marker-check)](https://materialdesignicons.com/icon/map-marker-check)
