### ISSUE TITLE
Many, many aliases to add!

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3674]
I felt the need for another aliasing spree! Leaving these here for myself until the aliasing form is fixed.

## map-marker-check
- [x] map-marker-tick
- [x] where-to-vote

## charity
- [x] super-chat-for-good

## calendar-remove
- [x] event-remove

## calendar-remove-outline
- [x] event-busy-outline
- [x] event-remove-outline

## calendar-check-outline
- [x] event-available-outline
- [x] event-check-outline
- [x] event-tick-outline
- [x] calendar-task-outline
- [x] calendar-tick-outline

## seat
- [x] event-seat
- [x] chair

## seat-outline
- [x] event-seat-outline
- [x] chair-outline

## playlist-music
- [x] playlist-note
- [x] queue-music

## playlist-music-outline
- [x] playlist-note-outline
- [x] queue-music-outline

## account-multiple-minus-outline
- [x] accounts-minus-outline
- [x] people-minus-outline
- [x] user-multiple-minus-outline
- [x] users-minus-outline
- [x] person-multiple-minus-outline

## account-off-outline
- [x] user-off-outline
- [x] person-off-outline

## battery-plus
- [x] battery-add

## bell-plus-outline
- [x] bell-add-outline

## book-multiple-plus
- [x] book-multiple-add
- [x] books-add

## book-plus
- [x] book-add

## bookmark-plus
- [x] bookmark-add

## bookmark-plus-outline
- [x] bookmark-add-outline

## briefcase-plus
- [x] briefcase-add

## calendar-plus
- [x] calendar-add
- [x] event-add

## clipboard-plus
- [x] clipboard-add

## comment-plus
- [x] comment-add

## comment-plus-outline
- [x] comment-add-outline

## credit-card-plus
- [x] credit-card-add

## database-plus
- [x] database-add

## email-plus
- [x] email-add
- [x] envelope-add

## email-plus-outline
- [x] email-add-outline
- [x] envelope-add-outline

## eye-plus
- [x] eye-add

## eye-plus-outline
- [x] eye-add-outline

## flag-plus
- [x] flag-add

## folder-plus
- [x] folder-add

## folder-plus-outline
- [x] folder-add-outline

## format-annotation-plus
- [x] format-annotation-add

## home-plus
- [x] home-add

## image-plus
- [x] image-add

## key-plus
- [x] key-add

## lock-plus
- [x] lock-add

## magnify-plus
- [x] magnify-add

## magnify-plus-cursor
- [x] magnify-add-cursor

## magnify-plus-outline
- [x] magnify-add-outline

## map-plus
- [x] map-add

## message-plus
- [x] message-add

## microphone-plus
- [x] microphone-add

## note-plus
- [x] note-add

## note-plus-outline
- [x] note-add-outline

## server-plus
- [x] server-add

## shape-circle-plus
- [x] shape-circle-add

## shape-plus
- [x] shape-add

## shape-polygon-plus
- [x] shape-polygon-add

## shape-rectangle-plus
- [x] shape-rectangle-add

## shape-square-plus
- [x] shape-square-add

## shield-plus
- [x] shield-add

## shield-plus-outline
- [x] shield-add-outline

## tab-plus
- [x] tab-add

## table-column-plus-after
- [x] table-column-add-after

## table-column-plus-before
- [x] table-column-add-before

## table-plus
- [x] table-add

## table-row-plus-after
- [x] table-row-add-after

## table-row-plus-before
- [x] table-row-add-before

## tag-plus
- [x] tag-add

## tooltip-plus
- [x] tooltip-add

## tooltip-plus-outline
- [x] tooltip-add-outline

## video-plus
- [x] video-add

## volume-minus
- [x] volume-decrease

## volume-plus
- [x] volume-increase

## account-alert
- [x] person-alert
- [x] person-warning

## account-alert-outline
- [x] user-warning-outline
- [x] person-warning-outline
- [x] person-alert-outline

## account-arrow-left
- [x] person-arrow-left

## account-arrow-left-outline
- [x] person-arrow-left-outline

## account-arrow-right
- [x] person-arrow-right

## account-arrow-right-outline
- [x] person-arrow-right-outline

## account-box
- [x] person-box

## account-box-multiple
- [x] person-box-multiple
- [x] person-boxes

## account-box-outline
- [x] person-box-outline

## account-card-details
- [x] person-card-details
- [x] id-card

## account-check
- [x] person-check
- [x] person-tick
- [x] how-to-reg

## account-check-outline
- [x] account-tick-outline
- [x] user-check-outline
- [x] user-tick-outline
- [x] person-check-outline
- [x] person-tick-outline
- [x] how-to-reg-outline

## account-child
- [x] person-child

## account-child-circle
- [x] person-child-circle

## account-circle
- [x] person-circle

## account-circle-outline
- [x] person-circle-outline

## account-clock
- [x] person-clock

## account-clock-outline
- [x] person-clock-outline

## account-convert
- [x] person-convert

## account-details
- [x] person-details

## account-edit
- [x] person-edit

## account-group
- [x] users-group
- [x] person-group
- [x] people-group

## account-group-outline
- [x] users-group-outline
- [x] person-group-outline
- [x] people-group-outline

## account-heart
- [x] person-heart

## account-key
- [x] person-key

## account-location
- [x] person-location
- [x] person-address

## account-minus
- [x] person-minus

## account-minus-outline
- [x] person-minus-outline

## account-multiple
- [x] person-multiple

## account-multiple-check
- [x] person-multiple-check
- [x] person-multiple-tick
- [x] people-check
- [x] people-tick

## account-multiple-minus
- [x] person-multiple-minus
- [x] people-minus

## account-multiple-plus
- [x] person-multiple-plus
- [x] people-plus
- [x] person-multiple-add
- [x] people-add
- [x] account-multiple-add
- [x] accounts-add
- [x] user-multiple-add
- [x] users-add

## account-multiple-plus-outline
- [x] person-multiple-plus-outline
- [x] people-plus-outline
- [x] person-multiple-add-outline
- [x] people-add-outline
- [x] account-multiple-add-outline
- [x] accounts-add-outline
- [x] user-multiple-add-outline
- [x] users-add-outline

## account-network
- [x] person-network

## account-off
- [x] person-off

## account-plus
- [x] account-add
- [x] person-plus
- [x] user-add

## account-plus-outline
- [x] account-add-outline
- [x] person-plus-outline
- [x] user-add-outline

## account-question
- [x] person-question
- [x] person-help

## account-question-outline
- [x] person-question-outline
- [x] person-help-outline

## account-remove
- [x] person-remove

## account-remove-outline
- [x] person-remove-outline

## account-search
- [x] person-search

## account-search-outline
- [x] person-search-outline

## account-settings
- [x] person-settings

## account-star
- [x] person-star

## account-supervisor
- [x] person-supervisor

## account-supervisor-circle
- [x] person-supervisor-circle

## account-switch
- [x] person-switch
- [x] people-switch

## airplane
- [x] flight-mode
- [x] plane

## airplane-off
- [x] flight-mode-off
- [x] plane-off

## airplane-landing
- [x] plane-landing

## airplane-takeoff
- [x] airplane-take-off
- [x] plane-takeoff

## airplay
- [x] apple

## alarm
- [x] alarm-clock

## alarm-check
- [x] alarm-clock-check
- [x] alarm-clock-tick

## alarm-multiple
- [x] alarm-clock-multiple
- [x] alarm-clocks

## alarm-off
- [x] alarm-clock-off

## alarm-plus
- [x] alarm-clock-plus
- [x] alarm-clock-add

## alarm-snooze
- [x] alarm-clock-snooze

## arrow-bottom-left
- [x] arrow-down-left

## arrow-bottom-left-bold-outline
- [x] arrow-down-left-bold-outline

## arrow-bottom-left-thick
- [x] arrow-down-left-thick

## arrow-bottom-right
- [x] arrow-down-right

## arrow-bottom-right-bold-outline
- [x] arrow-down-right-bold-outline

## arrow-bottom-right-thick
- [x] arrow-down-right-thick

## arrow-down
- [x] arrow-bottom

## arrow-down-bold
- [x] arrow-bottom-bold

## arrow-down-bold-box
- [x] arrow-bottom-bold-box

## arrow-down-bold-box-outline
- [x] arrow-bottom-bold-box-outline

## arrow-down-bold-circle
- [x] arrow-bottom-bold-circle

## arrow-down-bold-circle-outline
- [x] arrow-bottom-bold-circle-outline

## arrow-down-bold-hexagon-outline
- [x] arrow-bottom-bold-hexagon-outline

## arrow-down-bold-outline
- [x] arrow-bottom-bold-outline

## arrow-down-box
- [x] arrow-bottom-box

## arrow-down-drop-circle
- [x] arrow-bottom-drop-circle

## arrow-down-drop-circle-outline
- [x] arrow-bottom-drop-circle-outline

## arrow-down-thick
- [x] arrow-bottom-thick

## arrow-top
- [x] arrow-up

## arrow-top-bold
- [x] arrow-up-bold

## arrow-top-bold-box
- [x] arrow-up-bold-box

## arrow-top-bold-box-outline
- [x] arrow-up-bold-box-outline

## arrow-top-bold-circle
- [x] arrow-up-bold-circle

## arrow-top-bold-circle-outline
- [x] arrow-up-bold-circle-outline

## arrow-top-bold-hexagon-outline
- [x] arrow-up-bold-hexagon-outline

## arrow-top-bold-outline
- [x] arrow-up-bold-outline

## arrow-top-box
- [x] arrow-up-box

## arrow-top-drop-circle
- [x] arrow-up-drop-circle

## arrow-top-drop-circle-outline
- [x] arrow-up-drop-circle-outline

## arrow-top-thick
- [x] arrow-up-thick

## walk
- [x] walker
- [x] walking

## wall
- [x] bricks

## xbox
- [x] microsoft

## diameter
- [x] circle-diameter
- [x] sphere-diameter

## diameter-outline
- [x] circle-diameter-outline
- [x] sphere-diameter-outline

## diameter-variant
- [x] circle-diameter-variant
- [x] sphere-diameter-variant

## radius
- [x] circle-radius
- [x] sphere-radius

## radius-outline
- [x] circle-radius-outline
- [x] sphere-radius-outline

## progress-alert
- [x] progress-warning

**Comment by JamesCoyle** [comment]
Should probably have a tool to highlight any missing aliases for common patterns such as the plus -> add icons
