### ISSUE TITLE
Update account-multiple(-*)-outline

### ISSUE THREAD

**Issue by henriquecm** [Templarian/MaterialDesign#3675]
I remade the mdi-account-multiple-outline based on the version of the new MDI icons.

[mdi-account-multiple-outline.zip](https://github.com/Templarian/MaterialDesign/files/2550196/mdi-account-multiple-outline.zip)
![mdi-account-multiple-outline-01](https://user-images.githubusercontent.com/15136037/48020847-13aa5a80-e11e-11e8-92cf-d45d19ed0ffd.png)

**Comment by PeterShaggyNoble** [comment]
Here's Google's version:

[![group](https://user-images.githubusercontent.com/15157491/48127334-5d5c8780-e27b-11e8-8fcb-b8916c6e1a88.png)](https://material.io/tools/icons/?search=group&icon=group&style=outline)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53063459-2e68cb00-3492-11e9-838d-7762f3e819b2.png)
Our current is the outline.

[account-multiple-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2882853/account-multiple-outline.svg.zip)

**Comment by Templarian** [comment]
Yeah, we'll need to tweak this...

![untitled41](https://user-images.githubusercontent.com/338885/53065509-8bb04c80-3491-11e9-911d-63317fbd6980.png)

**Comment by Templarian** [comment]
Forgot to get this into the release, top priority so I can get this out for `3.6.xx`.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53705667-22ff9300-3df4-11e9-8028-486bec10bee8.png)
(Our current is the outline.)

---

And the two variants we have of this style:

![image](https://user-images.githubusercontent.com/1015040/53705699-56422200-3df4-11e9-8ef7-995d3ed32a69.png)![image](https://user-images.githubusercontent.com/1015040/53705702-5cd09980-3df4-11e9-91c1-17b6b24de029.png)

[account-multiple-outline.zip](https://github.com/Templarian/MaterialDesign/files/2924007/account-multiple-outline.zip)

**Comment by Templarian** [comment]
Updated and reassigned to Google. Thanks! 😃
