### ISSUE TITLE
Site performance

### ISSUE THREAD

**Issue by inlinecoder** [Templarian/MaterialDesign#3676]
Yo peeps,

I was wondering if I'm the only one who has performance issues (e.g. typing in inputs, scrolling, hovering, etc..) with the site itself in Safari? In Chrome it works better.

**Comment by Templarian** [comment]
@inlinecoder Known issue unfortunately. The current site was never really made with the idea we would have 3000+ icons. No updates are being made to the legacy site as it's really beyond repair.

https://github.com/Templarian/MaterialDesign-Site New site is here.

https://dev.materialdesignicons.com/ Uses a lot more aggressive cache, but is still a work in progress for the team.
