### ISSUE TITLE
Word, Excel, Powerpoint product icons

### ISSUE THREAD

**Issue by GuiCavi** [Templarian/MaterialDesign#368]
What about some of these icons?
![guilherme 21_05_15 14 58 05](https://cloud.githubusercontent.com/assets/7794819/7755403/24a2f4ca-ffca-11e4-90df-285ff0b5b522.png)
- [ ] office-excel
- [ ] office-word
- [ ] office-powerpoint
- [x] office-onenote
- [x] office-outlook

**Comment by GreenTurtwig** [comment]
All but OneNote and Outlook have 2 variations of icons now.

**Comment by Templarian** [comment]
[![onenote](https://materialdesignicons.com/icon/onenote)](https://materialdesignicons.com/icon/onenote)

For the OneNote icon it's probably best represented in the style above.

**Comment by PeterShaggyNoble** [comment]
Closing here as all have been added, bar Outlook which has its own issue in #730.

**Comment by CoDEmanX** [comment]
How about icons following the onenote design?

**Comment by PeterShaggyNoble** [comment]
Reopening so we can add the remaining _product_ icons.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
