### ISSUE TITLE
clipboard-play

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3681]
I'm using this in an application to symbolize 'running a report'. 

![image](https://user-images.githubusercontent.com/4528551/48098159-1ae26e80-e1d9-11e8-97b2-941640611747.png) ![image](https://user-images.githubusercontent.com/4528551/48098175-2766c700-e1d9-11e8-8deb-acad6f117eb9.png)

[clipboard-play.zip](https://github.com/Templarian/MaterialDesign/files/2555259/clipboard-play.zip)

**Comment by JamesCoyle** [comment]
Shouldn't the play icon be inside the clipboard like all the other clipboard icons?

**Comment by MrGrigri** [comment]
I wanted there to be text, so I guess they should have the `*-text-*` modifiers.

**Comment by Templarian** [comment]
Yea, it would be `clipboard-text-play` I guess.

Deep rabbit hole. 😅

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/48098617-909b0a00-e1da-11e8-8809-e4d270c9f1a5.png) ![image](https://user-images.githubusercontent.com/4528551/48098633-9a247200-e1da-11e8-9016-27b8549ed258.png) ![image](https://user-images.githubusercontent.com/4528551/48098659-a7d9f780-e1da-11e8-9754-65f7c2b7925f.png) ![image](https://user-images.githubusercontent.com/4528551/48098689-b32d2300-e1da-11e8-8b38-df23a5d15577.png)

[clipboard-play.zip](https://github.com/Templarian/MaterialDesign/files/2555316/clipboard-play.zip)

**Comment by JamesCoyle** [comment]
Why is the triangle in the non-text ones stretched?

**Comment by MrGrigri** [comment]
I took the play button from the `play-network`. Another inconsistency between all of the play icons.

**Comment by JamesCoyle** [comment]
Should we add this to our list of things to fix? Really should be closest grid points to equilateral as possible.

**Comment by Templarian** [comment]
Added, but all the clipboards in the pack are `1dp` higher. Eventually we may want to look into why that is and adjust them all at once.
