### ISSUE TITLE
folder-text

### ISSUE THREAD

**Issue by pille0071** [Templarian/MaterialDesign#3683]

**Comment by pille0071** [comment]
![folder-document](https://user-images.githubusercontent.com/16647268/48259769-55d2e500-e419-11e8-8420-77175452baee.png)

**Comment by pille0071** [comment]
[folder-document.zip](https://github.com/Templarian/MaterialDesign/files/2565624/folder-document.zip)

**Comment by JamesCoyle** [comment]
This would probably have to be the folder icon with the text from the document icon.

**Comment by MrGrigri** [comment]
I could see this being used as folder having content type scenario. 

![image](https://user-images.githubusercontent.com/4528551/48273688-c02a5c00-e3fe-11e8-9a23-f84aef19c11d.png) ![image](https://user-images.githubusercontent.com/4528551/48273701-cae4f100-e3fe-11e8-922b-5d8ef1137186.png)

[folder-text.zip](https://github.com/Templarian/MaterialDesign/files/2566568/folder-text.zip)

**Comment by Templarian** [comment]
Added. 😃
