### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3684]
This was made to represent an iframe, so that's what I'm calling it. 

![image](https://user-images.githubusercontent.com/4528551/48279426-cb38b880-e40d-11e8-9e60-dd064901df75.png) ![image](https://user-images.githubusercontent.com/4528551/48279441-d855a780-e40d-11e8-9060-c7260566ba7c.png)

[iframe.zip](https://github.com/Templarian/MaterialDesign/files/2566971/iframe.zip)

**Comment by Templarian** [comment]
Added! 😃
