### ISSUE TITLE
ballot-recount

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3685]
In true Floridian fashion, I present...
![image](https://user-images.githubusercontent.com/1015040/48296645-63af5700-e467-11e8-8180-bc719eee3ea1.png) ![image](https://user-images.githubusercontent.com/1015040/48296646-6d38bf00-e467-11e8-9cdb-95cbaae0646e.png)

[ballot-recount.zip](https://github.com/Templarian/MaterialDesign/files/2568044/ballot-recount.zip)

**Comment by Templarian** [comment]
Added. 😃
