### ISSUE TITLE
oreo

### ISSUE THREAD

**Issue by Richienb** [Templarian/MaterialDesign#3686]

**Comment by goyney** [comment]
The logo? The cookie?

**Comment by Richienb** [comment]
The oreo cookie. Something like this:
![Image of an Oreo](https://www.gannett-cdn.com/-mm-/55594ff22d5e2125c915e4251a4019c612268760/c=0-1109-5100-3990/local/-/media/2017/05/09/USATODAY/USATODAY/636298910755831488-050917oreo-cookie.jpg)

**Comment by goyney** [comment]
After an internal discussion, we feel this is way too specific to add. I'd recommend using the `cookie` icon.

[![image](https://user-images.githubusercontent.com/1015040/48324387-7c05aa00-e5fe-11e8-8c96-2e2525391f96.png)](https://materialdesignicons.com/icon/cookie)
