### ISSUE TITLE
network-outline

### ISSUE THREAD

**Issue by donhurickerby** [Templarian/MaterialDesign#3687]
how about some outlined icons for "network", "minus-network" and "close-network"?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48322372-401a1700-e5f5-11e8-8372-a14ab0ad51bc.png)![image](https://user-images.githubusercontent.com/1015040/48322386-4a3c1580-e5f5-11e8-9fde-4c5ca0c6141d.png)
![image](https://user-images.githubusercontent.com/1015040/48322392-51fbba00-e5f5-11e8-94b9-7026c2ebb412.png)![image](https://user-images.githubusercontent.com/1015040/48322399-5d4ee580-e5f5-11e8-81de-c4a3e5499712.png)
![image](https://user-images.githubusercontent.com/1015040/48322406-6475f380-e5f5-11e8-8ce4-bd7dbf6d62a4.png)![image](https://user-images.githubusercontent.com/1015040/48322413-6e97f200-e5f5-11e8-8a0d-e27fc9914f30.png)
![image](https://user-images.githubusercontent.com/1015040/48322418-748dd300-e5f5-11e8-80ef-de80dc6a149e.png)![image](https://user-images.githubusercontent.com/1015040/48322424-7d7ea480-e5f5-11e8-82bd-a526382766cc.png)
![image](https://user-images.githubusercontent.com/1015040/48322427-84a5b280-e5f5-11e8-83bc-5ad831589d58.png)![image](https://user-images.githubusercontent.com/1015040/48322433-8cfded80-e5f5-11e8-87bf-f21c7012bbad.png)
![image](https://user-images.githubusercontent.com/1015040/48322447-95eebf00-e5f5-11e8-9639-4fbbb8fcadcf.png)![image](https://user-images.githubusercontent.com/1015040/48322450-9edf9080-e5f5-11e8-9ef7-10ece8ecb4e6.png)

[network-outline.zip](https://github.com/Templarian/MaterialDesign/files/2570231/network-outline.zip)

**Comment by Templarian** [comment]
All of these were added. Thanks for creating all of these @goyney!!!
