### ISSUE TITLE
Fix network icon alignments

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3688]
Several of the `network` related icons have varying alignments. I have updated all the misaligned ones and attached them here. The outlines are the current icons.

![image](https://user-images.githubusercontent.com/1015040/48322840-87090c00-e5f7-11e8-88a0-1671960f5df3.png)![image](https://user-images.githubusercontent.com/1015040/48322858-9daf6300-e5f7-11e8-8e5a-535a76d921af.png)
![image](https://user-images.githubusercontent.com/1015040/48322874-ac961580-e5f7-11e8-836e-27db4246c99d.png)![image](https://user-images.githubusercontent.com/1015040/48322887-b9b30480-e5f7-11e8-8090-4dbd9d570f86.png)
![image](https://user-images.githubusercontent.com/1015040/48322898-c6375d00-e5f7-11e8-9874-7463fac20e87.png)![image](https://user-images.githubusercontent.com/1015040/48322909-d2bbb580-e5f7-11e8-8f49-2a2a25372be9.png)
![image](https://user-images.githubusercontent.com/1015040/48322927-e0713b00-e5f7-11e8-87c5-7e2eb08854d8.png)![image](https://user-images.githubusercontent.com/1015040/48322945-f4b53800-e5f7-11e8-814b-45477911a955.png)
![image](https://user-images.githubusercontent.com/1015040/48322972-04cd1780-e5f8-11e8-8c03-657c83a57db1.png)

[updated-network.zip](https://github.com/Templarian/MaterialDesign/files/2570261/updated-network.zip)

**Comment by Templarian** [comment]
All of these have been updated. Thanks @goyney for listing them all.
