### ISSUE TITLE
Networking/hardware related icons

### ISSUE THREAD

**Issue by guifal** [Templarian/MaterialDesign#369]
I'd suggest to add a bunch of networking/hardware related icons.
These icons are a must for apps with high-tech features, but might also be useful for the "advanced settings" interface for apps of any kind.
- [x] 1. Access Point / Wireless
- [x] 2. IP telephone
- [ ] 3. ~~VMWare server~~ _(too specific)_
- [x] 4. ~~No break (UPS)~~ _(too specific, ask @CoDEmanX for his [UPS icons](https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-122517208) if you want)_
- [x] 5. Cable Ethernet connected / disconnected
- [x] 6. Certificate
- [x] 7. WAN
- [x] 8. LAN

| Number | Icon |
| --- | :-- |
| 1. | ![wirelessicon](https://cloud.githubusercontent.com/assets/10040003/7757568/cb10de4e-ffd9-11e4-8877-d0dcd86ebac4.jpg) |
| 2. | ![network-voip-gateway-icon](https://cloud.githubusercontent.com/assets/10040003/7756099/3caa0bee-ffcf-11e4-9abe-c52e201e8037.png) |
| 3. | ![ico-virtu](https://cloud.githubusercontent.com/assets/10040003/7757660/7fd7015a-ffda-11e4-9386-54df844ca710.png) |
| 4. | ![automatic_voltage_stabilizer_icon](https://cloud.githubusercontent.com/assets/10040003/7757234/39a1341a-ffd7-11e4-87f2-b30950ec5907.jpg) |
| 5. | ![pc2_go-36-512](https://cloud.githubusercontent.com/assets/10040003/7758102/633c6a28-ffdd-11e4-8e85-c9f45661c087.png) ![con_et](https://cloud.githubusercontent.com/assets/10040003/7758147/c76a31ec-ffdd-11e4-80c1-0a5b81efeb27.png) |
| 6. | ![certificate_seal-128](https://cloud.githubusercontent.com/assets/10040003/7756243/7fc47832-ffd0-11e4-9ae9-5c12e03c0450.png) |
| 7. | ![hosting_4-512](https://cloud.githubusercontent.com/assets/10040003/7758836/0552101a-ffe3-11e4-9c70-013b6e9a8ec0.png) |
| 8. | ![9-512](https://cloud.githubusercontent.com/assets/10040003/7758874/6a955cb6-ffe3-11e4-97b5-004f2c92200a.png) |

**Comment by cvsguimaraes** [comment]
:+1:

**Comment by felipestagio** [comment]
:+1

**Comment by felipestagio** [comment]
:+1:

**Comment by Templarian** [comment]
A few of these exist. `delete` and `console`. Do you have anther example for no-break? Not sure what that is.

**Comment by cvsguimaraes** [comment]
@Templarian the right term for "no-break" is UPS

https://www.google.com.br/search?q=ups&es_sm=93&tbas=0&tbm=isch&source=lnt&sa=X&ei=q651VfSPEIjnsASv84P4Cg&ved=0CBQQpwU&dpr=1&biw=900&bih=1485

**Comment by cvsguimaraes** [comment]
About the UPS again, something that relates the keywords "power" and "box" might work.
Here's a draft with that idea:
![untitled-1](https://cloud.githubusercontent.com/assets/1047033/8038121/053518b8-0dd8-11e5-8f3d-bf672b204262.png)

however it looks like a door or something, you better at semiotics than me anyway
so its your call 
:smile:

**Comment by CoDEmanX** [comment]
As for UPS, here are my experiments:
 
Icon | Comment
---|---
![power-supply](https://cloud.githubusercontent.com/assets/1309249/8761039/f066736c-2d3c-11e5-96ea-376e731c865c.png) | Minimalistic, but could be mistaken for short circuit
![power-supply-variant](https://cloud.githubusercontent.com/assets/1309249/8761041/f0676448-2d3c-11e5-856b-64c7e1921c54.png) | Computer socket like on a UPS unit and arrow for "continue"
![power-supply-variant2](https://cloud.githubusercontent.com/assets/1309249/8761042/f0691f04-2d3c-11e5-86a8-db8d1c29b008.png) | Literally "no break"
![power-supply-variant3](https://cloud.githubusercontent.com/assets/1309249/8761040/f0672bf4-2d3c-11e5-9eae-42535126d4cb.png) | The arrow is usually used to depict fast-forward, but seems better than a single triangle. Might be mistaken for "very brief/fast light flash".
![power-supply-variant4](https://cloud.githubusercontent.com/assets/1309249/8761043/f06a5ef0-2d3c-11e5-86b6-587b1490f0c6.png) | Arrow for "skip over gap", flash to symbolize what kind of gap
![power-supply-variant5](https://cloud.githubusercontent.com/assets/1309249/8761044/f079effa-2d3c-11e5-9be6-b73ebff4d2ef.png) | added strike to negate the flash to "no energy", but there's actually too little space for this (could be mitigated by moving into the 2px border margin)

**Comment by CoDEmanX** [comment]
Google's `ic_dialer_sip`:
![ic_dialer_sip_24px](https://cloud.githubusercontent.com/assets/1309249/8761388/fc5676b4-2d4f-11e5-9a16-d0029553447f.png)

My IP phone experiment:
![phone-ip](https://cloud.githubusercontent.com/assets/1309249/8761389/fc58a47a-2d4f-11e5-99ba-2779c6cd5a07.png)

**Comment by CoDEmanX** [comment]
There's [ic_router](http://www.google.com/design/icons/#ic_router) by Google, which should do for Access Point / wireless. If you want to distinguish routers and APs however, a variant with two antennas and without the negative (white) squares might work.

**Comment by CoDEmanX** [comment]
A try on certificate:
![certificate](https://cloud.githubusercontent.com/assets/1309249/9073614/d3589826-3b02-11e5-8d09-2cf666618bca.png)

**Comment by Templarian** [comment]
Can you link the SVG for these. I'll get them added.

**Comment by CoDEmanX** [comment]
Cert: https://www.dropbox.com/s/d8y3tw5xbnde45d/certificate.svg?dl=0
IP phone: https://www.dropbox.com/s/4pnvq7dzpwz8lyo/phone-ip.svg?dl=0

Do you want any of the UPS icons too?

**Comment by Templarian** [comment]
Not really sorry, their a little too specific.

**Comment by CoDEmanX** [comment]
No problem. Just a socket might be less specific:
![computer-socket](https://cloud.githubusercontent.com/assets/1309249/9075571/d60bc9da-3b16-11e5-9d5a-65e010b51d60.png) https://www.dropbox.com/s/dfy195oke443lfu/computer-socket.svg?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/power-socket

**Comment by Templarian** [comment]
[![phone-voip](https://materialdesignicons.com/icon/phone-voip)](https://materialdesignicons.com/icon/phone-voip) [![certificate](https://materialdesignicons.com/icon/certificate)](https://materialdesignicons.com/icon/certificate)

**Comment by CoDEmanX** [comment]
We are still missing a few of the requested icons. I changed the initial post so it's easier to see.

**Comment by Templarian** [comment]
Yea, you're right shouldn't have been closed. Just going through some of the open issues marked as contributor. Agreed on the VMware being too specific.

**Comment by cvsguimaraes** [comment]
IMO Access Point can be considered complete, since ic_router is good enough for that purpose.
I've taken another look in the gallery and still didn't found something to use as:
- LAN
- WAN
- Ethernet cable connected/disconnected (can be just the connector and we could use a red version for disconnected)

**Comment by CoDEmanX** [comment]
There are couple of possible icons for LAN if a google for that. Some of them are actually Ethernet cable plugs, so one icon might work for both. No idea about WAN however... isn't GAN (global) = Internet and WAN (wide) = distributed network (possibly world-wide), but not accessible by everyone? Could be a company's intranet, using own cables and satellites. Although it's hard to to draw a line between WAN and a VPN network, to which company employees can connect to over the public internet - I would consider the latter a private network, that uses the GAN and not a WAN.

**Comment by CoDEmanX** [comment]
![ethernet](https://cloud.githubusercontent.com/assets/1309249/9834153/71b94586-59af-11e5-9369-ebec4ad912c9.png) 1. slightly simplified
![ethernet-xxl](https://cloud.githubusercontent.com/assets/1309249/9834154/71bc227e-59af-11e5-9d89-d14d9d1a60b2.png) 2. 4 pins, but too large
![ethernet-cable](https://cloud.githubusercontent.com/assets/1309249/9834155/71bc7cec-59af-11e5-912d-e7ed4c18a0bf.png) 3. stylized cable like seen on Windows, but fine details (1px)
![ethernet-cable-off](https://cloud.githubusercontent.com/assets/1309249/9834221/947f02b6-59b1-11e5-94b0-2a75b73ca6ac.png) 4. same as off-version, doesn't work that well
![ethernet-plug-slim](https://cloud.githubusercontent.com/assets/1309249/9834169/a3a17afa-59af-11e5-8905-e945e7d2243a.png) 5. stylized, looks a bit odd
![ethernet-plug-xxl](https://cloud.githubusercontent.com/assets/1309249/9834157/71bd90aa-59af-11e5-9d03-4cae52626372.png) 6. more literal, but overall too many details
![lan](https://cloud.githubusercontent.com/assets/1309249/9834158/71bf6862-59af-11e5-8803-fb1f858ec334.png) 7. simple network icon
![wan](https://cloud.githubusercontent.com/assets/1309249/9834159/71d12c6e-59af-11e5-87d9-6e6b5d3b8f8f.png) 8. network + web (scaled down)
![wan-2px](https://cloud.githubusercontent.com/assets/1309249/9834160/71d43512-59af-11e5-81e3-88841853bc56.png) 9. network + custom crafted globe (2px lines)

7 and 9 should be fine. I would also add 3 despite the thin details, all others are either too detailed or look too fat / bold.

https://www.dropbox.com/sh/faesszv5ey4e6es/AAB5mp3ojtTu_FDzO20bGfa6a?dl=0

**Comment by cvsguimaraes** [comment]
Number 6 looks fantastic!! Indeed it has too many details, but the icons (for the webfont at least) are pixel perfect at `24px`, isn't?!  If so I think it will not be used a lot in smaller sizes than that...

Also would be nice to have 1px margin by reducing the height a little:
![screenshot_1](https://cloud.githubusercontent.com/assets/1047033/9834407/683ce53e-598d-11e5-9367-bb0abd13de39.png)

Thanks @CoDEmanX !

**Comment by Templarian** [comment]
1, 3, 4, 7, 8, and the 1px solid margin version. Stylized has too much detail on the ethernet cable.

**Comment by CoDEmanX** [comment]
Really 8, not 9? 9 is more pixel-perfect, but has a higher perceived weight. I still prefer it because 8 looks slightly washed out on my regular density screen.

Dropbox link contains all icons.

**Comment by cvsguimaraes** [comment]
@CoDEmanX About your thoughts on the VPN icon. I believe that something like this can represent the VPN concept very well:
![house-office 2](https://cloud.githubusercontent.com/assets/1047033/9918324/82f9edd8-5c9c-11e5-907f-0ac064b0dd53.JPG)

Unfortunately I believe it will require too many details to look good...

**Comment by Templarian** [comment]
@cvsguimaraes VPN is in the pack already and fits really nice in the Material style.

[![vpn](https://materialdesignicons.com/icon/vpn)](https://materialdesignicons.com/icon/vpn)

**Comment by cvsguimaraes** [comment]
@Templarian thanks!

Just curious, how did you came up with this symbol?!
I've did an image search and all that I could found like this was a [bank logo](https://www.google.com.br/search?q=norges+bank&espv=2&biw=1366&bih=643&source=lnms&tbm=isch&sa=X&ved=0CAcQ_AUoAmoVChMIq6Oa2vn9xwIVxQ6QCh29QgkA#tbm=isch&q=norges+bank+logo).

My concerns are just to make sure that users will recognize it as something IT related.

**Comment by CoDEmanX** [comment]
@cvsguimaraes: it's derived from Microsoft's VPN logo, see https://github.com/Templarian/MaterialDesign/issues/204#issuecomment-122531842

**Comment by cvsguimaraes** [comment]
@CoDEmanX @Templarian Awww I see...
Argh,  I'm always searching in the wrong place :sweat_smile: 

Sorry for bothering you guys

**Comment by wp9015362** [comment]
> @CoDEmanX wrote:
> 
> ![lan-laptops](https://cloud.githubusercontent.com/assets/1309249/9834290/9d488b26-59b4-11e5-8216-98af7dba5eb7.png) LAN with two laptops, too big
> ![lan-laptops2](https://cloud.githubusercontent.com/assets/1309249/9834288/9d481d9e-59b4-11e5-8f9a-394556f64825.png) 1px margin, dotted line
> ![lan-laptops3](https://cloud.githubusercontent.com/assets/1309249/9834291/9d49e962-59b4-11e5-9bda-98cd651a123d.png) 1px margin, solid line
> ![lan-laptops4](https://cloud.githubusercontent.com/assets/1309249/9834289/9d484954-59b4-11e5-8da3-c35a6bf63736.png) 2px margin

Those lan-with-two-laptops icons look nice.

The ConnectBot devs are currently looking into using Material icons for indicating if a host is currently connected or disconnected (https://github.com/connectbot/connectbot/issues/217).

A lan-with-two-laptops icon could work well for that IMHO, by using it with full opacity for the connected (active) status and with reduced opacity for the disconnected (inactive) status.

So, it would be nice if such an icon would find it's way into the collection :+1: .

PS: If you have a better idea than reducing the opacity for the disconnected (inactive) status, or generally have an idea for another icon that could fit for https://github.com/connectbot/connectbot/issues/217, feel free to express :wink:.

Regards

**Comment by CoDEmanX** [comment]
Like that?
![lan-laptops3-disconnected](https://cloud.githubusercontent.com/assets/1309249/9962780/d60bfeee-5e27-11e5-8cc1-675fc6b5cf6a.png) https://www.dropbox.com/s/6x376bznvfvvozc/lan-laptops3-disconnected.svg?dl=0

**Comment by wp9015362** [comment]
Thanks a lot @CoDEmanX . I've forwarded it to the dev in charge (@khorimoto) via https://github.com/connectbot/connectbot/issues/217.

Let's see what he will say.

Regards

**Comment by wp9015362** [comment]
PS:

@CoDEmanX :

Seems like @khorimoto likes it, see: https://github.com/connectbot/connectbot/issues/217#issuecomment-141501479 :wink:.

Are those the final versions of the "lan-laptops3" and "lan-laptops3-disconnected" icons and will they be included in the [collection](https://materialdesignicons.com/)?

Regards

**Comment by CoDEmanX** [comment]
That's up to @Templarian, but you can use the SVGs if you want.

**Comment by Templarian** [comment]
I've been reading along, yea I'll get these in tonight. Traveling for work, so busy week.

You can put the SVG files into https://materialdesignicons.com/custom if you need the images right away.

**Comment by wp9015362** [comment]
@CoDEmanX :

Another ConnectBot dev (@kruton) commented and said they would also need an icon for "not yet connected" (i.e. pending connection).

Any suggestion for that? I've already suggested your icon with dotted lines to them, i.e.:

> Not yet connected:
> ![lan-laptops2](https://cloud.githubusercontent.com/assets/1309249/9834288/9d481d9e-59b4-11e5-8f9a-394556f64825.png)
> Connected:
> ![lan-laptops3](https://cloud.githubusercontent.com/assets/1309249/9834291/9d49e962-59b4-11e5-9bda-98cd651a123d.png)
> Disconnected:
> ![lan-laptops3-disconnected](https://cloud.githubusercontent.com/assets/1309249/9962780/d60bfeee-5e27-11e5-8cc1-675fc6b5cf6a.png)

Do you have another suggestion for a pending connection icon?

Maybe a small clockface in place where the line/cross is in the connected/disconnected icon? 

Regards

**Comment by cvsguimaraes** [comment]
@wp9015362 I believe the interpretations of the icons are subjective to each context they're used, so would be nice the leave their name as abstract as possible, i.e always favor for abstract names on icon variants. Something like:
 * `lan`
 * `lan-dotted`
 * `lan-disconnected` (`lan-off` would be nice but gives the idea of a `\` over the icon)

Those 3 icons are great btw

:laughing:

**Comment by CoDEmanX** [comment]
How about these 4 states?
http://codepen.io/simran/pen/YyqBNp

I'm not 100% happy with `disconnected`, it looks slightly blurry.

**Comment by wp9015362** [comment]
@CoDEmanX :

Thank you, but I think the pending state should not have a dotted line, but instead should have a clockface like in:

[ic_access_time](https://www.google.com/design/icons/#ic_access_time):
![ic_access_time](https://raw.githubusercontent.com/google/material-design-icons/master/device/drawable-xxxhdpi/ic_access_time_black_18dp.png)

I am also not quite sure if I do like the style of the question mark in the unknown state. Maybe it should be the same question mark as in:

[ic_help_outline](https://www.google.com/design/icons/#ic_help_outline):
![ic_help_outline](https://raw.githubusercontent.com/google/material-design-icons/master/action/drawable-xxxhdpi/ic_help_outline_black_18dp.png)

for better consistency?

Also, can't you just use:

[ic_computer](https://www.google.com/design/icons/#ic_computer):
![ic_help_computer](https://raw.githubusercontent.com/google/material-design-icons/master/hardware/drawable-xxxhdpi/ic_computer_black_18dp.png)

for the two computers/laptops?

Or wouldn't it be allowed to reuse those icons to create other icons?

Regards

**Comment by CoDEmanX** [comment]
There's simply not enough space for a clockface, and actually no question mark either - unless you bend the MD guidelines.

**Comment by wp9015362** [comment]
@CoDEmanX :

Okay, then I have another suggestion:

How about using the network-* icon as a base:

[account-network](https://materialdesignicons.com/icon/account-network)
![account-network](https://cloud.githubusercontent.com/assets/7558360/9970380/15b093fc-5e55-11e5-9d36-a57ca7991c8a.png)

[close-network](https://materialdesignicons.com/icon/close-network)
![close-network](https://cloud.githubusercontent.com/assets/7558360/9970384/19d091c6-5e55-11e5-8baf-a687d6a8f0b0.png)

[minus-network](https://materialdesignicons.com/icon/minus-network)
![minus-network](https://cloud.githubusercontent.com/assets/7558360/9970385/1da02bd6-5e55-11e5-8c40-72d28d4d590c.png)

[plus-network](https://materialdesignicons.com/icon/plus-network)
![plus-network](https://cloud.githubusercontent.com/assets/7558360/9970005/88101362-5e52-11e5-83c8-bc809658bb1a.png)

[security-network](https://materialdesignicons.com/icon/security-network)
![security-network](https://cloud.githubusercontent.com/assets/7558360/9970387/22c8591c-5e55-11e5-9559-da6383411462.png)

[server-network](https://materialdesignicons.com/icon/server-network)
![server-network](https://cloud.githubusercontent.com/assets/7558360/9970388/26b013c6-5e55-11e5-828f-83bf0f340fe9.png)

[server-network-off](https://materialdesignicons.com/icon/server-network-off)
![server-network-off](https://cloud.githubusercontent.com/assets/7558360/9970392/2bd08d72-5e55-11e5-9cc7-5003e5303fba.png)

and extending it with some more variations by replacing the plus/minus/close/etc. symbols with the symbols in the following icons for example:

[ic_check_circle](https://www.google.com/design/icons/#ic_check_circle) for ***connected/connection established state*** (i.e. "network-connected" or "network-established"):
![ic_check_circle](https://raw.githubusercontent.com/google/material-design-icons/master/action/drawable-xxxhdpi/ic_check_circle_black_18dp.png)

[ic_highlight_off](https://www.google.com/design/icons/#ic_highlight_off) for ***disconnected state*** (i.e. "network-disconnected"):
![ic_highlight_off](https://raw.githubusercontent.com/google/material-design-icons/master/action/drawable-xxxhdpi/ic_highlight_off_black_18dp.png)
(well, this is pretty much already availble as [close-network](https://materialdesignicons.com/icon/close-network))

[ic_help_outline](https://www.google.com/design/icons/#ic_help_outline) for ***unknown state*** (i.e. "network-unknown"):
![ic_help_outline](https://raw.githubusercontent.com/google/material-design-icons/master/action/drawable-xxxhdpi/ic_help_outline_black_18dp.png)

[ic_error_outline](https://www.google.com/design/icons/#ic_error_outline) for ***error state*** (i.e. "network-error"):
![ic_error_outline](https://raw.githubusercontent.com/google/material-design-icons/master/alert/drawable-xxxhdpi/ic_error_outline_black_18dp.png)

[ic_access_time](https://www.google.com/design/icons/#ic_access_time) for ***pending state*** (i.e. "network-pending"):
![ic_access_time](https://raw.githubusercontent.com/google/material-design-icons/master/device/drawable-xxxhdpi/ic_access_time_black_18dp.png)

[ic_swap_vertical_circle](https://www.google.com/design/icons/#ic_swap_vertical_circle) for ***up- and download state*** (i.e. "network-updownload") (consequently there could (and should) also be ***download state*** (i.e. "network-download") with the up arrow being removed and a ***upload state*** (i.e. "network-upload") with the down arrow being removed.) :
![ic_swap_vertical_circle](https://raw.githubusercontent.com/google/material-design-icons/master/action/drawable-xxxhdpi/ic_swap_vertical_circle_black_18dp.png)


?

Those would be some nice additions, don't you think?

Personally I do not really care if the top symbol would be a square (like in the already existing network-* icons) or a circle and also wouldn't care if it has an outline or not.

What do you think?

Regards

**Comment by CoDEmanX** [comment]
Those network icons represent nodes or actions, not connection state...

**Comment by CoDEmanX** [comment]
Like this:
![pending-network](https://cloud.githubusercontent.com/assets/1309249/9976768/70549c74-5eee-11e5-9098-12c0a72472cc.png)
![check-network](https://cloud.githubusercontent.com/assets/1309249/9976769/7b43e518-5eee-11e5-9b05-29d31d2d6033.png)

@Templarian?

**Comment by wp9015362** [comment]
> @CoDEmanX wrote:
> 
> Those network icons represent nodes or actions, not connection state...

You are right.

> @CoDEmanX wrote:
> 
> Like this:

After having seen them now, I have to admit I actually prefer the the [lan-laptops-* icons](http://codepen.io/simran/pen/YyqBNp) :open_mouth: :wink:.

Regards

**Comment by Templarian** [comment]
[![lan](https://materialdesignicons.com/icon/lan)](https://materialdesignicons.com/icon/lan) [![lan-connect](https://materialdesignicons.com/icon/lan-connect)](https://materialdesignicons.com/icon/lan-connect) [![lan-pending](https://materialdesignicons.com/icon/lan-pending)](https://materialdesignicons.com/icon/lan-pending) [![lan-disconnect](https://materialdesignicons.com/icon/lan-disconnect)](https://materialdesignicons.com/icon/lan-disconnect) [![wan](https://materialdesignicons.com/icon/wan)](https://materialdesignicons.com/icon/wan) [![ethernet](https://materialdesignicons.com/icon/ethernet)](https://materialdesignicons.com/icon/ethernet) [![ethernet-cable](https://materialdesignicons.com/icon/ethernet-cable)](https://materialdesignicons.com/icon/ethernet-cable) [![ethernet-cable-off](https://materialdesignicons.com/icon/ethernet-cable-off)](https://materialdesignicons.com/icon/ethernet-cable-off)

**Comment by CoDEmanX** [comment]
Maybe the lines in lan-connect should be made 1px longer to be consistent with lan-pending? Or make the dotted line use 3 squares only?

**Comment by cvsguimaraes** [comment]
@Templarian :heart:

**Comment by CoDEmanX** [comment]
Access point icon (I hope I didn't overlook an existing icon like this):
![access-point](https://cloud.githubusercontent.com/assets/1309249/10017323/a8553f7a-612d-11e5-9d73-1ecf3466f2a9.png) https://www.dropbox.com/s/vk52kp1v1zuvhzm/access-point.svg?dl=0

**Comment by cvsguimaraes** [comment]
@CoDEmanX there's the [ic_router](http://www.google.com/design/icons/#ic_router) icon as you mentioned before. However I can't find it in the [current collectio](https://materialdesignicons.com/). I'm missing something here?!

**Comment by CoDEmanX** [comment]
See #420, it's yet to be added. Routers and APs are different (at least in operation mode), so I think 1-2 extra icons for APs are reasonable. Also, `ic_router` focuses much on the physical device, whereas my proposed icons are more conceptual.

**Comment by Templarian** [comment]
[![access-point](https://materialdesignicons.com/icon/access-point)](https://materialdesignicons.com/icon/access-point) [![access-point-network](https://materialdesignicons.com/icon/access-point-network)](https://materialdesignicons.com/icon/access-point-network)

**Comment by CoDEmanX** [comment]
How about adding the following icons?

![folder-key](https://cloud.githubusercontent.com/assets/1309249/13510218/e203f2a6-e18f-11e5-9e06-ce17fdf7715e.png) protected folder (also LDAP I guess)
![network-folder](https://cloud.githubusercontent.com/assets/1309249/13510219/e206079e-e18f-11e5-94d5-3a70ca411ce6.png) network share
![remote-desktop](https://cloud.githubusercontent.com/assets/1309249/13510220/e20960d8-e18f-11e5-9cc3-f28d400230c7.png) remote desktop

**Comment by onreachable** [comment]
The key in "protected folder" seem to unaligned. Also if you're able to fit that key (or ideally an user head) in "network share" icon it would represent very well what a LDAP folder is...

**Comment by CoDEmanX** [comment]
@onreachable: have a look at the existing folder icons, they have the counter shapes aligned to the right. If you centered them, the curvature at the top that adds the folder-meaning to the rectangle gets visually lost.

User + key will probably not fit, but yeah, would be best for LDAP.

**Comment by CoDEmanX** [comment]
Found a (different) certificate icon in Google Chrome:

![image](https://user-images.githubusercontent.com/1309249/35049816-7529c6e6-fba1-11e7-8754-cb1fe510894b.png)
![image](https://user-images.githubusercontent.com/1309249/35049821-7be4abfe-fba1-11e7-8028-8961a1d24170.png)

It fills the entire 24x24 grid. Thus, I tried to shrink it to a 20x20 rectangle to see if that works too:

![chrome_cert_recreated](https://user-images.githubusercontent.com/1309249/35050642-94545d0e-fba3-11e7-9ecd-f56c480d0e58.png) ![chrome_cert_small](https://user-images.githubusercontent.com/1309249/35050643-94d2b7a8-fba3-11e7-88a0-47d89378a69d.png)

**Comment by JamesCoyle** [comment]
Closing as we now have a certificate icon

**Comment by PeterShaggyNoble** [comment]
There was a lot going on in this issue so, if there are any outstanding requests from it, please open a new issue for each one, not forgetting to search existing icons and issues first.
