### ISSUE TITLE
turnstile, turnstile-off

### ISSUE THREAD

**Issue by xplodwild** [Templarian/MaterialDesign#3690]
It would be awesome for my current project to have a turnstile, and turnstile-off icon.

Examples:
https://static.thenounproject.com/png/844765-200.png
https://static.thenounproject.com/png/52544-200.png
https://image.shutterstock.com/image-vector/access-door-outline-icon-linear-260nw-1086780113.jpg

Thanks!

**Comment by MrGrigri** [comment]
Maybe. Idk how I feel about this, but it's a start.

![image](https://user-images.githubusercontent.com/4528551/48442441-7cf82200-e74b-11e8-8a3f-def638354a6e.png) ![image](https://user-images.githubusercontent.com/4528551/48442460-8b463e00-e74b-11e8-8985-26a9f099fbb6.png)

---

[turnstyle.zip](https://github.com/Templarian/MaterialDesign/files/2578063/turnstyle.zip)

**Comment by xplodwild** [comment]
Didn't expect it that fast, congrats to you!
Good start indeed, but I agree something's grinding my gears. Perhaps the "head ball" (what holds the bars) could be a bit smaller, or removed altogether? And adding a third, shorter bar? Just throwing a few ideas that may help

**Comment by MrGrigri** [comment]
What would be the point of a `turnstyle-off`?

**Comment by xplodwild** [comment]
I'm building a web UI to check the status of various turnstile-powered access control solutions. `turnstile-off` (beware, it's a "i" not a "y") would basically be used to notify that one of the turnstile is disconnected from the network and not operational.
It could maybe be a `-remove` variant (like `shield-remove`) instead of the traditional crossed-out `-off` layout? Both would work in my use case.

**Comment by Templarian** [comment]
There is something slightly off, but I think it works in context. As we don't know any other idea I'm going to add these and just assume someone could create another version in the future.

**Comment by Templarian** [comment]
Added. Also @MrGrigri `turnstile`. I almost spelled it wrong also.
