### ISSUE TITLE
ruler-square

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3691]
Here is a new icon for `ruler-square`. I used the same teeth size as the original `ruler` icon at 1.5-pixel wide. 

Possible alises:

- [ ] square
- [ ] carpentry
- [ ] archetecture

![image](https://user-images.githubusercontent.com/4528551/48441223-35bc6200-e748-11e8-9d02-a0774e3a6e70.png)

--- 

[ruler-square.zip](https://github.com/Templarian/MaterialDesign/files/2577949/ruler-square.zip)

**Comment by Templarian** [comment]
Added with aliases.
