### ISSUE TITLE
barrier

### ISSUE THREAD

**Issue by sebkob** [Templarian/MaterialDesign#3692]
![barrier_small](https://user-images.githubusercontent.com/39202827/48444831-5d85e700-e795-11e8-9d05-ee9cae0dae0e.png)

**Comment by goyney** [comment]
Would `sign-caution` fit your needs?
[![image](https://user-images.githubusercontent.com/1015040/48456889-aa19f400-e78e-11e8-8212-225ca69fe0d6.png)](https://materialdesignicons.com/icon/sign-caution)

**Comment by goyney** [comment]
If so, we can alias this one.

**Comment by goyney** [comment]
Added `barrier` as an alias to `sign-caution`.
