### ISSUE TITLE
Missing shield outlines

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3693]
These can be added once #3654 has been addressed. These are the missing `shield-*-outline` variants.
![image](https://user-images.githubusercontent.com/1015040/48455362-e185a200-e788-11e8-94f2-154f184491e0.png)![image](https://user-images.githubusercontent.com/1015040/48455525-90c27900-e789-11e8-9e2b-4f86895254cf.png)
![image](https://user-images.githubusercontent.com/1015040/48455386-f2ceae80-e788-11e8-8f6d-2a4f9029c878.png)![image](https://user-images.githubusercontent.com/1015040/48455401-fb26e980-e788-11e8-90fd-78b426bde23c.png)
![image](https://user-images.githubusercontent.com/1015040/48455405-037f2480-e789-11e8-9c66-7da8840688d4.png)![image](https://user-images.githubusercontent.com/1015040/48455415-0b3ec900-e789-11e8-87e2-3a806eddedeb.png)

[shield-outline.zip](https://github.com/Templarian/MaterialDesign/files/2578923/shield-outline.zip)

**Comment by Templarian** [comment]
Since we already have a different style for shield remove I didn't add that one.

Also `shield-airplane-outline` not `plane`.

Rest were added as is.
