### ISSUE TITLE
Update several account icons

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3694]
All of our `account-*` icons have the floating variant icon to the left of the person, with the exception of these icons:

- [ ] account-alert
- [ ] account-alert-outline
- [ ] account-multiple-check
- [ ] account-question
- [ ] account-question-outline

Should we consider updating these icons to follow the pattern of all the rest?

---

Additionally, we are missing:
- [x] account-star-outline
- [x] account-heart-outline
- [x] account-key-outline
- [ ] account-multiple-check-outline

**Comment by Templarian** [comment]
- The approach for the alert is on the right so it reads left-to-right. So those can be ignored.
- I have an update for `account-check`, that uses the Google icon's style.
- Same as `account-alert`
- We need to add these missing ones. They are a little weird since just the account part is outline, but it is okay.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48456552-4f33cd00-e78d-11e8-90ae-0a571822cedf.png)![image](https://user-images.githubusercontent.com/1015040/48456557-56f37180-e78d-11e8-81dc-ab9536806a49.png)
![image](https://user-images.githubusercontent.com/1015040/48456566-5f4bac80-e78d-11e8-8b3c-10bbda900577.png)

[account-outlines.zip](https://github.com/Templarian/MaterialDesign/files/2579004/account-outlines.zip)

**Comment by Templarian** [comment]
Resolved. 😃

**Comment by PeterShaggyNoble** [comment]
We can probably close out #2809 on the back of this then?
