### ISSUE TITLE
delete-sweep-outline

### ISSUE THREAD

**Issue by donhurickerby** [Templarian/MaterialDesign#3695]
combine delete outline and delete sweep

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48503566-7da6bc00-e810-11e8-9bea-3939cba1af0f.png)
[delete-sweep-outline.zip](https://github.com/Templarian/MaterialDesign/files/2582075/delete-sweep-outline.zip)

**Comment by Templarian** [comment]
[![delete-sweep-outline](https://materialdesignicons.com/icon/delete-sweep-outline)](https://materialdesignicons.com/icon/delete-sweep-outline)
