### ISSUE TITLE
Parachute

### ISSUE THREAD

**Issue by sureshreddyputta** [Templarian/MaterialDesign#3696]
There is no Parachute available right now. can you upload it to the library?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48558236-d6c92b00-e8b6-11e8-88cf-586b35c6aa6f.png)![image](https://user-images.githubusercontent.com/1015040/48558247-de88cf80-e8b6-11e8-86f7-c3d9810faf4e.png)

[parachute.zip](https://github.com/Templarian/MaterialDesign/files/2585615/parachute.zip)

**Comment by CoDEmanX** [comment]
Looks nice, but couldn't the inner two straps have a straight terminal (relative to their own axis)?

**Comment by goyney** [comment]
None of them have straight terminals, they're cut at a 1dp width with the curve of the parachute top.

**Comment by Templarian** [comment]
Added both. Line ends look fine to me.
