### ISSUE TITLE
Math sin cos tan

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3698]
We can either add these as text or a symbol if they exist.

- [x] `math-cos`
- [x] `math-sin`
- [x] `math-tan`

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48566056-e3a24a80-e8c7-11e8-9c44-18d990963741.png)![image](https://user-images.githubusercontent.com/1015040/48566039-d9804c00-e8c7-11e8-9be3-2d3065a0cb6b.png)
![image](https://user-images.githubusercontent.com/1015040/48566067-ec931c00-e8c7-11e8-8b0f-e3de4d6a977b.png)

[math.zip](https://github.com/Templarian/MaterialDesign/files/2586119/math.zip)

**Comment by Templarian** [comment]
Added. 😃
