### ISSUE TITLE
Microwave

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#3699]
[![](https://user-images.githubusercontent.com/15905797/48580216-82ee2e80-e916-11e8-91f2-8564e43d1bee.png)](https://github.com/Templarian/MaterialDesign/files/2586954/microwave.zip)

**Comment by goyney** [comment]
* `microwave-classic` :)

**Comment by MrGrigri** [comment]
I believe if you move the handle, we could add an `oven-toaster` as well.

**Comment by Templarian** [comment]
[![toaster-oven](https://materialdesignicons.com/icon/toaster-oven)](https://materialdesignicons.com/icon/toaster-oven) [![microwave](https://materialdesignicons.com/icon/microwave)](https://materialdesignicons.com/icon/microwave)
