### ISSUE TITLE
Food category icons

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#37]
Icons for meal categories would be nice. Such as organic, vegetarian, vegan, pork, cow and fish

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/carrot *rabbit noise*

**Comment by matthew2402** [comment]
Awesome!
Maybe a basket with vegetable and fruits for Bio and a leaf for vegan

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/leaf (I don't really like this one and will probably be replacing it).
http://materialdesignicons.com/icon/bio

I'll try to do a basket with fruits, but I don't think the detail is possible tbh.

**Comment by matthew2402** [comment]
That's nice! Maybe a basket with an apple and bottle of milk would be nice solution for bio.

**Comment by matthew2402** [comment]
Idea for vegan:
https://drive.google.com/file/d/0BxbgboM9HJr9REp5ZjQ4MktQdXc/view?usp=sharing

**Comment by Templarian** [comment]
That is almost perfect. Do you have a source for the image? I need to check licensing etc.

The only small issue might be that it is perspective, and Material Design guidelines specifically say no perspective, but maybe just the leaf?

**Comment by matthew2402** [comment]
I think a small perspective is okay ;)

http://icons8.com/web-app/category/all/Food
The license: http://icons8.com/license/

**Comment by Templarian** [comment]
That license will not work with this pack.

* The leaf icon was replaced.
* http://materialdesignicons.com/icon/food-apple

**Comment by matthew2402** [comment]
Thumbs up! Thanks
