### ISSUE TITLE
file-table

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3701]
I'm using this to represent a template, and I figured it would be a nice one to have.

![image](https://user-images.githubusercontent.com/4528551/48586288-c338b700-e8ec-11e8-8b7f-181df3ca81f7.png) ![image](https://user-images.githubusercontent.com/4528551/48586319-d51a5a00-e8ec-11e8-80c4-0a010a88ceb1.png)

[file-table.zip](https://github.com/Templarian/MaterialDesign/files/2587300/file-table.zip)

**Comment by Templarian** [comment]
Added. 😃
