### ISSUE TITLE
youtube-off

### ISSUE THREAD

**Issue by edorofeyev** [Templarian/MaterialDesign#3704]
Here, can you add this icon?
It indicates that YouTube is not supported (by some service or, in my case, an application).

Thanks.

[youtube-off.zip](https://github.com/Templarian/MaterialDesign/files/2591141/youtube-off.zip)

**Comment by PeterShaggyNoble** [comment]
We can't modify brand icons like this, I'm afraid; we have to adhere to a brand's guidelines for usage of their logo/iconography.

If an official `youtube-off` icon exists, though, please let us know and reopen this issue.

The best alternative I can think of off the top of my head is to use `video` and `video-off` instead.
