### ISSUE TITLE
"Delivered"-icon, truck with checkmark

### ISSUE THREAD

**Issue by Nallefjant** [Templarian/MaterialDesign#3705]

**Comment by Templarian** [comment]
@Nallefjant Did you mean to close this? Just want to double check, because it actually might be a useful icon for showing a package was delivered (we have the arrow for in-transit).

**Comment by Templarian** [comment]
[![truck-check](https://materialdesignicons.com/icon/truck-check)](https://materialdesignicons.com/icon/truck-check)

Bottom right looked a little odd, but this fitted nicer.
