### ISSUE TITLE
create-outline

### ISSUE THREAD

**Issue by valaki52** [Templarian/MaterialDesign#3707]
We need it.
![image](https://user-images.githubusercontent.com/41679054/48676422-15850c80-eb67-11e8-8bc6-e274fcf29781.png)

**Comment by Templarian** [comment]
Yea, you're right the stock one is slightly different. Updated.

[![pencil-outline](https://materialdesignicons.com/icon/pencil-outline)](https://materialdesignicons.com/icon/pencil-outline)
