### ISSUE TITLE
Aliases to be removed

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3709]
- [x] `account-details`: `user-settings-variant` no longer needed (Icon was renamed)
- [x] `tooltip-account`: `*-address` & `*-location` no longer needed (Icon was renamed)
- [x] `account-off-outline`: Duplicate occurrence of `user-off-outline`
- [x] `account-question`: Duplicate occurrence of `account-help`
- [x] `barley`: 2 duplicate occurrences of `wheat`
- [x] `checkbox-multiple-marked`: `checkboxes-multiple-marked` added accidentally
- [x] `fridge`: `refrigerator-filled` no longer needed (Icon was renamed)
- [x] `fridge-filled-top`: `refrigerator-filled-top` no longer needed (Icon was renamed)
- [x] `fridge-outline`: `refrigerator` no longer needed (Icon was renamed)
- [x] `fridge-top`: `refrigerator-filled-bottom` no longer needed (Icon was renamed)
- [x] `script-outline`: `scroll` no longer needed (Icon was renamed)
- [x] `shield-airplane`: `airplane-shield` no longer needed (Icon was renamed)
- [x] `shield-check`: `shield-check` no longer needed (Icon was renamed)

**Comment by Templarian** [comment]
Good catch. These have all been fixed. Except for `barley` I don't see the duplicate `wheat` aliases in the database?

**Comment by PeterShaggyNoble** [comment]
@Templarian, I think you got the `wheat` ones already; I was referencing the history while creating the list and it's still showing 3 entries for it.
