### ISSUE TITLE
Car Headlamps

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3711]
This issue is a split off of #874. It includes the three car headlamp icons: dimmed beam, high beam, and fog lamp.

These icons were created by @Alekhen and should be attributed appropriately.
![image](https://user-images.githubusercontent.com/1015040/48714729-502b8b00-ebe1-11e8-9fac-7fd55664ad9b.png)![image](https://user-images.githubusercontent.com/1015040/48714733-528de500-ebe1-11e8-854b-2c0d2612f51c.png)
![image](https://user-images.githubusercontent.com/1015040/48714740-57529900-ebe1-11e8-9d43-6dfaad7345a5.png)

[headlamps.zip](https://github.com/Templarian/MaterialDesign/files/2595746/headlamps.zip)

**Comment by Templarian** [comment]
[![car-light-dimmed](https://materialdesignicons.com/icon/car-light-dimmed)](https://materialdesignicons.com/icon/car-light-dimmed) [![car-light-high](https://materialdesignicons.com/icon/car-light-high)](https://materialdesignicons.com/icon/car-light-high) [![car-light-fog](https://materialdesignicons.com/icon/car-light-fog)](https://materialdesignicons.com/icon/car-light-fog)
