### ISSUE TITLE
hazard-lights

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3712]
This issue is a split off of #874.

![image](https://user-images.githubusercontent.com/1015040/48716377-3b50f680-ebe5-11e8-9176-0ab0eb81e536.png)
[hazard-lights.zip](https://github.com/Templarian/MaterialDesign/files/2595879/hazard-lights.zip)

**Comment by MrGrigri** [comment]
That doesn't look equilateral enough. Why not use the `triangle-outline`?

**Comment by Templarian** [comment]
[![hazard-lights](https://materialdesignicons.com/icon/hazard-lights)](https://materialdesignicons.com/icon/hazard-lights)
