### ISSUE TITLE
seatbelt

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3713]
This issue is a split off of #874.

![image](https://user-images.githubusercontent.com/1015040/48716460-6dfaef00-ebe5-11e8-9477-b43567bfef21.png)
[seatbelt.zip](https://github.com/Templarian/MaterialDesign/files/2595889/seatbelt.zip)

**Comment by Templarian** [comment]
Added as one word. But I guess it's actually hyphenated.

[![seatbelt](https://materialdesignicons.com/icon/seatbelt)](https://materialdesignicons.com/icon/seatbelt)
