### ISSUE TITLE
airbag

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3714]
This issue is a split off of #874.

![image](https://user-images.githubusercontent.com/1015040/48717322-27a68f80-ebe7-11e8-85db-fd7d4d17b62d.png)
[airbag.zip](https://github.com/Templarian/MaterialDesign/files/2595951/airbag.zip)

**Comment by Templarian** [comment]
[![airbag](https://materialdesignicons.com/icon/airbag)](https://materialdesignicons.com/icon/airbag)
