### ISSUE TITLE
briefcase-*-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3715]
All the missing briefcase outlines:

![image](https://user-images.githubusercontent.com/1015040/48748217-0e7ffc00-ec44-11e8-9506-1ed988d40f61.png)![image](https://user-images.githubusercontent.com/1015040/48748228-19d32780-ec44-11e8-8f85-c3903b52c368.png)
![image](https://user-images.githubusercontent.com/1015040/48748238-222b6280-ec44-11e8-80cb-737515889ee1.png)![image](https://user-images.githubusercontent.com/1015040/48748245-29eb0700-ec44-11e8-8b6f-3981e1b9b58b.png)
![image](https://user-images.githubusercontent.com/1015040/48748256-32434200-ec44-11e8-9e73-1fffae19bedf.png)![image](https://user-images.githubusercontent.com/1015040/48748264-3a9b7d00-ec44-11e8-822d-837b5d8974df.png)
![image](https://user-images.githubusercontent.com/1015040/48748271-42f3b800-ec44-11e8-8bad-bb74312acfac.png)![image](https://user-images.githubusercontent.com/1015040/48748276-4a1ac600-ec44-11e8-8b79-2827c4f6b86b.png)

[briefcase-outline.zip](https://github.com/Templarian/MaterialDesign/files/2597841/briefcase-outline.zip)

**Comment by JamesCoyle** [comment]
I feel the plus, minus, and remove should be inside the case.

**Comment by goyney** [comment]
Then the existing ones will also need to be updated.

**Comment by goyney** [comment]
After some internal discussion, we're going to change `-plus`, `-minus`, and `-remove`, which includes changing the filled versions as well.

![image](https://user-images.githubusercontent.com/1015040/48802379-1b9cf980-ecdd-11e8-9ce7-c2cbfc04cdf1.png)![image](https://user-images.githubusercontent.com/1015040/48802398-26f02500-ecdd-11e8-8176-f042f58a98b1.png)
![image](https://user-images.githubusercontent.com/1015040/48802423-35d6d780-ecdd-11e8-84c2-687eb7666001.png)![image](https://user-images.githubusercontent.com/1015040/48802431-3c654f00-ecdd-11e8-9cbc-069bc8751819.png)
![image](https://user-images.githubusercontent.com/1015040/48802442-45562080-ecdd-11e8-9194-45cd806f0dd6.png)![image](https://user-images.githubusercontent.com/1015040/48802454-4be49800-ecdd-11e8-80ba-aeaee63613ee.png)

**Comment by Templarian** [comment]
I'm voting against adding the plus inside the briefcase. It will be too confusing as medical related. It's why the current icons are in the corner.

Added. 😃
