### ISSUE TITLE
update database-*

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3716]
We have discussed this internally and have decided to update the `database-*` icons to be more consistent. This issue will track that progress.

This will also create three new icons: `database-remove`, `database-refresh`, and `database-settings` from #2112.

**Comment by MrGrigri** [comment]
For `database-refresh`, I used the same thats in `ballot-recount`. Idk if this could become a common modifier.

![image](https://user-images.githubusercontent.com/4528551/48851956-93186a80-ed69-11e8-88e6-f8c5111ccf2e.png) ![image](https://user-images.githubusercontent.com/4528551/48852077-cbb84400-ed69-11e8-922a-7236da37693b.png) ![image](https://user-images.githubusercontent.com/4528551/48852094-d83c9c80-ed69-11e8-9af8-8b0e7910f8f1.png) ![image](https://user-images.githubusercontent.com/4528551/48852120-e68ab880-ed69-11e8-9180-8cb0006d5605.png) ![image](https://user-images.githubusercontent.com/4528551/48852138-f3a7a780-ed69-11e8-8dfc-ac5ddac700e7.png)

---

[database.zip](https://github.com/Templarian/MaterialDesign/files/2604853/database.zip)

**Comment by MrGrigri** [comment]
For reference:

![image](https://user-images.githubusercontent.com/4528551/48852407-8b0cfa80-ed6a-11e8-8a80-d1ba1ae1c6cd.png)

**Comment by Templarian** [comment]
All of these were fixed. 😃
