### ISSUE TITLE
Update link icon to match Google's

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3718]
Google's in grey, ours overlayed in red:

[![link](https://user-images.githubusercontent.com/15157491/48832541-49cc1900-ed71-11e8-9927-bea6bf82d8aa.png)](https://material.io/tools/icons/?search=link&icon=link&style=baseline) [![link-off](https://user-images.githubusercontent.com/15157491/48832650-8e57b480-ed71-11e8-8398-82fad2eed26f.png)](https://material.io/tools/icons/?search=link&icon=link-off&style=baseline)

**Comment by JamesCoyle** [comment]
That looks so much better. Never liked our version.

**Comment by Templarian** [comment]
Ours was based on theirs, so they must have updated it at some point. 😆 

Reassigned `link-off` to Google and updated both. 😃
