### ISSUE TITLE
Bone Icon

### ISSUE THREAD

**Issue by tmack8001** [Templarian/MaterialDesign#372]
I have a want to add a bone to a web interface or mobile application to signify that the user is currently viewing a "dogfood" version of the application.

The idea is similar to some of the icons leaked in mobile applications like Google's Youtube (See example below).

![youtube dogfood icon](http://www.androidcentral.com/sites/androidcentral.com/files/styles/large/public/article_images/2014/03/youtube-dogfood-logo.png?itok=1BqG5i21)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/bone

**Comment by tmack8001** [comment]
Nice work thanks so much for a quick turn around. I'll include this in my app this week.
