### ISSUE TITLE
Car brake icons

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#3720]
It would be great to have parking/emergency brake light icon like :
![parking-emergency-brake-lights](https://user-images.githubusercontent.com/45227578/48833134-01195d80-ed7b-11e8-9fd4-19aa1a86cdd4.png)

**Comment by PeterShaggyNoble** [comment]
`alert-circle-outline` should be suitable here:

[![alert-circle-outline](http://mdi.houseofdesign.ie/tools/preview/?icon=alert-circle-outline&action=link)](https://materialdesignicons.com/icon/alert-circle-outline)

**Comment by JamesCoyle** [comment]
It may be a good placeholder but I don't think it really accurately depicts a parking brake indicator. I think we should add an icon for it.

**Comment by goyney** [comment]
Way too specific, we generally only name icons to specificity if there is no other obvious use for them. This icon could be used in many contexts, so should be named in a generic fashion.

**Comment by MrGrigri** [comment]
`parking-brake`

**Comment by JamesCoyle** [comment]
I'd just go with `parking-brake`. This style can also be used for ABS warning lights with the text `ABS` inside, and as an indicator to press the brake for autostarting/push-to-start cars with a foot inside.

**Comment by goyney** [comment]
ABS won't fit inside that circle, unfortunately.

**Comment by JamesCoyle** [comment]
Could we go against guidelines and have the outer lines be 1dp?

**Comment by goyney** [comment]
Give me a few minutes and I'll whip up that example for comparison.

**Comment by goyney** [comment]
Here is the 1dp modifier:
![image](https://user-images.githubusercontent.com/1015040/48853270-24dda300-ed7d-11e8-8253-b5b05e96c698.png)

And here is an example of ABS, which doesn't work at native:
![image](https://user-images.githubusercontent.com/1015040/48853320-3a52cd00-ed7d-11e8-9822-bd97845d55e3.png)

And another ABS at 1.5dp on the letters and a cut-out on the circle, which works better at native:
![image](https://user-images.githubusercontent.com/1015040/48853462-8dc51b00-ed7d-11e8-8776-41e1109bc47e.png)

[parking-and-abs.zip](https://github.com/Templarian/MaterialDesign/files/2604928/parking-and-abs.zip)

**Comment by MrGrigri** [comment]
No, on number 2. I like what you did with number 3. And I also like the 1dp outer circle cutouts.

**Comment by goyney** [comment]
Alrighty then, based on discussions, here are the three candidates:

![image](https://user-images.githubusercontent.com/1015040/48853883-7c304300-ed7e-11e8-89fe-1121bcfbe00a.png)![image](https://user-images.githubusercontent.com/1015040/48853909-8eaa7c80-ed7e-11e8-9e46-1214bea078f4.png)
![image](https://user-images.githubusercontent.com/1015040/48853933-9bc76b80-ed7e-11e8-908b-d4371f7bb871.png)

[car-systems.zip](https://github.com/Templarian/MaterialDesign/files/2604950/car-systems.zip)

**Comment by JamesCoyle** [comment]
What does 1.5dp look like? And could to to increase spacing between circle and text if possible.

**Comment by JamesCoyle** [comment]
I think the 1.5 looks better. The letter spacing is fine though. I meant the vertical space between the letters and the inner circle border. At smaller sizes the spacing above and below gets a bit lost in the details.

**Comment by goyney** [comment]
Okay, hopefully this is the final set:
![image](https://user-images.githubusercontent.com/1015040/48855328-d54da600-ed81-11e8-97fb-02c6b6ba19c0.png)![image](https://user-images.githubusercontent.com/1015040/48855297-c9fa7a80-ed81-11e8-89bc-65440c7b3455.png)
![image](https://user-images.githubusercontent.com/1015040/48855277-c0711280-ed81-11e8-9e87-c30f568e9137.png)

[car-systems-final.zip](https://github.com/Templarian/MaterialDesign/files/2605031/car-systems-final.zip)

**Comment by MrGrigri** [comment]
I believe we have a winner. Except, I believe since they are all related, they should be called `brake-parking`, `brake-abs`, and `brake-eps` respectively.

**Comment by goyney** [comment]
Power steering has nothing to do with braking, unfortunately. But the first two, I agree with that naming convention.

**Comment by MrGrigri** [comment]
Ah, I guess your right about that...I didn't even read it and I thought it was Electric Parking System...I guess I'm not car smart 😉

**Comment by PeterShaggyNoble** [comment]
@MrGrigri, [me either](https://github.com/Templarian/MaterialDesign/issues/3720#issuecomment-440620486)! 😆

**Comment by goyney** [comment]
Adding the `Alias` label because, regardless of name, there will be some variations will want to add.

**Comment by JamesCoyle** [comment]
Should EPS even be in that design of icon? I always assumed it was a representation of drum brakes with the outer lines being the shoes.

**Comment by MrGrigri** [comment]
Yeah, all eps icons I'm seeing are a steering wheel with an exclamation next to it.

**Comment by JamesCoyle** [comment]
I think we should add ABS, TCS, EPS, ESC as purely text icons alongside the icon representations.

**Comment by goyney** [comment]
I actually believe you guys are right. Steering uses a steering wheel, which we have. I believe I switched up the letters from the example icon in #874 and it should actually be ESP, or Electronic Stability Control (Program), which is typically a car with wavy tire streaks.

**Comment by JamesCoyle** [comment]
ESP/ESC makes more sense as it often uses computer controlled braking on each wheel.

**Comment by goyney** [comment]
Alright, I updated the ESP icon above and renamed all of them to follow the `brake-*` naming pattern. Good catch @JamesCoyle.

**Comment by Templarian** [comment]
Added. 😃 `car-break-parking` `car-break-abs` and `car-esp`.
