### ISSUE TITLE
Link-Plus

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3721]
From Google's extended set:

[![link-plus](http://mdi.houseofdesign.ie/tools/preview/?icon=add_link&action=launch)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

**Comment by MrGrigri** [comment]
Idk if I like the placement of the plus modifier.

**Comment by goyney** [comment]
I don't know what the use case is here. You typically only see link icons like that in a toolbar, which inherently means "insert".

**Comment by CoDEmanX** [comment]
Maybe for adding a constraint (in the database sense)? But then the regular link icon could be used too, unless it is used for something else in the same app, like adding a relation.How does Google use this icon? In Google Cloud perhaps?

**Comment by Templarian** [comment]
Not really a fan of this icon with the way the plus is positioned. We may way to modify it. 😕

**Comment by CoDEmanX** [comment]
It's pretty smart IMO, given all restrictions. It does not touch the main shape in the only way I can think of. Shifted to the right, it would either overlap the chain, or be in one line with its outer arc, thus would look like one shape.

**Comment by Templarian** [comment]
Added `link-plus`. 😃
