### ISSUE TITLE
alpha-box-outline & alpha-circle-outline

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3722]
Threw together a quick script to generate all of these automatically and save a little work.

[![alpha-a-box-outline](http://mdi.houseofdesign.ie/tools/preview/?name=alpha-a-box-outline&action=download&path=M19,3H5C3.89,3%203,3.89%203,5V19A2,2%200%200,0%205,21H19A2,2%200%200,0%2021,19V5C21,3.89%2020.1,3%2019,3M19,5V19H5V5H19ZM11,7A2,2%200%200,0%209,9V17H11V13H13V17H15V9A2,2%200%200,0%2013,7H11M11,9H13V11H11V9Z)](https://github.com/Templarian/MaterialDesign/files/2604987/alphaoutline.zip) [![alpha-z-circle-outline](http://mdi.houseofdesign.ie/tools/preview/?name=alpha-z-circle-outline&action=download&path=M12,20A8,8%200%200,1%204,12A8,8%200%200,1%2012,4A8,8%200%200,1%2020,12A8,8%200%200,1%2012,20M12,2A10,10%200%200,0%202,12A10,10%200%200,0%2012,22A10,10%200%200,0%2022,12A10,10%200%200,0%2012,2ZM9,7V9H13L9,15V17H15V15H11L15,9V7H9Z)](https://github.com/Templarian/MaterialDesign/files/2604987/alphaoutline.zip)

**Comment by Templarian** [comment]
Thanks, but wish you would had these earlier. I was already part way through exporting all of these.

Will have them all in shortly.

**Comment by PeterShaggyNoble** [comment]
Only now spotting that the descender of the `Q` touches the bottom line of the `box` and is less than 2 pixels from the bottom of the `circle`; don't know what the fix is, though.

**Comment by Templarian** [comment]
@PeterShaggyNoble By the way it doesn't look that bad when viewed with the rest. Should be fine having the 1dp space.
