### ISSUE TITLE
food-apple-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3723]
Here's an apple outline variant.

![food-apple-outline](https://user-images.githubusercontent.com/4528551/48869572-ee168580-ed9a-11e8-91c6-06cc4ac152fc.png)

---

[food-apple-outline.zip](https://github.com/Templarian/MaterialDesign/files/2605852/food-apple-outline.zip)

**Comment by Templarian** [comment]
Added. 😃
