### ISSUE TITLE
photo-size-select

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3724]
There are three `photo-size-select` icons in the stock Google library: small, large, and actual. I'm not sure how we want to name these, or if we even want to include all three.

Additionally, `actual` is the same as `image`, but `actual` is a little wider. Throws another wrench into things, IMO.

![image](https://user-images.githubusercontent.com/1015040/48879066-3e600880-edd8-11e8-93e8-fa237466eb19.png)![image](https://user-images.githubusercontent.com/1015040/48879074-44ee8000-edd8-11e8-8a6f-826800a51d53.png)
![image](https://user-images.githubusercontent.com/1015040/48879084-4d46bb00-edd8-11e8-97be-6d405cfce3ea.png)

[photo-size-select.zip](https://github.com/Templarian/MaterialDesign/files/2606442/photo-size-select.zip)

**Comment by Templarian** [comment]
Added, but we call all the `photo-*` icons `image-*`.
