### ISSUE TITLE
Cursor-click

### ISSUE THREAD

**Issue by PierreClementCazon** [Templarian/MaterialDesign#3728]
Hi,

I think an icon of this style could be useful to represent a click :

![500_f_209980873_kcex8bs27so1ysc5rhc6fozrkne3cywc](https://user-images.githubusercontent.com/36991574/48934890-0525b680-ef06-11e8-84ae-19886b82c17c.jpg)

Thank you in advance for your help !

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48974628-b70ad300-f02b-11e8-9b42-3cb83ce3e8fd.png)![image](https://user-images.githubusercontent.com/1015040/48974644-56c86100-f02c-11e8-834d-806f5d321fdf.png)


My only issue with these two is that the cursor had to be scaled dow, I had to drop the outline to 1.5dp, and had to go into the boundary to make it work. That means these break some rules and won't line up with our existing `cursor-default` icons:
![image](https://user-images.githubusercontent.com/1015040/48974643-4e702600-f02c-11e8-9eb0-db317b58eb06.png)

[cursor-default-click.zip](https://github.com/Templarian/MaterialDesign/files/2612764/cursor-default-click.zip)

**Comment by Templarian** [comment]
[![cursor-default](https://materialdesignicons.com/icon/cursor-default-click)](https://materialdesignicons.com/icon/cursor-default-click) [![cursor-default-outline](https://materialdesignicons.com/icon/cursor-default-click-outline)](https://materialdesignicons.com/icon/cursor-default-click-outline)
