### ISSUE TITLE
Beach Icon

### ISSUE THREAD

**Issue by VitorHugoDS** [Templarian/MaterialDesign#373]
First of all I want to thank all the people supporting this project. It's definitely one of my favorites in here.
I've been using this a lot, for months, at least once a week, and this is the first time I couldn't find an icon that I need.

This is amazing.

So, what I couldn't find is a beach icon. 
(sorry, I can't format the image size here) 
Something like this: 
![hard-liner-clipart-umbrella-and-waves](https://cloud.githubusercontent.com/assets/9389043/7786403/a1936f1c-01a2-11e5-8232-3bb500e11f37.jpg)

MAYBE without the waves, the umbrella on the bottom right and a circle (representing the sun) on the top left.

Thanks!

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/beach
