### ISSUE TITLE
Yamaha brand icon

### ISSUE THREAD

**Issue by chris-thorn** [Templarian/MaterialDesign#3730]
Would it be possible to add the Yamaha logo?

![yamaha](https://user-images.githubusercontent.com/3541291/48937021-c0e5e680-ef04-11e8-8d9c-3ce17f210c09.png)

![image](https://user-images.githubusercontent.com/3541291/48937154-23d77d80-ef05-11e8-8463-5d5bc253bb0c.png)

SVG: [yamaha.zip](https://github.com/Templarian/MaterialDesign/files/2610265/yamaha.zip)

Thanks!

Chris

**Comment by PeterShaggyNoble** [comment]
I'm leaning towards this being beyond the scope of this project but I'll leave it open for now to let the rest of the team weigh in.

**Comment by Templarian** [comment]
Agreed. We may come back to add a lot of brand icons eventually. We'll use the rejected label to track these. There are just too many sound systems out there.

**Comment by PeterShaggyNoble** [comment]
@chris-thorn, for brand icons beyond the scope of this project try [Simple Icons](https://simpleicons.org) instead.
