### ISSUE TITLE
File-search

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3732]
After discussing it briefly with @JamesCoyle the other day, I think we need to add a `file-search` icon. We already have `file-find` but that's typically used to represent searching *within* a file rather than searching *for* files.

**Comment by MrGrigri** [comment]
So, I've had to move the `search modifier` down by one pixel to help with cutout spacing. But here is `file-search` and `file-search-outline`.

![image](https://user-images.githubusercontent.com/4528551/48959776-f1d61380-ef24-11e8-8f41-83d46544c360.png) ![image](https://user-images.githubusercontent.com/4528551/48959795-09ad9780-ef25-11e8-8f80-a5d8ddad6dd3.png)

---

[file-search.zip](https://github.com/Templarian/MaterialDesign/files/2611687/file-search.zip)

**Comment by CoDEmanX** [comment]
I think it should be 1dp longer, so that the gap more like 2dp.
![screenshot_20181123-234551__01](https://user-images.githubusercontent.com/1309249/48962017-4061cd00-ef7a-11e8-8a82-10fe11cea31e.jpg)

**Comment by JamesCoyle** [comment]
Shouldn't the cutout be circular anyway?

**Comment by goyney** [comment]
Yeah, @JamesCoyle, I believe it should be.

**Comment by CoDEmanX** [comment]
I like the circular cutout better, because the gaps are smaller and everything looks more connected as one.

**Comment by Templarian** [comment]
Added. 😃
