### ISSUE TITLE
brightness-percent

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3737]
Please consider adding brightness-percentage for lighting scenes.

**Comment by goyney** [comment]
Please provide an example of what you're looking for. Thanks.

**Comment by Mariusthvdb** [comment]
ok thanks.
Id suggest adhering to the other brightness icons like brightness-auto, and replay the A with a % ?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/49026775-b62d8a80-f16c-11e8-972e-f04196d0801c.png)
[brightness-percent.svg.zip](https://github.com/Templarian/MaterialDesign/files/2616406/brightness-percent.svg.zip)

**Comment by Mariusthvdb** [comment]
cool, thanks!

**Comment by goyney** [comment]
Sidenote: a version of this icon already exists. It is called `sale`. However, the octagram is different from the `brightness-*` icons.

[![sale](https://materialdesignicons.com/icon/sale)](https://materialdesignicons.com/icon/sale)

**Comment by Templarian** [comment]
Decided to just add it as `brightness-percent`.
