### ISSUE TITLE
work-outline

### ISSUE THREAD

**Issue by Ankhwatcher** [Templarian/MaterialDesign#3738]
I'm working on a Wear OS project and I would like an outline version of the work icon for ambient mode.

![selection_138](https://user-images.githubusercontent.com/260021/49029326-3ae3cd00-f19c-11e8-8dc5-2d844abcfa52.png)

**Comment by Ankhwatcher** [comment]
And it turns out that image alias's to briefcase and that has an outline version so never mind.

**Comment by goyney** [comment]
Use `briefcase-outline`.

[![briefcase-outline](https://materialdesignicons.com/icon/briefcase-outline)](https://materialdesignicons.com/icon/briefcase-outline)

**Comment by Templarian** [comment]
@Ankhwatcher Alias added. 😃
