### ISSUE TITLE
Technet Icon

### ISSUE THREAD

**Issue by tscholze** [Templarian/MaterialDesign#374]
A icon of the [Microsoft Technet](https://technet.microsoft.com/en-us/?f=255&MSPPError=-2147217396) would be great. I lot of people contribute to the forums, blogs and examples but there is no 'icon' to build a link. (Like for github profile, Facebook profile etc.)

**Comment by Templarian** [comment]
What is the technet logo? I don't actually see one on their site.

**Comment by tscholze** [comment]
Hi, thanks for your follow up.
There is no 'real' Technet-Logo. But maybe a Icon with the TN (as the favicon) might work as well? I think the TN-Logo had a lighlty curved Font, some years ago.

**Comment by Templarian** [comment]
I'm going to close this as they don't have a logo. I like technet, but there are probably better ways to represent it than a generic TN icon.
