### ISSUE TITLE
UPDATE: credit-card

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3740]
BREAKING CHANGES

The current credit card icons are technically the outlined versions.

*Rename:*
- [ ] `credit-card` => `credit-card-outline`
- [ ] `credit-card-multiple` => `credit-card-multiple-outline`
- [ ] `credit-card-off` => `credit-card-off-outline`
- [ ] `credit-card-plus` => `credit-card-plus-outline`
- [ ] `credit-card-refund` => `credit-card-refund-outline`
- [ ] `credit-card-scan` => `credit-card-scan-outline`
- [ ] `credit-card-settings` => `credit-card-settings-outline`

*Add:*
- [ ] `credit-card`
- [ ] `credit-card-multiple`
- [ ] `credit-card-off`
- [ ] `credit-card-plus`
- [ ] `credit-card-refund`
- [ ] `credit-card-scan`
- [ ] `credit-card-settings`
- [x] `credit-card-minus`
- [x] `credit-card-minus-outline`
- [x] `credit-card-remove`
- [x] `credit-card-remove-outline`

![image](https://user-images.githubusercontent.com/4528551/49047246-0e2bb780-f194-11e8-9f31-72f012fe315b.png) ![image](https://user-images.githubusercontent.com/4528551/49047318-5054f900-f194-11e8-87e1-8ea3fa17aae1.png) ![image](https://user-images.githubusercontent.com/4528551/49047330-61056f00-f194-11e8-8078-0bf058573d4b.png) ![image](https://user-images.githubusercontent.com/4528551/49047353-75496c00-f194-11e8-9ba6-66a6c6f40805.png) ![image](https://user-images.githubusercontent.com/4528551/49047433-a9249180-f194-11e8-8f39-81ef7e246ae0.png)
 ![image](https://user-images.githubusercontent.com/4528551/49047492-d40ee580-f194-11e8-9262-2acfd7e48345.png) ![image](https://user-images.githubusercontent.com/4528551/49047514-e557f200-f194-11e8-87b3-7a71e482ccf3.png)

New

![image](https://user-images.githubusercontent.com/4528551/49047466-bfcae880-f194-11e8-9040-4905d94e8dc4.png) ![image](https://user-images.githubusercontent.com/4528551/49047300-40d5b000-f194-11e8-9968-7e9ff576b7de.png)

---

[credit-card.zip](https://github.com/Templarian/MaterialDesign/files/2617617/credit-card.zip)

**Comment by goyney** [comment]
We'll also need to add outline versions of `minus` and `remove` since those do not currently exist.

**Comment by goyney** [comment]
The four non-breaking icons have been added.
[![credit-card-minus](https://materialdesignicons.com/icon/credit-card-minus)](https://materialdesignicons.com/icon/credit-card-minus)[![credit-card-minus-outline](https://materialdesignicons.com/icon/credit-card-minus-outline)](https://materialdesignicons.com/icon/credit-card-minus-outline)
[![credit-card-remove](https://materialdesignicons.com/icon/credit-card-remove)](https://materialdesignicons.com/icon/credit-card-remove)[![credit-card-remove-outline](https://materialdesignicons.com/icon/credit-card-remove-outline)](https://materialdesignicons.com/icon/credit-card-remove-outline)

**Comment by goyney** [comment]
All done!

**Comment by goyney** [comment]
Also noticed we were missing `credit-card-marker` and `credit-card-wireless`, so those are now included so we have a full set.
