### ISSUE TITLE
Remove Remaining Variant Settings Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3741]
Leaving this here as a reminder for ourselves. We're currently monitoring whether or not Google are going to start adding more settings icons that use `cog` instead of `settings-helper` as the modifier (there's currently **a** version of our old `account-settings-variant`, which was removed in #3413, out there); if they don't then we should remove the rest of our `*-settings-variant` icons.

- [ ] `cellphone-settings-variant`
- [ ] `message-settings-variant`

**Comment by MrGrigri** [comment]
I would disagree with `message-settings-variant` as it was created to not confuse the user that someone is typing. See #1724 for the discussion.

**Comment by JamesCoyle** [comment]
I personally feel at this point we should keep what we have and evaluate new icons on a case by case basis. I don't think it hurts having the three dots variants as they can still be used to indicate a menu will open when clicked.

**Comment by goyney** [comment]
We've recently added new settings type icons with the three dots, so I'm going to agree with @JamesCoyle and say we handle each settings-type icon on a case-by-case basis.
