### ISSUE TITLE
flag-modifiers-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3742]
This is to go along with #3556 as outlined variants...again, I forgot to do these with the original issue.

![image](https://user-images.githubusercontent.com/4528551/49111957-c027ba00-f24e-11e8-9b1d-6d97353be3db.png) ![image](https://user-images.githubusercontent.com/4528551/49111976-d2095d00-f24e-11e8-92d9-988d3e50ac6c.png) ![image](https://user-images.githubusercontent.com/4528551/49112010-e2213c80-f24e-11e8-9d58-56bd5ea2bcaf.png)

---

[flag-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2621879/flag-modifiers.zip)

**Comment by CoDEmanX** [comment]
Hm, the first two might look better with a circular cutout. Did you try that locally?

**Comment by MrGrigri** [comment]
I did, but I'm a fan of using straight cutouts with outlined versions of icons, or if it's only cutting out of a 2-pixel stroke.

**Comment by goyney** [comment]
These will all need to be updated to match the updated path data from Google's outlined version. See https://github.com/Templarian/MaterialDesign/issues/3978 for more information.

Removing the `Contribution` label and Milestone until they are updated.

**Comment by MrGrigri** [comment]
UPDATED

![image](https://user-images.githubusercontent.com/4528551/62717369-feba6a80-b9c0-11e9-8448-48e76953a6a1.png) ![image](https://user-images.githubusercontent.com/4528551/62717396-0bd75980-b9c1-11e9-841a-43dd6a3f3e81.png) ![image](https://user-images.githubusercontent.com/4528551/62717453-28739180-b9c1-11e9-8ad5-7af3232500a6.png)

---
#### Files
[flag-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/3482573/flag-modifiers.zip)

**Comment by CoDEmanX** [comment]
Shouldn't the gaps be smaller, like this?

![grafik](https://user-images.githubusercontent.com/1309249/62738798-7aed9600-ba33-11e9-985f-0f0da6306b12.png)

**Comment by JamesCoyle** [comment]
Shouldn't they use the standard round cutout like the filled versions?

**Comment by MrGrigri** [comment]
I thought that at 1x the plus and remove modifiers were too close to the flag cutout.

**Comment by goyney** [comment]
[![flag-plus](https://materialdesignicons.com/icon/flag-plus)](https://materialdesignicons.com/icon/flag-plus)[![flag-minus](https://materialdesignicons.com/icon/flag-minus)](https://materialdesignicons.com/icon/flag-minus)[![flag-remove](https://materialdesignicons.com/icon/flag-remove)](https://materialdesignicons.com/icon/flag-remove)
