### ISSUE TITLE
sign-direction-modifiers

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3744]
In a project I'm working on I'm needing an icon to represent 'creating a new version'. So I've used to conventional `sign-direction` icon with the `add` modifier to represent this. I figured this could be useful for some so I've created all three modifiers. 

If they are not needed, then just reject this issue.

![image](https://user-images.githubusercontent.com/4528551/49171055-df7c2100-f2fa-11e8-9a6a-67b22f13c0e9.png) ![image](https://user-images.githubusercontent.com/4528551/49171065-e73bc580-f2fa-11e8-9586-1879fd1808cb.png) ![image](https://user-images.githubusercontent.com/4528551/49171076-ef940080-f2fa-11e8-9c92-a1e0a9bc415c.png)

---

[sign-direction-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2626019/sign-direction-modifiers.zip)

**Comment by MrGrigri** [comment]
For reference that issue is #3129

**Comment by MrGrigri** [comment]
As a side note, I prefer our current `sign-direction` over the proposed in the other issue.

**Comment by goyney** [comment]
[![sign-direction-plus](https://materialdesignicons.com/icon/sign-direction-plus)](https://materialdesignicons.com/icon/sign-direction-plus)[![sign-direction-minus](https://materialdesignicons.com/icon/sign-direction-minus)](https://materialdesignicons.com/icon/sign-direction-minus)
[![sign-direction-remove](https://materialdesignicons.com/icon/sign-direction-remove)](https://materialdesignicons.com/icon/sign-direction-remove)
