### ISSUE TITLE
Carpool

### ISSUE THREAD

**Issue by systect** [Templarian/MaterialDesign#3748]
Based on the car icon, I suggest a carpool icon, e.g. showing two heads in the car, like e.g.:

![image](https://user-images.githubusercontent.com/45437612/49278476-3281df80-f485-11e8-963b-1c8598dd3a88.png)

**Comment by MrGrigri** [comment]
MD Guidelines specifically state not to do this. Is there another way that you can think of to represent this?

![image](https://user-images.githubusercontent.com/4528551/49297573-5db20200-f478-11e8-9e9c-3b74271a4322.png)

**Comment by MrGrigri** [comment]
Another commonality in the US is the black diamond for carpool lanes. We do have `card-diamond`, but not `card-diamond-outline` which would be more appropriate. Would that work?

[![card-diamond](https://materialdesignicons.com/icon/cards-diamond)](https://materialdesignicons.com/icon/cards-diamond)

--

[![image](https://user-images.githubusercontent.com/4528551/49298386-7a4f3980-f47a-11e8-93d6-2959fdd6aef7.png)](https://github.com/Templarian/MaterialDesign/files/2633935/card-diamond-outline.zip)

**Comment by systect** [comment]
Oh, didn‘t know. Could you share the reference, as I can‘t find this specific guideline? Thx!

The diamond symbol is rather unknown in Europe, I‘d say, at least in Germany and France. But a car with multiple people is used e.g. on French parking signage, so it seems to represent carpooling in a very understandable manner IMHO. (See e.g. https://fr.m.wikipedia.org/wiki/Covoiturage)

So, I personally would not agree with the guidelines in this specific case, but I these are just my five cents.

**Comment by MrGrigri** [comment]
The image is a link, so just click on it and it'll take you to the guidelines.

**Comment by JamesCoyle** [comment]
I don't feel like that guideline applies here. In this case the second person isn't adding to the complexity of the icon as it is required. I believe Google are saying not to add unnecessary details where they are not required.

**Comment by MrGrigri** [comment]
What about `account-multiple-plus`?

[![account-multiple-plus](https://materialdesignicons.com/icon/account-multiple-plus)](https://materialdesignicons.com/icon/account-multiple-plus)

**Comment by systect** [comment]
The guidelines explicitly uses this icon to illustrate the rule.

Though I‘d state somewhat more explicitly in this guideline, that human elements should not be added to illustrate a ‚car’ (what I think, is intended). Or find another representation of unneeded complexity added by human elements.

As an icon for a carpool, these elements not only amplify the meaning, but they are essential, IMHO.

Could someone (Google?) clarify?

**Comment by MrGrigri** [comment]
I believe that the detail is lost at 1x and as such pushes my opinion to `account-multiple-plus` for outside the US and `cards-diamond-outline` for inside the US.

[![image](https://user-images.githubusercontent.com/4528551/49303424-e0da5480-f486-11e8-8241-05c367f5b0b0.png)](https://github.com/Templarian/MaterialDesign/files/2634276/carpool.zip)

**Comment by systect** [comment]
To me, account-multiple-plus seems not appropriate, as the + usually signifies an ‚Add‘ action not intended here and it would not relate to a car in any way.

I see the detail issue.

**Comment by PeterShaggyNoble** [comment]
Would one of the `account-multiple` or `account-group` icons without a modifier not work in context?

**Comment by hbruch** [comment]
In my context, I'd not use account-multiple or account-group. Think of a trip description as below, where the user would not get the meaning of the account icons IMHO:
![image](https://user-images.githubusercontent.com/2187389/49695136-74eaa100-fb96-11e8-9f32-f2ca2ba70083.png)

If the detail is lost at 1x, one might consider leaving out the person's shoulder and enlarge the heads a bit(?). I'd ask not to close this request for now.

**Comment by PeterShaggyNoble** [comment]
Maybe I'm missing exactly what that's trying to convey ("carpooling" isn't a thing here) but would `car` itself not suffice?

**Comment by hbruch** [comment]
This is the directions overview of our journey planner, which returns intermodal connections, including carpool and public transit legs. We want to show carpool (riding) legs and self-driving legs differently, i.e. a carpool icon for carpooling, and `car` for self-driving.

**Comment by goyney** [comment]
Here's a different take on it:
![image](https://user-images.githubusercontent.com/1015040/50697595-aaa56d00-1010-11e9-81dc-6345e6cda20c.png)

[carpool.svg.zip](https://github.com/Templarian/MaterialDesign/files/2727592/carpool.svg.zip)

---

Idea is from a HOV lane sign on I5:
![image](https://user-images.githubusercontent.com/1015040/50697611-b5600200-1010-11e9-8027-80598d69015d.png)

**Comment by goyney** [comment]
Or we can go super-simplistic since it seems "HOV" is a recognizable term worldwide ([inferred from this wikipedia article](https://en.wikipedia.org/wiki/High-occupancy_vehicle_lane)).

![image](https://user-images.githubusercontent.com/1015040/50698277-7763dd80-1012-11e9-918d-ac5d887a35e8.png)

[hov.svg.zip](https://github.com/Templarian/MaterialDesign/files/2727623/hov.svg.zip)

**Comment by MrGrigri** [comment]
Idk about adding `hov`. I do like the `car-2-plus` icon. I believe that one, plus the `cards-diamond-outline` should be added.

**Comment by goyney** [comment]
It looks like in some countries, they have a 2+ or 3+ limit on their carpool lanes, so here's the 2+ one from above and an additional 3+ one in case we want to go this route.

![image](https://user-images.githubusercontent.com/1015040/50698870-32d94180-1014-11e9-952f-f6daaf3e7ad5.png)![image](https://user-images.githubusercontent.com/1015040/50698882-3a98e600-1014-11e9-9b7a-67f1a7189df7.png)

[carpool.zip](https://github.com/Templarian/MaterialDesign/files/2727674/carpool.zip)

**Comment by CoDEmanX** [comment]
Never heard of HOV. I like the 2+ / 3+ but my girlfriend did not recognize it as carpool icon (her guess was that it would indicate how many cars can be parked).

**Comment by goyney** [comment]
Honestly, I do not think there is one specific icon that will indicate "carpool." Even the original proposal with two people in it doesn't really specifically mean carpool. A combination of the diamond and a 2/3+ might be enough. But really, his icon is going to depend on the context in which it is used.

**Comment by PeterShaggyNoble** [comment]
I think the car would work better than the diamond as far as international recognition goes but context is still going to be the key factor in them being interpreted properly.

**Comment by goyney** [comment]
[![cards-diamond-outline](https://materialdesignicons.com/icon/cards-diamond-outline)](https://materialdesignicons.com/icon/cards-diamond-outline)

**Comment by goyney** [comment]
[![car-2-plus](https://materialdesignicons.com/icon/car-2-plus)](https://materialdesignicons.com/icon/car-2-plus)[![car-3-plus](https://materialdesignicons.com/icon/car-3-plus)](https://materialdesignicons.com/icon/car-3-plus)
