### ISSUE TITLE
speaker-multiple

### ISSUE THREAD

**Issue by Stark003** [Templarian/MaterialDesign#3749]
![baseline_speaker_group_black_48dp](https://user-images.githubusercontent.com/32213671/49322753-76004a80-f566-11e8-888a-6b48c5267dd6.png)

**Comment by MrGrigri** [comment]
I'm not a fan of how tall this is...but here is the SVG.

[![image](https://user-images.githubusercontent.com/4528551/49384903-49b90b00-f6d9-11e8-9eb9-1e6115d5afd9.png)](https://github.com/Templarian/MaterialDesign/files/2640171/speaker-multiple.zip)

**Comment by Templarian** [comment]
[![speaker-multiple](https://materialdesignicons.com/icon/speaker-multiple)](https://materialdesignicons.com/icon/speaker-multiple)
