### ISSUE TITLE
baby-buggy-off / child-friendly-off

### ISSUE THREAD

**Issue by Webifi** [Templarian/MaterialDesign#3750]
There's currently a "baby-buggy" icon (alias: child-friendly)

It would be nice to have "off" (slash through) version to signify as not-child-friendly

**Comment by MrGrigri** [comment]
[![baby-buggy-off.zip](https://user-images.githubusercontent.com/4528551/49385148-f09da700-f6d9-11e8-8d3c-8c1df177e2d6.png)](https://github.com/Templarian/MaterialDesign/files/2640196/baby-buggy-off.zip)

**Comment by PeterShaggyNoble** [comment]
Hmm ... should we rename this one; it looks more like a pram than a buggy to me.

**Comment by MrGrigri** [comment]
I believe there is a language conflict here...even in English.

**Comment by Webifi** [comment]
In the US, "baby carriage" would be used more often to describe the old-school type baby stroller (as depicted  in the icon).  "Stroller" is the more common name here.  We don't really use "pram" here.  Can't think of a time I heard them called a "buggy".

**Comment by MrGrigri** [comment]
If we rename these, it should be `baby-carriage` and `baby-carriage-off`, with the aliases of `stroller` and `pram`.

**Comment by JamesCoyle** [comment]
And probably buggy too

**Comment by MrGrigri** [comment]
The list was updated.

**Comment by PeterShaggyNoble** [comment]
So chips aren't chips, jelly isn't jelly, biscuits aren't biscuits and now a pram isn't a pram? How does America survive like this?! 😝

**Comment by Webifi** [comment]
We survive spelling canceled wrong!

**Comment by goyney** [comment]
`baby-buggy-off` added.
[![baby-buggy-off](https://materialdesignicons.com/icon/baby-buggy-off)](https://materialdesignicons.com/icon/baby-buggy-off)

Leaving this open until `3.9.x` drops, then we can do the rename. Also labeling this `Breaking Changes`.

**Comment by goyney** [comment]
Aliases added.
