### ISSUE TITLE
Hubspot

### ISSUE THREAD

**Issue by wkeizer** [Templarian/MaterialDesign#3753]
![hubspotlogo](https://user-images.githubusercontent.com/5119313/49379481-84d63100-f70f-11e8-9e4f-03cf52e8c0dd.png)

**Comment by PeterShaggyNoble** [comment]
Sorry but that brand is currently beyond the scope of this project but we may revisit it if we ever release a dedicated icon pack for brands.

In the meantime, I'd recommend trying [Simple Icons](https://simpleicons.org) instead.

**Comment by Templarian** [comment]
Been a little swamped. Agreed, Hubspot falls outside of social media, but I would say it's so large it's worthwhile to have as an icon. Next to wordpress it's probably the next largest platform business use for their CMS.

**Comment by wkeizer** [comment]
Thanks guys. As HS is a widely used alternative for SalesForce (which does have an icon in the library). Therefore lot's of apps have integrations with HS.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50038164-09b32b80-ffe9-11e8-9a30-c9bba9276001.png)
[hubspot.svg.zip](https://github.com/Templarian/MaterialDesign/files/2682348/hubspot.svg.zip)

**Comment by Templarian** [comment]
[![hubspot](https://materialdesignicons.com/icon/hubspot)](https://materialdesignicons.com/icon/hubspot)
