### ISSUE TITLE
Outlined Alert Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3755]
These are the last 4 outlined `alert-*`  icons that need to be added to complete the set. They'll also need to be aliased as `warning-*`. The spacing in the octagram one isn't right but I don't know what the best solution would be to get around it.

[![alert-box-outline](https://user-images.githubusercontent.com/15157491/49439049-ee117f00-f7b7-11e8-8cff-c2fc3395ca0f.png)](https://github.com/Templarian/MaterialDesign/files/2643744/alert-box-outline.zip) [![alert-decagram-outline](https://user-images.githubusercontent.com/15157491/49439373-beaf4200-f7b8-11e8-9d7d-2cca30951ff2.png)](https://github.com/Templarian/MaterialDesign/files/2643764/alert-decagram-outline.zip)

[![alert-octagon-outline](https://user-images.githubusercontent.com/15157491/49439221-60825f00-f7b8-11e8-88ca-8adb32315b59.png)](https://github.com/Templarian/MaterialDesign/files/2643756/alert-octagon-outline.zip) [![alert-octagram-outline](https://user-images.githubusercontent.com/15157491/49439525-2cf40480-f7b9-11e8-86c7-1681fa1623e7.png)](https://github.com/Templarian/MaterialDesign/files/2643772/alert-octagram-outline.zip)

**Comment by Templarian** [comment]
Added these.
