### ISSUE TITLE
Aliases to be removed (v3.3.xx)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3756]
**Please keep this issue updated with any additional aliases to be removed up to the release of v3.3.xx**

- [x] `alpha-b-circle`: `alphabet-b-circle` (Duplicate)
- [x] `alpha-b-circle`: `letter-b-circle` (Duplicate)
- [x] `emoticon-cool-outline`: `smiley-cool` (Icon was renamed)
- [x] `emoticon-dead-outline`: `smiley-dead` (Icon was renamed)
- [x] `emoticon-devil-outline`: `smiley-devil` (Icon was renamed)
- [x] `emoticon-excited-outline`: `smiley-excited` (Icon was renamed)
- [x] `emoticon-happy-outline`: `smiley-happy` (Icon was renamed)
- [x] `emoticon-neutral-outline`: `smiley-neutral` (Icon was renamed)
- [x] `emoticon-outline`: `smiley` (Icon was renamed)
- [x] `emoticon-sad-outline`: `smiley-sad` (Icon was renamed)
- [x] `format-list-numbered`: `format-list-numbered` (Icon was renamed)
- [x] `resize-bottom-right`: `drag` (Duplicate)
- [x] `shield-airplane`: `aeroplane-shield` (Icon was renamed)

**Comment by Templarian** [comment]
Fixed. 😃
