### ISSUE TITLE
local_stadium

### ISSUE THREAD

**Issue by henriquecm** [Templarian/MaterialDesign#3757]
This version is based on the stadium pin from the google maps.

![local_stadium](https://user-images.githubusercontent.com/15136037/49447631-2d42ce80-f7be-11e8-8949-bf1912f87aef.png)

![stadium_pinlet-2-medium](https://user-images.githubusercontent.com/15136037/49447569-05ec0180-f7be-11e8-9c2e-0a96b1bcf36c.png)

[local_stadium.zip](https://github.com/Templarian/MaterialDesign/files/2644307/local_stadium.zip)

**Comment by PeterShaggyNoble** [comment]
I like it. But I don't think the gaps on the right work, especially at native size. How would it look with that portion completely filled? Also should the gate and screens (I assume they are) have rounded corners?

**Comment by MrGrigri** [comment]
I would fill in the gaps, but the gate and screen should remain as is. Because they are small and would appear round.

**Comment by goyney** [comment]
Here it is with the filled back half.
![image](https://user-images.githubusercontent.com/1015040/62001582-e47bb500-b0c1-11e9-8def-36395dd7709a.png)
[local_stadium.svg.zip](https://github.com/Templarian/MaterialDesign/files/3438815/local_stadium.svg.zip)

We already have a community-based `stadium`, so this will update that one. We need to decide whether or not to add the current `stadium` as a variant.

**Comment by goyney** [comment]
[![stadium](https://materialdesignicons.com/icon/stadium)](https://materialdesignicons.com/icon/stadium)
