### ISSUE TITLE
Hearing Aid Device

### ISSUE THREAD

**Issue by senolsenturk77** [Templarian/MaterialDesign#3759]
Can you add Hearing Aid device icon with connect and disconnect to computer state and enable/disable Bluetooth function on Hearing Aid device as Icon

**Comment by PeterShaggyNoble** [comment]
For reference: [search results from The Noun Project for "hearing aid"](https://thenounproject.com/search/?q=hearing%20aid).

Would our existing `ear-hearing` icon be suitable as the base icon for this?

![ear-hearing](https://user-images.githubusercontent.com/15157491/49531980-6d37ad80-f8b3-11e8-8d74-bd6554c83bc6.png)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @senolsenturk77, if `ear-hearing` doesn't suit your needs please provide an example of what you're looking for and reopen this issue.
