### ISSUE TITLE
Currency: Turkish Lira (try) Icon

### ISSUE THREAD

**Issue by bcinarli** [Templarian/MaterialDesign#376]
Is it possible to add Turkish Lira currency icon. The symbole is ₺ in unicode

- [x] currency-try
- [ ] currency-turkish-lira

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/currency-try

**Comment by bcinarli** [comment]
Thanks for very quick response. Btw, I'm bundling MDI in https://github.com/bcinarli/doctro default template :)

**Comment by Templarian** [comment]
Cool. always nice to see other projects using the icons. I should have an updated webfont out soon. Maybe tonight if I get around to it.
