### ISSUE TITLE
Review icons with point data outside the viewBox

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3760]
Looks like [I spoke too soon](https://github.com/Templarian/MaterialDesign/issues/2624#issuecomment-347205101); following on from [this issue](https://github.com/PeterShaggyNoble/MDI-Sandbox/issues/15) I ran the script I used again to see if there were any icons that had been added since that broke out of the `viewBox` but I discovered a bug in it that had prevented it from checking if the icon broke the left or top boundary. After fixing it, I discovered the following icons that do so, plus a couple of newer icons that break the right or bottom boundary.

I didn't get time to check the point data of all the icons but, in the couple I did look it, the offending point is part of a `C`urve command so it may be that no fixes are needed here but we should review them all anyway.

- [x] `account-clock`
- [x] `air-conditioner`
- [x] `android`
- [x] `border-color`
- [x] `edge`
- [x] `pirate`
- [x] `pistol`
- [x] `shovel`
- [x] `shovel-off`
- [x] `xbox-controller-battery-alert`
- [x] `xbox-controller-battery-charging`
- [x] `xbox-controller-battery-empty`
- [x] `xbox-controller-battery-full`
- [x] `xbox-controller-battery-low`
- [x] `xbox-controller-battery-medium`
- [x] `xbox-controller-battery-unknown`
- [x] `xda`

**Comment by goyney** [comment]
The only icon above that breaks the 24dp box is `xda`, by `0.05`. Worth fixing or nah?

**Comment by goyney** [comment]
Fixed `xda`.
