### ISSUE TITLE
Kick/Push Scooter

### ISSUE THREAD

**Issue by walbell** [Templarian/MaterialDesign#3762]
Would it be possible to have a kick scooter icon?

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/50807319-e453cd80-12c7-11e9-85d9-c3271988c994.png)

**Comment by thehaxxa** [comment]
Would find this icon useful +1

**Comment by Templarian** [comment]
[![scooter](https://materialdesignicons.com/icon/scooter)](https://materialdesignicons.com/icon/scooter)
