### ISSUE TITLE
sign-real-estate

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3763]
Not sure if we want to add this or not...but here it is. Thoughts?

[![image](https://user-images.githubusercontent.com/4528551/49666236-a3d90980-fa14-11e8-956c-c86d9dcca821.png)](https://github.com/Templarian/MaterialDesign/files/2658415/sign-real-estate.zip)

**Comment by PeterShaggyNoble** [comment]
Hmm ... this may be too region-specific. Estate agents signs in Ireland, for example, (and I think the UK, too) are generally placards or signposts. And in Spain, from my experience, private properties up for sale usually just have a sign on their wall.

**Comment by MrGrigri** [comment]
I would disagree. I understand that this is an international pack, however, there are a lot of users here in the US and it's a very common sign. IMO, region-specific is more like Afghanistan asking for an icon to represent a Pakol. They are used everywhere in Afghanistan, and everyone would recognize it. However, not many people who use the pack would.

**Comment by goyney** [comment]
I like it and instantly recognize its meaning, but I don't know how I feel about the round terminators. What if you used a point at the left corner (like our existing `sign` variants) and a square terminator on the right side (or some other variation)?

**Comment by Templarian** [comment]
I think most will understand it's use in context, so it should be fine. It can be also used for other sign related things.

May want to add the little footing shape at the bottom like we have on other `sign` icons.

**Comment by JamesCoyle** [comment]
I'm not a fan of the rounded ends but otherwise I think it works well.

**Comment by CoDEmanX** [comment]
I would shift the sign 1dp to the right perhaps

**Comment by goyney** [comment]
[![sign-real-estate](https://materialdesignicons.com/icon/sign-real-estate)](https://materialdesignicons.com/icon/sign-real-estate)

**Comment by douira** [comment]
I think it would be more recognizable with two little connecting lines between the pole and the sign.
![68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f7369676e2d7265616c2d657374617465](https://user-images.githubusercontent.com/17120022/62828687-b7b0bd00-bbec-11e9-928b-558e4e323559.png)
