### ISSUE TITLE
Google-Artist-Outline

### ISSUE THREAD

**Issue by TobiiAtGitHub** [Templarian/MaterialDesign#3764]
Hey, I need the "artist" icon by Google in the outlined theme as a Vector Drawable.
I tried it by myself but unfortunately I wasn't able to create a Vector Drawable, only a PNG. :(
I appreciate every help!

This is the PNG I got:
![artist](https://user-images.githubusercontent.com/45732091/49696913-3dd5b900-fbb1-11e8-87cb-f2d893bcd935.png)

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/49701647-7fcd2200-fbe6-11e8-97b9-cf672d613840.png)![](https://user-images.githubusercontent.com/15905797/49701643-73e16000-fbe6-11e8-8ed6-47c1cd443f89.png)
[artist-outline.zip](https://github.com/Templarian/MaterialDesign/files/2660912/artist-outline.zip)

We'll have to go with the one on the left.

**Comment by TobiiAtGitHub** [comment]
Thank you very much! :D

**Comment by Templarian** [comment]
@GreenTurtwig We've been trying to not go with the crunched torso in the outline versions. Same design as yours, but with the `account-outline` as the starting point.

[![artist-outline](https://materialdesignicons.com/icon/artist-outline)](https://materialdesignicons.com/icon/artist-outline)

**Comment by Templarian** [comment]
Also updated the point count for `artist` to remove 3 of the unnecessary points. 🙃
