### ISSUE TITLE
home-import, home-export

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3765]
HI Please consider creating a home-import and home-export. I would love to use that for power production or consumption schemes.

Right now I use the import and export icons, but these don't reference the house/home.

I could use the home-plus and home-minus, but I feel the arrow entering/leaving a Home would be better for providing visual clue to action.

I'll post my current card for solar energy production/consumption below:

home-production
![schermafbeelding 2018-12-10 om 11 55 35](https://user-images.githubusercontent.com/33354141/49729060-ae91d980-fc74-11e8-9b5c-497a97f5ff86.jpg)

home-consumption
![schermafbeelding 2018-12-10 om 12 11 37](https://user-images.githubusercontent.com/33354141/49729119-dbde8780-fc74-11e8-858a-c025539705e0.jpg)

thx for considering.

**Comment by PeterShaggyNoble** [comment]
Would it work with the arrows in the bottom right of the standard `home` icon?

We'd probably need to call those `home-arrow-left/right` for consistency with existing icons.

**Comment by goyney** [comment]
[![home-import-outline](https://materialdesignicons.com/icon/home-import-outline)](https://materialdesignicons.com/icon/home-import-outline)[![home-export-outline](https://materialdesignicons.com/icon/home-export-outline)](https://materialdesignicons.com/icon/home-export-outline)
