### ISSUE TITLE
dishwasher inconsistent with other appliances?

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3766]
Sorry if this is been answered before, and I am aware of the google icon https://github.com/Templarian/MaterialDesign/issues/2313 but would it be possible to make the dishwasher consistent with the other kitchen/household appliances? 

The dishwasher is wider than the others, and seems off because of that:

![schermafbeelding 2018-12-10 om 12 17 52](https://user-images.githubusercontent.com/33354141/49729544-15fc5900-fc76-11e8-81fc-fdd23af5ee5b.jpg)

Might not be world standard but the size of the dryer/washing machine is consistent with real life default dimensions h85xw60 cm, the dishwasher is unseen here....(Europe/continental) ;=)

Also, the waterdrup isn't very helpful deciding whether it is a dishwasher or a washing machine....

the mockup with knife and fork seems perfect ?

https://github.com/Templarian/MaterialDesign/issues/2313#issuecomment-320541620

**Comment by MrGrigri** [comment]
LIke this?

[![image](https://user-images.githubusercontent.com/4528551/49745768-f278e480-fc5c-11e8-90db-e952a561da3d.png)](https://github.com/Templarian/MaterialDesign/files/2663943/dishwasher.zip)

**Comment by Mariusthvdb** [comment]
yes, the size is much more consistent with the others now. thanks!

could you maybe change the square with the drop, in to a circle with cutlery or knife and fork? (one of the silverware icons?) or maybe create two dishes? It is a dishwasher after all ;-) I you'd make that somewhat diagonal, it would be even more consistent with the other 2 machines washing machine and dryer.

**Comment by Templarian** [comment]
Should we add an filled/outline where the bottom is filled in?

**Comment by Templarian** [comment]
I'm fine adding this a compact, but changing the shape of the dishwasher seems weird.

**Comment by Mariusthvdb** [comment]
please do, add as compact, ty!

could you try an use the silverware also? like: 

![](https://user-images.githubusercontent.com/18021678/29008285-6ddd5cbc-7ae2-11e7-89db-64d3c63b0e5e.png)

would be amazing if possible.

**Comment by JamesCoyle** [comment]
I much prefer ^ that one tbh. It's more like the dishwashers I've ever used and is more consistent with the existing icons.

**Comment by MrGrigri** [comment]
The first one uses the water drop and the second one uses the silverware. My fear is that the silverware is lost at 1x.

![image](https://user-images.githubusercontent.com/4528551/49822031-30e3d180-fd39-11e8-8fe4-e453bfdc7370.png) ![image](https://user-images.githubusercontent.com/4528551/49821965-0a259b00-fd39-11e8-83f6-01968f9b9b67.png)

---

[dishwasher.zip](https://github.com/Templarian/MaterialDesign/files/2668840/dishwasher.zip)

**Comment by Mariusthvdb** [comment]
So Nice! Exactly what I would have hoped for. Understand your concern though. Maybe the original silverware set of crossed spoon and knife would be more robust on that small size ?

**Comment by goyney** [comment]
I believe narrowing the dishwasher to match the other appliance's width is a good change, but I would vote against the silverware variant and stick with the water drop.

**Comment by Templarian** [comment]
[![dishwasher](https://materialdesignicons.com/icon/dishwasher)](https://materialdesignicons.com/icon/dishwasher)

Agreed this will be the best. The silverware one is a bit much.
