### ISSUE TITLE
heart-broken-outline Icon

### ISSUE THREAD

**Issue by gurupras** [Templarian/MaterialDesign#3767]
There are `heart` and `heart-outline` icon which make it very easy to show states that could be toggled.
Could we get a `heart-broken-outline` similar to `heart-broken`?

Here's the result of my two-minute edit of the existing `heart-broken` icon.
It seemed pretty easy to remove the fill and stroke the path on Inkscape, but I don't know if it matches your standards/requirements.

![heart-broken-outline](https://user-images.githubusercontent.com/2933207/49769250-735fcc80-fcad-11e8-8dc8-1ed64de1787e.png)

**Comment by goyney** [comment]
Here's two options:
![image](https://user-images.githubusercontent.com/1015040/50038086-de7c0c80-ffe7-11e8-8972-85c8d779e247.png)![image](https://user-images.githubusercontent.com/1015040/50038114-4b8fa200-ffe8-11e8-9956-dda6814bc6bc.png)

[heart-broken-outline.zip](https://github.com/Templarian/MaterialDesign/files/2682343/heart-broken-outline.zip)

**Comment by PeterShaggyNoble** [comment]
My vote goes to the first one.

**Comment by Templarian** [comment]
[![heart-broken-outline](https://materialdesignicons.com/icon/heart-broken-outline)](https://materialdesignicons.com/icon/heart-broken-outline)
