### ISSUE TITLE
two new icons. Vibrate with 1 in the box and vibrate with 2 in the box. 

### ISSUE THREAD

**Issue by dnl20** [Templarian/MaterialDesign#3768]
like this: 

![vibraten1_1](https://user-images.githubusercontent.com/6676832/49856921-6d730400-fdf1-11e8-9c2c-05cf0e5ee09c.png)
![vibraten2_1](https://user-images.githubusercontent.com/6676832/49856922-6d730400-fdf1-11e8-932a-2a4626fb20ac.png)

**Comment by goyney** [comment]
I don't believe we'd be interested in adding numbers to random icons. I will leave this open for now for other Contributors to weigh in.

**Comment by Templarian** [comment]
Agreed this is going to be too niche to add.

@dnl20 Thanks for creating an issue, but some requests are too specific for us to add. Most suggestions need to have a general purpose. Suggest overlaying the number with the vibrate might work for you in this case.

**Comment by PeterShaggyNoble** [comment]
@dnl20, as a quick example, here's what `vibrate` looks like when combined with `numeric-1`.

![](https://user-images.githubusercontent.com/15157491/49931188-39194980-febe-11e8-8199-8c8a2896f2be.png)

**Comment by dnl20** [comment]
@PeterShaggyNoble this is very great!
