### ISSUE TITLE
Update sigma

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3770]
Our `sigma` icon doesn't match any other Greek letters in terms of style, nor does it really look all that Material. This is a proposal to update `sigma` to match the version used in Google Sheets.

![image](https://user-images.githubusercontent.com/1015040/49912125-1273f800-fe57-11e8-87c7-1bf6ef82ca1c.png)
[sigma.zip](https://github.com/Templarian/MaterialDesign/files/2674340/sigma.zip)

---

We would also need to re-attribute this icon to Google.

**Comment by Templarian** [comment]
[![sigma](https://materialdesignicons.com/icon/sigma)](https://materialdesignicons.com/icon/sigma)
