### ISSUE TITLE
Text wrapping

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3771]
From Google Sheets, three icons to toggle text wrapping mode:

![image](https://user-images.githubusercontent.com/1015040/50037639-a7a2f800-ffe1-11e8-8004-6f476a95aae2.png)![image](https://user-images.githubusercontent.com/1015040/50037635-8a6e2980-ffe1-11e8-8e3e-62ea41de59d8.png)
![image](https://user-images.githubusercontent.com/1015040/50037642-b25d8d00-ffe1-11e8-98b6-8da5e3978001.png)

[format-text-wrapping.zip](https://github.com/Templarian/MaterialDesign/files/2682311/format-text-wrapping.zip)

**Comment by Templarian** [comment]
Trying to prioritize some of the stock icon requests for the next release, so we don't fall out of sync.

Added these three.
