### ISSUE TITLE
Update table-merge-cells

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3772]
Our version of `table-merge-cells` that I created in the past does not match the version supplied by Google in Google Sheets. Google uses hard edges instead of rounded.

I propose we update the icon and reattribute it to Google.

![image](https://user-images.githubusercontent.com/1015040/50037802-12086800-ffe3-11e8-9e60-35c221494e73.png)

[table-merge-cells.svg.zip](https://github.com/Templarian/MaterialDesign/files/2682324/table-merge-cells.svg.zip)

**Comment by Templarian** [comment]
Agreed, this doesn't make sense to have round edges.

Updated and assigned to Google.

**Comment by CoDEmanX** [comment]
We can add back the rounded one some time later if we start adding rounded variants for everything.
