### ISSUE TITLE
textbox-variant

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3773]
From Google Slides, a drawable, floating text box. I'm not sure how we should name this, considering we already have `textbox` (which shows a form field text box and cursor).

![image](https://user-images.githubusercontent.com/1015040/50037896-d2428000-ffe4-11e8-8e17-e9a52fe179a4.png)

[text-box.svg.zip](https://github.com/Templarian/MaterialDesign/files/2682336/text-box.svg.zip)

**Comment by Templarian** [comment]
Since `text-box` is kind of a reserved naming convention for us. I'm fine naming it `format-textbox`. Going to add it as that for now.

**Comment by Templarian** [comment]
Added as `format-textbox`. Let me know if this doesn't make sense.
