### ISSUE TITLE
beaker

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3774]
We currently have `beaker`, which is an outlined icon.

- [ ] Rename `beaker` to `beaker-outline`.
- [ ] Add new `beaker`.

![image](https://user-images.githubusercontent.com/1015040/50038508-9ca29480-ffee-11e8-8a94-6770c71a0968.png)

[beaker.svg.zip](https://github.com/Templarian/MaterialDesign/files/2682371/beaker.svg.zip)

**Comment by Templarian** [comment]
Added / Updated.
