### ISSUE TITLE
Update Fedora Brand Icon

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3776]
As the community waits for Fedora to provide an official icon we'll be continuing using the current icon. Opening this issue, so we update to the official icons within the next release. We also have the predicament that it's extremely difficult to remove icons from the pack due to our tooling chain.

@mairin Our team has been tracking the progress in the Font Awesome thread and will resolve this issue once it is resolved in Font Awesome. 😃 

https://github.com/FortAwesome/Font-Awesome/issues/980

**Comment by Templarian** [comment]
[![fedora](https://materialdesignicons.com/icon/fedora)](https://materialdesignicons.com/icon/fedora)

Updated above with the 256 Points (original provided had 433 Points). 😃

@mairin Thanks for the quick update from your team. 👍

**Comment by mairin** [comment]
@Templarian thank you so much for optimizing the points! This is a stop gap, we're planning to revamp our logo and the new properly one color version will be available in the early spring! Cheers!
