### ISSUE TITLE
fireplace icon

### ISSUE THREAD

**Issue by dgorski** [Templarian/MaterialDesign#3777]
A nice fireplace icon for use with Home Automation software like Home Assistant.

**Comment by goyney** [comment]
See also #594.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/51011179-7dcbeb00-1525-11e9-9fb0-1fc8832f780d.png)
[fireplace.svg.zip](https://github.com/Templarian/MaterialDesign/files/2747949/fireplace.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Here's Google's new `fireplace` icon:

[![fireplace](https://user-images.githubusercontent.com/15157491/52489361-f9b76280-2bb9-11e9-8f7a-c4870a897f28.png)](https://github.com/Templarian/MaterialDesign/files/2845875/fireplace.zip)

**Comment by MrGrigri** [comment]
That path needs to be cleaned up...common Google!

**Comment by MrGrigri** [comment]
However, I still prefer @goyney's version.

**Comment by PeterShaggyNoble** [comment]
I initially thought the imperfections were intended to represent a flickering flame but they're completely lost at `24*24` *and* they violate the MD guidelines on simplicity.

I prefer @goyney's too - maybe add Google's as `fireplace-electric`?

**Comment by dgorski** [comment]
I prefer @goyney's too

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53382650-03bfbc00-3943-11e9-8bf6-0e5604b085f4.png)

[fireplace-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/2903475/fireplace-off.svg.zip)

**Comment by Templarian** [comment]
Added both. Agreed, Google's is a little too generic.
