### ISSUE TITLE
teamleader

### ISSUE THREAD

**Issue by andreisgn** [Templarian/MaterialDesign#3778]
Can't find an icon for a teamleder or sectionleader.
Maybe a user with a hat or tie.

**Comment by PeterShaggyNoble** [comment]
You could try `account-supervisor` or `account-supervisor-circle`. If you're specifically looking for a user with a tie then see #354. If none of these suit your needs then please leave a comment with an example and reopen this issue.

[![account-supervisor](https://user-images.githubusercontent.com/15157491/50145186-dc94a080-02a8-11e9-8af4-fd91c6a24bec.png)](https://materialdesignicons.com/icon/account-supervisor) [![account-supervisor-circle](https://user-images.githubusercontent.com/15157491/50145266-11a0f300-02a9-11e9-9d64-2a1440bfc293.png)](https://materialdesignicons.com/icon/account-supervisor-circle)
