### ISSUE TITLE
Update blender-software to use official logo

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3781]
We have a custom icon for the 3D software Blender, which seems to [fall under "Bad Logos"](https://www.blender.org/about/logo/) because it is not backward leaning.

![grafik](https://user-images.githubusercontent.com/1309249/50286923-34760780-0461-11e9-8bfd-61592b321c74.png)

Ther preview shows the 1dp margin variant. I also included a 2dp margin variant just in case.

[blender-software.zip](https://github.com/Templarian/MaterialDesign/files/2698972/blender-software.zip)

**Comment by Templarian** [comment]
Wish every brand would add these. 😃 Makes updating so much easier.

[![blender-software](https://materialdesignicons.com/icon/blender-software)](https://materialdesignicons.com/icon/blender-software)
