### ISSUE TITLE
viadeo icon

### ISSUE THREAD

**Issue by nikolaysm** [Templarian/MaterialDesign#3785]
viadeo icon

![iconfinder_viadeo_2308135](https://user-images.githubusercontent.com/3074155/50443015-b3f05480-0901-11e9-9844-5555cf81f5ed.png)

**Comment by Templarian** [comment]
Never heard of this one. Probably going to be too niche to add at the moment.

**Comment by nikolaysm** [comment]
That is not a specific niche. Viadeo is a social network. More info at wikipedia https://en.wikipedia.org/wiki/Viadeo.
![viadeo](https://user-images.githubusercontent.com/3074155/50820804-ef414900-132d-11e9-954f-dc8c1de44608.jpeg)

**Comment by PeterShaggyNoble** [comment]
Looking at the figures, I concur with @Templarian that it's beyond the (current) scope of this project.

- Usage has declined massively over the past year (global ranking has dropped by over 1200 places in the past 3 months alone)
- Almost 60% of visitors are from a single country, with the next highest percentage being just 4.5%
- [Google Play](https://play.google.com/store/apps/details?id=com.viadeo.android) reports that the app only has 20.2k users ([LinkedIn](https://play.google.com/store/apps/details?id=com.linkedin.android), for comparison, has 1.3m)

I'd suggest using [Simple Icons](https://simpleicons.org/?q=viadeo) for this icon instead:

[![viadeo](https://user-images.githubusercontent.com/15157491/50831297-4a7d3680-1342-11e9-89a8-ccff98702912.png)](https://simpleicons.org/?q=viadeo)
