### ISSUE TITLE
window (opened and closed)

### ISSUE THREAD

**Issue by abattech** [Templarian/MaterialDesign#3786]
I would like to have window icons, like real windows. Variants include: opened and closed windows.

All I find is windows like computer windows on screen, or Windows OS.

**Comment by Templarian** [comment]
`window-open` and `window-closed`, not sure how else we can depict this.

**Comment by VDRainer** [comment]
I do not want to open a new icon request, but it would be nice to have open/closed icons for other windows.
Not the up/down shown above.
Something like the door-open / door-closed.
![20190918_11:31:24_001](https://user-images.githubusercontent.com/26381449/65136527-04678f00-da08-11e9-958d-9e6dbbfddaac.png)
![20190918_11:31:53_001](https://user-images.githubusercontent.com/26381449/65136537-092c4300-da08-11e9-95dd-16cdd5ea66f1.png)

**Comment by JapanYoshi** [comment]
Maybe use this kind of shape, just for iconicity?
![image](https://user-images.githubusercontent.com/8707990/65736800-a7628c00-e11f-11e9-94a6-a9b15ae2932b.png)

**Comment by abattech** [comment]
i had in mind something like this for an open window:
![image](https://user-images.githubusercontent.com/11120944/65809514-e0c0e900-e16b-11e9-9e6e-5225a93e15f3.png)
and a similar image for a closed window.

**Comment by goyney** [comment]
This issue has been closed for over a year, and there are new contributions and discussions happening on #4436. If there is something to add, please add it on that issue.
