### ISSUE TITLE
key-wireless

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3787]
Here is an icon for a wireless key entry. Like at hotels, or IoT.

[![image](https://user-images.githubusercontent.com/4528551/50520865-ec1da180-0a7f-11e9-823e-407c3577bc38.png)](https://github.com/Templarian/MaterialDesign/files/2715198/key-wireless.zip)

**Comment by goyney** [comment]
[![key-wireless](https://materialdesignicons.com/icon/key-wireless)](https://materialdesignicons.com/icon/key-wireless)
