### ISSUE TITLE
credit-card-wireless

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3788]
Here is a `credit-card-wireless` icon for use at <abbr title="Point of Sales">POS</abbr> machines. Here in the states, this icon is used to demonstrate that a POS accepts wireless payment options...like Apple and Android Pay, and wireless credit/debit cards.

[![image](https://user-images.githubusercontent.com/4528551/50520959-75cd6f00-0a80-11e9-8de8-44f5bea1e77b.png)](https://github.com/Templarian/MaterialDesign/files/2715204/credit-card-wireless.zip)

**Comment by PeterShaggyNoble** [comment]
I'd suggest using the standard "contactless payment" icon for this or, at least, adding it as well.

**Comment by MrGrigri** [comment]
I would disagree for their original logo, but if we modified it to just the wireless signal that could work.

![image](https://user-images.githubusercontent.com/4528551/50597328-51003f80-0e64-11e9-9285-5f77e85b969b.png) ![image](https://user-images.githubusercontent.com/4528551/50597346-5f4e5b80-0e64-11e9-83c4-537379ccc3c6.png)

---

[reference](https://en.wikipedia.org/wiki/Contactless_payment)

[contactless-payment.zip](https://github.com/Templarian/MaterialDesign/files/2721052/contactless-payment.zip)

**Comment by PeterShaggyNoble** [comment]
That's the one I was referring to 😃

**Comment by CoDEmanX** [comment]
I'm for adding both, the credit card + two waves in material style (as icon for contactless cards in general), and the four waves with rounded corners, which is on all my three wireless/V-Pay cards (as brand logo of sorts).

**Comment by Templarian** [comment]
Yea, this seems fine to add. Wish the contact payment standard logo wasn't so detailed, but `credit-card-wireless` gets the idea across.

**Comment by Templarian** [comment]
Added the two.
