### ISSUE TITLE
Maintenance support Icon / Customer support Icon (icon request)

### ISSUE THREAD

**Issue by jakicho** [Templarian/MaterialDesign#379]
here are some inspiration -

maintenance & support :
https://thenounproject.com/term/mechanic/140044/
https://thenounproject.com/term/user/75933/
https://thenounproject.com/term/construction/36597/
https://thenounproject.com/term/construction/28105/
https://thenounproject.com/term/mechanic/140044/

customer support :
https://thenounproject.com/term/customer-support/79727/
https://thenounproject.com/term/customer-service/50337/
https://thenounproject.com/term/support/5163/
https://thenounproject.com/term/customer-service/20052/

**Comment by CoDEmanX** [comment]
Webalys Nova examples: ![image](https://cloud.githubusercontent.com/assets/1309249/15425146/b4ff6144-1e86-11e6-8b0c-83952bc64c88.png) ![image](https://cloud.githubusercontent.com/assets/1309249/15425153/c03a75bc-1e86-11e6-9477-1760aded77aa.png)

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #574 and #2474
