### ISSUE TITLE
Table tennis

### ISSUE THREAD

**Issue by Gualty** [Templarian/MaterialDesign#3790]
Hi,
there are a lot of different sport icons but not a table tennis racket.

Like this: https://fontawesome.com/icons/table-tennis?style=solid

**Comment by goyney** [comment]
The stock icon was a little funky, so I improved it a little bit by upping the size and aligning it to the grid.

![image](https://user-images.githubusercontent.com/1015040/50653837-d9600c80-0f58-11e9-847b-7979a0520fe5.png)
(Grey is the original icon from Fit)

Both are included here: [table-tennis.zip](https://github.com/Templarian/MaterialDesign/files/2724851/table-tennis.zip)

**Comment by Templarian** [comment]
Added.
