### ISSUE TITLE
health-insurance-id-card

### ISSUE THREAD

**Issue by jonnyborg** [Templarian/MaterialDesign#3791]
Requesting an ID Card for health insurance use. I work in the healthcare insurance world and this closely resembles the real deal.

See bottom right corner. I took the "Subtitles" icon and added a large rectangle above. This creates the typical header area of an insurance card where there is a logo and plan name. This is helpful in situations where an insurance card is not mis-represented by an icon where the card includes either a "credit card magnet strip" such as the "credit" icon, or "profile image" such as "account-card-details".

<img width="271" alt="screen shot 2018-12-31 at 1 35 08 pm" src="https://user-images.githubusercontent.com/16577242/50565847-1af67a80-0d01-11e9-8ebb-01a784f616fb.png">

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/50618679-c6b3ec00-0ef4-11e9-9121-a8c908e79967.png)

Download: [id-card.zip](https://github.com/Templarian/MaterialDesign/files/2722412/id-card.zip)

**Comment by jonnyborg** [comment]
@PeterShaggyNoble the icon @CoDEmanX drafted is perfect! Thanks for adding!

**Comment by JamesCoyle** [comment]
If you'd like to contribute just attach a zip of the SVG file and a preview image to any issue. Once you hit 5 icons you will be added as a contributor.

**Comment by jonnyborg** [comment]
Got it. Thanks @JamesCoyle

**Comment by goyney** [comment]
[![id-card](https://materialdesignicons.com/icon/id-card)](https://materialdesignicons.com/icon/id-card)
