### ISSUE TITLE
Unsplash

### ISSUE THREAD

**Issue by minimaluminium** [Templarian/MaterialDesign#3792]
![Unsplash](https://d1qb2nb5cznatu.cloudfront.net/startups/i/65467-4b3e46561abf4c2727186ffb1aec54cf-medium_jpg.jpg?buster=1489952272)

**Comment by goyney** [comment]
This seems pretty niche and would likely not be a good fit for this library.

**Comment by PeterShaggyNoble** [comment]
Yeah, I'd agree that it's beyond the current scope of the project.

We have discussed a dedicated brand icon pack in the past and will revisit this if it ever comes to light. In the meantime, you could try [Simple Icons](https://simpleicons.org/?q=unsplash).
