### ISSUE TITLE
Automotive Icons, Part II

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3793]
**MOAR. CAR. ICONS!**

Firstly, we have `car-brake-parking`:
![image](https://user-images.githubusercontent.com/1015040/50711474-51533300-103c-11e9-9518-c8759e02206e.png)

This icon is typically used to indicate an issue with the brakes, not a parking brake. We should rename this to `car-brake-alert`. (All icons with the waves around the circle are brake related.)

Then we can add the real parking brake icon:
![image](https://user-images.githubusercontent.com/1015040/50711535-82cbfe80-103c-11e9-9d9d-bf0d14542594.png)

---

Many newer cars have a "hold" mode that auto applies the brake when coming to a complete stop while the car is still in gear. This icon represents that:
![image](https://user-images.githubusercontent.com/1015040/50711585-ad1dbc00-103c-11e9-95ac-e525e9470996.png)

---

Missing defroster icons:
![image](https://user-images.githubusercontent.com/1015040/50711622-ccb4e480-103c-11e9-80fb-e508760d329f.png)![image](https://user-images.githubusercontent.com/1015040/50711633-d63e4c80-103c-11e9-80ff-da068f79b72a.png)

---

And four more missing icons:
![image](https://user-images.githubusercontent.com/1015040/50711651-e6562c00-103c-11e9-8ca3-9cbc2bd9ce21.png)![image](https://user-images.githubusercontent.com/1015040/50711665-eeae6700-103c-11e9-9c57-45a9b6b40b0c.png)
![image](https://user-images.githubusercontent.com/1015040/50711678-f79f3880-103c-11e9-9717-7c43cc137b5c.png)![image](https://user-images.githubusercontent.com/1015040/50711690-00900a00-103d-11e9-8e6a-72238c2bcdda.png)

---

**Source:** [car.zip](https://github.com/Templarian/MaterialDesign/files/2728588/car.zip)

**Comment by Templarian** [comment]
Added these quick before starting on some others.

**Comment by JamesCoyle** [comment]
Could do with speed limiter too.
