### ISSUE TITLE
car-seat

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3795]
![image](https://user-images.githubusercontent.com/1015040/50746135-a4bfaf80-11fb-11e9-9e85-12a3c1ccc7c2.png)

[car-child-seat.svg.zip](https://github.com/Templarian/MaterialDesign/files/2731229/car-child-seat.svg.zip)

**Comment by goyney** [comment]
Here's some other car-seat related icons too:

![image](https://user-images.githubusercontent.com/1015040/51131628-477cbd00-17fe-11e9-812b-cc072745c42a.png)
![image](https://user-images.githubusercontent.com/1015040/51131616-4055af00-17fe-11e9-82ad-96e686e44bc2.png)![image](https://user-images.githubusercontent.com/1015040/51131605-3a5fce00-17fe-11e9-81fa-2b721f9b158a.png)

[car-seat.zip](https://github.com/Templarian/MaterialDesign/files/2756499/car-seat.zip)

**Comment by Wefneck** [comment]
I have also had a need for this icon. My take is attached should you want it. 
[car-child-seat.svg.zip](https://github.com/Templarian/MaterialDesign/files/2867580/car-child-seat.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Here's a preview of @Wefneck's contribution:

![car-seat-child](https://user-images.githubusercontent.com/15157491/53239057-eb297a80-3692-11e9-864f-7a6d7504eb4a.png)

I think some combination of this with @goyney's would work best; the raised legs on his contribution don't look right to me.

**Comment by goyney** [comment]
[![car-child-seat](https://materialdesignicons.com/icon/car-child-seat)](https://materialdesignicons.com/icon/car-child-seat)[![car-seat](https://materialdesignicons.com/icon/car-seat)](https://materialdesignicons.com/icon/car-seat)
[![car-seat-heater](https://materialdesignicons.com/icon/car-seat-heater)](https://materialdesignicons.com/icon/car-seat-heater)
[![car-seat-cooler](https://materialdesignicons.com/icon/car-seat-cooler)](https://materialdesignicons.com/icon/car-seat-cooler)
