### ISSUE TITLE
lacrosse

### ISSUE THREAD

**Issue by mazenchami** [Templarian/MaterialDesign#3796]
[lacrosse-racquets-couple.svg.zip](https://github.com/Templarian/MaterialDesign/files/2734072/lacrosse-racquets-couple.svg.zip)

**Comment by goyney** [comment]
This icon is included in Google Fit as `racquetball`. I've cleaned the original icon up for inclusion into MDI.

![image](https://user-images.githubusercontent.com/1015040/50791331-7ee3ea80-128f-11e9-96e2-f501e8b746af.png)

[racquetball.svg.zip](https://github.com/Templarian/MaterialDesign/files/2734180/racquetball.svg.zip)

We can add a `lacrosse` alias to this once it is added.

**Comment by mazenchami** [comment]
@goyney thank you very much for your quick reply. when do you think this will be included and available to be used?

**Comment by goyney** [comment]
Currently, it is slated for the 3.8 release, we're working on the 3.4 release now, so a few months. That is, unless @Templarian feels nice enough to include it earlier. :)

**Comment by Templarian** [comment]
I've been prioritizing sports related icons for the 3.4 release. Also stock icons get added fairly quick.

**Comment by Templarian** [comment]
[![racquetball](https://materialdesignicons.com/icon/racquetball)](https://materialdesignicons.com/icon/racquetball)

**Comment by mazenchami** [comment]
@Templarian will this be available here: https://oblador.github.io/react-native-vector-icons/?

**Comment by Templarian** [comment]
Assuming they use `@mdi/js` or `@mdi/svg` as dependencies shortly after the next release (probably in early February). We just released 3.3.xx.
