### ISSUE TITLE
diving

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3798]
This icon is exported from Google Fit and is not ready to be included in MDI. It'll need someone to take a pass at Materializing it. Feel free!

![image](https://user-images.githubusercontent.com/1015040/50807201-52e45b80-12c7-11e9-9437-61743e50f644.png)

Google Fit sources: [water-sports.zip](https://github.com/Templarian/MaterialDesign/files/2737118/water-sports.zip)

**Comment by JamesCoyle** [comment]
We should use the person from `bike` or `human` where appropriate for these.

[![](https://materialdesignicons.com/icon/bike)](https://materialdesignicons.com/icon/bike)[![](https://materialdesignicons.com/icon/human)](https://materialdesignicons.com/icon/human)

**Comment by goyney** [comment]
[![diving](https://materialdesignicons.com/icon/diving)](https://materialdesignicons.com/icon/diving)
