### ISSUE TITLE
Sensor icon

### ISSUE THREAD

**Issue by MiguelAngelLV** [Templarian/MaterialDesign#3802]
I need a "sensor" icon from devices (arduino, smartphones, raspberry).

#1016 is for specific sensors, I say the "sensor group".

Something as "video-input-antenna" but, instead of "antenna" a device.

**Comment by PeterShaggyNoble** [comment]
Would the existing `remote` icon suit your needs?

![remote](http://mdi.houseofdesign.ie/tools/preview/?icon=remote)

**Comment by goyney** [comment]
This has been requested and several icons added several times.

See #3309, #2584, #2464.

**Comment by MiguelAngelLV** [comment]
I think that #3309 will be perfect but I see it did not add finally.

**Comment by goyney** [comment]
#3309 was closed because we couldn't incorporate the zig-zag line with the wireless symbols in a way that worked. `video-input-antenna` was deemed suitable enough by the Contributors, so we closed it.

I believe `video-input-antenna` and `remote` are your two best options.

**Comment by goyney** [comment]
Closing because the `Consider Closing` tag was added quite a while ago. If you have another idea for this icon, please feel free to comment again and we'll take another look. Thanks!
