### ISSUE TITLE
Forwardburger

### ISSUE THREAD

**Issue by en-davidh** [Templarian/MaterialDesign#3803]
Hi,

I'm using the "backburger" icon for opening a sidebar containing a list of elements (not the main navigation).
In order to close this sidebar, I need a **mirrored version of the backburger**. For now, I just rotate it with CSS, but an actual icon would be better, I guess.

Regarding the name: I just came up with forwardburger, but if you have something better, feel free to use something else.

Thanks

**Comment by Templarian** [comment]
This was definitely added as a joke a while back. I added the forward one now, because what's the worst that could happen.
