### ISSUE TITLE
rewind-30

### ISSUE THREAD

**Issue by SeanPM5** [Templarian/MaterialDesign#3804]
There's an icon for fast-forward-30 ([link](https://materialdesignicons.com/icon/fast-forward-30)) which is a great icon to use for commercial skip. 

The equivalent for the rewind side seems to be rewind-10 ([link](https://materialdesignicons.com/icon/rewind-10)), I suspect that's because "Go Back" defaults to ten seconds on many DVR's. But most of them allow you to change that, and I have mine set at 30. Was wondering if we could also get a rewind-30 for consistency. 

Thanks for this great project by the way!

**Comment by Templarian** [comment]
[![fast-forward-10](https://materialdesignicons.com/icon/fast-forward-10)](https://materialdesignicons.com/icon/fast-forward-10) [![rewind-30](https://materialdesignicons.com/icon/rewind-30)](https://materialdesignicons.com/icon/rewind-30)
