### ISSUE TITLE
Trophy Multiple

### ISSUE THREAD

**Issue by BapediBoupi** [Templarian/MaterialDesign#3805]
Hey guys! 

Would be great to have a trophy icon with "multiple" trophies. The goal would be to display the total of trophies.
Something like http://www.psdgraphics.com/file/2018/gold-silver-bronze-trophies.jpg but obviously material, smaller and beautiful ;)

Thanks!

**Comment by goyney** [comment]
I don't really think this is going to be possible in the confines of a 24x24dp square. For example, this is indistinguishable:

![image](https://user-images.githubusercontent.com/1015040/72312718-f5f84f80-3656-11ea-9897-44fd39835e04.png)
