### ISSUE TITLE
restart-off

### ISSUE THREAD

**Issue by FANMixco** [Templarian/MaterialDesign#3808]
I got an idea of creating an icon for disabling restart.

![picture1](https://user-images.githubusercontent.com/1666156/50965544-8810c980-14d2-11e9-9c10-0dd20f93d9ba.png)

There are some cases when you have an option of restarting, however, if you do some actions like running a timer or stopwatch, you might block it until it's finished or paused. I attached my proposal. Thanks!

**Comment by goyney** [comment]
So, our `restart` icon already has an alignment issue, so we should update that:

![image](https://user-images.githubusercontent.com/1015040/50974071-61de3000-14b8-11e9-9863-d1b7564f9c7f.png)
(Grey is the current icon)

Then we can add the off variant:
![image](https://user-images.githubusercontent.com/1015040/50974096-6f93b580-14b8-11e9-98e4-2facc308e591.png)

[restart.zip](https://github.com/Templarian/MaterialDesign/files/2745666/restart.zip)

**Comment by FANMixco** [comment]
Awesome! @goyney, nice design!

**Comment by Templarian** [comment]
Updated and Added. 😃
