### ISSUE TITLE
tea

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3810]
From Google's Extended Set:

![image](https://user-images.githubusercontent.com/1015040/50987656-3ff4a580-14d8-11e9-89db-7e4401d49a6c.png)
[tea.svg.zip](https://github.com/Templarian/MaterialDesign/files/2746552/tea.svg.zip)

**Comment by goyney** [comment]
Here's my take on the outlined version:
![image](https://user-images.githubusercontent.com/1015040/50987809-a974b400-14d8-11e9-9c0c-829b47290854.png)
[tea-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2746558/tea-outline.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Hmm ... might need to move the string 1 point to the right for the outlined version.

**Comment by Templarian** [comment]
^ Fixed that and added both. 😃
