### ISSUE TITLE
golf-tee

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3811]
From Google's Extended Set:

![image](https://user-images.githubusercontent.com/1015040/50987949-feb0c580-14d8-11e9-89b3-8dba32e238af.png)
[golf-tee.svg.zip](https://github.com/Templarian/MaterialDesign/files/2746561/golf-tee.svg.zip)

**Comment by PeterShaggyNoble** [comment]
I think we might need to redo this one ourselves to increase the spacing between the dimples and add 1 or 2 more.

**Comment by goyney** [comment]
[![golf-tee](https://materialdesignicons.com/icon/golf-tee)](https://materialdesignicons.com/icon/golf-tee)
