### ISSUE TITLE
rotate-360

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3812]
![image](https://user-images.githubusercontent.com/1015040/51006628-2ff9b780-1512-11e9-9e17-80b885bdbde3.png)
[360.svg.zip](https://github.com/Templarian/MaterialDesign/files/2747630/360.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Should there be a cutout where the 2 cross in `axis-orbit`?

**Comment by Templarian** [comment]
[![rotate-orbit](https://materialdesignicons.com/icon/rotate-orbit)](https://materialdesignicons.com/icon/rotate-orbit)

**Comment by Templarian** [comment]
[![axis-z-rotate-clockwise](https://materialdesignicons.com/icon/axis-z-rotate-clockwise)](https://materialdesignicons.com/icon/axis-z-rotate-clockwise) [![axis-z-rotate-counterclockwise](https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise)](https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/51096188-63417e00-1780-11e9-9dd3-a1cf12d177a8.png)

Thinking of something like this for the `x` and `y` axis rotations.

**Comment by Templarian** [comment]
Added the above 4.

**Comment by PeterShaggyNoble** [comment]
Was the original `rotate-360` icon added?
