### ISSUE TITLE
Update wheelchair-accessibility

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3813]
Google's Extended Set contains an official wheelchair icon. We should update ours and reattribute to Google.

![image](https://user-images.githubusercontent.com/1015040/51006804-e5c50600-1512-11e9-9d18-b7bc8b984577.png)
(Grey is our current)
[wheelchair-accessibility.svg.zip](https://github.com/Templarian/MaterialDesign/files/2747640/wheelchair-accessibility.svg.zip)

**Comment by MrGrigri** [comment]
I do not agree. See [The Accessibility Icon Project](http://accessibleicon.org/) website for more on this.

**Comment by goyney** [comment]
Then ours is technically a brand logo and should be reattributed.

**Comment by MrGrigri** [comment]
It is not a brand, it is a social push to update the current wheelchair icon.

**Comment by Templarian** [comment]
Closing this one out. I would prefer us to use keep using the accessibility project's icon. Over the years many have moved to use this as the standard icon. It's also Material enough that works.
