### ISSUE TITLE
microsoft is off-center

### ISSUE THREAD

**Issue by Patricol** [Templarian/MaterialDesign#3818]
It's shifted a bit down and to the left.

**Comment by goyney** [comment]
This is intended so the four square remain lined up perfectly on the grid. Centering the logo or reducing it down 1dp would cause it to be blurry at smaller resolutions.

![image](https://user-images.githubusercontent.com/1015040/51066790-892d1e00-15da-11e9-85a2-95e018ea9843.png)![image](https://user-images.githubusercontent.com/1015040/51066785-7dd9f280-15da-11e9-90f8-15fd1f4b7122.png)
