### ISSUE TITLE
Each day of month

### ISSUE THREAD

**Issue by pawelantczak** [Templarian/MaterialDesign#382]
Hello.
I'm thinking about something like Google Calendar favicon.
You can see current day of the month at first sight, just looking at tab icon.
There are many different use cases, in which daily icons could be used.
Wrap-up: icons looking like a card from calendar, for each day `01, 02, ...31`.

- [ ] calendar-1
- [ ] calendar-2
- [ ] calendar-3
- [ ] calendar-4
- [ ] calendar-5
- [ ] calendar-6
- [ ] calendar-7
- [ ] calendar-8
- [ ] calendar-9
- [ ] calendar-10
- [ ] calendar-11
- [ ] calendar-12
- [ ] calendar-13
- [ ] calendar-14
- [ ] calendar-15
- [ ] calendar-16
- [ ] calendar-17
- [ ] calendar-18
- [ ] calendar-19
- [ ] calendar-20
- [ ] calendar-21
- [ ] calendar-22
- [ ] calendar-23
- [ ] calendar-24
- [ ] calendar-25
- [ ] calendar-26
- [ ] calendar-27
- [ ] calendar-28
- [ ] calendar-29
- [ ] calendar-30
- [ ] calendar-31

**Comment by pawelantczak** [comment]
Thanks for accepting.
Donate button clicked.
Regards.

**Comment by Templarian** [comment]
Tagging it, doesn't mean it will be added. To be honest, this is more so something that should be scripted into the application rather than with individual icons.

**Comment by pawelantczak** [comment]
Got it. 
I really think, that this could be useful in many different use cases.
I wanted icons to be pixel perfect, on-the-fly generation won't address it.
Anyway, I somehow created it myself - thanks for svg template.
