### ISSUE TITLE
Clapping icon

### ISSUE THREAD

**Issue by FANMixco** [Templarian/MaterialDesign#3821]
I have seen many times the emoji of the clapping icon a couple of times:

https://www.emojibase.com/emoji/1f44f/clappinghandssign

And I thought if there is any similar icon or proposition from material design, I know it's an uncommon idea, but I'd like to know if it's possible to create a similar icon in the future? For clapping and stop clapping?

This is a basic draft of the clapping based on the hand icon.

![clap](https://user-images.githubusercontent.com/1666156/51181346-39e13900-18cb-11e9-9417-211c73de485c.png)

And this one for the stop clapping.

![stopclap](https://user-images.githubusercontent.com/1666156/51181537-b6741780-18cb-11e9-97bc-3fc179ee2cc5.png)

I got an inspiration from here:

https://www.flaticon.com/free-icon/clapping-hands_103856

Thanks for any idea or if it's possible.

**Comment by goyney** [comment]
This is loosely related to #1353.

I think both of these issues have a perspective issue, showing one hand on top of the other. This may be a difficult thing to represent via an icon in the Material style.

**Comment by FANMixco** [comment]
> This is loosely related to #1353.
> 
> I think both of these issues have a perspective issue, showing one hand on top of the other. This may be a difficult thing to represent via an icon in the Material style.

Hi goyney, wouldn't be like this?
https://www.shutterstock.com/image-vector/clap-green-blue-material-color-minimal-694952209
Or this?
https://www.shutterstock.com/image-vector/clap-hands-bright-yellow-material-minimal-794747863

I think it can be used similar to the edit that I made with the hand, it's just an idea :).

**Comment by MrGrigri** [comment]
@goyney, displaying one object on top of another is not violating MD. It's a flat perspective, not 3d.

**Comment by eman1986** [comment]
This would be a great addition

**Comment by alexykouakou** [comment]
Please consider this clap icon request! I need it too

**Comment by Nisgrak** [comment]
Hey! Will be it added? 😄

**Comment by goyney** [comment]
This breaks a bunch of guidelines, but I don't know how else we can accomplish it.

![image](https://user-images.githubusercontent.com/1015040/133357272-077ea748-a471-43fe-aa17-280bc05e53d9.png)

[hand-clap.svg.zip](https://github.com/Templarian/MaterialDesign/files/7166083/hand-clap.svg.zip)

**Comment by FANMixco** [comment]
Hi @goyney, amazing job!

**Comment by goyney** [comment]
[![hand-clap](https://materialdesignicons.com/icon/hand-clap)](https://materialdesignicons.com/icon/hand-clap)

**Comment by FANMixco** [comment]
Thank you @goyney !
