### ISSUE TITLE
Forest

### ISSUE THREAD

**Issue by Darrelk** [Templarian/MaterialDesign#3823]
Hello,

Can you please include the following forest icon? I like the "pine-tree" icon, but this will be a nice improvement
![forest icon](https://user-images.githubusercontent.com/6082867/51309545-573e1080-1a4d-11e9-90cf-67379ad8c335.png)

The SVG can be downloaded from 
One of the following svg's can be used.
https://www.onlinewebfonts.com/icon/498096
https://www.onlinewebfonts.com/icon/556097

Regards,
DarrelK

**Comment by mark-monserrat** [comment]
![preview](https://user-images.githubusercontent.com/8490508/51423390-53032600-1bfa-11e9-8b3f-c8226ecb087f.png)
[forest.svg 2.zip](https://github.com/Templarian/MaterialDesign/files/2775285/forest.svg.2.zip)

**Comment by JamesCoyle** [comment]
I'd suggest `pine-tree` with a smaller pine tree behind it.
[![](https://materialdesignicons.com/icon/pine-tree)](https://materialdesignicons.com/icon/pine-tree)

**Comment by CoDEmanX** [comment]
I wonder if a horizontal line is added, whether it should be disconnect it from the trees or not.

**Comment by goyney** [comment]
[![forest](https://materialdesignicons.com/icon/forest)](https://materialdesignicons.com/icon/forest)

**Comment by Darrelk** [comment]
Thank you so much. Can't wait for the next release!!!
