### ISSUE TITLE
Icons for MongoDB | Electron | AWS | Elastic Search | Kafka | Grunt | Gulp

### ISSUE THREAD

**Issue by PsyGik** [Templarian/MaterialDesign#3825]
- [ ] MongoDB
- [ ] Electron
- [ ] AWS
- [ ] Elastic Search
- [ ] Kafka
- [ ] Grunt
- [ ] Gulp
- [ ] Web Components

**Comment by PeterShaggyNoble** [comment]
Thanks for the requests, @PsyGik.

However could you open separate requests for each one please to allow us to evaluate and track each one individually? Don't forget to search for existing issues first. Also, note that some of these *will* be beyond the current scope of this project.

**Comment by PsyGik** [comment]
Closing in favor of #3827, #3828, #3829, #3830, #3831, #3832, #3833, #3834
