### ISSUE TITLE
Update: Slack

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3826]
Slack hase [a new logo](https://slackhq.com/say-hello-new-logo) so we'll need to update our icon accordingly.

SVGS can be found [here](https://brandfolder.com/slack/logos) and brand guidelines (for those interested) [here](https://a.slack-edge.com/0f43e/marketing/img/media-kit/Slack-Brand-Guidelines.pdf).

**Comment by MrGrigri** [comment]
So, there is a slight issue with their logo. It's built on a 19x19 platform. If we place it on-grid at 19x19, slightly off-center to the top-right (figure 1), then the path is much cleaner and will raster better. We could keep it at 19x19 in the center, which wouldn't raster well (figure 2). They also have a 15x15 version, but IMO, that would be too small and have the same issues

My vote is for Figure 1

---

#### Figure 1
![slack - figure 1](https://user-images.githubusercontent.com/4528551/51335014-45a13c80-1a3e-11e9-8f4f-14a804aa534a.png)


#### Figure 2
![slack - figure 2](https://user-images.githubusercontent.com/4528551/51335037-4fc33b00-1a3e-11e9-8e18-6c657ef6d2b0.png)

---

#### Assets

[slack.zip](https://github.com/Templarian/MaterialDesign/files/2769735/slack.zip)

**Comment by Templarian** [comment]
So with the Microsoft logo we decided to offset it, I think we should probably follow that for cleaner 1:1 icons even if it's off-center.

**Comment by PeterShaggyNoble** [comment]
And, for consistency with the MS icon, we should probably shift it down & left of centre.

**Comment by CoDEmanX** [comment]
I agree, figure 1.

**Comment by Templarian** [comment]
[![slack](https://materialdesignicons.com/icon/slack)](https://materialdesignicons.com/icon/slack)
