### ISSUE TITLE
mongo-db

### ISSUE THREAD

**Issue by PsyGik** [Templarian/MaterialDesign#3827]

**Comment by PeterShaggyNoble** [comment]
It looks like their single colour icon is an outline of their leaf; SVG [here](https://www.mongodb.com/assets/images/index/icon-leaf.svg).

**Comment by PsyGik** [comment]
Standard Logo includes the name: https://www.mongodb.com/brand-resources

![image](https://user-images.githubusercontent.com/5432911/51335051-1c68c680-1aa7-11e9-89b2-3be2f2ad14a4.png)

**Comment by goyney** [comment]
Considering this is a development tool, it meets the criteria to still be added, [despite our recent announcement about brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by goyney** [comment]
I'm not sure we can include this logo in our library because of the rules set forth by MongoDB's brand guidelines.

> Do not change the color of the MongoDB logo.

Additionally, all of their official, downloadable logos contain the wordmark as well, which obviously wouldn't fit within a 24x24dp square. Lastly, I don't know how we would translate the leaf into a single color, but recognizable, icon.

I am proposing we reject this logo.

**Comment by MrGrigri** [comment]
I agree that we do not go against their branding guidelines.

**Comment by MrGrigri** [comment]
I have reached out to MongoDB and we'll see if they respond and take it from there.

**Comment by goyney** [comment]
@MrGrigri Did you ever get any responses from MongoDB about their logo?

**Comment by MrGrigri** [comment]
I have not

**Comment by MrGrigri** [comment]
I believe we should close this issue and revisit it if/when they respond

**Comment by goyney** [comment]
Agreed. Closing this for now. If we get confirmation from MongoDB on an appropriate use of their logo which fits this library, we will reopen.

**Comment by PeterShaggyNoble** [comment]
In the meantime, there is a version available in [Simple Icons](https://simpleicons.org/?q=MongoDB).
