### ISSUE TITLE
Electron

### ISSUE THREAD

**Issue by PsyGik** [Templarian/MaterialDesign#3828]

**Comment by Templarian** [comment]
Need to get the SVG from the top left logo and convert it. https://electronjs.org/

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/54494603-57199000-4899-11e9-9290-28c9da5ff980.png)
[electron-logo.svg](https://github.com/terreng/samples/blob/master/electron-logo.svg)

**Comment by goyney** [comment]
[![electron-framework](https://materialdesignicons.com/icon/electron-framework)](https://materialdesignicons.com/icon/electron-framework)
