### ISSUE TITLE
Generated files permissions

### ISSUE THREAD

**Issue by pawelantczak** [Templarian/MaterialDesign#383]
I don't know if it's just me,
but  on my Ubuntu, after unzipping 5.x package, files don't have read permissions.
I have to chmod all of them, to make is usable.

**Comment by Templarian** [comment]
Since you're the first person to report this, I'm going to assume it's an environment issue on your local machine. I'm not going to be much help, so I would suggest asking on a forum or IRC.

The zip library in use is all in memory it doesn't even know what a file system is. :smile:
