### ISSUE TITLE
Elasticsearch

### ISSUE THREAD

**Issue by PsyGik** [Templarian/MaterialDesign#3830]

**Comment by PeterShaggyNoble** [comment]
I'd be of the opinion that Elasticsearch would be beyond the scope of this project but I'll leave this open for now for other members of the team to weigh in.

If we do decide to add it, a single colour SVG can be found at https://www.elastic.co/static/images/svg/logo-elastic-footer-stacked-999.svg

**Comment by Templarian** [comment]
I would say it's in scope for the project. Pretty heavily used tech now-a-days.

**Comment by PeterShaggyNoble** [comment]
The SVG I linked above is actually the company icon. An single colour SVG of the Ealsticsearch *product* icon can be found at https://github.com/elastic/kibana/blob/master/src/ui/public/icons/elasticsearch-gray.svg

**Comment by goyney** [comment]
Considering this is a development tool, it meets the criteria to still be added, [despite our recent announcement about brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by goyney** [comment]
We are unable to add this icon to the library because of the rules set forth in Elastic's branding.

> **Kindly Don't…**
> Use the wordmarks without the logo marks or vice versa

https://www.elastic.co/brand
