### ISSUE TITLE
kafka (Apache)

### ISSUE THREAD

**Issue by PsyGik** [Templarian/MaterialDesign#3831]

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/54494882-1707dc80-489c-11e9-98d4-dd825b7da03c.png)
[apache-kafa-logo.svg](https://github.com/terreng/samples/blob/master/apache-kafa-logo.svg)

**Comment by goyney** [comment]
Considering this is a development tool, it meets the criteria to still be added, [despite our recent announcement about brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by goyney** [comment]
[![apache-kafka](https://materialdesignicons.com/icon/apache-kafka)](https://materialdesignicons.com/icon/apache-kafka)
