### ISSUE TITLE
web-components

### ISSUE THREAD

**Issue by PsyGik** [Templarian/MaterialDesign#3834]

**Comment by PeterShaggyNoble** [comment]
Do they have a single colour icon?

**Comment by PsyGik** [comment]
I don't think they do. This is the official icon maybe?

![image](https://user-images.githubusercontent.com/5432911/51334705-61402d80-1aa6-11e9-952d-11165a65ef25.png)

Goes similar with the polymer icon (which is also not single color I think)

**Comment by Templarian** [comment]
I'm going to mark this one as rejected. Actually was looking into adding this a while back since I was going to write docs for web component usage with the icon pack, but never got around to it.

**Comment by PeterShaggyNoble** [comment]
There *is* a single colour hexagon in the "Browser Support" table on their homepage but I don't think it's their official brand icon.
