### ISSUE TITLE
camera-outline

### ISSUE THREAD

**Issue by ruslang02** [Templarian/MaterialDesign#3835]
Didn't find the `camera-outline`, though found a `camera-enhance-outline`, so I made my own one.

![screenshot_20190118_230733](https://user-images.githubusercontent.com/25264730/51410510-e2b2c100-1b75-11e9-8d60-a782f120f5df.png)

[camera-outline.zip](https://github.com/Templarian/MaterialDesign/files/2774353/camera-outline.zip)

**Comment by Templarian** [comment]
Added. 😃
