### ISSUE TITLE
Light icons

### ISSUE THREAD

**Issue by hulkhaugen** [Templarian/MaterialDesign#3836]
So, I've made some icons, figured I might be a contributor. Seems like that option is disabled at the moment. Anyway, I put some effort into some of these icons, others are more copy/paste type like brands etc. Figured I could share them here, and maybe you can use some of them :)

![image](https://user-images.githubusercontent.com/1409758/51445471-a0b88500-1d05-11e9-8882-ad9d0325ac89.png)

![image](https://user-images.githubusercontent.com/1409758/51445482-c3e33480-1d05-11e9-9c99-88303602f63a.png)

![image](https://user-images.githubusercontent.com/1409758/51445502-0d338400-1d06-11e9-9aaa-54e671fdb2de.png)

![image](https://user-images.githubusercontent.com/1409758/51445507-2a685280-1d06-11e9-9c44-7fc8cfffda0d.png)

![image](https://user-images.githubusercontent.com/1409758/51445520-51268900-1d06-11e9-87ee-4812591100a7.png)

![image](https://user-images.githubusercontent.com/1409758/51445458-6e0e8c80-1d05-11e9-8fc6-3f3504e487ac.png)

Would like to see some of these make it into the library, and sorry if I'm going about this the wrong way. SVG is also brand new to me, but I cleaned up the files after making them in Inkscape, don't think I'm far off of what you want ;)

EDIT: Replaced SVG code with preview images.

**Comment by Templarian** [comment]
Can you attach them into a Zip. You can also use http://dev.materialdesignicons.com/contribute/github to generate a preview image than can be pasted.

**Comment by hulkhaugen** [comment]
Sure. Updated the first post. Attached a zip file.
[mdi-extra.zip](https://github.com/Templarian/MaterialDesign/files/2777062/mdi-extra.zip)

**Comment by goyney** [comment]
Node-RED - See https://github.com/Templarian/MaterialDesign/issues/3170.
Pi-Hole won't be added at the moment - See https://github.com/Templarian/MaterialDesign/issues/3310

---

Your other lamp/light icons are a good first attempt. I would recommend you take some time to read through Google's design guidelines for icons: https://material.io/design/iconography/system-icons.html

For example, `outdoor-lamp` and `floor-lamp-variant` appear to be using very skinny (>1dp width) lines, which goes against those guidelines. `outdoor-lamp-variant` is better, but is not aligned to the grid very well.

See if you can take another stab at improving those icons. If you have other questions about how to align them better with the guidelines, feel free to ask them here.

**Comment by hulkhaugen** [comment]
Yes, I suspected that the outdoor-lamp and floor-lamp-variant might be a bit skinny. I'll see if I can make them look better with thicker lines, thanks for the link ;) I must admit that I'm not quite sure what you refer to about the outdoor-lamp-variant as it has a consistent 2px padding from all the outer points. Or do you mean that the lamp itself should be centered, and the bracket should be secondary and just stay within the paddings? You didn't comment on the led-strip-variant, does that mean that it's good, or was it so bad that you didn't know where to start?

**Comment by hulkhaugen** [comment]
I think I got it now. Is this better?

![image](https://user-images.githubusercontent.com/1409758/51497744-6235cf80-1dc4-11e9-8227-e7c523daa623.png)

![image](https://user-images.githubusercontent.com/1409758/51497761-75489f80-1dc4-11e9-80a0-73d32130c722.png)

![image](https://user-images.githubusercontent.com/1409758/51497804-9610f500-1dc4-11e9-93b2-a3d8b1cda103.png)

![image](https://user-images.githubusercontent.com/1409758/51497785-885b6f80-1dc4-11e9-9603-a39e2ad85eee.png)

![image](https://user-images.githubusercontent.com/1409758/51497844-b50f8700-1dc4-11e9-927f-056298025f72.png)

**Comment by Templarian** [comment]
Very nice improvements @hulkhaugen! Thanks for revising these to match the MD guidelines.

I'll work to get these in shortly.

**Comment by hulkhaugen** [comment]
I tried that, but I personally went back to the bracket as that made it more obvious a lamp. Without it, I found it a bit hard to identify. However, I added it to the zip.

![image](https://user-images.githubusercontent.com/1409758/51500105-2a7f5580-1dcd-11e9-89ad-5e59e9bc8c43.png)

[mdi-extra.zip](https://github.com/Templarian/MaterialDesign/files/2780575/mdi-extra.zip)

**Comment by MrGrigri** [comment]
I would still simplify it. Like this. Remember that we try to stay on-grid as much as possible with all points. This helps when rasterizing the logo into a png. 

[![image](https://user-images.githubusercontent.com/4528551/51501173-1831f700-1d8e-11e9-89ba-b65e68077385.png)](https://github.com/Templarian/MaterialDesign/files/2780636/outdoor-lamp.zip)

**Comment by hulkhaugen** [comment]
Stay on grid, do you mean as the top of my lamp goes from 12.5px to 13.5px for instance, or do you mean the round shape on the bracket?

As I understand the guidelines, and as I believe I was criticized for from the first post, was to make the other outdoor-lamp-variant go all the way to the outer edges -2px, both sides and top/bottom. As I read the guidelines, it's either/or, unless it's a round shape. Or did I get it wrong?

I personally don't like your example as it's not how they actually look. The bracket is either in the top or the bottom. Then I'd prefer the bracket-less version. But that's my opinion. I also made a quick simpler bracket:

![image](https://user-images.githubusercontent.com/1409758/51502039-8a2d2f00-1dd4-11e9-9bde-67d697fa89c1.png)

I don't make the rules here, I just came with some suggestions. Do whatever pleases you ;)

**Comment by MrGrigri** [comment]
I do not mean to offend. We like what you've come up with, we're just trying to help with MD guidelines. The first rule is 2-pixels everywhere, as much as possible. At the top and bottom of the lamp, you have it terminating in 1-pixel. Second, on-grid means that every point is on a whole number as much as possible. This helps when rastering the icon. You can have curved elements, especially when dealing with object representation and not basic shapes. Also, these outside lamps come in many styles...mine on my house mount in the middle like in my example. And that bracket doesn't really matter much as the general shape is more than recognizable by itself. Especially when used in context.

**Comment by hulkhaugen** [comment]
Yes ok, I understand what you're saying now. Normally, those detail on such lamps are sharp like an arrow, so a 2px width would look bulky I think, but I'm not able to test it out now. That being said, those are guidelines and not laws. It's narrowing in towards 1px, it's not a straight 1px line going down or up, so it's almost an triangle. I personally think the ones I provided are ok, with or without the bracket. And I also think I prefer the last sharp bracket I made, but it doesn't show much on a small scale anyway.

Now I have another icon in mind also, and that should be a simple mirror (or glass), not that easy to visualize. What I have in mind is just a square with two or three diagonal lines in one corner to represent reflection. I might add that tonight if I can make something i'm happy with.

**Comment by Templarian** [comment]
Added the `pi-hole` icon in the issue marked as a duplicate. 😄

**Comment by hulkhaugen** [comment]
Cool, thanks. As far as I can see, noen of the other icons i created has made it to the pack. Is there a reason for that?

I never got a reply for the very first ´led-strip-variant´ icon I made. Looking at both of them, I think the ideal design might be something in between the two, as the second one has a bit too much detail and looks unclear.

**Comment by hulkhaugen** [comment]
As i'm impatient and wanted a way to ingrate my own icons now, I made my own (temporary?) icon pack. My icons from this post and a few more are available at: https://github.com/hulkhaugen/hass-bha-icons

**Comment by goyney** [comment]
Lots of good discussion in this thread, but at this point, we just need to get some lamps added. 😄 

Here are the 5 we're going to accept into the library, each has been brought in line with Material guidelines.

![image](https://user-images.githubusercontent.com/1015040/62016163-747f3480-b17e-11e9-99d8-b8a468afff22.png)![image](https://user-images.githubusercontent.com/1015040/62016173-882a9b00-b17e-11e9-89eb-da6c60c0fea7.png)
![image](https://user-images.githubusercontent.com/1015040/62016180-8fea3f80-b17e-11e9-9ffc-c8f45dbc1804.png)![image](https://user-images.githubusercontent.com/1015040/62016187-98427a80-b17e-11e9-9665-7db9047b917e.png)
![image](https://user-images.githubusercontent.com/1015040/62016219-d63f9e80-b17e-11e9-8925-bd1740ec05da.png)

[lamps.zip](https://github.com/Templarian/MaterialDesign/files/3439836/lamps.zip)

**Comment by goyney** [comment]
[![led-strip-variant](https://materialdesignicons.com/icon/led-strip-variant)](https://materialdesignicons.com/icon/led-strip-variant)
[![floor-lamp-variant](https://materialdesignicons.com/icon/floor-lamp-variant)](https://materialdesignicons.com/icon/floor-lamp-variant)
[![floor-lamp-dual](https://materialdesignicons.com/icon/floor-lamp-dual)](https://materialdesignicons.com/icon/floor-lamp-dual)
[![coach-lamp](https://materialdesignicons.com/icon/coach-lamp)](https://materialdesignicons.com/icon/coach-lamp)
[![outdoor-lamp](https://materialdesignicons.com/icon/outdoor-lamp)](https://materialdesignicons.com/icon/outdoor-lamp)
