### ISSUE TITLE
transfer-left, transfer-up, transfer-down

### ISSUE THREAD

**Issue by jonny123d** [Templarian/MaterialDesign#3838]
I find the mdi-transfer icon very useful to identify it with data transfer. They would be very useful left, right-left, up, down and up-down to identify different forms of data transfer such as reading, writing or reading / writing data.

mdi-transfer icon is made by @Templarian , I don't know if these variants are easy to make, but they would be useful.

**Comment by MrGrigri** [comment]
I know that a lot of people don't like hearing this...but you can just transform them using CSS.

**Comment by jonny123d** [comment]
But I'm not using this icon in web design, but in a desktop application in WPF (I know that I can rotate the text too). As there are several left / right icons (like mdi-arrow-expand-left, mdi-arrow-left, mdi-arrow-left-bold...), I thought it would not be bad to have them in the case of transfer.
In title changing you forgot transfer-left-right and transfer-up-down to duplex data transfer.

**Comment by Templarian** [comment]
Updated / Added. 😄 Breaking change unfortunately.
