### ISSUE TITLE
Aliases to be removed / updated (v3.5.xx)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3839]
- [x] `google-classroom`: `wallet-product` (icon has been repurposed)
- [x] `mailbox`: `markunread-mailbox` (stock icon name, icon since been redesigned)
- [x] `sim`: `subscriber-identification -module` (remove space)
- [x] `tennis-ball`: `tennis-ball` (icon has been renamed)
- [x] `water`: `drop` (duplicated alias)

**Comment by Templarian** [comment]
Resolved. Thanks!
