### ISSUE TITLE
apps-box

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3840]
Following on from a /team discussion the other day, here's Google's `play_apps` icon, which recently showed up in GSuite (original can be found [here](https://petershaggynoble.github.io/MDI-Sandbox/) if my poor attempt at resizing and optmmising it isn't up to scratch):

[![apps-box](https://user-images.githubusercontent.com/15157491/51491287-c8f7c080-1da5-11e9-9b30-cb8016c65589.png)](https://github.com/Templarian/MaterialDesign/files/2780023/play-apps.zip)

**Comment by Templarian** [comment]
Added. 😃
