### ISSUE TITLE
valve - Open / Closed states

### ISSUE THREAD

**Issue by gijbelsy** [Templarian/MaterialDesign#3842]

**Comment by Templarian** [comment]
Do you have an example of what you're looking for?

**Comment by gijbelsy** [comment]
An example can be found [here](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQyiilNCIOvx9oTR-dX0UCw7GjkTDyvySP2QsS0FsusFaorSA9i)

**Comment by Templarian** [comment]
That's probably going to be too specific for us to add. This looks more like a diagram specific icon. Was thinking more of a "valve" for water/liquids/gas then we might be able to add that.

**Comment by gijbelsy** [comment]
Well, that's fine too. This example is used in PID schematics.
Just need a representation for a valve so I can use this for my heating valve to state open or closed.

**Comment by Templarian** [comment]
Related to #3071, but seeing as that one is just for water specifically lets keep this one open to track the actual valve states. 😃

**Comment by MrGrigri** [comment]
Closing in favor of #4077.
