### ISSUE TITLE
fit-to-page/stretch-to-page

### ISSUE THREAD

**Issue by Asatelit** [Templarian/MaterialDesign#3844]
There are a couple of icons that I would like to offer you, please take a look:
![zoom-control-icons](https://user-images.githubusercontent.com/5496004/51525897-e1191f80-1e39-11e9-9251-ba1dd4e04941.png)

[Icons.zip](https://github.com/Templarian/MaterialDesign/files/2782119/Icons.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/51865190-a4569800-2313-11e9-8ad8-46f9f3d397b2.png)![image](https://user-images.githubusercontent.com/1015040/51865179-9b65c680-2313-11e9-8fad-382f9021a692.png)
![image](https://user-images.githubusercontent.com/1015040/51865208-b0daf080-2313-11e9-8e9d-eeca17de644e.png)![image](https://user-images.githubusercontent.com/1015040/51865225-b9cbc200-2313-11e9-8283-86802a96656e.png)

**Comment by Templarian** [comment]
Added all 4. 😃
