### ISSUE TITLE
OpenBadges

### ISSUE THREAD

**Issue by wilmouths** [Templarian/MaterialDesign#3845]
It's possible to add OpenBadges logo to make an icon ?
For example : https://imgur.com/a/dX1saeY

**Comment by PeterShaggyNoble** [comment]
If you're referring to https://openbadges.org/ then I'm afraid that that would be beyond the current scope of this project (their current global traffic rank is 318,178).

If it ever does take off, though, please leave a comment here and we'll revisit this issue. In the meantime, you could try requesting it from [Simple Icons](https://simpleicons.org/), where it would be within scope.
