### ISSUE TITLE
Dependency / Dependent

### ISSUE THREAD

**Issue by Z4D** [Templarian/MaterialDesign#3846]
I have looked all over the web including your icon library, however still couldn't find an icon that would fit/suit my purpose!

Dependent icon or dependency icon could be used where we have some dependencies that we would like to show in our design, in my case I have a bunch of form controls that are dependent on some other form controls of which I want the user to know and understand without giving it a text as that takes so much room and it's not an option!

I have no clue of what should the icon look alike or at least be around, my closest guess would be jigsaw puzzle icon but that's my last choice if I couldn't get hold of a decent icon!

Thanks in advance :)

**Comment by MrGrigri** [comment]
I know that it could be a bit abstract, but we do have `human-male-boy` that could work.

![human-male-boy](https://materialdesignicons.com/icon/human-male-boy)

**Comment by Z4D** [comment]
> I know that it could be a bit abstract, but we do have `human-male-boy` that could work.
> 
> ![human-male-boy](https://camo.githubusercontent.com/47dcf30df66dece12e3ad8b619e0d46cdc52fc3e/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f68756d616e2d6d616c652d626f79)

Thanks for the reply but unfortunately this icon wouldn't be suitable for a form control that's dependents on some other form control! It needs to be as generic as possible.

**Comment by MrGrigri** [comment]
Could something like this work?

[![image](https://user-images.githubusercontent.com/4528551/51705818-e319e480-1fd9-11e9-87c0-aa0fb8376364.png)](https://github.com/Templarian/MaterialDesign/files/2793416/dependency.zip)

**Comment by goyney** [comment]
I don't think those arrows work at 1x.

**Comment by goyney** [comment]
See also: https://github.com/Templarian/MaterialDesign/issues/910

**Comment by MrGrigri** [comment]
Yeah...I'm in favor of #910.

**Comment by Z4D** [comment]
> Yeah...I'm in favor of #910. Would this work for you @Z4D?

Actually, I'm not against it, it showcases parent-child relationship as in tree roots, not bad at all...
Let me present it to my team and see what they all think...

Thanks

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #910 for now. @Z4D, if that doesn't suit your team's needs, please feel free to reopen this issue with their feedback.
