### ISSUE TITLE
Sonoff

### ISSUE THREAD

**Issue by lmesousa** [Templarian/MaterialDesign#3847]
So, I need some icons... who knows I will become a contributor!

![images](https://user-images.githubusercontent.com/46972464/51626719-160b9c00-1f38-11e9-97bd-98c05a8d382c.jpg)

**Comment by Templarian** [comment]
This might be too niche of a brand for us to add at this time. Do they have a square logo that could fit in the small size?

**Comment by goyney** [comment]
I believe Sonoff has a brand identity crisis.
![screen shot 2019-01-28 at 9 36 40 am](https://user-images.githubusercontent.com/1015040/51843072-45c3f680-22e0-11e9-8d16-1fdb5503cd3e.png)

Their brand name, favicon, and app icons are all different. I also agree with @Templarian that this seems pretty niche and do not see a square logo that is definitively theirs. Closing for now.
