### ISSUE TITLE
format-comma-*

### ISSUE THREAD

**Issue by spencerfeng** [Templarian/MaterialDesign#3848]
Can we have a comma icon which can be used in number format separator scenario.

**Comment by Templarian** [comment]
Really surprised we don't have this one already. This needs a `-box` / `box-outline` variant also.

**Comment by MrGrigri** [comment]
I used the `format-quote-close` for this as I wanted to keep them consistent. And I also add a `circle` and `circle-outline` version as well. I tried a `format-comma-outline` as well, but that didn't look so good.

![format-comma](https://user-images.githubusercontent.com/4528551/51705263-62a6b400-1fd8-11e9-8685-7cf07bfb4dba.png)
![image](https://user-images.githubusercontent.com/4528551/51705321-908bf880-1fd8-11e9-9126-b75a27250aa0.png) ![image](https://user-images.githubusercontent.com/4528551/51705347-a39ec880-1fd8-11e9-9200-b1fbfac95c3d.png)
![image](https://user-images.githubusercontent.com/4528551/51705371-b44f3e80-1fd8-11e9-8b3a-cca50622f0fa.png) ![image](https://user-images.githubusercontent.com/4528551/51705401-c630e180-1fd8-11e9-93b9-49e978692928.png)

---

[format-comma.zip](https://github.com/Templarian/MaterialDesign/files/2793397/comma.zip)

**Comment by Templarian** [comment]
I'm wondering if this should be offset to the bottom and smaller. Because we'll probably have a period also and that would also look nicer toward the bottom of the circle/square. 🤔

**Comment by MrGrigri** [comment]
I don't think a `format-period` would look ok, and if you add it to a `box` or `circle`, then they'll just look like weird checkboxes or radio buttons, especially if they are off-center.

**Comment by Templarian** [comment]
Added all 5. 😃
