### ISSUE TITLE
Billboard / Hoarding

### ISSUE THREAD

**Issue by sureshreddyputta** [Templarian/MaterialDesign#3849]
Can you please provide Hoarding Icon.

![image](https://user-images.githubusercontent.com/21020661/51725862-862a3700-208a-11e9-8582-d2217060b265.png)

**Comment by Templarian** [comment]
Do you have an example of what this might look like?

**Comment by sureshreddyputta** [comment]
Yeah Sure, I can provide you a sample image

[image: image.png]


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
25/01/19,
10:08:47 AM

**Comment by Templarian** [comment]
@sureshreddyputta Email attachments don't work. You can edit the above comment and paste in images. 😺

**Comment by MrGrigri** [comment]
[![image](https://user-images.githubusercontent.com/4528551/51998938-e4825b80-2476-11e9-8c8c-bd067eaae6cb.png)billboard.zip](https://github.com/Templarian/MaterialDesign/files/2813661/billboard.zip)

**Comment by goyney** [comment]
[![billboard](https://materialdesignicons.com/icon/billboard)](https://materialdesignicons.com/icon/billboard)
