### ISSUE TITLE
Thumbs up outline icon

### ISSUE THREAD

**Issue by sumitbrt** [Templarian/MaterialDesign#385]
Thank you so much for the icons. Please, could you also add an icon of thumbs up outline. It would sever as "pre-like" icon.

- [ ] thumbs-up-outline
- [ ] thumbs-down-outline

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/thumb-up-outline
http://materialdesignicons.com/icon/thumb-down-outline
