### ISSUE TITLE
Gantry

### ISSUE THREAD

**Issue by sureshreddyputta** [Templarian/MaterialDesign#3850]
Can you Please provide Gantry Icon.

**Comment by Templarian** [comment]
There is a `pier-crane` icon, but yea no gantry.

**Comment by sureshreddyputta** [comment]
Thank you but what I need is a Gantry icon.

**Comment by MrGrigri** [comment]
I just took the structure of the crane and created this one.

[![image](https://user-images.githubusercontent.com/4528551/51921004-c0a21580-23a3-11e9-867f-0ece51cee09d.png)](https://github.com/Templarian/MaterialDesign/files/2808470/gantry-crane.zip)

**Comment by Templarian** [comment]
Added.
