### ISSUE TITLE
bus-stop-covered

### ISSUE THREAD

**Issue by sureshreddyputta** [Templarian/MaterialDesign#3851]
can you please provide bus shelter Icon

![image](https://user-images.githubusercontent.com/21020661/51725712-ecfb2080-2089-11e9-8c45-3a4e8c524699.png)

**Comment by PeterShaggyNoble** [comment]
Related: #1253

**Comment by sureshreddyputta** [comment]
I need a Bus Shelter Icon, not this([#1253]) one.

**Comment by MrGrigri** [comment]
I believe this would not work well as an icon. I can not conceive of a situation where there would need to be icons that depict the different types of bus stops. Please refer to the aforementioned issue for a `bus-stop` icon that now has a possible contribution.

**Comment by Templarian** [comment]
We might be able to depict this with a Chicago style bus stop. This one's outside my office:

![image](https://user-images.githubusercontent.com/338885/51859461-c7c21880-22fc-11e9-945f-9feeb11284d7.png)

**Comment by Templarian** [comment]
This style are becoming more common in cities for the last few years, but not sure how recognizable they would be in Europe etc.

**Comment by MrGrigri** [comment]
I'm not by any means stating that they are uncommon, merely that I do not see a need to have two separate icons to represent a bus stop.

**Comment by Templarian** [comment]
Agreed. Covered vs Uncovered bus stop makes sense. We don't need two bus stops, but this difference is useful.

- `bus-stop-covered`

**Comment by MrGrigri** [comment]
I'm going to close this in favor of the aforementioned issue. As I have included a covered variation.

**Comment by MrGrigri** [comment]
@sureshreddyputta, if this does not cover your situation, please feel free to re-open this issue
