### ISSUE TITLE
Footover Bridge

### ISSUE THREAD

**Issue by sureshreddyputta** [Templarian/MaterialDesign#3855]
Can you Please Provide Footover Bridge Icon.

![image](https://user-images.githubusercontent.com/21020661/51726159-f1c0d400-208b-11e9-9206-242185d8f7d1.png)

**Comment by PeterShaggyNoble** [comment]
Would the general purpose `bridge` icon not cover this?

**Comment by sureshreddyputta** [comment]
No

**Comment by goyney** [comment]
Closing this issue because the `Consider Closing` and `Needs More Information` tags have been on it for well over 10 days. Please comment back here if you still need this and are able to provide more examples of what you're looking for. Thanks!
