### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by MathiasKandelborg** [Templarian/MaterialDesign#3859]
So I've been searching for an icon to use for a blog/news page. The default google news icon does not fit into the overall 'rounded' aesthetic I'm searching for and all other icons are using (in my perspective).

What I've been searching for:

https://thenounproject.com/term/blog/344251/

https://thenounproject.com/term/blog/240736/

There's a bunch more [great examples of a blog/news icon here](https://thenounproject.com/term/blog/)

It could simply be called `blog`.

**Comment by goyney** [comment]
`newspaper` satisfies this use case.

If you're looking for something with rounded corners specifically, checkout the `file-document-box` icons.

**Comment by MathiasKandelborg** [comment]
I got it! file-document-box-multiple

Thanks!

Could file-document-box maybe have an alias like:

- text-lines-box
- lines-box
- article-box
- blog-box

Or anything other than file-document, as I've literally spent several minutes googling and thinking about alternatives to text-box, article, blog, news etc. and I would never have found this icon if it wasn't for you suggesting it (except meticulously going through every icon, which I tried but... you know, there's a lot)

I'm guessing I'm not the only one who's been searching for 'news', 'article', 'blog', 'text' in hopes that a box with lines of text and maybe even containing an image icon would appear. 

Thanks once again.

**Comment by PeterShaggyNoble** [comment]
Google do have a lot of other news related icons (e.g., `full_-coverage` from Material Icons Extended) and even more that could be used to represent a blog (entry).

![full_-coverage](https://user-images.githubusercontent.com/15157491/51842913-e11d9180-2309-11e9-86f7-18f84b3a8176.png)

**Comment by MathiasKandelborg** [comment]
@PeterShaggyNoble This icon is a lot to my vision of a MD news/blog icon.

**Comment by goyney** [comment]
Nice find, @PeterShaggyNoble.

**Comment by MathiasKandelborg** [comment]
Is it okay if I try my best with Inkscape and give creating icons a go? I'd be more than happy to, I've just been thinking this got implemented quite quickly and would love to experience working _properly_  with SVG's.

**Comment by goyney** [comment]
@MathiasKandelborg Sure, you can do whatever you like. If you make icons you feel would make a good fit into the library, please create an issue per icon for us to consider adding.

Also, just a side note, nothing has been implemented in this issue yet. I'll gather the source from the stock Google icons and get them posted so they can be included in an upcoming release over the next few months.

**Comment by goyney** [comment]
All icons added. 😄
