### ISSUE TITLE
swiss-cross/hospital variants

### ISSUE THREAD

**Issue by EthanKing96** [Templarian/MaterialDesign#3860]
*Rename:*
- [ ] `hospital` => `hospital-box`

*Add:*
- [ ] `hospital`
- [ ] `hospital-box-outline`

**Comment by goyney** [comment]
We already have `hospital`, but it should be renamed `hospital-box`. Then we can add a new `hospital`.
[![hospital](https://materialdesignicons.com/icon/hospital)](https://materialdesignicons.com/icon/hospital)
![image](https://user-images.githubusercontent.com/1015040/51876482-ae3dc280-2336-11e9-9b79-371fc58fa263.png)

---

We can then alias each of this with `swiss-cross`.

---

[hospital.svg.zip](https://github.com/Templarian/MaterialDesign/files/2805564/hospital.svg.zip)

**Comment by goyney** [comment]
@EthanKing96 We'll close this issue once the icons have been added to the library.

**Comment by EthanKing96** [comment]
Sounds good. Thanks for being so responsive!

**Comment by JamesCoyle** [comment]
Could probably Have an outline version of the non-box variant

**Comment by goyney** [comment]
Updated, added, and aliased!
