### ISSUE TITLE
wizard-hat

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3862]
This one's open for discussion because I'm not a fan of the details being lost at 1x and the fact that this specific design doesn't work in an outline fashion.

![image](https://user-images.githubusercontent.com/1015040/52004904-53bb7800-2496-11e9-82c9-d7f5bf7b79bd.png)

[wizard-hat.svg.zip](https://github.com/Templarian/MaterialDesign/files/2814020/wizard-hat.svg.zip)

**Comment by MrGrigri** [comment]
I'm not a fan of the folded tip.

**Comment by PeterShaggyNoble** [comment]
We could probably adapt this one for a witch's hat, too.

**Comment by CoDEmanX** [comment]
Maybe use the stars from e.g. silverware-clean?

**Comment by goyney** [comment]
[![wizard-hat](https://materialdesignicons.com/icon/wizard-hat)](https://materialdesignicons.com/icon/wizard-hat)
