### ISSUE TITLE
New Icons

### ISSUE THREAD

**Issue by ovirogo** [Templarian/MaterialDesign#3863]
Hi,
New icons a, medical doctor, nurse, police, fireman, synagogue, torah, medical prescription (R), plane pilot, teacher/professor, musical instruments.
All this with its respective variants (male, female) when is the case.
Thank you for your attention
Have a nice day

**Comment by goyney** [comment]
Thanks for the suggestions. Please make use of the search functionality of both the MDI website and of GitHub as most of these icons already exists or have been requested. Also, please limit each issue to one icon request.

- **Doctor:** https://materialdesignicons.com/icon/doctor
- **Nurse:** https://github.com/Templarian/MaterialDesign/issues/2621
- **Police:** https://github.com/Templarian/MaterialDesign/issues/1343
- **Fireman:** N/A
- **Pilot:** N/A
- **Synagogue:** N/A
- **Torah:** N/A
- **Medical Prescription:**  https://materialdesignicons.com/icon/prescription
- **Teacher**: https://materialdesignicons.com/icon/teach
- **Musical Instruments:** What are you looking for? We have `saxophone`, but definitely have room to grow here.

I'm going to close this issue. Please reopen separate issues for the 4 missing icons and any instruments you need.
