### ISSUE TITLE
chart-bell-curve-cumulative

### ISSUE THREAD

**Issue by jacobq** [Templarian/MaterialDesign#3864]
Similar to #3697 (:heart:) I would like a chart icon resembling a [cumulative distribution function](https://en.wikipedia.org/wiki/Cumulative_distribution_function) or at least one that never decreases.
Perhaps it could look something like this:
![cdf-icon](https://user-images.githubusercontent.com/1633459/52006362-8dd64b00-2491-11e9-80fe-9084f4ab1824.png)

I would like to use this to identify a "plot cumulative" option vs. a "plot" option. Alternatively, having a chart icon with a capital sigma or plus sign on it might also work.

**Comment by jacobq** [comment]
Perhaps a more clear way to express this would be to show 2 traces on the plot, one dotted or dashed -- perhaps following the shape of the one in `mdi-chart-line` -- and then another which indicates the integral of that trace (e.g. if the first function is constant then it is linear, if the first function is linear then it is quadratic, etc.). The challenge with this approach is keeping it clear that we're talking about two traces/function, not, say, a function and a threshold / cursor.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52009808-cd0c9800-24a1-11e9-9a48-5a3f699c26ec.png)
[chart-bell-curve-cumulative.svg.zip](https://github.com/Templarian/MaterialDesign/files/2814274/chart-bell-curve-cumulative.svg.zip)

**Comment by jacobq** [comment]
> Maybe we could alias this as "[sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function)".

That's fine with me. However, for those it might be better to draw the vertical axis through the middle instead of on the left.

**Comment by goyney** [comment]
[![chart-bell-curve-cumulative](https://materialdesignicons.com/icon/chart-bell-curve-cumulative)](https://materialdesignicons.com/icon/chart-bell-curve-cumulative)
