### ISSUE TITLE
Additional Home Floor Numeric 0 and -1

### ISSUE THREAD

**Issue by Roemer** [Templarian/MaterialDesign#3866]
As stated in the title, please add additional floor icons with a numeric `-1` and `0` as they are more common in EU.
Not sure if the `-1` is going to work as that would contain two characters. Alterntives would be to add other variants for different languages (like `K` for the German `Keller`).
They should fit into the new icons created in #1964.

**Comment by goyney** [comment]
We discussed internally and are fine with adding 0 and -1, but won't add any more letters at this time.

![image](https://user-images.githubusercontent.com/1015040/52665704-2fba5680-2eda-11e9-80db-d589dcddffd0.png)![image](https://user-images.githubusercontent.com/1015040/52665724-39dc5500-2eda-11e9-9753-04ac820aab4a.png)

[floors.zip](https://github.com/Templarian/MaterialDesign/files/2857521/floors.zip)

**Comment by Templarian** [comment]
Added, but added `-1` as `home-floor-negative-1`.

**Comment by zappasmart** [comment]
I know it was decided not to have more numbers.
I need an icon to identify an apartment number 4, and thought it could be useful to have all numeric variants available in case they are used for apartment numbers and not actual floors.
I have submitte an icon request for the purpose:
https://github.com/Templarian/MaterialDesign/issues/4902
