### ISSUE TITLE
neighborhood

### ISSUE THREAD

**Issue by arup42** [Templarian/MaterialDesign#3869]
I'd like an icon to represent a group of homes, or a neighborhood. Many reasonable examples of what would be nice come up if you search Google for "neighborhood icon". This is useful in contexts related to both real estate and sharing things between homes (e.g. in an IOT devices context.) I think something that has 3 or 4 homes staggered next to each other would work well. Here are some examples: 

https://www.shutterstock.com/image-vector/town-buildings-icon-vector-style-flat-477520993?src=ckBwqCL-Z4SgTvwpb3SPVw-1-2

https://www.shutterstock.com/image-vector/neighbourhood-icon-professional-pixel-perfect-icons-367821761?src=ckBwqCL-Z4SgTvwpb3SPVw-1-30

https://www.shutterstock.com/image-vector/neighbourhood-icon-professional-pixel-perfect-icons-367821758?src=ckBwqCL-Z4SgTvwpb3SPVw-1-21

**Comment by MrGrigri** [comment]
I'm not sure if this will work, but this is my attempt

[![image](https://user-images.githubusercontent.com/4528551/52142939-70cb8480-2617-11e9-8967-5f840e504ea9.png)](https://github.com/Templarian/MaterialDesign/files/2822910/home-multiple.zip)

**Comment by arup42** [comment]
This actually looks pretty good to me. I'm happy with it as-is, but if you feel like tweaking it at all, I think it might be a little nicer if you raised the two rear homes a bit so that their entire roof lines are visible. 
Thanks for the quick response!

**Comment by PeterShaggyNoble** [comment]
I agree with @arup42; it might look better with the back 2 houses sitting higher on the canvas and/or the front house sitting lower.

Also, we should probably name this one `home-group` and add a `home-multiple` consistent with our other `*-multiple` variants.

**Comment by Templarian** [comment]
[![home-group](https://materialdesignicons.com/icon/home-group)](https://materialdesignicons.com/icon/home-group)

Does this work? Kind of tried to make the back two at different levels.

**Comment by arup42** [comment]
This is still fine with me (as was the original), and this adds a little more depth, so in that sense it's better. Thanks for your effort in working on this!.

However, my original comment was that I think it would be nice to move the homes enough that the complete roof lines of the two rear homes would be visible (i.e. all three points of the roof triangle of each home would be visible, rather than just two points currently visible for the two rear homes). That suggestion still applies.

**Comment by Templarian** [comment]
Reopening this, I think there is enough room to do that, we'll just need to play around with the spacing a little.

**Comment by MrGrigri** [comment]
Here is another version.

[![home-group](https://user-images.githubusercontent.com/4528551/53029598-75b97200-3426-11e9-8e91-e302cae0cb6e.png)](https://github.com/Templarian/MaterialDesign/files/2880842/home-group.zip)

**Comment by arup42** [comment]
Thanks again ...  This looks good too. At the largest size, I think it would be a tiny bit better if the rightmost home were one square lower, so that the apexes of the roofs of the two rear homes are not aligned vertically. However you can't really see this difference at the small sizes anyway, so feel free to leave it as is.

**Comment by Templarian** [comment]
Updated.

**Comment by PeterShaggyNoble** [comment]
Personally, I still prefer @MrGrigri original contribution, but with the 3 houses moved as per my comment above. Having multiple levels looks a bit off in relation to the standards set in our other icons, especially at native size.

**Comment by arup42** [comment]
I would be fine with @PeterShaggyNoble 's suggestion too.
