### ISSUE TITLE
Ozone revisited

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3870]
aware of https://github.com/Templarian/MaterialDesign/issues/3222 I feel it might be worthwhile having another go...
this is not just some element, but a crucial one in our environmental data. And in fact ine of the left missing icons to represent eg the dark_sky sensors and other air-quality and weather components.

please reconsider and add an icon like this:

![ozone](https://user-images.githubusercontent.com/33354141/52106407-f2f58200-25f2-11e9-9645-52eed052f664.png)

**Comment by goyney** [comment]
That icon doesn't really work because ozone isn't in any way representative of a cloud.

We'll discuss this internally since it deals with two closed issues on the topic.

**Comment by goyney** [comment]
We've once again come to the same conclusion. We do not wish to add a ton of chemical compounds to the library.

Personally, I would just use `earth` for the ozone sensor. Icons are meant to supplement content, and using `earth` in context with ozone makes sense.

Thanks for your suggestion.
