### ISSUE TITLE
protocol

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3871]
Internal request for `protocol`

[![image](https://user-images.githubusercontent.com/4528551/52141170-1845b880-2612-11e9-90bf-ee57aef05c40.png)](https://github.com/Templarian/MaterialDesign/files/2822781/protocol.zip)

**Comment by Templarian** [comment]
I think the modifiers are a little overkill, but we should probably move the `:` up one dp. Looks too low right now.

**Comment by goyney** [comment]
[![protocol](https://materialdesignicons.com/icon/protocol)](https://materialdesignicons.com/icon/protocol)
