### ISSUE TITLE
diving-*

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3873]
I'm consolidating #2605 and #3867 into a diving category. 

#### Icons

![image](https://user-images.githubusercontent.com/4528551/52148502-19cdab80-2627-11e9-84e6-04d1f890cdbb.png) ![image](https://user-images.githubusercontent.com/4528551/52148363-a88df880-2626-11e9-8ce1-8d35492ca622.png) ![image](https://user-images.githubusercontent.com/4528551/52148336-957b2880-2626-11e9-9d90-4d28a8f62ea5.png) ![image](https://user-images.githubusercontent.com/4528551/52148395-c78c8a80-2626-11e9-89a3-fe5e7b3fc919.png) ![image](https://user-images.githubusercontent.com/4528551/52148422-d4a97980-2626-11e9-8650-6cc70179c1f8.png) ![image](https://user-images.githubusercontent.com/4528551/52148436-e0953b80-2626-11e9-8c17-29aff15e778a.png) ![image](https://user-images.githubusercontent.com/4528551/52148892-52ba5000-2628-11e9-814a-e9ba2b4acc41.png)

---

### Files

[diving.zip](https://github.com/Templarian/MaterialDesign/files/2823304/diving.zip)

**Comment by kmlucy** [comment]
I have a few suggestions if you're open to it. For the helmet, the hoses didn't come to the top of the helmet, they came to the suit. I would remove the hose, add a third protrusion to the top of the helmet, and make the collar/base extend a little farther down. 

For the flag, the proportions look a little off to me. I think the stripe should be a little thicker.

Other than that, they look great!

**Comment by Templarian** [comment]
Added these 7 icons.
