### ISSUE TITLE
Pencil Variations

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3874]
The modifiers are following `pencil-lock` and generally look better in the top corner than the bottom.

![image](https://user-images.githubusercontent.com/1015040/52159570-38a65f00-2674-11e9-8147-dddadb0886e6.png)![image](https://user-images.githubusercontent.com/1015040/52159587-6095c280-2674-11e9-895d-998eacbb8dce.png)
![image](https://user-images.githubusercontent.com/1015040/52159583-4a880200-2674-11e9-9770-996452256706.png)![image](https://user-images.githubusercontent.com/1015040/52159585-51167980-2674-11e9-9068-3aece47cd507.png)
![image](https://user-images.githubusercontent.com/1015040/52171217-220d1000-2727-11e9-87f3-6321a08b557b.png)![image](https://user-images.githubusercontent.com/1015040/52171215-1a4d6b80-2727-11e9-8a3a-cadeb3afd071.png)

---

[pencils.zip](https://github.com/Templarian/MaterialDesign/files/2825077/pencils.zip)

**Comment by Templarian** [comment]
Added.
