### ISSUE TITLE
file-document-edit-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3876]
Missing outline variation:

![image](https://user-images.githubusercontent.com/1015040/52159680-aa32dd00-2675-11e9-84a7-a3a4457315c9.png)

---

[file-document-edit-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2824023/file-document-edit-outline.svg.zip)

**Comment by Templarian** [comment]
[![file-document-edit-outline](https://materialdesignicons.com/icon/file-document-edit-outline)](https://materialdesignicons.com/icon/file-document-edit-outline)
