### ISSUE TITLE
texture-box

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3877]
Boxed version of `texture`.

![image](https://user-images.githubusercontent.com/1015040/52159688-ca629c00-2675-11e9-8d49-b640608e510c.png)

---

[texture-box.svg.zip](https://github.com/Templarian/MaterialDesign/files/2824024/texture-box.svg.zip)

**Comment by CoDEmanX** [comment]
Somewhat looks like a window pane - should we add something like that as well?

What other icons would one use this with? Filled and outline square?

**Comment by goyney** [comment]
[![texture-box](https://materialdesignicons.com/icon/texture-box)](https://materialdesignicons.com/icon/texture-box)
