### ISSUE TITLE
draw

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3878]
![image](https://user-images.githubusercontent.com/1015040/61757748-e6770880-ad8f-11e9-9512-4615b909354a.png)
[draw.svg.zip](https://github.com/Templarian/MaterialDesign/files/3424607/draw.svg.zip)

**Comment by Templarian** [comment]
What about the line with the `x_`, where the x is a bit larger?

[![signature](https://materialdesignicons.com/icon/signature)](https://materialdesignicons.com/icon/signature)

**Comment by goyney** [comment]
The x-line are types of signature, but we also already use an icon to represent the act of signing, which this icon is required for.

**Comment by JamesCoyle** [comment]
Should we name this `draw` or something and alias `sign` and `signature`? It looks more like a freehand draw icon to me and we already have a signature-freehand:

[![](https://materialdesignicons.com/icon/signature-freehand
)](https://materialdesignicons.com/icon/signature-freehand)

**Comment by goyney** [comment]
[![draw](https://materialdesignicons.com/icon/draw)](https://materialdesignicons.com/icon/draw)
