### ISSUE TITLE
Cafe, Bar, Restaurant

### ISSUE THREAD

**Issue by treylon** [Templarian/MaterialDesign#388]
Would be nice to have icons for Cafes, Bars and Restaurants. For instance when using Google Places.

- [x] cafe
- [ ] bar
- [x] resturant

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/coffee 
http://www.google.de/design/icons/#ic_local_bar - yet to be added #420 
https://materialdesignicons.com/icon/silverware - what Google uses for restaurant / dining

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/martini = `ic_local_bar`
