### ISSUE TITLE
folder-transfer

### ISSUE THREAD

**Issue by dbenitez-bcn** [Templarian/MaterialDesign#3880]
Hi everyone!
I'm making a project for college and i need an icon about FTP. Looking for some icons I did not find any with the features I needed, so i start designing my own one. Here is the design. Hope it would be helpful to somebody.
Greetings :D
![file-transfer](https://user-images.githubusercontent.com/39645422/52160959-82b43280-26be-11e9-9b45-5a0bfafe1276.png)
![file-transfer_v2](https://user-images.githubusercontent.com/39645422/52161044-957b3700-26bf-11e9-8c0c-ca4e870bcd4e.png)

SVG & Example: https://we.tl/t-gkqEImE6gj

**Comment by MrGrigri** [comment]
Would `folder-network` not suffice? If we want to add a `file-transfer`, which I'm not opposed to, we should use the same cutout as `bank-transfer` and not `transit-transfer`.

**Comment by goyney** [comment]
@MrGrigri The `bank-transfer` cutout only works if we make the folder smaller, which I'm not sure if we should do. Regardless, I believe the arrows should some how be contained within the folder. And remember, we would need an `outline` version as well.

**Comment by MrGrigri** [comment]
Yeah...this is the best that I could think of. Not sure if it coveys the right meaning. 

![file-transfer](https://user-images.githubusercontent.com/4528551/52220383-f2135900-285b-11e9-95a0-0184f92626a5.png) ![file-transfer-outline](https://user-images.githubusercontent.com/4528551/52220393-f8a1d080-285b-11e9-8d7d-7c669a7e0b24.png)

---

#### SVG

[file-transfer.zip](https://github.com/Templarian/MaterialDesign/files/2828774/file-transfer.zip)

**Comment by MrGrigri** [comment]
Yeah...I don't think it'll hurt. I'll create a new issue for that.

**Comment by goyney** [comment]
[![folder-swap](https://materialdesignicons.com/icon/folder-swap)](https://materialdesignicons.com/icon/folder-swap)[![folder-swap-outline](https://materialdesignicons.com/icon/folder-swap-outline)](https://materialdesignicons.com/icon/folder-swap-outline)
