### ISSUE TITLE
It's curtains for the lot of you!

### ISSUE THREAD

**Issue by robotsandcake** [Templarian/MaterialDesign#3881]
Hello, @GreenTurtwig Suggested on the Twitters that this is where I should post requests for icons for a special version of Home Assistant I'm putting together specifically for quadriplegics and other disabled people like me.

Curtains, I would like a pair of icons that denote “curtains open” and "curtains closed" if at all possible please. I have no design input as I am not a designer and you guys are much better at this than me. I will say however that I do like the outline type icons the best. :-)

Happy Sunday!
[@robotsandcakes](https://twitter.com/robotsandcakes?lang=en) on the Twitters, and [robotsandcake](https://keybase.io/robotsandcake) on Keybase.io

**Comment by PeterShaggyNoble** [comment]
Duplicate of #2523
