### ISSUE TITLE
Signature Types

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3884]
Somewhat related to #3878, there are a few ways to "digitally" sign a document. These indicate those types:

![image](https://user-images.githubusercontent.com/1015040/52187006-dcb91300-27f8-11e9-89ae-04cb0b27d32b.png)![image](https://user-images.githubusercontent.com/1015040/52187013-e3e02100-27f8-11e9-9864-c9a6c28e76ac.png)
![image](https://user-images.githubusercontent.com/1015040/52187018-ea6e9880-27f8-11e9-855d-80dfca1c4518.png)

[signature-types.zip](https://github.com/Templarian/MaterialDesign/files/2826309/signature-types.zip)

**Comment by MrGrigri** [comment]
Idk how I feel about the decagram. Wouldn't a rectangle be better?

**Comment by goyney** [comment]
That was actually what I first made:
![image](https://user-images.githubusercontent.com/1015040/52219610-fd21b580-286a-11e9-9b92-bb6727b0cd72.png)

[sign-image-alt.svg.zip](https://github.com/Templarian/MaterialDesign/files/2828739/sign-image-alt.svg.zip)

I didn't like the square edge on the right side and I felt that the starburst shape made it feel more "official," like a seal or something. 🤷‍♂️

**Comment by MrGrigri** [comment]
Yeah, I'm just thinking of when I sigh with an image, it's always in a rectangle.

**Comment by Templarian** [comment]
The sign freehand should probably be the letter S[igature] or A[utograph]. `sign-*` is already used, so `signature`.
