### ISSUE TITLE
Redaction

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3885]
These may have a more generic name (such as `-disabled`), but we don't have a precedent for that naming in the library currently, because any "disabled" states we have are typically with a slash and `-off`. We do have `cancel`, which is the no symbol, so maybe `file-cancel` and `marker-cancel`?

Redact an entire file/document:
![image](https://user-images.githubusercontent.com/1015040/52187694-f0ff0f00-27fc-11e9-86f0-c21247f9df1c.png)![image](https://user-images.githubusercontent.com/1015040/52187726-2ad01580-27fd-11e9-9f4f-7387a6a4fdbb.png)

Redact by text selection:
![image](https://user-images.githubusercontent.com/1015040/52187738-358aaa80-27fd-11e9-8e6d-d41c1eb8d7e2.png)

**Comment by Templarian** [comment]
Added as `cancel`.
