### ISSUE TITLE
file-transfer

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3886]
In response to #3880, we're also going to create a `file-transfer` and `file-transfer-outline` to match.

![image](https://user-images.githubusercontent.com/4528551/52221275-0e17fa00-285e-11e9-9961-6412d78156fa.png) ![image](https://user-images.githubusercontent.com/4528551/52221293-140ddb00-285e-11e9-9216-5921901445ea.png)

---
#### Files

[file-transfer.zip](https://github.com/Templarian/MaterialDesign/files/2828854/file-transfer.zip)

**Comment by Templarian** [comment]
Not a huge fan of the `<->` to represent a transfer. Tried a few ideas, but not happy with them either.

**Comment by MrGrigri** [comment]
To me, it symbolizes more of a swap than a transfer/move. Since we already have `folder-move` and `file-move` icons, maybe we should rename these to `folder-swap` and `file-swap`.

**Comment by goyney** [comment]
[![file-swap](https://materialdesignicons.com/icon/file-swap)](https://materialdesignicons.com/icon/file-swap)[![file-swap-outline](https://materialdesignicons.com/icon/file-swap-outline)](https://materialdesignicons.com/icon/file-swap-outline)
