### ISSUE TITLE
Bolt - Screw - nail 

### ISSUE THREAD

**Issue by Dimtrivh** [Templarian/MaterialDesign#3887]

**Comment by goyney** [comment]
Without anything being added, you could use the following for each:

Bolt:
[![hexagon](https://materialdesignicons.com/icon/hexagon)](https://materialdesignicons.com/icon/hexagon)

Flathead Screw:
[![minus-circle](https://materialdesignicons.com/icon/minus-circle)](https://materialdesignicons.com/icon/minus-circle)

Phillips Screw:
[![close-circle](https://materialdesignicons.com/icon/close-circle)](https://materialdesignicons.com/icon/close-circle)[![plus-circle](https://materialdesignicons.com/icon/plus-circle)](https://materialdesignicons.com/icon/plus-circle)

Nailhead:
[![circle](https://materialdesignicons.com/icon/circle)](https://materialdesignicons.com/icon/circle)

**Comment by Dimtrivh** [comment]
Hey thanks a lot your stuff is amazing !



Met vriendelijke groeten
Dimitri Vanhaecke


-------- Oorspronkelijk bericht --------
Van: Michael Irigoyen <notifications@github.com>
Datum: 4/02/19 18:36 (GMT+01:00)
Aan: Templarian/MaterialDesign <MaterialDesign@noreply.github.com>
Cc: Dimtrivh <dimitrivh@hotmail.com>, Author <author@noreply.github.com>
Onderwerp: Re: [Templarian/MaterialDesign] Bolt - Screw - nail  (#3887)


Without anything being added, you could use the following for each:

Bolt:
[hexagon]<https://materialdesignicons.com/icon/hexagon>

Flathead Screw:
[minus-circle]<https://materialdesignicons.com/icon/minus-circle>

Phillips Screw:
[close-circle]<https://materialdesignicons.com/icon/close-circle>[plus-circle]<https://materialdesignicons.com/icon/plus-circle>

Nailhead:
[circle]<https://materialdesignicons.com/icon/circle>

**Comment by JamesCoyle** [comment]
Side views might be useful for the types of heads: rounded, countersunk etc

**Comment by goyney** [comment]
Here's a bunch I created:
![image](https://user-images.githubusercontent.com/1015040/52315556-65fd5080-2985-11e9-90fe-92237d194c48.png)![image](https://user-images.githubusercontent.com/1015040/52315576-81685b80-2985-11e9-93d7-11006afc827c.png)
![image](https://user-images.githubusercontent.com/1015040/52315562-70b7e580-2985-11e9-92e5-adfc732667b2.png)![image](https://user-images.githubusercontent.com/1015040/52315570-78778a00-2985-11e9-97f1-46336468bf0f.png)
![image](https://user-images.githubusercontent.com/1015040/52315596-8e854a80-2985-11e9-9402-0eda311465cb.png)![image](https://user-images.githubusercontent.com/1015040/52315603-9513c200-2985-11e9-9880-939405e860cf.png)
![image](https://user-images.githubusercontent.com/1015040/52315619-a8bf2880-2985-11e9-9eb7-8e95af78df19.png)

[screws.zip](https://github.com/Templarian/MaterialDesign/files/2834541/screws.zip)

**Comment by CoDEmanX** [comment]
Maybe also add a rivet?

**Comment by Templarian** [comment]
Added.
