### ISSUE TITLE
add arrows for more detailed cardinal directions

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#3889]
please consider creating 8 extra (half way) arrows to use for cardinal directions.
at the moment we can use:
```
    sensor.dark_sky_wind_bearing:
      templates:
        icon: >
          var icons = [ 'mdi:arrow-down', 'mdi:arrow-bottom-left', 'mdi:arrow-left', 
                        'mdi:arrow-top-left', 'mdi:arrow-up', 'mdi:arrow-top-right', 
                        'mdi:arrow-right', 'mdi:arrow-bottom-right' ];
          var quadrant = Math.round(Number(state)/45);
          if (quadrant < icons.length) return icons[quadrant];
          return 'mdi:arrow-down';
```

and use the icons to map 45, 90, 135, 180, 225, 270, 315, 360 degrees. Which is very nice indeed Would be even better to  be able to use /22.5 and have these too:

![wind_compass](https://user-images.githubusercontent.com/33354141/52304382-ed9d8c00-2992-11e9-97a3-92b614f19990.gif)

for naming, use the degrees, (and not the cardinal direction), so the user could decided which direction to use the arrow: showing the wind-direction, or wind-source..
thanks for considering

**Comment by goyney** [comment]
Adding other angle degree'd variations of arrows is way too niche for this library. If you're looking to acheive these angles, I would recommend using CSS transforms. If you're using React, you can use `@mdi/react` and specify a rotation value.
