### ISSUE TITLE
credit-card-clock

### ISSUE THREAD

**Issue by iang0ld** [Templarian/MaterialDesign#389]
To be used as payment, multiple payment and payment schedule.
- [ ] cash-clock
- [ ] cash-usd-multiple

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/cash-usd (exists provided by google)
http://materialdesignicons.com/icon/cash (exists)
http://materialdesignicons.com/icon/cash-multiple (exists)

Dollar with a clock does not exist though. Do you need `cash-usd-multiple`?

**Comment by CoDEmanX** [comment]
Pretty specific, not for if it's really necessary:
![cash-usd-multiple](https://cloud.githubusercontent.com/assets/1309249/8847841/d8785fbe-3132-11e5-8cfd-fc7259ac6765.png) https://www.dropbox.com/s/8xvuqu8dgxe8amn/cash-usd-multiple.svg?dl=0

Scheduled transactions are hard to symbolize as a combination of 2 symbols in 24px:
![cash-clock](https://cloud.githubusercontent.com/assets/1309249/8848387/40f01aba-3137-11e5-9bdd-a1694d992ce5.png) https://www.dropbox.com/s/3txoen7ldw7wn24/cash-clock.svg?dl=0 (not production-ready)
![cash-date](https://cloud.githubusercontent.com/assets/1309249/8848388/40f0ebf2-3137-11e5-849b-358ad4601b2c.png) https://www.dropbox.com/s/jcxohdup6fp2hry/cash-date.svg?dl=0

The former has no margin left around the borders, the latter uses a slightly modified calendar shape (upper inner edge moved 1px up to make room for the dollar sign).

**Comment by CoDEmanX** [comment]
Alternative `cash-clock` icon, which has 2px margin around all sides:

![cash-clock-variant](https://cloud.githubusercontent.com/assets/1309249/8857058/41438b2c-316f-11e5-84b5-5e146915a982.png) https://www.dropbox.com/s/job28c6gb3zx14f/cash-clock-variant.svg?dl=0

**Comment by goyney** [comment]
@iang0ld Do you need `cash-usd-multiple` or does `cash-multiple` work for you?

**Comment by PeterShaggyNoble** [comment]
Given that, outside of the `currency-*` icons themselves, we are no longer adding any currency specific icons.

For a payment schedule, I'd suggest a `credit-card-clock` icon.

**Comment by goyney** [comment]
Alrighty, so we're going to reject `cash-usd-multiple`.

This issue then turns into a request for `credit-card-clock` for a payment schedule. I am updating the issue accordingly.

**Comment by MrGrigri** [comment]
I'm not sure if the current clock modifier will suffice here because of its size. If we go any smaller, the clock will not be recognizable.

![image](https://user-images.githubusercontent.com/4528551/52223448-e1b2ac80-2862-11e9-86c3-08318f67b2fa.png)

**Comment by MrGrigri** [comment]
In keeping with issue #3740 (add outline version if that issue is rejected), this could work if we move the modifier down and the card up.

![image](https://user-images.githubusercontent.com/4528551/52223840-c5fbd600-2863-11e9-9afa-0a68a2ac51f7.png) ![image](https://user-images.githubusercontent.com/4528551/52223888-e4fa6800-2863-11e9-9191-fa4c25723d6c.png)

---
#### Files

[credit-card-clock.zip](https://github.com/Templarian/MaterialDesign/files/2829022/credit-card-clock.zip)

**Comment by Templarian** [comment]
Added. 😃
