### ISSUE TITLE
EU Tyre Labelling

### ISSUE THREAD

**Issue by paulmacarie** [Templarian/MaterialDesign#3891]
Hi, 

It would be great if someone could create the icons that can be found on the EU Tyre label. I'm referring  to fuel efficiency class, wet grip and noise emission. Please see the attached files. 
![noise](https://user-images.githubusercontent.com/47388951/52346298-fbe9b780-2a27-11e9-941f-52e6e821faff.jpg)
![wet](https://user-images.githubusercontent.com/47388951/52346306-02782f00-2a28-11e9-9b7b-37bcec707c96.jpg)
![fuel](https://user-images.githubusercontent.com/47388951/52346310-04da8900-2a28-11e9-82ce-c46cba17c3f7.jpg)

**Comment by MrGrigri** [comment]
I believe since these are regulatory branded icons we shouldn't add these. With regulatory labels, their logo, and not a recreation, is needed. Could we get clarification on this @Templarian.

**Comment by paulmacarie** [comment]
Hello, 

Thanks for the quick turnaround. 
A recreation will be good enough for us and for many other tyre eCommerce websites.

**Comment by JamesCoyle** [comment]
As these are rather niche and the design doesn't fit in with the material guidelines I'm gonna close this one out. I'd recommend just using the speaker, raindrop, and fuel station icons in context in the UI.

**Comment by PeterShaggyNoble** [comment]
However, if these are *indeed* regulatory icons then, as @MrGrigri stated, you should use the originals.
