### ISSUE TITLE
wifi-star

### ISSUE THREAD

**Issue by GabrielInTheWorld** [Templarian/MaterialDesign#3892]
An icon for the case 'Wifi is available' would be nice.
I think this could look as the default Wifi-icon outlined with a star in the bottom (similar to the Windows icon).

I haven't seen a similar icon in the whole set - if it's already there, I apologize!

**Comment by goyney** [comment]
Not sure how I feel about this one:
![image](https://user-images.githubusercontent.com/1015040/52366146-018ad180-2a17-11e9-96d5-aa82e7ed199b.png)
[wifi-star.svg.zip](https://github.com/Templarian/MaterialDesign/files/2837831/wifi-star.svg.zip)

**Comment by MrGrigri** [comment]
I like the icon, but I'm not sure if it will convey what the requester desires. WiFi being available should just be the WiFi icon itself. This could though, symbolize a preferred network in a list of remembered networks.

**Comment by PeterShaggyNoble** [comment]
Agreed with @MrGrigri; that definitely says favourite network(s) to me rather than network(s) available.

**Comment by GabrielInTheWorld** [comment]
I like this icon, too. Thank you!

**Comment by Templarian** [comment]
[![wifi-star](https://materialdesignicons.com/wifi/star)](https://materialdesignicons.com/wifi/star)

Agreed, this is more for favorite networks.
