### ISSUE TITLE
account-card-details-outline

### ISSUE THREAD

**Issue by first087** [Templarian/MaterialDesign#3893]

**Comment by MrGrigri** [comment]
[![account-card-details-outline](https://user-images.githubusercontent.com/4528551/52424036-6f3a0a80-2ab6-11e9-83c8-86950a9c2f43.png)](https://github.com/Templarian/MaterialDesign/files/2841632/account-card-details-outline.zip)

**Comment by first087** [comment]
Thank you

**Comment by Templarian** [comment]
Added.
