### ISSUE TITLE
smart-card

### ISSUE THREAD

**Issue by first087** [Templarian/MaterialDesign#3895]
Ex: https://iconscout.com/icon/smart-card-1

**Comment by MrGrigri** [comment]
![smart-card](https://user-images.githubusercontent.com/4528551/52487951-0917bb00-2b7c-11e9-9d49-c77254bca45e.png) ![smart-card-outline](https://user-images.githubusercontent.com/4528551/52487978-1cc32180-2b7c-11e9-8a70-07ebc7ab6c2b.png)

---
#### SVG

[smart-card.zip](https://github.com/Templarian/MaterialDesign/files/2845690/smart-card.zip)

**Comment by PeterShaggyNoble** [comment]
Hmm ... not sure those work; maybe ditch the person and just use the chip and an arrow?

**Comment by MrGrigri** [comment]
I was in the U.S. military for 12 years. They use smart cards (Common Access Cards) all of the time and this more than works. It's more than just the chip on a credit card, it is most common to have a picture with it.

**Comment by first087** [comment]
Thank you

**Comment by PeterShaggyNoble** [comment]
Ah, so a smart *ID* card. Don't think such a thing has made it over here yet - are they common outside the US army?

**Comment by MrGrigri** [comment]
Think of it as a dual purpose card. It's used for identification and two-factor authentication with the `smart-card-reader`. They are used throughout the government, hospitals, and other organizations.

**Comment by GreenTurtwig** [comment]
@petershaggynoble they're used over here loads, been around for years. RFID cards on lanyards are pretty standard nowadays. Usually they're used so you can give permission for certain staff to open doors and to track entries and exists on turnstiles.

**Comment by goyney** [comment]
[![smart-card](https://materialdesignicons.com/icon/smart-card)](https://materialdesignicons.com/icon/smart-card)[![smart-card-outline](https://materialdesignicons.com/icon/smart-card-outline)](https://materialdesignicons.com/icon/smart-card-outline)
