### ISSUE TITLE
typewriter

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3896]
Discussed internally.

[![typewriter](https://user-images.githubusercontent.com/4528551/52441434-c6070a80-2add-11e9-8a05-c2daa4dc40b6.png)](https://github.com/Templarian/MaterialDesign/files/2842588/typewriter.zip)

**Comment by Templarian** [comment]
Added. 😃

**Comment by MrGrigri** [comment]
@Templarian, I don't see this as being added.

**Comment by goyney** [comment]
Added.
