### ISSUE TITLE
smart-card-reader

### ISSUE THREAD

**Issue by first087** [Templarian/MaterialDesign#3897]
Ex: https://iconscout.com/icon/smart-card-reader-1

**Comment by MrGrigri** [comment]
![smart-card-reader](https://user-images.githubusercontent.com/4528551/52488083-5562fb00-2b7c-11e9-81e1-ba8430cd80ba.png) ![smart-card-reader-outline](https://user-images.githubusercontent.com/4528551/52488138-69a6f800-2b7c-11e9-9a9a-a38222c523ed.png)

---
#### SVG
[smart-card-reader.zip](https://github.com/Templarian/MaterialDesign/files/2845695/smart-card.zip)

**Comment by first087** [comment]
Thank you

**Comment by GreenTurtwig** [comment]
There is a potential conflict with RFID cards not being represented. Although I variant for that would be difficult.

**Comment by goyney** [comment]
[![smart-card-reader](https://materialdesignicons.com/icon/smart-card-reader)](https://materialdesignicons.com/icon/smart-card-reader)[![smart-card-reader-outline](https://materialdesignicons.com/icon/smart-card-reader-outline)](https://materialdesignicons.com/icon/smart-card-reader-outline)
