### ISSUE TITLE
account-badge

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3898]
Just thinking to myself and realized that we don't have any badge icons.

![account-badge](https://user-images.githubusercontent.com/4528551/52489414-77aa4800-2b7f-11e9-9eb5-943e3f490753.png) ![account-badge-outline](https://user-images.githubusercontent.com/4528551/52489442-885abe00-2b7f-11e9-9e2c-7c2a92f6d4d5.png)

![account-badge-alert](https://user-images.githubusercontent.com/4528551/52489469-97417080-2b7f-11e9-8c75-ec0bd4cde0d6.png) ![account-badge-alert-outline](https://user-images.githubusercontent.com/4528551/52489502-a7595000-2b7f-11e9-985e-9ddc2ee5e473.png)

---
#### SVG

[account-badge.zip](https://github.com/Templarian/MaterialDesign/files/2845801/account-badge.zip)

**Comment by goyney** [comment]
I really like these!

**Comment by Templarian** [comment]
Added.
