### ISSUE TITLE
Importance

### ISSUE THREAD

**Issue by simondrabble** [Templarian/MaterialDesign#3900]
This would be a set (4-5) of icons used to represent a level of interest/ importance. For example I am choosing from a set of recommendations. I can indicate how interested I am in a recommendation, or how important it might be to me.

If this is too broad or it would be better to separate the concepts visually then let me know and I'll open a separate ticket for the other concept.

In the existing icons there are somewhat general forms of this but none really indicate to me a level of interest - e.g. the wifi signal strength icons kinda sorta could be used but not really since they already have an association in people's minds ("My level of interest in Foo is "high strength signal" ?"). 

The various exclamation point and thumbs up/down icons are also somewhat related but (across the web) there's typically only three at most of the latter, and one of the former. 

My searches have had very little success so I have no idea how you'd even go about representing this concept visually. Perhaps variations on the smiley face - there are thousands of those already but none really suitable.

Thanks!

**Comment by goyney** [comment]
This seems too abstract to create something specific for. I believe you could easily portray this with outline and filled versions of icons, such as stars or circle. For example, out of 5 stars, 3 of the 5 are filled.

**Comment by MrGrigri** [comment]
I agree...to specific. You could also take a CodePen approach and with each click of the heart, it gets redder and slightly larger (to help people who are colorblind).

**Comment by CoDEmanX** [comment]
The star icons should also work nicely (star, star-outline, star-half, star-off)

**Comment by PeterShaggyNoble** [comment]
I agree with the others; my first thought when reading the request was that the `star-*` icons would be perfectly suitable.

Closing this out. If you think of another way to represent this, feel free to reopen the issue with a few examples.

**Comment by simondrabble** [comment]
Ah, the star idea is perfect! I must have missed those. Thanks for the responses :)
