### ISSUE TITLE
mine

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3901]
I'm not sure if I'm a fan of the square terminals, but I've included both to see what the community thinks. 

![mine-round](https://user-images.githubusercontent.com/4528551/52654196-b8bb9880-2eae-11e9-81aa-7405d40a6edf.png) ![mine-square](https://user-images.githubusercontent.com/4528551/52654220-cbce6880-2eae-11e9-8d51-f42c24bc0b23.png)

---
#### SVG

[mine.zip](https://github.com/Templarian/MaterialDesign/files/2856825/mine.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52654376-d5140100-2ebf-11e9-8a14-a74c14d5de4e.png)

**Comment by JamesCoyle** [comment]
I prefer the square one but rounded could be useful once we start adding rounded variants.

**Comment by CoDEmanX** [comment]
The "reflection" is rounded in both variants. How does it look with straight terminals?Are there actually any rules regarding this?

**Comment by MrGrigri** [comment]
[![image](https://user-images.githubusercontent.com/4528551/52721234-79e91980-2f66-11e9-8148-43dc9ae87418.png)](https://github.com/Templarian/MaterialDesign/files/2860876/mine-square.zip)

**Comment by PeterShaggyNoble** [comment]
@goyney, now I want a seagull icon! 😆

**Comment by MrGrigri** [comment]
Side note: the seagull is actually the [state bird](https://onlinelibrary.utah.gov/research/utah_symbols/bird.html) in Utah!

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52733240-3c00eb00-2f90-11e9-9644-a3dc0e7feeb8.png)

**Comment by Templarian** [comment]
Added `mine`.
