### ISSUE TITLE
Few more missing Pen/Pencil Variants

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3902]
Noticed a three missing icons from the pen/pencil collection. Here they are:

![image](https://user-images.githubusercontent.com/1015040/52665115-c5ed7d00-2ed8-11e9-9d7b-f1b7e3bb5831.png)![image](https://user-images.githubusercontent.com/1015040/52665124-cdad2180-2ed8-11e9-9988-ca18d7291bc8.png)
![image](https://user-images.githubusercontent.com/1015040/52665083-b1a98000-2ed8-11e9-9bea-276d0cbf4155.png)

[pencils.zip](https://github.com/Templarian/MaterialDesign/files/2857486/pencils.zip)

**Comment by Templarian** [comment]
Added.
