### ISSUE TITLE
disabled-[left/right]-arrow

### ISSUE THREAD

**Issue by trife** [Templarian/MaterialDesign#3903]
Left: ![ic_action_ic_adv_disable_left](https://user-images.githubusercontent.com/1869534/52672857-a0ff0700-2ee4-11e9-93b3-1fd1e0c4878c.png)

Right: ![ic_action_ic_adv_disable_right](https://user-images.githubusercontent.com/1869534/52672856-a0ff0700-2ee4-11e9-9f27-a18ff70e80aa.png)

**Comment by JamesCoyle** [comment]
What is the use-case for these? We don't really want to start adding off variants for arrows as people will expect them for every arrow we have.

**Comment by trife** [comment]
My specific use case is for an app that focuses on an individual entry and disables moving left or right to the previous or next entry. I suggested it because I did not see any other arrows in the collection that conveyed a message of left or right being unavailable choices.

**Comment by JamesCoyle** [comment]
Generally we would handle this with a disabled state on the icon rather than an `off` variant. `off` is intended to be used for togglable states and not really to show something is disabled.

**Comment by goyney** [comment]
Agreed, I feel that for proper UX, you'd want to recolor or drop the opacity of the icon in a disabled state for your use case.

We're going to reject this issue for now as we can't see a use case for the `-off` variants of arrows that also promotes good UX in application.

Thanks for the suggestion.

**Comment by trife** [comment]
That makes sense. In my specific case, the icon is for a setting that modifies how the user can interact with UI elements in a different activity. Thanks for the rapid responses.

**Comment by PeterShaggyNoble** [comment]
A combination of colour & opacity is generally used to highlight enabled/disabled states. For arrows, I also usually use different weights for added clarity:

![image](https://user-images.githubusercontent.com/15157491/52732516-52bb3800-2fb8-11e9-9cc7-8688d2261630.png)
