### ISSUE TITLE
cash on delivery

### ISSUE THREAD

**Issue by mohammad425** [Templarian/MaterialDesign#3904]
**Something like this:**

![image](https://user-images.githubusercontent.com/12151806/52701022-7bc6d300-2f8e-11e9-95e7-f7ddc25cb63c.png)

or

![image](https://user-images.githubusercontent.com/12151806/52701001-6a7dc680-2f8e-11e9-9df3-5cd0bc499f5e.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52718842-68a60a00-2f72-11e9-8fed-74531807f62e.png)
[cash-marker.svg.zip](https://github.com/Templarian/MaterialDesign/files/2860736/cash-marker.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Suggest also aliasing this as `cod`.

**Comment by MrGrigri** [comment]
Should we add a `credit-card-marker` as well?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52743671-8aba7f00-2fa8-11e9-983e-2ca9924d0402.png)
[credit-card-marker.svg.zip](https://github.com/Templarian/MaterialDesign/files/2862196/credit-card-marker.svg.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52743783-d836ec00-2fa8-11e9-80bb-af3d35675928.png)
[credit-card-marker.svg.zip](https://github.com/Templarian/MaterialDesign/files/2862202/credit-card-marker.svg.zip)

**Comment by Templarian** [comment]
Added both. 😃
