### ISSUE TITLE
slot-machine

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3906]
![image](https://user-images.githubusercontent.com/1015040/52747963-251fc000-2fb3-11e9-9c2b-05d8d5a686c4.png)![image](https://user-images.githubusercontent.com/1015040/52747969-310b8200-2fb3-11e9-869c-5afe28944303.png)

Yeah, the `-reels` version isn't centered to keep it on the grid.

[slots.zip](https://github.com/Templarian/MaterialDesign/files/2862443/slots.zip)

**Comment by MrGrigri** [comment]
I don't think numbers should be used....maybe diamond, circle, and square.

**Comment by goyney** [comment]
Something like this? Dunno if this works:
![image](https://user-images.githubusercontent.com/1015040/52756543-b43ad100-2fcf-11e9-99fa-4c271b7b94df.png)

Doesn't really make sense on the reels:
![image](https://user-images.githubusercontent.com/1015040/52756613-f106c800-2fcf-11e9-8395-ff4a31308a3c.png)

[slot-machine-2.zip](https://github.com/Templarian/MaterialDesign/files/2862930/slot-machine-2.zip)

**Comment by JapanYoshi** [comment]
I disagree with MrGrigri that numbers shouldn't be on this icon; I think that the "777" is iconic enough to represent a slot machine.

**Comment by PeterShaggyNoble** [comment]
Aliases: `fruit-machine`, `one-armed-bandit`, `casino`.

**Comment by JapanYoshi** [comment]
![slots](https://user-images.githubusercontent.com/8707990/52785357-1d3b4b00-309b-11e9-8196-9479f5a9fce5.png)
I gave it a shot.

**Comment by goyney** [comment]
@JapanYoshi All you did is add more complexity, which seems to go against Material guidelines. Additionally, please actually show those on the grid, because I do not believe they fit in a 24x24 box with a 2dp border.

**Comment by MrGrigri** [comment]
The only reason why I was steering away from the iconic sevens, was because they are too detailed and small at 1x. I also like @JapanYoshi's middle version with the numbers offset...much like our `counter` icon.

**Comment by Templarian** [comment]
I'm definitely leaning toward the 7's in the first design. They are a bit more quickly recognizable.

The shapes aren't a bad idea, I'm fine adding a variant if you guys think it would be a good idea. The `7`'s are just much quicker to recognize (even at the smaller size).

The offset letters in @JapanYoshi is a bit too detailed imo.

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/52857427-7a520200-316a-11e9-96d8-0b68b82ae3a0.png)
I've tweaked the icon and overlaid the grid.

**Comment by goyney** [comment]
What are the circles for? The lack of the handle removes visual identify as a slot machine for me.

**Comment by JamesCoyle** [comment]
The hold buttons I'd assume.

**Comment by goyney** [comment]
That's too much detail, not every slot machine has those. A slot machine, IMO, should consist of the lever and the reels. That's the minimum required to convey what it is.

**Comment by goyney** [comment]
Went with @Templarian's recommendation.
[![slot-machine](https://materialdesignicons.com/icon/slot-machine)](https://materialdesignicons.com/icon/slot-machine)[![slot-machine-outline](https://materialdesignicons.com/icon/slot-machine-outline)](https://materialdesignicons.com/icon/slot-machine-outline)
