### ISSUE TITLE
thermometer-modifiers

### ISSUE THREAD

**Issue by lmesousa** [Templarian/MaterialDesign#3907]
Max and min level temperature

Something like this:
[temperature_min_max.zip](https://github.com/Templarian/MaterialDesign/files/2869499/temperature_min_max.zip)

**Comment by goyney** [comment]
Thanks for the potential contributions. We don't work in the ICO format, but with SVGs. Can you please reupload SVG versions of these icons? You can also use http://dev.materialdesignicons.com/contribute/github to generate previews to copy and paste here so we can see them and discuss them easier!

**Comment by lmesousa** [comment]
With svc files:
[temperature_min_max.zip](https://github.com/Templarian/MaterialDesign/files/2869567/temperature_min_max.zip)

**Comment by goyney** [comment]
The SVG files you've provided are not valid files.

**Comment by MrGrigri** [comment]
I believe these could be highly useful. I've just quickly made them up.

![image](https://user-images.githubusercontent.com/4528551/52879759-3be22600-311d-11e9-9383-349b2b0d02b3.png) ![image](https://user-images.githubusercontent.com/4528551/52879782-4ac8d880-311d-11e9-8c3b-83828e8b8152.png)

---
#### Resources

[thermometer-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2870561/thermometer-modifiers.zip)

**Comment by MrGrigri** [comment]
Adding chevron variants

![image](https://user-images.githubusercontent.com/4528551/52880220-9cbe2e00-311e-11e9-9780-222105ec38fe.png) ![image](https://user-images.githubusercontent.com/4528551/52880247-afd0fe00-311e-11e9-8f5f-c7f43457776f.png)

---
#### Resources

[thermometer-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2870595/thermometer-modifiers.zip)

**Comment by MrGrigri** [comment]
Also an alert variant

![image](https://user-images.githubusercontent.com/4528551/52880486-57e6c700-311f-11e9-9a54-1353dfdfba42.png)

---
#### All Resources

[thermometer-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/2870608/thermometer-modifiers.zip)

**Comment by goyney** [comment]
Related: https://github.com/Templarian/MaterialDesign/issues/3291

We should probably handle both issues together. One of the more interesting pieces was discussion on what color the "mercury" should be. I'm still of the opinion that the mercury should be the fill.

**Comment by Templarian** [comment]
Added! 😃
