### ISSUE TITLE
RealBank

### ISSUE THREAD

**Issue by pml10628** [Templarian/MaterialDesign#3908]
![logo22](https://user-images.githubusercontent.com/24299277/52879063-4952dc80-312c-11e9-91d6-6b0d2e2c6fc1.gif)

**Comment by Templarian** [comment]
This is going to be too niche. We generally only add social media related brands.

**Comment by pml10628** [comment]
![crypto image](https://user-images.githubusercontent.com/24299277/52879269-b9616280-312c-11e9-83d4-686a184e956b.jpg)

**Comment by pml10628** [comment]
![coin-in system48](https://user-images.githubusercontent.com/24299277/52880715-b5cfda80-3130-11e9-86d7-6cf909d049db.png)
