### ISSUE TITLE
key-outline

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3909]

**Comment by PeterShaggyNoble** [comment]
Here's Google's:

[![key-outline](https://user-images.githubusercontent.com/15157491/52904327-3b7f8300-3222-11e9-9252-5b268d0962f8.png)](https://material.io/tools/icons/static/icons/outline-vpn_key-24px.svg)

**Comment by Templarian** [comment]
Added.

**Comment by ofekashery** [comment]
Thanks!
