### ISSUE TITLE
OCR

### ISSUE THREAD

**Issue by kyay** [Templarian/MaterialDesign#3910]
An ocr icon, like this one: [OCR Icon](https://iconscout.com/icon/general-ocr-1)

**Comment by goyney** [comment]
If we want to break some rules:
![image](https://user-images.githubusercontent.com/1015040/52958921-1cd4d580-3363-11e9-85e0-5adfcde82100.png)

[ocr.svg.zip](https://github.com/Templarian/MaterialDesign/files/2876147/ocr.svg.zip)

**Comment by kyay** [comment]
I mean like it is OK, but it is totally not Material

**Comment by Templarian** [comment]
Yeah, we usually try not to use text in icons whenever possible. It's one of the guidelines. In this case it might be difficult to make it obvious the icon is doing OCR.

Was thinking something like with a letter inside, but that might be less obvious.

**Comment by JapanYoshi** [comment]
Perhaps keep the square corners, and use a T instead to stand for text?

**Comment by JamesCoyle** [comment]
Why not just two or three lines representing text? I think it makes the most sense visually.

**Comment by goyney** [comment]
Erm, well, the only thing "not Material" about it is that it breaks the buffer area. But we have plenty of icons that work that way.

Exhibit A
[![face-recognition](https://materialdesignicons.com/icon/face-recognition)](https://materialdesignicons.com/icon/face-recognition)

I work for a company that engineers OCR software and I can tell you, there is no other visual representation that will work at native resolution than just the letters.

**Comment by JapanYoshi** [comment]
![ocr-big](https://user-images.githubusercontent.com/8707990/53220417-25554500-36b0-11e9-8ad3-fae015950591.png)
![ocr-small](https://user-images.githubusercontent.com/8707990/53220418-25eddb80-36b0-11e9-8b4e-f07f3f039ad3.png)
I made one with `face_recognition`'s frame, and another with the standard 18x18dp one.

**Comment by CoDEmanX** [comment]
Some experiments:

![grafik](https://user-images.githubusercontent.com/1309249/53239142-8d4d6080-369b-11e9-88f7-3cb930dd80b4.png)

![grafik](https://user-images.githubusercontent.com/1309249/53239174-a0f8c700-369b-11e9-9061-ad79e1f3cb47.png)

![grafik](https://user-images.githubusercontent.com/1309249/53239544-97bc2a00-369c-11e9-9015-10fb940c103b.png)

![grafik](https://user-images.githubusercontent.com/1309249/53239571-a4408280-369c-11e9-8e90-1c43beec26be.png)

Download: [ocr.zip](https://github.com/Templarian/MaterialDesign/files/2893675/ocr.zip)

**Comment by CoDEmanX** [comment]
A few more variants:

![grafik](https://user-images.githubusercontent.com/1309249/62861219-051f4e00-bd03-11e9-836b-f14a8117ec03.png)

![grafik](https://user-images.githubusercontent.com/1309249/62861674-82978e00-bd04-11e9-812c-178a78519664.png)

![grafik](https://user-images.githubusercontent.com/1309249/62861503-00a76500-bd04-11e9-8eb3-0285c5e60bd7.png)

![grafik](https://user-images.githubusercontent.com/1309249/62861460-dfdf0f80-bd03-11e9-8c1f-e2c688f0c3cf.png)

![grafik](https://user-images.githubusercontent.com/1309249/62862385-f1291b80-bd05-11e9-8a8e-e708917c2019.png)

[ocr6.zip](https://github.com/Templarian/MaterialDesign/files/3492093/ocr6.zip)

**Comment by goyney** [comment]
[![ocr](https://materialdesignicons.com/icon/ocr)](https://materialdesignicons.com/icon/ocr)[![text-recognition](https://materialdesignicons.com/icon/text-recognition)](https://materialdesignicons.com/icon/text-recognition)
