### ISSUE TITLE
folder-information(-outline)

### ISSUE THREAD

**Issue by HockeyFan77** [Templarian/MaterialDesign#3911]
Take the standard folder design and add a small "information" symbol (the letter "i")

**Comment by goyney** [comment]
I'm not sure about these. I think the idea of "information" on a folder could be indicated another way.

For example, here's taking our `information-variant` icon and putting it inside the folder:

![image](https://user-images.githubusercontent.com/1015040/52954994-894ad700-3359-11e9-833a-17a8c102bf65.png)

It get's lost.

Using a lowercase "i" in at that size also looks very similar to an exclamation point, and could get confused for an `alert` icon.

Taking `folder-clock` and replacing the hands with either a Material lowercase "i" or our `information-variant` runs into the same issue of being completely lost at native size and potentially confused for an `alert` variation.

Just curious, would something like `folder-text` not work?
[![folder-text](https://materialdesignicons.com/icon/folder-text)](https://materialdesignicons.com/icon/folder-text)

**Comment by goyney** [comment]
After looking at these some more, maybe they're not that bad.
![image](https://user-images.githubusercontent.com/1015040/52985514-2d686880-33c2-11e9-8436-27c540506e79.png)![image](https://user-images.githubusercontent.com/1015040/52985521-348f7680-33c2-11e9-801f-ecb167a955ac.png)

[folder-information.zip](https://github.com/Templarian/MaterialDesign/files/2877944/folder-information.zip)

**Comment by MrGrigri** [comment]
Why not do a `folder-settings` icon.

![folder-settings](https://user-images.githubusercontent.com/4528551/53031291-c9798a80-3429-11e9-9070-571ef55ed4f0.png) ![folder-settings-outline](https://user-images.githubusercontent.com/4528551/53031317-d8f8d380-3429-11e9-92f0-af06a0d0f4b5.png)

---
#### Files

[folder-settings.zip](https://github.com/Templarian/MaterialDesign/files/2880965/folder-settings.zip)

**Comment by goyney** [comment]
[![folder-information](https://materialdesignicons.com/icon/folder-information)](https://materialdesignicons.com/icon/folder-information)[![folder-information-outline](https://materialdesignicons.com/icon/folder-information-outline)](https://materialdesignicons.com/icon/folder-information-outline)
