### ISSUE TITLE
folder-edit-outline

### ISSUE THREAD

**Issue by HockeyFan77** [Templarian/MaterialDesign#3913]
Take the outline folder design and add the pencil from the standard folder design

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52907281-6ec70f80-322c-11e9-96ba-b18b52c5b818.png)
[folder-edit-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2872581/folder-edit-outline.svg.zip)

**Comment by Templarian** [comment]
Added.
