### ISSUE TITLE
folder-open-outline

### ISSUE THREAD

**Issue by HockeyFan77** [Templarian/MaterialDesign#3914]
Take the standard folder open design and convert it to "outline" style

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52907335-cf0a8100-322d-11e9-9f08-445eb5c7a3dc.png)
[folder-open-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2872584/folder-open-outline.svg.zip)

**Comment by Templarian** [comment]
Added.
