### ISSUE TITLE
phone-outline

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3915]
From the MD icons:
![image](https://user-images.githubusercontent.com/16443111/52906251-a0ea6880-3250-11e9-9ff6-975b3b0c11f4.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52907344-0711c400-322e-11e9-8056-1c3432421c9b.png)
[phone-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2872586/phone-outline.svg.zip)

**Comment by Templarian** [comment]
Added.
