### ISSUE TITLE
upload-outline

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#3916]
Like the ``download-outline``

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/52916103-97d9b580-32a9-11e9-8ae3-9ec4bc48cf88.png)
[upload-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2873165/upload-outline.svg.zip)

**Comment by Templarian** [comment]
[![upload-outline](https://materialdesignicons.com/icon/upload-outline)](https://materialdesignicons.com/icon/upload-outline)
