### ISSUE TITLE
License plate europe

### ISSUE THREAD

**Issue by Franki1986** [Templarian/MaterialDesign#3917]
Hello,

I would like to use an europe license plate no.

[license-plate-eur.zip](https://github.com/Templarian/MaterialDesign/files/2875709/license-plate-eur.zip)

**Comment by PeterShaggyNoble** [comment]
Duplicate of #712

**Comment by Franki1986** [comment]
What is the reason for rejecting this or the other icon?

**Comment by goyney** [comment]
This was closed because there is already a request for a license plate. You're better to ask your questions on the original issue.

**Comment by Templarian** [comment]
@Franki1986 Looks like we closed it due to it not being legible at smaller sizes. Also that licenses look different in every country.

**Comment by CoDEmanX** [comment]
@Templarian How about changing the *Language Conflict* label to *Language / Cultur Dependent* and add it here?
