### ISSUE TITLE
folder-alert

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3918]
![image](https://user-images.githubusercontent.com/1015040/52954560-88fe0c00-3358-11e9-8daf-ad00c7d7d22d.png)![image](https://user-images.githubusercontent.com/1015040/52954579-91564700-3358-11e9-984a-89ab0f254a19.png)

[folder-alert.zip](https://github.com/Templarian/MaterialDesign/files/2875839/folder-alert.zip)

**Comment by Templarian** [comment]
Added! (slightly different but same idea).
