### ISSUE TITLE
image-scale, image-scale-increase, image-scale-decrease, others...

### ISSUE THREAD

**Issue by raveesh08** [Templarian/MaterialDesign#392]
1. Parcel,Courier Icon
2. Image Scale Icon(Enlarge,Compress) Single Icon and Individual Icon
3. Single Icon with Portrait and Landscape Rectangles
4. Postbox,Mail Box
5. Globe icon
6. Country and Continent Icons will be more use full
7. Medicines,Tablets
8. Alphabets,Numbers,Math Symbols
- [ ] image-scale-increase
- [ ] image-scale-decrease
- [ ] image-scale
- [x] currency-inr

**Comment by Templarian** [comment]
1. Example?
2. Needs to be added.
3. http://materialdesignicons.com/icon/crop-landscape / portrait (exists)
4. Needs to be added.
5. http://materialdesignicons.com/icon/earth (exists)
6. Example?
7. http://materialdesignicons.com/icon/pill (exists)
8. Many math symbols exist in the icon pack. Which ones do you need?

**Comment by Templarian** [comment]
Also, i think http://materialdesignicons.com/icon/package or http://materialdesignicons.com/icon/package-variant might work for the parcel icon.

**Comment by raveesh08** [comment]
1. Well Package works, but i feel in this icon Grey color is more...
3. individual exists, like this one..  ![ic_orientation](https://cloud.githubusercontent.com/assets/3930657/7877275/26ae9940-05f6-11e5-8b94-dc7c911197ab.png)
6. all countries continents will be help full for others too, i need India icon
7. A-Z all Uppercase,a-z all Lowercase characters,1-9 digits
8. Not exactly Math symbols... i need Indian Rupee symbol but other currency symbols also can be included...  Symbols available in MS Word will be use full.

**Comment by Templarian** [comment]
Thanks.

For 1, I think your sentence got cut off.

Probably going to reject 6 as it's too specific for the pack.

For 7 I'm thinking about including those in another font. Adding 62 characters (high point also) seems overkill for 99% of users. Making a separate webfont might fit this nicer. The site's engine is actually set up to manage multiple icon packages, so can be done. :smile:

**Comment by raveesh08** [comment]
Icons are awesome.....

**Comment by PeterShaggyNoble** [comment]
Closing this out as most all the viable icons from the original request have been either been added or have icons that can be used to represent them. If you are still in need of anything in this issue, though, please open a new one for each individual request, not forgetting to search the existing issues and icons first.
