### ISSUE TITLE
Saws

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3920]
![image](https://user-images.githubusercontent.com/1015040/53020884-eb710e00-3425-11e9-95d0-36a4c107a93e.png)![image](https://user-images.githubusercontent.com/1015040/53020892-f2981c00-3425-11e9-861e-173424289cd6.png)

[saws.zip](https://github.com/Templarian/MaterialDesign/files/2880313/saws.zip)

**Comment by PeterShaggyNoble** [comment]
See also @augustin32's contributions on [#2366](https://github.com/Templarian/MaterialDesign/issues/2366#issuecomment-333438540)

**Comment by Templarian** [comment]
Yeah, that circular saw in the above issue looks really nice. Saw blades in this looks a little more recognizable.

**Comment by CoDEmanX** [comment]
I really like the style of saw-blade, but I think the cutouts could be even larger to look very pointy even at native size.

**Comment by Templarian** [comment]
Added.
