### ISSUE TITLE
Seed / Sprout / Plant

### ISSUE THREAD

**Issue by lukepighetti** [Templarian/MaterialDesign#3922]

**Comment by goyney** [comment]
We have several variations of flowers that I feel fit "plant".

Here's a seed and a sprout:
![image](https://user-images.githubusercontent.com/1015040/53061457-b5667500-348b-11e9-9aaf-be02cecb3ff9.png)![image](https://user-images.githubusercontent.com/1015040/53061465-bbf4ec80-348b-11e9-9052-1ebee27367f9.png)
![image](https://user-images.githubusercontent.com/1015040/53061478-c7e0ae80-348b-11e9-98d4-2d405c3386ca.png)![image](https://user-images.githubusercontent.com/1015040/53061490-d202ad00-348b-11e9-994f-287bd7d3b3ad.png)

[plants.zip](https://github.com/Templarian/MaterialDesign/files/2882723/plants.zip)

**Comment by PeterShaggyNoble** [comment]
Hmm ... could swear I've seen a Google sprout icon somewhere ...

**Comment by Templarian** [comment]
Added. 😃

**Comment by lukepighetti** [comment]
You can't even pay for service this good. Thanks so much everyone for the assistance and blazing fast turnaround.
