### ISSUE TITLE
reply-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3923]
As noticed in #3155, we don't have outline versions of our `reply` (back) icons, but we do of our `share` (forward) icons.

![image](https://user-images.githubusercontent.com/1015040/53063082-edbc8200-3490-11e9-943f-8c072f67228a.png)![image](https://user-images.githubusercontent.com/1015040/53063094-f57c2680-3490-11e9-9bd1-7f4187f94cdb.png)

[reply-outlines.zip](https://github.com/Templarian/MaterialDesign/files/2882832/reply-outlines.zip)

**Comment by PeterShaggyNoble** [comment]
I _was_ about to say that these should be assigned to Google but [they don't have `outline`s of these 2](https://material.io/tools/icons/?search=reply&style=outline)

**Comment by Templarian** [comment]
Added. :smile:
