### ISSUE TITLE
kettle-hot

### ISSUE THREAD

**Issue by icouper** [Templarian/MaterialDesign#3925]
Hoping for a version of the kettle icon that shows it is on/hot/heating. Maybe with steam coming out or fire under it?

Thanks!

**Comment by JamesCoyle** [comment]
For reference: 
[![](https://materialdesignicons.com/icon/kettle)](https://materialdesignicons.com/icon/kettle)

**Comment by CoDEmanX** [comment]
Maybe shift the kettle a bit to the left in general and then add an exclamation mark for hot? (`kettle-alert`)

**Comment by goyney** [comment]
Here's the `-alert` variants:
![image](https://user-images.githubusercontent.com/1015040/72311327-3c977b00-3652-11ea-9cb2-91f953f65df1.png)![image](https://user-images.githubusercontent.com/1015040/72311333-4325f280-3652-11ea-9573-e0af4985e51a.png)

And attempt to add some steam:
![image](https://user-images.githubusercontent.com/1015040/72311350-520ca500-3652-11ea-87b6-6079e04e19a3.png)![image](https://user-images.githubusercontent.com/1015040/72311354-58028600-3652-11ea-91c4-a455f3cca6a2.png)

[kettle-hot.zip](https://github.com/Templarian/MaterialDesign/files/4057174/kettle-hot.zip)

**Comment by goyney** [comment]
[![kettle-alert](https://materialdesignicons.com/icon/kettle-alert)](https://materialdesignicons.com/icon/kettle-alert)[![kettle-alert-outline](https://materialdesignicons.com/icon/kettle-alert-outline)](https://materialdesignicons.com/icon/kettle-alert-outline)
[![kettle-steam](https://materialdesignicons.com/icon/kettle-steam)](https://materialdesignicons.com/icon/kettle-steam)[![kettle-steam-outline](https://materialdesignicons.com/icon/kettle-steam-outline)](https://materialdesignicons.com/icon/kettle-steam-outline)
[![kettle-off](https://materialdesignicons.com/icon/kettle-off)](https://materialdesignicons.com/icon/kettle-off)[![kettle-off-outline](https://materialdesignicons.com/icon/kettle-off-outline)](https://materialdesignicons.com/icon/kettle-off-outline)
