### ISSUE TITLE
Door locked/unlocked 

### ISSUE THREAD

**Issue by kmlucy** [Templarian/MaterialDesign#3926]
I'd like to request icons for door locked and door unlocked. My initial thought was just the door icon with a locked or unlocked padlock inside it.

**Comment by Templarian** [comment]
Probably need a door lock and a car door lock version.

**Comment by MrGrigri** [comment]
Speaking from a UI/UX standpoint, an unlocked variant would best be represented as the icon sans lock. And the locked variant, with a padlock in the corner. I.e. use `door-closed` for the unlocked state and `door-closed-lock` for the locked state.

![image](https://user-images.githubusercontent.com/4528551/53179544-1d62ab80-35b1-11e9-8c83-31b62c8b68e5.png) ![image](https://user-images.githubusercontent.com/4528551/53179675-6a468200-35b1-11e9-8a6e-e464c56c3f3a.png)

---
#### Files

[door-lock.zip](https://github.com/Templarian/MaterialDesign/files/2889859/door-lock.zip)

**Comment by goyney** [comment]
@MrGrigri What about the door without the floor line and the lock to the right? Think there's too much going on in that without it.

**Comment by MrGrigri** [comment]
I tried that...but the door alone looked off.

**Comment by goyney** [comment]
[![door-closed-lock](https://materialdesignicons.com/icon/door-closed-lock)](https://materialdesignicons.com/icon/door-closed-lock)
[![car-door-lock](https://materialdesignicons.com/icon/car-door-lock)](https://materialdesignicons.com/icon/car-door-lock)
