### ISSUE TITLE
mdi-stack

### ISSUE THREAD

**Issue by dominique-debert** [Templarian/MaterialDesign#3927]
Hello there,
Some of our developers needed 2 icons to be stacked, so I create a classe "mdi-stack" as fa did.

```
.mdi-stack {
   left: 0;
   position: absolute;
   text-align: center;
   width: 100%;
}
```

So you use it that way:

```
<span class="mdi-stack">
	<i class="mdi mdi-chart-bar mdi-18px mdi-stack"></i>
	<i class="mdi mdi-cancel mdi-24px mdi-stack"></i>
</span>
```

Could it be possible to integrate it in the CSS if you find an interest in it ?

Thank you.

**Comment by goyney** [comment]
We decided against adding stack functionality in the CSS back in this issue: https://github.com/Templarian/MaterialDesign/issues/686

We *do*, however, support icon stacks in the official [`@mdi/react`](https://www.npmjs.com/package/@mdi/react) component. If you're using React, please check that out.

**Comment by Templarian** [comment]
@dominique-debert Little clarification. Stacking icons tends to lead to less recognizable icons. It usually makes more sense for us to design that icon combination and include it in the pack for easier use by the community. The react library supports this to provide feature parity with third party libraries.

Let us know if there are any icon combinations you feel are missing and we'll try and get them added.

**Comment by Franki1986** [comment]
I think you should consider that more than one icon can be combined with the close or check icon.
Something like block user or block device, block camera.. whatever. And the opposite release.

**Comment by Templarian** [comment]
@Franki1986 Yeah, we might reconsider this eventually so there is a little more parity with FA 5. Unfortunately probably won't make it in for another release or two. I'll reopen this issue to track the progress.

**Comment by Franki1986** [comment]
Here are some of my combined icons over css that cover the most of my cases:
[predefined combined](https://codepen.io/franki1986/pen/XGQBeP)

**Comment by goyney** [comment]
I'm glad those work for you and I'm glad there are CSS options for those who wish to go this path, but after seeing them, I am 100% convinced this is not something we should officially support.

**Comment by JamesCoyle** [comment]
I'm gonna close this as I agree. I don't feel we should be adding features to the webfont implementation and should only issue fixes and new icons. These features are better handled in userland.
