### ISSUE TITLE
check-bold

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#3928]
Check that is bold.

**Comment by MrGrigri** [comment]
I thought we already had this...

**Comment by Templarian** [comment]
So did I... but I can't seem to find it. Needed it at work today and could have sworn I added it, but guess not.

**Comment by MrGrigri** [comment]
I not quite sure how bold you wanted it. So here is one at 3-, 3.5-, and 4-pixel stroke weights. Original 2-pixel is shadowed.

![image](https://user-images.githubusercontent.com/4528551/53203712-253d4280-35e7-11e9-8c76-f6f186008d2d.png) ![image](https://user-images.githubusercontent.com/4528551/53203736-39813f80-35e7-11e9-8a8c-c9c81892c4db.png) ![image](https://user-images.githubusercontent.com/4528551/53203753-49008880-35e7-11e9-9da5-5f9c899bae6e.png)

---
#### Files
[check-bold.zip](https://github.com/Templarian/MaterialDesign/files/2891416/check-bold.zip)

**Comment by CoDEmanX** [comment]
If we wanna go for normal and bold, then I guess 2dp and 4dp, so that the bold one is really bold?

Wouldn't it be awesome if we could make a variable icon font so users could choose the thickness and style? 😩

**Comment by Templarian** [comment]
Added the 4dp one. Agreed that we should make it really bold if we're going to add a bold one.
