### ISSUE TITLE
iPhone X/XS/Notched design

### ISSUE THREAD

**Issue by foxfluff** [Templarian/MaterialDesign#3929]
The only iPhone style icons that currently exist are those with the home button at the bottom.  There are plenty of generic cellphone icons but none with a notch that could be used to represent newer phone models.

**Comment by Templarian** [comment]
🤣 Yeah... the notch, hole punch, etc. They are all temporary workarounds until they find a nicer way to solve this issue. They also all look the same in the smaller size.

We'll actually probably deprecate the iphone specific icons shortly and merge them all into a single icon. All phones look basically the same now.
