### ISSUE TITLE
Email in box, link in box

### ISSUE THREAD

**Issue by Eitz** [Templarian/MaterialDesign#393]
Just like "facebook-box" and "twitter-box"

![screenshot from 2015-05-29 09 38 41](https://cloud.githubusercontent.com/assets/6805910/7882645/1e8b8b20-05e6-11e5-82dc-69012cba9198.png)
- [ ] email-box
- [x] link-box

**Comment by GreenTurtwig** [comment]
Email box:
![](https://puu.sh/vEn5l.png)
![](https://puu.sh/vEn6N.png)
[email-box.zip](https://github.com/Templarian/MaterialDesign/files/974018/email-box.zip)

**Comment by CoDEmanX** [comment]
Preview:

![image](https://user-images.githubusercontent.com/1309249/38769795-e791a126-4008-11e8-9278-ba80b81d38b7.png)

Not sure, maybe make the letter a bit smaller (1px on each side in width and probably 1px in total in height)?

**Comment by goyney** [comment]
Here are the `link` versions. @CoDEmanX just needs to solidify his `email-box` icon and create and outlined version for this issue to be complete.

![image](https://user-images.githubusercontent.com/1015040/48750677-628fde00-ec4e-11e8-8673-36890dc64306.png)![image](https://user-images.githubusercontent.com/1015040/48750683-6a4f8280-ec4e-11e8-90c7-b9b33c4dfc80.png)
![image](https://user-images.githubusercontent.com/1015040/48750689-74718100-ec4e-11e8-81a9-7240ea5a1c7e.png)![image](https://user-images.githubusercontent.com/1015040/48750694-7afff880-ec4e-11e8-99e5-f22938549d4d.png)

[link-box.zip](https://github.com/Templarian/MaterialDesign/files/2598001/link-box.zip)

**Comment by CoDEmanX** [comment]
It's from @GreenTurtwig, I only added a preview image.

**Comment by Templarian** [comment]
[![email-box](https://materialdesignicons.com/icon/email-box)](https://materialdesignicons.com/icon/email-box)

[![link-box](https://materialdesignicons.com/icon/link-box)](https://materialdesignicons.com/icon/link-box) [![link-box-outline](https://materialdesignicons.com/icon/link-box-outline)](https://materialdesignicons.com/icon/link-box-outline) [![link-box-variant](https://materialdesignicons.com/icon/link-box-variant)](https://materialdesignicons.com/icon/link-box-variant) [![link-box-variant-outline](https://materialdesignicons.com/icon/link-box-variant-outline)](https://materialdesignicons.com/icon/link-box-variant-outline)
