### ISSUE TITLE
Palette outline

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#3932]
Hey,
I'd like to replace solid icons with outline ones in an app and need an outline variant of https://materialdesignicons.com/icon/palette for that. Thanks for all the other icons :+1: .

**Comment by CoDEmanX** [comment]
There is an official Google outline variant:
https://material.io/tools/icons/?search=palette&icon=palette&style=outline

**Comment by mueller-ma** [comment]
Thanks for the hint, @CoDEmanX :+1:

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53294415-27083100-37b4-11e9-9779-75f6777b2931.png)
[palette-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2897516/palette-outline.svg.zip)

**Comment by PeterShaggyNoble** [comment]
[![palette-outline](https://user-images.githubusercontent.com/15157491/53433250-fd394f00-39eb-11e9-9e27-6b00acce7955.png)](https://materialdesignicons.com/icon/palette-outline)
