### ISSUE TITLE
Electrical-resistance

### ISSUE THREAD

**Issue by mattpurnell** [Templarian/MaterialDesign#3933]
![image](https://user-images.githubusercontent.com/35792584/53235491-cd8dfc80-36f6-11e9-904a-fe7e6ca23494.png)

**Comment by PeterShaggyNoble** [comment]
This already exists as `omega`. We'll need to alias it as `electrical-resistance` and `ohm`.

[![omega](https://user-images.githubusercontent.com/15157491/53240454-a7387480-3696-11e9-8362-cf466cfc9df6.png)](https://materialdesignicons.com/icon/omega)

**Comment by mattpurnell** [comment]
Ahh great thanks!

**Comment by goyney** [comment]
Aliases added.
