### ISSUE TITLE
Ads and no-ads icon

### ISSUE THREAD

**Issue by da411d** [Templarian/MaterialDesign#3934]
maybe something like this....

![image](https://user-images.githubusercontent.com/12462454/53268582-2eb1d200-36ef-11e9-9259-18dce6886963.png)

**Comment by Templarian** [comment]
We need to name these in a way that won't be blocked by ad blockers. `mdi-ad` and `mdi-advertisement` may not display on some devices.

**Comment by CoDEmanX** [comment]
Gonna be tricky... I saw ad blocker rules blocking everything prefixed "ad".mdi-a-ds would be odd, maybe mdi-promo?On the other hand, we already have icons named adchoices, adjust and adobe...

**Comment by PeterShaggyNoble** [comment]
See also Google's `youtube_ad` icon:

![youtube_ad](http://mdi.houseofdesign.ie/tools/preview/?icon=youtube-ad)

There's a potential language conflict here, though, but I don't know how we'd get around it. Google have a few other options but none really work to express an ad.

![ad](http://mdi.houseofdesign.ie/tools/preview/?icon=ad) ![ad_group](http://mdi.houseofdesign.ie/tools/preview/?icon=ad_group) ![planner_banner_ad_ls](http://mdi.houseofdesign.ie/tools/preview/?icon=planner_banner_ad_ls) ![planner_banner_ad_pt](http://mdi.houseofdesign.ie/tools/preview/?icon=planner_banner_ad_pt) ![planner_banner_ad_sq](http://mdi.houseofdesign.ie/tools/preview/?icon=planner_banner_ad_sq) ![text_ad](http://mdi.houseofdesign.ie/tools/preview/?icon=text_ad)

**Comment by JamesCoyle** [comment]
Isn't that AD icon for audio description?

**Comment by goyney** [comment]
At this point, I feel like we should just add these two. @Templarian?

**Comment by Templarian** [comment]
Sure, worst case they don't render for webfont users. nbd.

Use `advertisement` for the name?

**Comment by JapanYoshi** [comment]
None of these convey "ads" without words.

**Comment by goyney** [comment]
[![advertisements](https://materialdesignicons.com/icon/advertisements)](https://materialdesignicons.com/icon/advertisements)[![advertisements-off](https://materialdesignicons.com/icon/advertisements-off)](https://materialdesignicons.com/icon/advertisements-off)
