### ISSUE TITLE
Icon request: Sonos Speaker

### ISSUE THREAD

**Issue by CaptainFuzzyFace** [Templarian/MaterialDesign#3935]
Suggestion.

![image](https://user-images.githubusercontent.com/6475306/53286605-06ff5000-3769-11e9-8834-704e74467f9f.png)

**Comment by Templarian** [comment]
Same reason as the other issue. We've decided not to add branded icons for home devices as there are too many (we actually went through and removed any a few releases ago).

We can add generic looking icons, but for speakers it's difficult as they are simple in shape.

**Comment by CaptainFuzzyFace** [comment]
That's fine. Perfectly reasonable decision.
