### ISSUE TITLE
Investment or business idea

### ISSUE THREAD

**Issue by FANMixco** [Templarian/MaterialDesign#3937]
I thought in an idea for business ideas or investments, the icon is a small modification of the bulb icon:

![investment](https://user-images.githubusercontent.com/1666156/53287639-6cf6d200-377f-11e9-9852-154c0a3ae310.png)

Is it possible to add it? Thanks!

**Comment by Templarian** [comment]
Do you have an example that doesn't use the USD dollar symbol `$`. One of our guidelines is not to use currency symbols.

**Comment by FANMixco** [comment]
I found this icon in the website for generic currency, but I'm not sure if it's going to be understandable, 

![innovation2](https://user-images.githubusercontent.com/1666156/53289963-f61d0180-379d-11e9-934f-5a4dbcc8b938.png)

Or this one with a 100 paper money.
![innovation3](https://user-images.githubusercontent.com/1666156/53289981-3f6d5100-379e-11e9-8d48-993a48014def.png)

**Comment by FANMixco** [comment]
My other ideas involves to create 2 icons:
Golden bars:
![golden bars 2](https://user-images.githubusercontent.com/1666156/53290192-d6d3a380-37a0-11e9-881d-5c870b864566.png)

I got some inspiration from here:
http://www.free-icons-download.net/gold-bar-icon-70617/

And combine them with the bulb:
![innovation 4](https://user-images.githubusercontent.com/1666156/53290199-e9e67380-37a0-11e9-91fa-5a857be5e6cb.png)

Then it will be somehow neutral. What do you think?

**Comment by goyney** [comment]
No offense, but I don't think any of those work. I would simply use `lightbulb-on`. Used in the correct context, it would make sense.

**Comment by FANMixco** [comment]
> No offense, but I don't think any of those work. I would simply use `lightbulb-on`. Used in the correct context, it would make sense.

What about the Golden Bars? I think it could be another icon since it's not existent.

**Comment by CoDEmanX** [comment]
Gold ingots as icon would be a good addition.Maybe there's another way to represent "investment" still, although I can't think of one. Abstract concepts are often difficult to depict in a minimalist icon.

**Comment by MrGrigri** [comment]
Gold Ingot is already included as an issue. #2386

**Comment by goyney** [comment]
We're going to close this issue because the we feel that an "idea" can be handled by the `lightbulb` icons. Additionally, gold ingots are already being tracked in #2386. Thanks for your suggestion.

**Comment by RubyCastaneda77** [comment]
I think it's worth learning more about business ideas.
