### ISSUE TITLE
Window Shutters

### ISSUE THREAD

**Issue by gibman** [Templarian/MaterialDesign#3938]
Something like..

https://www.iconfinder.com/icons/2902426/blinds_garage_roller_shutters_icon

**Comment by goyney** [comment]
That seems to be more of a security or hurricane type window shutter. When I think of window shutters, I picture:

![image](https://user-images.githubusercontent.com/1015040/53382741-3bc6ff00-3943-11e9-85cb-db704832f6dc.png)

**Comment by gibman** [comment]
A typical use case is preventing the sun from heating up the interior of the house.

for roof windows:
https://www.knall.uk/media/towary/big/9b/9b263c03114886cb9922c999327a89a5.jpg

for normal windows:
https://freedomwindowrollershutters.files.wordpress.com/2015/01/window-roller-shutters.jpg?w=529&h=396

both are often operated using a remote control of some sort.

**Comment by PeterShaggyNoble** [comment]
Duplicate of #2766
