### ISSUE TITLE
Awning

### ISSUE THREAD

**Issue by gibman** [Templarian/MaterialDesign#3939]
Inspiration :

https://www.canstockphoto.com/awnings-and-canopies-of-buildings-30381026.html

Dont know how to suggest a proper icon for this:

https://www.pinterest.dk/pin/313985405256077507/

**Comment by PeterShaggyNoble** [comment]
Google's `storefront` icon might be suitable here.

[![storefront](https://user-images.githubusercontent.com/15157491/53507624-215e6400-3ab0-11e9-9f56-69375c48c57d.png)](https://github.com/Templarian/MaterialDesign/files/2911385/storefront.zip)

**Comment by gibman** [comment]
Would it be possible to a version of this icon that represents a retracted state of the awning.

eg when not in use.

**Comment by goyney** [comment]
[![storefront](https://materialdesignicons.com/icon/storefront)](https://materialdesignicons.com/icon/storefront)
