### ISSUE TITLE
Game console icons.

### ISSUE THREAD

**Issue by nchhina** [Templarian/MaterialDesign#394]
How about game console icons - xbox, playstation, nintendo

- [x] playstation
- [x] wii (for lack of a nintendo icon this will have to suffice)

**Comment by Templarian** [comment]
I have one in there for the Xbox, I'll add the playstation, but I don't think the nintendo icon would work.

Is there an alternative for them that could fix in 20x20?

**Comment by nchhina** [comment]
Yup, you are right, nintendo is not pliable into a 20x20 icon. How about Wii, that can be iconified.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/playstation
http://materialdesignicons.com/icon/wii
