### ISSUE TITLE
ashes

### ISSUE THREAD

**Issue by BruceBuckland** [Templarian/MaterialDesign#3940]
Need ashes to be the opposite of fire.

Also would be useful to have fire in a fireplace, and a cold, unlit fireplace.

These are useful for home automation systems that control the fireplace.

**Comment by goyney** [comment]
`fireplace` will be added in https://github.com/Templarian/MaterialDesign/issues/3777. We could probably add a variation without a fire there.

I'm not sure how we would depict "ashes".

**Comment by goyney** [comment]
We've added both an on and off fireplace in #3777. I don't think there's a good way to depict "ashes" in a simplistic and material fashion that will make sense at native size. If you can think of a way, or provide some examples of a way, to potentially depict ashes, please comment here and we'll reconsider the idea. Thanks for your suggestions!

**Comment by PeterShaggyNoble** [comment]
[This](https://thenounproject.com/term/ashes/335562/) is all The Noun Project has for a pile of ashes; it's not great.
