### ISSUE TITLE
pollution

### ISSUE THREAD

**Issue by haabe** [Templarian/MaterialDesign#3941]
I'd love to see air pollution as an icon / multiple icons ie pollution--none, pollution--low, pollution--medium, pollution--high, pollution--extreme

**Comment by goyney** [comment]
I'm not sure how we would represent this in a minimal icon.

Would `smog` not be sufficient?

[![smog](https://materialdesignicons.com/icon/smog)](https://materialdesignicons.com/icon/smog)

**Comment by goyney** [comment]
Closing this since `Needs More Information` was added a week ago. Please let us know if you have other ideas for how to depict pollution if `smog` doesn't work for your use case and we'll reconsider this. Thanks!
