### ISSUE TITLE
zone1, zone2, zone1+2 icons

### ISSUE THREAD

**Issue by thabet-h** [Templarian/MaterialDesign#3942]
I'd like to request icons for audio video receivers with multi-zone audio...
- **zone1**
-   **zone2**
- **zone1+2**

Maybe something as simple as the box and text in Onkyo's Zone 2 logo;

![image](https://user-images.githubusercontent.com/36610722/53380426-04be1100-3976-11e9-9e00-d9409b49c446.png)

I would use the icons on my media control panel on Home Assistant as buttons to control the zones, as opposed to this:

![image](https://user-images.githubusercontent.com/36610722/53380647-d0972000-3976-11e9-9640-532eec90d169.png)

Great work on this project!

**Comment by goyney** [comment]
I believe these are way too niche for us to add. We have the `numeric-*` icons which should solve this use case nicely.
