### ISSUE TITLE
staffbase

### ISSUE THREAD

**Issue by leventeolahx** [Templarian/MaterialDesign#3943]
Would be nice to have a staffbase icon for those who are integrating staffbase into their system.

![image](https://user-images.githubusercontent.com/22756232/53401963-1e307e80-39b1-11e9-85de-f24596f3dd17.png)

For https://staffbase.com/en/

**Comment by goyney** [comment]
I'm going to say this is probably too niche to be added. We typically only add icons from larger social media type brands.

**Comment by PeterShaggyNoble** [comment]
Agreed with @goyney.
