### ISSUE TITLE
equalizer

### ISSUE THREAD

**Issue by Hutsko** [Templarian/MaterialDesign#3944]
![equalizer_black_144x144](https://user-images.githubusercontent.com/27406893/53413989-47afd100-39d6-11e9-846f-deae07b661a0.png)

**Comment by goyney** [comment]
This already exists as `poll`. We'll alias it with `equalizer`.
[![poll](https://materialdesignicons.com/icon/poll)](https://materialdesignicons.com/icon/poll)

**Comment by goyney** [comment]
Actually, it looks like Google has a stock icon called `equalizer` that matches the bar heights from the original request. Perhaps we should just add that.

![image](https://user-images.githubusercontent.com/1015040/53416775-2b923c80-39a2-11e9-8aff-af32765a47d0.png)

---

Google, however, does *not* have an outlined version, so here is that one as well.

![image](https://user-images.githubusercontent.com/1015040/53416816-406ed000-39a2-11e9-9680-d8a2104cb701.png)


[equalizer.zip](https://github.com/Templarian/MaterialDesign/files/2905711/equalizer.zip)

**Comment by MrGrigri** [comment]
We already have `tune` and `tune-vertical`

![tune](https://materialdesignicons.com/icon/tune) ![tune-vertical](https://materialdesignicons.com/icon/tune-vertical)

**Comment by Templarian** [comment]
[![equalizer](https://materialdesignicons.com/icon/equalizer)](https://materialdesignicons.com/icon/equalizer) [![equalizer-outline](https://materialdesignicons.com/icon/equalizer-outline)](https://materialdesignicons.com/icon/equalizer-outline)
