### ISSUE TITLE
account-badge-horizontal

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3945]
With reference to #3898, Google has a 'horizontal' badge outline. The only thing I don't like about this badge is the clip. I believe I like ours better. I'm not a fan of 1-pixel rounded corners, nor the wider clip base

![menu-personal-info](https://user-images.githubusercontent.com/4528551/53425156-c63e4b80-39a1-11e9-991a-d20cdef51337.png)

This are my preferred variants. However, I don't believe there is room for an `alert` modifier with these 'horizontal' variants.

![account-badge-horizontal-outline](https://user-images.githubusercontent.com/4528551/53425650-a9564800-39a2-11e9-9af0-5d1a04c9076c.png) ![account-badge-horizontal](https://user-images.githubusercontent.com/4528551/53425628-9e9bb300-39a2-11e9-9dc9-d6c356439b01.png)

---
#### Files

[account-badge.zip](https://github.com/Templarian/MaterialDesign/files/2906260/account-badge.zip)

**Comment by Templarian** [comment]
Added. 😃
