### ISSUE TITLE
Power pole

### ISSUE THREAD

**Issue by hehrsson** [Templarian/MaterialDesign#3946]
I would like an icon that looks like a power pole.
Want to use it to my solar panel versus power import from grid layout.

In my solar panel dashboard, my supplier SolarEdge use this icon:
![image](https://user-images.githubusercontent.com/6585546/53442261-3633ec80-3a09-11e9-8bb9-8cb886d51932.png)

**Comment by goyney** [comment]
We already have this icon included in the library:

[![transmission-tower](https://materialdesignicons.com/icon/transmission-tower)](https://materialdesignicons.com/icon/transmission-tower)
