### ISSUE TITLE
Solar panel

### ISSUE THREAD

**Issue by hehrsson** [Templarian/MaterialDesign#3947]
I would like an icon that looks like solar panels.
Want to use it to my solar panel versus power import from grid layout.

I know there is a grid icon, but it's not so explaining.
In my solar panel dashboard, my supplier SolarEdge use this icon:
![image](https://user-images.githubusercontent.com/6585546/53442366-72674d00-3a09-11e9-95c7-d7d6773d1400.png)

**Comment by goyney** [comment]
These are also already included:
[![solar-panel](https://materialdesignicons.com/icon/solar-panel)](https://materialdesignicons.com/icon/solar-panel)[![solar-panel-large](https://materialdesignicons.com/icon/solar-panel-large)](https://materialdesignicons.com/icon/solar-panel-large)

**Comment by Mariusthvdb** [comment]
Or use solar-power
