### ISSUE TITLE
Calendar-range but with an extra line of dots

### ISSUE THREAD

**Issue by martinory** [Templarian/MaterialDesign#3949]
Hi!
Would like to have a calendar icon similar to calendar-range but with an extra line of dots that could be called calendar-bullets or calendar-bullet-list or something likewise.
Kind regards, Martin

**Comment by goyney** [comment]
That seems oddly specific. Could you maybe explain your use case a little bit?

**Comment by martinory** [comment]
I was thinking of the icon Todoist uses for "next 7 days" but perhaps this is too much of a request.

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/53609424-c8f49880-3b7b-11e9-83db-e6f9f2aa4d1b.png)
[calendar-bullets.svg](https://github.com/terreng/samples/blob/master/calendar-bullets.svg)

![image](https://user-images.githubusercontent.com/11605395/53609472-ff321800-3b7b-11e9-8538-f6444c4ed6e2.png)
[calendar-bullets-outline.svg](https://github.com/terreng/samples/blob/master/calendar-bullets-outline.svg)

**Comment by PeterShaggyNoble** [comment]
Call them `calendar-month`, maybe?

**Comment by Templarian** [comment]
Seeing as the calendar icons are heavily popular I'm fine adding specific variations like this. Agreed about the naming, `calendar-month` makes sense.

@terreng Created you placeholder contributor account in the DB and assigned the 3 so far to it.

**Comment by PeterShaggyNoble** [comment]
The filled version got added twice.
