### ISSUE TITLE
Captcha Icon

### ISSUE THREAD

**Issue by Pseudocode99** [Templarian/MaterialDesign#395]
would be great to see it here...
- [ ] captcha

**Comment by Templarian** [comment]
Do you have an example of what this would look like?

**Comment by Pseudocode99** [comment]
![captcha](https://cloud.githubusercontent.com/assets/12672113/7901896/2f31157e-07a0-11e5-936b-ab5a0aab5387.png)
Syncfusion Metro Studio has something like this...

**Comment by CoDEmanX** [comment]
Maybe this with a diagonal line?
![](https://camo.githubusercontent.com/a1428ba7fea6325312b58842daf3a221db7c9f64/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3138393334382f313934373330332f65313065393236382d383034622d313165332d383464312d6461356436616530396436612e706e67)

**Comment by Pseudocode99** [comment]
the robot is a great idea, but maybe a captcha like text in the middle?

**Comment by danielhickman** [comment]
Seems kinda hard to get across with the distortions in the small grid of pixels.
