### ISSUE TITLE
rectangle(-outline)

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3950]
shape-rectangle-plus without the -plus, called rectangle-outline

**Comment by terreng** [comment]
Simple enough

![image](https://user-images.githubusercontent.com/11605395/53674780-37e9f400-3c45-11e9-9aea-3c9116d37256.png)
[rectangle-outline.svg](https://github.com/terreng/samples/blob/master/rectangle-outline.svg)

**Comment by goyney** [comment]
@terreng Let's add a filled version too please!

**Comment by terreng** [comment]
Here we are

![image](https://user-images.githubusercontent.com/11605395/53689770-ff641c00-3d11-11e9-9c1c-374c6e8efae4.png)
[rectangle.svg](https://github.com/terreng/samples/blob/master/rectangle.svg)

**Comment by Templarian** [comment]
Usually it takes the skill set of @PeterShaggyNoble to design these ones.

Added both.

**Comment by PeterShaggyNoble** [comment]
Harsh!

But accurate!
