### ISSUE TITLE
clock-digital

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3951]
digital-clock that looks like: 12:00 with a rounded box around it. There could probably be variants with AM/PM.

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/53508031-e7da2880-3ab0-11e9-8592-6e7ab3ba25c8.png)![](https://user-images.githubusercontent.com/15905797/53508067-f9233500-3ab0-11e9-9caa-41b4299ef4ed.png)
![](https://user-images.githubusercontent.com/15905797/53508110-093b1480-3ab1-11e9-9440-c5022313468a.png)

[clock-digital.zip](https://github.com/Templarian/MaterialDesign/files/2911404/clock-digital.zip)

Second one is the only decent of the bunch I feel.

**Comment by GreenTurtwig** [comment]
Time on the second matches `clock` BTW

**Comment by MrGrigri** [comment]
I don't think they're recognizable at 1x

**Comment by Templarian** [comment]
Added. Agreed, not great, but we can replace it later if something better comes along. It's useful as is for now.
