### ISSUE TITLE
Gatsby icon

### ISSUE THREAD

**Issue by Seru88** [Templarian/MaterialDesign#3952]
A Gatsby logo icon. https://www.gatsbyjs.org/

**Comment by terreng** [comment]
Hot off the press

![image](https://user-images.githubusercontent.com/11605395/53689646-1f461080-3d0f-11e9-917d-1b56785b258d.png)
[gatsby.svg](https://github.com/terreng/samples/blob/master/gatsby.svg)

**Comment by JapanYoshi** [comment]
IIRC, we've limited new logo additions to social media only...

**Comment by goyney** [comment]
This has been approved internally by the team.

**Comment by Templarian** [comment]
Added. Since it's a brand icon @terreng it gets assigned to the shared contributor account.
