### ISSUE TITLE
Fitness Tracker

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#3953]
Example: http://store-images.s-microsoft.com/image/apps.52593.13510798883717724.b037c830-81a3-441f-aff9-4c8d998c476a.a9d22748-7d44-4919-acb7-027cde04b121

**Comment by PeterShaggyNoble** [comment]
Would `watch-variant` work for a fitness tracker?

**Comment by mueller-ma** [comment]
Not really. I need this icon for a mi band and it's more a band than a watch.

**Comment by PeterShaggyNoble** [comment]
We try to avoid adding icons for *specific* devices, preferring instead to keep them as generic as we can. Are most of these fitness trackers bands? I thought they were mostly more watch-like. I'm too old to be keeping with all these new devices, though! 😆

**Comment by mueller-ma** [comment]
Most of them have a "watch-like" display, but the display has the same width than the ribbon: https://duckduckgo.com/?q=fitness+tracker&t=ffab&iax=images&ia=images

**Comment by terreng** [comment]
How about this?

![image](https://user-images.githubusercontent.com/11605395/53608752-d3616300-3b78-11e9-9947-a2c7f77cf9e1.png)
[watch-fitness.svg](https://github.com/terreng/samples/blob/master/watch-fitness.svg)

**Comment by goyney** [comment]
Icon artwork shouldn't extend into the 2dp buffer area, so that wouldn't really work.

**Comment by terreng** [comment]
I based this off of the watch and watch-variant icons, which do indeed extend into the buffer area. Nonetheless I have adjusted it to fit.

![image](https://user-images.githubusercontent.com/11605395/53609767-3f45ca80-3b7d-11e9-80ed-62124554fcd8.png)
[watch-fitness-2.svg](https://github.com/terreng/samples/blob/master/watch-fitness-2.svg)

**Comment by goyney** [comment]
We feel that this icon is too specific. There are other icons which can convey the meaning of a fitness band already included in the library that are much more generic. If used in the proper context, I don't think anyone would have a problem understanding what it is supposed to represent.

Thank you for your suggestion.

**Comment by mueller-ma** [comment]
@terreng Under which license do you release your WIP watch-fitness icon?

**Comment by terreng** [comment]
> @terreng Under which license do you release your WIP watch-fitness icon?

[MIT License](https://opensource.org/licenses/MIT)
