### ISSUE TITLE
Request: Brand Mi

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#3954]
http://pluspng.com/img-png/xiaomi-png-how-to-use-your-xiaomi-mi-1-or-mi-2-smartband-on-a-treadmill-850.png

**Comment by goyney** [comment]
I'm going to say this is probably too niche to be added. We typically only add icons from larger social media type brands.

**Comment by PeterShaggyNoble** [comment]
Agreed with @goyney.
