### ISSUE TITLE
nfc-search(-variant)

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#3955]
Hey,
I'd like to see a combination of https://materialdesignicons.com/icon/magnify and https://materialdesignicons.com/icon/nfc-variant. I want to show this icon when an app waits for the user to put the nfc tag next to the device.

**Comment by terreng** [comment]
How's this?

![image](https://user-images.githubusercontent.com/11605395/53674637-1fc5a500-3c44-11e9-8681-6d70ee4326a9.png)
[nfc-search-variant.svg](https://github.com/terreng/samples/blob/master/nfc-search-variant.svg)

**Comment by mueller-ma** [comment]
Great! Thanks

**Comment by Templarian** [comment]
@terreng Nicely done. I'm bad at keeping track, let me know when you hit 5 icons and I'll transfer them over to a contributor account.

By the way, when cutting an object with a circle be careful not to include extra points. Fixed it for this path.

If you're curious about learning more about the naming: http://dev.materialdesignicons.com/contribute/icon-naming

[![nfc-search-variant](https://materialdesignicons.com/icon/nfc-search-variant)](https://materialdesignicons.com/icon/nfc-search-variant)

Thanks!
