### ISSUE TITLE
file-image-outline

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3956]
file-image, but outline

**Comment by terreng** [comment]
How's this?

![image](https://user-images.githubusercontent.com/11605395/53675097-f9096d80-3c47-11e9-9e43-59162c943ea6.png)
[file-image-outline.svg](https://github.com/terreng/samples/blob/master/file-image-outline.svg)

**Comment by goyney** [comment]
@terreng Make sure to combine all your paths down to a single path when posting contributions please. :)

**Comment by Templarian** [comment]
Added. 😃
