### ISSUE TITLE
file-video-outline

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3957]
file-video, but outlined

**Comment by PeterShaggyNoble** [comment]
[![file-video-outline](https://user-images.githubusercontent.com/15157491/53646884-38c65a00-3c34-11e9-9814-36eb0c0ca4fa.png)](https://github.com/Templarian/MaterialDesign/files/2919962/file-video-outline.zip)

**Comment by Templarian** [comment]
[![file-video-outline](https://materialdesignicons.com/icon/file-video-outline)](https://materialdesignicons.com/icon/file-video-outline)

Added, with some changes. We'll make you an icon designer eventually. 😃

**Comment by PeterShaggyNoble** [comment]
Ha! My boss has been trying for ~20 years!

I did try it with the smaller camera but the lens gets a bit lost at native size.
