### ISSUE TITLE
file-music-outline

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3959]
~file-audio~ file-music, but outlined

**Comment by PeterShaggyNoble** [comment]
Umm ... we don't have a `file-audio` icon; did you mean `file-music`?

**Comment by sirisian** [comment]
Edited, sorry about that. I transitioned a large project over to this icon pack. Have the names all mixed up.

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/53675171-c90e9a00-3c48-11e9-8f73-9fb53d2b4c21.png)
[file-music-outline.svg](https://github.com/terreng/samples/blob/master/file-music-outline.svg)

**Comment by goyney** [comment]
The stock Google music note icon was updated a while ago. Our current `file-music` and this new outlined variation are using the old music note. Can you please update both and attach them here so we can fix the current one and add your new one?

For reference, see https://github.com/Templarian/MaterialDesign/issues/3263 or https://material.io/tools/icons/?search=music&icon=music_note&style=baseline.

Thank you!

**Comment by terreng** [comment]
Here I've updated the music note for both

![image](https://user-images.githubusercontent.com/11605395/53690072-5d93fd80-3d18-11e9-9389-1ee74ac6d4d2.png)
[file-music.svg](https://github.com/terreng/samples/blob/master/file-music.svg)

![image](https://user-images.githubusercontent.com/11605395/53690027-b747f800-3d17-11e9-935c-cc8963a0b2b4.png)
[file-music-outline-2.svg](https://github.com/terreng/samples/blob/master/file-music-outline-2.svg)

**Comment by Templarian** [comment]
Updated and added. 😃
