### ISSUE TITLE
Sheep

### ISSUE THREAD

**Issue by ComeBurguburu** [Templarian/MaterialDesign#396]
Can we have a clone icon represent by a single sheep
- [ ] sheep

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48686654-192a8a80-eb8b-11e8-9cd1-dae07da8fa0e.png)
[sheep.zip](https://github.com/Templarian/MaterialDesign/files/2593806/sheep.zip)

**Comment by ComeBurguburu** [comment]
Hello,
My idea was to use an icon of a sheep to represent the concept of cloning 
The idea came from Virtualbox: https://cdn-sysprobs.netdna-ssl.com/wp-content/uploads/2011/09/clickclone.png

May we have the body of the sheep ?

**Comment by Templarian** [comment]
[![sheep](https://materialdesignicons.com/icon/sheep)](https://materialdesignicons.com/icon/sheep)
