### ISSUE TITLE
file-delimited-outline

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3960]
file-delimited, but outlined

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/53675236-636edd80-3c49-11e9-8028-ff26bc64f275.png)
[file-delimited-outline.svg](https://github.com/terreng/samples/blob/master/file-delimited-outline.svg)

**Comment by Templarian** [comment]
Added. 😃

**Comment by JapanYoshi** [comment]
The comma looks wonky in that preview. Can we use the one in the numeric format icon?

**Comment by CoDEmanX** [comment]
I agree that is doesn't look very materialy...
