### ISSUE TITLE
camera-retake(-outline)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#3961]
![camera-retake](https://user-images.githubusercontent.com/4528551/53600764-9771d200-3b67-11e9-9723-e287a0e905ab.png) ![camera-retake-outline](https://user-images.githubusercontent.com/4528551/53600953-27178080-3b68-11e9-8531-073106dbeb0a.png)

---
#### Files
[camera-retake.zip](https://github.com/Templarian/MaterialDesign/files/2917039/camera-retake.zip)

**Comment by Templarian** [comment]
Added.
