### ISSUE TITLE
Rivet

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3962]
Related to #3887

Some experiments:

![grafik](https://user-images.githubusercontent.com/1309249/53641549-a6bc5280-3c2f-11e9-8f3e-37e89661af28.png)
![grafik](https://user-images.githubusercontent.com/1309249/53642226-8e4d3780-3c31-11e9-9a8d-8a7d27ce8212.png)
![grafik](https://user-images.githubusercontent.com/1309249/53641785-4679e080-3c30-11e9-8dd6-132fb63df668.png)
![grafik](https://user-images.githubusercontent.com/1309249/53641962-c86a0980-3c30-11e9-83dd-66a706a632a5.png)

**Comment by goyney** [comment]
The last one looks like an eye dropper. :)

**Comment by JamesCoyle** [comment]
2dp stem is best. Rounded corners on the top need to be separated like in 3 and not a complete radius like 4. The angled bottom of 4 is good though.

**Comment by CoDEmanX** [comment]
5, 6 and 7:

![grafik](https://user-images.githubusercontent.com/1309249/53644255-71673300-3c36-11e9-8120-cc8b4a89aace.png)
![grafik](https://user-images.githubusercontent.com/1309249/53644283-7fb54f00-3c36-11e9-9c79-89dbab043523.png)
![grafik](https://user-images.githubusercontent.com/1309249/53644384-c30fbd80-3c36-11e9-8584-bf05380daea5.png)

**Comment by goyney** [comment]
I think 6 works the best, IMO.

Can you add the source SVG of the one you'd like to contribute so we can label this issue and line it up in a milestone?

**Comment by CoDEmanX** [comment]
Source: [rivet-6.zip](https://github.com/Templarian/MaterialDesign/files/2922852/rivet-6.zip)

**Comment by Templarian** [comment]
Added, very specific.
