### ISSUE TITLE
Money transfer / transaction

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#3963]
Ref: https://github.com/Templarian/MaterialDesign/issues/2177#issuecomment-421663835

In my online banking, for transactions they use this: ![image](https://user-images.githubusercontent.com/1309249/31473016-5790a0c4-aef2-11e7-8579-79d5e1a82863.png)

![grafik](https://user-images.githubusercontent.com/1309249/53650588-2c96c880-3c45-11e9-83c3-dba88370f3c7.png)
![grafik](https://user-images.githubusercontent.com/1309249/53650616-3ae4e480-3c45-11e9-8e2a-fc5c940370d6.png)

[transfer.zip](https://github.com/Templarian/MaterialDesign/files/2920216/transfer.zip)

Unsure about the size of the arrow head, but I think I'm in favor of the smaller one in the first variant.

**Comment by goyney** [comment]
I like the first one.

**Comment by CoDEmanX** [comment]
The second one with the smaller arrow head would basically the sharp variant.

**Comment by PeterShaggyNoble** [comment]
Would the `bank-transfer` icons not cover this?

**Comment by CoDEmanX** [comment]
Hm yes, but I still like the concept of this icon very much. It could also be used for other, non-monetary things. What else could it be called?

**Comment by CoDEmanX** [comment]
Could be used in a database system for a Rebalance shards action or similar.

**Comment by goyney** [comment]
[![transfer](https://materialdesignicons.com/icon/transfer)](https://materialdesignicons.com/icon/transfer)
