### ISSUE TITLE
Update account-box-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3966]
![image](https://user-images.githubusercontent.com/1015040/53704844-1710d280-3dee-11e9-859a-af1fbe1f0e33.png)

Outline is our current version.
[account-box-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2923928/account-box-outline.svg.zip)

**Comment by JapanYoshi** [comment]
Oof, I think the inside looks really crowded

**Comment by Templarian** [comment]
Closing this issue as this looks too crowded.
