### ISSUE TITLE
call-merge and call-split icons

### ISSUE THREAD

**Issue by caseyjhol** [Templarian/MaterialDesign#397]
![mergeicons](https://cloud.githubusercontent.com/assets/2874325/7899742/52299082-06ed-11e5-8056-801265464ac9.png)

**Comment by Templarian** [comment]
Yea, I'll be adding all the new 80+ stock icons that Google released soon. Will take a second to get them all imported into the system.

**Comment by danielhickman** [comment]
Is there a list of Google icons that need to be added?

**Comment by Templarian** [comment]
I asked them that yesterday. They said the best solution for now is to use their git history to see the 80+ new icons. I'll do that and import them one by one into the system.

I already have the 1.1.34 package ready for an update with 60+ new community icons. The new Google ones will go in the next release. This is the first release with the CDN and non-beta status so I don't want to delay it.

**Comment by danielhickman** [comment]
Ah okay. I think polymer has a copy of their newest ones all compressed in a single path that can be compared against. I bet they don't update it as often, but it may be interesting to see it that works.

**Comment by Templarian** [comment]
I just realized it's going to be a manual process finding the new icons. They renamed a lot of their icons, and pretty much wiped out their repo and reuploaded the new icons.

Not a huge issue, but kind of slows down the process.

**Comment by Templarian** [comment]
I started a google doc if you want to help it is attached to issue #420.

I'm going to close all the stock google issues and add them to the list.
