### ISSUE TITLE
Icon reassignments

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3972]
This issue piggybacks off of #3163 and contains many Stock Google Icons that are wrongly attributed to people instead of Google and that we should reattribute.

_Will be updated._

- [x] `cart-outline` *(Attributed to Austin Andrews)*
- [x] `coffee-outline` *(Attributed to Case Sandberg)*
- [x] `fast-forward-outline` *(Attributed to Michael Irigoyen)*
- [x] `file-outline` *(Attributed to Austin Andrews)*
- [x] `hand-right` *(Attributed to Michael Irigoyen)*
- [x] `map-marker-outline` *(Attributed to Austin Andrews)*
- [x] `minus-box-outline` *(Attributed to Austin Andrews)*
- [x] `plus-box-outline` *(Attributed to Michael Irigoyen)*
- [x] `rewind-outline` *(Attributed to Michael Irigoyen)*
- [x] `thumbs-up-outline` *(Attributed to Austin Andrews)*
- [x] `thumbs-down-outline` *(Attributed to Austin Andrews)*

**Comment by Templarian** [comment]
Fixed! 😃
