### ISSUE TITLE
Update compass-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3973]
![image](https://user-images.githubusercontent.com/1015040/53706386-21d06500-3df8-11e9-84df-727e49870f5a.png)
(Our current is outlined.)

**Reassign To:** Google

[compass-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2924054/compass-outline.svg.zip)

**Comment by PeterShaggyNoble** [comment]
I think we should keep ours, with the gap between the compass and the circle.
