### ISSUE TITLE
eye-minus(-outline)

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3976]
![image](https://user-images.githubusercontent.com/1015040/53707162-cbfdbc00-3dfb-11e9-8998-ff002fa30b8c.png)
(Our current is outlined.)

**Reassign To:** Google

---

Also update several variations:

- `eye-check-outline`
- `eye-off-outline`
- `eye-plus-outline`
- `eye-settings-outline`

**Do not reassign.**

---

Add missing `eye-minus-outline`:

![image](https://user-images.githubusercontent.com/1015040/53707390-cbb1f080-3dfc-11e9-8ff4-796c18223e6c.png)

**Assign To:** Michael Irigoyen

[eye-outline.zip](https://github.com/Templarian/MaterialDesign/files/2924118/eye-outline.zip)

**Comment by Templarian** [comment]
This may look weird with the modifiers. 🤷‍♂

**Comment by goyney** [comment]
Yeah, I think I agree. Changing this to be a contribution for `eye-minus(-outline)`.

![image](https://user-images.githubusercontent.com/1015040/61051894-2dd8be80-a3b8-11e9-987f-339cd8a887a0.png)![image](https://user-images.githubusercontent.com/1015040/61051907-37622680-a3b8-11e9-8aec-6134139c58da.png)

[eye-minus.zip](https://github.com/Templarian/MaterialDesign/files/3382027/eye-minus.zip)

**Comment by goyney** [comment]
[![eye-minus](https://materialdesignicons.com/icon/eye-minus)](https://materialdesignicons.com/icon/eye-minus)[![eye-minus-outline](https://materialdesignicons.com/icon/eye-minus-outline)](https://materialdesignicons.com/icon/eye-minus-outline)
