### ISSUE TITLE
Update flag-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3978]
![image](https://user-images.githubusercontent.com/1015040/53707737-31eb4300-3dfe-11e9-8cd0-a8f7380cd5fb.png)
(Our current is outlined.)

**Reassign To:** Google

[flag-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2924139/flag-outline.svg.zip)

**Comment by Templarian** [comment]
Updated.
