### ISSUE TITLE
Update folder-outline/folder-open

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3979]
- [ ] Rename `folder-outline` -> `folder-open`.
- [ ] Rename `folder-open` -> `folder-open-variant`.
- [ ] Rename `folder-open-outline` -> `folder-open-outline-variant`.
- [ ] Alias the new `folder-open` -> `folder-outline`.

---

Additionally, we'll need to update a bunch of `-outline` variations of folder icons to remove the dark-filled tab (which will now indicate "open").

- [ ] `folder-alert-outline`
- [ ] `folder-clock-outline`
- [ ] `folder-edit-outline`
- [ ] `folder-multiple-outline`
- [ ] `folder-pound-outline`
- [ ] `folder-search-outline`
- [ ] `folder-sync-outline`
- [ ] `folder-text-outline`

**Comment by Templarian** [comment]
Little confused why would we would do this. It is an outline of folder. The `*-open` is as it says an opened folder.

Not sure why we would rename these as it would actually make things more confusing.
