### ISSUE TITLE
Update forum-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3980]
![image](https://user-images.githubusercontent.com/1015040/53708046-922eb480-3dff-11e9-99a2-3c281431e428.png)
(Out current is outlined.)

**Reassign To:** Google

[forum-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2924160/forum-outline.svg.zip)

**Comment by Templarian** [comment]
Fixed. 😃
