### ISSUE TITLE
Update home-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3981]
![image](https://user-images.githubusercontent.com/1015040/53708109-dde15e00-3dff-11e9-8f0c-fbc76e50ff17.png)
(Our current is the outline.)

**Reassign To:** Google

[home-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2924170/home-outline.svg.zip)

**Comment by goyney** [comment]
Icon updated:
[![home-outline](https://materialdesignicons.com/icon/home-outline)](https://materialdesignicons.com/icon/home-outline)

Needs to be reassigned to Google.

**Comment by Templarian** [comment]
Reassigned. 👍
