### ISSUE TITLE
Update note-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3982]
![image](https://user-images.githubusercontent.com/1015040/53708240-927b7f80-3e00-11e9-8667-7415d74a832e.png)
(Our current is outlined.)

**Reassign To:** Google

---

Also update several variations:

- `note-multiple-outline`
- `note-plus-outline`

**Do not reassign.**

[note-outline.zip](https://github.com/Templarian/MaterialDesign/files/2924189/note-outline.zip)

**Comment by PeterShaggyNoble** [comment]
I think we should keep our existing one as it matches the size & shape of the filled version.

**Comment by goyney** [comment]
The filled one should be updated as well. I just didn't get to that point last night to create an issue. :)

**Comment by Templarian** [comment]
If I remember right I did this on purpose to make `note-multiple` proportionally correct and not to be confused with a landscape piece of paper.

Opinions? We could definitely add file-landscape or something even if we don't add this one.
