### ISSUE TITLE
Update settings-outline

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3983]
![image](https://user-images.githubusercontent.com/1015040/53708483-b4c1cd00-3e01-11e9-9fc0-4643b5257f8d.png)
(Our current is the outline.)

**Reassign To:** Google

[settings-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2924195/settings-outline.svg.zip)

**Comment by Templarian** [comment]
[![settings-outline](https://materialdesignicons.com/icon/settings-outline)](https://materialdesignicons.com/icon/settings-outline)
