### ISSUE TITLE
bookmark-multiple

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3984]
![image](https://user-images.githubusercontent.com/1015040/53708622-4cbfb680-3e02-11e9-9b60-62abc0c9f491.png)![image](https://user-images.githubusercontent.com/1015040/53708628-52b59780-3e02-11e9-96a3-967a863c5f82.png)

[bookmark-multiple.zip](https://github.com/Templarian/MaterialDesign/files/2924209/bookmark-multiple.zip)

**Comment by Templarian** [comment]
Added, but had to fix the corner to follow the guidelines. 😃
