### ISSUE TITLE
cast-education

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3985]
![image](https://user-images.githubusercontent.com/1015040/53708698-a6c07c00-3e02-11e9-92bf-449f64b91620.png)
[cast-education.svg.zip](https://github.com/Templarian/MaterialDesign/files/2924216/cast-education.svg.zip)

**Comment by Templarian** [comment]
[![cast-education](https://materialdesignicons.com/icon/cast-education)](https://materialdesignicons.com/icon/cast-education)
