### ISSUE TITLE
account-plus-off

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#3986]
![image](https://user-images.githubusercontent.com/1015040/53708844-3fef9280-3e03-11e9-9f01-698b69e27455.png)![image](https://user-images.githubusercontent.com/1015040/53708853-4aaa2780-3e03-11e9-9e60-32ff5a3bab1e.png)

[account-plus-off.zip](https://github.com/Templarian/MaterialDesign/files/2924224/account-plus-off.zip)

**Comment by Templarian** [comment]
Does this seem like a really weird icon to have? Like what would be the use of such an icon?

**Comment by PeterShaggyNoble** [comment]
Disabling the ability to add new accounts, maybe?

**Comment by goyney** [comment]
I don't think we should add these, to be honest. We've made the case for a "disabled" state to use opacity in the past and I think this applies here. Closing.
