### ISSUE TITLE
Update Unity

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3987]
Our `unity` icon is off-centre. First version below is ours recentred with current version in red. Second version is Google's [`plat_unity`](https://petershaggynoble.github.io/MDI-Sandbox/other/) with ours in red.

[![unity](https://user-images.githubusercontent.com/15157491/53723096-de5d1180-3e5e-11e9-8c62-5d945c80d04b.png)](https://github.com/Templarian/MaterialDesign/files/2925645/unity.zip) [![plat_unity](https://user-images.githubusercontent.com/15157491/53723347-8541ad80-3e5f-11e9-9c21-60539db62942.png)](https://github.com/Templarian/MaterialDesign/files/2925672/plat-unity.zip)

**Comment by Templarian** [comment]
Fixed.
