### ISSUE TITLE
Pliers

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#3989]
Splitting from #2366

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/136130060-01bf2694-0c7b-4c46-9894-198f522c3382.png)
[pliers.svg.zip](https://github.com/Templarian/MaterialDesign/files/7290370/pliers.svg.zip)

**Comment by goyney** [comment]
[![pliers](https://materialdesignicons.com/icon/pliers)](https://materialdesignicons.com/icon/pliers)
