### ISSUE TITLE
diaspora

### ISSUE THREAD

**Issue by dasmaeh** [Templarian/MaterialDesign#3991]
![diaspora-brands svg](https://user-images.githubusercontent.com/777345/53740699-141ced00-3e95-11e9-8a19-a0f9bd514a65.png)

**Comment by PeterShaggyNoble** [comment]
Sorry but, with a website global rank of ~255k and only 230 downloads on the Google Play Store, this is far too niche for us to add at this time. If it ever does gain traction then please leave a comment and we'll revisit this issue.
