### ISSUE TITLE
content-save-move

### ISSUE THREAD

**Issue by foridur-kayes** [Templarian/MaterialDesign#3993]

**Comment by MrGrigri** [comment]
Would something like this work?

![content-save-move](https://user-images.githubusercontent.com/4528551/53824175-973f5100-3f30-11e9-8bee-5ab75e13bdb1.png) ![content-save-move-outline](https://user-images.githubusercontent.com/4528551/53824189-a0c8b900-3f30-11e9-8ba3-fffe55325b34.png)

---

####Files

[content-save-move.zip](https://github.com/Templarian/MaterialDesign/files/2932022/content-save-move.zip)

**Comment by Templarian** [comment]
Added. 😃
