### ISSUE TITLE
camera-retake-off-outline

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3995]
In addition to the outline from: #3961

Not sure if this is too niche. I have a toggle that refreshes screenshots in a program. An off variant would be nice.

**Comment by MrGrigri** [comment]
I believe the `retake` design will be lost when the `off` modifier is added.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53850725-4b20fa80-3f8a-11e9-99b2-ed10a4293736.png)![image](https://user-images.githubusercontent.com/1015040/53850740-52e09f00-3f8a-11e9-930f-819382710274.png)

[camera-retake-off.zip](https://github.com/Templarian/MaterialDesign/files/2933985/camera-retake-off.zip)

**Comment by MrGrigri** [comment]
I stand by my comment...I believe the `retake` modifier is lost and unrecognizable. Consider using a disabled state instead.
