### ISSUE TITLE
tablet-variant

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3996]
A tablet icon that looks like monitor-dashboard without the stand. Basically I need a tablet that looks like it has content running.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/53849650-84f00200-3f86-11e9-9601-f5839d680837.png)
[tablet-dashboard.svg.zip](https://github.com/Templarian/MaterialDesign/files/2933919/tablet-dashboard.svg.zip)

**Comment by Templarian** [comment]
Added 😃

**Comment by JapanYoshi** [comment]
While we're at it, can we make `laptop-dashboard`and `phone-dashboard`? It feels a bit weard to have a desktop and a tablet but not a laptop or a phone.
