### ISSUE TITLE
weather-crawl

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3998]
The weather-partlycloudy icon with an arrow under it like format-text-rotation-none has.

**Comment by goyney** [comment]
Not sure how I feel about this use case either, but here's an icon anyways. You're not going to get the sun in there, unfortunately.

![image](https://user-images.githubusercontent.com/1015040/53850568-b3bba780-3f89-11e9-8818-4638c389adcb.png)

[weather-cloudy-arrow-right.svg.zip](https://github.com/Templarian/MaterialDesign/files/2933963/weather-cloudy-arrow-right.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Could you provide a use case for this? As with #3999 I'm thinking it might be better served by another, existing icon.

**Comment by sirisian** [comment]
I have weather and weather crawl widgets, so I was looking for a unique icon to separate them. If it's too niche, you can close it. I can just program an arrow overlay or something.

**Comment by Templarian** [comment]
Not adding it for the use case described, I think it can be useful for wind/cloud direction.

[![weather-cloudy-arrow-right](https://materialdesignicons.com/icon/weather-cloudy-arrow-right)](https://materialdesignicons.com/icon/weather-cloudy-arrow-right)
