### ISSUE TITLE
rss-crawl

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#3999]
The rss icon with an arrow under it like format-text-rotation-none has.

**Comment by goyney** [comment]
Not sure how I feel about this use case, but here's a potential icon anyways:

![image](https://user-images.githubusercontent.com/1015040/53850410-28421680-3f89-11e9-9203-09e7d9f51cd2.png)

[rss-arrow-right.svg.zip](https://github.com/Templarian/MaterialDesign/files/2933953/rss-arrow-right.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Could you provide a use case for this? I'm thinking it might be better served by another, existing icon.

**Comment by sirisian** [comment]
I have rss and rss crawl widgets, so I was looking for a unique icon to separate them. If it's too niche, you can close it. I can just program an arrow overlay or something.

**Comment by Templarian** [comment]
[![signal-distance-variant](https://materialdesignicons.com/icon/signal-distance-variant)](https://materialdesignicons.com/icon/signal-distance-variant)

I think RSS crawl is going to be too niche, but `signal-distance` could be useful.
