### ISSUE TITLE
Trapezium shaped icon and parallelogram shaped icon

### ISSUE THREAD

**Issue by matthijsdewit111** [Templarian/MaterialDesign#400]
For icons perspective transform and shearing.
- [ ] trapezium
- [ ] parallelogram

**Comment by MrGrigri** [comment]
Looking at Wikipedia<sup>†</sup>, there might be some linguistic differences with the term 'Trapezium'. 

> The word trapezium, used to describe a geometric quadrilateral shape, has two contradictory meanings:
> * (outside the US and Canada) – a quadrilateral with at least one pair of parallel sides, known in the US as a trapezoid.
> * (in the US and Canada) – a quadrilateral with no parallel sides ([the] shape [is] known elsewhere as a general irregular quadrilateral).

<sup>†</sup>: [Wikipedia](https://en.wikipedia.org/wiki/Trapezium)

**Comment by goyney** [comment]
I don't believe this is a language conflict. They're looking for "perspective transform and shearing," which they suggested to be a parallelogram and a trapezoid, which is actually accurate. A skew icon is typically a parallelogram while a trapezoid is used to signify perspective.

I think these solve their use case and I actually can't believe we didn't have anything already, considering we have `format-rotate-90`.

![image](https://user-images.githubusercontent.com/1015040/48750057-7554e380-ec4b-11e8-9c56-90c960c0322c.png)

---

![image](https://user-images.githubusercontent.com/1015040/48750074-8140a580-ec4b-11e8-8631-555a4a4ad60d.png)![image](https://user-images.githubusercontent.com/1015040/48750089-8bfb3a80-ec4b-11e8-8ade-c8c89e771015.png)

[format.zip](https://github.com/Templarian/MaterialDesign/files/2597969/format.zip)

**Comment by goyney** [comment]
@matthijsdewit111 Please chime in if you can to verify these new additions would solve your use case.

**Comment by goyney** [comment]
Sidenote: `vector-square` (which happens to also be the MDI logo) should be aliased `format-free-transform`.

**Comment by matthijsdewit111** [comment]
I have no use for them anymore, but for what I was doing 3 years ago these would've been good icons, they are exectly what I meant.

**Comment by goyney** [comment]
Awesome, thanks @matthijsdewit111. I'm sorry you still don't have a use for them anymore, but we'll still get them added. Thank you!

**Comment by Templarian** [comment]
[![perspective-more](https://materialdesignicons.com/icon/perspective-more)](https://materialdesignicons.com/icon/perspective-more) [![perspective-less](https://materialdesignicons.com/icon/perspective-less)](https://materialdesignicons.com/icon/perspective-less) [![skew-more](https://materialdesignicons.com/icon/skew-more)](https://materialdesignicons.com/icon/skew-more) [![skew-less](https://materialdesignicons.com/icon/skew-less)](https://materialdesignicons.com/icon/skew-less)
