### ISSUE TITLE
video-wireless-outline

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#4000]
video-outline but with something like camera-wireless-outline

**Comment by goyney** [comment]
**Variant 1:**
![image](https://user-images.githubusercontent.com/1015040/53850077-11e78b00-3f88-11e9-8d90-d1c8615cbcc5.png)![image](https://user-images.githubusercontent.com/1015040/53850091-190e9900-3f88-11e9-882c-4521825fb891.png)

**Variant 2:**
![image](https://user-images.githubusercontent.com/1015040/53850118-29bf0f00-3f88-11e9-81ca-63dcc14a74cd.png)![image](https://user-images.githubusercontent.com/1015040/53850125-32174a00-3f88-11e9-8b29-a5ff3de142e8.png)

[video-wireless.zip](https://github.com/Templarian/MaterialDesign/files/2933940/video-wireless.zip)

**Comment by PeterShaggyNoble** [comment]
Variant 2 gets my vote.

**Comment by MrGrigri** [comment]
Yeah, I agree with @PeterShaggyNoble. The first one, IMO, signifies casting, instead of a generic wireless.

**Comment by Templarian** [comment]
Agreed. Added both. 😃
