### ISSUE TITLE
button-gesture-tap-outline

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#4002]
rectangle-outline with gesture-tap overlayed. Not sure on the name. Basically I just need an icon that indicates to the user it's an interactive button.

**Comment by goyney** [comment]
I think that would be an overly-specific (and crowded icon), especially at native resolution. I feel that `gesture-tap`, used in the proper context, should be more than enough to indicate something is tappable.

If you are using React, consider using [`@mdi/react`](https://www.npmjs.com/package/@mdi/react), as you can use the `<Stack>` component to stack icons on top of each other.

**Comment by goyney** [comment]
Going to close this one out as its too niche. Thanks for the suggestion!
