### ISSUE TITLE
format-font variant with T instead of A.

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#4003]
My coworkers prefer T instead of A. I've been told this is a Google convention to use A?

**Comment by goyney** [comment]
I vote to reject this variation. All our other format icons use an `A` and I don't think we need two versions of all them with a `T` as well. Additionally, `T` is used for `format-title`, which makes sense.

**Comment by PeterShaggyNoble** [comment]
Agreed.
