### ISSUE TITLE
Termometer

### ISSUE THREAD

**Issue by arcarruda** [Templarian/MaterialDesign#4004]
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 71.46 180.63"><title>Termometer</title><g id="Layer_2" data-name="Layer 2"><g id="Termometer"><path d="M59.18,118.5a8.43,8.43,0,0,1-3.29-7.17C56.05,96.18,56,81,56,65.88h0c0-15.49.14-31-.05-46.45C55.76,10.5,49.32,2.52,41.33.65c-10-2.34-19.23,1.74-23.66,10.43-1.8,3.54-2.13,7.28-2.13,11.14,0,29.47,0,58.94.08,88.41,0,3.41-.8,5.72-3.51,8.07a34.84,34.84,0,0,0-7.78,43.18C13.2,177.81,28,183.39,45,179.37c13.59-3.21,22.23-12.58,25.37-26.17S69.69,127.79,59.18,118.5Zm2.74,34.73a27.39,27.39,0,0,1-52.25.24A26.68,26.68,0,0,1,20.3,122.72c2.76-1.85,3.52-3.75,3.51-6.87q-.15-47.25,0-94.5c0-7.26,4.09-12.32,10.37-13.13,7.43-1,13.55,4.47,13.6,12.38.11,16.17,0,32.34,0,48.5,0,15.67.07,31.33-.06,47,0,2.94.71,4.74,3.31,6.47A26.68,26.68,0,0,1,61.92,153.23Z"/><path d="M45.36,130.32c-3-1.7-3.55-3.64-3.54-6.7.12-19.46,0-38.93.13-58.39,0-3.06-.77-4.31-3.88-3.83a11.6,11.6,0,0,1-3.48,0c-3.53-.56-4.45.87-4.36,4.33.24,9.65.08,19.3.08,29s-.11,19.3.07,28.94c.05,3.1-.64,5-3.6,6.67A17.26,17.26,0,0,0,19,150.13,17.87,17.87,0,0,0,36.07,163a17.54,17.54,0,0,0,17-12.89A16.81,16.81,0,0,0,45.36,130.32Z"/></g></g></svg>

**Comment by goyney** [comment]
Do you mean `thermometer`?

[![thermometer](https://materialdesignicons.com/icon/thermometer)](https://materialdesignicons.com/icon/thermometer)

**Comment by arcarruda** [comment]
Oh my... So sorry about that.
Thank you very much.
