### ISSUE TITLE
RacingShell

### ISSUE THREAD

**Issue by Yuanruili** [Templarian/MaterialDesign#4005]
Made an icon for the sport of racing shell. Its motion is more dynamic than the 'rowing' icon. 
Could be used in a more specific scene. 
[RacingShell.zip](https://github.com/Templarian/MaterialDesign/files/2933469/RacingShell.zip)

**Comment by goyney** [comment]
@Yuanruili When creating icons, please combine everything down to a single path. Then use the [Preview Generator](http://dev.materialdesignicons.com/contribute/github) to create a preview to post on your contribution issue. Thank you!

![image](https://user-images.githubusercontent.com/1015040/53848618-05acff00-3f83-11e9-80f4-dace75759010.png)

**Comment by Yuanruili** [comment]
@goyney Thank you for telling me!~

**Comment by PeterShaggyNoble** [comment]
Personally, I find this a bit too specific and think it would be covered, with the correct context, by the existing `rowing` icon. However, a `rowing-variant` that includes a boat might also be useful to have.

**Comment by goyney** [comment]
Agree with @PeterShaggyNoble, `rowing` already covers this.
[![rowing](https://materialdesignicons.com/icon/rowing)](https://materialdesignicons.com/icon/rowing)
