### ISSUE TITLE
car-off

### ISSUE THREAD

**Issue by n-keist** [Templarian/MaterialDesign#4006]
A crossed out car icon
[for example](https://www.iconfinder.com/icons/1176102/ban_no_no_car_no_transport_no_vehicle_prohibited_icon)

**Comment by MrGrigri** [comment]
Like this?

![car-off](https://user-images.githubusercontent.com/4528551/53999724-c0fba200-4101-11e9-92a5-fbb169078f4d.png)

---

#### Files

[car-off.zip](https://github.com/Templarian/MaterialDesign/files/2943957/car-off.zip)

**Comment by n-keist** [comment]
Yeah, seems nice.

**Comment by Templarian** [comment]
[![car-off](https://materialdesignicons.com/icon/car-off)](https://materialdesignicons.com/icon/car-off)
