### ISSUE TITLE
message-plus-outline

### ISSUE THREAD

**Issue by localpcguy** [Templarian/MaterialDesign#4007]
Like the Message-Plus icon, but in outline form

![image](https://user-images.githubusercontent.com/593240/53887406-337c5d00-3ff0-11e9-874c-bbcc2bc6bc84.png)

**Comment by MrGrigri** [comment]
@localpcguy, we need the SVG for this to be considered a contribution. Could you please Zip it up and put it in the issue. Thanks.

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/59697026-fbb1b380-91a1-11e9-865f-e031d7f350c9.png)

[message-plus-outline.svg](https://github.com/terreng/samples/blob/master/message-plus-outline.svg)

**Comment by goyney** [comment]
[![message-plus-outline](https://materialdesignicons.com/icon/message-plus-outline)](https://materialdesignicons.com/icon/message-plus-outline)
