### ISSUE TITLE
mdi-format-list-numbered in the sheatsheet isn't correct. It should be mdi-format-list-numbers

### ISSUE THREAD

**Issue by RALGIE** [Templarian/MaterialDesign#4008]
The icon mdi-format-list-numbered in the sheatsheet isn't correct. It should be mdi-format-list-numbers

**Comment by Templarian** [comment]
@RALGIE As in the naming is weird? I think we named it that way because `-bulleted` has an `ed` at the end.

**Comment by goyney** [comment]
Unless I'm missing something, our icon is named[`format-list-numbered` ](https://materialdesignicons.com/icon/format-list-numbered) on the site and is correctly named the same in the sheet.

**Comment by MrGrigri** [comment]
Closing this issue as we intentionally changed the name from `format-list-numbers` to `format-list-numbered` on 25 December 2018 with issue #3733.
