### ISSUE TITLE
microbit logo

### ISSUE THREAD

**Issue by r0the** [Templarian/MaterialDesign#4009]
The [micro:bit](https://microbit.org/) logo. An SVG can be found here:

https://microbit.org/images/globalchallenge/microbit-logo-stripped.svg

Like this without the text:

![](https://user-images.githubusercontent.com/4189262/45967806-fcf4ec00-c026-11e8-90a7-be2ecac881d5.png)

**Comment by Yuanruili** [comment]
First time making a brand icon. Is it must fit the original logo shape, or I can do some adjustments, make it pixel perfect?
![image](https://user-images.githubusercontent.com/12135487/53960950-cd730100-40e7-11e9-9475-544cb65ed241.png)
[Microbit.zip](https://github.com/Templarian/MaterialDesign/files/2941480/Microbit.zip)

**Comment by goyney** [comment]
We are really only adding brand icons for bigger social media companies at this point. This brand doesn't really fit into that scope and seems too niche for the product, so we're going to reject this one for now.

@Yuanruili When doing Brand logos, you must follow that specific brand's guidelines. As a general rule, you wouldn't modify them to be pixel perfect or increase strokes or anything of that nature. In this case, the [Micro:bit guideline](https://microbit.org/community/) shows two examples of logo use, but does not explicitly say that the icon portion of the logo can be used without the text. If we were to actually be adding this icon, we would have needed to reach out to get permission to use the icon by itself.

**Comment by goyney** [comment]
@r0the You may consider requesting this brand to be added to https://simpleicons.org/, where it would be more in scope.

**Comment by Yuanruili** [comment]
@goyney Thank you for telling me :D

**Comment by r0the** [comment]
@goyney I understand, thank you for your explanation and for pointing out simpleicons.
