### ISSUE TITLE
keyboard-variant

### ISSUE THREAD

**Issue by mushahidhassan** [Templarian/MaterialDesign#401]
1) A keyboard icon like this one http://imgur.com/BAILbU5 its hardly visible due to the black background check it out on white background or click on the image it will open in full screen with white background. 
2) an icon that symbolize a dashboard or an admin panel in some way. I think something like a speedometer or something

- [ ] keyboard-variant

**Comment by Templarian** [comment]
1. Keyboard variant to http://materialdesignicons.com/icon/keyboard with just the keys.
2. I would suggest the standard dashboard icon http://materialdesignicons.com/icon/view-dashboard
A speedometer already exists also http://materialdesignicons.com/icon/speedometer

**Comment by mushahidhassan** [comment]
In my opinion, i think the keyboard icon link that i provided looks better
then http://materialdesignicons.com/icon/keyboard.  It would be really
great if you can add them to http://materialdesignicons.com/. and thanks
for the view-dashboard

**Comment by Templarian** [comment]
It will be added as a variant of the Stock Google keyboard icon they provide. Certain styles of icons work better in certain interfaces. :smile:

**Comment by mushahidhassan** [comment]
Thanks Austin, you guys are doing a great job keep it up. If there is
anything that i can do to somehow promote your cause then please do let me
know. I'm really thankful for your contributions.
P.S in future i'll keep suggesting some icons ideas :)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/keyboard-variant
