### ISSUE TITLE
Squat

### ISSUE THREAD

**Issue by Yuanruili** [Templarian/MaterialDesign#4011]
Made an icon for squat. 
Its position of feet and head are just for visual balance. Don't do it in a real squat exercise ;P
[Squat.zip](https://github.com/Templarian/MaterialDesign/files/2941306/Squat.zip)
![image](https://user-images.githubusercontent.com/12135487/53958557-9ef22780-40e1-11e9-8b46-f9373a726c9d.png)

**Comment by goyney** [comment]
I'm not sure this really depicts a "squat". Additionally, this seems to break a few of the [Material guidelines](https://material.io/design/iconography/system-icons.html#design-principles) for icon design.

Take a look at some of our other "sports" related icons, like `karate`, for the style I think we would expect for "stick figure" type icons.

[![karate](https://materialdesignicons.com/icon/karate)](https://materialdesignicons.com/icon/karate)

**Comment by Yuanruili** [comment]
Sorry I didn't aware there is a style for sports icons.

**Comment by Yuanruili** [comment]
@goyney I found the 'rowing' icon shows another style, rounded body and curved arm, but not the 'stick figure' -_- 
![image](https://user-images.githubusercontent.com/12135487/53988792-9f5fe200-4124-11e9-94a3-8c8b6f01b721.png)
I feel the stick figure is good at showing stretched limbs, but the curled body might be a different case.

**Comment by goyney** [comment]
Oh, the big, hallowed out circle isn't supposed to be the head? Yeah, this icon is even way less recognizable than I thought. I don't think we can add what you've suggested in its current form.

**Comment by Yuanruili** [comment]
Yep that's not a head 🤣 It's a barbell. 
Here is a picture of the (weighted) squat. I don't have a better idea now. Hope someone could help out. 
![image](https://user-images.githubusercontent.com/12135487/53991322-9d991d00-412a-11e9-9423-44c3051721ad.png)

**Comment by goyney** [comment]
I think this is overly specific and that `dumbbell` could potentially be used here:
[![dumbbell](https://materialdesignicons.com/icon/dumbbell)](https://materialdesignicons.com/icon/dumbbell)

**Comment by PeterShaggyNoble** [comment]
If this *is* going to work then it might be as a front view instead of a side view.

**Comment by goyney** [comment]
Going to close this since the `Consider Closing` tag was added a week ago. If you do decide to take a stab at a front view, feel free to post it and we'll consider it for addition. Thank you for your suggestion!
