### ISSUE TITLE
Weightlift

### ISSUE THREAD

**Issue by Yuanruili** [Templarian/MaterialDesign#4012]
Olympic weightlift (clean-and-jerk)
![image](https://user-images.githubusercontent.com/12135487/53959903-3147fa80-40e5-11e9-864b-1b30fd108068.png)
[Clean-and-jerk.zip](https://github.com/Templarian/MaterialDesign/files/2941402/Clean-and-jerk.zip)

**Comment by goyney** [comment]
See my comment on #4011.

**Comment by Yuanruili** [comment]
Ok got it

**Comment by goyney** [comment]
Closing as a duplicate of #4011.
