### ISSUE TITLE
Google's rounded triangle warning icon

### ISSUE THREAD

**Issue by Milleus** [Templarian/MaterialDesign#4013]
hello!

would like to request for a rounded triangle warning icon,
https://material.io/tools/icons/?search=warning&icon=warning&style=round

**Comment by PeterShaggyNoble** [comment]
Thanks for the request, @Milleus. Currently we're focusing our efforts on the filled & outlined variants. The rounded and sharp ones are still under discussion so we won't be adding them for a good while, if at all. We're tracking all requests for them with the `Future Variant` label.
