### ISSUE TITLE
Extension for vscode

### ISSUE THREAD

**Issue by lukas-tr** [Templarian/MaterialDesign#4016]
Hello, 

I made an extension for vscode that allows auto completing, searching and previewing Material Design Icons.

https://marketplace.visualstudio.com/items?itemName=lukas-tr.materialdesignicons-intellisense

**Comment by goyney** [comment]
This is pretty cool.

Is this using the webfont version of the library? I think there is value there for those using that version of MDI, but we are trying to dissuade people from using that because of the sheer size of it, especially as we add more icons.

Any possibility to add this Intellisense to things such as [`@mdi/js`](https://www.npmjs.com/package/@mdi/js) and [`@mdi/svg`](https://www.npmjs.com/package/@mdi/svg), in addition to what you already have? These are the packages we really would prefer people be using. By the mere nature of these being NPM packages, VSCode does an okay job with Intellisense on its own, but I really like your icon preview pane.

![Screen Shot 2019-03-10 at 1 48 26 PM](https://user-images.githubusercontent.com/1015040/54089060-3900dc80-433b-11e9-8bc3-d34092b91357.png)

**Comment by lukas-tr** [comment]
The `mdi mdi-` prefix can be removed by setting `materialdesigniconsIntellisense.insertPrefix` to an empty string in settings.

I am providing completion for the webfont version as I have been using https://vuetifyjs.com/en/framework/icons#install-material-design-icons a lot recently, which uses the webfont.

**Comment by JamesCoyle** [comment]
Definitely needs to support `@mdi/js` IMO.

**Comment by Templarian** [comment]
This is pretty awesome! Nice work @lukas-tr.

Looks like it would have to tie into the TypeScript / JavaScript autocomplete for `@mdi/js` exported modules. Not sure if there is a way to `async` wrap logic into that autocomplete list to add a similar doc/preview.

Seeing as it's open source if I have time I can look into this.

**Comment by lukas-tr** [comment]
> Definitely needs to support `@mdi/js` IMO. Surely it would just be the same as you already have but with camelCase rather than kebab-case? If the user types `mdi` show the `@mdi/js` syntax, if they type `mdi-` show the `@mdi/font` syntax.

I added support for camel case names:

![usage-5](https://user-images.githubusercontent.com/36337818/54146508-64b1be80-4430-11e9-8c11-fad5d194c502.gif)



> This is pretty awesome! Nice work @lukas-tr.
> 
> Looks like it would have to tie into the TypeScript / JavaScript autocomplete for `@mdi/js` exported modules. Not sure if there is a way to `async` wrap logic into that autocomplete list to add a similar doc/preview.
> 
> Seeing as it's open source if I have time I can look into this.

I have no idea how to do this. The entries with previews currently just sit underneath the TypeScript ones. 

![ts](https://user-images.githubusercontent.com/36337818/54146870-31236400-4431-11e9-8a78-e53948b37671.gif)

**Comment by goyney** [comment]
> I added support for camel case names:
> 
> ![usage-5](https://user-images.githubusercontent.com/36337818/54146508-64b1be80-4430-11e9-8c11-fad5d194c502.gif)

Now that's what I'm talking about! 👍

**Comment by Templarian** [comment]
That was fast! Tweeted about it earlier today by the way:

https://twitter.com/templarian/status/1105129674798190592

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/getting-started/visual-studio-code First pass adding a links to the docs.

Added buttons to a few of the doc pages also. Hopefully that gets you some more downloads.

- [React](https://dev.materialdesignicons.com/getting-started/react)
- [Webfont](https://dev.materialdesignicons.com/getting-started/webfont)

Will spend some time later adding some more content and links.

**Comment by lukas-tr** [comment]
Thanks, I appreciate it.

I'll also look into supporting Home Assistant syntax soon.

**Comment by lukas-tr** [comment]
The extension now also supports Home Assistant icon names.

![usage-6](https://user-images.githubusercontent.com/36337818/54236395-baab6280-4513-11e9-9a66-12a387596f73.gif)

**Comment by JamesCoyle** [comment]
Gonna close this out as it isn't really an issue. Thanks for bringing this to our  attention as it is super useful. :D
