### ISSUE TITLE
keyboard-space

### ISSUE THREAD

**Issue by luiey** [Templarian/MaterialDesign#4017]
As far I'm scrolling through the full icon pack, can I request for space bar icon? It's either open box/tray as  link in [Open Tray](https://www.materialui.co/icon/space-bar)

**Comment by MrGrigri** [comment]
I'm not sure if we should round the bottom corners or not. Thoughts?

![keyboard-space](https://user-images.githubusercontent.com/4528551/54137661-a7997500-43e3-11e9-8470-4b57aa4a6673.png) ![keyboard-space-rounded](https://user-images.githubusercontent.com/4528551/54137697-b849eb00-43e3-11e9-9393-8d7baaecdc64.png)

---
#### Files
[keyboard-space.zip](https://github.com/Templarian/MaterialDesign/files/2953024/keyboard-space.zip)

**Comment by goyney** [comment]
I think we should follow the spec and use the rounded corners unless someone has a compelling reason not to. 😄

**Comment by CoDEmanX** [comment]
The HTML entity `&blank;` to represent a space is the Unicode code point U+2423 ("open box"):

https://codepoints.net/U+2423?lang=en

It does not have rounding. I'm in favor of adding the sharp version and add the rounded version at some later point together with other rounded icon variants.

**Comment by goyney** [comment]
These aren't brand logos though, we're creating Material versions of them. Just like all the ISO car icons I added, they aren't exactly as defined in the spec, but Materialized versions of them.

**Comment by JamesCoyle** [comment]
I've only ever seen it with sharp corners. I vote for that version and save the other for the rounded set when we get to that.

**Comment by PeterShaggyNoble** [comment]
I'm torn, but leaning towards rounded.

Should it be moved down the canvas, though?

**Comment by JamesCoyle** [comment]
The old android OSKs used a square version:
![image](https://user-images.githubusercontent.com/10384436/54356543-c736d480-4653-11e9-92a9-c30b60a4b882.png)

I believe we should just emulate the U+2423 ("open box") character as that is most commonly used after the interpunct.

**Comment by goyney** [comment]
Just as we've developed an alphabet to follow the spec, as well as several punctuation marks that follow the spec, we should continue to follow the spec here. Added the rounded version and moved it down on the canvas.

[![keyboard-space](https://materialdesignicons.com/icon/keyboard-space)](https://materialdesignicons.com/icon/keyboard-space)

**Comment by JapanYoshi** [comment]
NBSP icon when? :3
