### ISSUE TITLE
water-well

### ISSUE THREAD

**Issue by Melkor82** [Templarian/MaterialDesign#4018]
Icon for a well, something like 
![well](https://user-images.githubusercontent.com/17194596/54164029-6644ac00-445b-11e9-9a15-2d90dcb0d2bf.jpg)

**Comment by MrGrigri** [comment]
![water-well](https://user-images.githubusercontent.com/4528551/54215543-bc423f80-44ad-11e9-9ff4-975e899dbdba.png) ![water-well-outline](https://user-images.githubusercontent.com/4528551/54215577-c9f7c500-44ad-11e9-953b-ae49b88321e4.png)

---
#### Files
[well.zip](https://github.com/Templarian/MaterialDesign/files/2957706/well.zip)

**Comment by goyney** [comment]
The top of the wells look like they're off by 1dp in terms of skew.

**Comment by MrGrigri** [comment]
Updated

**Comment by goyney** [comment]
[![water-well](https://materialdesignicons.com/icon/water-well)](https://materialdesignicons.com/icon/water-well)[![water-well-outline](https://materialdesignicons.com/icon/water-well-outline)](https://materialdesignicons.com/icon/water-well-outline)
