### ISSUE TITLE
Icon request: handshake

### ISSUE THREAD

**Issue by nwalters512** [Templarian/MaterialDesign#402]
Perhaps something similar to [this](http://www.icon2s.com/wp-content/uploads/2013/07/black-white-metro-handshake-icon.png), but more material-y.

- [ ] handshake

**Comment by Templarian** [comment]
This was requested before, I'll try and think of a design. In the small size it may not be possible.

**Comment by CoDEmanX** [comment]
Same icon as requested in #330.
