### ISSUE TITLE
car-glass-front(-outline)

### ISSUE THREAD

**Issue by Leinad4Mind** [Templarian/MaterialDesign#4020]
Something like this maybe: ![Image](https://i.imgur.com/buUJYLL.jpg)

**Comment by MrGrigri** [comment]
Again, I do not believe this would be a great stand-alone icon and would need to be consumed within context.

![car-glass-front](https://user-images.githubusercontent.com/4528551/54214175-5a80d600-44ab-11e9-9ccc-0c489ecdd2ba.png) ![car-glass-front-outline](https://user-images.githubusercontent.com/4528551/54214206-67052e80-44ab-11e9-8777-0bce3ec06d26.png)

---
####Files
[car-glass.zip](https://github.com/Templarian/MaterialDesign/files/2957624/car-glass.zip)

**Comment by goyney** [comment]
And it depends on your perspective. That's an external view.

While this is an internal view (if we removed the heating element):
[![car-defrost-front](https://materialdesignicons.com/icon/car-defrost-front)](https://materialdesignicons.com/icon/car-defrost-front)

**Comment by goyney** [comment]
[![car-windshield](https://materialdesignicons.com/icon/car-windshield)](https://materialdesignicons.com/icon/car-windshield)[![car-windshield-outline](https://materialdesignicons.com/icon/car-windshield-outline)](https://materialdesignicons.com/icon/car-windshield-outline)
