### ISSUE TITLE
Charging Station

### ISSUE THREAD

**Issue by Leinad4Mind** [Templarian/MaterialDesign#4021]
Something like this: ![image](https://i.imgur.com/mGWb754.png)

**Comment by goyney** [comment]
This icon already exists:
[![ev-station](https://materialdesignicons.com/icon/ev-station)](https://materialdesignicons.com/icon/ev-station)

**Comment by CoDEmanX** [comment]
Looks like we could use an alias?

**Comment by goyney** [comment]
Yep, good call. Added.
