### ISSUE TITLE
Tire Flat

### ISSUE THREAD

**Issue by Leinad4Mind** [Templarian/MaterialDesign#4022]
Would be great to have a tire flat too: ![image](https://i.imgur.com/Q0nvtgF.png)

**Comment by goyney** [comment]
This icon already exists:
[![car-tire-alert](https://materialdesignicons.com/icon/car-tire-alert)]
(https://materialdesignicons.com/icon/car-tire-alert)

**Comment by Leinad4Mind** [comment]
That's a tire? Doesnt look like at all. The example I provided its completely different

**Comment by goyney** [comment]
It is the ISO standard icon: http://auto.gosstandart.info/data/documents/ISO-2575.pdf (Page 5, Row K).

We also already have https://github.com/Templarian/MaterialDesign/issues/1308 for a generic tire, though all examples there are either a perspective or more of a "wheel", than a tire.
