### ISSUE TITLE
Terraform

### ISSUE THREAD

**Issue by fishpen0** [Templarian/MaterialDesign#4023]
I would like to use the terraform "Square Logo" Icon in this font (possibly all hashicorp logos)

Logo visible here: https://www.terraform.io/logos.html
Logo assets available here: https://www.hashicorp.com/brand#terraform

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/54468724-e06f7c00-474c-11e9-80fa-b23b01f88784.png)
[terraform-logo.svg](https://github.com/terreng/samples/blob/master/terraform-logo.svg)

**Comment by goyney** [comment]
Considering this is a development tool, it meets the criteria to still be added, [despite our recent announcement about brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by goyney** [comment]
[![terraform](https://materialdesignicons.com/icon/terraform)](https://materialdesignicons.com/icon/terraform)
