### ISSUE TITLE
Updated reddit icon

### ISSUE THREAD

**Issue by hulkhaugen** [Templarian/MaterialDesign#4025]
I made a new reddit icon as the current one seems a bit off:

![image](https://user-images.githubusercontent.com/1409758/54244804-88f3c500-452e-11e9-9d32-854d65b3b751.png)

[reddit.zip](https://github.com/Templarian/MaterialDesign/files/2959218/reddit.zip)

**Comment by MrGrigri** [comment]
For comparison

![image](https://user-images.githubusercontent.com/4528551/54302164-f67f1000-4585-11e9-8e56-63943a928c74.png)

**Comment by Templarian** [comment]
Makes sense. Updated!
