### ISSUE TITLE
Google Wi-Fi

### ISSUE THREAD

**Issue by MiPiGamer** [Templarian/MaterialDesign#4026]
I would like to use the Google Wi-Fi Logo.

Logo from App Store: https://bit.ly/2u4RWmY

**Comment by goyney** [comment]
You'll need to use `wifi-strength-outline`. There is no way that icon would ever work because of the multi-colored nature of it.

[![wifi-strength-outline](https://materialdesignicons.com/icon/wifi-strength-outline)](https://materialdesignicons.com/icon/wifi-strength-outline)
