### ISSUE TITLE
blind-open

### ISSUE THREAD

**Issue by gibman** [Templarian/MaterialDesign#4027]
hi..

We already have the MDI icon representing a closed window blind.
It would be nice to also have another icon representing an opened blind.

I have a motorized window blind that I need some icons for.

**Comment by idevo89** [comment]
What about a shorter version of `blinds`

<a href="https://github.com/Templarian/MaterialDesign/files/3064171/blinds-open.zip"><img src="https://user-images.githubusercontent.com/48392636/55885463-46172280-5baa-11e9-97f7-8850dcd0299a.png" alt="blinds-open.zip" style="max-width:100%;"></a>

**Comment by gibman** [comment]
Yes.. that would do just fine :)

**Comment by goyney** [comment]
[![blinds-open](https://materialdesignicons.com/icon/blinds-open)](https://materialdesignicons.com/icon/blinds-open)
