### ISSUE TITLE
Google Podcasts

### ISSUE THREAD

**Issue by erchinoK** [Templarian/MaterialDesign#4028]
Google Podcasts logo, please.

Thanks :)

**Comment by PeterShaggyNoble** [comment]
Do you mean this, existing icon?

[![podcast](https://user-images.githubusercontent.com/15157491/54320028-8901cc80-45e3-11e9-98a7-93206943217d.png)](https://materialdesignicons.com/icon/podcast)

**Comment by erchinoK** [comment]
Oh no, sorry for not giving more details. Google has a new app for Podcasts and the logo is 
![unnamed](https://user-images.githubusercontent.com/1665613/54320362-a7b49300-45e4-11e9-9d33-1dd88e892ad8.png)

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/54650604-98ae6480-4a6c-11e9-9a0b-62e28fa279d9.png)
[google-podcasts.svg](https://github.com/terreng/samples/blob/master/google-podcasts.svg)

**Comment by Templarian** [comment]
[![google-podcast](https://materialdesignicons.com/icon/google-podcast)](https://materialdesignicons.com/icon/google-podcast)
