### ISSUE TITLE
currency-npr

### ISSUE THREAD

**Issue by khadkamhn** [Templarian/MaterialDesign#4030]
I don't see currency-npr. It would be great if you can add this currency symbol.
Symbol is रू or Rs
Picture are attached below:
![Rs-symbol](https://user-images.githubusercontent.com/5512363/54346726-ad09f000-466d-11e9-9703-4d956d2d86ba.JPG)
![Rs-symbol-2](https://user-images.githubusercontent.com/5512363/54346727-ad09f000-466d-11e9-9fb0-02d6f5c370d1.png)

**Comment by JamesCoyle** [comment]
I think we should add this as the more generic rupee symbol.

**Comment by khadkamhn** [comment]
The generic symbol can be ₨. But, symbol are different by country.

Code | Country | Symbol
---- | ------- | ------ |
INR | India | ₹
NRP | Nepal | रू
PKR | Pakistan | ₨

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/134227656-82c6ae89-0448-4191-abe5-2eb2623b629a.png)
[currency-rupee.svg.zip](https://github.com/Templarian/MaterialDesign/files/7205378/currency-rupee.svg.zip)

**Comment by goyney** [comment]
[![currency-rupee](https://materialdesignicons.com/icon/currency-rupee)](https://materialdesignicons.com/icon/currency-rupee)
