### ISSUE TITLE
odometer icon

### ISSUE THREAD

**Issue by redge13** [Templarian/MaterialDesign#4031]
Can you add a new icon on the Material Design Icons an odometer (car)
I give you two different idea.
thanks a lot
Régis

Idea 001

[odometer.pdf](https://github.com/Templarian/MaterialDesign/files/2965738/odometer.pdf)

<img width="24" alt="Artboard 1@2x-8" src="https://user-images.githubusercontent.com/48550710/54347239-e7ac6200-4646-11e9-838b-94cbeb5eb9c1.png">

Idea 002

[odometer 002.pdf](https://github.com/Templarian/MaterialDesign/files/2965752/odometer.002.pdf)
<img width="24" alt="odometer 002" src="https://user-images.githubusercontent.com/48550710/54347454-55588e00-4647-11e9-8788-5f29d51a8abb.png">

**Comment by JamesCoyle** [comment]
Might be a tough one to fit into the space restrictions.

**Comment by redge13** [comment]
Maybe the version 002 juste with the 2 boxes ;-)

**Comment by PeterShaggyNoble** [comment]
Would `counter` suit your needs?

[![counter](https://user-images.githubusercontent.com/15157491/54353772-ca7a9200-464c-11e9-8987-8e86d56f5c58.png)](https://materialdesignicons.com/icon/counter)

**Comment by redge13** [comment]
Ok I’m going to present this design to the team 
To see if it’s good for them ;-)
Thanks a lot

Régis

**Comment by goyney** [comment]
I've aliased `counter` as `odometer`. My vote is that this issue is resolved and can now be closed.

**Comment by JamesCoyle** [comment]
Closing this out as I don't feel we can do much better with the space restrictions.
