### ISSUE TITLE
clipboard-text-outline not properly aligned

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4032]
@MrGrigri

![](https://user-images.githubusercontent.com/15157491/54364436-d1ad9a00-4664-11e9-90fc-52ab1a076b7c.png)

**Comment by MrGrigri** [comment]
Nice catch. 

[![image](https://user-images.githubusercontent.com/4528551/54370658-9d72b300-463d-11e9-945a-c7060a98af01.png)](https://github.com/Templarian/MaterialDesign/files/2967230/clipboard-text-outline.zip)

**Comment by Templarian** [comment]
Updated, but going to keep it with two lines. 3 looks a bit crushed.
