### ISSUE TITLE
folder-home

### ISSUE THREAD

**Issue by MitchBerninger** [Templarian/MaterialDesign#4033]
For a project, I needed an icon to represent a home directory. Came up with this concept. Let me know if any changes are needed.

![image](https://user-images.githubusercontent.com/10249199/54366396-fa269b80-4646-11e9-8236-0a3310457b25.png)

![image](https://user-images.githubusercontent.com/10249199/54366514-24785900-4647-11e9-81e9-30ed2d82da61.png)

**Comment by goyney** [comment]
Thanks for the contribution! 

The first thing I noticed was that the home is not aligned to the grid. For example, the sides of the house are slight over 2dp in width; it probably makes sense to shrink them down. With something very geometric, like the house, it is very easy to make sure every anchor is directly on the grid. Doing this makes the icon appear "sharper" at native resolution.

I'd also consider moving the house over slightly so there is at least 1 full dp of space between it and the edge of the folder.

Can you make those revisions? Then, make sure to also upload your source SVGs in a ZIP file so we can consider them for inclusion!

**Comment by MitchBerninger** [comment]
@goyney Thanks for the input! I have made those changes in the version below. Originally I began with Google's home icon and tried resizing it. However I couldn't get each point on the grid without adjusting the proportions slightly.

![image](https://user-images.githubusercontent.com/10249199/54373991-960ad400-4654-11e9-8ebb-5cfcbbacb134.png)

![image](https://user-images.githubusercontent.com/10249199/54374047-afac1b80-4654-11e9-81a4-855f4dbc7f8c.png)

[folder-home.zip](https://github.com/Templarian/MaterialDesign/files/2967432/folder-home.zip)

**Comment by MrGrigri** [comment]
What would it look like without the door? I believe at 1x it is more complex than needed.

**Comment by MitchBerninger** [comment]
Here are what the icon would look like without the door. Unfortunately, I feel it looks too much like an arrow and could be viewed as 'going up a folder level'.

![image](https://user-images.githubusercontent.com/10249199/54381057-3536c800-4663-11e9-8c19-eb4bf27a2606.png)
![image](https://user-images.githubusercontent.com/10249199/54381113-54355a00-4663-11e9-9104-ff144b66c753.png)

**Comment by MrGrigri** [comment]
Yeah, scratch that

**Comment by goyney** [comment]
[![folder-home](https://materialdesignicons.com/icon/folder-home)](https://materialdesignicons.com/icon/folder-home)[![folder-home-outline](https://materialdesignicons.com/icon/folder-home-outline)](https://materialdesignicons.com/icon/folder-home-outline)
