### ISSUE TITLE
el-car icon

### ISSUE THREAD

**Issue by sonybansi** [Templarian/MaterialDesign#4035]
![images](https://user-images.githubusercontent.com/28208396/54395440-16aaee00-46b0-11e9-9a7b-e1404a3cfbbb.png)

**Comment by sonybansi** [comment]
Please add el-car icon.

**Comment by goyney** [comment]
Duplicate of https://github.com/Templarian/MaterialDesign/issues/4021.

It already exists as `ev-station`. Please search before requesting icons. Thank you!
