### ISSUE TITLE
human_greeting_outlined

### ISSUE THREAD

**Issue by gabrielvaz** [Templarian/MaterialDesign#4036]
Make the icon of human greeting in the outline version

**Comment by goyney** [comment]
This icon doesn't really work as an outline.
![image](https://user-images.githubusercontent.com/1015040/54447198-43e2b500-471f-11e9-8c68-ea4d86d52497.png)

**Comment by PeterShaggyNoble** [comment]
Agreed with @goyney. Closing this one out.
