### ISSUE TITLE
Font suddenly working worse in design software (Sketch)

### ISSUE THREAD

**Issue by willekensrobin** [Templarian/MaterialDesign#4037]
Hi 👋

I've been using the font in my Sketch for quite a some time now and haven't been having too much problems but somehow most icons I use don't work anymore. All of my projects (all made in Sketch) have weird characters in them and is a major problem at the moment. Also occurs in other software like Framer and Illustrator. Is any solution available for this? 

Sketch
![issue-sketch](https://user-images.githubusercontent.com/11174343/54433643-ad1cf500-472c-11e9-8650-999f2c353111.gif)

Framer
![issue-framer](https://user-images.githubusercontent.com/11174343/54433179-827e6c80-472b-11e9-984b-b72152f00dfe.gif)

Illustrator
![issue-illustrator](https://user-images.githubusercontent.com/11174343/54433201-8f9b5b80-472b-11e9-85db-c61bd6ac612d.gif)

**Comment by Templarian** [comment]
I'll play with trying to reproduce this shortly, but can you verify you have the latest version of the webfont installed. Delete your currently installed font first.

https://cdn.materialdesignicons.com/3.5.95/fonts/materialdesignicons-webfont.ttf?v=3.5.95

**Comment by willekensrobin** [comment]
Thank you so much, would literally save my butt because I just convinced my boss to start working with MDI. Yes that's what made it worse somehow, on both my laptops which I find weird. I now reversed to an older one I still had installed on my old laptop which works a bit better, not great but a better.

**Comment by willekensrobin** [comment]
> I'll play with trying to reproduce this shortly, but can you verify you have the latest version of the webfont installed. Delete your currently installed font first.
> 
> https://cdn.materialdesignicons.com/3.5.95/fonts/materialdesignicons-webfont.ttf?v=3.5.95

Sorry to bother you again with this one. Do you have an update on this maybe?

**Comment by CoDEmanX** [comment]
String.fromCharCode() only supports the Unicode BMP range 0x0000 .. 0xFFFF, but JavaScript offers String.fromCodePoint() since ECMAScript 6 which supports all Unicode codepoints and there is also a syntax extension for escaping them in string literals: `"\u{1f600}"` = "😀"
