### ISSUE TITLE
Car retarder icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#4038]
It would be great to have car retarder icon like :
![B17 Retarder failure](https://user-images.githubusercontent.com/45227578/54435595-261e4b80-4731-11e9-879d-bcace5e966b3.png)

Ref :  http://auto.gosstandart.info/data/documents/ISO-2575.pdf (Icons : B.14 and B.17)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/54447541-1b0eef80-4720-11e9-8b80-859792d4dd96.png)
[car-brake-retarder.svg.zip](https://github.com/Templarian/MaterialDesign/files/2972064/car-brake-retarder.svg.zip)

**Comment by goyney** [comment]
[![car-brake-retarder](https://materialdesignicons.com/icon/car-brake-retarder)](https://materialdesignicons.com/icon/car-brake-retarder)
