### ISSUE TITLE
Engine oil temperature icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#4039]
It would be great to have engine oil temperature icon like :
![F05 Engine oil temperature](https://user-images.githubusercontent.com/45227578/54439838-dd1ec500-4739-11e9-98b3-81a4324444da.png)

Ref : http://auto.gosstandart.info/data/documents/ISO-2575.pdf (Icon: F.05)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/54448753-d6388800-4722-11e9-8165-45b01bfd87ce.png)
[oil-temperature.svg.zip](https://github.com/Templarian/MaterialDesign/files/2972135/oil-temperature.svg.zip)

**Comment by goyney** [comment]
@Templarian This icon needs to be done at the same time as #4045.

**Comment by goyney** [comment]
[![oil-temperature](https://materialdesignicons.com/icon/oil-temperature)](https://materialdesignicons.com/icon/oil-temperature)
