### ISSUE TITLE
[Question] Adobe Symbols Library

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#404]
Is it planned to create an Adobe Illustrator symbols library?

**Comment by danielhickman** [comment]
PS: 404, Issue not found.

**Comment by Templarian** [comment]
Nice issue number. I'm not really familiar with how to create these. I have Adobe CC, so if you have some more information I can try and create it.

**Comment by danielhickman** [comment]
Looks like the file is a PDF file disguised as a AI file or something. It appears that you can't create symbols or symbols libraries as easy as I thought (no automation built in) I may be able to find something on automating it or I may end up doing it myself using AutoIt.

Create Symbols: https://helpx.adobe.com/illustrator/how-to/create-symbols.html
Export Libraries: https://helpx.adobe.com/illustrator/using/symbols.html#create_symbol_libraries

**Comment by danielhickman** [comment]
*Actually...* I take that back. It seems that Illustrator actions could do it just fine. I may try myself and send you either my actions or a few files.

**Comment by danielhickman** [comment]
Also... without moving anything from a complied SVG I made from the Custom section, [thumbs-up-down](http://materialdesignicons.com/icon/thumbs-up-down) looks cut off.
![image](https://cloud.githubusercontent.com/assets/5341898/7956923/4bed1b46-0998-11e5-80fa-9840fe85de4d.png)

**Comment by danielhickman** [comment]
Currently my main computer is running a combination of AutoIt scripts and Illustrator Actions. I slowed it down to one every three seconds but this library would only have the icons (symbols) alphabetized. It would be amazing if you could add a tag feature to the custom export so you can search by category and not alphabetically. Because this project has grown so much.

**Comment by danielhickman** [comment]
I have scripts (AutoIt and AI Actions) as well as the current symbols library as a `.ai` file.
https://github.com/danielhickman/MDI-Symbols

**Comment by Templarian** [comment]
Stuck in meetings all today. I'll try and look through it tonight.

**Comment by danielhickman** [comment]
Moved to https://github.com/danielhickman/MaterialDesign/tree/master/Symbols/Templarian for simplicity on updating for me.

**Comment by Templarian** [comment]
http://materialdesignicons.com/getting-started and the download modal have links to this resource.

Awesome! Sorry for never getting back, sometimes these things lapse. Thanks! :smile:

**Comment by danielhickman** [comment]
Thanks so much for putting me on the page!
