### ISSUE TITLE
Engine oil level icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#4040]
It would be great to have engine oil level icon like :
![F06 Engine oil level](https://user-images.githubusercontent.com/45227578/54440008-2c64f580-473a-11e9-9af2-5e1fbb2a830a.png)
Ref : http://auto.gosstandart.info/data/documents/ISO-2575.pdf (Icon : F.06)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/54448917-4810d180-4723-11e9-809d-a2d706f10212.png)
[oil-level.svg.zip](https://github.com/Templarian/MaterialDesign/files/2972149/oil-level.svg.zip)

**Comment by goyney** [comment]
[![oil-level](https://materialdesignicons.com/icon/oil-level)](https://materialdesignicons.com/icon/oil-level)
