### ISSUE TITLE
Engine coolant level icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#4041]
It would be great to have engine coolant level icon like :
![F15 Engine coolant level](https://user-images.githubusercontent.com/45227578/54440094-56b6b300-473a-11e9-84ef-2e20594c6ea2.png)
Ref : http://auto.gosstandart.info/data/documents/ISO-2575.pdf (Icon: F.15)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/54449326-35e36300-4724-11e9-9088-3e68283217f8.png)
[car-coolant-level.svg.zip](https://github.com/Templarian/MaterialDesign/files/2972173/car-coolant-level.svg.zip)

**Comment by goyney** [comment]
[![car-coolant-level](https://materialdesignicons.com/icon/car-coolant-level)](https://materialdesignicons.com/icon/car-coolant-level)
