### ISSUE TITLE
Turbocharger icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#4042]
It would be great to have turbo charger icon like :
![F20 Turbocharger](https://user-images.githubusercontent.com/45227578/54440151-751cae80-473a-11e9-80c4-01666f33354c.png)

Ref : http://auto.gosstandart.info/data/documents/ISO-2575.pdf (Icon : F.20)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/54450731-8ad4a880-4727-11e9-9045-ccaade3837d8.png)
[car-turbocharger.svg.zip](https://github.com/Templarian/MaterialDesign/files/2972256/car-turbocharger.svg.zip)

It's important to note that this *should not* be aliased as a supercharger. Turbochargers work off exhaust gas, thus the fan, while superchargers work off of the engine via a belt.

**Comment by isaacwritescode** [comment]
Can I use this for a project 😂
