### ISSUE TITLE
Ad blue icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#4043]
It would be great to have ad blue icon like :
![G01 Ad_Blue_jm](https://user-images.githubusercontent.com/45227578/54440225-9382aa00-473a-11e9-9132-b49e1d402b57.png)

**Comment by goyney** [comment]
This icon is going to be pretty impossible to convey meaning in a Material format. I think you'd be better off using `gas-station` and recoloring the icon, or using the wording "AdBlue" next to it.

Additionally, AdBlue is _technically_ a brand, though it seems to be used very similar to other brands, such as Escalator.

I think we're going to reject this icon for now, but if you can think of another way to depict it, please post those suggestions and we'll reconsider. Thank you!
