### ISSUE TITLE
Clutch icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#4044]
It would be great to have clutch icon like :
![H13 Clutch](https://user-images.githubusercontent.com/45227578/54440352-d04ea100-473a-11e9-9bce-6fbeb93aaf28.png)
Ref : http://auto.gosstandart.info/data/documents/ISO-2575.pdf (Icon : H.13)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/54452475-a8a40c80-472b-11e9-9ed7-bb9ddd554a3e.png)
[car-clutch.svg.zip](https://github.com/Templarian/MaterialDesign/files/2972353/car-clutch.svg.zip)

**Comment by goyney** [comment]
[![car-clutch](https://materialdesignicons.com/icon/car-clutch)](https://materialdesignicons.com/icon/car-clutch)
