### ISSUE TITLE
more file icons

### ISSUE THREAD

**Issue by hanakin** [Templarian/MaterialDesign#4046]
I have made a couple of variations on the file-outline icon that might be great for others to user

###### Active file
<img width="37" alt="Screen Shot 2019-03-15 at 7 22 33 PM" src="https://user-images.githubusercontent.com/73081/54471101-e74fbc00-4757-11e9-942d-06a19fa181b7.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M15.414 2H6c-1.103 0-2 .898-2 2v16c0 1.103.897 2 2 2h12c1.103 0 2-.897 2-2V6.586L15.414 2zm2.587 18H6V4h8v4h4l.001 12zm-4.695-4.811h2.944v-1.167h-2.223l-1.135-2.27-.931 2.793-1.635-4.25-1.397 3.727H7.75v1.167h1.988l.602-1.608L12.04 18l1.068-3.207.198.397z" />
</svg>
```

###### Hidden File
<img width="34" alt="Screen Shot 2019-03-15 at 7 22 12 PM" src="https://user-images.githubusercontent.com/73081/54471104-ed459d00-4757-11e9-9bed-4f55891c687d.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M15.414 2H6c-1.103 0-2 .898-2 2v16c0 1.103.897 2 2 2h12c1.103 0 2-.897 2-2V6.586L15.414 2zM10 4h4v4h4v3h2v2h-2v3h2v2h-2l.001 2H15v2h-2v-2h-3v2H8v-2H6v-2H4v-2h2v-3H4v-2h2V8H4V6h2V4h2V2h2v2z" />
</svg>
```

###### Important File
<img width="37" alt="Screen Shot 2019-03-15 at 7 22 22 PM" src="https://user-images.githubusercontent.com/73081/54471106-f2a2e780-4757-11e9-9ec7-6e42bf328a1b.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M15.414 2H6c-1.103 0-2 .898-2 2v16c0 1.103.897 2 2 2h12c1.103 0 2-.897 2-2V6.586L15.414 2zm2.587 18H6V4h8v4h4l.001 12zM12 11l-.934 2.066L9 14l2.066.934L12 17l.942-2.066L15 14l-2.058-.934L12 11z" />
</svg>
```

###### Error File
<img width="36" alt="Screen Shot 2019-03-15 at 7 22 27 PM" src="https://user-images.githubusercontent.com/73081/54471110-f6cf0500-4757-11e9-9eae-317110b4a3c1.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" 
d="M15.414 2H6c-1.103 0-2 .898-2 2v16c0 1.103.897 2 2 2h12c1.103 0 2-.897 2-2V6.586L15.414 2zm2.587 18H6V4h8v4h4l.001 12zM11 10v5h2v-5h-2zm1 8a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
</svg>
```

some of these are fixes for inconsistencies

###### Locked File
<img width="32" alt="Screen Shot 2019-03-15 at 8 06 49 PM" src="https://user-images.githubusercontent.com/73081/54471515-444e7080-475e-11e9-8506-e34907483898.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M14 20H6V4h8v4h4v4h2V6.586L15.414 2H6c-1.103 0-2 .898-2 2v16c0 1.103.897 2 2 2h11.5H14v-2zm7.4-3.538C21.4 15.104 20.323 14 19 14s-2.4 1.104-2.4 2.462c-.332 0-.6.275-.6.615v4.308c0 .34.268.615.6.615h4.8c.332 0 .6-.276.6-.615v-4.308a.608.608 0 0 0-.6-.615zM19 15.23c.662 0 1.2.551 1.2 1.23h-2.4c0-.679.538-1.23 1.2-1.23zm1.8 5.538h-3.6v-3.077h3.6v3.077z" />
</svg>
```

###### checked-out-file
<img width="36" alt="Screen Shot 2019-03-15 at 8 07 02 PM" src="https://user-images.githubusercontent.com/73081/54471512-37318180-475e-11e9-8475-a88842fb317b.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M10 2h5.414L20 6.586V20c0 1.103-.897 2-2 2H6c-1.103 0-2-.897-2-2V10h2v10h12.001L18 8h-4V4h-4V2zM4.182 5.816L5 7.998l.818-2.183L8 4.998 5.818 4.18 5 1.998 4.182 4.18 2 4.998l2.182.817z" />
</svg>
```

###### info-file
<img width="25" alt="Screen Shot 2019-03-15 at 8 07 14 PM" src="https://user-images.githubusercontent.com/73081/54471531-84155800-475e-11e9-9ddc-d09e3b26291c.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M15.414 2L20 6.586V20c0 1.103-.897 2-2 2H6c-1.103 0-2-.897-2-2V4c0-1.102.897-2 2-2h9.414zm2.587 18L18 8h-4V4H6v16h12.001zM11 14h2v4h-2v-4zm1-1.5a1.25 1.25 0 1 1 0-2.5 1.25 1.25 0 0 1 0 2.5z" />
</svg>
```

###### burn-file
<img width="26" alt="Screen Shot 2019-03-15 at 8 07 09 PM" src="https://user-images.githubusercontent.com/73081/54471532-8aa3cf80-475e-11e9-89a6-78ed1088de97.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M15.414 2L20 6.586V20c0 1.103-.897 2-2 2H6c-1.103 0-2-.897-2-2V4c0-1.102.897-2 2-2h9.414zm2.587 18L18 8h-4V4H6v16h12.001zM12 10c3 2.667 3 3.96 3 5.333C15 16.806 13.657 18 12 18s-3-1.194-3-2.667c0-1.119.776-2.075 1.8-2.47v1.804S13 13.555 12 10z" />
</svg>
```

###### move-file
<img width="29" alt="Screen Shot 2019-03-15 at 8 07 28 PM" src="https://user-images.githubusercontent.com/73081/54471530-811a6780-475e-11e9-827e-e725d9a6ba44.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M11.664 13l-1.836-1.836 1.415-1.414 4.242 4.243-4.242 4.242-1.415-1.414L11.65 15H4v-2h7.664zM4 17h2v3h12.001L18 8h-4V4H6v7H4V4c0-1.102.897-2 2-2h9.414L20 6.586V20c0 1.103-.897 2-2 2H6c-1.103 0-2-.897-2-2v-3z" />
</svg>
```

###### favorite-file
<img width="27" alt="Screen Shot 2019-03-15 at 8 13 09 PM" src="https://user-images.githubusercontent.com/73081/54471546-e2dad180-475e-11e9-8eb2-f3819d679598.png">

```html
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M15.414 2L20 6.586V20c0 1.103-.897 2-2 2H6c-1.103 0-2-.897-2-2V4c0-1.102.897-2 2-2h9.414zm2.587 18L18 8h-4V4H6v16h12.001zM12 10l1.143 2.857H16l-2.472 2.087L14.857 18 12 16.11 9.143 18l1.329-3.056L8 12.857h2.857L12 10z" />
</svg>
```

**Comment by goyney** [comment]
- [x] Hidden File - Already exists as [`file-hidden`](https://materialdesignicons.com/icon/file-hidden)
- [x] Error File - Already exists as [`file-alert(-outline)`](https://materialdesignicons.com/icon/file-alert)
- [x] Locked File - Already exists as [`file-lock`](https://materialdesignicons.com/icon/file-lock) (Needs outline version)
- [x] Checked Out File - Already exists as [`file-plus`](https://materialdesignicons.com/icon/file-plus) (Needs outline version)
- [x] Move File - Already exists in [`file-move`](https://materialdesignicons.com/icon/file-move) and [`file-send`](https://materialdesignicons.com/icon/file-send) (Need outline version)
---
- [ ] Active File - _I don't see a use case for this and believe it is too niche._
- [ ] Important File - _This doesn't seem to be any different than the proposed `file-star`._
- [ ] Info File - _I don't see a use case for this that can't be solved by using a simple `file` icon or perhaps `file-search`._
- [ ] Burn File - _I don't see a use case for this and believe it is too niche._
- [ ] Favorite File - _Could be created as `file-star`._
---

So, let's add `file-star` from @hanakin:

![image](https://user-images.githubusercontent.com/1015040/54480749-c09a8f80-4802-11e9-89ef-c6c0d815ff1f.png)
[file-star.svg.zip](https://github.com/Templarian/MaterialDesign/files/2974426/file-star.svg.zip)

Then, I've created the missing outline versions of the other 4 existing icons:

![image](https://user-images.githubusercontent.com/1015040/54480845-0c016d80-4804-11e9-9777-53b58a0c026e.png)![image](https://user-images.githubusercontent.com/1015040/54480850-128fe500-4804-11e9-93b0-a78078ed79c7.png)
![image](https://user-images.githubusercontent.com/1015040/54480853-191e5c80-4804-11e9-8efe-25d50c01d7e4.png)![image](https://user-images.githubusercontent.com/1015040/54480857-1facd400-4804-11e9-96c0-ac3aa0c6cf25.png)

[file-outlines.zip](https://github.com/Templarian/MaterialDesign/files/2974433/file-outlines.zip)

**Comment by hanakin** [comment]
File lock was proposed as is because you lock a file that could potentially be star info erc

**Comment by MrGrigri** [comment]
I'm going to add to this list with `file-account-outline`. 

[![file-account-outline.zip](https://user-images.githubusercontent.com/4528551/54710881-4756b180-4b0e-11e9-9ed6-224c989874c6.png)](https://github.com/Templarian/MaterialDesign/files/2989646/file-account-outline.zip)

**Comment by goyney** [comment]
Note: There's some overlap here with #3964. We should probably address that issue BEFORE this one.

**Comment by goyney** [comment]
Added the `file-star` icons:
[![file-star](https://materialdesignicons.com/icon/file-star)](https://materialdesignicons.com/icon/file-star)[![file-star-outline](https://materialdesignicons.com/icon/file-star-outline)](https://materialdesignicons.com/icon/file-star-outline)

The rest were added in #3964.
