### ISSUE TITLE
Wrong size of icon with Angular Material

### ISSUE THREAD

**Issue by pavethiran** [Templarian/MaterialDesign#4047]
I'm using the `@mdi/angular-material` and registering the `mdi.svg` via the IconRegistry.
Everything works great except when I'm using an `mat-icon-button`. In that case, the icon is too big for the button and is cut.

This seems to be an issue with the icons, because they don't define `viewBox`. Since some icons don't go from edge to edge, the lower and right part of the SVG is cut.

This can be fixed by adding `viewbox="0 0 24 24"` to the SVG definitions or by adding a transparent box in the background. The first option is the simplest, because `viewBox` already exists on the SVGs.

✌️

**Comment by HitomiTenshi** [comment]
I created a PR here: https://github.com/Templarian/MaterialDesign-Angular-Material/pull/6

The PR should copy over the existing `viewBox` definitions.
