### ISSUE TITLE
Fastfood icon

### ISSUE THREAD

**Issue by pavethiran** [Templarian/MaterialDesign#4048]
| Icon | Url |
| --- | --- |
| ![baseline_fastfood_black_18dp](https://user-images.githubusercontent.com/4603306/54480468-ecc90700-4828-11e9-9639-a8b3075834ef.png) | https://material.io/tools/icons/?icon=fastfood |

![fastfood](https://user-images.githubusercontent.com/4603306/54480570-48e05b00-482a-11e9-9ce7-ef80e789a16d.png)

**Comment by goyney** [comment]
We already have `food`.
[![food](https://materialdesignicons.com/icon/food)](https://materialdesignicons.com/icon/food)

These icons are way too similar and I prefer our version. I propose we alias our existing `food` with `fastfood` instead of adding this icon.

**Comment by Templarian** [comment]
Alias added. `fast-food` and `fast-food-off`.
