### ISSUE TITLE
format-text-variant

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4049]
So, we currently have `format-color-text`:

[![format-color-text](https://materialdesignicons.com/icon/format-color-text)](https://materialdesignicons.com/icon/format-color-text)

This icon is arbitrarily pushed up in the viewbox to accommodate `color-helper`:

[![color-helper](https://materialdesignicons.com/icon/color-helper)](https://materialdesignicons.com/icon/color-helper).

This is the only icon in the whole library that does this, despite the fact that other icons may need to use `color-helper`. When using the `color-helper` with other icons, you run into issues like this:

*EDIT*: I've been informed by @PeterShaggyNoble that `border-color` and `format-color-fill` are also pushed up.

![Screen Shot 2019-03-15 at 10 37 10 PM](https://user-images.githubusercontent.com/1015040/54480981-51726a80-4805-11e9-9cff-6e83cd177638.png)

---

Therefore, I propose adding a new variant of `format-color-text` that is properly centered in the viewbox. The idea is then the same transform to push any icon up in the viewbox can happen in the consuming application without needing to make special cases just for `format-color-text`.

Since it has nothing to do with "color" anymore, let's name it `format-text`. But wait! We already have `format-text` with a large "T". So, let's add this as `format-text-variant`:

[![format-text](https://materialdesignicons.com/icon/format-text)](https://materialdesignicons.com/icon/format-text)![image](https://user-images.githubusercontent.com/1015040/54481003-9d251400-4805-11e9-951a-8a325a1708f2.png)

[format-text-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/2974445/format-text-variant.svg.zip)

**Comment by Templarian** [comment]
Added. Also added. `format-color-highlight`
