### ISSUE TITLE
Aliases for study/learn/college/university...

### ISSUE THREAD

**Issue by NicoWeio** [Templarian/MaterialDesign#4050]
I miss some aliases in the education sector. Keywords like "study", "learn", "college", "university", "graduate" or "degree" lead nowhere. For at least some of these, an alias to the **school** (alias **graduation-cap**) icon might be appropriate.
See #2109 for the icon.

**Comment by PeterShaggyNoble** [comment]
Thanks for the suggestions. To help us along, though, could you provide us with examples of the icon(s) you're expecting to see returned for each of those search terms so we can alias the ones we already have and add the ones we don't to our queue?

**Comment by NicoWeio** [comment]
I'll try. Just give me some days.

**Comment by NicoWeio** [comment]
**university** → [**school**](https://materialdesignicons.com/icon/school)
**academic-cap** → [**school**](https://materialdesignicons.com/icon/school)
**college** →[**school**](https://materialdesignicons.com/icon/school) or [**teach**](https://materialdesignicons.com/icon/teach), but rather the former
**blackboard** → [**teach**](https://materialdesignicons.com/icon/teach)
(**graduation-cap** → [**school**](https://materialdesignicons.com/icon/school) has already been done)

I also suggest the following:
**paper** → [**note**](https://materialdesignicons.com/icon/note) or maybe [**note-outline**](https://materialdesignicons.com/icon/note-outline)
**think** → [**thought-bubble**](https://materialdesignicons.com/icon/thought-bubble) and **think-outline** → [**thought-bubble-outline**](https://materialdesignicons.com/icon/thought-bubble-outline)

**Comment by PeterShaggyNoble** [comment]
All added. Thanks for the suggestions, @NicoWeio.

Note that multiple aliases can be added to one icon and the same alias can be added to multiple icons.

Let us know if there are any other icons in this category (by creating a new issue).
