### ISSUE TITLE
Unicode in range U+FDD0 to U+FDEF are actually non-characters

### ISSUE THREAD

**Issue by Yourney** [Templarian/MaterialDesign#4052]
I am trying to incorporate the Material Design Icon font in a mobile app.
Therefore, I created a source file that maps the names (like mdi_palette_outline) to the Unicode character (in this case \u{FDE8}).
However, my compilers give a "Invalid unicode scalar" error.

Apparently, the range of unicode characters for U+FDD0 .. U+FDEF is reserved for a block of 32 non-characters "to make additional codes available to programmers to use for internal processing purposes"

This means that I have to comment out 24 characters that lie in that range.

Would it be possible to not use that range of unicode characters?

URL:
https://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=IWS-Chapter04a#4d3110c8

Text:
Unassigned codepoints can be reserved in a similar manner at any time if there is a reason for doing so. This was recently done in TUS 3.1, reserving 32 codepoints from U+FDD0..U+FDEF as non-characters. This was done specifically in order to make additional codes available to programmers to use for internal processing purposes. Again, these should never appear in data.

**Comment by Templarian** [comment]
- [ ] `FDD0` - `64976` - `screw-lag`
- [ ] `FDD1` - `64977` - `screw-machine-flat-top`
- [ ] `FDD2` - `64978` - `screw-machine-round-top`
- [ ] `FDD3` - `64979` - `screw-round-top`
- [ ] `FDD4` - `64980` - `send-circle`
- [ ] `FDD5` - `64981` - `send-circle-outline`
- [ ] `FDD6` - `64982` - `shoe-print`
- [ ] `FDD7` - `64983` - `signature`
- [ ] `FDD8` - `64984` - `signature-freehand`
- [ ] `FDD9` - `64985` - `signature-image`
- [ ] `FDDA` - `64986` -`signature-text`
- [ ] `FDDB` - `64987` -`slope-downhill`
- [ ] `FDDC` - `64988` -`slope-uphill`
- [ ] `FDDD` - `64989` - `thermometer-alert`
- [ ] `FDDE` - `64990` - `thermometer-chevron-down`
- [ ] `FDDF` - `64991` - `thermometer-chevron-up`
- [ ] `FDE0` - `64992` - `thermometer-minus`
- [ ] `FDE1` - `64993` - `thermometer-plus`
- [ ] `FDE2` - `64994` - `translate-off`
- [ ] `FDE3` - `64995` - `upload-outline`
- [ ] `FDE4` - `64996` - `volume-variant-off`
- [ ] `FDE5` - `64997` - `wallpaper`
- [ ] `FDE6` - `64998` - `water-outline`
- [ ] `FDE7` - `64999` - `wifi-star`
- [ ] `FDE8` - `65000` - `palette-outline`
- [ ] `FDE9` - Chrome overrides this character's font settings, so it wasn't added.
- [ ] `FDEA`
- [ ] `FDEB`
- [ ] `FDEC`
- [ ] `FDED`
- [ ] `FDEE`
- [ ] `FDEF`

**Comment by Yourney** [comment]
The question is: Can these characters be moved to another unicode uuuh code, so that I can use these? The url I gave specifies that these codes are reserved.

**Comment by Templarian** [comment]
Yep, forgot to add the bug label. This requires DB edits since I don't have an interface for editing previous releases codepoints (as their never suppose to change).

We'll have to address it in the next release for `3.6.xx`. Until then you'll have to find a workaround unfortunately.

**Comment by PeterShaggyNoble** [comment]
Given that this is a fairly significant breaking change, I think it's best to hold off on this until v4.0.x

Even though we don't use semantic versioning, people generally tend to be less forgiving of such breaking changes without a major version change.

**Comment by Yourney** [comment]
The workaround for me seems to be 'do not use the 20 something icons'. I think I can live with that for a while, because this set has many more icons than my previous set (google material icons).

One way to avoid the breaking change may be to duplicate the offending icons ... and remove the originals in the 4.0.0 release.

**Comment by Templarian** [comment]
Update... Chrome has an issue rendering `fe00...fe2F` also.

I just ran into this while working on the next release.

**Comment by Templarian** [comment]
https://en.wikibooks.org/wiki/Unicode/Character_reference/F000-FFFF

This chart makes it a lot easier to see what characters not to use.

**Comment by Templarian** [comment]
Okay updated the ones above for `3.6.95`, but need to fix some other codepoints still before releasing.

**Comment by Templarian** [comment]
Fixing the codepoints below also. These all have fixed spacing that ignores the character box.

- [ ] fe00
- [ ] fe01
- [ ] fe02
- [ ] fe03
- [ ] fe04
- [ ] fe05
- [ ] fe06
- [ ] fe07
- [ ] fe08
- [ ] fe09
- [ ] fe0A
- [ ] fe0B
- [ ] fe0C
- [ ] fe0D
- [ ] fe0E
- [ ] fe0F

**Comment by Templarian** [comment]
- [ ] `FE20` -> `FE7E`
- [ ] `FE21` -> `FE7F`
- [ ] `FE22` -> `FE80`
- [ ] `FE23` -> `FE81`
- [ ] `FE24` -> `FE82`
- [ ] `FE25` -> `FE83`
- [ ] `FE26` -> `FE84`
- [ ] `FE27` -> `FE85`
- [ ] `FE28` -> `FE86`
- [ ] `FE29` -> `FE87`
- [ ] `FE2A` -> `FE88`
- [ ] `FE2B` -> `FE89`
- [ ] `FE2C` -> `FE8A`
- [ ] `FE2D` -> `FE8B`
- [ ] `FE2E` -> `FE8C`
- [ ] `FE2F` -> `FE8D`

**Comment by Templarian** [comment]
These have been fixed and are in the `3.6.95` release. I'll keep an eye out for issues in the future.

Thanks again for bringing this to our attention!

**Comment by Yourney** [comment]
Great!!
You are welcome ;-)

**Comment by Yourney** [comment]
Perhaps a silly question ...
You state it has been fixed in the 3.6.95 release. When I visit http://materialdesignicons.com , I can download 3.5.94.

![Screenshot 2019-04-15 at 13 26 53](https://user-images.githubusercontent.com/8373961/56129373-286b0400-5f82-11e9-8759-338b763649be.png)

How can I download 3.6.95?
Thanks!
Wouter

**Comment by Templarian** [comment]
@Yourney Got busy with a work thing last night and didn't have a second to update the site. That just links over to the https://github.com/templarian/MaterialDesign-SVG repo I think.

So you can just download it from there.

**Comment by Yourney** [comment]
On the page you mention, one can download the svg-master.
On http://materialdesignicons.com One can download the webfoot-master, containing the ttf, not, woff, woff2 and the svg.

**Comment by Templarian** [comment]
That's the other dist repo for npm: https://github.com/Templarian/MaterialDesign-Webfont

**Comment by Yourney** [comment]
Thanks !!!!
