### ISSUE TITLE
Prezi icon

### ISSUE THREAD

**Issue by FANMixco** [Templarian/MaterialDesign#4054]
Prezi is a well-recognized software for building presentations as PowerPoint:
https://images.g2crowd.com/uploads/product/image/large_detail/large_detail_1493138483/prezi.jpg

**Comment by Templarian** [comment]
Their logo might be too detailed for the small 24x24 size. Assuming it might also go against their brand to use it at such a small size.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/54579300-d2ca2880-49d0-11e9-843f-f6e1e3032144.png)

Yeah, too much detail.

**Comment by PeterShaggyNoble** [comment]
They _do_ use a simplified version as their favicon.
