### ISSUE TITLE
view-list-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4055]
Saw this icon on Google Drive

[![image](https://user-images.githubusercontent.com/4528551/54549684-2e17fe80-4970-11e9-9940-48ae2bd2b4ce.png)](https://github.com/Templarian/MaterialDesign/files/2979439/list-view-outline.zip)

![image](https://user-images.githubusercontent.com/4528551/54549742-49830980-4970-11e9-8bcf-64a56da91b0a.png)

**Comment by MrGrigri** [comment]
Apparently, this was rejected in #2263, So I'm going to close this one out.

**Comment by PeterShaggyNoble** [comment]
It was actually Google's `view_comfy_outline` icon that was rejected in #2263.
