### ISSUE TITLE
account-edit-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4057]
I needed this for a project.

[![account-edit-outline](https://user-images.githubusercontent.com/4528551/54561379-236a6300-498a-11e9-813e-a384ead46ddb.png)](https://github.com/Templarian/MaterialDesign/files/2980121/account-edit-outline.zip)

**Comment by goyney** [comment]
[![account-edit-outline](https://materialdesignicons.com/icon/account-edit-outline)](https://materialdesignicons.com/icon/account-edit-outline)
