### ISSUE TITLE
home-circle-outline

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#4058]
We miss an home-circle-outline-icon.

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/54649400-4dde1e00-4a67-11e9-88d1-b0aebb6ce360.png)
[home-circle-outline.svg](https://github.com/terreng/samples/blob/master/home-circle-outline.svg)

**Comment by goyney** [comment]
It looks like the home isn't square to the grid, causing it to blur at native resolution.

**Comment by terreng** [comment]
The previous home icon was 13.2 x 11 and shifted down 0.5 from the centre. This new version is 12 x 10 and exactly centered.

![image](https://user-images.githubusercontent.com/11605395/54697691-3c3e5a00-4aeb-11e9-9dae-7d69d20a31ee.png)
[home-circle-outline-2.svg](https://github.com/terreng/samples/blob/master/home-circle-outline-2.svg)

**Comment by goyney** [comment]
[![home-circle-outline](https://materialdesignicons.com/icon/home-circle-outline)](https://materialdesignicons.com/icon/home-circle-outline)
