### ISSUE TITLE
Google home mini icon/chromecast

### ISSUE THREAD

**Issue by 78wesley** [Templarian/MaterialDesign#4059]
Maybe add a google home mini icon like the google home![image](https://user-images.githubusercontent.com/9322930/54642534-2a31cc80-4a95-11e9-90c2-6bc28614a6d0.png)
I can't make picture/icons maybe one of you guys can make one. and maybe you can create one for a google chromecast?

**Comment by JamesCoyle** [comment]
Duplicate of #2731
