### ISSUE TITLE
Gantt Chart Icon or "Timeline" for projects/engagements 

### ISSUE THREAD

**Issue by seanmcne** [Templarian/MaterialDesign#406]
- [x] chart-gantt
- [x] chart-timeline

**Comment by Templarian** [comment]
I think these could be 2 separate icons. The timeline being more linear style.

**Comment by seanmcne** [comment]
Agreed.  On a separate note, I just noticed on the new MaterialDesign site I think the search is case sensitive.  "Chart" returns nothing but "chart" brings back a few icons. Thanks again for all the great work!

**Comment by Templarian** [comment]
The site isn't really new. It's been around for about 10 months now. That definitely a bug though, will fix it tonight. Thanks.

**Comment by seanmcne** [comment]
Thanks!  I should have just said "site", it's just new to me :)

**Comment by CoDEmanX** [comment]
My first try:
![gantt](https://cloud.githubusercontent.com/assets/1309249/8665112/77c0f22a-29e0-11e5-91eb-9bc4b8cf7187.png)

I like the following:
![Imgur](http://i.imgur.com/AIvk91a.jpg?1)

although it looks quite similar to `ic-tune`:
https://github.com/google/material-design-icons/blob/master/image/svg/production/ic_tune_48px.svg

**Comment by seanmcne** [comment]
Thanks!  These look good but me think of music tabs, a vertical line could be introduced to indicate more of a  timeline.  Attached icons are from MS Project for reference: 

![image](https://cloud.githubusercontent.com/assets/2292260/8705105/0c6b7f32-2aed-11e5-89de-475d2f3f9c14.png)

Thoughts?

**Comment by CoDEmanX** [comment]
Maybe like this?
![timeline](https://cloud.githubusercontent.com/assets/1309249/8715258/16b4990a-2b7f-11e5-98af-35e5f230930d.png)

Slightly different length and position of the bars:
![timeline2](https://cloud.githubusercontent.com/assets/1309249/8715280/64a7fe86-2b7f-11e5-9a0f-b8fcd3b1faf9.png)

Another idea:
![gantt-variant](https://cloud.githubusercontent.com/assets/1309249/8715348/59efe0c0-2b80-11e5-9a0c-b77b4378ec64.png)

**Comment by seanmcne** [comment]
Oh very nice :+1: the second one I like a bit better as it seems to flow a little more smoothly. I could possibly see the desire to have one horizontal variant along with one that's similar to the second icon above - but I like it. Great work!

**Comment by seanmcne** [comment]
CoDEmanX - did you have an icon ready to post or a draft possibly?  Thanks again!

**Comment by CoDEmanX** [comment]
Added Dropbox links for 3 icons I posted earlier. @Templarian?

**Comment by Templarian** [comment]
Marked as a high priority, will be in shortly.

**Comment by seanmcne** [comment]
Thanks Austin, one clarification (since this is my first time through the process of requesting icons) once you have them checked in will they show up both in github as well as the materialdesign website?  

Thanks again for the great work guys - this is an awesome project!

**Comment by CoDEmanX** [comment]
Immediately on website, eventually in repo - if you look at the commit history, you'll see that he committed new icons in batches.

**Comment by Templarian** [comment]
[![chart-scatterplot-hexbin](https://materialdesignicons.com/icon/chart-scatterplot-hexbin)](https://materialdesignicons.com/icon/chart-scatterplot-hexbin) [![chart-gantt](https://materialdesignicons.com/icon/chart-gantt)](https://materialdesignicons.com/icon/chart-gantt) [![chart-timeline](https://materialdesignicons.com/icon/chart-timeline)](https://materialdesignicons.com/icon/chart-timeline)

Sorry, not sure how this kept getting overlooked. This will go into Sunday's release.

**Comment by CoDEmanX** [comment]
Hm, shouldn't the timeline and the gantt icons be swapped? The one with the 3 horizontal bars look more like a timeline, doesn't it?

**Comment by OlsonDev** [comment]
Gantt chart software usually has a vertical line running through all task estimates indicating current time. I'm guessing the timeline icon has the thing above to say "all time estimates in this set"..?

**Comment by Templarian** [comment]
This release went out earlier. But we can revise the icon. I think the gantt looks fine. Timeline works, but if something else looks nicer we can substitute it.

**Comment by CoDEmanX** [comment]
I see, I guess it's fine then.
Am 16.05.2016 1:14 vorm. schrieb Josh Olson <notifications@github.com>:Gantt chart software usually has a vertical line running through all task estimates indicating current time. I'm guessing the timeline icon has the thing above to say "all time estimates in this set"..?
