### ISSUE TITLE
More IoT Device Icons

### ISSUE THREAD

**Issue by gdreelin** [Templarian/MaterialDesign#4063]
Icons like Fingbox, Smartthings Hub, and Philips Hues Hub.

**Comment by Templarian** [comment]
Unfortunately we made a decision a while back to not add specific IoT devices. But adding the SmartThings brand logo is probably fine as it's more of a hub.

We actually removed any specific IoT devices and replaced them with generic icons.

**Comment by gdreelin** [comment]
That is great! Like Fing's logo, Philips, Wemo, etc... I am cool with that.   Thanks

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
