### ISSUE TITLE
3D-printer-nozzle

### ISSUE THREAD

**Issue by simbesh** [Templarian/MaterialDesign#4064]
![image](https://user-images.githubusercontent.com/17171925/54734208-b6ed9f00-4be9-11e9-95c7-21f129d6d0a6.png)

was thinking something like this

**Comment by jldubz** [comment]
I had some spare time today and mocked up a filled and outlined version for this.  I had come across some really nice looking stock art that did something very similar to this a few weeks ago; so I found the middle ground between that and this.

### Filled
![3dprinter_nozzle_filled](https://user-images.githubusercontent.com/1074249/54776666-f797e900-4be6-11e9-860a-d4fbba9e8905.png)

```XML
<svg
   xmlns="http://www.w3.org/2000/svg"
   style="width:24px;height:24px"
   viewBox="0 0 24 24">
  <path
     style="fill-opacity:1;stroke:#000000;stroke-width:0.5"
     d="M 4,22 Q 4,20 6,20 4,20 4,18 4,16 6,16 h 4 q 1,0 1,-2 h -0.5 l -3,-3 H 4 V 7 H 6 V 2 h 12 v 5 h 2 v 4 h -3.5 l -3,3 H 13 v 2 q 0,2 -2,2 h 7 q 2,0 2,2 0,2 -2,2 z m 9.5,-8 h -3 M 6,20 H 18 M 11,18 H 6"
     id="path1" />
</svg>
```

### Outline
![3dprinter_nozzle_outline](https://user-images.githubusercontent.com/1074249/54776675-fa92d980-4be6-11e9-8a0b-274257529127.png)

```XML
<svg
   xmlns="http://www.w3.org/2000/svg"
   viewBox="0 0 24 24"
   style="width:24px;height:24px">
  <path
     id="path1"
     d="M 4,22 Q 4,20 6,20 4,20 4,18 4,16 6,16 h 4 q 1,0 1,-2 h -0.5 l -3,-3 H 4 V 7 H 6 V 2 h 12 v 5 h 2 v 4 h -3.5 l -3,3 H 13 v 2 q 0,2 -2,2 h 7 q 2,0 2,2 0,2 -2,2 z m 9.5,-8 h -3 M 6,20 H 18 M 11,18 H 6"
     style="fill-opacity:0;stroke:#000000;stroke-width:0.5" />
</svg>
```

[3dprinter_nozzle.zip](https://github.com/Templarian/MaterialDesign/files/2993493/3dprinter_nozzle.zip)

**Comment by Templarian** [comment]
@jldubz Might be a good idea to look at the guidelines for outline icons for future contributions.

https://material.io/design/iconography/system-icons.html#system-icon-metrics

**Comment by Templarian** [comment]
[![printer-3d-nozzle](https://materialdesignicons.com/icon/printer-3d-nozzle)](https://materialdesignicons.com/icon/printer-3d-nozzle) [![printer-3d-nozzle-outline](https://materialdesignicons.com/icon/printer-3d-nozzle-outline)](https://materialdesignicons.com/icon/printer-3d-nozzle-outline)

Pretty sure in context this should work without the second line underneath.
