### ISSUE TITLE
Home Automation

### ISSUE THREAD

**Issue by jldubz** [Templarian/MaterialDesign#4066]
I have created a few icons to serve various situations while developing Home Automation applications.  Some of these are variations of the Google Material icons, and some of them are custom designs.

### Indoor Video Camera
This works for indoor security cameras that can be placed on a flat surface (The only thing close enough to this that I could find was a webcam icon)

![indoor_video_camera](https://user-images.githubusercontent.com/1074249/54763534-86e3d300-4bcc-11e9-9902-695a84831b59.png)
```XML
<svg xmlns="http://www.w3.org/2000/svg"
	style="width:24px;height:24px"
	viewBox="0 0 24 24">
    <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="M 7,15.5 Q 6.5,15.5 6.5,16 L 6,20 q 0,2 2,2 h 8 q 2,0 2,-2 l -0.5,-4 q 0,-0.5 -0.5,-0.5 z m 10.4,0 C 17,14 17.5,11 18,9 18.5,7 18,1.7 12,1.7 6,1.7 5.5,7 6,9 c 0.5,2 1,5 0.6,6.5 z M 8,3 v 10 c 2,1.5 6,1.5 8,0 V 3 m -4,0.5 a 3,3 -180 0 1 0,6 3,3 -180 0 1 0,-6 m 0,2 a 1,1 -180 0 1 0,2 1,1 -180 0 1 0,-2"
       id="path1" />
</svg>
```

### Outdoor Video Camera
This was designed as an alternative to the existing video camera icon because the existing one did not resemble our camera closely enough

![outdoor_video_camera](https://user-images.githubusercontent.com/1074249/54763721-db874e00-4bcc-11e9-9dfc-087d7477a45a.png)
```XML
<svg xmlns="http://www.w3.org/2000/svg"
	style="width:24px;height:24px"
	viewBox="0 0 24 24">
	<path
	   style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
	   d="m 22,7 h -0.5 q -1,0 -1,1 0,1 -1,1 H 18 C 17,9 17,9 16,9.33 15,9.66 14.2,9.7 13.5,9 Q 13,8 11.5,8.33 l -8.5,3 q -0.67,0.33 -0.5,1 0.16,1 1.16,0.67 Q 5,12.5 5.33,13.66 L 6,15.5 Q 6.5,17 8,16.33 L 13.66,14.5 Q 15.1,14 14.9,13 C 14.66,11.66 15,11.9 16,11.5 17,11.1 17,11 18,11 h 1.5 q 1,0 1,1 0,1 1,1 H 22 Z m -14,2.66 2.33,6 M 9,9.33 l 2.33,6"
	   id="path1" />
</svg>
```

### Video Camera Success/Done/Good
The Google Material icons for video cameras have this icon with a few different symbols in the middle, but there is none that has a check mark.  This was used to indicate that a configuration change to a video camera was successful

![video_camera_success](https://user-images.githubusercontent.com/1074249/54763893-26a16100-4bcd-11e9-8cef-a2cec7a29bc0.png)
```XML
<svg xmlns="http://www.w3.org/2000/svg"
	style="width:24px;height:24px"
	viewBox="0 0 24 24">
    <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="M 17,10.5 V 7 C 17,6.45 16.55,6 16,6 H 4 C 3.45,6 3,6.45 3,7 v 10 c 0,0.55 0.45,1 1,1 h 12 c 0.55,0 1,-0.45 1,-1 v -3.5 l 4,4 V 6.5 Z M 15,16 H 5 V 8 H 15 Z M 6,12 9,15 14,10 13,9 9,13 7,11 Z"
       id="path1" />
</svg>
```

### Change/Swap Configuration
I couldn't find anything that represented switching or swapping configurations or systems; so I tweaked an existing Google Material Icon to create this one for that.

![change_configuration](https://user-images.githubusercontent.com/1074249/54764056-6d8f5680-4bcd-11e9-943e-b41bd53a0106.png)
```XML
<svg xmlns="http://www.w3.org/2000/svg"
	style="width:24px;height:24px"
	viewBox="0 0 24 24">
  <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="M 14.26,7.12 V 4.87 H 3.75 V 3.37 H 14.26 V 1.12 l 5.99,3 z"
       id="path1" />
    <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="m 13,6.8 0.1,1.4 1.6,0.95 1.2,-0.65 0.75,0.8 0.35,1 -1.2,0.7 v 1.95 l 1.2,0.7 -0.35,1 -0.75,0.8 -1.2,-0.65 -1.6,0.95 -0.1,1.4 -1,0.2 -1,-0.2 -0.1,-1.4 L 9.3,14.8 8.1,15.45 7.35,14.65 7,13.65 8.2,12.95 V 11 L 7,10.3 7.35,9.3 8.1,8.5 9.3,9.15 10.9,8.2 11,6.8 12,6.6 Z m -3.3,6.55 2.3,1.3 2.3,-1.3 V 10.6 L 12,9.3 9.7,10.6 Z"
       id="path2" />
    <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="m 20.25,19.12 v 1.5 H 9.74 v 2.25 l -5.99,-3 5.99,-3 v 2.25 z"
       id="path3" />
</svg>
```

### Sign out/Log out
This one is a more generic design.  I did not like how all of the signout and logout icons go left to right and point towards the form.  I reversed the design to better indicate that you are leaving the current form or application.  Less ambiguity this way.

![app_sign_out](https://user-images.githubusercontent.com/1074249/54764403-1ccc2d80-4bce-11e9-97f5-aee2c247c135.png)
```XML
<svg xmlns="http://www.w3.org/2000/svg"
	style="width:24px;height:24px"
	viewBox="0 0 24 24">
	<path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="M 16.5,10.59 H 5.33 L 8.91,7 7.5,5.59 l -6,6 6,6 1.41,-1.41 -3.58,-3.59 H 16.5 Z"
       id="path1" />
    <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="m 21.55,1.88 c 0.32,0 0.58,0.25 0.58,0.57 0,3.94 0,15.15 0,19.09 0,0.32 -0.27,0.59 -0.59,0.59 -2.51,0 -9.46,0 -11.97,0 C 9.26,22.13 9,21.87 9,21.56 9,21.18 9,20.25 9,18.75 h 1.88 v 1.13 h 9 V 4.13 h -9 V 4.88 H 9 C 9,3.68 9,2.93 9,2.63 9,2.21 9.34,1.88 9.75,1.88 c 2.48,0 9.29,0 11.8,0 z"
       id="path2" />
</svg>
```

[Icons.zip](https://github.com/Templarian/MaterialDesign/files/2992723/Icons.zip)

**Comment by goyney** [comment]
- As you stated, the [indoor](https://materialdesignicons.com/icon/webcam) and [outdoor](https://materialdesignicons.com/icon/cctv) cameras are already included in the library. Icons are meant to be "simple" and our two icons already indicate what they represent. Adding variations to match specific devices is not really something we're interested in pursuing or maintaining.

- A `video` icon with a check could be useful, so we'll consider adding it in https://github.com/Templarian/MaterialDesign/issues/4067.

- The settings swap icon seems like a potentially good request too. Can you please create a new request specifically for this concept?

- The sign-out/log-out icon is unlikely to be added. We had conversations about arrow side and direction in https://github.com/Templarian/MaterialDesign/issues/288 and opt'ed to leave them alone.

---

Thank you for your suggestions. I am going to close this issue out for now, but do create new issues for any additional icon suggestions, one icon per issue please.

**Comment by jldubz** [comment]
Thank you!

I have created [#4068](https://github.com/Templarian/MaterialDesign/issues/4068) for the settings swap icon.
