### ISSUE TITLE
settings-transfer(-outline)

### ISSUE THREAD

**Issue by jldubz** [Templarian/MaterialDesign#4068]
Per request in [#4066](https://github.com/Templarian/MaterialDesign/issues/4066) I am creating a new request specifically for this concept.

### Change/Swap Configuration
I couldn't find anything that represented switching or swapping configurations or systems; so I tweaked an existing Google Material Icon to create this one for that.

![change_configuration](https://user-images.githubusercontent.com/1074249/54764056-6d8f5680-4bcd-11e9-943e-b41bd53a0106.png)
```XML
<svg xmlns="http://www.w3.org/2000/svg"
	style="width:24px;height:24px"
	viewBox="0 0 24 24">
  <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="M 14.26,7.12 V 4.87 H 3.75 V 3.37 H 14.26 V 1.12 l 5.99,3 z"
       id="path1" />
    <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="m 13,6.8 0.1,1.4 1.6,0.95 1.2,-0.65 0.75,0.8 0.35,1 -1.2,0.7 v 1.95 l 1.2,0.7 -0.35,1 -0.75,0.8 -1.2,-0.65 -1.6,0.95 -0.1,1.4 -1,0.2 -1,-0.2 -0.1,-1.4 L 9.3,14.8 8.1,15.45 7.35,14.65 7,13.65 8.2,12.95 V 11 L 7,10.3 7.35,9.3 8.1,8.5 9.3,9.15 10.9,8.2 11,6.8 12,6.6 Z m -3.3,6.55 2.3,1.3 2.3,-1.3 V 10.6 L 12,9.3 9.7,10.6 Z"
       id="path2" />
    <path
       style="fill-opacity:0;stroke:#000000;stroke-width:0.6"
       d="m 20.25,19.12 v 1.5 H 9.74 v 2.25 l -5.99,-3 5.99,-3 v 2.25 z"
       id="path3" />
</svg>
```

**Comment by PeterShaggyNoble** [comment]
I like the idea of this but I think both arrows should be in the bottom right, as they are in our `bank-transfer` icon.

**Comment by MrGrigri** [comment]
Yeah, I would use the `transfer` modifier for this one.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/54841343-bd852080-4c94-11e9-9d0d-5c44777124ac.png) ![image](https://user-images.githubusercontent.com/4528551/54841366-c970e280-4c94-11e9-9687-d69cdd135048.png)

---
#### Files
[settings-transfer.zip](https://github.com/Templarian/MaterialDesign/files/2997581/settings-transfer.zip)

**Comment by CoDEmanX** [comment]
Hm, the cog seems a bit too large. It would be easier to recognize if a smaller portion was removed I guess.

**Comment by PeterShaggyNoble** [comment]
Or, maybe, reduce the size of the cog by 1 point in each direction?

**Comment by MrGrigri** [comment]
I believe that it would lose recognizability if we reduce its size.

**Comment by goyney** [comment]
https://github.com/Templarian/MaterialDesign/issues/4271 will play an important part in the names for these icons.

**Comment by goyney** [comment]
[![settings-transfer](https://materialdesignicons.com/icon/settings-transfer)](https://materialdesignicons.com/icon/settings-transfer)[![settings-transfer-outline](https://materialdesignicons.com/icon/settings-transfer-outline)](https://materialdesignicons.com/icon/settings-transfer-outline)
