### ISSUE TITLE
compass-square

### ISSUE THREAD

**Issue by trhessel** [Templarian/MaterialDesign#4069]
I was wondering if someone could create the Masonic Square and Compass, being a mason would be nice to add material design icons to my home automation software that I use at the lodge as well at home. Regard, Tom

![image](https://user-images.githubusercontent.com/46470153/54797468-a0b40300-4c2a-11e9-90a8-b49d4a5192e5.png)

**Comment by MrGrigri** [comment]
Would we add this as a brand icon or create our own?

**Comment by trhessel** [comment]
Not sure, would there be a reason for one vs the other? The square and
compass represents freemasonry and is used to identify membership.

**Comment by MrGrigri** [comment]
For some reason, my contribution didn't stay...here it is. 

[![ruler-square-compass.zip](https://user-images.githubusercontent.com/4528551/54927985-d2ea8c80-4ed8-11e9-88d5-2a19fbfb5a27.png)](https://github.com/Templarian/MaterialDesign/files/3003798/ruler-square-compass.zip)

**Comment by trhessel** [comment]
I think that looks great, any idea how long before that is posted so it can
be used? Any way to reduce the space between the square and compass a
little bit? or given the scale is that is what is required?

**Comment by MrGrigri** [comment]
Md guidelines require a 2-pixel cutout. Here is a variation with the ruler 3-pixels wide and moved down 1 pixel as well as the compass moved up 1 pixel.

[![compass-square.zip](https://user-images.githubusercontent.com/4528551/54930957-cd437580-4edd-11e9-909e-71abaad8029a.png)](https://github.com/Templarian/MaterialDesign/files/3004015/compass-square.zip)

**Comment by trhessel** [comment]
Ahhh ok thanks, wasn't aware of the guidelines. If it were me I like the
first version better :).

**Comment by trhessel** [comment]
Sorry as this will show my ignorance of the process but will this then just
show up on materialdesignicons.com or do I need to further submit or use
what you developed locally?

**Comment by MrGrigri** [comment]
This one has been labeled as milestone 4.0.xx. We are currently on 3.6.xx. When this issue gets closed, it will then be queued for the next release.

**Comment by trhessel** [comment]
That is great, thank you so much.

**Comment by goyney** [comment]
If you click on his preview, you can download the raw SVG if you need to use it before it is added to the library. Otherwise, once you get a close notification for this issue, it'll be in the next released version!

**Comment by trhessel** [comment]
Hi Michael, I see you're still on 3.6 do you know when 4.0 will drop so
this icon will be in there?

Thanks,

Tom

**Comment by goyney** [comment]
[![ruler-square-compass](https://materialdesignicons.com/icon/ruler-square-compass)](https://materialdesignicons.com/icon/ruler-square-compass)
