### ISSUE TITLE
Icon request: line graph

### ISSUE THREAD

**Issue by nwalters512** [Templarian/MaterialDesign#407]
I mocked up something like what I think would be a good idea in Paint; obviously it needs the love of a designer :stuck_out_tongue:  This would be good for representing statistics, trends, etc

![line graph icon](http://i.imgur.com/PbOlmtL.png)

- [ ] Redesign `chart-line`

**Comment by Templarian** [comment]
I'm going to put this in a request to remake the http://materialdesignicons.com/icon/chart-line icon. Not really a fan of how it is currently designed.

**Comment by ecols33** [comment]
I made one
![up graph](https://cloud.githubusercontent.com/assets/12535799/8027538/c34543de-0d5e-11e5-915b-f4950e39dfe6.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/chart-line

@ecols33 That is a google provided icon already http://materialdesignicons.com/icon/trending-up
