### ISSUE TITLE
math-compass path

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4070]
When I was working on #4069, I noticed that our `math-compass` icon's path data is way off. Here is a comparison with a fix. 

[![math-compass.zip](https://user-images.githubusercontent.com/4528551/54848216-612afc80-4ca6-11e9-9600-b0925bc54230.png)](https://github.com/Templarian/MaterialDesign/files/2998016/math-compass.zip)

**Comment by Templarian** [comment]
Updated! 😃
