### ISSUE TITLE
vuetify

### ISSUE THREAD

**Issue by MajesticPotatoe** [Templarian/MaterialDesign#4071]
Used for Vuetify.js - The popular material design based framework built on Vue.js
SVG attached. Preview below.

![vuetify_preview](https://user-images.githubusercontent.com/27827979/54850140-ac500a00-4cbc-11e9-98d4-64f939533702.png)

[vuetify.svg.zip](https://github.com/Templarian/MaterialDesign/files/2998114/vuetify.svg.zip)

**Comment by Templarian** [comment]
🤨 Hmm...  we'll look into this.

Just out of curiosity does the Vuetify community use the `@mdi/js` or the `@mdi/font`?

**Comment by johnleider** [comment]
Vuetify author here. We have instructions on both but I want to make the js variant our default in the future.

**Comment by Templarian** [comment]
Correct answer. I'll try and add this one shortly.

**Comment by Templarian** [comment]
[![vuetify](https://materialdesignicons.com/icon/vuetify)](https://materialdesignicons.com/icon/vuetify)

Added! By the way be sure to have your little army of devs/users star this project. 😃

**Comment by WORMSS** [comment]
Dev Army to the rescue!

**Comment by Templarian** [comment]
@johnleider You probably heard, but this went out in Sunday's `3.6.95` release.
