### ISSUE TITLE
niconico

### ISSUE THREAD

**Issue by Craftplacer** [Templarian/MaterialDesign#4072]
[Website](https://www.nicovideo.jp/)

![icon_niconico](https://user-images.githubusercontent.com/22963120/54866190-35c11400-4d71-11e9-9ca8-40f1f5a025a6.png)  ([original image, taken from header, white](https://nicovideo.cdn.nimg.jp/web/images/bundle/modules/GlobalHeader/resources/icon_niconico.png))

This icon might be used in the same context as other icons like `youtube` or other website icons.

**Comment by JapanYoshi** [comment]
As a Japanese person, I can confirm that Niconico is a significant social media presence (though it's starting to lose the fight against YouTube)

**Comment by Craftplacer** [comment]
> As a Japanese person, I can confirm that Niconico is a significant social media presence (though it's starting to lose the fight against YouTube)

I actually needed that icon while constructing my website where I was adding my profiles to different sites. I wanted to add niconico but there wasn't any (Material Design) icon for it :sweat_smile:

**Comment by MrGrigri** [comment]
Is there an SVG we can get?

**Comment by Craftplacer** [comment]
> Is there an SVG we can get?

I found this; https://www.easyicon.net/1188751-JP_niconico_icon.html

**Comment by PeterShaggyNoble** [comment]
Note that we are starting to drastically reduce the number of brand icons we add to the library and, instead, directing people to request them from [Simple Icons](https://simpleicons.org/) ([repo](https://github.com/simple-icons/simple-icons)), an icon library dedicated to brand icons.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
