### ISSUE TITLE
lightbulb-off icons

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#4073]
I noticed that the icons for turned off lightbulb are rather different from the "off versions" of other icons, which are mostly using a cross out line. I therefore suggest to add these additional icons following that common approach.

![lightbulb-outline-off](https://user-images.githubusercontent.com/7279415/54877242-1af7a980-4e1c-11e9-8a83-dfc68ff3ce8a.png)
![lightbulb-off](https://user-images.githubusercontent.com/7279415/54877243-1b904000-4e1c-11e9-8c7b-23b6cb5bb47d.png)

[lightbulb-off.zip](https://github.com/Templarian/MaterialDesign/files/3000188/lightbulb-off.zip)

**Comment by Templarian** [comment]
Added! 😃 

Let me know if/when you contribute 3 more icons and I'll assign these over to a contributor account.
