### ISSUE TITLE
filter-plus-variant and filter-minus-variant

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4074]
Such as:

<img width="121" alt="filter-minus-vairant filter-plus-variant" src="https://user-images.githubusercontent.com/6012554/54934580-0bad5480-4f1f-11e9-8ec0-6f4cdbc76369.png">

What do you think ?

**Comment by qnp** [comment]
I have worked on the icons, here are the SVG files, pixel proofed. I also reworked the filter-remove-variant from work in progress (see #3485 ) because I felt like the cross was too big to harmoniously go along with the two new icons.
[filter-variants.zip](https://github.com/Templarian/MaterialDesign/files/3004281/filter-variants.zip)

**Comment by goyney** [comment]
Related: https://github.com/Templarian/MaterialDesign/issues/3485

**Comment by MrGrigri** [comment]
@qnp: the contributions should be a single compound path. You can use our [preview generator](http://dev.materialdesignicons.com/contribute/github) to help with displaying the final icon. 

Once those icons are all a single compound path, then we can add this as a contribution.

**Comment by qnp** [comment]
Greetings,
Here are the previews for the two icons:
![filter-minus-variant](https://user-images.githubusercontent.com/6012554/56749049-40f8cc80-6781-11e9-88f4-a54dfab48ad8.png)
![filter-plus-variant](https://user-images.githubusercontent.com/6012554/56749052-435b2680-6781-11e9-9afe-d9af32cc3915.png)
And here the associated paths:
filter-minus-variant: `M5 10h12v2H5zM2 5h18v2H2zM9 15h4v2H9zM15 17h8v2h-8z``
filter-plus-variant: `M5 10h12v2H5zM2 5h18v2H2zM9 15h4v2H9zM20 17v-3h-2v3h-3v2h3v3h2v-3h3v-2z`
Is it OK ?
Best,

**Comment by JamesCoyle** [comment]
Might be worth keeping the base icon and using the cutouts. I don't like how off-center those look.

**Comment by qnp** [comment]
I'll work on it but only in 1 week. Thanks for the feedback

**Comment by goyney** [comment]
[![filter-variant-plus](https://materialdesignicons.com/icon/filter-variant-plus)](https://materialdesignicons.com/icon/filter-variant-plus)[![filter-variant-minus](https://materialdesignicons.com/icon/filter-variant-minus)](https://materialdesignicons.com/icon/filter-variant-minus)
