### ISSUE TITLE
boom-gate(-*)

### ISSUE THREAD

**Issue by mitnits** [Templarian/MaterialDesign#4075]
The icon set is missing an icon for open and closed boom barrier (aka traffic gate aka parking gate)

The icon can be along the lines of 
![image](https://user-images.githubusercontent.com/8820606/54982167-d2262900-4fb2-11e9-81dc-6c177a302637.png)

or possibly

![image](https://user-images.githubusercontent.com/8820606/54982210-f3871500-4fb2-11e9-9be5-f56a1df8becb.png)

I know we have gate icon but it does not depict boom barrier and hard to show open and close. Boom barrier open/close OTOH is trivial.

**Comment by Templarian** [comment]
Had to double check, surprised we don't have this one already. Pretty common icon for parking.

Makes me wonder if there is an easily recognizable valet icon also.

**Comment by goyney** [comment]
We have `sign-caution`:
[![sign-caution](https://materialdesignicons.com/icon/sign-caution)](https://materialdesignicons.com/icon/sign-caution)

**Comment by MrGrigri** [comment]
I could see these being used for control. 

![image](https://user-images.githubusercontent.com/4528551/55021050-b8d6aa00-4fbd-11e9-8f0b-eac9a64fe4d0.png) ![image](https://user-images.githubusercontent.com/4528551/55021262-0e12bb80-4fbe-11e9-92c8-39dca4574818.png) ![image](https://user-images.githubusercontent.com/4528551/55021290-1b2faa80-4fbe-11e9-8dae-66a840a69a92.png) ![image](https://user-images.githubusercontent.com/4528551/55021316-2551a900-4fbe-11e9-9da5-4944ff8c3c9e.png)

The question is, should we add an outlined version as well?

---
#### Files

[boom-gate.zip](https://github.com/Templarian/MaterialDesign/files/3009558/boom-gate.zip)

**Comment by goyney** [comment]
I don't think that stripe pattern works at all at native resolution.

**Comment by MrGrigri** [comment]
It's the exact same stripe pattern from the crane.

**Comment by goyney** [comment]
My first thought was, "that can't be right," but it is. 🤔 

My comment was prompted by the angled ones, the detail is really lost there.

**Comment by Templarian** [comment]
Yeah, might look into making the bar `1dp` taller and the stripe more spaced out.

**Comment by MrGrigri** [comment]
More like this?

![image](https://user-images.githubusercontent.com/4528551/55024444-795f8c00-4fc4-11e9-9956-fc9a35bdd6e4.png)

**Comment by mitnits** [comment]
Totally not graphics designer or even claiming to have good taste but this looks like a very “fat” boom to me :) the base can also use some slimming down, in my eyes.

**Comment by MrGrigri** [comment]
The stripes are needed for better recognition of a `boom-gate`. Because of that, there are specific MD guidelines that we are required to follow. As stated [earlier](https://github.com/Templarian/MaterialDesign/issues/4075#issuecomment-476786223), @Templarian asked that the arm be larger and the stripes more spaced apart. The base is as wide as it needs to be for recognition of the center cutout at 1x. I hope this makes sense.

**Comment by Templarian** [comment]
@mitnits Often we have to exaggerate features of physical objects when making an icon like this. Since the size is often on the smaller size having the more recognizable features will be beneficial.

**Comment by MrGrigri** [comment]
Should I also create outlined versions?

![image](https://user-images.githubusercontent.com/4528551/55026426-9e55fe00-4fc8-11e9-94fb-55813a1cf207.png)

**Comment by GreenTurtwig** [comment]
We should always aim to have outline variants.  
Should probably add the alias `arm-barrier`. Never in my life have I heard them referred to as "boom gates".

**Comment by mitnits** [comment]
https://en.m.wikipedia.org/wiki/Boom_barrier
:) not a native speaker though.

**Comment by goyney** [comment]
We should also add `boom-arm` aliases as well. That's a common way to refer to them in the midwestern States.

**Comment by MrGrigri** [comment]
Aliases to add 

- [ ] boom-arm
- [ ] boom-barrier
- [ ] barrier

**Comment by davwheat** [comment]
In the UK, I hear these referred to as `automated/automatic barriers` or `automated/automatic gates`

**Comment by PeterShaggyNoble** [comment]
In Ireland, they're just barriers.

**Comment by Templarian** [comment]
Added all 8 of these and the aliases. 😃 

Slightly modified the outline arrows to be consistent.
