### ISSUE TITLE
Duplicate clock icon

### ISSUE THREAD

**Issue by NicoWeio** [Templarian/MaterialDesign#4076]
[history](https://materialdesignicons.com/icon/history) and [restore-clock](https://materialdesignicons.com/icon/restore-clock) are exactly the same. Is this intentional, because both icons are from Google? 🤔

**Comment by goyney** [comment]
We have several cases of duplicated icons with different names. There are a variety of reasons this may occur, but each case is usually done consciously. I'll let @Templarian close this to confirm it really isn't a bug, but I would assume this was done intentionally.

**Comment by Templarian** [comment]
This was brought up once and we decided to just ignore it for now. I'll keep this open for the 4.0.x release and we can roll a dice and remove one (probably `restore-clock`?).

**Comment by goyney** [comment]
After `restore-clock` is removed, we'll want to add it as an alias to `history`.

**Comment by goyney** [comment]
Removed and aliased!
