### ISSUE TITLE
valve(-open)(-close)

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#4077]
Hi,
couldn't find an icon for a throttle flap. A suggestion would be:
![throttle](https://user-images.githubusercontent.com/7279415/55100824-11439f80-50c3-11e9-928a-93b814af8616.png)
And eventually open/closed states:
![throttle-open-closed](https://user-images.githubusercontent.com/7279415/55100906-3b955d00-50c3-11e9-96d4-b549e98d9465.png)

[throttle.zip](https://github.com/Templarian/MaterialDesign/files/3014674/throttle.zip)

**Comment by MrGrigri** [comment]
I believe this could close #3842.

![image](https://user-images.githubusercontent.com/4528551/55241733-57068200-5201-11e9-833a-45a3033d3583.png)

![image](https://user-images.githubusercontent.com/4528551/55241755-61c11700-5201-11e9-9791-639152c3057b.png) ![image](https://user-images.githubusercontent.com/4528551/55241774-6ede0600-5201-11e9-8fab-6312499fae07.png)


---
#### Files
[valve.zip](https://github.com/Templarian/MaterialDesign/files/3023225/valve.zip)

**Comment by goyney** [comment]
[![valve](https://materialdesignicons.com/icon/valve)](https://materialdesignicons.com/icon/valve)
[![valve-open](https://materialdesignicons.com/icon/valve-open)](https://materialdesignicons.com/icon/valve-open)
[![valve-closed](https://materialdesignicons.com/icon/valve-closed)](https://materialdesignicons.com/icon/valve-closed)
