### ISSUE TITLE
entertainment icon

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#4078]
Hi,
I was looking for an icon covering entertainment systems (audio & video). Since I couldn't find an appropriate one, I tried to draft on myself. Here are some suggestions, but I couldn't decide which would fit best, especially when looking at 'off' versions. Personally the first one looks best to me (also compared to existing icons like [monitor-cellphone](https://materialdesignicons.com/icon/monitor-cellphone)), but I had to bend the template a bit (cross-out-line).
wdyt?
![entertainment](https://user-images.githubusercontent.com/7279415/55102444-adbb7100-50c6-11e9-9bf9-c4c7407478ec.png)

[entertainment.zip](https://github.com/Templarian/MaterialDesign/files/3014757/entertainment.zip)

**Comment by Templarian** [comment]
These are nice. Can you extend the `-off` slack to go `1dp` further in both directions. It would probably look nicer instead of cutting off at the corner of the monitor.

First one might be the best, but will look closer as they are added.

**Comment by PeterShaggyNoble** [comment]
See also Google's `google_home_devices` icon from their extended set. Could've sworn we already had an open issue for it.

![google-home-devices](https://user-images.githubusercontent.com/15157491/55103724-ee17f080-50c0-11e9-8175-842d2017dc1c.png)

**Comment by Templarian** [comment]
Agreed we can probably just add this with the `-off` using the stock.

`monitor-speaker` / `monitor-speaker-off` to keep the naming consistent.

**Comment by boehan** [comment]
Couldn't find any official google source, only this one: https://petershaggynoble.github.io/MDI-Sandbox/extended/
Added an `-off` version, but the icon is all in all slightly misaligned and doesn't really follow the 2px guideline. If this is an official icon or you don't care that much, I won't either. Nevertheless, I created another alternative version.
![monitor-speaker-off](https://user-images.githubusercontent.com/7279415/55111094-dd27a900-50d9-11e9-9784-c5a8b1e9bc3e.png)
[monitor-speaker.zip](https://github.com/Templarian/MaterialDesign/files/3015230/monitor-speaker.zip)
Variant:
![monitor-speaker_1](https://user-images.githubusercontent.com/7279415/55111131-f03a7900-50d9-11e9-8160-2d2e28e3550a.png)
[monitor-speaker_1.zip](https://github.com/Templarian/MaterialDesign/files/3015232/monitor-speaker_1.zip)

**Comment by goyney** [comment]
The one from the extended set does not match our current `monitor` variations; the base is different. We need to match our current style when adding these.

**Comment by goyney** [comment]
[![monitor-speaker](https://materialdesignicons.com/icon/monitor-speaker)](https://materialdesignicons.com/icon/monitor-speaker)[![monitor-speaker-off](https://materialdesignicons.com/icon/monitor-speaker-off)](https://materialdesignicons.com/icon/monitor-speaker-off)
