### ISSUE TITLE
Blockchain Icon

### ISSUE THREAD

**Issue by XoXs** [Templarian/MaterialDesign#4079]

**Comment by MrGrigri** [comment]
This was my first thought of a `blockchain` icon; a `link-lock` icon.

[![link-lock.zip](https://user-images.githubusercontent.com/4528551/55175190-6d9ad380-5144-11e9-9c34-55e0160e2068.png)](https://github.com/Templarian/MaterialDesign/files/3019121/link-lock.zip)

**Comment by goyney** [comment]
[![link-lock](https://materialdesignicons.com/icon/link-lock)](https://materialdesignicons.com/icon/link-lock)
