### ISSUE TITLE
hand service

### ISSUE THREAD

**Issue by klawdyo** [Templarian/MaterialDesign#4080]
An icon to waiter like this
![image](https://user-images.githubusercontent.com/100168/55194610-f76c9000-5188-11e9-9ac2-68e556981a63.png)

**Comment by PeterShaggyNoble** [comment]
We have the `room-service` icon, which should cover this - we never have been able to figure out whether Google intended it to be a desk bell or a covered tray!

**Comment by goyney** [comment]
This has been request [several](https://github.com/Templarian/MaterialDesign/issues/2761) [times](https://github.com/Templarian/MaterialDesign/issues/1580) [before](https://github.com/Templarian/MaterialDesign/issues/1546) and we have `room-service` and `room-service-outline`.

There is no way we'll ever get the `room-service` bell/tray *and* a hand into a single icon.
