### ISSUE TITLE
Surface area / volume icons

### ISSUE THREAD

**Issue by jjjuho** [Templarian/MaterialDesign#4082]
Theres a need for surface area and volume icons describing basicly m2 and m3, not in a letter form but in icon form

**Comment by Templarian** [comment]
Note for us: We need to add a tag for Chemistry.

**Comment by Louistwee** [comment]
![image](https://user-images.githubusercontent.com/27563848/55865253-45689700-5b7e-11e9-8466-9b67a8d907e5.png)

[m^2.txt](https://github.com/Templarian/MaterialDesign/files/3062903/m.2.txt)

**Comment by goyney** [comment]
See: https://github.com/Templarian/MaterialDesign/issues/3877

**Comment by PeterShaggyNoble** [comment]
Would `square-outline` and `cube-outline` be understood in context?

**Comment by goyney** [comment]
[![texture-box](https://materialdesignicons.com/icon/texture-box)](https://materialdesignicons.com/icon/texture-box)
