### ISSUE TITLE
AdGuard

### ISSUE THREAD

**Issue by MiPiGamer** [Templarian/MaterialDesign#4083]
I was wondering if there was a way for the AdGuard icon to be added? It would be very beneficial for the HA community.
Example:
![8361145](https://user-images.githubusercontent.com/13185170/55281233-e26a3b00-5307-11e9-942e-6b33b60be76b.png)

**Comment by pravynandas** [comment]
Here is my sample work. Please review and suggest in case of any correction. The colors are original from the above example, however they look little dull in this sample. Once design is approved I think we can color correct it.

Fairly new to the community, so please guide me in case of errors.

![adguard](https://user-images.githubusercontent.com/4099637/55438753-82c29880-5570-11e9-954a-fd4143b7fc08.png)

**Comment by Templarian** [comment]
@pravynandas We're in the process of consolidating the brand icons we're including. At this time this brand falls outside of the scope. We're moving to an approach of complimenting our icons with the [Simple Icons](https://github.com/simple-icons/simple-icons) brand icons.

You can open an issue in their repo if the icon doesn't already exist.

In the coming weeks we'll be updating some of our guidelines and you may see some existing brand icons disappear in the `4.0.0` release (not all, just more niche ones that exist in Simple Icons).

**Comment by pravynandas** [comment]
Thanks for the note @Templarian . It makes lot a sense to group brand icons under Simple Icons umbrella. Since this is one of the recent open issues to which no body responded so I thought I can quickly jump and see what I can do.

Let me know if there is anything in specific I can contribute to this community, like pending icons, corrections etc.,

**Comment by Templarian** [comment]
We've realized it takes too much of our time updating brands in each release and that time could go toward more unique utility/action/symbol icons.

@pravynandas One thing you can do is if you use a search term and see no icons, but an icon exists let us know what you searched for and what you expected. No issue is too small to let us know an Alias is missing. This can greatly help others searching for icons. Similar for missing tags (which our third party apps use). These also are the easiest for our contributor team to close out.
