### ISSUE TITLE
check-box-outline displays an arabic character instead of icon

### ISSUE THREAD

**Issue by Young-JuL** [Templarian/MaterialDesign#4085]
I was trying to use 'check-box-outline' icon but the following shows up instead.

![image](https://user-images.githubusercontent.com/47011327/55297860-942f7600-5486-11e9-8b12-2c5a5f8331ef.png)

**Comment by goyney** [comment]
Could this be related to #4052?

**Comment by Young-JuL** [comment]
> Could this be related to #4052?

I don't think so.. I am not getting any errors.

**Comment by PeterShaggyNoble** [comment]
Is this the same problem reported in #4037?

**Comment by Templarian** [comment]
@Young-JuL What version are you using? Make sure it's not an older version not being copied over during a build also.

As no one else has reported a similar issue I'm thinking it's related to a build or an older asset reference.

**Comment by HoraceDiesel** [comment]
@Young-JuL , this is likely due to missing font files. Double check your in font folder, if the font files are there with correct names.

**Comment by Templarian** [comment]
Old issue but this is 99% due to old version or people installing the font locally and forgetting that browsers will try and use the local version.
