### ISSUE TITLE
Stellar's Lumens

### ISSUE THREAD

**Issue by rquattros** [Templarian/MaterialDesign#4086]
Requesting the Digital Currency Lumen from Stellar. Something along the lines of [this official icon](https://cdn-images-1.medium.com/max/800/0*vtLfy2F-tPdr63ud).

Thanks!

**Comment by PeterShaggyNoble** [comment]
Do you have any information on the usage of this currency? Our current criteria for adding cryptocurrencies is that they must have over 100k transactions per day.

Note as well that we are currently scaling back the number of brand icons we add and, instead, directing people to [Simple Icons](https://simpleicons.org/) ([repo](https://github.com/simple-icons/simple-icons)), which is a dedicated icon pack for brands.

We will, however, continue to add currency symbols (Lumens' can be found in [this blog post](https://www.stellar.org/blog/announcing-the-new-stellar-logo/), which would be beyond the scope of the Simple Icons project.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
