### ISSUE TITLE
Icon list with aliases

### ISSUE THREAD

**Issue by buutqn** [Templarian/MaterialDesign#4087]
I could not find a way to get the list of icons and aliases on the official website download.
Some JSON file with icon information, something like this below, would be very useful for enthusiasts like me.

`[{"name":"Icon Name", "class": "mdi-icon-class", "alias":["alias", "alias2", "alias3"]}]`

**Comment by Templarian** [comment]
There are two places after every release:

- https://cdn.materialdesignicons.com/3.5.95/meta.json
- https://github.com/Templarian/MaterialDesign-SVG/blob/master/meta.json

We ask that you not scrape the site or API's for this data between releases. Thanks!

We heavily encourage third parties to build tools and software with these repos and data.
