### ISSUE TITLE
clipboard-flow-outline

### ISSUE THREAD

**Issue by pravynandas** [Templarian/MaterialDesign#4088]
New to this community; Here is my first creation. Please review and suggest in case of any corrections needed. I used Microsoft Express Design 4 to redesign the 'clipboard-flow' icon to the outline version. Thanks all, it's a great community to work with.

![clipboard-flow-outline](https://user-images.githubusercontent.com/4099637/55434465-af24e780-5565-11e9-900a-79072d05be9b.png)

**Comment by MrGrigri** [comment]
There are a couple of things to consider. First off, we need a single compound path of the SVG...not just an image of the icon. Secondly, you can create a preview using our generator with said single compound path [here](http://dev.materialdesignicons.com/contribute/github). Thirdly, please look at other examples or styles first. There is a common `clipboard-outline` that we use, please use it. 

![clipboard-outline](https://materialdesignicons.com/icon/clipboard-outline)

**Comment by goyney** [comment]
[![clipboard-flow-outline](https://materialdesignicons.com/icon/clipboard-flow-outline)](https://materialdesignicons.com/icon/clipboard-flow-outline)
