### ISSUE TITLE
flickr

### ISSUE THREAD

**Issue by equinoxel** [Templarian/MaterialDesign#409]
- [x] flickr

**Comment by Templarian** [comment]
Flickr's logo in black and white is simply 2 circles with different opacity. I'm wondering if that will suffice.

![image](https://cloud.githubusercontent.com/assets/338885/8024439/85b48378-0cf9-11e5-80c9-dc5d38f54b4a.png)

That or I make it a double icon like PayPal requires... #297.

**Comment by equinoxel** [comment]
IMHO there are a several options you could do:
- circles with different opacity (I wonder how this will fare in a font)
- circles with the same opacity/color in a rounded square (like you have it), but then you'll have the option of 2 white circles in a filled black square or 2 circles in a white/transparent square
- circles with the same opacity (but without the square), like 
![flickr-icon-614x460](https://cloud.githubusercontent.com/assets/592506/8031309/9a671d38-0dcd-11e5-8a63-579303dd7001.png)

I'd go for just the two circles (either both filled black or one filled black and one empty/white with a black contour), but I'm not sure which variant would fit better with the other icons.

**Comment by Templarian** [comment]
A rough idea of how it will work in PayPal and Flickr. This won't go in until the next Webfont though, so I'll keep the issue open until then.

```css
.mdi-test::before {
    content: "\f---";
}
.mdi-test::after {
    content: "\f---";
    opacity: 0.6;
    position: absolute;
    left: 0;
}
```

```html
<i class="mdi-flickr"></i>
```

![flickr](https://cloud.githubusercontent.com/assets/338885/8049840/3babf180-0e2a-11e5-9150-5476f565972b.png) ![paypal](https://cloud.githubusercontent.com/assets/338885/8049847/54df6088-0e2a-11e5-98a0-a9d03dc3bae5.png)

(PayPal uses Above: opacity = 0.8; Below: opacity = 0.6)

**Comment by equinoxel** [comment]
looks very nice :) I'll look forward to the next release then!

**Comment by PeterShaggyNoble** [comment]
2 circles knocked out of the square would do the job, similar to FontAwesome: http://fortawesome.github.io/Font-Awesome/icon/flickr/

**Comment by PeterShaggyNoble** [comment]
Cheeky bump! ;)

**Comment by stevengliebe** [comment]
I'd like to see this as well.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48857858-e1d4fd00-ed87-11e8-9bd5-f8516957a5d1.png)
[flickr.zip](https://github.com/Templarian/MaterialDesign/files/2605181/flickr.zip)

**Comment by PeterShaggyNoble** [comment]
I revise my vote that we use the 2 circles on their own, it's what Flickr use for their favicon and it's also what [Simple Icons](https://simpleicons.org/?q=flickr) use (they're pretty strict on adhering to brand guidelines).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48858519-94f22600-ed89-11e8-8fb0-42eac63d5fb8.png)
[flickr.zip](https://github.com/Templarian/MaterialDesign/files/2605223/flickr.zip)

**Comment by Templarian** [comment]
[![flickr](https://materialdesignicons.com/icon/flickr)](https://materialdesignicons.com/icon/flickr)

🙃 ~3 Years later.

**Comment by minimaluminium** [comment]
Just downloaded the webfont v3.2.89 from the website, but it still doesn't include the Flickr icon. Is there any extra step?

**Comment by PeterShaggyNoble** [comment]
@minimaluminium, this icon will be available in the next release, coming soon. You can use the [history page](http://dev.materialdesignicons.com/history) to track the changes since the last release.
