### ISSUE TITLE
format-list-bulleted-square does not match other format-list icons

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#4090]
[![](https://materialdesignicons.com/icon/format-list-bulleted)](https://materialdesignicons.com/icon/format-list-bulleted)[![](https://materialdesignicons.com/icon/format-list-bulleted-square)](https://materialdesignicons.com/icon/format-list-bulleted-square)[![](https://materialdesignicons.com/icon/format-list-numbered)](https://materialdesignicons.com/icon/format-list-numbered)[![](https://materialdesignicons.com/icon/format-list-bulleted-type)](https://materialdesignicons.com/icon/format-list-bulleted-type)

It looks weird compared to the rest. I believe we should fix this so the shapes of the bulleted an square match the shapes from `format-list-bulleted-type`. Could maybe add a `format-list-bulleted-triangle` while we are at it?

**Comment by Templarian** [comment]
Definitely agree with this, noticed it when someone opened that `outline` issue the other day that we rejected. The spacing looks odd when these are put in a list of options.

**Comment by Templarian** [comment]
Tracking the triangle request here: #4097.

**Comment by davwheat** [comment]
Just another odd observation: why is the Triangle ~4.5dp tall vs the other shapes at 4dp

**Comment by MrGrigri** [comment]
@davwheat, just to visually balance the equilateral triangle.

**Comment by MrGrigri** [comment]
[![format-list-bulleted-square.zip](https://user-images.githubusercontent.com/4528551/55748128-170e7e80-59fb-11e9-9c10-7992dbfb0416.png)](https://github.com/Templarian/MaterialDesign/files/3055799/format-list-bulleted-square.zip)

**Comment by Templarian** [comment]
Updated. 😃

**Comment by JamesCoyle** [comment]
I feel like the circles and numbers should be one to the right to match the other two and the circles should be 4dp diameter to match the size of the squares.
