### ISSUE TITLE
language-fortran

### ISSUE THREAD

**Issue by kc9jud** [Templarian/MaterialDesign#4091]
Just an "F", analogous to https://materialdesignicons.com/icon/language-c and https://materialdesignicons.com/icon/language-cpp

**Comment by Templarian** [comment]
I think this is within our ability to add. While it's a bit niche I think we should have an icon to represent all the common programming languages.

**Comment by PeterShaggyNoble** [comment]
There is no official logo or icon for Fortran; @kc9jud do you know if there is a standard icon used within the Fortran community?

**Comment by kc9jud** [comment]
I don't think so... any logos are based on the cover design of the 1956 IBM manual for the original FORTRAN. See https://github.com/exercism/meta/issues/46 and https://en.wikipedia.org/wiki/Fortran for reference.

**Comment by kc9jud** [comment]
Also, see the design at http://fortranwiki.org/fortran/show/HomePage

**Comment by Templarian** [comment]
[![language-fortran](https://materialdesignicons.com/icon/language-fortran)](https://materialdesignicons.com/icon/language-fortran)

@kc9jud Adding this as a placeholder. If they ever decide on a logo let us know and we'll replace this one.

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/66974704-4e16c880-f0df-11e9-81d8-0c076c6adbbb.png)
I recognise the Clarendon font, but I tried to redraw the F to use 2dp strokes, fit on the grid, and use circles and ellipses for the corners for a more consistent feel with the rest of the icons.

**Comment by Templarian** [comment]
@JapanYoshi Can you attach the svg or if you join slack I can give you the steps to update it in the system. Ping me on twitter if you need the invite link again.

**Comment by JapanYoshi** [comment]
This should be optimal: 
d = ```m 5,4 v 2 h 1 c 0.554,0 1,0.446 1,1 v 10 c 0,0.554 -0.446,1 -1,1 H 5 v 2 h 9 v -2 h -2 c -0.554,0 -1,-0.446 -1,-1 v -4 h 2 c 0.554,0 1,0.446 1,1 v 2 h 2 V 8 h -2 v 2 c 0,0.554 -0.446,1 -1,1 H 11 V 6 h 5 c 1.108,0 2,1.338 2,3 v 1 h 2 V 4 Z```

**Comment by Templarian** [comment]
Updated. You can use the admin to update your profile also.

https://dev.materialdesignicons.com/history

**Comment by JapanYoshi** [comment]
I don't know what you mean by that last part.

**Comment by Templarian** [comment]
@JapanYoshi Sent a message on twitter explaining it.
