### ISSUE TITLE
chart-tree

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4092]
This icon was found in Google Sheets with an 18x18 viewbox. I've recreated it with a 24x24 viewbox. 

[![image](https://user-images.githubusercontent.com/4528551/55574954-f2e53180-56ca-11e9-8041-2a81688870d4.png)](https://github.com/Templarian/MaterialDesign/files/3044680/chart-tree.zip)

**Comment by Templarian** [comment]
[![chart-tree](https://materialdesignicons.com/icon/chart-tree)](https://materialdesignicons.com/icon/chart-tree)
