### ISSUE TITLE
Update markdown & add markdown-outline

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4093]
The official Markdown icons can be found in [this repo](https://github.com/dcurtis/markdown-mark).

**Comment by MichaelPriebe** [comment]
![markdown@3x](https://user-images.githubusercontent.com/5238952/56979037-d8299f80-6b46-11e9-9990-075082586732.png)
![markdown@2x](https://user-images.githubusercontent.com/5238952/56979043-da8bf980-6b46-11e9-9aba-3ad7e756caf3.png)
![markdown](https://user-images.githubusercontent.com/5238952/56979061-e4adf800-6b46-11e9-85b5-5a75ced79963.png)
```svg
<path d="M3,6H21a1,1,0,0,1,1,1V17a1,1,0,0,1-1,1H3a1,1,0,0,1-1-1V7A1,1,0,0,1,3,6Zm4,9V11.5l2,2.26471L11,11.5V15h2V9H11L9,11.25,7,9H5v6Zm12-3H17.25V9h-2v3H13.5l2.75,3.25Z"/>
```

![markdown-outline@3x](https://user-images.githubusercontent.com/5238952/56979116-014a3000-6b47-11e9-8820-af834949bd9b.png)
![markdown-outline@2x](https://user-images.githubusercontent.com/5238952/56979118-027b5d00-6b47-11e9-8a5c-e8180d85ddce.png)
![markdown-outline](https://user-images.githubusercontent.com/5238952/56979138-0c9d5b80-6b47-11e9-82b0-a4b7a7face46.png)
```svg
<path d="M3,6H21a1,1,0,0,1,1,1V17a1,1,0,0,1-1,1H3a1,1,0,0,1-1-1V7A1,1,0,0,1,3,6ZM3,17H21V7H3Zm4-2V11.5l2,2.26471L11,11.5V15h2V9H11L9,11.25,7,9H5v6Zm12-3H17.25V9h-2v3H13.5l2.75,3.25Z"/>
```

**Comment by goyney** [comment]
Considering this is a development tool, it meets the criteria to still be added, [despite our recent announcement about brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/58273316-6d8f0c80-7d5e-11e9-8ea4-b7431b9e4798.png)![image](https://user-images.githubusercontent.com/1015040/58273324-74b61a80-7d5e-11e9-907e-a1ef22bdb1e1.png)

[markdown.zip](https://github.com/Templarian/MaterialDesign/files/3213440/markdown.zip)

**Comment by goyney** [comment]
[![markdown](https://materialdesignicons.com/icon/markdown)](https://materialdesignicons.com/icon/markdown)[![markdown-outline](https://materialdesignicons.com/icon/markdown-outline)](https://materialdesignicons.com/icon/markdown-outline)
