### ISSUE TITLE
No Line App Icon

### ISSUE THREAD

**Issue by JPMulder** [Templarian/MaterialDesign#4095]
Hi
I think with 600 million users I think this icon should be available.
https://expandedramblings.com/index.php/line-statistics/
much appreciated

**Comment by Templarian** [comment]
Thought we had an issue for this opened at one point.

**Comment by Templarian** [comment]
Duplicate of #1481.

**Comment by JPMulder** [comment]
In the mean time I've created a webfont with an svg here https://glyphter.com/ for those who want to create the line app icon urgently
