### ISSUE TITLE
Meditate

### ISSUE THREAD

**Issue by nellering** [Templarian/MaterialDesign#4096]
meditate

**Comment by Templarian** [comment]
Until we can think of a design, the `metronome` icon might work. Not how many correlate the two though, so might not work.

Do you have an examples of what you're looking for. The smaller size might make this one difficult.

**Comment by nellering** [comment]
Maybe something like this?

[https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjl7ZTU-7vhAhWi7IMKHa-UB_EQjRx6BAgBEAU&url=https%3A%2F%2Fwww.iconfinder.com%2Ficons%2F2565220%2Fcalm_meditate_meditation_yoga_icon&psig=AOvVaw2J43nxJd3ydo4frtllhui-&ust=1554657196822153](url)

or this:

[https://www.google.com/url?sa=i&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjqtdDh-7vhAhWCr4MKHcOYAmEQjRx6BAgBEAU&url=%2Furl%3Fsa%3Di%26source%3Dimages%26cd%3D%26ved%3D%26url%3Dhttps%253A%252F%252Fthenounproject.com%252Fterm%252Fmeditate%252F127690%252F%26psig%3DAOvVaw2J43nxJd3ydo4frtllhui-%26ust%3D1554657196822153&psig=AOvVaw2J43nxJd3ydo4frtllhui-&ust=1554657196822153](url)

Thanks in advance!

**Comment by goyney** [comment]
Duplicate of https://github.com/Templarian/MaterialDesign/issues/176.
