### ISSUE TITLE
format-list-triangle

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#4097]
Format list triangle should be added so we have a unique way to represent the various bullet types.

**Comment by MrGrigri** [comment]
[![format-list-triangle.zip](https://user-images.githubusercontent.com/4528551/55747876-859f0c80-59fa-11e9-97a3-e2a0a820fa6c.png)](https://github.com/Templarian/MaterialDesign/files/3055784/format-list-triangle.zip)

**Comment by Templarian** [comment]
Added! 😃
