### ISSUE TITLE
remote-off

### ISSUE THREAD

**Issue by gurupras** [Templarian/MaterialDesign#4101]
Could we have a `remote-off` icon with a simple diagonal line over the current remote icon?
It would also be great if the same were added to the `remote-variant` icon as suggested in #2445

**Comment by idevo89** [comment]
<a href="https://github.com/Templarian/MaterialDesign/files/3058701/remote-off.zip"><img src="https://user-images.githubusercontent.com/48392636/55797235-30cbc680-5acc-11e9-85bb-8d53bdd6618d.png" alt="remote-off.zip" style="max-width:100%;"></a>

**Comment by idevo89** [comment]
<a href="https://github.com/Templarian/MaterialDesign/files/3060292/remote-variant-off.zip"><img src="https://user-images.githubusercontent.com/48392636/55822369-bd43ac80-5aff-11e9-8497-4c959c41b595.png" alt="remote-variant-off.zip" style="max-width:100%;"></a>

**Comment by Templarian** [comment]
[![remote-off](https://materialdesignicons.com/icon/remote-off)](https://materialdesignicons.com/icon/remote-off) [![remote-tv-off](https://materialdesignicons.com/icon/remote-tv-off)](https://materialdesignicons.com/icon/remote-tv-off)
