### ISSUE TITLE
delete-off delete-alert

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4102]
please consider adding these 2 icons, we need for signaling trash collection days.

delete-alert for days trash is collected,
delete-off for days no trash is collected.

now using delete-outline and delete-restore, bt they are not quite correct.
thanks for considering

**Comment by idevo89** [comment]
<a href="https://github.com/Templarian/MaterialDesign/files/3059097/delete-alert-outline.zip"><img src="https://user-images.githubusercontent.com/48392636/55802870-64f9b400-5ad9-11e9-8645-fd20e1fa33d6.png" alt="delete-alert-outline.zip" style="max-width:100%;"></a>

**Comment by idevo89** [comment]
<a href="https://github.com/Templarian/MaterialDesign/files/3059117/delete-off-outline.zip"><img src="https://user-images.githubusercontent.com/48392636/55803049-db96b180-5ad9-11e9-97e0-fa08ac8ebf1a.png" alt="delete-off-outline.zip" style="max-width:100%;"></a>

**Comment by Mariusthvdb** [comment]
Perfect ! Thank you v M!

**Comment by idevo89** [comment]
![image](https://user-images.githubusercontent.com/48392636/55818887-f710b500-5af7-11e9-80a7-75514cadce0b.png)![image](https://user-images.githubusercontent.com/48392636/55818977-23c4cc80-5af8-11e9-9ba9-62c23465afd9.png)
[delete.zip](https://github.com/Templarian/MaterialDesign/files/3060103/delete.zip)

**Comment by MrGrigri** [comment]
Thanks

**Comment by Mariusthvdb** [comment]
Could the alert variant be done with an open lid also?

**Comment by MrGrigri** [comment]
I would vote against that. As `delete-empty` is a one-off state and shouldn't gain modifiers. There are many ways to symbolize empty trash, i.e. `delete-outline`.

**Comment by Mariusthvdb** [comment]
while I understand what you're saying here, I would think an opened trashcan with an alert would visually signal it's an alert (!) day for having the trash picked up, opened (hence the request) and deleted....

If it would be against guidelines, no issue, simply would have thought it to be of (extra) added value.
appreciate the discussion, as always ;-)
thanks!

**Comment by Templarian** [comment]
Does `delete-empty-outline` visually look odd or am I just looking at it too long?

![image](https://user-images.githubusercontent.com/338885/57057587-87fa2c80-6c6f-11e9-89fb-85ae905513a4.png)

**Comment by Mariusthvdb** [comment]
well, no, not to me, if that's of any relevance..
maybe try the lid completely Off, next to the bin, just like the exclamation mark in the example above?

**Comment by MrGrigri** [comment]
@Templarian, I believe you're just looking too long/hard at it.

@Mariusthvdb, If we move the lid to the side, then it could be confused with the newly designed `delete-alert` icon.

**Comment by goyney** [comment]
[![delete-off](https://materialdesignicons.com/icon/delete-off)](https://materialdesignicons.com/icon/delete-off)[![delete-off-outline](https://materialdesignicons.com/icon/delete-off-outline)](https://materialdesignicons.com/icon/delete-off-outline)
[![delete-alert](https://materialdesignicons.com/icon/delete-alert)](https://materialdesignicons.com/icon/delete-alert)[![delete-alert-outline](https://materialdesignicons.com/icon/delete-alert-outline)](https://materialdesignicons.com/icon/delete-alert-outline)
