### ISSUE TITLE
Please add More Login/logout Icons

### ISSUE THREAD

**Issue by ShahMoiz** [Templarian/MaterialDesign#4104]
In Material Community Icons there are only two icons available for Login/Logout. Can you added more icons on Login/Logout ?

**Comment by goyney** [comment]
What do you propose? What value does providing other icons gain us?

**Comment by MrGrigri** [comment]
See #747 as a possible alternative

**Comment by ShahMoiz** [comment]
My Purpose is Selecting Login/Logout Icon but the Problem is there is no choice for selecting these Icons

There are Only Two Almost Same Icon for Login 
![image](https://user-images.githubusercontent.com/15573188/55889004-39241000-5b65-11e9-9d6c-6eabc16d9746.png)
also,
Two almost same Icon for Logout
![image](https://user-images.githubusercontent.com/15573188/55889112-6bce0880-5b65-11e9-83d2-e571a045550c.png)

**Comment by goyney** [comment]
That really doesn't clarify anything. Why won't those icons work for you? What are you proposing as other ideas/approaches for them?

**Comment by ShahMoiz** [comment]
These icons work for me but i suggest you to add more verity on

**Comment by MrGrigri** [comment]
Thanks for those suggestions, but they are already included in this project. (we could add an alias to `account-plus` as login). I'm going to close this issue out until there is a better suggestion.

![account-plus](https://materialdesignicons.com/icon/account-plus)
