### ISSUE TITLE
Fullscreen vertical

### ISSUE THREAD

**Issue by terreng** [Templarian/MaterialDesign#4105]
As seen on the YouTube app, for vertical videos. 

![image](https://user-images.githubusercontent.com/11605395/55921974-081efc00-5bb4-11e9-871b-6f71ea89ba47.png)
[fullscreen-vertical.svg](https://github.com/terreng/samples/blob/master/fullscreen-vertical.svg)

**Comment by goyney** [comment]
I don't think this provides any value that our current `fullscreen` doesn't.

**Comment by terreng** [comment]
YouTube uses it to demonstrate that the video is getting cut off because it is to tall, and that entering fullscreen mode won't change the device's orientation to landscape. I needed it for a project, saw it was missing, and decided to post it here, and I completely understand if it is deemed unnecessary.

**Comment by davwheat** [comment]
I think this should be added. As @terreng stated, it indicated more than just 'fullscreen' but also the video format (portrait) and that the device orientation won't change.

It won't *hurt* anyone by adding it and some may find it useful, just like terreng.

**Comment by goyney** [comment]
Closing because the `Consider Closing` tag was added more than 30 days ago.
