### ISSUE TITLE
alarm-note(-off)

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4106]
please consider adding an alarm-radio and alarm-radio-off variant.

been looking for a suggestion for this, especially when using googlehome and alexa devices playing radio at wakeup.
Maybe the small music note on 'playlist-music' could be added to the alarm and alarm-off?

**Comment by MrGrigri** [comment]
Would something like this work?

I reflected the clock hands vertically so it would make more sense and not be cut-off by the note.

![image](https://user-images.githubusercontent.com/4528551/55968189-c6846480-5c38-11e9-83af-3a0a78607143.png) ![image](https://user-images.githubusercontent.com/4528551/55968216-d3a15380-5c38-11e9-99f3-3d100f12e77c.png)

---
#### Files
[alarm-note.zip](https://github.com/Templarian/MaterialDesign/files/3069268/alarm-note.zip)

**Comment by JamesCoyle** [comment]
The hands seem off center to me.

**Comment by MrGrigri** [comment]
Updated. The hands are 1.5x wide and aligned to the grid on the left. So I aligned them to the right...I believe that does look better.

**Comment by Templarian** [comment]
[![alarm-note](https://materialdesignicons.com/icon/alarm-note)](https://materialdesignicons.com/icon/alarm-note) [![alarm-note-outline](https://materialdesignicons.com/icon/alarm-note-outline)](https://materialdesignicons.com/icon/alarm-note-outline)
