### ISSUE TITLE
Jewellery Icon

### ISSUE THREAD

**Issue by KushalKatta** [Templarian/MaterialDesign#4110]
Please add some jewellery related icons.

Maybe something like this: 

https://d1yn1kh78jj1rr.cloudfront.net/image/preview/rnp9KOKvfjdviiioz/storyblocks-jewelry-icon-set-simple-set-of-jewelry-vector-icons-for-web-design-isolated-on-white-background_Sh2RFbhiX_SB_PM.jpg

**Comment by goyney** [comment]
Open request for necklace: https://github.com/Templarian/MaterialDesign/issues/2165

`ring` is already included:
[![ring](https://materialdesignicons.com/icon/ring)](https://materialdesignicons.com/icon/ring)

`diamond-stone` would be another already included:
[![diamond-stone](https://materialdesignicons.com/icon/diamond-stone)](https://materialdesignicons.com/icon/diamond-stone)

I don't really think there is much more to add.
