### ISSUE TITLE
download-off

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4111]
We recently had a need for an off variant of the `download` icon.

![image](https://user-images.githubusercontent.com/1015040/56252732-39ea0400-6087-11e9-9a43-b81703ef7d25.png)

[download-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/3087419/download-off.svg.zip)

**Comment by PeterShaggyNoble** [comment]
May as well add one for upload while we're at it.

**Comment by goyney** [comment]
[![download-off](https://materialdesignicons.com/icon/download-off)](https://materialdesignicons.com/icon/download-off)[![download-off-outline](https://materialdesignicons.com/icon/download-off-outline)](https://materialdesignicons.com/icon/download-off-outline)
[![upload-off](https://materialdesignicons.com/icon/upload-off)](https://materialdesignicons.com/icon/upload-off)[![upload-off-outline](https://materialdesignicons.com/icon/upload-off-outline)](https://materialdesignicons.com/icon/upload-off-outline)
