### ISSUE TITLE
Ellipse and Polygon

### ISSUE THREAD

**Issue by hillin** [Templarian/MaterialDesign#4113]
We now have `rectangle`, `circle`, `*gon`s and `*gram`s, but still lack simple shape icons for `ellipse` and `polygon` (yes I'm aware there are `vector-ellipse` and `vector-polygon`, but with the control points they are less applicable).

**Comment by MrGrigri** [comment]
We already have `pentagon` and `pentagon-outline` that could be used to symbolize a polygon. Simply removing the handles on the `vector-polygon` didn't work.

[![image](https://user-images.githubusercontent.com/4528551/56427526-77ae7e80-6279-11e9-8d82-fdca347f0fbd.png)](https://github.com/Templarian/MaterialDesign/files/3098324/shape-ellipse.zip)

**Comment by hillin** [comment]
Yes in some context `pentagon` can be used to represent a polygon, but it implies the polygon has to be convex. It would be great if we can have a dedicated polygon icon with both convex and concave corners.

**Comment by Templarian** [comment]
Added `ellipse` and `ellipse-outline`. `shape-polygon-plus` can probably be use.
