### ISSUE TITLE
surgical

### ISSUE THREAD

**Issue by kipkilimo** [Templarian/MaterialDesign#4115]

**Comment by PeterShaggyNoble** [comment]
This is very vague. Could you add more detail as to what you're looking for, please?

**Comment by goyney** [comment]
Possible duplicate of https://github.com/Templarian/MaterialDesign/issues/864.

**Comment by goyney** [comment]
Looks like the OP put this link in the issue template comment:

> https://www.svgrepo.com/show/186994/scalpel.svg

The request for a scalpel is definitely a duplicate of #864. Closing.
