### ISSUE TITLE
coat-rack

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4116]
Need for the room in the house to store the coats, shoes etcetera, Id love an icon for wardrobe.

![iu-12](https://user-images.githubusercontent.com/33354141/56530576-e1b57500-6552-11e9-9039-0049405c1903.png)
![iu-13](https://user-images.githubusercontent.com/33354141/56530577-e1b57500-6552-11e9-8297-050b2083f19e.png)

to give you an idea of what could be used.
could also imagine the human-male-female to be adapted: takeout the bodyparts, add the stick in the middle ;-)

**Comment by MrGrigri** [comment]
We already have a `hanger` icon:

![hanger](https://materialdesignicons.com/icon/hanger)

**Comment by Templarian** [comment]
There is already an issue for wardrobe #3169 (with a design). Renaming this to `coat-rack`.

I'm thinking `garderobe` is going to be too difficult to show at our small size.

**Comment by Mariusthvdb** [comment]
sorry, missed the hanger.
#3169 was my own request, but focussed on an real cabinet. this is more geared to indicating the place/room where the coats are stored. 
Coat-rack is better named, and would be really nice indeed. Would even the first pic I provided as an example be too complicated to show? Wouldn't need all the rounded ends if that would help.

or maybe like this:
![iu-2](https://user-images.githubusercontent.com/33354141/56633805-f6cbfa00-665f-11e9-8358-ef907c9db8e8.jpeg)
![iu-3](https://user-images.githubusercontent.com/33354141/56633806-f6cbfa00-665f-11e9-9dbe-56b1a24ee631.jpeg)
![iu-4](https://user-images.githubusercontent.com/33354141/56633808-f6cbfa00-665f-11e9-9bde-80637f7e365f.jpeg)

**Comment by MrGrigri** [comment]
Would this suffice? 

[![coat-rack.zip](https://user-images.githubusercontent.com/4528551/56664607-a192e700-6665-11e9-8c77-fb334eab6b5f.png)](https://github.com/Templarian/MaterialDesign/files/3112562/coat-rack.zip)

**Comment by Mariusthvdb** [comment]
ha, cool!
if you ask me, the foot could be a bit wider, and the top could simply be the end of the vertical stick

these changes might give you room for a second branch on each side, especially if you'd make them straight, and maybe thinner?

anyways, thanks for your time and effort, much appreciated!

**Comment by goyney** [comment]
[![coat-rack](https://materialdesignicons.com/icon/coat-rack)](https://materialdesignicons.com/icon/coat-rack)
