### ISSUE TITLE
OpenType features icons

### ISSUE THREAD

**Issue by Leisvan** [Templarian/MaterialDesign#4117]
It would be great if we had icons for managing OpenType features such as Ligatures, Stylistic Sets, etc. For example, to use it in an app that toggles on/off font features for ademo texts.
Thanks

**Comment by JamesCoyle** [comment]
Can you provide some examples of what these could look like. I think it would help to get a better idea of what is needed to fulfill this issue.

**Comment by goyney** [comment]
Closing this issue because no additional information was provided. If you still have a need for the icon(s) requested, please comment here with what you're looking for and we'll see what we can do. Thanks!
