### ISSUE TITLE
Contact phone

### ISSUE THREAD

**Issue by rardoz** [Templarian/MaterialDesign#4118]
I'm not able to find the contact phone icon from the material icon set:

https://material.io/tools/icons/?search=contact&icon=contact_phone&style=baseline

Could we add this in?

**Comment by Templarian** [comment]
[![contact-phone](https://materialdesignicons.com/icon/contact-phone)](https://materialdesignicons.com/icon/contact-phone) [![contact-phone-outline](https://materialdesignicons.com/icon/contact-phone-outline)](https://materialdesignicons.com/icon/contact-phone-outline) [![contact-mail-outline](https://materialdesignicons.com/icon/contact-mail-outline)](https://materialdesignicons.com/icon/contact-mail-outline)
