### ISSUE TITLE
gas-station-outline

### ISSUE THREAD

**Issue by farahfilho** [Templarian/MaterialDesign#4119]
https://material.io/tools/icons/?search=gas&icon=local_gas_station&style=outline

Is it possible to add this icon and the new ones from all the different themes?

**Comment by farahfilho** [comment]
Also this one:
https://material.io/tools/icons/?icon=account_balance&style=outline

**Comment by JamesCoyle** [comment]
Please create different issues for different icons so it is easier for us to track. We are currently only focusing on the filled and outline variants for the moment but we may start to support different styles in the future. We still have a lot of filled and outlined icons to add so if you see any that we have missed please open up new issues so we can get them added.

Thank you for your suggestion!

**Comment by Templarian** [comment]
[![gas-station-outline](https://materialdesignicons.com/icon/gas-station-outline)](https://materialdesignicons.com/icon/gas-station-outline) [![bank-outline](https://materialdesignicons.com/icon/bank-outline)](https://materialdesignicons.com/icon/bank-outline)
