### ISSUE TITLE
Shape icon - circle with inset square

### ISSUE THREAD

**Issue by johnnylambada** [Templarian/MaterialDesign#412]

**Comment by Templarian** [comment]
Can you illustrate this really quick? I think i get the idea, but want to make sure we're on the same page.

**Comment by johnnylambada** [comment]
Similar to this:
![image](https://cloud.githubusercontent.com/assets/180409/7995128/2f439f7a-0ac8-11e5-80e9-a145b4aef5e5.png)

**Comment by CoDEmanX** [comment]
A lot of icons are composites, but they often require some sort of subtraction to make overlapping elements work. It's fine for non-overlapping of course.

**Comment by PeterShaggyNoble** [comment]
I believe `shape` and/or `shape-outline` should fulfil this request so going to close it out.

[![shape](https://user-images.githubusercontent.com/15157491/36682144-4330f7b4-1b12-11e8-805c-1d880116000b.png)](https://materialdesignicons.com/icon/shape) [![shape-outline](https://user-images.githubusercontent.com/15157491/36682189-628d995a-1b12-11e8-8325-d8c6c7100273.png)](https://materialdesignicons.com/icon/shape-outline)
