### ISSUE TITLE
Create a Helm icon

### ISSUE THREAD

**Issue by fullstacktester** [Templarian/MaterialDesign#4120]
Can an icon be created for Helm charts.

Helm charts are used to deploy applications into a kubernetes cluster.
More info on Helm can be found on their website: https://helm.sh/

This is their logo:
![image](https://user-images.githubusercontent.com/17121161/56640991-3698de80-666c-11e9-9e37-9934cd26343d.png)

**Comment by goyney** [comment]
We've started to be more careful about adding new brand icons to this library. Regardless, this is too niche to be included here. You might consider requesting this icon over at [SimpleIcons](https://simpleicons.org/), a library dedicated to brand icons.

**Comment by fullstacktester** [comment]
@goyney Thanks for the quick response. I fully understand your position. Just to let you know the reason for my request is that Concourse CI has allowed incorporating your icons into their pipelines (https://concourse-ci.org/resources.html#resource-icon). I don't know if you were aware of this but it could lead to further requests.

**Comment by Templarian** [comment]
@fullstacktester Interesting, first I've seen or heard about this update. Always great when other open source projects integrate the icons, but I do find it funny how we're usually the last the find out. 🤣

I'll be sure to reach out to them to make sure they are okay with our release schedule and plans going forward about brand icons.
