### ISSUE TITLE
map-parcel

### ISSUE THREAD

**Issue by m4dd** [Templarian/MaterialDesign#4121]
If possible, add a "map-parcel" icon similar to this one:
![image](https://user-images.githubusercontent.com/49964797/56700967-e8ff8e80-66ca-11e9-9a27-909cdce1ec4a.png)

Also, would be great to see an open source kit like the ESRI Calcite icons or any Web GIS icons.
https://developers.arcgis.com/javascript/latest/guide/esri-icon-font/

**Comment by MrGrigri** [comment]
Going to close this one out due to inactivity and lack of response.
