### ISSUE TITLE
domain-plus

### ISSUE THREAD

**Issue by Bjego** [Templarian/MaterialDesign#4123]
Hey guys,

I'm missing a nicely add domain Icon

Something like this

![image](https://user-images.githubusercontent.com/12625568/56727366-daf45100-6750-11e9-845f-098db939d610.png)

**Comment by MrGrigri** [comment]
Might as well add the `-remove` modifier as well. The `-minus` modifier looked like an extension to the building foundation, therefore it will not be added. All though, with these, I believe that the cutout might be better 1px larger. Thoughts?

![image](https://user-images.githubusercontent.com/4528551/56745605-ebe49880-6737-11e9-8f04-c05ca84f5b2d.png) ![image](https://user-images.githubusercontent.com/4528551/56745729-22baae80-6738-11e9-8f5f-15e4118f6b50.png)

---
#### Files
[domain-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/3117524/domain-modifiers.zip)

**Comment by Bjego** [comment]
Hey Guys, that was quick! Thanks a Lot!

**Comment by goyney** [comment]
[![domain-plus](https://materialdesignicons.com/icon/domain-plus)](https://materialdesignicons.com/icon/domain-plus)[![domain-remove](https://materialdesignicons.com/icon/domain-remove)](https://materialdesignicons.com/icon/domain-remove)
