### ISSUE TITLE
Overline Icon

### ISSUE THREAD

**Issue by CodeDoctorDE** [Templarian/MaterialDesign#4124]
A overline icon.

There are a [outline icon](https://materialdesignicons.com/icon/format-underline) but not a overline icon.

A image for this:
![image](https://user-images.githubusercontent.com/20452814/56865581-15b7ec80-69d0-11e9-98c6-939ba4a4afdc.png)

**Comment by MichaelPriebe** [comment]
![3x](https://user-images.githubusercontent.com/5238952/56868201-56f2d100-69bd-11e9-849a-744dc8334e95.png)
![2x](https://user-images.githubusercontent.com/5238952/56868212-696d0a80-69bd-11e9-8734-a1a251e9e08c.png)
![1x](https://user-images.githubusercontent.com/5238952/56868204-5d814880-69bd-11e9-832e-2dd7354b778e.png)

Combined format-color-text and format-underline.

```svg
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path d="M5,5H19V3H5V5M9.62,16,12,9.67,14.37,16M11,7,5.5,21H7.75l1.12-3h6.25l1.13,3H18.5L13,7Z"/>
</svg>
```

**Comment by Templarian** [comment]
[![format-overline](https://materialdesignicons.com/icon/format-overline)](https://materialdesignicons.com/icon/format-overline)

@MichaelPriebe Assigned to the shared contributor account for now. Let me know when you hit 5 and I'll assign it over to a contributor account.
