### ISSUE TITLE
Dock Action Icons

### ISSUE THREAD

**Issue by DubeauJL** [Templarian/MaterialDesign#4126]
Hi,

I was unable to find dock action icons. 
Funny, because the developer tools console has the icons... maybe google didn't make them available?

Screenshot below of what I'm looking for.

![dockIcons](https://user-images.githubusercontent.com/24304306/56926397-c2ad6a80-6a9f-11e9-8edd-3897b74741b4.png)

- Undock in a separate window (this one had pretty similar icons within the list)
- Dock Bottom
- Dock Left
- Dock Right

**Comment by MrGrigri** [comment]
Here you go. I know that those are "Google's", but they are not Material. So I created these to be Material.

![image](https://user-images.githubusercontent.com/4528551/56969809-2b89f680-6b23-11e9-860c-6df373b279ea.png) ![image](https://user-images.githubusercontent.com/4528551/56969842-380e4f00-6b23-11e9-98bd-42afe5dcefee.png)
![image](https://user-images.githubusercontent.com/4528551/56969871-43fa1100-6b23-11e9-8e76-251ad59b2723.png) ![image](https://user-images.githubusercontent.com/4528551/56969911-55431d80-6b23-11e9-8ed3-9e869e4e46bd.png)

---
#### Fies

[dock.zip](https://github.com/Templarian/MaterialDesign/files/3131708/dock.zip)

**Comment by DubeauJL** [comment]
Thank you!

**Comment by goyney** [comment]
[![dock-bottom](https://materialdesignicons.com/icon/dock-bottom)](https://materialdesignicons.com/icon/dock-bottom)[![dock-left](https://materialdesignicons.com/icon/dock-left)](https://materialdesignicons.com/icon/dock-left)
[![dock-right](https://materialdesignicons.com/icon/dock-right)](https://materialdesignicons.com/icon/dock-right)
[![dock-window](https://materialdesignicons.com/icon/dock-window)](https://materialdesignicons.com/icon/dock-window)
