### ISSUE TITLE
Runbook

### ISSUE THREAD

**Issue by melissakinsey** [Templarian/MaterialDesign#4129]
Looking for an engineering runbook icon. Thanks.

**Comment by Templarian** [comment]
Book with a play symbol? Like...

[![book-play](https://materialdesignicons.com/icon/book-play)](https://materialdesignicons.com/icon/book-play) [![book-play](https://materialdesignicons.com/icon/book-play-outline)](https://materialdesignicons.com/icon/book-play-outline)

**Comment by melissakinsey** [comment]
Thanks so much! The play symbol is a brilliant idea. Not sure about the bookmark, although this would be a fantastic icon to represent an audiobook. For a runbook, to represent instructions, it might be better to have horizontal lines with bullet points. Or just horizontal lines if there's not enough room for bullets. Thanks again!~MK

**Comment by Templarian** [comment]
Maybe if we did something similar to the existing `notebook` icon?

**Comment by melissakinsey** [comment]
The comb binding on the notebook seems too literal, and I really love the Play icon you used. How about just working in "</>" or some binary digits somewhere to suggest software? Thanks so much! I'll keep an eye out for your reply.

**Comment by goyney** [comment]
There's not really room to add any more symbols to those current icons. I feel they work very well to contextually mean some collection of things that need to be played or ran. Going to close this request because of that. Thank you for your suggestion.
