### ISSUE TITLE
Icons for music's bitrate, duration, album, artist, genre, sample rate and date of creation

### ISSUE THREAD

**Issue by rustamzh** [Templarian/MaterialDesign#413]
It would be great if you add Icons for music's bitrate, duration, album, artist, genre, sample rate and date of creation. Thank you in advance.

**Comment by PushkaCom** [comment]
Along similar lines: Music/ Audio - I didn't want to start a new thread just for one icon - but:

It would be good to have an awesome audiobook icon or several:
could be 
book with ear in it, book with soundwaves coming out of it
I mashed the bookmark + music note elements of material design to make one:

http://pushka.com/i/p/goog/material/material-audiobook.svg

![material-book](https://cloud.githubusercontent.com/assets/985223/8002459/603a387e-0bb2-11e5-829d-04377fbe723c.png)

**Comment by Templarian** [comment]
@PushkaCom That looks more like a `bookmark-music` mashing a book icon and a music note or play triangle with a book might be better.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/bookmark-music

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/audiobook

**Comment by CoDEmanX** [comment]
There's a stock album icon by Google:
https://materialdesignicons.com/icon/album

For bitrate, duration, artist, genre, sample rate and date of creation, I can't really think of a meaningful symbol, nor do I think they are needed. 

Have a look at Google Photos app, the technical details like ISO, f-stop etc. are grouped and there's a single rather generic icon for the entire group:
![rps20150802_162250](https://cloud.githubusercontent.com/assets/1309249/9026544/cc215aba-3932-11e5-9a9b-bf0b4e2bfa07.jpg)

**Comment by CoDEmanX** [comment]
There are actually two suitable Google icons for duration:
https://www.google.com/design/icons/#ic_timelapse
https://www.google.com/design/icons/#ic_timer

**Comment by icarapovic** [comment]
What about genre? I thought of using a guitar icon, but something official would be far better. I see that for a long time nobody noticed this issue.

**Comment by JamesCoyle** [comment]
If you have an idea of what that would look like @icarapovic you can open a new issue with some examples. Personally I feel this should be handled via text labels instead. 

I'm gonna close this issue out as it's pretty dead at this point and we have icons which are pretty well suited to the task. If anyone has anything more specific to contribute you can open a new issue with examples.
