### ISSUE TITLE
calendar-account(-outline)

### ISSUE THREAD

**Issue by space-dweeb** [Templarian/MaterialDesign#4130]
Need to indicate "date of birth" in medical (EHR) software. 

Just **"cake"** is a bit quirky for the use case, but EHR tracks so many dates that just **"calendar"** isn't a sufficient visual cue. 

Looking for some combination of the calendar:

![calendar-blank (1)](https://user-images.githubusercontent.com/24944746/57106923-a823fd00-6cfc-11e9-8ed5-4b69f1087612.png)

And cake/a candle/balloon/present/etc:

![cake (1)](https://user-images.githubusercontent.com/24944746/57106916-a22e1c00-6cfc-11e9-9d99-a5f2c79f99ce.png) ![balloon](https://user-images.githubusercontent.com/24944746/57107161-41531380-6cfd-11e9-80e1-828272919fc9.png) ![gift](https://user-images.githubusercontent.com/24944746/57107164-431cd700-6cfd-11e9-9269-c05fcc63be98.png)

Perhaps a simplified **"cake"** overlapping **"calendar"**, the way **"clock"** does here?

![calendar-clock](https://user-images.githubusercontent.com/24944746/57106906-99d5e100-6cfc-11e9-984e-7660604d1061.png)

I know that's a bit complex, so any suggestions for making it simpler are appreciated. Thank you so much to anyone who helps with this. :)

**Comment by MrGrigri** [comment]
I believe this is too niche for this project. Could you please provide a different example. We must remember that we cannot shrink complex icons.

**Comment by space-dweeb** [comment]
I agree that complex icons shouldn't be shrunk. Maybe a simpler version of a cake or present could be used instead of just shrinking the complex ones down? Or maybe just an element of those icons, like a candle, or bow, etc?

I agree that it is a bit niche, but I've worked on 3 medical applications utilizing this icon pack and it's a common issue mentioned by the product owners, so I do think it would get significant use, at least in medical applications if nothing else. They are often very particular about maintaining a "serious, professional" tone in their branding, and shy away from anything "playful". 

Do you have any ideas for solving that problem that are maybe a bit different? I'm open to other options. :)

**Comment by JapanYoshi** [comment]
Google has a different cake icon under “Social”. We might need to update
our cake icon to that.

>

**Comment by MrGrigri** [comment]
I got it...what about a `calendar-account(-outline)` icon?

![image](https://user-images.githubusercontent.com/4528551/57534425-3d2a8580-72fd-11e9-915a-d3d094d309ff.png) ![image](https://user-images.githubusercontent.com/4528551/57534467-4e739200-72fd-11e9-8366-2191b7d4bfd2.png)

---
#### Files
[calendar-account.zip](https://github.com/Templarian/MaterialDesign/files/3166875/calendar-account.zip)

**Comment by Templarian** [comment]
Added both. :smile
