### ISSUE TITLE
human-male-height

### ISSUE THREAD

**Issue by space-dweeb** [Templarian/MaterialDesign#4131]
Need to indicate **"patient height"** in medical (EHR) software. 

Maybe a combination of **"human-handsdown"** on the left side, and arrows going up and down, similar to **"arrow-expand"** but tilted, on the right side?  

![human-handsdown](https://user-images.githubusercontent.com/24944746/57107710-be32bd00-6cfe-11e9-8867-71385d53a9f2.png) 
+ 
![arrow-expand](https://user-images.githubusercontent.com/24944746/57107766-e3273000-6cfe-11e9-82b2-6dfc1fc80e63.png), tilted to face up and down

Thank you so much to anyone who helps with this. :)

**Comment by MrGrigri** [comment]
Here are a couple of options.

![image](https://user-images.githubusercontent.com/4528551/57110012-50819380-6cf4-11e9-9bf8-e627ce0f1c7c.png) ![image](https://user-images.githubusercontent.com/4528551/57110052-71e27f80-6cf4-11e9-960f-410470097b9f.png)

---
### Files
[human-height.zip](https://github.com/Templarian/MaterialDesign/files/3140133/human-height.zip)

**Comment by space-dweeb** [comment]
These look awesome!! :) I think the arrows convey the idea quicker. It could probably be made less complex without the lines on the top and bottom of the arrows, but I think it's great as is as well. Thank you so much!! :) I really appreciate you working on this.

**Comment by MrGrigri** [comment]
The lines depict a fixed height instead of a growing or shrinking depiction.

**Comment by Templarian** [comment]
Added. 😃
