### ISSUE TITLE
human-weight

### ISSUE THREAD

**Issue by space-dweeb** [Templarian/MaterialDesign#4132]
Need to indicate **"patient weight"** in medical (EHR) software. 

Maybe a combination of **"human-handsdown"** on the left side, and an arrow facing out, similar to **"account-arrow-right"**?  

![human-handsdown](https://user-images.githubusercontent.com/24944746/57107710-be32bd00-6cfe-11e9-8867-71385d53a9f2.png) 

plus an outward arrow, to make something like:

![account-arrow-right](https://user-images.githubusercontent.com/24944746/57108022-98f27e80-6cff-11e9-946e-ef61e9661a63.png)

Thank you so much to anyone who helps with this. :)

**Comment by MrGrigri** [comment]
Wouldn't the `scale-bathroom` work for that?

![scale-bathroom](https://materialdesignicons.com/icon/scale-bathroom)

**Comment by space-dweeb** [comment]
Ah, I missed this icon. This would work fine, thank you :) Sorry for the redundancy.
