### ISSUE TITLE
Ansible

### ISSUE THREAD

**Issue by tychovbh** [Templarian/MaterialDesign#4133]
See https://www.ansible.com/ : 

<img width="167" alt="Screenshot 2019-05-05 at 21 31 12" src="https://user-images.githubusercontent.com/5880561/57199243-2098f100-6f7d-11e9-8207-4ef905ac6094.png">

**Comment by goyney** [comment]
We've recently changed our stance on brand icons and are less likely to add new ones.

We recommend the [SimpleIcons](https://simpleicons.org) library for brand icons. If they do not have the brand you're requesting, you can request it on their GitHub.

**Comment by PeterShaggyNoble** [comment]
Would this meet our criteria for brand icons otherwise?

**Comment by Templarian** [comment]
Anisible is fine for us to add. Branding icons related to tech tooling still are included.

**Comment by goyney** [comment]
Considering this is a development tool, it meets the criteria to still be added, [despite our recent announcement about brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/58272985-b98d8180-7d5d-11e9-999b-572b3b9403eb.png)
[ansible.svg.zip](https://github.com/Templarian/MaterialDesign/files/3213412/ansible.svg.zip)

**Comment by goyney** [comment]
[![ansible](https://materialdesignicons.com/icon/ansible)](https://materialdesignicons.com/icon/ansible)
