### ISSUE TITLE
home-attic

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4134]
please consider creating a home-attic next to home-floor-a, which still is somewhat prosaic.

simplest idea would be a horizontal line connecting the 2 outside points of the roof of the current home icon? maybe even an outline and a filled roof version if possible.

usecase: to show location of lights, sensors, movement etc etc.

thanks for considering!

**Comment by goyney** [comment]
This was discussed extensively in https://github.com/Templarian/MaterialDesign/issues/1964.

We choose to move forward with number and letter representations. We already have one for attic:
[![home-floor-a](https://materialdesignicons.com/icon/home-floor-a)](https://materialdesignicons.com/icon/home-floor-a)

**Comment by Mariusthvdb** [comment]
ok thanks, had missed that, sorry.
