### ISSUE TITLE
grass

### ISSUE THREAD

**Issue by marcoach** [Templarian/MaterialDesign#4136]
Icons to idealize a garden behaviour.
Thanks.

**Comment by MrGrigri** [comment]
Please provide some examples.

**Comment by marcoach** [comment]
Hello and thank-you ( all )

I need icons to identify courtyard, gardens, plants, trees and as I requested grass .

I need those icons to identify some appliances or activities ( such as switches ) related on irrigation, gardens, etc.

Thanks.

**Comment by MrGrigri** [comment]
I meant to ask for examples of what the icon would look like, not what you are going to use it for. Albeit, that is useful to know as well.

**Comment by marcoach** [comment]
some samples ...
grass :


or

garden : 


plants :

or

thanks.

**Comment by MrGrigri** [comment]
We already have the following icons that can represent plants or garden. Would any of these work?

We should add `plant` as an alias to all of these to help with searching.

- [flower](https://materialdesignicons.com/icon/flower)
- [flower-outline](https://materialdesignicons.com/icon/flower-outline)
- [flower-poppy](https://materialdesignicons.com/icon/flower-poppy)
- [flower-tulip](https://materialdesignicons.com/icon/flower-tulip)
- [flower-tulip-outline](https://materialdesignicons.com/icon/flower-tulip-outline)
- [flower-spa](https://materialdesignicons.com/icon/flower-spa-outline)
- [flower-poppyr](https://materialdesignicons.com/icon/flower-poppy)
- [nature](https://materialdesignicons.com/icon/nature)
- [nature-people](https://materialdesignicons.com/icon/nature-people)
- [pine-tree](https://materialdesignicons.com/icon/pine-tree)
- [tree](https://materialdesignicons.com/icon/tree)
- [tree-outline](https://materialdesignicons.com/icon/tree-outline)
- [sprout](https://materialdesignicons.com/icon/sprout)
- [sprout-outline](https://materialdesignicons.com/icon/sprout-outline)

**Comment by marcoach** [comment]
Hi,

The icons you suggested are enough !!!    My fault not having found them !

1 more question : are there also “Family Icons” something such as 2 people and a children ?

Thanks a lot !

**Comment by MrGrigri** [comment]
For a `family` icon, please refer to #1894 and #3015.

Closing this issue and all of the aforementioned icons now have the `plant` alias added to them.
