### ISSUE TITLE
phone-cancel

### ISSUE THREAD

**Issue by keycad** [Templarian/MaterialDesign#4137]
I've needed to create these two icons, using others from Mui as base, so I'm submitting them in case they're useful for the community, and the team finds wants to add them to the collection.

// Phone error 24px
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <path d="M0 0h24v24H0z" fill="none" />
  <path d="M20 15.5c-1.25 0-2.45-.2-3.57-.57-.35-.11-.74-.03-1.02.24l-2.2 2.2c-2.83-1.44-5.15-3.75-6.59-6.59l2.2-2.21c.28-.26.36-.65.25-1C8.7 6.45 8.5 5.25 8.5 4c0-.55-.45-1-1-1H4c-.55 0-1 .45-1 1 0 9.39 7.61 17 17 17 .55 0 1-.45 1-1v-3.5c0-.55-.45-1-1-1z" />
  <path d="m 16.669491,2.01695 c -2.484,0 -4.5,2.0159997 -4.5,4.4999992 0,2.4839994 2.016,4.5000008 4.5,4.5000008 2.484,0 4.5,-2.0160014 4.5,-4.5000008 0,-2.4839995 -2.016,-4.4999992 -4.5,-4.4999992 z m 0.45,6.7499986 h -0.9 V 7.8669488 h 0.9 z m 0,-1.7999997 h -0.9 V 4.2669497 h 0.9 z" />
</svg>
```

// Phone rejected 24px
```
<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
  <path d="M0 0h24v24H0z" fill="none" />
  <path d="M20 15.5c-1.25 0-2.45-.2-3.57-.57-.35-.11-.74-.03-1.02.24l-2.2 2.2c-2.83-1.44-5.15-3.75-6.59-6.59l2.2-2.21c.28-.26.36-.65.25-1C8.7 6.45 8.5 5.25 8.5 4c0-.55-.45-1-1-1H4c-.55 0-1 .45-1 1 0 9.39 7.61 17 17 17 .55 0 1-.45 1-1v-3.5c0-.55-.45-1-1-1z" />
  <path d="m 16.576271,1.6016949 c -2.484,0 -4.5,2.016 -4.5,4.5 0,2.484 2.016,4.5000001 4.5,4.5000001 2.484,0 4.5,-2.0160001 4.5,-4.5000001 0,-2.484 -2.016,-4.5 -4.5,-4.5 z m -3.6,4.5 c 0,-1.989 1.611,-3.6 3.6,-3.6 0.8325,0 1.5975,0.2835 2.205,0.7605 l -5.0445,5.0445 c -0.477,-0.6075 -0.7605,-1.3725 -0.7605,-2.205 z m 3.6,3.5999997 c -0.8325,0 -1.5975,-0.2835 -2.205,-0.7604997 l 5.0445,-5.0445 c 0.477,0.6075 0.7605,1.3725 0.7605,2.205 0,1.989 -1.611,3.5999997 -3.6,3.5999997 z" />
</svg>
```

**Comment by MrGrigri** [comment]
Thanks for contributing to our community. There are a couple of requirements that need to be met in order for us to consider counting this contribution. 

1. The icon needs to be a single compound path. E.g. `<path d="M1,21H23L12,2" />`.
2. Some sort of preview would be nice so we can see what the contribution is. This can be done a variety of ways, however, we prefer to use our [preview generator](http://dev.materialdesignicons.com/contribute/github) that accepts the aforementioned compound path.

**Comment by goyney** [comment]
@keycad Can you please address @MrGrigri comments so we can consider including these icons into the library?

**Comment by goyney** [comment]
`phone-alert` was added in `3.8.95`:
[![phone-alert](https://materialdesignicons.com/icon/phone-alert)](https://materialdesignicons.com/icon/iphone-alert)

**Comment by goyney** [comment]
The other proposed icon's preview is here:
![image](https://user-images.githubusercontent.com/1015040/61243471-08301a00-a716-11e9-8c1a-6c39244c8c2c.png)

This will need some work, as the `cancel` symbol doesn't meet Material guidelines.

**Comment by JamesCoyle** [comment]
`phone-cross` (or `phone-close` I guess) might be a better solution.

**Comment by goyney** [comment]
Nah, I see a real use case for the cancel variation. Could also be used as "block". Here's the cancel symbol updated to match our others. Credit still can be given to @keycad since he did the original design.

![image](https://user-images.githubusercontent.com/1015040/62747367-1e35af80-ba22-11e9-8b67-dd21b88278a8.png)
[phone-cancel.svg.zip](https://github.com/Templarian/MaterialDesign/files/3484280/phone-cancel.svg.zip)

**Comment by goyney** [comment]
[![phone-cancel](https://materialdesignicons.com/icon/phone-cancel)](https://materialdesignicons.com/icon/phone-cancel)
