### ISSUE TITLE
railroad-light

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4139]
As discussed in #4127, this issue is being created to handle the lighted railroad crossing post.

Something like this?

[![railroad-light.zip](https://user-images.githubusercontent.com/4528551/57165841-7cb11900-6db5-11e9-8482-1fcfe6fc64fe.png)](https://github.com/Templarian/MaterialDesign/files/3143566/railroad-light.zip)

**Comment by Templarian** [comment]
Added. 😃
