### ISSUE TITLE
Sports icons

### ISSUE THREAD

**Issue by aslakagens** [Templarian/MaterialDesign#414]
I would love some sports icons like, soccer, golf, sailing, kayaking, rowing, badmington, beachvolley, dans, surfing +++

**Comment by Glurt** [comment]
Can we add Cricket, Rugby and a generic sports icon please?

Thanks

**Comment by CoDEmanX** [comment]
Read about Google Fit icons:
https://github.com/Templarian/MaterialDesign/issues/505#issue-95548152

**Comment by derwaldgeist** [comment]
Is anyone working on these fit icons?

I am looking for vacation activities, like

- [ ] canoeing, 
- [ ] climbing, 
- [ ] gliding,
- [ ] hanggliding,
- [ ] horse riding,
- [ ] mountain biking,
- [ ] mountaineering,
- [ ] rafting,
- [ ] scuba diving,
- [ ] skiing

**Comment by PeterShaggyNoble** [comment]
I'm going to close this one out as a good few [sports icons](https://petershaggynoble.github.io/MDI-Sandbox/?categories=sport) have been added lately. If there are still any sports you would like to see included, please open new requests for each icon.
