### ISSUE TITLE
API icon

### ISSUE THREAD

**Issue by ofekashery** [Templarian/MaterialDesign#4140]
By Google.
[![image](https://user-images.githubusercontent.com/16443111/57571309-06479300-7415-11e9-8158-1754b722a758.png)](https://github.com/Templarian/MaterialDesign/files/3169162/api.svg.zip)
[api.svg.zip](https://github.com/Templarian/MaterialDesign/files/3169162/api.svg.zip)

**Comment by goyney** [comment]
That "P" doesn't look quite right.

**Comment by MrGrigri** [comment]
I believe it's because it's not using our alphabet.

**Comment by MichaelPriebe** [comment]
![api@3x](https://user-images.githubusercontent.com/5238952/58143123-ae303e00-7c17-11e9-879a-2ca7c5d894c8.png)
![api@2x](https://user-images.githubusercontent.com/5238952/58143124-af616b00-7c17-11e9-8a16-254cad90f66c.png)
![api](https://user-images.githubusercontent.com/5238952/58143132-b4beb580-7c17-11e9-9529-8a64ddae54f8.png)
```
M7,7H5A2,2,0,0,0,3,9v8H5V13H7v4H9V9A2,2,0,0,0,7,7Zm0,4H5V9H7Zm7-4H10V17h2V13h2a2,2,0,0,0,2-2V9A2,2,0,0,0,14,7Zm0,4H12V9h2Zm6-2v6h1v2H17V15h1V9H17V7h4V9Z
```

**Comment by goyney** [comment]
[![api](https://materialdesignicons.com/icon/api)](https://materialdesignicons.com/icon/api)
