### ISSUE TITLE
map-marker-alert

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4141]
Greetings,
I am using this icon in the web-app i'm developping. Hope it'll be usefull for others ;-)

path: `M12 2C8.1 2 5 5.1 5 9c0 5.2 7 13 7 13s7-7.8 7-13c0-3.9-3.1-7-7-7zm1 13h-2v-2h2v2zm0-4h-2V6h2v5z`

![img](https://user-images.githubusercontent.com/6012554/57625907-12f2f500-7595-11e9-9e93-4bec1b2bab81.png)

**Comment by Templarian** [comment]
Added! 😃 Also added the outline.

Assigned to the contributor account. Let me know when you add 3 more. 😸

**Comment by qnp** [comment]
Thanks !
I was also working on #4074
I don’t know if they are suitable for release yet.
