### ISSUE TITLE
Some outline icons missing

### ISSUE THREAD

**Issue by rataman098** [Templarian/MaterialDesign#4142]
Some of the official [Material icons](material.io/icons) are missing at their outline version. The ones I noticed are:
- [music_note](https://material.io/tools/icons/?search=music&icon=music_note&style=outline)
- [play_arrow](https://material.io/tools/icons/?search=play&icon=play_arrow&style=outline)
- [skip_next](https://material.io/tools/icons/?search=next&icon=skip_next&style=outline) (and previous, backwards and forward)
- [library_music](https://material.io/tools/icons/?search=music&icon=library_music&style=outline)

And some others. They're already made, so it shouldn't be difficult to add :P

**Comment by rataman098** [comment]
Hey! I just added these icon's svg to the mdi.svg file, and it seems to work! Here's what I added at the end of the `mdi.svg` file (I'm using Angular, don't know how it works for other platforms):
- Music note outline: <svg id="music-note-outline" viewBox="0 0 24 24"><path d="M12 3l.01 10.55c-.59-.34-1.27-.55-2-.55C7.79 13 6 14.79 6 17s1.79 4 4.01 4S14 19.21 14 17V7h4V3h-6zm-1.99 16c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z"/></svg>
- Play arrow outline: <svg id="play_arrow_outline" viewBox="0 0 24 24"><path d="M10 8.64L15.27 12 10 15.36V8.64M8 5v14l11-7L8 5z"/></svg>
- Skip previous: <svg id="skip-previous-outline" viewBox="0 0 24 24"><path d="M6 6h2v12H6zm3.5 6l8.5 6V6l-8.5 6zm6.5 2.14L12.97 12 16 9.86v4.28z"/></svg>
- Skip next: <svg id="skip-next-outline" viewBox="0 0 24 24"><path d="M6 18l8.5-6L6 6v12zm2-8.14L11.03 12 8 14.14V9.86zM16 6h2v12h-2z"/></svg>
- Library music outline: <svg id="library-music-outline" viewBox="0 0 24 24"><path d="M20 2H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H8V4h12v12zm-7.5-1c1.38 0 2.5-1.12 2.5-2.5V7h3V5h-4v5.51c-.42-.32-.93-.51-1.5-.51-1.38 0-2.5 1.12-2.5 2.5s1.12 2.5 2.5 2.5zM4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6z"/></svg>

I'll manually make the forwards and backwards and post them there too!

**Comment by rataman098** [comment]
Hey again! I manually inserted them into `mdi.svg` and it seems to work. Here's what I have included at the end of the file (I use Angular, so I don't know if this will work in other platforms:

- Play arrow outline
```
<svg id="play-arrow-outline" viewBox="0 0 24 24"><path d="M10 8.64L15.27 12 10 15.36V8.64M8 5v14l11-7L8 5z"/></svg>
```
- Music note outline:
```
<svg id="music-note-outline" viewBox="0 0 24 24"><path d="M12 3l.01 10.55c-.59-.34-1.27-.55-2-.55C7.79 13 6 14.79 6 17s1.79 4 4.01 4S14 19.21 14 17V7h4V3h-6zm-1.99 16c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z"/></svg>
```
- Skip previous outline:
```
<svg id="skip-previous-outline" viewBox="0 0 24 24"><path d="M6 6h2v12H6zm3.5 6l8.5 6V6l-8.5 6zm6.5 2.14L12.97 12 16 9.86v4.28z"/></svg>
```
- Skip next outline:
```
<svg id="skip-next-outline" viewBox="0 0 24 24"><path d="M6 18l8.5-6L6 6v12zm2-8.14L11.03 12 8 14.14V9.86zM16 6h2v12h-2z"/></svg>
```
- Library music outline:
```
<svg id="library-music-outline" viewBox="0 0 24 24"><path d="M20 2H8c-1.1 0-2 .9-2 2v12c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm0 14H8V4h12v12zm-7.5-1c1.38 0 2.5-1.12 2.5-2.5V7h3V5h-4v5.51c-.42-.32-.93-.51-1.5-.51-1.38 0-2.5 1.12-2.5 2.5s1.12 2.5 2.5 2.5zM4 6H2v14c0 1.1.9 2 2 2h14v-2H4V6z"/></svg>
```

I'll manually make the other 2 (skip forward and backwards) and post them there too!

**Comment by goyney** [comment]
- `music-note-outline` is already covered in #1632

---

These four are **Stock Google Icons**:

![image](https://user-images.githubusercontent.com/1015040/60060692-dea84380-96bf-11e9-8a82-e79ce28b363a.png)![image](https://user-images.githubusercontent.com/1015040/60060762-35ae1880-96c0-11e9-8bba-ff8f533284d1.png)
![image](https://user-images.githubusercontent.com/1015040/60060768-3cd52680-96c0-11e9-8310-a38d796896df.png)![image](https://user-images.githubusercontent.com/1015040/60060811-6b530180-96c0-11e9-94c9-f4ed30f59a7f.png)

---

These two were created by me:

![image](https://user-images.githubusercontent.com/1015040/60060962-0ea41680-96c1-11e9-8e52-fba1fec7429e.png)![image](https://user-images.githubusercontent.com/1015040/60060970-15328e00-96c1-11e9-89c0-5d451fd8f139.png)

[icons.zip](https://github.com/Templarian/MaterialDesign/files/3323078/icons.zip)

**Comment by Templarian** [comment]
Added. 😃
