### ISSUE TITLE
Homeassistant integration

### ISSUE THREAD

**Issue by mclaudiopt** [Templarian/MaterialDesign#4143]
hello
i use home assistant icons witho this code
icon: 'mdi:ceiling-light'
(example)
but mdi gives me acess to limited number of icons
how can i use all other icons available?
thanks

**Comment by goyney** [comment]
As we add new icons, Home Assistant needs to update to our later versions of the source packages. If there are icons in our released library that are not available to you in Home Assistant, I would open up a support issue with them as we don't control their integration.
