### ISSUE TITLE
book-account(-outline) book-(outline-)edit

### ISSUE THREAD

**Issue by appurist** [Templarian/MaterialDesign#4144]
I'd like to suggest an icon for authoring / writing / composing, e.g. a book.

I'm thinking something like a combination of the `fountain-pen` icon scaled and applied to the right-hand page of the `book-open-variant` icon.  Or something like that.

**Comment by MrGrigri** [comment]
What about something like this? Going to rename this to `book-author(-outline)` to be consistent and add the aforementioned aliases.

![image](https://user-images.githubusercontent.com/4528551/57816655-69009d80-7739-11e9-94e2-e934435dff9c.png) ![image](https://user-images.githubusercontent.com/4528551/57816686-7ddd3100-7739-11e9-8427-b5c7840aae18.png)

---
#### Files

[book-account.zip](https://github.com/Templarian/MaterialDesign/files/3184818/book-account.zip)

**Comment by appurist** [comment]
Hmm.  That's a nice one but it's not really what I was suggesting.

I wasn't suggesting anything to do with a user _account_, or _bookmark_, so I don't really see anything from that icon I can related to my request. It's a nice icon for something like a menu item or toolbar link to _saved bookmarks in an account_ (e.g. tab on a profile), but I'm thinking more along the lines of a _compose_ verb. Like _edit_. But for books.  

i.e. More than an editor: a writer / author composing a novel.  So my suggestion was an edit pencil or pen on an open book. Something like the `fountain-pen` implies a bit of style, so more than just a blog post, but an actual book like a fiction novel, text book, book of poetry, etc.

I'm sure that icon would be welcomed (I can already see where I might use it, to take me to this account's saved bookmarks) but it doesn't really trigger actually _writing_ a book to me.

**Comment by MrGrigri** [comment]
The reason why I went with a book (not bookmark) and account is that it symbolizes a person having possession of the book. Another option could be the same book icon with a pencil (or edit modifier) in the lower right corner.

The `account-edit` icon could represent an author.

![account-edit](https://materialdesignicons.com/icon/account-edit)

**Comment by appurist** [comment]
Sorry, I didn't recognize the rect with rounded corners as a book. (When I saw it, I was thinking tablet, or clipboard, or generic thing that holds bookmarks.)

I think you're still misinterpreting this request though (as the title change shows). As I mentioned above, I'm referring to a verb, an action, "_to author_ something". Not a person.

**Comment by MrGrigri** [comment]
We try not to add icons that represent an action. In this case, there shouldn't be a difference between authoring or being an author of something. Does the `account-edit` not suffice?

**Comment by appurist** [comment]
No, not really. The account-edit icon looks like an account (user) edit, not a book edit/compose. 

There are many icons for actions.  Even on this GitHub page, there are Watch, Fork, Edit, Comment, Close and Comment, etc.  In fact I'd argue that most icons are actions, not even just in MDI: open, close, print, like, reply, forward, delete, zoom in/out, find, exit, etc.  (And in this case, I also don't understand why editing one object _is_ an action (book), while editing the other object type (user) _is not_.) But I'm willing in this case to defer to those who actually do the work! ;)

At any rate, it is probably easy enough for me to plop a fountain pen on an open book for my own needs, so I was probably being a bit selfish and requesting something specific for me.  It's okay by me if you want to close this one as redundant with `account-edit`, or change it to a request for something else that you see as more general-purpose.

**Comment by appurist** [comment]
Sorry, I just don't even get "book" from that icon (at all). From what I can see, it seems Google uses it for Google Play books, but even there they often have a visible binding down the left and sometimes square off the left-side corners, which helps hint at book quite a bit more than a rectangle does (although not enough in my opinion). To me, it's just not a book.  It's a good icon for "_eBook_ bookmark" though.

I Googled "authoring icon" and then "book authoring icon" ([here's a link](https://www.google.com/search?q=book+authoring+icon&newwindow=1&tbs=itp:clipart&tbm=isch&source=lnt) to the image results) and I see lots of fountain pens, quills, and objects which are more obviously books.

One of the links was to a Shutterstock collection and so I followed that and I see several "book" collections that have at least one icon with a pen.  Any one of those would probably convey the key concepts of "book" and "writing". For example, the one in the bottom left corner below ![image](https://image.shutterstock.com/image-vector/book-icons-vector-set-ebook-450w-229201648.jpg)
All of these present "book" to me, except the last one in the third row, which has enough info to convey "eBook" to me (or tablet reading).

**Comment by goyney** [comment]
The Material Design guidelines state:

> System icons are designed to be simple, modern, friendly, and sometimes quirky. Each icon is **reduced to its minimal form**, expressing essential characteristics.

And goes on to state:

> Don’t be overly literal. **Avoid complex icons.**

The simple `book` icon Google has created absolutely meets this criteria. Adding in a pencil in the cut out, as @MrGrigri has done, is about as far as we're willing to push the envelope in terms of making an icon overly complex.

We have book variants, such as the ones you provided as an example (see [`book-open-variant`](https://materialdesignicons.com/icon/book-open-variant)), but that icon in and of itself is more complex than a simple `book`. It also takes up more of the design grid than we're technically supposed to consume, but Google created it, so we allow it.

> 2dp of empty space makes up the padding surrounding the 20dp x 20dp live area.

Additionally, books that show depth (where you can see the tops of the pages) is absolutely against Material Design.

> Don’t tilt, rotate, or make icons appear dimensional.

All that being said, the four icons proposed by @MrGrigri will likely be added in a future release, but I don't see edit variants of `book-open-variant` working.

--

*Source*: https://material.io/design/iconography/system-icons.html

**Comment by appurist** [comment]
The last icon you have suggested is a great icon for _editing ebook bookmarks_.  But that is not what I was requesting at all.

That is something a _reader_ would do, not the book _author_, and something done _after_ the book exists, and is an operation on bookmarks, not books.

**Comment by appurist** [comment]
@goyney I understand. And I do think it's pretty obvious that icons need to be simplified from the presentation of their concepts, especially when combining two. My original mention of the open book and the fountain pen icons were to present the _concept_ of what I was requesting.  It seems that this concept has not been understood for several replies, and then the desire to use the Google 'book' icon (which clearly represents an eBook) seems to be overriding all other concerns.  That's okay, these other concepts are also useful to some people, just not me.

That Google concept of `book` (and suggested by @MrGrigri above) just doesn't represent a book to me, except with more context (which is absent in the suggestions).  It may represent a _notebook_ if the binding rect and square edges were included on one side, or a tablet without (which to me means ebook, not book).  I think the problem here is that it is difficult to present a simple icon for a physical book without it appearing at least a little 3D. 

If that's the reason you want to reject this concept of an icon for a physical book, and using only a rectangle with rounded corners, that is your call.  Please consider my request withdrawn.  In that case, the `feather` icon at least has the potential to convey the act of writing or composition.  Some icon creators leave a trail behind it to indicate more clearly the concept of writing.  But a rectangle with a bookmark and a pencil overlay in the corner to me only implies editing bookmarks.

I just looked at font-awesome to see if they had such a concept of a book compose/edit/authoring, and there are several [book-related icons](https://fontawesome.com/icons?d=gallery&q=book&s=light,regular,solid) but nothing for creating/editing/composing one. However, their use of an open book (`book-open`) is very simple and often augmented with something. A simple circle over it to indicate a book user (`book-reader`), or even the closed book (`book`) has two simple horizontal lines representing the writing (e.g. title) on the book.  Replacing either the circle, or the lines, with a simple pencil would convey the "book authoring" (or editing) I was requesting. I don't think that violates the MD guidelines, although it could be argued it's partly 3-D.  

Unfortunately none of the alternatives suggested seem to convey the concepts I requested, so again I see continued discussion of this somewhat unproductive. I am going to bow out and allow you folks to produce the author (user) or ebook bookmark edit icons, as those will probably be useful for others.

**Comment by goyney** [comment]
> That Google concept of `book` (and suggested by @MrGrigri above) just doesn't represent a book to me, except with more context.

This is the most important line in your statement. Icons are not meant to be absolute, but to supplement the content in which they appear. They are inherently contextual. Sometimes, there are objects that convey themselves very well in a 22x22 grid, sometimes they don't. But that doesn't make icons being contextual any less true.

I'm sorry we were not able to satisfy exactly what you were looking for. However, we do have many icons that indicate writing or authoring, and I hope you are able to work with those in a way which meets your needs.
