### ISSUE TITLE
currency-rial

### ISSUE THREAD

**Issue by Kayoti** [Templarian/MaterialDesign#4145]
The following countries uses the Rial as their currency and the symbol is Generic standard for all regardless of variation, this is tricky it is not quite region specific it covers a range just like euro in a way

Yemen population ->29,579,986
Saudi Arabia -> population 34,140,662
Qatar population ->2,743,901
Oman population ->5,001,875
Iran population ->82,820,766
[RialTemplate.zip](https://github.com/Templarian/MaterialDesign/files/3184201/RialTemplate.zip)

![RialTemplate](https://user-images.githubusercontent.com/3899197/57804578-398d6900-7718-11e9-8fd0-f552801c25d4.png)

**Comment by JapanYoshi** [comment]
I had the text rendered in Noto Sans Arabic, then I tweaked the strokes a bit to fit within the grid. I hope this looks accptable enough; I don't speak a lick of Arabic!
![rial](https://user-images.githubusercontent.com/8707990/57815680-bd4c6180-77bb-11e9-9997-6242e56b36fd.png)

**Comment by JapanYoshi** [comment]
Alternatively, here's an icon in a style more in line with the `numeric-` and `alpha-` icons, but it might not look good for Arabic. Please do provide some feedback, since I'm not experienced in Arabic typography.
![currency_rial_blocky](https://user-images.githubusercontent.com/8707990/57816054-3dbf9200-77bd-11e9-8200-09befc12e0a6.png)
![currency_rial_blocky-24](https://user-images.githubusercontent.com/8707990/57816055-3e582880-77bd-11e9-9cd7-833e24e9c361.png)

**Comment by MrGrigri** [comment]
Those two dots need to be in line with each other on that last one since we're going for a more on-grid approach.

**Comment by MrGrigri** [comment]
@JapanYoshi, we also need the SVG attached.

**Comment by JapanYoshi** [comment]
I've tweaked the letters a little bit, but I'd much rather wait until I can get an opinion from someone who actually uses the Arabic script.
![currency_rial_8x](https://user-images.githubusercontent.com/8707990/57830365-42a03800-77f5-11e9-8cd4-6c5188ef5eab.png)
![currency_rial_blocky](https://user-images.githubusercontent.com/8707990/57830367-4338ce80-77f5-11e9-807f-f0b01ae6a7d7.png)
![currency_rial_24](https://user-images.githubusercontent.com/8707990/57830377-5186ea80-77f5-11e9-91bf-9be5fc9ac1e7.png)
![currency_rial_blocky_24](https://user-images.githubusercontent.com/8707990/57830378-5186ea80-77f5-11e9-9936-d508fdcf3b3f.png)
[currency_rial_draft.zip](https://github.com/Templarian/MaterialDesign/files/3185617/currency_rial_draft.zip)

**Comment by MrGrigri** [comment]
I speak Pashto which uses the Arabic script...so you're good.

**Comment by MrGrigri** [comment]
And we'll use the square terminal one.

**Comment by JapanYoshi** [comment]
Alright, fine by me!

**Comment by Kayoti** [comment]
This looks good!

**Comment by Kayoti** [comment]
> This looks good!

I speak arabic

**Comment by Templarian** [comment]
[![currency-rial](https://materialdesignicons.com/icon/currency-rial)](https://materialdesignicons.com/icon/currency-rial)
