### ISSUE TITLE
recessed-lights

### ISSUE THREAD

**Issue by tom-greene** [Templarian/MaterialDesign#4146]
I found an icon I liked by searching and created an SVG for it. Hoping it can be used by the default icon set. 
[recessed-light.svg.gz](https://github.com/Templarian/MaterialDesign/files/3187580/recessed-light.svg.gz)

**Comment by goyney** [comment]
Duplicate of #1826. Could you please post your suggested icon there?

Also, you can use http://dev.materialdesignicons.com/contribute/github to generate a preview of it for your post.
