### ISSUE TITLE
account-cash

### ISSUE THREAD

**Issue by jacwright** [Templarian/MaterialDesign#4147]
An icon to represent sales activities. Probably a person and money or cash symbol. Here is an example of what it might be:

![Screen Shot 2019-05-16 at 12 30 37 PM](https://user-images.githubusercontent.com/120294/57878073-7d46a800-77d6-11e9-825c-66b18ad9a21c.png)

**Comment by MrGrigri** [comment]
Please be aware that we are not adding the `dollar` symbol as a modifier as it is not international.

**Comment by goyney** [comment]
Why wouldn't something as simple as `cash` work for this?

As @MrGrigri stated, we won't be adding any new icon variations with specific currency marks (such as the `$`). The first example does not work because it does not meet Material guidelines; the border of the dollar will need to be 2dp wide, which makes it too large of an icon to turn into a modifier of an existing icon.

Unless you have some other ideas, I'm not sure what else we can do on this.

**Comment by jacwright** [comment]
`cash` _could_ work, though I was hoping for something with a person in it to represent a person who works with cash rather than cash itself. But you can only do so much in 24 pixels.

**Comment by jacwright** [comment]
Would this be too big to fit into the icon space?

<img width="46" alt="Screen Shot 2019-06-22 at 11 16 06 AM" src="https://user-images.githubusercontent.com/120294/59966843-2623a980-94df-11e9-9686-49a68cb10158.png">

**Comment by Templarian** [comment]
@jacwright I think that would work for a salary icon. `account-cash` following our naming guidelines.

**Comment by jacwright** [comment]
This is my first icon, feedback much appreciated.

I made the account icon base 2px smaller and moved the head circle over 1px. I rotated the cash icon 90 degrees, made the inner circle 1px smaller and brought the right and bottom border in 1px each to keep make it thinner while keeping the circle centered still. This allowed for a 2px gap between the 2 icons while still fitting in the 24px boundary. I'm not sure what guidelines exist around if there needs to be space between the boundary and icon or what.

![image](https://user-images.githubusercontent.com/120294/61186100-7f828280-a61e-11e9-9e91-326cc151c947.png)

**Comment by jacwright** [comment]
From what I understand, I don't need to create a pull request, someone else will add this?

If it is helpful, here is the svg for it:

```svg
<svg width="24" height="24" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <path fill="#000000" d="M11,8 C11,10.209139 9.209139,12 7,12 C4.790861,12 3,10.209139 3,8 C3,5.790861 4.790861,4 7,4 C9.209139,4 11,5.790861 11,8 Z M11,14.7164678 L11,20 L0,20 L0,18 C0,15.79 3.1325,14 7,14 C8.48753982,14 9.866346,14.2648071 11,14.7164678 Z M24,20 L13,20 L13,3 L24,3 L24,20 Z M16,11.5 C16,10.1192881 17.1192881,9 18.5,9 C19.8807119,9 21,10.1192881 21,11.5 C21,12.8807119 19.8807119,14 18.5,14 C17.1192881,14 16,12.8807119 16,11.5 Z M22,7 C20.8954305,7 20,6.1045695 20,5 L17,5 C17,6.1045695 16.1045695,7 15,7 L15,16 C16.1045695,16 17,16.8954305 17,18 L20,18 C20,16.8954305 20.8954305,16 22,16 L22,7 Z"/>
</svg>
```

**Comment by goyney** [comment]
Yes, one of the Core Contributors will add it to the library if we're all in agreement that it is a good addition (we do!). We typically add about 100 icons per month (we typically release once a month). That may ramp up here as we get some new systems in place, allowing us to add icons quicker. That being said, we also add icons in the order in which we get contributions, so it may be a few releases until this gets added. Once it does, we'll let you know via this issue. Thanks for your contribution!

**Comment by jacwright** [comment]
Thank you!

**Comment by goyney** [comment]
[![account-cash](https://materialdesignicons.com/icon/account-cash)](https://materialdesignicons.com/icon/account-cash)[![account-cash-outline](https://materialdesignicons.com/icon/account-cash-outline)](https://materialdesignicons.com/icon/account-cash-outline)
