### ISSUE TITLE
Request for excel download icon

### ISSUE THREAD

**Issue by himaniamola** [Templarian/MaterialDesign#4148]
I need an icon for excel download. Excel is a common tool that is used in applications so, it should be part of the material icons.

**Comment by goyney** [comment]
We have:
[![file-excel](https://materialdesignicons.com/icon/file-excel)](https://materialdesignicons.com/icon/file-excel)
[![file-excel-box](https://materialdesignicons.com/icon/file-excel-box)](https://materialdesignicons.com/icon/file-excel-box)

We also have open request #368 for the actual product icon.

**Comment by himaniamola** [comment]
Hi Michael,
I downloaded it and it's all white.

Thanks,
Himani
