### ISSUE TITLE
Advanced icon chooser always uses ZIP

### ISSUE THREAD

**Issue by madisotenurm** [Templarian/MaterialDesign#415]
The advanced icon chooser always packs it in a ZIP archive that just contains the icon and a readme file.
That makes using those icons really annoying because you have to unpack every one of them.

**Comment by Templarian** [comment]
This will be fixed along side #371, but I'll leave it as a separate issue instead of merging.

**Comment by Templarian** [comment]
Fixed. Sorry for the long delay. Just getting around to cleaning up the icon generation side.

There are 1 click download buttons for black / white icons also.

![image](https://cloud.githubusercontent.com/assets/338885/8347192/dd41f862-1aca-11e5-83a5-19de4afaad33.png)
