### ISSUE TITLE
Natural / alternate eye Icon

### ISSUE THREAD

**Issue by boltex** [Templarian/MaterialDesign#4150]
I would like to submit an alternate eye icon. (A more natural looking eye, but still in a  minimalist/material style, of course.)

Here is what the actual eye-outline icon looks in a grid. It either looks like a "too-much-coffee/coke eye" or at most a radio control (with actual radios in the red box as reference):
![example-eye-radio](https://user-images.githubusercontent.com/847716/57956118-e0fbce80-78c5-11e9-94c0-335e957bb357.png)

Here is the one I propose (right) compared to the existing "eye-outline" (left) : 
![image](https://user-images.githubusercontent.com/847716/57956284-7b5c1200-78c6-11e9-851a-564925592b30.png)

So here's the .svg attached in a .zip: 
[eye-natural.zip](https://github.com/Templarian/MaterialDesign/files/3193124/eye-natural.zip)

I've made it by downloading the .svg in the sources from "eye-outline.svg" and modifying it a bit in inkscape and exported as "plain svg".

**Comment by Templarian** [comment]
Cool idea, but this is going to be too niche and goes against the MD guidelines of unnecessary detail.

`eye-outline` will most likely be updated to match https://material.io/tools/icons/?search=eye&style=outline
