### ISSUE TITLE
ufo

### ISSUE THREAD

**Issue by pacovalverde** [Templarian/MaterialDesign#4151]
ufo, ufo-alert, ufo-old, ufo-old-1
![ufo](https://user-images.githubusercontent.com/12108757/57987165-2ebb3700-7a7e-11e9-9cbd-b9416c34dec3.png)
![ufo-alert](https://user-images.githubusercontent.com/12108757/57987166-2ebb3700-7a7e-11e9-91db-a4ca3f0b2b30.png)
![ufo-old](https://user-images.githubusercontent.com/12108757/57987167-2ebb3700-7a7e-11e9-8b0f-561058c1f0b6.png)
![ufo-old_1](https://user-images.githubusercontent.com/12108757/57987168-2ebb3700-7a7e-11e9-9329-eee1eb1edcb7.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/60060477-c7b52180-96be-11e9-9a7b-ef2cf7b021d0.png)![image](https://user-images.githubusercontent.com/1015040/60060484-d13e8980-96be-11e9-8c47-01494815c591.png)

/shrug

[ufo.zip](https://github.com/Templarian/MaterialDesign/files/3323050/ufo.zip)

**Comment by pacovalverde** [comment]
![ufo-alert](https://user-images.githubusercontent.com/12108757/60131986-eb4d9a00-979a-11e9-8725-92b05f9a06da.png) ufo-alert
![ufo-variant-alert](https://user-images.githubusercontent.com/12108757/60132019-f30d3e80-979a-11e9-87a6-1d88bfbfcacc.png) ufo-variant-alert

**Comment by goyney** [comment]
I don't think we'd add "alert" variants. Very niche.

**Comment by pacovalverde** [comment]
![ufo-go](https://user-images.githubusercontent.com/12108757/60133609-f5bd6300-979d-11e9-9e87-1753dfa49cd6.png) ufo-go
![ufo-variant-go](https://user-images.githubusercontent.com/12108757/60133639-02da5200-979e-11e9-8eb0-1805c890516e.png) ufo-variant-go

**Comment by pacovalverde** [comment]
> I don't think we'd add "alert" variants. Very niche.

Please. I need it for my web page https://ufo-alert.com/

**Comment by goyney** [comment]
"alert" is a modifier that adds a ! to the icon, so if we were to include that, it would need to follow the pattern set by other icons in the library. The "go" ones are even more niche.

**Comment by pacovalverde** [comment]
> "alert" is a modifier that adds a ! to the icon, so if we were to include that, it would need to follow the pattern set by other icons in the library. The "go" ones are even more niche.
But, the problem are the name or the figure?

**Comment by pacovalverde** [comment]
> "alert" is a modifier that adds a ! to the icon, so if we were to include that, it would need to follow the pattern set by other icons in the library. The "go" ones are even more niche.

But, the problem are the name or the figure? Is possible names: ufo-ring, ufo-send?

**Comment by JamesCoyle** [comment]
I agree with @goyney. The UFO icon is great but I don't see any benefit of having different modifiers as it's really niche as is. If you need those in your app you would be best using inline SVG assets.

**Comment by pacovalverde** [comment]
Hello, when will the »ufo« icon available in materialdesignicons.css?
Kind regards

**Comment by goyney** [comment]
[![ufo](https://materialdesignicons.com/icon/ufo)](https://materialdesignicons.com/icon/ufo)[![ufo-outline](https://materialdesignicons.com/icon/ufo-outline)](https://materialdesignicons.com/icon/ufo-outline)
