### ISSUE TITLE
Various icons with check ✅✅✅

### ISSUE THREAD

**Issue by mocking-mike** [Templarian/MaterialDesign#4152]
Hello, 

I've been using the icons for some time in my projects and now it's time to give some design back to community :). I needed an icon with a document and a check, so I made it and couple more to make it round 5.

I combined elements from other icons and since it's my first time uploading icons here, feel free to point out my errors so I can correct them. Svg files in one path can be found in the .zip archive. Please tell me if any other format are needed :)

[icons-with-check.zip](https://github.com/Templarian/MaterialDesign/files/3197740/icons-with-check.zip)

file-document-box-check-outline
![image](https://user-images.githubusercontent.com/50829720/58018763-ff4f0d80-7b03-11e9-8b41-bd4c0c9459db.png)

file-document-box-check
![image](https://user-images.githubusercontent.com/50829720/58018990-af247b00-7b04-11e9-8de6-19f4f272bc9c.png)

map-check
![image](https://user-images.githubusercontent.com/50829720/58019189-3d98fc80-7b05-11e9-91d5-63cad55ffbcf.png)

shield-check-outline
![image](https://user-images.githubusercontent.com/50829720/58019157-28bc6900-7b05-11e9-9144-90afeb9c0534.png)

shield-check
![image](https://user-images.githubusercontent.com/50829720/58019235-56091700-7b05-11e9-8d7a-c16439f9cc04.png)

Hope they will serve you well sometime! :)
Michał

**Comment by Templarian** [comment]
The naming for `shield-check` is interesting since we use the check inside for it currently.

**Comment by goyney** [comment]
I vote we add an outline version of our current `shield-check` and not add the two shield variants above. The rest seem fine.

**Comment by Templarian** [comment]
Added the three `file-document-box-check`, `file-document-box-check-outline` and `map-check`. Assigned to the shared contributor account. Let me know once you have 5 icons and I'll create/assign to a contributor account.

**Comment by Templarian** [comment]
Also `map-check-outline` was added.
