### ISSUE TITLE
arrow-up-down and arrow-left-right

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#4153]
Like arrow-expand but rotated 135 and 45 degrees. Also there's a arrow-up-down-bold-outline and arrow-left-right-bold-outline. This would just be a thin single line version combining arrow-up and arrow-down.

I'd use arrow-expand with mdi-rotate-135, but the space between the arrows is a bit large and makes it awkward to use with other icons.

**Comment by ginlime** [comment]
How do you like these?

![arrow-left-right](https://user-images.githubusercontent.com/3253790/58158741-fdc54700-7cb5-11e9-822b-83155cf968bd.png)
![arrow-left-right_large](https://user-images.githubusercontent.com/3253790/58158746-03bb2800-7cb6-11e9-86a8-6f31b77b60ba.png)

![arrow-up-down](https://user-images.githubusercontent.com/3253790/58158760-087fdc00-7cb6-11e9-9819-8dc7af7f5693.png)
![arrow-up-down_large](https://user-images.githubusercontent.com/3253790/58158767-0cabf980-7cb6-11e9-9a03-3b96a90c97ed.png)

![arrow-upleft-downright](https://user-images.githubusercontent.com/3253790/58158824-32390300-7cb6-11e9-8f31-25fe9f95522b.png)
![arrow-upleft-downright_large](https://user-images.githubusercontent.com/3253790/58158835-35cc8a00-7cb6-11e9-825b-97340162a015.png)

![arrow-upright-downleft](https://user-images.githubusercontent.com/3253790/58158847-3cf39800-7cb6-11e9-9240-97e3970292f8.png)
![arrow-upright-downleft_large](https://user-images.githubusercontent.com/3253790/58158857-44b33c80-7cb6-11e9-95f3-f8971a11a48c.png)

And, shorter version for tilted arrows.
![arrow-upleft-downright-shorter](https://user-images.githubusercontent.com/3253790/58159617-dcfdf100-7cb7-11e9-83b3-2ab82b19756e.png)
![arrow-upleft-downright-shorter_large](https://user-images.githubusercontent.com/3253790/58159628-e71fef80-7cb7-11e9-8bd7-e217935d26e8.png)

![arrow-upright-downleft-shorter](https://user-images.githubusercontent.com/3253790/58159642-eb4c0d00-7cb7-11e9-9349-94bf9867aa47.png)
![arrow-upright-downleft-shorter_large](https://user-images.githubusercontent.com/3253790/58159651-f010c100-7cb7-11e9-884b-41c1766e7ad3.png)

[double_end_arrows.zip](https://github.com/Templarian/MaterialDesign/files/3206439/double_end_arrows.zip)

**Comment by Templarian** [comment]
Added with some slight modifications for consistency. Also added `*-bold`. 😃

**Comment by ginlime** [comment]
Thanks.
Icons I made became over 5 totally.
Is it enough to be a contributor?
