### ISSUE TITLE
App Store

### ISSUE THREAD

**Issue by pixieaka** [Templarian/MaterialDesign#4154]
![app-store-logo](https://user-images.githubusercontent.com/17777237/58062115-6bb82400-7b79-11e9-9c48-1f1589dbd23e.jpg)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
