### ISSUE TITLE
Coffee/Espresso Machine Icon

### ISSUE THREAD

**Issue by barrycraig** [Templarian/MaterialDesign#4155]
I would love it if you would consider an icon to represent a coffee machine. Currently using a generic cup is the only option. Even an espresso cup on a saucer would be a good option.

**Comment by goyney** [comment]
Perhaps something like this?

![image](https://user-images.githubusercontent.com/1015040/58281384-0e86c300-7d71-11e9-8a18-2447d31d5827.png)
[coffee-maker.svg.zip](https://github.com/Templarian/MaterialDesign/files/3213861/coffee-maker.svg.zip)

**Comment by goyney** [comment]
[![coffee-maker](https://materialdesignicons.com/icon/coffee-maker)](https://materialdesignicons.com/icon/coffee-maker)
