### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by odesmet** [Templarian/MaterialDesign#4156]
Need to indicate some dimensions.

Would be great to have some icons to show:
- Length
- Width
- Height
- Weight

Maybe length and width can be the same icon. But a combination of an icon and text is already a lot better than only text.

**Comment by MrGrigri** [comment]
For `height` please refer to #4132.

There are plenty of icons that represent weight: [weight](https://materialdesignicons.com/icon/weight) or [scale-bathroom](https://materialdesignicons.com/icon/scale-bathroom) or [scale](https://materialdesignicons.com/icon/scale) or [scale-balance](https://materialdesignicons.com/icon/scale-balance)

For length and width, there is [arrow-expand-vertical](https://materialdesignicons.com/icon/arrow-expand-vertical) and [arrow-expand-horizontal](https://materialdesignicons.com/icon/arrow-expand-horizontal)

Do these not satisfy your request?

**Comment by odesmet** [comment]
This is exactly what I needed. materialdesignicons.com was blocked by my company and I couldn't found these on material.io. 

Thanks Michael!

**Comment by MrGrigri** [comment]
@odesmet, you could try https://petershaggynoble.github.io/MDI-Sandbox/

**Comment by Templarian** [comment]
@odesmet I don't force https on the site, might be an issue with that.

Or the CDN https://cdn.materialdesignicons.com/3.6.95/
