### ISSUE TITLE
Diaper

### ISSUE THREAD

**Issue by informatious** [Templarian/MaterialDesign#4158]

**Comment by JamesCoyle** [comment]
Should add nappy as an alias.

**Comment by vcantu** [comment]
How's this: I made two variants a filled in and an outline variant

[diaper-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3484489/diaper-outline.svg.zip)
[diaper.svg.zip](https://github.com/Templarian/MaterialDesign/files/3484490/diaper.svg.zip)

**Comment by drpeppershaker** [comment]
+1 for this request

**Comment by kguy18** [comment]
+1 for this as well. Also the design is perfect.

**Comment by jhil** [comment]
I created `underwear-outline` and `diaper-outline`. Let me know if you have any feedback before I productionize these!

![Screenshot 2023-11-30 at 23 00 27](https://github.com/Templarian/MaterialDesign/assets/2228347/a6bad5cb-aee7-4341-9c7a-1339c3685cf8)

**Comment by jhil** [comment]
[![diaper-outline](https://pictogrammers.com/library/mdi/icon/diaper-outline)](https://pictogrammers.com/library/mdi/icon/diaper-outline)
[![underwear-outline](https://pictogrammers.com/library/mdi/icon/underwear-outline)](https://pictogrammers.com/library/mdi/icon/underwear-outline)
