### ISSUE TITLE
decimal-(increase|decrease)-comma decimal(-comma)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4159]
I'm going to create these.

**Comment by MrGrigri** [comment]
`decimal(-comma)`

![decimal](https://user-images.githubusercontent.com/4528551/58202646-50dad200-7c95-11e9-9c32-f741451e2ed4.png) ![decimal-comma](https://user-images.githubusercontent.com/4528551/58202696-6fd96400-7c95-11e9-9e85-42ff8710836b.png)

`decimal-(increase|decrease)-comma`

![decimal-increase-comma](https://user-images.githubusercontent.com/4528551/58202736-8f708c80-7c95-11e9-8fbc-53adbf7e3b89.png) ![decimal-decrease-comma](https://user-images.githubusercontent.com/4528551/58202755-9bf4e500-7c95-11e9-9258-a8cf52c36510.png)


---
#### Files

[decimal.zip](https://github.com/Templarian/MaterialDesign/files/3208993/decimal.zip)

**Comment by goyney** [comment]
[![decimal](https://materialdesignicons.com/icon/decimal)](https://materialdesignicons.com/icon/decimal)[![decimal-comma](https://materialdesignicons.com/icon/decimal-comma)](https://materialdesignicons.com/icon/decimal-comma)
[![decimal-comma-increase](https://materialdesignicons.com/icon/decimal-comma-increase)](https://materialdesignicons.com/icon/decimal-comma-increase)
[![decimal-comma-decrease](https://materialdesignicons.com/icon/decimal-comma-decrease)](https://materialdesignicons.com/icon/decimal-comma-decrease)
