### ISSUE TITLE
Page freeze after direct download

### ISSUE THREAD

**Issue by madisotenurm** [Templarian/MaterialDesign#416]
The site always freezes after downloading a direct icon file with the right click menu.
Site can be used again after a reload, but this still occurs after the download.
Google Chrome 44.0.2383.0 m (64-bit)

**Comment by Templarian** [comment]
What are your exact steps, I just tried and it seems to be fine in Chrome 43 latest.

If so that's a pretty bad bug.

**Comment by madisotenurm** [comment]
Weird, it doesn't occur for me anymore, too.
However:
1) Find an icon
2) Right click
3) Pick icon size/type
4) Icon gets downloaded
5) Page freezes, shows the backwards throbber on tab

**Comment by Templarian** [comment]
I've messed around for a bit to reproduce it. Not seeing anything. None of that code is really recursive or attached to a loop, so it shouldn't happen.

That code has been probably the same for the last 5 months, with this being the first issue. Might have been chrome just being weird.

Let me know and I'll reopen the issue.
