### ISSUE TITLE
Infusion bag

### ISSUE THREAD

**Issue by senyahnoj** [Templarian/MaterialDesign#4163]
Would anyone be interested in producing an icon for an infusion bag?

i.e. one of these

https://www.testresources.net/images/applications/iv-bag-1.jpg

**Comment by goyney** [comment]
We already have `blood-bag`, which can be used to indicate the same thing:
[![blood-bag](https://materialdesignicons.com/icon/blood-bag)](https://materialdesignicons.com/icon/blood-bag)

We should probably add some aliases to this icon for IVs.

**Comment by senyahnoj** [comment]
Nice - thanks for the suggestion. The only difference is that an infusion bag has the tubes coming out of the bottom (as it's hung from a stand and the fluids travel downwards with gravity). So the blood bag icon rotated 180 degrees would work.

**Comment by MrGrigri** [comment]
@senyahnoj Are you needing this icon to distinguish between both a blood and infusion bags?

**Comment by senyahnoj** [comment]
No specifically in the application I'm writing. It's just that the target audience would understand it as an infusion bag by the fact that it was hung this way up.

If you google image search "infusion bag icon" you'll see pretty much all the examples are this way up.

**Comment by goyney** [comment]
Would a true flip like this be enough?

![image](https://user-images.githubusercontent.com/1015040/58272468-94e4da00-7d5c-11e9-824b-e27402a33df7.png)

[blood-bag-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/3213386/blood-bag-variant.svg.zip)

**Comment by senyahnoj** [comment]
Thanks for this. I would use this icon, although if you wanted to go further here's some suggestions based on reviewing some other infusion bag icons on a google image search: some other features which one might want to incorporate

- Some have measuring lines on the bag itself (although might not work in small sizes)
- Instead of a drop most seem to be filled (or half-filled) with liquid. I'm not sure whether people associate the drop with blood rather than a concentration of saline or medication
- The tube should predominantly travel downwards as the patient is below it

![Screenshot from 2019-05-24 08-42-23](https://user-images.githubusercontent.com/5585851/58311045-fa3dd700-7dff-11e9-9c90-4a1f767cb7f6.png)

**Comment by goyney** [comment]
Here's another idea:
![image](https://user-images.githubusercontent.com/1015040/59921728-9dccd800-93fc-11e9-9520-d8dc8ca03301.png)

[iv-bag.svg.zip](https://github.com/Templarian/MaterialDesign/files/3314396/iv-bag.svg.zip)

**Comment by senyahnoj** [comment]
This looks perfect

**Comment by goyney** [comment]
[![iv-bag](https://materialdesignicons.com/icon/iv-bag)](https://materialdesignicons.com/icon/iv-bag)
