### ISSUE TITLE
home-account variant

### ISSUE THREAD

**Issue by Tom-ahawk** [Templarian/MaterialDesign#4164]
1. Like icon "home-account", but with the person (whole figure) outside the house.

~2. Moon faces (north and south hemispheres):~

**Comment by goyney** [comment]
Moon phases request is a duplicate of https://github.com/Templarian/MaterialDesign/issues/2603.

Renaming this issue for the first request.

**Comment by MrGrigri** [comment]
I don't think that would make a good icon. The perspective alone would look weird, let alone the constraints of a 20x20 pixel area.

**Comment by goyney** [comment]
I agree with @MrGrigri. @Tom-ahawk, can you explain what your use case was so we can brainstorm other ways to possibly handle it?

**Comment by Tom-ahawk** [comment]
Like the button on some control panels, ilustrating some one at home or not at home. 

https://images.app.goo.gl/gSyzCETN8UbbnZBH7

**Comment by MrGrigri** [comment]
I know that my Xfinity Home Security System uses a person (arm stay), a person running (arm away), and the moon with stars (arm night) to represent those three states.

We have each of those icons:

![human-handsdown](https://materialdesignicons.com/icon/human-handsdown) ![run](https://materialdesignicons.com/icon/run) ![weather-night](https://materialdesignicons.com/icon/weather-night)

**Comment by Tom-ahawk** [comment]
The run icon would work.
