### ISSUE TITLE
Missing equalizer icons in webfont

### ISSUE THREAD

**Issue by romaluca** [Templarian/MaterialDesign#4165]
Hi, in the list of icons there are:
https://materialdesignicons.com/icon/equalizer-outline
https://materialdesignicons.com/icon/equalizer

But it don't exist in the webfont:
https://cdn.materialdesignicons.com/3.6.95/

Could you add the icons to it?

Thanks!

**Comment by Templarian** [comment]
Looks like it was added _after_ our last release on April 24. We're working on icons for the next release.

https://dev.materialdesignicons.com/history

No timeline at the moment for that release. We're still about 40 icons away from the next release.

Using SVG's for any missing icons between releases is one solution we recommend.
