### ISSUE TITLE
'gift' icon has wrong positioning

### ISSUE THREAD

**Issue by breyvilas** [Templarian/MaterialDesign#4168]
Hi, I'm using @mdi/font at version 3.6.95, and it seems like the 'gift' icon is positioned wrong.
Wherever I put it, it will show up moved to the left by approximately 50% of its width.

Interestingly enough this happens only with the `gift` icon and not the `gift-outline` icon (or any other I've tested).

Here's a comparison. Normal (`gift-outline`):
![Screenshot_20190527_103741](https://user-images.githubusercontent.com/8677743/58407257-a6cfc100-806b-11e9-93f2-4e0690638e2f.png)

Wrong positioning (`gift`):

![Screenshot_20190527_103840](https://user-images.githubusercontent.com/8677743/58407277-b9e29100-806b-11e9-9b44-211bb8d57af9.png)

**Comment by Templarian** [comment]
Need to research why codepoint `fe85` would do that. @breyvilas What OS/Browser? Can you see it happening on the CDN also?

https://cdn.materialdesignicons.com/3.6.95/

**Comment by breyvilas** [comment]
It behaves like that at least in Chrome and Firefox under Ubuntu 18.04.
However, I cannot see the bug in the CDN page you linked.

**Comment by breyvilas** [comment]
Some more info: this happens on a fresh Vue application with nothing extra installed.

**Comment by breyvilas** [comment]
I've written a tiny test HTML page, and can verify it _doesn't_ happen here. It seems to be specific to Vue, or maybe the NPM package since this page loads the css from the CDN.

**Comment by Templarian** [comment]
@breyvilas I'm working on the next release tonight. `3.5.xx` did have issues like you explained, but I thought I had fixed them in `3.6.xx`.  When I release `3.7.xx` to NPM I'll have you update and test. If it persists we can look into it further.

**Comment by Templarian** [comment]
@breyvilas Can you retest with `3.7.95` that went out yesterday. Thanks.

**Comment by breyvilas** [comment]
@Templarian just tested, the bug seems to be gone in 3.7.95. Thanks!

**Comment by Templarian** [comment]
Awesome [in that's it is fixed, but not so much in that I didn't do anything different]. 😃
