### ISSUE TITLE
[Improvement] - Adding font-display: swap; to @font-face declaration

### ISSUE THREAD

**Issue by SirAuron** [Templarian/MaterialDesign#4169]
Hi all.
First of all let me thank you for your work on this project, it is really amazing.

Currently I'm working on optimizing our website to boost its performance.
I'm using the web font version of this project.
By running Chrome Lighthouse audits, the results warns me about this web font not having a [font-display](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-display) property set.
In my project I've solved this problem by importing all scss files but `_path.scss`, and declaring the font face once again with the new property added.

I think it can be useful to add this declaration to improve performance of the webfont loading and rendering.

**Comment by Templarian** [comment]
@SirAuron Catching up on issues at the moment. You can read about why we will be using the default behavior and other icon packs should also.

https://github.com/Templarian/MaterialDesign-Webfont/issues/47

**Comment by Templarian** [comment]
For context not rendering the icons produces a very different UI and would not be advised.

We _highly_ suggest not using the webfont. Please read more in the docs:

http://dev.materialdesignicons.com/guide/webfont-alternatives (SVG's are your friend! ❤️)

**Comment by SirAuron** [comment]
@Templarian Thank you for your reply and explanation, I'm sorry I did not manage to find the issue you linked before opening a new one (I try to avoid duplicate issues as much as possible).
And also thank you for your advice :) In the next iteration of the website I'll try to move the icons from the webfont to the SVG.
