### ISSUE TITLE
Question: difference between this and original site

### ISSUE THREAD

**Issue by madisotenurm** [Templarian/MaterialDesign#417]
With the I/O 2015, Google made an official site for Material design icons - https://www.google.com/design/icons/. 
However, compared to this site, it has much less icons. 
(I'm only looking at the ones that are marked as "made by google".)

Do you have any idea on why is that so?

**Comment by Templarian** [comment]
Yea, the stock icons have to be synced in still. Google overwrote their entire repo and didn't provide a change log so it is a manual process to find the new ones. Should be synced up in the next week or so.

Also, just to be clear the community site actually predates Google's official open source stock set. :)
