### ISSUE TITLE
map-marker-error

### ISSUE THREAD

**Issue by delphVdmbg** [Templarian/MaterialDesign#4170]
Would anyone be interested in producing an icon for map marker error?
Like the map-marker-check has a 'v' in it, the error would have a 'x' in it

**Comment by MrGrigri** [comment]
Would #4141 work?

**Comment by delphVdmbg** [comment]
No because I would use this one for a warning and not for an error

**Comment by MrGrigri** [comment]
It's a fine line between warning and error with iconography. An `x` inside the `map-marker` would designate closing the marker, not an error.

**Comment by delphVdmbg** [comment]
Yes, you're right. So, I would rather use the one you proposed and make the difference with colours.
Thank you.

**Comment by MrGrigri** [comment]
I would not suggest that, as well as 8% of men and 0.5% of women, suffer from colorblindness.

**Comment by delphVdmbg** [comment]
Ok, but how do you make the difference then?

**Comment by MrGrigri** [comment]
I would suggest, from a UI/UX background, that your errors are not displayed as a marker icon. Rather a clear verbal description of the error. That could be handled with a modal/dialog or some sort of persistent toast.

Either way, I'm going to close this issue out.
