### ISSUE TITLE
gamepad-variant-outline

### ISSUE THREAD

**Issue by joyfreak** [Templarian/MaterialDesign#4173]
Can you make one that has an outline please?

[![](https://materialdesignicons.com/icon/gamepad-variant)](https://materialdesignicons.com/icon/gamepad-variant)

**Comment by MrGrigri** [comment]
I'm not quite sure that I like it 24-pixels wide. But I feel that is the only way to keep it recognizable with such small buttons

[![gamepad-variant-outline.zip](https://user-images.githubusercontent.com/4528551/58721567-7d2bd800-8392-11e9-9d8e-b6a51a41e2fe.png)](https://github.com/Templarian/MaterialDesign/files/3242151/gamepad-variant-outline.zip)

**Comment by joyfreak** [comment]
Many thanks for doing this! I am assuming this will be added to the official list of icons?

**Comment by Templarian** [comment]
[![gamepad-variant-outline](https://materialdesignicons.com/icon/gamepad-variant-outline)](https://materialdesignicons.com/icon/gamepad-variant-outline)

**Comment by joyfreak** [comment]
Thanks for doing that. Is this icon in the latest release version?

**Comment by Templarian** [comment]
@joyfreak This milestone doesn't have a release date yet. But when it goes out it will be included. Until then use the vector (SVG if you're on web).
