### ISSUE TITLE
Blind Person

### ISSUE THREAD

**Issue by JWOverschot** [Templarian/MaterialDesign#4174]
This example image is from font awesome.  
Something in this direction could be nice to have.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/21358884/58806343-436b0380-8616-11e9-8c81-028713a30f58.png)  

maybe the walk icon is a good one the use as a base  
![walk](https://user-images.githubusercontent.com/21358884/58806764-2420a600-8617-11e9-9aed-679986cd5194.png)

**Comment by goyney** [comment]
They're called "white canes." Should we call it that as well, or do something like `human-blind`? I wonder if that carries negative connotation?
![image](https://user-images.githubusercontent.com/1015040/134228876-63fd26b6-6cfe-4012-8152-705aa495a5dc.png)
[human-white-cane.svg.zip](https://github.com/Templarian/MaterialDesign/files/7205439/human-white-cane.svg.zip)

**Comment by goyney** [comment]
[![human-white-cane](https://materialdesignicons.com/icon/human-white-cane)](https://materialdesignicons.com/icon/human-white-cane)
