### ISSUE TITLE
Offer stylesheet link to latest stable version

### ISSUE THREAD

**Issue by PanderMusubi** [Templarian/MaterialDesign#4176]
Please offer a link to the latest stable version of stylesheet:

    https://cdn.materialdesignicons.com/3.6.95/css/materialdesignicons.min.css

The URL could be

    https://cdn.materialdesignicons.com/stable/css/materialdesignicons.min.css

and offer the user the latest stable version.

**Comment by Templarian** [comment]
@PanderMusubi While I could easily put `3.6.95` into a folder called stable I'm not going to do that for a few reasons.

We have people still referencing every single version on the CDN (18TB+ a month). While it may be as simple as "no one would ever reference `stable` in production"... They definitely would. 😄 Our core team already hates the webfont and this would put them over the top if we got issues after every release (no one reads the [changelog](http://dev.materialdesignicons.com/changelog)).

Hopefully that makes sense. With that said, we are working on a way to publish nightly releases. These would be super unstable automatic builds every night. Pretty close to what you want with a much heavier emphasis on this may break between releases.

https://cdn.materialdesignicons.com/nightly/css/materialdesignicons.min.css
