### ISSUE TITLE
MultiLine-text-input

### ISSUE THREAD

**Issue by Delboyeire** [Templarian/MaterialDesign#4179]
![Multitextbox](https://user-images.githubusercontent.com/14996120/58936774-d6b84c00-8770-11e9-9c1d-a2abe7293747.png)

![Multitextbox](https://user-images.githubusercontent.com/14996120/58936837-01a2a000-8771-11e9-8ce6-21c869a4298e.png)

**Comment by goyney** [comment]
Duplicate of https://github.com/Templarian/MaterialDesign/issues/3533.
