### ISSUE TITLE
postage stamp-icon

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#418]
http://www.iconexperience.com/_img/i_collection_png/128x128/plain/postage_stamp.png

**Comment by CoDEmanX** [comment]
Quite delicate details if you follow this example:
![Imgur](http://i.imgur.com/OQnMZ3j.jpg)

**Comment by CoDEmanX** [comment]
It bends the icon guidelines a little to look like a stamp:
![postage-stamp](https://cloud.githubusercontent.com/assets/1309249/9235323/65e75254-413e-11e5-85ce-481675482601.png) https://www.dropbox.com/s/47iyzk921oyiz8g/postage-stamp.svg?dl=0

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37561718-3ccde50c-2a2c-11e8-8718-4fd61d3e204f.png)
I tried with 2px inner border but it left almost no space.

[Download link](https://github.com/Templarian/MaterialDesign/files/1822277/icons.zip)

**Comment by CoDEmanX** [comment]
How about making the cut outs 3px in diameter? The fringes look a bit too tiny.

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37768315-8495d802-2da3-11e8-87eb-53ec0cc94316.png)![image](https://user-images.githubusercontent.com/18645219/37768414-e645ffe6-2da3-11e8-8cdf-99eb06885f6c.png)
Left one looks like a memory chip, the right one is better I think.

[Download link](https://github.com/Templarian/MaterialDesign/files/1837297/icons.zip)

**Comment by PeterShaggyNoble** [comment]
Of the 3, my vote would go to the first one you posted.

**Comment by CoDEmanX** [comment]
3 and 3.5 pixel diameter for the cutouts doesn't work that good:

![post-stamp-3 5px](https://user-images.githubusercontent.com/1309249/37936078-726f852e-3154-11e8-94b1-52ff4edad82b.png) ![post-stamp-3px](https://user-images.githubusercontent.com/1309249/37936079-728b21c6-3154-11e8-9e1f-b8be371cbd16.png)

**Comment by CoDEmanX** [comment]
With a bit less cutout it's slightly better, using 4px diameter:

![image](https://user-images.githubusercontent.com/1309249/37936351-7e73b20e-3155-11e8-9418-0683e669b4b9.png)

**Comment by Croutonix** [comment]
[![image](https://user-images.githubusercontent.com/18645219/38322506-9b71c4b8-3808-11e8-8a1d-208e41939c5d.png)](https://github.com/Templarian/MaterialDesign/files/1876772/icon.zip)
With 4x5px ellipse cutouts and 1,5 px inner padding, that's the best I got.

**Comment by CoDEmanX** [comment]
Hm, the sun and the hills are not grid aligned anymore. Might be better to only use 1px margin instead.

The corners look small compared to the middle thingy. I tried to move the cutouts 0.5px towards the center, to make it more even:

![postage-stamp-3](https://user-images.githubusercontent.com/1309249/38328506-65c67ae6-384b-11e8-9c19-4e9d08f5c925.png)
![postage-stamp-3 4x](https://user-images.githubusercontent.com/1309249/38328505-65ac5dc8-384b-11e8-9696-90dfbfed97e1.png)

**Comment by CoDEmanX** [comment]
Download: [postage-stamp-3.zip](https://github.com/Templarian/MaterialDesign/files/1900546/postage-stamp-3.zip)

BTW: This is how it's solved in Nova icons: ![grafik](https://user-images.githubusercontent.com/1309249/38643638-1626d86c-3dde-11e8-9d1c-5594d088129f.png)

**Comment by JamesCoyle** [comment]
What about a variant with the account icon in it? Like a British stamp with the Queen on it.

**Comment by PeterShaggyNoble** [comment]
You raise a good point, @CodeManX; it's primarily monarchies and dictatorships that feature profiles of heads of state on their coinage and stamps, ehereas the rest of the world predominantly use national symbols. For example, and to the best of my knowledge, we've never had a current Irish head of state profiled on a stamp intended for genral circulation.

**Comment by CoDEmanX** [comment]
Haven't used many postage stamps in the recent years, but I remember from my childhood that there used to be special commemorate stamps with head profiles in Germany. Not exclusively for leaders of the country however, but people significant to national history in general.

**Comment by Templarian** [comment]
Added. We can come back to this later if there are other ideas/complaints/confusions.
