### ISSUE TITLE
Temperatures

### ISSUE THREAD

**Issue by leofuscaldi** [Templarian/MaterialDesign#4180]
Hi,

what about icons with common temperature values for A/C  and Heating?

Taking an A/C as example (I'll say in Degrees, but could be a range of fahrenheit too), icons with values from 17° to 30°...

**Comment by goyney** [comment]
We have this idea addressed in https://github.com/Templarian/MaterialDesign/issues/3291.

We also already have 0-9 numeric icons in the library. We've decided in the past we're not going to add anymore. You could use these icons to piece together larger numbers depending on your application and use. We also have `temperature-celsius/fahrenheit` that can be appended to the end.
