### ISSUE TITLE
CSV file icon

### ISSUE THREAD

**Issue by Mish325** [Templarian/MaterialDesign#4182]
![32](https://user-images.githubusercontent.com/19853627/59144894-04fc8c80-89fa-11e9-8f28-aaddcdc88b77.PNG)

This is from Fontawesome. Appreciate if you can provide this icon for Material Design Icons.

Thanks

**Comment by MrGrigri** [comment]
We already have a CSV file icon. It's labeled as `file-delimited`.

![file-delimited](https://materialdesignicons.com/icon/file-delimited)
