### ISSUE TITLE
calendar-repeat(-outline)

### ISSUE THREAD

**Issue by ToucanBran** [Templarian/MaterialDesign#4184]
I have:

- [x ] Searched open issues to make sure there isn't a request for this icon.
- [x ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/19380503/59162267-b8b95700-8aa2-11e9-876e-637214d5e5a6.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[reoccurringcalender.zip](https://github.com/Templarian/MaterialDesign/files/3269793/reoccurringcalender.zip)

**Comment by JamesCoyle** [comment]
I think this would be better with the icon in the bottom right to match `calendar-clock` and `calendar-search`. The arrows ideally need to be 2dp thick.

**Comment by MrGrigri** [comment]
Idk if the "day selection" is too much. What are y'all's thoughts?

![calendar-repeat](https://user-images.githubusercontent.com/4528551/59226307-f051fd00-8b8f-11e9-8562-9effabe69dd9.png) ![calendar-repeat-outline](https://user-images.githubusercontent.com/4528551/59226329-fea01900-8b8f-11e9-8d8f-6f95e8a058eb.png)

---

#### Files

[calendar-repeat.zip](https://github.com/Templarian/MaterialDesign/files/3273770/calendar-repeat.zip)

**Comment by ToucanBran** [comment]
I like this design a lot although I can see how the day select may be a bit
much especially if the icon is scaled down. I'd be interested in seeing
what it looks like without it.

**Comment by MrGrigri** [comment]
![calendar-repeat(sans-selection)](https://user-images.githubusercontent.com/4528551/59229289-38c0e900-8b97-11e9-8402-7d3a3463dc52.png) ![calendar-repeat-outline(sans-selection)](https://user-images.githubusercontent.com/4528551/59229323-47a79b80-8b97-11e9-98f1-cf3af4b9508b.png)

---

#### Files

[calendar-repeat.zip](https://github.com/Templarian/MaterialDesign/files/3273904/calendar-repeat.zip)

**Comment by ToucanBran** [comment]
Looks good to me

**Comment by Templarian** [comment]
Added both.

(My bro needed this one for work so it skips milestones 😜 )
