### ISSUE TITLE
ask.fm

### ISSUE THREAD

**Issue by illvart** [Templarian/MaterialDesign#4186]
Request Material Design Icons for [ASKfm](https://ask.fm/). Thanks!

**Comment by illvart** [comment]
I think this is official logo of ASKfm.

![apple-touch-icon-180x180](https://user-images.githubusercontent.com/24722231/59293859-55017a80-8caa-11e9-9b38-347b43389dc9.png)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
