### ISSUE TITLE
Visual Studio Code Update Icon

### ISSUE THREAD

**Issue by pixieaka** [Templarian/MaterialDesign#4187]
https://github.com/Microsoft/vscode-docs/blob/vnext/release-notes/v1_35.md

![Annotation 2019-06-12 101304](https://user-images.githubusercontent.com/17777237/59334421-b8b39400-8cfa-11e9-9a19-6c0423351111.jpg)

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/59356189-a8b2a900-8d28-11e9-8484-db811071f833.png)

Download: [vscode2019.zip](https://github.com/Templarian/MaterialDesign/files/3281657/vscode2019.zip)

Insiders variant doesn't work at native size:

![grafik](https://user-images.githubusercontent.com/1309249/59357639-7f474c80-8d2b-11e9-8eb1-02a0f451aab7.png)

**Comment by Templarian** [comment]
Updated.

[![visual-studio-code](https://materialdesignicons.com/icon/visual-studio-code)](https://materialdesignicons.com/icon/visual-studio-code)

**Comment by Templarian** [comment]
For anyone searching the insiders icon is nice, but a little niche for our pack.
