### ISSUE TITLE
Nuxt.js

### ISSUE THREAD

**Issue by m-ibrahim17** [Templarian/MaterialDesign#4189]
Hi there, how could I integrate the MDI with Nuxt.js?
Thanks

**Comment by Templarian** [comment]
@m-ibrahim17 Once you do figure out how be sure to reach out. We do like to document most frameworks. The smaller ones we'll need help form the community.

**Comment by m-ibrahim17** [comment]
1- Install MDI package **`npm install @mdi/font -D`**
2- In **nuxt.config.js** file add `@mdi/font/css/materialdesignicons.min.css` in your CSS configration, add `iconfont: 'mdi'` in vuetify module configuration
3- You can now use `mdi-**` icons in your ***.vue** files

**Comment by Templarian** [comment]
@m-ibrahim17 We don't really recommend using the webfont if you're using a framework that can use `@mdi/js`. http://dev.materialdesignicons.com/guide/webfont-alternatives

**Comment by goyney** [comment]
This issue is old and we don't recommend using the webfont anymore, so unfortunately those instructions won't be useful for us at this time.

If you would like to share how you are using `@mdi/js` with Nuxt.js, we'd be happy to include those in our documentation.

Thanks!
