### ISSUE TITLE
Hand icon

### ISSUE THREAD

**Issue by conundrumer** [Templarian/MaterialDesign#419]
It would be nice to have a hand icon, like that of the pan tool in Photoshop, Illustrator, and other graphics editors.

**Comment by Templarian** [comment]
Like the drag and drop hand? Not the [pointer](http://materialdesignicons.com/icon/cursor-pointer).

**Comment by conundrumer** [comment]
Oh, yea, drag-and-drop makes sense too!

**Comment by CoDEmanX** [comment]
A pointing hand could be derived from the remainder icon I posted, but a closed hand for dragging will look odds because there are no separation strokes between fingers...
