### ISSUE TITLE
Icon for Diagnosis(Dx), Hx, Vitals,  Service Orders

### ISSUE THREAD

**Issue by abhilashtg** [Templarian/MaterialDesign#4190]
Good to have more medical icons like Diagnosis(Dx), (History)Hx, Vitals,  Service Orders, Allergy, Patient Visits, Patient Referral, Lab Results

**Comment by goyney** [comment]
@abhilashtg We need examples of what you want included for each of these. Several can likely already be served by icons already in the library.

**Comment by goyney** [comment]
We have icons that work for most of the suggested types, or open issues with icons that could fit:
- Diagnosis - `clipboard-pulse`
- History - `history`, `chart-timeline`, `calendar`
- Vitals - `heart-pulse`, `clipboard-pulse`, `vitals`
- Allergy - `flower`, `flower-poppy`, `flower-tulip`, `tree`, `peanut` (#3488)
- Patient - #1416 
- Results - `clipboard-check`, `format-lists-check`

Unless there is something more specific, @abhilashtg, I'm going to recommend we close this issue.

**Comment by abhilashtg** [comment]
@goyney Thanks for suggesting the icons. It will suite. 
I am closing the issue.

Thank you..
