### ISSUE TITLE
Dashed rotate-(left|right) vs. Solid axis-(x|y|z)-[counter]clockwise

### ISSUE THREAD

**Issue by Crissov** [Templarian/MaterialDesign#4191]
+ [![mdi:rotate-left]][mdi:rotate-left] [![mdi:rotate-right]][mdi:rotate-right]
  + [![mdi:axis-x-rotate-clockwise]][mdi:axis-x-rotate-clockwise] [![mdi:axis-x-rotate-counterclockwise]][mdi:axis-x-rotate-counterclockwise]
  + [![mdi:axis-y-rotate-clockwise]][mdi:axis-y-rotate-clockwise] [![mdi:axis-y-rotate-counterclockwise]][mdi:axis-y-rotate-counterclockwise]
  + [![mdi:axis-z-rotate-clockwise]][mdi:axis-z-rotate-clockwise] [![mdi:axis-z-rotate-counterclockwise]][mdi:axis-z-rotate-counterclockwise]

While 2D rotation symbols are shown with a partially dashed arrow, 3D rotation symbols have completely solid arrows. This should probably be harmonized to either style.

[mdi:autorenew]: https://materialdesignicons.com/icon/autorenew
[mdi:rotate-left]: https://materialdesignicons.com/icon/rotate-left
[mdi:rotate-right]: https://materialdesignicons.com/icon/rotate-right
[mdi:reload]: https://materialdesignicons.com/icon/reload
[mdi:refresh]: https://materialdesignicons.com/icon/refresh
[mdi:restore]: https://materialdesignicons.com/icon/restore
[mdi:restore-clock]: https://materialdesignicons.com/icon/restore-clock
[mdi:update]: https://materialdesignicons.com/icon/update
[mdi:history]: https://materialdesignicons.com/icon/history
[mdi:axis-x-rotate-clockwise]: https://materialdesignicons.com/icon/axis-x-rotate-clockwise
[mdi:axis-x-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-x-rotate-counterclockwise
[mdi:axis-y-rotate-clockwise]: https://materialdesignicons.com/icon/axis-y-rotate-clockwise
[mdi:axis-y-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-y-rotate-counterclockwise
[mdi:axis-z-rotate-clockwise]: https://materialdesignicons.com/icon/axis-z-rotate-clockwise
[mdi:axis-z-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise

**Comment by goyney** [comment]
The 2d rotates were made by Google, so they will obviously stay as is.

The 3d rotates are more complicated in nature, and adding dashed portions of the lines will likely make the icon less distinguishable at native size.

I recommend we reject this issue.
