### ISSUE TITLE
vertical-rotate-[counter]clockwise = axiz-z-rotate-[counter]clockwise

### ISSUE THREAD

**Issue by Crissov** [Templarian/MaterialDesign#4192]
+ [![mdi:axis-z-rotate-clockwise]][mdi:axis-z-rotate-clockwise] [![mdi:axis-z-rotate-counterclockwise]][mdi:axis-z-rotate-counterclockwise] 

This pair, `mdi:axis-z-rotate-[counter]clockwise`, should have aliases `mdi:vertical-rotate-[counter]clockwise` which could then be paired with a new `mdi:horizontal-rotate-[counter]clockwise`. #4193

[mdi:autorenew]: https://materialdesignicons.com/icon/autorenew
[mdi:rotate-left]: https://materialdesignicons.com/icon/rotate-left
[mdi:rotate-right]: https://materialdesignicons.com/icon/rotate-right
[mdi:reload]: https://materialdesignicons.com/icon/reload
[mdi:refresh]: https://materialdesignicons.com/icon/refresh
[mdi:restore]: https://materialdesignicons.com/icon/restore
[mdi:restore-clock]: https://materialdesignicons.com/icon/restore-clock
[mdi:update]: https://materialdesignicons.com/icon/update
[mdi:history]: https://materialdesignicons.com/icon/history
[mdi:axis-x-rotate-clockwise]: https://materialdesignicons.com/icon/axis-x-rotate-clockwise
[mdi:axis-x-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-x-rotate-counterclockwise
[mdi:axis-y-rotate-clockwise]: https://materialdesignicons.com/icon/axis-y-rotate-clockwise
[mdi:axis-y-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-y-rotate-counterclockwise
[mdi:axis-z-rotate-clockwise]: https://materialdesignicons.com/icon/axis-z-rotate-clockwise
[mdi:axis-z-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise

**Comment by goyney** [comment]
Aliases added.
