### ISSUE TITLE
horizontal-rotate-[counter]clockwise

### ISSUE THREAD

**Issue by Crissov** [Templarian/MaterialDesign#4193]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [x] Only requested a single icon in this issue. &ndash; Well, a mirrored pair.

## Usage

In #4192, I requested aliases `mdi:vertical-rotate-[counter]clockwise` for 3D rotation around the upright, vertical (with regards to the 2D drawing canvas) axis, which is labeled _z_ here, but _y_ is common elsewhere. These would be paired with a new mirrored pair of symbols `mdi:horizontal-rotate-[counter]clockwise` for 3D rotation around the *horizontal* axis, which is labeled _y_ here, but _x_ elsewhere.

  + [![mdi:axis-z-rotate-clockwise]][mdi:axis-z-rotate-clockwise] [![mdi:axis-z-rotate-counterclockwise]][mdi:axis-z-rotate-counterclockwise] 

## Examples

The difference to the existing _x_ and _y_ rotation symbols would be a straight horizontal, non-skewed rotation axis, i.e. the _z_ images rotated by a quarter turn (90°).

  + [![mdi:axis-x-rotate-clockwise]][mdi:axis-x-rotate-clockwise] [![mdi:axis-x-rotate-counterclockwise]][mdi:axis-x-rotate-counterclockwise]
  + [![mdi:axis-y-rotate-clockwise]][mdi:axis-y-rotate-clockwise] [![mdi:axis-y-rotate-counterclockwise]][mdi:axis-y-rotate-counterclockwise]

## Related

- #4191 (line style)
- ~~#3812~~ `rotate-360`
- The English language does not have a word like _horizontal_ and _vertical_ for the depth axis along the line of sight, which is labeled _x_ here_ but _z_ is common elsewhere, so there would not be a like name for rotation around this axis where it would be shown as a circle in the middle of this pair:
  + [![mdi:rotate-left]][mdi:rotate-left] [![mdi:rotate-right]][mdi:rotate-right] 
  + [![mdi:backup-restore]][mdi:backup-restore] 

[mdi:autorenew]: https://materialdesignicons.com/icon/autorenew
[mdi:rotate-left]: https://materialdesignicons.com/icon/rotate-left
[mdi:rotate-right]: https://materialdesignicons.com/icon/rotate-right
[mdi:reload]: https://materialdesignicons.com/icon/reload
[mdi:refresh]: https://materialdesignicons.com/icon/refresh
[mdi:restore]: https://materialdesignicons.com/icon/restore
[mdi:restore-clock]: https://materialdesignicons.com/icon/restore-clock
[mdi:backup-restore]: https://materialdesignicons.com/icon/backup-restore
[mdi:update]: https://materialdesignicons.com/icon/update
[mdi:history]: https://materialdesignicons.com/icon/history
[mdi:axis-x-rotate-clockwise]: https://materialdesignicons.com/icon/axis-x-rotate-clockwise
[mdi:axis-x-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-x-rotate-counterclockwise
[mdi:axis-y-rotate-clockwise]: https://materialdesignicons.com/icon/axis-y-rotate-clockwise
[mdi:axis-y-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-y-rotate-counterclockwise
[mdi:axis-z-rotate-clockwise]: https://materialdesignicons.com/icon/axis-z-rotate-clockwise
[mdi:axis-z-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/59958044-744c9480-946e-11e9-963a-2ec38e79683a.png)![image](https://user-images.githubusercontent.com/1015040/59958057-98a87100-946e-11e9-8956-0fc828616652.png)

[horizontal-rotate.zip](https://github.com/Templarian/MaterialDesign/files/3316437/horizontal-rotate.zip)

I'll let @Templarian figure out the naming convention for these.

**Comment by goyney** [comment]
[![horizontal-rotate-clockwise](https://materialdesignicons.com/icon/horizontal-rotate-clockwise)](https://materialdesignicons.com/icon/horizontal-rotate-clockwise)[![horizontal-rotate-counterclockwise](https://materialdesignicons.com/icon/horizontal-rotate-counterclockwise)](https://materialdesignicons.com/icon/horizontal-rotate-counterclockwise)
