### ISSUE TITLE
autorenew, cached = Clockwise Circular Arrows

### ISSUE THREAD

**Issue by Crissov** [Templarian/MaterialDesign#4194]
[![mdi:autorenew]][mdi:autorenew] [![mdi:cached]][mdi:cached] [![mdi:autoreload]][mdi:autoreload] [![mdi:sync]][mdi:sync]

I [searched](https://materialdesignicons.com/) for `circle`, `circular`, `clockwise` and `arrow`, but [`mdi:autorenew`](https://materialdesignicons.com/icon/autorenew) and [`mdi:cached`](https://materialdesignicons.com/icon/cached) did not show up for any of these keywords nor the `Arrow` tag. I suggest to add aliases like `mdi:circular-arrows-clockwise` and `mdi:circular-arrows-clockwise-variant` or `mdi:circular-arrows-vertical` and `mdi:circular-arrows-horizontal`.

I also believe there should be (and shall therefore raise issues for, although most can be achieved with manual rotation and mirroring of existing symbols):

- mirrored, hence counter-clockwise versions `mdi:circular-arrows-counterclockwise` or `mdi:circular-arrows-counterclockwise-variant`
- similar aliases (`mdi:circular-arrow-[counter]clockwise`) and keywords for variants with a single arrow head like these:
  + [![mdi:rotate-left]][mdi:rotate-left] [![mdi:rotate-right]][mdi:rotate-right]
  + [![mdi:reload]][mdi:reload] [![mdi:refresh]][mdi:refresh] [![mdi:update]][mdi:update]
  + [![mdi:restore]][mdi:restore] [![mdi:restore-clock]][mdi:restore-clock] [![mdi:history]][mdi:history]
- *perhaps* variants with the `mdi:refresh` arrow head

[mdi:autorenew]: https://materialdesignicons.com/icon/autorenew
[mdi:autoreload]: https://materialdesignicons.com/icon/autoreload
[mdi:cached]: https://materialdesignicons.com/icon/cached
[mdi:sync]: https://materialdesignicons.com/icon/sync
[mdi:rotate-left]: https://materialdesignicons.com/icon/rotate-left
[mdi:rotate-right]: https://materialdesignicons.com/icon/rotate-right
[mdi:reload]: https://materialdesignicons.com/icon/reload
[mdi:refresh]: https://materialdesignicons.com/icon/refresh
[mdi:restore]: https://materialdesignicons.com/icon/restore
[mdi:restore-clock]: https://materialdesignicons.com/icon/restore-clock
[mdi:update]: https://materialdesignicons.com/icon/update
[mdi:history]: https://materialdesignicons.com/icon/history
[mdi:axis-x-rotate-clockwise]: https://materialdesignicons.com/icon/axis-x-rotate-clockwise
[mdi:axis-x-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-x-rotate-counterclockwise
[mdi:axis-y-rotate-clockwise]: https://materialdesignicons.com/icon/axis-y-rotate-clockwise
[mdi:axis-y-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-y-rotate-counterclockwise
[mdi:axis-z-rotate-clockwise]: https://materialdesignicons.com/icon/axis-z-rotate-clockwise
[mdi:axis-z-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise

**Comment by goyney** [comment]
Aliases for [counter]clockwise, circular, and circle arrows added to `autorenew`, `cached`, and `sync`.

We will not be adding other variants of circular arrows in different rotations because that's a slippery slope. Most of those variations come from the Google library, which is why they are included. As you stated, simple CSS transformations can handle rotating these icons just fine.
