### ISSUE TITLE
Circular arrow inconsistency

### ISSUE THREAD

**Issue by Crissov** [Templarian/MaterialDesign#4195]
+ [![mdi:reload]][mdi:reload] [![mdi:refresh]][mdi:refresh] [![mdi:update]][mdi:update]
  + [![mdi:restore]][mdi:restore] [![mdi:restore-clock]][mdi:restore-clock] [![mdi:history]][mdi:history]
  + [![mdi:loop]][mdi:loop] [![mdi:replay]][mdi:replay] [![mdi:restart]][mdi:restart] 

`mdi:history` is the same as `mdi:restore-clock` and both differ from `mdi:restore` only by the added clock hands. This is the same difference as between `mdi:update` and `mdi:refresh`. Alas, `mdi:refresh` and `mdi:restore` are not simple mirrored variants of each other, but `mdi:restore` and `mdi:reload` are!

I suggest two changes to fix this inconsistency:

- Make `mdi:history` (but not `mdi:restore-clock`) use the mirrored arrow style from `mdi:update` and `mdi:refresh`.
- Add `mdi:reload-clock` by adding clock hands to `mdi:reload`.

PS: There also seem to be some differences in diameter, position and line thickness, which _may_ be intentional.

[mdi:autorenew]: https://materialdesignicons.com/icon/autorenew
[mdi:rotate-left]: https://materialdesignicons.com/icon/rotate-left
[mdi:rotate-right]: https://materialdesignicons.com/icon/rotate-right
[mdi:reload]: https://materialdesignicons.com/icon/reload
[mdi:refresh]: https://materialdesignicons.com/icon/refresh
[mdi:restore]: https://materialdesignicons.com/icon/restore
[mdi:restore-clock]: https://materialdesignicons.com/icon/restore-clock
[mdi:restart]: https://materialdesignicons.com/icon/restart
[mdi:update]: https://materialdesignicons.com/icon/update
[mdi:history]: https://materialdesignicons.com/icon/history
[mdi:replay]: https://materialdesignicons.com/icon/replay
[mdi:loop]: https://materialdesignicons.com/icon/loop
[mdi:axis-x-rotate-clockwise]: https://materialdesignicons.com/icon/axis-x-rotate-clockwise
[mdi:axis-x-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-x-rotate-counterclockwise
[mdi:axis-y-rotate-clockwise]: https://materialdesignicons.com/icon/axis-y-rotate-clockwise
[mdi:axis-y-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-y-rotate-counterclockwise
[mdi:axis-z-rotate-clockwise]: https://materialdesignicons.com/icon/axis-z-rotate-clockwise
[mdi:axis-z-rotate-counterclockwise]: https://materialdesignicons.com/icon/axis-z-rotate-counterclockwise

**Comment by goyney** [comment]
The following icons are from Google's set and will not be modified: `refresh`, `update`, `restore`, `restore-clock`, `history`, `replay`, and `restart`.

The `reload` icon's arrowhead is off and needs to be updated:

![image](https://user-images.githubusercontent.com/1015040/59957967-3ef37700-946d-11e9-986c-bbf5f95a5d30.png)
(Our current is the outline.)
[reload.svg.zip](https://github.com/Templarian/MaterialDesign/files/3316429/reload.svg.zip)

The `loop` icon is so similiar to others, I actually recommend we remove it and alias any of the other icons as `loop`. @Templarian, thoughts on this?

**Comment by goyney** [comment]
I've updated `reload`.

Leaving this open to further discuss removing the `loop` icon.

**Comment by Templarian** [comment]
Yeah, we can probably remove loop in the `4.0` release.

**Comment by goyney** [comment]
Moving to the 4.0 milestone.

**Comment by goyney** [comment]
`loop` has been removed. Aliases added to `restore`, `reload`, `refresh`.
