### ISSUE TITLE
calendar-weekend

### ISSUE THREAD

**Issue by Crissov** [Templarian/MaterialDesign#4197]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [ ] Only requested a single icon in this issue. &ndash; I'm requesting multiple symbols that are visually and semantically *very* similar, so make sense to be tracked collectively.

## Usage

[![mdi:calendar-week]][mdi:calendar-week] [![mdi:calendar-week-begin]][mdi:calendar-week-begin]
[![mdi:calendar-range]][mdi:calendar-range] [![mdi:calendar-range-outline]][mdi:calendar-range-outline]

There are symbols for a calendar week and the start of the week, but none for the **weekend** or **weekends** (which, [variably throughout the world](https://www.unicode.org/cldr/charts/latest/supplemental/territory_information.html), means one or two consecutive days from Friday, Saturday and Sunday). I suggest this would be shown as a mirrored variant of `calendar-week-begin` (for *weekend*) or like `calendar-range` with two or three vertical square dots on the right-hand side (for *weekend**s***). 

For implementing a visual switch between US **Su**-Mo-&hellip;-Fr-**Sa** and international Mo-&hellip;-Fr-**Sa-Su** week layouts, it might also be helpful to have a calendar icon with one vertical line on the left and one on the right-hand side: `calendar-weekend-split`.

For implementing a visual switch between single-day, e.g. Mo-&hellip;-Fr-Sa-**Su**, and double-day weekend, e.g. Mo-&hellip;-Fr-**Sa-Su**, it might also be helpful to have a calendar icon with either a thicker vertical line or two thin vertical lines on the right, alternatively two or three *rectangular* (2:1) dots: `calendar-weekend-day` and  `calendar-weekend-days`. 

For implementing a visual toggle for week numbers, it might also be helpful to have a calendar icon with two or three vertical square dots on the left-hand side: `calendar-week-number`. 

## Examples

![calendar-weekend: M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M9,10H17V17H15V10Z](https://user-images.githubusercontent.com/6200185/59518257-99b52d80-8ec5-11e9-9087-dcb825998979.png) ![calendar-weekends: M17,10V12H15V10H17M19,3A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5C3.89,21 3,20.1 3,19V5A2,2 0 0,1 5,3H6V1H8V3H16V1H18V3H19M19,19V8H5V19H19M17,14V16H15V14H17Z](https://user-images.githubusercontent.com/6200185/59518432-e8fb5e00-8ec5-11e9-87f6-7761d424e31d.png)

![calendar-weekend-split: M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,10H17V17H15V10M9,10H7V17H9V10Z](https://user-images.githubusercontent.com/6200185/59518659-60c98880-8ec6-11e9-9351-35d4e9a9fa49.png) ![calendar-weekend-split: M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M17,10H17V17H16V10M8,10H7V17H8V10Z](https://user-images.githubusercontent.com/6200185/59518992-362bff80-8ec7-11e9-8695-c1a34eed977f.png)

![calendar-weekend-day: M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M16,10H17V17H16V10Z](https://user-images.githubusercontent.com/6200185/59518796-bef66b80-8ec6-11e9-8996-55911dca8b21.png) ![calendar-weekend-days: M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M16,10H17V17H14V10Z](https://user-images.githubusercontent.com/6200185/59518835-d7668600-8ec6-11e9-8697-1cef0ef55af8.png)

![calendar-weekend-day: M17,10V12H15V10H17M19,3A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5C3.89,21 3,20.1 3,19V5A2,2 0 0,1 5,3H6V1H8V3H16V1H18V3H19M19,19V8H5V19H19M17,14V16H15V14H17Z](https://user-images.githubusercontent.com/6200185/59519131-7db28b80-8ec7-11e9-8100-b2bbd8d93ed6.png) ![calendar-weekend-days: M19,3A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5C3.89,21 3,20.1 3,19V5A2,2 0 0,1 5,3H6V1H8V3H16V1H18V3H19M19,19V8H5V19H19M17,14V16H13V14H17M17,10V12H13V10H17Z](https://user-images.githubusercontent.com/6200185/59519267-c4a08100-8ec7-11e9-8a31-c1afa2aacc2c.png)

![calendar-week-number: M9,10V12H7V10H9M19,3A2,2 0 0,1 21,5V19A2,2 0 0,1 19,21H5C3.89,21 3,20.1 3,19V5A2,2 0 0,1 5,3H6V1H8V3H16V1H18V3H19M19,19V8H5V19H19M9,14V16H7V14H9Z](https://user-images.githubusercontent.com/6200185/59517972-07148e80-8ec5-11e9-8e1b-a1b4242480c2.png)

![calendar-workdays: M19,19H5V8H19M16,1V3H8V1H6V3H5C3.89,3 3,3.89 3,5V19A2,2 0 0,0 5,21H19A2,2 0 0,0 21,19V5C21,3.89 20.1,3 19,3H18V1M7,10h8v2h-8v-2Z](https://user-images.githubusercontent.com/6200185/59520334-02060e00-8eca-11e9-867f-bb4cbed7e7bf.png)

[mdi:calendar-week]: https://materialdesignicons.com/icon/calendar-week "mdi:calendar-week"
[mdi:calendar-week-begin]: https://materialdesignicons.com/icon/calendar-week-begin "mdi:calendar-week-begin"
[mdi:calendar-range]: https://materialdesignicons.com/icon/calendar-range "mdi:calendar-range"
[mdi:calendar-range-outline]: https://materialdesignicons.com/icon/calendar-range-outline "mdi:calendar-range-outline"

**Comment by Templarian** [comment]
Added a `calendar-weekend` and `calendar-weekend`. They are assigned to a placeholder account for you.
