### ISSUE TITLE
finance

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4198]
Google has just updated its `finance` icon. Here is the comparison. 

![image](https://user-images.githubusercontent.com/4528551/59519245-a8c7bb80-8e84-11e9-8cd2-136222df68cd.png) ![image](https://user-images.githubusercontent.com/4528551/59519411-06f49e80-8e85-11e9-9083-3d6dc68d25a8.png)

---
#### Files

[finance.zip](https://github.com/Templarian/MaterialDesign/files/3291201/finance.zip)

**Comment by Templarian** [comment]
Updated. 😃

**Comment by abons** [comment]
I preferred the old finance icon, why is this not added as -variant?
