### ISSUE TITLE
truck-time

### ISSUE THREAD

**Issue by pixieaka** [Templarian/MaterialDesign#4199]
Like `mdi-truck-check` but with clock instead of check

**Comment by MrGrigri** [comment]
due to constraints and MD Guidelines, the clock inside the truck as a cutout will not work. Do you have another example?

**Comment by pixieaka** [comment]
![Capture](https://user-images.githubusercontent.com/17777237/59642704-6c3adf00-9166-11e9-8523-edc0d862d910.PNG)

**Comment by MrGrigri** [comment]
The clock will not be placed inside the truck because of the Material Design guidelines. I was able to shrink the truck for the modifier to work in the top right.

[![truck-time.zip](https://user-images.githubusercontent.com/4528551/59695118-ebe89e00-91a6-11e9-9dee-6f6242dc79f7.png)](https://github.com/Templarian/MaterialDesign/files/3302104/truck-time.zip)

**Comment by pixieaka** [comment]
Can we put clock inside truck like mdi-truck-check
![{5DDD4C7C-DBFE-45AD-ADDD-BDFC13FB65DB} png](https://user-images.githubusercontent.com/17777237/59695562-bb2a5800-91ea-11e9-9ac4-55e86109d0bd.jpg)

**Comment by MrGrigri** [comment]
No, as I stated earlier, it wouldn't conform to Material Design Guidelines.

**Comment by pixieaka** [comment]
It's fine that way thank you for add it @MrGrigri

**Comment by pixieaka** [comment]
Can we change [ mdi-truck-check, mdi-truck-delivery ] to match this icon to be full set in same theme

**Comment by MrGrigri** [comment]
I do not believe that will happen.

**Comment by pixieaka** [comment]
okay without replace it we can add new 3 icons to be same theme with prefix like outside
[ mdi-truck-outside-check, mdi-truck-outside-delivery, mdi-truck-outside-check ] @MrGrigri

**Comment by MrGrigri** [comment]
Add them as separate requests please

**Comment by pixieaka** [comment]
okay #4201, #4202 but can you now change truck time with prefix outside

**Comment by MrGrigri** [comment]
No, we have a very strict naming convention.

**Comment by pixieaka** [comment]
@MrGrigri  but mdi-truck-check, mdi-truck-delivery it's already exists, so when add it in it must to add prefix to it. i mean it can be same theme with name & icon theme in same time to be easy to memorize it.

**Comment by MrGrigri** [comment]
Don't worry about that, that's our job. If those other icons are added, we'll name them at that time. This one will be `truck-time`.
