### ISSUE TITLE
Icon Chat outline

### ISSUE THREAD

**Issue by romaluca** [Templarian/MaterialDesign#4200]
Is possible add icon chat outline?

There is only the normal version:
[https://materialdesignicons.com/icon/chat](https://materialdesignicons.com/icon/chat)

Thanks!

**Comment by MrGrigri** [comment]
[![chat-outline.zip](https://user-images.githubusercontent.com/4528551/59631979-5b5a8100-9106-11e9-9729-7e9912eb2591.png)](https://github.com/Templarian/MaterialDesign/files/3298589/chat-outline.zip)

**Comment by Templarian** [comment]
Added. 😃
