### ISSUE TITLE
New Facebook Messenger

### ISSUE THREAD

**Issue by kiernann** [Templarian/MaterialDesign#4203]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Facebook updates the icon to the Messenger platform. It's a little more round with softer round edges, which might actually go well with the Material Design theme.

## Examples

![image](https://user-images.githubusercontent.com/18021678/59813426-6a485b80-92df-11e9-9fa3-a5969f9e9377.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/59921247-1894f380-93fb-11e9-9a37-d55982157713.png)

[facebook-messenger.svg.zip](https://github.com/Templarian/MaterialDesign/files/3314364/facebook-messenger.svg.zip)

**Comment by Templarian** [comment]
Updated. 😃
