### ISSUE TITLE
file-table-box

### ISSUE THREAD

**Issue by charlax** [Templarian/MaterialDesign#4205]
I have:

- [X] Searched all issues to make sure there isn't a request for this icon.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

Note: #1966 exists but was actually named `google-spreadsheet`

Also: `file-table` exists, perhaps `file-table-box` instead?

## Usage

In a file explorer, I would like to have box file icon for CSV files, ODS (Open Office/LibreOffice). Just like there is a generic `file-presentation-box`.

## Examples

Take inspiration from: https://materialdesignicons.com/icon/file-table ?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/59921039-7aa12900-93fa-11e9-8673-3edd47558221.png)![image](https://user-images.githubusercontent.com/1015040/59921048-8260cd80-93fa-11e9-8f62-b1b53beda9ae.png)
![image](https://user-images.githubusercontent.com/1015040/59921056-8ab90880-93fa-11e9-9d62-0b2fd276871b.png)![image](https://user-images.githubusercontent.com/1015040/59921065-90aee980-93fa-11e9-8b30-01ced3c5c399.png)

[file-table-box.zip](https://github.com/Templarian/MaterialDesign/files/3314349/file-table-box.zip)

**Comment by charlax** [comment]
Wow that's fast! :)

**Comment by goyney** [comment]
[![file-table-box](https://materialdesignicons.com/icon/file-table-box)](https://materialdesignicons.com/icon/file-table-box)[![file-table-box-outline](https://materialdesignicons.com/icon/file-table-box-outline)](https://materialdesignicons.com/icon/file-table-box-outline)
[![file-table-box-multiple](https://materialdesignicons.com/icon/file-table-box-multiple)](https://materialdesignicons.com/icon/file-table-box-multiple)[![file-table-box-multiple-outline](https://materialdesignicons.com/icon/file-table-box-multiple-outline)](https://materialdesignicons.com/icon/file-table-box-multiple-outline)
