### ISSUE TITLE
[4.0] Add deprecation notice for brand icons

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4206]
As per [Material Design Icon's policy on brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons), we will need to begin notification procedures starting in version `4.0.xx` of our intent to deprecate all current brand icons. (See the end of this post for a list of icons that will be affected by this deprecation.)

We will need to add appropriate notices to the README files of each `@mdi/*` package, as well as notices to the MDI site, and any other appropriate places.

We will continue to point people to [SimpleIcons](https://simpleicons.org/) for their brand icon needs and work with them to migrate some of the icons we currently have, but they do not. If there is an icon in the below list you use, please check SimpleIcons to see if it is included. If it is not, please request the icon [via their GitHub issue tracker](https://github.com/simple-icons/simple-icons/issues) so it may get added.

All deprecated brand icons will continue to be part of Material Design Icon packages until *at least* version `5.0.xx`.

---

Icons to be deprecated in version `4.0.xx`: _(*List subject to change)_

| brand | remove | reason |
|-----|-----|----|
| accusoft | x | niche |
| adchoices |  | useful |
| adobe | | tech |
| amazon | | tech |
| alexa | | tech |
| amazon-drive | | tech |
| apple-finder | | tech |
| apple-icloud | | tech |
| apple-ios | | tech |
| artstation | | social media |
| atlassian | | tech |
| bandcamp | | social media |
| basecamp | x | niche |
| battlenet | | gaming |
| beats | x | niche |
| behance | x | niche |
| blackberry | x | dead |
| blender-software | | tech |
| box | | tech |
| buffer | x | niche |
| cisco-webex | | business |
| cryengine | | gaming |
| dev-to | | social media |
| deviantart | | social media |
| discord | | tech |
| disqus | | tech |
| disqus-outline | | tech |
| dlna | | media |
| dolby | | media |
| douban | | no reason to remove yet |
| dribble | x | niche |
| dribble-box | x | niche |
| dropbox | | tech |
| emby | | media |
| etsy | x | brand doesn't fit |
| eventbrite | x | brand doesn't fit |
| evernote | | almost dead, but we'll keep it for now |
| facebook  | | social media |
| facebook-box | | social media |
| facebook-messenger  | | social media |
| facebook-workplace | | tech |
| flattr | x | dead |
| foursquare | x | dead |
| glassdoor | x | meh |
| gog | | gaming |
| hackernews | | geek cred |
| home-assistant | | we like them |
| houzz | x | niche |
| houzz-box | x | niche |
| hulu | | tech |
| humble-bundle | | gaming |
| instagram | | social media |
| instapaper | x | niche |
| itunes | x | niche |
| jabber | | tech |
| jira | | tech |
| kickstarter | | social media |
| kodi | | tech |
| lastfm | x | does not fit |
| lastpass | | tech |
| linkedin | | social media |
| linkedin-box | | social media |
| lyft | x | tech |
| mail-ru | x | niche |
| mastodon | | social media |
| mastodon-variant | | social media |
| medium | x | niche |
| meetup | x | niche |
| microsoft | | tech |
| microsoft-dynamics | | tech |
| midi | | tech |
| minecraft | | cute |
| mixcloud | x | niche |
| mixer | | gaming |
| netflix | | media |
| nintendo-switch | | gaming |
| odnoklassniki | | social media |
| office | | tech |
| onedrive | | tech |
| onenote | | tech |
| onepassword | | tech |
| origin | | gaming |
| pandora | | media |
| patreon | | tech |
| paypal | x | payment |
| periscope | x | dead |
| pi-hole | | tech |
| pinterest | | social media |
| pinterest-box | | social media |
| playstation | | gaming |
| plex | | tech |
| pocket | x | niche |
| qqchat | | nostalgia |
| quicktime | x | dead? |
| reddit | | nerds |
| salesforce | | I work there, so keeping this one |
| shopify | x | meh |
| sina-weibo | | social media |
| skype | | tech |
| skype-business  | | tech |
| slackware | x | niche |
| snapchat | | social media |
| soundcloud | | social media |
| spotify | | tech |
| square-inc | x | payment |
| square-inc-cash | x | payment |
| steam | | gaming |
| steam-box | | gaming, for now |
| strava | x | niche |
| teamviewer | | tech |
| telegram |  | social media, for now |
| tor | x | niche |
| trello | | tech |
| tumblr | x | niche |
| tumblr-box | x | niche |
| tumblr-reblog | x | niche |
| twitch | | gaming |
| twitter | | social media |
| twitter-box | | social media |
| twitter-circle | | social media |
| uber | x | niche |
| umbraco | | platform |
| unity | | tech |
| unreal | | tech |
| untappd | | social media |
| venmo | x | payment |
| vimeo | | tech |
| vk | | social media |
| vk-box | | social media |
| vk-circle | | social media |
| vlc | | tech |
| wechat | | tech |
| whatsapp | | tech |
| wii | | gaming |
| wiiu | | gaming |
| wikipedia | | like it |
| windows-classic | | nostalgic |
| wordpress | | web tech |
| wunderlist | x | niche |
| xbox | | gaming |
| xda | x | niche |
| xing | | social media |
| xing-box | | social media |
| xmpp | | tech |
| yahoo | | nostalgic |
| yammer | | social media |
| yelp | x | niche |

**Comment by Templarian** [comment]
After 4.0 any with an x in the remove column will show with a red slash in the website and a tooltip explaining the deprecation.

Story time: I have the poster from when we hit 2k icons over my desk and it's entertaining to look at how many of those brands no longer around. There are a few dead brands we may remove from 4.0 also.
