### ISSUE TITLE
Add ginlime as a Contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#4207]
Welcome, @ginlime! Since you've hit at least 5 icon contributions, we'd like to make sure you get credit for your efforts.

Please optionally provide us with the follow for your profile:
- [ ] Your Name
- [x] Twitter
- [ ] Website
- [x] Short bio (like 250 words max)

---

**Icons to assign:**

- [x] arrow-up-down
- [ ] arrow-left-right
- [ ] arrow-top-left-bottom-right
- [ ] arrow-top-right-bottom-left
- [ ] vanish
- [ ] double-circle

**Comment by Templarian** [comment]
Other than #4153 which ones have you added so I can reassign them?

**Comment by ginlime** [comment]
@Templarian I added #2055 and #2363.

My Twitter is @ginlime (sorry, written in Japanese mainly)

My short bio:
A UI designer.
I’ｍ interested in UI design, front-end technologies.

**Comment by Templarian** [comment]
Sorry that took so long. Lot of re-coding the admin tooling. Hopefully open it to more than the core team shortly. Once updates are done you'll be able to edit this profile info.

The core team will now assign icons you create to this account. Thanks!
