### ISSUE TITLE
fishbowl

### ISSUE THREAD

**Issue by MiguelAngelLV** [Templarian/MaterialDesign#4208]
I need a aquarium icon. Maybe a circular aquarium with the icon fish in should be enought.

I am using the fish icon, but, a aquarium icon could be better.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/60059631-427c3d80-96bb-11e9-9c2e-69c7522c7666.png)![image](https://user-images.githubusercontent.com/1015040/60059622-3bedc600-96bb-11e9-98a4-cc75e4a6ea00.png)

[fishbowl.zip](https://github.com/Templarian/MaterialDesign/files/3323012/fishbowl.zip)

**Comment by goyney** [comment]
Can alias this to `aquarium` and `aquarium-outline` as well.

**Comment by Templarian** [comment]
Added. 😃 Added the alias also... but a fish tank is a boring aquarium.
