### ISSUE TITLE
Unit Load Device (ULD) Icon

### ISSUE THREAD

**Issue by ButchMonkey** [Templarian/MaterialDesign#4209]
This is an icon for a ULD - https://en.wikipedia.org/wiki/Unit_load_device
These are the containers that are filled with bags and cargo to be loaded onto aircrafts

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

[![image](https://user-images.githubusercontent.com/9367266/60176551-89c71300-980e-11e9-9a5e-a0984b7d27da.png)](https://github.com/Templarian/MaterialDesign/files/3329753/uld.zip)

**Comment by goyney** [comment]
I've removed the `Contribution` label and the checkmark for following Material guidelines because there are some issues. The corners are not rounded at 2dp, the strokes aren't 2dp wide, and it is not aligned to the grid. If you can fix those issues, we can consider this request again.

**Comment by MrGrigri** [comment]
I believe this icon is too niche for this project!

**Comment by CoDEmanX** [comment]
I wanted to try some ways to round corners in Inkscape, so I recreated the icon nonetheless:

![grafik](https://user-images.githubusercontent.com/1309249/60218286-2ae5b600-986f-11e9-819b-2604f2409e55.png)

Using more space of the canvas and closer to the look and feel of the original one:

![grafik](https://user-images.githubusercontent.com/1309249/60218331-4fda2900-986f-11e9-8828-0c28e7c2c5d5.png)

[uld.zip](https://github.com/Templarian/MaterialDesign/files/3332084/uld.zip)

**Comment by goyney** [comment]
Closing this because it's too niche. Thank you for your suggestion.
