### ISSUE TITLE
Shield/badge icon

### ISSUE THREAD

**Issue by johanbenschop** [Templarian/MaterialDesign#421]
It would be nice to have a shield/badge icon, much like the  ["verified_user"](https://www.google.com/design/icons/#ic_verified_user) icon that Google has, but without the checkmark in the middle.

**Comment by johanbenschop** [comment]
I modified Google's icon to remove the checkmark. Not sure if this is valid svg though, but it works fine for me.

    <svg fill="#000000" height="24" viewBox="0 0 24 24" width="24" xmlns="http://www.w3.org/2000/svg">
        <path d="M0 0h24v24H0z" fill="none"/>
        <path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4zm-2  "/>
    </svg>

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/shield
http://materialdesignicons.com/icon/shield-outline
