### ISSUE TITLE
Account icon combined with gender icons

### ISSUE THREAD

**Issue by camiel80** [Templarian/MaterialDesign#4210]
I would like if there where icons where the account (google) icon is combined with the gender icons

**Comment by goyney** [comment]
I think that's going to be pretty hard to do considering the size of both of them. What's your use case that just the context of the gender icons wouldn't be sufficient?

**Comment by camiel80** [comment]
I mean like the icon 'account - arrow' but instead of the arrow the gender sign.

**Comment by MrGrigri** [comment]
Wouldn't the `gender-*` icons work?

**Comment by MrGrigri** [comment]
I recommend closing this issue as we already have the `gender-*` icons and that shrinking the gender icons will lose value as well as over polluting the `account` icon.

**Comment by goyney** [comment]
Agreed, I don't feel this is something that'll work very well.
