### ISSUE TITLE
bicycle without rider

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4211]
In my compagny I am working with bicycles. I needed a bicycles without somebody riding it. Hope it will help !
I have several "tool" declinations (plus, minus, remove, alert)

## Preview

![image](https://user-images.githubusercontent.com/6012554/60196516-a0389300-983d-11e9-9ae8-9f4d446f3e1e.png)
![image](https://user-images.githubusercontent.com/6012554/60196587-cb22e700-983d-11e9-8324-f6be6e3d9386.png)
![image](https://user-images.githubusercontent.com/6012554/60196615-d70ea900-983d-11e9-91b7-7d56183bc335.png)
![image](https://user-images.githubusercontent.com/6012554/60196631-e1c93e00-983d-11e9-80d1-5ce46eec7d07.png)
![image](https://user-images.githubusercontent.com/6012554/60196652-edb50000-983d-11e9-9c10-47d6883e34b6.png)

## Zip Download

[archive.zip](https://github.com/Templarian/MaterialDesign/files/3330993/archive.zip)

**Comment by MrGrigri** [comment]
Couple of things to note. 

1. The strokes should be 2-pixels wide everywhere. The preview looks like they are not.
2. The modifiers don't typically go in the upper right-hand corner.
3. I like the design ;)

**Comment by MrGrigri** [comment]
Please note that when those corrections are made, we'll slap a release milestone on this issue.

**Comment by JamesCoyle** [comment]
I don't think it would really work with 2dp strokes. The design is great but I'm also not sure about the modifiers. It's a bit of an odd position but it might cut into the design a bit too much to have the standard cutout.

**Comment by goyney** [comment]
The !2dp strokes, the breakout into the 2dp buffer area, and the modifier positions are all issues to me, although I do like the design of the bicycle.

**Comment by qnp** [comment]
@MrGrigri @goyney
1. Theoretically yes, material specs stipulates that all strokes should be 2px wide. However, in the mdi library we are contributing to, a major part of the icons contains less that 2px strokes (such as for examples, the transportation ones). Moreover, even the _bike_ one, provided by Google itself, has wheels that are 1.5px thick. And I started over this icon to make mine. Finally, @JamesCoyle your are right, I tried with 2px strokes but it is not working well, the bicycle seems too **bold**.

2. I'll try versions with the modifiers as subscript position. I felt them good on superscript because the design itself of the bike provides a space in the upper right-hand corner that can be smartly filled. I found plenty of similar examples in the mdi library (phone-plus and phone-minus (Google), microphone-plus and microphone-minus, etc...)
What do you think, though, about the exclamation mark, being at that position ? When i search for alert-modified icons in the mdi library, no clear rule is visible.

**Comment by qnp** [comment]
Greetings ! Here is a 2px stroke version, which looks more like an old motorized moped than a bicycle.
![image](https://user-images.githubusercontent.com/6012554/60253466-7f6b4e80-98cc-11e9-89c9-099cea8c9099.png)
I also provide an intermediate version where I kept the 1.5px wheels and a 1.5px saddle rod.
![image](https://user-images.githubusercontent.com/6012554/60253507-901bc480-98cc-11e9-93ab-148b666d78e8.png)
You can also see the modifiers at bottom right corner for the first (1.5px stroke) design:
![image](https://user-images.githubusercontent.com/6012554/60254924-1df8af00-98cf-11e9-814d-66eba6339876.png)
![image](https://user-images.githubusercontent.com/6012554/60254960-2b159e00-98cf-11e9-9b25-79a8d0c36160.png)
![image](https://user-images.githubusercontent.com/6012554/60254980-32d54280-98cf-11e9-972b-5ef571f71aff.png)

What do you think ?

**Comment by qnp** [comment]
Greetings, any input on my former update ?

**Comment by MrGrigri** [comment]
Please refer to [our guidelines](https://dev.materialdesignicons.com/contribute/icon-naming#overlay) for modifier placements and cutouts around them. On that page, there is an 'Overlay' section with different tabs. The purple area is the cutout around the modifier. Also, I believe that the 1.5-pixel wide stroke should work with the bike.

This is the template that I use which has the modifiers under the hidden layer named 'Modifiers'.
[template.zip](https://github.com/Templarian/MaterialDesign/files/3378372/template.zip).

**Comment by qnp** [comment]
Thanks, I have worked on it using the standard cutouts. I have cleaned the shape.
![image](https://user-images.githubusercontent.com/6012554/61039907-ef4efe00-a3cf-11e9-9373-318e1fbc3d8d.png)
![image](https://user-images.githubusercontent.com/6012554/61040146-5a003980-a3d0-11e9-9c9b-fb54cb72fcd2.png)
![image](https://user-images.githubusercontent.com/6012554/61040187-6b494600-a3d0-11e9-8a67-11bd603bd30a.png)
![image](https://user-images.githubusercontent.com/6012554/61040216-77350800-a3d0-11e9-88b2-a966d3fecb24.png)
[bicycle_20190711.zip](https://github.com/Templarian/MaterialDesign/files/3381321/bicycle_20190711.zip)

**Comment by qnp** [comment]
If you feel the modifiers variants are not relevant, just stick with the bicycle alone :-)

**Comment by MrGrigri** [comment]
Yeah, I don't think we'll be adding the modifiers. The bicycle alone should work. Thanks for the contribution.

**Comment by goyney** [comment]
[![bicycle](https://materialdesignicons.com/icon/bicycle)](https://materialdesignicons.com/icon/bicycle)
