### ISSUE TITLE
Water filter

### ISSUE THREAD

**Issue by MiguelAngelLV** [Templarian/MaterialDesign#4214]
I need a "water filter". I would use for the swiming pool filter. Now I use air filter, but a water filter should be better.

Example:
![image](https://user-images.githubusercontent.com/638110/60258872-4fc14400-98d6-11e9-8509-4dd85883cc87.png)

**Comment by goyney** [comment]
I honestly think `air-filter` is your best bet. It shows something fluid passing through a solid surface. Your example looks more like a water storage tank system than a filter, and we already have something to cover that, `water-pump`.

I'm not opposed to adding an alias to `air-filter` for `water-filter` as well.

**Comment by goyney** [comment]
Aliases `filter` and `water-filter` added to `air-filter`.
