### ISSUE TITLE
battery-alert-outline

### ISSUE THREAD

**Issue by zxdavb** [Templarian/MaterialDesign#4215]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

`battery-alert` suggests (to me) that the battery is full (albeit with a problem, ?maybe too full?)

`battery-alert-outline` suggest battery is empty (or nearly empty).

Use-case: battery is nearly empty & needs replacing.

## Examples

I hope battery-alert-outline is sufficient description?

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/60319132-10790e80-993b-11e9-82fe-8492f63739d9.png) 
![image](https://user-images.githubusercontent.com/338885/60319163-271f6580-993b-11e9-989e-fcab88b3b1d3.png)

Not sure about just moving it to the right changes the meaning.

**Comment by MrGrigri** [comment]
Yeah, I don't think it changes the meaning at all.

**Comment by zxdavb** [comment]
Hey thanks for such a quick response.

My only concern is if the battery outline is in the same position in space as `battery-alert`?  That is, it seems to me there are two groups of battery icons, one with some qualifier _inside_ teh battery outline, the other with the qualifier _next_ to the outline.

In my UI (Home Assistant), the battery icons all line up, regardless of whether I use `battery` (is full), `battery-50` (is half full), or `battery-unknown` (not heard from the zwave device for a long while).

With is icon, will the battery icon I think the outline of the battery is shifted to the left?

So maybe the about, but also `battery-alert-outline`?

**Comment by goyney** [comment]
[![battery-alert-variant](https://materialdesignicons.com/icon/battery-alert-variant)](https://materialdesignicons.com/icon/battery-alert-variant)[![battery-alert-variant-outline](https://materialdesignicons.com/icon/battery-alert-variant-outline)](https://materialdesignicons.com/icon/battery-alert-variant-outline)
