### ISSUE TITLE
newspaper

### ISSUE THREAD

**Issue by CarlVinggaard** [Templarian/MaterialDesign#4218]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A newspaper would be very nice. We would use it as an icon/indicator for "news" in our webapp.

## Examples

Here is an example from fontawesome.com. Apart from the style, we prefer this type of icon to the existing mdi-news icon.

![newspaper-regular-1](https://user-images.githubusercontent.com/7403587/60344948-18c35f00-99b8-11e9-9b45-a0fcff4033a9.png)

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/newspaper
)](https://materialdesignicons.com/icon/newspaper)

Please search the existing icons before posting an icon request.
