### ISSUE TITLE
Automated External Defibrillator (AED)

### ISSUE THREAD

**Issue by jeevans01** [Templarian/MaterialDesign#4219]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Like the fire extinguisher and medical bag icons, the AED icon would be used to indicate the presence and location of critical emergency equipment (esp. on a building floor plan). A defibrillator is often not a part of a first aid kit, so a separate indicator might be life-saving in the event of cardiac arrest.

## Examples

The accepted symbol for an Automated External Defibrillator is a heart icon superimposed with a lightning bolt in its center. See the attached images:

![51vorKoPPOL _SL1000_](https://user-images.githubusercontent.com/52332317/60367826-30511680-99bd-11e9-9e28-f3576543c313.jpg)

![Automated_External_Defibrillator](https://user-images.githubusercontent.com/52332317/60367974-a9e90480-99bd-11e9-9a4c-ddbb151033bf.gif)

**Comment by JapanYoshi** [comment]
So a combination of ``heart`` and ``flash-circle``?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/60377846-242e7e80-99e8-11e9-8daa-29e00e0fa2af.png)

The outline version doesn't really work; the bolt gets lost.

Adding `Alias` to alias `aed` and `defibrillator` to this.

**Comment by jeevans01** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1015040/60377865-78d1f980-99e8-11e9-964e-0b8e07710f09.png)
> 
> [heart-flash.svg.zip](https://github.com/Templarian/MaterialDesign/files/3341250/heart-flash.svg.zip)
> 
> The outline version doesn't really work; the bolt gets lost.
> 
> Adding `Alias` to alias `aed` and `defibrillator` to this.

That works really well!

**Comment by Templarian** [comment]
[![heart-flash](https://materialdesignicons.com/icon/heart-flash)](https://materialdesignicons.com/icon/heart-flash)
