### ISSUE TITLE
Worker icon

### ISSUE THREAD

**Issue by mishelka** [Templarian/MaterialDesign#422]
[Here](https://www.dropbox.com/s/hwmbtyq2xrmvf8l/worker.svg?dl=0), SVG for my new icon **worker** can be found.

[Here](http://i.imgur.com/f4NmMmp.png) is a screenshot in Incscape.

The icon represents a working person. I didn't want to sign as a contributor because I only have one icon and we need it ASAP for our system :)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/worker

If you needed it in the webfont: [download](http://cl.ly/1o1m0k0f403x)

I tweaked your icon slightly to put the lines on absolute pixels. If you add 4 more icons I can add you as a contributor. Thanks!

**Comment by mishelka** [comment]
Thank you very much! :)
I don't have four icons, but when I'll have new ones, I will add them :)
