### ISSUE TITLE
Confused reaction icon

### ISSUE THREAD

**Issue by sourabhv** [Templarian/MaterialDesign#4222]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

PS: I am not really a designer, I just made this my merging other icons for a project. This might be a really bad icon actually. 😅 

## Preview

![image](https://user-images.githubusercontent.com/2307626/60447972-46bbd400-9c42-11e9-955b-89dfc989b505.png)

## Zip Download

[confused-reaction.svg.zip](https://github.com/Templarian/MaterialDesign/files/3346300/confused-reaction.svg.zip)

**Comment by goyney** [comment]
The [confused emoji](https://emojipedia.org/confused-face/) is defined as "A [...] face with open eyes and a skewed frown, as if scrunching its cheeks or chewing its lips. A look of feeling unsure. An Google’s design heightens its intended puzzlement by including contorted eyebrows."

This is similar to our `emoticon-sad`:
[![emoticon-sad](https://materialdesignicons.com/icon/emoticon-sad)](https://materialdesignicons.com/icon/emoticon-sad)

Perhaps there's more we can do to that base icon further distinguish it as "confused." Regardless, I'm not a fan of the split mouth/color. If we come up with something for this, I believe we should have a filled and outline variant, like all our other emoji icons.

**Comment by JamesCoyle** [comment]
Yeah I agree with @goyney. The icon you contributed doesn't really fit in with the others. I think if we copied the `emoticon-sad` icon but made one side of the mouth flat it would line up with the general consensus of how such an icon should look. 

![image](https://user-images.githubusercontent.com/10384436/60495334-74d3ff00-9ca8-11e9-8616-00aafb194350.png)

**Comment by MrGrigri** [comment]
Like this?

![image](https://user-images.githubusercontent.com/4528551/60518285-700a4d80-9c9e-11e9-9ae5-723fea424e3c.png) ![image](https://user-images.githubusercontent.com/4528551/60518301-7d273c80-9c9e-11e9-8bca-505bdb7bab85.png)

---
#### Files

[emoticon-confused.zip](https://github.com/Templarian/MaterialDesign/files/3350383/emoticon-confused.zip)

**Comment by JamesCoyle** [comment]
Yeah I think that works well. The curved side of the mouth on the outline version looks a bit too close to the circle though IMO.

**Comment by MrGrigri** [comment]
Updated. I moved the mouth up one pixel.

**Comment by JamesCoyle** [comment]
Yeah that looks right.

**Comment by MrGrigri** [comment]
P.S. I love that both you and Michael responded with a confused reaction! 😆

**Comment by goyney** [comment]
[![emoticon-confused](https://materialdesignicons.com/icon/emoticon-confused)](https://materialdesignicons.com/icon/emoticon-confused)[![emoticon-confused-outline](https://materialdesignicons.com/icon/emoticon-confused-outline)](https://materialdesignicons.com/icon/emoticon-confused-outline)
