### ISSUE TITLE
waiting room

### ISSUE THREAD

**Issue by mfindlay93** [Templarian/MaterialDesign#4223]
I have:

- [ ] Searched all issues to make sure there isn't a request for this icon.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
Can you please provide your use case and some examples of what this might look like?

**Comment by goyney** [comment]
I think your best bet is going to be `seat-recline-normal`:

[![seat-recline-normal](https://materialdesignicons.com/icon/seat-recline-normal)](https://materialdesignicons.com/icon/seat-recline-normal)

**Comment by mfindlay93** [comment]
seat-recline-normal with a clock next to it would be perfect

**Comment by goyney** [comment]
Even our smallest clock will not work in conjunction with this icon.

**Comment by goyney** [comment]
Just to further prove this:

![image](https://user-images.githubusercontent.com/1015040/61178374-e6218500-a5b9-11e9-913e-54db5083b151.png)

It's impossible to tell that the person is seated with the clock in place. I still believe `seat-recline-normal` is your best bet. Unless someone else has a better idea, I'm moving to close this request.
