### ISSUE TITLE
dirty icon

### ISSUE THREAD

**Issue by edwinmartinez** [Templarian/MaterialDesign#4225]
I have looked and I could not find an icon for dirty

**Comment by JamesCoyle** [comment]
Please follow the issue template when requesting icons. We need some examples of what this icon should look like and what context it would be used for.

**Comment by goyney** [comment]
Well, we already have a couple that could work for this:

[![broom](https://materialdesignicons.com/icon/broom)](https://materialdesignicons.com/icon/broom)[![delete](https://materialdesignicons.com/icon/delete)](https://materialdesignicons.com/icon/delete)

---

Here's another idea:
![image](https://user-images.githubusercontent.com/1015040/60555793-6dded800-9d0c-11e9-8b6b-90ee99062dec.png)![image](https://user-images.githubusercontent.com/1015040/60555803-76371300-9d0c-11e9-8f98-1757a096c301.png)

[bacteria.zip](https://github.com/Templarian/MaterialDesign/files/3352815/bacteria.zip)

**Comment by Templarian** [comment]
Added. 😃
