### ISSUE TITLE
Update weather-rainy

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4226]
Our current `weather-rainy`'s drop is misshapen, so let's fix it!

![image](https://user-images.githubusercontent.com/1015040/60526305-10239f00-9cbe-11e9-9bb0-2ce5126bc9fa.png)

(Our current is the outline.)

[weather-rainy-fixed.svg.zip](https://github.com/Templarian/MaterialDesign/files/3350859/weather-rainy-fixed.svg.zip)

**Comment by Templarian** [comment]
Fixed.

**Comment by Templarian** [comment]
By the way we should put all "Update Icon" labels into the most recent milestone.
