### ISSUE TITLE
Some icons misattributed from #2723

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4227]
![image](https://user-images.githubusercontent.com/8707990/60563973-40903980-9da1-11e9-8664-c9f29780ea61.png)
I was the one who designed the ``gamepad-circle`` and ``gamepad-round`` icons, but on the site, they were attributed to GreenTurtwig instead.

**Comment by Templarian** [comment]
Oops. Fixed! :smile
