### ISSUE TITLE
power-socket-us-variant/power-socket-jp

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4228]
I found that the Type A plug is missing from our library, so I made it. The American variant has one wider pin, while the Japanese variant has two congruent pins (which is [how it is in real life](https://www.iec.ch/worldplugs/typeA.htm)).

Also, the preview tool isn't working with the output from Inkscape's XML editor. :(

[socket.zip](https://github.com/Templarian/MaterialDesign/files/3353337/socket.zip)

**Comment by goyney** [comment]
Here are the previews from @JapanYoshi's contribution:
![image](https://user-images.githubusercontent.com/1015040/60591571-bcbc5a00-9d6c-11e9-976f-cfbd74c1ba38.png)![image](https://user-images.githubusercontent.com/1015040/60591592-c940b280-9d6c-11e9-97cc-24d98679be6a.png)

I personally don't feel we need the `us-variant`. Non-grounded plugs are just not a thing anymore and only exist in extremely old homes that haven't been updated yet.

**Comment by goyney** [comment]
[![power-socket-jp](https://materialdesignicons.com/icon/power-socket-jp)](https://materialdesignicons.com/icon/power-socket-jp)
