### ISSUE TITLE
resume

### ISSUE THREAD

**Issue by harsha20599** [Templarian/MaterialDesign#4229]
I believe there should be a resume icon present in the library. 

### Usage

It's used to represent the resume of a candidate. The resume is a document which explains about a person.

### Examples

Something similar to this might help

![225937-200](https://user-images.githubusercontent.com/20438252/60702194-d059f300-9f1b-11e9-9129-e02ce4dca639.png)

**Comment by PeterShaggyNoble** [comment]
Would `file-account` suit your needs?

[![file-account](https://materialdesignicons.com/icon/file-account)](https://materialdesignicons.com/icon/file-account)

**Comment by harsha20599** [comment]
Yes, that looks pretty and fits the need. Thank you @PeterShaggyNoble

**Comment by goyney** [comment]
Added the `resume` alias to `file-account`.
