### ISSUE TITLE
Re-design Euro icon

### ISSUE THREAD

**Issue by gytdau** [Templarian/MaterialDesign#423]
The Euro icon looks really off.
Look at [this example from Wikipedia](http://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Euro_Construction.svg/220px-Euro_Construction.svg.png) and then contrast it with [this extremely awkward symbol](http://materialdesignicons.com/icon/currency-eur).
It has some resemblance, yes, but it looks unnatural to a European such as myself.

**Comment by Templarian** [comment]
Yea, I used the style out of the Roboto font and I 100% agree it is ugly and needs to redone.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/currency-eur

As close as possible, while keeping it in the Material Design style guidelines. Hopefully this fits. :smile:
