### ISSUE TITLE
hairdryer(-outline)

### ISSUE THREAD

**Issue by guiumb** [Templarian/MaterialDesign#4230]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Can be usable in a domotic contest

## Examples

![image](https://user-images.githubusercontent.com/42201341/60744245-49d1ff80-9f75-11e9-8889-adbb95053113.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/60825547-27083c80-a169-11e9-9bbf-cf8aa7aa04b7.png) ![image](https://user-images.githubusercontent.com/4528551/60825569-34252b80-a169-11e9-832d-d06ede0ce842.png)

---
#### Files
[hairdryer.zip](https://github.com/Templarian/MaterialDesign/files/3369275/hairdryer.zip)

**Comment by goyney** [comment]
[![hair-dryer](https://materialdesignicons.com/icon/hair-dryer)](https://materialdesignicons.com/icon/hair-dryer)[![hair-dryer-outline](https://materialdesignicons.com/icon/hair-dryer-outline)](https://materialdesignicons.com/icon/hair-dryer-outline)
