### ISSUE TITLE
folder-(upload | download)-outline

### ISSUE THREAD

**Issue by benct** [Templarian/MaterialDesign#4231]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same as with [folder-upload](https://materialdesignicons.com/icon/folder-upload), used for uploading or navigation to parent folder.

## Examples

Just an `outline` version of the already existing [folder-upload](https://materialdesignicons.com/icon/folder-upload)

**Comment by MrGrigri** [comment]
Here are both upload and download.

![image](https://user-images.githubusercontent.com/4528551/60823523-f1615480-a164-11e9-83d4-e10742015b14.png) ![image](https://user-images.githubusercontent.com/4528551/60823556-ff16da00-a164-11e9-9380-913ba5e11dab.png)

---
#### Files
[folder-(upload__download)-outline.zip](https://github.com/Templarian/MaterialDesign/files/3369155/folder-.upload__download.-outline.zip)

**Comment by goyney** [comment]
[![folder-download-outline](https://materialdesignicons.com/icon/folder-download-outline)](https://materialdesignicons.com/icon/folder-download-outline)[![folder-upload-outline](https://materialdesignicons.com/icon/folder-upload-outline)](https://materialdesignicons.com/icon/folder-upload-outline)
