### ISSUE TITLE
cast-audio

### ISSUE THREAD

**Issue by kineticscreen** [Templarian/MaterialDesign#4233]
As a distinction for Chromecast Only media players and 'Home' devices. Matches to the usual Chromecast logo, which implies a screen.

## Preview

![image](https://user-images.githubusercontent.com/39250334/60873443-c157a580-a279-11e9-91fe-7ce717d2a556.png)

## Zip Download
[chromecast-audio.zip](https://github.com/Templarian/MaterialDesign/files/3372045/chromecast-audio.zip)

**Comment by goyney** [comment]
Good start! The wireless part of the icon and the bottom of the speaker isn't aligned to the grid and there should be a 2dp cutout between the end of the wireless part and the speaker. Could you address those two issues?

**Comment by goyney** [comment]
Here's the fixed version:
![image](https://user-images.githubusercontent.com/1015040/61177482-a9975e80-a5a4-11e9-85b1-88341a6ee683.png)

[cast-audio.svg.zip](https://github.com/Templarian/MaterialDesign/files/3389312/cast-audio.svg.zip)

**Comment by kineticscreen** [comment]
Looks good to me - sorry I wasn't to get onto the changes myself sooner.

**Comment by goyney** [comment]
[![cast-audio](https://materialdesignicons.com/icon/cast-audio)](https://materialdesignicons.com/icon/cast-audio)

**Comment by kineticscreen** [comment]
Glad to see this got added to MDI. Not sure why I wasn't credited though.

**Comment by goyney** [comment]
Once you hit 5 icons added to the library, open an issue and we'll add you as a Contributor.
