### ISSUE TITLE
Leader board

### ISSUE THREAD

**Issue by Ross-Rawlins** [Templarian/MaterialDesign#4234]
I have:

- [x] Searched all issues to make sure there isn't a request for this icon.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A leader board icon, similar to the link below.

## Examples

http://chittagongit.com/images/leaderboard-icon/leaderboard-icon-23.jpg

**Comment by goyney** [comment]
Already included as `podium`:
[![podium](https://materialdesignicons.com/icon/podium)](https://materialdesignicons.com/icon/podium)

There's also `podium-gold`, `podium-silver`, and `podium-bronze`.
