### ISSUE TITLE
Anonymous icon

### ISSUE THREAD

**Issue by Franki1986** [Templarian/MaterialDesign#4235]
Hello,

I was searching for an anonymous or incognito icon.

This is what I would expect:

[Anonymous.svg](https://svgshare.com/i/Dzw.svg)

**Comment by goyney** [comment]
Already exists as `incognito`:
[![incognito](https://materialdesignicons.com/icon/incognito)](https://materialdesignicons.com/icon/incognito)

**Comment by goyney** [comment]
`anonymous` added as an alias.

**Comment by Franki1986** [comment]
perfect !! Thanks for that!
