### ISSUE TITLE
consolidate

### ISSUE THREAD

**Issue by HassanMehmood1992** [Templarian/MaterialDesign#4236]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon can be used to dipict integration of different kind of sources. A general icon for integration.

## Examples

Icon can consist of multiple arrows with dots connecting. or simple connecting dots.

**Comment by goyney** [comment]
Would something like https://github.com/Templarian/MaterialDesign/issues/910#issuecomment-441710780 work for you?

**Comment by HassanMehmood1992** [comment]
> Would something like [#910 (comment)](https://github.com/Templarian/MaterialDesign/issues/910#issuecomment-441710780) work for you?
> 
> Or the `one-to-many`/`many-to-one` suggestions from #720?

something along this line 
![image](https://user-images.githubusercontent.com/17563392/60976364-9a16dc00-a33e-11e9-92b9-b3bece4568af.png)

**Comment by goyney** [comment]
I don't think this really work in the space we have.
![image](https://user-images.githubusercontent.com/1015040/60981377-32439f80-a304-11e9-8478-a6ae10ccfbdd.png)

What about `puzzle`? it is used quite frequently with plug-ins or integrations into a larger system.
[![puzzle](https://materialdesignicons.com/icon/puzzle)](https://materialdesignicons.com/icon/puzzle)

**Comment by MrGrigri** [comment]
Yeah, the puzzle piece is typically used to identify a component, plugin, or integration. The proposal is more of a consolidation idea.

**Comment by HassanMehmood1992** [comment]
I am mainly working in aviation field and we are integrating different sources like email, data sources, services so it is like all sort of integration. I couldn't find any specific type of icon which might fit to our needs. 
I couldn't come up with something integrating in to a single source. that was a general idea behind it . 

@goyney  i think this could work for us. Thanks

**Comment by goyney** [comment]
@HassanMehmood1992 Which one, the `puzzle` icon?

**Comment by HassanMehmood1992** [comment]
@goyney  https://user-images.githubusercontent.com/1015040/60981377-32439f80-a304-11e9-8478-a6ae10ccfbdd.png this one

**Comment by MrGrigri** [comment]
I believe we should call this icon `consolidate`. Unless there is a better term. I don't think that `integration` works.

**Comment by goyney** [comment]
[![consolidate](https://materialdesignicons.com/icon/consolidate)](https://materialdesignicons.com/icon/consolidate)
