### ISSUE TITLE
[question about @mdi/js] How can we get a different colored svg?

### ISSUE THREAD

**Issue by vladfrangu** [Templarian/MaterialDesign#4237]
Hello there o/

I've recently started using these amazing icons in one of the projects I work on, but I couldn't figure out how to get differently colored SVG icons. They all seem to return the icon in pure black. (this could be due to the fact I use vuetify's [Icon](https://next.vuetifyjs.com/en/components/icons) component)

Is there any simple way to get the icons a different color?

Also, the docs for material design icons suggests we use `vue-material-design-icons`, while this repository suggests we use `@mdi/js`.. Which one are we meant to use in the end?

Thanks!

**Comment by goyney** [comment]
It looks like the `v-icon` component from Vuetify has a `color` prop that can be set to change the icon color.

You can also target the icon's container via CSS and change the fill:

```css
.my-icon svg {
  fill: red;
}
```

`@mdi/js` is a package that simply returns the raw path data for any given icon. It looks like Vuetify has this built in and all you need to do is provide `mdi-icon-name` as a child of the `v-icon` component.

**Comment by vladfrangu** [comment]
> `@mdi/js` is a package that simply returns the raw path data for any given icon. It looks like Vuetify has this built in and all you need to do is provide `mdi-icon-name` as a child of the `v-icon` component.

That is true, but only for the CSS version of MDI. The svg version requires you to set the iconfont to `mdiSvg` (which I've done) and make the child of `v-icon` BE the svg (which I've done). Seems like they set `color` for it, while svg's need.. fill?

Adding a manual

```vue
<style lang="css" scoped>
.v-icon--svg {
	fill: white;
}
</style>
```

has solved the issue! Should I report this to the vuetify team instead? 😅

**Comment by goyney** [comment]
Yeah, this is likely a better question for their community/support team. We deal with a lot of different projects integrating us, so it is hard for us to know all the details in how they implement the icons.

I'll close this for now, but feel free to comment again if you have more questions.
