### ISSUE TITLE
Electric switch closed

### ISSUE THREAD

**Issue by MarcHagen** [Templarian/MaterialDesign#4238]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As of #2879 we have a electric switch, but no closed version of that.

## Examples

See https://github.com/Templarian/MaterialDesign/issues/2879#issuecomment-417625661

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/60999107-5618dc80-a328-11e9-9164-72b328fea12c.png)
[electric-switch-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/3379135/electric-switch-off.svg.zip)

**Comment by goyney** [comment]
[![electric-switch-closed](https://materialdesignicons.com/icon/electric-switch-closed)](https://materialdesignicons.com/icon/electric-switch-closed)
