### ISSUE TITLE
Calendar icon

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#424]
Could you please update calendar icon or date picker icon with date

**Comment by Templarian** [comment]
The pack has a handful of "calendar" icons. Can you be more specific?

Date picker... I think the standard stock http://materialdesignicons.com/icon/calendar icon would be used for that.

**Comment by jmj4you** [comment]
Thank you. I haven't find this first time. Sorry for troubling you.

**Comment by Templarian** [comment]
No problem. Feel free to submit an icon suggestions if you don't find an icon you require.

You can use the common ctrl/cmd+f to bring up the search ability on the site or press the magnifying glass icon on the site.
