### ISSUE TITLE
Design Icon - Combine the ruler and pencil

### ISSUE THREAD

**Issue by TheWilks** [Templarian/MaterialDesign#4240]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To indicate a design panel within an application.

## Examples

![image](https://user-images.githubusercontent.com/6516828/60998805-a80d3280-a327-11e9-8c50-40dab6313155.png)

**Comment by TheWilks** [comment]
![image](https://user-images.githubusercontent.com/6516828/60998706-7b591b00-a327-11e9-9c2e-36eeb44144da.png)

**Comment by goyney** [comment]
I don't think this really works. The ruler is unidentifiable.

![image](https://user-images.githubusercontent.com/1015040/60998921-ee629180-a327-11e9-99eb-f32ace3f807d.png)

**Comment by TheWilks** [comment]
Works well enough for me personally. Would love to hear more opinions though. Really just looking for something to loosely indicate design.

**Comment by goyney** [comment]
A ruler and pencil wouldn't indicate "design" to me, more architecture.

What about:
[![palette-advanced](https://materialdesignicons.com/icon/palette-advanced)](https://materialdesignicons.com/icon/palette-advanced)

Or any of these:
[![palette](https://materialdesignicons.com/icon/palette)](https://materialdesignicons.com/icon/palette)[![palette-swatch](https://materialdesignicons.com/icon/palette-swatch)](https://materialdesignicons.com/icon/palette-swatch)[![brush](https://materialdesignicons.com/icon/brush)](https://materialdesignicons.com/icon/brush)

**Comment by TheWilks** [comment]
Yeah well it's true you are right my application is more using parts to build something then design so rule and pencil works. I don't want to use the colour and paint icons in case I add the ability to change colours on things in the future.

**Comment by TheWilks** [comment]
Is there a quick way to add things to the library myself. I don't want you to persuade you to go against your vision.

**Comment by JapanYoshi** [comment]
Just download the svg.zip file, and use the svg contained therein. There are several ways to use it, but I personally like using the <svg> tag best.

**Comment by CoDEmanX** [comment]
A ruler and pencil combination seems quite useful, as it represents architectural work or CAD much better than the existing ones, which are rather express an artistic activity. Maybe place the ruler vertically on the side?

**Comment by goyney** [comment]
Here's Google's take on this:

![image](https://user-images.githubusercontent.com/1015040/72488477-1521e900-37df-11ea-92c9-e569fae8972b.png)
[pencil-ruler.svg.zip](https://github.com/Templarian/MaterialDesign/files/4069036/pencil-ruler.svg.zip)

**Comment by TheWilks** [comment]
Perfect. Can’t complain. Simple representation of design / simple alternative to the current representation of design.

**Comment by goyney** [comment]
[![pencil-ruler](https://materialdesignicons.com/icon/pencil-ruler)](https://materialdesignicons.com/icon/pencil-ruler)
