### ISSUE TITLE
routes-clock

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4241]
I the webapp I am developping, I needed an icon that evocated routes/directions **estimation**. Here is my attempt:

![image](https://user-images.githubusercontent.com/6012554/61041355-6d140900-a3d2-11e9-8e3e-701b5c246423.png)

[routes-clock.zip](https://github.com/Templarian/MaterialDesign/files/3381380/routes-clock.zip)

**Comment by goyney** [comment]
I think I'd like to see some variations of this that don't break into the 2dp padding.

**Comment by PeterShaggyNoble** [comment]
I like the idea of this but would `map-clock` suit your needs?

[![map-clock](https://materialdesignicons.com/icon/map-clock)](https://materialdesignicons.com/icon/map-clock)

**Comment by qnp** [comment]
I would, but as I use a lot of map icons for the meaning of map itself and not direction/route/path, I needed an alternative

**Comment by goyney** [comment]
Trying something out here:
![image](https://user-images.githubusercontent.com/1015040/61078663-22ed5080-a3ef-11e9-9c28-bff83c9ad4dd.png)

**Comment by qnp** [comment]
@goyney I like that version

**Comment by qnp** [comment]
I could suggest to restore the initial lenght of the directionnal sign pointing to the left, such as:
![image](https://user-images.githubusercontent.com/6012554/61119886-0e1ac680-a49c-11e9-9ac2-0bb086389346.png)
Feels more balanced.

**Comment by goyney** [comment]
[![routes-clock](https://materialdesignicons.com/icon/routes-clock)](https://materialdesignicons.com/icon/routes-clock)
