### ISSUE TITLE
Salt or Pepper

### ISSUE THREAD

**Issue by FANMixco** [Templarian/MaterialDesign#4242]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I was considering an icon for ingredients for cooking applications and I believe that a salt or pepper icon like the example below could be neutral and represents all.

## Examples

![download](https://user-images.githubusercontent.com/1666156/61049849-cafe1c00-a3e5-11e9-89bb-4cc3188814d4.png)

<div>Icons made by <a href="https://www.freepik.com/" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/"                 title="Flaticon">www.flaticon.com</a> is licensed by <a href="http://creativecommons.org/licenses/by/3.0/"                 title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a></div>

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61078375-7a3ef100-a3ee-11e9-8b8e-812de1a962bc.png)![image](https://user-images.githubusercontent.com/1015040/61078398-87f47680-a3ee-11e9-90dd-7f783b10925b.png)

[shakers.zip](https://github.com/Templarian/MaterialDesign/files/3383533/shakers.zip)

**Comment by FANMixco** [comment]
> ![image](https://user-images.githubusercontent.com/1015040/61078375-7a3ef100-a3ee-11e9-8b8e-812de1a962bc.png)![image](https://user-images.githubusercontent.com/1015040/61078398-87f47680-a3ee-11e9-90dd-7f783b10925b.png)
> 
> [shakers.zip](https://github.com/Templarian/MaterialDesign/files/3383533/shakers.zip)

Awesome! That's what I wanted!

**Comment by goyney** [comment]
[![shaker](https://materialdesignicons.com/icon/shaker)](https://materialdesignicons.com/icon/shaker)[![shaker-outline](https://materialdesignicons.com/icon/shaker-outline)](https://materialdesignicons.com/icon/shaker-outline)
