### ISSUE TITLE
map-marker-up & map-marker-down

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4243]
Again, these are useful for me:

## Preview

![image](https://user-images.githubusercontent.com/6012554/61063569-71efb180-a400-11e9-8f3e-7b296a1cd176.png)
![image](https://user-images.githubusercontent.com/6012554/61063594-7caa4680-a400-11e9-98da-bde579eca1c4.png)

## Zip Download

[map-marker-up-and-down.zip](https://github.com/Templarian/MaterialDesign/files/3382745/map-marker-up-and-down.zip)

**Comment by goyney** [comment]
What would the use case be for these?

**Comment by qnp** [comment]
For instance to mark on a map the positions of a pickup and of a deposit

**Comment by goyney** [comment]
[![map-marker-up](https://materialdesignicons.com/icon/map-marker-up)](https://materialdesignicons.com/icon/map-marker-up)[![map-marker-down](https://materialdesignicons.com/icon/map-marker-down)](https://materialdesignicons.com/icon/map-marker-down)
