### ISSUE TITLE
link-variant(-plus)

### ISSUE THREAD

**Issue by dphoebus** [Templarian/MaterialDesign#4244]
First, thank you for all the work.  This library is an amazing supplement to the original material design icon set.  

Second, I am no artists and the example below is just something for reference.  The link-variant icon IMHO is a much nicer representation of a 'link' but there is no icon for adding a new link.  Thanks in advance for your time.

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

`<mat-icon svgIcon="link-variant-plus"></mat-icon>`

## Examples

![link-variant-plus](https://user-images.githubusercontent.com/4739577/61076376-14e90100-a3ea-11e9-9835-7df230c571f4.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61077377-41058180-a3ec-11e9-8bab-0da5153bf30e.png)![image](https://user-images.githubusercontent.com/1015040/61077394-48c52600-a3ec-11e9-9aa8-899abc48ed4c.png)
![image](https://user-images.githubusercontent.com/1015040/61077404-511d6100-a3ec-11e9-9616-30ce6a360eac.png)

[link-variant.zip](https://github.com/Templarian/MaterialDesign/files/3383496/link-variant.zip)

**Comment by dphoebus** [comment]
That looks amazing.  Thank you!

**Comment by PeterShaggyNoble** [comment]
@dphoebus, we'll leave this open until these icons are added to the library.

**Comment by dphoebus** [comment]
Sorry!  Just thought I was cleaning up after myself. Thanks again.

**Comment by goyney** [comment]
[![link-variant-plus](https://materialdesignicons.com/icon/link-variant-plus)](https://materialdesignicons.com/icon/link-variant-plus)[![link-variant-minus](https://materialdesignicons.com/icon/link-variant-minus)](https://materialdesignicons.com/icon/link-variant-minus)[![link-variant-remove](https://materialdesignicons.com/icon/link-variant-remove)](https://materialdesignicons.com/icon/link-variant-remove)
