### ISSUE TITLE
Alternate versions of some of the "developer-languages" icons

### ISSUE THREAD

**Issue by TheWilks** [Templarian/MaterialDesign#4245]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Just looking for some variation here. As seen in the image I am looking for variations of the red circled items similar to the highlighted items.

## Examples

![Capture](https://user-images.githubusercontent.com/6516828/61087052-7a48ec00-a402-11e9-9bf9-6ab09d869274.PNG)

**Comment by JamesCoyle** [comment]
Just box variants for each or iframe style ones too?

**Comment by TheWilks** [comment]
Originally I was thinking both for all but probably box variant for all and the iframe styles for the variable icon. The reason for the variable icon being in the iframe style is because in the app we are developing we have a panel to define variables.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61178210-56c6a280-a5b6-11e9-8562-7b60cd9ef52c.png)![image](https://user-images.githubusercontent.com/1015040/61178211-5e864700-a5b6-11e9-8a99-b5a751f1ca88.png)
![image](https://user-images.githubusercontent.com/1015040/61178269-b83b4100-a5b7-11e9-984e-68bc963a0cd3.png)![image](https://user-images.githubusercontent.com/1015040/61178273-d99c2d00-a5b7-11e9-87a1-53fac2dbf200.png)
![image](https://user-images.githubusercontent.com/1015040/61178283-47e0ef80-a5b8-11e9-9b22-f80c9010d918.png)![image](https://user-images.githubusercontent.com/1015040/61178285-4fa09400-a5b8-11e9-868b-2dbc3cba2317.png)
![image](https://user-images.githubusercontent.com/1015040/61178310-8b3b5e00-a5b8-11e9-8f3e-fe82faa08d0c.png)![image](https://user-images.githubusercontent.com/1015040/61178316-a8702c80-a5b8-11e9-915f-62eaeb6cc185.png)
![image](https://user-images.githubusercontent.com/1015040/61178326-e2413300-a5b8-11e9-8300-454c4144d922.png)![image](https://user-images.githubusercontent.com/1015040/61178331-069d0f80-a5b9-11e9-8561-209637887eea.png)
![image](https://user-images.githubusercontent.com/1015040/61178234-c2107480-a5b6-11e9-9fa2-f52e344d0d16.png)

[code-variations.zip](https://github.com/Templarian/MaterialDesign/files/3389383/code-variations.zip)

**Comment by TheWilks** [comment]
@goyney Thanks!

**Comment by goyney** [comment]
😆 "iframes are pretty much obsolete". Boy, do I wish that were true.

**Comment by goyney** [comment]
All these have been added. 😄
