### ISSUE TITLE
nix icon

### ISSUE THREAD

**Issue by MichaelBergquistSuarez** [Templarian/MaterialDesign#4246]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Could be used as a file icon for [nix files](https://nixos.org/nix/) files with a `nix` extension, such as in the Visual Studio Code extension [`material-icon-theme`](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme).

## Examples
![](https://nixos.org/logo/nixos-logo-only-hires.png)

**Comment by goyney** [comment]
Considering this is a development tool, it meets the criteria to still be added, [despite our recent announcement about brand icons](http://dev.materialdesignicons.com/roadmap/brand-icons).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61190080-8207cb00-a664-11e9-848f-373ca65c1014.png)
[nix.svg.zip](https://github.com/Templarian/MaterialDesign/files/3390478/nix.svg.zip)

**Comment by goyney** [comment]
[![nix](https://materialdesignicons.com/icon/nix)](https://materialdesignicons.com/icon/nix)
