### ISSUE TITLE
filter-menu(-outline)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4248]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/61219818-41469b00-a6d2-11e9-8caf-e06801cd55be.png) ![image](https://user-images.githubusercontent.com/4528551/61219868-5a4f4c00-a6d2-11e9-8622-a62d98152269.png)

## Zip Download

[filter-menu.zip](https://github.com/Templarian/MaterialDesign/files/3392488/filter-menu.zip)

**Comment by goyney** [comment]
Alias these with `funnel-menu` and `funnel-menu-outline` as well.

**Comment by goyney** [comment]
[![filter-menu](https://materialdesignicons.com/icon/filter-menu)](https://materialdesignicons.com/icon/filter-menu)[![filter-menu-outline](https://materialdesignicons.com/icon/filter-menu-outline)](https://materialdesignicons.com/icon/filter-menu-outline)
