### ISSUE TITLE
Shipment booking

### ISSUE THREAD

**Issue by johnknoop** [Templarian/MaterialDesign#4249]
I found myself looking for an icon representing "shipment booking". I combined the MDI truck and phone icons, and added a diagonal line for clarity.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Comment: If there's something in the guidelines that I've missed then please point it out and I will try to correct it.

## Preview

![image](https://user-images.githubusercontent.com/3394270/61253380-0dff1d00-a761-11e9-8e1b-3960c8001b68.png)

I'm not sure why the wheels on the truck are filled in the preview. They look correct when I open the svg in chrome.

## Zip Download

[truck-phone.zip](https://github.com/Templarian/MaterialDesign/files/3394455/truck-phone.zip)

**Comment by JamesCoyle** [comment]
I'm not sure this really fits in with our project as it is pretty specific and the icon is a bit too detailed.

**Comment by johnknoop** [comment]
No worries. I can use the svg directly instead.

It would be nice if there was a simple way to add local extensions to MDI. That way I wouldn't need to different ways to show icons.

**Comment by goyney** [comment]
If you're using React, you can use [`@mdi/react`](https://www.npmjs.com/package/@mdi/react) in conjunction with [`@mdi/js`](https://www.npmjs.com/package/@mdi/js). This gives you the ability to use our icons directly, but then also provide your own combined path data.

```js
import Icon from '@mdi/react';
import { mdiChevronLeft } from '@mdi/js';

...

return (
  <>
    <Icon path={mdiChevronLeft} size={1} />
    <Icon path='M...MY PATH DATA...Z' size={1} />
  </>
);
```

**Comment by goyney** [comment]
I still think this issue could be used to track the intent of the icon, though: "shipment booking". I have some ideas I can mess with tonight. Renaming the issue and dropping the `Contribution` label for now.

**Comment by MrGrigri** [comment]
Wouldn't [truck-check](https://materialdesignicons.com/icon/truck-check) work?

 ![truck-check](https://materialdesignicons.com/icon/truck-check)

**Comment by JamesCoyle** [comment]
Gonna close this out for the reasons stated above. Thank you for your contribution!
