### ISSUE TITLE
closed captioning

### ISSUE THREAD

**Issue by slambe** [Templarian/MaterialDesign#425]

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/closed-caption

You mean the stock google icon?

**Comment by slambe** [comment]
Yes, perfect...didn't see this when I did a pass over the list!

**Comment by Templarian** [comment]
Normal find on the page or click the search button will let you search through the icons. :smile:

Feel free to submit a suggestion if you don't see an icon you need.
