### ISSUE TITLE
reboot

### ISSUE THREAD

**Issue by rickx** [Templarian/MaterialDesign#4250]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/1685369/61298665-ec447b00-a7de-11e9-86af-45926b7248ab.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[reboot.zip](https://github.com/Templarian/MaterialDesign/files/3397288/reboot.zip)

**Comment by JamesCoyle** [comment]
Generally software will use something similar to our restart or restore icons. I'm not really sure the one you provided is recognisable as 'reboot' as it is not part of the IEC standard for power icons. 
[![](https://materialdesignicons.com/icon/restart
)](https://materialdesignicons.com/icon/restart)[![](https://materialdesignicons.com/icon/restore
)](https://materialdesignicons.com/icon/restore)

**Comment by rickx** [comment]
I think it give the idea of reboot or power cycle pretty good, visually better than the "info-icon" they propose for this action for sure. I agree the restart is not bad also, but I find mine more specific.

**Comment by MrGrigri** [comment]
According to the [ISO](https://www.iso.org/obp/ui#iec:grs:60417:5010) IEC 60417-5010 our `power-cycle` icon is the standard for a reboot or power cycle. We love your desire to contribute to our repository and your creative thinking. However, we'll be sticking with the standard. Do not let this discourage you from continuing to contribute.

![power-cycle](https://materialdesignicons.com/icon/power-cycle)
