### ISSUE TITLE
folder-settings(-outline)

### ISSUE THREAD

**Issue by massivemadness** [Templarian/MaterialDesign#4251]
I'm looking for an icon like [this](https://materialdesignicons.com/icon/folder-sync-outline) but instead of "rotate" or "refresh" icon in the bottom right corner I want [settings](https://materialdesignicons.com/icon/settings) icon.

Could you please make these two versions? (Filled + Outlined)

**Comment by MrGrigri** [comment]
Please be advised that it is an exception and not the guidelines to use the cog modifier as a settings identifier. MD Guidelines use the three dots underneath the icon to represent that. 

Also, I'm going to split this from #3911 as that one is for `folder-information`. Also, the settings modifier on that one was not correct.

![image](https://user-images.githubusercontent.com/4528551/61395676-3848fb80-a883-11e9-8210-cfaa4324d3e4.png) ![image](https://user-images.githubusercontent.com/4528551/61395717-57478d80-a883-11e9-9f42-87d747fbffd2.png)

---
#### Files (Optimized)

[folder-settings.zip](https://github.com/Templarian/MaterialDesign/files/3403007/folder-settings.zip)

**Comment by goyney** [comment]
https://github.com/Templarian/MaterialDesign/issues/4271 is going to play a part in the eventual name for these.

**Comment by goyney** [comment]
These were added in a previous issue.
