### ISSUE TITLE
bagpipe(-outline)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4252]
I have:

- [x] Been to multiple Scottish festivals this year.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/61486812-90eec600-a961-11e9-9608-b1cc938b31f0.png) ![image](https://user-images.githubusercontent.com/4528551/61486830-9ea44b80-a961-11e9-8a40-18d2c930dd56.png)

## Zip Download

[bagpipe.zip](https://github.com/Templarian/MaterialDesign/files/3408189/bagpipe.zip)

**Comment by Mariusthvdb** [comment]
Aye!
being there myself right now, I had been looking for a nice set of pipes. No coincidence... Thanks for this.

**Comment by CoDEmanX** [comment]
Looks like a bunch of bent nails in a pocket to me 😕

**Comment by goyney** [comment]
I have to agree, I think this is going to be a hard thing to represent so small because of the complexity.

**Comment by MrGrigri** [comment]
I believe that within the proper context it would be understood.

**Comment by JapanYoshi** [comment]
Maybe make the top part a bit "squishier"? It feels like it's pretty rigid.

**Comment by MrGrigri** [comment]
Closing this out as niche.
