### ISSUE TITLE
hand-heart

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4253]
I've seen this used to symbolize volunteering. So we'll add this as `hand-heart` but alias it with the following:

- [ ] Volunteer
- [ ] Love
- [ ] Hope

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/61487392-0a3ae880-a963-11e9-992b-f9350b250f5b.png)

## Zip Download

[hand-heart.zip](https://github.com/Templarian/MaterialDesign/files/3408208/hand-heart.zip)

**Comment by CoDEmanX** [comment]
I'm in favor of Google's `volunteer-activism` icon:

![grafik](https://user-images.githubusercontent.com/1309249/62691791-aa6ab700-b9cf-11e9-9e85-625af786ab9b.png)

https://petershaggynoble.github.io/MDI-Sandbox/extended/

[volunteer-activism-svgomg.zip](https://github.com/Templarian/MaterialDesign/files/3480885/volunteer-activism-svgomg.zip) (optimized, markup looks a bit strange...)

**Comment by goyney** [comment]
[![hand-heart](https://materialdesignicons.com/icon/hand-heart)](https://materialdesignicons.com/icon/hand-heart)
