### ISSUE TITLE
Restart Warning

### ISSUE THREAD

**Issue by FANMixco** [Templarian/MaterialDesign#4254]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Let's suppose you need to restart an application or server for X or Y reason, but you should do it carefully because X update can affect your application, but you can do it at your own risk. Then a warning sign can appear with the restart icon.

## Examples

These are my general ideas.

![Warning](https://user-images.githubusercontent.com/1666156/61518401-b1725b00-aa09-11e9-9652-c0118130ca51.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61572741-4b6cee80-aa70-11e9-8492-c3f44b0f34b2.png)
[restart-alert.svg.zip](https://github.com/Templarian/MaterialDesign/files/3413155/restart-alert.svg.zip)

**Comment by goyney** [comment]
[![restart-alert](https://materialdesignicons.com/icon/restart-alert)](https://materialdesignicons.com/icon/restart-alert)
