### ISSUE TITLE
Sikh Religion Symbol

### ISSUE THREAD

**Issue by devsebastian** [Templarian/MaterialDesign#4255]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
We've seen icons of many major religions but none of the Sikh religion. It could be used  wherever the Sikh symbol must be used including websites and apps based or related to this religion.

## Examples

 - [Sikh religion icon](https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Khanda.svg/220px-Khanda.svg.png)
 -  https://i.pinimg.com/originals/ec/3b/f9/ec3bf9d0d152388d6543db751607b9e2.jpg

**Comment by goyney** [comment]
Here's my attempt:
![image](https://user-images.githubusercontent.com/1015040/61922359-207e1100-af2e-11e9-9e15-f56b2dba62f8.png)
[khanda.svg.zip](https://github.com/Templarian/MaterialDesign/files/3433999/khanda.svg.zip)

**Comment by devsebastian** [comment]
That looks great! Thanks goyney. I think it is pretty much recognizable:)

**Comment by goyney** [comment]
[![khanda](https://materialdesignicons.com/icon/khanda)](https://materialdesignicons.com/icon/khanda)
