### ISSUE TITLE
power-socket-eu variant

### ISSUE THREAD

**Issue by jul-fls** [Templarian/MaterialDesign#4256]
Can somebody make a variant for the eu plug but with the third contact which is the earth?

**Comment by goyney** [comment]
There's a couple things here. First, the EU plug doesn't have a third contact as is. Second, and most importantly, there is no way the earth is going to be recognizable at that scale.

Could you elaborate on your use case? Perhaps we can brainstorm other ideas to meet your needs.

**Comment by jul-fls** [comment]
This is for use on Home Assistant with switches
[image: image.png]
and I would like to be able to represent the earth on each of these logos
for more understanding for the users.
Cordially

**Comment by goyney** [comment]
The image you tried to share did not attach to the image. Could you come to the actual issue and try sharing it again?

**Comment by jul-fls** [comment]
https://imgur.com/a/wq8iZPA this is the image

**Comment by goyney** [comment]
> I would like to be able to represent the earth on each of these logos for more understanding for the users.

I don't understand what you mean by this. Regardless, we definitely cannot put the earth in with the plug and make it work at native size.

If you have other ideas for how to depict what you're trying to convey, please let us know.

**Comment by almostserious** [comment]
Just to jump in here, i guess when he is talking about the "Earth" he actually means the 3rd contact that is available on some EU Plugs which is the "ground" or "Erdung" in German. Not actually a logo of planet earth, just a third contact in the lower middle part of the icon.

**Comment by jul-fls** [comment]
Yes you have understand what I wanted to say the ''earth'' or ''ground'' for the third contact which just consists to do a third point between the 2 actual contact but a little higher just a little bit under the limit of the plug

**Comment by goyney** [comment]
That makes way more sense. Like in the States, ungrounded wall outlets are pretty much a thing of the past. There are older homes that still have these, but pretty much electrical code everywhere requires they be updated.

Is this the same in the EU? The reason I ask is because perhaps we should just update the EU plug to include the ground, instead of offering both variants.

**Comment by jul-fls** [comment]
Yes it's the same in EU so you could just adapt the logo to include this
third contact and it will be good.
Thank you

**Comment by almostserious** [comment]
Actually its not. There are 2 Plugs. Its Plug Type E which has the ground as a PIN. And Type F which has the ground as clips on the top and bottom. Type E is used commonly in some countries, while Type F is common in others.
https://www.iec.ch/worldplugs/typeE.htm
https://www.iec.ch/worldplugs/typeF.htm

So it makes sense to have both available.

**Comment by goyney** [comment]
Good information. We can also name them appropriately.

**Comment by jul-fls** [comment]
So who wants to do the EU plug type e and type f logos ?

**Comment by goyney** [comment]
We've begun to talk internally about revamping all of our plug icons to be better representations of the actual plugs. That being said, anyone can contribute, so if you want to take a stab at it, feel free! Just make sure to follow [Material guidelines](https://material.io/design/iconography/system-icons.html#design-principles). 😄 

Otherwise, we have a couple contributors who are from the UK who may look into these as well.

**Comment by GreenTurtwig** [comment]
@jul-fls here's your français one: :tada: 
[![](https://user-images.githubusercontent.com/15905797/61731581-b883cb00-ad73-11e9-8473-f43b44551b8f.png)](https://github.com/Templarian/MaterialDesign/files/3423231/power-socket-fr.zip)

And the German:
[![](https://user-images.githubusercontent.com/15905797/61731802-2c25d800-ad74-11e9-9860-963c05e29f1a.png)](https://github.com/Templarian/MaterialDesign/files/3423232/power-socket-de.zip)

**Comment by jul-fls** [comment]
Thank You for your great work but do you know when it will be accessible from "mdi:power-socket-fr" in Home Assistant ?
Please

**Comment by goyney** [comment]
Hi @jul-fls, we're currently working on speeding up our releases, so I can't give you an exact time frame. However, we are working through a lot of older issues so it may be a few releases before this actually gets included. Just keep following this issue, we'll post here and close it when they've been added.

**Comment by jul-fls** [comment]
Ok Thank You for your very hard work in Material Design Icons !!
Thank You for what you make for the community !

**Comment by GreenTurtwig** [comment]
Do keep in mind that once our release is out, it's up to the contributors of Home Assistant to update the icon set that's in use. So it won't be available immediately. :-)

**Comment by jul-fls** [comment]
Ok that's totally normal but during that I will use the local image which i will convert in .png !

**Comment by goyney** [comment]
[![power-socket-de](https://materialdesignicons.com/icon/power-socket-de)](https://materialdesignicons.com/icon/power-socket-de)[![power-socket-fr](https://materialdesignicons.com/icon/power-socket-fr)](https://materialdesignicons.com/icon/power-socket-fr)
