### ISSUE TITLE
folder-heart

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#4257]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Folder of favorites or liked items.

## Examples

folder with a heart in it

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61572687-802c7600-aa6f-11e9-815a-a4ff4224e4cc.png)![image](https://user-images.githubusercontent.com/1015040/61572690-891d4780-aa6f-11e9-9b40-d049536be6de.png)

[folder-heart.zip](https://github.com/Templarian/MaterialDesign/files/3413153/folder-heart.zip)

**Comment by goyney** [comment]
[![folder-heart](https://materialdesignicons.com/icon/folder-heart)](https://materialdesignicons.com/icon/folder-heart)[![folder-heart-outline](https://materialdesignicons.com/icon/folder-heart-outline)](https://materialdesignicons.com/icon/folder-heart-outline)
