### ISSUE TITLE
Express

### ISSUE THREAD

**Issue by Omar-Aziz** [Templarian/MaterialDesign#4258]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Just like how we have a nodejs icon, a webpack icon, can we have a Express icon? It's not a brand but rather a technology-related logo icon.

## Examples

[Express Icon](https://d2eip9sf3oo6c2.cloudfront.net/tags/images/000/000/359/thumb/expressjslogo.png)
![enter image description here](https://d2eip9sf3oo6c2.cloudfront.net/tags/images/000/000/359/thumb/expressjslogo.png)

**Comment by goyney** [comment]
Express.js does not have an official logo, I'm not sure where you pulled that example from. They do have a workmark:

![image](https://user-images.githubusercontent.com/1015040/61585185-1ae68c80-ab24-11e9-9e57-8a5daf9f8a92.png)

However, that would not translate into an icon at all. I don't think this is something we would add unless they had something official.

**Comment by Omar-Aziz** [comment]
It’s a common icon used in express articles. A simple google search will list a few. Will try somewhere else, thank you.

**Comment by goyney** [comment]
Sorry, we won't add an icon for a brand unless it's the official brand icon and we are able to follow the branding guidelines the company provides. In this case, there is no official icon for Express, so we cannot add anything. Thanks for the suggestion!
