### ISSUE TITLE
Nuxt

### ISSUE THREAD

**Issue by Omar-Aziz** [Templarian/MaterialDesign#4259]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Just like how we have a nodejs icon, a webpack icon, can we have a Nuxt.js icon? It's not a brand but rather a technology-related logo icon.

## Examples

![enter image description here](https://nuxtjs.org/logos/nuxt-square.svg)

**Comment by Templarian** [comment]
Does their brand guidelines allow it to be a single color.

**Comment by goyney** [comment]
I have reached out to determine what the appropriate usage of the Nuxt logo is.

**Comment by manniL** [comment]
cc @atinux @alexchopin

**Comment by alexchopin** [comment]
Hi @Templarian,

The NuxtJS logo can be in a single color, but of course, we would prefer to keep our color present if possible.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61636090-efb68700-ac62-11e9-8c6c-ad9fd9cfa61b.png)
[nuxt.svg.zip](https://github.com/Templarian/MaterialDesign/files/3417600/nuxt.svg.zip)

**Comment by goyney** [comment]
[![nuxt](https://materialdesignicons.com/icon/nuxt)](https://materialdesignicons.com/icon/nuxt)
