### ISSUE TITLE
HBO GO

### ISSUE THREAD

**Issue by ploca14** [Templarian/MaterialDesign#4260]
I have:

- [X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

I want to use this icon along the Netflix and YouTube icons.

## Examples

Include any example images so we know what the icon should look like.

Just the simple HBO GO text logo.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
