### ISSUE TITLE
duo

### ISSUE THREAD

**Issue by annymosse** [Templarian/MaterialDesign#4261]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

my icon its exist already at google material icons `duo` icon

## Examples
https://material.io/tools/icons/?search=duo&style=baseline

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/roadmap/brand-icons

Thinking this might be a better fit for Simple Icons. Maybe try asking for it in their repo as we're moving away from brand related icons.

Also everytime we add a Google video app they end up killing it and replacing it with something else. 😄

**Comment by Templarian** [comment]
#3013

**Comment by annymosse** [comment]
hahaha it's true each time they bring a new apps to follow the life needs ,whenever i like it's logos not her sevices or apps and i prefer to get all the icons who i like from only a single source font else your icons i prefer to use for ex `duo icon` from it's original souce `google material design icons` ;thank you @Templarian
