### ISSUE TITLE
Amazon Echo Device icon

### ISSUE THREAD

**Issue by JayBigGuy10** [Templarian/MaterialDesign#4262]
I think an amazon echo icon of the physical device is needed, it would be used to represent different versions of the device, the normal and the dot. something like this:
https://www.iconfinder.com/icons/3719010/alexa_amazon_assistant_dot_echo_smart_speaker_icon
and this
https://www.iconfinder.com/icons/1035367/alexa_amazon_command_echo_smart_speaker_voice_icon

**Comment by goyney** [comment]
We have `amazon-alexa` for this case:

[![amazon-alexa](https://materialdesignicons.com/icon/amazon-alexa)](https://materialdesignicons.com/icon/amazon-alexa)

At this time, we are not interested in adding icons depicting physical smart assistant devices. There's too many and they change appearances too frequently.

**Comment by DelanoLima** [comment]
@mririgoyen hi!

I can't find this icon. Is it no longer available?

**Comment by JayBigGuy10** [comment]
@DelanoLima it never existed, this issue has the rejected tag
