### ISSUE TITLE
Kubernetes Icon

### ISSUE THREAD

**Issue by roshankadasani** [Templarian/MaterialDesign#4263]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Used in concourse ci. 

## Examples

Include any example images so we know what the icon should look like.
https://cdn2.iconfinder.com/data/icons/mixd/512/15_kubernetes-512.png

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/61652422-e5f24b00-ac85-11e9-9dda-835a99003930.png)
[k8n.svg.zip](https://github.com/Templarian/MaterialDesign/files/3418587/k8n.svg.zip)

**Comment by goyney** [comment]
[![kubernetes](https://materialdesignicons.com/icon/kubernetes)](https://materialdesignicons.com/icon/kubernetes)
