### ISSUE TITLE
email-send(-outline) & email-receive(-outline)

### ISSUE THREAD

**Issue by harsha20599** [Templarian/MaterialDesign#4264]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) and found an issue which is closed due to lack of feedback.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To represent the email sent and email received for the activity in my ATS project.

### Email sent
<img src="https://user-images.githubusercontent.com/20438252/61700958-f6c0c080-ad5a-11e9-9296-0e09c9807535.png" width="48">

### Email received
<img src="https://user-images.githubusercontent.com/20438252/61701041-2079e780-ad5b-11e9-9878-141dc4e30b53.png" width="48">

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/61713737-7b3d2000-ad16-11e9-8332-535e4ef5c7d9.png) ![image](https://user-images.githubusercontent.com/4528551/61713760-898b3c00-ad16-11e9-8ec1-1932795f4c20.png)
![image](https://user-images.githubusercontent.com/4528551/61713776-960f9480-ad16-11e9-94a9-356fc2d0c500.png) ![image](https://user-images.githubusercontent.com/4528551/61713795-a32c8380-ad16-11e9-8177-38c762f2957d.png)

---
#### Files

[email-(send__receive)(-outline).zip](https://github.com/Templarian/MaterialDesign/files/3422117/email-.send__receive.-outline.zip)

**Comment by icistrate** [comment]
Can somebody create an "email in action" something along these lines?
![sample](https://user-images.githubusercontent.com/17759960/61790662-1e299300-ae18-11e9-97c6-0b93aa515a03.jpg)

**Comment by goyney** [comment]
I don't know if these really work, they definitely break the 2dp padding rule.
![image](https://user-images.githubusercontent.com/1015040/61793792-d130c700-aded-11e9-8bc7-e83b29f3772e.png)![image](https://user-images.githubusercontent.com/1015040/61793777-c8d88c00-aded-11e9-8812-9d9267098ca9.png)

[email-send-variant.zip](https://github.com/Templarian/MaterialDesign/files/3426802/email-send-variant.zip)

**Comment by goyney** [comment]
@MrGrigri Your outline contributions will need be updated. The base of `email-outline` was updated last night.

**Comment by MrGrigri** [comment]
I used that specific one. I took it from your issue.

**Comment by goyney** [comment]
> I used that specific one. I took it from your issue.

Oh, my bad. 😄

**Comment by goyney** [comment]
[![email-send](https://materialdesignicons.com/icon/email-send)](https://materialdesignicons.com/icon/email-send)[![email-send-outline](https://materialdesignicons.com/icon/email-send-outline)](https://materialdesignicons.com/icon/email-send-outline)
[![email-receive](https://materialdesignicons.com/icon/email-receive)](https://materialdesignicons.com/icon/email-receive)[![email-receive-outline](https://materialdesignicons.com/icon/email-receive-outline)](https://materialdesignicons.com/icon/email-receive-outline)
