### ISSUE TITLE
briefcase-clock

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4266]
I was in need of an icon that represented work hours and I thought this was the best representation.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/61802979-9b401280-adee-11e9-8c89-9855214bcff4.png) ![image](https://user-images.githubusercontent.com/4528551/61802930-84012500-adee-11e9-81dc-526fc1cbe2c3.png)

## Zip Download

[briefcase-clock.zip](https://github.com/Templarian/MaterialDesign/files/3427338/briefcase-clock.zip)

**Comment by goyney** [comment]
[![briefcase-clock](https://materialdesignicons.com/icon/briefcase-clock)](https://materialdesignicons.com/icon/briefcase-clock)[![briefcase-clock-outline](https://materialdesignicons.com/icon/briefcase-clock-outline)](https://materialdesignicons.com/icon/briefcase-clock-outline)
