### ISSUE TITLE
Flip (mirror image)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4268]
Related but different: #818

Not sure about the naming, could be `image-mirror-*`, `mirror-*`, `flip-*`...

Google calls the horizontal one `flip` and doesn't have the vertical one on material.io/icons, but it's included in the Google Docs spritesheet.

## Preview

![grafik](https://user-images.githubusercontent.com/1309249/61851739-0f92b880-aeb8-11e9-8c01-80a2d8ca0f9e.png) ![grafik](https://user-images.githubusercontent.com/1309249/61851707-ff7ad900-aeb7-11e9-8d91-a4756f75f0f9.png)

## Zip Download

[flip.zip](https://github.com/Templarian/MaterialDesign/files/3430059/flip.zip)

**Comment by goyney** [comment]
[![flip-horizontal](https://materialdesignicons.com/icon/flip-horizontal)](https://materialdesignicons.com/icon/flip-horizontal)[![flip-vertical](https://materialdesignicons.com/icon/flip-vertical)](https://materialdesignicons.com/icon/flip-vertical)
