### ISSUE TITLE
Razor Blade

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4269]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Tool for cutting in the context of a non-linear video editor - it's called razor blade tool in popular software, so box-cutter doesn't "cut" it.

## Examples

For larger sizes this would work, but at native size there is way too much detail and it's hardly recognizable as razor blade:

![grafik](https://user-images.githubusercontent.com/1309249/61857196-eed06000-aec3-11e9-8203-6c92286dc509.png)

**Comment by MrGrigri** [comment]
I believe this is too much detail in the middle and is lost at 1x

**Comment by goyney** [comment]
I don't understand how that's a razor blade. Each edge looks like the razor blades "handle"?

![image](https://user-images.githubusercontent.com/1015040/61876932-f855ca00-aebb-11e9-9c43-00a8cb1b34ee.png)

**Comment by MrGrigri** [comment]
I believe that is a razor for shaving. [https://en.wikipedia.org/wiki/Safety_razor](https://en.wikipedia.org/wiki/Safety_razor)

**Comment by annymosse** [comment]
i think he have a right and its much better to have like this picture as icon 
![](https://www.telegraph.co.uk/content/dam/beauty/2019/01/22/Gillette-SkinGuard-Sensitive-razor_trans_NvBQzQNjv4BqY0XMnE4berkpvWhc-fw2CB5sdRarK_7jBbmKnuqKQ_w.jpg?imwidth=450)

**Comment by goyney** [comment]
Yeah, I think the original proposal is too niche. A regular razor blade could be useful, and if you want to depict shaving, a shaving razor as pictured above would be more recognizable.

**Comment by annymosse** [comment]
@goyney which the best icon designer for linux users ? sometimes i have ideas to make them whenver i don't know the right and the good way to go ahead

**Comment by CoDEmanX** [comment]
If you Google for icon razor blade this is what you get:

![Screenshot_20190725-182409](https://user-images.githubusercontent.com/1309249/61891406-e1d65f80-af09-11e9-95ef-808f24053faf.jpg)

Adobe Premiere:

![Screenshot_20190725-183138](https://user-images.githubusercontent.com/1309249/61891824-d6376880-af0a-11e9-80bd-701a2c611f39.jpg)

DaVinci Resolve:

![Screenshot_20190725-183321](https://user-images.githubusercontent.com/1309249/61891890-f7985480-af0a-11e9-9ca9-69e13037ba5e.jpg)

I am not aware of any software which would use a safety razor, scissors or knife icon.

**Comment by annymosse** [comment]
hi i tried my first icon ever using `Gravit desinger` then i couldn't save it as a single shape with transparent parts this is how its look like 
![DeepinScreenshot_20190725173942](https://user-images.githubusercontent.com/24898178/61892237-375b3e00-af03-11e9-94d6-337bdec21945.png)

**Comment by goyney** [comment]
@annymosse If you have a suggestion or contribution for a new icon, please create a new issue for it. This issue is tracking the suggestion of a razor blade type icon.

**Comment by annymosse** [comment]
ok @goyney thanks, whenever i just tried to contributing few files when i can :+1:

**Comment by annymosse** [comment]
how about somthing like this pic
![Razor](https://user-images.githubusercontent.com/24898178/61899125-b1df8a00-af12-11e9-8f60-811964edb0cf.png)

**Comment by MrGrigri** [comment]
@annymosse, I love your enthusiasm to help, however, there are strict guidelines that we follow. You can have a look at them [here](https://material.io/design/iconography/system-icons.html). Following up on the issue, what is being requested isn't a shaving razor, but a general razor used in programs to denote splicing, trimming, or cutting.

**Comment by annymosse** [comment]
:smile: i feel of myself stupid ,thanks @MrGrigri i will take a look , it may guid me to help on the future :+1:

**Comment by JamesCoyle** [comment]
What if you simplify it a bit?
![image](https://user-images.githubusercontent.com/10384436/62743328-efc3ce80-ba39-11e9-8cf1-1dfc7f84f021.png)
(not a vector)

**Comment by goyney** [comment]
Still think we can't just add that. If we add razor blades, we need the more common razor in addition to the proposed safety razor.

**Comment by goyney** [comment]
Thoughts on these?
![image](https://user-images.githubusercontent.com/1015040/134250239-7abb4075-2a0f-416c-9eb8-198f08c0dca0.png)![image](https://user-images.githubusercontent.com/1015040/134250277-faca92d8-9fa4-4c50-8578-f719401842c4.png)
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7206385/Archive.zip)

**Comment by Simran-B** [comment]
I think they will work in context. Not super happy about the details at native size, but can't think of a better solution.

**Comment by goyney** [comment]
[![razor-single-edge](https://materialdesignicons.com/icon/razor-single-edge)](https://materialdesignicons.com/icon/razor-single-edge)[![razor-double-edge](https://materialdesignicons.com/icon/razor-double-edge)](https://materialdesignicons.com/icon/razor-double-edge)
