### ISSUE TITLE
Connect/disconnect icon

### ISSUE THREAD

**Issue by Poorchop** [Templarian/MaterialDesign#427]
Thank you for your work on these icons.

I would like to request a connect icon. I've typically seen this icon represented as something along the lines of a solid line or ball fitting into a socket. Similarly, a disconnect icon could be the ball and socket slightly pulled apart and with a slash through it. Even if it were something completely different stylistically, it would be a great addition.

**Comment by CoDEmanX** [comment]
Maybe `power` and a strike-through version?
http://www.google.com/design/icons/#ic_power

**Comment by Poorchop** [comment]
That sounds like a good idea. Something like this, right?

![ic_power_black_24dp_2x](https://cloud.githubusercontent.com/assets/5256208/8671480/6b373a56-29f3-11e5-938b-5b066bc9c33c.png)

**Comment by CoDEmanX** [comment]
I hope it's recognizable, I took the stroke from the template:
![power-off](https://cloud.githubusercontent.com/assets/1309249/8672195/64d5bf00-2a2c-11e5-8c22-ad0d5c53d757.png) https://www.dropbox.com/s/yi1qm0jtg6012qk/power-off.svg?dl=0

**Comment by Templarian** [comment]
[![power-plug](https://materialdesignicons.com/icon/power-plug)](https://materialdesignicons.com/icon/power-plug) [![power-plug-off](https://materialdesignicons.com/icon/power-plug-off)](https://materialdesignicons.com/icon/power-plug-off)

**Comment by Poorchop** [comment]
Looks great, thank you.
