### ISSUE TITLE
double quotes icon

### ISSUE THREAD

**Issue by iAmAndroidDeveloper** [Templarian/MaterialDesign#4270]
double quotes icon like this 
https://www.google.com/search?biw=1366&bih=608&tbm=isch&sa=1&ei=bY85XYHbKtmCyAP0p5LYAQ&q=double+quotes+icon&oq=double+quotes+icon&gs_l=img.3...0.0..324305...0.0..0.0.0.......0......gws-wiz-img.aupm6vhSvlQ&ved=0ahUKEwjBxa7m-M_jAhVZAXIKHfSTBBsQ4dUDCAY&uact=5

**Comment by PeterShaggyNoble** [comment]
[![format-quote-close](https://materialdesignicons.com/icon/format-quote-close)](https://materialdesignicons.com/icon/format-quote-close) [![format-quote-open](https://materialdesignicons.com/icon/format-quote-open)](https://materialdesignicons.com/icon/format-quote-open)
