### ISSUE TITLE
[5.0] Rename all "settings" icons

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4271]
We intend to clean up all of our `settings` variant icons. To indicate "settings," there are currently two competing variants: one with 3 dots at the bottom of the icon _or_ a cog somewhere in the icon. In both cases, we're inferring the meaning of "settings" based on the variant, which is something we do not do with any other icon variant.

To solve this issue, we are planning on renaming all "settings" variant icons:
_*replacement names subject to change_
- Icons with the 3 dots will have the word `settings` replaced with `dots`
- Icons with a cog will have the word `settings` replaced with `cog`

After the icons have been renamed, we will add the original name as an alias for the icon so they may continue to be found via our search mechanism.

Since this is a breaking change, it will have to happen on either the `4.0` or `5.0` release.

---

As of this posting, we have 27 icons that use the word "settings" in the name of the icon and will be affected by this change. These icons are listed below:

- [ ] `account-settings` => `account-dots`
- [ ] `bluetooth-settings` => `bluetooth-dots`
- [ ] `card-bulleted-settings` => `card-bulleted-dots`
- [ ] `card-bulleted-settings-outline` => `card-bulleted-dots-outline`
- [ ] `cellphone-settings` => `cellphone-dots`
- [ ] `cellphone-settings-variant` => `cellphone-cog`
- [ ] `content-save-settings` => `content-save-dots`
- [ ] `content-save-settings-outline` => `content-save-dots-outline`
- [ ] `credit-card-settings` => `credit-card-dots`
- [ ] `database-settings` => `database-dots`
- [ ] `eye-settings` => `eye-dots`
- [ ] `eye-settings-outline` => `eye-dots-outline`
- [ ] `headphones-settings` => `headphones-dots`
- [ ] `keyboard-settings` => `keyboard-dots`
- [ ] `keyboard-settings-outline` => `keyboard-dots-outline`
- [ ] `message-settings` => `message-dots`
- [ ] `message-settings-variant` => `message-cog`
- [ ] `microphone-settings` => `micorphone-dots`
- [ ] `phone-settings` => `phone-dots`
- [ ] `power-settings` => `power-dots`
- [ ] `printer-settings` => `printer-dots`
- [ ] `router-wireless-settings` => `router-wireless-dots`
- [ ] `settings` => `cog`
- [ ] `settings-box` => `cog-box`
- [ ] `settings-helper` => `dots-helper`
- [ ] `settings-outline` => `cog-outline`
- [ ] `table-settings` => `table-dots`

**Comment by Templarian** [comment]
Still not 100% sure if we want to do this change. As we get closer to 5.0.

**Comment by Templarian** [comment]
Update, hold off on this one. Definitely thinking this needs more discussion.

**Comment by goyney** [comment]
After rereading this, I agree we should not do the original proposal.

My new proposal is this:

- Any icon with the gear/cog in it should have `settings` changed to `cog` in its name. Then an alias should be added for settings.
- Any icon with the three dots under it should have `settings` in its name.

**Comment by goyney** [comment]
Done!
