### ISSUE TITLE
account-dots-outline

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4272]
I have:

- [✔] Searched open issues to make sure there isn't a request for this icon.
- [✔] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/53331546/61935297-7c768300-af8a-11e9-8138-f0dc12de3757.png)

## Zip Download

[account-settings-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3434754/account-settings-outline.svg.zip)

**Comment by JamesCoyle** [comment]
Need to be aware of #4271

**Comment by goyney** [comment]
[![account-settings-outline](https://materialdesignicons.com/icon/account-settings-outline)](https://materialdesignicons.com/icon/account-settings-outline)
