### ISSUE TITLE
account-tie-outline

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4273]
I have:

- [✔] Searched open issues to make sure there isn't a request for this icon.
- [✔] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/53331546/61935514-f870cb00-af8a-11e9-86dc-7518cb344355.png)

## Zip Download

[account-tie-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3434765/account-tie-outline.svg.zip)

**Comment by goyney** [comment]
[![account-tie-outline](https://materialdesignicons.com/icon/account-tie-outline)](https://materialdesignicons.com/icon/account-tie-outline)
