### ISSUE TITLE
account-supervisor-outline

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4274]
I have:

- [✔] Searched open issues to make sure there isn't a request for this icon.
- [✔] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/53331546/61935662-438ade00-af8b-11e9-93b4-b12c27816e8f.png)

## Zip Download

[account-supervisor-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3434772/account-supervisor-outline.svg.zip)

**Comment by MrGrigri** [comment]
Is there no way for the foreground silhouette to be outlined?

**Comment by David-Jackson** [comment]
![image](https://user-images.githubusercontent.com/11835431/62077951-62060900-b219-11e9-89f2-ac6f8b6786ed.png)
[account-supervisor-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3444100/account-supervisor-outline.svg.zip)

**Comment by JamesCoyle** [comment]
Google is a bit funny with this one. I prefer @David-Jackson's version as its more outliney.

**Comment by goyney** [comment]
Yeah, but it breaks the rules. A 2dp stroke would make the smaller one filled. Dunno what to do with this one.

**Comment by MrGrigri** [comment]
What about with a 1.5-dp stroke?

![account-supervisor-outline](https://user-images.githubusercontent.com/4528551/62875732-c4aed880-bce0-11e9-8633-e84d63e72a1e.png)

---
#### Files

[account-supervisor-outline.zip](https://github.com/Templarian/MaterialDesign/files/3493140/account-supervisor-outline.zip)

**Comment by goyney** [comment]
[![account-supervisor-outline](https://materialdesignicons.com/icon/account-supervisor-outline)](https://materialdesignicons.com/icon/account-supervisor-outline)
