### ISSUE TITLE
account-child-outline

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4275]
I have:

- [✔] Searched open issues to make sure there isn't a request for this icon.
- [✔] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/53331546/61935800-8947a680-af8b-11e9-8a0e-3b333609ca0a.png)

## Zip Download

[account-child-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3434775/account-child-outline.svg.zip)

**Comment by Templarian** [comment]
Looking at the preview, it might be slightly off the grid. Try and round to `1.5dp` (but might be able to make it look nice with `2dp`).

**Comment by goyney** [comment]
[![account-child-outline](https://materialdesignicons.com/icon/account-child-outline)](https://materialdesignicons.com/icon/account-child-outline)
