### ISSUE TITLE
alien-outline

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4276]
I have:

- [✔] Searched open issues to make sure there isn't a request for this icon.
- [✔] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/53331546/61941371-9e2a3700-af97-11e9-8e58-9df11d3b3bcc.png)

## Zip Download

[alien-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3435110/alien-outline.svg.zip)

**Comment by goyney** [comment]
[![alien-outline](https://materialdesignicons.com/icon/alien-outline)](https://materialdesignicons.com/icon/alien-outline)
