### ISSUE TITLE
gamma

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4277]
I have:

- [✔] Searched open issues to make sure there isn't a request for this icon.
- [✔] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/53331546/61948483-3af4d080-afa8-11e9-80b6-3d2116a5450e.png)

## Zip Download

[gamma.svg.zip](https://github.com/Templarian/MaterialDesign/files/3435498/gamma.svg.zip)

**Comment by goyney** [comment]
[![gamma](https://materialdesignicons.com/icon/gamma)](https://materialdesignicons.com/icon/gamma)
