### ISSUE TITLE
Add herrsascha as a Contributor

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4278]
Welcome, @herrsascha! Since you've hit at least 5 icon contributions, we'd like to make sure you get credit for your efforts.

Please optionally provide us with the follow for your profile:
- [x] Twitter
- [x] Website
- [x] Short bio (like 250 words max)

---

Upcoming additions: #4276, #4275, #4274, #4273, #4272, #4277, #4280

**Comment by goyney** [comment]
@herrsascha Please provide us with your twitter handle and website (if available) and a short bio so we can add you as a Contributor. 😄

**Comment by herrsascha** [comment]
Uhh thanks ♥

Twitter: **/whlgmth**
Website: **www.saschawohlgemuth.com** (offline atm)

Bio:
**Interaction Designer and Usability Engineer living and working in Munich, Germany.
With over 8 years of experience in different creative fields such as brand, print and digital product design - my focus is on creating unique visual concepts and gripping digital experiences. I’m always looking for creative and innovative solutions, aiming to reach timeless and fresh results to get the best out of each project. To successfully create & optimize digital products agile productive collaboration is a key ingredient. In the process of analyzing customers‘ interactions I work side by side with stakeholders, product owners and developers to improve the customer experience.**

Hope this Bio isn't too long 😉

**Comment by Templarian** [comment]
Added. The bio got truncated. I'll hopefully have the ability rolled out soon-ish to edit it/manage your profile. The icons will get assigned shortly.

**Comment by goyney** [comment]
No icons have yet been added for @herrsascha, but now that he is added, we can assign them to him when they get added! 😄 Closing this since no further action needs to happen at this moment.
