### ISSUE TITLE
epsilon

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4280]
I have:

- [✔] Searched open issues to make sure there isn't a request for this icon.
- [✔] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/53331546/62032921-1f2d3c80-b1eb-11e9-85d8-2643b6d27d21.png)

## Zip Download

[epsilon.svg.zip](https://github.com/Templarian/MaterialDesign/files/3441001/epsilon.svg.zip)

**Comment by David-Jackson** [comment]
I think the padding could be reduced to match material guidelines.

Simply scaling (Line thickness >2dp):
![image](https://user-images.githubusercontent.com/11835431/62060993-3c1a3d80-b1f4-11e9-92ae-6b5c6bba932a.png)
[epsilon.svg.zip](https://github.com/Templarian/MaterialDesign/files/3443061/epsilon.svg.zip)

or maintaining the 2dp thick stroke:
![image](https://user-images.githubusercontent.com/11835431/62061520-59034080-b1f5-11e9-85ea-02bb8a6bfb26.png)
[epsilon.svg.zip](https://github.com/Templarian/MaterialDesign/files/3443062/epsilon.svg.zip)

**Comment by goyney** [comment]
[![epsilon](https://materialdesignicons.com/icon/epsilon)](https://materialdesignicons.com/icon/epsilon)
