### ISSUE TITLE
Beehive

### ISSUE THREAD

**Issue by guenth39** [Templarian/MaterialDesign#4281]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

maybe a combination of #1978 and a modern or classical beehive
![image](https://user-images.githubusercontent.com/29251617/62063667-9e426500-b22b-11e9-9e7e-edc1be6898e1.png)
![image](https://user-images.githubusercontent.com/29251617/62063685-a8fcfa00-b22b-11e9-8d94-f61e5e312cfa.png)
![image](https://user-images.githubusercontent.com/29251617/62063714-ba460680-b22b-11e9-9bd8-9a45bfef2082.png)
![image](https://user-images.githubusercontent.com/29251617/62063731-c16d1480-b22b-11e9-9cad-6da9ffdf70af.png)

**Comment by goyney** [comment]
Would something like `hexagon-multiple` cover your use case? (e.g. honeycomb)

[![hexagon-multiple](https://materialdesignicons.com/icon/hexagon-multiple)](https://materialdesignicons.com/icon/hexagon-multiple)

**Comment by goyney** [comment]
We could also add `hexagon-multiple-outline`.
![image](https://user-images.githubusercontent.com/1015040/62095261-df4b7100-b24d-11e9-9409-f8b3d7dde8de.png)

[hexagon-multiple-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3444879/hexagon-multiple-outline.svg.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/62095923-e4a9bb00-b24f-11e9-9109-308919ab8358.png)
[beehive.svg.zip](https://github.com/Templarian/MaterialDesign/files/3444922/beehive.svg.zip)

**Comment by guenth39** [comment]
Unfortunately the hexagon-multiple doesn't cover my use case, but I really like the beehive! For bee is flying around the beehive we could maybe add a bee in the right top of the icon and for inside the beehive a sleeping Z Z Z?

**Comment by goyney** [comment]
Unfortunately, no, there is just no room to include a bee at the small scale we're working with. You could combine its use with our `bee` icon.

**Comment by guenth39** [comment]
Okay, it's fine for me. Thank you for your help :) How long it will need until the icon is available?

**Comment by goyney** [comment]
We work on icons in the order they're request/contributed to. Typically, we've been releasing about 100 new icons a month, but we are actively trying to increase that turn around time. That being said, we're about to release `3.9` and `4.0` shouldn't be too long after that. So, it may be a few releases before this gets out.

**Comment by goyney** [comment]
I hate my beehive, so I took another stab at it.

![image](https://user-images.githubusercontent.com/1015040/62748001-ef6d0880-ba24-11e9-9889-6d63685705c3.png)
[beehive.svg.zip](https://github.com/Templarian/MaterialDesign/files/3484314/beehive.svg.zip)

**Comment by goyney** [comment]
[![hexagon-multiple-outline](https://materialdesignicons.com/icon/hexagon-multiple-outline)](https://materialdesignicons.com/icon/hexagon-multiple-outline)
[![beehive-outline](https://materialdesignicons.com/icon/beehive-outline)](https://materialdesignicons.com/icon/beehive-outline)
