### ISSUE TITLE
toothbrush

### ISSUE THREAD

**Issue by atar-axis** [Templarian/MaterialDesign#4282]
I have:

- [ x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It could be used for dentist websites e.g.

## Examples

![image](https://user-images.githubusercontent.com/11148588/62075984-df943e00-b246-11e9-8876-03255cf9c0e7.png)
![image](https://user-images.githubusercontent.com/11148588/62076060-09e5fb80-b247-11e9-89da-c0719240ffc9.png)
![image](https://user-images.githubusercontent.com/11148588/62076145-326df580-b247-11e9-8d65-5aadc5fe4567.png)

**Comment by goyney** [comment]
Kinda feel meh about both of these.
![image](https://user-images.githubusercontent.com/1015040/62095077-44eb2d80-b24d-11e9-9cfb-0a56536584bd.png)![image](https://user-images.githubusercontent.com/1015040/62095055-356be480-b24d-11e9-967a-51c4d2818889.png)

[toothbrush.zip](https://github.com/Templarian/MaterialDesign/files/3444870/toothbrush.zip)

**Comment by atar-axis** [comment]
Hey @goyney, thank you for your fast draft! Its definitely the right direction in my honest opinion, but you are right - it is still looking a bit unnatural... maybe because of the width of the lines?
I don't know too much about your design rules, but I would feeld a bit more comfortable with something like this:

![image](https://user-images.githubusercontent.com/11148588/62111786-a47b2480-b2b1-11e9-8efa-f7d239cd8e4b.png)
[toothbrush-paste.zip](https://github.com/Templarian/MaterialDesign/files/3445771/toothbrush-paste.zip)

Anyway, I really appreaciate your work!

**Comment by JamesCoyle** [comment]
What if you get rid of the bristles and just use a rectangle?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/62747575-188c9980-ba23-11e9-8ef2-705f49a3aefa.png)![image](https://user-images.githubusercontent.com/1015040/62747578-1f1b1100-ba23-11e9-9fa4-7b485730e3ad.png)

Thoughts?

**Comment by atar-axis** [comment]
I like the second one the most! But something about the proportions (upper part/lower) is still a bit unnatural.

http://www.soidergi.com/wp-content/uploads/ou/outline-toothbrush-toothpaste-icon-illustration-vector.jpg

**Comment by CoDEmanX** [comment]
I like try 3 and 4, unsure whether I like the individial bristles or the stylized better.

Tried something myself but it's way too busy:

![grafik](https://user-images.githubusercontent.com/1309249/62808061-53f89800-baf7-11e9-922c-074edecf01cc.png)

Also tried to iterate on Michael's toothbrush:

![grafik](https://user-images.githubusercontent.com/1309249/62809352-fa926800-bafa-11e9-9016-a7815fad4bfc.png)
![grafik](https://user-images.githubusercontent.com/1309249/62809388-185fcd00-bafb-11e9-97e6-e82cc3fe25d7.png)
![grafik](https://user-images.githubusercontent.com/1309249/62809432-34fc0500-bafb-11e9-9e27-26d8cf6dd5ce.png)
![grafik](https://user-images.githubusercontent.com/1309249/62809832-5f01f700-bafc-11e9-8d73-11bf4fc7b621.png)

**Comment by goyney** [comment]
[![toothbrush](https://materialdesignicons.com/icon/toothbrush)](https://materialdesignicons.com/icon/toothbrush)[![toothbrush-paste](https://materialdesignicons.com/icon/toothbrush-paste)](https://materialdesignicons.com/icon/toothbrush-paste)

**Comment by CoDEmanX** [comment]
2dp would had been too bold indeed:

![grafik](https://user-images.githubusercontent.com/1309249/62862675-d5724500-bd06-11e9-85d3-e56f20d01105.png)

I came up with a slight modification for the upper toothbrush terminal. Not sure if it really makes a difference in this icon, but it might make it easier to style an electric toothbrush somewhat similar:

![grafik](https://user-images.githubusercontent.com/1309249/62862656-c1c6de80-bd06-11e9-8305-bea7483164ea.png)

Electric toothbrush suggestion (see #2388):

![grafik](https://user-images.githubusercontent.com/1309249/62863677-d193f200-bd09-11e9-8bdb-9087c193a205.png)

**Comment by JapanYoshi** [comment]
Honestly I like "try4" the best. The electric toothbrush from the last one just looks like a key to me, not a toothbrush.

**Comment by CoDEmanX** [comment]
@JapanYoshi You mean with individual bristles? Then the electric toothbrush icon would need to be like this:

![grafik](https://user-images.githubusercontent.com/1309249/62864950-6d732d00-bd0d-11e9-94a4-ba8368c80e60.png)

**Comment by goyney** [comment]
The individual bristles are overly literal and go against guidelines.

**Comment by goyney** [comment]
We'll add the electric version in #2388.

**Comment by CoDEmanX** [comment]
Updated the icons:

![grafik](https://user-images.githubusercontent.com/1309249/62905422-b4dbd680-bd6a-11e9-95ad-5cfc2a0e743f.png)

![grafik](https://user-images.githubusercontent.com/1309249/62905432-c2915c00-bd6a-11e9-91f1-3087757210b6.png)
