### ISSUE TITLE
Arrow Left Right Double

### ISSUE THREAD

**Issue by lpiguet** [Templarian/MaterialDesign#4283]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/5504162/62114712-87495480-b2b7-11e9-8dae-cffc7c1a8e8a.png)

This was built by reusing the existing arrow-left-right.

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[arrow-left-right-double.zip](https://github.com/Templarian/MaterialDesign/files/3445921/arrow-left-right-double.zip)

**Comment by JamesCoyle** [comment]
We already have this;
[![](https://materialdesignicons.com/icon/swap-horizontal
)](https://materialdesignicons.com/icon/swap-horizontal)

**Comment by lpiguet** [comment]
Me = blind. Thank you. I was all happy to contribute something. Next time.

**Comment by JamesCoyle** [comment]
No problem. I've added a couple of aliases to the swap icons to make them easier to search for. Hope to see more contributions from you in the future! :)
