### ISSUE TITLE
Add PerthTotty as a Contributor

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4285]
Welcome, @PerthTotty! Since you've hit at least 5 icon contributions, we'd like to make sure you get credit for your efforts.

Please optionally provide us with the follow for your profile:
- [ ] Your Name
- [ ] Twitter
- [ ] Website
- [ ] Short bio (like 250 words max)

---

**Icons to assign:**

- [x] book-remove
- [x] book-multiple-remove
- [x] book-multiple-plus
- [x] book-multiple-minus
- [x] map-legend

Upcoming additions: #3225

**Comment by Templarian** [comment]
Added a placeholder account and assigned these five over.

Eventually, you'll be able to edit this data. Still working on revamping this feature.

**Comment by goyney** [comment]
Icons reassigned. Leaving this open for a little bit to allow @PerthTotty to opt-in to providing a little bit more info. 😄

**Comment by goyney** [comment]
Going to close this due to no response. Feel free to comment back here if you wish to provide any more details. In the future, all contributors will be able to edit their details via the new website.
