### ISSUE TITLE
Add idevo89 as a Contributor

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4286]
Welcome, @idevo89! Since you've hit at least 5 icon contributions, we'd like to make sure you get credit for your efforts.

Please optionally provide us with the follow for your profile:
- [ ] Your Name
- [ ] Twitter
- [ ] Website
- [x] Short bio (like 250 words max)

---

**Icons to assign:**

- [x] remote-off
- [x] remote-tv-off

Upcoming additions: #4102, #4027

**Comment by Templarian** [comment]
Added a placeholder account and assigned these two over.

Eventually, you'll be able to edit this data. Still working on revamping this feature.

**Comment by goyney** [comment]
Leaving this open for a little bit to allow @idevo89 to opt-in to providing a little bit more info. 😄

**Comment by idevo89** [comment]
Bio:
Electronics and communications engineer in security and home automation, IoT developer
