### ISSUE TITLE
Add qnp as a Contributor

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4287]
Welcome, @qnp! Since you've hit at least 5 icon contributions, we'd like to make sure you get credit for your efforts.

Please optionally provide us with the follow for your profile:
- [x] Twitter
- [x] Website
- [x] Short bio (like 250 words max)

---

**Icons to assign:**

- [x] map-marker-alert
- [x] map-marker-alert-outline

Upcoming additions: #4243, #4241, #4211, #4074

**Comment by Templarian** [comment]
Added a placeholder account and assigned these two over.

Eventually, you'll be able to edit this data. Still working on revamping this feature.

**Comment by qnp** [comment]
Hello @goyney 
Thanks for your credits ! I hope I could help comunity as much as I can.

- Twitter: @ekqnp
- Website: http://www.francoisrisoud.com/
- Short bio:

---

Paris, from PhD in quantum physics to full-stack developer, currently working at Zoov – start-up developing an innovative shared e-bike service. Love digital art and music: composer and DJ for Bredrin Records.

---

Best regards

**Comment by Templarian** [comment]
Working on the ability shortly for everyone to be able to edit their own meta data.

Closing as this will be completed shortly.
