### ISSUE TITLE
Add TheChilliPL as a Contributor

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4288]
Welcome, @TheChilliPL! Since you've hit at least 5 icon contributions, we'd like to make sure you get credit for your efforts.

Please optionally provide us with the follow for your profile:
- [ ] Your Name
- [ ] Twitter
- [ ] Website
- [ ] Short bio (like 250 words max)

---

**Icons to assign:**

- [x] radioactive-off
- [x] nfc-off
- [x] nfc-variant-off
- [x] delete-circle-outline
- [x] cloud-alert

**Comment by Templarian** [comment]
Created. We can assign these over. I'll update if we get any details.

**Comment by goyney** [comment]
Icons reassigned. Leaving this open for a little bit to allow @TheChilliPL to opt-in to providing a little bit more info. 😄

**Comment by terreng** [comment]
Hey can I get in on this too? http://materialdesignicons.com/contributor/Terren
You can take everything from my GitHub profile (bio, website, image).

**Comment by goyney** [comment]
We'll be adding the ability for current contributors the ability to update their own info in the future. For now, don't worry! Any new icons you create are being attributed to you.

**Comment by goyney** [comment]
Going to close this due to no response. Feel free to comment back here if you wish to provide any more details. In the future, all contributors will be able to edit their details via the new website.
