### ISSUE TITLE
Celebration icons

### ISSUE THREAD

**Issue by eman1986** [Templarian/MaterialDesign#4289]
I have:

- [ X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

could be used for a birthday Ecard or an upcoming company holiday party.

## Examples

confetti is a great example of what I'm talking about.

**Comment by goyney** [comment]
Possible duplicate of https://github.com/Templarian/MaterialDesign/issues/3148.

**Comment by eman1986** [comment]
it does look similar, not sure why I couldn't find that when I was searching for a related request. I can close this ticket seeing that a similar request is already in queue
