### ISSUE TITLE
Rooms

### ISSUE THREAD

**Issue by FauthD** [Templarian/MaterialDesign#4293]
Rooms like kitchen. living room, dining room etc.
Would be nice for home assistant

**Comment by goyney** [comment]
Nice idea, but the idea of representing an entire room in a single, little icon is pretty hard. Have you considered using icons that represent something that is a staple of each room type? For example, `fridge` for kitchen or `silverware-fork-knife` for dining, etc? Contextually, these icons next to the word "Kitchen" or "Dining Room" fit perfectly.

**Comment by goyney** [comment]
We're going to close this because its just not feasible. I stick by my recommendation of using other icons that typically indicate the types of rooms you're trying to convey. Thanks for the suggestion!

**Comment by ciechompl** [comment]
@goyney I'm also missing good set of icons representing particular rooms in my house. I understand, that it is difficult to think about what exactly could represent specific room but maybe this set will inspire you :) [icons are from https://thenounproject.com/] I know .. different size, too detailed as for MDI etc. but I would love to have something similar in MDI set as I'm using this set as a base form all icons in my home automation system :) maybe someone will have an idea how to make in suitable for MDI 

- office: ![gabinet](https://user-images.githubusercontent.com/27088154/84196262-43f76f00-aaa0-11ea-8d1b-644ef2cff39a.png), 

- garage: ![garaz](https://user-images.githubusercontent.com/27088154/84196264-44900580-aaa0-11ea-8e97-951c306d9c6d.png)

- guest room ![gosinny_gora](https://user-images.githubusercontent.com/27088154/84196265-44900580-aaa0-11ea-8c65-eb1bd4d06565.png)

- corridor/hall ![korytarz](https://user-images.githubusercontent.com/27088154/84196269-45289c00-aaa0-11ea-8247-66b6462470d8.png)

-boiler room: ![kotlownia](https://user-images.githubusercontent.com/27088154/84196271-45289c00-aaa0-11ea-95fd-1cee4155d8d8.png)

- kitchen: ![kuchnia](https://user-images.githubusercontent.com/27088154/84196273-45c13280-aaa0-11ea-8188-c2c5b9a91496.png)

- toilet: ![lazienka_dol](https://user-images.githubusercontent.com/27088154/84196274-4659c900-aaa0-11ea-871a-e7faaa50b31e.png)

- bathroom: ![lazienka_dzieci](https://user-images.githubusercontent.com/27088154/84196275-4659c900-aaa0-11ea-959c-ea947eb5c00c.png)

- shower room: ![lazienka_rodzicow](https://user-images.githubusercontent.com/27088154/84196276-46f25f80-aaa0-11ea-91a6-500a1184aaf3.png)

- garen: ![ogrod](https://user-images.githubusercontent.com/27088154/84196277-46f25f80-aaa0-11ea-8ba0-e28d06810aed.png)

-front yard:  ![przed domem](https://user-images.githubusercontent.com/27088154/84196289-48bc2300-aaa0-11ea-9694-a97900fd03cd.png)

- wardrobe: ![przedpokoj](https://user-images.githubusercontent.com/27088154/84196292-48bc2300-aaa0-11ea-8591-6a92e4460775.png)

- TV/living room: ![salon](https://user-images.githubusercontent.com/27088154/84196294-4954b980-aaa0-11ea-9ed1-9561e8420ccb.png)

- attic: ![strych](https://user-images.githubusercontent.com/27088154/84196295-4954b980-aaa0-11ea-8aa4-a0cae3afc956.png)

- bedroom: ![sypialnia](https://user-images.githubusercontent.com/27088154/84196297-49ed5000-aaa0-11ea-994a-0ac360f5a8e1.png)

- terrace: ![taras](https://user-images.githubusercontent.com/27088154/84196303-4a85e680-aaa0-11ea-968c-20dc6b7e2004.png)

**Comment by goyney** [comment]
Most of those are too detailed or can already be represented by icons that exist in the pack.
