### ISSUE TITLE
beauty health icon

### ISSUE THREAD

**Issue by aminaghamiri** [Templarian/MaterialDesign#4295]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.
![50-501709_beauty-symbol-png-clipart png](https://user-images.githubusercontent.com/53684025/62420024-71fe6c80-b6a1-11e9-99fd-545bb4b98dfc.jpg)

**Comment by aminaghamiri** [comment]
Please add a beauty health icon to your free package.

**Comment by goyney** [comment]
What about `hair-dryer`?

[![hair-dryer](https://materialdesignicons.com/icon/hair-dryer)](https://materialdesignicons.com/icon/hair-dryer)[![hair-dryer-outline](https://materialdesignicons.com/icon/hair-dryer-outline)](https://materialdesignicons.com/icon/hair-dryer-outline)

**Comment by CoDEmanX** [comment]
I like the hair dryer idea. Could work well in the context of a web shop for instance.

Combining a face with something to signify _beauty_ will be difficult. Here is an example using `face-woman` and the "stars" from the `silver-clean` icon:

![grafik](https://user-images.githubusercontent.com/1309249/62860923-10be4500-bd02-11e9-8026-39eb51a2c6d6.png)

At default size, the larger star looks like flower or hair brooch and the small one like a random dot.

**Comment by PeterShaggyNoble** [comment]
The lotus flower, which we've included as `spa(-outline)` is frequently used to represent health & beauty.

[![spa](https://user-images.githubusercontent.com/15157491/63708041-477c7b00-c82b-11e9-8851-afc9565875fe.png)](https://materialdesignicons.com/icon/spa)[![spa-outline](https://user-images.githubusercontent.com/15157491/63708081-5f53ff00-c82b-11e9-8525-ce5e74b654d2.png)](https://materialdesignicons.com/icon/spa-outline)

**Comment by goyney** [comment]
Looks like there are several options here. If none of these fit your needs, feel free to comment back here and we'll reopen to reconsider any new examples you provide us. Thanks for your suggestion.
