### ISSUE TITLE
Command Post Icon

### ISSUE THREAD

**Issue by vorant94** [Templarian/MaterialDesign#4296]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon for indicating admin panel or command post section, where superusers can manage other users and so on

## Examples

![photo5924762666365202746](https://user-images.githubusercontent.com/9719319/62423894-c587af00-b6cf-11e9-94f0-51b7889c0267.jpg)

Include any example images so we know what the icon should look like.

**Comment by MrGrigri** [comment]
Would `monitor-dashboard` work?

![monitor-dashboard](https://materialdesignicons.com/icon/monitor-dashboard)

**Comment by CoDEmanX** [comment]
I think I would go with the `console` icon:

![grafik](https://user-images.githubusercontent.com/1309249/62493377-3a8edd80-b7d1-11e9-9f6b-bc05ce975e39.png)

**Comment by vorant94** [comment]
> Would `monitor-dashboard` work?
> 
> ![monitor-dashboard](https://camo.githubusercontent.com/05c49aeab22ecc05d4813af75ed6ddf5b642018e/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f6d6f6e69746f722d64617368626f617264)

Not really because I already have dashboard section and use this icon there

**Comment by vorant94** [comment]
> I think I would go with the `console` icon:
> 
> ![grafik](https://user-images.githubusercontent.com/1309249/62493377-3a8edd80-b7d1-11e9-9f6b-bc05ce975e39.png)

It is a bit confusing for the superusers since they are not necessary programmers, I think

**Comment by goyney** [comment]
I don't think you're going to be able to git multiple monitors in the small space we have to follow your example. Do you have any other ideas on how to convey this?

**Comment by MrGrigri** [comment]
This is as good as I believe it can get with the current MD Guidelines.

![image](https://user-images.githubusercontent.com/4528551/62552720-59ba5900-b82b-11e9-81ff-b8435e5b6cc7.png)

---
#### Files
[monitor-multiple-alternate.zip](https://github.com/Templarian/MaterialDesign/files/3472944/monitor-multiple-alternate.zip)

**Comment by goyney** [comment]
Meh.

**Comment by MrGrigri** [comment]
That was my thought. Not much of a fan.

**Comment by JamesCoyle** [comment]
Gonna close this out as I feel the alternatives provided cover this as best we can.
