### ISSUE TITLE
Are these icons open source like the original Material icons?

### ISSUE THREAD

**Issue by RuzeHiroma** [Templarian/MaterialDesign#4297]
I was just wondering what the use permissions were on these. I'm guessing that they are free to use like the original Material icons but I just want to confirm.

Thanks!

**Comment by MrGrigri** [comment]
Please refer to our [LICENCE](https://github.com/Templarian/MaterialDesign/blob/master/LICENSE) in the root of this repo.

**Comment by CoDEmanX** [comment]
There is also http://dev.materialdesignicons.com/license
