### ISSUE TITLE
Sport modalities

### ISSUE THREAD

**Issue by mfcarneiro** [Templarian/MaterialDesign#4299]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist. 

## Usage

I'm finishing a website that need to display some sport modalities that is missing for my use case.

Found some examples below:

## Examples

![Airsoft](https://user-images.githubusercontent.com/13247083/62484270-37273200-b790-11e9-9848-b44df4842c6d.png)
_Airsoft_

---
![Futevlei fw](https://user-images.githubusercontent.com/13247083/62484420-88cfbc80-b790-11e9-9380-daabf9c3be3a.png)
_Futevôlei (soccer variant/similar to beach volley)_

---
![Futsal fw](https://user-images.githubusercontent.com/13247083/62484421-88cfbc80-b790-11e9-9d57-cbd6845b9423.png)
_Futsal (soccer variant/five-a-side football)_

---
![Society fw](https://user-images.githubusercontent.com/13247083/62484426-8a00e980-b790-11e9-8cd0-e33bd0d57b02.png)
_Futebol society (soccer variant/artificial turf)_

---
![Paintball fw](https://user-images.githubusercontent.com/13247083/62484423-89685300-b790-11e9-933a-9c44d5f2cc74.png)
_Paintball_

---
![Pdel fw](https://user-images.githubusercontent.com/13247083/62484424-89685300-b790-11e9-9c62-e8242c23ee76.png)
_Padel_

---
![Skate fw](https://user-images.githubusercontent.com/13247083/62484425-89685300-b790-11e9-8477-e08a55ac0e85.png)
_Skate_

---
![Squash fw](https://user-images.githubusercontent.com/13247083/62484427-8a00e980-b790-11e9-8d35-d993c5491108.png)
_Squash_

---
![TnisPraia](https://user-images.githubusercontent.com/13247083/62484428-8a00e980-b790-11e9-9ce9-403eafd63434.png)
_Beach tennis_

---
![VleiPraia fw](https://user-images.githubusercontent.com/13247083/62484430-8a998000-b790-11e9-9416-bb76c46b7205.png)
_Beach volley_

**Comment by goyney** [comment]
We have a number of what you're asking for already:

- [x] Airsoft - `target`
- [x] Futevôlei - `soccer`
- [x] Futsal (soccer variant/five-a-side football) - `soccer`
- [x] Futebol society (soccer variant/artificial turf) - `soccer`
- [ ] Paintball - Also could use `target`
- [x] Padel - `tennis`
- [x] Skate - Will be added in #3800.
- [x] Squash - `racquetball`
- [x] Beach tennis - `tennis`
- [x] Beach volley - `volleryball`

I really don't see us adding a bunch of different variants of a soccer ball.

I could see us adding a "puddle" or "paint splotch" type icon that would satisfy the request for painball. I've opened an issue for that: #4313.

---

Also, please request only _one_ icon per request.

**Comment by mfcarneiro** [comment]
Alright, thank you.
