### ISSUE TITLE
Medical icons addition

### ISSUE THREAD

**Issue by yolapop** [Templarian/MaterialDesign#430]
So there's a few medical icons already https://github.com/Templarian/MaterialDesign/issues/15, but if you can, please add
- [x] Stethoscope http://fortawesome.github.io/Font-Awesome/icon/stethoscope
- [ ] Doctor http://fortawesome.github.io/Font-Awesome/icon/user-md
- [ ] Nurse
- [x] Heartbeat https://thenounproject.com/term/heartbeat/123231
- [ ] Insurance https://thenounproject.com/term/insurance/139828

Oh and also calendar related
- [ ] The date from 1 to 31 https://thenounproject.com/term/date/47373
- [ ] Day https://thenounproject.com/gianni_dolce/icon/66845

Thank you :smiley:

**Comment by yolapop** [comment]
@Templarian Is there any way you can prioritize icon request, maybe by donation?

**Comment by Templarian** [comment]
@yolapop Oh, uhh... nope. It is being worked on, but at this current time no. This is just a side project at the moment.

https://materialdesignicons.com/icon/pulse The heartbeat icon was added.

**Comment by yolapop** [comment]
That's alright, no big deal. I just like your icon collection very much
than others.
Thanks for making these!

**Comment by gmrash** [comment]
up

**Comment by CoDEmanX** [comment]
Stethoscope was added:
https://materialdesignicons.com/icon/stethoscope

**Comment by PeterShaggyNoble** [comment]
- `doctor` is tracked in #2245
- `nurse` is tracked in #2621
- From the examples in the link, `lifebuoy`, `security-home` or `umbrella`, among others, should cover insurance.
- `calendar` or `calendar-today` should suit `calendar-day`
- I don't think adding 31 new icons to cover all the days is viable, the better option is simply to overlay text on `calendar-blank`.
