### ISSUE TITLE
cellphone-message-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4301]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
id like to have a identifier in the frontend of my system (homeassistant) indicating wether my notifications are switched on/off.

## Examples

would be simply the current cellphone-message with the diagonal off-line

thanks for considering

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/62588410-7f228380-b87a-11e9-9b49-886930ba86d2.png)
[cellphone-message-off.svg](https://github.com/terreng/samples/blob/master/cellphone-message-off.svg)

**Comment by Mariusthvdb** [comment]
Yes! Cool. Thanks

**Comment by goyney** [comment]
[![cellphone-message-off](https://materialdesignicons.com/icon/cellphone-message-off)](https://materialdesignicons.com/icon/cellphone-message-off)
