### ISSUE TITLE
controller

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4302]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-controller](https://user-images.githubusercontent.com/53791292/62525364-94c28980-b837-11e9-8400-dc4255ee893f.png)

## Zip Download

[mdi-controller.zip](https://github.com/Templarian/MaterialDesign/files/3471200/mdi-controller.zip)

**Comment by goyney** [comment]
I'm not sure this is a "controller". It looks like our `locker`, tipped over. We also have several game controller variants.

Can you further elaborate on what this is supposed to visualize? I'm afraid it might be too niche for this library.

**Comment by kevin-hens** [comment]
Haha locker tipped over nice :p. And I already thought that it might be too niche. Let me explain. It's not supposed to be a controller like a gamepad or so. It's supposed to look like a PLC (Programmable Logic Controller). Kind of controller that can be found in industrial applications to run machines. Therefore I also have a download and upload to controller cause this is with any supplier of PLC a common function to download or upload data from a visualizing system to the actual controller from the machine. It's supposed to illustrate the attached picture. But like you say it might be too niche.

![image](https://user-images.githubusercontent.com/53791292/62608633-77a5bd80-b900-11e9-8883-9b35ba387988.png)

**Comment by PeterShaggyNoble** [comment]
I agree that this is too niche so I'm going to close it out, along with the 2 related issues.

Would our `server-*` icons fulfil your needs, as an alternative?
