### ISSUE TITLE
controller-download

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4303]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-controller-download](https://user-images.githubusercontent.com/53791292/62525493-cf2c2680-b837-11e9-88c8-2edd8bf0ae87.png)

## Zip Download

[mdi-controller-download.zip](https://github.com/Templarian/MaterialDesign/files/3471208/mdi-controller-download.zip)

**Comment by PeterShaggyNoble** [comment]
Closed as per #4302
