### ISSUE TITLE
controller-upload

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4304]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-controller-upload](https://user-images.githubusercontent.com/53791292/62525589-f71b8a00-b837-11e9-83fc-9053f699b368.png)

## Zip Download

[mdi-controller-upload.zip](https://github.com/Templarian/MaterialDesign/files/3471214/mdi-controller-upload.zip)

**Comment by PeterShaggyNoble** [comment]
Closing as per #4302 

Thanks for the contributions, though, @kevin-hens, hope to see more from you in the future.
