### ISSUE TITLE
television-clean

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4305]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-clean-screen](https://user-images.githubusercontent.com/53791292/62525660-11edfe80-b838-11e9-8f70-1cfa3ad0512a.png)

## Zip Download

[mdi-clean-screen.zip](https://github.com/Templarian/MaterialDesign/files/3471216/mdi-clean-screen.zip)

**Comment by goyney** [comment]
This needs to be updated to use our `monitor` as the base.

[![monitor](https://materialdesignicons.com/icon/monitor)](https://materialdesignicons.com/icon/monitor)

**Comment by goyney** [comment]
[![monitor-clean](https://materialdesignicons.com/icon/monitor-clean)](https://materialdesignicons.com/icon/monitor-clean)[![television-clean](https://materialdesignicons.com/icon/television-clean)](https://materialdesignicons.com/icon/television-clean)

**Comment by jeanie77** [comment]
Are these icons available with the current release of mdi (4.2.95)? If they will be relased only with the upcoming version (4.3.*), why are they displayed as search result on materialdesignicons.com?

**Comment by CoDEmanX** [comment]
They are not released yet. Not sure if they will be part of 4.3 or 4.4.

**Comment by jeanie77** [comment]
Probably a flag could indicate that the single icon is not released yet. But it's all clear now, thank you.
