### ISSUE TITLE
factory-variant

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4306]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-factory-variant](https://user-images.githubusercontent.com/53791292/62525702-28945580-b838-11e9-87f7-6ed3c3e7447c.png)

## Zip Download

[mdi-factory-variant.zip](https://github.com/Templarian/MaterialDesign/files/3471221/mdi-factory-variant.zip)

**Comment by goyney** [comment]
I'm not sure this adds any value over our already existing `factory`.

[![factory](https://materialdesignicons.com/icon/factory)](https://materialdesignicons.com/icon/factory)

**Comment by goyney** [comment]
Think we're going to stick with our current `factory`. Thanks for the suggestion!
