### ISSUE TITLE
file-document-edit-variant

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4307]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-file-document-edit-variant](https://user-images.githubusercontent.com/53791292/62525757-41047000-b838-11e9-9718-7322bd4dba93.png)

## Zip Download

[mdi-file-document-edit-variant.zip](https://github.com/Templarian/MaterialDesign/files/3471225/mdi-file-document-edit-variant.zip)

**Comment by goyney** [comment]
I am not a fan of us using out `edit` modifier in this fashion.

**Comment by goyney** [comment]
We don't wish to use the `edit` modifier like this, so we're going to reject this one. Sorry!

Thanks for the suggestion though! 😄
