### ISSUE TITLE
tag-variant

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4308]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-label-variant](https://user-images.githubusercontent.com/53791292/62525800-56799a00-b838-11e9-8c7c-bf3b76fd0ea3.png)

## Zip Download

[mdi-label-variant.zip](https://github.com/Templarian/MaterialDesign/files/3471230/mdi-label-variant.zip)

**Comment by JamesCoyle** [comment]
What is the usecase for this?

**Comment by kevin-hens** [comment]
I use it on my HMI displays to toggle display tag names from actual components (motors (M100), valves (XV205), sensors (PT460), ... ). Might be the same case as the controller I submitted, being too niche.

**Comment by kevin-hens** [comment]
> What is the usecase for this?

I use it on my HMI displays to toggle display tag names from actual components (motors (M100), valves (XV205), sensors (PT460), ... ). Might be the same case as the controller I submitted, being too niche.

**Comment by PeterShaggyNoble** [comment]
I don't see a use case for this that wouldn't be covered by our existing `tag-*` icons.

Again, though, we appreciate the efforts, @kevin-hens.
