### ISSUE TITLE
weather-rain

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4309]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-rain](https://user-images.githubusercontent.com/53791292/62525847-65604c80-b838-11e9-9fb4-a82e7269a2fc.png)

## Zip Download

[mdi-rain.zip](https://github.com/Templarian/MaterialDesign/files/3471233/mdi-rain.zip)

**Comment by goyney** [comment]
We have a couple icons that already indicate "rain" and follow the style of all the other weather icons, so we're going to reject this in favor of those. Thanks for your suggestion!
