### ISSUE TITLE
map route icon

### ISSUE THREAD

**Issue by codeator** [Templarian/MaterialDesign#431]
Similar to this

https://cdn0.iconfinder.com/data/icons/map-locations-and-tourism/512/35-512.png
https://cdn3.iconfinder.com/data/icons/map/500/way-512.png
https://cdn2.iconfinder.com/data/icons/travel-set-1/512/6-512.png
https://cdn3.iconfinder.com/data/icons/drone-business/512/route_points-512.png

**Comment by CoDEmanX** [comment]
There's the official google `directions` icon:
https://materialdesignicons.com/icon/directions

**Comment by codeator** [comment]
Too bad that is something completely different from what they got in google maps.

**Comment by CoDEmanX** [comment]
But it is what they use in Google maps?!

**Comment by codeator** [comment]
![2015-07-14 12 53 21](https://cloud.githubusercontent.com/assets/99560/8670648/615c68ec-2a27-11e5-8b0f-97c266cda0d1.png)

I mean this one.

**Comment by CoDEmanX** [comment]
Ah, that's Google My Maps, like a web-version of Google Earth to create custom maps. Haven't seen it before.

**Comment by CoDEmanX** [comment]
We now have this: https://materialdesignicons.com/icon/directions-fork

**Comment by codeator** [comment]
Cool! Thank you!

**Comment by GreenTurtwig** [comment]
Haha, nice you found this after two years. Hope it's still useful to you. :-P

**Comment by PeterShaggyNoble** [comment]
I came across this yesterday and thought it was the one to the left of `directions-fork`, that looks similar to `vector-polyline`, that you were after.

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/directions-fork)](https://materialdesignicons.com/icon/directions-fork)[![](https://materialdesignicons.com/icon/vector-polyline)](https://materialdesignicons.com/icon/vector-polyline)
