### ISSUE TITLE
spray-bottle-variant

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4310]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-spray-bottle-variant](https://user-images.githubusercontent.com/53791292/62525902-7f9a2a80-b838-11e9-86c3-b21e13e0c29d.png)

## Zip Download

[mdi-spray-bottle-variant.zip](https://github.com/Templarian/MaterialDesign/files/3471235/mdi-spray-bottle-variant.zip)

**Comment by goyney** [comment]
The spray of this icon is the bothersome portion. Can you try some other things. Take a look at some of our other icons that indicate a water spray, such as `shower` or `sprinkler`.

**Comment by JamesCoyle** [comment]
The shape seems a bit off to me. This is more the shape I think of:
![image](https://user-images.githubusercontent.com/10384436/62735791-eaf42000-ba23-11e9-8201-a479ab121865.png)

**Comment by goyney** [comment]
And that already matches our current `spray-bottle`.

[![spray-bottle](https://materialdesignicons.com/icon/spray-bottle)](https://materialdesignicons.com/icon/spray-bottle)

**Comment by goyney** [comment]
If all we need is the spray, we could make a `spray-bottle-spraying` (name?) variant. 🤔

**Comment by JamesCoyle** [comment]
Derp. Didn't realize we already had that... I don't really think we need anything other than that personally.

**Comment by goyney** [comment]
Going to close this since our `spray-bottle` should serve this use case.
