### ISSUE TITLE
clipboard-list-outline

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4311]
I started off a couple of years ago designing icons for my industrial HMI systems. I found out about this project just recently and decided to submit some of the icons that I designed myself.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![mdi-tasklist](https://user-images.githubusercontent.com/53791292/62525961-993b7200-b838-11e9-8e56-ec5196e0c34e.png)

## Zip Download

[mdi-tasklist.zip](https://github.com/Templarian/MaterialDesign/files/3471238/mdi-tasklist.zip)

**Comment by goyney** [comment]
It'd be nice to have the filled version of this as well.

**Comment by MrGrigri** [comment]
The only issue is it's not on-pixel. So it's blurry at 1x. Could this be refactored to be on-pixel?

**Comment by JamesCoyle** [comment]
Should be easy to align if it uses our icon as a base. 
[![](https://materialdesignicons.com/icon/clipboard-outline
)](https://materialdesignicons.com/icon/clipboard-outline)![image](https://user-images.githubusercontent.com/10384436/62552227-33191400-b865-11e9-939f-fdc3836388e5.png)

**Comment by goyney** [comment]
We'll add the aligned one as exhibited by @JamesCoyle.

**Comment by goyney** [comment]
[![clipboard-list](https://materialdesignicons.com/icon/clipboard-list)](https://materialdesignicons.com/icon/clipboard-list)[![clipboard-list-outline](https://materialdesignicons.com/icon/clipboard-list-outline)](https://materialdesignicons.com/icon/clipboard-list-outline)
