### ISSUE TITLE
Contribution FontForge template with grid (reverse engeneering original google mdi font)

### ISSUE THREAD

**Issue by kevin-hens** [Templarian/MaterialDesign#4312]
I don't know if this is of any value, but I started off a couple of years ago designing icons for my industrial HMI systems. When I started I first reversed engineered a grid in FontForge where I design my Icons now. This grid is entirely based on the original font Google provided.
I prefer working in FontForge as on my HMI systems I use a font file to keep all my icons in one place and be able to color them accordingly in my HMI graphical designer.

The file also includes 160 "template slots" where I've already foreseen standard sizes that I took from the original Google font.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![001 Templates](https://user-images.githubusercontent.com/53791292/62526059-cbe56a80-b838-11e9-947b-c0780bda79bf.png)
![002 Grid](https://user-images.githubusercontent.com/53791292/62526062-cdaf2e00-b838-11e9-860a-790e2a8850e3.png)

## Zip Download

[MatterialIcons-Regular.zip](https://github.com/Templarian/MaterialDesign/files/3471247/MatterialIcons-Regular.zip)

**Comment by PeterShaggyNoble** [comment]
I've read through this a few times and it's unclear to me what you're requesting, suggesting or looking for - could you please clarify?

**Comment by Templarian** [comment]
Font Forge is more tailored for fonts and is great for it, but we don't use any font features for the icon pack. You may be interested in the now Open Source `@mdi/font-build` package that we use to generate `@mdi/font`. We get icons from pretty much ever editor out there as long as it can output an SVG file.

Be sure to share any icons you create that the community may find helpful. We're always looking for designers to help out.
