### ISSUE TITLE
Wrong font name on @mdi/font 3.9.95

### ISSUE THREAD

**Issue by LuisAngelMoralesRomo** [Templarian/MaterialDesign#4314]
The file `@mdi\font\fonts\materialdesignicons-webfont.ttf` on the npm version `3.9.95` has `my-font-name`  as font name, instead of `Material Design Icons` as the npm version `3.8.95`.

![image](https://user-images.githubusercontent.com/15383945/62567345-9ea4b680-b850-11e9-9198-857fc452e99b.png)

**Comment by LuisAngelMoralesRomo** [comment]
This is the file with the typo:
https://github.com/Templarian/MaterialDesign-Font-Build/blob/70149b4b82437d695080d98360a408c6bfec00f2/bin/index.js#L238

And was introduced in this commit:
Templarian/MaterialDesign-Font-Build@c857675

**Comment by LuisAngelMoralesRomo** [comment]
I created the issue here because it is the repository referenced from the `@mdi/font` npm package.
Should I create an issue on https://github.com/Templarian/MaterialDesign-Webfont 
and https://github.com/Templarian/MaterialDesign-Font-Build too?

**Comment by Templarian** [comment]
Completely forgot to fix this before re-export. Need to republish for v3.9.96.

Unpublished 3.9.95 for now. Annoyingly this was reported by one of the core members yesterday and had been fixed, but I was publishing rom an old folder.

**Comment by Templarian** [comment]
`@mdi/font-build` v1.3.0 was just published. This has the font name fix in the tooling that will be used in tonight's release.

**Comment by LuisAngelMoralesRomo** [comment]
That was quick! Thanks!

**Comment by Templarian** [comment]
@LuisAngelMoralesRomo We've published `3.9.96`. Hopefully this resolves the issue you were seeing.

Thanks again for opening this bug!

**Comment by LuisAngelMoralesRomo** [comment]
Working as expected, thank you!

BTW, I had a little bit of trouble with the change of the css selectors from `:before` to `::before`. Mostly realizing the change in the selector, and realizing that  https://github.com/NathanWalker/nativescript-ngx-fonticon does not recognize the double-colon selector.

It would be a good idea to add this change to the changelog.

Should I open another issue?

**Comment by goyney** [comment]
[We made this change intentionally.](https://github.com/Templarian/MaterialDesign/issues/1997)

The [changelog](https://dev.materialdesignicons.com/changelog) hasn't been updated for `3.9.95` yet, but it definitely will include this change.

No need for another issue.

**Comment by Templarian** [comment]
Updated this in the docs for `3.9.97`.

That library will have to update to support `::` as we're moving away from the legacy selector and supporting IE9+ going forward.

**Comment by LuisAngelMoralesRomo** [comment]
Thanks again for the quick response and the suggestion, I already made a pull request to support `::` on https://github.com/NathanWalker/nativescript-ngx-fonticon .
