### ISSUE TITLE
Traffic icons

### ISSUE THREAD

**Issue by magtimmermans** [Templarian/MaterialDesign#4315]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
> Usage
> Provide some context of how your icon could be used.

> Examples
> Include any example images so we know what the icon should look like.

What are you requesting? We have tons of icons around [road transportation](https://materialdesignicons.com/tag/transportation-road) already.

**Comment by magtimmermans** [comment]
I have attached samples. Tons??? You mean a few :)

![ic_pin_incident](https://user-images.githubusercontent.com/17949840/62722982-e7ef3480-ba0f-11e9-85ec-c5d28eb334e0.png)
![ic_pin_police](https://user-images.githubusercontent.com/17949840/62722996-efaed900-ba0f-11e9-8fbd-de39c3be2dd8.png)
![ic_pin_redlight](https://user-images.githubusercontent.com/17949840/62723003-f50c2380-ba0f-11e9-9aa0-0211458fb3db.png)
![ic_pin_schoolzone](https://user-images.githubusercontent.com/17949840/62723017-fe958b80-ba0f-11e9-9291-b3948c955ab4.png)
![ic_pin_traffic](https://user-images.githubusercontent.com/17949840/62723028-035a3f80-ba10-11e9-8ea4-dd62851dbb0e.png)
![ic_pin_speedcam](https://user-images.githubusercontent.com/17949840/62723038-081ef380-ba10-11e9-8789-c7c0aebf5d1c.png)

**Comment by goyney** [comment]
> Searched the current library to make sure the icon doesn't exist.

We have many of those, `traffic-light`, `car-multiple`, `minus-circle`, several cameras, etc.

---

> Only requested a single icon (or a few near-identical ones) in this issue.

Large issues with many different requests are hard to manage and track. Please narrow down the icons you need and request a single one per issue. Thanks!

**Comment by magtimmermans** [comment]
The only one that I missed is a car and the minus-circle. The traffic camera's you do not have (only normal camera's) Redlight traffic light Also not. The rest also not and your just closing the case :(

**Comment by goyney** [comment]
If there are specific icons you would like to see added, please create a single issue for a single icon request.
