### ISSUE TITLE
Tonic Bottles

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4316]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

---

## Description

I got the ideas for these off a billboard while driving home the other day. Not sure if the skull one works at native size.

## Preview

![image](https://user-images.githubusercontent.com/1015040/62734695-9d61be00-b9f7-11e9-8ddc-28ead90eaabf.png)
![image](https://user-images.githubusercontent.com/1015040/62734708-a3f03580-b9f7-11e9-8809-f86ecb963c9a.png)
![image](https://user-images.githubusercontent.com/1015040/62734722-ac487080-b9f7-11e9-919e-c083236ef922.png)
![image](https://user-images.githubusercontent.com/1015040/62734730-b36f7e80-b9f7-11e9-80bd-2d1d4bfe6a70.png)
![image](https://user-images.githubusercontent.com/1015040/62734745-bc605000-b9f7-11e9-940a-415dd2e8f6d6.png)
![image](https://user-images.githubusercontent.com/1015040/62734762-c4b88b00-b9f7-11e9-9a67-1b2a33011975.png)

## Zip Download

[tonic-bottle.zip](https://github.com/Templarian/MaterialDesign/files/3483503/tonic-bottle.zip)

**Comment by MrGrigri** [comment]
We should alias the poison ones as moonshine

**Comment by MrGrigri** [comment]
I would remove the teeth cutouts

**Comment by Templarian** [comment]
The teeth cut outs are what make it look like a skull.

**Comment by CoDEmanX** [comment]
The skull in `tonic-bottle-poison-outline` is very blurry 😕

**Comment by MrGrigri** [comment]
What about a Saint Andrew's cross instead of a skull.

**Comment by goyney** [comment]
Trying to make the skulls less blurry, think it works better with these:
![image](https://user-images.githubusercontent.com/1015040/62828529-df852e00-bbb6-11e9-8b82-801fd3553e6a.png)
![image](https://user-images.githubusercontent.com/1015040/62828530-e6ac3c00-bbb6-11e9-85a5-d57e3220dd3b.png)

**Comment by MrGrigri** [comment]
I was thinking more like this. 

![image](https://user-images.githubusercontent.com/4528551/62873854-587ea580-bcdd-11e9-989b-fbce9c66dc59.png) ![image](https://user-images.githubusercontent.com/4528551/62873900-70eec000-bcdd-11e9-886d-8403423b1d1c.png)


---
#### Files

[tonic-bottle.zip](https://github.com/Templarian/MaterialDesign/files/3493023/tonic-bottle.zip)

**Comment by goyney** [comment]
Yeah, those are much simpler, can represent poison, alcohol, etc.

**Comment by goyney** [comment]
[![bottle-tonic](https://materialdesignicons.com/icon/bottle-tonic)](https://materialdesignicons.com/icon/bottle-tonic)[![bottle-tonic-outline](https://materialdesignicons.com/icon/bottle-tonic-outline)](https://materialdesignicons.com/icon/bottle-tonic-outline)
[![bottle-tonic-plus](https://materialdesignicons.com/icon/bottle-tonic-plus)](https://materialdesignicons.com/icon/bottle-tonic-plus)[![bottle-tonic-plus-outline](https://materialdesignicons.com/icon/bottle-tonic-plus-outline)](https://materialdesignicons.com/icon/bottle-tonic-plus-outline)
[![bottle-tonic-skull](https://materialdesignicons.com/icon/bottle-tonic-skull)](https://materialdesignicons.com/icon/bottle-tonic-skull)[![bottle-tonic-skull-outline](https://materialdesignicons.com/icon/bottle-tonic-skull-outline)](https://materialdesignicons.com/icon/bottle-tonic-skull-outline)
