### ISSUE TITLE
Icon "tanker-truck" not included into v3.9.97

### ISSUE THREAD

**Issue by aprotsyk** [Templarian/MaterialDesign#4318]

**Comment by Templarian** [comment]
@aprotsyk That icon is going out in the `4.0.96` release. The preview for that is on the CDN now: https://cdn.materialdesignicons.com/4.0.96/

We just did the release for `3.9.97` yesterday. This should be out next week. Usually we don't have releases this close, but we're in the process of open sourcing our tooling chain, so we had 3 releases ready at the same time (`4.1.95` will be out the following week).

**Comment by aprotsyk** [comment]
@Templarian really appreciated for the answer
