### ISSUE TITLE
Qualify and disqualify icon

### ISSUE THREAD

**Issue by sumeetgupta123** [Templarian/MaterialDesign#4319]
I have:

- [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.

## Usage

These icons will be used to qualify and disqualify user in our project

## Examples

Includeing examples images to know what the icon should look like.

[icons.zip](https://github.com/Templarian/MaterialDesign/files/3484855/icons.zip)
![group-30-copy@2x](https://user-images.githubusercontent.com/19700390/62755727-ce430100-ba92-11e9-8405-84852e9593c3.png)
![group-31-copy@2x](https://user-images.githubusercontent.com/19700390/62755745-dac75980-ba92-11e9-84d7-193c5a6bbbab.png)

**Comment by CoDEmanX** [comment]
I don't understand these weird circles. Anyway, we also have the following icons, which are very similar:

![grafik](https://user-images.githubusercontent.com/1309249/62806523-62dd4b80-baf3-11e9-979a-e320becb3b10.png) ![grafik](https://user-images.githubusercontent.com/1309249/62806511-5658f300-baf3-11e9-80a2-52d9267aa1d5.png)

![grafik](https://user-images.githubusercontent.com/1309249/62806421-142fb180-baf3-11e9-9653-98623506e779.png)

There is no circle-outline with an overlapping X, but I'm not sure if I would want to add one:

![grafik](https://user-images.githubusercontent.com/1309249/62806805-134b4f80-baf4-11e9-8ef2-aed7bc56cfec.png) ![grafik](https://user-images.githubusercontent.com/1309249/62806874-3e35a380-baf4-11e9-8a4c-bcfe4952e04f.png)

I can rather see a strikethrough version work:

![grafik](https://user-images.githubusercontent.com/1309249/62807202-1266ed80-baf5-11e9-97d9-965a514adb41.png)

**Comment by goyney** [comment]
We also have `progress-check`, which is similar in the circle.

![progress-check(https://materialdesignicons.com/icon/progress-check)](https://materialdesignicons.com/icon/progress-check)

We can add `progress-close` to match.
![image](https://user-images.githubusercontent.com/1015040/62815876-0840f100-baed-11e9-8e05-72550013ad65.png)
[progress-close.svg.zip](https://github.com/Templarian/MaterialDesign/files/3488395/progress-close.svg.zip)

**Comment by goyney** [comment]
[![circle-off-outline](https://materialdesignicons.com/icon/circle-off-outline)](https://materialdesignicons.com/icon/circle-off-outline)
[![progress-close](https://materialdesignicons.com/icon/progress-close)](https://materialdesignicons.com/icon/progress-close)
