### ISSUE TITLE
Scanner icon

### ISSUE THREAD

**Issue by Tom65380** [Templarian/MaterialDesign#432]
Hi! I suggest to add an image scanner icon like this one:
![](http://icons.iconarchive.com/icons/custom-icon-design/mono-business-2/128/scanner-icon.png)

**Comment by CoDEmanX** [comment]
There's one by Google:
https://www.google.com/design/icons/#ic_scanner

**Comment by Templarian** [comment]
[![scanner](https://materialdesignicons.com/icon/scanner)](https://materialdesignicons.com/icon/scanner)
