### ISSUE TITLE
Add icon: folder loading

### ISSUE THREAD

**Issue by MCwither** [Templarian/MaterialDesign#4320]
I want to add a icon: `folder is loading` 
You can also add outline's copy
Please!

**Comment by MrGrigri** [comment]
Would [`folder-clock`](https://materialdesignicons.com/icon/folder-clock) or  [`folder-sync`](https://materialdesignicons.com/icon/folder-sync) not work for this situation? If not, how do you suggest we design this icon? Please provide examples.

![folder-clock](https://materialdesignicons.com/icon/folder-clock) ![folder-sync](https://materialdesignicons.com/icon/folder-sync)

**Comment by MrGrigri** [comment]
> You can also add outline's copy

Idk what you mean by this. Also, we only track one icon per issue. If this is another request, please open a new issue.

**Comment by goyney** [comment]
`folder-sync` should be fairly sufficient for this use case.

**Comment by MCwither** [comment]
yes, thank you. @MrGrigri
