### ISSUE TITLE
earth-box-off and earth-off have the slash going the wrong way

### ISSUE THREAD

**Issue by vcantu** [Templarian/MaterialDesign#4321]
This is a minor bug but the earth-off and earth-box-off icons have the slash going the opposite of the standard way
![Screen Shot 2019-08-09 at 11 00 28 AM](https://user-images.githubusercontent.com/13156162/62788455-eddb2900-ba94-11e9-8611-1b821c1d97cc.png)

**Comment by MrGrigri** [comment]
This is not a bug. It is intended to go that way because of the direction North and South America connect. If it were to go the other direction, it wouldn't be recognizable.

**Comment by CoDEmanX** [comment]
... and mirroring the continents is obviously not an option here.
