### ISSUE TITLE
Update in plantuml-stdlib, request to tag version

### ISSUE THREAD

**Issue by Potherca** [Templarian/MaterialDesign#4323]
Hi! I'm in the process of opening MRs to update `*.puml` files in `plantuml-stdlib`, but since there is no versioning available in this repo, it's not something I can easily automate.

Would it be possible to add git tags to this project?

**Comment by goyney** [comment]
The code contains in the repository is not the actual released code. It serves as a place where some of our design files are in (in the future) the source SVG files. These files are used by internal processes to generate a variety of packages, including `@mdi/svg`, `@mdi/js`, and `@mdi/font`.

I quickly glanced at the library you are referencing, but I have no clue what a `*.puml` file is. I would recommend using one of our official releases (likely `@mdi/svg`), which is released on NPM and is versioned.

**Comment by Templarian** [comment]
`@mdi/svg` is hosted in https://github.com/Templarian/MaterialDesign-SVG

**Comment by Potherca** [comment]
@goyney the `puml` where probably originally converted from SVG files in this repo.
(At least, this repo was linked to from the PlanUML Standard Library)

I'll switch the URL in planuml-stdlib over to https://github.com/Templarian/MaterialDesign-SVG and use the versioning from there.

Thanks for the response! :+1:
