### ISSUE TITLE
Rename icons which don't starting with noun of predominant shape?

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4325]
`account-*` icons have the silhouette of a person as predominant shape and thus start with the noun _account_. However, some icons are not named correctly following this concept, e.g. `account-badge` whose predominant shape is the badge and not the person silhouette:

![grafik](https://user-images.githubusercontent.com/1309249/62898739-848a3d00-bd56-11e9-91e4-17d0d3cefe00.png)

`account` is the secondary shape in this case. I wouldn't consider it a modifier though, as it is placed in different location and sizes in other composite icons.

Here is a list of icons that we may want to rename for v5.0 for a consistent naming:

- [x] `account-badge` → `badge-account`
- [x] `account-badge-alert` → `badge-account-alert`
- [x] `account-badge-alert-outline` → `badge-account-alert-outline`
- [x] `account-badge-outline` → `badge-account-outline`
- [x] `account-badge-horizontal-outline` → `badge-account-horizontal`
- [x] `account-badge-horizontal-outline` → `badge-account-horizontal-outline`
- [x] `account-card-details` → `card-account-details` ❓
- [x] `account-card-details-outline` → `card-account-details-outline` ❓

(not exhaustive)

Also see #4324

**Comment by goyney** [comment]
I've addressed the ones in the initial post, but since this list is not exhaustive, someone should continue the audit. :)

*points at @CoDEmanX*

**Comment by Templarian** [comment]
Looks like we've handled a lot of these. Closing but feel free to open another issue if others are found.
