### ISSUE TITLE
symbol of mercury

### ISSUE THREAD

**Issue by JungComdok** [Templarian/MaterialDesign#4326]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Astronomical symbol of mercury &#9791;
It is used as gender symbol of the third gender.

## Examples

![symbol of mercury](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Mercury_symbol.svg/180px-Mercury_symbol.svg.png)

**Comment by CoDEmanX** [comment]
Would `gender-male-female` work? 

![grafik](https://user-images.githubusercontent.com/1309249/62944543-33715c00-bddd-11e9-9051-72053b8f996f.png)

If not, we could add this:

![grafik](https://user-images.githubusercontent.com/1309249/62944475-12a90680-bddd-11e9-8f12-c44b70544f90.png)

[gender-mercury.zip](https://github.com/Templarian/MaterialDesign/files/3497057/gender-mercury.zip)

**Comment by JungComdok** [comment]
`gender-mercury` is perfect.

For me personally would `gender-male-female` work and we use it currently.
But we need to change it to the requested symbol. It is used in germany as a symbol for intersex people.

**Comment by goyney** [comment]
[![gender-male-female-variant](https://materialdesignicons.com/icon/gender-male-female-variant)](https://materialdesignicons.com/icon/gender-male-female-variant)
[![gender-non-binary](https://materialdesignicons.com/icon/gender-non-binary)](https://materialdesignicons.com/icon/gender-non-binary)
