### ISSUE TITLE
Andela

### ISSUE THREAD

**Issue by evergreen2001** [Templarian/MaterialDesign#4327]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

![download](https://user-images.githubusercontent.com/39932962/62942088-6dfed880-bd8c-11e9-8937-e814499862e8.jpg)

**Comment by CoDEmanX** [comment]
> Andela builds distributed engineering teams with Africa’s top software engineers. We handle talent assessment, onboarding, and continuous improvement. You get back to building.

Not really a social network, rather a company / brand. We don't accept brand icons anymore.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
