### ISSUE TITLE
Call Log Icon

### ISSUE THREAD

**Issue by chrisonline** [Templarian/MaterialDesign#433]
Can you please add a Call Log Icon ..

Something like this:
https://lh3.ggpht.com/bTX_xpU70L3VUG3B4hBsznE2nGDSQ9OZwKLQYgoSQyVBtZXyhglJr6Jv61vasTlcoZo=w300-rw

**Comment by CoDEmanX** [comment]
This is how it looks like:

![unnamed](https://cloud.githubusercontent.com/assets/1309249/8663886/bbd1f6e0-29d0-11e5-9d6a-6c0f0a96807e.png)

**Comment by CoDEmanX** [comment]
I first tried something very similar:
![phone_call_log_design](https://cloud.githubusercontent.com/assets/1309249/8664486/184dea58-29d8-11e5-8a4f-5a992139233c.png)
but either the 2dp margin is violated or one of the arrows is getting too close to the handset.

Thus, I made the arrows smaller:
![phone_call_log](https://cloud.githubusercontent.com/assets/1309249/8664501/472a696e-29d8-11e5-8ad6-4e01a2f0d63b.png) https://www.dropbox.com/s/svrtttk3wbtnwtb/phone_call_log.svg?dl=0
The minimum distance is actually 1.41 between the arrows, but I think it's not too bad.

What worries me more is that they are not very legible in both versions at a resolution of 24x24 px

An alternative approach could be to actually depict "log":

![phone_call_log_variant](https://cloud.githubusercontent.com/assets/1309249/8664692/ea73dd42-29da-11e5-8fe5-b38a06fa9f6d.png) ![phone_call_log_variant2](https://cloud.githubusercontent.com/assets/1309249/8664694/ea741302-29da-11e5-8561-fda232e9d2f0.png) ![phone_call_log_variant3](https://cloud.githubusercontent.com/assets/1309249/8664693/ea740a42-29da-11e5-8b2f-12748fc92254.png)

@Templarian: would like to hear your opinion on such composite icons.

**Comment by Templarian** [comment]
Can you export them at 24x24 instead of 48x48 when you attach them. It's hard to tell how they will look scaled down.

I know it's difficult, but every icon has to be recognizable at the base size.

**Comment by CoDEmanX** [comment]
Sure. BTW: if you click the Dropbox links, there will be a preview in native size.
The call log icons aren't very legible at 24x24 to be honest. Maybe the arrows can be fine tuned, but the stroke width and spacing of 2px need to be sacrificed I'm afraid (I wouldn't move the handset, it's the same position in all Google icons).

**Comment by chrisonline** [comment]
I like the second icon in the alternative approach line. Very good!

**Comment by CoDEmanX** [comment]
24x24 pixels preview:

![phone_call_log_design](https://cloud.githubusercontent.com/assets/1309249/8747825/8baf8f40-2c96-11e5-9876-535a782012c6.png)
![phone_call_log](https://cloud.githubusercontent.com/assets/1309249/8744878/f2793c88-2c7a-11e5-93e2-5f8135b30739.png)
![phone_call_log_variant](https://cloud.githubusercontent.com/assets/1309249/8744879/f29e5482-2c7a-11e5-9d1e-5c5c3e2544f7.png)
![phone_call_log_variant2](https://cloud.githubusercontent.com/assets/1309249/8744880/f29ebaee-2c7a-11e5-9a28-ebddf74b4825.png)
![phone_call_log_variant3](https://cloud.githubusercontent.com/assets/1309249/8744881/f2a1cebe-2c7a-11e5-998a-a3df5cccec20.png)

New tries (I don't like them):
![phone_call_log_variant4](https://cloud.githubusercontent.com/assets/1309249/8748169/0d36501a-2c99-11e5-80a5-28a0b31d2c09.png)
![phone_call_log_variant5](https://cloud.githubusercontent.com/assets/1309249/8748170/0d4f4390-2c99-11e5-8294-d192ff5367b7.png)
![phone_call_log_variant6](https://cloud.githubusercontent.com/assets/1309249/8748171/0d786b6c-2c99-11e5-9961-c720e0781304.png)

**Comment by chrisonline** [comment]
Great work. The 24x24 is really good.
The first and 4th are my favorites.

**Comment by CoDEmanX** [comment]
The 4th is my favorite, 1st is also good but a little unbalanced (which I tried to fix in 2nd, but the arrows get too small for screens with regular density at 24px).

Yet another:
![phone_call_log_variant7](https://cloud.githubusercontent.com/assets/1309249/8847043/9fdd71be-312b-11e5-95e9-a1be6e4805dd.png) https://www.dropbox.com/s/kcq4v1eo8qpcomy/phone_call_log_variant7.svg?dl=0

@Templarian: any opinion / favorite?

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/phone-log

4th looked the closest to a log or list of calls.

**Comment by CoDEmanX** [comment]
Spacing is a little odd in the modified version you uploaded, it doesn't respect the top and right boundaries as seen in Google's call icons. The increased padding between the "rows" breaks the connection between them, because of the little space left to the handset...

**Comment by CoDEmanX** [comment]
With no margin to the top and right side, it would look like this:

![phone-log2](https://cloud.githubusercontent.com/assets/1309249/9027002/027e98e6-3944-11e5-87ce-8c520c452536.png)

**Comment by CoDEmanX** [comment]
In the current version, the log strokes look incoherent due to the 2px spacing. Therefore, I'd like to request an update to the icon with 2px stroke width, but 1px margin:

![phone-log](https://cloud.githubusercontent.com/assets/1309249/12405823/b2095eb2-be47-11e5-8887-48e451d907c0.png) https://www.dropbox.com/s/sik64sx5tlkbmsf/phone-log.svg?dl=0

It's legible, top and right-hand side of the "log" part align with the handset and it has an overall "cleaner" appearance IMO.

I hope the update also gets rid of extraneous points, all top-left corner points in the log part seem to exist twice if I download the compressed SVG from the page. The repository version seems fine though.

**Comment by CoDEmanX** [comment]
@Templarian: apparently the same issue (extra points in InkScape) like we had in #1106.
And please update the icon :smiley:

**Comment by CoDEmanX** [comment]
There is a duplicate point:

![image](https://user-images.githubusercontent.com/1309249/38422473-2b598464-39ab-11e8-9d03-f3a5c481eded.png)

Otherwise the issue can be closed.

**Comment by PeterShaggyNoble** [comment]
Does the duplicate point still need to be fixed?

**Comment by goyney** [comment]
It wasn't a duplicate point issue, it is an artifact from the optimizer. There are two points at that one spot because they are not joined. There are tons of icons in the library that have the same behavior.

**Comment by CoDEmanX** [comment]
I guess so. In fact, many icons have duplicate verts, or rather one superfluous vertex... maybe it's something with the processing pipeline? But it doesn't affect all icons alike 🤔
