### ISSUE TITLE
Outlined dice icons

### ISSUE THREAD

**Issue by LuckyLuke19** [Templarian/MaterialDesign#4330]
Create outlined variants for dice icons (dice-multiple, dice-1, dice-2, dice-3, dice-4, dice-5, dice-6).

**Comment by goyney** [comment]
- [ ] Add `dice-(1-6)-outline`
- [ ] Add `dice-multiple-outline`
- [ ] Rename `dice-d(4|6|8|10|12|20)` to have `-outline` suffix
- [ ] Add `dice-d(4|6|8|10|12|20)`

---

[dice.zip](https://github.com/Templarian/MaterialDesign/files/3502690/dice.zip)

---

![image](https://user-images.githubusercontent.com/1015040/63044985-64b16100-be9d-11e9-835f-cc16c59a5fd0.png)
![image](https://user-images.githubusercontent.com/1015040/63044992-6d099c00-be9d-11e9-9972-c1ae0b194566.png)
![image](https://user-images.githubusercontent.com/1015040/63045009-74c94080-be9d-11e9-9ff4-d8a4b7691355.png)
![image](https://user-images.githubusercontent.com/1015040/63045026-7bf04e80-be9d-11e9-98d3-70b3588102c6.png)
![image](https://user-images.githubusercontent.com/1015040/63045043-83aff300-be9d-11e9-99b5-687eb541250e.png)
![image](https://user-images.githubusercontent.com/1015040/63045053-8a3e6a80-be9d-11e9-9d14-5b9873858b85.png)
![image](https://user-images.githubusercontent.com/1015040/63045130-b6f28200-be9d-11e9-912c-758f693a75f1.png)
![image](https://user-images.githubusercontent.com/1015040/63045168-ceca0600-be9d-11e9-934b-2b185ad7ea8a.png)
![image](https://user-images.githubusercontent.com/1015040/63045181-d4275080-be9d-11e9-95c9-4623adc175ea.png)
![image](https://user-images.githubusercontent.com/1015040/63045194-dab5c800-be9d-11e9-9137-d2ff40025b49.png)
![image](https://user-images.githubusercontent.com/1015040/63045206-e1443f80-be9d-11e9-917e-97bedd8c3255.png)
![image](https://user-images.githubusercontent.com/1015040/63045216-e6a18a00-be9d-11e9-95f6-678cf68cc24c.png)
![image](https://user-images.githubusercontent.com/1015040/63045230-ed300180-be9d-11e9-926f-108d1e81a019.png)

**Comment by goyney** [comment]
We may also consider updating the `d(#)` to use our font? Example:
![image](https://user-images.githubusercontent.com/1015040/63045800-1a30e400-be9f-11e9-980f-be6d17965c48.png)
![image](https://user-images.githubusercontent.com/1015040/63045813-2026c500-be9f-11e9-8468-d440641e0176.png)

**Comment by MrGrigri** [comment]
It kind of sucks that the `dice-multiple-outline` is too small to have the numbers add up to 7. That's what I did with `dice-multiple`

**Comment by goyney** [comment]
All added. No dice on using our font, didn't work for half of them in the outlined form.
