### ISSUE TITLE
A magazine icon

### ISSUE THREAD

**Issue by rockthrower69** [Templarian/MaterialDesign#4331]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For subscriptions on magazines/journals 

## Examples

https://cdn2.iconfinder.com/data/icons/modern-business-advertising-and-media-1/48/Modern_Business_magazine_ads-512.png
https://image.flaticon.com/icons/svg/652/652932.svg

**Comment by PeterShaggyNoble** [comment]
Would any of the existing `book-*` or `book-open-*` icons suit your needs?

**Comment by rockthrower69** [comment]
They are good alternatives, but it is still different than a magazine/newspaper kinda thing.

**Comment by goyney** [comment]
We have plenty of icons that indicate a spined reading apparatus already. Any of those should work with the proper context.
