### ISSUE TITLE
_extras.scss variable names were reverted to being less specific in 3.9.95

### ISSUE THREAD

**Issue by ctyler-liquidfish** [Templarian/MaterialDesign#4332]
Hi,
I tracked down an issue I was having to a change you made at tag 3.9.95. In the webfont _extras.scss file, you define several variables; sizes, degrees, etc.

[This commit on Feb 19, 2018](https://github.com/Templarian/MaterialDesign-Webfont/commit/31ea782ab75a528350d6a350a722ddade6d16596#diff-dde4a3ede9ecb8fd275ea5a53cbf52d2) added an "mdi-" prefix to the variable names, but [this commit several days ago](https://github.com/Templarian/MaterialDesign-Webfont/commit/ae59791d8cfd319e8ec2a6f9dc8b6137e3dab225#diff-dde4a3ede9ecb8fd275ea5a53cbf52d2) removed the prefixes.

I'm using the MDI font with the Bulma framework, and this change broke my code. Both frameworks use a $sizes variable now.

Could you put the prefix back? Any plans for that?

**Comment by Templarian** [comment]
That's definitely a bug. It will be fixed in the 4.1.xx update this weekend.

https://github.com/Templarian/MaterialDesign-Font-Build is now open source since 3.9.xx

**Comment by Templarian** [comment]
This has been updated in `1.4.0` in `@mdi/font-build` which will generate `4.1.95`. 😃 

Doing several more updates so `4.1.95` will probably use `1.5` with some other updates.
