### ISSUE TITLE
Waveform Icon

### ISSUE THREAD

**Issue by jake-armour** [Templarian/MaterialDesign#4333]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Could be used to indicate audio usage, nothing like this currently exists and the existing audio icons don't fit the use case

## Examples

![wf](https://user-images.githubusercontent.com/32387986/63172695-3450fa80-c036-11e9-852d-abb9b3894d3e.png)

**Comment by JapanYoshi** [comment]
Why would volume-high, cellphone-sound, microphone, or music-note not work?

**Comment by half2me** [comment]
@JapanYoshi none of those icons look anything like this one. Its not about "working" or not "working", if you need an icon for an audio editing app for example, this would fit the case perfectly, while the other icons you mentioned, wouldn't "work"...

**Comment by goyney** [comment]
Would `google-podcast` work?

[![google-podcast](https://materialdesignicons.com/icon/google-podcast)](https://materialdesignicons.com/icon/google-podcast)

**Comment by goyney** [comment]
This will be covered in #4346, if `google-podcast` doesn't fit the use case.
