### ISSUE TITLE
Waterdrop icon

### ISSUE THREAD

**Issue by RandyPJ** [Templarian/MaterialDesign#4335]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by JamesCoyle** [comment]
Please search before requesting:
[![](https://materialdesignicons.com/icon/water)](https://materialdesignicons.com/icon/water)

**Comment by Templarian** [comment]
Added the aliases `water-drop` and `water-drop-outline`.
