### ISSUE TITLE
Rename coins => circle-multiple, add variants

### ISSUE THREAD

**Issue by LuckyLuke19** [Templarian/MaterialDesign#4336]
## Usage

Add a filled variant for the coin icon.

**Comment by goyney** [comment]
We will need to rename `coin` => `coin-outline` and `coins` => `coins-outline` and create the filled versions in this issue.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/63228682-95520d00-c1b3-11e9-996b-817fc6aedc04.png)

---

#### Files

[coin.zip](https://github.com/Templarian/MaterialDesign/files/3513411/coin.zip)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/63228724-583a4a80-c1b4-11e9-9f49-8fdfc85cfcf4.png) ![image](https://user-images.githubusercontent.com/4528551/63228726-62f4df80-c1b4-11e9-9098-b1f24d83cef4.png)


---

#### Files

[coins.zip](https://github.com/Templarian/MaterialDesign/files/3513418/coins.zip)

**Comment by CoDEmanX** [comment]
Is coins the best name for it?

**Comment by goyney** [comment]
> Is coins the best name for it?

Probably not, we also have:

[![plus-circle-multiple-outline](https://materialdesignicons.com/icon/plus-circle-multiple-outline)](https://materialdesignicons.com/icon/plus-circle-multiple-outline)

Probably should be renamed `circle-multiple` and `circle-multiple-outline` with aliases added.

**Comment by goyney** [comment]
Coin renamed and the filled version added:
[![coin](https://materialdesignicons.com/icon/coin)](https://materialdesignicons.com/icon/coin)[![coin-outline](https://materialdesignicons.com/icon/coin-outline)](https://materialdesignicons.com/icon/coin-outline)

Renaming this issue to focus on `circle-multiple`, which likely won't happen until 5.0 because of it being a Breaking Change.

**Comment by JamesCoyle** [comment]
Wouldn't the coin icons make more sense as `currency-usd-circle`?

**Comment by Capeleto** [comment]
This has already been released 🤔 

http://materialdesignicons.com/icon/coin


http://dev.materialdesignicons.com/icon/coin-outline
http://dev.materialdesignicons.com/icon/coin

![image](https://user-images.githubusercontent.com/15040543/71199907-bd42a180-2275-11ea-9a0c-f368b5776efc.png)

**Comment by MrGrigri** [comment]
Yes, `coin` and `coin-outline` have been released. However, `coins` has not been renamed to `coins-outline` and `coins` has not been created yet.

**Comment by galechus** [comment]
Is there any progress with `coins` and 'coins-outline'?

**Comment by Templarian** [comment]
4.9.95 is getting closer to release. Hopefully next week. Then the long process of closing out all the issues marked breaking change. Including this one.

**Comment by goyney** [comment]
`coins` renamed `circle-multiple-outline` and aliased `coins-outline`.
`circle-multiple` added and aliased `coins`.

Note: `circle-multiple` replaced `lyft` in the v5.0 release.

**Comment by goyney** [comment]
`coin` renamed `currency-usd-circle` and aliased `coin`.
`coin-outline` renamed `currency-usd-circle-outline` and aliased `coin-outline.

**Comment by goyney** [comment]
Added missing variants:
[![plus-circle-multiple](https://materialdesignicons.com/icon/plus-circle-multiple)](https://materialdesignicons.com/icon/plus-circle-multiple)

[![minus-circle-multiple](https://materialdesignicons.com/icon/minus-circle-multiple)](https://materialdesignicons.com/icon/minus-circle-multiple)[![minus-circle-multiple-outline](https://materialdesignicons.com/icon/minus-circle-multiple-outline)](https://materialdesignicons.com/icon/minus-circle-multiple-outline)

[![close-circle-multiple](https://materialdesignicons.com/icon/close-circle-multiple)](https://materialdesignicons.com/icon/close-circle-multiple)[![close-circle-multiple-outline](https://materialdesignicons.com/icon/close-circle-multiple-outline)](https://materialdesignicons.com/icon/close-circle-multiple-outline)

Note: `plus-circle-multiple` replaced ` mail-ru`. `minus-circle-multiple` replaced `medium`.  `minus-circle-multiple-outline` replaced `medium`. `close-circle-multiple` replaced `mixcloud`. `close-circle-multiple-outline` replaced `paypal`. All in the v5.0 release.
