### ISSUE TITLE
Toilet paper

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4337]
It has some pseudo-perspective, otherwise I can't think of a way to make it recognizable.

## Preview

![grafik](https://user-images.githubusercontent.com/1309249/63229868-4d5bd600-c205-11e9-967e-d05e4623d3e9.png)

The diameter of the inner circle is 3.5dp because everything else felt off proportions-wise, for reference:

![grafik](https://user-images.githubusercontent.com/1309249/63229918-e559bf80-c205-11e9-999c-092457b9e9b9.png)

## Zip Download

[toilet-paper.zip](https://github.com/Templarian/MaterialDesign/files/3513527/toilet-paper.zip)

**Comment by goyney** [comment]
I actually really like these, though I think the paper is too wide in comparison with the size of the roll. It might be enough to trim off 1dp.

**Comment by CoDEmanX** [comment]
Not sure, it looks a bit weird:

![grafik](https://user-images.githubusercontent.com/1309249/63231674-9ae53c80-c21f-11e9-88ac-a91e77760382.png)

I have to think of a periscope:

![grafik](https://user-images.githubusercontent.com/1309249/63231687-cd8f3500-c21f-11e9-90b8-bc5321793911.png)

**Comment by JamesCoyle** [comment]
I prefer that one. Still not a huge fan of perspective icons but there isn't really any other way.

**Comment by goyney** [comment]
Alias it periscope then :P

**Comment by CoDEmanX** [comment]
Added to v4.4, might create a periscope icon tomorrow 😋

**Comment by CoDEmanX** [comment]
Above icon will be added as `toilet-paper-outline` and here is the filled variant:

![grafik](https://user-images.githubusercontent.com/1309249/63250080-1a4c2d80-c26b-11e9-9fb5-0615129978d8.png)
