### ISSUE TITLE
Home edit

### ISSUE THREAD

**Issue by mariovials** [Templarian/MaterialDesign#4338]
I need home edit icon.

## Usage
I have developed an application to manage the real estate development of a city. This application is used by the local government in Chile.
When changes have been made to homes I need an icon to easily access the edit form for housing fields, differentiated from other fields that can be edited.

## Examples
Just a home with a pencil.

**Comment by CoDEmanX** [comment]
I'm surprised that we don't have such an icon or request already. Seems useful for home automation as well.

![grafik](https://user-images.githubusercontent.com/1309249/63246662-79a63f80-c263-11e9-9d27-12e7bd19b161.png) ![grafik](https://user-images.githubusercontent.com/1309249/63246624-65fad900-c263-11e9-908f-5b8a5e2cf5c0.png)

[MaterialDesign.zip](https://github.com/Templarian/MaterialDesign/files/3514660/MaterialDesign.zip)

**Comment by goyney** [comment]
[![home-edit](https://materialdesignicons.com/icon/home-edit)](https://materialdesignicons.com/icon/home-edit)[![home-edit-outline](https://materialdesignicons.com/icon/home-edit-outline)](https://materialdesignicons.com/icon/home-edit-outline)
