### ISSUE TITLE
SendCheck

### ISSUE THREAD

**Issue by svendeckers** [Templarian/MaterialDesign#4339]
I'm using the `mdiSendLock` icon to securely send messages from one client to another.
It would be great to have the same icon, but instead with a lock, with a checkmark that confirms the message was sent successfully.
Like `eye-check`, `clock-check`, `bug-check` etc

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/63246996-37c9c900-c264-11e9-8043-04f231f75a81.png) ![grafik](https://user-images.githubusercontent.com/1309249/63247099-7f505500-c264-11e9-836c-664524eb3a68.png)

Outline variant by Google without modifier, which we don't have yet:
![grafik](https://user-images.githubusercontent.com/1309249/63247205-c1799680-c264-11e9-9010-c2fa751368af.png)

Download: [send-check.zip](https://github.com/Templarian/MaterialDesign/files/3514693/send-check.zip)

I don't really like these. I would rather go with `email-check` or a similar icon:

![grafik](https://user-images.githubusercontent.com/1309249/63247253-e110bf00-c264-11e9-8624-88a04e125ef8.png)

**Comment by svendeckers** [comment]
Thank you for your reply. 
We use the airplane to make a distinction with email, but I'll put it up for consideration.

I get why someone would like the email version better, the checkmark cuts into the nose of the plane a bit. It might work better leaving out the white circle background (`sendlock` also doesn't have this) ?

**Comment by CoDEmanX** [comment]
Such cutouts should generally be used for icons with modifiers, but here it could also be left out I guess.

![grafik](https://user-images.githubusercontent.com/1309249/63252844-e6740680-c270-11e9-862d-76f49208eb3c.png)

![grafik](https://user-images.githubusercontent.com/1309249/63252891-fd1a5d80-c270-11e9-9991-8792ea21eea2.png)

[send-check2.zip](https://github.com/Templarian/MaterialDesign/files/3514976/send-check2.zip)

**Comment by CoDEmanX** [comment]
With the check mark it could be interpreted as sending a message with read confirmation. With a lock it is an encrypted mesage. How about another variant for scheduled sending?

![grafik](https://user-images.githubusercontent.com/1309249/63255048-23da9300-c275-11e9-87ea-94a3ab86e26f.png)
![grafik](https://user-images.githubusercontent.com/1309249/63255324-cb57c580-c275-11e9-91a2-158380566c1b.png)

[send-clock.zip](https://github.com/Templarian/MaterialDesign/files/3515122/send-clock.zip)

**Comment by goyney** [comment]
[![send-check](https://materialdesignicons.com/icon/send-check)](https://materialdesignicons.com/icon/send-check)[![send-check-outline](https://materialdesignicons.com/icon/send-check-outline)](https://materialdesignicons.com/icon/send-check-outline)
[![send-clock](https://materialdesignicons.com/icon/send-clock)](https://materialdesignicons.com/icon/send-clock)[![send-clock-outline](https://materialdesignicons.com/icon/send-clock-outline)](https://materialdesignicons.com/icon/send-clock-outline)

**Comment by svendeckers** [comment]
that was fast, thanks!!

**Comment by CoDEmanX** [comment]
It will take a few weeks until v4.4 gets released though.
