### ISSUE TITLE
Google Group icon

### ISSUE THREAD

**Issue by wkeizer** [Templarian/MaterialDesign#434]
A Google groups icon would be nice.

![image](https://cloud.githubusercontent.com/assets/1309249/15603215/c827ffba-23f9-11e6-9cfe-01723986349d.png)

**Comment by chrvasile** [comment]
Always wondered why there's no icon for multiple accounts. Now there is:
![account-multiple](https://cloud.githubusercontent.com/assets/17312269/13197848/06d5b4e2-d7fa-11e5-8ced-003a0162d652.png)

And the SVG:
[account-multiple.svg.zip](https://github.com/Templarian/MaterialDesign/files/139238/account-multiple.svg.zip)

**Comment by wkeizer** [comment]
Great work!

**Comment by CoDEmanX** [comment]
@chrvasile: I think the two outer human shapes should be slightly smaller than the middle one. The spacing should be even (as in normal vector distance).

Google Groups icon, derived from existing shapes and with some subtle adjustments:

![google-groups2](https://cloud.githubusercontent.com/assets/1309249/15603186/a90207f2-23f9-11e6-9945-ef689bdba78e.png) ![google-groups1](https://cloud.githubusercontent.com/assets/1309249/15603187/a9023cb8-23f9-11e6-974d-8e2c525d4ce1.png)

![google-groups2_96](https://cloud.githubusercontent.com/assets/1309249/15603260/fb0721d6-23f9-11e6-9038-6ba2d54cb90f.png) ![google-groups1_96](https://cloud.githubusercontent.com/assets/1309249/15603261/fb088864-23f9-11e6-9633-db5d9ef9138d.png)

@Templarian?

**Comment by JamesCoyle** [comment]
Closing as `account-group` now exists.
[![](https://materialdesignicons.com/icon/account-group)](https://materialdesignicons.com/icon/account-group)
