### ISSUE TITLE
Invert selection

### ISSUE THREAD

**Issue by nafets1234** [Templarian/MaterialDesign#4341]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

If you have a list of items and can select multiple ones then you might want to be able to invert the selection.

## Examples
Unfortunately I do not have a real good idea. An often used depiction is a circle in square with a diagonal line and touching areas having different colors.

**Comment by CoDEmanX** [comment]
There is `select-inverse` already:

![grafik](https://user-images.githubusercontent.com/1309249/63304833-c5e59400-c2e4-11e9-98b9-fb709dc23e9b.png)

Added an alias `selection-invert`.
