### ISSUE TITLE
Instagram boxed

### ISSUE THREAD

**Issue by berenicestr** [Templarian/MaterialDesign#4342]
Hello!

I request an icon: instagram-box, similar as Linkedin-box, facebook-box to have the same style in RRSS.
Great work with the material design icons. :-)
Thanks in advance.
Regards!

I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
We've gotten very stringent on the new brand icons we're going to add to the library. When we do allow a brand, it is going to follow they brands guidelines. While we may have variations of certain brand logos, we're not going to be doing that anymore. Apologizes, but thanks for the suggestion.
