### ISSUE TITLE
Update my details

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4344]
I've migrated to a different Twitter account and changed my profile pic. Could you update the details for me?

Twitter: @JapanYoshiLOL -> @ItsSpelledHALEY
Name: JapanYoshi -> Haley Halcyon
Description: Also known as theFIZZYnator around the internet. -> Also known as JapanYoshi, theFIZZYnator, or Akira Sora around the Internet.
Profile pic: https://cdn.discordapp.com/attachments/590163025332535307/613160399079997448/haleyhalcyon-layer3.png

**Comment by JamesCoyle** [comment]
I thought we could do this ourselves through the admin portal?

**Comment by Templarian** [comment]
You can.
