### ISSUE TITLE
Update `furigana` to resemble `translate`

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4345]
I'd like to update my icon so it looks a bit more consistent with a Google icon.

## Preview

![bitmap](https://user-images.githubusercontent.com/8707990/63308050-13d5b880-c334-11e9-8cd8-619d77cd6425.png)
![bitmap](https://user-images.githubusercontent.com/8707990/63308034-07e9f680-c334-11e9-86c0-d747aa6b2d48.png)

## Zip Download

[furigana_export.zip](https://github.com/Templarian/MaterialDesign/files/3518141/furigana_export.zip)
Contains 2 path elements. I made sure to merge each of them beforehand.

**Comment by goyney** [comment]
Done!
