### ISSUE TITLE
Aliases and tags to some of my icons

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4347]
- [x] `currency-rial`: add tags "Currency" and "Banking" and possibly aliases `currency-[irr, omr, yer, sar]` for specific `/Riy?al/`s
- [x] `furigana-*`: add tag "Text / Content / Format" and alias `ruby-*`
- [x] `fuel`: add aliases `petrol` and/or `gasoline`
- [x] `metronome`: add aliases `tempo` and/or `bpm`

**Comment by goyney** [comment]
Done. Thanks!
