### ISSUE TITLE
Google home max icon

### ISSUE THREAD

**Issue by tomhoogeveentje** [Templarian/MaterialDesign#4348]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to use the icon in Home assistant to differentiate my regular google home device and my google home max devices

## Examples
I don't have a icon design but this is what the speaker looks like :) 
https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6124/6124307_sa.jpg;maxHeight=640;maxWidth=550

**Comment by goyney** [comment]
We've stopped adding icons depicting specific devices a while ago. Unfortunately, we will not be adding this.
