### ISSUE TITLE
flow process- horizontal flow

### ISSUE THREAD

**Issue by berenicestr** [Templarian/MaterialDesign#4349]
Hi Team!

 I request an icon flowchart / process to the flows in horizontal flow  in outline style. I don't see something similar.

Thanks and regards.

I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
We've added `sitemap-outline`. You can simply rotate the glyph 90 degrees for a horizontal flow.
[![sitemap-outline](https://materialdesignicons.com/icon/sitemap-outline)](https://materialdesignicons.com/icon/sitemap-outline)
