### ISSUE TITLE
Project/s Management 

### ISSUE THREAD

**Issue by berenicestr** [Templarian/MaterialDesign#4350]
Hi team!

I request an icon, that I don't find something similar in the repo. 
An icon that represents project/s management , in outline style.

Thanks and best regards,

I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
> Provide some context of how your icon could be used.
> Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
See also #3299, #1605, #1971, #1929... This has been requested a few times. See if anyone of those work for you, otherwise please share some examples of what you envision. Thanks.

**Comment by berenicestr** [comment]
Thanks @goyney. Its for a menu option where the projects management section configure/edit the projects or the teams. 
I have also the options (teams, folders/documents analytics and settings option menu - So, in my case,  the #3299 #1605 #1971 #1929 could be confused the option for the user app ). 

I will provide some examples. 
Thanks and regards

**Comment by berenicestr** [comment]
Hi!

For example, something similar:

https://icon-library.net/icon/project-management-icon-13.html

**Comment by goyney** [comment]
So, we have those in certain variations:

[![clipboard-list](https://materialdesignicons.com/icon/clipboard-list)](https://materialdesignicons.com/icon/clipboard-list)[![clipboard-list-outline](https://materialdesignicons.com/icon/clipboard-list-outline)](https://materialdesignicons.com/icon/clipboard-list-outline)
[![chart-timeline](https://materialdesignicons.com/icon/chart-timeline)](https://materialdesignicons.com/icon/chart-timeline)

Do any of these work for you?

**Comment by berenicestr** [comment]
Thanks @goyney. 

I use clipboard-list-outline in my option tasks 😞.

I would be great to have an clipboard-list with an icon time/person o settings 🎉, but chart-time could be an alternative to work for me ( I don’t see it before).

Thanks and regards

**Comment by PeterShaggyNoble** [comment]
See also `clipboard-account(-outline)`:

![clipboard-account](https://user-images.githubusercontent.com/15157491/63379110-81f99a00-c38b-11e9-9e69-c5c997087851.png)![clipboard-account-outline (1)](https://user-images.githubusercontent.com/15157491/63379123-8d4cc580-c38b-11e9-9db2-f970143bef92.png)

**Comment by berenicestr** [comment]
Thanks @PeterShaggyNoble ! This would be great for me. 👍
