### ISSUE TITLE
Flights & Hotels

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4351]
Came across this in MIE (dunno how I missed it before), which would've come in handy on a tour website I did recently.

[![flights-and-hotels](https://user-images.githubusercontent.com/15157491/63388409-40271e80-c3a0-11e9-8227-57cad925b2fc.png)](https://petershaggynoble.github.io/MDI-Sandbox/extended/)

On my phone at the moment so can't convert it and zip it up.

**Comment by CoDEmanX** [comment]
@PeterShaggyNoble v48 of Material Icons font?

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX, don't know if it's included in the standard MI font (yet), but it's been in MIE since v51, at least.

**Comment by CoDEmanX** [comment]
Thanks, will check out https://fonts.googleapis.com/icon?family=Material+Icons+Extended

**Comment by PeterShaggyNoble** [comment]
Needs a bit of a cleanup.

[![airplane-hotel](https://user-images.githubusercontent.com/15157491/63789276-f03fde80-c8ee-11e9-8681-8d6a153e3b73.png)](https://github.com/Templarian/MaterialDesign/files/3547172/airplane-hotel.zip)

**Comment by JamesCoyle** [comment]
I feel `hotel-airplane` might be better here or better `bed-airplane` (`hotel` should be `bed` IMO). You would be most likely to use this icon to denote a hotel that is in proximity to an airport.

**Comment by Templarian** [comment]
I get that it's an official icon, but it still looks kind of... lazy? Like there should be a nicer way to show this.

**Comment by goyney** [comment]
Closing because the `Consider Closing` label was added months ago and this icon is subpar, at best.
