### ISSUE TITLE
format-quote-(open,close)-outline

### ISSUE THREAD

**Issue by SignpostMarv** [Templarian/MaterialDesign#4352]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Used in the same way the existing `format-quote-open` & `format-quote-close` icons are used.

## Examples
Ideally the tails of the quotes would be outlined rather than solid, as with the narrow tails of the flash icons.
![flash](https://user-images.githubusercontent.com/304403/63420062-d8072580-c3fd-11e9-99ae-0e4ac30ed46f.png) ![flash-outline](https://user-images.githubusercontent.com/304403/63420057-d50c3500-c3fd-11e9-92a4-a2fad2855a99.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/63456848-0d673f80-c40d-11e9-86db-56908951b453.png) ![image](https://user-images.githubusercontent.com/4528551/63456880-1b1cc500-c40d-11e9-99dc-c28f4fa37488.png)

---
#### Files

Pre-optimized paths.

[format-quote-outline.zip](https://github.com/Templarian/MaterialDesign/files/3526665/format-quote-outline.zip)

**Comment by SignpostMarv** [comment]
re: the thin outline in the tails, I had something like this in mind?
![this-is-what-i-was-thinking](https://user-images.githubusercontent.com/304403/63459361-4ecb0f80-c44c-11e9-8593-657beb8816bb.png)

**Comment by CoDEmanX** [comment]
The tail is only 3dp wide. Even with a stroke width of 1.5dp it would still be filled. The option is to grow the outline IMO...

![grafik](https://user-images.githubusercontent.com/1309249/63473382-8601e680-c475-11e9-80d1-1edcef966225.png)

It's kinda blurry however. MrGrigri suggestions look a bit too much like 66 and 99 on the other hand.

**Comment by goyney** [comment]
I do not think an outlined variant of this makes much sense. As @MrGrigri has proved, they just look like numbers.

**Comment by MrGrigri** [comment]
I believe in context they would make sense.

**Comment by SignpostMarv** [comment]
@goyney it's a stylistic choice, and the outlined tails seem to negate the resemblance to numbers one gets when outlining solely the main body of the quotes.

**Comment by goyney** [comment]
@CoDEmanX Your version of growing out is not using a 2dp stroke. Can we see what that looks like?

**Comment by CoDEmanX** [comment]
Away camping over the weekend, but can try next week.

MDI light has this icon BTW.

**Comment by PeterShaggyNoble** [comment]
For reference:

Google's version ain't pretty:
[![format-quote-close-outline](https://user-images.githubusercontent.com/15157491/63787661-1ca62b80-c8ec-11e9-9001-75eac30c9414.png)](https://material.io/resources/icons/?search=format_quote&icon=format_quote&style=outline)

Our MDIL ones @CoDEmanX mentioned:
![format-quote-close](https://user-images.githubusercontent.com/15157491/63787912-87effd80-c8ec-11e9-83b2-954eb129f415.png)![format-quote-open](https://user-images.githubusercontent.com/15157491/63787963-9b9b6400-c8ec-11e9-9e86-b11d7f876c80.png)

**Comment by SignpostMarv** [comment]
MDIL ones appear to have a distinctly different aspect ratio on the head of the quote :s

**Comment by CoDEmanX** [comment]
> Your version of growing out is not using a 2dp stroke. Can we see what that looks like?

@goyney Google's icon is exactly that:

[![format-quote-close-outline](https://user-images.githubusercontent.com/15157491/63787661-1ca62b80-c8ec-11e9-9001-75eac30c9414.png)](https://material.io/resources/icons/?search=format_quote&icon=format_quote&style=outline)

It's not too bad IMO, it does not look like 99 and uses the standard stroke width...

What we can do to improve it slight is to move the two bottom left vertices to the left by 0.5dp:

![grafik](https://user-images.githubusercontent.com/1309249/63791627-30598e00-c8fc-11e9-9056-876cd54e5bf7.png)

[format-quote-outline.zip](https://github.com/Templarian/MaterialDesign/files/3547277/format-quote-outline.zip)

**Comment by goyney** [comment]
[![format-quote-open-outline](https://materialdesignicons.com/icon/format-quote-open-outline)](https://materialdesignicons.com/icon/format-quote-open-outline)[![format-quote-close-outline](https://materialdesignicons.com/icon/format-quote-close-outline)](https://materialdesignicons.com/icon/format-quote-close-outline)
