### ISSUE TITLE
Database Related Icons

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4353]
- [ ] primary key (key-star)
- [ ] foreign key (key-link)
- [ ] null (I know `null` exists, but that symbol is more often used for empty set)
- [ ] not null (null-off)

P.S. some others I already found candidates for (for future searchers):
- constraint ([pencil-lock](http://materialdesignicons.com/icon/pencil-lock) should suit that purpose)
- query ([database-search](http://materialdesignicons.com/icon/database-search) or [table-search](http://materialdesignicons.com/icon/table-search) should suit that purpose)
- drop table ([table-remove](http://materialdesignicons.com/icon/table-remove) should suit that purpose)

## Preview
![image](https://user-images.githubusercontent.com/8707990/63420316-cb102380-c449-11e9-880d-eece7ae9d77f.png)
![image](https://user-images.githubusercontent.com/8707990/63420349-d7947c00-c449-11e9-918a-c5df4ab8d257.png)
![image](https://user-images.githubusercontent.com/8707990/63420258-af0c8200-c449-11e9-98d1-25d7e525cc36.png)
![image](https://user-images.githubusercontent.com/8707990/63420284-baf84400-c449-11e9-92fd-06947f5f6de1.png)

## Zip Download
[sql.zip](https://github.com/Templarian/MaterialDesign/files/3524597/sql.zip)

**Comment by MrGrigri** [comment]
I believe `null` could be a language conflict. I would suggest `circle-outline` and `circle-off-outline` for `null` and `null-off`. 

![circle-outline](https://materialdesignicons.com/icon/circle-outline) ![circle-off-outline](https://materialdesignicons.com/icon/circle-off-outline)

**Comment by JamesCoyle** [comment]
I don't mind the `null` as text as it's a common keyword in programming languages and is pretty recognisable for a lot of people. I'd alias the circles with null too if they aren't already though so there is a good option for locales that the text doesn't work for.

I also think these should be added as `key-star` and `key-link` to keep with our more literal naming with the names suggested above as aliases.

**Comment by goyney** [comment]
[![key-star](https://materialdesignicons.com/icon/key-star)](https://materialdesignicons.com/icon/key-star)[![key-link](https://materialdesignicons.com/icon/key-link)](https://materialdesignicons.com/icon/key-link)

I'm inclined to agree with @MrGrigri that `null` is a language conflict. We've said here many times before that we will only add letter-based icons if there are no other ways to depict the meaning of the icon. I think that there are several language-agnostic ways to do so, so I chose to not add the `null` ones for now.

If you feel strongly about those being added, please open a new issue for further discussion.
