### ISSUE TITLE
pound-box-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4354]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

- Hashtag for social media.
- Number identicator.

## Examples

![pound-box-outline](https://user-images.githubusercontent.com/6717356/63438894-c6417480-c435-11e9-8742-2440fbad85c7.png)

**Comment by MrGrigri** [comment]
Path has been pre-optimized

![image](https://user-images.githubusercontent.com/4528551/63455757-a3e63180-c40a-11e9-823c-f53f40f3daed.png)

---
### Files
[pound-box-outline.zip](https://github.com/Templarian/MaterialDesign/files/3526610/pound-box-outline.zip)

**Comment by PeterShaggyNoble** [comment]
@ozgurg, we'll close this once it's been added to the library.

**Comment by goyney** [comment]
[![pound-box-outline](https://materialdesignicons.com/icon/pound-box-outline)](https://materialdesignicons.com/icon/pound-box-outline)
