### ISSUE TITLE
account-settings-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4355]
The `account-settings-outline` icon is misaligned. It should be 2-pixels lower.

![account-settings-outline](https://materialdesignicons.com/icon/account-settings-outline) ![account-settings](https://materialdesignicons.com/icon/account-settings)

**Comment by CoDEmanX** [comment]
Also the stroke width seems to 1.9dp instead of 2dp?

![grafik](https://user-images.githubusercontent.com/1309249/63473950-9915b600-c477-11e9-93de-87428d90052f.png)

**Comment by MrGrigri** [comment]
Good catch

**Comment by CoDEmanX** [comment]
Is this an optical correction by any chance? Or caused by Austin's path optimization?

**Comment by MrGrigri** [comment]
The `settings` modifier is supposed to be at the bottom. I don't think placing it up 2-pixels was intentional.

**Comment by CoDEmanX** [comment]
Sorry, I meant the 0.1dp too thin stroke width

**Comment by goyney** [comment]
Updated.

[![account-settings-outline](https://materialdesignicons.com/icon/account-settings-outline)](https://materialdesignicons.com/icon/account-settings-outline)
