### ISSUE TITLE
Icon Request: Borrow and Lend

### ISSUE THREAD

**Issue by nkappler** [Templarian/MaterialDesign#4356]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

I'd like to have two icons for borrow and lend. (And maybe a combination of both)
Examples I like:
https://icon-library.net/icon/borrow-icon-23.html
https://icon-library.net/icon/borrow-icon-26.html
https://icon-library.net/icon/borrow-icon-25.html

**Comment by goyney** [comment]
We recently added `hand-coin`. Would that work for this?

[![hand-coin](https://materialdesignicons.com/icon/hand-coin)](https://materialdesignicons.com/icon/hand-coin)

**Comment by goyney** [comment]
It seems we have an answer for this use case, but we haven't gotten a response from you in a couple weeks. Therefore, we're going to close this and consider the issue complete. If this does not satisfy your use case, please comment back or open a new issue. Thanks for your suggestion!
