### ISSUE TITLE
Icons after update 2px over normal text-line

### ISSUE THREAD

**Issue by doppelff** [Templarian/MaterialDesign#4357]
Hey,
after i am update MaterialDesign from 3.5.95 to 4.1.95 (or 3.9.96) my mdi icons are 2px horizontally higher than the normal text-line.

![Issue MDI](https://user-images.githubusercontent.com/49231898/63501712-6f3aae80-c4cc-11e9-90f3-09afec1d8009.JPG)
![Issue MDI_2](https://user-images.githubusercontent.com/49231898/63501713-6fd34500-c4cc-11e9-9a2f-3abd012f0c49.JPG)

I can't find a style that's responsible for it. After a rollback to 3.5.95 everything is fine.

**Comment by Templarian** [comment]
Something is definitely wrong with the export. I wonder if we didn't set a property in the font export.

**Comment by Templarian** [comment]
@doppelff Context for you, we switched everything over to `@mdi/font-build` as we open source the tooling chain.

**Comment by goyney** [comment]
@doppelff Can you share a minimal reproduction example?

**Comment by Templarian** [comment]
No need. I can reproduce it on the http://dev.materialdesignicons.com/getting-started/bootstrap page after updating the version (that page uses an old version, edit the html to bump the version).

**Comment by Templarian** [comment]
We have a fix for this in `4.2.95` that is going out Sunday. I've update the CDN for this version also. Please let me know if this fixes your issue @doppelff. 😃

**Comment by doppelff** [comment]
Thanks for the fast Update, i have test it with the CDN and it work like a charm. 😃

**Comment by doppelff** [comment]
no probs! yesterday i dont had any time to build it in my project. But now i have it in and it work, thanks!
