### ISSUE TITLE
school-outline

### ISSUE THREAD

**Issue by berenicestr** [Templarian/MaterialDesign#4359]
Please, ¿Could add for the next versions the school icon in outline mode?

https://materialdesignicons.com/icon/school

Thanks and Regards

I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/63536554-191c3a00-c4d1-11e9-8e38-2180a5050ff8.png)

---
#### Files

[school-outline.zip](https://github.com/Templarian/MaterialDesign/files/3531278/school-outline.zip)

**Comment by berenicestr** [comment]
Great! Thanks @MrGrigri

**Comment by PeterShaggyNoble** [comment]
Google's version:

[![school-outline](https://user-images.githubusercontent.com/15157491/63552513-b4dc9300-c52f-11e9-8786-d3d048ae66c2.png)](https://material.io/resources/icons/?search=school&icon=school&style=outline)

**Comment by MrGrigri** [comment]
Yeah, that's better. Let's add theirs.

**Comment by CoDEmanX** [comment]
Or both? Mixed solid and outlined seems to be a style variant of its own, seen a few by Google like that e.g. their account multiple...

![grafik](https://user-images.githubusercontent.com/1309249/63599386-c7071180-c5c1-11e9-9123-3549f0ac2d52.png)

**Comment by goyney** [comment]
[![school-outline](https://materialdesignicons.com/icon/school-outline)](https://materialdesignicons.com/icon/school-outline)
