### ISSUE TITLE
Is include account-tie-outline icon in the latest version?

### ISSUE THREAD

**Issue by berenicestr** [Templarian/MaterialDesign#4360]
Hi Team!

When I try to show account-tie-outline doesn't see anything. 
Please, Is this icon include in the latest npm version?

This is a code sandbox: https://codesandbox.io/s/nuxtjs-vuetify-p8flj?fontsize=14

Thanks and regards

**Comment by Templarian** [comment]
It will got out in `4.3.95`. Which is probably 2 weeks out. We're wrapping up the release for `4.2.95` right now.

We're behind a few releases right now as we update and open source the tooling chain.

**Comment by berenicestr** [comment]
Great. Thanks @Templarian !
