### ISSUE TITLE
Send variants (cancel schedule / archive)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4361]
Google uses two more send variants in addition to the one with a clock, e.g.

![grafik](https://user-images.githubusercontent.com/1309249/63598238-742c5a80-c5bf-11e9-835e-5cb244141565.png)

Here are my slightly tweaked versions:

![grafik](https://user-images.githubusercontent.com/1309249/63598516-046a9f80-c5c0-11e9-9784-79fe5aaf26d7.png)
![grafik](https://user-images.githubusercontent.com/1309249/63598543-10566180-c5c0-11e9-915c-4159e83fb1b2.png)
![grafik](https://user-images.githubusercontent.com/1309249/63598566-1fd5aa80-c5c0-11e9-9322-17369093a8a1.png)
![grafik](https://user-images.githubusercontent.com/1309249/63598587-2cf29980-c5c0-11e9-8547-5fca92a51fb4.png)

Mine use the base shape (the left points not moved 1dp into the margin like Google did), but consistently with an optical correction (pointy inside):

![grafik](https://user-images.githubusercontent.com/1309249/63598888-c02bcf00-c5c0-11e9-9d10-b2b93efded2a.png)

Names are up for discussion.

[send-variants.zip](https://github.com/Templarian/MaterialDesign/files/3534883/send-variants.zip)

**Comment by goyney** [comment]
I don't like them, we don't have any other icons with the modifier in a box. Can we see what these would look like without the box, using our cutout instead?

**Comment by CoDEmanX** [comment]
For the cancel that should work, but just an arrow down doesn't really read as "archive". It needs a box of some sort IMO.

**Comment by JamesCoyle** [comment]
Isn't there enough space to just have the icon in the bottom corner? Might have to bend the 2dp margin rule a bit.

**Comment by PeterShaggyNoble** [comment]
The filled versions are in MIE:

![cancel-schedule-send](https://user-images.githubusercontent.com/15157491/63635046-c0c27500-c655-11e9-9edb-e8fbea193bfd.png)![send-and-archive](https://user-images.githubusercontent.com/15157491/63635048-c750ec80-c655-11e9-8433-5d1ea1b3cd52.png)

**Comment by CoDEmanX** [comment]
@petershaggynoble The MIE versions are weird. The cancel schedule one has the base shape moved 1dp to the left and both have the outer points on the left-hand side not on grid by 0.1dp for some reason.

**Comment by JamesCoyle** [comment]
TBH I don't see the use-case for either of these.

**Comment by Templarian** [comment]
These seem very niche. Seems like one could use a regular cancel/download type icon. 😕

**Comment by JapanYoshi** [comment]
I agree with the others; these shouldn't be added.

**Comment by Templarian** [comment]
Closing this as the general consensus seems to be the same.
