### ISSUE TITLE
phone-in-talk-outline

### ISSUE THREAD

**Issue by SnickDesign** [Templarian/MaterialDesign#4363]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

![Без названия (1)](https://user-images.githubusercontent.com/54479108/63642722-6a444d80-c6cc-11e9-8c15-b24494a2183b.png)

[phone-in-talk-outline.zip](https://github.com/Templarian/MaterialDesign/files/3537568/phone-in-talk-outline.zip)

**Comment by PeterShaggyNoble** [comment]
This too is a stock Google icon:

[![phone-in-talk-outline](https://user-images.githubusercontent.com/15157491/63706434-4cd7c680-c827-11e9-8e2d-9516ff632e71.png)](https://github.com/Templarian/MaterialDesign/files/3542000/phone-in-talk-outline.zip)

**Comment by PeterShaggyNoble** [comment]
Now available:

[![phone-in-talk-outline](https://user-images.githubusercontent.com/15157491/63707202-3fbbd700-c829-11e9-9ccd-e1e3d70d0eed.png)](https://materialdesignicons.com/icon/phone-in-talk-outline)

**Comment by SnickDesign** [comment]
I did not find such an icon in google material.
Modification of google icons are google material icons?
Thanks!

![image](https://user-images.githubusercontent.com/54479108/63708110-2e2ffa80-c83c-11e9-8d3e-62f3ab780e9f.png)

**Comment by PeterShaggyNoble** [comment]
It's in their "Notification" category.
