### ISSUE TITLE
Laravel logo update

### ISSUE THREAD

**Issue by pixieaka** [Templarian/MaterialDesign#4364]
https://laravel.com/
![Capture](https://user-images.githubusercontent.com/17777237/63643502-e2f9d880-c6d1-11e9-8495-caf3bc04a985.PNG)

**Comment by JapanYoshi** [comment]
# [We're no longer accepting new brand icons into MDI.](http://dev.materialdesignicons.com/roadmap/brand-icons)

We recommend checking out [SimpleIcons](https://simpleicons.org/). SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page](https://github.com/simple-icons/simple-icons/issues).

Thank you for your suggestion.

**Comment by goyney** [comment]
This logo already exists and is a developmental tool/framework which would meet our exception list anyways. We will update this logo.

**Comment by goyney** [comment]
[![laravel](https://materialdesignicons.com/icon/laravel)](https://materialdesignicons.com/icon/laravel)
