### ISSUE TITLE
basket-outline

### ISSUE THREAD

**Issue by SnickDesign** [Templarian/MaterialDesign#4366]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

![Презентация иконки](https://user-images.githubusercontent.com/54479108/63655941-fae76000-c796-11e9-8b29-1d99edbb569a.png)

[basket-outline.zip](https://github.com/Templarian/MaterialDesign/files/3538643/basket-outline.zip)

**Comment by PeterShaggyNoble** [comment]
Thanks for the contribution, @SnickDesign but please note that all icons should be a single path.

This particular icon is also a stock Google icon:

[![basket-outline](https://user-images.githubusercontent.com/15157491/63706012-56146380-c826-11e9-83da-ba52ac536ec0.png)](https://github.com/Templarian/MaterialDesign/files/3541984/basket-outline.zip)

**Comment by PeterShaggyNoble** [comment]
Now available:

[![basket-outline](https://user-images.githubusercontent.com/15157491/63707322-89a4bd00-c829-11e9-9229-0299450481e3.png)](https://materialdesignicons.com/icon/basket-outline)

**Comment by SnickDesign** [comment]
ok. Thanks
