### ISSUE TITLE
sms-plus

### ISSUE THREAD

**Issue by Sunpay** [Templarian/MaterialDesign#4367]
Our application has a bulk send option for emails and SMS.
The icon email-plus works well for bulk emails.
We would like a sms-plus icon for bulk SMS

**Comment by goyney** [comment]
We already have `message-plus`. The message icons have their modifiers in the bubble.

[![message-plus](https://materialdesignicons.com/icon/message-plus)](https://materialdesignicons.com/icon/message-plus)
