### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by mupkoo** [Templarian/MaterialDesign#4368]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A simple table icon. It can be used by a restaurant to indicate that a specific number is a the tables number

## Examples

Here is an example from Icon8
![icons8-table-96](https://user-images.githubusercontent.com/1788571/63684211-08d3ca00-c805-11e9-81df-adf6c45ce28c.png)

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73598073-d2c50f80-4533-11ea-8aec-efe021bc545e.png)

What about a whole furniture collection? There are only few furniture icons at the moment.

**Comment by Templarian** [comment]
Lets center it and bring the legs up a tiny bit, but 2.5dp works for this.

@nilsfast Even if it's a work in progress attach the `.zip` for the SVG. Assigned this one to you with the tweaks mentioned. 👍  You'll get an idea of the look as you design more, keep it up good work so far.
