### ISSUE TITLE
file-key

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4369]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![file-key](https://user-images.githubusercontent.com/4528551/63713548-1c7b3280-c7fd-11e9-9fda-76fa0733bfee.png) ![file-key-outline](https://user-images.githubusercontent.com/4528551/63713503-04a3ae80-c7fd-11e9-8d0a-e3d211ec1727.png)

## Zip Download

[file-key.zip](https://github.com/Templarian/MaterialDesign/files/3542349/file-key.zip)

**Comment by goyney** [comment]
[![file-key](https://materialdesignicons.com/icon/file-key)](https://materialdesignicons.com/icon/file-key)[![file-key-outline](https://materialdesignicons.com/icon/file-key-outline)](https://materialdesignicons.com/icon/file-key-outline)
