### ISSUE TITLE
Do you have an icon for update my location?

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#437]
Could you please make an icon to say "update location".

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/crosshairs-gps Probably the stock gps icon I would think.

**Comment by jmj4you** [comment]
I think this means current GPS location. But i need to say user that update my location by current location. That icon shows an action just like update/save. I think you can add "checked/ticked" with this icon.
Thank you

**Comment by Templarian** [comment]
http://materialdesignicons.com/ Google has this stock one, but do you mean the upside down tear drop style with a check to the right (or maybe inside)?

**Comment by Templarian** [comment]
(fixed the link above to point at the right icon)

**Comment by jmj4you** [comment]
Billion thanks. This is super.
