### ISSUE TITLE
file-certificate

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4370]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![file-certificate](https://user-images.githubusercontent.com/4528551/63713841-aaefb400-c7fd-11e9-8b9e-c952adf0de4d.png) ![file-certificate-outline](https://user-images.githubusercontent.com/4528551/63713786-97444d80-c7fd-11e9-981a-c2c736c68de1.png)

## Zip Download

[file-certificate.zip](https://github.com/Templarian/MaterialDesign/files/3542371/file-certificate.zip)

**Comment by CoDEmanX** [comment]
The star shape looks a little squashed, unlike in our certificate and seal icons. Is it on purpose to place the vertices on the grid?

**Comment by CoDEmanX** [comment]
I feel that we would need to update the existing icons accordingly to make them consistent, WDYT?

**Comment by goyney** [comment]
[![file-certificate](https://materialdesignicons.com/icon/file-certificate)](https://materialdesignicons.com/icon/file-certificate)[![file-certificate-outline](https://materialdesignicons.com/icon/file-certificate-outline)](https://materialdesignicons.com/icon/file-certificate-outline)
