### ISSUE TITLE
certificate-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4371]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![certificate-outline](https://user-images.githubusercontent.com/4528551/63726358-42fb9680-c81a-11e9-8cb6-d94873532d84.png)

## Zip Download

[certificate-outline.zip](https://github.com/Templarian/MaterialDesign/files/3543265/certificate-outline.zip)

**Comment by goyney** [comment]
[![certificate-outline](https://materialdesignicons.com/icon/certificate-outline)](https://materialdesignicons.com/icon/certificate-outline)
