### ISSUE TITLE
QR Code - add a plus sign for "add new"

### ISSUE THREAD

**Issue by peterkd** [Templarian/MaterialDesign#4372]
QR Code - add a plus sign for "add new"

**Comment by PeterShaggyNoble** [comment]
Having the modifier in the top-right of the QR icons still looks weird to me:

[![qrcode-plus](https://user-images.githubusercontent.com/15157491/63785107-b4ede180-c8e7-11e9-8c15-3401ac2e06e0.png)](https://github.com/Templarian/MaterialDesign/files/3546960/qrcode-plus.zip)[![qrcode-minus](https://user-images.githubusercontent.com/15157491/63785333-18780f00-c8e8-11e9-9b5f-7a04aeadb5e0.png)](https://github.com/Templarian/MaterialDesign/files/3546980/qrcode-minus.zip)

**Comment by PeterShaggyNoble** [comment]
Path data 'cause I'm on me phone:

```
M5,5H7V7H5V5M1,1H11V11H1V1M3,3V9H9V3H3M5,17H7V19H5V17M1,13H11V23H1V13M3,15V21H9V15H3M13,13H17V15H19V13H23V15H19V17H23V23H19V21H15V23H13V21H15V19H13V13M21,21V19H19V21H21M19,17H17V15H15V19H19V17M15.17,1.76L13.76,3.17L16.59,6L13.76,8.83L15.17,10.24L18,7.41L20.83,10.24L22.24,8.83L19.41,6L22.24,3.17L20.83,1.76L18,4.59L15.17,1.76Z
```

![qrcode-remove](https://user-images.githubusercontent.com/15157491/63812104-3dd53f00-c921-11e9-8200-47348d84d723.png)

**Comment by goyney** [comment]
[![qrcode-plus](https://materialdesignicons.com/icon/qrcode-plus)](https://materialdesignicons.com/icon/qrcode-plus)[![qrcode-minus](https://materialdesignicons.com/icon/qrcode-minus)](https://materialdesignicons.com/icon/qrcode-minus)
[![qrcode-remove](https://materialdesignicons.com/icon/qrcode-remove)](https://materialdesignicons.com/icon/qrcode-remove)
