### ISSUE TITLE
shield-edit & shield-refresh + outline variants

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4374]
I needed them, so I share them with the community. I hope it'll be useful.

## Preview

![image](https://user-images.githubusercontent.com/6012554/63779884-9c7dc700-c8e7-11e9-9aba-a8a095af67c7.png)
![image](https://user-images.githubusercontent.com/6012554/63779937-abfd1000-c8e7-11e9-90b7-c1be9fdf4d85.png)
![image](https://user-images.githubusercontent.com/6012554/63780017-c931de80-c8e7-11e9-9424-d234c98a4361.png)
![image](https://user-images.githubusercontent.com/6012554/63780062-d949be00-c8e7-11e9-99a4-ac363c07483a.png)

## Zip Download

[more-shields.zip](https://github.com/Templarian/MaterialDesign/files/3546639/more-shields.zip)

**Comment by goyney** [comment]
[![shield-edit](https://materialdesignicons.com/icon/shield-edit)](https://materialdesignicons.com/icon/shield-edit)[![shield-edit-outline](https://materialdesignicons.com/icon/shield-edit-outline)](https://materialdesignicons.com/icon/shield-edit-outline)
[![shield-refresh](https://materialdesignicons.com/icon/shield-refresh)](https://materialdesignicons.com/icon/shield-refresh)[![shield-refresh-outline](https://materialdesignicons.com/icon/shield-refresh-outline)](https://materialdesignicons.com/icon/shield-refresh-outline)
