### ISSUE TITLE
lock-check and lock-open-alert

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4375]
In my case, the _system_ is safe when it is locked and in danger when it is unlocked. I express this with the following icons. I hope it'll help.

## Preview

![image](https://user-images.githubusercontent.com/6012554/63784385-ddc5a500-c8ee-11e9-9547-33deaab55426.png)

![image](https://user-images.githubusercontent.com/6012554/63784335-cdadc580-c8ee-11e9-8b1f-9ed559dbfb64.png)

## Zip Download

[more-locks.zip](https://github.com/Templarian/MaterialDesign/files/3546912/more-locks.zip)

**Comment by qnp** [comment]
I did not join the outline variants as I feel they did not match

**Comment by qnp** [comment]
Yes it's true, hence we need to modify the lock-alert version accordingly

**Comment by qnp** [comment]
Accross the library, there are plenty of versions of a check mark. If you look for every icons with "check" filter you will see that there is not a clear unity between all icons. I count at least 9 versions of a check mark (with varying size, shape and thickness).
I used the one used by Google (in *alarm-check* for instance). However, if we strictly apply material design principles we should use a 2px thick mark. I tried but it looks too boldy – as you can see here:
![image](https://user-images.githubusercontent.com/6012554/63924345-6572f700-ca48-11e9-8a2f-b8bcc872f114.png)

I also tested the alternate versions of lock / lock-open with the alert modifier: what do you think ?
![image](https://user-images.githubusercontent.com/6012554/63925508-84728880-ca4a-11e9-86c2-64d5256cb9b1.png)
![image](https://user-images.githubusercontent.com/6012554/63925458-745aa900-ca4a-11e9-9092-dd76bffa3bd5.png)

**Comment by CoDEmanX** [comment]
The lock looks huge compared to the exclamation mark.

I dislike the open lock in general because it's hard to see that it's open. I very much prefer the variant:

![grafik](https://user-images.githubusercontent.com/1309249/64050616-edf0b500-cb78-11e9-83aa-44fe25738093.png)

Might look weird with an exclamation mark though.

**Comment by Templarian** [comment]
Updated `lock-alert`.

**Comment by Templarian** [comment]
Added `lock-check` and `lock-open-check`.
