### ISSUE TITLE
phone-missed-outline & phone-off-outline

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4376]
To finish off the `phone-*-outline` icons, Google's `phone-missed-outline` needs to be tweaked to play nice with our optimiser and their `phone-off-outline` needs to be flipped, for consistency.

[![phone-missed-outline](https://user-images.githubusercontent.com/15157491/63793202-15d0e600-c8f7-11e9-86d7-7b7c4d58459b.png)](https://fonts.gstatic.com/s/i/materialiconsoutlined/phone_missed/v1/24px.svg)[![phone-off-outline](https://user-images.githubusercontent.com/15157491/63793239-2f722d80-c8f7-11e9-9572-ca50a29aec35.png)](https://fonts.gstatic.com/s/i/materialiconsoutlined/phone_disabled/v1/24px.svg)

**Comment by CoDEmanX** [comment]
Not a fan of the flipped phone. Keeping the phone shape consistent seems more important than having the strike through line consistent here.

**Comment by goyney** [comment]
[![phone-missed-outline](https://materialdesignicons.com/icon/phone-missed-outline)](https://materialdesignicons.com/icon/phone-missed-outline)[![phone-off-outline](https://materialdesignicons.com/icon/phone-off-outline)](https://materialdesignicons.com/icon/phone-off-outline)

**Comment by goyney** [comment]
That phone missed arrow is too thick. It doesn't match the other phone outline arrow weights and it doesn't match the filled arrow weight, so I reduced it to match the filled version.
