### ISSUE TITLE
CSS file size 187KB !!

### ISSUE THREAD

**Issue by Waleedov** [Templarian/MaterialDesign#4377]
I only use 5-10 icons. Do I have to include a huge CSS file just for that?
I think I am using the library the wrong way?
I read about Iconify but that won't help in my scenario.

**Comment by MrGrigri** [comment]
We are pushing for the `@mdi/svg` NPM repo instead of using the font. There are several ways to implement SVGs in web pages on our dev [site](https://dev.materialdesignicons.com/getting-started)

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/guide/webfont-alternatives

We *HIGHLY* recommend not using the webfont. We really just provide it for legacy reasons. You should really be using `@mdi/js` or `@mdi/svg`.

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/guide/iconify For iconify it's documented here.

**Comment by Waleedov** [comment]
I wish there was another way than using Iconify, using their API servers (relying on external servers) isn't ideal.

**Comment by Templarian** [comment]
Yeah, we'll be building out more docs and examples to make the transition easier for users. Our public CDN is very fast https://cdn.materialdesignicons.com/4.2.95/ but it's a heavy payload.

Let us know what you end up going with. It's interesting to hear how others handle this. For those using frameworks it's easy enough to switch to `@mdi/js`, but for CMS/blogs/etc the webfont is easy to use.

**Comment by Waleedov** [comment]
I still think a webfont is the best option for many people including me. 

How about providing a service like this:
http://fontello.com/
Very intelligent, you pick the icons and then you download the webfont for it!

**Comment by CoDEmanX** [comment]
Or you use mdi/js, let your bundler tree-shake it and it will include only what is necessary, without you having to go through the trouble of hand-picking which icons you need...
