### ISSUE TITLE
balcony icon

### ISSUE THREAD

**Issue by Ziltosh** [Templarian/MaterialDesign#4378]
Hi,

I made an app and I need a balcony icon.

Thank you for this awesome library.

I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Mobile app on real estate.

## Examples

https://www.flaticon.com/free-icons/balcony

**Comment by PeterShaggyNoble** [comment]
Examples from Icons8:

[![balcony](https://user-images.githubusercontent.com/15157491/64166401-ef530380-ce3e-11e9-9ca9-29032b7ff68c.png)](https://icons8.com/icon/set/balcony/material)[![balcony-outline](https://user-images.githubusercontent.com/15157491/64166552-3b05ad00-ce3f-11e9-9cf3-48332132f450.png)](https://icons8.com/icon/set/balcony/material-outlined)

**Comment by goyney** [comment]
[![balcony](https://materialdesignicons.com/icon/balcony)](https://materialdesignicons.com/icon/balcony)
