### ISSUE TITLE
helmet icon

### ISSUE THREAD

**Issue by Ziltosh** [Templarian/MaterialDesign#4379]
Hi,

I searched a helmet icon but without success.

Thank you.

I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Real estate mobile app.

## Examples

https://www.flaticon.com/free-icon/helmet_2028052#term=helmet&page=1&position=39

**Comment by goyney** [comment]
[![hard-hat](https://materialdesignicons.com/icon/hard-hat)](https://materialdesignicons.com/icon/hard-hat)

Alias added.
