### ISSUE TITLE
bash

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4381]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/64032097-fc05ed80-cb06-11e9-9c91-352979ea3b7e.png)

## Zip Download

[bash.zip](https://github.com/Templarian/MaterialDesign/files/3560513/bash.zip)

**Comment by goyney** [comment]
[![bash](https://materialdesignicons.com/icon/bash)](https://materialdesignicons.com/icon/bash)
