### ISSUE TITLE
No mdi:hexagon-multiple-outline icon on Github

### ISSUE THREAD

**Issue by Spirituss** [Templarian/MaterialDesign#4383]
Github set of MDI icons doesn't have mdi:hexagon-multiple-outline icon while the site shows it. Could you explain the difference between these two sources?

Additional details can be found here:
https://github.com/home-assistant/home-assistant/issues/26294

**Comment by PeterShaggyNoble** [comment]
`hexagon-multiple-outline` will be released in v4.3.95 which is currently being prepped for release and should be available in the next few days.

Note, though, that we cannot guarantee it's availability in HA in the same timeframe as they will need to update the version they're using, which is beyond our control.

**Comment by Spirituss** [comment]
@PeterShaggyNoble Have it been added yet into the last HA release (0.99)?
