### ISSUE TITLE
Icon size is quite inconsistent

### ISSUE THREAD

**Issue by AlexSHoffman** [Templarian/MaterialDesign#4384]
### Demonstration on Codepen: 
https://codepen.io/x84733/pen/aboyEaR?editors=1000

![image](https://user-images.githubusercontent.com/13764106/64063887-597f6480-cc03-11e9-97a7-cc11ddc73fe5.png)

**Comment by Templarian** [comment]
https://material.io/design/iconography/system-icons.html#grid-keyline-shapes

Icons follow these proportions so they view nicely in horizontally and vertically lists.

If a specific icon does not follow this though, please let us know by opening an issue.

**Comment by CoDEmanX** [comment]
In particular, the icons are designed
- for a 24 x 24 dp grid (with a 2dp of padding)
- for viewing at 100% scale (to be legible at 24x24 pixels)
- to be pixel-perfect (on grid)
- with consistent stroke width of 2dp

There are exceptions to some of these guidelines, but a consistent optical size / weight is not a goal. You would either have to shrink or grow icons - ruining pixel accuracy and causing blurriness - or use different proportions - not utilizing the 20x20 live area and potentially leading to odd looking icons.

![grafik](https://user-images.githubusercontent.com/1309249/64103574-d1b86800-cd72-11e9-8a2d-9e8dd00e6fc8.png) ![grafik](https://user-images.githubusercontent.com/1309249/64103498-b2213f80-cd72-11e9-8a32-fbbd99c70a4a.png)

**Comment by AlexSHoffman** [comment]
@CoDEmanX I see, thanks for explaining it
