### ISSUE TITLE
account-cancel

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4385]
Related to #2632, I have a real use-case of account-cancel in my UI where we specifically need to express that the **account** is suspended (and that it is not another functionnality or capability of the user that is prevented). Maybe it is an edge case, but I share the icons just in case.

## Preview
![image](https://user-images.githubusercontent.com/6012554/64117897-a47db100-cd96-11e9-8d18-9f16dcebbd0f.png)
![image](https://user-images.githubusercontent.com/6012554/64117927-b52e2700-cd96-11e9-8578-f9ed06875c3f.png)

## Zip Download
[account-cancel.zip](https://github.com/Templarian/MaterialDesign/files/3566208/account-cancel.zip)

**Comment by CoDEmanX** [comment]
Looks a little strange to me without a gap between the user silhouette and the modifier. Wouldn't `account-off` work?

![grafik](https://user-images.githubusercontent.com/1309249/64132197-52f11880-cdce-11e9-8f4e-4d00f69e2734.png)

**Comment by qnp** [comment]
You are right. Can close this issue.
