### ISSUE TITLE
rolling shades icon request

### ISSUE THREAD

**Issue by chadlyy** [Templarian/MaterialDesign#4386]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
Please do not remove the template when adding an icon issue (edited it back in). 👍

**Comment by chadlyy** [comment]
sorry :(

**Comment by PeterShaggyNoble** [comment]
Are you looking for the `blinds-*` icons? If not, can you please provide some detail and an exmaple of what you are looking for?

[![blinds](https://user-images.githubusercontent.com/15157491/64163254-d0517300-ce38-11e9-9413-38d078178463.png)](https://materialdesignicons.com/icon/blinds)[![blinds-open](https://user-images.githubusercontent.com/15157491/64163410-19092c00-ce39-11e9-8d08-1757023aaacb.png)](https://materialdesignicons.com/icon/blinds-open)

**Comment by chadlyy** [comment]
I am using that for now but looking for something a more modern looking. I
have automated rolling shades no string attached. Was hoping for something
cooler. :)

**Comment by goyney** [comment]
And what would that look like exactly?

**Comment by chadlyy** [comment]
Maybe an outline of a window, a round roller at the top and a shade 1/4 the
way down and another almost all the way down?  (Similar to blinds but with
a window outline so it's easier to tell what it is? )

**Comment by goyney** [comment]
[![roller-shade](https://materialdesignicons.com/icon/roller-shade)](https://materialdesignicons.com/icon/roller-shade)[![roller-shade-closed](https://materialdesignicons.com/icon/roller-shade-closed)](https://materialdesignicons.com/icon/roller-shade-closed)

**Comment by alexanderlindstrom** [comment]
The roller shade icon should be more open, similar to the blinds example above. They are now to similar to look at a glance.
