### ISSUE TITLE
book<-modifiers>-multiple-outline

### ISSUE THREAD

**Issue by freakbite** [Templarian/MaterialDesign#4387]
A version of book multiple outline would be nice, since we use mdi-book-outline in the same page.

**Comment by freakbite** [comment]
As the topic says, it would be nice if the outline version of multiple book existed .

**Comment by MrGrigri** [comment]
I had to extend the book outside the 2-pixel padding to make it work. And I added the modifiers as well.

![book-multiple-outline](https://user-images.githubusercontent.com/4528551/64183094-8cee0900-ce26-11e9-9ba4-4788d6ab4169.png) ![book-minus-multiple-outline](https://user-images.githubusercontent.com/4528551/64183143-a2633300-ce26-11e9-8e32-8b0d874518b8.png) ![book-minus-multiple-outline](https://user-images.githubusercontent.com/4528551/64183170-b0b14f00-ce26-11e9-9d5f-d721ebc36b41.png) ![book-remove-multiple-outline](https://user-images.githubusercontent.com/4528551/64183213-c6bf0f80-ce26-11e9-92f8-9af01f8d78bc.png)

---
#### Files

[book-multiple-outline.zip](https://github.com/Templarian/MaterialDesign/files/3570016/book-multiple-outline.zip)

**Comment by goyney** [comment]
Wow, we really did the modifiers like that for the books instead of our cutout? I really don't like these, nor do I like the filled versions we currently have.

Perhaps we should update them all to use our proper modifier cutout?

**Comment by JamesCoyle** [comment]
The internal modifiers are consistent with other icons which have large areas of filled space such as the file and folder icons.

I'm not sure why the plus symbol is so different from our other icons though. I feel we should update them to be consistent.

[![](https://materialdesignicons.com/icon/file-plus)](https://materialdesignicons.com/icon/file-plus)[![](https://materialdesignicons.com/icon/book-plus)](https://materialdesignicons.com/icon/book-plus)

![image](https://user-images.githubusercontent.com/10384436/64186543-ee35cc80-ce66-11e9-8f80-d7d60bf48421.png)

**Comment by freakbite** [comment]
Not sure if all that would delay the icon release, but if it does we'd be happy with getting this version to start with and getting an updated one later.

**Comment by MrGrigri** [comment]
Specifically, on these, the larger modifier doesn't fit with it being inside. We might consider updating them to the cut-out.

![image](https://user-images.githubusercontent.com/4528551/64188194-2c16fe80-ce2f-11e9-9c68-e8498444d4e5.png) ![image](https://user-images.githubusercontent.com/4528551/64188226-3afdb100-ce2f-11e9-931b-a17fe8d72f9a.png) ![image](https://user-images.githubusercontent.com/4528551/64188261-4d77ea80-ce2f-11e9-9728-ff4ba907c935.png) ![image](https://user-images.githubusercontent.com/4528551/64188294-5e286080-ce2f-11e9-819d-6ff2bfffe3d8.png)

---

### Files

[book-multiple-outline.zip](https://github.com/Templarian/MaterialDesign/files/3570310/book-multiple-outline.zip)

**Comment by MrGrigri** [comment]
@freakbite, the SVGs are available here in this issue.

Since we're changing the look of the `book-multiple`, I would suggest not updating these until the next major release to stay consistent.

**Comment by goyney** [comment]
[![book-multiple-outline](https://materialdesignicons.com/icon/book-multiple-outline)](https://materialdesignicons.com/icon/book-multiple-outline)[![book-plus-multiple-outline](https://materialdesignicons.com/icon/book-plus-multiple-outline)](https://materialdesignicons.com/icon/book-plus-multiple-outline)
[![book-minus-multiple-outline](https://materialdesignicons.com/icon/book-minus-multiple-outline)](https://materialdesignicons.com/icon/book-minus-multiple-outline)[![book-remove-multiple-outline](https://materialdesignicons.com/icon/book-remove-multiple-outline)](https://materialdesignicons.com/icon/book-remove-multiple-outline)

Note: `book-multiple-outline` replaced `quicktime`. `book-plus-multiple-outline` replaced `shopify`. `book-minus-multiple-outline` replaced `slackware`. `book-remove-multiple-outline` replaced `square-inc`. All in the v5.0 release.
