### ISSUE TITLE
Drive / disk / storage icon

### ISSUE THREAD

**Issue by AlexSHoffman** [Templarian/MaterialDesign#4388]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Examples
Fontawesome has a nice looking outlined icon that represents a storage device. 

MDI should have a similar icon, maybe even a few different variations of it (e.g. 2 drives on top of each other to represent "server" or "cloud" storage)

Here's the preview:
https://fontawesome.com/icons/hdd?style=regular

![image](https://user-images.githubusercontent.com/13764106/64176100-600d1680-ce65-11e9-9ca5-932c55927cd3.png)

**Comment by MrGrigri** [comment]
We cannot add icons with perspective per Material Design guidelines; with few exceptions. We already have a `harddisk` icon, but not a `harddisk-outline` icon. As far as stacked drives, we have the `server` icon. Would that work?

![harddisk](https://materialdesignicons.com/icon/harddisk) ![server](https://materialdesignicons.com/icon/server)

**Comment by AlexSHoffman** [comment]
@MrGrigri I didn't know perspective is considered something unacceptable, especially when Google themselves have an icon that is almost identical to the one I specified in the issue

![image](https://user-images.githubusercontent.com/13764106/64184238-d9ac0100-ce73-11e9-94eb-4f3b9176513f.png)

**Comment by goyney** [comment]
[It's considered unacceptable by Google.](https://material.io/design/iconography/system-icons.html#system-icon-metrics)

![Screen Shot 2019-09-03 at 10 57 51 AM](https://user-images.githubusercontent.com/1015040/64184599-b06e7f00-ce39-11e9-9d4f-925cb0d1b5a5.png)

Also, not sure the `youtube-subscription` icon shows any perspective; it shows a stack.

**Comment by AlexSHoffman** [comment]
@goyney I don't think that's a fair comparison, the `youtube-subscription` icon indeed represents a stack but it's in perspective. Here's how a stack looks in orthographic view (without perspective):

![1](https://user-images.githubusercontent.com/13764106/64185612-2264b980-ce76-11e9-9c40-e0b584f23171.png)

**Comment by goyney** [comment]
How do you know those aren't smaller things behind it? 🤔 😝 

Regardless, we follow Google's guidelines, even if they sometimes do not.

**Comment by AlexSHoffman** [comment]
@goyney well, how do you know that the drive I specified is not just shaped in a triangular design? 😏 
Let's hear other people out before closing the issue though.

**Comment by MrGrigri** [comment]
> We cannot add icons with perspective per Material Design guidelines; **with few exceptions**.

That 'with few exceptions' statement was in reference to a few icons that either Google has created or ones that couldn't be done otherwise (i.e. `stadium-variant`).

> @goyney well, how do you know that the drive I specified is not just shaped in a triangular design? 😏 Let's hear other people out before closing the issue though.

Icons are meant to be supplementary. Standard UX patterns suggest using icons alone only if the meaning is absolutely clear (i.e. a like or heart toggle button). We have strict rules amongst before adding an icon. The `consider-closing` label was added as a precaution and not a kill-all. 

If you are needing a `harddisk-outline` icon, then create a new request specifically for that one.

**Comment by goyney** [comment]
We've decided that we're not interested in breaking the perspective rule, especially considering we have other icons that already fit the proposed use case. Thanks for your suggestion.
