### ISSUE TITLE
View SVG does not include xmlns

### ISSUE THREAD

**Issue by dlew** [Templarian/MaterialDesign#439]
If you click "View SVG" on an icon, it shows SVG without an xmlns. For example, this is "delete":

```
<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="#000000" d="M19,4H15.5L14.5,3H9.5L8.5,4H5V6H19M6,19A2,2 0 0,0 8,21H16A2,2 0 0,0 18,19V7H6V19Z" />
</svg>
```

This causes it to be an invalid SVG unless you are including it inline in HTML, which probably isn't the case for Android.

This is causing problems with [Victor](https://github.com/trello/victor) as it's failing to rasterize SVGs as a result: https://github.com/trello/victor/issues/19

**Comment by Templarian** [comment]
Instead of selecting View SVG (which is targeted for web developers), please select the download SVG option instead (either should work for your use case).

![image](https://cloud.githubusercontent.com/assets/338885/8209573/44b7f6e8-14d3-11e5-9898-756ae3c94b3c.png)

**Comment by dlew** [comment]
I'm not having an issue; the issue is that other people are misinterpreting the website and thinking that "view SVG" is good enough for standalone files.

If you're going to keep "view SVG" for web developers only, you should at least make it clear on the site, because I'm getting issue requests on my SVG-based project due to people not understanding your UX.

**Comment by Templarian** [comment]
Oh. Yea, I can rename it . "View SVG for Web", but that won't keep those new to SVG from messing it up.

What I could do is add 2 tabs one that reads "For Web" and another that reads "SVG File Contents". With little explanations of their use?

**Comment by Templarian** [comment]
I'll add a download button for the SVG file on that modal window also.

**Comment by dlew** [comment]
I think that would help out, thanks!

**Comment by Templarian** [comment]
Done! :smile: 

The SVG viewer has tabs and download links. Hopefully this clears things up. Let me know if they still have confusion and I can try and make it more obvious.

I added download links for the XAML and the Vector Drawable viewer also.

**Comment by ciskeboekelo** [comment]
Great!
Op 18 jun. 2015 06:40 schreef "Austin Andrews" <notifications@github.com>:
