### ISSUE TITLE
book-multiple-<modifiers>

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4390]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

As per #4387, I am creating a breaking change to the `book-multiple` modifiers to be a cut-out.

## Preview

![image](https://user-images.githubusercontent.com/4528551/64189507-a34d9200-ce31-11e9-9d45-e114faf644fe.png) ![image](https://user-images.githubusercontent.com/4528551/64189533-b06a8100-ce31-11e9-892b-fb2d67888909.png) ![image](https://user-images.githubusercontent.com/4528551/64189594-d2fc9a00-ce31-11e9-8461-0500664da13a.png)

## Zip Download

[book-multiple.zip](https://github.com/Templarian/MaterialDesign/files/3570378/book-multiple.zip)

**Comment by goyney** [comment]
Updated.
