### ISSUE TITLE
Golf Cart Icon

### ISSUE THREAD

**Issue by mcaminiti** [Templarian/MaterialDesign#4391]
I have:

- [X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
Looking for a golf cart icon to be used in Home Assistant or other applications for reference to golf cart chargers and status.  

## Examples

Examples: 
https://d30y9cdsu7xlg0.cloudfront.net/png/5255-200.png
https://image.flaticon.com/icons/png/512/335/335072.png

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/64267384-8a0d1a00-cef3-11e9-8f8f-5d88d96eff2e.png)


---

### Files

[golf-cart.zip](https://github.com/Templarian/MaterialDesign/files/3575178/golf-cart.zip)

**Comment by mcaminiti** [comment]
Great! Thanks for the fast work!

**Comment by goyney** [comment]
[![golf-cart](https://materialdesignicons.com/icon/golf-cart)](https://materialdesignicons.com/icon/golf-cart)
