### ISSUE TITLE
Indian Rupees Icon

### ISSUE THREAD

**Issue by developerConjoinix** [Templarian/MaterialDesign#4393]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by PeterShaggyNoble** [comment]
That icon already exists and is aliased as `rupee`:

[![currency-inr](https://user-images.githubusercontent.com/15157491/64253108-76be7680-cf14-11e9-8e21-ceaa7e081fd8.png)](https://materialdesignicons.com/icon/currency-inr)
