### ISSUE TITLE
Unsharp "Plus" Icon, even on materialdesignicons Site

### ISSUE THREAD

**Issue by Subwaytime** [Templarian/MaterialDesign#4394]
Hey there,

just by testing i found out that the "Plus" Icon (used via svg) is blurry/unsharp in Medium Size (36px). Its the normal "Plus" by Google.

Also seen on the https://materialdesignicons.com/ Site.

Viewed with Firefox: 68.0.2 (64 Bit)

![Screenshot_2019-09-04 Material Design Icons](https://user-images.githubusercontent.com/7354569/64261512-ef313180-cf2c-11e9-8603-c31f4302be6a.png)

Greetings

**Comment by goyney** [comment]
This is not an issue with the icon; the icon is perfectly on the grid:

![image](https://user-images.githubusercontent.com/1015040/64261764-035c3b00-cefb-11e9-920b-c9690e8902ae.png)

Also, all whole numbers: `M19,13H13V19H11V13H5V11H11V5H13V11H19V13Z`.

**Comment by Subwaytime** [comment]
Just updated to newest Firefox Version, same Result. 
Any Way to fix this on Firefox?
Seems a little off.

**Comment by JamesCoyle** [comment]
This is gonna be the case for most of the thinner icons. Each grid square is scaled by 1.5 so a lot of the on-grid pixels end up on grid boundaries for 36dp icons.

The actual path of the plus icon takes up a 14x14dp square. When this is scaled up to 36dp, the path takes up 14dp*1.5=21dp. Now 36dp minus that 21dp gives 15dp which means the space either side of the icon is 7.5dp causing the icon path to straddle the gridlines. The 2dp lines end of the original icon end up being 3dp lines at 36dp with half a pixel being added to either side of the line causing the icon to appear blurred.

On high DPI displays this shouldn't matter assuming each device pixel is 4 actual pixels but for low DPI displays you either have to live with the issue, add in an extra bit of padding somewhere to optically re-align the icon, or stick to using multiples of two of the base icon size.
