### ISSUE TITLE
cdn.materialdesignicons.com Is down 

### ISSUE THREAD

**Issue by vcantu** [Templarian/MaterialDesign#4395]

**Comment by Templarian** [comment]
@vcantu Not related to that issue. It's an issue with our CDN provider. Out of my hands at the moment. Some regions work some don't right now (Chicago works, but it will fail in San Francisco for instance).

https://status.maxcdn.com/

**Comment by PeterShaggyNoble** [comment]
Thanks for the report, @vcantu. It looks like MaxCDN are having some localised issues. See https://status.maxcdn.com/ for updates.

(Note that this is unrelated to the issue in #3212)

**Comment by Templarian** [comment]
Please try again. Regions seem to be restored now.

**Comment by vcantu** [comment]
It appears to be back up, thanks for the prompt response!
