### ISSUE TITLE
Update Android Icon

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4396]
Google have [recently rebranded Android](https://blog.google/products/android/evolving-android-brand/), including a change of logo/icon so we'll need to update ours to match. An SVG can be found on their [brand guidelines page](https://source.android.com/setup/start/brands#robot-android).

**Comment by PeterShaggyNoble** [comment]
Took a stab at this but I don't think it worked out too well; the antennae go missing at 24*24.

[![android](https://user-images.githubusercontent.com/15157491/64327164-25b98b80-cfc3-11e9-8c7e-8c4ecda1fa02.png)](https://github.com/Templarian/MaterialDesign/files/3578359/android.zip)

**Comment by PeterShaggyNoble** [comment]
With better optimisation of the path, resulting in 9 less points:

[![android](https://user-images.githubusercontent.com/15157491/64339894-d97b4500-cfdc-11e9-8540-0df6df55b6e8.png)](https://github.com/Templarian/MaterialDesign/files/3579159/android.zip)

**Comment by goyney** [comment]
[![android](https://materialdesignicons.com/icon/android)](https://materialdesignicons.com/icon/android)
