### ISSUE TITLE
Program Icon Suggestion

### ISSUE THREAD

**Issue by CraftedPvP** [Templarian/MaterialDesign#4398]
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm making my own file explorer, for fun, and I want to show the icon of an executable (.exe) and (.dll) and its counterparts.

## Examples

![image](https://user-images.githubusercontent.com/20311462/64303071-f30a9580-cfb8-11e9-9715-d47923e768b6.png)
![image](https://user-images.githubusercontent.com/20311462/64303101-3402aa00-cfb9-11e9-97be-f92566110fde.png)

**Comment by goyney** [comment]
Not really a fan of included `EXE` on an file icon, nor do I think there is room for that. Any other ideas?

As for the second one, would `location-enter` work?
[![location-enter](https://materialdesignicons.com/icon/location-enter)](https://materialdesignicons.com/icon/location-enter)

**Comment by JapanYoshi** [comment]
Possibly ``console`` + ``play``?

**Comment by Templarian** [comment]
Yeah, `exe` is old school even in the Windows world. MSIX is their package format now-a-days. A more generic console box play would make sense as @JapanYoshi suggested.

- [ ] `application-play` maybe is a good name.

**Comment by CoDEmanX** [comment]
The format extension for (portable) executables is still exe though.

**Comment by CraftedPvP** [comment]
> Possibly console + play?

I went ahead and used `console`. Thanks
