### ISSUE TITLE
www.materialdesignicons.com shows coming soon page.

### ISSUE THREAD

**Issue by theharshin** [Templarian/MaterialDesign#4399]
**Works** https://materialdesignicons.com/ 
**Works** https://www.materialdesignicons.com/
**Works** http://materialdesignicons.com/
**Does not Work** http://www.materialdesignicons.com/

**Comment by Templarian** [comment]
Ironically our web server is down for maintenance by the host. So can't modify anything right now until it gets back.

**Comment by Templarian** [comment]
I think this was just due to our server outage that lasted quite a while. It was a little random at first then knocked everything offline.
