### ISSUE TITLE
A section with "new icons" or "recently added"

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#44]
Sometimes it's kinda annoying to find new icons.

**Comment by Templarian** [comment]
Started coding this feature. It actually works a bit differently than simply recently added, but definitely gives more details on changes.

It will view more like a feed with comments. For instance:

```text
[webfont] Generated webfont v0.7.73-alpha    Jan, 21 2015 11:56 PM
[glyph]   Modified the description           Jan 21, 2015 11:54 PM
[glyph]   Renamed                            Jan 21, 2015 11:53 PM
[glyph]   Created                            Jan 21, 2015 11:52 PM
```

Each time will have a permalink icon next to it for easy reference.

**Comment by Templarian** [comment]
http://materialdesignicons.com/history

Still styling it and wiring up the back end, but this page will contain all the changes.

**Comment by Templarian** [comment]
This page is now live. It will evolve over time, but features described in this issue have been completed.

Enjoy! :smile:

**Comment by matthew2402** [comment]
Awesome!!! Good job man
