### ISSUE TITLE
status-pending, status-accepted, status-rejected

### ISSUE THREAD

**Issue by jmj4you** [Templarian/MaterialDesign#440]
Could you please make icons for showing status as PENDING, ACCEPTED and REJECTED ?.

**Comment by CoDEmanX** [comment]
How would this look like?
Don't the following work?
https://materialdesignicons.com/icon/checkbox-blank-circle-outline
https://materialdesignicons.com/icon/checkbox-marked-circle-outline
https://materialdesignicons.com/icon/close-circle-outline

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback from OP.
