### ISSUE TITLE
Release date for "mdi-file-table-box-outline" icon

### ISSUE THREAD

**Issue by oliviergaucher** [Templarian/MaterialDesign#4401]
Hi there,

I see on https://materialdesignicons.com/ the icon `mdi-file-table-box-outline` icon.
Can you tell me when it will be made available? (It is not part of `4.2.95` version)

<img width="535" alt="Pasted_Image_9_6_19__9_48_AM" src="https://user-images.githubusercontent.com/3456675/64393245-80b6b580-d08b-11e9-997d-c62e38ef4875.png">

Thank you very much.
Olivier

**Comment by goyney** [comment]
Please see the milestone on the original issue: https://github.com/Templarian/MaterialDesign/issues/4205

It'll be part of the 4.3 release which should be released any day.

**Comment by oliviergaucher** [comment]
> Please see the milestone on the original issue: #4205
> 
> It'll be part of the 4.3 release which should be released any day.

Awesome, thank you very much! (I didn't think to search on closed issues, will do next time)

**Comment by Templarian** [comment]
Ironically I'm publishing 4.3.95 right now. `@mdi/svg` and `@mdi/font` are out. Other are going out in a few minutes.
