### ISSUE TITLE
All icons from Simple Icons

### ISSUE THREAD

**Issue by SumNeuron** [Templarian/MaterialDesign#4402]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

Various common brands / libraries etc such as Rollup, Jupyter, StackOverflow, etc

https://simpleicons.org/

## Examples

Include any example images so we know what the icon should look like.

https://simpleicons.org/

**Comment by JamesCoyle** [comment]
We are actively moving away from including brand icons and are recommending people use simple icons for brands going forward.
