### ISSUE TITLE
SVG font missing from webfont download

### ISSUE THREAD

**Issue by code-mc** [Templarian/MaterialDesign#4403]
There used to be a materialdesignicons-webfont.svg inside the fonts directory, there no longer is. There also still is a mention of the SVG font next to the download button which leads me to believe it was removed by accident?

**Comment by goyney** [comment]
I believe this was intentionally removed when we updated the webfont generation tooling for two reasons:

1. We want people to stop using the webfont. There are over 4500 icons in the library now and all the assets are a burden to anyone who has to download them to see a few icons. There are dedicated libraries for SVGs (@mdi/svg) and JavaScript (@mdi/js) so you are only using and including the icons you need.

2. The SVG webfont file was *significantly* larger than the WOFF(2) versions, which all major and modern browsers support. If you _must_ use the webfont, you should really be using WOFF(2).

The main reason we still offer the @mdi/font package is for those who need to use in on the Desktop by installing. We understand many people still use it on the web to our dismay, but we highly recommend you do not.

I will let @Templarian correct me if I'm wrong on either of these. However, I would think it is fair to say that we will not be including the SVG variant any longer.

**Comment by code-mc** [comment]
Alright, thanks. I mostly used it to parse the mappings from identifier to unicode codepoint. The same can be achieved with the css files so I'll have a go at that instead.

**Comment by Templarian** [comment]
@code-mc You could use the `meta.json` in the `@mdi/svg` package. It's also in the CDN.

- http://cdn.materialdesignicons.com/4.4.95/meta.json
- https://github.com/Templarian/MaterialDesign-SVG
- @mdi/svg

**Comment by Templarian** [comment]
We provide a node utility also at `@mdi/util` that makes it easier to work with `@mdi/svg`.

The `@mdi/font-build` can also generate the svg font.

**Comment by PeterShaggyNoble** [comment]
See #4166, [MaterialDesign-Webfont#49](https://github.com/Templarian/MaterialDesign-Webfont/issues/49), [MaterialDesign-Webfont#50](https://github.com/Templarian/MaterialDesign-Webfont/issues/50) and, for details on how to generate the webfont with the SVG file included if you really need it, [MaterialDesign-Webfont#55](https://github.com/Templarian/MaterialDesign-Webfont/issues/55).

**Comment by Templarian** [comment]
Updated the webfont guide to not mention the `.svg`. Added a section at the bottom to explain how to generate it.

http://dev.materialdesignicons.com/getting-started/webfont
