### ISSUE TITLE
Storefront-closed

### ISSUE THREAD

**Issue by PDekker** [Templarian/MaterialDesign#4404]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'd like to have an icon for a closed state for device class "awning" in Home-Assistant
https://www.home-assistant.io/components/cover/

the "storefront" icon is perfectly usable for an open state. 
A storefront-closed might be a perfect addition.

## Examples

https://github.com/Templarian/MaterialDesign/issues/3939

**Comment by goyney** [comment]
What would a "closed" state look like? An awning is either extended out or not we cannot show perspective in icons. Please provide some examples of what this might look like.

**Comment by TheNr1Guest** [comment]
I also would like to see some sort of icon to show this in Home Assistant! Instead of the storefront, can't we add the awning to the home icon so that we can use the home icon for the closed state and the home+awning icon for the open state?

**Comment by CoDEmanX** [comment]
We could add off-variants for the storefront icon...

![grafik](https://user-images.githubusercontent.com/1309249/73503861-b6a75e00-43cd-11ea-8d77-89680bb52acf.png) ![grafik](https://user-images.githubusercontent.com/1309249/73503888-caeb5b00-43cd-11ea-9964-189b4c9df52b.png)

Related to #4771

**Comment by Templarian** [comment]
@CoDEmanX Can you add those to the other issue so we can add them at the same time.
