### ISSUE TITLE
Power Amplifier (non Marshall...) and -off variant(s)

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4405]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

Looking for a Power Amplifier icon , more along the lines of mdi:audio-video, to be used for a home audio setup in the home theater.

current mdi:amplifier is an On stage guitar amp, more resembling a speaker than an Amp really
## Examples

Include any example images so we know what the icon should look like.

not really many available icons around, most of them have too many bells and whistles for my taste:
![Schermafbeelding 2019-09-09 om 10 30 10](https://user-images.githubusercontent.com/33354141/64515491-f9687c80-d2ec-11e9-9099-93addecf4007.jpg)

I am looking for an icon, as clean as possible, simply resembling the box on the small feet, with maybe a single dot in the middle to indicate an on/off led.

Don't even need a turning wheel. to give you a real life idea:

![Schermafbeelding 2019-09-09 om 10 33 57](https://user-images.githubusercontent.com/33354141/64515697-5bc17d00-d2ed-11e9-8cce-8821523b3a6c.jpg)

secondly: I'd love an -off variant, both for the mdi:audio-video, and hopefully for the new mdi:power-ampfilier...

maybe have a look at mdi:radiator-disabled, and move the feet a bit inside, like on the mdi:audio-video.

would even be quite cool, resembling the cooling fins on the amps ;-)
thanks for considering

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/64535877-1057a080-d2e6-11e9-84f3-b9449db53313.png)
[audio-video.svg.zip](https://github.com/Templarian/MaterialDesign/files/3590764/audio-video.svg.zip)

**Comment by goyney** [comment]
I think the other variant you're requesting is too niche as it is simply changed very minor details of the base `audio-video` icon.

**Comment by Mariusthvdb** [comment]
thanks for the off variants! much appreciated.

about the power-amp being niche: the difference would be significant tbh.

it would really help if the round volume knob would be taken out, as a key visual indicator and difference between this and other audio components.

It could be even further simplified (the audio-video is a crowded icon...) and only needs 1 power-button. no other selectors as the audio-video has, nor a display.

all in all, a completely different icon, only sharing the chassis ;-)
hope you'd reconsider based on my closer explanation?

**Comment by goyney** [comment]
[![audio-video-off](https://materialdesignicons.com/icon/audio-video-off)](https://materialdesignicons.com/icon/audio-video-off)

**Comment by Mariusthvdb** [comment]
let me please express my gratitude on all added icons -off and -alert love created on my request! thanks, and so appreciated!
