### ISSUE TITLE
amplifier-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4406]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

I am using the mdi:amplifier for my powered subwoofer, since this is what resembles best among the current icon (next to speaker)

would love to have an -off icon for obvious reasons

## Examples

Include any example images so we know what the icon should look like.

the default diagonal line would suffice perfectly
thanks for considering!

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/64535713-c1117000-d2e5-11e9-9f4a-c7d518bcd334.png)
[amplifier.svg.zip](https://github.com/Templarian/MaterialDesign/files/3590757/amplifier.svg.zip)

**Comment by goyney** [comment]
[![amplifier-off](https://materialdesignicons.com/icon/amplifier-off)](https://materialdesignicons.com/icon/amplifier-off)
