### ISSUE TITLE
toaster-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4407]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

context seems simple: turn-off the toaster and use the -off icon
so cool we now have a toaster icon, thanks!
## Examples

Include any example images so we know what the icon should look like.

the diagonal line will be perfect!

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/64541802-83661480-d2f0-11e9-87ab-f38a802d656e.png)
[toaster.svg.zip](https://github.com/Templarian/MaterialDesign/files/3591144/toaster.svg.zip)

**Comment by Mariusthvdb** [comment]
yes!
you're fast ;-)
thanks.

**Comment by goyney** [comment]
[![toaster-off](https://materialdesignicons.com/icon/toaster-off)](https://materialdesignicons.com/icon/toaster-off)
