### ISSUE TITLE
searching for icons goes blank after entering a dash and a next character

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4408]
Didnt know where to ask, but as of late (I think, didnt notice before tbh) whenever I enter a dash in the searchbar followed by a next character, the result field goes blank:

seaching for weather icons:
still ok using `weather-`
![Schermafbeelding 2019-09-09 om 17 01 24](https://user-images.githubusercontent.com/33354141/64542328-ac53cd00-d323-11e9-883c-4a6e08d7a53e.jpg)

blank after `weather-pa` :

![Schermafbeelding 2019-09-09 om 17 01 15](https://user-images.githubusercontent.com/33354141/64542399-cab9c880-d323-11e9-83c2-4095e692d1fe.jpg)

missing out on all `weather-partly-` icons

same goes for all other combinations, eg the -off variants. 

if one only enters the dash and the following characters things change:

![Schermafbeelding 2019-09-09 om 17 05 23](https://user-images.githubusercontent.com/33354141/64542578-179d9f00-d324-11e9-98f2-53cd2f7fbb28.jpg)

but still not 100% correct. Missing out on some, or render yet again an empty result after adding a few more characters in the search bar

Since this is a heavily used functionality on the main site, please have a look what's amiss?

**Comment by goyney** [comment]
Can confirm, this happens to me as well on Chrome.

**Comment by Mariusthvdb** [comment]
using safari Mac here

**Comment by Templarian** [comment]
You mean I shouldn't make updates to the site without testing. Next time... maybe.

Fixed.

Thanks @Mariusthvdb! This was from a change a week ago, surprised no one reported it until now.
