### ISSUE TITLE
share-circle

### ISSUE THREAD

**Issue by dibarto** [Templarian/MaterialDesign#4409]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As a button to share something onsocial media

## Examples

Like play-circle or pencil-circle, but with a share symbol inside

**Comment by goyney** [comment]
[![share-circle](https://materialdesignicons.com/icon/share-circle)](https://materialdesignicons.com/icon/share-circle)[![reply-circle](https://materialdesignicons.com/icon/reply-circle)](https://materialdesignicons.com/icon/reply-circle)
