### ISSUE TITLE
phone-ring

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4410]
Google's `ring_volume` icons.

[![phone-ring](https://user-images.githubusercontent.com/15157491/64560068-b683c480-d33f-11e9-999c-a0b5d629f1f3.png)](https://fonts.gstatic.com/s/i/materialicons/ring_volume/v1/24px.svg)[![phone-ring-outline](https://user-images.githubusercontent.com/15157491/64560334-3a3db100-d340-11e9-83d4-396a50cb17b2.png)](https://fonts.gstatic.com/s/i/materialiconsoutlined/ring_volume/v1/24px.svg)

**Comment by goyney** [comment]
[![phone-ring](https://materialdesignicons.com/icon/phone-ring)](https://materialdesignicons.com/icon/phone-ring)[![phone-ring-outline](https://materialdesignicons.com/icon/phone-ring-outline)](https://materialdesignicons.com/icon/phone-ring-outline)
