### ISSUE TITLE
fridge-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4411]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

as a signal for power-failure on the fridge....
any fridge variant would do with the diagonal line

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
[![fridge-off](https://materialdesignicons.com/icon/fridge-off)](https://materialdesignicons.com/icon/fridge-off)[![fridge-off-outline](https://materialdesignicons.com/icon/fridge-off-outline)](https://materialdesignicons.com/icon/fridge-off-outline)
[![fridge-alert](https://materialdesignicons.com/icon/fridge-alert)](https://materialdesignicons.com/icon/fridge-alert)[![fridge-alert-outline](https://materialdesignicons.com/icon/fridge-alert-outline)](https://materialdesignicons.com/icon/fridge-alert-outline)
