### ISSUE TITLE
water-boiler-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4412]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

as a signal to power-failure for the water-boiler

please add the diagonal line
## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
[![water-boiler-off](https://materialdesignicons.com/icon/water-boiler-off)](https://materialdesignicons.com/icon/water-boiler-off)[![water-boiler-alert](https://materialdesignicons.com/icon/water-boiler-alert)](https://materialdesignicons.com/icon/water-boiler-alert)
