### ISSUE TITLE
appliances -off for (dishwasher, tumble-dryer, washing-machine)

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4413]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
as a warning signal for power-failure to these main appliances, please add an -off variant using the diagonal line

thanks for considering (hope this 3 in 1 is allowed...)
## Examples

Include any example images so we know what the icon should look like.

**Comment by PeterShaggyNoble** [comment]
This applies to #4411 & #4412 as well: For the use-case you've provided the `alert` modifier would be more appropriate and more consistent with our existing icons. We generally use the `off` modifier to indicate that a device or appliance is off(line).

**Comment by Mariusthvdb** [comment]
I would be most happy with the alert modifier as well on the appliances icons. especially in case of power-failure. Great idea! thanks.

then again, I would love to be able to switch them off manually, and show the -off modifier. It's not always an alert situation and can be a desired situation, switching appliances Off ;-)

**Comment by goyney** [comment]
[![dishwasher-off](https://materialdesignicons.com/icon/dishwasher-off)](https://materialdesignicons.com/icon/dishwasher-off)[![dishwasher-alert](https://materialdesignicons.com/icon/dishwasher-alert)](https://materialdesignicons.com/icon/dishwasher-alert)
[![tumble-dryer-off](https://materialdesignicons.com/icon/tumble-dryer-off)](https://materialdesignicons.com/icon/tumble-dryer-off)[![tumble-dryer-alert](https://materialdesignicons.com/icon/tumble-dryer-alert)](https://materialdesignicons.com/icon/tumble-dryer-alert)
[![washing-machine-off](https://materialdesignicons.com/icon/washing-machine-off)](https://materialdesignicons.com/icon/washing-machine-off)[![washing-machine-alert](https://materialdesignicons.com/icon/washing-machine-alert)](https://materialdesignicons.com/icon/washing-machine-alert)
