### ISSUE TITLE
solar-water-boiler

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4414]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

as title, icon for solar-water-boiler

## Examples

Include any example images so we know what the icon should look like.
we now have a water-boiler, which is kind of cool ;-)
we also have solar-energy. Use them both. 

Would it in any way be possible to have that cornered sun shine on the water-boiler? 

if possible, please create an -off version to come along
thanks for considering!

**Comment by MrGrigri** [comment]
I believe this is too niche for this repo.

**Comment by PeterShaggyNoble** [comment]
I agree with @MrGrigri. A boiler is a boiler, I don't see a use-case for differentiating how it's powered.

Also, were we to add this, we'd open ourselves up to adding a new `solar` modifier and requests to apply it to every device that can be solar powered, which seems incredibly niche to me.

Having said that, if you can provide a convincing use-case for `water-boiler-solar` that can't be served by the base icon, we'll be happy to revisit and reassess this request.

**Comment by Mariusthvdb** [comment]
well, thanks...

about the convincing use-case: next to a heat-pump and solar panels, solar-boilers are among the few appliances available right now for creating a sustainable home. Not sure about the english terminology, but where I live it is called NOM (Null on the Meter).

It would really be very cool if we could reflect that sustainability in our icon-set. I might  be a front runner (never a good thing....), but having said that, I would indeed expect more devices to arrive. Hope they will be served by MDI.
