### ISSUE TITLE
phone-check(-outline)

### ISSUE THREAD

**Issue by julienreszka** [Templarian/MaterialDesign#4415]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Like for email-check displays that email was verified to display that the phone number was verified.

## Examples

https://materialdesignicons.com/icon/email-check
https://materialdesignicons.com/icon/phone

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/64630423-4febbe80-d3b2-11e9-8ccc-176eceec9e14.png) ![image](https://user-images.githubusercontent.com/4528551/64630456-64c85200-d3b2-11e9-8f95-0f46ac7216de.png)

---

#### Files

[phone-check.zip](https://github.com/Templarian/MaterialDesign/files/3596623/phone-check.zip)

**Comment by goyney** [comment]
[![phone-check](https://materialdesignicons.com/icon/phone-check)](https://materialdesignicons.com/icon/phone-check)[![phone-check-outline](https://materialdesignicons.com/icon/phone-check-outline)](https://materialdesignicons.com/icon/phone-check-outline)
