### ISSUE TITLE
beaker half full

### ISSUE THREAD

**Issue by bodeen123** [Templarian/MaterialDesign#4416]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by bodeen123** [comment]
Would be great to have a half full beaker to complete the beaker set

**Comment by MrGrigri** [comment]
Could you please provide your use case for this request. I cannot foresee a need for an icon that represents a beaker that is half full.

**Comment by bodeen123** [comment]
As a rating system. Similar to the star icons and heart icons that have a full half and empty icon

**Comment by goyney** [comment]
Hearts and starts make sense for ratings, a beaker does not. Sorry, but I do not think this is a worthwhile addition.
