### ISSUE TITLE
Elixir language icon

### ISSUE THREAD

**Issue by lobo-tuerto** [Templarian/MaterialDesign#4417]
I have:

- [ x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It's a tech related icon, I usually create blog posts about different tech topics and add an icon for it on the main listing.

## Examples

![Elixir logo](https://elixir-lang.org/images/logo/logo.png)

I think a solid droplet would do it :)

I went ahead and requested a brand icon because I read this:

> We may consider technology-related logo icons based around development (e.g. Webpack) for well-known tools, but these will be done on a case-by-case basis.

Hopefully this is one of those cases.

**Comment by Templarian** [comment]
Yeah, it's fine, but we need to reach out to them and ensure they are fine with their programming language being represented by a solid glyph.

We generally just tweet to the company and wait for someone to respond. If they don't respond we don't add it.

**Comment by Templarian** [comment]
https://twitter.com/templarian/status/1172022237135872000

Now we wait for someone to respond. Many large projects take a while, but we'll keep an eye out.

**Comment by Templarian** [comment]
@lobo-tuerto That's really all the effort we put into getting brands in. If you're able to get their attention somehow let us know. We'll leave the issue opened for a while longer, but it might get closed after some time.

**Comment by lobo-tuerto** [comment]
Thanks, I already tried on the Elixir forum, twitter and directly on the contact form on their page. Hopefully they'll respond.

**Comment by goyney** [comment]
It's been two weeks. Any response? I'm inclined to close this until a point in which we know if we can safely add this.

**Comment by lobo-tuerto** [comment]
No response from them yet :(

**Comment by goyney** [comment]
It's been well over a month now. We're going to close this for now. If any new information is received, please comment back here.
