### ISSUE TITLE
Ballet Icon

### ISSUE THREAD

**Issue by broyuken** [Templarian/MaterialDesign#4418]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I use Home Assistant and have a zone for my daughters ballet class that I would like an icon for.

## Examples

Something like this
https://image.flaticon.com/icons/png/512/93/93925.png
or 
https://stock.adobe.com/images/ballet-icon-ballet-symbol-design-from-museum-collection/229513143

**Comment by PeterShaggyNoble** [comment]
If you're raising the other arm then the angle of the skirt could probably do with being a bit higher to better convey that it's a tutu.

**Comment by broyuken** [comment]
Is there any sort of dance/ballet icon yet? I haven’t seen anything. The one above doesn’t seem to be on mdi

**Comment by lukecarbis** [comment]
I'd like to see this updated too please.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/89363191-9cf91300-d69d-11ea-9ddb-6aa5b664122b.png)
[ballet-shoes.svg.zip](https://github.com/Templarian/MaterialDesign/files/5025680/ballet-shoes.svg.zip)

**Comment by goyney** [comment]
[![human-female-dance](https://materialdesignicons.com/icon/human-female-dance)](https://materialdesignicons.com/icon/human-female-dance)[![shoe-ballet](https://materialdesignicons.com/icon/shoe-ballet)](https://materialdesignicons.com/icon/shoe-ballet)
