### ISSUE TITLE
Venetian / Wooden blinds

### ISSUE THREAD

**Issue by DBuit** [Templarian/MaterialDesign#4419]
I have:

- [x] Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For home assistant i got wooden blinds that i can open and close. I know there are blind icons already but it's not the same kind. i will add a image of the blinds i'm talking about.

would be awesome to have an open and closed icon. i got an example of an icon.

## Examples

This are the blinds: https://dzrlz2ysbzk1i.cloudfront.net/images/products/wood/nile%2050%20taped/pearl%20white/skus/nile-50mm-taped-pearl-white-real%20wood-lifestyle.jpg

i got something from homekit blinds icon that looks nice: 
https://9to5mac.com/wp-content/uploads/sites/6/2018/08/JPEG-image-01148FD58C09-1.jpeg?resize=1024,470

**Comment by DBuit** [comment]
[venetian_blinds.zip](https://github.com/Templarian/MaterialDesign/files/3885899/venetian_blinds.zip)

**Comment by DBuit** [comment]
I made this issue a while ago but i have no experience in making icons but i gave it a try.
Maybe it can still get in if a collaborator can check it out?

### Preview

![preview blinds closed](https://user-images.githubusercontent.com/17079647/69540868-0f9ae600-0f88-11ea-9b6b-028c83081c25.png)
![preview blinds half open](https://user-images.githubusercontent.com/17079647/69540870-10337c80-0f88-11ea-8f42-11b1bc1da757.png)
![preview blindsopen](https://user-images.githubusercontent.com/17079647/69540874-10337c80-0f88-11ea-9f6c-c9990d65a924.png)

### Download
[venetian_blinds.zip](https://github.com/Templarian/MaterialDesign/files/3886574/venetian_blinds.zip)

**Comment by JamesCoyle** [comment]
Icons need to follow the material guidelines as defined here: https://material.io/design/iconography/system-icons.html

**Comment by DBuit** [comment]
@JamesCoyle Wat about these?

### Preview
![preview blinds open material](https://user-images.githubusercontent.com/17079647/69622524-60bae080-1041-11ea-8bdd-3eed432cd45a.png)
![preview blinds half open material](https://user-images.githubusercontent.com/17079647/69622523-60bae080-1041-11ea-8a22-f6c8ac64ac17.png)
![preview blinds closed material](https://user-images.githubusercontent.com/17079647/69622525-61537700-1041-11ea-9479-78c49118aa1a.png)

### Download
[blinds_material.zip](https://github.com/Templarian/MaterialDesign/files/3891381/blinds_material.zip)

**Comment by goyney** [comment]
[![blinds-horizontal](https://materialdesignicons.com/icon/blinds-horizontal)](https://materialdesignicons.com/icon/blinds-horizontal)[![blinds-horizontal-closed](https://materialdesignicons.com/icon/blinds-horizontal-closed)](https://materialdesignicons.com/icon/blinds-horizontal-closed)
