### ISSUE TITLE
Signup/Register and Login/Logout icon needed.

### ISSUE THREAD

**Issue by viralj** [Templarian/MaterialDesign#442]
I have been looking for icons that will give user idea about Register/Signup and Login (we have logout icon just like github) and Logout. These icons can be used for mobile apps so we won't need to tell user in specific words like "Register here" or "Signup" or "Login" etc. I think someone will need to design icons. I am not an artist otherwise I'd contribute. I hope this idea is useful.

**Comment by Templarian** [comment]
Do you have examples of what these might look like?

http://materialdesignicons.com/icon/login
http://materialdesignicons.com/icon/logout

**Comment by viralj** [comment]
I have seen Login and Logout icons but I think we need to redesign them that will make user to understand all three of them , Register/Signup, Login and Logout. As I said, I am not an artist so I cant think about them, but as a programmer, all I see is that we need something really short that we can use for buttons so our users will get things without need of explanation of the particular button.

**Comment by timothyjc** [comment]
How about you use this for the register icon?
https://materialdesignicons.com/icon/pencil-box-outline

**Comment by gytdau** [comment]
Or, for Register, you could use this:
https://materialdesignicons.com/icon/account-plus

**Comment by viralj** [comment]
Yes, I've used it for now. That is the only icon I found some how relevant to Signup action.

**Comment by Templarian** [comment]
I'm going to close this issue. If anyone has any examples for an alternative icon I'll reopen it. I think the two suggestions so far would both work fine for a register icon.

Thanks by the way, always nice to see others jumping in helping each other find an icon to fit their needs.
