### ISSUE TITLE
card-plus(-outline)

### ISSUE THREAD

**Issue by MqnA** [Templarian/MaterialDesign#4420]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Card Add

There is already a card add but for credit cards, i want one that is squared and that doesn't remind a credit card.

## Examples

https://materialdesignicons.com/icon/card-outline

**Comment by goyney** [comment]
[![card-plus](https://materialdesignicons.com/icon/card-plus)](https://materialdesignicons.com/icon/card-plus)[![card-plus-outline](https://materialdesignicons.com/icon/card-plus-outline)](https://materialdesignicons.com/icon/card-plus-outline)
