### ISSUE TITLE
image-edit

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4421]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Would have sworn blind we already had this but found myself in need of an `image-edit` icon today, to use as a link to the image editor within our system. We're already using `image` for inserting images in our content editor and `image-multiple` as a link to the image library/gallery.

**Comment by MrGrigri** [comment]
How do we not have that?

**Comment by frankgrinaert** [comment]
How's this?

![image](https://user-images.githubusercontent.com/55925048/66019991-e446ce00-e4e5-11e9-9a49-213db6fbfdd0.png)

[image-edit.svg.zip](https://github.com/Templarian/MaterialDesign/files/3679612/image-edit.svg.zip)

**Comment by goyney** [comment]
[![image-edit](https://materialdesignicons.com/icon/image-edit)](https://materialdesignicons.com/icon/image-edit)[![image-edit-outline](https://materialdesignicons.com/icon/image-edit-outline)](https://materialdesignicons.com/icon/image-edit-outline)

**Comment by frankgrinaert** [comment]
Nitpick: MDI [image-outline](https://materialdesignicons.com/icon/image-outline) differs slightly from the [official Google one](https://material.io/resources/icons/?search=image&icon=image&style=outline). Shouldn't we adjust the MDI icons to match?

Result:
![image](https://user-images.githubusercontent.com/55925048/66253350-3b0f0a80-e767-11e9-94a0-175715d80e78.png)

[image-edit-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3693087/image-edit-outline.svg.zip)

Don't know your policy on 'discrepancies with Papa Google' :)
