### ISSUE TITLE
ranking

### ISSUE THREAD

**Issue by akajack** [Templarian/MaterialDesign#4423]
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The icon should represent the athletic podium, which can be used to represent game rankings.

## Examples

[https://cdn.icon-icons.com/icons2/390/PNG/512/podium_39434.png](https://cdn.icon-icons.com/icons2/390/PNG/512/podium_39434.png)
[https://st3.depositphotos.com/14846838/18340/v/1600/depositphotos_183400132-stock-illustration-podium-flat-line-vector-icon.jpg](https://st3.depositphotos.com/14846838/18340/v/1600/depositphotos_183400132-stock-illustration-podium-flat-line-vector-icon.jpg)
[https://cdn0.iconfinder.com/data/icons/social-productivity-line-art-4/128/rankings-512.png](https://cdn0.iconfinder.com/data/icons/social-productivity-line-art-4/128/rankings-512.png)

**Comment by PeterShaggyNoble** [comment]
We already have a number of `poidium-*` icons to represent the different rankings.
