### ISSUE TITLE
car-info

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4424]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/65054211-352dc280-d93b-11e9-9332-d652fef74719.png)

## Zip Download

[car-info.zip](https://github.com/Templarian/MaterialDesign/files/3622059/car-info.zip)

**Comment by MrGrigri** [comment]
I used the unconventional 'i' because the normal 'i' looked weird because of the headlight.

**Comment by MrGrigri** [comment]
Updated:

![image](https://user-images.githubusercontent.com/4528551/65434592-4d3e8f80-dddc-11e9-9498-248ec30768f7.png)


---

#### Files

[car-info.zip](https://github.com/Templarian/MaterialDesign/files/3642602/car-info.zip)

**Comment by goyney** [comment]
[![car-info](https://materialdesignicons.com/icon/car-info)](https://materialdesignicons.com/icon/car-info)
