### ISSUE TITLE
Router Icon

### ISSUE THREAD

**Issue by sergiocarlotto** [Templarian/MaterialDesign#4425]
Hi, I searched for router icons, but found only more specific icons for wireless hubs or equipment.
Following is an edited icon based on the diameter contour.
I made a SGV based on an existing one but I believe it is different from the project standards.

[router-icon.zip](https://github.com/Templarian/MaterialDesign/files/3622797/router-icon.zip)

Follows an edited icon based on the diameter-outline.

I have:

- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by CoDEmanX** [comment]
Do you actually mean routing as a concept? Our arrow-decision icon depicts that pretty well IMO.

**Comment by sergiocarlotto** [comment]
> Do you actually mean routing as a concept? Our arrow-decision icon depicts that pretty well IMO.

It would be in the sense of network routing, current icons refer to a specific equipment. The application I refer to would be for network mapping. Where I have a routing on the network.

It could look something like the image:
![image](https://user-images.githubusercontent.com/2835460/65074559-7ccc4280-d96b-11e9-883f-d7552cabb8b4.png)

**Comment by sergiocarlotto** [comment]
I made the adjustment in the SVG file and includes the print Icon Preview



### Preview

![image](https://user-images.githubusercontent.com/2835460/65776789-299b8200-e119-11e9-8219-6823769b9137.png)

### Zip Download
[router.zip](https://github.com/Templarian/MaterialDesign/files/3663135/router.zip)

**Comment by JamesCoyle** [comment]
What are we calling this? arrows-in-out-circle-outline?

**Comment by goyney** [comment]
No, this is the official symbol for a router in network topologies. In should definitely include `router` in the name, just not sure what it should be exactly.

**Comment by sergiocarlotto** [comment]
> No, this is the official symbol for a router in network topologies. In should definitely include `router` in the name, just not sure what it should be exactly.

Acreito que este seja o símbolo correto para ilustrar um "roteador", segue artigo na uml-diagrams.org:

https://www.uml-diagrams.org/network-architecture-diagrams.html#router

![image](https://user-images.githubusercontent.com/2835460/65788158-daf9e200-e130-11e9-9f55-c48d62ba33d5.png)

**Comment by goyney** [comment]
Except that shows perspective, which is not Material. @MrGrigri's version is the correct design to (a) match a router for topologies and (b) follow Material guidelines.

**Comment by MrGrigri** [comment]
@goyney, not me!

**Comment by goyney** [comment]
> @goyney, not me!

Whoops, apologies. @sergiocarlotto's version. :)

**Comment by goyney** [comment]
[![router](https://materialdesignicons.com/icon/router)](https://materialdesignicons.com/icon/router)
