### ISSUE TITLE
bell-check

### ISSUE THREAD

**Issue by baskuipers93** [Templarian/MaterialDesign#4426]
![image](https://user-images.githubusercontent.com/24432642/65131875-468cd280-da00-11e9-9546-df10ce1d4701.png)

[bell-check.zip](https://github.com/Templarian/MaterialDesign/files/3625253/bell-check.zip)

**Comment by CoDEmanX** [comment]
Arrow and cutout seem too thin, and the placement of the modifier is non-standard. I think it would work if it followed the example of e.g. email-check.

**Comment by JamesCoyle** [comment]
Please follow the issue template when contributing. Unfortunately the icon you have provided does not fit with the Material guidelines. This needs to use our standard check modifier and cutout.

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/66261128-fc596e80-e7bf-11e9-8bd7-03db678a0814.png)![image](https://user-images.githubusercontent.com/15905797/66261141-1bf09700-e7c0-11e9-8e74-8e840ef2d7df.png)
Personally I prefer the first, the design of Google's check modifier, though the second is consistent with the rest of ours.

[bell-check.zip](https://github.com/Templarian/MaterialDesign/files/3693718/bell-check.zip)

**Comment by Templarian** [comment]
The circle cutout is more consistent. Using our regular cut out it looks like this:

![image](https://user-images.githubusercontent.com/338885/66275677-a41e7d00-e850-11e9-9d04-8206ac9bbd2b.png)![image](https://user-images.githubusercontent.com/338885/66275687-b39dc600-e850-11e9-8131-6173464160f6.png)

**Comment by Templarian** [comment]
Added. We'll revise this later as `-check` is not the most consistent.
