### ISSUE TITLE
outdoor light

### ISSUE THREAD

**Issue by moahamadramezani** [Templarian/MaterialDesign#4427]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by moahamadramezani** [comment]
![images](https://user-images.githubusercontent.com/55602577/65355800-0a2bc300-dc08-11e9-8ba8-8d1f0d8533bf.png)

**Comment by PeterShaggyNoble** [comment]
We have `coach-lamp`. Will that fulfill this request or are you also requesting the others?

![coach-lamp](https://user-images.githubusercontent.com/15157491/65357431-f6279780-dbee-11e9-8a01-b0bfccaf08e5.png)

**Comment by goyney** [comment]
We also have `outdoor-lamp`. I think this is covered.

[![outdoor-lamp](https://materialdesignicons.com/icon/outdoor-lamp)](https://materialdesignicons.com/icon/outdoor-lamp)
