### ISSUE TITLE
printer-3d-alert

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#4428]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Error during print. 🖨!

## Examples

Basically ! to the existing `printer-3d` icon.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/65403858-7be84600-dd9b-11e9-8bc1-484b0e081a52.png)

Does this look right?

**Comment by MrGrigri** [comment]
IMO, this is way too complex.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/65480048-9ed73080-de55-11e9-8d7f-896aa308f731.png)

Weird without the cube. Might work in context.

**Comment by goyney** [comment]
Is this solved by...
[![printer-3d-nozzle-alert](https://materialdesignicons.com/icon/printer-3d-nozzle-alert)](https://materialdesignicons.com/icon/printer-3d-nozzle-alert)

**Comment by Templarian** [comment]
Was thinking since we have `printer-error` it might be a good idea to have an error for a 3D print. The nozzle alert is more for jam/temperature issue.

**Comment by Templarian** [comment]
I think nozzle alert does better for 3d printers. Closing this out.
