### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by SnickDesign** [Templarian/MaterialDesign#4429]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/54479108/65377494-803a3380-dcb5-11e9-974f-e744cc1fdc91.png)

## Zip Download

[Code.zip](https://github.com/Templarian/MaterialDesign/files/3638969/Code.zip)

**Comment by Templarian** [comment]
It's called `xml`. 👍

**Comment by Templarian** [comment]
Added the alias `code` and tagged it to `developer / languages`

**Comment by SnickDesign** [comment]
Maybe publish as an "-variant"?

**Comment by Templarian** [comment]
Proportionally it's too narrow. Look at the section in the MD guidelines about proportions. Since the icon would be wide we can increase the shapes a little. This gives it a visual consistency when placed in a list of items vertically/horizontally.
