### ISSUE TITLE
close-big

### ISSUE THREAD

**Issue by SnickDesign** [Templarian/MaterialDesign#4430]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/54479108/65377923-196b4900-dcba-11e9-83c8-4a8fb14c5c8b.png)

## Zip Download

[close-big.zip](https://github.com/Templarian/MaterialDesign/files/3638982/close-big.zip)

**Comment by Templarian** [comment]
What is the use case of this over using the regular `close` icon? This would probably go against Material Design guidelines as it introduces inconsistency.

**Comment by JamesCoyle** [comment]
Yeah I'm gonna close this out as it really doesn't fit in with the material style. Thanks for your suggestion!
