### ISSUE TITLE
menu-big

### ISSUE THREAD

**Issue by SnickDesign** [Templarian/MaterialDesign#4431]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/54479108/65378036-e924aa00-dcbb-11e9-96dd-210ba73455ce.png)

## Zip Download

[menu-big.zip](https://github.com/Templarian/MaterialDesign/files/3638987/menu-big.zip)

**Comment by Templarian** [comment]
What is the use case of this over using the regular `menu` icon? If it's for a hamburger menu with a different look that would probably go against Material Design guidelines as it introduces inconsistency.

**Comment by JamesCoyle** [comment]
I'm gonna close this out as it really doesn't fit in with the material style. Thanks for your suggestion!
