### ISSUE TITLE
account-close

### ISSUE THREAD

**Issue by SnickDesign** [Templarian/MaterialDesign#4432]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/54479108/65378175-ba0f3800-dcbd-11e9-881b-d1e47ebe9975.png)

## Zip Download

[account-close.zip](https://github.com/Templarian/MaterialDesign/files/3639000/account-close.zip)

**Comment by Templarian** [comment]
`account-remove`

Also be careful with `-remove`. These have a standard cutout shape and placement. Look at any of the `-remove` icons to get an idea.

There may be some discussion about converting `account-` to use standard `-remove` `-plus` `-minus` in the corner as these were done well before the standardization of the others.

**Comment by goyney** [comment]
Same as #4433, this is already included as `account-remove`.
