### ISSUE TITLE
account-close-outline

### ISSUE THREAD

**Issue by SnickDesign** [Templarian/MaterialDesign#4433]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/54479108/65378216-0f4b4980-dcbe-11e9-9559-8ac233fc51cf.png)

## Zip Download

[account-close-outline.zip](https://github.com/Templarian/MaterialDesign/files/3639005/account-close-outline.zip)

**Comment by MrGrigri** [comment]
Wouldn't `account-remove-outline` work? 

![account-remove-outline](https://materialdesignicons.com/icon/account-remove-outline)

**Comment by goyney** [comment]
The account icons are a mix of modifier placements, mainly because we just haven't gone back and updated a few of them. Our standard is to the left of the person, so this is already included as `account-remove-outline`.
