### ISSUE TITLE
Alternative Window icons

### ISSUE THREAD

**Issue by VDRainer** [Templarian/MaterialDesign#4436]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It would be nice to have an alternative for the window-open and window-closed icons as we don't use such up/down windows in europe.
I commented it in a closed icon request, but not sure if someone will read it.
https://github.com/Templarian/MaterialDesign/issues/3786

## Examples
![20190918_11:31:24_001](https://user-images.githubusercontent.com/26381449/65136527-04678f00-da08-11e9-958d-9e6dbbfddaac.png)
![20190918_11:31:53_001](https://user-images.githubusercontent.com/26381449/65136537-092c4300-da08-11e9-95dd-16cdd5ea66f1.png)

**Comment by MrGrigri** [comment]
As discussed in many issues and as per Material Design Guidelines, we do not add icons with perspective. Yes, there are a couple of exceptions, but this will not be one of them. Do you have any other examples that could fulfill your request?

**Comment by VDRainer** [comment]
Thanks @MrGrigri, for your reply and the explanation.
Didn't know about that.
Then this would be my next suggestion.
![Auswahl_202](https://user-images.githubusercontent.com/26381449/65456689-2c148800-de4a-11e9-9baa-0709f46b25fd.png)

**Comment by VDRainer** [comment]
Played a little with an online editor.
![20190924_12:09:26_001](https://user-images.githubusercontent.com/26381449/65503175-a8e44800-dec4-11e9-9daa-cb875d1d9827.png)
![20190924_12:09:51_001](https://user-images.githubusercontent.com/26381449/65503184-ad106580-dec4-11e9-8568-54aee473b510.png)
![20190924_12:11:20_001](https://user-images.githubusercontent.com/26381449/65503202-b3064680-dec4-11e9-9100-60182fd1a8f7.png)

**Comment by VDRainer** [comment]
So, after a lot of fiddling, i created my first svg's.
![20190926_16:06:24_001](https://user-images.githubusercontent.com/26381449/65702103-b9422180-e082-11e9-857f-8e59a2c3f330.png)

**Comment by MrGrigri** [comment]
First, thanks for your willingness to contribute to our community.

Second, please refer to the [Material Design specs](https://material.io/design/iconography/system-icons.html#) and provide the actual SVG. You can use our [preview tool](http://dev.materialdesignicons.com/contribute/github) to copy and paste the image here. Also, please ensure that the icon is a single compound path.

**Comment by VDRainer** [comment]
Sorry, absolute noob here.
I don't want to contribute, it was just an example.

**Comment by MrGrigri** [comment]
Here are the above examples in a single SVG path and designed to spec. IMO, these should be an acceptable variant. 

![image](https://user-images.githubusercontent.com/4528551/65707018-e2de5700-e048-11e9-986e-eac1b44f8664.png) ![image](https://user-images.githubusercontent.com/4528551/65707080-06a19d00-e049-11e9-84ca-9c2cfba43880.png)

---

#### Files

[window-variant.zip](https://github.com/Templarian/MaterialDesign/files/3658873/window-variant.zip)

**Comment by VDRainer** [comment]
GREAT! I love it!
Thanks very much!

**Comment by JapanYoshi** [comment]
Maybe use this shape just for iconicity? ![](https://user-images.githubusercontent.com/8707990/65736800-a7628c00-e11f-11e9-94a6-a9b15ae2932b.png)

**Comment by goyney** [comment]
[![window-open-variant](https://materialdesignicons.com/icon/window-open-variant)](https://materialdesignicons.com/icon/window-open-variant)[![window-closed-variant](https://materialdesignicons.com/icon/window-closed-variant)](https://materialdesignicons.com/icon/window-closed-variant)
