### ISSUE TITLE
Bathroom Light

### ISSUE THREAD

**Issue by Frigorio** [Templarian/MaterialDesign#4437]
Hope someone will find it useful.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/43074128/65505413-712bcf00-dec9-11e9-885a-fe7ca703d239.png)

## Zip Download

[bathroom-light.zip](https://github.com/Templarian/MaterialDesign/files/3646749/bathroom-light.zip)

**Comment by Templarian** [comment]
Not sure about this one, but a fan light might be possible with a few tweaks. 🤔

**Comment by Frigorio** [comment]
> Not sure about this one

Maybe you call it "[over mirror light](https://www.google.com/search?q=over+mirror+light)"

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/65575431-69097900-df35-11e9-81b2-9324ec81600a.png)

**Comment by Frigorio** [comment]
> Not sure about this one, but a fan light might be possible with a few tweaks. 🤔

![image](https://user-images.githubusercontent.com/43074128/65576698-bd7f1980-df72-11e9-94d9-d19af7411ae7.png)
[fan-light.zip](https://github.com/Templarian/MaterialDesign/files/3650954/fan-light.zip)

**Comment by MrGrigri** [comment]
Shouldn't the squares of the mirror (angry robot) be rounded?

**Comment by goyney** [comment]
I believe this is covered by the vanity light just added in #4460. Closing.
