### ISSUE TITLE
Shape Polyline Plus

### ISSUE THREAD

**Issue by smeijer** [Templarian/MaterialDesign#4439]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For a map editor, we need to have a few buttons to draw geometries. Geometries like a point, cirlce, polygon, and polyline.

Currently, the following icons are there (`query: shape`):

![image](https://user-images.githubusercontent.com/1196524/65692999-db807300-e073-11e9-8bc1-f52d39a47d35.png)

The interesting ones are:

```
2 shape-circle-plus 
5 shape-polygon-plus
6 shape-rectangle-plus
7 shape-square-plus
```

What I'm missing is `shape-polyline-plus` and `shape-point-plus`. 

## Examples

Include any example images so we know what the icon should look like.

We do have `vector-polyline`, but not with the `plus`:

![image](https://user-images.githubusercontent.com/1196524/65693286-55186100-e074-11e9-84be-879f54d9d710.png)

I suggest to create something like the `vector-polyline`, but without the vertices and with a +. 

The idea is something like this, but I'm sure you're better at this. Maybe rotate the polyline a bit so it doesn't need to be cut off? Or make it less sharp, so it matches better with the `shape-polygon-plus`?

![image](https://user-images.githubusercontent.com/1196524/65694167-b260e200-e075-11e9-804d-58e2ab54443a.png)

Regarding the `shape-point-plus`, I have no idea how to visualize that differently than the circle. It would be nice to have it as well.

**Comment by JamesCoyle** [comment]
Vector polyline plus will be added in #4504. Would that work for you?

**Comment by MrGrigri** [comment]
I believe the aforementioned icon request will suffice for this request.

**Comment by goyney** [comment]
Agree with @MrGrigri. Closing this one.
