### ISSUE TITLE
CPU, RAM etc

### ISSUE THREAD

**Issue by royale1223** [Templarian/MaterialDesign#444]
How about icons for phone components like CPU, RAM, storage etc?

eg:

http://www.advancetec.co.uk/amd/icons/cpu-icon.jpg

**Comment by oRRs** [comment]
Already exists, just search for "memory".

**Comment by royale1223** [comment]
Yeah, sorry

On Thu, Jun 18, 2015 at 6:14 PM, oRRs <notifications@github.com> wrote:

> Already exists, just search for "memory".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/444#issuecomment-113143661>
> .
>



-- 
Dr. Binoy Babu,
Kaimathuruthil,
Puthenvelikkara,
Eranakulam
683594
Mob : +91 9961 31 2801

**Comment by CoDEmanX** [comment]
The memory icon can be equally used for CPU IMHO. It's hard to make a distinct icon in 24x24 pixels.
