### ISSUE TITLE
Session cookies being set by MDI

### ISSUE THREAD

**Issue by wookoouk** [Templarian/MaterialDesign#4440]
I am using `@mdi/font` as part of Buefy and just noticed the following requests being sent by my site, why are these cookie requests being sent?

http://materialdesignicons.com/{persistent-cookie:_ga}
http://materialdesignicons.com/{session-cookie:PHPSESSID}

**Comment by Templarian** [comment]
The `@mdi/font` self hosted? If you're using the CDN and have visited the website it might be sending cookies for the `cdn.` subdomain?

The `@mdi/font` self hosted has nothing that references the website.

**Comment by wookoouk** [comment]
Thanks for the quick response, I am looking into the issue, I think the cause could from the way buefy is using mdi https://github.com/buefy/buefy/issues/890
I will update when I have found the cause.

**Comment by goyney** [comment]
@wookoouk I'm unable to reproduce this with our CDN. Have you made any progress on this?

**Comment by Templarian** [comment]
As this is a third party integration and `@mdi/font` has nothing in it referencing the domain I think this outside of our project. I don't think we share cookies across our CDN/website so not sure that is what you're seeing either.

Let us know if you figure this out... curious what it could be.

https://github.com/Templarian/MaterialDesign-Webfont

**Comment by wookoouk** [comment]
I went through all the dependencies for my project and found the following:

node_modules/buefy/CHANGELOG.md:* Buefy now uses [MDI icons from community](https://materialdesignicons.com/) instead, you'll have to change icon names and if you use a CDN you should change:
node_modules/buefy/CHANGELOG.md:<link rel="stylesheet" href="//cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css">
node_modules/buefy/README.md:* Supports both [Material Design Icons](https://materialdesignicons.com/) and [FontAwesome](http://fontawesome.io/)
node_modules/buefy/README.md:<link rel="stylesheet" href="//cdn.materialdesignicons.com/2.0.46/css/materialdesignicons.min.css">
Binary file node_modules/@nuxt/core/node_modules/.cache/esm/.data.blob matches
node_modules/@mdi/font/license.md:Copyright (c) 2014, Austin Andrews (http://materialdesignicons.com/),
node_modules/@mdi/font/README.md:Webfont distribution for the [Material Design Icons](https://materialdesignicons.com).
node_modules/@mdi/font/README.md:- [MaterialDesignIcons.com](https://materialdesignicons.com)
node_modules/@mdi/font/package.json:  "homepage": "https://materialdesignicons.com",
node_modules/nuxt-buefy/lib/module.js:    materialDesignIconsHRef: '//cdn.materialdesignicons.com/2.4.85/css/materialdesignicons.min.css'


I believe that `nuxt-buefy` is causing the issue.
Thank you for being polite while I looked into the issue.
