### ISSUE TITLE
"Alert" icon variations

### ISSUE THREAD

**Issue by sergiocarlotto** [Templarian/MaterialDesign#4442]
I would like to contribute the warning icons I needed to use in a project to give the feeling of intent. Post only icon color could harm users with vision problems. So besides the existing icon "alert" I created two versions with two and three exclamation points.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/2835460/65778095-a29bd900-e11b-11e9-8324-6ac5459c5d68.png)

![image](https://user-images.githubusercontent.com/2835460/65778135-bd6e4d80-e11b-11e9-882b-765038220767.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[alert.zip](https://github.com/Templarian/MaterialDesign/files/3663199/alert.zip)

**Comment by goyney** [comment]
There are other ways to indicate intent than by simply adding more. Moreover, I've never seen a case like the one presented above, which makes these extremely niche. Unfortunately, we will not be adding these to the library. Thank you for your suggestion.
