### ISSUE TITLE
note-text-outline

### ISSUE THREAD

**Issue by smeijer** [Templarian/MaterialDesign#4443]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The `outline` variant of `note-text` will have the same purpose as the default variant. Just a slightly different style.

## Examples

![image](https://user-images.githubusercontent.com/1196524/65788814-3d1c0c80-e15c-11e9-9e1e-7316e8de56fa.png)

The inverse of the icon above, like we have with a lot of other icons:

<img width="250" src="https://user-images.githubusercontent.com/1196524/65788940-88361f80-e15c-11e9-86d8-9a42fb33e730.png" />

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/65791745-9285f880-e11f-11e9-8950-065b9c40c170.png)

---

#### Files

[note-text-outline.zip](https://github.com/Templarian/MaterialDesign/files/3664022/note-text-outline.zip)

**Comment by goyney** [comment]
[![note-outline](https://materialdesignicons.com/icon/note-outline)](https://materialdesignicons.com/icon/note-outline)
