### ISSUE TITLE
State machine

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4444]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55925048/65820022-6d2ee280-e224-11e9-9e96-0194bfadea5d.png)

## Zip Download

[state-machine.zip](https://github.com/Templarian/MaterialDesign/files/3665785/state-machine.zip)

**Comment by goyney** [comment]
I like the idea, though I am unsure about the name. Needs some work to be better on-grid.

**Comment by frankgrinaert** [comment]
Thanks for the feedback!

Here's a more on-grid attempt. Bit tricky, since it's an equilateral triangle, but I think this is an improvement:

![image](https://user-images.githubusercontent.com/55925048/65820560-0103ad00-e22b-11e9-9d7a-954c482fb8e4.png)

As for the name, it was designed to illustrate the concept "state machine", but perhaps a more generic name can be found. _state-transitions_? _transitions_?

**Comment by goyney** [comment]
That's definitely better! We'll probably bring the whole thing down 1dp. Now to figure out an appropriate name. 🤔

**Comment by CoDEmanX** [comment]
Reminds me of a symbol for recycling. But following our usual conventions it should be something with arrow in the name I guess.

**Comment by frankgrinaert** [comment]
By "bring down 1dp" did you mean reduce the icon size on the artboard? Tried out some variations doing that:

![image](https://user-images.githubusercontent.com/55925048/65820946-80937b00-e22f-11e9-8b95-eff86f20f2da.png)

![image](https://user-images.githubusercontent.com/55925048/65820954-96a13b80-e22f-11e9-9b74-8ef5f978497e.png)

![image](https://user-images.githubusercontent.com/55925048/65820960-acaefc00-e22f-11e9-8064-843fe31b5522.png)

**Comment by goyney** [comment]
None of those.

![image](https://user-images.githubusercontent.com/1015040/65821171-0ef00880-e200-11e9-96a0-9daa4309eb07.png)

You have 1dp of a gap on top and 3dp gap on the bottom. It just needs to be moved down so there is an even 2dp top and bottom.

**Comment by frankgrinaert** [comment]
Got it. The upward offset was deliberate, so the triangle would look optically centered. But maybe I'm overthinking it. Some variations at initial size, shifted 1dp downwards:

![image](https://user-images.githubusercontent.com/55925048/65826829-be25f180-e28b-11e9-9a02-abc209981414.png)

![image](https://user-images.githubusercontent.com/55925048/65826844-d85fcf80-e28b-11e9-80af-f1d59bed5872.png)

![image](https://user-images.githubusercontent.com/55925048/65826845-deee4700-e28b-11e9-847c-5d87a11d57b7.png)

**Comment by goyney** [comment]
@frankgrinaert Can you attach the SVG for the `state-machine-lg-2` so we can add it? Thanks!

**Comment by frankgrinaert** [comment]
[state-machine.svg.zip](https://github.com/Templarian/MaterialDesign/files/3693004/state-machine.svg.zip)

**Comment by Templarian** [comment]
Added. 😃
