### ISSUE TITLE
Unpublish

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4445]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55925048/65820054-d4e52d80-e224-11e9-8900-2982d48f544e.png)

## Zip Download

[unpublish.zip](https://github.com/Templarian/MaterialDesign/files/3665790/unpublish.zip)

**Comment by MrGrigri** [comment]
I don't see this as an unpublish icon. IMO this still says download.

**Comment by frankgrinaert** [comment]
It's the inverse of [publish](https://materialdesignicons.com/icon/publish)

Fair point, though. :)

**Comment by goyney** [comment]
We've decided we're not going to add this icon. Thanks for the suggestion.
