### ISSUE TITLE
File embedded smart object

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4446]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Similar to Adobe Photoshop's 'embedded smart object' icon:

![image](https://user-images.githubusercontent.com/55925048/65820201-73be5980-e226-11e9-91ea-f7c71d608242.png)
![image](https://user-images.githubusercontent.com/55925048/65820185-55f0f480-e226-11e9-9859-f922b43b707a.png)

Proposal:

![image](https://user-images.githubusercontent.com/55925048/65820138-bdf30b00-e225-11e9-9f7c-dc9724b03343.png)

## Zip Download

[file-embed.svg.zip](https://github.com/Templarian/MaterialDesign/files/3665800/file-embed.svg.zip)

**Comment by goyney** [comment]
This really doesn't follow the pattern we have with nearly all other file icons. Also, a big square doesn't really mean "embed" to me, more like... "stop." Unsure about this one.

**Comment by frankgrinaert** [comment]
Fair enough. This was created specifically for a Photoshop plug-in, probably a bit too niche :)

**Comment by Templarian** [comment]
Closing this out. Agreed it's a little too niche at the moment.
