### ISSUE TITLE
Quill

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4447]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55925048/65820233-ef200b00-e226-11e9-9197-aef5564fd85e.png)

## Zip Download

[quill.svg.zip](https://github.com/Templarian/MaterialDesign/files/3665811/quill.svg.zip)

**Comment by Templarian** [comment]
Alias added to `feather`.

**Comment by Templarian** [comment]
We could probably add an inkwell / feather type combo though.
