### ISSUE TITLE
image-off-outline

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4448]
Outlined version of [image-off](https://materialdesignicons.com/icon/image-off)

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Using the MDI template—not quite satisfying:
![image](https://user-images.githubusercontent.com/55925048/65827102-11e60a00-e28f-11e9-80d9-96c8743be210.png)

Tweaked for balance and legibility:
![image](https://user-images.githubusercontent.com/55925048/65827121-435ed580-e28f-11e9-84a9-71e5259ccf9f.png)

Note: MDI [image-outline](https://materialdesignicons.com/icon/image-outline) differs slightly from the [official Google one](https://material.io/resources/icons/?search=image&icon=image&style=outline). I used the latter as a basis.

## Zip Download

[image-off-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3666400/image-off-outline.svg.zip)

**Comment by frankgrinaert** [comment]
solid version slightly tweaked to match the outlined version's silhouette:

![image](https://user-images.githubusercontent.com/55925048/65993918-7c1acc80-e492-11e9-9cbd-07754c325957.png)

Current version: [image-off](https://materialdesignicons.com/icon/image-off)

Apologies if this is too nitpicky :)

[image-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/3678219/image-off.svg.zip)

**Comment by goyney** [comment]
Further simplified the icons to remove the slight rounding at the slash intersection.

[![image-off](https://materialdesignicons.com/icon/image-off)](https://materialdesignicons.com/icon/image-off)[![image-off-outline](https://materialdesignicons.com/icon/image-off-outline)](https://materialdesignicons.com/icon/image-off-outline)
