### ISSUE TITLE
Sorting icons (set)

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4449]
This is a 'family' of sorting icons, so it made more sense to group them in one issue. Hope that's OK.

In addition to the generic [small to big](https://materialdesignicons.com/icon/sort-ascending) and [big to small](https://materialdesignicons.com/icon/sort-descending) sorting icons, I believe it's useful to have specific icons for various data types; text, numbers, booleans. These require less thinking from the user. For example, when I want to sort _A to Z_, I always need to remember that translates to _ascending_, i.e. _arrow-up_, or _small to big_.

Additional note: for _descending_ variants, I find it more intuitive to keep the arrow pointing downwards and switch the orientation of the values instead. This more accurately reflects what happens on screen.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

**Generic**
![image](https://user-images.githubusercontent.com/55925048/65828446-45c72c80-e29b-11e9-8212-4938ff67849b.png)
![image](https://user-images.githubusercontent.com/55925048/65828452-55df0c00-e29b-11e9-870b-0aff395473df.png)

**Alphabetic**
![image](https://user-images.githubusercontent.com/55925048/65828458-6db69000-e29b-11e9-9953-d6f23e2ad53a.png)
![image](https://user-images.githubusercontent.com/55925048/65828460-760ecb00-e29b-11e9-9f06-53c6e75f80f6.png)

**Numeric**
![image](https://user-images.githubusercontent.com/55925048/65828474-89219b00-e29b-11e9-85a3-b58c54543673.png)
![image](https://user-images.githubusercontent.com/55925048/65828483-9f2f5b80-e29b-11e9-9f76-54fd1640e0f7.png)

**Boolean**
![image](https://user-images.githubusercontent.com/55925048/65828501-cab24600-e29b-11e9-8b3e-c32b2831425a.png)
![image](https://user-images.githubusercontent.com/55925048/65828505-d271ea80-e29b-11e9-9971-b4c41b73f7d1.png)

## Zip Download

[sorting-set.zip](https://github.com/Templarian/MaterialDesign/files/3666451/sorting-set.zip)

**Comment by goyney** [comment]
All the arrows facing down is a no-go. We've already have extensive discussions surrounding the arrows in our sort icons in the past and switching them to change the arrows over the content of the icon.

Personally, I feel these aren't needed. However, if we are to add them, the base of the icons need to be the same and the arrows need to change direction based on ascending/descending.

**Comment by frankgrinaert** [comment]
Thanks for the feedback, Michael. This approach is what I landed on after my own lengthy debates, but there is clearly no one objective solution. Sorting is hard :)

I'd be very interested in seeing your past discussion, if that's still around.

If the demand is there, I'm happy to make the arrow-up variants of all of these.

**Comment by JamesCoyle** [comment]
I personally feel these are more intuitive than the arrow flipping. Could do with a few tweaks though.

**Comment by Templarian** [comment]
Actually kind of prefer these, but we need one that looks like check box.

**Comment by goyney** [comment]
The discussion partially happened here: https://github.com/Templarian/MaterialDesign/issues/3203 and also happened in our Slack. Looks like the majority of the contributors like the different types, but I am still of the opinion that we change the arrow directions and not the context. Arrows are easier to discern, especially at native resolution.

**Comment by frankgrinaert** [comment]
Looks like reheated a debate ;) Thanks for sharing!

In my opinion, the problem stems from the fact that this idea mashes up 2 'conflicting' pairs of sorting icons:

name|asc|desc
-|-|-
items|![lines-ascending](https://user-images.githubusercontent.com/55925048/66017855-c88afa00-e4dc-11e9-9e82-af9340f67e19.png)|![lines-descending](https://user-images.githubusercontent.com/55925048/66017856-c88afa00-e4dc-11e9-93b0-c5b7664915b8.png)
arrow|![arrow-up](https://user-images.githubusercontent.com/55925048/66017898-0d169580-e4dd-11e9-9bd9-3b46be8cd21a.png)|![arrow-down](https://user-images.githubusercontent.com/55925048/66017897-0d169580-e4dd-11e9-9111-189e641abbb1.png)

So the question is: which of the two is considered the _base_ icon and which the _addition_? The _base_ icon is the one that changes direction, the _addition_ stays put. Both approaches:

**1. items as base**

name|asc|desc
-|-|-
generic|![sort-ascending](https://user-images.githubusercontent.com/55925048/66018173-4c91b180-e4de-11e9-9265-0cc9f6bc4381.png)|![sort-descending](https://user-images.githubusercontent.com/55925048/66018179-4c91b180-e4de-11e9-9653-94aeaf4d42bd.png)
alpha|![sort-alpha-ascending](https://user-images.githubusercontent.com/55925048/66018171-4bf91b00-e4de-11e9-881b-a930e43bf762.png)|![sort-alpha-descending](https://user-images.githubusercontent.com/55925048/66018172-4bf91b00-e4de-11e9-9ca7-41d1df1b1517.png)
num|![sort-num-ascending](https://user-images.githubusercontent.com/55925048/66018180-4d2a4800-e4de-11e9-91ed-ce9dc1e418d9.png)|![sort-num-descending](https://user-images.githubusercontent.com/55925048/66018181-4d2a4800-e4de-11e9-8c26-7fbfff7a61e0.png)
bool|![sort-bool-ascending](https://user-images.githubusercontent.com/55925048/66018175-4c91b180-e4de-11e9-866a-48ead81f0199.png)|![sort-bool-descending](https://user-images.githubusercontent.com/55925048/66018177-4c91b180-e4de-11e9-9a7d-a0138d0cc981.png)
bool-var|![sort-bool-ascending-b](https://user-images.githubusercontent.com/55925048/66018174-4c91b180-e4de-11e9-9fdd-ee320defa443.png)|![sort-bool-descending-b](https://user-images.githubusercontent.com/55925048/66018176-4c91b180-e4de-11e9-9687-26d12f44a367.png)

**2. arrow as base**

name|asc|desc
-|-|-
generic|![sort-ascending](https://user-images.githubusercontent.com/55925048/66018337-f5d8a780-e4de-11e9-8dcf-0d313658fb5f.png)|![sort-descending](https://user-images.githubusercontent.com/55925048/66018343-f6713e00-e4de-11e9-98a0-86d28195f085.png)
alpha|![sort-alpha-ascending](https://user-images.githubusercontent.com/55925048/66018334-f5d8a780-e4de-11e9-8558-6c0a49a26c8b.png)|![sort-alpha-descending](https://user-images.githubusercontent.com/55925048/66018335-f5d8a780-e4de-11e9-81c3-f452fc13007b.png)
num|![sort-num-ascending](https://user-images.githubusercontent.com/55925048/66018344-f6713e00-e4de-11e9-9d41-a461165a039d.png)|![sort-num-descending](https://user-images.githubusercontent.com/55925048/66018346-f709d480-e4de-11e9-9819-5dd89f7adb44.png)
bool|![sort-bool-ascending](https://user-images.githubusercontent.com/55925048/66018340-f6713e00-e4de-11e9-92bd-f4dd865af02f.png)|![sort-bool-descending](https://user-images.githubusercontent.com/55925048/66018342-f6713e00-e4de-11e9-8124-9125982af542.png)
bool-var|![sort-bool-ascending-b](https://user-images.githubusercontent.com/55925048/66018339-f5d8a780-e4de-11e9-80ca-0eb9818b5472.png)|![sort-bool-descending-b](https://user-images.githubusercontent.com/55925048/66018341-f6713e00-e4de-11e9-99a9-7a23e239f1bf.png)

**Comment by goyney** [comment]
My vote is for arrow as a base (#2). Of course, the AZ, 09, and checkboxes are all flipped from how we'd actually add them.

**Comment by frankgrinaert** [comment]
_There was a logical error in v2, now corrected (checkboxes wrong way round for _bool-var_)_

If we want to flip AZ and 09, then everything should be flipped, for consistency → see **v3**

One of the reasons I prefer **v1** is that neither **v2** nor **v3** feels best for _all_ data types:

**v2** – big to small (descending) – better for _generic_ & _bool_
**v3** – small to big (ascending) – better for _alpha_ & _num_

This is not a concern in **v1**

The strongest argument for **v1**, however, is that the orientation of the icon _mirrors_ the orientation of the items on screen → less thought required from the user.

**Comment by JamesCoyle** [comment]
Could we add both options as variants and let users decide on the best for their use-case?

I'd like to see group 1 but with `menu-swap` instead of the arrow.
[![](https://materialdesignicons.com/icon/menu-swap)](https://materialdesignicons.com/icon/menu-swap)

I'd also like group 3 but with the arrows on the right hand side so it reads as "A to Z Ascending" rather than "Ascending A to Z".

**Comment by frankgrinaert** [comment]
> I'd like to see group 1 but with `menu-swap` instead of the arrow.

I think "`menu-swap` + something" is too uncommon to be a good choice:

<img width="360" alt="Screenshot 2019-10-06 at 18 58 37 (2)" src="https://user-images.githubusercontent.com/55925048/66274323-bd89ee00-e87d-11e9-8fe3-acf0d1d9660a.png">
<img width="360" alt="Screenshot 2019-10-06 at 20 41 34 (2)" src="https://user-images.githubusercontent.com/55925048/66274325-c67abf80-e87d-11e9-99a3-49078f2c1112.png">
<img width="360" alt="Screenshot 2019-10-06 at 21 09 31 (2)" src="https://user-images.githubusercontent.com/55925048/66274328-cb3f7380-e87d-11e9-8cdf-d2ed572abc5f.png">

> I'd also like group 3 but with the arrows on the right hand side so it reads as "A to Z Ascending" rather than "Ascending A to Z".

Sure, that could work. Both seem to be common.

**Comment by Templarian** [comment]
Agreed group 3 looks fine, but the arrows would look better on the right for group 3.

If we can find a nice way to name these. I'm fine adding variants or somehow grouping them differently. Naming needs to use these:

- `ascending`
- `descending`
- `alpha`
- `numeric`
- `checkbox`
- `radiobox`

**Comment by frankgrinaert** [comment]
Do we need both radio and checkbox, though?
Both are intended to sort on true/false

**Comment by Templarian** [comment]
Yeah, easy to assume some UX people will argue a Boolean circle is a radiobox. Is weird to call it a radiobox... maybe something else like box/box outline and circle/circle outline to be more generic.

**Comment by JamesCoyle** [comment]
I feel like we should do a version with the arrow changing direction and a version without the arrow where the icon content swaps. The latter would be better if your sorting options are displayed all together in a select box.

**Comment by Templarian** [comment]
That works. Just need naming that makes sense for this. I'll assign these all to @frankgrinaert once we get the names finalized.

**Comment by Templarian** [comment]
I know naming is the hardest part, but we're so close to getting these all added.

| ascending | descending | descending-variant |
|------------------------------------|--------------------------------------|-------------------------|
| ![image](https://user-images.githubusercontent.com/338885/66966995-e14ef000-f044-11e9-8421-fc00299e496f.png) | ![image](https://user-images.githubusercontent.com/338885/66966964-bfee0400-f044-11e9-90a6-306b7ab649fa.png) | ![image](https://user-images.githubusercontent.com/338885/66967038-0b081700-f045-11e9-89eb-2e95541049cb.png) |
| `sort-arrow-numeric-ascending` | `sort-arrow-numeric-descending` | `sort-arrow-numeric-descending-variant` |

**Comment by goyney** [comment]
I want to get these in this next version, but I need a final list of all icons being added and their names attached below this reply for that to happen. Someone please do that. 😄

**Comment by goyney** [comment]
This is actually going to happen in the 5.0 release since it's a breaking change to our current sort icons.

We are going to go with set #3 above.
![Screen Shot 2020-01-17 at 9 12 39 AM](https://user-images.githubusercontent.com/1015040/72618627-8a89d880-3909-11ea-9ebe-2f0e9245e268.png)

Naming will look like this:

- Generic [Breaking Update] - `sort-ascending`, `sort-descending`
- Alpha - `sort-alpha-ascending`, `sort-alpha-descending`
- Numeric - `sort-numeric-ascending`, `sort-numeric-descending`
- Bool - `sort-bool-ascending`, `sort-bool-descending`
- Bool Variant - `sort-bool-ascending-variant`, `sort-bool-descending-variant`

**Comment by CoDEmanX** [comment]
James suggested to place the arrow on the right-hand side and I like it:

![grafik](https://user-images.githubusercontent.com/1309249/72651936-5d7b0b80-3985-11ea-88c6-edebbe26f431.png)

And the `sort` icon:

![grafik](https://user-images.githubusercontent.com/1309249/72652434-10983480-3987-11ea-8559-d88594bdf956.png)

[sorting-set-arrow-right.zip](https://github.com/Templarian/MaterialDesign/files/4079559/sorting-set-arrow-right.zip)

In addition, I would like to discuss `sort-variant`. #4754 is missing a generic icon to represent "order", and `sort-variant` would actually be a great fit IMO. I tried to create one from the `order-*` icons, but there is too much space between the lines. It looks much better with less like in `sort-variant`. I would re-interpret the existing icon as "descending", but that doesn't match up with the new generic sort icons (on the other hand, it's unclear whether they represent an order at all).

![grafik](https://user-images.githubusercontent.com/1309249/72652493-58b75700-3987-11ea-90b1-aa1489365949.png)

We would need to add a flipped variant for ascending (included in above zip as `sort-reverse-variant.svg`):

![grafik](https://user-images.githubusercontent.com/1309249/72652011-90bd9a80-3985-11ea-8e6a-37f5c5ba4db4.png)

However, there are three icons based on `sort-variant`:
- `sort-variant-lock`
- `sort-variant-lock-open`
- `sort-variant-remove`

They would need to be renamed if we change the base icon's name...

**Comment by goyney** [comment]
These have all been added.
