### ISSUE TITLE
Cat icon

### ISSUE THREAD

**Issue by oRRs** [Templarian/MaterialDesign#445]
I'd love to see an icon of a cat, similar to the panda and pig icons:

http://materialdesignicons.com/icon/panda
http://materialdesignicons.com/icon/pig

**Comment by matthew2402** [comment]
I'd like to see that too ;)

**Comment by Templarian** [comment]
I would too.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/cat

Nice rough draft. Maybe someone will think of a nicer design in the future.

**Comment by oRRs** [comment]
@Templarian thanks a bunch, I love it! :+1:

**Comment by CoDEmanX** [comment]
Maybe just a silhouette like in this logo?
http://i.imgur.com/RLE0oEP.png
