### ISSUE TITLE
Fluorescent tube light

### ISSUE THREAD

**Issue by MattiasC** [Templarian/MaterialDesign#4450]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This icon can be used when showing different light types in Home Assistant or other smart home control apps.

## Examples

https://simple.wikipedia.org/wiki/Fluorescent_lamp#/media/File:OPK_2.jpg

https://www.shutterstock.com/es/image-photo/black-tunnel-ceiling-orange-yellow-fluorescent-399161914

https://imgur.com/a/AVq12e7

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/66260863-26109680-e7bc-11e9-8b9d-6f2c9a1abd43.png)

Also a filled variant:
![image](https://user-images.githubusercontent.com/15905797/66260880-5d7f4300-e7bc-11e9-983b-82105eae38c1.png)

[fluorescent-tube.zip](https://github.com/Templarian/MaterialDesign/files/3693695/fluorescent-tube.zip)

Also #4471 for CFL bulbs.

**Comment by goyney** [comment]
I feel like the gap in the filled version either needs to be in the outlined version or it needs to be removed. Thoughts?

**Comment by MattiasC** [comment]
> 
> 
> I feel like the gap in the filled version either needs to be in the outlined version or it needs to be removed. Thoughts?

I feel the same way, it does not quite look like the same thing as the top one with the gaps.

I also envisioned it completely horizontal to indicate that it is monted in the ceiling or underneath a cabinet for example. Several of the lights on the website alos have light rays beaming from the light source that helps indicate that it is a light.

**Comment by goyney** [comment]
[![lightbulb-fluorescent-tube](https://materialdesignicons.com/icon/lightbulb-fluorescent-tube)](https://materialdesignicons.com/icon/lightbulb-fluorescent-tube)[![lightbulb-fluorescent-tube-outline](https://materialdesignicons.com/icon/lightbulb-fluorescent-tube-outline)](https://materialdesignicons.com/icon/lightbulb-fluorescent-tube-outline)
