### ISSUE TITLE
car plate

### ISSUE THREAD

**Issue by samste** [Templarian/MaterialDesign#4451]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by MrGrigri** [comment]
Do you mean license plate? #712

**Comment by samste** [comment]
Yes!....
I apologize, I searched without finding and I thought I'd suggest.
I must have given the wrong definition.

Thanks for the reply

**Comment by MrGrigri** [comment]
Going to close this with the aforementioned issue as the main conversation thread. Please comment on that issue if you want any traction on that request.
