### ISSUE TITLE
alert-rhombus(-outline)

### ISSUE THREAD

**Issue by gdang** [Templarian/MaterialDesign#4452]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Used as an alert/error icon. There's already a rhombus icon with the question mark so this new icon could be a nice companion.

## Examples

https://www.atlassian.design/server/components/messages/

https://www.iconfinder.com/icons/3651967/alert_caution_diamond_exclamation_frame_warning_icon

**Comment by MrGrigri** [comment]
I cannot believe we don't have this icon.

![alert-rhombus](https://user-images.githubusercontent.com/4528551/65979553-ba809f00-e432-11e9-8e99-14cd8df637b0.png) ![alert-rhombus-outline](https://user-images.githubusercontent.com/4528551/65979647-ddab4e80-e432-11e9-8bfb-5df22deb971c.png)

---
#### Files
[alert-rhombus.zip](https://github.com/Templarian/MaterialDesign/files/3677429/alert-rhombus.zip)

**Comment by goyney** [comment]
[![alert-rhombus](https://materialdesignicons.com/icon/alert-rhombus)](https://materialdesignicons.com/icon/alert-rhombus)[![alert-rhombus-outline](https://materialdesignicons.com/icon/alert-rhombus-outline)](https://materialdesignicons.com/icon/alert-rhombus-outline)
