### ISSUE TITLE
paper money wave icon

### ISSUE THREAD

**Issue by zeeshanweb-official** [Templarian/MaterialDesign#4453]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
> Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
Closing because the `Needs More Info` tag was added a week ago with no response.
