### ISSUE TITLE
chart-snakey(-variant)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4454]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

I'm using this in a project of mine and thought it could be useful.

![chart-snakey](https://user-images.githubusercontent.com/4528551/65981099-a4c0a900-e435-11e9-8fe1-463f2af43254.png)
![chart-snakey-variant](https://user-images.githubusercontent.com/4528551/65981109-ab4f2080-e435-11e9-856e-2f8cf81a9e5a.png)

## Zip Download

[chart-snakey.zip](https://github.com/Templarian/MaterialDesign/files/3677538/chart-snakey.zip)

**Comment by goyney** [comment]
[![chart-snakey](https://materialdesignicons.com/icon/chart-snakey)](https://materialdesignicons.com/icon/chart-snakey)[![chart-snakey-variant](https://materialdesignicons.com/icon/chart-snakey-variant)](https://materialdesignicons.com/icon/chart-snakey-variant)
