### ISSUE TITLE
crown-outline

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4455]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55925048/65989879-d1eb7680-e48a-11e9-9504-e26af787926a.png)

I've had to tweak the existing solid version of this icon slightly, to match:

![image](https://user-images.githubusercontent.com/55925048/65989918-e596dd00-e48a-11e9-9142-3d88d39dd089.png)

## Zip Download

[crown-outline.zip](https://github.com/Templarian/MaterialDesign/files/3677958/crown-outline.zip)

**Comment by JamesCoyle** [comment]
Needs to be a bigger gap between the base and the points somehow IMO.

**Comment by Templarian** [comment]
Yeah, but I think it looks visually okay considering matches the filled one.

**Comment by goyney** [comment]
[![crown](https://materialdesignicons.com/icon/crown)](https://materialdesignicons.com/icon/crown)[![crown-outline](https://materialdesignicons.com/icon/crown-outline)](https://materialdesignicons.com/icon/crown-outline)
