### ISSUE TITLE
Add icons in all other 3 types (sharp, round and two-tone icons)

### ISSUE THREAD

**Issue by kaushalyap** [Templarian/MaterialDesign#4456]
Here in material design website, there are [5 types of icons](https://material.io/resources/icons/). Currently we only have two types of icons (outlined, filled). We are missing 

- sharp
- rounded
- two-toned

Think about adding other 3 types of icons also to make the collection complete.

**Comment by JamesCoyle** [comment]
See #3163. 

This is a massive task to undertake and we are currently focused on clearing out our icon backlog, bringing our outline icon collection up to match our filled selection, and developing the new website. You can help by contributing filled and outline icons which follow the guidelines and opening issues for missing outline icons.
