### ISSUE TITLE
movie-search

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4458]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55925048/66044102-1a557380-e521-11e9-9ff7-0690e951b85b.png)

## Zip Download

[movie-search.svg.zip](https://github.com/Templarian/MaterialDesign/files/3681060/movie-search.svg.zip)

**Comment by JamesCoyle** [comment]
Can you add the outline version of this too?

**Comment by frankgrinaert** [comment]
![image](https://user-images.githubusercontent.com/55925048/66052534-087bcc80-e531-11e9-8cc6-dd386eec6772.png)

[movie-search-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3681583/movie-search-outline.svg.zip)

**Comment by goyney** [comment]
[![movie-search](https://materialdesignicons.com/icon/movie-search)](https://materialdesignicons.com/icon/movie-search)[![movie-search-outline](https://materialdesignicons.com/icon/movie-search-outline)](https://materialdesignicons.com/icon/movie-search-outline)
