### ISSUE TITLE
Horse

### ISSUE THREAD

**Issue by EnzoDaneri** [Templarian/MaterialDesign#4459]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by JamesCoyle** [comment]
Please follow the instructions in the issue template before posting a new issue. #174
