### ISSUE TITLE
Mobile Home / RV

### ISSUE THREAD

**Issue by coogle** [Templarian/MaterialDesign#4461]
I have:

- [X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

I'd like an icon that represents a mobile home / RV. Looking through the existing icons the closest would be the firetruck .. something similar with a door in the back part would probably make sense.

## Examples

![image](https://user-images.githubusercontent.com/1863471/66083473-6365f180-e53a-11e9-92d6-23077acc8950.png)

**Comment by MrGrigri** [comment]
This might be tricky

**Comment by coogle** [comment]
How so?

**Comment by MrGrigri** [comment]
I initially thought that it would be difficult because of the size and detail needed to ensure it looks like a camper without adding too much detail.

![rv-truck](https://user-images.githubusercontent.com/4528551/66086312-e5e9b380-e530-11e9-8c07-ecb76e1250e4.png)

---
#### Files

[rv-truck.zip](https://github.com/Templarian/MaterialDesign/files/3683624/rv-truck.zip)

**Comment by coogle** [comment]
Ah. Yeah it totally works I think and fits my need. I wonder if you made the door 1px wider and put a handle on if it would look oversized? But as I said, this would fit my need as is.

**Comment by MrGrigri** [comment]
MD guidelines specifically state to not add too much detail. I believe what we have will work.

**Comment by coogle** [comment]
Thank you!

**Comment by goyney** [comment]
[![rv-truck](https://materialdesignicons.com/icon/rv-truck)](https://materialdesignicons.com/icon/rv-truck)
