### ISSUE TITLE
settings-restore

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4462]
Just in case, if you think it can be useful:

## Preview

![image](https://user-images.githubusercontent.com/6012554/66115775-cbb3e200-e5d1-11e9-9919-7a93be40a269.png)

## Zip Download

[restore-settings.zip](https://github.com/Templarian/MaterialDesign/files/3685362/restore-settings.zip)

**Comment by goyney** [comment]
I think the icon is okay, but the name would have to be more like `cog-counterclockwise` and we should add the `clockwise` version as well. We can add aliases for settings then.

**Comment by goyney** [comment]
[![cog-clockwise](https://materialdesignicons.com/icon/cog-clockwise)](https://materialdesignicons.com/icon/cog-clockwise)[![cog-counterclockwise](https://materialdesignicons.com/icon/cog-counterclockwise)](https://materialdesignicons.com/icon/cog-counterclockwise)

**Comment by qnp** [comment]
Thanks for your update !
