### ISSUE TITLE
shopping-outline

### ISSUE THREAD

**Issue by Usama4745** [Templarian/MaterialDesign#4463]
I have:

- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by Usama4745** [comment]
[shopping-bag.zip](https://github.com/Templarian/MaterialDesign/files/3685608/shopping-bag.zip)

**Comment by MrGrigri** [comment]
Please refer to the already included icons. Do none of them suit your needs? We already have `shopping`, `basket`, and `cart`.

![shopping](https://materialdesignicons.com/icon/shopping) ![basket](https://materialdesignicons.com/icon/basket) ![cart](https://materialdesignicons.com/icon/cart)

**Comment by Usama4745** [comment]
I need the icon I have posted

**Comment by MrGrigri** [comment]
This is the proposed icon by @Usama4745. This does not follow the [Material Design guidelines](https://material.io/design/iconography/system-icons.html). 

![image](https://user-images.githubusercontent.com/4528551/66144242-b33dca80-e5c5-11e9-8c3f-dd0c92f07f14.png)

**Comment by PeterShaggyNoble** [comment]
Google have a `shopping-outline` icon:

[![shopping-outline](https://user-images.githubusercontent.com/15157491/66146264-56add000-e604-11e9-831a-eca84bab5868.png)](https://material.io/resources/icons/?search=local_mall&icon=local_mall&style=outline)

**Comment by goyney** [comment]
We'll add the outline version of `shopping` in this issue.

**Comment by goyney** [comment]
[![shopping-outline](https://materialdesignicons.com/icon/shopping-outline)](https://materialdesignicons.com/icon/shopping-outline)
