### ISSUE TITLE
view-agenda-outline & view-grid(-plus)-outline

### ISSUE THREAD

**Issue by donhurickerby** [Templarian/MaterialDesign#4465]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

Can we have a view-agenda-outline and a view-grid-outline?

Thanks!

## Usage
Same as the "non-outline" icons

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by MrGrigri** [comment]
Is there a reason why the current `view-agenda` is not centered?

![image](https://user-images.githubusercontent.com/4528551/66140010-9a7de680-e5be-11e9-824e-5a96237ca637.png)

**Comment by MrGrigri** [comment]
This `view-agenda-outline` is corrected to be centered and on-grid. I also did the `view-grid-plus-outline` as well. 

![view-agenda-outline](https://user-images.githubusercontent.com/4528551/66140742-dfeee380-e5bf-11e9-9b36-d751d91ff5cc.png) ![view-grid-outline](https://user-images.githubusercontent.com/4528551/66140826-01e86600-e5c0-11e9-8fb5-8728b49283b3.png) ![view-grid-plus-outline](https://user-images.githubusercontent.com/4528551/66140931-2e9c7d80-e5c0-11e9-99e0-baebe11e4759.png)

---
#### Files

[view(-agenda)(-grid(-plus))-outline.zip](https://github.com/Templarian/MaterialDesign/files/3686842/view.-agenda.-grid.-plus.-outline.zip)

**Comment by donhurickerby** [comment]
wouldn't the smaller boxes have curved edges as well? id say either all pointy edges or all curved edges to be consistent. what do you think?

**Comment by MrGrigri** [comment]
That's not part of the [Material Design guidelines](https://material.io/design/iconography/system-icons.html).

**Comment by donhurickerby** [comment]
This is the material design's view-agenda icon : 
https://material.io/resources/icons/?search=view&icon=view_agenda&style=outline

The design guidelines say do not round interior corners of icons but i was referring to the outside corners of the smaller squares

**Comment by MrGrigri** [comment]
Yeah, these are Google's icons...they themselves are contradictory. If we add an icon, we adhere to the standard, but if we add a Google icon, we just add theirs. Welcome to the wonderful frustrations of Google.

**Comment by donhurickerby** [comment]
got it, thanks

**Comment by goyney** [comment]
[![view-agenda](https://materialdesignicons.com/icon/view-agenda)](https://materialdesignicons.com/icon/view-agenda)[![view-agenda-outline](https://materialdesignicons.com/icon/view-agenda-outline)](https://materialdesignicons.com/icon/view-agenda-outline)
[![view-grid-outline](https://materialdesignicons.com/icon/view-grid-outline)](https://materialdesignicons.com/icon/view-grid-outline)[![view-grid-plus-outline](https://materialdesignicons.com/icon/view-grid-plus-outline)](https://materialdesignicons.com/icon/view-grid-plus-outline)
