### ISSUE TITLE
farm

### ISSUE THREAD

**Issue by vitaly-ignatovich** [Templarian/MaterialDesign#4466]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Farm icon can be used for smart agriculture apps.

## Examples

like farmer worker digging or holding wheat

**Comment by MrGrigri** [comment]
Would `barn` not suffice?

![barn](https://materialdesignicons.com/icon/barn)

**Comment by MrGrigri** [comment]
I'm going to add an alias of `farm` to `barn`

**Comment by GreenTurtwig** [comment]
And if you're outside NA there's also:
![tractor](https://materialdesignicons.com/icon/tractor)
and
![silo](https://materialdesignicons.com/icon/silo)
