### ISSUE TITLE
Contact Export

### ISSUE THREAD

**Issue by Hrnkas** [Templarian/MaterialDesign#4467]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Export Contact (Address) data to file or some other destination. (different than share, because target is not another App).

## Examples

I can imagine it to be person (like for contact icon) with an arrow pointing to the right (like export icon).

**Comment by CoDEmanX** [comment]
There is very little space using the account base shape:

![grafik](https://user-images.githubusercontent.com/1309249/66253835-3bf76a80-e76e-11e9-84b9-b88133258b67.png) ![grafik](https://user-images.githubusercontent.com/1309249/66253847-66e1be80-e76e-11e9-8468-97c95a47b565.png)

I also tried smaller user silhouettes from other icons, but they are too small and it looked odd with other arrows.

**Comment by Hrnkas** [comment]
I must be tripping! I just found account-arrow-right. I could swear there was none when I looked a few days ago. Sorry for your trouble!
