### ISSUE TITLE
cloud-lock(-outline)

### ISSUE THREAD

**Issue by gabsy** [Templarian/MaterialDesign#4468]

**Comment by MrGrigri** [comment]
When putting this path through the optimizer, it was cutting off the left-side of the cloud.

![image](https://user-images.githubusercontent.com/4528551/66236907-ec9f3480-e6b0-11e9-889c-2849c58db63f.png) ![image](https://user-images.githubusercontent.com/4528551/66236938-fcb71400-e6b0-11e9-8654-ee172fe5e20f.png)

---

#### Files

[cloud-lock.zip](https://github.com/Templarian/MaterialDesign/files/3692159/cloud-lock.zip)

**Comment by JamesCoyle** [comment]
Could we put the lock in the center of the icon?

**Comment by Templarian** [comment]
To keep it consistent the position is fine even if it leads an odd cut.

**Comment by JamesCoyle** [comment]
But most of the cloud icons have a central modifier.

**Comment by MrGrigri** [comment]
Not a fan with it being inside the cloud.

![image](https://user-images.githubusercontent.com/4528551/66324266-5b170900-e8e2-11e9-975d-d96e5acef0d8.png) ![image](https://user-images.githubusercontent.com/4528551/66324317-6c601580-e8e2-11e9-9187-1e29611b6746.png)

**Comment by Templarian** [comment]
Yeah, the idea is there, but even with the weird cut out it reads nicer in the corner. Should be fine to add that one.

**Comment by JamesCoyle** [comment]
What if we moved the lock up 2dp? Would the cutout look less weird?

**Comment by Templarian** [comment]
Added. We can discuss it more after the release if it needs to be modified.
