### ISSUE TITLE
magnet (mouse snap)

### ISSUE THREAD

**Issue by TheCamel** [Templarian/MaterialDesign#447]
something like mouse icon but snaping to something, like attracted
or magnet would be ok

**Comment by CoDEmanX** [comment]
A very straightforward magnet:
![magnet](https://cloud.githubusercontent.com/assets/1309249/8663207/9b1e1c10-29c8-11e5-81ec-510297e7a1da.png) https://www.dropbox.com/s/gvu6d8bmmixalei/magnet.svg?dl=0

Not very happy with the result though, might be more intuitive if "+" and "-" were added somehow. Or a flash like in https://cdn3.iconfinder.com/data/icons/glypho-computers-andother-tech/64/magnet-power-512.png

**Comment by CoDEmanX** [comment]
Another try, with 1.25px line width on the upper rectangles:
![magnet2](https://cloud.githubusercontent.com/assets/1309249/8888140/bb1d4e78-32a1-11e5-851d-c3211720f6b4.png) https://www.dropbox.com/s/3uv9n3scbesz54t/magnet2.svg?dl=0

**Comment by TheCamel** [comment]
well both are ok
how it is if you try to put the flash in the middle/center ?

Question : how to contribute ? should i use a git repository ? then should i make a pull requesdt or what else ?
I am not using svg, but the design and xaml  in a new wpf application -:) please submit the design so i can integrate
http://www.codeproject.com/Articles/1003517/Arch-X
https://archx.codeplex.com/

**Comment by CoDEmanX** [comment]
I would make the magnet wider in order to achieve 2px spacing between magnet and flash:

![magnet3](https://cloud.githubusercontent.com/assets/1309249/8894076/0f618356-33aa-11e5-96af-3d0b262bf152.png) https://www.dropbox.com/s/az9a9q7tdi1fkvs/magnet3.svg?dl=0

**Comment by TheCamel** [comment]
it's ok, post it :-)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/magnet
https://materialdesignicons.com/icon/magnet-on
