### ISSUE TITLE
USB Hard Disk

### ISSUE THREAD

**Issue by rmcproductions** [Templarian/MaterialDesign#4470]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The Hard disk icon with an attached usb icon. Like harddisk-plus or harddisk-remove, but with an usb.

## Examples

I thought of something similar to this: 
![image](https://user-images.githubusercontent.com/40141421/66258942-83501c00-e7ab-11e9-9caa-2c855beeadce.png)

**Comment by GreenTurtwig** [comment]
![image](https://user-images.githubusercontent.com/15905797/66261295-886c9580-e7c2-11e9-9477-fd792d83f22f.png)

Not a fan of this, the symbol definitely wasn't designed to be this small.

**Comment by rmcproductions** [comment]
I see what you mean, it's really small and almost clipping outside of the image. I am fine with using my own "custom" version of it, I'd thought it'd be cool to have it "official".
Anyways, thanks for your time :)

**Comment by GreenTurtwig** [comment]
[harddisk-usb.zip](https://github.com/Templarian/MaterialDesign/files/3693741/harddisk-usb.zip)
Here's the SVG if you think it'll come in handy. :+1:

**Comment by rmcproductions** [comment]
Thank you very much, appreciated 👍
