### ISSUE TITLE
lightbulb-cfl

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#4471]
![image](https://user-images.githubusercontent.com/15905797/66260759-03ca4900-e7bb-11e9-9517-0bfbfa3b2827.png)![image](https://user-images.githubusercontent.com/15905797/66260766-19d80980-e7bb-11e9-8203-ee2f51f4753a.png)

![image](https://user-images.githubusercontent.com/15905797/66260839-e8137280-e7bb-11e9-8cb5-7282b4bf47ce.png)

  
  

Other not so good designs:

![image](https://user-images.githubusercontent.com/15905797/66260780-3bd18c00-e7bb-11e9-8e35-119446ed06bc.png)![image](https://user-images.githubusercontent.com/15905797/66260786-4ab83e80-e7bb-11e9-85c2-f4ab0b868390.png)
![image](https://user-images.githubusercontent.com/15905797/66260801-7f2bfa80-e7bb-11e9-9a0a-2a75997dcc28.png)![image](https://user-images.githubusercontent.com/15905797/66260800-79361980-e7bb-11e9-80e2-1c8beb0ca415.png)

[lightbulb-cfl.zip](https://github.com/Templarian/MaterialDesign/files/3693697/lightbulb-cfl.zip)

**Comment by GreenTurtwig** [comment]
Should probably mention some good use cases.
To represent energy saving and potentially useful for smart home.

**Comment by MrGrigri** [comment]
I like the first one. I like the flat perspective just like we have in `mailbox`

**Comment by goyney** [comment]
[![lightbulb-cfl](https://materialdesignicons.com/icon/lightbulb-cfl)](https://materialdesignicons.com/icon/lightbulb-cfl)[![lightbulb-cfl-off](https://materialdesignicons.com/icon/lightbulb-cfl-off)](https://materialdesignicons.com/icon/lightbulb-cfl-off)
