### ISSUE TITLE
unfold-more icons: Direction misnamed?

### ISSUE THREAD

**Issue by rpattabi** [Templarian/MaterialDesign#4473]
Take a look at [unfold-more-horizontal](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/unfold-more-horizontal.svg) and [unfold-more-vertical](https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/unfold-more-vertical.svg).`unfold-more-horizontal` is actually pointing in vertical direction and `unfold-more-vertical` is pointing in horizontal direction.

Aren't they supposed to have their names switched?

**Comment by Templarian** [comment]
It's probably in the way it's interpreted. Unfolding an item on an horizontal is how I would view this.

![Untitled1](https://user-images.githubusercontent.com/338885/66275437-1772bf80-e84e-11e9-8e5e-7cbefd68a1e5.png)
