### ISSUE TITLE
file-edit

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4474]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55925048/66274903-a5b56880-e883-11e9-8526-6c3a8e59eaf4.png)

![image](https://user-images.githubusercontent.com/55925048/66274896-920a0200-e883-11e9-96bd-3fbdb937fea5.png)

## Zip Download

[file-edit.zip](https://github.com/Templarian/MaterialDesign/files/3694801/file-edit.zip)

**Comment by Templarian** [comment]
Added. ✅
