### ISSUE TITLE
Dark theme / circle-half-full

### ISSUE THREAD

**Issue by sabuhikhalili** [Templarian/MaterialDesign#4475]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by sabuhikhalili** [comment]
It is similar to 50/50 of who wants to be millionaire game. Circle and inside 50/50. I couldn't find any icon that represents half of anything.

**Comment by JapanYoshi** [comment]
Try [circle-slice-4](http://materialdesignicons.com/icon/circle-slice-4)

**Comment by MrGrigri** [comment]
I know that [Material Design Documentation](https://material.io/design/color/dark-theme.html#behavior) suggests using the `brightness-4` to go to a dark theme and `brightness-7` to go to a light theme.

**Comment by sabuhikhalili** [comment]
Thanks for all the comments. Much appreciated. I guess circle-slice will not be bad option for me given the alternatives.
