### ISSUE TITLE
seat-passenger / seat-passenger-*

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#4476]
It would be great to have a "passenger" icon like :
![image](https://user-images.githubusercontent.com/45227578/66310163-c88b5f80-e90b-11e9-90e4-b23c413f5092.png)

**Comment by GreenTurtwig** [comment]
![http://materialdesignicons.com/icon/seat-recline-normal](http://materialdesignicons.com/icon/seat-recline-normal)![http://materialdesignicons.com/icon/seat-recline-extra](http://materialdesignicons.com/icon/seat-recline-extra)![http://materialdesignicons.com/icon/car-seat](http://materialdesignicons.com/icon/car-seat)

**Comment by antembmip** [comment]
I have seen these icons. But for me, icons look like driver icon and not passenger icon.

**Comment by Templarian** [comment]
Removing the steering wheel arm looks like the change needed for this.

**Comment by MrGrigri** [comment]
I think it'll look weird without the arms or with the arms laying down to the side.

**Comment by Templarian** [comment]
In context I think it might be fine. Lets get some design ideas for this first.

**Comment by goyney** [comment]
I agree with @MrGrigri, this provide no new meaning over the existing version.

![image](https://user-images.githubusercontent.com/1015040/66724941-fc79ef80-edf9-11e9-98a0-cf0fa10d1f28.png)
[seat-passenger.svg.zip](https://github.com/Templarian/MaterialDesign/files/3722665/seat-passenger.svg.zip)

**Comment by Templarian** [comment]
I think in context with a diagram showing top down seats this will make more sense in a vehicle.
