### ISSUE TITLE
document camera

### ISSUE THREAD

**Issue by Josef-Friedrich** [Templarian/MaterialDesign#4477]
I wrote a app for an document camera. I have drawn two icons: document-camera and document-camera-off. I used the icon cctv as a starting point. Maybe someone else needs this icons. I want to contribute this two icons.

![](http://ashlandtech.org/wp-content/uploads/2016/03/The-ELMO-TT-12-Document-Camera.jpg)

[document-camera.zip](https://github.com/Templarian/MaterialDesign/files/3699339/document-camera.zip)

**Comment by Josef-Friedrich** [comment]
![document-camera-off svg](https://user-images.githubusercontent.com/545838/66347249-3196c580-e954-11e9-8fef-0a4eef447812.png)

**Comment by JapanYoshi** [comment]
I wouldn't understand that icon on first view. If your app is specifically for document cameras, why not just use the standard `camera` or `video` icons, and let the app itself provide the context for it?

This is probably a bad example, but the official YouTube app uses `tune` to mean sorting, even though the icon could mean equalizer on a music app. The extra meaning is provided by the fact that the icon is placed above the comment section, and not a media control toolbar.

**Comment by snis** [comment]
Just an idea.

![image](https://user-images.githubusercontent.com/205149/82143543-03ac2480-9845-11ea-8a6a-ba0a14e057e7.png)

![image](https://user-images.githubusercontent.com/205149/82143578-3b1ad100-9845-11ea-9372-07af3d280ec2.png)

**Comment by goyney** [comment]
Got a little too literal there with the document embedded in the camera. 😆 

Added these!
[![camera-document](https://materialdesignicons.com/icon/camera-document)](https://materialdesignicons.com/icon/camera-document)[![camera-document-off](https://materialdesignicons.com/icon/camera-document-off)](https://materialdesignicons.com/icon/camera-document)
