### ISSUE TITLE
alert-circle-outline with check mark

### ISSUE THREAD

**Issue by smeijer** [Templarian/MaterialDesign#4478]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To indicate issue status in a custom github interface, I need to have something like the `alert-circle-outline` icon, with the tiny check mark. Just like github has.

## Examples

We have: https://materialdesignicons.com/icon/alert-circle-outline

![image](https://user-images.githubusercontent.com/1196524/66349707-c8b24c00-e959-11e9-9b03-7333582a83f0.png)

But github also has one with a check-mark:

![image](https://user-images.githubusercontent.com/1196524/66349822-0911ca00-e95a-11e9-944b-8fc7bc0c8205.png)

It would be nice to have one similar to that.

**Comment by Templarian** [comment]
Added: 
[![alert-circle-check](https://materialdesignicons.com/icon/alert-circle-check)](https://materialdesignicons.com/icon/alert-circle-check)[![alert-circle-check-outline](https://materialdesignicons.com/icon/alert-circle-check-outline)](https://materialdesignicons.com/icon/alert-circle-check-outline)
