### ISSUE TITLE
Discrepancies with official Google icons?

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4479]
I've come across some discrepancies between MDI icons and their official Google counterparts, sometimes major, sometimes minute.

For example, we may have a community-contributed icon, when an official Google one exists. Increasingly occurs, as new icons are added or updated in the Google library.

Do we address this? How?

Examples:

Google: [emoji_events](https://material.io/resources/icons/?icon=emoji_events&style=baseline)
MDI: [trophy](https://materialdesignicons.com/icon/trophy)

Google: [sports_baseball](https://material.io/resources/icons/?icon=sports_baseball&style=baseline)
MDI: [baseball](https://materialdesignicons.com/icon/baseball)

Google: [visibility (outline)](https://material.io/resources/icons/?search=visi&icon=visibility&style=outline)
MDI: [eye-outline](https://materialdesignicons.com/icon/eye-outline)

Google: [description](https://material.io/resources/icons/?icon=description&style=baseline)
MDI: [file-document](https://materialdesignicons.com/icon/file-document)

Google: [image (outline)](https://material.io/resources/icons/?search=image&icon=image&style=outline)
MDI: [image-outline](https://materialdesignicons.com/icon/image-outline)

**Comment by Templarian** [comment]
Usually if we like ours more we just keep it (tons of issues with discussions and votes). It use to come up a while ago since this project is a few months older than the Google project. Doesn't happen much since they only add a few icons every so often.

All of these are minor differences. Nothing enough for us to change.

Naming Guidelines: https://dev.materialdesignicons.com/contribute/icon-naming

**Comment by Templarian** [comment]
Inversely if we don't like our design and they improved it we reassign it to Google and update the path.

**Comment by Templarian** [comment]
Note: We get most of the new icons from Google official apps and their extended set.

https://petershaggynoble.github.io/MDI-Sandbox/extended/ Peter maintains this. We use it to monitor their updates. ✅

**Comment by frankgrinaert** [comment]
Cool, thanks!
