### ISSUE TITLE
7 icons — Work, Safety & Travel

### ISSUE THREAD

**Issue by vitavalka** [Templarian/MaterialDesign#4480]
**Hello guys, I am new here.** For a long time I have used your library, plus I have created hundreds of icons (not just MD). So I have collected 7 pieces of icons, used in my projects that were missing for me. And I would like to contribute them for you & others to benefit. Unless you think any of those icons is out of scope. In such case I apologise for taking your time.

Please do comment on any of those as that helps me improve.

My humble thank you — Vita

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines]

## Preview

![ico-boot](https://user-images.githubusercontent.com/2325142/66407977-66575b00-e9ee-11e9-9273-225460771f4a.png)
![ico-accident](https://user-images.githubusercontent.com/2325142/66407987-6a837880-e9ee-11e9-85a8-7a566dc0cc91.png)
![ico-calendar-span](https://user-images.githubusercontent.com/2325142/66407993-6ce5d280-e9ee-11e9-80e7-b51acb7f3382.png)
![ico-categories](https://user-images.githubusercontent.com/2325142/66407998-6fe0c300-e9ee-11e9-96e4-1cab9e798043.png)
![ico-files](https://user-images.githubusercontent.com/2325142/66408004-71aa8680-e9ee-11e9-8010-67afa84dfbfd.png)
![ico-pool-roof](https://user-images.githubusercontent.com/2325142/66408010-74a57700-e9ee-11e9-8a64-5a0c9dacd02d.png)
![ico-robot-factory](https://user-images.githubusercontent.com/2325142/66408016-77a06780-e9ee-11e9-884c-d7cd758caec4.png)

## Zip Download

[vitavalka-7icons.zip](https://github.com/Templarian/MaterialDesign/files/3703174/vitavalka-7icons.zip)

**Comment by MrGrigri** [comment]
Thanks for providing the icons. Here are some critiques:

* The `boot` icon is too detailed. I would remove the inner square and the quarter circle cutout.
* The `accident` icon looks off. Idk if it's just the body shape or what...but something is off.
* Idk how I feel about the `calendar-span` but it looks good enough to add.
* The `categories` icon already exists as `file-tree`. That icon could do with a new request for an outlined variant
* The `files` icon. Is that supposed to be a series of binders on a shelf? Idk how that represents files.
* The `pool-roof` icon to me doesn't appear to represent a pool's roof and might be too niche. 
* The `robot-factory` icon already exists as `robot-industrial`. We might want to add a few aliases to that icon.

**Comment by JamesCoyle** [comment]
- Yeah the boot would be good without the detail.
- I'd remove the line and two dots on the accident icon and just have the person centered.
- I actually prefer this categories icon to the `file-tree` we have. The squares make it a bit more general purpose.

**Comment by Templarian** [comment]
One thing to add.

- `shoe-boot` needs to be the name. Definitely think we need this icon, just need the design tweaks suggested.
- `pool-indoor` naming
- `accident` is a great icon, but not sure about the pallet or what the boxes are?
- We can definitely tweak `file-tree` and make an outline. Note the rounded borders will need to be changed.
- `calendar-span`... wouldn't the arrows be pointing left and right? But I like the idea for this icon.

**Comment by vitavalka** [comment]
Thank you! All suggestions helped & make perfect sense. I've updated the set and here's the result.  

- As for the `calendar-span` - I have made arrows in both directions. Still I like the original one, as it implies locking in a date period. I've used that one on a travel portal where user can set the (maximum) length of the stay in days. The outward direction implies more a free/floating period.
- The `accident` icon had those things as a symbol for we/messy floor in a workshop or factory. But it's not necessary, so I've removed those details.
- Rounded corners from `file-tree` are gone now.
- Sorry @MrGrigri for bad name for the files, that's my bad English. Renamed to `binders`.
- I've kept the 24x24px bounding box there in the SVGs as opacity 0.0, should I rather get rid of it?

[vitavalka-8icons-fix1.zip](https://github.com/Templarian/MaterialDesign/files/3710850/vitavalka-8icons-fix1.zip)

**Comment by JapanYoshi** [comment]
The only thing I don't like is `binders`, which has dimensionality that doesn't really help express the meaning. Also, I think the shoelaces on the boot can be omitted and keep the iconicity.

**Comment by smeijer** [comment]
- I think `binders` looks off, because most (all?) other icons have their "multiple" variants rendered as being stacked on top of each other. Not next to each other.

> The accident icon looks off. Idk if it's just the body shape or what...but something is off.

I think it's because one arm is curvy, while all other limbs have sharp corners. Google Images shows some nice suggestions on "accident icon". The one in the middle is quite clear to me. Not to detailed, but still obvious. Just remove the circle?

(possibly copyrighted:)
![image](https://user-images.githubusercontent.com/1196524/66646695-36df6300-ec27-11e9-9859-5874f452c2bb.png)


- I do like this robot variant more than the current `robot-industrial`. The suggestion here, is more clear when scaled down.

**Comment by vitavalka** [comment]
Thank you @smeijer 👍 
Here's an updated inspired by your suggestion:
<img width="413" alt="preview" src="https://user-images.githubusercontent.com/2325142/66657496-37d0be80-ec40-11e9-8124-12908055c7fd.png">

**Comment by MrGrigri** [comment]
I believe we should have these icons as separate requests. I'm going to close this issue and @vitavalka, if you could create a separate issue for each of the icon that you wish to contribute. It helps us track each of them better.

**Comment by smeijer** [comment]
Came across a binder icon today, just dropping it here as inspiration, in case this icon will find further development.

<img src="https://user-images.githubusercontent.com/1196524/67041250-88a35400-f125-11e9-88c7-d74ca13ea335.png" width=32 />

I think when removing the perspective, it will match a bit better with icons like inbox:

<img src="https://user-images.githubusercontent.com/1196524/67041370-cef8b300-f125-11e9-9653-626f187ece5a.png" width=128 />
