### ISSUE TITLE
Share all Icon

### ISSUE THREAD

**Issue by sergiocarlotto** [Templarian/MaterialDesign#4481]
I created these two icons to represent sharing with everyone in a group or sharing all items with someone. I followed the same pattern as responding (reply-all) to everyone already available in the library.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/2835460/66419054-be379700-e9d9-11e9-9003-984cfe3e458e.png)

![image](https://user-images.githubusercontent.com/2835460/66419171-f50dad00-e9d9-11e9-8683-2b7fedfc1d6e.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[share-all.zip](https://github.com/Templarian/MaterialDesign/files/3703835/share-all.zip)

**Comment by Templarian** [comment]
Added. 😃
