### ISSUE TITLE
Google Cloud icon

### ISSUE THREAD

**Issue by melanieplageman** [Templarian/MaterialDesign#4482]
I have:
- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

We use MaterialDesign icons in our Concourse resource descriptions to make it easier to see what kind of resource it is. Many of the resources are from Google Cloud Storage, so it would be nice to have a Google Cloud icon.

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/165995/66419158-66d4ff00-e9b8-11e9-869c-ed1b5b1136a2.png)

**Comment by MrGrigri** [comment]
FYI, this icon will be monochromatic.

**Comment by Templarian** [comment]
[![google-cloud](https://materialdesignicons.com/icon/google-cloud)](https://materialdesignicons.com/icon/google-cloud)

Wondering if this is too wide. 🤔
