### ISSUE TITLE
Time frame from creation to release? (looking at phone-ring)

### ISSUE THREAD

**Issue by Mantic** [Templarian/MaterialDesign#4484]
I see that `phone-ring` was created on Sept. 11, how long until an icon appears in the dist files? Sorry if this is a common question... I'm new! :P

**Comment by Templarian** [comment]
The release literally just went out. `@mdi/font` and `@mdi/svg` were published like 10 minutes ago.

But we do releases at 100 icons. + 1 day of preview on the CDN, and if there are no issues we publish to all the repos and NPM.

**Comment by Mantic** [comment]
Thank you so much! I had no idea this project existed until a few days ago. 10/10, will recommend.

**Comment by Templarian** [comment]
Be sure to spread the word with your design friends. 😉
