### ISSUE TITLE
rewind-5, fast-forward-5

### ISSUE THREAD

**Issue by miluxmilux** [Templarian/MaterialDesign#4485]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Hi!
Since I couldn't find an open related issue, I made a new one, hope it is ok ;)
I would like to migrate my whole project to mdi, but am missing 2 important icons for my app : [Replay5](https://material.io/resources/icons/?search=replay&icon=replay_5) and [Forward5](https://material.io/resources/icons/?search=forward&icon=forward_5&style=baseline). Would it be possible to add them to mdi ? 
Maybe it would make sense to also add Replay10, Replay30, Forward10 and Forward30.
Cheers.

**Comment by Templarian** [comment]
Do not delete the icon template when making an Icon Request. This has been pasted back in.

Unfortunately those go against the Material Design guidelines so they've been designed slightly different in MDI. `rewind-*`, `fast-forward-*` are the naming.

Should be doable.

**Comment by miluxmilux** [comment]
Thanks for your reply. I somehow didn't have a template when creating a new issue (?). Thanks for pointing to the existing icons and changing the title.

**Comment by Templarian** [comment]
Added. 👍

**Comment by miluxmilux** [comment]
Thanks!
