### ISSUE TITLE
account-multiple-remove(-outline)

### ISSUE THREAD

**Issue by ekuleshov** [Templarian/MaterialDesign#4488]
I have:

- [+] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [+] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [+] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Need an icon to remove all accounts (or all persons) in the app.

## Examples

There are [account-multiple-outline](https://materialdesignicons.com/icon/account-multiple-outline) and [account-multiple](https://materialdesignicons.com/icon/account-multiple) icons.
The one I'm looking for could look like those icons with an X symbol added at the bottom right, similar to [playlist-remove](https://materialdesignicons.com/icon/playlist-remove) icon.

this will also match style of [account-check](https://materialdesignicons.com/icon/account-check), [account-clock-outline](https://materialdesignicons.com/icon/account-clock-outline) and [account-edit](https://materialdesignicons.com/icon/account-edit) icons.

**Comment by MrGrigri** [comment]
Before creating these icons, we'll have to settle #4489 first.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/66679425-61331f80-ec2b-11e9-9064-d0b28205779a.png) ![image](https://user-images.githubusercontent.com/4528551/66679445-6b551e00-ec2b-11e9-8e6c-36f6df69530b.png)

---
#### Files

[account-multiple.zip](https://github.com/Templarian/MaterialDesign/files/3719354/account-multiple.zip)

**Comment by ekuleshov** [comment]
Thank you @MrGrigri though that matches with other account icons (minus, plus, heart, etc), I was hoping for the `playlist-remove` style. I wonder how come there are two styles there?

My personal preference is to have a decoration or indicator on the right side of the main shape and it seem to be most common too. Have to try both in the interface to get a better feel for it.

**Comment by MrGrigri** [comment]
The reason I made it to the left is because of consistency. As you stated, they are to the left to be consistent. They are there because the cutout of the second person is on the right (consistent with `account-multiple`) and it doesn't look right with both are on the same side.

**Comment by ekuleshov** [comment]
Speaking of consistency there are icons like [account-search](https://materialdesignicons.com/icon/account-search)

I understand about the shadow being on the right. Maybe a strike-trough variant similar to [account-off-outline](https://materialdesignicons.com/icon/account-off-outline) may work better

**Comment by goyney** [comment]
[![account-multiple-remove](https://materialdesignicons.com/icon/account-multiple-remove)](https://materialdesignicons.com/icon/account-multiple-remove)[![account-multiple-remove-outline](https://materialdesignicons.com/icon/account-multiple-remove-outline)](https://materialdesignicons.com/icon/account-multiple-remove-outline)

**Comment by MrGrigri** [comment]
Is there something wrong with the paths? 

![image](https://user-images.githubusercontent.com/4528551/66727825-cd19b180-edfe-11e9-9001-a1412cdf76c9.png)

**Comment by Templarian** [comment]
Definitely looks like there is something wrong. This uses the standard imagemagick API to render the SVG to an image. If it fails there it's probably a broken path.
