### ISSUE TITLE
more vector icons

### ISSUE THREAD

**Issue by TheCamel** [Templarian/MaterialDesign#449]
it exist vector...what about circle, triangle, polyline, etc..with the little square, it is very nice

**Comment by CoDEmanX** [comment]
Does #829 close this issue?
We could add filled variants for the triangle, polygon and both circle icons, if it helps. Or should there be no squares at the corner points?

**Comment by Templarian** [comment]
Ehh... lets not on the filled. I think this issue is closed.

[![vector-rectangle](https://materialdesignicons.com/icon/vector-rectangle)](https://materialdesignicons.com/icon/vector-rectangle)
