### ISSUE TITLE
account-multiple-check-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4490]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/66680726-647bda80-ec2e-11e9-98f9-4efbb41228ca.png)

## Zip Download

[account-multiple-check-outline.zip](https://github.com/Templarian/MaterialDesign/files/3719404/account-multiple-check-outline.zip)

**Comment by goyney** [comment]
[![account-multiple-check-outline](https://materialdesignicons.com/icon/account-multiple-check-outline)](https://materialdesignicons.com/icon/account-multiple-check-outline)
