### ISSUE TITLE
cradle

### ISSUE THREAD

**Issue by diaperexpert** [Templarian/MaterialDesign#4493]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Illustrating blog articles

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/56486213/66705778-6bd4de00-ed2b-11e9-83a5-861dd94f87cd.png)

**Comment by goyney** [comment]
[![cradle](https://materialdesignicons.com/icon/cradle)](https://materialdesignicons.com/icon/cradle)[![cradle-outline](https://materialdesignicons.com/icon/cradle-outline)](https://materialdesignicons.com/icon/cradle-outline)
