### ISSUE TITLE
Mirror Icon

### ISSUE THREAD

**Issue by phcella** [Templarian/MaterialDesign#4494]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I installed a led strip bihind my bathroom mirror. And there is no icon that represent mirror.

## Examples

https://thenounproject.com/creativestall/collection/furniture-material-design-icons/?i=382936

I made a file on illustrator, but I don't know if it is right

[mirror.zip](https://github.com/Templarian/MaterialDesign/files/3721018/mirror.zip)

**Comment by Templarian** [comment]
@phcella Can you attach a svg file.

**Comment by phcella** [comment]
> @phcella Can you attach a svg file.

The svg file is attached... Thanks
[mirror.zip](https://github.com/Templarian/MaterialDesign/files/3721776/mirror.zip)

**Comment by Templarian** [comment]
This might have too much unnecessary detail. Maybe something much simpler like this....

![image](https://user-images.githubusercontent.com/338885/66720686-c91d6d80-edc5-11e9-86e2-ec3449d32984.png)

**Comment by Templarian** [comment]
Added.
