### ISSUE TITLE
GIS icon set

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4497]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

I would like to start to contribute a GIS (geographic information system) icon set.

To start with I hereby try to contribute 5 typical icons used in GIS in order to get some feedback and see if I understood properly how to create them.

I hope there is interest for an addition of this type. 

## Preview

Add raster layer:

![image](https://user-images.githubusercontent.com/390250/66716562-6204b680-edcf-11e9-8e1b-10d509a670b8.png)

Delete vector layer:

![image](https://user-images.githubusercontent.com/390250/66716672-b492a280-edd0-11e9-8f27-b491e41e7b64.png)

Zoom by box:

![image](https://user-images.githubusercontent.com/390250/66716689-e6a40480-edd0-11e9-90e8-17513a5f0c6b.png)

Zoom to extent:

![image](https://user-images.githubusercontent.com/390250/66716771-fc65f980-edd1-11e9-86b5-3af8a41e3efa.png)

Zoom to layer:

![image](https://user-images.githubusercontent.com/390250/66716783-24edf380-edd2-11e9-8721-44c44ae95dc6.png)

## Zip Download

Not sure if this one is correct, in case pleaes let me know. Opening it with a text editor it starts with the svg tag and the path has been joined in a single one.

[gis-materialdesignicons.zip](https://github.com/Templarian/MaterialDesign/files/3721826/gis-materialdesignicons.zip)

**Comment by Templarian** [comment]
Some feedback on these:

- `*-plus` and `*-minus` need to follow the standard cutout, preferably in the bottom corner.
  - `raster` could use `checkerboard` as the guidelines enforce minimum detail.
- `gis-vector` needs to use a `2dp` line.
- `*-search` is a standard cutout. It does not use the full sized `magnify` icon.
- There is a `layer` base icon already. Maybe adding search modifier to those?

**Comment by goyney** [comment]
- `gis-raster-add-layer` will be handled by #4499.
- `gis-vector-remove-layer` - ??? - This and `raster-add-layer` can also be solved by using `layers-add` and `layers-minus` to be less specific.
- `gis-zoom-by-box` will be handled by #4500.
- `gis-zoom-extent` will be handled by #4502.
- `gis-zoom-to-layer` will be handled by #4501.

**Comment by goyney** [comment]
> get some feedback and see if I understood properly how to create them

I think all of these icons are generic enough and are not specific to just GIS. Therefore, they all make good contributions in one way or another. The best advice I could give to you is find a base icon (if it exists) in the library and use it as a base for your modifiers, following how we do modifiers on each other icon. Also, take a look at the [Material guidelines ](https://material.io/design/iconography/system-icons.html#design-principles)for all the gotchas we have to consider when adding new icons.

Since everything in this issue is now addressed in subsequent issues, feel free to create new issues for other icons you may want to see added. Please remember, one icon per issue. Thank you!

**Comment by moovida** [comment]
@goyney , @Templarian,  thanks for the feedback.

A few comments/questions:
1. I think there is the need for both raster and vector layer in the GIS case. They point to very different properties. Am I allowed to create also the vector layer ones?
2.  regarding the material guidelines, I thought I had applied them properly. Can you point me to the errors, so I can improve next time please?
3. I have now seen the overlay part to be followed here: http://dev.materialdesignicons.com/contribute/icon-naming will do
4. why is the magnifying glass in the search icon not consistent in shape with the magnify icons? Is that the case also with other icons

Big question: is there a way to create aliases? Thing is that it would improve a lot searching of icons. For example a GIS user looking for a raster icon will have to browse thousands of icons to find the checkerboard icon. Instead if he/she could insert **gis** in the search box and find all of one category, that would be awesome. 

Ok, heading over to the subissues. Thanks

**Comment by moovida** [comment]
One more thing. I checked the documentation about the overlays and what I find is:

![image](https://user-images.githubusercontent.com/390250/66729886-8f447980-ee4e-11e9-8117-6497d819b502.png)

The circle seems to get to half of the icon in width. But for example in issue #4499 the circle cut for the plus doesn't cover half icon, but less. 
So what do I need to consider?
