### ISSUE TITLE
Additional window-shutter icon

### ISSUE THREAD

**Issue by spali** [Templarian/MaterialDesign#4498]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There already 3 different `window-shutter` icons. I miss one for the shutter to be not open nor closed.
The same as `window-shutter-alert` but without the exclamation mark.
I use it four visualization in smart home.
I would like to show `window-shutter-open` for fully open shutter, `window-shutter` for completely closed shutter, `window-shutter-alert` for alerts/problems and the suggested new one for everything between open and closed shutter.

If it's not to much work... it would be also nice to have the states between based on the currently existing 1-4 elements inside the "window".
0%: would be the current `window-shutter-open` but without the single element
25% would be the current `window-shutter-open` with one element
50% would be the current `window-shutter-open` with two elements
75% would be the current `window-shutter-open` with three elements
100% would be the current `window-shutter` with four elements

The advantage of this would also be that the current names could be untouched and just have aliases for the existing reused ones. This wouldn't introduce a breaking change.

## Examples

-

**Comment by drash1** [comment]
Hello, I was just looking to request the exact same thing. Looking forward to get this available.

**Comment by goyney** [comment]
Our `window-shutter` icons follow the same design pattern as our `garage` icons. We've had extensive discussions in the past around the garage icon and decided against adding a ton of variants around it, including more granular door states. That decision will stand with the newer `window-shutter` icons and we won't be adding middle states. Thank you for your suggestion.
