### ISSUE TITLE
checkerboard-(plus|minus|remove)

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4499]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

This is a fork from issue #4497.

## Preview

![image](https://user-images.githubusercontent.com/1015040/66725277-41a02080-edfe-11e9-84d9-674633720642.png)
![image](https://user-images.githubusercontent.com/1015040/66725279-4b298880-edfe-11e9-873f-4b54573a2db6.png)
![image](https://user-images.githubusercontent.com/1015040/66725281-52509680-edfe-11e9-9f7b-264d6eecf6e9.png)

## Zip Download

[checkerboard.zip](https://github.com/Templarian/MaterialDesign/files/3722685/checkerboard.zip)

**Comment by Templarian** [comment]
The cut out doesn't really work great in this case. May need to modify the checkerboard so it is divided more. 🤔

**Comment by goyney** [comment]
After internal discussion, we've decided to add some more detail to the `checkerboard` base so we can add modifiers that make sense. Therefore, the base `checkerboard` will be updated and then the 3 modifiers will be added.

![image](https://user-images.githubusercontent.com/1015040/66725594-97c29300-ee01-11e9-9e51-4d32d9078236.png)
![image](https://user-images.githubusercontent.com/1015040/66725598-9e510a80-ee01-11e9-8a61-292d5580d219.png)
![image](https://user-images.githubusercontent.com/1015040/66725602-a4df8200-ee01-11e9-8203-4c511bf11a7e.png)
![image](https://user-images.githubusercontent.com/1015040/66725608-add05380-ee01-11e9-98e7-a0749256c4b6.png)

**Comment by goyney** [comment]
[![checkerboard](https://materialdesignicons.com/icon/checkerboard)](https://materialdesignicons.com/icon/checkerboard)[![checkerboard-plus](https://materialdesignicons.com/icon/checkerboard-plus)](https://materialdesignicons.com/icon/checkerboard-plus)
[![checkerboard-minus](https://materialdesignicons.com/icon/checkerboard-minus)](https://materialdesignicons.com/icon/checkerboard-minus)[![checkerboard-remove](https://materialdesignicons.com/icon/checkerboard-remove)](https://materialdesignicons.com/icon/checkerboard-remove)
