### ISSUE TITLE
generic accept/decline icons

### ISSUE THREAD

**Issue by shainefisher** [Templarian/MaterialDesign#450]
It would be ideal if we had a generic accept/decline icons (check mark/cross x), for things like terms and conditions, yes/no for form buttons.
That would be really nice if they suddenly appeared.

Thanks

**Comment by Templarian** [comment]
These exist...

https://materialdesignicons.com/icon/check
https://materialdesignicons.com/icon/close

Unless you mean something else?

**Comment by shainefisher** [comment]
These are perfect, sorry about that, and thank you.
