### ISSUE TITLE
magnify-expand(-outline)

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4502]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

This is a fork of issue #4497.

Not really sure how I feel about this at the moment. It probably needs a few more passes on how to handle the arrows.

## Preview

![image](https://user-images.githubusercontent.com/1015040/66725872-a3af5480-ee03-11e9-8a11-428dd63aabe1.png)

## Zip Download

[magnify-expand.zip](https://github.com/Templarian/MaterialDesign/files/3722720/magnify-expand.zip)

**Comment by MrGrigri** [comment]
Our current `magnify` icon doesn't look like that. 

![magnify](https://materialdesignicons.com/icon/magnify).

**Comment by snis** [comment]
One with alternative arrows/borders

![image](https://user-images.githubusercontent.com/205149/82144266-09a30500-9847-11ea-90d6-558ccd934754.png)

**Comment by goyney** [comment]
[![magnify-expand](https://materialdesignicons.com/icon/magnify-expand)](https://materialdesignicons.com/icon/magnify-expand)
