### ISSUE TITLE
gis-vertex-(plus|minus|edit)

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4503]
I have:

- [x ] Searched open issues to make sure there isn't a request for this icon.
- [x ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

The only related icon I found, is the vector point icon.

## Preview

![image](https://user-images.githubusercontent.com/390250/66731556-3e398300-ee58-11e9-9293-4b5666364a2f.png)

![image](https://user-images.githubusercontent.com/390250/66731615-8e184a00-ee58-11e9-975f-b9ad24cd8d31.png)

![image](https://user-images.githubusercontent.com/390250/66731641-a25c4700-ee58-11e9-87af-06064a8b3dd0.png)

The zip contains also the non-outline version (not sure when the outline version makes sense though).

This, if accepted, would be done also for line and polygon shapes. 

For the edit icon, I used the account-edit icon as template.

## Zip Download

[gis-vertex.zip](https://github.com/Templarian/MaterialDesign/files/3723132/gis-vertex.zip)

**Comment by moovida** [comment]
Adding also the plain vertex one:

![image](https://user-images.githubusercontent.com/390250/66733110-c3279b00-ee5e-11e9-8606-444331dbb568.png)

Re-add the zip here in order to:
* add also the plain vertex
* moved the right-most vertex properly to work better with the line icon in #4504 and be coherent

[gis-vertex.zip](https://github.com/Templarian/MaterialDesign/files/3723248/gis-vertex.zip)

**Comment by goyney** [comment]
I'm not quite sure what this icon is supposed to represent. Floating boxes? Also, they are not 2dp in thickness.

I think a generic `box-plus` and `box-plus-outline` would handle adding something like a "vertex".

**Comment by moovida** [comment]
@goyney , I am trying to represent different shapes. To keep consistency, I was trying to make the points, lines and polygons using the same vertexes. Should I then try to make this as a single box?

**Comment by goyney** [comment]
Closing in favor of #4518.
