### ISSUE TITLE
vector-polyline-(plus|minus|edit)

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4504]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

The only related icons I found are vector-line and vector polyline, but the first has only a simple 2-nodes line and the second is a bit too narrow (maybe removing one node there might be an idea -> i.e. like the here proposed gis-line?). Here the vertices are kept the same as in #4503 on purpose.

## Preview

![image](https://user-images.githubusercontent.com/390250/66732780-7ee7cb00-ee5d-11e9-8304-b52868cafc6e.png)

![image](https://user-images.githubusercontent.com/390250/66732814-9fb02080-ee5d-11e9-8c88-2eb11fc409aa.png)

![image](https://user-images.githubusercontent.com/390250/66732851-ca9a7480-ee5d-11e9-8e9a-e1870adfa624.png)

![image](https://user-images.githubusercontent.com/390250/66732860-da19bd80-ee5d-11e9-940b-51696fa3b9c2.png)

## Zip Download

[gis-line.zip](https://github.com/Templarian/MaterialDesign/files/3723218/gis-line.zip)

**Comment by smeijer** [comment]
I think this icon would be `vector-polyline-plus`?

**Comment by MrGrigri** [comment]
Please follow the [Material Design Guidelines](https://material.io/design/iconography/system-icons.html#design-principles). Those strokes and square anchor points need to be 2-pixels wide.

**Comment by goyney** [comment]
We should use `vector-polyline` as the baseline for these.

**Comment by moovida** [comment]
@goyney as I wrote, I found the vector-polyline too narrow in its content. But if that is the will of most, i will redo them with that as baseline.

**Comment by MrGrigri** [comment]
We are very strict with the MD Guidelines as previously stated. all strokes are 2-pixels wide.

**Comment by moovida** [comment]
@MrGrigri , yes, I apologize for that and will keep that in mind. Thanks to everyone for the patience in the reviews.

**Comment by moovida** [comment]
@goyney , the problem with using vector-polyline with plus|minus|edit, is that there is no space:

![image](https://user-images.githubusercontent.com/390250/66828798-38c06380-ef52-11e9-8613-58b47e13efc7.png)

would it make sense to propose a change of the polyline icon to have more space (i.e. with one less vertex and rearranged)?
That would look like this:

![image](https://user-images.githubusercontent.com/390250/66828997-acfb0700-ef52-11e9-9262-54476d0a6970.png)

**Comment by goyney** [comment]
There's plenty of space using the standardized cut-out in the bottom corner.

**Comment by moovida** [comment]
@goyney I am not sure I understand. In the upper polyline (the one with 4 vertexes) I added the standard cut-out, taken from previous fixes that had been made on my issues.  
You mean what should be done is to cut the circle and remove piece of the vertex that overlays? I am trying to understand if that is preferred.

**Comment by JamesCoyle** [comment]
The cutout looks dumb IMO. I prefer the 3 point line above.

**Comment by MrGrigri** [comment]
BTW, @moovida, you can use our [preview generator](http://dev.materialdesignicons.com/contribute/github) to get a smaller preview for Github.

**Comment by Templarian** [comment]
Agreed, not sure the cut out makes sense in this case as it can be reworked.

**Comment by moovida** [comment]
Not being sure what happens next in these cases, I tried to create the set with the 3-vertex polyline. This is the outcome. 

To make the plain icon look better, I centered the polyline properly (it was a bit up top before).

I don't like the edit icon that much, the pencil is too near to the vetrex for small icons, but I would also not do a cutout. Might moving the vertex make sense? In which case the plain icon doesn't look all that good.

![image](https://user-images.githubusercontent.com/390250/66890365-37407b00-efe6-11e9-8b14-cdae067b8aff.png)

![image](https://user-images.githubusercontent.com/390250/66890381-49221e00-efe6-11e9-9512-9c5c7060840e.png)


![image](https://user-images.githubusercontent.com/390250/66890408-5ccd8480-efe6-11e9-9bc9-79a86eaacdf0.png)

![image](https://user-images.githubusercontent.com/390250/66890434-7b338000-efe6-11e9-9282-afe0999739b6.png)

for completeness:

[vector-polyline.zip](https://github.com/Templarian/MaterialDesign/files/3732556/vector-polyline.zip)

**Comment by MrGrigri** [comment]
Grazie per il tuo contributo.

**Comment by moovida** [comment]
Grazie mille for the patient reviews. This project is something huge and I would really like to slowly be able to contribute without involving too many people :-)

Just as information. I now leave this issue and someone of the bosses will take care of it? Or is there something else I need to do?

**Comment by JamesCoyle** [comment]
We'll leave this open until it is added to a release milestone by one of the team. It is now in the Upcoming Icons milestone which means it is awaiting release in a future version so there is nothing left for you to do. We look forward to your contributions in the future. 😃

**Comment by goyney** [comment]
[![vector-polyline](https://materialdesignicons.com/icon/vector-polyline)](https://materialdesignicons.com/icon/vector-polyline)[![vector-polyline-plus](https://materialdesignicons.com/icon/vector-polyline-plus)](https://materialdesignicons.com/icon/vector-polyline-plus)
[![vector-polyline-minus](https://materialdesignicons.com/icon/vector-polyline-minus)](https://materialdesignicons.com/icon/vector-polyline-minus)[![vector-polyline-remove](https://materialdesignicons.com/icon/vector-polyline-remove)](https://materialdesignicons.com/icon/vector-polyline-remove)
[![vector-polyline-edit](https://materialdesignicons.com/icon/vector-polyline-edit)](https://materialdesignicons.com/icon/vector-polyline-edit)
