### ISSUE TITLE
dot-net-core

### ISSUE THREAD

**Issue by WhiteBookmark** [Templarian/MaterialDesign#4506]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

While we have dot-net icon which is perfect for showing .NET framework, however, .NET Core is a completely different framework and using the same icon for both would be confusing.

## Examples

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/.NET_Core_Logo.svg/1200px-.NET_Core_Logo.svg.png" width="100" height="100">

**Comment by goyney** [comment]
I don't know how this will work. We already have a generic .NET icon, but even adding "Core" to that would be unintelligible. There isn't any alternative logo for the language either, they literally use the text.

**Comment by Templarian** [comment]
As a C# dev I understand this would be useful, but it probably going to be too difficult to display inside of the small size.

`Core` text would be absolutely tiny and unreadable.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/66791918-eb91b280-eebb-11e9-93bc-6042f918727e.png)

**Comment by WhiteBookmark** [comment]
How about making it inline instead of wrapping ? I think that would solve issue of displaying in small size.

**Comment by Templarian** [comment]
@WhiteBookmark That would make the text far too small to read at 24x24. All icons need to be readable at 24x24 and a lot of the examples I see online seem to stack it like this.

**Comment by JamesCoyle** [comment]
I really don't see the need to differentiate Core, Framework, and Standard in a tiny icon. They are all pretty similar so the .NET icon should cover the whole .NET ecosystem. If you need to differentiate I'd personally just use text which will be more readable and more semantic.

**Comment by Templarian** [comment]
Realistically .net Core is the future of the platform and they stopped updating legacy .NET so I think it will be fine just having a single icon.
