### ISSUE TITLE
approximately-not-equal

### ISSUE THREAD

**Issue by tsiryulya** [Templarian/MaterialDesign#4507]
I think a negative approximate sign should be added.

![Screenshot_1](https://user-images.githubusercontent.com/40541362/66743301-cb55f980-eea3-11e9-9e83-a08eb7e333b1.png)

**Comment by MrGrigri** [comment]
This seems very niche!

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/66762539-32f45080-ee74-11e9-9059-bb0d22298a20.png)
[approximately-equal-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/3725130/approximately-equal-off.svg.zip)

**Comment by MrGrigri** [comment]
Here is the icon if we decide to add it.

![image](https://user-images.githubusercontent.com/4528551/66762965-35e74500-ee64-11e9-847b-869e285f3a59.png)


---
#### Files

[approximately-not-equal.zip](https://github.com/Templarian/MaterialDesign/files/3725161/approximately-not-equal.zip)

**Comment by MrGrigri** [comment]
I believe this is going to be too niche. 'Not approximately' and 'approximately' are the same meaning. 3.14159 is approximately 3.14 and also not approximately 3.14.
