### ISSUE TITLE
function(-variant)-off

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4508]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

We have need for these in a spreadsheet application.

## Preview

![image](https://user-images.githubusercontent.com/1015040/66774924-d05d7d80-ee90-11e9-8c1b-5253417a67d4.png)
![image](https://user-images.githubusercontent.com/1015040/66774941-da7f7c00-ee90-11e9-9b5d-ac61ca07553f.png)

## Zip Download

[function-off.zip](https://github.com/Templarian/MaterialDesign/files/3725938/function-off.zip)

**Comment by Templarian** [comment]
Not sure if this works for these two. Is there another way they could be represented?

**Comment by MrGrigri** [comment]
Is this icon used to clear a function within a cell?
