### ISSUE TITLE
table-headers

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4509]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/66775852-ff74ee80-ee92-11e9-8ce5-41024f8c6e7a.png)

## Zip Download

[table-headers.svg.zip](https://github.com/Templarian/MaterialDesign/files/3725993/table-headers.svg.zip)

**Comment by MrGrigri** [comment]
With @goyney's contribution, it focuses on the data cells and not the headers themselves. This icon represents both the toggle-ability of showing and hiding the headers but also focuses on the headers themselves and not the data.

![image](https://user-images.githubusercontent.com/4528551/66776030-b2891c00-ee82-11e9-89b3-1403e28da69e.png) ![image](https://user-images.githubusercontent.com/4528551/66776035-b61ca300-ee82-11e9-868b-2dbe9fb03b96.png)

---

#### Files

[table-headers-eye.zip](https://github.com/Templarian/MaterialDesign/files/3726011/table-headers-eye.zip)

**Comment by goyney** [comment]
[![table-headers-eye](https://materialdesignicons.com/icon/table-headers-eye)](https://materialdesignicons.com/icon/table-headers-eye)[![table-headers-eye-off](https://materialdesignicons.com/icon/table-headers-eye-off)](https://materialdesignicons.com/icon/table-headers-eye-off)
