### ISSUE TITLE
New Google Photos Assistant icon

### ISSUE THREAD

**Issue by renanferrari** [Templarian/MaterialDesign#451]
I'd like to see the [new Google Photos Assistant icon](http://i.imgur.com/2R1pTbc.png).

Thanks for doing this! :)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/file-image-box ? This one

**Comment by Templarian** [comment]
This will be closed in #420. Thanks for opening an issue.

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/assistant
