### ISSUE TITLE
semantic-web

### ISSUE THREAD

**Issue by ecow** [Templarian/MaterialDesign#4510]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To denote a Semantic web resource (RDF/linkeddata/solid) 

## Examples

An example  from [rdf wikimedia common resource](https://commons.wikimedia.org/wiki/File:Rdf_logo.svg)

![image](https://user-images.githubusercontent.com/5788689/66813865-e07b6880-ef35-11e9-8931-35df377b8984.png)

A simpler example:

![image](https://user-images.githubusercontent.com/5788689/66813789-ba55c880-ef35-11e9-9135-42de3b155563.png)

**Comment by goyney** [comment]
The RDF logo above is [deprecated](https://www.w3.org/RDF/icons/), so it will not be added. We can add the Semantic Web icon, though, on that same page, so I'm adjusting this issue to add that icon instead.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/72310581-17097200-3650-11ea-8be8-7b458615559d.png)
[semantic-web.svg.zip](https://github.com/Templarian/MaterialDesign/files/4057145/semantic-web.svg.zip)

**Comment by goyney** [comment]
[![semantic-web](https://materialdesignicons.com/icon/semantic-web)](https://materialdesignicons.com/icon/semantic-web)

**Comment by goyney** [comment]
@PeterShaggyNoble Pinging you for potential addition to Simple Icons.

**Comment by PeterShaggyNoble** [comment]
Thanks, @goyney; Issue created at [SI#2366](https://github.com/simple-icons/simple-icons/issues/2366).
