### ISSUE TITLE
bus-marker

### ISSUE THREAD

**Issue by Akkanura** [Templarian/MaterialDesign#4512]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It would be great to have an icon for a bus stop with a marker
This is to indicate the location of a bus stop.

## Examples

![bus-stop-marker](https://user-images.githubusercontent.com/15104196/66844411-8d71d780-ef6e-11e9-90a2-8c660e433760.png)

**Comment by MrGrigri** [comment]
We have `bus-stop`, `bus-stop-covered`, and `bus-stop-uncovered`. Do neither of these work for you?

![bus-stop](https://materialdesignicons.com/icon/bus-stop)  ![bus-stop-covered](https://materialdesignicons.com/icon/bus-stop-covered) ![bus-stop-uncovered](https://materialdesignicons.com/icon/bus-stop-uncovered)

**Comment by Akkanura** [comment]
Yes, I have seen those but it doesn't work. 
We display bus top on a map and for those we use the icon "bus-stop", but we also need to indicate that the bus is located on a particular stop so this is why I propose bus-stop-marker.

**Comment by Akkanura** [comment]
No because the bus can be anywhere else, that's why I thought about the icon bus-stop but with a marker

**Comment by MrGrigri** [comment]
Idk if this looks good with our current bus modifier schema. But I've added it in case others feel differently.

![image](https://user-images.githubusercontent.com/4528551/66939237-efc6e880-efff-11e9-92ef-bb04e919dff5.png)

---
#### Files

[bus-map-marker.zip](https://github.com/Templarian/MaterialDesign/files/3735402/bus-map-marker.zip)

**Comment by MrGrigri** [comment]
A milestone will be added if this icon is agreed upon to be added.

**Comment by Templarian** [comment]
Maybe solid with a cut out? Not sure though how that would look.

**Comment by MrGrigri** [comment]
Yeah, I tried that, but it didn't look good at all.

**Comment by MrGrigri** [comment]
Here are all three options:

![image](https://user-images.githubusercontent.com/4528551/66942574-9f9f5480-f006-11e9-8dc5-a8705ebce2c9.png) ![image](https://user-images.githubusercontent.com/4528551/66942633-be9de680-f006-11e9-8162-5f8b74031398.png) ![image](https://user-images.githubusercontent.com/4528551/66942666-ccec0280-f006-11e9-9f31-cab3288fcaf7.png)

---
#### Files
[bus-map-marker.zip](https://github.com/Templarian/MaterialDesign/files/3735591/bus-map-marker.zip)

**Comment by Templarian** [comment]
My vote is for 3 simply for the fact we can make it a standard cutout going forward. A lot of icons could use a `*-map-marker` for location.

**Comment by Templarian** [comment]
Just realized we have a few icons with `-marker` already. As long as it matches those they are good to be added.

**Comment by MrGrigri** [comment]
We'll be adding the second option then. 

![image](https://user-images.githubusercontent.com/4528551/67241769-49b91b00-f411-11e9-97c3-58bec2832598.png)

---

[bus-map-marker-2.zip](https://github.com/Templarian/MaterialDesign/files/3752828/bus-map-marker-2.zip)

**Comment by goyney** [comment]
[![bus-marker](https://materialdesignicons.com/icon/bus-marker)](https://materialdesignicons.com/icon/bus-marker)
