### ISSUE TITLE
cash-plus and cash-minus

### ISSUE THREAD

**Issue by sergiocarlotto** [Templarian/MaterialDesign#4513]
Hello, here are two suggestions of icons, I needed to use in a project to indicate the action of making withdrawals and entries of values.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/2835460/66850053-69060300-ef4e-11e9-807f-71c342759180.png)

![image](https://user-images.githubusercontent.com/2835460/66850097-7cb16980-ef4e-11e9-85e3-949e3ede9a0c.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[cash-plus-and-minus.zip](https://github.com/Templarian/MaterialDesign/files/3730388/cash-plus-and-minus.zip)

**Comment by Templarian** [comment]
`cash-remove` was also added. Bit of delay getting these added.

Thanks. Let me know if you create 3 more and I'll assign these over to a contributor account.

**Comment by sergiocarlotto** [comment]
> `cash-remove` was also added. Bit of delay getting these added.
> 
> Thanks. Let me know if you create 3 more and I'll assign these over to a contributor account.

Yes, it already contributes with 4 other icons:
api-off
https://github.com/Templarian/MaterialDesign/issues/4561

share-all
share-outline-all
https://github.com/Templarian/MaterialDesign/issues/4481

router
https://github.com/Templarian/MaterialDesign/issues/4425
