### ISSUE TITLE
chart-multiple

### ISSUE THREAD

**Issue by Pathfinder216** [Templarian/MaterialDesign#4514]
I have:

- [x] Searched for the icon in the current library
- [x] Searched for the icon in the issues

### Usage
To signify multiple charts.

### Example
![image](https://user-images.githubusercontent.com/17412026/66851829-9e5c2200-ef49-11e9-87b7-f2802a24185b.png)
[chart-bell-curve-multiple.zip](https://github.com/Templarian/MaterialDesign/files/3730512/chart-bell-curve-multiple.zip)

**Comment by MrGrigri** [comment]
Your contribution will not be counted until there is an SVG provided with a single compound path. Please ensure the path is valid by using our [image preview generator](http://dev.materialdesignicons.com/contribute/github).

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/66980539-d745e500-f076-11e9-9bf6-53eb2e76c303.png)

Not sure how I like it with `chart-bar`

**Comment by MrGrigri** [comment]
I believe that `chart-line` would work best for this request.

![image](https://user-images.githubusercontent.com/4528551/67024226-4811ef00-f0c1-11e9-9be7-ef7be9adc5e6.png)

---

[chart-multiple.zip](https://github.com/Templarian/MaterialDesign/files/3740110/chart-multiple.zip)

**Comment by goyney** [comment]
[![chart-multiple](https://materialdesignicons.com/icon/chart-multiple)](https://materialdesignicons.com/icon/chart-multiple)
