### ISSUE TITLE
radio-off

### ISSUE THREAD

**Issue by Zoara** [Templarian/MaterialDesign#4515]
I have:

- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/11468496/66878742-2c4b0380-ef70-11e9-9dcc-4944a1fe1c28.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by goyney** [comment]
Please **DO NOT** remove the issue templates. If you would have followed the template, you would have known you need to include the source SVG for this contribution. Removing the Contribution label as there is no SVG attached to this issue.

**Comment by Templarian** [comment]
Added to the general contributor account. @Zoara let me know when you have 5 icons in the system to get contributor access.
