### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by hamid678** [Templarian/MaterialDesign#4516]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by JamesCoyle** [comment]
We already have `view-dashboard` and several other variants on dashboards. 
[![](https://materialdesignicons.com/icon/view-dashboard)](https://materialdesignicons.com/icon/view-dashboard)

If that isn't what you are looking for you need to provide usage and image examples as stated in the issue template so we know what you're requesting.
