### ISSUE TITLE
bitcoincash

### ISSUE THREAD

**Issue by georgengelmann** [Templarian/MaterialDesign#4517]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

An icon for Bitcoin Cash

## Examples

![image](https://user-images.githubusercontent.com/10384436/66921504-468eeb00-f01d-11e9-8352-4730f56cd2fb.png)

**Comment by goyney** [comment]
We already have `bitcoin` and `currency-btc`. I don't think we're going to add another version of a Bitcoin logo.

**Comment by georgengelmann** [comment]
It is for Bitcoin Cash specifically.

**Comment by MrGrigri** [comment]
Going to close this out as issue #2643 discussed this. You can easily add CSS (or whatever rendering platform) to rotate the Bitcoin logo and place it in a circle.
