### ISSUE TITLE
vector-point-(plus|minus|edit)

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4518]
I have:

- [x ] Searched open issues to make sure there isn't a request for this icon.
- [x ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

This is a followup on a suggestion in #4503. I assume opening a new issue with proper naming is the correct way to go. 

## Preview

![image](https://user-images.githubusercontent.com/390250/66929731-d2137680-f033-11e9-8bfe-65db8a8bfe85.png)

![image](https://user-images.githubusercontent.com/390250/66929778-e8b9cd80-f033-11e9-877f-dc366f20350e.png)

![image](https://user-images.githubusercontent.com/390250/66929820-f8d1ad00-f033-11e9-8444-38589c863dbb.png)

![image](https://user-images.githubusercontent.com/390250/66929949-2c143c00-f034-11e9-8920-0fc4e6026830.png)

## Zip Download

[box.zip](https://github.com/Templarian/MaterialDesign/files/3734930/box.zip)

**Comment by Templarian** [comment]
Need to figure out naming around `vector-point` already existing, but we can probably rename that one and add these.

What is `vector-point-edit` for @moovida?

**Comment by moovida** [comment]
@Templarian , when you have a layer of vector points, you would use it for a tool that allows to move the single points. Talking about GIS, that would mean change interactively the planimetric coordinates of the point.

**Comment by Templarian** [comment]
We'll need to add a `-remove` also. But this seems doable. I'm not sure adding the `-edit` makes sense.

Maybe a mouse cursor and a `vector-point` ?

**Comment by moovida** [comment]
Adding a remove makes sense.

The problem with not having an editing version is that then the line and polygon editing icons would not be consistent. The mouse cursor could make sense also for the line and polygon editing though, if it points to one of the vertexes in all icons.

**Comment by goyney** [comment]
Wish I would have saw this before we cut the v6 release. Due to the rename of `vector-point`, this will have to wait until our next major version. Tagged and updated.

**Comment by goyney** [comment]
[![vector-point](https://materialdesignicons.com/icon/vector-point)](https://materialdesignicons.com/icon/vector-point)[![vector-point-edit](https://materialdesignicons.com/icon/vector-point-edit)](https://materialdesignicons.com/icon/vector-point-edit)
[![vector-point-plus](https://materialdesignicons.com/icon/vector-point-plus)](https://materialdesignicons.com/icon/vector-point-plus)[![vector-point-minus](https://materialdesignicons.com/icon/vector-point-minus)](https://materialdesignicons.com/icon/vector-point-minus)
