### ISSUE TITLE
vector-polygon-(plus|minus|edit) question

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4519]
I am struggeling with the vector polygon icon and the plus-minus-edit.

I tried to take the original vector-polygon and add the plus:

![image](https://user-images.githubusercontent.com/390250/66949908-a1453880-f057-11e9-9b40-d31d9e8858a8.png)

I find the plain polygon icon already a bit too "full", so I am not really happy with this.

## Proposal 1

This is obtained removing one vertex from the original icon and flipping it vertically.

![image](https://user-images.githubusercontent.com/390250/66950081-013bdf00-f058-11e9-9428-8bc43a3c0822.png)

![image](https://user-images.githubusercontent.com/390250/66950136-1add2680-f058-11e9-853d-4b83fb2629c7.png)

## Proposal 2

This is the original icon with one vertex removed and two vertex arranged to lead the lines vertically/horizontally into the plus. 

![image](https://user-images.githubusercontent.com/390250/66951196-24678e00-f05a-11e9-92c5-e19b336618f6.png)

![image](https://user-images.githubusercontent.com/390250/66951256-3f3a0280-f05a-11e9-8c9b-20c78f4dadd8.png)

Any thoughts?

**Comment by goyney** [comment]
I like proposal 1. However, you did not provide the source SVG files for us to add. Please do so and we'll get this issue resolved.

**Comment by moovida** [comment]
Fantastic @goyney , I am abroad but will soon comply. Thank you

**Comment by moovida** [comment]
![image](https://user-images.githubusercontent.com/390250/72706488-6d9a1300-3b5e-11ea-8cf4-df910a06aa8d.png)

![image](https://user-images.githubusercontent.com/390250/72706514-81de1000-3b5e-11ea-9e98-fe21dc9aac1b.png)

![image](https://user-images.githubusercontent.com/390250/72706540-96baa380-3b5e-11ea-9364-6b0cec1911f1.png)

![image](https://user-images.githubusercontent.com/390250/72706576-a89c4680-3b5e-11ea-9a5b-c86f4b317074.png)

![image](https://user-images.githubusercontent.com/390250/72706604-b9e55300-3b5e-11ea-8a89-e41061c06fe9.png)

I made 2 different minus versions, which I both don't like that much. Not sure how to handle the cutout in this case.

[vector_polygon.zip](https://github.com/Templarian/MaterialDesign/files/4084931/vector_polygon.zip)

**Comment by goyney** [comment]
Even that version is too chaotic, and we recently added another variant. To simplify, we're going to do this on the square version as it conveys the same meaning.

[![vector-square-plus](https://materialdesignicons.com/icon/vector-square-plus)](https://materialdesignicons.com/icon/vector-square-plus)[![vector-square-minus](https://materialdesignicons.com/icon/vector-square-minus)](https://materialdesignicons.com/icon/vector-square-minus)
[![vector-square-remove](https://materialdesignicons.com/icon/vector-square-remove)](https://materialdesignicons.com/icon/vector-square-remove)[![vector-square-edit](https://materialdesignicons.com/icon/vector-square-edit)](https://materialdesignicons.com/icon/vector-square-edit)
