### ISSUE TITLE
how do aliases work?

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4520]
I see the issue template **Add an Alias**, but I could not find any documentation about it.

Do aliases give the possibility to create a category of icons? 
For example, if I want make it simple for a GIS to find gis related icons, I could propose a set of gis-* icons that make more sense in that particular domain?

If I understand correctly an alias would then be present in the naming, but not duplicate the icon, right?

Thanks for any information or documentation link.

**Comment by Templarian** [comment]
So we support both tags and aliases. Aliases are like `account` being called `users`.

But what you want is a Tag. Once I add a tag anyone on the contributor team and add/remove icons to a tag.

Example of a tag: http://dev.materialdesignicons.com/icons/alpha-numeric

`global-information-system` would be the url and we can name it `Global Information System`

Do you have a list of icons you would like placed into this tag?

**Comment by moovida** [comment]
GIS would actually be for "geographic information system". Yes, I would be interested to slowly browse all the icons and group them for GIS people interested to be found. Is it ok to open an issue once I have a set put together?

The tag is actually very useful, but my question was around a different need. Not sure if that then is alias. I will try with an example.

Checkboard is what I would use for a raster-layer in the GIS world. But if someone coming from the GIS domain wants to see what raster icons are available, they will not find checkboard. It would be really cool to be able to have an alias named raster--(plus|minus|remove).
I assume that would make the naming also available downstream to packages supplying the icons for different frameworks?

**Comment by Templarian** [comment]
Added the tag and added aliases to `checkerboard-*`. Added these 4 to the tag below also.

https://dev.materialdesignicons.com/icons/geographic-information-system

**Comment by Templarian** [comment]
@moovida May not be obvious, but [`meta.json`](https://github.com/Templarian/MaterialDesign/blob/master/meta.json) contains all this data. It's released in `@mdi/svg` package and the CDN for third party integrations.

For this repo itself it's synced real-time all the other packages/cdn are versioned.

**Comment by Templarian** [comment]
Let us know on other issues if tags/aliases are required. Closing this issue out.

**Comment by moovida** [comment]
Thanks a ton, Everything is clear now.

Just about the procedure I have a few doubts:

1. for aliases I assume one issue is made for one icon, same as when they are proposed
2. for tags I assume that once I have a set of icons that I would like to add to the tag, I open an issue with the complete list.

**Comment by CoDEmanX** [comment]
1. If you want to propose multiple aliases for a single icon, then a single issue is sufficient. If the icons you want to propose aliases for are closely related, e.g. same base icon or aliases prefix, then that should also be fine in a single issue.2. A single issue with a list of icons you think should be tagged with the same tag is also fine. In the admin backend, we can quickly add a tag to icons (it's actually the other way around, we select the tag name and then add icons to it).
