### ISSUE TITLE
Google Nest/Home family

### ISSUE THREAD

**Issue by redskinwashingtons** [Templarian/MaterialDesign#4521]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have a couple of smart speakers for which I'm using the default speaker icon right now, but it'd be very cool to have specific icons for the devices. There's a Google Home icon already, but the device looks distinctly different from say a Home Mini or Nest Hub.

## Examples

I think a couple of existing icons could just be tweaked a bit:

mdi:dots-horizontal-circle is already really close to the Home Mini. With 4 circles instead of 3 it'd be perfect. mdi:monitor with the base replaced by a bigger/fatter base (representing the speaker on the back of the Hub) would be a good fit for the Hub/smart display.

**Comment by goyney** [comment]
We have made the conscious choice to *not* add icons for specific devices, instead creating more generic ones. The Google Home one only exists because its an official Google icon. Unfortunately, we will not be adding any device-specific icons. Thanks for your suggestion.
