### ISSUE TITLE
Problem with water-boiler-off

### ISSUE THREAD

**Issue by browetd** [Templarian/MaterialDesign#4522]
Hello

I am using your icons a lot within Home Assistant... 
I tried to access the **water-boiler-off** icon but it comes blank in HA while **water-boiler** icon works fine... Any clue why ?  Not released yet maybe ...  Thank you for your work and website !
Didier

**Comment by JamesCoyle** [comment]
I believe that icon went out in the release that happened only 8 days ago so I would assume that Home Assistant hasn't had chance to update their version of MDI yet.

**Comment by goyney** [comment]
@JamesCoyle Is correct. You'll have to wait until HASS updates to the latest version of our icon library.
