### ISSUE TITLE
compare, change, switch, replace

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4523]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 
- [x] Searched all icons with "arrow", "change", "switch" and "compare"

## Usage

Two or more products compare by their specs.

## Examples

![keyboard-backspace](https://user-images.githubusercontent.com/6717356/67029023-175ba500-f115-11e9-8dae-2948344dfdb7.png)

**Comment by goyney** [comment]
You mean...
[![swap-horizontal](https://materialdesignicons.com/icon/swap-horizontal)](https://materialdesignicons.com/icon/swap-horizontal)

**Comment by ozgurg** [comment]
@goyney Yes, "swap-horizontal" very similar but not what I wanted. Arrows must be looks like the example. Is there a chance to add? (I made the example by using "keyboard-backspace")
