### ISSUE TITLE
archive-outline

### ISSUE THREAD

**Issue by smeijer** [Templarian/MaterialDesign#4524]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same purpose as the archive icon, but a slightly different style.

## Examples

Outline variant of : https://materialdesignicons.com/icon/archive

![image](https://user-images.githubusercontent.com/1196524/67040977-e97e5c80-f124-11e9-9992-d21b9be4677e.png)

**Comment by MrGrigri** [comment]
Idk if I like it.

![image](https://user-images.githubusercontent.com/4528551/67147779-4e38d480-f255-11e9-8c31-54ad80ab13e7.png)

---
[archive-outline.zip](https://github.com/Templarian/MaterialDesign/files/3746864/archive-outline.zip)

**Comment by JamesCoyle** [comment]
The gap in the top of the box probably needs to be 2dp and the handle should probably just be the same as the filled version.

**Comment by MrGrigri** [comment]
I kept the 1-pixel gap between the lid and the box because that's the way that it is done on the filled version. Since the stroke goes inward from the original line, the handle cannot go where it was in the filled version.

**Comment by JamesCoyle** [comment]
I was thinking something more like this:

![image](https://user-images.githubusercontent.com/10384436/67148123-90810680-f293-11e9-9d36-f030907f6357.png)
M3,3H21V9H3V3M5,5V7H19V5H4M4,10H20V21H4V10 M6,10V19H18V10M9.5,11A0.5,0.5 0 0,0 9,11.5V13H15V11.5A0.5,0.5 0 0,0 14.5,11H9.5Z

**Comment by smeijer** [comment]
I like the last one. It matches better with the real thing, as the box slides a bit under the lid. 

I agree that there is no need for outlining the handle.

Last alternative I see, is keep the same dimensions of the lid, and fill that as well. Only outlining the box.

**Comment by smeijer** [comment]
Off-topic, what software do you use to create the svgs?

**Comment by MrGrigri** [comment]
I use Adobe Illustrator. But I've also used Affinity Designer, Figma, and Adobe XD.

**Comment by Templarian** [comment]
Added.

[![archive-outline](https://materialdesignicons.com/icon/archive-outline)](https://materialdesignicons.com/icon/archive-outline)
