### ISSUE TITLE
search on the material design website

### ISSUE THREAD

**Issue by DuncanFaulkner** [Templarian/MaterialDesign#4525]
just recently I've noticed that the search doesn't seem to work all to well, searching for an icon called home use to return a list of images that matched a house like image. but now this just seems to bring all 6000+ images back.

Has the naming changed or is there an issue with the search feature?

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/67064860-c27a5780-f131-11e9-9759-4eeec4be0404.png)

What browser are you using? Not seeing anything in Chrome.

**Comment by Templarian** [comment]
@DuncanFaulkner Do you have steps to reproduce this?
