### ISSUE TITLE
shoe-sneaker (or shoe-running)

### ISSUE THREAD

**Issue by ayinmursalin** [Templarian/MaterialDesign#4526]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Infinitay** [comment]
Something like the following would be wonderful:

![image](https://user-images.githubusercontent.com/6964154/89363559-7edfe280-d69e-11ea-8149-9a542ca1b26b.png)
Source:
https://icons8.com/icon/39712/sneakers
https://icons8.com/icon/69628/sneakers

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/89365709-31b23f80-d6a3-11ea-87dc-68e46e9967cd.png)![image](https://user-images.githubusercontent.com/1015040/89365769-57d7df80-d6a3-11ea-8975-0485705510a8.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/5025823/Archive.zip)

**Comment by goyney** [comment]
Both added.

**Comment by escully27** [comment]
My version of MDI doesn't include these. Any help as to why? Have they been deprecated? I'm using Vuetify and all the icons here are available currently in our app.
https://pictogrammers.github.io/@mdi/font/5.4.55/

thanks!

**Comment by goyney** [comment]
`shoe-sneaker` was added in 5.6.55. You're on 5.4.55, so you'll need to upgrade to use it.

**Comment by escully27** [comment]
Thanks. Got it! Assumed I was on the most recent 😅
