### ISSUE TITLE
Icons to add to Geographic Information System

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4527]
I would like to ask to add the following icons to the GIS tag:

- [x] arrange-bring-forward
- [x] arrange-bring-to-front
- [x] arrange-send-backward
- [x] arrange-send-to-back
- [x] arrow-expand-all
- [x] compass
- [x] compass-off
- [x] compass-outline
- [x] compass-off-outline
- [x] crosshairs
- [x] crosshairs-off
- [x] crosshairs-gps
- [x] crosshairs-question
- [x] database
- [x] database-check
- [x] database-edit
- [x] database-export
- [x] database-import
- [x] database-lock
- [x] database-minus
- [x] database-plus
- [x] database-refresh
- [x] database-remove
- [x] database-search
- [x] database-settings
- [x] earth
- folder
- folder-key
- folder-account
- folder-alert
- folder-clock
- folder-download
- folder-edit
- folder-heart
- folder-image
- folder-information
- folder-key
- folder-lock
- folder-lock-open
- folder-move
- folder-multiple
- folder-open
- folder-plus
- folder-remove
- folder-search
- folder-settings-variant
- folder-star
- folder-sync
- folder-text
- folder-upload
- folder-zip
- folder-outline
- folder-key-outline
- folder-account-outline
- folder-alert-outline
- folder-clock-outline
- folder-download-outline
- folder-edit-outline
- folder-heart-outline
- folder-image-outline
- folder-information-outline
- folder-key-outline
- folder-lock-outline
- folder-lock-open-outline
- folder-move-outline
- folder-multiple-outline
- folder-open-outline
- folder-plus-outline
- folder-remove-outline
- folder-search-outline
- folder-settings-variant-outline
- folder-star-outline
- folder-sync-outline
- folder-text-outline
- folder-upload-outline
- folder-zip-outline
- [x] latitude
- [x] layers
- [x] layers-minus
- [x] layers-off
- [x] layers-off-outline
- [x] layers-outline
- [x] layers-plus
- [x] layers-remove
- [x] layers-search
- [x] layers-search-outline
- [x] longitude
- [x] magnify-minus-outline
- [x] magnify-outline
- [x] magnify-plus-outline
- [x] magnify-remove-outline
- [x] map
- [x] map-check
- [x] map-check-outline
- [x] map-clock
- [x] map-clock-outline
- [x] map-legend
- [x] map-marker
- [x] map-marker-alert
- [x] map-marker-alert-outline
- [x] map-marker-check
- [x] map-marker-circle
- [x] map-marker-distance
- [x] map-marker-down
- [x] map-marker-minus
- [x] map-marker-multiple
- [x] map-marker-off
- [x] map-marker-outline
- [x] map-marker-path
- [x] map-marker-plus
- [x] map-marker-question
- [x] map-marker-question-outline
- [x] map-marker-radius
- [x] map-marker-remove
- [x] map-marker-up
- [x] map-minus
- [x] map-outline
- [x] map-plus
- [x] map-search
- [x] map-search-outline
- [x] palette-outline
- [x] table-large
- [x] table-large-plus
- [x] table-large-minus
- [x] vector-arragne-above
- [x] vector-arragne-below
- [x] vector-circle
- [x] vector-combine
- [x] vector-curve
- [x] vector-difference
- [x] vector-difference-ab
- [x] vector-difference-ba
- [x] vector-ellipse
- [x] vector-intersection
- [x] vector-line
- [x] vector-link
- [x] vector-point
- [x] vector-polygon
- [x] vector-polyline
- [x] vector-radius
- [x] vector-rectangle
- [x] vector-selection
- [x] vector-square
- [x] vector-triangle
- [x] vector-union
- [x] web
- [x] web-box

**Comment by Templarian** [comment]
Added checkboxes for whoever does this. Our tagging system is relatively quick, but this could still take a few minutes. 😅

**Comment by moovida** [comment]
:-) is there something I can do to help? (apart of adding checkboxes next time). A pull request?

**Comment by JamesCoyle** [comment]
Unfortunately this is a manual process for the core team so not much else you can do. I made a start but don't really have time to do any more at the minute.

**Comment by moovida** [comment]
Ok, no rush here, so thanks.

**Comment by CoDEmanX** [comment]
What about the following icons? If e.g. most layer icons are tagged with GIS, shouldn't we include the remaining ones as well?

- layers-triple
- layers-triple-outline
- magnify-* (filled)
- vector-bezier
- vector-polyline-* (plus, minus, edit, remove)
- vector-circle-variant
- map-marker-remove-variant
- home-map-marker

Others:
- table-large-minus:
  there is only table-large-remove?
- folder-*:
  Seems like a bit of a stretch to include all these. They are not closely related to GIS in my opinion.

**Comment by moovida** [comment]
> I added the GIS tag to everything but the `folder-*` icons. Seems like a bit of a 
> stretch to include all these. They are not closely related to GIS in my opinion.

Well, it is used to reference a project. So open project etc. I could not find a project icon. If someone has an idea, I will give it a try to create a new icon for project. But without a different project icon, I think the folder icon is a quite well accepted icon for that purpose. And it has an open and close version. I am very keen to discuss this, since I would like to have a project icon.


> There is no `table-large-minus`, I guess you meant `table-large-remove`?

Oh, you are right, sorry.

> What about the following icons? If e.g. most layer icons are tagged with GIS, 
> shouldn't we include the remaining ones as well?
> 
> * layers-triple
> * layers-triple-outline

I was in doubt whether to add those or not. In the end I decided to not in order to give one workflow. But you might be right. It is better to add them and let the user choose.

> * magnify-* (filled with modifier)

Same as above.

> * vector-bezier

While this is a graphical applications icon, I've never seen a GIS having such a functionality. But it sure would not hurt to add it.

> * vector-polyline-* (with modifier: plus, minus, edit, remove)
> * vector-circle-variant

I only now notice that for polyline I forgot the modifiers. Yes, those are necessary.

> * map-marker-remove-variant
> * home-map-marker
> * palette

Yes, agreed.

> Additionally, what about the following icons?
> 
> * ruler
> * ruler-square-compass
> * ruler-square
> * tape-measure
> * earth-box
> * earth-box-off
> * *-rotate-* icons?

Ok, I definitely missed those. They would be good to have. I would just leave out the phone-rotate-*, but the others look relevant.

Thank you.

**Comment by Templarian** [comment]
Kind of agreed. Lets not include folders in this tag. The rest seem fine.

**Comment by moovida** [comment]
Goes fine by me. I will open a question about ideas for a project icon.

**Comment by JamesCoyle** [comment]
I believe these are all done now?
