### ISSUE TITLE
vending-machine

### ISSUE THREAD

**Issue by motapinto** [Templarian/MaterialDesign#4529]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by GreenTurtwig** [comment]
Please can you provide some examples of usage and design. 👍
