### ISSUE TITLE
tag-off/tag-off-outline

### ISSUE THREAD

**Issue by douglasg14b** [Templarian/MaterialDesign#4530]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For an action that toggles something related to tags off.

## Examples

Similar to: 
![image](https://user-images.githubusercontent.com/1400380/67173289-16c04a00-f373-11e9-8f82-dae0c29f363b.png) 
![image](https://user-images.githubusercontent.com/1400380/67173312-23dd3900-f373-11e9-83e2-cc64c4086a15.png) 
![image](https://user-images.githubusercontent.com/1400380/67173334-37889f80-f373-11e9-9edf-c592ac55d4f4.png)
![image](https://user-images.githubusercontent.com/1400380/67173340-3eafad80-f373-11e9-91f4-ef5a528ae53b.png)

**Comment by JamesCoyle** [comment]
I feel this is one good case for flipping the off modifier.

**Comment by MrGrigri** [comment]
If we choose to switch the slash, here are those.

![image](https://user-images.githubusercontent.com/4528551/67226787-08197780-f3f3-11e9-8542-21bb62c4889d.png) ![image](https://user-images.githubusercontent.com/4528551/67226820-1cf60b00-f3f3-11e9-8183-d4e941d24376.png)

---

[tag-variant.zip](https://github.com/Templarian/MaterialDesign/files/3752075/tag-variant.zip)

**Comment by douglasg14b** [comment]
I believe switching the tag orientation for an off toggle would be pretty off putting, and support the change of orientation to match existing tags.

Though I do see how it could jive with the consistency of other off symbols when used side by side.

**Comment by MrGrigri** [comment]
After some internal discussion, the slash is going to be reflected as opposed to the tag itself.

**Comment by MrGrigri** [comment]
The `tag-off-outline` will be updated with the next major release to match the soon-to-be-updated `tag-outline` icons. See #4536 for reference.

**Comment by douglasg14b** [comment]
Good stuff, thanks for the prompt action @MrGrigri !

**Comment by goyney** [comment]
[![tag-off](https://materialdesignicons.com/icon/tag-off)](https://materialdesignicons.com/icon/tag-off)[![tag-off-outline](https://materialdesignicons.com/icon/tag-off-outline)](https://materialdesignicons.com/icon/tag-off-outline)
