### ISSUE TITLE
Add 3 new icons shield-outline with number inside

### ISSUE THREAD

**Issue by notjulian** [Templarian/MaterialDesign#4532]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2241601/67197603-719e8380-f3fd-11e9-8ca7-089de6e0a1a2.png)

![image](https://user-images.githubusercontent.com/2241601/67198067-74e63f00-f3fe-11e9-969e-b0aaacdf83da.png)

![image](https://user-images.githubusercontent.com/2241601/67198093-84fe1e80-f3fe-11e9-9131-a7705ccbb6a0.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[svg.zip](https://github.com/Templarian/MaterialDesign/files/3750224/svg.zip)

**Comment by goyney** [comment]
What's the use case? We're not typically too keen on adding numeric variants of icons unless there is a very compelling reason to, especially since you can stack icons via CSS to achieve your goal.

**Comment by goyney** [comment]
We'll discuss internally how we want to proceed with this issue and then post an update here when we have an answer for you. Thanks!

**Comment by MrGrigri** [comment]
This goes against what we have discussed internally. Not because we don't believe they'd be useful, but because it would open the floor to want numbers inside a lot of different icons.
