### ISSUE TITLE
kotlin

### ISSUE THREAD

**Issue by schneiderEDU** [Templarian/MaterialDesign#4534]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon could be used on App Navigation

## Examples

Icon should look like the Kotlin logo

**Comment by Templarian** [comment]
Does anyone know if they have a monotone version of their icon. Wondering if we want to do more than just making it a single color.

**Comment by MrGrigri** [comment]
According to their [documentation](https://kotlinlang.org/assets/kotlin-media-kit.pdf), they do have a monotone icon.

![image](https://user-images.githubusercontent.com/4528551/67234805-022b9280-f403-11e9-9a57-40212b64a13d.png)


---

[kotlin.zip](https://github.com/Templarian/MaterialDesign/files/3752464/kotlin.zip)

**Comment by goyney** [comment]
[![kotlin](https://materialdesignicons.com/icon/kotlin)](https://materialdesignicons.com/icon/kotlin)
