### ISSUE TITLE
tag-text

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4536]
I have:

- [X] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/67237697-fcd14680-f408-11e9-9dc9-29650f32fa4b.png)

## Zip Download

[tag-text.zip](https://github.com/Templarian/MaterialDesign/files/3752612/tag-text.zip)

**Comment by goyney** [comment]
[![tag-text](https://materialdesignicons.com/icon/tag-text)](https://materialdesignicons.com/icon/tag-text)
