### ISSUE TITLE
file-sync(-outline)

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4537]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/67238657-8a1d9680-f41b-11e9-8401-877e05ae8e1e.png)![image](https://user-images.githubusercontent.com/1015040/67238753-ab7e8280-f41b-11e9-8c9f-9b8cad5b5878.png)

## Zip Download
[file-sync.zip](https://github.com/Templarian/MaterialDesign/files/3752660/file-sync.zip)

**Comment by Templarian** [comment]
Weird we had folder sync before ever adding a file sync.

**Comment by goyney** [comment]
[![file-sync](https://materialdesignicons.com/icon/file-sync)](https://materialdesignicons.com/icon/file-sync)[![file-sync-outline](https://materialdesignicons.com/icon/file-sync-outline)](https://materialdesignicons.com/icon/file-sync-outline)
