### ISSUE TITLE
tag-(plus | remove | minus)-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4538]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

To go with #4535, these are to be added whenever -- as they do not exist -- but follow the new outline. 

## Preview

![image](https://user-images.githubusercontent.com/4528551/67239516-9817eb00-f40c-11e9-98ae-dff52815f2f6.png) ![image](https://user-images.githubusercontent.com/4528551/67239565-b41b8c80-f40c-11e9-8a55-094193b5f89c.png) ![image](https://user-images.githubusercontent.com/4528551/67239613-cac1e380-f40c-11e9-873a-31c4fcdcc5be.png)

## Zip Download

[tag-modifiers-outline.zip](https://github.com/Templarian/MaterialDesign/files/3752709/tag-modifiers-outline.zip)

**Comment by goyney** [comment]
[![tag-plus-outline](https://materialdesignicons.com/icon/tag-plus-outline)](https://materialdesignicons.com/icon/tag-plus-outline)[![tag-minus-outline](https://materialdesignicons.com/icon/tag-minus-outline)](https://materialdesignicons.com/icon/tag-minus-outline)
[![tag-remove-outline](https://materialdesignicons.com/icon/tag-remove-outline)](https://materialdesignicons.com/icon/tag-remove-outline)
