### ISSUE TITLE
google-controller-outline

### ISSUE THREAD

**Issue by StormiFire** [Templarian/MaterialDesign#4539]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
This icon can be used in more of a gaming app, or an app store like Google Play. The reason I'm requesting this is because there is no outlined version of `google-controller` in the library.

From the name, I'm assuming it's short for **Electronic Sports**.

## Examples
![Esports](https://user-images.githubusercontent.com/43486313/67251051-ad583e00-f43b-11e9-812e-47dd810d2db3.png)

**Comment by goyney** [comment]
I really don't think this works...

![image](https://user-images.githubusercontent.com/1015040/72310147-04426d80-364f-11ea-8a8b-4180dfccfb93.png)
[google-controller-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/4057123/google-controller-outline.svg.zip)

**Comment by KodedScorpius** [comment]
> I really don't think this works...
> 
> ![image](https://user-images.githubusercontent.com/1015040/72310147-04426d80-364f-11ea-8a8b-4180dfccfb93.png)
> [google-controller-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/4057123/google-controller-outline.svg.zip)

Maybe it's because there's 4 buttons there, try removing 2.

**Comment by goyney** [comment]
It is not the buttons I’m concerned about.

**Comment by KodedScorpius** [comment]
> It is not the buttons I’m concerned about.

What are you concerned about?
