### ISSUE TITLE
Currency sign icons

### ISSUE THREAD

**Issue by mgursch** [Templarian/MaterialDesign#454]
Hello

please provide some currency signs
Euro, Dollar ,....

**Comment by matthew2402** [comment]
Euro and Dollar already exist:
https://materialdesignicons.com/icon/currency-eur
https://materialdesignicons.com/icon/currency-usd

https://materialdesignicons.com/icon/currency-gbp

**Comment by Templarian** [comment]
Let me know if you need any other specific currency symbols. Closing the issue for now.
