### ISSUE TITLE
eye-lock, eye-off-lock, eye-lock-open, eye-off-lock-open

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4540]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm using "mdi-eye" and "mdi-eye-off". But the icons in the examples would be great instead of that.
![123](https://user-images.githubusercontent.com/6717356/67307228-da225900-f500-11e9-8585-2728018665fa.gif)

## Examples
I don't know which icons fits perfectly, so I created different variants of icons. (Excluded outline)
![eye-unlock](https://user-images.githubusercontent.com/6717356/67307365-11910580-f501-11e9-8351-095dcdd62c74.png)
![eye-lock](https://user-images.githubusercontent.com/6717356/67307367-13f35f80-f501-11e9-95e4-a98430c6d8fa.png)
![eye-off-lock](https://user-images.githubusercontent.com/6717356/67307371-15bd2300-f501-11e9-922c-8ae749608fe5.png)
![eye-off-unlock](https://user-images.githubusercontent.com/6717356/67307376-18b81380-f501-11e9-83c6-1aae073e7a18.png)

**Comment by goyney** [comment]
I don't think the lock is necessary for your example. I, personally, have never seen an icon such as that for any password field.

If we do choose to add these, however, the `off` slash *must* intersect all icon artwork (e.g. go through the lock as well). Due to the position and size of the lock, I don't think this will work.

**Comment by MrGrigri** [comment]
With UX, the icon should represent the action and not the state. In other words, the slash should be in place when the user wants to hide the password (action) and not that the password is hidden (state).

**Comment by ozgurg** [comment]
> I don't think the lock is necessary for your example. I, personally, have never seen an icon such as that for any password field.
> 
> If we do choose to add these, however, the `off` slash _must_ intersect all icon artwork (e.g. go through the lock as well). Due to the position and size of the lock, I don't think this will work.

Google is currently using. Maybe the current is good, I opened the issue to make you think about it.
![454](https://user-images.githubusercontent.com/6717356/67311380-1f965480-f508-11e9-9164-9fb03bae4e00.gif)


> With UX, the icon should represent the action and not the state. In other words, the slash should be in place when the user wants to hide the password (action) and not that the password is hidden (state).

Yeah, you're right.

**Comment by goyney** [comment]
We have the icons to support your use case, so I think we're going to reject this issue. Thanks for the suggestion!

**Comment by ozgurg** [comment]
> We have the icons to support your use case, so I think we're going to reject this issue. Thanks for the suggestion!

Alright, thank you for time.
