### ISSUE TITLE
home-remove

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4542]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Deleting an address. (Variant for mdi-home-minus)

## Examples

![eye](https://user-images.githubusercontent.com/6717356/67308326-9597bd00-f502-11e9-9c1f-f420af039bc7.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/67310852-839b2780-f4cc-11e9-928a-0c04252f18c7.png)

[home-remove.svg.zip](https://github.com/Templarian/MaterialDesign/files/3757301/home-remove.svg.zip)

**Comment by MrGrigri** [comment]
We don't use the `delete` as a modifier. We use the `remove` modifier.

**Comment by Templarian** [comment]
Added.
