### ISSUE TITLE
webrtc

### ISSUE THREAD

**Issue by K4rakara** [Templarian/MaterialDesign#4543]
*I'm not sure if APIs fall under brands icons so if they do, sorry, just go ahead and delete this issue :/*
I have:
- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 
## Usage
I've seen a few great [WebRTC](https://webrtc.org/) projects popping up ([Snapdrop](https://snapdrop.net/), [ShareDrop](https://www.sharedrop.io/), [WebTorrent](https://webtorrent.io/), etc) as of late, and for projects using both Material Design Icons and WebRTC, an icon for WebRTC would be a nice addition.
## Examples
I'd say these are the best two possibilities:
Their official icon:
<img src="https://webrtc.org/assets/images/webrtc-logo-vert-retro-255x305.png" width="100">
Or, their complete logo:
<img src="https://webrtc.org/assets/images/webrtc-logo-horiz-retro-750x140.png"  width="250">
HD and svg versions of these images are available [here](https://webrtc.org/press/).

**Comment by Templarian** [comment]
Nah, this falls under tech brand, so it is probably fine.

**Comment by Templarian** [comment]
Added.
