### ISSUE TITLE
bicycle with basket

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4544]
If you like the "bicycle" design, I quite also like this version with a basket. I'm not sure about the naming though:

## Preview
![image](https://user-images.githubusercontent.com/6012554/67396806-83705a00-f5a8-11e9-930b-9e1fa04cbcb7.png)

## Zip Download
[bicycle-with-basket.zip](https://github.com/Templarian/MaterialDesign/files/3762526/bicycle-with-basket.zip)

**Comment by Templarian** [comment]
Added (tweaked the path a little bit):

[![bicycle-basket](https://materialdesignicons.com/icon/bicycle-basket)](https://materialdesignicons.com/icon/bicycle-basket)
