### ISSUE TITLE
allergy

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4545]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Possible Aliases

- [x] hand
- [x] rash
- [x] germs

## Preview

![image](https://user-images.githubusercontent.com/4528551/67430749-27a1d300-f5a0-11e9-9bb8-6610404b3241.png)

## Zip Download

[allergy.zip](https://github.com/Templarian/MaterialDesign/files/3764293/allergy.zip)

**Comment by Templarian** [comment]
Maybe `germs` or something?

**Comment by MrGrigri** [comment]
Do you mean to add germs as an alias or rename this icon to germs? This is meant to show a rash from allergies.

**Comment by Templarian** [comment]
Oh, then maybe call it rash? But kind of looks like a germ hand washing icon.

**Comment by MrGrigri** [comment]
Hense the aliases. I got the idea straight from [Font Awesome](https://fontawesome.com/icons?d=gallery&q=allergies). That doesn't mean we have to name it that. We can name it whatever and have aliases for it.

**Comment by MrGrigri** [comment]
Added with aliases
