### ISSUE TITLE
folder-marker

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4546]
Hi, I am looking out ideas to base on in the creation of an icon that represents a project.

The context for me is the use of software applications that allow the creation of a project inside which they handle particular setting as for example styles and where project files are referenced.

Often for this the folder icons are used, also because they have an open/close option.

Has anyone ideas about a good icon representing a project? 
Thank you

**Comment by Templarian** [comment]
- #1605
- #3299
- #4350

This has been discussed a couple times. What a project is will depend on the context of the application. These issues might give you an idea of what existing icons you can use.

**Comment by moovida** [comment]
Ahhh, thanks a ton. Sorry for not finding it myself. :-/

**Comment by moovida** [comment]
I would love to discuss a bit the idea (as seen in the above linked issue) to use the folder with a dedicated symbol. 

This uses the folder outline with the map marker. 

![image](https://user-images.githubusercontent.com/390250/67488117-87b37a80-f66f-11e9-9217-58208c56f472.png)

And the version with plus:

![image](https://user-images.githubusercontent.com/390250/67488235-c0ebea80-f66f-11e9-9f62-86cd4b9bb988.png)

One problem can be already seen in the outline version with plus. The plus and the marker are very near and hardly readable. When making the cutout, I didn't touch the map-marker, since it didn't interfere with the plus. 

It obviously does interfere a lot in the solid version of the icon.

In that case I therefore tried to move the map marker to the left (I assume that is not allowed though):

![image](https://user-images.githubusercontent.com/390250/67488418-1e803700-f670-11e9-80ad-63a408cf2692.png)

and the plus:

![image](https://user-images.githubusercontent.com/390250/67488527-42dc1380-f670-11e9-887b-e4dbd86b3654.png)

Any suggestion?
Thanks

**Comment by Templarian** [comment]
We can definitely add a `folder-marker` (`*-marker` is the modifier for the location marker).

I don't think adding two modifiers on a single folder is in scope.

**Comment by moovida** [comment]
But then what is the paradigm for the add/remove geo project?

**Comment by goyney** [comment]
I think the marker should be taken out of the folder and cut-out of the bottom right corner. At native resolution, that small marker is hard to identify.

**Comment by moovida** [comment]
Ok, I will give it a go asap. It is not clear to me how the adding and removing or editing of such a "project" would look like.

**Comment by goyney** [comment]
To be clear, while you might use this new icon to represent a project, at our level it is a modifier (the map marker) of the base folder icon. We only allow one modifier per base icon. So, while we'll likely add this as `folder-marker(-outline)`, there will not be any plus, minus, remove, etc. modifiers added to this.

**Comment by moovida** [comment]
:-) I had imagined it might be that, but hoped it would be different (no idea how though). 

Ok, will go for the geo-project for now. Thanks.

**Comment by moovida** [comment]
Question. In this case:

![image](https://user-images.githubusercontent.com/390250/68403041-98d6ae00-017c-11ea-8df8-510fef4ace91.png)

the circle cutout looks a bit strange due to the shape of the geo-marker. 
What is the best practice in this case?

**Comment by Templarian** [comment]
Little bit of a delay. Added the outline also.

The cutout needs to follow the shape of the marker symbol.

**Comment by moovida** [comment]
Hi @Templarian thanks a lot. I assume that means that you made the cut and outline version. 

I am not able to see the icon request though (was interested to see how the cutout was done.

**Comment by moovida** [comment]
PS: could this also be adde to the geographic-information-system tag? Should I open a new issue for that?

**Comment by Templarian** [comment]
The easiest way in illustrator is to set stroke and convert it to an path and subtract. Depends on the software.

Tags added. ✅

**Comment by moovida** [comment]
Yep, that sounds a good way. I assume it will be  a 1pixel stroke.

Thanks.
