### ISSUE TITLE
Rename: image-filter --> image-multiple-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4548]
These icons are the different version of each others but I think the names needs renamed.

"image-filter" is outlined version of "image-multiple". So it's may be renamed to "image-multiple-outline"

(I accidentally added this "Bug" tag. I don't know how to change it.)

![Screenshot_1](https://user-images.githubusercontent.com/6717356/67521057-c74f8600-f6b2-11e9-9707-74ad86b9c112.png)

**Comment by Templarian** [comment]
Fixed.
