### ISSUE TITLE
Up left arrow icon request like in the Google Now search :)

### ISSUE THREAD

**Issue by timothyjc** [Templarian/MaterialDesign#455]
http://i.imgur.com/mAXSqkd.png

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/arrow-top-left
https://materialdesignicons.com/icon/arrow-top-right
https://materialdesignicons.com/icon/arrow-bottom-left
https://materialdesignicons.com/icon/arrow-bottom-right
