### ISSUE TITLE
New Beaker Icons

### ISSUE THREAD

**Issue by coogle** [Templarian/MaterialDesign#4550]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have an application where I want to indicate the status of a chemical test results with an icon and have a bunch of "standard" use-cases I'd love to see included. 

## Examples

The `beaker-outline` and `beaker` classes are great as a base. I'd like to see a few more created in the style of something like `flag-remove`:

- [ ] `beaker-check`
- [x] `beaker-question`
- [x] `beaker-alert`
- [x] `beaker-plus`
- [x] `beaker-minus`
- [x] `beaker-remove`
- A beaker with a $ mark next to it

Of these six requests, the first three are the most important to me but I'd absolutely make use of the total six if they were available!

**Comment by Templarian** [comment]
Added these with their `*-outline` counterparts also.

Note, we're not really adding currency symbols as modifiers as it would become a headache to maintain. If you can think of another modifier for this we can use that.

**Comment by coogle** [comment]
Awesome thank you! How about a tiny little shopping cart instead?

**Comment by Templarian** [comment]
That would be too detailed. It's also bit niche. We would usually recommend using the full currency symbol in most cases.

**Comment by coogle** [comment]
One more question -- what is the best way for me to get access to these icons right now? I See they are already on the matieraldesignicons.com website, but I don't see this repository updated which seems to me means it wouldn't be in the master .zip file, even if I wanted to build it myself?

**Comment by Templarian** [comment]
@coogle I forgot to add them to the `4.6.xx` version. Fixed.

You can now download the zip in `master` now and run `npx @mdi/font-build`. Playing Outer Worlds easy to get distracted. 🎮

**Comment by coogle** [comment]
Heh thanks man I really appreciate you taking the time out from gaming to help out!

**Comment by coogle** [comment]
Just FYI I don't know if I'm doing something wrong but I can't seem to get the package to build. Well that's not entirely true -- I download this repo's master.zip, I unzip it and run `npx @mdi/font-build` and the command runs. I even see using `strace` that it seems to build the entire library in a temp directory -- it then deletes it from the temp directory leaving me without a `dist` folder to use. 

I feel like I'm doing something silly here but   `npx` doesn't seem to have any parameters to set an output directory and I can't even tell how you're building in the first place since `font-build.json` looks like just meta data !

**Comment by Templarian** [comment]
@coogle This was working, something is definitely broken. 🤔 

Will have to look later after work.

**Comment by Templarian** [comment]
@coogle Fixing it now. That took forever to debug. Apparently `account-multiple-remove` and `account-multiple-remove-outline` uploaded with bad path data that for some reason silently fails the webfont build scripts.

`@mdi/font-build` is fine, this is an issue with our validation in the contributor icon management screen. It shouldn't be allowing this to get into the system.

**Comment by Templarian** [comment]
Fixed. But will have to actually fix our system soon to prevent this from happening again. The package that `webfont` uses already has an open bug related to this, but we can catch it on our side.
