### ISSUE TITLE
digitalocean

### ISSUE THREAD

**Issue by chitanok** [Templarian/MaterialDesign#4551]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/67686879-fbe66a80-f95c-11e9-9347-ab57dbceb8c2.png)

---

[digitalocean.zip](https://github.com/Templarian/MaterialDesign/files/3779122/digitalocean.zip)

**Comment by Templarian** [comment]
Added.
