### ISSUE TITLE
Universal 2nd Factor (U2F) security key / yubikey

### ISSUE THREAD

**Issue by intervia** [Templarian/MaterialDesign#4552]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To use U2F / yubikey in accounts

## Examples

![yubikey](https://user-images.githubusercontent.com/13640952/67721575-2d038100-f9d7-11e9-9b0b-beefb2660a29.png)
![yubikey-1-558608](https://user-images.githubusercontent.com/13640952/67721580-3260cb80-f9d7-11e9-8817-3715520a0a3e.png)

**Comment by Templarian** [comment]
Different, but designs will be similar'ish #1078

My work one is USB-C and I think that is pretty normal now since I can use it on my phone/laptop. The little left and right capacitive buttons on yubi's are pretty normal to see.

**Comment by ybandura** [comment]
Maybe something  like this https://github.com/Templarian/MaterialDesign/issues/4608?

**Comment by goyney** [comment]
`usb-flash-drive` definitely covers this.

[![usb-flash-drive](https://materialdesignicons.com/icon/usb-flash-drive)](https://materialdesignicons.com/icon/usb-flash-drive)[![usb-flash-drive-outline](https://materialdesignicons.com/icon/usb-flash-drive-outline)](https://materialdesignicons.com/icon/usb-flash-drive-outline)

**Comment by mochaaP** [comment]
<https://www.gstatic.com/identity/boq/accountsettingssecuritycommon/images/sprites/2sv_x2-376cf0cbd62be6b103c146c2464cdff9.png>

![image](https://user-images.githubusercontent.com/21154023/201820279-415c3eb2-be1d-47e6-afac-89a4cce60e86.png)

![image](https://user-images.githubusercontent.com/21154023/201820418-fa3afb0b-b61e-47f3-b135-2d076f2ceaac.png)


I don't think `usb-flash-drive` covers these? cc @mririgoyen
