### ISSUE TITLE
barcode-off

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4554]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/67783331-7a680880-fa40-11e9-8b08-7e92809f0081.png)

## Zip Download

[barcode-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/3784412/barcode-off.svg.zip)

**Comment by Templarian** [comment]
Added
