### ISSUE TITLE
check-alert

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4555]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Useful for "completed but with warnings" type of stuff.

## Preview

Struggling a bit to combine the checkmark and exclamation point in a satisfying way. Input more than welcome :)

![image](https://user-images.githubusercontent.com/55925048/67846428-836cde80-fb01-11e9-857f-c84af385688b.png)

![image](https://user-images.githubusercontent.com/55925048/67846470-92ec2780-fb01-11e9-8679-1cc8698e07c8.png)

## Zip Download

[check-alert.zip](https://github.com/Templarian/MaterialDesign/files/3788036/check-alert.zip)

**Comment by PeterShaggyNoble** [comment]
Would `check-bold` be a better option for the base icon, I wonder?

**Comment by goyney** [comment]
I don't believe these work. Additionally.... what's the use case?
