### ISSUE TITLE
exclamation – grid alignment

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4556]
http://materialdesignicons.com/icon/exclamation is not well aligned on grid:

![image](https://user-images.githubusercontent.com/55925048/67846987-5ec53680-fb02-11e9-8f13-3aa4d2ef3fd6.png)

Suggested improvement:

![image](https://user-images.githubusercontent.com/55925048/67847030-743a6080-fb02-11e9-8217-73986a118a58.png)

Also better matches the weight of https://materialdesignicons.com/icon/help

**Comment by Templarian** [comment]
Probably a good idea to update this one to be more consistent. 👍

**Comment by MrGrigri** [comment]
I would call it `exclamation-thick` and then update the current `exclamation` to fit the grid and maybe make it a tad shorter.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/67907605-76bea980-fb46-11e9-9736-602790fa0380.png) Like this?

**Comment by Templarian** [comment]
Updated and added to your account. But left height of the one I linked. Shrinking the size makes it a little disproportionate.

Open a new issue for `help`.
