### ISSUE TITLE
Update Firefox

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4557]
Firefox underwent [an extensive rebranding](https://blog.mozilla.org/opendesign/firefox-the-evolution-of-a-brand/) over the summer including updating its logos and icons. A single colour SVG of the new browser icon can be downloaded from [this page](https://mozilla.design/firefox/logos-usage/), under "Firefox browser logos".

Here's Simple Icons' version of it for reference:
![firefox](https://user-images.githubusercontent.com/15157491/67856669-fa5ba480-fb0c-11e9-87d9-6aef19ef425c.png)

**Comment by Templarian** [comment]
Updated!
