### ISSUE TITLE
archive-outline not working

### ISSUE THREAD

**Issue by ebuychance** [Templarian/MaterialDesign#4558]
v4.4.95 and not able to get `archive-outline` to work. `archive` works though?

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/history Added oct 19th, will be in the next release.

Also `4.5.95` is latest currently out. `archive-outline` will be in `4.6.xx` which releases in the next few days or so.

**Comment by smeijer** [comment]
@Templarian, any idea when the next few days will arrive? 😇. I see that the milestone has [been closed](https://github.com/Templarian/MaterialDesign/milestone/41), but the packages haven't been updated yet.

**Comment by Templarian** [comment]
@smeijer Working on some CI related changes that ended up delaying things. I'll manually publish this version. My hope is to have this all automated shortly. 🤞

**Comment by smeijer** [comment]
Sounds awesome. Thanks.
