### ISSUE TITLE
round-bottom-flask

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#4559]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/338885/67907296-78d43880-fb45-11e9-8221-1035a37444c2.png) 
![image](https://user-images.githubusercontent.com/338885/67907312-8689be00-fb45-11e9-8888-70df194c7b4f.png)

With a solid and an outline like `flask`.

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by PeterShaggyNoble** [comment]
I don't know if the outline version is needed - I can't unsee Pacman in a bottle!

Should the name be `flask-round-bottom`?

**Comment by Templarian** [comment]
@JamesCoyle When you swirl the liquid in a beaker it looks like that.

Agreed the outline is probably unnecessary for this one so it would just be.

- `flask-round-bottom`
- `flask-round-bottom-empty`
- `flask-round-bottom-empty-outline`

**Comment by Templarian** [comment]
Added. ✔️
