### ISSUE TITLE
Moon Icon

### ISSUE THREAD

**Issue by ezabaw** [Templarian/MaterialDesign#456]
What about a moon icon? I see you got plenty for the sun. Btw, amazing work!!!

**Comment by ezabaw** [comment]
Just found weather-night. Sorry for that, and Thanks!

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/brightness-1
https://materialdesignicons.com/icon/brightness-2
https://materialdesignicons.com/icon/brightness-3
https://materialdesignicons.com/icon/weather-night

Would probably work for a moon.

**Comment by Templarian** [comment]
I'm still taking credit for solving the issue. :stuck_out_tongue_winking_eye:
