### ISSUE TITLE
folder-move-outline

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4560]
I have:

- [✓] Searched open issues to make sure there isn't a request for this icon.
- [✓] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/53331546/67932017-6698df80-fbc3-11e9-964a-e9bdf9dc24a3.png)

## Zip Download

[folder-move-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3792857/folder-move-outline.svg.zip)

**Comment by Templarian** [comment]
Added to your account.
