### ISSUE TITLE
api-off

### ISSUE THREAD

**Issue by sergiocarlotto** [Templarian/MaterialDesign#4561]
Good morning, follow the icon suggestion to set api off.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2835460/67952496-29851b00-fbcc-11e9-8e2e-479425952c7c.png)

## Zip Download

[api-off.zip](https://github.com/Templarian/MaterialDesign/files/3794024/api-off.zip)

**Comment by goyney** [comment]
[![api-off](https://materialdesignicons.com/icon/api-off)](https://materialdesignicons.com/icon/api-off)
