### ISSUE TITLE
web-clock

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4562]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

alternative for [Timezone](https://github.com/Templarian/MaterialDesign/issues/2383)

## Preview

![image](https://user-images.githubusercontent.com/55925048/67962559-8e0c9e00-fbfd-11e9-8a3c-54cc8fb8cf16.png)

## Zip Download

[web-clock.svg.zip](https://github.com/Templarian/MaterialDesign/files/3794630/web-clock.svg.zip)

**Comment by Templarian** [comment]
Added to your account. ✔️
