### ISSUE TITLE
lightbulb-group(-outline) lightbulb-multiple(-outline)

### ISSUE THREAD

**Issue by JasonS1** [Templarian/MaterialDesign#4563]
## Usage

Home Assistant (Smart Home Systems) - building Light/Bulb Groups

## Examples

like --> mdi:account-group

**Comment by JasonS1** [comment]
like this:

![](https://www.pinpng.com/pngs/m/336-3362110_philips-hue-light-bulb-png-transparent-png.png)

**Comment by MrGrigri** [comment]
Here are some that I believe we could add. I've patterned them after `car-multiple` and `account-group`. I believe some of the detail is lost of the `-multiple` modifier is in the bottom-left corner. 

![bulb-multiple](https://user-images.githubusercontent.com/4528551/68136908-43cc3b00-fee3-11e9-9ab2-310adda29c16.png)
![bulb-multiple-outline](https://user-images.githubusercontent.com/4528551/68136919-4a5ab280-fee3-11e9-987e-0a84495104b5.png)
![bulb-group](https://user-images.githubusercontent.com/4528551/68136941-5181c080-fee3-11e9-8e13-28b2310f3d63.png)
![bulb-group-outline](https://user-images.githubusercontent.com/4528551/68136955-58a8ce80-fee3-11e9-9c0e-5e13fbc0a5e7.png)

---

[bulb-modifier.zip](https://github.com/Templarian/MaterialDesign/files/3804899/bulb-modifier.zip)

**Comment by goyney** [comment]
The bases look too wide, shouldn't they be inset 1dp on each size to the width of the bulb?

**Comment by MrGrigri** [comment]
![bulb-multiple](https://user-images.githubusercontent.com/4528551/68141865-93af0000-feeb-11e9-9e55-4982508ca0ad.png)
![bulb-multiple-outline](https://user-images.githubusercontent.com/4528551/68141934-b7724600-feeb-11e9-8f8a-e382e1374145.png)
![bulb-group](https://user-images.githubusercontent.com/4528551/68141984-d07af700-feeb-11e9-81b8-b8116e309eec.png)
![bulb-group-outline](https://user-images.githubusercontent.com/4528551/68142075-fe603b80-feeb-11e9-924b-c19ef4b5e2d9.png)

---

[bulb-modifier.zip](https://github.com/Templarian/MaterialDesign/files/3805210/bulb-modifier.zip)

**Comment by Templarian** [comment]
Added.

**Comment by JasonS1** [comment]
Big THX! :)
