### ISSUE TITLE
home-light(-outline)

### ISSUE THREAD

**Issue by JasonS1** [Templarian/MaterialDesign#4564]
## Usage

For Home Assistant / other Smart Home (IoT) 

## Examples

like mdi:home-thermometer

**Comment by Templarian** [comment]
Like the lights are on/off in a home. hmm... that's going to be difficult with the size.

**Comment by MrGrigri** [comment]
![home-bulb](https://user-images.githubusercontent.com/4528551/68137858-e33dfd80-fee4-11e9-9bd9-a2a33662f3d2.png)
![home-bulb-outline](https://user-images.githubusercontent.com/4528551/68137962-0799da00-fee5-11e9-8162-b46b6203fde0.png)

---
[home-bulb.zip](https://github.com/Templarian/MaterialDesign/files/3804951/home-bulb.zip)

**Comment by Templarian** [comment]
Added. ✔️
