### ISSUE TITLE
How account-box-multiple is called in Google's Material design?

### ISSUE THREAD

**Issue by lcswillems** [Templarian/MaterialDesign#4565]
Hi,

Thank you for this awesome library!! 

This icon is marked as coming from Google Material Design:
https://materialdesignicons.com/icon/account-box-multiple

Do you know the name in Google's library?

**Comment by Templarian** [comment]
@lcswillems I think it's part of their internal extended set or it was pulled from an application they maintain. They have a lot of unpublished internal only icons that we include and attribute to them.

If you don't see it in their set assume it's used in one of their Google apps.

**Comment by Templarian** [comment]
@lcswillems Looked over it at first glance it's called `account-switch` in the extended set. https://petershaggynoble.github.io/MDI-Sandbox/extended/ (maintained by one of out contributors to track Google stuff).

**Comment by lcswillems** [comment]
Thanks for this fast answer.

But if it is an icon from their internal set, am I allowed to use it in my own project?

**Comment by Templarian** [comment]
Sure. Just make sure you use it in a context that makes sense. Like they use it for "account switching". There are other icons in the pack to show multiple users for instance.

**Comment by lcswillems** [comment]
Okay, thank you!
