### ISSUE TITLE
Pressure Icon

### ISSUE THREAD

**Issue by Jesulayo** [Templarian/MaterialDesign#4567]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

icon for barometer pressure

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
Do not delete the issue template! If you can add paste examples you find online to give the team an idea of what this might look like it would be helpful.

**Comment by MrGrigri** [comment]
Couldn't any of the `gauge` icons work?

![gauge](https://materialdesignicons.com/icon/gauge)

**Comment by goyney** [comment]
Closing due to no response in well over a month. Please comment back here if @MrGrigri's suggestion doesn't suit your needs and you have examples of an alternative.
