### ISSUE TITLE
Curtains

### ISSUE THREAD

**Issue by IanAdd** [Templarian/MaterialDesign#4568]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Similar to window-open-variant.
Ideal would be two - curtain open and curtain closed. 

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
Try not to delete the template when submitting issues. ✔️ (edited back)

**Comment by MrGrigri** [comment]
Duplicate of #2523
