### ISSUE TITLE
indentify-scan

### ISSUE THREAD

**Issue by herrsascha** [Templarian/MaterialDesign#4569]
I have:

- [✓] Searched open issues to make sure there isn't a request for this icon.
- [✓] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/53331546/68109760-ae817480-feeb-11e9-8531-1332ed8c5595.png)

## Zip Download

[indentify-scan.svg.zip](https://github.com/Templarian/MaterialDesign/files/3803231/indentify-scan.svg.zip)

**Comment by MrGrigri** [comment]
Idk if this represents identifying and scanning.

**Comment by goyney** [comment]
I agree. `face-recognition` would mean "identity scanning" to me.

[![face-recognition](https://materialdesignicons.com/icon/face-recognition)](https://materialdesignicons.com/icon/face-recognition)

**Comment by goyney** [comment]
If we were to add this, it would need to be named `magnify-scan`. Also, the magnifying lens probably needs to be increased in size and aligned to the grid.

**Comment by herrsascha** [comment]
![image](https://user-images.githubusercontent.com/53331546/68208871-730da580-ffd2-11e9-816c-544e1a63bc61.png)

[magnify-scan.svg.zip](https://github.com/Templarian/MaterialDesign/files/3808999/magnify-scan.svg.zip)

**Comment by Templarian** [comment]
Tweaked and added to your contributor account. 👍
