### ISSUE TITLE
Leg

### ISSUE THREAD

**Issue by igorushi** [Templarian/MaterialDesign#457]

**Comment by CoDEmanX** [comment]
Head: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-170745882
Hand: possibly https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-159449974
Body: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-130788291, re-created version two comments further down
Leg: none so far

**Comment by MrGrigri** [comment]
Why would we need a leg icon?

**Comment by CoDEmanX** [comment]
@MrGrigri Possibly in a medical context, to indicate where you suffer from pain or something like that 👩‍⚕️
