### ISSUE TITLE
language-iapp

### ISSUE THREAD

**Issue by MCwither** [Templarian/MaterialDesign#4570]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Objective
iApp is a Chinese programming language. It's simple and convenient. The icon is made according to this picture
![icon_iapp](https://user-images.githubusercontent.com/47308278/68121506-e7006d00-ff42-11e9-9b80-7e31c63c7c1a.png)

## Preview

![language-iapp](https://user-images.githubusercontent.com/47308278/68121267-45791b80-ff42-11e9-9ecf-0c531bb394b9.png)

## Zip Download

[removed Attach the ZIP]

**Comment by goyney** [comment]
Is that the official logo for the language? Can you provide some links. Because this is a potential Brand Icons, we need to be sure we're following their branding guidelines.

**Comment by Templarian** [comment]
Literally can't find anything on google about this or what it is. Also upload the zip to github, please don't link to external sites.

**Comment by MCwither** [comment]
@goyney  Yes, it can't be found.It doesn't have an accurate website.So I can't provide a link.But iApp doesn't need to be validated.

**Comment by MCwither** [comment]
@Templarian My browser can't upload files.Can I tell you the path information?
``` M9,4L15,4L15,7L9,7zM4,9L4,11L9,11L9,20L15,20L15,9L4,9
```

**Comment by PeterShaggyNoble** [comment]
Is there a repo for it? A community run site? Anything? A quick search and the only result I can find on Google related to iApp as a language is this issue.

**Comment by MCwither** [comment]
@PeterShaggyNoble Please use Baidu search engine.
http://www.baidu.com/
So we should find it.

**Comment by MrGrigri** [comment]
@MCwither, thank you for your contribution; however, this is going to be to niche for this project.
