### ISSUE TITLE
toy-brick(-modifiers)(-outline)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4571]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Aliases: 

- [ ] lego
- [ ] plugin
- [ ] extension

## Preview

![toy-brick](https://user-images.githubusercontent.com/4528551/68148469-4a65ad00-fef9-11e9-917d-64d4ea21853c.png) ![toy-brick-outline](https://user-images.githubusercontent.com/4528551/68148491-52bde800-fef9-11e9-8812-8114b65fb4dc.png)

![toy-brick-plus](https://user-images.githubusercontent.com/4528551/68148586-87ca3a80-fef9-11e9-8e21-e7c9c770eed7.png) ![toy-brick-plus-outline](https://user-images.githubusercontent.com/4528551/68148815-f0b1b280-fef9-11e9-8ff2-f17b029f91f6.png)

![toy-brick-remove](https://user-images.githubusercontent.com/4528551/68148733-c8c24f00-fef9-11e9-93d9-ad769396d063.png) ![toy-brick-remove-outline](https://user-images.githubusercontent.com/4528551/68148776-e1cb0000-fef9-11e9-9f23-d862c0c7ec7a.png)

![toy-brick-minus](https://user-images.githubusercontent.com/4528551/68148942-35d5e480-fefa-11e9-9c9e-a975ade75caf.png) ![toy-brick-minus-outline](https://user-images.githubusercontent.com/4528551/68148994-50a85900-fefa-11e9-9c93-a7ba090512b4.png)

![toy-brick-marker](https://user-images.githubusercontent.com/4528551/68149197-af6dd280-fefa-11e9-8cf2-336bd9324edf.png) ![toy-brick-marker-outline](https://user-images.githubusercontent.com/4528551/68156058-3c6b5880-ff08-11e9-9429-f8c41380c1f6.png)

![toy-brick-search](https://user-images.githubusercontent.com/4528551/68149334-fbb91280-fefa-11e9-8e2d-f42c4089be08.png) ![toy-brick-search-outline](https://user-images.githubusercontent.com/4528551/68156100-5ad15400-ff08-11e9-87a9-49833c42dec3.png)

## Zip Download

[toy-brick.zip](https://github.com/Templarian/MaterialDesign/files/3805982/toy-brick.zip)

**Comment by Templarian** [comment]
`toy-brick-search-outline` needs to use the round cutout. We don't do flat cutouts on the search modifier.

**Comment by Templarian** [comment]
Same goes for the marker.

**Comment by MrGrigri** [comment]
Updated

**Comment by Templarian** [comment]
Added. ✅

**Comment by Templarian** [comment]
@MrGrigri Can you add the aliases. Reopening.

**Comment by MrGrigri** [comment]
Added.
