### ISSUE TITLE
Plus circle icon is not displaying

### ISSUE THREAD

**Issue by Mish325** [Templarian/MaterialDesign#4572]
Hi,

I installed the icon pack using the CDN and tried using the "plus-circle" icon. But it's not displaying in the UI. Any way to fix this issue?

**Comment by goyney** [comment]
You will need to provide more details than that. How did you install it? How are you including it? How are you trying to display the icon? Do you have a reproducible example?

**Comment by Templarian** [comment]
Yeah, `plus-circle` is a initial release icon added 5+ years ago. If it doesn't work none of the icons would work. 😕

**Comment by Mish325** [comment]
Hi @goyney.

I installed it using CDN and here the code I used.

<link href="https://cdn.materialdesignicons.com/4.5.95/css/materialdesignicons.min.css" rel="stylesheet">

I tried to display the icon as below,

<i ng-class="{'mdi mdi-plus-circle' : !isTenantAlreadyCreated, 'fa fa-spinner' : isTenantConnecting, 'fa fa-check-circle' : isTenantAlreadyCreated}"></i>

For the moment I don't have a reproducible example. But I want to display the icon as below,

![image](https://user-images.githubusercontent.com/19853627/68269564-3e582780-0080-11ea-8a82-84041a93962b.png)

**Comment by Templarian** [comment]
https://codepen.io/templarian/pen/dyymKVx

Closing as not reproducible. Make sure your not applying multiple of those classes at the same time. Inspect and make sure only `mdi mdi-plus-circle` is in the CSS and you're not mixing in those `fa` classes.
