### ISSUE TITLE
file-web

### ISSUE THREAD

**Issue by MCwither** [Templarian/MaterialDesign#4573]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have a need for icons, but I can't make up my mind
It can be used in file browser.
`file-web` 

## Examples

![file_web](https://user-images.githubusercontent.com/47308278/68299108-ff54c100-00d5-11ea-9eca-2cde83d362c3.png)

**Comment by MrGrigri** [comment]
@MCwither, please do not delete the issue template. Also please find some examples or explain what this icon should or would be used for.

**Comment by St-Ex** [comment]
Using [file-sync-outline](https://materialdesignicons.com/icon/file-sync-outline) as template
[![fileWeb](https://user-images.githubusercontent.com/2870576/69615550-5a266c00-1035-11ea-9d31-6495051971db.png)](https://github.com/Templarian/MaterialDesign/files/3890951/fileWeb.zip)

**Comment by Templarian** [comment]
The globe is too much detail. Lets try to find another icon or design to do this with. I don't want to start a precedent of using such an icon for `web` as an overlay.

**Comment by St-Ex** [comment]
Paradigm inversion, it's just a design idea not a prototype

![fileWeb](https://user-images.githubusercontent.com/2870576/69807695-36eeee80-11e6-11ea-8d16-c661f4550ccc.png)

**Comment by CoDEmanX** [comment]
12dp diameter, 1dp stroke is a bit better:

![grafik](https://user-images.githubusercontent.com/1309249/71302177-786b5780-23a8-11ea-9d99-e60751140dda.png)

12dp diameter, 1.5dp stroke is a big no-no:

![grafik](https://user-images.githubusercontent.com/1309249/71302197-92a53580-23a8-11ea-9382-4e4d352536b8.png)

**Comment by goyney** [comment]
@CoDEmanX Nice attempts, but as @Templarian stated, we don't want to state a precedent for using that as an overlay.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/72686090-57d11300-3ab6-11ea-90da-46ebb90c0982.png) 
![image](https://user-images.githubusercontent.com/338885/72686098-6dded380-3ab6-11ea-98db-5fba566dac47.png)

**Comment by Templarian** [comment]
Not a fan of any of these designs. Thinking we may just want to close this one out.

**Comment by CoDEmanX** [comment]
Not to bad actually.

`file-clock` has quite a large circle which touches the triangle, but doing that here doesn't work that well:

![grafik](https://user-images.githubusercontent.com/1309249/72690841-5f2d0680-3b20-11ea-85ba-5be10123c0c6.png)

Here I tried a smaller circle, and a horizontal line which isn't in the middle, but its upper side aligned to grid (0.5dp down from center):

![grafik](https://user-images.githubusercontent.com/1309249/72691079-cea3f580-3b22-11ea-8098-698f500856c9.png)

**Comment by goyney** [comment]
@Templarian Thoughts on this one?

**Comment by goyney** [comment]
Pinging @Templarian one more time on this one. If no new information is presented in another week or so, we'll close this one and reject it.
