### ISSUE TITLE
print-settings

### ISSUE THREAD

**Issue by motabass** [Templarian/MaterialDesign#4575]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Could represent print-settings

## Examples

Could an combination of 'settings' and 'print'

**Comment by goyney** [comment]
We already have `printer-settings`.

[![printer-settings](https://materialdesignicons.com/icon/printer-settings)](https://materialdesignicons.com/icon/printer-settings)
