### ISSUE TITLE
Using icons from @mdi/js imports entire package

### ISSUE THREAD

**Issue by Immugio** [Templarian/MaterialDesign#4576]
I'm using a few icons from the @mdi/js. The package is added as devDependency and the import is done in this way:

`import { mdiFlipHorizontal, .. } from "@mdi/js";`

After building the project with webpack this result in approx. 1.6MB extra size added to the output bundle. Is there any way to just import a single icon?

**Comment by Templarian** [comment]
Does it do this even for a production build?

Might be how your project is configured.

**Comment by Immugio** [comment]
> Does it do this even for a production build?
> 
> Might be how your project is configured.

I found a solution, the problem was in the configuration in my tscofig I had `"module":"commonjs"`. The module type needs to be es6 for the tree shaking to work. Thanks

**Comment by Templarian** [comment]
I'll add this to the documentation after work. Needs a troubleshooting section.

**Comment by Templarian** [comment]
Added to the docs for webpack. https://dev.materialdesignicons.com/getting-started/webpack

**Comment by JapanYoshi** [comment]
If you're using ``@font-face`` to import [the Web font](https://dev.materialdesignicons.com/getting-started/webfont), and you know the Unicode code point of the icons you need, you can use the property ``unicode-range`` to only import the necessary glyphs. Google Fonts does this to specify the character set you need (e.g. Latin Extended, Devanagari, etc.).
[Documentation of ``unicode-range``](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/unicode-range)

**Comment by Templarian** [comment]
@JapanYoshi This is for the `@mdi/js` package. I think you might be replying to the wrong issue?

**Comment by guyyst** [comment]
I'm using `"module": "es2020"`, and I'm observing the same issue. Just importing and using one icon bumps up the build size by 2.6mb. Going down to `es6` is not an option for my at this point.

**Comment by Templarian** [comment]
@guyyst Can you give more details about your setup? Webpack / Rollup / TS etc?

**Comment by Immugio** [comment]
> I'm using `"module": "es2020"`, and I'm still observing the same issue. Just importing and using one icon bumps up the build size by 2.6mb. Going down to `es6` is not an option for my at this point.

@guyyst try this and see if it helps 
`"module": "es6",
"moduleResolution": "node",`

**Comment by guyyst** [comment]
I spun up a new angular app on `es2020` with nothing but `@mdi/js` installed and the tree shaking is working properly. I must have misconfigured something in my other project since the package is working just fine 👍

**Comment by emileNetter** [comment]
Hi I'm using create-react-app and @mdi/js. I'm only using a few icons from @mdi/js but the bundle size is 1.76MB larger (33% of total bundle size) even for production build. So I assume tree shaking is not working. I do not have access to webpack config (because I'm using create-react-app). Have you ever encountered this issue ?

**Comment by Templarian** [comment]
@emileNetter Seeing the same thing with `npm run build` ?

**Comment by Templarian** [comment]
Sorry, too early, can't read you already said that.

**Comment by emileNetter** [comment]
I use https://www.npmjs.com/package/source-map-explorer to analyze bundle size (after npm run build)

**Comment by Templarian** [comment]
@emileNetter You're importing only single icons right? `import { mdiAccount } from '@mdi/js';` ?

Not really sure what could be happening. It should just work as that uses webpack.

**Comment by emileNetter** [comment]
Yes I'm only importing single icons like in your example

**Comment by morriq** [comment]
We have the same issue I think:

![image](https://user-images.githubusercontent.com/2962338/91542297-eb58a500-e91d-11ea-83c9-d71cf359ae77.png)

We use maybe 20 icons and webpack with libraryTarget umd

**Comment by lpaulger** [comment]
@emileNetter I'm running into this problem as well now. Any chance you found the cause? 

I've got 29 icons imported and seeing 2.04 MB for `@mdi/js` inside my bundle when I analyze with https://www.npmjs.com/package/source-map-explorer

**Comment by Immugio** [comment]
> @emileNetter I'm running into this problem as well now. Any chance you found the cause?
> 
> I've got 29 icons imported and seeing 2.04 MB for `@mdi/js` inside my bundle when I analyze with https://www.npmjs.com/package/source-map-explorer

Can you share your setup?

**Comment by DinnieJ** [comment]
@Immugio can you tell me which version of mdi/js you are using

**Comment by kwisatz** [comment]
Seeing the same behavior with this `tsconfig`:

```
    "moduleResolution":                 "node",
    "target":                           "es2018",
    "module":                           "esnext",
```

I get tree-shaking for other modules, but not for `mdi.js` of which we always have the full `2.08Mb` (unminified).

**Comment by Bruce17** [comment]
I'm having the same issue for a Vue.js v2 project using typescript.

Dependencies:
* vue@2.6.14
* @mdi/js@6.7.96
* typescript@4.5.5

The issue occurs when building as web component using the command `vue-cli-service build --target wc --name some-name`. Using `vue-cli-service build` it seems to build just find.

Altering the target version from `esnext` to `es2020` or `es6` didn't help at all in my case.

**Comment by oceangravity** [comment]
Hi guys, same here 😔

**Comment by CodeDG** [comment]
Hello, same issue.

package.json:
`   "webpack": "^4.43.0",
    "typescript": "^3.9.9",
    "terser-webpack-plugin": "^4.2.3",
    "@mdi/js": "^5.9.55"
`
tsconfig.json:
   `"module": "es6",
    "moduleResolution": "node",`

**Comment by mririgoyen** [comment]
If you feel that this is still an issue, please provide us with a barebones git repository proving the issue.

Through extensive testing, I have personally never been able to reproduce this issue under normal, default circumstances. Depending on your bundler/settings, while in development mode tree-shaking does not occur. There are also other settings, plugins, etc. that might disable or hinder tree-shaking.

Sidenote, I'm literally working on the new Pictogrammers/MDI website as we speak and I just double-checked the production output and only the icons being included are bundled, further confirming a likely configuration issue on your end.

**Comment by gabrieljbaker** [comment]
@mririgoyen , is treeshaking possible in any target besides es6? I’m not able to get tree shaking working for my webpack 5 project and es6 is not an option for me.

**Comment by susnux** [comment]
We had the same issue, the reason is the invalid / missing exports. Causing webpack to import the commonjs version that gets not tree-shaken.
The solution: https://github.com/Templarian/MaterialDesign-JS/pull/29

**Comment by kirkcola** [comment]
In our case, the reason for tree-shaking not working of the `@mdi/js` is that we used `TerserPlugin.esbuildMinify` as the minification tool. 
However, esbuild's minification mechanism seems to primarily focus on module & function tree-shaking, and its support for dead code elimination of single module constants is quite limited.
Switching to `TerserPlugin.swcMinify` resolved this issue.

Sry for replying to a closed issue, just wanted to remind others who might encounter a similar problem.
