### ISSUE TITLE
refresh document icon

### ISSUE THREAD

**Issue by nimrod-cohen** [Templarian/MaterialDesign#4577]
I have:

- [V ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ V] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ V] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would use it to regenerate a document, or refresh a collaborative view of the online document

## Examples

![Screen Shot 2019-11-08 at 1 26 23](https://user-images.githubusercontent.com/7694428/68436606-2808b380-01c7-11ea-8f57-96356e424293.png)

**Comment by Templarian** [comment]
Assume you closed after seeing `file-sync` going out in `4.6.95`'s release?

**Comment by nimrod-cohen** [comment]
yes, and there's file-restore which can also be of similar visual
