### ISSUE TITLE
truck-outline, truck-check-outline, truck-delivery-outline, truck-fast-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4579]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Variants of truck, truck-check, truck-delivery, truck-fast

## Examples

![truck](https://user-images.githubusercontent.com/6717356/68495179-b7ae7080-0260-11ea-9b55-e0715f59514d.png)

**Comment by Templarian** [comment]
Added (obviously not the designs above, but MD styled ones).
