### ISSUE TITLE
sofa

### ISSUE THREAD

**Issue by mlazzari-tribecube** [Templarian/MaterialDesign#458]
something like https://thenounproject.com/term/sofa/45002/ but more "material" :)

**Comment by mlazzari-tribecube** [comment]
any chance to have this one? just asking

**Comment by CoDEmanX** [comment]
Some experiments:
![sofa1](https://cloud.githubusercontent.com/assets/1309249/9004893/39f4ab38-377a-11e5-9062-5e4a3478181f.png)
![sofa2](https://cloud.githubusercontent.com/assets/1309249/9004896/39fa59b6-377a-11e5-85ed-26277a86a461.png)
![sofa3](https://cloud.githubusercontent.com/assets/1309249/9004894/39f68e94-377a-11e5-9c68-44a7a4881e33.png)
![sofa4](https://cloud.githubusercontent.com/assets/1309249/9004895/39f6f6c2-377a-11e5-85e5-6e3190aeb297.png)

![sofa1](https://cloud.githubusercontent.com/assets/1309249/9004974/bd123792-377a-11e5-928a-bf7d8baed79d.png)
![sofa2](https://cloud.githubusercontent.com/assets/1309249/9004973/bd0f1ada-377a-11e5-822f-d4eaa9c43d83.png)
![sofa3](https://cloud.githubusercontent.com/assets/1309249/9004972/bd0f0450-377a-11e5-889f-057028fa4ac3.png)
![sofa4](https://cloud.githubusercontent.com/assets/1309249/9004975/bd131f54-377a-11e5-91b8-120daaaa8353.png)

**Comment by Templarian** [comment]
4th one definitely. I'll get it added in shortly. Kind of nice using the material up slack chat to vote.

**Comment by CoDEmanX** [comment]
![sofa7](https://cloud.githubusercontent.com/assets/1309249/9047047/73560d4c-3a2f-11e5-9503-d19daa83ddd6.png) increased rounding of the seating surface edges to 2px - [Dropbox](https://www.dropbox.com/s/nu8n0spre7mwsil/sofa7.svg?dl=0)
![sofa6](https://cloud.githubusercontent.com/assets/1309249/9047046/733dedac-3a2f-11e5-951c-0afc6425ec59.png) ... and the little brother! (2px margin left and right) - [Dropbox](https://www.dropbox.com/s/gv63etmxpjv0g2h/sofa6.svg?dl=0)

**Comment by Templarian** [comment]
Why would the robot face need armrests. :grin:

I still kind of like the 4th more than the others for the simplicity.

**Comment by CoDEmanX** [comment]
What does it do with a [couch](http://couchdb.apache.org/) at all? :wink:

The 4th isn't too wide if placed next to event seat:
![ic_event_seat_24px](https://cloud.githubusercontent.com/assets/1309249/9047825/d47cbc2e-3a34-11e5-95b9-cb3a1a7ec26a.png)

**Comment by Templarian** [comment]
So... the 4th from the comment [above](/458#issuecomment-126630037) matches it best?

Or the 1st from the comment 2 above this? Either matches the stock seat pretty well.

**Comment by CoDEmanX** [comment]
![ic_event_seat_24px](https://cloud.githubusercontent.com/assets/1309249/9047825/d47cbc2e-3a34-11e5-95b9-cb3a1a7ec26a.png) ![event-sofa](https://cloud.githubusercontent.com/assets/1309249/9047975/e09eb240-3a35-11e5-8d24-7d162266956f.png) ![sofa7](https://cloud.githubusercontent.com/assets/1309249/9048012/2bca97d4-3a36-11e5-9207-9327d4c9aa11.png)

I tried to adapt event seat, but doesn't look that good... https://www.dropbox.com/s/haacauhsw8upxpl/event-sofa.svg?dl=0

The 4th from that post ya, so your initial favorite is probably the best choice. I updated the SVG to use 3px bottom margin like event seat though:
https://www.dropbox.com/s/nu8n0spre7mwsil/sofa7.svg?dl=0

**Comment by Templarian** [comment]
Looks good. Yea matching their style for the couch looks odd by itself.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/sofa

**Comment by CoDEmanX** [comment]
Nice modification, no more 1px rounding and looks really good!
