### ISSUE TITLE
IOT ( internet of things ) 

### ISSUE THREAD

**Issue by GauravPatni** [Templarian/MaterialDesign#4580]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

IOT ( internet of things ) related icons 

## Examples

e.g.
- wireless connectivity ,
- sensors such as pressure , temperature , humidity , soil moisture , co2, water meter , gas meter , flow meter , tank level , wind speed - direction , soalr radiation , solar panel ,touch sensor , speed meter etc...
- smart city related

**Comment by JapanYoshi** [comment]
We have ``wifi``, ``wifi-strength-n``, ``bluetooth``, ``gauge`` (aliased ``barometer``), ``thermometer`` (aliased ``temperature``), ``water``, ``water-percent`` (aliased ``humidity``), ``wave``, ``co2``, ``weather-windy``, ``shield-sun``, ``solar-panel``, ``gesture-tap``, and ``speedometer``. They should cover at least 90% of those icons. If you need any other icons, please start a new thread for each of them.

**Comment by Templarian** [comment]
Please create individual issues for any missing IoT devices. As said above most of these exist in some fashion.
