### ISSUE TITLE
CTA Button Icon

### ISSUE THREAD

**Issue by zgover** [Templarian/MaterialDesign#4581]
## Usage

Indicates a call to action button element, for uses in which case the user may choose whether to show a button vs another action element. CMS, CRM etc.

## Examples

<img width="158" alt="Screen Shot 2019-11-09 at 4 46 28 AM" src="https://user-images.githubusercontent.com/9044773/68527431-6b891d80-02ac-11ea-82f3-f20263ad6f3d.png">

**Comment by goyney** [comment]
I'm confused. We already have `gesture-tap`, which is in your example.

[![gesture-tap](https://materialdesignicons.com/icon/gesture-tap)](https://materialdesignicons.com/icon/gesture-tap)

**Comment by goyney** [comment]
Closing since we haven't heard back from in you in a week on this. If there is more information to share on this issue, please feel free to comment here.

**Comment by zgover** [comment]
My apologies notifications got shut off.

To address your comment; you're correct a gesture tap does indicate a tap/touch, however it is more vague and broadly suggests the end-users' following interaction and due to it's simplistic nature it is often perceived as "open ended," (e.g. offering the user to make that choice or proceed with their original path in which may not require the user to take action vs a call to action "value prop" tending to be the only available action). Obviously these are purely based on the UX design. However, by providing both the suggestive "user interaction"(i.e. gesture tap) alongside a "user action"(i.e. cta), it will provide the benefit to the organizer to choose based on the flow of their application or funnel.

Use Case #1 (Tutorial – Gesture-Tap):
`Open the drawer menu by tapping on the gesture in the top right corner`-> *discreetly in the bottom left – "Skip Tutorial"*

Use Case #2 (Lead Form – CTA):
`Proceed to Next Step` -> *only providing a back/next button to edit previous details* 

Do keep in mind these use cases are modeled with the focus of the end-user (e.g. digital immigrant/admin) building through a gui. The variation of the two may greatly differ provided the features in which may determine whether the user is building a step-through form with a drag-n-drop, all the way to a custom defined user action such as through a walk-through tutorial with the outcome being deterministic on the previously recorded data of whether or not they closed the view but returned later etc.. 

I think you get my direction now, let discuss if you got further input.

**Comment by zgover** [comment]
I see some are confused, let me provide a little more straight forward example.

**Use Case #3**
User is building a web page with a drag-n-drop editor. Within the editor there is a canvas containing the current web page the user is building. There is a panel which contains a list of draggable **dom elements** and another panel which contains a list of draggable **dom events**.

Let's say there is a button (<img width="75" alt="Screen Shot 2019-11-09 at 4 46 28 AM" src="https://user-images.githubusercontent.com/9044773/68527431-6b891d80-02ac-11ea-82f3-f20263ad6f3d.png">) within the panel containing a list of **dom elements**, which the user may drag into the canvas to place within their page. 

Now in the other panel containing the list of **dom events** there is a click/touch event (<img width="25" alt="Screen Shot 2019-12-01 at 8 18 22 PM" src="https://user-images.githubusercontent.com/9044773/69925887-ca8b1e00-1477-11ea-9394-4a479469ea50.png">) which the user may attach it by dragging it into the *new button* they had previously dragged into the canvas.

---

Within the icons on Material.io they provide a [similar icon _'call_to_action'_](https://material.io/resources/icons/?search=call&icon=call_to_action&style=baseline) (<img width="25" alt="Screen Shot 2019-12-01 at 8 26 57 PM" src="https://user-images.githubusercontent.com/9044773/69926142-f4911000-1478-11ea-82d7-14d66033eb43.png">) to what I am suggesting, however the **issue** with that icon is as follows:
- Surrounding dark background suggests it is contained within another element such as a parent div container.
- Potentially indicates a bottom bar or any other plain block element.
- Inappropriately suggests its position within the document or parent element.
- Does NOT indicate it has a potential for an action/gesture/user-interaction.

**Comment by zgover** [comment]
@goyney Where is your confusion? Can't elaborate if you don't provide an explanation to your confusion.

**Comment by goyney** [comment]
All of your use cases and valid use cases, but I fail to see where we need a new icon for this. Icons are meant to be supplementary and contextual, especially in the use cases your are describing, meaning there should be other textual content accompanying the icon that together convey the meaning or action. That would be good UX.

All those use cases aside, your proposed button with the pointer hand just won't work as an icon. The hand would need to be shrunk down to a point that would break Material guidelines.

The best we could probably do is `gesture-tap-box`.

![image](https://user-images.githubusercontent.com/1015040/69965542-7a957100-14e2-11ea-85c7-365c12a3a257.png)

If that works for you, we'll consider adding it. If not, I'm going to recommend we close this issue.

**Comment by zgover** [comment]
Yes, I agree and the textual content representing the icon nearby is implied/assumed of its existence (at least from my preference). However in times such as the use cases provided, you can agree providing an icon to represent two separate items just due to its broad nature; will 9/10 times confuse the end-user. You wouldn't place two items indicating tap and double-tap within the same view using only `gesture-tap` when `gesture-two-tap` is available or even more broad the `gesture`, so I don't see a clear reason to ignore the diversity of an actionable element, especially when Material provides a `call_to_action` in their minimal library.

The example you provided `gesture-tap-box` is a bit too similar to Material *filled* icons. Something as follows would be better fitting

![Screen Shot 2019-12-02 at 2 47 31 PM](https://user-images.githubusercontent.com/9044773/69995664-21dfcb80-1516-11ea-969b-2143b143942b.png)

**Comment by goyney** [comment]
And yet, what you provided as an example isn't Material and isn't possible with the size of the hand and gesture. The finger is already 2dp wide and cannot be made thinner. The "button" is not at least 2dp wide.

**Comment by goyney** [comment]
We're internally discussing the following:

![image](https://user-images.githubusercontent.com/1015040/70014233-28873680-1548-11ea-887a-19f787657b4c.png)

[gesture-tap-button.svg.zip](https://github.com/Templarian/MaterialDesign/files/3914155/gesture-tap-button.svg.zip)

**Comment by goyney** [comment]
We've added the following two to address this issue:
[![gesture-tap-box](https://materialdesignicons.com/icon/gesture-tap-box)](https://materialdesignicons.com/icon/gesture-tap-box)[![gesture-tap-button](https://materialdesignicons.com/icon/gesture-tap-button)](https://materialdesignicons.com/icon/gesture-tap-button)
