### ISSUE TITLE
cheese

### ISSUE THREAD

**Issue by lucasbkatayama** [Templarian/MaterialDesign#4582]
I have:

- [ X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Just want to put an icon on my category page. And the category needed is 'Cheese'

## Examples

Well theres is easy to imagine a cheese. And I'm got very curious about why there's no cheese on this library, cheese is so good to see and eat. My example is the github icon :cheese: , even github cares about cheese. Thanks

**Comment by JapanYoshi** [comment]
I tried to make a top-down icon because we want to avoid dimensionality.
![image](https://user-images.githubusercontent.com/8707990/68539435-0f66ec00-03c7-11ea-9bf8-b90e4017c509.png)

**Comment by lucaskatayamaHVL** [comment]
Thank you for the icon, but it looks too simple.

**Comment by JapanYoshi** [comment]
So does anyone else want to take a crack at a cheese icon that avoids dimensionality?

**Comment by St-Ex** [comment]
[![cheese](https://user-images.githubusercontent.com/2870576/69575050-d1beb180-0fc9-11ea-9141-d8842db7cf63.png)](https://github.com/Templarian/MaterialDesign/files/3888571/cheese.zip)

**Comment by Templarian** [comment]
@St-Ex Needs to be aligned to the grid, but I like the design. 👍

**Comment by St-Ex** [comment]
[![cheese](https://user-images.githubusercontent.com/2870576/69579787-80b3bb00-0fd3-11ea-9b90-88d5038300c8.png)](https://github.com/Templarian/MaterialDesign/files/3888831/cheese.zip)

**Comment by goyney** [comment]
Adjusted so everything is aligned to the grid:
[![cheese](https://materialdesignicons.com/icon/cheese)](https://materialdesignicons.com/icon/cheese)
