### ISSUE TITLE
combination light + fan

### ISSUE THREAD

**Issue by xspyboyx** [Templarian/MaterialDesign#4583]
I have several switches I use in my Home Automation that are a combo switch that is light and fan. I would love to see an icon for this.
Something like this?
![image](https://user-images.githubusercontent.com/24324682/68533950-f1748b00-02e3-11ea-992a-dd5954412a9a.png)
.

**Comment by nilsfast** [comment]
Like in #4772 ?

**Comment by goyney** [comment]
This doesn't work in the space we have. We recently added `ceiling-fan` and `ceiling-fan-light`. If those don't solve your use case and you have another idea, please feel free to comment back here and we can reevaluate. Thanks for your suggestion!
