### ISSUE TITLE
map-marker-multiple-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4584]
I have:
- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Variant of map-marker-multiple.

## Examples
![map-marker-multiple](https://user-images.githubusercontent.com/6717356/68548213-61c20000-03fb-11ea-91cb-c7e5b006b964.png)

**Comment by Templarian** [comment]
Added. ✅
