### ISSUE TITLE
ceiling lamp

### ISSUE THREAD

**Issue by mleiber** [Templarian/MaterialDesign#4585]
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

any light directly affixed to the ceiling, could be round or square

## Examples

https://images-na.ssl-images-amazon.com/images/I/31voINeL3IL.jpg

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/wall-sconce-flat)](https://materialdesignicons.com/icon/wall-sconce-flat)

**Comment by mleiber** [comment]
I was looking for something more like this. Ceiling, not wall mounted. Not sure what the 'rules' for similarity.

![image](https://user-images.githubusercontent.com/52375201/68654648-aef2be80-052e-11ea-827a-03549e97dd96.png)

Screenshot from the Philips Hue app - mentioning it for copyright purposes.

**Comment by Mariusthvdb** [comment]
no need to screenshot them, here's the full icon pack: https://developers.meethue.com/wp-content/uploads/2019/10/HueIconPack2019_2.zip

note they are bound to copyright and use with their products

**Comment by GreenTurtwig** [comment]
Unfortunately that would go against the MD guidelines, so `wall-sconce-flat` is really your only option.
> "Don’t tilt, rotate, or make icons appear dimensional."

Added the alias of `ceiling-light-flat` to `wall-sconce-flat`.

**Comment by mleiber** [comment]
ok, thx for the detailed explanations. And thx for adding an alias so it can be found more easily.
