### ISSUE TITLE
hexadecimal

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4586]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/68615463-1e19d580-0491-11ea-87be-e748d4f362f3.png)

## Zip Download

[hexedecimal.svg.zip](https://github.com/Templarian/MaterialDesign/files/3832962/hexedecimal.svg.zip)

**Comment by SSinischo** [comment]
![Screenshot from 2019-11-17 22-35-20](https://user-images.githubusercontent.com/15145783/69022830-90575200-098a-11ea-9df7-9ba0dabbebab.png)

**Comment by goyney** [comment]
[![hexadecimal](https://materialdesignicons.com/icon/hexadecimal)](https://materialdesignicons.com/icon/hexadecimal)
