### ISSUE TITLE
lightbulb-cfl-spiral

### ISSUE THREAD

**Issue by Undearius** [Templarian/MaterialDesign#4587]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

This is an addition to the CFL referenced in #4471 for the spiral variant of CFLs

## Preview

![image](https://user-images.githubusercontent.com/1106442/68651948-6fa87b80-04f6-11ea-9b98-71ae163c4007.png)

## Zip Download

[lightbulb-cfl-spiral.zip](https://github.com/Templarian/MaterialDesign/files/3834948/lightbulb-cfl-spiral.zip)

**Comment by goyney** [comment]
Preview of @Undearius' contribution:
![image](https://user-images.githubusercontent.com/1015040/68700111-60efb200-0552-11ea-95de-abd0924cb9c0.png)

Feel like it's too much detail at native resolution.

**Comment by JamesCoyle** [comment]
Probably be better if it lost one of the twists and increased spacing etc to 1.5dp.

**Comment by Undearius** [comment]
Agreed, this looks better. Sorry, the preview generator is not working for me
![image](https://user-images.githubusercontent.com/1106442/68703210-2d178b00-0558-11ea-9a80-4ca65a13ca64.png)1000%
![image](https://user-images.githubusercontent.com/1106442/68703256-40c2f180-0558-11ea-8bcf-93c5a72bc810.png)100%



[lightbulb-cfl-spiral2.zip](https://github.com/Templarian/MaterialDesign/files/3837832/lightbulb-cfl-spiral2.zip)

**Comment by Undearius** [comment]
Minor change that I'm a bit more keen on
[lightbulb-cfl-spiral3.zip](https://github.com/Templarian/MaterialDesign/files/3838077/lightbulb-cfl-spiral3.zip)


![image](https://user-images.githubusercontent.com/1106442/68707917-a74c0d80-0560-11ea-9b9f-fcda380acd14.png)
![image](https://user-images.githubusercontent.com/1106442/68707167-39ebad00-055f-11ea-9d9f-89a9b4ba5434.png)

**Comment by Templarian** [comment]
Added. @Undearius Please let us know when you have 5 icons in the system and we'll add a contributor account. Right now it's assigned to the shared account.
