### ISSUE TITLE
clipboard-accounts

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4588]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Not sure about naming; single clipboard, multiple accounts… :)

If approved, I'll create an outlined version as well

## Preview

![image](https://user-images.githubusercontent.com/55925048/68663567-39431e80-053f-11ea-9a8d-f4fda03508c4.png)

## Zip Download

[clipboard-accounts.svg.zip](https://github.com/Templarian/MaterialDesign/files/3835611/clipboard-accounts.svg.zip)

**Comment by Templarian** [comment]
Feel like this might be too specific as we already have `clipboard-account`.

**Comment by Templarian** [comment]
Also we've never had a `-multiple-multiple` before. Interesting edge case.

http://dev.materialdesignicons.com/contribute/icon-naming Generally keeps track of these things.

**Comment by frankgrinaert** [comment]
> Feel like this might be too specific as we already have `clipboard-account`.
Might indicate a shared assignment, but agreed it is quite obscure.

> Also we've never had a `-multiple-multiple` before. Interesting edge case.
Ha! Stress-testing the naming system ;)

**Comment by goyney** [comment]
We're going to defer on this one as too niche. Thanks for the suggestion.
