### ISSUE TITLE
clipboard-check-multiple

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4589]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

If approved, I'll create an outlined version as well

## Preview

![image](https://user-images.githubusercontent.com/55925048/68663738-7c9d8d00-053f-11ea-8601-1ebc179d9c98.png)

## Zip Download

[clipboard-check-multiple.svg.zip](https://github.com/Templarian/MaterialDesign/files/3835618/clipboard-check-multiple.svg.zip)

**Comment by Templarian** [comment]
Added. ✅

You're up to 15 icons now. 🎉  These type of icons are very useful for the community since utility icons get the most use in our system! 😃

**Comment by Templarian** [comment]
Assigned the `-outline` to you also. If you can add those also as you make these.

**Comment by frankgrinaert** [comment]
> You're up to 15 icons now. 🎉 These type of icons are very useful for the community since utility icons get the most use in our system! 😃

Cheers! Happy to contribute. This set has been an amazing resource for me over the years.

> Assigned the `-outline` to you also. If you can add those also as you make these.

Got it! Thanks
