### ISSUE TITLE
clipboard-multiple

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4590]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

If approved, I'll create an outlined version as well

## Preview

![image](https://user-images.githubusercontent.com/55925048/68663890-b373a300-053f-11ea-85da-4064369d711d.png)

## Zip Download

[clipboard-multiple.svg.zip](https://github.com/Templarian/MaterialDesign/files/3835626/clipboard-multiple.svg.zip)

**Comment by Templarian** [comment]
Added (also added `-outline`).
