### ISSUE TITLE
clipboard-play-multiple

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4591]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

If approved, I'll create an outlined version as well

## Preview

![image](https://user-images.githubusercontent.com/55925048/68664066-ffbee300-053f-11ea-996e-8e109df5d7dc.png)

## Zip Download

[clipboard-play-multiple.svg.zip](https://github.com/Templarian/MaterialDesign/files/3835629/clipboard-play-multiple.svg.zip)

**Comment by frankgrinaert** [comment]
![image](https://user-images.githubusercontent.com/55925048/69009255-eceb4a80-0953-11ea-9822-34b23fbaa0ca.png)
![image](https://user-images.githubusercontent.com/55925048/69009259-f5dc1c00-0953-11ea-8da9-7125a302957d.png)

[clipboard-play-multiple.zip](https://github.com/Templarian/MaterialDesign/files/3855704/clipboard-play-multiple.zip)

**Comment by Templarian** [comment]
Added!
