### ISSUE TITLE
clipboard-text-multiple

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4592]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

If approved, I'll create an outlined version as well

## Preview

![image](https://user-images.githubusercontent.com/55925048/68664682-ff731780-0540-11ea-9ef5-cdf127c16d17.png)

## Zip Download

[clipboard-text-multiple.svg.zip](https://github.com/Templarian/MaterialDesign/files/3835669/clipboard-text-multiple.svg.zip)

**Comment by frankgrinaert** [comment]
@Templarian outlined version:

![image](https://user-images.githubusercontent.com/55925048/69005220-25246600-091f-11ea-87f1-4d8235a8f109.png)

[clipboard-text-multiple-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3855384/clipboard-text-multiple-outline.svg.zip)

**Comment by Templarian** [comment]
Added @frankgrinaert, be sure to reopen next time or things can get lost. I get an insane amount of GitHub notifications so easy to miss closed issues. 😉
