### ISSUE TITLE
archive-down + outline

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4593]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55925048/68711904-eb5c0400-059a-11ea-908b-6cd1e4384710.png)
![image](https://user-images.githubusercontent.com/55925048/68711927-f6af2f80-059a-11ea-9cf1-6a2d1ac9b74f.png)

## Zip Download

[archive-down.zip](https://github.com/Templarian/MaterialDesign/files/3838437/archive-down.zip)

**Comment by Templarian** [comment]
Added.
