### ISSUE TITLE
archive-up + outline

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4594]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55925048/68712022-24947400-059b-11ea-8fde-eb117dcf0fce.png)
![image](https://user-images.githubusercontent.com/55925048/68712055-32e29000-059b-11ea-801f-ffd41e0ca41e.png)

## Zip Download

[archive-up.zip](https://github.com/Templarian/MaterialDesign/files/3838436/archive-up.zip)

**Comment by Templarian** [comment]
Added. I like your submissions they don't require any tweaks (outside of name, `archive-arrow-up`).

🎉

**Comment by frankgrinaert** [comment]
Thanks to your clear guidelines :)

I'd based the naming on `package-up` and `package-down` but agreed the "arrow" versions seem more appropriate here
