### ISSUE TITLE
Battery bar icon

### ISSUE THREAD

**Issue by Prathik-Jain** [Templarian/MaterialDesign#4595]
3 Battery icons with bars - Indicating high/low/medium

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
On embedded devices we look for average battery instead of accurate percentage.

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/25041441/68766293-a4c2e400-0644-11ea-9ce8-597283c452f4.png)

**Comment by goyney** [comment]
We already have many in-between states for battery charge. Why don't those solve your use case?

**Comment by Templarian** [comment]
This might be okay to add as a variant. No reason to add modifiers if these do get added.

- [ ] `battery-level-high`
- [ ] `battery-level-medium`
- [ ] `battery-level-low`

**Comment by Prathik-Jain** [comment]
@goyney, I agree. The level we have currently indicate the battery in terms of percentages and they do solve my use case. But if the options, @Templarian  is suggesting were available; I would prefer them  over percentages.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/68927723-04f17d00-074e-11ea-8c43-bf8a58e093b8.png)

![image](https://user-images.githubusercontent.com/338885/68927880-674a7d80-074e-11ea-8e93-9aeb08787fdd.png)

Making this pixel perfect might be difficult.

**Comment by Prathik-Jain** [comment]
`account` looks better in my opinion

**Comment by Prathik-Jain** [comment]
can we remove the `needs more info` label?

**Comment by goyney** [comment]
[![battery-low](https://materialdesignicons.com/icon/battery-low)](https://materialdesignicons.com/icon/battery-low)[![battery-medium](https://materialdesignicons.com/icon/battery-medium)](https://materialdesignicons.com/icon/battery-medium)[![battery-high](https://materialdesignicons.com/icon/battery-high)](https://materialdesignicons.com/icon/battery-high)

**Comment by goyney** [comment]
[![battery-charging-low](https://materialdesignicons.com/icon/battery-charging-low)](https://materialdesignicons.com/icon/battery-charging-low)[![battery-charging-medium](https://materialdesignicons.com/icon/battery-charging-medium)](https://materialdesignicons.com/icon/battery-charging-medium)[![battery-charging-high](https://materialdesignicons.com/icon/battery-charging-high)](https://materialdesignicons.com/icon/battery-charging-high)
