### ISSUE TITLE
percent-outline

### ISSUE THREAD

**Issue by MCwither** [Templarian/MaterialDesign#4596]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Total sensation `percent` need outline will be better.

## Examples

![percent-outline](https://user-images.githubusercontent.com/47308278/68768957-79e58980-065e-11ea-8750-e92d660feb62.png)

**Comment by Templarian** [comment]
Added.

This was added to the shared contributor account. If you add 4 more icons let us know.
