### ISSUE TITLE
Various icons for the services of a monument

### ISSUE THREAD

**Issue by christian160984** [Templarian/MaterialDesign#46]
- [x] Description: wardrobe. Drawing: hanger
- [x] Description: restaurant. Drawing: knife and fork
- [x] Description: photos without flash. Drawing: camera with flash strikethrough
- [x] Description: food. Drawing: soda and hamburger
- [x] Description: wifi area. Drawing: 3 stripes
- [ ] Description: bathrooms. Drawing: acronym W.C.

**Comment by CoDEmanX** [comment]
There are two access point icons available now:
https://materialdesignicons.com/icon/access-point
https://materialdesignicons.com/icon/access-point-network

For bathrooms, there is
https://materialdesignicons.com/icon/human-male-female

**Comment by CoDEmanX** [comment]
![wc](https://cloud.githubusercontent.com/assets/1309249/11769178/6e8a047a-a1e1-11e5-8209-4f39819c5887.png) https://www.dropbox.com/s/yugvuh973ju7oz7/wc.svg?dl=0

**Comment by PeterShaggyNoble** [comment]
WC won't be added (See [this comment](https://github.com/Templarian/MaterialDesign/issues/475#issuecomment-185044149)) and all other requests in this issue have been fulfilled so closing this out.
