### ISSUE TITLE
Autodesk icons

### ISSUE THREAD

**Issue by SuperDJ** [Templarian/MaterialDesign#4600]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Show icons for different file types of Autodesk.  

## Examples

Include any example images so we know what the icon should look like.

Some sort of combination of the `file-pdf` icon but instead of using the pdf logo use something like the revit
![image](https://user-images.githubusercontent.com/6484766/68849116-c9b16880-06d1-11ea-9e54-94e6f1b2eb55.png) or autocad 
![image](https://user-images.githubusercontent.com/6484766/68849163-d9c94800-06d1-11ea-975e-813bbe12379d.png) logo, with that there are many more like: Civil, fusion, 3ds max, inventor, maya, bim, powermill etc.

**Comment by Templarian** [comment]
Do they have monotone versions of these? With just a single color, if not these will just look like letters.

**Comment by Templarian** [comment]
Closing this out as it doesn't look possible to include these.
