### ISSUE TITLE
square-safe

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#4601]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![square-safe](https://user-images.githubusercontent.com/5179676/68863117-65a19b00-06f7-11ea-82d1-01329f171a8b.png)
## Zip Download
[square-safe.svg.zip](https://github.com/Templarian/MaterialDesign/files/3846787/square-safe.svg.zip)

**Comment by Templarian** [comment]
Added as `safe-square`.

Let me know when you have 5 icons so I can create a contributor account. Until then it's assigned to the shared contributor account. 👍

**Comment by ybandura** [comment]
> Added as `safe-square`.
> 
> Let me know when you have 5 icons so I can create a contributor account. Until then it's assigned to the shared contributor account. 👍

At the moment I have only 3 (with this icon), but I have some ideas 😄 
https://github.com/Templarian/MaterialDesign/issues/4604
https://github.com/Templarian/MaterialDesign/issues/4603

**Comment by Templarian** [comment]
Reopening.

- [ ] Update to `safe-square-outline`
- [ ] Add `safe-square` filled.

**Comment by ybandura** [comment]
> Reopening.
> 
> * [ ]  Update to `safe-square-outline`
> * [ ]  Add `safe-square` filled.

For safe square outline i just should change name of the icon? Or do something else?

**Comment by Templarian** [comment]
@ybandura Don't worry about it. It's just a reminder for me after work so I don't forget. ✅

**Comment by ybandura** [comment]
> @ybandura Don't worry about it. It's just a reminder for me after work so I don't forget.

)) Thanks a lot!

**Comment by ybandura** [comment]
## safe-square filled
![square-safe](https://user-images.githubusercontent.com/5179676/68974627-df21b200-07f9-11ea-98aa-48e9ffc7683c.png)
[square-safe.svg.zip](https://github.com/Templarian/MaterialDesign/files/3853090/square-safe.svg.zip)

**Comment by Templarian** [comment]
Added / reassigned to your contributor account. 👍

**Comment by ybandura** [comment]
> Added / reassigned to your contributor account.

Thanks you very much!!
