### ISSUE TITLE
microsoft office packet icons

### ISSUE THREAD

**Issue by kubatheklamca** [Templarian/MaterialDesign#4602]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@kubatheklamca Can you copy and paste a few images of what ones you're referring to. Also which specific ones need to be added.

**Comment by kubatheklamca** [comment]
I need icon like "file-excel" or "file-spreadsheet" icon from font-awesome library. 
https://fontawesome.com/icons/file-excel?style=solid
https://fontawesome.com/icons/file-spreadsheet?style=solid

**Comment by goyney** [comment]
[![file-excel](https://materialdesignicons.com/icon/file-excel)](https://materialdesignicons.com/icon/file-excel)
[![file-table](https://materialdesignicons.com/icon/file-table)](https://materialdesignicons.com/icon/file-table)

**Comment by kubatheklamca** [comment]
I apologize, I have confused material icons with material design icons, my bad
