### ISSUE TITLE
articles-view

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#4603]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![articles-view](https://user-images.githubusercontent.com/5179676/68922464-5583cd00-0784-11ea-9d21-0130be25dede.png)
## Zip Download
[articles-view.svg.zip](https://github.com/Templarian/MaterialDesign/files/3850126/articles-view.svg.zip)

**Comment by Templarian** [comment]
How about `format-list-text` for this name? `view` is generic and we use that for layout icons (see `view-*`).

**Comment by ybandura** [comment]
> How about `format-list-text` for this name? `view` is generic and we use that for layout icons (see `view-*`).

I do not mind. I will rename the icon a bit later and update the preview) Thank you!

**Comment by Templarian** [comment]
You don't have to do that. We just enter the name in when we paste in the SVG path data. The name you have the file doesn't matter. 👍

**Comment by Templarian** [comment]
Added. 😃
