### ISSUE TITLE
scoreboard

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#4604]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![scoreboard](https://user-images.githubusercontent.com/5179676/68922922-9d572400-0785-11ea-9c04-8743c29c9451.png)

## Zip Download
[scoreboard.svg.zip](https://github.com/Templarian/MaterialDesign/files/3850177/scoreboard.svg.zip)

**Comment by Templarian** [comment]
Assigned the `-outline` and filled to yours.

👍
