### ISSUE TITLE
water-polo

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#4606]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![water-polo](https://user-images.githubusercontent.com/5179676/68931095-7d7d2b80-0798-11ea-8360-0b7173fd07d0.png)

## Zip Download
[water-polo.svg.zip](https://github.com/Templarian/MaterialDesign/files/3850673/water-polo.svg.zip)

**Comment by Templarian** [comment]
Nice design, but for simplicity can you swap it with the `wave`/`waves` icon style waves. The current waves are a little to detailed.

**Comment by ybandura** [comment]
> Nice design, but for simplicity can you swap it with the `wave`/`waves` icon style waves. The current waves are a little to detailed.

Something like this:
![water-polo](https://user-images.githubusercontent.com/5179676/69006791-fddc9180-093c-11ea-9d6d-ddf378e0eccb.png)
[water-polo.svg.zip](https://github.com/Templarian/MaterialDesign/files/3855508/water-polo.svg.zip)

**Comment by Templarian** [comment]
Added! 😃
