### ISSUE TITLE
favorites-document-box-multiple

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#4607]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![favorites-document-box-multiple-outline](https://user-images.githubusercontent.com/5179676/68945815-f3de5580-07b9-11ea-9b09-3db08bbb47ad.png)

![favorites-document-box-multiple](https://user-images.githubusercontent.com/5179676/68946599-107b8d00-07bc-11ea-8f5b-007cae8372ff.png)

## Zip Download

[favorites-document-box-multiple-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/3851591/favorites-document-box-multiple-outline.svg.zip)

[favorites-document-box-multiple.svg.zip](https://github.com/Templarian/MaterialDesign/files/3851637/favorites-document-box-multiple.svg.zip)

**Comment by JamesCoyle** [comment]
Needs properly centering and we also need the non-outline version doing.

**Comment by ybandura** [comment]
> Needs properly centering and we also need the non-outline version doing.

I fixed the centering and add a non-outline as soon as possible

**Comment by JamesCoyle** [comment]
Awesome. We'll leave this issue open and once you add the filled version to this issue and we'll get them both added in one of the next few releases.

**Comment by ybandura** [comment]
> Awesome. We'll leave this issue open and once you add the filled version to this issue and we'll get them both added in one of the next few releases.

Thank you) I just added filled icon

**Comment by Templarian** [comment]
Added! ✅ These utility icons are very helpful. They may seem basic, but every one helps the community. 😃 

The naming makes more sense the longer you look through the pack. https://dev.materialdesignicons.com/contribute/icon-naming

**Comment by Templarian** [comment]
Also, just noticed (and fixed), but make sure all your border radius for boxes are `2dp`. Other than that great work!

**Comment by ybandura** [comment]
> Also, just noticed (and fixed), but make sure all your border radius for boxes are `2dp`. Other than that great work!

Thanks. I will check the radius more carefully for my future icons)
