### ISSUE TITLE
usb-flash-drive

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#4608]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![usb-flash-drive](https://user-images.githubusercontent.com/5179676/68934643-b79dfb80-079f-11ea-893a-89abe3d74812.png)

## Zip Download
[usb-flash-drive.svg.zip](https://github.com/Templarian/MaterialDesign/files/3850929/usb-flash-drive.svg.zip)

**Comment by Templarian** [comment]
Related: #1078 (we'll close 1078 when this gets added).

**Comment by Templarian** [comment]
@ybandura Might just be the preview, but double check the circles hit pixel perfect. Looks like it might be rotated and off the grid slightly.

**Comment by ybandura** [comment]
> @ybandura Might just be the preview, but double check the circles hit pixel perfect. Looks like it might be rotated and off the grid slightly.

Ok. I check it. Thank you

**Comment by Templarian** [comment]
[![usb-flash-drive](https://materialdesignicons.com/icon/usb-flash-drive)](https://materialdesignicons.com/icon/usb-flash-drive)

Ended up fixing it quick. I'll start assigning them over in a little bit.

http://materialdesignicons.com/contributor/Yaroslav-Bandura
