### ISSUE TITLE
database-schema

### ISSUE THREAD

**Issue by vovanenok** [Templarian/MaterialDesign#4609]
## Usage
Used to display relationships among multiple database tables

## Examples
![image](https://user-images.githubusercontent.com/32107800/69001398-8b6fa100-08ab-11ea-961e-bdaeff1ca9ae.png)

**Comment by goyney** [comment]
I think `sitemap` would be the obvious icon to fit this use case. Any boxes smaller than those won't really work.

[![sitemap](https://materialdesignicons.com/icon/sitemap)](https://materialdesignicons.com/icon/sitemap)

**Comment by vovanenok** [comment]
Somehow I missed that icon, exactly what I needed. Thanks, closing this issue
