### ISSUE TITLE
Adjust bar chart icon

### ISSUE THREAD

**Issue by gytdau** [Templarian/MaterialDesign#461]
The bar chart icon seems off.
The fourth bar doesn't look like a bar - it looks like it's part of the graph outline.
I also suggest halving the width of the axis - it looks like another bar.
While yes, if you stare at it for long enough, you'll realize it's a bar chart, but at first glance it doesn't look that way.

The icon, by the way: https://materialdesignicons.com/icon/chart-bar

**Comment by Templarian** [comment]
Let me get some feedback from some others on this issue and get back to you. I see what you're saying, but I can't half the axis bar as that breaks the 2px requirement for system icons.

**Comment by gytdau** [comment]
You could try decreasing the amount of bars and making them wider. There just has to be a distinction between the axis and the bars.

**Comment by Templarian** [comment]
![untitled6](https://cloud.githubusercontent.com/assets/338885/8345316/e1394d3e-1ab2-11e5-8dea-86d89248a28e.png)

Like the above image?

**Comment by Templarian** [comment]
Or...

![untitled6](https://cloud.githubusercontent.com/assets/338885/8345347/3a03e00a-1ab3-11e5-95c9-9668c5f39c7b.png)

**Comment by gytdau** [comment]
The second image looks much better. Good work - you should push/commit that :+1:

**Comment by Templarian** [comment]
I'll switch it out tonight. It will be in the next webfont package. So for now keep using the ugly bar chart and when you update it will be replaced.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/chart-bar I actually updated it last week. Got distracted and forgot to update the issue.
