### ISSUE TITLE
play-box (filled)

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4610]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Strangely missing from the set :)

![image](https://user-images.githubusercontent.com/55925048/69005330-04f5a680-0921-11ea-95cb-ed6f8c67c86b.png)

## Zip Download

[play-box.svg.zip](https://github.com/Templarian/MaterialDesign/files/3855404/play-box.svg.zip)

**Comment by Templarian** [comment]
Good catch. Not sure how we missed this one. 😄 

Added. 👍
