### ISSUE TITLE
usb-flash-drive-filled

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#4611]
Filled version of https://github.com/Templarian/MaterialDesign/issues/4608

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![usb-flash-drive-filled](https://user-images.githubusercontent.com/5179676/69006549-1480e980-0939-11ea-8143-c282c3f7a572.png)

## Zip Download
[usb-flash-drive-filled.svg.zip](https://github.com/Templarian/MaterialDesign/files/3855486/usb-flash-drive-filled.svg.zip)

**Comment by Templarian** [comment]
Added.
