### ISSUE TITLE
Food allergy icons - gluten, lactose, crustaceans. vegan, vegetarian, nut allergies, etc

### ISSUE THREAD

**Issue by theMangledBadger** [Templarian/MaterialDesign#4612]
I have:

- [Y] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [Y] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [Y] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
Online menus; 
RSVP services; 
Guest dietary requirements;

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
A few of these already exist.

- `wheat` / `wheat-off`
- `peanut` / `peanut-off`

Do you have examples of what the others could look like. You can paste images in comments.

**Comment by goyney** [comment]
We'll also have `leaf-off` in #4624 and we recently added `allergy`. Considering this has been stale for a month now and we have even more options, we're going to close this. If you have more specific examples of things that our current offers don't cover, please feel free to comment back.
