### ISSUE TITLE
clipboard-file

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#4613]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

For _Paste_. Not crazy about the filled version, but couldn't find anything better.

## Preview

![image](https://user-images.githubusercontent.com/55925048/69009114-af39f200-0952-11ea-8de9-db11f49c6032.png)

![image](https://user-images.githubusercontent.com/55925048/69009126-cc6ec080-0952-11ea-903b-20020e26d934.png)

## Zip Download

[clipboard-file.zip](https://github.com/Templarian/MaterialDesign/files/3855693/clipboard-file.zip)

**Comment by JamesCoyle** [comment]
The file on the filled version should probably have a cutout and perhaps be filled itself. I'd also play around with the dog ear that our file icons have to try make it look more like a file.

**Comment by Templarian** [comment]
Added to your account. Applied the fix that @JamesCoyle mentioned.
