### ISSUE TITLE
Adsense icon

### ISSUE THREAD

**Issue by gsmxcell** [Templarian/MaterialDesign#4614]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
This is going to be too niche to add at this time as we focus on cutting down on Brand related icons for the 5.0 release.

http://dev.materialdesignicons.com/roadmap/brand-icons
