### ISSUE TITLE
Vacuum cleaner

### ISSUE THREAD

**Issue by PierreClementCazon** [Templarian/MaterialDesign#4618]
Hello,

I couldn't find a classic vacuum icon (there are only icons representing robot vacuum cleaners).

This icon could be useful in various situations such as the representation of scraping for example.

Thank you in advance for your help !

![Capture](https://user-images.githubusercontent.com/36991574/69140178-4a050e80-0ac2-11ea-9666-403fd230f145.PNG)

**Comment by JamesCoyle** [comment]
Duplicate of #2217
