### ISSUE TITLE
phone-classic-off (outline)

### ISSUE THREAD

**Issue by davidplappert** [Templarian/MaterialDesign#4619]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This icon is used to show an unavailable or disabled landline phone. 

## Examples

Similar icons include cellphone-link-off and cellphone-off. This icon would be based on the current phone-classic icon.

**Comment by PeterShaggyNoble** [comment]
Would `phone-off(-outline)` suit your needs?

**Comment by davidplappert** [comment]
> Would `phone-off(-outline)` suit your needs?

They would not. I am building a phone system and need to designate the different types of phones (land line, cellphone, and softphone (web). Thank you for asking.

**Comment by Templarian** [comment]
Added.

**Comment by davidplappert** [comment]
less than 24-hour response time? This is excellent! Thank you!
