### ISSUE TITLE
Solar Angle

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4621]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As per title, need a solar angle icon, accompanying the just posted solar azimuth.

## Examples

Hope eg the regular mdi:angle-acute could be combined with the small sun of the mdi:solar-power to have the angle and sun in 1 icon ?

thanks for considering!

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/136132810-afd85579-a3ef-400a-877d-acfabc738080.png)![image](https://user-images.githubusercontent.com/1015040/136132834-e23a5f9f-16d5-4cc9-9737-012e8c8980b2.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7290503/Archive.zip)

**Comment by goyney** [comment]
Not sure which one of those makes more sense, but the one without the angle measurement line seems less busy maybe?

**Comment by Mariusthvdb** [comment]
Hey Michael,

Since these were never released, I added them to my tiny [Custom icons](https://github.com/Mariusthvdb/Custom-icons) plugin repo, and before formally creating a next 'release' containing them, would kindly ask your permission to do so.
Of course I have full credited you and linked to Material design here.

thanks!

**Comment by goyney** [comment]
[![sun-angle](https://materialdesignicons.com/icon/sun-angle)](https://materialdesignicons.com/icon/sun-angle)[![sun-angle-outline](https://materialdesignicons.com/icon/sun-angle-outline)](https://materialdesignicons.com/icon/sun-angle-outline)
