### ISSUE TITLE
selection-markers

### ISSUE THREAD

**Issue by mikesmichael** [Templarian/MaterialDesign#4622]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Select multiple markers

## Examples

Name:
selection-markers
![image](https://user-images.githubusercontent.com/9534827/69270780-a559fe00-0ba1-11ea-83a0-644cedddda5c.png)

[selection-markers.zip](https://github.com/Templarian/MaterialDesign/files/3871027/selection-markers.zip)

**Comment by Templarian** [comment]
Added `selection-marker` and `select-marker`. We don't really add `-multiple` overlays as it's too much detail.

**Comment by Templarian** [comment]
Would `selection-marker-multiple` work where the selection was a `multiple` work?

**Comment by mikesmichael** [comment]
You are right, `selection` include `multiple` so no need to use `multiple`.

**Comment by Templarian** [comment]
Added `select-multiple-marker` and `selection-multiple-marker`.
