### ISSUE TITLE
Vegetarian and Non vegetarian

### ISSUE THREAD

**Issue by piyushgupta9450** [Templarian/MaterialDesign#4624]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
Do you have examples of what this could look like? Images can be pasted by editing your original issue.

`leaf` or `leaf-off`? A `chicken` etc? If you have images from menus that might help the team think of an idea to represent this.

**Comment by Templarian** [comment]
@piyushgupta9450 ^

**Comment by JapanYoshi** [comment]
I'm in full agreement with Templarian. I guess we could also benefit from a ``leaf-off`` icon though.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71008159-2c719780-20b6-11ea-8734-5d4287cb9747.png)
![image](https://user-images.githubusercontent.com/1015040/71008181-3398a580-20b6-11ea-8a4f-6516ded1a035.png)

In both anti-leaf and anti-Canada flavors. 😝 

[leaf-off.zip](https://github.com/Templarian/MaterialDesign/files/3973994/leaf-off.zip)

**Comment by goyney** [comment]
[![leaf-off](https://materialdesignicons.com/icon/leaf-off)](https://materialdesignicons.com/icon/leaf-off)[![leaf-maple-off](https://materialdesignicons.com/icon/leaf-maple-off)](https://materialdesignicons.com/icon/leaf-maple-off)
