### ISSUE TITLE
Clothes sizes

### ISSUE THREAD

**Issue by Aura-Mancer** [Templarian/MaterialDesign#4626]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

These could be really useful, for indicating sizes available and/or selecting the one you are looking for in a shopping app.

## Examples

![imagen](https://user-images.githubusercontent.com/57840599/69368110-c43bbb80-0c99-11ea-9948-8f9917a90dda.png)

![imagen](https://user-images.githubusercontent.com/57840599/69368402-5fcd2c00-0c9a-11ea-8e53-551b904cfa90.png)

Also an icon for depecting clothes sizes **in general** could look like this:

![imagen](https://user-images.githubusercontent.com/57840599/69368302-2a284300-0c9a-11ea-91ff-5da497994312.png)
![imagen](https://user-images.githubusercontent.com/57840599/69368357-46c47b00-0c9a-11ea-903d-6ae21d7eeea9.png)

PS: I would also add an icon for Extra short clothes i.e XS

Thanks!

**Comment by Templarian** [comment]
All of these should be possible just one note for `xxxl` to work we should have to make it something like:

![image](https://user-images.githubusercontent.com/338885/69469352-f6aaee80-0d55-11ea-847a-ad39a61e764e.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/69469623-72596b00-0d57-11ea-8410-827a4558f591.png)

Not a huge fan of just shrinking down our shirt with the "lopsided" ruler measurements. Might want to do a diagonal cut out.

(designing out loud for others to see).

**Comment by SrWindings** [comment]
> 
> 
> All of these should be possible just one note for `xxxl` to work we should have to make it something like:
> 
> ![image](https://user-images.githubusercontent.com/338885/69469352-f6aaee80-0d55-11ea-847a-ad39a61e764e.png)

Yeah, that works perfectly. 



> 
> 
> ![image](https://user-images.githubusercontent.com/338885/69469623-72596b00-0d57-11ea-8410-827a4558f591.png)
> 
> Not a huge fan of just shrinking down our shirt with the "lopsided" ruler measurements. Might want to do a diagonal cut out.
> 
> (designing out loud for others to see).

Do you mean orienting a ruler diagonally across the shirt?

**Comment by JapanYoshi** [comment]
What about system that use LL (2L), LLL (3L), etc.?

**Comment by goyney** [comment]
There is a clear language conflict here because sizes are not global. I think we are more likely to add that ruler variant than individual sizes. Why use an icon to represent a size when you can use (a) text or (b) our alphabet?

**Comment by Templarian** [comment]
Kind of fine with the language conflict as these will mostly be used in context with the items being sold.

While each means something different most countries still use this naming style.

**Comment by Templarian** [comment]
Added these as generic `size-*` icons. Still not sure about the other variations above.

**Comment by JapanYoshi** [comment]
I am very opposed to the addition of text based icons. I mean, look how ~~stupid~~ redundant that would look:
![redundant](https://user-images.githubusercontent.com/8707990/75337988-bcfbfd80-58d9-11ea-80df-6c0406cff068.png)

**Comment by Aura-Mancer** [comment]
Since these have been added, I think it's fitting to close this issue.
