### ISSUE TITLE
icons for amplifier sources

### ISSUE THREAD

**Issue by gericho** [Templarian/MaterialDesign#4628]
If I may, it wil be useful to have amplifier source icons like toslink optical digital ecc..
## Usage
Home asistant HIFI amplifier source control with a generic infrared emitter like the broadlink and so on

## Examples
toslink
https://icons8.it/icon/90424/toslink

digital binary input, maybe with a arrow somewhere
https://www.flaticon.com/premium-icon/binary-code_967592

or for eg a square wave
https://stockfresh.com/image/6355497/voice-waves-icons-on-white-background

RCA input already present
HDMI already present
other useful icon already present, thanx!!

**Comment by goyney** [comment]
Added `toslink`:

Binary is a dupe of #4615 
[![toslink](https://materialdesignicons.com/icon/toslink)](https://materialdesignicons.com/icon/toslink)

Square wave (and others) is a dupe of #4346.
