### ISSUE TITLE
inbox-full

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4630]
## Request

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![inbox-full](https://user-images.githubusercontent.com/4528551/69452522-1bd03a80-0d1f-11ea-8431-818593ab30a6.png)

## Zip Download

[inbox-full.zip](https://github.com/Templarian/MaterialDesign/files/3880971/inbox-full.zip)

**Comment by Templarian** [comment]
Can you make the lines not 1dp, this is a little too narrow.

**Comment by Templarian** [comment]
Added (modified a little).
