### ISSUE TITLE
inbox(-arrow-up|-arrow-down)-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4632]
# Request

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![inbox-outline](https://user-images.githubusercontent.com/4528551/69460424-5fcc3b00-0d31-11ea-80ce-89c4aea83006.png) ![inbox-arrow-up-outline](https://user-images.githubusercontent.com/4528551/69460357-2b587f00-0d31-11ea-80e8-9738f63f5cb2.png) ![inbox-arrow-down-outline](https://user-images.githubusercontent.com/4528551/69460382-40cda900-0d31-11ea-847d-abd25651d87a.png)

## Zip Download

[inbox-outline.zip](https://github.com/Templarian/MaterialDesign/files/3881444/inbox-outline.zip)

**Comment by Templarian** [comment]
Added. Also added the other `-full` one.
