### ISSUE TITLE
tray(-full|-plus|-minus|-remove|-alert)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4633]
# Request

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![tray](https://user-images.githubusercontent.com/4528551/69460835-50012680-0d32-11ea-92e8-235e3ee2b4ca.png) ![tray-full](https://user-images.githubusercontent.com/4528551/69460858-5d1e1580-0d32-11ea-9547-40ee1be2d812.png) ![tray-plus](https://user-images.githubusercontent.com/4528551/69460875-6909d780-0d32-11ea-830d-ebdf1b15dcd7.png) ![tray-minus](https://user-images.githubusercontent.com/4528551/69460912-7c1ca780-0d32-11ea-8608-787d0c011f33.png) ![tray-remove](https://user-images.githubusercontent.com/4528551/69460933-88a10000-0d32-11ea-9b42-4e9afd5ff354.png) ![tray-alert](https://user-images.githubusercontent.com/4528551/69460953-948cc200-0d32-11ea-9994-1f80e4bea3b8.png)

## Zip Download

[tray.zip](https://github.com/Templarian/MaterialDesign/files/3881472/tray.zip)

**Comment by Templarian** [comment]
Added.
