### ISSUE TITLE
Bookshelf

### ISSUE THREAD

**Issue by St-Ex** [Templarian/MaterialDesign#4634]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon (Closed one #593).
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

[![bookshelf](https://user-images.githubusercontent.com/2870576/69564323-1be86880-0fb3-11ea-8e10-7ee2409dac9c.png)](https://github.com/Templarian/MaterialDesign/files/3887892/bookshelf.zip)

## Zip Download

[bookshelf.zip](https://github.com/Templarian/MaterialDesign/files/3887892/bookshelf.zip)

**Comment by Templarian** [comment]
@St-Ex Align the left book to the grid, and remove the round edges. Might need to shrink it by `1dp` as proportionally it's taking up a lot of space. 👍

**Comment by St-Ex** [comment]
Simplified the path to the bare minimum with perfect pixel angle.
[![bookshelf](https://user-images.githubusercontent.com/2870576/69581154-51527d80-0fd6-11ea-9387-d87bd8d7de87.png)](https://github.com/Templarian/MaterialDesign/files/3888921/bookshelf.zip)

```svg
<svg width="24" height="24" enable-background="new 0 0 24.00 24.00" version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
 <path d="m9 3v15h3v-13-2h-3zm3 2 4 13 3-1-4-13-3 1zm-7 0v13h3v-13h-3zm-2 14v2h18v-2h-18z"/>
</svg>
```

**Comment by Templarian** [comment]
Nice! For future reference scan over https://material.io/design/iconography/system-icons.html and it will give you a solid background on why these changes are requested. Their overview of proportions does a great job of explaining consistent sizing. 👍

**Comment by St-Ex** [comment]
Thanks for pointing it. I was using a lot of mdiBook* lately and I was underimpresion of needing exterior round corners.

**Comment by Templarian** [comment]
Yeah, it gets a little confusing also since the official set has a "rounded" variant. But we don't support that as it's outside of the scope of this project at the moment (just regular/outline).

**Comment by Templarian** [comment]
Added. You'll see these display under your github/name on the site as their added.
