### ISSUE TITLE
Skin/Theme

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4635]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Not sure what's recommended to show "skin" or "theme".

**Comment by JamesCoyle** [comment]
These could work in context: 
[![](https://materialdesignicons.com/icon/palette)](https://materialdesignicons.com/icon/palette)[![](https://materialdesignicons.com/icon/palette-advanced)](https://materialdesignicons.com/icon/palette-advanced)

I don't really think we have anything better.

**Comment by MrGrigri** [comment]
Angular Material uses `format-color-fill` with `color-helper` underneath (Figure A). And Google Fonts uses the same but changes the underline color (Figure B).

![image](https://user-images.githubusercontent.com/4528551/69753477-efe2f980-1110-11ea-866e-c2efcd956bda.png)
![image](https://user-images.githubusercontent.com/4528551/69753494-f83b3480-1110-11ea-9924-3c9fc789ae62.png)

**Comment by goyney** [comment]
Looks like we have several options for this already, so we're going to close it. If you come up with some other ideas, post them back here for reconsideration. Thanks for the suggestion.
