### ISSUE TITLE
Pixel Resolution; Mosaic

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4636]
## Preview
![image](https://user-images.githubusercontent.com/8707990/69620123-2b81b300-1080-11ea-9801-fda5b30e4c42.png)

```M 5 3 C 3.892 3 3 3.892 3 5 L 3 19 C 3 20.108 3.892 21 5 21 L 19 21 C 20.108 21 21 20.108 21 19 L 21 5 C 21 3.892 20.108 3 19 3 L 5 3 z M 12 11 L 13 11 L 13 13 L 15 13 L 15 15 L 17 15 L 17 17 L 19 17 L 19 19 L 5 19 L 12 11 z```

**Comment by Templarian** [comment]
@JapanYoshi What's the context for this? Like what is such an icon used for?

**Comment by JapanYoshi** [comment]
For graphics quality, or to show the pixel resolution of an image.

**Comment by goyney** [comment]
I don't think this icon works at native resolution.

For graphics quality, wouldn't things like `quality-(high|medium|low)` work? And then something like `checkerboard` or even `square-opacity`/`circle-opacity` for resolution. Used in the right context, I think any of those would be fine.
