### ISSUE TITLE
battery-off(-outline)

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#4638]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to enhance an existing app, so it can sent the battery state to a server. If this feature is turned on, a battery outline icon is shown in the settings. If it's turned off, a battery-outline-off icon should be shown.

## Examples

The battery-outline icon with the "-off" modifier.

**Comment by MrGrigri** [comment]
![battery-off](https://user-images.githubusercontent.com/4528551/69753219-469c0380-1110-11ea-9dd7-347aa20a71a0.png) ![battery-off-outline](https://user-images.githubusercontent.com/4528551/69753248-5b789700-1110-11ea-895c-379f73f8a47c.png)

---

[battery-off.zip](https://github.com/Templarian/MaterialDesign/files/3898486/battery-off.zip)

**Comment by mueller-ma** [comment]
Nice!

**Comment by Templarian** [comment]
@MrGrigri cut a 1dp off the left line. Other than that looks good to add.

**Comment by MrGrigri** [comment]
Do you want me to add these to now to 4.7.95?

![battery-off](https://user-images.githubusercontent.com/4528551/69754923-53baf180-1114-11ea-8dc7-f00334a510c2.png) ![battery-off-outline](https://user-images.githubusercontent.com/4528551/69754928-56b5e200-1114-11ea-9ee2-0f758de6a692.png)

---

[battery-off.zip](https://github.com/Templarian/MaterialDesign/files/3898576/battery-off.zip)

**Comment by Templarian** [comment]
You can add icons at any time. They don't get synced to the repo until they are assigned a codepoint which you can do also. Need to start assigning codepoint as we're only like 30 icons away from that release.

**Comment by MrGrigri** [comment]
Added.
