### ISSUE TITLE
lan-check

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4639]
##  Request

I have been using this in a project and forgot to add it here.

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![lan-check](https://user-images.githubusercontent.com/4528551/69746923-9e337280-1102-11ea-9998-4ee9eedf3dd1.png)

## Zip Download

[lan-check.zip](https://github.com/Templarian/MaterialDesign/files/3898156/lan-check.zip)

**Comment by goyney** [comment]
[![lan-check](https://materialdesignicons.com/icon/lan-check)](https://materialdesignicons.com/icon/lan-check)
