### ISSUE TITLE
Crown icon

### ISSUE THREAD

**Issue by QuadFlask** [Templarian/MaterialDesign#464]
like this

![https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRYadpqGjMdMb4z6m-DLxiJLct0_10aWAlq-E8GzI0s1vJ8uBsh](https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRYadpqGjMdMb4z6m-DLxiJLct0_10aWAlq-E8GzI0s1vJ8uBsh)

or, is there already exist?

**Comment by Templarian** [comment]
I don't think it exists yet.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/crown Is this too minimal?

**Comment by QuadFlask** [comment]
@Templarian  Oh, good icon! but this is little old fashioned i think, narrowed bottom side may look good. it just my opinion, thanks all!

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/crown Updated.

Let me know I'll keep modifying it.

**Comment by QuadFlask** [comment]
@Templarian  Wow, swift feedback! I love your icons. Thanks!

**Comment by Templarian** [comment]
I'll take that as a it looks good. :smile: 

Feel free to suggest more in the future as you need them.
