### ISSUE TITLE
Multimedia icon

### ISSUE THREAD

**Issue by kdw2060** [Templarian/MaterialDesign#4640]
An icon that can be used to describe a collection of audio, video, picture resources.
I found individual icons for audio and video in the current icon set but none for a collection of materials.

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As an interface element pointing to a collection of audio, video, etc. files. Or to an application that can be used to view/play said files.

## Examples

https://thenounproject.com/term/multimedia/1317447/
https://thenounproject.com/search/?q=multimedia&i=2826888

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73571162-469ce480-446e-11ea-8e37-f5ee620543a1.png)

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73591071-47735c00-44ea-11ea-9671-07a03ba0d496.png)

**Comment by CoDEmanX** [comment]
There is just too much going on and the strokes at 1dp lead to too fine details. There might be some clever way to do 2dp strokes by overlapping the elements cleverly...

**Comment by goyney** [comment]
These suggestions suffer from the same problem as #4351. Simply throwing a bunch of small icons together to make up another icon isn't a good solution.

**Comment by goyney** [comment]
Another shot at this, still really busy.

![image](https://user-images.githubusercontent.com/1015040/137418223-9b293838-4361-4a70-9b28-cdeca27860ab.png)

[multimedia.svg.zip](https://github.com/Templarian/MaterialDesign/files/7350242/multimedia.svg.zip)

**Comment by endiemen-ao** [comment]
![ag-multimedia](https://user-images.githubusercontent.com/107536590/175336633-b717bf57-bc9b-4a30-9254-4c7ad6e333c2.png)

**Comment by goyney** [comment]
[![multimedia](https://materialdesignicons.com/icon/multimedia)](https://materialdesignicons.com/icon/multimedia)
