### ISSUE TITLE
thermometer-snowflake

### ISSUE THREAD

**Issue by eopo** [Templarian/MaterialDesign#4642]
I have:

- [ x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A thermometer with a snowflake beneath it. It could be used to show that a temperature is not only low, but very low, without indicating that it this would be critical with temperature-alert

## Examples

Something like this, but I'd prefer the snowflake on the right to be consistent with the other thermometer icons: https://www.iconfinder.com/icons/4243450/cold_weather_frost_low_temperature_snowflake_icon

**Comment by goyney** [comment]
We have `thermometer-alert` and `snowflake-alert`. Would either of these not work? It's going to be rather hard to create this without it looking like a thermometer with an asterisk next to it.

[![thermometer-alert](https://materialdesignicons.com/icon/thermometer-alert)](https://materialdesignicons.com/icon/thermometer-alert)[![snowflake-alert](https://materialdesignicons.com/icon/snowflake-alert)](https://materialdesignicons.com/icon/snowflake-alert)

**Comment by goyney** [comment]
Closing due to no response in over two weeks. We have two potential icons that fit this use case. Please comment back here if you have further suggestions around the original request.
