### ISSUE TITLE
Update libraries

### ISSUE THREAD

**Issue by guidotraversaro** [Templarian/MaterialDesign#4643]
Hi there, I'm currently working with the library and sometimes I found out that a specific icon is not currently on the library but is displayed on the list. I'm using the react one and these are the versions found on package.json:
` "@mdi/js": "3.9.97",
    "@mdi/react": "1.2.1",`

Can you please update the libraries to the last ones on all platforms?

Thank you in advance and sorry for the writing, english is my second language

**Comment by goyney** [comment]
`@mdi/react` is just a utility library and you're on the latest version, so nothing needs to happen there.

However, you are an extremely old version of `@mdi/js`. We're currently on `4.6.95`. You will need to update that to get all the latest icons.

If you are using some other libraries that incorporate our icon packages, you will need to ask them to update. There's nothing for us to do here.
