### ISSUE TITLE
mobile payment

### ISSUE THREAD

**Issue by intervia** [Templarian/MaterialDesign#4644]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To pay using a mobile somehow. In my particular case to initiate a payment by SMS.

## Examples

![aami7-82-512](https://user-images.githubusercontent.com/13640952/70019543-e67ee480-1589-11ea-9eba-276b56392c3e.png)
![Mobile_Payment_Pay_Shopping_Finance_NFC_Smartphone_Phone_Buy-512](https://user-images.githubusercontent.com/13640952/70019545-e67ee480-1589-11ea-8ffa-fa186e9833c6.png)
![phone__credit_card-512](https://user-images.githubusercontent.com/13640952/70019547-e67ee480-1589-11ea-96db-5efa7a483096.png)

**Comment by FANMixco** [comment]
> I have:
> 
> * [ ]  [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
> * [ ]  [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
> * [ ]  Only requested a single icon (or a few near-identical ones) in this issue.
> 
> ## Usage
> To pay using a mobile somehow. In my particular case to initiate a payment by SMS.
> 
> ## Examples
> ![aami7-82-512](https://user-images.githubusercontent.com/13640952/70019543-e67ee480-1589-11ea-9eba-276b56392c3e.png)
> ![Mobile_Payment_Pay_Shopping_Finance_NFC_Smartphone_Phone_Buy-512](https://user-images.githubusercontent.com/13640952/70019545-e67ee480-1589-11ea-8ffa-fa186e9833c6.png)
> ![phone__credit_card-512](https://user-images.githubusercontent.com/13640952/70019547-e67ee480-1589-11ea-96db-5efa7a483096.png)

I highly doubt it will be added because it has a dollar sign. I tried to promote a similar idea before and if it has any currency symbol is going to be rejected most probably.

**Comment by intervia** [comment]
The last example does not have the dollar symbol, in fact if there was a symbol I would prefer the euro, but a credit card is ok.

**Comment by goyney** [comment]
We have several icons that already meet this use case:

[![credit-card-wireless](https://materialdesignicons.com/icon/credit-card-wireless)](https://materialdesignicons.com/icon/credit-card-wireless)
[![cellphone-nfc](https://materialdesignicons.com/icon/cellphone-nfc)](https://materialdesignicons.com/icon/cellphone-nfc)
[![nfc](https://materialdesignicons.com/icon/nfc)](https://materialdesignicons.com/icon/nfc)

As @FANMixco said, we won't add any new icons with a specific currency marker. I also believe combining a credit card and a cellphone is too much for the 24dp area we have to work with.

**Comment by intervia** [comment]
A wave does not represent a payment :(
NFC can be used to pay, but it is not a payment method.

**Comment by intervia** [comment]
![cellphone-payment](https://user-images.githubusercontent.com/13640952/70169432-1681d100-16cb-11ea-8031-da884f93d4f0.png)

**Comment by PeterShaggyNoble** [comment]
We also have `contactless-payment`:

![contactless-payment](https://user-images.githubusercontent.com/15157491/70189723-f31b4e00-16eb-11ea-8dcf-659a631bdf93.png)

**Comment by intervia** [comment]
That symbol means "contactless" and can only be related to "payment" because it is printed inside a credit card, if you take it out of the card the concept of payment is lost. To me it seems unusable to indicate a payment.

**Comment by goyney** [comment]
And yet, that is what the industry has standardized on. Additionally, icons are meant to be contextual and supplemental to the surrounding content. Any of those icons used in the proper context would clearly indicate a mobile payment.

**Comment by intervia** [comment]
I asked my wife what the icon looked like and she said wi-fi.

That is a standard for contactless, not for payments, even in context it is not clear, I use NFC access cards that have that icon and are not to pay anything.

In my case the icon is to ask for a payment link to receive on a mobile and that does not represent it by any means. No problem, I understand that my request is not of general interest to this project.

Thank you for your interest and for sharing your work.

**Comment by FANMixco** [comment]
> I asked my wife what the icon looked like and she said wi-fi.
> 
> That is a standard for contactless, not for payments, even in context it is not clear, I use NFC access cards that have that icon and are not to pay anything.
> 
> In my case the icon is to ask for a payment link to receive on a mobile and that does not represent it by any means. No problem, I understand that my request is not of general interest to this project.
> 
> Thank you for your interest and for sharing your work.

You're not the only one with the same concern, personally, I see it only as a NFC symbol and I'm from IT, if I'd have seen it without any description, I hadn't guessed it. Even if it's a standard.

**Comment by goyney** [comment]
We're going to close this issue because we have many options for indicating mobile pay, several of which incorporate the standardized symbols for doing so.
