### ISSUE TITLE
cellphone-nfc-off

### ISSUE THREAD

**Issue by xabi62** [Templarian/MaterialDesign#4645]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to use this cellphone-nfc-off icon to see if my ESPs are online or not.
I did it with wifi and wifi-off icons but it does not distinguish between esp and other equipment.

## Examples

the cellphone-nfc icon crossed out as for the wifi-off icon

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71007721-7b6afd00-20b5-11ea-9f4b-a5ad670547a0.png)
[cellphone-nfc-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/3973962/cellphone-nfc-off.svg.zip)

**Comment by goyney** [comment]
[![cellphone-nfc-off](https://materialdesignicons.com/icon/cellphone-nfc-off)](https://materialdesignicons.com/icon/cellphone-nfc-off)
