### ISSUE TITLE
speech-help or voice-help

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4646]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

I would need an icon to set a page and commands for speech assist aliases, so the user can click it and find a list of voice commands to issue.
I can right now use the generic mdi:help, or some of the voice / speech icons, but would really appreciate a voice / speech icon with a help question mark in the upper right corner if possible. This would help distinguish it from the other help subjects and assistants/weblinks in use.

Thanks for considering!
cheers.

**Comment by goyney** [comment]
[![microphone-question](https://materialdesignicons.com/icon/microphone-question)](https://materialdesignicons.com/icon/microphone-question)[![microphone-question-outline](https://materialdesignicons.com/icon/microphone-question-outline)](https://materialdesignicons.com/icon/microphone-question-outline)
