### ISSUE TITLE
whistle-outline

### ISSUE THREAD

**Issue by julienreszka** [Templarian/MaterialDesign#4647]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
Like whistle but outlined

## Examples

Include any example images so we know what the icon should look like.

**Comment by MrGrigri** [comment]
![whistle-outline](https://user-images.githubusercontent.com/4528551/70158948-5c13af00-1675-11ea-9df8-9f54ccaf6812.png)

---

[whistle-outline.zip](https://github.com/Templarian/MaterialDesign/files/3922805/whistle-outline.zip)

**Comment by Templarian** [comment]
Added.
