### ISSUE TITLE
Invite Friends icon

### ISSUE THREAD

**Issue by fractalbob** [Templarian/MaterialDesign#4648]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by fractalbob** [comment]
Could resemble the Facebook "Invite Friends" icon or something generic.

**Comment by PeterShaggyNoble** [comment]
Would `account(-multiple)-plus(-outline)` suit your needs?

**Comment by fractalbob** [comment]
Yes! I missed that! Thanks, Peter!

**Comment by MrGrigri** [comment]
Alias 'invite' has been added to

- `account-plus`
- `account-plus-outline`
- `account-multiple-plus`
- `account-multiple-plus-outline`

**Comment by fractalbob** [comment]
Good idea! Thanks!
