### ISSUE TITLE
Icon not showing at all.

### ISSUE THREAD

**Issue by alucardu** [Templarian/MaterialDesign#4649]
I've added `"@mdi/font": "^4.6.95",` to my package.json and in my app, the mdi folder is added to my node_modules folder. I want to add a icon like this: `<span class="mdi mdi-whatsapp"></span>` when I load the page, no icon is shown. Am I missing a step somewhere?

**Comment by Templarian** [comment]
Open your dev console and double check it's actually downloading the webfont files (most browsers will load the `.woff2` front file).
