### ISSUE TITLE
Where Have gray icons?

### ISSUE THREAD

**Issue by RadiationX** [Templarian/MaterialDesign#465]
The desired gray icons, where to get them?
P.S. on https://materialdesignicons.com

**Comment by Templarian** [comment]
They were removed from the package yesterday as I get close to fully implementing #371.

Sorry about that. I reenabled it to include grey600 (although Google also removed it from their settings as they want everyone using black at I think 0.6 opacity).

**Comment by RadiationX** [comment]
Many thanks!

**Comment by Templarian** [comment]
Hey @RadiationX I'm not really a Android developer, so quick question. Do people need the grey icons. I ask since google doesn't offer a download options.

Also would it be more useful to have 2 quick buttons for black/white rather than one download containing both?

**Comment by RadiationX** [comment]
If I understand the question then yes. (Google Translate).
It would be very convenient to download the icons in three colors separately.
And it would be convenient at the same time be able to choose only one size, for example, only 24dp.

**Comment by Templarian** [comment]
The option to download just a single `dp` is coming also. That has been highly requested by users.

Thanks!
