### ISSUE TITLE
MaxCDN is now StackPath

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4650]
MaxCDN has [changed its name to StackPath](https://www.stackpath.com/maxcdn/) and, with that, comes [a new icon](https://www.stackpath.com/company/logo-and-branding/), which we'll need to replace our existing `maxcdn` icon with. After discussing it internally: as this is not a deprecation but, rather, a rebranding and as StackPath are a sponsor of this project, we'll need to roll this breaking change out in `v4.8` instead of waiting until `v5` so people can start using the correct icon as soon as possible. While the name of the icon will be changing, it will be retaining the same codepoint as `maxcdn`.

[![stackpath](https://user-images.githubusercontent.com/15157491/70318346-ba789300-1817-11ea-868b-016c751c69c4.png)](https://github.com/Templarian/MaterialDesign/files/3931827/stackpath.zip)

**Comment by Templarian** [comment]
Seeing at `4.7.95` is released I'm going to update this one now. ✅
