### ISSUE TITLE
Outline cloud icons

### ISSUE THREAD

**Issue by ocavue** [Templarian/MaterialDesign#4652]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want *outline* versions of two existed icons. These icons can fill well with other outline icons in this project.

1. cloud-check (Google already has the [outline version](https://material.io/resources/icons/?search=clou&icon=cloud_done&style=outline) of this icon)
2. cloud-sync

## Examples

Since the filled versions of these icons exist, I think no examples are needed.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/70445550-b0e66980-1a69-11ea-9ac8-228b6c2fa9f0.png)![image](https://user-images.githubusercontent.com/1015040/70445567-b8a60e00-1a69-11ea-83b9-76232efcafa3.png)

[cloud-sync-check.zip](https://github.com/Templarian/MaterialDesign/files/3940239/cloud-sync-check.zip)

**Comment by Templarian** [comment]
Wondering if we should update the `cloud-sync` to the corner like all the other overlays?

**Comment by ocavue** [comment]
I'm ok with both corner and center. However, if we update the `cloud-sync` to the corner, I think we should also update some other `cloud-*` icons to the corner. 

For example, an App could switch its icon from `cloud`, `cloud-sync`, `cloud-download` and `cloud-upload` to represent different state (doing nothing, checking new content from server, downloading something, uploading something). When switching state, the different part of these icons should be the same position, which keep the UI consistency.

**Comment by goyney** [comment]
Added `cloud-check-outline`.

I think I'm in agreement with @Templarian about moving the `sync` arrows. Here is what those would look like:

![image](https://user-images.githubusercontent.com/1015040/71012494-3d71d700-20bd-11ea-990e-b452a327f8c9.png)
![image](https://user-images.githubusercontent.com/1015040/71012525-4498e500-20bd-11ea-9eda-6a8b209d96a8.png)

[cloud-sync.zip](https://github.com/Templarian/MaterialDesign/files/3974249/cloud-sync.zip)

**Comment by Templarian** [comment]
Yeah, corner looks nicer and more consistent for `sync`. 👍

**Comment by goyney** [comment]
[![cloud-sync](https://materialdesignicons.com/icon/cloud-sync)](https://materialdesignicons.com/icon/cloud-sync)[![cloud-sync-outline](https://materialdesignicons.com/icon/cloud-sync-outline)](https://materialdesignicons.com/icon/cloud-sync-outline)
