### ISSUE TITLE
Double Garage Door Open/Close

### ISSUE THREAD

**Issue by rayzorben** [Templarian/MaterialDesign#4654]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

Request exists bundled in with others that has been open for a while https://github.com/Templarian/MaterialDesign/issues/1826

## Usage

Home automation.

## Examples

Include any example images so we know what the icon should look like.

Just the stock garage and garage-open ones , just wider. Possibly with a line down the middle to represent 2 doors?

**Comment by goyney** [comment]
I can see us making a wider variant for typical two-car garages. However, if you want to represent single doors, our `garage` is more than sufficient.

Adding these as potential additions:
![image](https://user-images.githubusercontent.com/1015040/70447442-b3968e00-1a6c-11ea-9213-9ed5df58123b.png)
![image](https://user-images.githubusercontent.com/1015040/70447456-babd9c00-1a6c-11ea-84c2-a2334eff1634.png)
![image](https://user-images.githubusercontent.com/1015040/70447474-c27d4080-1a6c-11ea-8f9b-33cffde4ee51.png)

[garage-variant.zip](https://github.com/Templarian/MaterialDesign/files/3940324/garage-variant.zip)

**Comment by rayzorben** [comment]
Works for me, I am aware of garage and garage-open and am using them, but the wider one would be great for my home automation.

**Comment by rayzorben** [comment]
The only issue some people might not like is that on alert the garage is shifted over. Personally I don't use alert, but that might cause issues for some.

**Comment by goyney** [comment]
`garage-alert` is also shifted, it's a common occurrence with the `alert` modifier.

**Comment by rayzorben** [comment]
OK then I am good!

**Comment by goyney** [comment]
Removing Consider Closing as I'm not sure why it was added. I believe this is a good variant. (I mean, I plan on using it. 😝)

**Comment by goyney** [comment]
[![garage-variant](https://materialdesignicons.com/icon/garage-variant)](https://materialdesignicons.com/icon/garage-variant)[![garage-open-variant](https://materialdesignicons.com/icon/garage-open-variant)](https://materialdesignicons.com/icon/garage-open-variant)[![garage-alert-variant](https://materialdesignicons.com/icon/garage-alert-variant)](https://materialdesignicons.com/icon/garage-alert-variant)
