### ISSUE TITLE
Bulk or multiple upload

### ISSUE THREAD

**Issue by SokolSM** [Templarian/MaterialDesign#4655]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Bulk or multiple upload:
1) files
2) list items

The idea of plurality

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@SokolSM Please fill out the icon issue template (edited it back in above). Do you have example of what these might look like? You can edit the issue and paste images.

**Comment by MrGrigri** [comment]
We already have a `upload-multiple` icon.

![upload-multiple](https://materialdesignicons.com/icon/upload-multiple)

**Comment by goyney** [comment]
As pointed out by @MrGrigri, we already have this. If there is something more specific you are looking for, please comment back here. For now, we're going to close this.
