### ISSUE TITLE
Newspaper - show the fold similar to FontAwesome icon

### ISSUE THREAD

**Issue by jasonbunnell** [Templarian/MaterialDesign#4656]
The newspaper icon looks more like a spiral calendar than newspaper to me.  Think it would look better if it looked like a folded piece of newspaper with the fold at the bottom.  Seems more iconic of a newspaper to me.

**Comment by goyney** [comment]
We've discussed this in the past and won't do it, mainly because of this MD guideline:

> Don’t.
> 
> Don’t tilt, rotate, or make icons appear dimensional.
