### ISSUE TITLE
string-lights

### ISSUE THREAD

**Issue by weaverprojects** [Templarian/MaterialDesign#4657]
hi, the icon doesn't show up on the Hassio frontend.

<img width="437" alt="Bildschirmfoto 2019-12-10 um 08 00 35" src="https://user-images.githubusercontent.com/26321173/70503192-2c582180-1b23-11ea-97f8-4058aaadeae2.png">

<img width="1398" alt="Bildschirmfoto 2019-12-10 um 07 59 16" src="https://user-images.githubusercontent.com/26321173/70503113-03379100-1b23-11ea-9871-1379096ef5a0.png">

**Comment by Templarian** [comment]
@weaverprojects We released `4.7.95` was released 2 days ago. Usually take a few days for Home Assistant to update. Yeah, it would have been nice to have these in a previous release so they could be used for peoples decorations. Next year. 😃
