### ISSUE TITLE
send-rtl

### ISSUE THREAD

**Issue by Dumb092** [Templarian/MaterialDesign#4658]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
Please do not remove the issue templates when requesting a new icon, even if the responses are obvious from the title.

**Comment by Templarian** [comment]
@Dumb092 That icon is just mirrored for RTL? We generally only add `*-rtl` to icons that can't simply be mirrored.

**Comment by Dumb092** [comment]
@Templarian Hi. No, I'm not able to mirror this icon. Before this, I was using mdi-arrow-right & mdi-arrow-left icons in my chat feature. I wanted to switch to send icon, but couldn't find left/right versions for this one.

**Comment by Templarian** [comment]
But mirroring it is all that is required to support RTL with no other changes? If that's the case it's outside of the scope of this project.

You'll need to look into your platforms approach to mirroring icons to support RTL. This is very common/standard in UI framework/platforms.
