### ISSUE TITLE
Resend Email Icon

### ISSUE THREAD

**Issue by Desnoo** [Templarian/MaterialDesign#4659]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

If an Email has already been sent and the user wants to resend the e-mail.

## Examples
I thought of something like these:

* ![email](https://user-images.githubusercontent.com/5712661/70639985-8cda8200-1c3b-11ea-9bfa-9ed251b0e1a1.png)

* ![Screen Shot 2019-12-11 at 17 28 17](https://user-images.githubusercontent.com/5712661/70640048-a24fac00-1c3b-11ea-85fb-5e28936e76f9.png)

**Comment by CoDEmanX** [comment]
Not sure about the naming, we have other icons with this modifier but they are named inconsistently (repeat, refresh, sync...)

![grafik](https://user-images.githubusercontent.com/1309249/70760622-8a1a8280-1d4a-11ea-82cd-01d78636f93b.png)
![grafik](https://user-images.githubusercontent.com/1309249/70760700-c64de300-1d4a-11ea-9e16-c836bf1fcf92.png)

[email-resend.zip](https://github.com/Templarian/MaterialDesign/files/3958440/email-resend.zip)

**Comment by goyney** [comment]
`sync` makes the most sense for email, so that's the naming convention we went with.

[![email-sync](https://materialdesignicons.com/icon/icon)](https://materialdesignicons.com/icon/email-sync)[![email-sync-outline](https://materialdesignicons.com/icon/icon-outline)](https://materialdesignicons.com/icon/email-sync-outline)
