### ISSUE TITLE
Mark sheet

### ISSUE THREAD

**Issue by atulmala** [Templarian/MaterialDesign#4661]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Mine is an application for schools and download of Mark sheet (results) of exams is a feature of this application.
Need icon to show download mark sheet

## Examples

Include any example images so we know what the icon should look like.

**Comment by MrGrigri** [comment]
Would the user have the option to download any other type of file? If not, just use the `download` icon. I don't know what a mark sheet is. Is there a file format (e.g. .pdf, .doccx)?

**Comment by Templarian** [comment]
Yeah, we've already rejected document type icons with grade icons due to not being able to easily internationalize them.

Might be best to use `format-list-checks`. We might be able to look into a modifier for a `download` in the corner if there is room.

**Comment by Templarian** [comment]
Making a cut out that looks good with download/upload is difficult. 🤔

**Comment by goyney** [comment]
Closing because the `Needs More Info` label was added several months ago with no new suggestions or contributions. Please comment back if you have other ideas that could help fulfill this request. Thank you for your suggestion!
