### ISSUE TITLE
Defrost icon

### ISSUE THREAD

**Issue by nvschilleman** [Templarian/MaterialDesign#4664]
## Usage

Provide some context of how your icon could be used.

Defrosting of refrigeration appliances, I'm currently developing a cold storage monitoring system to keep track of temperatures and control states in Home Assistant

## Examples

Include any example images so we know what the icon should look like.

https://www.123rf.com/photo_84140733_stock-vector-snowflake-and-drop-icon-symbol-of-defrosting-air-conditioning-and-change-of-seasons-concept-.html

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71007206-a012a500-20b4-11ea-984f-5260894aac1c.png)

[snowflake-melt.svg.zip](https://github.com/Templarian/MaterialDesign/files/3973928/snowflake-melt.svg.zip)

**Comment by nvschilleman** [comment]
Very cool! Thank you!!

**Comment by goyney** [comment]
[![snowflake-melt](https://materialdesignicons.com/icon/snowflake-melt)](https://materialdesignicons.com/icon/snowflake-melt)

Added and aliased.
