### ISSUE TITLE
Angular 8 svg integration

### ISSUE THREAD

**Issue by stherrienaspnet** [Templarian/MaterialDesign#4665]
What is the best way to use your svg icons that do not require to load all the icons on the the browser. As additional information I'm using material design library. Wich configuration steps do I need to do.
Thanks for your wonderful work!

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/getting-started/angular ?

**Comment by stherrienaspnet** [comment]
When looking at the guide since the mdi.svg file is around 1749k into the assets folder, it seems that the browser will have to download the file before displaying the first icons. Do I'm right? I just want to confirm my understanding I might be wrong :)  If this is the case using few svg files included into @mdi/svg might make more sense?

**Comment by stherrienaspnet** [comment]
Thanks I now understand :)

**Comment by Templarian** [comment]
Cool, yeah basically use `@mdi/js` for JS development.
