### ISSUE TITLE
lightbulb-group-off/lightbulb-multiple-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4666]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

Now we have the lightbulb-group and lightbulb-multiple icons, which is really cool, please consider adding -off variants, for obvious reasons ;-)
## Examples

Include any example images so we know what the icon should look like.

the default -off diagonal line would be perfect
thanks for considering

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71005953-8a9c7b80-20b2-11ea-956b-b628cf18015c.png)
![image](https://user-images.githubusercontent.com/1015040/71005966-912af300-20b2-11ea-847d-d6f69ceaf6e7.png)
![image](https://user-images.githubusercontent.com/1015040/71005988-9daf4b80-20b2-11ea-9140-5d0ddc3a98e2.png)
![image](https://user-images.githubusercontent.com/1015040/71006014-a6078680-20b2-11ea-9eec-2a05a6dcde88.png)

[lightbulb-off.zip](https://github.com/Templarian/MaterialDesign/files/3973837/lightbulb-off.zip)

**Comment by Mariusthvdb** [comment]
Yes! 🙏

**Comment by goyney** [comment]
[![lightbulb-multiple-off](https://materialdesignicons.com/icon/lightbulb-multiple-off)](https://materialdesignicons.com/icon/lightbulb-multiple-off)[![lightbulb-multiple-off-outline](https://materialdesignicons.com/icon/lightbulb-multiple-off-outline)](https://materialdesignicons.com/icon/lightbulb-multiple-off-outline)
[![lightbulb-group-off](https://materialdesignicons.com/icon/lightbulb-group-off)](https://materialdesignicons.com/icon/lightbulb-group-off)[![lightbulb-group-off-outline](https://materialdesignicons.com/icon/lightbulb-group-off-outline)](https://materialdesignicons.com/icon/lightbulb-group-off-outline)
