### ISSUE TITLE
Hanging Globe Lighting Fixture

### ISSUE THREAD

**Issue by jhein05** [Templarian/MaterialDesign#4667]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

More specific variant of "ceiling-light" for usage in electrical planing or home automation.

## Examples

https://andrewneyer.com/wp-content/uploads/2017/06/AstroGlobeLight.jpg
  or the first couple results from here:
https://www.google.com/search?tbm=isch&q=hanging+globe+light+fixture

Thanks guys :)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71004836-88d1b880-20b0-11ea-87e6-5a74fb5cb321.png)
[globe-light.svg.zip](https://github.com/Templarian/MaterialDesign/files/3973763/globe-light.svg.zip)

**Comment by jhein05** [comment]
Holy smokes, thank you so much!

(Not sure whether I should close the issue or you still need it open for process reasons.)

**Comment by goyney** [comment]
We'll close the issue once it has been added.

**Comment by goyney** [comment]
[![globe-light](https://materialdesignicons.com/icon/globe-light)](https://materialdesignicons.com/icon/globe-light)
