### ISSUE TITLE
petra

### ISSUE THREAD

**Issue by mahmed743** [Templarian/MaterialDesign#4668]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by MrGrigri** [comment]
Please give some examples.

**Comment by Templarian** [comment]
Yeah, not sure what this is requesting. Google shows it's a landmark, but have a feeling this issue is talking about something else?

**Comment by goyney** [comment]
Closing due to no response. If you have more information to share for consideration, please comment back here.
