### ISSUE TITLE
monitor-edit

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4669]
## Research

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

I am in need of an icon that represents prototyping. ~~I believe 'Option 1' is too detailed and I prefer 'Option 2'. Thoughts?~~ The second option will be used.

## Preview

![option-2](https://user-images.githubusercontent.com/4528551/70939424-7cdcec80-2005-11ea-9753-b863001a0d13.png)

## Aliases

- [ ] ui
- [ ] ux
- [ ] prototype
- [ ] design

## Zip Download

[monitor-dashboard-edit.zip](https://github.com/Templarian/MaterialDesign/files/3969919/monitor-dashboard-edit.zip)

**Comment by goyney** [comment]
My vote is option 2.

**Comment by goyney** [comment]
[![monitor-edit](https://materialdesignicons.com/icon/monitor-edit)](https://materialdesignicons.com/icon/monitor-edit)
