### ISSUE TITLE
Update file-delimitated's comma style

### ISSUE THREAD

**Issue by ismaeljtl** [Templarian/MaterialDesign#4670]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It would be great to have an icon similar to the PDF one on https://material.io/resources/icons/?style=baseline

## Examples

Include any example images so we know what the icon should look like.
![csvMI](https://user-images.githubusercontent.com/12703224/70940025-d81bd880-201f-11ea-917f-812472e571ad.png)

**Comment by Templarian** [comment]
We usually try and stay away from from adding text icons for file types. Int his case the text is going to be very cramped at 1:1 size. Would recommend using the current `file-delimitated`.

**Comment by JapanYoshi** [comment]
It's even aliased as ``file-csv``.

But I think it should be renewed to use the same comma as the other ``comma`` icons, then also aliased ``file-comma``.

**Comment by goyney** [comment]
Agree with @JapanYoshi, we won't add the textual icon as suggested in the initial post, but we will use this issue to track updating `file-delimitated` to use the `comma` style.

**Comment by goyney** [comment]
Proposed updates:
![image](https://user-images.githubusercontent.com/1015040/71944345-7ae3f480-3191-11ea-993e-c4f22f136cd4.png)![image](https://user-images.githubusercontent.com/1015040/71944360-820b0280-3191-11ea-915b-3e842cb4ab22.png)

[file-delimited.zip](https://github.com/Templarian/MaterialDesign/files/4033291/file-delimited.zip)

**Comment by goyney** [comment]
Updated.
