### ISSUE TITLE
script-*

### ISSUE THREAD

**Issue by firehiros** [Templarian/MaterialDesign#4671]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by JamesCoyle** [comment]
Please provide examples of what this would look like. Is there a specific symbol which represents kanji?

**Comment by MrGrigri** [comment]
I'm going to close this one out. The Japanese character to represent Kanji is too complicated for a 24x24-pixel icon. And the Chinese characters are more complicated. And from what I can tell, besides these characters, there is no other standardized way of representing Kanji. Also, IMO, this is too specific. 

If you feel differently, please feel free to re-open this issue.

**Comment by firehiros** [comment]
I don't think it need too complicated, you can see an example on below link:
https://favicon.io/favicon-generator/?t=%E5%AD%97&ff=Leckerli+One&fs=110&fc=%23FFF&b=rounded&bc=%23000
And I think 字 character is almost OK, If you need standardized way of representing Kanji. This character is mean word or a character on both Japanese and Chinese

**Comment by JapanYoshi** [comment]
Where's the use in this? I'm Japanese and I can't think of any examples why you would need a kanji icon.

**Comment by firehiros** [comment]
Maybe Japanese will not need using this icon. But non-Japanese like me, will need. It can be used in Japanese/Chinese learning app, or be used for creating custom keyboard (switch between alphabet/kanji)

**Comment by firehiros** [comment]
@JapanYoshi 
Ops, you right. Furigana is good for that cases. I didn't see furigana icon on the beginning, then open this issue, sry about that.

**Comment by MrGrigri** [comment]
@JapanYoshi, do you believe `furigana` alone, sans dots, would be useful as a new icon? I understand that the two dots represent writing direction. But could `furigana` suffice for this request?

**Comment by JapanYoshi** [comment]
![script-latin](https://user-images.githubusercontent.com/8707990/71169492-64d2ca80-229c-11ea-8cc1-57f0da86d770.png)![script-cyrillic](https://user-images.githubusercontent.com/8707990/71169518-77e59a80-229c-11ea-8b57-d291887cf135.png)![script-greek](https://user-images.githubusercontent.com/8707990/71169566-9cda0d80-229c-11ea-99e4-0b2646e9461b.png)![script-arabic](https://user-images.githubusercontent.com/8707990/71169613-b713eb80-229c-11ea-93a4-c163afb0317a.png)![script-hebrew](https://user-images.githubusercontent.com/8707990/71169635-c2671700-229c-11ea-9a0f-887dd1d194d8.png)![script-thai](https://user-images.githubusercontent.com/8707990/71169640-c98e2500-229c-11ea-92b0-d2529aa3a412.png)![script-hiragana](https://user-images.githubusercontent.com/8707990/71169748-05c18580-229d-11ea-84c6-8306ac469ef8.png)![script-katakana](https://user-images.githubusercontent.com/8707990/71169780-1a058280-229d-11ea-9792-576f545488ee.png)![script-cjk](https://user-images.githubusercontent.com/8707990/71169808-2b4e8f00-229d-11ea-8d5f-e8227c66b685.png)![script-cjk-alt](https://user-images.githubusercontent.com/8707990/71169831-37d2e780-229d-11ea-8d81-ee8f624343f1.png)![script-hangul](https://user-images.githubusercontent.com/8707990/71169853-44efd680-229d-11ea-849f-94c6c92214bf.png)

I went the extra 42 miles on this one.

**Comment by MrGrigri** [comment]
Those work perfect I believe

**Comment by JapanYoshi** [comment]
[Here are the merged SVG paths.](https://pastebin.com/aqMnY4fm)

**Comment by CoDEmanX** [comment]
The first 3 look quite similar. Latin and Cyrillic are not very distinct, and Greek could be misinterpreted as German (`aß` vs `αβ`). How about using different letters, which are more commonly recognized as representative for the respective langauge?

![script-latin](https://user-images.githubusercontent.com/8707990/71169492-64d2ca80-229c-11ea-8cc1-57f0da86d770.png)![script-cyrillic](https://user-images.githubusercontent.com/8707990/71169518-77e59a80-229c-11ea-8b57-d291887cf135.png)![script-greek](https://user-images.githubusercontent.com/8707990/71169566-9cda0d80-229c-11ea-99e4-0b2646e9461b.png)

**Comment by JapanYoshi** [comment]
Eszett doesn't have a descender. I tried using Q, Л, and Ψ, but they didn't communicate "Latin, Cyrillic, and Greek script". The first two lowercase letters of these alphabets uniquely identify these three (The capital beta and the capital B are the same shape).

**Comment by goyney** [comment]
We'll need to figure out a better naming scheme for these. `script-*` already exists. Any thoughts there?

**Comment by JapanYoshi** [comment]
Only alternative I can think of is ``writing-system-*``. ``alphabet`` is linguistically incorrect (some are abjads, abugidas, syllabaries, or ideograms), so I can't use that in good faith.

**Comment by CoDEmanX** [comment]
The Cyrillic d is easily mistaken as a Latin A by people who don't know Cyrillic, but still classified as Russian I would say. Here is my little experiment:

![grafik](https://user-images.githubusercontent.com/1309249/71546542-3f2e7b00-2998-11ea-969f-e7f601b29450.png)

I know that the d should be lower and not sit on top of the baseline, but it looks cleaner this way.

**Comment by JapanYoshi** [comment]
@CoDEmanX That looks awful and screams “I don't speak Russian!”.

**Comment by Templarian** [comment]
Yeah, we have a lot of other countries covered, but Russian isn't one. Need to make sure we handle this correctly.

I'm definitely the worst on the team to give feedback. 😅 If anyone knows people to collaborate this that would be great.

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/71566102-073e4980-2af8-11ea-9695-3f7b070457f2.png)
How could I forget Devanagari? This is the first letter of the word "Devanagari" in Hindi (though abugidas don't have "letters" as we do in alphabets...)
```M 8 3 L 8 5 L 11 5 C 12.315018 5 13.408818 5.8328765 13.818359 7 L 6 7 L 6 9 L 14 9 L 14 10 L 12 10 C 9.2504209 10 7 12.250421 7 15 C 7 17.749579 9.2504209 20 12 20 C 12.77183 20 13.453941 19.732815 14 19.296875 L 14 21 L 16 21 L 16 17 L 14 17 C 13.54458 17.615507 12.83435 18 12 18 C 10.331301 18 9 16.668699 9 15 C 9 13.331301 10.331301 12 12 12 L 16 12 L 16 9 L 18 9 L 18 7 L 15.898438 7 C 15.43156 4.7253923 13.407209 3.0000001 11 3 L 8 3 z ```

**Comment by JapanYoshi** [comment]
![tengwar](https://user-images.githubusercontent.com/8707990/71706089-2efa1e00-2e26-11ea-8ed7-ece6b9474542.png)
![klingon](https://user-images.githubusercontent.com/8707990/71705914-2bb26280-2e25-11ea-88ec-7f2db2fffbba.png)
![aurebesh](https://user-images.githubusercontent.com/8707990/71706111-4a652900-2e26-11ea-93f7-e7f7c3c288ff.png)
For fun, here are the three conscripts that I know of: Tengwar (Lord of the Rings), Klingon pIqaD (Star Trek), and Aurebesh (Star Wars)

**Comment by goyney** [comment]
I want to get these in this next version, but I need a final list of all icons being added and their names attached below this reply for that to happen. Someone please do that. 😄

**Comment by JapanYoshi** [comment]
writing-system-latin
m 13,6 v 12 h 2 V 17.304688 C 15.367937,17.726584 15.902274,18 16.5,18 H 17 c 1.644703,0 3,-1.355297 3,-3 V 12 C 20,10.355297 18.644703,9 17,9 H 16.5 C 15.902274,9 15.367937,9.2734161 15,9.6953125 V 6 Z M 5,9 v 2 h 3 c 0.5712972,0 1,0.428703 1,1 H 7 c -1.6447028,0 -3,1.355297 -3,3 0,1.644703 1.3552972,3 3,3 h 4 V 12 C 11,10.355297 9.6447028,9 8,9 Z m 11,2 h 1 c 0.571297,0 1,0.428703 1,1 v 3 c 0,0.571297 -0.428703,1 -1,1 h -1 c -0.571297,0 -1,-0.428703 -1,-1 v -3 c 0,-0.571297 0.428703,-1 1,-1 z m -9,3 h 2 v 2 H 7 C 6.4287028,16 6,15.571297 6,15 6,14.428703 6.4287028,14 7,14 Z

writing-system-cyrillic
m 16,6 c -1.64501,0 -3,1.3549907 -3,3 v 6 c 0,1.644703 1.355297,3 3,3 h 1 c 1.644703,0 3,-1.355297 3,-3 V 12 C 20,10.355297 18.644703,9 17,9 h -2 c 0,-0.5641295 0.43587,-1 1,-1 h 2 c 1.092725,0 2,-0.9072754 2,-2 z M 5,9 v 2 h 3 c 0.5712972,0 1,0.428703 1,1 H 7 c -1.6447028,0 -3,1.355297 -3,3 0,1.644703 1.3552972,3 3,3 h 4 V 12 C 11,10.355297 9.6447028,9 8,9 Z m 10,2 h 2 c 0.571297,0 1,0.428703 1,1 v 3 c 0,0.571297 -0.428703,1 -1,1 h -1 c -0.571297,0 -1,-0.428703 -1,-1 z m -8,3 h 2 v 2 H 7 C 6.4287028,16 6,15.571297 6,15 6,14.428703 6.4287028,14 7,14 Z

writing-system-greek
m 16,6 c -1.644703,0 -3,1.3552972 -3,3 v 12 h 2 V 9 c 0,-0.5712972 0.428703,-1 1,-1 h 1 c 0.571297,0 1,0.4287028 1,1 v 1 c 0,0.571297 -0.428703,1 -1,1 h -1 v 2 h 1 c 0.571297,0 1,0.428703 1,1 v 1 c 0,0.571297 -0.428703,1 -1,1 h -1 v 2 h 1 c 1.644703,0 3,-1.355297 3,-3 V 14 C 20,13.1829 19.593133,12.457459 18.978516,12 19.593133,11.542541 20,10.8171 20,10 V 9 C 20,7.3552972 18.644703,6 17,6 Z M 7,9 C 5.3552972,9 4,10.355297 4,12 v 3 c 0,1.644703 1.3552972,3 3,3 H 7.6992188 C 8.1960007,18 8.6485182,17.808765 9,17.503906 V 18 h 2 V 9 H 9 V 9.4960938 C 8.6485182,9.1912353 8.1960007,9 7.6992188,9 Z m 0,2 h 1 c 0.5712972,0 1,0.428703 1,1 v 3 c 0,0.571297 -0.4287028,1 -1,1 H 7 C 6.4287028,16 6,15.571297 6,15 v -3 c 0,-0.571297 0.4287028,-1 1,-1 z

writing-system-arabic
M 12,4 C 10.078848,4 8.5000001,5.5788482 8.5,7.5 8.5,8.4328208 8.8775584,9.2802927 9.4804688,9.9101562 7.9678398,10.907894 7.0000001,12.615825 7,14.5 c -1e-7,3.025721 2.4742787,5.5 5.5,5.5 1.755316,0 3.479852,-0.462185 5,-1.339844 l -1,-1.732422 C 15.283802,17.629907 13.904344,18 12.5,18 10.555159,18 8.9999999,16.444841 9,14.5 c 10e-8,-1.588952 1.058888,-2.969797 2.59375,-3.380859 L 16.800781,9.7246094 16.28125,7.7929688 11.833984,8.984375 C 11.075396,8.9031796 10.5,8.2834139 10.5,7.5 10.5,6.6597282 11.159728,6 12,6 c 0.263356,0 0.521927,0.069494 0.75,0.2011719 l 1,-1.7324219 C 13.217977,4.1615863 12.614328,4 12,4 Z

writing-system-hebrew
m 3.9023438,4 5.1152343,6.029297 C 7.5829395,10.172561 6.3637213,11.177922 5.984375,12.59375 L 4,20 H 6.0703125 L 7.9160156,13.111328 C 8.0915316,12.456255 8.6851022,12 9.3632812,12 H 10.6875 l 6.787109,8 h 2.623047 l -5.115234,-6.029297 c 1.434639,-0.143264 2.653857,-1.148625 3.033203,-2.564453 L 20,4 h -2.070312 l -1.845704,6.888672 C 15.908468,11.543745 15.314898,12 14.636719,12 H 13.3125 L 6.5253906,4 Z

writing-system-thai
M 9,20 C 9,17.436079 10.870239,12.424438 13.857422,7.2509766 14.290608,6.5007471 15.076208,6 16,6 c 1.116413,0 2,0.88359 2,2 v 12 h 2 V 8 C 20,5.80271 18.197297,4 16,4 14.343693,4 12.898142,4.9153272 12.126953,6.25 10.559801,8.9622202 9.6046961,11.14524 9,13.027344 V 6.5 C 9,5.13113 7.8688672,4 6.5,4 5.1311328,4 4,5.13113 4,6.5 4,7.86887 5.1311328,9 6.5,9 6.6711084,9 6.8380657,8.9828217 7,8.9492188 V 20 Z M 6.5,6 C 6.787987,6 7,6.21201 7,6.5 7,6.78799 6.787987,7 6.5,7 6.212013,7 6,6.78799 6,6.5 6,6.21201 6.212013,6 6.5,6 Z

writing-system-hiragana
M 9,4 V 6 H 6 v 2 h 3 v 2.001953 c -2.7552988,0.01605 -5,2.268408 -5,5.027344 0,2.768813 2.2604834,5.029297 5.0292969,5.029297 0.8616417,0 1.6866291,-0.29019 2.3710941,-0.796875 0.230659,0.282466 0.477598,0.557676 0.74414,0.824219 l 1.414063,-1.414063 C 13.30214,18.415421 13.071892,18.153494 12.857422,17.886719 l 1,-1 c 1.068815,-1.068815 1.924101,-2.657246 2.558594,-4.296875 C 17.307529,13.111761 18,13.89989 18,15.013672 c 0,1.309484 -0.526891,2.583531 -1.464844,3.521484 l 1.414063,1.414063 C 19.261702,18.636736 20,16.857705 20,15.013672 c 0,-1.972178 -1.180364,-3.6492 -2.851562,-4.466797 L 17.484375,9.2929688 15.550781,8.7753906 15.208984,10.048828 C 15.12558,10.044684 15.055102,10 14.970703,10 H 11 V 8 h 5 V 6 H 11 V 4 Z m 2,8 h 3.5 c -0.562931,1.368543 -1.306787,2.722802 -2.056641,3.472656 l -0.658203,0.658203 C 11.248469,14.932563 11,13.592621 11,12 Z m -2,0.002 c 2.601e-4,2.070263 0.4150411,3.937489 1.296875,5.591797 C 9.9400741,17.888325 9.4961211,18.058594 9.0292969,18.058594 7.3338889,18.058594 6,16.724704 6,15.029297 6,13.343918 7.3189068,12.017607 9,12.001953 Z

writing-system-katakana
M 4,4 V 6 H 18 V 6.085937 L 14.292969,9.7929688 15.707031,11.207031 20,6.9140625 V 4 Z m 7,5 v 4 c 0,2.777778 -0.750363,3.893008 -2.6386719,5.462891 L 9.6386719,20 C 11.750363,18.244403 13,16.222222 13,13 V 9 Z

writing-system-katakana-halfwidth
m 8,4 v 2 h 5.980469 l -0.960938,4.804688 1.960938,0.390624 L 16,6.0996094 V 4 Z m 2,5 v 3 c 0,2.854544 -0.6611911,5.291105 -1.921875,6.609375 l 1.4453125,1.380859 C 11.35365,18.076421 12,15.145456 12,12 V 9 Z

writing-system-cjk
M 11,4 V 6 H 4 v 4 H 6 V 8 h 12 v 2 h 2 V 6 H 13 V 4 Z m -3,6 v 2 h 5.585938 l -2,2 H 4 v 2 h 7 v 2 h -1 v 2 h 3 v -4 h 7 V 14 H 14.214 L 16,12.214 V 10 Z

writing-system-cjk-variant
M 11,4 V 6 H 4 V 8 H 15.355469 C 15.127991,8.8704468 14.62763,9.7686698 13.882812,10.693359 13.351329,11.353196 12.707007,12.014932 12,12.673828 11.292992,12.014932 10.64867,11.353196 10.117188,10.693359 9.6539868,10.118297 9.2977688,9.5543659 9.0273438,9 H 6.8476562 c 0.3602991,1.047789 0.9732371,2.028986 1.7128907,2.947266 C 9.1335256,12.658618 9.7909617,13.339669 10.490234,14 L 5.3652344,18.228516 6.6347656,19.771484 12,15.34375 17.365234,19.771484 18.634766,18.228516 13.509766,14 c 0.699272,-0.660331 1.356708,-1.341382 1.929687,-2.052734 C 16.409437,10.743032 17.156208,9.4288598 17.404297,8 H 20 V 6 H 13 V 4 Z

writing-system-hangul
M 8,4 V 6 H 4 V 8 H 6.3886719 C 5.5462008,8.735161 5,9.8028706 5,11 c 0,2.197294 1.8027056,4 4,4 2.197294,0 4,-1.802706 4,-4 C 13,9.8028706 12.453799,8.735161 11.611328,8 H 14 V 6 H 10 V 4 Z m 7,0 v 12 h 2 v -5 h 3 V 9 H 17 V 4 Z M 9,9 c 1.116414,0 2,0.8835859 2,2 0,1.116414 -0.883586,2 -2,2 C 7.8835859,13 7,12.116414 7,11 7,9.8835859 7.8835859,9 9,9 Z m -2,7 v 4 H 17 V 18 H 9 v -2 z

writing-system-devanagari
M 8 3 L 8 5 L 11 5 C 12.315018 5 13.408818 5.8328765 13.818359 7 L 6 7 L 6 9 L 14 9 L 14 10 L 12 10 C 9.2504209 10 7 12.250421 7 15 C 7 17.749579 9.2504209 20 12 20 C 12.77183 20 13.453941 19.732815 14 19.296875 L 14 21 L 16 21 L 16 17 L 14 17 C 13.54458 17.615507 12.83435 18 12 18 C 10.331301 18 9 16.668699 9 15 C 9 13.331301 10.331301 12 12 12 L 16 12 L 16 9 L 18 9 L 18 7 L 15.898438 7 C 15.43156 4.7253923 13.407209 3.0000001 11 3 L 8 3 z 

writing-system-tengwar
m 3,4 v 7 H 14.226562 L 22,4 H 19.011719 L 13.458984,9 H 5 V 4 Z m 0,9 v 7 h 2 v -5 h 8.458984 l 5.552735,5 H 22 l -7.773438,-7 z

writing-system-piqad
M 13.037109,4 6.5429688,17.845703 C 6.2129704,18.549269 5.5075819,19.00004 4.7304688,19 H 4 v 1 h 12 c 1.202785,0 2.268532,0.542938 3,1.384766 l 1.007812,0.0039 C 19.046865,19.323754 16.976806,18 14.699219,18 H 12 C 11.285224,17.999556 10.620139,17.634237 10.236328,17.03125 9.8534721,16.430407 9.8005017,15.675015 10.101562,15.029297 L 10.582031,14 H 19 v -1 h -1.5 c -2.209139,0 -4,-1.790861 -4,-4 0,-2.209139 1.790861,-4 4,-4 H 20 V 4 Z

writing-system-aurebesh
M 3 4 L 3 11 L 14.226562 11 L 22 4 L 19.011719 4 L 13.458984 9 L 5 9 L 5 4 L 3 4 z M 3 13 L 3 20 L 5 20 L 5 15 L 13.458984 15 L 19.011719 20 L 22 20 L 14.226562 13 L 3 13 z

**Comment by goyney** [comment]
Thanks @JapanYoshi, I'm compiling these now for addition.

Question: Would these not all be considered alphabets? Could we use `alphabet-latin`, `alphabet-arabic`, etc. instead?

**Comment by MrGrigri** [comment]
I would use `alphabet-*`

**Comment by goyney** [comment]
All are added with two exceptions:

- `katakana-halfwidth` seems superfolous
- `tengwar`'s path data is Aurebesh's. Probably bad copy pasta. @JapanYoshi can you provide the correct path data for it?

**Comment by JapanYoshi** [comment]
@goyney @MrGrigri 
> Question: Would these not all be considered alphabets? Could we use `alphabet-latin`, `alphabet-arabic`, etc. instead?

***NO!*** Thai and Devanagari are abugidas. Arabic and Hebrew are abjads. Hiragana, Katakana, and Hangul are syllabaries. CJK ideograms are ideograms.

> * `katakana-halfwidth` seems superfolous

Japanese has a multibyte encoding system where a version of katakana is encoded using 1 byte instead of 2 bytes, and shown with half the width of normal katakana. They're different things.

* Fullwidth katakana looks like this: コンピューター
* Halfwidth katakana looks like this: ｺﾝﾋﾟｭｰﾀｰ

Of course, they're included in Unicode.

> * `tengwar`'s path data is Aurebesh's. Probably bad copy pasta. @JapanYoshi can you provide the correct path data for it?

It should be in this. https://github.com/Templarian/MaterialDesign/issues/4671#issuecomment-570450970

**Comment by goyney** [comment]
Tengwar's path data is incorrect. Do you have the good path data?

**Comment by goyney** [comment]
> _**NO!**_ Thai and Devanagari are abugidas. Arabic and Hebrew are abjads. Hiragana, Katakana, and Hangul are syllabaries. CJK ideograms are ideograms.

This was super helpful! These scripts have been renamed to be specific (e.g. `abugida-thai`, `abjad-arabic`, `syllabary-hangul`, `ideogram-cjk`, etc)

> Japanese has a multibyte encoding system (well, several of them) where a version of katakana is encoded using 1 byte instead of 2 bytes, and shown with half the width of normal katakana. They're different things.

They look the same, just squished. Is their meanings any different?

**Comment by JapanYoshi** [comment]
> This was super helpful! These scripts have been renamed to be specific (e.g. `abugida-thai`, `abjad-arabic`, `syllabary-hangul`, `ideogram-cjk`, etc)
That sounds like a total disaster. You should name the icons `writing-system-name` and alias them as `specific-type-of-writing-system-name` (possibly `script-name`). That way it's more searchable.

> They look the same, just squished. Is their meanings any different?

It has the same difference between “HELLO WORLD” and “ＨＥＬＬＯ　ＷＯＲＬＤ” (Those are “fullwidth” letters), and Japanese input methods consider them a different type of letter. And in fact I'd wager all Japanese developers. (In name entry screens, you may read “Enter your name phonetically in fullwidth katakana”.)

**Comment by goyney** [comment]
K, I'll add it. I still need path data for tengwar.

**Comment by goyney** [comment]
Nevermind, I recreated it. All of these have been added and aliased!
