### ISSUE TITLE
chat-sleep

### ISSUE THREAD

**Issue by julienreszka** [Templarian/MaterialDesign#4672]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

**Temporarily Stop chat notifications from disturbing user**

## Examples

Include any example images so we know what the icon should look like.

like `bell-sleep` 
https://petershaggynoble.github.io/MDI-Sandbox/?icon=bell-sleep
https://petershaggynoble.github.io/MDI-Sandbox/?icon=bell-sleep-outline
but `chat`
https://petershaggynoble.github.io/MDI-Sandbox/?icon=chat

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71006411-4d84b900-20b3-11ea-8145-9d3231f5e319.png)
![image](https://user-images.githubusercontent.com/1015040/71006443-54133080-20b3-11ea-90e0-56c5158063c6.png)

[chat-sleep.zip](https://github.com/Templarian/MaterialDesign/files/3973868/chat-sleep.zip)

**Comment by MrGrigri** [comment]
Can we ensure the letter 'Z' is internationalized?

**Comment by goyney** [comment]
Considering the icons we currently have with "Z"s in them are Google stock icons, I feel these are okay to add. However, you sparked my curiosity about "Z" and sleeping, and this is what I found:

> Originally, the resemblance between the 'z' sound and that of a snore seemed exclusive to the English language, but the spread of American comics has made it a frequent feature in other countries. An exception to this is in Japanese manga, where the usual symbol for sleep is a large bubble coming out of the character's nose.

[Source](https://en.wikipedia.org/wiki/Speech_balloon#The_big_Z)

**Comment by goyney** [comment]
[![chat-sleep](https://materialdesignicons.com/icon/chat-sleep)](https://materialdesignicons.com/icon/chat-sleep)[![chat-sleep-outline](https://materialdesignicons.com/icon/chat-sleep-outline)](https://materialdesignicons.com/icon/chat-sleep-outline)
