### ISSUE TITLE
Request Google Material "explicit" icon

### ISSUE THREAD

**Issue by cawa-93** [Templarian/MaterialDesign#4677]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Need to mark explicit content. How it's done, say, on Google Music

## Examples
https://material.io/resources/icons/?icon=explicit&style=baseline

**Comment by goyney** [comment]
Already exists:

[![alpha-e-box](https://materialdesignicons.com/icon/alpha-e-box)](https://materialdesignicons.com/icon/alpha-e-box)
