### ISSUE TITLE
propane-tank(-outline)

### ISSUE THREAD

**Issue by klawdyo** [Templarian/MaterialDesign#4678]
I have:

- [x ] Searched open issues to make sure there isn't a request for this icon.
- [ x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/100168/71131054-5ddf8580-21d2-11ea-8f92-0fadb40916ef.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[Botijão Solido.zip](https://github.com/Templarian/MaterialDesign/files/3980919/Botijao.Solido.zip)

**Comment by Templarian** [comment]
Nice start. Probably need to overexaggerat the handle with a 2px line somehow.

**Comment by klawdyo** [comment]
![image](https://user-images.githubusercontent.com/100168/71132219-a8aecc80-21d5-11ea-8b03-fc8cc83df864.png)

This is the original. The generated preview was a little bit different

**Comment by Templarian** [comment]
Yep, even in that preview we'll need a 2dp thick line. The line separator on the tank might be fine, but an outline/filled version of this icon is probably possible.

**Comment by goyney** [comment]
I think the problem is just too much detail. Here's a simplistic approach:

![image](https://user-images.githubusercontent.com/1015040/72308858-55506280-364b-11ea-8f32-c3de1d638fd8.png)
![image](https://user-images.githubusercontent.com/1015040/72308875-5d100700-364b-11ea-8909-aab9946d96be.png)

[propane-tank.zip](https://github.com/Templarian/MaterialDesign/files/4057043/propane-tank.zip)

**Comment by goyney** [comment]
[![propane-tank](https://materialdesignicons.com/icon/propane-tank)](https://materialdesignicons.com/icon/propane-tank)[![propane-tank-outline](https://materialdesignicons.com/icon/propane-tank-outline)](https://materialdesignicons.com/icon/propane-tank-outline)
