### ISSUE TITLE
Icon Propane Outline

### ISSUE THREAD

**Issue by klawdyo** [Templarian/MaterialDesign#4679]
## Preview
![image](https://user-images.githubusercontent.com/100168/71131719-43a6a700-21d4-11ea-9cf7-99feb5a6c21a.png)

## Zip Download
[propane-outline.zip](https://github.com/Templarian/MaterialDesign/files/3980944/propane-outline.zip)

**Comment by klawdyo** [comment]
![image](https://user-images.githubusercontent.com/100168/71131807-7f417100-21d4-11ea-8a91-f1cdecf01850.png)

This is original icon. The generated preview is different, but I don't know why.

**Comment by CoDEmanX** [comment]
Looks more like a Cyberman to me. Needs more simplification.

**Comment by JamesCoyle** [comment]
Yeah this is too detailed. Need to use 2dp wide strokes where possible.

**Comment by goyney** [comment]
Going to close this as a duplicate of #4678 since they're the same icons, just this is an outline variant.
