### ISSUE TITLE
chart-line

### ISSUE THREAD

**Issue by aljachimiak** [Templarian/MaterialDesign#468]
Reason:

[View History Item](http://materialdesignicons.com/history/550B487D-F27E-458B-9634-5E3B64D25006)

Hi - I really liked the previous chart-line icon...

I'm sure you have your reasons for changing it.  

Can the previous look come back with a different name?  I am using it in a current project and would need this in there to continue with updates.

Thanks,
Al

**Comment by Templarian** [comment]
Yea, I'll look into it. I'm not actually a huge fan of the redesign, so it might go back to a more traditional line chart.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/chart-line
https://materialdesignicons.com/icon/chart-areaspline
