### ISSUE TITLE
hydro power

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#4680]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![grafik](https://user-images.githubusercontent.com/7279415/71161095-04ff0400-2249-11ea-939f-bdac0457de8a.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[hydropower.zip](https://github.com/Templarian/MaterialDesign/files/3982694/hydropower.zip)

**Comment by CoDEmanX** [comment]
@Templarian Added to your account, but I think it's time for a separate contributor account:
https://github.com/Templarian/MaterialDesign/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Aboehan

**Comment by goyney** [comment]
This is only @boehan's third addition to the library, 2 more before a contributor account is created for them.
