### ISSUE TITLE
mdi-folder-table

### ISSUE THREAD

**Issue by TheWilks** [Templarian/MaterialDesign#4681]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Need a folder the visually represents that it is full of datasets. Just a folder icon similar to the file icon below. Filled and outlined variants.

## Examples

![file-table-outline](https://user-images.githubusercontent.com/6516828/71197155-00454a80-225f-11ea-8a57-3e892013b478.png)

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/71301797-33452680-23a4-11ea-8cee-63dbe9bc789c.png)
![grafik](https://user-images.githubusercontent.com/1309249/71301799-3d672500-23a4-11ea-8e37-22a53847b6b6.png)

Not sure if I like it.

[folder-table.zip](https://github.com/Templarian/MaterialDesign/files/3990971/folder-table.zip)

Would it make sense to use a "landscape" modifier?

![grafik](https://user-images.githubusercontent.com/1309249/71301816-7e5f3980-23a4-11ea-953f-00b7ac871c7c.png)
![grafik](https://user-images.githubusercontent.com/1309249/71301848-ad75ab00-23a4-11ea-99e6-a97255d1c838.png)

**Comment by TheWilks** [comment]
I like the vertical table personally because it’s consistent with the other icons.

**Comment by goyney** [comment]
I'm a fan of the vertical tables as well for consistency sake.

**Comment by CoDEmanX** [comment]
Added, will be released with v4.8
