### ISSUE TITLE
file-clock

### ISSUE THREAD

**Issue by andrewspy** [Templarian/MaterialDesign#4682]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Show when a file is pending.

## Examples

Similar to `folder-clock` and `folder-clock-outline`

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/71301722-43a8d180-23a3-11ea-8ef9-92786d69292b.png)
![grafik](https://user-images.githubusercontent.com/1309249/71301730-4e636680-23a3-11ea-9929-798c1cd20b7a.png)

or with the base icon in the original position:

![grafik](https://user-images.githubusercontent.com/1309249/71301737-5a4f2880-23a3-11ea-95bd-0ca941a2d51d.png)
![grafik](https://user-images.githubusercontent.com/1309249/71301741-6509bd80-23a3-11ea-880f-e4731107c934.png)

I prefer the former.

[file-clock.zip](https://github.com/Templarian/MaterialDesign/files/3990965/file-clock.zip)

**Comment by goyney** [comment]
Agreed, go with the former.

**Comment by CoDEmanX** [comment]
Added, will be released with v4.8
