### ISSUE TITLE
Graduation rolled paper

### ISSUE THREAD

**Issue by sdavid501** [Templarian/MaterialDesign#4685]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
> Include any example images so we know what the icon should look like.

**Comment by sdavid501** [comment]
![SmartSelect_20191220-140113_Chrome](https://user-images.githubusercontent.com/22420460/71285451-318f4a80-2333-11ea-8da8-649866fcd1a3.jpg)

**Comment by CoDEmanX** [comment]
Would any of the script or certificate icons work?

**Comment by sdavid501** [comment]
No

**Comment by goyney** [comment]
This really is going to be hard to depict because of the dimensional nature of the roll.

I would recommend the `script` icons or the `certificate` icons as @CoDEmanX suggested.

**Comment by sdavid501** [comment]
That's fine. Thanks for your help.
