### ISSUE TITLE
Account blocked/disabled

### ISSUE THREAD

**Issue by gdang** [Templarian/MaterialDesign#4686]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Can be shown on the user's account page as an empty state.

## Examples

![Example image](https://miro.medium.com/max/372/1*m-_ey1OZeqXHEfg5k8AHFw.png)

**Comment by JapanYoshi** [comment]
You didn't search the current library hard enough. [`account-off`](http://materialdesignicons.com/icon/account-off)

**Comment by CoDEmanX** [comment]
Alternative representation:

![grafik](https://user-images.githubusercontent.com/1309249/71301656-55d64000-23a2-11ea-8344-e47e99544bf9.png)

![grafik](https://user-images.githubusercontent.com/1309249/71301651-49ea7e00-23a2-11ea-8b94-515c2395d0dc.png)

[account-cancel.zip](https://github.com/Templarian/MaterialDesign/files/3990962/account-cancel.zip)

**Comment by JapanYoshi** [comment]
What benefit does that present over `account-off`?

**Comment by CoDEmanX** [comment]
account-off is more like a toggle, which a user can change (actionable), whereas account-cancel is more of a status indication beyond that user's control. That's at least one interpretation.The cancel variant could also be used as icon for a "block user" action of course, which is stronger than the off variant IMO.I'm not sure how one would use both icons on the same page for different things though. This leaving it up for voting.

**Comment by gdang** [comment]
> You didn't search the current library hard enough. [`account-off`](http://materialdesignicons.com/icon/account-off)

I do know about account-off, but @CoDEmanX's draft is exactly what I'm looking for in my use case.

I also agree that the -off icons look more appropriate for toggles but YMMV I suppose.

**Comment by CoDEmanX** [comment]
Added, will be released with v4.8
