### ISSUE TITLE
account-tie-voice

### ISSUE THREAD

**Issue by caiosweet** [Templarian/MaterialDesign#4687]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Voice notification center

## Examples

![account-tie-voice](https://user-images.githubusercontent.com/24454580/71295231-57404200-237b-11ea-8331-dc6ee2c69d59.jpg)

[account-tie-voice.zip](https://github.com/Templarian/MaterialDesign/files/3990421/account-tie-voice.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71928478-a224cc80-3165-11ea-9db0-fda1e3f545cd.png)![image](https://user-images.githubusercontent.com/1015040/71928490-a94bda80-3165-11ea-8a9d-205f91f3a3b6.png)
![image](https://user-images.githubusercontent.com/1015040/71928513-b36dd900-3165-11ea-852d-e269f7e2960e.png)![image](https://user-images.githubusercontent.com/1015040/71928532-ba94e700-3165-11ea-9374-787518a52bac.png)

[account-tie-voice.zip](https://github.com/Templarian/MaterialDesign/files/4032423/account-tie-voice.zip)

**Comment by goyney** [comment]
[![account-tie-voice](https://materialdesignicons.com/icon/account-tie-voice)](https://materialdesignicons.com/icon/account-tie-voice)[![account-tie-voice-outline](https://materialdesignicons.com/icon/account-tie-voice-outline)](https://materialdesignicons.com/icon/account-tie-voice-outline)
[![account-tie-voice-off](https://materialdesignicons.com/icon/account-tie-voice-off)](https://materialdesignicons.com/icon/account-tie-voice-off)[![account-tie-voice-off-outline](https://materialdesignicons.com/icon/account-tie-voice-off-outline)](https://materialdesignicons.com/icon/account-tie-voice-off-outline)
