### ISSUE TITLE
Donate icon

### ISSUE THREAD

**Issue by midhunhk** [Templarian/MaterialDesign#469]
Hi, Is it possible to get a Donate icon. Can't think of one, sorry.

**Comment by Templarian** [comment]
Would the gift icon work for this? https://materialdesignicons.com/icon/gift

A google search pulls up... but I think the gift icon might be better.

![image](https://cloud.githubusercontent.com/assets/338885/8393397/07002f0c-1cd3-11e5-9f7a-1e28b6e97a04.png)

**Comment by midhunhk** [comment]
That's brilliant Andrew, can you maybe add a tag against the gift icon as donate. Thanks.

**Comment by Templarian** [comment]
Adding an alias `donate` to the gift icon.
