### ISSUE TITLE
drag_handle

### ISSUE THREAD

**Issue by ThewBear** [Templarian/MaterialDesign#4690]
I cannot find it.
https://material.io/resources/icons/?icon=drag_handle&style=baseline

**Comment by Templarian** [comment]
We'll need to add variants. Right now drag is represented by dotted lines.

**Comment by Templarian** [comment]
- [ ] `drag-horizontal-variant`
- [ ] `drag-vertical-variant`

**Comment by goyney** [comment]
[![drag-horizontal-variant](https://materialdesignicons.com/icon/drag-horizontal-variant)](https://materialdesignicons.com/icon/drag-horizontal-variant)[![drag-vertical-variant](https://materialdesignicons.com/icon/drag-vertical-variant)](https://materialdesignicons.com/icon/drag-vertical-variant)
