### ISSUE TITLE
Add icon for air humidity

### ISSUE THREAD

**Issue by FauthD** [Templarian/MaterialDesign#4691]
Hi,
there are icons for temperature, none for humidity yet.

**Comment by CoDEmanX** [comment]
There is air-humidifier if you need a device icon and water-percent for humidity itself.

**Comment by goyney** [comment]
[![air-humidifier](https://materialdesignicons.com/icon/air-humidifier)](https://materialdesignicons.com/icon/air-humidifier)
[![water-percent](https://materialdesignicons.com/icon/water-percent)](https://materialdesignicons.com/icon/water-percent)
