### ISSUE TITLE
pdf-box-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4694]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Variant for `pdf-box`

## Examples

![pdf-box-outline](https://user-images.githubusercontent.com/6717356/71450137-c0a1c580-276c-11ea-9729-35fe2b8c85cd.png)

**Comment by goyney** [comment]
This is not possible in the size constraints we have and we've avoided adding it in the past. Thanks for the suggestion, but we will be unable to add this.
