### ISSUE TITLE
cart-delete / cart-delete-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4695]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Deleting an item from the cart.

## Examples

![cart-delete-outline](https://user-images.githubusercontent.com/6717356/71501244-5f681800-287a-11ea-8ae4-638435cf1b6b.png)
![cart-delete](https://user-images.githubusercontent.com/6717356/71501246-61ca7200-287a-11ea-83cf-eb7d0eb9f1e1.png)

**Comment by CoDEmanX** [comment]
The trash can is too small and too literal IMO. We already have cart-remove with an x, which is technically an outline icon. Not sure if a filled variant is possible with our current approach of placing the secondary shape in the center.

We could try to adjust all the cart icons to use the standard cutout in the bottom right corner for the modifier, but I'm unsure how well that may work with this particular base icon.

**Comment by goyney** [comment]
As @CoDEmanX, `cart-remove` already exists.
