### ISSUE TITLE
Request Icon for Shader Files in VScode

### ISSUE THREAD

**Issue by hyt589** [Templarian/MaterialDesign#4696]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The requested icon would be used in VS code editor to represent shading language program files (*.glsl, *.hlsl, *.cg).

## Examples

The requested icon would look something like this: 
![](https://image.winudf.com/v2/image/Y29tLmdvbWRldi5zaGFkZXJfaWNvbl8wX2EyNzVlNTZk/icon.png?w=170&fakeurl=1)
![](https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/d7785084-d31b-454b-8e34-4523f5e33527/dchlqkx-48fa552c-7eca-4cfa-be39-9c4dea96dc7a.png/v1/fill/w_1024,h_1024,q_80,strp/shader_icon_by_marion_thorne_dchlqkx-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTAyNCIsInBhdGgiOiJcL2ZcL2Q3Nzg1MDg0LWQzMWItNDU0Yi04ZTM0LTQ1MjNmNWUzMzUyN1wvZGNobHFreC00OGZhNTUyYy03ZWNhLTRjZmEtYmUzOS05YzRkZWE5NmRjN2EucG5nIiwid2lkdGgiOiI8PTEwMjQifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.I83d7aPemiOEiE7hekSSvJuHEICth_EyLoqQtGIXlvE)

**Comment by goyney** [comment]
I'd use `cube` or `cube-outline`. It takes a really good reason to break Material guidelines and add perspective to an icon, so using one which already exists is going to be your best bet.
