### ISSUE TITLE
Hydraulic oil level, hydraulic oil temperature symbol

### ISSUE THREAD

**Issue by edepalos** [Templarian/MaterialDesign#4697]
Dear All,

First of all thank you for your work!!
To one of my project I'm searching for hydraulic oil temperature, level and pressure symbols, a nicely designed one, not like I made in Paint. Thank You In advance and a Happy New Year!!
![Hydrooillevel](https://user-images.githubusercontent.com/59317443/71547797-05b03c80-29a5-11ea-846d-0f1ee6a171de.png)
![HydroOoilTemp_Red](https://user-images.githubusercontent.com/59317443/71547808-25dffb80-29a5-11ea-915a-2615449c638d.png)

**Comment by goyney** [comment]
Our `oil-level` and `oil-temperature` icons would not fill this use case?

**Comment by edepalos** [comment]
Hi,

Unfortunatelly if I have a diesel-hydraulic powerpack than I can not distinguish between the two warning signs...

**Comment by goyney** [comment]
So, the two icons provided in the initial request are actual ISO icons. It should be fairly simple to Materialize these for inclusion.

Hydraulic Oil Level - https://www.iso.org/obp/ui#iso:grs:7000:1412
Hydraulic Oil Temp - https://www.iso.org/obp/ui#iso:grs:7000:1414

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/72378769-0e607c80-36e0-11ea-80c6-e31d703b12d7.png)![image](https://user-images.githubusercontent.com/1015040/72378842-3059ff00-36e0-11ea-9fff-98cb83dfbb3e.png)

[hydraulic-oil.zip](https://github.com/Templarian/MaterialDesign/files/4061252/hydraulic-oil.zip)

**Comment by goyney** [comment]
[![hydraulic-oil-level](https://materialdesignicons.com/icon/hydraulic-oil-level)](https://materialdesignicons.com/icon/hydraulic-oil-level)[![hydraulic-oil-temperature](https://materialdesignicons.com/icon/hydraulic-oil-temperature)](https://materialdesignicons.com/icon/hydraulic-oil-temperature)

**Comment by edepalos** [comment]
Dear Michael,

The icons are wonderful!! Thank You!

Best regards,
Ede
