### ISSUE TITLE
doorbell

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4698]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Description

I recently made my doorbell smart, but I'm not using any of those cloud-based video doorbells out of privacy concerns (so no `video-doorbell`). I'd like to show my doorbell button in Home Assistant, but the closest thing we have that I like is `light-switch`.

<img width="487" alt="Screen Shot 2019-12-28 at 12 10 08 PM" src="https://user-images.githubusercontent.com/1015040/71547864-062be180-296b-11ea-82d4-465fa2864a4b.png">

However, this clashes with other actual light switches in my interface. Here are 4 potentials for a doorbell. Note, my doorbell resembles option 1 or 2, but I do know there are circular doorbell buttons as well, so there's options 3 and 4 for those as well. Feel like these are all kinda meh and could potentially resemble other things as well, so I'm interested in more feedback on which direction we should go.

## Preview

![image](https://user-images.githubusercontent.com/1015040/71547795-4fc7fc80-296a-11ea-9ebb-232693cdc563.png)
![image](https://user-images.githubusercontent.com/1015040/71547796-5787a100-296a-11ea-9fd9-def86425466b.png)
![image](https://user-images.githubusercontent.com/1015040/71547799-5fdfdc00-296a-11ea-8ca8-8456de88cf35.png)
![image](https://user-images.githubusercontent.com/1015040/71547802-679f8080-296a-11ea-8b86-928064666911.png)

## Zip Download

[doorbells.zip](https://github.com/Templarian/MaterialDesign/files/4007292/doorbells.zip)

**Comment by MrGrigri** [comment]
I believe 1 and 2 looks similar to light switch

**Comment by goyney** [comment]
[![doorbell](https://materialdesignicons.com/icon/doorbell)](https://materialdesignicons.com/icon/doorbell)
