### ISSUE TITLE
Admin and Wrench icon

### ISSUE THREAD

**Issue by mazza094** [Templarian/MaterialDesign#470]
Hi everyone, wopuld be usefull to have a Admin icon (like a crown) and a Wrench icon.

Thanks!

**Comment by CoDEmanX** [comment]
A simple crown:
![crown](https://cloud.githubusercontent.com/assets/1309249/8656885/99462ca8-299a-11e5-8262-676302c4b044.png) https://www.dropbox.com/s/j6qgefx14rs53uo/crown.svg?dl=0

[FontAwesome has a wrench](http://fontawesome.io/icon/wrench/), but maybe it could be even simpler (no fine details, primitive geometric shapes only).

**Comment by Templarian** [comment]
@CoDEmanX https://materialdesignicons.com/icon/crown (already exists)

**Comment by CoDEmanX** [comment]
Oh, did you add it a few moments ago? Otherwise I need to see an optician...

**Comment by Templarian** [comment]
https://materialdesignicons.com/history 12 days ago, so kind of new. :smile:

**Comment by CoDEmanX** [comment]
Well, I thought I checked before I created an own one - today. DOH!

**Comment by CoDEmanX** [comment]
There's a crown now and the request for a wrench is a duplicate: #319
Can be closed.

**Comment by CoDEmanX** [comment]
Btw: there will be a supervisor Icon too
https://www.google.com/design/icons/#ic_supervisor_account
