### ISSUE TITLE
message-send icon

### ISSUE THREAD

**Issue by Propaganistas** [Templarian/MaterialDesign#4701]
## Description

I'm looking for the "message" alternative of "email-send" and "email-send-outline". 

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'll be using it in a button to indicate that clicking it will dispatch a text message.

## Examples

Quick cut-paste in Paint:

![image](https://user-images.githubusercontent.com/6680176/71576204-14efd100-2af0-11ea-97e7-8f5d943fb4ca.png)

(I used `message-text` here, but of course other message variants apply as well)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71929056-c9c86480-3166-11ea-992f-994861c56211.png)![image](https://user-images.githubusercontent.com/1015040/71929068-d056dc00-3166-11ea-88f2-698b9373ec3a.png)
![image](https://user-images.githubusercontent.com/1015040/71929075-d77dea00-3166-11ea-9a5d-3a1f1583f688.png)![image](https://user-images.githubusercontent.com/1015040/71929086-dcdb3480-3166-11ea-99d7-4f62aae04972.png)

[message-arrows.zip](https://github.com/Templarian/MaterialDesign/files/4032447/message-arrows.zip)

**Comment by Propaganistas** [comment]
Fantastic work!

**Comment by Templarian** [comment]
@goyney I think this needs to use the other arrows style like in `comment-*` ?

**Comment by Templarian** [comment]
Although, we're a bit inconsistent with it, so not sure. 😕

**Comment by goyney** [comment]
> @goyney I think this needs to use the other arrows style like in `comment-*` ?

Good catch!

**Comment by goyney** [comment]
> Although, we're a bit inconsistent with it, so not sure. 😕

True, but the comment ones would fit better and be more defined. I wasn't happy with the points on the arrow on the ones above. I'll update them and get them added.

**Comment by goyney** [comment]
Found grid issues with those comment icons, so updated them too. 😄 

[![message-arrow-right](https://materialdesignicons.com/icon/message-arrow-right)](https://materialdesignicons.com/icon/message-arrow-right)[![message-arrow-right-outline](https://materialdesignicons.com/icon/message-arrow-right-outline)](https://materialdesignicons.com/icon/message-arrow-right-outline)
[![message-arrow-left](https://materialdesignicons.com/icon/message-arrow-left)](https://materialdesignicons.com/icon/message-arrow-left)[![message-arrow-left-outline](https://materialdesignicons.com/icon/message-arrow-left-outline)](https://materialdesignicons.com/icon/message-arrow-left-outline)
