### ISSUE TITLE
buffet

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4702]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
next to cabinet and a few variants( which all are vertical), we don't have an icon for a horizontally dimensioned cabinet (called Buffet where live, hope its a universal naming) Also used as audio-furnitures.

please consider? thanks!

## Examples

Include any example images so we know what the icon should look like.

![besta-tv-bench-with-drawers__0765860_PE753660_S5](https://user-images.githubusercontent.com/33354141/71580099-9438d100-2aff-11ea-9786-60add203008f.jpg)
![hemnes-tv-bench__0644455_PE702706_S5](https://user-images.githubusercontent.com/33354141/71580100-9438d100-2aff-11ea-9725-88e4c5e203a8.jpg)

**Comment by nilsfast** [comment]
![Uploading image.png…]()

![image](https://user-images.githubusercontent.com/58486458/73568518-d6d82b00-4468-11ea-8503-ec7b1fd2a060.png)

**Comment by goyney** [comment]
1dp lines aren't Material. Take a look at `cupboard` or `cabinet`. That's the style we'll likely need to match.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73570775-4d772780-446d-11ea-966f-c398e34df7b7.png)

I simplified the design and made the lines thicker.

**Comment by Mariusthvdb** [comment]
yes, thanks for tailing this up!

**Comment by goyney** [comment]
Try adding the handles just to see what that might look like.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73590665-4e4ba000-44e5-11ea-990a-9d9b35c90291.png)

**Comment by CoDEmanX** [comment]
Seems pretty flat, how about making it slightly larger?

![grafik](https://user-images.githubusercontent.com/1309249/73593379-ee182680-4503-11ea-9dac-9deccda3b70b.png)

**Comment by nilsfast** [comment]
Higher?

**Comment by CoDEmanX** [comment]
Yeah, I meant vertically larger (higher, taller). Not sure if you still consider it a buffet with that aspect ratio however. The flatter version looks more like a tv low board to me - or is that what you call a buffet? In the tv series "Living with yourself" they feature a buffet, but it's more like a dresser / waist-high cabinet in the corridor.

BTW. WDYT about round handles?

![grafik](https://user-images.githubusercontent.com/1309249/73593442-b8c00880-4504-11ea-85ec-87b91e4a3c5f.png)

**Comment by nilsfast** [comment]
I am form Germany and have also no idea how a buffet is defined. I think a buffet is a bunch of drawers on legs.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73596397-24649e80-4522-11ea-864e-f41f872a876f.png)

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73596586-92f62c00-4523-11ea-9ed4-dd2da230c746.png)

Here is a variation with a mirror :)

**Comment by Templarian** [comment]
The others introduce unneeded complexity. I think simply using the two drawer design with rounded works the best.

With that said I think there is a lot of opportunities for variations (TV / photo frame above). Please create issues for these as it could represent a living room.

**Comment by Mariusthvdb** [comment]
thanks for all the work, looking forward to using it!
