### ISSUE TITLE
Football icons

### ISSUE THREAD

**Issue by tsvetann** [Templarian/MaterialDesign#4703]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage & Examples

Sport apps can benefit from sport icons such as a ball, penalty cards, corners

**Comment by JapanYoshi** [comment]
I think these are definitely too niche.

**Comment by goyney** [comment]
We already have several sports ball variations and things like square which can be used for a card. Not sure what you mean by corners, but I'm inclined to agree with @JapanYoshi on this request being a little too niche.

**Comment by JamesCoyle** [comment]
We have a football and pitch:
[![](https://materialdesignicons.com/icon/soccer)](https://materialdesignicons.com/icon/soccer)[![](https://materialdesignicons.com/icon/soccer-field)](https://materialdesignicons.com/icon/soccer-field)

This may work for cards but we could perhaps do with `card-portrait` and variants:
[![](https://materialdesignicons.com/icon/cards
)](https://materialdesignicons.com/icon/cards)

This may work for corners though I personally feel this could be tweaked to look more flag like:
[![](https://materialdesignicons.com/icon/flag-triangle
)](https://materialdesignicons.com/icon/flag-triangle)

**Comment by Templarian** [comment]
Yeah, going to say we close this unless someone can find some concrete examples that differ from our existing icons.
