### ISSUE TITLE
Bulma

### ISSUE THREAD

**Issue by mtpiercey** [Templarian/MaterialDesign#4704]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I really enjoy the [Bulma](https://bulma.io/) CSS framework, and while I understand that brand icons are no longer a focus of this project - I think the Bulma icon would make a nice addition since it's a popular framework and the logo is fairly recognizable. Thoughts?

## Examples

From the official website: (The teal "B" part could work)

![image](https://user-images.githubusercontent.com/22581026/71645940-90e34800-2cad-11ea-8c92-df9c30fb0899.png)

The folks at svgporn have an SVG version too, at https://cdn.svgporn.com/logos/bulma.svg

![Image](https://cdn.svgporn.com/logos/bulma.svg)

**Comment by PeterShaggyNoble** [comment]
An official SVG can be found at https://bulma.io/favicons/safari-pinned-tab.svg

**Comment by PeterShaggyNoble** [comment]
[![bulma](https://user-images.githubusercontent.com/15157491/71721152-fa816480-2e1b-11ea-90b7-9186573d9a89.png)](https://github.com/Templarian/MaterialDesign/files/4018923/bulma.zip)

**Comment by goyney** [comment]
[![bulma](https://materialdesignicons.com/icon/bulma)](https://materialdesignicons.com/icon/bulma)
