### ISSUE TITLE
label-percent, label-percent-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4705]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To indicate the product is discounted.

## Examples

![label-percent](https://user-images.githubusercontent.com/6717356/71719693-2f97b200-2e30-11ea-92a6-996882f31efd.png)
![label-percent-outline](https://user-images.githubusercontent.com/6717356/71719698-31fa0c00-2e30-11ea-9325-b7706731cd9e.png)

**Comment by goyney** [comment]
[![label-percent](https://materialdesignicons.com/icon/label-percent)](https://materialdesignicons.com/icon/label-percent)
