### ISSUE TITLE
not-applicable (N/A)

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#4706]
It would be nice to have an N/A icon to represent "not available" or "not applicable" etc. I based this design on [ab-testing](https://materialdesignicons.com/icon/ab-testing)

![download](https://user-images.githubusercontent.com/1837101/71736708-031f6e00-2e0f-11ea-8ccd-cb93b9dfc9fd.png)

[NA.svg.zip](https://github.com/Templarian/MaterialDesign/files/4020012/NA.svg.zip)

**Comment by Templarian** [comment]
Not a huge fan of this design for `not-applicable`. I like the idea of adding this icon, but needs to be different where it looks more like `N/A`.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/71801479-ab585100-3020-11ea-96bf-dfef37f21ce0.png)

Might be better to make the letters a little larger. This might be tweaked a little more.

**Comment by JapanYoshi** [comment]
I am opposed to these text-based, language-specific icons in general. And as long as #4353 remains rejected, I find it only fair to reject this in favor of a graphical representation.

**Comment by JamesCoyle** [comment]
I agree with that. I can't really see a use-case for this in an application that couldn't be easily done with text.

**Comment by Xenomorph99** [comment]
I forgot about the issues that would arise due to app translation. I think @JapanYoshi is correct. It should simply be a graphical representation not text-based.
