### ISSUE TITLE
square-off-outline & rounded-square-off-outline

### ISSUE THREAD

**Issue by nickarvanitas** [Templarian/MaterialDesign#4708]
**I have:**

 Searched all issues to make sure there isn't a request for this icon.
 Searched the current library to make sure the icon doesn't exist.
 Only requested a single icon (or a few near-identical ones) in this issue.
**Usage**
To indicate that a box is disabled or that nothing has been selected. We personally use this icon for a color picker where a color has not been selected. 

**Examples**

![rounded-square-off-outline](https://user-images.githubusercontent.com/46571851/71750220-04639180-2e35-11ea-90ed-c78df199d0e2.png)
![square-off-ouline](https://user-images.githubusercontent.com/46571851/71750221-04639180-2e35-11ea-94e8-c926c88d50ad.png)

[square-off-outline.zip](https://github.com/Templarian/MaterialDesign/files/4020966/square-off-outline.zip)

**Comment by some1awesome** [comment]
This would be great!  We would use this icon for an app I'm working on.

**Comment by goyney** [comment]
[![square-off](https://materialdesignicons.com/icon/square-off)](https://materialdesignicons.com/icon/square-off)[![square-off-outline](https://materialdesignicons.com/icon/square-off-outline)](https://materialdesignicons.com/icon/square-off-outline)

**Comment by goyney** [comment]
[![checkbox-blank-off-outline](https://materialdesignicons.com/icon/checkbox-blank-off-outline)](https://materialdesignicons.com/icon/checkbox-blank-off-outline)[![checkbox-blank-off](https://materialdesignicons.com/icon/checkbox-blank-off)](https://materialdesignicons.com/icon/checkbox-blank-off)
