### ISSUE TITLE
Update my contributor profile

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4709]
It's been a while, and I've moved on to a newer username and changed my Twitter account name.

## From:
> JapanYoshi \@japanyoshilol
> Also known as theFIZZYnator around the internet.

## To:
> Haley Halcyon \@itsspelledhaley
> Also known as theFIZZYnator around the internet.

## Profile picture:
![haleyhalcyon-layer3](https://user-images.githubusercontent.com/8707990/71764360-40c4e980-2f2a-11ea-97d4-3d2faa052f34.png)

**Comment by Templarian** [comment]
Check slack on how you can update your profile photo. Not something I handle.
