### ISSUE TITLE
"Inline SVG for HTML" uses unofficial style attributes for width/height

### ISSUE THREAD

**Issue by dlew** [Templarian/MaterialDesign#471]
The "Inline SVG for HTML" defines its width/height using the `style` attribute, but as far as I can tell those attributes are not supported as style attributes for SVGs:

1. [This page](http://www.w3.org/TR/SVG/styling.html#SVGStylingProperties) lists out all the SVG styling properties, which does not include `width` nor `height`.
1. [This page](http://www.w3.org/TR/SVG/propidx.html) is another view of supported attributes that does not include it. (Though it specifies that it's not normative.)

This came up as a result of people trying to use [Victor](https://github.com/trello/victor/) with this file format (see more details here: https://github.com/trello/victor/issues/20).

I understand that people shouldn't be using "for HTML" SVGs with Android. The only reason I bring this up is because, after investigating it myself, it seems like `width`/`height` is invalid all cases. My knowledge of SVGs is far from complete, though, so feel free to correct me if I'm wrong.

**Comment by Templarian** [comment]
http://www.w3.org/TR/SVG/styling.html#UAStyleSheet

Every browser supports `width` and `height`. I wouldn't overthink it.
