### ISSUE TITLE
IoBroker Icon

### ISSUE THREAD

**Issue by klotzma** [Templarian/MaterialDesign#4710]
Because Lovelace now also works under IoBroker and it uses the mdi icons, it would be nice to create an icon for Iobroker.

[Link from the Logo](https://github.com/ioBroker/ioBroker/blob/master/img/ioBrokerLogoSmall.png)

Thanks in advance

Marcus

![ioBrokerLogoSmall](https://user-images.githubusercontent.com/45261052/71779513-2422c300-2fb7-11ea-9c22-73fa7a6c3363.png)

**Comment by PeterShaggyNoble** [comment]
SVG here: https://github.com/ioBroker/awesome-iobroker/blob/master/images/awesome-iobroker.svg

**Comment by PeterShaggyNoble** [comment]
[![iobroker](https://user-images.githubusercontent.com/15157491/71816527-c6f04580-307a-11ea-831a-b2a916bb7353.png)](https://github.com/Templarian/MaterialDesign/files/4025921/iobroker.zip)

**Comment by goyney** [comment]
[![iobroker](https://materialdesignicons.com/icon/iobroker)](https://materialdesignicons.com/icon/iobroker)
