### ISSUE TITLE
Open Container Initiative Icon

### ISSUE THREAD

**Issue by muskrat1337** [Templarian/MaterialDesign#4711]
Requesting an icon for OCI as an alternative to the docker icon

A square with Ci in the center.

https://www.opencontainers.org/wp-content/uploads/sites/10/2016/10/logo_oci.png

**Comment by PeterShaggyNoble** [comment]
SVG here: https://github.com/opencontainers/artwork/blob/master/oci/icon/black/oci-icon-black.svg

**Comment by PeterShaggyNoble** [comment]
[![open-containers-initiative](https://user-images.githubusercontent.com/15157491/71817046-8bef1180-307c-11ea-9b93-a4b731133ab7.png)](https://github.com/Templarian/MaterialDesign/files/4025954/open-containers-initiative.zip)

**Comment by goyney** [comment]
[![oci](https://materialdesignicons.com/icon/oci)](https://materialdesignicons.com/icon/oci)

**Comment by PeterShaggyNoble** [comment]
@muskrat1337, if you have a minute could you provide some feedback on [SI#2279](https://github.com/simple-icons/simple-icons/issues/2279), please?
