### ISSUE TITLE
database-marker

### ISSUE THREAD

**Issue by moovida** [Templarian/MaterialDesign#4712]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Info

For the GIS part, it would be great to have a spatial database icon. That would be achieved by adding the geo-marker to the current database icon. 

I see that other people than the author contributed database modes. Should I (in case) contribute the geo-mode or is this issue ok like this?

Thanks.

**Comment by Templarian** [comment]
It's a standard cut out overlay we use for the map marker in the corner. So probably easier for one of us to create it, but yea generally anyone can attach a .svg file (as a zip) to an issue for us to review/add. 😃

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/71927502-9f28dc80-3163-11ea-98d0-549a8bd1b154.png)
[database-marker.svg.zip](https://github.com/Templarian/MaterialDesign/files/4032368/database-marker.svg.zip)

**Comment by MohammadKhrram** [comment]
i need map-marker-(remove,plus)-outline
please design for me and put in materialdesignicons.com
Thanks

**Comment by JamesCoyle** [comment]
Please open a new icon request issue if you wish to request new icons. This issue is for tracking database-marker only.

**Comment by MohammadKhrram** [comment]
> Please open a new icon request issue if you wish to request new icons. This issue is for tracking database-marker only.

Thanks for help...
Please show me the link for *request new icon*

**Comment by goyney** [comment]
[![database-marker](https://materialdesignicons.com/icon/database-marker)](https://materialdesignicons.com/icon/database-marker)
