### ISSUE TITLE
Disney+ icon

### ISSUE THREAD

**Issue by TurboTronix** [Templarian/MaterialDesign#4713]
Can anyone create a Disney+ icon, want to use it with my remote.

Something like: https://www.kindpng.com/picc/m/10-100798_transparent-swot-clipart-walt-disney-logo-png-png.png

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by Templarian** [comment]
That's not the Disney plus logo, but for other reasons we can't add it...

- It's Disney, so no way we're touching that legal headache. 🤣
- They don't provide a small square sized logo, only the full sized design.
