### ISSUE TITLE
apple-homepod

### ISSUE THREAD

**Issue by douzs** [Templarian/MaterialDesign#4714]
hello,
i want a icon of homepod,and i have a svg,but i don't know  how to create a icon like mdi:homepod by using svg
the svg is 
 path fill="#789" d="M21.12,18.43c0,0.38-3.19,0.68-7.12,0.68s-7.12-0.31-7.12-0.68 c0-0.38,3.19-0.68,7.12-0.68S21.12,18.06,21.12,18.43z M22.19,18.81c-0.16,0.46-1.21,1.15-8.19,1.15s-8.03-0.69-8.19-1.15 C2.52,19.38,0,21.87,0,25.31v17.97c0,3.45,2.54,6.33,5.84,6.88c0.24,0.46,1.52,1.08,8.16,1.08s7.92-0.63,8.16-1.08 c3.3-0.56,5.84-3.44,5.84-6.88V25.31C28,21.87,25.48,19.38,22.19,18.81z" 

hope you can help me 
thank you

**Comment by Templarian** [comment]
Seems like a few extra steps to move it over here to reject, but we're not adding device specific icons. There are just too many and they change designs every other year.

**Comment by douzs** [comment]
> Seems like a few extra steps to move it over here to reject, but we're not adding device specific icons. There are just too many and they change designs every other year.

ok,i knew it ,thank you
