### ISSUE TITLE
map-marker-[plus|remove]-outline

### ISSUE THREAD

**Issue by MohammadKhrram** [Templarian/MaterialDesign#4715]
I need the following icons:
<b>map-marker-plus-outline</b>
<b>map-marker-remove-outline</b>
<b>tag-multiple-outline</b>

Please design specified icons
Thanks...

**Comment by JamesCoyle** [comment]
Please do not delete the issue template. If you request any new icons we need examples of what it could look like and examples of how it would be used.

**Comment by goyney** [comment]
[![map-marker-plus-outline](https://materialdesignicons.com/icon/map-marker-plus-outline)](https://materialdesignicons.com/icon/map-marker-plus-outline)[![map-marker-minus-outline](https://materialdesignicons.com/icon/map-marker-minus-outline)](https://materialdesignicons.com/icon/map-marker-minus-outline)
[![map-marker-remove-outline](https://materialdesignicons.com/icon/map-marker-remove-outline)](https://materialdesignicons.com/icon/map-marker-remove-outline)

**Comment by goyney** [comment]
[![tag-multiple-outline](https://materialdesignicons.com/icon/tag-multiple-outline)](https://materialdesignicons.com/icon/tag-multiple-outline)

**Comment by MohammadKhrram** [comment]
Special thanks <b>Michael Irigoyen</b>

**Comment by goyney** [comment]
> Thanks soooooooo much Michael Irigoyen

No problem. But, please try to use our Icon Request issue templates in the future. We're starting to get more stringent about requests that are freeform and they're more likely to just be immediately closed. 😄
