### ISSUE TITLE
Salesman

### ISSUE THREAD

**Issue by lohhans** [Templarian/MaterialDesign#4716]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I need a icon to identify a salesman.

## Examples

I need a new look like the "account" icon.

**Comment by JamesCoyle** [comment]
I'm not really sure how we would show this other than something like `account-tie`.
[![](https://materialdesignicons.com/icon/account-tie)](https://materialdesignicons.com/icon/account-tie)

**Comment by lohhans** [comment]
Maybe with a suitcase...

**Comment by Templarian** [comment]
We have something like that, but not with account as the main with a smaller briefcase. hmm...

[![briefcase-account](https://materialdesignicons.com/icon/briefcase-account)](https://materialdesignicons.com/icon/briefcase-account) [![briefcase-account](https://materialdesignicons.com/icon/briefcase-account-outline)](https://materialdesignicons.com/icon/briefcase-account-outline)

**Comment by Templarian** [comment]
Tried a couple ideas, the briefcase due to the wide width doesn't work well when placed next to our cut out with the `account`. 😕

**Comment by lohhans** [comment]
Even on side? Like account-arrow-left...
<img src="https://materialdesignicons.com/icon/account-arrow-left" style="max-width:100%;">

**Comment by goyney** [comment]
`account-tie` or `briefcase-account` are going to be your best bets for this use case. Thanks for your suggestion.
