### ISSUE TITLE
external-link-alt

### ISSUE THREAD

**Issue by edilsonlsouza** [Templarian/MaterialDesign#4717]
Very used in Brazil.

**Comment by JamesCoyle** [comment]
Please use the [issue template](https://github.com/Templarian/MaterialDesign/issues/new?labels=Icon+Request&template=1_icon_request.md) to request new icons. We are going to need some examples of what you mean.

**Comment by goyney** [comment]
When you click "New Issue," please select "Request an Icon" and fill out the template. We are no longer addressing blank issues.
