### ISSUE TITLE
Looking for icon: external-link-alt

### ISSUE THREAD

**Issue by edilsonlsouza** [Templarian/MaterialDesign#4719]
Hello,

Sorry for the post error, I came from a deep link to request an icon.

So what I need is this link icon below:

https://fontawesome.com/icons/external-link-alt?style=solid

Thanks!

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/open-in-new
)](https://materialdesignicons.com/icon/open-in-new)

**Comment by edilsonlsouza** [comment]
Thanks, but that's not it, see the arrow overlaps.

**Comment by edilsonlsouza** [comment]
Calm down buddy. Do not close until we signal ok, the answer. Thanks!

**Comment by MrGrigri** [comment]
@edilsonlsouza, we follow strict Material Design guidelines. The Font Awesome icon that you have request is the same representation of our own `open-in-new`. We understand that the arrow doesn't extend past the box, but this is a Google icon and it will not be changed. We also will not be adding a variant for this.
