### ISSUE TITLE
Weather-Fog Icon request

### ISSUE THREAD

**Issue by RobinSmits** [Templarian/MaterialDesign#472]
Hi Austin,

Would it be possible for you to create a Fog icon as part of all the weather icons you already have?
I'am using them in a weather app that I created.

I like your work very much :-)

Thanks in advance.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/weather-fog

**Comment by CoDEmanX** [comment]
Maybe also a weather warning icon?

![weather-warning-alternative](https://cloud.githubusercontent.com/assets/1309249/8761349/49aadeb2-2d4d-11e5-88fa-a488efa96d3b.png)

![weather-warning](https://cloud.githubusercontent.com/assets/1309249/8761329/687c9ae8-2d4c-11e5-95e7-3a9ea086e92f.png)

(latter has a rounded exclamation mark, making it slightly less legible at 24x24)

**Comment by Templarian** [comment]
I think one of the general alert icon / variations would work best for that. In context it would suffice better than trying to fit a exclamation into a cloud.

**Comment by RobinSmits** [comment]
In windows Phone I would use a flip tile…alert icon on one side….the specific weather about which it is on the other side.

Should be fine enough for me. 😊


Thanks for the idea though.


Robin.






Verzonden met Windows Mail





Van: Austin Andrews
Verzonden: ‎zondag‎ ‎19‎ ‎juli‎ ‎2015 ‎10‎:‎19
Aan: Templarian/MaterialDesign
CC: RobinSmits





I think one of the general alert icon / variations would work best for that. In context it would suffice better than trying to fit a exclamation into a cloud.
