### ISSUE TITLE
map-marker-[check|radius]-outline

### ISSUE THREAD

**Issue by MohammadKhrram** [Templarian/MaterialDesign#4724]
I need the following icons:

<b>map-marker-check-outline</b>
<b>map-marker-radius-outline</b>

Please design specified icons
Thanks...

**Comment by goyney** [comment]
[![map-marker-radius-outline](https://materialdesignicons.com/icon/map-marker-radius-outline)](https://materialdesignicons.com/icon/map-marker-radius-outline)[![map-marker-check-outline](https://materialdesignicons.com/icon/map-marker-check-outline)](https://materialdesignicons.com/icon/map-marker-check-outline)

**Comment by MohammadKhrram** [comment]
Thanks so much... <b>goyney</b>
