### ISSUE TITLE
Bunk bed

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4725]
Inspired by FontAwesome: https://fontawesome.com/icons/bed-bunk?style=solid

## Preview

![grafik](https://user-images.githubusercontent.com/1309249/72118502-9695f900-3351-11ea-9610-88720f89e5a7.png)

## Zip Download

[hotel-bunk2.zip](https://github.com/Templarian/MaterialDesign/files/4043477/hotel-bunk2.zip)

**Comment by goyney** [comment]
[![bunk-bed](https://materialdesignicons.com/icon/bunk-bed)](https://materialdesignicons.com/icon/bunk-bed)
