### ISSUE TITLE
account-convert-outline (+tweak for solid icon)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4726]
The existing `account-convert` icon doesn't really allow for an outline variant:

![grafik](https://user-images.githubusercontent.com/1309249/72119324-5a17cc80-3354-11ea-8c90-4aeb0ed3cd3f.png)

But the icon could be tweaked a little (using the person from `account-network`, current icon in red):

![grafik](https://user-images.githubusercontent.com/1309249/72119405-9b0fe100-3354-11ea-8382-e3496218efdf.png)

![grafik](https://user-images.githubusercontent.com/1309249/72119298-43717580-3354-11ea-90e2-f4dcdf3487c3.png)

[account-convert-outline.zip](https://github.com/Templarian/MaterialDesign/files/4043561/account-convert-outline.zip)

**Comment by goyney** [comment]
[![account-convert](https://materialdesignicons.com/icon/account-convert)](https://materialdesignicons.com/icon/account-convert)[![account-convert-outline](https://materialdesignicons.com/icon/account-convert-outline)](https://materialdesignicons.com/icon/account-convert-outline)
