### ISSUE TITLE
Beer-outline

### ISSUE THREAD

**Issue by glynnallen1704** [Templarian/MaterialDesign#4727]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by CoDEmanX** [comment]
It's unclear what you are looking for. Just an empty glass? Or an outlined liquid?

![grafik](https://user-images.githubusercontent.com/1309249/72196398-12f30f80-3418-11ea-8cad-61c1351d2e2c.png)

![grafik](https://user-images.githubusercontent.com/1309249/72196392-07074d80-3418-11ea-9742-32fb90310173.png)

![grafik](https://user-images.githubusercontent.com/1309249/72196374-fa82f500-3417-11ea-8181-5c2f3ca70fec.png)

While we are at it, we should consider adding outlined variants of the cup and coffee-to-go icons:

![grafik](https://user-images.githubusercontent.com/1309249/72196409-2d2ced80-3418-11ea-9bca-05e2276a4bbe.png)

![grafik](https://user-images.githubusercontent.com/1309249/72196522-0d49f980-3419-11ea-964f-6f63428c5db5.png)

For the other glass and mug icons it doesn't make sense to me to provide outlined versions however, as they are meant as microset to distinguish different kinds of drinking vessels.

The wine-bottle perhaps?

![grafik](https://user-images.githubusercontent.com/1309249/72196642-269f7580-341a-11ea-957c-34a711f8a12a.png)

@MrGrigri gave up on soda-bottle-classic https://github.com/Templarian/MaterialDesign/issues/237#issuecomment-511868648 and I can totally see why. For a consistent stroke width, the inner sides need to touch, making it look really odd

![grafik](https://user-images.githubusercontent.com/1309249/72196864-9d893e00-341b-11ea-95d3-7d6110fa1dff.png)

Tweaked, but still not satisfactory:

![grafik](https://user-images.githubusercontent.com/1309249/72196842-6e72cc80-341b-11ea-8938-082ee0827d67.png)

It would require a change of the base icon, but that would probably make it look to wide to give it enough space for the outline variant.

[drinking-vessels-outline.zip](https://github.com/Templarian/MaterialDesign/files/4048834/drinking-vessels-outline.zip)

**Comment by goyney** [comment]
[![beer-outline](https://materialdesignicons.com/icon/beer-outline)](https://materialdesignicons.com/icon/beer-outline)[![glass-pint-outline](https://materialdesignicons.com/icon/glass-pint-outline)](https://materialdesignicons.com/icon/glass-pint-outline)
[![coffee-to-go-outline](https://materialdesignicons.com/icon/coffee-to-go-outline)](https://materialdesignicons.com/icon/coffee-to-go-outline)[![cup-outline](https://materialdesignicons.com/icon/cup-outline)](https://materialdesignicons.com/icon/cup-outline)
[![bottle-wine-outline](https://materialdesignicons.com/icon/bottle-wine-outline)](https://materialdesignicons.com/icon/bottle-wine-outline)

**Comment by glynnallen1704** [comment]
Perfec the one labelled beer-outline is exactly what i was looking for.

**Comment by CoDEmanX** [comment]
Hm, the wine bottle is pretty narrow. Should we make it wider?

![grafik](https://user-images.githubusercontent.com/1309249/72691793-53454280-3b28-11ea-91ac-a4b015dc9dca.png)

I think it needs some more tuning to better match the solid variant.

A wider soda-classic as outline variant, with some tuning applied:

![grafik](https://user-images.githubusercontent.com/1309249/72691634-38260300-3b27-11ea-801f-5941cde05288.png)

![grafik](https://user-images.githubusercontent.com/1309249/72691850-b33be900-3b28-11ea-9df9-ffee0085d7fe.png)

**Comment by goyney** [comment]
@CoDEmanX This issue was already released, can you create a new issue to address your other changes to keep the concerns separate?
