### ISSUE TITLE
"earth" and "key" with outgoing arrow

### ISSUE THREAD

**Issue by wolframroesler** [Templarian/MaterialDesign#4729]
I have:

- [x] [Searched all issues]() to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm in the process of converting the KeePassXC password safe to Material Design icons (details in https://github.com/keepassxreboot/keepassxc/issues/475 and https://github.com/keepassxreboot/keepassxc/pull/4066). For the toolbar we need icons for "copy user name to clipboard", "copy password to clipboard" and "copy URL to clipboard". So far we're using rather generic person/key/earth icons, like this (the 6th to 8th icon from the left):

![toolbar](https://user-images.githubusercontent.com/25565229/71771751-c9e71b00-2f40-11ea-99dd-f1e45a5c42fc.png)

That's not too bad but we'd like to have something that indicates "copy to clipboard". One idea is to use `account-arrow-right-outline` (which displays a person with an outgoing arrow) for "copy user name", and my request is to add equivalent variations of `key` and `earth`.

## Examples

Take `account-arrow-right-outline`:

![account-arrow-right-outline](https://user-images.githubusercontent.com/25565229/71772033-47f8f100-2f44-11ea-85d9-ad7175434d78.png)

and replace the person with the `key` and `earth`, respectively.

**Comment by goyney** [comment]
[![earth-arrow-right](https://materialdesignicons.com/icon/earth-arrow-right)](https://materialdesignicons.com/icon/earth-arrow-right)[![key-arrow-right](https://materialdesignicons.com/icon/key-arrow-right)](https://materialdesignicons.com/icon/key-arrow-right)

**Comment by wolframroesler** [comment]
Awesome, and incredibly fast. Thanks a lot!

**Comment by goyney** [comment]
No problem! We like well defined use cases. 😄

**Comment by wolframroesler** [comment]
FYI here's how KeePassXC looks with Material Design icons. Big thanks for your awesome work.

![Screenshot from 2020-01-11 17-45-50](https://user-images.githubusercontent.com/25565229/72207521-51c9a980-349a-11ea-8185-767003463504.png)

For reference: https://github.com/keepassxreboot/keepassxc/issues/475

**Comment by droidmonkey** [comment]
Very nice! Thank you
