### ISSUE TITLE
blood-bag

### ISSUE THREAD

**Issue by kazaky** [Templarian/MaterialDesign#473]

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/water Kind of like blood droplet.

![water-bag](https://cloud.githubusercontent.com/assets/338885/8470167/5e0f06ac-204c-11e5-837c-25bc449cd9bc.png)

Does the above icon look like a bag? (I'm going to call it `water-bag` when it gets added).

**Comment by kazaky** [comment]
Thank you, Nice one
But i mean more like the traditional blood bag
http://cache.pakistantoday.com.pk/bloodbagnotext-0001.jpg

**Comment by CoDEmanX** [comment]
Not a trivial one, because it's very hard to convey that it's blood and not an infusion or the like (unless you color the icon red). See Google Image search for `blood bag icon`.

**Comment by goyney** [comment]
Here's my attempt:
![image](https://user-images.githubusercontent.com/1015040/48751054-5b69cf80-ec50-11e8-9c92-ead126a0b002.png)

[blood-bag.zip](https://github.com/Templarian/MaterialDesign/files/2598042/blood-bag.zip)

**Comment by PeterShaggyNoble** [comment]
@goyney, I think, in context, your suggestion could work well.

**Comment by JamesCoyle** [comment]
I say we add @goyney's icon to close this out.

**Comment by Templarian** [comment]
[![blood-bag](https://materialdesignicons.com/icon/blood-bag)](https://materialdesignicons.com/icon/blood-bag)
