### ISSUE TITLE
Update Yahoo!

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4730]
[![yahoo](https://user-images.githubusercontent.com/15157491/72204743-28e1ee00-3473-11ea-9b6f-c5c93b650c1a.png)](https://github.com/Templarian/MaterialDesign/files/4049356/yahoo.zip)

**Source:** https://s.yimg.com/cv/apiv2/default/icons/favicon_y19_32x32_custom.svg

**Comment by goyney** [comment]
[![yahoo](https://materialdesignicons.com/icon/yahoo)](https://materialdesignicons.com/icon/yahoo)
