### ISSUE TITLE
currency-eur-off

### ISSUE THREAD

**Issue by CyrilAntoni** [Templarian/MaterialDesign#4731]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Similar to the use of `currency-usd` and `currency-usd-off`. The `currency-euro-off` would be a crossed-through euro symbol to indicate that an item or service is free.

## Examples

The `currency-euro-off` icon should look like the `currency-usd-off` but using the euro symbol instead of the dollar symbol. Here is the link to the original icon: [https://materialdesignicons.com/icon/currency-usd-off](https://materialdesignicons.com/icon/currency-usd-off)

Thank you.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/72306698-123fc080-3646-11ea-9676-b1088dc49808.png)
[currency-eur-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/4056893/currency-eur-off.svg.zip)

**Comment by goyney** [comment]
[![currency-eur-off](https://materialdesignicons.com/icon/currency-eur-off)](https://materialdesignicons.com/icon/currency-eur-off)

**Comment by CyrilAntoni** [comment]
Wow, that was quick! Thank you for the great job @goyney!

Do you know when the next version will be released?
