### ISSUE TITLE
television-ambient-light

### ISSUE THREAD

**Issue by pichlerralf** [Templarian/MaterialDesign#4732]
I have:

- [X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I use a light behind my TV (kind of ambilight) and would suggest a dedicated icon for a TV (ambi-)light. So this can differ in the UI's a bit from a 'normal' light icon.

Thanks in advance for thinking about my suggestion!

Regards,
Ralf

**Comment by GreenTurtwig** [comment]
Do you have any examples?

**Comment by JamesCoyle** [comment]
Could maybe try shrink `television` a bit and add the glow markers from `lightbulb-on` around it. Might look a bit daft though.
[![](https://materialdesignicons.com/icon/television)](https://materialdesignicons.com/icon/television)
[![](https://materialdesignicons.com/icon/lightbulb-on)](https://materialdesignicons.com/icon/lightbulb-on)/

**Comment by goyney** [comment]
Something like...
![image](https://user-images.githubusercontent.com/1015040/72307160-6ac38d80-3647-11ea-8646-9a4959518a0d.png)
[television-ambient-light.svg.zip](https://github.com/Templarian/MaterialDesign/files/4056943/television-ambient-light.svg.zip)

**Comment by goyney** [comment]
[![television-ambient-light](https://materialdesignicons.com/icon/television-ambient-light)](https://materialdesignicons.com/icon/television-ambient-light)

**Comment by pichlerralf** [comment]
Thanks for the icon!
