### ISSUE TITLE
Consider using fill="currentColor" instead of fill="#000000" (black)

### ISSUE THREAD

**Issue by limonte** [Templarian/MaterialDesign#4733]
Consider using `fill="currentColor"` instead of `fill="#000000"` so icons will inherit the color. Font Awesome is using `fill="currentColor"` in their SVGs.

![image](https://user-images.githubusercontent.com/6059356/72264798-fa574500-3623-11ea-85b2-d851ce1bde75.png)

**Comment by Templarian** [comment]
Good idea. I'll update this shortly.

**Comment by Templarian** [comment]
Updated!

Thanks @limonte

**Comment by limonte** [comment]
That was fast, thank you @Templarian!
