### ISSUE TITLE
format-color-marker-cancel

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4735]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/72280990-958df180-3607-11ea-9180-57d90508cf1d.png)

## Zip Download

[format-color-marker-cancel.svg.zip](https://github.com/Templarian/MaterialDesign/files/4055070/format-color-marker-cancel.svg.zip)

---

This goes along with our `format-color-[fill|highlight|text]` icons and leaves a space for the `color-helper`. Its use case is for choosing the color of a redaction. Colorized redactions are common to categorize why things have been redacted.

**Comment by CoDEmanX** [comment]
Doesn't the modifier overlay the marker overly much? Why not place it +2dp to the right?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/72306557-888ff300-3645-11ea-9832-7df0e7a9f2f2.png)
[format-color-marker-cancel.svg.zip](https://github.com/Templarian/MaterialDesign/files/4056883/format-color-marker-cancel.svg.zip)

**Comment by goyney** [comment]
[![format-color-marker-cancel](https://materialdesignicons.com/icon/format-color-marker-cancel)](https://materialdesignicons.com/icon/format-color-marker-cancel)
