### ISSUE TITLE
Lock + Download

### ISSUE THREAD

**Issue by jordyamc** [Templarian/MaterialDesign#4736]
I have:

- [ X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For example, when you have an app where you use inapp purchase to download something, or suscriptions, or account levels

## Examples
Like any other locked icon, but with download

![Anotación 2020-01-13 210845](https://user-images.githubusercontent.com/6831873/72311022-fdb0f780-3648-11ea-9e41-e79756d814a2.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/72548114-47693000-384b-11ea-9c50-959b5a2e326f.png) ![image](https://user-images.githubusercontent.com/4528551/72548119-4a642080-384b-11ea-8b1e-82e56b57c2fa.png)

## Files

[download-lock.zip](https://github.com/Templarian/MaterialDesign/files/4072757/download-lock.zip)

**Comment by goyney** [comment]
[![download-lock](https://materialdesignicons.com/icon/download-lock)](https://materialdesignicons.com/icon/download-lock)[![download-lock-outline](https://materialdesignicons.com/icon/download-lock-outline)](https://materialdesignicons.com/icon/download-lock-outline)
