### ISSUE TITLE
Twitter logo is missing at Chrome browser

### ISSUE THREAD

**Issue by hapdesmith** [Templarian/MaterialDesign#4737]
Browser version Chrome Version 79.0.3945.88 (Official Build) (64-bit), i just update my Chrome and the issue is still there

I think it's the browser because I try to check it with safari. there is no problem.

there is no problem with network too
![image](https://user-images.githubusercontent.com/3312461/72312584-207bf400-36bb-11ea-8e10-0e1bb3ed5cb0.png)

**Comment by Templarian** [comment]
Can you retry with incognito. Just to make sure it's not an extension issue. 99% of the time this happens it's due to something blocking a CSS class too loosely.

**Comment by goyney** [comment]
I cannot reproduce this. I'm on Chrome Version 79.0.3945.117 (Official Build) (64-bit).

**Comment by hapdesmith** [comment]
Yup, turn out it's because one of my extension. Sorry for the trouble. Keep up the good work, you guys rocks.

**Comment by Templarian** [comment]
@hapdesmith If you can report it as a bug to the extension author. 👍
