### ISSUE TITLE
compare-remove

### ISSUE THREAD

**Issue by asssc** [Templarian/MaterialDesign#4738]
## Usage

Remove something from compare list.

## Examples

![compare-remove](https://user-images.githubusercontent.com/13476320/72345145-030f5000-36e4-11ea-8e17-ae14f47913bf.png)

**Comment by MrGrigri** [comment]
What would the purpose of this request? Wouldn't a simple `close` icon work? Why does it have to be directly associated with the `compare` icon?

**Comment by asssc** [comment]
@MrGrigri 
Imagine a button with an icon that adds something to the comparison list, when we click on the button, it changes its state and pressing it again should remove the item from the comparison list and the icon should be different.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73591149-4bec4480-44eb-11ea-8bbe-e246427b9653.png)

**Comment by CoDEmanX** [comment]
Maybe not suitable for the specific use case, but would inverted variant make sense? As in horizontally flipped, except that the vertical line stays in place:

![grafik](https://user-images.githubusercontent.com/1309249/73593636-8d3e1d80-4506-11ea-8d18-449f48269cc7.png)

**Comment by goyney** [comment]
[![compare-remove](https://materialdesignicons.com/icon/compare-remove)](https://materialdesignicons.com/icon/compare-remove)
