### ISSUE TITLE
Add image to album

### ISSUE THREAD

**Issue by mevcloud** [Templarian/MaterialDesign#474]
I would like to request an icon for "Add image to icon" action

**Comment by CoDEmanX** [comment]
Like `file-image` with a small `+`?

**Comment by mevcloud** [comment]
Yes, exactly

Sent from my iPhone

On 13 Jul 2015, at 17:31, CoDEmanX <notifications@github.com<mailto:notifications@github.com>> wrote:


Like file-image with a small +?

**Comment by vickychijwani** [comment]
+1 for this, would also be useful for "upload an image".

**Comment by donhurickerby** [comment]
+1

**Comment by GreenTurtwig** [comment]
Closing as https://github.com/Templarian/MaterialDesign/issues/2339 has a contribution.
