### ISSUE TITLE
Simple Icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4741]
I have:
- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
With the relationship between both libraries, I thought it would be nice it they featured each others icons (ref: [SI#2369](https://github.com/simple-icons/simple-icons/issues/2369)). Could also be useful internally when linking to SI from the docs on the new site.

## Examples
<img alt="Simple Icons" src="https://simpleicons.org/icons/simpleicons.svg" width="72">

https://github.com/simple-icons/simple-icons/blob/master/icons/simpleicons.svg

Given that there's a conflict of interest with me being a member of both projects' teams, I'm only posting this as a request and won't be adding it myself. I'll leave it to another member of the MDI team to make a decision on whether or not it should be included.

**Comment by Templarian** [comment]
Yeah, feel free to add it. We already have don't awesomes in there so might as well.

**Comment by goyney** [comment]
> don't awesomes

😆

**Comment by Templarian** [comment]
😅

**Comment by goyney** [comment]
[![simple-icons](https://materialdesignicons.com/icon/simple-icons)](https://materialdesignicons.com/icon/simple-icons)

**Comment by PeterShaggyNoble** [comment]
`vector-square` has been added to Simple Icons and will be available in the next release.

[![image](https://user-images.githubusercontent.com/15157491/72431508-e7ac4f80-378c-11ea-917b-b47e2104dd38.png)](https://github.com/simple-icons/simple-icons/blob/develop/icons/materialdesignicons.svg)

**Comment by CoDEmanX** [comment]
Huh, our icon isn't grid aligned? I mean it might have a different native size, but it would make a lot of sense to design it for 24dp like all the icons, wouldn't it?

**Comment by Templarian** [comment]
@CoDEmanX Simple Icons does not align to grids. They are simply scaled to fit within a square. So what they've done is correct scaling it edge to edge.
