### ISSUE TITLE
brightness_percent-outline and palette-swatch-outline

### ISSUE THREAD

**Issue by MohammadKhrram** [Templarian/MaterialDesign#4742]
I need the following icons:

<b>brightness-percent-outline</b>
<b>palette-swatch-outline</b>

Please design specified icons
Thanks...

**Comment by goyney** [comment]
We [have asked you before](https://github.com/Templarian/MaterialDesign/issues/4715#issuecomment-572566079) to stop removing the Icon Request template on your requests, so unfortunately I am closing this issue. Please read and follow that template when making icon requests, such as posting _one_ icon request per issue.
