### ISSUE TITLE
rodent (mouse/rat)

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4745]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/72488755-e22c2500-37df-11ea-8ed3-5d790838173f.png)

## Zip Download

[rodent.svg.zip](https://github.com/Templarian/MaterialDesign/files/4069059/rodent.svg.zip)

**Comment by Templarian** [comment]
That is a really nice design. Props to Google's design team.

**Comment by JamesCoyle** [comment]
Would be great to get more animal icons like this. They are so hard to design compared to other icons.

**Comment by goyney** [comment]
[![rodent](https://materialdesignicons.com/icon/rodent)](https://materialdesignicons.com/icon/rodent)
