### ISSUE TITLE
Update hammer

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4747]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/72489078-e1e05980-37e0-11ea-890a-423bd07df95b.png)

## Zip Download

[hammer.svg.zip](https://github.com/Templarian/MaterialDesign/files/4069079/hammer.svg.zip)

---

With the potential add of two new icons with this style hammer in #2028, we should consider updating our hammer to match the style and reattribute to Google.

**Comment by Templarian** [comment]
Lets replace ours.

**Comment by goyney** [comment]
Updated.

**Comment by CoDEmanX** [comment]
Not a fan I must say. I really miss the gap between the head and the stick. Without it, the proportions don't look right and I find it hard to recognize at native size.

**Comment by Templarian** [comment]
@CoDEmanX Forgot to reply to this. Yeah, I got the same feel, but at the same time I think it visually works nicer in the MD guidelines.

After looking at the old one for a bit the way we separate the handle and head of the hammer matches axe/pickaxe is why I would have kept it, but the shape didn't look that "Material".

**Comment by CoDEmanX** [comment]
Just spotted another Google hammer from MIE:

![grafik](https://user-images.githubusercontent.com/1309249/73582467-a48cf480-448d-11ea-917a-140e22bd3228.png)

Should we add that as `hammer-alt`?

**Comment by Templarian** [comment]
Looks a little crushed, but you can tell what it is. Not sure it's necessary to add though.
