### ISSUE TITLE
industrial-robot

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4748]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/72489234-72b73500-37e1-11ea-88b2-a2b30cd50cd7.png)
[industrial-robot.svg.zip](https://github.com/Templarian/MaterialDesign/files/4069091/industrial-robot.svg.zip)

**Comment by Templarian** [comment]
Lets keeps ours. Not a fan of the design.

**Comment by JamesCoyle** [comment]
Yeah I think we rejected this before when someone asked for some factory machinery.

**Comment by goyney** [comment]
Didn't see ours. Closing.
