### ISSUE TITLE
medal-outline

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4749]
## Information

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/72542098-d45abc00-3840-11ea-9ca0-e338040b1121.png)

## Zip Download

[medal-outline.zip](https://github.com/Templarian/MaterialDesign/files/4072261/medal-outline.zip)

**Comment by goyney** [comment]
[![medal-outline](https://materialdesignicons.com/icon/medal-outline)](https://materialdesignicons.com/icon/medal-outline)
