### ISSUE TITLE
Suggest Protocol icon

### ISSUE THREAD

**Issue by StephaneSynergie** [Templarian/MaterialDesign#4751]
Hello !

## Usage

This icon should represent a logic protocol (digital lines output frames composed of logic states 0 or 1), more specifically than the [01|10] icon, that represents only digital data.
Main target are electronic industrial applications

## Examples

It could be a one or two signal frames lines like that :
 _-__-
___-__

![clock-signal-Delaying-Effect-768x274](https://user-images.githubusercontent.com/59999013/72605265-bc586a80-391c-11ea-97e7-e1380d275871.png)

Regards,

Stephane.

**Comment by goyney** [comment]
Please **do not** remove out issue template. You specifically removed the sections talking about searching for existing requests. We are closing issues that fail to utilize our request template.

This duplicates https://github.com/Templarian/MaterialDesign/issues/4346.
