### ISSUE TITLE
Order icons (alphabetical, numeric, bool, bool-variant)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4754]
![grafik](https://user-images.githubusercontent.com/1309249/72631761-2260e400-3955-11ea-8c9e-297a53f0634b.png)

Unlike the sorting icons in #4449, these are supposed to represent the outcome of sorting action, e.g. to be used in user preferences to define a default order.

[order-set.zip](https://github.com/Templarian/MaterialDesign/files/4077889/order-set.zip)

Technically they are for LTR languages, but not sure if we want to add 8 more where the lines are on the left.

Unsure if we need a generic variant and what that would look like. Like the current sort-variant?
![grafik](https://user-images.githubusercontent.com/1309249/72632141-f2fea700-3955-11ea-99e5-3caf27cb2e0b.png)

**Comment by goyney** [comment]
These technically be added now, but I think we might wait until 5.0 and add them with all the icons from #4449.

**Comment by goyney** [comment]
All of these have been added. 🚀
