### ISSUE TITLE
widgets-outline

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#4755]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Examples

Like `widgets`, but as outline.

**Comment by PeterShaggyNoble** [comment]
[![widgets](https://user-images.githubusercontent.com/15157491/72641090-36aade00-3961-11ea-9c78-822e4997a3c5.png)](https://petershaggynoble.github.io/MDI-Sandbox/google/)

**Comment by goyney** [comment]
[![widgets-outline](https://materialdesignicons.com/icon/widgets-outline)](https://materialdesignicons.com/icon/widgets-outline)

**Comment by mueller-ma** [comment]
Thanks!
