### ISSUE TITLE
Rename star-half to star-half-full, add half a star

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4756]
Our naming is inconsistent with `heart-half(-full)` and we don't have the left half of a star on its own:

![grafik](https://user-images.githubusercontent.com/1309249/72654059-0e85a400-398e-11ea-9027-53126ee5b095.png)

Also see https://stackoverflow.com/questions/58673902/vuetify-rating-component-half-stars-with-all-mdi-icons

I suggest we
- rename `star-half` -> `star-half-full`
- add new `star-half`
- check if there are other icons we want to rename/add a half-variant for (there is `shield-half-full`, but I don't see a use case for `shield-half` unlike `heart` and `star` which are commonly used for rating systems)

![grafik](https://user-images.githubusercontent.com/1309249/72654003-e26a2300-398d-11ea-8ae0-522e6b64a95a.png)

[star-half.zip](https://github.com/Templarian/MaterialDesign/files/4079720/star-half.zip)

**Comment by JamesCoyle** [comment]
The shield might be useful for an armor indicator in games?

**Comment by Templarian** [comment]
Agreed. These are perfect 5.0 breaking changes we should be getting in. 👍

**Comment by goyney** [comment]
Added `shield-half` now since it's not breaking.
[![shield-half](https://materialdesignicons.com/icon/shield-half)](https://materialdesignicons.com/icon/shield-half)

**Comment by goyney** [comment]
Renamed `star-half` to `star-half-full`. Added `star-half`.

[![star-half](https://materialdesignicons.com/icon/star-half)](https://materialdesignicons.com/icon/star-half)

Note: `star-half` replaced `flattr` in the v5.0 release.
