### ISSUE TITLE
settings-edit, settings-edit-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4757]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Edit settings.

## Examples

![settings-edit](https://user-images.githubusercontent.com/6717356/72680754-7e02ad00-3ace-11ea-9f49-b1019f988f4c.png)
![settings-edit-outline](https://user-images.githubusercontent.com/6717356/72680756-7fcc7080-3ace-11ea-8f4d-40a679b379b5.png)

**Comment by JamesCoyle** [comment]
Surely the settings icon itself is sufficient? The notion of settings already indicates they can be edited.

**Comment by ozgurg** [comment]
> Surely the settings icon itself is sufficient? The notion of settings already indicates they can be edited.

Hmm, actually you're right.
