### ISSUE TITLE
folder-music, folder-music-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4758]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Music folder.

## Examples

![folder-music](https://user-images.githubusercontent.com/6717356/72681927-55cc7b80-3ad9-11ea-897d-887bd8aa637c.png)
![folder-music-outline](https://user-images.githubusercontent.com/6717356/72681928-57963f00-3ad9-11ea-936f-21c5316d900b.png)

**Comment by Templarian** [comment]
[![folder-music](https://materialdesignicons.com/icon/folder-music)](https://materialdesignicons.com/icon/folder-music) [![folder-music-outline](https://materialdesignicons.com/icon/folder-music-outline)](https://materialdesignicons.com/icon/folder-music-outline)
