### ISSUE TITLE
Add pot/bowl outline variants, update pot base icon, rename?

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4759]
1. We currently have
   - a pot with pixel steam `pot`
   - a pot with a stirring spoon `pot-mix`
   - a bowl with a stirring spoon `bowl`

   ![grafik](https://user-images.githubusercontent.com/1309249/72690494-38210580-3b1d-11ea-9832-2475be058210.png) ![grafik](https://user-images.githubusercontent.com/1309249/72690486-250e3580-3b1d-11ea-8a13-66b1b6bbf06e.png)

   Should we rename `bowl` to `bowl-mix` for consistent naming with `pot-mix`? Adding just a bowl with no stirring spoon as `bowl` to fill the gap doesn't make sense to me however, as is would be hardly recognizable. Maybe rename `pot-mix` to `pot` and `pot` to `pot-steam` instead?

2. I would like to update the base shape of the pot to have a thinner edge. 3dp it acceptable in a solid icon, but it looks odd in an outline variant.

3. We miss outline variants for the mentioned icons.

![grafik](https://user-images.githubusercontent.com/1309249/72690605-3441b300-3b1e-11ea-9577-48e791ef4ab9.png)
![grafik](https://user-images.githubusercontent.com/1309249/72690618-53404500-3b1e-11ea-996c-0d52ed136176.png) ![grafik](https://user-images.githubusercontent.com/1309249/72690612-44f22900-3b1e-11ea-9fda-b3b0b580543c.png)

![grafik](https://user-images.githubusercontent.com/1309249/72690625-68b56f00-3b1e-11ea-9a76-94cf5e873673.png) ![grafik](https://user-images.githubusercontent.com/1309249/72690623-5dfada00-3b1e-11ea-8589-4243e7730f73.png)

[pot-bowl.zip](https://github.com/Templarian/MaterialDesign/files/4083917/pot-bowl.zip)

**Comment by JamesCoyle** [comment]
I like everything here. I think renaming to `pot-steam` is a good idea too.

**Comment by CoDEmanX** [comment]
4. Should there be a gap between bowl/pot and the stirring spoon?
   1dp is the max though, but even that looks slightly strange doesn't it?

![grafik](https://user-images.githubusercontent.com/1309249/72691141-6acdfc80-3b23-11ea-9735-5b75c890e105.png)

**Comment by goyney** [comment]
Bowls are done:

[![bowl](https://materialdesignicons.com/icon/bowl)](https://materialdesignicons.com/icon/bowl)[![bowl-outline](https://materialdesignicons.com/icon/bowl-outline)](https://materialdesignicons.com/icon/bowl-outline)
[![bowl-mix](https://materialdesignicons.com/icon/bowl-mix)](https://materialdesignicons.com/icon/bowl-mix)[![bowl-mix-outline](https://materialdesignicons.com/icon/bowl-mix-outline)](https://materialdesignicons.com/icon/bowl-mix-outline)

Note: `bowl` replaced `foursquare`. `bowl-outline` replaced `glassdoor`. `bowl-mix-outline` replaced `houzz`. All in the v5.0 release.

**Comment by goyney** [comment]
Pots are done.

[![pot](https://materialdesignicons.com/icon/pot)](https://materialdesignicons.com/icon/pot)[![pot-outline](https://materialdesignicons.com/icon/pot-outline)](https://materialdesignicons.com/icon/pot-outline)
[![pot-mix](https://materialdesignicons.com/icon/pot-mix)](https://materialdesignicons.com/icon/pot-mix)[![pot-mix-outline](https://materialdesignicons.com/icon/pot-mix-outline)](https://materialdesignicons.com/icon/pot-mix-outline)
[![pot-steam](https://materialdesignicons.com/icon/pot-steam)](https://materialdesignicons.com/icon/pot-steam)[![pot-steam-outline](https://materialdesignicons.com/icon/pot-steam-outline)](https://materialdesignicons.com/icon/pot-steam-outline)

Note: `pot` replaced `houzz-box`. `pot-outline` replaced `instapaper`. `pot-mix-outline` replaced `itunes`. `pot-steam-outline` replaced `lastfam`. All in the v5.0 release.
