### ISSUE TITLE
Binoculars

### ISSUE THREAD

**Issue by caseyls** [Templarian/MaterialDesign#476]
I'm not entirely sure how easy binoculars would be with no perspective. I guess doing it from a top view would work.

**Comment by Templarian** [comment]
![Maybe](https://cloud.githubusercontent.com/assets/338885/8469883/e3b95f28-2047-11e5-9f82-be8d4b762464.png)

Not sure how these should look... hmm.

**Comment by Templarian** [comment]
Kind of looks like two people, but I might be looking at it too long.

**Comment by caseyls** [comment]
I think it works! You're quick. Thanks so much!

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/binoculars
