### ISSUE TITLE
cricle versions of autorenew, cached, sync and refresh

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#4762]
Hello,
I needed the circle versions, I share them here just in case :

## Preview
![image](https://user-images.githubusercontent.com/6012554/72795785-7e21ba80-3c3e-11ea-90f1-6aa7c23c5da3.png)
![image](https://user-images.githubusercontent.com/6012554/72795820-8aa61300-3c3e-11ea-8150-05fc15d33cee.png)
![image](https://user-images.githubusercontent.com/6012554/72795843-972a6b80-3c3e-11ea-84df-d14d922149c2.png)
![image](https://user-images.githubusercontent.com/6012554/72795870-a3aec400-3c3e-11ea-821c-95868d702400.png)

## Zip Download
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4090461/Archive.zip)

**Comment by goyney** [comment]
We'll add `refresh-circle` and `sync-circle`.

**Comment by Templarian** [comment]
We might want to discuss for 5.0 removing `cached` entirely as it's name/use is very abstract. It's more of a refresh/sync operation normally.

**Comment by qnp** [comment]
I have been thinking about `cached`. I guess the suitable icon to express caching process would be `database-refresh` :

<img width="70" alt="Capture d’écran 2020-01-27 à 10 00 38" src="https://user-images.githubusercontent.com/6012554/73162223-9df92880-40ed-11ea-9c0a-5b9e60140e16.png">

I would be thinking more as smothing like that (**just tests, not propositions**):
<img width="89" alt="Capture d’écran 2020-01-27 à 10 48 05" src="https://user-images.githubusercontent.com/6012554/73164585-87090500-40f2-11ea-8ccb-184ed2d8f17c.png">


However this raises two questions : how comes the `refresh` modifier is in fact the `sync` icon, and why all these `*-refresh` icons are aliased as `*-sync` ? It may have a different meaning:

<img width="503" alt="Capture d’écran 2020-01-27 à 10 11 56" src="https://user-images.githubusercontent.com/6012554/73162358-e7e20e80-40ed-11ea-96ff-3df532932079.png">
(results when searching "refresh" on mdi search bar)


Best regards

**Comment by JamesCoyle** [comment]
I believe these icons should all be `sync` with aliases for the other uses so I've opened a few issues to update the naming. #4778 #4779 #4777

**Comment by goyney** [comment]
[![refresh-circle](https://materialdesignicons.com/icon/refresh-circle)](https://materialdesignicons.com/icon/refresh-circle)[![sync-circle](https://materialdesignicons.com/icon/sync-circle)](https://materialdesignicons.com/icon/sync-circle)
