### ISSUE TITLE
Rename "snakey" chart icons to "sankey"

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4763]
It's not 🐍 diagram, but Sankey diagram (name of the inventor):

https://en.wikipedia.org/wiki/Sankey_diagram

Affected:
- `chart-snakey` → `chart-sankey`
- `chart-snakey-variant` → `chart-sankey-variant`

**Comment by MrGrigri** [comment]
How did this happen? I guess I read snakey instead of Sankey. Oh well, my bad.

**Comment by Templarian** [comment]
Good catch. Hadn't noticed even had to reread this issue. 😶👍

**Comment by goyney** [comment]
Renames have happened. Added the alias too because it doesn't hurt anything.
