### ISSUE TITLE
floor-lamp missing path; strokes look wrong

### ISSUE THREAD

**Issue by hufterkruk** [Templarian/MaterialDesign#4764]
The floor-lamp icon seems to be "missing" a (part of a) path at the very top of the icon, causing (CSS) strokes to look incorrect.
Pic of the issue:
![image](https://user-images.githubusercontent.com/4234982/72829410-03c55a80-3c7f-11ea-9205-035ca162da3b.png)
What the path looks like near the top:
![image](https://user-images.githubusercontent.com/4234982/72829586-59016c00-3c7f-11ea-9cd8-9c1a178b10a6.png)

**Comment by Templarian** [comment]
Most paths do not close. It's an optimization step in the system to cut down the webfont/svg size.

The icons are not designed to be used with a stroke.
