### ISSUE TITLE
Make bottle-wine-outline wider, add soda-classic-outline

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4765]
Continuation of #4727

The outlined wine bottle is pretty narrow. Should we make it wider?

![grafik](https://user-images.githubusercontent.com/1309249/72855987-8ff47380-3cb9-11ea-9ba6-a9efc989e8db.png)

My first attempt:

![grafik](https://user-images.githubusercontent.com/1309249/72691793-53454280-3b28-11ea-91ac-a4b015dc9dca.png)

I think it needs some more tuning to better match the solid variant.

![grafik](https://user-images.githubusercontent.com/1309249/72855926-6a676a00-3cb9-11ea-9718-8980f300bb3f.png)

The above follows the shape of the original closely (I used dynamic offset in InkScape), but not sure what to think.

---

A wider soda-classic as outline variant, with some tuning applied:

![grafik](https://user-images.githubusercontent.com/1309249/72691634-38260300-3b27-11ea-801f-5941cde05288.png)

![grafik](https://user-images.githubusercontent.com/1309249/72691850-b33be900-3b28-11ea-9df9-ffee0085d7fe.png)

[bottle-outlines.zip](https://github.com/Templarian/MaterialDesign/files/4094725/bottle-outlines.zip)

**Comment by Templarian** [comment]
Agreed these look much nicer with the wider profiles.

**Comment by Templarian** [comment]
✔️ 👍
