### ISSUE TITLE
Swiss Franc currency icon

### ISSUE THREAD

**Issue by thegoldgoat** [Templarian/MaterialDesign#4768]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same as every other currency, to specify the currency of a transaction

## Examples

I found [this](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn3.iconfinder.com%2Fdata%2Ficons%2Fcurrency-2%2F460%2FFranc-512.png&f=1&nofb=1), but I have never seen that icon before, maybe a [CHF](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fcdn2.iconfinder.com%2Fdata%2Ficons%2Fcoins-currencies-outline%2F100%2FSwiss_Franc-512.png&f=1&nofb=1) would be fine.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73475892-86da6500-4391-11ea-875b-a12135611379.png)

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73476575-d1101600-4392-11ea-8525-77ec376bdee6.png)

**Comment by thegoldgoat** [comment]
I think the 'F' one is actually better and more coherent with the rest of the icons

**Comment by PeterShaggyNoble** [comment]
We did previously have this but removed it in #1991 - see the discussion there for the reasons why.

![currency-chf](https://user-images.githubusercontent.com/15157491/73478286-bab38b80-438d-11ea-8ce9-924fd5952503.png)

**Comment by andreasomaini** [comment]
I see. Makes sense actually, as I said I have never seen that 'F' myself. Is the 'CHF' a bad idea though (?)

**Comment by thegoldgoat** [comment]
I see. Makes sense actually, as I said I have never seen that 'F' myself. Is the 'CHF' a bad idea though (?)

**Comment by goyney** [comment]
> I see. Makes sense actually, as I said I have never seen that 'F' myself. Is the 'CHF' a bad idea though (?)

Yes.
