### ISSUE TITLE
currency-usd-down, currency-usd-down-variant

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4769]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Discount. Maybe can be expanded for other currencies.

## Examples

![currency-usd-down](https://user-images.githubusercontent.com/6717356/72904376-da203800-3d3f-11ea-8c25-ca964dc547ba.png)
![currency-usd-down-variant](https://user-images.githubusercontent.com/6717356/72904382-dc829200-3d3f-11ea-8c1b-0fbfeafd4f8b.png)

**Comment by goyney** [comment]
We're avoiding make changes to or adding new icons that deal with specific currencies. Your use case is to indicate a sale or discount. We have `sale` which is global across all currencies, and we recommend you use that.

[![sale](https://materialdesignicons.com/icon/sale)](https://materialdesignicons.com/icon/sale)

**Comment by CoDEmanX** [comment]
You may also use the `trending-*` icons:
![grafik](https://user-images.githubusercontent.com/1309249/72917405-10f84d00-3d44-11ea-8b9b-eb097a3cb64e.png)
