### ISSUE TITLE
Feature request: Copy to clipboard

### ISSUE THREAD

**Issue by ButchersBoy** [Templarian/MaterialDesign#477]
A shortcut feature to copy an icon source directly to clipboard would be a neat little time save.

Cheers, James.

**Comment by danielhickman** [comment]
I'd add [ZeroClipboard](https://github.com/zeroclipboard/zeroclipboard) to this site, if I knew how to use the tools you've used for the website. 

Also, ZeroClip doesn't work without Flash and there sadly isn't any other alternatives without it. *Waits anxiously for HTML5's implementation*

**Comment by ButchersBoy** [comment]
An easier/auto select all like on GitHub clone command or goo.gl would be cool.

**Comment by Templarian** [comment]
@danielhickman I'll be using the native copy to clipboard found in modern browsers. Definitely using zero clipboard, so there will be no legacy browser support.

**Comment by danielhickman** [comment]
I haven't ever seen that. Even GitHub and Google both use ZeroClip and I haven't seen anything else.

**Comment by Templarian** [comment]
Well yea... it was just added in Chrome 43... I coded a demo to show off how it works:

http://codepen.io/templarian/pen/doeLQY

**Comment by danielhickman** [comment]
Oh my! This is new! I love it, thanks.

**Comment by CoDEmanX** [comment]
Good news: Firefox 41+ supports copying too!

https://hacks.mozilla.org/2015/09/flash-free-clipboard-for-the-web/
