### ISSUE TITLE
Tilted window / door icon

### ISSUE THREAD

**Issue by breti** [Templarian/MaterialDesign#4770]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There are some icons for open and closed windows and doors, but there is no icon for a tilted window or door. 

Usually rotary handle sensors [like this one](https://www.eq-3.com/products/homematic/detail/homematic-wireless-window-rotary-handle-sensor.html) report closed / open / tilted.

## Examples

Window:

https://www.shutterstock.com/de/image-vector/diagram-showing-casement-window-three-different-299251349

Door:

https://www.greatlandwindow.com/images/300/img_6666.jpg

**Comment by CoDEmanX** [comment]
MD icons shall avoid perspective as per the guidelines, so this seems nearly impossible to depict.
