### ISSUE TITLE
Add filled storefront, rename existing icon to storefront-outline?

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4771]
The existing `storefront` icon is technically an outline variant of a non-existing solid version:

![grafik](https://user-images.githubusercontent.com/1309249/72913541-93c9d980-3d3d-11ea-8f17-3c1f41bdcada.png)

We might want to rename it and add either of the following filled variants:

![grafik](https://user-images.githubusercontent.com/1309249/72913467-772da180-3d3d-11ea-9436-8b8e7d273b5a.png) ![grafik](https://user-images.githubusercontent.com/1309249/72913483-7d238280-3d3d-11ea-8c4e-e37d15dabbe1.png)

The fully-solid version is hardly recognizable, therefore I would go with the partially filled one.

[storefront.zip](https://github.com/Templarian/MaterialDesign/files/4098754/storefront.zip)

**Comment by goyney** [comment]
Agree with the first of the two.

**Comment by goyney** [comment]
Renamed and added solid version.
[![storefront](https://materialdesignicons.com/icon/storefront)](https://materialdesignicons.com/icon/storefront)[![storefront-outline](https://materialdesignicons.com/icon/storefront-outline)](https://materialdesignicons.com/icon/storefront-outline)

Note: `storefront` replaced `eventbrite` in the v5.0 release.
