### ISSUE TITLE
Ceiling Fan with Light Icon

### ISSUE THREAD

**Issue by chansearrington** [Templarian/MaterialDesign#4772]
Hey guys,

I'm hoping you can add a combo ceiling fan/light icon it would help out my home assistant config a lot.

Here is one that was recently release for Homekit

![image](https://user-images.githubusercontent.com/123082/72968059-8f221700-3d77-11ea-9fdd-cc58ee44f163.png)

https://homekitnews.com/2019/06/30/icon-changes-to-homekit-in-ios13/

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73591270-b18d0080-44ec-11ea-8db2-81391f751554.png)

**Comment by CoDEmanX** [comment]
The horizontal line at the top doesn't need any rounding I think. Otherwise this could work in context.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73596797-e10c2f00-4525-11ea-857d-5997c570bbe0.png)

![image](https://user-images.githubusercontent.com/58486458/73596828-29c3e800-4526-11ea-84fd-ba8b916c453c.png)

**Comment by kmlucy** [comment]
@nilsfast Do you have the svgs for those icons?

**Comment by nilsfast** [comment]
Here is a .zip with the icons from above:

[ceiling-fan-with-light.zip](https://github.com/Templarian/MaterialDesign/files/4470256/ceiling-fan-with-light.zip)

**Comment by Templarian** [comment]
We'll need to exaggerate the light rays a little bit more. Right now they are too small at the 1:1 size. I think the fan design works though.

**Comment by kmlucy** [comment]
When this gets added, can there also be a version without the light rays? Just the ceiling fan portion would also be very useful.

**Comment by chansearrington** [comment]
Is there a reason this still isn't available?

**Comment by Harrison-Phillips** [comment]
> Is there a reason this still isn't available?

I second this.  Is there a reason this hasn't been implemented.  Also I agree with @kmlucy that a version without light rays would be nice.

**Comment by LordNex** [comment]
+1 Vote from me. Add me to this request!

**Comment by Corneloues** [comment]
+1 for me too - waiting patiently (at the moment)

**Comment by XtremeOwnageDotCom** [comment]
+1, but- add multiple icons.

- ceiling_fan_light_on
- ceiling_fan_light_off

**Comment by Jackroser123** [comment]
+Another 1 - extremely excited if this eventually gets released

**Comment by edpvic** [comment]
Guys, How long can take release an icon?

**Comment by euromem** [comment]
Bump

**Comment by XtremeOwnageDotCom** [comment]
@chansearrington, perhaps you should open a pull request to close this issue. I don't think anybody is looking at these issues....

**Comment by goyney** [comment]
[![ceiling-fan](https://materialdesignicons.com/icon/ceiling-fan)](https://materialdesignicons.com/icon/ceiling-fan)[![ceiling-fan-light](https://materialdesignicons.com/icon/ceiling-fan-light)](https://materialdesignicons.com/icon/ceiling-fan-light)
