### ISSUE TITLE
Add account-details-outline

### ISSUE THREAD

**Issue by mozi-h** [Templarian/MaterialDesign#4773]
## Usage

Having an `account-details` variant for `account-outline` would be nice, as it's the only missing `-outline` option I stumbled across (because I could use it - bad luck I guess).

## Examples
![account-details-outline-demo](https://user-images.githubusercontent.com/19172408/73005407-326f3c80-3e09-11ea-956b-9224dc3f00b5.png)
Rough image

**Comment by CoDEmanX** [comment]
Little anecdote:
I checked the account icons for missing outline variants the other day and added `account-convert-outline` while also updating the base icon to make an outlined variant possible. I also saw `account-details`, but the person silhouette was even smaller than in that other icon, of which I had to increase the person shape already. What I did not consider was to use a narrower shape, and we actually have account icons like that (e.g. `account-multiple-plus-outline`).

The base icon needs to be updated, but it's not much of a change (red = old, gray = new):

![grafik](https://user-images.githubusercontent.com/1309249/73035394-340c2500-3e48-11ea-933b-75f54651691b.png) ![grafik](https://user-images.githubusercontent.com/1309249/73035424-500fc680-3e48-11ea-82d3-444b46bd213b.png)

[account-details.zip](https://github.com/Templarian/MaterialDesign/files/4106298/account-details.zip)

Meanwhile, you could consider to use `account-card-details-outline`.
