### ISSUE TITLE
Sticker Icons

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#4774]
It would be nice to have a set of sticker icons for a project I'm working on. I put these together based on the Google [sticker-emjoi](https://materialdesignicons.com/icon/sticker-emoji)

[sticker-icons.zip](https://github.com/Templarian/MaterialDesign/files/4104683/SVG.zip)

**Outline Icons**

![sticker-outline](https://user-images.githubusercontent.com/1837101/73010189-2d8d9700-3dcf-11ea-98b5-77bf6930c4e2.png)

![sticker-plus-outline](https://user-images.githubusercontent.com/1837101/73010175-26ff1f80-3dcf-11ea-9273-496a42691e40.png)

![sticker-minus-outline](https://user-images.githubusercontent.com/1837101/73010184-2bc3d380-3dcf-11ea-9ada-37f4730d73c1.png)

![sticker-check-outline](https://user-images.githubusercontent.com/1837101/73010209-367e6880-3dcf-11ea-95d2-b9d2a4593cda.png)

![sticker-close-outline](https://user-images.githubusercontent.com/1837101/73010217-3bdbb300-3dcf-11ea-9618-156358440eac.png)

![sticker-alert-outline](https://user-images.githubusercontent.com/1837101/73010227-3e3e0d00-3dcf-11ea-8515-f4dee4b380df.png)

**Filled Icons**
I'm not sure if it makes sense to include filled sticker icons as well, but here are some:

![sticker](https://user-images.githubusercontent.com/1837101/73010281-6299e980-3dcf-11ea-869a-aa7158d03246.png)

![sticker-plus](https://user-images.githubusercontent.com/1837101/73010295-69c0f780-3dcf-11ea-82a1-82d08145fba3.png)

![sticker-minus](https://user-images.githubusercontent.com/1837101/73010304-6ded1500-3dcf-11ea-849e-76c7cb46d57a.png)

![sticker-check](https://user-images.githubusercontent.com/1837101/73010316-71809c00-3dcf-11ea-90a2-589d916beff6.png)

![sticker-close](https://user-images.githubusercontent.com/1837101/73010324-75142300-3dcf-11ea-80b1-ebe055fec86b.png)

![sticker-alert](https://user-images.githubusercontent.com/1837101/73010333-78a7aa00-3dcf-11ea-855c-e8a90e520fc5.png)

**Comment by goyney** [comment]
These aren't too bad. I would like to see the folded over corner follow our `file-*` icons do it for consistency.

And yes, we want filled and `-outline` variants. We will also update our current `sticker` icon and remove it as part of this.

**Comment by Xenomorph99** [comment]
Awesome! I'll get those updated and add them here.

**Comment by MrGrigri** [comment]
Good job!

I would definitely keep the dogear in the bottom right corner, but make it consistent like our file icons as @goyney stated.

**Comment by Xenomorph99** [comment]
Here's all the updated icons:
[SVG.zip](https://github.com/Templarian/MaterialDesign/files/4109568/SVG.zip)

**Updated Outline Icons**

![sticker-outline](https://user-images.githubusercontent.com/1837101/73088074-c801df00-3e90-11ea-968b-83e29051c812.png)

![sticker-plus-outline](https://user-images.githubusercontent.com/1837101/73088065-c3d5c180-3e90-11ea-91a1-294d470b6df3.png)

![sticker-minus-outline](https://user-images.githubusercontent.com/1837101/73088093-d05a1a00-3e90-11ea-8c8a-be76ee373854.png)

![sticker-check-outline](https://user-images.githubusercontent.com/1837101/73088155-e9fb6180-3e90-11ea-95fc-ecde9a11e052.png)

![sticker-close-outline](https://user-images.githubusercontent.com/1837101/73088123-dea83600-3e90-11ea-8dd8-5d96460214f1.png)

![sticker-alert-outline](https://user-images.githubusercontent.com/1837101/73088181-f54e8d00-3e90-11ea-9149-cce58e97f26b.png)






**Updated Filled Icons**

![sticker](https://user-images.githubusercontent.com/1837101/73088047-bae4f000-3e90-11ea-97f1-9726f42d030c.png)

![sticker-plus](https://user-images.githubusercontent.com/1837101/73088058-c0dad100-3e90-11ea-807b-b28ba908002f.png)

![sticker-minus](https://user-images.githubusercontent.com/1837101/73088086-cc2dfc80-3e90-11ea-879e-5cc9c8ad33f5.png)

![sticker-check](https://user-images.githubusercontent.com/1837101/73088131-e49e1700-3e90-11ea-9583-0caea372febd.png)

![sticker-close](https://user-images.githubusercontent.com/1837101/73088111-d6e89180-3e90-11ea-989c-6935177b24ce.png)

![sticker-alert](https://user-images.githubusercontent.com/1837101/73088171-ef58ac00-3e90-11ea-8ec5-b29f719557ee.png)

**Comment by Xenomorph99** [comment]
Here's a comparison to the file icon
![comparison](https://user-images.githubusercontent.com/1837101/73088283-29c24900-3e91-11ea-8d0f-5ae3ed41ac80.jpg)

**Comment by Templarian** [comment]
All of these have been added to your contributor account.

Thanks! 😃
