### ISSUE TITLE
radiology or x-ray

### ISSUE THREAD

**Issue by raetha** [Templarian/MaterialDesign#4775]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

We are using a variety of Material Design Icons at our hospital system for identifying various groups and services in our ticketing system. One we are struggling to find a suitable icon for is our radiology department. An x-ray icon would work, or something else that represents the field of radiology.

## Examples

Common icons we see out there seem to be of a full or partial skeleton with a frame around them. Sometimes they include a head, arms and legs with the x-ray frame just over the torso. No strong preference in any direction if the icon seems to represent radiology or x-rays reasonably well.

**Comment by CoDEmanX** [comment]
Some experiments:

![grafik](https://user-images.githubusercontent.com/1309249/73036191-0d9bb900-3e4b-11ea-9106-52c316ebe6d3.png) ![grafik](https://user-images.githubusercontent.com/1309249/73037551-bea45280-3e4f-11ea-9c27-cedcec31196c.png)
![grafik](https://user-images.githubusercontent.com/1309249/73037523-aa605580-3e4f-11ea-8b79-2f84c68292ab.png)
![grafik](https://user-images.githubusercontent.com/1309249/73037668-31153280-3e50-11ea-87f0-499d210a28b3.png) ![grafik](https://user-images.githubusercontent.com/1309249/73037895-e516bd80-3e50-11ea-8692-e72cb5c782e5.png)
![grafik](https://user-images.githubusercontent.com/1309249/73038708-b5b58000-3e53-11ea-8b8f-43c03f82b439.png) ![grafik](https://user-images.githubusercontent.com/1309249/73038723-bfd77e80-3e53-11ea-8dbb-0c80ffcb14b1.png)


[radiology.zip](https://github.com/Templarian/MaterialDesign/files/4106496/radiology.zip)

**Comment by MrGrigri** [comment]
I believe `radiology` and `radiology2` have too many one-pixel wide elements. With `human-radiology2`, I believe there needs to be a consistent cutout around the scan area. The head is cut out but the arms are not (see Figure 1). I do quite enjoy `skull-scan` and `skull-scan2`.

---
#### Figure 1

![image](https://user-images.githubusercontent.com/4528551/73086865-a7d12080-3e8e-11ea-9374-4bb87ca35d6c.png)

**Comment by CoDEmanX** [comment]
Good points. Also not happy with the first two. My gf says the skull shouldn't be used because of its strong connotation for "death", but it works rather well in terms of size. I think I would shrink it by 2dp though to increase the gap to the scan corners.

**Comment by raetha** [comment]
Hi @CoDEmanX,
I apologize for the delay on feedback, got pulled in on some things taking all my attention the last couple weeks. I like your drafts, and recognize you and the other designers talking about some specific details that I'm not familiar with, but would likely impact an end result. I did want to pass along that for the specific use I had in mind here, my favorites as starting points are the following in order of preference: radiology, human-radiology3, human-radiology.

They all look great though, and thank you for taking a stab at this!
-raetha

**Comment by CoDEmanX** [comment]
@raetha No worries! Your feedback is welcome.

What MrGrigri means is that in the radiology icons there are a lot of "thin lines" (the ribs ,1 pixel in height), which are not compliant with the material icon guidelines. There are exceptions however, in both Google and our icons - sometimes it is simple not possible using the standard 2 pixel strokes.

@MrGrigri It looks more consistent with the arms cut off similar to the head, but rather chopped off overall 😕

![grafik](https://user-images.githubusercontent.com/1309249/74192902-b7a28000-4c56-11ea-8500-2027f68a3e25.png)

The skull scan icon with a smaller circle is much nicer:

![grafik](https://user-images.githubusercontent.com/1309249/74192866-a6f20a00-4c56-11ea-8802-93bdbf9bf4d0.png)

My favorite is `radiology` so far. The pelvis bone in `human-radiology3` is too blurry, but if we could get that tweaked to look crisper, than it might become a winner.

**Comment by goyney** [comment]
`skull-scan(-outline)` have been added.

As for `radiology`, I also like that one, but agree with @MrGrigri that there is too much 1dp happening. Here are my proposal's to simplify the icon and also allow us to offer an outline version as well:

![image](https://user-images.githubusercontent.com/1015040/81631702-7432eb80-93d6-11ea-9f0d-f598bce43e90.png)![image](https://user-images.githubusercontent.com/1015040/81631724-857bf800-93d6-11ea-8cc0-80fc536e6185.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4613047/Archive.zip)

**Comment by goyney** [comment]
Dropped a rib out of `radiology` so it could be made to fit in the outline variant. Also helps solved the "too much 1dp" dilemma a little bit. The icon is better served with 1dp lines than trying to go to 1.5dp, because at that thickness it becomes blurry. We've opted to stay on grid for this.

[![radiology-box](https://materialdesignicons.com/icon/radiology-box)](https://materialdesignicons.com/icon/radiology-box)[![radiology-box-outline](https://materialdesignicons.com/icon/radiology-box-outline)](https://materialdesignicons.com/icon/radiology-box-outline)

**Comment by goyney** [comment]
`x-ray` aliased added.

**Comment by Simran-B** [comment]
@goyney Nice iteration on the design, thanks!

**Comment by raetha** [comment]
I'm late to reply, but thank you everyone that helped on this. The icons look great, and we're already using some of them. :)
