### ISSUE TITLE
Pylon, powerline

### ISSUE THREAD

**Issue by flykenobi** [Templarian/MaterialDesign#4776]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It could be useful in home automation scenarios, to differentiate the energy coming from the grid from that self-produced by solar panels

## Examples

![industry_electricity-pylon-512](https://user-images.githubusercontent.com/59345373/73107446-1ac5b000-3efe-11ea-8b5b-10691bfbd9f3.png)

**Comment by Templarian** [comment]
Aliases added to the `transmission-tower` icon that exists. Should making find it easier in the search.

😃
