### ISSUE TITLE
Rename `calendar-repeat-[outline]` to `calendar-sync` / Add `-refresh`

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#4777]
We have a few icons with `sync` as a modifier so I feel this should be consistent with those. Needs aliasing with repeat for searchability.

**Comment by goyney** [comment]
`calendar-repeat(-outline)` renamed to `calendar-sync(-outline)` and aliased.

**Comment by goyney** [comment]
[![calendar-refresh](https://materialdesignicons.com/icon/calendar-refresh)](https://materialdesignicons.com/icon/calendar-refresh)[![calendar-refresh-outline](https://materialdesignicons.com/icon/calendar-refresh-outline)](https://materialdesignicons.com/icon/calendar-refresh-outline)

Note: `calendar-refresh` replaced `dribbble-box` and `calendar-refresh-outline` replaced `etsy` in the v5.0 release.
