### ISSUE TITLE
Rename `database-refresh` to `database-sync` / Add `-refresh`

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#4778]
This is actually using the sync icon as the modifier not refresh. Should probably rename it to avoid confusion. Might want to add a `database-refresh` icon in its place and add `database-sync` as a new icon?

**Comment by CoDEmanX** [comment]
I this context I can kind of see a need for both:– Reload database from disk (as in re-read/reset)– Synchronize local state with online database or sync two databases

**Comment by Templarian** [comment]
Yeah, both are fine for all. But needs to use refresh/sync naming consistently.

**Comment by Templarian** [comment]
Already created these by the way and will handle this one.

**Comment by Templarian** [comment]
Done. `database-refresh` replaced yelp in `5.0`
