### ISSUE TITLE
Rename `shield-refresh-[outline]` to `shield-sync-[outline]` / Add `-refresh`

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#4779]
This is actually using the sync icon as the modifier not refresh. Should probably rename it to avoid confusion. Might want to add a shield-refresh icon in its place and add shield-sync as a new icon?

**Comment by goyney** [comment]
`shield-refresh(-outline)` renamed `shield-sync(-outline)`. Added new `refresh` variants.

[![shield-refresh](https://materialdesignicons.com/icon/shield-refresh)](https://materialdesignicons.com/icon/shield-refresh)[![shield-refresh-outline](https://materialdesignicons.com/icon/shield-refresh-outline)](https://materialdesignicons.com/icon/shield-refresh-outline)

Note: `shield-refresh` replaced `blackberry` and `shield-refresh-outline` replaced `dribble` in the v5.0 release.
