### ISSUE TITLE
Trading: Up Trend / Down Trend

### ISSUE THREAD

**Issue by dmitry8887** [Templarian/MaterialDesign#478]
Ideally as Bool/Bear but can be arrows with the relevant chart at the background. 

Thanks.

**Comment by Templarian** [comment]
Google provides trending icons...

https://materialdesignicons.com/icon/trending-up
https://materialdesignicons.com/icon/trending-neutral
https://materialdesignicons.com/icon/trending-down

The https://materialdesignicons.com/icon/elevation-rise / descend might also work.

**Comment by Templarian** [comment]
I'm going to close this issue out. If the above icons do not work let me know with some example images and I will reopen the issue.
