### ISSUE TITLE
bookmark-check-outline

### ISSUE THREAD

**Issue by MohammadKhrram** [Templarian/MaterialDesign#4781]
bookmark-check-outline

**Comment by MohammadKhrram** [comment]
i don't know your template.
please tell me How should I request with your template...
thanks

**Comment by JamesCoyle** [comment]
It's the thing you keep deleting when you open the issue.

**Comment by goyney** [comment]
![Screen Recording 2020-01-27 at 4 23 46 PM](https://user-images.githubusercontent.com/1015040/73215239-a23f3900-4121-11ea-874d-18e822b723f1.gif)
