### ISSUE TITLE
Can you add my Twitter profile?

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4782]
Can you add my Twitter profile here?:
![Screenshot_1](https://user-images.githubusercontent.com/6717356/73220048-96c62f00-416e-11ea-901f-911be5ce1d09.png)

My Twitter profile: https://twitter.com/ozgurg0

Should this link be Twitter? Can it be GitHub profile?

**Comment by Templarian** [comment]
Updated.

There is a way for contributors to modify this, but we haven't opened it just yet outside of core contributors.
