### ISSUE TITLE
upload-lock

### ISSUE THREAD

**Issue by ari0ch8** [Templarian/MaterialDesign#4783]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

Uploading encrypted data.

## Examples

Include any example images so we know what the icon should look like.

Upload version of download-lock.

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/73396204-27e7f380-429e-11ea-88c2-d52fdefb39d8.png) ![image](https://user-images.githubusercontent.com/4528551/73396240-333b1f00-429e-11ea-9b01-2092b0c393d6.png)

[upload-lock.zip](https://github.com/Templarian/MaterialDesign/files/4130669/upload-lock.zip)

**Comment by ari0ch8** [comment]
Fantastic work! Thank you!

**Comment by CoDEmanX** [comment]
Added, as we already have the download icons.
