### ISSUE TITLE
I just want use some icon in MaterialDesign

### ISSUE THREAD

**Issue by hinora** [Templarian/MaterialDesign#4784]
Hello, my english is not good, so if i say something wrong, forgive me :)
Material too big with my website, I just want use some icon, so how i can do that? Somebody can tell me. Thanks so much

**Comment by JamesCoyle** [comment]
You can use individual SVG files for each icon directly or the easier way is to use [@mdi/js](https://www.npmjs.com/package/@mdi/js) which provides the SVG path for each icon. That will allow you to import each icon individually without including all of them.

**Comment by Templarian** [comment]
http://dev.materialdesignicons.com/guide/webfont-alternatives

But you can use http://icomoon.io/ or similar to subset the font with the SVGs provided in this repo.

We do not current offer a nice utility to subset the webfont. `@mdi/font-build` package is what we use internally to build the font, but requires one to manually create a `meta.json` to subset the font.

**Comment by CoDEmanX** [comment]
I'm closing this issue as answered. Feel free to reopen if you have follow-up questions.
