### ISSUE TITLE
bookmark-check-outline

### ISSUE THREAD

**Issue by MohammadKhrram** [Templarian/MaterialDesign#4785]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by MohammadKhrram** [comment]
What happened?!
Please design specified icon for me
<b>bookmark-check-outline</b>
Thanks...

**Comment by goyney** [comment]
> Provide some context of how your icon could be used.

> Include any example images so we know what the icon should look like.

???? Please fill out the template.
