### ISSUE TITLE
Traffic Cone

### ISSUE THREAD

**Issue by gdang** [Templarian/MaterialDesign#4786]
Suggestions:

- safety-cone
- construction-cone
- traffic-cone
- road-cone

Context: I was searching for an icon to represent my "under construction/error 404" pages and had used **construction** and **cone** keywords.

**Comment by PeterShaggyNoble** [comment]
As VLC is a brand icon, we don't recommend using it for any other purposes than representing that brand. Repurposing this as a request for a generic traffic cone.

**Comment by PeterShaggyNoble** [comment]
We do already have a `sign-caution` icon, which might suit your needs in the meantime.

[![sign-caution](https://user-images.githubusercontent.com/15157491/73278989-51444900-41e4-11ea-969e-133b5f08f286.png)](https://materialdesignicons.com/icon/sign-caution)

**Comment by MrGrigri** [comment]
I went with it being 1 pixel higher than the boundary so that the cone points stay on the grid. This is also my first time using Affinity Designer...so the SVG might not be great. 

![image](https://user-images.githubusercontent.com/4528551/73394397-cbcfa000-429a-11ea-80eb-5a5bd699f211.png)

[traffic-cone.zip](https://github.com/Templarian/MaterialDesign/files/4130550/traffic-cone.zip)

**Comment by CoDEmanX** [comment]
The SVG seems pretty messed up, at least in InkScape. Canvas size is 1x1, with no unit?! If I change the canvas size, set it to pixels and revert the scaling to 1, then it's just a tiny icon in the top-left corner 😕 

Regarding the icon, my gut feeling was to make it wider at the top, shorten it by 1dp and shift the stripes down. A wider top looks really weird though, and I'm not sure about the other changes:

![grafik](https://user-images.githubusercontent.com/1309249/73499130-7a6d0100-43bf-11ea-8904-de67361ed0e5.png)

With the stripes higher as in yours makes it more recognizable IMO, so +1

**Comment by CoDEmanX** [comment]
Re the SVG, the path data itself looks good. It is unnecessarily grouped and the canvas is somehow messed up, but the extracted path data looks quite clean.

**Comment by goyney** [comment]
[![traffic-cone](https://materialdesignicons.com/icon/traffic-cone)](https://materialdesignicons.com/icon/traffic-cone)
