### ISSUE TITLE
Rename & Update google-adwords

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4787]
Google Adwords was rebranded as Google Ads in 2018, so it's probably about time we updated it! Found the following in the menu of https://business.google.com/ - do we want to scale it down to fit in `20*20`?

[![google-ads](https://user-images.githubusercontent.com/15157491/73349563-4e4c6580-4283-11ea-99fb-196bdc504f23.png)](https://github.com/Templarian/MaterialDesign/files/4127477/google-ads.zip)

**Comment by MrGrigri** [comment]
For reference:
![image](https://user-images.githubusercontent.com/4528551/73375771-8cdd2280-4279-11ea-8165-57385736c582.png)

**Comment by goyney** [comment]
[![google-ads](https://materialdesignicons.com/icon/google-ads)](https://materialdesignicons.com/icon/google-ads)

Updated and aliased.
