### ISSUE TITLE
Update nfc(-off)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4788]
Two options available, both allowable under their brand guidelines. Google includes the first one in MIE but we'll need to decide which works best with the `-off` modifier - we may need to flip it for this one.

[![nfc](https://user-images.githubusercontent.com/15157491/73355862-f61c6000-4290-11ea-82e0-d3c0307ca986.png)](https://github.com/Templarian/MaterialDesign/files/4127853/nfc-1.zip)[![nfc](https://user-images.githubusercontent.com/15157491/73355960-2b28b280-4291-11ea-96e7-12ff608a840a.png)](https://github.com/Templarian/MaterialDesign/files/4127857/nfc-2.zip)

**Comment by MrGrigri** [comment]
I believe with this, it makes sense to reverse the off modifier. Thoughts?

**Comment by JamesCoyle** [comment]
Definitely agree. Do we want to go for an nfc and nfc-box variant? If we're only using one I think it should be the left one which is used in android.

**Comment by goyney** [comment]
I see the potential use case for an `off` variant, but doing that to a Brand Icon seems like a big no-no. Wouldn't a more generic contactless icon with an off fit those use cases and the simple `nfc` icon can be the logo?

**Comment by CoDEmanX** [comment]
I tend to agree. This isn't a materialy icon. Google has at least two other contactless icons, let's try them with the strikes trough line.

**Comment by MrGrigri** [comment]
Good point @goyney, I didn't even consider that. I don't think we should do an `off` variant with this icon.

**Comment by goyney** [comment]
Marking this breaking since we are going to remove `nfc-off` from the library as well.

**Comment by CoDEmanX** [comment]
Our generic `contact-payment` icon:

![grafik](https://user-images.githubusercontent.com/1309249/73616707-2b210d80-4617-11ea-8515-5f8976d7c019.png)

Off variant that we should add:

![grafik](https://user-images.githubusercontent.com/1309249/73616705-1cd2f180-4617-11ea-9f1f-aa424ae9ede2.png)

We could also consider adding off variants for `credit-card-wireless(-outline)`:

![grafik](https://user-images.githubusercontent.com/1309249/73616749-a5519200-4617-11ea-8b95-007cfe0905b3.png) ![grafik](https://user-images.githubusercontent.com/1309249/73616779-f19cd200-4617-11ea-8035-205487435e38.png)

(I extended the strike through stroke from the template, by shifting the end vertices by 1dp to the right and bottom - should it be 0.5dp more for clarity?)

Google MIE contains a `contactless` icon:

![grafik](https://user-images.githubusercontent.com/1309249/73616695-02991380-4617-11ea-833f-ee2bc914c192.png)

... but it doesn't work as off-icon:

![grafik](https://user-images.githubusercontent.com/1309249/73616689-f1e89d80-4616-11ea-8d93-e2dac2b3953e.png)

Source files: [contactless-off.zip](https://github.com/Templarian/MaterialDesign/files/4145627/contactless-off.zip)

**Comment by goyney** [comment]
`nfc` was updated. `nfc-off` was removed.
[![nfc](https://materialdesignicons.com/icon/nfc)](https://materialdesignicons.com/icon/nfc)

Leaving this open to add the three generic `off` variants by @CoDEmanX at some point during 5.0.

**Comment by PeterShaggyNoble** [comment]
Our `contactless-payment` icon actually has its own "brand" guidelines at https://www.emvco.com/about/trademark-centre/

**Comment by goyney** [comment]
@PeterShaggyNoble To use their logo, we have to actually go through a DocuSign signing agreement. Which means, we should probably remove that ASAP.

@Templarian FYI

**Comment by goyney** [comment]
[![credit-card-wireless-off](https://materialdesignicons.com/icon/credit-card-wireless-off)](https://materialdesignicons.com/icon/credit-card-wireless-off)[![credit-card-wireless-off-outline](https://materialdesignicons.com/icon/credit-card-wireless-off-outline)](https://materialdesignicons.com/icon/credit-card-wireless-off-outline)

[![contactless-payment-circle](https://materialdesignicons.com/icon/contactless-payment-circle)](https://materialdesignicons.com/icon/contactless-payment-circle)[![contactless-payment-circle-outline](https://materialdesignicons.com/icon/contactless-payment-circle-outline)](https://materialdesignicons.com/icon/contactless-payment-circle-outline)

**Comment by goyney** [comment]
I recommend we replace our current `contactless-payment` with a non-circle version of Google's, and then add an `off` variant of it.

**Comment by goyney** [comment]
For now, we've adding information on how to get a license to use the `contactless-payment` and `nfc` logos in the icons descriptions.
