### ISSUE TITLE
auto-download

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4789]
## Request

We have an `auto-upload` icon and not an `auto-download` icon. Also, should we have an "off" variant for these as well?

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/4528551/73395476-d8ed8e80-429c-11ea-9154-442c13a46c54.png)

## Zip Download

[auto-download.zip](https://github.com/Templarian/MaterialDesign/files/4130622/auto-download.zip)

**Comment by CoDEmanX** [comment]
I don't quite see a use case for `auto-{upload|download}-off`. You could just use a normal `{download|upload}-off` couldn't you?

**Comment by goyney** [comment]
[![auto-download](https://materialdesignicons.com/icon/auto-download)](https://materialdesignicons.com/icon/auto-download)
