### ISSUE TITLE
Multiple labels

### ISSUE THREAD

**Issue by dzhusi** [Templarian/MaterialDesign#4791]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Well, if something has multiple labels or some web page displays a list of labels, then the icon fits perfectly. 

## Examples

![MultipleLabels](https://user-images.githubusercontent.com/5774079/73448761-c8681180-438b-11ea-859f-c9a349191996.png)

**Comment by nilsfast** [comment]
I don't know how this works... Should I just post the files when I want to become a contributor?

If so, here is the .zip file:
[multiple-lablels.zip](https://github.com/Templarian/MaterialDesign/files/4135305/multiple-lablels.zip)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/73473258-b1a0cb00-4349-11ea-922c-6f0e73373252.png) ![image](https://user-images.githubusercontent.com/4528551/73473936-d0ec2800-434a-11ea-8a7c-aa39f13ed438.png)

[label-multiple.zip](https://github.com/Templarian/MaterialDesign/files/4135344/label-multiple.zip)

**Comment by MrGrigri** [comment]
Very surprised that we didn't have this one.

**Comment by nilsfast** [comment]
Hey MrGrigri,
can one still become contributor?

**Comment by Templarian** [comment]
@nilsfast Nice timing. Yeah, we'll let these two count toward yours (he has enough icons 🤣). 5 icons and it gets created. 👍

**Comment by MrGrigri** [comment]
Let's clarify: 5 icons and your **contributor account** gets created. The icon will get added in a future release. For future reference, if you wish to contribute an icon, you must provide the icon and conform to MD guidelines.

**Comment by Templarian** [comment]
Added to the shared contributor account until they hit 5 icons.

**Comment by nilsfast** [comment]
Thank you very much for your support!
