### ISSUE TITLE
phone-hangup-outline

### ISSUE THREAD

**Issue by nilsfast** [Templarian/MaterialDesign#4793]
I have:

- [x ] Searched open issues to make sure there isn't a request for this icon.
- [x ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/58486458/73474793-5a254e00-438f-11ea-8b59-15c0ece33a0d.png)

## Zip Download

[phone-hangup-outline.zip](https://github.com/Templarian/MaterialDesign/files/4135398/phone-hangup-outline.zip)

**Comment by MrGrigri** [comment]
We already have a [phone-hangup-outline](https://materialdesignicons.com/icon/phone-hangup-outline)

![phone-hangup-outline](https://materialdesignicons.com/icon/phone-hangup-outline)
