### ISSUE TITLE
account-details-outline

### ISSUE THREAD

**Issue by nilsfast** [Templarian/MaterialDesign#4794]
I have:

- [X ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by CoDEmanX** [comment]
Duplicate of #4773, will be published as part of v4.9
