### ISSUE TITLE
incognito-off

### ISSUE THREAD

**Issue by nilsfast** [Templarian/MaterialDesign#4795]
I have:

- [ X] Searched open issues to make sure there isn't a request for this icon.
- [ X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/58486458/73525924-6bfb0580-4410-11ea-81e3-9e196fa311b6.png)

## Zip Download

[incognito-off.zip](https://github.com/Templarian/MaterialDesign/files/4138382/incognito-off.zip)

**Comment by MrGrigri** [comment]
I believe the off bar needs to be lower in the bottom right by one or two pixels.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73555529-180f1180-444e-11ea-8f15-4db2f427b697.png)

l think that fixed it.

**Comment by goyney** [comment]
This would be the correct `-off` variant for `incognito`.

![image](https://user-images.githubusercontent.com/1015040/73586591-77d0e100-447d-11ea-82a1-e7cf15c1fa14.png)
[incognito.svg.zip](https://github.com/Templarian/MaterialDesign/files/4142121/incognito.svg.zip)

**Comment by nilsfast** [comment]
Why am I not assigned?

**Comment by nilsfast** [comment]
Thank you

**Comment by goyney** [comment]
I blame operating on little to no sleep for a week. Thanks for taking care of that @MrGrigri.

**Comment by goyney** [comment]
[![incognito-off](https://materialdesignicons.com/icon/incognito-off)](https://materialdesignicons.com/icon/incognito-off)

Note: `incognito-off` replaced `basecamp` in the v5.0 release.
