### ISSUE TITLE
compass-rose

### ISSUE THREAD

**Issue by JAD92** [Templarian/MaterialDesign#4796]
## Usage

In my case as an icon to accompany my wind direction sensor on Home Assistant. The current icons that exist under a compass search are not quite what I am looking for.

Thanks in advance if this is accepted!

## Examples

![image](https://user-images.githubusercontent.com/49363398/73534220-79b48900-4418-11ea-99d3-ae2ad595a41f.png)

**Comment by MrGrigri** [comment]
I believe what you are looking for is the 'compass rose'. Is this correct?

**Comment by JAD92** [comment]
Hi, yes that is correct. A much better description/name than just compass, thanks.

**Comment by MrGrigri** [comment]
I've got a couple of options.

![image](https://user-images.githubusercontent.com/4528551/73555076-2d624c80-440a-11ea-945b-6a4a8d55c9be.png)
![image](https://user-images.githubusercontent.com/4528551/73555102-3b17d200-440a-11ea-8491-9b8b419ae92e.png)
![image](https://user-images.githubusercontent.com/4528551/73555128-45d26700-440a-11ea-9a1f-23616667d89e.png)

**Comment by PeterShaggyNoble** [comment]
`1b` gets my vote of the 3.

Remove the extra points from `2`, though, and we've got a nice shuriken icon! (Do we have one already, maybe?)

**Comment by MrGrigri** [comment]
I don't believe we do. I'll have to look through the history to see if there has been a request

**Comment by JAD92** [comment]
I quite like 2 and 1b. Is it possible in 1b to have the current internal blue triangles mirrored in place? Almost looking like smaller arrows within the main compass directions?
I'm very grateful for the speed that these examples came through!

**Comment by MrGrigri** [comment]
@JAD92, I believe we'll be going with option two. As far as the triangle cutouts, because of Material Design guidelines, we cannot mirror the cutouts.

**Comment by MrGrigri** [comment]
## Resources 

[compass-rose.zip](https://github.com/Templarian/MaterialDesign/files/4140522/compass-rose.zip)

**Comment by JAD92** [comment]
Not a problem, I appreciate even having the request looked at. Thanks guys.

**Comment by CoDEmanX** [comment]
I think it would be slightly better to move the inner tips outwards more, so that the width is consistent and the countershape more pronounced:

![grafik](https://user-images.githubusercontent.com/1309249/73584385-4addf780-4498-11ea-894c-59238a3e1313.png)

Actually not too bad:

![grafik](https://user-images.githubusercontent.com/1309249/73584559-76151680-4499-11ea-88d3-34538fc92940.png)

**Comment by goyney** [comment]
[![compass-rose](https://materialdesignicons.com/icon/compass-rose)](https://materialdesignicons.com/icon/compass-rose)
