### ISSUE TITLE
bookmark-check-outline

### ISSUE THREAD

**Issue by KasaP-AndroDev** [Templarian/MaterialDesign#4797]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use this icon in android app for show bookmarked items.
I need Vector Drawable (.xml)

## Examples

![bookmark-check](https://user-images.githubusercontent.com/59648393/73536995-88149c00-443c-11ea-9ca8-5c10c7eee51c.png)

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/73539941-e470bf00-442e-11ea-9d1a-723c33922758.png)

[bookmark-check-outline.zip](https://github.com/Templarian/MaterialDesign/files/4139287/bookmark-check-outline.zip)

**Comment by KasaP-AndroDev** [comment]
> ![grafik](https://user-images.githubusercontent.com/1309249/73539941-e470bf00-442e-11ea-9d1a-723c33922758.png)
> 
> [bookmark-check-outline.zip](https://github.com/Templarian/MaterialDesign/files/4139287/bookmark-check-outline.zip)

Thank you CoDEmanX

**Comment by goyney** [comment]
[![bookmark-check-outline](https://materialdesignicons.com/icon/bookmark-check-outline)](https://materialdesignicons.com/icon/bookmark-check-outline)
