### ISSUE TITLE
bookmark-remove-outline, bookmark-music-outline

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4798]
The cross is 8.82dp long in the filled variant, but it looks too large in an outline variant:

![grafik](https://user-images.githubusercontent.com/1309249/73540226-a758fc80-442f-11ea-971b-c08c6bdf0d7d.png)

8dp looks alright:

![grafik](https://user-images.githubusercontent.com/1309249/73540364-00289500-4430-11ea-9f6b-864c5e247517.png)

I think in the bookmark-music-outline icon it's better to use the long note tail like in the filled variant, despite that the gap is only 1dp:

![grafik](https://user-images.githubusercontent.com/1309249/73540830-3adefd00-4431-11ea-89f5-e2122f7f5cc5.png) ![grafik](https://user-images.githubusercontent.com/1309249/73540771-14b95d00-4431-11ea-8984-290181d69fd6.png)

[bookmark-outlines.zip](https://github.com/Templarian/MaterialDesign/files/4139451/bookmark-outlines.zip)

**Comment by goyney** [comment]
[![bookmark-remove-outline](https://materialdesignicons.com/icon/bookmark-remove-outline)](https://materialdesignicons.com/icon/bookmark-remove-outline)[![bookmark-music-outline](https://materialdesignicons.com/icon/bookmark-music-outline)](https://materialdesignicons.com/icon/bookmark-music-outline)
