### ISSUE TITLE
cup-off-outline

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4799]
To complete the set, possible use case would be "no cups allowed" as in don't litter or don't bring your own cups to an event (specifically refering to the vessel, not the liquid)

![grafik](https://user-images.githubusercontent.com/1309249/73541423-af666b80-4432-11ea-98fe-4ea811c518a5.png)

[cup-off-outline.zip](https://github.com/Templarian/MaterialDesign/files/4139487/cup-off-outline.zip)

**Comment by goyney** [comment]
[![cup-off-outline](https://materialdesignicons.com/icon/cup-off-outline)](https://materialdesignicons.com/icon/cup-off-outline)
