### ISSUE TITLE
bunk-bed-outline, hotel-outline

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4800]
By me:

![grafik](https://user-images.githubusercontent.com/1309249/73542833-dd997a80-4435-11ea-9135-80b8647bcdd2.png)

By Google:

![grafik](https://user-images.githubusercontent.com/1309249/73542901-09b4fb80-4436-11ea-93f2-597c7dd9103b.png)

[hotel-bed-outline.zip](https://github.com/Templarian/MaterialDesign/files/4139581/hotel-bed-outline.zip)

**Comment by JamesCoyle** [comment]
Shouldn't we rename hotel to bed? It isn't showing a hotel at all.

**Comment by CoDEmanX** [comment]
Good point! Marking it as a breaking change. We should probably go through all icons for v5.0 and check that their primary name describes what is depicted and add other names as aliases #4324

**Comment by goyney** [comment]
[![bunk-bed-outline](https://materialdesignicons.com/icon/bunk-bed-outline)](https://materialdesignicons.com/icon/bunk-bed-outline)

Note: `bunk-bed-outline` has replaced `beats` in v5.0.

**Comment by goyney** [comment]
[![bed-outline](https://materialdesignicons.com/icon/bed-outline)](https://materialdesignicons.com/icon/bed-outline)

Note: `bed-outline` has replaced `behance` in v5.0.

**Comment by goyney** [comment]
`hotel` renamed `bed.
