### ISSUE TITLE
shuriken

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4801]
## Request

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

This was brought up in #4796

## Preview

![image](https://user-images.githubusercontent.com/4528551/73555888-9c8c7080-440b-11ea-9565-fa620da2ff6d.png)

## Zip Download

[shuriken.zip](https://github.com/Templarian/MaterialDesign/files/4140408/shuriken.zip)

**Comment by CoDEmanX** [comment]
For the compass rose I can see that you would need the entire canvas, but there is not much going here - how about scaling it down to 20dp?

**Comment by goyney** [comment]
[![shuriken](https://materialdesignicons.com/icon/shuriken)](https://materialdesignicons.com/icon/shuriken)
