### ISSUE TITLE
International Space Station

### ISSUE THREAD

**Issue by HemiBob** [Templarian/MaterialDesign#4803]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by HemiBob** [comment]
Useful in software that displays sighting times

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73568075-f3c02e80-4467-11ea-94eb-e7d8947ceb5b.png)

**Comment by goyney** [comment]
Good start. I don't think we could really go any thicker with the lines on the solar panels, however, they do need to be aligned to the grid.

**Comment by GreenTurtwig** [comment]
Might also be worth just naming it `space-station`.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/73570283-63381d00-446c-11ea-8dd0-ef284e3b8c87.png)

Like so?

**Comment by HemiBob** [comment]
"Assigned to me" - I'm new to all this, do I have to do something, like close it.
Thanks guys, what a superb job.

**Comment by goyney** [comment]
Nope, that's just our way of tracking who it will get assigned to in our system once we add it. We'll close this issue and mark the version in the milestone once it has been added to the library.

**Comment by CoDEmanX** [comment]
@goyney Shouldn't it be assigned to nilsfast?

**Comment by Templarian** [comment]
Yeah, I think that was an accident. 👍  Assigned to the right person.

**Comment by goyney** [comment]
[![space-station](https://materialdesignicons.com/icon/space-station)](https://materialdesignicons.com/icon/space-station)
