### ISSUE TITLE
Production Possibilities Frontier

### ISSUE THREAD

**Issue by PedroCuadra** [Templarian/MaterialDesign#4804]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Hi MDI-team. Hoping you are having a great day, i'm building an application and I dont find any simillar to represent the title. I imagine this pretty simple: a XY positive chart with a quarter circle arc in it. About its name it could be `mdi-chart-production-posibilities-frontier` or `mdi-chart-ppf`, or inclusive `mdi-chart-quarter-arc` in order to be more generic.

## Examples

![imagen](https://user-images.githubusercontent.com/14881608/73572519-c1a2d280-444f-11ea-8c30-9041a41f5115.png)

![imagen](https://user-images.githubusercontent.com/14881608/73572672-252d0000-4450-11ea-9d9e-c3dbc2e8a596.png)

**Comment by goyney** [comment]
I'm going to leave this open, because you at least provided a use case and examples.... But please **do not remove our issue template** in the future. That is grounds for an immediate closure.

**Comment by PedroCuadra** [comment]
Oh, I'm sorry, It was not my intention. I'm new contibuting.

**Comment by CoDEmanX** [comment]
First time I come across this kind of chart. An interesting one for sure. If this works for your then why not:

![grafik](https://user-images.githubusercontent.com/1309249/73582940-d69f5600-448f-11ea-8547-3fd7acdc73f5.png)

Could be mistaken for a right angle despite it's slight oval shape perhaps... But adding other elements is kinda weird:

![grafik](https://user-images.githubusercontent.com/1309249/73583072-7c52c500-4490-11ea-8322-6d8edc301682.png) ![grafik](https://user-images.githubusercontent.com/1309249/73583218-4530e380-4491-11ea-8814-f5f077c25a50.png)
![grafik](https://user-images.githubusercontent.com/1309249/73583269-87f2bb80-4491-11ea-8d8a-5e2b24f937c1.png) ![grafik](https://user-images.githubusercontent.com/1309249/73583388-2121d200-4492-11ea-97da-e291a9a96e9d.png)

[chart-ppf.zip](https://github.com/Templarian/MaterialDesign/files/4141957/chart-ppf.zip)

**Comment by PedroCuadra** [comment]
That's perfect. The simpler, the better. Anyway, I'm going to use it in a menu, so, it's quite descriptive. Thank you.

**Comment by goyney** [comment]
[![chart-ppf](https://materialdesignicons.com/icon/chart-ppf)](https://materialdesignicons.com/icon/chart-ppf)
