### ISSUE TITLE
MoMA human icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4805]
Tried to recreate them closely, but the first is weird with the kid shifted 0.5dp off grid.

![grafik](https://user-images.githubusercontent.com/1309249/73586810-e54b3480-44b2-11ea-93aa-07562ba55b35.png)

I think it's better like this:

![grafik](https://user-images.githubusercontent.com/1309249/73586893-3576c680-44b4-11ea-8051-0399e104e079.png)

The other two are unproblematic:

![grafik](https://user-images.githubusercontent.com/1309249/73586816-0744b700-44b3-11ea-953c-8a3a0179aabd.png)
![grafik](https://user-images.githubusercontent.com/1309249/73586823-1fb4d180-44b3-11ea-916a-e4ad70120c8b.png)

Really unsure how to name these and who to contribute them to - MoMA Design Studios, Google, Seheely?

[moma-humans.zip](https://github.com/Templarian/MaterialDesign/files/4142147/moma-humans.zip)

**Comment by Templarian** [comment]
A contributor account was added for these. So feel free to add them to that.

**Comment by CoDEmanX** [comment]
Okay, account is called moma (note to self). Please help me find good names for them.

I tweaked the first icon again to get rid of some of the blur. WDYT?

![grafik](https://user-images.githubusercontent.com/1309249/73593858-a5af3780-4508-11ea-8052-4cc0a10f1e5f.png)

[human-male-child3.zip](https://github.com/Templarian/MaterialDesign/files/4142662/human-male-child3.zip)

**Comment by goyney** [comment]
[![human-male-child](https://materialdesignicons.com/icon/human-male-child)](https://materialdesignicons.com/icon/human-male-child)[![human-wheelchair](https://materialdesignicons.com/icon/human-wheelchair)](https://materialdesignicons.com/icon/human-wheelchair)
[![human-baby-changing-table](https://materialdesignicons.com/icon/human-baby-changing-table)](https://materialdesignicons.com/icon/human-baby-changing-table)
