### ISSUE TITLE
contacts-outline

### ISSUE THREAD

**Issue by nilsfast** [Templarian/MaterialDesign#4807]
I have:

- [X] Searched open issues to make sure there isn't a request for this icon.
- [  ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/58486458/73592722-6fb88600-44fd-11ea-822b-aa78f8d2d795.png)

![image](https://user-images.githubusercontent.com/58486458/73592732-84951980-44fd-11ea-9f2c-fb07cededa39.png)

## Zip Download
[contacts-outline.zip](https://github.com/Templarian/MaterialDesign/files/4142582/contacts-outline.zip)

**Comment by CoDEmanX** [comment]
This exists as stock Google icon (with the person silhouette outlined as well however), as well as two related ones:

![grafik](https://user-images.githubusercontent.com/1309249/73593469-194f4580-4505-11ea-91cf-df2977176acb.png)

https://material.io/resources/icons/?search=contact&style=outline

**Comment by MrGrigri** [comment]
@nilsfast, thanks for your contribution...but we tend to stick with Google if they have one.

**Comment by Templarian** [comment]
But do let us know if one exists in Google's that we need to add. There are quite a few random ones we may have glanced over.

**Comment by Templarian** [comment]
This replaced `wunderlist` for 5.0. ✅
