### ISSUE TITLE
camera-switch-outline

### ISSUE THREAD

**Issue by nilsfast** [Templarian/MaterialDesign#4808]
I have:

- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/58486458/73593123-93c99680-4500-11ea-9ba2-495d56fbf7c7.png)

## Zip Download

[camera-switch-outline.zip](https://github.com/Templarian/MaterialDesign/files/4142606/camera-switch-outline.zip)

**Comment by CoDEmanX** [comment]
This does exist as stock Google icon, as well as a camcorder switch icon:
https://material.io/resources/icons/?search=switch&style=outline

![grafik](https://user-images.githubusercontent.com/1309249/73593308-fb80e100-4502-11ea-8b2d-ef2218520083.png)

**Comment by goyney** [comment]
[![camera-switch-outline](https://materialdesignicons.com/icon/camera-switch-outline)](https://materialdesignicons.com/icon/camera-switch-outline)[![video-switch-outline](https://materialdesignicons.com/icon/video-switch-outline)](https://materialdesignicons.com/icon/video-switch-outline)

**Comment by goyney** [comment]
Note: `camera-switch-outline` replaced `accusoft` and `video-switch-outline` replaced `android-head` in v5.0.
