### ISSUE TITLE
box-cutter-off

### ISSUE THREAD

**Issue by nilsfast** [Templarian/MaterialDesign#4809]
I have:

- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/58486458/73597211-f1bea400-4529-11ea-8868-3b066f1acfeb.png)

## Zip Download

[box-cutter-off.zip](https://github.com/Templarian/MaterialDesign/files/4143101/box-cutter-off.zip)

**Comment by nilsfast** [comment]
I think this is my fifth icon.

**Comment by Templarian** [comment]
We already created you one earlier so you would get attribution in `4.9.95` 👍 (3 of them). We can work on getting details added later: https://materialdesignicons.com/contributor/nilsfast

![example](https://user-images.githubusercontent.com/338885/73600800-2ecf6a00-451b-11ea-9ae4-bcb440012d33.png)

We're working on making templates more universal in EPS format, until then hopefully this above image gives you a better idea. The off slash needs to be cut off at moved at half pixel increments and cut off at the ends. This is the pattern MD uses for all `-off`. Seems very subtle, but creates a nice consistency.

**Comment by Templarian** [comment]
@nilsfast 1.8 width, ignore that I accidentally used 2dp. Cutouts are a bit different. Definitely use the template in this repo.

![image](https://user-images.githubusercontent.com/338885/73601249-9689b300-4523-11ea-9c56-329f4b3ec0ae.png)

**Comment by nilsfast** [comment]
I think it is right now:

![image](https://user-images.githubusercontent.com/58486458/73606227-89fb6e00-45a8-11ea-9591-e85489b684b7.png)

**Comment by goyney** [comment]
[![box-cutter-off](https://materialdesignicons.com/icon/box-cutter-off)](https://materialdesignicons.com/icon/box-cutter-off)

Note: `box-cutter-off` replaced `strava` in the v5.0 release.
