### ISSUE TITLE
Icon Request: Tasks and Subtasks

### ISSUE THREAD

**Issue by brenjt** [Templarian/MaterialDesign#481]
Icons to represent a list of tasks and subtasks.

**Comment by CoDEmanX** [comment]
Have you seen the `assignment` icons by google?
https://www.google.com/design/icons/

**Comment by Templarian** [comment]
Called `clipboard-*` on https://materialdesignicons.com/

**Comment by ayozebarrera** [comment]
assignment icons works for me, thanks :D

**Comment by justinlawrence** [comment]
I would really appreciate a separate subtask icon. Something like this:

![subtask](https://user-images.githubusercontent.com/1521183/32338752-9757b4fc-bfed-11e7-9c79-ba8e5734cb6d.png)

Thanks guys!

**Comment by PeterShaggyNoble** [comment]
@justinlawrence, would `file-tree` or `sitemap` suit your needs?

[![](https://materialdesignicons.com/icon/file-tree)](https://materialdesignicons.com/icon/file-tree) [![](https://materialdesignicons.com/icon/sitemap)](https://materialdesignicons.com/icon/sitemap)

**Comment by justinlawrence** [comment]
File tree is perfect, thanks!

Could you hook that up to the sub task search keyword?

Thanks for the quick response.

**Comment by PeterShaggyNoble** [comment]
Alias `subtasks` added to `file-tree`. Also aliased the relevant `clipboard-*` icons with their Google `assignment-*` names.

Closing this issue out now, due to a lack of response from the OP.

**Comment by justinlawrence** [comment]
Thanks Peter!
