### ISSUE TITLE
Untangle UTM Logo

### ISSUE THREAD

**Issue by anderbak** [Templarian/MaterialDesign#4810]
Was hoping to add the Untangle UTM logo for use in Home Assistant. I thought something like this (black added to help with visibility) might work based on the Ubuntu logo.

![image](https://user-images.githubusercontent.com/29143113/73603311-c9956c00-454e-11ea-8e53-07522a7358f2.png)

Thanks!

[Untangle.svg..zip](https://github.com/Templarian/MaterialDesign/files/4143549/Untangle.svg.zip)

**Comment by Templarian** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by PeterShaggyNoble** [comment]
I've opened [an issue](https://github.com/simple-icons/simple-icons/issues/2519) for you for this over at Simple Icons.
