### ISSUE TITLE
buffet with picture 

### ISSUE THREAD

**Issue by nilsfast** [Templarian/MaterialDesign#4812]
I have:

- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/58486458/73606443-908ae500-45aa-11ea-98dd-b9728ed4e51b.png)

## Zip Download
[buffet-with-picture.zip](https://github.com/Templarian/MaterialDesign/files/4143770/buffet-with-picture.zip)

**Comment by JapanYoshi** [comment]
*How* could you possibly use this????

**Comment by nilsfast** [comment]
As an icon for a living room

**Comment by Mariusthvdb** [comment]
yes, it might be a bit niche, but I can use it ;-)

would you consider adding a light replacing the picture for a buffet-light-variation? Could be exactly what people use it for in the UI.

**Comment by goyney** [comment]
This complicates the icon in a way which does not add value. I don't think we should add this one.

**Comment by Templarian** [comment]
Simplify the buffet and put a TV on the wall. This icon can definitely work, just needs a lot of tweaks.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/74508699-44eb0c00-4ec5-11ea-8fd1-b59a9fa94c35.png)

**Comment by goyney** [comment]
I honestly don't know what that is supposed to be at native size.

**Comment by Templarian** [comment]
Going to close this one out. Would have been nice to represent a living room, but might not work.

**Comment by CoDEmanX** [comment]
Not very modern:

![grafik](https://user-images.githubusercontent.com/1309249/74791281-544dc900-52ba-11ea-9325-7ee5224b0a88.png)
