### ISSUE TITLE
Reproduction body feature explicit

### ISSUE THREAD

**Issue by Molodax** [Templarian/MaterialDesign#4813]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Dedicated medical mobile applications
Connected adult toys

## Examples

https://thenounproject.com/term/penis/1137803/

**Comment by goyney** [comment]
After some internal discussion, we don't feel this icon fits in MDI. Thank you for your suggesiton.

**Comment by Molodax** [comment]
It's a bit difficult to understand the logic behind why some concepts (e.g., icon emoticon-poop) fit, and others don't. Must admit that MDI is extremely skewed towards depicting machine-related features, but very poor on human/anatomic/medicine side. The last is going to be in demand soon but somewhere else.
Anyhow, thanks for the discussion at least.

**Comment by Templarian** [comment]
We do have a generalized `reproduction` icon that can be used for some use cases and various gender icons that might suffice.

There are better icon packs and libraries for anatomy related iconography. Utility/tech icons are the void this pack fills and this would be too niche.

**Comment by JamesCoyle** [comment]
Personally I'm all for icons of this nature if done in a tasteful, scientific way rather than an explicit way. Im of the belief the world needs to be more sex positive and better informed and if icons can help with that then I feel they should.
