### ISSUE TITLE
scooter-off

### ISSUE THREAD

**Issue by WideAngleDe** [Templarian/MaterialDesign#4814]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Based on scooter but stroke through like food-off to food.

**Comment by Templarian** [comment]
I pasted back in the template into each request. Do not delete the template!

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/73620388-b1315a00-45ff-11ea-92b5-af6653bb4175.png)
[scooter-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/4145956/scooter-off.svg.zip)

**Comment by goyney** [comment]
Don't know if this really works...

**Comment by CoDEmanX** [comment]
What I see is blind superman flying over a crossing with a cane

**Comment by goyney** [comment]
This doesn't work as an `off` variant and we're going to reject this request. Thanks for your suggestion!
