### ISSUE TITLE
Icon suggestion: ice-cream-off

### ISSUE THREAD

**Issue by WideAngleDe** [Templarian/MaterialDesign#4815]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Based on ice-cream but stroke through like food-off.

## Examples

Include any example images so we know what the icon should look like.

**Comment by CoDEmanX** [comment]
Unsure about the positioning of the off-stroke:

![grafik](https://user-images.githubusercontent.com/1309249/73616837-bd75e100-4618-11ea-849b-e6f850bb740e.png) ![grafik](https://user-images.githubusercontent.com/1309249/73616831-ab943e00-4618-11ea-93a4-65291b023737.png)
![grafik](https://user-images.githubusercontent.com/1309249/73616887-28bfb300-4619-11ea-921a-43147e1f8a6f.png)

We might to rename & replace our icon with Google's MIE icon:

![grafik](https://user-images.githubusercontent.com/1309249/73616911-599fe800-4619-11ea-8d69-81c9ec51b6c9.png)

Off variants I created:

![grafik](https://user-images.githubusercontent.com/1309249/73616916-7dfbc480-4619-11ea-8708-27ca1d6858fc.png) ![grafik](https://user-images.githubusercontent.com/1309249/73616928-98ce3900-4619-11ea-9525-fdec646ef62a.png)

[icecream.zip](https://github.com/Templarian/MaterialDesign/files/4145667/icecream.zip)

**Comment by goyney** [comment]
`ice-cream` updated. `ice-cream-off` added.

[![ice-cream](https://materialdesignicons.com/icon/ice-cream)](https://materialdesignicons.com/icon/ice-cream)[![ice-cream-off](https://materialdesignicons.com/icon/ice-cream-off)](https://materialdesignicons.com/icon/ice-cream-off)

Note: `ice-cream-off` replaced `nfc-off` in the v5.0 release.
