### ISSUE TITLE
roller-skate-off

### ISSUE THREAD

**Issue by WideAngleDe** [Templarian/MaterialDesign#4816]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Like roller-skate but stroke through.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/73620444-f5bcf580-45ff-11ea-8947-81fba5f4a913.png)
[roller-skate-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/4145958/roller-skate-off.svg.zip)

**Comment by goyney** [comment]
[![roller-skate-off](https://materialdesignicons.com/icon/roller-skate-off)](https://materialdesignicons.com/icon/roller-skate-off)

Note: `roller-skate-off` replaced `cisco-webex` in the v5.0 release.
