### ISSUE TITLE
rollerblade-off

### ISSUE THREAD

**Issue by WideAngleDe** [Templarian/MaterialDesign#4817]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Like rollerblade but stroke though.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/73620494-387ecd80-4600-11ea-97d0-17e0160f5498.png)
[rollerblade-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/4145969/rollerblade-off.svg.zip)

**Comment by goyney** [comment]
[![rollerblade-off](https://materialdesignicons.com/icon/rollerblade-off)](https://materialdesignicons.com/icon/rollerblade-off)
