### ISSUE TITLE
Remove: amazon-drive

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4818]
Our `amazon-drive` brand icon is simply a cloud which I cannot find anywhere on their current site. The "legacy" iOS and Android app icons have the Amazon A over the top of a cloud. Not sure where this icon came from our how it could ever be tied to a brand because of its generic nature. I recommend we remove it.

[![amazon-drive](https://materialdesignicons.com/icon/amazon-drive)](https://materialdesignicons.com/icon/amazon-drive)

**Comment by Templarian** [comment]
https://developer.amazon.com/docs/amazon-drive/ad-brand-guidelines.html

They have branding guidelines, but I'm not sure if that will work for our use case.

**Comment by goyney** [comment]
This brand icon has been removed in v5.0.
