### ISSUE TITLE
Remove: google-glass

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4824]
The Google Glass logo is a wordmark, and we currently just have the Google G as the icon. Not sure where that came from, but it's not official. If we're just using the G, we should remove `google-glass`.

**Comment by PeterShaggyNoble** [comment]
The `G` is from Material Icons Extended but their official icon, which can be found [here](https://developers.google.com/glass/tools-downloads/downloads) is the `A` from their logo, boxed.

**Comment by Templarian** [comment]
https://www.google.com/glass/start/ It's their logo for this I think?

**Comment by goyney** [comment]
[![google-glass](https://materialdesignicons.com/icon/google-glass)](https://materialdesignicons.com/icon/google-glass)
