### ISSUE TITLE
Discussion: NPM

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4828]
NPM is an interesting brand. They do not provide their logos. In fact, they state you must receive special permission from them to use them.

That being said, we have three `npm`, `npm-variant`, and `npm-variant-outline` (which is actually not an outline compared to our use of that word).

I believe we should keep `npm` and remove `npm-variant(-outline)` since we have no permission to change their logo.

**Comment by Templarian** [comment]
We may want to reach out and see what their preference is and remove any/all that do not work. Would like to have a more correct representation for v5.

**Comment by goyney** [comment]
Removed the variants.
