### ISSUE TITLE
Dropbox font icon

### ISSUE THREAD

**Issue by BasitAli** [Templarian/MaterialDesign#483]
The dropbox font icon does not look correct however the svg icon is fine. See screenshot below,

![image](https://cloud.githubusercontent.com/assets/869390/8513224/14ae7b78-237b-11e5-8565-65e432c9ba37.png)

What may be causing this?

**Comment by Templarian** [comment]
I'm looking at: https://cdn.materialdesignicons.com/1.1.34/ and it looks fine.

To debug further I need to know your browser engine/version and the OS.

**Comment by Templarian** [comment]
[v1.1.70](http://cdn.materialdesignicons.com/1.1.70/) was just released tonight, but I don't think it will fix anything you are seeing. Let me know the details requested above so it can be debugged this week.

**Comment by basitali** [comment]
I see the same issue on https://cdn.materialdesignicons.com/1.1.34/. I am running Chrome Version 43.0.2357.130 (64-bit) on Mac. v1.1.70 has the same issue as well.

![image](https://cloud.githubusercontent.com/assets/869390/8517951/1d181c88-23df-11e5-9419-bb2db55d885f.png)

**Comment by Templarian** [comment]
I've verified this with others. It appears to be a bug in Mac's font rendering for Woff2. I'll tweak the vector paths and hope it gets fixed in the next release. For now it's going to look a little off.

**Comment by basitali** [comment]
Awesome, thanks. I was first using the icons in Polymer as svg and they were just perfect. But now in angular as font icon it had this tiny glitch. Thanks for the great package.

**Comment by Templarian** [comment]
Fixed, this will be in the `v1.2.64` release.

Thanks.

**Comment by BasitAli** [comment]
Awesome, verified at https://cdn.materialdesignicons.com/1.2.64/.
