### ISSUE TITLE
Remove: pinterest-box

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4832]
> Our logo is a red circle with a white scripted “P” in the middle. Use the EPS and high resolution PNGs provided below. Do not alter them in any way, and keep the badge free of filters and effects.

https://business.pinterest.com/en/pinterest-brand-guidelines

**Comment by Templarian** [comment]
Agreed with this update. This whole lets add a `-box` was a bad idea to a lot of these logos.

**Comment by goyney** [comment]
Removed.
