### ISSUE TITLE
account-card-details-star(-outline)

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#4838]
## Request

I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Represents a favorite contact

## Preview

![image](https://user-images.githubusercontent.com/4528551/73782508-72121e80-474f-11ea-8e4c-6e45cf3d4c5f.png) ![image](https://user-images.githubusercontent.com/4528551/73782554-8524ee80-474f-11ea-95a0-2a42e93c37b3.png)

## Zip Download

[account-card-star.zip](https://github.com/Templarian/MaterialDesign/files/4155787/account-card-star.zip)

**Comment by goyney** [comment]
[![account-card-details-star](https://materialdesignicons.com/icon/account-card-details-star)](https://materialdesignicons.com/icon/account-card-details-star)[![account-card-details-star-outline](https://materialdesignicons.com/icon/account-card-details-star-outline)](https://materialdesignicons.com/icon/account-card-details-star-outline)

Note: `account-card-details-star` replaced `github-box`. `account-card-details-star-outline` replaced `github-face`. Both in the v5.0 release.
