### ISSUE TITLE
Missing Material text_fields icon

### ISSUE THREAD

**Issue by derked27** [Templarian/MaterialDesign#4839]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like to be able to use the `text_fields` icon that is part of the material icons.

## Examples
![image](https://user-images.githubusercontent.com/17728637/73791039-d1c3f600-475e-11ea-9716-7cecf3764645.png)

https://material.io/resources/icons/?search=text_&icon=text_fields&style=baseline

**Comment by PeterShaggyNoble** [comment]
We have `format-size`, which is the same icon horizontally flipped.

**Comment by goyney** [comment]
Our is credited to Google, so it looks like they updated this. Should we not update ours?

**Comment by Templarian** [comment]
Yeah, lets just update ours to match and alias `font-size`.

**Comment by goyney** [comment]
Updated and aliased.
