### ISSUE TITLE
Update apple-ios?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4840]
First we need to decide whether we want to continue using Google's version of this icon or update to the official logo. My own view on it is that Google taking liberties with other brands probably isn't a good enough reason for us to do the same and that we should update.

[![apple-ios](https://user-images.githubusercontent.com/15157491/73838335-62f0a680-480b-11ea-82d6-028706c39cef.png)](https://github.com/Templarian/MaterialDesign/files/4159230/apple-ios.zip)

**Comment by goyney** [comment]
Updated.
