### ISSUE TITLE
Update babel?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4841]
Our Babel icon is missing the inner detail. If we're updating our remaining brand icons to be more faithful to the originals, we should probably update this one too.

[![babel](https://user-images.githubusercontent.com/15157491/73838682-27a2a780-480c-11ea-9337-02bdd3167f11.png)](https://github.com/Templarian/MaterialDesign/files/4159258/babel.zip)

**Comment by goyney** [comment]
Updated.
