### ISSUE TITLE
Discussion: Update bluetooth?

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4842]
This one's tricky - use of the Bluetooth symbol without the oval is _incredibly_ common but [their brand guidelines](https://www.bluetooth.com/develop-with-bluetooth/marketing-branding/) _do_ state:

> **INCORRECT**
Adding drop shadow, graphic emboss, or applying other graphic alterations to
the logo including **removing the oval** or placing the Runic B in other shapes

And, of course, there's the knock-on effect on all of our other `*-bluetooth` icons to consider.

[![bluetooth](https://user-images.githubusercontent.com/15157491/73839505-10fd5000-480e-11ea-83fe-1e5affd50554.png)](https://github.com/Templarian/MaterialDesign/files/4159296/bluetooth.zip)

**Comment by goyney** [comment]
My vote is no. Microsoft doesn't follow this, Apple doesn't follow this, and it complicates all of our variants.

**Comment by PeterShaggyNoble** [comment]
Forgot to include my vote above, which is also to stick to our current version.

We should keep an eye on things, though, as those guidelines are relatively new, dated October 2019. If everyone updates to adhere to them then we may yet have to follow suit, somehow.

**Comment by goyney** [comment]
Leaving our alone for now. We can reevaluate if things seem to be changing.
