### ISSUE TITLE
Rename microsoft-dynamics

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4845]
The parent Microsoft Dynamics brand doesn't have an icon of its own, our `microsoft-dynamics` icon is the logo of the sub-brand Dynamics 365 so we should update the name of ours to `dynamics-365`.

**Comment by goyney** [comment]
`microsoft-dynamics-365` or `dynamics-365`?

**Comment by Templarian** [comment]
Lets keep the prefix `microsoft` for these to keep them linked to the parent company.

**Comment by PeterShaggyNoble** [comment]
I'm not _entirely_ sure - even [their brand guidelines](http://thepartnerchannel.com/wp-content/uploads/Dynamics365_styleguide_092816.pdf) use both versions. I've been using its [Wikipedia page](https://en.m.wikipedia.org/wiki/Microsoft_Dynamics_365) where it's just "Dynamics 365" as the tie-breaker. Although I've just now noticed that, confusingly, the URL includes "Microsoft" :man_shrugging: No harm in us keeping the `microsoft`, I suppose, it'll at least save the alias.

**Comment by goyney** [comment]
Updated to `microsoft-dynamics-365`.
