### ISSUE TITLE
Update existing Microsoft Office icons & Add remaining ones

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4847]
Microsoft updated the branding of all its Office products a while back so we need to update our related icons. An SVG of them all (bar Access, which we don't have an icon for anyway) can be found at https://blobs.officehome.msocdn.com/images/content/images/whatisoffice365-apps-2436adcc5c.svg and the icons we need to update are:

- [x] `onenote`
- [x] `outlook`
- [x] `yammer`

And the ones we need to add are:
- [x] `access`
- [x] `excel`
- [x] `powerpoint`
- [x] `sharepoint`
- [x] `teams`
- [x] `word`

**Comment by goyney** [comment]
Yammer doesn't need to be updated: https://yammerassets.blob.core.windows.net/assets/sites/12/2014/07/Yammer_BrandIdentityGuidelines-1.pdf

**Comment by goyney** [comment]
Additionally, these icons don't work in monochrome. I made the case for removing these the other night in Slack, but was overruled.

**Comment by PeterShaggyNoble** [comment]
From the URL, it looks like those guidelines for Yammer are from 2014, whereas the rebrand was in 2018.

I think I _might_ have found monochrome versions of _all_ of these buried in a font. Investigating now ...

**Comment by PeterShaggyNoble** [comment]
**SUCCESS!** 😁
Found them in [this font file](https://partnerresources.azureedge.net/public/2020.1.28.1/fonts/DevCMDL2.woff), in use on [this page](https://developer.microsoft.com/en-us/yammer)

[![onenote](https://user-images.githubusercontent.com/15157491/73852868-d56f7f80-4827-11ea-80bf-080697cce686.png)![outlook](https://user-images.githubusercontent.com/15157491/73853073-2aab9100-4828-11ea-9984-796580716eb2.png)![Yammer](https://user-images.githubusercontent.com/15157491/73853245-7827fe00-4828-11ea-831c-d0f5199f9a0d.png)](https://github.com/Templarian/MaterialDesign/files/4160198/office.zip)

**Comment by goyney** [comment]
Should we just add all the apps then?

CC: @Templarian

**Comment by PeterShaggyNoble** [comment]
Here they are if we do decide to add them:

[![access](https://user-images.githubusercontent.com/15157491/73859810-8c70f880-4832-11ea-8b49-223cbf7e0451.png)![excel](https://user-images.githubusercontent.com/15157491/73859941-bd512d80-4832-11ea-9878-86fcaa690055.png)![powerpoint](https://user-images.githubusercontent.com/15157491/73860077-effb2600-4832-11ea-8bbc-0046af307675.png)![sharepoint](https://user-images.githubusercontent.com/15157491/73860226-2042c480-4833-11ea-8939-990d1ad9a233.png)![teams](https://user-images.githubusercontent.com/15157491/73860347-55e7ad80-4833-11ea-93c3-01d7f6bc301d.png)![word](https://user-images.githubusercontent.com/15157491/73860445-77e13000-4833-11ea-853e-caac98efcd2d.png)](https://github.com/Templarian/MaterialDesign/files/4160655/office.zip)

**Comment by Templarian** [comment]
Yeah, might as well. They will definitely be useful for devs.

**Comment by goyney** [comment]
All updated and added with `microsoft-`prefixes.
