### ISSUE TITLE
Update reddit

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4848]
Reddit's [brand guidelines](https://www.redditinc.com/assets/press-resources/reddit_brand_guidelines_20180314.pdf) allow for the use of the alien completely filled.

[![reddit](https://user-images.githubusercontent.com/15157491/73843860-612ce000-4817-11ea-91a1-dd645fc90614.png)](https://github.com/Templarian/MaterialDesign/files/4159569/reddit.zip)

**Comment by goyney** [comment]
I feel like our circle version is much more recognizable and vote to keep it.

[![reddit](https://materialdesignicons.com/icon/reddit)](https://materialdesignicons.com/icon/reddit)

**Comment by PeterShaggyNoble** [comment]
On reflection, using the circle version allows people to use it both as a logo representation of the brand and as a social icon while adhering to their guidelines so, I agree, let's stick with that.
