### ISSUE TITLE
Slider Icon for (filter settings) Icon Request

### ISSUE THREAD

**Issue by techsin** [Templarian/MaterialDesign#485]
i have seen this icon in setting on my android phone,

basically it's i think 3 lines with sliders on each of them.

**Comment by Templarian** [comment]
This will be synced in with issue #420.

**Comment by CoDEmanX** [comment]
Yet to be added: https://design.google.com/icons/#ic_tune

**Comment by PeterShaggyNoble** [comment]
This was added in v1.6.50

[![](https://materialdesignicons.com/icon/tune)](https://materialdesignicons.com/icon/tune) [![](https://materialdesignicons.com/icon/tune-vertical)](https://materialdesignicons.com/icon/tune-vertical)

**Comment by techsin** [comment]
Awesome

**Comment by techsin** [comment]
took years to add an icon but we are there
lol

**Comment by PeterShaggyNoble** [comment]
They were actually added back in April of last year with the release the following month 😆

But, yeah, occasionally it can take a while to add an icon - there are a lot of requests to get through 😉
