### ISSUE TITLE
Update unicode

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4851]
Two options here, but it looks like they use the boxed version only.

[![unicode](https://user-images.githubusercontent.com/15157491/73856805-ecb16b80-482d-11ea-9931-2028b1fbd272.png)![unicode](https://user-images.githubusercontent.com/15157491/73856977-28e4cc00-482e-11ea-9c95-d4df03c1c18f.png)](https://github.com/Templarian/MaterialDesign/files/4160420/unicode.zip)

**Comment by goyney** [comment]
Updated ours with the second version. Since both are acceptable, people can choose to box it in or not.
