### ISSUE TITLE
Update whatsapp

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4852]
Our current WhatsApp icon (overlaid in red below) is slightly off compared to the official version available at https://whatsappbrand.com/

[![whatsapp](https://user-images.githubusercontent.com/15157491/73858976-30f23b00-4831-11ea-832a-14009dfd57a5.png)](https://github.com/Templarian/MaterialDesign/files/4160553/whatsapp.zip)

**Comment by goyney** [comment]
Updated.
