### ISSUE TITLE
Solar panel

### ISSUE THREAD

**Issue by aztuk** [Templarian/MaterialDesign#4855]
I have:

- [ x ] Searched open issues to make sure there isn't a request for this icon.
- [ x ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/48598254/73919526-056c6080-48c4-11ea-9476-e4b75bf5d649.png)

## Zip Download
[solar-panel.zip](https://github.com/Templarian/MaterialDesign/files/4163981/solar-panel.zip)

**Comment by goyney** [comment]
Already exists.
[![solar-panel](https://materialdesignicons.com/icon/solar-panel)](https://materialdesignicons.com/icon/solar-panel)[![solar-panel-large](https://materialdesignicons.com/icon/solar-panel-large)](https://materialdesignicons.com/icon/solar-panel-large)
