### ISSUE TITLE
Prefix remaining Mircosoft icons

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4857]
This isn't (yet) an exhaustive list but some MS icons that have still to be prefixed with `microsoft-` include:

- [x] `bing`
- [x] `onedrive`
- [x] `visual-studio`
- [x] `visual-studio-code`
...

**Comment by PeterShaggyNoble** [comment]
The other MS icons we have are probably better off without the prefix but we should at least alias them, if they're not already.

- [ ] `dot-net`
- [ ] `github`
- [ ] `minecraft`
- [ ] `mixer`
- [ ] `skype`
- [ ] `skype-business` (rename as `skype-for-business`)
- [ ] `xamarin`
- [ ] `xamarin-outline`
- [ ] `xaml` (maybe prefix with `language-` instead
- [ ] `xbox`

**Comment by Templarian** [comment]
Agreed all of these should not have it. Also yes, xaml should be a `language-*`, so lets rename that.

Aliases would be helpful (just add `microsoft-name` for the aliases. Including the xbox controllers?

**Comment by Templarian** [comment]
Even `dot-net` shouldn't as it's more of a framework now-a-days that is becoming less tied to them.

**Comment by PeterShaggyNoble** [comment]
Aliases add to all and `xaml` renamed as `language-xaml`. Do we want to rename `skype-business`?

I'll leave the Xbox controllers for another day.

**Comment by Templarian** [comment]
Keep `skype`, I have a feeling they'll be dead in a couple years or absorbed into `teams` or something else.

**Comment by PeterShaggyNoble** [comment]
@Templarian, the question was whether or not to _rename_ `skype-business` as `skype-for-business`.

**Comment by Templarian** [comment]
Oh... nah. That seems weird.

**Comment by PeterShaggyNoble** [comment]
In that case, we can close this out - the Xbox icons are covered in #4886.
