### ISSUE TITLE
Chrome does not display some icons

### ISSUE THREAD

**Issue by qLutCh55** [Templarian/MaterialDesign#4858]
## Expected Behavior
All icons should be displayed.

## Current Behavior
Although most icons do display. Some icons (it does seem to be newer icons) do not display on Chrome.

## Context (Environment)
OS: Elementary Os 5.1 (Built on Ubuntu 18.04)
Chrome: Version 80.0.3987.87 (Official Build) (64-bit)
Firefox: 72.0.2 (64-bit)
Application: Laravel + (Vue or Blade [html] ) 

## Description
So I have been experiecing this issue for a while now. And I am not sure if it is a problem with Chrome, or Chrome on Linux, or Material Design Icons.

But for some reason, when including material design in my Vue Spa application or any application for that matter, some icons do not render.

I have tried including scss of node_modules. I have tried referencing the CDN directly, but the issue still persists.

## Example:
Chrome:
![Screenshot from 2020-02-07 10-51-16](https://user-images.githubusercontent.com/26224124/74014937-577eb600-4998-11ea-89f1-0eeef956ea83.png)

Firefox:
![Screenshot from 2020-02-07 10-51-01](https://user-images.githubusercontent.com/26224124/74014911-4f267b00-4998-11ea-89aa-9ca0702bdc75.png)

I hope this information is enough to replicate or debug, but please let me know if there is any other information you would need to assist.

**Comment by JamesCoyle** [comment]
Are you using @mdi/font or @mdi/js?

**Comment by qLutCh55** [comment]
@mdi/font

**Comment by JamesCoyle** [comment]
Do you have the font installed locally on your machine? Have you tried clearing the cache? 

I'd recommend you switch to @mdi/js if possible. It is really easy to use and you will drastically reduce the size of your site as only the icons you actually use will be imported.

**Comment by qLutCh55** [comment]
We thought it might be a caching issue, but Laravel mix (webpack) does seem to version the fonts saved locally to prevent this issue.

If I use the @mdi/js -> would I need to make any code changes?

Currently with Vuetify, there is a component 'v-icon', which then transforms into <i class="mdi mdi-*"></i>.

Would <i> then still work with @mdi/js?

**Comment by JamesCoyle** [comment]
The implementation is slightly different. Here is some documentation on how to get it working: https://vuetifyjs.com/en/customization/icons#install-material-design-icons-js-svg

It's actually pretty simple:

1. Install @mdi/js: `npm install @mdi/js`
2. Change the icon font setting on the vuetify configuration object to be `mdiSvg`.
```
export default new Vuetify({
  icons: {
    iconfont: 'mdiSvg',
  },
})
```
3. Import the icon you want to use into the file where you want to use it. 
```
import { mdiStar } from '@mdi/js'
```
4. Add that icon to your data props so it can be used within the Vue template. 
```
data() { 
    return { 
        mdiStar,
    }
}
```
5. Pass that variable into the icon component. 
```
<v-icon>{{ mdiStar }}</v-icon>
```

**Comment by qLutCh55** [comment]
Oh wow,

I actually didn't even know this existed on vuetify.

One last question though, I can't seem to find anything about importing all the icons... and injecting them globally?

Any suggestions?

Thanks for the tip and the advice so far.

Really appreciate the feedback.

**Comment by qLutCh55** [comment]
@JamesCoyle Thank you very much for all your help.

I managed to read all the Vuetify Documentation and trying to implement it.

Ill close the issue, as soon as I can verify all icons are working.

Thanks

**Comment by FresBlueMan** [comment]
Hey buddy
I have the same issue like this.
icons are showing on firefox but not on chrome.
Chrome:
![image](https://user-images.githubusercontent.com/56789260/220297407-2979c3c6-a7b5-4519-8c03-cad84e647050.png)
FireFox:
![image](https://user-images.githubusercontent.com/56789260/220297601-f7c0e07f-22ff-4e83-b61c-f81806b31c96.png)

Please advise. thanks
