### ISSUE TITLE
Update Google Maps

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4859]
[Google have rebranded Maps](https://www.blog.google/products/maps/maps-15th-birthday/) but we may want to hold off a while before updating it to see if they provide a monochrome treatment of it themselves that doesn't just look like a generic map marker.

[![google-maps](https://user-images.githubusercontent.com/15157491/74020935-7ed28480-4992-11ea-807e-dd4279c25ed8.png)](https://github.com/Templarian/MaterialDesign/files/4170139/google-maps.zip)

**Comment by Templarian** [comment]
Not sure if they will provide anything better. We should definitely replace it for 5.0 though, so adding the milestone.

**Comment by PeterShaggyNoble** [comment]
May as well hold off until close to release, though, in _case_ they come out with something official or add a version to one of their font files.

**Comment by goyney** [comment]
@PeterShaggyNoble That download is the wrong icon.

**Comment by PeterShaggyNoble** [comment]
Oop! Don't know how I managed that! In case I don't get to it later, he original can be found at https://developers.google.com/maps/images/maps-icon.svg

For reference, here's the treatment one of the SI contributors gave it:

![Google Maps](https://user-images.githubusercontent.com/15157491/76209690-61dfda00-61fa-11ea-9664-44016437466e.png)

**Comment by goyney** [comment]
Updated.
