### ISSUE TITLE
file cabinet icon

### ISSUE THREAD

**Issue by jedld** [Templarian/MaterialDesign#486]
A file cabinet icon that suggest viewing a collection of documents or list of documents.

**Comment by Templarian** [comment]
Could the https://materialdesignicons.com/icon/archive icon work for that?

**Comment by CoDEmanX** [comment]
Or tray multiple, which I found in gmail app?
https://github.com/Templarian/MaterialDesign/issues/420#issuecomment-126732936

**Comment by CoDEmanX** [comment]
Or file-multiple:
https://materialdesignicons.com/icon/file-multiple

I could also create a multiple version of document, which is line above but with two counter strokes to symbolize text on the sheets.

**Comment by jedld** [comment]
yeah, the tray multiple best describes what I need. Thanks!

**Comment by PeterShaggyNoble** [comment]
`inbox-multiple` has been added so closing this out.
