### ISSUE TITLE
email-off

### ISSUE THREAD

**Issue by wkeizer** [Templarian/MaterialDesign#4860]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have an application where you can enable email notifications of certain events. A user can configure whether she wants certain email notifications on or off. I want to show this in the UI by having a email icon or an email-off icon.

Currently the OFF version of mail is missing in the libray.

## Examples

See "mdi-email". I'm looking for a strike through version like a lot of other icons have. See MDI library and search on OFF.

**Comment by goyney** [comment]
[![email-off](https://materialdesignicons.com/icon/email-off)](https://materialdesignicons.com/icon/email-off)
