### ISSUE TITLE
close-thick

### ISSUE THREAD

**Issue by euller88** [Templarian/MaterialDesign#4862]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Since there is a check-bold icon, then a close-bold icon in order to emphasize the negation of whatever check-bold is affirming or confirming 

## Examples

I think that filling out the blank space inside of close-outline would have the visual impact needed to match check-bold.

**Comment by Templarian** [comment]
Fixed title, `-thick` is our use for increasing the weight. `-bold` is for making an icon heavy.

**Comment by Templarian** [comment]
Added.
