### ISSUE TITLE
Nightlight / Light night/moon mode

### ISSUE THREAD

**Issue by MitschiBoy** [Templarian/MaterialDesign#4863]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have a lot off lights that have a night mode. I would be nice to have an icon for home automation software.

## Examples

![nightlight](https://user-images.githubusercontent.com/47030576/74047974-8feeb600-49d1-11ea-8fc4-8adfb0a3e23b.jpg)

**Comment by Templarian** [comment]
This might be possible by incorporating the `theme-light-dark`, although with the bulb shape it might have to be altered, so the cut out looks correct.

**Comment by Templarian** [comment]
Wouldn't worry about moving the bulb to the left if a larger moon looks nicer.

**Comment by goyney** [comment]
[![lightbulb-night](https://materialdesignicons.com/icon/lightbulb-night)](https://materialdesignicons.com/icon/lightbulb-night)[![lightbulb-night-outline](https://materialdesignicons.com/icon/lightbulb-night-outline)](https://materialdesignicons.com/icon/lightbulb-night-outline)
