### ISSUE TITLE
I need a empty icon, I use it as place holder for  align with other icons in a grid of icon

### ISSUE THREAD

**Issue by hoogw** [Templarian/MaterialDesign#4864]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I need a empty icon, I use it as place holder for  align with other icons in a grid of icon

## Examples

  I have icon grid, x means a empty icon, 

      D x C B
      x C D H
      U T x C

**Comment by Templarian** [comment]
The webfont CSS class `mdi-blank` and if you're using SVG use the `solid` icon as transparent.

We cannot create a blank "space" in the font as our current build system does not support this and is not on the roadmap as we deprecate. I do not believe the `webfont` NPM package supports this.

**Comment by Templarian** [comment]
@hoogw Can I get more context on how you are using the icons? Is this for the web or something else?

**Comment by goyney** [comment]
If you're using `@mdi/react`, just don't provide path data.

```
<Icon path='' size={1} />
```

**Comment by Templarian** [comment]
@hoogw I'll leave this for a few more days, still kind of curious how this is being used, so it can be solved correctly.
