### ISSUE TITLE
library-video-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4865]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Outlined version of "library-video" (https://dev.materialdesignicons.com/icon/library-video)

## Examples
![mdi-library-video-outline](https://user-images.githubusercontent.com/6717356/74154557-ebb07d80-4c23-11ea-8904-c51b6a16109b.png)

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/74187404-bf5d2700-4c4c-11ea-9547-0c9d8a5ebe46.png) ![grafik](https://user-images.githubusercontent.com/1309249/74187420-c8e68f00-4c4c-11ea-82f4-73e1fb429077.png)

[box-play-multiple.zip](https://github.com/Templarian/MaterialDesign/files/4182899/box-play-multiple.zip)

**Comment by Templarian** [comment]
The name is `play-box-multiple` / `play-box-multiple-outline`.

Box is a shape modifier, so always after the noun.

**Comment by Templarian** [comment]
Rename all the `library-*` icons to the correct names: `library-video` -> `play-box-multiple`.

Not sure why we did that. 🙃

**Comment by Templarian** [comment]
- [ ] `library-books`
- [ ] `library-movie`
- [ ] `library-music`
- [ ] `library-music-oultine`
- [ ] `library-video` (the one in this issue)

**Comment by JamesCoyle** [comment]
Can we make that play icon more equilateral? It doesn't look right to me.

**Comment by CoDEmanX** [comment]
Hm, I guess we should do a survey of the existing icons to find out what aspect ratios we use, decide on one that looks good for the play triangle and unify it.

**Comment by JamesCoyle** [comment]
They should all be scaled down versions of the play icon:
[![](https://materialdesignicons.com/icon/play)](https://materialdesignicons.com/icon/play)

**Comment by CoDEmanX** [comment]
Okay, that's 14 high, 11 wide. True geometric width for an equilateral triangle would be 14 ÷ √ (3 ÷ 2) = ~11.431 👍

**Comment by JamesCoyle** [comment]
For the smaller sizes these might work?
6 -> 4.898979485566357
10 ->  8.16496580927726

**Comment by Templarian** [comment]
Put play/pause/stop next to each other to get an idea so they visually look correct. Lets not entirely rely on math.

**Comment by goyney** [comment]
Renamed and the outlined version from Google added.
