### ISSUE TITLE
Escalator & stairs in box (MoMA)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4866]
Re-creations which are on-grid. The original icons were apparently not pixel perfect or for a different canvas/box size. I used our stairs and escalator icons as base and tweaked them to fit within the standard 18x18 box. Not sure how to attribute the icon in such a situation.

![grafik](https://user-images.githubusercontent.com/1309249/74187566-1c58dd00-4c4d-11ea-816f-6ac925a787ac.png) ![grafik](https://user-images.githubusercontent.com/1309249/74187586-28dd3580-4c4d-11ea-90f6-39af7ac4c648.png)

[escalator-stairs-box.zip](https://github.com/Templarian/MaterialDesign/files/4182906/escalator-stairs-box.zip)

**Comment by Templarian** [comment]
Added.
