### ISSUE TITLE
Bag rucksack / backpack variant (MoMA)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4867]
More minimalistic versions of the existing bag-personal icons:

![grafik](https://user-images.githubusercontent.com/1309249/74188478-c8e78e80-4c4e-11ea-91cc-d868249b1424.png) ![grafik](https://user-images.githubusercontent.com/1309249/74188505-d56be700-4c4e-11ea-8e9e-a10586eed482.png)

Outline variant is by me, filled is MoMA with tweaks.

[bag-rucksack.zip](https://github.com/Templarian/MaterialDesign/files/4182953/bag-rucksack.zip)

**Comment by goyney** [comment]
Do we really need a second, nearly identical version of this?

**Comment by goyney** [comment]
Gonna close this since we already have a backpack.
