### ISSUE TITLE
Wash hands / hand-water (MoMA)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4868]
Re-created based on the existing hand icon (rotated), which isn't exactly pixel-perfect either. The thumb is shortened, because that's how it is in the MoMA icon. Might make the hand look söightly more held upwards.

![grafik](https://user-images.githubusercontent.com/1309249/74188745-5fb44b00-4c4f-11ea-965c-bc1d12038ad1.png)

[hand-water.zip](https://github.com/Templarian/MaterialDesign/files/4182981/hand-water.zip)

**Comment by Templarian** [comment]
Added.
