### ISSUE TITLE
Cloackroom icons: hanger & umbrella (MoMA)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4869]
We already have icons for both, so not sure what to do. I like the hanger better than ours, but the umbrella seems more complicated than necessary and wouldn't know how to do an open variant in the same style.

![grafik](https://user-images.githubusercontent.com/1309249/74189046-03056000-4c50-11ea-9a81-f967283fef19.png) ![grafik](https://user-images.githubusercontent.com/1309249/74189354-8030d500-4c50-11ea-9176-47513ab8ccb5.png)

Re-creation of MoMA icons: [cloakroom.zip](https://github.com/Templarian/MaterialDesign/files/4183006/cloakroom.zip)

We miss `umbrella-closed-outline`, so I created this one but I also experimented with different terminals at the top:

![grafik](https://user-images.githubusercontent.com/1309249/74190530-cf780500-4c52-11ea-8ed3-7802f19704ff.png)

![grafik](https://user-images.githubusercontent.com/1309249/74190620-f1718780-4c52-11ea-9a42-7de22a551634.png) ![grafik](https://user-images.githubusercontent.com/1309249/74190644-f9c9c280-4c52-11ea-80f6-9f3243680e8e.png)

![grafik](https://user-images.githubusercontent.com/1309249/74190568-dc94f400-4c52-11ea-8115-0bb4e12fbe35.png) ![grafik](https://user-images.githubusercontent.com/1309249/74190597-e6b6f280-4c52-11ea-94ac-5b5706780293.png)

I really like the rounded end. Makes the outline version look less like a tree.

[umbrella-update.zip](https://github.com/Templarian/MaterialDesign/files/4183055/umbrella-update.zip)

**Comment by MrGrigri** [comment]
I prefer the third versions of `umbrella-closed`.

**Comment by goyney** [comment]
Hanger updated. Added the new closed umbrella variant. Updated our closed umbrella with variation 3 and added the outline as well.
