### ISSUE TITLE
circle-half, circle-half-full

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4870]
Nothing special, but I think `circle-half-full` is useful as a generic icon:
- contrast (we have one, but it's less simplistic)
- dark / light mode switch (again more minimal than what we have so far)
- progress indicator (full circle, half circle, circle outline; same as above)
- rating (like star-half and star-half-full)
- parity with https://microsoft.github.io/vscode-codicons/dist/codicon.html (we same to have almost all their icons)

![grafik](https://user-images.githubusercontent.com/1309249/74190833-46ad9900-4c53-11ea-84ea-9e07b8d49811.png) ![grafik](https://user-images.githubusercontent.com/1309249/74190806-3b5a6d80-4c53-11ea-8980-5877e72b45e5.png)

[circle-half.zip](https://github.com/Templarian/MaterialDesign/files/4183087/circle-half.zip)

For other basic shapes it doesn't make much sense however, like box-half...

**Comment by Templarian** [comment]
Added. 😃
