### ISSUE TITLE
baby-stroller (MoMA)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4871]
In contrast to a baby-carriage, the baby somewhat sits in such a buggy instead of lying flat.

![grafik](https://user-images.githubusercontent.com/1309249/74191746-75783f00-4c54-11ea-8255-038f80f287ef.png)

[baby-buggy.zip](https://github.com/Templarian/MaterialDesign/files/4183113/baby-buggy.zip)

**Comment by goyney** [comment]
[![baby-buggy](https://materialdesignicons.com/icon/baby-buggy)](https://materialdesignicons.com/icon/baby-buggy)
