### ISSUE TITLE
Single sofa / couch (MoMA)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4872]
I tried to re-create it, but it's unclear what the original size is supposed to be. Theirs has more like a 1.5dp gap than 1dp.

![grafik](https://user-images.githubusercontent.com/1309249/74192061-149d3680-4c55-11ea-9bef-e061a0956fec.png) ![grafik](https://user-images.githubusercontent.com/1309249/74192040-0a7b3800-4c55-11ea-9ade-6ef559f9ef62.png)

[sofa-single.zip](https://github.com/Templarian/MaterialDesign/files/4183144/sofa-single.zip)

Note that we already have a double `sofa` icon, and there is a Google icon `weekend` which we don't have:
https://material.io/resources/icons/?search=weekend&icon=fastfood&style=baseline

**Comment by MrGrigri** [comment]
I believe that the first one works

**Comment by goyney** [comment]
I'd rather see us pick a style and stick with it. This style differs quite a bit from our current `sofa`.

[![sofa](https://materialdesignicons.com/icon/sofa)](https://materialdesignicons.com/icon/sofa)

We could create a single version in that style:

![image](https://user-images.githubusercontent.com/1015040/76135750-06de9500-5ff8-11ea-8d33-19816e28c46b.png)

---

We could use Google's `weekend` instead and make the other variation:

![image](https://user-images.githubusercontent.com/1015040/76135808-8d937200-5ff8-11ea-9d33-22aeb9e9a8cf.png)
![image](https://user-images.githubusercontent.com/1015040/76135814-9b48f780-5ff8-11ea-829b-b6328782e85d.png)

---

Or do the same thing with this MoMA variation.

Thoughts?

**Comment by JamesCoyle** [comment]
I like the Google ones more but they could use some little legs IMO. The single one should probably be made narrower too, though I feel we could keep that version as a generic `sofa` and add `sofa-single` as a narrower version and `sofa-double` at that width but with the two cushions.

**Comment by goyney** [comment]
Modified Google's `weekend` to meet our needs and give us the loveseat variant.

[![sofa](https://materialdesignicons.com/icon/sofa)](https://materialdesignicons.com/icon/sofa)[![sofa-outline](https://materialdesignicons.com/icon/sofa-outline)](https://materialdesignicons.com/icon/sofa-outline)
[![sofa-single](https://materialdesignicons.com/icon/sofa-single)](https://materialdesignicons.com/icon/sofa-single)[![sofa-single-outline](https://materialdesignicons.com/icon/sofa-single-outline)](https://materialdesignicons.com/icon/sofa-single-outline)
