### ISSUE TITLE
Recycling variant (MoMA)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4874]
Slightly tweaked to better fit to grid.

![grafik](https://user-images.githubusercontent.com/1309249/74192391-be7cc300-4c55-11ea-8c9e-f4a36d8069de.png)

[recycling-variant.zip](https://github.com/Templarian/MaterialDesign/files/4183153/recycling-variant.zip)

**Comment by Templarian** [comment]
If we replace the current recycle with this and make a `recycle-thick`.

**Comment by Templarian** [comment]
Fixed. Ended up going with `recycle-variant`.
