### ISSUE TITLE
Fire extinguisher variant (MoMA)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4875]
We already have such an icon and I'm not a fan of this one (only for completeness):

![grafik](https://user-images.githubusercontent.com/1309249/74192506-f5eb6f80-4c55-11ea-8573-8c32d41dea4a.png)

[fire-extinguisher.zip](https://github.com/Templarian/MaterialDesign/files/4183161/fire-extinguisher.zip)

**Comment by JamesCoyle** [comment]
I much prefer ours.

**Comment by Templarian** [comment]
It's so cute and "chunky", but yes, we'll go with ours for this one.
