### ISSUE TITLE
Update food icon with Google's fastfood / add off-variant?

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4876]
Google's `fastfood` icon and our `food` icon are different.
https://material.io/resources/icons/?search=fastfood&icon=fastfood&style=baseline

The MoMA `fastfood-off` icon is really just Google's base icon with with strike through:

![grafik](https://user-images.githubusercontent.com/1309249/74192605-2206f080-4c56-11ea-8840-f93bffb2321c.png)

We already have an off variant of our base icon, so the question is whether we want to update both or stick with what we have.

**Comment by Templarian** [comment]
I don't know if this warrants addition/update. The way the two items are stacked adds perspective. I like our `food-variant` as the vegetarian/generic also.

**Comment by JamesCoyle** [comment]
Yeah I think our fast food icon is better.

**Comment by CoDEmanX** [comment]
Yeah, I think we can stick with our icons. Should we add a `food-variant-off` icon though?

![grafik](https://user-images.githubusercontent.com/1309249/74356425-98befd80-4dbe-11ea-9362-65af942d7ecc.png)

[food-variant-off.zip](https://github.com/Templarian/MaterialDesign/files/4193512/food-variant-off.zip)

Another variant for vegans seems unnecessary, as `food-variant` might depict soy milk and vegan cornflakes.

**Comment by goyney** [comment]
[![food-variant-off](https://materialdesignicons.com/icon/food-variant-off)](https://materialdesignicons.com/icon/food-variant-off)
