### ISSUE TITLE
Vertical Blinds/Shades

### ISSUE THREAD

**Issue by deanlongstaff** [Templarian/MaterialDesign#4878]
I have: Vertical Blinds/Shades that are smart controlled

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
Using to show the status of my vertical blinds - Open or Closed

## Examples

Include any example images so we know what the icon should look like.
![IMG_7326](https://user-images.githubusercontent.com/56657761/74323301-38f43280-4d7d-11ea-924f-c9039942a286.jpg)

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/77181468-a6f1ef00-6acb-11ea-858c-1ced5c5c7182.png)

**Comment by benblb** [comment]
I'd love to see one for open and one for closed! My open/closed buttons in HA are currently a vertical roller shade which isn't as descriptive as it could be.

**Comment by goyney** [comment]
[![blinds-vertical](https://materialdesignicons.com/icon/blinds-vertical)](https://materialdesignicons.com/icon/blinds-vertical)[![blinds-vertical-closed](https://materialdesignicons.com/icon/blinds-vertical-closed)](https://materialdesignicons.com/icon/blinds-vertical-closed)
