### ISSUE TITLE
Inconsistent key icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4880]
Google's `key` has a short end, but it's already 1dp in the margin so extending it a little isn't really an option and because of the overall size it is quite recognizable:

![grafik](https://user-images.githubusercontent.com/1309249/74353984-fb15ff00-4dba-11ea-884e-5517f3a55893.png)

However, we have additional icons with a key as main shape as well as icons with a key modifier.

The first group has a pretty long end:

![grafik](https://user-images.githubusercontent.com/1309249/74354065-1b45be00-4dbb-11ea-86e5-376b78f0b697.png) ...

![grafik](https://user-images.githubusercontent.com/1309249/74354371-8c857100-4dbb-11ea-89a3-0b3caf35b9f5.png)

The second group has a very short end like in Google's icon:

![grafik](https://user-images.githubusercontent.com/1309249/74354093-24cf2600-4dbb-11ea-901a-d4d18fbd56dc.png) ![grafik](https://user-images.githubusercontent.com/1309249/74354119-2e588e00-4dbb-11ea-8cda-0969d1725b8d.png) ...

![grafik](https://user-images.githubusercontent.com/1309249/74354543-d0787600-4dbb-11ea-9cd7-12e3b81e9601.png)

I think it would make sense to unify this where possible to 3/3 and 2/2 respectively.

![grafik](https://user-images.githubusercontent.com/1309249/74354745-16cdd500-4dbc-11ea-92ee-c56219804f9e.png) ![grafik](https://user-images.githubusercontent.com/1309249/74354878-4977cd80-4dbc-11ea-8c4a-6395da8f1cb4.png)

There is a small problem with the first group: shortening the end in `key-change` doesn't really work, but the key bit could be moved to the left I guess:

![grafik](https://user-images.githubusercontent.com/1309249/74355029-89d74b80-4dbc-11ea-8f53-954481258a10.png)

There is no space left in `account-key`, so that should remain as-is:
![grafik](https://user-images.githubusercontent.com/1309249/74355096-aa070a80-4dbc-11ea-82e8-d2aaaf7a3477.png)

The file and folder icons should probably stay as-is too.

About `car-key`: the key modifier is currently not on grid, which should be corrected. With the slightly longer end it can be perfectly centered again (6dp on both sides) and I find it easier to recognize:

![grafik](https://user-images.githubusercontent.com/1309249/74355275-efc3d300-4dbc-11ea-832d-46b3afaab1d4.png)

**Comment by goyney** [comment]
All updated.
