### ISSUE TITLE
account-decagram

### ISSUE THREAD

**Issue by julienreszka** [Templarian/MaterialDesign#4883]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
I use the `decagram` symbol to signify "brand"
I would like to have `account-decagram` to signify "brand representative"
I wish I could have `account-multiple-decagram` to signify "brand representatives"

## Examples

decagram :
https://petershaggynoble.github.io/MDI-Sandbox/?icon=decagram
account-plus
https://petershaggynoble.github.io/MDI-Sandbox/?icon=account-plus
account-multiple-plus :
https://petershaggynoble.github.io/MDI-Sandbox/?icon=account-multiple-plus

**Comment by MrGrigri** [comment]
I'm not sure if the inside of the decagram should follow the outside on the non-outlined version.

![image](https://user-images.githubusercontent.com/4528551/74374559-e413e480-4d9b-11ea-9573-3f85af811fa0.png) ![image](https://user-images.githubusercontent.com/4528551/74374584-f1c96a00-4d9b-11ea-8893-80c75ad0fc55.png)

### Files

[account-decagram.zip](https://github.com/Templarian/MaterialDesign/files/4194895/account-decagram.zip)

**Comment by MrGrigri** [comment]
I'm not sure if multiple would work with the 20x20 pixel area.

**Comment by julienreszka** [comment]
Maybe something like this?
![account-multiple-decagram-test](https://user-images.githubusercontent.com/8984570/74380950-d3d72600-4dea-11ea-93b7-e35b0b3ca222.png)

**Comment by MrGrigri** [comment]
We haven't added `decagram` as a modifier and not sure if we want to.

**Comment by goyney** [comment]
This is not something we are going to be likely to add. However, if you use `@mdi/react`, you can use the `<Stack/>` component to stack our account and decagram icons on each other.

**Comment by Templarian** [comment]
Agreeing with the above comments. This is not really a base shape that works.

At the smaller size as an overlay almost all detail is lost at 1:1 making it almost raster as a circle.
