### ISSUE TITLE
folder-multiple-star 

### ISSUE THREAD

**Issue by julienreszka** [Templarian/MaterialDesign#4884]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I use `folder-star` to signify "favorite folder"
I have multiple folders that have been starred.
I would like to have an icon `folder-multiple-star` to signify "favorite folders"

## Examples

https://petershaggynoble.github.io/MDI-Sandbox/?icon=folder-star-outline
https://petershaggynoble.github.io/MDI-Sandbox/?icon=folder-multiple-outline

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/76044189-8fd9cb80-5f27-11ea-9846-4884c5b5e59c.png)![image](https://user-images.githubusercontent.com/1015040/76044196-96684300-5f27-11ea-9e91-3cb6331265a9.png)

[folder-star-multiple.zip](https://github.com/Templarian/MaterialDesign/files/4296149/folder-star-multiple.zip)

**Comment by goyney** [comment]
[![folder-star-multiple](https://materialdesignicons.com/icon/folder-star-multiple)](https://materialdesignicons.com/icon/folder-star-multiple)[![folder-star-multiple-outline](https://materialdesignicons.com/icon/folder-star-multiple-outline)](https://materialdesignicons.com/icon/folder-star-multiple-outline)
