### ISSUE TITLE
file-tree-outline

### ISSUE THREAD

**Issue by MarioKalac** [Templarian/MaterialDesign#4885]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Like the existing file-tree icon, but in outline style.

## Examples

https://dev.materialdesignicons.com/icon/file-tree

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/76043848-acc1cf00-5f26-11ea-9a44-82c04cbde032.png)

[file-tree-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/4296126/file-tree-outline.svg.zip)

**Comment by goyney** [comment]
[![file-tree-outline](https://materialdesignicons.com/icon/file-tree-outline)](https://materialdesignicons.com/icon/file-tree-outline)
