### ISSUE TITLE
Brand Icon Prefixes

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4886]
Spinning these out from an internal discussion for further feedback. Should we prefix the following icons?

- [ ] ~`lumx` with `lumapps-`~
- [ ] ~`material-design` with `google-`~
- [x] All games consoles - currently `nintendo-switch` is prefixed (although just as much for disambiguation as anything else), we had decided against prefixing `xbox` but have been discussing prefixing `wii` and `wiiu`. We should be consistent here, either all or nothing.
  - [x] `playstation` with `sony-`
  - [x] `wii` with `nintendo-`
  - [x] `wiiu` with `nintendo-`
  - [x] `xbox` with `microsoft-`
  - [x] `xbox-controller(-*)` with `microsoft-`

**Comment by JamesCoyle** [comment]
I'd say yes for consoles, no for MD, and I've never heard of the first one so no clue.

**Comment by PeterShaggyNoble** [comment]
@JamesCoyle, does that include the Xbox controller icons?

**Comment by Templarian** [comment]
I guess if we're doing `xbox` we should do the controllers also.
