### ISSUE TITLE
credit-card-box-check (fill and outline)

### ISSUE THREAD

**Issue by philtomblin** [Templarian/MaterialDesign#4887]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would use this to indicate that an item has been paid.

## Examples

I would envisage this to look like mdi-credit-card-remove[-outline], except with a tick instead of a cross (as mdi-file-document-box-check[-outline] is to mdi-file-document-box-remove[-outline]).

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/76043563-e9d99180-5f25-11ea-9d70-b9a4c64b582f.png)![Uploading image.png…]()

[credit-card-check.zip](https://github.com/Templarian/MaterialDesign/files/4296116/credit-card-check.zip)

**Comment by goyney** [comment]
[![credit-card-check](https://materialdesignicons.com/icon/credit-card-check)](https://materialdesignicons.com/icon/credit-card-check)[![credit-card-check-outline](https://materialdesignicons.com/icon/credit-card-check-outline)](https://materialdesignicons.com/icon/credit-card-check-outline)
