### ISSUE TITLE
mdi-shield-car not working on Firefox

### ISSUE THREAD

**Issue by glics** [Templarian/MaterialDesign#4888]
Tested on mdi 4.9.95 on Firefox 70~ 73, under Windows 10 and Manjaro Linux.

Sample from https://cdn.materialdesignicons.com/4.9.95/ below, 
with Chrome:
![chrome](https://user-images.githubusercontent.com/5410803/74460022-8dd29e80-4e8c-11ea-931c-c3f2cb637687.png)

And Firefox:
![firefox](https://user-images.githubusercontent.com/5410803/74460048-988d3380-4e8c-11ea-9110-c0ceb97d9c6f.png)

**Comment by Templarian** [comment]
Would like to confirm, but I think that codepoint might not be in the private use area. Either way it will be addressed in 5.0 part of moving to `F0001` private use area for all codepoints.

https://github.com/Templarian/MaterialDesign/issues/4806

**Comment by goyney** [comment]
This is a bug with Firefox and not us. Do a search for Firefox FFA0 and you'll find a couple posts complaining about the same issue.

You can check out https://www.fileformat.info/info/unicode/char/ffa0/browsertest.htm to see the issue. If you highlight the page in Chrome, you'll see the Decimal Escape and Hex Escape highlight a blank box, but in Firefox, there will be nothing.

All that being said, we are considering moving all the glyphs into the private unicode space in 5.0, so this will be addressed there.
