### ISSUE TITLE
Duplicate icon

### ISSUE THREAD

**Issue by ashughes** [Templarian/MaterialDesign#489]
An icon to duplicate selected content. Basically the actions of copy and paste, but in a single icon.

**Comment by ashughes** [comment]
Here's an idea:
![duplicate_icon](https://cloud.githubusercontent.com/assets/295214/8630656/64155812-271d-11e5-8305-bd4e703620ce.png)

Another idea is to use a plus icon in the center or bottom right of the copy icon, however I don't like those ideas as much.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/content-duplicate
