### ISSUE TITLE
Artical/Blog Icon [Desktop Google Search]

### ISSUE THREAD

**Issue by nitin2953** [Templarian/MaterialDesign#4893]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In front of "BLOG" link in my website

## Examples

As seen on desktop google search : in front of NEWS link

**Comment by PeterShaggyNoble** [comment]
Do you mean the one below, @nitin2953? We have a number of `newspaper` icons already plus `post` & `post-outline`, do any of them suit your requirements?

![news](https://user-images.githubusercontent.com/15157491/74648197-1b580c00-5175-11ea-8d58-fee0f6dd228f.png)

**Comment by nitin2953** [comment]
no, the google one looks clean and suits my site design language

**Comment by goyney** [comment]
We already have 2 variants of `newspaper`. I do not believe we need a third. I, however, might be open to the idea of replacing one of our two with this variation, particularly our variant.

**Comment by JamesCoyle** [comment]
Could we add this as article-outline or something? I do like this version.

**Comment by goyney** [comment]
Our `newspaper-variant` icons have been updated to use this new style.
