### ISSUE TITLE
Whys is the site so slow ?

### ISSUE THREAD

**Issue by adrianTNT** [Templarian/MaterialDesign#4894]
When I go to materialdesignicons.com to look for an icon, I am always drawn back by the site speed, when you click to search for an icon, it takes even around 20 seconds to return results, and sometimes it simply returns all icons instead of the query. 
It also shows the "not secure" warning, I see the https version is live, it probably needs a redirect.

**Comment by Templarian** [comment]
New Site WIP: https://github.com/Templarian/MaterialDesign-Site

The site was built with a couple hundred icons in mind. It was never meant to support 5000. It's nearly 7 years old.

After the 5.0 release more work is going in to the new site. For now you can use the Chrome / Firefox extension to search icons.

`Material Design Icons Picker`

**Comment by Templarian** [comment]
The new site uses entirely rewritten backed. Which is nearly complete. The front end should go quicker, but the advanced export that many use might be too complicated to move over in the initial release.

**Comment by adrianTNT** [comment]
Thanks. I was not sure if it is the site or something at my end.

**Comment by Christophrenic** [comment]
I see a lot of passionate support for this site, which is great. However, two years later and the website is as slow or slower than ever before.

**Comment by Templarian** [comment]
@Christophrenic Will be working on this more soon. Been a busy as of late. We do still have several more releases and some new icon sets that will be ramping up.

Definitely use the browser extensions for now.
