### ISSUE TITLE
car-settings

### ISSUE THREAD

**Issue by SeanPM5** [Templarian/MaterialDesign#4895]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There is an existing icon `mdi:car-info` added in https://github.com/Templarian/MaterialDesign/issues/4424 that shows a car with an info icon to the right. It is great, but I would like the exact same thing but swap out the info icon for a settings cog (`mdi:cog` or `mdi:cogs`).

In Home Assistant, I have a page for my car and a section with various toggles and automation settings. They are hidden/collapsed until I click on a button, I would like to use this icon for the button as it fits the use case better than `mdi:car-info`. Thanks in advance to anyone that can make this happen :) 

## Examples
Here is a quick mockup of the rough idea.

![car-settings](https://i.imgur.com/LFfnU5n.jpg)

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/74790772-ea80ef80-52b8-11ea-90ee-611bcd8ac655.png) ![grafik](https://user-images.githubusercontent.com/1309249/74790789-f53b8480-52b8-11ea-9a16-8053887f5411.png)

The standard presentation for settings is three small rectangles however:

![grafik](https://user-images.githubusercontent.com/1309249/74790820-0f756280-52b9-11ea-869b-dcea98c40f64.png)

[car-cog.zip](https://github.com/Templarian/MaterialDesign/files/4222528/car-cog.zip)

**Comment by SeanPM5** [comment]
That is perfect, thanks!

**Comment by goyney** [comment]
[![car-cog](https://materialdesignicons.com/icon/car-cog)](https://materialdesignicons.com/icon/car-cog)[![car-settings](https://materialdesignicons.com/icon/car-settings)](https://materialdesignicons.com/icon/car-settings)
