### ISSUE TITLE
cog-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4896]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

As the cog represents a settings option, this is used in my frontend to reveal a more-info window. This more-info window needs an icon to represent closing it again. A cog-off would be perfect for doing so

## Examples

Include any example images so we know what the icon should look like.

I would simply suggest to add the diagonal -off line to cog, and maybe cog-outline while at it..

thanks for considering!

**Comment by CoDEmanX** [comment]
> icon to represent closing [a window] again

That's not what -off icons are for. You should use a plain icon such as `close`.

It would also look pretty horrible:

![grafik](https://user-images.githubusercontent.com/1309249/74789981-8d843a00-52b6-11ea-9992-13a1183ea485.png)

**Comment by Mariusthvdb** [comment]
Actually, I think this looks very good!
And it visually represents exactly what  I expect it to be.

So, would truly appreciate if you would add this really...

**Comment by goyney** [comment]
[![cog-off](https://materialdesignicons.com/icon/cog-off)](https://materialdesignicons.com/icon/cog-off)[![cog-off-outline](https://materialdesignicons.com/icon/cog-off-outline)](https://materialdesignicons.com/icon/cog-off-outline)
