### ISSUE TITLE
scan-helper

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#4897]
Just the bounding box from `face-recognition`.

While we're at it, should we rename `face-recognition` as `face-scan`, for consistency with our other `*-scan` icons?

-----

I have:
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
[![scan-helper](https://user-images.githubusercontent.com/15157491/74648462-a6d19d00-5175-11ea-900e-b3792cca68ab.png)](https://github.com/Templarian/MaterialDesign/files/4213371/scan-helper.zip)

## Zip Download
https://github.com/Templarian/MaterialDesign/files/4213371/scan-helper.zip

**Comment by goyney** [comment]
[![scan-helper](https://materialdesignicons.com/icon/scan-helper)](https://materialdesignicons.com/icon/scan-helper)
