### ISSUE TITLE
new-box-outline

### ISSUE THREAD

**Issue by nareshravlani** [Templarian/MaterialDesign#4898]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

We already have outline icons for most of icons, but its missing for the "new-box" icon. I request to add "new-box-outline" icon.

## Examples

![new-box-outline](https://user-images.githubusercontent.com/43164757/74657680-c6d58080-51b6-11ea-9565-c3c5fae4099e.PNG)

**Comment by runxel** [comment]
Made an outline version and also adjusted the width of the non-outline version, so they are the same width.

[![new-outline](https://user-images.githubusercontent.com/2277182/74682128-7ca7cb80-51c5-11ea-9002-693b9984173c.png)](https://github.com/Templarian/MaterialDesign/files/4215861/new-outline.zip)


[![new](https://user-images.githubusercontent.com/2277182/74682129-7d406200-51c5-11ea-938f-12aeb0c4bd2a.png)](https://github.com/Templarian/MaterialDesign/files/4215862/new.zip)

**Comment by goyney** [comment]
These break Material guidelines and break into the 2dp buffer area.

**Comment by Templarian** [comment]
Rejecting as it goes against our guidelines for internationalization. English only icons are not being added.

Maybe use a more specific noun to represent what is being created. Feel like it may break a lot of people if we try removing `new-box` at this point since it was one of the original icons.

**Comment by runxel** [comment]
> Rejecting as it goes against our guidelines for internationalization. English only icons are not being added.

Great, fully understandable.
But maybe write that down somewhere?

**Comment by PeterShaggyNoble** [comment]
Google don't include the box in their outline version of it 🙄

[![fiber_new](https://user-images.githubusercontent.com/15157491/74724612-65ec8d80-5234-11ea-81a4-f373331b7ba6.png)](https://material.io/resources/icons/?search=fiber_new&icon=fiber_new&style=outline)

**Comment by CoDEmanX** [comment]
The should've nudged it 0.5dp left or right on grid...
