### ISSUE TITLE
Digital clock

### ISSUE THREAD

**Issue by runxel** [Templarian/MaterialDesign#4899]
Rename the existing `digital-clock` to `digital-clock-outline`.
This icon here will be the new `digital-clock`.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![clock-digital](https://user-images.githubusercontent.com/2277182/74681017-9abffc80-51c2-11ea-88a6-daa914baf13f.png)

## Zip Download

[clock-digital.zip](https://github.com/Templarian/MaterialDesign/files/4215810/clock-digital.zip)

**Comment by goyney** [comment]
I'm not a fan of either this or our current digital clock. They both break Material guidelines.

**Comment by Templarian** [comment]
Yeah, feel like there may be a nicer way to design our current digital clock. Definitely not an ideal design.

**Comment by runxel** [comment]
What would make a good design in your eyes?

**Comment by PeterShaggyNoble** [comment]
See also #3951.

Welcome to MDI, @runxel :grin: To help you get started we follow Google's [Material Design guidelines for system icons](https://material.io/design/iconography/system-icons.html) here.

**Comment by runxel** [comment]
Hey there @PeterShaggyNoble 😎 
Yeah, thanks! Already had a close look at those ;)

>  content may extend into the padding between the live area and the trim area (the complete size of a graphic)

**Comment by CoDEmanX** [comment]
Only if it's unavoidable however. Otherwise you may end up with icons touching each other or icons being inconsistent in size. [Nova](https://www.streamlineicons.com/nova/) uses the full 24x24 canvas IIRC, but it kind of leads to a different style as well (comparable to 18dp Google Fit vs. ~20dp Material System Icons)

**Comment by goyney** [comment]
I think the core team is pretty much in agreement that we don't want to make this change. We are, however, open to other ideas. We're going to close this request now, but if you come up with another way to portray a digital clock that would work well in a filled/outlined variant, please open a new issue.
