### ISSUE TITLE
shield-bug-outline (antivirus)

### ISSUE THREAD

**Issue by MaksUr** [Templarian/MaterialDesign#4900]
![image](https://user-images.githubusercontent.com/26674247/74718085-5b8dbc00-5253-11ea-8bc0-d6a128c8f1c5.png)

[shield-bug-outline.zip](https://github.com/Templarian/MaterialDesign/files/4218136/shield-bug-outline.zip)

**Comment by CoDEmanX** [comment]
Better on grid:

![grafik](https://user-images.githubusercontent.com/1309249/74789704-cec81a00-52b5-11ea-8933-55c43f2c2b89.png)

[shield-bug-outline.zip](https://github.com/Templarian/MaterialDesign/files/4222463/shield-bug-outline.zip)

It doesn't work well in a solid variant however.

**Comment by gespispace** [comment]
@Templarian

**Comment by MrGrigri** [comment]
It might work if the bug is larger. Thoughts?

![image](https://user-images.githubusercontent.com/4528551/74851418-70705b00-52f8-11ea-8ab2-4a1d7996bba4.png)

[shield-bug.zip](https://github.com/Templarian/MaterialDesign/files/4225990/shield-bug.zip)

**Comment by CoDEmanX** [comment]
It changes the propertions quit a lot, but it would work I guess. Might want to stretch the legs in the outline variant to 2dp on grid then as well.

**Comment by goyney** [comment]
[![shield-bug](https://materialdesignicons.com/icon/shield-bug)](https://materialdesignicons.com/icon/shield-bug)[![shield-bug-outline](https://materialdesignicons.com/icon/shield-bug-outline)](https://materialdesignicons.com/icon/shield-bug-outline)

`shield-bug-outline` assigned to the global Contribution account for now until you reach 5 contributed icons.
