### ISSUE TITLE
Numeric Home Floor icons up to 9

### ISSUE THREAD

**Issue by zappasmart** [Templarian/MaterialDesign#4902]
## Usage
Numeric home floors icons are only up to the 3rd floor.
It could be useful to have all numbers available (0 to 9) that could be used to describe apartment numbers instead of actual floors.

## Examples
See home-floor-3 as an example

**Comment by CoDEmanX** [comment]
There can be more than 9 apartments per floor, therefore I'm against adding specific icons for 0-9. Just use a generic icon (door?) and the apartment number as text, or use one or multiple of the numeric icons (e.g. `numeric-9-box-outline`)

**Comment by Templarian** [comment]
Yeah, we should invest on getting that font created. Actually would be fairly easy with the font build package probably.

**Comment by goyney** [comment]
We are not going to deviate from our original decision to not include all the numbers. The use case is too niche. Thanks for your suggestion.
