### ISSUE TITLE
account-cog cutout

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4903]
In `file-cog` and `folder-cog`, the cutout has a diameter of 14dp and is -2dp outside of the canvas:

![grafik](https://user-images.githubusercontent.com/1309249/74792173-ebb41b80-52bc-11ea-8e3e-dedff17d6762.png) ![grafik](https://user-images.githubusercontent.com/1309249/74792187-f66eb080-52bc-11ea-8354-e8ce7a9299bf.png)

In the current `account-cog` icon however, the diamter is 13dp, it is fully within the canvas and not centered around the modifier:

![grafik](https://user-images.githubusercontent.com/1309249/74792239-24ec8b80-52bd-11ea-99ba-b13775fd9d52.png)

I guess it should be unified?

![grafik](https://user-images.githubusercontent.com/1309249/74792138-c58e7b80-52bc-11ea-9415-07d52831d972.png) ![grafik](https://user-images.githubusercontent.com/1309249/74792298-549b9380-52bd-11ea-9d45-606fc7c631d0.png)

Current icons for comparison:

![grafik](https://user-images.githubusercontent.com/1309249/74792552-16eb3a80-52be-11ea-916d-98fa1abab4d4.png) ![grafik](https://user-images.githubusercontent.com/1309249/74792570-24082980-52be-11ea-934d-d82570a6ec5e.png)

[account-cog-outline.zip](https://github.com/Templarian/MaterialDesign/files/4222609/account-cog-outline.zip)

**Comment by goyney** [comment]
The current icons look more optically correct. I’m not sure I like this change.

**Comment by CoDEmanX** [comment]
Cog further up:

![grafik](https://user-images.githubusercontent.com/1309249/74792761-a98bd980-52be-11ea-822c-447c70fdd3bd.png) ![grafik](https://user-images.githubusercontent.com/1309249/74792780-b8728c00-52be-11ea-88a0-4c32b1b6a60f.png)

In the same position as the current one, but with the cutout fixed:

![grafik](https://user-images.githubusercontent.com/1309249/74792880-f079cf00-52be-11ea-8cf0-5002418f3ced.png) ![grafik](https://user-images.githubusercontent.com/1309249/74792919-0dae9d80-52bf-11ea-9cab-8eff9e05624d.png)

[account-cog-outline3.zip](https://github.com/Templarian/MaterialDesign/files/4222658/account-cog-outline3.zip)

**Comment by goyney** [comment]
Those last two are my vote! 👍

**Comment by MrGrigri** [comment]
Idk, I'm all about keeping a standard. A cutout isn't part of the icon but an addition to it.

**Comment by CoDEmanX** [comment]
I agree with goyney that it looks visually more balanced with the cog further up, and I would honestly keep the location but fix the cutout to make it consistent. It focuses more on the "settings" aspect this way.

**Comment by goyney** [comment]
Updated.
