### ISSUE TITLE
monitor-eye (monitoring)

### ISSUE THREAD

**Issue by MaksUr** [Templarian/MaterialDesign#4904]
[monitor-eye.zip](https://github.com/Templarian/MaterialDesign/files/4224514/monitor-eye.zip)

![image](https://user-images.githubusercontent.com/26674247/74826548-98c67c80-532d-11ea-9a74-2db50baa48a5.png)

The svg file has `fill="black"` option and i don't know it's good or not for you.
I did it in figma. I didnt undestand how to save svg file in figma without `fill="black"` option

**Comment by MrGrigri** [comment]
Thanks @MaksUr for your contribution. The black fill doesn't matter much. What does matter, is this needs to be a single compound path. In Figma, once you've united the path, you can press `Ctrl + e` or `Cmd + e` and it will create a compound path for you. Once you've done that, we'll add this as a contribution assigned to you.

**Comment by MrGrigri** [comment]
P.S. I can see this icon being very useful. Thanks again.

**Comment by CoDEmanX** [comment]
As MrGrigri says, we only need a single path. In an SVG file, that would be the part in quote marks:

`<path d="M 7.5,4 C 5.567,4 4,5.73858…" />`

Any additional attributes like `style="fill:black;fill-opacity:1;…"` do not matter. We only store the path data in the database.

**Comment by MaksUr** [comment]
@MrGrigri  @CoDEmanX  Thanks a lot.
I fixed it:
![image](https://user-images.githubusercontent.com/26674247/74927448-71d57c80-53f9-11ea-9263-da622159fb24.png)

[monitor-eye.zip](https://github.com/Templarian/MaterialDesign/files/4230286/monitor-eye.zip)

**Comment by Templarian** [comment]
Added. @MaksUr let me know when you've hit 5 icons and we'll add a contributor account.
