### ISSUE TITLE
ticket-confirmation-outline

### ISSUE THREAD

**Issue by philtomblin** [Templarian/MaterialDesign#4905]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This is an outline version of the existing "ticket-confirmation" icon - usage would be similar to existing

## Examples

Looks like existing ticket-confirmation, but outline only (i.e. like ticket-outline but with the dotted-line perforations from ticket-confirmation).

**Comment by CoDEmanX** [comment]
It's a stock icon: https://material.io/resources/icons/?search=confirm&style=outline
Added to our backend.

![grafik](https://user-images.githubusercontent.com/1309249/74861821-45632700-534b-11ea-84aa-e4e5ccf146f6.png)
