### ISSUE TITLE
Add flags of all countries

### ISSUE THREAD

**Issue by Yourney** [Templarian/MaterialDesign#4906]
I know it will probably be a huge undertaking, but I'd love to see the flags of the world entered in this icon set. I do not know if it is even possible, given the fact that flags typically have verious colors.

**Comment by JamesCoyle** [comment]
Yeah this isn't gonna be possible as our icons are single color icons. I'd recommend just using one of the SVG world flags sets that are available. 

[This one is good if you want uniform sizes](https://flagicons.lipis.dev/)
[This one seems better if you want accurate sizes and colors](https://hjnilsson.github.io/country-flags/)
