### ISSUE TITLE
Alert modifier inconsistencies

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#4908]
In certain icons it is unavoidable to use a shorter than pleasing exclamation mark because of space constraints, but in cases where it is placed on the right-hand side, there is usually sufficient space. Yet, some of our icons use a 5+2 exclamation mark, but 6+2 looks much better IMO and also centers perfectly:

![grafik](https://user-images.githubusercontent.com/1309249/74862775-033ae500-534d-11ea-8ecb-bcb371aa1ebe.png) ![grafik](https://user-images.githubusercontent.com/1309249/74862926-42693600-534d-11ea-944d-858554bd39f0.png)

A secondary inconsistency is the margin to the right. Should it generally be 2dp? Or should we rather place it in a way that there is at least a 2dp gap to the main shape? For above icons, I would not change the placement (but only extend the upper stroke from 5 to 6).

**Comment by goyney** [comment]
6+2 with a 2dp spacing between the main icon content and the exclamation point.

**Comment by goyney** [comment]
The kettles have been updated. Do you have a list of others that need to be updated as well @CoDEmanX?

**Comment by CoDEmanX** [comment]
Updated:
- account-alert
- account-alert-outline
- alert-octagon (replaced circle by square in exclamation mark)
- badge-account-alert
- badge-account-alert-outline
- battery-alert-variant
- battery-alert-variant-outline
- beaker-alert
- beaker-alert-outline
- bell-alert
- bell-alert-outline

To be discussed:
- alert-outline - very little space, use modifier version (5dp line, 1dp space, 2dp dot)? But this would have to be done to the solid version as well but there is actually enough space to make it longer. Perhaps just make the line longer in the solid version?
- alert-rhombus-outline - the outline stroke is 1.697dp instead of 2dp. Fix it?
  `M12 2C11.5 2 11 2.19 10.59 2.59L2.59 10.59C1.8 11.37 1.8 12.63 2.59 13.41L10.59 21.41C11.37 22.2 12.63 22.2 13.41 21.41L21.41 13.41C22.2 12.63 22.2 11.37 21.41 10.59L13.41 2.59C13 2.19 12.5 2 12 2M12 4L20 12L12 20L4 12M11 7V13H13V7M11 15V17H13V15Z`
  ![grafik](https://user-images.githubusercontent.com/1309249/80312388-426e3200-87e5-11ea-90ac-96b3ec169ca3.png)
- battery-alert-bluetooth, battery-alert, battery-charging-wireless-alert - centering the exclamation mark is not a good idea, because it would take too much attention from the upper battery shape away. The exclamation mark line should be extended, but it's unclear whether that should be at the top or bottom end. 

No action:
- alert-box
- alert-box-outline
- alert-circle-check
- alert-circle-check-outline
- alert-circle
- alert-circle-outline
- alert-decagram
- alert-decagram-outline
- alert-octagon-outline
- alert-octagram
- alert-octagram-outline
- alert-rhombus
- car-brake-alert
- dishwasher-alert
- fire-hydrant-alert
- flash-alert
- flash-alert-outline
- fridge-alert
- fridge-alert-outline
- kettle-alert
- kettle-alert-outline
- progress-alert
- reload-alert
- restart-alert
- restore-alert
- shield-alert
- shield-alert-outline
- snowflake-alert
- sync-alert
- table-alert
- timeline-alert-outline
- timeline-alert
- tumble-dryer-alert
- washing-machine-alert
- water-boiler-alert
- weather-sunny-alert

To do:
- 62 more alert icons to check

**Comment by goyney** [comment]
Anything without a strikethrough in it got updated and will be available in v5.6.

**Comment by Simran-B** [comment]
Some of the icons are apparently inconsistent still, need to investigate. So far, I found the following:

Too tall exclamation mark:
- `content-save-alert`
- `content-save-alert-outline`

Too short:
- `garage-alert`
- `garage-alert-variant`
- `window-shutter-alert`

**Comment by goyney** [comment]
The garage alerts were done purposefully to look optically correct because of the slanting roofline. The rest that are contained all look fine.

**Comment by goyney** [comment]
@Simran-B Where are with with these updates?

**Comment by Simran-B** [comment]
@goyney Do we wanna do anything about the "odd height" ones? If not, then this can be closed.

**Comment by goyney** [comment]
I think all the odd height ones are limited by their containers, so they're okay to leave. Closing! Thanks for the detective work and helping get these fixed!
