### ISSUE TITLE
brightness-2-outline

### ISSUE THREAD

**Issue by KasaP-AndroDev** [Templarian/MaterialDesign#4909]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use this icon in android app for change brightness of phone.
I need Vector Drawable (.xml)

## Examples
![brightness-2](https://user-images.githubusercontent.com/60508681/74925098-ddfbb480-53e8-11ea-8538-d514c2aaa0f0.png)

Include any example images so we know what the icon should look like.

**Comment by KasaP-AndroDev** [comment]
Please design for me!

**Comment by goyney** [comment]
We get to issues as soon as we can. We're all volunteers here after all.

Additionally, we are working to get our HUGE 5.0 release out. That's taking up most of our time at the moment. In other words, we'll get to it when we get to it.
