### ISSUE TITLE
I have been looking for a comment icon that's unique or not so old and couldn't find one and so I'd like to share one that I made. Let me know what you think of it.

### ISSUE THREAD

**Issue by Juliotati** [Templarian/MaterialDesign#4911]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just 
[comment_icon.zip](https://github.com/Templarian/MaterialDesign/files/4239326/comment_icon.zip)
need the SVG tag with the viewbox and a single path element.

**Comment by goyney** [comment]
Here is a screenshot of the contribution.
![Screen Shot 2020-02-22 at 12 54 48 PM](https://user-images.githubusercontent.com/1015040/75096919-838e5f80-5572-11ea-80be-12b8fe722771.png)

While we appreciate new ideas and contributions to this library, you did not follow [Material guidelines at all](https://material.io/design/iconography/system-icons.html).

The biggest ones are:

- The icon must be on a 24x24dp grid.
- The icon must include a 2dp buffer area (unless absolutely necessary to break into it), leaving you with a 22x22dp grid to design on.
- The icon's elements should be as geometrical and even as possible.
- The icon should be aligned to the grid as best as possible.
- The icon should be combined down to a single compound path.

If you would like to take another try, please read the guidelines and submit a new contribution. You can use the [preview generator](http://dev.materialdesignicons.com/contribute/github) to see what your icon would look like. If it renders there, it can be considered for addition.
