### ISSUE TITLE
home-search-outline

### ISSUE THREAD

**Issue by forrestw92** [Templarian/MaterialDesign#4914]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon for searching for homes or properties.

## Examples

Have no idea to design but something along these lines.
![image](https://user-images.githubusercontent.com/35408046/75125075-dd794d00-5678-11ea-8b99-6c8e6a4b4280.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/75135199-68247100-56a6-11ea-8117-362bfa016d6c.png)

The cut out is interesting.

**Comment by goyney** [comment]
I'd remove the doorway for the filled and outlined version of this.

**Comment by MrGrigri** [comment]
All of our other home modifiers are in the middle.

**Comment by goyney** [comment]
This one probably will need to break that pattern due to the size of the magnifying glass.

**Comment by MrGrigri** [comment]
Agreed, I just wanted to point it out.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/75641931-d23d9880-5c07-11ea-962c-bfa3d5f56ff0.png)![image](https://user-images.githubusercontent.com/1015040/75641949-db2e6a00-5c07-11ea-84cf-ea0e42512fc1.png)

**Comment by Templarian** [comment]
Added. 👍
