### ISSUE TITLE
home-plus-outline

### ISSUE THREAD

**Issue by forrestw92** [Templarian/MaterialDesign#4915]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Add new home or property to a list.

## Examples

Excuse my designing skills again.
![image](https://user-images.githubusercontent.com/35408046/75125266-ec143400-5679-11ea-9be3-ba472f96fbf9.png)

**Comment by goyney** [comment]
I'd remove the doorway for the outlined and filled version of this.

**Comment by MrGrigri** [comment]
All of our other home modifiers are in the middle.

**Comment by goyney** [comment]
Good call.

**Comment by goyney** [comment]
All three modifiers are in the same center position here, but the plus looks off and may need to come up one 1dp.

![image](https://user-images.githubusercontent.com/1015040/75642206-b1c20e00-5c08-11ea-83fe-6fff1307a3e9.png)![image](https://user-images.githubusercontent.com/1015040/75642215-ba1a4900-5c08-11ea-9953-f8d4cad05ab6.png)
![image](https://user-images.githubusercontent.com/1015040/75642229-c1d9ed80-5c08-11ea-8d7d-5ab9b72374b7.png)

[home-outlines.zip](https://github.com/Templarian/MaterialDesign/files/4273231/home-outlines.zip)

**Comment by goyney** [comment]
All three added.
