### ISSUE TITLE
pallet

### ISSUE THREAD

**Issue by Cyborg-dev** [Templarian/MaterialDesign#4916]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The icon will be used in an asset monitoring app

## Examples

Include any example images so we know what the icon should look like.

![image](https://user-images.githubusercontent.com/61398633/75125927-8d3ed100-56f2-11ea-9b08-2d411411840b.png)

**Comment by goyney** [comment]
You searched? #2848
