### ISSUE TITLE
Meta.json has a large number of  incorrect codepoint values

### ISSUE THREAD

**Issue by JohnnyWestlake** [Templarian/MaterialDesign#4919]
Example, take:

```
{
    "id": "F8E5E9B6-9953-46F8-84DC-CFBB11DEFFB7",
    "name": "dice-1",
    "codepoint": "F01CA",
    "aliases": [
      "die-1",
      "dice-one"
    ],
    "tags": [
      "Gaming \/ RPG"
    ],
    "author": "Yasmina Lembachar",
    "version": "1.5.54"
  },
```

The actual codepoint of the glyph is `F1CA`, not `F01CA` as listed here. A large number of glyphs have similar issues. Probably something small in whatever generates meta.json.

(This is based on the current public download of the TTF version of this font, and mostly a concern to me as I'm working on a character map / font viewer, and I'd like to be able to map glyphs to names)

Perhaps related to V5 release

**Comment by Templarian** [comment]
Related: #4806

You want the versioned repo: https://github.com/Templarian/MaterialDesign-SVG

This repo is real-time. A large part of 5.0 is fixing our codepoints. The final verdict was to break all codepoints rather than randomly updating incorrect ones.

**Comment by Templarian** [comment]
The webfont should always be using the CSS class names in the CSS file. Codepoints are note a way to uniquely identify an glyph.

If you need a desktop font (but this is very new and the preview.html is not currently committed for this repo): https://github.com/Templarian/MaterialDesign-Font

**Comment by JohnnyWestlake** [comment]
Thanks. Re: the TTF files, it would be helpful for my usecase if the version string could be included in the file metadata, so I can choose the correct codepoint list to use (as a desktop based font viewer I have to rely on codepoint).

I believe svg2ttf supports version strings with the `--vs` argument, like `--vs 5.0.0` or something.

**Comment by Templarian** [comment]
Yeah, I'll add that to the `@mdi/font-build` package.

Yes, v5.0's `-Font` repo is being built specifically for that use case. v4 and below has no desktop support at all. People incorrectly installed the webfont which creates a ton of headaches.

**Comment by Templarian** [comment]
Reopening until I've updated `@mdi/font-build` with the version information.

**Comment by Templarian** [comment]
Okay, `@mdi/font-build` supports `version` in 1.8 once it's released. Need to get some other changes into 1.8 before publishing.
