### ISSUE TITLE
Volunteering to improve website user experience

### ISSUE THREAD

**Issue by topzdev** [Templarian/MaterialDesign#4921]
I know this issue is not a question but I have a little concern bout the user experience in this site. 

I'm trying to navigate on mdijs website it's very slow even in searching icons it takes time to load the icons.

So my solution is to recreate and redesign the website by using web framework like vue.js to have more interactive and good user experience not just for the user also for contributors of this great community for free. or instead, there is an API to fetch all icons? so that I can create my own website base on the existing mdijs site. 

Thank you and more power mdijs! 

ps: Sorry for my bad english :)

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Site/

The v2 site under development under development above. v2 API's are:
http://dev.materialdesignicons.com/contribute/site/api

**Comment by Templarian** [comment]
Not to close it hastily. Please keep discussion in that repo. Thanks.

**Comment by Templarian** [comment]
Definitely a lot of things that need to redone on the new icons page, it will be our main focus after v5:

http://dev.materialdesignicons.com/icons

**Comment by topzdev** [comment]
Wow, that's great hoping that it will release soon. I didn't see that at first haha anyways more power to you @Templarian and other contributors in this community.

**Comment by Templarian** [comment]
Thanks. If you want to learn more: http://dev.materialdesignicons.com/contribute/site
