### ISSUE TITLE
video-3D-off

### ISSUE THREAD

**Issue by cezar-darac** [Templarian/MaterialDesign#4923]
I have:

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/76042772-abdb6e00-5f23-11ea-8571-56fc87ebbe4b.png)

## Zip Download
[3D_off.svg.zip](https://github.com/Templarian/MaterialDesign/files/4250442/3D_off.svg.zip)

**Comment by Templarian** [comment]
@cezar-darac Can you paste the preview as the template explains so we can see the contribution. Thanks.

**Comment by goyney** [comment]
[![video-3d-off](https://materialdesignicons.com/icon/video-3d-off)](https://materialdesignicons.com/icon/video-3d-off)

Added and assigned to the global Contributor account until you have 5 added contributions. :)
