### ISSUE TITLE
Add Youtube Icon

### ISSUE THREAD

**Issue by abhijeet-infobeans** [Templarian/MaterialDesign#4924]
I have:

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by JamesCoyle** [comment]
Please follow the instructions in the issue template and search before requesting an icon. We already have a YouTube icon:
[![](https://materialdesignicons.com/icon/youtube)](https://materialdesignicons.com/icon/youtube)

Please only use the contribution template for submitting your own icon creation. Requests should just use the icon request template.
