### ISSUE TITLE
car direction icon

### ISSUE THREAD

**Issue by MrHad** [Templarian/MaterialDesign#4925]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It would be helpful to have icons indicating the direction of car travel (left/right, there/back), for example in travel instructions, or in system for reporting of travel expenses where each direction of business travel is reported separately.

 It would be indicated by simple arrow above the standard car icon. 

Thanks for consideration!

## Examples

Quick mockup of an idea how it could look like:

![image](https://user-images.githubusercontent.com/61497762/75335865-78954100-588a-11ea-86df-c96fe1e4476b.png)

**Comment by goyney** [comment]
We cannot implement the proposed design without breaking a bunch of Material guidelines or shrinking the car. I recommend we use our standard cut-off.

![image](https://user-images.githubusercontent.com/1015040/75642754-9a842000-5c0a-11ea-8238-6a835ade8ce8.png)![image](https://user-images.githubusercontent.com/1015040/75642760-a1129780-5c0a-11ea-9bd2-c1aee5bbf91e.png)

[car-arrow.zip](https://github.com/Templarian/MaterialDesign/files/4273265/car-arrow.zip)

**Comment by MrHad** [comment]
Thank you! I think cut-off works just fine, the meaning stays the same.

**Comment by Templarian** [comment]
These were added.
