### ISSUE TITLE
thermometer outline/filled

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4926]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
as an indicator of temp levels without any further embellishments like alerts or lines
## Examples

Include any example images so we know what the icon should look like.

as tiltle suggest: only the formfactor of thermometer with:
outline: only the outer lines
full/filled: the full outline filled

I realize [this discussion](https://github.com/Templarian/MaterialDesign/issues/3291) was closed, but can't seem to find a definitive njet on the outline and filled version.

would appreciate if this became possible.
thanks for considering.

**Comment by goyney** [comment]
Not sure what we'd name these, or if they are even necessary. What is your use case that our various leveled icons cannot solve?

![image](https://user-images.githubusercontent.com/1015040/76043081-6ff4d880-5f24-11ea-99b0-62ac2dc9d03e.png)![image](https://user-images.githubusercontent.com/1015040/76043094-797e4080-5f24-11ea-8c57-b0c46a9a7bf4.png)

[thermometer.zip](https://github.com/Templarian/MaterialDesign/files/4296089/thermometer.zip)

**Comment by Mariusthvdb** [comment]
hi, and thanks for these icons, which I do hope you would add. Imho, these 2 were the only 2  missing left in the variation  levels, as the outer extremes of max and min.

they are truly simple and unambiguous, please add?
thanks for considering.

**Comment by goyney** [comment]
I honestly don't think these are worth adding. There is never, under normal circumstances, an absence or an infinite amount of temperature. The icons we currently have hit the high, medium, and low points which should be enough, contextually, to convey the require meaning. I recommend we reject this.

**Comment by Mariusthvdb** [comment]
HI Michael,

Please let me add these to my https://github.com/Mariusthvdb/Custom-icons? Ofc, fully credited.

**Comment by goyney** [comment]
We're not going to add them here, so sure, you may use them in your custom library for Home Assistant with proper accreditation.

**Comment by Mariusthvdb** [comment]
thanks!
Please have a look if the accreditation Ive used so far is what it should be.Ive tried to be as complete as possible, both using the authors bio, material and pr/issue links
