### ISSUE TITLE
lipstick

### ISSUE THREAD

**Issue by iiiiiiines** [Templarian/MaterialDesign#4927]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/49793239/75369642-c9468180-58fe-11ea-92d4-7b0d84b534d0.png)

Sorry I just can't get the preview generator right, wonder is there anything I can do to fix it?

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[lipstick.svg.zip](https://github.com/Templarian/MaterialDesign/files/4257174/lipstick.svg.zip)

**Comment by Templarian** [comment]
Added to the shared contributor account. Let me know when you're at 5 icons and I'll create a contributor account. 👍 

[![lipstick](https://materialdesignicons.com/icon/lipstick)](https://materialdesignicons.com/icon/lipstick)

... little difficult to tell what it is at 1:1.
