### ISSUE TITLE
S3 Icon

### ISSUE THREAD

**Issue by jshah** [Templarian/MaterialDesign#4929]
I have:

- [ x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Concourse CI uses Material icons for its resources. S3 is a very popular resource that is used and it would be amazing if we could show a S3 logo.

Not sure if this counts as "brand" but it said:

> We may consider technology-related logo icons based around development (e.g. Webpack) for well-known tools, but these will be done on a case-by-case basis.

## Examples

Just the plain logo: 
https://cdn2.iconfinder.com/data/icons/amazon-aws-stencils/100/Storage__Content_Delivery_Amazon_S3-512.png

Bucket with S3 on it:
https://www.filepounder.com/assets/images/steps/aws-s3-bucket.svg

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by jshah** [comment]
@goyney I posted this in my initial issue but under the link it says:

"We may consider technology-related logo icons based around development (e.g. Webpack) for well-known tools, but these will be done on a case-by-case basis."

I would consider S3 a "technology-related" logo just like "Webpack"? If it's not done as a case-by-case basis, thats okay but if it doesn't violate the rules, is it okay to leave up?

**Comment by goyney** [comment]
This is mostly rejected because there is not a single color version of this logo.

**Comment by Templarian** [comment]
It is a valid tech icon, but it's also what I would consider too niche and can be represented by a more generic icon. There are way too may services offered by the top platforms. We would get into a never ending story trying to represent them all specifically. So generic icons are best.

**Comment by PeterShaggyNoble** [comment]
This is one of the reasons we recommend Simple Icons: so that we're not rejecting requests for brands without offering an alternative that works well with MDI.

As you can see above, I've already opened an issue for you to request S3. However, as there isn't an official vector version of the logo available (that we've yet found), never mind a monochrome one, it may take a while to fulfill.
