### ISSUE TITLE
Does it support IE8?

### ISSUE THREAD

**Issue by zacksleo** [Templarian/MaterialDesign#493]
Does it support IE8?

**Comment by Templarian** [comment]
Should, I just noticed that https://cdn.materialdesignicons.com/1.1.70/ preview doesn't due to a JS error though.

You will be the first to test it, let me know if you see any errors. If I find some time I'll try and fix the preview to work with legacy.

**Comment by gervye** [comment]
Well, I just had the problem with IE8. It does not work because the css uses double colon-notation for all ::before pseudo-elements. 
Could you use single-colon notation as in the Font-Awesome css ?

**Comment by Templarian** [comment]
Definitely could make this change for the next version.

Marked this as a bug so it will be fixed in the next release.

**Comment by gervye** [comment]
Cool. Thanks !

**Comment by zacksleo** [comment]
Found the reason, @gervye is right. Thanks !

**Comment by Templarian** [comment]
Okay, these has been modified in the build step and will be in the next release this week. :smile:

**Comment by Templarian** [comment]
I made the `preview.html` also sort of work in IE for `v1.2.64` (it uses some CSS3, so it doesn't format nicely, but it does render, not a big deal, but just wanted to show that the icons do work, just incase anyone tests it).

Coming soon, wrapping up a few more bugs before releasing.
