### ISSUE TITLE
MacDonald's

### ISSUE THREAD

**Issue by Lomba8** [Templarian/MaterialDesign#4930]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Flutter app

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by Lomba8** [comment]
Thank you for the fast reply


Il giorno gio 27 feb 2020 alle ore 18:33 Michael Irigoyen <
notifications@github.com> ha scritto:
