### ISSUE TITLE
Rocket Ship

### ISSUE THREAD

**Issue by brookenbrooklyn** [Templarian/MaterialDesign#4931]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator]
## Zip Download
![image](https://user-images.githubusercontent.com/16228384/75481362-efa50500-5970-11ea-87ff-5a1bc0319b8f.png)

![image](https://user-images.githubusercontent.com/16228384/75479644-db133d80-596d-11ea-94a9-e882933be72b.png)

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[rocket_ship.svg.zip](https://github.com/Templarian/MaterialDesign/files/4263477/rocket_ship.svg.zip)
[rocket_ship_solid.svg.zip](https://github.com/Templarian/MaterialDesign/files/4263790/rocket_ship_solid.svg.zip)

**Comment by Templarian** [comment]
@brookenbrooklyn Can you edit your issue with the preview, so we can compare it with our current `rocket` icon.

**Comment by brookenbrooklyn** [comment]
<img width="24" alt="rocket_ship@2x" src="https://user-images.githubusercontent.com/16228384/75476786-34c53900-5969-11ea-97ed-125e0876938b.png">

**Comment by brookenbrooklyn** [comment]
@Templarian Such a quick response! 

I'm new to contributing so still figuring out how to add everything here.

**Comment by Templarian** [comment]
We might want to look into replacing our current rocket icon as it's not very material. This would also let us add an outline/solid version. 👍 Fill in the center of the rocket and cutout the window.

@brookenbrooklyn There is a preview generator that creates fancy icon previews that can be pasted into github issues described in the issue template.

**Comment by brookenbrooklyn** [comment]
Thanks! I'll try to figure out the preview generator and created the filled in icon. Should I add the filled in version here or create a new issue? 

^will have to do that for all the other issues I just opened as well.

**Comment by goyney** [comment]
Google actually already has this icon created and we should probably replace ours with theirs. We, of course, need to make a filled version of it.

![Screen Shot 2020-03-01 at 10 36 41 PM](https://user-images.githubusercontent.com/1015040/75643464-2139fc80-5c0d-11ea-8b04-6c6ac3e549a2.png)

![image](https://user-images.githubusercontent.com/1015040/75643450-17b09480-5c0d-11ea-9bc8-00e25bf50ccd.png)

[rocket-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/4273310/rocket-outline.svg.zip)

**Comment by Templarian** [comment]
The google design might need some tweaks at the bottom of the rocket, let me try and do that in a minute, until then here were some tweaks to the other proposed design.

![image](https://user-images.githubusercontent.com/338885/75647844-dbccfd80-5c13-11ea-817e-4c0a0487c3b6.png)
![image](https://user-images.githubusercontent.com/338885/75647941-30707880-5c14-11ea-9c01-8a17de8629a0.png)
![image](https://user-images.githubusercontent.com/338885/75648001-60b81700-5c14-11ea-8d3d-af453912f4ae.png)

**Comment by Templarian** [comment]
Updated with Googles icon. Lot of cool ideas, but theirs is the simplest that works great in outline/solid.
