### ISSUE TITLE
Lightning Bolt

### ISSUE THREAD

**Issue by brookenbrooklyn** [Templarian/MaterialDesign#4932]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/16228384/75694787-16b44d00-5c77-11ea-9997-c850c7a38c53.png)

![image](https://user-images.githubusercontent.com/16228384/75693776-7a3d7b00-5c75-11ea-944f-c79e52402b34.png)

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[Lightning_bolt_outline.zip](https://github.com/Templarian/MaterialDesign/files/4276364/Lightning_bolt_outline.zip)

[Lightning_bolt.zip](https://github.com/Templarian/MaterialDesign/files/4276460/Lightning_bolt.zip)

**Comment by JamesCoyle** [comment]
If you are contributing multiple icons that are just variants of each other they can all be in one issue to make it easier to track when adding them.

**Comment by brookenbrooklyn** [comment]
Great. Thanks for the tip. Will update.

**Comment by goyney** [comment]
Thanks for the contribution. We'll need these updated to follow Material guidelines for consideration. Here's a few things that will need to be adjusted:

- There should be a 2dp buffer area around the edge.
- The points should be on grid.
- The outline shouldn't have rounded corners.

**Comment by JapanYoshi** [comment]
The official Google icons [``flash``](http://materialdesignicons.com/icon/flash) and our outline variant [``flash-outline``](http://materialdesignicons.com/icon/flash-outline) already exist.
![image](https://user-images.githubusercontent.com/8707990/75496995-955a8180-5a0e-11ea-92dd-49cae63dd3c0.png)
![image](https://user-images.githubusercontent.com/8707990/75497013-a0151680-5a0e-11ea-9ba8-cf85a18eaf37.png)
They even show up when you search for "lightning" on the page.

**Comment by goyney** [comment]
Yeah, but I could see this as being a good "lightning" icon on its own. We use the proposed variant on our battery charging icons. I'm in favor of adding these once they are cleaned up.

**Comment by brookenbrooklyn** [comment]
Material also has an offline_bolt that uses the lightning style. I believe they may have the bolt that i've attached as a solid bolt as well. I believe I've seen it before in gmail used to represent fast connectivity (maybe) but I'm having a hard time finding proof of this.

I've updated both bolts to have a 2px border. Let me know if there is anything else I can do.

**Comment by goyney** [comment]
We may need to adjust the size/shape a little bit to allow an outlined version work.

To achieve the required 2dp stroke, we need to break the 2dp buffer area slightly. Thoughts?

![image](https://user-images.githubusercontent.com/1015040/76022854-f0e8ab80-5ef5-11ea-813d-d0ebd5fa8ed9.png)![Uploading image.png…]()

[bolt.zip](https://github.com/Templarian/MaterialDesign/files/4295018/bolt.zip)

**Comment by Templarian** [comment]
Added. Also added a placeholder contributor account.
