### ISSUE TITLE
Sales Receipt

### ISSUE THREAD

**Issue by brookenbrooklyn** [Templarian/MaterialDesign#4934]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
<img width="24" alt="receipt@2x" src="https://user-images.githubusercontent.com/16228384/75477653-a6ea4d80-596a-11ea-83eb-b2e692a8c60a.png">

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[receipt.svg.zip](https://github.com/Templarian/MaterialDesign/files/4263525/receipt.svg.zip)

**Comment by goyney** [comment]
We have `receipt`. We won't add anything with a $ anymore as it is not globally usable.
[![receipt](https://materialdesignicons.com/icon/receipt)](https://materialdesignicons.com/icon/receipt)

**Comment by brookenbrooklyn** [comment]
makes sense.
