### ISSUE TITLE
Biography

### ISSUE THREAD

**Issue by brookenbrooklyn** [Templarian/MaterialDesign#4935]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/16228384/75693354-cfc55800-5c74-11ea-811e-770fed2b80a9.png)

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[auth_bio.svg.zip](https://github.com/Templarian/MaterialDesign/files/4263529/auth_bio.svg.zip)

**Comment by JapanYoshi** [comment]
That icon looks more like a hamburger menu for a list of users. Either way, I would consider this unnecessary, given that the official Google icon [``account-details``](http://materialdesignicons.com/icon/account-details) exists:

![image](https://user-images.githubusercontent.com/8707990/75496866-2ed56380-5a0e-11ea-916f-18c8851d6ead.png)

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/75587431-b1bce500-5a33-11ea-804f-ba69dafed21b.png) ![image](https://user-images.githubusercontent.com/4528551/75587460-c1d4c480-5a33-11ea-8421-b5416ac8ea6d.png)

[book-account.zip](https://github.com/Templarian/MaterialDesign/files/4269102/book-account.zip)

**Comment by Templarian** [comment]
Added the `book-account` icons, but I'm wondering if we can have a `text-account` icon? Where text is large and account is small.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/75636168-15851080-5be2-11ea-8347-1f34136d4704.png)

The one you submitted is basically the same as above, so it will count as a contribution. What do others think of a `text-account`.

**Comment by JapanYoshi** [comment]
I think it's redundant.

**Comment by Templarian** [comment]
Redundant, but in a scenario where `text` is already being used as the default option and one wanted to describe a textblock using overlays.

Kind of like how we have overlays for `text-box` right now.

**Comment by JapanYoshi** [comment]
Already default? Describe? Textblocks? Overlays? Those sentences didn't mean anything to me. Can you explain what they mean?

**Comment by Templarian** [comment]
In a UI where there is a list of options. The list read "Text", "Author Biography" (inserts profile photo + text section), "Quote Block", etc. One wouldn't use the same text icon for each.

We could then create overlays in the corner for for `text-account`, `text-quote` etc.

**Comment by goyney** [comment]
[![text-account](https://materialdesignicons.com/icon/text-account)](https://materialdesignicons.com/icon/text-account)
