### ISSUE TITLE
Edit Page

### ISSUE THREAD

**Issue by brookenbrooklyn** [Templarian/MaterialDesign#4936]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
<img width="24" alt="EDIT_page@2x" src="https://user-images.githubusercontent.com/16228384/75477944-0c3e3e80-596b-11ea-967c-8d849f3c5eeb.png">

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[EDIT_page.svg.zip](https://github.com/Templarian/MaterialDesign/files/4263546/EDIT_page.svg.zip)

**Comment by goyney** [comment]
Am I missing something here?

[![file-edit](https://materialdesignicons.com/icon/file-edit)](https://materialdesignicons.com/icon/file-edit)
[![file-edit-outline](https://materialdesignicons.com/icon/file-edit-outline)](https://materialdesignicons.com/icon/file-edit-outline)

**Comment by brookenbrooklyn** [comment]
It's a different variation of the idea. It works better for our company's use case but if you don't think it should be included... then don't include it. Just trying to contribute icons that I've had to create. Not offended if they don't get incorporated.

**Comment by goyney** [comment]
Appreciate the different variation, however our `-edit` modifier is typically paired with one of our base icons. Our "page" base is `file`, so those two icons above would it. I'll let some of the other contributors chime in here, but I don't think this is something we're likely to add just because we already have icons that convey the same meaning.

**Comment by JapanYoshi** [comment]
You're more than welcome to use your variant, but we're not inclined to add it because it violates how the ``-edit`` modifier is used consistently throughout our icon set.

**Comment by brookenbrooklyn** [comment]
The official material icons actually use it in the upper right. see circle-edit-outline and edit_location for example.

The scenario we are using it for is edit webpage–not file or paper. The edit file icon doesn't work for us in this situation. 

If it's helpful for the community, happy to have it added.
