### ISSUE TITLE
mdiBed is missing in @mdi/js

### ISSUE THREAD

**Issue by Mycl95** [Templarian/MaterialDesign#4937]
Hi,

mdiBed is missing in @mdi/js

**Comment by goyney** [comment]
`bed` was renamed for the 5.0 release which will be going out in the next couple weeks. The old name was `hotel`, so you should be able to use that until 5.0.

See https://github.com/Templarian/MaterialDesign/issues/4901 for more information.

**Comment by Templarian** [comment]
#4901

Think it's called hotel in that version. Use the CDN to see 4.9.95: https://cdn.materialdesignicons.com/4.9.95/

**Comment by Mycl95** [comment]
Alright thanks! On materialdesignicons.com it's already saying mdiBed.
