### ISSUE TITLE
Engine icon

### ISSUE THREAD

**Issue by asdiallo** [Templarian/MaterialDesign#494]
Add an Engine icon

**Comment by CoDEmanX** [comment]
![engine](https://cloud.githubusercontent.com/assets/1309249/9088405/2b592008-3b90-11e5-9d8f-1f2210524d46.png) ?

**Comment by asdiallo** [comment]
Yes, It is perfect.

-----Message d'origine-----
De : "CoDEmanX" <notifications@github.com>
Envoyé : ‎05/‎08/‎2015 16:37
À : "Templarian/MaterialDesign" <MaterialDesign@noreply.github.com>
Cc : "asdiallo" <abdoulsalamy@yahoo.fr>
Objet : Re: [MaterialDesign] Engine icon (#494)

 ?

**Comment by Templarian** [comment]
Agreed that is perfect. Very material, but instantly recognizable.

**Comment by CoDEmanX** [comment]
In case you prefer an outlined version:
![engine-border](https://cloud.githubusercontent.com/assets/1309249/9091217/4180fc66-3b9f-11e5-95d6-87d44dc35f98.png) https://www.dropbox.com/s/jvexo4f605y33hm/engine-border.svg?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/engine
https://materialdesignicons.com/icon/engine-outline
