### ISSUE TITLE
tailwind css / ui

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#4940]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Tailwind UI/CSS logo. We include a lot CSS framework logos in the set.

We usually verify with the maintainer for the project to see if they are fine with the addition. @adamwathan are you fine with this being added in a future update.

If we don't get a reply in a week I'll ping Steve Schoger as he'll probably be able to get an official answer.

## Examples

Logo taken from their website: https://tailwindui.com/img/tailwindui-logo-on-dark.svg

**Comment by Templarian** [comment]
@sschoger Pinging to get an eye on this. Would be nice to add this especially with the UI components in preview. Missed the `5.0.45`, cut off, but could get it into `5.1.xx`.

**Comment by PeterShaggyNoble** [comment]
Went ahead and knocked this together, to provide a preview.

[![tailwind-ui](https://user-images.githubusercontent.com/15157491/76209944-006c3b00-61fb-11ea-87e2-2b8189dba3eb.png)](https://github.com/Templarian/MaterialDesign/files/4306389/tailwind-ui.zip)

**Comment by adamwathan** [comment]
Totally fine with this! 👍 Thank you for pushing it forward!

**Comment by Templarian** [comment]
This one was added. Will be part of the `5.1.xx` release as `tailwind` (since the same icon is used for both).
