### ISSUE TITLE
 mdi-circle-slice-8 is not consistent with its "predecessors"

### ISSUE THREAD

**Issue by rsaleri** [Templarian/MaterialDesign#4941]
You can check the issue here: https://codepen.io/rsaleri/full/dyoRLME
Grab the slide to 8 to see the issue: until 7 the sliced circle is consistent, whet it comes to 8 is like the 4 quadrants go off and the circle is somehow blunt
Comparing 7 and 8 makes it more visible, I put 3, 4, 5 and 6 only to show that until 7 it's consistent.

**Comment by Templarian** [comment]
Definitely a bug going on here. Good find!

**Comment by Templarian** [comment]
Fixed in v5.
