### ISSUE TITLE
Project List

### ISSUE THREAD

**Issue by TheWilks** [Templarian/MaterialDesign#4942]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I am using the mdi-pencil-ruler to indicate a project and am looking for an icon that indicates a list of all projects.

## Examples

Looking to follow this pattern...

![Capture1](https://user-images.githubusercontent.com/6516828/75803910-2d2cd800-5d4d-11ea-8f9c-bd91943bc8c1.PNG)

![Capture](https://user-images.githubusercontent.com/6516828/75803768-f35bd180-5d4c-11ea-9ec6-7601e0f6f153.PNG)

**Comment by goyney** [comment]
If you're looking for the pencil/ruler combo in the corner there, that isn't going to work. Do you have any other ideas or can you further clarify what you expect?

**Comment by TheWilks** [comment]
Why will that not work? Seems like it follows the pattern that has already been set.

**Comment by goyney** [comment]
Because all detail is lost when the pencil/ruler is shrunk down. We cannot follow Material guidelines and make it distinguishable.

![image](https://user-images.githubusercontent.com/1015040/76136369-b0288980-5ffe-11ea-8ce7-3c01cd9d9db2.png)

If you have other ideas, feel free to pitch them.

**Comment by TheWilks** [comment]
Makes sense thanks for the explanation.

**Comment by TheWilks** [comment]
![1B50B7DE-ADE1-42D3-A092-04778E1E929C](https://user-images.githubusercontent.com/6516828/76136535-8a03e900-6000-11ea-90e1-b8ec618e0201.jpeg)

Maybe something like this works better? It may allow for a bit more detail to be shown.

**Comment by goyney** [comment]
It's better, but still not sure. Let's see what the other contributors think.
![image](https://user-images.githubusercontent.com/1015040/76168209-e15ea200-6143-11ea-9a66-2212d3773ae3.png)![image](https://user-images.githubusercontent.com/1015040/76168213-e7ed1980-6143-11ea-95e9-ec1137cf2751.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4303601/Archive.zip)

**Comment by Templarian** [comment]
No on that icon. Way too much detail for the small size.

**Comment by goyney** [comment]
This issue has become stale with no new ideas. If you have other suggestions, please feel free to comment back. For now, we're going to close this out and recommend you use `pencil-ruler` for your use case.
