### ISSUE TITLE
Stop icon

### ISSUE THREAD

**Issue by rhuanbarreto** [Templarian/MaterialDesign#4943]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To display some categories marked as stop instead of using a PNG icon.

## Examples

![image](https://user-images.githubusercontent.com/283004/75875613-4ea4c700-5e14-11ea-9f76-a392586b1367.png)

**Comment by JamesCoyle** [comment]
We have an octagon icon:

[![](https://materialdesignicons.com/icon/octagon)](https://materialdesignicons.com/icon/octagon)

We can't add the text "Stop" as that wouldn't work internationally.
