### ISSUE TITLE
Torchiere Floor Lamp

### ISSUE THREAD

**Issue by arkansas-coder** [Templarian/MaterialDesign#4945]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This icon can be used to indicate a torchiere either on or off. Ideally, there would be two variants of this icon: one on; and one off.

## Examples

The fifth icon on row two:
https://www.istockphoto.com/vector/lighting-fixtures-and-equipment-icons-gm1043644776-279355437

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/76042619-4a1b0400-5f23-11ea-82df-229dc8040de4.png)

[floor-lamp-torchiere.svg.zip](https://github.com/Templarian/MaterialDesign/files/4296066/floor-lamp-torchiere.svg.zip)

We should probably renamed `floor-lamp-variant` to `floor-lamp-torchiere-variant` as well.

**Comment by arkansas-coder** [comment]
Thanks Michael, this looks good to me

**Comment by goyney** [comment]
Renamed the original and added the new.
