### ISSUE TITLE
export 'mdiCircleHalf' was not found in '@mdi/js'

### ISSUE THREAD

**Issue by pashinin** [Templarian/MaterialDesign#4946]
```
import { mdiCircleHalf } from '@mdi/js';
```

gives an error

```
export 'mdiCircleHalf' was not found in '@mdi/js'
```

And there is no such export. Maybe add these icons to mdi/js?

```
mdiCircleHalf
mdiCircleHalfFull
```

**Comment by goyney** [comment]
`circle-half` and `circle-half-full` were added in 5.0.45, which has not been released. When version 5 comes out, these will be available. You can see new additions, their corresponding GitHub issues, and release versions on the history page. https://dev.materialdesignicons.com/history
