### ISSUE TITLE
Biology Icon: virus

### ISSUE THREAD

**Issue by Sudo-Rob** [Templarian/MaterialDesign#4947]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
   Icon graphic for tracking COVID-19

## Examples

Include any example images so we know what the icon should look like.

![image](https://user-images.githubusercontent.com/56487711/75956188-5b153800-5e85-11ea-90e3-0451959b1dd6.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/75988212-38077a00-5ebf-11ea-9ff1-5e3bec6f9345.png)![image](https://user-images.githubusercontent.com/1015040/75988236-3f2e8800-5ebf-11ea-8b92-7f909958e955.png)

[virus.zip](https://github.com/Templarian/MaterialDesign/files/4293262/virus.zip)

**Comment by goyney** [comment]
These are now available from our website and will be included in v5.1.xx when it is released in the coming weeks.

[![virus](https://materialdesignicons.com/icon/virus)](https://materialdesignicons.com/icon/virus)[![virus-outline](https://materialdesignicons.com/icon/virus-outline)](https://materialdesignicons.com/icon/virus-outline)

**Comment by Sudo-Rob** [comment]
Excellent.  Will be looking for next release.

Thanks.
