### ISSUE TITLE
file-download-variant

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#4948]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Variant for [file-download](https://materialdesignicons.com/icon/file-download)

## Examples

![file](https://user-images.githubusercontent.com/6717356/75972242-2389a880-5ee4-11ea-8e45-6572a222d4db.png)

**Comment by goyney** [comment]
In the past, we chose to not use the cut-out on `file` icons and most modifiers are in the file itself. Unless we want to revisit all of these and move to a cut-out, I don't think this is something we're likely to add.
