### ISSUE TITLE
eyedropper-plus

### ISSUE THREAD

**Issue by innovate-invent** [Templarian/MaterialDesign#4949]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I need an icon to signify adding colors to a palette

## Examples

The same as pencil-plus but eyedropper-plus.

I will need eyedropper-minus as well.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/76042450-cc56f880-5f22-11ea-8583-19311625f62d.png)![image](https://user-images.githubusercontent.com/1015040/76042460-d37e0680-5f22-11ea-965f-e8f7f525ec29.png)
![image](https://user-images.githubusercontent.com/1015040/76042476-d973e780-5f22-11ea-9e06-0ac0b420e351.png)![image](https://user-images.githubusercontent.com/1015040/76042486-e09af580-5f22-11ea-97fa-ff854a2ed61a.png)

[eyedropper.zip](https://github.com/Templarian/MaterialDesign/files/4296054/eyedropper.zip)

**Comment by goyney** [comment]
All have been added and are now available from our website. They'll be available in our published packages when v5.1 is released in the coming weeks.
