### ISSUE TITLE
Constraint icon

### ISSUE THREAD

**Issue by asdiallo** [Templarian/MaterialDesign#495]
Add a constraint icon like  ->|<-

**Comment by CoDEmanX** [comment]
I created two versions:

![constrain](https://cloud.githubusercontent.com/assets/1309249/8654529/1e5a8fca-298b-11e5-8006-0cffd23ab78d.png) https://www.dropbox.com/s/5kqwczpx1yg40jo/constrain.svg?dl=0

![constrain2](https://cloud.githubusercontent.com/assets/1309249/8654530/1e5e6e42-298b-11e5-94c3-33d426578b55.png) https://www.dropbox.com/s/daiw7guh29fhjse/constrain2.svg?dl=0

The problem with the latter is the missing margin on the left and right. Some Google icons use this space, so it might be okay, but I still prefer the first, simplistic variant.

Maybe `link-variant` works as well for your purpose: https://materialdesignicons.com/

**Comment by CoDEmanX** [comment]
BTW: "align center vertical" might be a more appropriate name (there could be an additional horizontal variant).

**Comment by CoDEmanX** [comment]
Here's another with smaller arrows, based on `unfold-less`. It respects the 2dp margin:
![constrain3](https://cloud.githubusercontent.com/assets/1309249/8655572/54e67d40-2992-11e5-9ace-0dc53d3bcfc8.png) https://www.dropbox.com/s/av4a1w7tw2y629v/constrain3.svg?dl=0

**Comment by CoDEmanX** [comment]
There's actually a Google Icon, which just needs to be rotated:
https://www.google.com/design/icons/#ic_vertical_align_center

We could provide the other two related icons rotated too:
https://www.google.com/design/icons/#ic_vertical_align_top
https://www.google.com/design/icons/#ic_vertical_align_bottom

**Comment by CoDEmanX** [comment]
[![format-horizontal-align-center](https://materialdesignicons.com/icon/format-horizontal-align-center)](https://materialdesignicons.com/icon/format-horizontal-align-center) [![format-vertical-align-center](https://materialdesignicons.com/icon/format-vertical-align-center)](https://materialdesignicons.com/icon/format-vertical-align-center)
