### ISSUE TITLE
fuse-blown

### ISSUE THREAD

**Issue by jgladen** [Templarian/MaterialDesign#4950]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Indicate a fuse has blown vs the intact "fuse"

## Examples

![fuse-blown](https://user-images.githubusercontent.com/9341599/76025641-38653c80-5ee2-11ea-95c8-18d49d7c5f71.png)

**Comment by goyney** [comment]
I don't think your example will work within the space we have available, however perhaps one these would fit your use case?

![image](https://user-images.githubusercontent.com/1015040/76042100-d3c9d200-5f21-11ea-8375-a74d40400239.png)![image](https://user-images.githubusercontent.com/1015040/76042115-db897680-5f21-11ea-966a-38f7f69647d8.png)

[fuse.zip](https://github.com/Templarian/MaterialDesign/files/4296034/fuse.zip)

**Comment by goyney** [comment]
[![fuse-off](https://materialdesignicons.com/icon/fuse-off)](https://materialdesignicons.com/icon/fuse-off)[![fuse-alert](https://materialdesignicons.com/icon/fuse-alert)](https://materialdesignicons.com/icon/fuse-alert)
