### ISSUE TITLE
Can't use cog icon

### ISSUE THREAD

**Issue by Esquimor** [Templarian/MaterialDesign#4951]
Hello,

I have a little problem.
I can use the cog icon.
[example](https://jsfiddle.net/vzg4ye8q/)

It is in the google set so it strange.

Sorry for my english.

**Comment by Esquimor** [comment]
Sorry, my fault, for use the icon is "settings".

**Comment by PeterShaggyNoble** [comment]
Note that it _will_ be renamed as `cog` in the `v5.0.45` release, coming very soon. See our [pinned issue on breaking changes](https://github.com/Templarian/MaterialDesign/issues/4901) for more details.
