### ISSUE TITLE
TikTok Icon

### ISSUE THREAD

**Issue by outshot** [Templarian/MaterialDesign#4956]

**Comment by Templarian** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by PeterShaggyNoble** [comment]
This one is already available from Simple Icons:

[![Tik Tok](https://user-images.githubusercontent.com/15157491/76209323-7ff90a80-61f9-11ea-8310-d0862afabf65.png)](https://simpleicons.org/?q=Tik%20Tok)

**Comment by balibebas** [comment]
> We recommend checking out [SimpleIcons](https://simpleicons.org/).

Damn, literally needed one icon which wasn't in this library and it was TikTok. Here's what the Simple Icons `Tiktok` icon looks like sitting in a line of Material Icons. I'd change them all bu the Simple Icons are bulgy and some (like Telegram) don't even look like the actual logo. 😢 

<img width="305" alt="Screen Shot 2020-09-23 at 10 50 35 PM" src="https://user-images.githubusercontent.com/65664227/94029389-56977900-fdef-11ea-855d-03e580b71f66.png">

**Comment by goyney** [comment]
> and some (like Telegram)

Hate to burst your bubble, but you should probably start using the telegram icon from SimpleIcons.

https://github.com/Templarian/MaterialDesign/issues/5275

**Comment by balibebas** [comment]
It's all good. Think I'll just pin for now and roll onto a different icon pack. There's a nice buffet these days to choose from: https://icones.js.org. Thank you all for your continued support of FOSS.
