### ISSUE TITLE
human-male-board (human-male-board-poll)

### ISSUE THREAD

**Issue by MaksUr** [Templarian/MaterialDesign#4959]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

**human-male-board**
![image](https://user-images.githubusercontent.com/26674247/76163744-a3c13f80-616a-11ea-8936-2927f13da82c.png)
[human-male-board.zip](https://github.com/Templarian/MaterialDesign/files/4303240/human-male-board.zip)

**human-male-board-poll**
![image](https://user-images.githubusercontent.com/26674247/76163759-c9e6df80-616a-11ea-9a91-b5777631a5d8.png)
[human-male-board-poll.zip](https://github.com/Templarian/MaterialDesign/files/4303242/human-male-board-poll.zip)

There is icon [**teach**](https://materialdesignicons.com/icon/teach), but i dont like the man and the icon called incorrectly (very difficult to find for me).

![image](https://user-images.githubusercontent.com/26674247/76163819-50032600-616b-11ea-8e4d-640194421fa6.png)

**Comment by goyney** [comment]
Agree with the name change. However, this missed the 5.0 release and since it's a breaking change, will need to wait until 6.0 which is quite a bit away. I've added an alias to the icon for now to make it easier to find.

**Comment by goyney** [comment]
It terms of the new addition, we'll need to tweak the graph on the board as it's not really following Material guidelines.

**Comment by MaksUr** [comment]
@goyney 
> It terms of the new addition, we'll need to tweak the graph on the board as it's not really following Material guidelines.

Can you give me more details for fixing icon.
When i drew graph i saw [material design guide](https://material.io/design/iconography/system-icons.html#system-icon-metrics) (example with paperclip and cigaret)

**Comment by goyney** [comment]
The bar graphs are 1dp wide with 1dp, not-on-grid spacing in between. Using 1dp lines isn't Material and they're only used in very special cases. Ideally, we'd like to see those bars be at least 2dp wide, the spacing is debatable, but should at least try to be on grid.

**Comment by goyney** [comment]
`teach` has been renamed. The other variant with the charts still needs to be updated before it can be added.

**Comment by goyney** [comment]
[![human-male-board-poll](https://materialdesignicons.com/icon/human-male-board-poll)](https://materialdesignicons.com/icon/human-male-board-poll)
