### ISSUE TITLE
Account-Multiple-Minus

### ISSUE THREAD

**Issue by bhndbrwneyes** [Templarian/MaterialDesign#496]
Looking for account-multiple-minus icon. There are similar account-multiple and account-multiple-plus icons. Should be a simple addition.

**Comment by CoDEmanX** [comment]
Here it is:
https://www.dropbox.com/s/ocx4vroj1qs4z0n/account-multiple-minus.svg?dl=0

Directly derived from the plus variant, removed 6 path points.

**Comment by Templarian** [comment]
Agreed, closing this was the best move. It's too specific at this time.
