### ISSUE TITLE
Icon to represent meat

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4962]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To indicate meat contents, steakhouses, etc.

## Examples

![image](https://user-images.githubusercontent.com/1015040/76167747-685d4b80-613f-11ea-8147-0552e42eb425.png)
![image](https://user-images.githubusercontent.com/1015040/76167750-6eebc300-613f-11ea-99cc-8cef75103b7c.png)

## Other Notes

A steak and a chicken/turkey leg seem like two good new icons we can add. We'll need `off` variants of both for allergen use.

**Comment by goyney** [comment]
First attempt at a drumstick:
![image](https://user-images.githubusercontent.com/1015040/76176932-e42fb600-6188-11ea-95fb-21653c34b88a.png)![image](https://user-images.githubusercontent.com/1015040/76176939-ec87f100-6188-11ea-90c0-043c9c824e33.png)

[food-drumstick.zip](https://github.com/Templarian/MaterialDesign/files/4304350/food-drumstick.zip)

**Comment by goyney** [comment]
First attempt at a steak:
![image](https://user-images.githubusercontent.com/1015040/76177717-8355ad00-618b-11ea-8cc4-e8231b3c84d6.png)![image](https://user-images.githubusercontent.com/1015040/76177736-90729c00-618b-11ea-9259-8c37d6c674cd.png)
[food-steak.zip](https://github.com/Templarian/MaterialDesign/files/4304380/food-steak.zip)

**Comment by JamesCoyle** [comment]
I think the bone on the drumstick could do to be a bit shorter so it looks less handle like. At first I thought it was a maraca.

**Comment by goyney** [comment]
> I think the bone on the drumstick could do to be a bit shorter so it looks less handle like. At first I thought it was a maraca.

![image](https://user-images.githubusercontent.com/1015040/76214331-e161af00-61e2-11ea-9789-51dcf8b796e5.png)

**Comment by Templarian** [comment]
Agree the bone needs to be a tad shorter. Also lets try and remove maybe one diagonal line and make them thinner on the filled.

**Comment by goyney** [comment]
Updated drumsticks:
![image](https://user-images.githubusercontent.com/1015040/77132014-4663a300-6a34-11ea-88af-c790c942ea58.png)![image](https://user-images.githubusercontent.com/1015040/77132020-4d8ab100-6a34-11ea-8244-f2303e4eb497.png)

[food-drumstick.zip](https://github.com/Templarian/MaterialDesign/files/4357783/food-drumstick.zip)

**Comment by goyney** [comment]
I don't think going less than 1dp on the steak grill lines is a good idea.

**Comment by goyney** [comment]
Drumsticks were added.

**Comment by goyney** [comment]
Next iteration on the steaks:
![image](https://user-images.githubusercontent.com/1015040/81341544-b8915500-907f-11ea-8bb1-6a58fa19f670.png)![image](https://user-images.githubusercontent.com/1015040/81341757-11f98400-9080-11ea-96b4-06040f7f1610.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4595630/Archive.zip)

**Comment by goyney** [comment]
Steaks added.

**Comment by JapanYoshi** [comment]
I had a question: At least in Japan where I come from, meat in general can be represented by something like this. 
![image](https://user-images.githubusercontent.com/8707990/81493453-d101a980-92e3-11ea-8f88-e7ffe072a690.png)
Is this recognizable elsewhere as a general meat icon?

**Comment by Simran-B** [comment]
Looks like a variant of the more common drumstick:

![image](https://user-images.githubusercontent.com/7819991/81677841-8c941c00-9451-11ea-90bb-69977dd6b589.png)

e.g. Minecraft:

![image](https://user-images.githubusercontent.com/7819991/81678194-b9e0ca00-9451-11ea-84eb-9a3eae218b0f.png)
