### ISSUE TITLE
Rename conflicting form input icons

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#4963]
In our 5.0 release, we renamed all the `file-document-box` icons to `text-box`. This is a welcome change, however it clashes with an icon we already have simply called `textbox`. Importing both in `@mdi/js`, for example, looks like this:

```
import { mdiTextBox, mdiTextbox } from '@mdi/js';`
```

Not ideal.

---

We should rename our "form" based textbox, and a few others that match its intention, for better clarity.

- [x] Rename `textbox` => `form-field-textbox`
- [x] Rename `textbox-lock` => `form-field-textbox-lock`
- [x] Rename `textbox-password` => `form-field-textbox-password`
- [x] Rename `textarea` => `form-field-textarea`

If there are others I missed, or make sense to follow this naming pattern, please feel free to edit and add them.

**Comment by JamesCoyle** [comment]
Could probably add `date`, `time`, `color`, `number`, `image`, `file`, `email`, `phone`, `map-marker`, `select`.

**Comment by Templarian** [comment]
I'm not sure I actually view this as an issue. Maybe a 6.0 thing we can look at later on.

**Comment by goyney** [comment]
This is definitely a thing, I've already had several people reach out to me and complain today.

**Comment by Templarian** [comment]
Okay, lets push these in 5.1.45? I think it could bite us for users that remove `-` from the names or ENUM values.

**Comment by Templarian** [comment]
Reassigned to the 5.1.xx milestone. This is actually causing issues for third party scripts that consume `meta.json`. 😢

- [ ] Add script to verify no name collisions when `-` is removed.

**Comment by Templarian** [comment]
Closing. We'll track the script seperately.
