### ISSUE TITLE
Icon to represent agent or spy

### ISSUE THREAD

**Issue by karlsnyder0** [Templarian/MaterialDesign#4964]
I have:

- [ x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Inspect, or listen to.  For example, to listen in on network packets.

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/638810/76241875-120a0e80-620c-11ea-96c5-e95ff6041e2e.png)

**Comment by goyney** [comment]
Would `incognito` work?
[![incognito](https://materialdesignicons.com/icon/incognito)](https://materialdesignicons.com/icon/incognito)

**Comment by karlsnyder0** [comment]
Incognito looks like a vehicle.

**Comment by Templarian** [comment]
Our current incognito is more for Google Chrome. It's not really a Material Design representation.

**Comment by goyney** [comment]
It's not even the Chrome image...

![Screen Shot 2020-03-09 at 10 10 41 PM](https://user-images.githubusercontent.com/1015040/76272864-d21a4a00-6252-11ea-9879-f8a61f917c38.png)
![Screen Shot 2020-03-09 at 10 10 51 PM](https://user-images.githubusercontent.com/1015040/76272873-d8102b00-6252-11ea-915c-6f5a24e7a809.png)

**Comment by goyney** [comment]
I vote for updating ours to the latest Google icon and calling this issue good.

**Comment by nilsfast** [comment]
![image](https://user-images.githubusercontent.com/58486458/77183960-5da39e80-6acf-11ea-8190-e61f5a65afd6.png)

Here is the current version.

**Comment by PeterShaggyNoble** [comment]
The version @nilsfast posted above and a circled variant are both available in Material Icons Extended.

![incognito_circle](https://user-images.githubusercontent.com/15157491/77184555-e585aa80-6ac7-11ea-9b98-1cffd04a11b4.png)

**Comment by nilsfast** [comment]
And incognito-off?

**Comment by PeterShaggyNoble** [comment]
Missed that one, @nilsfast; looks like you edited it in after I read your comment. That one's not included in MIE, no.

**Comment by goyney** [comment]
`incognito` and `incognito-off` have been updated and the circle variants added.
