### ISSUE TITLE
Icons on cheatsheet & webfont don't match up.

### ISSUE THREAD

**Issue by pjmdesi** [Templarian/MaterialDesign#4965]
I'm a UI/UX developer and I'm trying to use mdi with my UI applications. I installed the Webfont on my machine and I am able to use macOS' Font Book to copy/paste icons into the document. But, given that there are so many, it's tough to find the one I need, and there's no searching in Font Book.

When I go to the Cheatsheet on the website, I can ⌘f to search, find the icon and click it to copy. Which is great. However, when I paste it into my document, _a completely different icon is rendered_.

For instance, the **mdi-logout** icon is listed as `F0343` in the Cheatsheet, but when I copy it from the Cheatsheet and paste into a text field, `F0343` is it ends up pasting **mdi-kettle-alert-outline**. I looked in Font Book and indeed `F0343` is **mdi-kettle-alert-outline**.

Another example is when I copy the **mdi-vector-square** (`F0001` in the Cheatsheet & `F001` in Font Book), it ends up pasting **mdi-slash-forward-box** (`F0FE0` in the Cheatsheet & `F0001` in Font Book).

Plus, the new icons (mdi-microsoft-word, mdi-size-xxxl, etc.) listed on the Cheatsheet don't seem to work at all (pasting nothing), and I can't find them in the, albeit huge, list in Font Book.

Maybe the Webfont is not updated? Maybe they are encoded differently? _Or maybe there's something I don't understand about how all this works._

I'd really like to be able to easily search, copy, and paste into apps since you can't CDN from Illustrator, Photoshop, Figma, Sketch, Invision Studio, etc.
Either way, an answer would be nice!

**Comment by goyney** [comment]
> I installed the Webfont on my machine.

It's a webfont, not a desktop font. You shouldn't be installing webfonts locally.

We just started offering a Desktop version of the font that is always up-to-date (it builds every time we publish a new icon) and it can be found here: https://github.com/Templarian/MaterialDesign-Font

Additionally, we just did a huge new, breaking release (5.0.45) which changed a lot of codepoints. You need to be using the 5.0.45 cheatsheet AND the latest TTF font for everything to work correctly.

**Comment by pjmdesi** [comment]
@goyney awesome! Thank you for clearing that up. It's working great!

I wish the website would say that somewhere, like maybe under the resources section of the download pop-up? Just a thought...

**Comment by Templarian** [comment]
That is brand new repo released with v5+. Docs will be coming shortly!

Really excited to finally get a Desktop Font into designers/print media hands. Something we've wanted to provide for a while.

**Comment by Templarian** [comment]
@pjmdesi You're like the first person to use it probably. Do let us know if we can make anything easier. It has a special cheatsheet generated just for the Desktop Font.

**Comment by pjmdesi** [comment]
@Templarian
Sorry for being so late with this response. The cheat sheet and desktop font work great! I use it pretty much every day.

The only suggestion I have is to have the same search option on the cheat sheet that's on https://materialdesignicons.com/. Specifically, the ability to search by tags/categories. For example, if I type "money" into the search bar, it finds, cash, cash-100, cash-multiple, currency-usd, and currency-usd-off.

Currently, I have to know the name of the icon ane ⌘f to find it easily. This isn't a huge issue as I can use the search on https://materialdesignicons.com/ to find the name if I don't already know it and then search for it on the cheat sheet, but it would be nice if I could do that all on 1 page.

Otherwise everyone is great :)
