### ISSUE TITLE
transport-layer-l4 transport-layer-l4-box

### ISSUE THREAD

**Issue by MaksUr** [Templarian/MaterialDesign#4966]
I need l4 icon.
Tags: **l4**, **protocol**, **[transport-layer](https://en.wikipedia.org/wiki/Transport_layer)**
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/26674247/76400586-5f1fe900-63a2-11ea-9592-8f874739bcfb.png)

![image](https://user-images.githubusercontent.com/26674247/76400666-7ced4e00-63a2-11ea-88e2-fd9c0d539a1f.png)

## Zip Download

[transport-layer-l4.zip](https://github.com/Templarian/MaterialDesign/files/4317145/transport-layer-l4.zip)

[transport-layer-l4-box.zip](https://github.com/Templarian/MaterialDesign/files/4317144/transport-layer-l4-box.zip)

**Comment by goyney** [comment]
We're not too keen on adding text-only icons anymore. This is also very niche. I vote no on this.
