### ISSUE TITLE
ip, ip-box, ip-box-outline

### ISSUE THREAD

**Issue by MaksUr** [Templarian/MaterialDesign#4967]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html) .

## Preview

![image](https://user-images.githubusercontent.com/26674247/76404779-df494d00-63a8-11ea-86d8-edb5ac64387b.png)

![image](https://user-images.githubusercontent.com/26674247/76404834-fb4cee80-63a8-11ea-8107-d18217b8b827.png)

**I'm not sure about outline version**

![image](https://user-images.githubusercontent.com/26674247/76404882-13247280-63a9-11ea-9ab1-3a513a4ae24e.png)

## Zip Download

[ip.zip](https://github.com/Templarian/MaterialDesign/files/4317459/ip.zip)
[ip-box.zip](https://github.com/Templarian/MaterialDesign/files/4317460/ip-box.zip)
[ip-box-outline.zip](https://github.com/Templarian/MaterialDesign/files/4317461/ip-box-outline.zip)

**Comment by goyney** [comment]
We're not too keen on adding text-only icons anymore. I vote no on this.

**Comment by Templarian** [comment]
Yeah, I would advise to use the more generic networking symbols for things like this.

**Comment by Templarian** [comment]
Awesome work following the issue template though and hope you submit other icons in the future. It's just that we don't really like adding text unless it's absolutely necessary.
