### ISSUE TITLE
Rename text-subject to text-long

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#4968]
Probably pretty low priority but to go along with our change to descriptive icon names I think this would be a good idea. We already have `text` and `text-short` so it would go along with that scheme.

[![](https://materialdesignicons.com/icon/text-subject)](https://materialdesignicons.com/icon/text-subject)

**Comment by goyney** [comment]
`text-subject` has been renamed `text-long`.
