### ISSUE TITLE
Sort icons mixed up

### ISSUE THREAD

**Issue by frozen-chameleon** [Templarian/MaterialDesign#4969]
It looks like with the changes to sort icons in version 5.0.45 (discussed in #4449) the sort-descending and sort-ascending icons got mixed up.

The current icon for sort-ascending
![sort-ascending](https://user-images.githubusercontent.com/52851698/76457866-d91f9480-63d9-11ea-89c0-4b7fac868406.png)
Following the arrow this icon goes from big value to small value which translates to descending order.

The current icon for sort-descending 
![sort-descending](https://user-images.githubusercontent.com/52851698/76457909-e76db080-63d9-11ea-9084-77cdef9df72a.png)
Following the arrow this icon goes from small value to big value which translates to ascending order.

**Comment by Templarian** [comment]
@goyney Okay, I'll take partial credit for not double checking this, but yeah. 🤦‍♂

**Comment by goyney** [comment]
All of our sort icons match the same style: arrow down is ascending, arrow up is descending. If we change anything, it would be flipping the lines to have the smaller one up top and the larger one down bottom.

**Comment by goyney** [comment]
This will require `sort` to be updated as well.

**Comment by goyney** [comment]
These are fixed and will go out in our next version. Thanks for reporting the issue.

[![sort](https://materialdesignicons.com/icon/sort)](https://materialdesignicons.com/icon/sort)
[![sort-ascending](https://materialdesignicons.com/icon/sort-ascending)](https://materialdesignicons.com/icon/sort-ascending)[![sort-descending](https://materialdesignicons.com/icon/sort-descending)](https://materialdesignicons.com/icon/sort-descending)
