### ISSUE TITLE
list-merge / list-split

### ISSUE THREAD

**Issue by s-ki** [Templarian/MaterialDesign#4970]
For a list containing entries which can each consist of one or more items, I use:
- list-merge to combine multiple selected single-item entries into one multi-item entry,
- list-split to separate the items of a multi-item entry into several single-item entries.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![list-merge](https://user-images.githubusercontent.com/62099917/76519219-dd42c500-6460-11ea-986e-696d587dc21c.png)
![list-split](https://user-images.githubusercontent.com/62099917/76519230-e3d13c80-6460-11ea-8d31-831cf7a87dfc.png)

## Zip Download

[list-merge-split.zip](https://github.com/Templarian/MaterialDesign/files/4323955/list-merge-split.zip)

**Comment by MrGrigri** [comment]
Thanks, @s-ki for your contribution! These are perfect and conceptualize the idea in a clean a straightforward way.

**Comment by Templarian** [comment]
Is `list-*` the right prefix for this? I'm not really against it, but wondering if there is a more correct or better name.

**Comment by s-ki** [comment]
You're right, list doesn't make much sense here.
Maybe items-merge/item(s?)-split, but that might also sound too specific.
Or something like group/ungroup or join/disjoin?

**Comment by Templarian** [comment]
`items-merge` / `item-split`... that seems weird. It's more of a list, so `group` doesn't really work. `set-split` / `set-merge` maybe? Since we use that prefix for our "SQL" join icons.

http://dev.materialdesignicons.com/contribute/icon-naming

**Comment by goyney** [comment]
[![set-split](https://materialdesignicons.com/icon/set-split)](https://materialdesignicons.com/icon/set-split)[![set-merge](https://materialdesignicons.com/icon/set-merge)](https://materialdesignicons.com/icon/set-merge)
