### ISSUE TITLE
Fridge 1 door

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#4974]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

Need an icon to distinguish between Freezer (2 doors in their variants) and a fridge (1 door)

Could discuss about naming but a simple variant for 1 door (and its off variant) would be great and much appreciated

## Examples

Include any example images so we know what the icon should look like.

**Comment by Xenomorph99** [comment]
Would these work? You could probably use "fridge-industrial" to represent a dedicated freezer.

![fridge-industrial](https://user-images.githubusercontent.com/1837101/90280088-91d57e00-de27-11ea-9584-cfa5b73313f2.png)
![fridge-industrial-alert](https://user-images.githubusercontent.com/1837101/90280077-8f732400-de27-11ea-8d2c-2aaf0ee00b75.png)
![fridge-industrial-off](https://user-images.githubusercontent.com/1837101/90280081-900bba80-de27-11ea-8ab3-53221364712f.png)

![fridge-industrial-outline](https://user-images.githubusercontent.com/1837101/90280085-913ce780-de27-11ea-99a6-121751141947.png)
![fridge-industrial-outline-alert](https://user-images.githubusercontent.com/1837101/90280082-90a45100-de27-11ea-8531-6effefcedb54.png)
![fridge-industrial-outline-off](https://user-images.githubusercontent.com/1837101/90280083-913ce780-de27-11ea-8d78-99edb5ffff8a.png)

I also created a side-by-side fridge variant.

![fridge-variant](https://user-images.githubusercontent.com/1837101/90280100-9306ab00-de27-11ea-8271-ab262c8959d4.png)
![fridge-variant-alert](https://user-images.githubusercontent.com/1837101/90280090-91d57e00-de27-11ea-878b-a9faabae8858.png)
![fridge-variant-off](https://user-images.githubusercontent.com/1837101/90280094-91d57e00-de27-11ea-9e41-b094e8a8baef.png)

![fridge-variant-outline](https://user-images.githubusercontent.com/1837101/90280099-926e1480-de27-11ea-9d73-121d5c2f5091.png)
![fridge-variant-outline-alert](https://user-images.githubusercontent.com/1837101/90280096-926e1480-de27-11ea-9285-7d8bc15ed6fc.png)
![fridge-variant-outline-off](https://user-images.githubusercontent.com/1837101/90280097-926e1480-de27-11ea-90b1-091e8b7a09c1.png)

[fridge-icons.zip](https://github.com/Templarian/MaterialDesign/files/5076331/fridge-icons.zip)

**Comment by goyney** [comment]
All added.
