### ISSUE TITLE
Icons missing

### ISSUE THREAD

**Issue by DreamsOfImran** [Templarian/MaterialDesign#4978]
medium, facebook-box, github-box icons all missing. Can I know where to find those icons?

**Comment by goyney** [comment]
They were removed. https://github.com/Templarian/MaterialDesign/issues/4901

**Comment by DreamsOfImran** [comment]
How can I access those icons if I want?

**Comment by Templarian** [comment]
@DreamsOfImran Starting with 5.0 we only publish the official vectors for these brands. You could use `v4.9.95` which has them. The SVG's are provided in the SVG distribution repo with the tag.

https://github.com/Templarian/MaterialDesign-SVG/tree/v4.9.95

For any brands removed we've suggested people use Simple Icons. As they do a better job than we could keeping them up to date and offer many more brands.

**Comment by PeterShaggyNoble** [comment]
> For any brands removed we've suggested people use Simple Icons. As they do a better job than we could keeping them up to date and offer many more brands.

Note, though, that variants like `facebook-box` and `github-box` are also beyond the scope of Simple Icons.
