### ISSUE TITLE
dropdownlist

### ISSUE THREAD

**Issue by Wallysburg** [Templarian/MaterialDesign#4979]
## Preview
![image](https://user-images.githubusercontent.com/9012326/76960310-8ff7a500-68f1-11ea-955b-1b8a75613762.png)

## Zip Download
[mdiDropDownList.svg.zip](https://github.com/Templarian/MaterialDesign/files/4348885/mdiDropDownList.svg.zip)

Shoutout to @goyney for helping me with this.

**Comment by goyney** [comment]
There was an idea to see what this looks like with only 2 options as well, so here that one is as well for consideration:

![image](https://user-images.githubusercontent.com/1015040/76961820-72780a80-68f4-11ea-8077-89e6fd4a029a.png)

[dropdown2.svg.zip](https://github.com/Templarian/MaterialDesign/files/4348976/dropdown2.svg.zip)

---

When we do add this, we'll assign it to the common contributor account. Once you hit 5 icons added, we'll get you your own contributor account and reassign it to you then.

**Comment by JamesCoyle** [comment]
Can we add variant which doesn't have the drop down section? Could make it match with the style of our textbox icon so we can add icons for the different types of form fields. Would be handy to have in a WYSIWYG form editor toolbar.

**Comment by goyney** [comment]
> Would be handy to have in a WYSIWYG form editor toolbar.

You mean like this?
![image](https://user-images.githubusercontent.com/1015040/76962592-e0710180-68f5-11ea-8ec7-461e11c639a4.png)

That's why it was created. 😄 

Looking at all those though, we have a difference between rounded corners and not. Wonder if we should change anything about either this or the text field icons. 🤔

**Comment by JamesCoyle** [comment]
Yeah like that lol. I think we could update textbox to be rounded when we rename them. The rest of our icons are rounded so it's weird having a sharp style icon.

**Comment by Templarian** [comment]
- `form-select`
- `form-dropdown`

Which name are we using? We should have one that is the full width if it's a `form-select`.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/77038881-c7faf880-6982-11ea-9a05-da49287a61ad.png)

**Comment by Templarian** [comment]
Added. I assigned both of these to @Wallysburg 

https://dev.materialdesignicons.com/history
