### ISSUE TITLE
Smoking pipe

### ISSUE THREAD

**Issue by michelle-arzul** [Templarian/MaterialDesign#4980]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To represent smoking (in addition to the existing cigarette and cigar) or as a nod to a certain character. Possible variants include designs used by Popeye, Captain Haddock, Sherlock Holmes, Gandalf, etc.

## Examples

https://www.google.com/search?q=smoking+pipe+icon&tbm=isch

**Comment by JapanYoshi** [comment]
So something like what's pictured in [The Treachery of Images](https://en.wikipedia.org/wiki/The_Treachery_of_Images)?

**Comment by michelle-arzul** [comment]
Ah yes, that would add another possible meaning of surrealism.

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/77722065-6862b400-7038-11ea-9f05-506f1f2aba1f.png)
![image](https://user-images.githubusercontent.com/8707990/77722081-7284b280-7038-11ea-9e7a-1c2018036ee7.png)
Here's my first attempt.

**Comment by Templarian** [comment]
The first one works, the lines make it harder to see at the smaller size.

**Comment by JapanYoshi** [comment]
Here's the path data:

    M 4,7 C 2.8920055,7 2,7.89201 2,9 v 4 c 0,2.20914 1.7908611,4 4,4 h 2 c 3,0 4.282875,-0.525059 7.113281,-3.355469 L 18.878906,9.8789062 C 19.441786,9.3160265 20.203962,9 21,9 h 1 V 7 h -1 c -1.325693,10e-6 -2.597745,0.5274336 -3.535156,1.4648438 L 13.697266,12.230469 C 13.004247,12.923128 12,13 11,13 H 10 V 9 C 10,7.89201 9.107994,7 8,7 Z

**Comment by Templarian** [comment]
Added. 😃 👍 

[![smoking-pipe](https://materialdesignicons.com/icon/smoking-pipe)](https://materialdesignicons.com/icon/smoking-pipe)

**Comment by michelle-arzul** [comment]
Awesome, thanks guys!

**Comment by goyney** [comment]
Where’s the smoke? The cigar and cigarette have smoke. This follow our pattern.

**Comment by Templarian** [comment]
Yeah, we can update it before the release. Wasn't sure if it would complicate it too much, but might work if done right.

**Comment by goyney** [comment]
This has been updated to include the smoke and to change the direction to match our cigarette and cigar icons. An off variant has also been added.
