### ISSUE TITLE
Drag handle alternative

### ISSUE THREAD

**Issue by Croutonix** [Templarian/MaterialDesign#4981]
As seen in Google Keep Notes. We already have a lot of drag icons, I just think they look better than the current ones with smaller dots.

![drag-vertical-alt](https://user-images.githubusercontent.com/18645219/76999994-f995a480-692d-11ea-8be6-dab2b2202ae3.png)

![drag-horizontal-alt](https://user-images.githubusercontent.com/18645219/77000005-fc909500-692d-11ea-85f8-dbc1717aa7e8.png)

These are just `dots-vertical` and `dots-horizontal` repeated twice.

[Download link](https://github.com/Templarian/MaterialDesign/files/4351018/drag-alt.zip)

**Comment by goyney** [comment]
I personally prefer our current ones. 🤔

**Comment by Templarian** [comment]
I'm not against adding a variant if they could work into a UX. Do agree the current ones look more correct for dragging.

**Comment by parloti** [comment]
I prefer this alternative:

[`Material cdkDragHandle`](https://stackblitz.com/angular/lmgyeavyyrle?file=src%2Fapp%2Fcdk-drag-drop-handle-example.html)

Can we have this?

**Comment by goyney** [comment]
> I prefer this alternative:
> 
> [`Material cdkDragHandle`](https://stackblitz.com/angular/lmgyeavyyrle?file=src%2Fapp%2Fcdk-drag-drop-handle-example.html)
> 
> Can we have this?

We already have `arrow-all` and `drag-variant`. I don't think we going to add yet another.

**Comment by Templarian** [comment]
The reason I'm leaning toward closing this is that if we add these we need to add drag separators / drag corner for this style also. Not sure if the circles make sense. Could get confused with menu circles.
