### ISSUE TITLE
People in queue/line

### ISSUE THREAD

**Issue by vegarda** [Templarian/MaterialDesign#4983]
Retry of this(?) https://github.com/Templarian/MaterialDesign/issues/1425

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

[icon] \<number>

Indicate how many people are waiting in queue simply with an icon and a number next to it

## Examples

I suggest_ 3 people so it fits in 24x24, something like  https://visualpharm.com/assets/560/Queue-595b40b75ba036ed117d83b3.svg

https://www.google.com/search?q=people+in+queue+icon

**Comment by Croutonix** [comment]
`account` repeated x3:
[![people-queue-1](https://user-images.githubusercontent.com/18645219/77344733-fb82ad80-6d09-11ea-863b-783a9014cd4d.png)](https://github.com/Templarian/MaterialDesign/files/4370953/queue1.zip)

Pushing vertical boundaries a little:
[![people-queue-2](https://user-images.githubusercontent.com/18645219/77344781-11906e00-6d0a-11ea-97fb-039e58e1dc34.png)](https://github.com/Templarian/MaterialDesign/files/4370958/queue2.zip)

Back peoples are scaled down:
[![people-queue-3](https://user-images.githubusercontent.com/18645219/77344805-1bb26c80-6d0a-11ea-9760-4ef9a8c7aa31.png)](https://github.com/Templarian/MaterialDesign/files/4370962/queue3.zip)

The last one looks best IMO, other looks like stacks of cardboard people. I used 1.5px clip for the head and 2px clip for the body as with other account icons.

**Comment by JapanYoshi** [comment]
Why not full pictograms side-by-side?

**Comment by Croutonix** [comment]
It wouldn't fit very well. First one barely fits already. And there's already `account-group` that's pretty much that.

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/77398450-462c2480-6df3-11ea-9da9-b294e454c747.png)
I tried a dense packing of a shrunk down version of Google's `human-male`, that fits in the horizontal rectangle area.

    M 5 4 C 3.8954305 4 3 4.8954305 3 6 C 3 7.1045695 3.8954305 8 5 8 C 6.1045695 8 7 7.1045695 7 6 C 7 4.8954305 6.1045695 4 5 4 z M 12 4 C 10.895431 4 10 4.8954305 10 6 C 10 7.1045695 10.895431 8 12 8 C 13.104569 8 14 7.1045695 14 6 C 14 4.8954305 13.104569 4 12 4 z M 19 4 C 17.895431 4 17 4.8954305 17 6 C 17 7.1045695 17.895431 8 19 8 C 20.104569 8 21 7.1045695 21 6 C 21 4.8954305 20.104569 4 19 4 z M 3.5 9 C 2.6693136 9 2 9.6693138 2 10.5 L 2 15 L 3 15 L 3 20 L 7 20 L 7 15 L 8 15 L 8 10.5 C 8 9.6693138 7.3306864 9 6.5 9 L 3.5 9 z M 10.5 9 C 9.6693137 9 9 9.6693138 9 10.5 L 9 15 L 10 15 L 10 20 L 14 20 L 14 15 L 15 15 L 15 10.5 C 15 9.6693138 14.330686 9 13.5 9 L 10.5 9 z M 17.5 9 C 16.669314 9 16 9.6693138 16 10.5 L 16 15 L 17 15 L 17 20 L 21 20 L 21 15 L 22 15 L 22 10.5 C 22 9.6693138 21.330686 9 20.5 9 L 17.5 9 z

**Comment by Templarian** [comment]
Maybe putting the first 2px down and the right 2px up? But yeah, I like using these over the account icon for lining up.

**Comment by goyney** [comment]
[![human-queue](https://materialdesignicons.com/icon/human-queue)](https://materialdesignicons.com/icon/human-queue)
