### ISSUE TITLE
birthday Icon

### ISSUE THREAD

**Issue by beigiz** [Templarian/MaterialDesign#4984]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Croutonix** [comment]
There are already a few icons that might work:
- [cake](https://materialdesignicons.com/icon/cake)
- [balloon](https://materialdesignicons.com/icon/balloon)
- [party-popper](https://materialdesignicons.com/icon/party-popper)

What icon did you have in mind?

**Comment by beigiz** [comment]
i needed exactly something like the Cake/Cake-Variant Icon
but this leads us to an issue and that would be your search and filters, it
needs more alias for each icon
these cake icon are definitely birthday cakes but the word "birthday" is
missing and if i search that nothings gonna be found

thank you for your fast response and your awesome work!

**Comment by beigiz** [comment]
i needed exactly something like the Cake/Cake-Variant Icon
but this leads us to an issue and that would be your search and filters, it
needs more aliases for each icon
these cake icon are definitely birthday cakes but the word "birthday" is
missing and if i search that nothings gonna be found

thank you for your fast response and your awesome work!

**Comment by Templarian** [comment]
@beigiz Aliases added. Let us know if any other aliases are missing when you're searching for icons.

New Issue -> Alias, and we'll get them added.
