### ISSUE TITLE
Religious dietary restrictions (Halal, Kosher)

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#4985]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/8707990/77401242-4b3fa280-6df8-11ea-9544-2b9a3cfe6acb.png)
![image](https://user-images.githubusercontent.com/8707990/77401544-d7ea6080-6df8-11ea-80ad-917654429414.png)

## Zip Download
Halal:

    m 7,5 0,10 c 0,1.11 -0.89,2 -2,2 H 4 C 3.4477153,17 3,16.552285 3,16 V 13 H 1 v 3 c 0,1.656854 1.3431458,3 3,3 h 1 c 2.2091391,0 4,-1.790861 4,-4 L 9,5 Z m 16,8.378906 -1.232422,-1.232422 C 21.033791,11.412697 20.03773,11 19,11 h -2 v 2 h 2 c 0.508066,0 0.99426,0.201291 1.353516,0.560547 L 20.699219,13.90625 19.5,14.597656 C 19.043739,14.860712 18.526661,15 18,15 h -1 c -0.564128,0 -1,-0.435872 -1,-1 V 6 H 14 V 9.8066406 L 13.376953,9.1152344 C 12.701661,8.3658511 11.594694,8 10.585938,8 H 10 v 2 h 0.585938 c 0.640672,0 1.254007,0.254007 1.707031,0.707031 L 14,12.414062 V 14 c 0,1.116412 -0.883588,2 -2,2 h -2 v 2 h 2 c 1.367133,0 2.504006,-0.699295 3.167969,-1.755859 C 15.628831,16.707959 16.248697,17 17,17 h 1 c 0.877633,0 1.739946,-0.23111 2.5,-0.669922 L 23,14.886719 Z

Kosher:

    M 1 7 L 1 9 L 3 9 C 3.5712883 9 4 9.42872 4 10 L 4 17 L 6 17 L 6 10 C 6 8.3553 4.6446997 7 3 7 L 1 7 z M 7 7 L 7 14 C 7 15.64469 8.3553001 17 10 17 L 14 17 C 15.6447 17 17 15.6447 17 14 L 17 7 L 15 7 L 15 14 C 15 14.57128 14.571288 15 14 15 L 10 15 C 9.4287109 15 9 14.57129 9 14 L 9 13 L 10 13 C 11.644703 13 13 11.6447 13 10 L 13 7 L 11 7 L 11 10 C 11 10.5713 10.571297 11 10 11 L 9 11 L 9 7 L 7 7 z M 18 7 L 18 9 L 20 9 C 20.571288 9 21 9.42872 21 10 L 21 14 C 21 14.57128 20.571288 15 20 15 L 18 15 L 18 17 L 20 17 C 21.6447 17 23 15.6447 23 14 L 23 10 C 23 8.3553 21.6447 7 20 7 L 18 7 z

**Comment by Templarian** [comment]
These are probably not going to work for localization reasons. Also trying to move away from text in any iconography. Nice job getting them to fit nicely in the small size though.

**Comment by JapanYoshi** [comment]
I mean, most Islamic stuff has *religious* objections against iconography, so there isn't much we can do with stuff like "halal", where the word written in Arabic acts as sort of an icon even for people who can't read Arabic. I *could* make an iconified kosher icon by combining a check mark with the Star of David, but that might end up looking like a jumble of lines.

**Comment by Templarian** [comment]
In these cases I would suggest the UX doesn't call for an icon and using text would make more sense.

**Comment by goyney** [comment]
[![food-halal](https://materialdesignicons.com/icon/food-halal)](https://materialdesignicons.com/icon/food-halal)[![food-kosher](https://materialdesignicons.com/icon/food-kosher)](https://materialdesignicons.com/icon/food-kosher)
