### ISSUE TITLE
earth-plus

### ISSUE THREAD

**Issue by fatihbalsoy** [Templarian/MaterialDesign#4986]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Usage
Creating a new scene or world in 3D computer graphics software.

## Preview
![earth-plus-contribution](https://user-images.githubusercontent.com/28816254/77508076-d9874900-6e37-11ea-9c74-31d4b4790076.png)

## Zip Download
[earth-plus.zip](https://github.com/Templarian/MaterialDesign/files/4379342/earth-plus.zip)

**Comment by Templarian** [comment]
- [x] `earth-plus`
- [x] `earth-minus`
- [x] `earth-remove`

Let me know when you've added 2 more icons for a contributor account (min 5, we'll count all 3 toward it).

**Comment by fatihbalsoy** [comment]
Thanks for applying the `-minus` and `-remove` modifiers to `earth`, I forgot to mention them.
I've created issue #4991 to apply these changes to `earth-box` for two-dimensional and voxel scenes in rendering software.
