### ISSUE TITLE
Variant of currency-sign

### ISSUE THREAD

**Issue by s-ki** [Templarian/MaterialDesign#4988]
I'm not sure if you have any use for this.
I needed a currency sign that would line up nicely with some other icons like coins-outline. The existing one looked a bit weird in combination with the others due to its thicker lines.
The new variant is basically a clone of coins-outline with the four lines added. The circle is smaller than the current one and the lines are as thin as those of most other icons.
I have no idea if it makes sense to replace the current icon, add this as a variant or just leave everything as is.

## Preview

![image](https://user-images.githubusercontent.com/62099917/77586009-b915c800-6ee5-11ea-9ebb-b698c28cfd05.png)

## Zip Download

[currency-sign-small.zip](https://github.com/Templarian/MaterialDesign/files/4383550/currency-sign-small.zip)

**Comment by Templarian** [comment]
We should replace ours. Never noticed the current one we have don't look right.

**Comment by goyney** [comment]
Updated.
