### ISSUE TITLE
Virus & Virus Outline Icons

### ISSUE THREAD

**Issue by Yanovsky** [Templarian/MaterialDesign#4989]
I've downloaded version 5.0.45 and I see some flaws:
1. I tryed to use "Virus" and "Virus Outline" icon which has added by Michael Irigoyen at Mar 5, 2020 but not found it in materialdesignicons.min.css and other files.
2. For some icons the charcode has changed and this is extremely inconvenient
for example:
in version 4.5.95 in file materialdesignicons.min.css
.mdi-settings-helper::before {
	content: "\FA6D"
}
in version 5.0.45 in file materialdesignicons.min.css
.mdi-settings-helper::before {
    content: "\F0A6E"
}

Thanks

**Comment by goyney** [comment]
1. The `virus(-outline)` icons were created and will be released in `v5.1.xx`, which hasn't gone out yet. The icons are available from our website as individual downloads as soon as they are added, but if you want to use them as part of one of our released packages, you will need to wait until it is actually released. Releases tend to happen about once every month (once we hit ~100 new icons).
2. Going from `v4` => `v5` is a MAJOR version increase. Major version changes typically happen when there are breaking changes. You should never blindly update a package to a new major version without [reading the change log](http://dev.materialdesignicons.com/changelog#version-5.0.45). Also see the pinned issue at the top of our issue list: https://github.com/Templarian/MaterialDesign/issues/4901.
