### ISSUE TITLE
Please provide icons for 3 major Russian social networks

### ISSUE THREAD

**Issue by afarber** [Templarian/MaterialDesign#499]
There are 3 major Russian social networks with millions of users:

* [vk.com](https://en.wikipedia.org/wiki/VK_%28social_networking_website%29) (aka "vkontakte" (fixed typo))
* [ok.ru](https://en.wikipedia.org/wiki/Odnoklassniki) (aka "odnoklassniki")
* [mail.ru](https://ru.wikipedia.org/wiki/%D0%9C%D0%BE%D0%B9_%D0%BC%D0%B8%D1%80@Mail.Ru) (aka "moj mir")

I have attached their current logos (all taken from the official iPhone apps) - 

it would be great to have them as material design icons

Thank you

![mail_ru](https://cloud.githubusercontent.com/assets/1884458/8672732/79b13148-2a31-11e5-9cce-db062f06e950.png)
![odnoklassniki](https://cloud.githubusercontent.com/assets/1884458/8672731/79a7d9c2-2a31-11e5-9a61-0a8d9f92a537.png)
![vk](https://cloud.githubusercontent.com/assets/1884458/8672733/79b2d250-2a31-11e5-8e20-e51325b501c7.png)

**Comment by Templarian** [comment]
VK already [exists](https://materialdesignicons.com/icon/vk), but I'll be sure to add the other two.

**Comment by Templarian** [comment]
I'll add an alias to `vk` also for `vkontake` to make searching easier.

**Comment by afarber** [comment]
Oh great, thank you!

**Comment by CoDEmanX** [comment]
@Templarian: you got a typo there, missing `t` in `vkontakte`

**Comment by Templarian** [comment]
@CoDEmanX Thanks, would have never seen that. Not familiar with any of these services.

**Comment by CoDEmanX** [comment]
Me neither, but it's written like the German `Kontakte` - which happens to be my native language ;-)

**Comment by afarber** [comment]
Yes "vkontakte" would be correct (my mother tongue is Russian and I live in Germany :)

**Comment by Templarian** [comment]
https://materialdesignicons.com/odnoklassniki
`vkontakte` alias for `vk` added
https://materialdesignicons.com/mail-ru (added official logo).

**Comment by Templarian** [comment]
`ok-ru` alias added also for `odnoklassniki`.
