### ISSUE TITLE
earth-box-(minus | plus | remove)

### ISSUE THREAD

**Issue by fatihbalsoy** [Templarian/MaterialDesign#4991]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Usage
Creating and removing a two-dimensional scene or voxel world in 3D computer graphics software.
Same as my other issue #4986 for `earth`, but applied to `earth-box`.

## Aliases
`earth-box`:`voxel`
All `cube` icons:`voxel`

## Preview

![earth-box-minus](https://user-images.githubusercontent.com/28816254/77705388-8cb58680-6f8d-11ea-981d-f53574427bfd.png)
![earth-box-plus](https://user-images.githubusercontent.com/28816254/77705393-8f17e080-6f8d-11ea-851e-b93d6e2ad661.png)
![earth-box-remove](https://user-images.githubusercontent.com/28816254/77705396-90490d80-6f8d-11ea-9075-3792dca01766.png)

## Zip Download

[earth-box-plus-minus-remove.zip](https://github.com/Templarian/MaterialDesign/files/4390492/earth-box-plus-minus-remove.zip)

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/history

All added/reassigned. ✅

**Comment by fatihbalsoy** [comment]
Awesome, thanks!
When can I expect to get a contributors account on the website?

**Comment by Templarian** [comment]
@fatihbalsoy I can do this tonight... technically I need to connect this page to an endpoint: https://github.com/Templarian/MaterialDesign-Site/blob/master/src/app/contributorsPage/contributorsPage.component.html

Just haven't gotten around to it.
