### ISSUE TITLE
Paper plane

### ISSUE THREAD

**Issue by GrassiSupport** [Templarian/MaterialDesign#4992]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As an alternative of send icon

## Examples

[Font awesome paper-plane icon](https://fontawesome.com/icons/paper-plane?style=solid)

**Comment by goyney** [comment]
Already exists:
[![send](https://materialdesignicons.com/icon/send)](https://materialdesignicons.com/icon/send)[![send-outline](https://materialdesignicons.com/icon/send-outline)](https://materialdesignicons.com/icon/send-outline)
