### ISSUE TITLE
Turbocharger

### ISSUE THREAD

**Issue by mattcorner** [Templarian/MaterialDesign#4993]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
To distinguish between car parts.

## Examples
https://d2gg9evh47fn9z.cloudfront.net/800px_COLOURBOX38034373.jpg
https://www.iconfinder.com/icons/3112721/automobile_car_part_turbo_turbocharger_icon

**Comment by goyney** [comment]
Already exists:
[![car-turbocharger](https://materialdesignicons.com/icon/car-turbocharger)](https://materialdesignicons.com/icon/car-turbocharger)

**Comment by mattcorner** [comment]
Apologies, not sure how i missed that.
