### ISSUE TITLE
Gas Station Off

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#4997]
I created this icon because I needed it for a small project. It relates to [gas-station](https://materialdesignicons.com/icon/gas-station).

![gas-station-off](https://user-images.githubusercontent.com/1837101/77858383-73e0e700-71c0-11ea-8c3d-49ee14c87413.png)

[gas-station-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/4399626/gas-station-off.svg.zip)

**Comment by Templarian** [comment]
Added (assigned the `-outline` to you also).
