### ISSUE TITLE
Google Material Icon - storage

### ISSUE THREAD

**Issue by OldShaterhan** [Templarian/MaterialDesign#4999]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Missing `storage` icon from the Google Material Design Icons https://material.io/resources/icons/?style=baseline 
It is possible that only some alias is missing, but possesing this icon within MDI would be great.

## Examples

It is visible on: https://fonts.gstatic.com/s/i/materialicons/storage/v4/24px.svg?download=false

**Comment by Templarian** [comment]
We recommend using `server` or `database` instead.

The `storage` was not added intentionally left out as there are more accurate icons to represent this.

**Comment by Templarian** [comment]
Almost forgot there is a `nas` icon which is also a good solution for `storage`. I'll add an alias to `server` and `database`.

**Comment by OldShaterhan** [comment]
Okay, thanks for clarification ;) I didn't find anything and I thought it was just forgotten :)
