### ISSUE TITLE
Snow icon

### ISSUE THREAD

**Issue by gervye** [Templarian/MaterialDesign#500]
Should be nice to have a snow (or ice) icon.
![snow](https://cloud.githubusercontent.com/assets/13333322/8674433/34d38d16-2a3e-11e5-9d59-07d3809be0b4.png)

**Comment by CoDEmanX** [comment]
Nice addition to the weather-related icons!

**Comment by CoDEmanX** [comment]
Frost warning:
![frost-warning](https://cloud.githubusercontent.com/assets/1309249/9088495/85464064-3b90-11e5-8d73-9e755a285866.png)

**Comment by PeterShaggyNoble** [comment]
![](https://materialdesignicons.com/icon/snowflake)
