### ISSUE TITLE
Axis info/help

### ISSUE THREAD

**Issue by mattcorner** [Templarian/MaterialDesign#5000]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Would use as an icon button to display a dialog explaining coordinate systems when uploading data.

## Examples
Proposing the current axis-arrow icon, with the i found in car-info in the top right corner?

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/77981802-72064900-72d0-11ea-9c42-dccb6368d7db.png)

**Comment by Templarian** [comment]
@mattcorner ^ Is that what you meant?

**Comment by mattcorner** [comment]
Yep, looks good to me

**Comment by mattcorner** [comment]
> ![image](https://user-images.githubusercontent.com/338885/77981802-72064900-72d0-11ea-9c42-dccb6368d7db.png)
> 

Would you be able to share the svg path so that I can use in a project until its officially released?

**Comment by Templarian** [comment]
@mattcorner Added it, should be on the website once the cache clear ~5 mins.

**Comment by Templarian** [comment]
@goyney I was 50/50 on this one also. But axis information icon makes sense to have and I couldn't think of another way to design it. We can always revise this later.
