### ISSUE TITLE
Updated to web font broke all icons on my website

### ISSUE THREAD

**Issue by swonline** [Templarian/MaterialDesign#5002]
I think your most recent update broke all the icons on my webflow website. I download the font files and upload them to my webflow project. I then use the cheat sheet to copy and paste the icons to the site. After the update, I could no longer add new icons. But when I uploaded the new font files, then all my existing icons are broken. Not sure there's much you can do about it now but just wanted to make you aware. I now need to go through my entire site and copy across all the new icons.

**Comment by Templarian** [comment]
You needed to use the CSS class names for use on the web. Codepoints should not be used even with v5.0+ on the web. Note that starting with v5 codepoints were all moved to the public unicode area and will be unchanged between version releases. Still don't actually use them, use the CSS file to map names to codepoints.

#4901 Has some ideas for how to convert 4.0 to 5.0 codepoints. There is a python script someone wrote.
