### ISSUE TITLE
Request: compare-arrows from Google

### ISSUE THREAD

**Issue by OldShaterhan** [Templarian/MaterialDesign#5003]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Similarly to `swap-horizontal` `compare-arrows` can be used to show compare/data exchange.

## Examples

Include any example images so we know what the icon should look like.

https://fonts.gstatic.com/s/i/materialicons/compare_arrows/v6/24px.svg?download=false

I was looking through the library and I didn't find any icon that corresponds to that one. It is possible I just didn't notice it, in that case I'm requesting for alias for that icon.

**Comment by goyney** [comment]
[![compare-horizontal](https://materialdesignicons.com/icon/compare-horizontal)](https://materialdesignicons.com/icon/compare-horizontal)[![compare-vertical](https://materialdesignicons.com/icon/compare-vertical)](https://materialdesignicons.com/icon/compare-vertical)
