### ISSUE TITLE
power-plug-outline(-off)

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#5004]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same usage than power-plug(-off)

## Examples

Like power-plug(-off), but as outline. Thank you for all these great icons!

**Comment by goyney** [comment]
[![power-plug-outline](https://materialdesignicons.com/icon/power-plug-outline)](https://materialdesignicons.com/icon/power-plug-outline)[![power-plug-off-outline](https://materialdesignicons.com/icon/power-plug-off-outline)](https://materialdesignicons.com/icon/power-plug-off-outline)
