### ISSUE TITLE
account-lock-open

### ISSUE THREAD

**Issue by laurent-brisbois** [Templarian/MaterialDesign#5005]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Since there is an `account-lock` icon, it would be great to have an `account-lock-open`. Which would be the same but with the lock opened.

## Examples

Something like this, but with the lock opened the other side to keep MD lock usual side.

![image](https://user-images.githubusercontent.com/48165976/78024293-68282880-7358-11ea-9094-45e1cda05244.png)

I mean a combination of 
![image](https://user-images.githubusercontent.com/48165976/78024450-afaeb480-7358-11ea-84e5-2a1472f46132.png)
and 
![image](https://user-images.githubusercontent.com/48165976/78024598-ebe21500-7358-11ea-83a8-ff44193ca47e.png)

**Comment by goyney** [comment]
With the size of the lock in `account-lock`, I don't think this is going to be discernible.

**Comment by laurent-brisbois** [comment]
Oh I see. I thought it was possible since I saw it exists in fontawesome (see [here](https://fontawesome.com/icons/user-unlock?style=solid))

**Comment by goyney** [comment]
Font Awesome doesn't follow Material guidelines since they have their own design system. Our `account-lock` uses our standard lock modifier. Making the lock look open at that size just doesn't work. 🤔

**Comment by goyney** [comment]
[![account-lock-open](https://materialdesignicons.com/icon/account-lock-open)](https://materialdesignicons.com/icon/account-lock-open)[![account-lock-open-outline](https://materialdesignicons.com/icon/account-lock-open-outline)](https://materialdesignicons.com/icon/account-lock-open-outline)

`account-lock` and `account-lock-outline` were also updated so the styles match.
