### ISSUE TITLE
Create all icon variants, not just the baseline and outlined.

### ISSUE THREAD

**Issue by icarapovic** [Templarian/MaterialDesign#5006]
Material design icons page provides also dual-tone, sharp and rounded icons. It would be nice for all icons to add at least the dual tone variant as sharp and rounded are very similar and the differences are not always really visible.

**Comment by Templarian** [comment]
Thanks for the suggestion. At this time these are outside of the scope of this project's goals.

We will begin working on https://github.com/Templarian/MaterialDesignLight shortly which we feel is more useful for the community.

After Material Design Icons Light is up to a more usable quantity, we may refocus efforts.
