### ISSUE TITLE
Seringe

### ISSUE THREAD

**Issue by zoombie3000** [Templarian/MaterialDesign#5009]
I have:

- [ X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Creating a medical app, so I would be using the icons as ticket types. I can use medical-bag for on site consultations and pills for a standard take medication, but the seringe would be for vaccines.

## Examples

https://www.cleanpng.com/png-logo-product-brand-clip-art-font-medical-seringe-s-6907904/

**Comment by Templarian** [comment]
It's called `needle` in the pack. It already has an alias for `syringe`.

Think you might have it misspelled. 😉
