### ISSUE TITLE
empty

### ISSUE THREAD

**Issue by jaybowles** [Templarian/MaterialDesign#501]

**Comment by Templarian** [comment]
@jaybowles Do you mean a blank icon like #352 or something else?

An example might help.

**Comment by jaybowles** [comment]
Ah not exactly like that, no.

I'm looking for a generic icon which can be used in a view that has no data. "Looks like you haven't added any members yet". I don't know - maybe the right thing is to show a greyed-out Members icon - the Material group icon for example. But I feel like there's room for a generic symbol to say "There's nothing here yet". An empty bucket perhaps?

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/delete-variant Like this but empty?

**Comment by CoDEmanX** [comment]
Maybe a sad smiley? A question mark? [This](http://www.google.com/design/icons/#ic_filter_3) with a zero?

Maybe something context-dependent, like [cart-outline](https://materialdesignicons.com/icon/cart-outline) if it's an empty cart.

**Comment by CoDEmanX** [comment]
Also found these on the web:
![Imgur](http://i.imgur.com/JbQacHp.png?2)
![Imgur](http://i.imgur.com/CkI6CqJ.png?1)

**Comment by jaybowles** [comment]
All great suggestions, thanks.

I took a look at them all and I guess the conclusion I've come to is that
your idea of context dependent icons is the best. For example, when we're
displaying a view of users, I'll gray out our users icon to indicate
emptiness.

Perhaps nobody's requested this before because that's the conclusion others
have come to. Thanks again for your help!

**Comment by CoDEmanX** [comment]
You probably want to read this:
https://www.google.com/design/spec/patterns/empty-states.html#

**Comment by jaybowles** [comment]
Oh nice, great share!

**Comment by Templarian** [comment]
I'm going to close this issue out as that link is probably the right UX solution.
