### ISSUE TITLE
Google—Visibility Icons

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5012]
Google Updates

It looks like they changed the verbage from "eye" to "visability". Not sure if we change our library as well or just add in new "visibility" icons. I love the updated outline versions!

[visibility](https://material.io/resources/icons/?search=view&icon=visibility&style=baseline)
[visibility-off](https://material.io/resources/icons/?search=view&icon=visibility_off&style=baseline)
[visibility-outline](https://material.io/resources/icons/?search=view&icon=visibility&style=outline)
[visibility-off-outline](https://material.io/resources/icons/?search=view&icon=visibility_off&style=outline)

**Comment by Templarian** [comment]
Nah, ours always uses the noun name. Looks like the icons are still the same.

**Comment by Xenomorph99** [comment]
@Templarian the outline versions are different - Google has an inner circle outline for the pupil ours just have a solid inner circles for the pupils - the outline pupil looks way better.

**Comment by Templarian** [comment]
Oh, didn't see that. Reopening, not sure, but I think we decided not to replace this at one point.

**Comment by tgrelka** [comment]
Add them in as `-variant`? I much prefer the look of the new ones!

**Comment by goyney** [comment]
We did decide not to update these and I stand behind that decision.
