### ISSUE TITLE
Google—View Outline Icons

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5013]
**Google Additions**

MDI has the [view-dashboard](https://materialdesignicons.com/icon/view-dashboard) and [view-dashboard-outline](https://materialdesignicons.com/icon/view-dashboard-outline) icons which are similar to these, but it would be awesome to add these two new Google icons as well:

- [view-qulit](https://material.io/resources/icons/?search=view&icon=view_quilt&style=baseline)
- [view-quilt-outline](https://material.io/resources/icons/?search=view&icon=view_quilt&style=outline)

Also, let's add the following view outline icons because we have their corresponding filled icons already in MDI:

- [view-calendar-outline](https://material.io/resources/icons/?search=view&icon=calendar_view_day&style=outline)
- [view-array-outline](https://material.io/resources/icons/?search=view&icon=view_array&style=outline)
- [view-carousel-outline](https://material.io/resources/icons/?search=view&icon=view_carousel&style=outline)
- [view-column-outline](https://material.io/resources/icons/?search=view&icon=view_column&style=outline)
- [view-day-outline](https://material.io/resources/icons/?search=view&icon=view_day&style=outline)
- [view-list-outline](https://material.io/resources/icons/?search=view&icon=view_list&style=outline)
- [view-module-outline](https://material.io/resources/icons/?search=view&icon=view_module&style=outline)
- [view-stream-outline](https://material.io/resources/icons/?search=view&icon=view_stream&style=outline)
- [view-week-outline](https://material.io/resources/icons/?search=view&icon=view_week&style=outline)
- [view-comfy-outline](https://material.io/resources/icons/?search=view&icon=view_comfy&style=outline)

We don't need to add these view outline icons to MDI, because we already have the outline versions and they match Google:

MDI: [view-agenda-outline](https://materialdesignicons.com/icon/view-agenda-outline)
Google: [view-agenda-outline](https://material.io/resources/icons/?search=view&icon=view_agenda&style=outline)

MDI: [view-compact-outline](https://materialdesignicons.com/icon/view-compact-outline)
Google: [view-compact-outline](https://material.io/resources/icons/?search=view&icon=view_compact&style=outline)

**Comment by goyney** [comment]
All added.
