### ISSUE TITLE
chat plus

### ISSUE THREAD

**Issue by secmin** [Templarian/MaterialDesign#5014]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

Can be used to add or create a new chat.
There are already message-plus-outline and comment-plus-outline, but they are not chat icons, so I will request them.

## Examples

Include any example images so we know what the icon should look like.

I don't need the dots in the icon.
![SnapCrab_NoName_2020-4-4_15-22-15_No-00](https://user-images.githubusercontent.com/56533444/78420350-329d7b00-7689-11ea-9d87-1a334d4868c4.png)

**Comment by Templarian** [comment]
These 6 were added. You can see them on the history page.

https://dev.materialdesignicons.com/history
