### ISSUE TITLE
Air dehumidifier

### ISSUE THREAD

**Issue by maucollu** [Templarian/MaterialDesign#5015]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Would be good to have an air dehumidifier icon, similar to the air-humidifier one

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@maucollu Do you have any examples of what this might look like? You can paste images inline. Also please use the templates when creating issues. I edited the issue template into your original comment.

**Comment by Nanianmichaels** [comment]
Can I suggest the current humidifier icon, but with a crossed water droplet?

**Comment by goyney** [comment]
Just added `air-humidifier-off`, will that work for your use case?
[![air-humidifier-off](https://materialdesignicons.com/icon/air-humidifier-off)](https://materialdesignicons.com/icon/air-humidifier-off)

**Comment by maucollu** [comment]
Thanks a lot!
