### ISSUE TITLE
YouTube video library

### ISSUE THREAD

**Issue by damonleelcx** [Templarian/MaterialDesign#5016]
![_20200404_122926](https://user-images.githubusercontent.com/25017609/78456142-fa3d7300-766f-11ea-9e6c-7f472e08fda3.JPG)

I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
`play-box-outline`

**Comment by damonleelcx** [comment]
Play box outline is not what I requested.

![_20200404_123829](https://user-images.githubusercontent.com/25017609/78456367-3a512580-7671-11ea-8f6f-8d187f2fa333.JPG)

**Comment by Templarian** [comment]
@damonleelcx oops, `play-box-multiple` copied the wrong one. 😉

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/play-box-multiple)](https://materialdesignicons.com/icon/play-box-multiple)
