### ISSUE TITLE
elevator-off / door-open-off

### ISSUE THREAD

**Issue by akloeckner** [Templarian/MaterialDesign#5017]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
I intend to show the user, whether an elevator is in service or whether it is currently broken. So, I'd be glad to see something like no-meeting-room, just for elevators.

As to “a few near identical“ icons: it would be great to have this no-* also for the three escalator variants.

## Examples

see e.g. icon elevator and no-meeting-room

**Comment by Templarian** [comment]
Since our set uses nouns for the naming I've updated the title to make it more clear.

- [ ] `elevator-off`
- [ ] `elevator-up-off`
- [ ] `elevator-down-off`
- [ ] `door-open-off` (no room assigned, or something to that nature)

**Comment by akloeckner** [comment]
Alright. Thanks. There is a no-meeting-room already. So, probably that should be changed then? But that would be another issue...

**Comment by goyney** [comment]
The only one this makes sense for is `elevator-passenger`. I've added the outline of that, plus these two:
[![elevator-passenger-off](https://materialdesignicons.com/icon/elevator-passenger-off)](https://materialdesignicons.com/icon/elevator-passenger-off)[![elevator-passenger-off-outline](https://materialdesignicons.com/icon/elevator-passenger-off-outline)](https://materialdesignicons.com/icon/elevator-passenger-off-outline)

We don't include Google's `meeting-room` in our set at this time and `door-off` does not work.
