### ISSUE TITLE
Add reaction | emoticon-happy-plus-outline

### ISSUE THREAD

**Issue by davegomez** [Templarian/MaterialDesign#5018]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

[Manyverse](https://www.manyver.se/) is a social network off the grid for mobile, using [Scuttlebutt](https://scuttlebutt.nz/) as a communication protocol to provide an off the grid experience focused on privacy and data ownership.

Manyverse uses the Material Design Icons set to build its UI and our next release will introduce a new **Emoji Reactions** and we are exploring some improvements for future releases as you can see in [this issue](https://gitlab.com/staltz/manyverse/-/issues/838).

An important part of this improvement would be to have a "*add reaction*" icon, which we think could be a smiling face with a plus icon, but this is not available yet in the icon set.

I created the SVG file but I couldn't make it with just one `path` so I won't use the *Contribute an Icon* template. But here is the zip file with the SVG icon in case you want to take a look.

[emoticon-happy-plus-outline.zip](https://github.com/Templarian/MaterialDesign/files/4432906/emoticon-happy-plus-outline.zip)

## Examples

This is my idea of how it is supposed to look like:

![emoticon-happy-plus-outline](https://user-images.githubusercontent.com/282903/78466203-8ed5be80-76cc-11ea-9554-adba03e1df7a.png)

**Comment by Templarian** [comment]
Trying to think how we can handle this for the solid icon without making it looking weird. 🤔

**Comment by davegomez** [comment]
I thought about it too, and the only idea I could come up with was to "carving" the shape into the face as it is in `emoticon-kiss` and `emotion-cry,` but it would require to put the plus sign even more into the face to make it recognizable.

**Comment by jhil** [comment]
A couple other options! Made this for myself in #5257, but then saw this afterwards. 

![image](https://user-images.githubusercontent.com/2228347/85379959-33f47c00-b4f1-11ea-9263-9e253111353a.png)
![image](https://user-images.githubusercontent.com/2228347/85379965-36ef6c80-b4f1-11ea-8f3e-ab15c3450abc.png)

**Comment by goyney** [comment]
We're going to reject this because modifiers on emojis just doesn't work. Emojis are already complex icons and are difficult to represent monotone. Even with the `plus`, we cannot work it into both the filled and outlined versions. Additionally, this would open a slippery slope to add modifiers to all emojis, some of which just won't work at all. Thanks for the suggestion!
