### ISSUE TITLE
microwave-off

### ISSUE THREAD

**Issue by Ysbrand** [Templarian/MaterialDesign#5019]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There are a few icons for "appliance"-off, but not for a microwave

## Examples

Include any example images so we know what the icon should look like.
Examples  fridge-off, dishwasher-off etc
![dishwasher-off](https://user-images.githubusercontent.com/16001552/78469711-f408ce80-7723-11ea-9583-85696c6d5c03.png)

**Comment by goyney** [comment]
[![microwave-off](https://materialdesignicons.com/icon/microwave-off)](https://materialdesignicons.com/icon/microwave-off)
