### ISSUE TITLE
WakeLock Icon

### ISSUE THREAD

**Issue by royale1223** [Templarian/MaterialDesign#502]
I have no idea how this would look. Anyone?

https://developer.android.com/training/scheduling/wakelock.html

**Comment by CoDEmanX** [comment]
Maybe this?
![Imgur](http://i.imgur.com/jKbfFWG.png?1)

Or a literal no-sleep: ![sleep-off](https://cloud.githubusercontent.com/assets/1309249/8715096/36b3f090-2b7d-11e5-8d4e-9ef0ec7173a6.png) based on snooze icon from Google Clock,
or mirrored zzZ :![sleep-off-variant](https://cloud.githubusercontent.com/assets/1309249/8715128/8bd98990-2b7d-11e5-9e85-73c55f5a1c81.png)

**Comment by CoDEmanX** [comment]
@royale1223: is the sleep-off icon acceptable for your request?

**Comment by royale1223** [comment]
I think the owl icon is good. The mirrored zzz is also good. BTW I'm
currently using the eye icon. It does okay. But wouldn't hurt to have a
better icon.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/sleep-off

Uploaded to my icon earlier. Unless someone wants to add an owl.

**Comment by CoDEmanX** [comment]
@Templarian: I think `sleep-off` can be improved by removing 3 points to get rid of the tiny notch:
![sleep-off](https://cloud.githubusercontent.com/assets/1309249/9005092/8d7694fa-377b-11e5-813a-c64286166948.png)

![sleep-off-variant](https://cloud.githubusercontent.com/assets/1309249/9005185/5a8458ce-377c-11e5-95db-f0bab3e4792e.png)
before
![sleep-off-fix](https://cloud.githubusercontent.com/assets/1309249/9005138/f07586ba-377b-11e5-8512-c6e741e31c4e.png) after

https://www.dropbox.com/s/5tb9ocfk91llev4/sleep-off-fix.svg?dl=0

**Comment by CoDEmanX** [comment]
And here's an owl:
![owl](https://cloud.githubusercontent.com/assets/1309249/9007627/64ba0214-3793-11e5-9b4a-16e70d1cff64.png) https://www.dropbox.com/s/gq1s8yh1xi26stb/owl.svg?dl=0

1px border margin because the eyes would had been too small.

**Comment by Templarian** [comment]
@CoDEmanX Good catch. Eventually I want to put in a point viewer (I have code that counts point data), but a way to flag high point icons and gives a view like the compare view, but circles all the points in the icon.

This is extremely useful for some icons that may have overlapping points at corners.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/owl

Fixed the `sleep-off` icon also.
