### ISSUE TITLE
adding key-broken icon

### ISSUE THREAD

**Issue by tribis** [Templarian/MaterialDesign#5020]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The user has uploaded an encryption key that either is broken or in an unsupported format, or the key has become obsolete. The user needs to create a new one and upload again.

## Examples

![billede](https://user-images.githubusercontent.com/54670/78471486-ee19ea00-7731-11ea-97c1-1f228349843c.png)

It's just an idea to comply with the issue format here. I'm not a designer ;-)

**Comment by JapanYoshi** [comment]
The cracking would be difficult to show in a 24×24dp grid. Does anyone else have an idea on how to iconify this?

**Comment by Templarian** [comment]
A `key-alert` might not work for this use case. Still think we should have `key-alert` though.

Yeah, the key snapped details doesn't work.

**Comment by tribis** [comment]
for the crack, what about using something like in the heart-flash or heart-pulse?

**Comment by goyney** [comment]
A broken key isn't going to happen, but here's an option for the alert variants.

![image](https://user-images.githubusercontent.com/1015040/134242631-ff42830f-a2de-4bbe-a3af-fca33324f4aa.png)![image](https://user-images.githubusercontent.com/1015040/134242662-4a99dec2-7ca3-4b9e-9e2c-cd5d361a4e82.png)
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7206052/Archive.zip)

**Comment by goyney** [comment]
[![key-alert](https://materialdesignicons.com/icon/key-alert)](https://materialdesignicons.com/icon/key-alert)[![key-alert-outline](https://materialdesignicons.com/icon/key-alert-outline)](https://materialdesignicons.com/icon/key-alert-outline)
