### ISSUE TITLE
horse

### ISSUE THREAD

**Issue by xabi62** [Templarian/MaterialDesign#5021]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to create views to watch the cameras of the stable and what could be better than an icon of a horse for these views

## Examples

<img src="https://thumbs.dreamstime.com/z/web-139990293.jpg" height="400" width="400">

**Comment by goyney** [comment]
Duplicate of #174. Please search, like you claimed to have done.

**Comment by xabi62** [comment]
I was thinking more about an entire horse, rather than just the head

**Comment by goyney** [comment]
Nothing about that request defines it to be a horse head. It asks for a horse. If you have specific wishes around that icon being added, you may comment in the single issue dealing with the horse. We don't need multiple issues for the same thing.
