### ISSUE TITLE
closed-caption-off

### ISSUE THREAD

**Issue by mtermoul** [Templarian/MaterialDesign#5023]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I will use the closed-caption-off icons along with closed-caption icon on an application to manage TV application settings to turn closed caption on and off

## Examples

It should look like closed-caption icon with the back slash indicating the the off status.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/79709461-cecda180-8287-11ea-966e-e0a677142e92.png)

This is difficult since it makes the icon completely unreadable.

**Comment by Xenomorph99** [comment]
I've been using Google Meet for work and just realized they're using [closed-caption](https://materialdesignicons.com/icon/closed-caption) for the "on" state and [closed-caption-outline](https://materialdesignicons.com/icon/closed-caption-outline) for the "off" state with a label and color change.

Screenshots:
<img width="144" alt="turn-on" src="https://user-images.githubusercontent.com/1837101/96622382-18df2080-12c7-11eb-85fa-1e986e020b38.png">
<img width="144" alt="turn-off" src="https://user-images.githubusercontent.com/1837101/96622384-1977b700-12c7-11eb-9594-af6f6faf8e3d.png">

I agree, while it's simple for us to add the slash to our icons, it does make this one illegible. We could probably go ahead and close this issue.
