### ISSUE TITLE
folder-multiple-plus

### ISSUE THREAD

**Issue by arunsundaramco** [Templarian/MaterialDesign#5024]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have a container that holds multiple folders. And mdi-folder-multiple is a very representative icon for it. My workflow also involves "folder addition" as an action. I believe a mdi-folder-multiple-plus icon would be an awesome addition.

## Examples
This could be based off of mdi-folder-multiple icon

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/80825276-e44e9f80-8b94-11ea-84fe-cfc9e5fedfc2.png)
[folder-multiple-plus.svg](https://github.com/terreng/samples/blob/master/folder-multiple-plus.svg)

![image](https://user-images.githubusercontent.com/11605395/80825366-119b4d80-8b95-11ea-8fd6-a5549c1e5ea2.png)
[folder-multiple-plus-outline.svg](https://github.com/terreng/samples/blob/master/folder-multiple-plus-outline.svg)

**Comment by goyney** [comment]
[![folder-multiple-plus](https://materialdesignicons.com/icon/folder-multiple-plus)](https://materialdesignicons.com/icon/folder-multiple-plus)[![folder-multiple-plus-outline](https://materialdesignicons.com/icon/folder-multiple-plus-outline)](https://materialdesignicons.com/icon/folder-multiple-plus-outline)
