### ISSUE TITLE
mdi-emulationstation

### ISSUE THREAD

**Issue by Asthonishia** [Templarian/MaterialDesign#5025]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Menus, dashboards...

## Examples

https://pic.clubic.com/v1/images/1505453/raw

SVG exemple by me : https://drive.google.com/file/d/1S_7PhwqxBdxe3E_y1Qa1Q11L0xjItyGs/view?usp=sharing

**Comment by PeterShaggyNoble** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by PeterShaggyNoble** [comment]
I've opened a [PR](https://github.com/simple-icons/simple-icons/pull/2913) for this over at Simple Icons.

![EmulationStation](https://user-images.githubusercontent.com/15157491/78775021-7b0caf80-798d-11ea-8b50-9054d0a193d8.png)

**Comment by Asthonishia** [comment]
I did not understand that "brand" included open source projects ... My bad !
