### ISSUE TITLE
icon name: "selection-mutliple" instead of "selection-multiple

### ISSUE THREAD

**Issue by sitecarpenter** [Templarian/MaterialDesign#5029]
The icon which should have the name "selection-multiple" is called "selection-mutliple".

**Comment by Templarian** [comment]
Fixed. Good catch we're wrapping up the `5.1.45` release right now and this will make the cut.

**Comment by sitecarpenter** [comment]
Thanks! Okay, great! This was my first attempt to create a pull request, so I hope it helped.
