### ISSUE TITLE
security-link-variant

### ISSUE THREAD

**Issue by KevinLeighCrain** [Templarian/MaterialDesign#503]
I thought of maybe an icon that combines the link icon and lock icon together to indicate a secure network or secure link. Peace

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/shield + https://materialdesignicons.com/icon/link ?

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/security-network This one also exists and might work (it's more local network though).

**Comment by KevinLeighCrain** [comment]
https://materialdesignicons.com/icon/link-variant +
https://materialdesignicons.com/icon/shield , the shield at the back and
the link variant on the shield. I really like your work
at materialdesignicons Austin. Well done.

Kind regards
Kevin

**Comment by CoDEmanX** [comment]
![shield-link](https://cloud.githubusercontent.com/assets/1309249/8714577/1297d1fa-2b77-11e5-9d76-35bc89884850.png) https://www.dropbox.com/s/q55zxw672p9gcg9/shield-link.svg?dl=0

It violates the 2px spacing guideline on the chains. Stroke width of shield is >2px however.

If you want to express "secure connection", use https://materialdesignicons.com/icon/lock (equals http://www.google.com/design/icons/#ic_https) to not be overly literal.

**Comment by Templarian** [comment]
[![shield-link-variant](https://materialdesignicons.com/icon/shield-link-variant)](https://materialdesignicons.com/icon/shield-link-variant) [![shield-link-variant-outline](https://materialdesignicons.com/icon/shield-link-variant-outline)](https://materialdesignicons.com/icon/shield-link-variant-outline)
