### ISSUE TITLE
bucket-plus

### ISSUE THREAD

**Issue by arunsundaramco** [Templarian/MaterialDesign#5030]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Bucket is a concept that I run into often in multiple applications. I am not talking about (just) s3 buckets. It acts as a container where things are added to, removed from, etc. However, a Shopping Cart is a poor replacement when there is no "ordering" involved.

## Examples

Surprisingly there are no icons that comes close to a bucket to provide as an example.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/79034447-858c9c00-7b7b-11ea-8275-db28847b6cd0.png)

A literal bucket. 🤔

**Comment by Templarian** [comment]
I've been informed this would be a `pail`. So bucket could be without the handle maybe.

**Comment by tgrelka** [comment]
After having consulted the oxford dictionary, both bucket and pail have a handle, they're listed as synonyms. Personally, I would prefer the naming `bucket` and `bucket-variant` (without handle), as that's easier to find as an icon.

**Comment by Templarian** [comment]
Yeah, I think we can get both added. One as `bucket` without handle, and `pail` with a handle.

**Comment by Templarian** [comment]
Added these, but keeping it open to add various overlays.

- [x] `bucket`
- [x] `bucket-outline`
- [x] `pail`

**Comment by tgrelka** [comment]
My point was, bucket and pail are synonyms (at least that's what I learned and it says so in three dictionaries I checked).  I personally would find it confusing when searching for a "bucket", finding one without a handle but not the one with, and later finding out that "pail" was the one **with** a handle. `bucket` and `bucket-variant` seems more in-line with MD, as well as being grouped together in alphabetical lists (which makes logical sense) and easier to find, because a search for "bucket" finds all of them. Of course, language is never super precise, so I don't quite see the sense in using a - especially for non-native speakers, rather confusing naming when `object` and `object-variant` is a perfectly valid MDI naming scheme.

**Comment by Templarian** [comment]
That makes sense and I kind of agree. We'll add aliases for pail/bucket so people can find them. I kind of already cut the release, so we'll stick with this naming for now. This also keeps the naming shorter, when I add the `-plus`, `-minus`, `-remove` overlays.

**Comment by tgrelka** [comment]
Thank you!

**Comment by arunsundaramco** [comment]
Both the bucket-outline and the bucket looks great. Thank you.

Should I open additional requests for each of the following overlays for you (or others) to look into: plus  (imply adding a new bucket), minus (removing the bucket) curved arrow in (item added to bucket), and arrow out (item taken out of bucket)?

Just a personal thought: the WIP image above with the handle on looks even better!

**Comment by Templarian** [comment]
@arunsundaramco I'll create the overlays shortly (we have templates that make it a quick process).

You `pail` and `bucket` were both added. So use `pail` if you want the handle.

**Comment by arunsundaramco** [comment]
That would be wonderful @Templarian.

**Comment by arunsundaramco** [comment]
Not trying to be a pest. Looking forward for the pail and bucket overlays.

**Comment by goyney** [comment]
Bucket or pail?

**Comment by arunsundaramco** [comment]
Pail suits better for the application I am working on.

**Comment by goyney** [comment]
All the basics added.

[![pail-plus](https://materialdesignicons.com/icon/pail-plus)](https://materialdesignicons.com/icon/pail-plus)[![pail-minus](https://materialdesignicons.com/icon/pail-minus)](https://materialdesignicons.com/icon/pail-minus)
[![pail-remove](https://materialdesignicons.com/icon/pail-remove)](https://materialdesignicons.com/icon/pail-remove)[![pail-off](https://materialdesignicons.com/icon/pail-off)](https://materialdesignicons.com/icon/pail-off)
[![pail-outline](https://materialdesignicons.com/icon/pail-outline)](https://materialdesignicons.com/icon/pail-outline)
[![pail-plus-outline](https://materialdesignicons.com/icon/pail-plus-outline)](https://materialdesignicons.com/icon/pail-plus-outline)[![pail-minus-outline](https://materialdesignicons.com/icon/pail-minus-outline)](https://materialdesignicons.com/icon/pail-minus-outline)
[![pail-remove-outline](https://materialdesignicons.com/icon/pail-remove-outline)](https://materialdesignicons.com/icon/pail-remove-outline)[![pail-off-outline](https://materialdesignicons.com/icon/pail-off-outline)](https://materialdesignicons.com/icon/pail-off-outline)

**Comment by arunsundaramco** [comment]
This is terrific. Given there isn't anything close to representing the pail/bucket, I am hopeful many others like me benefit from your great work @goyney 
Thank You.
