### ISSUE TITLE
I need help for use the github tool 

### ISSUE THREAD

**Issue by Skyn3n0l** [Templarian/MaterialDesign#5032]
Hello,
I designed 4 icons but I can't format it on the GitHub tool on your site and I need help for that, I have all SVG ^^'.
Thanks for your responses.

**Comment by Templarian** [comment]
Your SVG's need to be flattened to a single path. You can do this by selecting all items and unioning the points also knowing as unite in some apps. Usually under path operations.

Once you do that export as an SVG file. We'll optimize it later, so any path data would work.

Find the `<path d="...">` and copy everything in the `...` spot. Paste that into the site below to generate an image that can be copy/pasted into a comment.

http://dev.materialdesignicons.com/contribute/github

Eventually we may add an upload button to make things a little easier.

**Comment by Skyn3n0l** [comment]
on my SVG's I have 3 to 5 <path d = "..."> in one SVG file

**Comment by Skyn3n0l** [comment]
I don't how I can flatten my path's of my files

**Comment by Skyn3n0l** [comment]
I can't have a single path I have between 3 and 5 path each time ^^’

**Comment by Skyn3n0l** [comment]
I have a single path and copy this in two locations for data and nothing appears and the image under stay virgin.

**Comment by Templarian** [comment]
Closing this out. Feel free to make the issue without the attached previews and zip + attach the svg files. We'll sort it out if you get stuck.

Search unioning paths for your software if you get stuck.
