### ISSUE TITLE
inbox-remove & inbox-outline-remove

### ISSUE THREAD

**Issue by replygirl** [Templarian/MaterialDesign#5035]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In a list item or context menu, reinforce an option to remove an item from an inbox or similar collection object

## Design recommendation

Put an x in the empty space--it seems perfectly sized

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/80826946-f54ce000-8b97-11ea-98dd-05d4d9181b72.png)
[inbox-remove.svg](https://github.com/terreng/samples/blob/master/inbox-remove.svg)

![image](https://user-images.githubusercontent.com/11605395/80827048-1d3c4380-8b98-11ea-98ed-4a83d7afe821.png)
[inbox-remove-outline.svg](https://github.com/terreng/samples/blob/master/inbox-remove-outline.svg)

**Comment by goyney** [comment]
[![inbox-remove](https://materialdesignicons.com/icon/inbox-remove)](https://materialdesignicons.com/icon/inbox-remove)[![inbox-remove-outline](https://materialdesignicons.com/icon/inbox-remove-outline)](https://materialdesignicons.com/icon/inbox-remove-outline)
