### ISSUE TITLE
Floodlight icons downwards and upwards

### ISSUE THREAD

**Issue by mykp** [Templarian/MaterialDesign#5036]
I have:

- Searched all issues to make sure there isn't a request for this icon.
- Searched the current library to make sure the icon doesn't exist.
- Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In Home Automation menus for exterior floodlight switch icons.

## Examples

Something along these lines?

<img width="95" alt="image" src="https://user-images.githubusercontent.com/16393091/79170156-72313900-7de6-11ea-92cd-eafc2cd7dc7b.png">

<img width="71" alt="image" src="https://user-images.githubusercontent.com/16393091/79170321-f1bf0800-7de6-11ea-8d80-e298ecf8dab8.png">

**Comment by tgrelka** [comment]
![floodlight-downwards](https://user-images.githubusercontent.com/22134144/79698468-62ec3880-8289-11ea-86d9-42c135f530af.png)
I gave it a shot! I'll add a `upwards` and `-outline` variants later, this is just the concept. I think the three light rays help communicate the meaning of the icon better.
But, I think I made the floodlight a bit too small, maybe it should be scaled up.
[floodlight-downwards.zip](https://github.com/Templarian/MaterialDesign/files/4500065/floodlight-downwards.zip)

**Comment by mykp** [comment]
Looks good thanks. I like the proportion and the light rays. Would it lend itself to an outline version as well do you think.

**Comment by Templarian** [comment]
Angling down the light a little bit more might help. 30 degrees.

**Comment by tgrelka** [comment]
I'll work on it later.

**Comment by mykp** [comment]
Any time to progress this please?

**Comment by mykp** [comment]
Any chance of this being completed please?

**Comment by goyney** [comment]
[![light-flood-up](https://materialdesignicons.com/icon/light-flood-up)](https://materialdesignicons.com/icon/light-flood-up)[![light-flood-down](https://materialdesignicons.com/icon/light-flood-down)](https://materialdesignicons.com/icon/light-flood-down)

**Comment by mykp** [comment]
Great job - thank you!

**Comment by perdw** [comment]
These are great! An "off" version of these would be appreciated.
