### ISSUE TITLE
zhihu and bilibili

### ISSUE THREAD

**Issue by CaanDoll** [Templarian/MaterialDesign#5038]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
- zhihu
![zhihu](https://user-images.githubusercontent.com/23540471/79212251-eec12780-7e79-11ea-9944-dde7d71f0f35.png)
- bilibili
![bilibili](https://user-images.githubusercontent.com/23540471/79212273-f680cc00-7e79-11ea-8a66-07f0de6ec1c7.png)

## Zip Download
[svg.zip](https://github.com/Templarian/MaterialDesign/files/4474594/svg.zip)

**Comment by PeterShaggyNoble** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by PeterShaggyNoble** [comment]
Zhihu is [already available](https://simpleicons.org/?q=Zhihu) from Simple Icons and I've [opened a PR](https://github.com/simple-icons/simple-icons/pull/2939) for you for Bilibili.

![Zhihu](https://user-images.githubusercontent.com/15157491/79335019-3e0a6500-7f19-11ea-9cbf-81ac2a090894.png)![Bilibili](https://user-images.githubusercontent.com/15157491/79335158-75791180-7f19-11ea-9f80-4431b5b2b6a2.png)

**Comment by CaanDoll** [comment]
thx!
