### ISSUE TITLE
Permanent link bug

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#504]
If you click the chain Icon, a second dialog will be opened. To return to the main page, both need to be closed. There should only be a need to close one.

BTW: is it possible to speed it up? It seems to reload the page. Also, when you open a permanent link, it takes a lot of time until the dialog with the icon is shown, and it's not very clear that the page is loading for some time.

(Firefox 39 on Windows and chrome for Android 43)

**Comment by PeterShaggyNoble** [comment]
Closing this as focus has shifted to the new site.
