### ISSUE TITLE
Request to add sports icons, more specifically actions involving basketball

### ISSUE THREAD

**Issue by williancm812** [Templarian/MaterialDesign#5040]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Icons like the ones below, would be actions related to the events present in a basketball game

[Icons 1](https://www.istockphoto.com/pt/vetorial/basketball-icon-set-vector-illustration-graphic-design-gm952401904-260003783)

[Icons 2](https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vectorstock.com%2Froyalty-free-vector%2Fbasketball-icons-set-vector-10290976&psig=AOvVaw0teVADStnt8Co5GEtRvqBb&ust=1586966598875000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCIDooLql6OgCFQAAAAAdAAAAABAb)

[Icons 3](https://www.google.com/url?sa=i&url=https%3A%2F%2Feu.fotolia.com%2Fid%2F193828561&psig=AOvVaw0teVADStnt8Co5GEtRvqBb&ust=1586966598875000&source=images&cd=vfe&ved=0CA0QjhxqFwoTCIDooLql6OgCFQAAAAAdAAAAABAj)

**Comment by goyney** [comment]
You've obviously done zero searching.

**Comment by goyney** [comment]
Please see our collection of [sports icons](https://materialdesignicons.com/tag/sport) which contains many of the ones in your example. If there are specific ones we do not have, please open a new issue for each one.
