### ISSUE TITLE
[Removed]

### ISSUE THREAD

**Issue by iMrDJAi** [Templarian/MaterialDesign#5041]

**Comment by Templarian** [comment]
@iMrDJAi If there is a documentation gap please let us know. We try and document almost every framework. If you got confused it could help others in the same boat.

**Comment by Templarian** [comment]
I would highly recommend not using the webfont though.

http://dev.materialdesignicons.com/guide/webfont-alternatives

**Comment by iMrDJAi** [comment]
> 
> 
> I would highly recommend not using the webfont though.
> 
> http://dev.materialdesignicons.com/guide/webfont-alternatives

Oh sorry, I generally delete my issues when I find solutions alone so contributors don't have to worry about it anymore.

Now I'm using the @mdi/react, it's compatible.
