### ISSUE TITLE
wildfire / forest-fire / pine-tree-fire

### ISSUE THREAD

**Issue by therufa** [Templarian/MaterialDesign#5042]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The icon would come in handy for an European MET service which intends to move to MDI. The icon should indicate a warning for forest- and wildfires. 

## Examples

Include any example images so we know what the icon should look like.

![Wildfire](https://user-images.githubusercontent.com/315825/79364989-58a90200-7f4a-11ea-8ebc-fff381adfc81.png)

I'm not very skilled with SVG, but i gave my best to create this one:
[Wildfire.zip](https://github.com/Templarian/MaterialDesign/files/4482649/Wildfire.zip)

**Comment by Templarian** [comment]
I think the idea of this icon could work very well in the pack. We'll need to tweak the cut out a little.

Updated the title with a few name ideas. We have a `pine-tree` and this is kind of a overlay for it.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/79709784-b6aa5200-8288-11ea-8186-98272760d589.png)

What about this?

**Comment by therufa** [comment]
@Templarian this is much nicer than what I made

**Comment by Templarian** [comment]
This has been added.
