### ISSUE TITLE
lifted-truck

### ISSUE THREAD

**Issue by jkruskie** [Templarian/MaterialDesign#5043]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A lifted truck icon could be useful for vehicle modification shops.

## Examples

![](https://cdn.clipart.email/5df939141aba2c6526e9a2a29bfc439f_truck-big-tires-svg-pdf-png-jpg-dxf-eps-custom-designs-wording-_570-376.jpeg)

**Comment by Templarian** [comment]
Basically a `car-pickup` modified with lower wheels / higher body frame.

- [ ] So we don't forget we need to alias `car-pickup` with `truck`.

**Comment by Templarian** [comment]
Maybe name this one `car-pickup-lifted`. Not a car person, @jkruskie is a lifted truck the same a pickup?

**Comment by jkruskie** [comment]
@Templarian A lifted truck and lifted pickup would be the same. Truck is just short for pickup truck.

**Comment by jkruskie** [comment]
@Templarian Something of the sorts of car-lifted-truck or car-lifted-pickup. Something to signify that it is a lifted truck, which is typically meant for mudding and offroad.

**Comment by Templarian** [comment]
I think `car-lifted-pickup` works. Reads a little nicer. 👍  We're using truck for delivery type cargo trucks, so this will keep it consistent.

Thanks for the clarification!

**Comment by jkruskie** [comment]
@Templarian Thanks for taking this into consideration!

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/79950062-1e54ce80-843c-11ea-8034-bb9fe92d1b5f.png)

@jkruskie Does the above work. Cutting out the wheels and moving them down 2.

**Comment by jkruskie** [comment]
@Templarian 
I think it looks great. I do believe that it would look better with the mud tires, with the big lugs on the outside. (Like the ones given in my example)
Most people lift trucks to go mudding, so mud tires would fit this best.

Thanks!

**Comment by Templarian** [comment]
@jkruskie Oops, I designed and made this, but never added it. 🤦‍♂️ 

[![car-lifted-pickup](https://materialdesignicons.com/icon/car-lifted-pickup)](https://materialdesignicons.com/icon/car-lifted-pickup)
