### ISSUE TITLE
cog and cod-outline icon is not working.... how to fix it?

### ISSUE THREAD

**Issue by khalid-imran** [Templarian/MaterialDesign#5046]

**Comment by Templarian** [comment]
@khalid-imran Are you on v5+? These use to be called `settings`. After v5 we moved to using 3 dots as the standard representation of settings and `cog` as an overlay.

You can either update or just use v4 naming.

- v4: https://cdn.materialdesignicons.com/4.9.95/
- v5: https://cdn.materialdesignicons.com/5.1.45/
