### ISSUE TITLE
hammer + anvil

### ISSUE THREAD

**Issue by Cornelius-Labuschagne** [Templarian/MaterialDesign#5047]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

i recommend creating a hammer+anvil icon or something that may resemble forging or crafting

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@Cornelius-Labuschagne Please use the issue templates when creating issues. I pasted it in above, you can edit it to fill out the template. If you could paste in some examples that would be helpful.

**Comment by goyney** [comment]
Closing because `Needs More Info` was added quite a while ago without further clarification.
