### ISSUE TITLE
AllOptions or ManyOptions

### ISSUE THREAD

**Issue by sterlingwalsh** [Templarian/MaterialDesign#5048]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
My particular case is an icon to represent zooming on a map to show all markers, that could mean zooming either in or out, but without stepping on the expected UX of a standard zoom icon. Generally, the icon would represent an unstructured "show all". Searching the current library, the closest I could find was the gamepad icon. 

## Examples

Include any example images so we know what the icon should look like.
specific idea for request taken from https://graphicdesign.stackexchange.com/questions/2312/how-to-represent-all-all-options-show-all-as-an-icon https://i.stack.imgur.com/mr7MZ.png .

**Comment by goyney** [comment]
I feel like this is way too abstract a concept for an icon. The fact that there's a whole thread discussing how to possibly depict this concept in an icon throws red flags for me.

Icons are meant to be _contextual_. Sometimes, we can get lucky and it is easy to depict something literally, but that is not always the case. I feel that there are many options in our ever-growing collection that can serve your use case.

**Comment by Templarian** [comment]
This reminds me we need a `map-marker-scan`.

Maybe `map-marker-multiple`?

**Comment by sterlingwalsh** [comment]
@goyney if you have even a few suggestions of the many options that could serve my use case, I would gladly take the suggestions, but after looking for a while I could not find what I was looking for.

**Comment by sterlingwalsh** [comment]
@Templarian Something like this and an outlined version would work for my use and cover the naming you suggested. https://www.iconfinder.com/icons/1475077/area_location_map_multiple_pin_icon an outlined version would also be nice.

**Comment by goyney** [comment]
The icons @Templarian suggested already exist and are very similar to your link.
[![map-marker-multiple](https://materialdesignicons.com/icon/map-marker-multiple)](https://materialdesignicons.com/icon/map-marker-multiple)[![map-marker-multiple-outline](https://materialdesignicons.com/icon/map-marker-multiple-outline)](https://materialdesignicons.com/icon/map-marker-multiple-outline)

**Comment by goyney** [comment]
Closing because the `Needs More Info` and `Consider Closing` labels are both on this now for several months. If you have some other suggestions, please feel free to comment back here or open a new issue. Thanks for your suggestion!
