### ISSUE TITLE
Google icons not in their repository

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#505]
The following is from the MD specs, Family and Recipes are missing in their current GitHub repo:

![screenshot_2015-07-17-00-00-38](https://cloud.githubusercontent.com/assets/1309249/8736916/30f4c454-2c1d-11e5-9cbe-ee877416f20f.png)

zzZ icon in Google Clock app is also not available:

![screenshot_2015-07-16-05-01-06](https://cloud.githubusercontent.com/assets/1309249/8737057/9a228690-2c1e-11e5-85ab-de1f9079ea62.png)

Several more are used in Google Fit app for activity types, but there's not even the generic Sports icon it seems (also the screenshot above):

![screenshot_2015-07-11-09-13-05](https://cloud.githubusercontent.com/assets/1309249/8737071/bd7072a6-2c1e-11e5-9ac7-adb07dc0e738.png)

Camera switch icons are different from the ones used in Google Camera:

![screenshot_2015-07-11-21-42-12 2](https://cloud.githubusercontent.com/assets/1309249/8736995/fdde3b58-2c1d-11e5-916e-f11432a6d6d4.png)
![screenshot_2015-07-11-21-41-59 2](https://cloud.githubusercontent.com/assets/1309249/8736998/05ae8482-2c1e-11e5-8237-167cca0db42c.png)
![screenshot_2015-07-11-21-48-09 2](https://cloud.githubusercontent.com/assets/1309249/8737003/0e8f807e-2c1e-11e5-95de-a8edd20e2d5a.png)

I would like to add as many as possible of them, but I dunno how to do that without creating them from scratch (is the vector drawable data stored in apk files?). I also wonder what the licence of these unpublished icons is.

**Comment by danielhickman** [comment]
+1

**Comment by CoDEmanX** [comment]
iOS text icon found here: https://photos.google.com/apps

![googleiconios](https://cloud.githubusercontent.com/assets/1309249/8737256/6fc87cf4-2c20-11e5-9848-f98b08e83fd7.png)

It's an inlined SVG!

Google Fit website does have the sports-related icons, but they are PNGs. The ones we can grab from the APK are way better, but still raster images :(

**Comment by Templarian** [comment]
Wow, that is a really good idea to add the non documented icons.

Will look into creating these. Thanks for the screenshots.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/apple-ios
https://materialdesignicons.com/icon/baby
https://materialdesignicons.com/icon/tennis

Rasters are "easy" to reproduce since Google uses the same measurements on almost every icon. That volleyball though is a tough one.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/camera-front
https://materialdesignicons.com/icon/camera-front-variant
https://materialdesignicons.com/icon/camera-rear
https://materialdesignicons.com/icon/camera-rear-variant

Few more missing ones.

**Comment by Templarian** [comment]
I'm going to talk with Google and see if they have the vectors for the sports icons so I don't have to recreate them.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/sleep
https://materialdesignicons.com/icon/sleep-off

**Comment by CoDEmanX** [comment]
Great work Austin!

https://materialdesignicons.com/icon/sleep isn't by Google actually, in their version the Zs go from top left to bottom right. [I did it the other way](#502), because it works better for the off-state.

**Comment by CoDEmanX** [comment]
Google Fit icons of interest (too many to post here):
https://www.dropbox.com/sh/r3u4nopcxachcqr/AADDqfFxTJ8bpTX-sbDRw8rxa?dl=0

(Dropbox previews aren't that great if there's transparency, download for optimal quality)

Notes:
- `ic_weight_gray` is basically Google's [scale-bathroom](https://materialdesignicons.com/icon/scale-bathroom). There's another scale (`ic_weight_blue`), but it can also be interpreted as generic measurement icon.
- `ic_trophy_gray` and `ic_card_trophy` are different and alternatives to [trophy](https://materialdesignicons.com/icon/trophy) / [trophy-variant](https://materialdesignicons.com/icon/trophy-variant)
- `ic_calories_dark` is different from [fire](https://materialdesignicons.com/icon/fire)
- `ic_circuit_training_gray` is similar to [timer](https://materialdesignicons.com/icon/timer), but it has much more details, it is rounded and has a different hand position.
- `ic_distance_white` is a map marker in a rotated box, maybe useful
- `ic_heartrate_red` is different from [pulse](https://materialdesignicons.com/icon/pulse), but I like pulse better
- `ic_reorder_light` is 2x3, whereas [drag-vertical](https://materialdesignicons.com/icon/drag-vertical) is 2x5
- `ic_sleep_blue` is a moon, which seems to be missing from MDI, although there is [weather-night](https://materialdesignicons.com/icon/weather-night)
- `ic_graph_details_gray` seems to be `ic_equalizer_24px.svg` from their icon repo
- The following are rounded versions of the very similar stock ones: `ic_biking_teal` / `ic_fitness_walking_gray` / `ic_jogging_gray`

Duplicates (add one, use the others for aliases / tagging):
- `ic_indoor_skating_gray` / `ic_inline_skating_gray`
- `ic_kayaking_gray` / `ic_paddle_boarding_gray` / `ic_rowing_gray`
- `ic_dancing_gray` / `ic_zumba_gray`
- `ic_backcountry_skiing_gray` / `ic_downhill_skiing_gray`
- `ic_martial_arts_gray` / `ic_mixed_martial_arts_gray`
- `ic_open_water_swimming_gray` / `ic_pool_swimming_gray`
- `ic_road_biking_gray` / `ic_biking_teal`
- `ic_jogging_gray` / `ic_running_pink` (both rounded)
- `ic_ergometer_gray` / `ic_rowing_machine_gray`
- `ic_australian_football_gray` / `ic_rugby_gray`

---

Google Clock has a sand timer / hourglass different from the one in MDI and Google's own repo:
https://youtu.be/YXjCBN18MWE (3rd icon from left at the top)

![hourglass](https://cloud.githubusercontent.com/assets/1309249/8747409/0e0cb52a-2c93-11e5-9bf1-5123d628dfc2.png)

Moreover, it's the only half-full / half-empty hourglass. Google repo has full and empty only.

---

More from Google Camera
- ic_capture_**pano** / ic_**pano**_blanket

![ic_pano_blanket](https://cloud.githubusercontent.com/assets/1309249/8746267/e18f5332-2c87-11e5-9a07-196f6242cb09.png)

- ic_photosphere

![ic_photosphere_blanket](https://cloud.githubusercontent.com/assets/1309249/8746266/e18ce57a-2c87-11e5-884b-712be7665815.png)

- ic_photosphere_processing<br>
(I believe this is actually from a background, but after all, it's a simplified version of ic_photosphere)

![ic_photosphere_processing](https://cloud.githubusercontent.com/assets/1309249/8746294/20dd86ee-2c88-11e5-93a5-fadfff897d2d.png)

**Comment by Templarian** [comment]
@CoDEmanX I can't add the Google Fit icons until I get an email back from http://alexlikesdesign.com/google-fit-ui-iconography/

I need to verify the usage rights kept on the icons and if it is possible for them to be open sourced.

**Comment by CoDEmanX** [comment]
I see. BTW: on Alex's page, there are a couple more icons I obviously missed or weren't in the APK:

Table tennis, team sports, wheelchair, windsurfing, spinning, skateboarding, sledding, snowmobiling, back-country skiing, snowboarding, soccer, stair climbing, surfing, strength training, water polo - man this guy is a :hamster:

**Comment by CoDEmanX** [comment]
There's an alternative version of the briefcase icon used in Google Contacts. It has no rounded handle:
![screenshot_2015-07-19-11-46-17 2](https://cloud.githubusercontent.com/assets/1309249/8766861/b4d5db50-2e48-11e5-9d78-b34dda683efe.png)

**Comment by MaxKorz** [comment]
What about redesigned YouTube player icons? https://www.youtube.com/testtube

They're animated (sic!) and they look differently

Youtube vs Repository 
![volume-high](http://i.imgur.com/oStBoKe.png) vs ![volume-high](http://i.imgur.com/v8HyC51.png)
![volume-medium](http://i.imgur.com/gvfsb5w.png) vs ![volume-medium](http://i.imgur.com/oypKNW3.png)
![volume-off](http://i.imgur.com/nEzsfsH.png) vs ![volume-off](http://i.imgur.com/jfFgPOZ.png)

It's inlined SVG as well

**Comment by CoDEmanX** [comment]
They are not fully compliant to the MD specs. They rather look like they looked for a long time, for consistency. YouTube has millions of inexperienced users which could get confused maybe... We can think about an alternate mute icon, but it should be based on the MD speaker icon.

**Comment by CoDEmanX** [comment]
@Templarian: is transparency supported by TTF / OTF / WOFF? Google's WiFi and battery status icons use different opacities...

Furthermore, the battery icons do not match the ones used in stock android lollipop, the latter have no rounding at the top. What shall we do?

**Comment by Templarian** [comment]
Their updated icons have no transparency in their 2.0 set. Not all the icons are going to match 1:1 some have slight variations since 2.0 was released.

These are from 1.0, it looks like google deleted all of their battery related icons and only left a few remaining. I think the ones in the community pack are fine.

**Comment by CoDEmanX** [comment]
Fill color 30% opacity in their repo, latest trunk:
https://github.com/google/material-design-icons/blob/master/device/svg/design/ic_battery_50_24px.svg

**Comment by CoDEmanX** [comment]
Local ATM icon is different in Google Maps:

![screenshot_2015-07-21-17-19-31 2](https://cloud.githubusercontent.com/assets/1309249/8804930/cd6240a0-2fce-11e5-9b13-a945f3fa09e4.png)

https://www.google.com/design/icons/#ic_local_atm

Couldn't find either on MDI.

**Comment by CoDEmanX** [comment]
Alternative version of light bulb:
![light-bulb](https://cloud.githubusercontent.com/assets/1309249/8858239/9f46626a-3176-11e5-96b8-d82cde423396.png) https://www.dropbox.com/s/7ee1y3mvq8lk1g0/light-bulb.svg?dl=0 (reference image still included)

Works nicely IMO, although it's not fully pixel-aligned and stroke-width is 1.5px. But this is the closest I got to the reference image, assuming they had a 2px margin on all borders.

**Comment by CoDEmanX** [comment]
Saw a `bluetooth-transfer` icon on my Nexus 5, stock Android:
![screenshot_2015-07-23-21-49-08](https://cloud.githubusercontent.com/assets/1309249/8863387/810f208a-3198-11e5-9cbc-2eb02d58020b.png)

![bluetooth-transfer](https://cloud.githubusercontent.com/assets/1309249/8863351/1cec0e60-3198-11e5-943e-f4a96a8fafff.png) https://www.dropbox.com/s/5c8ms5905w6zxdq/bluetooth-transfer.svg?dl=0

**Comment by CoDEmanX** [comment]
The local atm item doesn't work that well, the "100" is hardly legible and got heavily distorted when I saved it as optimized SVG (3 decimal places). Thus the existing bank note icon is probably preferred.

Below a design-version, with the digits as font letters in white:
![atm](https://cloud.githubusercontent.com/assets/1309249/8888601/b09f9916-32b4-11e5-8946-8aa2250bad32.png) https://www.dropbox.com/s/bzwx1jdd5x9egcm/atm.svg?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/bluetooth-transfer
https://materialdesignicons.com/icon/cash-100

Not really a big fan of the lightbulb variant. The on/off variants do not look as clean as the current ones.

Seeing as I can't get any response on the licensing for the Google Fit icons I can't currently add them.

**Comment by CoDEmanX** [comment]
Found another in Google Camera: crop and rotate
![screenshot_2015-08-05-12-45-45 2](https://cloud.githubusercontent.com/assets/1309249/9084244/e7844556-3b71-11e5-9f23-1528d03cbba8.png)

**Comment by CoDEmanX** [comment]
Re-creation of crop-rotate:
![crop-rotate](https://cloud.githubusercontent.com/assets/1309249/9135907/59edc74c-3d12-11e5-9f93-002ed1562929.png) https://www.dropbox.com/s/ipu3pd72mowurwx/crop-rotate.svg?dl=0

**Comment by CoDEmanX** [comment]
"important" icon ("fat arrow", "big chevron"?):
![important](https://cloud.githubusercontent.com/assets/1309249/9234934/202f80d0-413c-11e5-8e24-e33015f7925c.png) https://www.dropbox.com/s/mgffguy7kvhzl5n/important.svg?dl=0

as seen in Gmail app:
![gmail_important](https://cloud.githubusercontent.com/assets/1309249/9234905/0c5e86c8-413c-11e5-8e80-f9dafe2c3881.png)

3 more icons over here: https://github.com/Templarian/MaterialDesign/issues/420#issuecomment-127570399

**Comment by jvanderwee** [comment]
Also a few icons from https://www.google.co.uk/design/spec/style/icons.html#icons-system-icons, e.g. full body icons:
![image](https://cloud.githubusercontent.com/assets/3587922/9257910/5e2a1242-41f0-11e5-95f6-8f9031e5faed.png)

**Comment by danielhickman** [comment]
I found this one in one of Google's repos.
![physical-web-logo](https://cloud.githubusercontent.com/assets/5341898/9425256/4b61e844-48bf-11e5-96ce-1b6065a59d71.png)

**Comment by CoDEmanX** [comment]
I tried to re-create the recipe / apple icon, here are the results:
https://www.dropbox.com/s/8utdls3o5z5wpk6/apple2.svg?dl=0
https://www.dropbox.com/s/ikxmp4h5zdpgu70/apple3.svg?dl=0 less points, but no perfect line width on the left half

**Comment by CoDEmanX** [comment]
Android 6 icons:

![android6](https://cloud.githubusercontent.com/assets/1309249/10834105/ffbbd518-7e96-11e5-85fb-9acbfedf7df7.png)

The battery icon is not pixel-perfect and has no rounding on the top corner in contrast to the repo / MDI battery icons. Should we change the existing icons to use no rounding, add an additional set or ignore this variation?

RAM: The original is not pixel-perfect either. I think my slightly different but pixel-perfect version is better for MDI.
![ram](https://cloud.githubusercontent.com/assets/1309249/10827014/c97b183a-7e6c-11e5-9931-50be7d98613e.png) https://www.dropbox.com/s/rjhgrkjsqx8jgfb/ram.svg?dl=0
![ram-reference](https://cloud.githubusercontent.com/assets/1309249/10827015/c97c82ba-7e6c-11e5-8e0b-39542de1f600.png)

![minus-circle-off](https://cloud.githubusercontent.com/assets/1309249/10834143/3f0ceb44-7e97-11e5-9950-eceae962e178.png) https://www.dropbox.com/s/cqi7i2jrlqt8a5n/minus-circle-off.svg?dl=0
![cast-off](https://cloud.githubusercontent.com/assets/1309249/10834149/43cc18a8-7e97-11e5-988a-06550924932b.png) https://www.dropbox.com/s/vbn9kww09ynlgn1/cast-off.svg?dl=0

**Comment by CoDEmanX** [comment]
![protected-content](https://cloud.githubusercontent.com/assets/1309249/10866778/46b8639a-8041-11e5-8c46-271e7f64f029.png) https://www.dropbox.com/s/itpqtrhy5ridy6v/protected-content.svg?dl=0
![cookie](https://cloud.githubusercontent.com/assets/1309249/10866779/46bf9e30-8041-11e5-8fd5-22d660aa4d67.png) https://www.dropbox.com/s/mct4gj6o4wpsjyw/cookie.svg?dl=0

Found in Chrome:
![screenshot_20151031-142430x](https://cloud.githubusercontent.com/assets/1309249/10866798/09886334-8042-11e5-898e-ad2aa05d43d8.png)

The icon used for the JavaScript entry is very similar to MDI's import icon, so not really needed. The language icon is not very legible at small sizes and there's a superior "translate" icon in the Google repository.

**Comment by CoDEmanX** [comment]
I tried to re-create a few of the Google Fit icons, but it's pretty difficult. They were designed for 18x18 pixels, and they need to be changed quite a lot to make them pixel-perfect at 20 / 24px. Not sure how to continue...
![google-fit](https://cloud.githubusercontent.com/assets/1309249/11046025/3182167e-872b-11e5-8f7b-1329092423ca.png)

**Comment by CoDEmanX** [comment]
Found this on Google Docs and slightly improved the grid alignment:
![upper-lower-case](https://cloud.githubusercontent.com/assets/1309249/11060825/f78747d2-87a2-11e5-9343-d9b4927a06e9.png) https://www.dropbox.com/s/f1eqo6cjixlrnv2/upper-lower-case.svg?dl=0

**Comment by CoDEmanX** [comment]
email-multiple as seen in Gmail app:
![email-multiple](https://cloud.githubusercontent.com/assets/1309249/11080348/13d218d4-8813-11e5-9012-d03c2715e8df.png) https://www.dropbox.com/s/rluoltturxzf06l/email-multiple.design?dl=0

**Comment by CoDEmanX** [comment]
Discovered on Google Maps website:

![google-maps-icons](https://cloud.githubusercontent.com/assets/1309249/11189486/a38b5cfc-8c90-11e5-9c2f-a72c629354c6.png)

Couldn't find them in their repo in a quick search, but I might've overlooked them. If not, shall I re-create them all @Templarian?

**Comment by CoDEmanX** [comment]
In Google Clock app:

New round (timer feature)
![screenshot_20151116-192215](https://cloud.githubusercontent.com/assets/1309249/11190828/2c6006fc-8c98-11e5-933e-de58fe10a17e.png)

Reset timer
![screenshot_20151116-192222](https://cloud.githubusercontent.com/assets/1309249/11190829/2c613770-8c98-11e5-8f7b-234fe671dbc6.png)

The latter can be created by simply mirroring https://materialdesignicons.com/icon/reload

**Comment by CoDEmanX** [comment]
I don't think I've seen this in their repo either:

![salute](http://i.imgur.com/ATdfpWe.png?1)

**Comment by CoDEmanX** [comment]
There's apparently a tramway icon in Google Maps(?):
https://github.com/google/material-design-icons/issues/271

**Comment by rcknr** [comment]
@CoDEmanX It is in different style though. All other directions icons show vehicle type from the front.

**Comment by CoDEmanX** [comment]
Two more from the guidelines:

![hearing_family-games](https://cloud.githubusercontent.com/assets/1309249/12251426/29ab12fe-b8cf-11e5-8e16-a7898e2796c1.png)

The star is actually a counter example, but Google uses it in the Play Store app for family games IIRC.

**Comment by CoDEmanX** [comment]
This icon appears in the status bar if you take a screenshot on a stock Android:

![screenshot_20160125-125403a](https://cloud.githubusercontent.com/assets/1309249/12556357/b5048dba-c385-11e5-9345-0964da3e926f.png)

It doesn't comply to MD guidelines it seems. A more material-y version could look like this:

![screenshot](https://cloud.githubusercontent.com/assets/1309249/12556351/b0fee0bc-c385-11e5-9897-2be84a529922.png) https://www.dropbox.com/s/zpoueg8sgwmebz1/screenshot.svg?dl=0

**Comment by CoDEmanX** [comment]
From Google Photos app:

- [ ] assistant
- [ ] story / flick through / book open (yet another variant)
- [ ] animation / keyframes
- [ ] collage
- [ ] what's new / dashboard? / view/layout something?
- [ ] ov-gif (auto-generated mini animations of picture series)

From Google Maps (I think):
- [ ] directions
- [ ] lead-pencil
- [ ] mobile-devices

Dropbox: https://www.dropbox.com/sh/v7ftlivfq8gc1kx/AAC7oVXF0i4MYYCLgJcJ1rGFa?dl=0

**Comment by CoDEmanX** [comment]
"collections" icon from Google Plus (SVG is inlined on their page):
https://www.dropbox.com/s/8baq6um8y8qplck/collections.svg?dl=0

**Comment by CoDEmanX** [comment]
![google-icons](https://cloud.githubusercontent.com/assets/1309249/13304710/c38c2760-db56-11e5-8324-7f0040cc3dcc.png)

- [ ] Google Docs something, not grid-aligned at all
- [ ] location (near by, Google Maps)
- [ ] Sorted inbox (Gmail)
- [ ] drag handle (Google Keep) / Braille?
- [ ] add participant (call conference, Google Phone)
- [ ] select (Keep)
- [ ] eraser (Keep)
- [ ] pen (Keep)
- [ ] grease pencil (Keep)
- [ ] marker pen (Keep)

Tried to re-create some of them: ![drag-handle](https://cloud.githubusercontent.com/assets/1309249/13304825/6ed49c60-db57-11e5-96a1-a6cb12b2e29b.png) ![eraser](https://cloud.githubusercontent.com/assets/1309249/13304822/6ed3c54c-db57-11e5-9d53-de780c156973.png) ![grease-pencil](https://cloud.githubusercontent.com/assets/1309249/13304820/6ed13336-db57-11e5-914a-11e43b7422c2.png) ![location](https://cloud.githubusercontent.com/assets/1309249/13304823/6ed44a44-db57-11e5-972a-1cd36a3b5bfd.png) ![marker](https://cloud.githubusercontent.com/assets/1309249/13304824/6ed4ceb0-db57-11e5-8411-c33eb1691ea7.png) ![phone-minus](https://cloud.githubusercontent.com/assets/1309249/13304821/6ed1ea24-db57-11e5-9b7b-52b2d0e6ef63.png) ![phone-plus](https://cloud.githubusercontent.com/assets/1309249/13304826/6ee9f81c-db57-11e5-9f31-e51071868f2e.png) ![selection-arrow](https://cloud.githubusercontent.com/assets/1309249/13304827/6eecceca-db57-11e5-9408-f54b04da24cf.png)

**Comment by Templarian** [comment]
@CoDEmanX Wehre are the SVG's for the ones above (eraser, marker, pens, highlighters etc)?

I really want to get more of the drawing icons in.

**Comment by CoDEmanX** [comment]
Was actually waiting for 1.5 release, because you said you would start to add many more icons after that, but I can provide them any time of course. I'm not quite happy with the drawing icons though, they feel like they aren't fully material yet. I tried to adhere to the reference icons, but they don't really comply to the MD guidelines. I think they should be slightly smaller...

**Comment by Templarian** [comment]
Yea, no problem. Yea, no new icons are going in before the `1.5.54` release.

**Comment by CoDEmanX** [comment]
Found these 3 in the latest official sticker sheet:

![select-something](https://cloud.githubusercontent.com/assets/1309249/13584732/2c14db6e-e4b8-11e5-9028-f4846de3e064.png) ![updates](https://cloud.githubusercontent.com/assets/1309249/13584731/2c0f389e-e4b8-11e5-90b8-153805fee79b.png) ![clipboard-outline](https://cloud.githubusercontent.com/assets/1309249/13584733/2c2ab4ac-e4b8-11e5-984f-a04b4505e0d5.png) (select-?, updates, clipboard)

The clipboard is quite a bit larger than our version.

**Comment by anjocerdena** [comment]
I'm contributing icons found in notifications: Android Device Manager and Weather in Google Now (an alternative to the cloud icon).

![screenshot_20160419-124558](https://cloud.githubusercontent.com/assets/15527344/14639895/8aede8bc-0671-11e6-8ff9-105e9262ed19.png)

![android device manager](https://cloud.githubusercontent.com/assets/15527344/14639914/9e928620-0671-11e6-9e6b-85f6ab07e15f.png) ![google now weather](https://cloud.githubusercontent.com/assets/15527344/14639915/9f9b7658-0671-11e6-96ff-588559964662.png)

[Found Google icons.zip](https://github.com/Templarian/MaterialDesign/files/225893/Found.Google.icons.zip)

**Comment by Templarian** [comment]
[![phone-plus](https://materialdesignicons.com//icon/phone-plus)](https://materialdesignicons.com/icon/phone-plus] [![phone-minus](https://materialdesignicons.com//icon/phone-minus)](https://materialdesignicons.com/icon/phone-minus)

**Comment by CoDEmanX** [comment]
The phone-minus icon is actually from the recesses of creativity of mine. Phone-plus is by Google and used in their dialer app to add participants to a call, but no minus button to remove. Seemed like a good addition icon-wise though.

**Comment by CoDEmanX** [comment]
some more recreations: ![new4c_ 505](https://cloud.githubusercontent.com/assets/1309249/14904176/bb9bcfe2-0da6-11e6-9717-41a5ed3c7be8.png) ![pen_ 505](https://cloud.githubusercontent.com/assets/1309249/14904177/bb9cb5ec-0da6-11e6-9999-a01c01ee1646.png) ![sorted-inbox_ 505](https://cloud.githubusercontent.com/assets/1309249/14904179/bb9ef83e-0da6-11e6-8512-a709f43db870.png)

Based on @anjocerdena's idea to add the locate device icon, I made one that matches our existing map-marker: ![map-marker-locate_ 505](https://cloud.githubusercontent.com/assets/1309249/14904178/bb9e8ca0-0da6-11e6-8767-e124f04b0b9e.png)

@Templarian: Here's another pack of icons, including above:
https://www.dropbox.com/s/wf4jjxu07pammz7/2016-04-29_Conversion.zip?dl=0

**Comment by CoDEmanX** [comment]
The keyboard app for Android was updated and has now some sort of display mode for one-handed writing. The icon to activate this mode:

![image](https://cloud.githubusercontent.com/assets/1309249/15409218/1f54f432-1e14-11e6-8881-6e5edae0548c.png)

My re-creation doesn't seem very recognizable at 24px² though: ![keyboard-one-handed](https://cloud.githubusercontent.com/assets/1309249/15410102/40c8c108-1e18-11e6-9f93-8e0b58228aee.png)

**Comment by JamesCoyle** [comment]
https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-122299730
Did you ever get the permission to use those?

**Comment by TheManuz** [comment]
I retraced the hourglass icon of system alarm app, mentioned in [@CoDEmanX comment](https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-122265400).

Here are the PNGs:
![hourglass_24px](https://cloud.githubusercontent.com/assets/2032334/18915672/1db84bca-8592-11e6-9a97-09782f5962d1.png)
![hourglass_24px 2x](https://cloud.githubusercontent.com/assets/2032334/18915673/1dc200fc-8592-11e6-9c43-d4da73fa3cae.png)
![hourglass_24px 4x](https://cloud.githubusercontent.com/assets/2032334/18915674/1dcb9658-8592-11e6-8157-bee770fa8340.png)

And here is the SVG (zipped):
[Hourglass_24px.svg.zip](https://github.com/Templarian/MaterialDesign/files/498165/Hourglass_24px.svg.zip)

**Comment by gabrielgrant** [comment]
@Templarian Did you ever hear back about the Google Fit icons? Looks like the same person/people have more (afaics not-in-repo) icons here: https://lunarsaloon.com/work/google-iconography/

**Comment by Templarian** [comment]
@gabrielgrant Yea, Google owns all rights to the icons as far as the designer knew. We just need to get them traced and added I assume (was on a week vacation working through backlog of issues, usually quicker at responding). If someone wants to reach out for the source files that might be quicker.

**Comment by JapanYoshi** [comment]
TIL even Google sometimes breaks their own Guidelines.
