### ISSUE TITLE
lecturn

### ISSUE THREAD

**Issue by OblivionSY** [Templarian/MaterialDesign#5053]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To denote a speaker, lecturer, presentation giver. Could include a couple (eg lecturn with or without speaker)

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/3511993/79691934-281edc00-825a-11ea-923c-04373cfed17e.png)
![image](https://user-images.githubusercontent.com/3511993/79691936-2ce39000-825a-11ea-80ef-f89ada78e1d1.png)
![image](https://user-images.githubusercontent.com/3511993/79691940-33720780-825a-11ea-8817-1d4903cccf2d.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/137419062-63f3aab0-4c69-4405-8332-747460842e17.png)
[lectern.svg.zip](https://github.com/Templarian/MaterialDesign/files/7350276/lectern.svg.zip)

**Comment by goyney** [comment]
[![lecturn](https://materialdesignicons.com/icon/lecturn)](https://materialdesignicons.com/icon/lecturn)
