### ISSUE TITLE
Television and Television Outline Icon Set Variants

### ISSUE THREAD

**Issue by MEAN-James** [Templarian/MaterialDesign#5054]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Most icons have both a solid and outlined variant available and I think the television icon set shouldn't be an exception. Especially when considering how frequently UI's include some form of streaming or watching videos. One use case is to use the outline icons for inactive routes and solid icons along with a color for active routes.

## Examples
![Screen Shot 2020-04-19 at 12 51 29 PM](https://user-images.githubusercontent.com/32887770/79698265-bc7a4600-823c-11ea-9f25-ecdb837a9d64.png)
![Screen Shot 2020-04-19 at 12 51 45 PM](https://user-images.githubusercontent.com/32887770/79698267-bdab7300-823c-11ea-8ece-7d348958a21f.png)

**Comment by Templarian** [comment]
- [ ] `television-play`
- [ ] `television-pause`
- [ ] `television-stop`

This is a weird situation since `television` filled wouldn't look much like a TV.

**Comment by Templarian** [comment]
We're going to reject this request as the Television icon's meaning is lost in the filled version. This is one of those rare occasions where a filled variant is not possible.

It ends up looking more like a `card` with a notch at the bottom.
