### ISSUE TITLE
Clap, hands clapping

### ISSUE THREAD

**Issue by graphican** [Templarian/MaterialDesign#5055]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To appreciate, to encourage, to indicate you admire something. 

## Examples

Just like the icon in Medium Blogs, two hands clapping gives you an opportunity to appreciate some article or a product/service/initiative.

**Comment by goyney** [comment]
SEARCH! (Like you claim you did.)

#3821
