### ISSUE TITLE
Google Jamboard

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#5056]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

open, drive and kiosk are sourced from MIE, laser is taken from the Jamboard web app.

drive is technically a brand icon, so maybe not adding that, and kiosk is just another monitor icon, so probably not add that either. The other are quite nice though. Names to be discussed.

![grafik](https://user-images.githubusercontent.com/1309249/79747122-72ac6100-830b-11ea-9ea7-21ec6785a5af.png) ![grafik](https://user-images.githubusercontent.com/1309249/79747282-adae9480-830b-11ea-923a-12d068643525.png)
![grafik](https://user-images.githubusercontent.com/1309249/79747538-244b9200-830c-11ea-9005-b41974aa588d.png) ![grafik](https://user-images.githubusercontent.com/1309249/79747593-42b18d80-830c-11ea-9fed-42cb42679ca0.png)

## Zip Download

[jamboard.zip](https://github.com/Templarian/MaterialDesign/files/4503176/jamboard.zip)

**Comment by Templarian** [comment]
I think these are all too specific for addition. The last one might be fine as a more generalized icon.

**Comment by CoDEmanX** [comment]
- `laser` -> `laser-pointer` seems quite useful to me actually
- `open-jam` -> `open-on-screen`? It's not quite like the television or monitor icons, otherwise I would go with e.g. `monitor-open` or `monitor-share`...

**Comment by goyney** [comment]
Slightly modified the monitor one to use our monitor style and added the laser pointer.
[![monitor-share](https://materialdesignicons.com/icon/monitor-share)](https://materialdesignicons.com/icon/monitor-share)
[![laser-pointer](https://materialdesignicons.com/icon/laser-pointer)](https://materialdesignicons.com/icon/laser-pointer)
