### ISSUE TITLE
`cog` icon doesn't show up when searching `settings`

### ISSUE THREAD

**Issue by locness3** [Templarian/MaterialDesign#5057]
When searching up "settings" on the site, the `cog` icon itself doesn't appear, although its variants do.
![Screen Shot 2020-04-20 at 14 28 40](https://user-images.githubusercontent.com/37651007/79751669-4563b100-8313-11ea-8c2e-ad0403d22b23.png)

**Comment by Templarian** [comment]
@locness3 Fixed. Thanks!
