### ISSUE TITLE
ticket-percent-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#5058]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Outline version of "ticket-percent"

## Examples

![ticket-percent-outline](https://user-images.githubusercontent.com/6717356/79759368-443c7f00-8327-11ea-898b-a9ac36e0d89d.png)

**Comment by Templarian** [comment]
Added and assigned https://dev.materialdesignicons.com/history
