### ISSUE TITLE
Beekeeper

### ISSUE THREAD

**Issue by guenth39** [Templarian/MaterialDesign#5059]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

Maybe just this icon https://materialdesignicons.com/icon/account with a beekeeper head net.

Maybe something like this?
![image](https://user-images.githubusercontent.com/29251617/79751504-f584ea00-8312-11ea-850a-4e8ad31d7e52.png)
Or something like this but without the hexagon?
![image](https://user-images.githubusercontent.com/29251617/79759708-53b7ca00-831f-11ea-933f-2e66722ddc8a.png)

Or some other inspiration:
https://materialdesignicons.com/icon/account-cowboy-hat

**Comment by guenth39** [comment]
I just played a bit around and came to that idea. Maybe it helps someone find a nice solution

![Entwurf_Imker](https://user-images.githubusercontent.com/29251617/79764492-bb711380-8325-11ea-9ffd-4dcf744dfcaf.png)

**Comment by guenth39** [comment]
What do you think about this? I hope it matches the Material Guidelines.
Looking Forward to you're feedback :)

[Beekeeper.zip](https://github.com/Templarian/MaterialDesign/files/4554596/Beekeeper.zip)

**Comment by guenth39** [comment]
Maybe this is a bit better. I increased the white spaces from 1px to 1.5px

![image](https://user-images.githubusercontent.com/29251617/80716987-9be1a400-8af8-11ea-9448-cd38c5b7d20a.png)

**Comment by Templarian** [comment]
Trying to not see a monitor and I'm not sure this works even though the design should work.

Generally perspective isn't allowed for an icon to be considered "Material Design". Would have to remove the perspective (cube/database are the only ones that break this).

**Comment by guenth39** [comment]
What do you think about this?
![image](https://user-images.githubusercontent.com/29251617/81823665-d0ac1d00-9534-11ea-9956-d379caa4a070.png)

**Comment by goyney** [comment]
That's better. My two nitpicks:
- The top of the hat (the circular top) should probably be brought up to the grid.
- The gap at the bottom of the shield should also be on the grid, its blurry at native size.

**Comment by guenth39** [comment]
![image](https://user-images.githubusercontent.com/29251617/81826645-4960a880-9538-11ea-9d91-55cfd5d0132e.png)

**Comment by goyney** [comment]
Can you share your SVG please?

**Comment by guenth39** [comment]
[Beekeepr.svg.zip](https://github.com/Templarian/MaterialDesign/files/4622629/Beekeepr.svg.zip)

**Comment by goyney** [comment]
Thanks. So here's me taking a pass at aligning the icon better to the grid:
![image](https://user-images.githubusercontent.com/1015040/81828369-bc056000-9507-11ea-877c-5ba884c458ff.png)

I wanted to share it with you because you are so close and its just really hard to put into words all the little things to get it all the way there.

We'll get this added, but it won't make the next release as we just finalized it last night. So, it may be a few weeks.

[Beekeeper.svg.zip](https://github.com/Templarian/MaterialDesign/files/4622715/Beekeeper.svg.zip)

**Comment by guenth39** [comment]
I really like it! Thank you, so much for your input. Your icons always looks like a charm. I really like to playing around with the pixels but sometimes it's quite hard for a newcomer like me :D It's cool that I have the possibility to improve my skills with your input.

It’s totally fine if it's not in the current release. I can make me a font with fluttericon.com until its released :)

Thank you for your help with this :)

**Comment by goyney** [comment]
[![beekeeper](https://materialdesignicons.com/icon/beekeeper)](https://materialdesignicons.com/icon/beekeeper)
