### ISSUE TITLE
Function Icon

### ISSUE THREAD

**Issue by johnsonryan** [Templarian/MaterialDesign#507]
The typical fx but in material iconography

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/function With an scripted `x` ?

**Comment by johnsonryan** [comment]
Yeah I apologize, I just saw that icon a few minutes ago. I ended up adding a scripted x to it for my purposes, but thanks!

**Comment by CoDEmanX** [comment]
"fx" would work and is used in Adobe Flash IIRC.
I prefer the following however:
![Imgur](http://i.imgur.com/yXh6lMd.png?1)

Google's `ic_settings_ethernet` might also work, although it's more like "expand" or "code options":
![ic_settings_ethernet_24px](https://cloud.githubusercontent.com/assets/1309249/8752359/c2fdda70-2cb3-11e5-9513-6b5ab1a126c1.png)

**Comment by Templarian** [comment]
@CoDEmanX Never every language uses `{}`. So this request is still opened to add a `fx` scripted icon.

**Comment by CoDEmanX** [comment]
Sure not every language does, but `{}` is very common and should be well known by every programmer. Also, not every programming language calls functions functions (methods, routines, procedures...). Python calls functions functions, but they are written `def foobar(): ...`.

**Comment by MrGrigri** [comment]
Here is my function-variant that I am using in a project. 

![function-variant](https://cloud.githubusercontent.com/assets/4528551/21662287/282fa57a-d296-11e6-874f-84fe8888f630.png)

[function.zip](https://github.com/Templarian/MaterialDesign/files/686055/function.zip)

**Comment by Templarian** [comment]
[![function-variant](https://materialdesignicons.com/icon/function-variant)](https://materialdesignicons.com/icon/function-variant)
