### ISSUE TITLE
ladder

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#5078]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 
![kisspng-ladder-drawing-ladder-5a90990604a350 892921201519425798019](https://user-images.githubusercontent.com/59885526/79917646-de202c80-83f8-11ea-8439-f72c68854408.jpg)

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/89138610-224bbe80-d50a-11ea-914b-1a9f7d58ee9b.png)
[ladder.svg.zip](https://github.com/Templarian/MaterialDesign/files/5013470/ladder.svg.zip)

**Comment by goyney** [comment]
[![ladder](https://materialdesignicons.com/icon/ladder)](https://materialdesignicons.com/icon/ladder)
