### ISSUE TITLE
Politics

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#508]
Some inspiration:

![politics2](https://cloud.githubusercontent.com/assets/1309249/8752480/91f15aaa-2cb4-11e5-9491-9e172ddba564.jpg)
![politics3](https://cloud.githubusercontent.com/assets/1309249/8752482/93910ad6-2cb4-11e5-8fd2-33a81fad4596.jpg)
![politics1](https://cloud.githubusercontent.com/assets/1309249/8752478/90693ad6-2cb4-11e5-9837-d7c403bc858a.jpg)
![icon-worship](https://cloud.githubusercontent.com/assets/1309249/8752431/45262f98-2cb4-11e5-926a-620081e364ca.png)

The existing flag or bullhorn icons might work, but maybe there's an even better solution.

**Comment by goyney** [comment]
@CoDEmanX I think this issue either needs to be split into specific requests or closed.

Just as a note, we have the following icons that relate:
- `ballot`
- `vote`
- `donkey` - Democrat
- `elephant` - Republican
- `bank` - Town Hall
- `sign-text` - Campaign signs
- `forum` - Dialogue between people
- `check-circle` - Voted
- `format-list-checks` - Another "ballot" type icon
- `account-group` - Group of people
- `bullhorn` - Broadcasting message
- `flag`

**Comment by PeterShaggyNoble** [comment]
Given that we already have a lot of icons that can be used to represent various political concepts plus a few open issues for others and that this issue hasn't received any attention in >3 years, I think we can safely close it out.
