### ISSUE TITLE
monkey-wrench

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#5081]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 
![monkey-wrench-linear-icon-thin-line-illustration-spanner-contour-symbol-vector-isolated-outline-drawing-2AEPMEG](https://user-images.githubusercontent.com/59885526/79918166-e2991500-83f9-11ea-9fd7-215b48de4680.jpg)

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
We already have `pipe-wrench`. I've added `monkey-wrench` as an alias.
