### ISSUE TITLE
phillips-screwdriver

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#5082]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x
![maxresdefault](https://user-images.githubusercontent.com/59885526/79918568-ac0fca00-83fa-11ea-9c1e-2f9b5a41f763.jpg)
] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
We have a screwdriver. This one isn't going to be possible keeping with Material guidelines.
