### ISSUE TITLE
pitchfork

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#5083]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 
![93056773-vector-hand-drawn-pitchfork-outline-doodle-icon-pitchfork-sketch-illustration-for-print-web-mobile-a](https://user-images.githubusercontent.com/59885526/79918835-35270100-83fb-11ea-89f5-70429656d1ae.jpg)

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/80554821-54460580-899c-11ea-8395-c8fba747d380.png)

[pitchfork.svg.zip](https://github.com/Templarian/MaterialDesign/files/4549478/pitchfork.svg.zip)

Made to match the `shovel`s.

**Comment by molinaga** [comment]
Thank You!

**Comment by goyney** [comment]
[![pitchfork](https://materialdesignicons.com/icon/pitchfork)](https://materialdesignicons.com/icon/pitchfork)
