### ISSUE TITLE
rake

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#5085]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 
![rake-toy-beach-eps-vectors_csp64434137](https://user-images.githubusercontent.com/59885526/79919104-b9798400-83fb-11ea-8270-012db6f1ad20.jpg)

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/80554580-a33f6b00-899b-11ea-9c6c-53a0577417d1.png)
[rake.svg.zip](https://github.com/Templarian/MaterialDesign/files/4549463/rake.svg.zip)

**Comment by Templarian** [comment]
@molinaga Please don't close issues, the contributor team will once a design is accepted and added to the system.

**Comment by goyney** [comment]
[![rake](https://materialdesignicons.com/icon/rake)](https://materialdesignicons.com/icon/rake)
