### ISSUE TITLE
set-square

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#5087]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

![ruler_1-512](https://user-images.githubusercontent.com/59885526/79919949-4a049400-83fd-11ea-8b43-aa9c56021477.png)

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/80441226-75ddb900-88d8-11ea-9020-4a70259b0995.png)
[set-square.svg.zip](https://github.com/Templarian/MaterialDesign/files/4543084/set-square.svg.zip)

**Comment by Templarian** [comment]
Google actually has one of these called `square_foot` in their set.

**Comment by goyney** [comment]
[![set-square](https://materialdesignicons.com/icon/set-square)](https://materialdesignicons.com/icon/set-square)
