### ISSUE TITLE
sickle

### ISSUE THREAD

**Issue by molinaga** [Templarian/MaterialDesign#5089]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x
![download (2)](https://user-images.githubusercontent.com/59885526/79920053-8b953f00-83fd-11ea-84d8-b6610bdf126c.png)
] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
[![sickle](https://materialdesignicons.com/icon/sickle)](https://materialdesignicons.com/icon/sickle)[![hammer-sickle](https://materialdesignicons.com/icon/hammer-sickle)](https://materialdesignicons.com/icon/hammer-sickle)
