### ISSUE TITLE
Spotify (new)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#509]
https://materialdesignicons.com/icon/spotify is outdated, their current logo looks like this:
https://spotifypresscom.files.wordpress.com/2015/01/spotify_logo_rgb_black.png

I traced the 3 strokes and subtracted them from a perfect circle:
![spotify-new](https://cloud.githubusercontent.com/assets/1309249/8761580/c79d1dde-2d58-11e5-8479-01fbccad4eb4.png) https://dl.dropboxusercontent.com/u/39101475/MaterialDesignIcons/spotify-new.svg

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/spotify
