### ISSUE TITLE
kettle-pour-over

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#5095]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Visually show the difference between a conventional kettle and a pour over (used for making tea usually).

## Examples

For instance the one I have:

![image](https://user-images.githubusercontent.com/338885/79921433-cd22eb80-83f7-11ea-9097-cd33fcd6617e.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/79939159-feb1ac00-8423-11ea-8a5a-950d3e05b6cc.png)

Here is a literal design, but we may need to make it more simple to fit the MD style.

**Comment by imperfectsignature** [comment]
![image](https://user-images.githubusercontent.com/58486458/82733759-74a47e00-9d16-11ea-8af5-491b476304a5.png)

This one is a little more material.

**Comment by Templarian** [comment]
@imperfectsignature Can you attach a zip with this SVG. We'll need to move it 1px down probably.

**Comment by imperfectsignature** [comment]
[kettle-pour-over.zip](https://github.com/Templarian/MaterialDesign/files/4694698/kettle-pour-over.zip)

**Comment by goyney** [comment]
Adjusted and added.
