### ISSUE TITLE
Icon request: percentage

### ISSUE THREAD

**Issue by encsolutions** [Templarian/MaterialDesign#510]
Icon request: percentage (%)

**Comment by CoDEmanX** [comment]
Maybe like this, two circles and a line?
![percentage](https://cloud.githubusercontent.com/assets/1309249/8798528/3194fb52-2fa3-11e5-85b2-a5301d68168e.png)

Perhaps an even smaller one works too, which could then be placed in a polygon for the also [requested sale icon](https://github.com/Templarian/MaterialDesign/issues/324).

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/percent

**Comment by CoDEmanX** [comment]
Now that I look at it, the diagonal line appears a bit too narrow.
@Templarian: What do you think of the following alternatives?

![percentage2](https://cloud.githubusercontent.com/assets/1309249/8845459/9353ac1c-311f-11e5-9b8e-79dde9d6330e.png)
![percentage3](https://cloud.githubusercontent.com/assets/1309249/8845458/93509bda-311f-11e5-9f86-bcb229f0d75e.png) https://www.dropbox.com/s/vi4bgz7nbm19f9t/percentage.svg?dl=0

The line points are snapped to the 24x24 grid for both, unlike the original. The line in the latter is slightly longer, and my favorite.

**Comment by encsolutions** [comment]
Amazing job, thank you
