### ISSUE TITLE
Shift Planning

### ISSUE THREAD

**Issue by mohsendana2010** [Templarian/MaterialDesign#5101]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

![grafik](https://user-images.githubusercontent.com/58403209/79974387-8ede0880-8499-11ea-8220-a1a850476df3.png)

**Comment by Templarian** [comment]
@mohsendana2010 Use the issue templates when creating issues.

Any reason not to use `calendar-clock`?
