### ISSUE TITLE
motion-sensor-off

### ISSUE THREAD

**Issue by Tiebe** [Templarian/MaterialDesign#5102]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

I would like an off state of #3007

**Comment by goyney** [comment]
[![motion-sensor-off](https://materialdesignicons.com/icon/motion-sensor-off)](https://materialdesignicons.com/icon/motion-sensor-off)
