### ISSUE TITLE
Sql query

### ISSUE THREAD

**Issue by YousefGhafouri** [Templarian/MaterialDesign#5103]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
Where is your use case and examples? The icon request issue template is not optional, so I've edited it back in. Please provide that information and we can consider the request.

**Comment by YousefGhafouri** [comment]
Hello
I'm sorry,I didn't write an explanation for them, because it's a little difficult for them to explain!
Sql Query refers to the commands used to interact with the Microsoft SqlServer database.
These commands can include other commands called Sql SubQuery.
Example:
_SELECT Id, _Name,_  Family,_
          _(SELECT Address_
           _FROM PersonnelAddress_
           _WHERE _dbo.PersonnelAddress.PersonnelId_ = Personnel
           ) AS Address_
_FROM dbo.Personnel_

These commands are called Sql Suery and the part that identifies the address is called Sql SubQuery.

**Comment by Templarian** [comment]
@YousefGhafouri We know what SQL is 😄, what we needed was example images of how this could be represented. Search google for ideas if you can. Images can be pasted into GitHub comments.

**Comment by YousefGhafouri** [comment]
An example can be found for sql query, but unfortunately there is no idea for sub query.
 
![sql](https://user-images.githubusercontent.com/52343597/80064469-631c5a80-854d-11ea-8d72-20f3f698382c.png)

**Comment by JapanYoshi** [comment]
We avoid plaintext in icons in most cases. Also, the icon [`database-search`](http://materialdesignicons.com/icon/database-search) exists already, and as long as you are in an SQL related page, just [`search`](http://materialdesignicons.com/icon/search) will represent the idea just fine.

**Comment by goyney** [comment]
I have to agree with @JapanYoshi here. I think we're going to close this out. Feel free to come back with other examples if the icons he linked don't fit your use case.
