### ISSUE TITLE
"Halfwidth" is 1 word

### ISSUE THREAD

**Issue by JapanYoshi** [Templarian/MaterialDesign#5105]
One of my icons is named ``syllabary-kana-half-width``, but according to [the Unicode Consortium](https://www.unicode.org/charts/PDF/UFF00.pdf) and [Wiktionary](https://en.wiktionary.org/wiki/halfwidth), it's spelled as "halfwidth", one word. Can you rename the icon with the correct name ``syllabary-kana-halfwidth``?

**Comment by Templarian** [comment]
Fixed!
