### ISSUE TITLE
Nextcloud icon

### ISSUE THREAD

**Issue by JanOstrowka** [Templarian/MaterialDesign#5107]
Below is the suggestion of a Nextcloud icon, that could be added to the library
[nextcloud.svg.zip](https://github.com/Templarian/MaterialDesign/files/452568/nextcloud.svg.zip)
It has been created based on the [original logo](
https://upload.wikimedia.org/wikipedia/commons/6/60), but without the "Nextcloud" text, under the logo

**Comment by Templarian** [comment]
@JanOstrowka https://simpleicons.org/

We don't do brand icons anymore.

**Comment by PeterShaggyNoble** [comment]
This one is [already available from SI](https://simpleicons.org/?q=Nextcloud).

![Nextcloud](https://user-images.githubusercontent.com/15157491/80353896-ebf90600-886d-11ea-84e6-7647a618c1c6.png)
