### ISSUE TITLE
table-split-cells

### ISSUE THREAD

**Issue by Magiczne** [Templarian/MaterialDesign#5108]
There is an icon table-merge-cells made by Google so I have made a complementary icon to it.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/8850255/80204207-bc0cf100-8628-11ea-865c-ab69224920e7.png)

## Zip Download
[table-merge-cells.zip](https://github.com/Templarian/MaterialDesign/files/4528364/table-merge-cells.zip)

**Comment by goyney** [comment]
[![table-split-cell](https://materialdesignicons.com/icon/table-split-cell)](https://materialdesignicons.com/icon/table-split-cell)
