### ISSUE TITLE
Bad icon for "toy-brick-remove-outline"

### ISSUE THREAD

**Issue by rwaness** [Templarian/MaterialDesign#5109]
Hi,

Simple issue :
`toy-brick-remove-outline` is exactly the same as `toy-brick-plus-outline`
I expect that it should be similar than not outlined icons (`toy-brick-remove` and `toy-brick-plus`)

Thank you ;)

**Comment by Templarian** [comment]
@rwaness Good catch. That's on me, we'll have it fixed shortly on the site and in the next release.

**Comment by Templarian** [comment]
Fixed. Thanks again!
