### ISSUE TITLE
icon request: sort alternative symbols

### ISSUE THREAD

**Issue by pine3ree** [Templarian/MaterialDesign#511]
Would be nice to have simpler sort icons similar to fa sort symbols

http://fortawesome.github.io/Font-Awesome/icon/sort/
http://fortawesome.github.io/Font-Awesome/icon/sort-asc/
http://fortawesome.github.io/Font-Awesome/icon/sort-desc/

i am using menu-up and menu-down in place of asc and desc icons, so i guess a double caret symbol should suffice.

kind regards

**Comment by CoDEmanX** [comment]
Up and down (asc / desc) already exist:
http://www.google.com/design/icons/#ic_arrow_drop_down
http://www.google.com/design/icons/#ic_arrow_drop_up

Are they acceptable in your opinion?
Would be easy to create an up+down variant.

**Comment by pine3ree** [comment]
@CoDEmanX 
Yes i was thinking about having a symbol with both directions together with a little margin between the two. As of now I am in fact using those same symbols for up-down sort states adjusting the vertical-position. The one from fa are not centered. Having different icons (with graphically only v-pos changed) and proper names distinct from caret|menu would be also semantically more correct.

kind regards

**Comment by CoDEmanX** [comment]
Good point. So 3 icons, and maybe also a variant of http://fortawesome.github.io/Font-Awesome/icon/sort-alpha-asc/ ? I like it better than http://www.google.com/design/icons/#ic_sort_by_alpha

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #2460, which includes contributions.
