### ISSUE TITLE
puzzle-

### ISSUE THREAD

**Issue by rwaness** [Templarian/MaterialDesign#5110]
Hi,

i'm working on a modular project, where user can add some plugins, represented by `puzzle` icon , to the application.

It should be awesome to have `puzzle-plus`, `puzzle-minus`, `puzzle-remove`, `puzzle-star`, `puzzle-heart`, `puzzle-edit` (and outlined ones too).

Thank ;)

**Comment by goyney** [comment]
These have all been added.
