### ISSUE TITLE
xiaomi-mijia

### ISSUE THREAD

**Issue by Jozziej** [Templarian/MaterialDesign#5111]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usag

mdi-xiaomi-mijia
Used as icon for Xiaomi Mijia Gateway

## Examples

![image](https://user-images.githubusercontent.com/63554049/80275711-5a5d8d00-86e3-11ea-9450-5d48dc26e7a3.png)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
