### ISSUE TITLE
Chess pawn icon too simplistic

### ISSUE THREAD

**Issue by lmn8** [Templarian/MaterialDesign#5113]
The chess pawn icon is missing a [piece collar](https://en.wikipedia.org/wiki/Staunton_chess_set#Design) and is very nondescript. At a large size and next to other chess piece icons, it looks like a chess pawn. But at smaller size, it doesn't.

**Comment by Templarian** [comment]
[![chess-pawn](https://materialdesignicons.com/icon/chess-pawn)](https://materialdesignicons.com/icon/chess-pawn)
