### ISSUE TITLE
source-branch-plus

### ISSUE THREAD

**Issue by mmghv** [Templarian/MaterialDesign#5116]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon for adding a new branch, emphasizing on the `plus` sign.

## Examples

![26-04-2020 06-09-38 م](https://user-images.githubusercontent.com/5418859/80313074-2a001680-87e9-11ea-8194-046891ba29c5.jpg)

**Comment by goyney** [comment]
Added the following `source-branch` variants: `plus`, `minus`, `remove`, `sync`, `refresh`, and `check`.

**Comment by mmghv** [comment]
Awesome, thank you.
