### ISSUE TITLE
clock with hour hand

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#5118]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Love to be able to have a clock icon to follow the actual time. Hour hand suffices of course ;-)

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

simply like clock, or clock-outline with the hour hand at 1-12. Minutes could remain at always 12, or maybe even taken out?

thanks for considering

**Comment by goyney** [comment]
We rejected this in #3234.

**Comment by Mariusthvdb** [comment]
sorry I missed that.
sorry to hear too... Since this was back I 2018, wouldn't a re-consider be possible?

**Comment by Templarian** [comment]
I'm not against adding the 24 icons to represent these (with `-outline`).

@goyney ?

**Comment by goyney** [comment]
I'll get them added tonight since they're all already created.

**Comment by goyney** [comment]
These have all been added.

**Comment by Mariusthvdb** [comment]
Hi @goyney 
Can I ask a question here? Is it me or are the hour and minute hand switched on more than a few icons. Finally been able to wrap up some templates and use these fine icons to their possibilities in my frontend, I now notice the clock-time-five really is showing 12:20...

<img width="426" alt="Schermafbeelding 2020-09-01 om 17 22 31" src="https://user-images.githubusercontent.com/33354141/91872086-c21a7a80-ec77-11ea-9d1c-14c2f97dff5c.png">

same goes for quite a few others, if not all (not always very clearly visible because of the size and positions of the 2 hands)
If you'd agree, would it be at all possible to repair that?

thanks for having a look, (and adding them in the first place!, much appreciated)
