### ISSUE TITLE
Configuration in Ionic

### ISSUE THREAD

**Issue by akhilkathi97** [Templarian/MaterialDesign#5119]
How to configure this icon pack in ionic angular?

**Comment by Templarian** [comment]
@akhilkathi97 Never used ionic, but does the http://dev.materialdesignicons.com/getting-started/angular apply to ionic? Or do they have a custom icon handler?

**Comment by Templarian** [comment]
@akhilkathi97 Context on how you configured this for iconic. It might be helpful for others using Iconic. You don't have to write any docs, but if you could give an idea one of our core members could help write formal docs if we have a starting point.
