### ISSUE TITLE
Search is extremely freezing 

### ISSUE THREAD

**Issue by janindu2r** [Templarian/MaterialDesign#5120]
When performing a search site get frozen and unresponsive

**Comment by Templarian** [comment]
@janindu2r A new site is under works right now to fix this. We've introduced a lot more aliases that are slowing down things.

Please use the Chrome / Firefox extension for now: https://chrome.google.com/webstore/detail/materialdesignicons-picke/edjaedpifkihpjkcgknfokmibkoafhme

We're also seeing a uptick in traffic with more projects making things worse.
