### ISSUE TITLE
Save & Close Icon

### ISSUE THREAD

**Issue by yusifk88** [Templarian/MaterialDesign#5121]
I have:

i wish there were icons such us save & close and save & clear.
thanks for the good work out there

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
in a form where i can provide the user with the option to save and close the form or save and clear the form for another input 

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@yusifk88 Please include examples. Images can be pasted into your edited comment above. The template sections are not optional.

**Comment by goyney** [comment]
We haven't heard back on this in over a week, so I'm going to close this issue. If you have some suggestions on what this might possibly look like, feel free to comment back.
