### ISSUE TITLE
(home-)import-(outline) pointing left

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#5122]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

showing the im/export of solar produced energy I now have to use either set of mentioned icons, which unfortunately points to the fixed position of the consuming household in the graphical card provided in HA.

it would make it visually much clearer to be able to use the icons flipped vertically, and have the arrow point left.

## Examples

Include any example images so we know what the icon should look like.

<img width="423" alt="Schermafbeelding 2020-04-29 om 12 24 17" src="https://user-images.githubusercontent.com/33354141/80585895-5fd51300-8a14-11ea-8559-14a38566a23c.png">

as you can see here, the arrow is pointing towards the home icon, but it is exporting

<img width="448" alt="Schermafbeelding 2020-04-29 om 12 25 07" src="https://user-images.githubusercontent.com/33354141/80585978-8004d200-8a14-11ea-8cdd-e767c026d904.png">

same goes for importing.

would be very cool if we could have the im/exporting icons sets flipped too
(cant change the rest of the card as that is fixed...and cant use the helper classes, as discussed before)

thanks for considering!

**Comment by goyney** [comment]
This is not something we're likely to do as it breaks the pattern for all of our other import/export icons. I'd suggest using CSS to flip the icons yourself.
