### ISSUE TITLE
"pin-off" and "pin-off-outline" slight pixel offset

### ISSUE THREAD

**Issue by Triction** [Templarian/MaterialDesign#5125]
Hello, I've noticed that the icons "pin-off" and "pin-off-outline" are both slightly offset to the right via 2 pixels (assuming the pin to be the center).
See below for example.

![PixelOffsetZoomed](https://user-images.githubusercontent.com/2709207/80854648-b9feef80-8c31-11ea-8481-be069d1e2a7b.png)

Thank you.

**Comment by goyney** [comment]
Our `pin`s are perfectly aligned to the grid and centered.

![image](https://user-images.githubusercontent.com/1015040/80867718-a9676d00-8c63-11ea-8d53-eb4d0b9ebe5b.png)
