### ISSUE TITLE
printer-search / printer-eye

### ISSUE THREAD

**Issue by YousefGhafouri** [Templarian/MaterialDesign#5126]
![printer](https://user-images.githubusercontent.com/52343597/80871008-5fac7000-8cbf-11ea-8373-cdc67b722cd7.png)

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples
A combination of magnify and printer
![printer](https://user-images.githubusercontent.com/52343597/80871022-7226a980-8cbf-11ea-9cc5-121c1e645b63.png)
![magnify](https://user-images.githubusercontent.com/52343597/80871037-7fdc2f00-8cbf-11ea-8e60-6305645eddc8.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/80871372-30274480-8c7a-11ea-8a83-f78a283a1282.png)
[printer.svg.zip](https://github.com/Templarian/MaterialDesign/files/4568410/printer.svg.zip)

**Comment by Templarian** [comment]
@goyney Move the magnifying glass down 1 pixel.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/80871539-336f0000-8c7b-11ea-8e55-542cf12a6987.png)
[printer.svg.zip](https://github.com/Templarian/MaterialDesign/files/4568439/printer.svg.zip)

**Comment by Templarian** [comment]
Thanks for adjusting that, yeah. Good addition.

**Comment by YousefGhafouri** [comment]
The combination of these two icons can also be good...
![printer](https://user-images.githubusercontent.com/52343597/80873215-26c6c800-8ccc-11ea-9629-f26276ec5872.png)
![eye-outline](https://user-images.githubusercontent.com/52343597/80873218-2cbca900-8ccc-11ea-9e24-5120e757d3b6.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/80873451-a16cf480-8c86-11ea-85bf-6f79019d2a2d.png)
[printer.svg.zip](https://github.com/Templarian/MaterialDesign/files/4568602/printer.svg.zip)

**Comment by YousefGhafouri** [comment]
Hello
Are these two icons added to the Material Design icon collection?

**Comment by goyney** [comment]
Not yet, we'll close this issue when they're added and then they will go out in our next release, which is likely in the next couple weeks.

**Comment by YousefGhafouri** [comment]
> Not yet, we'll close this issue when they're added and then they will go out in our next release, which is likely in the next couple weeks.

Tanks

**Comment by goyney** [comment]
[![printer-search](https://materialdesignicons.com/icon/printer-search)](https://materialdesignicons.com/icon/printer-search)[![printer-eye](https://materialdesignicons.com/icon/printer-eye)](https://materialdesignicons.com/icon/printer-eye)
