### ISSUE TITLE
content-save-cog

### ISSUE THREAD

**Issue by YousefGhafouri** [Templarian/MaterialDesign#5127]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples
A combination of magnify and printer
![content-save](https://user-images.githubusercontent.com/52343597/80919977-1f61f600-8d82-11ea-8b50-13f981da82a8.png)
![cog](https://user-images.githubusercontent.com/52343597/80919979-238e1380-8d82-11ea-9661-86008c178c11.png)

**Comment by goyney** [comment]
[![content-save-cog](https://materialdesignicons.com/icon/content-save-cog)](https://materialdesignicons.com/icon/content-save-cog)[![content-save-cog-outline](https://materialdesignicons.com/icon/content-save-cog-outline)](https://materialdesignicons.com/icon/content-save-cog-outline)
