### ISSUE TITLE
restore-cog

### ISSUE THREAD

**Issue by YousefGhafouri** [Templarian/MaterialDesign#5128]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples
A combination of magnify and printer

![cog](https://user-images.githubusercontent.com/52343597/80919999-43253c00-8d82-11ea-8234-fad091490a00.png)
![restore](https://user-images.githubusercontent.com/52343597/80920003-45879600-8d82-11ea-8412-801007490b28.png)

**Comment by goyney** [comment]
Are you looking for `cog-counterclockwise`?

[![cog-counterclockwise](https://materialdesignicons.com/icon/cog-counterclockwise)](https://materialdesignicons.com/icon/cog-counterclockwise)

**Comment by YousefGhafouri** [comment]
> Are you looking for `cog-counterclockwise`?
> 
> [![cog-counterclockwise](https://camo.githubusercontent.com/cc47919dd70d6becfc98b9363f1450956037fb05/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f636f672d636f756e746572636c6f636b77697365)](https://materialdesignicons.com/icon/cog-counterclockwise)

Hello
I searched a lot and didn't find it; I didn't expect it to have such a name at all!

**Comment by goyney** [comment]
I could see a use case for a "settings refresh" though that follows our current pattern.
![image](https://user-images.githubusercontent.com/1015040/81112086-1db44180-8eec-11ea-94fa-a298cfc89e82.png)![image](https://user-images.githubusercontent.com/1015040/81112104-2442b900-8eec-11ea-832c-613890c75524.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4583432/Archive.zip)

**Comment by goyney** [comment]
Or a "settings sync":
![image](https://user-images.githubusercontent.com/1015040/81112314-7388e980-8eec-11ea-8d22-df6b91d95672.png)![image](https://user-images.githubusercontent.com/1015040/81112331-7a176100-8eec-11ea-9124-647ae5da0367.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4583438/Archive.zip)

**Comment by goyney** [comment]
Those four variations have been added.
