### ISSUE TITLE
star-cog

### ISSUE THREAD

**Issue by YousefGhafouri** [Templarian/MaterialDesign#5129]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples
A combination of magnify and printer

![cog](https://user-images.githubusercontent.com/52343597/80920026-6819af00-8d82-11ea-909c-0f6f6fb3ffcb.png)
![star-outline](https://user-images.githubusercontent.com/52343597/80920027-6a7c0900-8d82-11ea-8a82-cfe5c34b74d6.png)

**Comment by Templarian** [comment]
- [ ] `star-cog`
- [ ] `star-cog-outline`
- [ ] `heart-cog`
- [ ] `heart-cog-outline`
- [ ] `heart-settings`
- [ ] `heart-settings-outline`

**Comment by goyney** [comment]
I don't think these work.

![image](https://user-images.githubusercontent.com/1015040/81366863-ac29ee00-90b9-11ea-9dc0-514ec9f1d43c.png)

**Comment by YousefGhafouri** [comment]
It can be a good option if the star and cog location are also changed.

**Comment by Xenomorph99** [comment]
I don't see a problem with adding the "cog" modifier. I matched the same specs as [folder-cog](https://materialdesignicons.com/icon/folder-cog). `star-cog-outline` gets a little "sharp" but I think it works.

![star-cog](https://user-images.githubusercontent.com/1837101/94225189-9161e580-feb1-11ea-8d69-38ae50a134da.png)
![star-cog-outline](https://user-images.githubusercontent.com/1837101/94225188-9161e580-feb1-11ea-8c59-403ee1f84f8b.png)
![heart-cog](https://user-images.githubusercontent.com/1837101/94225181-9030b880-feb1-11ea-8958-fe0d4b221220.png)
![heart-cog-outline](https://user-images.githubusercontent.com/1837101/94225178-8f982200-feb1-11ea-86bb-40a188538b5a.png)

For the "settings" modifier, I left the icon in its original position. Should I shift it up 1 or 2 dps or leave it as I've got here?

![star-settings](https://user-images.githubusercontent.com/1837101/94225191-91fa7c00-feb1-11ea-96e0-0d59acfcb9d9.png)
![star-settings-outline](https://user-images.githubusercontent.com/1837101/94225190-9161e580-feb1-11ea-9c61-d4c0fb282c7e.png)
![heart-settings](https://user-images.githubusercontent.com/1837101/94225185-90c94f00-feb1-11ea-83c6-455ce029a736.png)
![heart-settings-outline](https://user-images.githubusercontent.com/1837101/94225183-90c94f00-feb1-11ea-8da7-191b5f89d57f.png)

[star-and-heart-settings.zip](https://github.com/Templarian/MaterialDesign/files/5280536/star-and-heart-settings.zip)

**Comment by Templarian** [comment]
Added. 👍
