### ISSUE TITLE
Empty Icon

### ISSUE THREAD

**Issue by Kasheftin** [Templarian/MaterialDesign#5130]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It would be nice to have an empty icon, just a viewBox without anything inside. Some frameworks (vuetify) use their own mechanics & attributes to set the icon size, etc. Sometimes some space has to be occupied to show the icon dynamically. Currently, I use just any icon + opacity: 0. It would be more convenient to use mdiEmpty for this case.

**Comment by goyney** [comment]
If you're using the webfont (which you absolutely should not be using), there is `mdi-blank`. If you're using anything else, it is up to you to create that placeholder.

**Comment by Templarian** [comment]
If you need an empty just pass an empty string. The webfont is actually using `mdiSolid` with visibility toggled.

This is not something were going to include as it's not really a glyph.
