### ISSUE TITLE
Alert outline add / remove

### ISSUE THREAD

**Issue by itaross** [Templarian/MaterialDesign#5131]
alert-outline is already existing, but is missing plus and minus, so I have improved the design with two more icons

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/695970/80972184-1b83b180-8e1e-11ea-8828-0b1e1b1ac43f.png)

![alert-outline-plus](https://user-images.githubusercontent.com/695970/80972448-68678800-8e1e-11ea-8fcb-b131d9aab2a4.jpg)

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download
[alert-outline.zip](https://github.com/Templarian/MaterialDesign/files/4574998/alert-outline.zip)

**Comment by Templarian** [comment]
Since we only the same overlay for all icons it would look like below. Not a huge fan of moving the plus symbol against the edge, but only way to prevent the cutout.

![image](https://user-images.githubusercontent.com/338885/81262089-c94fb580-9002-11ea-953d-d7956dbc5046.png)![image](https://user-images.githubusercontent.com/338885/81262123-d79dd180-9002-11ea-9828-885ae49b4fab.png)

**Comment by itaross** [comment]
Yes, unfortunately I had to figure out where to put the plus, but I had no better ideas than using all the available space for this one.

**Comment by goyney** [comment]
Added the plus/minus outlines and attributed them to the generic contributor account. @itaross, when you hit 5 icons added, we'll reassign them to you.

Added plus/minus/remove of alert and also remove out alert outline as well.

**Comment by itaross** [comment]
> Added the plus/minus outlines and attributed them to the generic contributor account. @itaross, when you hit 5 icons added, we'll reassign them to you.
> 
> Added plus/minus/remove of alert and also remove out alert outline as well.

Great! I will try to contribute more then and helping with the good job you are doing
