### ISSUE TITLE
minus-circle-off-outline

### ISSUE THREAD

**Issue by mueller-ma** [Templarian/MaterialDesign#5132]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A crossed out version of minus-circle-outline. Outline version of https://materialdesignicons.com/icon/do-not-disturb-off

## Examples

It can be used as "Do not disturb is turned off".

**Comment by goyney** [comment]
[![minus-circle-off](https://materialdesignicons.com/icon/minus-circle-off)](https://materialdesignicons.com/icon/minus-circle-off)[![minus-circle-off-outline](https://materialdesignicons.com/icon/minus-circle-off-outline)](https://materialdesignicons.com/icon/minus-circle-off-outline)

**Comment by mueller-ma** [comment]
Thanks!
You could deduplicate do-not-disturb and minus-circle and their "off" versions.

**Comment by goyney** [comment]
Would you look at that, we have duplicate icons. Reopening this issue.

We need to remove and replace the following icons:

- `do-not-disturb`
- `do-not-disturb-off`

These have already been added as aliases to `minus-circle` and `minus-circle-off`.

**Comment by mueller-ma** [comment]
Me? I don't know how to do that. Just remove the icons or do I need to document it somewhere, because it's a breaking change?
