### ISSUE TITLE
lightbulb-auto

### ISSUE THREAD

**Issue by herrsackbauer** [Templarian/MaterialDesign#5133]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

to indicate that a light is controlled/switched by an automation (in "auto-mode") instead of manually.

## Examples

similar to 
![image](https://user-images.githubusercontent.com/64155998/80982525-bd5dcb00-8e2b-11ea-84aa-453573621989.png) "brightness-auto"
or
![image](https://user-images.githubusercontent.com/64155998/80982570-ccdd1400-8e2b-11ea-90ce-e7b0675a63cc.png) "flash-auto"

![image](https://user-images.githubusercontent.com/64155998/80982710-f9912b80-8e2b-11ea-87ad-cc1e35688983.png) the lightbulb-icon
 with the letter "A" inside

**Comment by Templarian** [comment]
What about a sensor + light type of design. I'm kind of 50/50 on the idea of `lightbulb-auto`, but I realize that not all "auto" implementations are triggered by a "sensor".

- `motion-sensor` + `lightbulb`
- `lightbulb-auto`

**Comment by herrsackbauer** [comment]
The sensor + light icon is definitely a good idea, as a light triggered by a motion sensor is a 
very common implementation.
However, a more generic `lightbulb-auto` icon could fit for the above case as well as for others.
It makes sense to have both, but from my side the priority for `lightbulb-auto` would be slightly higher.

**Comment by goyney** [comment]
`lightbulb-auto-outline` won't work, so I think we'll need a different way of depicting this.

**Comment by goyney** [comment]
Perhaps putting the `A` next to the bulb is okay? We have precedence for it.

![image](https://user-images.githubusercontent.com/1015040/130816795-49047ae1-089d-4c54-83e7-33f7390d649c.png)![image](https://user-images.githubusercontent.com/1015040/130816825-f7d2bb5f-b0b2-4284-a49a-193c0417ed25.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7048059/Archive.zip)

**Comment by goyney** [comment]
[![lightbulb-auto](https://materialdesignicons.com/icon/lightbulb-auto)](https://materialdesignicons.com/icon/lightbulb-auto)[![lightbulb-auto-outline](https://materialdesignicons.com/icon/lightbulb-auto-outline)](https://materialdesignicons.com/icon/lightbulb-auto-outline)
