### ISSUE TITLE
Watering Can

### ISSUE THREAD

**Issue by guenth39** [Templarian/MaterialDesign#5134]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Hope it follows the guidelines, it's my first try to build a material icon, so I'm looking forward to you're feedback :)

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/29251617/81086791-40992280-8ef9-11ea-878d-2cc07d321b7a.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[watering-can.svg.zip](https://github.com/Templarian/MaterialDesign/files/4581987/watering-can.svg.zip)

**Comment by goyney** [comment]
I like it, but there are some minor things I think we'd like to see adjusted before addition. The half-circle for the spout should be on grid and the area where the handle meets the back of the can can probably have the rounded corner removed to simplify the path.

**Comment by guenth39** [comment]
Hey :)
Thank you for your feedback! I tried to fix these two things. Hope I got the thing with the spout right. 
![image](https://user-images.githubusercontent.com/29251617/81117126-e1520700-8f26-11ea-909f-f5ca0e730e66.png)

if you prefer we could also make the spout linear:
![image](https://user-images.githubusercontent.com/29251617/81117016-ae0f7800-8f26-11ea-93e6-6147fc85db15.png)

**Comment by Templarian** [comment]
The first one looks nicer with the larger spout.

Do we need a filled version?

**Comment by goyney** [comment]
Yep, this should be the outlined version for sure.

**Comment by guenth39** [comment]
Filled version could be easily like this:
![image](https://user-images.githubusercontent.com/29251617/81118565-6e965b00-8f29-11ea-82a1-d9351d3130d3.png)

**Comment by guenth39** [comment]
Can you maybe have a look into my beekeeper #5059  as well?

**Comment by goyney** [comment]
@guenth39 Need the source SVG of the filled and outlined cans to add them.

**Comment by guenth39** [comment]
Hope the file format is correct :)

![image](https://user-images.githubusercontent.com/29251617/81429913-d4b7f380-915e-11ea-93d6-068a446e2b97.png)
[watering-can.svg.zip](https://github.com/Templarian/MaterialDesign/files/4600480/watering-can.svg.zip)

![image](https://user-images.githubusercontent.com/29251617/81430102-295b6e80-915f-11ea-9aeb-ed7a073fbc2c.png)
[watering-can-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/4600488/watering-can-outline.svg.zip)

**Comment by goyney** [comment]
Both added. They're assigned to the global contributor account for now. When you hit 5 icons added, we'll reassign them to you. Thanks for the contributions!
[![watering-can](https://materialdesignicons.com/icon/watering-can)](https://materialdesignicons.com/icon/watering-can)[![watering-can-outline](https://materialdesignicons.com/icon/watering-can-outline)](https://materialdesignicons.com/icon/watering-can-outline)
