### ISSUE TITLE
download-circle

### ISSUE THREAD

**Issue by jordyamc** [Templarian/MaterialDesign#5136]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

When using the icon on images

## Examples

Like the delete-circle icon, but for downloads

![imagen](https://user-images.githubusercontent.com/6831873/81137059-03498a80-8f23-11ea-8e10-5ff8d33ea82e.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/81141818-5cb9b580-8f33-11ea-85ad-48fe887965fe.png) ![image](https://user-images.githubusercontent.com/338885/81141742-2b40ea00-8f33-11ea-9e01-4e6bfe16003e.png)

This uses half pixels to render with a correct look.

**Comment by Templarian** [comment]
Added. 👍
