### ISSUE TITLE
kitchen/bathroom tap/sink/wash basin

### ISSUE THREAD

**Issue by wojtek14a** [Templarian/MaterialDesign#5137]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In Home Assistant I have a smart plug that powers on small kitchen water heater for kitchen sink (no domestic hot water). I would like to picture this entity with something more kitchen-ish than `water-pump`.

### Type one
![one](https://st2.depositphotos.com/1495079/12193/v/950/depositphotos_121935240-stock-illustration-faucet-sign-icon.jpg)
![two](https://as2.ftcdn.net/jpg/01/99/88/13/1000_F_199881396_tFwnAHiB4edqYXs0fFnhzYq0wbuPm8XW.jpg)

### Type two
![three](https://image.flaticon.com/icons/png/512/129/129244.png)
![four](https://cdn2.vectorstock.com/images/1000x1000/33/51/26163351.jpg)
![five](https://cdn2.iconfinder.com/data/icons/elasto-sanitary-engineering/26/05-ELASTOFONT-SANITARY-ENGINEERING-READY_faucet-kitchen-512.png)

**Comment by goyney** [comment]
We have `water-pump`. Aliases were added to make this easier to find in the future.
[![water-pump](https://materialdesignicons.com/icon/water-pump)](https://materialdesignicons.com/icon/water-pump)

**Comment by wojtek14a** [comment]
I don't quite agree that it is the same use case, as I've mentioned before I did a research (3 ticks at the beginning of feature request) and I know about `water-pump` but it's too much ?industrial? to use in kitchen (hence my comment about something more *kitchen-ish*.
I believe `water-pump` would be good for an outside spigot (but not ideal) but either bathroom or kitchen tap/faucet in my opinion should be a separate icon. 
What do you think?

**Comment by Templarian** [comment]
@wojtek14a / @Aryankids This shouldn't have been closed. There needs to be a more kitchen'esk design for this.

**Comment by goyney** [comment]
Not an exact answer to this issue, but a related icon was added in v6.2.

[![countertop](https://materialdesignicons.com/icon/countertop)](https://materialdesignicons.com/icon/countertop)[![countertop-outline](https://materialdesignicons.com/icon/countertop-outline)](https://materialdesignicons.com/icon/countertop-outline)

**Comment by goyney** [comment]
Here's a couple faucet attempts based on the examples provided:

![image](https://user-images.githubusercontent.com/1015040/159106333-758da2e9-74b6-42a1-b71b-d59171e8cac1.png)
![image](https://user-images.githubusercontent.com/1015040/159106328-09ab5ff5-3ca4-48c7-857d-d940ab87ec41.png)
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/8308556/Archive.zip)

**Comment by goyney** [comment]
[![faucet](https://materialdesignicons.com/icon/faucet)](https://materialdesignicons.com/icon/faucet)[![faucet-variant](https://materialdesignicons.com/icon/faucet-variant)](https://materialdesignicons.com/icon/faucet-variant)
