### ISSUE TITLE
Flour / Sugar

### ISSUE THREAD

**Issue by aemirdnr** [Templarian/MaterialDesign#5138]
- [+] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.

- [+] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'll use on my project for a button icon.

## Examples

![bag_wheat_rye_grain_farming_agriculture_flour-512](https://user-images.githubusercontent.com/53477261/81362478-a51ad400-90e9-11ea-8ce4-8215633a3465.png)

![depositphotos_44446059-stock-illustration-sugar-bag](https://user-images.githubusercontent.com/53477261/81362542-c67bc000-90e9-11ea-941e-f45b702edec4.jpg)

**Comment by goyney** [comment]
See the discussion here: https://github.com/Templarian/MaterialDesign/issues/4954#issuecomment-620338633

We have a few icons already to support this use case.
