### ISSUE TITLE
text-box-double-check

### ISSUE THREAD

**Issue by italowaxman** [Templarian/MaterialDesign#5139]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our preview generator.

![image](https://user-images.githubusercontent.com/2953435/81419867-5be87580-9125-11ea-9ee6-addd89da5ff0.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[text-box-double-check.zip](https://github.com/Templarian/MaterialDesign/files/4599851/text-box-double-check.zip)

**Comment by Templarian** [comment]
Thanks for the contribution, but going to close this as too niche of an overlay.

By the way thanks for following the template guidelines.
