### ISSUE TITLE
text-box-chassi-car

### ISSUE THREAD

**Issue by italowaxman** [Templarian/MaterialDesign#5140]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/2953435/81420896-02814600-9127-11ea-9697-546d7d78bacb.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[text-box-chassi-car.zip](https://github.com/Templarian/MaterialDesign/files/4599918/text-box-chassi-car.zip)

**Comment by Templarian** [comment]
@italowaxman Can you give a use case that this icon fulfills? Icons generally work with a `<noun>-<modifier>` style. Like `car-check` could be used for auto apps.

If this is for car details the car should be the main icon and the text/document should be the modifier.

`car-<modifier>` and see if we have an existing overlay/modifier that could be used.

**Comment by italowaxman** [comment]
@Templarian this icon will be use to represent a informations of car chassis after its unlocked.

After your sugestion, maybe the name of icon is **car-info-chassi**. What do tou think?

**Comment by goyney** [comment]
`car-info` should suffice for this use case.
[![car-info](https://materialdesignicons.com/icon/car-info)](https://materialdesignicons.com/icon/car-info)

**Comment by italowaxman** [comment]
But the focus in this case is not a car, its the chassi information, cause this we use the list-text to represent this and the car to contextualize these informations.

**Comment by Templarian** [comment]
The main noun is car so it would be the large main icon. The modifier needs to represent `chassis` which is probably not viable at such a small size, so general information icon would probably be best. The `-details` list modifier or `-text` modifier.

Will say though `car-info` is probably best.

**Comment by italowaxman** [comment]
In my specific case of use, we decided to extend the "text-box" icon to represent all possibility status about chassi. Cause this, we understand to use the "list-box" with the main element.

Look at this example of used icons:

<img width="1171" alt="Captura de Tela 2020-05-08 às 13 13 01" src="https://user-images.githubusercontent.com/2953435/81425328-c1d8fb00-912d-11ea-8cd1-646be90a8fda.png">

**Comment by goyney** [comment]
Sorry, but this would be a custom icon to your application then. It really doesn't fit within the scope of MDI as a whole and is very niche.

**Comment by JamesCoyle** [comment]
I don't want to be mean but that is a terrible idea. The whole point of icons is to make them easily recognisable. You've just made all of those options look the same at a glance so the icons are useless for quickly identifying them.

**Comment by JapanYoshi** [comment]
In that menu, you should remove the ``page`` part to all but the first tab ("Resultados"), because it is redundant. Context should suffice for the document part; you are showing a document, after all. Just use ``plus``, ``check``, ``check-all``, and ``currency-usd`` for the rest.
