### ISSUE TITLE
Plus Minus variants

### ISSUE THREAD

**Issue by HassanMehmood1992** [Templarian/MaterialDesign#5142]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The Icon will be used in pricing/days calculation like + 1 day / -2 days

## Examples

Icon should be +/-

**Comment by JapanYoshi** [comment]
[``plus``](http://materialdesignicons.com/icon/plus) and [``minus``](http://materialdesignicons.com/icon/minus) exist, and are Google stock icons. If this is not what you mean, please elaborate.

**Comment by Templarian** [comment]
@JapanYoshi They mean +/- like with a slash. Not at my computer but it might existed with another name.

**Comment by JapanYoshi** [comment]
[``plus-minus``](http://materialdesignicons.com/icon/plus-minus) is also a thing.

**Comment by goyney** [comment]
[![plus-minus](https://materialdesignicons.com/icon/plus-minus)](https://materialdesignicons.com/icon/plus-minus)[![plus-minus-box](https://materialdesignicons.com/icon/plus-minus-box)](https://materialdesignicons.com/icon/plus-minus-box)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/81516324-19799100-92fd-11ea-810b-413340647d8a.png)

Above is probably what they were talking about @goyney / @JapanYoshi

**Comment by HassanMehmood1992** [comment]
That's right .. if you can increase the angle of / that would be great in my opinion

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/81531688-c9b0bf00-9328-11ea-84ee-6a0fbeedf455.png)

@HassanMehmood1992 Reopening this issue. I think this icon makes sense for niche cases where a mathematical symbol might not work.

**Comment by HassanMehmood1992** [comment]
Yes that's correct. Its more general and can be in many designs

**Comment by Templarian** [comment]
@HassanMehmood1992 We'll close this once we decide if it will be included. Thanks.

**Comment by goyney** [comment]
Let's add it, @Templarian share the SVG.

**Comment by Templarian** [comment]
Added.
