### ISSUE TITLE
Anchor (replace ours with Google's)

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#5144]
From MIE v58. I like the design better than mine. Cleaned up the path data a bit.

## Preview

![image](https://user-images.githubusercontent.com/7819991/81532444-ac014b00-9364-11ea-9577-10050d2480af.png)

## Zip Download

[anchor.zip](https://github.com/Templarian/MaterialDesign/files/4607957/anchor.zip)

**Comment by goyney** [comment]
Done.
