### ISSUE TITLE
Farm tractor (agriculture)

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#5145]
From MIE, cleaned up. We already have `tractor`, which fits really well to the other vehicle icons. Therefore I would like to see this added as `tractor-variant`.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/7819991/81532839-65602080-9365-11ea-90d5-9901ab169bfb.png)

## Zip Download

[agriculture.zip](https://github.com/Templarian/MaterialDesign/files/4607979/agriculture.zip)

**Comment by Templarian** [comment]
Do we think this adds enough. The current tractor icon might be good enough as it represents a "modern" tractor.

**Comment by Simran-B** [comment]
Google's name for this tractor is agriculture, which it represent very well IMO. The modern tractor represents the vehicle as such very well and I would expect to see it on a street sign, but it's too clean and contemporary to represent "old-school" agriculture.

**Comment by goyney** [comment]
[![tractor-variant](https://materialdesignicons.com/icon/tractor-variant)](https://materialdesignicons.com/icon/tractor-variant)
