### ISSUE TITLE
Rhombus et al with <2dp outline strokes

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#5146]
The outline of `alert-rhombus-outline` is 1.697dp instead of 2dp:

![alert-rhombus-outline](https://user-images.githubusercontent.com/1309249/80312388-426e3200-87e5-11ea-90ac-96b3ec169ca3.png)

Affected icons that I'm aware of:

- alert-rhombus-outline
- ~closed-caption-outline~ (1.5dp, thicker stroke would get too close to text)
- dice-d8-outline
- dice-d10-outline
- help-rhombus-outline
- rhombus-outline

The filled icons need to be updated as well for a proper corner radius 2dp.

![image](https://user-images.githubusercontent.com/7819991/81537439-7876ee80-936d-11ea-9b2d-415c8ccdda8c.png) ![image](https://user-images.githubusercontent.com/7819991/81537501-95abbd00-936d-11ea-89e6-1886fbe470c6.png)
![image](https://user-images.githubusercontent.com/7819991/81537611-c1c73e00-936d-11ea-9337-aceb22f930be.png) ![image](https://user-images.githubusercontent.com/7819991/81537666-d7d4fe80-936d-11ea-91d3-83e0802023df.png)

`10` repositioned to keep it legible (still on grid, but now aligned to bottom and right of zero instead of left and top):

![image](https://user-images.githubusercontent.com/7819991/81537728-efac8280-936d-11ea-9f3a-f0809b872554.png) ![image](https://user-images.githubusercontent.com/7819991/81537770-00f58f00-936e-11ea-836a-1f2a06a591c6.png)
![image](https://user-images.githubusercontent.com/7819991/81537852-1ec2f400-936e-11ea-8cb2-ebc14b40ed3a.png) ![image](https://user-images.githubusercontent.com/7819991/81537902-3306f100-936e-11ea-95be-654bc8b4cd7a.png)

New outline variant:

![image](https://user-images.githubusercontent.com/7819991/81537988-5a5dbe00-936e-11ea-99b5-55f4823f4724.png) ![image](https://user-images.githubusercontent.com/7819991/81538182-af99cf80-936e-11ea-8c2d-2f77dbc07c69.png)
![image](https://user-images.githubusercontent.com/7819991/81538245-c8a28080-936e-11ea-8f14-b1b3b9e0051e.png) ![image](https://user-images.githubusercontent.com/7819991/81538293-dc4de700-936e-11ea-93d2-9d789288aea0.png)

New outline variant:

![image](https://user-images.githubusercontent.com/7819991/81538335-ec65c680-936e-11ea-8c04-2e32fc469ea5.png) ![image](https://user-images.githubusercontent.com/7819991/81538395-01425a00-936f-11ea-9ae4-fe256dc35df4.png)

### Download

[rhombus.zip](https://github.com/Templarian/MaterialDesign/files/4608328/rhombus.zip)

**Comment by Templarian** [comment]
Yeah, all of these need to be updated.

Note: Like a regular rectangle make sure the curved corners only have 2 points each and not 3 on the outer line.

**Comment by goyney** [comment]
All updated and 2 new added.
