### ISSUE TITLE
Hands icons - on grid or not on grid? Placement? Shape & finger length?

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#5147]
Google's hand icons are inconsistent:

**A**: 12.5 four finger total width, 2.5 fingers with ~0.83 gaps (e.g. `hand-right`)
**B**: 13.0 four finger total width, ~2.5 fingers with ~1.0 gaps (like in `wash`)

![image](https://user-images.githubusercontent.com/7819991/81550755-f98bb100-9380-11ea-9200-7e398557324b.png)

![image](https://user-images.githubusercontent.com/7819991/81551278-dd3c4400-9381-11ea-8022-63bf893dbc9a.png)

A with orientation lines (mostly off grid):

![image](https://user-images.githubusercontent.com/7819991/81550566-ba5d6000-9380-11ea-85a6-202694bc3b5c.png)

B with orientation lines (either on grid or in the center between two grid lines):

![image](https://user-images.githubusercontent.com/7819991/81551807-c0544080-9382-11ea-83bf-ca84289fba51.png)

There are a few things to consider here:

1. **Anti-aliasing**:
   - A: `hand-right`
     ![hand1](https://user-images.githubusercontent.com/7819991/81552746-4e7cf680-9384-11ea-94cf-a9b4ba1920f4.png)
     At 1x, the ring finger is blurry, which makes the gap between index and middle finger look slightly larger than the other ones.
     At 2x, the gap between middle and ring finger is smaller than the rest
   - B: `wash` without water drops and rotated
     ![hand2](https://user-images.githubusercontent.com/7819991/81552753-5177e700-9384-11ea-8b15-fac2bb33420f.png)
     At 1x, the gaps between index and middle finger and between ring and little finger are blurry and look smaller.
     At 2x, all gaps look equally wide.

2. **Outline variants**:
   The new MIE `hand-gesture` icon is an outline version with modifier.
   11.5 four finger total width, 1.5 stroke width and ~1.0 gaps.
   It is similar to B in terms of pixel-perfect grid alignment.

   ![image](https://user-images.githubusercontent.com/7819991/81553588-a7995a00-9385-11ea-83ae-12716ab6de54.png)

3. **New Variants**:
   A filled version of `hand-gesture` would leave too little space for the outline variant modifiers.
   See how the top left star touches the red index finger:

   ![image](https://user-images.githubusercontent.com/7819991/81554138-8d13b080-9386-11ea-85e5-2ccaab1eea0f.png)

   The current `hand-right` icon is 0.5 narrower, so there would be small gap, but actually still too small as per the MD guidelines. Possible solutions:
   - shrink the star(s)
   - move the upper star 1 to the left (canvas border)
   - move hand and lower star 1 to the right (but what about the base icon? would be too close to right border without modifier on the left, use different alignments?)
   - cut out a small part of the index finger

4. **Shape & finger length**:
   The fingers in the `wash` icon (red) are longer than they are currently in `hand-right` (gray). The thumb is in a different angle. 

   ![image](https://user-images.githubusercontent.com/7819991/81554806-b5e87580-9387-11ea-84ab-1103e622ba48.png)

   The `hand-gesture` icon has the thumb at a slightly steeper angle and it's quite a bit shorter than the other two:

   - `hand-gesture` (gray) vs `hand-right` (red):
   ![image](https://user-images.githubusercontent.com/7819991/81555166-58a0f400-9388-11ea-93d5-018d5eafe47b.png)

   - `wash` (gray) vs `hand-gesture` (red):
   ![image](https://user-images.githubusercontent.com/7819991/81555248-8be38300-9388-11ea-94dd-27e9bb3ab95b.png)

---

I'm in favor of B (on grid or right between grid lines), because the anti-aliasing at native size isn't much worse than of A, and it removes the irregularities at 2x.

Regarding shape & finger length, I'm slightly in favor of longer fingers, because of the more natural proportions (at least in my perception). The bottom left area at the root of the thumb looks a bit strange at large scale though.

Really unsure about how to solve the space issue for a future filled `hand-gesture` icon.

**Comment by goyney** [comment]
All our hands icons were updated to Google's in v6. Closing.
