### ISSUE TITLE
spray-bottle / household-supplies

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#5148]
MIE v58 has `household-supplies`, a variant of our `spray-bottle`:

![image](https://user-images.githubusercontent.com/7819991/81556516-b8989a00-938a-11ea-8942-df5eebe41c90.png)

![image](https://user-images.githubusercontent.com/7819991/81556608-e847a200-938a-11ea-8db3-161f33d375c5.png)

Do we want to add it as variant or replace ours?

**Comment by goyney** [comment]
Ours looks more like a spray bottle, albeit not as Material. 🤔

**Comment by Templarian** [comment]
Really not liking either design. 🤷‍♂️

**Comment by Simran-B** [comment]
We could update ours to look more like the Google Fit one:

![image](https://user-images.githubusercontent.com/7819991/81677367-2d360c00-9451-11ea-9a1f-ab0620f74667.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/81766500-42885600-94a4-11ea-85b8-2413cb7641e0.png)
[spray-bottle.svg.zip](https://github.com/Templarian/MaterialDesign/files/4619584/spray-bottle.svg.zip)

**Comment by Templarian** [comment]
Maybe we should exaggerate the bottle trigger like in the Google fit?

The curve at the top of the bottle should probably follow the handle a little.

**Comment by goyney** [comment]
Handle exaggerated and the bottle change to follow the handle. Updated!
[![spray-bottle](https://materialdesignicons.com/icon/spray-bottle)](https://materialdesignicons.com/icon/spray-bottle)
