### ISSUE TITLE
Please add ability to search icon

### ISSUE THREAD

**Issue by deliriousrhino** [Templarian/MaterialDesign#515]
Due to the amazing on these icons there are now so many it is hard to find the one you want.

Could you please add a way to search the icons

**Comment by ArneDerynck** [comment]
You can click the search icon on the top-left corner right under the title:
**"Hello! Need some icons? Have a look below. The orange icons are from the community."**

It wouldn't be bad if icons had some more tags on them so it would be easier to find an icon, sometimes I have so search 2 - 3 times before getting the result I want, but overall it works quite well

**Comment by Templarian** [comment]
I have aliases to account for the top 300 or so most common search results. Slowly adding more aliases (if you search for certain terms it will return icons with different names).

Tagging is built in, but I need to go through and tag more of the icons.

There is a lot of backend code changes going on at the moment getting ready for the new export screen. After that I have a few other small issues then next will be improving the search even further (mostly better integrating the existing tags/aliases more).

**Comment by Templarian** [comment]
I'm going to close out this issue. You can get to the search quicker by hitting `CTRL+F` in your browser to expand the search field.

**Comment by tchret** [comment]
+1, I don't get it for the `CTRL + F` on the front page, the icon name are in tooltips

**Comment by tchret** [comment]
@Templarian +1, I don't get it for the `CTRL + F` on the front page, the icon name are in tooltips

**Comment by CoDEmanX** [comment]
Talking about search... search is really slow on my smartphone (which has a 4x2.27ghz) in Chrome for Android. The search field does even reject input some times. Loading times are also really high, and always the same (no caching?) - anything you can do @Templarian? FontAwesome has distinct pages for every icon to achieve fast load times.

**Comment by Templarian** [comment]
Yea, @CoDEmanX I thought about it, but the investment for mobile doesn't make sense. I get less than 1% mobile users since it is targeting designers and developers.

**Comment by Templarian** [comment]
@tchret I tested in a handful of browsers CTRL+F opened up the search panel. If I get some time to redesign things I'll make a fixed search bar.

![image](https://cloud.githubusercontent.com/assets/338885/9075604/6b853888-3adc-11e5-9be0-0d5078c404b7.png)

**Comment by CoDEmanX** [comment]
I see. Loading times are high on desktop too nonetheless (also no caching).

**Comment by Templarian** [comment]
I sort of do that on purpose due to the rapid increase of traffic the site is seeing. I cache the entire icon call every 5 minutes and just hand that to the user directly.

If I update the server I'll try and implement a more graceful loading of the icons (in chunks).

**Comment by tchret** [comment]
@Templarian a great feature like this one should be more accessible 😄nice job

**Comment by Templarian** [comment]
The search box is now visible all the time. It's just a quick workaround until the new design is in place.

**Comment by tchret** [comment]
@Templarian 🙌
