### ISSUE TITLE
refer friend

### ISSUE THREAD

**Issue by ShanmugavelGK** [Templarian/MaterialDesign#5154]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@ShanmugavelGK The template isn't optional. You actually need to fill it out so we know what you're requesting.

**Comment by goyney** [comment]
Closing because the `Needs More Info` label was added several months ago with no new suggestions or contributions. Please comment back if you have other ideas that could help fulfill this request. Thank you for your suggestion!
