### ISSUE TITLE
subdirectory_arrow_right and subdirectory_arrow_right1 are off-center

### ISSUE THREAD

**Issue by oliverkx** [Templarian/MaterialDesign#5155]
The current subdirectory_arrow_right (standard) and subdirectory_arrow_right1 (extended) icons look off-center when combined with their highlight - see attached:
![icon-current](https://user-images.githubusercontent.com/12791021/81830599-1e9f3180-94f1-11ea-9b19-f57445917943.png)

Here is a representation of a proposed re-centered version:
![icon-proposed](https://user-images.githubusercontent.com/12791021/81830625-28289980-94f1-11ea-81fd-356bdc7df090.png)

Thanks!

**Comment by goyney** [comment]
For reference, on the grid:

![image](https://user-images.githubusercontent.com/1015040/81833284-85cadf00-950d-11ea-86d7-254b1819a54a.png)

Also note, that these are official Google icons.

**Comment by Templarian** [comment]
So the proposal is to move it right twice and up 1.

![image](https://user-images.githubusercontent.com/338885/81895993-34583980-9579-11ea-8c4e-f69bf1d9550e.png)

**Comment by goyney** [comment]
I think that's worse. Now it's too heavy on the right side.

A true centering of these would move them over .5dp to the right and .1dp down.

I don't feel these changes are warranted. Considering their use case by the name of "subdirectory," they're likely meant to be used in a file tree. This means you wouldn't want them to feel heavy on the right side. Keeping these on the grid and in their current positions feels like the right answer and is why Google probably positioned them they way they did.

I recommend we reject this update.

**Comment by oliverkx** [comment]
I agree that the modified version looks off-center on its own. But the current version looks off-center when combined with a circle highlight. That same circle highlight looks perfectly centered with all the other MD icons I have used so far.

I will check with the team that manages these icons for our software, and see if there is anything they can do on their end.

Thank you!

**Comment by Templarian** [comment]
I'm just going to put this in case others run across this issue. Might not apply, but react devs we have an open issue to add offset support, but no one has actually asked for it, so I never added it.

https://github.com/Templarian/MaterialDesign-React/issues/17
