### ISSUE TITLE
crossed snowflake (snowflake-off)

### ISSUE THREAD

**Issue by PawelTroka** [Templarian/MaterialDesign#5156]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Turned off cooling, turned off AC, etc.

## Examples

![image](https://user-images.githubusercontent.com/11928766/81871727-b2681080-9578-11ea-868d-8cb62a6f630f.png)

**Comment by goyney** [comment]
[![snowflake-off](https://materialdesignicons.com/icon/snowflake-off)](https://materialdesignicons.com/icon/snowflake-off)
