### ISSUE TITLE
Separators of verses from the holy Quran

### ISSUE THREAD

**Issue by BasitCode** [Templarian/MaterialDesign#5159]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Icons will be used in Quran applications

## Examples
![image](https://user-images.githubusercontent.com/53387349/82130139-f3af2900-97e1-11ea-958b-7fb8da117098.png)

![image](https://user-images.githubusercontent.com/53387349/82129917-0163af00-97e0-11ea-8b38-a8e7cdbee01e.png)
![image](https://user-images.githubusercontent.com/53387349/82130007-e3e31500-97e0-11ea-89b2-d390f9022e6d.png)

![image](https://user-images.githubusercontent.com/53387349/82129912-e98c2b00-97df-11ea-81b3-5ae142517f79.png)

![image](https://user-images.githubusercontent.com/53387349/82129949-44be1d80-97e0-11ea-9575-8292d759097c.png)

**Comment by Templarian** [comment]
We haven't really invested a lot of time into decorative glyphs.

Could you reuse something like `brightness-5` / `brightness-7` for these? Kind of like the last example.

The detail might be too much for the 1:1 size.

**Comment by Templarian** [comment]
@BasitCode Do you have examples of what this looks like in context? Trying to think of how we'll go about naming these.

- Do these function the same as a "Section" page break? Like Horizontal Rule.
- https://en.wikipedia.org/wiki/Section_(typography)
- `format-section` which is the actual symbol for ^
- Just jotting down notes trying to get familiar with the subject.

**Comment by Templarian** [comment]
@BasitCode Reminder on the questions above. Thanks.

**Comment by goyney** [comment]
We haven't heard back for clarifications on this issue, so unfortunately there's not much we can do with it. We're going to close it for now. If this is still something you need, please feel free to comment back and we can reopen for consideration. Thanks for your suggestion!
