### ISSUE TITLE
icon request(s): more code-* icons

### ISSUE THREAD

**Issue by dgmltn** [Templarian/MaterialDesign#516]
Several more code-* icons in the style of code-array:

- [x] code-block: "{}"<br>
![ic_variables](https://cloud.githubusercontent.com/assets/698270/8821096/e128ad72-300f-11e5-8b91-687e18a5a587.png)
- [x] code-tag: "<>"
- [ ] code-array: "[]"
- [ ] code-function(?): "()"

Also, black-on-white versions of those.

**Comment by CoDEmanX** [comment]
[ic_code](http://www.google.com/design/icons/#ic_code) by Google is `code-tag`.
Oddly, there's no `{}` icon, despite it's a common icon in code editors. Should definitely be added to MDI!

**Comment by CoDEmanX** [comment]
`code-block` proposal:
![function-braces](https://cloud.githubusercontent.com/assets/1309249/8863293/ab834f22-3197-11e5-8523-4ad878ff861e.png) https://www.dropbox.com/s/g4l20x8tgpe9l0z/function-braces.svg?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/code-tags
https://materialdesignicons.com/icon/code-braces

**Comment by dgmltn** [comment]
Thanks!

**Comment by CoDEmanX** [comment]
Pairs of square brackets and parentheses:

![function-square-brackets2](https://cloud.githubusercontent.com/assets/1309249/9695061/8e2cd5c2-535e-11e5-924d-de3cbf554505.png) 
![function-braces](https://cloud.githubusercontent.com/assets/1309249/9695062/8e2e34d0-535e-11e5-975b-6dbb19360401.png) (reference brackets)
![function-parens3](https://cloud.githubusercontent.com/assets/1309249/9695063/8e3092f2-535e-11e5-92c2-4b67cbe4e79b.png)

Will add links later, Dropbox seems offline.

![function-parens](https://cloud.githubusercontent.com/assets/1309249/9695067/a059917c-535e-11e5-86de-aabba394b4d1.png) - closer together, is this better than the one above?
![function-parens2](https://cloud.githubusercontent.com/assets/1309249/9695068/a05b10ce-535e-11e5-8efa-e13bed8a112a.png) - between both above parens pairs, but slightly blurry
![function-square-brackets](https://cloud.githubusercontent.com/assets/1309249/9695069/a05bbd76-535e-11e5-9e7d-5d4f12318e66.png) - taller than above version, looked a little odd to me
![function-square-brackets-fat](https://cloud.githubusercontent.com/assets/1309249/9695070/a05c0272-535e-11e5-89b8-aaa75f6093e6.png) - probably not :no_good:

**Comment by Templarian** [comment]
[![code-brackets](https://materialdesignicons.com/icon/code-brackets)](https://materialdesignicons.com/icon/code-brackets) [![code-parentheses](https://materialdesignicons.com/icon/code-parentheses)](https://materialdesignicons.com/icon/code-parentheses)

**Comment by CoDEmanX** [comment]
There's actually some sort of "official code-braces icon", used in Android for developer options:

![google-developer-options](https://cloud.githubusercontent.com/assets/1309249/10836083/e97363a8-7ea9-11e5-8330-4bf34c720924.png)

It's nowhere near pixel-perfect. Interestingly, they use rounding all over, violating their own rules. I think ours is fine though.

**Comment by Templarian** [comment]
Yea, yours looks better also. Probably made by a developer really quick on their team.
