### ISSUE TITLE
Glimmer

### ISSUE THREAD

**Issue by rsolorio** [Templarian/MaterialDesign#5164]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A glimmer icon for marking text (folders, tree view items, etc) as new. This is part of the sharepoint design, which I think is a good idea.

## Examples

https://gxcuf89792.i.lithium.com/t5/image/serverpage/image-id/23878i9608333CE926FD1B/image-size/large?v=1.0&px=999

**Comment by Templarian** [comment]
This seems like a good icon to have similar to how we have `mdiCreation`.

Thought we had something like this, but I'm not finding it.

**Comment by Templarian** [comment]
I'm going to propose we call this `vanish-quarter`, but we'll alias it `glimmer` and a few other things like `new`.

**Comment by goyney** [comment]
Two options here:

![image](https://user-images.githubusercontent.com/1015040/82275640-41966f00-9951-11ea-9482-31199894843e.png)![image](https://user-images.githubusercontent.com/1015040/82275689-60950100-9951-11ea-86a0-18a161d5c7a8.png)

Thoughts?

**Comment by rsolorio** [comment]
I like it, but I feel the lines are a little bit shorter.

I just found the icon here for better reference: https://uifabricicons.azurewebsites.net/

**Comment by goyney** [comment]
It's meant to be a flair or helper, not an entire icon. If you need it bigger, you can resize. :smile:

[![vanish-quarter](https://materialdesignicons.com/icon/vanish-quarter)](https://materialdesignicons.com/icon/vanish-quarter)
