### ISSUE TITLE
Flag

### ISSUE THREAD

**Issue by JxnGraphix** [Templarian/MaterialDesign#5165]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/5524146/82262299-42fe7200-9926-11ea-82ba-841b9b5171e1.png)

[flag.zip](https://github.com/Templarian/MaterialDesign/files/4647039/flag.zip)

**Comment by goyney** [comment]
This is just `bookmark` rotated. Feel free to use CSS or the `rotate` prop in @mdi/react to achieve this. We already have icons for flags and this doesn't add any value, so we're going to close this issue. Thanks for your suggestion.

**Comment by JxnGraphix** [comment]
> This is just `bookmark` rotated. Feel free to use CSS or the `rotate` prop in @mdi/react to achieve this. We already have icons for flags and this doesn't add any value, so we're going to close this issue. Thanks for your suggestion.

The zip file contains five additional versions: check mark, star and outline. CSS will not rotate the check mark and star separately.
