### ISSUE TITLE
open-hand / hand-extended

### ISSUE THREAD

**Issue by mariovials** [Templarian/MaterialDesign#5169]
Hi, you can make the open-hand icon. (Like the hand-heart but whitout heart)

## Usage
I need it for represent the idea of to give or provide.

## Examples
![image](https://user-images.githubusercontent.com/1584766/82349962-bb1d7400-99c8-11ea-8aa8-d065b8031843.png)

Thanks

PD: The hand of hand-heart icon seems too thick and the fingers too short ;)

**Comment by Templarian** [comment]
We need to think of a better name for this `hand-???`.

**Comment by mariovials** [comment]
> We need to think of a better name for this `hand-???`.

hand-open (better than open-hand) or hand-extended, to continue with "hand-" prefix
I think hand-extended is more accurate than hand-open

**Comment by goyney** [comment]
[![hand-extended](https://materialdesignicons.com/icon/hand-extended)](https://materialdesignicons.com/icon/hand-extended)[![hand-extended-outline](https://materialdesignicons.com/icon/hand-extended-outline)](https://materialdesignicons.com/icon/hand-extended-outline)
