### ISSUE TITLE
icon request: section collapse/expand icons

### ISSUE THREAD

**Issue by ArneDerynck** [Templarian/MaterialDesign#517]
I have an app that has collapsible sections (left/right/up/down) so a collapse / expand icon would come in very useful.

For example (iconic font): 
![screen shot 2015-07-22 at 11 22 21](https://cloud.githubusercontent.com/assets/1822535/8822194/f2c9a3de-3063-11e5-9e32-25276cb729bf.png)

As an extra: it would be nice if it were to match with "view-array, view-columns, ..." icons

Thanks!
- [ ] `panel-expand-left`
- [ ] `panel-collapse-left`
- [ ] `panel-expand-right`
- [ ] `panel-collapse-right`
- [ ] `panel-expand-up`
- [ ] `panel-collapse-up`
- [ ] `panel-expand-down`
- [ ] `panel-collapse-down`

**Comment by CoDEmanX** [comment]
I would actually recommend the `chevron-*` icons ([see here](https://materialdesignicons.com/icon/chevron-left)), because it's a much simpler shape and easier to understand. Users should be able to figure it out.

**Comment by llihak** [comment]
I like the Materialize.css swap_vert to indicate accordion open / close functionality

![image](https://cloud.githubusercontent.com/assets/72495/9047162/3580295e-39ed-11e5-9b1d-f734e0edec56.png)

**Comment by PeterShaggyNoble** [comment]
Closing this issue out as we have a few options that should cover this now, including the already mentioned `chevron-*` & `swap-*` icons and the `unfold-*` icons.
