### ISSUE TITLE
Music icons: thirtysecond, dotted-thirtysecond, tie-up, tie-down, and arpeggio

### ISSUE THREAD

**Issue by trantinan2512** [Templarian/MaterialDesign#5171]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
Extending #3263 music icon suite
![image](https://user-images.githubusercontent.com/20013228/82361609-43396300-9a35-11ea-9f08-1b159084819c.png)
![image](https://user-images.githubusercontent.com/20013228/82362307-58fb5800-9a36-11ea-9441-4675a5d1e2ea.png)
![image](https://user-images.githubusercontent.com/20013228/82362399-7defcb00-9a36-11ea-82ca-58cdaa7d5b90.png)
![image](https://user-images.githubusercontent.com/20013228/82362441-8ea04100-9a36-11ea-8c4b-ed5bf9f3a79e.png)
![image](https://user-images.githubusercontent.com/20013228/82361521-2735c180-9a35-11ea-96af-0b38f772db6b.png)

## Zip Download

[Music.Suite.Extension.zip](https://github.com/Templarian/MaterialDesign/files/4652397/Music.Suite.Extension.zip)

**Comment by goyney** [comment]
We discussed these when we added all the other icons and decided that we were opening a can of work added every permutation of every note type and musical symbol. I still don't think we need these, but I'll let the other contributors weigh in.

**Comment by goyney** [comment]
That being said, the 32nd notes require all our notes to be updated to support the third bar. The ties and the arpeggio are not Material, so they're need some work if we were to include them.

**Comment by trantinan2512** [comment]
I used the 16th notes in #3263 zip file to make those 32nd notes, not sure if a new version of those notes has already been there :\
I'll try to update the other 3.

**Comment by goyney** [comment]
The problem is the 4/1/3/1/2 size/gap ratio on the flags. If we decide to add these, we should probably just make those all an even 2/2/2/2/2 and then apply that change to the existing notes.

**Comment by trantinan2512** [comment]
Yeah, I would totally agree with that, that will be following Material to its fullest 😄

**Comment by trantinan2512** [comment]
Looks better IMO \(￣︶￣*\))
![image](https://user-images.githubusercontent.com/20013228/82400422-786ba280-9a81-11ea-8a44-d5d0e300d2c1.png)
```M18,5V3h-6v10.6c-0.6-0.3-1.3-0.6-2-0.6c-2.2,0-4,1.8-4,4s1.8,4,4,4s4-1.8,4-4v-4h4v-2h-4V9h4V7h-4V5H18z```
![image](https://user-images.githubusercontent.com/20013228/82400480-9afdbb80-9a81-11ea-9d53-236220061a9e.png)
```M18,5V3h-6v10.6c-0.6-0.3-1.3-0.6-2-0.6c-2.2,0-4,1.8-4,4s1.8,4,4,4s4-1.8,4-4v-4h4v-2h-4V9h4V7h-4V5H18z M16.5,17    c-0.8,0-1.5,0.7-1.5,1.5s0.7,1.5,1.5,1.5s1.5-0.7,1.5-1.5S17.3,17,16.5,17z```

**Comment by trantinan2512** [comment]
Rework of `music-note-tie-up`, `music-note-tie-down`, and `music-note-arpeggio`
![image](https://user-images.githubusercontent.com/20013228/82406930-136c7880-9a92-11ea-85c2-e2fa06866184.png)
![image](https://user-images.githubusercontent.com/20013228/82406943-1d8e7700-9a92-11ea-9d0f-9bf609334bd2.png)
![image](https://user-images.githubusercontent.com/20013228/82406707-82959d00-9a91-11ea-8ed0-1e1f512ab5e8.png)

[Music.Ties.Arpeggio.zip](https://github.com/Templarian/MaterialDesign/files/4654720/Music.Ties.Arpeggio.zip)

**Comment by trantinan2512** [comment]
The ties look too small in small versions so I attempted to make them bigger:
![image](https://user-images.githubusercontent.com/20013228/82518298-445bb480-9b49-11ea-8bd9-00bce105ed93.png)
![image](https://user-images.githubusercontent.com/20013228/82518314-4f164980-9b49-11ea-8eb0-58defab26334.png)
[Music.Ties.zip](https://github.com/Templarian/MaterialDesign/files/4660383/Music.Ties.zip)

**Comment by goyney** [comment]
I think we're going to pass on these for now. Thanks for you suggestion and work.
