### ISSUE TITLE
submarine

### ISSUE THREAD

**Issue by adlaws** [Templarian/MaterialDesign#5172]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
Incorporates the existing "wave"icon as the ocean surface.

![image](https://user-images.githubusercontent.com/1201371/82404013-c0df8c00-9a92-11ea-9802-e9a66c531d58.png)

## Zip Download
[submarine.zip](https://github.com/Templarian/MaterialDesign/files/4654579/submarine.zip)

**Comment by goyney** [comment]
[![submarine](https://materialdesignicons.com/icon/submarine)](https://materialdesignicons.com/icon/submarine)
