### ISSUE TITLE
HBO Icon

### ISSUE THREAD

**Issue by rauljerico** [Templarian/MaterialDesign#5173]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In Media Player entity

## Examples

I'm trying custom:lg-remote-control and I want to get the HBO button. Thanks

**Comment by Templarian** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by PeterShaggyNoble** [comment]
This one's [already available from SI](https://simpleicons.org/?q=HBO):

![](https://user-images.githubusercontent.com/15157491/82439154-17989600-9a92-11ea-9cbc-a69d4346122a.png)

**Comment by rauljerico** [comment]
> This one's [already available from SI](https://simpleicons.org/?q=HBO):
> 
> ![](https://user-images.githubusercontent.com/15157491/82439154-17989600-9a92-11ea-9cbc-a69d4346122a.png)

Thanks, but how can I use this in Home Assistant? I'm newie :P 

Should I install the simpleicon HACS?

Thanks

**Comment by Templarian** [comment]
@rauljerico There is a package for simple icons. @goyney Do you have a link?

**Comment by PeterShaggyNoble** [comment]
Is [this](https://github.com/vigonotion/hass-simpleicons) the one you're thinking of, @Templarian?

**Comment by Templarian** [comment]
Yep, that package.
