### ISSUE TITLE
Flag Check

### ISSUE THREAD

**Issue by JxnGraphix** [Templarian/MaterialDesign#5174]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

This is different from the bookmark icon because it is rotated with a stable element inside of it. CSS will rotate both elements and I need the check to remain in position. Variations are in the Zip. 

## Preview
(http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/5524146/82454684-ab109d80-9a77-11ea-994b-7d5612703da6.png)

## Zip Download
[flag.zip](https://github.com/Templarian/MaterialDesign/files/4657281/flag.zip)

**Comment by goyney** [comment]
Our base `flag` icon is this:
![image](https://user-images.githubusercontent.com/1015040/82456505-50307380-9a82-11ea-8807-3857899f3e5e.png)

If we are going to add this, we need to get buy in from all the contributors that a rotated version of an existing icon is acceptable to add first. Then we need to determine a name for the new base.

BTW, you *can* accomplish this with `@mdi/react` using the `Stack` component and the `rotate` prop.

```js
import Icon, { Stack } from '@mdi/react';
import { mdiBookmark, mdiCheck } from '@mdi/js';

<Stack>
  <Icon path={mdiCheck} size={.7} />
  <Icon path={mdiBookmark} rotate={90} size={1} />
</Stack>
```

**Comment by JxnGraphix** [comment]
It doesn't have to be called flag. I'm using it as a status "marker" for separate sections. The "markers" represent the state of each section: enabled (solid), active (star) and completed (checked).

**Comment by Templarian** [comment]
Are these used in a similar way to say `label` icons. Because we even have `label-variant`. 🤔

**Comment by Templarian** [comment]
@JxnGraphix The above question. Still curious about the usage, trying to picture these used in an app.
