### ISSUE TITLE
Make $mdi-sizes overridable 

### ISSUE THREAD

**Issue by SachaJolly** [Templarian/MaterialDesign#5175]
Hi there!

I wanted to override the $mdi-sizes variable to add a new size (e.g. 20px to follow my design system) but it doesn't work.

```
$mdi-sizes: 16 20 24 32 48;
```

It seems that it is not in the `_variables.scss` file but in the `_extras.scss` file without a `!default` flag to make it overridable.

I don't know if I am doing something wrong or if this is a choice, if not it would be very cool to add the ability to override this variable! 🙏

Thanks!

**Comment by goyney** [comment]
We really, really recommend you stop using the webfont. You're currently downloading nearly 5500 icons. Please see this page for more information: http://dev.materialdesignicons.com/guide/webfont-alternatives.

Using alternatives gives you MUCH more control on how you use the icons.

**Comment by Templarian** [comment]
That's kind of a separate issue @goyney. Yeah, this is a bug we can fix in the `v5.3.45` release.

**Comment by Templarian** [comment]
@SachaJolly This was fixed in `@mdi/font-build@1.8.5` which I'll use to in `v5.3.45`.
