### ISSUE TITLE
fuel-tank-outline

### ISSUE THREAD

**Issue by ybandura** [Templarian/MaterialDesign#5176]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![fuel-tank-outline](https://user-images.githubusercontent.com/5179676/82600618-d9e15d80-9bb6-11ea-990c-82247fde9747.png)

## Zip Download
[fuel-tank-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/4664483/fuel-tank-outline.svg.zip)

**Comment by goyney** [comment]
[![storage-tank](https://materialdesignicons.com/icon/storage-tank)](https://materialdesignicons.com/icon/storage-tank)[![storage-tank-outline](https://materialdesignicons.com/icon/storage-tank-outline)](https://materialdesignicons.com/icon/storage-tank-outline)
