### ISSUE TITLE
Globe or round map

### ISSUE THREAD

**Issue by shariffaraz** [Templarian/MaterialDesign#5177]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by JapanYoshi** [comment]
> - [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.

I unchecked this for you, because searching for "globe" on materialdesignicons.com yields not only the ``earth`` icon but also the ``globe-model`` icon.

**Comment by shariffaraz** [comment]
Sorry I couldn't find it earlier on search. But now I can find Thanks @JapanYoshi closing this issue as no longer required
