### ISSUE TITLE
Right-angled/corner diagonal arrows

### ISSUE THREAD

**Issue by retnikt** [Templarian/MaterialDesign#5179]
Currently there are arrows for diagonal directions up-right, down-left, etc. However they are all diagonal and straight instead of right-angled or "corner" shaped.

There are `subdirectory-arrow-left` and `-right`, but these are only 2 of the possible 8 arrows, (including right-up and up-right, see below) and are hard to find in search because of their very specific naming

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In my case I want to portray inserting an object above the selected one, to the right, etc.

## Examples

For up-right
![image](https://user-images.githubusercontent.com/24581770/82687857-c7ffc900-9c4f-11ea-858b-df0c275beeea.png)

For right-up
![image](https://user-images.githubusercontent.com/24581770/82687953-f382b380-9c4f-11ea-94e6-0aa144072399.png)

**Comment by goyney** [comment]
Our arrow collection has grown to include these types, so go check them out!
