### ISSUE TITLE
Duplicate alias on syllabary-katakana-halfwidth

### ISSUE THREAD

**Issue by Xcodo** [Templarian/MaterialDesign#5181]
Similar to #5180, the icon `syllabary-katakana-halfwidth` has a duplicated alias `writing-system-katakana-half-width` listed in the [5.2.45 meta.json file](https://cdn.materialdesignicons.com/5.2.45/meta.json).

**Comment by PeterShaggyNoble** [comment]
That's deliberate, @Xcodo; notice the extra hyphen in the alias. It's primarily for the benefit of  people searching for it under that name as it was recently renamed.

**Comment by Xcodo** [comment]
I might be wrong @PeterShaggyNoble but I think the hyphenated version appears twice in the `alias` field in the JSON. I'll check again in an hour or so.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/82704968-5c603080-9c3c-11ea-9344-497ee72aa386.png)

@Xcodo You were right about this bug.

**Comment by Templarian** [comment]
This bug was fixed. I'll be adding scripts to our verification script to catch these types of things.
