### ISSUE TITLE
arrow_back_ios

### ISSUE THREAD

**Issue by Renecoty** [Templarian/MaterialDesign#5182]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For an app navigation 

## Examples

https://material.io/resources/icons/?icon=arrow_back_ios&style=baseline

**Comment by Templarian** [comment]
Marking this was as rejected as it's too niche. The focus is on more general/utility icons. Like `chevron-left` for instance.

**Comment by Renecoty** [comment]
Yes I saw chevron-left but it is not designed for a back navigation. It would benefit to all developpers using this library for an iOS app and so all their users. (Plus it has already been designed by Google)

**Comment by Templarian** [comment]
@Renecoty If you're needing iOS specific iconography you should be using their icons. Not something we have the time to maintain. You might want to use iOS iconography everywhere if that is the goal.
