### ISSUE TITLE
*-minus variants have inconsistent cutouts

### ISSUE THREAD

**Issue by daavko** [Templarian/MaterialDesign#5183]
Some *-minus variants have a rectangular cutout, and some have a round cutout. The guide at [http://dev.materialdesignicons.com/contribute/icon-naming](http://dev.materialdesignicons.com/contribute/icon-naming) specifies a rectangular cutout for *-minus variants. Is this intended?

![image](https://user-images.githubusercontent.com/7669061/82702087-9c8dd600-9c71-11ea-82ad-88920f75cde2.png)
![image](https://user-images.githubusercontent.com/7669061/82702403-3eadbe00-9c72-11ea-84d0-36bee4a1c3e5.png)

**Comment by Templarian** [comment]
This is a known issue, we're trying to decide if went want to push forward with the circle everywhere.

Right now it was intended, but might not be the final design. Keeping this open to track this.

**Comment by goyney** [comment]
Every `minus` variant I have added over the past 4-5 version have used the circle cutout. The problem with the rectangular cutout is that they don't work well in some outline variants. The circle is clear and consistent in all cases.

**Comment by goyney** [comment]
We'll use this issue to track updating all `minus` variants that use the rectangular cutout to use a circle instead.

**Comment by goyney** [comment]
All `minus` variants have been updated to use the circle cutout.
