### ISSUE TITLE
school-building

### ISSUE THREAD

**Issue by nilsfast** [Templarian/MaterialDesign#5184]
I have:

- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

I had to use some off-grid 1dp lines.

## Preview

![image](https://user-images.githubusercontent.com/58486458/82729007-62b1e380-9cf4-11ea-9571-b4d4c713cb27.png)

## Zip Download

[school-building.zip](https://github.com/Templarian/MaterialDesign/files/4671623/school-building.zip)

**Comment by Templarian** [comment]
Can we try shrinking down the windows by 1px away from the base. For some reason it's looking like a satellite right now. 🤔

**Comment by PeterShaggyNoble** [comment]
As I mentioned in [#2173](https://github.com/Templarian/MaterialDesign/issues/2173#issuecomment-334469003): people outside America wouldn't identify this icon with a school. If you showed it to me without context, my best guess would be that is was, maybe, a town hall.

**Comment by goyney** [comment]
Like the icon, agree about the name, so went with a different one. We'll alias school to it.
[![town-hall](https://materialdesignicons.com/icon/town-hall)](https://materialdesignicons.com/icon/town-hall)
