### ISSUE TITLE
mdi/js combine icons

### ISSUE THREAD

**Issue by JBauto** [Templarian/MaterialDesign#5188]
Hi,

I'm trying to combine 2 icons, mdiPlay with mdiFlipHorizontal however I'm not sure if I'm using the icons in the correct way. Using Vue/Vuetify with @mdi/js.

```
<v-icon dense>{{icons.play}} {{icons.fliph}}</v-icon>
...
icons = {play: mdiPlay, fliph:mdiFlipHorizontal}
```

This is how it looks. 

![image](https://user-images.githubusercontent.com/7757542/83061678-4cd65280-a055-11ea-8bba-e7642934e977.png)

Before I was using webfont and could do `mdi-play mdi-flip-horizontal` and it was working as expected.

Thanks for the help!
Cheers

**Comment by Templarian** [comment]
Looking at the docs that doesn't appear to be a feature. I'm not sure what the use of such an icon can be, but we often ask people to request specific icons rather than stacking them.

https://vuetifyjs.com/en/components/icons/

**Comment by Templarian** [comment]
Going to close this as it may be a better feature request on their side. TBH, you can kind of combine the path vectors into a single string value.

Example: `${path1}Z${path2}`, but that might always work.
