### ISSUE TITLE
Calendar span 

### ISSUE THREAD

**Issue by Valmanway** [Templarian/MaterialDesign#5189]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Could be used to symbolize a span (from a time to another), I know calendar-range exists but it doesn't express the same thing 

## Examples

![calendar-span](https://user-images.githubusercontent.com/6604880/83143722-aa6cac80-a0f2-11ea-857d-5b18c1f9fb13.png)

**Comment by Templarian** [comment]
`calendar` + `table-split-cell` essentially. 👍

**Comment by Valmanway** [comment]
Basically yes, with the arrows touching in the middle. Would be great, thank you

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/83318585-ca3bc780-a1fb-11ea-9aaa-38e2beca5582.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/83318806-d45ec580-a1fd-11ea-8e98-2958bf4b3fd4.png)

**Comment by Valmanway** [comment]
Awesome, thank you :)

**Comment by Templarian** [comment]
Probably tweaking them more after input from some others. Will add these shortly.

**Comment by Valmanway** [comment]
Ok, great

**Comment by goyney** [comment]
[![calendar-expand-horizontal](https://materialdesignicons.com/icon/calendar-expand-horizontal)](https://materialdesignicons.com/icon/calendar-expand-horizontal)[![calendar-collapse-horizontal](https://materialdesignicons.com/icon/calendar-collapse-horizontal)](https://materialdesignicons.com/icon/calendar-collapse-horizontal)
