### ISSUE TITLE
mdi-key-chain

### ISSUE THREAD

**Issue by mateosilguero** [Templarian/MaterialDesign#5192]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/25598400/83258403-98d7e300-a18c-11ea-84b6-668df2760613.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[key-chain.zip](https://github.com/Templarian/MaterialDesign/files/4701740/key-chain.zip)

**Comment by goyney** [comment]
Had to do some work on this one, but it's added:
[![key-chain](https://materialdesignicons.com/icon/key-chain)](https://materialdesignicons.com/icon/key-chain)
