### ISSUE TITLE
key-chain-variant

### ISSUE THREAD

**Issue by mateosilguero** [Templarian/MaterialDesign#5193]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/25598400/83258891-772b2b80-a18d-11ea-8af5-548dcdc7d165.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[key-chain-variant.zip](https://github.com/Templarian/MaterialDesign/files/4701725/key-chain-variant.zip)

**Comment by goyney** [comment]
A lot of rework on this one too. Added!
[![key-chain-variant](https://materialdesignicons.com/icon/key-chain-variant)](https://materialdesignicons.com/icon/key-chain-variant)
