### ISSUE TITLE
pentagram / pentagram-circle / *-reversed

### ISSUE THREAD

**Issue by Sjoerd82** [Templarian/MaterialDesign#5194]
A Pentagram (or "Pentacle") is a five-pointed star. The orientation is usually pointing upwards, but it can also be reversed. Upward/downwards pointing (often called "reversed"), and enclosed in a circle can all have different meanings. Ideally, I'd see four icons:

mdi-pentagram
mdi-pentagram-reversed
mdi-pentagram-circle
mdi-pentagram-reversed-circle

I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A pentagram icon could be used to:
- Represent the Wiccan faith, witchcraft, etc. Other faith icons already exist.
- Represent something magical.
- Represent a ritual.
- Represent something evil (when pointing down).
- Represent five senses or five elements.
- Occasionally used in various mythological contexts and rituals.

## Examples

![pentagrams](https://user-images.githubusercontent.com/15013786/83265756-40bbd380-a1c2-11ea-8428-f39c4f4961cd.jpg)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/83482206-543a9900-a465-11ea-9eb9-4d273da26475.png)

1.5dp width lines.

**Comment by Sjoerd82** [comment]
I had been struggeling with Inkscape, but failed horribly. This looks pretty much spot on. I think Material Design prefers 2dp lines, but that would really not look very good in this case.

Being pretty new to this Material Design Icons, what's the stance on the same icon, reversed, inverted, etc.? I can imagine you wouldn't want to clog-up the collection with effects that could be achieved on the 'client side'.

Then there is the "-circle" version. I've been doing some research on the differences, with and without. There are, but seem to be fairly subtle. From an icon/symbol perspective, I would personally like to see both versions. The "open"-version is quite a versatile symbol that may represent a wide range of concepts. The "circle"-version feels much more representing the spirtual side. I'm currently designing a game where the player can do something magical, in that case I'd prefer a circled pentagram over an open one, as it's more recognizable as something ritualistic.

So, what would an icon submission path look like here on MDI? Could I expect to see the icon appear in the collection, or are there any things that I could do to expedite the process?

Sorry for the 100-questions. As a kid I "collected" icons, back in the Windows 3.11 era. Always loved how small pictures could convey idea's and concepts. Thus, I'm very interested in this MDI repository.

**Comment by goyney** [comment]
Considering that @Templarian's contribution only works at 1dp, I think that pretty much means the circle variant is out of the picture. In terms of reversing, flipping, or rotating, unless there is a very common use case, we don't typically add those and it would be up to your tooling to manipulate the icon.

@Templarian Share your SVG so this can be added. 😄

**Comment by Templarian** [comment]
Added. Agreed circle would lose too much detail.
