### ISSUE TITLE
Linear Scale

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5195]
Can we get Google's [Linear Scale](https://material.io/resources/icons/?search=linear&icon=linear_scale&style=baseline) icon added to the library?

![image](https://user-images.githubusercontent.com/1837101/83281692-b65d7a80-a195-11ea-8140-acbb31dafe43.png)

**Comment by Templarian** [comment]
Probably could just add it to the existing `ray-*` set.

**Comment by goyney** [comment]
[![ray-start-vertex-end](https://materialdesignicons.com/icon/ray-start-vertex-end)](https://materialdesignicons.com/icon/ray-start-vertex-end)
