### ISSUE TITLE
file-document-multiple

### ISSUE THREAD

**Issue by beardhatcode** [Templarian/MaterialDesign#5196]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/662538/83282328-b54e3c80-a1d9-11ea-8454-89be3a0b7407.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[a.zip](https://github.com/Templarian/MaterialDesign/files/4703001/a.zip)

**Comment by goyney** [comment]
[![file-document-multiple](https://materialdesignicons.com/icon/file-document-multiple)](https://materialdesignicons.com/icon/file-document-multiple)[![file-document-multiple-outline](https://materialdesignicons.com/icon/file-document-multiple-outline)](https://materialdesignicons.com/icon/file-document-multiple-outline)
