### ISSUE TITLE
notebook_add

### ISSUE THREAD

**Issue by dpeter99** [Templarian/MaterialDesign#5198]
I'm really new to this so I hope I did this correctly.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
Paste a preview of your icon here. You can generate one using our [preview generator]
![download](https://user-images.githubusercontent.com/7725817/83329477-0f0e3f80-a28a-11ea-99e8-8e04d1ff447a.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[notebook_add.zip](https://github.com/Templarian/MaterialDesign/files/4705668/notebook_add.zip)

**Comment by Templarian** [comment]
@dpeter99 Notice the grid and the position of the plus symbol on the grid. For this reason we'll use a cutout for this (aka overlay).

**Comment by dpeter99** [comment]
The idea came from the fact that the book has a variant with a plus (https://dev.materialdesignicons.com/icon/book-plus)[book-plus]

But yes I can see now that I forgot to align the plus to the grid

**Comment by goyney** [comment]
Added the plus, minus, and remove variants.
