### ISSUE TITLE
Currency UK Pound Sign

### ISSUE THREAD

**Issue by bowaybilly** [Templarian/MaterialDesign#5199]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Currency UK pound sign will be used in apps displaying currency for uk apps..

## Examples

My playstore app that shows members contribution amount paid in UK pounds.

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/currency-gbp)](currency-gbp)

Please make sure to search thoroughly before requesting.
