### ISSUE TITLE
wreck-boat

### ISSUE THREAD

**Issue by wizmo2** [Templarian/MaterialDesign#5200]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

needed for chart markers.
It's based this on Greenturtwigs sail-boat icon 

## Preview
![image](https://user-images.githubusercontent.com/11602094/83359572-0b8dbd80-a349-11ea-927a-25bcd8a3c4e0.png)

## Zip Download
[wreck-boat.zip](https://github.com/Templarian/MaterialDesign/files/4708146/wreck-boat.zip)

**Comment by Sjoerd82** [comment]
I saw the confused icon. Perhaps the current name (wreck-boat) isn't that great. Perhaps this should be called **shipwreck**, **boat-shipwreck**, **boat-wreck**, **boat-sinking**, **sail-boat-sinking** or **sail-boat-shipwreck**.

Keep an eye on **sail-boat** when designing this icon, to stay in the same style.
That said, I like the idea of this icon.

**Comment by goyney** [comment]
Here's an updated attempt based on our `sail-boat` being updated in a previous release.

![image](https://user-images.githubusercontent.com/1015040/133547665-b8f377b7-1071-49b7-8258-394bf16b5379.png)

[sail-boat.svg.zip](https://github.com/Templarian/MaterialDesign/files/7174835/sail-boat.svg.zip)

**Comment by goyney** [comment]
[![sail-boat-sink](https://materialdesignicons.com/icon/sail-boat-sink)](https://materialdesignicons.com/icon/sail-boat-sink)
