### ISSUE TITLE
dolphin

### ISSUE THREAD

**Issue by wizmo2** [Templarian/MaterialDesign#5201]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

This is part of a small series of marine mammal icons 

## Preview
![image](https://user-images.githubusercontent.com/11602094/83359706-febd9980-a349-11ea-8bc0-60af68e079b5.png)

## Zip Download
[dolphin.zip](https://github.com/Templarian/MaterialDesign/files/4708157/dolphin.zip)

**Comment by Xenomorph99** [comment]
How about something like this?

![dolphin](https://user-images.githubusercontent.com/1837101/95391624-99a82080-08b4-11eb-9f99-f7f335fd996f.png)

[dolphin.zip](https://github.com/Templarian/MaterialDesign/files/5344018/dolphin.zip)

**Comment by goyney** [comment]
[![dolphin](https://materialdesignicons.com/icon/dolphin)](https://materialdesignicons.com/icon/dolphin)
