### ISSUE TITLE
shark

### ISSUE THREAD

**Issue by wizmo2** [Templarian/MaterialDesign#5202]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Part of a small series of marine mammals

## Preview
![image](https://user-images.githubusercontent.com/11602094/83359817-a9ce5300-a34a-11ea-86d7-79eda70bcb60.png)

## Zip Download
[shark.zip](https://github.com/Templarian/MaterialDesign/files/4708164/shark.zip)

**Comment by Xenomorph99** [comment]
How about this for `shark`?

![shark](https://user-images.githubusercontent.com/1837101/95274476-34482700-0803-11eb-82e2-9e034b559acc.png)

Here's an `outline` version too, but I had to remove the mouth because it didn't read well.

![shark-outline](https://user-images.githubusercontent.com/1837101/95274475-34482700-0803-11eb-8bfd-be6d33d0af4c.png)

I also thought it would be fun to have a `fin` variant based on [water-polo](https://materialdesignicons.com/icon/water-polo).

![shark-fin](https://user-images.githubusercontent.com/1837101/95274474-33af9080-0803-11eb-9752-9e5ccd06efb1.png)

[shark.zip](https://github.com/Templarian/MaterialDesign/files/5337654/shark.zip)

**Comment by Xenomorph99** [comment]
Actually, here's a better version of `shark-fin` with `shark-fin-outline` as a variant.

![shark-fin](https://user-images.githubusercontent.com/1837101/95280766-0074fd80-0813-11eb-91c9-1437e28f89c3.png)
![shark-fin-outline](https://user-images.githubusercontent.com/1837101/95280765-ffdc6700-0812-11eb-9049-57dec508882d.png)

[shark-fin.zip](https://github.com/Templarian/MaterialDesign/files/5337938/shark-fin.zip)

**Comment by Templarian** [comment]
Shark outline doesn't really work, but the fin ones are great.

I'm thinking that a literal shark is too detailed maybe (really good job though on the design)?

**Comment by Xenomorph99** [comment]
Here's another idea:
![shark](https://user-images.githubusercontent.com/1837101/95282204-2e0f7600-0816-11eb-82e9-6db3126574a4.png)
[shark.zip](https://github.com/Templarian/MaterialDesign/files/5338009/shark.zip)

The shark needs something in order for it to not look like a fish. Maybe without the gills just the angry eye and the mouth are enough.

What if we add this one as `shark` and the one I previously posted as `shark-variant` and we ignore the outlined version?

**Comment by Templarian** [comment]
Added the `shark-fin` and `shark-fin-outline`. Leaving open for more input.

**Comment by Xenomorph99** [comment]
I stretched the shark shape a little wider and made some other adjustments. This version is looking way better I think.

![shark](https://user-images.githubusercontent.com/1837101/95352372-6bf4b480-087f-11eb-9205-4423382e6ed7.png)
![shark-off](https://user-images.githubusercontent.com/1837101/95352369-6b5c1e00-087f-11eb-9b6d-b6adae78e4b4.png)

[shark.zip](https://github.com/Templarian/MaterialDesign/files/5341817/shark.zip)

**Comment by goyney** [comment]
[![shark](https://materialdesignicons.com/icon/shark)](https://materialdesignicons.com/icon/shark)[![shark-off](https://materialdesignicons.com/icon/shark-off)](https://materialdesignicons.com/icon/shark-off)
[![shark-fin](https://materialdesignicons.com/icon/shark-fin)](https://materialdesignicons.com/icon/shark-fin)[![shark-fin-outline](https://materialdesignicons.com/icon/shark-fin-outline)](https://materialdesignicons.com/icon/shark-fin-outline)

(BTW, I really love your first shark attempt.)
