### ISSUE TITLE
man-overboard

### ISSUE THREAD

**Issue by wizmo2** [Templarian/MaterialDesign#5204]
I have:

- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Searched open issues to make sure there isn't a request for this icon.
- [ x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

needed as chart marker

## Preview
![image](https://user-images.githubusercontent.com/11602094/83360006-1564f000-a34c-11ea-8d49-155ad1788296.png)

## Zip Download
[man-overboard.zip](https://github.com/Templarian/MaterialDesign/files/4708178/man-overboard.zip)

Let me know if you have issues with this file.  Ut did not render correctly in the custom icon generator, but works in other apps.

**Comment by Templarian** [comment]
Duplicate `lifebuoy`

**Comment by Templarian** [comment]
Added another alias `overboard`
