### ISSUE TITLE
phone with click for redial

### ISSUE THREAD

**Issue by GaborTorma** [Templarian/MaterialDesign#5206]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

~I need~ A phone icon like this (phone-cancel), but clock icon (mdiAlarm) instead of cancel.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@GaborTorma Do not delete the issue templates. I've pasted it back in above. This helps us process requests.

**Comment by goyney** [comment]
A clock isn't going to work, but if you're looking for something meaning redial, one of these should suffice:

[![phone-sync](https://materialdesignicons.com/icon/phone-sync)](https://materialdesignicons.com/icon/phone-sync)[![phone-sync-outline](https://materialdesignicons.com/icon/phone-sync-outline)](https://materialdesignicons.com/icon/phone-sync-outline)

[![phone-refresh](https://materialdesignicons.com/icon/phone-refresh)](https://materialdesignicons.com/icon/phone-refresh)[![phone-refresh-outline](https://materialdesignicons.com/icon/phone-refresh-outline)](https://materialdesignicons.com/icon/phone-refresh-outline)
