### ISSUE TITLE
Website flagged as malware/malicious software due to icon class name

### ISSUE THREAD

**Issue by palfaro91** [Templarian/MaterialDesign#5207]
Hello,
We've been using this library for quite some time now but more recently some of our websites have been flagged as "malicious software" by Google when creating Google Ads and linking the ad to our site. We ran a check through an online malware checker and it returned this 

> The tool found a number of terms, pharmacy, sunglasses, shoe, purse, poker, that are common terms found in spam hacks

The only reference to those terms are in the mdi css classes. We are using @mdi/font version 4.7.95.

Has anyone else experienced this issue before?

**Comment by Templarian** [comment]
We purposefully don't include the term `ad`, `advert`, `advertisement`, `banner`, and a few other words.

Unfortunately we can't fix such an issue and will recommend not using the webfont. This must be a new check they've implemented recently.

http://dev.materialdesignicons.com/guide/webfont-alternatives

**Comment by Templarian** [comment]
Please search here if you see anything: https://support.google.com/google-ads/community?hl=en

If you reach out to their support please link to this issue and let us know.

**Comment by palfaro91** [comment]
We were using webfont specifically because of this line: 

> In a scenerio where the frontend does not know all required icons it may be ideal to use the webfont.

But ok, I will have to check with Google. Thanks!

**Comment by Templarian** [comment]
@palfaro91 We have a solution for that in a prototype state. Unfortunately it won't be ready for a bit. 😢

**Comment by goyney** [comment]
> We purposefully don't include the term `ad`, `advert`, `advertisement`, `banner`, and a few other words.
> 
> Unfortunately we can't fix such an issue and will recommend not using the webfont. This must be a new check they've implemented recently.
> 
> http://dev.materialdesignicons.com/guide/webfont-alternatives

We should honestly relax this restriction. We have several open issues that haven't been added because we don't know how to name them. People should NOT be using the webfont anymore. We honestly need to deprecate it and remove it at v6.0.0.

**Comment by Templarian** [comment]
Once we have a nice solution documented with a drop in implementation similar to the webfont we'll do just that. Might have it ready for the 6.0 release maybe. It's going to be very similar to what the new site uses for caching icon data.

**Comment by goyney** [comment]
There's not much more that can be done in this issue. Our official recommendation if you're running into these issues is to use anything but the webfont. If you absolutely have to use the webfont (you don't!), you'll need to wait until we come up with our new solution that @Templarian spoke about. Keep an eye on [our official Twitter account](https://twitter.com/materialicons) for announcements regarding that.
