### ISSUE TITLE
Double and tripple switchplates with switch identifying variants

### ISSUE THREAD

**Issue by joshtbw** [Templarian/MaterialDesign#5208]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

In my home assistant setup, I would like to be able to have an icon for the indication of which switch this is in a plate that may have two or three switches. I can see it laid out like a UK switch plate with one or two switches, the variants would have an indication of which switch amongst the group is indicated. This could be an inverse of the switch colour or it could be my some indicating mark.

## Examples

Include any example images so we know what the icon should look like.

**Comment by joshtbw** [comment]
Here are some examples I've mocked up:

![Blank Diagram](https://user-images.githubusercontent.com/40309755/83758242-a6e4a280-a669-11ea-833f-eb7f67ef0527.jpeg)

**Comment by goyney** [comment]
I do not see these as being possible in the small space we have available. Additionally, I don't see the value; these seem very niche. Especially since a single control (in Home Assistant, for example) is tied to a single switch. I just can't see a use case for these.

**Comment by Templarian** [comment]
Yeah, was looking at this issue yesterday. It ends up looking like a taller `card` with random cuts.

Nice idea for a store product, but would need a larger size and maybe duo-tone to correctly convey.
