### ISSUE TITLE
Icon request: pawn chess piece

### ISSUE THREAD

**Issue by doeixd** [Templarian/MaterialDesign#521]
- [x] chess-pawn
- [x] chess-rook
- [x] chess-queen
- [x] chess-bishop
- [x] chess-horse
- [x] chess-king

**Comment by infanf** [comment]
Bishop
![chess-bishop](https://cloud.githubusercontent.com/assets/8826710/12079052/500ba5ee-b22b-11e5-82a6-374cf30d2377.png) ![chess-bishop-48](https://cloud.githubusercontent.com/assets/8826710/12079053/50233042-b22b-11e5-956d-20feb6038651.png) ![chess-bishop-96](https://cloud.githubusercontent.com/assets/8826710/12079054/502ee86a-b22b-11e5-908c-d8c02e1b6c7e.png)
King
![chess-king](https://cloud.githubusercontent.com/assets/8826710/12079055/50313c6e-b22b-11e5-8843-f65eef51458c.png) ![chess-king-48](https://cloud.githubusercontent.com/assets/8826710/12079056/5031c332-b22b-11e5-8802-202e2ef374fe.png) ![chess-king-96](https://cloud.githubusercontent.com/assets/8826710/12079057/503345e0-b22b-11e5-9cc2-6c7cab6a552f.png)
Knight
![chess-knight](https://cloud.githubusercontent.com/assets/8826710/12079059/5037c3ea-b22b-11e5-8541-4a30f4f77cef.png) ![chess-knight-48](https://cloud.githubusercontent.com/assets/8826710/12079058/50379384-b22b-11e5-84db-f7bab61f11fd.png) ![chess-knight-96](https://cloud.githubusercontent.com/assets/8826710/12079060/50431d6c-b22b-11e5-91c9-671fdb28d9cd.png)
Pawn
![chess-pawn](https://cloud.githubusercontent.com/assets/8826710/12079062/50486236-b22b-11e5-860c-536d40d49663.png) ![chess-pawn-48](https://cloud.githubusercontent.com/assets/8826710/12079061/504778b2-b22b-11e5-90a2-748562d457e8.png) ![chess-pawn-96](https://cloud.githubusercontent.com/assets/8826710/12079063/5048d7ac-b22b-11e5-984b-5657578baf23.png)
Queen
![chess-queen](https://cloud.githubusercontent.com/assets/8826710/12079065/5051911c-b22b-11e5-82f0-a162345da870.png) ![chess-queen-48](https://cloud.githubusercontent.com/assets/8826710/12079064/50501436-b22b-11e5-9f7e-1c5b06827593.png) ![chess-queen-96](https://cloud.githubusercontent.com/assets/8826710/12079066/50589340-b22b-11e5-9aae-bdad464cb4fe.png)
Rook
![chess-rook](https://cloud.githubusercontent.com/assets/8826710/12079067/505c31ee-b22b-11e5-94de-d1e710525518.png) ![chess-rook-48](https://cloud.githubusercontent.com/assets/8826710/12079069/50614b98-b22b-11e5-80af-86e94523dd9b.png) ![chess-rook-96](https://cloud.githubusercontent.com/assets/8826710/12079068/505fddd0-b22b-11e5-93b9-dc41452b5de6.png)
zipped SVGs
[chess.zip](https://github.com/Templarian/MaterialDesign/files/76616/chess.zip)

**Comment by MrGrigri** [comment]
I believe that those icons do not follow MD guidelines. Here is what I propose.

![image](https://user-images.githubusercontent.com/4528551/34892631-3cf6be4a-f797-11e7-9a7a-be151c0833db.png) ![image](https://user-images.githubusercontent.com/4528551/34892752-afdccf1c-f797-11e7-9cf8-191c47c9a783.png) ![image](https://user-images.githubusercontent.com/4528551/34892792-cd49873e-f797-11e7-8896-6ce442650c62.png) ![image](https://user-images.githubusercontent.com/4528551/34892830-ecbdb964-f797-11e7-946f-a212f11519a1.png) ![image](https://user-images.githubusercontent.com/4528551/34892851-01748522-f798-11e7-949d-e151b583745d.png) ![image](https://user-images.githubusercontent.com/4528551/34892867-0de14462-f798-11e7-9e1d-6d8c686e5145.png)

[chess.zip](https://github.com/Templarian/MaterialDesign/files/1627306/chess.zip)

**Comment by GreenTurtwig** [comment]
Should probably give `chess-rook` the alias `chess-castle`.

**Comment by MrGrigri** [comment]
As well as `chess-knight` with `horse`, `challenge`, and `strategy`; see #555.

**Comment by Templarian** [comment]
These are all added. 😃
