### ISSUE TITLE
lock-money

### ISSUE THREAD

**Issue by KarBoy2314PL** [Templarian/MaterialDesign#5210]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

something locked behind a paywall

## Examples

google's lock with the keyhole of currency-usd

**Comment by Templarian** [comment]
We don't add overlays to the `currency-usd` since there are too many currency icons.

Would the `cash` + `lock` suffice?

**Comment by KarBoy2314PL** [comment]
fine

**Comment by Templarian** [comment]
@KarBoy2314PL We don't have that icon currently, so leaving this opened until it is added.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/83936203-e0f79680-a786-11ea-9db5-9b1a9371643d.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/83936276-c2de6600-a787-11ea-9915-34caab2cfca5.png)

Should probably add the `cash-lock-open`.

**Comment by Templarian** [comment]
Forgot to close this. These were added the other day.
