### ISSUE TITLE
Halaal icon

### ISSUE THREAD

**Issue by mariomos** [Templarian/MaterialDesign#5211]
I have a request, i am looking for a 'Halaal' icon.

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by mariomos** [comment]
Thank you for your response🙏🏽🙌🏽😊

**Comment by Templarian** [comment]
Our of curiosity how are you using this icon @mariomos? Thinking if we should add it, but don't have context for it's use in an application/website/print etc?

Screenshots would be helpful for this content.

**Comment by JapanYoshi** [comment]
Not OP, but here's something I whipped up. It's supposed to be a restaurant finder app, with dietary restrictions displayed as icons on each listing.

![halal-example](https://user-images.githubusercontent.com/8707990/83846229-a291b580-a74d-11ea-9cc0-050a8094160b.png)

From left to right: "Serves meat", "Serves fish", "Vegan options", "Egg-free options", "Dairy-free options", "Gluten-free options", and "Halal".

**Comment by Templarian** [comment]
Lets add these as it's probably useful in the example shown.

I'm going to close this issue and open the other one that contains the two icons.

Thanks @JapanYoshi for the clear example.
