### ISSUE TITLE
Fan H/M/L

### ISSUE THREAD

**Issue by johnkread** [Templarian/MaterialDesign#5213]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home Assistant button to set a fan to high medium low

## Examples

Just like the fan 1/2/3 just L/M/H

**Comment by goyney** [comment]
1, 2, and 3 were used intentionally to prevent a language conflict. We will not be adding these.

**Comment by JapanYoshi** [comment]
Most fans have numeric 1, 2, and 3 markings anyway.
