### ISSUE TITLE
clipboard-edit

### ISSUE THREAD

**Issue by alisonmoura** [Templarian/MaterialDesign#5214]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![clipboard-edit](https://user-images.githubusercontent.com/8182696/83931812-a5e86980-a76c-11ea-90cb-caef0bbd84e3.png)

## Zip Download

[clipboard-edit.zip](https://github.com/Templarian/MaterialDesign/files/4739095/clipboard-edit.zip)

**Comment by goyney** [comment]
While we appreciate the nice looking preview, we ask you please use the official preview generator. This assures the path has been combined properly and allows us to evaluate the design against the grid, which is very important.

http://dev.materialdesignicons.com/contribute/github

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/83937541-14d8b900-a793-11ea-815c-3bd4ccafd73c.png)

**Comment by Templarian** [comment]
Here is what it looks like with the standard overlay / cutout size.

![image](https://user-images.githubusercontent.com/338885/83937644-4ef68a80-a794-11ea-9beb-dbe45a01d574.png)

**Comment by Templarian** [comment]
Added:

- `clipboard-edit`
- `clipboard-edit-outline`

**Comment by alisonmoura** [comment]
Thanks! @goyney sorry about that, I didn't see it. Next time I'll do it :D

**Comment by goyney** [comment]
Not a problem. I've actually had talks with @Templarian before about making our previews look nicer. 😄  The grid is the most important part though.

**Comment by JapanYoshi** [comment]
Yeah, the grid is important, but it would definitely help if you could also see the icons in light and dark mode colors like in the preview OP made.

**Comment by alisonmoura** [comment]
I totally agree @goyney! The functional value of the grid is clearly needful 😄 I feel happy to help, let me know if you need something 👍
