### ISSUE TITLE
kho-kho

### ISSUE THREAD

**Issue by taru1610** [Templarian/MaterialDesign#5216]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@taru1610 Those sections in the template are not optional. Paste examples and provide context so the team has something to go off of.

**Comment by taru1610** [comment]
> @taru1610 Those sections in the template are not optional. Paste examples and provide context so the team has something to go off of.

Logo representing one person sitting in kho kho position and other just about to run

**Comment by Templarian** [comment]
Interesting, yeah, not sure we can represent this in such a small icon. Looking around I don't see any good icons as a starting point.

Just watched a video to understand what kho kho. I'll leave this open for a while to see if anyone can think of a design that will work.

**Comment by taru1610** [comment]
https://images.app.goo.gl/S2D33P3FDREgc78U7

**Comment by taru1610** [comment]
> Interesting, yeah, not sure we can represent this in such a small icon. Looking around I don't see any good icons as a starting point.
> 
> Just watched a video to understand what kho kho. I'll leave this open for a while to see if anyone can think of a design that will work.

https://images.app.goo.gl/S2D33P3FDREgc78U7

**Comment by JapanYoshi** [comment]
![khokho-draft0](https://user-images.githubusercontent.com/8707990/84650518-c02ffd80-af4b-11ea-8c1a-12643d766eff.png)
Made a draft based on the icon used for the South Asian Games (not like I'm from a participating country or I was aware of its existence until 10 minutes ago).

**Comment by taru1610** [comment]
> ![khokho-draft0](https://user-images.githubusercontent.com/8707990/84650518-c02ffd80-af4b-11ea-8c1a-12643d766eff.png)
> Made a draft based on [the icon used for the South Asian Games](https://commons.wikimedia.org/wiki/File:Kho_kho_pictogram.svg) (not like I'm from a participating country or I was aware of its existence until 10 minutes ago).

Thankyou , great work

**Comment by taru1610** [comment]
> > ![khokho-draft0](https://user-images.githubusercontent.com/8707990/84650518-c02ffd80-af4b-11ea-8c1a-12643d766eff.png)
> > Made a draft based on [the icon used for the South Asian Games](https://commons.wikimedia.org/wiki/File:Kho_kho_pictogram.svg) (not like I'm from a participating country or I was aware of its existence until 10 minutes ago).
> 
> Thankyou , great work

But, this isn't available in material design package provided by flutter

**Comment by JapanYoshi** [comment]
The path data for the merged icon is:

    M 12,1 V 2 L 11.234375,1.3574219 7.7558594,5.5097656 11,7.5078125 V 5.15625 L 10.775391,5.0175781 12,3.5585938 V 23 h 2 v -9.757812 l 1.931641,-1.931641 c 2.587592,0.403398 5.193802,-0.951615 6.724609,-2.482422 L 21.242188,7.4140625 c -1.143578,1.1435764 -3.5462,2.1914298 -5.226563,1.84375 L 14,7.2441406 V 1 Z m 5,3 A 2,2 0 0 0 15,6 2,2 0 0 0 17,8 2,2 0 0 0 19,6 2,2 0 0 0 17,4 Z M 11,7.7578125 7.0996094,11.65625 c -1.8493262,1.848688 -2.788807,3.194904 -4.0351563,6.501953 l 1.8710938,0.707031 C 5.9413591,16.196423 6.6598128,15.137242 7.8652344,13.835938 L 9.2226562,15.193359 4.2714844,20.142578 5.6855469,21.556641 11,16.242188 Z

**Comment by Templarian** [comment]
Added.
