### ISSUE TITLE
Expand icon and Collapse icon

### ISSUE THREAD

**Issue by Taschenbuch** [Templarian/MaterialDesign#5218]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Can be used in a tree next to a tree node to expand/collapse the tree node

## Examples

like the + and - icon in this picture
![grafik](https://user-images.githubusercontent.com/43114787/83943763-cbbe4e80-a7fe-11ea-80d8-68a26049e9be.png)

expand icon: single + with a border around it (outlined and not outlined version)
collapse icon: single - with a border around it (outlined and not outlined version)

They should look like the existing icons collapse-all and expand-all. But with only a single square and not a stack of squares:
![grafik](https://user-images.githubusercontent.com/43114787/83943723-99145600-a7fe-11ea-9514-3f356aaf6ba9.png)
![grafik](https://user-images.githubusercontent.com/43114787/83943732-a16c9100-a7fe-11ea-8efc-8a38cd08568a.png)

**Comment by Templarian** [comment]
Could you use `plus-box-multiple` for this?

**Comment by Taschenbuch** [comment]
@Templarian perfect! how could i missed those... `minus-box` `plus-box.` I searched too much for "expand".

**Comment by Templarian** [comment]
The new search we're making for the new site will cut down on this confusion. Can't wait to launch it. 😄 

![image](https://user-images.githubusercontent.com/338885/83949831-91978180-a7eb-11ea-9512-99aaa8e74c90.png)
