### ISSUE TITLE
Tie: wider alternative for improved legibility

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#522]
The existing [thin tie](https://materialdesignicons.com/icon/tie) a little hard to read at 24px, thus I tried something more like the logo of [FontAwesome Black Tie](http://blacktie.io/):

![tie-alternative](https://cloud.githubusercontent.com/assets/1309249/8845685/6dba1444-3121-11e5-84e1-10cab70f81fa.png)

https://www.dropbox.com/s/k5mhrytfh8ndl4p/tie-alternative.svg?dl=0

**Comment by Templarian** [comment]
Updated.
