### ISSUE TITLE
Underfloor Heating icon

### ISSUE THREAD

**Issue by davidmackarill** [Templarian/MaterialDesign#5221]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Underfloor heating icon 

## Examples
To match the mid:radiator same arrows but with a floor squiggle design like this https://vectorified.com/download-image#floor-icon-8.png

**Comment by Nordicfastware** [comment]
Hello, I would be interested in this one as well. Is there any need for further input ?

**Comment by goyney** [comment]
I think out best option for this request would be a more generic heating coil (and it would help solve several other icon requests).

![image](https://user-images.githubusercontent.com/1015040/159106558-a0847adc-1df1-4c02-91a7-9f98792e8ed0.png)

[heating-coil.svg.zip](https://github.com/Templarian/MaterialDesign/files/8308565/heating-coil.svg.zip)

**Comment by goyney** [comment]
[![heating-coil](https://materialdesignicons.com/icon/heating-coil)](https://materialdesignicons.com/icon/heating-coil)
