### ISSUE TITLE
account-supervisor-circle-outlined

### ISSUE THREAD

**Issue by hanselsen** [Templarian/MaterialDesign#5224]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

My app uses the outlined variant of icons where available.
There are still some icons not outlined.
This issue is for:

mdi-account-supervisor-circle

## Examples

https://material.io/resources/icons/?search=supervised_user&icon=supervised_user_circle&style=outline

**Comment by Templarian** [comment]
Added.
