### ISSUE TITLE
The old bitcoin icon...

### ISSUE THREAD

**Issue by oneezy** [Templarian/MaterialDesign#5225]
Hi, I'm requesting that you guys bring back the old **bitcoin** icon that was in version `4.9.95`

Don't get me wrong, I'm all for having the new bitcoin icon also. But due to a design issue, we're needing to use the one below.

![image](https://user-images.githubusercontent.com/7369575/84143591-73649800-aa1c-11ea-94b4-8d29ecb503a9.png)

---
you can see the difference in the top right of the header, and in the middle to the left of the `0.2153`

### BEFORE
![image](https://user-images.githubusercontent.com/7369575/84144071-41a00100-aa1d-11ea-93fb-536a19140c08.png)

### AFTER
![image](https://user-images.githubusercontent.com/7369575/84144102-52e90d80-aa1d-11ea-9f3f-0904b3e87956.png)

**Comment by Templarian** [comment]
Don't forget that `currency-btc` exists also.

**Comment by oneezy** [comment]
> 
> 
> Don't forget that `currency-btc` exists also.

I saw that also and was considering it. will probably just use the old svg for now.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-SVG/blob/v4.9.95/svg/bitcoin.svg

For anyone that runs across this and wonders how to view past versions. ^
