### ISSUE TITLE
book-check, notebook-check

### ISSUE THREAD

**Issue by dpuckett** [Templarian/MaterialDesign#5226]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Visually show something has been affirmatively read.

## Examples

Currently you have two icons that kind of do what I want, but not great. 
That would be the 'Book' and 'R Tick' (has read) icons. 

The book is nice, and the R Tick does what is needed but doesn't look great.

Please could the Book be combined with the Tick (Book Tick) to represent 'Has Read' in a more universally visual and appealing way.

**Comment by Templarian** [comment]
Added.

- `book-check` / `book-check-outline`
- `notebook-check` / `notebook-check-outline`
