### ISSUE TITLE
80 New official Google Material Design Icons

### ISSUE THREAD

**Issue by nils-fast** [Templarian/MaterialDesign#5227]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

I noticed, that Google has added new Icons to the official Material Design Icons-Set. 
I downloaded all new Icons and added them to a .zip.
## Zip Download

[Google Icons 10.6.2020.zip](https://github.com/Templarian/MaterialDesign/files/4759887/Google.Icons.10.6.2020.zip)

**Comment by Templarian** [comment]
Closing this as there is a solution forward. And it would be amazing if you could open issues for awesome ones we're missing. 🚀
