### ISSUE TITLE
clear icon

### ISSUE THREAD

**Issue by klompenrunner** [Templarian/MaterialDesign#5228]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The Developer Tools section in Chrome uses a circle with a backwards slash thru it as the Clear and Clear Console command. The icon also looks like the "not allowed" traffic sign.

Wikipedia calls this the no-symbol:
The general prohibition sign (official name, according to ISO 7010[1]), also known as a no symbol, no sign, circle-backslash symbol, nay, interdictory circle or universal no, is a red circle with (in some jurisdictions) a red diagonal line through it (running from top left to bottom right), completely enclosing a pictogram to indicate something is not permitted.
[https://en.wikipedia.org/wiki/No_symbol](https://en.wikipedia.org/wiki/No_symbol)

## Examples
![image](https://user-images.githubusercontent.com/11701178/84337573-e2023c80-ab67-11ea-8bc9-898f2543cb3b.png)

**Comment by Templarian** [comment]
This is confusing why our `cancel` icon is flipped. But when it's used like a modifier we have it correct.

This might be a bug?

**Comment by goyney** [comment]
Updated and added some more aliases so it can be found.
