### ISSUE TITLE
Google Icons: Transportation

### ISSUE THREAD

**Issue by nils-fast** [Templarian/MaterialDesign#5229]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Icons

- [x] `electric-bike`
- [x] `electric-car`
- [x] `electric-moped`
- [x] `electric-scooter`
- [x] `electric-rickshaw`
- [x] `pedal-bike`

## Zip Download

[GoogleTransportationIcons.zip](https://github.com/Templarian/MaterialDesign/files/4763889/GoogleTransportationIcons.zip)

**Comment by goyney** [comment]
All added.
