### ISSUE TITLE
bulletin board

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#523]
Idea: a board with a pinned note at it.

**Comment by CoDEmanX** [comment]
You could use `clipboard-outline` or `pin`. Not sure if it's possible to somehow combine a board with a pin or note...

**Comment by matthew2402** [comment]
Nah, this does not fit really well for me. But I will give it a try.
Close this issue for now and I'll reopen it if necassary.
Thanks man!

**Comment by CoDEmanX** [comment]
Maybe something really abstract then?
https://materialdesignicons.com/icon/view-dashboard
BTW, you can leave issues like this one open, someone might stumble upon it and have a great idea to visualize it.

**Comment by matthew2402** [comment]
Got this icon for another thing :)

**Comment by CoDEmanX** [comment]
What do you think of this?
![bulletin-board](https://cloud.githubusercontent.com/assets/1309249/8888328/8ce3a48c-32a9-11e5-9531-9eb02d7e1a45.png) https://www.dropbox.com/s/vwlk9gq7ekczh8b/bulletin-board.svg?dl=0

Inspired by Apple's F3 key icon.

**Comment by matthew2402** [comment]
This is great!
Thanks!

**Comment by CoDEmanX** [comment]
Looks a bit odd in my opinion:
![clipboard-notes](https://cloud.githubusercontent.com/assets/1309249/8894143/46121256-33ac-11e5-9fd7-9635ad489f46.png) https://www.dropbox.com/s/ppgp7domicdxaam/clipboard-notes.svg?dl=0

My bulletin board with a round wall hook:
![bulletin-board3](https://cloud.githubusercontent.com/assets/1309249/8894144/463baa30-33ac-11e5-9517-f4cb5e988da2.png) https://www.dropbox.com/s/sr4ugv52ywqdcl4/bulletin-board3.svg?dl=0

And with a triangular mounting (my favorite):
![bulletin-board2](https://cloud.githubusercontent.com/assets/1309249/8894145/463c1f42-33ac-11e5-86a0-f73e84a5704a.png) https://www.dropbox.com/s/xwsib4xe0tib6ff/bulletin-board2.svg?dl=0

**Comment by matthew2402** [comment]
Yeah, the last one is also my favorite! Great job ;)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/bulletin-board
