### ISSUE TITLE
Google Icons: UI

### ISSUE THREAD

**Issue by nils-fast** [Templarian/MaterialDesign#5230]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Icons

- [x] `admin` (Added as `shield-account-variant(-outline)`)
- [x] `addchart` (Added as `chart-box-plus-outline`)
- [ ] `analytics` - Going to hold off on this one for now. Too similar to `chart-box`.
- [ ] `api` - This isn't a standard visual indicator for an API, so we're going to defer on adding this right now.
- [x] `article` (Already exists as `text-box(-outline)`)
- [x] `calculate` (Added as `calculator-variant(-outline)`)
- [ ] `insights` - Meh. Use `chart-timeline-variant`.
- [x] `support` (Already exists as `lifebuoy`)
- [x] `quickreply` (Added as `message-flash(-outline)`)
- [x] `rule` (Added as `list-status`)
- [x] `motion-blur` (Added as `motion(-outline)`)
- [x] `comment-bank` (Added as `message-bookmark(-outline)`)
- [x] `block-flipped` would close #5228

## Zip Download

[GoogleUIIcons.zip](https://github.com/Templarian/MaterialDesign/files/4763967/GoogleUIIcons.zip)

**Comment by unitytotheunity** [comment]
I'm in need of just the addchart icon, but rather than making a new thread I hope it's okay to just bump this one.

![image](https://user-images.githubusercontent.com/13513869/87339337-761f4500-c514-11ea-9059-118595144d45.png)

**Comment by Templarian** [comment]
@unitytotheunity Thanks, yeah, we'll try and get all these added at once.

@goyney Might be a quick one to sync in.

**Comment by goyney** [comment]
Added `chart-box`, `chart-box-outline`, and `chart-box-plus-outline`. I'll look at the rest for our 5.5 release.

**Comment by goyney** [comment]
The majority of these will be in 5.5.
