### ISSUE TITLE
book-open-page-outline-variant

### ISSUE THREAD

**Issue by KasaP-AndroDev** [Templarian/MaterialDesign#5231]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to create Diary Application
![book-open-page-variant](https://user-images.githubusercontent.com/60508681/84488477-7ded8e80-acb5-11ea-8eb3-8eae10badfc3.png)

## Examples

Include any example images so we know what the icon should look like.

**Comment by KasaP-AndroDev** [comment]
Please design for me...

**Comment by KasaP-AndroDev** [comment]
!!!!!!!!!!!!!

**Comment by PeterShaggyNoble** [comment]
Found this in Google Photos:
```
M19,1 L14,6 L14,17 L19,12.5 L19,1 Z M21,5 L21,18.5 C19.9,18.15 18.7,18 17.5,18 C15.8,18 13.35,18.65 12,19.5 L12,6 C10.55,4.9 8.45,4.5 6.5,4.5 C4.55,4.5 2.45,4.9 1,6 L1,20.65 C1,20.9 1.25,21.15 1.5,21.15 C1.6,21.15 1.65,21.1 1.75,21.1 C3.1,20.45 5.05,20 6.5,20 C8.45,20 10.55,20.4 12,21.5 C13.35,20.65 15.8,20 17.5,20 C19.15,20 20.85,20.3 22.25,21.05 C22.35,21.1 22.4,21.1 22.5,21.1 C22.75,21.1 23,20.85 23,20.6 L23,19.5 L23,6 C22.4,5.55 21.75,5.25 21,5 Z M10,18.41 C8.75,18.09 7.51,18 6.5,18 C5.44,18 4.18,18.19 3,18.52 L3,7.13 C3.91,6.73 5.14,6.5 6.5,6.5 C7.86,6.5 9.09,6.73 10,7.13 L10,18.41 Z
```
![book-open-page-variant-outline](https://user-images.githubusercontent.com/15157491/86345673-c0bada80-bc53-11ea-8de4-2a07017e1f8b.png)

**Comment by goyney** [comment]
[![book-open-page-variant-outline](https://materialdesignicons.com/icon/book-open-page-variant-outline)](https://materialdesignicons.com/icon/book-open-page-variant-outline)
