### ISSUE TITLE
pokemon-go icon with a plus sign

### ISSUE THREAD

**Issue by schneiderEDU** [Templarian/MaterialDesign#5232]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

If you're programming a website or app, you could use this icon to label a button to add a new point of interest for pokemon go players.

## Examples

pokemon-go with a plus-sign similiar to the map-marker-plus icon

**Comment by goyney** [comment]
This was more of a fun icon that borderline shouldn't be in the pack. I'm not of the opinion we should add modifiers to it. @Templarian, thoughts?

**Comment by Templarian** [comment]
Correct, closing this out as it's not something we'll be expanding on. It was just a nice to have for the 🤓 community.
