### ISSUE TITLE
Pause

### ISSUE THREAD

**Issue by schora01** [Templarian/MaterialDesign#5233]
LifeMart has a carousel that rotates and they want to allow the user to pause the rotation.
When building a navigation bar they had to replace the Pause button with another button

**Comment by goyney** [comment]
What exactly is your request? We have a pause button. Several, in fact.

**Comment by JamesCoyle** [comment]
Please make sure you complete the issue template. Without examples it's impossible to understand what you are asking as we already have pause icons.

**Comment by schora01** [comment]
Hi,
You can close the ticket it wat by mistake.
