### ISSUE TITLE
Alias request for mdi-ev-station

### ISSUE THREAD

**Issue by Nanianmichaels** [Templarian/MaterialDesign#5234]
As suggested via Twitter, since my original search for "EV charger", "EVSE", and "Wallbox" left me scratching my head, and only after combing through the issues did I manage to find "mdi-ev-station", I propose that all of those terms can be aliased to "mdi-ev-station".

Eventually, it might be a good idea to have both the different EV plugs and the wallbox as icons, but since that's another completely different issue, I won't expand here.

Thanks in advance for considering these aliases.

**Comment by Templarian** [comment]
Oops, forgot to add these earlier. Done and a few others (like `electric-charger`).
