### ISSUE TITLE
EV Charging Plugs

### ISSUE THREAD

**Issue by Nanianmichaels** [Templarian/MaterialDesign#5235]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Apologies for not exactly following the "more than one icon request", but considering these are all related, I'm assuming opening 6 issues might be more taxing for the people dealing with this.

Seeing that, as far as I can tell, there are no icons for the most common EV plugs, I propose they are added, as per the below picture:

- Type 1/SAE J1772
- Type 2/Mennekes
- CCS (both Combo 1 and Combo 2)
- Tesla
- CHAdeMO

I also suggest each of the icons might also be aliased to " EV plug", "plug", and maybe "EV charger" and "charger".

Thank you in advance for considering adding these icons.

## Examples

![EV Plugs](https://user-images.githubusercontent.com/12832500/84580645-a0c09580-add0-11ea-95cd-e8a498192446.png)

Image taken from the Tesla forums for reference only, since it has the 6 connectors clearly shown. The "front-facing" designs should comply with the Material guidelines, I believe.

**Comment by goyney** [comment]
[![ev-plug-type1](https://materialdesignicons.com/icon/ev-plug-type1)](https://materialdesignicons.com/icon/ev-plug-type1)[![ev-plug-type2](https://materialdesignicons.com/icon/ev-plug-type2)](https://materialdesignicons.com/icon/ev-plug-type2)
[![ev-plug-ccs1](https://materialdesignicons.com/icon/ev-plug-ccs1)](https://materialdesignicons.com/icon/ev-plug-ccs1)[![ev-plug-ccs2](https://materialdesignicons.com/icon/ev-plug-ccs2)](https://materialdesignicons.com/icon/ev-plug-ccs2)
[![ev-plug-chademo](https://materialdesignicons.com/icon/ev-plug-chademo)](https://materialdesignicons.com/icon/ev-plug-chademo)[![ev-plug-tesla](https://materialdesignicons.com/icon/ev-plug-tesla)](https://materialdesignicons.com/icon/ev-plug-tesla)
