### ISSUE TITLE
mdi-handshake-outline

### ISSUE THREAD

**Issue by hanselsen** [Templarian/MaterialDesign#5237]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

My app uses the outlined variant of icons where available.
There are still some icons not outlined.
This issue is for:

mdi-handshake

## Examples

https://fontawesome.com/icons/hands-helping?style=light

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/89138460-a6ea0d00-d509-11ea-8971-90edac0c0d16.png)
[handshake-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/5013446/handshake-outline.svg.zip)

**Comment by goyney** [comment]
[![handshake-outline](https://materialdesignicons.com/icon/handshake-outline)](https://materialdesignicons.com/icon/handshake-outline)
