### ISSUE TITLE
Update Bootstrap Logo

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#5238]
https://twitter.com/getbootstrap/status/1272973565952847873

**Comment by PeterShaggyNoble** [comment]
From [this blog entry](https://blog.getbootstrap.com/2020/06/16/bootstrap-5-alpha/), it doesn't look like they'll be rebranding until they actually launch v5 so we should probably hold off until then. There's a SVG of the new logo available at https://v5.getbootstrap.com/

**Comment by goyney** [comment]
Bootstrap has been in v5 for a while now and their own official icon library set continues to use the older version of their logo. We're going to defer updating this unless that changes.
