### ISSUE TITLE
archive-alert

### ISSUE THREAD

**Issue by chpo69** [Templarian/MaterialDesign#5239]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Display information from a default archive.

## Examples

I think mix archive and alert icon disign. Existing examples : folder-alert or clock-alert.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/85649263-50ff8b00-b668-11ea-9719-f916a7c9301d.png) ![image](https://user-images.githubusercontent.com/338885/85649381-ab005080-b668-11ea-932d-ffb23f09e2b6.png)

**Comment by chpo69** [comment]
Hello,
It's very good! Thank you

**Comment by Templarian** [comment]
I'll close this once I add these two. 👍

**Comment by Templarian** [comment]
Added.
