### ISSUE TITLE
TTF font is not recognized.

### ISSUE THREAD

**Issue by kpect** [Templarian/MaterialDesign#5241]
Hello.
Starting from version 4.9.95 all new TTF font versions are not reflected in files fonts.dir and fonts.scale when you execute `mkfondir` and `mkfontscale` commands. Hence the font is not recognized by an application.
Regards,
Sergey.

**Comment by Templarian** [comment]
@kpect Are you using the desktop font? https://github.com/Templarian/MaterialDesign-Font

I need more context for this bug. What are those commands and why are you trying to run them on the TTF?

**Comment by kpect** [comment]
Here is what i do:

- download latest version of fonts
- unzip MaterialDesign-Webfont-master.zip
- mkdir tmp
- cp MaterialDesign-Webfont-master/fonts/materialdesignicons-webfont.ttf tmp/
- cd tmp
- mkfontscale && mkfontdir                                                                                                                                                                  
- ll
total 610
-rw-r--r--  1 x  x  uarch      2 17 июня  22:11 fonts.dir
-rw-r--r--  1 x  x  uarch      2 17 июня  22:11 fonts.scale
-rw-r--r--  1 x  x  uarch 899432 17 июня  22:10 materialdesignicons-webfont.ttf
- cat fonts.*
0
0

**Comment by kpect** [comment]
though version 4.9.95 is recognized as supposed to:
- grep material fonts.*                                                                                                                                                                     
fonts.dir:materialdesignicons-webfont.ttf -misc-material design icons-medium-r-normal--0-0-0-0-p-0-iso10646-1
fonts.dir:materialdesignicons-webfont.ttf -misc-material design icons-medium-r-normal--0-0-0-0-p-0-iso8859-6.16
fonts.scale:materialdesignicons-webfont.ttf -misc-material design icons-medium-r-normal--0-0-0-0-p-0-iso10646-1
fonts.scale:materialdesignicons-webfont.ttf -misc-material design icons-medium-r-normal--0-0-0-0-p-0-iso8859-6.16

**Comment by kpect** [comment]
Yes, desktop version - https://github.com/Templarian/MaterialDesign-Font/blob/master/MaterialDesignIconsDesktop.ttf doesn't work.

**Comment by kpect** [comment]
these commands mkfontscale && mkfontdir are required by Xorg to recognize them as fonts and to use them appropriately. Now I can only use 4.9.95

**Comment by Templarian** [comment]
This is probably going to take a while to figure out. Maybe see if you can convert one of the other font types and use that. Our build tooling is open source (it's used for both the webfont and the desktop fonts). That's why the bug exists in both.

We bumped all our versions in 5.0, so probably related to that.

https://github.com/Templarian/MaterialDesign-Font-Build

**Comment by Templarian** [comment]
Also, we need to document using the desktop fonts I suppose. Part of this will be listing these commands for Xorg.

**Comment by kpect** [comment]
Tried to convert from eot to ttf here: https://cloudconvert.com/eot-to-ttf
Got - "Converison failed" error ))

**Comment by kpect** [comment]
woff2 has been converted to ttf successfully, but nonetheless final file is not being recognized by mkfontscale && mkfontdir

**Comment by goyney** [comment]
@kpect It's been quite a few versions since you reported this issue. Is it still a problem with our latest font version? Can you further elaborate what/why you're trying to accomplish here that the standard font file cannot do?

**Comment by goyney** [comment]
Closing due to months of inactivity. We'll assume this is no longer an issue unless reported otherwise.
