### ISSUE TITLE
Ethnicity icon

### ISSUE THREAD

**Issue by brahboulkriaat** [Templarian/MaterialDesign#5242]
An icon to represent ethnicity: Black, Asian, Caucasian, etc.
![images](https://user-images.githubusercontent.com/28343145/84960927-4e9aaf80-b103-11ea-8af0-3c063196215e.png)
![94199-200](https://user-images.githubusercontent.com/28343145/84960948-58bcae00-b103-11ea-8446-f6fb65a89bca.png)

**Comment by Templarian** [comment]
But yeah, not adding these there are too many different variations to represent with a `24x24` icon. I would suggest using text for such a feature.

**Comment by JapanYoshi** [comment]
Just use emoji. ;)
