### ISSUE TITLE
Police car icon

### ISSUE THREAD

**Issue by SimonRijn** [Templarian/MaterialDesign#5244]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

My icon would be used in an emergency services app

## Examples

![40584910-ee2b5cb0-61ec-11e8-8764-5a24025de870](https://user-images.githubusercontent.com/20671637/85119744-83515880-b222-11ea-85cc-ad7c52e6023e.png)

**Comment by GreenTurtwig** [comment]
Has to be pushed up right to the edge annoyingly, unless the car is downsized.
![](https://user-images.githubusercontent.com/15905797/90990675-33cd3700-e59b-11ea-9806-2bd44d84a489.png)

Definitely not a fan of the light bar.
![](https://user-images.githubusercontent.com/15905797/90990730-adfdbb80-e59b-11ea-9901-ecf9c59bfcee.png)![](https://user-images.githubusercontent.com/15905797/90990742-c077f500-e59b-11ea-8ebc-79b1df443ffc.png)![](https://user-images.githubusercontent.com/15905797/90990748-cd94e400-e59b-11ea-9be9-00371c57754a.png)


[car-emergency.zip](https://github.com/Templarian/MaterialDesign/files/5115157/car-emergency.zip)

**Comment by goyney** [comment]
[![car-emergency](https://materialdesignicons.com/icon/car-emergency)](https://materialdesignicons.com/icon/car-emergency)
