### ISSUE TITLE
Teddy bear toys icon

### ISSUE THREAD

**Issue by nchieffo** [Templarian/MaterialDesign#5245]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
There is currently a pinwheel icon but it does not recall the idea of toys
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For example I would use it as an icon for children room

## Examples

https://www.flaticon.com/free-icon/toys_3081993?term=toy&page=1&position=9

**Comment by goyney** [comment]
[![teddy-bear](https://materialdesignicons.com/icon/teddy-bear)](https://materialdesignicons.com/icon/teddy-bear)
