### ISSUE TITLE
Progress questionable

### ISSUE THREAD

**Issue by valentingavran** [Templarian/MaterialDesign#5246]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Besides the existing progress icons, another one with a question mark would be very handy if the progress is not known.

## Examples

Like progress-check but with a question mark in the middle.

**Comment by goyney** [comment]
[![progress-question](https://materialdesignicons.com/icon/progress-question)](https://materialdesignicons.com/icon/progress-question)
