### ISSUE TITLE
water-minus & water-plus

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5248]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85368884-e96b0380-b4e0-11ea-95b3-18bee776a7f4.png)
![image](https://user-images.githubusercontent.com/2228347/85369361-d60c6800-b4e1-11ea-9e50-add7ce1b279c.png)

## Zip Download

[water-minus.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817497/water-minus.svg.zip)
[water-plus.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817518/water-plus.svg.zip)

**Comment by goyney** [comment]
We've decided all new modifiers should use the cut-out as opposed to being included in the object.

**Comment by jhil** [comment]
Thanks for the feedback. I might find time soon to make cut-out versions of these in the future. Would it be helpful if I also did it for the current `water-percent` icon?

**Comment by Xenomorph99** [comment]
![water-plus](https://user-images.githubusercontent.com/1837101/87340631-94317900-c505-11ea-96e9-cbbd920166ec.png)

![water-plus-outline](https://user-images.githubusercontent.com/1837101/87340605-87ad2080-c505-11ea-8a41-dbc5796f90ed.png)

![water-minus](https://user-images.githubusercontent.com/1837101/87340657-9eec0e00-c505-11ea-8134-108df99fd392.png)

![water-minus-outline](https://user-images.githubusercontent.com/1837101/87340674-a57a8580-c505-11ea-9f51-8d7076f90197.png)

[water-plus-minus.zip](https://github.com/Templarian/MaterialDesign/files/4914452/water-plus-minus.zip)

**Comment by Xenomorph99** [comment]
Here's a quick revision

![water-plus](https://user-images.githubusercontent.com/1837101/87363805-30bc4100-c52f-11ea-9384-1c731b424e2a.png)

![water-plus-outline](https://user-images.githubusercontent.com/1837101/87363803-3023aa80-c52f-11ea-86b4-4225eb099377.png)

![water-minus](https://user-images.githubusercontent.com/1837101/87363802-3023aa80-c52f-11ea-8287-193486c7381e.png)

![water-minus-outline](https://user-images.githubusercontent.com/1837101/87363801-2f8b1400-c52f-11ea-9167-1176bb25de67.png)



[water-plus-minus.zip](https://github.com/Templarian/MaterialDesign/files/4915654/water-plus-minus.zip)

**Comment by goyney** [comment]
[![water-plus](https://materialdesignicons.com/icon/water-plus)](https://materialdesignicons.com/icon/water-plus)[![water-plus-outline](https://materialdesignicons.com/icon/water-plus-outline)](https://materialdesignicons.com/icon/water-plus-outline)
[![water-minus](https://materialdesignicons.com/icon/water-minus)](https://materialdesignicons.com/icon/water-minus)[![water-minus-outline](https://materialdesignicons.com/icon/water-minus-outline)](https://materialdesignicons.com/icon/water-minus-outline)
