### ISSUE TITLE
transit-connection-horizontal

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5249]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85369297-b8d79980-b4e1-11ea-9a90-7486c8e45215.png)

## Zip Download

[transit-connection-horizontal.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817527/transit-connection-horizontal.svg.zip)

**Comment by goyney** [comment]
[![transit-connection-horizontal](https://materialdesignicons.com/icon/transit-connection-horizontal)](https://materialdesignicons.com/icon/transit-connection-horizontal)
