### ISSUE TITLE
Three books

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#525]
Ideas:
http://neueerde.de/bilder-shop-verlag-heilsteine/Vorspann/ne_icon_book.png
or
http://www.fh-kl.de/~zitt/images/icon_buecher.png

Maybe both? ;-)

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/book-multiple symbolized a variable amount of books, not just two. Your suggested icon could be a variant nonetheless.

**Comment by Templarian** [comment]
I think book multiple would suffice for these use cases.

Perspective on icons doesn't fit the style guidelines.
