### ISSUE TITLE
waves-two & waves-shore

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5250]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85369474-0522d980-b4e2-11ea-9a7c-ab34e2535c87.png)
![image](https://user-images.githubusercontent.com/2228347/85369418-efadaf80-b4e1-11ea-8e89-097738916e73.png)

## Zip Download

[waves-two.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817535/waves-two.svg.zip)
[waves-shore.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817534/waves-shore.svg.zip)

**Comment by Templarian** [comment]
Added `shore`, but not sure it's necessary for 2 waves icon.

**Comment by jhil** [comment]
Thanks for the feedback! With a waves-two icon, you can put it against the
wave and waves icon to communicate flow rate or water consumption, but
that's less possible.
