### ISSUE TITLE
dots-grid, dots-square, dots-triangle

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5251]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85370708-f9d0ad80-b4e3-11ea-8a96-5827323947a5.png)
![image](https://user-images.githubusercontent.com/2228347/85370775-15d44f00-b4e4-11ea-8c21-4e429534bd70.png)
![image](https://user-images.githubusercontent.com/2228347/85370750-0e14aa80-b4e4-11ea-8afe-05f782eeb8bf.png)

## Zip Download

[dots-grid.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817601/dots-grid.svg.zip)
[dots-square.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817602/dots-square.svg.zip)
[dots-triangle.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817603/dots-triangle.svg.zip)

**Comment by JapanYoshi** [comment]
What's the use case for this?

**Comment by jhil** [comment]
With the rise of Lidar technology, I anticipate use cases (and have some of my own) that involve precise selections of points in a point cloud. I figured extending the dots-vertical / dots-horizontal icons would be a good place to start!
- dots-grid can represent an array of points
- dots-square can represent exterior/perimeter points
- dots-triangle can represent a group of points, if dots-grid is being used to represent all points

There are a few more in the family that I was considering too.
- dot (single)
- dots with solid perimeters to represent focus states

**Comment by St-Ex-savadenn** [comment]
Could it be other type of focus ?

3 already exist : 
* focus-field
![focus-field](https://user-images.githubusercontent.com/65651015/85467495-9ad66b80-b5ab-11ea-86b1-7b1afbb2a52e.png)
* focus-field-horizontal
![focus-field-horizontal](https://user-images.githubusercontent.com/65651015/85467528-a2961000-b5ab-11ea-832a-33a61368683e.png)
* focus-field-vertical
![focus-field-vertical](https://user-images.githubusercontent.com/65651015/85467550-a6c22d80-b5ab-11ea-8e56-7c54f18644b4.png)

**Comment by goyney** [comment]
These 3 have been added.
