### ISSUE TITLE
flag-stripe

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5252]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85370974-69df3380-b4e4-11ea-868f-c5ae1b9f3b46.png)

## Zip Download

[flag-stripe.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817605/flag-stripe.svg.zip)

**Comment by Templarian** [comment]
We have `flag-checkered` for sports / racing. Not a huge sports person, so what one is this for?

**Comment by jhil** [comment]
I was thinking about it as a common national flag variant, but I actually
agree it should be scrapped after all.
