### ISSUE TITLE
sparkles

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5253]
An extension of `auto-fix` (aka magic/wand), these sparkles represent the magic product of the wand. Also inspired by ✨  and ❇️.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85373024-83ce4580-b4e7-11ea-8ba5-77134c8a1bd5.png)

## Zip Download

[sparkles.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817675/sparkles.svg.zip)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/85502177-69aa6b00-b5ac-11ea-85df-d9a0c5c9ac13.png)

The sparkles would need to be less uniformly placed. Not 100% on this one, but something like this.

**Comment by goyney** [comment]
[![sparkles](https://materialdesignicons.com/icon/sparkles)](https://materialdesignicons.com/icon/sparkles)
