### ISSUE TITLE
vector-square-open, vector-square-close

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5254]
_For advanced vector editing, like opening and closing shape paths._

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85375263-e37a2000-b4ea-11ea-81d1-16e47190b5ed.png)
![image](https://user-images.githubusercontent.com/2228347/85375287-ee34b500-b4ea-11ea-8951-915ce355ee10.png)

## Zip Download

[vector-square-open.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817843/vector-square-open.svg.zip)
[vector-square-close.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817842/vector-square-close.svg.zip)

**Comment by goyney** [comment]
[![vector-square-open](https://materialdesignicons.com/icon/vector-square-open)](https://materialdesignicons.com/icon/vector-square-open)[![vector-square-close](https://materialdesignicons.com/icon/vector-square-close)](https://materialdesignicons.com/icon/vector-square-close)
