### ISSUE TITLE
vector-polygon-variant

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5255]
_Since the current vector-polygon icon is off-kilter, this squared off version would be good for places where it might look too informal to use the current version._

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85375588-60a59500-b4eb-11ea-9c6a-21c106504b5e.png)

## Zip Download

[vector-polygon-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/4817865/vector-polygon-variant.svg.zip)

**Comment by goyney** [comment]
[![vector-polygon-variant](https://materialdesignicons.com/icon/vector-polygon-variant)](https://materialdesignicons.com/icon/vector-polygon-variant)
