### ISSUE TITLE
car-autonomous

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5256]
_A few options for autonomous cars. I think car-connected is great for use cases like CarPlay enabled vehicles, but something specific to self-driving cars would be helpful!_

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

_(I'm not sure why the preview generator isn't working, so these are Illustrator screenshots.)_

<img width="655" alt="CleanShot 2020-06-23 at 01 23 12@2x" src="https://user-images.githubusercontent.com/2228347/85379200-59cd5100-b4f0-11ea-9660-dfd8972bd1c4.png">
<img width="658" alt="CleanShot 2020-06-23 at 01 23 05@2x" src="https://user-images.githubusercontent.com/2228347/85379206-5b971480-b4f0-11ea-8058-d0e536f5128b.png">
<img width="651" alt="CleanShot 2020-06-23 at 01 22 22@2x" src="https://user-images.githubusercontent.com/2228347/85379222-605bc880-b4f0-11ea-939f-ef8bb427832f.png">
<img width="666" alt="CleanShot 2020-06-23 at 01 24 11@2x" src="https://user-images.githubusercontent.com/2228347/85379228-62258c00-b4f0-11ea-9887-58b878730c04.png">

## Zip Download

[car-autonomous-1.svg.zip](https://github.com/Templarian/MaterialDesign/files/4818090/car-autonomous-1.svg.zip)
[car-autonomous-2.svg.zip](https://github.com/Templarian/MaterialDesign/files/4818091/car-autonomous-2.svg.zip)
[car-autonomous-3.svg.zip](https://github.com/Templarian/MaterialDesign/files/4818092/car-autonomous-3.svg.zip)
[car-autonomous-4.svg.zip](https://github.com/Templarian/MaterialDesign/files/4818094/car-autonomous-4.svg.zip)

**Comment by goyney** [comment]
See if you can do something with the icon added here: https://github.com/Templarian/MaterialDesign/issues/5244#issuecomment-689263499 and wifi type lines coming off the light.

**Comment by jhil** [comment]
Sure I'll take a stab at that soon. Good idea!

**Comment by goyney** [comment]
[![car-wireless](https://materialdesignicons.com/icon/car-wireless)](https://materialdesignicons.com/icon/car-wireless)
