### ISSUE TITLE
car-select

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5258]
_For selecting or following a vehicle._

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85380198-7ddd6200-b4f1-11ea-899a-1102d9f220b9.png)

## Zip Download

[car-select.svg.zip](https://github.com/Templarian/MaterialDesign/files/4818129/car-select.svg.zip)

**Comment by goyney** [comment]
[![car-select](https://materialdesignicons.com/icon/car-select)](https://materialdesignicons.com/icon/car-select)
