### ISSUE TITLE
sign-pole

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5259]
_Icon for sign pole/post or obelisks, stemming from the sign-X icon family._

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85380718-1d025980-b4f2-11ea-9923-daf13d68b6e5.png)

## Zip Download

[sign-pole.svg.zip](https://github.com/Templarian/MaterialDesign/files/4818148/sign-pole.svg.zip)

**Comment by Templarian** [comment]
Added.

You can view them as they are added here: https://dev.materialdesignicons.com/history
