### ISSUE TITLE
A brain

### ISSUE THREAD

**Issue by oxydron** [Templarian/MaterialDesign#526]
A brain icon :)

**Comment by CoDEmanX** [comment]
Takes a lot of fine details to not make it look like a walnut...
![brain](https://cloud.githubusercontent.com/assets/1309249/8886456/cce3cbdc-326a-11e5-9503-0a5e51f4d678.png)

**Comment by oxydron** [comment]
Very nice, **thanks** :D

**Comment by JamesCoyle** [comment]
![image](https://cloud.githubusercontent.com/assets/10384436/20860407/504da7d6-b96f-11e6-8d7b-395fffbb243e.png)

**Comment by karlinnolabs** [comment]
![thinking](https://cloud.githubusercontent.com/assets/19834601/25485615/711b2070-2b56-11e7-9b41-7fcc7c2c49b4.png)

How about a top view instead of a side view? Easier to avoid the walnut perhaps?

**Comment by CoDEmanX** [comment]
Still looks a bit nutty, but it seems much more doable.

**Comment by JapanYoshi** [comment]
![brain 10](https://cloud.githubusercontent.com/assets/8707990/25526465/94393990-2c4e-11e7-86b3-0404676c4fe3.png)
![brain](https://cloud.githubusercontent.com/assets/8707990/25526466/9466dc42-2c4e-11e7-952e-ef9e9f15c4fe.png)

I tried making a silhouette side view, inspired by the following graphic by Kurzgesagt: ![brain](http://kurzgesagt.org/wp-content/uploads/2016/07/060_Website-Project-MS-Video1_Kurzgesagt-Header.png)

**Comment by oxydron** [comment]
@JapanYoshi I think that your icon should represent, in some way, the spaghetti patterns on the brain. Maybe a single line forking to 2 lines maybe do the trick.

**Comment by JamesCoyle** [comment]
I'd personally just make the top arc have some curves.

**Comment by GreenTurtwig** [comment]
Google uses this icon:
https://cloud.google.com/_static/images/cloud/products/icons/machine-learning.svg
To represent machine learning, something similar could be done to make it fit in with Material.

**Comment by justinlawrence** [comment]
+1 from me!

**Comment by damianobarbati** [comment]
Brain is very much needed! We have machine learning everywhere / AI and typically a brain is the proper icon to mean "intelligence".

PS: @GreenTurtwig is google really using that icon? It really sucks to me :|

**Comment by MrGrigri** [comment]
@damianobarbati, Google is using it with the (cloud platform)[https://cloud.google.com/].

**Comment by damianobarbati** [comment]
I'd work off from the shape shared by @JamesCoyle or a stylized version of the following:
<img width="45" alt="screen shot 2018-01-30 at 16 18 31" src="https://user-images.githubusercontent.com/2225869/35574135-4285c9dc-05d9-11e8-8e73-34b399daa924.png">

**Comment by Croutonix** [comment]
I think this should be high priority, it has already been asked 9 times.

**Comment by karlinnolabs** [comment]
Given the current collapse of cambridge analytica we could always just pinch theirs, or at least the idea :) 

https://upload.wikimedia.org/wikipedia/en/thumb/b/b9/Cambridge_Analytica_logo.png/125px-Cambridge_Analytica_logo.png

**Comment by justinlawrence** [comment]
😂

**Comment by MrGrigri** [comment]
Here is my attempt. I used a 2-pixel stroke with rounded caps. 

![image](https://user-images.githubusercontent.com/4528551/40866583-b17ee7c8-65bb-11e8-8b1e-acf041d591b4.png)

[brain.zip](https://github.com/Templarian/MaterialDesign/files/2064377/brain.zip)

**Comment by justinlawrence** [comment]
Looking good!

**Comment by damianobarbati** [comment]
@MrGrigri nice one!

**Comment by PeterShaggyNoble** [comment]
Nice work, @MrGrigri, I really like that one.

How would it look, though, without the line separating the brainstem?

**Comment by MrGrigri** [comment]
Not good. I tried.

**Comment by Templarian** [comment]
[![brain](https://materialdesignicons.com/icon/brain)](https://materialdesignicons.com/icon/brain)

Removed a lot of points, but could probably cut out more.
