### ISSUE TITLE
point-cloud

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5260]
_I just submitted #5251 and think a point-cloud or dots-cluster icon would be helpful too!_

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85381832-37890280-b4f3-11ea-9e0f-bb5c9dff5873.png)

## Zip Download

[point-cloud.svg.zip](https://github.com/Templarian/MaterialDesign/files/4818212/point-cloud.svg.zip)

**Comment by goyney** [comment]
If we decide to add this, we'll need to figure out what to name it. A "point cloud" isn't accurate.

> A point cloud is a set of data points in space. Point clouds are generally produced by 3D scanners, which measure many points on the external surfaces of objects around them.

**Comment by goyney** [comment]
Added as `dots-hexagon`.
