### ISSUE TITLE
menu-book

### ISSUE THREAD

**Issue by benmosher** [Templarian/MaterialDesign#5261]
Apologies if I'm not understanding the process, but I would just like to be able to use the `menu book` icon from the sandbox, but it appears not to have been loaded.

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

<img width="123" alt="image" src="https://user-images.githubusercontent.com/3709196/85413400-c79d6b00-b538-11ea-9815-fabc9ba09239.png">

from https://petershaggynoble.github.io/MDI-Sandbox/extended/

**Comment by Templarian** [comment]
Interesting... `book-open-variant` should probably be renamed to `book-open-blank-variant`.

That will align with `book-open` better.

**Comment by Templarian** [comment]
Added.
