### ISSUE TITLE
When published svgIcon doesn't work

### ISSUE THREAD

**Issue by kidodevteam** [Templarian/MaterialDesign#5262]
Before compiled and published our project dosen't work when load svgIcon.
![image](https://user-images.githubusercontent.com/47394751/85435587-0d205f00-b55e-11ea-8129-0e2becb5efc3.png)

After we published i have got this error:

Error: Error retrieving icon :android! Unable to find icon with the name "android"

The same is happing in Stackblitz:

https://stackblitz.com/edit/mdi-material-example

![image](https://user-images.githubusercontent.com/47394751/85435502-ea8e4600-b55d-11ea-995d-d8a1b860d2e0.png)

**Comment by kidodevteam** [comment]
Hi Austin, you saw the problem on Stackblitz. Its the same problem i have here after project publish!

![image](https://user-images.githubusercontent.com/47394751/85443246-69d44780-b567-11ea-87e8-e09b3f76fa71.png)

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Angular-Material/pull/7 This might be related.

Looks like you're not copying to the assets directory. Not sure what is going on with Stackblitz exactly.

Either way, probably shouldn't use that package. The `mdi.svg` it's very much a legacy. We were going to deprecate the package during 5.0, but 5.x will be the last release. Use `@mdi/js`.

**Comment by kidodevteam** [comment]
Hi @Templarian sorry, but in our project we use Angular 7 and how did you say, i can't use @mdi/js, because this is for React project.
You have any example using injection .ts in Angular 7?

**Comment by Templarian** [comment]
@kidodevteam https://dev.materialdesignicons.com/getting-started/angular `@mdi/js` isn't react, you're thinking of `@mdi/react`. 😉

**Comment by kidodevteam** [comment]
Sorry! 👍 😩

**Comment by EdricChan03** [comment]
Hi @kidodevteam,

The issue you're facing was caused by me attempting to remove the external URL dependencies to the hosted `mdi.svg` file by instead using the [`@mdi/angular-material`](https://www.npmjs.com/package/@mdi/angular-material) but unfortunately it did not work, partially due to me accidentally linking the StackBlitz to GitHub. I'll see what I can do.
