### ISSUE TITLE
square-rounded, square-rounded-outline, shape-square-rounded-plus

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5263]
Useful for representing app icons and shapes for design tools. Uses the same dimensions as `rounded-corner`.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85509110-3d8dea80-b5aa-11ea-9efa-36feaa63acde.png)
![image](https://user-images.githubusercontent.com/2228347/85509345-ae350700-b5aa-11ea-9585-38f6e8deee6e.png)
![image](https://user-images.githubusercontent.com/2228347/85509314-9fe6eb00-b5aa-11ea-8613-33d5cbe598da.png)

## Zip Download

[square-rounded.svg.zip](https://github.com/Templarian/MaterialDesign/files/4823601/square-rounded.svg.zip)

[square-rounded-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/4823602/square-rounded-outline.svg.zip)

[shape-square-rounded-plus.svg.zip](https://github.com/Templarian/MaterialDesign/files/4823600/shape-square-rounded-plus.svg.zip)

**Comment by Templarian** [comment]
Added x 3. 👍  Keep these up (these are all assigned to you).

View: https://dev.materialdesignicons.com/history
