### ISSUE TITLE
tractor-plow

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5264]
Variant of tractor with a plow behind it.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85511751-f86bb780-b5ad-11ea-8761-2dbb7f0b22c9.png)

## Zip Download

[tractor-plow.svg.zip](https://github.com/Templarian/MaterialDesign/files/4823691/tractor-plow.svg.zip)

**Comment by goyney** [comment]
This needs some work. I think it's okay to break the 2dp padding because of the width of the glyph, but they way it's presented currently makes the plow look cut off.
