### ISSUE TITLE
Remove Mixer (and add Facebook Gaming?)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#5265]
Microsoft have [announced](https://blog.mixer.com/2020/06/22/the-next-step-for-mixer/) that they will be discontinuing their Mixer service effective the 22nd of July with accounts being transferred over to the new Facebook Gaming service.

We can, therefore, remove Mixer. But do we want to replace it with Facebook Gaming, given that we're winding down our support for brand icons altogether and that it's still relatively new (launched on the 15th of April), giving us no guarantees of _its_ longevity?

Here it is anyway, based on the SVG found in the footer at https://www.facebook.com/fbgaminghome/

[![facebook-gaming](https://user-images.githubusercontent.com/15157491/85545858-3f8c9380-b614-11ea-82f1-e0bb4dc7af8e.png)](https://github.com/Templarian/MaterialDesign/files/4824995/facebook-gaming.zip)

**Comment by JamesCoyle** [comment]
I don't think we should add this.

**Comment by Templarian** [comment]
It falls into our gaming branding which I believe is fine in this case. Dislike Facebook as much as the next person, but believe it's fair to have this and it also is an easy substitute in the next release.

**Comment by goyney** [comment]
I agree with @JamesCoyle.

**Comment by Templarian** [comment]
Fixed. 👍 

Not trying to dictator this one. It's just that we do usually allow gaming platforms and it's not something I'm planning to change in 5.0.
