### ISSUE TITLE
cellphone-iphone-notch

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5266]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/85668940-2c111500-b674-11ea-863d-9757ba8ef040.png)

## Zip Download

[cellphone-iphone-notch.svg.zip](https://github.com/Templarian/MaterialDesign/files/4829459/cellphone-iphone-notch.svg.zip)

**Comment by JapanYoshi** [comment]
As much as it pains me to say it, notched phones are widespread, and the iPhones with notches don't have a home button. A more generic ``cellphone-notched`` icon would fare better.

**Comment by Templarian** [comment]
This reminds me we'll most likely remove the `iPad` and `cellphone-iphone` / `cellphone-android` in 6.0 release. Need to mark those as deprecation probably.

They can all be represented with the generic cellphone now-a-days.
