### ISSUE TITLE
Other characters Keyboard symbol

### ISSUE THREAD

**Issue by cbalmeida** [Templarian/MaterialDesign#5268]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon to be used in keyboards that suggests more characters, like question mark, exclamation mark, hashtag, dollar symbol, etc.

## Examples
Something like this (but using the characters I mentioned above).

![Screen Shot 2020-06-25 at 10 40 48 AM](https://user-images.githubusercontent.com/6311815/85741369-5b556f80-b6d0-11ea-9f2d-e0de6cc8e83f.png)

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/85754665-9a2b0a00-b750-11ea-883a-ae5133ad93fe.png)

    M 2 7 L 2 14 L 4 14 L 4 7 L 2 7 z M 6 7 L 6 9 L 10 9 L 10 11 L 8 11 L 8 14 L 10 14 L 10 13 C 11.108 13 12 12.108 12 11 L 12 9 C 12 7.892 11.108 7 10 7 L 6 7 z M 15.800781 7 L 15.599609 9 L 14 9 L 14 11 L 15.400391 11 L 15.199219 13 L 14 13 L 14 15 L 15 15 L 14.800781 17 L 16.800781 17 L 17 15 L 18.400391 15 L 18.199219 17 L 20.199219 17 L 20.400391 15 L 22 15 L 22 13 L 20.599609 13 L 20.800781 11 L 22 11 L 22 9 L 21 9 L 21.199219 7 L 19.199219 7 L 19 9 L 17.599609 9 L 17.800781 7 L 15.800781 7 z M 17.400391 11 L 18.800781 11 L 18.599609 13 L 17.199219 13 L 17.400391 11 z M 2 15 L 2 17 L 4 17 L 4 15 L 2 15 z M 8 15 L 8 17 L 10 17 L 10 15 L 8 15 z

**Comment by cbalmeida** [comment]
Thank you very much!! That's exactly what I was lookin for! Very useful!

**Comment by PeterShaggyNoble** [comment]
We'll leave this open until the icon is finalised and added to our library, @cbalmeida.

**Comment by cbalmeida** [comment]
OK! Perfect!

**Comment by Templarian** [comment]
Added.
