### ISSUE TITLE
Increase / decrease decimcal places icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#527]
As known from spreadsheet application:

![decimal-places-decrease2](https://cloud.githubusercontent.com/assets/1309249/8894215/95f3f184-33ae-11e5-9939-433aa5d0e27f.png) https://www.dropbox.com/s/dped36z35bsfcqv/decimal-places-decrease.svg?dl=0
![decimal-places-increase2](https://cloud.githubusercontent.com/assets/1309249/8894214/95cd7bb2-33ae-11e5-8645-ccdd6d1fa09d.png) https://www.dropbox.com/s/663duzvlkdgeal3/decimal-places-increase.svg?dl=0

Very similar to Google Spreadsheet icons, using Roboto font.

**//edit:** slightly updated SVGs / icons (pixel-aligned arrow points, shortened arrow)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/decimal-increase
https://materialdesignicons.com/icon/decimal-decrease

**Comment by epelc** [comment]
Are the names backwards on this? Microsoft Excel(for macOS) has the names the other way.

![image](https://cloud.githubusercontent.com/assets/5204642/20272455/ea552a34-aa5b-11e6-8fdf-d7cf235d4acd.png)

Decreasing seems like it should be shifting to the right(removing a decimal place).
