### ISSUE TITLE
User with wrench

### ISSUE THREAD

**Issue by GiuseppeMobijay** [Templarian/MaterialDesign#5271]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

CRUD operation about technichal maintainer.
I need an icon like user one but with wrench (like mdiAccountQuestion but with wrench instead of question mark)

## Examples

--

**Comment by goyney** [comment]
[![account-wrench](https://materialdesignicons.com/icon/account-wrench)](https://materialdesignicons.com/icon/account-wrench)[![account-wrench-outline](https://materialdesignicons.com/icon/account-wrench-outline)](https://materialdesignicons.com/icon/account-wrench-outline)
