### ISSUE TITLE
telegram1

### ISSUE THREAD

**Issue by buxkala** [Templarian/MaterialDesign#5272]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
> ## Usage
> Provide some context of how your icon could be used.
> 
> ## Examples
> Include any example images so we know what the icon should look like.

**Comment by buxkala** [comment]
![telegram1](https://user-images.githubusercontent.com/67478660/85894439-00279800-b80a-11ea-907f-4a15c39b4c8f.png)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by Templarian** [comment]
Weird enough `telegram` is already an icon in the pack.

**Comment by goyney** [comment]
Yes, yes it is.
[![telegram](https://materialdesignicons.com/icon/telegram)](https://materialdesignicons.com/icon/telegram)

**Comment by goyney** [comment]
Also, as a FYI, this icon is deprecated and will be removed in the v6.0 release. More information here: https://github.com/Templarian/MaterialDesign/issues/5275
