### ISSUE TITLE
Air Conditioner binary sensor

### ISSUE THREAD

**Issue by antoweb** [Templarian/MaterialDesign#5273]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

AN icon tath raprsent air flow when air conditioner is on and no air when conditioner is off

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
I've added `hvac-off`, so would using `hvac` and `hvac-off` be enough for your request? If not, I'd also recommend following #2812.

[![hvac](https://materialdesignicons.com/icon/hvac)](https://materialdesignicons.com/icon/hvac)[![hvac-off](https://materialdesignicons.com/icon/hvac-off)](https://materialdesignicons.com/icon/hvac-off)

**Comment by antoweb** [comment]
Hi goyney many thanks thanks for the icons are fine.

**Comment by antoweb** [comment]
Hello,
mdi:hvac is good but when specify hvac-off no icon is displayed

**Comment by goyney** [comment]
`hvac-off` was just added and it will be released in our next version (v5.5), which is due out in the next week or two.

If you're looking to use it in Home Assistant, you'll need to wait to use it until after we release and they update to the new version and do a new release on their end. I personally usually open a PR to Home Assistant the day we release, so the turnaround is as quick as the Home Assistant release cycle. At this point, that could be roughly a month from now. Hope that helps clear up the lag.

**Comment by antoweb** [comment]
Ok. Thank you mdi:smile :-)
