### ISSUE TITLE
Remove telegram

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#5275]
This is a reminder issue. We plan on removing `telegram` in the v6.0 release in accordance with our brand icon policy.

We recommend using SimpleIcons for your brand icon needs. Telegram exists within that pack: https://simpleicons.org/?q=telegram

**Comment by zumoshi** [comment]
Can I ask why telegram in particular? There appears to be a lot of other brand icons (e.g. `mdi-skype`, `mdi-slack`, `mdi-teamviewer`, ...), neither of which are deprecated. IMHO either all of them should become deprecated or neither. Unless the brand icon policy isn't to just not have them, but only include those matching some criteria, But I failed to find what that policy is. Could you include a link to it?

Personally I think at least compared to Teamviewer, it is a more useful icon as a share target similar to twitter.

**Comment by TarNegar** [comment]
What is your problem with Telegram?
Are other brands (Facebook, Instagram, Twitter and so on) good and Telegram is bad?
Please rethink about removing Telegram from this iconset.

**Comment by JapanYoshi** [comment]
I agree that you should remove the icons for other messengers too, if Telegram is to be removed.

**Comment by Fusseldieb** [comment]
Some people use brand icons as other things, since they fit certain purposes. Removing them is kinda counterintuitive imo.

**Comment by goyney** [comment]
> Some people use brand icons as other things

You absolutely, positively **SHOULD NOT** be doing this. If you break a brand's guidelines for use, you are setting yourself up for all sorts of legal trouble.

**Comment by goyney** [comment]
This icon has now been removed.

**Comment by Skywalker13** [comment]
Why not just change a bit the icon and keep a mdi-paperplane instead ? It's missing...

**Comment by goyney** [comment]
It is not missing. See any of the `send` icons.
