### ISSUE TITLE
Remove cellphone-android, cellphone-iphone, tablet-ipad, laptop-chromebook, laptop-mac, laptop-windows

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#5276]
Cutting down on duplication.

- [x] `cellphone-android`
- [x] `cellphone-iphone`
- [x] `tablet-ipad`
- [x] `laptop-chromebook`
- [x] `laptop-mac`
- [x] `laptop-windows`

All tablets, phones, laptops look the same and can be representative by their logos instead.

**Comment by goyney** [comment]
These have all been marked as deprecated.

**Comment by Mancerrss** [comment]
What about keep them as legacy, or some sort of version history? Still downloadable somewhere.

As I'm still seeing some instances that I might need those icons too.

This is one of my main issues on using the official Material Design Icons website, some icons disappear entirely, even if they're not supposed to be disappear?

**Comment by goyney** [comment]
When we remove icons, we take a lot of thought into why it is appropriate to remove them. We then allow public forum like this for a considerable amount of time before removal. These icons go against our policy of adding device-specific icons, even if Google created most of them. Device-specific icons change way too frequently as device manufacturers iterate on their designs, so it is always better to use generic version. System icons are _supposed_ to be contextual anyways.

In terms of a history, these icons will be removed in our v6 release, which will likely be early in 2021. Anytime after that point, you can install an older version of the icon package or look at this repo's Git history to find the icons, but you'll need to engineer a solution if you wish to use them with a newer version the library. We, of course, recommend that you instead use the generic `cellphone` or `laptop` instead.

**Comment by Mancerrss** [comment]
Alright I understand. As long as the older repo stays as history, I'm cool with it.

**Comment by goyney** [comment]
This have all been removed.

**Comment by hotrungnhan** [comment]
these icon is so good, you can create a package for legacy icon which was remove ? may be some one need these ?

**Comment by goyney** [comment]
Please see the above comments for your answers.
