### ISSUE TITLE
Sort by date

### ISSUE THREAD

**Issue by iahdevelop** [Templarian/MaterialDesign#5278]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Similar to A-Z sorting but for dates. From oldest to newest, from newest to oldest.

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/87843804-16f76280-c87d-11ea-93d4-2697b747f9a1.png)

Probably need one with a clock also. But wondering if crushing the calendar makes sense for such an icon. 🤔 

/cc @goyney

**Comment by goyney** [comment]
I think that's fine. I'll get these added!

**Comment by goyney** [comment]
[![sort-calendar-ascending](https://materialdesignicons.com/icon/sort-calendar-ascending)](https://materialdesignicons.com/icon/sort-calendar-ascending)[![sort-calendar-descending](https://materialdesignicons.com/icon/sort-calendar-descending)](https://materialdesignicons.com/icon/sort-calendar-descending)
[![sort-clock-ascending](https://materialdesignicons.com/icon/sort-clock-ascending)](https://materialdesignicons.com/icon/sort-clock-ascending)[![sort-clock-descending](https://materialdesignicons.com/icon/sort-clock-descending)](https://materialdesignicons.com/icon/sort-clock-descending)
[![sort-clock-ascending-outline](https://materialdesignicons.com/icon/sort-clock-ascending-outline)](https://materialdesignicons.com/icon/sort-clock-ascending-outline)[![sort-clock-descending-outline](https://materialdesignicons.com/icon/sort-clock-descending-outline)](https://materialdesignicons.com/icon/sort-clock-descending-outline)
