### ISSUE TITLE
Milestone / land mark icon

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#528]
Inspired by GitHub milestone icon:
![milestone](https://cloud.githubusercontent.com/assets/1309249/8888264/7b04e0f8-32a6-11e5-87a3-07d192ea2477.png) https://www.dropbox.com/s/g5kwwddqdkh6n1n/milestone.svg?dl=0

The shape could be simplified by removing the end of the pole...

**Comment by CoDEmanX** [comment]
Two lighter variations:
![milestone2](https://cloud.githubusercontent.com/assets/1309249/8990304/92286d00-36f1-11e5-8968-c731ad9c0e8b.png)
![milestone3](https://cloud.githubusercontent.com/assets/1309249/8990305/9228b3b4-36f1-11e5-8217-d0b15e05194c.png)

**Comment by JamesCoyle** [comment]
Closing in favor of #1679.
