### ISSUE TITLE
CDN certificate cross signed with expired COMODO

### ISSUE THREAD

**Issue by GregersP** [Templarian/MaterialDesign#5280]
The TLS-certificate served on cdn.materialdesignicons.com is cross signed with the old/expired COMODO-root CA.
Though this does not affect many users, it does get reported by various SSL-checkers, and some users get a notification (due to high security focused settings, I guess). Anyhow, a cert signed or cross signed by a now expired root is worthless :-)

AFAIK the certificate can be reissued at no cost.

See: https://support.sectigo.com/articles/Knowledge/Sectigo-AddTrust-External-CA-Root-Expiring-May-30-2020#:~:text=Upcoming%20AddTrust%20Root%20Expiration%20%E2%80%93%20What,the%20end%20of%20May%2C%202020.

**Comment by GregersP** [comment]
Marked as "question" since I really do not like to call this a bug :-)

**Comment by Templarian** [comment]
Wonder if it would be worth my time to finally switch it with a letsencrypt. Always need to be really careful messing with that stuff since the CDN burns through amost 30TB a month right now. One bad setting and 🔥 .

**Comment by goyney** [comment]
Considering the cdn.materialdesignicons.com is no longer operational, I'm going to close this.
