### ISSUE TITLE
MDI Plugins

### ISSUE THREAD

**Issue by Dominic-Marcelino** [Templarian/MaterialDesign#5281]
In order to have a consistent design, as a user, I'd love to have an MDI-integration into different types of tools.

The most significant examples would be plugins to Adobe XD / sketch and the google editors to easily use the icons in Wireframes and presentations.

**Comment by Templarian** [comment]
The new site under development has a copy feature that lets one just right click and paste. All the data is provided if one wanted to add the icons to an extension/addon. Similar to how we have a Chrome/Firefox extension or the popular VS Code extension.

https://dev.materialdesignicons.com/contribute/third-party

Right now such an extension is outside of the scope as we'll be focusing a lot of our effort on the new site and expanding features once it is online.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Font If you download this it actually has a click to copy feature that can be pasted into AdobeXD also. It actually pastes a SVG with a transparent 24x24 rectangle group. Same feature the new site will have. It's also built real-time so it always has all the icons.

**Comment by Dominic-Marcelino** [comment]
Didn't knew those - solved my problems for know. Thanks!
