### ISSUE TITLE
Update "cash-refund" to fit with other "cash" icons

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#5282]
Hi there,

Looking for cash icons, I experienced that "cash-refund" is not similar to the other cash icons and less explicit. Indeed, the center dot in the note is not big enough. I provide here the corrected version If you think it is worth updating it.

## Path

```
M12.3 8.93L9.88 6.5h5.62V10H17V5H9.88l2.42-2.43-1.06-1.07L7 5.75 11.24 10l1.06-1.07zM12 14a3 3 0 103 3 2.991 2.991 0 00-3-3z M3 11v12h18V11zm16 8a2 2 0 00-2 2H7a2 2 0 00-2-2v-4a2 2 0 002-2h10a2 2 0 002 2z
```

## Preview

![image](https://user-images.githubusercontent.com/6012554/86013726-c039fe00-ba1f-11ea-9e0e-52ddd21b9793.png)

## Zip Download

[cash-refund.zip](https://github.com/Templarian/MaterialDesign/files/4845872/cash-refund.zip)

**Comment by Templarian** [comment]
Updated.
