### ISSUE TITLE
timer-sand reversed

### ISSUE THREAD

**Issue by rosenstand** [Templarian/MaterialDesign#5283]
## Usage

To indicate "time remaining" (current timer-sand, sand at bottom) and "time elapsed" (new timer-sand-reverse, sand at bottom) status.

## Examples

Exactly like the current timer-sand but rotated 180 degrees.

**Comment by jhil** [comment]
Took a stab at this one! Also added a half-and-half rotated state. Let me know if it's helpful.

![image](https://user-images.githubusercontent.com/2228347/86097226-331b9700-ba69-11ea-8175-108dc8f9958b.png)

![image](https://user-images.githubusercontent.com/2228347/86097191-28f99880-ba69-11ea-9eba-1bb67fdb6e92.png)

[timer-sand icons.zip](https://github.com/Templarian/MaterialDesign/files/4850116/timer-sand.icons.zip)

**Comment by Templarian** [comment]
Maybe `-complete` and `-paused`?

**Comment by goyney** [comment]
[![timer-sand-complete](https://materialdesignicons.com/icon/timer-sand-complete)](https://materialdesignicons.com/icon/timer-sand-complete)[![timer-sand-paused](https://materialdesignicons.com/icon/timer-sand-paused)](https://materialdesignicons.com/icon/timer-sand-paused)
