### ISSUE TITLE
video-input-vga

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5284]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/86092863-f8aefb80-ba62-11ea-95d9-9e233739614e.png)

## Zip Download

[video-input-vga.svg.zip](https://github.com/Templarian/MaterialDesign/files/4849896/video-input-vga.svg.zip)

**Comment by Templarian** [comment]
Not a terrible idea, but I'm thinking we should reject this solely based on it being obsolete/legacy. We have a few classic tech icons, but mostly for nostalgia.

It's it nice that we're down to 3 ports (and the new RTX 3080's will have them all 😅). DisplayPort / HDMI / USB-C kind of won out in the end.

**Comment by JamesCoyle** [comment]
I think we should add an icon for this. It's still quite commonly used and is still available on some motherboards as it always just works with no issues. Quite common in school or office environments still where they reuse older monitors but upgrade the tower.

**Comment by goyney** [comment]
It's not Material. The icon would need some work to fit into guidelines. Also, there might be other ways to depict this? Perhaps the receiving end (port) instead? That would be a little more abstract, but would also cover other types of connectors that follow the shape (such as pre-USB serial ports).

**Comment by JamesCoyle** [comment]
Yeah if we can get a more material representation of a D-type connector it would probably be handy for all types of that standard.

**Comment by Templarian** [comment]
Maybe exaggerating the screw pins by 2 width, but yeah I like the idea of having a more generic d-type connector with an alias for VGA.

**Comment by daavko** [comment]
What about the `serial-port` icon that already exists? That looks like a D-type connector. Couldn't that be aliased to VGA? Am I missing something?

![image](https://user-images.githubusercontent.com/7669061/88282585-2269e400-ccea-11ea-9170-a11c91a7f593.png)

**Comment by goyney** [comment]
Alias added to `serial-port`.
