### ISSUE TITLE
gradient-horizontal

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5285]
For use in design tools to assign the direction of a gradient fill.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/86094568-90ade480-ba65-11ea-8762-be3aa6dc4ea9.png)

## Zip Download

[gradient-horizontal.svg.zip](https://github.com/Templarian/MaterialDesign/files/4850004/gradient-horizontal.svg.zip)

**Comment by Templarian** [comment]
We might have to make a v6 breaking issue to rename `gradient` to `gradient-vertical` then. 🤔

**Comment by goyney** [comment]
Original renamed and new one added.
