### ISSUE TITLE
transit-skip

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5286]
To skip a stop in a transit app. Pairs with `transit-connection`.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/86094845-e84c5000-ba65-11ea-8eca-a98649c1db21.png)

## Zip Download

[transit-skip.svg.zip](https://github.com/Templarian/MaterialDesign/files/4850016/transit-skip.svg.zip)

**Comment by Templarian** [comment]
Do you think we need to have vertical/horizontal versions of these? Or could they always be vertical.

**Comment by goyney** [comment]
[![transit-skip](https://materialdesignicons.com/icon/transit-skip)](https://materialdesignicons.com/icon/transit-skip)
