### ISSUE TITLE
cursor-variant

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5287]
This is the `cursor-default` icon, but with no tail. It's the style used in a lot of design software, like Figma.

![0001](https://user-images.githubusercontent.com/2228347/86096685-7590a400-ba68-11ea-9c99-8b444fa7a01f.png)

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/86096565-4aa65000-ba68-11ea-8099-98e0d1c451a6.png)

## Zip Download

[cursor-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/4850090/cursor-variant.svg.zip)

**Comment by Templarian** [comment]
I get the idea, it just looks weird for some reason. 🤔

**Comment by goyney** [comment]
I don't see a reason to add this. Our icons aren't being used as cursors and our actual cursor icons are much more user-friendly for depicting that an action that would need to take place via the mouse cursor. I recommend we reject this.
