### ISSUE TITLE
Pollen icon

### ISSUE THREAD

**Issue by ChristofferG** [Templarian/MaterialDesign#5288]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use it as an icon with pollen numbers

## Examples
https://www.flaticon.com/premium-icon/pollen_2265508?term=pollen&page=1&position=22

**Comment by Templarian** [comment]
`flower-tulip` + dots. Should be an easy one for someone to create. 👍

**Comment by Xenomorph99** [comment]
Not sure if it makes sense to add all these to the library, but I posted them here as options. If we picked just one, I'd recommend `flower-pollen`. The tulip shape reminds me of an open book or a library icon for some reason.

![flower-pollen](https://user-images.githubusercontent.com/1837101/94970704-7818f480-04c2-11eb-8045-98679d53683c.png)
![flower-pollen-outline](https://user-images.githubusercontent.com/1837101/94970701-77805e00-04c2-11eb-9283-a86fc16aa385.png)
![flower-tulip-pollen](https://user-images.githubusercontent.com/1837101/94970709-794a2180-04c2-11eb-8110-9bd120d193f6.png)
![flower-tulip-pollen-outline](https://user-images.githubusercontent.com/1837101/94970706-794a2180-04c2-11eb-893a-dbedf6ea11f6.png)

[flower-pollen.zip](https://github.com/Templarian/MaterialDesign/files/5320261/flower-pollen.zip)

**Comment by Templarian** [comment]
Agreed, tulip also kind of looks like fire, which is confusing.

**Comment by goyney** [comment]
[![flower-pollen](https://materialdesignicons.com/icon/flower-pollen)](https://materialdesignicons.com/icon/flower-pollen)[![flower-pollen-outline](https://materialdesignicons.com/icon/flower-pollen-outline)](https://materialdesignicons.com/icon/flower-pollen-outline)
