### ISSUE TITLE
power-socket-it (Italian)

### ISSUE THREAD

**Issue by angelofan** [Templarian/MaterialDesign#5289]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

When used with existing socket icons, for example: `mdi-power-socket-au`, `mdi-power-socket-de`, `mdi-power-socket-eu`

## Examples

Include any example images so we know what the icon should look like.

It has 3 holes, the one in the middle is grounded, and the two sides are live and neutral.
It has many appearances, so I don’t know how to recommend the shape of the outer contour.
The three holes are arranged in a straight line, like this:
[power-socket-it.zip](https://github.com/Templarian/MaterialDesign/files/4856439/power-socket-it.zip)

Below are some pictures of the Italian-style sockets I searched on Google:
![image](https://user-images.githubusercontent.com/20255750/86216528-c27f9200-bbb0-11ea-8e65-a3aff036c2c2.png)
![image](https://user-images.githubusercontent.com/20255750/86216715-0ffbff00-bbb1-11ea-9816-59d3ab786299.png)

**Comment by angelofan** [comment]
Just as a suggestion, because I feel that the shape of this outer contour does not look very intuitive.

## Preview

![image](https://user-images.githubusercontent.com/20255750/86218754-d7115980-bbb3-11ea-9f6e-89f783753b4a.png)

## Zip Download

[power-socket-it.zip](https://github.com/Templarian/MaterialDesign/files/4856486/power-socket-it.zip)

**Comment by angelofan** [comment]
![image](https://user-images.githubusercontent.com/20255750/86304306-146ff880-bc41-11ea-89a2-54943dbc2bf4.png)

https://www.iec.ch/worldplugs/typeL.htm

**Comment by Templarian** [comment]
Added, just to verify is vertical more common or should we have had these horizontal @angelofan?

**Comment by angelofan** [comment]
@Templarian It does not have a fixed direction on the household outlet

I feel that vertical placement is easier to recognize.

**Comment by angelofan** [comment]
As an alternative:

![image](https://user-images.githubusercontent.com/20255750/86326437-4a7aa000-bc74-11ea-8c66-caacf828c21e.png)

[power-socket-it.zip](https://github.com/Templarian/MaterialDesign/files/4862511/power-socket-it.zip)
