### ISSUE TITLE
Sanitary icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#529]
Noticed these in a train toilet recently:

![toilet_isnt_a_litter_bin](https://cloud.githubusercontent.com/assets/1309249/8888689/694ab8d0-32b8-11e5-9347-d9f944dbd27a.png) Don't throw trash into the toilet
![hand_dryer](https://cloud.githubusercontent.com/assets/1309249/8888691/69509278-32b8-11e5-988d-16b481ab827f.png) Hand dryer (drier?)
![no_smoking](https://cloud.githubusercontent.com/assets/1309249/8888693/695421ea-32b8-11e5-8010-7268e18b7584.png) No smoking (and an "on"-version possibly too for smoking areas)
![soap_dispenser](https://cloud.githubusercontent.com/assets/1309249/8888692/69514eac-32b8-11e5-9448-6ff62ca1a1e0.png) Soap dispenser
![flush_water_dryer](https://cloud.githubusercontent.com/assets/1309249/8888690/69508062-32b8-11e5-9fb6-a07e0c70b7a2.png) Flush toilet, activate water, activate hand dryer

**Comment by CoDEmanX** [comment]
The cigarette ones:
![smoking](https://cloud.githubusercontent.com/assets/1309249/9047776/63c0630a-3a34-11e5-9149-220a3215e1e1.png) ![smoking-off](https://cloud.githubusercontent.com/assets/1309249/9047777/63e8f838-3a34-11e5-9bf9-d9d8d4afa669.png)
https://www.dropbox.com/s/ptu3ftqd9e3smgz/smoking.svg?dl=0
https://www.dropbox.com/s/g46d5egkge43oq6/smoking-off.svg?dl=0

**Comment by CoDEmanX** [comment]
Slightly extended the fume for better legibility (especially the off version):
![smoking](https://cloud.githubusercontent.com/assets/1309249/9075658/bd300542-3b17-11e5-856e-8eec9fabd45f.png)
![smoking-off](https://cloud.githubusercontent.com/assets/1309249/9075657/bd2e2146-3b17-11e5-8204-e9d5f58fe9f8.png)
Links still valid.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/smoking
https://materialdesignicons.com/icon/smoking-off

**Comment by CoDEmanX** [comment]
Shower / sink:
![shower](https://cloud.githubusercontent.com/assets/1309249/9088525/b903944c-3b90-11e5-8df4-47d791cc5bf9.png) https://www.dropbox.com/s/hnvm1bn1veufh8y/shower.svg?dl=0

**Comment by metbril** [comment]
see #1560.

**Comment by metbril** [comment]
Any progresss on these?

**Comment by goyney** [comment]
From the original request:

- [ ] No trash in toilet
- [ ] Hand dryer
- [x] No smoking - `smoking-off`
- [ ] Soap dispenser
- [ ] Flush toilet - `toilet`, but no modifier indicating flush
- [ ] Activate water/sink - `shower-head` is similar to the example

**Comment by JamesCoyle** [comment]
I'm gonna close this out as there isn't much here that is workable. If anyone wants any of the icons requested, please open a new issue for each so they can be tracked easily.
