### ISSUE TITLE
share-variant-outline

### ISSUE THREAD

**Issue by locness3** [Templarian/MaterialDesign#5290]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Would be used in the case where outlined icons are already used, for visual consistency.
An outline version of the share-variant icon, like the one in Google's icon set :
![Screen Shot 2020-07-01 at 15 49 21](https://user-images.githubusercontent.com/37651007/86251720-877e5e00-bbb2-11ea-9edc-47f3aae2088e.png)

**Comment by goyney** [comment]
[![share-variant-outline](https://materialdesignicons.com/icon/share-variant-outline)](https://materialdesignicons.com/icon/share-variant-outline)
