### ISSUE TITLE
Money Transactions

### ISSUE THREAD

**Issue by Saff-Elli-Khan** [Templarian/MaterialDesign#5291]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
> ## Usage
> Provide some context of how your icon could be used.
> 
> ## Examples
> Include any example images so we know what the icon should look like.

**Comment by Saff-Elli-Khan** [comment]
Hi Goyney, thanks for your fast reply.

I want this icon to look something similar to this one below but more professional...
[https://image.flaticon.com/icons/svg/3029/3029373.svg](url)

This icon will represent the money transactions on any application.
Also, I would request any icon for a "list of money transactions". I would leave this to you.

Thank you very much.

**Comment by Templarian** [comment]
The example isn't something we can really show in the small size. So it would have to be simplified. Like cash overlayed with an arrow or credit-card overlayed with an arrow.

Which reminds me we might want a credit card with a longer arrow for `credit-card-swipe` (little legacy now-a-days, but might be useful).

**Comment by Templarian** [comment]
`credit-card-check` that we have right be a good one for transactions.

**Comment by Saff-Elli-Khan** [comment]
I know you have one with credit-card-check but in my case, I cannot use that, because my app represents a digital wallet transaction instead of a credit card transaction. You can make it smaller by removing some details from it, I trust your talent and I am sure you can manage to do it. If not then don't worry, let me know if I can do this for you? I am a designer, I can create an svg for you that you can add to your collection...

**Comment by Saff-Elli-Khan** [comment]
Just provide me an appropriate size and margin calculations...

**Comment by Templarian** [comment]
@Saff-Elli-Khan https://material.io/design/iconography/system-icons.html Are the guidelines, they go into a lot of detail and should be a good starting point.

**Comment by goyney** [comment]
Considering we have plenty of monetary icons that could be used to represent a monetary transaction in the proper context, I'm going to close this issue for now. If you come up with a new idea following Material guidelines, feel free to open a new issue or comment back here.
