### ISSUE TITLE
AJAX JavaScript Icon

### ISSUE THREAD

**Issue by CyanNinja** [Templarian/MaterialDesign#5292]
I have:
* [Y] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
* [Y] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
* [Y] Only requested a single icon (or a few near-identical ones) in this issue.

## Usage

It shows the dev knows AJAX and could be used in portfolio pages.

## Examples

Probably just the letters 'AJAX' put in a square and styled into different types of boxes or circles, outlined, not, etc., as shown below:

A J

A X

**Comment by Templarian** [comment]
I'm going to reject this as it's more meta legacy tech and can only be represented with text.

Off-topic, but the fetch API is by far the more common API now-a-days. Not sure anyone would be putting "ajax" on a portfolio / resume in 2020. 😨

**Comment by Templarian** [comment]
Looks like I decided not to add it back in 2015 also... #271 👴

**Comment by CyanNinja** [comment]
Oh okay then, very quick response, good job!

I was going to add AJAX but now might remove it. I also did not know about the fetch API (gonna research), I thought AJAX was the way to fetch things. Thanks!
