### ISSUE TITLE
Remove Google Photos

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#5293]
Google has recently rebranded Photos with a new, outline monohhrome icon: https://partnermarketinghub.withgoogle.com/#/brands/1TP3sHcc3rsLp2L0EW_pfsCjSM79DZ_ng/1nrCb8vd2u-VIKRe37NOOy6V6o749qU9jBQHBiRxqVvs

**Comment by JapanYoshi** [comment]
Looks like Google *only* wants the icon to be outlined.

**Comment by JapanYoshi** [comment]
![image](https://user-images.githubusercontent.com/8707990/86349982-4f0b7c80-bca5-11ea-8a13-e280e18ba51a.png)

Recreated within MD guidelines. Applied some visual correction on the inside curve where it meets another petal

    M 13 2 C 11.98752 2.0000255 11 2.8954762 11 4 L 11 7.0722656 C 10.285589 6.0748252 9.1436097 5.5 7.5 5.5 C 4.4841491 5.5 1.9999242 7.9841491 2 11 C 2.0000255 12.01248 2.8954762 13 4 13 L 7.0722656 13 C 6.0748252 13.714411 5.5 14.85639 5.5 16.5 C 5.5 19.515851 7.9841491 22.000076 11 22 C 12.01248 21.999975 13 21.104524 13 20 L 13 16.927734 C 13.714411 17.925175 14.85639 18.5 16.5 18.5 C 19.515851 18.5 22.000076 16.015851 22 13 C 21.999974 11.98752 21.104524 11 20 11 L 16.927734 11 C 17.925175 10.285589 18.5 9.1436097 18.5 7.5 C 18.5 4.4841491 16.015851 1.9999242 13 2 z M 13 4 C 14.932997 4 16.5 5.5670034 16.5 7.5 C 16.5 9.4329966 14.932997 11 13 11 L 13 4 z M 7.5 7.5 C 9.4329966 7.5 11 9.067003 11 11 L 4 11 C 4 9.067003 5.5670034 7.5 7.5 7.5 z M 11 13 L 11 20 C 9.067003 20 7.5 18.432997 7.5 16.5 C 7.5 14.567003 9.067003 13 11 13 z M 13 13 L 20 13 C 20 14.932997 18.432997 16.5 16.5 16.5 C 14.567003 16.5 13 14.932997 13 13 z

**Comment by goyney** [comment]
We don't recreate brand icons.

**Comment by Templarian** [comment]
Did anyone find the vector for this updated icon?

**Comment by PeterShaggyNoble** [comment]
Not as yet, unfortunately.

Is it just an optical illusion or is the outline of the white version thicker than that of the gray?

**Comment by Xenomorph99** [comment]
Coincidentally, I saw these in our library today [pinwheel](https://materialdesignicons.com/icon/pinwheel) and [pinwheel outline](https://materialdesignicons.com/icon/pinwheel-outline). They look like the exact same icon just backwards. Here's the flipped versions.

![google-photos](https://user-images.githubusercontent.com/1837101/87610877-d0123d00-c6c3-11ea-8a8d-cd77943ebc1d.png)
![google-photos-outline](https://user-images.githubusercontent.com/1837101/87610878-d0aad380-c6c3-11ea-8597-7fbc4c5060d1.png)

[google-photos.zip](https://github.com/Templarian/MaterialDesign/files/4928561/google-photos.zip)

**Comment by Templarian** [comment]
@Xenomorph99 We don't recreate Logos or add outlines of them. The Google Photos icon has very detailed corners. Easier to wait and find a vector out in the wild.

**Comment by Xenomorph99** [comment]
Talk about a subtle nuance. Sorry I missed that. I was excited that I found the pinwheel icons just this morning haha. Looks like the designers took the half circle shapes from the filled version, shrunk them down, adjusted the corner radius, and overlapped them a bit in the center. Definitely best to wait till you can download the SVG directly from them to get it exact.

That being said, isn't the principle behind the material design guidelines driving us to flatten, simplify, and distill a meaning down to its absolute simplest form optimizing for the 24x24 pixel grid? It feels like the reversed pinwheel icons could be an iconic representation of the google photos logo. An icon to represent a logo = abstraction of an abstraction 🤯. I guess this is just one reason why we don't keep adding brand icons into the MDI library.

![image](https://user-images.githubusercontent.com/1837101/87618354-e1b11000-c6d6-11ea-9d6d-6b20409e302a.png)
![image](https://user-images.githubusercontent.com/1837101/87618381-f392b300-c6d6-11ea-91f6-9c8cb334feec.png)

**Comment by Templarian** [comment]
Yes. Just not for logos. We actually went back through and removed any modifications from logos to keep their branding. 👍

**Comment by goyney** [comment]
We're going to remove this icon in 6.0. It's a brand icon that is not developer related (on top of the fact that we cannot find an official version of the new logo 😝 ).

**Comment by goyney** [comment]
This has been removed.
