### ISSUE TITLE
Flag of Washington, D.C.

### ISSUE THREAD

**Issue by MilesAWilson** [Templarian/MaterialDesign#5294]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Washington DC has both a simplistic and widely used flag. It is used frequently throughout the city and could be used in mobile apps and site footers to acknowledge being made in DC.

With recent legislation passing the US house to make Washington, DC a US state it would be a timely addition.

## Examples
https://en.wikipedia.org/wiki/File:Flag_of_the_District_of_Columbia.svg

![DC Flag](https://upload.wikimedia.org/wikipedia/commons/d/d4/Flag_of_the_District_of_Columbia.svg)

**Comment by goyney** [comment]
This is a slippery slope. We won't be adding flags because there are a million of them and most can't be recreated in Material style and in monotone accurately.
