### ISSUE TITLE
FAX

### ISSUE THREAD

**Issue by swschilke** [Templarian/MaterialDesign#530]
A nice fax icon would be great (yes some people still use it)

**Comment by CoDEmanX** [comment]
Derived from printer icon:
![fax](https://cloud.githubusercontent.com/assets/1309249/8893988/8e01168a-33a6-11e5-8ab8-b443efb46e28.png) https://www.dropbox.com/s/wgwafob8vroqedp/fax.svg?dl=0

Something more experimental:
![fax2](https://cloud.githubusercontent.com/assets/1309249/8893989/8e01fb0e-33a6-11e5-9b14-ce8b3cdbd9a8.png) https://www.dropbox.com/s/3jmm5t3n9n2eg09/fax2.svg?dl=0

**Comment by Templarian** [comment]
I kind of like the 2nd one more. What do you think @swschilke?

I feel like the first could get mistake for a printer too easily.

**Comment by CoDEmanX** [comment]
I been thinking about adding a label, but pixel style and Roboto didn't work well. Maybe if @Tamplarian could add "FAX" to the first in the same style as iOS, GIF and HTTP icons?

**Comment by Templarian** [comment]
![fax](https://cloud.githubusercontent.com/assets/338885/8896437/4291384e-33c2-11e5-9d23-7ae7c51df4c1.png) ?

**Comment by CoDEmanX** [comment]
Not quite, the inside part of the A triangle  (can't remember the typographic name) is barely visible at 24px. I'll give it another shot when I return home Wednesday/Thursday.

**Comment by CoDEmanX** [comment]
I had this on mind:

![fax3](https://cloud.githubusercontent.com/assets/1309249/8956279/781a8a68-35f4-11e5-9224-9a6653310045.png) https://www.dropbox.com/s/k3wwlq6i46djc4n/fax3.svg?dl=0

Close-up:
![fax3_xl](https://cloud.githubusercontent.com/assets/1309249/8956293/a88a14b6-35f4-11e5-8efd-fca40389af17.png)

The A is narrower because I wanted to center the text. Moved the Fax device one pixel down, so there's 2px margin all around. I assume it still works horizontally next to the printer icon.

**Comment by Templarian** [comment]
Looks nice, except for the style of the X. I like the idea, but scaled up it looks out of place.

**Comment by CoDEmanX** [comment]
In the SVG you find two more tries on the X, but maybe it's best to just use two diagonal lines...

**Comment by swschilke** [comment]
Dear all,

thnk you very  much - the last one seems the best in my eyes!

Great work

**Comment by CoDEmanX** [comment]
Two diagonal lines, 30° angle, cut off at baseline and height of other chars:

![fax4_](https://cloud.githubusercontent.com/assets/1309249/9035524/e5bded34-39d8-11e5-8cdb-6d199550ba13.png)

![fax4](https://cloud.githubusercontent.com/assets/1309249/9035513/c649d404-39d8-11e5-9188-b0b12a82e02c.png) https://www.dropbox.com/s/5lsygx28qmto5jx/fax4.svg?dl=0

**Comment by CoDEmanX** [comment]
Maybe we could also add a paper shredder?
![shredder](https://cloud.githubusercontent.com/assets/1309249/9088439/615cd2c6-3b90-11e5-9bdf-9f4fa8b0021b.png)

**Comment by Templarian** [comment]
[![fax](https://materialdesignicons.com/icon/fax)](https://materialdesignicons.com/icon/fax) [![shredder](https://materialdesignicons.com/icon/shredder)](https://materialdesignicons.com/icon/shredder)
