### ISSUE TITLE
Dock-Top is missing

### ISSUE THREAD

**Issue by Symbai** [Templarian/MaterialDesign#5300]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

#4126 added icons for bottom, left and right. For completeness (and because I'm needing it) dock-top is missing.

## Examples

#4126

_ping @MrGrigri because he created the original ones._

**Comment by goyney** [comment]
[![dock-top](https://materialdesignicons.com/icon/dock-top)](https://materialdesignicons.com/icon/dock-top)
