### ISSUE TITLE
chandelier

### ISSUE THREAD

**Issue by Erickclee** [Templarian/MaterialDesign#5301]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To represent Chandelier in Home Assistant Picture Element Card.

## Examples

Include any example images so we know what the icon should look like.

![chandelier](https://user-images.githubusercontent.com/67800010/86879419-98345400-c11d-11ea-9085-2ac7a8b37988.jpg)

**Comment by lkroeker** [comment]
This would be great to have!

**Comment by goyney** [comment]
[![chandelier](https://materialdesignicons.com/icon/chandelier)](https://materialdesignicons.com/icon/chandelier)
