### ISSUE TITLE
Access Point Off

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5304]
## Preview

![access-point-off](https://user-images.githubusercontent.com/1837101/87103561-9e582c80-c212-11ea-8c47-024167b00217.png)

## Zip Download

[access-point-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/4900129/access-point-off.svg.zip)

**Comment by goyney** [comment]
[![access-point-off](https://materialdesignicons.com/icon/access-point-off)](https://materialdesignicons.com/icon/access-point-off)
