### ISSUE TITLE
Device Hub

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5305]
![device-hub](https://user-images.githubusercontent.com/1837101/87099708-b24a6100-c207-11ea-8ef0-90e95285f3ce.png)

It would be helpful for a project I'm working on if we had this Google icon added to the MDI library. Here's a link to the icon https://material.io/resources/icons/?search=hub&icon=device_hub&style=baseline

**Comment by goyney** [comment]
We actually have a rotated version of this already.
[![merge](https://materialdesignicons.com/icon/merge)](https://materialdesignicons.com/icon/merge)

Can you just use that one @Xenomorph99?
