### ISSUE TITLE
probe

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5306]
## Preview

![thermometer-bluetooth (1)](https://user-images.githubusercontent.com/1837101/87102592-9945ae00-c20f-11ea-885d-dc3224223e0c.png)

![thermometer-bluetooth-off](https://user-images.githubusercontent.com/1837101/87102573-8b902880-c20f-11ea-841e-5d2fc30e227c.png)

I'm working on a project that connects a mobile app to a bluetooth thermometer. It would be awesome to add these two icons into the MDI library. I'm not sure what the best name is, but here are three options:

1. Bluetooth Thermometer
2. Bluetooth Probe
3. Bluetooth Pyrometer

We already have a set of thermometer icons so it might make sense to group them together. Probe is a little abstract and pyrometers generally look a little different.

Here's an example of what one of the bluetooth thermometers looks like https://www.webstaurantstore.com/cooper-atkins-92010-k-blue2-wand-bluetooth-thermocouple-instrument-with-51337-k-duraneedle-direct-connect-kit/27392010K.html

## Zip Download

[thermometer-bluetooth.zip](https://github.com/Templarian/MaterialDesign/files/4900087/thermometer-bluetooth.zip)

**Comment by Xenomorph99** [comment]
I realized a pyrometer should be a separate icon. I created a related issue.

**Comment by goyney** [comment]
I think this would be better served using `thermometer` with the bluetooth logo next to it.

**Comment by Xenomorph99** [comment]
@goyney it's not a bad idea to add that icon to our library regardless. However, in my specific use case, a user can record the temperature of an item such as a frozen chicken breast either using a hand-held bluetooth probe like this, a stationary bluetooth sensor with probe attachment, or through manual entry with a keypad. I need a way to visually distinguish the collection method. The thermometer with a bluetooth modifier wouldn't distinguish in this case.

**Comment by Xenomorph99** [comment]
While I could live with calling it a meat thermometer, I worry that’s too narrow of a classification. Their real differentiation is the fact that they communicate temperatures to mobile devices via Bluetooth. In a restaurant, they’re used to measure the temperature of all kinds of things to monitor food safety like ice cream, produce, sauces, and both frozen and cooked meat.

I could try adding the Bluetooth symbol to the icon if you feel it necessary.

One of the most popular Bluetooth thermometers for restaurants is the [Cooper Atkins Blue 2](https://www.cooper-atkins.com/products/blue2-2/). You can see it in action in this video https://youtu.be/k_0SCqpInZg

**Comment by GreenTurtwig** [comment]
`thermometer-probe` perhaps would be a better fit?

**Comment by Xenomorph99** [comment]
`thermometer-probe` would work great.

<img src="https://user-images.githubusercontent.com/1837101/93395717-a0062800-f833-11ea-8314-cba7b855945c.png" width="400" height="400">

https://www.thermoworks.com/BlueTherm-Probe

**Comment by goyney** [comment]
Adding the more generic version:
[![thermometer-bluetooth](https://materialdesignicons.com/icon/thermometer-bluetooth)](https://materialdesignicons.com/icon/thermometer-bluetooth)

Renaming this issue to include a generic probe.

**Comment by goyney** [comment]
[![thermometer-probe](https://materialdesignicons.com/icon/thermometer-probe)](https://materialdesignicons.com/icon/thermometer-probe)[![thermometer-probe-off](https://materialdesignicons.com/icon/thermometer-probe-off)](https://materialdesignicons.com/icon/thermometer-probe-off)
