### ISSUE TITLE
email

### ISSUE THREAD

**Issue by VicoMorales** [Templarian/MaterialDesign#5307]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@VicoMorales The issue template isn't optional. 😄  Closing as a duplicate for now. Fill in the issue template with more details.

- `email` exists already.
