### ISSUE TITLE
Grass

### ISSUE THREAD

**Issue by metbril** [Templarian/MaterialDesign#5309]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'd need it for a grass pollen alert in Home Assistant next to tree and flower.

## Examples

Include any example images so we know what the icon should look like.

https://duckduckgo.com/?q=grass+icon

![](https://maxcdn.icons8.com/Share/icon/Plants/grass1600.png)

![](http://getdrawings.com/free-icon-bw/grass-icon-1.png)

**Comment by Xenomorph99** [comment]
Google has a grass icon we could probably add to our library. https://material.io/resources/icons/?search=grass&icon=grass&style=baseline

![grass](https://user-images.githubusercontent.com/1837101/87178283-203f6880-c29a-11ea-9e7d-6ac020dec524.png)

**Comment by goyney** [comment]
[![grass](https://materialdesignicons.com/icon/grass)](https://materialdesignicons.com/icon/grass)
