### ISSUE TITLE
Encrypted (secure) eMail 

### ISSUE THREAD

**Issue by swschilke** [Templarian/MaterialDesign#531]
A icon which symbolizes encrypted (secure) eMail

**Comment by CoDEmanX** [comment]
Google's `ic_vpn_lock` uses 1px border margin, thus I tried the same for mail:
![mail-secure](https://cloud.githubusercontent.com/assets/1309249/8894008/952dc7ea-33a7-11e5-8bb0-dfbf0261ff06.png)
vs. original with 2px left and right, 4px bottom margin:
![mail](https://cloud.githubusercontent.com/assets/1309249/8894009/952e60ce-33a7-11e5-83b1-d12bd6875174.png)

And horizontal (not very pretty):
![mail-secure](https://cloud.githubusercontent.com/assets/1309249/8894008/952dc7ea-33a7-11e5-8bb0-dfbf0261ff06.png) ![mail](https://cloud.githubusercontent.com/assets/1309249/8894009/952e60ce-33a7-11e5-83b1-d12bd6875174.png)

With letter at original position (letter is quite obstructed):
![mail-secure2](https://cloud.githubusercontent.com/assets/1309249/8894024/25aec080-33a8-11e5-83d7-fc002b95611c.png) ![mail](https://cloud.githubusercontent.com/assets/1309249/8894009/952e60ce-33a7-11e5-83b1-d12bd6875174.png)

Lock with no margin to border:
![mail-secure3](https://cloud.githubusercontent.com/assets/1309249/8894033/66d591ba-33a8-11e5-9ce0-fb03de007252.png) ![mail](https://cloud.githubusercontent.com/assets/1309249/8894009/952e60ce-33a7-11e5-83b1-d12bd6875174.png)

https://www.dropbox.com/s/6z2t89dedry36es/mail-secure.svg?dl=0 (design version)

Opinions, please!

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/email-secure
