### ISSUE TITLE
Currency MNT (Mongolian Tugrug)

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5311]
Reference link: https://en.wikipedia.org/wiki/Mongolian_t%C3%B6gr%C3%B6g

## Preview

![currency-mnt](https://user-images.githubusercontent.com/1837101/87180374-ad37f100-c29d-11ea-9932-fb8ceb84df0e.png)

## Zip Download

[currency-mnt.svg.zip](https://github.com/Templarian/MaterialDesign/files/4904476/currency-mnt.svg.zip)

**Comment by goyney** [comment]
[![currency-mnt](https://materialdesignicons.com/icon/currency-mnt)](https://materialdesignicons.com/icon/currency-mnt)
