### ISSUE TITLE
Yurt

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5312]
Here's a few options I considered. I think the one with smoke reads the best as a yurt. I thought about a _yurt_ and _yurt-smoke_ variant, but having the icon shift in the frame seems weird.

<img width="812" alt="variations" src="https://user-images.githubusercontent.com/1837101/87191679-23465300-c2b2-11ea-9238-b739eaea0749.png">

## Preview

![yurt](https://user-images.githubusercontent.com/1837101/87191543-dbbfc700-c2b1-11ea-91a2-9d21342ab3cb.png)

## Zip Download

[yurt.svg.zip](https://github.com/Templarian/MaterialDesign/files/4905034/yurt.svg.zip)

**Comment by goyney** [comment]
We have a distinct "smoke" or "steam" pattern we use on other icons. Wanted to try it out here for consistency. Thoughts?

![image](https://user-images.githubusercontent.com/1015040/87378923-ff5a6a00-c55c-11ea-9e86-3789e4ee7126.png)
[yurt.svg.zip](https://github.com/Templarian/MaterialDesign/files/4916295/yurt.svg.zip)

**Comment by Xenomorph99** [comment]
I really like that standard smoke/steam pattern. However, the thickness makes the stove pipe look like it's a brick chimney. Yurts only have tiny smoke pipes attached to the stove they keep in the center. Perhaps we simply choose the option without smoke to keep it simple?

![image](https://user-images.githubusercontent.com/1837101/87379530-bfd85180-c54d-11ea-9102-5e70f79c8c2f.jpg)
![inside-the-ger-that-stove](https://user-images.githubusercontent.com/1837101/87379993-c1eee000-c54e-11ea-8fe2-669346da2eec.jpg)

**Comment by Xenomorph99** [comment]
Here's another option combining the two ideas. Not sure I like this any better.

![yurt-smoke](https://user-images.githubusercontent.com/1837101/87380250-56594280-c54f-11ea-9fee-81f382a9befe.png)
[yurt-smoke.svg.zip](https://github.com/Templarian/MaterialDesign/files/4916372/yurt-smoke.svg.zip)

**Comment by goyney** [comment]
That's much better. Simplistic like yours and more geometrical to fit Material guidelines.

**Comment by goyney** [comment]
[![yurt](https://materialdesignicons.com/icon/yurt)](https://materialdesignicons.com/icon/yurt)

**Comment by Xenomorph99** [comment]
One last option haha. I inverted the smoke.

![yurt-smoke](https://user-images.githubusercontent.com/1837101/87380626-1cd50700-c550-11ea-8f65-7aeaa3fe7bca.png)
[yurt-smoke.svg.zip](https://github.com/Templarian/MaterialDesign/files/4916391/yurt-smoke.svg.zip)

**Comment by Templarian** [comment]
Yeah, I think we might want to update it to this smoke maybe, so it looks less uniform.

**Comment by goyney** [comment]
Updated!
