### ISSUE TITLE
Snake

### ISSUE THREAD

**Issue by yoyosan** [Templarian/MaterialDesign#5316]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
I've searched for `cobra, snake, serpent`.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

> Provide some context of how your icon could be used.

For yoga postures(e.g. cobra) or symbolizing the Snake game from old Nokia phones.

## Examples

> Include any example images so we know what the icon should look like.

Some like the four icons from https://fontawesome.com/icons?d=gallery&q=snake

Thank you.

**Comment by Xenomorph99** [comment]
Here's a few ideas. I think Snake-A is the best option so far. The tail on Snake-B doesn't read the best. Snake-C feels a bit busy. We might be able to include Snake-D as a variant. I included them all here as a comparison.

These are generic snakes. They don't really match a cobra nor a yoga pose. It might make sense to create a separate set of icons representing yoga poses that match the style of [human-handsdown](https://materialdesignicons.com/icon/human-handsdown) and [human-handsup](https://materialdesignicons.com/icon/human-handsup).

As for the Nokia phone game _Snake_, [square-wave](https://materialdesignicons.com/icon/square-wave) may work for you.

![snake-a](https://user-images.githubusercontent.com/1837101/87367902-78e06100-c539-11ea-9f05-705ade5b1638.png)
![snake-b](https://user-images.githubusercontent.com/1837101/87367903-7978f780-c539-11ea-8478-497ef7ab5344.png)
![snake-c](https://user-images.githubusercontent.com/1837101/87367904-7a118e00-c539-11ea-896a-c681fb1eb0f5.png)
![snake-d](https://user-images.githubusercontent.com/1837101/87367905-7a118e00-c539-11ea-96b4-4b9b94f3e7e9.png)
[snake-options.zip](https://github.com/Templarian/MaterialDesign/files/4915885/snake-options.zip)

**Comment by Templarian** [comment]
My vote is `snake-b`. It looks like a basket without the small tail and `c` has too much detail.

**Comment by goyney** [comment]
[![snake](https://materialdesignicons.com/icon/snake)](https://materialdesignicons.com/icon/snake)

**Comment by yoyosan** [comment]
Thank you ❤️
