### ISSUE TITLE
Speaker with Spotify icon

### ISSUE THREAD

**Issue by nagyrobi** [Templarian/MaterialDesign#5317]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home Assistant home automation system uses MDI icons in its main user interface. With it, smart speakers can also be managed.
There are a variety of speaker icons already in MDI which are useful to show the state of the speaker:
- playing: `mdi-speaker-wireless`
- muted: `mdi-speaker-off`
- idle: `mdi-speaker`
- multiroom: `mdi-speaker-multiple`
- bluetooth: `mdi-speaker-bluetooth`
- push: `mdi-cast-audio`

What's missing, show playback of Spotify streams. I notice that there is already a Spotify icon, all that hast to be done is to combine the already existing speaker icon with the Spotofy icon.
So what we need is a `mdi-speaker` + `mdi-spotify` in one. Just like  `mdi-speaker-bluetooth` is.

**Comment by Templarian** [comment]
Home Assistant still uses an old version of MDI (`v4.9.95`). We removed a lot of brand icons in 5.0 and will not be including any variants or additions going forward. The 'Simple Icons' is available in Home Assistant and should be used.

https://dev.materialdesignicons.com/guide/home-assistant
