### ISSUE TITLE
Speaker with DLNA

### ISSUE THREAD

**Issue by nagyrobi** [Templarian/MaterialDesign#5318]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home Assistant home automation system uses MDI icons in its main user interface. With it, smart speakers can also be managed.
There are a variety of speaker icons already in MDI which are useful to show the state of the speaker:
- playing: `mdi-speaker-wireless`
- muted: `mdi-speaker-off`
- idle: `mdi-speaker`
- multiroom: `mdi-speaker-multiple`
- bluetooth: `mdi-speaker-bluetooth`
- push: `mdi-cast-audio`

What's missing, show playback of DLNA streams. I notice that there is already a DLNA icon, all that hast to be done is to combine the already existing speaker icon with the DLNA icon.
So what we need is a `mdi-speaker` + `mdi-dlna` in one. Just like  `mdi-speaker-bluetooth` is.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
