### ISSUE TITLE
Format text border or Format text color outline

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [Templarian/MaterialDesign#5319]
![image](https://user-images.githubusercontent.com/6233059/87253160-3c383b00-c44f-11ea-81be-d128166eaec0.png)

[format-color-text-border.zip](https://github.com/Templarian/MaterialDesign/files/4909034/format-color-text-border.zip)

**Comment by Templarian** [comment]
This definitely is something we should have, but wonder if A is too complex. Maybe a T, but that might be too bold.

We do use `A` for most of these format options. Is it `text-border` or `text-stroke`. Design software might call this different than text editors. 🤔

**Comment by goyney** [comment]
This isn't Material and is blurry at native. If this is something we should have, it needs some other options.

**Comment by EdnaldoNeimeg** [comment]
![image](https://user-images.githubusercontent.com/6233059/87257459-86321880-c471-11ea-9f7b-c218ad1e9e96.png)
[text-border.zip](https://github.com/Templarian/MaterialDesign/files/4909660/text-border.zip)

**Comment by JapanYoshi** [comment]
Literally just centered and added an outline effect to ``format-color-text``.
![image](https://user-images.githubusercontent.com/8707990/87257729-bcf34780-c4e0-11ea-99bb-330613abaa09.png)

    M 11,3 C 10.17756,3 9.4393992,3.5040436 9.1386719,4.2695312 l -5.5,13.9999998 C 3.1234848,19.580916 4.0910467,21 5.5,21 h 2.25 c 0.8345818,0 1.5809909,-0.518969 1.8730469,-1.300781 L 10.257812,18 h 3.478516 l 0.642578,1.705078 C 14.672445,20.483984 15.417618,21 16.25,21 h 2.25 c 1.408953,0 2.376515,-1.419084 1.861328,-2.730469 l -5.5,-13.9999998 C 14.560601,3.5040435 13.82244,3 13,3 Z m 0,2 h 2 l 5.5,14 H 16.25 L 15.119141,16 H 8.8691406 L 7.75,19 H 5.5 Z M 12,7.6699219 9.6191406,14 h 4.7500004 z

To align it to ``format-text-bold``, you need to move the icon up one dp though. 
![image](https://user-images.githubusercontent.com/8707990/87257775-2b380a00-c4e1-11ea-8931-2ea28553ed91.png)

**Comment by goyney** [comment]
[![format-text-variant-outline](https://materialdesignicons.com/icon/format-text-variant-outline)](https://materialdesignicons.com/icon/format-text-variant-outline)
