### ISSUE TITLE
500px icon

### ISSUE THREAD

**Issue by megyland** [Templarian/MaterialDesign#532]
![500px Official logo](http://seeklogo.com/images/1/500px-logo-3C3F756790-seeklogo.com.gif)

**Comment by Templarian** [comment]
Their official logo is like so many extra points if anyone gets bored and wants to make a more point friendly version that would be awesome. If not I'll create one tomorrow.

**Comment by GreenTurtwig** [comment]
500px now has a new logo which I don't think will be possible to add. https://cdn0.iconfinder.com/data/icons/logos-3/46/500px-color-128.png

**Comment by Templarian** [comment]
Agreed, looks like we can close this as it won't be added.

https://meetthenew.500px.com/

**Comment by CoDEmanX** [comment]
That's a horrible logo...

**Comment by Templarian** [comment]
Meh, kind of grows the longer I look at it. Also a pretty nice watermark due to the details. I do prefer more minimal marks usually.

**Comment by kareldonk** [comment]
So the new 500px logo can't or won't be added?

**Comment by Templarian** [comment]
@kareldonk It will not be included. Sorry for the confusion. Too much detail being the primary reason.
