### ISSUE TITLE
Text border

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [Templarian/MaterialDesign#5320]
![image](https://user-images.githubusercontent.com/6233059/87256632-c80b9080-c46a-11ea-9cf4-8fa001d22dd8.png)
[text-border.zip](https://github.com/Templarian/MaterialDesign/files/4909528/text-border.zip)

**Comment by Templarian** [comment]
Lets keep it in the #5319 thread, so we can go over the proposed ideas in one place.

**Comment by EdnaldoNeimeg** [comment]
Sorry. I created a new issue cause the other one is tagged as "Contribution" anymore and (maybe) does not count as a contribution. I do want to become a contributor :)
