### ISSUE TITLE
Water Check

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5321]
## Preview

![water-check](https://user-images.githubusercontent.com/1837101/87342032-c7750780-c507-11ea-93fb-f351edaf7b22.png)
![water-check-outline](https://user-images.githubusercontent.com/1837101/87342037-c93ecb00-c507-11ea-9054-838975d7f249.png)

## Zip Download

[water-check.zip](https://github.com/Templarian/MaterialDesign/files/4914518/water-check.zip)

**Comment by Xenomorph99** [comment]
Here's a quick revision

![water-check](https://user-images.githubusercontent.com/1837101/87363137-c0f98680-c52d-11ea-87a3-b58c16d8940f.png)
![water-check-outline](https://user-images.githubusercontent.com/1837101/87363135-bfc85980-c52d-11ea-82d2-beaeba063014.png)

[water-check.zip](https://github.com/Templarian/MaterialDesign/files/4915619/water-check.zip)

**Comment by goyney** [comment]
[![water-check](https://materialdesignicons.com/icon/water-check)](https://materialdesignicons.com/icon/water-check)[![water-check-outline](https://materialdesignicons.com/icon/water-check-outline)](https://materialdesignicons.com/icon/water-check-outline)
