### ISSUE TITLE
Water Remove

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5322]
## Preview

![water-remove](https://user-images.githubusercontent.com/1837101/87342112-f12e2e80-c507-11ea-98e3-ee2609791eec.png)
![water-remove-outline](https://user-images.githubusercontent.com/1837101/87342110-f0959800-c507-11ea-8051-6b3c61108a5b.png)

## Zip Download

[water-remove.zip](https://github.com/Templarian/MaterialDesign/files/4914520/water-remove.zip)

**Comment by Templarian** [comment]
Double check the standard cut outs are used for these. Looks a little off.

**Comment by Templarian** [comment]
ToDo: Upload these as SVG, right now I don't have them all easily findable.

**Comment by Xenomorph99** [comment]
Here's the updated ones using the 12x12 template. They look better.

![water-remove](https://user-images.githubusercontent.com/1837101/87361952-978b2b80-c52a-11ea-9365-c6f94722e097.png)
![water-remove-outline](https://user-images.githubusercontent.com/1837101/87361949-96f29500-c52a-11ea-9ec2-8d4a470a84f1.png)

[water-remove.zip](https://github.com/Templarian/MaterialDesign/files/4915568/water-remove.zip)

**Comment by goyney** [comment]
[![water-remove](https://materialdesignicons.com/icon/water-remove)](https://materialdesignicons.com/icon/water-remove)[![water-remove-outline](https://materialdesignicons.com/icon/water-remove-outline)](https://materialdesignicons.com/icon/water-remove-outline)
