### ISSUE TITLE
Water Off Outline

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5323]
## Preview

![water-off-outline](https://user-images.githubusercontent.com/1837101/87342173-0dca6680-c508-11ea-9d1b-6aebb0cca5fb.png)

## Zip Download

[water-off-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/4914524/water-off-outline.svg.zip)

**Comment by goyney** [comment]
[![water-off-outline](https://materialdesignicons.com/icon/water-off-outline)](https://materialdesignicons.com/icon/water-off-outline)

Also updated `water-off` because the off modifier was incorrect.
