### ISSUE TITLE
Water Alert

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5324]
## Preview

![water-alert](https://user-images.githubusercontent.com/1837101/87342243-2b97cb80-c508-11ea-99d9-8d62a2841697.png)
![water-alert-outline](https://user-images.githubusercontent.com/1837101/87342240-2b97cb80-c508-11ea-9833-1ed033b79023.png)
![water-percent-alert](https://user-images.githubusercontent.com/1837101/87342247-2c306200-c508-11ea-9761-4fe2f0541dce.png)

## Zip Download

[water-alert.zip](https://github.com/Templarian/MaterialDesign/files/4914529/water-alert.zip)

**Comment by Xenomorph99** [comment]
Here's a quick revision to match the template.

![water-alert](https://user-images.githubusercontent.com/1837101/87362548-2e0c1c80-c52c-11ea-8f17-5a913fb26d8c.png)

![water-alert-outline](https://user-images.githubusercontent.com/1837101/87362547-2d738600-c52c-11ea-985f-5636a4969e22.png)

![water-percent-alert](https://user-images.githubusercontent.com/1837101/87362550-2ea4b300-c52c-11ea-8366-639a38bd3b50.png)

[water-alert.zip](https://github.com/Templarian/MaterialDesign/files/4915589/water-alert.zip)

**Comment by goyney** [comment]
[![water-alert](https://materialdesignicons.com/icon/water-alert)](https://materialdesignicons.com/icon/water-alert)[![water-alert-outline](https://materialdesignicons.com/icon/water-alert-outline)](https://materialdesignicons.com/icon/water-alert-outline)
[![water-percent-alert](https://materialdesignicons.com/icon/water-percent-alert)](https://materialdesignicons.com/icon/water-percent-alert)
