### ISSUE TITLE
Circle inside square icon (veg/non-veg)

### ISSUE THREAD

**Issue by Saunved** [Templarian/MaterialDesign#5325]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
There are similar issues but it seems like the requesters did not provide reference images and there was confusion as to what they were asking for (since this icon is used in the India/Sri Lanka region)
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Used to show whether a food item is vegetarian or non-vegetarian (in India/Sri Lanka).
[Wikipedia article with image for context](https://en.wikipedia.org/wiki/Vegetarian_and_non-vegetarian_marks)

## Examples
![](https://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Veg_NonVeg_SVG.svg/144px-Veg_NonVeg_SVG.svg.png)
The actual icon will be black and white, and we can color it using HTML/CSS.

**Comment by goyney** [comment]
[![square-circle](https://materialdesignicons.com/icon/square-circle)](https://materialdesignicons.com/icon/square-circle)

Aliased with `vegetarian` and `lacto-vegetarian`.
