### ISSUE TITLE
Office Location Icon

### ISSUE THREAD

**Issue by solomojo** [Templarian/MaterialDesign#5326]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

I thought this would be a good icon to have to indicate office location.    I would probably also do an outlined version too.
[office-location.zip](https://github.com/Templarian/MaterialDesign/files/4914839/office-location.zip)

**Comment by goyney** [comment]
Please don't remove the issue template. I've added it back in.

Please create a preview of your icon and paste it in your request for consideration. Thanks!

**Comment by solomojo** [comment]
Thanks goyney... FYI, the issue template wasn't there when I added the issue.  I've updated the .zip with a .ai containing both an outlined version and a filled version.  They look like this:  

![office-location](https://user-images.githubusercontent.com/5481983/87351435-a962d380-c516-11ea-9199-5c210ea42d98.png)
![office-location-outline](https://user-images.githubusercontent.com/5481983/87351448-ae278780-c516-11ea-8a40-b69f50dce6ad.png)
[office-location.zip](https://github.com/Templarian/MaterialDesign/files/4914993/office-location.zip)

**Comment by goyney** [comment]
We'll need a combined-path SVG to consider your contributions. Use the [preview generator](http://dev.materialdesignicons.com/contribute/github) to make sure everything looks right, then copy and paste that preview here.

**Comment by solomojo** [comment]
OK, here are the previews and I've added the combined-path SVGs to the zip folder attached.
![image](https://user-images.githubusercontent.com/5481983/87352262-001cdd00-c518-11ea-81d0-eac8c0eb031c.png)
![image](https://user-images.githubusercontent.com/5481983/87352367-2773aa00-c518-11ea-921f-ea1b24d6488e.png)
[office-location.zip](https://github.com/Templarian/MaterialDesign/files/4915056/office-location.zip)

**Comment by goyney** [comment]
Thanks! I think those are both a good start. Here's my feedback. 😄 

1. I'd put the markers on the right side of the icon. That is our typical "cut-out" location. Do a search for "marker" to see some other icons with the map marker modifier.
2. The outlined building has a 1dp outline, it needs to be a 2dp border. In this specific case, we'd probably want it to expand outward the extra 1dp to keep the windows in the same place. However, that might cause issues with the door, so we'll need to probably play around with that.
3. The modifiers don't have an filled/outlined distinction; they should always be filled. So, the map marker in the "outline" version of the icon should still be filled. Regardless, it's 1dp outline is too thin and would need to be 2dp if we were to go that route.

Hope that helps!

**Comment by goyney** [comment]
We should probably add an outline of `office-building` here too when we figure it out.

**Comment by solomojo** [comment]
Thanks goyney, I'll move the marker to the right side and fill it in, make the outline of the office building 2dp, and provide an oulined version of the office-building icon too.

**Comment by solomojo** [comment]
@goyney  Do you think this will work for the office-building-outline:  

![image](https://user-images.githubusercontent.com/5481983/87355325-6eb06980-c51d-11ea-8e0f-a60a128b7af1.png)

**Comment by solomojo** [comment]
Here's the filled in version with the marker on the right side:  

![image](https://user-images.githubusercontent.com/5481983/87357097-89381200-c520-11ea-8b5d-059eefeb9578.png)

[office-location.zip](https://github.com/Templarian/MaterialDesign/files/4915380/office-location.zip)

**Comment by solomojo** [comment]
Here is the office building outline:  

![image](https://user-images.githubusercontent.com/5481983/87358201-8f2ef280-c522-11ea-8cb4-6b3cac76dbdd.png)

[office-building-outline.zip](https://github.com/Templarian/MaterialDesign/files/4915419/office-building-outline.zip)

**Comment by goyney** [comment]
[![office-building-outline](https://materialdesignicons.com/icon/office-building-outline)](https://materialdesignicons.com/icon/office-building-outline)
[![office-building-marker](https://materialdesignicons.com/icon/office-building-marker)](https://materialdesignicons.com/icon/office-building-marker)[![office-building-marker-outline](https://materialdesignicons.com/icon/office-building-marker-outline)](https://materialdesignicons.com/icon/office-building-marker-outline)

**Comment by solomojo** [comment]
Awesome!  Thanks honey.
