### ISSUE TITLE
fan-speed....

### ISSUE THREAD

**Issue by frayberen** [Templarian/MaterialDesign#5327]
Hello Austin: I have tried to configure several icons of yours in my Home Assistant. Specifically the "fan-speed-1", "fan-speed-2" and "fan-speed-3", (mdi: fan-speed-1) but they do not appear. Is there a solution in this regard? Thanks from Spain.

**Comment by goyney** [comment]
Home Assistant has not yet updated past the 4.9.x release. See: https://github.com/home-assistant/frontend/issues/5094
