### ISSUE TITLE
Official icons themes

### ISSUE THREAD

**Issue by Danziger** [Templarian/MaterialDesign#5328]
If you check the official [Material Design icons](https://material.io/resources/icons/?icon=home&style=round) you can see there are different themes for them: Filled, outlined, rounded, two-tone and sharp.

However, those seem to be unavailable in this project, is that the case? Do you plan on adding support for those?

**Comment by goyney** [comment]
We provide filled and outlined versions. We do not have plans to support other styles at this time but have explored options for two-tone in the past.
