### ISSUE TITLE
tune-variant Icon

### ISSUE THREAD

**Issue by nithinankam** [Templarian/MaterialDesign#5329]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

<canvas _ngcontent-elj-c93="" width="325" height="294"></canvas>
![image](https://user-images.githubusercontent.com/8216363/87430310-a4e7fa80-c5aa-11ea-9df4-b2bfa0a3a866.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[filter.svg.zip](https://github.com/Templarian/MaterialDesign/files/4919000/filter.svg.zip)

**Comment by Xenomorph99** [comment]
This icon looks like it's the same as [tune](https://materialdesignicons.com/icon/tune) and [tune-vertical](https://materialdesignicons.com/icon/tune-vertical) which are already in the library.

**Comment by goyney** [comment]
I understand this is supposed to be a variant, but I don't really see the reasoning for it. Why not just use `tune(-vertical)`?

**Comment by nithinankam** [comment]
@goyney  It’s for visibility and clarity. 
This tune-variant icon is more recognizable for its function vs the given material design ones mentioned above.
It would fall under System icons which symbolize common action. However, I wouldn't be able to reason it out more 'coz its totally has the same purpose of `tune` but making it more visible and clear.

Just curious are `variants` of an icon discouraged ?

**Comment by JapanYoshi** [comment]
The lines are rounded, violating Material guidelines.

I don't agree that rounded handles are more recognizable than linear handles. Real sliders have square, not round, handles anyway.

**Comment by Xenomorph99** [comment]
Here's another idea to consider. Figma uses this settings/tune icon in their interface. If we did a rounded variant of ours maybe we drop a lines so it's just two like theirs is?

![image](https://user-images.githubusercontent.com/1837101/87804863-b41cb180-c811-11ea-962f-08082b3bfc64.png)

**Comment by Xenomorph99** [comment]
Like this or maybe shrink the knobs down a bit. 

![tune-variant](https://user-images.githubusercontent.com/1837101/87805704-03afad00-c813-11ea-99b6-d68a7f46a47a.png)
![tune-vertical-variant](https://user-images.githubusercontent.com/1837101/87805705-04484380-c813-11ea-951a-be7dcf6f02fb.png)

[tune-variant.zip](https://github.com/Templarian/MaterialDesign/files/4938737/tune-variant.zip)

**Comment by nithinankam** [comment]
Am fine with either of the above mentioned alternatives, let me know if this request can be addressed of its dead.

**Comment by Templarian** [comment]
@nithinankam I think the one @Xenomorph99 shared 3 days ago can be added. Removing the label.

**Comment by goyney** [comment]
[![tune-variant](https://materialdesignicons.com/icon/tune-variant)](https://materialdesignicons.com/icon/tune-variant)[![tune-vertical-variant](https://materialdesignicons.com/icon/tune-vertical-variant)](https://materialdesignicons.com/icon/tune-vertical-variant)
