### ISSUE TITLE
More circle icons

### ISSUE THREAD

**Issue by jonatasleon** [Templarian/MaterialDesign#533]
Has not of circle type from icons like facebook and twitter

**Comment by IgnaciodeNuevo** [comment]
This would be great, and more social media square icons with rounded corners

**Comment by jonatasleon** [comment]
[twitter-circle](https://github.com/Templarian/MaterialDesign/blob/58c6ee5daee9fcfad3502a7b7f480c923f2d2d7b/icons/svg/twitter-circle.svg) was added

**Comment by PeterShaggyNoble** [comment]
I'm going to close this one out as:
1. You can easy do this yourself with CSS, SVG layering/masking, etc.
2. There are already individual requests for some of these (e.g., #1800, #2720)

If you still have need for any of these, please open an individual request for each brand (multiple variants, such as `*-box` and `*-circle`, would be OK, though), not forgetting to search the existing issues before you do.
