### ISSUE TITLE
Access Point Medium & Low

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5330]
Here's two icons that relate to [access-point](https://materialdesignicons.com/icon/access-point) showing diminished signal strength.

_access-point-low_ is the same as [circle-small](https://materialdesignicons.com/icon/circle-small). I don't know if it's better to add a unique icon or if it's better adding an alias to [circle-small](https://materialdesignicons.com/icon/circle-small).

If we add these medium and low variants should be add the word 'high' to [access-point](https://materialdesignicons.com/icon/access-point)? I don't know if we have a convention. We should probably define this on the dev icon naming page.

[signal](https://materialdesignicons.com/icon/signal) uses a 1, 2, 3 pattern. [battery](https://materialdesignicons.com/icon/battery) has both a 10, 20, 30, ..., 90 and low-medium-high patterns.

## Preview

![access-point-medium](https://user-images.githubusercontent.com/1837101/87482228-3167dc80-c5ee-11ea-81b6-a4d6c0918348.png)
![access-point-low](https://user-images.githubusercontent.com/1837101/87482225-3036af80-c5ee-11ea-8ecd-c9ef9e54855b.png)

## Zip Download

[access-point-medium-and-low.zip](https://github.com/Templarian/MaterialDesign/files/4921787/access-point-medium-and-low.zip)

**Comment by goyney** [comment]
We've decided to not add this at this time. Thanks for the contribution.
