### ISSUE TITLE
Access Point Actions

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5333]
It would make sense to have a full set of [access point](https://materialdesignicons.com/icon/access-point) action icons for a project I'm working on.

## Preview

![access-point-plus](https://user-images.githubusercontent.com/1837101/87594654-89fcaf80-c6aa-11ea-8c49-133a537d9772.png)
![access-point-minus](https://user-images.githubusercontent.com/1837101/87594651-89fcaf80-c6aa-11ea-8396-00b14840d2fd.png)
![access-point-check](https://user-images.githubusercontent.com/1837101/87594647-89641900-c6aa-11ea-97b7-dc92e8e84acf.png)
![access-point-remove](https://user-images.githubusercontent.com/1837101/87594656-8a954600-c6aa-11ea-83a6-73961a02d0c3.png)

## Zip Download

[access-point-actions.zip](https://github.com/Templarian/MaterialDesign/files/4927901/access-point-actions.zip)

**Comment by goyney** [comment]
All added.
