### ISSUE TITLE
Missing changes in changelog

### ISSUE THREAD

**Issue by bramkragten** [Templarian/MaterialDesign#5334]
For Home Assistant 0.113 we made a conversion to deal with all the breaking changes in 4.9.95 -> 5.3.45.

I found at least one icon that was missing in the changelog, `visual-studio-code` -> `microsoft-visual-studio-code`, and I am now worried more might be missing.

Could you verify this in some way?

Thanks!

**Comment by Templarian** [comment]
- https://github.com/Templarian/MaterialDesign-SVG/commits/master

Above has each version tagged. We pull it from the commit log, but might have messed up. Sorry about that.

When I wrap up work today I can go through and double check the changelog and report any missing items.

**Comment by goyney** [comment]
I'm also checking right now. Better to have two sets of eyes on it.

**Comment by Templarian** [comment]
@bramkragten There were 470 changes in the 5.0.45 release. Looks like those two renames got left out.

- `visual-studio` -> `microsoft-visual-studio`
- `visual-studio-code` -> `microsoft-visual-studio-code`

**Comment by bramkragten** [comment]
Thank you very much for double checking this!

**Comment by bramkragten** [comment]
One final little remark, some icons are in the list in this issue <https://github.com/Templarian/MaterialDesign/issues/4901> that I used but are missing on the changelog/migration page <https://dev.materialdesignicons.com/upgrade#4.9.95-to-5.0.45>

Like `library-video` => `play-box-multiple` (that I found because it has a typo in that issue, play-box-mutiple -> play-box-multiple)

**Comment by Templarian** [comment]
@bramkragten Good catch! Pushed an update to fix these issues (should be on the site in ~5 minutes).

Our next release includes a lot of Home Assistant tagged icons, so it will be great to see the mappings working. 5.0 was our large break it for the future release, so relatively smooth now-a-days.

Thanks!
