### ISSUE TITLE
Timeline Minus

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5336]
## Preview

![timeline-minus](https://user-images.githubusercontent.com/1837101/87691029-5facff80-c747-11ea-8032-aa41eb64efad.png)
![timeline-minus-outline](https://user-images.githubusercontent.com/1837101/87691027-5f146900-c747-11ea-86d9-c219d2280928.png)

## Zip Download

[timeline-minus.zip](https://github.com/Templarian/MaterialDesign/files/4932474/timeline-minus.zip)

**Comment by goyney** [comment]
[![timeline-minus](https://materialdesignicons.com/icon/timeline-minus)](https://materialdesignicons.com/icon/timeline-minus)[![timeline-minus-outline](https://materialdesignicons.com/icon/timeline-minus-outline)](https://materialdesignicons.com/icon/timeline-minus-outline)
