### ISSUE TITLE
Timeline Remove

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5337]
For these icons, I simply rotated [timeline-plus](https://materialdesignicons.com/icon/timeline-plus) and [timeline-plus-outline](https://materialdesignicons.com/icon/timeline-plus-outline). Let me know if this works or not.

## Preview

![timeline-remove](https://user-images.githubusercontent.com/1837101/87691207-93882500-c747-11ea-9fbb-200b55bb2a87.png)
![timeline-remove-outline](https://user-images.githubusercontent.com/1837101/87691205-92ef8e80-c747-11ea-8137-61ee23f298fa.png)

## Zip Download

[timeline-remove.zip](https://github.com/Templarian/MaterialDesign/files/4932483/timeline-remove.zip)

**Comment by goyney** [comment]
[![timeline-remove](https://materialdesignicons.com/icon/timeline-remove)](https://materialdesignicons.com/icon/timeline-remove)[![timeline-remove-outline](https://materialdesignicons.com/icon/timeline-remove-outline)](https://materialdesignicons.com/icon/timeline-remove-outline)
