### ISSUE TITLE
Timeline Check

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5338]
I used the same checkmark from [check-network](https://materialdesignicons.com/icon/check-network) and [check-network-outline](https://materialdesignicons.com/icon/check-network-outline). I centered the check inside the box. It doesn't line up exactly to the grid, I'm assuming this is ok. If not, I can adjust it.

## Preview

![timeline-check](https://user-images.githubusercontent.com/1837101/87691582-f5488f00-c747-11ea-84b8-907105c1be8b.png)
![timeline-check-outline](https://user-images.githubusercontent.com/1837101/87691580-f4aff880-c747-11ea-857a-293a108b2987.png)

## Zip Download

[timeline-check.zip](https://github.com/Templarian/MaterialDesign/files/4932502/timeline-check.zip)

**Comment by goyney** [comment]
[![timeline-check](https://materialdesignicons.com/icon/timeline-check)](https://materialdesignicons.com/icon/timeline-check)[![timeline-check-outline](https://materialdesignicons.com/icon/timeline-check-outline)](https://materialdesignicons.com/icon/timeline-check-outline)
