### ISSUE TITLE
Thermometer Off

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5339]
I've got two options. Option A cuts the icon using the template but leaves a strange arcing tail on the top shape. I cut off the strange tail in option B to make the shape simpler.

## Preview

![thermometer-off-a](https://user-images.githubusercontent.com/1837101/87710697-4dd95580-c763-11ea-9ff7-b0d65b089cd7.png)
![thermometer-off-b](https://user-images.githubusercontent.com/1837101/87710699-4e71ec00-c763-11ea-9d6b-befc301e71c0.png)

## Zip Download

[thermometer-off-options.zip](https://github.com/Templarian/MaterialDesign/files/4933564/thermometer-off-options.zip)

**Comment by goyney** [comment]
The off modifier doesn't look quite right. Are you using the one from our base template?

**Comment by Xenomorph99** [comment]
I think it's an optical illusion. I checked it a few times before posting it. The solid slash is two pixels from the left, two up from the bottom, and four from the right.

![image](https://user-images.githubusercontent.com/1837101/87711684-d99fb180-c764-11ea-95d7-7088e8529219.png)

**Comment by Xenomorph99** [comment]
Here's the updated icon

![thermometer-off](https://user-images.githubusercontent.com/1837101/87713324-3dc37500-c767-11ea-8da5-cd6cff14df3a.png)

[thermometer-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/4933720/thermometer-off.svg.zip)

**Comment by goyney** [comment]
[![thermometer-off](https://materialdesignicons.com/icon/thermometer-off)](https://materialdesignicons.com/icon/thermometer-off)
