### ISSUE TITLE
Vine icon

### ISSUE THREAD

**Issue by dapearce** [Templarian/MaterialDesign#534]

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/vine

**Comment by dapearce** [comment]
Doh, sorry long day ha

**Comment by Templarian** [comment]
It wasn't there... it was just added. You just caught me in the middle of adding some other icons and that one was simple (vector is provided on their press page).

https://materialdesignicons.com/history

**Comment by dapearce** [comment]
Aaah okay thought I was going crazy
