### ISSUE TITLE
An icon for Monalisa

### ISSUE THREAD

**Issue by varun-vc** [Templarian/MaterialDesign#5340]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@varun-vc The issue template isn't optional. Can you fill it in with examples of what you mean.

Like the portrait Monalisa? In a 24x24 square... 🤨

**Comment by goyney** [comment]
Closing because the `Needs More Info` label was added over a week ago with no new suggestions or clarifications. Please comment back if you have other ideas that could help fulfill this request. Thank you for your suggestion!
