### ISSUE TITLE
Man user; Women user;  Man (generally); Women (generally) 

### ISSUE THREAD

**Issue by Czech-Lion** [Templarian/MaterialDesign#5342]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by JapanYoshi** [comment]
The template is NOT optional. Please fill it in.

**Comment by Templarian** [comment]
Are you talking about the `face-*` icons? Those exist already. This might be a duplicate.

**Comment by Templarian** [comment]
@Czech-Lion ^

**Comment by goyney** [comment]
Closing because the `Needs More Info` label was added a week ago with no new suggestions or clarifications. Please comment back if you have other ideas that could help fulfill this request. Thank you for your suggestion!
