### ISSUE TITLE
Medium Icon

### ISSUE THREAD

**Issue by manishdhakal** [Templarian/MaterialDesign#5343]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
Medium, as in the blogging site?

**Comment by goyney** [comment]
Medium was removed in the v5 release: https://github.com/Templarian/MaterialDesign/issues/4901

---

### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by oneezy** [comment]
why was this removed? I need it

**Comment by goyney** [comment]
Brand Icons are not Material. We deprecated many brand icons nearly 10 releases ago and removed them at the v5 release. If you need to use brand-specific icons, please check out [SimpleIcons](https://simpleicons.org/). They are a collection of brand icons and their packages work with MDI tooling.
