### ISSUE TITLE
Corridor/Hallway

### ISSUE THREAD

**Issue by AalianKhan** [Templarian/MaterialDesign#5344]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

I have home assistant and I group my devices into rooms. I couldn't find an icon that can represent my hallway which has lights. 
## Examples

Include any example images so we know what the icon should look like.

![image](https://user-images.githubusercontent.com/39784853/87863842-fdfaba00-c92d-11ea-867a-1132f2920fb3.png)

![image](https://user-images.githubusercontent.com/39784853/87863824-cf7cdf00-c92d-11ea-85bb-c633d6b64010.png)

![image](https://user-images.githubusercontent.com/39784853/87863840-eb808080-c92d-11ea-89cf-991d5fe667f1.png)

**Comment by goyney** [comment]
These break Material guidelines. We've actually added Google's official `hallway` icon, just under a different name.

https://github.com/Templarian/MaterialDesign/issues/3114

[![image-frame](https://materialdesignicons.com/icon/image-frame)](https://materialdesignicons.com/icon/image-frame)

**Comment by pafnow** [comment]
+1

**Comment by PatrickGlatz** [comment]
+1

**Comment by dalyand** [comment]
+1

**Comment by agsola** [comment]
+1
