### ISSUE TITLE
Lotus

### ISSUE THREAD

**Issue by TarNegar** [Templarian/MaterialDesign#5348]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Lotus is a flower mainly used in Persian culture. It is a symbol for lotus flower that exactly has 12 petals.
You can find it on ancient tablets in Persepolis (IR).

[Read more about Persepolis here](https://en.wikipedia.org/wiki/Persepolis)

## Examples

![Lotus](https://user-images.githubusercontent.com/20040995/87927685-d6743080-ca98-11ea-9fa5-6ccd7288daaa.png)
![Lotus In Persepolis](https://upload.wikimedia.org/wikipedia/commons/0/09/Medes_and_Persians_at_eastern_stairs_of_the_Apadana%2C_Persepolis.JPG)
![Persian Lotus](https://i.pinimg.com/originals/29/48/06/294806f6a68d675b2b3c5fe772945090.jpg)
![Persian Lotus](https://www.cais-soas.com/CAIS/Images2/Achaemenid/Persepolis/Persepolis_Damaged_Lotus.jpg)
![Persian Lotus](https://media.gettyimages.com/photos/lotus-basrelief-in-persepolis-iran-picture-id600257173?s=2048x2048)

**Comment by goyney** [comment]
[![spa](https://materialdesignicons.com/icon/spa)](https://materialdesignicons.com/icon/spa)[![spa-outline](https://materialdesignicons.com/icon/spa-outline)](https://materialdesignicons.com/icon/spa-outline)

Already aliased as `lotus` as well.

**Comment by TarNegar** [comment]
But the recomended Lotus design is different from design of spa!
