### ISSUE TITLE
Illustrator Style Pen Tool Icon

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#535]
These icons would be helpful for an illustration project. (Minus the small triangle in the bottom right corner on the first one)
![Pen Tool](http://i.imgur.com/pS6EAhq.png?1)

**Comment by goyney** [comment]
Since the image is broken now, here's a screen shot of what I assume he's requesting:
![screen shot 2018-11-18 at 11 01 39 pm](https://user-images.githubusercontent.com/1015040/48685762-f8ac0180-eb85-11e8-9615-13b425effc5b.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/48748887-6fa8cf00-ec46-11e8-9281-268b92277832.png)![image](https://user-images.githubusercontent.com/1015040/48748891-77687380-ec46-11e8-9368-175db88a863c.png)

[fountain-pen.zip](https://github.com/Templarian/MaterialDesign/files/2597889/fountain-pen.zip)

**Comment by Templarian** [comment]
[![fountain-pen](https://materialdesignicons.com/icon/fountain-pen)](https://materialdesignicons.com/icon/fountain-pen) [![fountain-pen-tip](https://materialdesignicons.com/icon/fountain-pen-tip)](https://materialdesignicons.com/icon/fountain-pen-tip)
