### ISSUE TITLE
Having issue implementing it on Twig template symfoony

### ISSUE THREAD

**Issue by heardofdezz** [Templarian/MaterialDesign#5350]

**Comment by Templarian** [comment]
@heardofdezz Can you give more details? Unfortunately I didn't write these docs, but we can look up who did.

http://dev.materialdesignicons.com/getting-started/php = @chteuchteu

**Comment by Templarian** [comment]
Removing the bug label until more details are given. Not familiar with any of this php stuff, so any context will help.

**Comment by chteuchteu** [comment]
This issue can be closed, we'll follow up on [this one](https://github.com/chteuchteu/MaterialDesignIcons-PHP/issues/2) :-)

**Comment by heardofdezz** [comment]
Yea sorry i accidently added the bug label to it.

i tried the mdi-php package for php, but didnt work out.
So i ended up just installing mdi via yarn, and uploaded the ressources file thru my wepback.config.js  : 
```
.addStyleEntry('css/app', [
        './node_modules/bootstrap/dist/css/bootstrap.min.css',
        './node_modules/mdi/css/materialdesignicons.min.css',
        './assets/css/app.css',
    ])
```

the build is success, mid is injected in my build css file. but when i called on any mdi value such mdi-arrow-down-thick this way {{mdi-arrow-down-thick}} i get a mdi doesnt exist.

**Comment by chteuchteu** [comment]
Yup - as stated on [this issue](https://github.com/chteuchteu/MaterialDesignIcons-PHP/issues/2), you have to install both `@mdi/svg` using yarn, and `mesavolt/mdi-php` using composer
