### ISSUE TITLE
Add icon sack-dollar

### ISSUE THREAD

**Issue by kelvindominguez1595** [Templarian/MaterialDesign#5351]
Hello, I would like you to add the sack-dollar currency icon please [like this](https://image.flaticon.com/icons/svg/82/82296.svg)

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I probably use a win list for demo or show a coin indicator for a game

## Examples

Include any example images so we know what the icon should look like.

![currency](https://user-images.githubusercontent.com/44550467/87990427-38d12f00-caa1-11ea-97c2-eeb07033bc36.png)

**Comment by goyney** [comment]
Thanks for the suggestion. Unfortunately, we are no longer adding icons with localized currency symbols as modifiers to existing icons. We recommend you use more generic icons to avoid localization and language barrier issues.
