### ISSUE TITLE
pilot (tie + cap)

### ISSUE THREAD

**Issue by syrynj** [Templarian/MaterialDesign#5352]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A guy with a cap is what I have in mind.
This way it can represent a pilot, taxi driver, even a police officer.
If possible, the icon can be even more specific with a wings sign on the hat

## Examples

Starting from 'account-tie', and putting a cap on it
![pilot](https://user-images.githubusercontent.com/12996425/88041223-61613380-cb4a-11ea-97d1-c019a9d2a37b.PNG)

**Comment by Templarian** [comment]
This might not be recognizable at such a small size. Look at `account-tie` for example. Wondering if there is another way to show this that would be recognizable at 1:1 sizing.

**Comment by syrynj** [comment]
I agree, 
Therefore I would be pleased of having an icon of awith a man with tie and the cap. This will clearly pass as a pilot. 
We can start with that and later see to add details for more specific use.

**Comment by goyney** [comment]
Here's one attempt:

![image](https://user-images.githubusercontent.com/1015040/89106733-618aea00-d3fa-11ea-8d34-7459d241b305.png)
[pilot.svg.zip](https://github.com/Templarian/MaterialDesign/files/5010993/pilot.svg.zip)

**Comment by Templarian** [comment]
@goyney The brim doesn't look quite right at 1:1. To cut down on confusion lets not add the `light` style here, we can manage them in the other repo.

**Comment by goyney** [comment]
[![account-tie-hat](https://materialdesignicons.com/icon/account-tie-hat)](https://materialdesignicons.com/icon/account-tie-hat)[![account-tie-hat-outline](https://materialdesignicons.com/icon/account-tie-hat-outline)](https://materialdesignicons.com/icon/account-tie-hat-outline)
