### ISSUE TITLE
Shelf Icon

### ISSUE THREAD

**Issue by jalakamkiran** [Templarian/MaterialDesign#5353]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

![image](https://user-images.githubusercontent.com/39314292/88057119-3a712480-cb7f-11ea-9d67-f8a28ee39a0a.png)

**Comment by goyney** [comment]
Already included:
[![bookshelf](https://materialdesignicons.com/icon/bookshelf)](https://materialdesignicons.com/icon/bookshelf)
