### ISSUE TITLE
Phone-wrong (phone with an x, like phone-check has a tick)

### ISSUE THREAD

**Issue by PurpleProgrammer** [Templarian/MaterialDesign#5354]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
[![phone-remove](https://materialdesignicons.com/icon/phone-remove)](https://materialdesignicons.com/icon/phone-remove)[![phone-remove-outline](https://materialdesignicons.com/icon/phone-remove-outline)](https://materialdesignicons.com/icon/phone-remove-outline)

**Comment by PurpleProgrammer** [comment]
Thank you @goyney !!
