### ISSUE TITLE
HD Video Camera

### ISSUE THREAD

**Issue by sentinel-23** [Templarian/MaterialDesign#5356]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For high-definition video camera streams. For example, in the Home Assistant UI. 

## Examples

![video-hd](https://user-images.githubusercontent.com/25797974/88306124-934bd480-ccc7-11ea-9c27-9bfa2a085c01.png)

**Comment by goyney** [comment]
Normally, we are keeping letters off of new icons for localization issues. However, I feel this one is universal enough to allow, especially since we have `high-definition(-box)`.

**Comment by goyney** [comment]
[![video-high-definition](https://materialdesignicons.com/icon/video-high-definition)](https://materialdesignicons.com/icon/video-high-definition)
