### ISSUE TITLE
Temporary

### ISSUE THREAD

**Issue by CoreyVidal** [Templarian/MaterialDesign#5357]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/20746389/88417824-a090be00-cdb0-11ea-9c6e-bd8331064c03.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[temp.zip](https://github.com/Templarian/MaterialDesign/files/4973670/temp.zip)

**Comment by Templarian** [comment]
Looks good. The name will be `delete-clock` (base + overlay).

**Comment by Templarian** [comment]
Added! By the way you can see your additions here (will be the same url when the new site launches).

http://materialdesignicons.com/contributor/Corey-Vidal

**Comment by CoreyVidal** [comment]
Hey, that's awesome! Didn't expect that.
Any chance you could use /coreyvidal (or /CoreyVidal) instead of with the dash? It'll align with my SEO. 🤓
Big fan of MDI. Been using them for 3+ years. Figured it was time I shared some of the custom ones I've made along the way.
Thanks for all your hard work!

**Comment by Templarian** [comment]
@CoreyVidal Done. 👍
