### ISSUE TITLE
application-settings

### ISSUE THREAD

**Issue by CoreyVidal** [Templarian/MaterialDesign#5358]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/20746389/88420334-b99b6e00-cdb4-11ea-881c-2e9d94e928cd.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[application-setings.zip](https://github.com/Templarian/MaterialDesign/files/4973515/application-setings.zip)

**Comment by Templarian** [comment]
Added / assigned to your name.
