### ISSUE TITLE
Logitech Harmony Hub (with and without Remote)

### ISSUE THREAD

**Issue by CoreyVidal** [Templarian/MaterialDesign#5359]
I have:

- [✓] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [✓] Searched open issues to make sure there isn't a request for this icon.
- [✓] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/20746389/88420404-d6d03c80-cdb4-11ea-8ce1-31362fd725f2.png)

![image](https://user-images.githubusercontent.com/20746389/88420455-ed769380-cdb4-11ea-81d3-8d47c6b12683.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[logitech-harmony-hub.zip](https://github.com/Templarian/MaterialDesign/files/4973557/logitech-harmony-hub.zip)

[logitech-harmony-hub-with-remote.zip](https://github.com/Templarian/MaterialDesign/files/4973559/logitech-harmony-hub-with-remote.zip)

**Comment by goyney** [comment]
Thanks for the suggestion. However, we don't add icons for specific devices or manufacturers anymore. There's too many to keep up with. Luckily, there are plenty of generic icons that can be used for your use cases.
