### ISSUE TITLE
Slide Share Icon

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#536]
It would be nice if you add slideshare icon.
See here : http://fortawesome.github.io/Font-Awesome/icon/slideshare/

**Comment by rpi-odoo** [comment]
Slide share icon in svg format

https://www.dropbox.com/s/5la09fsjqww4nu8/slideshare%20%28copy%29.svg?dl=0

**Comment by PeterShaggyNoble** [comment]
Closing this as SlideShare was bought out by LinkedIn and now use their iconography. See https://www.slideshare.net/about/logos
