### ISSUE TITLE
Kangaroo

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5361]
## Preview

![kangaroo](https://user-images.githubusercontent.com/1837101/88431109-e781b200-cdb6-11ea-8c1a-05b6fd27e3f2.png)

## Zip Download

[kangaroo.svg.zip](https://github.com/Templarian/MaterialDesign/files/4974018/kangaroo.svg.zip)

**Comment by goyney** [comment]
[![kangaroo](https://materialdesignicons.com/icon/kangaroo)](https://materialdesignicons.com/icon/kangaroo)
