### ISSUE TITLE
Improved stairs icon

### ISSUE THREAD

**Issue by smugleafdev** [Templarian/MaterialDesign#5362]
I think the current stairs icon can be improved, as its current state is actually _too_ geometric. I have downloaded the current stairs icon and modified it slightly. Unsure about it's placement on the grid, but otherwise I'm happy with it.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/20119855/88444356-f594fa00-cdd9-11ea-89df-d6ed11b58491.png)

## Zip Download

[stairs2.zip](https://github.com/Templarian/MaterialDesign/files/4974662/stairs2.zip)

**Comment by Templarian** [comment]
It's a nice idea, but I'm going to keep our current stairs as it conforms with the ADA recommended iconography for accessibility. That should make it quickly recognizable by a broad demographic.

There are also some other variants such as box etc where the zig/zag works nicer.

Thanks for creating this issue though, we're always going back and revising icons. 😃
