### ISSUE TITLE
connect

### ISSUE THREAD

**Issue by javad99** [Templarian/MaterialDesign#5364]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@javad99 Please don't delete the issue template. Can you fill out the example section. Search around Google so we can get an idea. "connect" can mean a lot of things. Images can be copy/pasted into comments.

Thanks.

**Comment by OlivierLDff** [comment]
Hi i'm also looking for a connect/disconnect icon that would indicate a connection to a server from client.
I'm currently thinking about using `power-plug-outline` or `link-variant`.
But i don't find anything that would represent a connection with a server.

I see quite often this kind of icon ![](https://cdn2.iconfinder.com/data/icons/ui-outline-set/128/Plug_Socket_Power_Outlet_Electric_Energy-512.png)
![](https://www.flaticon.com/premium-icon/icons/svg/2961/2961697.svg)

![socket battlenet](https://user-images.githubusercontent.com/17255804/91963313-fe98b580-ed0d-11ea-9621-dccd93f811e2.png)
Battle.net is using the power socket to indicate the process of connection to server.

Do you have a recommandation of icon do use for such case? 

Thank you for all the work.

**Comment by goyney** [comment]
[![connection](https://materialdesignicons.com/icon/connection)](https://materialdesignicons.com/icon/connection)

**Comment by OlivierLDff** [comment]
Perfect, would you consider a plug variant? Like connection/connection-off. And outlined variant?
