### ISSUE TITLE
beachtennis

### ISSUE THREAD

**Issue by elsonsilva** [Templarian/MaterialDesign#5365]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To be used in sports apps

## Examples

Maybe some palm tree + a tennis ball or a racquet

![image](https://user-images.githubusercontent.com/6776077/88468599-6b719200-cebc-11ea-80e8-01b731d8eabd.png)

**Comment by goyney** [comment]
I think this is too niche. We have both palm tree icons and tennis icons already.
