### ISSUE TITLE
av-receiver

### ISSUE THREAD

**Issue by elfhack** [Templarian/MaterialDesign#5366]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To represent it in audio control systems (and home assistant)

## Examples
Here's a couple of AVRs. Usually a monoblock with one or two dials
![proxy-image-3](https://user-images.githubusercontent.com/18247748/88480946-43843c00-cf59-11ea-8c67-64dff7b30a2c.jpg)
![proxy-image-2](https://user-images.githubusercontent.com/18247748/88480951-4717c300-cf59-11ea-8dd7-23a40be18cc9.jpg)
![proxy-image](https://user-images.githubusercontent.com/18247748/88480953-497a1d00-cf59-11ea-84ef-3d76d4630585.jpg)

**Comment by Templarian** [comment]
Added `av-receiver` alias to `audio-video`. Oversight there. 🤔

**Comment by Templarian** [comment]
Added it to the `-off` overlay also.
