### ISSUE TITLE
combination of "floor-lamp" and "lamp"

### ISSUE THREAD

**Issue by cjmjmartens** [Templarian/MaterialDesign#5367]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

An icon which contains the combination of "floor-lamp" and "lamp" can be used in situations where you would like to show that multiple lamps can be switched on or off, e.g. in house or in the garden. 
## Examples

I would use the icons above and combine them in one icon.

**Comment by goyney** [comment]
They're the same icon, just the middle support is longer. I'd recommend we look at creating a `-multiple` variation of one or both of these icons for this request instead of trying to put two different length lamps in one icon.

**Comment by cjmjmartens** [comment]
Hi Michael,

Thanks for your reaction. Your plan sounds very good. When do you expect that a first version will be available? 

Kind regards,

Corné

**Comment by goyney** [comment]
After doing some experimentation with `lamp-multiple` and `floor-lamp-multiple`, I think I'd like to retract my initial comment; they don't really work.

Going with the original suggestion from @cjmjmartens, I think we might be better off creating a whole new icon simply called `lamps`.

![image](https://user-images.githubusercontent.com/1015040/88747069-06b47280-d11c-11ea-8c28-c0b0c0bb39bc.png)
[lamps.svg.zip](https://github.com/Templarian/MaterialDesign/files/4992021/lamps.svg.zip)

**Comment by goyney** [comment]
[![lamps](https://materialdesignicons.com/icon/lamps)](https://materialdesignicons.com/icon/lamps)
