### ISSUE TITLE
mdi-twitter is broken

### ISSUE THREAD

**Issue by wswilliams67** [Templarian/MaterialDesign#5369]
In the cheatsheet and in the font itself mdi-twitter is broken and displays no icon.

**Comment by goyney** [comment]
I see it just find in both the [cheatsheet](http://materialdesignicons.com/cdn/5.1.45/) and the TTF font.

![Screen Shot 2020-07-27 at 12 01 21 PM](https://user-images.githubusercontent.com/1015040/88564188-e5129880-d000-11ea-8c58-a3e63c6acb06.png)

Can you please provide more information?

**Comment by Templarian** [comment]
Tested in Chrome / FF / Safari. Looks fine. Disable any plugins or try in incognito.

Some ad blocking tools are very sensitive to "brand" related CSS classes.

**Comment by wswilliams67** [comment]
Yep it was a new version of adblocker. Thanks.
