### ISSUE TITLE
Brand Icons: Paypal, Visa, Mastercard

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#537]
It would be great if you add paypal, visa and mastercard icons too.

For reference see the links below:

http://fortawesome.github.io/Font-Awesome/icon/paypal/
http://fortawesome.github.io/Font-Awesome/icon/cc-visa/
http://fortawesome.github.io/Font-Awesome/icon/cc-mastercard/

**Comment by Templarian** [comment]
#297 #194

**Comment by rpi-odoo** [comment]
Sorry For that....

**Comment by Templarian** [comment]
No problem. Feel free to suggest any others. Somethings don't fit in this pack due to style restrictions and size. But mostly everything else are fine suggestions.

**Comment by CoDEmanX** [comment]
Maybe split out all brand icons to a separate project / font? I thought of adding a tag "brand" while I worked on the to-do spreadsheet, but I think it's way cleaner to have them all in a different place.

**Comment by rpi-odoo** [comment]
Thats true. So that the icons can be easily maintained.
