### ISSUE TITLE
Tooltip Remove

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5370]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![tooltip-remove](https://user-images.githubusercontent.com/1837101/88575586-5b16ff80-d001-11ea-8054-01494b1241e0.png)
![tooltip-remove-outline](https://user-images.githubusercontent.com/1837101/88575585-5a7e6900-d001-11ea-8208-04537acd5ef2.png)

## Zip Download

[tooltip-remove.zip](https://github.com/Templarian/MaterialDesign/files/4983700/tooltip-remove.zip)

**Comment by goyney** [comment]
[![tooltip-remove](https://materialdesignicons.com/icon/tooltip-remove)](https://materialdesignicons.com/icon/tooltip-remove)[![tooltip-remove-outline](https://materialdesignicons.com/icon/tooltip-remove-outline)](https://materialdesignicons.com/icon/tooltip-remove-outline)
