### ISSUE TITLE
Tooltip Minus

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5371]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![tooltip-minus](https://user-images.githubusercontent.com/1837101/88575708-8863ad80-d001-11ea-91ab-a284ac84a8ba.png)
![tooltip-minus-outline](https://user-images.githubusercontent.com/1837101/88575706-8863ad80-d001-11ea-9f68-8917b4e787a9.png)

## Zip Download

[tooltip-minus.zip](https://github.com/Templarian/MaterialDesign/files/4983708/tooltip-minus.zip)

**Comment by goyney** [comment]
[![tooltip-minus](https://materialdesignicons.com/icon/tooltip-minus)](https://materialdesignicons.com/icon/tooltip-minus)[![tooltip-minus-outline](https://materialdesignicons.com/icon/tooltip-minus-outline)](https://materialdesignicons.com/icon/tooltip-minus-outline)
