### ISSUE TITLE
Tooltip Check

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5372]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![tooltip-check](https://user-images.githubusercontent.com/1837101/88575811-aaf5c680-d001-11ea-9dfa-93944e606584.png)
![tooltip-check-outline](https://user-images.githubusercontent.com/1837101/88575807-aa5d3000-d001-11ea-9813-0f0f7228e886.png)

## Zip Download

[tooltip-check.zip](https://github.com/Templarian/MaterialDesign/files/4983720/tooltip-check.zip)

**Comment by goyney** [comment]
[![tooltip-check](https://materialdesignicons.com/icon/tooltip-check)](https://materialdesignicons.com/icon/tooltip-check)[![tooltip-check-outline](https://materialdesignicons.com/icon/tooltip-check-outline)](https://materialdesignicons.com/icon/tooltip-check-outline)
