### ISSUE TITLE
star-plus, star-minus, star-plus-outline and star-minus-outline

### ISSUE THREAD

**Issue by Arkshine** [Templarian/MaterialDesign#5373]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Example: to be used as button to add/remove a rating. 

## Examples

Typically the `+` or `-` would be located at the bottom right, like most of `{icon}-plus` or `{icon}-minus`  (e.g. `bell-plus`, `bell-minus)`.

**Comment by goyney** [comment]
`plus`, `minus`, `remove`, and `check` versions of the filled and outline have been added.
