### ISSUE TITLE
Pretzel

### ISSUE THREAD

**Issue by Nico0302** [Templarian/MaterialDesign#5374]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/28566744/88674322-f71c3600-d0e9-11ea-8adf-134122eea67a.png)

## Zip Download

[pretzel.zip](https://github.com/Templarian/MaterialDesign/files/4988711/pretzel.zip)

**Comment by goyney** [comment]
[![pretzel](https://materialdesignicons.com/icon/pretzel)](https://materialdesignicons.com/icon/pretzel)

Great first issue! We've assigned this icon to the generic contributor account for now. Once you hit 5 icons added, let us know and we'll get you set up and all your icons assigned to you.
