### ISSUE TITLE
phone-dial

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#5375]
I was in need of a "phone-dial" icon to express a _phone number_. I thought that the current "dialpad" icon was not explicit enought for that purpose. What do you think of this proposition ?

## Preview

![image](https://user-images.githubusercontent.com/6012554/88688290-7402dc00-d0f9-11ea-96ac-390430721450.png)
![image](https://user-images.githubusercontent.com/6012554/88688211-5e8db200-d0f9-11ea-8e37-1290bbbe2899.png)

## Zip Download

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/4989414/Archive.zip)

**Comment by goyney** [comment]
[![phone-dial](https://materialdesignicons.com/icon/phone-dial)](https://materialdesignicons.com/icon/phone-dial)[![phone-dial-outline](https://materialdesignicons.com/icon/phone-dial-outline)](https://materialdesignicons.com/icon/phone-dial-outline)
