### ISSUE TITLE
Apple Airplay Audio

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5376]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

![exploration](https://user-images.githubusercontent.com/1837101/88697861-831a6780-d0c2-11ea-9590-9fa8de21ff73.png)

Here's a material version of the Apple iOS audio Airplay icon. I used the triangle from [apple-airplay](https://materialdesignicons.com/icon/apple-airplay) as the base. In doing so, I think the 1.5px rings in option "C" work best when compared to the 2px rings in [access-point](https://materialdesignicons.com/icon/access-point) and option "A".

## Preview

![apple-airplay-audio](https://user-images.githubusercontent.com/1837101/88697869-87468500-d0c2-11ea-9f93-103aac3c8bdd.png)

## Zip Download

[apple-airplay-audio.zip](https://github.com/Templarian/MaterialDesign/files/4989934/apple-airplay-audio.zip)

**Comment by PeterShaggyNoble** [comment]
If we add this, we should probably suffix our existing icon with `-video`. Also, as a brand icon, we probably shouldn't be Materialising it; an official SVG can be found at https://developer.apple.com/design/human-interface-guidelines/airplay/overview/icons/

Personally, though, I think we should be deprecating our existing icon for `v6`.

**Comment by goyney** [comment]
I don't think this get named `apple-airplay-audio`, but some more generic. I also don't agree with deprecated the other airplay icon, because it really is very generic. It probably should just be renamed.

**Comment by goyney** [comment]
I wouldn't consider these Brand Icons. These are system icons in a different icon style other than Material. To include them in a Material library, we need to Materialize them.

**Comment by Xenomorph99** [comment]
We have Google's [cast](https://materialdesignicons.com/icon/cast) icon in our library. Maybe we change [apple-airplay](https://materialdesignicons.com/icon/apple-airplay) to "cast-variant" and this icon could be called "cast-audio" or "cast-audio-variant".

**Comment by goyney** [comment]
Renamed and added.
