### ISSUE TITLE
Eiffel Tower

### ISSUE THREAD

**Issue by Nico0302** [Templarian/MaterialDesign#5378]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![eiffel-tower](https://user-images.githubusercontent.com/28566744/88718869-b096fd80-d122-11ea-9fb9-a9fc8e790cbf.png)

## Zip Download

[eiffel-tower.zip](https://github.com/Templarian/MaterialDesign/files/4991066/eiffel-tower.zip)

**Comment by goyney** [comment]
Added. That's 2 icons for you!

[![eiffel-tower](https://materialdesignicons.com/icon/eiffel-tower](https://materialdesignicons.com/icon/eiffel-tower)
