### ISSUE TITLE
X icon

### ISSUE THREAD

**Issue by mattrossman** [Templarian/MaterialDesign#5379]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For canceling actions or deleting input.

## Examples

I'm looking at one right now next to this issue:
<img width="293" alt="image" src="https://user-images.githubusercontent.com/22670878/88720163-6ac24100-d0f2-11ea-8d35-19b70c25cc36.png">

Another example, close up:
<img width="188" alt="image" src="https://user-images.githubusercontent.com/22670878/88720224-8594b580-d0f2-11ea-851e-950564324bdc.png">

This is such a common UI element, I'm amazed it doesn't exist yet. Maybe I'm not searching for the right thing but I tried "X" and "cancel" as queries, the only thing I see is the alpha-x icon which is not the same.

**Comment by goyney** [comment]
[![window-close](https://materialdesignicons.com/icon/window-close)](https://materialdesignicons.com/icon/window-close)

Adding some aliases.

**Comment by PeterShaggyNoble** [comment]
We also have a number of `close-*` icons, in various styles: https://petershaggynoble.github.io/MDI-Sandbox/?filter=close

**Comment by mattrossman** [comment]
Thanks, "close" was what I needed. I kept thinking of it as an "X" or "cancel" button so those extra aliases would be great 👍
