### ISSUE TITLE
Sitemap

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#538]
Like this:
http://fortawesome.github.io/Font-Awesome/icon/sitemap/

**Comment by CoDEmanX** [comment]
Margin left and right only 1px, but otherwise the lines wouldn't be centered or the the squares too small:
![sitemap](https://cloud.githubusercontent.com/assets/1309249/8955632/c7300282-35ee-11e5-8aa8-a69e6392f8d7.png) https://www.dropbox.com/s/7c2egyjlczjatif/sitemap.svg?dl=0

**Comment by rpi-odoo** [comment]
Good Job. Keep it up.

**Comment by CoDEmanX** [comment]
Increased rounding to recommended 2px:
![sitemap2](https://cloud.githubusercontent.com/assets/1309249/8985550/40e8ddee-36d8-11e5-8f20-51632bcc9b0e.png) https://www.dropbox.com/s/y9c1ey20sbo7gpd/sitemap2.svg?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/sitemap
