### ISSUE TITLE
Icon request for GNU Emacs

### ISSUE THREAD

**Issue by peterwu** [Templarian/MaterialDesign#5381]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Many people use Emacs.

## Examples

![image](https://user-images.githubusercontent.com/584751/88727188-15d7f800-d0fd-11ea-9427-1c12d3c2ebba.png)

**Comment by goyney** [comment]
Thank you for your suggestion, however we cannot add this icon to the library at this time. This is considered a brand icon, so we must adhere to the brand's official guidelines. Unfortunately, Emacs does not provide a single-color version of their logo. If they release an official, single-color version of their logo in the future, we may be able to reconsider this request.

**Comment by PeterShaggyNoble** [comment]
We recommend [Simple Icons](https://simpleicons.org/) for brand icons, where this is already available:

[![GNU Emacs](https://user-images.githubusercontent.com/15157491/88824533-5fd4e280-d1be-11ea-845f-bece16d28f20.png)](https://simpleicons.org/?q=GNU%20Emacs)

**Comment by peterwu** [comment]
Well, I was aware that such icons were available from other icons fonts but I was hoping that Material Design Icons font could include the Emacs icon for uses such as the workspace icon in a tiling window manager. As part of the ricing exercise, people tend to use pretty and meaningful icons to represent the workspaces they're in. Emacs is one of the most popular free open source programs and providing an Emacs icon in this font will help many people better identify they're working in an Emacs session/workspace.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
