### ISSUE TITLE
Family Tree Icon

### ISSUE THREAD

**Issue by Albert-Jan** [Templarian/MaterialDesign#5382]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide navigational icons to sections related to family trees.

## Examples

Include any example images so we know what the icon should look like.

[Example 1](https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcR_-K5XIjddSb7p94ZbWOI-NkOiL27xXAu9tw&usqp=CAU)
![tree](https://user-images.githubusercontent.com/11318861/88779737-647fa380-d18a-11ea-8ec4-c521aecf2c85.png)

**Comment by goyney** [comment]
Probably could make a variant of `graph(-outline)` to support this.

**Comment by Simran-B** [comment]
MIE has a `tenancy` icon:

![image](https://user-images.githubusercontent.com/7819991/89075169-dd931c80-d37d-11ea-822d-00d05018730e.png)

**Comment by Simran-B** [comment]
We also have this:

![image](https://user-images.githubusercontent.com/7819991/89075233-04515300-d37e-11ea-84b0-7634a2876f08.png)

Not sure how legible it would still be with added circles

**Comment by Simran-B** [comment]
Not really working I'm afraid:

![image](https://user-images.githubusercontent.com/7819991/89075517-affaa300-d37e-11ea-8b70-b753f63cd707.png)

![image](https://user-images.githubusercontent.com/7819991/89075540-bee15580-d37e-11ea-9f3e-463a4ab7553e.png)

**Comment by goyney** [comment]
What if we extended the middle section a little bit?
![image](https://user-images.githubusercontent.com/1015040/89093089-2f8b7080-d385-11ea-9fe2-12b5f15e288a.png)![image](https://user-images.githubusercontent.com/1015040/89093092-374b1500-d385-11ea-9f75-7d8e8b129fbb.png)

**Comment by goyney** [comment]
And now that I'm looking at these more, wonder if we just do the `outline` version and literally call it `family-tree`.

**Comment by Simran-B** [comment]
Not too bad actually. But it bothers me a little that the distance above and below the central circles is different. Here are some more consistent versions:

![image](https://user-images.githubusercontent.com/7819991/89132260-41028300-d513-11ea-9821-bfa897dbcca5.png) ![image](https://user-images.githubusercontent.com/7819991/89132329-a0f92980-d513-11ea-99af-96ec52ecc2a9.png)
![image](https://user-images.githubusercontent.com/7819991/89132363-e289d480-d513-11ea-9dd6-d6514bc74f25.png)

And variants with larger circles:

![image](https://user-images.githubusercontent.com/7819991/89132880-96d92a00-d517-11ea-9863-5cc58d42c400.png) ![image](https://user-images.githubusercontent.com/7819991/89132953-2979c900-d518-11ea-9fd6-a69dab89cb38.png)

[family-tree.zip](https://github.com/Templarian/MaterialDesign/files/5013014/family-tree.zip)

**Comment by goyney** [comment]
[![family-tree](https://materialdesignicons.com/icon/family-tree)](https://materialdesignicons.com/icon/family-tree)
