### ISSUE TITLE
Todo / Kanban / Scrum Icons

### ISSUE THREAD

**Issue by h-zone** [Templarian/MaterialDesign#5384]
I have:

- [v ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ v] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ v] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

ToDo and/or Kanban and/or Scrum and/or any another Agile application/list/item

## Examples

ToDo list/item
Any Agile list/item

**Comment by goyney** [comment]
Would something like our `format-list-checks` work?

[![format-list-checks](https://materialdesignicons.com/icon/format-list-checks)](https://materialdesignicons.com/icon/format-list-checks)

**Comment by Nico0302** [comment]
Some online articles illustrate agile workflows with looping arrows:
![image](https://media.planview.com/wp-content/uploads/2018/07/basics-and-benefits-of-agile-method1-1024x486.jpg)
Maybe something like this (I would give it a more general name):
![image](https://user-images.githubusercontent.com/28566744/88822724-839b2700-d1c4-11ea-9f09-8b05b8d42893.png)
![reiterate](https://user-images.githubusercontent.com/28566744/88823752-bdb8f880-d1c5-11ea-856d-e16f9a00f59f.png)

**Comment by goyney** [comment]
Ohh, I like those. Not sure which one though, maybe the first.

**Comment by Nico0302** [comment]
I also think that the first one is a bit better since the horizontal arrow is more recognizable.

[reiterate.zip](https://github.com/Templarian/MaterialDesign/files/4996169/reiterate.zip)

**Comment by Simran-B** [comment]
Hm, I like the 2nd at large scale, but it's difficult to see at small size.

Here are two variants with slightly smaller circle sizes:

![image](https://user-images.githubusercontent.com/7819991/89074586-dfa8ab80-d37c-11ea-906e-14b59de5bae1.png) ![image](https://user-images.githubusercontent.com/7819991/89074546-d0c1f900-d37c-11ea-84b0-f691e45e6687.png)

The left arrow touching the bottom line in the 1st one makes it illegible IMO, but the 2nd variant would work quite well IMO.

[reiterate2.zip](https://github.com/Templarian/MaterialDesign/files/5008944/reiterate2.zip)

**Comment by goyney** [comment]
[![reiterate](https://materialdesignicons.com/icon/reiterate)](https://materialdesignicons.com/icon/reiterate)
