### ISSUE TITLE
Akatsuki symbol

### ISSUE THREAD

**Issue by rauberJv** [Templarian/MaterialDesign#5388]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
-Symbol in rpg browser based game

## Examples

Include any example images so we know what the icon should look like.

https://i.pinimg.com/564x/0e/b3/0a/0eb30ae9c0242bbc44b4761c5010f469--nerdy-tattoos-small-tattoos.jpg

**Comment by goyney** [comment]
This is way too niche.

**Comment by JapanYoshi** [comment]
Yep, even less relevant than a brand account.
