### ISSUE TITLE
GU10 Downlight

### ISSUE THREAD

**Issue by Nalith** [Templarian/MaterialDesign#5389]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home automation software to indicate GU10 down lights.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
Duplicate of #4597.
