### ISSUE TITLE
Icon Request: Skype

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#539]
Skype icon should be there..

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/skype

**Comment by CoDEmanX** [comment]
How about an outline version for Skype for Business (former Lync)?

**Comment by Templarian** [comment]
That would be a good idea. If you do this use the version I created. I  made it pixel perfect.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/skype-business
