### ISSUE TITLE
Tablet (drug)

### ISSUE THREAD

**Issue by fabian-michael** [Templarian/MaterialDesign#5391]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Currently there is just a pill icon but for my purpose I need an icon of a tablet.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
`minus-circle` is going to be your best bet. A tablet is typically round with a perforation to make breaking it in half easier.

[![minus-circle](https://materialdesignicons.com/icon/minus-circle)](https://materialdesignicons.com/icon/minus-circle)

**Comment by goyney** [comment]
Aliases added to `minus-circle(-outline)`.
