### ISSUE TITLE
Select text size

### ISSUE THREAD

**Issue by FlVis** [Templarian/MaterialDesign#5392]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by FlVis** [comment]
For article pages that allow users to select text size when reading, is there a material icon/combination of icons that can be used for this purpose?

**Comment by JapanYoshi** [comment]
Please search the site before making an issue. http://materialdesignicons.com/icon/format-size
