### ISSUE TITLE
baseball-diamond(-outline)

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#5396]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1015040/89141244-fc2a1c80-d511-11ea-851b-7d760b7a53e2.png)![image](https://user-images.githubusercontent.com/1015040/89141258-0d732900-d512-11ea-9fdf-a0bbcf275251.png)

## Zip Download

[baseball-diamond.zip](https://github.com/Templarian/MaterialDesign/files/5013597/baseball-diamond.zip)

**Comment by Templarian** [comment]
🤷‍♂️ Maybe, I just can't get my eyes to actually see it in the smaller size. Looks like a fan/broom.
