### ISSUE TITLE
Router Wireless Off

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5399]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Here's the OFF modifier for [router-wireless](https://materialdesignicons.com/icon/router-wireless). I followed the template for the slash.

## Preview

![router-wireless-off](https://user-images.githubusercontent.com/1837101/89201903-6b822980-d56f-11ea-9198-e9bec60f7087.png)

## Zip Download

[router-wireless-off.zip](https://github.com/Templarian/MaterialDesign/files/5016982/router-wireless-off.zip)

**Comment by goyney** [comment]
[![router-wireless-off](https://materialdesignicons.com/icon/router-wireless-off)](https://materialdesignicons.com/icon/router-wireless-off)
