### ISSUE TITLE
account-graduation

### ISSUE THREAD

**Issue by SleepingProgrammer** [Templarian/MaterialDesign#5401]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It can be used for educational background, or graduates icon. This would be much better than just using the mdi-school if you were using a lot of the mdi-account series already, here is an example from my sidebar. (I added the educational background to the resume but I think it would be more fitting to use this requested icon instead of just the actual mdi-school

![image](https://user-images.githubusercontent.com/32633305/89745344-c5da3780-dae5-11ea-8e94-98b79425f2b7.png)

## Examples

Here is what it would roughly look like. Sorry for my horrible illustration lol

![image](https://user-images.githubusercontent.com/32633305/89745398-2ec1af80-dae6-11ea-9537-24b5029529a4.png)

**Comment by goyney** [comment]
The issue template is not optional. Please fill it out.

**Comment by SleepingProgrammer** [comment]
> 
> 
> The issue template is not optional. Please fill it out.

Thanks goyney, I wasn't about to push through with this request and I thought it wasn't posted so left it blank. But since it got to your attention already, I decided to update it anyway. Please do let me know if you think this would be a good addition. Thanks!

**Comment by viktor-yakubiv** [comment]
I tried a few options and this one seems to be the best. I know, the line aside is not aligned to the grid, I will do it later. How does this look in general? Any suggestions?

![image](https://user-images.githubusercontent.com/8440244/92704477-a724c600-f35b-11ea-9b9a-831f45301477.png)

By the way, why is this called 'account-graduation' but not 'account-school' as a combination of the two other icon names? However, both names seem to be correct, maybe we need an alias for this?

**Comment by goyney** [comment]
It would likely be called `account-school` when we add it. We name it when we add it, everything else is just suggestions until that point.

In terms of the icon, I think I'd like to see the hat exaggerated a little bit more in terms of size. It's kinda lost at native resolution.

**Comment by viktor-yakubiv** [comment]
@goyney I added 2 more vertical pixels to the hat but I am not sure it looks better.

![account-school updated](https://user-images.githubusercontent.com/8440244/92730321-4659b580-f37c-11ea-98bd-30291fb633ca.png)

If I avoid snapping everything to the pixel grid and let the hat have even pixel height, it seems to be a bit better to me.

![account-school even pixel hat](https://user-images.githubusercontent.com/8440244/92731000-34c4dd80-f37d-11ea-896c-31daf181ddaa.png)

What do you think?

**Comment by SleepingProgrammer** [comment]
It looks good! This is another masterpiece of an icon to the account icon series. Congratulations to the team for a job very well done. I'm looking forward to using this in the future! Cheers!

**Comment by SleepingProgrammer** [comment]
I agree with the account-school. I just thought that it could be described better with account-graduation for the use cases. But based on how I use mdi, it would make more sense if we use account-school instead of account-graduation. Thanks!

**Comment by Templarian** [comment]
[![account-school](https://materialdesignicons.com/icon/account-school)](https://materialdesignicons.com/icon/account-school) [![account-school-outline](https://materialdesignicons.com/icon/account-school-outline)](https://materialdesignicons.com/icon/account-school-outline)

**Comment by viktor-yakubiv** [comment]
@Templarian thanks a lot for this!
