### ISSUE TITLE
Alarm Panel

### ISSUE THREAD

**Issue by IIAIronWolf** [Templarian/MaterialDesign#5402]
I have:

- [ X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use to signify an alarm panel.

## Examples

Intend to use as the header icon on my Home Assistant alarm panel. Idea is to have an icon that is similar to the attached image (NOTE: I do not own the example icon).
![burglar_alarm6-512](https://user-images.githubusercontent.com/51146434/89340348-36f09980-d665-11ea-9bc4-acc3a8f2738c.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/89341018-a9b24280-d66e-11ea-8bf8-0a525ef1d6ee.png)![image](https://user-images.githubusercontent.com/1015040/89341040-b040ba00-d66e-11ea-91ba-4fe6bfdfb4dd.png)

[alarm-panel.zip](https://github.com/Templarian/MaterialDesign/files/5024327/alarm-panel.zip)

**Comment by JamesCoyle** [comment]
Would it look any better with square buttons? To me it looks like when they take a 4:3 show on TV and for some bizarre reason stretch it to 16:9 so everything is distorted.

**Comment by goyney** [comment]
Here is my alarm panel. I've never seen one with square buttons.
![image](https://user-images.githubusercontent.com/1015040/89342426-c94a6a80-d670-11ea-9aec-ace261a29e45.jpeg)

**Comment by IIAIronWolf** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/1015040/89341018-a9b24280-d66e-11ea-8bf8-0a525ef1d6ee.png)![image](https://user-images.githubusercontent.com/1015040/89341040-b040ba00-d66e-11ea-91ba-4fe6bfdfb4dd.png)
> 
> [alarm-panel.zip](https://github.com/Templarian/MaterialDesign/files/5024327/alarm-panel.zip)

That looks perfect!

**Comment by goyney** [comment]
> Would it look any better with square buttons? To me it looks like when they take a 4:3 show on TV and for some bizarre reason stretch it to 16:9 so everything is distorted.

Plus, we already have square buttons. It's called `calculator`. 😄

**Comment by goyney** [comment]
[![alarm-panel](https://materialdesignicons.com/icon/alarm-panel)](https://materialdesignicons.com/icon/alarm-panel)[![alarm-panel-outline](https://materialdesignicons.com/icon/alarm-panel-outline)](https://materialdesignicons.com/icon/alarm-panel-outline)
