### ISSUE TITLE
Generate (or) Create

### ISSUE THREAD

**Issue by biddlecom** [Templarian/MaterialDesign#5404]
I have:

- [X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I am creating an app and looked for an icon that would symbolize "Generate" or "Create".  I don't even know what this would look like as an icon.  But specifically, (in my case) I would be asking the user to generate or create a password.  I was just looking for an icon that would symbolize that.

Just a suggestion, so that maybe down the road in case someone else would need that icon, it would be there already.

## Examples

Include any example images so we know what the icon should look like.  --Not a clue.  =(

**Comment by goyney** [comment]
For something that is auto-generated, a lot of the times you will see something like our `refresh` or `sync` icons.

LastPass uses the `refresh` icon with a lock in the middle for password generation. Unfortunately, that won't work under Material rules; there isn't enough room to get the lock a decent size and have the arrow head.

We also have `form-textbox-password` for password form fields which might suit your use case.

Anything there help?

I just think this is too generic to represent without any other context. Most of the `plus` variants would fit for this idea, depending on what you are targeting.

**Comment by biddlecom** [comment]
Wow, you guys respond quickly! Sorry I didn't.  I am currently using "refresh" and "plus" in my app.  I didn't see the "form-textbox-password" sorry about that.  I think that would probably work.  Thank you for your time and attention.  I think that we can close the books on this one.

**Comment by JapanYoshi** [comment]
May I also suggest [`key-plus`](https://materialdesignicons.com/icon/key-plus)
