### ISSUE TITLE
Google Fire & Fire Alert

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5405]
Google has an updated fire icon called [local-fire-department](https://material.io/resources/icons/?search=fire&icon=local_fire_department&style=baseline). Should we update our [fire](https://materialdesignicons.com/icon/fire) icon to match theirs?

Our current fire icon has a strange artifact on the right side. Google's new fire icon has strange things going on with uneven bezier curves. I wouldn't mind creating a new icon without quirks.

![local-fire-department](https://user-images.githubusercontent.com/1837101/89356133-462e1200-d67a-11ea-82cb-799c8e50f062.png)

![local-fire-department-overlay](https://user-images.githubusercontent.com/1837101/89356181-6362e080-d67a-11ea-93b3-9eab2716a153.png)

I included an alert variant to both versions depending on which one we pick.

![fire-alert-mdi](https://user-images.githubusercontent.com/1837101/89356636-880b8800-d67b-11ea-8a4a-3d1f7f0601e8.png)
![fire-alert-google](https://user-images.githubusercontent.com/1837101/89356634-880b8800-d67b-11ea-96a2-37977aa76d6d.png)

[fire-alert.zip](https://github.com/Templarian/MaterialDesign/files/5025344/fire-alert.zip)

**Comment by Templarian** [comment]
That looks like the "rounded" one. We should not update ours to match, but we can include the alert.

**Comment by goyney** [comment]
[![fire-alert](https://materialdesignicons.com/icon/fire-alert)](https://materialdesignicons.com/icon/fire-alert)
