### ISSUE TITLE
New / Updated Weather Icons

### ISSUE THREAD

**Issue by SaltySeaDog** [Templarian/MaterialDesign#541]
Hello,

I updated some of your weather icons to match the latest google spec. In particular in regards to rounded ends. I also added some new ones as well.

https://www.dropbox.com/sh/zzephzko5ibxahh/AACyE145kvU3qQhan90R1GGPa?dl=0

![weather_icons2](https://cloud.githubusercontent.com/assets/7164266/8912009/b62c42a6-3487-11e5-9548-f5d2901d9ea9.png)

**Comment by CoDEmanX** [comment]
You need to use the share feature to generate a proper Dropbox link, the one you posted will only work for you.

**Comment by SaltySeaDog** [comment]
Ahh opps, my mistake. 

https://www.dropbox.com/sh/zzephzko5ibxahh/AACyE145kvU3qQhan90R1GGPa?dl=0

**Comment by SaltySeaDog** [comment]
Added 3 new icons: tornado, blustery (the old windy with some flattening) and cold, which can also be used for  #500

**Comment by Templarian** [comment]
I'll get these imported this weekend.

Yea, making the weather ones I knew the rounded terminals were bad idea but felt they looked odd. Guess it's best to just follow the guidelines rather than detouring for a few specific icons.

**Comment by Templarian** [comment]
@SaltySeaDog The contributor system is currently down as it is being updated, but if you email (austin at templarian com) I can forward you the contributor getting started steps.

**Comment by CoDEmanX** [comment]
It looks a little weird indeed, especially haze... A rough look and feel.

I like the idea of tornado, but it's hardly recognizable at larger sizes. Maybe some of the lines could be connected by curves, similar to the curves seen in blustery? (U-turn)

The raindrops might be more legible at small sizes if the upper point was moved further up. It's hard to distinguish from hail otherwise.

**Comment by SaltySeaDog** [comment]
Haze is definitly my least favorite

**Comment by SaltySeaDog** [comment]
(Ooops really sorry, hit totally the wrong button).

Haze is the one I'm least proud off but its difficult to find any adjustments that really work. Its similar to the foggy one, in that its hard to convey a haze in a monochrome.

For the rain, I found that it I was fine with the light rain but really struggled to distinguish easily when it was the heavy rain icon.  I was thinking maybe something like this: 
![rain-alt](https://cloud.githubusercontent.com/assets/7164266/8971808/b959ae76-364b-11e5-8d43-a8fdab96fc3e.png)

**Comment by Templarian** [comment]
The haze one is nice, can't think of another way it would be represented. Filling in the cloud doesn't fit well with the others, so I think the way it is now is best.

**Comment by CoDEmanX** [comment]
Original haze + 2 variants (sun beams moved slightly up to improve separation of sun and haze, wider haze in the last):

![weather-haze5](https://cloud.githubusercontent.com/assets/1309249/8989676/f87aca3e-36ed-11e5-8395-0f11aa32becd.png) ![weather-haze](https://cloud.githubusercontent.com/assets/1309249/8989675/f87a5dc4-36ed-11e5-8ed0-76755612927b.png) ![weather-haze2](https://cloud.githubusercontent.com/assets/1309249/8989677/f87b2902-36ed-11e5-941f-b3d49512074e.png)

**Comment by Templarian** [comment]
The 3rd haze one is a subtle, but nice change. Can you link the SVG for that one.

i think the current rain icon is fine.

**Comment by CoDEmanX** [comment]
![weather-haze-2](https://cloud.githubusercontent.com/assets/1309249/9003831/c2a9e050-3771-11e5-9bab-369b864c7243.png) A) 3rd from above
![weather-haze-7](https://cloud.githubusercontent.com/assets/1309249/9003832/c2cf2748-3771-11e5-8d41-8f043c236a85.png) B) with sun beam strokes in original position (margin only ~1.5px between beams and haze)
![weather-haze-6](https://cloud.githubusercontent.com/assets/1309249/9003833/c2cfc9be-3771-11e5-8dfe-3649c341ccd8.png) C) just to see how it would look with Templarian's beams

A) https://www.dropbox.com/s/h0g9sgckh81xnst/weather-haze-2.svg?dl=0
B) https://www.dropbox.com/s/1zuegz8p7l4qgn5/weather-haze-7.svg?dl=0

We shouldn't forget about the sunset icons by the way!
![weather-sunset](https://cloud.githubusercontent.com/assets/1309249/9004172/1fee3cf0-3774-11e5-939a-9a2cb00fa97b.png) 1px border margin
https://www.dropbox.com/s/s62q7pub6ce769p/weather-sunset.svg?dl=0
![weather-sunset2](https://cloud.githubusercontent.com/assets/1309249/9004171/1feb9428-3774-11e5-9ff6-4c43eebdc97d.png) Closer beams (2px border margin)
https://www.dropbox.com/s/zh4c50knbvbyw10/weather-sunset2.svg?dl=0
![weather-sunset3](https://cloud.githubusercontent.com/assets/1309249/9004256/b7f45e30-3774-11e5-9ef3-fb01444bc097.png) better distinction of beams and water reflections, but inconsistent with below up/down icons https://www.dropbox.com/s/3nn3itorasmmbu8/weather-sunset3.svg?dl=0

![weather-sunset-up](https://cloud.githubusercontent.com/assets/1309249/9004176/2302cbc2-3774-11e5-9f63-c357c73e723b.png) https://www.dropbox.com/s/lxr3xy2qknx2fuy/weather-sunset-up.svg?dl=0
![weather-sunset-down](https://cloud.githubusercontent.com/assets/1309249/9004175/2302ca96-3774-11e5-9ef0-8e9bd25629a7.png) https://www.dropbox.com/s/ysm1jskyf0tdmiv/weather-sunset-down.svg?dl=0
The chevrons seem a bit blurry, maybe there's a better way to do them (i.e. less on pixel). The beams could be moved outwards, like in 1st weather-sunset icon above...

**Comment by SaltySeaDog** [comment]
The first haze is definitely better.

How does that sunset look with filled in sun by the way?

**Comment by CoDEmanX** [comment]
Good point:

![weather-sunset-filled](https://cloud.githubusercontent.com/assets/1309249/9089513/c5193fb6-3b95-11e5-8ea5-c8fb8e32517c.png)
![weather-sunset2-filled](https://cloud.githubusercontent.com/assets/1309249/9089580/20d84e78-3b96-11e5-95a9-978bdbaa5f8c.png)
![weather-sunset-down-filled](https://cloud.githubusercontent.com/assets/1309249/9089515/c5207344-3b95-11e5-992c-44affa9c40c3.png)
![weather-sunset-up-filled](https://cloud.githubusercontent.com/assets/1309249/9089514/c52040ae-3b95-11e5-857d-5100457f1ee9.png)

**Comment by SaltySeaDog** [comment]
I don't know about you but the alignment rays seem a little odd to me. the horizontal rays seem to not in the middle.

**Comment by CoDEmanX** [comment]
Yeah I had to move them and tried to keep them on a virtual circle line, but it may look unbalanced after all. Do you want to fine tune them?

**Comment by SaltySeaDog** [comment]
![weather-sunrise](https://cloud.githubusercontent.com/assets/7164266/9239792/e79aa41e-4156-11e5-83e6-be872bae2817.png)
![weather-sunset](https://cloud.githubusercontent.com/assets/7164266/9239793/e7c9058e-4156-11e5-86d1-22c86a21684c.png)
![weather-sunset-alt](https://cloud.githubusercontent.com/assets/7164266/9239794/e7d5ea4c-4156-11e5-910e-0917f8d446f8.png)

It was a lot harder to do that than I expected

**Comment by CoDEmanX** [comment]
Looks good to me! 3 beams are plenty enough.

I tried to do a snow flake btw: https://github.com/Templarian/MaterialDesign/issues/500#issuecomment-128020466

The exclamation mark is optional, I couldn't make it work at 20x20px though.

**Comment by CoDEmanX** [comment]
Oh, and maybe you could try 3 beams on the haze icon too? Or at least check if the 5 strokes are well-aligned, because I moved them.

**Comment by CoDEmanX** [comment]
@SaltySeaDog Do you happen to have the source files still around and can share them?

**Comment by goyney** [comment]
Removing the Contribution label since the original source files were not provided for us to include.

**Comment by goyney** [comment]
After an internal discussion, we've decided we're happy with the current style of the weather icons. That being said, any new additions from your list of contributions should aim to follow the style (for example, the sun rays).

Out of the original posting, the following icons were provided:
- [x] `weather-blustery` - Already included as `weather-windy`
- [x] `weather-cloudy` - Already included as `weather-cloudy`
- [ ] `weather-cold` - Already included as `snowflake`, but could be a snowflake variation
- [x] `weather-fog` - Already included as `weather-fog`
- [x] `weather-hail` - Already included as `weather-hail`
- [ ] `weather-haze`
- [ ] `weather-hot`
- [x] `weather-night` - Already included as `weather-night`
- [ ] `weather-overcast` - Is a filled version of `weather-cloudy`
- [ ] `weather-partial-night`
- [x] `weather-partial` - Already included as `weather-partlycloudy`
- [x] `weather-rain-light` - Already included as `weather-rainy`
- [x] `weather-rain` - Already included as `weather-pouring`
- [ ] `weather-severe-storm`
- [x] `weather-showers` - Already included as `weather-pouring`
- [x] `weather-snow` - Already included as `weather-snowy`
- [x] `weather-storm` - Already included as `weather-lightning`
- [x] `weather-sunny` - Already included as `weather-sunny` 
- [x] `weather-sunrise` - Already included as `weather-sunset-up`
- [x] `weather-sunset-alt` - Already included as `weather-sunset-down`
- [x] `weather-sunset` - Already included as `weather-sunset`
- [ ] `weather-tornado`
- [x] `weather-windy` - Already included as `weather-windy`

---

That leaves this issue wanting to add the following icons to the library:
- `snowflake-variation`
- `weather-haze`
- `weather-hot`
- `weather-cloudy`
  - Rename the current `weather-cloudy` to `weather-cloudy-outline`
- `weather-cloudy-alert`
- `weather-night-partlycloudy`
- `weather-tornado`

**Comment by goyney** [comment]
Now that we've inventoried this issue, we've created and combined it with another master weather-related issue since there were two very large issues regarding weather icons. We'll track the work of the addition of the additional 6 icons from this issue there. Please follow that issue to keep up-to-date with the progress. Thank you for your contribution.
