### ISSUE TITLE
Lamp Post

### ISSUE THREAD

**Issue by itsadamslife** [Templarian/MaterialDesign#5412]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Yard lamp post. Similar to the coach-lamp icon but with the light on a post rather than "wall mounted".

## Examples

Include any example images so we know what the icon should look like.

![image](https://user-images.githubusercontent.com/36297955/89735963-12fdd100-da34-11ea-8637-f7eabbc7f092.png)

![image](https://user-images.githubusercontent.com/36297955/89735965-18f3b200-da34-11ea-8d05-7c5a3826bb2a.png)

**Comment by williamobrien** [comment]
I was looking for this icon too so I took a crack at it - thoughts?

![lamp-post](https://user-images.githubusercontent.com/6143684/103559920-f0f26880-4e84-11eb-96c5-5dd00931dfab.png)
![lamp-post-invert](https://user-images.githubusercontent.com/6143684/103560009-0ff0fa80-4e85-11eb-81df-e6df25d3305a.png)

**Comment by itsadamslife** [comment]
That icon would work.

**Comment by williamobrien** [comment]
What would need to get done for this to get moved on to the next step for approval?

**Comment by bwarman** [comment]
Love for this to be added. Possibly just the coach-lamp icon without the side mount. Issue #6063 had some interesting variants that weren't too tall for a UI also.

**Comment by giwleb** [comment]
I love this idea. I might suggest a varient too with a cross-piece common on many light post designs (not a great edit of the one above):
![103559920-f0f26880-4e84-11eb-96c5-5dd00931dfab](https://user-images.githubusercontent.com/28053992/147841709-ed7918b3-9ede-4e8b-a1b1-439c258af208.png)

**Comment by benjocaz45** [comment]
I came up with one myself, the same as @williamobrien just a little bit shorter. 
![image](https://user-images.githubusercontent.com/40012850/157956380-b62fb466-e749-403f-be4f-23b6b5873b7c.png)

How do I go about submitting this? Was going to use the submit a contribution form but then I saw that the first checkbox says to make sure nobody requested it, which clearly someone has done.

**Comment by bwarman** [comment]
Yeah, I went ahead and made my own as well and have just been using it programatically, since there were never any responses to the issue. Hopefully one will be added. I have no idea how you would submit.

**Comment by goyney** [comment]
[![post-lamp](https://materialdesignicons.com/icon/post-lamp)](https://materialdesignicons.com/icon/post-lamp)
