### ISSUE TITLE
account-hard-hat not working

### ISSUE THREAD

**Issue by khalid-imran** [Templarian/MaterialDesign#5413]

**Comment by Templarian** [comment]
@khalid-imran Need more details like what version are you using? But that icon has been around for many years at this point.

**Comment by khalid-imran** [comment]
im using  v3.9.96

**Comment by Templarian** [comment]
@khalid-imran I was thinking of `hard-hat`, `account-hard-hat` was added in `v5.0.45`.

https://dev.materialdesignicons.com/upgrade

**Comment by PeterShaggyNoble** [comment]
`account-hard-hat` was added in `v1.1.70` but, prior to `v5.0.45` was known as `worker`.

**Comment by Templarian** [comment]
Good catch @PeterShaggyNoble. This will be a lot more obvious on the new site since we'll be listing the audit log changes.
