### ISSUE TITLE
art_track

### ISSUE THREAD

**Issue by GrRivero** [Templarian/MaterialDesign#5414]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Represent placement of image and text in a form.

## Examples

https://material.io/resources/icons/?icon=art_track&style=baseline

**Comment by goyney** [comment]
Added as `image-text`.
