### ISSUE TITLE
Create an Icon for Notification plus

### ISSUE THREAD

**Issue by HassanMehmood1992** [Templarian/MaterialDesign#5417]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use to create notifications 

## Examples

Bell icon with plus inside

**Comment by goyney** [comment]
[![bell-plus](https://materialdesignicons.com/icon/bell-plus)](https://materialdesignicons.com/icon/bell-plus)[![bell-plus-outline](https://materialdesignicons.com/icon/bell-plus-outline)](https://materialdesignicons.com/icon/bell-plus-outline)

We recently updated these to use the standard cutout. We don't want the modifiers in middle of the icon unless there is a good reason/no other way to depict them.
