### ISSUE TITLE
Fast-forward/rewind 60 seconds 

### ISSUE THREAD

**Issue by agneevX** [Templarian/MaterialDesign#5418]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home Assistant media player - fast forward/rewind by 60 seconds

## Examples

Just a 6 instead of 3 in `mdi-fast-forward-30` or `mdi-rewind-30`.

**Comment by terreng** [comment]
<a href="https://github.com/terreng/samples/blob/master/fast-forward-60.svg"><img width="118" src="https://user-images.githubusercontent.com/11605395/90686357-10fbf500-e220-11ea-9f6c-a1e62e70bccb.png">
fast-forward-60.svg</a>
<br>
<a href="https://github.com/terreng/samples/blob/master/rewind-60.svg"><img width="118" src="https://user-images.githubusercontent.com/11605395/90686618-75b74f80-e220-11ea-8e3a-bfebc8e7fb8b.png">
rewind-60.svg</a>

**Comment by goyney** [comment]
Added.
