### ISSUE TITLE
Manjaro Linux

### ISSUE THREAD

**Issue by Speykious** [Templarian/MaterialDesign#5419]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue+is%3Aopen+manjaro) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same usage as any other operating system icon like Ubuntu or Windows.

## Examples

It's one of the easiest icons to make, proof in image!
![image](https://user-images.githubusercontent.com/13885008/89785037-0a7fc600-db1a-11ea-9f15-8c29aa8e848f.png)
![image](https://user-images.githubusercontent.com/13885008/89785136-31d69300-db1a-11ea-8449-0ee4dd60d25c.png)

**Comment by goyney** [comment]
I'll let @Templarian make the call on this one, but [this is available in SimpleIcons](https://simpleicons.org/?q=manjaro). I really don't think we should be adding any new brand icons at this point.

**Comment by Templarian** [comment]
Tech related so we're going to keep allowing all the Linux icons as long as they fit.

**Comment by goyney** [comment]
Added.
