### ISSUE TITLE
Icon Request: Signal

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#542]
See this:
http://fortawesome.github.io/Font-Awesome/icon/signal/

**Comment by CoDEmanX** [comment]
@Templarian: Do you mean this one?
http://www.google.com/design/icons/#ic_signal_cellular_4_bar

rpi-odoo's example shows a signal icon, but it's quite different. The official Google icon isn't very recognizable without particular context.

Could be used as icon for charts / metrics too:
![signal](https://cloud.githubusercontent.com/assets/1309249/8955983/d7bfb37e-35f1-11e5-9de2-817756b96d92.png) https://www.dropbox.com/s/a7bggs6osy9qh7k/signal.svg?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/signal
