### ISSUE TITLE
IEC_60309 plugs

### ISSUE THREAD

**Issue by remcotjeerdsma** [Templarian/MaterialDesign#5423]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There are icons for multiple EV-plug-types available, thanks to @goyney, but we are missing a few to make the set complete. These would be:
IEC_60309 Single phase
IEC_60309 Three phase 
IEC_62196_T3C
IEC_62196_T3A

## Examples

IEC_60309 Single phase (image left)
IEC_60309 Three phase (image right)
![image](https://user-images.githubusercontent.com/3865006/90125785-e4993200-dd62-11ea-8d64-ef7b46e8fdce.png)
IEC_62196_T3C
![image](https://user-images.githubusercontent.com/3865006/90125677-b61b5700-dd62-11ea-8aa0-046595024891.png)
IEC_62196_T3A 
![image](https://user-images.githubusercontent.com/3865006/90125650-aac82b80-dd62-11ea-802a-e8068c32b6b0.png)

**Comment by goyney** [comment]
The top two are not EV charging plugs; they're industrial plugs. They might be worth considering, but seem rather niche.

The bottom two plugs are deprecated connections only used in Europe. Consider they're deprecated, they are very niche.

While I appreciate the idea of completing a set, I don't know if these are worth adding at this time.
