### ISSUE TITLE
Fridge Open

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5424]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Here are "open" variants to both our current [fridge](https://materialdesignicons.com/icon/fridge) icons, and the proposed icons in #4974.

## Preview

![fridge-open](https://user-images.githubusercontent.com/1837101/90283087-c39d1380-de2c-11ea-866b-60bd786cef2b.png)
![fridge-top-open](https://user-images.githubusercontent.com/1837101/90283090-c39d1380-de2c-11ea-9660-f8dedbbdd304.png)
![fridge-bottom-open](https://user-images.githubusercontent.com/1837101/90283083-c26be680-de2c-11ea-841a-152d3ef2adb4.png)
![fridge-variant-open-left](https://user-images.githubusercontent.com/1837101/90283092-c435aa00-de2c-11ea-843a-664e633262c2.png)
![fridge-variant-open-right](https://user-images.githubusercontent.com/1837101/90283094-c435aa00-de2c-11ea-923c-8a17b0d63397.png)
![fridge-industrial-open](https://user-images.githubusercontent.com/1837101/90283085-c3047d00-de2c-11ea-98c4-d1bb9e6485d6.png)

## Zip Download

[fridge-open-icons.zip](https://github.com/Templarian/MaterialDesign/files/5076565/fridge-open-icons.zip)

**Comment by goyney** [comment]
Seems like we're missing some variants here. I'm guessing they don't work well with the outline versions, but then the side-by-side variant is outline. I think we need to do some more work here before these are ready.

**Comment by goyney** [comment]
As of right now, there doesn't seem to be much demand for these, so we're going to defer for now. If that changes, we can reopen and reevaluate these. Thanks for the work you put into them!
