### ISSUE TITLE
Using MDI inside a marker on Google maps API

### ISSUE THREAD

**Issue by cicarelli** [Templarian/MaterialDesign#5429]
Hi,
I'm trying to insert an icon inside a marker on a map created by Google maps API. I tried to use 
<pre>
label: { fontFamily: "Material Design Icons", text: "\uF0596" }
</pre>
but it didn't work. I'm not sure if the font name is correct and I tried some variants, without success. Could you please help me?

Thanks, and my apologies if this is not the correct forum to this kind of issue.

**Comment by JamesCoyle** [comment]
Take a look at the following:
https://developers.google.com/maps/documentation/javascript/symbols#add_to_marker

You can just use the @mdi/js package to import the required icon path.

**Comment by cicarelli** [comment]
Thank you, JamesCoyle! In fact, I'm using this Google documentation to create my markers, and it works. I'm using path to create customized markers.
My doubt is how could I put a mdi icon inside my markers, using label, like this:
https://jsfiddle.net/robsilva/hxt5jcu5/

**Comment by goyney** [comment]
You would need to install and use the [@mdi/js](https://www.npmjs.com/package/@mdi/js) package.

```js
import { mdiWeatherPouring } from '@mdi/js';

...

const marker = createMarker({
    ...
    icon: {
      path: mdiWeatherPouring
    }
};

**Comment by goyney** [comment]
@cicarelli Were you able to get this working?

**Comment by cicarelli** [comment]
Hi goyney... I wasn't. It works if I use an icon as a marker, but I didn't find the trick to use the icon as a label. So, I used another font (using unicode) to deliver the job, and I will work on it asap!
