### ISSUE TITLE
Icon Request: Account delete (account cross)

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#543]
Like this:
http://fortawesome.github.io/Font-Awesome/icon/user-times/

**Comment by CoDEmanX** [comment]
Is there a need for a distinct "x" user icon? There's already a "minus" version.

**Comment by rpi-odoo** [comment]
It would be nice if we have the one with 'x'.

**Comment by CoDEmanX** [comment]
It actually exists already:
https://materialdesignicons.com/icon/account-remove
