### ISSUE TITLE
Cart Check & Cart Variant

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5431]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Here's a cart icon with the check modifier. I also created a cart variant icon.

![cart-check](https://user-images.githubusercontent.com/1837101/90538985-80001d80-e13c-11ea-8edf-e396e2302ec1.png)
![cart-variant](https://user-images.githubusercontent.com/1837101/90538986-8098b400-e13c-11ea-84c2-d53d1a04acf7.png)

## Zip Download

[cart-icons.zip](https://github.com/Templarian/MaterialDesign/files/5091531/cart-icons.zip)

**Comment by goyney** [comment]
I'd like to see the variant's basket lines be aligned to the grid, but other than that 👍 .

**Comment by Xenomorph99** [comment]
In the previous cart-variant I posted, I'd aligned the vertical basket lines to the top of the basket's negative space so it would feel more balanced. If they line up with the grid they will be off center. Either option works for me.

![cart-variant](https://user-images.githubusercontent.com/1837101/90792680-0137eb80-e2c8-11ea-9936-d509021f88cb.png)

[cart-variant.zip](https://github.com/Templarian/MaterialDesign/files/5103984/cart-variant.zip)

**Comment by viktor-yakubiv** [comment]
@Xenomorph99 try using only 2 vertical lines so you can align it to the grid and balance visually in the same time.

**Comment by Xenomorph99** [comment]
Something like this? I used two vertical lines instead of three. The lines are aligned to the grid, but not the cart's inner white space. This works for me unless there's any objections.

![cart-variant](https://user-images.githubusercontent.com/1837101/91583930-1c7da900-e90f-11ea-9c2d-be70c80a9bf2.png)
[cart-variant.zip](https://github.com/Templarian/MaterialDesign/files/5142831/cart-variant.zip)

**Comment by viktor-yakubiv** [comment]
@Xenomorph99, it looks perfect to my eye!

@goyney what do you think?

**Comment by goyney** [comment]
Yes, that is exactly what I was thinking! Nice work.

**Comment by goyney** [comment]
Both added.
