### ISSUE TITLE
Map Marker Star / Map Marker Pit Stop (?)

### ISSUE THREAD

**Issue by baron159** [Templarian/MaterialDesign#5433]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

**Map Marker Star** -The marker can be used to show highlights or high-profile locations on maps and any other pin based UIs.
**Map Marker Pit Stop** -This marker can be used to show secondary waypoints along routes or other pin based UIs

## Examples

For the map marker star --- take the existing `map-marker' and replace the dot with a star.

for the map marker pit stop(?) ---  take the existing `map-marker' and replace the dot with a gas pump (?)

**Comment by goyney** [comment]
The star variants have been added. I'm not sure about the second request, a gas pump definitely won't fit inside the map marker.
