### ISSUE TITLE
Currency icons for Ukrainian hryvnia

### ISSUE THREAD

**Issue by GitVVV** [Templarian/MaterialDesign#5434]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon in this issue. 

## Usage

* It will be used to show the currency sign for money value in hryvnia.
* It's sign is: ₴.
* The code is: UAH
* [Wikipedia](https://en.wikipedia.org/wiki/Ukrainian_hryvnia)
* [Hryvnia sign](https://en.wikipedia.org/wiki/Hryvnia_sign)
* [Unicode Character](http://www.fileformat.info/info/unicode/char/20b4/index.htm)

## Examples

![1](https://camo.githubusercontent.com/96388bac39576ce8bef99e922a292aea0412e885/68747470733a2f2f706f6f686974616e2e636f6d2f73747566662f7561682f7561687369676e2e706e67)
![2](https://camo.githubusercontent.com/ad89d1367673c4db40b159e6b92157b146cb2ab5/68747470733a2f2f696d6167652e666c617469636f6e2e636f6d2f69636f6e732f7376672f36362f36363233302e737667)

**Comment by Templarian** [comment]
@MichaelGitArt added the high priority label so we can get this in before 6.0

**Comment by goyney** [comment]
[![currency-uah](https://materialdesignicons.com/icon/currency-uah)](https://materialdesignicons.com/icon/currency-uah)
