### ISSUE TITLE
Form Button icon

### ISSUE THREAD

**Issue by deniska-info** [Templarian/MaterialDesign#5436]
Hi!
There are icons for almost every form control: dropdown, input (text, password), select, checkbox, etc.
But I don't see a simple button icon.
Could you please add one or suggest what to use?
Thanks a lot for the great icons!
P.S. There is a "gesture-tap-button", but I think it will confuse users.

## Usage

Form builder tool.

## Examples
![button1](https://user-images.githubusercontent.com/9800889/90763364-3d327700-e2ef-11ea-9648-1586c08b754b.png)
![button2](https://user-images.githubusercontent.com/9800889/90763375-402d6780-e2ef-11ea-9a0d-0beb0ef40b05.png)

**Comment by goyney** [comment]
I would use `card(-outline)`. We can't include the word "button" for language conflict reasons.
