### ISSUE TITLE
TYPO3 icon

### ISSUE THREAD

**Issue by alexander-nitsche** [Templarian/MaterialDesign#5437]
Hey guys,

thanks for your great icon set maintenance!

I would like to push again the integration of the TYPO3 icon provided in these denied closed issues

https://github.com/Templarian/MaterialDesign/issues/3386
https://github.com/Templarian/MaterialDesign/issues/3428

TYPO3 is a Content Management System like Wordpress or Drupal, which both have icons integrated in your icon set.

The reason for rejection maybe is outdated as there seems to be still no brand icon set (cannot approve as the provided url http://dev.materialdesignicons.com/roadmap/brand-icons is outdated) and still a lot of brands are included in this Material Design icon set.

Thank you and greetings
Alex

**Comment by goyney** [comment]
I appreciate your dedication for trying to get this icon added, however we have rejected it twice. Brand Icons are deprecated as a whole and @Templarian has the final say as to what continues to be supported and what does not. We removed a ton of brand icons in the v5 release and are likely to remove more at v6.

Here is our official statement:

### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

---

Also, **please do not remove our issue template when requesting icons**. The reason for its existence is to prevent duplicate issues. I know you searched and wanted to push the issue even more, but honestly, with 2 already rejected issues for this icon, this issue shouldn't have even been opened.

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
