### ISSUE TITLE
account-tie-woman

### ISSUE THREAD

**Issue by nickarvanitas** [Templarian/MaterialDesign#5439]
I have:

- [ X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X] Searched open issues to make sure there isn't a request for this icon.
- [ X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![business-man-women](https://user-images.githubusercontent.com/46571851/90816621-d3fc3500-e2e9-11ea-9ca6-98ae99427cf1.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[business-man-woman.svg.zip](https://github.com/Templarian/MaterialDesign/files/5105095/business-man-woman.svg.zip)

**Comment by Simran-B** [comment]
Both man and woman in one icon is just not possible. We do have `account-tie` and could add a female version, though. Still quite a lot of details:

![image](https://user-images.githubusercontent.com/7819991/136055653-ee1cced3-62cd-4e8e-8644-1d0eae8a8ecd.png)

[account-tie-female.zip](https://github.com/Templarian/MaterialDesign/files/7287201/account-tie-female.zip)

**Comment by nickarvanitas** [comment]
I sent this last year haha. All good though! Too much detail. Thanks for
the response

**Comment by Simran-B** [comment]
It's a slightly tweaked version of your icon. The collar ends are moved down a little to make them more recognizable at native size. Also redid the shapes for cleaner paths. I tested different hair shapes but it hardly made a different at native size and looked odd zoomed in.

**Comment by goyney** [comment]
[![account-tie-woman](https://materialdesignicons.com/icon/account-tie-woman)](https://materialdesignicons.com/icon/account-tie-woman)
