### ISSUE TITLE
torch

### ISSUE THREAD

**Issue by julienreszka** [Templarian/MaterialDesign#5440]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

"passing the torch" 
https://www.dictionary.com/browse/pass-the-torch

## Examples

We could combine those two
https://petershaggynoble.github.io/MDI-Sandbox/?icon=fire
https://petershaggynoble.github.io/MDI-Sandbox/?icon=flashlight
to make something similar to this : https://thenounproject.com/search/?q=torch%20flame&i=2718853

**Comment by goyney** [comment]
[![torch](https://materialdesignicons.com/icon/torch)](https://materialdesignicons.com/icon/torch)
