### ISSUE TITLE
Card Minus

### ISSUE THREAD

**Issue by drasque** [Templarian/MaterialDesign#5441]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This is just an opposite to the `card-plus` and `card-plus-outline` icons.  Seems natural and intuitive there should be minus versions of these icons.

## Examples

Same as the `card-plus` and `card-plus-outline` icons but with a `minus` (-) instead of a `plus` (+)

**Comment by Xenomorph99** [comment]
I went ahead and created the minus, remove, and off variants for the [card](https://materialdesignicons.com/icon/card) and [card-outline](https://materialdesignicons.com/icon/card-outline) icons. Additionally, I updated the [card-plus-outline](https://materialdesignicons.com/icon/card-plus-outline) icon to match. The [card-plus](https://materialdesignicons.com/icon/card-plus) icon already matches, so doesn't need to be updated.

![card-minus](https://user-images.githubusercontent.com/1837101/91588292-2bfff080-e915-11ea-9fd1-15502efd78bb.png)
![card-minus-outline](https://user-images.githubusercontent.com/1837101/91588289-2b675a00-e915-11ea-971e-da8e975526a8.png)

![card-remove](https://user-images.githubusercontent.com/1837101/91588303-2dc9b400-e915-11ea-803e-d129afebe9f7.png)
![card-remove-outline](https://user-images.githubusercontent.com/1837101/91588300-2dc9b400-e915-11ea-90f3-0ca8d22919c1.png)

![card-off](https://user-images.githubusercontent.com/1837101/91588296-2d311d80-e915-11ea-8a76-8860059e326d.png)
![card-off-outline](https://user-images.githubusercontent.com/1837101/91588293-2c988700-e915-11ea-839a-cb33910e30d5.png)

![card-plus-outline](https://user-images.githubusercontent.com/1837101/91588298-2d311d80-e915-11ea-9b20-df598bcae1a2.png)

[card-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5143038/card-modifiers.zip)

**Comment by goyney** [comment]
There were all added, except `card-plus-outline` which already existed.

**Comment by drasque** [comment]
thx team!
