### ISSUE TITLE
French Fries Icon

### ISSUE THREAD

**Issue by mathritter** [Templarian/MaterialDesign#5448]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Restaurant apps, food delivery etc

## Examples
This is actually from FA, which, in this case, it's a paid icon. It would be cool to have something like this available.
![image](https://user-images.githubusercontent.com/6000689/91037319-2cc81800-e5df-11ea-9afe-28873db289dd.png)

**Comment by Xenomorph99** [comment]
Would something like this work?

We'll probably want to add these aliases:
- chips
- finger-chips
- french-fry
- fried-potatoes
- fries
- frites

![french-fries](https://user-images.githubusercontent.com/1837101/92143717-e2128100-edd2-11ea-8853-79475c60ff63.png)
![french-fries-outline](https://user-images.githubusercontent.com/1837101/92143711-e0e15400-edd2-11ea-8b1e-39749effd29f.png)

![french-fries-variant](https://user-images.githubusercontent.com/1837101/92143713-e2128100-edd2-11ea-88e3-fc2aafc3aaff.png)
![french-fries-variant-outline](https://user-images.githubusercontent.com/1837101/92143712-e179ea80-edd2-11ea-8fd6-205882033d0e.png)


[french-fries.zip](https://github.com/Templarian/MaterialDesign/files/5170034/french-fries.zip)

**Comment by mathritter** [comment]
Holy moly. it's perfect. It's even better than the FA ones. For me, those would fit perfectly.

**Comment by JapanYoshi** [comment]
I don't know, the line width is non-Material. I can tolerate the 1dp strokes on the fries themselves, but the rest should be at 2dp.

**Comment by Xenomorph99** [comment]
Sorry, I got carried away with the 1dp lines and forgot to switch the box to 2dp. I don't think I like this outline version though. I'd say lets just add the "french-fries" and "french-fries-variant" above to the library and not include these two outline versions.

![french-fries-outline](https://user-images.githubusercontent.com/1837101/92620543-fdbcd200-f27f-11ea-907a-6d180ca9fa55.png)
![french-fries-variant-outline](https://user-images.githubusercontent.com/1837101/92620549-fe556880-f27f-11ea-9a34-7f3e2567e072.png)

[french-fries-outline.zip](https://github.com/Templarian/MaterialDesign/files/5196272/french-fries-outline.zip)

**Comment by goyney** [comment]
[![french-fries](https://materialdesignicons.com/icon/french-fries)](https://materialdesignicons.com/icon/french-fries)
