### ISSUE TITLE
Tor / Onion Icon (new and old

### ISSUE THREAD

**Issue by MYDavoodeh** [Templarian/MaterialDesign#5449]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It could be used as an indicator in system tray that the Tor is enabled (that's how I use this package. In my DWM Window manager config)

## Examples

It's pretty obvious and iconic a google image search can show it.
It's basically a half-circle-full with extra echoing rings inside it.

Also the classic icon is simply just an onion.

### Extra note 

I found #71 but I couldn't find the implemented icon in the site! Idk what's up with that.

**Comment by goyney** [comment]
This icon was removed in v5 (https://github.com/Templarian/MaterialDesign/issues/4901) and won't be readded. The icon is available in SimpleIcons.

Here's our official statement on brand icons:

---

### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
