### ISSUE TITLE
Icon Request: Hand Pointing Left, down and up

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#545]
We have hand point right, Still we need hand pointing left , down and up direction

See this:
http://fortawesome.github.io/Font-Awesome/icon/hand-o-down/
http://fortawesome.github.io/Font-Awesome/icon/hand-o-left/
http://fortawesome.github.io/Font-Awesome/icon/hand-o-up/

**Comment by CoDEmanX** [comment]
@Templarian: Are separate icons really required for differently rotated symbols, or is there some trick to have the symbol once in the font + 3 aliases with transformation info? I know it's possible in CSS, but outside the browser?

**Comment by jeroendekorte** [comment]
Should work in CSS with transform. See: https://css-tricks.com/snippets/css/text-rotation/

**Comment by PeterShaggyNoble** [comment]
I was going to close this as this can be achieved with the `.mdi-rotate-[angle]` classes but, then, by that logic, we should only every need one of each type of arrow.

**Comment by PeterShaggyNoble** [comment]
Closing on favour of #3238 which includes contributions.
