### ISSUE TITLE
ice-cubes

### ISSUE THREAD

**Issue by ajmarks** [Templarian/MaterialDesign#5450]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm working on a Home Assistant  integration for GE kitchen appliance, which would include ice makers, both as their own appliance and as a part of a fridge/freezer.

**Comment by goyney** [comment]
This has this same issue as `sugar`: https://github.com/Templarian/MaterialDesign/issues/4954#issuecomment-620338633

I'm going to recommend `cube-outline`.

**Comment by ajmarks** [comment]
What about squares in a glass, along the lines of these?

![iced drink](https://cdn1.iconfinder.com/data/icons/coffee-71/64/Ice_coffee-128.png) 

![another glass of ice](https://cdn3.vectorstock.com/i/thumb-large/89/57/glass-of-whiskey-with-ice-icon-vector-10648957.jpg)

**Comment by Xenomorph99** [comment]
We have [delete-variant](https://materialdesignicons.com/icon/delete-variant) which is cup shape with cubes.

**Comment by ajmarks** [comment]
:+1:
