### ISSUE TITLE
Outline Navigation

### ISSUE THREAD

**Issue by fabiiomiiguel** [Templarian/MaterialDesign#5451]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
navigation
It will be nice having an outline navigation icon.

## Examples

![image](https://user-images.githubusercontent.com/27894544/91181538-f83c8500-e6e0-11ea-9963-da3077dccdb4.png)

**Comment by Xenomorph99** [comment]
Google has an outlined version of both [navigation](https://material.io/resources/icons/?search=nav&icon=navigation&style=outline) and [near-me](https://material.io/resources/icons/?search=nav&icon=near_me&style=outline) we could use.

**Comment by goyney** [comment]
Added `navigation-outline`. If you require the icon to be rotated like above, you'll need to facilitate that via your tooling.
