### ISSUE TITLE
File zip

### ISSUE THREAD

**Issue by Meller008** [Templarian/MaterialDesign#5453]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon for the file type.

## Examples

![](https://i.pinimg.com/originals/9b/24/5c/9b245ca3d8fc804e2be61926c5d7b129.png)

**Comment by goyney** [comment]
This is a duplicate of https://github.com/Templarian/MaterialDesign/issues/1288.

ZIP files (or archives) are not files. They are collection of files archived, so we have stayed away from creating a singular file version of this.

I recommend you use `zip-box`.

**Comment by Meller008** [comment]
Thanks. I understand your position. I'm using a zip-box now. But it differs in style.
