### ISSUE TITLE
file-school, file-school-outline

### ISSUE THREAD

**Issue by viktor-yakubiv** [Templarian/MaterialDesign#5454]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![file-shcool](https://user-images.githubusercontent.com/8440244/91416688-6d7e9600-e858-11ea-98ab-fe7e34755d6b.png)

![file-shcool-outline](https://user-images.githubusercontent.com/8440244/91417456-7fad0400-e859-11ea-93c0-bfe8e574e757.png)

## Zip Download

[file-school.zip](https://github.com/Templarian/MaterialDesign/files/5135136/file-school.zip)

## Usage

I used the icon to identify type of the file. There are file icons for a picture and text. We needed a one to identify (bachelor/master/PhD) 'thesis' but this can be also used for any academic work like laboratory work, study, learning materials etc.

## Comments

Icons are based on the already existing file and school icons in the library but the inner school pictures are redrawn to follow material guidelines.

**Comment by viktor-yakubiv** [comment]
I saw that in the icon request has the 'Usage' section which may be useful here too. I added it to my initial comment. Consider including the section into the issue template.

**Comment by goyney** [comment]
This is way too niche. We're gonna pass on adding it for now. Thank you for your suggestion.
