### ISSUE TITLE
Update in font breaks my design

### ISSUE THREAD

**Issue by dennisvanlith** [Templarian/MaterialDesign#5457]
Hi All,

I'm using the MaterialDesign font for a couple of projects in Adobe XD. But a weird thing happens every time I update the font to a newer version. After updating all my text in my designs that used the font break. Meaning I only get a placeholder icon where this font was used. 

I was trying to get back to an older version of the font (5.1.45) But the repository doesn't allow me to download any older versions.

My main questions are:

1. Could someone export that older version, or send me to a link where I can find the older version (5.1.45). So I can get back on track with my design.

2. Could someone investigate the issue with a design tool like Adobe XD. I think it has to do with the version numbering within the font. But I'm not sure.

Kind regards,
Dennis

**Comment by dennisvanlith** [comment]
Maybe one solution is to have all version of the repository browsable and downloadable on Github.

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign-Font We only support a font v5+

- There is actually a copy/paste feature in ^ for SVG that works great in Adobe XD, it includes a 24x24 grouped transparent box so you can better align the icons also. The new website has a similar feature when it launches.

If you were accidentally using Webfont, you can get any version via the version tag

- https://github.com/Templarian/MaterialDesign-Webfont/tree/v5.1.45
