### ISSUE TITLE
Document fragment / part

### ISSUE THREAD

**Issue by jacobq** [Templarian/MaterialDesign#5458]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like to indicate that some data (e.g. document or table) has been partitioned into pieces (e.g. for parallel processing). 
The problem with the `mdi-format-page-break` icon for this purpose is that it focuses on the location of the break rather than the notion of some of the document being unavailable. 

## Examples

Take an existing icon (e.g. `mdi-file-document-outline`) and make it shorter, replacing the bottom with a jagged / "zig-zag" line (indicating a rip or break). 
https://www.iconfinder.com/icons/1013961/clipboard_data_document_file_fragment_information_lost_icon
https://www.needpix.com/photo/941258/document-fragments-icon-documents-icon-document-icon-content

**Comment by goyney** [comment]
Seems like `receipt` would cover this use case. Will it?

[![receipt](https://materialdesignicons.com/icon/receipt)](https://materialdesignicons.com/icon/receipt

**Comment by jacobq** [comment]
> Seems like `receipt` would cover this use case. Will it?
> 
> [![receipt](https://camo.githubusercontent.com/eb73391d00eaef8b58ef73346cd613af65024cdf38711246e230a976f2a5f1d7/68747470733a2f2f6d6174657269616c64657369676e69636f6e732e636f6d2f69636f6e2f72656365697074)](https://materialdesignicons.com/icon/receipt)

I haven't been thinking about this for quite a while, and that's not quite was I had in mind. Nonetheless, it looks like it will work just fine for what I wanted. Thanks for the suggestion!
