### ISSUE TITLE
joomla

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#546]

**Comment by Templarian** [comment]
Drupal was closed by a contributor. Joomla is still not added.

[![drupal](https://materialdesignicons.com/icon/drupal)](https://materialdesignicons.com/icon/drupal)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
