### ISSUE TITLE
Glass-Mug-Off & Glass-Cocktail-Off

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5460]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Here's the "off" modifiers for [glass-mug](https://materialdesignicons.com/icon/glass-mug), [glass-mug-variant](https://materialdesignicons.com/icon/glass-mug-variant), and [glass-cocktail](https://materialdesignicons.com/icon/glass-cocktail)

"glass-mug-off" aliases:
alcohol-off, alcohol-prohibited, bar-closed, bar-off, cup-off, drink-off, local-bar-closed, local-bar-off, no-alcohol

"glass-mug-variant-off" aliases:
alcohol-off, alcohol-prohibited, bar-closed, bar-off, cup-off, drink-off, local-bar-closed, local-bar-off, no-alcohol

"glass-cocktail" aliases:
alcohol-off, alcohol-prohibited, bar-closed, bar-off, cup-off, drink-off, local-bar-closed, local-bar-off, martini-off, no-alcohol

## Preview

![glass-mug-off](https://user-images.githubusercontent.com/1837101/91597024-370d4d80-e922-11ea-847f-bcbe28c0d931.png)
![glass-mug-variant-off](https://user-images.githubusercontent.com/1837101/91597032-37a5e400-e922-11ea-9950-8d88c183f116.png)
![glass-cocktail-off](https://user-images.githubusercontent.com/1837101/91597015-3674b700-e922-11ea-9a38-20671b4a498c.png)

## Zip Download

[glass-off.zip](https://github.com/Templarian/MaterialDesign/files/5143397/glass-off.zip)

**Comment by goyney** [comment]
All added.
