### ISSUE TITLE
Unicycle

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5461]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

I created 3 unicycle options:

- **Option A** follows the 2dps standard.
- **Option B** uses 1.5dps lines that match our current [bicycle](https://materialdesignicons.com/icon/bicycle) icons.
- **Option C** also uses 1.5dps lines and is smaller to match the proportions of our current [bicycle](https://materialdesignicons.com/icon/bicycle) icons.

## Preview

![unicycle-a](https://user-images.githubusercontent.com/1837101/91619388-296bbe00-e94a-11ea-9b00-4a904fa79a10.png)
![unicycle-a-overlay](https://user-images.githubusercontent.com/1837101/91619387-28d32780-e94a-11ea-9075-4c0aaebf968e.png)

![unicycle-b](https://user-images.githubusercontent.com/1837101/91619391-2a045480-e94a-11ea-84b9-7ea41f67faf0.png)
![unicycle-b-overlay](https://user-images.githubusercontent.com/1837101/91619390-296bbe00-e94a-11ea-8eb3-b9fd5a1f8aad.png)

![unicycle-c](https://user-images.githubusercontent.com/1837101/91619394-2a9ceb00-e94a-11ea-984b-9a2e753b8f11.png)
![unicycle-c-overlay](https://user-images.githubusercontent.com/1837101/91619392-2a045480-e94a-11ea-8650-ba905ec5242d.png)

## Zip Download

[unicycle.zip](https://github.com/Templarian/MaterialDesign/files/5144356/unicycle.zip)

**Comment by MrGrigri** [comment]
I believe 'A' is the best option.

**Comment by goyney** [comment]
[![unicycle](https://materialdesignicons.com/icon/unicycle)](https://materialdesignicons.com/icon/unicycle)
