### ISSUE TITLE
Bicycle Antique

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5462]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

I created two options to represent an antique bicycle:

- **Option A** uses 2dps lines matching Material guidelines, but stretches beyond the 20dps width requirements.
- **Option B** uses 1.5dps lines matching our current [bicycle](https://materialdesignicons.com/icon/bicycle) icons, but conforms to the 20dps width requirement.

## Preview

![bicycle-antique-a](https://user-images.githubusercontent.com/1837101/91619847-84ea7b80-e94b-11ea-9a73-32388e953cbe.png)
![bicycle-antique-b](https://user-images.githubusercontent.com/1837101/91619849-85831200-e94b-11ea-982b-a114dd475c16.png)

## Zip Download

[bicycle-antique.zip](https://github.com/Templarian/MaterialDesign/files/5144377/bicycle-antique.zip)

**Comment by MrGrigri** [comment]
This is called a Penny-Farthing. We'll need to either have the name be `bicycle-penny-farthing` or `bicycle-vintage` with `penny-farthing` as an alias.

**Comment by MrGrigri** [comment]
And 'A' is probably the better option.

**Comment by goyney** [comment]
Added the A variant.
