### ISSUE TITLE
Share icon (ios variant)

### ISSUE THREAD

**Issue by reswitchtech** [Templarian/MaterialDesign#5464]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
This is the share icon that is visible on the Safari browser

## Examples
![ios_share_icon](https://user-images.githubusercontent.com/66621351/91634103-6ba90400-ea0b-11ea-9e32-74933c94d07a.png)

**Comment by JapanYoshi** [comment]
Looks like `logout-variant` rotated

**Comment by reswitchtech** [comment]
Ah, thanks a lot! I will open an alias issue for it.
