### ISSUE TITLE
Tune-Plus

### ISSUE THREAD

**Issue by BartEngram** [Templarian/MaterialDesign#5467]
[done] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
[done] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
[done] Only requested a single icon (or a few near-identical ones) in this issue. 

Currently there is an icon available called Tune. Google itself uses it to open or close a backdrop. 
To add items to the backdrop I look for an icon. Therefor I was thinking of the Tune icon with a "+"
Nevertheless it seems a bit challenging to make this look good.

Who can help?

For reference, the backdrop by Google: https://material.io/components/backdrop/

Thanks in advance!

**Comment by goyney** [comment]
Adding `plus` or worse, `minus`, just doesn't work with this icon. Thanks for the suggestion.
