### ISSUE TITLE
Comment Minus & Off Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5468]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Looks like the "minus" modifier is missing for [comment](https://materialdesignicons.com/icon/comment) and [comment-outline](https://materialdesignicons.com/icon/comment-outline).

We should add "comments-disabled" or "commenting-disabled" as an alias to the off modifier.

## Preview

![comment-minus](https://user-images.githubusercontent.com/1837101/91899456-6988b480-ec5a-11ea-8b6c-d0393e847a5b.png)
![comment-minus-outline](https://user-images.githubusercontent.com/1837101/91899454-6988b480-ec5a-11ea-97fa-bdf491190ee0.png)

![comment-off](https://user-images.githubusercontent.com/1837101/91900166-81146d00-ec5b-11ea-97a3-104290cf1a12.png)
![comment-off-outline](https://user-images.githubusercontent.com/1837101/91900164-807bd680-ec5b-11ea-8c1d-78ee7aef9564.png)

## Zip Download

[comment-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5158514/comment-modifiers.zip)

**Comment by goyney** [comment]
All added.
