### ISSUE TITLE
Rust programming language

### ISSUE THREAD

**Issue by ronlut** [Templarian/MaterialDesign#5469]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Rust programming language logo, to join the `language-x` icons family 🙂 
It's a 

> technology-related logo icon based around development

as stated [here](http://dev.materialdesignicons.com/roadmap/brand-icons).

## Examples

https://www.rust-lang.org/policies/media-guide
https://simpleicons.org/icons/rust.svg

Thanks!

**Comment by goyney** [comment]
Added.
