### ISSUE TITLE
Dialog icons

### ISSUE THREAD

**Issue by RueDeRennes** [Templarian/MaterialDesign#547]
- Dialog Close icon
- Dialog Maximize icon
- Dialog Minimize icon
- Dialog Restore icon

**Comment by CoDEmanX** [comment]
Is there any difference between windows and dialogues?
https://materialdesignicons.com/icon/close
https://materialdesignicons.com/icon/window-maximize
https://materialdesignicons.com/icon/window-minimize maybe move the line further down?
https://materialdesignicons.com/icon/window-restore

**Comment by Templarian** [comment]
Closing this issue as I think it's complete and there hasn't been feedback.

**Comment by CoDEmanX** [comment]
What about

>
https://materialdesignicons.com/icon/window-minimize maybe move the line further down?
