### ISSUE TITLE
Eye Remove

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5470]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

I didn't see the remove modifier for [eye](https://materialdesignicons.com/icon/eye) and [eye-outline](https://materialdesignicons.com/icon/eye-outline) so I created one.

## Preview

![eye-remove](https://user-images.githubusercontent.com/1837101/92017194-a2836080-ed10-11ea-8f71-5d9bb4bfdb4d.png)
![eye-remove-outline](https://user-images.githubusercontent.com/1837101/92017191-a1eaca00-ed10-11ea-9a91-e724280c7832.png)

## Zip Download

[eye-remove-modifier.zip](https://github.com/Templarian/MaterialDesign/files/5163870/eye-remove-modifier.zip)

**Comment by goyney** [comment]
Both added.
