### ISSUE TITLE
SUV vehicle

### ISSUE THREAD

**Issue by artcad** [Templarian/MaterialDesign#5474]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/30954074/92093483-b17f1700-edd3-11ea-986e-3e983155bcc4.png)
![image](https://user-images.githubusercontent.com/30954074/92093530-c065c980-edd3-11ea-8e01-0ebb44ea8b33.png)

## Zip Download

[SUV-icons.zip](https://github.com/Templarian/MaterialDesign/files/5167380/SUV-icons.zip)

**Comment by goyney** [comment]
We already have `car-estate`. Added `suv` and `sports-utility-vehicle` aliases to it.

[![car-estate](https://materialdesignicons.com/icon/car-estate)](https://materialdesignicons.com/icon/car-estate)
