### ISSUE TITLE
Bedroom/Basement/SharedRoom

### ISSUE THREAD

**Issue by sdemisse** [Templarian/MaterialDesign#5476]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The icon can be used to show types of areas in a  house, like a basement, bedroom, shared space. 

## Examples
Basement
![basement-icon](https://user-images.githubusercontent.com/23273033/92152174-4132be80-edf0-11ea-8e67-1223224b6f38.png)
Sharedroom
![images](https://user-images.githubusercontent.com/23273033/92152261-64f60480-edf0-11ea-980e-c94bdbdaec67.png)

**Comment by goyney** [comment]
We already have several bed icons and icons to indicate a basement (`home-floor-b`, `home-floor-negative-1`).
