### ISSUE TITLE
Herb (Plants/Nature) OR Mortar and Pestle

### ISSUE THREAD

**Issue by filcuk** [Templarian/MaterialDesign#5478]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Herbs, herbal medicine, gardening, culinary, cosmetics and more.

## Examples

<img src="https://www.clipartkey.com/mpngs/m/114-1147836_clip-art-herb-icon-herb-icon-png.png" width="100">

Edit: following too similar to `leaf` - disregard
<img src="https://cdn.onlinewebfonts.com/svg/img_483502.png" width="100">
<img src="https://image.flaticon.com/icons/svg/616/616742.svg" width="100">

**Comment by goyney** [comment]
Would `sprout(-outline)` or `leaf` work?

[![sprout](https://materialdesignicons.com/icon/sprout)](https://materialdesignicons.com/icon/sprout)[![sprout-outline](https://materialdesignicons.com/icon/sprout-outline)](https://materialdesignicons.com/icon/sprout-outline)
[![leaf](https://materialdesignicons.com/icon/leaf)](https://materialdesignicons.com/icon/leaf)

**Comment by filcuk** [comment]
I have overlooked `leaf` in the `Nature` tag - that works better than `sprout` I was using before, thank you.

`leaf` also looks similar to my other suggestions, which makes me think `mortar and pestle` would be the best unique icon in this regard.
<img src="https://static.thenounproject.com/png/3070597-200.png" width="100">

**Comment by MrGrigri** [comment]
I believe the `mortar-pestle` would work without the leaves (too much detail)

**Comment by goyney** [comment]
[![bowl-mix](https://materialdesignicons.com/icon/bowl-mix)](https://materialdesignicons.com/icon/bowl-mix)

This is similar enough to mortar and pestle that I don't think we need to really do anything here.

**Comment by Xenomorph99** [comment]
The [pharmacy](https://materialdesignicons.com/icon/pharmacy) icon is a mortar and pestle.

![pharmacy](https://user-images.githubusercontent.com/1837101/94730019-d22d8480-031f-11eb-8171-fda32ce81c5f.png)

Here's a version without the medical cross.

![mortar-pestle](https://user-images.githubusercontent.com/1837101/94730014-d0fc5780-031f-11eb-8068-5190705d255f.png)
[mortar-pestle.zip](https://github.com/Templarian/MaterialDesign/files/5307798/mortar-pestle.zip)

It probably makes sense to rename `pharmacy` to one of the following: `mortar-pestle-variant`, `mortar-pestle-plus`, or `mortar-pestle-cross`. That way it follows our literal naming convention.

**Comment by goyney** [comment]
We will rename `pharmacy` to `mortar-pestle-plus` and add a generic `mortar-pestle` in 6.0.

**Comment by goyney** [comment]
Renamed `pharmacy` and added the base `mortar-pestle`.
