### ISSUE TITLE
Icon Request: RSS Icon

### ISSUE THREAD

**Issue by simodorg** [Templarian/MaterialDesign#548]
Just like this: [FontAwesome RSS Icon](http://fortawesome.github.io/Font-Awesome/icon/rss/).
I think it is very frequent used in website development.

**Comment by CoDEmanX** [comment]
![rss](https://cloud.githubusercontent.com/assets/1309249/8955288/8e883fa6-35eb-11e5-8abd-c21b41bac807.png) https://www.dropbox.com/s/faqi9392g70l354/rss.svg?dl=0

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/rss There is this one.

**Comment by CoDEmanX** [comment]
Oh, missed it... proportions don't look quite right on it though...

**Comment by simodorg** [comment]
OK, I got it.
Thx a lot.

**Comment by CoDEmanX** [comment]
Google published an own RSS icon in their 2.2.0 update, which is quite a bit different from the updated RSS icon we have (Google = red):

![rss_mix](https://cloud.githubusercontent.com/assets/1309249/13063198/cfa7b7de-d445-11e5-8e14-834ec0b1a4fe.png)

**Comment by Templarian** [comment]
Yea, we should definitely be using the official icon for that then.

**Comment by Templarian** [comment]
Fixed and moved to Google.
