### ISSUE TITLE
Dolly person

### ISSUE THREAD

**Issue by dino-at-git** [Templarian/MaterialDesign#5481]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same as dolly icon (mdi-dolly) but with person delivering with dolly

## Examples

From FA

![image](https://user-images.githubusercontent.com/71004353/92571209-1d092e80-f283-11ea-8014-cbe681c3a4c3.png)
![image](https://user-images.githubusercontent.com/71004353/92571272-35794900-f283-11ea-8144-ea797e54a946.png)

**Comment by goyney** [comment]
What added meaning does the human add over just the simple `hand-truck` icon?

**Comment by dino-at-git** [comment]
![image](https://user-images.githubusercontent.com/71004353/95422598-e1c05500-093f-11eb-8226-64e2d2caf8d9.png)

Here is example. First step is pickup, second step is transporting, third step is delivering, final step is delivered.

**Comment by goyney** [comment]
Thoughts on this?

![image](https://user-images.githubusercontent.com/1015040/134253790-9834fbb1-2c66-46dc-b0a7-89f689d0494d.png)
[human-dolly.svg.zip](https://github.com/Templarian/MaterialDesign/files/7206526/human-dolly.svg.zip)

**Comment by goyney** [comment]
[![human-dolly](https://materialdesignicons.com/icon/human-dolly)](https://materialdesignicons.com/icon/human-dolly)
