### ISSUE TITLE
Numeric Decimal Point

### ISSUE THREAD

**Issue by PolarLava** [Templarian/MaterialDesign#5482]
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In the context of building a calculator or TV remote, etc. interface, there's a need for a single decimal point icon in the numeric-box,  numeric-box-outline,  numeric-circle,  numeric-circle-outline, et. al. families.

## Examples

![numeric-decimal-box](https://user-images.githubusercontent.com/876041/92608515-7709f400-f283-11ea-99b1-603cb297faec.png)
![numeric-decimal-box-outline](https://user-images.githubusercontent.com/876041/92608516-7709f400-f283-11ea-89d8-02d6ff3a1e72.png)

**Comment by goyney** [comment]
`circle-box` and `circle-box-outline` were added a few weeks ago and will go out in v5.6.

**Comment by PolarLava** [comment]
Nevermind, I've found the circle-box and circle-box-outline which is what I'm looking for.

**Comment by PolarLava** [comment]
@goyney thanks.  I missed your comment when I posted my reply that I had found the same.

**Comment by goyney** [comment]
No problem, I actually added them for another project sans-issue, which is why you probably couldn't find them. Glad they were useful to you!
