### ISSUE TITLE
snail

### ISSUE THREAD

**Issue by Ch-Lo** [Templarian/MaterialDesign#5485]
A snail icon was planned in #2103, but that issue was closed.

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As icon for low performance or delay in general.

## Examples

https://www.google.com/search?q=snail+icon&source=lnms&tbm=isch&sa=X&ved=2ahUKEwifk8iPgt7rAhVENOwKHeBzCGQQ_AUoAXoECAsQAw&biw=1920&bih=910

**Comment by Xenomorph99** [comment]
How about this?
![snail](https://user-images.githubusercontent.com/1837101/94048235-72b7fd80-fd90-11ea-968b-ad2e2f9f3b62.png)
[snail.zip](https://github.com/Templarian/MaterialDesign/files/5269892/snail.zip)

**Comment by goyney** [comment]
[![snail](https://materialdesignicons.com/icon/snail)](https://materialdesignicons.com/icon/snail)
