### ISSUE TITLE
paw-outline

### ISSUE THREAD

**Issue by BananaMasterz** [Templarian/MaterialDesign#5486]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Examples

Like the already existing paw icon but outlined.

**Comment by Xenomorph99** [comment]
I couldn't decide which direction to go so I created 3 options. I included the "off" variant as well.

**Option A:** The white space in the center of the toes feels awkward to me, but every shape is outlined equally
**Option B:** I changed the toe outline from "inside" to "center". While the toes are touching now, the icon is easy to read.
**Option C:** The sole is outlined, but the toes remain unchanged

![paw-outline-a](https://user-images.githubusercontent.com/1837101/94072245-8d9b6980-fdb2-11ea-95dc-a79f4210d7e2.png)
![paw-outline-b](https://user-images.githubusercontent.com/1837101/94072246-8d9b6980-fdb2-11ea-8a4d-e09b8584ee93.png)
![paw-outline-c](https://user-images.githubusercontent.com/1837101/94072248-8e340000-fdb2-11ea-90bf-9b4a49f37b0b.png)

![paw-off-outline-a](https://user-images.githubusercontent.com/1837101/94072241-8c6a3c80-fdb2-11ea-8715-33bc98a51b16.png)
![paw-off-outline-b](https://user-images.githubusercontent.com/1837101/94072243-8d02d300-fdb2-11ea-8192-e2d745cb3702.png)
![paw-off-outline-c](https://user-images.githubusercontent.com/1837101/94072244-8d9b6980-fdb2-11ea-9f00-a124654dbec9.png)

[paw-outline.zip](https://github.com/Templarian/MaterialDesign/files/5272041/paw-outline.zip)

**Comment by BananaMasterz** [comment]
Yes! Second one fits my other outlined icons perfectly.

**Comment by Templarian** [comment]
I think b works the best. @goyney input?

**Comment by goyney** [comment]
[![paw-off](https://materialdesignicons.com/icon/paw-off)](https://materialdesignicons.com/icon/paw-off)[![paw-off-outline](https://materialdesignicons.com/icon/paw-off-outline)](https://materialdesignicons.com/icon/paw-off-outline)
