### ISSUE TITLE
mdiCameraFlipis missing in 5.5.55

### ISSUE THREAD

**Issue by mseele** [Templarian/MaterialDesign#5487]
`import { mdiCameraFlip } from '@mdi/js';`
results in an error
`Module '"../../node_modules/@mdi/js/mdi"' has no exported member 'mdiCameraFlip'. Did you mean 'mdiCameraOff'`
using
`"@mdi/js": "5.5.55"`

**Comment by goyney** [comment]
https://github.com/Templarian/MaterialDesign/issues/5407

"Will Release in 5.6"
