### ISSUE TITLE
Can you add coronavirus icon please ?

### ISSUE THREAD

**Issue by poeteo** [Templarian/MaterialDesign#5491]
I have:

- [ X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I am writing a Flutter app and need to display coronavirus icon. 

material.io has released a set of icons related to corona virus and you have already added almost all of them. I can use all released ones through this library : https://pub.dev/packages/community_material_icon 

However, the actual coronavirus icon itself is missing. You have a generic virus icon, but it is a bad replacement. Can you add the coronavirus icon please ? 

## Examples

The icon exists on material.io and you can see it on this link :

https://material.io/resources/icons/?icon=coronavirus&style=baseline

**Comment by Simran-B** [comment]
There is already `virus` and `virus-outline`, therefore it's unclear whether this stock icon will be added.

**Comment by poeteo** [comment]
I can find a way to use that coronavirus icon in one way or another. But you definitely must add it. 

 

“Coronavirus” is not any regular virus anymore, it has already changed the world for worse. I don’t know about where you live, but the whole Western world has turned into a dystopic movie or TV series: the economy collapsed, fear is everywhere, everybody wears masks and governments impose restrictions upon restrictions in the name of battling coronavirus… and people have started to die like flies while official numbers are covered up of governments. 

 

Even if it involves a simple icon, dismissing the importance of coronavirus itself is an unfortunate decision. 

 

Best regards,

 

Eyup

**Comment by goyney** [comment]
We have virus and won't be adding the Google variant.
