### ISSUE TITLE
message-*-outline icons have inconsistent line width

### ISSUE THREAD

**Issue by daavko** [Templarian/MaterialDesign#5492]
In particular, in the lower left part where the bubble starts, the line going diagonally up and to the right is 2dp in some icons, not-2dp (looks like 1.5dp or maybe less) in other icons.

Here's exactly what I mean (the lower left part):
![image](https://user-images.githubusercontent.com/7669061/93336467-16049200-f828-11ea-9199-0b79429fea1d.png)

Icons with 2dp line width:

- `message-alert-outline`
- `message-flash-outline`
- `message-text-clock-outline`
- `message-text-lock-outline`
- `message-text-outline`

Icons with smaller line width:

- `message-arrow-left-outline`
- `message-arrow-right-outline`
- `message-bookmark-outline`
- `message-cog-outline`
- `message-image-outline`
- `message-lock-outline`
- `message-minus-outline`
- `message-outline`
- `message-plus-outline`
- `message-processing-outline`
- `message-settings-outline`

It looks like official Google icons on material.io are also inconsistent, as can be seen on [here](https://material.io/resources/icons/?search=message&style=outline).

**Comment by Templarian** [comment]
Good catch! We're releasing `5.6.55` tonight, but this will make it into the next release. Adding the milestone.

**Comment by goyney** [comment]
All fixed.
