### ISSUE TITLE
Railway carriage icon

### ISSUE THREAD

**Issue by macaronlover** [Templarian/MaterialDesign#5493]
I have:

- [x]  Searched all issues to make sure there isn't a request for this icon.
- [x]  Searched the current library to make sure the icon doesn't exist.
- [x]  Only requested a single icon (or a few near-identical ones) in this issue.

![Screenshot 2020-09-17 at 01 22 40](https://user-images.githubusercontent.com/12353505/93405345-a4a6fc80-f884-11ea-806f-e2db060ecbad.png)

**Comment by Templarian** [comment]
Nice example. It's funny, but the core team often shares images of icons we see in our various cities around the world. 👀 😃

**Comment by macaronlover** [comment]
Interesting. What do they think abut this idea?

**Comment by Templarian** [comment]
It's definitely an icon I could see added. Might need to iterate on something less of a box with wheels, but in context it should be fine.

**Comment by macaronlover** [comment]
Some windows + a doorway (pair or doors) should give clearer context but not too much detail as it should be legible at small sizes too

**Comment by Xenomorph99** [comment]
There's lots of types of train cars. If we're liking this style, I've got a ton I could render out.

<img width="1334" alt="train-cars" src="https://user-images.githubusercontent.com/1837101/94323963-e7d43000-ff54-11ea-9b1a-b56f0a05105a.png">

**Comment by macaronlover** [comment]
Image B is the most accurate or of all of them and more recognisable than
the others.

**Comment by Templarian** [comment]
D and G can be used for a subway/commuter train doors. And the open state.

**Comment by Xenomorph99** [comment]
![train-car-passenger](https://user-images.githubusercontent.com/1837101/94328069-dbf46800-ff6c-11ea-92b5-6c10245f4cd0.png)
![train-car-passenger-variant](https://user-images.githubusercontent.com/1837101/94328068-dbf46800-ff6c-11ea-8775-b08b8203f9ab.png)
![train-car-passenger-door](https://user-images.githubusercontent.com/1837101/94328067-db5bd180-ff6c-11ea-9e26-9ae1f5ee5f23.png)
![train-car-passenger-door-open](https://user-images.githubusercontent.com/1837101/94328066-dac33b00-ff6c-11ea-8667-7ef8a0a64c76.png)

[train-car-passenger.zip](https://github.com/Templarian/MaterialDesign/files/5286077/train-car-passenger.zip)

**Comment by macaronlover** [comment]
Do you know how often new icons are released to the website?

**Comment by Xenomorph99** [comment]
I just added them to the library - these ones will go out in the next release.
