### ISSUE TITLE
Heat/cool Icon

### ISSUE THREAD

**Issue by nekohuntr** [Templarian/MaterialDesign#5494]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There are icons for heating and cooling, but none that really cover both.  At the moment, I've seen some interfaces use a swirling arrows (like the "cached" icon) to handle this, but that doesn't do a good job of conveying it.  I suggest adding an icon that is split down the middle vertically, one half a snowflake and one half either a sun or a flame.  This will convey the meaning of both heating and cooling in one.

## Examples

Include any example images so we know what the icon should look like.
![unnamed](https://user-images.githubusercontent.com/27426759/93513734-47e32a80-f8f4-11ea-9697-f5275735da26.png)

**Comment by GreenTurtwig** [comment]
[![hot-cold](https://user-images.githubusercontent.com/15905797/97644217-ab0ec380-1a41-11eb-8a91-d56ff1262fff.png)](https://github.com/Templarian/MaterialDesign/files/5461937/hot-coldbest.zip)
Couldn't get any of our icons to work, so went with Google's.

**Comment by nekohuntr** [comment]
Looks good to me.  @Templarian is GreenTurtwig's icon suitable to be added?

**Comment by goyney** [comment]
[![sun-snowflake](https://materialdesignicons.com/icon/sun-snowflake)](https://materialdesignicons.com/icon/sun-snowflake)
