### ISSUE TITLE
Quantity icon

### ISSUE THREAD

**Issue by DanieliusAsm** [Templarian/MaterialDesign#5495]
I have:

* [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
* [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
* [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

An Icon to show quantity that could be used to show food quantity

![Image of icon](https://upload.wikimedia.org/wikipedia/commons/2/27/Simple_Measuring_Cup.jpg)

**Comment by goyney** [comment]
Would any of the `beaker` icons not suffice?

[![beaker](https://materialdesignicons.com/icon/beaker)](https://materialdesignicons.com/icon/beaker)

**Comment by DanieliusAsm** [comment]
Yes, actually it should work. Didnt even think of searching for that kind of word.
