### ISSUE TITLE
metadata icon

### ISSUE THREAD

**Issue by sukeshlaghate** [Templarian/MaterialDesign#5496]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Metadata summarizes basic information about data, making finding & working with particular instances of data easier.
Metadata is used in cataloging systems. Especially in GIS (Geographical Information Systems), Metadata is crucial source of information.

## Examples

Few ideas ( borrowed from internet )how meta-data icon can look like 
![metadata](https://user-images.githubusercontent.com/25061957/93572197-2006cc00-f9b3-11ea-8c5b-94ff9534e64b.png)
![metadata_3](https://user-images.githubusercontent.com/25061957/93572216-272dda00-f9b3-11ea-98a8-69eca24900ae.png)
![metadata_2](https://user-images.githubusercontent.com/25061957/93572230-2bf28e00-f9b3-11ea-88c3-a3746a9f49df.png)
![metadata_4](https://user-images.githubusercontent.com/25061957/93572243-314fd880-f9b3-11ea-9224-bec02e8d5bdb.png)

**Comment by JapanYoshi** [comment]
[`file-code`](https://materialdesignicons.com/icon/file-code) looks the most suitable, out of all the current `file` based icons. It might merit adding a `file-details` icon along the lines of `account-details`.

**Comment by goyney** [comment]
Yes, any of the `tag` icons or `file-code` handles this use case. We aren't going to add an icon with the word META on it, so at this point, I don't feel there is anything more to do in this issue. Thanks for the suggesiton.
