### ISSUE TITLE
Recessed Light Icon

### ISSUE THREAD

**Issue by rcblackwell** [Templarian/MaterialDesign#5497]
I have:

- [X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Associate with recessed lighting fixtures entities and objects used to control automated lighting systems.

## Examples
Please refer to;

![image](https://user-images.githubusercontent.com/70527431/93670911-b814bc00-fa6c-11ea-9b56-48411fb4b454.png)
 or
![image](https://user-images.githubusercontent.com/70527431/93670885-a3d0bf00-fa6c-11ea-9f37-82ba3e832e49.png)

The first icon would be prefered.

**Comment by goyney** [comment]
This is has been requested [many](https://github.com/Templarian/MaterialDesign/issues/1826), [many](https://github.com/Templarian/MaterialDesign/issues/5463), [many](https://github.com/Templarian/MaterialDesign/issues/5303), [many](https://github.com/Templarian/MaterialDesign/issues/4146), [many](https://github.com/Templarian/MaterialDesign/issues/3427) times.
