### ISSUE TITLE
AC Swing Modes Horizontal / Vertical

### ISSUE THREAD

**Issue by michelcve** [Templarian/MaterialDesign#5498]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

My airconditioner support setting both horizontal and vertical swing settings (5 steps each). I would like to represent the current swing mode for both using an icon.

## Examples

For vertical swing, the dot should be at the top left, with lines at 0, 22.5, 45, 67.5, 90 degrees coming from the dot.
For horizontal swing, the dot should be at the top, with lines at -45, -22.5, 0, 22.5, 45 degrees below the dot.

Active angle should be black, the other angles grayed.

For both there should be an 'Auto' variant (all angles black, and a small A in the bottom right corner perhaps)

There should also be a 'disabled' variant, in which all angles and the dot are grayed

**Comment by goyney** [comment]
This seems really niche. Can you provide some graphical examples of the controls, or other useful images, to help us understand?

**Comment by goyney** [comment]
Looks like another request was made with more details. I'm going to close this one, even though the request is older, in favor of #5653 because it contains more detail.
