### ISSUE TITLE
Piggybank Outline Icon

### ISSUE THREAD

**Issue by blude** [Templarian/MaterialDesign#5499]
A solid piggybank icon currently exists in the library so I've designed an outline version.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![piggybank-outline-preview](https://user-images.githubusercontent.com/616018/93714753-04432780-fb65-11ea-9e91-40eb84511eaf.png)

## Zip Download

[mdi-piggybank-outline.zip](https://github.com/Templarian/MaterialDesign/files/5251966/mdi-piggybank-outline.zip)

**Comment by goyney** [comment]
[![pig-variant-outline](https://materialdesignicons.com/icon/pig-variant-outline)](https://materialdesignicons.com/icon/pig-variant-outline)[![piggy-bank-outline](https://materialdesignicons.com/icon/piggy-bank-outline)](https://materialdesignicons.com/icon/piggy-bank-outline)
