### ISSUE TITLE
Icon Request: Issue Icon.

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#550]
Like we have issue icon in github.
See this : https://drive.google.com/file/d/0B2iROa1uo10vMHpaUm9HRDB0UTA/view?usp=sharing

**Comment by CoDEmanX** [comment]
Not in MDI yet, but will certainly be (#420):
http://www.google.com/design/icons/#ic_error_outline

Until then, you might wanna flip MDI's `information-outline`.
