### ISSUE TITLE
Standard ticket barrier icon

### ISSUE THREAD

**Issue by macaronlover** [Templarian/MaterialDesign#5501]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Examples

https://i.stack.imgur.com/xNY9B.jpg

**Comment by goyney** [comment]
We already have `turnstile`.

![image](https://user-images.githubusercontent.com/1015040/93771168-254e5b80-fbeb-11ea-92df-b13131b60d56.png)

**Comment by goyney** [comment]
Closing because `Needs More Info` was added quite a while ago without further clarification.
