### ISSUE TITLE
HACS

### ISSUE THREAD

**Issue by nunoladeiro** [Templarian/MaterialDesign#5503]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
I assume you're talking about the Home Assistant Community Store. This would be considered a brand icon and fall under our policy about new brand icons (we don't add them anymore). Considering HACS inside Home Assistant already supplies and provides their own icon, what is the benefit of us adding it? Please fill our the template to describe your usage.

**Comment by nunoladeiro** [comment]
Thanks,
Initially, the icon didn't install, so I try a workaround with MDI. Now is solved.
Thank you anyway!
Nuno

________________________________
De: Michael Irigoyen <notifications@github.com>
Enviado: 21 de setembro de 2020 15:33
Para: Templarian/MaterialDesign <MaterialDesign@noreply.github.com>
Cc: nunoladeiro <nuno_ladeiro@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [Templarian/MaterialDesign] HACS (#5503)


I assume you're talking about the Home Assistant Community Store. This would be considered a brand icon and fall under our policy about new brand icons (we don't add them anymore). Considering HACS inside Home Assistant already supplies and provides their own icon, what is the benefit of us adding it? Please fill our the template to describe your usage.
