### ISSUE TITLE
Truck cabin / Truck variant

### ISSUE THREAD

**Issue by LeLpiaDoSilvio** [Templarian/MaterialDesign#5504]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
The current truck icon shows both the cabin and trailer as one, however, I may reference they separeted E.g I need to register the Cabin and the Trailer (which has it's own icon already) individualy.

## Examples

![mdi-truck-variant-svg](https://user-images.githubusercontent.com/55469851/93807738-6d887080-fc21-11ea-9856-d6860af16d79.png)

**Comment by Templarian** [comment]
Surprised we don't have this one actually. Maybe this could be `empty`?

**Comment by Xenomorph99** [comment]
Perhaps we could call this `truck-flatbed`?

**Option A:** based on [dump-truck](https://materialdesignicons.com/icon/dump-truck) and centered.
**Option B:** based on [tow-truck](https://materialdesignicons.com/icon/tow-truck).

![truck-flatbed-a](https://user-images.githubusercontent.com/1837101/93948585-14413f80-fcfc-11ea-9884-2a2f8da102ba.png)
![truck-flatbed-b](https://user-images.githubusercontent.com/1837101/93948587-14d9d600-fcfc-11ea-8e7e-7e4acf1929cd.png)

[truck-flatbed.zip](https://github.com/Templarian/MaterialDesign/files/5264655/truck-flatbed.zip)

**Comment by goyney** [comment]
[![truck-flatbed](https://materialdesignicons.com/icon/truck-flatbed)](https://materialdesignicons.com/icon/truck-flatbed)
