### ISSUE TITLE
Ghost Outline

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5506]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Here's the outline versions of [ghost](https://materialdesignicons.com/icon/ghost) and [ghost-off](https://materialdesignicons.com/icon/ghost-off).

## Preview

![ghost-outline](https://user-images.githubusercontent.com/1837101/93946552-c7a73580-fcf6-11ea-97e0-3210650301e6.png)
![ghost-off-outline](https://user-images.githubusercontent.com/1837101/93946551-c70e9f00-fcf6-11ea-84f9-347e47698244.png)

## Zip Download

[ghost-outline.zip](https://github.com/Templarian/MaterialDesign/files/5264480/ghost-outline.zip)

**Comment by Templarian** [comment]
Added! 👻
