### ISSUE TITLE
Bank Check & Off Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5507]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![bank-check](https://user-images.githubusercontent.com/1837101/93947343-b2cba180-fcf8-11ea-8e10-92162fe7cc3d.png)
![bank-off](https://user-images.githubusercontent.com/1837101/93947347-b3643800-fcf8-11ea-90fc-46b9d55e5d85.png)
![bank-off-outline](https://user-images.githubusercontent.com/1837101/93947345-b3643800-fcf8-11ea-924c-70ed527bf20f.png)

## Zip Download

[bank-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5264540/bank-modifiers.zip)

**Comment by Templarian** [comment]
Added. 👍
