### ISSUE TITLE
Briefcase Off Modifier

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5508]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![briefcase-off](https://user-images.githubusercontent.com/1837101/93947923-45207500-fcfa-11ea-82f1-c9181b401537.png)
![briefcase-off-outline](https://user-images.githubusercontent.com/1837101/93947922-4487de80-fcfa-11ea-8f8e-ba22650cbb85.png)
![briefcase-variant-off](https://user-images.githubusercontent.com/1837101/93947927-45207500-fcfa-11ea-813c-f6287afe4e9a.png)
![briefcase-variant-off-outline](https://user-images.githubusercontent.com/1837101/93947925-45207500-fcfa-11ea-802c-88f76f471fdf.png)

## Zip Download

[briefcase-off.zip](https://github.com/Templarian/MaterialDesign/files/5264604/briefcase-off.zip)

**Comment by Templarian** [comment]
Added. 👍
