### ISSUE TITLE
Email Remove Modifier

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5509]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![email-remove](https://user-images.githubusercontent.com/1837101/93948202-017a3b00-fcfb-11ea-9aff-d36cf6b4ccf0.png)
![email-remove-outline](https://user-images.githubusercontent.com/1837101/93948201-00e1a480-fcfb-11ea-93a3-39c46ad3936c.png)

## Zip Download

[email-remove.zip](https://github.com/Templarian/MaterialDesign/files/5264636/email-remove.zip)

**Comment by Templarian** [comment]
Added. 👍
