### ISSUE TITLE
Message Off Modifier

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5510]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![message-off](https://user-images.githubusercontent.com/1837101/93949268-a9910380-fcfd-11ea-9a39-b2bf8ff6f889.png)
![message-off-outline](https://user-images.githubusercontent.com/1837101/93949266-a8f86d00-fcfd-11ea-89a2-bed1edf572c9.png)

## Zip Download

[message-off.zip](https://github.com/Templarian/MaterialDesign/files/5264685/message-off.zip)

**Comment by Templarian** [comment]
Added. 👍
