### ISSUE TITLE
regular lawnmower

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#5511]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
Need the icon for indicating the Gardentool shed. appreciate the robot-mower, but please consider adding a regular lawnmower too?
the robot-mower is kinda hard to discern, if one doesn't know a real life rebot-mower.... ;-)

## Examples

Include any example images so we know what the icon should look like.
<img width="318" alt="Schermafbeelding 2020-09-23 om 13 47 14" src="https://user-images.githubusercontent.com/33354141/94008434-51144180-fda3-11ea-8dea-0346609c35da.png">

or a 'bagged' variant

<img width="383" alt="Schermafbeelding 2020-09-23 om 13 47 48" src="https://user-images.githubusercontent.com/33354141/94008507-6ab58900-fda3-11ea-94a1-1514c9fde7f7.png">

thanks for considering
(did check the discussion for mower, and found a few threads, but no icon in the set, other than robot-mower? If I overlooked, my pardon)

**Comment by Xenomorph99** [comment]
How about this?

![mower](https://user-images.githubusercontent.com/1837101/94037085-3d0c1800-fd82-11ea-8e1c-5394f067828b.png)
![mower-variant](https://user-images.githubusercontent.com/1837101/94037079-3c738180-fd82-11ea-8d03-5636a7231ac1.png)

[mower.zip](https://github.com/Templarian/MaterialDesign/files/5269337/mower.zip)

**Comment by Templarian** [comment]
Added as `mower-bag`.

**Comment by Mariusthvdb** [comment]
Hey @Xenomorph99 

Since your top icon wasn't added here, (and I'd like to use it) please allow me to add it in my [Custom icon ](https://github.com/Mariusthvdb/Custom-icons)repo?

Ill credit completely ofc.
I will add a fill color so users with dark themes can easily see the icons.
Thanks!
