### ISSUE TITLE
mdi-battery-charging

### ISSUE THREAD

**Issue by Simsa** [Templarian/MaterialDesign#5512]
Hello,

I'm trying to animate battery charging and as i can see the icon mdi-battery-charging-40 is the same as mdi-battery-charging-50. They have the same SoC level. 

Not charging icon such as mdi-battery-40 and mdi-battery-50 looks as expected.

With the Best regards.

Martin

**Comment by Templarian** [comment]
Good catch! This is what happens when we're copying and pasting too much. Surprised no one has seen this until now. 🤦‍♂️
