### ISSUE TITLE
Lock Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5513]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

I created 3 of the missing lock modifiers: `lock-off`, `lock-minus`, and `lock-remove`.

![lock-off](https://user-images.githubusercontent.com/1837101/94040681-7777b400-fd86-11ea-9ca9-d92bdf8bb70e.png)
![lock-minus](https://user-images.githubusercontent.com/1837101/94040677-76df1d80-fd86-11ea-872f-033e41b016a2.png)
![lock-remove](https://user-images.githubusercontent.com/1837101/94040688-79417780-fd86-11ea-9a9d-8f1e0d43700c.png)

I also noticed that we were missing these outline versions: `lock-off-outline`, `lock-plus-outline`, `lock-minus-outline`, `lock-remove-outline`, `lock-check-outline`, and `lock-question-outline`.

![lock-off-outline](https://user-images.githubusercontent.com/1837101/94040678-7777b400-fd86-11ea-9812-c03cde3d5996.png)
![lock-plus-outline](https://user-images.githubusercontent.com/1837101/94040684-78a8e100-fd86-11ea-9c6c-54fdde0d5446.png)
![lock-minus-outline](https://user-images.githubusercontent.com/1837101/94040676-76df1d80-fd86-11ea-9f26-52fef7e464f1.png)
![lock-remove-outline](https://user-images.githubusercontent.com/1837101/94040687-79417780-fd86-11ea-9d55-2b2a380cb030.png)
![lock-check-outline](https://user-images.githubusercontent.com/1837101/94040674-76468700-fd86-11ea-922a-d8dfd38ddf4c.png)
![lock-question-outline](https://user-images.githubusercontent.com/1837101/94040685-78a8e100-fd86-11ea-83a3-d10d1ecb2c13.png)

It's probably unnecessary to build out a full set of modifiers for the "open" variants, but I could if anyone feels we need them. Since we already have [lock-open-check](https://materialdesignicons.com/icon/lock-open-check), I created a corresponding `lock-open-check-outline` variant.

![lock-open-check-outline](https://user-images.githubusercontent.com/1837101/94040683-78104a80-fd86-11ea-9b1b-5fa0e25e92ad.png)

Something else I noticed is that the loop at the top of [lock](https://materialdesignicons.com/icon/lock) is a different width compared to [lock-outline](https://materialdesignicons.com/icon/lock-outline). The modifiers I created are based on these two. I didn't change any widths.

## Zip Download

[lock-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5269540/lock-modifiers.zip)

**Comment by Templarian** [comment]
Wondering if we need to change the `plus` / `minus` / `remove` modifiers to be outside of the lock. The minus looks odd.

**Comment by Xenomorph99** [comment]
I think there's something nice about having the icon in the center of the lock shape, but our standard modifiers work nicely too. I rendered them all out so we could go either direction.

I didn't create `lock-open-off` or `lock-open-off-outline` because they looked the same as `lock-off` and `lock-off-outline`.

Also, I didn't create a new version of `lock-question`. Do we have a standardized "question" modifier? It seems to be all over the place.

![lock-off](https://user-images.githubusercontent.com/1837101/95104026-97966400-06f2-11eb-85ac-517ab769729f.png)
![lock-off-outline](https://user-images.githubusercontent.com/1837101/95104025-97966400-06f2-11eb-9fae-438ae4759292.png)

![lock-plus](https://user-images.githubusercontent.com/1837101/95104030-982efa80-06f2-11eb-83a5-88cdca9d67e6.png)
![lock-plus-outline](https://user-images.githubusercontent.com/1837101/95104028-982efa80-06f2-11eb-9791-98213ae434d6.png)

![lock-minus](https://user-images.githubusercontent.com/1837101/95104024-96fdcd80-06f2-11eb-8928-fc372a20eb52.png)
![lock-minus-outline](https://user-images.githubusercontent.com/1837101/95104023-96fdcd80-06f2-11eb-9c74-0fbf94f0e391.png)

![lock-check](https://user-images.githubusercontent.com/1837101/95104020-96653700-06f2-11eb-8f73-e264b147f3f2.png)
![lock-check-outline](https://user-images.githubusercontent.com/1837101/95104017-96653700-06f2-11eb-9798-096ec61c2cb4.png)

![lock-remove](https://user-images.githubusercontent.com/1837101/95104033-98c79100-06f2-11eb-8852-0d771a4e73c8.png)
![lock-remove-outline](https://user-images.githubusercontent.com/1837101/95104032-98c79100-06f2-11eb-8d8c-f44593a93932.png)

![lock-open-plus](https://user-images.githubusercontent.com/1837101/95104242-d62c1e80-06f2-11eb-981a-d625db73bbe7.png)
![lock-open-plus-outline](https://user-images.githubusercontent.com/1837101/95104239-d5938800-06f2-11eb-8e13-9d324e242b2d.png)

![lock-open-minus](https://user-images.githubusercontent.com/1837101/95104238-d4faf180-06f2-11eb-820b-4527c504e165.png)
![lock-open-minus-outline](https://user-images.githubusercontent.com/1837101/95104235-d4faf180-06f2-11eb-8276-942cae1b8f7a.png)

![lock-open-check](https://user-images.githubusercontent.com/1837101/95104233-d4625b00-06f2-11eb-9a4a-ac641eeb930e.png)
![lock-open-check-outline](https://user-images.githubusercontent.com/1837101/95104229-d4625b00-06f2-11eb-9c93-ea0137aa53f9.png)

![lock-open-remove](https://user-images.githubusercontent.com/1837101/95104248-d62c1e80-06f2-11eb-8cc9-aa16a457caa8.png)
![lock-open-remove-outline](https://user-images.githubusercontent.com/1837101/95104245-d62c1e80-06f2-11eb-8a80-f68ade9495ea.png)

[lock-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5328595/lock-modifiers.zip)

**Comment by Templarian** [comment]
Definitely like that more. Added the `lock-off` and `lock-off-outline`.

Waiting for some more feedback.

**Comment by Xenomorph99** [comment]
Added
