### ISSUE TITLE
Clipboard Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5514]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![clipboard-search](https://user-images.githubusercontent.com/1837101/94056126-1dcdb480-fd9b-11ea-975c-f66d756f5bff.png)
![clipboard-search-outline](https://user-images.githubusercontent.com/1837101/94056124-1d351e00-fd9b-11ea-920f-50dbb198d5b5.png)
![clipboard-text-search](https://user-images.githubusercontent.com/1837101/94056131-1e664b00-fd9b-11ea-98b5-9e8883c2bd54.png)
![clipboard-text-search-outline](https://user-images.githubusercontent.com/1837101/94056129-1dcdb480-fd9b-11ea-99b5-49cb444a7db0.png)

## Zip Download

[clipboard-search.zip](https://github.com/Templarian/MaterialDesign/files/5270420/clipboard-search.zip)

**Comment by Xenomorph99** [comment]
I realized we were more clipboard modifiers missing. I threw these together:



![clipboard-minus](https://user-images.githubusercontent.com/1837101/94223341-eea76800-feac-11ea-82a1-7d607a70057b.png)
![clipboard-minus-outline](https://user-images.githubusercontent.com/1837101/94223339-ee0ed180-feac-11ea-8c8e-f971c2892bc8.png)

![clipboard-remove](https://user-images.githubusercontent.com/1837101/94223348-f0712b80-feac-11ea-8f1c-0a9d1f66dbd4.png)
![clipboard-remove-outline](https://user-images.githubusercontent.com/1837101/94223347-efd89500-feac-11ea-88b5-550f86bd0504.png)

![clipboard-off](https://user-images.githubusercontent.com/1837101/94223345-efd89500-feac-11ea-8856-1942ca8fe392.png)
![clipboard-off-outline](https://user-images.githubusercontent.com/1837101/94223344-ef3ffe80-feac-11ea-8a28-0acc3a3daf26.png)

![clipboard-text-off](https://user-images.githubusercontent.com/1837101/94223350-f0712b80-feac-11ea-9849-9c313cde6d28.png)
![clipboard-text-off-outline](https://user-images.githubusercontent.com/1837101/94223349-f0712b80-feac-11ea-84bc-c05479b0bcd4.png)

[clipboard-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5280431/clipboard-modifiers.zip)

**Comment by Templarian** [comment]
All 12 were added. 👍
