### ISSUE TITLE
Note Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5515]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

I had to flip the search modifier to the left side otherwise it was cutting off the folded corner making it unreadable.

## Preview

![note-minus](https://user-images.githubusercontent.com/1837101/94057430-d811eb80-fd9c-11ea-8852-8832a1cf4a05.png)
![note-minus-outline](https://user-images.githubusercontent.com/1837101/94057427-d7795500-fd9c-11ea-8d88-38241389e616.png)

![note-remove](https://user-images.githubusercontent.com/1837101/94057435-d8aa8200-fd9c-11ea-8b60-7ce21eee6efc.png)
![note-remove-outline](https://user-images.githubusercontent.com/1837101/94057432-d8aa8200-fd9c-11ea-860c-6a07c7c3f60b.png)

![note-search](https://user-images.githubusercontent.com/1837101/94057439-d9431880-fd9c-11ea-9206-43b216da1544.png)
![note-search-outline](https://user-images.githubusercontent.com/1837101/94057437-d9431880-fd9c-11ea-9aa9-b3c98e0b7b39.png)

## Zip Download

[note-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5270517/note-modifiers.zip)

**Comment by Templarian** [comment]
Added. 👍
