### ISSUE TITLE
Gas detector

### ISSUE THREAD

**Issue by chemelli74** [Templarian/MaterialDesign#5516]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

IoT devices are everyday more present in our houses;
as a HomeAssistant contributor, I think a specific icon would be nice to have.

## Examples

Include any example images so we know what the icon should look like.

One idea for on/off:
![image](https://user-images.githubusercontent.com/57354320/94072521-1c7da580-fdf6-11ea-9125-fda066117de7.png)
![image](https://user-images.githubusercontent.com/57354320/94072535-256e7700-fdf6-11ea-9cea-3ccf0cfae9a5.png)

**Comment by Xenomorph99** [comment]
We already have [molecule-co](https://materialdesignicons.com/icon/molecule-co) and [molecule-co2](https://materialdesignicons.com/icon/molecule-co2). Would these sensor variants work?

![molecule-co-sensor](https://user-images.githubusercontent.com/1837101/94170339-2ed6fe00-fe4d-11ea-84f8-de9e08371fbe.png)
![molecule-co2-sensor](https://user-images.githubusercontent.com/1837101/94170342-2f6f9480-fe4d-11ea-9e5e-3215b323e244.png)

[molecule-sensor.zip](https://github.com/Templarian/MaterialDesign/files/5277490/molecule-sensor.zip)

**Comment by Xenomorph99** [comment]
We should probably include the "off" variants as well.

![molecule-co-sensor-off](https://user-images.githubusercontent.com/1837101/94171794-ed475280-fe4e-11ea-8936-3ee00cb4f03e.png)
![molecule-co2-sensor-off](https://user-images.githubusercontent.com/1837101/94171797-eddfe900-fe4e-11ea-9198-5b2c10f39ba9.png)

[molecule-sensor-off.zip](https://github.com/Templarian/MaterialDesign/files/5277577/molecule-sensor-off.zip)

**Comment by chemelli74** [comment]
LGTM !!!

**Comment by Templarian** [comment]
Off becomes un-readable, so lets leave those out for now.

**Comment by Xenomorph99** [comment]
Now that you mention it @Templarian, I agree that you can't read "CO" and "CO2" with the slash. Let's go ahead and add the sensor variants: `molecule-co-sensor` and `molecule-co2-sensor`.

@chemelli74, you might be able to distinguish between an "on" and "off" state in your project by changing color instead of changing the icon.

**Comment by chemelli74** [comment]
> @chemelli74, you might be able to distinguish between an "on" and "off" state in your project by changing color instead of changing the icon.

In HomeAssistant, for on/off sensors we need 2 icons; https://www.home-assistant.io/images/screenshots/binary_sensor_classes_icons.png

What if you use https://image.shutterstock.com/z/stock-vector-gas-sensor-icon-monochrome-style-design-from-sensors-collection-ux-and-ui-pixel-perfect-gas-1188262543.jpg ?

The word CO2 seems lower enough to be still readable in the off version.

Thx a lot for your work,

Simone

**Comment by Templarian** [comment]
A `cloud` + `sensor` might work. But we would have to leave out the text in that case.

**Comment by goyney** [comment]
Icons with text are special case icons. The original CO and CO2 icons were special cases added after much debate. These variant further complicate these. I do not think these should be added and believe we should reject this issue or come up with a less-literal variation that can solve the use case without the use of letters and numbers.

**Comment by chemelli74** [comment]
Then we can go with @Templarian suggestion

**Comment by temaprint** [comment]
hard to find a similar
but maybe these will help
https://icons8.com/icons/set/co2
<img src="https://img.icons8.com/wired/50/000000/co2.png"/><img src="https://img.icons8.com/nolan/50/co2.png"/><img src="https://img.icons8.com/dusk/50/000000/co2.png"/>

**Comment by chemelli74** [comment]
> A `cloud` + `sensor` might work. But we would have to leave out the text in that case.

I think this is the best solution.
Can you be so kind and proceed ? :-)

Simone

**Comment by chemelli74** [comment]
@Templarian, any chance to see this committed ? ;-)

Thx in advance,

Simone

**Comment by chemelli74** [comment]
Bump ;-)

**Comment by chemelli74** [comment]
Few more ideas:

![image](https://user-images.githubusercontent.com/57354320/111888667-e86af200-89de-11eb-8b8c-597ecdc178de.png)

![image](https://user-images.githubusercontent.com/57354320/111888660-dc7f3000-89de-11eb-8dcb-be7af437f32a.png)

![image](https://user-images.githubusercontent.com/57354320/111888686-1bad8100-89df-11eb-8ea2-9e68e0270463.png)

**Comment by chemelli74** [comment]
None of the proposal make sense ?

Thx in advance for the feedback,

Simone

**Comment by chemelli74** [comment]
@Xenomorph99, @Templarian, @temaprint, @goyney:  Should I look for some other sample or one of the proposal above can be accepted ?

Simone

**Comment by Templarian** [comment]
Gas burner icon is a good idea, but little different than the request. Definitely a good icon to have. With an `-off`

**Comment by chemelli74** [comment]
do you plan to add those ?

Simone

**Comment by chemelli74** [comment]
@Templarian, are you considering the addition of this 2 icons (on/off) to the package ?

Thx in advance for your feedback.

Simone

**Comment by chemelli74** [comment]
Any decision on those 2 icons ?

Simone

**Comment by goyney** [comment]
@chemelli74 We're all volunteers here. Constantly pinging an issue with nothing new isn't helpful, it's noise.

That being said, this issue is for an icon depicting a gas detector of which no suitable suggestions or contributions have yet been posted. The side conversation about a gas burner seems like something worthy to add but must be requested in a separate issue so it can be tracked appropriately.

**Comment by chemelli74** [comment]
First of all, let me thank you for taking the time to answering.

> @chemelli74 We're all volunteers here. 

I perfectly know what it means: I'm a volunteer in many projects 
since more than 15 years.

> Constantly pinging an issue with nothing new isn't helpful, it's noise.

I always though that any requester deserve an answer; Last update is from 3 months ago, didn't ping every day 😉


> That being said, this issue is for an icon depicting a gas detector of which no suitable suggestions or contributions have yet been posted. The side conversation about a gas burner seems like something worthy to add but must be requested in a separate issue so it can be tracked appropriately.

As you can easily see, finally got an answer!
Nobody wrote anything in this direction before 😊

Will close this issue and open a new one once back home and with a pc on my hands.

Regards,

Simone

**Comment by chemelli74** [comment]
> The side conversation about a gas burner seems like something worthy to add but must be requested in a separate issue so it can be tracked appropriately.

Closing, follow-up here: https://github.com/Templarian/MaterialDesign/issues/6153

Simone
