### ISSUE TITLE
calendar-start and calendar-end

### ISSUE THREAD

**Issue by pebs74** [Templarian/MaterialDesign#5518]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Similar to the clock-start and clock-end icons, the calendar-start and calendar-end icons would be used for "Start Date" and "End Date" input fields.

## Examples

I'm developping an app in which there is a search form for calls in a log. Two of the fields you can search by are "Call date after: <fromDate>" and "Call date before: <endDate>". I would like to give meaningfull icons to these fields, and I found the "clock-start" and "clock-end" which I like, but refer to times instead of dates.

The new icons should be very similar to the clock ones, but replacing the clock with a small calendar.

**Comment by pebs74** [comment]
Proposed icons attached:
[calendar-start-end.zip](https://github.com/Templarian/MaterialDesign/files/5274667/calendar-start-end.zip)

**Comment by Templarian** [comment]
This will need to be tweaks a bit, but the general idea is there. Maybe something closer to... ?

![image](https://user-images.githubusercontent.com/338885/95151379-29808a00-0750-11eb-9030-294625c60dd0.png) ![image](https://user-images.githubusercontent.com/338885/95151405-38673c80-0750-11eb-8f9f-c5383674b593.png)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/95151635-c511fa80-0750-11eb-9753-eab79ebe9e52.png)

Actually probably ^

**Comment by Templarian** [comment]
Added. 👍
