### ISSUE TITLE
mdi-minus-thick

### ISSUE THREAD

**Issue by salvatorepandolfi** [Templarian/MaterialDesign#5519]
We have the mdi-plus-thick but not the minus thick.
So this can't be used as a toogle icon for like a menu.

**Comment by Xenomorph99** [comment]
This should work
![minus-thick](https://user-images.githubusercontent.com/1837101/94163159-c126d400-fe44-11ea-8bc0-c4a0244ce3ab.png)
[minus-thick.zip](https://github.com/Templarian/MaterialDesign/files/5277064/minus-thick.zip)

**Comment by salvatorepandolfi** [comment]
@Xenomorph99 Thanks a lot!

**Comment by Templarian** [comment]
Added. 👍 

(Really some of your best design work @Xenomorph99 😉)
