### ISSUE TITLE
Icon Request: PaintCan (Paint Bucket)

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#552]
Example: https://octicons.github.com/icon/paintcan/

**Comment by CoDEmanX** [comment]
This is Google's color fill icon:
http://www.google.com/design/icons/#ic_format_color_fill

For symbolize colors or a color picker, use palette instead:
http://www.google.com/design/icons/#ic_palette

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/format-color-fill

This is already in the pack (it requires an overlap with [color-helper](https://materialdesignicons.com/icon/color-helper)).
