### ISSUE TITLE
mdiSquare

### ISSUE THREAD

**Issue by Valianton** [Templarian/MaterialDesign#5520]
Hi everyone.

MdiSquare svg shape missing 'z' to close path

**wrong**
`M3,3V21H21V3`

**right**
`M3,3V21H21V3Z`

**Comment by goyney** [comment]
The trailing `Z` or `z` is optional and is removed as part of our SVG optimizer. This is intentional and valid.

**Comment by Valianton** [comment]
I believe your  yours SVG optimizer make a mistake

[preview](https://ibb.co/mS7Kcws)

I use this shape in my application and I need the shape to have borders of any color, but I cannot do this, because yours SVG optimizer thinks that the symbol z is an optional parameter for closing the path. This is ridiculous

**Comment by Templarian** [comment]
@Valianton Stroke is not something we support at this time for any of the vector data. The icons are meant to be used with a single filled path.

**Comment by Valianton** [comment]
> @Valianton Stroke is not something we support at this time for any of the vector data. The icons are meant to be used with a single filled path.

As you say, only now I have to use a square shape from another library, eh =\
