### ISSUE TITLE
Credit Card (Refresh, Sync, Search)

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5522]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![credit-card-search](https://user-images.githubusercontent.com/1837101/94223996-907b8480-feae-11ea-8ac7-23dc316e18d7.png)
![credit-card-search-outline](https://user-images.githubusercontent.com/1837101/94223994-8fe2ee00-feae-11ea-99b0-d641335d4817.png)

![credit-card-refresh](https://user-images.githubusercontent.com/1837101/94223992-8fe2ee00-feae-11ea-9c92-8aeced439367.png)
![credit-card-refresh-outline](https://user-images.githubusercontent.com/1837101/94223990-8f4a5780-feae-11ea-9a3a-03453f30f277.png)

![credit-card-sync](https://user-images.githubusercontent.com/1837101/94223999-91141b00-feae-11ea-9aec-56ccd1dab21c.png)
![credit-card-sync-outline](https://user-images.githubusercontent.com/1837101/94223997-907b8480-feae-11ea-8ecf-907032c0fce8.png)

## Zip Download

[credit-card-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5280472/credit-card-modifiers.zip)

**Comment by Templarian** [comment]
@Xenomorph99 That is the wrong sync overlay.

**Comment by Xenomorph99** [comment]
Oops, good catch. I used the one I've got in the illustrator template. I'll update it. The thicker arrows like [folder-sync](https://materialdesignicons.com/icon/folder-sync) look way better.

![credit-card-sync](https://user-images.githubusercontent.com/1837101/94227638-2d8eeb00-feb8-11ea-87b9-31dd5f94465d.png)
![credit-card-sync-outline](https://user-images.githubusercontent.com/1837101/94227636-2cf65480-feb8-11ea-9265-9d450a93c0c5.png)

[credit-card-sync.zip](https://github.com/Templarian/MaterialDesign/files/5280653/credit-card-sync.zip)

**Comment by Templarian** [comment]
Added. 👍
