### ISSUE TITLE
hammer-sickle (Communism)

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5523]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

This symbol is generally used to represent "communism". It is also called the "Hammer and Sickle".

**Option A:** Vector shape found on [Wikipedia](https://commons.wikimedia.org/wiki/File:Hammer_and_sickle.svg)
**Option B:** A Material-esque version of the icon

## Preview

![communism-a](https://user-images.githubusercontent.com/1837101/94226931-1a7b1b80-feb6-11ea-95d9-52eb57435b7c.png)
![communism-b](https://user-images.githubusercontent.com/1837101/94226932-1b13b200-feb6-11ea-8141-e7d43f784d6e.png)

## Zip Download

[communism.zip](https://github.com/Templarian/MaterialDesign/files/5280610/communism.zip)

**Comment by goyney** [comment]
Definitely `hammer-sickle` with a `communism` alias.

**Comment by Xenomorph99** [comment]
I'm fine with calling it either. However, if we go with the literal `hammer-sickle`, wouldn't it make sense to change [christianity](https://materialdesignicons.com/icon/christianity) to `cross` or `crucifix` and [islam](https://materialdesignicons.com/icon/islam) to `star-crescent` or even `moon-star`. They're using the religious/ideological name not the literal name of the symbol.

https://en.wikipedia.org/wiki/Star_and_crescent
https://en.wikipedia.org/wiki/Crucifix

**Comment by goyney** [comment]
Yeah, those changes make sense. Can you open issues for each so we can track them as Breaking Changes for 6.0? Those were added long before we changed our naming pattern to be as literal as possible.

**Comment by goyney** [comment]
[![hammer-sickle](https://materialdesignicons.com/icon/hammer-sickle)](https://materialdesignicons.com/icon/hammer-sickle)
