### ISSUE TITLE
Alternate design for coach or outdoor lamp

### ISSUE THREAD

**Issue by Box2112** [Templarian/MaterialDesign#5525]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same use as other light icons but different design.

## Examples

Include any example images so we know what the icon should look like.
![outdoor-lamp](https://user-images.githubusercontent.com/46469423/94227504-fbc06780-ff3d-11ea-87fd-e4c5c19cbb68.png)

**Comment by JoryHogeveen** [comment]
Would be nice!
Also, a group variation of these type of lamps would be nice as well

**Comment by goyney** [comment]
[![coach-lamp-variant](https://materialdesignicons.com/icon/coach-lamp-variant)](https://materialdesignicons.com/icon/coach-lamp-variant)
