### ISSUE TITLE
code-tags-*

### ISSUE THREAD

**Issue by magranero** [Templarian/MaterialDesign#5526]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/18167085/94258701-877dc800-ff2d-11ea-884c-d56a39ac575b.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[cyber-water.svg.zip](https://github.com/Templarian/MaterialDesign/files/5282272/cyber-water.svg.zip)

**Comment by goyney** [comment]
Thank you for your suggestion/contribution. There are a couple things that will need to be addressed here before this is ready for consideration:
- [Material guidelines](https://material.io/design/iconography/system-icons.html) must be followed.
- The proposed icon contains several elements we already have, such as `code-tags` and `water-outline`. Those should be used as the basis for this type of icon.

**Comment by Templarian** [comment]
@magranero Lets consolidate all of these here. Also what is the use case for these?

- [ ] `code-tags-pulse`
- [ ] `code-tags-cog`
- [ ] `code-tags-toilet-sink`
- [ ] `code-tags-battery-charging-outline`
- [ ] `code-tags-panel`
- [ ] `code-tags-thermometer`
- [ ] `code-tags-microphone`
- [ ] `code-tags-bed-empty`
- [ ] `code-tags-chevron-triple-right`
- [ ] `code-tags-door`
- [ ] `code-tags-television`
- [ ] `code-tags-lock-outline`

**Comment by Templarian** [comment]
@magranero ^ ?

**Comment by goyney** [comment]
This seems extremely niche and we haven't gotten a response on a valid use case, so we're going to close this out. Please feel free to comment back here if these are still needed with any additional information and we can reconsider this request. Thank you!
