### ISSUE TITLE
Pirate Face 

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#553]
I just think that it's kind a cool thing to have

**Comment by CoDEmanX** [comment]
I guess something like on the upper left
![Imgur](http://i.imgur.com/eU4tK8m.jpg)
Although a wooden leg or a pirate hook would be more expressive I guess.

**Comment by raeglan** [comment]
I still think that is a good idea, there is no Captain or Pirate symbol yet.

**Comment by PeterShaggyNoble** [comment]
I meant to bump this a while ago, must've forgotten.

**Comment by goyney** [comment]
Time for a showdown!

![image](https://user-images.githubusercontent.com/1015040/41948018-d13f533c-7988-11e8-946e-95e75d56884b.png) ![image](https://user-images.githubusercontent.com/1015040/41948049-f43ad8c0-7988-11e8-895d-a39ee18491a5.png)

**Comment by PeterShaggyNoble** [comment]
Nice work, @goyney, looks great.

Out of curiousity, how does it look without the cross on the hat and with a full beard?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/41977830-61198210-79ee-11e8-9625-c70d612fa87f.png) ![image](https://user-images.githubusercontent.com/1015040/41977819-5d10b986-79ee-11e8-9400-4ba3e64b88ee.png)

**Source:** [arrrrrr.zip](https://github.com/Templarian/MaterialDesign/files/2141478/arrrrrr.zip)

**Comment by JamesCoyle** [comment]
What about having the eyes just be round? Seem a bit too angry and
negative for MDI.

**Comment by goyney** [comment]
@JamesCoyle It was made to match the `ninja` icon.

Also: 
![image](https://user-images.githubusercontent.com/1015040/41982218-d915992a-79f8-11e8-9667-deb826a7af1a.png)

**Comment by Templarian** [comment]
[![pirate](https://materialdesignicons.com/icon/pirate)](https://materialdesignicons.com/icon/pirate)
