### ISSUE TITLE
code-tags-battery-charging-outline

### ISSUE THREAD

**Issue by magranero** [Templarian/MaterialDesign#5530]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/18167085/94261661-83a07480-ff32-11ea-824b-12fba5950312.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[cyber-battery.svg.zip](https://github.com/Templarian/MaterialDesign/files/5282447/cyber-battery.svg.zip)

**Comment by goyney** [comment]
Thank you for your suggestion/contribution. There are a couple things that will need to be addressed here before this is ready for consideration:
- [Material guidelines](https://material.io/design/iconography/system-icons.html) must be followed.
- The proposed icon contains several elements we already have, such as `code-tags` and `battery-charging-outline`. Those should be used as the basis for this type of icon.
