### ISSUE TITLE
code-tags-panel

### ISSUE THREAD

**Issue by magranero** [Templarian/MaterialDesign#5531]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/18167085/94261801-c06c6b80-ff32-11ea-9f5d-d688e641cb17.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[cyber-panel.svg.zip](https://github.com/Templarian/MaterialDesign/files/5282460/cyber-panel.svg.zip)

**Comment by goyney** [comment]
Thank you for your suggestion/contribution. There are a couple things that will need to be addressed here before this is ready for consideration:
- [Material guidelines](https://material.io/design/iconography/system-icons.html) must be followed.
- The proposed icon contains an element we already have (`code-tags`). The other element is new and would need to be created following Material guidelines.
