### ISSUE TITLE
Rename Religious/Ideological Icons

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5541]
I believe we decided to use literal not representational names for icons in our library. If this is true, then the following icons need to be renamed.

- **[christianity](https://materialdesignicons.com/icon/christianity) --> cross or crucifix**
We have [shield-cross](https://materialdesignicons.com/icon/shield-cross) and [shield-cross-outline](https://materialdesignicons.com/icon/shield-cross-outline), which motivates us to rename [christianity](https://materialdesignicons.com/icon/christianity) and [christianity-outline](https://materialdesignicons.com/icon/christianity-outline) to `cross` and `cross-outline`. However, `crucifix` and `crucifix-outline` would work too, but then we'd probably want `shield-crucifix` and `shield-crucifix-outline` to match.
 _https://en.wikipedia.org/wiki/Crucifix_
 
- **[islam](https://materialdesignicons.com/icon/islam) --> star-crescent**
_https://en.wikipedia.org/wiki/Star_and_crescent_
aliases: `islam`, `religion-islam`, `religion-muslim`
 
- **[judaism](https://materialdesignicons.com/icon/judaism) --> star-david**
 _https://en.wikipedia.org/wiki/Star_of_David_
aliases: `judaism`, `religion-judaism`, `religion-judaic`, `jewish`, `hebrew`, `israel`, `magen-david`
 
- **[buddhism](https://materialdesignicons.com/icon/buddhism) --> dharmachakra**
 _https://en.wikipedia.org/wiki/Dharmachakra_
aliases: `dharma-wheel`, `religion-hinduism`, `religion-buddhism`, `religion-jainism`
 
- **[hinduism](https://materialdesignicons.com/icon/hinduism) --> om**
 _https://en.wikipedia.org/wiki/Om_
aliases: `aum`, `religion-hinduism`, `religion-buddhism`, `religion-jainism`

**Comment by goyney** [comment]
These have been renamed.
