### ISSUE TITLE
Truck Cargo Container

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5542]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![truck-cargo-container](https://user-images.githubusercontent.com/1837101/94314924-cff1b180-ff3e-11ea-955c-9f418e44aaa1.png)

## Zip Download

[truck-cargo-container.zip](https://github.com/Templarian/MaterialDesign/files/5285352/truck-cargo-container.zip)

**Comment by goyney** [comment]
[![truck-cargo-container](https://materialdesignicons.com/icon/truck-cargo-container)](https://materialdesignicons.com/icon/truck-cargo-container)
