### ISSUE TITLE
Train Cars

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5543]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

These icons are based on the same specs as the passenger cars I submitted in #5493. I created a separate issue for these ones since they're only tangentially related.

## Preview

![train-car-box](https://user-images.githubusercontent.com/1837101/94328111-1eb64000-ff6d-11ea-9e30-03c7b9850f5b.png)
![train-car-box-open](https://user-images.githubusercontent.com/1837101/94328109-1e1da980-ff6d-11ea-8082-1aa91ae23eaf.png)
![train-car-box-full](https://user-images.githubusercontent.com/1837101/94328108-1d851300-ff6d-11ea-9d30-66621ff8c5b0.png)
![train-car-box-variant](https://user-images.githubusercontent.com/1837101/94328110-1e1da980-ff6d-11ea-841a-6b7ca31babb8.png)

![train-car-hopper](https://user-images.githubusercontent.com/1837101/94328123-21189a00-ff6d-11ea-87d1-d7d1e1cd76fa.png)
![train-car-hopper-full](https://user-images.githubusercontent.com/1837101/94328122-20800380-ff6d-11ea-90d0-449bbf2741d7.png)
![train-car-hopper-covered](https://user-images.githubusercontent.com/1837101/94328121-20800380-ff6d-11ea-8341-77b6551eb311.png)

![train-car-gondola](https://user-images.githubusercontent.com/1837101/94328120-20800380-ff6d-11ea-89fe-96909e958005.png)
![train-car-gondola-full](https://user-images.githubusercontent.com/1837101/94328119-1fe76d00-ff6d-11ea-8e7a-fb4201029ebd.png)

![train-car-centerbeam](https://user-images.githubusercontent.com/1837101/94328115-1f4ed680-ff6d-11ea-9815-b12bae7f6412.png)
![train-car-centerbeam-full](https://user-images.githubusercontent.com/1837101/94328113-1eb64000-ff6d-11ea-854d-614a22dd3ee6.png)

![train-car-flat](https://user-images.githubusercontent.com/1837101/94328118-1fe76d00-ff6d-11ea-9678-7e83424a78ff.png)
![train-car-flat-car](https://user-images.githubusercontent.com/1837101/94328116-1f4ed680-ff6d-11ea-8cf8-1be62b212ac5.png)
![train-car-flat-tank](https://user-images.githubusercontent.com/1837101/94328117-1fe76d00-ff6d-11ea-9612-fa759aeb0fd9.png)

![train-car-intermodal](https://user-images.githubusercontent.com/1837101/94328124-21189a00-ff6d-11ea-8721-a553a8c07370.png)

![train-car-tank](https://user-images.githubusercontent.com/1837101/94328125-21189a00-ff6d-11ea-838c-ce0bf8cffa7f.png)

![train-car-autorack](https://user-images.githubusercontent.com/1837101/94328107-1cec7c80-ff6d-11ea-8353-e3e08d36ae1f.png)

![train-car-caboose](https://user-images.githubusercontent.com/1837101/94328112-1eb64000-ff6d-11ea-8618-e78626a088ec.png)

## Zip Download

[train-cars.zip](https://github.com/Templarian/MaterialDesign/files/5286080/train-cars.zip)

**Comment by goyney** [comment]
All of these were added, though some rather niche. 🥲

**Comment by Xenomorph99** [comment]
Yay! Now I can design a train game.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/170349101-01d5d71a-1544-4718-93e2-bddf08345e0b.png)
