### ISSUE TITLE
All Inclusive "Box" version.

### ISSUE THREAD

**Issue by dpuckett** [Templarian/MaterialDesign#5544]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As an "active" counter part to the All-Inclusive icon. 
If we were to take the current AllInclusive icon as though it were the outline version, there should then be a "box" version which can act as it's active state (or vice versa).

Design should just be a rounded rectangle, filled color, with a white all-Inclusive symbol.

## Examples

VideoBox / VideoOutline
NewsPaper-Variant / NewsPaper-Variant-outline

**Comment by Xenomorph99** [comment]
I tried out the shape using 1, 1.5, and 2 dps. Even though it get's a little squishy, the 2 dps options are probably best. They're easiest to read at smaller resolutions.

![all-inclusive-box-1dps](https://user-images.githubusercontent.com/1837101/94597667-1733b700-024b-11eb-8919-341bf3c46d68.png)
![all-inclusive-box-1 5dps](https://user-images.githubusercontent.com/1837101/94597664-1733b700-024b-11eb-871d-932f9acd99dd.png)
![all-inclusive-box-2dps](https://user-images.githubusercontent.com/1837101/94597668-17cc4d80-024b-11eb-8799-79e55bbd002a.png)

![all-inclusive-box-outline-1dps](https://user-images.githubusercontent.com/1837101/94597671-1864e400-024b-11eb-9039-848845db9eac.png)
![all-inclusive-box-outline-1 5dps](https://user-images.githubusercontent.com/1837101/94597669-17cc4d80-024b-11eb-9a4e-5687c3e314cf.png)
![all-inclusive-box-outline-2dps](https://user-images.githubusercontent.com/1837101/94597674-1864e400-024b-11eb-94dc-262f2cf5494c.png)
[all-inclusive-box.zip](https://github.com/Templarian/MaterialDesign/files/5300961/all-inclusive-box.zip)

**Comment by dpuckett** [comment]
Personally I think the 1.5 dps versions look best. They're more aesthetically pleasing, closer to the counter part icon sizing and still readable at smaller resolutions.

**Comment by goyney** [comment]
[![all-inclusive-box](https://materialdesignicons.com/icon/all-inclusive-box)](https://materialdesignicons.com/icon/all-inclusive-box)[![all-inclusive-box-outline](https://materialdesignicons.com/icon/all-inclusive-box-outline)](https://materialdesignicons.com/icon/all-inclusive-box-outline)
