### ISSUE TITLE
Pop OS icon

### ISSUE THREAD

**Issue by octavcosmin** [Templarian/MaterialDesign#5546]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

I intend to use it with [this](https://github.com/mateosss/matter) project.

## Examples

Include any example images so we know what the icon should look like.

I suggest [this image](https://support.system76.com/images/pop-icon.png) or a simplified one similar to [this one](https://i.redd.it/ms9je823h6y31.png).

**Comment by Templarian** [comment]
This one might be too niche of a Linux distribution. 🤔

**Comment by octavcosmin** [comment]
Maybe, but it's the new distro recommended to beginners and it is already taking some of ubuntu's marketshare. I'm following the r/FindMeADistro on Reddit (and answer sometimes) and most people who mention either gaming or having an nvidia gpu are instantly recommended Pop os.

**Comment by Templarian** [comment]
After some research I think this is worth adding to the pack. 👍

**Comment by octavcosmin** [comment]
Glad to help :D
