### ISSUE TITLE
Database Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5547]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![database-off](https://user-images.githubusercontent.com/1837101/94746962-1ed28900-033b-11eb-8928-a255cde75784.png)
![database-alert](https://user-images.githubusercontent.com/1837101/94746952-1d08c580-033b-11eb-80c2-190f84a4caff.png)
![database-clock](https://user-images.githubusercontent.com/1837101/94746961-1ed28900-033b-11eb-9678-a849f815845f.png)

![database-arrow-left](https://user-images.githubusercontent.com/1837101/94746957-1da15c00-033b-11eb-9c7d-3dfa3af6eb60.png)
![database-arrow-right](https://user-images.githubusercontent.com/1837101/94746958-1e39f280-033b-11eb-9ece-8c7d95340ab0.png)
![database-arrow-up](https://user-images.githubusercontent.com/1837101/94746960-1e39f280-033b-11eb-850d-970b757dc07e.png)
![database-arrow-down](https://user-images.githubusercontent.com/1837101/94746954-1da15c00-033b-11eb-9b0e-31c771048dbf.png)

## Zip Download

[database-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5308592/database-modifiers.zip)

**Comment by Templarian** [comment]
Added. 👍
