### ISSUE TITLE
Database Outline

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5548]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![database-outline](https://user-images.githubusercontent.com/1837101/94747149-77a22180-033b-11eb-8d79-6d264eea3d77.png)
![database-off-outline](https://user-images.githubusercontent.com/1837101/94747148-77098b00-033b-11eb-9ee9-2cf1d39103f7.png)

![database-plus-outline](https://user-images.githubusercontent.com/1837101/94747152-77a22180-033b-11eb-8630-267819edea5a.png)
![database-minus-outline](https://user-images.githubusercontent.com/1837101/94747147-77098b00-033b-11eb-9422-cbc7c562cab8.png)

![database-check-outline](https://user-images.githubusercontent.com/1837101/94747140-753fc780-033b-11eb-98bf-9c459cdb03c3.png)
![database-remove-outline](https://user-images.githubusercontent.com/1837101/94747154-783ab800-033b-11eb-99e6-bbb91f60f17b.png)

![database-alert-outline](https://user-images.githubusercontent.com/1837101/94747130-73760400-033b-11eb-9a08-a2250c098f3f.png)

![database-search-outline](https://user-images.githubusercontent.com/1837101/94747156-783ab800-033b-11eb-8c58-b584a17baf0e.png)
![database-edit-outline](https://user-images.githubusercontent.com/1837101/94747142-75d85e00-033b-11eb-8e4d-3489af6e04f1.png)
![database-lock-outline](https://user-images.githubusercontent.com/1837101/94747145-7670f480-033b-11eb-81c9-d9d1f9b577d0.png)
![database-marker-outline](https://user-images.githubusercontent.com/1837101/94747146-77098b00-033b-11eb-9679-b5c3bb616dd5.png)
![database-settings-outline](https://user-images.githubusercontent.com/1837101/94747157-783ab800-033b-11eb-9da5-bbf69298db39.png)

![database-refresh-outline](https://user-images.githubusercontent.com/1837101/94747153-77a22180-033b-11eb-982d-a6517b54f849.png)
![database-sync-outline](https://user-images.githubusercontent.com/1837101/94747159-78d34e80-033b-11eb-938c-dad6b2acff46.png)

![database-export-outline](https://user-images.githubusercontent.com/1837101/94747143-7670f480-033b-11eb-9c7a-bdbe81872009.png)
![database-import-outline](https://user-images.githubusercontent.com/1837101/94747144-7670f480-033b-11eb-8efd-6f122c33c197.png)

![database-arrow-left-outline](https://user-images.githubusercontent.com/1837101/94747133-740e9a80-033b-11eb-9206-cf99ae130f9d.png)
![database-arrow-right-outline](https://user-images.githubusercontent.com/1837101/94747137-74a73100-033b-11eb-8cdf-ac2639baa37e.png)
![database-arrow-up-outline](https://user-images.githubusercontent.com/1837101/94747139-753fc780-033b-11eb-81db-09b3060bb786.png)
![database-arrow-down-outline](https://user-images.githubusercontent.com/1837101/94747132-740e9a80-033b-11eb-807d-2dca505dc0f1.png)

![database-clock-outline](https://user-images.githubusercontent.com/1837101/94747141-75d85e00-033b-11eb-821f-d4f5077d1511.png)

## Zip Download

[database-outline.zip](https://github.com/Templarian/MaterialDesign/files/5308599/database-outline.zip)

**Comment by Templarian** [comment]
Added. 😃
