### ISSUE TITLE
Strategy

### ISSUE THREAD

**Issue by jaybowles** [Templarian/MaterialDesign#555]
Perhaps an icon to represent strategy?

![image](https://cloud.githubusercontent.com/assets/1458030/8982030/32e26dc8-36b5-11e5-967a-1b15ac78b03d.png)

**Comment by CoDEmanX** [comment]
Looks like a treasure map :wink:

Maybe a chess piece or something like this?
![flow chart](http://www.777icons.com/libs/design/flow_block-icon.gif)

**Comment by jaybowles** [comment]
Haha yea I guess it does look a bit like a treasure map. It's the one which
tends to come up for strategy, though.

Personally I would use the one you posted if I was looking for Process or
Flow, or maybe even Hierarchy.

Perhaps the Compass is the most suitable option?

**Comment by MrGrigri** [comment]
I'm going to reopen this issue with a contribution.

![strategy](https://user-images.githubusercontent.com/4528551/66138637-322e0580-e5bc-11e9-9cae-d8ad02cff6fa.png)

---
#### Files

[strategy.zip](https://github.com/Templarian/MaterialDesign/files/3686718/strategy.zip)

**Comment by goyney** [comment]
[![strategy](https://materialdesignicons.com/icon/strategy)](https://materialdesignicons.com/icon/strategy)
