### ISSUE TITLE
Content Save Off

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5550]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![content-save-off](https://user-images.githubusercontent.com/1837101/94884150-de9e0400-0429-11eb-91ee-49cfbdce015b.png)
![content-save-off-outline](https://user-images.githubusercontent.com/1837101/94884148-de056d80-0429-11eb-8589-d414589a4a8c.png)

## Zip Download

[content-save-off.zip](https://github.com/Templarian/MaterialDesign/files/5315785/content-save-off.zip)

**Comment by Templarian** [comment]
Added. 👍
