### ISSUE TITLE
3D Shapes (Sphere, Cylinder, Cone, Pyramid, Octahedron)

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5551]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

It would be nice to have other basic 3D shapes in addition to [cube](https://materialdesignicons.com/icon/cube) and [cube-outline](https://materialdesignicons.com/icon/cube-outline).

## Sphere

![sphere](https://user-images.githubusercontent.com/1837101/94887785-6be65600-0434-11eb-83f3-80a37c297e29.png)
![sphere-outline](https://user-images.githubusercontent.com/1837101/94887784-6be65600-0434-11eb-98b7-8d5309358dbc.png)
![sphere-off](https://user-images.githubusercontent.com/1837101/94887783-6be65600-0434-11eb-92e6-0e8ed7001925.png)
![sphere-off-outline](https://user-images.githubusercontent.com/1837101/94887780-6b4dbf80-0434-11eb-93d6-79c08ae94bc1.png)

## Cylinder

![cylinder](https://user-images.githubusercontent.com/1837101/94887821-86b8ca80-0434-11eb-83ec-48b4a05ccc08.png)
![cylinder-outline](https://user-images.githubusercontent.com/1837101/94887820-86b8ca80-0434-11eb-90bf-7cc653e42283.png)
![cylinder-off](https://user-images.githubusercontent.com/1837101/94887819-86203400-0434-11eb-83aa-de16ce0f8f16.png)
![cylinder-off-outline](https://user-images.githubusercontent.com/1837101/94887817-85879d80-0434-11eb-9d4d-739098533812.png)

## Pyramid

![pyramid](https://user-images.githubusercontent.com/1837101/94887867-9d5f2180-0434-11eb-8315-bdf421e04b4f.png)
![pyramid-outline](https://user-images.githubusercontent.com/1837101/94887866-9d5f2180-0434-11eb-9e6f-03887c20b53e.png)
![pyramid-off](https://user-images.githubusercontent.com/1837101/94887865-9cc68b00-0434-11eb-8487-295cf32ee47c.png)
![pyramid-off-outline](https://user-images.githubusercontent.com/1837101/94887863-9c2df480-0434-11eb-969d-f0d95568e2a7.png)

## Cone

![cone](https://user-images.githubusercontent.com/1837101/94887931-c8497580-0434-11eb-95ed-dee9ae72a55e.png)
![cone-outline](https://user-images.githubusercontent.com/1837101/94887929-c8497580-0434-11eb-8e0d-f67a99d604f8.png)
![cone-off](https://user-images.githubusercontent.com/1837101/94887927-c7b0df00-0434-11eb-817f-46208bfd0a2a.png)
![cone-off-outline](https://user-images.githubusercontent.com/1837101/94887925-c67fb200-0434-11eb-8c0f-344e0599e3ec.png)

## Octahedron

![octahedron](https://user-images.githubusercontent.com/1837101/94944003-d085cd00-0495-11eb-8bd6-af7dfa10510b.png)
![octahedron-outline](https://user-images.githubusercontent.com/1837101/94944002-d085cd00-0495-11eb-993d-ebd99b0660e7.png)
![octahedron-off](https://user-images.githubusercontent.com/1837101/94944000-cfed3680-0495-11eb-8ad8-0b11ff689885.png)
![octahedron-off-outline](https://user-images.githubusercontent.com/1837101/94943999-cf54a000-0495-11eb-96ca-4b87ac23415e.png)

## Zip Download

[3D-shapes.zip](https://github.com/Templarian/MaterialDesign/files/5319040/3D-shapes.zip)

**Comment by goyney** [comment]
I don't understand the sphere and octahedron and this is why perspective isn't allowed in Material. I appreciate the work here but do not feel we should add these.

**Comment by Xenomorph99** [comment]
It's kind of a double standard saying we can't have 3D shapes when we already have a [cube](https://materialdesignicons.com/icon/cube) icon in the library. Personally, I think the outline versions are useful to have in the library.

I only created the non-outline versions to match the existing [cube](https://materialdesignicons.com/icon/cube) paradigm. I agree, I'm not the biggest fan of `sphere` and `octahedron`, but they match as a set. They could be read as having light cast on their form producing highlights.

**Comment by Templarian** [comment]
I think these are fine exceptions.

**Comment by Xenomorph99** [comment]
I'm fine if we just add the outline versions.

**Comment by goyney** [comment]
All the outlined versions were added without `-outline` in their names.
