### ISSUE TITLE
Add Sonarqube icon

### ISSUE THREAD

**Issue by cam-brown** [Templarian/MaterialDesign#5553]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/55197655/94907877-b8637d00-0498-11eb-8009-39dd24f84f92.png)

## Zip Download

[sonarqube.svg.zip](https://github.com/Templarian/MaterialDesign/files/5317025/sonarqube.svg.zip)

**Comment by Templarian** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by Templarian** [comment]
This is already included in SimpleIcons by the way. 👍
