### ISSUE TITLE
Database Cog

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5555]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Oops, I forgot this important database modifier in my previous issue #5548

## Preview

![database-cog](https://user-images.githubusercontent.com/1837101/94947169-6facc380-049a-11eb-81cb-149f04b02ca4.png)
![database-cog-outline](https://user-images.githubusercontent.com/1837101/94947167-6f142d00-049a-11eb-8624-366f002e4a7d.png)

## Zip Download

[database-cog.zip](https://github.com/Templarian/MaterialDesign/files/5319204/database-cog.zip)

**Comment by Templarian** [comment]
Added. 👍
