### ISSUE TITLE
Cookie Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5556]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![cookie-outline](https://user-images.githubusercontent.com/1837101/94949978-12674100-049f-11eb-84aa-70cd00c5b2e4.png)
![cookie-off](https://user-images.githubusercontent.com/1837101/94949977-12674100-049f-11eb-8522-5783122f87ef.png)
![cookie-off-outline](https://user-images.githubusercontent.com/1837101/94949975-11ceaa80-049f-11eb-8ef9-8f12a331373d.png)

![cookie-plus](https://user-images.githubusercontent.com/1837101/94949981-12ffd780-049f-11eb-8bbd-ae543e98660b.png)
![cookie-plus-outline](https://user-images.githubusercontent.com/1837101/94949979-12ffd780-049f-11eb-83e1-28b0ea38ebeb.png)
![cookie-minus](https://user-images.githubusercontent.com/1837101/94949961-0aa79c80-049f-11eb-81e5-7ae201702a28.png)
![cookie-minus-outline](https://user-images.githubusercontent.com/1837101/94949959-0a0f0600-049f-11eb-8354-9eeaee1b21fb.png)

![cookie-check](https://user-images.githubusercontent.com/1837101/94949949-08454280-049f-11eb-8026-ebf82d4ade53.png)
![cookie-check-outline](https://user-images.githubusercontent.com/1837101/94949948-08454280-049f-11eb-9e4c-cbcce5c6258a.png)
![cookie-remove](https://user-images.githubusercontent.com/1837101/94949987-14310480-049f-11eb-87b5-62298da3d863.png)
![cookie-remove-outline](https://user-images.githubusercontent.com/1837101/94949986-14310480-049f-11eb-8136-60b2e71f180a.png)

![cookie-refresh](https://user-images.githubusercontent.com/1837101/94949985-14310480-049f-11eb-993a-c32924e546b4.png)
![cookie-refresh-outline](https://user-images.githubusercontent.com/1837101/94949982-13986e00-049f-11eb-8115-6940d06a9062.png)
![cookie-alert](https://user-images.githubusercontent.com/1837101/94949946-08454280-049f-11eb-9d49-bc887f9a4225.png)
![cookie-alert-outline](https://user-images.githubusercontent.com/1837101/94949945-07acac00-049f-11eb-8841-1251bacd0a92.png)

![cookie-cog](https://user-images.githubusercontent.com/1837101/94949953-09766f80-049f-11eb-8c41-29e93b73b7e8.png)
![cookie-cog-outline](https://user-images.githubusercontent.com/1837101/94949952-08ddd900-049f-11eb-9dc3-2e57c413c274.png)
![cookie-settings](https://user-images.githubusercontent.com/1837101/94949989-14c99b00-049f-11eb-83fd-4004b0900869.png)
![cookie-settings-outline](https://user-images.githubusercontent.com/1837101/94949988-14c99b00-049f-11eb-8ad3-692f16dc9e42.png)

![cookie-edit](https://user-images.githubusercontent.com/1837101/94949956-0a0f0600-049f-11eb-89ac-20f094f44e57.png)
![cookie-edit-outline](https://user-images.githubusercontent.com/1837101/94949955-09766f80-049f-11eb-98b6-be558ce7522e.png)
![cookie-lock](https://user-images.githubusercontent.com/1837101/94949958-0a0f0600-049f-11eb-978b-a9552abb00d4.png)
![cookie-lock-outline](https://user-images.githubusercontent.com/1837101/94949957-0a0f0600-049f-11eb-975b-820e6d648bf9.png)

![cookie-clock](https://user-images.githubusercontent.com/1837101/94949951-08ddd900-049f-11eb-82bb-7b20ea302c55.png)
![cookie-clock-outline](https://user-images.githubusercontent.com/1837101/94949950-08ddd900-049f-11eb-84c3-735d85252ec2.png)

## Zip Download

[cookie-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5319355/cookie-modifiers.zip)

**Comment by goyney** [comment]
These are nice. The alert one needs 2dp of space between the cookie and the exclamation point though.

**Comment by Xenomorph99** [comment]
Here's the updated `cookie-alert` and `cookie-alert-outline` icons.

![cookie-alert](https://user-images.githubusercontent.com/1837101/94955828-6f1b2980-04a8-11eb-83b5-f8530a826c69.png)
![cookie-alert-outline](https://user-images.githubusercontent.com/1837101/94955816-6c203900-04a8-11eb-8e3a-0695716dda0e.png)

[updated-cookie-alert.zip](https://github.com/Templarian/MaterialDesign/files/5319599/updated-cookie-alert.zip)

**Comment by Templarian** [comment]
No objections to adding these.

**Comment by Xenomorph99** [comment]
Done. Added.
