### ISSUE TITLE
Calendar privacy / lock icon

### ISSUE THREAD

**Issue by oliver-jonas** [Templarian/MaterialDesign#5557]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It's for an option that filters calendar events by privacy visibility status (public / private).

## Examples

![calendar-lock](https://user-images.githubusercontent.com/12098901/94972126-dcf73d80-0508-11eb-926d-8f866f4495d4.png)

If the lock is too small to fit inside the calendar it could also be moved to the lower / right corner like with calendar-refresh or calendar-search.

**Comment by Templarian** [comment]
@oliver-jonas Agreed `*-lock` might be better used an overlay in the bottom right corner in this case. `account-lock` / `cloud-lock` are good examples. Definitely a useful icon to include. @Xenomorph99 quick one since you've been doing overlays lately.

**Comment by Xenomorph99** [comment]
Here's the standard "lock" overlay.

![calendar-lock-a](https://user-images.githubusercontent.com/1837101/94974657-718f7a80-04cc-11eb-8697-6a418bb5dfcd.png)
![calendar-lock-outline-a](https://user-images.githubusercontent.com/1837101/94974660-72281100-04cc-11eb-9e61-1532fa5d7912.png)

I tried putting the lock in the center of the calendar icons. It works in `calendar`, but I had to shrink it to fit inside `calendar-outline`. I don't think these are bad, but I recommend we run with the standard overlay in this case.

![calendar-lock-b](https://user-images.githubusercontent.com/1837101/94974659-72281100-04cc-11eb-9a74-04ac63b4c3f1.png)
![calendar-lock-outline-b](https://user-images.githubusercontent.com/1837101/94974661-72c0a780-04cc-11eb-8765-5cc587e18a55.png)

[calendar-lock.zip](https://github.com/Templarian/MaterialDesign/files/5320591/calendar-lock.zip)

**Comment by Templarian** [comment]
Added. 👍

**Comment by oliver-jonas** [comment]
Thanks for the icon.
