### ISSUE TITLE
store-plus icon

### ISSUE THREAD

**Issue by dylanoli** [Templarian/MaterialDesign#5559]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/20401971/94992784-a221f380-0562-11eb-9d10-2bea8bcda4c9.png)

## Zip Download
[store-plus.zip](https://github.com/Templarian/MaterialDesign/files/5321740/store-plus.zip)

**Comment by Templarian** [comment]
Added (along with `remove` and `minus`). These were assigned to the pooled contributor account. Let us know once you have 5 icons and we'll create/assign these to a contributor account. 👍
