### ISSUE TITLE
Icon Request: IMDb

### ISSUE THREAD

**Issue by DavidEdwards** [Templarian/MaterialDesign#556]
I would love to see an icon for IMDb

Here is a Wikimedia commons SVG in the public domain:

https://commons.wikimedia.org/wiki/File:IMDb_logo.svg

**Comment by Templarian** [comment]
This might be a little too detailed for the 24x24 size.

**Comment by Templarian** [comment]
I don't think this is an ideal icon for the the style. I actually tried to create it, but there is too much detail in the 24x24 size restriction.
