### ISSUE TITLE
robot-outline icon

### ISSUE THREAD

**Issue by oneezy** [Templarian/MaterialDesign#5562]
# robot-outline Icon

Requesting a `robot-outline` icon. The original `robot` icon was created by @GreenTurtwig 
![image](https://user-images.githubusercontent.com/7369575/95044249-92122d00-06a4-11eb-8056-dc1059b6049c.png)

## Usage

We would use for our navigation menu. All of our other icons are `outline` except this one. It doesn't look bad but it would look way better if we had that `robot-outline` !

## Examples

![image](https://user-images.githubusercontent.com/7369575/95044469-15338300-06a5-11eb-8ea7-51709125585c.png)

**Comment by Xenomorph99** [comment]
In example A, I left the eyes the same size (5x5 dps) as [robot](https://materialdesignicons.com/icon/robot), but they felt a little too big and made the robot look like a Teletubby. In example B, I shrunk the eyes to 4x4 dps, but they felt a little too wide if they stayed in the same position.
![robot-outline-example-a](https://user-images.githubusercontent.com/1837101/95098823-62871300-06ec-11eb-80df-5b2bbeca60d1.png)
![robot-outline-example-b](https://user-images.githubusercontent.com/1837101/95098826-62871300-06ec-11eb-8cbc-ccc5071b4e88.png)

So, I shifted the eyes in towards the center. I think this version looks the best. Even though the top and bottom of the eyes don't line up to the grid, they're at the same vertical position as the filled version.

![robot-outline](https://user-images.githubusercontent.com/1837101/95098828-631fa980-06ec-11eb-92d1-ff1aef1b9fc4.png)

I figured I'd make the off version while I was at it too.

![robot-off](https://user-images.githubusercontent.com/1837101/95098820-61ee7c80-06ec-11eb-8c98-9bc83d6ab8a1.png)
![robot-off-outline](https://user-images.githubusercontent.com/1837101/95098817-6155e600-06ec-11eb-8a4b-603434013ed6.png)

[robot-outline.zip](https://github.com/Templarian/MaterialDesign/files/5328284/robot-outline.zip)

**Comment by oneezy** [comment]
nice work @Xenomorph99 ! for me it still seems like the eyes need to be brought in and up a bit. i did a quick mockup of what that would look like. 

**adjustments made:**
- brought both eyes inwards by `1px` block
- brought both eyes up by `.5px` block

![image](https://user-images.githubusercontent.com/7369575/95138928-04c8ea00-0731-11eb-85cb-60444aceb4cb.png)

**Comment by Xenomorph99** [comment]
The closer the eyes get the less it looks like a robot and the more it looks like a Teletubby to me.

![teletubby](https://user-images.githubusercontent.com/1837101/95140560-6aff3e00-072c-11eb-937a-6b1e974a26ee.png)

**Comment by oneezy** [comment]
you make a good point

**Comment by oneezy** [comment]
updated navigation
![image](https://user-images.githubusercontent.com/7369575/95294624-42199e80-083b-11eb-8b45-185820c16518.png)

**Comment by Templarian** [comment]
What happens if we place it on a half a pixel. I think that might look nicer.

**Comment by Xenomorph99** [comment]
Here's what it would look like shifting the eyes outwards by 0.5 dps. Now there's only a 0.5 dps gap between the outline and the eyes instead of 1 dps like I posted above. It depends on how strict we want to be with the rules. I could go either way on this one.

![robot-outline](https://user-images.githubusercontent.com/1837101/95349887-c7717300-087c-11eb-8618-ee76869311c8.png)
![robot-off-outline](https://user-images.githubusercontent.com/1837101/95349885-c6d8dc80-087c-11eb-98e8-a00f459aa014.png)

[robot-outine.zip](https://github.com/Templarian/MaterialDesign/files/5341689/robot-outine.zip)

**Comment by Templarian** [comment]
I definitely meant the other way @Xenomorph99 😓

**Comment by Xenomorph99** [comment]
Haha! How about this then?

![robot-outline](https://user-images.githubusercontent.com/1837101/95357485-2509bd80-0885-11eb-8945-8219ccb07076.png)
![robot-off-outline](https://user-images.githubusercontent.com/1837101/95357481-24712700-0885-11eb-89ce-59c5caa5f540.png)

[robot-outline.zip](https://github.com/Templarian/MaterialDesign/files/5342096/robot-outline.zip)

**Comment by Templarian** [comment]
That's the one. Will add it later today!

**Comment by goyney** [comment]
Added.

**Comment by Xenomorph99** [comment]
@goyney or @Templarian can you add `robot-off` as well? It's in one of the first posts on this issue. I could try doing it if you'd like, but I haven't actually added an icon myself yet.
