### ISSUE TITLE
outdoor-lamp-reverse

### ISSUE THREAD

**Issue by shevu** [Templarian/MaterialDesign#5564]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![outdoor-lamp-reverse](https://user-images.githubusercontent.com/5359829/95096727-f082ee00-072c-11eb-8193-d3f4009de478.png)

## Zip Download

[outdoor-lamp-reverse.zip](https://github.com/Templarian/MaterialDesign/files/5328171/outdoor-lamp-reverse.zip)

**Comment by goyney** [comment]
For the most part, we do not offer flip, rotated, or reversed version of our icons. It is your responsibility to do that via CSS, or some other means, in your application.
