### ISSUE TITLE
Store Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5565]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Here's a full set of modifiers for [store](https://materialdesignicons.com/icon/store).

I'm not sure if `store-clock` or `store-search` are readable, but I included them here in case we decide to add them too.

## Preview

![store-plus-outline](https://user-images.githubusercontent.com/1837101/95112393-16dd6500-06fe-11eb-9208-ea04f820de68.png)
![store-minus-outline](https://user-images.githubusercontent.com/1837101/95112389-16dd6500-06fe-11eb-80d5-bcfdf2526a3c.png)
![store-remove-outline](https://user-images.githubusercontent.com/1837101/95112394-1775fb80-06fe-11eb-94b7-6645f854e5d1.png)

![store-check](https://user-images.githubusercontent.com/1837101/95112373-147b0b00-06fe-11eb-936c-1e9ba1caac02.png)
![store-check-outline](https://user-images.githubusercontent.com/1837101/95112372-147b0b00-06fe-11eb-9554-747fd2a6fe13.png)

![store-off](https://user-images.githubusercontent.com/1837101/95112392-16dd6500-06fe-11eb-9396-b507b9b13a4b.png)
![store-off-outline](https://user-images.githubusercontent.com/1837101/95112390-16dd6500-06fe-11eb-8f91-f338e1889ac1.png)

![store-alert](https://user-images.githubusercontent.com/1837101/95112370-13e27480-06fe-11eb-85d4-dc6f744b3509.png)
![store-alert-outline](https://user-images.githubusercontent.com/1837101/95112367-1349de00-06fe-11eb-8dde-ad4bfe893eda.png)

![store-edit](https://user-images.githubusercontent.com/1837101/95112384-1644ce80-06fe-11eb-9eac-2bffe483408a.png)
![store-edit-outline](https://user-images.githubusercontent.com/1837101/95112383-15ac3800-06fe-11eb-94b5-a1ef55080286.png)

![store-settings](https://user-images.githubusercontent.com/1837101/95112398-180e9200-06fe-11eb-901d-2309719705bd.png)
![store-settings-outline](https://user-images.githubusercontent.com/1837101/95112397-1775fb80-06fe-11eb-8ea9-59000de7340c.png)

![store-cog](https://user-images.githubusercontent.com/1837101/95112381-15ac3800-06fe-11eb-91b7-c0a494213114.png)
![store-cog-outline](https://user-images.githubusercontent.com/1837101/95112380-15ac3800-06fe-11eb-9be8-c881ee00239c.png)

![store-marker](https://user-images.githubusercontent.com/1837101/95112388-1644ce80-06fe-11eb-8351-85b1b9724a31.png)
![store-marker-outline](https://user-images.githubusercontent.com/1837101/95112385-1644ce80-06fe-11eb-8cb4-72aed4a05703.png)

![store-clock](https://user-images.githubusercontent.com/1837101/95112377-1513a180-06fe-11eb-8d72-35929fc24902.png)
![store-clock-outline](https://user-images.githubusercontent.com/1837101/95112374-1513a180-06fe-11eb-8c30-2d6095f56959.png)

![store-search](https://user-images.githubusercontent.com/1837101/95112396-1775fb80-06fe-11eb-958d-73dfacfabb69.png)
![store-search-outline](https://user-images.githubusercontent.com/1837101/95112395-1775fb80-06fe-11eb-8408-53f69347b244.png)

## Zip Download

[store-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5329100/store-modifiers.zip)

**Comment by goyney** [comment]
All added and will release in v6.3.
