### ISSUE TITLE
Bulletlight

### ISSUE THREAD

**Issue by hatjan** [Templarian/MaterialDesign#5566]
I would like to see an icon of a hanging ball lamp

## Examples

something like this
![kugellampeV3black](https://user-images.githubusercontent.com/53946271/95192179-16160300-07d2-11eb-8e5b-9b3392f4fc86.png)

**Comment by goyney** [comment]
[![globe-light](https://materialdesignicons.com/icon/globe-light)](https://materialdesignicons.com/icon/globe-light)
