### ISSUE TITLE
Tape drive

### ISSUE THREAD

**Issue by zgover** [Templarian/MaterialDesign#5567]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/9044773/95231370-af401c00-07c8-11eb-957a-cefa8ccc0fc8.png)

## Zip Download

[tape-drive.svg.zip](https://github.com/Templarian/MaterialDesign/files/5335349/tape-drive.svg.zip)

**Comment by Templarian** [comment]
@zgover Looks nice, but needs to be 18x18 or the proportions will look off next to other icons.

Then it can be added.

**Comment by zgover** [comment]
Updated, see below.

![image](https://user-images.githubusercontent.com/9044773/95357471-833a9e80-088d-11eb-98e9-5c77d8a58f67.png)

[tape-drive.svg.zip](https://github.com/Templarian/MaterialDesign/files/5342103/tape-drive.svg.zip)

**Comment by zgover** [comment]
Updated, see below.

![image](https://user-images.githubusercontent.com/9044773/95358692-f09aff00-088e-11eb-98b2-72df37875f19.png)

[tape-drive.svg.zip](https://github.com/Templarian/MaterialDesign/files/5342164/tape-drive.svg.zip)

**Comment by goyney** [comment]
The center circle needs to be on grid, IMO.

**Comment by zgover** [comment]
To address that here are examples of 4 and 2, I just felt 4 was too big and 2 was too small. 

![image](https://user-images.githubusercontent.com/9044773/95359908-491ecc00-0890-11eb-9a32-9bc255306ff9.png)
[tape-drive.svg.zip](https://github.com/Templarian/MaterialDesign/files/5342222/tape-drive.svg.zip)

![image](https://user-images.githubusercontent.com/9044773/95360091-8be0a400-0890-11eb-80e5-6c56402b55ff.png)
[tape-drive.svg.zip](https://github.com/Templarian/MaterialDesign/files/5342233/tape-drive.svg.zip)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/95360271-27761280-0899-11eb-9578-a506cd4dd316.png)
That's the winner for me.

**Comment by Templarian** [comment]
Added.
