### ISSUE TITLE
ID icon

### ISSUE THREAD

**Issue by notsidney** [Templarian/MaterialDesign#5568]
The use case for this icon is a unique ID for a database item. I’ve based it off the alpha- icons by GreenTurtwig

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/27017118/95283650-0b2da200-08a8-11eb-82b5-cfefd39364fb.png)

## Zip Download

[id.svg.zip](https://github.com/Templarian/MaterialDesign/files/5338095/id.svg.zip)

**Comment by goyney** [comment]
We already have `identifier`. This can remain open for discussion if we should update the current icon to use our font or not. @Templarian will need to chime in, since he created the current icon.

**Comment by Templarian** [comment]
I really hate our current `id` icon. Lets replace it! Who let me add that. 🤦‍♂️

**Comment by goyney** [comment]
Our has been updated.
