### ISSUE TITLE
Robot Emoticons

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5570]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Here's some ideas for robot emoticons. It'd be awesome to get some feedback on these. (The outline versions relate to issue #5562)

## Preview

![robot-angry](https://user-images.githubusercontent.com/1837101/95365553-8df63300-088f-11eb-9e9c-c48966cd22f2.png)
![robot-angry-outline](https://user-images.githubusercontent.com/1837101/95365550-8d5d9c80-088f-11eb-8aa6-c355d43aa52d.png)

![robot-confused](https://user-images.githubusercontent.com/1837101/95365560-8e8ec980-088f-11eb-826e-ce22fbffcc85.png)
![robot-confused-outline](https://user-images.githubusercontent.com/1837101/95365556-8e8ec980-088f-11eb-8338-cf539dd11938.png)

![robot-dead](https://user-images.githubusercontent.com/1837101/95365564-8f276000-088f-11eb-8dac-5ba621d0ca5d.png)
![robot-dead-outline](https://user-images.githubusercontent.com/1837101/95365561-8f276000-088f-11eb-99b8-ec97faf1efe5.png)

![robot-excited](https://user-images.githubusercontent.com/1837101/95365568-8fbff680-088f-11eb-9fc5-16baa6fd1023.png)
![robot-excited-outline](https://user-images.githubusercontent.com/1837101/95365567-8fbff680-088f-11eb-9c61-9f519cf8bb3b.png)

![robot-happy](https://user-images.githubusercontent.com/1837101/95365571-90588d00-088f-11eb-9daf-f2c9f4e24801.png)
![robot-happy-outline](https://user-images.githubusercontent.com/1837101/95365569-90588d00-088f-11eb-9085-60d58e563e67.png)

![robot-tongue](https://user-images.githubusercontent.com/1837101/95365576-90f12380-088f-11eb-8e79-8de4d1335d94.png)
![robot-tongue-outline](https://user-images.githubusercontent.com/1837101/95365572-90f12380-088f-11eb-8270-d24197ff82e5.png)

## Zip Download

[robot-emoticons.zip](https://github.com/Templarian/MaterialDesign/files/5342618/robot-emoticons.zip)

**Comment by Xenomorph99** [comment]
Here's another one

![robot-love](https://user-images.githubusercontent.com/1837101/95366746-14f7db00-0891-11eb-9040-52e79a147b23.png)
![robot-love-outline](https://user-images.githubusercontent.com/1837101/95366745-145f4480-0891-11eb-8bde-e8faec3a34c8.png)

[robot-love.zip](https://github.com/Templarian/MaterialDesign/files/5342665/robot-love.zip)

**Comment by Templarian** [comment]
All of them are okay to add except for tongue. That one is just odd on a robot. 😛

**Comment by darren-outdev** [comment]
All of them look great, except for the ones with a mouth. Good job!

**Comment by Templarian** [comment]
Try the happy one without the mouth maybe.

**Comment by Xenomorph99** [comment]
I added all the ones without mouths.

**Comment by Xenomorph99** [comment]
I removed the mouths and these are the two sets of eyes leftover. It makes sense to add "robot-happy-a" as `robot-happy`. Is there another emotion you guys can think of for "robot-happy-b" or should we scrap that version?

![robot-happy-a](https://user-images.githubusercontent.com/1837101/95602908-d7bb5680-0a12-11eb-8c83-7d67c6c0d8dc.png)
![robot-happy-outline-a](https://user-images.githubusercontent.com/1837101/95602912-d853ed00-0a12-11eb-8c85-51cdfd755eb8.png)

![robot-happy-b](https://user-images.githubusercontent.com/1837101/95602910-d853ed00-0a12-11eb-9f95-fe166181ed61.png)
![robot-happy-outline-b](https://user-images.githubusercontent.com/1837101/95602914-d8ec8380-0a12-11eb-9e82-bf1cfbc9f44f.png)
[robot-happy.zip](https://github.com/Templarian/MaterialDesign/files/5355971/robot-happy.zip)

**Comment by Templarian** [comment]
Probably go with -a, the -b looks more like "content happiness", which is probably not necessary. That should close out this issue.

**Comment by Xenomorph99** [comment]
Added.
