### ISSUE TITLE
Update cloud-sync and cloud-sync-outline

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#5571]
I feel `cloud-sync` and `cloud-sync-outline` are a little bit odd due to the way the modifier cuts the cloud, leading to a very thin path on top-right of the modified.

What do you think about these versions ? (the outline one is not completely clear but the plain one sounds great)

## Preview
![image](https://user-images.githubusercontent.com/6012554/95450322-66be6500-0966-11eb-9acd-a1f4afb2281e.png)
![image](https://user-images.githubusercontent.com/6012554/95450454-9a00f400-0966-11eb-8ece-fc0f16fa7757.png)

## Zip Download
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/5347343/Archive.zip)

**Comment by goyney** [comment]
The `sync` modifier is our standard. I do not feel we should modify these.

**Comment by jdinnen** [comment]
Is it possible to use the source code to customize this as my project managers don't want the new cloud sync icon but we need some of the newer ones like the Shield-Alert? Are there instruct somewhere that I could follow? Thank you.

**Comment by jdinnen** [comment]
> Is it possible to use the source code to customize this as my project managers don't want the new cloud sync icon but we need some of the newer ones like the Shield-Alert? Are there instruct somewhere that I could follow? Thank you.

OK, I think I got it to build but it renamed all 5000+ svg files to include the unicode character code at the beginning.. I don't know if that was normal...

**Comment by Templarian** [comment]
@jdinnen Yeah, need to fix that in the `@mdi/font-build`. Going to try and make it a lot easier to override / customize the font.

Read more: https://github.com/Templarian/MaterialDesign-Font-Build/issues/6

The whole rename thing is part of how the `webfont` package expects the file names. We'll rename it back after generation.

**Comment by Templarian** [comment]
@jdinnen https://github.com/Templarian/MaterialDesign-Font-Build/issues/10 created a bug specifically for this.

**Comment by Templarian** [comment]
@qnp The original designs looked like this, but we actually updated them as the outline looked really bad if I recall. Also think we should probably close this one.

**Comment by qnp** [comment]
Ok, yes I agree for the outline version.
Thanks for taking time to read my request. I'm closing.

**Comment by jdinnen** [comment]
> @jdinnen https://github.com/Templarian/MaterialDesign-Font-Build/issues/10 created a bug specifically for this.

Thank you! Sorry for posting my noob problems here... Thank you guys for the hard work you put into this, it's excellent! I was hoping to slim a version of this down to be more a-la-Carte and lightweight. I used maybe 10-15 icons. Having 5500+ is overkill when bundling with a app.

**Comment by qnp** [comment]
Can't you use @mdi/js to import only required icons and benefit from tree shaking ?

**Comment by jdinnen** [comment]
> Can't you use @mdi/js to import only required icons and benefit from tree shaking ?

I honestly have no idea, I only just figured out how to get the source and build the font very recently. I'm very new to it. I'm more in Xamarin Forms and C# world. I can look I'm around for some info on that. Thanks!

**Comment by Templarian** [comment]
@jdinnen https://dev.materialdesignicons.com/getting-started/xamarin I'm surprised xamarin doesn't have a library to render basic small SVG images somehow. That is really bulky to include the entire icon pack (especially the TTF format).

Let me reach out on twitter to some people I know.

**Comment by Templarian** [comment]
A quick search shows: https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SVG but not sure how to use it where icons are used (not really familiar with Xamarin).

**Comment by jdinnen** [comment]
> A quick search shows: https://github.com/paulpatarinski/Xamarin.Forms.Plugins/tree/master/SVG but not sure how to use it where icons are used (not really familiar with Xamarin).

Nice... I use this as Xamarin forms has a really cool feature to make icons easier. It would be roughly along the lines of these. It's called FontImageSource and used the glyph from the font... 
https://montemagno.com/using-font-icons-in-xamarin-forms-goodbye-images-hello-fonts/
