### ISSUE TITLE
closed_marked_outline(X) similar to checkbox_marked outline

### ISSUE THREAD

**Issue by dhaladitya108** [Templarian/MaterialDesign#5572]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.
the icon should to completely similar to checkbox_marked_outline but with cross symbol instead of a tick symbol

**Comment by goyney** [comment]
Already exists:
[![close-circle-outline](https://materialdesignicons.com/icon/close-circle-outline)](https://materialdesignicons.com/icon/close-circle-outline)
