### ISSUE TITLE
"A/C Cool" ; "A/C Heat" ; "A/C Off" based on "air-conditioner"

### ISSUE THREAD

**Issue by ItamarVa** [Templarian/MaterialDesign#5573]
"A/C Cool" ; "A/C Heat" ; "A/C Off" based on "air-conditioner" or something similar

![air-conditioner](https://user-images.githubusercontent.com/69388551/95661562-f74c9f00-0b38-11eb-9005-3a12fa4894b3.png)

I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by agneevX** [comment]
Yep, the current AC icon is quite dumb and should be replaced.

**Comment by GreenTurtwig** [comment]
This won't be possible due to issues with language conflicts, a potential workaround would be to use `fire` and `snowflake` as modifiers.

**Comment by Xenomorph99** [comment]
While A/C was derived from an English abbreviation, it has become an internationally recognized symbol. People who don't know English even know what it mean. It's very common to see the symbol A/C in cars anywhere in the world. Automotive manufacturers don't translate A/C on car dashboards. 

![image](https://user-images.githubusercontent.com/1837101/97644786-db8a3980-1a10-11eb-986e-ba3b403d4279.png)
![image](https://user-images.githubusercontent.com/1837101/97645241-0032e100-1a12-11eb-8f3b-001d4c6e3487.png)

That being said, you'll notice how car dashboards use other means to convey whether A/C is on or off. (There's a light on the buttons in the two examples above.) I don't think it makes sense to add our standard `-off` modifier to our [air-conditioner](https://materialdesignicons.com/icon/air-conditioner) icon. Nor does it make sense to create a similar icon that uses the word "cool" or "heat".

**Comment by agneevX** [comment]
How about creating a new icon, instead of the fan icon and some text below it?

**Comment by TheGroundZero** [comment]
+1 for air-conditioner-off
Could simply be the air-conditioner icon with a strikethrough, like hvac and hvac-off

**Comment by soosp** [comment]
> +1 for air-conditioner-off Could simply be the air-conditioner icon with a strikethrough, like hvac and hvac-off

+1
