### ISSUE TITLE
Split AC

### ISSUE THREAD

**Issue by agneevX** [Templarian/MaterialDesign#5574]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Used to denote split aircons.

Aside, the current `air-conditioner` is very generic and only shows a fan atop the text; not very helpful. 

## Examples

<img src="https://cdn1.iconfinder.com/data/icons/electronics-vol-2/48/096-512.png" width="250">

<img src="https://cdn1.iconfinder.com/data/icons/appliancesets/31/aircon_2-512.png" width="250">

<img src="https://cdn.iconscout.com/icon/premium/png-512-thumb/split-2-204753.png" width="250">

**Comment by goyney** [comment]
There's a duplicate issue for this that was created after this one, but we're going to close this one because the other issue has a lot more detail into what might be required to satisfy the use case. Please follow that issue for further updates.

#5653
