### ISSUE TITLE
wifi-connected icon

### ISSUE THREAD

**Issue by RobinSinghNanda** [Templarian/MaterialDesign#5575]
I have:

- [YES] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [YES] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [YES] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
This wifi icon can be used to show the wifi is connected to server.

## Examples

Include any example images so we know what the icon should look like.
![rsz_screenshot_20201011-194035](https://user-images.githubusercontent.com/71327582/95680891-5a523a80-0bfa-11eb-8614-b00299b58607.jpg)

**Comment by RobinSinghNanda** [comment]
I have designed some WiFi icons that could be useful. 
![wifi-connected](https://user-images.githubusercontent.com/71327582/95947720-db811b80-0e0c-11eb-9d6f-3149b44a4ef8.png)
![wifi-alert](https://user-images.githubusercontent.com/71327582/95947785-fb184400-0e0c-11eb-8873-ee80a37d685d.png)
![wifi-success](https://user-images.githubusercontent.com/71327582/95947903-2bf87900-0e0d-11eb-83cc-114aece9ecc4.png)
![wifi-sync](https://user-images.githubusercontent.com/71327582/95948339-03bd4a00-0e0e-11eb-9b88-8cb7789beb57.png)

**Comment by visualpharm** [comment]
Great work! 
You can also take this if you want https://icons8.com/icon/set/wifi/material-outlined
!(wifi connected)[https://img.icons8.com/material-outlined/24/000000/wi-fi-connected.png"]

**Comment by Templarian** [comment]
@RobinSinghNanda There are standard overlays for all icons that need to used. 

Read more: https://dev.materialdesignicons.com/contribute/icon-naming#overlay

**Comment by RobinSinghNanda** [comment]
Hi @Templarian,
       Except for **alert** overlay, I don't see any standard overlays **sync**, **connected**, **check** and **lock**

![wifi-lock](https://user-images.githubusercontent.com/71327582/96376561-60698d80-119d-11eb-9cb7-59f87e163e51.png)
![wifi-sync](https://user-images.githubusercontent.com/71327582/96376563-63647e00-119d-11eb-9b02-a03f96a7e76f.png)
![wifi-alert](https://user-images.githubusercontent.com/71327582/96376566-665f6e80-119d-11eb-826c-c63af5f4f259.png)
![wifi-check](https://user-images.githubusercontent.com/71327582/96376567-67909b80-119d-11eb-81fa-c35bbb71988c.png)
![wifi-connected](https://user-images.githubusercontent.com/71327582/96376568-68c1c880-119d-11eb-9543-35c87568f26a.png)

Please suggest changes.

**Comment by Templarian** [comment]
@RobinSinghNanda Look at the existing icons and you'll see the standardized overlays (almost all have been updated).

`-lock`, `-sync`, `-check`, `-alert`.

The up down arrow one is not a standard overlay, but there needs to be a 2px cutout around the arrows. Right not it's not readable at 1:1 size.

**Comment by RobinSinghNanda** [comment]
Sure, I will check the existing icons and update my icons to match them. I will add 2px cutout around the arrows as well.

**Comment by RobinSinghNanda** [comment]
I updated the icons with 2px cutout.
![wifi-connected](https://user-images.githubusercontent.com/71327582/96418963-1b7f3e80-1211-11eb-9cb7-1f4b51977a6b.png)
![wifi-lock](https://user-images.githubusercontent.com/71327582/96418964-1b7f3e80-1211-11eb-8b65-4cbc4c9d3360.png)
![wifi-sync](https://user-images.githubusercontent.com/71327582/96418969-1c17d500-1211-11eb-8cee-a22a6ed34827.png)
![wifi-alert](https://user-images.githubusercontent.com/71327582/96418976-1f12c580-1211-11eb-80f3-208e57707c9e.png)
![wifi-check](https://user-images.githubusercontent.com/71327582/96418987-22a64c80-1211-11eb-8aef-8c4081f415a7.png)


Let me know if any other changes are required.

**Comment by Xenomorph99** [comment]
## Standard Modifiers

![wifi-plus](https://user-images.githubusercontent.com/1837101/96507231-1ec8f900-1216-11eb-93a0-bacf971ef95b.png)
![wifi-minus](https://user-images.githubusercontent.com/1837101/96507229-1ec8f900-1216-11eb-8c9b-802858d124e4.png)
![wifi-check](https://user-images.githubusercontent.com/1837101/96507219-1cff3580-1216-11eb-9913-3c6011532239.png)
![wifi-remove](https://user-images.githubusercontent.com/1837101/96507233-1f618f80-1216-11eb-8aa5-1063abdf8121.png)
![wifi-cog](https://user-images.githubusercontent.com/1837101/96507221-1d97cc00-1216-11eb-8123-4145e940bdcf.png)
![wifi-settings](https://user-images.githubusercontent.com/1837101/96507234-1f618f80-1216-11eb-86fa-40f713159754.png)
![wifi-lock](https://user-images.githubusercontent.com/1837101/96509666-9b110b80-1219-11eb-924e-591827d6c538.png)
![wifi-lock-open](https://user-images.githubusercontent.com/1837101/96509664-9a787500-1219-11eb-8ff1-465739fdf9a9.png)
![wifi-marker](https://user-images.githubusercontent.com/1837101/96507226-1e306280-1216-11eb-8696-b16c6496eb99.png)
![wifi-cancel](https://user-images.githubusercontent.com/1837101/96507215-1cff3580-1216-11eb-9d4c-97b0554f7b54.png)
![wifi-sync](https://user-images.githubusercontent.com/1837101/96507237-1ffa2600-1216-11eb-91ff-c526d6a1c9be.png)
![wifi-refresh](https://user-images.githubusercontent.com/1837101/96507232-1f618f80-1216-11eb-8235-53341081fc33.png)
![wifi-arrow-down](https://user-images.githubusercontent.com/1837101/96507191-153f9100-1216-11eb-9fa7-12d4e342e40e.png)
![wifi-arrow-left](https://user-images.githubusercontent.com/1837101/96507194-15d82780-1216-11eb-9314-2e53aecc8d63.png)
![wifi-arrow-right](https://user-images.githubusercontent.com/1837101/96507196-15d82780-1216-11eb-8f06-bfd7cedb842a.png)
![wifi-arrow-up](https://user-images.githubusercontent.com/1837101/96507198-15d82780-1216-11eb-91d1-c2a305f31885.png)

### Alert

How should we deal with `wifi-alert`? I applied our standard alert overlay, but our other wifi alert icons ([wifi-strength-1-alert](https://materialdesignicons.com/icon/wifi-strength-1-alert), [wifi-strength-2-alert](https://materialdesignicons.com/icon/wifi-strength-2-alert), [wifi-strength-3-alert](https://materialdesignicons.com/icon/wifi-strength-3-alert), [wifi-strength-4-alert](https://materialdesignicons.com/icon/wifi-strength-4-alert), and [wifi-strength-alert-outline](https://materialdesignicons.com/icon/wifi-strength-alert-outline)) are not using the same one. Perhaps we can update our other icons as well? I saw that we never got to them in #4908. I included the updated icons in the zip below.

![wifi-alert](https://user-images.githubusercontent.com/1837101/96510462-c8aa8480-121a-11eb-8c6e-1ffb86712b5c.png)
![wifi-strength-alert-outline](https://user-images.githubusercontent.com/1837101/96512531-ddd4e280-121d-11eb-94c2-a01ecddc2957.png)
![wifi-strength-4-alert](https://user-images.githubusercontent.com/1837101/96512530-dd3c4c00-121d-11eb-8e5d-b6e0e899213a.png)
![wifi-strength-3-alert](https://user-images.githubusercontent.com/1837101/96512529-dd3c4c00-121d-11eb-95d7-40540bd3fa60.png)
![wifi-strength-2-alert](https://user-images.githubusercontent.com/1837101/96512528-dca3b580-121d-11eb-8e49-fcea58f00948.png)
![wifi-strength-1-alert](https://user-images.githubusercontent.com/1837101/96512525-dc0b1f00-121d-11eb-9689-5fbfe3594674.png)

## Non-standard Modifiers

How do we feel about these arrows? [cog-transfer](https://materialdesignicons.com/icon/cog-transfer) is another icon with a left and right arrow, but I feel like we should do something that matches closer to our arrow overlay (posted above).

![wifi-arrow-left-right](https://user-images.githubusercontent.com/1837101/96507169-0eb11980-1216-11eb-8195-9eaf93780728.png)
![wifi-arrow-up-down](https://user-images.githubusercontent.com/1837101/96507172-0f49b000-1216-11eb-831a-a46d1829ae54.png)

### Zip Download

[wifi-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/5404824/wifi-modifiers.zip)

**Comment by RobinSinghNanda** [comment]
All icons looks good to me. May i know how did you generate the work in progress images? Is there a standard software or template to do it?

**Comment by Xenomorph99** [comment]
@RobinSinghNanda, I'm guessing when you created this issue you clicked the `get started` button on the "Request an icon" row. In the future if you're planning to submit an icon and click the `get started` button on the "Contribute an icon" row instead. There's a link to one of the image generators there.

<img width="600" alt="screenshot-2" src="https://user-images.githubusercontent.com/1837101/96623231-4bd5e400-12c8-11eb-9761-ef1e2d5cefd2.png">
<img width="600" alt="screenshot-1" src="https://user-images.githubusercontent.com/1837101/96623235-4c6e7a80-12c8-11eb-985e-d470c0f10c45.png">

http://dev.materialdesignicons.com/contribute/github

**Comment by Xenomorph99** [comment]
Added and updated all the icons except the existing alert icons.
