### ISSUE TITLE
Philips Hue Go

### ISSUE THREAD

**Issue by JanOstrowka** [Templarian/MaterialDesign#5576]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

version 1.0
![image](https://user-images.githubusercontent.com/3185243/95685795-6c33dd80-0bfa-11eb-9f84-9bed5ea290ec.png)

version 2.0
![image](https://user-images.githubusercontent.com/3185243/95686107-3859b780-0bfc-11eb-928a-c6d423092d8d.png)

## Zip Download

version 1.0
[philips-hue-go.svg.zip](https://github.com/Templarian/MaterialDesign/files/5361570/philips-hue-go.svg.zip)

version 2.0
[philips-hue-go-wider.svg.zip](https://github.com/Templarian/MaterialDesign/files/5361613/philips-hue-go-wider.svg.zip)

**Comment by goyney** [comment]
https://github.com/Templarian/MaterialDesign/issues/4063#issuecomment-474876241
