### ISSUE TITLE
please fix icon of routes.js file

### ISSUE THREAD

**Issue by saeidalb** [Templarian/MaterialDesign#5577]
When i create routes.js file the icons not showing correctly

![Screenshot 2020-10-12 093630](https://user-images.githubusercontent.com/45012465/95710862-74c5fb80-0c6e-11eb-9c46-23f7a9f849d1.png)

**Comment by goyney** [comment]
I think you might be confusing us for a Material Design Icon extension for VSCode. While an extension author might use our icon pack to power their extension, we do not create or maintain any.

If you go into your Extensions, find the Material Icons extension you're using and click on it, then click the "Repository" link. That should take you to the extension's GitHub page.
