### ISSUE TITLE
Group / ungroup icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#558]
As seen in graphic design applications, Word etc. to create compound objects or to split them into separate pieces again:

![Imgur](http://i.imgur.com/oQ16E8y.png)
![group-objects](https://cloud.githubusercontent.com/assets/1309249/8990207/12fa4a12-36f1-11e5-97c2-d1b5b53fb23a.png)

Already gave it a shot, but don't particularly like the result:
![group-objects](https://cloud.githubusercontent.com/assets/1309249/8990249/49381708-36f1-11e5-933c-4f8c3cd22cc1.png)

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/group
https://materialdesignicons.com/icon/ungroup

**Comment by CoDEmanX** [comment]
Nice one, thanks!
