### ISSUE TITLE
Celebrate Icon

### ISSUE THREAD

**Issue by harsha20599** [Templarian/MaterialDesign#5580]
I have:

- [ ✅ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ✅ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ✅ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
I'd like to have an icon that demonstrates celebration, enjoyment, and party. I'd want to represent work anniversaries.

## Examples

Here are a few of my ideas took from the noun-project
![image](https://user-images.githubusercontent.com/20438252/96160561-bf2bce80-0f33-11eb-850b-c5c795d26fe1.png)

**Comment by goyney** [comment]
[![party-popper](https://materialdesignicons.com/icon/party-popper)](https://materialdesignicons.com/icon/party-popper)
