### ISSUE TITLE
Deck of Cards icon

### ISSUE THREAD

**Issue by michaeldadzie** [Templarian/MaterialDesign#5585]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

![Capture](https://user-images.githubusercontent.com/52431642/96391318-cf4be400-11a7-11eb-9875-40eb3b4520f5.PNG)

**Comment by Templarian** [comment]
@michaeldadzie Did you see `cards-playing-outline` (or `cards` / `cards-outline`)? Would these work or do you need them stacked like that specifically.

**Comment by michaeldadzie** [comment]
> @michaeldadzie Did you see `cards-playing-outline` (or `cards` / `cards-outline`)? Would these work or do you need them stacked like that specifically.

I need them stacked like that.

**Comment by Templarian** [comment]
When we create this one it might be worthwhile to create `card-playing-heart` etc with all the suits. Then just add the standard `-multiple` design. 🤔

**Comment by michaeldadzie** [comment]
Definitely worthwhile creating the other suits. looking forward to seeing them soon :)

**Comment by temaprint** [comment]
try these
https://icons8.com/icons/set/cards
<img src="https://img.icons8.com/dusk/64/000000/cards.png"/>
<img src="https://img.icons8.com/wired/64/000000/cards.png"/>
<img src="https://img.icons8.com/color/64/000000/cards.png"/>

**Comment by GreenTurtwig** [comment]
`cards-playing-*-outline`
![](https://user-images.githubusercontent.com/15905797/97617198-666d3300-1a15-11eb-95ac-1f3a84d3f283.png)![](https://user-images.githubusercontent.com/15905797/97617249-7127c800-1a15-11eb-9b40-61f32dc4fe71.png)![](https://user-images.githubusercontent.com/15905797/97617303-80a71100-1a15-11eb-993c-52f44b7dac55.png)![](https://user-images.githubusercontent.com/15905797/97617378-96b4d180-1a15-11eb-9de1-c7ffbfd14708.png)  
  
`cards-playing-*-multiple-outline`
![](https://user-images.githubusercontent.com/15905797/97617576-d4b1f580-1a15-11eb-8abf-59c03f97ed56.png)![](https://user-images.githubusercontent.com/15905797/97617645-ee533d00-1a15-11eb-8118-5e4c23b3a836.png)![](https://user-images.githubusercontent.com/15905797/97622784-a71c7a80-1a1c-11eb-9125-d17ca849f299.png)![](https://user-images.githubusercontent.com/15905797/97622818-b4d20000-1a1c-11eb-9b55-8af5a281612a.png)

  
`cards-playing-*`
![](https://user-images.githubusercontent.com/15905797/97622989-eba81600-1a1c-11eb-9adb-349d5d262709.png)![](https://user-images.githubusercontent.com/15905797/97623058-0a0e1180-1a1d-11eb-8c57-9bada1c9e151.png)![](https://user-images.githubusercontent.com/15905797/97623142-2316c280-1a1d-11eb-9271-1a8d29044679.png)![](https://user-images.githubusercontent.com/15905797/97623103-16926a00-1a1d-11eb-8a42-64e19f02b954.png)
  
`cards-playing-*-multiple`
![](https://user-images.githubusercontent.com/15905797/97623515-ad5f2680-1a1d-11eb-9c12-927fee5ae299.png)![](https://user-images.githubusercontent.com/15905797/97623565-bbad4280-1a1d-11eb-95ae-0d0673b33975.png)![](https://user-images.githubusercontent.com/15905797/97623610-cec01280-1a1d-11eb-9db3-623960f51dba.png)![](https://user-images.githubusercontent.com/15905797/97623632-daabd480-1a1d-11eb-9474-9be4b225cb2f.png)
  
  
Also got these variations on the standard `cards-playing-*` where the symbol is larger, though I'm not sure how I feel about them.
![](https://user-images.githubusercontent.com/15905797/97623875-31b1a980-1a1e-11eb-86c6-23b995b04002.png)![](https://user-images.githubusercontent.com/15905797/97623956-4e4de180-1a1e-11eb-825d-581e7af9eed2.png)![](https://user-images.githubusercontent.com/15905797/97623988-5a39a380-1a1e-11eb-9526-db91cc571ced.png)![](https://user-images.githubusercontent.com/15905797/97624028-67ef2900-1a1e-11eb-9987-bfc6f39ae1be.png)

**Comment by GreenTurtwig** [comment]
[cards-playing.zip](https://github.com/Templarian/MaterialDesign/files/5460982/cards-playing.zip)
Forgot this. 😖

**Comment by goyney** [comment]
All of these have been added and will release in v6.3.
