### ISSUE TITLE
Smoking, Cigar, and Pipe

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5588]
We have [smoking](https://materialdesignicons.com/icon/smoking) and [smoking-pipe](https://materialdesignicons.com/icon/smoking-pipe). We also have [cigar](https://materialdesignicons.com/icon/cigar).

Should we change [cigar](https://materialdesignicons.com/icon/cigar) to `smoking-cigar` to match the set?

**or**

Should we change [smoking](https://materialdesignicons.com/icon/smoking) to `cigarette` and change [smoking-pipe](https://materialdesignicons.com/icon/smoking-pipe) to either `pipe` or `pipe-tobacco` and use their literal names?

**Comment by Templarian** [comment]
We discussed this one before. It was done to not conflict with `pipe` (which represents pipes). Often these are called smoking pipes.

My vote is to leave these as-is.

**Comment by Xenomorph99** [comment]
I'm fine leaving it as is for now. Just thought I'd bring it up in case we add other types of smoking paraphernalia such as `pipe-cannabis` or 'pipe-glass` in the future? It would feel strange to call it `smoking-cannabis` or `smoking-glass`. Smoking can also refer to Hookah or using a Bong. Some references to peruse:

https://www.etsy.com/market/glass_pipes
https://en.wikipedia.org/wiki/Cannabis_smoking
https://en.wikipedia.org/wiki/Tobacco_pipe
https://en.wikipedia.org/wiki/Ceremonial_pipe
https://en.wikipedia.org/wiki/Kiseru
https://en.wikipedia.org/wiki/Hookah
https://en.wikipedia.org/wiki/Bong

**Comment by goyney** [comment]
Going to leave this alone for now. If we amass more smoking related icons before v7, we can revisit renaming this.
