### ISSUE TITLE
houzz-box icon broken?

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#559]
The non-boxed version looks like a 3D `H`, but the boxed version looks just confusing:
![houzz-box-orig](https://cloud.githubusercontent.com/assets/1309249/8990612/ca34fec8-36f3-11e5-8a0c-76ba8c1e1c21.png)

Shouldn't it be like this instead?
![houzz-box](https://cloud.githubusercontent.com/assets/1309249/8990613/ca368478-36f3-11e5-9ecf-0341e0bc66ab.png) https://www.dropbox.com/s/p0akeu7yob7bfxu/houzz-box.svg?dl=0

**Comment by Templarian** [comment]
Fixed.

https://materialdesignicons.com/icon/houzz-box

**Comment by CoDEmanX** [comment]
Thanks, looks good. Doesn't appear on history stream though?!
https://materialdesignicons.com/history

**Comment by Templarian** [comment]
Yea, the ability for my account to update through another users account is broken right now so I just edited the DB, downside no history log.
