### ISSUE TITLE
Face recognizion (biometric) icon

### ISSUE THREAD

**Issue by casni** [Templarian/MaterialDesign#5591]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

When logging in with the Biometrics API on Android phones, it will prompt the user to use fingerprint, face recognition og even iris scanning. I would like version of the "official" Android face recognition biometric icon, to be used for the biometrics login button.

## Examples

I am curently using this:
![image](https://user-images.githubusercontent.com/45106283/96855682-5b3a6600-145d-11eb-8f36-633930ddda86.png)

But would like this icon instead:
![image](https://user-images.githubusercontent.com/45106283/96855603-3fcf5b00-145d-11eb-9b31-3e10c7628f39.png)

**Comment by Xenomorph99** [comment]
Our library already has several options for faces. Stylistically, these are what we've decided to go with. I don't think it makes sense to add additional styles.

![face](https://user-images.githubusercontent.com/1837101/97728113-c526c100-1a96-11eb-9474-38477c8cc152.png)
![face-woman](https://user-images.githubusercontent.com/1837101/97728110-c48e2a80-1a96-11eb-9965-fc99e66b6996.png)
![emoticon-outline](https://user-images.githubusercontent.com/1837101/97728115-c526c100-1a96-11eb-9507-da010161f338.png)
![apple-finder](https://user-images.githubusercontent.com/1837101/97728208-e091cc00-1a96-11eb-8dc9-f06a3e1cd2d4.png)
