### ISSUE TITLE
Oven

### ISSUE THREAD

**Issue by jormercury** [Templarian/MaterialDesign#5592]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There is a md toaster-oven icon, but I was looking for one more resembling a full size oven.
It is for use with [home assistant](https://www.home-assistant.io/) to link to a connected oven, for instance for the power toggle (so could be on and off as well...).

## Examples

![](https://www.appliance-insurance.co.uk/wp-content/uploads/2019/06/Oven-Symbols-Explained.png)

![](https://cdn0.iconfinder.com/data/icons/thin-food-cooking/24/thin-0892_cooking_oven_kitchen_appliances-512.png)

**Comment by GreenTurtwig** [comment]
[![oven](https://user-images.githubusercontent.com/15905797/97321817-2bc59800-1867-11eb-95fc-6cf325ec0392.png)](https://github.com/Templarian/MaterialDesign/files/5446225/oven.zip)[![cooker](https://user-images.githubusercontent.com/15905797/97321748-1d777c00-1867-11eb-9778-6d668d628436.png)](https://github.com/Templarian/MaterialDesign/files/5446226/cooker.zip)

Will try and sort some things out for the symbols in a bit. 👍

**Comment by GreenTurtwig** [comment]
Don't particually like these, fan and light especially, probably need to increase the box to 20x20.  
![oven-bottom](https://user-images.githubusercontent.com/15905797/97371692-bd55f980-18a9-11eb-979d-29c20a137065.png)![oven-top-bottom](https://user-images.githubusercontent.com/15905797/97371718-d1016000-18a9-11eb-8a88-c4abc2edb194.png)![oven-grill](https://user-images.githubusercontent.com/15905797/97371741-e2e30300-18a9-11eb-9ffb-946b726195c7.png)![oven-grill-bottom](https://user-images.githubusercontent.com/15905797/97371762-f2fae280-18a9-11eb-92c0-5562a2ec185f.png)![oven-grill-fan](https://user-images.githubusercontent.com/15905797/97371806-0443ef00-18aa-11eb-832a-4b642c92d4eb.png)![oven-fan](https://user-images.githubusercontent.com/15905797/97371831-13c33800-18aa-11eb-86ae-0bb166f0f7bd.png)![oven-light](https://user-images.githubusercontent.com/15905797/97371845-1e7dcd00-18aa-11eb-8914-836386e9e39f.png)

**Comment by Xenomorph99** [comment]
I think you did a great job. I think they work, but I agree 20x20 box would probably be best.

**Comment by Youpimatin** [comment]
Hi, I'm not a designer but maybe I can help, so I came with these designs for a built-in oven icon :
![Four2](https://user-images.githubusercontent.com/55438591/97872281-1690b380-1d16-11eb-8962-f2ef8966ea67.png)
![Four3](https://user-images.githubusercontent.com/55438591/97872293-18f30d80-1d16-11eb-8b36-64a72a7e6b12.png)
![Four4](https://user-images.githubusercontent.com/55438591/97872297-1b556780-1d16-11eb-8a67-01b9e23770fe.png)

With a preference for the second one :)

**Comment by Youpimatin** [comment]
Not vectorial, but more icon-style :

![Four5](https://user-images.githubusercontent.com/55438591/97883747-8d817880-1d25-11eb-847f-994ea0a897ae.png)

**Comment by I-Simen-I** [comment]
> Hi, I'm not a designer but maybe I can help, so I came with these designs for a built-in oven images (not icon-sized) :
> ![Four2](https://user-images.githubusercontent.com/55438591/97872281-1690b380-1d16-11eb-8962-f2ef8966ea67.png)
> ![Four3](https://user-images.githubusercontent.com/55438591/97872293-18f30d80-1d16-11eb-8b36-64a72a7e6b12.png)
> ![Four4](https://user-images.githubusercontent.com/55438591/97872297-1b556780-1d16-11eb-8a67-01b9e23770fe.png)
> 
> With a preference for the second one :)

Had been nice with an option illustrate a steam oven :) same style, but with a steam-symbol or something

**Comment by Youpimatin** [comment]
Something like this ?

![Four10](https://user-images.githubusercontent.com/55438591/98097871-e4a25d00-1e8d-11eb-9e53-8a67153450a2.png)

**Comment by I-Simen-I** [comment]
Excample on a steam icon 
![steam](https://user-images.githubusercontent.com/7014388/98127795-635fc000-1eb7-11eb-84a6-3a99300eaea5.png)

**Comment by goyney** [comment]
[![stove](https://materialdesignicons.com/icon/stove)](https://materialdesignicons.com/icon/stove)

**Comment by jormercury** [comment]
In my view this is not the same, so not a duplicate. A stove or oven. The oven's I was referring to are stand alone. They do not have hob's. They have several functions for instance related to these icon's above: https://github.com/Templarian/MaterialDesign/issues/5592#issuecomment-717595773

To keep it simple, a solution would be to remove the hob's and feet on top and below the main image of the oven.
