### ISSUE TITLE
clock-actions

### ISSUE THREAD

**Issue by dylanoli** [Templarian/MaterialDesign#5593]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/20401971/97094405-25e37300-162b-11eb-82f0-53d9e387b19d.png)
![image](https://user-images.githubusercontent.com/20401971/97094460-4a3f4f80-162b-11eb-873b-e6052d8d0912.png)
![image](https://user-images.githubusercontent.com/20401971/97094474-59260200-162b-11eb-8b76-9d28b6a1266e.png)

## Zip Download
[icons.zip](https://github.com/Templarian/MaterialDesign/files/5433844/icons.zip)

**Comment by Templarian** [comment]
@dylanoli The clocks look great, but all icons face the right. One will need to flip them. All of the first party libraries support this as do almost all third party icon components.

**Comment by dylanoli** [comment]
it's looking good now?
thanks for the tip with the truck icons, I will use the icons that already exist in the library

**Comment by dylanoli** [comment]
Hi! @Templarian are these icons ok?

**Comment by goyney** [comment]
[![clock-plus](https://materialdesignicons.com/icon/clock-plus)](https://materialdesignicons.com/icon/clock-plus)[![clock-plus-outline](https://materialdesignicons.com/icon/clock-plus-outline)](https://materialdesignicons.com/icon/clock-plus-outline)
[![clock-minus](https://materialdesignicons.com/icon/clock-minus)](https://materialdesignicons.com/icon/clock-minus)[![clock-minus-outline](https://materialdesignicons.com/icon/clock-minus-outline)](https://materialdesignicons.com/icon/clock-minus-outline)
[![clock-remove](https://materialdesignicons.com/icon/clock-remove)](https://materialdesignicons.com/icon/clock-remove)[![clock-remove-outline](https://materialdesignicons.com/icon/clock-remove-outline)](https://materialdesignicons.com/icon/clock-remove-outline)
