### ISSUE TITLE
Back Yard Icons

### ISSUE THREAD

**Issue by brianm71** [Templarian/MaterialDesign#5595]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icons to represent the back yard area for use in home assistant.  For example, I have a "front yard" and "back yard" areas.  The other areas of the house (1st floor, second floor, etc..) are all represented by a fairly self-explanatory icon, but there really aren't any icons in this set to represent outside areas such as front yard, back yard, shed and garden.

Suggestion is for:
Back Yard

## Examples
https://thenounproject.com/search/?q=back+yard&i=199287 (back yard)

**Comment by goyney** [comment]
The proposed example would not work with [Material Guidelines](https://material.io/design/iconography/system-icons.html#system-icon-metrics). We have plenty of other icons that could potentially represent a yard. Try searching for grass, tree, etc.
