### ISSUE TITLE
Shed Icon

### ISSUE THREAD

**Issue by brianm71** [Templarian/MaterialDesign#5596]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icons to represent the outside shed area for use in home assistant.  For example, I have a "front yard" and "back yard" areas.  The other areas of the house (1st floor, second floor, etc..) are all represented by a fairly self-explanatory icon, but there really aren't any icons in this set to represent outside areas such as a shed.

Suggestion is for:
Shed

## Examples
https://thenounproject.com/search/?q=shed&i=1586870 (shed)

**Comment by goyney** [comment]
I think `greenhouse` might fit this.

[![greenhouse](https://materialdesignicons.com/icon/greenhouse)](https://materialdesignicons.com/icon/greenhouse)

**Comment by goyney** [comment]
Added `shed` alias to `greenhouse`.
