### ISSUE TITLE
folder icons ( emacs neotree) 

### ISSUE THREAD

**Issue by siduck76** [Templarian/MaterialDesign#5598]
I like the default folder icons from material fonts  , but it'd be great if the folder icons get a lil modified like these  
![emacs folders0](https://user-images.githubusercontent.com/59060246/97140252-2f332380-1782-11eb-8c37-41ee13240e74.png) ![atom](https://user-images.githubusercontent.com/59060246/97140137-ff841b80-1781-11eb-99c8-27fbf41d90ef.png)
com/59060246/97140126-fbf09480-1781-11eb-9843-43cc90e9ee09.png)

my current one looks like this

![image](https://user-images.githubusercontent.com/59060246/97140188-14f94580-1782-11eb-93b1-9bce8fbb309c.png)

**Comment by goyney** [comment]
Those folders aren't Material, so we would not be able to consider this change.

**Comment by siduck76** [comment]
> Those folders aren't Material, so we would not be able to consider this change.

I mean the folder icon on this can be modified a lil 

![image](https://user-images.githubusercontent.com/59060246/97340305-9f889480-18a9-11eb-909d-b90ae3f6ce0f.png)

**Comment by goyney** [comment]
No.
