### ISSUE TITLE
Copyright, Trademark and Registered Trademark?

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#560]
Would be nice to have these icons in the material design style.
- [x] Copyright ©
- [ ] Trademark ™
- [ ] Registered trademark ®

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/43753942-39d51216-99d6-11e8-90a0-44d55a714de6.png) ![image](https://user-images.githubusercontent.com/1015040/43753948-46ddd790-99d6-11e8-9ea8-935653e02d39.png)

**Source:** [trademark.zip](https://github.com/Templarian/MaterialDesign/files/2264948/trademark.zip)

**Comment by Templarian** [comment]
[![trademark](https://materialdesignicons.com/icon/trademark)](https://materialdesignicons.com/icon/trademark) [![registered-trademark](https://materialdesignicons.com/icon/registered-trademark)](https://materialdesignicons.com/icon/registered-trademark)
