### ISSUE TITLE
Copy SVG icon content to clipboard

### ISSUE THREAD

**Issue by quyleanh** [Templarian/MaterialDesign#5601]
How can I do quick copy SVG icon content to clipboard?

For example when I do copy instead of download, the clipboard content will be something like this
```svg
<svg fill="none" viewBox="0 0 24 24" height="24" width="24" xmlns="http://www.w3.org/2000/svg">
<path xmlns="http://www.w3.org/2000/svg" fill-rule="evenodd" clip-rule="evenodd" d="M12 4C12.5523 4 13 4.44772 13 5V16.5858L17.2929 12.2929C17.6834 11.9024 18.3166 11.9024 18.7071 12.2929C19.0976 12.6834 19.0976 13.3166 18.7071 13.7071L12.7071 19.7071C12.3166 20.0976 11.6834 20.0976 11.2929 19.7071L5.29289 13.7071C4.90237 13.3166 4.90237 12.6834 5.29289 12.2929C5.68342 11.9024 6.31658 11.9024 6.70711 12.2929L11 16.5858V5C11 4.44772 11.4477 4 12 4Z" fill="#282828"></path>
</svg>
```

**Comment by Templarian** [comment]
The new website will have this feature! Can't wait to get it online. Just use the chrome/firefox extension for now.

https://chrome.google.com/webstore/detail/materialdesignicons-picke/edjaedpifkihpjkcgknfokmibkoafhme 

![image](https://user-images.githubusercontent.com/338885/97251885-c0cc8080-17d6-11eb-83c6-2ea2deddf2b0.png)

The Desktop cheatsheet actually has this feature also: https://github.com/Templarian/MaterialDesign-Font (similar code as the desktop, it includes an invisible 24x24 transparent rectangle to make pasting into software and aligning easier).

**Comment by quyleanh** [comment]
Thanks. I will wait for new UI website.

**Comment by siburny** [comment]
Granted it's not the exact functionality you are asking about, but you can do it now like this:
1) Go to website and click on the icon
2) Click the code button:
![image](https://user-images.githubusercontent.com/1232281/99705410-aef19c80-2a67-11eb-9b2d-2818c3e0910b.png)
3) Select `View SVG` menu option and see the full SVG code:
![image](https://user-images.githubusercontent.com/1232281/99705317-92556480-2a67-11eb-960f-789334166a15.png)
4) Select all and copy 👍
