### ISSUE TITLE
"Dog Not Allowed" icon

### ISSUE THREAD

**Issue by tomaszchabinka** [Templarian/MaterialDesign#5603]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Sometimes dogs are not allowed in some spaces or context, e.g. in some parks or shops. There's no icon at the moment to be used to mark this.

## Examples

crossed [dog side icon](https://materialdesignicons.com/icon/dog-side)

**Comment by Xenomorph99** [comment]
Here's our standard `-off` modifier. Will this suit your need?

![dog-side-off](https://user-images.githubusercontent.com/1837101/97612217-c4315900-19dc-11eb-89a8-f22c7cdd42af.png)
[dog-side-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/5460347/dog-side-off.svg.zip)

**Comment by tomaszchabinka** [comment]
Hey Henomorph99,
yes, it looks nice! By "standard" I understand you still need to add it to the catalog - it's not "autogenerated" in some way if I just use the "dog-side-off" identifier in my JavaScript library

**Comment by Xenomorph99** [comment]
You're correct. They're not autogenerated. I just added it to the library.

**Comment by tomaszchabinka** [comment]
Thanks, really appreciate it!
