### ISSUE TITLE
why my svg icon that build by inkscape including many labels , such as <text> , more <path > 

### ISSUE THREAD

**Issue by sytpb** [Templarian/MaterialDesign#5605]
I have check some icon's svg codec . that is simple , short . but my svg file is complicated，have <text> more than one <path> ...

I just want to a 24px*24px  svg .    like MD's svg format . one path only ...  

my svg code as 

`<svg width="24" height="24" version="1.1" viewBox="0 0 6.35 6.35" xmlns="http://www.w3.org/2000/svg">
 <defs>
  <clipPath id="clipPath114">
   <path d="m12.209.56055v23.084h11.533v-23.084zm7.6309 10.307c.14646-.0083.21728.16614.03906.31836-.20844.17804-.41968.35276-.61914.54102-.07451.03042-.10069.1068-.15234.1582-.02481.02469-.05212.04688-.07813.07031-.17493.11785-.28831.29127-.41211.45703-.03912.05237-.08106.10262-.12109.1543-.02545.03109-.05535.05939-.07617.09375-.07833.12918-.31361.57391-.38672.7168-.02482.0485-.04849.09746-.07227.14648.0041.06069-.01263.1532-.04492.19336-.02386.02968-.05452.05182-.08203.07813-.04482.0067-.08994.01288-.13476.01953-.1487.02211-.06785-.06818.01953-.1582-.0176-.0065-.0426-.02237-.04297-.05664-.02537-.01341-.05648-.01809-.07813-.03711-.02242-.01971.0205-.05501.0332-.08203.16052-.3419.34876-.69837.54492-1.0195.01949-.03192.04857-.05898.07227-.08789.17825-.22936.33341-.48538.57422-.65625.08906-.0727-.000695.0052.09766-.09766.04175-.04368.08495-.08549.12891-.12695.20183-.19043.41607-.3687.62695-.54883.0594-.05074.11524-.07339.16406-.07617zm-2.1641 2.7324c.02101.0111.04209.02219.06445.03125.01236-.01263.01811-.02136.0293-.0332-.03191-.02462-.06572-.04575-.09766-.07031-.004.0011-.0078.0028-.01172.0039-.0023.0039-.0056.0077-.0078.01172.02314.02547.02327.04077.02344.05664zm.06445.03125c-.0092.0094-.01222.01585-.02148.02539.0071.0026.05091.0032.08008.0039-.02071-.0079-.03814-.02101-.05859-.0293z" fill="#f00"/>
  </clipPath>
 </defs>
 <text transform="scale(.77081 1.2973)" x="-0.028795449" y="4.5959597" fill="#000000" font-family="sans-serif" font-size="8.214px" stroke-width=".20535" style="line-height:1.25" xml:space="preserve"><tspan x="-0.028795449" y="4.5959597" stroke-width=".20535">s</tspan></text>
 <path transform="scale(.26458)" d="m12.209.56055v23.084h2.4004v-10.736c-.07769-.05706-.12219-.11028-.0078-.04492.0049.0028.0037-.0017.0078 0v-.33594h.0059c8.6e-5-.0052 7.8e-5-.01042 0-.01563-.000563-.02741-.000163-.05467 0-.08203 2.6e-5-.0059-5.2e-5-.01172 0-.01758-1.6e-5-.02621-6e-6-.05206 0-.07813 9e-5-.0051 2.5e-5-.0104 0-.01563 9e-6-.02511 3e-6-.05078 0-.07617-.005-.02621-.01258-.057-.0078-.06445.0043-.0067.0038-.0037.0078-.0098v-1.6816c.000885.0066.0021.01294-.002.01758-.0043.005-.0072-.0095-.0098-.01563-.008-.01931-.01438-.04089-.02149-.06055-.01081-.05014-.0066-.09814.01563-.14453.0046-.0096-.0063.01917-.0098.0293-.000613.0018-.0014.0077-.002.0059-.0011-.0039.000264-.0077 0-.01172-.0029-.03473-.0022-.07066-.002-.10547-7.8e-5-.02805-4e-6-.05594 0-.08398-.0027-.0021-.0072-.0016-.0098-.0039-.04743-.04306-.02762-.13195-.01953-.17969-.0042-.014997-.0022-.056418-.002-.080078.000652-.030875 5.2e-5-.060918 0-.091797 1.8e-5-.031654 7e-6-.064031 0-.095703-6e-6-.01474 0-.030182 0-.044922 0-.083622.02343-.14082.05664-.17969v-6.1524h9.1328v-2.7285z" clip-path="url(#clipPath114)"/>
 <ellipse cx="4.9436" cy="3.145" rx="1.1117" ry="1.0478" fill="#f00" fill-rule="evenodd" stroke-width=".32412"/>
</svg>`

**Comment by goyney** [comment]
We're not really a resource for teaching you how to use _x_ application. You need to figure out how to combine all the paths into a single, compound path. I'd recommend searching Google for "inkscape compound path".

**Comment by sytpb** [comment]
ok  , got it , thanks a lot !
