### ISSUE TITLE
NVM... *not* shutting down the CDN

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#5608]
NVM, we've moved over everything to https://www.jsdelivr.com/ in the background. So the CDN will keep functioning.

We still recommend using https://www.jsdelivr.com/package/npm/@mdi/font directly rather than `cdn.materialdesignicons.com`.

--------

As our sponsorship comes to an end we are making the decision to shutdown the CDN. As it currently only houses the webfont we are going to be creating a repo with backups of all the previously stored versions.

- https://github.com/Templarian/MaterialDesign-Webfont/
- `<we're still moving the previews to github pages>`

**MaxCDN has sponsored us for nearly 6 years (now StackPath). 🥰**

> There is one stat I want to share... 45TB a month. That's a lot of data and an uncountable amount of websites.

**Q.** I use the CDN how can I prevent the icons from disappearing?
**A.** Two Options:
 - Switch to https://www.jsdelivr.com/package/npm/@mdi/font
 - Find the version you are currently using and download the matching version from the repository listed above and self host the files on your server.

**Q.** Are there any alternatives to the webfont? 
**A.** Yes. We provide [@mdi/js](https://www.npmjs.com/package/@mdi/js) for Javascript based projects which provides all icons as an SVG path that can be injected into an inline SVG element. We also provide [@mdi/svg](https://www.npmjs.com/package/@mdi/svg) which provides all icons as SVG files.

**Q.** I use a theme that was making a request to the CDN.
**A.** You will need to let the theme author know. Link them here and hopefully they can update the theme or host the files as part of the theme.

**Q.** How do I know if I'm using the CDN?
**A.** Open your developer console in your browser and click the network tab. If you see a request to `cdn.materialdesignicons.com` you will need to follow the steps above.

**Q.** Why don't you keep the CDN online?
**A.** Financially it's not something we can maintain and there are better options now-a-days.

**Q.** Won't this break a lot of the web?
**A.** Yes, but we hope people realize there is no easy way to inform every website of the CDN shutdown.

**Comment by jimaek** [comment]
Hey, there are definitely options to fix this without breaking any website. I PMed you on Twitter. jsDelivr can definitely help out

**Comment by Templarian** [comment]
We might have this fixed thanks to @jimaek. We're waiting for the DNS to propagate.

**Comment by Templarian** [comment]
All the docs have been updated to point at jsdelivr. We also spun up new URLs for previewing the releases:

Example: https://pictogrammers.github.io/@mdi/font/5.8.55/

I'll leave this open until I've 100% closed down the current CDN.

**Comment by Templarian** [comment]
Everything was migrated with almost no downtime, so closing out this issue.
