### ISSUE TITLE
library-video icon

### ISSUE THREAD

**Issue by alenz316** [Templarian/MaterialDesign#561]
Google has a library-music icon, so a library-video icon would great addition

**Comment by CoDEmanX** [comment]
From YouTube:
![screenshot_2015-07-24-19-05-15 2](https://cloud.githubusercontent.com/assets/1309249/8996788/181077a4-371b-11e5-80f8-c5deb40518db.png)

But there's also a video_library icon in their repository / on their page:
https://www.google.com/design/icons/#ic_video_library

**Comment by PeterShaggyNoble** [comment]
The YouTube one is the stock [`subscriptions` icon](https://material.io/icons/#ic_subscriptions).

**Comment by PeterShaggyNoble** [comment]
There's also `video library` in the stock set and `library movies` in the extended set.

[![video library](https://user-images.githubusercontent.com/15157491/37217450-704a32be-23b5-11e8-8eb4-e718d3ca1b0f.png)](https://material.io/icons/#ic_video_library) ![library movies](https://user-images.githubusercontent.com/15157491/37217417-59bac4d2-23b5-11e8-8886-2f61d4869af8.png)

**Comment by Templarian** [comment]
These were added the other day. Forgot to close this one.
