### ISSUE TITLE
get Power from Grid and send Power to Grid

### ISSUE THREAD

**Issue by mla4ger** [Templarian/MaterialDesign#5613]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have a solar system and i would like to visualize:
- buy Power from grid
- send Power to grid

## Examples
You have allready an icon for the grid (transmission-tower).
Use this and add only an incomming or outcomming arrow.
That would be my suggestion.

Thanks a lot.

**Comment by dpeter99** [comment]
I think this could be extended to all modifiers for the ``transmission-tower`` icon just to cover future requests.

**Comment by goyney** [comment]
This is WIP. We're discussing arrow placement and naming for these:

![image](https://user-images.githubusercontent.com/1015040/133159024-c3ad66e2-1933-461c-a530-6c889ffee922.png)![image](https://user-images.githubusercontent.com/1015040/133159041-bba54eda-61a7-4b08-b8c5-db97e05204f7.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7157452/Archive.zip)

**Comment by goyney** [comment]
[![transmission-tower-import](https://materialdesignicons.com/icon/transmission-tower-import)](https://materialdesignicons.com/icon/transmission-tower-import)[![transmission-tower-export](https://materialdesignicons.com/icon/transmission-tower-export)](https://materialdesignicons.com/icon/transmission-tower-export)
