### ISSUE TITLE
street light

### ISSUE THREAD

**Issue by sirinimal** [Templarian/MaterialDesign#5614]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Xenomorph99** [comment]
@sirinimal, can you provide an example image?

**Comment by goyney** [comment]
Closing since the Needs More Info label was added over 2 weeks ago without a response.
