### ISSUE TITLE
Patio door (open/closed)

### ISSUE THREAD

**Issue by I-Simen-I** [Templarian/MaterialDesign#5617]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Illustrate that a patio door is open or not in Home Assistant.

### patio-door
![patio_door](https://user-images.githubusercontent.com/7014388/98028311-37d4cb00-1e0e-11eb-97ee-ea2e173ea981.png)
### patio-door-open
![patio_door_open](https://user-images.githubusercontent.com/7014388/98028315-386d6180-1e0e-11eb-9a5a-ab3a964497a7.png)

**Comment by ctrl50** [comment]
Definitely needed!

**Comment by goyney** [comment]
[![door-sliding](https://materialdesignicons.com/icon/door-sliding)](https://materialdesignicons.com/icon/door-sliding)[![door-sliding-open](https://materialdesignicons.com/icon/door-sliding-open)](https://materialdesignicons.com/icon/door-sliding-open)[![door-sliding-lock](https://materialdesignicons.com/icon/door-sliding-lock)](https://materialdesignicons.com/icon/door-sliding-lock)
