### ISSUE TITLE
Swab test icon

### ISSUE THREAD

**Issue by Mhsmit** [Templarian/MaterialDesign#5618]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Indication of a type of medical treatment / medical test. 

## Examples
a testtube with a cotton swab

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/16267033/98098890-3697b280-1e8f-11eb-90f1-f01b640d7fda.png)

**Comment by goyney** [comment]
Google seems to have an answer for this:

![image](https://user-images.githubusercontent.com/1015040/131537852-5cc161ca-6184-4c26-8b0d-c42ea8fdca8e.png)
[medication_liquid_black_24dp.svg.zip](https://github.com/Templarian/MaterialDesign/files/7085326/medication_liquid_black_24dp.svg.zip)

**Comment by JamesCoyle** [comment]
Could maybe do to make the swab look less spoon like.

**Comment by goyney** [comment]
[![medical-cotton-swab](https://materialdesignicons.com/icon/medical-cotton-swab)](https://materialdesignicons.com/icon/medical-cotton-swab)
