### ISSUE TITLE
Account Arrow Modifiers

### ISSUE THREAD

**Issue by bnping** [Templarian/MaterialDesign#5619]
I am looking for mdi-account-multiple-arrow-down icon in Material Design Icons to be used in vuetify project but thier is only mdi-account-multiple-plus.
Thanks.

**Comment by Xenomorph99** [comment]
I took a look at our existing `account-arrow-` icons and I noticed that the modifier mask has a big and somewhat strange radius. I took the liberty of creating updated ones and included them in the Zip file below.

These two examples show the difference (blue is the updated icon and red is the current icon):

![account-arrow-left](https://user-images.githubusercontent.com/1837101/98152072-61cdd200-1e8e-11eb-87ad-df4c8dd5079d.png)
![account-arrow-left-outline](https://user-images.githubusercontent.com/1837101/98152069-61353b80-1e8e-11eb-9e65-5c8105197c32.png)

## Updated Icons

![account-arrow-left](https://user-images.githubusercontent.com/1837101/98152516-18ca4d80-1e8f-11eb-8545-9fa3034c4163.png)
![account-arrow-right](https://user-images.githubusercontent.com/1837101/98152521-1a941100-1e8f-11eb-8436-5185d8521c67.png)
![account-arrow-left-outline](https://user-images.githubusercontent.com/1837101/98152545-25e73c80-1e8f-11eb-906d-d68bd43e3e7b.png)
![account-arrow-right-outline](https://user-images.githubusercontent.com/1837101/98152546-267fd300-1e8f-11eb-89a4-b50b6dcbadef.png)

## New Icons

### `account-arrow-*`

![account-arrow-up](https://user-images.githubusercontent.com/1837101/98152525-1bc53e00-1e8f-11eb-8725-703c62714d2e.png)
![account-arrow-down](https://user-images.githubusercontent.com/1837101/98152508-1667f380-1e8f-11eb-8b68-d0f953275a7f.png)
![account-arrow-up-outline](https://user-images.githubusercontent.com/1837101/98152547-267fd300-1e8f-11eb-8cd8-1f88c1ae9453.png)
![account-arrow-down-outline](https://user-images.githubusercontent.com/1837101/98152544-254ea600-1e8f-11eb-9d49-f076e7cf2879.png)

### `account-multiple-arrow-*`

![account-multiple-arrow-left](https://user-images.githubusercontent.com/1837101/98152637-4adbaf80-1e8f-11eb-996a-16156e45e6c7.png)
![account-multiple-arrow-right](https://user-images.githubusercontent.com/1837101/98152644-4b744600-1e8f-11eb-9b10-91d64c3af70b.png)
![account-multiple-arrow-up](https://user-images.githubusercontent.com/1837101/98152647-4c0cdc80-1e8f-11eb-83d5-eb2ac376aee3.png)
![account-multiple-arrow-down](https://user-images.githubusercontent.com/1837101/98152634-4a431900-1e8f-11eb-9c15-5fae0bdd1290.png)
![account-multiple-arrow-left-outline](https://user-images.githubusercontent.com/1837101/98152636-4a431900-1e8f-11eb-8bbd-91cde7151b01.png)
![account-multiple-arrow-right-outline](https://user-images.githubusercontent.com/1837101/98152641-4adbaf80-1e8f-11eb-809f-2f43838f5ef4.png)
![account-multiple-arrow-up-outline](https://user-images.githubusercontent.com/1837101/98152645-4b744600-1e8f-11eb-9a07-6894580b6660.png)
![account-multiple-arrow-down-outline](https://user-images.githubusercontent.com/1837101/98152633-49aa8280-1e8f-11eb-9a43-a87063894793.png)

## Zip file

[account-arrow.zip](https://github.com/Templarian/MaterialDesign/files/5489738/account-arrow.zip)

**Comment by Templarian** [comment]
We might not be able to do cutouts for multiple on these, but thinking arrows to the left might convey something different. 🤔

**Comment by Xenomorph99** [comment]
They would work better if we flipped them.

![account-multiple-arrow-right](https://user-images.githubusercontent.com/1837101/98196189-b69a3880-1ee0-11eb-8f02-9912df91e11f.png)
![account-multiple-arrow-right-outline](https://user-images.githubusercontent.com/1837101/98196188-b601a200-1ee0-11eb-95e4-0601c16f4345.png)

**Comment by binarynoise** [comment]
I'd also suggest a combination with the download icon, eg for downloading account or people  related stuff.
&nbsp;

> They would work better if we flipped them.  

This would also fix the very tiny shoulder of the second person

**Comment by goyney** [comment]
Updated and added the single account up and down icons. Decided to hold off on the multiple because they don't fit our current modifier pattern for those icons and I'm not a fan of flipping the icon for certain modifiers and not for others.
