### ISSUE TITLE
doing angular-material 'grunt build' shows the wrong icons?

### ISSUE THREAD

**Issue by jeffthompson1971** [Templarian/MaterialDesign#562]
using angular-material along with mdi.    works perfect on development mode (i.e. grunt serve)

so this works fine:
 <i class="mdi  mdi-map-marker-circle md-accent s36 md-avatar"></i>

i actually see the map-marker-circle icon... duh right?

then i only do 'grunt build' which does the minification and such and puts in /dist - the standard stuff.. only when that's done all the icons are shifted somehow.   so this map one shows an upside down triangle.    i used another icon for a chat icon and that one turns into the 'phone fowared' icon.

how is this possible?   how could touching NO code but only doing a prod build make all the icons not match the names anymore?? anyone?  totally stumped and no clue how to debug it

**Comment by Templarian** [comment]
That an interesting one. The class name is matching: `class="mdi mdi-map-marker-circle"` perfectly?

The character position changes every single version, that is why SASS is recommended or the pre-compiled CSS (which is directly generated from SASS latest). The background font generation system is actually all grunt.

I use these icons in production with/without grunt build steps and they work good.

**Comment by Templarian** [comment]
If you are using sass and need `content: \f100` type support use the code example on (under the SASS heading):

https://materialdesignicons.com/getting-started

**Comment by Templarian** [comment]
I'm going to mark this as resolved since I haven't heard anything back. Let me know if this is not the case and I'll reopen the issue.

**Comment by stephenycchang** [comment]
I'm having a similar problem with Grunt. 
Using the mdi bower package with Yeoman Angular. 

Development, everything shows. However, on production, I'll get 404s on the files since it's looking for file in the specifc "styles/fonts/materialdesignicons-webfont....?v=1.2.64"". It makes sense since Grunt will minify the files to a vendor.css file. 

Is there a workaround to get this to work with Grunt?
