### ISSUE TITLE
[UPDATE] Gmail

### ISSUE THREAD

**Issue by shmshd** [Templarian/MaterialDesign#5620]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![gmail](https://user-images.githubusercontent.com/11484121/98205642-eafa0d00-1f51-11eb-801d-d14319c6fcbc.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[gmail.zip](https://github.com/Templarian/MaterialDesign/files/5492378/gmail.zip)

**Comment by goyney** [comment]
I am of the opinion that we should actually remove this icon. We do not have icons for other email providers and would not add them under our current brand icon policy.

**Comment by Templarian** [comment]
We have the office suite of applications that includes `microsoft-outlook`. 🤔

**Comment by shmshd** [comment]
so, `gmail` and, `microsoft-outlook` will also be removed due to the current brand icon policy?

**Comment by Templarian** [comment]
Possibly, we definitely don't need gmail in the pack. We have the office suite icons since they get used a lot in menus.
