### ISSUE TITLE
Surround Sound 2.1

### ISSUE THREAD

**Issue by ddppddpp** [Templarian/MaterialDesign#5622]
Please add an icon for a 2.1 speaker (L, R, bass/subwoofer) surround sound system.

I have:

- [*] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [*] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [*] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A 2.1 Speaker Surround Sound System can be used in relation to an audio system. Currently there are icons for 2.0 (stereo), 3.1 (left, right, center, subwoofer), 7.1.

## Examples

similar to the icon surround-sound-3-1

Thanks in advance!

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/98421128-94d7b780-2080-11eb-8a95-1e6d8f1c5354.png)](https://github.com/Templarian/MaterialDesign/files/5503804/surround-sound-2-1.zip)

**Comment by ddppddpp** [comment]
looks great! not sure should I close the issue...

**Comment by Templarian** [comment]
@ddppddpp Nah, @GreenTurtwig will when they add it into the system.

**Comment by GreenTurtwig** [comment]
Sorry this took so long!

[![Surround Sound 2.1](http://materialdesignicons.com/icon/surround-sound-2-1)](http://materialdesignicons.com/icon/surround-sound-2-1)
