### ISSUE TITLE
Surround Sound 5.1.2

### ISSUE THREAD

**Issue by ddppddpp** [Templarian/MaterialDesign#5623]
Please add an icon for a 5.1.2 speaker (Front Left, Center, Front Right, Surround Left, Surround Right, Subwoofer, Height Left, Height Right) surround sound system.

I have:

- [*] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [*] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [*] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A 5.1.2 Speaker Surround Sound System can be used in relation to an audio system. Currently there are icons for 3.1, 5.1 and 7.1.

## Examples

similar to the icon surround-sound-7-1, surround-sound-5-1

Thanks in advance!

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/98421567-89d15700-2081-11eb-801c-646c1ff630ea.png)](https://github.com/Templarian/MaterialDesign/files/5503828/surround-sound-5.1.2.zip)
The amount of characters is really pushing it here.

**Comment by GreenTurtwig** [comment]
[![Surround Sound 5.1.2](http://materialdesignicons.com/icon/surround-sound-5-1-2)](http://materialdesignicons.com/icon/surround-sound-5-1-2)
