### ISSUE TITLE
calendar-clock-outline

### ISSUE THREAD

**Issue by StereoMissile** [Templarian/MaterialDesign#5624]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

`calendar` is a good representation for 'date', 
`clock` for 'time'. 
`calendar-clock` is  really good for 'datetime' since it's bringing both in the same icon.

Calendar clock is, however, missing an outline style to bring it in line with the other date/time icons.

## Examples

![calendar-blank-outline](https://user-images.githubusercontent.com/43047330/98287902-08d86980-1f74-11eb-9082-ebf418241178.png)
![calendar-clock](https://user-images.githubusercontent.com/43047330/98287904-09710000-1f74-11eb-88dd-46b68be44154.png)

**Comment by GreenTurtwig** [comment]
🐱
[![](https://materialdesignicons.com/icon/calendar-clock-outline)](https://materialdesignicons.com/icon/calendar-clock-outline)
