### ISSUE TITLE
Update surround sound icons

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#5627]
All use different character designs than other icons, updated so they're consistent.
[![](https://materialdesignicons.com/icon/surround-sound-2-0)](https://materialdesignicons.com/icon/surround-sound-2-0)![](https://user-images.githubusercontent.com/15905797/98421813-2562c780-2082-11eb-810b-153e3ec10ef3.png)
[![](https://materialdesignicons.com/icon/surround-sound-3-1)](https://materialdesignicons.com/icon/surround-sound-3-1)![](https://user-images.githubusercontent.com/15905797/98421830-314e8980-2082-11eb-8028-164a2ab63c2b.png)
[![](https://materialdesignicons.com/icon/surround-sound-5-1)](https://materialdesignicons.com/icon/surround-sound-5-1)![](https://user-images.githubusercontent.com/15905797/98421849-3c091e80-2082-11eb-837b-fa7758fb697e.png)
[![](https://materialdesignicons.com/icon/surround-sound-7-1)](https://materialdesignicons.com/icon/surround-sound-7-1)![](https://user-images.githubusercontent.com/15905797/98421860-44f9f000-2082-11eb-89f5-401befcb5344.png)

**Comment by goyney** [comment]
Updated.
