### ISSUE TITLE
webcam-off

### ISSUE THREAD

**Issue by krasatos** [Templarian/MaterialDesign#5628]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

An icon to indicate that the webcamcam has been turned off. 
Will be used when camera is set to look the other way or when privacy mode is ON.

## Examples

Exactly like mdi:webcam ![webcam (1)](https://user-images.githubusercontent.com/1773624/98438358-406d2000-20f2-11eb-96ff-1a78b68ae3fb.png) but with a line crossing it out. (like camera off: ![camera-off](https://user-images.githubusercontent.com/1773624/98438367-49f68800-20f2-11eb-9976-ccb51c13123f.png))

Thank you.

**Comment by Xenomorph99** [comment]
![webcam-off](https://user-images.githubusercontent.com/1837101/98565996-7e418400-226b-11eb-8b5b-5335735b4ecc.png)
[webcam-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/5511725/webcam-off.svg.zip)

**Comment by goyney** [comment]
Added.

**Comment by krasatos** [comment]
A million thank yous!
