### ISSUE TITLE
Using only specific icons

### ISSUE THREAD

**Issue by vosidiy** [Templarian/MaterialDesign#5629]
Thanks to creators of material fonticons. is it possible to use icons which is only related to user interface?, I don't want to load all thousand icons just for small ecommerce project. 
I need to load only around 50 icons. I don't need animals, tools, objects...

Please give us an opportunity to download only important icons for small projects.

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/guide/webfont-alternatives

If you're stuck using the font you can use something like https://icomoon.io/ to generate a subset.

Our tooling currently doesn't exactly allow this, but we have a story to upgrade it. Once we update the tooling we could wrap it in a GUI, but we're still working on the new site first.

https://github.com/Templarian/MaterialDesign-Font-Build/issues/6
