### ISSUE TITLE
Horse Variant Fast

### ISSUE THREAD

**Issue by Sjoerd82** [Templarian/MaterialDesign#5632]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To make a distinction between a riding and a speeding/galloping horse.
My personal interest is to select between the two to present different calculations for each style in my app.

I believe it's both an easy to produce and useful icon to add to the already very beautiful MaterialDesign collection!

## Examples

Similar to run and run-fast, the current horse-alternative could be extended with three lines to indicate speed:

![image](https://user-images.githubusercontent.com/15013786/98540861-d76edf00-228e-11eb-90af-35cfd6ad6a74.png)

**Comment by Xenomorph99** [comment]
Personally, I don't think this icon looks very good. Even with breaking the 20 dps width convention, the "movement" lines don't feel long enough.

Let's get some feedback from other people.

![horse-variant-fast](https://user-images.githubusercontent.com/1837101/98566996-ac739380-226c-11eb-8da0-da285d579547.png)

[horse-fast.svg.zip](https://github.com/Templarian/MaterialDesign/files/5511788/horse-fast.svg.zip)

**Comment by Sjoerd82** [comment]
Most icons use these same three lines to indicate speed, and personally I don't think it looks bad. The only possible confusion might be that they might be seen as manes, instead of speed. However, an icon such as this is likely to be used among other icons with the same speed indication, mitigating that problem.

If the lines are moved up a bit, then they can be made slightly longer.

Alternatively, there are the speed lines as used in **truck-fast** that _could_ work. However, I would prefer the three lines as these are used everywhere and should probably considered the standard for denoting "speed".

**Comment by goyney** [comment]
[![horse-variant-fast](https://materialdesignicons.com/icon/horse-variant-fast)](https://materialdesignicons.com/icon/horse-variant-fast)

**Comment by Sjoerd82** [comment]
Thanks for adding, much appreciated!!
