### ISSUE TITLE
Circadian Lighting

### ISSUE THREAD

**Issue by danielbrunt57** [Templarian/MaterialDesign#5635]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home Assistant Circadian and Adaptive lighting integrations

## Examples

https://www.google.com/search?q=circadian+lighting+icon&rlz=1C1CHBD_enCA927CA927&sxsrf=ALeKk03kQGmyIKx1UA__Dj3JchXW3FZJMQ:1604984372510&tbm=isch&source=iu&ictx=1&fir=XORQgE73GwtYmM%252CaP0wdfgUsgATnM%252C_&vet=1&usg=AI4_-kTJ_iKfIojYN3UQXVM3TEEivEsRew&sa=X&ved=2ahUKEwiJvpLbmPfsAhVQGDQIHUn5DDAQ9QF6BAgIEAw#imgrc=XORQgE73GwtYmM

**Comment by goyney** [comment]
[![theme-light-dark](https://materialdesignicons.com/icon/theme-light-dark)](https://materialdesignicons.com/icon/theme-light-dark)
