### ISSUE TITLE
Add task

### ISSUE THREAD

**Issue by pedrokost** [Templarian/MaterialDesign#5636]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I need an icon for "Add task". This would create a new task into a task list.

## Examples

There is an icon in [material.io icon pack](https://material.io/resources/icons/?icon=add_task&style=baseline) that fulfills this perfectly.

![Screenshot from 2020-11-10 16-15-32](https://user-images.githubusercontent.com/725286/98693000-07da7a00-2370-11eb-904e-486cd9a9592d.png)

**Comment by steodor** [comment]
Hi, how about this?

![image](https://user-images.githubusercontent.com/4397338/99509948-21427e00-298f-11eb-95a4-639a33d59423.png)

**Comment by Xenomorph99** [comment]
@steodor your approach works, but I feel like this icon is trying to present way too much information all at once (circle, checkmark, and a plus icon). Also, `-check` and `-plus` are treated throughout the library as mutually exclusive modifiers. I wouldn't recommend adding this icon because it introduces a strange duality (e.g. Am I completing something or am I adding something?).

**Comment by steodor** [comment]
@Xenomorph99 you make a very good point, from the icon set's point of view indeed this icon doesn't make any sense, even though it does have real-world usage. I mean, more and more apps (e.g. JIRA - see subtasks icon, TickTick, etc.) are moving away from the clipboard as the idiom for task, towards the checkmark in some enclosure to make it distinct from save or success. A requirement for this kind of icon is bound to appear at some point, but right now it's not enough reason to change the library, i see that now. So as far as i'm concerned you can close this issue, no problem :) Thank you for your time!

@pedrokost if you still need this icon regardless of the explanations above, just let me know and i can give you the svg path so you can use it.

**Comment by pedrokost** [comment]
@steodor Thank you for taking the time to create that icon. I would appreciate the svg, it might come in useful, if you don't mind me using it for commercial purposes. You can contact me at github at pedro dot si

**Comment by steodor** [comment]
@pedrokost no need for the e-mail address :) here's a zip with the svg for the preview above: [add-task.zip](https://github.com/Templarian/MaterialDesign/files/5565731/add-task.zip)

**Comment by goyney** [comment]
We have precedence for multiple modifiers. While the name is a mouthful, this is a totally acceptable addition. Added.

[![checkbox-marked-circle-plus-outline](https://materialdesignicons.com/icon/checkbox-marked-circle-plus-outline)](https://materialdesignicons.com/icon/checkbox-marked-circle-plus-outline)
