### ISSUE TITLE
AR Icon - Augmented reality

### ISSUE THREAD

**Issue by dariocavada** [Templarian/MaterialDesign#5639]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Provide some context of how your icon could be used.

![example-1](https://user-images.githubusercontent.com/4304176/98910950-281b4d80-24c4-11eb-82f0-972d48aa96b4.jpg)

![example-2](https://user-images.githubusercontent.com/4304176/98910946-26518a00-24c4-11eb-9e15-84e941e03d3b.jpg)

## Examples

Include any example images so we know what the icon should look like.

<img width="508" alt="ar-icon-example" src="https://user-images.githubusercontent.com/4304176/98910934-22256c80-24c4-11eb-96e3-f45639440bc5.png">
<img width="508" alt="ar-icon-alternative" src="https://user-images.githubusercontent.com/4304176/98910940-25b8f380-24c4-11eb-94b4-44f1add5b02e.png">
<img width="84" alt="ar-icon-1" src="https://user-images.githubusercontent.com/4304176/98910943-26518a00-24c4-11eb-9949-338918e63cda.png">

**Comment by Templarian** [comment]
`cube-scan` is the icon you have above. Marking this as a duplicate unless you're looking for something else.
