### ISSUE TITLE
Linear Icons

### ISSUE THREAD

**Issue by SachinAgarwal1337** [Templarian/MaterialDesign#564]
How about adding linear icons?
for reference: https://linearicons.com/

**Comment by Templarian** [comment]
Please let us know which specific icons are missing from the pack.

Going to close this issue for now as it is too vague.

**Comment by SachinAgarwal1337** [comment]
@Templarian not missing any icons, I am referring to design of the icons.

**Comment by CoDEmanX** [comment]
None of them complies to the material design icon guidelines...

**Comment by Templarian** [comment]
Sorry @SachinAgarwal1337, what @CoDEmanX said. Material Design styled iconography only.

**Comment by SachinAgarwal1337** [comment]
Sorry, I dint knew. :)
