### ISSUE TITLE
Display cabinet

### ISSUE THREAD

**Issue by dangoodhead** [Templarian/MaterialDesign#5640]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

An icon for lights in a display cabinet.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@dangoodhead Can you include some examples. Please do not remove the issue template it's there for a reason.

**Comment by goyney** [comment]
Closing since the Needs More Info label was added over 2 weeks ago without a response.
