### ISSUE TITLE
lightbulb-group-on/lightbulb-group-on-outline

### ISSUE THREAD

**Issue by siburny** [Templarian/MaterialDesign#5643]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like to include "-on" modifier for `mdi-lightbulb-group` and `mdi-lightbulb-group-outline` similarly to `mdi-lightbulb-on` and `mdi-lightbulb-on-outline`.

## Examples

My crude mash up of two:
![image](https://user-images.githubusercontent.com/1232281/99410743-d0fcea80-28c0-11eb-8b27-f8ccf524c6c7.png)

**Comment by siburny** [comment]
Slightly better option:

![image](https://user-images.githubusercontent.com/1232281/99414180-91380200-28c4-11eb-9951-b3e03c555841.png)

**Comment by siburny** [comment]
`mdi-lightbulb-on` has fight little "rays" of lights. How about this?
![image](https://user-images.githubusercontent.com/1232281/99462322-6ae48780-2901-11eb-8e8c-4198aca62118.png)

**Comment by goyney** [comment]
I'm sorry, I'm not a fan of any of these. I just do not think there is enough room to do it properly.

**Comment by siburny** [comment]
Figured I would ask for the consistency sake 👍 
![image](https://user-images.githubusercontent.com/1232281/99550184-6dd68b00-2988-11eb-8d2e-a59ea085d896.png)

**Comment by goyney** [comment]
And what happens when only part of the group is illuminated? We don't have a way to indicate that. I feel that a group icon is fine to represent literal group of lights, but each individual state should be managed independently.

This is also a case where I never liked the lines coming out of the bulb. I feel that `outline` for off and filled for on would be sufficient. 🤷

**Comment by siburny** [comment]
Yes, agreed. I will switch to that (outline: off and filled: on) to make the UI consistent.
