### ISSUE TITLE
Gift Open & Gift Off

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5645]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![gift-open](https://user-images.githubusercontent.com/1837101/99439482-79677a80-28d2-11eb-8d05-40c09cd25163.png)
![gift-open-outline](https://user-images.githubusercontent.com/1837101/99439481-79677a80-28d2-11eb-9a1b-31f7bc793b57.png)
![gift-off](https://user-images.githubusercontent.com/1837101/99439476-78cee400-28d2-11eb-82b7-49213258c938.png)
![gift-off-outline](https://user-images.githubusercontent.com/1837101/99439474-78364d80-28d2-11eb-9c29-6b95a6d3c44c.png)

## Zip Download

[gift.zip](https://github.com/Templarian/MaterialDesign/files/5555850/gift.zip)

**Comment by Templarian** [comment]
Slash needs to go down a little further. But then good to add.

**Comment by Xenomorph99** [comment]
Like this? @Templarian

![gift-off](https://user-images.githubusercontent.com/1837101/99990733-6c82d500-2d71-11eb-820e-1d22f5158e86.png)
![gift-off-outline](https://user-images.githubusercontent.com/1837101/99990731-6bea3e80-2d71-11eb-814f-c4408cbf7418.png)
[gift-off.zip](https://github.com/Templarian/MaterialDesign/files/5584467/gift-off.zip)

**Comment by Xenomorph99** [comment]
Here's what it looks like if I extend the slash instead of shifting it down.

![gift-off](https://user-images.githubusercontent.com/1837101/99991739-a43e4c80-2d72-11eb-89f8-ed8b2a617823.png)
![gift-off-outline](https://user-images.githubusercontent.com/1837101/99991736-a3a5b600-2d72-11eb-95ca-bc9a2cc9f912.png)
[gift-off.zip](https://github.com/Templarian/MaterialDesign/files/5584513/gift-off.zip)

**Comment by Templarian** [comment]
I meant just extending it down. Generally we try to keep the slack always in the same location. Extending it down is a little clearer. 👍

**Comment by Xenomorph99** [comment]
Awesome. I added them to the library.
