### ISSUE TITLE
Turkey

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5646]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![turkey](https://user-images.githubusercontent.com/1837101/99463882-03740b00-28f4-11eb-9e09-a01fcc034db4.png)

## Zip Download

[turkey.svg.zip](https://github.com/Templarian/MaterialDesign/files/5556831/turkey.svg.zip)

**Comment by Xenomorph99** [comment]
Using [food-drumstick](https://materialdesignicons.com/icon/food-drumstick), I created a "cooked" turkey as well.

![turkey-cooked](https://user-images.githubusercontent.com/1837101/99701586-e05f6d80-2a51-11eb-9f54-2eb6bf2358b7.png)
[turkey-cooked.svg.zip](https://github.com/Templarian/MaterialDesign/files/5568617/turkey-cooked.svg.zip)

**Comment by Templarian** [comment]
Tese are nice additions I think. I can instantly tell what both are.

**Comment by Xenomorph99** [comment]
I went ahead and added these so we have them before Thanksgiving 😊
