### ISSUE TITLE
message-star / message-star-outline

### ISSUE THREAD

**Issue by steodor** [Templarian/MaterialDesign#5647]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## message-star / message-star-outline

Hi, we're currently using this icon as a combined rating + feedback icon, so it would make sense for the icons to be aliased with both `rating` and `feedback`. The styling is based off existing icons to preserve consistency.

This is my first contribution, so please let me know if there's something i can improve on in the future. I will also try to address existing icon requests but this pair seemed the most straightforward to submit/review/integrate as a first attempt.

Thank you for the great icons and ecosystem around them, it's awesome!

## Preview

![image](https://user-images.githubusercontent.com/4397338/99495004-a1aab400-297a-11eb-869d-26969da35511.png) ![image](https://user-images.githubusercontent.com/4397338/99495030-acfddf80-297a-11eb-98ba-19f1637715b2.png)

## Zip Download

[message-star.zip](https://github.com/Templarian/MaterialDesign/files/5558241/message-star.zip)

**Comment by Templarian** [comment]
Added a milestone so this doesn't get missed. Probably should have had it in the last release. 👍

**Comment by goyney** [comment]
[![message-star](https://materialdesignicons.com/icon/message-star)](https://materialdesignicons.com/icon/message-star)[![message-star-outline](https://materialdesignicons.com/icon/message-star-outline)](https://materialdesignicons.com/icon/message-star-outline)
