### ISSUE TITLE
Abacus

### ISSUE THREAD

**Issue by jpgilchrist** [Templarian/MaterialDesign#5648]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

When referencing an abacus / calculator etc. 

## Examples

![image](https://user-images.githubusercontent.com/5065660/99577777-d2eea880-29a9-11eb-8e06-c7cf8508d5e6.png)

**Comment by Xenomorph99** [comment]
I started by trying to mimic the examples above. I created `abacus-idea-1` and `abacus-idea-2`, but as you can see there's too much detail making them hard to interpret at 24x24 dps.

![abacus-idea-1](https://user-images.githubusercontent.com/1837101/99696886-6bd60000-2a4c-11eb-9488-db661c48b3bd.png)
![abacus-idea-2](https://user-images.githubusercontent.com/1837101/99696888-6c6e9680-2a4c-11eb-8a18-d88f55712b13.png)

I explored the idea of modifying [tune](https://materialdesignicons.com/icon/tune), but `abacus-idea-3` didn't work out so well either.

![abacus-idea-3a](https://user-images.githubusercontent.com/1837101/99696899-709ab400-2a4c-11eb-9eff-7edbae8e3130.png)
![abacus-idea-3b](https://user-images.githubusercontent.com/1837101/99696904-709ab400-2a4c-11eb-8bad-77b6314a3476.png)

Finally, I took `abacus-idea-2` and simplified it from 3 horizontal lines to 2. I think it's the best option so far.

![abacus](https://user-images.githubusercontent.com/1837101/99696932-785a5880-2a4c-11eb-802f-5aeff2321bc2.png)
[abacus.zip](https://github.com/Templarian/MaterialDesign/files/5568402/abacus.zip)

**Comment by jpgilchrist** [comment]
@Xenomorph99 that's great. I do think three bars is more "representative" of an abacus. I look at a three bar and say, "that's an abacus", whereas the two bar option is less so... however, I totally see what you mean with smaller sizing at 24x24 dps and the two bar does look crisper. I think this would be sufficient.

**Comment by Xenomorph99** [comment]
Awesome. I added it to the library.
