### ISSUE TITLE
Heartbeat icon

### ISSUE THREAD

**Issue by Wanderer16** [Templarian/MaterialDesign#5649]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To be used as healthcare or status icon in app/web.

## Examples

It could be something like this:
![image](https://user-images.githubusercontent.com/74710428/99652811-98901480-2a58-11eb-9e06-dc474515d0f1.png)
or this:
![image](https://user-images.githubusercontent.com/74710428/99656735-911f3a00-2a5d-11eb-8bc1-de975d378cf0.png)
or maybe both icons separately.

Thanks in advance!

**Comment by goyney** [comment]
[![heart-pulse](https://materialdesignicons.com/icon/heart-pulse)](https://materialdesignicons.com/icon/heart-pulse)
