### ISSUE TITLE
Road

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#565]
See this: http://fortawesome.github.io/Font-Awesome/icon/road/

**Comment by CoDEmanX** [comment]
![road](https://cloud.githubusercontent.com/assets/1309249/9038745/fbdb4878-39f6-11e5-921f-92dccdc749e9.png)? https://www.dropbox.com/s/9a887pi4kfppl0n/road.svg?dl=0
Perspective is discouraged, so there's little room for creativity...

**Comment by Templarian** [comment]
Really one of your best icons yet. :grin:

https://materialdesignicons.com/icon/road

**Comment by CoDEmanX** [comment]
Yeah I'm very proud!
