### ISSUE TITLE
Kite

### ISSUE THREAD

**Issue by scstraus** [Templarian/MaterialDesign#5650]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I plan to show an icon of a kite on my home automation dashboard when the weather is nice for flying a kite :-)

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
Google has two options in their extended set:

![image](https://user-images.githubusercontent.com/1015040/134224356-e5472609-494a-499f-be23-159ee20e4bf3.png)![image](https://user-images.githubusercontent.com/1015040/134224382-2e0003dc-98eb-487f-84e4-5c49dbddd122.png)

![image](https://user-images.githubusercontent.com/1015040/134224418-5d188077-135c-450a-a503-f6859c427063.png)![image](https://user-images.githubusercontent.com/1015040/134224446-8e4910d5-e790-4bfb-95d8-56415363fc84.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7205294/Archive.zip)

**Comment by goyney** [comment]
[![kite](https://materialdesignicons.com/icon/kite)](https://materialdesignicons.com/icon/kite)[![kite-outline](https://materialdesignicons.com/icon/kite-outline)](https://materialdesignicons.com/icon/kite-outline)
