### ISSUE TITLE
Edison Bulbs

### ISSUE THREAD

**Issue by gdreelin** [Templarian/MaterialDesign#5651]
I have:

- [ X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For Home assistant on various lamps
![edison bulbs 1](https://user-images.githubusercontent.com/802649/99868477-ce381900-2b90-11eb-8268-ebffff4ef6ae.jpg)
![edison bulbs 2](https://user-images.githubusercontent.com/802649/99868479-ce381900-2b90-11eb-9b74-7ca47554d84b.jpg)

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
These were added in v6.

[![lightbulb-variant](https://materialdesignicons.com/icon/lightbulb-variant)](https://materialdesignicons.com/icon/lightbulb-variant)[![lightbulb-variant-outline](https://materialdesignicons.com/icon/lightbulb-variant-outline)](https://materialdesignicons.com/icon/lightbulb-variant-outline)
