### ISSUE TITLE
Jellyfin

### ISSUE THREAD

**Issue by damiantje99** [Templarian/MaterialDesign#5654]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The Icon could be used in HomeAssistant. Jellyfin is an alternative for Plex and Emby.

_**Disclaimer: I'm not sure if Jellyfin falls under the brand icons, which are no longer accepted, but since Plex and Emby are still available I gave it a shot.**_

_**If its not allowed to add Jellyfin as an icon, please close the issue.**_

## Examples

![jellyfin](https://user-images.githubusercontent.com/12126826/99913990-03f91100-2cfb-11eb-9086-41170d2d7473.png)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by PeterShaggyNoble** [comment]
There is [an open PR](https://github.com/simple-icons/simple-icons/pull/4674) for this over at Simple Icons:

![Jellyfin](https://user-images.githubusercontent.com/15157491/104339567-a362a500-54ef-11eb-9622-1741aa664370.png)
