### ISSUE TITLE
GYM icon

### ISSUE THREAD

**Issue by cbalmeida** [Templarian/MaterialDesign#5656]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon to represent a "gym" location (since we have icons for other places like gas stations, etc.).
"Person lifting dumbbell". 

## Examples

![Screen Shot 2020-11-23 at 10 09 02 AM](https://user-images.githubusercontent.com/6311815/99978436-f16eee00-2d73-11eb-8e5b-85dbc441e338.png)

**Comment by Xenomorph99** [comment]
We already have [dumbell](https://materialdesignicons.com/icon/dumbbell). Creating a `human-dumbell` icon could be cool. It might work best if we based it on [human-handsup](https://materialdesignicons.com/icon/human-handsup). I would add "gym" as an alias.

**Comment by cbalmeida** [comment]
_We already have dumbell. Creating a human-dumbell icon could be cool. It might work best if we based it on human-handsup. I would add "gym" as an alias._

Yes, sure!! Thank you!!!

**Comment by goyney** [comment]
We already have `weight-lifter`.
[![weight-lifter](https://materialdesignicons.com/icon/weight-lifter)](https://materialdesignicons.com/icon/weight-lifter)
