### ISSUE TITLE
Where are the standard icons?

### ISSUE THREAD

**Issue by RandomClunk** [Templarian/MaterialDesign#5658]
Not all icons from [https://material.io/resources/icons/](https://material.io/resources/icons/) are available.
I was wondering why as this library extends the original with a ton of new icons.

I want to use an icon not in the standard library, but this library doesnt have an icon I want from the standard library.

And I dont want to load 2 files.

**Comment by Templarian** [comment]
What icon are we missing. Just note we don't add all of the stock icons as some are way too niche.

It's probably in the pack just under a more appropriate name (https://dev.materialdesignicons.com/contribute/icon-naming).

**Comment by goyney** [comment]
Yep, just let us know which icons you're looking for. We can find the name of them in our library or consider adding them.

**Comment by RandomClunk** [comment]
I did some searches and found the icons I wanted. They were `account_tree` and `push_pin`. I didn't find the exact tree icon but it was good enough, and the pin was named 'pin'. Thank you for responding and helping out.

**Comment by goyney** [comment]
You're welcome!
