### ISSUE TITLE
Digg

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#566]

**Comment by PeterShaggyNoble** [comment]
Cheeky bump!

**Comment by PeterShaggyNoble** [comment]
StumbleUpon is no longer a thing so editing this down to a request for Digg only.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
