### ISSUE TITLE
storage-tank(-underground)

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#5662]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Suggestion for a storage tank (e.g. water, oil) icon and a corresponding underground storage (could also be used for natural reservoir). Potentially also suitable for #5176.

## Preview

![grafik](https://user-images.githubusercontent.com/7279415/100262946-2aae8600-2f4d-11eb-95c5-8b3fc82fa4b5.png)
![grafik](https://user-images.githubusercontent.com/7279415/100263029-444fcd80-2f4d-11eb-8303-70b5367c45ab.png)

## Zip Download

[storage-tank(-underground).zip](https://github.com/Templarian/MaterialDesign/files/5598350/storage-tank.-underground.zip)

**Comment by goyney** [comment]
Can you try moving the liquid line to be on the grid so it's not so blurry at native resolution?

**Comment by boehan** [comment]
As you wish.

![grafik](https://user-images.githubusercontent.com/7279415/100265213-394a6c80-2f50-11eb-867d-0757fa95971c.png)
![grafik](https://user-images.githubusercontent.com/7279415/100265234-40717a80-2f50-11eb-963f-5e7830eec1f1.png)

[storage-tank-underground.zip](https://github.com/Templarian/MaterialDesign/files/5598458/storage-tank-underground.zip)

**Comment by goyney** [comment]
Much better!

**Comment by Horsi70** [comment]
Hello, interested in such underground tanks too. I have a rainwater-tank which is made of concrete and looks like this one:
https://thenounproject.com/term/water-tank/30192/
Thanks a lot in advance

**Comment by goyney** [comment]
[![storage-tank](https://materialdesignicons.com/icon/storage-tank)](https://materialdesignicons.com/icon/storage-tank)[![storage-tank-outline](https://materialdesignicons.com/icon/storage-tank-outline)](https://materialdesignicons.com/icon/storage-tank-outline)
