### ISSUE TITLE
fuel-cell

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#5664]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Icon for a fuel cell (or also an electrolyzer cell).

## Preview

![grafik](https://user-images.githubusercontent.com/7279415/100269623-212a1b80-2f57-11eb-9e17-46820d1f0b82.png)

## Zip Download

[fuel-cell.zip](https://github.com/Templarian/MaterialDesign/files/5598687/fuel-cell.zip)

**Comment by goyney** [comment]
There's a lot going on in this icon. The extra detail of the stripes on the right add noise, in my opinion, at native size. Additionally, the plus and minus are unintelligible at native size. I think we'll need to try and simplify this a little more before we'd consider adding it.

**Comment by boehan** [comment]
I'm aware that this icon is maybe a bit too technical. However, I'm not sure if there is much room for simplification. I could agree to remove the plus and minus (while keeping the bulges as indication of electrical connectors). However, I feel like the stripes should stay as an indication of the stacked design of the cell.
But I'm totally fine if it is not accepted due to lack of broader usage.

**Comment by Xenomorph99** [comment]
What would it look like if you removed the plus and minus signs at the bottom and simplified the stripes on the right to only 3 instead of 4?

**Comment by boehan** [comment]
![grafik](https://user-images.githubusercontent.com/7279415/101876257-6facfc00-3b8c-11eb-8080-5e2c5c45e5c0.png)
[fuel-cell_v2.zip](https://github.com/Templarian/MaterialDesign/files/5677670/fuel-cell_v2.zip)

**Comment by goyney** [comment]
[![fuel-cell](https://materialdesignicons.com/icon/fuel-cell)](https://materialdesignicons.com/icon/fuel-cell)

**Comment by boehan** [comment]
I guess I've reached the necessary amount of contributions to apply for an own contributor account? However, I don't know how to do that.
https://github.com/Templarian/MaterialDesign/issues?q=assignee%3Aboehan+is%3Aclosed+
(plus those which have probably not been assigned properly: #5663, #4073)

**Comment by goyney** [comment]
@boehan Please see https://github.com/Templarian/MaterialDesign/issues/6176.
