### ISSUE TITLE
Wreath

### ISSUE THREAD

**Issue by brayStorm** [Templarian/MaterialDesign#5667]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Controlling lights attached to a mega wreath on my house. (Homeassistant)

## Examples
maybe someting like this?
Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/20567279/100373466-b8987880-3002-11eb-8e96-49801c79a19a.png)

**Comment by bytrangle** [comment]
## Preview
![christmas-wreath-filled-preview](https://user-images.githubusercontent.com/28924121/102016742-f2080c80-3d94-11eb-9d60-62dd486959bd.png)

## Zip Download

[christmas-wreath.svg.zip](https://github.com/Templarian/MaterialDesign/files/5684895/christmas-wreath.svg.zip)

**Comment by goyney** [comment]
Nice first attempt, but there's a little too much detail and the detail doesn't follow Material guidelines. For example, whatever those dots represent, the bow, and the bell are all lost at native resolution.
