### ISSUE TITLE
car repair

### ISSUE THREAD

**Issue by ricar2ce** [Templarian/MaterialDesign#5668]
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

car repairs, maintenances, etc...

**Comment by Xenomorph99** [comment]
My first thought was to take the wrench from [progress-wrench](https://materialdesignicons.com/icon/progress-wrench) and add it like a modifier. I tried moving the car around, but I don't like how it looks.

![car-wrench-a](https://user-images.githubusercontent.com/1837101/100649981-7ae86800-3300-11eb-8f39-1e4129d62c83.png)
![car-wrench-b](https://user-images.githubusercontent.com/1837101/100649984-7ae86800-3300-11eb-8916-87e2e1b5c188.png)

Instead, I thought maybe we could add a wrench similar to the way [car-electric](https://materialdesignicons.com/icon/car-electric) includes a lightning bolt.

![car-repair](https://user-images.githubusercontent.com/1837101/100649978-79b73b00-3300-11eb-9d9f-dfdce0678f8f.png)
![car-repair-outline](https://user-images.githubusercontent.com/1837101/100649974-791ea480-3300-11eb-9185-5e14114aaf0c.png)

[car-repair.zip](https://github.com/Templarian/MaterialDesign/files/5618037/car-repair.zip)

**Comment by ricar2ce** [comment]
> My first thought was to take the wrench from [progress-wrench](https://materialdesignicons.com/icon/progress-wrench) and add it like a modifier. I tried moving the car around, but I don't like how it looks.
> 
> ![car-wrench-a](https://user-images.githubusercontent.com/1837101/100649981-7ae86800-3300-11eb-8f39-1e4129d62c83.png)
> ![car-wrench-b](https://user-images.githubusercontent.com/1837101/100649984-7ae86800-3300-11eb-8916-87e2e1b5c188.png)
> 
> Instead, I thought maybe we could add a wrench similar to the way [car-electric](https://materialdesignicons.com/icon/car-electric) includes a lightning bolt.
> 
> ![car-repair](https://user-images.githubusercontent.com/1837101/100649978-79b73b00-3300-11eb-9d9f-dfdce0678f8f.png)
> ![car-repair-outline](https://user-images.githubusercontent.com/1837101/100649974-791ea480-3300-11eb-9185-5e14114aaf0c.png)
> 
> [car-repair.zip](https://github.com/Templarian/MaterialDesign/files/5618037/car-repair.zip)

**Comment by ricar2ce** [comment]
Excellent work, the first option is the one I liked the most, but all are good, thank you very much answer so quickly

**Comment by Xenomorph99** [comment]
Let's leave the issue open until it's added to the library and to see if anyone comes up with other options.

**Comment by ricar2ce** [comment]
my apologies, I accidentally closed it

**Comment by ricar2ce** [comment]
> Let's leave the issue open until it's added to the library and to see if anyone comes up with other options.

my apologies, I accidentally closed it

**Comment by goyney** [comment]
[![car-wrench](https://materialdesignicons.com/icon/car-wrench)](https://materialdesignicons.com/icon/car-wrench)
