### ISSUE TITLE
void linux logo 

### ISSUE THREAD

**Issue by siduck76** [Templarian/MaterialDesign#5669]
I've seen many distro logos in the icon set but the void linux logo's missing  https://voidlinux.org/assets/img/void_bg.png

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
