### ISSUE TITLE
Battery icons

### ISSUE THREAD

**Issue by EladBezalel** [Templarian/MaterialDesign#567]
I noticed that there are only 0, 20, 30, 40, 60, 80, 90, 100
So i tried to use them and make 50, 10 and 70 and then i realized that they're not accurate.
I made all the svgs of the accurate ones but i can't contribute (it's disabled)

How can I contribute?

**Comment by Templarian** [comment]
Link to the SVG files here. There is a lot of recode going on behind the scenes for some new features coming soon. Once you hit 5 icons you become a contributor (and any icons you submitted will be transferred to your account).

**Comment by EladBezalel** [comment]
Uploaded all of them into [rar](https://drive.google.com/file/d/0B6KDLahcBkdJai1haWdGcGlLaHc/view?usp=sharing)

Thanks :)

**Comment by Templarian** [comment]
Awesome. I'll get them added tonight, should have time.

**Comment by EladBezalel** [comment]
Is there anything new about this? :smile:

**Comment by Templarian** [comment]
Nope. Might get into the new release this week.

**Comment by EladBezalel** [comment]
:pray:

**Comment by Templarian** [comment]
[![battery-10](https://materialdesignicons.com/icon/battery-10)](https://materialdesignicons.com/icon/battery-10) [![battery-50](https://materialdesignicons.com/icon/battery-50)](https://materialdesignicons.com/icon/battery-50) [![battery-70](https://materialdesignicons.com/icon/battery-70)](https://materialdesignicons.com/icon/battery-70)

**Comment by Templarian** [comment]
Above are just the new ones. A few others were modified and can be viewed on the [history](https://materialdesignicons.com/history) page.

**Comment by EladBezalel** [comment]
Well, at least I'm not the only one that was annoyed by that.. 
With all my hard work in happy that this is standard now. 
Thanks!
