### ISSUE TITLE
0 / 90 / 180 / 270 icons for subwoofer remote

### ISSUE THREAD

**Issue by fryc88** [Templarian/MaterialDesign#5670]
I have:

- Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Remote for audio system

## Examples

Just simple numbers - 90 / 180 / 270 for phase alignment - for example remote what i want to integrate for Velodyne sub got buttons with phase 0 degrees / 90 / 180 / 270 so i'd wish i could add icons for them.

**Comment by goyney** [comment]
We have the numeric alphabet, so you should be able to create these by using the individual numbers. We only add number/letter only icons in very specific cases. Unfortunately, I feel this is too niche for us to consider.

**Comment by Xenomorph99** [comment]
These numbers could be used for trigonometry if they included a degree sign: 0º, 45º, 90º, 180º etc, but I agree just adding the numbers alone feels too niche.
