### ISSUE TITLE
contact_support

### ISSUE THREAD

**Issue by oneezy** [Templarian/MaterialDesign#5671]
Looking for the `contact_support` icon
https://material.io/resources/icons/?icon=contact_support&style=baseline

## Examples
![baseline_contact_support_black_18dp](https://user-images.githubusercontent.com/7369575/100554637-8f265980-325b-11eb-96a0-8f65e0bf8f3d.png)

**Comment by goyney** [comment]
I don't feel we should add that exact icon, since it doesn't match the style of any of our other chat bubbles. We should, however, create a help variant of our chat base.

**Comment by Xenomorph99** [comment]
I agree. Google's `contact_support` icon feels to me like a Google brand icon. We could add these instead.

![chat-question](https://user-images.githubusercontent.com/1837101/101060075-3a7d2a00-354c-11eb-8887-7ce9c6b41cdb.png)
![chat-question-outline](https://user-images.githubusercontent.com/1837101/101060071-3a7d2a00-354c-11eb-8f76-77b6d32ca6d8.png)

[chat-question.zip](https://github.com/Templarian/MaterialDesign/files/5637545/chat-question.zip)

**Comment by Xenomorph99** [comment]
We should probably add these two as well.

![message-question](https://user-images.githubusercontent.com/1837101/101061808-24706900-354e-11eb-91fe-3c24e341d783.png)
![message-question-outline](https://user-images.githubusercontent.com/1837101/101061805-23d7d280-354e-11eb-868d-84f7974fb956.png)

[message-question.zip](https://github.com/Templarian/MaterialDesign/files/5637623/message-question.zip)

**Comment by goyney** [comment]
All 4 added.
