### ISSUE TITLE
candlebridge

### ISSUE THREAD

**Issue by ArnstadFredrik** [Templarian/MaterialDesign#5672]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/41859568/100590073-3656cf80-32f4-11eb-8b88-181a80f64fe9.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[candlebridge.svg.zip](https://github.com/Templarian/MaterialDesign/files/5614895/candlebridge.svg.zip)

**Comment by Xenomorph99** [comment]
Probably should reference this issue: https://github.com/Templarian/MaterialDesign/issues/2160
