### ISSUE TITLE
Candle stick icon (for Home Assistant)

### ISSUE THREAD

**Issue by f00dagi** [Templarian/MaterialDesign#5673]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Christmas light are often in the form of a candle stick. Would be nice to have as a light switch in Home Assistant.

## Examples

![image](https://user-images.githubusercontent.com/56124786/100797496-83d15a80-3422-11eb-8af7-e4b6e5c56b95.png)
![image](https://user-images.githubusercontent.com/56124786/100797567-a2375600-3422-11eb-9bdf-c9f351463a2b.png)

Thanks for your great work!

**Comment by goyney** [comment]
We already have `candle` which is used in your second image.

A candlebridge has been requested in #5672 and #2160.
