### ISSUE TITLE
Rename `face` to `face-man` to better align with `face-woman`

### ISSUE THREAD

**Issue by maxjoehnk** [Templarian/MaterialDesign#5675]
I'm not sure whether this has an impact but I feel like the `face` icon (and variants) should be renamed to `face-man`.
Right now it's assuming man is the default and woman is just a variant instead of seeing both options as equal.

I'm not sure whether you rename the default google icons as the `face` icon is from the google pack.

**Comment by Templarian** [comment]
Good eye.  Renaming icons is a breaking change and are only done during major releases. We can use this issue to discuss if these renames make sense for `6.x`. Looks like `4.2.95` introduced these additions.

The set follows the [icon naming guidelines](https://dev.materialdesignicons.com/contribute/icon-naming) defined here. This means a lot of the Google icons have altered names.

First of all we need to make a list of icon this impacts. This also might mean adding additional icons so we have male/female versions of each.

**Comment by goyney** [comment]
We'll be updating these in 6.0.

- `face` ➜ `face-man` (#5675)
- `face-outline` ➜ `face-man-outline` (#5675)
- `face-profile` ➜ `face-man-profile` (#5675)
- `face-profile-woman` ➜ `face-woman-profile` (#5675)
- `face-shimmer` ➜ `face-man-shimmer` (#5675)
- `face-shimmer-outline` ➜ `face-man-shimmer-outline` (#5675)

**Comment by goyney** [comment]
These have been renamed.
