### ISSUE TITLE
Message Reply Outline

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5676]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![message-reply-outline](https://user-images.githubusercontent.com/1837101/101061997-55e93480-354e-11eb-9905-abcecd12aa51.png)
![message-reply-text-outline](https://user-images.githubusercontent.com/1837101/101062000-571a6180-354e-11eb-848d-0116a0cdfe91.png)

## Zip Download

[message-reply-outline.zip](https://github.com/Templarian/MaterialDesign/files/5637629/message-reply-outline.zip)

**Comment by Templarian** [comment]
This looks good to add.

**Comment by goyney** [comment]
Added.
