### ISSUE TITLE
'Donate' / give money icon

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#5678]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In [AntennaPod](https://github.com/AntennaPod/AntennaPod/) we're looking to implement the [funding tag](https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#funding) of the Podcast Index namespace. So we want to include a quick way to give money to podcast creators. We need an icon for this.

I realise there've been several similar requests:
* Charity Icon #3670 
* Donation / Giving #3809

Former implemented, latter rejected/closed. The former, [charity icon](https://materialdesignicons.com/icon/charity), is not really on-point, as:
* it does not clearly indicate it's about money
* it focuses on charity, whereas the 'funding' link of a podcast could also refer to a paid, ad-free RSS feed

## Examples
I see different options, no clear view on what would work best:
* hand with coin<br><img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.6hDHAEqxRf7dSYhDgnNITAHaHa%26pid%3DApi&f=1" width=50px> <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.UCocbdPrTMIfLmxfaEpCzAHaHa%26pid%3DApi&f=1" width=50px>
* coin with heart<br><img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.f_NzZdB_P5E6U8BZqUqunQHaHa%26pid%3DApi&f=1" width=50px> <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.GR48E9Pmq_-2Sj8UBZC_-wHaHa%26pid%3DApi&f=1" width=45px>
* coin in box (slightly similar to the [vote icon](https://materialdesignicons.com/icon/vote))<br><img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.2woqycL0njTKO5qyr459QAHaHa%26pid%3DApi&f=1" width=50px>
* collection box (with coin)<br><img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.GakAk_a97JPoNIaLFrB91gHaHa%26pid%3DApi&f=1" width=50px> <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%3Fid%3DOIP.gDwIdSSNE--NSyhVv780QQHaKD%26pid%3DApi&f=1" width=50px> <img src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.buVIElNoevW1N_kiAEWXEQAAAA%26pid%3DApi&f=1" width=70px>
(left a [US model](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.9Jb57wjyQJwdQmmgUQaLJgHaLH%26pid%3DApi&f=1), right a [Dutch model](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.U_QxRCeXI7JIe2VScy474AHaEl%26pid%3DApi&f=1))

I like the 'collection box' but am afraid that because models seem to differ internationally it's difficult to land on an internationally recognised symbol. I like the heart also but the downside is currencies... again: not international-friendly. The close-up 'coin in box' or the 'hand with coin' might be the best concepts.

**Comment by goyney** [comment]
We have `charity` and `hand-heart` for these use cases. We won't add anything with the USD symbol on it. If you need something related to money, we have the coin and cash icons. Other than that, I feel you might be being too literal. The `charity` or `hand-heart` icon would make sense in the proper context.

**Comment by ekuleshov** [comment]
@goyney a variant of hand-money or hand-coin would be nice though

**Comment by keunes** [comment]
Thank you @ekuleshov for weighing in.

@goyney I fully agree with you about the USD sign, and actually already mentioned the reasons for this in my reflections with this request.

And regarding 'the proper context': The context of AntennaPod isn't really about charity, as represented by the hand-heart symbol. I tried to set this out also in the original post, but maybe I failed to give a good explanation. So to reiterate: it's about giving money, without any classification of it being commercial, charity, or something in between. A simple coin I feel is not clear enough in the use context I described - it represents a thing/object rather than the action.

**Comment by jhil** [comment]
Could these simple modifications work? Let me know and I can export the SVGs!
<img width="661" alt="Screenshot 2021-08-31 at 10 54 04@2x" src="https://user-images.githubusercontent.com/2228347/131544350-94772e79-81ab-421f-9e93-ee4a94ea3efa.png">

**Comment by goyney** [comment]
`hand-coin` seems appropriate. Please post the source for those.

**Comment by jhil** [comment]
Done!

[hand-coin.zip](https://github.com/Templarian/MaterialDesign/files/7085932/hand-coin.zip)

**Comment by keunes** [comment]
Thanks @jhil for picking this up! It looks nice :)

But if I'm picky: to me it looks more like a 'receive money' icon than a 'give money' one. The icon quite literally is holding up it's hand.

This would surely be suitable in some situations (e.g. in an app to request back money from friends). However, for the donation/give money concept that we have in AntennaPod, I feel it won't work too well.

If going for a 'hand with coin' iconography, I think the hand should be on top (akin to the example in the OP) to indicate giving. I realise that wouldn't be a mere modification. But what d'you think?

**Comment by goyney** [comment]
[![hand-coin](https://materialdesignicons.com/icon/hand-coin)](https://materialdesignicons.com/icon/hand-coin)[![hand-coin-outline](https://materialdesignicons.com/icon/hand-coin-outline)](https://materialdesignicons.com/icon/hand-coin-outline)

**Comment by goyney** [comment]
> Thanks @jhil for picking this up! It looks nice :)
> 
> But if I'm picky: to me it looks more like a 'receive money' icon than a 'give money' one. The icon quite literally is holding up it's hand.
> 
> This would surely be suitable in some situations (e.g. in an app to request back money from friends). However, for the donation/give money concept that we have in AntennaPod, I feel it won't work too well.
> 
> If going for a 'hand with coin' iconography, I think the hand should be on top (akin to the example in the OP) to indicate giving. I realise that wouldn't be a mere modification. But what d'you think?

By that logic, then are these icons giving away a heart?

[![hand-heart](https://materialdesignicons.com/icon/hand-heart)](https://materialdesignicons.com/icon/hand-heart)[![hand-heart-outline](https://materialdesignicons.com/icon/hand-heart-outline)](https://materialdesignicons.com/icon/hand-heart-outline)

I feel that the `hand-coin` icons contextually work for both use cases.

**Comment by keunes** [comment]
Hi @goyney

> By that logic, then are these icons receiving a heart? To me, they read as giving.

To me, indeed, they represent 'receiving love or care'.


> I feel that the `hand-coin` icons contextually work for both use cases.

What do you mean with 'both use cases'?
