### ISSUE TITLE
Unlink Icon

### ISSUE THREAD

**Issue by muffinjello** [Templarian/MaterialDesign#568]
Hello,

I'm using the icons for a text editor right now, and it would be lovely if there was an 'unlink' icon - something along the lines of the link-variant with a slash going through it?

That would be awesome, thanks!

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/link-off
https://materialdesignicons.com/icon/link-variant-off

(give it 5 minutes for the cache to refresh).

**Comment by muffinjello** [comment]
Outstanding.
Thank you!

On Mon, Aug 03, 2015 at 9:52 pm, Austin Andrews < notifications@github.com [notifications@github.com] > wrote:
https://materialdesignicons.com/icon/link-off
[https://materialdesignicons.com/icon/link-off]
https://materialdesignicons.com/icon/link-variant-off
[https://materialdesignicons.com/icon/link-variant-off]

(give it 5 minutes for the cache to refresh).

—
Reply to this email directly or view it on GitHub
[https://github.com/Templarian/MaterialDesign/issues/568#issuecomment-127478055] .[https://github.com/notifications/beacon/ACDu3s2Wg5JDaa0FkJwCIspQP6HpZooOks5okDyNgaJpZM4FlDHe.gif]
