### ISSUE TITLE
round and square table

### ISSUE THREAD

**Issue by jacopoventura01** [Templarian/MaterialDesign#5684]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon for use e.g. within Home Automation software (Hoem Assistant and others)

## Examples

I need an icon to represent a simple table. I need round and square table icon.

thank you for your job!

here same examples.
![square 1](https://user-images.githubusercontent.com/58790272/101290771-9f62a980-3804-11eb-9a60-47db7c49d498.png)
![square 2](https://user-images.githubusercontent.com/58790272/101290773-a093d680-3804-11eb-8ea4-211762af0fe8.png)
![round 2](https://user-images.githubusercontent.com/58790272/101290774-a093d680-3804-11eb-9a4c-04a5a30479d4.png)
![round 1](https://user-images.githubusercontent.com/58790272/101290775-a12c6d00-3804-11eb-93d7-214cd4872965.png)

**Comment by goyney** [comment]
The problem with any of the examples is that they show perspective. Unfortunately, showing perspective is against Material guidelines. There are two ways we can show a table, directly from the side or directly from the top. The side view won't show square vs. circle. And the top could literally be a square or a circle. We have all of these in our current library. I do not think we could provide anything further on this issue.
