### ISSUE TITLE
InverterV icon 

### ISSUE THREAD

**Issue by JorgeTru** [Templarian/MaterialDesign#5686]
I have:

- [1] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I wanted the InverterV icon to use to represent my ac in a room

## Examples

Include any example images so we know what the icon should look like.
here it is 
https://www.lg.com/my/images/residential-air-conditioning/v10cfb/gallery/large01.jpg
i only want what says inverterV

**Comment by Simran-B** [comment]
This is apparently an AC model by LG, which I would count as brand icon. We also don't add text-only icons with very few exceptions.

### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
