### ISSUE TITLE
Timer settings icon

### ISSUE THREAD

**Issue by ekuleshov** [Templarian/MaterialDesign#5687]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A timer settings icon

## Examples

A variant of a [timer-outline](http://materialdesignicons.com/icon/timer-outline) with a "settings" or "cog" overlay similar to [account-cog-outline](http://materialdesignicons.com/icon/account-cog-outline) or [account-settings-outline](http://materialdesignicons.com/icon/account-settings-outline)

**Comment by goyney** [comment]
[![timer-settings](https://materialdesignicons.com/icon/timer-settings)](https://materialdesignicons.com/icon/timer-settings)[![timer-settings-outline](https://materialdesignicons.com/icon/timer-settings-outline)](https://materialdesignicons.com/icon/timer-settings-outline)
[![timer-cog](https://materialdesignicons.com/icon/timer-cog)](https://materialdesignicons.com/icon/timer-cog)[![timer-cog-outline](https://materialdesignicons.com/icon/timer-cog-outline)](https://materialdesignicons.com/icon/timer-cog-outline)
