### ISSUE TITLE
hydrogen-station

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#5691]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![grafik](https://user-images.githubusercontent.com/7279415/101792278-cf5fc480-3b04-11eb-826c-8d083419b93e.png)
![grafik](https://user-images.githubusercontent.com/7279415/101792469-07ff9e00-3b05-11eb-9c80-37e38d81ac3f.png)

## Zip Download

[hydrogen-station.zip](https://github.com/Templarian/MaterialDesign/files/5673819/hydrogen-station.zip)

**Comment by goyney** [comment]
[![hydrogen-station](https://materialdesignicons.com/icon/hydrogen-station)](https://materialdesignicons.com/icon/hydrogen-station)
