### ISSUE TITLE
Website down? (http://materialdesignicons.com/)

### ISSUE THREAD

**Issue by hardcodet** [Templarian/MaterialDesign#5692]
Assuming it's your site, this seems to be offline. All I'm getting is a WebFaction page saying:

```
Site not configured

If you are the owner of this website and weren’t expecting to see this message, here are some potential causes and solutions:
```

**Comment by Templarian** [comment]
Yeah, something is definitely broken. I'm in the middle of meetings, so it's going to stay broken for a little bit today.

**Comment by Templarian** [comment]
Support ticket has been filed. I can FTP into the box, so it's definitely still running.

**Comment by fernandocandiani** [comment]
For me is a DNS_PROBE_FINISHED_NXDOMAIN. The CDN is out as well.

https://cdn.materialdesignicons.com/5.3.45/fonts/materialdesignicons-webfont.woff?v=5.3.45 and
https://materialdesignicons.com/

**Comment by albertovincenzi** [comment]
I would suggest you to use:
https://cdn.jsdelivr.net/npm/@mdi/font@5.x/

> For me is a DNS_PROBE_FINISHED_NXDOMAIN. The CDN is out as well.
> 
> https://cdn.materialdesignicons.com/5.3.45/fonts/materialdesignicons-webfont.woff?v=5.3.45 and
> https://materialdesignicons.com/

**Comment by Templarian** [comment]
Everything is going to be offline for a day or two. My host apparently sent an email Dec 1st that the migration had failed. Missed that email, so everything is going to offline at least until the weekend.

I'll get it migrated as soon as I can, but I'll have to do everything manually.

**Comment by Templarian** [comment]
I have until Dec 20th to move it to another box as that server is being removed.

**Comment by tVienonen** [comment]
Hi.

Any update on the migration? The web server is now apparently down. I have no access to the website.

**Comment by kevintresuelo** [comment]
Any alternatives?

**Comment by Simran-B** [comment]
There are some unexpected difficulties with setting up the new server. It will take some time.

All NPM packages are available as usual and there is also a CDN option
https://cdn.jsdelivr.net/npm/@mdi/js@5.x/
https://cdn.jsdelivr.net/npm/@mdi/svg@5.x/
etc.

**Comment by mattiagalati** [comment]
> There are some unexpected difficulties with setting up the new server. It will take some time.
> 
> All NPM packages are available as usual and there is also a CDN option
> https://cdn.jsdelivr.net/npm/@mdi/js@5.x/
> https://cdn.jsdelivr.net/npm/@mdi/svg@5.x/
> etc.

Is there a replacement for the CSS CDN (i.e.: http://cdn.materialdesignicons.com/5.0.45/css/materialdesignicons.min.css) ?

**Comment by charvp** [comment]
https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css

**Comment by mattiagalati** [comment]
> https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css

Many thanks!
Is there some sort of prevision about if and when the CDN will be online again? I mean, should I replace all my CDNs urls or maybe in one day or two the problem will be fixed?

**Comment by Simran-B** [comment]
It's unclear at this point, but you should transition to jsDelivr anyway:

https://twitter.com/MaterialIcons/status/1322281438994223111?s=19

**Comment by MartinX3** [comment]
Is there a library I can use to see the available icon paths?
I'm searching new Icons for buttons and without the website I feel a bit lost.

**Comment by kevintresuelo** [comment]
> Is there a library I can use to see the available icon paths?
> I'm searching new Icons for buttons and without the website I feel a bit lost.

I used a [web archive](http://web.archive.org/web/20201216215418/https://materialdesignicons.com/) from the Wayback Machine. Functionality is limited but at least the icons are shown and searching works...

**Comment by MartinX3** [comment]
> > Is there a library I can use to see the available icon paths?
> > I'm searching new Icons for buttons and without the website I feel a bit lost.
> 
> I used a [web archive](http://web.archive.org/web/20201216215418/https://materialdesignicons.com/) from the Wayback Machine. Functionality is limited but at least the icons are shown and searching works...

Thank you
I also found this in the bug tracker
https://mdisearch.com/

**Comment by mattiagalati** [comment]
> It's unclear at this point, but you should transition to jsDelivr anyway:
> 
> https://twitter.com/MaterialIcons/status/1322281438994223111?s=19

Thanks, we managed to rollout the suggested JSDelivr url.
Don't remeber if I visited the website in the last two months, maybe there was a specific banner for the planned shutdown...

**Comment by Templarian** [comment]
The new site will be on shortly. Trying to get time to wire up some remaining things in AWS.

Have family staying, so the timing is awful.

**Comment by Templarian** [comment]
The Chrome / Firefox extensions are also a great option until I have the dns switched. "Material Design Icons Picker"

**Comment by JokerMartini** [comment]
does this mean that the material design icons will no longer be available for anyone to use going forward? How can I access the svg versions of the icons?

**Comment by douglasbraz** [comment]
I'm using a alternative link  https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.8.55/css/materialdesignicons.min.css

**Comment by Templarian** [comment]
@JokerMartini Nah, our host shut down entirely. I'm moving everything to AWS since yesterday, but didn't get it switched over before the cut off last night.

Working on configuring the various sites and database right now. Not familiar with AWS, so watching tutorials. 🙃

**Comment by Templarian** [comment]
Still fixing `https`. Site is up on `http` and the CDN vanity url is working again (still move to jsdelivr url if you can update it).

**Comment by hsks** [comment]
@Templarian thanks for the update. I'm still facing slight issues with the cdn (https://cdn.materialdesignicons.com/)

**Comment by Templarian** [comment]
@hsks Which specific version (full URL)? I literally just updated it, so it may take a second.

**Comment by hsks** [comment]
This one in particular:
https://cdn.materialdesignicons.com/2.5.94/css/materialdesignicons.min.css

Also, the curl command fails to resolve the host

**Comment by Templarian** [comment]
@hsks Loads here, but I updated the DNS 12 hours ago.

https://www.whatsmydns.net/#A/materialdesignicons.com

**Comment by hsks** [comment]
@Templarian that explains it. It's yet to propagate to Chennai, India.

**Comment by Templarian** [comment]
So, even though I think I have it set to 1 hour I think a lot of nodes completely ignore it and refresh every 24 hours. It will fix itself in a few.

**Comment by hsks** [comment]
@Templarian sounds good. Thanks a lot for the updates.

**Comment by hsks** [comment]
I came across this issue: https://github.com/Templarian/MaterialDesign/issues/5608
@Templarian would you still recommend migrating to a different CDN or is it safe to stay on http://cdn.materialdesignicons.com/ ?

**Comment by Simran-B** [comment]
@hsks you should change it to jsDelivr if you have the chance: https://github.com/Templarian/MaterialDesign/issues/5692#issuecomment-748961913

**Comment by somelinuxguy** [comment]
Plans to replace your example.com SSL cert with a real one soon?

`rlyeh:~ cthulhu$ openssl s_client -showcerts -servername materialdesignicons.com -connect materialdesignicons.com:443 </dev/null

CONNECTED(00000005)
depth=0 CN = example.com
verify error:num=18:self signed certificate
verify return:1
depth=0 CN = example.com
verify return:1
---
Certificate chain
 0 s:/CN=example.com
   i:/CN=example.com
-----BEGIN CERTIFICATE-----
MIICqDCCAZACCQCz8T3726LYsjANBgkqhkiG9w0BAQUFADAWMRQwEgYDVQQDDAtl
eGFtcGxlLmNvbTAeFw0xMjExMTQxMTE4MjdaFw0yMjExMTIxMTE4MjdaMBYxFDAS
BgNVBAMMC2V4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKC
AQEA5NHl5TfZtO6zugau2tp5mWIcQYJhuwKTmYeXDLYAGJpoD2SixwPL5c8glneI
Rz1N2EQIZVeaWGbS0FLFlPdOkCkplpW9isYVC4XqKrk5b4HW4+YC+Cup0k+Kd4NM
eZOTUvWr5N6dIpdibkVumBc/pao8VtdwywlCL/PwGRsQtkXrRICzdtRa3MXqTmEF
foyVCGgBRtronlB9x4Plfb8Psk4GrPkjrWYgO8peKrl0O5+F+sYg7Gj95zCH73BQ
ANzCVNrgD9fs9cyx3ru9CUdEoIxAAJwQFkjm7xr6xqhIlSgnQ7B0uOSTNRcXY6rw
s+PxGneec/kRPRgzjC/QHY6n8QIDAQABMA0GCSqGSIb3DQEBBQUAA4IBAQBbyMqF
RDsX8zX1EW5qA8AQ8Jb2XqWrVeSO8blMV3WagJ2airMm3+c/82FCwsd/cZ08UXhA
/Kou0gi/F16tV26PiiUdp590Qao3d8H2qxc1rzzULimZPgxH4iA4vRyMHtyZN6h4
7Fdn7O9xNMPu8siOz8rrzsEdEX5URbOMkDLCZsbTIUWVv2XmqrR0K10d5VuLWeLi
r+4G6c6jpa244WmqT9ClqceJ12G1Wnmezy7ybiW0l5M2iuIKFEiRP5Hj0J15o1I2
pXAbKysAdWRHsJSQOtcgO8Vh9k0wo3tKg4HDp1hbrEzoGzOv92Vjg3lG8X+hzbMJ
MQURotHkD4Gk57wL
-----END CERTIFICATE-----
---
Server certificate
subject=/CN=example.com
issuer=/CN=example.com
---
No client certificate CA names sent
Server Temp Key: ECDH, X25519, 253 bits`

**Comment by dietrichg** [comment]
ACM is pretty straightforward on AWS if you need help @Templarian

**Comment by Templarian** [comment]
@somelinuxguy letsencrypt is wired up for the main site now. Still getting the dev site wired up. That was just the default configs they had when I used the setup scripts.

Wiring up the dev subdomain.

**Comment by Templarian** [comment]
The dev site is all setup. Configuring all the support stuff / CI still.

**Comment by Templarian** [comment]
There is a known issue with downloading image icons right now. 500 error due to a difference in imagemagic versions I think. I'll fix it shortly, but doing family stuff (aka drinking bloody mary's at brunch).

Hopefully can fix it later today. 👍

**Comment by Templarian** [comment]
^ That is fixed. I left PHP errors on for now until we can fully ensure there are no other configuration issues.

**Comment by Templarian** [comment]
@vodnicearv Fixed! Thanks again.

I'll keep an eye out of other issues. Leaving the PHP error logs on so we don't miss anything.

**Comment by vodnicearv** [comment]
@Templarian nice! :)

**Comment by Sammy-T** [comment]
Whenever I try to download an Android icon package, it produces an invalid .zip file that can't be opened. But, as far as I can tell, downloading individual .png icon images seems to be working correctly now.

**Comment by Templarian** [comment]
Looking into the two bugs above right now. 👍 

@Sammy-T Thanks!

**Comment by Templarian** [comment]
@Karewan Fixed that bug. 👍 

Working on the invalid zip issue next.

**Comment by Templarian** [comment]
Any endpoints that generate an archive file like the Android 5.0 downloads are resolved. As far as I know this was the last issue for the migration to AWS, but will keep this open for another week before closing.

Still updating some CI related stuff.

**Comment by Templarian** [comment]
Had to take the CDN DNS down as it was configured incorrectly. Will work to get that fixed right now.

**Comment by sasaorasanin** [comment]
Oh that happened, I was destroying my mind with what just happened from nowhere :D

**Comment by Templarian** [comment]
@sasaorasanin https://dev.materialdesignicons.com/getting-started/webfont The subdomain is just pointing at this. We're going to be deprecating it over time and have already removed it from all docs.

With that said the new DNS should be propagated in a 40 minutes in most regions, but I know some take a full 24 hours.

**Comment by sasaorasanin** [comment]
@Templarian Thanks I changed, I am using buefy so I placed bug on their git to change it as well :D

**Comment by AndersWinther-Dahl** [comment]
@Templarian I still have problems getting resources like
https://cdn.materialdesignicons.com/1.7.22/fonts/materialdesignicons-webfont.ttf?v=1.7.22
https://cdn.materialdesignicons.com/1.7.22/fonts/materialdesignicons-webfont.woff?v=1.7.22
https://cdn.materialdesignicons.com/1.7.22/fonts/materialdesignicons-webfont.woff2?v=1.7.22

This works:
https://cdn.materialdesignicons.com/1.7.22/css/materialdesignicons.min.css
but references the three files not working.

**Comment by danicunhac** [comment]
As it seems, some links are broken so I'm using this one
https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.8.55/css/materialdesignicons.min.css

That's the only one working right now it looks like

**Comment by danicunhac** [comment]
> I'm using a alternative link https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/5.8.55/css/materialdesignicons.min.css
Thank him for that

**Comment by Templarian** [comment]
@AndersWinther-Dahl @danicunhac Is the jsdelivr url in https://dev.materialdesignicons.com/getting-started/webfont this document showing the same issue?

I'll look after work, but that should be fine as we didn't update those configs.

**Comment by AndersWinther-Dahl** [comment]
@Templarian it works now! Thank you very much!

**Comment by Templarian** [comment]
Thanks everyone to bearing with us while we transitioned over to AWS during the holiday break.

While we're fixing small hiccups I think a majority of the issues in the old site are resolved, so I'm closing this issue.

Follow the pinned issue for more information on the new site's progress. Part of the move to a new site required us moving to AWS, so it's nice to have everything over early.

**Comment by henry2man** [comment]
Hi! just want to share another alternative just for browsing icons. In https://github.com/ziofat/material_design_icons_flutter/issues/30 @ziofat have built this mobile-friendly-but-desktop-usable website: https://ziofat.github.io/material_design_icons_flutter/

@ziofat Here it is another alternative website: https://mdisearch.com/

Thanks everyone for your contributions.
