### ISSUE TITLE
½ fraction icon

### ISSUE THREAD

**Issue by nmummau** [Templarian/MaterialDesign#5695]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have a scale/rating in an app where the user can choose a range of values between 0, ½, 1. I am using [Vuetify's](https://vuetifyjs.com/en/components/ratings/) `v-rataing` component. However there is no icon specific to this "½" value.  So for now I am using the `slash-forward` and `slash-forward-box` to represent the "½" value:

![image](https://user-images.githubusercontent.com/10524529/101971184-7cb60380-3bfd-11eb-8f84-1382d8b72eba.png)

## Examples

Identical to the styling of the `numeric-1-circle-outline` and the `numeric-1-circle`, I would like this "½" icon to be styled similarly. 
Possibly other common fractions could be useful as icons as well, but my request is only needing a  "½" icon.

## Proposed Names
`fraction-one-half-outline`
`fraction-one-half`

**Comment by goyney** [comment]
This won't happen in a circle. Not enough room.

But we did add a standard version.
[![fraction-one-half](https://materialdesignicons.com/icon/fraction-one-half)](https://materialdesignicons.com/icon/fraction-one-half)
