### ISSUE TITLE
Dashboard edit

### ISSUE THREAD

**Issue by invotech-magnus** [Templarian/MaterialDesign#5696]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Editing of dashboards is common functionality. Many icons have an xxx-edit variation, but not this one. I propose an icon that's a combination of view-dashboard and pencil.

**Comment by goyney** [comment]
[![view-dashboard-edit](https://materialdesignicons.com/icon/view-dashboard-edit)](https://materialdesignicons.com/icon/view-dashboard-edit)[![view-dashboard-edit-outline](https://materialdesignicons.com/icon/view-dashboard-edit-outline)](https://materialdesignicons.com/icon/view-dashboard-edit-outline)
