### ISSUE TITLE
newspaper-check, newspaper-remove

### ISSUE THREAD

**Issue by oliverhausler** [Templarian/MaterialDesign#5697]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

2 icons for fake news and real news.

## Examples

I would suggest a combination of Google's newspaper icon with a checkmark or a cross.

![image](https://user-images.githubusercontent.com/8090341/101991470-3c00cd80-3c83-11eb-9e3f-2883098fa8a1.png)

![image](https://user-images.githubusercontent.com/8090341/101991476-491dbc80-3c83-11eb-9871-30c26fa24185.png)

**Comment by goyney** [comment]
[![newspaper-remove](https://materialdesignicons.com/icon/newspaper-remove)](https://materialdesignicons.com/icon/newspaper-remove)[![newspaper-check](https://materialdesignicons.com/icon/newspaper-check)](https://materialdesignicons.com/icon/newspaper-check)
