### ISSUE TITLE
Suggested Icons, Language, based on ISO standards

### ISSUE THREAD

**Issue by SefDik** [Templarian/MaterialDesign#5699]
I'm developing a Home Assistant site in various European languages and would like to use buttons with icons to change from one to the other.
° EN English
° FR French 
° NL Dutch, etc 
At present I'm using your Alphabet outline series as a basis.
See - https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
Seth.

**Comment by goyney** [comment]
This is what our alphabet is for. We only create text-only icons for very specific use cases. Because it's easy to use the alphabet to make these variants, I don't think there is anything here for us to do.

**Comment by SefDik** [comment]
Thanks for the reply 'gogney', it was just an idea to use the 'TWO letter' format.  
Never mind, that'll maybe spur me on to learn how to make my own.  
I'll close this if I can.
Cheers.  Keep safe.
Seth.  /0^0\
