### ISSUE TITLE
Stethoscope

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#570]
http://fontawesome.io/icon/stethoscope/

**Comment by CoDEmanX** [comment]
![stethoscope](https://cloud.githubusercontent.com/assets/1309249/9071837/d86cf646-3af7-11e5-8ea4-475c765f36e6.png) https://www.dropbox.com/s/iji4n6ir6hco525/stethoscope.svg?dl=0

**Comment by Templarian** [comment]
[![stethoscope](https://materialdesignicons.com/icon/stethoscope)](https://materialdesignicons.com/icon/stethoscope)
