### ISSUE TITLE
tsconfig.json icon

### ISSUE THREAD

**Issue by FeixuRuins** [Templarian/MaterialDesign#5701]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
[PKief's material icon theme for VSCode](https://github.com/PKief/vscode-material-icon-theme)

**Comment by goyney** [comment]
We have a Typescript icon. This seems like something the package maintainer of that theme would need to map.
