### ISSUE TITLE
Mouse left, right, wheel icon

### ISSUE THREAD

**Issue by misa-lili** [Templarian/MaterialDesign#5708]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
- mouse left click
- mouse right click
- mouse wheel scroll or click

## Examples
![image](https://user-images.githubusercontent.com/63999327/102448831-50bfd580-4076-11eb-8971-2b8dd6ffcfa8.png)

**Comment by Templarian** [comment]
There has to be a nice way to adapt our current mouse to have a scroll wheel variant. Even with outlines this may be difficult to show at the small size, but hopefully someone tries a design or two.

**Comment by jhil** [comment]
A few drafts for the scroll wheel (I like the latter two options the most)

![Screenshot 2023-12-13 at 16 06 00](https://github.com/Templarian/MaterialDesign/assets/2228347/7d4deb73-3664-47d1-8ebc-c6deff046ce1)


And then here are left click, right click, and outline variants. I think these are solid so will upload now.

![Screenshot 2023-12-13 at 16 06 58](https://github.com/Templarian/MaterialDesign/assets/2228347/df77fdf3-a536-4bdd-85e9-2d4ba1ed1acb)

**Comment by jhil** [comment]
[![mouse-outline](https://pictogrammers.com/library/mdi/icon/mouse-outline)](https://pictogrammers.com/library/mdi/icon/mouse-outline)

[![mouse-right-click](https://pictogrammers.com/library/mdi/icon/mouse-right-click)](https://pictogrammers.com/library/mdi/icon/mouse-right-click)

[![mouse-left-click](https://pictogrammers.com/library/mdi/icon/mouse-left-click)](https://pictogrammers.com/library/mdi/icon/mouse-left-click)

**Comment by jhil** [comment]
[![mouse-scroll-wheel](https://pictogrammers.com/library/mdi/icon/mouse-scroll-wheel)](https://pictogrammers.com/library/mdi/icon/mouse-scroll-wheel)
