### ISSUE TITLE
database-eye and database-eye-off

### ISSUE THREAD

**Issue by gnajom3** [Templarian/MaterialDesign#5709]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
This icon could be used as a hide and show database option for a database creating/using software or website.

## Examples

Include any example images so we know what the icon should look like.
database-eye: a database icon with an eye in the bottom right corner.
database-eye-off: a database icon with a crossed out eye in the bottom right corner.

**Comment by goyney** [comment]
[![database-eye](https://materialdesignicons.com/icon/database-eye)](https://materialdesignicons.com/icon/database-eye)[![database-eye-off](https://materialdesignicons.com/icon/database-eye-off)](https://materialdesignicons.com/icon/database-eye-off)
[![database-eye-outline](https://materialdesignicons.com/icon/database-eye-outline)](https://materialdesignicons.com/icon/database-eye-outline)[![database-eye-off-outline](https://materialdesignicons.com/icon/database-eye-off-outline)](https://materialdesignicons.com/icon/database-eye-off-outline)
