### ISSUE TITLE
Request for icon device - Kiosk

### ISSUE THREAD

**Issue by raghunath7** [Templarian/MaterialDesign#5711]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Templarian** [comment]
@raghunath7 Please fill out the template above.

**Comment by goyney** [comment]
Closing due to no more information being shared about what this icon should look like.
