### ISSUE TITLE
Flutter & Dart

### ISSUE THREAD

**Issue by naco-siren** [Templarian/MaterialDesign#5714]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For a third-party GitHub app or app market, display the repo/app's framework 

## Examples
![flutter-512](https://user-images.githubusercontent.com/8222638/102664555-e8d1c380-4137-11eb-85c0-ef3511b2aa6b.png)

**Comment by Geeky-star** [comment]
Are you talking about flutter icon?

**Comment by naco-siren** [comment]
> Are you talking about flutter icon?

...Yeah I believe so?
If we have Android, Apple, iOS, TypeScript, Java, etc. included, then why not Dart and Flutter

**Comment by dpeter99** [comment]
The repo no longer accepts brand icons

https://github.com/Templarian/MaterialDesign/issues/5743#issuecomment-754186580

**Comment by Templarian** [comment]
@dpeter99 Developer related icons are fine such as language icons.

**Comment by goyney** [comment]
We won't be adding these icons to the Material Design Icons library. Please see our announcement here: https://github.com/Templarian/MaterialDesign/issues/6602

You may open a request to add these icons on our new Brand Icon Library we've started here: https://github.com/Pictogrammers/brand-icons/issues/new/choose

Please open a single request per brand icon. Thanks you.
