### ISSUE TITLE
table-picnic

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5715]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/102672387-e0848300-414d-11eb-9e44-166a15c008b1.png)

## Zip Download

[table-picnic.svg.zip](https://github.com/Templarian/MaterialDesign/files/5718522/table-picnic.svg.zip)

**Comment by jhil** [comment]
This was adapted from `table-furniture`

**Comment by goyney** [comment]
Added.
