### ISSUE TITLE
check-decagram-outline

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5716]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

[The preview didn't generate properly with the tool.]

![image](https://user-images.githubusercontent.com/2228347/102673005-b338d480-414f-11eb-95a0-8283506bcd88.png)

## Zip Download

[check-decagram-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/5718554/check-decagram-outline.svg.zip)

**Comment by goyney** [comment]
The preview generator didn't work because your paths weren't compiled down to a single compound path, just FYI. 😄 

This has been added.

**Comment by jhil** [comment]
Thanks for the heads up. I'll double check for that next time!
