### ISSUE TITLE
hand-wave

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5717]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
There was an old request that was closed at for satisfying other variations, but I've been looking for a waving hand specifically. https://github.com/Templarian/MaterialDesign/issues/3238
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Onboarding/welcome flows, social apps, giving feedback.

## Examples

To me, the tilt and [optionally] motion marks make a normal hand into a waving hand.

👋 

![image](https://user-images.githubusercontent.com/2228347/102673272-b54f6300-4150-11eb-8557-32365fe39387.png)

![image](https://user-images.githubusercontent.com/2228347/102673279-b97b8080-4150-11eb-8974-2ad4c69a42e0.png)

**Comment by goyney** [comment]
[![hand-wave](https://materialdesignicons.com/icon/hand-wave)](https://materialdesignicons.com/icon/hand-wave)[![hand-wave-outline](https://materialdesignicons.com/icon/hand-wave-outline)](https://materialdesignicons.com/icon/hand-wave-outline)
