### ISSUE TITLE
openSuse icons

### ISSUE THREAD

**Issue by LeonardoFuba** [Templarian/MaterialDesign#5718]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/19802320/102699363-ded8bf00-4222-11eb-8742-35bb64c372cc.png)
![image](https://user-images.githubusercontent.com/19802320/102699377-f44de900-4222-11eb-89bd-148d2a2ecfa6.png)

## Zip Download

[suse.zip](https://github.com/Templarian/MaterialDesign/files/5720121/suse.zip)
[suse-filled.zip](https://github.com/Templarian/MaterialDesign/files/5720122/suse-filled.zip)

## Usage
Completing some missing icons suggested in #1422 with simplified version of Suse / openSuse Geeko

## Examples
The project [matter](https://github.com/mateosss/matter) uses the MDI icons to build the interface

**Comment by Templarian** [comment]
https://brand.suse.com/brand-system Just linking for context, need to make sure we follow this.

@LeonardoFuba Is this where you got the vectors?

**Comment by LeonardoFuba** [comment]
I got the vectors from opensuse wiki
https://pt.opensuse.org/openSUSE:Artwork_logotipos#Bot.C3.B5esop

opensuse have been using old suse brand. 

suse recently have redesigned its brand with several rules that do not fit icons, I believe they will create yet.

**Comment by goyney** [comment]
We've gotten even more wary about adding new brand icons, even dev ones, as we are trying to rework our strategy around licensing of our library. I am strongly in favor of rejecting this addition.

If you're looking for brand icons, please go checkout SimpleIcons. Their library is compatible with our tooling. They have this icon.

https://simpleicons.org/?q=opensuse
