### ISSUE TITLE
firework-off

### ISSUE THREAD

**Issue by RuneKlein** [Templarian/MaterialDesign#5723]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

If you want to do something fancy like fireworks for new year, provide a way for users to toggle on / off, similar to the snowflake and snowflake-off icons

## Examples

Bascially like any of the already existing x-of variants eg. eye-off or snowflake-off

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/104061598-8449d780-51be-11eb-8027-169796b6b394.png)
[firework-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/5789265/firework-off.svg.zip)
