### ISSUE TITLE
website php notice

### ISSUE THREAD

**Issue by vodnicearv** [Templarian/MaterialDesign#5724]
Notice: Undefined index: HTTP_REFERER in /opt/bitnami/mdi/index.php on line 11

![image](https://user-images.githubusercontent.com/14403446/103185818-b6a62b80-48c6-11eb-9bf2-527de1718ba4.png)

**Comment by Templarian** [comment]
@vodnicearv Part of the move to AWS... will handle it in the #5692 thread as I knock out all the issues.

Thanks!
