### ISSUE TITLE
Time-out

### ISSUE THREAD

**Issue by wkeizer** [Templarian/MaterialDesign#5727]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'd like to use a time-out icon in a time tracking application. Most of the tracked time is registered on a project, but some time can't be billed to a customer. For this kind of time entries I want to use some sort of time-out icon.

## Examples

![timeout-error-time-out-icon-vector-20890599](https://user-images.githubusercontent.com/5119313/103224010-6dd28f00-4927-11eb-87c6-6e5b69a0f93b.jpg)

**Comment by goyney** [comment]
Exists already as `progress-clock`.

![image](https://user-images.githubusercontent.com/1015040/104061489-4f3d8500-51be-11eb-8763-4d65f9477978.png)
