### ISSUE TITLE
Viber

### ISSUE THREAD

**Issue by zzzveroboy** [Templarian/MaterialDesign#5729]
<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 631.99 666.43"><defs><style>.cls-1{fill:#fff;}.cls-2{fill:#7360f2;}</style></defs><title>Artboard 3</title><path class="cls-1" d="M527.75,98.77c-14-12.72-74.43-50.69-200.52-51.24,0,0-149.3-9.81-221.78,55.84C65.1,143.2,51.51,202.43,50,274.72s-9.21,210.35,123,247.08h0s-.51,102.51-.58,111.52c0,6.3,1,10.61,4.6,11.5,2.6.63,6.47-.71,9.78-4,21.13-21.23,88.81-102.88,88.81-102.88,90.82,5.93,163.06-12,170.83-14.54,18.28-5.86,117.32-14.41,134.13-149.83C598,233.91,574.27,138.6,527.75,98.77Z"/><path class="cls-2" d="M560.65,65C544.09,49.72,477.17,1.14,328.11.48c0,0-175.78-10.6-261.47,68C18.94,116.19,2.16,186,.39,272.55S-3.67,521.3,152.68,565.28l.15,0-.1,67.11s-1,27.17,16.89,32.71c21.64,6.72,34.34-13.93,55-36.19,11.34-12.22,27-30.17,38.8-43.89,106.93,9,189.17-11.57,198.51-14.61,21.59-7,143.76-22.66,163.63-184.84C646.07,218.4,615.64,112.66,560.65,65Zm18.12,308.58C562,509,462.91,517.51,444.64,523.37c-7.77,2.5-80,20.47-170.83,14.54,0,0-67.68,81.65-88.82,102.88-3.3,3.32-7.18,4.66-9.77,4-3.64-.89-4.64-5.2-4.6-11.5.06-9,.58-111.52.58-111.52s-.08,0,0,0C38.94,485.05,46.65,347,48.15,274.71S63.23,143.2,103.57,103.37c72.48-65.65,221.79-55.84,221.79-55.84,126.09.55,186.51,38.52,200.52,51.24C572.4,138.6,596.1,233.91,578.77,373.54Z"/><path class="cls-2" d="M389.47,277.2a8.42,8.42,0,0,1-8.41-8c-1.43-28.61-14.91-42.62-42.42-44.1a8.43,8.43,0,0,1,.91-16.83c36.3,2,56.48,22.73,58.34,60.09a8.43,8.43,0,0,1-8,8.84Z"/><path class="cls-2" d="M432.73,291.7h-.2a8.43,8.43,0,0,1-8.23-8.62c.65-28.81-7.58-52.14-25.16-71.32s-41.53-29.58-73.46-31.92A8.43,8.43,0,1,1,326.91,163c35.93,2.63,64.41,15.2,84.66,37.35s30.32,50.17,29.58,83.08A8.44,8.44,0,0,1,432.73,291.7Z"/><path class="cls-2" d="M477,309a8.44,8.44,0,0,1-8.43-8.37c-.39-51.53-15.23-90.89-45.37-120.31-29.78-29-67.4-43.88-111.83-44.2a8.43,8.43,0,0,1,.06-16.86h.07c48.92.36,90.46,16.84,123.47,49S485,245,485.44,300.53a8.43,8.43,0,0,1-8.36,8.49Z"/><path class="cls-2" d="M340.76,381.68s11.85,1,18.23-6.86l12.44-15.65c6-7.76,20.48-12.71,34.66-4.81A366.67,366.67,0,0,1,437,374.1c9.41,6.92,28.68,23,28.74,23,9.18,7.75,11.3,19.13,5.05,31.13,0,.07-.05.19-.05.25a129.81,129.81,0,0,1-25.89,31.88c-.12.06-.12.12-.23.18q-13.38,11.18-26.29,12.71a17.39,17.39,0,0,1-3.84.24,35,35,0,0,1-11.18-1.72l-.28-.41c-13.26-3.74-35.4-13.1-72.27-33.44a430.39,430.39,0,0,1-60.72-40.11,318.31,318.31,0,0,1-27.31-24.22l-.92-.92-.92-.92h0l-.92-.92c-.31-.3-.61-.61-.92-.92a318.31,318.31,0,0,1-24.22-27.31,430.83,430.83,0,0,1-40.11-60.71c-20.34-36.88-29.7-59-33.44-72.28l-.41-.28a35,35,0,0,1-1.71-11.18,16.87,16.87,0,0,1,.23-3.84Q141,181.42,152.12,168c.06-.11.12-.11.18-.23a129.53,129.53,0,0,1,31.88-25.88c.06,0,.18-.06.25-.06,12-6.25,23.38-4.13,31.12,5,.06.06,16.11,19.33,23,28.74a366.67,366.67,0,0,1,19.74,30.94c7.9,14.17,2.95,28.68-4.81,34.66l-15.65,12.44c-7.9,6.38-6.86,18.23-6.86,18.23S254.15,359.57,340.76,381.68Z"/></svg>

https://www.viber.com/en/
Icon taken from the official website: https://www.viber.com/en/brand-center/

**Comment by goyney** [comment]
**Please do not remove our issue template.** 

In order to deal with incoming requests efficiently we ask you provide usage information and examples so we don't have to waste time asking for clarification on your request. Help us to help you by providing a bit more information. 

All requests which do not follow our template will now be closed immediately.

---

### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by PeterShaggyNoble** [comment]
This one is already available from Simple Icons:

[![Viber](https://user-images.githubusercontent.com/15157491/104339268-5088ed80-54ef-11eb-9221-5d8681e52d18.png)](https://simpleicons.org/?q=Viber)
