### ISSUE TITLE
Diamond

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#573]

**Comment by CoDEmanX** [comment]
![diamond](https://cloud.githubusercontent.com/assets/1309249/9060290/a60ab642-3ab2-11e5-8466-5a2c9259715d.png) 2px strokes https://www.dropbox.com/s/5m3u41zi5rpesnb/diamond.svg?dl=0
![diamond2](https://cloud.githubusercontent.com/assets/1309249/9060291/a60f70ba-3ab2-11e5-8014-1a6bacd6717b.png) pixel-aligned https://www.dropbox.com/s/sarwvmu1hm8e8cx/diamond2.svg?dl=0

**Comment by Templarian** [comment]
Definitely the second one. Has a more diamond shape to it.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/diamond
