### ISSUE TITLE
Firewire

### ISSUE THREAD

**Issue by Recordfriend** [Templarian/MaterialDesign#5730]
## Preview

![](https://cdn4.iconfinder.com/data/icons/proglyphs-communication-and-devices/512/Firewire-512.png)

## Zip Download

[Firewire-512.svg.zip](https://github.com/Templarian/MaterialDesign/files/5750995/Firewire-512.svg.zip)

**Comment by Templarian** [comment]
I'm not against adding classic tech icons to the pack (we already have a lot). Are you requesting for nostalgic reasons? 😄 

I haven't seen a firewire cable in many years.

**Comment by Recordfriend** [comment]
😄 I know it’s an oldie but I still use it every day to connect to my audio kit. Developments in analog technology go a bit slower than in digital and audio over FW still sounds superior…

**Comment by goyney** [comment]
[![firewire](https://materialdesignicons.com/icon/firewire)](https://materialdesignicons.com/icon/firewire)
