### ISSUE TITLE
Essential oil diffuser

### ISSUE THREAD

**Issue by pace6666** [Templarian/MaterialDesign#5731]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Looking for generic essential oil diffuser icon. For home automation purpose.

## Examples

Like this (found on google image search)

https://www.google.com/url?sa=i&url=https%3A%2F%2Ficonscout.com%2Ficon%2Fdiffuser-2590377&psig=AOvVaw2e1qinWUruA1TrXmHRwuUl&ust=1609462533677000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCKihiqyB9-0CFQAAAAAdAAAAABAP

**Comment by goyney** [comment]
Would the new `scent` icon fill this use case? I know it does for me!

[![scent](https://materialdesignicons.com/icon/scent)](https://materialdesignicons.com/icon/scent)

**Comment by goyney** [comment]
Closing due to lack of response. We have a new icon that should solve this use case. If it does not and you have more information you could share to help us with this request, please comment back here. Thanks!
