### ISSUE TITLE
Fire Off

### ISSUE THREAD

**Issue by evoblicec** [Templarian/MaterialDesign#5734]
I would like a `fire` icon disabled/off

I have:
- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This is to picture a stopped fireplace in my home automation system.

Thanks

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/104060909-3da7ad80-51bd-11eb-8b81-afc61d27d47f.png)

**Comment by evoblicec** [comment]
Thank you!
