### ISSUE TITLE
request projector-screen-outlined

### ISSUE THREAD

**Issue by annymosse** [Templarian/MaterialDesign#5736]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Examples

![projector-screen-outlined](https://user-images.githubusercontent.com/24898178/103474710-de096680-4da6-11eb-9da0-41e57bf29251.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/104060719-f3bec780-51bc-11eb-96b9-ffb8ac814517.png)
