### ISSUE TITLE
CDN Cheat Sheet Down???

### ISSUE THREAD

**Issue by oneezy** [Templarian/MaterialDesign#5737]
I noticed that the CDN cheat sheet is no longer available. Is this a bug or did the url change?

https://cdn.materialdesignicons.com/5.4.55/

![image](https://user-images.githubusercontent.com/7369575/103476748-0cbf1700-4d7e-11eb-835b-c9929a290a46.png)

**Comment by Templarian** [comment]
@oneezy oops, I messed up the redirect. This is fixed now.

We host the previews at https://pictogrammers.github.io/@mdi/font/5.8.55/ now, it should have been redirecting there.
