### ISSUE TITLE
tools (screwdriver/wrench combo)

### ISSUE THREAD

**Issue by rpi-odoo** [Templarian/MaterialDesign#574]
https://octicons.github.com/icon/tools/

**Comment by CoDEmanX** [comment]
There will be #319, but we could definitely use a screw driver as well. Not sure about a composition of both...

**Comment by CoDEmanX** [comment]
A screwdriver:
![screw-driver](https://cloud.githubusercontent.com/assets/1309249/9096712/2bc8a8ae-3bbf-11e5-9108-8caef84b5b1a.png) https://www.dropbox.com/s/nwppyvl6z5fkjzh/screw-driver.svg?dl=0

**Comment by derwaldgeist** [comment]
I'd like to see that screwdriver in the font!

**Comment by Templarian** [comment]
[![screwdriver](https://materialdesignicons.com/icon/screwdriver)](https://materialdesignicons.com/icon/screwdriver)

**Comment by CoDEmanX** [comment]
The wrench / build tool points to the upper left corner, should the screw driver also be rotated like that? Not that there's anything wrong with the current orientation. I just wonder if there's a principle involved. Pointing to the left bottom corner is what icons like the pen do.

**Comment by Templarian** [comment]
Uhh... probably be fine if we rotate the phillips head to the top left.

**Comment by CoDEmanX** [comment]
Hm, a combination doesn't work out of the (tool) box, because the wrench is too large:
![screw-driver-wrench](https://cloud.githubusercontent.com/assets/1309249/10836295/29ac85d8-7eac-11e5-8562-b8d64c71b271.png)

**Comment by goyney** [comment]
Removing Contribution label since `screwdriver` was added, but now this is a request for a screwdriver/wrench combination icon.

**Comment by MrGrigri** [comment]
Here's my stab at it.

[![image](https://user-images.githubusercontent.com/4528551/52224986-8b476d00-2866-11e9-8686-23d2abf3614c.png)](https://github.com/Templarian/MaterialDesign/files/2829097/wrench-screwdriver.zip)

**Comment by PeterShaggyNoble** [comment]
Would making the grip of the screwdriver a big wider work?

**Comment by MrGrigri** [comment]
It looks miss-proportioned with a wider screwdriver handle.

**Comment by goyney** [comment]
[![tools](https://materialdesignicons.com/icon/tools)](https://materialdesignicons.com/icon/tools)
