### ISSUE TITLE
LICENSE refers to pictogrammers.com which is now a dead link

### ISSUE THREAD

**Issue by juliangilbey** [Templarian/MaterialDesign#5741]
The LICENSE file says:
```
This icon collection is released as free, open source, and GPL friendly by
the [Pictogrammers](http://pictogrammers.com/) icon group.
```
but that website gives a 403 error.  Presumably this should be changed to the materialdesignicons website?

**Comment by Templarian** [comment]
@juliangilbey We're transitioning to AWS this week. That site is last on my list to move over. Low priority.

Merging with our mega issue... #5692

**Comment by Templarian** [comment]
I added a little placeholder index.html to that empty directory for now. 👍
