### ISSUE TITLE
request folder-save-outline

### ISSUE THREAD

**Issue by annymosse** [Templarian/MaterialDesign#5742]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

for save : folder files, folder setings,..

## Examples

![folder-outline2](https://user-images.githubusercontent.com/24898178/103517576-a8ca4a80-4e72-11eb-8f32-c9bd962f1c2b.png)

**Comment by goyney** [comment]
The "save" icon is not a standard modifier and I feel its meaning gets lost in that small of a format. I feel one of our normal save icons should be sufficient for most save operations and am of the opinion that we don't add this variation.

**Comment by annymosse** [comment]
actually i made it in my project as an svg and it didn't lose the format under small sizes,  the reason of choose this icon instead the existing ones is it's more meaningful and more declarative than the others, hopefully you make a test by yourself ,

**Comment by Templarian** [comment]
Going to close this one out. The `content-save` is not a modifier we're going to introduce at this time to other base icons.

Thanks for the request.
