### ISSUE TITLE
filter_d_fill

### ISSUE THREAD

**Issue by ronyfinastra** [Templarian/MaterialDesign#5744]
[filter_d_fill.zip](https://github.com/Templarian/MaterialDesign/files/5771323/filter_d_fill.zip)

I have: font to contributes

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
https://ibb.co/DLD4YR4
Paste a preview of your icon here. You can generate one using our [preview generator]
(http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

best regards
Rony

**Comment by goyney** [comment]
Thanks for your suggestions and contribution. However, we already have a set of `filter` icons that this is insanely similar to. Because of that, I do not feel that this variation is necessary.

**Comment by ronyfinastra** [comment]
Hello Michael
tnx for quick respond

The choosing styling of the current filter shape has a very technical visibility.
in a world that combines dev & design we should be able to add more value
in a friendlier filter shape design, therefore i would appreciate if you could accept my contribution.

https://imgur.com/a/N1BS4nP
best regards
Rony

**Comment by goyney** [comment]
I can appreciate that want to provide more value, however the two proposed icons have issues that would prevent them from being included in the first place.

The "filled" version is not actually a filled icon, but an outline. The "outlined" version is something else entirely that doesn't fit within Material guidelines.

The "filled" version could potentially be added as a variant of our current outline, however the only differences are the slight slant to the end of the tube and the fact that the tube is filled. Personally, I feel the tube needs to not be solid, which would match our current outlined version. At that point, all we would be doing is removing the slant.

All that being said, the icons suggested more closely resemble the stock Google icons. I believe we have improved on those and discussed this in the past, so I will let the other contributors chime in here. I am still of the opinion that what we have works and we should not add these variants.

**Comment by Templarian** [comment]
Agreed with the above points. Closing this as it's best to use the standard filter icon that exists for consistency.
