### ISSUE TITLE
filter_d_outline

### ISSUE THREAD

**Issue by ronyfinastra** [Templarian/MaterialDesign#5745]
I have:

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
https://ibb.co/wcX3tVx
[filter_d_outline.zip](https://github.com/Templarian/MaterialDesign/files/5771309/filter_d_outline.zip)

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

Best regards
Rony

**Comment by goyney** [comment]
Please see https://github.com/Templarian/MaterialDesign/issues/5744#issuecomment-754741651.
