### ISSUE TITLE
tag-price-up

### ISSUE THREAD

**Issue by erdemyilmaz06** [Templarian/MaterialDesign#5746]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![tag-price-up](https://user-images.githubusercontent.com/77012754/103673172-54b48880-4f8e-11eb-9fbc-87bae1170d0e.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[tag-price-up.zip](https://github.com/Templarian/MaterialDesign/files/5771361/tag-price-up.zip)

**Comment by goyney** [comment]
See comment on #5747.

![image](https://user-images.githubusercontent.com/1015040/104059313-c5d88380-51ba-11eb-9662-3a1df154a2bb.png)![image](https://user-images.githubusercontent.com/1015040/104059337-cc66fb00-51ba-11eb-92d3-d9ca61296e92.png)

**Comment by erdemyilmaz06** [comment]
The icons you uploaded do not represent a timeline. This icon is used for a textile has increased price that changed between selected time period.
