### ISSUE TITLE
tag-price-right

### ISSUE THREAD

**Issue by erdemyilmaz06** [Templarian/MaterialDesign#5748]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![tag-price-right](https://user-images.githubusercontent.com/77012754/103673528-bd036a00-4f8e-11eb-9402-ea865c59e6f8.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[tag-price-right.zip](https://github.com/Templarian/MaterialDesign/files/5771479/tag-price-right.zip)

**Comment by goyney** [comment]
And this one plays different compared to #5747 and actually points the direction. We should still use our cutout.

![image](https://user-images.githubusercontent.com/1015040/104060003-e0f7c300-51bb-11eb-8d7d-9027f7ffea89.png)![image](https://user-images.githubusercontent.com/1015040/104060024-e7863a80-51bb-11eb-8a65-0962e9292ee0.png)
![image](https://user-images.githubusercontent.com/1015040/104060125-143a5200-51bc-11eb-875f-92ee43d58e78.png)![image](https://user-images.githubusercontent.com/1015040/104060144-1b616000-51bc-11eb-8bae-b9aa1b53c4a7.png)

**Comment by erdemyilmaz06** [comment]
The icons you uploaded do not represent a timeline. This icon is used for a textile has stable price that not changed for selected time period.
