### ISSUE TITLE
More of the official google icons

### ISSUE THREAD

**Issue by eweilow** [Templarian/MaterialDesign#575]
For a project I'm doing I need a translation icon, like the official google one found here: https://github.com/google/material-design-icons/blob/master/action/svg/production/ic_translate_48px.svg

I'm aware that you have a lot of the official ones, but it would be great to have the rest too, since not all of them appear to be here! :+1:

**Comment by CoDEmanX** [comment]
See #420

**Comment by CoDEmanX** [comment]
There are now the following:
https://materialdesignicons.com/icon/translate
https://materialdesignicons.com/icon/google-translate
