### ISSUE TITLE
variable-equals

### ISSUE THREAD

**Issue by clairecas** [Templarian/MaterialDesign#5750]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/9113137/103696027-a7c91400-4f6b-11eb-965c-033a47d75944.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[mdi-variable-equals.svg.zip](https://github.com/Templarian/MaterialDesign/files/5772453/mdi-variable-equals.svg.zip)

**Comment by Templarian** [comment]
@clairecas What's the use case of such an icon? For context on this one.

**Comment by clairecas** [comment]
@Templarian I work on a team that is designing and building an IDE. Because of this we utilize many of the existing variable and code-related icons. We would use this icon to mean “Set Variable” throughout our IDE. (I also submitted an icon called [variable-add](https://github.com/Templarian/MaterialDesign/issues/5749) that we would use to mean “Create Variable”).

Expanding the set of “variable” icons will greatly help us differentiate the actions our users can perform with variables. I am hoping it could fit nicely with the current variable icon, and could be used by others in the community as well!

**Comment by goyney** [comment]
This is not one of our standard modifiers and I'm not entirely sure about it. The icon feels very busy. I would think our existing equal icons would be sufficient for the provided use case.

**Comment by Templarian** [comment]
Closing this one as too niche at this time.
