### ISSUE TITLE
script-text-key

### ISSUE THREAD

**Issue by clairecas** [Templarian/MaterialDesign#5751]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html)x

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/9113137/103696093-c4654c00-4f6b-11eb-85f9-05a17b41fbcf.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[mdi-script-key.svg.zip](https://github.com/Templarian/MaterialDesign/files/5772457/mdi-script-key.svg.zip)

**Comment by goyney** [comment]
I'd prefer to see us not move the base icon over 1dp.

![image](https://user-images.githubusercontent.com/1015040/104058205-f9b2a980-51b8-11eb-9246-d5debb5df2a7.png)![image](https://user-images.githubusercontent.com/1015040/104058220-00d9b780-51b9-11eb-959b-d372e89dc274.png)
