### ISSUE TITLE
koala

### ISSUE THREAD

**Issue by clairecas** [Templarian/MaterialDesign#5753]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/9113137/103699940-b1557a80-4f71-11eb-9441-a1bba8ca6789.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[mdi-koala.svg.zip](https://github.com/Templarian/MaterialDesign/files/5772645/mdi-koala.svg.zip)

**Comment by Templarian** [comment]
The idea is there, but you may have to bold the face and ears a bit more. Also it needs to be centered on the grid.

**Comment by clairecas** [comment]
@Templarian thank you for your feedback, those are good points. I tried another version to fix the centering issue and the boldness of the face and ears:

![image](https://user-images.githubusercontent.com/9113137/104025988-5dc27700-5193-11eb-8bc0-c1d21fbf24aa.png)

[mdi-koala.svg.zip](https://github.com/Templarian/MaterialDesign/files/5787697/mdi-koala.svg.zip)

**Comment by Templarian** [comment]
Might be a good idea to get the panda's oval on the exact grid if possible. Little bit of geometry to some of the MD style.

Pretty close, the general design is there. 👍

**Comment by goyney** [comment]
I had to do some tweaking to get it there, but its done and added!
![image](https://user-images.githubusercontent.com/1015040/104408978-e2621c00-552a-11eb-951d-7b469adaea09.png)
