### ISSUE TITLE
Bathroom Sinks / Wash Basins

### ISSUE THREAD

**Issue by timdonovanuk** [Templarian/MaterialDesign#5756]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Indication of lights behind tap. There is currently toilet icon, but no sink icon.

## Examples

![image](https://user-images.githubusercontent.com/8156439/103769884-04383c00-501d-11eb-8b16-edcee08ff1c3.png)

![image](https://user-images.githubusercontent.com/8156439/103769925-131eee80-501d-11eb-8028-59f5bc26b083.png)

**Comment by goyney** [comment]
Duplicate of #5137.
