### ISSUE TITLE
file-image-outline icon variants plus/minus/remove

### ISSUE THREAD

**Issue by ekuleshov** [Templarian/MaterialDesign#5758]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Looking for plus / minus / remove variants for the [file-image-outline](https://materialdesignicons.com/icon/file-image-outline) icon.

## Examples

These variants exist for other icons, eg. the [book-outline](https://materialdesignicons.com/icon/book-outline) icon - [book-plus-outline](https://materialdesignicons.com/icon/book-plus-outline), [book-minus-outline](https://materialdesignicons.com/icon/book-minus-outline), [book-remove-outline](https://materialdesignicons.com/icon/book-remove-outline). The

**Comment by goyney** [comment]
[![file-image-plus](https://materialdesignicons.com/icon/file-image-plus)](https://materialdesignicons.com/icon/file-image-plus)[![file-image-plus-outline](https://materialdesignicons.com/icon/file-image-plus-outline)](https://materialdesignicons.com/icon/file-image-plus-outline)
[![file-image-minus](https://materialdesignicons.com/icon/file-image-minus)](https://materialdesignicons.com/icon/file-image-minus)[![file-image-minus-outline](https://materialdesignicons.com/icon/file-image-minus-outline)](https://materialdesignicons.com/icon/file-image-minus-outline)
[![file-image-remove](https://materialdesignicons.com/icon/file-image-remove)](https://materialdesignicons.com/icon/file-image-remove)[![file-image-remove-outline](https://materialdesignicons.com/icon/file-image-remove-outline)](https://materialdesignicons.com/icon/file-image-remove-outline)
