### ISSUE TITLE
color-chart

### ISSUE THREAD

**Issue by erdemyilmaz06** [Templarian/MaterialDesign#5759]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![color-chart](https://user-images.githubusercontent.com/77012754/103874357-1c25c380-50e2-11eb-8c28-a35b21e3215b.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[color-chart.zip](https://github.com/Templarian/MaterialDesign/files/5780617/color-chart.zip)

**Comment by goyney** [comment]
See #5760.

**Comment by erdemyilmaz06** [comment]
This is very different from that one. This one is like pantone color swstch. Other one is used for materials, not colors.

**Comment by erdemyilmaz06** [comment]
Besides, I made them both :)
