### ISSUE TITLE
sports icon

### ISSUE THREAD

**Issue by ekiselyov** [Templarian/MaterialDesign#576]
- baseball (tracked in #1932)
- [x] soccer
- [ ] hockey
- [x] golf
- [x] run
- [x] bike
- [ ] other

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/run
https://materialdesignicons.com/icon/bike

Also see #414 / https://github.com/Templarian/MaterialDesign/issues/505#issue-95548152

**Comment by PeterShaggyNoble** [comment]
A golf icon is now available and #1620 is a specific request for a hockey icon so going to close this one out.

[![golf](https://user-images.githubusercontent.com/15157491/34606558-d48847c8-f207-11e7-9472-583c3e842080.png)](https://materialdesignicons.com/icon/golf)
