### ISSUE TITLE
color swatch

### ISSUE THREAD

**Issue by erdemyilmaz06** [Templarian/MaterialDesign#5760]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![material-chart](https://user-images.githubusercontent.com/77012754/103874456-39f32880-50e2-11eb-9486-970020f8801e.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[material-chart.zip](https://github.com/Templarian/MaterialDesign/files/5780623/material-chart.zip)

**Comment by goyney** [comment]
Our `palette-swatch` is very similar to this.

[![palette-swatch](https://materialdesignicons.com/icon/palette-swatch)](https://materialdesignicons.com/icon/palette-swatch)

**Comment by Templarian** [comment]
The name would need to be something else. But I think the design works. Just need to figure out a name. Not going to call it pantone, but it reminds me of those swatches.

**Comment by Templarian** [comment]
I do want to add this icon, but it needs another name. Just need to think of something.

- `palette-swatch-variant`
- ???

**Comment by erdemyilmaz06** [comment]
Color-Swatch-Card would be great

**Comment by erdemyilmaz06** [comment]
In fact, other one was for color, this one for material. So, "material-swatch-card" would be better for this icon.

**Comment by erdemyilmaz06** [comment]
We use these material cards for wood materials or fabrics.

**Comment by goyney** [comment]
[![palette-swatch-variant](https://materialdesignicons.com/icon/palette-swatch-variant)](https://materialdesignicons.com/icon/palette-swatch-variant)

**Comment by erdemyilmaz06** [comment]
Thank you very much indeed!
