### ISSUE TITLE
Add missing Material Design icon: Personal Hotspot

### ISSUE THREAD

**Issue by PuruVJ** [Templarian/MaterialDesign#5762]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It's the mobile hotspot/tethering icon already present in the official Material Design icons Library. 
2 iconsare missing to be precise:

1. wifi_tethering:
![image](https://user-images.githubusercontent.com/47742487/103913272-5fa61f00-512e-11eb-8f1d-6dc92ee97d39.png)

2. portable_wifi_off
![image](https://user-images.githubusercontent.com/47742487/103913413-81070b00-512e-11eb-81e3-c851795fcfe8.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/104057107-2c5ba280-51b7-11eb-92df-39554699f6cb.png)![image](https://user-images.githubusercontent.com/1015040/104057135-34b3dd80-51b7-11eb-9a14-24db4a30ef3f.png)

**Comment by Templarian** [comment]
Added these two (was testing a code change on the backend).
