### ISSUE TITLE
alarm-light-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#5764]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

to indicate the alarm lights are not flashing, Id appreciate if you'd consider adding an alarm-light-off icon. I am aware of the regular and -outline variant, but the latter doesnt really indicate an 'off' situation.
## Examples

the default diagonal line would suffice on the regular alarm-light.

thanks for considering.

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/104056711-860f9d00-51b6-11eb-969f-a1898274240b.png)![image](https://user-images.githubusercontent.com/1015040/104056724-8d36ab00-51b6-11eb-973f-c9a103da9f7c.png)

**Comment by Mariusthvdb** [comment]
great! thanks.
