### ISSUE TITLE
ruler-outline

### ISSUE THREAD

**Issue by RuneKlein** [Templarian/MaterialDesign#5767]
I have:

- [x] Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Same usage as the current "ruler" icon which represents e.g. units / distance, just as an outline version

## Examples

![ruler](https://user-images.githubusercontent.com/47398070/104163247-64045d80-53f6-11eb-8991-6b291949b557.png)

**Comment by Xenomorph99** [comment]
Unfortunately, I don't think an outlined version of `ruler` will be possible following our guidelines. Outline strokes need to be 2dps. Here's some more info: [Material Design: System Icons](https://material.io/design/iconography/system-icons.html#system-icon-metrics).

![image](https://user-images.githubusercontent.com/1837101/106938330-1371de80-66dc-11eb-9ace-e30795984d7a.png)

![ruler](https://user-images.githubusercontent.com/1837101/106937948-9a728700-66db-11eb-9bdb-616724663249.png)
![ruler-square](https://user-images.githubusercontent.com/1837101/106937956-9cd4e100-66db-11eb-9cf2-3f891e07d6dc.png)
![pencil-ruler](https://user-images.githubusercontent.com/1837101/106937951-9ba3b400-66db-11eb-99e6-abf344c725ac.png)
