### ISSUE TITLE
Jenkins icon 

### ISSUE THREAD

**Issue by regicsolutions** [Templarian/MaterialDesign#5768]
Jenkins icon

**Comment by Simran-B** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by PeterShaggyNoble** [comment]
This one is already available from Simple Icons:

[![Jenkins](https://user-images.githubusercontent.com/15157491/104338967-00119000-54ef-11eb-9b9c-a617eb71dc5d.png)](https://simpleicons.org/?q=Jenkins)
