### ISSUE TITLE
Vintage Filament Bulb Icon

### ISSUE THREAD

**Issue by dcwilli** [Templarian/MaterialDesign#5769]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

as a bulb icon in home assistant

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/55827604/104302330-5d6c0800-5514-11eb-8018-17b8079f1692.png)

**Comment by kineticscreen** [comment]
I've been meaning to make something like this. Difficult to get the classic design to communicate - almost impossible to stay within spec AND include the filament unfortunately.

![image](https://user-images.githubusercontent.com/39250334/104674153-3e998b80-5737-11eb-908d-a1036be5dbfe.png)

**Comment by LennardPlay** [comment]
Please don't leave us hanging. I need an icon for home assistant

**Comment by kineticscreen** [comment]
I've ended up just using the 'Hue Icons' library from HACS which has a number of filament bulbs. It also has other light types that have been more useful than the ones in Material Icons:
https://github.com/arallsopp/hass-hue-icons

**Comment by goyney** [comment]
> ...almost impossible to stay within spec AND include the filament unfortunately.

This is the issue and why something hasn't been added yet. We're not against the idea, we just need a design that works.

In regards to the Hue Icons library for Home Assistant, if you want to use that, by all means. While Home Assistant does consume our library as their primary set, we unfortunately cannot break spec unless there is not another option for a widely needed icon (the database icon is the perfect example of this). In this case, I think a light bulb variant with a filament might be cool, but it also might not be practical since it is simply a stylistic difference, as opposed to say the CFL lightbulb variant which is an actual different type of bulb.

Regardless, I still think this issue warrants exploration with our current `lightbulb` icons and a filament to see if it can be done while staying within spec.

**Comment by goyney** [comment]
I think this would be our best option:

![image](https://user-images.githubusercontent.com/1015040/131279265-03bcab6f-d2cd-4fcc-bd50-a60b3e753d66.png)![image](https://user-images.githubusercontent.com/1015040/131279286-c0b9427b-1007-4920-a98f-f9803c422d35.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7073888/Archive.zip)

**Comment by LennardPlay** [comment]
That one looks great 👍

**Comment by goyney** [comment]
[![lightbulb-variant](https://materialdesignicons.com/icon/lightbulb-variant)](https://materialdesignicons.com/icon/lightbulb-variant)[![lightbulb-variant-outline](https://materialdesignicons.com/icon/lightbulb-variant-outline)](https://materialdesignicons.com/icon/lightbulb-variant-outline)

**Comment by dcwilli** [comment]
Great work!

Love it

***@***.***
Daniel Williams
Student | Queensland University of Technology

Mobile 0404 792 838
Email ***@***.******@***.***>
Student Number n8293881

[Title: LinkedIn - Description: image of LinkedIn icon]<https://www.linkedin.com/in/daniel-williams-370213b1/> [Title: Twitter - Description: image of Twitter icon] <https://twitter.com/DanielW39657082>

**Comment by kineticscreen** [comment]
these look good, but they solve a different problem. These look like standard filament globes. The original idea was for the vintage style Edison bulbs and filaments.

**Comment by dcwilli** [comment]
Is this active in home assistant?

Kind Regards,


Daniel Williams

Student | Queensland University of Technology



Mobile 0404 792 838<tel:+61404792838>

Email ***@***.******@***.***>

Student Number n8293881<tel:+618293881>

________________________________

**Comment by goyney** [comment]
It was released in our packages yesterday. When Home Assistant bring in the update, it will be available there. Best thing is to watch their [changelog](https://rc.home-assistant.io/latest-release-notes/) for the announcement.
