### ISSUE TITLE
Umbrella

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#577]
3 variants:
![umbrella](https://cloud.githubusercontent.com/assets/1309249/9088570/f8c661b8-3b90-11e5-9474-1715f5daef8e.png) https://www.dropbox.com/s/80p61ezf19y8y3p/umbrella.svg?dl=0
![umbrella2](https://cloud.githubusercontent.com/assets/1309249/9088569/f8c6153c-3b90-11e5-9207-4739e00c0e67.png) https://www.dropbox.com/s/gdng7nei07t8h9x/umbrella2.svg?dl=0
![umbrella3](https://cloud.githubusercontent.com/assets/1309249/9088571/f8c91688-3b90-11e5-95a5-4df51b564dc5.png) https://www.dropbox.com/s/mnavf9ty423ls9l/umbrella3.svg?dl=0

**Comment by Templarian** [comment]
I kine of like the points, but wondering if it hurts the material'ness.

**Comment by CoDEmanX** [comment]
It looks a little odd at large sizes and definitely violates the 2px rule. The first two are pretty material.

**Comment by Templarian** [comment]
I'll get the first two added as `umbrella` `umbrella-outline`.

**Comment by CoDEmanX** [comment]
Okay, added links above.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/umbrella
https://materialdesignicons.com/icon/umbrella-outline
