### ISSUE TITLE
download-variant

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5770]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/77341534/104337921-43bbc800-54f6-11eb-9f41-447490e60a4a.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[download-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/5803215/download-variant.svg.zip)

**Comment by arnold-lepineux** [comment]
hello everyone,
first upload here for me. I felt like having a minimalistic download icon using the Material Design arrows would be a nice variation.
Feel free to comment and critic as you want, I am also looking for feedback.
Thank you

**Comment by goyney** [comment]
Looks good, would be named `tray-arrow-down`.

**Comment by goyney** [comment]
Added.
