### ISSUE TITLE
rolodex

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5772]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/77341534/104338843-3c48ee80-54f7-11eb-8583-816cae55edcc.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[calendar-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/5803243/calendar-variant.svg.zip)

**Comment by goyney** [comment]
I think this follow Material guidelines very well, but I'm unsure of the need for it.

**Comment by Templarian** [comment]
I don't hate it, but I'm seeing a rolodex and not a calendar.

🤔 Maybe we could work on adding a rolodex icon with some variants?

**Comment by goyney** [comment]
Our `card-account-*` icons fit the rolodex idea. I don't know what else to name this.

**Comment by goyney** [comment]
We're just going to add this using the generic "rolodex" name, and add aliases for "calendar" so it is found that way. 😄

**Comment by goyney** [comment]
[![rolodex](https://materialdesignicons.com/icon/rolodex)](https://materialdesignicons.com/icon/rolodex)[![rolodex-outline](https://materialdesignicons.com/icon/rolodex-outline)](https://materialdesignicons.com/icon/rolodex-outline)
