### ISSUE TITLE
refresh-variant

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5773]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/77341534/104339175-98137780-54f7-11eb-96cb-ed94d88ce931.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[refresh-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/5803258/refresh-variant.svg.zip)

**Comment by goyney** [comment]
Already exists as one of `cached`, `autorenew`, `sync`. In face, `cached` or `sync` should probably be deprecated since one is just a rotated version of the other.

**Comment by goyney** [comment]
Already exists as one of `cached`, `autorenew`, `sync`. In face, `cached` or `sync` should probably be deprecated since one is just a rotated version of the other.
