### ISSUE TITLE
reset

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5774]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![image](https://user-images.githubusercontent.com/77341534/104339534-fb9da500-54f7-11eb-82dd-979faaf01905.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[reset.svg.zip](https://github.com/Templarian/MaterialDesign/files/5803274/reset.svg.zip)

**Comment by goyney** [comment]
This already exists as `refresh` or `restore` (with a flip).
