### ISSUE TITLE
request for SRD currency icon

### ISSUE THREAD

**Issue by kevinhoogdorp** [Templarian/MaterialDesign#5775]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use for displaying Suriname Dollar

## Examples

[SRD]

**Comment by goyney** [comment]
From Wikipedia:

> The Surinamese dollar is normally abbreviated with the dollar sign $, or alternatively Sr$ to distinguish it from other dollar-denominated currencies.

That being said, its normal abbreviation is the `$` which we already have. I think that should be enough.

**Comment by Templarian** [comment]
Yeah, it looks like Sr$ isn't the symbol. They would mostly just use a dollar sign locally.

@kevinhoogdorp Did you have something in mind other than a `$`?

**Comment by kevinhoogdorp** [comment]
I was thinking more in the lines of


![SRD-2](https://user-images.githubusercontent.com/49961592/104965365-597d3180-59bd-11eb-9f2d-f1ceb0a09d35.png)
![SRD-1](https://user-images.githubusercontent.com/49961592/104965368-5b46f500-59bd-11eb-9006-2d0425873355.png)

**Comment by goyney** [comment]
That's not an official symbol for that currency and would break consistency with all other currency symbols we offer. I do not feel we should add that.

**Comment by kevinhoogdorp** [comment]
I see, no worries then
Thank you for your time.
