### ISSUE TITLE
ammunition-magazine

### ISSUE THREAD

**Issue by adlaws** [Templarian/MaterialDesign#5776]
Generic icons for magazines of ammunition, a "primary" and an alternate one. 

Aimed at supplementing the existing `mdi-ammunition` icon, and for being useful in FPS games and so on.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1201371/104410210-ce5a0100-55a2-11eb-9b4f-ec3f0fed52a6.png)

![image](https://user-images.githubusercontent.com/1201371/104410223-d6b23c00-55a2-11eb-8e41-6bd0960a52bf.png)

## Zip Download

[ammunition-magazine.zip](https://github.com/Templarian/MaterialDesign/files/5806581/ammunition-magazine.zip)

**Comment by Templarian** [comment]
Do these clip types have specific names we could use?

**Comment by adlaws** [comment]
Hmmm... that's a good question, and I'm hardly an expert… 😅 

Both are "box" magazines, so we can't really make a distinction on that basis. There are also "drum" and "tube" magazines, but the two presented are probably the most common, at least for the use case I'm targeting.

The top one (`ammunition-magazine`) is probably technically referred to as a "STANAG" or "NATO" magazine used in rifles and machine guns, while the second one is a pistol or handgun magazine.

How about `mdi-magazine-rifle` and `mdi-magazine-pistol`…? It's generic enough that it (hopefully) won't offend anyone…

...though there are always going to be people out there who really know their stuff who might point out that "Well, technically, the XYZ uses the ABC magazine so you can't really call it just a 'rifle' magazine because..."

If other contributors felt so inclined that would also leave space for `mdi-magazine-drum` and whatever else.

We should avoid calling the icon just `mdi-magazine` as it might collide in future with someone wanting a "magazine" icon representing the "newspapers and magazines" kind of magazine. This is why I initially suggested `ammunition-magazine`, even though it's a bit verbose.

For what it's worth, I'll here are a couple of references to justify my suggestions in case others question the choice track:
https://military.wikia.org/wiki/Magazine_(firearms)
https://en.wikipedia.org/wiki/Magazine_(firearms)

**Comment by Templarian** [comment]
I like the suggestion for `magazine-rifle` / `magazine-pistol`. That should work. The designs need some work. We try to stay away from 1px lines. It's best to exaggerate things. So 2px lines everywhere. Even for the individual rounds. This makes it easier to see at the 1:1 size.

**Comment by adlaws** [comment]
I kind of wanted to avoid the implication that the icon was also showing "number of rounds in the magazine", so the intent was to have a texture on the magazine rather than show actual rounds.

From your comment though, possibly I have failed there... 😅

Do these work better for you? (new zip file also attached)

![image](https://user-images.githubusercontent.com/1201371/104548335-8bb02b80-566b-11eb-8787-c8ac65f21bac.png)
![image](https://user-images.githubusercontent.com/1201371/104548362-9c60a180-566b-11eb-9cfb-81b521f913c8.png)

[mdi-magazines.zip](https://github.com/Templarian/MaterialDesign/files/5812461/mdi-magazines.zip)

**Comment by Templarian** [comment]
Pistol clip looks fine, but the angle of the line is off on the inside bottom of the rifle.

**Comment by adlaws** [comment]
Hmmm... like this, perhaps?

![image](https://user-images.githubusercontent.com/1201371/104552028-f1ec7c80-5672-11eb-8344-c03186642082.png)

[mdi-magazines.zip](https://github.com/Templarian/MaterialDesign/files/5812608/mdi-magazines.zip)

**Comment by adlaws** [comment]
Cheers! Thanks, as always, for your work on this awesome project. 👍

**Comment by goyney** [comment]
Both added.
