### ISSUE TITLE
BOM in scss/_functions.scss causes the scss compiler to fail

### ISSUE THREAD

**Issue by juliangilbey** [Templarian/MaterialDesign#5778]
For some reason, the file `scss/_functions.scss` begins with a byte-order mark, which causes scss to fail.  This can be removed using a command such as:
```
sed -i -e '1s/^\xEF\xBB\xBF//' scss/_functions.scss
```

**Comment by goyney** [comment]
I've never had any issues with this. Can you provide any more details about your setup?

**Comment by juliangilbey** [comment]
Ooh!  So there is code in the current Debian repository for removing the BOM "because it breaks scss", and I thought "why has no-one reported it?".  But I just tried it and it works fine, so perhaps it was a problem in an older version of scss.
So feel free to close this issue (and also apologies for the accidental duplicate - GitHub played up on me).  It might be nice to remove the BOM anyway: the file is entirely (7-bit) ASCII apart from the BOM, and none of the other scss files have a BOM.
Best wishes, Julian
