### ISSUE TITLE
Icon Request: Identification Card

### ISSUE THREAD

**Issue by quietmint** [Templarian/MaterialDesign#578]
Something to represent ID, driver license, etc.

**Comment by CoDEmanX** [comment]
Similar to https://materialdesignicons.com/icon/folder-account maybe?

![id](https://cloud.githubusercontent.com/assets/1309249/9091430/7f4899ae-3ba0-11e5-87e8-2cd283dcf95a.png) https://www.dropbox.com/s/te8ge3ve7go98hz/id.svg?dl=0

**Comment by CoDEmanX** [comment]
It is actually much like
[![account-card-details](https://materialdesignicons.com/icon/account-card-details)](https://materialdesignicons.com/icon/account-card-details)

**Comment by CoDEmanX** [comment]
@Templarian: alias?

**Comment by Templarian** [comment]
Yea, this one could use an alias. `identification-card`.

**Comment by Templarian** [comment]
Alias added.
