### ISSUE TITLE
attachment-variant

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5780]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/77341534/104600129-e603b900-5678-11eb-8e9a-beb83a94931e.png)

## Zip Download

[attachment-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/5814808/attachment-variant.svg.zip)

**Comment by goyney** [comment]
We have a horizontal and vertical paperclip. If you need it at an angle, you'll need to handle that via CSS or some other way. Thanks for the contribution, but we're not going to add this one.
