### ISSUE TITLE
compass-variant

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5781]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/77341534/104600443-4a267d00-5679-11eb-9321-8e4bb51339ae.png)

## Zip Download

[compass-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/5814820/compass-variant.svg.zip)

**Comment by goyney** [comment]
Unfortunately, this doesn't follow Material guidelines. Additionally, icons should be contextual, not informational. There are likely much better ways to indicate direction that provide a better user experience.

That said, thanks for the contribution, but we're going to pass on this one.
