### ISSUE TITLE
content-copy-full

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5782]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/77341534/104600728-ac7f7d80-5679-11eb-9968-557883ff8324.png)

## Zip Download

[content-copy-full.svg.zip](https://github.com/Templarian/MaterialDesign/files/5814832/content-copy-full.svg.zip)

**Comment by goyney** [comment]
This is insanely similar to `checkbox-multiple-blank` and doesn't really say "content."

**Comment by Templarian** [comment]
Having a stacked context in the bottom left is a `-multiple` modifier. This would have to be another name entirely.
