### ISSUE TITLE
direction-from

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5783]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/77341534/104601368-72fb4200-567a-11eb-85b1-7a60224603f9.png)

## Zip Download

[direction-from.svg.zip](https://github.com/Templarian/MaterialDesign/files/5814858/direction-from.svg.zip)

**Comment by goyney** [comment]
Duplicate of `ray-start-arrow`.
