### ISSUE TITLE
direction-to

### ISSUE THREAD

**Issue by arnold-lepineux** [Templarian/MaterialDesign#5784]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/77341534/104601484-97571e80-567a-11eb-82d5-ade4147703c6.png)

## Zip Download

[direction-to.svg.zip](https://github.com/Templarian/MaterialDesign/files/5814864/direction-to.svg.zip)

**Comment by goyney** [comment]
What's the use case for this? Would one of the `map-marker-*` icons be a better contextual icon to indicate a destination?

**Comment by goyney** [comment]
Closing because the `Needs More Info` tag was added quite a while ago without any further information provided. If you still have a need for this, please feel free to comment back and we can reopen to continue discussion. Thank you for your suggestion.
