### ISSUE TITLE
Suggestion: keyboard-tab-back

### ISSUE THREAD

**Issue by DabirSA** [Templarian/MaterialDesign#5785]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

- Complement a tab hotkey with a shift+tab hotkey in MATRIC.
- Could be relevant pretty much anywhere else that keyboard-tab is already used.

## Examples

Just flip keyboard-tab horizontally.

**Comment by goyney** [comment]
Normally, we would recommend flipped it yourself. However, this seems like a perfectly valid use case and I recommend we add it as `keyboard-tab-reverse`.

**Comment by goyney** [comment]
Added.
