### ISSUE TITLE
land

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5786]
I had a bunch of ideas for farmland inspired icons. These will be useful in agtech software (like the one I'm building).

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/104680416-17967780-56ad-11eb-9f0a-870738b47aa5.png)
![image](https://user-images.githubusercontent.com/2228347/104680430-136a5a00-56ad-11eb-86b7-69360ee74bc3.png)
![image](https://user-images.githubusercontent.com/2228347/104680435-17967780-56ad-11eb-8560-8a05283e404f.png)
![image](https://user-images.githubusercontent.com/2228347/104680442-28df8400-56ad-11eb-9f57-554efc9f792d.png)
![image](https://user-images.githubusercontent.com/2228347/104680476-3137bf00-56ad-11eb-9dfd-f634b296bf5e.png)
![image](https://user-images.githubusercontent.com/2228347/104680486-34cb4600-56ad-11eb-9f4a-931130bb7ee6.png)

## Zip Download

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/5818361/Archive.zip)

Thanks!

**Comment by goyney** [comment]
I don't get "land" from any of these. Most look like variations on our `view` outline variants. 😕

**Comment by jhil** [comment]
They were inspired by aerial views of farmland. 

![image](https://user-images.githubusercontent.com/2228347/104683026-4e6f8c00-56b3-11eb-8559-72847a0ed71d.png)
![image](https://user-images.githubusercontent.com/2228347/104683054-60e9c580-56b3-11eb-8f5a-014a6b9a303c.png)
![image](https://user-images.githubusercontent.com/2228347/104683191-a5756100-56b3-11eb-8ee2-0b713dbc340d.png)


Any thoughts on how to make that more clear?

The first one is a bit of a departure, so maybe that would warrant `fields` on it's own if that direction is chosen.

![image](https://user-images.githubusercontent.com/2228347/104683157-95f61800-56b3-11eb-8198-81014b4e5eac.png)

**Comment by jhil** [comment]
@goyney Perhaps `fields-` is a better base word than land? These would be especially helpful for agtech apps!

**Comment by goyney** [comment]
I don't really think the naming is the problem. These all just look like geometrical designs, which makes them abstract, which goes against Material guidelines. Top-down for these is likely not going to work.

**Comment by jhil** [comment]
Thank you for the feedback

**Comment by goyney** [comment]
I don't know what to do with these. I like them, I just don't know how to name them to be generic.

**Comment by goyney** [comment]
Still want to add these with generic names, but need so help brainstorming that. The bottom 5 look similar to our `view-` icons, but we already have a ton of those. Anyone have any ideas?

CC: @Templarian

**Comment by jhil** [comment]
How about plot-? Still relevant to my original land purpose, but generic enough to be used for other plotting needs.

**Comment by Templarian** [comment]
I don't like the prefix `plot-*` it may be confusing with graphs. `land-*` kind of works okay for this.

Agriculture is a huge industry that we should include icons for, so I think the possible overlap with `view` is fine.

**Comment by goyney** [comment]
Okay, originally proposed names it is! 😄

**Comment by jhil** [comment]
Nice resolution!

**Comment by goyney** [comment]
[![land-fields](https://materialdesignicons.com/icon/land-fields)](https://materialdesignicons.com/icon/land-fields)[![land-plots](https://materialdesignicons.com/icon/land-plots)](https://materialdesignicons.com/icon/land-plots)
[![land-plots-circle](https://materialdesignicons.com/icon/land-plots-circle)](https://materialdesignicons.com/icon/land-plots-circle)[![land-plots-circle-variant](https://materialdesignicons.com/icon/land-plots-circle-variant)](https://materialdesignicons.com/icon/land-plots-circle-variant)
[![land-rows-horizontal](https://materialdesignicons.com/icon/land-rows-horizontal)](https://materialdesignicons.com/icon/land-rows-horizontal)[![land-rows-vertical](https://materialdesignicons.com/icon/land-rows-vertical)](https://materialdesignicons.com/icon/land-rows-vertical)
