### ISSUE TITLE
tangram

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5787]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/104680640-9986a080-56ad-11eb-8013-6208b5ab8e86.png)

_I'm having trouble again getting the icon preview generator to work. Do we know if Figma's export encoding is compatible with this? My workflow is usually to flatten the icon into one vector before exporting the frame as SVG. Let me know if there's something I can do differently to be more helpful._ 

<img width="993" alt="Screenshot 2021-01-14 at 21 16 39@2x" src="https://user-images.githubusercontent.com/2228347/104680737-d18de380-56ad-11eb-9786-083a53aea8b8.png">
<img width="236" alt="Screenshot 2021-01-14 at 21 16 44@2x" src="https://user-images.githubusercontent.com/2228347/104680738-d2267a00-56ad-11eb-8f42-9403c049e75f.png">

## Zip Download

[tangram.zip](https://github.com/Templarian/MaterialDesign/files/5818376/tangram.zip)

**Comment by goyney** [comment]
Added.
