### ISSUE TITLE
greenhouse

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5788]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/104681409-7eb52b80-56af-11eb-94d1-b1a38f7cf4fe.png)

A few other explorations I didn't like as much:
<img width="2203" alt="Screenshot 2021-01-14 at 21 27 50@2x" src="https://user-images.githubusercontent.com/2228347/104681457-9d1b2700-56af-11eb-8e85-5791e526a0d4.png">

## Zip Download

[greenhouse.zip](https://github.com/Templarian/MaterialDesign/files/5818432/greenhouse.zip)

**Comment by jhil** [comment]
Whoops, I realized this is indeed a duplicate of https://github.com/Templarian/MaterialDesign/issues/2788.

**Comment by goyney** [comment]
> Whoops, I realized this is indeed a duplicate of #2788. Happy to migrate these suggestions to that ticket.

Please do!
