### ISSUE TITLE
cabin-a-frame

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5789]
A-frame cabin!

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/104682407-d48ad300-56b1-11eb-8cb6-a963649752ac.png)

(one more time, having trouble with the preview generator)

## Zip Download

[a-frame.zip](https://github.com/Templarian/MaterialDesign/files/5818499/a-frame.zip)

**Comment by jhil** [comment]
A few alternatives I didn't like as much: 
![image](https://user-images.githubusercontent.com/2228347/104682523-1a479b80-56b2-11eb-85ce-53f8155025ee.png)

**Comment by Xenomorph99** [comment]
I changed the title of this issue to not get confused with a-frame tents which we already have.

![tent](https://user-images.githubusercontent.com/1837101/106938688-8bd89f80-66dc-11eb-87f0-948e53749f15.png)

https://materialdesignicons.com/icon/tent

**Comment by goyney** [comment]
[![cabin-a-frame](https://materialdesignicons.com/icon/cabin-a-frame)](https://materialdesignicons.com/icon/cabin-a-frame)
