### ISSUE TITLE
venn-diagram

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5790]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/104683459-2fbdc500-56b4-11eb-9776-e08455a5489e.png)

Uses the forms from circle-multiple-outline as a starting place.

## Zip Download

[venn-diagram.svg.zip](https://github.com/Templarian/MaterialDesign/files/5818542/venn-diagram.svg.zip)

**Comment by goyney** [comment]
Duplicate of `set-none`. I've aliased it as `venn-diagram` as well.

**Comment by jhil** [comment]
No wonder I couldn't find it. Thanks!
