### ISSUE TITLE
App/Notification Badge icon request

### ISSUE THREAD

**Issue by MoOx** [Templarian/MaterialDesign#5791]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

I searched for "app", "badge", "notification", "unread" and didn't find any similar icon.

## Usage

This can be used as an alternative to classic _notification bells_ and is more "app" focused. For example, Apple use this kind of icons in their Settings app 

![IMG_38868E0FC997-1](https://user-images.githubusercontent.com/157534/104710710-b01a0f80-5720-11eb-892f-d0f96103f2d2.jpeg)

The bell with badge variant is a must have too :) 

## Examples

Here is SF Symbols "app.badge"

Include any example images so we know what the icon should look like.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/157534/104710345-43067a00-5720-11eb-8611-bb9388e7ed09.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/157534/104713716-8a8f0500-5724-11eb-8e42-61d58ef3f6ae.png">

Both variants would be nice to have!

**Comment by goyney** [comment]
This might be considered a new type of modifier.

@Templarian Your thoughts?

**Comment by Templarian** [comment]
I like the idea of adding this as a standard modifier. In context I think most would understand it. 👍

**Comment by goyney** [comment]
We've created a new icon overlay: "badge".

We've added these four icons: `checkbox-blank-badge`, `checkbox-blank-badge-outline`, `bell-badge`, `bell-badge-outline`.

**Comment by MoOx** [comment]
Thank you! I already saw the icons on the website (which is awesome), but where is the more appropriate place to follow a official release?

**Comment by MoOx** [comment]
I am curious to know the motivation that leads to the use of `checkbox-blank` instead of `square-rounded` (according to the idea I see in #4324 

Below `shape-square-rounded-plus` 
<img width="105" alt="image" src="https://user-images.githubusercontent.com/157534/105013074-28dddc00-5a3f-11eb-9346-2552117176ed.png">

**Comment by Templarian** [comment]
@MoOx While the icons are similar in style the use cases for `square-rounded` in design applications require the rounded edges to be more obvious. I think in this case it's fine having separate icons.

https://dev.materialdesignicons.com/contribute/icon-naming Explains the naming side of things in detail.

The ones you brought up could go either way. Bullseye is a little more descriptive to that type of target. Scope may make sense for that one, but `target` would be what most would think of probably.

**Comment by MoOx** [comment]
ok got it. no big deal :) 

I updated my comment about target/scope in the other issue. I just got that from sf symbols and this was making more sense to me (a French European guy that didn't no about bulleye as a word that could refer to target).

**Comment by Templarian** [comment]
@MoOx Hopefully the aliases can alleviate that in searching.

This actually comes up a lot since on the Core team (Pictogrammers now) we have like 5 or so languages (counting UK english) and we try to make the aliases as easy to search for as possible.
