### ISSUE TITLE
Dark Mode/Appearance icons

### ISSUE THREAD

**Issue by MoOx** [Templarian/MaterialDesign#5792]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Now that dark mode are popular in OS and apps, it would be nice to have icons for that (eg: some apps offer to switch appearance)

## Examples

Here is what I see that could be nice to have:

Google Material official dark mode icon
 
<img width="165" alt="image" src="https://user-images.githubusercontent.com/157534/104715936-7993c300-5727-11eb-82e0-8690e17313ae.png">

Google dark theme icon (android 11)

![Screenshot_20210115-115420](https://user-images.githubusercontent.com/157534/104716910-d6dc4400-5728-11eb-962c-43d25a603dc4.png)

Here is what Apple offers that might seems relevant

<img width="598" alt="image" src="https://user-images.githubusercontent.com/157534/104718305-fa07f300-572a-11eb-9df4-9da6e42bfe55.png">

And also the quick toggle "dark mode icon" from control center

![IMG_04C7BE620DBF-1 copy](https://user-images.githubusercontent.com/157534/104718530-4d7a4100-572b-11eb-98f7-85764899d58b.jpeg)

**Comment by goyney** [comment]
We have `circle-half-full` to match one of those:
![image](https://user-images.githubusercontent.com/1015040/104762873-b1e8d080-572a-11eb-8851-f12ba719ddaf.png)

This use case is basically exactly the same as your other issue (#5793) so I'm going to close this one. Feel free to continue the discussion in that issue.

**Comment by MoOx** [comment]
Oh sorry, I totally missed this one as I used https://mdisearch.com and I didn't saw the outline.
