### ISSUE TITLE
Night mode icon

### ISSUE THREAD

**Issue by MoOx** [Templarian/MaterialDesign#5793]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Night mode are something that every phones have this days and it would be cool to have icons for this

## Examples

Here is what I see that could be nice to have:

Google Material official dark mode icon
 
<img width="165" alt="image" src="https://user-images.githubusercontent.com/157534/104715936-7993c300-5727-11eb-82e0-8690e17313ae.png">

Google night icon

![Screenshot_20210115-115507](https://user-images.githubusercontent.com/157534/104717010-fbd0b700-5728-11eb-893c-30f81562bd71.png)

Here is what Apple offers that might seems relevant

<img width="598" alt="image" src="https://user-images.githubusercontent.com/157534/104718305-fa07f300-572a-11eb-9df4-9da6e42bfe55.png">

And also the quick toggle "night mode icon" from control center

![IMG_04C7BE620DBF-1](https://user-images.githubusercontent.com/157534/104718633-76023b00-572b-11eb-8249-9dba74494826.jpeg)

**Comment by goyney** [comment]
We have several icons that fulfill this use case:

![image](https://user-images.githubusercontent.com/1015040/104762662-57e80b00-572a-11eb-9fc1-19857b099e51.png)
![image](https://user-images.githubusercontent.com/1015040/104762693-6504fa00-572a-11eb-8d59-12cc602a1d42.png)
![image](https://user-images.githubusercontent.com/1015040/104762724-7221e900-572a-11eb-9548-5b91d3e8d4c2.png)

...Or any of our `moon` icons.

I'm not sure we need another.

**Comment by MoOx** [comment]
I did see theme and I don't think any of them match the iOS or android "simple partial moon with an angle".

**Comment by goyney** [comment]
> I did see theme and I don't think any of them match the iOS or android "simple partial moon with an angle".

To be fair, we're not here to match iOS and Android. And you can rotate any of our icons, so something like `moon-waning-crescent` with a 45 degree rotation might be all you need.

**Comment by MoOx** [comment]
I totally understand. Just curious: is this big "package of icons" supposed to have all the "official" google material one?

**Comment by goyney** [comment]
We don't proactively add them, but we tend to add them if someone requests one directly. There are some rare cases where we, as a contributor team, have decided a version of our icon is superior to the one Google provides and not add one (for example, our `virus` icon).

In this specific case, the Google icon does look like a waning moon, but we already have a full set of icons for moon phases, so I'm not sure we would add that particular one. We also name our icons in generic terms, so even if we did add it, it wouldn't be `dark-mode`, it would need to be something to do with the `moon`. This might be a case were we'll need to have a little internal discussion and make a decision. I'll start that and keep you posted. 😄

**Comment by MoOx** [comment]
I totally agree that the name should not be "dark-mode".
FYI, I am writing a react-native that will map icon as sf symbols on iOS and material icons for android. And after digging the naming, I found that very explicit name provided by Sf Symbols are a really cool thing even if sometimes it's not straight forward to find :)

<img width="132" alt="image" src="https://user-images.githubusercontent.com/157534/104763798-c1860a80-5766-11eb-87da-1517c7fb1323.png">

(For this reason, alias are a right choice)

Feel free to close, I was just "trying" to contribute somehow.

**Comment by Soutea** [comment]
@mririgoyen Would you re-consider opening this issue?

An alternative to `weather-night` without the stars would be nice and perhaps more useful?
