### ISSUE TITLE
Snapcast logo

### ISSUE THREAD

**Issue by 70MM13** [Templarian/MaterialDesign#5796]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like to us this in a Home Assistant dashboard, on a control panel

## Examples
![](https://raw.githubusercontent.com/badaix/snapcast/master/doc/web_hi_res_512.png)

logo and original svg's are here: 
https://raw.githubusercontent.com/badaix/snapcast/master/doc/

**Comment by Templarian** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
