### ISSUE TITLE
Remove `angularjs`

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#5798]
We have two Angular icons: `angular` and `angularjs`. The latter is just an outlined version of the first. Being a brand icon, we must follow Angular's brand, which does not offer an outlined version of their logo.

We should remove `angularjs`.

**Comment by Templarian** [comment]
This one shouldn't be removed. The `angularjs` logo is bordered. The `angular` one is solid. 👍

**Comment by goyney** [comment]
Then I would say `angularjs` should be renamed `angular-outline`. Thoughts?

**Comment by Templarian** [comment]
They are separate frameworks entirely. Going to leave this as is in 6.0. We can talk about removing it entirely in 7 or 8 as the framework is phased out. Right now it's still used a lot.
