### ISSUE TITLE
Expression Design

### ISSUE THREAD

**Issue by suprak** [Templarian/MaterialDesign#580]
I used to open the ModernUIIcons in Expression Design and manipulate them.
Now with the new portal, although the XAML code for them exists, there's no direct way for me to open the icons in Microsoft Expression Design.

Any recommendations for tools to use? Or how to get Expression Design to open SVG/XAML?

**Comment by suprak** [comment]
D'oh!
I didn't realize that this repo contains all the design files.

Awesome!

**Comment by Templarian** [comment]
Yep, no problem. There are a few contributor icons I have yet to back port into the .design source files. If you see any let me know.

For future reference generally SVG -> EPS / AI converts will import nice.

**Comment by CoDEmanX** [comment]
I had some trouble to import SVG in Expression Design via PDF export from InkScape, then rename to `.ai`. Seems to be related to DPI settings. It also didn't position the icon right, it was complete off-pixel but pixel-perfect in the original SVG...

**Comment by Templarian** [comment]
So, AI exports at 72 DPI so simply open it and then go to file -> document size -> remember the width then set it to 96 and put the width back in. Hit okay.

**Comment by CoDEmanX** [comment]
Thanks for the hint, I only tried 96 and 90. 72 might solve it.
