### ISSUE TITLE
layers-edit

### ISSUE THREAD

**Issue by ButchMonkey** [Templarian/MaterialDesign#5802]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

The repo currently has: layers-plus, layers-remove and layers-minus. I am proposing layers-edit
The icon below is the same base as layers-plus with the pencil icon in the place of the "+" to the same dimensions. (I would assume this covers for following the material guide-lines)

## Preview

![image](https://user-images.githubusercontent.com/9367266/105212244-21a0f600-5b45-11eb-9f6a-3b22fbe8f7a8.png)
![image](https://user-images.githubusercontent.com/9367266/105213637-d7b90f80-5b46-11eb-8f2e-c295527088fa.png)

## Zip Download

[layers-edit.zip](https://github.com/Templarian/MaterialDesign/files/5844262/layers-edit.zip)

**Comment by goyney** [comment]
[![layers-edit](https://materialdesignicons.com/icon/layers-edit)](https://materialdesignicons.com/icon/layers-edit)
