### ISSUE TITLE
File with location marker

### ISSUE THREAD

**Issue by timautin** [Templarian/MaterialDesign#5804]
Hello,

In the same way we have a marker folder :
![folder-marker-2](https://user-images.githubusercontent.com/3846288/105224161-21145980-5b5d-11eb-9e92-6b09e2693f36.png)

It would be nice to have a marker file, looking like this:
![file-cog](https://user-images.githubusercontent.com/3846288/105224184-24a7e080-5b5d-11eb-9d87-ddc49febbe12.png)

But with a marker icon instead of the settings icon.

**Comment by Templarian** [comment]
Tie it into this one, but `image` / `image-outline` needs it also.

**Comment by timautin** [comment]
Don't you mean file-image / file-image-outline?

**Comment by Templarian** [comment]
Both could probably benefit from this overlay. 👍

**Comment by Xenomorph99** [comment]
These two work perfect with the marker overlay.

![file-marker](https://user-images.githubusercontent.com/1837101/106829815-1f14c500-664a-11eb-8b0f-7080a82ceab4.png)
![file-marker-outline](https://user-images.githubusercontent.com/1837101/106829814-1f14c500-664a-11eb-8d31-102cdcf2ee1c.png)

However, these ones seem a little questionable. Let me know what you guys think.

![file-image-marker](https://user-images.githubusercontent.com/1837101/106829813-1f14c500-664a-11eb-99b1-1558b74ccfca.png)
![file-image-marker-outline](https://user-images.githubusercontent.com/1837101/106829811-1f14c500-664a-11eb-8cc9-f57c3153d372.png)

![image-marker](https://user-images.githubusercontent.com/1837101/106829802-1c19d480-664a-11eb-9a23-d504a747aed1.png)
![image-marker-outline](https://user-images.githubusercontent.com/1837101/106829797-1b813e00-664a-11eb-9999-d6a50cc7505f.png)

[file-image-marker.zip](https://github.com/Templarian/MaterialDesign/files/5922484/file-image-marker.zip)

**Comment by timautin** [comment]
@Xenomorph99 Thanks, the file-marker looks pretty good!
I agree for the file-image-marker, but I'm leaving open, if @Templarian wants to answer.

**Comment by Templarian** [comment]
These look great @Xenomorph99. They should be added shortly. 👍

**Comment by timautin** [comment]
`These look great @Xenomorph99. They should be added shortly. 👍 `

Great, I'm closing the issue then!
Thanks guys 🙂

**Comment by timautin** [comment]
`These look great @Xenomorph99. They should be added shortly. 👍`

Great, I'm closing the issue then!
Thanks guys 🙂

**Comment by Templarian** [comment]
@timautin Sorry for the confusion, @Xenomorph99 has to add them into our system still. You'll see them in the history page once they are added.

https://dev.materialdesignicons.com/history

**Comment by timautin** [comment]
No worries! @Xenomorph99 Please post a message here once it's done, in case I miss it in the history page.

**Comment by Xenomorph99** [comment]
I just added them @timautin 👍
