### ISSUE TITLE
virus-off and virus virus-off-outline

### ISSUE THREAD

**Issue by victor-perez** [Templarian/MaterialDesign#5806]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm currently using the `virus` icon, but I would  also like to have a `virus-off` icon when someone doesn't have virus.

## Examples

Just the standard off format of MDI

**Comment by goyney** [comment]
[![virus-off](https://materialdesignicons.com/icon/virus-off)](https://materialdesignicons.com/icon/virus-off)[![virus-off-outline](https://materialdesignicons.com/icon/virus-off-outline)](https://materialdesignicons.com/icon/virus-off-outline)
