### ISSUE TITLE
progress-review

### ISSUE THREAD

**Issue by valentingavran** [Templarian/MaterialDesign#5808]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Besides the current progress icons, another icon representing a review progress would be very handy.

## Examples

The icon should look like progress-check on the outside and in the middle the check symbol could be replaced by account-clock.

**Comment by goyney** [comment]
We have `progress-clock`. There's no way we're fitting `account-clock` within the progress circle.

**Comment by valentingavran** [comment]
In my case, I already use progress-clock for tasks that are queued. While the tasks are being executed I use progress-wrench and after they are completed progress-check. But between executing and completing there is sometimes a review phase and for this an icon would be really handy.

It does not have to be account-clock if it's to large. Maybe there is another option.

**Comment by steodor** [comment]
Given that the most meaningful icon regarding `review` is `message-draw` (which has `rate-review` as alias), i tried placing the idiom from that one into the `progress` circle. As you can see, it's not the most fortunate result. In the first one it's too big (the pencil approaches the circle too close). In the second one i tried making it a bit smaller but now the horizontal line next to the pencil is at half dp offset, making it a bit blurry at 24dp. I also tried making it a full dp smaller but then it's too small and not centered vertically, so after centering it would still end up at a half-dp offset. Personally i'm not very satisfied with the result (and wouldn't include it in the library if it was up to me) but maybe someone else can make it fit better?

@valentingavran Meanwhile if it's good enough for your use-case, you can use the path from the attached `.svg` directly.
![image](https://user-images.githubusercontent.com/4397338/107198829-467ae180-69fe-11eb-86bf-bb6647d24e74.png)![image](https://user-images.githubusercontent.com/4397338/107198839-48dd3b80-69fe-11eb-858f-001ebc5e38f8.png)
[progress-review.zip](https://github.com/Templarian/MaterialDesign/files/5942449/progress-review.zip)

**Comment by steodor** [comment]
Here i took the `edit` modifier pencil (version 1) and then the same from the `comment-edit-outline` icon (version 2) because it's smaller, trying to see which one would fit better. This would be `progress-edit` of course but maybe it's close enough semantically?
![image](https://user-images.githubusercontent.com/4397338/107202546-fce0c580-6a02-11eb-981a-35ec094d394c.png)![image](https://user-images.githubusercontent.com/4397338/107202552-ff431f80-6a02-11eb-81cf-08b5a29dc9e0.png)
[progress-edit.zip](https://github.com/Templarian/MaterialDesign/files/5942724/progress-edit.zip)

**Comment by valentingavran** [comment]
Thanks for the great designs. Like you, I'm not completely convinced by the` progress-review-*` designs.

The `progress-edit-*` designs, on the other hand, look very good! But as you already guessed, I don't know if the icons say exactly that what I aim for.

What if there was a star in the center, as mentioned before? Would that be possible?

**Comment by steodor** [comment]
Sure, no problem :)
![image](https://user-images.githubusercontent.com/4397338/107418845-cfd60500-6b1f-11eb-8150-a15386d3c1cb.png)
[progress-star.zip](https://github.com/Templarian/MaterialDesign/files/5953887/progress-star.zip)

**Comment by goyney** [comment]
[![progress-pencil](https://materialdesignicons.com/icon/progress-pencil)](https://materialdesignicons.com/icon/progress-pencil)[![progress-star](https://materialdesignicons.com/icon/progress-star)](https://materialdesignicons.com/icon/progress-star)
