### ISSUE TITLE
conversation icon

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#581]
Maybe I haven't found it but a conversation icon would be great.

**Comment by Templarian** [comment]
Probably any of the `message-*` icons would work for a conversation.

**Comment by Templarian** [comment]
Also @matthew2402 add a avatar to your account. Makes it quicker to identify reoccurring users in this repo. :smile:

**Comment by CoDEmanX** [comment]
`forum` is the best in my opinion:
https://materialdesignicons.com/icon/forum

**Comment by Templarian** [comment]
Forgot the name of that one. Knew it existed.

**Comment by CoDEmanX** [comment]
Yeah, it could really use some tags (chat, conversation, talk, ...)

**Comment by matthew2402** [comment]
@Templarian Alright Sir, I will :D
@CoDEmanX thanks, I also knew that it exists but message or conversation tags yielded no result.
