### ISSUE TITLE
air-pressure

### ISSUE THREAD

**Issue by reinhapa** [Templarian/MaterialDesign#5810]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Use within home assistant or similar application to distinguish air pressure values like thermometer icons.

## Examples

Include any example images so we know what the icon should look like.

**Comment by achebotarev** [comment]
It looks similar to https://github.com/Templarian/MaterialDesign/issues/4753
