### ISSUE TITLE
monetization_on

### ISSUE THREAD

**Issue by shpaginoleg7755** [Templarian/MaterialDesign#5812]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by shpaginoleg7755** [comment]
For menus in App

**Comment by Templarian** [comment]
@shpaginoleg7755 We're need to need a lot more context on this one and examples. The template should be filled out with the required information.

**Comment by goyney** [comment]
Closing because the `Needs More Info` tag was added quite a while ago without any further information provided. If you still have a need for this, please feel free to comment back and we can reopen to continue discussion. Thank you for your suggestion.
