### ISSUE TITLE
Delivery truck icon

### ISSUE THREAD

**Issue by martareg** [Templarian/MaterialDesign#5813]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

![truck-mat-design](https://user-images.githubusercontent.com/77104115/105632659-9aa99180-5e54-11eb-8de3-40c83561ad8e.png)

[truck-mat-design.zip](https://github.com/Templarian/MaterialDesign/files/5862375/truck-mat-design.zip)

@harsimranmaan

**Comment by JamesCoyle** [comment]
We already have `truck-check` and `truck-check-outline`.

[![](https://materialdesignicons.com/icon/truck-check)](https://materialdesignicons.com/icon/truck-check)
[![](https://materialdesignicons.com/icon/truck-check-outline)](https://materialdesignicons.com/icon/truck-check-outline)
