### ISSUE TITLE
math-or

### ISSUE THREAD

**Issue by erdemyilmaz06** [Templarian/MaterialDesign#5815]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

We use these icons for filter query building or advanced filters. They are used for mathematical AND, OR and XOR functions.

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![math-or](https://user-images.githubusercontent.com/77012754/105710123-bb8ee700-5f27-11eb-9e87-c45af03f0e7b.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[math-or.zip](https://github.com/Templarian/MaterialDesign/files/5866689/math-or.zip)

**Comment by goyney** [comment]
This would be included already as `set-all`.
