### ISSUE TITLE
brush-off

### ISSUE THREAD

**Issue by digoburigo** [Templarian/MaterialDesign#5817]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

When I have any draw tool active i want to show a button with this icon to deactivate the draw tool

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/28462822/105726879-47454b00-5f09-11eb-92d4-e85e14c29233.png)
![image](https://user-images.githubusercontent.com/28462822/105726934-54623a00-5f09-11eb-8b48-450b9a5b318e.png)

**Comment by steodor** [comment]
Hi, would this do the job?
![image](https://user-images.githubusercontent.com/4397338/105765760-8ef7c100-5f61-11eb-9463-22de14f48db7.png)

If yes, here's the svg path: [brush-off.zip](https://github.com/Templarian/MaterialDesign/files/5869678/brush-off.zip)

**Comment by goyney** [comment]
Close! The `off` modifier just needed to follow our template, so I made that modification. This has been added, once you hit 5 unique contributions, we'll get you added as a contributor. 😄 

[![brush-off](https://materialdesignicons.com/icon/brush-off)](https://materialdesignicons.com/icon/brush-off)
