### ISSUE TITLE
missed mdi-face-man

### ISSUE THREAD

**Issue by nuriakman** [Templarian/MaterialDesign#5819]
There is no mdi-face-man icon appear on screen when I use. BUT there is same icon named: mdi-face

**Comment by Templarian** [comment]
Our database is getting updated for v6.0 which is being worked on right now.

Read More: https://github.com/Templarian/MaterialDesign/issues/5409

https://pictogrammers.github.io/@mdi/font/5.9.55/ You can use this to see your specific version.
