### ISSUE TITLE
Contribute some icons

### ISSUE THREAD

**Issue by krambertech** [Templarian/MaterialDesign#582]
Hi, I just wanted to add some icons to the collection, but the form on the site is disabled. I checked them in [https://materialdesignicons.com/custom](https://materialdesignicons.com/custom) and they seem ok.

Find them [in dropbox](https://www.dropbox.com/sh/8fj8uzgg53mfrea/AACTPbgM7wwInQXQsDm-e5Pia?dl=0)

**Comment by Templarian** [comment]
Awesome. I'm out tonight for an event, but you should see them added in tomorrow.

Did you want to become a contributor by the way? I won't have the contributor system online again for at least a month, lot of changes going on to support some new features.

If you decide to (doesn't have to be now, in the future I can switch over the icons to the account) the details below are needed:
- email (will be deleted from the comment once added to the system)
- First [Last] (or company name)
- 100x100 PNG headshot (or company Logo or github avatar)
- Twitter
- Website Url
- Short bio (like 140 characters short).
- GitHub (assume this one)

**Comment by krambertech** [comment]
I'd like to, here's the information:
 - k.porshnieva@gmail.com
 - Kateryna Porshnieva
 - [picture](https://en.gravatar.com/userimage/91319862/04c02ec50c5bf96006cf9ca0c6efa5da.jpg?size=100)
 - krambertech
 - no website :(
 - Javascript developer from Ukraine, love material design and React.js
 - @krambertech

**Comment by Templarian** [comment]
https://materialdesignicons.com/contributor/Kateryna-Porshnieva

Welcome to the contributor team! I'll be sending an email out once the contributor panel is back online.
