### ISSUE TITLE
archive-(plus|minus|remove)

### ISSUE THREAD

**Issue by dandencker** [Templarian/MaterialDesign#5820]
I have:
- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 
 
## Usage
For deleting / removing archive

## Examples
**Base icon:** 
archive-outline

**With "x" to indicate remove - like this example (for movie):**
movie-remove-outline

**Ideas for related icons:**
"+" for add/append
"-" for substract/delete

**Comment by Xenomorph99** [comment]
Here's a full set of modifiers on [`archive`](https://materialdesignicons.com/icon/archive) and [`archive-outline`](https://materialdesignicons.com/icon/archive-outline):

![archive-plus](https://user-images.githubusercontent.com/1837101/106644542-72065380-6548-11eb-84c8-e498493e8ea7.png)
![archive-plus-outline](https://user-images.githubusercontent.com/1837101/106644541-72065380-6548-11eb-9226-d753e97ecc3a.png)

![archive-minus](https://user-images.githubusercontent.com/1837101/106644532-70d52680-6548-11eb-9693-42816749d38a.png)
![archive-minus-outline](https://user-images.githubusercontent.com/1837101/106644530-70d52680-6548-11eb-865d-3a47ab6322dd.png)

![archive-check](https://user-images.githubusercontent.com/1837101/106644508-6e72cc80-6548-11eb-97c4-f8fc65a91f4d.png)
![archive-check-outline](https://user-images.githubusercontent.com/1837101/106644507-6dda3600-6548-11eb-9c16-73a78bf275cd.png)

![archive-remove](https://user-images.githubusercontent.com/1837101/106644549-73378080-6548-11eb-80b9-fc70c465e984.png)
![archive-remove-outline](https://user-images.githubusercontent.com/1837101/106644547-729eea00-6548-11eb-8b81-62f9903e937b.png)

![archive-off](https://user-images.githubusercontent.com/1837101/106644540-72065380-6548-11eb-8ac6-b463740b5ce1.png)
![archive-off-outline](https://user-images.githubusercontent.com/1837101/106644539-716dbd00-6548-11eb-96dd-508c0e0f49a8.png)

![archive-cog](https://user-images.githubusercontent.com/1837101/106644513-6f0b6300-6548-11eb-8405-c9f7047b52b2.png)
![archive-cog-outline](https://user-images.githubusercontent.com/1837101/106644512-6f0b6300-6548-11eb-9bc6-03b5825fd3d3.png)

![archive-settings](https://user-images.githubusercontent.com/1837101/106644555-73d01700-6548-11eb-8c39-051a8616f65e.png)
![archive-settings-outline](https://user-images.githubusercontent.com/1837101/106644554-73d01700-6548-11eb-821f-fb2d6056232c.png)

![archive-edit](https://user-images.githubusercontent.com/1837101/106644517-6f0b6300-6548-11eb-9e23-d2b06ce19262.png)
![archive-edit-outline](https://user-images.githubusercontent.com/1837101/106644515-6f0b6300-6548-11eb-9196-93f363848d5d.png)

![archive-cancel](https://user-images.githubusercontent.com/1837101/106644505-6dda3600-6548-11eb-843e-bf16c2f042d3.png)
![archive-cancel-outline](https://user-images.githubusercontent.com/1837101/106644502-6d419f80-6548-11eb-96be-f552625e8b57.png)

![archive-lock](https://user-images.githubusercontent.com/1837101/106644523-703c9000-6548-11eb-9094-fe68c3dec0d5.png)
![archive-lock-outline](https://user-images.githubusercontent.com/1837101/106644522-703c9000-6548-11eb-8833-6de933b7f335.png)

![archive-lock-open](https://user-images.githubusercontent.com/1837101/106644521-703c9000-6548-11eb-854c-fec25c991a8b.png)
![archive-lock-open-outline](https://user-images.githubusercontent.com/1837101/106644520-6fa3f980-6548-11eb-8991-71e37e5bc769.png)

![archive-eye](https://user-images.githubusercontent.com/1837101/106644519-6fa3f980-6548-11eb-8ff8-809e3b4064e8.png)
![archive-eye-outline](https://user-images.githubusercontent.com/1837101/106644518-6fa3f980-6548-11eb-94d5-a8736ed3791f.png)

![archive-star](https://user-images.githubusercontent.com/1837101/106644558-7468ad80-6548-11eb-8b03-6d3963a264db.png)
![archive-star-outline](https://user-images.githubusercontent.com/1837101/106644556-73d01700-6548-11eb-9121-1793de00abd1.png)

![archive-marker](https://user-images.githubusercontent.com/1837101/106644527-70d52680-6548-11eb-8a7f-ea78a025be3a.png)
![archive-marker-outline](https://user-images.githubusercontent.com/1837101/106644524-703c9000-6548-11eb-9be8-c10c2a0defa7.png)

![archive-refresh](https://user-images.githubusercontent.com/1837101/106644546-729eea00-6548-11eb-96ed-91eb8de53e61.png)
![archive-refresh-outline](https://user-images.githubusercontent.com/1837101/106644544-729eea00-6548-11eb-800e-24b5c4d8c8a5.png)

![archive-sync](https://user-images.githubusercontent.com/1837101/106644563-7468ad80-6548-11eb-8e0d-cd43b5ea0c6f.png)
![archive-sync-outline](https://user-images.githubusercontent.com/1837101/106644559-7468ad80-6548-11eb-814a-09b5cc953a0c.png)

![archive-music](https://user-images.githubusercontent.com/1837101/106644536-716dbd00-6548-11eb-81a1-d525c5c303f4.png)
![archive-music-outline](https://user-images.githubusercontent.com/1837101/106644534-716dbd00-6548-11eb-8a5b-f28c7dc09a7c.png)

![archive-search](https://user-images.githubusercontent.com/1837101/106644553-73378080-6548-11eb-85ef-4972c7f2fc30.png)
![archive-search-outline](https://user-images.githubusercontent.com/1837101/106644551-73378080-6548-11eb-9e31-5b8a902e2af6.png)

![archive-clock](https://user-images.githubusercontent.com/1837101/106644510-6e72cc80-6548-11eb-9ccf-b508d0c5200a.png)
![archive-clock-outline](https://user-images.githubusercontent.com/1837101/106644509-6e72cc80-6548-11eb-9b03-b13fab3ce78f.png)

### Download
[archive-icons.zip](https://github.com/Templarian/MaterialDesign/files/5913538/archive-icons.zip)

**Comment by Xenomorph99** [comment]
Added
