### ISSUE TITLE
Document Split

### ISSUE THREAD

**Issue by anthonyChaussin-d4e** [Templarian/MaterialDesign#5826]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/70881374/106268775-d618d700-622b-11eb-9bb1-0a2018a8688e.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[DocumentSplit.zip](https://github.com/Templarian/MaterialDesign/files/5893696/DocumentSplit.zip)

## Description
Name : document_split
Description : for split/save document in two (or more) parts

**Comment by Templarian** [comment]
@anthonyChaussin-d4e Look at `file-compare` or `select-compare`. I think you may have exported incorrectly. Looking at the grid above the lines should be snapped to the grid.

For proportions icons like this shouldn't touch the edges on the left and right. Keeping them 2dp (display pixel) from the sides is ideal. Simplify the amount of lines in the document also to cut down to make room for 2dp text lines might look nicer.

I like the idea for this icon after some tweaks.

**Comment by anthonyChaussin-d4e** [comment]
Hello @Templarian,thanks for your reply, I Have done some changes, I let you tell me if it's better.

##Preview 
![image](https://user-images.githubusercontent.com/70881374/106442781-fc34b600-647b-11eb-81d3-50a633f8a115.png)

##ZIP file

[document-split.zip](https://github.com/Templarian/MaterialDesign/files/5903187/document-split.zip)

I've try to reduce the number of lines but i don't know if it has worked

**Comment by steodor** [comment]
This is closer i guess? Not sure on the dividers but at least i cleaned the paths :)
![image](https://user-images.githubusercontent.com/4397338/107160589-dfc6db00-699f-11eb-8eb2-71f9a7113a8c.png)![image](https://user-images.githubusercontent.com/4397338/107160696-7c897880-69a0-11eb-93c0-f972cf035259.png)
[document-split.zip](https://github.com/Templarian/MaterialDesign/files/5940110/document-split.zip)

**Comment by steodor** [comment]
And this is to within 1dp off the edge, if by any chance it helps make the icon more clear:
![image](https://user-images.githubusercontent.com/4397338/107160822-3da7f280-69a1-11eb-97f2-ecb5c6ae6a11.png)![image](https://user-images.githubusercontent.com/4397338/107160843-65975600-69a1-11eb-84eb-f35e7fe4bc62.png)
[document-split.zip](https://github.com/Templarian/MaterialDesign/files/5940118/document-split.zip)

**Comment by goyney** [comment]
These are good attempts, but my major issue is the way the pages hang off the sides of the artboard.

I still think there are a few icons we currently have that solve this use case in the right context, such as `format-page-break` or `file-replace(-outline)`.

I'll leave this open for a little while longer if someone wants to take another stab at these, but as it currently stands, nothings really ready to go into the library yet.

**Comment by steodor** [comment]
Really good points. I see `format-page-break` working best in this scenario, but just in case that's already used in the same app and might generate confusion (and closer to the initial request), how about a vertically split page break?

**Comment by goyney** [comment]
[![format-page-split](https://materialdesignicons.com/icon/format-page-split)](https://materialdesignicons.com/icon/format-page-split)
