### ISSUE TITLE
Update Hamburger & Add Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5827]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

I feel that our current [`hamburger`](https://materialdesignicons.com/icon/hamburger) icon is hard to read when it's really small.

![hamburger](https://user-images.githubusercontent.com/1837101/106339230-2b1c1380-6253-11eb-86f1-a4f71d38a942.png)

In contrast, the hamburger in our [`food`](https://materialdesignicons.com/icon/food) icon feels easier to read because of the balanced proportions.

![food](https://user-images.githubusercontent.com/1837101/106338381-ebecc300-6250-11eb-8c2a-a0d4256eb541.png)

I tried scaling up the hamburger in [`food`](https://materialdesignicons.com/icon/food), but it didn't look right.

I propose we replace our current [`hamburger`](https://materialdesignicons.com/icon/hamburger) icon with this new one. The rounded top bun and the slightly extended beef patty make it easy to read when it's really small.  

![hamburger](https://user-images.githubusercontent.com/1837101/106338918-46d2ea00-6252-11eb-94ff-8e5183e9d3ed.png)

It would be awesome to add these modifiers as well:

![hamburger-off](https://user-images.githubusercontent.com/1837101/106339093-d11b4e00-6252-11eb-97cb-8b3dc6baade1.png)

![hamburger-plus](https://user-images.githubusercontent.com/1837101/106339094-d1b3e480-6252-11eb-80a6-cc4b8fc7861e.png)

![hamburger-minus](https://user-images.githubusercontent.com/1837101/106339092-d11b4e00-6252-11eb-9a12-2e419eacca10.png)

![hamburger-check](https://user-images.githubusercontent.com/1837101/106339090-d082b780-6252-11eb-9128-cd59833ac52f.png)

![hamburger-remove](https://user-images.githubusercontent.com/1837101/106339095-d1b3e480-6252-11eb-83d7-072b3d2fcd7e.png)

## Zip Download

[hamburger-icons.zip](https://github.com/Templarian/MaterialDesign/files/5896962/hamburger-icons.zip)

**Comment by Templarian** [comment]
Agreed! Lets get these added/updated for 6.0. Good eye.

**Comment by Xenomorph99** [comment]
Added and updated
