### ISSUE TITLE
3 legged stool icon

### ISSUE THREAD

**Issue by RouNNdeL** [Templarian/MaterialDesign#5828]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The icon should represent a simple 3 legged stool. There's quite a lot of seat/chair icons but nothing that quite captures the simplicity of a stool. 

## Examples

![](https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQj2mM9OtmP_UFFT_nPKDGRY0gK5G3Tg3wY0Q&usqp=CAU)

**Comment by steodor** [comment]
A first version:
![image](https://user-images.githubusercontent.com/4397338/107159906-9f655e00-699b-11eb-858c-09408bd4e948.png)![image](https://user-images.githubusercontent.com/4397338/107159938-df2c4580-699b-11eb-86ac-a566ecfd2feb.png)
[stool.zip](https://github.com/Templarian/MaterialDesign/files/5940042/stool.zip)

**Comment by steodor** [comment]
Second version, slightly better i think?
![image](https://user-images.githubusercontent.com/4397338/107160132-059eb080-699d-11eb-9e66-6e34fc074672.png)![image](https://user-images.githubusercontent.com/4397338/107160136-0899a100-699d-11eb-953d-45f2e2b9e555.png)
[stool.zip](https://github.com/Templarian/MaterialDesign/files/5940054/stool.zip)

**Comment by RouNNdeL** [comment]
Yea, I personally like the second one better.

**Comment by goyney** [comment]
[![stool](https://materialdesignicons.com/icon/stool)](https://materialdesignicons.com/icon/stool)[![stool-outline](https://materialdesignicons.com/icon/stool-outline)](https://materialdesignicons.com/icon/stool-outline)
