### ISSUE TITLE
Apple Photos

### ISSUE THREAD

**Issue by dotbran** [Templarian/MaterialDesign#583]
probably just the silhouette of the ellipse things

**Comment by Templarian** [comment]
I don't think this can really be represented correctly in monotone colors.

**Comment by CoDEmanX** [comment]
Would probably look like a circle at 24px, and like a blossom at larger scales...

![Apple Photos](http://i.imgur.com/8K2fxXN.jpg)

**Comment by Templarian** [comment]
Yea, I'm going to close this as not possible. The logo will not be recognizable at the required 24x24 size constraints.

**Comment by CoDEmanX** [comment]
Looks funny, but definitely not like the Apple logo :laughing: 
![swirly-thing](https://cloud.githubusercontent.com/assets/1309249/9147497/2a40c0c0-3d68-11e5-9aba-e60cc838f5d1.png)

This isn't much better:
![apple-photos](https://cloud.githubusercontent.com/assets/1309249/9147564/eea32700-3d68-11e5-9f39-9fb5e9dcc39e.png)
![apple-photos2](https://cloud.githubusercontent.com/assets/1309249/9147565/eea6462e-3d68-11e5-8d11-a4a429a66b70.png)
