### ISSUE TITLE
cctv-off

### ISSUE THREAD

**Issue by jhein05** [Templarian/MaterialDesign#5831]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

CCTV cameras can be disabled, therefor it would make sense to have a cctv-off icon

## Examples

The existing cctv icon but struckthrough

Thanks for considering it,
Julian

**Comment by Xenomorph99** [comment]
I noticed that our current [`cctv`](https://materialdesignicons.com/icon/cctv) icon could use a little clean up. It feels a little low in the frame and doesn't line up to the grid where it should. I propose we update it.

![cctv-current](https://user-images.githubusercontent.com/1837101/106633670-43827b80-653c-11eb-92fc-c86eb7c740e9.png)
![cctv-comparison](https://user-images.githubusercontent.com/1837101/106633682-467d6c00-653c-11eb-9551-a598051ba735.png)
![cctv](https://user-images.githubusercontent.com/1837101/106633697-4aa98980-653c-11eb-871e-7e74f5e5c7fc.png)

I thought it would be fun to add `cctv-variant` as well. It doesn't feel like the camera is "looking at" anything if it's pointing straight ahead. It feels kind of like it's off.

![cctv-variant](https://user-images.githubusercontent.com/1837101/106634150-bab80f80-653c-11eb-8632-1b8348568c5a.png)

I think this option for `cctv-off` with the reflected off modifier will work best.

![cctv-off](https://user-images.githubusercontent.com/1837101/106634532-197d8900-653d-11eb-80d2-65b2f720ecd0.png)

You can see in the two ideas below that I tried our standard off modifier, but it covers the camera's wall mount and makes it difficult to interpret.

![problem-1](https://user-images.githubusercontent.com/1837101/106633049-a45d8400-653b-11eb-8c33-d969d6f00f48.png)
![problem-2](https://user-images.githubusercontent.com/1837101/106634904-78db9900-653d-11eb-9f84-e60c7c32e2f3.png)

### Download
[cctv-icons.zip](https://github.com/Templarian/MaterialDesign/files/5912915/cctv-icons.zip)

**Comment by goyney** [comment]
[![cctv-off](https://materialdesignicons.com/icon/cctv-off)](https://materialdesignicons.com/icon/cctv-off)
