### ISSUE TITLE
Outlined version of floor-lamp

### ISSUE THREAD

**Issue by TarcisioMenezes** [Templarian/MaterialDesign#5835]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
I'd like to get an outlined version of **floor-lamp**.

![image](https://user-images.githubusercontent.com/12872368/106809250-0f3cb700-6631-11eb-8ead-37a75a85c147.png)

## Examples

Example of an outlined icon:

![lightbulb-outline](https://user-images.githubusercontent.com/12872368/106777667-cbcf5200-660a-11eb-9537-aa5e120929cc.png)

https://materialdesignicons.com/icon/lightbulb-outline

**Comment by steodor** [comment]
![image](https://user-images.githubusercontent.com/4397338/107156875-88b60b80-6989-11eb-9a5e-1de5feaf071c.png)
[floor-lamp-outline.zip](https://github.com/Templarian/MaterialDesign/files/5939792/floor-lamp-outline.zip)

**Comment by goyney** [comment]
[![floor-lamp-outline](https://materialdesignicons.com/icon/floor-lamp-outline)](https://materialdesignicons.com/icon/floor-lamp-outline)
