### ISSUE TITLE
npm and bower

### ISSUE THREAD

**Issue by dcdeiv** [Templarian/MaterialDesign#584]
Please, add a npm and bower icon!

![npm128](https://cloud.githubusercontent.com/assets/6809907/9143204/422c079e-3d45-11e5-9669-df4690e6a5ee.png)
![bower48 2x](https://cloud.githubusercontent.com/assets/6809907/9143205/422e5788-3d45-11e5-8722-7df7021e590c.png)

**Comment by CoDEmanX** [comment]
The N alone of NPM is not very recognizable. Bower has too fine details for MD style icon IMO.

**Comment by Templarian** [comment]
Going to agree. These have been suggested before and they don't really fit well for the pack.

For these I would suggest using the PNG or SVG alternatives inline rather than the webfont.
