### ISSUE TITLE
TV input source

### ISSUE THREAD

**Issue by HappyEinara** [Templarian/MaterialDesign#5840]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As a user of Home Assistant I can control the selection of the HDMI input on my TV. I'd appreciate an appropriate icon for such a control. On infrared TV remotes and other interfaces this is very often depicted by an arrow pointing into a rectangle or a CRT-shaped screen.

I've googled various terms around television, video, source, input etc. and also checked the existing MDI icons but I can't seem to find either a formal name for this symbol or any precedent in MDI or Unicode.

While the idea of the arrow pointing into the screen does seem to be fairly widespread, the precise design doesn't seem to be standardised and varies according to the design language of a TV remote's icon set as a whole. This being the case, it would be appropriate if the design were consistent with other television icons in MDI, although I personally consider the four-rounded-sides CRT style (my first example) to be most readily identified as a video screen.

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/13725146/106853715-403ee980-670e-11eb-8641-b86fa765c9af.png)
![image](https://user-images.githubusercontent.com/13725146/106853090-3ff21e80-670d-11eb-86f0-346b61b5b7a9.png)
![image](https://user-images.githubusercontent.com/13725146/106853124-4e403a80-670d-11eb-8e5f-72439a0ec6f0.png)
![image](https://user-images.githubusercontent.com/13725146/106853211-7039bd00-670d-11eb-92f9-ad692ac6cef1.png)

**Comment by goyney** [comment]
This already exists as `import`.

[![import](https://materialdesignicons.com/icon/import)](https://materialdesignicons.com/icon/import)
