### ISSUE TITLE
note-edit

### ISSUE THREAD

**Issue by FireBird4** [Templarian/MaterialDesign#5841]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
symbol to edit a note
Provide some context of how your icon could be used.
there is a mdi-note-plus and mdi-notebook-edit but no  mdi-note-edit
## Examples

Include any example images so we know what the icon should look like.
like the mdi-note-plus (https://materialdesignicons.com/icon/note-plus) but intead of the plus-sign an pencil like in mdi-note-edit (https://materialdesignicons.com/icon/notebook-edit)

**Comment by Xenomorph99** [comment]
![note-edit](https://user-images.githubusercontent.com/1837101/106925507-62644780-66cd-11eb-9a2c-3f58f8669b13.png)
![note-edit-outline](https://user-images.githubusercontent.com/1837101/106925502-61cbb100-66cd-11eb-950b-0c76718dd0fb.png)

[note-edit-icons.zip](https://github.com/Templarian/MaterialDesign/files/5927202/note-edit-icons.zip)

**Comment by Xenomorph99** [comment]
I went ahead and added these to the library

**Comment by FireBird4** [comment]
Thank you😄

Colton <notifications@github.com> schrieb am Sa., 6. Feb. 2021, 19:44:
