### ISSUE TITLE
Advanced export invalid scaling

### ISSUE THREAD

**Issue by TheChilliPL** [Templarian/MaterialDesign#5842]
I tried to export an icon with these settings:  
![image](https://user-images.githubusercontent.com/18823939/106146601-26822d00-6177-11eb-8382-2f312757e7e5.png)
Yet the actual icon is way smaller than that:
![newspaper](https://user-images.githubusercontent.com/18823939/106146648-369a0c80-6177-11eb-882b-5264f047dad0.png)

(Originally I confused it with the Google official Material Design Icons repository and opened [an issue there](/google/material-design-icons/issues/1135))

**Comment by goyney** [comment]
This is very unlikely to be fixed. We are currently in the process of building a completely new website. See more information here: https://github.com/Templarian/MaterialDesign/issues/5161

**Comment by Templarian** [comment]
I haven't touched that code in probably 6 years and I'm not going to as it might introduce other bugs.

I coded that old advanced export on a mixture of caffeine and beer and I'm going to assume the code is terrible.

I'm slowly building out all the components, so we can rewrite the advanced exporter as I know a lot rely on it. Already have the color picker done which was a large part.
