### ISSUE TITLE
Update Note Icons to Use Standard Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#5844]
Should we update our existing note icons to use the standard modifiers?

![note-plus](https://user-images.githubusercontent.com/1837101/106935069-24205580-66d8-11eb-93ee-6aad5cde0025.png)
![note-plus-outline](https://user-images.githubusercontent.com/1837101/106935068-2387bf00-66d8-11eb-8e7d-aa08e15bd911.png)

![note-minus](https://user-images.githubusercontent.com/1837101/106935066-2387bf00-66d8-11eb-96e9-2168626291f9.png)
![note-minus-outline](https://user-images.githubusercontent.com/1837101/106935063-22ef2880-66d8-11eb-857f-56cb7b62a0dd.png)

![note-remove](https://user-images.githubusercontent.com/1837101/106935074-24b8ec00-66d8-11eb-8c5b-530249128228.png)
![note-remove-outline](https://user-images.githubusercontent.com/1837101/106935072-24205580-66d8-11eb-9f1d-d578868c4cc6.png)

## Download

[updated-note-icons.zip](https://github.com/Templarian/MaterialDesign/files/5927619/updated-note-icons.zip)

**Comment by goyney** [comment]
Yes.

**Comment by Xenomorph99** [comment]
Updated
