### ISSUE TITLE
emoji aliases for emoticon-*?

### ISSUE THREAD

**Issue by locness3** [Templarian/MaterialDesign#5846]
The emoticon-* icons, despite having an Emoji tag don't show up when searching "emoji".

**Comment by Templarian** [comment]
Surprised we didn't have these aliased. Short list of ones that need the alias prefix.

- All 36 emoji's need this
- The robot emojis
- cat / dog also

That should cover the basic ones.

**Comment by Xenomorph99** [comment]
Done. I added `emoji` and `emoticon` to a bunch of icons. Should be easier to search and find them now.
