### ISSUE TITLE
Copy icon as text

### ISSUE THREAD

**Issue by Joebayld** [Templarian/MaterialDesign#5848]
I'm wondering if it is possible to add the ability to copy an icon as text in the website. 

You can currently do this in the cheatsheet by clicking on the icon: 
<img width="492" alt="Screen Shot 2021-02-08 at 18 50 14 PM" src="https://user-images.githubusercontent.com/9399317/107309034-8f528a80-6a3e-11eb-97d1-027a92428692.png">

But is this not possible outside the cheatsheet? 

I ask because I installed the font to my machine and use the icons in text fields while working in Sketch (much easier than managing a ton of SVGs!). There is a dropdown with a handful of options in the main website icon picker, but this functionality only seems to exist in the cheatsheet. It's not a fun workflow to search via the main site, then search for that icon in the cheatsheet just to copy it! 

Thanks,
Joe

**Comment by Templarian** [comment]
This is a feature in the new site under development (actually took the code from the new site when making that preview):

![image](https://user-images.githubusercontent.com/338885/107456779-74ebe000-6b16-11eb-8024-6175caf20b9c.png)

Going to close this out as it's a known feature request. Please follow the pinned issue for details as we work on the new site.
