### ISSUE TITLE
chart-box-outline is a pixel too wide

### ISSUE THREAD

**Issue by daavko** [Templarian/MaterialDesign#5849]
The `chart-box-outline` icon is 19px wide and 18px high. This combined with the fact that it's centered causes it to not align to the grid and appear blurry. I'm not sure whether this was intended or not, but guessing by the fact that `chart-box` and `chart-box-plus-outline` are both squares, it probably wasn't.

![image](https://user-images.githubusercontent.com/7669061/107390764-4e1eb100-6af8-11eb-97fe-7fc7b2227ca6.png)

Comparison against `chart-box-plus-outline`:

![image](https://user-images.githubusercontent.com/7669061/107391035-99d15a80-6af8-11eb-979b-94cfa57b1d44.png)

**Comment by goyney** [comment]
Silly Google. Good catch, we can easily fix this one.

**Comment by goyney** [comment]
Updated.
