### ISSUE TITLE
Outdoor Lamp With Sensor (motion)

### ISSUE THREAD

**Issue by frasquez** [Templarian/MaterialDesign#5850]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

Besides outdoor lamp, I think is needed one with motion detection, so I took an existing icon and add a "motion detection" lines.

## Preview

<img width="393" alt="prev" src="https://user-images.githubusercontent.com/8196448/107442456-e5463180-6b15-11eb-99d0-9b14982e5ae8.png">

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[outdoor-lamp-sensor.zip](https://github.com/Templarian/MaterialDesign/files/5954903/outdoor-lamp-sensor.zip)

**Comment by goyney** [comment]
I think this icon is overly specific and opens us up to having to include "motion" versions of all variants of lightbulb/lamp icons.

I think we should fulfill the automatic light idea in https://github.com/Templarian/MaterialDesign/issues/5133 and close this as too niche.

**Comment by goyney** [comment]
For now, we're going to close this an suggest using the newly added `lightbulb-auto(-outline)`. Thanks for the suggestion.

**Comment by lightingman117** [comment]
Any chance on reopening this (dialogue)?

I concur that the outdoor motion light is overly specific.

That said, I think the generic lightbulb (F0335) with the motion glyph would be a good addition.

Auto /= motion (IMO)

Thanks for everything, team!
