### ISSUE TITLE
Home Switch (mdi-home-switch)

### ISSUE THREAD

**Issue by phillipa-llama** [Templarian/MaterialDesign#5851]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

We are switching between sites which are each for a different location / property

## Examples

Based on these existing Material Design Icons:
![image](https://user-images.githubusercontent.com/57439980/107476044-c5e2ef00-6b7d-11eb-9576-5fc45a6ece13.png)

But using the mdi-home instead of mdi-account:
![image](https://user-images.githubusercontent.com/57439980/107477476-76ea8900-6b80-11eb-8a32-e4c2f3fd3327.png)

**Comment by goyney** [comment]
[![home-switch](https://materialdesignicons.com/icon/home-switch)](https://materialdesignicons.com/icon/home-switch)[![home-switch-outline](https://materialdesignicons.com/icon/home-switch-outline)](https://materialdesignicons.com/icon/home-switch-outline)
