### ISSUE TITLE
Human-Male-Board Icon not loading anymore

### ISSUE THREAD

**Issue by BullfroG21** [Templarian/MaterialDesign#5852]
Hello,

it seems that it is not possible to load the icon "human-male-board" aka. teacher anymore. I tried different icons instead and they all worked properly.

Best Regards

**Comment by Templarian** [comment]
@BullfroG21 This is part of the renaming to #5409. Unfortunately while our database understand renames the site does not currently snapshot to a stable version.

5.9.55: http://pictogrammers.github.io/@mdi/font/5.9.55/

**Comment by Templarian** [comment]
It's called `teacher` before 6.0

**Comment by alfreema** [comment]
> It's called `teacher` before 6.0

I just got bit by this issue too.   After diving into the mdi/js file, I found it's "teach" not "teacher".   Just posting that for anybody else that might have this issue.
