### ISSUE TITLE
"Check All" and "Check None" as 4 checkboxes in a grid

### ISSUE THREAD

**Issue by alexeyinkin** [Templarian/MaterialDesign#5853]
## Usage

There are checkbox-multiple-marked and checkbox-multiple-blank. But for selection in a grid it is more intuitive to have icons with 4 checkboxes in 2x2 grid.

## Examples
![image](https://user-images.githubusercontent.com/44893228/107739085-23f80980-6d19-11eb-8265-445a04a09488.png)

**Comment by goyney** [comment]
There is not enough space for us to do this. However, we do have icons for this use case already.

[![checkbox-multiple-marked-outline(https://materialdesignicons.com/icon/checkbox-multiple-marked-outline)](https://materialdesignicons.com/icon/checkbox-multiple-marked-outline)[![checkbox-multiple-blank-outline](https://materialdesignicons.com/icon/checkbox-multiple-blank-outline)](https://materialdesignicons.com/icon/checkbox-multiple-blank-outline)
