### ISSUE TITLE
switch-city

### ISSUE THREAD

**Issue by valentingavran** [Templarian/MaterialDesign#5855]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

On my website I can switch between different cities/regions with a selectbox. For this purpose an icon would be very handy, which does not exist yet.

## Examples

You could extend `city` and `city-variant` and add a transfer icon in the lower right corner like in `bank-transfer`.
Another possibility would be to add a switch icon below like in `account-switch`.

**Comment by jhil** [comment]
Any preference @valentingavran ? 
<img width="1382" alt="Screenshot 2022-11-14 at 22 37 06 from Figma" src="https://user-images.githubusercontent.com/2228347/201835111-f39e58df-0cbe-4721-ac50-1d50af0b2fb1.png">

**Comment by valentingavran** [comment]
In my opinion, both icons are a bit unbalanced. But if I had to choose between the two, I would choose the right one. But I am not an expert in this matter :)

**Comment by jhil** [comment]
I agree optically but this is how the system has been applied to other similar variants. Will think about it!

**Comment by jhil** [comment]
[![city-switch](https://materialdesignicons.com/icon/city-switch)](https://materialdesignicons.com/icon/city-switch)

**Comment by jhil** [comment]
Threw in domain-switch while I was at it. [![domain-switch](https://materialdesignicons.com/icon/domain-switch)](https://materialdesignicons.com/icon/domain-switch)
