### ISSUE TITLE
aparat logo

### ISSUE THREAD

**Issue by phoenixservice** [Templarian/MaterialDesign#5856]
icon of aparat.com is not exist
https://img.icons8.com/color/452/aparat.png

**Comment by Templarian** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by phoenixservice** [comment]
and what about kinopoisk ?
https://www.kinopoisk.ru/

**Comment by phoenixservice** [comment]
and what about kinopoisk ?
https://www.kinopoisk.ru/

**Comment by PeterShaggyNoble** [comment]
@phoenixservice, @Templarian's statement above applies to all brand icons. I've already opened [a PR](https://github.com/simple-icons/simple-icons/pull/5046) for Aparat for you in [Simple Icons' repo](https://github.com/simple-icons/simple-icons/) but, if you have any further requests for brand icons then please [open a new issue](https://github.com/simple-icons/simple-icons/issues/new/choose) over there for each one you require.
