### ISSUE TITLE
moustache

### ISSUE THREAD

**Issue by jeroenqui** [Templarian/MaterialDesign#5857]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In a menu

## Examples

[moustache.svg.zip](https://github.com/Templarian/MaterialDesign/files/5991395/moustache.svg.zip)

**Comment by goyney** [comment]
Already exists.

[![mustache](https://materialdesignicons.com/icon/mustache)](https://materialdesignicons.com/icon/mustache)

**Comment by Templarian** [comment]
Yeah, we always default to US English. Will make sure an alias is added.
