### ISSUE TITLE
Lightautomation on/off

### ISSUE THREAD

**Issue by Pirol62** [Templarian/MaterialDesign#5858]
I have:

- [x ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I have booleans, that avoid, when switched, that light is toggled through motion detected or any other automation.
In order to show, if the automation is on or off I need a symbol light like this:

## Examples
![image](https://user-images.githubusercontent.com/48820003/108175477-1c61a780-7101-11eb-9f72-aa97313c2edc.png)

![image](https://user-images.githubusercontent.com/48820003/108175601-431fde00-7101-11eb-9045-b1af5f773320.png)

**Comment by jonathand131** [comment]
Hi there, I have exactly the same need.
About the icon design, I had in mind a light bulb with the "A" character in the middle or a little on the side like you did with the cogwheel.
The cogwheel is generally used for settings/configuration (see cog, account-cog, cellphone-cog, ...) whereas the "A" is more often used for automatism/automatic mode (see brightness-auto, fan-auto, flash-auto, ...).
I think that both designs could have their usage so it would be nice the have the "A" variant also.

**Comment by goyney** [comment]
These were added in v6.

[![lightbulb-auto](https://materialdesignicons.com/icon/lightbulb-auto)](https://materialdesignicons.com/icon/lightbulb-auto)[![lightbulb-auto-outline](https://materialdesignicons.com/icon/lightbulb-auto-outline)](https://materialdesignicons.com/icon/lightbulb-auto-outline)
