### ISSUE TITLE
WiFi signal quality

### ISSUE THREAD

**Issue by JamesCoyle** [Templarian/MaterialDesign#586]
I could have sworn there were network items already but I can't see them anywhere. Am I just blind? I specifically mean the different levels of wifi and cellular connection in the status bar on android that look like a triangle and quarter circle. I can see the battery icons listed but not those.

![Imgur](http://i.imgur.com/Rr35e6K.png?1)

**Comment by CoDEmanX** [comment]
See #420 and https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-122950329

The transparency is a problem... @Templarian?

**Comment by SolusSoftworks** [comment]
Ah. How about a non-stock set in the style of the [battery icons](https://materialdesignicons.com/icon/battery-60) with outlines around the transparent areas? I'd have a go at making them myself but I'm not 100% sure how to.

**Comment by CoDEmanX** [comment]
Like this? ![wifi-1bar](https://cloud.githubusercontent.com/assets/1309249/9199535/3cb86018-4043-11e5-9a24-9feb746c2cbb.png)

It's possible I guess. But one could also remove the transparent shape and layer the opaque shape with the full signal shape with CSS (the latter with opacity 0.5 to recreate the original icon)...

**Comment by SolusSoftworks** [comment]
Yes! Both options would be a great addition for the network, battery, and wifi icons.

**Comment by CoDEmanX** [comment]
I created outline version like shown above and linked them over here:

https://github.com/Templarian/MaterialDesign/issues/420#issuecomment-154769174

**Comment by CoDEmanX** [comment]
[wifi-outline.zip](https://github.com/Templarian/MaterialDesign/files/1804696/wifi-outline.zip)

![wifi-outline](https://user-images.githubusercontent.com/1309249/37312972-7369dd1a-264d-11e8-8c6b-206405ab0fdd.png)
![image](https://user-images.githubusercontent.com/1309249/37311888-532e87a2-2649-11e8-82f6-b3cf49de2a34.png)

[wifi-alert.zip](https://github.com/Templarian/MaterialDesign/files/1804726/wifi-alert.zip)

![wifi-outline-alert](https://user-images.githubusercontent.com/1309249/37313055-dcda545a-264d-11e8-9fb8-fe95eb0eabf7.png)
![image](https://user-images.githubusercontent.com/1309249/37311987-a4502352-2649-11e8-9cd6-d5757f0b7057.png)

[wifi-lock.zip](https://github.com/Templarian/MaterialDesign/files/1804727/wifi-lock.zip)

![wifi-outline-lock](https://user-images.githubusercontent.com/1309249/37313159-43a8746e-264e-11e8-8e52-af20fd8cb3ad.png)
![image](https://user-images.githubusercontent.com/1309249/37312067-dbc3e468-2649-11e8-8d2b-d617e569406f.png)

[wifi-off.zip](https://github.com/Templarian/MaterialDesign/files/1804791/wifi-off.zip)
![wifi-off](https://user-images.githubusercontent.com/1309249/37313217-85b962b4-264e-11e8-9674-33e26e51bd97.png)
![image](https://user-images.githubusercontent.com/1309249/37313287-d8de09d6-264e-11e8-8f3b-72e31c5053e6.png)

**Comment by CoDEmanX** [comment]
@Templarian Dunno if you also want the related mobile signal icons included: https://github.com/Templarian/MaterialDesign/issues/2901#issuecomment-372493257

**Comment by Templarian** [comment]
These have all been added.
