### ISSUE TITLE
Paint brush variant

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#5860]
Google icon, found in Google Slides (formatting options).

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/7819991/108349068-d7ae3d00-71e2-11eb-9747-6718aa162e3a.png)

## Vector Path

`M8 3C5.79 3 4 4.79 4 7v7c0 1.1.9 2 2 2h3v4c0 1.1.9 2 2 2h2c1.1 0 2-.9 2-2v-4h3c1.1 0 1.99-.9 1.99-2L20 3H8zm0 2h4v2h2V5h1v4h2V5h1v5H6V7c0-1.1.9-2 2-2zm-2 9v-2h12v2H6z`

**Comment by goyney** [comment]
Added.
