### ISSUE TITLE
printer-outline

### ISSUE THREAD

**Issue by FlVis** [Templarian/MaterialDesign#5862]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This is a Google Material icon that for some reason is not available in this library. The icon is https://material.io/resources/icons/?search=print&icon=local_printshop&style=outline (icon name: local_printshop; it is pretty much the Google print icon in outline format)

The icon is used for print buttons, when the current filled icon looks too heavy on screen.

## Examples

Include any example images so we know what the icon should look like.
Again, this is the link to Google Material where the icon already exists: https://material.io/resources/icons/?search=print&icon=local_printshop&style=outline
Attached is a PNG version of the icon
![IcPrint](https://user-images.githubusercontent.com/69047391/108429253-ba429880-720d-11eb-866d-84fe1d8db49c.png)

**Comment by Templarian** [comment]
[![printer-outline](https://materialdesignicons.com/icon/printer-outline)](https://materialdesignicons.com/icon/printer-outline) [![printer-off-outline](https://materialdesignicons.com/icon/printer-off-outline)](https://materialdesignicons.com/icon/printer-off-outline)

**Comment by FlVis** [comment]
Thank you so much for adding this. And good call on the printer off option
:)

Florina
