### ISSUE TITLE
Curtains icon

### ISSUE THREAD

**Issue by Murder3D** [Templarian/MaterialDesign#5865]
## Usage

Hello,

I have a set of automated curtains which open from the middle, half goes left and half goes right. I was looking for a curtain icon to use but there is none with that design. It would be really nice if it could be implemented a curtain icon like the example below.

Both open and closed versions and both solid color and outlined versions if possible.

Thank you!

## Examples

![94045111-vector-curtain-icon-illustration](https://user-images.githubusercontent.com/68924586/108620401-4500de80-742c-11eb-93eb-60b15d6d5a5c.jpg)

**Comment by 625alex** [comment]
I have the same use case as @Murder3D. Curtain icons would be a fantastic addition.

**Comment by Mariusthvdb** [comment]
there's this too: https://github.com/Templarian/MaterialDesign/issues/2523

**Comment by goyney** [comment]
Yes, this is a duplicate request, please search. #2523.
