### ISSUE TITLE
Dimmer actions (for home automation)

### ISSUE THREAD

**Issue by bennop** [Templarian/MaterialDesign#5868]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html) - at least I tried.

Icons for dimmer actions (home assistant)

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).
![lightbulb-brighter1](https://user-images.githubusercontent.com/5919157/108875321-5b11c900-75fd-11eb-9d89-6246904225f2.png)
![lightbulb-brighter2](https://user-images.githubusercontent.com/5919157/108875325-5b11c900-75fd-11eb-92b1-c3231f14dfe5.png)
![lightbulb-brighter3](https://user-images.githubusercontent.com/5919157/108875328-5baa5f80-75fd-11eb-9ebb-fb4ea39f3791.png)
![lightbulb-brighter4](https://user-images.githubusercontent.com/5919157/108875330-5baa5f80-75fd-11eb-823b-7d651f778e6f.png)
![lightbulb-dim1](https://user-images.githubusercontent.com/5919157/108875332-5c42f600-75fd-11eb-9e9c-0faee004d25b.png)
![lightbulb-dim2](https://user-images.githubusercontent.com/5919157/108875335-5cdb8c80-75fd-11eb-8856-f56768ced34d.png)
![lightbulb-dim3](https://user-images.githubusercontent.com/5919157/108875336-5cdb8c80-75fd-11eb-99fc-8f78893c006b.png)
![lightbulb-dim4](https://user-images.githubusercontent.com/5919157/108875339-5cdb8c80-75fd-11eb-9458-ba289aba7f44.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
[Dimmer.zip](https://github.com/Templarian/MaterialDesign/files/6030377/Dimmer.zip)

**Comment by Templarian** [comment]
I think a dimmer might be better represented in a vertical like maybe a line in `tune-vertical` to the right of a bulb.

**Comment by bennop** [comment]
While I agree that the _entity_ dimmer might be better visualized through the reuse of established symbols in the way you suggest, my intention was to indicate the associated _actions_ (i.e., go dimmer/brighter) which - for me - needs some sort of timeline.
That is often commonly done on a horizontal from left to right, thus the first three designs.
The respective fourth variants try to avoid that bias by adding the vertical arrows.

**Comment by skmagiik** [comment]
While I agree with the need, the suggested icons are troublesome if not in large sizes. Perhaps something more inspired by the phillips hue icons found on their switches could work better? Showing the appropriate size of the icon based on action? Technically this could be done via sizing exiting lightbulb-on or lightbulb-on-outline mdi icons.

**Comment by goyney** [comment]
We're going to go with the proposal in #6067, filling the lightbulb similar to our battery icons. Please follow that issue for status updates.
