### ISSUE TITLE
Bug downloading content-duplicate icon

### ISSUE THREAD

**Issue by zsheffer** [Templarian/MaterialDesign#587]
The 'content-duplicate' icon doesn't seem to be downloading properly. The file is in the icons > design and icons > svg folder, shows properly on the site, and the icons directly around it get downloaded but that one seems to have an issue.

Is there some sort of license issue around that icon that I am missing?

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/content-duplicate

I just downloaded it from the site in a few different formats and it worked. Not sure what could be going on. Can you write down your exact steps and which download option you are selecting (browser also).

The whole system simply takes the SVG path data from the database for any icon and generates the required files, so it it works for 1 icon it should work for all.

**Comment by zsheffer** [comment]
Tried in both:
Chrome - Version 44.0.2403.130 (64-bit)
Firefox - 38.0.5

1. Click download btn in top right corner
2. Click download in modal
3. Unzip file and view html preview
4. Sad face

![screen shot 2015-08-08 at 8 40 20 pm](https://cloud.githubusercontent.com/assets/1786166/9152984/f76d4636-3e0d-11e5-8214-ae6f5a610da9.png)

![screen shot 2015-08-08 at 8 40 23 pm](https://cloud.githubusercontent.com/assets/1786166/9152985/fa903d3c-3e0d-11e5-8085-e0f6bcf554ad.png)

![screen shot 2015-08-08 at 8 40 42 pm](https://cloud.githubusercontent.com/assets/1786166/9152986/fd7b3722-3e0d-11e5-8459-da8d368bb8d5.png)

**Comment by Templarian** [comment]
Oh, yea, you're talking about the webfont. That is versioned and updated in every 50 or so icons. That icon was added after `v1.1.70` released. The next version will be another large release shortly and will contain this new icon.

The reason for the versioned webfont is for compatibility (it is in use by thousands of applications and I need to ensure a level of stability between releases).

Follow the twitter account @ModernIcons for the next release.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history (will let you know the version an icon was added).

**Comment by zsheffer** [comment]
Ah - that explains it. Thanks for the quick response.
