### ISSUE TITLE
Code-Editor / IDE

### ISSUE THREAD

**Issue by kay999** [Templarian/MaterialDesign#5870]
## Usage

An icon used for showing the ability to edit application code or an IDE.

## Examples

![image](https://user-images.githubusercontent.com/14128442/108985488-657da280-7691-11eb-93b5-f138aed3fdeb.png)

**Comment by goyney** [comment]
Probably an `edit` variant of any/all of our `iframe` icons.

**Comment by kay999** [comment]
Yes, looks reasonable. 

Btw: Never found the iframe icons. Why are they named "iframe" instead of "window" or "app" or "dialog"?

**Comment by Templarian** [comment]
That is very weird those are named like that. 😕 This is something we might look into for 6.0.

**Comment by goyney** [comment]
Created  #6087 to address the naming issues of iframe.

**Comment by goyney** [comment]
[![application-edit](https://materialdesignicons.com/icon/application-edit)](https://materialdesignicons.com/icon/application-edit)[![application-edit-outline](https://materialdesignicons.com/icon/application-edit-outline)](https://materialdesignicons.com/icon/application-edit-outline)
