### ISSUE TITLE
arrow-collapse-vertical with a single line

### ISSUE THREAD

**Issue by sirisian** [Templarian/MaterialDesign#5871]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Similar to arrow-collapse-vertical, but to indicate it's compressing to 1 item.

## Examples

Like arrow-collapse-vertical, but with 1 line rather than 2. An image a coworker gave me:

![singleline](https://user-images.githubusercontent.com/1320998/109073002-6c210f80-76bb-11eb-9eae-d8a4e4b132fc.png)

**Comment by Templarian** [comment]
Added aliases.
