### ISSUE TITLE
information-off

### ISSUE THREAD

**Issue by PurpleProgrammer** [Templarian/MaterialDesign#5876]
I have:

- [] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

This could be used in an icon button to hide some info.

## Examples

<img width="256" alt="info-off" src="https://user-images.githubusercontent.com/24755259/109731328-b75b8680-7bc3-11eb-8301-336c54ec1486.png">

<img width="256" alt="info-off-2" src="https://user-images.githubusercontent.com/24755259/109731464-fa1d5e80-7bc3-11eb-9e1f-e3962e901d4b.png">

**Comment by goyney** [comment]
[![information-off](https://materialdesignicons.com/icon/information-off)](https://materialdesignicons.com/icon/information-off)[![information-off-outline](https://materialdesignicons.com/icon/information-off-outline)](https://materialdesignicons.com/icon/information-off-outline)

**Comment by PurpleProgrammer** [comment]
Thank you so much! Have a great one!
