### ISSUE TITLE
Icon for work site

### ISSUE THREAD

**Issue by knshafeeqkn** [Templarian/MaterialDesign#5877]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In a mobile application for a construction company, they need an icon to show in their worksite-related things.

## Examples

The icons in my mind is like [this](https://icon-library.com/images/construction-icon/construction-icon-23.jpg)

**Comment by goyney** [comment]
We have several of these.

[![account-hard-hat](https://materialdesignicons.com/icon/account-hard-hat)](https://materialdesignicons.com/icon/account-hard-hat)
[![excavator](https://materialdesignicons.com/icon/excavator)](https://materialdesignicons.com/icon/excavator)
[![wall](https://materialdesignicons.com/icon/wall)](https://materialdesignicons.com/icon/wall)
[![shovel](https://materialdesignicons.com/icon/shovel)](https://materialdesignicons.com/icon/shovel)
