### ISSUE TITLE
one dot

### ISSUE THREAD

**Issue by j4f2610** [Templarian/MaterialDesign#5879]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
The template is not optional, please fill it out.

That being said, we also already have `circle-small`.

[![circle-small](https://materialdesignicons.com/icon/circle-small)](https://materialdesignicons.com/icon/circle-small)

**Comment by Templarian** [comment]
Added the Alias dot.

**Comment by Templarian** [comment]
Haven't see an reply, going to assume the above icon solved this request.
