### ISSUE TITLE
run-and-debug / debug

### ISSUE THREAD

**Issue by 1nVitr0** [Templarian/MaterialDesign#5880]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Since Visual Studio Code now supports product icon themes, it would be great if all required icons would be supported by material design icons. I'm sure there are a few missing, but the most jarring is the debug icon. More specifically the "Run and Debug" Icon.

## Examples

The original VS Code icon is [debug-alt](https://raw.githubusercontent.com/microsoft/vscode-codicons/main/src/icons/debug-alt.svg):

![debug-alt](https://raw.githubusercontent.com/microsoft/vscode-codicons/main/src/icons/debug-alt.svg)

The closest icons at the moment seem to be

  - [play](https://materialdesignicons.com/icon/play) ![play](https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/play.svg)
  - and [bug](https://materialdesignicons.com/icon/bug) ![bug](https://raw.githubusercontent.com/Templarian/MaterialDesign/master/svg/bug.svg)

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/111058409-2488da80-8454-11eb-9eb7-c04bc64a5f6a.png)

We don't really have a small bug icon.

**Comment by goyney** [comment]
[![bug-play](https://materialdesignicons.com/icon/bug-play)](https://materialdesignicons.com/icon/bug-play)[![bug-play-outline](https://materialdesignicons.com/icon/bug-play-outline)](https://materialdesignicons.com/icon/bug-play-outline)
[![bug-pause](https://materialdesignicons.com/icon/bug-pause)](https://materialdesignicons.com/icon/bug-pause)[![bug-pause-outline](https://materialdesignicons.com/icon/bug-pause-outline)](https://materialdesignicons.com/icon/bug-pause-outline)
[![bug-stop](https://materialdesignicons.com/icon/bug-stop)](https://materialdesignicons.com/icon/bug-stop)[![bug-stop-outline](https://materialdesignicons.com/icon/bug-stop-outline)](https://materialdesignicons.com/icon/bug-stop-outline)

**Comment by 1nVitr0** [comment]
@PKief this might be interesting for [PKief/vscode-material-product-icons](https://github.com/PKief/vscode-material-product-icons)
