### ISSUE TITLE
Light Bulb with floor levels 

### ISSUE THREAD

**Issue by Kiezelke** [Templarian/MaterialDesign#5882]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I want to use light bulbs with floor levels so I can group the lights for the different floors in tabs for the corresponding floor
## Examples

Include any example images so we know what the icon should look like.

![lightbulb1](https://user-images.githubusercontent.com/76170233/110324270-06ffdf00-8016-11eb-84d8-8664c0960925.png)
![lightbulb2](https://user-images.githubusercontent.com/76170233/110324271-07987580-8016-11eb-9422-3a78c802df19.png)
![lightbulb3](https://user-images.githubusercontent.com/76170233/110324272-07987580-8016-11eb-9896-fffe01f20d3e.png)

**Comment by goyney** [comment]
This is way too niche.

**Comment by Kiezelke** [comment]
Hi, dies this mean that they icons are going tot be added?
Maybe also a bulb with "G" inside doe ground floor?
😃

**Comment by Templarian** [comment]
Closing this one out. Even as an overlay numbers are too niche. Text might be a better user experience in this case.
