### ISSUE TITLE
export 'mdiTrayArrowDown' was not found in '@mdi/js' 

### ISSUE THREAD

**Issue by Frank-0511** [Templarian/MaterialDesign#5883]
And there is no such export. Maybe add these icons to mdi/js?

import { mdiTrayArrowDown } from '@mdi/js';

**Comment by Frank-0511** [comment]
![Captura de pantalla 2021-03-08 101826](https://user-images.githubusercontent.com/29511920/110340841-b11c3e80-7ff7-11eb-91ef-c32c358817f5.png)

**Comment by goyney** [comment]
This icon was recently added and will be released in the 6.0 release.

https://github.com/Templarian/MaterialDesign/issues/5770

**Comment by Templarian** [comment]
@Frank-0511 For now you can include the path directly until it is added. 😃 

`const mdiTrayArrowDown = 'M...';`
