### ISSUE TITLE
water-saver

### ISSUE THREAD

**Issue by Drise13** [Templarian/MaterialDesign#5884]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

We were looking for some sort of water saver / ink saver icon and didn't find one. This is intended for use as a toggle icon. This is a google icon variant.

## Preview

![image](https://user-images.githubusercontent.com/10517125/110518680-0036a200-80d2-11eb-9c1e-15182513a923.png)

## Zip Download

[water-saver.zip](https://github.com/Templarian/MaterialDesign/files/6110650/water-saver.zip)

**Comment by Drise13** [comment]
I'm poking this since I don't know if I should have expected feedback by now.

**Comment by goyney** [comment]
"Water saver" isn't generic enough for this, but I'm not sure what else to name it.

**Comment by Drise13** [comment]
For our purpose, it's intended as some sort of draft mode, where instead of printing every column, we print every other column, hence the "saver" idea, since it literally reduces ink consumption in half.

**Comment by goyney** [comment]
[![water-opacity](https://materialdesignicons.com/icon/water-opacity)](https://materialdesignicons.com/icon/water-opacity)
