### ISSUE TITLE
identical icons chart-box and poll-box

### ISSUE THREAD

**Issue by The28AWG** [Templarian/MaterialDesign#5885]
identical icons:
chart-box = poll-box
chart-box-outline = poll-box-outline

**Comment by Templarian** [comment]
I think we discussed this once a while back. Not really sure what was decided or if we had just forgotten to do anything about the duplication.

We could also always redesign one of the icons.

**Comment by The28AWG** [comment]
It's funny.
https://github.com/Templarian/MaterialDesign/issues/5230#issuecomment-663323577
https://github.com/Templarian/MaterialDesign/issues/4605#issuecomment-554608362

**Comment by JamesCoyle** [comment]
I'd say we just remove the poll versions in v6. Sounds like Google being Google and naming things badly.

**Comment by goyney** [comment]
We are going to remove `poll-box` and `poll-box-outline` in v6. We'll also add the appropriate aliases.

**Comment by goyney** [comment]
These have been removed.
