### ISSUE TITLE
account-eye

### ISSUE THREAD

**Issue by sdtacoma** [Templarian/MaterialDesign#5886]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon could be used to view a person's record, or a list of people.

## Examples
With one person and/or multiple people and an eyeball. The the image below, but better.
![viewPerson](https://user-images.githubusercontent.com/18173141/110541391-8821a980-80dc-11eb-8dbd-9f20aaab833f.jpg)

**Comment by MrHad** [comment]
I just wanted to submit the same request.
But in my case I'd like to use it for account visibility, so it would be awesome if account-eye-off with crossed out eye would also be made.

**Comment by goyney** [comment]
[![account-eye](https://materialdesignicons.com/icon/account-eye)](https://materialdesignicons.com/icon/account-eye)[![account-eye-outline](https://materialdesignicons.com/icon/account-eye-outline)](https://materialdesignicons.com/icon/account-eye-outline)
