### ISSUE TITLE
HDMI Head on view

### ISSUE THREAD

**Issue by skmagiik** [Templarian/MaterialDesign#5887]
I have:

- [ X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Useful for video routing icons.
Preferred two icons one just the image and another with HDMI text added above

## Examples

Just image example:
![image](https://user-images.githubusercontent.com/1530487/110582696-30159200-8132-11eb-8201-e80350f0c943.png)

**Comment by goyney** [comment]
We already have `video-input-hdmi`. Would that not work?

**Comment by skmagiik** [comment]
Not for the use case of a showing a clear input port diagram.

It's common in the industry to show the front view like this for
configuration icons next to the port. The same can be applied on a web page
if you are doing an interactive configuration next to the ports.

**Comment by jeffderek** [comment]
Agree that this would be a very useful icon.  The existing HDMI icon is of the cable, and it would be nice to have an icon for the jack.

**Comment by goyney** [comment]
[![hdmi-port](https://materialdesignicons.com/icon/hdmi-port)](https://materialdesignicons.com/icon/hdmi-port)
