### ISSUE TITLE
Airplane with plus

### ISSUE THREAD

**Issue by mhamzamughal86** [Templarian/MaterialDesign#5888]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I will use it on my website design

## Examples

The icon should be an airplane with the plus symbol it should give the vibe of add airplane or add a trip alert

**Comment by Templarian** [comment]
Search... #5270
