### ISSUE TITLE
cart with heart

### ISSUE THREAD

**Issue by vasilis1992** [Templarian/MaterialDesign#5889]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
[![cart-heart](https://materialdesignicons.com/icon/cart-heart)](https://materialdesignicons.com/icon/cart-heart)
