### ISSUE TITLE
Phone call incoming and call outgoing

### ISSUE THREAD

**Issue by Bramengton** [Templarian/MaterialDesign#589]
Hi, how about adding a few icons calls - incoming call and outgoing call.
The style looks like:
https://materialdesignicons.com/icon/phone-missed
or
https://materialdesignicons.com/icon/phone-forward
Thanks.

**Comment by CoDEmanX** [comment]
There are stock Google icons for this:
http://www.google.com/design/icons/#ic_call_made
http://www.google.com/design/icons/#ic_call_made
etc.

But they do not include a phone symbol.
@Templarian: would you want custom icons with handset + arrow?

**Comment by Bramengton** [comment]
With handset and arrow would be perfect .. Exactly fits into a style icon with the handset like phone, phone-in-talk, phone-missed.

**Comment by Bramengton** [comment]
With handset and arrow would be perfect .. Exactly fits into a style icon with the handset like phone, phone-in-talk, phone-missed.

**Comment by CoDEmanX** [comment]
![call-outgoing](https://cloud.githubusercontent.com/assets/1309249/9156837/086c35e8-3ee8-11e5-9495-2763b603ce3a.png) https://www.dropbox.com/s/5z8jf8btbrmk2tc/call-outgoing.svg?dl=0
![call-incoming](https://cloud.githubusercontent.com/assets/1309249/9156838/08702572-3ee8-11e5-87a4-ce9cd9d12c22.png) https://www.dropbox.com/s/6tmyebfso11mfgd/call-incoming.svg?dl=0

@Templarian: not pixel-perfect on purpose, the missed call icon by Google uses 1.5px line width.

**Comment by Bramengton** [comment]
excellent

**Comment by Templarian** [comment]
[![phone-incoming](https://materialdesignicons.com/icon/phone-incoming)](https://materialdesignicons.com/icon/phone-incoming) [![phone-outgoing](https://materialdesignicons.com/icon/phone-outgoing)](https://materialdesignicons.com/icon/phone-outgoing)
