### ISSUE TITLE
Hotel

### ISSUE THREAD

**Issue by Kugeleis** [Templarian/MaterialDesign#5890]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like to have a house-like item indicating a hotel.

## Examples

It could be a capital H with a roof
```
^
H
```
...as an ugly illustration :)

**Comment by goyney** [comment]
While hotel might start with the letter H in most languages, it is not true in non-latin languages. This is definitely a language conflict and there are other icons that can be used to represent a hotel. Google uses `bed`, for example.

However, we do have other home icons with the latin letters A, B, G, and L, so there is precedence. @Templarian your thoughts?

**Comment by goyney** [comment]
We're going to pass on this for now and lean on the big names in mapping to provide precedence. As stated previously, Google uses `bed` to designate a hotel. That should work well contextually.

Also, "H" is universally used for hospitals, so this could be a very large confusion point.

Thanks for your suggestion.
