### ISSUE TITLE
mdi-progress-question horizontal bar

### ISSUE THREAD

**Issue by uself08** [Templarian/MaterialDesign#5894]
Hi, 

Using firefox (86.0.1 (64-bit)) i'm facing a strange horizontal bar (from the top of the '?' to the top of 'F1' on the screenshot) with this icon (and only this icon). I'm able to reproduce it on the mdi cheatsheet (https://pictogrammers.github.io/@mdi/font/5.4.55/)

![image](https://user-images.githubusercontent.com/52292999/111271308-5014ec00-8631-11eb-9d10-e54d2db24ba4.png)

This doesn't happen with Chrome, and doesn't happen when zooming above 125%. 

Weird..

**Comment by goyney** [comment]
![Screen Shot 2021-04-08 at 5 01 35 PM](https://user-images.githubusercontent.com/1015040/114101939-1465ee80-988c-11eb-99a2-c29c64a6e9cf.png)

I am unable to reproduce this in Firefox 87. This is likely a browser display bug.

I have also inspected the SVG path data for that specific icon and do not see anything that looks like a problem.

**Comment by Sebi11** [comment]
Hi!
I'm also facing the same issue, only on this icon, with Google Chrome version 93:
![image](https://user-images.githubusercontent.com/15053203/135216529-84922791-2083-4b60-bca3-6ce5de311945.png)
I have to zoom a lot to get rid of it.
The issue is visible when I integrate the icon on my website AND on the list of icons [on the documentaion](https://pictogrammers.github.io/@mdi/font/6.1.95/).

**Comment by goyney** [comment]
I'm on Chrome 94 and do not see it at 100% zoom. Please update and test again.
![Screen Shot 2021-09-29 at 9 20 32 AM](https://user-images.githubusercontent.com/1015040/135287511-20d152f3-5d53-40ab-9a2d-d18048505af4.png)

If you still see it after updating, please try disabling all browser extensions. If that helps, see if you can pinpoint which one is causing the issue.

Without proper troubleshooting steps, we can't help you. 😅

**Comment by Sebi11** [comment]
I updated Chrome toi version 94, same bug. It happens on Firefox 92 as well. I have no extensions on Firefox. I disabled the one I have on Chrome, without effect. 
On both browsers, the bug disappears at zoom level of 150% on a full HD screen of 24 inches. On my laptop srceen (full HD, 15 inches), the bug disappears at 100%. I will try later with a 4K 27" screen. I might be a screen glitch, but that's kinda strange it happens only on this icon.

**Comment by goyney** [comment]
What OS and screen resolution?

**Comment by Sebi11** [comment]
I'm running Windows 10, up-to-date. I've set the same resolution as the screen: full HD. The laptop screen has a scale text zoom of 125%, the other one stays at 100% scale.

**Comment by Sebi11** [comment]
I've just checked on a 27 inches 4K sreen with a 150% display scale in Windows: the bug only appears below a zoom of 100%.

**Comment by lcnittl** [comment]
Judged by the position of the horizontal line, I can imagine it is coming from 2 rogue nodes (coordinates `(20, 4)` and `(44, 4)`) that are present in the svg (according to Inkscape):

![image](https://user-images.githubusercontent.com/23134999/190263107-a16a8fc1-418e-4f93-9a11-290adf1cfb8a.png)

With stroke colored:

![image](https://user-images.githubusercontent.com/23134999/190265338-3a227c1a-d93f-4150-affb-66ff7beca9d1.png)

I assume it has to do with `18.37M20 4H44M13` (which includes the 2 nodes `M20 4H44`) in the [current version of file](https://github.com/Templarian/MaterialDesign/blob/73e0a2faf8aaa031988e021d857e4f2e42451c19/svg/progress-question.svg).

I can open a PR if you want.

**Comment by Templarian** [comment]
This was fixed, thanks @lcnittl. Also rotates the circle correctly. I think this was exported in possibly illustrator based on the vector, which depending on the version sometimes does weird things.
