### ISSUE TITLE
classical search icon

### ISSUE THREAD

**Issue by halillusion** [Templarian/MaterialDesign#5897]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

The magnifying glass icon found in many interfaces and used for search purposes is used to trigger search modules.

## Examples

For example: https://upload.wikimedia.org/wikipedia/commons/thumb/0/0b/Search_Icon.svg/1024px-Search_Icon.svg.png

The icon presented in the package has a globe icon in the magnifying glass section. It would be nice, even if it's a plain version.

**Comment by JamesCoyle** [comment]
Not really sure how you missed this as it definitely comes up when you type search on both our site and browser extension.

[![](https://materialdesignicons.com/icon/magnify)](https://materialdesignicons.com/icon/magnify)

**Comment by halillusion** [comment]
Hi @JamesCoyle 

If you are using the address and you think you may come across it by searching it as "search", this is quite normal.

https://pictogrammers.github.io/@mdi/font/5.9.55/

**Comment by JamesCoyle** [comment]
That page is just for reference of font codepoints. You still need to use the main site to search for icons as we alias all icons with common search terms.
