### ISSUE TITLE
Beach Outline

### ISSUE THREAD

**Issue by 4nk1r** [Templarian/MaterialDesign#5900]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/63253661/111904298-003a8880-8a68-11eb-83c0-92da9d1db3d5.png)

## Zip Download

[ic_beach_outline.zip](https://github.com/Templarian/MaterialDesign/files/6177363/ic_beach_outline.zip)

**Comment by goyney** [comment]
@4nk1r Did you extract this icon from a Google application or is this your own creation? This does not match our current `beach` icon.

**Comment by goyney** [comment]
Thoughts on updating our current `beach` to these and adding the outline variant proposed here?
![image](https://user-images.githubusercontent.com/1015040/131919863-44111d6c-7539-4cd3-b323-0b8a75080e29.png)![image](https://user-images.githubusercontent.com/1015040/131919895-c2857dc7-096f-4f03-b8da-495b502eb6a0.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7101918/Archive.zip)

Current `beach` for reference:
![image](https://user-images.githubusercontent.com/1015040/131919964-d957b766-c114-4a22-bb91-46bd67f5efbd.png)

**Comment by goyney** [comment]
Also added Google's beach umbrella in this issue:
[![umbrella-beach](https://materialdesignicons.com/icon/umbrella-beach)](https://materialdesignicons.com/icon/umbrella-beach)[![umbrella-beach-outline](https://materialdesignicons.com/icon/umbrella-beach-outline)](https://materialdesignicons.com/icon/umbrella-beach-outline)

**Comment by 4nk1r** [comment]
@goyney, it's my own, not from Google app. Google's umbrella looks more beautiful.
