### ISSUE TITLE
PH and EC

### ISSUE THREAD

**Issue by iyotee** [Templarian/MaterialDesign#5902]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by iyotee** [comment]
![ph ecPNG](https://user-images.githubusercontent.com/12566055/111937717-a5854900-8ac8-11eb-8d5d-c0d882aab2ba.PNG)

**Comment by Templarian** [comment]
- `pH` - Norma l PH scale... 0 to 14, 7 being water
- `EC` - Electrical conductivity

I'm not sure internationalization applies to these.

**Comment by goyney** [comment]
`pH` might be worth breaking our rule on text-based icons, but electrical conductivity definitely is not. `lightning-bolt` should suffice for that use case.

**Comment by goyney** [comment]
[![ph](https://materialdesignicons.com/icon/ph)](https://materialdesignicons.com/icon/ph)
