### ISSUE TITLE
Wallet Outline

### ISSUE THREAD

**Issue by 4nk1r** [Templarian/MaterialDesign#5903]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/63253661/111962206-d6d73680-8b13-11eb-8eae-9d5fcd4a5985.png)

## Zip Download
[ic_wallet_outline.zip](https://github.com/Templarian/MaterialDesign/files/6180688/ic_wallet_outline.zip)

**Comment by goyney** [comment]
`wallet-outline` is already included in our library.

[![wallet-outline](https://materialdesignicons.com/icon/wallet-outline)](https://materialdesignicons.com/icon/wallet-outline)
