### ISSUE TITLE
squeezelite or squeezecast 

### ISSUE THREAD

**Issue by fabiendostie** [Templarian/MaterialDesign#5904]
![squeeze_lms](https://user-images.githubusercontent.com/53846121/112128703-1138e600-8b9d-11eb-9deb-8eb26a2338d0.png)
![squeezelite2](https://user-images.githubusercontent.com/53846121/112128711-1302a980-8b9d-11eb-901f-27de19c10ad5.png)
![squeezelite](https://user-images.githubusercontent.com/53846121/112128738-1a29b780-8b9d-11eb-8a2c-5451527d0675.png)

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

to represent squeeze (logitech media server, slimserver, squeezebox etc...) family enabled players in home assistant and others. so we can differentiate with google cast, alexa, etc...

thank you so much

**Comment by goyney** [comment]
This is borderline brand icon rejection, but most definitely device-specific rejection. Either way, there are more generic casting icons you can. Thanks for the suggestion.

**Comment by fabiendostie** [comment]
Did you at least google it? this is a opensource project, which can be used on all linux platforms, mac, windows, raspberry pi, and all sbc, even on android and ios... not what i would call device specific... you can install the server which there is multiple distributions fro different devs... some run on tinycore linux some on windows some on atari computers even...

I would ask you to reconsider and actually do a bit of research, just at least google it.

PicorePlayer is one of the most open and advanced music server and player out there and it is opensource...

**Comment by goyney** [comment]
Then...


### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
