### ISSUE TITLE
microsoft-visual-studio-code-outline

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#5905]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
![image](https://user-images.githubusercontent.com/44722574/112323738-1db75e80-8cc3-11eb-9da5-4f9b61623382.png)

## Zip Download
[microsoft-visual-studio-code-outline.zip](https://github.com/Templarian/MaterialDesign/files/6197862/microsoft-visual-studio-code-outline.zip)

**Comment by goyney** [comment]
The brand icons we do allow in the library we do not modify in any way. This would be an unacceptable variation unfortunately. Thanks for the suggestion.
