### ISSUE TITLE
qrcode-scan incorrect size

### ISSUE THREAD

**Issue by dandencker** [Templarian/MaterialDesign#5908]
Maybe, theres a resonable explanation - but is there any reason why some icons does not respect the padding of most icons?

Eg.
mdi-qrcode-scan (No padding)
mdi-qrcode (Have a light padding)

![example](https://user-images.githubusercontent.com/60612546/112988413-19c48a00-9164-11eb-8799-0684224e92fc.JPG)

It makes my brain hurt when trying to add icons of same size on a toolbar :-)

/Dan

**Comment by Templarian** [comment]
Yeah, that is a bug. The scan overlay should be 20x20 (not sure how it got in like that).

**Comment by goyney** [comment]
This is not a bug. The scan modifier purposely sits in the 2dp buffer area on all scan variants.
