### ISSUE TITLE
View Light Table

### ISSUE THREAD

**Issue by blude** [Templarian/MaterialDesign#5909]
I propose a View Light Table icon which would go along with View Grid, View Dashboard, View Column, View Quilt, View Stream, View Compact, View Agenda, among others.

The icon represents a large media element on top of a row of smaller media elements.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

<img width="343" alt="view-light-table-iconpreview" src="https://user-images.githubusercontent.com/616018/113009221-0cb19600-9178-11eb-8970-f1c005998553.png">

## Usage

The new View Light Table icon is suitable for toolbars and button groups, in which the user can toggle between different viewing modes, like so:

<img width="322" alt="usage-view-modes" src="https://user-images.githubusercontent.com/616018/113010873-7a11f680-9179-11eb-9721-cc22e8dadad0.png">

## Zip Download

[view-light-table.svg.zip](https://github.com/Templarian/MaterialDesign/files/6229894/view-light-table.svg.zip)

**Comment by goyney** [comment]
Can you talk about the name? I think we'll add the icon, but I've never heard this view called a "view light table." Want to make sure we name it correctly.

**Comment by blude** [comment]
The "view" part comes from other icons names already in the library: view agenda, view array, view carousel, view column, view dashboard, view day, view grid, view headline, view list, etc…

I'm no native English speaker but some synonyms that come to mind: gallery, carousel (already in use), light box, slider, filmstrip.

Hope it helps!

**Comment by goyney** [comment]
[![view-gallery](https://materialdesignicons.com/icon/view-gallery)](https://materialdesignicons.com/icon/view-gallery)[![view-gallery-outline](https://materialdesignicons.com/icon/view-gallery-outline)](https://materialdesignicons.com/icon/view-gallery-outline)
