### ISSUE TITLE
Paw

### ISSUE THREAD

**Issue by erenemre** [Templarian/MaterialDesign#591]

**Comment by CoDEmanX** [comment]
Not quite happy with the result, maybe someone else can improve on it?
![paw](https://cloud.githubusercontent.com/assets/1309249/9156537/3ee41fe6-3ede-11e5-8ea3-c4582b7d3d5b.png) https://www.dropbox.com/s/4pts2ykkm3l2gyx/paw.svg?dl=0

**Comment by Templarian** [comment]
![image](https://cloud.githubusercontent.com/assets/338885/9156634/80492d38-3ea6-11e5-914d-dd75b1470b1d.png)

Maybe curve it up in the middle slightly like the above icon.

**Comment by CoDEmanX** [comment]
Yeah... but I think what makes it look so weird is mostly the 2px spacing between the elements. They are much closer in all reference images I've seen...

**Comment by Templarian** [comment]
That's fine, I think it is fine how it is.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/paw

**Comment by CoDEmanX** [comment]
Do you think this is better?
![paw2](https://cloud.githubusercontent.com/assets/1309249/9156800/c301f5a2-3ee6-11e5-97c1-405109ea9849.png) https://www.dropbox.com/s/je3soa6662xoptw/paw2.svg?dl=0

**Comment by Templarian** [comment]
It needs to still curve up in the middle at the bottom I think?

**Comment by CoDEmanX** [comment]
More like this?
![paw3xl](https://cloud.githubusercontent.com/assets/1309249/9156853/9b294c04-3ee8-11e5-970b-051d9f9b0e95.png) ![paw3](https://cloud.githubusercontent.com/assets/1309249/9156849/84668d92-3ee8-11e5-8afd-73dc33f5ce58.png)

**Comment by Templarian** [comment]
That much much more like a paw. SVG?

**Comment by CoDEmanX** [comment]
Added link above.

Another variant with rounder toes:
![paw4](https://cloud.githubusercontent.com/assets/1309249/9156895/8e177558-3ee9-11e5-815c-91f3c85dc0cc.png) https://www.dropbox.com/s/fuexpdedz41qzw5/paw4.svg?dl=0

**Comment by Templarian** [comment]
Updated to Paw4.
