### ISSUE TITLE
✳ 8 Points Asterisk with uniform stroke

### ISSUE THREAD

**Issue by nitin2953** [Templarian/MaterialDesign#5912]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Usage
Star, Asterisk, Union, Miscellaneous Things  

![asterisk_s](https://user-images.githubusercontent.com/34852979/113172977-cf8fe700-91fd-11eb-9acf-48119b068c79.png)

 ## Preview
![image](https://user-images.githubusercontent.com/34852979/113173931-bf2c3c00-91fe-11eb-8a15-44f42b0435e0.png)
  

Extracted from Google Sans/Product Sans font  _Asterisk LIKE character_  => ` ⁕ `

### Font Links:  
- woff2:  [https://fonts.googleapis.com/css?family=Google+Sans](https://fonts.googleapis.com/css?family=Google+Sans)
- woff2:  [https://fonts.googleapis.com/css?family=Product+Sans](https://fonts.googleapis.com/css?family=Product+Sans)
- ttf:  [https://befonts.com/product-sans-font.html](https://befonts.com/product-sans-font.html)
- LATEST ttf:  [https://github.com/nongthaihoang/google_sans_plus_font](https://github.com/nongthaihoang/google_sans_plus_font)  

### Bugs
- It's width are not uniform at 45° & 135°  
- And stroke is not 2px wide at 24px/24px viewbox -> 18px/18px icon size

### Conclusion
- I don't know Material design guidelines  
- SO, I request official member to include this in library, ? after Perfecting it ?

## Zip Download
[asterisk.zip](https://github.com/Templarian/MaterialDesign/files/6237349/asterisk.zip)

**Comment by goyney** [comment]
We're just going to update our current icon as it is not currently very Material.

**Comment by goyney** [comment]
Updated.
