### ISSUE TITLE
[BUG/TYPO] checkbox-multiple-blank-outline

### ISSUE THREAD

**Issue by laurent-brisbois** [Templarian/MaterialDesign#5914]
Hello everyone !

There might be a typo in the icon `checkbox-multiple-blank-outline`.
Note that there is nothing between `check` and `box`.

While there is for `check-box-multiple-outline`.

Is that normal ?

Just sayin' so that icon names are consistent between each other.

**Comment by goyney** [comment]
We will be updating the follow two icons names:

- `check-box-multiple-outline` ➜ `checkbox-multiple-outline`
- `check-box-outline` ➜ `checkbox-outline`

**Comment by goyney** [comment]
Updated.
