### ISSUE TITLE
Sausage-off

### ISSUE THREAD

**Issue by SvenVdv** [Templarian/MaterialDesign#5915]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm using the sausage icon (from #2933) for sausage profiles in our fermentation project (design phase for now): 
![sausage](https://user-images.githubusercontent.com/6322493/113476668-29eaab00-947d-11eb-9c68-6845db373abe.png)

We would like to use the "off" version for when the profile is not active, if anyone could make that

## Examples

An example would be the cheese-off icon:
![cheese-off](https://user-images.githubusercontent.com/6322493/113476620-e7c16980-947c-11eb-8f46-9d71c8629986.png)

🙏 🙇

**Comment by SvenVdv** [comment]
I went ahead and tried it out myself. Not sure it was done correctly, but I have:
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview
Here's a preview of what I made:
![image](https://user-images.githubusercontent.com/6322493/113518706-49222f00-9588-11eb-9e37-3610da138c5d.png)


## Zip Download
You can download it here:
[sausage-off_icon.zip](https://github.com/Templarian/MaterialDesign/files/6255163/sausage-off_icon.zip)

@Templarian I'm not sure this is the right way to make a contribution to an icon request that I made myself. If I should make a separate issue, please let me know, bc I don't seem to have the ability to add the "contribution" tag ^^

**Comment by goyney** [comment]
[![sausage-off](https://materialdesignicons.com/icon/sausage-off)](https://materialdesignicons.com/icon/sausage-off)

Added. Once you get to 5 added contributions, we can reassign it to you. Thanks!
