### ISSUE TITLE
folder-eye

### ISSUE THREAD

**Issue by gabe4797** [Templarian/MaterialDesign#5916]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For usage with a hidden folder

## Examples

The current file-eye by Michael Irigoyen but with a folder

**Comment by goyney** [comment]
[![folder-eye](https://materialdesignicons.com/icon/folder-eye)](https://materialdesignicons.com/icon/folder-eye)[![folder-eye-outline](https://materialdesignicons.com/icon/folder-eye-outline)](https://materialdesignicons.com/icon/folder-eye-outline)
