### ISSUE TITLE
file-deleted

### ISSUE THREAD

**Issue by gabe4797** [Templarian/MaterialDesign#5917]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A file icon with a delete badge to indicate a file has been deleted

## Examples

A file icon with a delete badge

**Comment by goyney** [comment]
We have `file-remove` already. The trash icon is not an icon modifier and is too detailed to shrink down to a modifier size in the space provided.

If a file has been deleted, you might considering using color or opacity to convey that it is no longer available in addition to something like `file-remove` or `file-alert`.

**Comment by Templarian** [comment]
Closing this issue as `delete` is not an overlay we're looking to support. Thanks for the icon request.

`delete-circle` uses a smaller `delete` symbol, but not sure it's recognizable.
