### ISSUE TITLE
folder-deleted

### ISSUE THREAD

**Issue by gabe4797** [Templarian/MaterialDesign#5918]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A folder icon with a delete badge to indicate a folder has been deleted

## Examples

A folder icon with a delete badge

**Comment by goyney** [comment]
We have `folder-remove` already. The trash icon is not an icon modifier and is too detailed to shrink down to a modifier size in the space provided.

If a folder has been deleted, you might considering using color or opacity to convey that it is no longer available in addition to something like `folder-remove` or `folder-alert`.

**Comment by Templarian** [comment]
Similar to `file-delete` request. `delete` is not a supported overlay at this time.
