### ISSUE TITLE
Google Calendar icon

### ISSUE THREAD

**Issue by ciscorucinski** [Templarian/MaterialDesign#592]
self explainatory

**Comment by CoDEmanX** [comment]
Do you mean this one?
![screenshot_2015-08-10-23-23-21 2](https://cloud.githubusercontent.com/assets/1309249/9184694/1adbd6dc-3fb7-11e5-947b-7d895677da2c.png)

**Comment by ciscorucinski** [comment]
yes, what is the name for it? I search for "google" and "calendar" but nothing came up

**Comment by CoDEmanX** [comment]
Google does not provide this icon, and it's not very material either.
@Templarian: What do you think?

I tried to re-create it, but it doesn't work well at 24px:
![google-calendar](https://cloud.githubusercontent.com/assets/1309249/9194457/a3849c26-401b-11e5-8101-af03f9099b38.png) https://www.dropbox.com/s/dzw8npzcissgy10/google-calendar.svg?dl=0

**Comment by ciscorucinski** [comment]
Yeah, I think one of the standard calendar icons will have to do. Thanks

**Comment by Templarian** [comment]
Yea, thanks @CoDEmanX, but I agree with you it does not fit well with the style.

**Comment by PeterShaggyNoble** [comment]
Google have since added this to the extended stock icons:

![timely](https://user-images.githubusercontent.com/15157491/36729511-56abfc08-1bbc-11e8-93d3-4c3c7526df65.png)
