### ISSUE TITLE
Payement

### ISSUE THREAD

**Issue by khaouet** [Templarian/MaterialDesign#5921]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

![image](https://user-images.githubusercontent.com/39202108/113716978-09238f00-96e3-11eb-9ac7-6ef584beadcf.png)

**Comment by kospl** [comment]
https://fonts.google.com/icons?icon.query=payments

**Comment by goyney** [comment]
[![cash-multiple](https://materialdesignicons.com/icon/cash-multiple)](https://materialdesignicons.com/icon/cash-multiple)

`cash-multiple` already exists.
