### ISSUE TITLE
account-cached

### ISSUE THREAD

**Issue by johnlwebb3** [Templarian/MaterialDesign#5922]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

My application uses a different User style icon depending on how a user logs in. A user with a check (mdi-account-check) to indicate Username/password. A user inside a smart card (mdi-smart-card-reader-outline) when the user signs in with client certificates. It would be great to have a user with a little storage cylinder at the bottom right to indicate when the user is logged in using cached credentials like from localStorage.

## Examples

Include any example images so we know what the icon should look like.
mdi-account-check
mdi-smart-card-reader-outline

New request would be like mdi-account-check but with a storage cylinder instead of a check.
maybe something like mdi-account-cached or whatever makes sense in your naming protocol...

Thanks,

John Webb

**Comment by goyney** [comment]
A little storage cylinder is not one of our modifiers unfortunately. Additionally, to shrink it down to a modifier size just won't work in the space provided. While I understand your use case, I think we'll have to brainstorm another way of depicting a "use cache".

**Comment by johnlwebb3** [comment]
Thanks for the reply. Please let me know if you move forward on anything.
I'm certain you are in a better position to decide what works with your
icon library.

Thanks,

John Webb
512.285.9568o
512.281.6265m
***@***.***

**Comment by goyney** [comment]
[![account-sync](https://materialdesignicons.com/icon/account-sync)](https://materialdesignicons.com/icon/account-sync)[![account-sync-outline](https://materialdesignicons.com/icon/account-sync-outline)](https://materialdesignicons.com/icon/account-sync-outline)

**Comment by johnlwebb3** [comment]
Those look great! We'll give them a try and thanks a lot!
