### ISSUE TITLE
Roof tilt window open and closed icon

### ISSUE THREAD

**Issue by degrashopper** [Templarian/MaterialDesign#5923]
I have:

- [ X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

see when the roof window is open or closed.

![png-transparent-roof-window-golden-gate-university-velux-window-angle-furniture-rectangle-thumbnail](https://user-images.githubusercontent.com/8464491/113819053-10957780-9779-11eb-96be-f13680caedb2.png)

**Comment by goyney** [comment]
This is going to be difficult to do without incorporating perspective.

**Comment by degrashopper** [comment]
Hmm you've got a point there. Viewing it from the side is also not an option. When it is closed you only see a line. I will close this change request then.

**Comment by rchiileea** [comment]
https://github.com/Templarian/MaterialDesign/issues/6306

**Comment by caco3** [comment]
> This is going to be difficult to do without incorporating perspective.

What about this: https://github.com/Templarian/MaterialDesign/issues/7464
