### ISSUE TITLE
Bar or liquor cabinet icon

### ISSUE THREAD

**Issue by greenring** [Templarian/MaterialDesign#5925]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To use in a home automation dashboard to control lights in liquor cabinet

## Examples

Maybe a series of bottles
https://www.google.com/search?q=bottles+icon

or something representing a cabinet of drinks:
https://www.google.com/search?q=liquor+cabinet+icon

**Comment by goyney** [comment]
[![liquor](https://materialdesignicons.com/icon/liquor)](https://materialdesignicons.com/icon/liquor)
