### ISSUE TITLE
Order By (sort)

### ISSUE THREAD

**Issue by WeanaSchnitzl** [Templarian/MaterialDesign#5926]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would like to use it on the top of a table (in a table header row) or on top of a list, to provide an common "order by" functionality.
![orderby_ifon_idea](https://user-images.githubusercontent.com/7577731/114298435-ad784d80-9ab6-11eb-999e-1864b818e79d.png)

There are existing sort icons for alphabetical sorting and date/time sorting, and some common icons to show when sorting up or down. On first (unsorted) show of the table i would provide the "not sorted" icon to the user an icon to click for sorting. 
After click i would show on of the others ... up or down  ... concerning sort order.

## Examples
the idea is to make 3 icons with 2 vertical arrows, one up and one down.
not sorted: both arrows have same width
ascending: the up arrow is fat, the down arrow thin
descending: this down arrow is fat, the up arrow is fat.

thx
Werner

**Comment by goyney** [comment]
We have your first request as `swap-vertical`.

[![swap-vertical](https://materialdesignicons.com/icon/swap-vertical)](https://materialdesignicons.com/icon/swap-vertical)

After that, you can simply use the appropriate sort icon for how the data is sorted.

**Comment by Simran-B** [comment]
The design pattern I would use: show an upward or downward pointing arrow if the data is sorted and no arrow at all if it's unsorted. That should be cleaner and clearer than having arrows pointing in both directions.

**Comment by WeanaSchnitzl** [comment]
You're right .. thx!!!
