### ISSUE TITLE
clipboard text clock

### ISSUE THREAD

**Issue by nmtri3** [Templarian/MaterialDesign#5927]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

![image](https://user-images.githubusercontent.com/43428102/114331475-43bb7a80-9b6e-11eb-94cd-ee95bc66bd3e.png)

**Comment by goyney** [comment]
[![clipboard-text-clock](https://materialdesignicons.com/icon/clipboard-text-clock)](https://materialdesignicons.com/icon/clipboard-text-clock)[![clipboard-text-clock-outline](https://materialdesignicons.com/icon/clipboard-text-clock-outline)](https://materialdesignicons.com/icon/clipboard-text-clock-outline)
