### ISSUE TITLE
source commit

### ISSUE THREAD

**Issue by nmtri3** [Templarian/MaterialDesign#5928]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

![image](https://user-images.githubusercontent.com/43428102/114331524-68afed80-9b6e-11eb-8348-77f9223c2147.png)

**Comment by goyney** [comment]
Already exists. You may need to rotate it on your own if you want it to be horizontal.

[![source-commit](https://materialdesignicons.com/icon/source-commit)](https://materialdesignicons.com/icon/source-commit)
