### ISSUE TITLE
Bookshelf icon

### ISSUE THREAD

**Issue by evanaccs** [Templarian/MaterialDesign#593]
It could be something like a bar horizontally representing the bookshelf and bars vertically on top of it representing the books.

**Comment by CoDEmanX** [comment]
I don't something like below but compliant to MD guidelines would be recognizable as bookshelf I'm afraid:
![Imgur](http://i.imgur.com/jYogepH.png?2)
![Imgur](http://i.imgur.com/ZrpSTcj.png?1)

**Comment by evanaccs** [comment]
thanks
