### ISSUE TITLE
Hdmi with input number 

### ISSUE THREAD

**Issue by Nik18111997** [Templarian/MaterialDesign#5930]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
You didn't fill out the issue template, but based on the title of the issue, this is not something we are likely to add.

**Comment by Templarian** [comment]
Definitely get the use case, but using a number or the box numbers might be best. Little niche and we would have to add a lot... my AV system has 6 I think.
