### ISSUE TITLE
Cannot upload MDI icons (any-more) due to presence of DOCTYPE header

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#5934]
Hello,
I really enjoy materialdesignicons.com and penpot.app for my FOSS project contribution. Unfortunately a recent change in Penpot made it impossible to upload MDI icons, apparently due to the fact that the provided SVG files contain a DOCTYPE header. Apparently this is a security risk (for Penpot).

When I [brought this up to Penpot](https://github.com/penpot/penpot/issues/826) they said they're working on a solution, but also suggested to report it to you folks to ask if this particular header could be removed. So, there you go, please find here the request :)

Would love to continue both without much hassle (as before) or any security risk for either platform/project 🙂

(Sorry - I realise it's not really a bug, but wasn't sure what other template to pick.)

**Comment by goyney** [comment]
Including a `<!DOCTYPE>` in an SVG is allowed as part of the SVG spec and is included for full backwards compatibility. That being said, I'm finding conflicting information about whether or not it is still required in 2021.

@Templarian Is going to have to a take a stance on this and give an answer. If anything is changed, it likely *will not* happen to the existing website's exporter, but would be fixed once the new site is released.

**Comment by goyney** [comment]
Here's another option: Go install the MDI Icon Picker Chrome extension. https://chrome.google.com/webstore/detail/materialdesignicons-picke/edjaedpifkihpjkcgknfokmibkoafhme?hl=en-US

The download as SVG option on the picker does not include the `DOCTYPE`.

**Comment by Templarian** [comment]
I don't see a reason we need to include the doctype, so I'll just remove it and it will update the next time it syncs to the DB.

**Comment by keunes** [comment]
Thanks for the quick replies and this course of action! :)

**Comment by goyney** [comment]
@Templarian Was this done?

**Comment by goyney** [comment]
We will be removing `DOCTYPE` declarations in v7.

**Comment by goyney** [comment]
Leaving this issue open until we verify the changes work as expected.

**Comment by goyney** [comment]
Everything looks to be working as expected. This should be considered completed and the changes will be seen in v7 release.
