### ISSUE TITLE
Back 

### ISSUE THREAD

**Issue by mcat56** [Templarian/MaterialDesign#5938]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

To signal going backwards in UI 

## Examples

It would be the current mdi-undo-variant, but instead of a dot at the bottom it would be a continuous line 
https://iconscout.com/icon/back-1667947

**Comment by andrejsharapov** [comment]
maybe `undo-variant` will suit you?

**Comment by mcat56** [comment]
Thank you @Xenomorph99 that would cover the icon of interest.
Thank you @andrejsharapov

**Comment by Xenomorph99** [comment]
Changed the naming convention from `turn-*` and `turn-u-*` to simply `arrow-*` and `arrow-u-*` and added them to the library with "undo" and "redo" and "turn" aliases.
