### ISSUE TITLE
Exit

### ISSUE THREAD

**Issue by mcat56** [Templarian/MaterialDesign#5939]
I have:

- [ X ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Demonstrate exit in UI 

## Examples

<img width="165" alt="Screen Shot 2021-04-19 at 8 58 38 AM" src="https://user-images.githubusercontent.com/51488670/115257670-88569100-a0ed-11eb-83e5-8dfc2555ee18.png">

**Comment by Templarian** [comment]
Would `login` / `logout` work for this?

**Comment by mcat56** [comment]
Would prefer this image, though logout is the best fit otherwise

**Comment by Templarian** [comment]
Since we have a pretty hard rule against perspective I'm going to close this one. Even the `door` icons are flat.

If you can find other examples without perspective we can see if it fits.
