### ISSUE TITLE
Campfire icon 

### ISSUE THREAD

**Issue by river-visual** [Templarian/MaterialDesign#594]
smtn like:

![campfire-material](https://cloud.githubusercontent.com/assets/8170805/9193204/0372e124-4012-11e5-9d80-1df4fd4a2804.jpg)

Did it quick, not happy with it.

**Comment by CoDEmanX** [comment]
I like the idea but it's hard to improve...

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/51007008-c5497b80-1513-11e9-9357-098289c1e46c.png)
[campfire.svg.zip](https://github.com/Templarian/MaterialDesign/files/2747656/campfire.svg.zip)

**Comment by Templarian** [comment]
Added. 😃
