### ISSUE TITLE
OK icon

### ISSUE THREAD

**Issue by mcat56** [Templarian/MaterialDesign#5940]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Click OK button on remote

## Examples

https://www.freepik.com/free-icon/ok-button_739316.htm

**Comment by Templarian** [comment]
Due to the vast amount of languages using the icon set we try to never include any English words in icons. For that reason this one is going to be closed.
