### ISSUE TITLE
Worn brake linings icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#5944]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It would be great to have an icon to represent "Worn brake linings". We need that to give an icon to car data.
Thanks

## Examples

![image](https://user-images.githubusercontent.com/45227578/115399391-6db51280-a1e8-11eb-9690-ee03717dfaa6.png)

Ref : http://auto.gosstandart.info/data/documents/ISO-2575.pdf (Page 17)

**Comment by goyney** [comment]
This will be added in #6159. Please subscribe that issue for status updates.
