### ISSUE TITLE
a combo between 'flag' and 'crop_free': call it 'include marked'

### ISSUE THREAD

**Issue by RoarGronmo** [Templarian/MaterialDesign#5949]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It is just an icon i miss, I use three others (but miss this one), focus_strong, crop_free, center_focus_weak.

## Examples

 focus_strong, crop_free, center_focus_weak

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
This is very niche. I think your best bet would be to use `scan-helper` with `flag` to make your own icon stack.
