### ISSUE TITLE
crown moulding lighting

### ISSUE THREAD

**Issue by StealthyJedi** [Templarian/MaterialDesign#5950]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by StealthyJedi** [comment]
https://i.pinimg.com/originals/b9/7f/ed/b97fed28ab914b62f5e4ab1eaafd32ef.jpg

**Comment by goyney** [comment]
I don't know how we would possibly be able to represent this in an icon.
