### ISSUE TITLE
Pendant Lamp

### ISSUE THREAD

**Issue by hesspoint** [Templarian/MaterialDesign#5952]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For smart home applications like Home Assistant

## Examples

![7E3A1612-D23A-4D63-AAD9-F4F5619B8108](https://user-images.githubusercontent.com/67288231/115969980-02e53d80-a540-11eb-914c-378b3bf8f53a.jpeg)

**Comment by goyney** [comment]
This is just a variation of a ceiling light. There's literally a million styles of these, so we don't have a interest in adding everyone we encounter.

I'd check out `ceiling-light`, `chandelier`, or `wall-sconce-flat` for this use case.

Thanks for your suggestion.

**Comment by GeeGee-be** [comment]
It's a good request. The existing ones are old fashion. I would also like a modern version like shown above. Still can't find a suitable one in the library. Thx
