### ISSUE TITLE
Arc Lamp

### ISSUE THREAD

**Issue by hesspoint** [Templarian/MaterialDesign#5953]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home Automation

## Examples

![9A073FA3-83A5-49BA-B3DF-7A8004C4007C](https://user-images.githubusercontent.com/67288231/115970600-bbf94700-a543-11eb-904f-2589a048faf1.jpeg)

**Comment by goyney** [comment]
In the space we have, I don't know how this works. I also don't think we need to add every variation of lamp style out there. It seems like we're trying to be overly literal here, when icons are meant to be contextual.
