### ISSUE TITLE
`tray-arrow-down` is missing from @mdi/js

### ISSUE THREAD

**Issue by ZYinMD** [Templarian/MaterialDesign#5954]
I see `tray-arrow-down.svg` exists in the repo, but isn't included in `@mdi/js`.  

(I apologize if this is expected, I don't know enough about your workflow. )

**Comment by Templarian** [comment]
@ZYinMD Teams been a little busy lately, but it will be in the 6.0 release. Until then just hardcode the path data in a constants file and import it until 6.0 is released. Learn more about 6.0 #5409
