### ISSUE TITLE
Updating to latest Material design library

### ISSUE THREAD

**Issue by oscargoossens** [Templarian/MaterialDesign#5955]
Love the work you're putting in, it's helping me out tons! 
Material.io has meanwhile released some new icons that aren't (yet) included here. Would it be possible to include that latest release here as well?

Next to that, I was wondering if there's a reason for not literally using Google's naming for icons that find their origin on material.io.

**Comment by goyney** [comment]
We evaluate and add icons on a request basis from Google's library. Please open a request for each icon you would like to see added so we can address each one. Thanks.
