### ISSUE TITLE
Dehumidifier

### ISSUE THREAD

**Issue by cooperised** [Templarian/MaterialDesign#5956]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Useful icon to have by a switch in Home Assistant to control a dehumidifier, for example.  air-humidifier exists, but not air-dehumidifier.

## Examples

Sorry, I'm no designer!  Perhaps

![Dehumidifier](https://cdn2.iconfinder.com/data/icons/lined-air-conditioning/48/a-11-512.png)

or

![Dehumidifier](https://cdn0.iconfinder.com/data/icons/elasto-heating-and-cooling/26/dehumidifier-512.png)

**Comment by goyney** [comment]
We have `water-off` and `humidifier`. Do those not work?

**Comment by goyney** [comment]
Closing due to lack of response. If you have some more information to help us with this request, please feel free to comment back here.

**Comment by cooperised** [comment]
Sorry, I didn't get a notification on the first request for some reason.

I don't believe that `water-off` or `humidifier` works.

`water-off` doesn't allow 'on' and 'off' variants, so although it could perhaps represent a dehumidifier on its own, it could not represent 'dehumidifier on' and 'dehumidifier off'.

`humidifier` is close, because the icon doesn't indicate the direction of travel of the water; but it would be possible to have both a humidifier _and_ a dehumidifier on the same property and it would be useful to differentiate between them.  (Case in point: my house dates from ~1750 and is damp, and the garage from which I work is new and dry.)

**Comment by goyney** [comment]
[![air-humidifier-off](https://materialdesignicons.com/icon/air-humidifier-off)](https://materialdesignicons.com/icon/air-humidifier-off)

**Comment by cooperised** [comment]
Indeed, `air-humidifier` and `air-humidifier-off` could work but don't permit the a distinction between a humidifier and a dehumidifier, as noted above.

**Comment by julitool** [comment]
I still think this is worth checking out indeed a humidifier and a dehumidifier are different devices that indicate different cappabilities and simply do not resemble the device in question.
I am not a designer as the OP but a Device with a drain hose and a handle on the top with maybe waves indicating air somewhere?

Respectfully I ask to reconsider implementing a suitable solution to this.

Thanks
