### ISSUE TITLE
Add a format-squiggly icon

### ISSUE THREAD

**Issue by Whiletru3** [Templarian/MaterialDesign#5957]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

there are format-underline, format-bold, format-italic but no format-squiggly

## Examples

https://support.kdanmobile.com/hc/article_attachments/217907827/1.8-1.png

**Comment by goyney** [comment]
Your suggestion is just a variation of `format-underline`. In nearly every application that offers variations on the underline, they are kept under the underline grouping for UX reasons.

This is an actual example from an application I built for a previous company:
![Screen Shot 2021-04-28 at 8 30 06 AM](https://user-images.githubusercontent.com/1015040/116412092-f0972800-a7fb-11eb-955c-774916b12cbd.png)

I think this icon is too niche, would open the door to other underline variation icons (which would also be too niche), and promotes bad user experience. I do not think we should add it, but will allow the other contributors a chance to weigh in.

**Comment by Whiletru3** [comment]
@goyney, I disagree with you, I need it in a PDF editor for the Squiggly annotation type. The user experience in Adobe Acrobat Reader is very bad on this. You need to create an underline annotation, then go to the properties to change the Style from Straight to Squiggly. In the pdf specification, these 2 annotations are different. In our application it is easier to directly create it with a Squiggly icon instead of having style on underline.

**Comment by Templarian** [comment]
I think squiggly makes sense in this case for the format icon. Especially in applications where you can red underline sections.

**Comment by goyney** [comment]
[![format-underline-wavy](https://materialdesignicons.com/icon/format-underline-wavy)](https://materialdesignicons.com/icon/format-underline-wavy)
