### ISSUE TITLE
Copyleft

### ISSUE THREAD

**Issue by mrshannonyoung** [Templarian/MaterialDesign#5958]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Used as an alternative to [Copyright](https://github.com/Templarian/MaterialDesign/blob/master/svg/copyright.svg).

> Copyleft is the practice of granting the right to freely distribute and modify intellectual property with the requirement that the same rights be preserved in derivative works created from that property.[1] Copyleft in the form of licenses can be used to maintain copyright conditions for works ranging from computer software, to documents, art, scientific discoveries and even certain patents.
> - https://en.wikipedia.org/wiki/Copyleft

## Examples

![Copyleft icon](https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Copyleft.svg/512px-Copyleft.svg.png)

**Comment by goyney** [comment]
Updated `copyright` to reduce points as well.
[![copyright](https://materialdesignicons.com/icon/copyright)](https://materialdesignicons.com/icon/copyright)[![copyleft](https://materialdesignicons.com/icon/copyleft)](https://materialdesignicons.com/icon/copyleft)
