### ISSUE TITLE
Dialog icon

### ISSUE THREAD

**Issue by ciscorucinski** [Templarian/MaterialDesign#596]
Provide an icon that when clicked would indicate that a dialog box will be opened. 

Here is an idea I had, but maybe there is something else to better represent that?
![ic_dialog_black_24dp](https://cloud.githubusercontent.com/assets/8707125/9196464/956f6ff8-4066-11e5-8f82-01d41968bca4.png)

**Comment by CoDEmanX** [comment]
What is your case?
I recommend to focus on the content instead of the interaction pattern, a dialog icon-button seems pretty meaningless. Unless you want to use this to visualize UI interactions?

**Comment by ciscorucinski** [comment]
This is to visualize a UI interaction. I am displaying Model data in a
RecyclerView that holds many different types of data. TextViews,
ImagesViews, VideoViews, RatingBars, etc...

For the TextViews there are 2 types (short length[4 characters], and
variable length [undetermined : short, medium, long, very long]). If the
TextViews go over a set amount of lines (ie 10), then I will ellipsize the
text and I want to display an icon on the side so the user knows it will
open a dialog box to read the whole long text. This is to reduce the amount
of scrolling that is needed and to create a more uniform look and feel. The
ellipsizing and displaying of an action-icon like dialog icon will help
with this.

**Comment by ciscorucinski** [comment]
I did some more searching and found the "more" keyword icons. Maybe one of those will suffice

**Comment by CoDEmanX** [comment]
Did you consider these two stock icons?
https://materialdesignicons.com/icon/open-in-new
https://materialdesignicons.com/icon/open-in-app

I created a reversed version of window-restore, maybe that's more like it?
![dialog](https://cloud.githubusercontent.com/assets/1309249/9237786/7d40721e-414d-11e5-9d61-c571cea9de15.png)

**Comment by ciscorucinski** [comment]
I will play around with them in a few days and see if they look good in the
app. Right now, every icon just seems wrong.

**Comment by Templarian** [comment]
There hasn't been any new information for a while. Closing issue, please reopen if this icon is still needed.
