### ISSUE TITLE
Symfonisk - Table Lamp with speaker

### ISSUE THREAD

**Issue by Warter21** [Templarian/MaterialDesign#5961]
I have:

- [ X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For smart home applications like Home Assistant.
It is a combination of desk/table lamp and wireless-speaker icons.

## Examples

![symfonisk-asztali-lampa-wifi-hangszoroval-fekete__0707109_pe726106_s5](https://user-images.githubusercontent.com/12511189/116883507-f9d22b80-ac25-11eb-895d-54bbe5741d10.png)

**Comment by goyney** [comment]
This seems manufacture- specific and very niche. Gonna pass on it for now. Thanks for the suggestion.
