### ISSUE TITLE
wallet-bifold

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#5963]
The `wallet` / `wallet-outline` icon most closely represents a [wallet clip](https://www.google.com/search?q=wallet+clip&rlz=1C5CHFA_enUS931US931&sxsrf=ALeKk02A3e7-Y1jQHQzisMLzbwEG44FPVg:1620068573695&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjiz-Lema7wAhV8JDQIHWe8DyQQ_AUoAnoECAIQBA&biw=1280&bih=1304), while a [bifold wallet](https://www.google.com/search?q=bifold+wallet&tbm=isch&ved=2ahUKEwiahrPfma7wAhWTRs0KHc4dCZwQ2-cCegQIABAA&oq=bifold+wallet&gs_lcp=CgNpbWcQAzIECCMQJzICCAAyAggAMgIIADICCAAyAggAMgIIADICCAAyAggAMgIIADoHCAAQsQMQQzoFCAAQsQM6BggAEAcQHlCvpwRYprEEYIKyBGgAcAB4AIABU4gBtQWSAQE5mAEAoAEBqgELZ3dzLXdpei1pbWfAAQE&sclient=img&ei=30iQYNoak421Bs67pOAJ&bih=1304&biw=1280&rlz=1C5CHFA_enUS931US931) resonates more with me. I think this variant would be a great addition, as we already have `wallet-membership`, `wallet-giftcard`, and `wallet-travel`. Would love to use this in the app I'm building!

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/2228347/116920312-b79def80-ac0f-11eb-967b-9e9bf3ec9513.png)

## Zip Download

[wallet-bifold.zip](https://github.com/Templarian/MaterialDesign/files/6417057/wallet-bifold.zip)

**Comment by jhil** [comment]
And here's an example of this style of icon in the wild (Robinhood app)
![image](https://user-images.githubusercontent.com/2228347/117506053-33ff3e00-af42-11eb-8011-9191a3c6bc30.png)

**Comment by jhil** [comment]
Here is the SVG of my latest suggestion for wallet-bifold or wallet-bifold-outline. Let me know if anyone has feedback!
[wallet-outline-bifold.svg.zip](https://github.com/Templarian/MaterialDesign/files/6882605/wallet-outline-bifold.svg.zip)

**Comment by jhil** [comment]
One more alternative idea: 
![image](https://user-images.githubusercontent.com/2228347/127094531-7e5fafde-abf0-4a7f-b44c-a2a907162074.png)

**Comment by goyney** [comment]
That version has obvious perspective in it, which goes against guidelines.

**Comment by jhil** [comment]
Oh ok, thanks for letting me know! How did you feel about the prior suggestion? https://github.com/Templarian/MaterialDesign/issues/5963#issuecomment-834758386

If anything, this overlap perspective style is used in other icons in the set, like https://materialdesignicons.com/icon/mailbox-open

**Comment by goyney** [comment]
We made a very special exception for the mailboxes because they are so commonly used and there wasn't a better way to show them. I don't know if a bi-fold wallet meets that same criteria. 🤔

**Comment by goyney** [comment]
We're gonna say no to this one because of the perspective issue and the fact that we already have an acceptable option. If there was no other way to show this, we'd probably take it because it was done very well. Sorry!

**Comment by jhil** [comment]
Would yall be open to reconsidering this? I still find it to be a more compelling and recognizable wallet icon and would love to use it in our app. The current wallet only represents the money clip or "snap" style wallet. If we really wanted to push the perspective principle, this could be interpreted as an [open wallet](https://c1.wallpaperflare.com/preview/464/8/910/coins-credit-cards-mastercard-money.jpg). If you search [wallet icons](https://thenounproject.com/search/icons/?iconspage=1&q=wallet), many of them are the bifold style. Thoughts?

> One more alternative idea: ![image](https://user-images.githubusercontent.com/2228347/127094531-7e5fafde-abf0-4a7f-b44c-a2a907162074.png)

**Comment by jhil** [comment]
Seeing and hearing no feedback, I'm going to move this one forward!

**Comment by jhil** [comment]
[![wallet-bifold-outline](https://materialdesignicons.com/icon/wallet-bifold-outline)](https://materialdesignicons.com/icon/wallet-bifold-outline)
