### ISSUE TITLE
connected / disconnected

### ISSUE THREAD

**Issue by Maverik1408** [Templarian/MaterialDesign#5968]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by Maverik1408** [comment]
create a connected / disconnected from device

**Comment by goyney** [comment]
> Include any example images so we know what the icon should look like.

**Comment by Maverik1408** [comment]
i don't have example i thinking two arrow up right and bottom left
