### ISSUE TITLE
svg toolbar icons for html form elements such as textarea, button, reset button, submit button, text field, select list/combo box etc

### ISSUE THREAD

**Issue by ss2020a** [Templarian/MaterialDesign#5969]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

For a form builder application this is needed when we provide various tool button to create form elements.

## Examples

Include any example images so we know what the icon should look like.
similar to radio button

**Comment by Templarian** [comment]
A lot of these exist already... `form-*` / `format-*`, `textarea`, `form-dropdown`.

Can you include example images from toolbars you've seen these. Might give us an idea for the missing ones.

**Comment by Templarian** [comment]
@ss2020a Can you please refine your request to specific icons not already provided and include examples you've seen elsewhere.

**Comment by goyney** [comment]
Closing because the `Needs More Info` tag was added quite a while ago without any further information provided. If you still have a need for this, please feel free to comment back and we can reopen to continue discussion. Thank you for your suggestion.
