### ISSUE TITLE
Small separate decoration icons to overlap existing full size icons

### ISSUE THREAD

**Issue by YuriGor** [Templarian/MaterialDesign#5971]
Hi all, it's not a request for specific icon, 
but idea to make existing icons more flexible and usable in variuos cases.

What I am dreaming about is to have like DIY set:

- base semantic icons of full size, like a 'person' or 'coffe'
- and collection of standart decorations like small plus, small cross, small lock, shield, pencil etc.

each decoration should have 4 or more variants, to be placed in each corner of standart icon 24x24 viewbox.

for example take a look at these icons:
![image](https://user-images.githubusercontent.com/6861317/117699263-ea725580-b1c4-11eb-8582-a52944ba167d.png)
It could be combination of only two base person icons + second decoration icon overlapping them(plus, cross, loupe, etc), and these decoration icons would be generic and reusable for other base icons.

For example we are missing "delete arrow" icon? Not a problem, let's take base arrow and overlap with one of 'delete' decorations using simple css (both icons with absolute position inside 'relative' container) or if used in some app - just render them on same coordinates and make sure alfa channel is enabled for decorations layer.
Using css, if needed, we can apply filter:drop-shadow of background(white) color, so decoration will be outlined and easily distinguishable from base ison. 

Depending on base icon geometry it's better to choose one of decoration variant (which corner to choose) to make it more readable and to not overlap key part of base icon.
If 4 vriations is not enough in some case - again it's not a problem to adjust decoration position by few pixels.

It could be separate repo with decorations only to not overload main, but it will be compatible and it will be easy to make fancy online constructor on the site.

And also we could create light version of MDI with base icons only and without pre-decorated variants.

**Comment by Templarian** [comment]
@YuriGor This has been discussed before and is currently is not a goal of the MDI set to provide overlays. Each icon is tailored as requests are made. Due to realistic workflows, developers and designers do not have the patience to adjust each overlay for every single icon (there are apps that use 200+ unique icons).

With modern dev tooling there is little overhead to having a tailored icons.

Read more: https://dev.materialdesignicons.com/guide/webfont-alternatives
