### ISSUE TITLE
thumbs-up-down-outline

### ISSUE THREAD

**Issue by anabeatrizzz** [Templarian/MaterialDesign#5972]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In a section of an app called "Rate our app".

## Examples
![](https://i.ibb.co/jwTQ1HR/thumbs-up-down-outline.jpg)
[Google Fonts](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Athumbs_up_down)

**Comment by anabeatrizzz** [comment]
@Templarian can you add `Google` label please?

**Comment by goyney** [comment]
[![thumbs-up-down-outline](https://materialdesignicons.com/icon/thumbs-up-down-outline)](https://materialdesignicons.com/icon/thumbs-up-down-outline)
