### ISSUE TITLE
email-seal aka sealed envelope

### ISSUE THREAD

**Issue by callegar** [Templarian/MaterialDesign#5973]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Envelope-type icons are often used to identify email addresses in sender or addressee fields in correspondence.

In some countries, and notably Italy, certified email services exist. For instance in Italy this is called PEC (posta elettronica certificata). They are important because the offer proof of sending and reception and they enjoy state blessing, taking the same value of registered mail in legal matters. 

For this reason it can be useful to have differentiated icons to mark "regular" and "certified" email addresses.

To the best of my knowledge there is no official icon for certified email, but the general trend is to use a stylized closed envelope with a seal on it. When the icon is big enough, the seal is made to have an "@" on it.

To get a general idea, you may want to look at  https://duckduckgo.com/?t=ffsb&q=posta+elettronica+certificata&iax=images&ia=images&iaf=type%3Aclipart

## Examples

Include any example images so we know what the icon should look like.

![image](https://user-images.githubusercontent.com/1041166/117781484-00bdf700-b241-11eb-994a-fcda4a78e40c.png)

![image](https://user-images.githubusercontent.com/1041166/117782321-cacd4280-b241-11eb-884d-95bf62f4642f.png)

![image](https://user-images.githubusercontent.com/1041166/117782576-0bc55700-b242-11eb-904a-b292d2012741.png)

![image](https://user-images.githubusercontent.com/1041166/117782671-226bae00-b242-11eb-901d-b9ab02466ae3.png)

**Comment by Templarian** [comment]
I like this idea, probably should call it `email-seal` or something. As the wax pointed star could be used.

Due to the small size `@` won't be possible.

**Comment by goyney** [comment]
Here's an idea with our `seal-variant`. Could be aliased `email-verified` and `email-certified`.

![image](https://user-images.githubusercontent.com/1015040/133837297-d56d7eb9-0ff7-4ffa-b76d-21ad8c2ca93a.png)![image](https://user-images.githubusercontent.com/1015040/133837175-ee542568-41bc-4584-8da4-5868cd409abf.png)
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7187741/Archive.zip)

**Comment by goyney** [comment]
[![email-seal](https://materialdesignicons.com/icon/email-seal)](https://materialdesignicons.com/icon/email-seal)[![email-seal-outline](https://materialdesignicons.com/icon/email-seal-outline)](https://materialdesignicons.com/icon/email-seal-outline)

**Comment by callegar** [comment]
Thanks for the nice addition!
