### ISSUE TITLE
Electric bus icon

### ISSUE THREAD

**Issue by antembmip** [Templarian/MaterialDesign#5974]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

It would be great to have an icon to represent "Electric bus". We need that to give an icon to electric bus data.
Thanks

## Examples

![image](https://user-images.githubusercontent.com/45227578/117823954-53fa6e80-b26e-11eb-9ad8-ac4cbcc245fa.png)

**Comment by goyney** [comment]
[![bus-electric](https://materialdesignicons.com/icon/bus-electric)](https://materialdesignicons.com/icon/bus-electric)
