### ISSUE TITLE
map-marker-account

### ISSUE THREAD

**Issue by varindergroove** [Templarian/MaterialDesign#5976]
https://fonts.google.com/icons?selected=Material+Icons:person_pin_circle

**Comment by goyney** [comment]
[![map-marker-account](https://materialdesignicons.com/icon/map-marker-account)](https://materialdesignicons.com/icon/map-marker-account)[![map-marker-account-outline](https://materialdesignicons.com/icon/map-marker-account-outline)](https://materialdesignicons.com/icon/map-marker-account-outline)
