### ISSUE TITLE
Surfing icon

### ISSUE THREAD

**Issue by igorkosta** [Templarian/MaterialDesign#5978]
Hi @Templarian,

thank you very much for great work.

Unfortunately I couldn't find some icons, specifically the surfing icon. I browsed through the .ttf file with BirdFont and couldn't find it.

I would love to contribute and add to the library but I'm not sure how to do it. I don't have a lot of experience with fonts.

Were certain icons left out intentionally?

Cheers,
Igor

**Comment by goyney** [comment]
[![surfing](https://materialdesignicons.com/icon/surfing)](https://materialdesignicons.com/icon/surfing)[![kitesurfing](https://materialdesignicons.com/icon/kitesurfing)](https://materialdesignicons.com/icon/kitesurfing)
