### ISSUE TITLE
Mosquitto (insect)

### ISSUE THREAD

**Issue by SeByDocKy** [Templarian/MaterialDesign#5979]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Home assistant panel

## Examples

https://thenounproject.com/term/mosquito/

**Comment by wiewior81** [comment]
Up! Need such icon, too!!

**Comment by goyney** [comment]
Duplicate of #4637.
