### ISSUE TITLE
Git Icon

### ISSUE THREAD

**Issue by FranciscoJavierPRamos** [Templarian/MaterialDesign#598]

**Comment by CoDEmanX** [comment]
Too fine detail IMO:
![git-orig](https://cloud.githubusercontent.com/assets/1309249/9211472/c7a4bd7c-4082-11e5-9c36-618f31ef62da.png) Original 20x20
![git](https://cloud.githubusercontent.com/assets/1309249/9211475/c9055f46-4082-11e5-90ff-f9d34cabaedf.png) 1.5px line width
![git2](https://cloud.githubusercontent.com/assets/1309249/9211481/cb595374-4082-11e5-921d-8ecc624f1978.png) 2px line width

**Comment by Templarian** [comment]
[![git](https://materialdesignicons.com/icon/git)](https://materialdesignicons.com/icon/git)
