### ISSUE TITLE
basket-check

### ISSUE THREAD

**Issue by 00ec454** [Templarian/MaterialDesign#5980]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon to show the my purchased item or my purchases

## Examples

https://thenounproject.com/term/purchase/3028930/

**Comment by goyney** [comment]
[![basket-check](https://materialdesignicons.com/icon/basket-check)](https://materialdesignicons.com/icon/basket-check)[![basket-check-outline](https://materialdesignicons.com/icon/basket-check-outline)](https://materialdesignicons.com/icon/basket-check-outline)
