### ISSUE TITLE
COG (Gear) with a PLAY, STOP and PAUSE icons

### ISSUE THREAD

**Issue by RafalChlopek** [Templarian/MaterialDesign#5981]
I have:

+ [YES] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
+ [YES] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
+ [YES] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

For jobs / pipelines / processes which are stopped / inactive / paused (and start / restart with PLAY icon)

## Examples

![image](https://user-images.githubusercontent.com/66465376/118490067-d4f9b000-b71d-11eb-967f-8c0a950d7b51.png)

**Comment by goyney** [comment]
[![cog-play](https://materialdesignicons.com/icon/cog-play)](https://materialdesignicons.com/icon/cog-play)[![cog-play-outline](https://materialdesignicons.com/icon/cog-play-outline)](https://materialdesignicons.com/icon/cog-play-outline)
[![cog-pause](https://materialdesignicons.com/icon/cog-pause)](https://materialdesignicons.com/icon/cog-pause)[![cog-pause-outline](https://materialdesignicons.com/icon/cog-pause-outline)](https://materialdesignicons.com/icon/cog-pause-outline)
[![cog-stop](https://materialdesignicons.com/icon/cog-stop)](https://materialdesignicons.com/icon/cog-stop)[![cog-stop-outline](https://materialdesignicons.com/icon/cog-stop-outline)](https://materialdesignicons.com/icon/cog-stop-outline)
