### ISSUE TITLE
New Tag: Justice

### ISSUE THREAD

**Issue by hecmec** [Templarian/MaterialDesign#5984]
You could add a tag: justice

**Comment by goyney** [comment]
We could add lots of tags. Why would you want us to add this one?

**Comment by hecmec** [comment]
> We could add lots of tags. Why would you want us to add this one?

We might want to have a collection that is useful for many different interest groups. That means it should be balanced and life orientated. I'm a tech guy and you are probably too. But life and the items we might wanna annotate or filter by icons is much bigger than sports and technology. I've just got the feeling that some pretty common topics concerning social life: justice, politics, solidarity, ecology, civil rights, collaboration etc are under-represented. (sorry for the en, i am de)

**Comment by Templarian** [comment]
@hecmec Can you give examples of what icons would go under such a tag. Usually we like to group by a category. So `legal`, `politics`, etc could work. `justice` is going to be too broad.

**Comment by goyney** [comment]
Closing because the `Needs More Info` tag was added quite a while ago without any further information provided. If you still have a need for this, please feel free to comment back and we can reopen to continue discussion. Thank you for your suggestion.
