### ISSUE TITLE
justice

### ISSUE THREAD

**Issue by hecmec** [Templarian/MaterialDesign#5985]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

Thanks for your great work.

## Usage

As visual tags to filter items like vocabulary, words, images ...

## Examples
maybe similar to this
https://icons8.com/icons/set/justice

**Comment by Templarian** [comment]
Could we just alias `scale-balance`? @hecmec would that work for `justice`?

**Comment by goyney** [comment]
Alias added.
