### ISSUE TITLE
Can You Build an App Like This With Your Font?

### ISSUE THREAD

**Issue by esdreesh** [Templarian/MaterialDesign#5986]
This app was abandoned since 2017 by the author. Can you update it or built yours. 👇👇👇👇

https://play.google.com/store/apps/details?id=id.delta.iconsexporter

**Comment by Templarian** [comment]
We're on and off working on the new site that will support mobile. See the pinned item.

We offer docs for third parties to build this kind of stuff, but it's outside of the scope that we can maintain.

https://dev.materialdesignicons.com/contribute/third-party-guide

**Comment by Templarian** [comment]
By the way had no idea that app existed... no one really tells us this kind of stuff. 😄
