### ISSUE TITLE
water-wave / tsunami

### ISSUE THREAD

**Issue by MrBartusek** [Templarian/MaterialDesign#5987]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm the author of [MeteoalarmCard](https://github.com/MrBartusek/MeteoalarmCard) and I was looking for an icon to indicate coastal event warning, I am for now using `waves` but it's not the best icon to indicate that.

## Examples

![image](https://user-images.githubusercontent.com/23432278/118989192-1f7b6680-b982-11eb-917d-54da0018877e.png)
![image](https://user-images.githubusercontent.com/23432278/118989288-3457fa00-b982-11eb-804f-9c9b520520d4.png)
![image](https://user-images.githubusercontent.com/23432278/118989308-38841780-b982-11eb-83fe-c31f9f6e01c2.png)
![image](https://user-images.githubusercontent.com/23432278/118989550-69644c80-b982-11eb-91e6-3edade50b0ba.png)

Maybe a variant with house or city?

![image](https://user-images.githubusercontent.com/23432278/118989469-5a7d9a00-b982-11eb-8a86-5746176740bc.png)
![image](https://user-images.githubusercontent.com/23432278/118989486-5d788a80-b982-11eb-8a61-6ea3c0e8eab5.png)

**Comment by Templarian** [comment]
We should probably have a...

- `home-flood` (home + wave)
- `tsunami`
- `tsunami-home`
- `tsunami-alert`

**Comment by goyney** [comment]
Tsunami was added recently:

[![tsunami](https://materialdesignicons.com/icon/tsunami)](https://materialdesignicons.com/icon/tsunami)

We already have `home-flood`:

[![home-flood](https://materialdesignicons.com/icon/home-flood)](https://materialdesignicons.com/icon/home-flood)
