### ISSUE TITLE
Spinner icon

### ISSUE THREAD

**Issue by micoll12268** [Templarian/MaterialDesign#599]
![spinner](https://cloud.githubusercontent.com/assets/13754841/9210175/bc6fcc24-4048-11e5-963e-a88c67995915.PNG)

**Comment by CoDEmanX** [comment]
![spinner](https://cloud.githubusercontent.com/assets/1309249/9210620/a3f2a042-407d-11e5-9d6b-26439388b5c4.png) https://www.dropbox.com/s/he5vqktzo2mrqfu/spinner.svg?dl=0

Not a fan though, you should use this instead:
http://www.getmdl.io/components/index.html#loading-section

**Comment by JamesCoyle** [comment]
#1869
