### ISSUE TITLE
cloud-alert-variant and cloud-check-variant

### ISSUE THREAD

**Issue by guenth39** [Templarian/MaterialDesign#5990]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I would love to have a cloud-alert and cloud-check variant where the alter/check is on the right bottom like at cloud-sync. At the moment the switch between sync, alert and check is a bit horrible because the icons are too different.

## Examples

![cloud-lock](https://user-images.githubusercontent.com/29251617/119123525-eef20600-ba2f-11eb-9a46-4fe107f9b542.png)
![cloud-search](https://user-images.githubusercontent.com/29251617/119123535-f0bbc980-ba2f-11eb-9a73-c141ac38ee7c.png)
![cloud-sync (1)](https://user-images.githubusercontent.com/29251617/119123545-f3b6ba00-ba2f-11eb-89fb-831513f7c99f.png)
![cloud-check](https://user-images.githubusercontent.com/29251617/119123553-f4e7e700-ba2f-11eb-8173-c596e7bd1fc1.png)
![image](https://user-images.githubusercontent.com/29251617/119123636-0a5d1100-ba30-11eb-9694-1cf522ea64f6.png)

**Comment by guenth39** [comment]
![image](https://user-images.githubusercontent.com/29251617/120215632-3ea5ae00-c236-11eb-89dd-480e9b972ae5.png)

**Comment by goyney** [comment]
This is actually one case where i think we should *not* use our cutout and move the modifiers inside the icon. Therefore, I believe instead we should update `sync` and `lock` to be contained. `search` is fine how it is.

**Comment by goyney** [comment]
We're not going to make these changes at this time.
