### ISSUE TITLE
publish-off / unpublish

### ISSUE THREAD

**Issue by PurpleProgrammer** [Templarian/MaterialDesign#5993]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In case someone wants to unpublish something or indicate that something is not currently published.

## Examples

I have 2 ideas in mind:
1. A simple publish-off icon, which is the publish icon with line that strikes it off.
2. An unpublished icon, which is the publish icon with the arrow flipped, pointing away from the "published area".

I am not sure whether the 2nd idea harmonizes with the Material Design ideal, though. In case it does, it would be a very helpful icon, eg. for when someone wants to show when a post was taken down or unpublished.

Here are the images:

1. publish-off
<img width="256" alt="publish-off" src="https://user-images.githubusercontent.com/24755259/119275740-5d48eb00-bc1f-11eb-8496-176abc8bf66a.png">

2. unpublish
<img width="256" alt="unpublish" src="https://user-images.githubusercontent.com/24755259/119275750-6c2f9d80-bc1f-11eb-9e60-f804731e2214.png">

Thank you for your time!

I apologize for putting 2 icon ideas under a single Github issue, but I am not sure whether the 2nd one is going to be accepted as is.

**Comment by goyney** [comment]
[![publish-off](https://materialdesignicons.com/icon/publish-off)](https://materialdesignicons.com/icon/publish-off)

If you need it pointing down, I'd recommend just rotating the icon 180 degrees.

**Comment by PurpleProgrammer** [comment]
@goyney thanks man!!
