### ISSUE TITLE
Youtube Icon Is Not A Legal Use Of Youtube's Trademark

### ISSUE THREAD

**Issue by hrichiksite** [Templarian/MaterialDesign#5994]
### The Youtube icon at https://materialdesignicons.com/icon/youtube is a violation of YouTube's Trademark.

I recently contacted Youtube about using their logo in our own product, and sent them the link (https://iconify.design/icon-sets/mdi/youtube.html same as above but from a different repo as they said me to open an issue here - https://github.com/iconify/iconify/issues/70), they responded 

> The link you provided has nothing to do with us, and is not a legal use of our trademark. Our official branding is available on YouTube.com/brand and all use requests should be submitted via the form on the site.

Maintainers are requested to take the required action.

**Comment by Templarian** [comment]
The logo provided is from the official source. Anyone using any brand icon must ensure they are following the brand's guidelines.

Not a bug, working as designed.
