### ISSUE TITLE
smart-card-off-outline

### ISSUE THREAD

**Issue by AshAsh1** [Templarian/MaterialDesign#5996]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

Would like to know if you can create a "Smart-Card-Off-Outline" logo so that we can show at a glance that no smart card is attached to a user's account.

Here is the regular Smart Card Outline logo and we would like to have one that is this with a diagonal line through it. 
import { mdiSmartCardOutline } from '@mdi/js';

![image](https://user-images.githubusercontent.com/84739612/119394488-38488c80-bca0-11eb-9776-bfdc044c07ef.png)

Thank you.

**Comment by goyney** [comment]
[![smart-card-off](https://materialdesignicons.com/icon/smart-card-off)](https://materialdesignicons.com/icon/smart-card-off)[![smart-card-off-outline](https://materialdesignicons.com/icon/smart-card-off-outline)](https://materialdesignicons.com/icon/smart-card-off-outline)
