### ISSUE TITLE
lifebuoy-outline

### ISSUE THREAD

**Issue by pcmb07500** [Templarian/MaterialDesign#5997]
Hi, 

Would it be possible to get a lifebuoy outline pictogram?

Hereunder is the current one findable through the website :) 
![image](https://user-images.githubusercontent.com/84768696/119460580-1eaa5200-bd3f-11eb-8ee1-b741c634b02d.png)

Thanks you for helping!

Regards.

**Comment by goyney** [comment]
This is one of those icons where the is no solid and outline version, it just is what it is.

**Comment by pcmb07500** [comment]
Hi Goyney, 
Then this is not possible to build an outline version?
I mean by inverting grey and transparent area around the lifebuoy OR other is to empty the grey and leaving the outlines/contours?
Thanks for helping :)
