### ISSUE TITLE
rfid

### ISSUE THREAD

**Issue by pcmb07500** [Templarian/MaterialDesign#5998]
Hi Everybody, 

I'm not able to find an RFID icon on the website. Is there already existing?

If not, I guess, it would be nice to get one like the illustration below, don't you think?
1 classic pictogram + 1 outlined pictogram would be really nice!

![image](https://user-images.githubusercontent.com/84768696/119461026-98424000-bd3f-11eb-8214-10145f4770bc.png)

Thanks in advance for helping! :)

Regards.

**Comment by Templarian** [comment]
We don't include brand icons, so you'll want to use one of the various `nfc` icons or smart card reader icons.
