### ISSUE TITLE
Yelp logo icon

### ISSUE THREAD

**Issue by shihpeng** [Templarian/MaterialDesign#600]
From Font-Awesome:
https://camo.githubusercontent.com/08268132088d62e81158cf9768df4766d9c685b9/68747470733a2f2f692e636c6f756475702e636f6d2f4565326331536a7643392e706e67

**Comment by CoDEmanX** [comment]
![yelp3](https://cloud.githubusercontent.com/assets/1309249/9223572/a9e88a60-40fb-11e5-93bf-7d328857c4b3.png) https://www.dropbox.com/s/netbj8a15i231wv/yelp3.svg?dl=0

**Comment by Templarian** [comment]
[![yelp](https://materialdesignicons.com/icon/yelp)](https://materialdesignicons.com/icon/yelp)
