### ISSUE TITLE
water the plants

### ISSUE THREAD

**Issue by Mowgly1977** [Templarian/MaterialDesign#6001]
using the watering can it would be nice to have an icon that displays both the watering can and the plants to be used on an automation that automatically irrigates the plants.

![watering-can-outline](https://user-images.githubusercontent.com/78051280/119881061-27607b00-bf2d-11eb-9a4e-66d42a2b7535.png)
![flower](https://user-images.githubusercontent.com/78051280/119881121-39421e00-bf2d-11eb-866a-f01d15a30f1f.png)

**Comment by guenth39** [comment]
What do you think about something like this? For Can and Flower is probably not enough space.
![image](https://user-images.githubusercontent.com/29251617/120364308-63208980-c30d-11eb-9314-6720f341fa85.png)
[flower-watering.svg.zip](https://github.com/Templarian/MaterialDesign/files/6578277/flower-watering.svg.zip)

**Comment by guenth39** [comment]
Here's another try. But to be honest it is very hard to get all the components on it. Maybe someone with more experience would have to try again. But I think the first one is nicer anyway.

![image](https://user-images.githubusercontent.com/29251617/120368011-d62bff00-c311-11eb-8524-eeefef0411a0.png)
[flower-watering-2.svg.zip](https://github.com/Templarian/MaterialDesign/files/6578406/flower-watering-2.svg.zip)

**Comment by Mowgly1977** [comment]
very beautifull!  I prefer the second version.  makes the idea more.  Fantastic!



Inviato da Libero Mail per iOS


martedì 1 giugno 2021, 19:48 +0200 da ***@***.***  ***@***.***>:

**Comment by goyney** [comment]
I believe `watering-can` is appropriate for this use case.

[![watering-can](https://materialdesignicons.com/icon/watering-can)](https://materialdesignicons.com/icon/watering-can)

The first idea above makes the water drops too small to be perceived well at native resolution and might even be confused for pollen. The second idea breaks Material size and artboard rules.
