### ISSUE TITLE
perm_data_setting icon suggestion

### ISSUE THREAD

**Issue by sergiocormio** [Templarian/MaterialDesign#6002]
Just suggest perm_data_setting icon available in materialicons. It's like a triangle with a little cog in right bottom corner.
[Link to an example](https://api.flutter.dev/flutter/material/Icons/perm_data_setting-constant.html)

Thanks

**Comment by goyney** [comment]
[![network-strength-4-cog](https://materialdesignicons.com/icon/network-strength-4-cog)](https://materialdesignicons.com/icon/network-strength-4-cog)
