### ISSUE TITLE
message-badge(-outline)

### ISSUE THREAD

**Issue by esaujc** [Templarian/MaterialDesign#6004]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I am using the icon "message" to check a messages sent/recieved, but when a new message arrived adn I did not read it, I need the "message-unread" version, with the spot marked in top-right side.

## Examples

We can find this version created at:

https://fonts.google.com/icons?selected=Material+Icons:notifications&icon.query=message
Icon Name: "mark_chat_unread"

**Comment by goyney** [comment]
[![message-badge](https://materialdesignicons.com/icon/message-badge)](https://materialdesignicons.com/icon/message-badge)[![message-badge-outline](https://materialdesignicons.com/icon/message-badge-outline)](https://materialdesignicons.com/icon/message-badge-outline)

**Comment by esaujc** [comment]
Amazing!!!
Thank you very much indeed!!
