### ISSUE TITLE
dot-circle icon for a "broken circle"

### ISSUE THREAD

**Issue by skendrot** [Templarian/MaterialDesign#6007]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

A dot-circle icon can be used to indicate that something is happening. In the context of a messenger app it would indicate that a message is being sent

## Examples

The Sending icon in Signal
https://support.signal.org/hc/en-us/articles/360007320751-How-do-I-know-if-my-message-was-delivered-or-read-

**Comment by goyney** [comment]
[![selection-ellipse](https://materialdesignicons.com/icon/selection-ellipse)](https://materialdesignicons.com/icon/selection-ellipse)

**Comment by skendrot** [comment]
I was thinking something more like this
![image](https://user-images.githubusercontent.com/1594689/120528650-ecc96900-c398-11eb-853c-1e79390c6dbd.png)

**Comment by skendrot** [comment]
The above fits with the dot-square and dot-triangle icons

**Comment by Templarian** [comment]
It would need to match the smaller standard circle size, but would work okay with 2dp sized circles

**Comment by goyney** [comment]
Eh, both the proposal and the idea of using 2dp circles doesn't match our existing `dots-*` icons. I've added one that does:

[![dots-circle](https://materialdesignicons.com/icon/dots-circle)](https://materialdesignicons.com/icon/dots-circle)

That should satisfy this request and keeps us in the same style as the other icons.
