### ISSUE TITLE
excel icon

### ISSUE THREAD

**Issue by davidsalomon14** [Templarian/MaterialDesign#601]
I WILL HAPPY WITH EXCEL ICON.
I NEED ICON TO IMPORT DATA TO EXCEL FILE.

THANKS
DAVID

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/file-excel-box
https://materialdesignicons.com/icon/file-excel
Duplicate of #368

PS: Captain Caps and his SHIFT crew is not welcome here.

**Comment by Templarian** [comment]
Ha. Yea what @CoDEmanX said.

Due to the size constraints app style icons are not included. So the file variants are the best choice.
