### ISSUE TITLE
patient left eye

### ISSUE THREAD

**Issue by athikamesh** [Templarian/MaterialDesign#6010]
![imgos](https://user-images.githubusercontent.com/33952931/120473795-084a6900-c3c5-11eb-8257-94d360fc9b7c.png)

I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
We already have several eye icons.
