### ISSUE TITLE
Request: credit-card-lock-(outline)

### ISSUE THREAD

**Issue by PeterShaggyNoble** [Templarian/MaterialDesign#6011]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist. _(Although, I could've sworn it did)_
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
**Generally:** To represent secure payments. Although it's somewhat redundant as it should go without saying that _all_ payments are secure.
**Specifically:** I have a site where the client wants to show off a few features of their online store and my designer decided to run with credit card icons for them all (e.g., `credit-card-sync-outline` for their refund policy, `wallet-giftcard` for their gift vouchers). The first one on the list is "secure payments" for which I'm currently using `shield-lock-outline` but it doesn't really sit well with the others.

## Examples
My own attempts at them, forgetting the lock modifier uses a stroke cut-out, not a circular one:

![](https://user-images.githubusercontent.com/15157491/120519991-303ccb00-c3cb-11eb-8de1-d7e15b17583d.png) ![](https://user-images.githubusercontent.com/15157491/120520017-38950600-c3cb-11eb-986e-b6e173cc2449.png)

**Comment by goyney** [comment]
[![credit-card-lock](https://materialdesignicons.com/icon/credit-card-lock)](https://materialdesignicons.com/icon/credit-card-lock)[![credit-card-lock-outline](https://materialdesignicons.com/icon/credit-card-lock-outline)](https://materialdesignicons.com/icon/credit-card-lock-outline)
