### ISSUE TITLE
Save icon 3.5″ diskette style (instead of existing floppy 5.25")

### ISSUE THREAD

**Issue by bascurtiz** [Templarian/MaterialDesign#6012]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/34075088/120541311-02b34a00-c3ea-11eb-9199-b35d4de8f671.png)
[save-disk.zip](https://github.com/Templarian/MaterialDesign/files/6587007/save-disk.zip)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by goyney** [comment]
That is Google's icon, so we won't update it. However `floppy` already exists.

[![floppy](https://materialdesignicons.com/icon/floppy)](https://materialdesignicons.com/icon/floppy)

**Comment by bascurtiz** [comment]
I just made this icon myself. So i'ts not Google's, it's mine.
And the title already shows it's a variant for the existing floppy.
