### ISSUE TITLE
A Filter icon with a check mark

### ISSUE THREAD

**Issue by jdinnen** [Templarian/MaterialDesign#6013]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

We have recently wanted to use the Filter icon but we actually want to indicate to our customers that the filter is applied with a check beside it, rather than an X. 

I have the SVG for the font which I intend to build independently but not sure if you would consider adding it to save me having to make a custom version of the font in future. It will not allow me to attach the SVG to this but I have included a PNG of the icon.

## Examples

![ic_filteredcheck_m](https://user-images.githubusercontent.com/16652997/120550185-2068bb00-c3ba-11eb-8cd3-bd880e368459.png)

**Comment by goyney** [comment]
[![filter-check](https://materialdesignicons.com/icon/filter-check)](https://materialdesignicons.com/icon/filter-check)[![filter-check-outline](https://materialdesignicons.com/icon/filter-check-outline)](https://materialdesignicons.com/icon/filter-check-outline)
