### ISSUE TITLE
receipt-text-outline

### ISSUE THREAD

**Issue by anabeatrizzz** [Templarian/MaterialDesign#6016]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Examples

![](https://i.ibb.co/hmLXYF4/receipt-outline-black.png)
![](https://i.ibb.co/hHCBdjj/receipt-outline-white.png)
[Google Fonts](https://fonts.google.com/icons?icon.query=receipt)

**Comment by goyney** [comment]
Keep in mind the changes happening in https://github.com/Templarian/MaterialDesign/issues/6016, which won't happen until v7.

**Comment by Templarian** [comment]
Adding the v7 milestone.
