### ISSUE TITLE
"content-save" with checkmark

### ISSUE THREAD

**Issue by FabianWilms** [Templarian/MaterialDesign#6019]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Something was/is save successfully.

## Examples

The already available `content-save`-Icon but with a checkmark in the bottom right corner.

Like https://materialdesignicons.com/icon/database-check

**Comment by goyney** [comment]
[![content-save-check](https://materialdesignicons.com/icon/content-save-check)](https://materialdesignicons.com/icon/content-save-check)[![content-save-check-outline](https://materialdesignicons.com/icon/content-save-check-outline)](https://materialdesignicons.com/icon/content-save-check-outline)
