### ISSUE TITLE
Groovy programming lang icon

### ISSUE THREAD

**Issue by serpro69** [Templarian/MaterialDesign#6022]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

There are already icons for some JVM-targeted programming languages like Kotlin and Java, would be useful to have Groovy as well.

## Examples

https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Groovy-logo.svg/1200px-Groovy-logo.svg.png

**Comment by Templarian** [comment]
https://simpleicons.org/?q=groovy

At this time this logo is too detailed for inclusion. At the 1:1 24x24 size it would be unreadable.

**Comment by serpro69** [comment]
Hi @Templarian ,
Thanks for the response.

How about this one as an example: https://findicons.com/files/icons/2773/pictonic_free/512/pl_groovy_02.png ?

**Comment by Templarian** [comment]
@serpro69 If you can find me a link for their brand guidelines we can consider something closer to that. We generally don't like to make custom icons or use third party for things like this.
