### ISSUE TITLE
line-scan

### ISSUE THREAD

**Issue by TheSnowfield** [Templarian/MaterialDesign#6029]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/17957399/122499733-01a62d80-d024-11eb-9679-f8c29ee3fe17.png)

## Zip Download

[line-scan.zip](https://github.com/Templarian/MaterialDesign/files/6674315/line-scan.zip)

**Comment by goyney** [comment]
[![line-scan](https://materialdesignicons.com/icon/line-scan)](https://materialdesignicons.com/icon/line-scan)
