### ISSUE TITLE
Feature: assimilate search phrases into icon tags

### ISSUE THREAD

**Issue by justinlawrence** [Templarian/MaterialDesign#603]
If a user searches for "activity" and there are no results, it would be great to add these searches to a log somehow and then process through the most searched for phrases and either create icons or connect them to existing icons.

When there are results, it might be cool to add add a "Didn't find what you were looking for? Click here" at the bottom, in case the user didn't find what they were looking for. This would allow them to trigger the assimilation process described in paragraph 1.

**Comment by Templarian** [comment]
That definitely already exists. Let me know what you searched for and what you expected to see. All searches are currently tracked and the top 300 most common are aliased to various related icons.

It's a manual process, but I just need to enter in aliases for each icon to match the keyword.

**Comment by CoDEmanX** [comment]
Could these search stats be made public somehow, so contributors see what people want?

Users could also be enabled to perform social tagging, but I worry moderation is required.

**Comment by Templarian** [comment]
Definitely: http://pastebin.com/CKVsN43R

Here are all the search results and values for the last month. 105k searches.

Once I get the contributor portal back up and running I should have the functionality for contributors to alias and tag icons (even the ones they don't have write access to).

**Comment by REJack** [comment]
I've removed the existing icons from the list http://pastebin.com/Lr5PiHCy

**Comment by CoDEmanX** [comment]
Thank you @Templarian and @REJack! This is quite interesting.

For example, **back** is often searched, but `ic_backspace` is not yet added to MDI.

Or that the search phrase **edit** is very common, but does not match https://materialdesignicons.com/icon/pencil - although this is the preferred icon for editing content (used throughout a lot of Google apps).

**Face** does not return any smiley icons, although they are faces :disappointed: 

Looking forward to new contributor portal!

**Comment by JamesCoyle** [comment]
Maybe transfer this over to MDI site repository?

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by PeterShaggyNoble** [comment]
See also https://github.com/Templarian/MaterialDesign-Site/issues/41
