### ISSUE TITLE
location-arrow

### ISSUE THREAD

**Issue by valentingavran** [Templarian/MaterialDesign#6035]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

iOS users expect a different location icon than Android users. iOS uses a `location-arrow` icon by default and not the `crosshair-gps` icon (like Android).

## Examples

Font awesome has implemented the icon and it looks like this:
https://fontawesome.com/v5.15/icons/location-arrow

You could also implement some other variations here like an outlined icon or one in a circle.

**Comment by goyney** [comment]
So, we already have `navigation(-outline)`, but Google does have the angled version as well. Typically, we'd just say perform the translation yourself, but this use case seems common enough for us to just include them as well.

[![navigation](https://materialdesignicons.com/icon/navigation)](https://materialdesignicons.com/icon/navigation)[![navigation-outline](https://materialdesignicons.com/icon/navigation-outline)](https://materialdesignicons.com/icon/navigation-outline)
[![navigation-variant](https://materialdesignicons.com/icon/navigation-variant)](https://materialdesignicons.com/icon/navigation-variant)[![navigation-variant-outline](https://materialdesignicons.com/icon/navigation-variant-outline)](https://materialdesignicons.com/icon/navigation-variant-outline)
