### ISSUE TITLE
Cheatsheet not working

### ISSUE THREAD

**Issue by VijeshDatt** [Templarian/MaterialDesign#6036]
Hi there, 

Seems the cheatsheet is not working as intended, the page gets redirected to cdn.jsdelivr.net .

Hoping this can be fixed soon as I rely on the cheat sheet for most of my icon searches.

**Comment by brendengreenwood** [comment]
Seconding this. Most designers are relying on copying pasting values from the cheatsheet into Sketch and Figma. Need this one fixed ASAP.

**Comment by MartinKolarik** [comment]
Looks like the cheatsheet is now at https://pictogrammers.github.io/@mdi/font/5.8.55/ and the link just needs to be changed on the website (based on #5737).

**Comment by Templarian** [comment]
We moved the previews a while back to GitHub pages. jsDelivr now handles everything for us with regards to the CDN for assets. One feature they do not offer is rendering html files, but minor issue considering the 620 million assets a month they process just for `@mdi/font`. 🙃 

They finalized their move to pull directly from NPM just last week, so our built in redirects no longer work.

I'll leave this issue open, but @MartinKolarik is correct that is where we host previews from now on.

/cc @VijeshDatt @brendengreenwood

**Comment by VijeshDatt** [comment]
Thank you so much. Decisions are being made on the daily for improvements so no one can be blamed for what's changing, even I'm developing web applications that are changing on the daily because of client requests or management requests. I'm just thankful that this icon font gallery exists because the default Material Icons (Google) doesn't have half the icons I use from here.

**Comment by brendengreenwood** [comment]
Thanks for the update!

**Comment by MartinKolarik** [comment]
@Templarian note that the old link is still at https://materialdesignicons.com/

**Comment by goyney** [comment]
This has been fixed.
