### ISSUE TITLE
boomicon

### ISSUE THREAD

**Issue by guykevin** [Templarian/MaterialDesign#6039]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by guykevin** [comment]
![back-arrow_icon-icons com_72866](https://user-images.githubusercontent.com/56883887/123831656-761e7d80-d8fc-11eb-830e-c30c66eb7584.png)
![user-account-box_icon-icons com_72491](https://user-images.githubusercontent.com/56883887/123831663-774faa80-d8fc-11eb-8129-bd470eb51df2.png)

**Comment by goyney** [comment]
What is your use case here, what are you trying to get added? It's not clear.
