### ISSUE TITLE
trash icon

### ISSUE THREAD

**Issue by homina** [Templarian/MaterialDesign#604]

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/delete-variant ?

**Comment by Templarian** [comment]
Going to close this issue out as a duplicate.

**Comment by homina** [comment]
thank you for the reply,
yeah, but it doesn't suit with email trash icon,

**Comment by Templarian** [comment]
Do you have an example?

**Comment by homina** [comment]
https://ssl.gstatic.com/bt/C3341AA7A1A076756462EE2E5CD71C11/1x/ic_trash_g60_24dp_r2.png

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/delete

The stock delete icon is present in the pack.

**Comment by Templarian** [comment]
A alias for `trash` has been added to `delete`. `trash-variant` has been added to `delete-variant`.

**Comment by homina** [comment]
ah, thank you
