### ISSUE TITLE
Sliders icon for control panel

### ISSUE THREAD

**Issue by Awsmolak** [Templarian/MaterialDesign#6040]
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
This would typically be a button used to open up a control panel or an options display.
## Examples

![sliders1](https://user-images.githubusercontent.com/15197249/123825224-f8d31880-d8bb-11eb-9dd2-873dce164c4a.png)
![sliders2](https://user-images.githubusercontent.com/15197249/123825229-fa044580-d8bb-11eb-936d-84fc9d15f952.png)

**Comment by goyney** [comment]
[![tune](https://materialdesignicons.com/icon/tune)](https://materialdesignicons.com/icon/tune)[![tune-vertical](https://materialdesignicons.com/icon/tune-vertical)](https://materialdesignicons.com/icon/tune-vertical)
[![tune-variant](https://materialdesignicons.com/icon/tune-variant)](https://materialdesignicons.com/icon/tune-variant)[![tune-vertical-variant](https://materialdesignicons.com/icon/tune-vertical-variant)](https://materialdesignicons.com/icon/tune-vertical-variant)
