### ISSUE TITLE
Icon Request: Tally or counter-variant

### ISSUE THREAD

**Issue by SimonAM** [Templarian/MaterialDesign#6041]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
A tally can be used when counting things. 
There already exist an icon with a similar use case:  [the counter icon](https://materialdesignicons.com/icon/counter). 
However, a tally is more intuitive in my opinion. While tallys' are used in kindergarten math,  most people have never seen a [tally-counter](https://en.wikipedia.org/wiki/Tally_counter) which the [counter icon ](https://materialdesignicons.com/icon/counter) is a metafor for.

Also, i think the icon should be called tally rather than counter-variant. Tally is the word for a tally. 

## Examples
[These are tally icons from the nounproject](https://thenounproject.com/term/tally-marks/1048954/)

**Comment by mxve** [comment]
This would a very useful and very epic addition!

**Comment by goyney** [comment]
These are the most common tally marks:
![image](https://user-images.githubusercontent.com/1015040/159616188-3d427681-16b7-4813-8fc8-4e0b83d170ad.png)![image](https://user-images.githubusercontent.com/1015040/159616219-5fa59651-9b3e-4e6d-b959-47e3f7ec052b.png)
![image](https://user-images.githubusercontent.com/1015040/159616236-e82e1dd2-d896-4b84-9614-a2bec51580cd.png)![image](https://user-images.githubusercontent.com/1015040/159616257-8386e8bb-28fe-40c3-9ac9-2c875d146fec.png)
![image](https://user-images.githubusercontent.com/1015040/159616306-6caf931e-0174-4e96-b232-ba2ccc3af0af.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/8329408/Archive.zip)

---

However, there are different tally marks in other cultures. I don't know if we want to add these as well.

Chinese tally marks follow this pattern:
![image](https://user-images.githubusercontent.com/1015040/159616411-332cc9ba-ceed-49b0-8d9f-820c3b42c175.png)

French tally marks follow this pattern:
![image](https://user-images.githubusercontent.com/1015040/159616435-43472807-5f69-44d4-ad79-d5cd5e4d6652.png)

**Comment by Templarian** [comment]
This is one situation I think it would be fine to add even with the language conflicts (we can even add the others if they eventually get requested).

**Comment by goyney** [comment]
[![tally-mark-1](https://materialdesignicons.com/icon/tally-mark-1)](https://materialdesignicons.com/icon/tally-mark-1)[![tally-mark-2](https://materialdesignicons.com/icon/tally-mark-2)](https://materialdesignicons.com/icon/tally-mark-2)
[![tally-mark-3](https://materialdesignicons.com/icon/tally-mark-3)](https://materialdesignicons.com/icon/tally-mark-3)[![tally-mark-4](https://materialdesignicons.com/icon/tally-mark-4)](https://materialdesignicons.com/icon/tally-mark-4)
[![tally-mark-5](https://materialdesignicons.com/icon/tally-mark-5)](https://materialdesignicons.com/icon/tally-mark-5)
