### ISSUE TITLE
mon icone

### ISSUE THREAD

**Issue by bertay2010** [Templarian/MaterialDesign#6042]
I have:

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
![beneficiaires_1](https://user-images.githubusercontent.com/86712868/123930368-f9d57a00-d98f-11eb-957b-c678e237ec9b.png)

**Comment by Simran-B** [comment]
Please fill out the issue template. It's not clear what this is supposed to represent.
