### ISSUE TITLE
winner

### ISSUE THREAD

**Issue by guykevin** [Templarian/MaterialDesign#6043]
I have:

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
![winner](https://user-images.githubusercontent.com/56883887/123935514-34d5ae80-d98c-11eb-897d-849d6343d934.png)
![back-arrow_icon-icons com_72866](https://user-images.githubusercontent.com/56883887/123935572-43bc6100-d98c-11eb-8d0e-a8c73be6c1a6.png)
![user-account-box_icon-icons com_72491](https://user-images.githubusercontent.com/56883887/123935579-4454f780-d98c-11eb-850a-eaec2fad1c56.png)
![téléchargement (1)](https://user-images.githubusercontent.com/56883887/123935800-77978680-d98c-11eb-870f-febcd7c9ceb7.png)
![téléchargement](https://user-images.githubusercontent.com/56883887/123935807-78c8b380-d98c-11eb-81f3-723b87a81f80.png)

**Comment by Simran-B** [comment]
Please fill out the issue template. What do the examples you shared have to do with "winner" except for the first one?

There are already several icons that could be used:

[![podium](https://materialdesignicons.com/icon/podium)](https://materialdesignicons.com/icon/podium) [![podium-bronze](https://materialdesignicons.com/icon/podium-bronze)](https://materialdesignicons.com/icon/podium-bronze) [![podium-silver](https://materialdesignicons.com/icon/podium-silver)](https://materialdesignicons.com/icon/podium-silver) [![podium-gold](https://materialdesignicons.com/icon/podium-gold)](https://materialdesignicons.com/icon/podium-gold)
[![trophy](https://materialdesignicons.com/icon/trophy)](https://materialdesignicons.com/icon/trophy) [![trophy-award](https://materialdesignicons.com/icon/trophy-award)](https://materialdesignicons.com/icon/trophy-award) [![trophy-variant](https://materialdesignicons.com/icon/trophy-variant)](https://materialdesignicons.com/icon/trophy-variant) [![trophy-outline](https://materialdesignicons.com/icon/trophy-outline)](https://materialdesignicons.com/icon/trophy-outline) [![medal](https://materialdesignicons.com/icon/medal)](https://materialdesignicons.com/icon/medal) [![crown](https://materialdesignicons.com/icon/crown)](https://materialdesignicons.com/icon/crown) [![crown-outline](https://materialdesignicons.com/icon/crown-outline)](https://materialdesignicons.com/icon/crown-outline)
