### ISSUE TITLE
Icons not available in v5.9.55

### ISSUE THREAD

**Issue by David-Ho** [Templarian/MaterialDesign#6045]
I can't seem to find these icons in v5.9.55, but I can search them in https://materialdesignicons.com/

- archive-eye-outline
- archive-check-outline
- archive-remove-outline
- archive-cancel-outline
- account-eye-outline

Are they not available in this version?  Do I have to submit icon request for them?   Any assistance is much appreciated.

Thanks
David

**Comment by goyney** [comment]
These have all been added and are staged for release in v6. Major version releases have lots of implications and breaking changes, so they take longer for us to release.

When we add new icons, they are always immediately available on materialdesignicons.com, but take until the next version release to be introduced to the various packages we release. You can download those icons directly and use them in that way for now and then move to the official packages once we do the release.
