### ISSUE TITLE
Icon Request: Google Material Design - Fit Screen

### ISSUE THREAD

**Issue by brettins** [Templarian/MaterialDesign#6046]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In a button to fit an image on the screen. 

## Examples

https://fonts.google.com/icons?selected=Material+Icons&icon.query=fit_screen

**Comment by goyney** [comment]
[![fit-to-screen](https://materialdesignicons.com/icon/fit-to-screen)](https://materialdesignicons.com/icon/fit-to-screen)[![fit-to-screen-outline](https://materialdesignicons.com/icon/fit-to-screen-outline)](https://materialdesignicons.com/icon/fit-to-screen-outline)
