### ISSUE TITLE
flag-off and flag-off-outline

### ISSUE THREAD

**Issue by hgiesel** [Templarian/MaterialDesign#6047]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In our application, we have tags and flags to categorize items. Currently we use `tag-off-outline` as "no tags assigned". It would be nice to have the same for flags.

## Examples

They would be like the current `flag` or `flag-outline`, but with a vertical strike, just like `tag-off`, or `tag-off-outline`.

**Comment by iSteeb** [comment]
@Templarian @hgiesel I gave this one a go.  I haven't posted designs before so apologies if I've misunderstood the process.
[flag-offs.zip](https://github.com/Templarian/MaterialDesign/files/6834328/flag-offs.zip)

**Comment by goyney** [comment]
[![flag-off](https://materialdesignicons.com/icon/flag-off)](https://materialdesignicons.com/icon/flag-off)[![flag-off-outline](https://materialdesignicons.com/icon/flag-off-outline)](https://materialdesignicons.com/icon/flag-off-outline)
