### ISSUE TITLE
ic_benefit_black

### ISSUE THREAD

**Issue by guykevin** [Templarian/MaterialDesign#6049]
I have:

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
![ic_benefit_black](https://user-images.githubusercontent.com/56883887/124118243-0548a400-da69-11eb-9d75-ab884c82d998.png)

**Comment by goyney** [comment]
What is this icon supposed to represent? In its current form, it's way too complex to be done in Material style at native resolution. We have several of the elements already within it though.

[![sack](https://materialdesignicons.com/icon/sack)](https://materialdesignicons.com/icon/sack)
[![database](https://materialdesignicons.com/icon/database)](https://materialdesignicons.com/icon/database)
[![cash-multiple](https://materialdesignicons.com/icon/cash-multiple)](https://materialdesignicons.com/icon/cash-multiple)
