### ISSUE TITLE
compte_bancaire_3

### ISSUE THREAD

**Issue by guykevin** [Templarian/MaterialDesign#6053]
I have:

- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Searched open issues to make sure there isn't a request for this icon.
- [ ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.
![compte_bancaire_3](https://user-images.githubusercontent.com/56883887/124561570-f598d900-de35-11eb-8790-48c92ef6d6a4.jpg)

**Comment by goyney** [comment]
Hello @guykevin, you've been opening lots of "Contribution" issues without any contributions on them. Please use "Request an Icon" if you're looking to request an icon to be added.

That being said, you've also not included much information in your requests. Please fill out the issue template so we can better address your requests.

I'm not sure what "compte_bancaire_3" means, but in the example image you provided... we already have it.

[![piggy-bank](https://materialdesignicons.com/icon/piggy-bank)](https://materialdesignicons.com/icon/piggy-bank)[![piggy-bank-outline](https://materialdesignicons.com/icon/piggy-bank-outline)](https://materialdesignicons.com/icon/piggy-bank-outline)
