### ISSUE TITLE
Dirac

### ISSUE THREAD

**Issue by udhaya68-ai** [Templarian/MaterialDesign#6054]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
The template issue is not optional; please fill it out.

**Comment by udhaya68-ai** [comment]
ic_dirac

**Comment by udhaya68-ai** [comment]
![Uploading dirac-logo-2020.png…]()

**Comment by udhaya68-ai** [comment]
![dirac-logo-2020](https://user-images.githubusercontent.com/62876759/124621324-ce72f380-de97-11eb-9af3-846f45d2896a.png)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
