### ISSUE TITLE
crossed-out-tilde

### ISSUE THREAD

**Issue by Hiroio** [Templarian/MaterialDesign#6059]
it`s like notLike func on backend

**Comment by Hiroio** [comment]
![image](https://user-images.githubusercontent.com/76852167/124924038-b28c6080-e003-11eb-850b-bbc1c9c97cec.png)
but crossed out

**Comment by goyney** [comment]
[![tilde-off](https://materialdesignicons.com/icon/tilde-off)](https://materialdesignicons.com/icon/tilde-off)
