### ISSUE TITLE
Fallback icon for missing/incorrect glyph classes

### ISSUE THREAD

**Issue by md5** [Templarian/MaterialDesign#6060]
When `.mdi` is specified with an invalid or missing glyph class, the result is that nothing is shown. This can be particularly confusing in the case of an upgrade where an existing icon was renamed (we ran into it with `.mdi-settings` being renamed to `.mdi-cog`). Given how the CSS is structured, with `core` coming before `icons` in the cascade, it looks like it should be possible to have a fallback icon to indicate a missing glyph specified as part of the `.mdi:before, .mdi-set` declaration. I wasn't able to find any existing issue for this suggestion, but please feel free to close as a duplicate if this has been discussed.

**Comment by goyney** [comment]
I mean, yeah that sounds feasible. But we're also actively trying to ween people off of the webfont, so I'm not sure how much more work we're planning on doing to it in terms of improvements.

**Comment by md5** [comment]
Thanks for the quick response @goyney. Looking at the getting started docs, it looks like you're trying to move users to use Iconify? In our case, would not want to introduce an external dependency on the Iconify API, so we'd need to look at self hosting the API. However, it looks like only PHP and JS implementations are available for doing so, while many of our applications are Ruby on Rails apps. We have also striven to have the applications be self-contained in the past, while it looks like the [self hosting option](https://docs.iconify.design/sources/api/hosting.html) assumes that a separate Iconify API server would be stood up?

It appears that if we want to go the Iconify route, we would need to do something similar to what was done for Django and implement our own Rails engine to embed the Iconify API into each application. Given that choice, we'll probably stick with the webfont as long as it is maintained.

**Comment by goyney** [comment]
Iconify is one of many choices. Realistically, you should be using the SVGs directly. I [wrote a blog article](https://www.irigoyen.dev/blog/2021/02/17/stop-using-icon-fonts/) about why you shouldn't use icon fonts anymore with examples on how to get started in React.

What's your front-end stack look like? Perhaps I can help give you some other recommendations that would get you off the webfont and move you into a more modern icon architecture.

**Comment by md5** [comment]
Front-end stack is vanilla HTML5 for the most part :)

We do have some Vue.js, but it is only used to render specific elements on the page. We'd have to move all these (legacy) applications to have Vue render the whole page or use some other frontend framework to make MDI icons available anywhere on the page.

**Comment by goyney** [comment]
Sorry for the long delay.

I'd recommend using web components then. Check out the guide here: https://dev.materialdesignicons.com/getting-started/webcomponent

Other than that, you'll need to engineer your own solution. We try to provide as much information about the basics of consuming the library, but some of the more advanced things are up to the consumers. Happy coding!
