### ISSUE TITLE
Request to add Bitcoin Cash (BCH) and Monero (XMR) Icons

### ISSUE THREAD

**Issue by bdkappel** [Templarian/MaterialDesign#6061]
## Usage

I am setting up cryptocurrency trackers in my Home Assistant instance and I noticed that there are icons for Bitcoin (BTC), Ethereum (ETH), and Litecoin (LTC) but not for other common/top cryptocurrencies. I'd like to request that both Bitcoin Cash (BCH) and Monero (XMR) icons be added to the library. Please help my OCD by adding these two (and maybe even other) cryptocurrencies to the icon list. Thank you.

## Examples

I've attached PNG images of both icons, I'm not a graphic designer, but I can find a way to prepare them however needed.
![bitcoin-cash-circle](https://user-images.githubusercontent.com/43278926/125149138-c23ba000-e0fc-11eb-9570-438943e96a23.png)
![monero-xmr-logo](https://user-images.githubusercontent.com/43278926/125149142-c5cf2700-e0fc-11eb-9ea6-3b248f20736c.png)

Edit: Formatting

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
