### ISSUE TITLE
Auto Start-Stop Icon

### ISSUE THREAD

**Issue by PedroS5499** [Templarian/MaterialDesign#6064]
I have:

- [ x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Auto Start-Stop icon used in cars

## Examples

![image](https://user-images.githubusercontent.com/11250367/125588674-cfac0a51-decf-492c-b99f-1ed805d7edd3.png)

**Comment by goyney** [comment]
[![refresh-auto](https://materialdesignicons.com/icon/refresh-auto)](https://materialdesignicons.com/icon/refresh-auto)
