### ISSUE TITLE
TikTok Icon is not in directory

### ISSUE THREAD

**Issue by mujtaba-blueeast** [Templarian/MaterialDesign#6065]
I have:

-  [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
-  [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
-  Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As you know TikTok is one of the trending application in social these days. Please add its icon to use.

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
