### ISSUE TITLE
Wall Sconce variants - left & right

### ISSUE THREAD

**Issue by DeltaNu1142** [Templarian/MaterialDesign#6066]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

I'm looking for an icon to represent a fixture that projects light to the side/from a wall, like a pool light.

## Examples

I'm requesting left and right variants of "wall-sconce-round."

**Comment by goyney** [comment]
This is simply rotating the icon 90 degrees one way or the other. We typically don't add these variants unless there is compelling reason to do so.
