### ISSUE TITLE
Lightbulb-on : 20,50, 80 % filled

### ISSUE THREAD

**Issue by gotama32** [Templarian/MaterialDesign#6067]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

As a user of on Homeautomation-Tablet where i can switch different light scenes on  i want to have buld-icons which are filled with 20%, 50%, 80% based on "mdiLightbulbOn" so that i can use these icons as scene buttons and not build own one.

## Examples

Based on mdiLightbulbOn
![Bildschirmfoto 2021-07-16 um 11 26 17](https://user-images.githubusercontent.com/80398046/125925705-b818d7de-6ce4-49fa-bf33-4df3f197ca65.png)

**Comment by goyney** [comment]
Possibly related to #5868.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/159062116-9790553f-a30f-403c-9102-fac227840533.png)![image](https://user-images.githubusercontent.com/1015040/159062076-ffc2191e-148d-497d-af87-227758def8be.png)
![image](https://user-images.githubusercontent.com/1015040/159062167-2e692b36-6663-468f-850e-15a0d208e888.png)![image](https://user-images.githubusercontent.com/1015040/159062224-e676aa83-4e59-4a34-8e9f-348f23092306.png)
![image](https://user-images.githubusercontent.com/1015040/159062272-a7911564-93f7-4735-a992-878827d128ac.png)![image](https://user-images.githubusercontent.com/1015040/159062317-6f7cf665-aebd-4a7e-8386-5ada02e7ab2a.png)
![image](https://user-images.githubusercontent.com/1015040/159062349-6f164e40-b683-4a69-9dc0-68defba5ca79.png)![image](https://user-images.githubusercontent.com/1015040/159062392-640952be-e00c-4878-8671-96d7408a9845.png)
![image](https://user-images.githubusercontent.com/1015040/159062433-79f91a6d-95a5-4b84-98c2-60e5c8dc6666.png)

[lightbulb-levels.zip](https://github.com/Templarian/MaterialDesign/files/8306839/lightbulb-levels.zip)

**Comment by goyney** [comment]
All added.
