### ISSUE TITLE
Weather history (cloud and clock)

### ISSUE THREAD

**Issue by brainfrz82** [Templarian/MaterialDesign#6068]
I have:

- [V] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [V] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [V] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Used for historical weather data, or maybe even timer based cloud events

## Examples

weather-cloudy, but with a clock like calendar-clock

**Comment by goyney** [comment]
[![weather-cloudy-clock](https://materialdesignicons.com/icon/weather-cloudy-clock)](https://materialdesignicons.com/icon/weather-cloudy-clock)

**Comment by brainfrz82** [comment]
Thank you! It’s perfect :)
