### ISSUE TITLE
Add a sneaker or running shoe icon!

### ISSUE THREAD

**Issue by escully27** [Templarian/MaterialDesign#6069]
PLEASE add a shoe or sneaker or running shoe like icon.

I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.
There are already "mdi-shoe-formal" and "mdi-shoe-heel" I think there should also be a "mdi-shoe-sneaker" or "mdi-shoe-running" !

Our app https://www.trackster.us uses mdi icon and we have to use a custom image every time we want to have a shoe icon, which is quite often in the app.

## Examples

https://upload.wikimedia.org/wikipedia/commons/1/14/Running_shoe_icon.png

https://previews.123rf.com/images/veronchick84/veronchick842006/veronchick84200602134/149213051-shoes-icon-sneakers-icon-shoe-vector-.jpg

Include any example images so we know what the icon should look like.

THANK YOU!

**Comment by goyney** [comment]
Already exists.

[![shoe-sneaker](https://materialdesignicons.com/icon/shoe-sneaker)](https://materialdesignicons.com/icon/shoe-sneaker)
