### ISSUE TITLE
Near me / Location icon

### ISSUE THREAD

**Issue by justinlawrence** [Templarian/MaterialDesign#607]
Thanks guys, you rock!

Like this one, please:
http://images.clipartpanda.com/location-icon-iphone-location-arrow-128.png

Or this one (without the circle around it):
http://ic8.link/2924

Useful tags for this one: location, navigation, arrow.

**Comment by CoDEmanX** [comment]
Did you consider the following?

https://materialdesignicons.com/icon/map-marker
https://materialdesignicons.com/icon/crosshairs-gps
https://materialdesignicons.com/icon/account-location
https://materialdesignicons.com/icon/crosshairs
https://materialdesignicons.com/icon/map-marker-radius
https://materialdesignicons.com/icon/navigation

**Comment by justinlawrence** [comment]
Thanks, the crosshair one would work.

Still, it might be good to have the diagonal arrow, as I have seen it used
to signify "find me".

Thanks!

**Comment by CoDEmanX** [comment]
Okay. I thought about a human upper body like in the user/account icons, combined with the GPS crosshairs, but I suppose it would look more like assassination than locate-me...

**Comment by justinlawrence** [comment]
Wahaha!!

**Comment by CoDEmanX** [comment]
Neither really convinces me...
![locate-me](https://cloud.githubusercontent.com/assets/1309249/9275987/6adfd8e4-42a1-11e5-9f9c-633539ff9e7e.png) ![locate-me2](https://cloud.githubusercontent.com/assets/1309249/9275988/6ae2a1b4-42a1-11e5-997d-cb91c81fcd7c.png) ![locate-me3](https://cloud.githubusercontent.com/assets/1309249/9275989/6ae36c70-42a1-11e5-8385-614f34da305c.png)

**Comment by justinlawrence** [comment]
Ok, up to you. Thanks.

**Comment by CoDEmanX** [comment]
Google added an official near me icon in their v2.1.0 update:
https://design.google.com/icons/#ic_near_me

**Comment by Templarian** [comment]
[![near-me](https://materialdesignicons.com/icon/near-me)](https://materialdesignicons.com/icon/near-me)
