### ISSUE TITLE
Recycling.

### ISSUE THREAD

**Issue by SefDik** [Templarian/MaterialDesign#6075]
I'm looking for:
°1 — Bin bags (plastic bag like icon for rubbish/garbage/waste).
°2 — Bulk waste skip/container as seen at a recycling centre.
There are I know lots of rubbish/garbage/dustbins on the site.
Thanks.

**Comment by goyney** [comment]
`sack` would solve your first.

[![sack](https://materialdesignicons.com/icon/sack)](https://materialdesignicons.com/icon/sack)

You'll need to give more examples of what you mean by "bulk waste." Most of the time, that is indicated by furniture, which we have plenty of icons to represent.

**Comment by SefDik** [comment]
Hello,

**Sack**, yes very good, **thanks**, I did scan the icons and must have missed it ...
![garbage_bag_noir_ORIG](https://user-images.githubusercontent.com/72972248/126674072-ecfd4852-e861-4acf-a4fb-fe84e073db14.png)

Bulk waste, **a skip** (British, English), a trapezium shaped container that is lifted onto the back of a lorry (truck) for disposal of waste typically stuff from a building site.
![garbage_skip_icon_ORIG](https://user-images.githubusercontent.com/72972248/126673955-43facb04-085c-46d5-a14d-95b936e6c3f2.jpg)  
![image](https://user-images.githubusercontent.com/72972248/126675115-29dfcc7f-239c-412e-a9ee-8b236788e30b.png)
![image](https://user-images.githubusercontent.com/72972248/126675309-a052e534-0edd-4cf1-9239-e7441257cee0.png)

I am using 'mdi: dump-truck' at present but that does not quite do it.

A side on view might be easier, a simple trapezium.

_Now I'm being cheeky and want more ...._
Waste truck,
![image](https://user-images.githubusercontent.com/72972248/126675561-6a122d8d-aa70-41af-99a5-6b44060a5649.png)
Wheelie-bin (UK),
![image](https://user-images.githubusercontent.com/72972248/126675680-315f165c-2822-4964-b6e3-f8061bbd753d.png)


Thanks goyney for getting back, recycling is among us ....

Seth   /0^0\

**Comment by SefDik** [comment]
Hello goyney,
I've just found mdi : basket (series), they may fit the bill for the 'skip'.
Might be worth an alias ....
Seth  /0^0\

**Comment by goyney** [comment]
Aliases added.
