### ISSUE TITLE
gamepad-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#6078]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Outlined version of "gamepad" icon.

## Examples
![gamepad](https://user-images.githubusercontent.com/6717356/126648375-b104b4c5-fa66-4f4d-9d8b-c743520a553d.jpg)

**Comment by goyney** [comment]
[![gamepad-outline](https://materialdesignicons.com/icon/gamepad-outline)](https://materialdesignicons.com/icon/gamepad-outline)
