### ISSUE TITLE
Air compressor

### ISSUE THREAD

**Issue by itzniru** [Templarian/MaterialDesign#6079]
A simple air compressor would be great. Then I can add it in my technical flow chart. And in home assistant too.
![images](https://user-images.githubusercontent.com/67348697/126664479-0c184165-b56a-4ca4-aca1-c15d5384e634.jpg)

**Comment by jameswood** [comment]
Could this work?

![image](https://github.com/Templarian/MaterialDesign/assets/1140049/1fd74bef-4b83-4863-a98e-f56987fb1753)

[Air Compressor.zip](https://github.com/Templarian/MaterialDesign/files/13211301/Air.Compressor.zip)

**Comment by itzniru** [comment]
Looks great to me. :)
