### ISSUE TITLE
Telegram icon

### ISSUE THREAD

**Issue by Jaeger87** [Templarian/MaterialDesign#608]

**Comment by CoDEmanX** [comment]
Tele... What? Is that ancient pigeon-powered SMS? :wink:

I doubt it's possible due to too fine details:
![telegram] (https://d30y9cdsu7xlg0.cloudfront.net/png/22058-200.png)

**Comment by Jaeger87** [comment]
I mean this messaging app: https://telegram.org/

I thought you knew, this app soon will take the place of the shitty what's app.

**Comment by Templarian** [comment]
[![telegram](https://materialdesignicons.com/icon/telegram)](https://materialdesignicons.com/icon/telegram)
