### ISSUE TITLE
ceiling-light incorrect alias appear incorrect

### ISSUE THREAD

**Issue by bricrsa** [Templarian/MaterialDesign#6083]
mdi:ceiling-light has an alias of ceiling-lamp on https://materialdesignicons.com/

It should be ceiling-light (ceiling-lamp does not work)

**Comment by goyney** [comment]
Can you clarify the problem? `ceiling-light` has an alias of `ceiling-lamp`. Aliases are just used to help you search for icons on the website, you must use the actual name of the icon wherever you are consuming it.

**Comment by bricrsa** [comment]
I noticed this in Home Assistant when I was trying to consume it via mdi:ceiling-lamp. This did not work but mdi:ceiling-light did. Maybe my misunderstanding of how the aliases work. I did not another pending icon for ceiling lamp (which is different) when I did a search before submitting.

**Comment by goyney** [comment]
Aliases are only for making searching easier. Using our website or the Chrome/Firefox extension, aliases cover cases to help people find icons with different names. As I said before, when consuming the icon, you must use the actual icon name, in your case `ceiling-light`.
