### ISSUE TITLE
SLP coin

### ISSUE THREAD

**Issue by ygcorrea** [Templarian/MaterialDesign#6084]
I have:

- [X] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [X] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
Axie Infinity is a NFT game where you play to earn a coin called SLP. I think would be great to have SLP coin on mdi-icons, because is like any other coin and the game is growing exponentially. I (and other developers) will use it on my software based on this game.

## Examples

The icon that i made/ original
![yasmim_correa_slpcoin](https://user-images.githubusercontent.com/58710976/126883621-8a55d089-6427-4154-b5a8-8de610901a8f.png)
![slp](https://user-images.githubusercontent.com/58710976/126883596-83f05598-5b98-445d-9642-85cd4f452b77.png)

**Comment by goyney** [comment]
This is very, very niche and not a good fit for this library. Thanks for your suggestion.
