### ISSUE TITLE
Agriculture batch

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6089]
I suggest we apply `Agriculture` tag to:
- barn
- greenhouse
- chili-mild
- food-apple 
- food-apple-outline
- egg
- egg-off
- egg-outline
- fruit-cherries
- fruit-citrus
- fruit-grapes
- fruit-grapes-outline
- fruit-pineapple
- fruit-watermelon
- hops
- mushroom
- mushroom-outline
- leaf
- leaf-off
- peanut
- peanut-outline
- account-cowboy-hat
- pig-variant-outline
- horse
- horseshoe
- horse-variant
- turkey

Some of these have `off` variants too, but I don't think that's as relevant here.

**Comment by goyney** [comment]
All added.
