### ISSUE TITLE
triangle-small

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6093]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

I'd like to show a month-over-month change in my app, and several icons haven't met this need. The current trending icons are too heavy for simple metadata, the triangle is too large, and the menu icons suggest an interaction that isn't there. This icon pattern is common in stock apps, so I thought it'd be helpful here too.

Alternatively, these could be triangle-small-up/down or something like that.

![image](https://user-images.githubusercontent.com/2228347/127097996-f4e862e8-64ae-4618-88c1-2218f8d14e74.png)

References from Robinhood app:
![image](https://user-images.githubusercontent.com/2228347/127098227-58635eb5-904f-483a-8af4-e3800e870167.png)

## Zip Download

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/6882802/Archive.zip)

**Comment by goyney** [comment]
[![menu-up](https://materialdesignicons.com/icon/menu-up)](https://materialdesignicons.com/icon/menu-up)[![menu-down](https://materialdesignicons.com/icon/menu-down)](https://materialdesignicons.com/icon/menu-down)

**Comment by jhil** [comment]
@goyney Hoping to reopen this up. Triangle and menu-up/down still don't work for this purpose, the former because it's too large and the latter because the interactions would get confused with actual menu actions. There is a precedent in square-medium, so I think moving this forward as triangle-medium and/or my trending-up/down variant would be helpful, especially for the growing number of investing apps.

**Comment by jhil** [comment]
Eyyyy

**Comment by goyney** [comment]
@jhil When you add new icons, please post the previews here, set the milestone, and assign the issue to whomever got credit. File keeping stuff. :)

**Comment by goyney** [comment]
[![triangle-small-up](https://materialdesignicons.com/icon/triangle-small-up)](https://materialdesignicons.com/icon/triangle-small-up)[![triangle-small-down](https://materialdesignicons.com/icon/triangle-small-down)](https://materialdesignicons.com/icon/triangle-small-down)

**Comment by jhil** [comment]
Thanks for the pointers and sorry for the confusion! This was my first day merging in a final icon, so I'll know for next time.
