### ISSUE TITLE
Icon home-floor-negative-2

### ISSUE THREAD

**Issue by slider07210** [Templarian/MaterialDesign#6098]
Hello,

Can you create icon home-floor-negative-2 ?
![home-floor-negative-2](https://user-images.githubusercontent.com/60269193/127551125-3b723dd1-19d3-4e67-81a1-68e72bdf0cf8.png)

Thank you

**Comment by goyney** [comment]
https://github.com/Templarian/MaterialDesign/issues/3866#issuecomment-462920138
