### ISSUE TITLE
Webmenu Icon

### ISSUE THREAD

**Issue by bgiesing** [Templarian/MaterialDesign#610]
[Webmenu](http://webmenu.org) is a web app store.

Example:
![Webmenu Badge](https://d2avfbmbvwlo8q.cloudfront.net/assets/square_badge-791aca7a0be903dab25007bf8d1ca058.png)

**Comment by Templarian** [comment]
Logos or brands are not allowed in the icon pack at this time. Eventually tools will become available to include external icons. For now we recommend using SVG's or vector drawables for outside icons.

**Comment by bgiesing** [comment]
This is similar to the Patreon request I made and that didn't get closed. It's also like the Play Store icon which is already available. It's like an get on Play Store or App store button but for web apps. 

Why is this different? Just curious...

**Comment by Templarian** [comment]
The pack mainly targets social media focused logos. Not companies or stores. You will find this in most icon packs.

It's also far too specific of an icon for the pack.
