### ISSUE TITLE
Faculties

### ISSUE THREAD

**Issue by cbrhex** [Templarian/MaterialDesign#6100]
We definitely need icon like this

![](https://images.squarespace-cdn.com/content/v1/55b21c72e4b09b5e3592ea96/1570535886898-THFS2HDQP5MQIR49F3SO/FAC-icon.png?format=300w)

=)

**Comment by goyney** [comment]
[![bank](https://materialdesignicons.com/icon/bank)](https://materialdesignicons.com/icon/bank)
