### ISSUE TITLE
clear-selection-*

### ISSUE THREAD

**Issue by JokerMartini** [Templarian/MaterialDesign#6101]
I have:

- [ x ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ x ] Searched open issues to make sure there isn't a request for this icon.
- [ x ] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/1416749/127757245-f6ca2ac9-cee1-4e76-b0ec-6bd55b58423b.png)
![image](https://user-images.githubusercontent.com/1416749/127757248-b6dec69b-4f53-4848-b828-115fdebfc749.png)
![image](https://user-images.githubusercontent.com/1416749/127757263-722374e5-96dd-4985-bd96-59a5e61ad4c7.png)
![image](https://user-images.githubusercontent.com/1416749/127757266-ff4f16b2-16ee-4116-9e75-4339b25f6a1e.png)
![image](https://user-images.githubusercontent.com/1416749/127757267-0be10d87-6f31-4685-b803-a0fa41156255.png)

## Zip Download
[icons.zip](https://github.com/Templarian/MaterialDesign/files/6912063/icons.zip)

**Comment by goyney** [comment]
The airplanes break Material Guidelines and will not be added. The others look good.

**Comment by JokerMartini** [comment]
Thank you @goyney for the feedback. You all are doing great work and it's much appreciated.

**Comment by goyney** [comment]
[![select-remove](https://materialdesignicons.com/icon/select-remove)](https://materialdesignicons.com/icon/select-remove)[![selection-remove](https://materialdesignicons.com/icon/selection-remove)](https://materialdesignicons.com/icon/selection-remove)
[![selection-ellipse-remove](https://materialdesignicons.com/icon/selection-ellipse-remove)](https://materialdesignicons.com/icon/selection-ellipse-remove)
