### ISSUE TITLE
Retractable Projector Screen

### ISSUE THREAD

**Issue by pp81381** [Templarian/MaterialDesign#6102]
I'd like to suggest a variant on the existing projector-screen icons (projector-screen-outline and projector-screen) that would represent an in-ceiling retractable projector screen in either the open (down) or closed (up) position.

I'm not an expert so apologies in advance if the contribution (or naming) isn't quite right.   Happy to tweak it or simply treat this as an icon request instead.

I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator](http://dev.materialdesignicons.com/contribute/github).

![image](https://user-images.githubusercontent.com/19621928/127865658-5c303339-d97f-4648-8848-4d0952491f50.png)

![image](https://user-images.githubusercontent.com/19621928/127865587-36e1e729-9b9a-4a40-999c-6091cf7661c3.png)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

[retractable-screen.zip](https://github.com/Templarian/MaterialDesign/files/6917044/retractable-screen.zip)

**Comment by goyney** [comment]
We have `blinds` and `blinds-open` which I think hits this.
[![blinds](https://materialdesignicons.com/icon/blinds)](https://materialdesignicons.com/icon/blinds)
[![blinds-open](https://materialdesignicons.com/icon/blinds-open)](https://materialdesignicons.com/icon/blinds-open)

**Comment by pp81381** [comment]
Thanks for the quick response!

The context is that I've written a Home Assistant integration for a projector screen controller so it already uses the blinds icons.   I'm not keen on using the blinds icons for the projector screen for a couple of reasons:

- I have motorised blinds in the same room as the projector screen so it is confusing to use the same icon for both - especially since the semantics of open and closed are opposite for the blinds and the screen
- The material design principle is that one should reduce the entity to its "essential characteristics".   I would argue that the most essential characteristic of a projector screen is the actual screen part and that doesn't appear on the blinds icons.
- While I can cope with a pull string on the _motorised_ blind icon because I think that it helps people recognise what is being represented, I struggle with the idea of a pull string on a motorised in-ceiling screen.

In the meantime I have been playing around with a couple of other ideas.   Would these be any better?

![image](https://user-images.githubusercontent.com/19621928/128003101-d16895b3-8a55-43a8-80c1-c0df02663a4d.png)

![image](https://user-images.githubusercontent.com/19621928/128003136-d895cf2e-eda0-404e-9bf1-960df6bcab9e.png)

Thanks & Regards!

**Comment by goyney** [comment]
I'd check out the [guidelines](https://material.io/design/iconography/system-icons.html) again. Mainly, your use of 1dp lines and 1dp corners breaks them.

**Comment by pp81381** [comment]
Thanks for the feedback.   Are these more acceptable?

![image](https://user-images.githubusercontent.com/19621928/128046693-64025ca6-e2ca-4952-96cc-5453de40d20b.png)

![image](https://user-images.githubusercontent.com/19621928/128046718-7e558122-e2c7-44ee-ace8-6e67a86b9beb.png)

**Comment by goyney** [comment]
Can you make the top bar 4dp in height? The `retracted` variant doesn't really look like anything.

**Comment by pp81381** [comment]
Here it is with a wider top bar.

![image](https://user-images.githubusercontent.com/19621928/128052049-d776e97a-d87f-437d-befd-a2856fa3f60c.png)

For me, that puts too much emphasis on the ceiling box/roller element.   I prefer this version where I get rid of it but make the top wider.   What do you think?

![image](https://user-images.githubusercontent.com/19621928/128052341-ff5d9bf2-0659-4009-ae65-1539d594eaa4.png)

I do agree about the retracted version.   I notice that a lot of icons have a slash through them to indicate "off".   Here's a crude attempt.   If you think that this is better then I'll go to the effort of doing it properly, detaching the top right with a neat 2px wide blank line...

![image](https://user-images.githubusercontent.com/19621928/128053008-9764975b-90f0-4411-8760-a6a44cc84b6c.png)

**Comment by goyney** [comment]
What about using the existing `projector-screen`s, removing the stand and calling them variants, and then adding `off` versions of all of them. So, we could add the following:

- [ ] `projector-screen-variant` (New without the stand)
- [ ] `projector-screen-variant-outline` (New without the stand)
- [ ] `projector-screen-off` (Existing with slash)
- [ ] `projector-screen-off-outline` (Existing with slash)
- [ ] `projector-screen-variant-off` (New without stand and with slash)
- [ ] `projector-screen-variant-off-outline` (New without stand and with slash)

Then they would all be standardized and solve your use case?

**Comment by pp81381** [comment]
I've had a go at it.   What do you think?

![image](https://user-images.githubusercontent.com/19621928/128088641-79c8d615-97e6-4f32-a645-e1d057551caf.png)

![image](https://user-images.githubusercontent.com/19621928/128088678-651a9442-27fa-4c0c-b362-a2055891fa61.png)

![image](https://user-images.githubusercontent.com/19621928/128088734-4b414e6d-f86a-4376-9838-d6cc075fc83b.png)

![image](https://user-images.githubusercontent.com/19621928/128088803-55f94ce7-cb5c-4981-8573-15a5d5ddfa09.png)

![image](https://user-images.githubusercontent.com/19621928/128088860-9613a26b-9b76-4399-b0ec-f5ef28e21ef6.png)

![image](https://user-images.githubusercontent.com/19621928/128088912-a8f7614b-3aa8-4767-8400-ff20a4c94138.png)

**Comment by pp81381** [comment]
By the way, here are the corresponding svg files...

[projector-screen-variant.zip](https://github.com/Templarian/MaterialDesign/files/6944927/projector-screen-variant.zip)

**Comment by goyney** [comment]
[![projector-screen](https://materialdesignicons.com/icon/projector-screen)](https://materialdesignicons.com/icon/projector-screen)[![projector-screen-outline](https://materialdesignicons.com/icon/projector-screen-outline)](https://materialdesignicons.com/icon/projector-screen-outline)
[![projector-screen-off](https://materialdesignicons.com/icon/projector-screen-off)](https://materialdesignicons.com/icon/projector-screen-off)[![projector-screen-off-outline](https://materialdesignicons.com/icon/projector-screen-off-outline)](https://materialdesignicons.com/icon/projector-screen-off-outline)

[![projector-screen-variant](https://materialdesignicons.com/icon/projector-screen-variant)](https://materialdesignicons.com/icon/projector-screen-variant)[![projector-screen-variant-outline](https://materialdesignicons.com/icon/projector-screen-variant-outline)](https://materialdesignicons.com/icon/projector-screen-variant-outline)
[![projector-screen-variant-off](https://materialdesignicons.com/icon/projector-screen-variant-off)](https://materialdesignicons.com/icon/projector-screen-variant-off)[![projector-screen-variant-off-outline](https://materialdesignicons.com/icon/projector-screen-variant-off-outline)](https://materialdesignicons.com/icon/projector-screen-variant-off-outline)

**Comment by pp81381** [comment]
Thanks.   The updates look great!
