### ISSUE TITLE
Request - Check Internet connection icon

### ISSUE THREAD

**Issue by bebenins** [Templarian/MaterialDesign#6103]
## Usage

My app has a button that does one thing and one thing only - checks to see whether there's internet connection or not.  It could be wired, it could be wireless.

## Examples

I was thinking something like this:
![image](https://user-images.githubusercontent.com/16761301/127900599-efa5fe10-266b-4837-a23d-104aae0f5339.png)

You can see the existing "Database-Check" on the right to use as an example.
I mocked up my idea using existing "Web" and "Check" icons but as you can see, the "Check" icon is inconsistent so I would really appreciate an official icon.

Thank you!

**Comment by goyney** [comment]
This was added.

[![web-check](https://materialdesignicons.com/icon/web-check)](https://materialdesignicons.com/icon/web-check)
