### ISSUE TITLE
In love emoji

### ISSUE THREAD

**Issue by vieira96** [Templarian/MaterialDesign#6104]
I have:

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

In love emoji can be used to available a video/course
![in love](https://user-images.githubusercontent.com/54036603/127935901-632bc9fe-2ac8-4f91-a86a-c96adcd77e7a.png)

**Comment by goyney** [comment]
Unfortunately, due to Material restrictions, we cannot fit two small hearts within the space we have available and have it distinguishable at native resolution. Thanks for your suggestion.
