### ISSUE TITLE
Arrows with filled arrowheads

### ISSUE THREAD

**Issue by mattStayner** [Templarian/MaterialDesign#6108]
I have:

- [X] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist. There are other arrows, but none with the filled-in arrowhead, which is what I needed. I thought I would share it here.
- [X] Searched open issues to make sure there isn't a request for this icon.
- [X] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

Paste a preview of your icon here. You can generate one using our [preview generator]
![image](https://user-images.githubusercontent.com/72460706/128607740-b10bc962-74e2-4daa-846f-43cbf4520b4d.png)
![image](https://user-images.githubusercontent.com/72460706/128607755-a6f9269a-6570-4a56-8196-29be3e0fd379.png)
![image](https://user-images.githubusercontent.com/72460706/128607766-b9a898f4-4a4b-4a04-9c51-fdbb7575acd8.png)
![image](https://user-images.githubusercontent.com/72460706/128607776-adca86a9-8ca4-4941-94cf-0c66ab9b044c.png)
![image](https://user-images.githubusercontent.com/72460706/128607787-544b2755-03c5-4054-836f-5bfeaea95491.png)
![image](https://user-images.githubusercontent.com/72460706/128607794-09e3592f-3d14-4b28-9e08-75b556a5b2b5.png)
![image](https://user-images.githubusercontent.com/72460706/128607803-b6f8afa8-351e-4eae-bd08-2225a49ef48d.png)
![image](https://user-images.githubusercontent.com/72460706/128607817-b9b61002-c5b5-45d1-bb47-ccf7b369033d.png)
[arrows-filled.zip](https://github.com/Templarian/MaterialDesign/files/6949430/arrows-filled.zip)

## Zip Download

Drag or paste a zip folder containing your icon as a minimal SVG file. We just need the SVG tag with the viewbox and a single path element.

**Comment by goyney** [comment]
This would be a @Templarian decision, but these (as of right now) don't fit into our naming standards.

- Normal arrows are open headed
- Thick arrows are open headed, but thicker
- Bold arrows are close header and thicker

I'm not sure how we would name these, but don't see any reason to not add them.

**Comment by goyney** [comment]
[![arrow-left-thin](https://materialdesignicons.com/icon/arrow-left-thin)](https://materialdesignicons.com/icon/arrow-left-thin)[![arrow-right-thin](https://materialdesignicons.com/icon/arrow-right-thin)](https://materialdesignicons.com/icon/arrow-right-thin)
[![arrow-up-thin](https://materialdesignicons.com/icon/arrow-up-thin)](https://materialdesignicons.com/icon/arrow-up-thin)[![arrow-down-thin](https://materialdesignicons.com/icon/arrow-down-thin)](https://materialdesignicons.com/icon/arrow-down-thin)
[![arrow-top-left-thin](https://materialdesignicons.com/icon/arrow-top-left-thin)](https://materialdesignicons.com/icon/arrow-top-left-thin)[![arrow-top-right-thin](https://materialdesignicons.com/icon/arrow-top-right-thin)](https://materialdesignicons.com/icon/arrow-top-right-thin)
[![arrow-bottom-left-thin](https://materialdesignicons.com/icon/arrow-bottom-left-thin)](https://materialdesignicons.com/icon/arrow-bottom-left-thin)[![arrow-bottom-right-thin](https://materialdesignicons.com/icon/arrow-bottom-right-thin)](https://materialdesignicons.com/icon/arrow-bottom-right-thin)
