### ISSUE TITLE
punctuation mark

### ISSUE THREAD

**Issue by WaylanPunch** [Templarian/MaterialDesign#611]
punctuation mark, like below
![1-1- 44](https://cloud.githubusercontent.com/assets/11749782/9269096/834f4b66-4298-11e5-81fd-d6176003b457.png)

**Comment by CoDEmanX** [comment]
It's better called double quote marks. There's already a stock one:
https://materialdesignicons.com/icon/format-quote
Leaving this open because another version of this icon rotated by 180° could be added to fulfill your request.

**Comment by WaylanPunch** [comment]
Sorry, I didn't see it.
