### ISSUE TITLE
Railing/Fence

### ISSUE THREAD

**Issue by hathalud** [Templarian/MaterialDesign#6110]
I have:

- [*] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [*] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [*] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage
I have a balcony that I would like to represent in Home Assistant via an icon of a Railing or Fence. While I would prefer a railing, something akin to the tradition picket fence would be acceptable too.

Provide some context of how your icon could be used.
Besides representing a balcony, it could be used to represent a patio, a yard or a similar enclosed outdoor area. 

## Examples

Include any example images so we know what the icon should look like.
![image](https://user-images.githubusercontent.com/5944078/128616377-c17520ed-d592-487a-b783-a3adfe2e930b.png)

**Comment by goyney** [comment]
`gate` could potentially cover this use case.

[![gate](https://materialdesignicons.com/icon/gate)](https://materialdesignicons.com/icon/gate)

**Comment by hathalud** [comment]
True, that would work. Thank you.

**Comment by JamesCoyle** [comment]
Would it be worth adding an icon with all the upper prongs the same height to represent a fence?

**Comment by goyney** [comment]
[![fence](https://materialdesignicons.com/icon/fence)](https://materialdesignicons.com/icon/fence)
