### ISSUE TITLE
Web Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6112]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![web-off](https://user-images.githubusercontent.com/1837101/129088959-ff668dfd-4849-4c36-bc6b-6bf6729825e4.png)

![web-plus](https://user-images.githubusercontent.com/1837101/129088960-3f47c1eb-141d-43d5-a9d0-55ce9ee16fa0.png)

![web-minus](https://user-images.githubusercontent.com/1837101/129088957-7dc755a2-72d0-48f1-9736-04bcdd1becb5.png)

![web-check](https://user-images.githubusercontent.com/1837101/129088956-0adaa381-46ed-4703-be2e-2e480d29121a.png)

![web-remove](https://user-images.githubusercontent.com/1837101/129088963-005b9a2a-f1db-4813-939a-f3b9c7e4ffc6.png)

![web-cancel](https://user-images.githubusercontent.com/1837101/129088955-b4f174f9-e754-49c9-8699-0a6326483c66.png)

![web-refresh](https://user-images.githubusercontent.com/1837101/129088962-bcc988c3-fdf8-46b8-bf1f-73b750e3de54.png)

![web-sync](https://user-images.githubusercontent.com/1837101/129088965-e88de2e6-899a-486e-8d4d-60a56106f6e3.png)

## Zip Download

[web-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/6970822/web-modifiers.zip)

**Comment by goyney** [comment]
All added.
