### ISSUE TITLE
3D Printer - Heat

### ISSUE THREAD

**Issue by kineticscreen** [Templarian/MaterialDesign#6113]
I have:

- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Searched open issues to make sure there isn't a request for this icon.
- [x] Followed the [material guidelines](https://material.io/design/iconography/system-icons.html).

## Preview

![image](https://user-images.githubusercontent.com/39250334/129133114-9fe55942-13e1-492e-8a80-d33ba147c611.png)

## Zip Download

[printer-3d-nozzle-heat.zip](https://github.com/Templarian/MaterialDesign/files/6972596/printer-3d-nozzle-heat.zip)

**Comment by dpeter99** [comment]
In my opinion this is hard to make out...
The nozle of the 3d printer is not that common object. I would suggest a full 3d printer icon. As that could be used to represent both filament and resin based printers (Or even the facncy metal powder based ones).

**Comment by kineticscreen** [comment]
This i just a minor addition to the already existing icons:
![image](https://user-images.githubusercontent.com/39250334/129443434-04e0e7e7-6b0f-4e32-a3d7-375dc9cd29ae.png)

**Comment by dpeter99** [comment]
Well those have the filament coming out of the nozle. I think that makes it more recognizable.

**Comment by kineticscreen** [comment]
Yeah it's just that in the context of it pre-heating, filament coming out of the nozzle doesn't make sense. Although then it would also make sense to have an 'idle' icon as well, if it's about creating a set for different printer states.

**Comment by goyney** [comment]
I think in the right context, these icons make sense, so I've added them.
[![printer-3d-nozzle-heat](https://materialdesignicons.com/icon/printer-3d-nozzle-heat)](https://materialdesignicons.com/icon/printer-3d-nozzle-heat)[![printer-3d-nozzle-heat-outline](https://materialdesignicons.com/icon/printer-3d-nozzle-heat-outline)](https://materialdesignicons.com/icon/printer-3d-nozzle-heat-outline)
