### ISSUE TITLE
AddNewIcon

### ISSUE THREAD

**Issue by rohamishop** [Templarian/MaterialDesign#6118]
hello 
dear sir or madam
I am new on this site and I couldn't find some icons .
Would you please Add some icons on material design library such as: 

**1. Home appliance category
2. Kitchen Machine
3. Hand blender (electric masher)
4. Steam Iron
5. Bread Toaster
6. Meat Grinder
7. Vacuum Cleaner
8. Fruit juicer**

Thank you so much

- [ ] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [ ] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [ ] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples
https://img.icons8.com/ios/2x/toaster.png
https://img.icons8.com/ios/2x/meat-grinder.png
https://img.icons8.com/ios/2x/iron.png
https://img.icons8.com/ios/2x/toaster.png
https://img.icons8.com/ios/2x/electric-teapot.png
https://img.icons8.com/ios/2x/vacuum-cleaner.png
https://img.icons8.com/ios/2x/mixer.png
https://img.icons8.com/ios/2x/coffee-maker.png
https://img.icons8.com/ios/2x/cooker.png
https://static.thenounproject.com/png/1965498-200.png
https://static.thenounproject.com/png/4138964-200.png
https://static.thenounproject.com/png/717658-200.png
https://static.thenounproject.com/png/3582946-200.png
https://static.thenounproject.com/png/2707679-200.png
https://static.thenounproject.com/png/982942-200.png
https://static.thenounproject.com/png/3865212-200.png
https://static.thenounproject.com/png/4153408-200.png
https://static.thenounproject.com/png/1579687-200.png
https://static.thenounproject.com/png/1993031-200.png
https://static.thenounproject.com/png/1868174-200.png
https://static.thenounproject.com/png/2061563-200.png
https://static.thenounproject.com/png/2127227-200.png
https://static.thenounproject.com/png/3409619-200.png
https://static.thenounproject.com/png/1579670-200.png
https://static.thenounproject.com/png/1747263-200.png
https://static.thenounproject.com/png/1777227-200.png
https://static.thenounproject.com/png/2853287-200.png
https://static.thenounproject.com/png/1945602-200.png
https://static.thenounproject.com/png/1830790-200.png
https://static.thenounproject.com/png/3659745-200.png
https://static.thenounproject.com/png/3659753-200.png
https://static.thenounproject.com/png/1339237-200.png
https://static.thenounproject.com/png/1383654-200.png
https://static.thenounproject.com/png/3454998-200.png
https://static.thenounproject.com/png/3123728-200.png
https://static.thenounproject.com/png/3996898-200.png

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
>  Searched all issues to make sure there isn't a request for this icon.
> Searched the current library to make sure the icon doesn't exist.
> Only requested a single icon (or a few near-identical ones) in this issue.

You didn't do any of these. Some of these exists. Others have been requested. Please take the time to discover those and then open a _single_ issue per icon request and fill out the template appropriately. Thank you.

**Comment by rohamishop** [comment]
> 
> 
> hello
> dear sir or madam
> I am new on this site and I couldn't find some icons .
> Would you please Add some icons on material design library such as:
> 
> **1. Home appliance category 2. Kitchen Machine 3. Hand blender (electric masher) 4. Steam Iron 5. Bread Toaster 6. Meat Grinder 7. Vacuum Cleaner 8. Fruit juicer**
> 
> Thank you so much
> 
>     * [ ]  [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
> 
>     * [ ]  [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
> 
>     * [ ]  Only requested a single icon (or a few near-identical ones) in this issue.
> 
> 
> ## Usage
> 
> Provide some context of how your icon could be used.
> ## Examples
> 
> https://img.icons8.com/ios/2x/toaster.png
> https://img.icons8.com/ios/2x/meat-grinder.png
> https://img.icons8.com/ios/2x/iron.png
> https://img.icons8.com/ios/2x/toaster.png
> https://img.icons8.com/ios/2x/electric-teapot.png
> https://img.icons8.com/ios/2x/vacuum-cleaner.png
> https://img.icons8.com/ios/2x/mixer.png
> https://img.icons8.com/ios/2x/coffee-maker.png
> https://img.icons8.com/ios/2x/cooker.png
> https://static.thenounproject.com/png/1965498-200.png
> https://static.thenounproject.com/png/4138964-200.png
> https://static.thenounproject.com/png/717658-200.png
> https://static.thenounproject.com/png/3582946-200.png
> https://static.thenounproject.com/png/2707679-200.png
> https://static.thenounproject.com/png/982942-200.png
> https://static.thenounproject.com/png/3865212-200.png
> https://static.thenounproject.com/png/4153408-200.png
> https://static.thenounproject.com/png/1579687-200.png
> https://static.thenounproject.com/png/1993031-200.png
> https://static.thenounproject.com/png/1868174-200.png
> https://static.thenounproject.com/png/2061563-200.png
> https://static.thenounproject.com/png/2127227-200.png
> https://static.thenounproject.com/png/3409619-200.png
> https://static.thenounproject.com/png/1579670-200.png
> https://static.thenounproject.com/png/1747263-200.png
> https://static.thenounproject.com/png/1777227-200.png
> https://static.thenounproject.com/png/2853287-200.png
> https://static.thenounproject.com/png/1945602-200.png
> https://static.thenounproject.com/png/1830790-200.png
> https://static.thenounproject.com/png/3659745-200.png
> https://static.thenounproject.com/png/3659753-200.png
> https://static.thenounproject.com/png/1339237-200.png
> https://static.thenounproject.com/png/1383654-200.png
> https://static.thenounproject.com/png/3454998-200.png
> https://static.thenounproject.com/png/3123728-200.png
> https://static.thenounproject.com/png/3996898-200.png
> 
> Include any example images so we know what the icon should look like.

Excuse me sir
I'm not a Developer. I can just search icons in template that you created and I need meat grinder, steam Iron, .... . How can I find here? would please show me a sample to find or create ? or would you please add them so I use it in my word press site.
thank you so much
