### ISSUE TITLE
Yield Icon

### ISSUE THREAD

**Issue by antonvonpiller** [Templarian/MaterialDesign#612]
![14395858593280](https://cloud.githubusercontent.com/assets/1309249/9283955/fc55d1f8-42d7-11e5-828e-b77068d2cda1.jpg)

**Comment by CoDEmanX** [comment]
Please don't post Google links. They are overly long, can contain sensitive data and may not work for others. Use the actual deep link, or download an image, reduce size if necessary and upload directly, so that it can't go offline.

**Comment by PeterShaggyNoble** [comment]
I believe [`details`](https://materialdesignicons.comm/icon/details) should fulfil this request.
