### ISSUE TITLE
format-letter-spacing

### ISSUE THREAD

**Issue by Latiatcha** [Templarian/MaterialDesign#6121]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Icon idea for spacing letters

## Examples

![format-letter-spacing](https://user-images.githubusercontent.com/26218680/129692944-4b971da1-1a7d-4897-8adb-08922fe0c261.png)

**Comment by goyney** [comment]
I don't know why, but many applications use this VA pattern. Gonna wait on adding this one to see if more discussion happens first.

![image](https://user-images.githubusercontent.com/1015040/133351541-ff701a47-222b-49a1-bc37-366859a3085d.png)

[format-letter-spacing.svg.zip](https://github.com/Templarian/MaterialDesign/files/7165849/format-letter-spacing.svg.zip)

**Comment by goyney** [comment]
[![format-letter-spacing](https://materialdesignicons.com/icon/format-letter-spacing)](https://materialdesignicons.com/icon/format-letter-spacing)
