### ISSUE TITLE
versus

### ISSUE THREAD

**Issue by Sotiris-Bekiaris** [Templarian/MaterialDesign#6124]
I have:

- [•] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [•] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [•] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

An icon for the versus word which is often abbreviated to vs. for games and sports.

## Examples

![image](https://user-images.githubusercontent.com/55894770/129930348-dbdaefff-4751-4597-9326-bac134cd998b.png)
![image](https://user-images.githubusercontent.com/55894770/129930475-01197b0b-6ec3-4a59-8366-d4000a641d07.png)

**Comment by goyney** [comment]
Unfortunately, this request would introduce a language conflict. We only add letter-only based icons in very special or specific cases. You can manually create this using our `alpha` icons. Thanks for your suggestion.
