### ISSUE TITLE
Add installation Material Design to applications in Meteor

### ISSUE THREAD

**Issue by lcpereira** [Templarian/MaterialDesign#613]
Hello,

Enable the use of icons by the meteor, without having to use the "npm" installing "command attached meteor add templarian:mdi"

Thanks!

**Comment by Templarian** [comment]
I have absolutely no idea what this issue means. Can you explain it more in depth? "Meteor?"

Might be helpful to explain it in steps or links.

**Comment by CoDEmanX** [comment]
Icpereira refers to MeteorJS and its package manager atmosphere I guess:
https://www.meteor.com
https://atmospherejs.com

**Comment by Templarian** [comment]
Hmm... another package manager. Maybe... will have to read up on what is required to support it.

Probably a low priority right now. Maybe after the next release. I have the next package built just cleaning up some bug fixes before I tag the branch and release.

**Comment by lcpereira** [comment]
:thumbsup:

**Comment by cedla** [comment]
If you're interested, I made a package for the webfont a few weeks ago:
https://atmospherejs.com/cedla/mdi

**Comment by lcpereira** [comment]
Perfect @cedla thanks! ;)
