### ISSUE TITLE
Vacuum Cleaner

### ISSUE THREAD

**Issue by rohamishop** [Templarian/MaterialDesign#6131]
I have:

- [x] [Searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [x] [Searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't exist.
- [x] Only requested a single icon (or a few near-identical ones) in this issue. 

## Usage

Provide some context of how your icon could be used.

## Examples

1) https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvv6kP5WbXCqswS8T5nk5iO9CEYfLIa9YJ-A&usqp=CAU

2) https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYydgPQL1zS4y0jAh3JHHJTkca91pY8MvAqg&usqp=CAU

Include any example images so we know what the icon should look like.

**Comment by goyney** [comment]
Duplicate #2217.
