### ISSUE TITLE
ceiling-light (variants duo, tripple)

### ISSUE THREAD

**Issue by berkavil** [Templarian/MaterialDesign#6136]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Hallo, thank you for creating such rich library of icons, it is realy beautiful and very useful.
I would appreciate to have also ceiling lights in duo and/or in tripple lights variants. (One switch turns-on more lights in the living room) on the Picture element card there will be just one button. 

### Give us an example of it's usage.

There are many variants of ceiling lights on the market, In the library mdi: there is not available ceiling light in "duo" and/or in "tripple" lights variants. 
My case - one switch turns-on more lights in the living room, usage will be on the Picture element card - to have one button for more ceiling lights.

**Comment by goyney** [comment]
Are you suggesting a `-multiple` version of `ceiling-light`... or something new entirely?

**Comment by berkavil** [comment]
hallo, thnks for answer, i was suggesting a version of ceiling light (one ceiling ligt with more cylinders)... thank you.VilemDne 25. 8. 2021 0:49 napsal uživatel Michael Irigoyen ***@***.***>:
Are you suggesting a -multiple version of ceiling-light... or something new entirely?

**Comment by goyney** [comment]
Something like our recently added `chandelier`?
[![chandelier](https://materialdesignicons.com/icon/chandelier)](https://materialdesignicons.com/icon/chandelier)

**Comment by goyney** [comment]
The multiple variant might suffer the same problem as our `lamp` icon and why we created `lamps` instead. We can give it a shot and see if it'll work.

**Comment by goyney** [comment]
I was able to get the `multiple` version of `ceiling-light` to work, however there is simply not enough space for anything else.

[![ceiling-light-multiple](https://materialdesignicons.com/icon/ceiling-light-multiple)](https://materialdesignicons.com/icon/ceiling-light-multiple)[![ceiling-light-multiple-outline](https://materialdesignicons.com/icon/ceiling-light-multiple-outline)](https://materialdesignicons.com/icon/ceiling-light-multiple-outline)

**Comment by berkavil** [comment]
Thank you very much J

Vilem

**Comment by goyney** [comment]
These will be released in `v6.3.95`, which has not gone out yet. It'll likely go out in approximately 2 weeks. That will likely be too late to get into Home Assistant before their October release, but we will try our best. If it does not make their October release, you can expect it no later then November.

**Comment by berkavil** [comment]
OK thank you for info – no problém, I was just afraid that I am doing something wrong…

Thank you for the new icons.

Vilem
