### ISSUE TITLE
i miss a lot of icons on the subject of home automation 

### ISSUE THREAD

**Issue by sohnvonoff** [Templarian/MaterialDesign#6138]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Sorry.. , 
i miss a lot of icons on the subject of home automation. They are symbols for the different rooms, objects and levels of a house. Symbols for yard, garden, greenhouse, fence, outdoor lighting, garden shed, gazebo, irrigation, outdoor camera, playground, hedge, diffrent trees, pool pump, water pump, water tap.

Thanks

### Give us an example of it's usage.

*

**Comment by goyney** [comment]
You literally had to check off that you searched *and* would only request a single icon in the issue and then did not. Please read our issue form carefully before submitting another request.
