### ISSUE TITLE
Deliver rendered icon conditionally + URL field in RMB menu?

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#614]
If you try to use https://materialdesignicons.com/icon/book-multiple as an image here on Github for instance, it will create a link, but not show an image (because the request doesn't return `image/*`).

But what if the site checked the HTTP header and returned a rendered PNG if `Accept: ...` contains `image/png`, or maybe just `image/`? That way, a browser would load the site, but Github would be able to retrieve an image instead. Super easy to embed icons here (or elsewhere?), and no long load times as when you click a link like above until you see the actual icon.

In addition, it would be great if you could copy the icon URL from RMB menu (main page and icon modal dialog). Since setting clipboard data doesn't really work in browsers without Flash, I would go for a text field with the URL set as text, read-only and selecting the entire range on click. The user would then hit Ctrl+C to copy it.

Another approach could be to remove the permanent link link, and put a text field with URL there instead (so no need to click and copy from address bar). The icon can stay in front of the text field.

**Comment by Templarian** [comment]
Good idea, I'll think of something.

![Book Multiple](https://materialdesignicons.com/icon/book-multiple)

**Comment by CoDEmanX** [comment]
Nice what you did there :+1: 
I guess the icon url should return a rendered icon image at 24px. Different sizes could be achieve like:
`https://materialdesignicons.com/icon/:icon/:size`, `.../icon/book-multiple/96` for 96x96 px

**Comment by Templarian** [comment]
The base template will actually be automatic for consistency:

![github](https://cloud.githubusercontent.com/assets/338885/9291038/2edd11c0-4370-11e5-863a-ae39fd5a1482.png)

**Comment by Templarian** [comment]
After some testing their proxy server sends accept headers correctly so I'll use those to handle the code.

Just got back from the Chicago Airshow a few minutes ago, but will work on coding something up maybe later tonight. I'm working on getting the next font release out (going to be closing out a few of the issues that you've submitted before I get the release out). Lots of bootstrap helper CSS issues are getting closed out also.

**Comment by CoDEmanX** [comment]
Hm like 2 different sizes, a giant version with pixel grid + name in the bottom row? I like the idea, but it takes quite some space.

At the right bottom, I see a link icon. Do you mean to create image links with this? This would be confusing if you did `![desc](url)`, because you can click the image, but it will only load the local GitHub version (githubusercontent.com), not MDI :(

Looking forward to the overhaul!

**Comment by Templarian** [comment]
`[![icon name](url)](sameurl)` syntax.

**Comment by Templarian** [comment]
Done, Example:

[![Book](https://materialdesignicons.com/icon/book)](https://materialdesignicons.com/icon/book) [![Book Multiple](https://materialdesignicons.com/icon/book-multiple)](https://materialdesignicons.com/icon/book-multiple)  [![Beaker](https://materialdesignicons.com/icon/beaker)](https://materialdesignicons.com/icon/beaker)

**Comment by CoDEmanX** [comment]
Looks like embedding is broken, or is GitHub broken?

**Comment by Templarian** [comment]
Nah, it's github. It glitches once in a while. Might be my server timing out while it downloads the cache. They proxy every image themselves and cache it.

**Comment by CoDEmanX** [comment]
The glitches seem permanent, it sometimes works in the preview for the first icon the first time, but then completely breaks. Really weird... Maybe we miss some header, e.g. `Access-Control-Allow-Origin`? But doesn't explain why it works occasionally.

**Comment by CoDEmanX** [comment]
Hm, I have a feeling the browser might also play a role - above icon previews work in Chrome at the moment. Maybe because `Accept: image/webp` returns `image/png`? Or Github's asset server might not be consistent in its requests and send different Accept headers... How about the following Regex in an attempt to fix it? (tested in JavaScript only)

    /^image\/(webp|png|\*)(,|$)/

it will match the following:

    image/webp
    image/png,foo/bar,...
    image/*;q=0.8

but not

    image/webppp
    text/javascript,image/*
