### ISSUE TITLE
mirror with angular edges

### ISSUE THREAD

**Issue by ferropolis** [Templarian/MaterialDesign#6141]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

mdi have already an (let me say) "old style" mirror, but some bathrooms and maybe some other rooms have a modern mirror with angular edges. Woukld ne nice to find them in next time into mdi laybery. Thanks

PS: I used it in Home assistant.

### Give us an example of it's usage.

https://cdn.iconscout.com/icon/premium/png-256-thumb/hand-mirror-1-597408.png

**Comment by goyney** [comment]
[![mirror-variant](https://materialdesignicons.com/icon/mirror-variant)](https://materialdesignicons.com/icon/mirror-variant)[![mirror-rectangle](https://materialdesignicons.com/icon/mirror-rectangle)](https://materialdesignicons.com/icon/mirror-rectangle)

**Comment by ferropolis** [comment]
Thanks @goyney ♥
