### ISSUE TITLE
Hidden Folder

### ISSUE THREAD

**Issue by soi013** [Templarian/MaterialDesign#6142]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I develop a file viewer.
Therefore I need hidden-folder.
I would like to represent the file type (file-or-folder, hidden-not_hidden)  with an icon.

_                   |      File          |        Folder     
------------ | ------------- | -------------- 
Not Hidden  |   file              |     folder        
Hidden         |   file-hidden |  _**folder-hidden**_

### Give us an example of it's usage.

```html  
<div>
   <label>Hidden Folder: </label>
   <Icon path={mdiFolderHidden} size={1} />
</div> 
```

**Comment by goyney** [comment]
[![folder-hidden](https://materialdesignicons.com/icon/folder-hidden)](https://materialdesignicons.com/icon/folder-hidden)

**Comment by soi013** [comment]
Thank you for your rapid action!
