### ISSUE TITLE
about/  aboutus

### ISSUE THREAD

**Issue by abdullah4a** [Templarian/MaterialDesign#6143]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

for general purpose site 

### Give us an example of it's usage.

like home icon there, I'm not able to find out to find the about icon

**Comment by goyney** [comment]
We need much more information on what you expect this icon to look like. We have _several_ icons that could contextually solve your use case.

**Comment by abdullah4a** [comment]
Thanks Templarian/MaterialDesign
First of all it shouldn't be an info icon which are provided on site...
#about
Second thing is be more specific that shows about context, what will inside
of that that icon.. Like home icon as well

**Comment by goyney** [comment]
Can you share some example images to help us understand?

**Comment by abdullah4a** [comment]
Yeah sure let me see

**Comment by abdullah4a** [comment]
here is that icon from shutterstock.com
[image: image.png]
"
https://www.shutterstock.com/image-vector/question-user-icon-vector-filled-flat-754015246
"

Shows About User... we want for the web right.
so we can draw an image like
[image: image.png]or [image: image.png]or [image: image.png]
 Both from "question" or "exclamation mark", whatever  you want to use for
the icon
or instead both you can use "information" icon there
                           M.Abdullah Khan
<http://www.facebook.com/abdullahkhan4a>

**Comment by abdullah4a** [comment]
I think that could work

                           M.Abdullah Khan
<http://www.facebook.com/abdullahkhan4a>

**Comment by goyney** [comment]
We have plenty of icons that follow that pattern. Do none of these solve your use case?

<img width="370" alt="Screen Shot 2021-08-24 at 12 55 59 PM" src="https://user-images.githubusercontent.com/1015040/130665972-85d05bcd-806e-4a7a-a958-869167c9cd97.png">

**Comment by abdullah4a** [comment]
thanks, Templarian/MaterialDesign,
but these are not site-specific Icons.
as I've explained to you in the scenario, user question, question, info,
computer question doesn't meet the WebSite criteria... but let it be,
you're not getting the point. thanks anyways for the time.
                           M.Abdullah Khan
<http://www.facebook.com/abdullahkhan4a>

**Comment by goyney** [comment]
We'd like to help you, but we need to know what this criteria is. We don't know what your specific web site's criteria is. We have plenty of icons that could indicate an "about" section. Can you choose one that is closest to working for you and tell us what changes could be made to fit your use case?
