### ISSUE TITLE
How to truncate/purge mdi.svg while build?

### ISSUE THREAD

**Issue by EgoistDeveloper** [Templarian/MaterialDesign#6144]
### What is your question?

I am using [Angular Material - Material Design Icons](https://github.com/Templarian/MaterialDesign-Angular-Material) and I think mdi.svg file too heavy for production. Actually I am using 50-100 icon every project. SVG option better than webfont but after build mdi.svg coming with thousands icons.

I want to use only selected icons. Is there are truncate/purge (_like TailwindCSS build optimisation_) option? Or how can I do this?

**Comment by goyney** [comment]
Duplicate of #4913.
