### ISSUE TITLE
mdi-reset

### ISSUE THREAD

**Issue by piyushdolar** [Templarian/MaterialDesign#6146]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Right now icon pack have only `mdi-lock-reset` which contain lock inside that reset arrow but we need reset only without any sub icon in it.a 

### Give us an example of what this icon might look like.

You can check mdi-lock-reset, just remove lock from that icon, simple.

**Comment by goyney** [comment]
[![restore](https://materialdesignicons.com/icon/restore)](https://materialdesignicons.com/icon/restore)
