### ISSUE TITLE
battery-lock and battery-unlock

### ISSUE THREAD

**Issue by qnp** [Templarian/MaterialDesign#6147]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Share a preview of your contribution.

Hello there,
It is now a common use case to have a control for unlocking / locking batteries (such as for e-bikes, e-scooters, etc...)
I have two propositions :

## Aligned versions
![image](https://user-images.githubusercontent.com/6012554/130588738-3e9ab069-1441-4caa-a72a-42bf242af158.png)
![image](https://user-images.githubusercontent.com/6012554/130588797-0e427d15-1a25-4614-969b-2bc3cc6800a5.png)

## Slightly shifted versions
![image](https://user-images.githubusercontent.com/6012554/130588775-de450e3f-3c91-46a1-9a85-97f34bf24808.png)
![image](https://user-images.githubusercontent.com/6012554/130588821-f80e4504-ff49-47b2-b97a-02b79124e744.png)

What do you think ?

Best

### Upload the icon source.

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7037957/Archive.zip)

**Comment by goyney** [comment]
[![battery-lock](https://materialdesignicons.com/icon/battery-lock)](https://materialdesignicons.com/icon/battery-lock)[![battery-lock-open](https://materialdesignicons.com/icon/battery-lock-open)](https://materialdesignicons.com/icon/battery-lock-open)
