### ISSUE TITLE
emoji_people

### ISSUE THREAD

**Issue by msobiecki** [Templarian/MaterialDesign#6148]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

_"This repo also contains converted icons from Google's official icon set."_

But it seems to me that not all the icons are there. For example, this icon would be useful in my project and it is the only one that I have to "hardcode" because it is not in `@mdi/svg`

### Give us an example of what this icon might look like.

https://fonts.google.com/icons?icon.query=emoji_people

https://github.com/google/material-design-icons/blob/master/src/social/emoji_people/materialicons/24px.svg

**Comment by goyney** [comment]
We're going to rename our current `human-greeting` to `human-greeting-variant` and add this as our new `human-greeting`.

**Comment by goyney** [comment]
[![human-greeting](https://materialdesignicons.com/icon/human-greeting)](https://materialdesignicons.com/icon/human-greeting)[![human-greeting-variant](https://materialdesignicons.com/icon/human-greeting-variant)](https://materialdesignicons.com/icon/human-greeting-variant)
