### ISSUE TITLE
shield-sword, shield crown and outline variants

### ISSUE THREAD

**Issue by hanakin** [Templarian/MaterialDesign#6149]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/73081/130845424-f32c5814-f0fd-4877-be24-8c4cd5525673.png)
![image](https://user-images.githubusercontent.com/73081/130897141-8898b387-4958-4b87-a5cd-f0743a855fef.png)
![image](https://user-images.githubusercontent.com/73081/130845467-72566ad3-1329-48be-8c8c-334fe99a079a.png)
![image](https://user-images.githubusercontent.com/73081/130845512-065f1360-8527-4630-a368-bd1a2f61fa84.png)

### Upload the icon source.
[shield-sword-crown-icons.zip](https://github.com/Templarian/MaterialDesign/files/7067322/shield-sword-crown-icons.zip)

Attached are two shield variations modeled off the twitch and discord icons for admin and mod. There is possibly more room for other icons in this use case such as shield-wrench, shield diamond, shield-axe, shield-hammer used across various gaming apps but a lot of apps use these now to represent both these roles. There is sort of a lack of icons for admin and moderator in the library as a whole. At least this can fill part of the gap in relation to game-focused apps. We can add other icons for the other use cases mentioned as well.

https://help.twitch.tv/s/article/twitch-chat-badges-guide?language=en_US

**Comment by goyney** [comment]
[![shield-crown](https://materialdesignicons.com/icon/shield-crown)](https://materialdesignicons.com/icon/shield-crown)[![shield-crown-outline](https://materialdesignicons.com/icon/shield-crown-outline)](https://materialdesignicons.com/icon/shield-crown-outline)
[![shield-sword](https://materialdesignicons.com/icon/shield-sword)](https://materialdesignicons.com/icon/shield-sword)[![shield-sword-outline](https://materialdesignicons.com/icon/shield-sword-outline)](https://materialdesignicons.com/icon/shield-sword-outline)
