### ISSUE TITLE
Projector icon

### ISSUE THREAD

**Issue by KenRmk** [Templarian/MaterialDesign#615]
Winows 10 has nice icon of projector. Take a look here at E95D
http://modernicons.io/segoe-mdl2/cheatsheet/

**Comment by Templarian** [comment]
Always nice to see people using the cheat sheet (that will actually be the site of a future icon pack which should be started in about a month (also open source)).

**Comment by CoDEmanX** [comment]
A shot at projector and projector screen (are they called that?):

![projector](https://cloud.githubusercontent.com/assets/1309249/10836504/8b92fab4-7eae-11e5-896f-69e80af865ba.png) https://www.dropbox.com/s/867hiwouu56n1va/projector.svg?dl=0
![projector-screen](https://cloud.githubusercontent.com/assets/1309249/10836322/6567b53e-7eac-11e5-90ed-dd2bc98eb161.png) https://www.dropbox.com/s/qkacrsrvnwdyo9s/projector-screen.svg?dl=0

**Comment by Templarian** [comment]
[![projector](https://materialdesignicons.com/icon/projector)](https://materialdesignicons.com/icon/projector) [![projector-screen](https://materialdesignicons.com/icon/projector-screen)](https://materialdesignicons.com/icon/projector-screen)
