### ISSUE TITLE
radioactive-circle and outline 

### ISSUE THREAD

**Issue by hanakin** [Templarian/MaterialDesign#6152]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/73081/131139676-050f67a3-0cd6-4af0-9702-8ef7ea7a8a2d.png)
![image](https://user-images.githubusercontent.com/73081/131137523-5437805c-ee9e-4b13-8d66-f482420f29fe.png)

### Upload the icon source.
[radioactive-circles.zip](https://github.com/Templarian/MaterialDesign/files/7067412/radioactive-circles.zip)

Currently, there is https://materialdesignicons.com/icon/radioactive however it's more commonly seen and used as a circle. So suggesting a circle and outline variant to better represent the icon.

**Comment by goyney** [comment]
[![radioactive-circle](https://materialdesignicons.com/icon/radioactive-circle)](https://materialdesignicons.com/icon/radioactive-circle)[![radioactive-circle-outline](https://materialdesignicons.com/icon/radioactive-circle-outline)](https://materialdesignicons.com/icon/radioactive-circle-outline)

Added, though these kind of look like lifebuoys too.

[![lifebuoy](https://materialdesignicons.com/icon/lifebuoy)](https://materialdesignicons.com/icon/lifebuoy)
