### ISSUE TITLE
Gas burner

### ISSUE THREAD

**Issue by chemelli74** [Templarian/MaterialDesign#6153]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Follow-up from https://github.com/Templarian/MaterialDesign/issues/5516.

Looking forward for your feedback.
Thx,

Simone

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/57354320/111888667-e86af200-89de-11eb-8b8c-597ecdc178de.png)

![image](https://user-images.githubusercontent.com/57354320/111888660-dc7f3000-89de-11eb-8dcb-be7af437f32a.png)

![image](https://user-images.githubusercontent.com/57354320/111888686-1bad8100-89df-11eb-8ea2-9e68e0270463.png)

**Comment by chemelli74** [comment]
Any kind feedback ?

Thank you in advance,

Simone

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/151910381-4fe71aab-4adb-450a-9ae8-ccb0f7392944.png)

Not sure this one works, but 🤔

**Comment by Templarian** [comment]
![image](https://user-images.githubusercontent.com/338885/151912896-a051401e-156e-4ad9-aaa5-7771790c6f9b.png)

Scaled down the fire a little.
