### ISSUE TITLE
[automotive] Speed Limiter

### ISSUE THREAD

**Issue by iDoka** [Templarian/MaterialDesign#6154]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

A speed limiter is a governor used to limit the top speed of a vehicle. The icon might to be used on digital car dashboard.
In real environment icon very similar to already exists Cruise Control icon. 
I placed some examples bellow.

### Give us an example of what this icon might look like.

**Name**: car-limiter

**Examples**:

![Screenshot from 2021-08-22 23-09-37](https://user-images.githubusercontent.com/4820969/131536798-996d4e2e-9bf0-4645-ac5d-857d0f84e00f.png)

![Screenshot from 2021-08-29 17-28-18](https://user-images.githubusercontent.com/4820969/131536774-529a1e25-1bd6-4730-9e9f-405174812814.png)

![speed_limiter_symbols](https://user-images.githubusercontent.com/4820969/131536759-3e6d4ba1-24ca-432d-9f6f-42434e1b5b67.png)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/132919233-66cad814-21b9-479d-a571-380064fc0667.png)

[car-speed-limiter.svg.zip](https://github.com/Templarian/MaterialDesign/files/7146558/car-speed-limiter.svg.zip)

**Comment by goyney** [comment]
Added.
