### ISSUE TITLE
[automotive] rear fog icon

### ISSUE THREAD

**Issue by iDoka** [Templarian/MaterialDesign#6155]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Icon very similar to already exists `car-light-fog` icon.
The icon might to be used on digital car dashboard.

### Give us an example of what this icon might look like.

**Name**: `car-rear-fog`
**Examples**: 
Just make vertically mirror the `car-light-fog` icon.

![100px-Kontrollleuchte_Nebelschlussleuchte_black svg](https://user-images.githubusercontent.com/4820969/131537899-cd0f6840-3314-49c7-8393-086f7c40c589.png)

https://commons.wikimedia.org/wiki/File:Kontrollleuchte_Nebelschlussleuchte_black.svg

**Comment by goyney** [comment]
This one is going to be simply applying a mirror transform to `car-light-fog`. Rear fog lights aren't common enough for this to warrant its own icon. Thanks for the suggestion.
