### ISSUE TITLE
[automotive] Bend Lighting Failure

### ISSUE THREAD

**Issue by iDoka** [Templarian/MaterialDesign#6156]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Icon should mean that Bend Lighting system not working.
The icon might to be used on digital car dashboard.

### Give us an example of what this icon might look like.

**Name**: `car-bend-light-fail`
**Example**:

![3162344](https://user-images.githubusercontent.com/4820969/131538265-80f7d1dd-4229-482a-9640-e6b06f1458d3.png)

![3162347](https://user-images.githubusercontent.com/4820969/131538270-392811e8-36be-42bd-948d-e3f1783cc316.png)

https://commons.wikimedia.org/wiki/File:A32_Bend_lighting_malfunction.svg

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/132919636-d556cc86-d315-4209-b469-cbba830e1756.png)

[car-light-alert.svg.zip](https://github.com/Templarian/MaterialDesign/files/7146577/car-light-alert.svg.zip)

**Comment by goyney** [comment]
Added.
