### ISSUE TITLE
Site extremely slow, almost unusable

### ISSUE THREAD

**Issue by snimavat** [Templarian/MaterialDesign#6157]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

materialdesignicons.com is so slow  that it has become almost impossible to search for an icon.  and its not one time issue, i am facing this issue since several days

<img width="983" alt="Screenshot 2021-08-31 at 9 44 59 PM" src="https://user-images.githubusercontent.com/623295/131538961-39c9badb-714a-4d2d-9279-f3ecb63cc93f.png">

**Comment by goyney** [comment]
#5161.
