### ISSUE TITLE
[automotive] Engine pre-heater

### ISSUE THREAD

**Issue by iDoka** [Templarian/MaterialDesign#6158]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

 Engine pre-heater (electrical or autonomous) used to warm up combustion in order to minimize "white smoke". 
The icon might to be used on digital car dashboard.

### Give us an example of what this icon might look like.

**Name**: `car-pre-heat`
**Examples**:

![Diesel_pre-heat](https://user-images.githubusercontent.com/4820969/131539243-f826f110-17ae-4bd4-a093-2c39fa9155ca.png)

https://commons.wikimedia.org/wiki/File:Diesel_pre-heat.png

**Comment by goyney** [comment]
We've recently added this under a different name.

[![induction](https://materialdesignicons.com/icon/induction)](https://materialdesignicons.com/icon/induction)
