### ISSUE TITLE
[automotive] Brake malfunction icons' set

### ISSUE THREAD

**Issue by iDoka** [Templarian/MaterialDesign#6159]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

A set of Brake malfunction icons. These icons might to be used on digital car dashboard.

### Give us an example of what this icon might look like.

**Name**: `car-brake-overheat`
**Description**: Brake temperature over normal
**Example**:

![208px-B11_Brake_temperature_over_normal svg](https://user-images.githubusercontent.com/4820969/131540740-bdfe7686-4a0a-41b8-a7b5-5436c347a1c8.png)
https://commons.wikimedia.org/wiki/File:B11_Brake_temperature_over_normal.svg

----

**Name**: `car-brake-low-pressure`
**Description**: Brake system pressure low
**Example**:

![208px-B12_Brake_system_pressure_low svg](https://user-images.githubusercontent.com/4820969/131540773-40cb6429-a12a-4209-afe5-f54d421f23b1.png)
https://commons.wikimedia.org/wiki/File:B12_Brake_system_pressure_low.svg

----

**Name**: `car-brake-low-fluid`
**Description**: Brake fluid level low
**Example**:

![B13_Brake_fluid_level_low svg](https://user-images.githubusercontent.com/4820969/131540809-4b9953b0-f407-446a-b6a4-8b5bcfd3ea65.png)
https://commons.wikimedia.org/wiki/File:B13_Brake_fluid_level_low.svg

**Comment by MrGrigri** [comment]
Please break these down into individual request as it makes it easier to track.

**Comment by goyney** [comment]
Related: https://github.com/Templarian/MaterialDesign/issues/5944

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/132917979-02202f53-ec6d-4164-90b6-ee45b995c4c2.png)![image](https://user-images.githubusercontent.com/1015040/132917842-8bbda653-9670-4187-a191-dd71af649f36.png)
![image](https://user-images.githubusercontent.com/1015040/132917863-d02152e1-c343-43fd-a05c-caea5b924e80.png)![image](https://user-images.githubusercontent.com/1015040/132917879-d14ca1f6-0fa0-4e3c-abbf-e154cc7cc15c.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7146490/Archive.zip)

**Comment by goyney** [comment]
Added.
