### ISSUE TITLE
car-traction-control-off

### ISSUE THREAD

**Issue by iDoka** [Templarian/MaterialDesign#6160]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Main purpose of icon is reminder that user switched off ESP (Traction control) system.
The icon might to be used on digital car dashboard.

### Give us an example of what this icon might look like.

**Name**: `car-esp-off` or `car-traction-control-off`
**Example**: 
Just caption "ESP OFF" 

![Screenshot from 2021-08-31 19-35-16](https://user-images.githubusercontent.com/4820969/131542029-861a0657-b5d0-4d4c-b2ac-3a643907b3da.png)

![Screenshot from 2021-08-31 19-35-25](https://user-images.githubusercontent.com/4820969/131542028-150d5bc7-2cca-44a7-9467-cb083b59404a.png)

![zachemotkluchatmain](https://user-images.githubusercontent.com/4820969/131542024-8b3988be-5a96-40b6-9b11-ae1f7d8587fe.JPG)

https://commons.wikimedia.org/wiki/File:Kontrollleuchte_TC.svg

**Comment by goyney** [comment]
I don't know if this really works. You may need to work out another solution in your application.

![image](https://user-images.githubusercontent.com/1015040/132068967-dfd5cd50-477e-4265-8976-8d7ea357c660.png)

[car-traction-control.svg.zip](https://github.com/Templarian/MaterialDesign/files/7108672/car-traction-control.svg.zip)

**Comment by goyney** [comment]
This one doesn't work with our standard `off` modifier and the industry standard is to use the some text under the standard icon. We're gonna pass on this one and recommend you add some text near the icon as shown in your examples to indicate the system being off.
