### ISSUE TITLE
cash-fast

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6161]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Share a preview of your contribution.

cash-fast, instant-deposit, instant-transfer all work here.

<img width="755" alt="Screenshot 2021-08-31 at 10 44 15@2x" src="https://user-images.githubusercontent.com/2228347/131543014-963b98f0-cb6b-46e2-873e-4be06b9bc5a0.png">

### Upload the icon source.

[cash-fast.svg.zip](https://github.com/Templarian/MaterialDesign/files/7085497/cash-fast.svg.zip)

**Comment by goyney** [comment]
This is an acceptable place to break the artboard rule to get the appropriate spacing between the icon and the modifier. 😄 

[![cash-fast](https://materialdesignicons.com/icon/cash-fast)](https://materialdesignicons.com/icon/cash-fast)
