### ISSUE TITLE
[automotive] Washer Fluid Low

### ISSUE THREAD

**Issue by iDoka** [Templarian/MaterialDesign#6162]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Icon lights on when detected low fluid in windscreen's washer.
The icon might to be used on digital car dashboard.

### Give us an example of what this icon might look like.

**Name**: `car-washer-low-fluid`
**Example**:

![washer_fluid_low-1-512](https://user-images.githubusercontent.com/4820969/131542898-6aa3f154-5713-4e47-b742-c5c821688400.png)

![100px-Kontrollleuchte_Waschwasserstand_black svg](https://user-images.githubusercontent.com/4820969/131542960-e945cf6a-4c8c-42a3-981e-8cbcc734d78d.png)

https://commons.wikimedia.org/wiki/File:Kontrollleuchte_Waschwasserstand_black.svg

**Comment by goyney** [comment]
[![wiper-wash-alert](https://materialdesignicons.com/icon/wiper-wash-alert)](https://materialdesignicons.com/icon/wiper-wash-alert)
