### ISSUE TITLE
[automotive] Windscreen Washer

### ISSUE THREAD

**Issue by iDoka** [Templarian/MaterialDesign#6163]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Icon lights on when switched on the  Windscreen Washer (manual or automatic mode).
The icon might to be used on digital car dashboard.

### Give us an example of what this icon might look like.

**Name**: `car-windsceen-washer`
**Example**:
(best view in light github theme)

![340206-200](https://user-images.githubusercontent.com/4820969/131544811-c569de42-04d1-4238-9d4c-f6e20dec55ff.png)

![172177-200](https://user-images.githubusercontent.com/4820969/131544812-cf844da8-9891-49cb-afb7-5ba740cc8973.png)

![423-200](https://user-images.githubusercontent.com/4820969/131544814-dd0989d2-c991-4987-8031-c160d8365a0e.png)

**Comment by goyney** [comment]
This exists:

[![wiper-wash](https://materialdesignicons.com/icon/wiper-wash)](https://materialdesignicons.com/icon/wiper-wash)
