### ISSUE TITLE
Saídas de emergência

### ISSUE THREAD

**Issue by rmcabralrmcabral** [Templarian/MaterialDesign#6166]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Para o home assistant

### Give us an example of what this icon might look like.

![seg_esq](https://user-images.githubusercontent.com/74008973/131558086-d97dde21-1eb0-4387-86d4-04d0f496e146.png)
![Seg_baixo](https://user-images.githubusercontent.com/74008973/131558089-af069008-d5cd-4127-9293-c7d2611043b7.png)
![Seg_cima](https://user-images.githubusercontent.com/74008973/131558090-114e5b63-5d8e-444f-a8fd-ade84c9145c4.png)
![seg_dir](https://user-images.githubusercontent.com/74008973/131558091-0a875a15-432e-4313-9dc3-600911dac9c5.png)

**Comment by goyney** [comment]
[![exit-run](https://materialdesignicons.com/icon/exit-run)](https://materialdesignicons.com/icon/exit-run)
