### ISSUE TITLE
Solar Heat

### ISSUE THREAD

**Issue by horriblenoises** [Templarian/MaterialDesign#6167]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Solar panels used for heating water (pool or potable). 

Various other uses for this icon as well for desirable or undesirable sun heating aspects of life.

### Give us an example of what this icon might look like.

Grab your sun-wireless icon, remove the wireless, and slap a little thermometer on there.

**Comment by Circeus** [comment]
There is... already [sun-thermometer](https://github.com/Templarian/MaterialDesign/issues/6167)?

**Comment by goyney** [comment]
`sun-thermometer` was added today and will release in v6.3 in a few weeks.
