### ISSUE TITLE
leaf-circle & leaf-circle-outline

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6168]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

leaf-circle & leaf-circle-outline. Could also be aliased with organic & organic-outline. I would like to use this in our app to represent organic since the circle makes it feel more like a certification vs a literal leaf.

### Share a preview of your contribution.

<img width="1426" alt="Screenshot 2021-09-04 at 23 03 33@2x" src="https://user-images.githubusercontent.com/2228347/132115915-90f5e4d1-4c60-4983-9a52-5ab03e7cb781.png">

### Upload the icon source.

[leaf-circle.zip](https://github.com/Templarian/MaterialDesign/files/7110932/leaf-circle.zip)

**Comment by goyney** [comment]
[![leaf-circle](https://materialdesignicons.com/icon/leaf-circle)](https://materialdesignicons.com/icon/leaf-circle)[![leaf-circle-outline](https://materialdesignicons.com/icon/leaf-circle-outline)](https://materialdesignicons.com/icon/leaf-circle-outline)
