### ISSUE TITLE
rotate variant

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6169]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I find the rotate-left and rotate-right icons too complex with the dotted circle, almost indicating additional meaning. These are more standard and simple and would be suitable variants.

### Share a preview of your contribution.

<img width="1415" alt="Screenshot 2021-09-04 at 23 31 09@2x" src="https://user-images.githubusercontent.com/2228347/132116479-5ac107ce-6109-4049-9396-b62c4c92eb6b.png">

### Upload the icon source.

[rotate variants.zip](https://github.com/Templarian/MaterialDesign/files/7110964/rotate.variants.zip)

**Comment by goyney** [comment]
Could you use `reload` and `restore`? I'm not sure we need another variant of these. 🤔 

[![reload](https://materialdesignicons.com/icon/reload)](https://materialdesignicons.com/icon/reload)[![restore](https://materialdesignicons.com/icon/restore)](https://materialdesignicons.com/icon/restore)

**Comment by goyney** [comment]
We're going to pass on these since they are so similar. I've added aliases so they're easier to find in the future.
