### ISSUE TITLE
Missing icons?

### ISSUE THREAD

**Issue by SolusSoftworks** [Templarian/MaterialDesign#617]
I don't appear to have some of the icons in the 1.1.70 version (I was on 1.1.35 and definitely updated the version with bower). The icon I need is the Steam icon but it isn't in the files anywhere. 

Is this expected or should they be available in that version? They are listed on the icons page which to me suggests they SHOULD be in version 1.1.70.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history Looks like it was added right after the `1.1.70` version. The latest version is going out this week. Pretty large update with lots of fixes (IE8 support, CSS helpers, etc...). I'm targeting tomorrow right now for it to be complete.

**Comment by SolusSoftworks** [comment]
Perhaps it would be a good idea to differentiate the icons on the main page? I don't think icons which aren't in the current version should be displayed below a banner that says v1.1.70. The page could use some work in general to be honest. It would be nice to have categories like google's icon page so icons are easier to find.

**Comment by Templarian** [comment]
That would be a good idea, especially at the rate new icons are being added. There is a very large update in the works for all the new export functionality. Maybe after that this could be a story (it has been requested by a few people, not nearly as much as more export options though).

**Comment by Templarian** [comment]
Issue #618. There are a few large stories left on the board to go through before some of these minor features can be started (few months of work, so think long timeline).
