### ISSUE TITLE
credit-card-fast / credit-card-swipe

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6170]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Communicating immediate actions that happen with a credit card, like realtime transactions or speedy delivery. Doubles as a card swipe icon!

### Share a preview of your contribution.

<img width="798" alt="Screenshot 2021-09-04 at 23 48 14@2x" src="https://user-images.githubusercontent.com/2228347/132116827-7f26fbfb-5ec8-460f-a02e-3d322dcff10d.png">

### Upload the icon source.

[credit-card-fast.svg.zip](https://github.com/Templarian/MaterialDesign/files/7110974/credit-card-fast.svg.zip)

**Comment by goyney** [comment]
[![credit-card-fast](https://materialdesignicons.com/icon/credit-card-fast)](https://materialdesignicons.com/icon/credit-card-fast)[![credit-card-fast-outline](https://materialdesignicons.com/icon/credit-card-fast-outline)](https://materialdesignicons.com/icon/credit-card-fast-outline)
