### ISSUE TITLE
credit-card-chip-[outline]

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6171]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Chip style credit card, now prominent over the magstrip though perhaps less recognizable for the time being. Maybe the chip styles should be consolidated? The slightly rounded and left aligned chip is how modern credit cards appear these days. Similar to https://github.com/Templarian/MaterialDesign/issues/3895.

### Share a preview of your contribution.

<img width="1416" alt="Screenshot 2021-09-05 at 00 00 09@2x" src="https://user-images.githubusercontent.com/2228347/132117185-d31b1909-d76a-4b7a-9c4a-8ba0fc53703b.png">

### Upload the icon source.

[credit-card-chip.zip](https://github.com/Templarian/MaterialDesign/files/7110994/credit-card-chip.zip)

**Comment by goyney** [comment]
If we're going to add something like this, I think we should follow how we did it with `smart-card`.

[![smart-card](https://materialdesignicons.com/icon/smart-card)](https://materialdesignicons.com/icon/smart-card)

**Comment by jhil** [comment]
We could do that! But the chips on credit cards appear on the left. Maybe I
could use the same shape and vertical positioning, but remove the avatar
and flip the horizontal positioning.

**Comment by goyney** [comment]
Interesting, all 3 of my cards have the chips on the right.

**Comment by goyney** [comment]
[![credit-card-chip](https://materialdesignicons.com/icon/credit-card-chip)](https://materialdesignicons.com/icon/credit-card-chip)[![credit-card-chip-outline](https://materialdesignicons.com/icon/credit-card-chip-outline)](https://materialdesignicons.com/icon/credit-card-chip-outline)
