### ISSUE TITLE
[WIP] icc-chip

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6172]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

[WIP] This would be an icon to represent the integrated circuit chip in newer chip credit cards. Trouble is there are a lot of different patterns that can be used: https://en.wikipedia.org/wiki/Smart_card#Financial. Do we think it makes sense to abstract the pattern even though it won't be technically accurate?

### Share a preview of your contribution.

<img width="1552" alt="Screenshot 2021-09-05 at 00 13 28@2x" src="https://user-images.githubusercontent.com/2228347/132117467-0ed18845-edc4-4fe2-a9e8-95ea3ea4947f.png">

### Upload the icon source.

[Archive 2.zip](https://github.com/Templarian/MaterialDesign/files/7111010/Archive.2.zip)

**Comment by jhil** [comment]
Reference: ![image](https://user-images.githubusercontent.com/2228347/132117517-a84076f1-8f65-4b8f-adbb-8f6609daa1ef.png)

**Comment by goyney** [comment]
I like them and think they will work fine in the proper context. I actually prefer the unsymmetrical one as its more apparent what it should be.

**Comment by goyney** [comment]
I wonder if we should lessen the detail and adhere a bit more to Material here. Here's a comparison of your second (1dp lines) versus a version with 2dp lines:
![image](https://user-images.githubusercontent.com/1015040/133162305-c697846b-41b2-4df0-993f-7b2c4b12400b.png)![image](https://user-images.githubusercontent.com/1015040/133162378-00756302-a194-40b0-bdc1-bf2c7d9d58b1.png)

Is it still recognizable? Mainly looking at it at native size.

[icc-chip-3.svg.zip](https://github.com/Templarian/MaterialDesign/files/7157571/icc-chip-3.svg.zip)

**Comment by jhil** [comment]
I like your modification!

**Comment by goyney** [comment]
[![integrated-circuit-chip](https://materialdesignicons.com/icon/integrated-circuit-chip)](https://materialdesignicons.com/icon/integrated-circuit-chip)
