### ISSUE TITLE
Robot vacuum triangular variant

### ISSUE THREAD

**Issue by techillin** [Templarian/MaterialDesign#6174]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Robot vacuum triangular variant akin to Electrolux and Panasonic Models.

![electrolux-pi92-4anm-robotstoevsuger-pi92-4anm-41037-1](https://user-images.githubusercontent.com/48240363/132315048-37ab9bb0-0bb5-4e99-a695-b9fd20ebc1aa.jpg)
![panasonic rulo](https://user-images.githubusercontent.com/48240363/132315056-94057f59-0018-43c3-8af1-8641c2ec1bcc.png)

### Give us an example of what this icon might look like.

Pretty much lite robot-vacuum-variant but sharp angle at bottom.

**Comment by goyney** [comment]
I don't think we need yet another variant of a generic robot vacuum. Our current variant already is in this basic shape, and that should be enough to contextual indicate your model.

[![robot-vacuum-variant](https://materialdesignicons.com/icon/robot-vacuum-variant)](https://materialdesignicons.com/icon/robot-vacuum-variant)
