### ISSUE TITLE
Add `boehan` as a new contributor

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#6176]
Welcome @boehan, you have hit the minimum threshold of 5 unique icons contributed to Material Design Icons. For use to get your contributions properly attributed to you, please provide us the following information:

- Your Name (required)
- Your Twitter Handle (optional)
- Your Email (optional)
- A list of icons you've created.
    - We try to keep track the best we can, but we don't want to miss any!

Once we get a reply from you with this information, we'll reassign your contributions to you. Thank you for help MDI grow!

**Comment by goyney** [comment]
Icons we've tracked to you so far include:
- `fuel-cell`
- `fan-speed-auto`
- `lightbulb-off`
- `lightbulb-off-outline`
- `water-sync`
- `hydrogen-station`
- `hydro-power`
- `monitor-speaker`
- `monitor-speaker-off`
- `home-thermometer-outline`

**Comment by boehan** [comment]
Thank you!

> please provide us the following information:
> 
> * Your Name (required)

Hans Böhm
> * A list of icons you've created.


The above list should be complete

**Comment by goyney** [comment]
Just FYI, we're having some back-end issues right now, that's why this is taking longer than I anticipated. It'll get done though!

**Comment by goyney** [comment]
You've been added and icons have been reassigned. Any new contributions from you will automatically be contributed to you. Welcome to MDI! 😄
