### ISSUE TITLE
Waterfall Chart Icon

### ISSUE THREAD

**Issue by aggr0lite** [Templarian/MaterialDesign#6179]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'd like to use this icon to representing waterfall charts in a web application. By now, there is no chart icon which can be used for that fairly common chart type. 

### Give us an example of what this icon might look like.

![649046-200](https://user-images.githubusercontent.com/27857785/132464089-a16337b3-7bd1-4e8f-b824-534b26b5139b.png)

**Comment by goyney** [comment]
[![chart-waterfall](https://materialdesignicons.com/icon/chart-waterfall)](https://materialdesignicons.com/icon/chart-waterfall)
