### ISSUE TITLE
icon mdi-file-pdf disappeared

### ISSUE THREAD

**Issue by Pitpy** [Templarian/MaterialDesign#6180]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

can not find the icon anymore.

**Comment by zohaib089** [comment]
i think it has been changed to mdi-file-pdf-box

**Comment by goyney** [comment]
It's in the pinned issue: https://github.com/Templarian/MaterialDesign/issues/5409

Also, be sure to always check our [CHANGELOG](https://dev.materialdesignicons.com/changelog) before updating, especially on a major version change.
