### ISSUE TITLE
document XML

### ISSUE THREAD

**Issue by RyanAutocom** [Templarian/MaterialDesign#6181]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need an icon that represents an xml document

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/70279814/132512306-bbe91e5e-3ac4-4f88-a688-c931e38e2128.png)
![image](https://user-images.githubusercontent.com/70279814/132512390-74bd8182-ffb4-4474-be4d-3da0a6b92b7c.png)

**Comment by goyney** [comment]
This will need to follow our `file-*-box` pattern. In this case, `file-xml-box`.

**Comment by goyney** [comment]
I had to expand the box 1dp all the way around to fit the letters. If we add this, we should update the other `file-*-box` icons to have the same size box.

![image](https://user-images.githubusercontent.com/1015040/132915806-146a069c-6413-4a4d-9c16-7c1ead617ed3.png)

[file-xml-box.svg.zip](https://github.com/Templarian/MaterialDesign/files/7146409/file-xml-box.svg.zip)

**Comment by RyanAutocom** [comment]
because it is a document, it should have the file format with the word "xml" inside, or just the symbol "</>" inside.
A similar example is the "file-cancel" icon

**Comment by goyney** [comment]
The `file-*-box` icons for GIF, JPG, PDF, and PNG were updated. XML was added.
[![file-xml-box](https://materialdesignicons.com/icon/file-xml-box)](https://materialdesignicons.com/icon/file-xml-box)
