### ISSUE TITLE
eye-link

### ISSUE THREAD

**Issue by bethings** [Templarian/MaterialDesign#6182]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would like to use this icon to represent the video privacy settings that are available only from the link. Currently, there is no icon that could be used for this fairly common type of data display on the site.

### Give us an example of what this icon might look like.

![Монтажная область 1@3x](https://user-images.githubusercontent.com/48183077/132527420-c723acc6-5bf2-43e5-a1fd-e94ebf2818c6.png)

**Comment by goyney** [comment]
`link` is not one of our standard modifiers because it is so hard to do in the little modifier space. Since you're dealing with privacy settings, would `link-lock` work? In not, would `link-eye` work? That may be more feasible.

**Comment by bethings** [comment]
Perhaps you are right, however, such a symbol clearly reflects the essence of the action and thus builds an associative model of perception. (Eye = to watch, link) = View by link.

**Comment by Circeus** [comment]
Maybe an eye+arrow combination, as on `account-arrow-right`?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/132914279-03cc3dd1-b628-405c-97f1-1a95d7b06062.png)![image](https://user-images.githubusercontent.com/1015040/132914291-366e91cb-a6a5-46e6-b199-85425e2df998.png)
![image](https://user-images.githubusercontent.com/1015040/132914305-0f9093c3-593f-4e7d-9813-5ce95b4b6713.png)![image](https://user-images.githubusercontent.com/1015040/132914312-baeaea84-a657-4829-b1f4-bc6ea720541f.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7146344/Archive.zip)

**Comment by goyney** [comment]
Added.
