### ISSUE TITLE
mdi-file-pdf is disappeared

### ISSUE THREAD

**Issue by euberdeveloper** [Templarian/MaterialDesign#6185]
### What is your question?

The icon `mdi-file-pdf` is disappeared. I used it and it suddently disappeared in all my sites.

It was a beautiful icon, was it intended to remove it?

**Comment by Simran-B** [comment]
The icon was removed from the pack as announced over a year ago in https://github.com/Templarian/MaterialDesign/issues/5409, along with several other brand icons.

We use every major version (v6 in this case) to implement breaking changes such as this one. So check the changelog and announcements before you update your dependencies. 

Brand icons generally don't follow material design guidelines and modifying them is usually prohibited by the brand owner. https://simpleicons.org/ is a great alternative for brand icons.

**Comment by euberdeveloper** [comment]
Thank you. The icons were updated automatically by updating Vuetify

**Comment by dantman** [comment]
> Brand icons generally don't follow material design guidelines and modifying them is usually prohibited by the brand owner. https://simpleicons.org/ is a great alternative for brand icons.

In this instance the icon in question was Material's "File" icon with a PDF to indicate it's a PDF file. Like the [FileWord](https://materialdesignicons.com/icon/file-word) icon. SimpleIcons doesn't even have a PDF icon, much less a Material file icon with a PDF marking.

**Comment by Simran-B** [comment]
The PDF thingy is a brand icon by Adobe, unfortunately.
