### ISSUE TITLE
Volume knob

### ISSUE THREAD

**Issue by bushcraftparsons** [Templarian/MaterialDesign#6186]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To represent controls which a user can use to tweak sensors

### Give us an example of what this icon might look like.

![image](https://image.shutterstock.com/image-vector/volume-icon-jpg-260nw-394421485.jpg)

**Comment by goyney** [comment]
I don't know how I feel about this or how else to even name it.

![image](https://user-images.githubusercontent.com/1015040/132913612-9b21de9a-7e58-46ae-889c-ef77ac3dcc3e.png)

[knob.svg.zip](https://github.com/Templarian/MaterialDesign/files/7146241/knob.svg.zip)

**Comment by goyney** [comment]
[![knob](https://materialdesignicons.com/icon/knob)](https://materialdesignicons.com/icon/knob)
