### ISSUE TITLE
Website. Download not link to latest version in cdn

### ISSUE THREAD

**Issue by chispitaos** [Templarian/MaterialDesign#6187]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

When you press the blue Download icon at the header, it's shows you to use the version 5.4.55 instead of 6.1.95
This is an screenshot:

![image](https://user-images.githubusercontent.com/51212459/132682580-8c595ace-0182-4bea-97b9-795c9cb16c8f.png)

Thanks in advance!

**Comment by goyney** [comment]
@Templarian When you do the website update for v6, this would be something to hit.

**Comment by Templarian** [comment]
I'm going to try and get the site pushed with everything for 6.0 and the new CDN URL. Will use this to track it.

**Comment by Templarian** [comment]
Fixed.
