### ISSUE TITLE
Add many items

### ISSUE THREAD

**Issue by achebotarev** [Templarian/MaterialDesign#6188]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

It could be used as button icon for creation many similar items (by one action). Something like "+N" or some another variant.

### Give us an example of what this icon might look like.

![add-many](https://user-images.githubusercontent.com/17259898/132707968-29334dd9-2204-442e-a738-9967581646c6.png)

**Comment by goyney** [comment]
`plus-circle-multiple` should cover this.

[![plus-circle-multiple](https://materialdesignicons.com/icon/plus-circle-multiple)](https://materialdesignicons.com/icon/plus-circle-multiple)

**Comment by Templarian** [comment]
Agreed with closing this one.

In math a lowercase n is generally used not an uppercase. A symbol would probably make more sense.
