### ISSUE TITLE
No icons, vk/telegram, which used to be

### ISSUE THREAD

**Issue by CHADREX** [Templarian/MaterialDesign#6189]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

What was the problem, why was it removed?

**Comment by Simran-B** [comment]
The icon was removed from the pack as announced over a year ago in https://github.com/Templarian/MaterialDesign/issues/5409, along with several other brand icons.

We use every major version (v6 in this case) to implement breaking changes such as this one. So check the changelog and announcements before you update your dependencies. 

Brand icons generally don't follow material design guidelines and modifying them is usually prohibited by the brand owner. https://simpleicons.org/ is a great alternative for brand icons.
