### ISSUE TITLE
some other ways to access "material-design-icons"

### ISSUE THREAD

**Issue by rolandbln** [Templarian/MaterialDesign#619]
Hi,

sometimes I like to play around with jquery and web-icon-fonts.

if someone is interested : you can look :

http://rh-balingen.de/WEB-Icons/icons-js-1.htm
http://rh-balingen.de/WEB-Icons/icons-js-2.htm
http://rh-balingen.de/WEB-Icons/icons-json.htm

download : http://rh-balingen.de/WEB-Icons/web-icons.zip

**Comment by Templarian** [comment]
Cool project.

A feature is being worked on to generate a designer cheat sheet. Hopefully this will be integrated shortly, for now you can use the [preview.html](http://cdn.materialdesignicons.com/1.1.70/).

The designer cheat sheet will look closer to the [MDL2 cheatsheet](http://modernicons.io/segoe-mdl2/cheatsheet/) with copy to clipboard and other functionality. The designer font will not change character positions like the current bootstrap focused webfont.
