### ISSUE TITLE
'mdiCreditCardLockOutline' is not exported from '@mdi/js'

### ISSUE THREAD

**Issue by arkabase** [Templarian/MaterialDesign#6190]
### Where are you experiencing this bug?

@mdi/js

### What is the issue you are experiencing?

@mdi/js version 6.1.95

mdiCreditCardLockOutline is in the website list, but not in the package.
Can you please update the package ?

**Comment by goyney** [comment]
When looking at icon additions, please pay attention to the "Milestone." It will tell you in what version you can expect the icon to appear.

https://github.com/Templarian/MaterialDesign/issues/6011

**Comment by goyney** [comment]
Additionally, when you filed this issue, there was a disclaimer that said...

> If you see an icon on the site, but it is not in the latest release, this is not a bug. When new icons are added the library, they will immediately show on the website. However, a new release must happen before they will be available in our packages.
> See our history log for more information.
