### ISSUE TITLE
Alias for heading/header

### ISSUE THREAD

**Issue by sampl** [Templarian/MaterialDesign#6194]
### What icon would you like to alias?

format-header-1

### What alias(es) should be added to the above icon?

format-heading-1

**Comment by sampl** [comment]
It looks like all the HTML heading icons are labeled as “headers”.

Full list of icons to alias:
- format-header-1
- format-header-2
- format-header-3
- format-header-4
- format-header-5
- format-header-6
- format-header-decrease
- format-header-equal
- format-header-increase
- format-header-pound

It’s pretty common to swap these terms, but “heading” should definitely work in search.

Heading vs header:
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/header

**Comment by goyney** [comment]
All added.
