### ISSUE TITLE
coffee maker ready

### ISSUE THREAD

**Issue by dannybeltran** [Templarian/MaterialDesign#6195]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have an automation on home assistant in which every night I load my coffee maker with water and coffee, then scan a tag to have a boolean set to true... I want to show the coffee maker icon with a check so I can confirm at dashboard glance that the coffee maker is ready to prepare my coffee the next morning.. I tried to modify the existing svg icon located here in illustrator: https://icon-icons.com/icon/coffee-maker/136751
however no matter what I did it resulted in multiple path values... currently am using a module to load custom icons in home assistant but it only accepts one single path

this is the end result in case you need it

below is my svg code from illustrator in case you guys can help me fix it to only have one path (checked different sources on the web but did not figure out how to simplify it to one path)
`<svg id="mdi-coffee-maker" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20.97 22"><path d="M7,21V4H21V1H4A2,2,0,0,0,2,3V23H15.06a5.8,5.8,0,0,1-1.12-2Z" transform="translate(-2 -1)"/><polygon points="15 8 17 4 7 4 9 8 15 8"/><path d="M18,13.68V13h2v.53a5.66,5.66,0,0,1,2,.59V13a2,2,0,0,0-2-2H10v6c0,2.76,2.54,3,3.72,3a6.3,6.3,0,0,1-.05-.75A5.75,5.75,0,0,1,18,13.68Z" transform="translate(-2 -1)"/><polygon points="16.22 20.8 13.47 17.8 14.63 16.64 16.22 18.23 19.81 14.64 20.97 16.05 16.22 20.8"/></svg>`

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/46332852/133335884-cec97e39-9998-49b6-a7f7-695434a09cf8.png)

**Comment by goyney** [comment]
That is our old coffee maker, so obviously not using that one. Needed to move them over for the check not to make the icon indistinguishable.

![image](https://user-images.githubusercontent.com/1015040/133336557-6f93fbdc-d992-495a-bfcc-cc90012b741c.png)![image](https://user-images.githubusercontent.com/1015040/133336571-dc929d42-291e-4c08-a15b-03207f88de4b.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7165255/Archive.zip)

**Comment by dannybeltran** [comment]
oh that was quick, thanks a lot!!!
![image](https://user-images.githubusercontent.com/46332852/133338900-048bc252-532a-4f1a-a152-8545563dd132.png)

**Comment by goyney** [comment]
Please don't close issues. We'll close it once we've added it to the library.

**Comment by goyney** [comment]
[![coffee-maker-check](https://materialdesignicons.com/icon/coffee-maker-check)](https://materialdesignicons.com/icon/coffee-maker-check)[![coffee-maker-check-outline](https://materialdesignicons.com/icon/coffee-maker-check-outline)](https://materialdesignicons.com/icon/coffee-maker-check-outline)
