### ISSUE TITLE
Office Building Cog Outline

### ISSUE THREAD

**Issue by solomojo** [Templarian/MaterialDesign#6198]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Use for Company Settings, business settings,  office settings

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/5481983/133515469-99cc6a65-ef08-4c34-b5ee-d8f68376a0b9.png)

### Upload the icon source.

[office-building-cog-outline.zip](https://github.com/Templarian/MaterialDesign/files/7173519/office-building-cog-outline.zip)

**Comment by goyney** [comment]
[![office-building-cog-outline](https://materialdesignicons.com/icon/office-building-cog-outline)](https://materialdesignicons.com/icon/office-building-cog-outline)
