### ISSUE TITLE
Furigana

### ISSUE THREAD

**Issue by Sithdown** [Templarian/MaterialDesign#620]
![furiganaicon](https://cloud.githubusercontent.com/assets/430612/9367166/09bd34d4-46bc-11e5-97ed-ee3a59251036.png)

Japanese language uses small text over complex/obscure pictograms (kanjis) as an aid in the reading. Such an icon could be useful in contexts where that visual aid is necessary.

Furigana is sometimes signaled with the "ふ" symbol (the one at the top of the image) too.

**Comment by CoDEmanX** [comment]
So the above symbol could be used as "icon" for a toggle button to switch reading aids on/off?
Like `idiosyncrasy` <> `[id-ee-uh-sing-kruh-see]`?

**Comment by Sithdown** [comment]
@CoDEmanX Yes, that is the case. It would be awesome if someone could create an icon for the [&lt;ruby tag&gt;](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ruby) reading aid used in east asian languages like Chinese, Japanese and Korean.
It should be noted that the same aid is used in some English dictionaries for pronunciations too.

So, maybe an icon for phonetics /fəˈnɛtɪks/ could do? Or one for the latin alphabet and other for asian languages.

**Comment by Templarian** [comment]
Learn something new every day. Although I'm not really sure the best icon for this. It needs to be something recognizable in the small `24x24` size.

**Comment by Sithdown** [comment]
I've tried some approaches but everything is too complex for the small grid.

This is the poor result of my last approach:

![furigana_192](https://cloud.githubusercontent.com/assets/430612/9379146/87814548-4727-11e5-92d2-88cfaaf60fea.png) ![furigana_48px](https://cloud.githubusercontent.com/assets/430612/9379145/877adfc8-4727-11e5-83f7-d4ff96dfdeb6.png) ![furigana_24px](https://cloud.githubusercontent.com/assets/430612/9379144/87782fe4-4727-11e5-8c6d-73d2ac45293c.png)

Excuse my poor skills with vectorial images.

Maybe the best approach is to ditch completely the idea of a furigana icon and use a pronunciation icon, because latin script is simpler and something like /:ɪ/ could be made recognizable on 24x24.

**Comment by CoDEmanX** [comment]
If it's really about pronunciation, I like the following:

![pronouncing](http://www.chromein.com/public/crx/neomigpibafpboiknmijddgnncengfnm/icon.png)

**Comment by Sithdown** [comment]
That's a good approach, I like it!

Also, it kinda follows the style of the Material "hearing" icon: [![ic_hearing_black_24dp_1x](https://cloud.githubusercontent.com/assets/430612/9380042/d5b77c72-472d-11e5-9f77-6b2acd0a7b4d.png)](https://www.google.com/design/icons/#ic_hearing)

**Comment by CoDEmanX** [comment]
Can't remember for sure, but it guess it was something along a head with circle segments for "speaking":

![speak](https://d30y9cdsu7xlg0.cloudfront.net/png/177448-200.png)

**Comment by PeterShaggyNoble** [comment]
Would `voice` not work in that case?

**Comment by goyney** [comment]
Closing because `Needs More Information` was added quite a while ago with no new information. It looks like `voice` should solve this use case. If it does not and you have other suggestions on how to depict this, comment here and we'll reconsider. Thank you!

**Comment by JapanYoshi** [comment]
As a Japanese person, furigana is quite an important concept, and none of the above suggestions cover it. [Here's a good explanation of it for non-Japanese speakers.](https://legendsoflocalization.com/why-do-japanese-games-have-like-double-text/)

I'll follow up with an icon suggestion...

**Comment by goyney** [comment]
Sounds good!

**Comment by JapanYoshi** [comment]
![furigana_1x](https://user-images.githubusercontent.com/8707990/53704236-a659cc80-3e66-11e9-9d1b-bc9632adc012.png)
![furigana_2x](https://user-images.githubusercontent.com/8707990/53704238-a659cc80-3e66-11e9-9cf9-c75c9982d9e7.png)
![furigana_4x](https://user-images.githubusercontent.com/8707990/53704239-a659cc80-3e66-11e9-964a-20fe1be3783c.png)
@Sithdown How does this look?

**Comment by Sithdown** [comment]
> ![furigana_1x](https://user-images.githubusercontent.com/8707990/53704236-a659cc80-3e66-11e9-9d1b-bc9632adc012.png)
> ![furigana_2x](https://user-images.githubusercontent.com/8707990/53704238-a659cc80-3e66-11e9-9cf9-c75c9982d9e7.png)
> ![furigana_4x](https://user-images.githubusercontent.com/8707990/53704239-a659cc80-3e66-11e9-964a-20fe1be3783c.png)
> @Sithdown How does this look?

I think it looks ok! +1

**Comment by JapanYoshi** [comment]
SVG attached. Contains default `furigana` (`furigana-horizontal`) icon and `furigana-vertical` icons
[furigana.zip](https://github.com/Templarian/MaterialDesign/files/2923901/furigana.zip)

**Comment by goyney** [comment]
Here are the two icons created by @JapanYoshi with their paths merged down and grids realigned:
![image](https://user-images.githubusercontent.com/1015040/53704614-30188400-3dec-11e9-90a6-9afecf11e24f.png)![image](https://user-images.githubusercontent.com/1015040/53704617-36a6fb80-3dec-11e9-9757-83d7fe1aebc4.png)

[furigana.zip](https://github.com/Templarian/MaterialDesign/files/2923909/furigana.zip)

**Comment by Templarian** [comment]
@JapanYoshi Dumb question. Am I suppose to add both of these?

**Comment by JapanYoshi** [comment]
Yes, for horizontal and vertical writing.

**Comment by goyney** [comment]
[![furigana-horizontal](https://materialdesignicons.com/icon/furigana-horizontal)](https://materialdesignicons.com/icon/furigana-horizontal)[![furigana-vertical](https://materialdesignicons.com/icon/furigana-vertical)](https://materialdesignicons.com/icon/furigana-vertical)
