### ISSUE TITLE
Generic Crypto Currency Icon

### ISSUE THREAD

**Issue by peter-dolkens** [Templarian/MaterialDesign#6200]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This could be used as a placeholder where brand/token/coin-specific icons don't exist, or where aggregates are made.

I understand the reluctance to add each and every new token that springs up, but I think the concept of crypto itself certainly warrants wide-enough usage to benefit from a generic icon.

### Give us an example of what this icon might look like.

The general consensus seems to be a C with double lines through it similar to Bitcoin and Dollars:

* https://iconscout.com/icon/crypto-coin-2432529
* https://icon-icons.com/icon/generic-crypto-cryptocurrency-cryptocurrencies-cash-money-bank-payment/95038

![image](https://user-images.githubusercontent.com/469666/133905523-d39ef6e9-78c4-4d9f-92f7-004146312468.png)

**Comment by goyney** [comment]
I like the idea of this, but I'm not sure how we'd pull it off.

First, we already have a [generic currency](https://en.wikipedia.org/wiki/Currency_sign_(typography)) icon:
[![currency-sign](https://materialdesignicons.com/icon/currency-sign)](https://materialdesignicons.com/icon/currency-sign)

Second, there are many competing currencies that utilize the "c":
- ₵ is the Ghanian currency
- ₡ is the Costa Rican/Salvadorian currency
- ¢ is the cent, used in many countries

I think your best bet here is to use the generic symbol.
