### ISSUE TITLE
Icon missing 

### ISSUE THREAD

**Issue by Meet132** [Templarian/MaterialDesign#6201]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

The below file icon is missing in @mdi/font library .

**icon name** : mdi-file-pdf-outline

**Icon preview is below** : 

![pdf](https://user-images.githubusercontent.com/20553076/133959635-4436ff6f-7df3-4ef3-b373-8a9f9f698a84.PNG)

**Comment by Templarian** [comment]
Related: #5409

**Comment by goyney** [comment]
And more specifically: https://github.com/Templarian/MaterialDesign/issues/5797.

**Comment by Simran-B** [comment]
And a duplicate of https://github.com/Templarian/MaterialDesign/issues/6185
