### ISSUE TITLE
Four icons (listed at https://materialdesignicons.com/) are missing in latest 6.1.95

### ISSUE THREAD

**Issue by boltex** [Templarian/MaterialDesign#6203]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

I verified in my node_modules packages, even after upgrading to the latest version, those four icons are missing:

eye-arrow-left
eye-arrow-right
eye-arrow-left-outline
eye-arrow-right-outline

Anyways, thanks for your great product! :)

**Comment by boltex** [comment]
Although they are listed at https://materialdesignicons.com/ they also are missing from https://pictogrammers.github.io/@mdi/font/6.1.95/

**Comment by Templarian** [comment]
@boltex We have two releases lined up that will be going out shortly. These are in the upcoming release.

**Comment by goyney** [comment]
Please be sure to read the issue templates before submitting them. This is directly from the bug issue form:

> If you see an icon on the site, but it is not in the latest release, this is not a bug. When new icons are added the library, they will immediately show on the website. However, a new release must happen before they will be available in our packages.
> See our [history log](https://dev.materialdesignicons.com/history) for more information.

**Comment by boltex** [comment]
@goyney Not knowing exactly what the 'website' refers to, I thought it was a legit bug because they are listed at https://materialdesignicons.com/ but are missing from https://pictogrammers.github.io/@mdi/font/6.1.95/ 

Anyways, sorry for this irrelevant issue but maybe update the helper-text in issue to show what the website address is, or give a clickable link for what you consider is the 'website' listing all available icons. (Was not clear for me at first glance of reading this tip as there are more than one 'website' listing ) Thanks! :)

**Comment by goyney** [comment]
Good feedback, I've updated that template to be more specific. The [new website](https://github.com/Templarian/MaterialDesign/issues/5161) will include the version an icon was released in.
