### ISSUE TITLE
outline version of palette-swatch-variant

### ISSUE THREAD

**Issue by erdemyilmaz06** [Templarian/MaterialDesign#6204]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Thank you for publishing palette-swatch-variant icon. This could be outline version of it.

### Share a preview of your contribution.

![palette-swatch-variant-outline](https://user-images.githubusercontent.com/77012754/134195955-cf21f686-43ee-4f9c-b170-deff80e253e6.png)

### Upload the icon source.

[palette-swatch-variant-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/7204185/palette-swatch-variant-outline.svg.zip)

**Comment by goyney** [comment]
I attempted to make this last night as well. This icon does not lend itself to an outlined version because there is not enough room available for the hole in the palette card. This is one of those icons that will not have an outlined version.

**Comment by erdemyilmaz06** [comment]
Yes, I have figured out the same thing. I have draw a smaller hole but it doesn't look nice. OK, not a problem. Thank you so much.
