### ISSUE TITLE
Labeled Boxes - ON, OFF, LOW, MED, HIGH

### ISSUE THREAD

**Issue by almighty059** [Templarian/MaterialDesign#6205]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Button icons that clearly say their function instead of a lightbulb or slashed lightbulb.

### Give us an example of what this icon might look like.

![Screenshot 2021-09-24 022429](https://user-images.githubusercontent.com/63380298/134635143-d4c7cf9e-9529-424a-9927-114ddb83377a.png)

**Comment by JamesCoyle** [comment]
We avoid using text in icons where possible as it causes localization issues.

**Comment by almighty059** [comment]
@JamesCoyle I never thought of that but it definitely makes sense. Thanks.
