### ISSUE TITLE
Update `panorama-(horizontal|vertical|wide-angle)`

### ISSUE THREAD

**Issue by goyney** [Templarian/MaterialDesign#6207]
In this issue, we're going to rename three existing icons:

- [ ] `panorama-horizontal` -> `panorama-horizontal-outline`
- [ ] `panorama-vertical` -> `panorama-vertical-outline`
- [ ] `panorama-wide-angle` -> `panorama-horizontal-wide-angle`

And then we're going to re-add the filled versions from Google's stock set:

![image](https://user-images.githubusercontent.com/1015040/134689095-b5f718ed-998d-498a-9e26-4c0ba770ea74.png)![image](https://user-images.githubusercontent.com/1015040/134689130-83267c05-3a9b-4155-b031-53d360ebe6f9.png)
![image](https://user-images.githubusercontent.com/1015040/134689160-90ad26ec-89f7-43f9-a49a-9da9ed946e90.png)
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/7226236/Archive.zip)

**Comment by Templarian** [comment]
We usually only count removals as breaking changes. These replacements are generally fine.

**Comment by goyney** [comment]
Done.
