### ISSUE TITLE
ip-outline

### ISSUE THREAD

**Issue by frafon84sh** [Templarian/MaterialDesign#6208]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

i think it can be useful to have an "ip-outline" icon, for example to have a difference between internal and external ip information on my domotik HUB

### Give us an example of what this icon might look like.

same as "ip" icon with reverse color

**Comment by goyney** [comment]
[![ip-outline](https://materialdesignicons.com/icon/ip-outline)](https://materialdesignicons.com/icon/ip-outline)
