### ISSUE TITLE
Shield Unlocked Padlock

### ISSUE THREAD

**Issue by XplodingData** [Templarian/MaterialDesign#6209]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

displaying state of overall perimeter security, or for indicating if individual buildings are secured in home automation software (HA)

### Give us an example of what this icon might look like.

same as mdi:shield-lock and mdi:shield-lock-outline but with the padlock open, and the hasp turned 180degrees to the side (so it is visually more obvious that just deleting a few pixels from the existing icons)

**Comment by goyney** [comment]
[![shield-lock-open](https://materialdesignicons.com/icon/shield-lock-open)](https://materialdesignicons.com/icon/shield-lock-open)[![shield-lock-open-outline](https://materialdesignicons.com/icon/shield-lock-open-outline)](https://materialdesignicons.com/icon/shield-lock-open-outline)
