### ISSUE TITLE
stamper

### ISSUE THREAD

**Issue by juvs** [Templarian/MaterialDesign#621]
Icon like this... maybe without the letters, just some kind of line representing the text.

![](http://www.psdgraphics.com/wp-content/uploads/2009/09/authorized-stamp.gif)

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37561718-3ccde50c-2a2c-11e8-8718-4fd61d3e204f.png)![image](https://user-images.githubusercontent.com/18645219/37561724-4fcc97d4-2a2c-11e8-8686-fcc1798dcb68.png)
For the postage stamp I tried with 2px inner border but it left almost no space.

[Download link](https://github.com/Templarian/MaterialDesign/files/1822277/icons.zip)

**Comment by PeterShaggyNoble** [comment]
@Croutonix, could you add the postage stamp to #418 and we'll track it there?

**Comment by CoDEmanX** [comment]
Nova icon for comparison:

![image](https://user-images.githubusercontent.com/1309249/38769854-fce0b21e-4009-11e8-8c8b-27af735a7618.png)

@Croutonix How about rounding the corners of the bottom rectangle a little and moving it closer to the main shape?

**Comment by Croutonix** [comment]
Honestly I think it's better and follows more material guidelines as it is now.

**Comment by Templarian** [comment]
[![stamper](https://materialdesignicons.com/icon/stamper)](https://materialdesignicons.com/icon/stamper)
