### ISSUE TITLE
Vertical and Horizontal distributed alignment icons

### ISSUE THREAD

**Issue by Rodgath** [Templarian/MaterialDesign#6210]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The icons will be used in an app design tool. 

As you can see the icons highlighted in red squares in the attached screenshot. I am already using the other 6 alignment icons from MDI but the user has to click twice to center an element horizontally or vertically. It will be great to have the distributed icons added as well.

Many thanks.

### Give us an example of what this icon might look like.

![distributed-icons](https://user-images.githubusercontent.com/25994782/134942469-7111bc1f-ee76-48c6-bcf3-efa254af595e.png)

**Comment by goyney** [comment]
[![align-vertical-distribute](https://materialdesignicons.com/icon/align-vertical-distribute)](https://materialdesignicons.com/icon/align-vertical-distribute)[![align-horizontal-distribute](https://materialdesignicons.com/icon/align-horizontal-distribute)](https://materialdesignicons.com/icon/align-horizontal-distribute)

The other 6 icons have also been updated and reattributed to Google.
