### ISSUE TITLE
"North" icon

### ISSUE THREAD

**Issue by RoarGronmo** [Templarian/MaterialDesign#6213]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need an icon (actually user on a push-radio-button which toggles between "driving direction", "towards aim" (from-to direction), and "turn map north direction") to turn the map direction to north

### Give us an example of what this icon might look like.

I.E: An arrow pointing up with a capital "N" on the lower right side

![image](https://user-images.githubusercontent.com/11217296/135453026-d8e14b92-0d4d-4486-a127-e697a96c876d.png)

**Comment by goyney** [comment]
This is most likely going to be a no because of language conflicts. We have plenty of arrows, navigation arrows, and the alphabet if you would like to craft your own icon.

**Comment by RoarGronmo** [comment]
I thought N for North was common for most languages...

**Comment by goyney** [comment]
It is not. For example, in Croatian it is "sjeverni". Regardless, adding one of the four cardinal directions means we would need to add all (and likely the 4 in-betweens), none of which translate properly. I recommend either using the letters from our alphabet or an arrow with contextual text accompanying it.
