### ISSUE TITLE
bed-calculator

### ISSUE THREAD

**Issue by howardae** [Templarian/MaterialDesign#6214]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Denotes a function to compute length of stay. Immediate use case relates to medical field. 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/91559642/135540173-6239bc25-4541-4f2f-81e2-0617dd6482ae.png)

### Upload the icon source.

[bed-calculator.zip](https://github.com/Templarian/MaterialDesign/files/7262917/bed-calculator.zip)

**Comment by goyney** [comment]
I see what you're going for here with the calculator, however that symbol is used to denote a mathematical function, not a function of time. The more appropriate modifier would be to use a clock.

It's a bit crowded, but it might be acceptable.
![image](https://user-images.githubusercontent.com/1015040/135953789-8764dc70-f40c-4dcd-b4d4-6e38e6281d12.png)
[bed-clock.svg.zip](https://github.com/Templarian/MaterialDesign/files/7282461/bed-clock.svg.zip)

**Comment by howardae** [comment]
Yeah, The other option I was messing with was essentially that, though I wasn't able to get it positioned correctly in preview generator.
![image](https://user-images.githubusercontent.com/91559642/136035950-d9caa73d-4a65-4594-850e-49e1082b2aa9.png)

**Comment by goyney** [comment]
[![bed-clock](https://materialdesignicons.com/icon/bed-clock)](https://materialdesignicons.com/icon/bed-clock)
