### ISSUE TITLE
arrow-[bottom|top]-[left-right]-box

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#6215]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

These can be used to point in diagonal directions, but in a box.

### Give us an example of what this icon might look like.

Similar to the existing `arrow-left-bold-box`,  `arrow-left-bold-box`, and `arrow-left-bold-box`.

**Comment by goyney** [comment]
All added.
