### ISSUE TITLE
Misting System

### ISSUE THREAD

**Issue by alexdw369** [Templarian/MaterialDesign#6216]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have a high-pressure misting system on a zigbee switch.  I'd like something more representative than a water droplet or the several variants of a water droplet

### Give us an example of what this icon might look like.

Should be pretty easy to imagine.  Perhaps a mist nozzle at the top of the image, with a conical spray pattern below.

**Comment by alexdw369** [comment]
Yes, but with the nozzle oriented 180° from the sprinkler, and with the
spray pointing downward out of the tip of the nozzle

**Comment by goyney** [comment]
I think we can hit two use cases with this request. Would something like this satisfy your use case?

![image](https://user-images.githubusercontent.com/1015040/135952797-aa0c5499-92de-4ecf-b712-fb05280c47a9.png)
[sprinkler.svg.zip](https://github.com/Templarian/MaterialDesign/files/7282435/sprinkler.svg.zip)

**Comment by alexdw369** [comment]
Yes!

**Comment by goyney** [comment]
[![sprinkler-fire](https://materialdesignicons.com/icon/sprinkler-fire)](https://materialdesignicons.com/icon/sprinkler-fire)
