### ISSUE TITLE
Sonic Pi icon

### ISSUE THREAD

**Issue by seanfroste** [Templarian/MaterialDesign#6217]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'd use this icon for sonic pi scripts. I have seen a minimal logo idea in an issue on the the [sonic pi github page](https://github.com/sonic-pi-net/sonic-pi). I would like it to be added for use in VSCode's material icon extension. Sonic Pi uses .pi and .pibook files, which are simply cellular notebooks, similar to jupyter notebooks in python. As per the response to the issue, the author rejected the logo idea because he already had a well established icon for the software. I would love a cleaner, more minimal icon for files.

### Give us an example of what this icon might look like.

Please find attached the icon idea that was posted on the sonic pi github in [this issue](https://github.com/sonic-pi-net/sonic-pi/issues/1880#issue-314518295).

**Comment by goyney** [comment]
We won't be adding this icon to the Material Design Icons library. Please see our announcement here: https://github.com/Templarian/MaterialDesign/issues/6602

You may open a request to add this icon on our new Brand Icon Library we've started here: https://github.com/Pictogrammers/brand-icons/issues/new/choose

Thanks you.
