### ISSUE TITLE
code-tags-off

### ISSUE THREAD

**Issue by hgiesel** [Templarian/MaterialDesign#6219]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

We maintain a WYSIWYG editor, with an optional mode where you can edit the HTML directly.
For turning on this HTML mode, we use the [code-tags](https://materialdesignicons.com/icon/code-tags) icon. We would use "code-tags-off" to signalize turning off the HTML editor.

### Give us an example of what this icon might look like.

Just like [code-tags](https://materialdesignicons.com/icon/code-tags), but with a diagonal strikethrough.

**Comment by goyney** [comment]
I don't think this works. Perhaps there is another way to indicate this.
![image](https://user-images.githubusercontent.com/1015040/135952990-1c5eac9d-0b6a-4048-9204-a10e83db6e66.png)

**Comment by felipeqq2** [comment]
I think it would be more user-friendly to show a toggle button, changing its background colour depending on what's turned on/off. This icon idea definitely does not pass the message

**Comment by goyney** [comment]
Yeah, this doesn't work in an `-off` variant, so we're gonna close this one out. Thanks for the suggestion.
