### ISSUE TITLE
Math symbols

### ISSUE THREAD

**Issue by ketangoyani** [Templarian/MaterialDesign#622]
We can add multiple mathematical icons. eg: fraction, factorial, sigma, integration etc...

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/sigma (exists already)

Can you please link examples of each of the missing icons so the contributors can more easily add them. Thanks.

**Comment by ketangoyani** [comment]
Like this,
![screenshot-2015-08-21-03 32 11](https://cloud.githubusercontent.com/assets/11384794/9403747/b54acce8-47b7-11e5-9c52-071654a2ff4d.png)

**Comment by RobertHerhold** [comment]
These would also be much appreciated:
* greater than
* less than
* greater than or equal to
* less than or equal to

**Comment by CoDEmanX** [comment]
True, we only have boxed versions of them.

**Comment by goyney** [comment]
We have many math-related icons now: https://materialdesignicons.com/tag/math

It looks like there are a few more we could add:
- [ ] Integral (∫)
- [ ] Approximately equal (≈)
- [ ] Plus-minus (±)
- [ ] Double vertical bars (||)
- [ ] Generic power icon (a<sup>b</sup>)
- [ ] Division slash, Fraction separator (/)

**Comment by PeterShaggyNoble** [comment]
We have a `plus-minus` and `exponent` icons already.

**Comment by goyney** [comment]
Thanks @PeterShaggyNoble, must have missed `plus-minus` somehow. I also aliased `exponent*` with `power`. Those two icons (and their box variants) have been added to the `Math` tag.

**Comment by goyney** [comment]
This should be enough to close this issue:

![image](https://user-images.githubusercontent.com/1015040/51007832-1870fd80-1517-11e9-9652-0ec97441b49d.png)![image](https://user-images.githubusercontent.com/1015040/51007834-1e66de80-1517-11e9-896d-e5f72aa083fa.png)
![image](https://user-images.githubusercontent.com/1015040/51008144-81a54080-1518-11e9-8188-2db6c443c706.png)![image](https://user-images.githubusercontent.com/1015040/51007859-3b9bad00-1517-11e9-861b-0f459e06bf33.png)
![image](https://user-images.githubusercontent.com/1015040/51007875-4b1af600-1517-11e9-95f1-bed2bd837c3c.png)![image](https://user-images.githubusercontent.com/1015040/51008108-56225600-1518-11e9-82b0-2bf2fea88bc8.png)
![image](https://user-images.githubusercontent.com/1015040/51007898-64bc3d80-1517-11e9-8661-9d269364c107.png)![image](https://user-images.githubusercontent.com/1015040/51007906-6ab21e80-1517-11e9-9fa3-53018c5e5b28.png)

[maths.zip](https://github.com/Templarian/MaterialDesign/files/2747750/maths.zip)

---

Let's also alias:

- `division-slash` -> `forward-slash`
- `math-norm` -> `code-or`
- `math-norm-box` -> `code-or-box`

**Comment by goyney** [comment]
[![approximately-equal](https://materialdesignicons.com/icon/approximately-equal)](https://materialdesignicons.com/icon/approximately-equal)[![approximately-equal-box](https://materialdesignicons.com/icon/approximately-equal-box)](https://materialdesignicons.com/icon/approximately-equal-box)
[![slash-forward](https://materialdesignicons.com/icon/slash-forward)](https://materialdesignicons.com/icon/slash-forward)[![slash-forward-box](https://materialdesignicons.com/icon/slash-forward-box)](https://materialdesignicons.com/icon/slash-forward-box)
[![math-integral](https://materialdesignicons.com/icon/math-integral)](https://materialdesignicons.com/icon/math-integral)[![math-integral-box](https://materialdesignicons.com/icon/math-integral-box)](https://materialdesignicons.com/icon/math-integral-box)
[![math-norm](https://materialdesignicons.com/icon/math-norm)](https://materialdesignicons.com/icon/math-norm)[![math-norm-box](https://materialdesignicons.com/icon/math-norm-box)](https://materialdesignicons.com/icon/math-norm-box)
