### ISSUE TITLE
Request a mask icon

### ISSUE THREAD

**Issue by kalpasameera** [Templarian/MaterialDesign#6220]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I want to use this in my project. 

### Give us an example of what this icon might look like.

![20211005_085332](https://user-images.githubusercontent.com/19950660/135956483-72bdc90d-106f-4906-acd9-60f04f6b2fef.jpg)
I attached my icon in here. This is similar to mask.

**Comment by goyney** [comment]
> ### Before submitting a new icon request, please confirm the following:
> * [x]  I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.

[![face-mask](https://materialdesignicons.com/icon/face-mask)](https://materialdesignicons.com/icon/face-mask)[![face-mask-outline](https://materialdesignicons.com/icon/face-mask-outline)](https://materialdesignicons.com/icon/face-mask-outline)
