### ISSUE TITLE
Frigo Truck Icon

### ISSUE THREAD

**Issue by erdemyilmaz06** [Templarian/MaterialDesign#6221]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Frigo Truck icon. These trucks carry fresh and cool food. User can choose delivery method of ordered food...

### Share a preview of your contribution.

![truck-frigo](https://user-images.githubusercontent.com/77012754/136047175-fddf1755-0c7a-40f9-8071-d23797ad19db.png)

### Upload the icon source.

[truck-frigo.zip](https://github.com/Templarian/MaterialDesign/files/7286887/truck-frigo.zip)

**Comment by goyney** [comment]
Please use the [preview generator](https://dev.materialdesignicons.com/contribute/github) to share of preview of your contribution.

**Comment by Simran-B** [comment]
Is Frigo a refrigerated truck brand or a service that delivers cooled/frozen food? Either way, it shouldn't be used in the icon name as this is highly dependent on the cultural context. The most popular delivery service for frozen food in Germany is Bofrost for instance.

**Comment by erdemyilmaz06** [comment]
<img width="330" alt="Screen Shot 2021-10-12 at 12 21 44" src="https://user-images.githubusercontent.com/77012754/136929172-c0356a63-165b-445e-875c-1bfe32fc4e27.png">

Sorry Goyney, I use Mac and preview generator doesn't allow me to copy image by right click. But here is a screenshot.

**Comment by erdemyilmaz06** [comment]
> Is Frigo a refrigerated truck brand or a service that delivers cooled/frozen food? Either way, it shouldn't be used in the icon name as this is highly dependent on the cultural context. The most popular delivery service for frozen food in Germany is Bofrost for instance.

Hi Simran-B, "Frigo" is not a brand. I think it is an Italian word. It is widely used for refrigerated/freezer transport business. We can call "refrigerated-truck" maybe...

**Comment by goyney** [comment]
[![truck-snowflake](https://materialdesignicons.com/icon/truck-snowflake)](https://materialdesignicons.com/icon/truck-snowflake)

If you want to open an issue for the rename, go ahead and mark it for `v7`.

**Comment by Simran-B** [comment]
What about the cooling unit above the driver compartment though? Did you remove it on purpose?

**Comment by goyney** [comment]
Yes, it does not match the base `truck` icon and doesn't add anything important to the icon that the snowflake doesn't depict.
