### ISSUE TITLE
Swimming pool temperature

### ISSUE THREAD

**Issue by PlusPlus-ua** [Templarian/MaterialDesign#6224]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

An icon could be used in Home Assistant as the icon for a temperature sensor placed in a swimming pool.

### Give us an example of what this icon might look like.

It might be a mix of https://materialdesignicons.com/icon/pool and https://materialdesignicons.com/icon/thermometer or https://materialdesignicons.com/icon/sun-thermometer-outline icons. 

Something like this:
https://www.iconfinder.com/icons/7090631/swimming_water_temperature_summertime_pool_icon

**Comment by dloeckx** [comment]
Would https://materialdesignicons.com/icon/coolant-temperature be an option?

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/159059155-2cf7c977-a8c4-4b26-abf9-0ac86cb71759.png)
[pool-thermometer.svg.zip](https://github.com/Templarian/MaterialDesign/files/8306713/pool-thermometer.svg.zip)

**Comment by goyney** [comment]
Added.
