### ISSUE TITLE
Drone variants

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6225]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would like to use drone variants for observastion project such as wind turbine check system. 

### Give us an example of what this icon might look like.

Drone with signal
drone with status (success, alert, info, warning, etc)
drone with clock (clock slice 6, 3, etc)

**Comment by goyney** [comment]
The `drone` icon currently takes up the entire artboard, so without major rework, most of these might be hard to do.

- "Drone with signal" - what does this mean?
- We may be able to add `check` (success) using our standard cutout. We'll have to check on `alert` (warning). We do not have a standard "info" variation as the base icon is more than sufficient in the majority of cases.
- We may be able to add the clock variant, but whatever you mean by "slice 6, 3, etc." is not likely to happen. What are you trying to accomplish there?

**Comment by goyney** [comment]
It's been a week with no further information, so going to close this for now. If you wish to provide more information, please feel free to comment back here so we can reconsider this issue. Thanks for your suggestion.
