### ISSUE TITLE
Transport Costs / Shipping Rates

### ISSUE THREAD

**Issue by phillipa-llama** [Templarian/MaterialDesign#6227]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To indicate Transport Costs / Shipping Rates

### Give us an example of what this icon might look like.

I logged this previously in #6223 which was closed (and I didn't seem able to re-open it and continue the discussion there).
I was basing my example of what it might look like on what I had found online.

I don't know what you are using to indicate money / currency instead of the dollar symbol which was used previously (and I totally understand moving away from that), but I still think there is a use case for this icon, whatever the money / currency indicator going forward is going to be. Unfortunately all google searches for currency / money / cost icons still use the dollar symbol heavily so I don't really know what to suggest.

Unfortunately I don't think enough users are familiar with the non-specific currency symbol yet:
![image](https://user-images.githubusercontent.com/57439980/136373215-b0560d76-be4a-4e57-bf9b-9c8300cb5193.png)

I tried a few options like the cash-100 combined with the truck, but it mght be too detailed for the smaller versions?

![image](https://user-images.githubusercontent.com/57439980/136372640-05ea7fd4-896a-41b4-81c0-9944f47ec291.png)

![image](https://user-images.githubusercontent.com/57439980/136372666-0a965fcf-2b15-4886-ac3d-da02b4f9b187.png)

![shipping-rate-02](https://user-images.githubusercontent.com/57439980/136372843-dc0476d7-edfd-47eb-94b9-068c5ed2ef87.png)

There doesn't seem to be a money bag icon currently and I don't think the coin or piggy bank icons would work. I think the credit card also probably wouldn't work. And the cash register inside the truck body also probably would not be clear in smaller versions.

I tried to combine the price tag & truck icon as well but also not sure that it would work for smaller versions:
![shipping-rate-03](https://user-images.githubusercontent.com/57439980/136374966-f594f57a-ad1f-4190-9d4d-65017fdfc266.png)

Open to suggestions.

**Comment by goyney** [comment]
Under normal circumstances, the `$` would be the best option here, but it's a rule we're not willing to break. I feel that a more generic money icon would be best for your use case anyways; shipping isn't always done by a truck.
