### ISSUE TITLE
Icon for icicle lights

### ISSUE THREAD

**Issue by mjitkop** [Templarian/MaterialDesign#6229]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In Home Assistant, I have a button to turn icicle lights on and off. Right now, the icon for the button is the default "flash" icon. It would be nice to have an icon that resembles icicle lights.

### Give us an example of what this icon might look like.

[Example of icicle lights on 1000bulbs.com](https://5fc98fa113f6897cea53-06dfa63be377ed632ae798753ae0fb3f.ssl.cf2.rackcdn.com/product_images/files/000/021/784/legacy_product_detail_large/7971_330508961d1f2994f2da9a94936a52beb87bec32_original.jpg?1429821786)

**Comment by goyney** [comment]
`string-lights` already exists. I don't feel we need another variant of them. Also, this feels hard to do in the space available, considering we already broke the artboard for `string-lights`.

[![string-lights](https://materialdesignicons.com/icon/string-lights)](https://materialdesignicons.com/icon/string-lights)
