### ISSUE TITLE
Ban Icon

### ISSUE THREAD

**Issue by MilosMosovsky** [Templarian/MaterialDesign#623]
Can you please make icon like this?

http://fortawesome.github.io/Font-Awesome/icon/ban/

the is icon named block-helper , but it looks larger then other icons.  There should be ban icon with circle large as mdi-checkbox-blank-circle-outline , thanks!

**Comment by ketangoyani** [comment]
![screenshot-2015-08-21-03 32 11](https://cloud.githubusercontent.com/assets/11384794/9403548/07dad96e-47b6-11e5-9eac-489f37dd9a60.png)

**Comment by MilosMosovsky** [comment]
@ketangoyani  i dont get point of your image. why are you posting math equations icons here?

**Comment by ketangoyani** [comment]
sorry guys by mistake I posted this not meant for this group.

**Comment by PeterShaggyNoble** [comment]
![](https://materialdesignicons.com/icon/cancel)
