### ISSUE TITLE
Restaurant table & chairs

### ISSUE THREAD

**Issue by pcs980** [Templarian/MaterialDesign#624]
I suggest a restaurant table icon like below or better:

https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/128/table.png

**Comment by GonZOO82** [comment]
+1

**Comment by MrGrigri** [comment]
Idk how I feel about this one...but here's my attempt.

[![table-chair](https://user-images.githubusercontent.com/4528551/52226259-aff11400-2869-11e9-9af3-7316b93d8494.png)](https://github.com/Templarian/MaterialDesign/files/2829171/table-chair.zip)

**Comment by goyney** [comment]
[![table-chair](https://materialdesignicons.com/icon/table-chair)](https://materialdesignicons.com/icon/table-chair)
