### ISSUE TITLE
Icon Request: New File

### ISSUE THREAD

**Issue by SwaroopSomanna** [Templarian/MaterialDesign#6247]
Example:
![173-1737013_new-file-icon-png-transparent-png.png](https://user-images.githubusercontent.com/32904377/137615279-2d737729-ab29-4c8f-acda-21a6d5e8d3b4.png)

The icon can either have a plus sign or star sign (✴️) at the lower right corner of the file symbol.

**Comment by goyney** [comment]
You edited away the required issue template that required you to agree that you searched the library.

We have both the plus and star versions of file. **Do not** remove the issue template.
