### ISSUE TITLE
Permalink Website Bug

### ISSUE THREAD

**Issue by danielhickman** [Templarian/MaterialDesign#625]
https://materialdesignicons.com/icon/account (or any permalink) shows only an image if not opened from materialdesignicons.com which makes it hard to share the icons.
![image](https://cloud.githubusercontent.com/assets/5341898/9425325/44076e5a-48c1-11e5-811d-a69f757b69db.png)

**Comment by CoDEmanX** [comment]
That looks like #614 overdoes it...

**Comment by danielhickman** [comment]
Couldn't the icon modal show two permalinks, one for the modal and one for the image? Or am I misunderstanding what that does?

**Comment by Templarian** [comment]
I'm can't seem to reproduce the issue on my machine. Hmm... looking into it.

**Comment by Templarian** [comment]
So, yea, not sure why it is showing that image. I have code that checks for the accept header and returns an image. The permalink should be going to the website not an image since the browser shouldn't be sending the header (only github's image cache in the comment sends the header).

**Comment by CoDEmanX** [comment]
What is it exactly that you check? If `Accept:` contains `image/`? It's possible that browsers send this too I guess. Maybe return an image only if it starts like that?

My Chrome and Chrome for Android send this to a local test server:

    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",

Whatever format `image/webp` is, Chrome accepts it and a test if "image/" is contained isn't enough. Firefox and IE do not send something similar.

IIRC, Github's asset proxy sent `image/png,image/*,...` last week, but today it sends the following:

    accept: 'image/webp,image/*,*/*;q=0.8',

I guess you could check whether the accept header starts with `image/`. Or if `image/png` or `image/*` is contained, but it's probably less safe.

**Comment by Templarian** [comment]
Fixed. Thanks @CoDEmanX. I changed the regex slightly to: `/^image\/webp`.

Test:
[![account-box](https://materialdesignicons.com/icon/account-box)](https://materialdesignicons.com/icon/account-box)

**Comment by danielhickman** [comment]
:+1: Thanks guys that was quick.
