### ISSUE TITLE
Cannot find issue template

### ISSUE THREAD

**Issue by SwaroopSomanna** [Templarian/MaterialDesign#6250]
I'm using GitHub app for Android.
Recently I had created an issue by clicking on issues button and then clicking on the add issue button and I couldn't find any issue template.
![Screenshot_20211017-172701.png](https://user-images.githubusercontent.com/32904377/137626271-d1b232d6-0e5b-4a7d-a1d4-f2be959e4fd4.png)

**Comment by Templarian** [comment]
Unfortunately the GitHub mobile app does not support issue template forms yet it seems. Please use a desktop.
