### ISSUE TITLE
mdiSendError

### ISSUE THREAD

**Issue by GaborTorma** [Templarian/MaterialDesign#6251]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Like mdiSendCheck icon but with small x instead off check icon.

### Give us an example of what this icon might look like.

Like mdiSendCheck icon but with small x instead off check icon.

**Comment by Simran-B** [comment]
It's a Google icon but we didn't like it, see the discussion here: https://github.com/Templarian/MaterialDesign/issues/4361

**Comment by GaborTorma** [comment]
send-cross perfect for me. Thanx!
