### ISSUE TITLE
UPS (Uninterruptible Power Supply)

### ISSUE THREAD

**Issue by tfgcampos** [Templarian/MaterialDesign#6252]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For Smart Home dashboard, to identify network connected UPS.

### Give us an example of what this icon might look like.

![ups-4](https://user-images.githubusercontent.com/29363199/137813853-6c10632a-e078-4008-bb45-13e92368c450.png)
![ups-3](https://user-images.githubusercontent.com/29363199/137813858-dc1be5e7-436a-4aca-b00f-9cb61274cf91.jpg)
![ups-2](https://user-images.githubusercontent.com/29363199/137813859-0c5bb421-6ecf-4835-8214-f4f4010107ec.png)
![ups-1](https://user-images.githubusercontent.com/29363199/137813861-f5af0714-10bd-4763-8e2d-d322d9b78e02.png)

**Comment by goyney** [comment]
UPS' don't have a typical, recognizable shape that translates well to an icon. I'd recommend using one of our many, many battery icons.
