### ISSUE TITLE
truck-alert-outline

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#6260]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

When there is no shipping company available.

### Give us an example of what this icon might look like.

![truck-alert-outline](https://user-images.githubusercontent.com/6717356/138082862-906c61c2-8dbd-40ca-831b-f5bde353141f.jpg)
![truck-alert-outline-2](https://user-images.githubusercontent.com/6717356/138082879-118e6a1c-11da-44e4-bd18-ed836ce125fd.jpg)

**Comment by Simran-B** [comment]
The last time I checked (April 2020), the alert modifier had a pretty inconsistent height, ranging from 5 to 8 pixels 😞

**Comment by goyney** [comment]
> The last time I checked (April 2020), the alert modifier had a pretty inconsistent height, ranging from 5 to 8 pixels 😞

This was fixed: https://github.com/Templarian/MaterialDesign/issues/4908

**Comment by Simran-B** [comment]
Right, seems fixed for the most part. The upper part should be 6 pixels high, pixels 8-13, with 1 pixel padding to the right side:

![image](https://user-images.githubusercontent.com/7819991/139969824-51f2c8ec-453f-44a8-b7c2-5bbf044c1c5f.png)

**Comment by Simran-B** [comment]
The truck could be cut off:
![image](https://user-images.githubusercontent.com/7819991/140185601-df79e64b-702f-4f8a-99a9-cc2822bc15b0.png)

Or shrunk:
![image](https://user-images.githubusercontent.com/7819991/140185961-cb54a82b-674f-4f0e-bca9-1b067d690afd.png)

Or place a non-standard modifier inside:
![image](https://user-images.githubusercontent.com/7819991/140186275-d5d658d6-59f7-4e3e-9e54-003095546d1d.png)

![image](https://user-images.githubusercontent.com/7819991/140187241-b74c2222-6846-4b47-b0a5-968c1ff8da7e.png)

![image](https://user-images.githubusercontent.com/7819991/140187198-c3b7616d-2438-4e04-bf26-a5a9cb5d8c29.png)

![image](https://user-images.githubusercontent.com/7819991/140187282-6649a6c3-3dbb-47e2-a545-3778592a0958.png)

[truck-alert.zip](https://github.com/Templarian/MaterialDesign/files/7470484/truck-alert.zip)

**Comment by goyney** [comment]
The modifiers go inside on the trucks.

**Comment by goyney** [comment]
[![truck-alert](https://materialdesignicons.com/icon/truck-alert)](https://materialdesignicons.com/icon/truck-alert)[![truck-alert-outline](https://materialdesignicons.com/icon/truck-alert-outline)](https://materialdesignicons.com/icon/truck-alert-outline)
