### ISSUE TITLE
briefcase-exchange

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#6262]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

The icon is suitable for sharing documents and/or cases (better than the "swap-horizontal" or "file-exchange" icon, which is also missing)

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/44722574/138449657-cf8d545f-d157-4768-ba53-3ff18b0f6a6c.png)
![image](https://user-images.githubusercontent.com/44722574/138449697-a1bc4f4d-7087-475b-b9cd-1f54285c607f.png)

### Upload the icon source.

[briefcase-exchange.zip](https://github.com/Templarian/MaterialDesign/files/7396860/briefcase-exchange.zip)

**Comment by Simran-B** [comment]
Please use the standard modifier and cutout, see e.g. https://github.com/Templarian/MaterialDesign/issues/6263#issuecomment-962118507

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/141103065-30c6ae50-773c-41ff-a2bf-605e43f13ea0.png)
![image](https://user-images.githubusercontent.com/44722574/141103092-96307a8f-f5f4-40fb-b5ee-20803855f7ed.png)
![image](https://user-images.githubusercontent.com/44722574/141103112-7e3a78b3-14fa-49f4-931c-7dad6d3be4e5.png)
![image](https://user-images.githubusercontent.com/44722574/141103124-c6e6c928-620f-49a0-a027-1f989da27fcc.png)
[briefcase-arrow.zip](https://github.com/Templarian/MaterialDesign/files/7512170/briefcase-arrow.zip)
[file-arrow.zip](https://github.com/Templarian/MaterialDesign/files/7512172/file-arrow.zip)

**Comment by goyney** [comment]
[![briefcase-arrow-left-right](https://materialdesignicons.com/icon/briefcase-arrow-left-right)](https://materialdesignicons.com/icon/briefcase-arrow-left-right)[![briefcase-arrow-left-right-outline](https://materialdesignicons.com/icon/briefcase-arrow-left-right-outline)](https://materialdesignicons.com/icon/briefcase-arrow-left-right-outline)
[![briefcase-arrow-up-down](https://materialdesignicons.com/icon/briefcase-arrow-up-down)](https://materialdesignicons.com/icon/briefcase-arrow-up-down)[![briefcase-arrow-up-down-outline](https://materialdesignicons.com/icon/briefcase-arrow-up-down-outline)](https://materialdesignicons.com/icon/briefcase-arrow-up-down-outline)
