### ISSUE TITLE
file-exchange

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#6263]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

When working with documents and files, it is very common to use "[swap-](https://materialdesignicons.com/icon/swap-horizontal)" icons, but explanations are lacking. I added the icon for the cases earlier and I think that the file-exchange icon will also be in place and will be useful to many.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/44722574/138446729-5c2abe1d-aeec-4472-84d4-7c744e8e1739.png)
![image](https://user-images.githubusercontent.com/44722574/138446747-27e2c864-c5e0-4aa9-b63e-42c7abbe5082.png)

### Upload the icon source.

[file-exchange.zip](https://github.com/Templarian/MaterialDesign/files/7396760/file-exchange.zip)

**Comment by Xenomorph99** [comment]
Here's [`file`](https://materialdesignicons.com/icon/file) and [`file-outline`](https://materialdesignicons.com/icon/file-outline) with the standard `-arrow-left-right` and `-arrow-up-down` modifiers:

![file-arrow-left-right](https://user-images.githubusercontent.com/1837101/140559753-39f160b8-421d-4260-a1b0-269b79c7bf39.png)
![file-arrow-left-right-outline](https://user-images.githubusercontent.com/1837101/140559751-1fc2d622-eb59-446c-9bf6-2567a85ff114.png)

![file-arrow-up-down](https://user-images.githubusercontent.com/1837101/140559757-1ceebd1a-74df-4db9-8879-417b8c738e9a.png)
![file-arrow-up-down-outline](https://user-images.githubusercontent.com/1837101/140559754-4645fe6d-e441-4fd3-aeef-ace3ed2bae7f.png)

[file-arrows.zip](https://github.com/Templarian/MaterialDesign/files/7488146/file-arrows.zip)

**Comment by andrejsharapov** [comment]
You're right. Such a concept would be even better than I expected. https://github.com/Templarian/MaterialDesign/issues/6262#issuecomment-965029277

**Comment by goyney** [comment]
[![file-arrow-left-right](https://materialdesignicons.com/icon/file-arrow-left-right)](https://materialdesignicons.com/icon/file-arrow-left-right)[![file-arrow-left-right-outline](https://materialdesignicons.com/icon/file-arrow-left-right-outline)](https://materialdesignicons.com/icon/file-arrow-left-right-outline)
[![file-arrow-up-down](https://materialdesignicons.com/icon/file-arrow-up-down)](https://materialdesignicons.com/icon/file-arrow-up-down)[![file-arrow-up-down-outline](https://materialdesignicons.com/icon/file-arrow-up-down-outline)](https://materialdesignicons.com/icon/file-arrow-up-down-outline)
