### ISSUE TITLE
message-fast

### ISSUE THREAD

**Issue by Propaganistas** [Templarian/MaterialDesign#6265]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'm using `email-fast-outline` as a status icon in a notification alert indicating that a mail has been sent and the user should check his inbox. 

I would love to convey the same idea for sent text messages (sms).

### Give us an example of what this icon might look like.

The very same concept of `email-fast`, but applied to `message`, `message-outline`, `message-text` and `message-text-outline`.

(I would use the `message-text-outline` variant)

**Comment by Simran-B** [comment]
It kind of works for the `message-` icons:

![image](https://user-images.githubusercontent.com/7819991/139965894-d3b73354-5b10-4e86-9175-e9060f996c95.png)
![image](https://user-images.githubusercontent.com/7819991/139966063-ae8ab153-63e2-4d4f-acf8-e80943ca2b74.png)

but fitting in the text of the `message-text-*` icons makes it look weird:

![image](https://user-images.githubusercontent.com/7819991/139966440-fe895ccd-b4a4-4e69-9d69-35ebb0f37b18.png)
![image](https://user-images.githubusercontent.com/7819991/139966774-91330d41-5b17-4fe0-b588-6a995b6be3c3.png)

[message-fast.zip](https://github.com/Templarian/MaterialDesign/files/7464601/message-fast.zip)

**Comment by Propaganistas** [comment]
Looking great!

Personally I don't feel like the `message-text` variants are off in some way, but of course you're better positioned to guard the overall consistency of the library.

**Comment by goyney** [comment]
[![message-fast](https://materialdesignicons.com/icon/message-fast)](https://materialdesignicons.com/icon/message-fast)[![message-fast-outline](https://materialdesignicons.com/icon/message-fast-outline)](https://materialdesignicons.com/icon/message-fast-outline)
[![message-text-fast](https://materialdesignicons.com/icon/message-text-fast)](https://materialdesignicons.com/icon/message-text-fast)[![message-text-fast-outline](https://materialdesignicons.com/icon/message-text-fast-outline)](https://materialdesignicons.com/icon/message-text-fast-outline)
