### ISSUE TITLE
file-chart with check symbol

### ISSUE THREAD

**Issue by YousefGhafouri** [Templarian/MaterialDesign#6266]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need an icon like file-chart but with a little check symbol at the right bottom corner . it means the file-chart is confirmed

### Give us an example of what this icon might look like.

![file-chart](https://user-images.githubusercontent.com/52343597/138600825-06cfdefd-47f4-4beb-bc70-5ce1c963dbb3.png)

Merge with 

![check](https://user-images.githubusercontent.com/52343597/138601055-76212f83-3e79-4a6d-a43d-bd00676f0d87.png)

**Comment by Simran-B** [comment]
It hardly recognizable with the cutout IMO:

![image](https://user-images.githubusercontent.com/7819991/139963751-29cc5959-85c8-42b3-b78a-68b00ed6cee5.png) ![image](https://user-images.githubusercontent.com/7819991/139963879-85992fbb-c21f-4088-913a-c1de1edb22e3.png)

[file-chart-check.zip](https://github.com/Templarian/MaterialDesign/files/7464459/file-chart-check.zip)

**Comment by goyney** [comment]
It's fine.

[![file-chart-check](https://materialdesignicons.com/icon/file-chart-check)](https://materialdesignicons.com/icon/file-chart-check)[![file-chart-check-outline](https://materialdesignicons.com/icon/file-chart-check-outline)](https://materialdesignicons.com/icon/file-chart-check-outline)
