### ISSUE TITLE
HitBox.tv icon

### ISSUE THREAD

**Issue by ghost** [Templarian/MaterialDesign#627]
That should help some streamers who use Hitbox instead of Twitch or other broadcasting websites.

**Comment by CoDEmanX** [comment]
@Templarian: does the existing Twitch icon fall under the new "no brand icons" policy? If no, then it's a legit request.
![hitbox logo](http://nvgamer.fr/images/hitbox.png)

**Comment by Templarian** [comment]
Nah, hitbox would be fine. I would say it is social media.
