### ISSUE TITLE
Image with lock

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6270]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To encrypt or add password to an image

### Give us an example of what this icon might look like.

Image-outline with lock-outline

<img width="259" alt="スクリーンショット 2021-10-26 18 40 37" src="https://user-images.githubusercontent.com/88420807/138852898-b014990e-bd23-4f7a-85cf-0a6dad57548d.png">

![archive-lock-outline](https://user-images.githubusercontent.com/88420807/138854270-a693f535-46dc-4fc4-87c7-1c74c7d1fada.png)

**Comment by Simran-B** [comment]
![image](https://user-images.githubusercontent.com/7819991/140587842-0a83f863-bee5-40e1-a84d-9cb6999fe749.png) ![image](https://user-images.githubusercontent.com/7819991/140587913-42eb26a7-e186-4f7a-b366-e596e5c1dee7.png)

[image-lock.zip](https://github.com/Templarian/MaterialDesign/files/7489273/image-lock.zip)

**Comment by tmy-sr** [comment]
thank you 👍

**Comment by tmy-sr** [comment]
when this will be uploaded?

**Comment by goyney** [comment]
[![image-lock](https://materialdesignicons.com/icon/image-lock)](https://materialdesignicons.com/icon/image-lock)[![image-lock-outline](https://materialdesignicons.com/icon/image-lock-outline)](https://materialdesignicons.com/icon/image-lock-outline)
