### ISSUE TITLE
Video with lock

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6271]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To encrypt or add password to a video

### Give us an example of what this icon might look like.

Play-box-outline with lock-outline

<img width="259" alt="スクリーンショット 2021-10-26 18 41 50" src="https://user-images.githubusercontent.com/88420807/138853106-c4024a37-dd2a-4f43-a7e5-0c192cd864d0.png">

![archive-lock-outline](https://user-images.githubusercontent.com/88420807/138854234-ee02fa62-752b-4b5a-95e7-f386226e9042.png)

**Comment by Simran-B** [comment]
![image](https://user-images.githubusercontent.com/7819991/140589574-2c2f2adc-1fe2-4721-b971-99965570f400.png) ![image](https://user-images.githubusercontent.com/7819991/140589742-a1e554bf-0557-42be-b514-75b1d9b1c755.png)

![image](https://user-images.githubusercontent.com/7819991/140589704-bd15ac35-99de-4a84-a319-c31592cf7341.png) ![image](https://user-images.githubusercontent.com/7819991/140589680-ab40e702-f47e-4dcc-91ab-7e56ba15bba5.png)

Not sure if there's any use for the lock-open variants.

[play-box-lock.zip](https://github.com/Templarian/MaterialDesign/files/7489338/play-box-lock.zip)

**Comment by tmy-sr** [comment]
thank you 👍

**Comment by tmy-sr** [comment]
when this will be uploaded?

**Comment by Templarian** [comment]
The boxes probably all need to be shifted to the left 1dp. 🤔  Something about the cut out looks off.

**Comment by Templarian** [comment]
[![play-box-lock](https://materialdesignicons.com/icon/play-box-lock)](https://materialdesignicons.com/icon/play-box-lock) [![play-box-lock-open](https://materialdesignicons.com/icon/play-box-lock-open)](https://materialdesignicons.com/icon/play-box-lock-open) [![play-box-lock-outline](https://materialdesignicons.com/icon/play-box-lock-outline)](https://materialdesignicons.com/icon/play-box-lock-outline) [![play-box-lock-open-outline](https://materialdesignicons.com/icon/play-box-lock-open-outline)](https://materialdesignicons.com/icon/play-box-lock-open-outline)

@Simran-B Updated the owner to you after the fact, but did modify them a little.
