### ISSUE TITLE
File with lock

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6272]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To encrypt or add password to a file

### Give us an example of what this icon might look like.

file-outline with lock-outline
<img width="259" alt="スクリーンショット 2021-10-26 18 47 56" src="https://user-images.githubusercontent.com/88420807/138854167-1f4f50b8-e2f9-47db-a5d3-ee5555166eb1.png">

![archive-lock-outline](https://user-images.githubusercontent.com/88420807/138853857-57d7df63-7741-4ddc-a9d9-4371a6803b53.png)

**Comment by Simran-B** [comment]
There are already `file-lock` and `file-lock-outline` but the lock is placed inside the file and the looks a bit bulky. Using the locks from the `account-` icons:

![image](https://user-images.githubusercontent.com/7819991/139964915-bbdebc1a-1667-4927-9739-fa8d383f3d15.png) ![image](https://user-images.githubusercontent.com/7819991/139964934-f178b966-c054-4658-84e3-b8e17327fa05.png)
![image](https://user-images.githubusercontent.com/7819991/139964952-45da1734-51aa-40b6-ada2-9216cb0275d2.png) ![image](https://user-images.githubusercontent.com/7819991/139964967-83d37967-bbd2-49c8-8d40-5b992a036933.png)

[file-lock.zip](https://github.com/Templarian/MaterialDesign/files/7464493/file-lock.zip)

**Comment by goyney** [comment]
Agreed. Updated and added the two new ones.

[![file-lock](https://materialdesignicons.com/icon/file-lock)](https://materialdesignicons.com/icon/file-lock)[![file-lock-outline](https://materialdesignicons.com/icon/file-lock-outline)](https://materialdesignicons.com/icon/file-lock-outline)
[![file-lock-open](https://materialdesignicons.com/icon/file-lock-open)](https://materialdesignicons.com/icon/file-lock-open)[![file-lock-open-outline](https://materialdesignicons.com/icon/file-lock-open-outline)](https://materialdesignicons.com/icon/file-lock-open-outline)
