### ISSUE TITLE
Scrapper Icon

### ISSUE THREAD

**Issue by royale1223** [Templarian/MaterialDesign#628]
It looks much like a brush. 

http://www.cesar.co.uk/image/cache/product_images/675-500x500.jpg

**Comment by PeterShaggyNoble** [comment]
@royale1223, the link above is dead. Could you please update with an inline image?

**Comment by royale1223** [comment]
@PeterShaggyNoble Here you go : https://www.remingtonsteelarts.com/scrapper/

**Comment by PeterShaggyNoble** [comment]
My gut feeling is that this a *very* specific type of knife that's probably going to be beyond the scope of this project; pretty sure I've never come across it before.

I'll leave this issue open for now, though, to gather thoughts from the others.

**Comment by MrGrigri** [comment]
Closing this as it's too niche.
