### ISSUE TITLE
Attachment with lock

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6281]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

for add an attachment file with password/encrypt

### Give us an example of what this icon might look like.

attachment icon with lock outline, looks like book-lock-outline
And we need attachment icon with tilted version

**Comment by Simran-B** [comment]
Not a fan:

![image](https://user-images.githubusercontent.com/7819991/139967158-4ccb6eaa-4f5c-4c8a-8232-8420242e7447.png)
![image](https://user-images.githubusercontent.com/7819991/139967368-eabff43c-531c-49f4-8d9d-0bcb4044682d.png)
![image](https://user-images.githubusercontent.com/7819991/139967560-055ea2fa-ad27-4768-a566-2c066a6c7e6b.png)
![image](https://user-images.githubusercontent.com/7819991/139967611-b5bc119c-c561-48d6-81bb-be262b9c0d3b.png)

[attachment-lock.zip](https://github.com/Templarian/MaterialDesign/files/7464630/attachment-lock.zip)

**Comment by goyney** [comment]
[![attachment-lock](https://materialdesignicons.com/icon/attachment-lock)](https://materialdesignicons.com/icon/attachment-lock)[![paperclip-lock](https://materialdesignicons.com/icon/paperclip-lock)](https://materialdesignicons.com/icon/paperclip-lock)
