### ISSUE TITLE
Audience network

### ISSUE THREAD

**Issue by dimon1512b** [Templarian/MaterialDesign#6282]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Same like else brand icons

### Give us an example of what this icon might look like.

![Screenshot_48](https://user-images.githubusercontent.com/83750747/139382851-04641aa1-2426-41d1-8f88-830367471c57.png)

**Comment by Simran-B** [comment]
No brand icons, read the issue template.
