### ISSUE TITLE
TransmissionTowerOff

### ISSUE THREAD

**Issue by TwixYU** [Templarian/MaterialDesign#6283]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In South Africa and other places in the world, power outages are occurring from time to time.
Please can we get an icon that will symbolise this power outage from the utility.

Once the power is off - it can be mdi:TransmissionTowerOff while the utility is supplying power - mdi:TransmissionTower that currently exist

### Give us an example of what this icon might look like.

TransmissionTowerOff
![transsmission-tower-off](https://user-images.githubusercontent.com/5261343/139387165-5b7895c4-b68c-4fdc-b31c-9b8ac4cf1f93.jpg)

**Comment by TwixYU** [comment]
Hello,

I think that your version looks just right!

I created mine as an example, but the one you created has right dimensions, etc, so I think it really looks good and will symbolise what it needs to 

 

Would you be able to include in the next release of mdi icons?

 

Kind regards,

 

Bobby Kaucic

+27 (0)76 755 3787

***@***.***

 

From: Simran ***@***.***>
Reply to: Templarian/MaterialDesign ***@***.***>
Date: Wednesday, 03 November 2021 at 02:06
To: Templarian/MaterialDesign ***@***.***>
Cc: TwixYU ***@***.***>, Author ***@***.***>
Subject: Re: [Templarian/MaterialDesign] TransmissionTowerOff (Issue #6283)

 

I tried to tweak the strike through the icon but it's not working out that well:



transmission-tower-off.zip

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by goyney** [comment]
[![transmission-tower-off](https://materialdesignicons.com/icon/transmission-tower-off)](https://materialdesignicons.com/icon/transmission-tower-off)

**Comment by TwixYU** [comment]
Thank you guys :)
