### ISSUE TITLE
phone with clock for scheduled call

### ISSUE THREAD

**Issue by GaborTorma** [Templarian/MaterialDesign#6286]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

A phone icon like phone-cancel, but with clock icon (mdiAlarm) instead of cancel.

### Give us an example of what this icon might look like.

A phone icon like phone-cancel, but with clock icon (mdiAlarm) instead of cancel.

**Comment by Simran-B** [comment]
The clock modifier is rather large, making it tricky to combine with the phone base icon. Here are some experiments:

![image](https://user-images.githubusercontent.com/7819991/139969146-2ee078e0-df38-445c-b05d-5a884c1b0132.png) ![image](https://user-images.githubusercontent.com/7819991/139969193-ca139600-4826-43be-b27f-6fb5adfd9e80.png)
![image](https://user-images.githubusercontent.com/7819991/139968681-5f16e3ea-6260-48b4-bda2-622102b1816a.png) ![image](https://user-images.githubusercontent.com/7819991/139969070-f3173286-7987-4179-9189-19f17c6503dc.png)

[phone-clock.zip](https://github.com/Templarian/MaterialDesign/files/7464683/phone-clock.zip)

**Comment by GaborTorma** [comment]
Thanx for your work! I think the phone-clock2 is the best.

**Comment by goyney** [comment]
[![phone-clock](https://materialdesignicons.com/icon/phone-clock)](https://materialdesignicons.com/icon/phone-clock)
