### ISSUE TITLE
Advance Exporting should limit size to 512

### ISSUE THREAD

**Issue by t123yh** [Templarian/MaterialDesign#6287]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

Open icon dialog, select "advanced export", then enter 1024 in the "Size" field, and click "Icon" button to download it. You will be redirected to a page saying that size is (12 to 512). I think we should prompt user that the max size is 512 when he enters 1024 in the Size field.

**Comment by Templarian** [comment]
We're not currently doing updates to the legacy site as we do development on the new site. See the pinned issue.
