### ISSUE TITLE
water-boiler-auto

### ISSUE THREAD

**Issue by vlebourl** [Templarian/MaterialDesign#6288]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I have a water-boiler with auto mode and am missing the icon.
Here is a suggestion based on fan-auto.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/5701372/139690519-be201450-4868-4d62-8a8a-38a7c85f4e29.png)

### Upload the icon source.

[water-boiler-auto.zip](https://github.com/Templarian/MaterialDesign/files/7454041/water-boiler-auto.zip)

**Comment by goyney** [comment]
[![water-boiler-auto](https://materialdesignicons.com/icon/water-boiler-auto)](https://materialdesignicons.com/icon/water-boiler-auto)
