### ISSUE TITLE
Write review icon

### ISSUE THREAD

**Issue by Rahulaswani** [Templarian/MaterialDesign#629]
Write icon, for writing a review

<img width="186" alt="screen shot 2015-08-23 at 11 21 15 pm" src="https://cloud.githubusercontent.com/assets/6178689/9429443/c738ca80-49ed-11e5-8130-cf26f23deaf2.png">

**Comment by CoDEmanX** [comment]
Looks much like #535 to me?!

**Comment by Templarian** [comment]
Yep, going to mark this as a duplicate. They appear to be the same requests.
