### ISSUE TITLE
package-variant-closed-plus

### ISSUE THREAD

**Issue by ferenc-szabo** [Templarian/MaterialDesign#6293]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I'm developing a project management tool where package is a metaphor for a group of tasks.
I needed an icon that represents the "create new package" action.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/47912631/140039648-b14cfc3a-44cb-4de3-82f0-79f32498908b.png)

### Upload the icon source.

[package-variant-closed-plus.zip](https://github.com/Templarian/MaterialDesign/files/7466669/package-variant-closed-plus.zip)

**Comment by goyney** [comment]
[![package-variant-plus](https://materialdesignicons.com/icon/package-variant-plus)](https://materialdesignicons.com/icon/package-variant-plus)[![package-variant-closed-plus](https://materialdesignicons.com/icon/package-variant-closed-plus)](https://materialdesignicons.com/icon/package-variant-closed-plus)
