### ISSUE TITLE
numeric-off

### ISSUE THREAD

**Issue by Voodu** [Templarian/MaterialDesign#6296]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I needed `off` variant of numeric for some option toggling in my app. I combined `numeric` and `label-off` strike through.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/24680898/140072985-b4edbf91-28c6-46c4-969f-2d858b0f6b15.png)

### Upload the icon source.

[numeric-off.zip](https://github.com/Templarian/MaterialDesign/files/7468027/numeric-off.zip)

**Comment by goyney** [comment]
[![numeric-off](https://materialdesignicons.com/icon/numeric-off)](https://materialdesignicons.com/icon/numeric-off)
