### ISSUE TITLE
receipt-outline

### ISSUE THREAD

**Issue by FranckSix** [Templarian/MaterialDesign#6297]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Icon on system website

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/8504152/140095333-eecfe5f3-d07d-4ecd-955a-1c6af5c718d2.png)

### Upload the icon source.

[invoice.zip](https://github.com/Templarian/MaterialDesign/files/7468883/invoice.zip)

**Comment by goyney** [comment]
Google has this icon in their set, so we'll add theirs.

![image](https://user-images.githubusercontent.com/1015040/140096151-6433e2e4-8cbd-4a67-b40e-ee705affec76.png)

**Comment by goyney** [comment]
[![receipt-outline](https://materialdesignicons.com/icon/receipt-outline)](https://materialdesignicons.com/icon/receipt-outline)
