### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by FranckSix** [Templarian/MaterialDesign#6298]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Icon for activity on website

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/8504152/140099220-8756b515-ffa3-4015-bac9-4b638a62b26d.png)

### Upload the icon source.

[budget.zip](https://github.com/Templarian/MaterialDesign/files/7469070/budget.zip)

**Comment by goyney** [comment]
[![piggy-bank](https://materialdesignicons.com/icon/piggy-bank)](https://materialdesignicons.com/icon/piggy-bank)
