### ISSUE TITLE
room-service-outline

### ISSUE THREAD

**Issue by awazgyawali** [Templarian/MaterialDesign#630]
I am seeking for the request icon.

**Comment by Templarian** [comment]
Do you have an example of what this might look like?

**Comment by awazgyawali** [comment]
Actually I was seeking for the icon for my project but I don't have any idea. Thought this icon would be useful to other users so I posted it.

**Comment by CoDEmanX** [comment]
I really like the idea behind this one:

![request](https://cdn4.iconfinder.com/data/icons/hotel-facilities-1/512/Special-request-512.png)

Too much like "I warn you":
![r](https://cdn3.iconfinder.com/data/icons/abstract-1/512/request-128.png)

Something list-like might work:
![r](http://gbxevents.org/wp-content/uploads/2013/12/Adds-Add-list-icon-150x150.png)

**Comment by goyney** [comment]
I think there is more context involved here. **What** are you requesting?

Some examples:
- Requesting an address/email address, you could use `email-plus`
- Requesting feedback or comments, you could use `tooltip-plus`.
- Requesting support, you could use `lifebuoy`.

If you wanted to go super generic, you could use `plus-box` or `plus-circle`.

I don't know if there is really anything to gain from this issue. I do like the service bell example, though. Perhaps we can add that.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50928443-afab5780-1428-11e9-969f-1f24e7c3faa8.png)

[service-bell.svg.zip](https://github.com/Templarian/MaterialDesign/files/2742608/service-bell.svg.zip)

**Comment by goyney** [comment]
Putting this in the `Backlog` for now, not sure if I like that icon. I'll let @Templarian make the call.

**Comment by CoDEmanX** [comment]
service-bell-outline?

**Comment by goyney** [comment]
I don't think there's a filled version of this without it looking like a boob.

**Comment by PeterShaggyNoble** [comment]
Not forgetting the `room-service` icon, too - I still don't know whether that's supposed to be a bell or a tray! 😆

**Comment by goyney** [comment]
Oh, geeze, we already have this exact icon in boob form! I think the fact that it could be used as a food tray or a service bell is actually an advantage of that icon. I say we consider this issue taken care of with that icon.

**Comment by PeterShaggyNoble** [comment]
May as well use this issue for the outline version:

[![room-service-outline](https://user-images.githubusercontent.com/15157491/50975500-b1872080-14e5-11e9-9c6d-33d0e738569f.png)](https://material.io/tools/icons/?search=room_service&icon=room_service&style=outline)

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50975656-204f8400-14bc-11e9-9d62-fa69be675df1.png)

[room-service-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/2745771/room-service-outline.svg.zip)

**Comment by Templarian** [comment]
As funny as it would be. Please no one alias this anything inappropriate. 😐

Updated/Added.
