### ISSUE TITLE
test

### ISSUE THREAD

**Issue by FranckSix** [Templarian/MaterialDesign#6300]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

test, simulation

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/8504152/140177281-edecb96d-d846-4e73-834b-0ac73d5a5100.png)

### Upload the icon source.

[simulation.zip](https://github.com/Templarian/MaterialDesign/files/7470163/simulation.zip)

**Comment by goyney** [comment]
Already included. Please search.
[![flask](https://materialdesignicons.com/icon/flask)](https://materialdesignicons.com/icon/flask)[![flask-outline](https://materialdesignicons.com/icon/flask-outline)](https://materialdesignicons.com/icon/flask-outline)
