### ISSUE TITLE
uploaded file

### ISSUE THREAD

**Issue by florank** [Templarian/MaterialDesign#6302]
### Before submitting a new icon request, please confirm the following:

- [x] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [x] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

File uploaded/imported (to distinguish from files created inside a tool)

For example, I'm making a invoice app, and users can create invoices inside the tool, or invoices pdf created in another one, to track payment.

### Give us an example of what this icon might look like.

Same as "file-move" with arrow top (and I had little bit rounded arrow corners)

![image](https://user-images.githubusercontent.com/88803280/140289994-9a35354b-08ec-422d-8cc0-61f722fabafd.png)

**Comment by goyney** [comment]
Already exists.
[![file-upload](https://materialdesignicons.com/icon/file-upload)](https://materialdesignicons.com/icon/file-upload)[![file-upload-outline](https://materialdesignicons.com/icon/file-upload-outline)](https://materialdesignicons.com/icon/file-upload-outline)
