### ISSUE TITLE
Folder lock outline

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6303]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For folder with password or encryption

### Give us an example of what this icon might look like.

https://materialdesignicons.com/icon/folder-lock
https://materialdesignicons.com/icon/folder-lock

**Comment by Xenomorph99** [comment]
Here's [`folder`](https://materialdesignicons.com/icon/folder) and [`folder-outline`](https://materialdesignicons.com/icon/folder-outline) with our standard `-lock-open` and `-lock-open-outline` modifiers.

![folder-lock-open](https://user-images.githubusercontent.com/1837101/140556398-7c348df0-680a-4fdf-933a-71bde5f7a6b6.png)
![folder-lock-open-outline](https://user-images.githubusercontent.com/1837101/140556397-a6e9dabd-c304-41af-bdb6-265d46e9c9d3.png)

[folder-lock-open.zip](https://github.com/Templarian/MaterialDesign/files/7488003/folder-lock-open.zip)

**Comment by tmy-sr** [comment]
thank you 👍

**Comment by Templarian** [comment]
I agree lets update our existing `folder-*` to use the standard cutout.

**Comment by goyney** [comment]
[![folder-lock](https://materialdesignicons.com/icon/folder-lock)](https://materialdesignicons.com/icon/folder-lock)[![folder-lock-outline](https://materialdesignicons.com/icon/folder-lock-outline)](https://materialdesignicons.com/icon/folder-lock-outline)
[![folder-lock-open](https://materialdesignicons.com/icon/folder-lock-open)](https://materialdesignicons.com/icon/folder-lock-open)[![folder-lock-open-outline](https://materialdesignicons.com/icon/folder-lock-open-outline)](https://materialdesignicons.com/icon/folder-lock-open-outline)
