### ISSUE TITLE
Paperclip and Attachment Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6307]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

[`paperclip-lock`](https://materialdesignicons.com/icon/paperclip-lock) and [`attachment-lock`](https://materialdesignicons.com/icon/attachment-lock) were introduced in #6281. If we're going to allow modifiers on [`paperclip`](https://materialdesignicons.com/icon/paperclip) and [`attachment`](https://materialdesignicons.com/icon/attachment) then we should probably include the following as well:

### Attachment
![attachment-off](https://user-images.githubusercontent.com/1837101/140545520-078b52ad-3ad9-4333-80bf-221c105ba054.png)
![attachment-plus](https://user-images.githubusercontent.com/1837101/140545522-526e1984-06db-4374-a7e4-dcbcdd6e86fb.png)
![attachment-minus](https://user-images.githubusercontent.com/1837101/140545519-dcc945b3-2945-49ac-a483-09296fad7e51.png)
![attachment-check](https://user-images.githubusercontent.com/1837101/140545517-9bc23f86-5996-49cf-8119-00d20e04cdc9.png)
![attachment-remove](https://user-images.githubusercontent.com/1837101/140545523-e0309387-dfb8-456b-bf5d-34d712d7354f.png)

### Paperclip
![paperclip-off](https://user-images.githubusercontent.com/1837101/140545676-08e2b589-beb3-41f4-9fcf-d64be868aa62.png)
![paperclip-plus](https://user-images.githubusercontent.com/1837101/140545677-629a95c4-ba98-4807-a32a-7badf7056ebc.png)
![paperclip-minus](https://user-images.githubusercontent.com/1837101/140545674-9486d77b-0512-497c-9078-6b3579ac2e23.png)
![paperclip-check](https://user-images.githubusercontent.com/1837101/140545671-97379e10-54fa-48cc-8c2f-f849df21a687.png)
![paperclip-remove](https://user-images.githubusercontent.com/1837101/140545680-26edd55a-276b-453d-9661-2601731fd4d5.png)

### Upload the icon source.

[attachment-paperclip-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/7487528/attachment-paperclip-modifiers.zip)

**Comment by goyney** [comment]
All added.
