### ISSUE TITLE
Additional Folder Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6308]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I've included a few missing and new modifiers to [`folder`](https://materialdesignicons.com/icon/folder) and [`folder-outline`](https://materialdesignicons.com/icon/folder-outline)

### Share a preview of your contribution.

![folder-off](https://user-images.githubusercontent.com/1837101/140556715-c550781a-2a9a-4f34-bf2b-56224efe270c.png)
![folder-off-outline](https://user-images.githubusercontent.com/1837101/140556714-6a3d5b6a-edf5-42d6-b649-0e5d225b0dc0.png)

![folder-alert](https://user-images.githubusercontent.com/1837101/140556685-6270ee70-1ecc-44f9-a88e-884c9704b25b.png)
![folder-alert-outline](https://user-images.githubusercontent.com/1837101/140556680-43a22497-41df-4da5-847e-64fd28059641.png)

![folder-cancel](https://user-images.githubusercontent.com/1837101/140556711-0e48205f-88fc-43a0-b5e3-5c294fabc8c5.png)
![folder-cancel-outline](https://user-images.githubusercontent.com/1837101/140556709-c5ca75a8-8c4d-44e3-bb31-2ad0ddf07cb4.png)

![folder-wrench](https://user-images.githubusercontent.com/1837101/140556723-ef17965d-547b-44a5-b818-6bd1e84351c5.png)
![folder-wrench-outline](https://user-images.githubusercontent.com/1837101/140556721-ffc9feb3-90cf-49a1-a4b1-b16b6c781f28.png)

![folder-file](https://user-images.githubusercontent.com/1837101/140556713-8d23b257-665b-4d1b-882b-a1bc47203a30.png)
![folder-file-outline](https://user-images.githubusercontent.com/1837101/140556712-f9ca2aeb-f209-431c-9446-53e5c9c73744.png)

![folder-play](https://user-images.githubusercontent.com/1837101/140556720-1ac7f657-7046-451d-a071-377e31e483ba.png)
![folder-play-outline](https://user-images.githubusercontent.com/1837101/140556718-4f448b42-e15a-435a-b094-b54228576728.png)

![folder-arrow-left](https://user-images.githubusercontent.com/1837101/140556694-f951a077-2452-4736-a844-985c9f0b7d86.png)
![folder-arrow-left-outline](https://user-images.githubusercontent.com/1837101/140556689-2168c0be-7ce3-431d-a8e4-348b794b582d.png)

![folder-arrow-right](https://user-images.githubusercontent.com/1837101/140556699-d82f3cc9-9200-4210-95f1-55c139a69c61.png)
![folder-arrow-right-outline](https://user-images.githubusercontent.com/1837101/140556697-5a226e9b-666f-4c08-9d04-cc74b0600b0d.png)

![folder-arrow-left-right](https://user-images.githubusercontent.com/1837101/140556692-1d880338-41ca-4c31-bc3a-bbfaed7ead86.png)
![folder-arrow-left-right-outline](https://user-images.githubusercontent.com/1837101/140556690-6dc4447f-7202-4f0f-9bae-d523caef3f3a.png)

![folder-arrow-up](https://user-images.githubusercontent.com/1837101/140556708-7fdc6192-673b-4807-924c-cffeb25d0a40.png)
![folder-arrow-up-outline](https://user-images.githubusercontent.com/1837101/140556707-6ed50542-fad2-4fc2-971c-23f4d5c4c63a.png)

![folder-arrow-down](https://user-images.githubusercontent.com/1837101/140556688-c3a53dd6-436f-4ead-9369-d08cc6039594.png)
![folder-arrow-down-outline](https://user-images.githubusercontent.com/1837101/140556686-4c1c667e-fdc1-4d70-b86e-e43a75417cab.png)

![folder-arrow-up-down](https://user-images.githubusercontent.com/1837101/140556704-39215de5-0267-4ccd-9d57-95961fe10af2.png)
![folder-arrow-up-down-outline](https://user-images.githubusercontent.com/1837101/140556701-22ad506b-57a1-4f02-9e10-d8b13754c728.png)

### Upload the icon source.

[folder-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/7488016/folder-modifiers.zip)

**Comment by Templarian** [comment]
No objections, feel free to add these all. 👍  That folder file one is really useful.

**Comment by Simran-B** [comment]
What's folder file for?

Interestingly, the arrow modifier cutout looks misaligned to me somehow but it's correct based on the grid.

**Comment by Xenomorph99** [comment]
Added all of these except for `folder-alert` and `folder-alert-outline` which I didn't realize we already have in the library. (see #6341 for continued discussion)
