### ISSUE TITLE
Standard Folder Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6309]
### What is your question?

Should we update [`folder`](https://materialdesignicons.com/icon/folder) and [`folder-outline`](https://materialdesignicons.com/icon/folder-outline) to use our standard modifiers? The request in #6303 for a `-lock-open` modifier will be difficult or impossible with the current pattern.

I've attached the updated icons:

![folder-plus](https://user-images.githubusercontent.com/1837101/140557879-551f6b56-082d-4d5f-9c6c-5f425324942e.png)
![folder-plus-outline](https://user-images.githubusercontent.com/1837101/140557878-b7068f40-4be4-4bae-8f25-8cd5ff96044c.png)

![folder-minus](https://user-images.githubusercontent.com/1837101/140557875-f98899f5-96ab-4f9f-b90e-9500b222b418.png)
![folder-minus-outline](https://user-images.githubusercontent.com/1837101/140557874-b6d84876-c2a4-4036-95e9-f9e274139445.png)

![folder-check](https://user-images.githubusercontent.com/1837101/140557862-7eee13f4-ef98-441a-8b0e-1ff95e0e6165.png)
![folder-check-outline](https://user-images.githubusercontent.com/1837101/140557858-910fc3f2-fdc9-4c59-ac59-5258baa0d491.png)

![folder-remove](https://user-images.githubusercontent.com/1837101/140557881-c5552ad8-5458-4f77-bdca-61c0a351775a.png)
![folder-remove-outline](https://user-images.githubusercontent.com/1837101/140557880-e20f46e1-d59c-4534-9bcd-ac2f5c14432c.png)

![folder-edit](https://user-images.githubusercontent.com/1837101/140557865-b095d33c-9a16-43b3-82b1-156b7bc2269e.png)
![folder-edit-outline](https://user-images.githubusercontent.com/1837101/140557863-7b1fff56-ac1c-446c-aa79-31cef54f273f.png)

![folder-lock](https://user-images.githubusercontent.com/1837101/140557871-27533546-7e9f-4535-8c0d-a260e4cfa2ab.png)
![folder-lock-outline](https://user-images.githubusercontent.com/1837101/140557868-da4a724b-db54-44ab-a66f-622db6f57ad3.png)

![folder-star](https://user-images.githubusercontent.com/1837101/140557883-2644ed42-0c2a-4a32-b562-d7db6a3583d8.png)
![folder-star-outline](https://user-images.githubusercontent.com/1837101/140557882-7744e9a6-2741-447e-8d8a-916fc64180ee.png)

![folder-music-outline](https://user-images.githubusercontent.com/1837101/140557876-5fb258d4-a6f0-40cc-bda1-5cda570af95c.png)
![folder-music](https://user-images.githubusercontent.com/1837101/140557877-baf9b4c6-2d75-45df-a2dd-336a47d6cccc.png)

### Download

[updated-folder-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/7488073/updated-folder-modifiers.zip)

**Comment by goyney** [comment]
I don't know. 😕  The reason most file/folder modifiers are internal are because they can be used within a file tree and that messes up alignment. Usually, when we have room inside the icon and there isn't artboard space (truck is a perfect example), we try to keep them inside.

I think these all look perfectly acceptable, I just am unsure if we want to go to this extreme. I'm up to hear some counter arguments. 😄

**Comment by Xenomorph99** [comment]
The file tree use case you brought up makes a lot of sense for keeping the internal modifiers available in the library. Perhaps we could convert the internal modifiers to `-variant` and introduce the standard modifiers as well. This would build on the visual continuity we've been establishing across the library while still supporting the file tree use case.

Icons such as `truck` or `message` lose their interpretation when our standard modifiers are applied because important visual cues are hidden. Using internal modifiers is the best alternative in these situations. However, both `folder` and `file` work with our standard modifiers and interpretation is not lost.

Something else to note is the seemingly arbitrary fragmentation across both the `folder` and `file` icons:

`folder-plus`, `folder-download`, `folder-question`, `folder-star`, `folder-lock` use internal modifiers while `folder-cog`, `folder-eye`, `folder-marker`, `folder-refresh`, and `folder-sync` use the standard modifiers.

`file-plus`, `file-alert`, `file-download`, and `file-music` use internal modifiers while `file-image-plus`, `file-chart-check`, `file-marker`, `file-move`, and `file-sync` use the standard modifiers.

I think it's safe to say that converting all `folder` and `file` modifiers to standard modifiers would work, but going the other direction won't. I think we're faced with three options:

**Option 1:** Convert all internal modifiers on `folder` and `file` icons to `-variant` and add all the standard modifiers.

**Option 2:** Convert all internal modifiers on `folder` and `file` icons to the standard modifiers

**Option 3:** Make no changes or additions but clearly document when an internal or standard modifier is to be used.

**Comment by goyney** [comment]
Absolutely not Option 1. Variants are for variants of the base icons, not modifiers. We don't need two of each of these.

**Comment by Xenomorph99** [comment]
Just to be clear @Templarian, are you recommending we go with Option 2 based on your comment on #6303?

**Comment by Xenomorph99** [comment]
Just as a reference, #6261 updated a bunch of the `file` icons to use the standard modifiers following **Option 2**.

**Comment by goyney** [comment]
> Just as a reference, #6261 updated a bunch of the `file` icons to use the standard modifiers following **Option 2**.

Yep, feel free to update them. Otherwise, I'll get to it eventually.

**Comment by goyney** [comment]
All updated, except for `folder-star` because it clashes with the multiple variant. Added the two `minus` variants.
