### ISSUE TITLE
Timer Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6310]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Here's additional modifiers for [`timer`](https://materialdesignicons.com/icon/timer) and [`timer-outline`](https://materialdesignicons.com/icon/timer-outline):

### Share a preview of your contribution.

![timer-plus](https://user-images.githubusercontent.com/1837101/140577653-84241f56-fa86-4ffb-a4e9-0c4e25cf257e.png)
![timer-plus-outline](https://user-images.githubusercontent.com/1837101/140577652-5639eae7-2603-4e01-abfb-b60a66b06a20.png)

![timer-minus](https://user-images.githubusercontent.com/1837101/140577640-307c37d5-d6df-4301-a1f5-7ed511b910c8.png)
![timer-minus-outline](https://user-images.githubusercontent.com/1837101/140577639-9a3d00d1-0e69-4558-92d3-1174211ce93a.png)

![timer-check](https://user-images.githubusercontent.com/1837101/140577617-d8f5e88d-1cb7-4b0f-a10c-41a21790a172.png)
![timer-check-outline](https://user-images.githubusercontent.com/1837101/140577614-fa3ad6f4-cca4-4686-bc5d-18f36bd8c18d.png)

![timer-remove](https://user-images.githubusercontent.com/1837101/140577658-5367eab8-a3e1-46b3-9e65-d6039de1f1f0.png)
![timer-remove-outline](https://user-images.githubusercontent.com/1837101/140577657-946f755c-e672-4e66-af77-2097174c657b.png)

![timer-cancel](https://user-images.githubusercontent.com/1837101/140577610-0142fd54-70e3-40c4-8538-9eabafe1ad3a.png)
![timer-cancel-outline](https://user-images.githubusercontent.com/1837101/140577607-a68d08c6-61f0-41a6-ab82-fca48129fe40.png)

![timer-alert](https://user-images.githubusercontent.com/1837101/140577606-03b23c08-3031-4f24-a058-7a6966359460.png)
![timer-alert-outline](https://user-images.githubusercontent.com/1837101/140577604-2e432b13-4afd-483c-920b-e2dc67821049.png)

![timer-cog](https://user-images.githubusercontent.com/1837101/140577621-ce5216be-20c2-4bb5-8fac-8e01fb6f0f2e.png)
![timer-cog-outline](https://user-images.githubusercontent.com/1837101/140577620-1ba612d5-d3e0-4d3f-b059-63ace1b7f292.png)

![timer-edit](https://user-images.githubusercontent.com/1837101/140577626-100028b6-9c90-4569-9c04-b6f93d4ba5b9.png)
![timer-edit-outline](https://user-images.githubusercontent.com/1837101/140577623-62bedabb-5eb0-43bf-a83e-3b703660c27f.png)

![timer-lock](https://user-images.githubusercontent.com/1837101/140577635-b9424a34-7b5a-40a2-84f6-51c0967c63e8.png)
![timer-lock-outline](https://user-images.githubusercontent.com/1837101/140577634-ab11b8ff-1726-4c76-8f6f-0e6088450ef7.png)

![timer-lock-open](https://user-images.githubusercontent.com/1837101/140577631-ddd3899d-d6e0-45b4-a72c-de173d01df99.png)
![timer-lock-open-outline](https://user-images.githubusercontent.com/1837101/140577630-d5df8f37-22e9-4d3f-a2fa-05921fd402c1.png)

![timer-marker](https://user-images.githubusercontent.com/1837101/140577638-fd0fe0df-a5aa-4e04-a409-06c38651932e.png)
![timer-marker-outline](https://user-images.githubusercontent.com/1837101/140577636-a2595d97-80fe-4814-9371-3d82659c82ee.png)

![timer-refresh](https://user-images.githubusercontent.com/1837101/140577655-25a0a2d9-a01e-4d85-b747-3ae831de345b.png)
![timer-refresh-outline](https://user-images.githubusercontent.com/1837101/140577654-092eafe2-ce12-42d6-a770-cc624dcfcccd.png)

![timer-sync](https://user-images.githubusercontent.com/1837101/140577667-b6a68387-6bcc-4832-8854-56b651615bc0.png)
![timer-sync-outline](https://user-images.githubusercontent.com/1837101/140577666-86859694-abd2-4d6f-9350-d6bae366e959.png)

![timer-star](https://user-images.githubusercontent.com/1837101/140577660-ebdb9fad-edce-4793-9720-d35294960c36.png)
![timer-star-outline](https://user-images.githubusercontent.com/1837101/140577659-695b21f6-5fb2-415d-963c-a10d780e4d11.png)

![timer-play](https://user-images.githubusercontent.com/1837101/140577649-374bd62d-29be-4c1a-bb80-f75badc4b375.png)
![timer-play-outline](https://user-images.githubusercontent.com/1837101/140577648-8f18b978-e871-4ede-8dc8-deed63299804.png)

![timer-pause](https://user-images.githubusercontent.com/1837101/140577647-e6950bbf-db22-44e8-982d-4096869e9f1a.png)
![timer-pause-outline](https://user-images.githubusercontent.com/1837101/140577645-1fd27a18-a551-49f9-84ac-fef0f6e99917.png)

![timer-stop](https://user-images.githubusercontent.com/1837101/140577663-9c968662-879d-469f-822a-6f9ea3090246.png)
![timer-stop-outline](https://user-images.githubusercontent.com/1837101/140577662-331d85be-6c92-46a7-92f5-7203c99d9f1a.png)

![timer-music](https://user-images.githubusercontent.com/1837101/140577643-45d4c863-5f70-4d3a-ae45-22816a5bbd0e.png)
![timer-music-outline](https://user-images.githubusercontent.com/1837101/140577641-fbfbf15b-d2ff-48b3-a4a8-4f50724e530a.png)

### Upload the icon source.

[timer-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/7488903/timer-modifiers.zip)

**Comment by goyney** [comment]
Extensive. 👏🏼

**Comment by goyney** [comment]
All added.
