### ISSUE TITLE
Update `sort-variant-lock*` icons to use standard lock modifier

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#6311]
![image](https://user-images.githubusercontent.com/7819991/140588080-5311d7f3-d3f0-4724-95ac-9b312fbf2110.png) ![image](https://user-images.githubusercontent.com/7819991/140588427-67cf781a-c26f-4036-a75a-50784e07e3bf.png)

I did not use a cutout because the missing padding is less than a pixel. The middle line could be shortened by 1 pixel to give the lock more space while also keeping the path complexity low...

[sort-variant-lock.zip](https://github.com/Templarian/MaterialDesign/files/7489299/sort-variant-lock.zip)

**Comment by goyney** [comment]
Updated.
