### ISSUE TITLE
Bulkhead Light

### ISSUE THREAD

**Issue by rclark213** [Templarian/MaterialDesign#6312]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'd like to request an icon to represent a **bulkhead light**. Essentially, a caged enclosure to protect bulbs, common in public and industrial spaces. 

### Give us an example of what this icon might look like.

Please see [this Google search](https://www.google.com/search?q=bulkhead+light+icon&sxsrf=AOaemvJHXQgiH-oYBRTTUQy2rdJuqQZfTA:1636154223214&source=lnms&tbm=isch&sa=X&ved=2ahUKEwjSt5a6rYL0AhXfDzQIHVV8CAIQ_AUoAXoECAEQAw&biw=1306&bih=1283&dpr=1#imgrc=VRC9REHjpKMMFM) as well as a rough idea of what I think the icon could look like attached.
![light_bulkhead_black_small](https://user-images.githubusercontent.com/2693295/140589374-5ed87714-15cb-4a8f-b901-7ad95031f39e.png)

![light_bulkhead_white_small](https://user-images.githubusercontent.com/2693295/140589376-d32d34ad-338e-47ae-8f7d-738520a92696.png)

**Comment by goyney** [comment]
[![bulkhead-light](https://materialdesignicons.com/icon/bulkhead-light)](https://materialdesignicons.com/icon/bulkhead-light)

**Comment by rclark213** [comment]
Thanks!
