### ISSUE TITLE
Standard position of lock modifier?

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#6313]
Most icons seem to have the lock placed in the bottom right corner, 2 pixels from the bottom, 1 pixel from the side. However, the account-lock icons have it 1 pixel from the bottom, 2 from the side:

![image](https://user-images.githubusercontent.com/7819991/140588860-585295a7-0c94-4fbe-b31d-c054015a367e.png)

Was that done on purpose to avoid a weird cutout shape with the outline versions? (Nothing is mentioned in #2356)

![image](https://user-images.githubusercontent.com/7819991/140589357-eb2f808c-10e4-4f82-8e4f-4e2e8cd334fa.png)

**Comment by goyney** [comment]
Most likely, yes. Anytime a modifier isn't in the standard place, it is usually for optical correctness. In the case of `account-*-outline`, this is the case.
