### ISSUE TITLE
Filters Multiple

### ISSUE THREAD

**Issue by demienYu** [Templarian/MaterialDesign#6314]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This icon could be used for a list of filters

### Give us an example of what this icon might look like.

Same as Bookmark Multiple, but Filter instead of bookmark

**Comment by HAOccassionalUser** [comment]
aquarium filters

**Comment by demienYu** [comment]
what do u mean?

**Comment by Simran-B** [comment]
@HAOccassionalUser Please create a separate issue if you want to request an aquarium filter icon.

**Comment by Simran-B** [comment]
![image](https://user-images.githubusercontent.com/7819991/141018017-6fc9494d-d9d3-4c04-9b31-eab5e23b6fcd.png) ![image](https://user-images.githubusercontent.com/7819991/141018048-e3a2ad83-564b-4bae-b3a8-d597b2046c10.png)
![image](https://user-images.githubusercontent.com/7819991/141018061-3094bfbc-1cb0-44ce-bda9-ea324fa8577e.png) ![image](https://user-images.githubusercontent.com/7819991/141018083-39a52434-cca7-4379-a0d0-4ac241ec392c.png)
![image](https://user-images.githubusercontent.com/7819991/141018098-5a51027b-5073-4df4-a990-3b4db62912e1.png) ![image](https://user-images.githubusercontent.com/7819991/141018130-6b50023f-057b-4b1c-9067-82cacb25c6ef.png)
![image](https://user-images.githubusercontent.com/7819991/141018151-4ab61821-77f7-4fce-9de0-768309d57e81.png) ![image](https://user-images.githubusercontent.com/7819991/141018176-ac4cd986-b5f5-4df7-8017-b0636102dd09.png)
![image](https://user-images.githubusercontent.com/7819991/141018921-38d6b5c2-b8a9-4cf1-b388-ce7d27bddbb0.png) ![image](https://user-images.githubusercontent.com/7819991/141019643-b71125f2-9972-4900-882e-b93f92192847.png)

[filter-multiple.zip](https://github.com/Templarian/MaterialDesign/files/7508536/filter-multiple.zip)

**Comment by demienYu** [comment]
I think filter-multiple 10 is ok.
So we need outline version too.

**Comment by Simran-B** [comment]
![image](https://user-images.githubusercontent.com/7819991/141196541-889e3ecc-99d5-4225-b9c7-3aa6fdab4209.png)
[filter-multiple-outline10.zip](https://github.com/Templarian/MaterialDesign/files/7516048/filter-multiple-outline10.zip)

**Comment by goyney** [comment]
[![filter-multiple](https://materialdesignicons.com/icon/filter-multiple)](https://materialdesignicons.com/icon/filter-multiple)[![filter-multiple-outline](https://materialdesignicons.com/icon/filter-multiple-outline)](https://materialdesignicons.com/icon/filter-multiple-outline)
