### ISSUE TITLE
led-strip-variant-off

### ISSUE THREAD

**Issue by capandcamera** [Templarian/MaterialDesign#6315]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Displaying the state of a light strip that is currently off, to be used in conjunction with led-strip-variant

### Give us an example of what this icon might look like.

[led-strip-variant-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/7507028/led-strip-variant-off.svg.zip)

**Comment by Simran-B** [comment]
The canvas has a wrong size (100x100) and there are multiple paths (that InkScape refuses to merge correctly).

**Comment by goyney** [comment]
[![led-strip-variant-off](https://materialdesignicons.com/icon/led-strip-variant-off)](https://materialdesignicons.com/icon/led-strip-variant-off)
