### ISSUE TITLE
Filter Settings

### ISSUE THREAD

**Issue by Simran-B** [Templarian/MaterialDesign#6316]
`filter` + `settings` / `cog` modifier (not sure about the latter, should the base icon be shifted to the left to make it look less weird?)

![image](https://user-images.githubusercontent.com/7819991/141024501-cb02d07b-b996-4547-af02-915283689f84.png) ![image](https://user-images.githubusercontent.com/7819991/141024460-1c081e17-8922-4ee3-8614-7e363786155a.png)
![image](https://user-images.githubusercontent.com/7819991/141024585-9b6876e1-955e-4756-8518-8027b9ebbb94.png) ![image](https://user-images.githubusercontent.com/7819991/141024641-efae493c-9f3a-479d-96fc-73b47e79f86e.png)

[filter-settings.zip](https://github.com/Templarian/MaterialDesign/files/7508720/filter-settings.zip)

**Comment by Simran-B** [comment]
![image](https://user-images.githubusercontent.com/7819991/141025213-43f02cdc-8496-4157-85a8-09b5330c0a8d.png) ![image](https://user-images.githubusercontent.com/7819991/141025245-d51978d9-26db-4017-b00b-1bc11e1702b2.png)

[filter-cog2.zip](https://github.com/Templarian/MaterialDesign/files/7508777/filter-cog2.zip)

**Comment by goyney** [comment]
[![filter-settings](https://materialdesignicons.com/icon/filter-settings)](https://materialdesignicons.com/icon/filter-settings)[![filter-settings-outline](https://materialdesignicons.com/icon/filter-settings-outline)](https://materialdesignicons.com/icon/filter-settings-outline)
[![filter-cog](https://materialdesignicons.com/icon/filter-cog)](https://materialdesignicons.com/icon/filter-cog)[![filter-cog-outline](https://materialdesignicons.com/icon/filter-cog-outline)](https://materialdesignicons.com/icon/filter-cog-outline)
