### ISSUE TITLE
Home-rounded filled and outline

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6317]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Home icon for button on tab bar menu.
filled and outline version

### Give us an example of what this icon might look like.

![round_home_black_24dp](https://user-images.githubusercontent.com/88420807/141212351-65edaaf7-d1dc-4fae-b288-43bf9250c9fd.png)

**Comment by goyney** [comment]
This is not a variant style we're currently offering in this library.
