### ISSUE TITLE
task-add

### ISSUE THREAD

**Issue by adalmagro** [Templarian/MaterialDesign#6318]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

In our web application we are developing a task section so we need to manage tasks (adding, removing, etc). The button with the icon will trigger a new task action

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/504739/141277637-27f061e4-f0c7-4575-b1d5-0e3f3fe3e373.png)

### Upload the icon source.

[task-add.svg.zip](https://github.com/Templarian/MaterialDesign/files/7519466/task-add.svg.zip)

**Comment by goyney** [comment]
This is a double-modifier case that I feel doesn't work. We've had this request in the past and we have another icon for adding tasks that is probably more appropriate for this use case:
[![checkbox-marked-circle-plus-outline](https://materialdesignicons.com/icon/checkbox-marked-circle-plus-outline)](https://materialdesignicons.com/icon/checkbox-marked-circle-plus-outline)

**Comment by Simran-B** [comment]
The clipboard icons can also stand for tasks
