### ISSUE TITLE
Is there a reason why package file is not being cached in site?

### ISSUE THREAD

**Issue by chaosifier** [Templarian/MaterialDesign#6319]
![image](https://user-images.githubusercontent.com/7871740/141280426-2bce8a06-863a-41f2-bd0e-237b87427bc3.png)

The file is loaded in every request. I think the sight would be a lot faster if static files are cached.

![image](https://user-images.githubusercontent.com/7871740/141280636-f5b27aae-0ee3-4b25-a163-24f695dd4c30.png)

**Comment by goyney** [comment]
Because the old site wasn't designed for 6500+ icons. There's a new site in development. See the stickied issue. We won't be making any changes to the old site.
