### ISSUE TITLE
no-bones/bone-off icon

### ISSUE THREAD

**Issue by jordandrako** [Templarian/MaterialDesign#6321]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'm making a Bones/No Bones sensor using the api from https://nobones.info/ and would like my sensor icon to be a bone or bone-off.

### Give us an example of what this icon might look like.

The bone icon with a slash through it indicated an off state.
![image](https://user-images.githubusercontent.com/7110658/141525575-3b73a3f5-be88-49a6-8c10-6049e3bc8430.png)

**Comment by Simran-B** [comment]
Not sure about the best placement for the strikethrough. It seems unavoidable to cross both ends of the bone, which makes it a little hard to recognize IMO

![image](https://user-images.githubusercontent.com/7819991/141538906-5d595b7c-9872-46e9-b84b-6c4338a28a8d.png)

Would be a lot nicer like this but here we are confined to the 24dp canvas...

![image](https://user-images.githubusercontent.com/7819991/141539125-d8c99e60-1c3d-4810-86d4-c317fa65042f.png)

**Comment by jordandrako** [comment]
Thank you! I think iteration 1 reads alright.

**Comment by goyney** [comment]
[![bone-off](https://materialdesignicons.com/icon/bone-off)](https://materialdesignicons.com/icon/bone-off)
