### ISSUE TITLE
bulb-alert, bulb-question

### ISSUE THREAD

**Issue by frenck** [Templarian/MaterialDesign#6322]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

With Home Assistant, some devices can tell you the bulb is broken or you can "identify" the bulb.

- For example, Fibaro Switches have an indicator of whether the bulb is broken or not.
- Most Zigbee bulbs (e.g, Hue & Ikea) have a way to trigger an "identify" action. This makes the bulb blink and is helpful if you have a bunch of them and want to know which one you are working with.

For that reason I would love to see a variant on these user icons:

![image](https://user-images.githubusercontent.com/195327/141614539-b8f0ca87-283d-47a5-ac18-1f00a2cb9eb6.png)
![image](https://user-images.githubusercontent.com/195327/141614543-76cf1807-c938-49fe-9e81-5259fbfec8c8.png)

### Give us an example of what this icon might look like.

Similar to what is done for bulb-auto:

![image](https://user-images.githubusercontent.com/195327/141614558-fb914b45-fe1d-4d5f-b93d-3a24f5237a3a.png)

But with a exclamation or question mark :)

**Comment by goyney** [comment]
[![lightbulb-alert](https://materialdesignicons.com/icon/lightbulb-alert)](https://materialdesignicons.com/icon/lightbulb-alert)[![lightbulb-alert-outline](https://materialdesignicons.com/icon/lightbulb-alert-outline)](https://materialdesignicons.com/icon/lightbulb-alert-outline)
[![lightbulb-question](https://materialdesignicons.com/icon/lightbulb-question)](https://materialdesignicons.com/icon/lightbulb-question)[![lightbulb-question-outline](https://materialdesignicons.com/icon/lightbulb-question-outline)](https://materialdesignicons.com/icon/lightbulb-question-outline)

**Comment by frenck** [comment]
Nice! Thanks @goyney ❤️
