### ISSUE TITLE
Can Light

### ISSUE THREAD

**Issue by makeitworktech** [Templarian/MaterialDesign#6323]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In Home Assistant for my can light buttons. Can lights, or recessed lights, are cylindrical shaped "cans" with a socket in them. They typically take BR30 bulbs.

### Give us an example of what this icon might look like.

https://www.shutterstock.com/image-vector/vector-illustration-modern-ceiling-lamp-flat-1155796885

**Comment by goyney** [comment]
#1846 #4146. Search.
