### ISSUE TITLE
cloud-percent

### ISSUE THREAD

**Issue by ben222b** [Templarian/MaterialDesign#6324]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I use sensor.weather_cloudiness on my HA dashboard, but there is no mdi icon that reflects cloud cover %

### Give us an example of what this icon might look like.

I would like to use an mdi icon with a percent sign on a dark cloud, like the following for ? and !

![image](https://user-images.githubusercontent.com/49306461/141644843-b32a6ae2-afba-4efb-98f8-1e44d6dcb244.png)
![image](https://user-images.githubusercontent.com/49306461/141644856-b46dda62-2cf7-48f9-9b00-465e49313fec.png)

Roughly something like this 
![image](https://user-images.githubusercontent.com/49306461/141645024-579fa2f8-62cb-4e46-a2b4-ccc822971a08.png)

**Comment by Simran-B** [comment]
![image](https://user-images.githubusercontent.com/7819991/141702908-49b4f2ec-f219-426d-8749-dcd0c5f69794.png) ![image](https://user-images.githubusercontent.com/7819991/141702912-b5a34e67-0df1-4025-8ed4-e8d2b5314b3e.png)

[cloud-percent.zip](https://github.com/Templarian/MaterialDesign/files/7534911/cloud-percent.zip)

**Comment by Simran-B** [comment]
On second thought, if this is for something weather-related then the proper base icon would be `weather-cloudy`. There's little room to work with, though:

![image](https://user-images.githubusercontent.com/7819991/141848025-fae00230-6aa0-487f-a079-48375ef275d4.png)

[weather-cloudy-percent.zip](https://github.com/Templarian/MaterialDesign/files/7541420/weather-cloudy-percent.zip)

**Comment by ben222b** [comment]
My use case is weather, but I could see a use case for IT applications - percent uploaded to the cloud, percent of cloud resources available. Your first idea (cloud-percent and cloud-percent-outline) would be more flexible.

**Comment by goyney** [comment]
[![cloud-percent](https://materialdesignicons.com/icon/cloud-percent)](https://materialdesignicons.com/icon/cloud-percent)[![cloud-percent-outline](https://materialdesignicons.com/icon/cloud-percent-outline)](https://materialdesignicons.com/icon/cloud-percent-outline)
