### ISSUE TITLE
FR Zigbee variants

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#6326]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

considering we have mdi:zigbee, I am not sure this is a so called 'brand' icon. If not, please consider adding zigbee-alert and zigbee-off, with the usual visual items.

this is to alert zigbee connectivity obvious, and needed to distinguish between states connected (the current mdi:zigbee), disconnected (request zigbee-off) and not available (request zigbee-alert)

thanks for considering!

### Give us an example of what this icon might look like.

as said above: please consider adding zigbee-alert and zigbee-off, with the usual visual items.

**Comment by Templarian** [comment]
We don't add modifiers to Brand iconography. This would need to be handled with a more generic icon.
