### ISSUE TITLE
download-forbidden & download-enabled

### ISSUE THREAD

**Issue by timautin** [Templarian/MaterialDesign#6327]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

My app proposes content for download. Some content can be downloaded for free, some can be downloaded if the user is subscribed, and some can't be downloaded.

We already have a download-locked icon, but it would be great to have download-forbidden & download-enabled icons as well.

### Give us an example of what this icon might look like.

These icons would be like the download-locked icon: ![download-lock](https://user-images.githubusercontent.com/3846288/141657822-e6ec6652-df8c-4748-bbb3-1c9c336ecbb1.png), but with a forbidden ![cancel](https://user-images.githubusercontent.com/3846288/141657837-a01a7edb-26b0-410a-a383-16891695159c.png) and a checkmark ![check](https://user-images.githubusercontent.com/3846288/141657842-0a3ec229-aa3b-425d-af9a-979985fe138a.png) sign at the bottom right corner instead of the lock.

**Comment by Simran-B** [comment]
![image](https://user-images.githubusercontent.com/7819991/141702343-3036b2db-8d93-4fa6-a429-0fc5562833a4.png) ![image](https://user-images.githubusercontent.com/7819991/141702350-eb635505-2e6f-4104-8ba7-63941f52abf1.png)
![image](https://user-images.githubusercontent.com/7819991/141702358-77b3be68-28f4-413a-9b72-2655f8c69b36.png) ![image](https://user-images.githubusercontent.com/7819991/141702368-73fd8716-9c3d-424f-9fda-c3dd1bf761b2.png)
![image](https://user-images.githubusercontent.com/7819991/141702373-7c8e117d-4008-4c49-8464-76956f4b9741.png) ![image](https://user-images.githubusercontent.com/7819991/141702377-9533322e-e5fd-49da-b02c-18e8cde8ac37.png)
![image](https://user-images.githubusercontent.com/7819991/141702382-8d3080ff-2d6e-4ac4-85a9-d79583ec879e.png) ![image](https://user-images.githubusercontent.com/7819991/141702389-32abd3b5-b752-46e4-abdd-956fec6bc812.png)

[download-upload-cancel-check.zip](https://github.com/Templarian/MaterialDesign/files/7534889/download-upload-cancel-check.zip)

**Comment by timautin** [comment]
This looks perfect, thank you very much! Not sure what is the procedure to add them to the website now?

**Comment by Simran-B** [comment]
If the core team agrees to accept these icons, then they will be added to the system (at which point they will show up on the website) and scheduled for release (this can take some time).

**Comment by timautin** [comment]
Thanks, I'll wait & see then 🙂

**Comment by goyney** [comment]
These do not feel right. I do not like them and think we should brainstorm other ideas for this concept.

**Comment by timautin** [comment]
🤔 What's wrong with them?

**Comment by goyney** [comment]
They seem... bad. It's my gut reaction.

More semantically, we have never put modifiers on an arrow before, which this icon essentially is. The only differentiator is the line at the bottom, which half of it is cut away by the modifier.

I simply do not think they work and vote no in their current form.

**Comment by timautin** [comment]
Well they are exactly like the download-lock / upload-lock icons. There are also the auto-download / auto-upload showing an arrow with a modifier.

**Comment by goyney** [comment]
The auto one is fine, but ick to those lock ones as well. We should consider updating them as well if we determine a better way to handle this use case.

**Comment by timautin** [comment]
Well I'd have put the A on the right side on the auto-download. Anyway the *-lock look fine to me, let's wait for more opinions.

**Comment by goyney** [comment]
Revisiting this. I still feel these suggestions do not work and that we have icons to support this use case.

`download-off` quite clearly means that you cannot download something, while the normal variant means you can.
[![download-off](https://materialdesignicons.com/icon/download-off)](https://materialdesignicons.com/icon/download-off)

At this time, we're not going to add these icons. You may download the proposed contributions above and use them direction in your app if you would like. Thank you for your suggestion.
