### ISSUE TITLE
Material Pets icon

### ISSUE THREAD

**Issue by japayne27** [Templarian/MaterialDesign#6328]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

The Material Design Icons pets icon is missing. I'd prefer to use the Material Design icon to the custom one that's available.

### Share a preview of your contribution.

![download](https://user-images.githubusercontent.com/8763539/141822974-8cdd6536-cb3f-42bf-8f11-86d7b38bbe8a.png)

### Upload the icon source.

[pets.zip](https://github.com/Templarian/MaterialDesign/files/7540317/pets.zip)

**Comment by goyney** [comment]
Already exists. Please search. [![paw](https://materialdesignicons.com/icon/paw)](https://materialdesignicons.com/icon/paw)

**Comment by japayne27** [comment]
@goyney that's very different to the Material one, I thought the intention of this library is to use the Material ones where possible?

Here's the Material one (black) with your custom one (red) overlaid.

![Artboard 1](https://user-images.githubusercontent.com/8763539/141824127-a94ce71c-e72f-47df-959c-d1e9622d7c36.png)

**Comment by Templarian** [comment]
@japayne27 If I recall we tweaked this one to give it a more paw shape to allow the outline version to be more readable. Material may do the same eventually when they add an outline version.

While we will often prefer official icons not all the designs work visually. Since 4.0+ we've spent significant time adding outline support as a large number of applications prefer that style.
