### ISSUE TITLE
sort-variant-off

### ISSUE THREAD

**Issue by Voodu** [Templarian/MaterialDesign#6333]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Variant of `sort-variant` with off line (same as ex. `label-off`) 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/24680898/142178793-4efb7d62-e961-475b-96a2-016ffc79712f.png)

### Upload the icon source.

[sort-variant-off.zip](https://github.com/Templarian/MaterialDesign/files/7553617/sort-variant-off.zip)

**Comment by Templarian** [comment]
Hmm, `sort-variant-remove` might make more sense? It's still pretty readable with `-off`, so not against adding it.

**Comment by Voodu** [comment]
Sure, `sort-variant-remove` sounds a bit better

**Comment by Templarian** [comment]
@Voodu I meant there is an existing icon `sort-variant-remove` that might work for this.

**Comment by Voodu** [comment]
@Templarian Ah, okay, I get it.

I think that `off` variant is still useful for apps using `off`-style icons in multiple places. At least that was a reason I made it - we don't have any `remove` style icons, only `off`.

**Comment by goyney** [comment]
[![sort-variant-off](https://materialdesignicons.com/icon/sort-variant-off)](https://materialdesignicons.com/icon/sort-variant-off)
