### ISSUE TITLE
track-light-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#6337]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

to indicate my outside flood/tracklights state. I have a dedicated script/button to turn on/off all outside track lights in case of emergency.

would be great if I could see the state of that easily reflected in the icon being on/off.
thanks for considering.

### Give us an example of what this icon might look like.

just add the simple diagonal line, and it would be perfect.

**Comment by goyney** [comment]
[![track-light-off](https://materialdesignicons.com/icon/track-light-off)](https://materialdesignicons.com/icon/track-light-off)
