### ISSUE TITLE
Battery with clock

### ISSUE THREAD

**Issue by tengl** [Templarian/MaterialDesign#6338]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I needed an icon to tell the user that power save mode will be enabled soon. It can also be used as an icon to tell users how long time the battery will last. 

I'm not an expert in working with SVG, I just hacked it in Inkscape. I took the existing battery and clock icons and resized them and removed a part of the battery. I followed the directions as far as I could understand them. 

I would be happy if someone could help me tidy it up and include it in this library. 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/590967/142863675-afda0850-4fae-4963-8e80-7bbb4b6fe6f2.png)

### Upload the icon source.

[battery-timer.zip](https://github.com/Templarian/MaterialDesign/files/7581042/battery-timer.zip)

**Comment by Templarian** [comment]
@Xenomorph99 If you correct/add this one (with `-outline`).

Also realized we don't have a `home-clock`. 🤔

**Comment by Xenomorph99** [comment]
Here's `battery` and `battery-outline` with our standard `-clock` overlay:

![battery-clock](https://user-images.githubusercontent.com/1837101/143066866-541fda3d-31e7-4a3a-b1e7-02cb247d43b1.png)
![battery-clock-outline](https://user-images.githubusercontent.com/1837101/143066873-5d8689d7-ce8b-415c-b0cf-1aca7d0f6060.png)

[battery-clock.zip](https://github.com/Templarian/MaterialDesign/files/7589686/battery-clock.zip)

**Comment by Xenomorph99** [comment]
These icons have been added.

**Comment by tengl** [comment]
Nice! Thanks 👍
