### ISSUE TITLE
Augmented Reality Icon

### ISSUE THREAD

**Issue by PhilLab** [Templarian/MaterialDesign#634]
An icon to represent an Augmented Reality Mode. Possible ideas:
- stylized version of Google glass. **Con:** glass is an outdated product
- A device screen with a stylized augmented object

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/hololens ?

**Comment by PhilLab** [comment]
oh, I didn't see that one. It is a nice icon for Hololens when you expect it - e.g. when choosing between devices. But as a general icon for AR it does not fit well. I admit that we would have the same problem with a glass-based icon.

**Comment by Templarian** [comment]
Same issue comes up when someone asks for a VR icon. Kind of a hard thing to show in the small size.

Hmm... probably a nice metaphor or a way of combining two symbols to show it. `Glasses` + `???`.

**Comment by GreenTurtwig** [comment]
![](https://user-images.githubusercontent.com/15905797/35972137-83c93ee2-0cc8-11e8-8bc6-32a95654e152.png)![](https://user-images.githubusercontent.com/15905797/35972122-73ebd03e-0cc8-11e8-845a-a94ec17f42b8.png)
[vr-ar.zip](https://github.com/Templarian/MaterialDesign/files/1706937/vr-ar.zip)

**Comment by Templarian** [comment]
[![augmented-reality](https://materialdesignicons.com/icon/augmented-reality)](https://materialdesignicons.com/icon/augmented-reality) [![mixed-reality](https://materialdesignicons.com/icon/mixed-reality)](https://materialdesignicons.com/icon/mixed-reality) [![virtual-reality](https://materialdesignicons.com/icon/virtual-reality)](https://materialdesignicons.com/icon/virtual-reality)
