### ISSUE TITLE
Home Clock

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6340]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

As @Templarian mentioned on #6338, we don't have a `home-clock` or `home-clock-outline` icon. I included two options here for review.

**Option A:** `home` icon remains center aligned with `-clock` overlay
**Option B:** `home` icon shifted 1 dps up and to the left with `-clock` overlay

### Option A
![home-clock-a](https://user-images.githubusercontent.com/1837101/143066438-31d270f0-8904-48c4-b016-871f911c615a.png)
![home-clock-outline-a](https://user-images.githubusercontent.com/1837101/143066426-80e56573-6675-4548-88f1-65cc906501d2.png)

### Option B
![home-clock-b](https://user-images.githubusercontent.com/1837101/143066443-3cf87831-9d62-4ffa-8314-1ff84c9d4200.png)
![home-clock-outline-b](https://user-images.githubusercontent.com/1837101/143066433-9c3b33f2-fcf2-4508-99fa-350ff7e86b8e.png)

### Upload the icon source.

[home-clock.zip](https://github.com/Templarian/MaterialDesign/files/7589673/home-clock.zip)

**Comment by Templarian** [comment]
Hmm... yeah not sure this works that well with either option. 🤔

**Comment by goyney** [comment]
Use the version of the home without the door, and push it over to the left 1 or 2dp.

**Comment by Xenomorph99** [comment]
@goyney thanks for the suggestion - this looks much better.

![home-clock](https://user-images.githubusercontent.com/1837101/144656327-a447564f-a43a-484b-9cd7-a77dce49edc7.png)
![home-clock-outline](https://user-images.githubusercontent.com/1837101/144656323-30ff80b7-aa5b-4429-a1fe-5281d39ea65a.png)

[home-clock.zip](https://github.com/Templarian/MaterialDesign/files/7651730/home-clock.zip)

**Comment by Templarian** [comment]
Added!
