### ISSUE TITLE
Alert Overlay

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6341]
### What is your question?

I just added all of the icons in #6308, but discovered we already have `folder-alert` and `folder-alert-outline`. I didn't realize we'd introduced a circular alert overlay. (Previous discussions in #4908 and #3918). Personally, I like having the option of using the circular alert overlay.

_My question is should we continue using the circular alert overlay and if so in what situations?_

#### Circular Alert Overlay
As reference, these are the icons we currently have in our library:
![folder-alert (1)](https://user-images.githubusercontent.com/1837101/143073211-9511785d-8287-4691-9abe-8a33a271c6ae.png)
![folder-alert-outline (1)](https://user-images.githubusercontent.com/1837101/143073222-550f7d85-5855-459c-84a0-5c5766152a07.png)

#### Standard Alert Overlay
These are the unused icons I created for #6308. I had to slightly shrink the folder's width to make space for the exclamation point.
![folder-alert](https://user-images.githubusercontent.com/1837101/143073239-4000dec6-0fd8-4e5e-a1ea-5ed46caf6c16.png)
![folder-alert-outline](https://user-images.githubusercontent.com/1837101/143073231-4533ce09-6f00-410b-89c7-3a4bfa4b9e74.png)

**Comment by Templarian** [comment]
I definitely like the circle alert more for folders. Possibly when we have to push the `!` very far to the right and it doesn't mess up the meaning of the base icon.

**Comment by goyney** [comment]
The circular alert modifiers is done in extreme circumstances where the normal alert modifier doesn't really work and must be approved by the contributor team before being added. I agree with Templarian that the use of it with folder was the correct choice.
