### ISSUE TITLE
Stick vacuum variant

### ISSUE THREAD

**Issue by jaimevisser** [Templarian/MaterialDesign#6342]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To turn on/off the charger for my vacuum using Home Assistant. The current vacuum icon works but looks nothing like mine (and confuses my wife to no end). Maybe add a "vacuum-variant" or "stick-vacuum"?

### Give us an example of what this icon might look like.

https://thenounproject.com/term/lightweight-upright-vacuum-cleaner/960544/

https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/product-selector/illustrations/cordless-stick-vacuums.png?$responsive$&fmt=png-alpha&cropPathE=mobile&fit=stretch,1&wid=640

https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/leap-petite-global/products/floorcare/sticks/248l-j/variants/nickel-blue-bb/V11-Absolute-Extra-gallery-hero-1.png?fmt=png-alpha&scl=1&fmt=png-alpha

**Comment by goyney** [comment]
Several of these were considered when we added vacuum. We went with something generic that encased several different styles. As a rule, we do not add specific products as icons and I do not think we need any more variations of a vacuum, less the hand-vacuum which already has an open issue. Thanks for your suggestion.
