### ISSUE TITLE
clapping-off/stop-clapping

### ISSUE THREAD

**Issue by FANMixco** [Templarian/MaterialDesign#6343]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To indicate silence when you are clapping.

### Give us an example of what this icon might look like.

We just need a diagonal over the current clapping icon:
![image](https://user-images.githubusercontent.com/1666156/143586097-3356f267-f46b-4dfe-bf88-219d38222e06.png)

That would be enough.

**Comment by goyney** [comment]
[![hand-clap-off](https://materialdesignicons.com/icon/hand-clap-off)](https://materialdesignicons.com/icon/hand-clap-off)
