### ISSUE TITLE
Image with Refresh and Sync modifiers

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6346]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For updating image file

### Give us an example of what this icon might look like.

image-outline , email-sync-outline, refresh

**Comment by Xenomorph99** [comment]
![image-refresh](https://user-images.githubusercontent.com/1837101/144097162-d241ccaa-8afe-417a-9cdc-a71bbcab7e04.png)
![image-refresh-outline](https://user-images.githubusercontent.com/1837101/144097152-5590b34a-d0df-4c5e-bc49-d57a66e1c996.png)

![image-sync](https://user-images.githubusercontent.com/1837101/144097180-ccb6e1a1-102b-45ce-b8be-5d603beb52f4.png)
![image-sync-outline](https://user-images.githubusercontent.com/1837101/144097172-cb00cbc9-27ae-44b6-97f0-c9ed588d2e0b.png)

[image-refresh-and-sync.zip](https://github.com/Templarian/MaterialDesign/files/7627596/image-refresh-and-sync.zip)

**Comment by Xenomorph99** [comment]
All added
