### ISSUE TITLE
Camera with lock icon

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6347]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To encrypt or add password to a camera 

### Give us an example of what this icon might look like.

Camera-outline with lock-outline

**Comment by Templarian** [comment]
Something like this?

![image](https://user-images.githubusercontent.com/338885/150727075-55c0e3b9-3cd4-4ec5-9b4d-810af6734490.png) ![image](https://user-images.githubusercontent.com/338885/150727126-fa70e3a1-65e3-4c67-bebf-f7ae0f0811b7.png)
