### ISSUE TITLE
Line of Sight(LoS)

### ISSUE THREAD

**Issue by atulsinghrajpoot** [Templarian/MaterialDesign#6348]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

1. an imaginary straight line running through aligned sights, or between two building/tower/object. 
2. an imaginary straight line that connects the center of the eye with the point focused on.

What Does Line of Sight (LoS) Mean? 
Line of sight (LoS) is a type of propagation that can transmit and receive data only where transmit and receive stations are in view of each other without any sort of an obstacle between them. FM radio, microwave and satellite transmission are examples of line-of-sight communication.

### Give us an example of what this icon might look like.

![los1](https://user-images.githubusercontent.com/18349866/144203361-5b28cd80-3d9f-4498-803d-216792e4324a.jpeg)
![los3](https://user-images.githubusercontent.com/18349866/144203368-8ad993b7-3062-47b8-be42-834ac8fedd82.jpeg)
![los5](https://user-images.githubusercontent.com/18349866/144203373-8751b2bd-faf4-4617-82ba-3b06a7b29d58.png)

**Comment by goyney** [comment]
I'm unsure on how we would indicate this in an icon. Some quick searches show common uses include an eye or cross-hairs, both of which we have. Your examples clearly indicate what you're trying to accomplish, but don't lend themselves well to a small icon.

Do you any other ideas of what this might look like? If not, I would recommend using either an eye (and eye-off for broken LOS), or the crosshairs.
