### ISSUE TITLE
window shutter icon with cog icon for represent configuration

### ISSUE THREAD

**Issue by nbranquinho** [Templarian/MaterialDesign#6349]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

An icon for represent the configuration of roller shutter. For example, to configure the time to open/close (in homeassistant for example) or the % of lift during the operation...

### Give us an example of what this icon might look like.

The joining of the 
window-shutter icon and cog-outline

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/159059426-368272a0-0c85-4764-b4a8-348ec1f49f72.png)![image](https://user-images.githubusercontent.com/1015040/159059452-a13e0225-2e9c-4cfb-96a4-fe440b9c5441.png)

[window-shutter.zip](https://github.com/Templarian/MaterialDesign/files/8306722/window-shutter.zip)

**Comment by goyney** [comment]
Both added.
