### ISSUE TITLE
ic_trophy_outline

### ISSUE THREAD

**Issue by BapediBoupi** [Templarian/MaterialDesign#635]
ic_trophy and variants in outline mode would be great !

Thanks !

**Comment by CoDEmanX** [comment]
![trophy-outline](https://cloud.githubusercontent.com/assets/1309249/9827885/58f65674-58e7-11e5-8147-4aa3365c1aa9.png) https://www.dropbox.com/s/9b9uk825dfb2wg3/trophy-outline.svg?dl=0

![trophy-variant-outline](https://cloud.githubusercontent.com/assets/1309249/9827889/5f0741c2-58e7-11e5-91ce-de24d55b2b4e.png) https://www.dropbox.com/s/qulvsy1oyjf7ck4/trophy-variant-outline.svg?dl=0

The latter is not fully symmetric it seems.

**Comment by Templarian** [comment]
[![trophy-outline](https://materialdesignicons.com/icon/trophy-outline)](https://materialdesignicons.com/icon/trophy-outline) [![trophy-variant-outline](https://materialdesignicons.com/icon/trophy-variant-outline)](https://materialdesignicons.com/icon/trophy-variant-outline)
