### ISSUE TITLE
Addition to the "Forum" icon

### ISSUE THREAD

**Issue by nlsve** [Templarian/MaterialDesign#6350]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Hi, 

My client wanted the forum icon from google with a plus. 

Best regards,
Nicolas

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/92360163/144392764-0c54d4ff-0467-4fc7-96c4-caeb6eab4973.png)
![image](https://user-images.githubusercontent.com/92360163/144392801-ffe64966-198b-4166-b501-354867ed2f89.png)

### Upload the icon source.

[Forum-plus.zip](https://github.com/Templarian/MaterialDesign/files/7640661/Forum-plus.zip)

**Comment by goyney** [comment]
[![forum-plus](https://materialdesignicons.com/icon/forum-plus)](https://materialdesignicons.com/icon/forum-plus)[![forum-plus-outline](https://materialdesignicons.com/icon/forum-plus-outline)](https://materialdesignicons.com/icon/forum-plus-outline)
[![forum-minus](https://materialdesignicons.com/icon/forum-minus)](https://materialdesignicons.com/icon/forum-minus)[![forum-minus-outline](https://materialdesignicons.com/icon/forum-minus-outline)](https://materialdesignicons.com/icon/forum-minus-outline)
[![forum-remove](https://materialdesignicons.com/icon/forum-remove)](https://materialdesignicons.com/icon/forum-remove)[![forum-remove-outline](https://materialdesignicons.com/icon/forum-remove-outline)](https://materialdesignicons.com/icon/forum-remove-outline)

**Comment by MrGrigri** [comment]
I believe a simple plus, minus, remove should work. This looks too busy.
