### ISSUE TITLE
Size of Alpha and Numeric Icons

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6354]
### What is your question?

I understand the size of the `alpha-*` and `numeric-*` icons when they're inside a circle or square, but is there a reason they're so small when they're on their own?

Notice how both `alpha-a` and `numeric-1` have 7 dps on top and bottom! Should we scale them up when they're not contained inside a circle or square so they don't feel so small?

![alpha-a](https://user-images.githubusercontent.com/1837101/144653228-976336c0-51e3-416b-9e6b-b4a090d0b262.png)
![alpha-a-circle](https://user-images.githubusercontent.com/1837101/144653233-107dd631-2c60-4903-9769-00faf1f492cc.png)

![numeric-1](https://user-images.githubusercontent.com/1837101/144653244-ded5e262-0101-40a5-b1b4-20eccd257b8b.png)
![numeric-1-circle](https://user-images.githubusercontent.com/1837101/144653251-3f37c823-f08b-482d-9090-8e6191f5a35d.png)

**Comment by Templarian** [comment]
@Xenomorph99 Consistency mainly. Do you want to make larger version? Not against the idea if it's something you want to invest time making.

**Comment by Xenomorph99** [comment]
Cool, I'll try making a few larger ones and see how it goes before deciding to invest a ton of time in it.

**Comment by Xenomorph99** [comment]
It was actually really simple to create larger versions. Some of the vector points will have to align to 0.5 or 0.25 dps, but it seems acceptable to me.

![alpha-a](https://user-images.githubusercontent.com/1837101/144659934-a5e4a754-af30-4b67-9645-e9446ac95318.png)
![alpha-b](https://user-images.githubusercontent.com/1837101/144659909-9f5994fd-8574-48b7-b496-e1f5cddfec41.png)
![alpha-c](https://user-images.githubusercontent.com/1837101/144659949-ec7e702c-7ef2-4053-aa89-5e7a39aa1e2c.png)
![alpha-d](https://user-images.githubusercontent.com/1837101/144659941-80e72764-197f-4eee-9c18-4da55b723457.png)
![alpha-g](https://user-images.githubusercontent.com/1837101/144659919-147fa82a-3ac5-464c-bcd1-f4aba0b41fb7.png)
![alpha-m](https://user-images.githubusercontent.com/1837101/144659927-c523bd5c-50ea-4f34-8a50-5616eb453e18.png)
![alpha-w](https://user-images.githubusercontent.com/1837101/144659929-c9ee043c-0d1e-46c0-9c89-73081e559751.png)
![alpha-x](https://user-images.githubusercontent.com/1837101/144659913-f1539a27-1685-4b1f-9e9f-b8c9fb56b3fe.png)

**Comment by Xenomorph99** [comment]
Not sure if we'd want these in the library or not, but with the larger `alpha-*` icons, I could also create a series of `alpha-*-plus` and `alpha-*-minus` icons that could be used for grading.

![alpha-a-plus](https://user-images.githubusercontent.com/1837101/144660895-b7170f7a-f320-4d6c-a91f-4ae43393394c.png)
![alpha-a-minus](https://user-images.githubusercontent.com/1837101/144660889-2c078b22-428a-4f1c-a200-34ff531828e1.png)

**Comment by goyney** [comment]
They're that size because of the 2dp rule. Even in your bigger examples, you're off-grid. I don't really care for them, TBH, because if you need them bigger, you can just resize them. The whole point of SVGs. 😄

**Comment by Templarian** [comment]
Yeah, I'm 50/50 on the idea. Seems like if we were to include larger versions they should still be 2dp width and maybe less blocky. 🤷‍♂️  Possibly just as a different icon set entirely?

**Comment by Xenomorph99** [comment]
I just remembered that [Roboto](https://fonts.google.com/specimen/Roboto#glyphs) is Google's standard font and since they created Material Design, it would be fitting if the larger letters matched the style of Roboto instead. Then we could create a set that used the 2dps rule.

**Comment by goyney** [comment]
At that point, just use Roboto.

**Comment by goyney** [comment]
I don't think we're interested in having two different alpha/numeric sets in an icon library at this time. You can resize our current icons if you need them larger. You can use Roboto if you need a true Materialesque typeface.
