### ISSUE TITLE
gate-buffer icon

### ISSUE THREAD

**Issue by the-avid-engineer** [Templarian/MaterialDesign#6356]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

We have almost all of the logic gate icons - the only really simple one that is missing is the buffer gate.

It would appear that the current designs came from @Croutonix in this comment:
https://github.com/Templarian/MaterialDesign/issues/2995#issuecomment-377599750

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/36554739/144731537-5603d92e-e281-42ed-b688-948b7063ee9d.png)

A buffer gate looks pretty much the same as the NOT gate, except there's no circle at the end of it.

**Comment by goyney** [comment]
[![gate-buffer](https://materialdesignicons.com/icon/gate-buffer)](https://materialdesignicons.com/icon/gate-buffer)

**Comment by the-avid-engineer** [comment]
Awesome!
