### ISSUE TITLE
RFID icons

### ISSUE THREAD

**Issue by mateusizoton** [Templarian/MaterialDesign#636]
Great site!!

Can you add some RFID icons, like these:

http://www.psd100.com/rfid-tag-icon/#.Vd3Rgvkziko
http://www.clker.com/cliparts/Q/Z/O/P/n/Z/rfid-reader-md.png

ty

**Comment by Templarian** [comment]
There are 3 NFC icons. I think the one below is what you are looking for.

[![nfc-variant](https://materialdesignicons.com/icon/nfc-variant)](https://materialdesignicons.com/icon/nfc-variant)

**Comment by Templarian** [comment]
Going to close this out as I assume the nfc icon sufficed.
