### ISSUE TITLE
account-network-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#6360]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

for personal devices disconnected from the network, think of mobile phones etc.
using -outline variant for now, but not ad clear in a single view as the -off variant would be

### Give us an example of what this icon might look like.

simply add the diagonal line?

**Comment by goyney** [comment]
[![account-network-off](https://materialdesignicons.com/icon/account-network-off)](https://materialdesignicons.com/icon/account-network-off)[![account-network-off-outline](https://materialdesignicons.com/icon/account-network-off-outline)](https://materialdesignicons.com/icon/account-network-off-outline)
