### ISSUE TITLE
Add Flurries icon

### ISSUE THREAD

**Issue by mhamzamughal86** [Templarian/MaterialDesign#6361]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I am using Azure weather service for that I need icons to show depending on the weather forecast.
Here are the Azure weather icons.
[https://docs.microsoft.com/en-us/azure/azure-maps/weather-services-concepts]
![Screenshot 2021-12-07 091606](https://user-images.githubusercontent.com/55759063/144971251-ebbf3071-5a4d-474a-aba8-bc2276ec419e.png)

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/55759063/144971609-b21973e6-d651-4d4c-ab88-d7e9fc12f553.png)

### Upload the icon source.

[flurries.zip](https://github.com/Templarian/MaterialDesign/files/7665705/flurries.zip)

**Comment by goyney** [comment]
This already exists.

[![weather-snowy-heavy](https://materialdesignicons.com/icon/weather-snowy-heavy)](https://materialdesignicons.com/icon/weather-snowy-heavy)
