### ISSUE TITLE
volcano / volcano-outline

### ISSUE THREAD

**Issue by swtch** [Templarian/MaterialDesign#6362]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

the volcano icon can be used on educational websites or  app, specialized websites or app, video games. Personally I will need it for integration into a theme park app.

### Give us an example of what this icon might look like.

Volcano from font awesome ->[https://fontawesome.com/v5.15/icons/volcano]( https://fontawesome.com/v5.15/icons/volcano)
Volcano from icon 8 -><img src="https://img.icons8.com/material/96/000000/volcano.png"/>

**Comment by goyney** [comment]
[![volcano](https://materialdesignicons.com/icon/volcano)](https://materialdesignicons.com/icon/volcano)[![volcano-outline](https://materialdesignicons.com/icon/volcano-outline)](https://materialdesignicons.com/icon/volcano-outline)
