### ISSUE TITLE
Layout Manipulation Icons

### ISSUE THREAD

**Issue by TonBits** [Templarian/MaterialDesign#6364]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

A set of layout manipulation icons that could be use to represents operations you can do in a layout, table or grid system.

Insert Left Column - an icon that represents inserting a column to the left of a cell
Insert Right Column - an icon that represents inserting a column to the right of a cell
Insert Top Row - an icon that represents inserting a row to the top of a cell 
Insert Bottom Row - an icon that represents inserting a row to the the bottom of a cell

The nearest icons I can find are **mdi-table-column-plus-after** and **mdi-table-column-plus-before** for column related manipulation and **mdi-table-row-plus-after** and **mdi-table-row-plus-before** for row related operations but somehow, these icons are table centric design.

**Applicable usages examples and use cases**.
Dynamic layout construction where a user can create layout dynamically as part of the application.
Customizable grid systems (generating bootstrap row column class)
Component designers - e.g. insert a button to the left or right of a selected button in a horizontal button group.
or inserting above or below a selected component in a vertical button group.
Dashboard systems.
Customizable views.

### Give us an example of what this icon might look like.

I am not a graphics designer but here is a sample images on the 4 related icons. 

Insert Top Row
![insert-top](https://user-images.githubusercontent.com/17241213/145146661-2f8de9dd-b8ec-4fe0-b6f9-53c17b3a74c2.png)

Insert Bottom Row
![insert-bottom](https://user-images.githubusercontent.com/17241213/145146662-a30103ab-6e10-4a3d-acd6-ee9c8caa3fba.png)

Insert Left Column
![insert-left](https://user-images.githubusercontent.com/17241213/145146663-831796de-6e3c-44ec-8d86-fb640921d2f0.png)

Insert Right Column
![insert-right](https://user-images.githubusercontent.com/17241213/145146664-49fcb0a8-9be4-49ec-9f14-35ea0c943cc7.png)

**Comment by goyney** [comment]
These already exist:
[![page-layout-header](https://materialdesignicons.com/icon/page-layout-header)](https://materialdesignicons.com/icon/page-layout-header)[![page-layout-footer](https://materialdesignicons.com/icon/page-layout-footer)](https://materialdesignicons.com/icon/page-layout-footer)
[![page-layout-sidebar-left](https://materialdesignicons.com/icon/page-layout-sidebar-left)](https://materialdesignicons.com/icon/page-layout-sidebar-left)[![page-layout-sidebar-right](https://materialdesignicons.com/icon/page-layout-sidebar-right)](https://materialdesignicons.com/icon/page-layout-sidebar-right)
