### ISSUE TITLE
Construction Site Icon

### ISSUE THREAD

**Issue by mayrhofer-simon** [Templarian/MaterialDesign#6365]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

An Icon for Construction site, showing a wrench and a hammer. Can be used  for Construction site applications, handyman and so on

### Give us an example of what this icon might look like.

![outline_construction_black_24dp](https://user-images.githubusercontent.com/56080914/145369378-cbe19a90-c31e-4272-adb0-b033e6352e1a.png)

**Comment by goyney** [comment]
Already exists.
[![hammer-wrench](https://materialdesignicons.com/icon/hammer-wrench)](https://materialdesignicons.com/icon/hammer-wrench)
