### ISSUE TITLE
seed-plus-outline

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6367]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I'd like to use this icon to represent adding a commodity to a dashboard.

### Share a preview of your contribution.

<img width="1546" alt="Screenshot 2021-12-13 at 15 56 48 from Figma" src="https://user-images.githubusercontent.com/2228347/145902280-e1fdf8b6-c3a4-4d96-9bd7-883d52f3afd0.png">

(Sorry folks, still having the same problem with the preview generator 👇)

<img width="2683" alt="Screenshot 2021-12-13 at 15 57 58 from Google Chrome" src="https://user-images.githubusercontent.com/2228347/145902387-9e3fe7e6-ae8f-44e7-a84d-397a24d74167.png">

### Upload the icon source.

[seed-plus-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/7707458/seed-plus-outline.svg.zip)

**Comment by goyney** [comment]
[![seed-plus](https://materialdesignicons.com/icon/seed-plus)](https://materialdesignicons.com/icon/seed-plus)[![seed-plus-outline](https://materialdesignicons.com/icon/seed-plus-outline)](https://materialdesignicons.com/icon/seed-plus-outline)
