### ISSUE TITLE
projector off

### ISSUE THREAD

**Issue by tompointexe** [Templarian/MaterialDesign#6368]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

use in homeassistant for my projector off button

### Give us an example of what this icon might look like.

![projector](https://user-images.githubusercontent.com/29174751/146056150-d773aa1c-e024-42dd-8cca-6bab45d52149.png)
a verry bad take at what it could look like

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/146817376-6c007e7c-507f-42f8-a6e1-79627a0041f0.png)
[projector-off.svg](https://github.com/terreng/samples/blob/master/projector-off.svg)

**Comment by tompointexe** [comment]
Awsome !! i love it !! 
Looking forward for the release

**Comment by Templarian** [comment]
[![projector-off](https://materialdesignicons.com/icon/projector-off)](https://materialdesignicons.com/icon/projector-off)
