### ISSUE TITLE
Duotone TV icon

### ISSUE THREAD

**Issue by SaiCorporation** [Templarian/MaterialDesign#6370]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

This icon is used as a flutter and html icon template.

### Share a preview of your contribution.

![drawable-svg-2](https://user-images.githubusercontent.com/74317023/146199365-ded3fdb3-b408-4a85-b2a2-2bb9b3a3b01d.png)

### Upload the icon source.

[Duotone TV icon](https://github.com/Templarian/MaterialDesign/files/7719911/Duotone-TV-icon.zip)

**Comment by goyney** [comment]
We do not currently support duotone icons. We hope to at some point in the future. Thanks for the suggestion.

**Comment by SaiCorporation** [comment]
This icon is on our company's Font Amazing website
