### ISSUE TITLE
mdi-account-hard-hat-outline

### ISSUE THREAD

**Issue by matthewblackburn** [Templarian/MaterialDesign#6372]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I am creating a construction CMS where a type of user is labelled as a "Technician". I want to use the mdi-account-hard-hat icon but would prefer an outlined version of it to match the rest of the icons used throughout the app.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/22760552/146287708-da7a6224-1192-46a4-b6d3-e35a6ec42000.png)

### Upload the icon source.

[mdi-account-hard-hat-outline.zip](https://github.com/Templarian/MaterialDesign/files/7723761/mdi-account-hard-hat-outline.zip)

**Comment by Templarian** [comment]
[![account-hard-hat-outline](https://materialdesignicons.com/icon/account-hard-hat-outline)](https://materialdesignicons.com/icon/account-hard-hat-outline) [![account-hard-hat](https://materialdesignicons.com/icon/account-hard-hat)](https://materialdesignicons.com/icon/account-hard-hat)

**Comment by Templarian** [comment]
@matthewblackburn This was added the shared contributor account. Once you have 5 icons we can add a contributor account.

**Comment by matthewblackburn** [comment]
@Templarian Awesome, thanks!
