### ISSUE TITLE
auto renew off

### ISSUE THREAD

**Issue by timautin** [Templarian/MaterialDesign#6373]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Have an icon to show the auto-renewing state of users in-app subscriptions (whether the subscription is auto-renewing or not), rather than just a text.

### Give us an example of what this icon might look like.

Very similar to the sync-off icon, but based on the autorenew icon.

Thanks!

**Comment by terreng** [comment]
![image](https://user-images.githubusercontent.com/11605395/146815826-e31f16e4-37c0-4d36-b69d-738f94887c1d.png)
[autorenew-off.svg](https://github.com/terreng/samples/blob/master/autorenew-off.svg)

**Comment by goyney** [comment]
The `off` line is not our standard here and will need to be updated before it can be added.

**Comment by terreng** [comment]
Could you elaborate, @goyney? This uses the same line as the already existing and visually similar `sync-off` icon. What line should be used instead? And, should the `sync-off` icon also then be updated?

**Comment by Xenomorph99** [comment]
@terreng it has to be the exact same standard line we use throughout the library. Here's the updated icon.

![autorenew-off](https://user-images.githubusercontent.com/1837101/147597990-35478a3f-51cb-4edf-bc84-011eb1d199e5.png)

[autorenew-off.zip](https://github.com/Templarian/MaterialDesign/files/7786029/autorenew-off.zip)

**Comment by Xenomorph99** [comment]
Added to the library.

**Comment by terreng** [comment]
@Xenomorph99 Should the `sync-off` icon therefore also be updated to use the standard line?
