### ISSUE TITLE
`mdi-bell-badge-outline` is smaller than other bells

### ISSUE THREAD

**Issue by kingyue737** [Templarian/MaterialDesign#6374]
### Where are you experiencing this bug?

@mdi/js

### What is the issue you are experiencing?

`mdi-bell-badge-outline` is smaller than other bells

![1](https://user-images.githubusercontent.com/40021217/146558236-04f56c41-0111-44d4-992d-173b9cdf1354.jpg)

**Comment by terreng** [comment]
I double-checked all of the other bell icons, and this is the only one that is a different size. Here's a fixed SVG:

![image](https://user-images.githubusercontent.com/11605395/146813394-d145e37d-c6d7-4142-9f1a-f83580b8aab0.png)
[bell-badge-outline.svg](https://github.com/terreng/samples/blob/master/bell-badge-outline.svg)

**Comment by Templarian** [comment]
Updated, this will be in 6.6.xx release! Thanks @kingyue737 for filing this bug.

Thanks @terreng!
