### ISSUE TITLE
It's been 3 years... when are you all going to improve search by implementing Algolia?

### ISSUE THREAD

**Issue by tycooperaow** [Templarian/MaterialDesign#6376]
### What is your question?

I have been using this package for about a few weeks and the search of the site is slow and there are better tools out there. I have seen others mention using Algolia which is something I personally recommend. Here was the first question that arose with it 

[https://github.com/Templarian/MaterialDesign-Site/issues/48](https://github.com/Templarian/MaterialDesign-Site/issues/48)

[A more recent post](https://github.com/Templarian/MaterialDesign/issues/4365)

Please improve your site search... use them => algolia.com

**Comment by goyney** [comment]
The new site is in development. It'll be done when it's done. We're all volunteers here. Posts like this are not helpful.
