### ISSUE TITLE
Add robot-industrial-icon outlined

### ISSUE THREAD

**Issue by mayrhofer-simon** [Templarian/MaterialDesign#6377]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need this Icon to match the rest of the Navigation which are also outlined icons. Can this be implemented? The robot-industrial is already inserted.

### Give us an example of what this icon might look like.

![precisionManufacturing](https://user-images.githubusercontent.com/56080914/147068615-5a6fcd5a-3e38-4615-a8c8-9f3349cc5a94.png)

**Comment by Templarian** [comment]
[![robot-industrial-outline](https://materialdesignicons.com/icon/robot-industrial-outline)](https://materialdesignicons.com/icon/robot-industrial-outline)

Tweaked a little bit to make it a little more geometric while keeping the filled icon's general design.
