### ISSUE TITLE
Folder lock outline

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6378]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Locking a folder. 

### Give us an example of what this icon might look like.

We already have folder-lock icon, but we need outlined style too.

**Comment by bens545** [comment]
[folder-lock-outline.zip](https://github.com/Templarian/MaterialDesign/files/7776231/folder-lock-outline.zip)

**Comment by Xenomorph99** [comment]
This issue is a duplicate and relates to #6303 and #6309
