### ISSUE TITLE
An icon for small bracket "("

### ISSUE THREAD

**Issue by sumitbrt** [Templarian/MaterialDesign#638]
Thank you once again :)

**Comment by CoDEmanX** [comment]
Like opening and closing parentheses?

**Comment by sumitbrt** [comment]
Yes. Sorry that I wasn't clear. Similar to this:
https://materialdesignicons.com/icon/code-braces

**Comment by CoDEmanX** [comment]
So `()` and `[]` as one icon each? Or do you also need individual opening and closing square brackets / parens?

**Comment by sumitbrt** [comment]
Individual would be great. I hope I'm not asking too much. Thank you again.

**Comment by gytdau** [comment]
Sumitbrt:
What's the issue with the `(`, `)`, `[` and `]` text characters?
You can even add bold or italicize, whereas with the icon, you can't.

**Comment by sumitbrt** [comment]
Okay I was planning to make something like this which would follow material design aesthetics:
http://imgur.com/WdZAPKn
Ended up editing https://materialdesignicons.com/icon/looks to achieve that.
Text character "(" won't give the uniformity, which would match angular brackets one. Again, I might have been too specific in my request.

**Comment by CoDEmanX** [comment]
Is that going to be a custom logo (`><(`)? It's probably best if you make that a single icon. It's not fully material by the way, because of the spacing. MD guidelines say 2px margins.

**Comment by sumitbrt** [comment]
Yes, a logo. Will try to make it a single icon as you say :)
