### ISSUE TITLE
Bell with Cog (Notification settings icon) filled and outlined 

### ISSUE THREAD

**Issue by tmy-sr** [Templarian/MaterialDesign#6382]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Notification settings page

### Give us an example of what this icon might look like.

Cog icon
https://materialdesignicons.com/icon/cog
with Bell icon
https://materialdesignicons.com/icon/bell

filled and outlined

**Comment by Xenomorph99** [comment]
![bell-cog](https://user-images.githubusercontent.com/1837101/147597489-08d570a9-1a41-448b-a5b1-058b1ca8a126.png)
![bell-cog-outline](https://user-images.githubusercontent.com/1837101/147597488-58b76413-bb57-4879-bf02-950ae1e41d26.png)

[bell-cog.zip](https://github.com/Templarian/MaterialDesign/files/7786011/bell-cog.zip)

**Comment by Templarian** [comment]
@Xenomorph99 This overlay looks good. 👍

**Comment by goyney** [comment]
[![bell-cog](https://materialdesignicons.com/icon/bell-cog)](https://materialdesignicons.com/icon/bell-cog)[![bell-cog-outline](https://materialdesignicons.com/icon/bell-cog-outline)](https://materialdesignicons.com/icon/bell-cog-outline)
