### ISSUE TITLE
Apache License v2.0 or SIL Open Font License 1.1 ?

### ISSUE THREAD

**Issue by fu7mu4** [Templarian/MaterialDesign#6383]
### What is your question?

Pop over says SIL Open Font License 1.1 on https://materialdesignicons.com/ . But the License file on the repository says Apache License v2.0 . Which license is right ?

![image](https://user-images.githubusercontent.com/1885537/147461504-11639a2b-7e68-4967-be87-2f74a73da439.png)

**Comment by Templarian** [comment]
https://dev.materialdesignicons.com/license
