### ISSUE TITLE
firewall icon

### ISSUE THREAD

**Issue by vrillusions** [Templarian/MaterialDesign#6384]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Specifically it would be used as the icon for firewall entities in home assistant but can see it being used in network diagrams as well

### Give us an example of what this icon might look like.

![firewall](https://user-images.githubusercontent.com/53131/147529465-95d1d84f-5376-4512-957a-3d2980b1a4d1.png) ![firewall-512](https://user-images.githubusercontent.com/53131/147529469-5482c514-e7f0-4c90-8838-bb87863274d2.png)

**Comment by Templarian** [comment]
[![wall-fire](https://materialdesignicons.com/icon/wall-fire)](https://materialdesignicons.com/icon/wall-fire)
