### ISSUE TITLE
Champagne

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#6388]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Celebrations, in this case more explicitly New Years day.

please consider adding ( tbh was surprised it was there already..)

### Give us an example of what this icon might look like.

<img width="192" alt="Schermafbeelding 2021-12-30 om 10 56 24" src="https://user-images.githubusercontent.com/33354141/147741186-326f1ddf-a9c3-4192-9631-9d18d3a57609.png">

Aware we have party-popper, but that doesnt really have the correct
<img width="386" alt="Schermafbeelding 2021-12-30 om 10 56 56" src="https://user-images.githubusercontent.com/33354141/147741272-f2f62dcc-23f3-49c5-8f42-a2f1d20dd12c.png">
 vibe ;-)

A set of clinging glasses might be welcome too:

<img width="189" alt="Schermafbeelding 2021-12-30 om 10 58 56" src="https://user-images.githubusercontent.com/33354141/147741484-485624ec-3c21-44da-b5b0-a9560c8e82f7.png">

thanks for considering, and ofc: Happy New Year!

**Comment by goyney** [comment]
[![bottle-wine](https://materialdesignicons.com/icon/bottle-wine)](https://materialdesignicons.com/icon/bottle-wine)

**Comment by Mariusthvdb** [comment]
aw too bad, a plain bottle of wine doesn't have the ring of festivities at all...
thans for having a look though
