### ISSUE TITLE
text-box-edit icon should be added

### ISSUE THREAD

**Issue by PashaTurok** [Templarian/MaterialDesign#6389]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This icon is required to show, that text-box will be edited.

### Give us an example of what this icon might look like.

There are icons : text-box-check, text-box-minus, text-box-plus. I suggest to add text-box-edit with pen in the right bottom corner.

**Comment by goyney** [comment]
[![text-box-edit](https://materialdesignicons.com/icon/text-box-edit)](https://materialdesignicons.com/icon/text-box-edit)[![text-box-edit-outline](https://materialdesignicons.com/icon/text-box-edit-outline)](https://materialdesignicons.com/icon/text-box-edit-outline)

**Comment by PashaTurok** [comment]
@goyney Thank you! Thank you very much!
