### ISSUE TITLE
Book library icon, open book icon, book on shelf

### ISSUE THREAD

**Issue by Shakib210** [Templarian/MaterialDesign#6395]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I making a book library app. For the bottom tab, I didn't find any library icons there.

### Give us an example of what this icon might look like.

Multiple books are stored on a shelf or something like that.

**Comment by goyney** [comment]
There's tons. Please search.
[![library-shelves](https://materialdesignicons.com/icon/library-shelves)](https://materialdesignicons.com/icon/library-shelves)[![book-open](https://materialdesignicons.com/icon/book-open)](https://materialdesignicons.com/icon/book-open)[![book-open-blank-variant](https://materialdesignicons.com/icon/book-open-blank-variant)](https://materialdesignicons.com/icon/book-open-blank-variant)[![book-open-outline](https://materialdesignicons.com/icon/book-open-outline)](https://materialdesignicons.com/icon/book-open-outline)[![book-open-page-variant](https://materialdesignicons.com/icon/book-open-page-variant)](https://materialdesignicons.com/icon/book-open-page-variant)[![book-open-page-variant-outline](https://materialdesignicons.com/icon/book-open-page-variant-outline)](https://materialdesignicons.com/icon/book-open-page-variant-outline)[![book-open-variant](https://materialdesignicons.com/icon/book-open-variant)](https://materialdesignicons.com/icon/book-open-variant)[![bookshelf](https://materialdesignicons.com/icon/bookshelf)](https://materialdesignicons.com/icon/bookshelf)
