### ISSUE TITLE
Manage search icon

### ISSUE THREAD

**Issue by hvalette** [Templarian/MaterialDesign#6396]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

As most of Google font icons are in MDI, it would be cool if could have a manage_search icon.

### Give us an example of what this icon might look like.

![baseline_manage_search_black_24dp](https://user-images.githubusercontent.com/43471126/148101090-160317d2-37e5-4621-b327-a8510a286d4a.png) ![baseline_manage_search_white_24dp](https://user-images.githubusercontent.com/43471126/148101377-7519d85a-67ad-49f8-9148-dfd72c257f73.png)

Can be found [here](https://fonts.google.com/icons?selected=Material+Icons&icon.query=manage+search).

**Comment by goyney** [comment]
We have `text-search`, which is similiar.

[![text-search](https://materialdesignicons.com/icon/text-search)](https://materialdesignicons.com/icon/text-search)

The question is whether or not we should update ours to Google's.

**Comment by hvalette** [comment]
I found this one too but I needed exactly the other one. Anyway thank you for the answer, it's up to you if you prefer align with google icons or community ones 😁

**Comment by Templarian** [comment]
I'm not against having both. I'd rather the current `text-search` stay for consistency with all the other styles of `text-*`.

**Comment by Templarian** [comment]
No idea what to name this if we did add it. 🤷‍♂️

**Comment by goyney** [comment]
We can add this as `text-search-variant`.

**Comment by goyney** [comment]
[![text-search-variant](https://materialdesignicons.com/icon/text-search-variant)](https://materialdesignicons.com/icon/text-search-variant)
