### ISSUE TITLE
Can the font be updated with current icons ? 

### ISSUE THREAD

**Issue by Fenntasy** [Templarian/MaterialDesign#64]
I really don't know much about font creation but this is my option of choice for displaying icons and there is some icons  that aren't in the font (or the css) like delete or dots-horizontal.

**Comment by Templarian** [comment]
Bower has been updated with the latest. 683 icons.

**Comment by Templarian** [comment]
I'm going to close out this issue now and will use the optimize issue in #63 to track the progress.

I'm expecting the file size of the webfonts to drop by a fifth once the optimization stuff is done.

**Comment by Fenntasy** [comment]
Great, thanks :)

**Comment by colinsteinmann** [comment]
Hey I noticed the icon font is not up to date.

For instance the "view-stream" icon is absent from the materialdesignicons.css styles.

**Comment by Templarian** [comment]
If you view http://materialdesignicons.com/history you can see when the fonts were last built.

I've been making a lot of changes, so I was holding off on building the font package. I guess I could build a font package and release it.

**Comment by colinsteinmann** [comment]
Much appreciated. Cheers!

**Comment by Templarian** [comment]
Updated to `v0.8.82-alpha`. Lots of new icons since the last build, so wanted to double check the export with a visually before publishing.

http://materialdesignicons.com/history You can see all the icons added between this release and the last here. The next font build will be Sunday.
