### ISSUE TITLE
Split into a logo font

### ISSUE THREAD

**Issue by gytdau** [Templarian/MaterialDesign#640]
I think that this font should be split into two: icons, and logos.

There's quite a lot of logos in the font, and to me, they just don't semantically fit in with the icons.

**Comment by Templarian** [comment]
Eventually there will be tooling to make subsets of the pack with default groupings. It is a ways off in the list of priorities though for now use https://fonticons.com/ which has this font as 'MD Community'.

I'll use this issue to track it.

**Comment by darosh** [comment]
Here is list of 150+ logos missing `logo` tag. It is made with [material-icons-bundle](https://darosh.github.io/material-icons-bundle/). Perhaps you can use is for some batch tagging? 

```
android studio
angular
angularjs
apple finder
apple mobileme
apple safari
apple
appnet
atom
azure
beats
bing
biohazard
bitbucket
black mesa
blackberry
blender
bootstrap
discord
dolby
dribbble box
dropbox
drupal
edge
emby
eventbrite
facebook messenger
file excel box
file pdf box
flattr
folder google drive
font awesome
foursquare
git
github box
github face
gnome
google analytics
google assistant
google cardboard
google chrome
google drive
google earth
google glass
google keep
google maps
google pages
google photos
google physical web
google play
google plus box
google plus box
google plus
google translate
google wallet
google
hackernews
hololens
hops
houzz box
hulu
humble bundle
internet explorer
kickstarter
kodi
language c
language cpp
language csharp
language css3
language go
language html5
language javascript
language php
language python text
language python
language r
language swift
language typescript
lastfm
linkedin
mail ru
material ui
maxcdn
medium
meteor
minecraft
mixcloud
netflix
nintendo switch
nodejs
npm
odnoklassniki
office
onenote
openid
opera
owl
pandora
periscope
pinterest
playstation
plex
pokeball
qqchat
quicktime
rdio
react
sass
skype
slack
soundcloud
spotify
square inc cash
square inc
stackexchange
stackoverflow
steam
tor
twitter box
twitter circle
uber
umbraco
unity
untappd
venmo
vimeo
vine
visualstudio
vk box
vk circle
vk
vlc
vuejs
webhook
webpack
wechat
wii
wiiu
wikipedia
wordpress
wunderlist
xamarin outline
xamarin
xaml
xbox
xda
xing circle
xing
xing box
xml
xmpp
yammer
yelp
youtube creator studio
```

**Comment by Templarian** [comment]
@darosh Thanks, I'm giving the contributor team access to tagging shortly (they have Alias now and have added hundreds of new aliases since then). We'll get these tagged, then I can use this in the build tools to give an option. Full package generation takes ~35 seconds, so need to put it behind the CDN before releasing the ability.

**Comment by JamesCoyle** [comment]
We are now recommending that people use [simple icons](https://simpleicons.org/) for brand icons.
