### ISSUE TITLE
human-male-board-plus

### ISSUE THREAD

**Issue by Faciliclic** [Templarian/MaterialDesign#6400]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I use human-male-board but I need human-male-board-plus please.

Thank you !

### Give us an example of what this icon might look like.

human-male-board => human-male-board-plus 
(like  archive-plus-outline)

**Comment by MrGrigri** [comment]
I don't know how I feel about the cutout.

![human-male-board-plus](https://user-images.githubusercontent.com/4528551/150864451-dfca19a0-3611-46af-bcee-37056803f622.svg)

---
Path: `M23,18v2H20v3H18V20H15V18h3V15h2v3ZM20,4v9.09a5.58,5.58,0,0,1,2,.72V4a2,2,0,0,0-2-2H9.46A4,4,0,0,1,10,4ZM6,6A2,2,0,1,0,4,4,2,2,0,0,0,6,6Zm5,11h2.35a5.49,5.49,0,0,1,1.19-2H11ZM15,7H3.5a2,2,0,0,0-2,2v5H3v8H5V16H7v6H9V9h6Z`

**Comment by Templarian** [comment]
It seems too specific like one would be better using `account-plus`.

**Comment by Faciliclic** [comment]
@MrGrigri , Thank you ! It's very good ! 
@Templarian It seems consistent with other icon packs, eg <code>archive-outline</code> and <code>archive-plus-outline</code>. <code>account-plus</code> symbolizes another action. If you agree...

Could this icon be added ?

**Comment by goyney** [comment]
I agree with @Templarian. The first thing I asked myself is... what are you adding? Are you adding a person? A lecturer? A teacher? In all those cases, you're adding a person, so `account-plus` is the right icon.

Going to close this one out as too niche. Thanks for the suggestion.
