### ISSUE TITLE
PEGI icons

### ISSUE THREAD

**Issue by nielsarts** [Templarian/MaterialDesign#6401]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

need a icon that makes it clear that something is 18+. I found out there are no PEGI icons or similar 

### Give us an example of what this icon might look like.

https://images.app.goo.gl/a4Ty4a2ny9ZdqB567

**Comment by goyney** [comment]
PEGI is specific to European countries and we are as language/country agnostic as possible. We include a full alpha and numeric set of icons that you should be able to use to create the mash-up you need. These are far too niche for this library.

Thanks for your suggestion.
