### ISSUE TITLE
garage(-variant)(-arrow-up|down)

### ISSUE THREAD

**Issue by LoloTheJeeper** [Templarian/MaterialDesign#6402]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Hi !
I have been creating a Garage door controller with a ESP32 and integrated it with Home Assistant.
Unfortunately, I did not find all "Garage" icon I needed in the Material Design proposed icons.
I created new icons based on those created by Michael Irigoyen @mririgo (I don't want to steal his job !)
The icons I needed was "Garage Door Opening" "Garage Door Fully Opened" "Garage Door Fully Closed" (already available) "Garage Door Closing" and an other design for "Garage Door In Problem".
Thank you for your great job !
I would be glad to help :)

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/34494124/148608959-adbd3069-0338-4894-a4a2-76e7bfc87133.png)
![image](https://user-images.githubusercontent.com/34494124/148609044-93b6e200-1aff-41a5-8e00-6610c67f8f58.png)
![image](https://user-images.githubusercontent.com/34494124/148609147-436f9fe8-aba8-423b-a2ff-cc4fccf5a443.png)
![image](https://user-images.githubusercontent.com/34494124/148609201-ea4db55f-a81e-4f1f-8085-f64fba614f84.png)
![image](https://user-images.githubusercontent.com/34494124/148609291-409833f6-6340-410a-b479-d963849a3e21.png)

### Upload the icon source.

[garage-door-alternate.zip](https://github.com/Templarian/MaterialDesign/files/7831421/garage-door-alternate.zip)

**Comment by goyney** [comment]
`garage-alert` already exists, as well as `garage-open`.

The other versions (which I'm assuming an arrow for direction?) are obscure and do not follow any pattern we have in the library. If we want to add directional icons, using our arrow modifiers would be the appropriate solution.

**Comment by LoloTheJeeper** [comment]
Thank you ! 
I don't know exactly what "using our arrow modifiers" means.
Do I need to do something and modify the icons I proposed ?

**Comment by Circeus** [comment]
Yes, he means your -arrow-up/down should use the same modifiers as, e.g. database-arrow-up/down

**Comment by LoloTheJeeper** [comment]
Ok. Thank you. I will close my request and use an integration to be able to use my icons. 
Thank you for your great work. I use a lot of mdi icons elsewhere in Home Assistant. They are great !

**Comment by felipecrs** [comment]
@mririgoyen, using the same arrow modifiers like `database-up`/`down` would be fine.

Nowadays this is what we have in Home Assistant:

![chrome_5zGNiKZ0Zz](https://github.com/user-attachments/assets/f1b5a9a1-4440-4d8a-99c9-df101e5f7d9f)


New icons for opening/closing (arrow up and arrow down for now), would make it a big improvement.

Do you want me to open a new request for it?
