### ISSUE TITLE
Vue useage

### ISSUE THREAD

**Issue by JokerMartini** [Templarian/MaterialDesign#6404]
### What is your question?

I want to use the MaterialDesignIcons with my vue project. What is the proper way of using these icons with my project? I tried the following but got errors....

`yarn add @mdi/font`

then in my vue file
```
<template>
...
<mdiLock /> 
...
</template>
<script>
import { mdiLock } from '@mdi/font';

export default {
  components: {
    mdiLock,
  },
}
</script>
```

However i get the error `This dependency was not found: `

**Comment by Templarian** [comment]
`@mdi/font` is the webfont package. Not for use within JS.

https://dev.materialdesignicons.com/getting-started/vuejs Has the Vue documentation and examples.
