### ISSUE TITLE
Raspberry Pi Logo

### ISSUE THREAD

**Issue by tdvantine** [Templarian/MaterialDesign#6406]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I am requesting that the Raspberry Pi logo be added. This was brought up in past issues (#398), but nothing surfaced from it. I also see that MDI has chosen to do a case by case base for brand icons as stated on the website: "We may consider technology-related logo icons based around development (e.g. Webpack) for well-known tools, but these will be done on a case-by-case basis." 
Hoping that the fact Home Assistant uses MDI icons as their sole icon library and that said platform is widely ran on a Raspberry Pi, that MDI may consider adding it to the library that already contains the Home Assistant logo.
If this icon were to be made, it could be designed in such a way that it can be used as an icon for the actual raspberry fruit as well.

### Give us an example of what this icon might look like.

[The Raspberry Pi Logo/Brand Guidelines](https://static.raspberrypi.org/files/Raspberry_Pi_Visual_Guidelines_2020.pdf)

**Comment by goyney** [comment]
We're not currently adding ANY new brand icons at the moment as we work on a strategy for a brand-icon specific icon pack. For now...

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
