### ISSUE TITLE
Agda

### ISSUE THREAD

**Issue by Meowcolm024** [Templarian/MaterialDesign#6408]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Icon for the Agda programming language

### Give us an example of what this icon might look like.

![agda](https://agda.readthedocs.io/en/v2.6.2.1/_images/agda.png)

**Comment by Templarian** [comment]
@Meowcolm024 Have you seen any versions of the logo that is readable at 24x24 size?

**Comment by goyney** [comment]
This seems like a very niche language. I know under current policies we allow tech related brand icons, but considering its niche-ness and the unavailability of a logo that works at native resolution, I move to close this.
