### ISSUE TITLE
networkCashBox

### ISSUE THREAD

**Issue by emeraldmor** [Templarian/MaterialDesign#6409]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Program Cash box 

### Share a preview of your contribution.

Program Cash box 

### Upload the icon source.

[network_cashbox.zip](https://github.com/Templarian/MaterialDesign/files/7837934/network_cashbox.zip)

**Comment by goyney** [comment]
Preview of the contribution:
![image](https://user-images.githubusercontent.com/1015040/159184150-ef14a02f-d212-4ba2-82ee-53397c88c22d.png)

I'm not sure what we'd call this. My gut reaction was `network-terminal`, but we already have that. Maybe `network-pos` or `network-point-of-sale`?

**Comment by goyney** [comment]
[![network-pos](https://materialdesignicons.com/icon/network-pos)](https://materialdesignicons.com/icon/network-pos)
