### ISSUE TITLE
Time of day

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#6414]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Icon to represent current or different time(s) of day (e.g., morning, noon, afternoon, night, etc.). Not sure if there is a common use case, I would probably use it within my home automation system for time-of-day-based rules.

### Share a preview of your contribution.

![grafik](https://user-images.githubusercontent.com/7279415/148965731-c7d05811-8242-4cd6-86a2-b3648fff6465.png)

Actually I prefer the second one, since it does not interfere with the upper right sunray, even though this means that the sun icon deviates from the default by a rotation of 15°.
![grafik](https://user-images.githubusercontent.com/7279415/148965942-d78a985e-cbf3-4c59-b57f-2f588b17cd34.png)

### Upload the icon source.

[time-of-day.zip](https://github.com/Templarian/MaterialDesign/files/7847532/time-of-day.zip)

**Comment by goyney** [comment]
[![sun-clock](https://materialdesignicons.com/icon/sun-clock)](https://materialdesignicons.com/icon/sun-clock)[![sun-clock-outline](https://materialdesignicons.com/icon/sun-clock-outline)](https://materialdesignicons.com/icon/sun-clock-outline)

**Comment by boehan** [comment]
Thanks, just a minor fix for the outline version (cut out of the sun ray above the clock)
![grafik](https://user-images.githubusercontent.com/7279415/159860116-2e49cc8c-75f2-4bdb-9c6c-b3310bc9a419.png)
[sun-clock-outline.zip](https://github.com/Templarian/MaterialDesign/files/8339136/sun-clock-outline.zip)

**Comment by goyney** [comment]
Thanks, actually the outline version is correct. I will fix the solid one.

**Comment by goyney** [comment]
Updated!
