### ISSUE TITLE
Add "RAW" icon from material.io

### ISSUE THREAD

**Issue by Frontesque** [Templarian/MaterialDesign#6416]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

RAW images // raw camera files

### Give us an example of what this icon might look like.

It already exists here:
https://fonts.google.com/icons?selected=Material%20Icons%3Araw_on%3A

**Comment by Templarian** [comment]
[![raw](https://materialdesignicons.com/icon/raw)](https://materialdesignicons.com/icon/raw) [![raw-off](https://materialdesignicons.com/icon/raw-off)](https://materialdesignicons.com/icon/raw-off)
