### ISSUE TITLE
file-cad-cog

### ISSUE THREAD

**Issue by engleder** [Templarian/MaterialDesign#6418]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Process a cad file.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/17008676/149030351-bb6fa0a5-f28c-424f-a9ea-0ee60ab1b6f3.png)

### Upload the icon source.

[chart-tree-cog.zip](https://github.com/Templarian/MaterialDesign/files/7850204/chart-tree-cog.zip)

**Comment by Templarian** [comment]
This might be too busy. Adding double modifiers to the file icon isn't something we've done. `file-cog` might be all that's necessary here.

**Comment by goyney** [comment]
Agreed. We don't do double modifiers except in extreme circumstances. Thanks for the suggestion.
