### ISSUE TITLE
Chromecast Icon

### ISSUE THREAD

**Issue by maxjoehnk** [Templarian/MaterialDesign#642]
A Icon for the Chromecast would be really nice

**Comment by CoDEmanX** [comment]
You mean these?
[![cast](https://materialdesignicons.com/icon/cast)](https://materialdesignicons.com/icon/cast)
[![cast-connected](https://materialdesignicons.com/icon/cast-connected)](https://materialdesignicons.com/icon/cast-connected)

**Comment by e-freak** [comment]
No, i mean an icon for the actual device. I know that these icons exist but an icon for the actual device is missing in my opinion.
I have something like this in mind:
![image](https://cloud.githubusercontent.com/assets/1153569/9550203/4340172c-4daa-11e5-924f-9d36d645abb3.png)

**Comment by goyney** [comment]
Considering Chromecast's aren't dongles anymore, I feel like this isn't needed/wouldn't be identifiable anymore.

**Comment by JamesCoyle** [comment]
Lets close this one out for now as there are alternatives that could be used.
