### ISSUE TITLE
sun-snowflake-variant

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#6420]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

A variant to the Google [sun-snowflake](https://materialdesignicons.com/icon/sun-snowflake) icon (which uses completely individual snowflake and sun icons). 
Could be used for "season change" or "heating/cooling" switch for thermostats.

### Share a preview of your contribution.

![grafik](https://user-images.githubusercontent.com/7279415/149197943-0307acca-4432-4098-9c3f-a3f0c549ac57.png)

### Upload the icon source.

[sun-snowflake-variant.zip](https://github.com/Templarian/MaterialDesign/files/7856740/sun-snowflake-variant.zip)

**Comment by goyney** [comment]
The reason theirs uses a thicker sun it to make it visually understandable at native resolution. This just looks like a snowflake with the off modifier unless you really pay attention to it. I do not feel this variant is needed.

**Comment by boehan** [comment]
> The reason theirs uses a thicker sun it to make it visually understandable at native resolution. This just looks like a snowflake with the off modifier unless you really pay attention to it.

That's a reasonable argument. Just another try with the non-outline version of the sun.
![image](https://user-images.githubusercontent.com/7279415/149219226-8b34e56c-2a07-40b0-927a-60205896ad93.png)
However, I can also understand if this is considered as not needed.

**Comment by goyney** [comment]
That actually isn't too bad with the filled sun half. I think we could add this.

**Comment by goyney** [comment]
[![sun-snowflake-variant](https://materialdesignicons.com/icon/sun-snowflake-variant)](https://materialdesignicons.com/icon/sun-snowflake-variant)
