### ISSUE TITLE
food-pear

### ISSUE THREAD

**Issue by True-cc** [Templarian/MaterialDesign#6426]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I have created a pear. I'm not super happy about the stem, but this is my first icon.

> What led you to create this icon?

A dream (srsly). I had a perfect shape for a pear in my dream, except the stem of course.

> Tell us how you would use it.

Same way as `food-apple`?

### Share a preview of your contribution.

![pear](https://user-images.githubusercontent.com/38010540/149635801-ec6d2a2c-9182-405f-90d5-7b65b78ccb6d.png)

### Upload the icon source.

[fruit-pear.svg.tar.gz](https://github.com/Templarian/MaterialDesign/files/7875778/fruit-pear.svg.tar.gz)

**Comment by Templarian** [comment]
[![fruit-pear](https://materialdesignicons.com/icon/fruit-pear)](https://materialdesignicons.com/icon/fruit-pear)
