### ISSUE TITLE
Helium HNT cryptocoin icon

### ISSUE THREAD

**Issue by vanarebane** [Templarian/MaterialDesign#6428]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [x] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I wanted to use Helium HNT cryptocoin icon on a platform that uses Material Design icons specifically

Source of the icon: https://drive.google.com/drive/folders/1Kagi1PDS-ULoTRlTXlrkxsI8LQGjc1cj

### Share a preview of your contribution.

![currency-hnt](https://user-images.githubusercontent.com/4301343/149733862-580c286d-6d32-4675-b1c0-036a7cd6ee83.png)

### Upload the icon source.

[currency-hnt.zip](https://github.com/Templarian/MaterialDesign/files/7880234/currency-hnt.zip)

**Comment by goyney** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: http://dev.materialdesignicons.com/roadmap/brand-icons
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues

**Comment by vanarebane** [comment]
What about currency symbols?
Bitcoin is in Material
