### ISSUE TITLE
Cart for download of multiple Icons at once

### ISSUE THREAD

**Issue by e-freak** [Templarian/MaterialDesign#643]
I would really like seeing some kind of cart, so you can download multiple icons at once and maybe even save the cart for quick access, so everytime you need a specific item set you can just go into your saved ones.
Maybe even some kind of "global ranking" with popular carts or sets?

**Comment by CoDEmanX** [comment]
Did you see this? https://github.com/Templarian/MaterialDesign/issues/640#issuecomment-135657646

**Comment by Templarian** [comment]
This is the future plans for the site with a lot more development needed. I'm going to close out this issue as there are similar issues tracking the progress.
