### ISSUE TITLE
Please update Fedora icon to new version

### ISSUE THREAD

**Issue by mattdm** [Templarian/MaterialDesign#6430]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

This is a continuation of #3776.  Because at the time Fedora did not have a logo which works in a single-color treatment, the icon included in Material Design Icons is an interpretation. We'd like that fixed — and we have a new logo which works in a single-color treatment. (In fact, the  Material Design Icons need was one of the big reasons we went through the whole process of creating a new logo.)

[fedora_fa.zip](https://github.com/Templarian/MaterialDesign/files/7908635/fedora_fa.zip)
I've attached the official SVG below (in a zipfile, as github won't let me attach the SVG directly).

We also have official permission for you to include the logo, via the following text:

----

The Fedora Council grants permission for a version of the official Fedora logo to be included in your collection of icons, unmodified from the logo image we are providing here except in size and/or file format, provided you include this text, the legal notice below, and a link to https://docs.fedoraproject.org/en-US/project/brand/ in any relevant accompanying documentation and websites. Please do not create modified versions of the logo, even to match a style or theme.

ACKNOWLEDGMENT FOR LOGO USE:

The "Fedora" logo provided as part of this collection is a trademark of Red Hat, Inc. and is provided solely for use to accurately identify Fedora or its products. To use this logo, you must agree to only use the logo in compliance with the Fedora Trademark Guidelines: https://fedoraproject.org/wiki/Legal:Trademark_guidelines, and never to use any logo or trademark of Red Hat in a manner that suggests that Red Hat or Fedora owns, sponsors, or endorses your products or services, or that you own any rights in the logo or trademark.
----

**Comment by Templarian** [comment]
@mattdm Congrats getting through approval. We'll have it updated in the 6.7.x release. 😃

**Comment by mattdm** [comment]
Thanks!

On Thu, Jan 20, 2022 at 01:55:54PM -0800, Austin Andrews wrote:
> @mattdm Congrats getting through approval. We'll have it updated in the 6.7.x release. 😃 
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/Templarian/MaterialDesign/issues/6430#issuecomment-1017961305
> You are receiving this because you were mentioned.
> 
> Message ID: ***@***.***>

-- 
Matthew Miller            ***@***.***             <http://mattdm.org/>
Fedora Project Leader  ***@***.***  <http://fedoraproject.org/>

**Comment by Templarian** [comment]
[![fedora](https://materialdesignicons.com/icon/fedora)](https://materialdesignicons.com/icon/fedora)
