### ISSUE TITLE
Volume icons with numeric levels

### ISSUE THREAD

**Issue by dougiteixeira** [Templarian/MaterialDesign#6432]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Add volume icons with numeric levels, similar to battery icons.

The idea would be the volume level numeric, being more noticeable the difference within the same level (low, medium and high).

### Give us an example of what this icon might look like.

Something like:
`volume-100`
`volume-90`
`volume-80`
`volume-70`
`volume-60`
`volume-50`
`volume-40`
`volume-30`
`volume-20`
`volume-10`

Currently it has the volume level by intensity, the idea would be the volume level numeric, being more noticeable the difference within the same level (low, medium and high):

`volume-high`
![volume-high](https://user-images.githubusercontent.com/31328123/150674122-50bc74ec-8602-4e7c-8774-91d587c30de8.png)
`volume-low`
![volume-medium](https://user-images.githubusercontent.com/31328123/150674137-906d39cd-ae44-46a8-91d0-e67f85426923.png)
`volume-medium`
![volume-low](https://user-images.githubusercontent.com/31328123/150674144-4271ec42-a4e7-45b4-946a-269ba1ea057a.png)

It is possible?

Sorry, I don't have the ability to create the icons...

**Comment by dougiteixeira** [comment]
@frenck, do you think i can implement this?

Thanks!

**Comment by Templarian** [comment]
The only way to really do this is with lines to the right to indicate rising volume.

![volume-10](https://user-images.githubusercontent.com/338885/150917288-25829b18-3dad-44fb-adae-c315eab0b7b2.svg) ![volume-50](https://user-images.githubusercontent.com/338885/150917293-7989b28b-e35e-4270-bc6f-b1cbd1c136ac.svg) ![volume-100](https://user-images.githubusercontent.com/338885/150917300-47f7594f-055a-4f2f-8163-637e8d74d3cf.svg)

Not really a fan of is this idea.

**Comment by Templarian** [comment]
Thinking through this more and not sure there is a design that works within the icon guidelines that would be readable.

If anyone thinks of something feel free to re-open.
