### ISSUE TITLE
Thermal indices

### ISSUE THREAD

**Issue by rautesamtr** [Templarian/MaterialDesign#6434]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Hi I add this as single issue since its in regard of similar icons. In this case it's like the title says icons for thermal indices. Those icons are used for a [custom integration](https://github.com/dolezsa/thermal_comfort) that exposes those indices as sensors. Having distinguishable icon makes it easier to read them when shown in a combined box. Especially without text.

Tell me if it would be better to separate this issue in separate issues per icon.

Here are the icons in action:
![image](https://user-images.githubusercontent.com/1131371/151231784-0cf35cbd-f3d6-4faf-8b34-9f5eb5654c30.png)

### Share a preview of your contribution.

# Heat Index
An index that combines air temperature and relative humidity, to posit a human-perceived equivalent temperature.
I used the thermometer with a fire element attached. While it doesn't make sense in that fire is part of the index, the idea is to represent the `Heat` in Heat Index.
![image](https://user-images.githubusercontent.com/1131371/151230689-908a4bd5-c278-42de-8ecc-8ae32f7451b0.png)

# Dew Point
The dew point is the temperature at which liquid first forms from a vapor.
![image](https://user-images.githubusercontent.com/1131371/151230803-96eba46f-6498-4cb0-9026-d1d7882cacb6.png)
![image](https://user-images.githubusercontent.com/1131371/151230850-41d24361-ff8d-4a02-ad0a-fe729eb1b161.png)

# Frost Point
Frost point, temperature, below 0° C (32° F), at which moisture in the air will condense as a layer of frost on any exposed surface.
![image](https://user-images.githubusercontent.com/1131371/151231059-b38f26bd-f3fa-4766-b1a0-63b222d6fad6.png)

# Simmer(Summer) Index
An index that combines air temperature and relative humidity. In contrast to the Heat Index it describes the human-perceived equivalent temperature at night and describes a factor of discomfort.
![image](https://user-images.githubusercontent.com/1131371/151231603-fc42ea08-6fd4-4c2c-b159-c67e1eb937e0.png)

### Upload the icon source.

[thermal-indices.zip](https://github.com/Templarian/MaterialDesign/files/7944613/thermal-indices.zip)

**Comment by rautesamtr** [comment]
@goyney May i ask what is confusing about this submission?

**Comment by goyney** [comment]
Not confused, more like unsure. I do not like how portions of the icons are being cut out by the thermometer. I also question whether the thermometers are actually needed, which would mean we have all those icons already.

**Comment by rautesamtr** [comment]
Thanks, I appreciate the honest feedback. I understand that your team probably doesn't have much time with the amount of issues you have to work trough, but it really makes a difference for the person trying to contribute.

The work for the icons is already done for the custom icon pack so i thought i try to upstream them. But i fully understand that if they go against your projects goal it's better to just keep them in the icon pack. Thanks for your time.

**Comment by Templarian** [comment]
Looking through this and do agree, but does make me think we could have more generic `dew-point` icons. Even if it's like...

- 💧+ `°` = `water-degrees`
- Thermometer + 💧 = `thermometer-water`

**Comment by goyney** [comment]
Added a `water` variant of `thermometer`. Aliased with `dew-point`.
[![thermometer-water](https://materialdesignicons.com/icon/thermometer-water)](https://materialdesignicons.com/icon/thermometer-water)

Added a `thermometer` variant of `snowflake` (to match `sun-thermometer`). Aliased with `frost-point`.
[![snowflake-thermometer](https://materialdesignicons.com/icon/snowflake-thermometer)](https://materialdesignicons.com/icon/snowflake-thermometer)

Aliased `sun-thermometer` with `heat-index`.

All the others seem very niche and could be solved by other already existing icons.

**Comment by boehan** [comment]
Just stumbled upon this... the upper arm of the snowflake in `snowflake-thermometer` seems to have gotten malformed somehow.

Furthermore, I'm not sure if it wouldn't be better in terms of consistency to also have a big water drop on the left and a small thermometer on the right in the `thermometer-water` icon. Although, it could then be misinterpreted as water temperature... just seems a little inconsistent when both items are viewed side-by-side...

**Comment by goyney** [comment]
Thanks for catching the malformed snowflake, that's been fixed.

**Comment by goyney** [comment]
I've added `water-thermometer` as well. Can't hurt to have both, depending on where you want the emphasis.

[![water-thermometer](https://materialdesignicons.com/icon/water-thermometer)](https://materialdesignicons.com/icon/water-thermometer)

**Comment by maxistviews** [comment]
Unsure if I should be making a new request, but I figured I'd try here with an issue already opened before. 

I am looking for a snowflake and heat icon for my thermostat, but I wish there was also a way to categorize it as idle, while maintaining the mode that the thermostat is on.

So I was hoping to suggest an icon that is similar to this:

[https://materialdesignicons.com/icon/snowflake-check](https://materialdesignicons.com/icon/snowflake-check)

but has a moon/sleep icon instead of the checkmark:

https://materialdesignicons.com/icon/power-sleep

Similarly, the radiator and fire icons would also be updated.

If I should instead make a new issue, please let me know.
