### ISSUE TITLE
shopping-search-outline

### ISSUE THREAD

**Issue by kgregory** [Templarian/MaterialDesign#6435]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Outlined variant of the existing `shopping-search` icon

### Give us an example of what this icon might look like.

I've already built one and felt it would be worth including in this collection (since it's based on two of your icons):

![image](https://user-images.githubusercontent.com/3155127/151233015-7889c296-100d-4fba-adad-59ad6b3e47a8.png)

The code, including the SVG path, is available in [this codesandbox](https://codesandbox.io/s/elastic-kate-9ogi9?file=/src/App.js)

**Comment by kgregory** [comment]
I wasn't sure if the example I submitted was sufficient, so here is the icon as an svg file:

![shopping-search-outlined-128](https://user-images.githubusercontent.com/3155127/151840717-bb7ee0dc-2fb9-4630-b440-2c894300391b.svg)

@Templarian Is there anything I could do to help move this along?

**Comment by goyney** [comment]
[![shopping-search-outline](https://materialdesignicons.com/icon/shopping-search-outline)](https://materialdesignicons.com/icon/shopping-search-outline)
