### ISSUE TITLE
virtual meeting / conference - desktop

### ISSUE THREAD

**Issue by johnbrissettejr** [Templarian/MaterialDesign#6436]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Hello. This is my first contribution so please bear with me.

This is for virtual meetings (zoom, webex, teams, etc)

### Share a preview of your contribution.

![virtual-meeting-desktop](https://user-images.githubusercontent.com/98535762/151378762-ae3fccdd-dffe-4a77-b32b-fe4e6dd5b87e.png)

![virtual-meeting-desktop-alt](https://user-images.githubusercontent.com/98535762/151381040-caa29a46-6f21-4bb3-b441-a5a03108e281.png)

![virtual-meeting-laptop](https://user-images.githubusercontent.com/98535762/151381059-d733bc1a-fec2-4929-b73e-ff15eedd407f.png)

### Upload the icon source.

[virtual-meetings.zip](https://github.com/Templarian/MaterialDesign/files/7951257/virtual-meetings.zip)

**Comment by Templarian** [comment]
- `laptop-???` - Not sure we want to use account here?
- `monitor-???` - ^ Same

We should probably get rid of that `desktop-mac` and `desktop-mac-dashboard` icon in 7.0 those should have been removed when we got rid of all the legacy phone icons.

**Comment by goyney** [comment]
Added #6510 to deal with the removal of `desktop-mac` and `desktop-mac-dashboard`.

**Comment by goyney** [comment]
[![monitor-account](https://materialdesignicons.com/icon/monitor-account)](https://materialdesignicons.com/icon/monitor-account)[![laptop-account](https://materialdesignicons.com/icon/laptop-account)](https://materialdesignicons.com/icon/laptop-account)

Added and aliased.
