### ISSUE TITLE
ear icon for hearing loop

### ISSUE THREAD

**Issue by WeanaSchnitzl** [Templarian/MaterialDesign#6443]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

for an online appointment reservation system, to lead people with special needs to desk, where assistive technology is installed.

### Give us an example of what this icon might look like.

the icon should exactly look like this: https://www.hearinglink.org/living/loops-equipment/hearing-loops/what-is-a-hearing-loop/
international standard.
referring to issue #2069

**Comment by Templarian** [comment]
@WeanaSchnitzl Do we want to include the `T` in the bottom right corner?

**Comment by WeanaSchnitzl** [comment]
yes, please! and don't forget the "strike through" line from the bottom-left to the top-right corner.
the line in the ear-hearing-off symbol is the wrong side.
THX !!!!

**Comment by goyney** [comment]
Is this what you're looking for?

![image](https://user-images.githubusercontent.com/1015040/159179938-ed6022b3-0da3-4b95-8a46-76f2f958172a.png)
[ear-hearing-loop.svg.zip](https://github.com/Templarian/MaterialDesign/files/8312048/ear-hearing-loop.svg.zip)

**Comment by goyney** [comment]
Snapped this at a drive-thru today. It doesn't include the "T".

![Screen Shot 2022-03-22 at 10 44 39 PM](https://user-images.githubusercontent.com/1015040/159619790-012bb604-7624-42f4-ae5d-9f06f50f6934.png)

**Comment by WeanaSchnitzl** [comment]
yes .. above sample ist exactly what i'm looking for. great ... thank you!!!

to the pic u took: i think it's just an interpretation of the standard specification.
Like the wheel-chair symbols .. there an ISO standard spec  ... and many different interpretations.

For official use on gov pages ISO standard matching symbols are essential.

**Comment by goyney** [comment]
[![ear-hearing-loop](https://materialdesignicons.com/icon/ear-hearing-loop)](https://materialdesignicons.com/icon/ear-hearing-loop)
