### ISSUE TITLE
calendar-week-end including outline variant

### ISSUE THREAD

**Issue by schacherlj** [Templarian/MaterialDesign#6444]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

show weekends in calendar for cultures, where week starts with monday, drafts already in #4197

### Give us an example of what this icon might look like.

like calendar-week-begin with vertical line on right side

**Comment by Templarian** [comment]
- `calendar-week-end`
- `calendar-week-end-outline`
- `calendar-week-begin-outline` Guess we should add this.

**Comment by goyney** [comment]
[![calendar-week-end](https://materialdesignicons.com/icon/calendar-week-end)](https://materialdesignicons.com/icon/calendar-week-end)[![calendar-week-end-outline](https://materialdesignicons.com/icon/calendar-week-end-outline)](https://materialdesignicons.com/icon/calendar-week-end-outline)
[![calendar-week-outline](https://materialdesignicons.com/icon/calendar-week-outline)](https://materialdesignicons.com/icon/calendar-week-outline)[![calendar-week-begin-outline](https://materialdesignicons.com/icon/calendar-week-begin-outline)](https://materialdesignicons.com/icon/calendar-week-begin-outline)
