### ISSUE TITLE
Icon change request/question for "WheelchairAccessibility"

### ISSUE THREAD

**Issue by WeanaSchnitzl** [Templarian/MaterialDesign#6445]
### What is your question?

the icon design of WheelchairAccessibility by Doug C. Hardester [@r3volution11](http://twitter.com/r3volution11)
was rejected by ISO.

for international use the ISO version of ISA would be better: https://en.wikipedia.org/wiki/International_Symbol_of_Access

Now my question: should i report a bug or place a new icon request?
There is no option for an icon change request.

I don't know, but if you are ok with both versions of this icon you can keep both. IMHO the ISO symbol should be marked/tagged as ISO symbol.

**Comment by Templarian** [comment]
We have `human-wheelchair` that uses the ISO version, so we could add this one as just `wheelchair`. A lot of people prefer the `wheelchair-accessibility` icon so that would have to stay.

**Comment by Templarian** [comment]
We can use this issue to handle the request also.

**Comment by WeanaSchnitzl** [comment]
human-wheelchair has a very different meaning, maybe it would nearly satisfy this ISO symbol: https://www.iso.org/obp/ui#iso:grs:7001:PI_PF_031

for websites with government purposes we have to use ISO symbols, because those are used all over the world.

**Comment by Templarian** [comment]
@WeanaSchnitzl Sorry for the confusion I meant to convey we'll be adding the ISO icon as `wheelchair`.

**Comment by WeanaSchnitzl** [comment]
cool ... great news ! thanks so much !!!

**Comment by goyney** [comment]
[![wheelchair](https://materialdesignicons.com/icon/wheelchair)](https://materialdesignicons.com/icon/wheelchair)
