### ISSUE TITLE
plus-lock / plus-lock-open

### ISSUE THREAD

**Issue by percula** [Templarian/MaterialDesign#6448]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I created a plus icon with a lock modifier. I'm using it to indicate that a certain feature is only available to pro users. In my case, the ability to add a custom plant in my garden planning app is only available for pro users.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/16809252/152560088-def72b55-6824-4d5c-b184-b09bf6c44fde.png)

### Upload the icon source.

[plus-lock.zip](https://github.com/Templarian/MaterialDesign/files/8004381/plus-lock.zip)

Edit: I noticed the icon was a bit off the gridlines. I re-uploaded a fixed version.

**Comment by percula** [comment]
Here is the icon in use in my app:

![image](https://user-images.githubusercontent.com/16809252/152560625-938d8a69-3d86-4635-96e3-97c48ffdac6c.png)

**Comment by Templarian** [comment]
@percula It works, but the lock would need to be in the bottom right to stay within the overlay guidelines.

**Comment by percula** [comment]
No problem, here's some updated versions:
![image](https://user-images.githubusercontent.com/16809252/152656145-a2c0322d-3ef2-4311-9436-122169b359ef.png)

I also added the lock-open version like the updated title suggests. Not sure why someone would need that icon, but might as well:
![image](https://user-images.githubusercontent.com/16809252/152656174-11cc2eb1-3f59-49fc-9a63-5ba3dea6d177.png)

Updated SVGs:
[plus-lock.zip](https://github.com/Templarian/MaterialDesign/files/8008766/plus-lock.zip)

**Comment by goyney** [comment]
[![plus-lock](https://materialdesignicons.com/icon/plus-lock)](https://materialdesignicons.com/icon/plus-lock)[![plus-lock-open](https://materialdesignicons.com/icon/plus-lock-open)](https://materialdesignicons.com/icon/plus-lock-open)
