### ISSUE TITLE
broken clouds

### ISSUE THREAD

**Issue by willsvc** [Templarian/MaterialDesign#6451]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

weather icon

### Give us an example of what this icon might look like.

broken cloud icon is an icon with a dark cloud in the background and light cloud in the foreground. Light cloud is shifted to the left.

**Comment by goyney** [comment]
The lack of horizontal space makes this different. Thoughts on this?

![image](https://user-images.githubusercontent.com/1015040/159178374-704185aa-3a9e-4b7a-adbf-ab0bcb65d264.png)
[clouds.svg.zip](https://github.com/Templarian/MaterialDesign/files/8311972/clouds.svg.zip)

**Comment by goyney** [comment]
[![clouds](https://materialdesignicons.com/icon/clouds)](https://materialdesignicons.com/icon/clouds)
