### ISSUE TITLE
thermometer-check and snowflake-check

### ISSUE THREAD

**Issue by agittins** [Templarian/MaterialDesign#6452]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'd like to request two new icons:

mdi-snowflake-check
mdi-thermometer-check

I'm replacing the controller in my fridge/freezer. I'd like to use a collection of single glyphs to indicate the state of the fridge. Currently I am using:

mdi-snowflake for actively cooling,
mdi-snowflake-melt for defrost cycle
mdi-snowflake-alert for when things are not good

I am looking for a glyph to indicate that the fridge is idle (ie, not actively cooling or heating) and everything's OK. The other icons I've considered are either not very fridgey (mdi-hand-okay, mdi-pause) or not very intuitive (mdi-thermometer for instance could be taken as an idle state given the lack of up/down chevrons or the low/high variants, but the absence of something is not obvious to an untrained observer).

I think a -check variant for mdi-thermometer and mdi-snowflake would be useful for this situation and possibly others. It also seems consistent with the way other icons have been treated in the past with many featuring "checked" variants, and will complement the -alert and other variants that already exist.

Some mockups attached for reference, I couldn't work out how to easily convert them back down to a single path (plus I'm no designer!) so just attaching png for what I had in mind - not emotionally attached to them :-).

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/752405/152682189-77b8397c-72ae-4944-9833-317cb292a653.png)
![image](https://user-images.githubusercontent.com/752405/152682224-7acea2ed-d6fb-40a6-bf21-d9af2ba167d9.png)
![image](https://user-images.githubusercontent.com/752405/152682247-f3b1193c-61c7-4171-92d9-337bd22cc994.png)
![image](https://user-images.githubusercontent.com/752405/152682470-ea333032-a3e5-4e94-8425-9495f7596b3b.png)

**Comment by goyney** [comment]
[![thermometer-check](https://materialdesignicons.com/icon/thermometer-check)](https://materialdesignicons.com/icon/thermometer-check)[![snowflake-check](https://materialdesignicons.com/icon/snowflake-check)](https://materialdesignicons.com/icon/snowflake-check)

**Comment by agittins** [comment]
Brilliant, thanks Michael!
