### ISSUE TITLE
IcoFont site

### ISSUE THREAD

**Issue by mweleme** [Templarian/MaterialDesign#6453]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

There's this site called https://icofont.com/icons. It has world-class icons, about 2,500 in all. It was a project that was closed several years ago. The site is perfect for icons. one can view and download icons by category or all together and also has nice icon browsing features. I tried to do a little bit of research and I think the members (who were a few) disbanded.

Was suggesting if its possible, and if you're willing, you try and reach out to whoever is there to take over the site and move your icons there. Site hasn't been maintained for years and contains icons found nowhere else. If not, maybe you could have those icons on your site.

Thanks.

### Give us an example of what this icon might look like.

https://icofont.com/icons

**Comment by Templarian** [comment]
@mweleme May be something our parent group [Pictogrammers ](https://pictogrammers.com) could do in the future. But is a little outside the scope for now.

I'm still coding the new site on and off (backend supports multiple icon packs), but have been a little busy as of late.
