### ISSUE TITLE
Library icon

### ISSUE THREAD

**Issue by pazfelipe** [Templarian/MaterialDesign#6455]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

A spotify-based icon library. There's no icon like that or similar.

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/19727571/152890151-8faca6d9-0b42-4be5-b9f6-b1d88c59e63f.png)

**Comment by Templarian** [comment]
@pazfelipe Could you use the existing `bookshelf` icon?

[![bookshelf](https://materialdesignicons.com/icon/bookshelf)](https://materialdesignicons.com/icon/bookshelf)
