### ISSUE TITLE
Fast / Quick charge icon.

### ISSUE THREAD

**Issue by AuraHerreroRuiz** [Templarian/MaterialDesign#6456]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

A large quantity of phones (and other devices) support at least one fast charging standard, but there doesn't seem to be an universal icon for fast charging as a concept.

A new icon to communicate that a device is fast charging regardless of standard would be ideal.

### Give us an example of what this icon might look like.

The best example of an icon like this (that I know of) is seen in Xiaomi's Android, MIUI.

In MIUI 11, fast charging was represented by two lightning bolts next to each other, which indicated fast charging clearly:

![XM9SE_charging_symbol_8](https://user-images.githubusercontent.com/95187075/153155575-5d19e5f7-9e51-4f63-8712-34b0d43442b5.jpg)

However, it [allegedly got changed](https://www.reddit.com/r/Xiaomi/comments/edcano/update_removes_the_controversial_ss_logo_to/)  because the icon [seemed to resemble](https://www.notebookcheck.net/Xiaomi-might-want-to-rapidly-reconsider-its-choice-for-the-fast-charging-icon-on-MIUI-11.444040.0.html)  the [Schutzstaffel](https://en.wikipedia.org/wiki/Schutzstaffel) [flag.](https://en.wikipedia.org/wiki/File:Flag_of_the_Schutzstaffel.svg)

The icon that is used in MIUI 12 is a lightning bolt with twice the usual angles, which is a good alternative:
![Screenshot_20220209-090252_Firefox~2](https://user-images.githubusercontent.com/95187075/153155407-0d26b934-e7de-421b-8c6a-a2528611ce9d.png)

**Comment by mattrayner** [comment]
Using the design for MIUI 12 shown above I have created a suite of battery-fast-charging icons using the 'double lightning bolt' motif:

![bitmap](https://user-images.githubusercontent.com/3502902/155406258-56ca4eeb-bcf9-4139-b03e-3203ba620b42.png)

[battery-fast-charging.zip](https://github.com/Templarian/MaterialDesign/files/8127710/battery-fast-charging.zip)

**Comment by AuraHerreroRuiz** [comment]
Those are excellent, but I feel like we also need a "double" variant for `battery-charging` and `lightning-bolt`

**Comment by goyney** [comment]
> there doesn't seem to be an universal icon for fast charging as a concept

This is important to be called out. Because there isn't a standard, that puts the onus on us to not offer something that is not.

> The best example of an icon like this (that I know of) is seen in Xiaomi's Android, MIUI.

This makes this super niche, because it essentially is a vendor-specific interpretation of a concept. For us, that makes this a very niche use case.

Additionally, adding a "double" bolt would require 15 new icons to the library and I'm really unsure if it would even work at native resolution while remaining within Material guidelines.

At this time, we're going to pass on adding these. If a standardized way to indicate "fast charging" appears in the future, we'll more than likely reevaluate adding them.

Thanks for your suggesiton.

**Comment by AuraHerreroRuiz** [comment]
All valid reasons, thank you for your consideration.
