### ISSUE TITLE
Lactose free / "milk-off"

### ISSUE THREAD

**Issue by roydejong** [Templarian/MaterialDesign#6457]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Allergen or dietary preference icon to indicate food and drink products that are lactose free.

We already have a few allergen icons like `barley-off` (gluten free) and `peanut-off` (nut free), and I believe this would be a valuable addition.

### Give us an example of what this icon might look like.

This could potentially be an extension of #6387, as an "off" variant.

![image](https://user-images.githubusercontent.com/6772638/153229409-ba91474d-4004-4b17-9712-8d1b5d1dcde9.png) ![image](https://user-images.githubusercontent.com/6772638/153229459-e57a2ef5-565d-4333-b6d0-4c9c0ba2c1dc.png)

**Comment by goyney** [comment]
`cow-off` exists for this purpose. [![cow-off](https://materialdesignicons.com/icon/cow-off)](https://materialdesignicons.com/icon/cow-off)

**Comment by roydejong** [comment]
Ah, missed that one. That's great, thank you.
