### ISSUE TITLE
Request for opposite version of Google's Rotate 90 CW icon

### ISSUE THREAD

**Issue by RBarry3** [Templarian/MaterialDesign#6458]
### Before submitting a new icon request, please confirm the following:

- [x] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The icon would be used to signify to a user, their ability to rotate a single document page 90 degrees in one direction and an opposite icon signifying the ability to rotate back in the other direction.  

Ideally there would be a similar pair of icons that signify that ALL pages of a document (stack of pages) could be rotated in this fashion both clockwise and counter clockwise.

Currently Google has the icon 'Rotate 90 CW' that is close to what I'm thinking and could work for rotating clockwise and if another for counter clockwise was made.  Maybe it could look a little bit more like a document page than a generic box object?

There are are also some standard Rotate icons but in some contexts they can be confused for Restarting, Refresh, Reload, Reset, etc.

### Give us an example of what this icon might look like.

Found this icon on a competitor's product, but I don't believe it's to Google MDI standards and I don't see anything else like it in the current library.  What's nice about this is you can clearly see that it shows A) a document and B) the direction of rotation.  

![image](https://user-images.githubusercontent.com/50967254/153264498-947c5d6d-cb2c-425f-a94f-2a080bd2b3bc.png)

Another idea would be like this Model Training icon but instead of a bulb, have a document 
![image](https://user-images.githubusercontent.com/50967254/153265152-f202b63c-580e-48b4-8543-dff3630cab2d.png)
![image](https://user-images.githubusercontent.com/50967254/153267447-1bb9a8bd-97a4-4c88-8ca7-91f6a7c1be21.png)

There are standard Rotate icons but in some contexts they can be confused for Restarting, Refresh, Reload, Reset, etc.

**Comment by goyney** [comment]
[![file-rotate-right](https://materialdesignicons.com/icon/file-rotate-right)](https://materialdesignicons.com/icon/file-rotate-right)[![file-rotate-right-outline](https://materialdesignicons.com/icon/file-rotate-right-outline)](https://materialdesignicons.com/icon/file-rotate-right-outline)
[![file-rotate-left](https://materialdesignicons.com/icon/file-rotate-left)](https://materialdesignicons.com/icon/file-rotate-left)[![file-rotate-left-outline](https://materialdesignicons.com/icon/file-rotate-left-outline)](https://materialdesignicons.com/icon/file-rotate-left-outline)
