### ISSUE TITLE
required-circle-outline

### ISSUE THREAD

**Issue by mocking-mike** [Templarian/MaterialDesign#6459]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Hello, I needed an icon for a component that works like a radio button, but indicates that a chosen option is necessary. Therefor I created an icon that looks like a radiobutton with an asteriks inside. I didn't use current asteriks icon for the element inside, because it has uncommon number of hands (8) for marking a field as required (most typefaces have 5 or 6). For the same reason I don't name it asteriks-circle-outline but required-circle-outline.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/50829720/153450751-eb8dd2c0-cc65-4ed4-856a-c7a6af1546b2.png)

### Upload the icon source.

[required-circle-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/8042596/required-circle-outline.svg.zip)

**Comment by mocking-mike** [comment]
@Templarian Hello, is there a reason why the icon has not been approved yet :)?

**Comment by goyney** [comment]
Because we're all volunteers and we haven't gotten to it yet.

**Comment by mocking-mike** [comment]
@goyney Thanks for replay! I was just worried it got rejected without me knowing about it :)
