### ISSUE TITLE
Pill-off icon

### ISSUE THREAD

**Issue by ygorats** [Templarian/MaterialDesign#6460]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would use this icon on a title of "medicines/drugs restrictions", kind of a listing of the drugs I can't take.

### Give us an example of what this icon might look like.

Would be the icon Pill with a slash, would be the "pill-off" icon.

![image](https://user-images.githubusercontent.com/5714320/153451854-4cb4d486-b04c-4555-ac92-75e080ce69af.png)

**Comment by hymat** [comment]
![pill-off](https://user-images.githubusercontent.com/89099501/155414048-0aec3624-f0a5-47ba-9aec-87f77657f05f.svg)

**Comment by goyney** [comment]
Thanks @hymat, added. Once you get 5 unique icons added, we'll get them attributed to you.

[![pill-off](https://materialdesignicons.com/icon/pill-off)](https://materialdesignicons.com/icon/pill-off)
