### ISSUE TITLE
ceiling-fan timer

### ISSUE THREAD

**Issue by PAOK1926** [Templarian/MaterialDesign#6463]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Home Assistant

### Give us an example of what this icon might look like.

You have icons for ceiling fan speed, for the light, but most ceiling fans have also a timer.
so some icons with indications for 2h 4h and 8h would be nice.

**Comment by Templarian** [comment]
Tagging this with language conflict as it most likely wouldn't be possible to display these with an icon (the `1h`, `2h`, `4h`) as the `h` in could be confusing.

**Comment by goyney** [comment]
A simple `clock` variant with the ceiling fan would be the logical choice here.

**Comment by PAOK1926** [comment]
i finally made it without the fan icon.. :)
![Screenshot 2022-02-15 at 19 09 51](https://user-images.githubusercontent.com/31358094/154113086-5cdc34e7-367d-415d-9e41-3985695caae9.png)

**Comment by goyney** [comment]
Adding clock to the `ceiling-fan` doesn't really work, but we can add this one:
![image](https://user-images.githubusercontent.com/1015040/159059597-665348b0-d7ab-49bf-b22c-8d8dab914976.png)

[fan-clock.svg.zip](https://github.com/Templarian/MaterialDesign/files/8306725/fan-clock.svg.zip)

**Comment by goyney** [comment]
Added.
