### ISSUE TITLE
(jet-)turbine

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#6464]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

A gas or jet turbine (turbo engine). Design is based on `wind-turbine` and `hydro-power` icons.

### Share a preview of your contribution.

![grafik](https://user-images.githubusercontent.com/7279415/153890474-5e665dc0-7182-4ce4-b660-5b98a0229153.png)

### Upload the icon source.

[turbine.zip](https://github.com/Templarian/MaterialDesign/files/8061832/turbine.zip)

**Comment by Templarian** [comment]
`jet-turbine` seems like an okay name for this, but `turbine` is also fine.

**Comment by goyney** [comment]
[![turbine](https://materialdesignicons.com/icon/turbine)](https://materialdesignicons.com/icon/turbine)
