### ISSUE TITLE
Website Down

### ISSUE THREAD

**Issue by preraksola** [Templarian/MaterialDesign#6465]
### What is your question?

Is the website https://materialdesignicons.com down?

I am unable to access it and get DNS_PROBE_FINISHED_NXDOMAIN.

**Comment by Templarian** [comment]
@preraksola Seems fine here. Tried from Chicago and west coast through a VPN. I have AWS setup with various alerts and nothing triggered, but maybe it was only for a quick second.

Going to close this out. But let me know what region if you're still seeing it. I only host in a single region for cost reasons.
