### ISSUE TITLE
Are you planning to add icon variants?

### ISSUE THREAD

**Issue by mwskwong** [Templarian/MaterialDesign#6466]
### What is your question?

Official Material icons have different icon variants like rounded and two-tone. Are there any plans to add variants for most, if not all of the icons? e.g. Rounded and outlined database icon.

**Comment by Templarian** [comment]
@mwskwong No plans, as we haven't seen a large ask. We'll probably expand into the Light variant to make it more fully featured in the future. Right now Filled and Outline are the main focus.

https://github.com/Templarian/MaterialDesignLight
