### ISSUE TITLE
Quiz, Q&A

### ISSUE THREAD

**Issue by klarson2** [Templarian/MaterialDesign#647]
Quiz icon: perhaps question mark with pencil overlay
Q&A icon: overlay stock "message" & "message reply" icons (thought I saw a stock "forum" icon like this somewhere), maybe add a question mark or something

**Comment by CoDEmanX** [comment]
Hm, only if you use the full 24px with no margin left:
![quiz](https://cloud.githubusercontent.com/assets/1309249/9562771/64772922-4e76-11e5-8ab0-1b251fe2cffe.png)
Perhaps just question and exclamation mark? But that might look like "what the f***?!?!"

**Comment by Templarian** [comment]
I think without the exclamation mark it looks like Q/A. The ! makes it look like it might be a 'F#$#' type forum related icon.

**Comment by CoDEmanX** [comment]
You mean like
![fu](https://cloud.githubusercontent.com/assets/1309249/9564350/9aa6be08-4ea4-11e5-9986-5b0483fd4a17.gif)

**Comment by Templarian** [comment]
Yea, pretty much. :laughing:

**Comment by klarson2** [comment]
Google actually lists that forum icon as "question answer" in the Action section...

I'm more interested in Quiz which doesn't have any close matches. Other ideas would be: question mark on the left with vertical checkboxes on the right, or borrow the "library" icon (person reading book) and put a question mark on the book.  Another idea: question mark on the left and vertical A. B. C. on the right; although "good" icons aren't supposed to have letters in them...  IDK, you're the designers, I'm just trying to jump-start the effort.

**Comment by JamesCoyle** [comment]
Gonna close this one out due to lack of ideas. If anyone can come up with something clear enough, please let us know.
