### ISSUE TITLE
desktop-duotone

### ISSUE THREAD

**Issue by SaiCorporation** [Templarian/MaterialDesign#6470]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [x] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

In a website, you could be programming a download button which downloads the file for a desktop.

### Share a preview of your contribution.

![desktop-duotone_nox!](https://user-images.githubusercontent.com/74317023/154818463-c1fd4035-4b0b-4682-bbe3-d49086bf5162.png)
![desktop-duotone_lumos!](https://user-images.githubusercontent.com/74317023/154818477-0d154ea9-8d8a-41ec-83ef-0d0917d35fcf.png)

### Upload the icon source.

[desktop-duotone.zip](https://github.com/Templarian/MaterialDesign/files/8102984/desktop-duotone.zip)

**Comment by goyney** [comment]
We do not currently support duotone icons.

**Comment by SaiCorporation** [comment]
OK sure
