### ISSUE TITLE
Repost arrows

### ISSUE THREAD

**Issue by tomasstofik** [Templarian/MaterialDesign#6472]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I couldn't find icon with two arrows for repost

### Give us an example of what this icon might look like.

![5436565](https://user-images.githubusercontent.com/45800877/154869800-74695dc3-6cbe-416d-970a-c2d4f3ba2c37.png)

**Comment by Templarian** [comment]
@tomasstofik Could you use `repeat` or `repeat-variant`? (`repeat-once` is also there since these are commonly used in music apps).

**Comment by goyney** [comment]
This concept is already included in a few variations. I don't feel we need another.
[![repeat](https://materialdesignicons.com/icon/repeat)](https://materialdesignicons.com/icon/repeat)[![repeat-variant](https://materialdesignicons.com/icon/repeat-variant)](https://materialdesignicons.com/icon/repeat-variant)
