### ISSUE TITLE
Stone lamp (Saltstone, Selenite, etc.)

### ISSUE THREAD

**Issue by JoryHogeveen** [Templarian/MaterialDesign#6474]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'm requesting here since Home Assistant is using this icon library.

### Give us an example of what this icon might look like.

It would be awesome if there would be icons available for stone type lamps like:

- Salt stone lamp: https://en.wikipedia.org/wiki/Himalayan_salt#/media/File:Saltlamp.jpg
- Selenite stone lamp: https://www.amazon.com/Himalayan-Glow-1333-Pillar-Chunks/dp/B01N1WK0GX

**Comment by JoryHogeveen** [comment]
Not sure why, as I did search, but I just found a related topic: https://github.com/Templarian/MaterialDesign/issues/5302

**Comment by Templarian** [comment]
Marking this a duplicate. Lets use the Salt Lamp request.
