### ISSUE TITLE
Missing icons, "mdiTriangleSmallDown" and "mdiTriangleSmallUp"

### ISSUE THREAD

**Issue by ninanung** [Templarian/MaterialDesign#6486]
### What is your question?

It looks these icons added 4 month ago but still can't use it with latest release. How long does it usually take for an icon to be added to a release version?

**Comment by Templarian** [comment]
@ninanung Bit behind in releases right now. These will go out very soon.

**Comment by goyney** [comment]
Yep, these should go out in `6.6.95`, which we just wrapped and expect to go out in the next week.
