### ISSUE TITLE
inconsictency in `home-*-outline` icons

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#6489]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

I noticed that the various `home-*-outline` icons use different base icons.
![grafik](https://user-images.githubusercontent.com/7279415/157093458-a3388c37-e613-47af-a80f-42a340868c5a.png)
Even though I can partially follow that this probably done in some cases to add inner modifiers, I don't think that it is necessary for most cases. The following table provides an overview, which icons are using the *correct* base icon and which do not, along with an indication if this is valued necessary (to maintain appropriate space to the outline).
| *correct* base shape | alternative shape           |                    |
|---------------------|-----------------------------|--------------------|
| home-alert-outline  |                             |                    |
|                     | home-battery-outline        | not necessary      |
|                     | home-export-outline         | not necessary      |
|                     | home-import-outline         | not necessary      |
|                     | home-lightbulb-outline      | not sure           |
|                     | home-lightning-bolt-outline | probably necessary |
|                     | home-minus-outline          | not necessary      |
|                     | home-plus-outline           | not necessary      |
|                     | home-remove-outline         | not necessary      |
| home-search-outline |                             |                    |
| home-switch-outline |                             |                    |
|                     | home-thermometer-outline    | not sure           |

![grafik](https://user-images.githubusercontent.com/7279415/157094921-26c8685d-34e3-4002-b91b-55c70f8620de.png)
![grafik](https://user-images.githubusercontent.com/7279415/157095274-ebd504a3-f73d-44d6-9709-6e79b07a3a93.png)
![grafik](https://user-images.githubusercontent.com/7279415/157095456-71ff1ac4-1129-41d9-ab68-84835646a1fc.png)
![grafik](https://user-images.githubusercontent.com/7279415/157095719-08f47243-3852-4a92-838b-6cd69261531c.png)
![grafik](https://user-images.githubusercontent.com/7279415/157096041-b4bae984-0b85-4f55-8d92-3e3054c658de.png)
![grafik](https://user-images.githubusercontent.com/7279415/157096270-79f06a54-dcdf-40fa-8191-3f3116890cbf.png)
![grafik](https://user-images.githubusercontent.com/7279415/157096396-f00a5a1e-d3d8-4822-bfb2-c15018b0bba4.png)
![grafik](https://user-images.githubusercontent.com/7279415/157096603-aad8b412-67df-4985-b7da-fd3808c6f9ae.png)
![grafik](https://user-images.githubusercontent.com/7279415/157096972-de773ecb-81ed-49b4-a701-94e484b6fbb4.png)

[home-outline.zip](https://github.com/Templarian/MaterialDesign/files/8200073/home-outline.zip)

WDYT?

**Comment by Templarian** [comment]
This definitely is a good bug. 😆 Not sure how it got so bad.

**Comment by boehan** [comment]
Even though, the minority of the above icons uses the *correct* shape, I would still go for that since it is

- the shape of `home-outline`, an official google icon
- the same shape as the filled `home` icon
- also used in other variants, such as `home-switch-outline` or `home-edit-outline` in modified forms (without affecting the outer shape/proportions)

Following your list, I think I have covered all items above, except `home-alert-outline`, which I don't think needs modification.
Since you also listed the non-outline `home-battery` I also had a look at it and made some minor corrections on the battery shape and cutout in both versions.
![grafik](https://user-images.githubusercontent.com/7279415/157884876-07bc2d01-9e9e-4798-8909-f24ca4a0ae31.png)

Furthermore, with regard to the battery modifier, I am wondering if it wouldn't make sense to change some other icons to using overlapping modifiers as well (would also affect non-outline versions). E.g., at least `plus`, `minus` and `remove` do not follow the common guidelines...
For the thermometer version also a *battery-like* modifier would be more consistent IMO (sorry to bring this up again as something similar was just rejected in #6484 ):
![grafik](https://user-images.githubusercontent.com/7279415/157886467-fe50b5b0-12d6-4b35-80b5-07e6c67e75d1.png)

Apart from that, all above corrections are collected here: [home.zip](https://github.com/Templarian/MaterialDesign/files/8232725/home.zip)

**Comment by Templarian** [comment]
Closing this one out. Agreed about moving the `plus`/`minus`/`remove` outside.

https://dev.materialdesignicons.com/history
