### ISSUE TITLE
Feedback icon

### ISSUE THREAD

**Issue by SaitejaP** [Templarian/MaterialDesign#649]
Since feedback will be used very frequently. I suggest an icon for it too.

**Comment by Templarian** [comment]
Do you have an example?

**Comment by SaitejaP** [comment]
Something of [this](https://dribbble.com/shots/1103908-Feedback-Icon) sort (text message bubble)

**Comment by CoDEmanX** [comment]
?
[![comment-text](https://materialdesignicons.com/icon/comment-text)](https://materialdesignicons.com/icon/comment-text)

**Comment by SaitejaP** [comment]
Oh! I din't notice it. Sorry.

Thanks for the help.

**Comment by CoDEmanX** [comment]
@Templarian: "feedback" could be added to both variants of this icon.
