### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by dlangley7** [Templarian/MaterialDesign#6491]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

There is a route icon (pole with 3 'flags'). There is also one with a clock.  I need one with the clock on one side and a dollar sign on the other side.

### Give us an example of what this icon might look like.

![RouteGuideIcon](https://user-images.githubusercontent.com/101208995/157298730-73f19211-2cb4-4bc3-a0f4-a08d1a79bb1a.png)

**Comment by goyney** [comment]
We do not add country specific currency symbols to icons. Thanks for the suggestion.

**Comment by dlangley7** [comment]
Could you use ?0.00

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
