### ISSUE TITLE
PayPal Icon

### ISSUE THREAD

**Issue by pebnn** [Templarian/MaterialDesign#6495]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

PayPal button linking to paypal website

### Give us an example of what this icon might look like.

![453-4537298_paypal-logo-icon-paypal-logo-png-transparent-png](https://user-images.githubusercontent.com/95236935/157857370-1cb7ddec-4da6-4db9-b0b1-9e006196ffb7.png)

![453-4537298_paypal-logo-icon-paypal-logo-png-transparent-black](https://user-images.githubusercontent.com/95236935/157858083-99ea35fe-e180-4ea4-8388-8ca23c538e5a.png)

**Comment by JamesCoyle** [comment]
> * [x]  I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.

PayPal is a brand.
