### ISSUE TITLE
shimmer-variant

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6497]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I wanted to use this as a generic icon to represent "automatic" functions. The single shimmer appears in some icons like `image-auto-adjust` or `face-man-shimmer`, so this would tie these together without the far sparklier `shimmer` icon. Maybe `-variant` isn't the right suffix, but `-small` and `-single` didn't seem right. Any thoughts?

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/158045296-674141b4-74c3-48bd-a08a-304dadf2be51.png)

### Upload the icon source.

[shimmer-single.svg.zip](https://github.com/Templarian/MaterialDesign/files/8238963/shimmer-single.svg.zip)

**Comment by goyney** [comment]
Already exists. :)

[![star-four-points](https://materialdesignicons.com/icon/star-four-points)](https://materialdesignicons.com/icon/star-four-points)

**Comment by jhil** [comment]
Ah! I just didn't know the right query. Thanks!
