### ISSUE TITLE
CD-ROM/DVD-ROM disk

### ISSUE THREAD

**Issue by mooction** [Templarian/MaterialDesign#6498]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Currently we do not have an icon for CD/DVD ROM (although we have hard disk icon). This is useful for `*.iso` files

### Give us an example of what this icon might look like.

![data-disc-dvd-cd-compact-256](https://user-images.githubusercontent.com/8206464/158100812-a07c4bdf-dba6-427d-9b00-28a2e6dd12d3.png)

**Comment by goyney** [comment]
[![disc](https://materialdesignicons.com/icon/disc)](https://materialdesignicons.com/icon/disc)
