### ISSUE TITLE
swap-reverse-bold

### ISSUE THREAD

**Issue by patstew** [Templarian/MaterialDesign#6499]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I'd like to indicate incoming then outgoing, and vice versa, so I'd like this vertically flipped version of swap-horizontal-bold

### Share a preview of your contribution.

![canvas](https://user-images.githubusercontent.com/4478567/158386122-482d537f-3ae0-4652-885a-c3a6972b0036.png)

### Upload the icon source.

![swap-reverse-bold](https://user-images.githubusercontent.com/4478567/158386233-8927e72a-d9cb-495b-9baf-766914e3c9a4.svg)

**Comment by goyney** [comment]
This would be a case where we'd expect you to flip the icon via CSS and doesn't warrant a new addition. Thanks for the suggestion.
