### ISSUE TITLE
Counter Strike icon

### ISSUE THREAD

**Issue by SuperCreeper** [Templarian/MaterialDesign#650]
Something like this: 
![image](https://cloud.githubusercontent.com/assets/6864020/9576971/b5c1e25c-4fe5-11e5-9c6b-38aaac3c142d.png)

**Comment by CoDEmanX** [comment]
I'd say too specific, and hardly possible to do compliant to MD guidelines. Added a generic soldier request to #365.

**Comment by Templarian** [comment]
Yea, it's too detailed and specific for this icon set.
