### ISSUE TITLE
Default icon for blog

### ISSUE THREAD

**Issue by SophiadbLopes000** [Templarian/MaterialDesign#6503]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I will use it for buttons indicating blogs on site

### Give us an example of what this icon might look like.

![TT - icons blog](https://user-images.githubusercontent.com/101829769/158876708-51406721-1f2b-46c5-b4f5-4698ad95ddea.png)

**Comment by goyney** [comment]
We have plenty of generic icons that could indicate a blog. What you're proposing above is the Blogger logo, which we will not add. Do some searches on our library for "blog", "news", "document", etc.
