### ISSUE TITLE
Tag with Checkmark

### ISSUE THREAD

**Issue by mbarone1** [Templarian/MaterialDesign#6509]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Currently I use Tag to indicate a garment that goes into alterations
I would like tag with checkmark to indicate that the alterations are finished.

### Give us an example of what this icon might look like.

like tag-plus or tag-plus-outline but with a checkmark :)

**Comment by goyney** [comment]
[![tag-check](https://materialdesignicons.com/icon/tag-check)](https://materialdesignicons.com/icon/tag-check)[![tag-check-outline](https://materialdesignicons.com/icon/tag-check-outline)](https://materialdesignicons.com/icon/tag-check-outline)

**Comment by mbarone1** [comment]
This is awsome. Thank you!
