### ISSUE TITLE
Plan icon request

### ISSUE THREAD

**Issue by Drabiv** [Templarian/MaterialDesign#651]

**Comment by CoDEmanX** [comment]
Do you have an example?

**Comment by Drabiv** [comment]
Sorry, no. I think it should be something like calendar icon, but with indication that it is a calendar for the future.

**Comment by CoDEmanX** [comment]
Most calendars are used to plan for the future...

**Comment by Templarian** [comment]
Or calendar check could be used I think.

[![calendar-clock](https://materialdesignicons.com/icon/calendar-clock)](https://materialdesignicons.com/icon/calendar-clock)

**Comment by Drabiv** [comment]
Calendar with a plus will do. Thanks. I am closing this issue.
