### ISSUE TITLE
Autopay icons

### ISSUE THREAD

**Issue by carlsonaaron** [Templarian/MaterialDesign#6511]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Indicating budget transactions that are automatically paid/drafted without manual user interaction.  

### Give us an example of what this icon might look like.

Option 1:
![3b6799f768f39921f4a5771489241a2f](https://user-images.githubusercontent.com/9780297/159403961-09529c92-6dc6-4e40-93b0-0cd117eb5301.jpg)

Option 2:
![dollar-money-icon-usd-graphic-pay-business-sign-market-economy-vector-illustration-199365742](https://user-images.githubusercontent.com/9780297/159403977-f38712dc-375c-4643-a680-03d5f3c8d471.jpg)

**Comment by goyney** [comment]
We cannot use the USD symbol as it is not universal. But maybe `cash-clock` or `cash-sync` would work.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/159616939-19f73ae5-3b56-4581-89fc-4b50681f114f.png)![image](https://user-images.githubusercontent.com/1015040/159617012-1959e3d3-5442-4464-9a86-1229a0bf4f66.png)

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/8329438/Archive.zip)

**Comment by carlsonaaron** [comment]
Those look great!

**Comment by goyney** [comment]
[![cash-clock](https://materialdesignicons.com/icon/cash-clock)](https://materialdesignicons.com/icon/cash-clock)[![cash-sync](https://materialdesignicons.com/icon/cash-sync)](https://materialdesignicons.com/icon/cash-sync)
