### ISSUE TITLE
Request for "Organization Structure" Icon

### ISSUE THREAD

**Issue by Ayman97** [Templarian/MaterialDesign#6512]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need it for Org Structure Page in a EPM software

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/10719494/159691927-d5f7a197-7f90-492b-9fd8-1a153dfa5d6a.png)

**Comment by goyney** [comment]
I think you're going to want to look at our `sitemap` icons. That many little account icons don't work in the limited space.

[![sitemap](https://materialdesignicons.com/icon/sitemap)](https://materialdesignicons.com/icon/sitemap)[![sitemap-outline](https://materialdesignicons.com/icon/sitemap-outline)](https://materialdesignicons.com/icon/sitemap-outline)

**Comment by Templarian** [comment]
Maybe `account` + at the top of the sitemap? possibly with circles.

**Comment by goyney** [comment]
We also have `family-tree` which might be a better fit for this:
[![family-tree](https://materialdesignicons.com/icon/family-tree)](https://materialdesignicons.com/icon/family-tree)

**Comment by Ayman97** [comment]
Sorry @goyney  I didn't check the notifications 😅
Thanks a lot. the one with the circles is better.

Thanks @Templarian for the suggestion.

**Comment by goyney** [comment]
Looks like this was solved with `family-tree`. Closing.
