### ISSUE TITLE
Rounded Corner Top Right

### ISSUE THREAD

**Issue by SintijaPotaicuka** [Templarian/MaterialDesign#6517]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I am looking into designing a "Designer panel" and need to display corner radius values.
Inspiration is taken from Figma, border-radius generators, and this dribble shot: https://dribbble.com/shots/14763903-Belder-Web-Builder-Dashboard

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/102287459/159884344-82a5b1d1-1465-4189-bd2b-97620094b67e.png)

### Upload the icon source.

[rounded-corner-top-right.svg.zip](https://github.com/Templarian/MaterialDesign/files/8340137/rounded-corner-top-right.svg.zip)

**Comment by Ben-Heel** [comment]
رمز حلو
