### ISSUE TITLE
'Auto-fix' by Google

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#652]
Searching on the site for 'wand' or 'magic' doesn't return the ['auto-fix' icon by Google](https://materialdesignicons.com/icon/auto-fix), would be nice if it did.

And it seems the icon is removed from the [official overview](https://www.google.com/design/icons/), but I guess it would be nice to still have it included it in the community edition.

**Comment by CoDEmanX** [comment]
Yeah, I noticed that too and noted it here: https://github.com/Templarian/MaterialDesign/issues/518#issuecomment-124140303

I think we really need that new tagging system for contributors to add this and other search helpers.

**Comment by Templarian** [comment]
Aliases are added.
