### ISSUE TITLE
Rounded Corners

### ISSUE THREAD

**Issue by SintijaPotaicuka** [Templarian/MaterialDesign#6520]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I am looking into designing a "Designer panel" and need to display corner radius values.
Inspiration is taken from Figma, border-radius generators, and this dribble shot: https://dribbble.com/shots/14763903-Belder-Web-Builder-Dashboard

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/102287459/159888445-4b01544a-b37e-4f80-8f42-8c2be8a6d1ef.png)

### Upload the icon source.

[rounded-corner.svg.zip](https://github.com/Templarian/MaterialDesign/files/8340317/rounded-corner.svg.zip)

**Comment by goyney** [comment]
[![border-radius](https://materialdesignicons.com/icon/border-radius)](https://materialdesignicons.com/icon/border-radius)
