### ISSUE TITLE
Format paragraph spacing

### ISSUE THREAD

**Issue by SintijaPotaicuka** [Templarian/MaterialDesign#6521]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I am looking into designing a "Designer panel" and need to paragraph spacing. Inspiration is taken from the Figma design panel.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/102287459/159889028-4dfea6de-ea0f-4be4-8b26-150504ef2b47.png)

### Upload the icon source.

[format-paragraph-spacing.svg.zip](https://github.com/Templarian/MaterialDesign/files/8340331/format-paragraph-spacing.svg.zip)

**Comment by goyney** [comment]
[![format-paragraph-spacing](https://materialdesignicons.com/icon/format-paragraph-spacing)](https://materialdesignicons.com/icon/format-paragraph-spacing)
