### ISSUE TITLE
format-line-height-variant

### ISSUE THREAD

**Issue by SintijaPotaicuka** [Templarian/MaterialDesign#6522]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Alternative to existing line-height icons. 
Inspiration is taken from Figma and dribble design shots.

I would like to have this alternative to align with the letter-spacing icon suggestion[ ( new issue )](https://github.com/Templarian/MaterialDesign/issues/6523)
![image](https://user-images.githubusercontent.com/102287459/159892003-20cfa541-a460-4347-9de4-81c0ccf4d4c7.png)

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/102287459/159891836-b0dcb3bc-0e71-4a4e-934c-089130be8528.png)

### Upload the icon source.

[format-line-height-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/8340451/format-line-height-variant.svg.zip)

**Comment by goyney** [comment]
[![format-line-height](https://materialdesignicons.com/icon/format-line-height)](https://materialdesignicons.com/icon/format-line-height)
