### ISSUE TITLE
plane-car

### ISSUE THREAD

**Issue by alketaselimaj24** [Templarian/MaterialDesign#6524]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would like to have an icon that shows combined methods of transportation:
- Plane + Car
- Plane + Train 
- Plane + Car + Train 

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/72202915/159898778-321e5323-d0ce-44a2-97ec-a5d53e931129.png)

**Comment by goyney** [comment]
We already have `train-car`. Following that style...

![image](https://user-images.githubusercontent.com/1015040/160037155-806478ee-3b34-475b-b7c6-a1a7313ac5cc.png)![image](https://user-images.githubusercontent.com/1015040/160037170-4b2294ef-c77b-4d42-b4b0-d95b7c24d0c9.png)
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/8346682/Archive.zip)

They _kinda_ work. Fitting all three into one icon isn't going to happen easily (nor do I think we should try).

Will await feedback on these from the other contributors.

**Comment by Templarian** [comment]
I think the small cut out is fine. These are both common transport icons I've seen. Concur has similar icons when booking travel.

**Comment by goyney** [comment]
Both added.
