### ISSUE TITLE
icon de abecedario y un icon de traducción

### ISSUE THREAD

**Issue by FapCod** [Templarian/MaterialDesign#6525]
Google Translated Title: alphabet icon and a translation icon

### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

El icon de abecedario lo usaria para mostrar en mi aplicación un abecedario.
El icon de traducción lo usaria para mostrar en mi aplicacion una traducción. 

Google Translation:
The alphabet icon would be used to display an alphabet in my application.
The translation icon would be used to display a translation in my application.

### Give us an example of what this icon might look like.

Por ejemplo el de abecedario seia mostrando la A,B y C.
Por ejemplo el de traduccion seria mostrando el famoso icono de google traductor o algo similar.

Google Translation:
For example, the alphabet would be showing A, B and C.
For example, the translation would be showing the famous google translator icon or something similar.

**Comment by goyney** [comment]
Thanks for the suggestion. If possible, please use English when creating issues.

As far as your two icon suggestions, we already have icons that fit your examples:
[![alphabetical](https://materialdesignicons.com/icon/alphabetical)](https://materialdesignicons.com/icon/alphabetical)[![translate](https://materialdesignicons.com/icon/translate)](https://materialdesignicons.com/icon/translate)

Will these work for you?
