### ISSUE TITLE
table-radio

### ISSUE THREAD

**Issue by sleepingaliencreature** [Templarian/MaterialDesign#6526]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The icon table-check already exist in library. The new table-radio should be used additionally to that one as some tool for tables.
In my case it would be used as "create table with radio buttons"
[table-radio.zip](https://github.com/Templarian/MaterialDesign/files/8344103/table-radio.zip)

### Give us an example of what this icon might look like.

https://materialdesignicons.com/icon/table-check
https://materialdesignicons.com/icon/table-plus

**Comment by goyney** [comment]
Preview of the contribution:
![image](https://user-images.githubusercontent.com/1015040/160036172-1d4f43f7-4247-405f-8e6a-e9dc61d9d2fc.png)

**Comment by goyney** [comment]
To me, it looks more like a target or bullseye. However, that is a non-standard modifier and we're usually cautious about adding new ones.

I wonder if this use-case might be too niche for the library, but will allow some time for the other contributors to weigh in.

**Comment by Dem0n3D** [comment]
> To me, it looks more like a target or bullseye. However, that is a non-standard modifier and we're usually cautious about adding new ones.

In which place radio is a non-standard?

**Comment by Templarian** [comment]
This seems a little too niche for it to be included. 🤷‍♂️

**Comment by goyney** [comment]
Thanks for the suggestion, but we're going to pass on this icon at this time.
