### ISSUE TITLE
Calendar with a badge

### ISSUE THREAD

**Issue by cagdasalagoz** [Templarian/MaterialDesign#6527]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This might indicate the calendar needs an action or has an update that you might want to check out.

Also in a list of notifications which are separated by their type of notification (for example notifications about the account information is using the account icon. While notifications about items added to your calendar while you're gone can use calendar icon. But to differentiate the notifications that are new and requires attention from the older ones this icon might be useful.

### Give us an example of what this icon might look like.

calendar icon with the badge that is used in message-badge

**Comment by goyney** [comment]
[![calendar-badge](https://materialdesignicons.com/icon/calendar-badge)](https://materialdesignicons.com/icon/calendar-badge)[![calendar-badge-outline](https://materialdesignicons.com/icon/calendar-badge-outline)](https://materialdesignicons.com/icon/calendar-badge-outline)
