### ISSUE TITLE
Reddit Icon

### ISSUE THREAD

**Issue by joaopluis** [Templarian/MaterialDesign#653]
I needed a Reddit icon and already checked the existing issues, along with the outline icon that didn't fit the set.

Based on that icon a made a filled version. I made it with Illustrator. Hope it gets included!

(I saw the contributor option, but I don't have 4 more icons...)

http://joaopluis.pt/reddit.svg

**Comment by Templarian** [comment]
[![reddit](https://materialdesignicons.com/icon/reddit)](https://materialdesignicons.com/icon/reddit)

If you do create 4 more reference this one it will be transferred to your account. Thanks!
