### ISSUE TITLE
"Lecturn" is misspelled and should be "lectern"

### ISSUE THREAD

**Issue by curtgrimes** [Templarian/MaterialDesign#6532]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

`mdi-lecturn` added in #5053 is misspelled and should be "lectern" (`mdi-lectern`) instead.

Sources:
- https://schoolandtravel.com/lecturn/ - "[lecturn] is an ancient or incorrect way of spelling the ideal word “Lectern”."
- https://www.dictionary.com/browse/lectern - "a reading desk in a church on which the Bible rests and from which the lessons are read during the church service. a stand with a slanted top, used to hold a book, speech, manuscript, etc., at the proper height for a reader or speaker."
- https://www.dictionary.com/browse/lecturn "No results found for lecturn"
- https://en.wikipedia.org/wiki/Lectern - "A lectern is a reading desk with a slanted top, on which documents or books are placed as support for reading aloud, as in a scripture reading, lecture, or sermon"
- https://en.wikipedia.org/wiki/Lecturn - redirects to [Lectern](https://en.wikipedia.org/wiki/Lectern)

**Comment by goyney** [comment]
Done.
