### ISSUE TITLE
bag-personal-tag

### ISSUE THREAD

**Issue by mat2718** [Templarian/MaterialDesign#6534]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

this will be used in an app made for U.S. Customs and border patrol for scanning property tags

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/22265388/161281149-c94081f9-c5e9-4e11-ab4a-ba4a91e0c4e1.png)

### Upload the icon source.

[Property Tag Dark 2.zip](https://github.com/Templarian/MaterialDesign/files/8398623/Property.Tag.Dark.2.zip)

**Comment by goyney** [comment]
We've never used `tag` as a modifier before, however I can see the use case here. However, the base icon will need to use our `bag-personal` icon.

[![bag-personal](https://materialdesignicons.com/icon/bag-personal)](https://materialdesignicons.com/icon/bag-personal)

**Comment by mat2718** [comment]
thank you for your assistance on this! I have included a preview and updated zip file for your review. additionally, for my reference is it advised to submit an individual issue for each icon or is the preference for one icon = one issue?

updated image:
![image](https://user-images.githubusercontent.com/22265388/161431051-87e5a193-80b7-420d-b8ea-962ef9d98dbd.png)

updated zip:
[property-tag.zip](https://github.com/Templarian/MaterialDesign/files/8404644/property-tag.zip)

**Comment by mat2718** [comment]
here is the outlined version as well. if this needs to be a separate issue please let me know and I will be happy to make one. thank you for your time. :)

Outline Preview:
![image](https://user-images.githubusercontent.com/22265388/161432785-28a4f274-88e3-4e62-aae4-37cdd564b9d1.png)

Outline Zip:
[property-tag-outline.zip](https://github.com/Templarian/MaterialDesign/files/8404716/property-tag-outline.zip)

**Comment by goyney** [comment]
This is going in the right direction, but it still needs some work. We already have a tag icon that should be used for the tag. It will also need to follow Material guidelines and have a 2dp cutout around it. Try placing the tag in the lower right corner, that's the typical place for a modifier.

**Comment by mat2718** [comment]
i apologize for my newness on this.. before I make the outlined icon, do you happen to have any additional feedback on this updated icon?

Icon Preview:
![image](https://user-images.githubusercontent.com/22265388/161593469-fccabc7a-d1a2-4ca5-93c6-865c75cd7116.png)

Icon Zip:
[property-tag (2).zip](https://github.com/Templarian/MaterialDesign/files/8411668/property-tag.2.zip)

**Comment by goyney** [comment]
No need for apologies, this is how we learn! You're doing great!

I'd probably use the generic `tag` as the modifier. A modifier is a smaller symbol that "modifies" the meaning of the base icon. Our more common modifiers are things like `plus`, `check`, `marker`, etc.

[![tag](https://materialdesignicons.com/icon/tag)](https://materialdesignicons.com/icon/tag)

Most of our modifiers "cut-out" the base icon in the shape of a circle (look at any plus or minus icons). But in this case, the tag wouldn't fit nicely inside a circle cut-out, so we'll need it to have a 2dp cut out that follows the shape of the tag. Look at this `marker` modifier for an example:

[![file-marker](https://materialdesignicons.com/icon/file-marker)](https://materialdesignicons.com/icon/file-marker)

Notice how around the marker, there is a full 2dp of white space separating the base icon and the modifier.

Lastly, if looks like you move the bag over like .5dp so it is no longer "on-grid." We want to try to keep points and lines on the grid as much as possible. When things are off-grid, they become blurrier, quicker when the are shrunk down.

Let us know if you have any other questions.

**Comment by mat2718** [comment]
one more time lol also thank you for your help on this :)

option one preview:
![image](https://user-images.githubusercontent.com/22265388/161619892-fe260d68-434b-43c3-abcc-4c2a5e433e64.png)

option one zip:
[property-tag option 1.zip](https://github.com/Templarian/MaterialDesign/files/8412695/property-tag.option.1.zip)

option 2 preview: 
![image](https://user-images.githubusercontent.com/22265388/161620086-6a5cf4d0-c59d-4d93-a1d5-c5e0319e97ad.png)

option 2 zip: 
[property-tag option 2.zip](https://github.com/Templarian/MaterialDesign/files/8412699/property-tag.option.2.zip)

**Comment by goyney** [comment]
Now you got it! Just need to have a 2dp cutout, looks like only 1dp there.

I like the second option. Could you expand that cutout and perhaps move the bag 2dp to the left, leaving the tag where it is?

**Comment by mat2718** [comment]
hows this?

preview:
![image](https://user-images.githubusercontent.com/22265388/161773590-86815311-72f8-4ff5-be3b-ee55e7844105.png)

zip:
[property-tag option 3.zip](https://github.com/Templarian/MaterialDesign/files/8418877/property-tag.option.3.zip)

**Comment by Templarian** [comment]
@boehan Appreciate it. The core team usually tweaks them before the final upload into the system.

We have the next 2 releases almost ready, so adding the 6.9.xx tag.

**Comment by goyney** [comment]
[![bag-personal-tag](https://materialdesignicons.com/icon/bag-personal-tag)](https://materialdesignicons.com/icon/bag-personal-tag)[![bag-personal-tag-outline](https://materialdesignicons.com/icon/bag-personal-tag-outline)](https://materialdesignicons.com/icon/bag-personal-tag-outline)
