### ISSUE TITLE
heat-wave missing in CSS file but shows in 6.5.95

### ISSUE THREAD

**Issue by walkoffhomerun** [Templarian/MaterialDesign#6535]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

6.5.95 shows a "heat-wave" icon but it is not available.  searched the CSS file and not shown.  could it be under a different name?  search "heat" variations but those are all accounted for.  searched "wave" but those are accounted for as well.  looks as if it was just left out

**Comment by goyney** [comment]
See: https://github.com/Templarian/MaterialDesign/issues/6325

It was added in v6.7.96 which is still pending release. It should go out this weekend or early next week./
