### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#654]
Would be nice to include a link to the [OFL](http://scripts.sil.org/cms/scripts/page.php?site_id=nrsi&id=OFL#5667e9e4) in readme.md.
And I'm also wondering if 'Free' for the templates is like a proper license - after all proprietary stuff can also be 'free'. Is it meant to be in the [Public Domain](https://creativecommons.org/publicdomain/)?

**Comment by Templarian** [comment]
Yes, public domain, I'll put it under wtfpl license when I get a second to update the wording.

Linked the text also to the license text.

Thanks!

**Comment by davelab6** [comment]
This isn't legal advice: The WTFPL isn't a 'real' license - eg, no warranty disclaimer means warranties are implied, which is unlikely what you want - and I recommend moving away from it to something recognised by the Open Source Initiative or recommended Free Software Foundation.
