### ISSUE TITLE
I need to request for icons on Figma, Laravel, Vue, React and React-Native

### ISSUE THREAD

**Issue by oluwaeinstein007** [Templarian/MaterialDesign#6540]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need them for my portfolio website

### Give us an example of what this icon might look like.

Any variation of those logos will do

**Comment by goyney** [comment]
All of these are available in the Simple Icons library. We've halted adding any brand icons at this time as we prepare to start building our own brand icon library.
