### ISSUE TITLE
Dev site: icon search doesn't work

### ISSUE THREAD

**Issue by okyr-ux** [Templarian/MaterialDesign#6541]
### Where are you experiencing this bug?

Somewhere else

### What is the issue you are experiencing?

I open the dev.site https://dev.materialdesignicons.com/icons
I type the search term into the search field in the top right corner, click the button „All results for %s“, the results page loads, but it contains all icons instead of the relevant subset.

**Comment by goyney** [comment]
The dev site is under development. Things may or may not work at any time until it is released.

Use the main site or the browser extensions to browse and search.
