### ISSUE TITLE
volume-equal, volume-sync icon submission

### ISSUE THREAD

**Issue by ronschaeffer** [Templarian/MaterialDesign#6543]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

This icon represents setting the volume of two or more speakers to be equal or, put another way, to synchronize the volume setting among two or more speakers. The icon adopts the style of `volume-plus` and `volume-minus.`

A possible alias is `volume-sync`.

I use this icon in Home Assistant to trigger a script which sets the volume of all Sonos speakers in my house to the same level. It could also be used an indicator to show that two or more speakers are set to the same volume level.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/12379923/162393032-ea0e6cfd-f319-4cc2-8998-cc22a8bc269d.png)

### Upload the icon source.

[volume-equal.zip](https://github.com/Templarian/MaterialDesign/files/8449975/volume-equal.zip)

**Comment by goyney** [comment]
Could you get the equal signs to be on grid for us please, then we should be able to add it. Thanks!

**Comment by ronschaeffer** [comment]
Sure. Does this work?

![image](https://user-images.githubusercontent.com/12379923/163198045-92f91ff7-e348-4a46-ab4d-abd9ded084e0.png)

[volume-equal.zip](https://1drv.ms/u/s!AtYGFztGDGYlkq1fyWjvFSdRCgYJbQ?e=9EHczW)

**Comment by goyney** [comment]
[![volume-equal](https://materialdesignicons.com/icon/volume-equal)](https://materialdesignicons.com/icon/volume-equal)
