### ISSUE TITLE
trash-box icon

### ISSUE THREAD

**Issue by bimaaurasakti** [Templarian/MaterialDesign#6544]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This icon is used for data change actions. the edit icon is already available, namely (pencil-box), for a pair I suggest a new icon, namely (trash-box)

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/51233688/162415650-464838ca-4d13-4815-8bd9-d612660c8f38.png)

**Comment by andrejsharapov** [comment]
https://materialdesignicons.com/icon/trash-can
https://materialdesignicons.com/icon/delete-empty
https://materialdesignicons.com/icon/delete-empty

**Comment by Templarian** [comment]
We originally allowed `delete-circle` and `delete-circle-outline`.

I'm leaning toward us not adding these for trash. Not sure it even works for the `delete-*` size.

**Comment by goyney** [comment]
Agreed. Thanks for the suggestion and work, but we're going to pass on these for now.
