### ISSUE TITLE
Thermometer/thermostat auto mode

### ISSUE THREAD

**Issue by breti** [Templarian/MaterialDesign#6545]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

There are many icons to activate an automatic mode, e.g.

brightness-auto 
lightbulb-auto
fan-auto
flash-auto

But there is no icon for a thermostat in automatic mode, e.g. for the automatic programme of the heating. 

### Give us an example of what this icon might look like.

This could be, for example, a thermometer with an "A".

**Comment by nagyrobi** [comment]
+ with clock. Use case: thermostat runs based on schedule.

**Comment by goyney** [comment]
> +1 with clock. Use case: thermostat runs based on schedule.

Please open a new issue for a new request.

**Comment by breti** [comment]
I think it's the same thing, or at least very close.

**Comment by goyney** [comment]
It may be perceived as such, but something like thermometer-clock needs to be a new request just so we don't miss it.

**Comment by boehan** [comment]
I was not sure about the placement of the "A"
![grafik](https://user-images.githubusercontent.com/7279415/164899056-a4d47da2-eec5-4176-8cac-7e37000ff327.png)
![grafik](https://user-images.githubusercontent.com/7279415/164899265-c2c96b5e-61b5-410c-a96f-b08ae1c6cf85.png)

**Comment by nagyrobi** [comment]
I would use the same A which is on the corresponding fan icon, for example

**Comment by boehan** [comment]
> I would use the same A which is on the corresponding fan icon, for example

Thought about this as well, but as the `fan-auto` icon is the only one that is different so far and there is no need here for the smaller A, I decided against it.

**Comment by goyney** [comment]
[![thermometer-auto](https://materialdesignicons.com/icon/thermometer-auto)](https://materialdesignicons.com/icon/thermometer-auto)
