### ISSUE TITLE
printer-3d-off

### ISSUE THREAD

**Issue by IcanDivideBy0** [Templarian/MaterialDesign#6546]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I am building a tool to help with managing 3d printers farm

### Give us an example of what this icon might look like.

In the same fashion we currently have `printer` and `printer-off`, the `pinter-3d` icon could have an "off" version

**Comment by boehan** [comment]
![grafik](https://user-images.githubusercontent.com/7279415/163568160-8cd5471a-a6b4-4cf2-ad80-60cee00f9f2c.png)
[printer-3d-off.zip](https://github.com/Templarian/MaterialDesign/files/8495767/printer-3d-off.zip)

**Comment by goyney** [comment]
[![printer-3d-off](https://materialdesignicons.com/icon/printer-3d-off)](https://materialdesignicons.com/icon/printer-3d-off)
