### ISSUE TITLE
account-online / offline

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#6549]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I am doing CRM for a company and in many projects I see a small badge, somewhere under the avatar, which shows whether the employee is online or not. This is convenient, of course, but I would like to make it an appropriate icon without resorting to unnecessary tricks. 

Of course, I could use "account-on/off" icons, but they do not reflect the proper understanding of users.

I am very glad that already more than 10 icons I proposed have been released and are useful to people. I hope that and these will not remain useless and will find support.  :blush:

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/44722574/163456649-312962d9-aaf2-41b9-ba07-cc450bb97403.png)
![image](https://user-images.githubusercontent.com/44722574/163456667-c08b073f-d5a2-4d7d-b66a-17f40a74d031.png)
![image](https://user-images.githubusercontent.com/44722574/163456694-72f1b23c-5e90-41f5-8844-803fed16dadd.png)
![image](https://user-images.githubusercontent.com/44722574/163456717-74329e78-3c79-46f1-a4d4-85f46c6bbc00.png)

### Upload the icon source.

[account-online.zip](https://github.com/Templarian/MaterialDesign/files/8491572/account-online.zip)

**Comment by andrejsharapov** [comment]
fix position
![image](https://user-images.githubusercontent.com/44722574/163458934-5c8f1532-c1f4-4a6f-98bf-33275817547d.png)
![image](https://user-images.githubusercontent.com/44722574/163458941-00d43049-b010-4e21-8024-2dd69510bc1a.png)
![image](https://user-images.githubusercontent.com/44722574/163458960-a4e5773f-e83c-427f-b5d0-39daa7996c3d.png)
![image](https://user-images.githubusercontent.com/44722574/163458968-e722ddea-532e-4835-ad76-85b0f73c75e7.png)

[account-online.zip](https://github.com/Templarian/MaterialDesign/files/8491618/account-online.zip)

**Comment by goyney** [comment]
These would be considered the `-badge` modifiers. They need a full 2dp cutout. Also, we probably won't add an outlined circle.

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/163592704-060231f7-43be-4fc1-a545-7425bc097146.png)
![image](https://user-images.githubusercontent.com/44722574/163592725-297721c6-4185-4a77-ac2f-b2d0b41bff25.png)
[account-badge.zip](https://github.com/Templarian/MaterialDesign/files/8496848/account-badge.zip)

**Comment by Simran-B** [comment]
Shouldn't the user silhouette be centered so that this icon can be used as a set together with the base icon?

**Comment by andrejsharapov** [comment]
So you can write about any icon that has an addition to the main account icon. All of them are to some extent shifted to the left. If that suits you, here are a few options.
![___](https://user-images.githubusercontent.com/44722574/163665968-1d7dc83f-7d7e-47d4-9e61-0d86cc0a381a.png)

![image](https://user-images.githubusercontent.com/44722574/163665715-288a8956-d65a-43f9-8185-e06fddec5930.png)
![image](https://user-images.githubusercontent.com/44722574/163665717-3ec2c055-5633-40fe-965b-fc873ec21b37.png)
[account-badge.zip](https://github.com/Templarian/MaterialDesign/files/8499471/account-badge.zip)

![image](https://user-images.githubusercontent.com/44722574/163666060-9b716728-a0f2-496f-aca6-66a2e3d0aaca.png)
![image](https://user-images.githubusercontent.com/44722574/163666064-8667547d-9a4f-4b4c-a5e2-6d2ee1b50c4f.png)
[account-badge.zip](https://github.com/Templarian/MaterialDesign/files/8499478/account-badge.zip)

**Comment by goyney** [comment]
I think the point being that we won't add an outlined badge version, you'd want to go between a normal account and an account-badge icon for the states without shifting the base icon.

**Comment by goyney** [comment]
[![account-badge](https://materialdesignicons.com/icon/account-badge)](https://materialdesignicons.com/icon/account-badge)[![account-badge-outline](https://materialdesignicons.com/icon/account-badge-outline)](https://materialdesignicons.com/icon/account-badge-outline)

**Comment by andrejsharapov** [comment]
Sorry, but https://github.com/Templarian/MaterialDesign/issues/5937 :sweat_smile:
[account-badge ](https://materialdesignicons.com/icon/account-badge)
[account-badge-outline](https://materialdesignicons.com/icon/account-badge-outline)

And one more question. Could you link to github instead of twitter? https://github.com/andrejsharapov

**Comment by andrejsharapov** [comment]
@goyney one more question. Could you link to github instead of twitter? https://github.com/andrejsharapov

**Comment by goyney** [comment]
Attributions updated to the correct author.
