### ISSUE TITLE
Baby buggy / pram

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#655]
Harder than I supposed...
![buggy](https://cloud.githubusercontent.com/assets/1309249/9586944/1f7a5f8c-5020-11e5-9b98-f90521488961.png)
![buggy2](https://cloud.githubusercontent.com/assets/1309249/9586945/1f7c97d4-5020-11e5-954d-9b3398f22e5b.png)
![buggy3](https://cloud.githubusercontent.com/assets/1309249/9586946/1f7f6e96-5020-11e5-9b48-313942639520.png)
Opinions please!

**Comment by Sithdown** [comment]
I'd choose the 2nd one.

**Comment by Templarian** [comment]
Yea, the 2nd is the most material, but I agree it's a more difficult one to display in a material way.

**Comment by CoDEmanX** [comment]
Google created a nice one, it's part of v2.1.0 and tracked in #420:

https://design.google.com/icons/#ic_child_friendly

**Comment by Templarian** [comment]
[![baby-buggy](https://materialdesignicons.com/icon/baby-buggy)](https://materialdesignicons.com/icon/baby-buggy)
