### ISSUE TITLE
printer-3d-nozzle-off(-outline)

### ISSUE THREAD

**Issue by phcella** [Templarian/MaterialDesign#6550]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have buttons to do some actions on my 3d printer, and I just want a icon to represent nozzle off or just the nozzle.

### Give us an example of what this icon might look like.

My idea is use the mdi:printer-3d-nozzle-heat but without the heatwaves. Just something like this:
![Captura de tela 2022-04-16 102040](https://user-images.githubusercontent.com/20034679/163676527-89a0a154-3fef-444c-9771-9464606bd023.png)

**Comment by Templarian** [comment]
Could you use `printer-3d-nozzle`? The filament it there to make it more recognizable.

**Comment by Templarian** [comment]
But we could add a `printer-3d-nozzle-off` icon with the normal slash.

**Comment by goyney** [comment]
Yeah, we're going to use the `printer-3d-nozzle` as the base and add the `-off` variant following our established patterns. We'll create the solid and outlined versions.

**Comment by phcella** [comment]
Hi,
Sorry about the delay.
I like the idea. Can you send a sketch?

**Comment by goyney** [comment]
[![printer-3d-nozzle-off](https://materialdesignicons.com/icon/printer-3d-nozzle-off)](https://materialdesignicons.com/icon/printer-3d-nozzle-off)[![printer-3d-nozzle-off-outline](https://materialdesignicons.com/icon/printer-3d-nozzle-off-outline)](https://materialdesignicons.com/icon/printer-3d-nozzle-off-outline)
