### ISSUE TITLE
Fast Forward/Rewind with number 45

### ISSUE THREAD

**Issue by unsnet** [Templarian/MaterialDesign#6553]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I am creating toggles in home assistant for automations to switch on a device for either 15, 30, 45 or 60 mins.  These icons are perfect for the toggle switch, but there isn't a 45 icon. 

### Give us an example of what this icon might look like.

Same as attached but with 45 as the number
![fast-forward-60](https://user-images.githubusercontent.com/81271340/164170180-ffda1e39-5722-4f11-9432-aaf21aa710b9.png)

**Comment by goyney** [comment]
[![fast-forward-45](https://materialdesignicons.com/icon/fast-forward-45)](https://materialdesignicons.com/icon/fast-forward-45)[![rewind-45](https://materialdesignicons.com/icon/rewind-45)](https://materialdesignicons.com/icon/rewind-45)

Let this issue publicly state that we will not add any more numeric variations of this nature. 😄

**Comment by unsnet** [comment]
Amazing, thank you! Now if you could just do 55…. Ha ha :)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
