### ISSUE TITLE
+63 Icon

### ISSUE THREAD

**Issue by SteplerPaulo** [Templarian/MaterialDesign#6554]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

+63 icons for input group.

+63 icons for CSS framework input group like Bulma, Bootstrap, etc
 

### Give us an example of what this icon might look like.

![+63](https://user-images.githubusercontent.com/2784873/164616456-a5b33a4c-7a37-445d-a244-441e676aa99a.png)

**Comment by goyney** [comment]
This is too niche. Use our individual numeric icons to generate larger numbers.
