### ISSUE TITLE
FilterByDate

### ISSUE THREAD

**Issue by BastiFantasti83** [Templarian/MaterialDesign#656]
I need an Icon to Filter a List by creation date. Like a combination between a generic filter icon and a clock or so.

**Comment by Sithdown** [comment]
Proposal: ![filter-clock](https://cloud.githubusercontent.com/assets/430612/9716278/87a40dfe-5568-11e5-8162-a8e07684218a.png)

**Comment by JamesCoyle** [comment]
We don't use filter as a modifier and clock is used to represent time and not dates.

I feel like this could be conveyed by context. For example, using one of the calendar icons within a section of the UI that contains other filter controls.
