### ISSUE TITLE
Motorbike-off icon

### ISSUE THREAD

**Issue by philtempleton** [Templarian/MaterialDesign#6560]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would use this icon for presence status when the is not parked in the garage.

It would be terrific if this icon were to be introduced.

Thank you for your consideration.

### Give us an example of what this icon might look like.

mdi:motorbike with a line through it diagonally - similar to the icon: mdi:car-off

**Comment by goyney** [comment]
[![motorbike-off](https://materialdesignicons.com/icon/motorbike-off)](https://materialdesignicons.com/icon/motorbike-off)
