### ISSUE TITLE
thermostat-auto

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#6561]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

As suggested in #6545 

### Share a preview of your contribution.

Due to the size/form of the base thermostat icon, I prefer the "badge" that is used by `fan-auto`. But as the "A" differs from the other "auto" icons, I also prepared an alternative.
![grafik](https://user-images.githubusercontent.com/7279415/164903923-ea640b5c-922d-4e5f-a625-c8bc9d600807.png)
![grafik](https://user-images.githubusercontent.com/7279415/164904147-0cb8a97d-6854-42e9-be51-266067e44a30.png)

### Upload the icon source.

[thermostat-auto.zip](https://github.com/Templarian/MaterialDesign/files/8547056/thermostat-auto.zip)

**Comment by goyney** [comment]
[![thermostat-auto](https://materialdesignicons.com/icon/thermostat-auto)](https://materialdesignicons.com/icon/thermostat-auto)
