### ISSUE TITLE
waste-recycle and waste-organic

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#6563]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Icons for different types of waste (recycling, organic), e.g., to use for garbage collection calendars.

### Share a preview of your contribution.

![grafik](https://user-images.githubusercontent.com/7279415/164911447-9394b24f-5a24-4ed2-adfd-6c86d0d5896c.png)
![grafik](https://user-images.githubusercontent.com/7279415/164911463-29f8fdec-d3fb-4001-a087-0c16a6ae82dd.png)
![grafik](https://user-images.githubusercontent.com/7279415/164911477-b22bbcf6-4310-47ae-9bb1-1e6213943b83.png)
![grafik](https://user-images.githubusercontent.com/7279415/164911489-aa035f28-2f50-4631-8dc8-c5b344f78908.png)

### Upload the icon source.

[waste.zip](https://github.com/Templarian/MaterialDesign/files/8547452/waste.zip)

**Comment by goyney** [comment]
The arrows of the recycle symbol are completely lost at native resolution. The leafs are way to big inside of their bases.

Personally, I don't like the idea of putting modifiers in middle of the base icons. It's a trend we're trying to move away from. Perhaps `sync` variants of the trash can could work. I'm not sure how to handle the other use case.

**Comment by boehan** [comment]
I tend to agree. The longer I look at them, the less I like them myself. Additionally, there are a lot more potential icons in terms of garbage collection. Therefore, it is probably easier and enough to use the original icons (`recycle`, `leaf`) with appropriate context. At least for me, this would probably fit my needs, thus, I leave it to you to close this.

**Comment by goyney** [comment]
Going to pass on these for now. If someone wants to take another stab at them, feel free to add your attempts to this issue and we'll reopen to reconsider.
