### ISSUE TITLE
Remove Discord icon

### ISSUE THREAD

**Issue by srabouin** [Templarian/MaterialDesign#6564]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

The current icon does not match the brand icon.

You can find the updated brand icon here: https://discord.com/branding

The logo was updated in May 2021, you can see their tweet about it here: https://twitter.com/discord/status/1392857573481586690

**Comment by goyney** [comment]
The Discord icon should probably be deprecated and removed in 7, following our brand guidelines. It does not align with the development related tools clause we have. Additionally, this icon is available in the Simple Icons library.

**Comment by goyney** [comment]
We've decided to deprecate and remove this icon in our next major version. Please use [SimpleIcons][2] to continue using this glyph.

[2]: https://simpleicons.org/

**Comment by goyney** [comment]
Removed.

**Comment by vermillion-excl** [comment]
I do find it strange that the decision was made to remove the Discord logo while keeping other brands that are not related to this project. What makes Facebook/Instagram/YouTube social media icons different from the Discord one?

**Comment by goyney** [comment]
They're all going. See #6602.

**Comment by vermillion-excl** [comment]
> 

Thank you, that clarifies it.
