### ISSUE TITLE
Prescription Pill Container

### ISSUE THREAD

**Issue by greghuntoon** [Templarian/MaterialDesign#6565]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I work for a compliance software company and we need to showcase when elements in an image trigger a compliance issue. Prescription pill containers, marijuana leaves, bongs, water pipes, etc., all trigger issues.

### Give us an example of what this icon might look like.

![prescription-16](https://user-images.githubusercontent.com/1495812/165355848-4941bc15-f54b-4e84-8b51-15090ce3337f.png)

**Comment by greghuntoon** [comment]
And, hopefully, this will be available in filled style...

**Comment by goyney** [comment]
[![medication](https://materialdesignicons.com/icon/medication)](https://materialdesignicons.com/icon/medication)[![medication-outline](https://materialdesignicons.com/icon/medication-outline)](https://materialdesignicons.com/icon/medication-outline)
