### ISSUE TITLE
yield-sign

### ISSUE THREAD

**Issue by djm228** [Templarian/MaterialDesign#6567]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I created a yield sign to go along with other warning signs.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/56743122/165383774-42e4e62a-141a-4f02-8e34-b28eb514cc37.png)

### Upload the icon source.

[yield-sign.zip](https://github.com/Templarian/MaterialDesign/files/8566551/yield-sign.zip)

**Comment by goyney** [comment]
We could add the basic triangle shape, but absolutely not with any text on it.
