### ISSUE TITLE
Icon Request: NestJS

### ISSUE THREAD

**Issue by carrotfarmer** [Templarian/MaterialDesign#6568]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

It can be used like how the Language (and node.js) Icons are used

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/66675022/165463241-89596495-d768-4595-82cf-74eb7f6f8e08.png)
![image](https://user-images.githubusercontent.com/66675022/165463298-7dc68333-c89d-41b1-adef-64784b645ac5.png)

**Comment by goyney** [comment]
We _might_ add this, but that is a big might. We're organizing a brand specific icon library, but it's far from ready. [This icon is available in SimpleIcons.](https://simpleicons.org/?q=nestjs) In the short-term, you should use it from there.

**Comment by goyney** [comment]
We're going to pass on this for now as we are beginning work on our Brand Icon pack. I'd hate for us to add it for a few releases and then remove it right away. Look out for more information about our pack soon, but in the meantime, use SimpleIcons.
