### ISSUE TITLE
Icon Request: Personal Hotspot

### ISSUE THREAD

**Issue by Datytguy13** [Templarian/MaterialDesign#6569]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

It can be used for sharing a hotspot to someone else

### Give us an example of what this icon might look like.

![personal-hotspot-icon](https://user-images.githubusercontent.com/24432130/165496628-0a1340ee-579f-4a42-8878-4ddfce7bec81.jpg)
![ios12-control-center-hotspot-icon](https://user-images.githubusercontent.com/24432130/165496707-ac79dadf-6805-4ae2-ade6-abb9ff76dc30.png)

**Comment by goyney** [comment]
That is an iOS specific icon that has no real meaning besides the context they give it. We already have two chain-link type icons: `link` and `link-variant`, the latter being very similar to this, just rotated. I would suggest using that one.
