### ISSUE TITLE
Editing off / writing locked (based on pencil)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#657]
![pencil-lock](https://cloud.githubusercontent.com/assets/1309249/9612625/fbd511b8-50e6-11e5-8234-5dc2ad00e69c.png) https://www.dropbox.com/s/8ho0laokigkic9z/pencil-lock.svg?dl=0
![pencil-off](https://cloud.githubusercontent.com/assets/1309249/9612626/fbd87510-50e6-11e5-9949-e8bf91236eb9.png) https://www.dropbox.com/s/o2e3n9tethsydjz/pencil-off.svg?dl=0

**Comment by Templarian** [comment]
[![pencil-lock](https://materialdesignicons.com/icon/pencil-lock)](https://materialdesignicons.com/icon/pencil-lock) [![pencil-off](https://materialdesignicons.com/icon/pencil-off)](https://materialdesignicons.com/icon/pencil-off)
