### ISSUE TITLE
Artboard

### ISSUE THREAD

**Issue by SintijaPotaicuka** [Templarian/MaterialDesign#6570]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Icon for "Artboard"

Inspiration: 
![image](https://user-images.githubusercontent.com/102287459/165745601-b7709256-374a-474b-9aad-fdc431cd6614.png)

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/102287459/165747200-576f05b6-7a04-4d5b-97ed-1446cdaca74e.png)

### Upload the icon source.

[artboard.svg.zip](https://github.com/Templarian/MaterialDesign/files/8582477/artboard.svg.zip)

**Comment by SintijaPotaicuka** [comment]
Alternative with 1px space:
![image](https://user-images.githubusercontent.com/102287459/165747560-5567718f-824b-4728-a9d3-02eaa51444d4.png)

[artboard1px.svg.zip](https://github.com/Templarian/MaterialDesign/files/8582488/artboard1px.svg.zip)

**Comment by goyney** [comment]
[![artboard](https://materialdesignicons.com/icon/artboard)](https://materialdesignicons.com/icon/artboard)
