### ISSUE TITLE
Make GitHub link a link, not a button

### ISSUE THREAD

**Issue by OnkelTem** [Templarian/MaterialDesign#6572]
### What is your question?

Hi!

Thank you for the great icon database. I used it many times in the past but today I couldn't use it: I waited for like 10 minutes for the initial screen to load and then gave up.

While waiting, I tried to left-click the GitHub link, but instead of opening GitHub in a new tab, **it just interrupted the downloading process and replaced the page.**

Right-clicking the link didn't bring the regular browser context menu for a link, which means it's not a link.

Please make it a link. While you're making a new website at least.

**Comment by goyney** [comment]
The new website will do things better. Please follow: https://github.com/Templarian/MaterialDesign/issues/5161

**Comment by OnkelTem** [comment]
Cool! Thanks @goyney
