### ISSUE TITLE
Add the science icon from the official Material Icons Library

### ISSUE THREAD

**Issue by maximiliancs** [Templarian/MaterialDesign#6573]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This icon could be used in context of experimental features or simply just science.

### Give us an example of what this icon might look like.

There already is a perfectly fine icon by Google in their official Material Icons Library:
https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Ascience

![science_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/18228028/165909156-31d317ad-20de-4153-a19a-88a811e7803f.png)

This should be available as filled and with an outline.

**Comment by Templarian** [comment]
Already exists `flask-empty-outline` (with several styles).
