### ISSUE TITLE
Alias for or rename `loupe`. Took me about 1 hr to find this as it has no aliases

### ISSUE THREAD

**Issue by nagyrobi** [Templarian/MaterialDesign#6574]
### What icon would you like to alias?

loupe

### What alias(es) should be added to the above icon?

plus circle zoom corner increase positive magnify

**Comment by Templarian** [comment]
Oh, that's an odd name we got from Google. Maybe it might be worth renaming it in 7.x 🙃 

Had to look up the word.

**Comment by nagyrobi** [comment]
yeah

**Comment by goyney** [comment]
A loupe is a loupe, other aliases added to help find it.
