### ISSUE TITLE
Modifications on `monitor-speaker(-off)`

### ISSUE THREAD

**Issue by boehan** [Templarian/MaterialDesign#6576]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

General entertainment devices

### Give us an example of what this icon might look like.

The current `monitor-speaker` icons break some material design rules (cutout, corner radius, etc.), which I tried to improve a bit. Furthermore, I personally would prefer a `television-speaker` icon, but as the differences are pretty small, adding both would probably be a bit overkill...
![grafik](https://user-images.githubusercontent.com/7279415/166156983-abe8bc6a-3171-4a65-9f6b-30a10ba496fa.png)
![grafik](https://user-images.githubusercontent.com/7279415/166156989-55afc16d-64f2-44b9-926b-e1a9e2de9085.png)
![grafik](https://user-images.githubusercontent.com/7279415/166156994-8c90697e-917f-4086-8be9-eb305dda6765.png)
![grafik](https://user-images.githubusercontent.com/7279415/166157000-9c8552aa-4db3-4878-b96f-9d734e4e96ad.png)
[mdi.zip](https://github.com/Templarian/MaterialDesign/files/8599391/mdi.zip)

**Comment by Templarian** [comment]
Marking this one as a bug. Good find @boehan

**Comment by goyney** [comment]
Updated and added.
[![television-speaker](https://materialdesignicons.com/icon/television-speaker)](https://materialdesignicons.com/icon/television-speaker)[![television-speaker-off](https://materialdesignicons.com/icon/television-speaker-off)](https://materialdesignicons.com/icon/television-speaker-off)
