### ISSUE TITLE
image filter icon like movie-filter

### ISSUE THREAD

**Issue by rodrigoaraujolima92trulogic** [Templarian/MaterialDesign#6578]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Edition image effects

### Give us an example of what this icon might look like.

Menu photo filters program web

**Comment by goyney** [comment]
Alias added to `image-auto-adjust`.

[![image-auto-adjust](https://materialdesignicons.com/icon/image-auto-adjust)](https://materialdesignicons.com/icon/image-auto-adjust)
