### ISSUE TITLE
Bloglovin icon

### ISSUE THREAD

**Issue by oysteinmyrmo** [Templarian/MaterialDesign#658]
I am looking for a Bloglovin icon. Their offical icon download package is found [here](http://www.bloglovin.com/files/Icon.zip), but the icons are only black. The SVGs can not be opened in Inkscape out of the box.

Keep up the great work!

**Comment by Templarian** [comment]
Sorry, but icons must fall into social media related category. We're starting to work through retroactively to make this policy consistent throughout the pack.

**Comment by CoDEmanX** [comment]
I can open them just fine in InkScape...
I re-saved them and uploaded here: https://www.dropbox.com/s/wxemou6wzcl4x08/bloglovin.zip?dl=0
Maybe works now for you?

**Comment by oysteinmyrmo** [comment]
Yes, they work fine now, dunno what the problem was. I'll stick with them then. Cheers!
