### ISSUE TITLE
alert-outline-flash

### ISSUE THREAD

**Issue by tetzla** [Templarian/MaterialDesign#6580]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I'm suggesting a high voltage icon (= combination of alert and flash).

### Share a preview of your contribution.

![grafik](https://user-images.githubusercontent.com/81367382/167099917-ddd8c7d5-a52f-41bf-ba7e-deecffb105f2.png)

### Upload the icon source.

[alert-outline-flash.zip](https://github.com/Templarian/MaterialDesign/files/8638766/alert-outline-flash.zip)

**Comment by goyney** [comment]
[![flash-triangle](https://materialdesignicons.com/icon/flash-triangle)](https://materialdesignicons.com/icon/flash-triangle)[![flash-triangle-outline](https://materialdesignicons.com/icon/flash-triangle-outline)](https://materialdesignicons.com/icon/flash-triangle-outline)
