### ISSUE TITLE
Image Check suggestion

### ISSUE THREAD

**Issue by dom-velloso** [Templarian/MaterialDesign#6581]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Button to upload and validate an image/video.

### Give us an example of what this icon might look like.

It could be a simple combination of the image icon and the check icon, similar to the movie-check icon (+ the outline variation).

**Comment by andrejsharapov** [comment]
Maybe this will suit you

![image](https://user-images.githubusercontent.com/44722574/169596112-f4b0d13c-9c30-4fdb-9d5e-84d5b087a50f.png) ![image](https://user-images.githubusercontent.com/44722574/169596186-fd3d2977-48df-4e14-8264-2de3a19e049c.png)

[image-check.zip](https://github.com/Templarian/MaterialDesign/files/8743525/image-check.zip)

**Comment by goyney** [comment]
[![image-check](https://materialdesignicons.com/icon/image-check)](https://materialdesignicons.com/icon/image-check)[![image-check-outline](https://materialdesignicons.com/icon/image-check-outline)](https://materialdesignicons.com/icon/image-check-outline)
