### ISSUE TITLE
Candelabra off

### ISSUE THREAD

**Issue by wrt54g** [Templarian/MaterialDesign#6582]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have IR candles automated with a cheap IR transmitter. I can use the icon for the automation to turn them off

### Give us an example of what this icon might look like.

An off icon for the existing Candelabra,

**Comment by goyney** [comment]
Technically, we already have this. `candelabra` is the off version and `candelabra-fire` is the on version. Does that not work for your use case?

[![candelabra](https://materialdesignicons.com/icon/candelabra)](https://materialdesignicons.com/icon/candelabra)[![candelabra-fire](https://materialdesignicons.com/icon/candelabra-fire)](https://materialdesignicons.com/icon/candelabra-fire)
