### ISSUE TITLE
phone-incoming-outgoing

### ISSUE THREAD

**Issue by dzuendorf** [Templarian/MaterialDesign#6583]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For example for a callcenter which handles both incoming and outgoing calls.

### Give us an example of what this icon might look like.

<img width="128" alt="phone-incoming-outgoing" src="https://user-images.githubusercontent.com/11569530/167353998-dc9e82d8-3d76-40c4-88e4-8ee3fae3bf3d.png">

**Comment by goyney** [comment]
I think these are okay, but want to get feedback from the contributors before adding them.
![image](https://user-images.githubusercontent.com/1015040/168722420-1db5eb24-9813-44c1-a67f-1d2bd7a1aade.png)![image](https://user-images.githubusercontent.com/1015040/168722457-d5bea585-b2e6-471f-bdf8-48464e683f2c.png)
[Archive.zip](https://github.com/Templarian/MaterialDesign/files/8704857/Archive.zip)

**Comment by goyney** [comment]
[![phone-incoming-outgoing](https://materialdesignicons.com/icon/phone-incoming-outgoing)](https://materialdesignicons.com/icon/phone-incoming-outgoing)[![phone-incoming-outgoing-outline](https://materialdesignicons.com/icon/phone-incoming-outgoing-outline)](https://materialdesignicons.com/icon/phone-incoming-outgoing-outline)
