### ISSUE TITLE
calendar-filter

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#6585]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

On a page where there are a lot of elements related to time, date and filters, a single calendar icon is not enough to accurately indicate filtering by date, so a calendar with a filter would be very useful.

### Share a preview of your contribution.

v1
![image](https://user-images.githubusercontent.com/44722574/167923257-415e1843-99ed-4107-9064-82de63ee6df6.png)
![image](https://user-images.githubusercontent.com/44722574/167923278-8dc38a6d-b698-452d-b57c-5b43f3c3b8db.png)

I took the `calendar` icon as a basis, the icons turned out higher, but I noticed that on some options the indentation from the bottom corner is different, so there are 3 options.

v2
![image](https://user-images.githubusercontent.com/44722574/167925739-ba6b5ab7-a0a6-4950-8402-01378148e5b6.png)
![image](https://user-images.githubusercontent.com/44722574/167925713-6a36aab4-dde3-4b48-9183-0633120ea8f2.png)

v3
![image](https://user-images.githubusercontent.com/44722574/167926210-d23680a7-71bd-43e1-934b-f72d1d31129c.png)
![image](https://user-images.githubusercontent.com/44722574/167926178-78d6e90a-df06-4e66-b059-5180689dc948.png)

### Upload the icon source.

[calendar-filter.zip](https://github.com/Templarian/MaterialDesign/files/8672746/calendar-filter.zip)

**Comment by Templarian** [comment]
Using v2 to fix an issue in the 6.7.96 release. 👍

(will fix up any attribution issues after I get this release out)

**Comment by goyney** [comment]
Attributions updated.

**Comment by andrejsharapov** [comment]
I noticed an error in the `calendar-filter-outline` icon. It is shifted 1dp to the left of all other calendar icons.

And you can also raise `calendar-lock` 1dp higher to align it with others.

![20220524_103638.jpg](https://user-images.githubusercontent.com/44722574/169975387-339f0587-38d2-4529-8bf6-615021a06e67.jpg)

**Comment by goyney** [comment]
Thanks, those have been updated.
