### ISSUE TITLE
Sign Language

### ISSUE THREAD

**Issue by five1** [Templarian/MaterialDesign#6587]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This icon would be used to signfy that a video contains sign language. I imagine the icon showing two hands crossed over each other signing a common sign language symbol (sorry I do not know sign language so can't suggest a sign to use - is there a sign for "sign language"). Note that there are many sign languages that exist in the world. It needs to be somewhat generic. It would be good to consult several signers to determine an appropriate hand gesture to use.

### Give us an example of what this icon might look like.

It could be similar to the style of the [hand-clap icon](https://materialdesignicons.com/icon/hand-clap). But with the hands crossed in some way and the fingers forming a symbol (perhaps the letter A or the sign for "sign language" if it exists).

**Comment by goyney** [comment]
I believe `hand-clap` is going to be your best bet. It was already difficult enough fitting two hands in one glyph for that icon. There are also a wide variety of other hand-type icons. Used in the correct context, many of them could signify sign language.

**Comment by five1** [comment]
Since submitting my request I have consulted some contacts I have from the deaf community. They recommend an icon like the one attached.
![sign language icon cropped screenshot](https://user-images.githubusercontent.com/7004707/168738060-2f097fad-6988-4b44-a31f-bd7180256ecc.png)

I think `hand-clap` with the far hand rotated to point up would be better.

**Comment by five1** [comment]
My deaf contacts have also mentioned the following icons as being other good examples:
https://icons-for-free.com/sign+language-1326548866373388591/
https://www.shutterstock.com/image-vector/sign-language-icondisabled-icon-web-application-441630703

**Comment by goyney** [comment]
The problem with most of these is that we have limited artboard space and two very large, complex items that are required to make this glyph, while still keeping its intended meaning very apparent.

Can you show them this and get some feedback please? I want to make sure it's acceptable by the deaf community so it works as you intend it to.

![image](https://user-images.githubusercontent.com/1015040/170122592-0c0c71e6-15c5-4119-82c4-bba864c35bcf.png)
[hand-sign-language.svg.zip](https://github.com/Templarian/MaterialDesign/files/8765879/hand-sign-language.svg.zip)

**Comment by goyney** [comment]
[![sign-language](https://materialdesignicons.com/icon/sign-language)](https://materialdesignicons.com/icon/sign-language)[![sign-language-outline](https://materialdesignicons.com/icon/sign-language-outline)](https://materialdesignicons.com/icon/sign-language-outline)

**Comment by five1** [comment]
Thank you @goyney!
