### ISSUE TITLE
Multiple Spoken Languages

### ISSUE THREAD

**Issue by five1** [Templarian/MaterialDesign#6588]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Signify that an audio program contains multiple spoken languages. There is an existing icon for multiple languages/translations, however I feel that it is too written language centric. I would like to see an icon produced that can be used to show multiple spoken languages.

### Give us an example of what this icon might look like.

The attached icon is similar to the [icon for translate](https://materialdesignicons.com/icon/translate), but uses speech bubbles to signify speech.
![ic_mixed_language_32dp](https://user-images.githubusercontent.com/7004707/167983476-362c4c95-e338-49fb-8fb1-e377e7e93879.png)

**Comment by goyney** [comment]
We can't fit two chat bubbles in a single icon like your suggestion. The best we might be able to do is encapsulate the existing `translate` icon into a chat bubble of some kind, though it may still be tricky due to the complexity of the icon.

**Comment by Circeus** [comment]
Alternatively, can a chat bubble be fitted as a pseudo-modifier in the corner?

**Comment by five1** [comment]
> We can't fit two chat bubbles in a single icon like your suggestion. The best we might be able to do is encapsulate the existing `translate` icon into a chat bubble of some kind, though it may still be tricky due to the complexity of the icon.

If you encapsulate the existing `translate` icon into a chat bubble then it could be good to have two or more points (tails) to indicate multiple voices, but I understand the complexities of acheiving that. We would not be trying to signify a conversation. A conversation with each party speaking a different language would not make much sense. However we want to convey a spoken message containing multiple languages. One language might be a trade language, while the other language is the local language spoken by the inhabitants of a region.

The material design chat bubbles with square corners appear to denote text chat, whereas the round chat bubbles denote verbal chat. We would want to denote verbal chat in this case.

**Comment by five1** [comment]
> Alternatively, can a chat bubble be fitted as a pseudo-modifier in the corner?

Possibly, however the icon is not meant to convey oral translation, which would be my immediate interpretation of such an icon.

**Comment by andrejsharapov** [comment]
What you want may look like this, but you must understand that the characters are almost invisible

![image](https://user-images.githubusercontent.com/44722574/169578904-2ae64d1c-ea42-4615-b0fc-005d112fa732.png)

**Comment by goyney** [comment]
Yeah, that won't work in that form. We'll need to play around with some ideas to get a few options that might work.

**Comment by goyney** [comment]
This breaks some rules, but is much more legible.

![image](https://user-images.githubusercontent.com/1015040/170119962-112f1088-db94-47a6-ac33-35869bb9d98b.png)
[translate-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/8765790/translate-variant.svg.zip)

**Comment by five1** [comment]
Thanks @goyney, I think that will work.

**Comment by andrejsharapov** [comment]
@goyney, It seems to me that it is possible to replace the hieroglyph with a simpler one, so as not to violate the principle of the library. 🤔

**Comment by goyney** [comment]
> @goyney, It seems to me that it is possible to replace the hieroglyph with a simpler one, so as not to violate the principle of the library. 🤔

It's the one that's used in the other translate icons, so it might be better to retain consistency.

**Comment by five1** [comment]
> @goyney, It seems to me that it is possible to replace the hieroglyph with a simpler one, so as not to violate the principle of the library. 🤔

The hieroglyph is the Chinese character for "language". As far as Chinese characters are concerned, I think this hieroglyph is one of the simplest. In terms of meaning "[语](https://translate.google.com/?sl=zh-CN&tl=en&text=%E8%AF%AD&op=translate)" (spoken language) might be more appropriate, however it is more complicated and is not consistent with other icons. Note that I do not speak or read Chinese, so I could be wrong in my understanding of Chinese characters and their meaning. My source was [Google Translate](https://translate.google.com/?sl=zh-CN&tl=en&text=%E8%AF%AD&op=translate).

**Comment by goyney** [comment]
[![translate-variant](https://materialdesignicons.com/icon/translate-variant)](https://materialdesignicons.com/icon/translate-variant)
