### ISSUE TITLE
Chef's Hat

### ISSUE THREAD

**Issue by oysteinmyrmo** [Templarian/MaterialDesign#659]
I am looking for one or more icons for difficulty, more specifically recipe/cooking difficulty. This can be solved in many ways, for example by having multiple icons with filled and non-filled parts. If the difficulty is 1/3, one of the outlined difficulty parts is filled, 2/3 are filled for difficulty 2, etc. Various other options are also possible, but it might be hard to express "difficulty level" through an icon.

**Comment by CoDEmanX** [comment]
In text, "3 out of 5" works better than "0.6" or "6%". Applied to icons, multiple times the same icon works probably better than one icon at different "fill levels". To indicate the maximum number, an outlined version of the icon can be used. Like this:

![Imgur](http://i.imgur.com/HOtkSxL.jpg)

Some use an additinal half-filled icon to allow for 3.5 out of 5.0 points (3 full stars + 1 half-filled, half-outlined star + 1 outlined star).

For recipe difficulty, a chef hat would probably work. 1x easy, 5x hard. For intance:

![Imgur](http://i.imgur.com/KFnecpa.png?1)

A cooking spoon would also work, but doesn't express the "difficulty" part quite right. It could be misinterpreted in the time it takes to prepare the described meal.

**Comment by oysteinmyrmo** [comment]
Yes, thank you, the chef hat would work perfectly, either as a count for difficulty or as number of filled hats in some way.

I am new to this site, so please forgive my ignorance, but is it expected for me to create icons based on the suggestions and upload them or will some of the contributors create the icon in the proper format(s)? Either way would work for me, but I suspect that others will make better icons then me, even with the template you provided. Maybe a few lines of guidance on this could be added to the README.md?

**Comment by CoDEmanX** [comment]
You can contribute your own icons, but you can also just ask for icons and hope that someone create one.

Here's my take at a chef hat:
![chat-hat](https://cloud.githubusercontent.com/assets/1309249/9669211/12b399f4-5286-11e5-9c70-89a34da5695e.png) https://www.dropbox.com/s/rqcx6kbi6xfmct9/chat-hat.svg?dl=0

**Comment by CoDEmanX** [comment]
.design file of above attempt:

[chef-hat.zip](https://github.com/Templarian/MaterialDesign/files/1804860/chef-hat.zip)

**Comment by CoDEmanX** [comment]
Seen this in an app:

![grafik](https://user-images.githubusercontent.com/1309249/38705351-94fc3076-3ea9-11e8-9eda-6a59b49f73d8.png)

Had to make it a bit wider to accomodate the 3 vertical counter strokes. Although, one could also make it 2px thinner...

![grafik](https://user-images.githubusercontent.com/1309249/38705292-60219a62-3ea9-11e8-887e-ca0700de5c12.png)

Download: [chef-hat-experimental2.zip](https://github.com/Templarian/MaterialDesign/files/1905071/chef-hat-experimental2.zip)

**Comment by PeterShaggyNoble** [comment]
[![chef-hat](http://mdi.houseofdesign.ie/tools/preview/?icon=chef-hat&action=link)](https://www.materialdesignicons.com/icon/chef-hat)
