### ISSUE TITLE
desk-lamp-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#6590]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

some while ago https://github.com/Templarian/MaterialDesign/issues/3057#issuecomment-390415698 was closed, and using it gladly.
However, the -off variant never made it, and I am not sure that was simply overlooked, or on purpose.

Would appreciate the regular -off variant (with the diagonal line) most certainly

thanks for considering!

### Give us an example of what this icon might look like.

from the old post:

<img width="686" alt="Schermafbeelding 2022-05-13 om 11 49 15" src="https://user-images.githubusercontent.com/33354141/168258627-711bce54-1344-4baa-a6a6-a9db09371ed9.png">

**Comment by goyney** [comment]
[![desk-lamp-off](https://materialdesignicons.com/icon/desk-lamp-off)](https://materialdesignicons.com/icon/desk-lamp-off)[![desk-lamp-on](https://materialdesignicons.com/icon/desk-lamp-on)](https://materialdesignicons.com/icon/desk-lamp-on)
