### ISSUE TITLE
When will version 6.7.96 be released?

### ISSUE THREAD

**Issue by PashaTurok** [Templarian/MaterialDesign#6592]
### What is your question?

According to the information [here](https://github.com/Templarian/MaterialDesign/milestones) version 6.7.96 is 100% complete and hasn't been modified for two months. All these two months I've been waiting for one icon that was added. I searched, but didn't find any roadmap with dates. Could anyone say when this version will be released?

**Comment by goyney** [comment]
When we release it. A technical issue has been holding things up.

**Comment by PashaTurok** [comment]
@goyney  Thank you for your answer, although I think you understand that `When we release it` is not of type of respectful answer and not the answer I waited.
