### ISSUE TITLE
Save and Add New Record

### ISSUE THREAD

**Issue by shanebovisync** [Templarian/MaterialDesign#6595]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The icon would be used for the action of saving and adding another. It differs from the standard "content-save" in that it also includes the action of directing to add the next record immediately after the save of the current one.

The design idea would be the "disk" icon used in the content-save icon with a + icon small on the lower right corner.

### Give us an example of what this icon might look like.

A user may be entering many instances of the same type of record in a form.  This icon would represent the option to "Save and Add Another Record"

**Comment by boehan** [comment]
Like this?
![grafik](https://user-images.githubusercontent.com/7279415/169645785-dbdfbeb8-d05b-46f8-ad5f-ab55d79eeedf.png)
added `outline` and `minus` versions as well:
![grafik](https://user-images.githubusercontent.com/7279415/169645828-a207f32d-fe56-4bfc-a7fc-b9675983037d.png)
![grafik](https://user-images.githubusercontent.com/7279415/169645839-2ec6fefe-2739-442f-846c-927c29ec9654.png)
![grafik](https://user-images.githubusercontent.com/7279415/169645841-ca2efef6-e12c-435f-8a63-a369d8f3d304.png)
[content-save.zip](https://github.com/Templarian/MaterialDesign/files/8747349/content-save.zip)

**Comment by shanebovisync** [comment]
Yes, those look exactly like what I was suggesting!

**Comment by goyney** [comment]
[![content-save-plus](https://materialdesignicons.com/icon/content-save-plus)](https://materialdesignicons.com/icon/content-save-plus)[![content-save-plus-outline](https://materialdesignicons.com/icon/content-save-plus-outline)](https://materialdesignicons.com/icon/content-save-plus-outline)
[![content-save-minus](https://materialdesignicons.com/icon/content-save-minus)](https://materialdesignicons.com/icon/content-save-minus)[![content-save-minus-outline](https://materialdesignicons.com/icon/content-save-minus-outline)](https://materialdesignicons.com/icon/content-save-minus-outline)
