### ISSUE TITLE
pump-off

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#6596]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

plase consider as title, to accompany the nice mdi:pump

use-case:
replacing the (rotating when on) engine/-off icons in  settings where a true pump is used, like in these Pond cards:

<img width="472" alt="Schermafbeelding 2022-05-19 om 12 59 16" src="https://user-images.githubusercontent.com/33354141/169278460-6512ec11-9d8e-42b5-8d43-90b912ef9a98.png">

thanks for considering

### Give us an example of what this icon might look like.

Pump is a better visual representation:

<img width="457" alt="Schermafbeelding 2022-05-19 om 12 59 22" src="https://user-images.githubusercontent.com/33354141/169278558-1e1113c7-8504-4fb2-9405-7893c2811b87.png">

and the usual diagonal line would fit the bill perfectly ;-)

**Comment by goyney** [comment]
[![pump-off](https://materialdesignicons.com/icon/pump-off)](https://materialdesignicons.com/icon/pump-off)
