### ISSUE TITLE
white-balance-sunny is not centered

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#6597]
### Where are you experiencing this bug?

Somewhere else

### What is the issue you are experiencing?

just posting this as a preliminary quest for perfect centered icons.

As it happens in Homeassistant we use css animation on the icons via plugin called card_mod.

a lot of mdi icons are centered nicely, some though are not while one would expect the form factor to indicate so. like weather-sunny.

I am aware this is part of a larger family of weather icons, but the -sunny being so symmetrical, feels 'buggy' because of that. 

compared to the circle family icons:

![b0ab588b8a24cf34f5f056c7a4f420213bf877ef](https://user-images.githubusercontent.com/33354141/169297879-bf5798b0-a881-4a8c-abfc-398502457548.gif)

made by @Ildar_Gabdullin in https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744/3179

please have a look if this is an issue you can sympathize with?
thanks!

**Comment by goyney** [comment]
`weather-sunny` definitely is centered:
[![weather-sunny](https://materialdesignicons.com/icon/weather-sunny)](https://materialdesignicons.com/icon/weather-sunny)

But `white-balance-sunny`, which is what is in your preview, is not:
[![white-balance-sunny](https://materialdesignicons.com/icon/white-balance-sunny)](https://materialdesignicons.com/icon/white-balance-sunny)

**Comment by goyney** [comment]
It's fixed. Won't make it until the 6.9 release.

![image](https://user-images.githubusercontent.com/1015040/169303932-f11196f2-7028-4eec-a193-66ee17d2430c.png)

**Comment by Mariusthvdb** [comment]
magic. thank you very much!

**Comment by Mariusthvdb** [comment]
as a followup please this: where can we check these icon file designs, like you posted above, with the grid-lines behind them? Asking because several more icons show this:

![May-20-2022 10-01-35](https://user-images.githubusercontent.com/33354141/169482928-3dd6d0d9-c47d-46d1-b561-921a323701b1.gif)

And I like to pinpoint it correctly: is it the icon, or is it some css issue in HA core.

**Comment by goyney** [comment]
Pump is perfectly aligned to the grid.
`[![pump](https://materialdesignicons.com/icon/pump)](https://materialdesignicons.com/icon/pump)`
[![pump](https://materialdesignicons.com/icon/pump)](https://materialdesignicons.com/icon/pump)

**Comment by Simran-B** [comment]
The icons are generally designed to be visually centered. In some cases, the base icon is shifted to make room for a modifier, so that the icon is recognizable and still fits on the canvas. The icons are not designed to rotate around what would be the most meaningful center based on what's depicted. For many icons, it would not even be possible to shift them so that the ideal center is at the canvas center due to the constraints of the canvas and material design guidelines, in particular the grid alignment for pixel-perfect shapes.

If you want icons to visually rotate around their semantically correct center, then determine this center and use it as rotation axis instead of the geometric canvas center. Note that this center can be off-grid.

**Comment by Mariusthvdb** [comment]
Thanks. Aware not all icons are suited for rotating effects. Ofc. But those that are, like above, and many other circular icons, should not be positioned off center in Ha. 

Somehow there are other issues at hand that cause that to happen , and I hope to select a few of those to create a working test setup for further analysis. 

The issues also seem to differ between browsers and/or desktop vs mobile. 

Ruling out icon issue by using these pixel perfect icons is really helpful and a first step in the process.

anyways, thanks for chiming in. I’ll will try to do as you suggest, because currently I wouldn’t know how (-)
