### ISSUE TITLE
Add package.json and publish to NPM

### ISSUE THREAD

**Issue by vanthome** [Templarian/MaterialDesign#66]
NPM is also used quite a lot as package manager for frontend development. Please add like https://github.com/FortAwesome/Font-Awesome does.

**Comment by Templarian** [comment]
I've decided not to add NPM support. I assume Font Awesome only keeps it for legacy reasons at this point.

I may reconsider it in the future, but for now fonts and icons do not really belong in the Node Package Manager. Please use [bower](http://bower.io/) to manage your Front End resources.

Thanks for getting involved though and feel free to suggest icons. :D

**Comment by vanthome** [comment]
Your assumption is wrong. NPM does not position itself as a server side only package manager and in fact it is used quite extensively for this purpose.
See:
http://blog.npmjs.org/post/101775448305/npm-and-front-end-packaging
Some examples of Frontend Stuff build around the NPM eco system:
https://github.com/atomify
https://github.com/vcl

**Comment by jgoux** [comment]
I'm interested too.
I'd like to have one unified system to handle all my dependencies.
As angular + angular-material are on NPM, it would be awesome to have mdi too. :)

**Comment by Templarian** [comment]
Forgot to attach the issue that is blocking this one... the directory structure is being updated this week. Once it is in I'll be adding the NPM package.

https://github.com/Templarian/MaterialDesign/issues/126

**Comment by jgoux** [comment]
Great ! Thanks a lot. ;)

**Comment by Templarian** [comment]
So, now that SASS is done and the build process is recoded with the new file structure. I'll be working on adding NPM tonight. Hopefully it doesn't take too long. :smile:

I figure NPM is slightly more important than LESS support. But that's coming right after I get done wiring up NPM.

**Comment by Templarian** [comment]
Done. `npm install mdi`.

Good luck your apps!

**Comment by ritz078** [comment]
There isn't bower.json so it creates problems while linking through grunt wiredep. The path of main file is wrong.

**Comment by Templarian** [comment]
Oh, complete oversight on my part. Thanks for letting me know!

I'm going to be doing a `v0.9.52-alpha` today or tomorrow and will fix this.

Please track progress for this issue at #202
