### ISSUE TITLE
Icon for Report

### ISSUE THREAD

**Issue by igorushi** [Templarian/MaterialDesign#660]

**Comment by CoDEmanX** [comment]
If a google for that, most icons are similar to:

[![clipboard](https://materialdesignicons.com/icon/clipboard-text)](https://materialdesignicons.com/icon/clipboard-text)
[![clipboard](https://materialdesignicons.com/icon/clipboard-check)](https://materialdesignicons.com/icon/clipboard-check)
[![clipboard](https://materialdesignicons.com/icon/file-document)](https://materialdesignicons.com/icon/file-document)

For a document + [chart-line](https://materialdesignicons.com/icon/chart-line) there's too little space.
But maybe a document with a check mark? Or 3 bars? That seems very reasonable actually...

**Comment by igorushi** [comment]
I thought of something like this:
![image](https://cloud.githubusercontent.com/assets/7131092/9630199/3b6b375e-5181-11e5-8fa0-d22c026c8fc2.png)
(Insert text from powerpoint)

but file-document is a nice direction, thanks :)

**Comment by CoDEmanX** [comment]
See here for my contribution for file-check:
https://github.com/Templarian/MaterialDesign/issues/241#issuecomment-126014319

And here's a bar-chart type document:
![file-report](https://cloud.githubusercontent.com/assets/1309249/9635778/48a7bcaa-5198-11e5-8e55-5f740798e0fb.png) https://www.dropbox.com/s/okjfigz35dmyxfa/file-report.design?dl=0

**Comment by Templarian** [comment]
[![file-chart](https://materialdesignicons.com/icon/file-chart)](https://materialdesignicons.com/icon/file-chart)

Alias of `file-report` also added.
