### ISSUE TITLE
Pills

### ISSUE THREAD

**Issue by Henenenerik** [Templarian/MaterialDesign#6607]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have a website where the pill symbolises manipulating a single entry and I'd love to have a symbol with two (or more) pills next to each other to symbolise manipulating multiple entries.

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/22444370/169839919-8eeca6ee-cba1-4055-a914-e68465fa45db.png)

**Comment by boehan** [comment]
A few suggestions
![grafik](https://user-images.githubusercontent.com/7279415/170045826-5603b780-1c77-4e37-a0cd-3090f696d7f3.png)
![grafik](https://user-images.githubusercontent.com/7279415/170045875-8055ad87-6cf8-42ea-a417-0b5fa54f4a59.png)
![grafik](https://user-images.githubusercontent.com/7279415/170045908-fd0440cf-b45b-415f-99f1-a54518ecac00.png)

[pill-multiple.zip](https://github.com/Templarian/MaterialDesign/files/8763071/pill-multiple.zip)

**Comment by Henenenerik** [comment]
pill-multiple_v1 looks great!

**Comment by goyney** [comment]
Our normal `-multiple` modifier is a 2dp gap and then a 2dp copy of the shape. Your first version is close, but exposes too much detail of the second pill. Take a look at some other `-multiple` modified icons and see if you can match that style.

**Comment by goyney** [comment]
This would be more in line with the patterns set in our library:
![image](https://user-images.githubusercontent.com/1015040/170181657-7790b909-9f70-48eb-bff8-041cc489e261.png)
[pill-multiple.svg.zip](https://github.com/Templarian/MaterialDesign/files/8768007/pill-multiple.svg.zip)

Though in this case, showing a little more, as @boehan has proposed, might be better. I will let the other core contributors chime in their thoughts before adding anything.
![image](https://user-images.githubusercontent.com/1015040/170181799-de384db8-9726-46b4-b4e3-8b60b7aa133d.png)

**Comment by Templarian** [comment]
Agreed the 2nd variation with more overlap while not normal for the set does fit better.

**Comment by goyney** [comment]
[![pill-multiple](https://materialdesignicons.com/icon/pill-multiple)](https://materialdesignicons.com/icon/pill-multiple)
