### ISSUE TITLE
Northern lights

### ISSUE THREAD

**Issue by Tommatheussen** [Templarian/MaterialDesign#6608]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Inside Home Assistant, I have a couple of scripts that toggle specific lighting effects on my LED strips. 1 of those effects is a Northern Lights/Aurora effect.
I'd be nice if I had a neat icon on my UI that triggers this lighting effect.

### Give us an example of what this icon might look like.

This is a nice one that I've come across during my searches on Google https://www.flaticon.com/free-icon/northern-lights_1553326

**Comment by jhil** [comment]
How's this?
[aurora.svg.zip](https://github.com/Templarian/MaterialDesign/files/9078351/aurora.svg.zip)


![image](https://user-images.githubusercontent.com/2228347/178129906-564319d2-b225-4e68-b9af-d2a96dc3b4d3.png)

**Comment by goyney** [comment]
Do we really need to break the 2dp border for it? That's my only criticism. Otherwise, seems like a solid first pass.

**Comment by jhil** [comment]
Yeah, I wrestled with this because with the border, you lose room for the
vertical lines and it looks like something else. Maybe if it's more inset,
1dp vertical lines could work? Is that kosher?

**Comment by jhil** [comment]
How's this? 
![image](https://user-images.githubusercontent.com/2228347/178797838-42b7af10-16c2-4f24-a487-b2b2be8e280e.png)

Uses a 1px border

**Comment by jhil** [comment]
[![aurora](https://materialdesignicons.com/icon/aurora)](https://materialdesignicons.com/icon/aurora)

**Comment by jhil** [comment]
@goyney or @Templarian - I don't have access to edit labels or close out a task. Can someone help me out?
