### ISSUE TITLE
New Google logo icon

### ISSUE THREAD

**Issue by SLembas** [Templarian/MaterialDesign#661]
September 1st Google changed their product logos. Google+, "G", Google Maps... I think the icons should be updated.

**Comment by CoDEmanX** [comment]
Yes, but maybe keep the old one for a while as googe-legacy?

Found an SVG version of the new logo on wiki commons:
https://commons.wikimedia.org/wiki/File:Google_2015_logo.svg

**Comment by SLembas** [comment]
I was not mean to replace them. Sure the old ones should be kept.

**Comment by Templarian** [comment]
I don't think there will be a reason for legacy use. I have the new Google Plus icon from the footer on their site. Was out last night for an event or would have updated them. Out tonight also, but might have some time to update them.

- `google`
- `google-plus`
- `google-plus-box`
- delete `google-maps`

**Comment by CoDEmanX** [comment]
Why delete google-maps?
![google-maps](https://cloud.githubusercontent.com/assets/1309249/9637257/1bcbaa22-51a0-11e5-86bc-85f8b508f606.png)

**Comment by Templarian** [comment]
Way too much detail for this icon pack. It doesn't really fit, so more of a quality control correction.

**Comment by oRRs** [comment]
Looking forward to the update! :smile:

**Comment by Templarian** [comment]
[![google](https://materialdesignicons.com/icon/google)](https://materialdesignicons.com/icon/google) [![google-plus](https://materialdesignicons.com/icon/google-plus)](https://materialdesignicons.com/icon/google-plus) [![google-plus-box](https://materialdesignicons.com/icon/google-plus-box)](https://materialdesignicons.com/icon/google-plus-box)

**Comment by oRRs** [comment]
Thanks a bunch!
