### ISSUE TITLE
package-delivered

### ISSUE THREAD

**Issue by GitHubGoody** [Templarian/MaterialDesign#6610]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I need an icon for delivered packages to use in Home Assistant.

Aliases: package-delivered, door-package

### Share a preview of your contribution.

![door-package](https://user-images.githubusercontent.com/46235745/170299529-9065a97b-2f2e-4667-832b-1b787901f368.PNG)

### Upload the icon source.

[door-package.zip](https://github.com/Templarian/MaterialDesign/files/8772476/door-package.zip)

**Comment by boehan** [comment]
What about these?
![grafik](https://user-images.githubusercontent.com/7279415/170708312-ed26e2b3-e760-45e7-9d4d-299828f525c1.png)
![grafik](https://user-images.githubusercontent.com/7279415/170708349-cec328ca-8bd9-4e80-be99-2cf618b5aff1.png)

[package-check.zip](https://github.com/Templarian/MaterialDesign/files/8786936/package-check.zip)

**Comment by GitHubGoody** [comment]
To me, those say "a package/box is good/checked" not "a package is at my door."

**Comment by goyney** [comment]
The amount of room of which the door current takes in the artboard does not leave enough space for a discernible "package". I believe the request is a little overly specific and that the options suggested by @boehan are reasonable additions to the library. In the proper context, they would solve the suggested use case.

**Comment by GitHubGoody** [comment]
Yeah, I agree it's not the best, but it does achieve what I'm after for my use case. In general, is the goal to minimize new icon additions even if they adhere to the guidelines? Why not add all three?

For me and my use case, I'd use a regular door icon over the package with a check mark.

**Comment by Simran-B** [comment]
Icons need to be legible at native size. It's okay if they require some context to be understandable, but all elements should be clearly identifiable. The package in your suggestion is too small in our opinion. Furthermore, it doesn't appear to adhere to the material design guidelines. Strokes and padding should be 2px.

**Comment by goyney** [comment]
[![package-check](https://materialdesignicons.com/icon/package-check)](https://materialdesignicons.com/icon/package-check)[![package-variant-closed-check](https://materialdesignicons.com/icon/package-variant-closed-check)](https://materialdesignicons.com/icon/package-variant-closed-check)
