### ISSUE TITLE
Image Outline Modifiers

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6612]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Here's `image-plus-outline`, `image-minus-outline`, and `image-remove-outline` to complete the set.

### Share a preview of your contribution.

![image-plus-outline](https://user-images.githubusercontent.com/1837101/170347750-baf47928-a6a4-4389-90af-4fc1b271e049.png)
![image-minus-outline](https://user-images.githubusercontent.com/1837101/170347740-4354ea24-00a6-4c97-bd2e-cadc0fa61f95.png)
![image-remove-outline](https://user-images.githubusercontent.com/1837101/170347731-49bdc6db-7708-4157-932c-0b16262b3f03.png)

### Upload the icon source.

[image-outline-modifiers.zip](https://github.com/Templarian/MaterialDesign/files/8773872/image-outline-modifiers.zip)

**Comment by goyney** [comment]
[![image-plus-outline](https://materialdesignicons.com/icon/image-plus-outline)](https://materialdesignicons.com/icon/image-plus-outline)[![image-minus-outline](https://materialdesignicons.com/icon/image-minus-outline)](https://materialdesignicons.com/icon/image-minus-outline)
[![image-remove-outline](https://materialdesignicons.com/icon/image-remove-outline)](https://materialdesignicons.com/icon/image-remove-outline)
