### ISSUE TITLE
Particle Icon

### ISSUE THREAD

**Issue by glennmichaelmejias** [Templarian/MaterialDesign#6613]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I will use this to my app. Thanks.

### Give us an example of what this icon might look like.

Particle Icon like this.
https://www.google.com/search?q=particle+icon&sxsrf=ALiCzsaCdKyNXPU4OXT68uAlNlwdIYItvA:1653699559339&tbm=isch&source=iu&ictx=1&vet=1&fir=s8d3wZuf5Ji6AM%252Cn4fNVloDr3ampM%252C_%253BvBFjUJrZHJdYDM%252Cu1WA5JkwJAGHgM%252C_%253BZ_i5VYqbgibXEM%252CS5XJwOctOUpdMM%252C_%253B8-iE-YV_JBjXdM%252ChSj0ElH46v_LPM%252C_%253Bi--U75XeFMqfFM%252Cz0H3IEq_KvhZJM%252C_%253B24LML1kJPbxyGM%252C2g7TCbBCJ5Cf1M%252C_%253BZuPuREUJLrHiHM%252CdwmSZCqlRVuLkM%252C_%253BnFQhnPASAwNP2M%252C6lsVqpcyin7jvM%252C_%253BaC6p0PgQKQQR6M%252CV8IDimLHtluB1M%252C_%253B3d_e9QSsiDOOtM%252Cz7tGUnFrKkLTwM%252C_%253B26hTY2iLGTr4eM%252C-RW6cmYSfvNahM%252C_%253Bx8oeCTS5jFNgKM%252CcbcnzJ3qitZARM%252C_%253B4whNlSlda9TtFM%252Cw4rsyWhkFMlS7M%252C_%253BwiyvqKw_n75fBM%252Ca5XY8J_KYwNOrM%252C_%253BwklMLreRSQxx-M%252Cc5CoafviRfJk6M%252C_%253Bm8e6h2a4Su8MFM%252CIasnKmho3PuzEM%252C_&usg=AI4_-kTb5P2rvhKo5QE_KtTKUAdRh9bMNg&sa=X&ved=2ahUKEwi4s7L2_oD4AhWMd94KHZJODBAQ9QF6BAgqEAE#imgrc=aC6p0PgQKQQR6M

**Comment by goyney** [comment]
A particle is defined as "any of the basic units of matter and energy (such as a molecule, atom, proton, electron, or photon)". We have icons for all of these.

[![molecule](https://materialdesignicons.com/icon/molecule)](https://materialdesignicons.com/icon/molecule)[![atom-variant](https://materialdesignicons.com/icon/atom-variant)](https://materialdesignicons.com/icon/atom-variant)[![atom](https://materialdesignicons.com/icon/atom)](https://materialdesignicons.com/icon/atom)[![circle-small](https://materialdesignicons.com/icon/circle-small)](https://materialdesignicons.com/icon/circle-small)
