### ISSUE TITLE
hand-front-left-circle

### ISSUE THREAD

**Issue by PurpleProgrammer** [Templarian/MaterialDesign#6614]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Same use with hand-front-left, but circle variation, which is blends better with an app in some cases. It would be really convenient for an outlined variant to be created with it, as well as hand-back-left, hand-back-right and hand-front-right, just like the icons that exist right now.

### Give us an example of what this icon might look like.

![hand_front_left_circle](https://user-images.githubusercontent.com/24755259/170855714-16cca885-f67d-4776-b915-dc5a8f7dcc6e.png)

**Comment by goyney** [comment]
The hand icons are too large to fit inside a circle modifier.

**Comment by PurpleProgrammer** [comment]
Will simply put it inside a colored div as a workaround, then. Thanks for your reply!
