### ISSUE TITLE
Right and Left Hands

### ISSUE THREAD

**Issue by bjoernramos** [Templarian/MaterialDesign#6616]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In serval apps you can choose that your a left- and right-hand writer. Is it pssoble to design an icon what shows two hands and in one of both is the left hand black and the other is outlined and in the other is the rieght hand black and the left hand is outlined.

### Give us an example of what this icon might look like.

![IMG_7714](https://user-images.githubusercontent.com/26013371/171149573-54348352-baff-4622-a658-9225dbb78841.JPG)
![IMG_7713](https://user-images.githubusercontent.com/26013371/171149622-6e5cad7b-89fb-4fbb-ba92-11aa2c98e1b0.JPG)

**Comment by goyney** [comment]
We literally have these. Please search.
