### ISSUE TITLE
Outside Noise

### ISSUE THREAD

**Issue by adi90x** [Templarian/MaterialDesign#6617]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Would use this icon to show whether it is allowed to do noise outside ( example : using any motor tools ).
Would also have the same icon with a "bar" on it for period where it is forbiden

### Give us an example of what this icon might look like.

Maybe something with tools outside or a house with noise symbole  ?

**Comment by Circeus** [comment]
`cellphone-sound` but with a house and the soundwave going toward the house?

**Comment by jhil** [comment]
How are these?

![image](https://user-images.githubusercontent.com/2228347/178123338-89621dbb-fb02-4c5a-bdb2-376e47a72f3d.png)
![image](https://user-images.githubusercontent.com/2228347/178123341-f6942270-cb52-408c-84f8-28ecff58acfb.png)
![image](https://user-images.githubusercontent.com/2228347/178123344-3345b4b9-ad46-4e60-9c44-6f38021e5508.png)
![image](https://user-images.githubusercontent.com/2228347/178123345-0098265c-e44b-4ccc-8451-a2c0ea684976.png)

**Comment by goyney** [comment]
@jhil Upload the SVGs and label this with `Contribution` please. 😄

**Comment by andrejsharapov** [comment]
Maybe so?))
![image](https://user-images.githubusercontent.com/44722574/178570573-a6bb4990-11d6-4b49-b5b0-303b5906ceb3.png)

**Comment by jhil** [comment]
[![home-sound-out](https://materialdesignicons.com/icon/home-sound-out)](https://materialdesignicons.com/icon/home-sound-out)[![home-sound-out-outline](https://materialdesignicons.com/icon/home-sound-out-outline)](https://materialdesignicons.com/icon/home-sound-out-outline)[![home-sound-in](https://materialdesignicons.com/icon/home-sound-in)](https://materialdesignicons.com/icon/home-sound-in)[![home-sound-in-outline](https://materialdesignicons.com/icon/home-sound-in-outline)](https://materialdesignicons.com/icon/home-sound-in-outline)
