### ISSUE TITLE
Material Design Icons REST API

### ISSUE THREAD

**Issue by Jake-NSW** [Templarian/MaterialDesign#6618]
### What new documentation or how-to guide would you like to see?

Would love to have some documentation (if any) on a REST API for the material icons. So I can get icons through web requests, with the parameters defined by the ones in the advanced export

**Comment by goyney** [comment]
Documentation about the API exists already: https://dev.materialdesignicons.com/contribute/site/api

However, please **do not use these endpoints to scrape the site or to build third party applications**. All data is provided in the `meta.json` on the [CDN](https://cdn.jsdelivr.net/npm/@mdi/svg@6.7.96/meta.json) or in the [GitHub](https://github.com/Templarian/MaterialDesign-SVG/blob/master/meta.json) repo after every release. You should always use the static packages assets first the API as a very last resort.
