### ISSUE TITLE
folder-remove-circle-outline

### ISSUE THREAD

**Issue by movalz** [Templarian/MaterialDesign#6620]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I suggest a folder icon with a "remove" overlay in a circle. This would fit with the icons folder-alert-outline and folder-information-outline. The existing icon folder-remove-outline doesn't fit together with folder-alert-outline and folder-information-outline.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/7384804/171596681-613fb355-4f78-404f-ba08-830e404c698f.png)

### Upload the icon source.

[folder-remove-circle.zip](https://github.com/Templarian/MaterialDesign/files/8822383/folder-remove-circle.zip)

**Comment by goyney** [comment]
Thanks for the suggestions. However, this is not a standard modifier and we already have `folder-remove-outline`. The alert and information variants exists as they do due to the width of the base icon. That being said, this is not a variant we are going to add at this time.
