### ISSUE TITLE
pointer-button

### ISSUE THREAD

**Issue by CodeFetch** [Templarian/MaterialDesign#6621]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need an "icon depicting a button" for the categorical overview of UI elements specifically for the category "buttons".

### Give us an example of what this icon might look like.

My idea is the same as the gesture-tap-button, but with a cursor instead of a hand.

**Comment by goyney** [comment]
From a UX standpoint, buttons shouldn't be using the hand cursor, so I fully support adding this icon.

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/173689690-a9717004-c4c0-4a5a-a05f-a50c572117d5.png) ![image](https://user-images.githubusercontent.com/44722574/173689703-a8398498-3055-476b-aa8d-0f9bf9c6e106.png)

![image](https://user-images.githubusercontent.com/44722574/173689789-173eef8b-aa61-42d3-a5cf-04a7c24160ca.png) ![image](https://user-images.githubusercontent.com/44722574/173689825-c296ae22-f200-4b45-beac-e61afd1f6199.png)

![image](https://user-images.githubusercontent.com/44722574/173690413-2656172c-e372-40e2-951d-9876c827660d.png) ![image](https://user-images.githubusercontent.com/44722574/173690528-bb2438b3-cce6-436c-9ce0-e892379e5a99.png)

![image](https://user-images.githubusercontent.com/44722574/173689958-eff02e3f-525c-41bd-a678-4352099ff746.png) ![image](https://user-images.githubusercontent.com/44722574/173689976-3e8d945b-0380-4ac0-a305-9c0adffa92c6.png)

I've expanded on this idea a bit. Perhaps these icons will be needed to work with UIKit. They still need to be improved, but it's 1 am for me now)) I'll leave my sources here, maybe someone can improve these icons.
[buttons.zip](https://github.com/Templarian/MaterialDesign/files/8904001/buttons.zip)

**Comment by goyney** [comment]
I just think we need this:

[![gesture-tap-button](https://materialdesignicons.com/icon/gesture-tap-button)](https://materialdesignicons.com/icon/gesture-tap-button)

With a cursor like this:

[![cursor-default](https://materialdesignicons.com/icon/cursor-default)](https://materialdesignicons.com/icon/cursor-default)

...in its place.

**Comment by andrejsharapov** [comment]
You're right. In this case, it would be appropriate to reconsider the version of the `calendar-cursor` icon. And tomorrow I'll try to make a suitable icon, if someone hasn't done it yet.

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/173828905-b25e7d6d-0942-4ce4-8e63-6297e125a59f.png) ![image](https://user-images.githubusercontent.com/44722574/173828481-4ce87c20-9cee-4c1a-a9b3-937c7caf04e5.png)

I think you can use this `default state` version of the button. According to the rules UI elements should change the cursor on hover, so it would be correct to use not the cursor, but the hand for `state-hovered`, but `gesture-tap-button` for the click/activity state.

**Comment by goyney** [comment]
Added these two:
[![button-cursor](https://materialdesignicons.com/icon/button-cursor)](https://materialdesignicons.com/icon/button-cursor)[![button-pointer](https://materialdesignicons.com/icon/button-pointer)](https://materialdesignicons.com/icon/button-pointer)

Added an alias to `gesture-tap-button` so it can be found with these. Added all to the `Forms` tag. Naming here is kinda weird because the hand icons all follow the gesture naming convention. We might revisit these names in v8.
