### ISSUE TITLE
icon with .csv text 

### ISSUE THREAD

**Issue by yash-myblockboard** [Templarian/MaterialDesign#6623]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

to show it on the text field

### Give us an example of what this icon might look like.

need icon which should only have 
*.csv* 
![Screenshot 2022-06-06 at 4 06 20 PM](https://user-images.githubusercontent.com/103049033/172145382-757795d5-5d3d-4235-9656-0d41b2e43504.png)

**Comment by goyney** [comment]
We have `file-delimited` for CSV files.

[![file-delimited](https://materialdesignicons.com/icon/file-delimited)](https://materialdesignicons.com/icon/file-delimited)

While we do have file extension based icons for common image types, I don't really know if we want to start adding ones for every other file type. I will consult with the other contributors on how we want to proceed on that front.
