### ISSUE TITLE
Direction icons for AC swing mode

### ISSUE THREAD

**Issue by houxg** [Templarian/MaterialDesign#6624]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I was trying to integrate my HAVC into Home Assistant and sadly found that there are no icons for different swing direction. Is there a chance to add some?

for instance, i hope there will be 6 icons, stands for 15°\30°\45°\60°\75°\90°

### Give us an example of what this icon might look like.

<img width="336" alt="swing" src="https://user-images.githubusercontent.com/9605160/172327193-09f05eca-55bd-4f6c-8097-3b530b61a58e.png">

**Comment by goyney** [comment]
This is captured as part of #5653, so going to mark it as a duplicate.
