### ISSUE TITLE
Calendar with star

### ISSUE THREAD

**Issue by BWhiteApps** [Templarian/MaterialDesign#6631]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I want to indicate an important date.

### Give us an example of what this icon might look like.

Similar to the current calendar icon except with a star instead of a box for the date.

**Comment by andrejsharapov** [comment]
v1
![image](https://user-images.githubusercontent.com/44722574/173591737-62dce1eb-4f3e-486f-a248-f82b0e64f2c4.png)
![image](https://user-images.githubusercontent.com/44722574/173591767-4b6bf4dd-2654-4dcd-ab59-719afe072732.png)


v2
![image](https://user-images.githubusercontent.com/44722574/173591811-be146aee-a4c6-45f4-a204-eed8ca9c8b52.png)
![image](https://user-images.githubusercontent.com/44722574/173591840-cb0b37d4-fa36-402a-830a-a54530dbb2b6.png)

**Comment by goyney** [comment]
`calendar-star` already exists. Added the outlined variant here.

[![calendar-star-outline](https://materialdesignicons.com/icon/calendar-star-outline)](https://materialdesignicons.com/icon/calendar-star-outline)
