### ISSUE TITLE
Replace playlist-remove with official Google version

### ISSUE THREAD

**Issue by TacoTheDank** [Templarian/MaterialDesign#6632]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Sorry, there was no "request an icon update" option. This felt like the closest thing (because this is technically "new" and is a request).

There is an icon made by the community: `playlist-remove`.

As of Nov 2021, Google has made [their own official one](https://github.com/google/material-design-icons/blob/master/src/av/playlist_remove/materialicons/24px.svg).

I feel that `playlist-remove` should be replaced with the official Google material version and reassigned accordingly.

### Give us an example of what this icon might look like.

This is the official version by Google:

![image](https://user-images.githubusercontent.com/32376686/173261103-d8aca2c3-40f0-454f-b01e-ec2697b142fd.png)

**Comment by goyney** [comment]
This change makes sense. We'll get to it. Thanks for reporting.

**Comment by TacoTheDank** [comment]
@goyney No problem.

By the way, would it be okay for there to be a "request an icon update" issue template for users like me looking to have icons updated?

There are a bunch of other icons for which I'd like to request updates (or replacements by Google Material that now exist). However, the `I only intend to request a single icon (or a few near-identical ones)` rule limits me on how many I can fit in an issue, and I'd rather not "spam" the repo with individual (or small groups of) icon update requests in case there's a better way to do this. What would you suggest?

Thanks.

**Comment by goyney** [comment]
Sure, we can get a template created.

Just a note, just because Google has a version of an icon we have a community version doesn't mean well update it automatically. It's better to suggest a new icon request in those situations. Sometimes they're worth updating, sometimes they're worth adding as a variation, sometimes we feel our version is superior.

**Comment by goyney** [comment]
Actually, thinking about this a little more (while in the process of creating a new issue template), an update to an icon is relatively rare. I think the best case would be to submit a bug report for an icon glyph that has some issue that needs rectifying.

**Comment by goyney** [comment]
This has been updated. Additionally, plus, minus, edit, check, and star have been modified to follow the positioning and spacing of remove for consistency.
