### ISSUE TITLE
Inside and outside the house

### ISSUE THREAD

**Issue by kongjudas** [Templarian/MaterialDesign#6634]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Illustrating inside or outside the house, as for cameras, people out of wifi range, climate sensors...

### Give us an example of what this icon might look like.

A house with at person outside and a house with a person inside, similar to the nature-people icon.
![nature-people](https://user-images.githubusercontent.com/55403016/173633180-f46624d5-e6b4-4bd7-b416-af2c45c3dbca.png)

**Comment by andrejsharapov** [comment]
you can use `home` and `account-home` icons for this :smirk:

**Comment by goyney** [comment]
Agree with @andrejsharapov. Thanks for the suggestion.

**Comment by kongjudas** [comment]
Yes, I agree. Thanks for showing me.
