### ISSUE TITLE
Ascending/Descending

### ISSUE THREAD

**Issue by TheCarpetMerchant** [Templarian/MaterialDesign#6635]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Be clearer on what the icon does.

### Give us an example of what this icon might look like.

1) A big arrow pointing up with "ASC" written underneath. The arrow would look like `keyboard_arrow_up`. The letters would be in the style of `sort-alphabetical-ascending`. Same goes for "DESC" with the arrow pointing the other way.
2) Make versions of `sort-descending` and `sort-ascending` where the biggest line is at the top.

**Comment by goyney** [comment]
This requires the icon to assume language. We have plenty of icons to indicate ascending and descending without the need for including "asc" or "desc".
