### ISSUE TITLE
Car (EV) Charging / Not charging

### ISSUE THREAD

**Issue by kongjudas** [Templarian/MaterialDesign#6636]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Showing if the electric vehicle is in charging mode or not. "Not" could be illustrating that the car is fully charged.

### Give us an example of what this icon might look like.

A car with a charger and a lightning. The lightning can be stroked if it's not active.

**Comment by goyney** [comment]
There is not enough room to include a car, a charger, and a lightning bolt. We already have `car-electric(-outline)`. Using that with a simple `car` while not charging should be enough to indicate the two states.

**Comment by kongjudas** [comment]
My wife would disagree. How about just the lightning?

**Comment by goyney** [comment]
Just the lightning what?

**Comment by goyney** [comment]
Considering we have several icons to handle this use case and no further clarification was provided, we're going to close out this issue. Please feel free to comment back if you have more information that could help us determine a path forward.
