### ISSUE TITLE
Robot Mower active

### ISSUE THREAD

**Issue by kongjudas** [Templarian/MaterialDesign#6637]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Showing that the robot lawn mower is out working

### Give us an example of what this icon might look like.

The existing mower icon with some grass flying around

**Comment by goyney** [comment]
Ehh, this doesn't sound feasible within Material guidelines. If someone wants to take a stab at it, feel free.

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/173662583-9812c504-3a45-4ebe-a77a-ba267375e92a.png)
It seems to me that this will be the good option, since it will be very difficult to draw small details.

**Comment by goyney** [comment]
I see what you're getting at there. To me, that convey's the mower making noise, which might be enough to fit this use case. We do, however, also have `mower-bag` that would need this. These will likely be `-on` variants.

**Comment by kongjudas** [comment]
With hardly any manual mowers left in Norway, I think the robot version could need a companion. How about just adding the two lines to the robot?

**Comment by goyney** [comment]
[![mower-on](https://materialdesignicons.com/icon/mower-on)](https://materialdesignicons.com/icon/mower-on)[![mower-bag-on](https://materialdesignicons.com/icon/mower-bag-on)](https://materialdesignicons.com/icon/mower-bag-on)
