### ISSUE TITLE
Select-up

### ISSUE THREAD

**Issue by SintijaPotaicuka** [Templarian/MaterialDesign#6638]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Icon will be used to select an element group within a container when designing page layouts in CMS.

Usually this action is presented with an arrow up, however I think it is not presented correctly, as icon could mean move content or jump one level higher and not to select a whole group.

Additional options:

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/102287459/173676172-951c4fd9-496c-4171-aa41-390cdad7e6a2.png)

### Upload the icon source.

[select-up.svg.zip](https://github.com/Templarian/MaterialDesign/files/8903550/select-up.svg.zip)

**Comment by goyney** [comment]
[![select-arrow-up](https://materialdesignicons.com/icon/select-arrow-up)](https://materialdesignicons.com/icon/select-arrow-up)[![select-arrow-down](https://materialdesignicons.com/icon/select-arrow-down)](https://materialdesignicons.com/icon/select-arrow-down)
