### ISSUE TITLE
Gaming services icons

### ISSUE THREAD

**Issue by IlanF** [Templarian/MaterialDesign#664]
We already have Steam icon, but it would be great if we could have other services too.
Specifically I'm looking for Origin and Uplay but I'd like to see others such as GOG/Galaxy, PSN, Xbox Live.

**Comment by lvlirko** [comment]
I agree. For a gaming website or a gaming store, it is important to show the customer for which platform the game can be used. The most important platforms (to activate your CD Keys) in the gaming scene are:

Origin (EA, Electronic Arts)
- https://de.wikipedia.org/wiki/Datei:Origin.svg

Steam (already available)

GOG.com
- https://commons.wikimedia.org/wiki/File:Gog-logo-2014.svg

uPlay (Ubi, Ubisoft)
- https://en.wikipedia.org/wiki/File:Uplay_logo.jpg

**Comment by PeterShaggyNoble** [comment]
Closing this out for now as they seem far too niche but we'll revisit this issue if we ever add a dedicated icon pack for brand logos.

**Comment by Templarian** [comment]
Reopening this request.

**Comment by Templarian** [comment]
[![origin](https://materialdesignicons.com/icon/origin)](https://materialdesignicons.com/icon/origin)

Please create individual issues for the rest.
