### ISSUE TITLE
air-purifier-off

### ISSUE THREAD

**Issue by Kertz1954** [Templarian/MaterialDesign#6640]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

As per the title.

**Comment by goyney** [comment]
We've never had an `-off` variant of this icon. Changing this issue into a request for it.

**Comment by andrejsharapov** [comment]
Is this option suitable? This can be made as an `air-purifier` without air.

![image](https://user-images.githubusercontent.com/44722574/173901418-5c88a56c-8355-469a-99f3-14997443cc4b.png)
[air-purifier-off.zip](https://github.com/Templarian/MaterialDesign/files/8912213/air-purifier-off.zip)

**Comment by goyney** [comment]
Considering we kept the water for `air-humidifer-off`, we should keep the air lines here as well.

**Comment by andrejsharapov** [comment]
Really. I didn't notice it :pensive:

![image](https://user-images.githubusercontent.com/44722574/173917628-2919a7d9-ae29-490c-a0c4-572b6bcbd150.png)
[air-purifier-off.zip](https://github.com/Templarian/MaterialDesign/files/8912732/air-purifier-off.zip)

**Comment by goyney** [comment]
[![air-purifier-off](https://materialdesignicons.com/icon/air-purifier-off)](https://materialdesignicons.com/icon/air-purifier-off)
