### ISSUE TITLE
checkbox-intermediate-variant

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6642]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

We like to use the current "checkbox-intermediate" for the 'marked' status in our project, so we needed a new variant for the intermediate status.

### Share a preview of your contribution.

![preview-checkbox-intermediate-variant](https://user-images.githubusercontent.com/107536590/173793375-8757c3e9-2658-4fac-b013-a6b6bd0d8672.png)

### Upload the icon source.

[checkbox-intermediate-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/8907587/checkbox-intermediate-variant.svg.zip)

**Comment by goyney** [comment]
[![checkbox-intermediate-variant](https://materialdesignicons.com/icon/checkbox-intermediate-variant)](https://materialdesignicons.com/icon/checkbox-intermediate-variant)
