### ISSUE TITLE
circle-slice-9

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6643]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

For our project we are using the circle-slice-x series, however we are in need for some additional status icons. Therefor we created three new icons to add to the existing series. This -9 so we can skip -8 in our project, which we feel like is looking to much a selected radiobutton. We also like to contribute a -pauzed icon and a -postponed icon.

### Share a preview of your contribution.

![preview-circle-slice-9](https://user-images.githubusercontent.com/107536590/173789642-8f19abcb-d5fb-46fb-92e4-c1f7ac6e1530.png)

### Upload the icon source.

[circle-slice-9.svg.zip](https://github.com/Templarian/MaterialDesign/files/8907754/circle-slice-9.svg.zip)

**Comment by goyney** [comment]
I'm not sure the need for this. We have a handful of check circle icons already. Removing a 1dp border is technically against Material guidelines, so breaking that rule with a modifier seems like something we probably should not do.

**Comment by endiemen-ao** [comment]
The reason we created this one is that we wanted to keep the completed status within the line of the other icons in this series, while having a 'better' (more clear and exciting) final status icon (according to our client).

**Comment by Templarian** [comment]
It's a bit too cramped. The `check-circle-outline` or `check-underline-circle-outline` could convey the same.
