### ISSUE TITLE
Calendar Multi-Select Outline

### ISSUE THREAD

**Issue by soolasty** [Templarian/MaterialDesign#6644]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To show that it is possible to select many dates.

### Give us an example of what this icon might look like.

Multi-select calendar icon already exists but there is no outlined version.

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/173824085-3f913680-f2f9-45c0-9ae1-cf03d45cac4e.png)
[calendar-multiselect-outline.zip](https://github.com/Templarian/MaterialDesign/files/8909116/calendar-multiselect-outline.zip)

**Comment by goyney** [comment]
[![calendar-multiselect-outline](https://materialdesignicons.com/icon/calendar-multiselect-outline)](https://materialdesignicons.com/icon/calendar-multiselect-outline)
