### ISSUE TITLE
circle-slice-pauzed

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6645]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

For our project we are using the circle-slice-x series, however we are in need for some additional status icons. Therefor we created three new icons to add to the existing series. A -9 so we can skip -8 in our project, which we feel like is looking to much a selected radiobutton. We also like to contribute this -pauzed icon and a -postponed icon.

### Share a preview of your contribution.

![preview-circle-slice-pauzed](https://user-images.githubusercontent.com/107536590/173791044-d4cd8923-1e35-43ac-be1a-224655ff973b.png)

### Upload the icon source.

[circle-slice-pauzed.svg.zip](https://github.com/Templarian/MaterialDesign/files/8907824/circle-slice-pauzed.svg.zip)

**Comment by goyney** [comment]
This already exists as `pause-circle-outline`.
