### ISSUE TITLE
circle-slice-postponed

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6646]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

For our project we are using the circle-slice-x series, however we are in need for some additional status icons. Therefor we created three new icons to add to the existing series. A -9 so we can skip -8 in our project, which we feel like is looking to much a selected radiobutton. We also like to contribute a -pauzed icon and this -postponed icon.

### Share a preview of your contribution.

![preview-circle-slice-postponed](https://user-images.githubusercontent.com/107536590/173791529-378d8fec-6f66-419a-b6ab-1d9da3bd9607.png)

### Upload the icon source.

[circle-slice-postponed.svg.zip](https://github.com/Templarian/MaterialDesign/files/8907836/circle-slice-postponed.svg.zip)

**Comment by goyney** [comment]
This already exists as `minus-circle-outline`.

**Comment by endiemen-ao** [comment]
Sorry, my bad you’re right



Admicom Systems B.V.
​Fokkerstraat 31
Postbus 646, 3900 AP  Veenendaal
Tel: 0318 - 548 648
KvK nr. 30101798
Web: www.admicom.nl
Snel naar: Brochure  |  Software  |  Admicom Apps  |  Prijzen
De FENIT voorwaarden zijn op al onze leveringen van toepassing.
​
Op 15 jun. 2022, om 12:28 heeft Michael Irigoyen ***@***.******@***.***>> het volgende geschreven:



This already exists as minus-circle-outline.
