### ISSUE TITLE
Photoshop Tools

### ISSUE THREAD

**Issue by augustin32** [Templarian/MaterialDesign#665]
Im making a material design photoshop,so,i need tools icons.
![bce86127-754d-46aa-947a-0397f9d0cdc1 0f668417-47de-4fe7-bea1-a5fdff821fc6](https://cloud.githubusercontent.com/assets/14167196/9726449/763c931a-559f-11e5-9b26-c9aff1bb2dc5.jpg)
These are icons with names
- [ ] `cursor-move`
- [x] `marquee-rectangle`
- [ ] `marquee-elliptical`
- [ ] `marquee-row`
- [ ] `marquee-column`
- [ ] `lasso`
- [ ] `lasso-polygonal`
- [ ] `lasso-magnetic`
- [ ] `selection-quick`
- [x] `magic-wand`
- [x] `crop`
- [ ] `crop-perspective`
- [ ] `slice`
- [ ] `slice-select`
- [x] `eyedropper`
- [ ] `eyedropper-3d`
- [ ] `color-sample` (what's the difference?)
- [x] `ruler`
- [x] `note-text`
- [x] `numeric`
- [ ] `brush-spot-healing`
- [ ] `content-aware-move`
- [ ] `red-eye`
- [x] `brush`
- [x] `pencil`
- [ ] `color-replacement`
- [ ] `mixer-brush`
- [ ] `clone-stamp`
- [ ] `pattern-stamp`
- [ ] `history-brush`
- [ ] `art-history-brush`
- [ ] `gradient`
- [x] `paint-bucket`
- [ ] `3d-material-drop`
- [x] `blur`
- [ ] `sharpen`
- [ ] `smudge`
- [ ] `dodge`
- [ ] `burn`
- [ ] `sponge`
- [x] `pen`
- [ ] `freeform-pen`
- [ ] `add-anchor-point`
- [ ] `delete-anchor-point`
- [ ] `convert-point`
- [x] `horizontal-type`
- [ ] `vertical-type`
- [ ] `horizontal-type-mask`
- [ ] `vertical-type-mask`
- [ ] `path-selection`
- [ ] `direct-selection`
- [ ] `renctangle`
- [ ] `rounded-renctangle`
- [ ] `elipse`
- [x] `polygon`
- [ ] `line`
- [ ] `custom-shape`
- [ ] `hand-tool`
- [ ] `rotate-view`
- [x] `zoom`
- [ ] `switch-background-foreground-color`
- [x] `standart-screen-mode`
- [x] `full-screen-mode-with-menu-bar`
- [ ] `full-screen-mode`

**Comment by Templarian** [comment]
Can you edit your issue and include a list of each icon with a respective name (even for the ones that already exist). Use the ``- [] `name` `` syntax to create a checkbox list.

**Comment by Templarian** [comment]
I started, can you continue the list with the same style. New image helps, but this will put tasks next to the issue.

**Comment by CoDEmanX** [comment]
I would scratch magnetic lasso, because it was hard enough to make a magnet in 20x, and it doesn't even look good :/

**Comment by CoDEmanX** [comment]
The recently added vector* icons may fulfill the requests for rectangle, ellipse and custom shape symbols. Pan tool, a vertical ruler and gradient will be added as part of #420 (stock icons). For Fullscreen mode, there's already https://materialdesignicons.com/icon/fullscreen, but you may want to wait for http://www.google.com/design/icons/#ic_aspect_ratio.

There are a couple icons available for photoshop features depicted in the image, but are not listed in the request: Type tool, count tool, note tool, healing brush tool / patch tool (#420).

**Comment by CoDEmanX** [comment]
Some related tool icons that are new:
[marker](https://materialdesignicons.com/icon/marker)
[lead-pencil](https://materialdesignicons.com/icon/lead-pencil)
[eraser-variant](https://materialdesignicons.com/icon/eraser-variant)
[grease-pencil](https://materialdesignicons.com/icon/grease-pencil)

**Comment by JamesCoyle** [comment]
If anyone requires any of these icons still, please create a new issue for each icon and we'll deal with it there instead.
