### ISSUE TITLE
paperplane

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6650]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

We find the only 'send' icon in the current MDI library lacking some recognizability, therefor we created this send-variant, called 'paperplane'. We created this stand alone version, a solid circle version and an outline circle version.

### Share a preview of your contribution.

![preview-paperplane](https://user-images.githubusercontent.com/107536590/173797192-490df3fa-3d62-414e-a5ec-83ff1ada1420.png)

### Upload the icon source.

[paperplane.svg.zip](https://github.com/Templarian/MaterialDesign/files/8908028/paperplane.svg.zip)

**Comment by goyney** [comment]
Thanks for the contribution, but this has been suggested many times. Unfortunately, it is not Material as it shows perspective. We already have a paper airplane icon that meets Material guidelines. We won't be adding these.
