### ISSUE TITLE
format-list-group-plus

### ISSUE THREAD

**Issue by endiemen-ao** [Templarian/MaterialDesign#6653]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

In addition to the existing 'format-list-group' we created a plus variant. When clicked on this icon, a new list is added.

### Share a preview of your contribution.

![preview-format-list-group-plus](https://user-images.githubusercontent.com/107536590/173798694-6f5acf01-b464-4bd1-a6bb-2ee58c5da661.png)

### Upload the icon source.

[format-list-group-plus.svg.zip](https://github.com/Templarian/MaterialDesign/files/8908104/format-list-group-plus.svg.zip)

**Comment by goyney** [comment]
[![format-list-group-plus](https://materialdesignicons.com/icon/format-list-group-plus)](https://materialdesignicons.com/icon/format-list-group-plus)
