### ISSUE TITLE
create an pdf file icon

### ISSUE THREAD

**Issue by amirhoseinZare** [Templarian/MaterialDesign#6654]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

There is no pdf file icon in the library right now.
there is a box pdf icon which is not suitable when you are using file icons like mdiFileWordOutline mdiFileCodeOutline mdiFileExcelOutline and you need pdf one too but there isn't so it will harm ux of application and will bring disorder in ui,
I will apperciate you to provide a icons for this in both outline and filled forms.

### Give us an example of what this icon might look like.

[https://dribbble.com/shots/3355518-Attachment-Icons](url)

there is an example of how icon might look like in the link.

and there are some icons they look like one I need mdiFileWordOutline mdiFileCodeOutline mdiFileExcelOutline.

**Comment by andrejsharapov** [comment]
Hello! Look at https://github.com/Templarian/MaterialDesign/issues/6185 and https://github.com/Templarian/MaterialDesign/issues/6399
