### ISSUE TITLE
mdiWindowMinimize and mdiWindowMinimize icons are identical. Can they me merged / cleaned up? 

### ISSUE THREAD

**Issue by SintijaPotaicuka** [Templarian/MaterialDesign#6655]
### What icon would you like to alias?

mdiWindowMinimize

### What alias(es) should be added to the above icon?

mdiWindowMinimize

**Comment by Simran-B** [comment]
You wrote mdiWindowMinimize twice, what's the actual other icon?

**Comment by daavko** [comment]
The other icon is `minus-thick`. It's identical to `window-minimize`. The only actual difference between the two icons is how they're closed.
`minus-thick` has path `M20 14H4V10H20V14Z`
`window-minimize` has path `M20,14H4V10H20`

**Comment by Templarian** [comment]
This is intentional. We should definitely cleanup the path though. Those are both really old icons. We now leave off the final `Z` that closes the path.

**Comment by goyney** [comment]
`minus-thick` path updated.
