### ISSUE TITLE
calendar-unlock

### ISSUE THREAD

**Issue by Propaganistas** [Templarian/MaterialDesign#6656]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'm looking for visual enhancement of a filter that "loosens" preset date/calendar restrictions.

### Give us an example of what this icon might look like.

The current `calendar-lock` icon, but with an open lock. I have no preference between `lock-open` and `lock-open-variant`.

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/174547450-97954536-190f-4aff-a01f-3533cd778bd9.png) ![image](https://user-images.githubusercontent.com/44722574/174547485-9c25f01b-5d2a-4555-bead-d0aae84dc4b5.png)
[calendar-unlock.zip](https://github.com/Templarian/MaterialDesign/files/8938449/calendar-unlock.zip)

**Comment by andrejsharapov** [comment]
Found several bugs. Updated

**Comment by Propaganistas** [comment]
That's cool. Thanks.

**Comment by goyney** [comment]
The base `calendar-lock` icons were outdated, so those got updated with these additions:
[![calendar-lock-open](https://materialdesignicons.com/icon/calendar-lock-open)](https://materialdesignicons.com/icon/calendar-lock-open)[![calendar-lock-open-outline](https://materialdesignicons.com/icon/calendar-lock-open-outline)](https://materialdesignicons.com/icon/calendar-lock-open-outline)

**Comment by andrejsharapov** [comment]
Hello, @goyney. It seems to me that it would be better to make the top indent of the calendar 2px. Otherwise the icon will jump when using the hover effect 🤔

**Comment by goyney** [comment]
See #6667.
