### ISSUE TITLE
robot-vacuum-error

### ISSUE THREAD

**Issue by kongjudas** [Templarian/MaterialDesign#6657]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

When the vacuum is stuck somewhere and reports an error.

### Give us an example of what this icon might look like.

robot-vacuum with a cross or warning symbol

**Comment by goyney** [comment]
[![robot-vacuum-alert](https://materialdesignicons.com/icon/robot-vacuum-alert)](https://materialdesignicons.com/icon/robot-vacuum-alert)[![robot-vacuum-variant-alert](https://materialdesignicons.com/icon/robot-vacuum-variant-alert)](https://materialdesignicons.com/icon/robot-vacuum-variant-alert)
