### ISSUE TITLE
Dust storm

### ISSUE THREAD

**Issue by MrBartusek** [Templarian/MaterialDesign#6658]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'm the author of [MeteoalarmCard](https://github.com/MrBartusek/MeteoalarmCard) and I was looking for an icon to indicate dust storm warnings and similar ones. I would love to see a modified wind icon to use here.

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/23432278/174500999-c7e1afa7-73db-4ee7-98eb-4e16fc1ce7d7.png)

**Comment by MrBartusek** [comment]
Hey, @andrejsharapov I do love the second one (`v2`) and it's the exact thing that I would use in my project! Hope this icon will make it to the release! I'm not really a fan of the first icon (`v1`) since it looks too similar to [weather-windy](https://materialdesignicons.com/icon/weather-windy) and doesn't really highlight the dust part.

The second thing is icon naming. I don't really like the `sand-wind` it would be much better to use something like `weather-dust` or `weather-windy-dust` but `sand` would make for a great alias.

> but you can use the [weather-windy](https://materialdesignicons.com/icon/weather-windy) if particles are not very important to you.

I actually do use this as a temporary icon till this one will be added :)

Thanks for that draft!

**Comment by andrejsharapov** [comment]
Good 👍 
I'll add an archive v2 on case of, if the icon is approved, but it is very likely that the icon will appear only in version 7.0.xx
[sand-wind.zip](https://github.com/Templarian/MaterialDesign/files/8941383/sand-wind.zip)

**Comment by goyney** [comment]
[![weather-dust](https://materialdesignicons.com/icon/weather-dust)](https://materialdesignicons.com/icon/weather-dust)
