### ISSUE TITLE
Inconsistent cutouts in `account-*-outline` icons

### ISSUE THREAD

**Issue by daavko** [Templarian/MaterialDesign#6659]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

Some of the outline versions of account icons (namely `account-arrow-*-outline`) have a cutout where the cut off parts are joined by an arc. Example:
![account-arrow-down-outline](https://user-images.githubusercontent.com/7669061/174778992-993f0fea-4951-4154-9ffe-377b577236e3.png)

Others (all other `account-*-outline` icons) have a cutout where the cut off parts are *not* joined. Example:
![account-badge-outline](https://user-images.githubusercontent.com/7669061/174779176-a1e5bcee-3fe8-468f-943b-fe1e7ceed6df.png)

I wasn't able to find any previous discussion about this inconsistency. Is it intentional?

**Comment by andrejsharapov** [comment]
Hello!
The `account-badge-outline` icon is based on most others that use an additional element. Therefore, they are all drawn without a closure. Only the `-arrow-` and `-wrench-` icons have a arc.

**Comment by Templarian** [comment]
I'm wondering if it was for a visual reason it was done for the arrows possibly. We can always compare the two and see what people prefer. Would be nice to have them consistent without the arc if it looks okay.

**Comment by goyney** [comment]
They're already being updated. It was a left over artifact when the base outline icon changed a while back.

**Comment by goyney** [comment]
All the `account-arrow-*` icons have been updated, fixing the outline cut-out and ensuring consistency between the filled and outlined variants. `account-wrench(-outline)` has also been updated to fix the cutout issue. Thanks for the report!
