### ISSUE TITLE
Some `bank-*` icons are blurry

### ISSUE THREAD

**Issue by daavko** [Templarian/MaterialDesign#6661]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

The icons added in #5507 (`bank-check`, `bank-off`, and `bank-off-outline`) have some elements that aren't aligned to the 1dp grid. This causes horizontal blurriness. All other bank icons that were added earlier are shifted 1dp to the left to avoid this. This causes an inconsistency. I assume this wasn't intentional, which raises the question: Should they all be shifted 1dp to the left, or should they all be slightly blurry?

The `bank-outline` icon attributed to Google (which I'll assume was inserted as-is) is also blurry, but in a different place.

The modifier cutouts appear to be inconsistent as well.

See following comparisons:
![bank-minus-vs-bank-check](https://user-images.githubusercontent.com/7669061/174788121-a386ab07-a797-49eb-80cf-788f074269a0.png)
![bank-outline-vs-bank-outline-off](https://user-images.githubusercontent.com/7669061/174788267-fa847d50-aedf-4409-8526-5d8d2432eb0d.png)

**Comment by goyney** [comment]
Updated the 3 that did not have the base icon on the grid:
[![bank-off](https://materialdesignicons.com/icon/bank-off)](https://materialdesignicons.com/icon/bank-off)[![bank-off-outline](https://materialdesignicons.com/icon/bank-off-outline)](https://materialdesignicons.com/icon/bank-off-outline)
[![bank-check](https://materialdesignicons.com/icon/bank-check)](https://materialdesignicons.com/icon/bank-check)

The outline's columns are on the half pixel on purpose.
