### ISSUE TITLE
Some outline icons have `plus` and `minus` modifiers placed inconsistently

### ISSUE THREAD

**Issue by daavko** [Templarian/MaterialDesign#6662]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

When compared to their regular counterparts, some outline icons have the `plus` and/or `minus` modifier shifted all the way to the right edge of the icon. It appears this is most commonly present in icons where the modifier aligns to the edges of the actual object depicted in the icon ("boxy" icons like cards, email; see list below). Considering this is *not* done for modifiers such as `remove` and others, and other "boxy" icons have all modifiers in a consistent location (examples: `book`, `earth-box`,  `file`, `folder`, `lock`), I'd consider this a bug.

One visual example:
![card-plus-vs-card-outline-plus](https://user-images.githubusercontent.com/7669061/174790236-7452a3c1-5639-4bfe-9c7b-b400463270d8.png)

Examples of such icons (this *should* be a complete list, but it's possible I missed some):
- `card-plus` vs `card-plus-outline`
- `credit-card-plus` vs `credit-card-plus-outline`; `credit-card-minus` and `credit-card-minus-outline`
- `email-plus`, `email-plus-outline`, `email-minus`, `email-minus-outline`
- `image-minus` vs `image-minus-outline` (in this one, the filled version is aligned, but outlined isn't)
- `image-plus` vs `image-plus-outline`

**Comment by goyney** [comment]
Thanks for the report. The way things line up on the wide, rectangular outlined icons is intentional. If done as the filled versions, you'd have a weird `-minus` modifier that's 1dp off and makes the icon look broken if used out of context. Because of this, we've made visual tweaks for usability sake. So, `card`, `credit-card`, and `email` are not bugs and will remain.

`image-plus` and `image-minus` have been updated to match the outlined versions. Because they are square and contain more detail, the visual tweaks are not necessary.

**Comment by daavko** [comment]
I understand your rationale, I just wanted to see if this was intentional or not. Aligning things as visual tweaks makes sense in those cases.
In which case, shouldn't `card-minus-outline` modifier be aligned as well? It's not aligned currently.

Also, looking at other `email` modifiers, they're all strangely inconsistent. Some are a bit to the left (`email-send`, `email-receive`), some are aligned same as `plus` and `minus` (`email-check`), and some are somewhere in between (`email-remove`, `email-sync`). `email-lock` is in the upper corner for some reason and missing an outline version. Shall I open a new issue for those, or is this also intentional? Also, `email-send` and `email-receive` use non-standard cutouts.
