### ISSUE TITLE
`home-*` icons should have `house-*` alias

### ISSUE THREAD

**Issue by daavko** [Templarian/MaterialDesign#6663]
### What icon would you like to alias?

Several `home-` icons already have a `house-` alias. Those are the ones that are missing:

- `home-account`-> `house-account`, `house-user`
- `home-alert` -> `house-alert`, `house-warning` (+ `-outline` variant)
- `home-analytics` -> `house-analytics`, `house-chart`, `house-report`, `chart-house`
- `home-automation` -> `house-automation`
- `home-battery` -> `house-battery`, `house-energy`, `house-power`, `house-electricity` (+ `-outline` variant)
- `home-clock` -> `house-clock`, `house-time`, `house-schedule` (+ `-outline` variant)
- `home-edit` -> `house-edit`
- `home-export-outline` -> `house-export-outline`
- `home-flood` -> `house-flood`
- `home-group-minus` -> `house-group-minus`
- `home-group-plus` -> `house-group-plus` (perhaps also `home-group-add` and `house-group-add`)
- `home-group-remove` -> `house-group-remove`
- `home-heart` -> `house-heart`
- `home-import-outline` -> `house-import-outline`
- `home-lightbulb` -> `house-lightbulb`, `house-bulb` (+ `-outline` variant)
- `home-lightning-bolt` -> `house-lightning-bolt`, `house-energy`, `house-power`, `house-electricity`, `house-flash` (+ `-outline` variant)
- `home-lock` -> `house-lock`
- `home-lock-open` -> `house-lock-open`
- `home-minus` -> `house-minus`
- `home-plus` -> `house-plus`, `house-add`
- `home-remove` -> `house-remove`
- `home-roof` -> `house-roof`, `house-chimney`, `house-attic`
- `home-search` -> `house-search`
- `home-switch` -> `house-switch`, `house-swap`
- `home-thermometer` -> `house-thermometer`, `house-climate`, `house-temperature`

**Comment by daavko** [comment]
I didn't want to create an issue for every single `home` icon, as that would be way too many, so I just created a single one for all of them. I hope that's okay.

**Comment by goyney** [comment]
Aliases added.
