### ISSUE TITLE
Touch App

### ISSUE THREAD

**Issue by chibike** [Templarian/MaterialDesign#6664]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

There is no icon to indicate that touch interactions are allowed i.e. similar to Google's material design icon library "touch_app".

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/10292615/174834078-35649621-ab62-421c-951c-1adb86b22532.png)

### Upload the icon source.

![touch_app_FILL0_wght400_GRAD0_opsz48](https://user-images.githubusercontent.com/10292615/174834115-fdcdaaaf-9bbc-4d47-94a7-6181736f283c.svg)

**Comment by chibike** [comment]
Lovely, thank you.

Perhaps we could still add this icon, or add the "touch" tag to " gesture-tap-button".

Anyways, thank you for your speedy reply.

**Comment by goyney** [comment]
This already exists. Alias of `touch` added to several of the `gesture-tap` icons.

[![gesture-tap](https://materialdesignicons.com/icon/gesture-tap)](https://materialdesignicons.com/icon/gesture-tap)

**Comment by andrejsharapov** [comment]
Maybe add alias of `touch` and `hand` for the `braille` icon?

**Comment by goyney** [comment]
Added `touch-reading` and `hand-reading` to `braille`.
