### ISSUE TITLE
quad / Trike

### ISSUE THREAD

**Issue by Do-AIP** [Templarian/MaterialDesign#6665]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Home Assistant

### Give us an example of what this icon might look like.

https://cdn5.vectorstock.com/i/1000x1000/72/79/ride-quad-bike-icon-simple-style-vector-26987279.jpg
https://cdn-icons-png.flaticon.com/512/208/208633.png

**Comment by goyney** [comment]
[![atv](https://materialdesignicons.com/icon/atv)](https://materialdesignicons.com/icon/atv)
