### ISSUE TITLE
Speaker Playing, Paused, Stopped

### ISSUE THREAD

**Issue by felipecrs** [Templarian/MaterialDesign#6668]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In Home Assistant, icons are used to richfully taint a device according to a state. Here is one example for TVs:

```typescript
switch (device) {
  case "tv":
    switch (state) {
      case "playing":
        return mdiTelevisionPlay;
      case "paused":
        return mdiTelevisionPause;
      case "off":
        return mdiTelevisionOff;
      default:
        return mdiTelevision;
```

But unfortunately, the only variant that could be used in the example above for speakers would be the `mdiSpeakerOff`.

An icon for `speaker-playing` would cover at least the most important scenario.

- Refs https://github.com/home-assistant/frontend/pull/12997

### Give us an example of what this icon might look like.

I'm not a designer, but as there is already a few variants of `speaker` with an right icon on it, I believe one option is to add an `play` icon (just like `televisionPlay`) right at the right side of the `speaker`. Like:

![image](https://user-images.githubusercontent.com/29582865/175161080-d76b3856-d77d-49fb-bc04-9d7ff3463ddb.png)
![image](https://user-images.githubusercontent.com/29582865/175161100-61dce36f-49cb-49ee-bf6b-7d6d3fcc0f33.png)
![image](https://user-images.githubusercontent.com/29582865/175161133-41d07bd3-a65f-4a44-bb94-79a594b28aaf.png)

**Comment by goyney** [comment]
[![speaker-play](https://materialdesignicons.com/icon/speaker-play)](https://materialdesignicons.com/icon/speaker-play)[![speaker-pause](https://materialdesignicons.com/icon/speaker-pause)](https://materialdesignicons.com/icon/speaker-pause)
[![speaker-stop](https://materialdesignicons.com/icon/speaker-stop)](https://materialdesignicons.com/icon/speaker-stop)

**Comment by felipecrs** [comment]
Wow! Amazing!
