### ISSUE TITLE
Speaker with WiFi symbol

### ISSUE THREAD

**Issue by bverkron** [Templarian/MaterialDesign#6669]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

WiFi connected speakers in Home Assistant or other systems with WiFi attached speakers. WiFi connected speakers are becoming more common, especially in the context of things like Home Assistant.

### Give us an example of what this icon might look like.

It would be very similar to either the [cast-audio](https://materialdesignicons.com/icon/cast-audio) icon or the [speaker-bluetooth](https://materialdesignicons.com/icon/speaker-bluetooth) icon but with a WiFi symbol instead of the cast or bluetooth symbols.

My personal preference would be to have the WiFi symbol overlap the speaker slightly like in the `cast-audio` icon but on the right side instead of the left. This seems to make both the speaker and symbol a bit larger and more visible unlike the `speaker-bluetooth` icon which has both of those elements smaller to fit them in next to each other. Though, I'd be happy with anything with a WiFi symbol pair with a speaker :)

It would also be great to have a variation with two speakers similar to [speaker-multiple](https://materialdesignicons.com/icon/speaker-multiple) (but with the WiFi symbol added of course) since speakers are often in sets of at least two (or sometimes more).

**Comment by bverkron** [comment]
I see that there is a [speaker-wireless](https://materialdesignicons.com/icon/speaker-wireless) but to me this visually conveys a speaker emitting sound, much like the traditional speaker icons like [volume-high](https://materialdesignicons.com/icon/volume-high), as opposed to the more or less universal [WiFi symbol](https://commons.wikimedia.org/wiki/File:Wireless-icon.svg) which is in a vertical orientation.

**Comment by goyney** [comment]
There is absolutely no way to incorporate the wireless vertically with the speaker icon. `speaker-wireless` exists for this use case. Look at any other `-wireless` icon we have, they all follow the same pattern. The only icon that breaks this is `cellphone-wireless` (by including the dot), but the orientation is still not of the WiFi symbol. Added just the dot to the speaker complicates the icon and doesn't add any value over it's current form.

You'll need to use `speaker-wireless` or `cast-audio`. Thanks for the suggestion.

**Comment by bverkron** [comment]
While I will accept the rejection and use one of the existing icons I find it odd to say there’s “absolutely no way to incorporate the wireless vertically with the speaker icon”. The `cast-speaker` icon is very similar to what I suggested and a good example of how it could be done, just with a slightly different orientation of the bars. Also there are roughly as many `-wireless` icons with vertical, almost the entire second row has vertical bars (though not a complete set).
![E867E30A-67C6-4040-8192-C026F3033896](https://user-images.githubusercontent.com/19174503/175226190-a334a5a4-d936-466a-9b3d-78cd5cb850f5.jpeg)

Anyway, in the end the cast icon is close enough I suppose and does convey the right intent. Without the context of the other wireless icons the `speaker-wireless` icon really looks like it’s emitting sound which is unfortunate.
