### ISSUE TITLE
car-search

### ISSUE THREAD

**Issue by tetzla** [Templarian/MaterialDesign#6670]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

search a catalog of cars

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/81367382/175316626-fb2177d7-34fd-453e-9a43-fca9332a6af2.png)

### Upload the icon source.

[car-search.zip](https://github.com/Templarian/MaterialDesign/files/8967901/car-search.zip)

**Comment by goyney** [comment]
Nice contribution! We will need the cutout for the magnifying glass to be 2dp though before we can include it.

**Comment by tetzla** [comment]
I'm not sure if I understand you correctly. I've increased the spacing between car and magnifying glass. It's combination of mdi-car-cog and mdi-home-search.

![car-search](https://user-images.githubusercontent.com/81367382/175520573-2953ac59-84df-4a9f-8de1-891334fc7913.svg)

**Comment by andrejsharapov** [comment]
You need to make such an indent (your image is not displayed)

![image](https://user-images.githubusercontent.com/44722574/175649288-ad38cc9f-0712-4eca-ae3c-06056e042d74.png)

**Comment by goyney** [comment]
[![car-search](https://materialdesignicons.com/icon/car-search)](https://materialdesignicons.com/icon/car-search)[![car-search-outline](https://materialdesignicons.com/icon/car-search-outline)](https://materialdesignicons.com/icon/car-search-outline)

**Comment by tetzla** [comment]
Thanks a lot!!!
