### ISSUE TITLE
check-plus

### ISSUE THREAD

**Issue by tetzla** [Templarian/MaterialDesign#6671]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

add an item and instantly add another one

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/81367382/175342904-601c2bdd-53de-43c2-a131-519acac537b9.png)

### Upload the icon source.

[check-plus.zip](https://github.com/Templarian/MaterialDesign/files/8968873/check-plus.zip)

**Comment by andrejsharapov** [comment]
[checkbox-marked-circle-plus-outline](https://materialdesignicons.com/icon/checkbox-marked-circle-plus-outline)

**Comment by tetzla** [comment]
I know this icon. The checkbox is not entirely appropriate.

We have the following use case:
- add an object + close current wizard/dialog (= mdi-check/mdi-check-bold)
- add an object + restart current wizard/dialog (to add another one) (= new icon requests)

**Comment by goyney** [comment]
A check icon doesn't feel like an appropriate icon to put a modifier on. This seems very niche. I am of the opinion that this isn't a good fit for the library at this time.

**Comment by goyney** [comment]
We're gonna pass on adding this for now. Thanks for the suggestion.

**Comment by JensMander** [comment]
Good morning guys, any suggestions for an existing icon for that use case? To my mind it has to be an icon slightly different from the common check-icon to distinguish the cases "accept data and move on", "accept data and add more of that".
Besides that, why are there "checkbox-marked-circle-outline" and "checkbox-marked-circle-plus-outline"? Isn't it just another stlye of check-bold? So wouldn't it be just straighforward to have an simliar icon for the check "style"?

**Comment by goyney** [comment]
In nearly every `-plus` case, it means to "add another of the base." For example, add another account, add another alarm, add another filter, add another checkbox, etc. "Add another check" doesn't make sense because the check alone is inherently an action.

Your use case is to "perform a base action, then assume repeat." That's the difference and goes against the established pattern of the `-plus` modifier in our library.

From a UX perspective, this is also confusing to an end-user without explicit context (such as text that says "Create and then add another," which at that point, the meaning of the icon is useless and just decorative at that point.

As I stated before, we understand what you're trying to accomplish, it's just too niche of a use case for us to include in the library at this time.

I hope that helps clear our position up.

**Comment by goyney** [comment]
My suggestion would be to qualify what your "item" is (an account? a time? a file?), find that base icon, and use the `-plus` modifier of that. What are the "items" being added in your use case?

**Comment by JensMander** [comment]
Thanks for clarification, I see your point. Maybe we're using the check some kind of different. 
We've some items in our application that act like that e.g. we have a dialog to enter the lines of an invoice. Each line (position) of the invoice has it's own type (material costs, wages, ...),  but sometimes many positions have the same one. For UX (and performance) reasons we added the check-plus icon to not close the input dialog but transfering several data of the last line to a new one.

**Comment by tetzla** [comment]
Our items are very special and immaterial (e. g. insurance claims). It's not possible to find a suitable base icon. That's why we are using the generic icon "mdi-check" to finish the item creation dialog.

An icon "mdi-check-plus" would be highly appreciated to finish an restart the item creation dialog once again.
