### ISSUE TITLE
wrench-check

### ISSUE THREAD

**Issue by xonauga** [Templarian/MaterialDesign#6673]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

tool ordering in production, tool order done

### Give us an example of what this icon might look like.

Like wrench-clock, replace clock with small check icon

**Comment by xonauga** [comment]
Thank you very much Andrey! Great!

**Comment by Templarian** [comment]
Similar for the other issue `-outline` should also be added.

**Comment by goyney** [comment]
[![wrench-check](https://materialdesignicons.com/icon/wrench-check)](https://materialdesignicons.com/icon/wrench-check)[![wrench-check-outline](https://materialdesignicons.com/icon/wrench-check-outline)](https://materialdesignicons.com/icon/wrench-check-outline)
