### ISSUE TITLE
wrench-cog

### ISSUE THREAD

**Issue by xonauga** [Templarian/MaterialDesign#6674]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Tool ordering in production, tool order in progress

### Give us an example of what this icon might look like.

Like wrench-clock, replace clock with small cog

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/175944118-3cd131c2-c6e2-4976-9af2-19d44f714094.png) ![image](https://user-images.githubusercontent.com/44722574/175944152-6892049f-bfcc-4c55-bc44-98b6f51db26c.png)

**Comment by Templarian** [comment]
Probably need the `-outline` also added for the modifier.

**Comment by andrejsharapov** [comment]
I'm sorry, but I don't think it's possible. This will either be bad or break the rules of the material. :pensive: The same applies to wrench with check-mark.

**Comment by goyney** [comment]
[![wrench-cog](https://materialdesignicons.com/icon/wrench-cog)](https://materialdesignicons.com/icon/wrench-cog)[![wrench-cog-outline](https://materialdesignicons.com/icon/wrench-cog-outline)](https://materialdesignicons.com/icon/wrench-cog-outline)

Also added the outline version of the clock variant here too:
[![wrench-clock-outline](https://materialdesignicons.com/icon/wrench-clock-outline)](https://materialdesignicons.com/icon/wrench-clock-outline)
