### ISSUE TITLE
mdi-folder-lock-outline icon is not working

### ISSUE THREAD

**Issue by Shilpa-K07** [Templarian/MaterialDesign#6675]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

**mdi-folder-lock-outline** icon is not working in my vue project. I'm using vue 2.6.11 and vuetify 2.4.0

**Comment by Shilpa-K07** [comment]
What is the expected release date?

**Comment by goyney** [comment]
Should be today, actually. I know @Templarian has been a bit busy recently, so the releases didn't go out as quickly as we'd have liked.
