### ISSUE TITLE
table-filter

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#6677]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

In addition to the built-in `filter` icons, in some cases separate buttons are used to indicate the ability to filter/settings data in tables. To do this, it would be good to use *not just another filter* icon, but a special one that points to the `table-filter`.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/44722574/176102600-c1439b15-1058-440b-875d-1d7123d16a4f.png)

### Upload the icon source.

[table-filter.zip](https://github.com/Templarian/MaterialDesign/files/8998029/table-filter.zip)

**Comment by goyney** [comment]
Filter modifiers don't use the circular cutout. Check `calendar-filter` for an example.

**Comment by andrejsharapov** [comment]
You're right, but most `table-` icons have a circle at the bottom, but not 2dp cutout. I decided it would be better that way.

**Comment by goyney** [comment]
Most modifiers use the circle, filter is on that does not.

**Comment by goyney** [comment]
So it seems we have an existing issue in the library. The two icons that have the `filter` modifier use varying sizes:
[![account-filter](https://materialdesignicons.com/icon/account-filter)](https://materialdesignicons.com/icon/account-filter)[![calendar-filter](https://materialdesignicons.com/icon/calendar-filter)](https://materialdesignicons.com/icon/calendar-filter)

The first thing we need to do is decide which is the correct size moving forward and update the others to match. Then we will use that size here in the new table icon.

**Comment by goyney** [comment]
My opinion is that `account-filter` is the correct version of the filter modifier and we should update the calendars to use it. Then we should use that one on these new table icons.

To avoid the table being cut in a weird way, I would suggest moving the table base up 1dp and the filter down 1dp.

**Comment by goyney** [comment]
[![table-filter](https://materialdesignicons.com/icon/table-filter)](https://materialdesignicons.com/icon/table-filter)

`calendar-filter` was also updated.
