### ISSUE TITLE
bookmark-box & -outline

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6680]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

There is a bookmark-box-multiple, but no bookmark-box. I used the bookmark sizing from comment-bookmark for this.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/176344681-28e4079e-0d80-41c9-8849-904f1427a86c.png)
![image](https://user-images.githubusercontent.com/2228347/176344820-aded552f-b9aa-474a-b017-162190d58541.png)

### Upload the icon source.

[bookmark-box.zip](https://github.com/Templarian/MaterialDesign/files/9007013/bookmark-box.zip)

**Comment by jhil** [comment]
![image](https://user-images.githubusercontent.com/2228347/176719003-9bb5b555-66db-48ee-b7a1-534342b43e13.png)
![image](https://user-images.githubusercontent.com/2228347/176719051-46f33af0-139d-42cb-a3c9-a5b0f7f8181b.png)

**Comment by Templarian** [comment]
@jhil Looks good. I added the modifiers. Basically for `box` click box and `outline` similarly `outline`.

**Comment by jhil** [comment]
Ah, noted for next time :)
