### ISSUE TITLE
message-check

### ISSUE THREAD

**Issue by BigQCZ** [Templarian/MaterialDesign#6681]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have project where I can make remarks for client and I would like to show this icon when the remark is solved. I am using `message-alert-outline` when I making the remark.

### Give us an example of what this icon might look like.

I would like to use a similar icon to `message-alert`, outlined or not doesnt matter, but not with exclamation mark (!) with check mark (✓).

Thank you very much

**Comment by andrejsharapov** [comment]
![image](https://user-images.githubusercontent.com/44722574/176658209-79d7ab44-96ae-4252-b740-db54eb3cd803.png) ![image](https://user-images.githubusercontent.com/44722574/176658003-26593424-028c-4922-88d1-82772ebdaccd.png)
[message-check.zip](https://github.com/Templarian/MaterialDesign/files/9019028/message-check.zip)

**Comment by andrejsharapov** [comment]
but in general you can use the [comment-check](https://materialdesignicons.com/icon/comment-check) icon

**Comment by andrejsharapov** [comment]
@goyney, look here please:
1. `comment-check` and `comment-check-outline` have different check mark
2. Both check mark in these icons are different from the one used in `account-check` (brown)

![image](https://user-images.githubusercontent.com/44722574/176660604-1cda68b3-79b5-4948-a7f5-d00a81a9dd30.png)

**Comment by goyney** [comment]
[![message-check](https://materialdesignicons.com/icon/message-check)](https://materialdesignicons.com/icon/message-check)[![message-check-outline](https://materialdesignicons.com/icon/message-check-outline)](https://materialdesignicons.com/icon/message-check-outline)

Also fixed:
[![comment-check](https://materialdesignicons.com/icon/comment-check)](https://materialdesignicons.com/icon/comment-check)[![comment-check-outline](https://materialdesignicons.com/icon/comment-check-outline)](https://materialdesignicons.com/icon/comment-check-outline)
