### ISSUE TITLE
Consistent naming for icons with number

### ISSUE THREAD

**Issue by henriquecm** [Templarian/MaterialDesign#6683]
### What is your question?

I just saw that v7 will be released soon and with some breaking changes. So I thought it might be the right moment to make the icon name more consistent.

Some icons that have number on the name use the number and other use the word. I think should be renamed to use number to make them shorter.

Example:

- mdi-clock-time-one -> mdi-clock-time-1
- mdi-clock-time-two -> mdi-clock-time-2
- mdi-music-note-sixteenth -> mdi-music-note-16th
- mdi-two-factor-authentication -> mdi-2fa or mdi-2-factor-authentication
- mdi-star-three-points -> mdi-star-3-points

**Comment by goyney** [comment]
We only use numeric numbers in names when the number is actually in the glyph. Of those examples, none of them meet that criteria. However, we could stand to do a simple audit to see if we are breaking that rule elsewhere.

**Comment by Templarian** [comment]
We build packages for various languages, so no icon can start with a number. `two-factor-authentication`. Our naming validation will throw an error if someone tries. It's fine for aliases though.

**Comment by goyney** [comment]
It looks like we're good with following our rules. Thanks for the opportunity to check.
