### ISSUE TITLE
music-note-minus

### ISSUE THREAD

**Issue by Nisgrak** [Templarian/MaterialDesign#6685]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Remove some notes in a musical app, I have music-note-plus to add notes and not found a good icon to remove it

### Give us an example of what this icon might look like.

Like the actual icon that have a plus, but with a minus

![image](https://user-images.githubusercontent.com/19597708/177039721-1d5e5b24-c3a6-4708-8404-7d244a12e2ad.png)

https://materialdesignicons.com/icon/music-note-plus

**Comment by goyney** [comment]
[![music-note-minus](https://materialdesignicons.com/icon/music-note-minus)](https://materialdesignicons.com/icon/music-note-minus)
