### ISSUE TITLE
awning

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6687]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

There are a few closed requests for awnings, which ended up just using `storefront`. These new icons allow for more granularity on specific awning needs.

Referencing:

- https://github.com/Templarian/MaterialDesign/issues/3939
- https://github.com/Templarian/MaterialDesign/issues/4404

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/177199053-0e6c0a65-d0a3-44a0-a869-9e7930a099cf.png)
![image](https://user-images.githubusercontent.com/2228347/177199065-4d1bf5f0-d59e-4bd6-bd09-730199afab37.png)

### Upload the icon source.

[awning & awning-outline.zip](https://github.com/Templarian/MaterialDesign/files/9041311/awning.awning-outline.zip)

**Comment by jhil** [comment]
Referencing: 
- https://github.com/Templarian/MaterialDesign/issues/3939
- https://github.com/Templarian/MaterialDesign/issues/4404

**Comment by andrejsharapov** [comment]
I think it's very abstract 🤔 #6688 will be enough

**Comment by goyney** [comment]
This should also solve #6584 when added.

**Comment by goyney** [comment]
[![awning](https://materialdesignicons.com/icon/awning)](https://materialdesignicons.com/icon/awning)[![awning-outline](https://materialdesignicons.com/icon/awning-outline)](https://materialdesignicons.com/icon/awning-outline)
