### ISSUE TITLE
storefront variants

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6688]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

`storefront` and `storefront-outline` with variants `-check` `-plus` `-edit`

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/177201898-aecb3f01-1f55-4352-adda-7a9493a8d88a.png)
![image](https://user-images.githubusercontent.com/2228347/177201943-567d51af-7755-4f0f-93c6-635a0f7c12ea.png)
![image](https://user-images.githubusercontent.com/2228347/177201916-151304fc-7457-4251-ab34-50903367d3c3.png)
![image](https://user-images.githubusercontent.com/2228347/177201952-fb49dd6c-e080-4ae5-b144-3ee204adfe26.png)
![image](https://user-images.githubusercontent.com/2228347/177201936-916b7cf9-c44f-4556-be54-2e71992d0055.png)
![image](https://user-images.githubusercontent.com/2228347/177201966-d8d8d560-b0c0-479f-9337-07bc0e78cf20.png)

### Upload the icon source.

[storefront variants.zip](https://github.com/Templarian/MaterialDesign/files/9041419/storefront.variants.zip)

**Comment by goyney** [comment]
[![storefront-check](https://materialdesignicons.com/icon/storefront-check)](https://materialdesignicons.com/icon/storefront-check)[![storefront-check-outline](https://materialdesignicons.com/icon/storefront-check-outline)](https://materialdesignicons.com/icon/storefront-check-outline)[![storefront-edit](https://materialdesignicons.com/icon/storefront-edit)](https://materialdesignicons.com/icon/storefront-edit)[![storefront-edit-outline](https://materialdesignicons.com/icon/storefront-edit-outline)](https://materialdesignicons.com/icon/storefront-edit-outline)[![storefront-plus](https://materialdesignicons.com/icon/storefront-plus)](https://materialdesignicons.com/icon/storefront-plus)[![storefront-plus-outline](https://materialdesignicons.com/icon/storefront-plus-outline)](https://materialdesignicons.com/icon/storefront-plus-outline)
