### ISSUE TITLE
Bookmark Box Multiple vs Book Variant Multiple

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6689]
### What is your question?

It looks like [`bookmark-box-multiple`](https://materialdesignicons.com/icon/bookmark-box-multiple) and [`book-variant-multiple`](https://materialdesignicons.com/icon/book-variant-multiple) are the same icon.

[![bookmark-box-multiple](https://materialdesignicons.com/icon/bookmark-box-multiple)](https://materialdesignicons.com/icon/bookmark-box-multiple) [![book-variant-multiple](https://materialdesignicons.com/icon/book-variant-multiple)](https://materialdesignicons.com/icon/book-variant-multiple)

**Should we keep both or get rid of one?**

I propose getting rid of `book-variant-multiple` since it looks like Google (and us with `bookmark-box`) have chosen to build out the `bookmark` icon series instead of introducing a `book-variant` series.

**Comment by goyney** [comment]
I agree. This is also a good time to catch stuff like this since we are able to make breaking changes during the runoff to v7.

**Comment by goyney** [comment]
We'll remove `book-variant-multiple` in this issue.

**Comment by goyney** [comment]
Removed.
