### ISSUE TITLE
Playstation controller buttons icons

### ISSUE THREAD

**Issue by DavidCeliis** [Templarian/MaterialDesign#6693]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would like to use them for HASS.  For example, if I want to send a command to press a certain button.  It would be useful for more people because the library doesn't have xbox buttons either.

### Give us an example of what this icon might look like.

I imagine the button from the PS controller in a circle.  Exactly as it is on the controller itself. The basic 5 would definitely be enough: PS, X, circle, square, triangle.

**Comment by goyney** [comment]
We have the basic shapes:
[![circle-outline](https://materialdesignicons.com/icon/circle-outline)](https://materialdesignicons.com/icon/circle-outline)[![close](https://materialdesignicons.com/icon/close)](https://materialdesignicons.com/icon/close)[![square-outline](https://materialdesignicons.com/icon/square-outline)](https://materialdesignicons.com/icon/square-outline)[![triangle-outline](https://materialdesignicons.com/icon/triangle-outline)](https://materialdesignicons.com/icon/triangle-outline)

We also currently have the PlayStation logo, but I wouldn't use or rely on it as it is [being removed in v8](https://github.com/Templarian/MaterialDesign/issues/6602).

As far as shapes inside circles, that seems very niche and I don't think it is something we're interesting in adding.
