### ISSUE TITLE
farmhouse / home-farm / home-silo

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6696]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Farm version of the `home-city` icon. Not sure if the right name is farmhouse or home-farm or home-silo.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/178123536-f9496351-115e-4b80-a5f6-1552d66033d5.png)
![image](https://user-images.githubusercontent.com/2228347/178123511-030fb555-2f31-439b-9cc2-53f3c71e7489.png)

### Upload the icon source.

[home-farm.zip](https://github.com/Templarian/MaterialDesign/files/9077974/home-farm.zip)

**Comment by goyney** [comment]
home-silo since home is the base.

**Comment by goyney** [comment]
[![home-silo](https://materialdesignicons.com/icon/home-silo)](https://materialdesignicons.com/icon/home-silo)[![home-silo-outline](https://materialdesignicons.com/icon/home-silo-outline)](https://materialdesignicons.com/icon/home-silo-outline)
