### ISSUE TITLE
account-card / account-credit-card (cardholder)

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6697]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I need an icon for cardholder, so made these! Inspired by account-cash.

### Share a preview of your contribution.

<img width="871" alt="Screenshot 2022-07-10 at 21 41 40 from Figma" src="https://user-images.githubusercontent.com/2228347/178173144-6bcbfc18-7747-4059-96c9-3e46167dd513.png">
(sorry, preview generator not working again)	

### Upload the icon source.

[Archive.zip](https://github.com/Templarian/MaterialDesign/files/9080332/Archive.zip)

**Comment by goyney** [comment]
What are you using to create your SVGs? Anytime the preview generator doesn't work, it means I need to reopen and fix the glyphs because something is wrong with them before I can add them.

**Comment by goyney** [comment]
In this case, it looks like you didn't combine the paths down to a single one.
![image](https://user-images.githubusercontent.com/1015040/178329846-7975455b-1529-4428-9c7f-843e30d81d39.png)

**Comment by goyney** [comment]
[![account-card](https://materialdesignicons.com/icon/account-card)](https://materialdesignicons.com/icon/account-card)[![account-card-outline](https://materialdesignicons.com/icon/account-card-outline)](https://materialdesignicons.com/icon/account-card-outline)[![account-credit-card](https://materialdesignicons.com/icon/account-credit-card)](https://materialdesignicons.com/icon/account-credit-card)[![account-credit-card-outline](https://materialdesignicons.com/icon/account-credit-card-outline)](https://materialdesignicons.com/icon/account-credit-card-outline)

**Comment by jhil** [comment]
> What are you using to create your SVGs? Anytime the preview generator doesn't work, it means I need to reopen and fix the glyphs because something is wrong with them before I can add them.

I am using Figma. Gah! It's frustrating because Figma shows this as a single unioned, flattened vector. It inconsistently exports. I will talk to Figma Support about this.

Sorry for the trouble!
