### ISSUE TITLE
Barcode scanner icons

### ISSUE THREAD

**Issue by macu** [Templarian/MaterialDesign#670]
Request for Bluetooth barcode scanner icons for indicating when connected and disconnected.

**Comment by CoDEmanX** [comment]
Hm, hardly distinguishable from an electric shaver or a blow-drier if you shrink it to 20px I'm afraid

![Imgur](http://i.imgur.com/X56OR7B.jpg?1)

**Comment by macu** [comment]
xD I went looking for the blowdryer icon. There is a huge variety in scanner form factors, so it's tough to imagine a general icon, but there are a lot of enterprise apps supporting peripheral scanners. Common elements are the scan trigger, scan ray, and photo sensor.

**Comment by CoDEmanX** [comment]
Scan ray sounds interesting...
This is a more simplistic scanner btw, not sure how it would look at 20px though:
https://cdn1.iconfinder.com/data/icons/ios7-active-2/512/Barcode_scanner.png

**Comment by CoDEmanX** [comment]
Ah well, hair-drier is not really working either:
![hair-drier](https://cloud.githubusercontent.com/assets/1309249/9776611/8bff513a-575a-11e5-8a55-575498636bbf.png)

**Comment by CoDEmanX** [comment]
Maybe this works for you?
![barcode-scanner-off](https://cloud.githubusercontent.com/assets/1309249/9776831/05c98696-575d-11e5-9529-b8b62d7a6d13.png)
![barcode-scanner](https://cloud.githubusercontent.com/assets/1309249/9776830/05c61e5c-575d-11e5-9f0f-f33faf3e6dc8.png)
I can send you the SVGs if you want.

**Comment by macu** [comment]
Thanks for taking a crack at this! But I'm going with a text label for now, and see what icons the future yields. We can close this request.

The scanners our customers use look more like this: http://us.ute.com/products.php?rbu=5&pc1=49&pc2=354

**Comment by CoDEmanX** [comment]
They look like remote controls for message chairs :D

Closing as requested.
