### ISSUE TITLE
account tag

### ISSUE THREAD

**Issue by mat2718** [Templarian/MaterialDesign#6700]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

im currently working on an application for U.S. Customs and Border Patrol and they would like an icon for adding tags to people. the attached icons would be used in the application. 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/22265388/178592864-39a55fc4-7857-4ee8-a5e0-5ccac66b8360.png)
![image](https://user-images.githubusercontent.com/22265388/178593902-e06c5315-5e9c-431e-9397-eb8584c58e99.png)

### Upload the icon source.
[account-tag (2).zip](https://github.com/Templarian/MaterialDesign/files/9096797/account-tag.2.zip)

**Comment by mat2718** [comment]
Any updates on if this is approved or not?

**Comment by mat2718** [comment]
@Templarian is this approved yet?

**Comment by mririgoyen** [comment]
It'll be added when we get to it. We generally slow down quite a bit after a major release.

**Comment by mririgoyen** [comment]
[![account-tag](https://materialdesignicons.com/icon/account-tag)](https://materialdesignicons.com/icon/account-tag)[![account-tag-outline](https://materialdesignicons.com/icon/account-tag-outline)](https://materialdesignicons.com/icon/account-tag-outline)
