### ISSUE TITLE
patient icon

### ISSUE THREAD

**Issue by repo-wiseacre** [Templarian/MaterialDesign#6703]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

patient icon can be used for many medical websites
![modules_PMI-2898347454](https://user-images.githubusercontent.com/8871305/178975121-14a06df6-2b54-43c4-a75a-d2fd47f40613.png)

### Give us an example of what this icon might look like.

icons can be like
![516749-200-1662654346](https://user-images.githubusercontent.com/8871305/178975315-b0d8585f-71be-4271-a4eb-d39d70251c5b.png)

**Comment by goyney** [comment]
Already exists as `account-injury`. We should add the alias "patient".

**Comment by Templarian** [comment]
Added. 👍
