### ISSUE TITLE
Modify the source-merge icon to match history flow

### ISSUE THREAD

**Issue by PulsarFX** [Templarian/MaterialDesign#6704]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

Currently `source-merge` looks like this:
![grafik](https://user-images.githubusercontent.com/4960210/179291015-c1a7a835-6fe3-4b42-af7e-7fcd5ee3548a.png)

whereas `source-branch` looks like this:
![grafik](https://user-images.githubusercontent.com/4960210/179291094-fce7d44f-9da6-4629-8392-8f12fe9a7379.png)

From what the git tools usually paint in their log graphs, I suggest to modify `source-merge` to have a convex joint instead of a concave one, so it would look like this:
![grafik](https://user-images.githubusercontent.com/4960210/179291655-7a60c4e3-a8b4-4aeb-aabe-d87dcbd0c626.png)

On a small scale, the merge icon looks awkward next to the branch icon:
![grafik](https://user-images.githubusercontent.com/4960210/179292121-cee6f1b1-1a03-4731-bd7b-799745642859.png)

Examples from git tools which show a branching and a merging action (bottom to top):
![grafik](https://user-images.githubusercontent.com/4960210/179291399-be369d26-1c43-4e3e-8c49-0884886481f9.png) ![grafik](https://user-images.githubusercontent.com/4960210/179291810-8d34b656-e4d0-4733-8405-e494a9863813.png)

**Comment by Templarian** [comment]
Agreed the readability at 1:1 could be improved by this change. 👍

**Comment by goyney** [comment]
To play devil's advocate, we've rejected requests many times in the past when the simple answer is to just apply a transform to an existing icon. Both of these icons have been around since `v1`, do we really want to change them?

I think my vote would be to transform `source-branch` to flip it into the orientation you'd like it to be in and leave what we have alone.

**Comment by Templarian** [comment]
https://www.bing.com/images/search?q=git+merge+icon&form=HDRSC2&first=1&tsc=ImageHoverTitle

Looks like most do look like the one we have.

**Comment by PulsarFX** [comment]
Just flipping an icon with a different name (you would have to flip `source-branch` and use it as replacement for `source-merge`) would work for primary consumers which can change the code to their like. But this is not possible for endusers who simply select an icon from a dropdown list, like it is done for example in home assistant.

For the image search: you will get different results on different search engines. Try the same on startpage for example ;-)
I think it's more a matter of taste and legibility if it is a concave or convex joint.

**Comment by goyney** [comment]
As @Templarian has pointed out, we are following the trend with the version of the icon we have. We don't typically rotate or transform existing glyphs and add them, especially when doing so would result in an almost identical glyph we already have.

In terms of third-parties utilizing our library, it would be on them to allow the functionality of transforming an icon to achieve this. In the case of Home Assistant, you would need to open a [Feature Request](https://community.home-assistant.io/c/feature-requests/13) with them or you could potentially use [card-mod](https://community.home-assistant.io/t/card-mod-add-css-styles-to-any-lovelace-card/120744).

As it stands now, I don't think we're going to make this change.
