### ISSUE TITLE
Google's Material 'logout' icon

### ISSUE THREAD

**Issue by gabrielatapaleo** [Templarian/MaterialDesign#6712]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Log out

There are alternatives in mdi but none of them is the real google icon for logging out.

### Give us an example of what this icon might look like.

<img width="146" alt="image" src="https://user-images.githubusercontent.com/109596872/180010332-eb36ece2-1ad6-4f9a-831f-c50ea7d71a2d.png">

https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Alogout%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048

**Comment by goyney** [comment]
Material Symbols are not the same as Material Icons. They follow different standards and rules, to my knowledge.

That being said, I'm not opposed to adding a Materialized version of this.

**Comment by gabrielatapaleo** [comment]
@goyney I think they are material symbols, at least is implicit in the code.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/109596872/180015781-b294250d-5ef6-4ccf-a493-2d4dd9915c7a.png">

**Comment by gabrielatapaleo** [comment]
What do you mean?

Material symbols and material icons are material elements, their are based on the same fundamental design guidelines.

an in the same way, this is an icon which happens to be a symbol in the technical code, but it is still a logout icon. right?

**Comment by goyney** [comment]
The Symbols library is more of a "light" version of the standard System Icons spec, allowing strokes of less than 2dp. For our library, we will always follow the guidelines for Material Design System Icons, which requires a 2dp stroke.

That being said, they have the same icon the the Icons library with the appropriate stroke. This is probably a case were we will update out current logout and login icons to use the new Google design, replacing what is already in the library. We already have a variant of each and we don't need 3 different login/logout icons.

**Comment by gabrielatapaleo** [comment]
@goyney Can you share with me the link to the Material Design System Icons guidelines that you are mentioning?

**Comment by gabrielatapaleo** [comment]
Also, I'm not finding the loggout icon in the library. I only found this two which are not google's oficial material icon.
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/109596872/180154939-e0fba0df-2488-4534-b8b8-b1f8985ece95.png">

The one I need is the [oficial one](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Alogout%3A) for a project that must use google's material icon but they are also consuming them through https://materialdesignicons.com/
![outline_logout_black_24dp](https://user-images.githubusercontent.com/109596872/180155755-2103b6fe-7415-40e8-a606-32d069388551.png)

Can you share me the link to this one?

**Comment by mririgoyen** [comment]
These have been updated and will ship in v7.3.
