### ISSUE TITLE
cash-off

### ISSUE THREAD

**Issue by ElLutzo** [Templarian/MaterialDesign#6713]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

May we have a `cash-off` icon, please? I.e. a striked out dollar bill.
For example to indicate that all payments are suspended.

In #4513 `cash-plus` and `cash-minus` were added.
There is a `cash-remove`.
There are `currency-usd-off` and `currency-eur-off`.

### Give us an example of what this icon might look like.

dollar bill off

**Comment by andrejsharapov** [comment]
Maybe [this icon](https://materialdesignicons.com/icon/cash-remove) can help you.

But I can suggest use this

![image](https://user-images.githubusercontent.com/44722574/180219206-0d6c6149-5a12-465f-8b4c-49d5f3c6f8d5.png)

And I also made two `-off` icons for `account-cash`. Perhaps they will suit you in the future.
![image](https://user-images.githubusercontent.com/44722574/180219426-028fe8ba-d9ca-4ed0-8d97-d457d3cc9ffe.png) ![image](https://user-images.githubusercontent.com/44722574/180219449-7c22697b-8b1d-44e2-872e-f7b9a0df4754.png)

[cash-off.zip](https://github.com/Templarian/MaterialDesign/files/9159541/cash-off.zip)

**Comment by goyney** [comment]
I vote no to the account-cash icons. They're way too busy and we don't typically do double modifiers.

**Comment by ElLutzo** [comment]
@andrejsharapov Yes, I have seen https://materialdesignicons.com/icon/cash-remove
Could be an option, but I wanted more of the indication, that there will be no (more) money.
So your cash-off draft looks quite right, thank you.
And I agree with @goyney double modifiers make the icons a bit overcrowded.

**Comment by ElLutzo** [comment]
@andrejsharapov How can we proceed with this Issue?

**Comment by andrejsharapov** [comment]
We need to wait for @mririgoyen answer

**Comment by ElLutzo** [comment]
bump:

@mririgoyen Can you set the "Contribution" label, please?

**Comment by ElLutzo** [comment]
Thank you, @mririgoyen and @andrejsharapov !
Done. :)

**Comment by mririgoyen** [comment]
Please do not close issues. We will once the icon is added.

**Comment by ElLutzo** [comment]
Sorry.

**Comment by tetzla** [comment]
In which release will this icon be included?

**Comment by jhil** [comment]
Added this! Only changes were some minor vector details.

<img width="557" alt="Screenshot 2023-02-28 at 20 33 10 from Figma" src="https://user-images.githubusercontent.com/2228347/222038559-b561c328-0193-4041-9976-fd392b194b5a.png">


[![cash-off](https://pictogrammers.com/library/mdi/icon/cash-off)](https://pictogrammers.com/library/mdi/icon/cash-off)
