### ISSUE TITLE
Gaule's subs helmet

### ISSUE THREAD

**Issue by pepz1n** [Templarian/MaterialDesign#6714]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Cause GauGau is a legend for brasilianz

### Give us an example of what this icon might look like.

![índice](https://user-images.githubusercontent.com/62623459/180274048-af901c61-4f5f-4c68-a8b5-26023cefd475.png)

**Comment by goyney** [comment]
From a [Google search](https://lens.google.com/search?p=AS3Fu8prEnHNormFF3q0yEON4q1p7wLm3FN5nHNUFaEZ8IZw-HSYKXQaDgS6Q2QRFAAtOQIC9yluAOx9k_P0XEAwgwb55Jdjuan-lvGf9TX37gDEa2YG_BFoPCzPEagX2bPhB-NgVI1CHgdNcNnO7NzvaLTWZRKyByAwtY5xfE8CNAYLHB4DBKIKLCXGrBI_VUdAG6JGYiNFz4I68_1ocEgTPyYbGrRyPhuLJuH9XnO9ji_vdoy_moBqPAoa0yTQmQUKBZf-OtXQ-bO067zU-FhMf0Rex_84Ezh_IgPvGh0WzVzBakelJhH2DUFlqDXagvhQH7_EpXubG5DQj74-eqsLV6ZwTsNOWJuS9atmRBUpGr7NHg%3D%3D&s&ep=cnts&pli=1#lns=W251bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsIkVrY0tKREkzT0RVME1UaGtMVGRtT1RFdE5EZGlNaTA1TldObExUUmlNRFExWWpRNU5XSm1OQklmTkRGNFgybHZkRUZVVFdkaVJVWkRjWGQ0VEhKTVVEUmhNMnhTUVVsb1p3PT0iXQ==), this request looks like it is asking us to add an icon from a Twitch streamer.

Unfortunately, this is not something we are interested in doing.
