### ISSUE TITLE
Ethernet Off

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6715]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I have a situation in my app where ethernet is sometime available or sometimes unavailable based on whether the hardware device has a modular ethernet port installed or not. It would be great to have an `ethernet-off` icon based on [`ethernet`](https://materialdesignicons.com/icon/ethernet)

### Share a preview of your contribution.

![ethernet-off](https://user-images.githubusercontent.com/1837101/180276643-70ca248a-3490-44a8-bffd-e00c8cd8b4a3.png)

### Upload the icon source.

[ethernet-off.svg.zip](https://github.com/Templarian/MaterialDesign/files/9161516/ethernet-off.svg.zip)

**Comment by jhil** [comment]
[![ethernet-off](https://pictogrammers.com/library/mdi/icon/ethernet-off)](https://pictogrammers.com/library/mdi/icon/ethernet-off)
