### ISSUE TITLE
mdi-discord missing

### ISSUE THREAD

**Issue by Ghost0159** [Templarian/MaterialDesign#6717]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

Hello, I don't know if this is a bug, but the discord icon is not available anymore.

**Comment by goyney** [comment]
It was removed in v7. Please check the [changelog](https://dev.materialdesignicons.com/changelog) before updating in the future to see potential breaking changes. We typically save breaking changes, such as removals, for major versions.

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one removed.



[2]: https://simpleicons.org/

**Comment by Templarian** [comment]
For context: #6564
