### ISSUE TITLE
Forgot password

### ISSUE THREAD

**Issue by MB34** [Templarian/MaterialDesign#672]
Let me try to explain.

Form Field with 3 dots and ? in circle to bottom right that symbolizes a forgot password.
See this:
![f_p](https://cloud.githubusercontent.com/assets/377196/9775224/53490e90-5713-11e5-869e-e7541d052b9c.png)

**Comment by CoDEmanX** [comment]
How is this?
![password-lost](https://cloud.githubusercontent.com/assets/1309249/9828107/82417ab6-58e9-11e5-9af5-54fcb93eb15a.png) https://www.dropbox.com/s/7d4xjos9ifkmln3/password-lost.svg?dl=0

**Comment by CoDEmanX** [comment]
This is probably better, same question mark as in #819:
![forgot-password](https://cloud.githubusercontent.com/assets/1309249/11659716/e9d30dbe-9dc9-11e5-8722-4bcbcf5bf366.png) https://www.dropbox.com/s/3j6b68ta85f9g8l/forgot-password.svg?dl=0

**Comment by Ch-Lo** [comment]
I think adding a lock-check for , e.g. secure password, would also be a good addition.

**Comment by PeterShaggyNoble** [comment]
@Ch-Lo, could you open a new issue for that, please?

**Comment by Templarian** [comment]
[![lock-alert](https://materialdesignicons.com/icon/lock-alert)](https://materialdesignicons.com/icon/lock-alert) [![lock-question](https://materialdesignicons.com/icon/lock-question)](https://materialdesignicons.com/icon/lock-question)

**Comment by Templarian** [comment]
The alias `forgot-password` was also added.
