### ISSUE TITLE
View-Grid-Small

### ISSUE THREAD

**Issue by DrCQ** [Templarian/MaterialDesign#6720]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need to implement a "resize" control, consisting of two buttons (up, down) and a slider in the middle. For up-button I use the View-Grid PackIcon, but for the down-button I need a PackIcon with 9 elements instead of 4. I created a GeometryDrawing representing it:
<GeometryDrawing Brush="{DynamicResource MaterialDesignBody}" 
                                             Geometry="M3,3 H8 V8 H3 M9.5,3 H14.5 V8 H9.5 M16,3 H21 V8 H16 
                                                       M3,9.5 H8 V14.5 H3 M9.5,9.5 H14.5 V14.5 H9.5 M16,9.5 H21 V14.5 H16
                                                       M3,16 H8 V21 H3 M9.5,16 H14.5 V21 H9.5 M16,16 H21 V21 H16" />
I will appreciate if this icon could be added to the next release. 

### Give us an example of what this icon might look like.

![grafik](https://user-images.githubusercontent.com/49019093/180652687-ac8109e6-d5df-42e9-8764-1ad9ed6a564f.png)

**Comment by Templarian** [comment]
This is the `apps` icon by the way. 🤔

@goyney What do you think about this one. Should it have a more general name?

**Comment by Templarian** [comment]
Switching this to a label since the icon exists, but might need additional work.

**Comment by DrCQ** [comment]
Thanks. I didn't find it directly. A new alias with "grid" in the name would help.
Thanks for fast response.

**Comment by DrCQ** [comment]
I close it.
