### ISSUE TITLE
success icon

### ISSUE THREAD

**Issue by mingxin-yang** [Templarian/MaterialDesign#6724]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

when a file upload success

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/23076937/180981841-4deb1647-e8f7-4154-96c3-95f7a35ddf2b.png)

**Comment by Templarian** [comment]
Already exists... `check-circle-outline`.

[![check-circle-outline](https://materialdesignicons.com/icon/check-circle-outline)](https://materialdesignicons.com/icon/check-circle-outline)
