### ISSUE TITLE
Fridge(s) with open door

### ISSUE THREAD

**Issue by IgnacioHR** [Templarian/MaterialDesign#6727]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In Home Automation system, I’ve develop a device that monitor when the fridge door is open (or closed) there are icons for fridge closed door state and for fridge in alert state, but I’ve not seen any with the door open.

I’m specifically interested in a version of industrial fridge open (the one with a single big door) as it matches best the one I’ve at home

### Give us an example of what this icon might look like.

The door might be open 45º so it is seen as rotating from the right side of the fridge. It is not required to see the fridge content :) if open 90º or more, the fridge size would be compromised so that’s why I suggest to use partially open drawing

**Comment by goyney** [comment]
You will need to use the filled and outlined variants to accomplish your use case. There are specifically `fridge-top` and `fridge-bottom` to indicate compartment or door status. We cannot add doors at angles because it goes against [Material guidelines](https://material.io/design/iconography/system-icons.html#design-principles).
