### ISSUE TITLE
collapse-top

### ISSUE THREAD

**Issue by pme-odoo** [Templarian/MaterialDesign#673]
I have seen that collapse icon is available but collapse-top icon is missing.
This icon will use for the fade-in.

Icon is like this : https://fontawesome.com/v3.2.1/icon/collapse-top/

**Comment by CoDEmanX** [comment]
So triangle in a box, possible 4 icons for all 4 directions?

**Comment by goyney** [comment]
This sounds like it will be handled in https://github.com/Templarian/MaterialDesign/issues/3244.

**Comment by PeterShaggyNoble** [comment]
Agreed. Closing here.
