### ISSUE TITLE
Landscape Lighting Spotlight

### ISSUE THREAD

**Issue by Neekster** [Templarian/MaterialDesign#6730]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'm installing some low voltage landscape lighting in my back yard, and I'm working to integrate it into HomeAssistant. I'd love to have an icon to depict them accurately and allow for more intuitive control.

### Give us an example of what this icon might look like.

I'm thinking something along the lines of mdi:track-light, but upside down and pointed up a bit more. Maybe also a longer stake? Pardon my atrocious design skills, but something like this:
![image](https://user-images.githubusercontent.com/58367045/181994602-a0890f54-1023-47c9-b419-4944e2d94f79.png)

For the product image, here's one that I found on Amazon: [https://www.amazon.com/LEONLITE-Landscape-Adjustable-Waterproof-WhiteAluminum/dp/B07JQHHRLF](url)
![image](https://user-images.githubusercontent.com/58367045/181994445-2d8dedd1-0c55-4257-9212-4a193d387ed6.png)

**Comment by goyney** [comment]
Not an exact duplicate, but similar enough to #5295. Let's merge them into one issue. Closing this one in favor of that.

**Comment by Neekster** [comment]
Similar, but different. I would still like to see separate icons for the pagoda and spot landscape light varieties.
