### ISSUE TITLE
Failed to decode downloaded font

### ISSUE THREAD

**Issue by adamkovari** [Templarian/MaterialDesign#6731]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

Meteor + Vue + Vuetify environment

I've imported in main.js

``` js
import '@mdi/font/css/materialdesignicons.css'
```

Failed to decode downloaded font, OTS parsing error invalid sfntversion: 1008813135

![image](https://user-images.githubusercontent.com/62180388/182032267-449efb02-31a1-46df-b6a0-a4b3b3c33dcb.png)

**Comment by Templarian** [comment]
@adamkovari Does the preview work here: https://pictogrammers.github.io/@mdi/font/7.0.96/

Could be a server configuration issue?

**Comment by adamkovari** [comment]
@Templarian do you mean this <span class="mdi mdi-name"></span> ?

Could be... however I did everything as the documentation says!

This is the project repo https://github.com/adamkovari/rock-solid.gg

**Comment by Templarian** [comment]
@adamkovari I would look around the support channels for the framework. It should be working. Maybe it's a config issue. If you do find a solution post it in this thread for others that may run into it.

By the way you really should not be using `@mdi/font`:
- https://dev.materialdesignicons.com/guide/webfont-alternatives
- https://dev.materialdesignicons.com/getting-started/vuejs (this is made by one of the Core MDI contributors)

I'm going to close this issue as it's too niche for us to help debug.

**Comment by adamkovari** [comment]
@Templarian yes, the @mdi/js pack works fine, however I don't really understand @mdi/font why not.
Just an add, font files produce the same problem, if they aren't stored in /public folder. When they are, @font-face works perfectly!
Unfortunately I don't have enough experience to know the answer for why.
Thanks for help!
