### ISSUE TITLE
Minecraft icon no longer accurate by the new brand standards

### ISSUE THREAD

**Issue by quiquelhappy** [Templarian/MaterialDesign#6738]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

The [minecraft icon](https://materialdesignicons.com/icon/minecraft) is no longer loyal to Minecraft's design language: the rounded corners make it completely off. The corners should be squared off ending in a sharp corner, as seen on [Minecraft's website overall style](https://www.minecraft.net/) or the [game icon itself](https://www.microsoft.com/store/productId/9PGW18NPBZV5).

I know brand icons are no longer being added but I'm guessing existing ones are still being maintained.

**Comment by mririgoyen** [comment]
We won't be updating this as it is being removed in v8. See #6602.
