### ISSUE TITLE
collapse-bottom

### ISSUE THREAD

**Issue by pme-odoo** [Templarian/MaterialDesign#674]
I have seen that collapse icon is available but collapse-top icon is missing.
This icon will use for the fade-out.

link : https://fontawesome.com/v3.2.1/icon/collapse/

**Comment by goyney** [comment]
Possible to be the same as https://github.com/Templarian/MaterialDesign/issues/673. Might be addressed with https://github.com/Templarian/MaterialDesign/issues/3244.
