### ISSUE TITLE
Icons relevant to stair and landing indicating the floor association

### ISSUE THREAD

**Issue by IliasEagle** [Templarian/MaterialDesign#6745]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have two flights of stairs and a landing in between 
![image](https://user-images.githubusercontent.com/93916516/184119111-afaa90b8-5e6a-4c2f-8d32-9e4b6f07c4f9.png)
where I have installed LED strips along the stairs and landing in my house and would like to have in Home Assistant meaningful icons 

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/93916516/184119201-368c943c-75e5-4040-9c4f-906fb6fe91af.png)

**Comment by mririgoyen** [comment]
This is extremely niche and overly literal for a small icon. I don't think this is something we'd be interested in adding.
