### ISSUE TITLE
Chiller Cabinet

### ISSUE THREAD

**Issue by Builder-DE-TH** [Templarian/MaterialDesign#6747]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For use in Home Assistant

### Give us an example of what this icon might look like.

![chiller cabinet](https://user-images.githubusercontent.com/109861242/184607684-f9d5baff-32b8-4f06-abb4-f0ea177e936e.png)

**Comment by Circeus** [comment]
Can you clarify with pictures of the real world element? The image looks like a vending machine. And if you mean refrigerated displays like you'd find in a grocery store, it's not clear if you want something with a door or open-faced.

**Comment by Builder-DE-TH** [comment]
![tu-mat-sanaky-inverter-vh-308k3l-org-0](https://user-images.githubusercontent.com/109861242/185355565-18b4bd8c-b349-4c92-95b2-6beb8b2b8208.jpg)

They have a glass door.

**Comment by mririgoyen** [comment]
There is no way this happens in the 24x24 artboard we have available to us. There is too much detail required to depict it.

My recommendation is to use one of the refrigerator icons. Thanks for the suggestion.
