### ISSUE TITLE
file type unknown icon

### ISSUE THREAD

**Issue by jayrave** [Templarian/MaterialDesign#675]
may be ![file](https://cloud.githubusercontent.com/assets/3953470/9823060/e35d83f6-5878-11e5-9715-fdd9928a6ac9.png) with ![help 1](https://cloud.githubusercontent.com/assets/3953470/9823068/ef55d8fc-5878-11e5-8c48-d00de3c6b822.png) inside it

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33990489-119535b4-e0c3-11e7-8824-59311361b22f.png)]((https://github.com/Templarian/MaterialDesign/files/1559007/file-question.zip)

**Comment by JamesCoyle** [comment]
The question mark doesn't really seem to fit with the font we tend to use on icons with text content. Might look better in that geometric font style.

**Comment by GreenTurtwig** [comment]
It's what @CoDEmanX made up for use in `comment-question`. https://github.com/Templarian/MaterialDesign/issues/819

It generally looks nicer than the geometric font. As seen in https://github.com/Templarian/MaterialDesign/issues/672.

**Comment by JamesCoyle** [comment]
Most curves in MD are arcs of a circle so to me that question mark looks out of place. The geometric one does look too square though... I think the one we use in the help icons would probably be best.

**Comment by GreenTurtwig** [comment]
`help-network` uses the same style as above. The Google help icons have the better design, however it's a bit too large for small locations like this without resizing to 3/4 its size and thus loosing detail at 1x. Anyhow, this is how it looks:
[![](https://user-images.githubusercontent.com/15905797/33996432-13728c86-e0d9-11e7-90a3-c79c6c2d31b9.png)](https://github.com/Templarian/MaterialDesign/files/1559475/file-question2.zip)

**Comment by Templarian** [comment]
[![file-question](https://materialdesignicons.com/icon/file-question)](https://materialdesignicons.com/icon/file-question)
