### ISSUE TITLE
Icon for home floors (basement, ground floor, 1st floor, etc)

### ISSUE THREAD

**Issue by Cikkajes** [Templarian/MaterialDesign#6753]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To be used in Home Assistant

### Give us an example of what this icon might look like.

a house icon with a '-1', 'G', '1', '2', etc.

**Comment by mririgoyen** [comment]
These already exist. Please search.
