### ISSUE TITLE
Contribute Page Guidelines Dead Link

### ISSUE THREAD

**Issue by DankRadon** [Templarian/MaterialDesign#6756]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

On this page: [https://dev.materialdesignicons.com/contribute#contribute-icons](https://dev.materialdesignicons.com/contribute#contribute-icons) ...
The "Material Design guidelines" link ([https://material.io/design/style/icons.html#icons-system-icons](https://material.io/design/style/icons.html#icons-system-icons)) is dead.
This looks like the new location: [https://material.io/design/iconography/system-icons.html](https://material.io/design/iconography/system-icons.html)

**Comment by mririgoyen** [comment]
Thanks. I've made the change and it'll propagate out shortly.
