### ISSUE TITLE
rename & rename-outline (no box)

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#6758]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Reviving this issue: https://github.com/Templarian/MaterialDesign/issues/1055

I'd like to add a no-box version of [rename-box](https://materialdesignicons.com/icon/rename-box)

My reasoning:

- "pencil with line" is a common convention for "Rename" (e.g. Google Drive, Box.com)
- … but the box in [rename-box](https://materialdesignicons.com/icon/rename-box) adds additional detail that is often unnecessary
- attached: filled & outline proposals, based on Google's [drive_file_rename_outline](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Adrive_file_rename_outline%3A)
- [form-textbox](https://materialdesignicons.com/icon/form-textbox) is _another_ popular convention for "Rename", [as suggested by Templarian](https://github.com/Templarian/MaterialDesign/issues/1055#issuecomment-187543903)—but not quite yet an 'uncontested standard', so I think it would be good to offer various options

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/55925048/186149152-a5dfd072-9621-4f31-a7be-afa19db30da7.png)
![image](https://user-images.githubusercontent.com/55925048/186149222-7b4d4f81-bf09-4b69-ac7c-1df9273279b5.png)

### Upload the icon source.

[rename.zip](https://github.com/Templarian/MaterialDesign/files/9402167/rename.zip)

**Comment by mririgoyen** [comment]
Unfortunately, I have to assign these to Google since there are currently in their library. Got them added though!

[![rename](https://materialdesignicons.com/icon/rename)](https://materialdesignicons.com/icon/rename)[![rename-outline](https://materialdesignicons.com/icon/rename-outline)](https://materialdesignicons.com/icon/rename-outline)

Also added this missing `rename-box-outline`:
[![rename-box-outline](https://materialdesignicons.com/icon/rename-box-outline)](https://materialdesignicons.com/icon/rename-box-outline)
