### ISSUE TITLE
Playlist icon

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#676]
I came across this cool icon for a playlist. I asked the original designer if I could propose it here :)
![playlist](https://cloud.githubusercontent.com/assets/11229646/9825467/6109b926-58cb-11e5-8615-01325828fd7f.png)
![permission](https://cloud.githubusercontent.com/assets/11229646/9825498/8deae99c-58cb-11e5-9d08-34d1954dfe36.png)

**Comment by CoDEmanX** [comment]
![playlist](https://cloud.githubusercontent.com/assets/1309249/9827561/a98aec02-58e3-11e5-97c1-3411557e9ec5.png) like this? https://www.dropbox.com/s/oquo00dnj9qhh2d/playlist.svg?dl=0

![playlist-delete](https://cloud.githubusercontent.com/assets/1309249/9827562/a992dd18-58e3-11e5-878b-fba9326168ca.png) variant of playlist-minus https://www.dropbox.com/s/atsgdl66avphan9/playlist-delete.svg?dl=0

**Comment by keunes** [comment]
yup :)

**Comment by keunes** [comment]
Actually compared to the playlist and playlist-minus/plus (by Google), it feels like the cross should be a little bit closer to the lines (there's to much white space); kinda like a bit more inside the square area of the three list lines, if you get what I mean.

**Comment by Templarian** [comment]
[![playlist-play](https://materialdesignicons.com/icon/playlist-play)](https://materialdesignicons.com/icon/playlist-play) [![playlist-remove](https://materialdesignicons.com/icon/playlist-remove)](https://materialdesignicons.com/icon/playlist-remove)
