### ISSUE TITLE
Call bell

### ISSUE THREAD

**Issue by ArielZabihi** [Templarian/MaterialDesign#6761]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would use it for a contact us page or a customer service page. I don't see a specialized icon for this purpose. In the past I've used stuff like `mdi-phone` or `mdi-email` but I think a call bell icon would be a more elegant solution.

### Give us an example of what this icon might look like.

I quick Google search gave me these examples:

![png-transparent-computer-icons-call-bell-icon-design-customer-service-hotel-hat-black-silhouette](https://user-images.githubusercontent.com/30534360/186494181-74d59347-d580-4b92-8b83-65db4ba6dd10.png)
![634989](https://user-images.githubusercontent.com/30534360/186494249-6878737f-c8cb-4111-a0cc-612fbf1a0acf.png)
![1828519-200](https://user-images.githubusercontent.com/30534360/186494282-0f0c0a91-9f22-4b39-9abb-e5a67f881f06.png)

**Comment by mririgoyen** [comment]
Already exists as `room-service`. We'll add an alias so it can be found under your suggestion.

**Comment by ArielZabihi** [comment]
Oh wow - thanks for the help! 😅

**Comment by mririgoyen** [comment]
Aliases added.
