### ISSUE TITLE
Removed and renamed icon

### ISSUE THREAD

**Issue by brhaka** [Templarian/MaterialDesign#6764]
### What is your question?

About two months ago the `discord` icon was replaced by a globe of light. After that, it was renamed `globe-light`: 
![image](https://user-images.githubusercontent.com/32342284/186948825-4ee7ea14-dbc3-45fd-a385-ae7d6de5c103.png)
I've found that info [here](https://materialdesignicons.com/history).

Why was it removed?
Is it going to be added back?

Thank you!

**Comment by mririgoyen** [comment]
No. It was removed in #6564. All brand icons are being removed in v8 (#6602). Please search before posting. This has been asked before.
