### ISSUE TITLE
Play-box-edit-outline

### ISSUE THREAD

**Issue by SintijaPotaicuka** [Templarian/MaterialDesign#6768]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Hey, I have created Play-box-edit-outline icon

We are looking into UI that supports Video attribute settings - size, playback time, loop, etc., so thought this icon could be useful to edit video settings

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/102287459/188454666-ca737a52-6eb0-4cac-b8b5-50ee746ba801.png)

### Upload the icon source.

[play-box-edit-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/9489954/play-box-edit-outline.svg.zip)

**Comment by mririgoyen** [comment]
[![play-box-edit-outline](https://materialdesignicons.com/icon/play-box-edit-outline)](https://materialdesignicons.com/icon/play-box-edit-outline)
