### ISSUE TITLE
Search logic suggestion: allow boolean ... search for "move -remove"

### ISSUE THREAD

**Issue by stuntpilot** [Templarian/MaterialDesign#6769]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

Not a bug per se, but when user tries to search for _"move"_, all of the _re"move"_ icons are included in the results.

**Comment by mririgoyen** [comment]
I would expect that if I type "move" I see everything with the word "move" in the name.

Regardless, we're not currently making changes to the existing site, as its deprecated while we [build the new one](https://github.com/Templarian/MaterialDesign/issues/5161).

Thanks for the suggestion.
