### ISSUE TITLE
Newspaper, folded

### ISSUE THREAD

**Issue by lenzi-erickson** [Templarian/MaterialDesign#6774]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need a newspaper icon that looks more vintage rather than new school. Aka, I wish there was one that was folded and looked like the Sunday paper sitting on your front porch. 🙂

\* Preferably in outlined and filled!

### Give us an example of what this icon might look like.

<img width="228" alt="Screen Shot 2022-09-08 at 10 21 23 AM" src="https://user-images.githubusercontent.com/20845477/189186187-68f039d6-6e77-4d85-bdcf-fe08d59a91c5.png">

**Comment by mririgoyen** [comment]
Unfortunately, you're not going to get anything like your example as it breaks [Material guidelines](https://material.io/design/iconography/system-icons.html#design-principles) and shows perspective. Your best bet is to use `newspaper`. The rounded edges at the bottom imply the fold.

[![newspaper](https://materialdesignicons.com/icon/newspaper)](https://materialdesignicons.com/icon/newspaper)

Thanks for your suggestion.
