### ISSUE TITLE
account-location

### ISSUE THREAD

**Issue by andrew-goldie** [Templarian/MaterialDesign#6778]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Indicating location or address of a person.

### Give us an example of what this icon might look like.

Similar to the other account- icons: Person icon with a small map-pin location device to the side. See account-question, account-credit-card, etc.

**Comment by boehan** [comment]
![grafik](https://user-images.githubusercontent.com/7279415/191523998-3aa99165-85e7-460a-aff8-778659ab49ce.png)
[account-marker.zip](https://github.com/Templarian/MaterialDesign/files/9617249/account-marker.zip)

**Comment by andrew-goldie** [comment]
Exactly what I needed. Thank you so much.
