### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by KenRmk** [Templarian/MaterialDesign#678]
Hello. Before switching to MDI I've been using polymer icons and googles iconfont and I noticed there are some icons missing. So i took a screenshot of some polymers icons and started comparing it. I couldn't find the yellow marked in MDI. I might have missed something but still it makes me wonder why are these icons missing? I thought MDI started by taking all of googles icons and then started adding commnity icons.
Is there a reason for it? Because I'd love to help by finding and adding these.
![screenshot 527](https://cloud.githubusercontent.com/assets/3995401/9836654/b4449dd4-5a21-11e5-8530-d99def17713c.png)

Also I noticed some of the official icons were replaced by community made (for example calendar-today) or are in conflict in some other way. I marked them blue.
My concern is how much does this community preffer the official icons over the community made? Because official google-made are priority for me. I simply want the consistency of using the very same icons that are in other apps and all of android.
For example: official google icon shouldn't be called 'eyedropper-variant'.
![screenshot 528](https://cloud.githubusercontent.com/assets/3995401/9836693/3e22f306-5a23-11e5-8005-c45166b20487.png)

Anyway thank you for this great library! :)

**Comment by CoDEmanX** [comment]
The story in short: Google published MD icons, MDI opened with stock Google icons, Google added a lot more icons, MDI still needs to incorporate a bunch.

"All" stock icons will eventually be available in MDI. I put "all" in quotes because there are couple icons in Google's icon repository, that aren't shown on their own icons page. Some are of low quality, others use more than one color (e.g. black and white or a dimmed black as secondary color).

See #420

**Comment by Templarian** [comment]
Yea, MDI existed before the official pack and to not break backwards compatibility some icons are will replaced with the stock and others will get a variant prefix. `eyedropper` is a special case that rarely happens, but it gets way more downloads than the official icon so I kept the official one as a `-variant`. Normally that won't happen.

Thanks for the feedback. This is the next priority after the new export tool (which is what I'm working on today).

**Comment by CoDEmanX** [comment]
@Templarian: I can presumably finish the TODO table in the first week of October.
