### ISSUE TITLE
More Fan Speeds

### ISSUE THREAD

**Issue by SGXander** [Templarian/MaterialDesign#6780]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Home Assistant honeycomb menu icon

### Give us an example of what this icon might look like.

Just like fan-speed-1, 2 and 3 please add 4 and 5 for devices that have 5 speed modes

**Comment by mririgoyen** [comment]
Related: #5213

The reason we used numbers instead of H/M/L was to avoid a language conflict. Most fans do not have more than 3 speeds and we're not interested in have the fan icon with all 9 numbers.

Thanks for the suggestion.

**Comment by drsassafras** [comment]
Although it may be true that a ceiling fan may typically only support 3 speeds, its extraonlay uncommon for a fan speed on a heat pump to only support three settings. They typically support something like:

fan_modes:
  - auto
  - low
  - medium_low
  - medium
  - medium_high
  - high
  - turbo
  - quiet

Perhaps if MaterialDesign is unintrested in supporting fan modes for ceiling fans above 3 settings, (a reasonable position) it may consider supporting additional speeds for the sake of heat pumps, which are currently the icon support for is very limited.
