### ISSUE TITLE
Metadata json file is missing from webfont package

### ISSUE THREAD

**Issue by tip2tail** [Templarian/MaterialDesign#6782]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

Can the meta.json file please be added to the @mdi/font package?

**Comment by Templarian** [comment]
@tip2tail This was intentionally left out of the `@mdi/font` package (which will only ship Woff2 in v8+). Trying to keep the package specifically tailored for just the font/css files. We really don't want anyone using the `@mdi/font` it's really just around for [legacy compatibility](https://dev.materialdesignicons.com/guide/webfont-alternatives).

Developers needing access to the meta data should also include the `@mdi/svg` package.
