### ISSUE TITLE
LED

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#679]
Google's eyedropper somehow inspired me :wink: 

![led](https://cloud.githubusercontent.com/assets/1309249/9838425/a50a0cb4-5a5d-11e5-9804-def7afaf3456.png) https://www.dropbox.com/s/g49r6txaigfxn5r/led.svg?dl=0
![led2](https://cloud.githubusercontent.com/assets/1309249/9838423/a5077f62-5a5d-11e5-9038-e828c656f485.png) https://www.dropbox.com/s/jfsdjjf68jlns3m/led2.svg?dl=0
![led3](https://cloud.githubusercontent.com/assets/1309249/9838424/a509da50-5a5d-11e5-942a-6d74aca0f57c.png) https://www.dropbox.com/s/ak6469cxccqup25/led3.svg?dl=0

**Comment by Templarian** [comment]
Those are sweet. `led`, [`led-off` with a slash], `led-on`, `led-outline`.

The last one's prongs are not consistent length, might make it off center, but would look more consistent.

**Comment by CoDEmanX** [comment]
Well, all 3 are different. The problem with a uniform base shape is, that it will be very off the horizontal center without the on-strokes, and the off state (slash) will also look odd. It could be solved by having 2 pairs: centered on / off (no on-strokes), on / off (strokes, no strokes) and an additional outline version (for both?)

**Comment by CoDEmanX** [comment]
![led-on](https://cloud.githubusercontent.com/assets/1309249/9838882/0f4e7eb0-5a69-11e5-90bf-cb3e3465b25b.png)  ![led-off](https://cloud.githubusercontent.com/assets/1309249/9838884/16505382-5a69-11e5-9670-46b0d8f52352.png) ![led-outline](https://cloud.githubusercontent.com/assets/1309249/9838892/46bff0c2-5a69-11e5-856f-d0ca5c22b7b6.png)

https://www.dropbox.com/s/rfisawrhgbwmt1n/led-on.svg?dl=0 / https://www.dropbox.com/s/7o0htoftbatbtuw/led-off.svg?dl=0 / https://www.dropbox.com/s/3cb1g5e3wow8zt8/led-outline.svg?dl=0

![led-on2](https://cloud.githubusercontent.com/assets/1309249/9838888/31a1cec2-5a69-11e5-8c38-e27c337c86c8.png) ![led-off2](https://cloud.githubusercontent.com/assets/1309249/9838886/31a064ec-5a69-11e5-93ba-3da28bb5d688.png) ![led-outline2](https://cloud.githubusercontent.com/assets/1309249/9838887/31a0e76e-5a69-11e5-8033-395a8fb8c605.png)
https://www.dropbox.com/s/p3wq3z4sv0xssmw/led-on2.svg?dl=0 / https://www.dropbox.com/s/8a2hxvxiillnmsd/led-off2.svg?dl=0 / https://www.dropbox.com/s/m0wmwpfwl3u1n8u/led-outline2.svg?dl=0

**Comment by Templarian** [comment]
I like that idea, that does look like the best option, even though it does add 6 icons.

**Comment by Templarian** [comment]
[![led-on](https://materialdesignicons.com/icon/led-on)](https://materialdesignicons.com/icon/led-on) [![led-off](https://materialdesignicons.com/icon/led-off)](https://materialdesignicons.com/icon/led-off) [![led-outline](https://materialdesignicons.com/icon/led-outline)](https://materialdesignicons.com/icon/led-outline) [![led-variant-on](https://materialdesignicons.com/icon/led-variant-on)](https://materialdesignicons.com/icon/led-variant-on) [![led-variant-off](https://materialdesignicons.com/icon/led-variant-off)](https://materialdesignicons.com/icon/led-variant-off) [![led-variant-outline](https://materialdesignicons.com/icon/led-variant-outline)](https://materialdesignicons.com/icon/led-variant-outline)
