### ISSUE TITLE
AL extention icon

### ISSUE THREAD

**Issue by haranhari11** [Templarian/MaterialDesign#6795]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Mostly working on projects that has .al extension. so I would like to request icon for that file extension.

**THANKYOU**

### Give us an example of what this icon might look like.

![file_type_al](https://user-images.githubusercontent.com/69118975/193900029-1332fe80-8ee0-45b8-97ff-3c9738712e10.svg)

**Comment by Templarian** [comment]
This is going to be too niche at this time. We're removing all brand icons and most company specific icongraphy out in v8.
