### ISSUE TITLE
US Power Outlet/Power Receptacle

### ISSUE THREAD

**Issue by bearhntr** [Templarian/MaterialDesign#6796]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Identifying Z-Wave Power Outlets (something like this)

![image](https://user-images.githubusercontent.com/100164602/194418511-3dcf5030-6ecc-4b7c-80eb-5a90fe33740b.png)

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/100164602/194418527-e3da312f-87e9-4980-9fbb-0417c5abee93.png)

**Comment by mririgoyen** [comment]
It exists as power-socket-us. Please search.
