### ISSUE TITLE
Exclamation mark in circle

### ISSUE THREAD

**Issue by baluson** [Templarian/MaterialDesign#6797]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This is the icon of the teacher's right movement in hungary. But it can also be used as a generic warning/alert sign with an exclamation mark.
The svg is almost ready. It would be great, if someone with actual knowledge could make the bottom part a but more round...

### Give us an example of what this icon might look like.

<svg style="width:24px;height:24p" viewBox="0 0 24 24"><path fill="currentColor" d="M11,6L 13,6L 13,19L 11,19L 11,6 Z M 13,20L 13,22L 11,22L 11,20L 13,20 Z" /><path fill="currentColor" d="M10,20 A8,8 0 0,1 4,12 A8,8 0 0,1 12,4 A8,8 0 0,1 20,12 A8,8 0 0,1 14,20 L14,22 A10,10 0 0,0 22,12 A10,10 0 0,0 12,2 A10,10 0 0,0 2,12 A10,10 0 0,0 10,22 L10,20 Z" /></svg>

**Comment by mririgoyen** [comment]
Once again, these exist. Please search before posting.

alert-circle(-outline)
