### ISSUE TITLE
Phone battery icons

### ISSUE THREAD

**Issue by LouisCAD** [Templarian/MaterialDesign#6798]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Show the status of a phone battery from another device (e.g. from a computer or a watch).

The goal is to communicate unambiguously the fact that it's the battery of a phone we're referring to, on a small area.

### Give us an example of what this icon might look like.

Similar to the gamepad battery icons, or similar to the bluetooth battery icons.

**Comment by mririgoyen** [comment]
I think this idea is too specific and too niche. Just use the battery icons.

**Comment by LouisCAD** [comment]
Can't the same be said for the existing gamepad battery icons?

**Comment by Ilove-Heng** [comment]
![Cryptocurrency_Logo svg](https://user-images.githubusercontent.com/102523138/194986667-dd5cabfe-a165-49a0-aab6-63067d05b05d.png)

**Comment by mririgoyen** [comment]
> Can't the same be said for the existing gamepad battery icons?

Absolutely. I'd love to see most of those removed as well. 😄

We're going to pass on this request for now though, thanks for the suggestion.
