### ISSUE TITLE
 icon mdi-view-tent-variant no longer available

### ISSUE THREAD

**Issue by Tiansing** [Templarian/MaterialDesign#6799]
### Where are you experiencing this bug?

materialdesignicons.com

### What is the issue you are experiencing?

The icon mdi-view-tent-variant seems to no longer be available in the mdi icons font (search for "tent" at https://materialdesignicons.com/).

**Comment by Templarian** [comment]
I don't see any icon named that ever existing.

- https://pictogrammers.github.io/@mdi/font/7.0.96/
- https://github.com/Pictogrammers/pictogrammers.github.io/tree/main/%40mdi/font (any version from here)
