### ISSUE TITLE
Car battery, oil temperature

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#680]
Not very pretty, but they complete the set of car service related icons:

![car-battery](https://cloud.githubusercontent.com/assets/1309249/9838499/37f63380-5a5f-11e5-9d80-7e7b06b3714e.png) https://www.dropbox.com/s/861ufd90i7y1xi9/car-battery.svg?dl=0
![oil-temperature](https://cloud.githubusercontent.com/assets/1309249/9838818/d3171436-5a66-11e5-854e-c17cbe06d99b.png) https://www.dropbox.com/s/8wmb9k9oee8rba7/oil-temperature.svg?dl=0

**Comment by Templarian** [comment]
![![car-battery](https://materialdesignicons.com/icon/car-battery)](https://materialdesignicons.com/icon/car-battery) ![![oil-temperature](https://materialdesignicons.com/icon/oil-temperature)](https://materialdesignicons.com/icon/oil-temperature)
