### ISSUE TITLE
mdi-playlist-play

### ISSUE THREAD

**Issue by joekirsch** [Templarian/MaterialDesign#6801]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

The icon in materialdesignicons for [mdi-playlist-play] correctly matches all of the other playlist icons.

![image](https://user-images.githubusercontent.com/39744244/194774850-6d3b83b4-f7ae-4e7e-b736-8fdc4c41a6e9.png)

But the [mdi-playlist-play] icon in the font package shows the playlist differently (all lines are long and same width). 

![image](https://user-images.githubusercontent.com/39744244/194774818-1d758930-b751-43f8-9004-4f8f304249f6.png)

We are hoping to see the icon shown in materialdesignicons since it matches the rest of the playlist icons

**Comment by Templarian** [comment]
Not seeing the same... what version are you on @joekirsch?

**Comment by mririgoyen** [comment]
We've been unable to reproduce this. Please make sure you're on the latest version of the icon pack.
