### ISSUE TITLE
UTF-16 encoded webfont as opposed to the current UTF-32 encoded one

### ISSUE THREAD

**Issue by mhamid3d** [Templarian/MaterialDesign#6802]
### What is your question?

I've noticed that out of all the icon packs out there (FontAwesome, CodiCon, Elusive, RemixiCon, Phosphor), Material Design is the one only one that provides its font file encoded in UTF-32 full range unicode. This causes some rendering issues in some programs on Windows, especially with the Qt framework on certain versions. Is it possible to do the font as Unicode Bmp 16 instead?

**Comment by Templarian** [comment]
@mhamid3d We made the switch back in v4.0 many years ago. This would be too niche of an edge case to support. Would file a bug with Qt Framework if they are having issues rendering fonts.

There are no plans to support UTF-16 as the codepoints are fixed across releases. We're moving to only supporting WOFF2 in v8+ for the webfont.
