### ISSUE TITLE
security guard

### ISSUE THREAD

**Issue by git-e-001** [Templarian/MaterialDesign#6803]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

there are no icon like guard or watchman

### Give us an example of what this icon might look like.

there are no icon like guard or watchman

**Comment by mririgoyen** [comment]
You mean like any of our numerous `shield` icons:

[![shield](https://materialdesignicons.com/icon/shield)](https://materialdesignicons.com/icon/shield)

Or did you mean something like `account-tie-hat`?

[![account-tie-hat](https://materialdesignicons.com/icon/account-tie-hat)](https://materialdesignicons.com/icon/account-tie-hat)

Telling us what we don't have without any examples of what you're looking for isn't exactly helpful.

**Comment by mririgoyen** [comment]
Going to close this for now since we never got any more clarification on what you were looking for. If you want to comment back with some more details, we can reopen and reevaluate your request. Thanks for the suggestion.
