### ISSUE TITLE
Upgrade Cloud icons to match Google's?

### ISSUE THREAD

**Issue by Xenomorph99** [Templarian/MaterialDesign#6804]
### What is your question?

I'd like to upgrade our Cloud icons to match the specs of Google's new ones. Specifically, I really like their updated `cloud-upload` and `cloud-download`. I feel that our current cloud icons are a bit wide and flat. Google's new ones are more rounded and the shape is easier to read at a small size. Any objections to me making these updates?

This image shows our current `cloud-upload` in red and Google's new `cloud-upload` in green.
[cloud-upload.png.zip](https://github.com/Templarian/MaterialDesign/files/9778449/cloud-upload.png.zip)

 _(Github still won't let me upload images into these text boxes so I had to zip it)_

**Comment by Templarian** [comment]
Yeah, I like their cloud, lets update these ones. Their upload is nicer!

**Comment by Xenomorph99** [comment]
I got all the cloud icons updated using the new cloud shape
