### ISSUE TITLE
roof window icon

### ISSUE THREAD

**Issue by Homeassistjoenka** [Templarian/MaterialDesign#6805]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

roof window / skylight window

### Give us an example of what this icon might look like.

![roof window](https://user-images.githubusercontent.com/113582714/195653817-1f4f159f-318e-4e74-a8a2-0bee499a2775.jpg)

**Comment by mririgoyen** [comment]
We cannot add this because it shows perspective. It has been requested several times in the past. Thanks for the suggestion.
