### ISSUE TITLE
Icons not shown on Android Browsers

### ISSUE THREAD

**Issue by muthuvijayanta** [Templarian/MaterialDesign#681]
Hi Guys,
Icons not shown on android browsers with bootstrap3..

**Comment by Templarian** [comment]
@muthuvijayanta I'm looking at the icons on https://materialdesignicons.com/bootstrap and they are rendering fine.

Not sure, I've viewed them on a few devices and I haven't noticed any issue yet. Do you have steps to reproduce it (I might not be able to fix it should be working).

View just the webfont by itself here: http://cdn.materialdesignicons.com/1.2.65/

**Comment by CoDEmanX** [comment]
Works on my Nexus 5 in Chrome too.

**Comment by Templarian** [comment]
Going to close this out, tested on my co-workers' phone (Samsung S6) and it rendered fine also.

Could be a network issue on your server you are hosting the icons from?
