### ISSUE TITLE
How to use MDI with Chakra UI

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#6812]
### What new documentation or how-to guide would you like to see?

I'm looking for the optimal way to use MDI in combination with the [Chakra UI](https://chakra-ui.com/) React library.

[Chakra UI documentation](https://chakra-ui.com/docs/components/icon/usage#creating-your-custom-icons) describes how to use its [Icon](https://chakra-ui.com/docs/components/icon) component with a third-party icon library, like [React Icons](https://react-icons.github.io/react-icons/icons?name=md), as follows:

```
// 1. Import
import { Icon } from '@chakra-ui/react'
import { MdSettings } from 'react-icons/md'

// 2. Use the `as` prop
<Icon as={MdSettings} />
```

However, I couldn't get this to work with MDI. The best I could come up with is this more convoluted approach:

```
import { Icon } from '@chakra-ui/react'
import { mdiCog } from '@mdi/js';

<Icon><path d={mdiCog} /></Icon>
```

Is there a more streamlined approach than this?

**Comment by mririgoyen** [comment]
I'd use our official React library in place of the Chakra include.

https://www.npmjs.com/package/@mdi/react

**Comment by fra-ux** [comment]
Thanks @mririgoyen ! We're looking for a way that allows us to use the [Icon component from Chakra UI](https://chakra-ui.com/docs/components/icon/usage#creating-your-custom-icons).

The following approach seems to work, using an alternate package: [mdi-react](https://www.npmjs.com/package/mdi-react)

```
import { Icon } from '@chakra-ui/react';
import CakeIcon from 'mdi-react/CakeIcon';

<Icon as={CakeIcon} />
```

**Comment by frankgrinaert** [comment]
Thanks @mririgoyen ! We're looking for a way that allows us to use the [Icon component from Chakra UI](https://chakra-ui.com/docs/components/icon/usage#creating-your-custom-icons).

The following approach seems to work, using an alternate package: [mdi-react](https://www.npmjs.com/package/mdi-react)

```
import { Icon } from '@chakra-ui/react';
import CakeIcon from 'mdi-react/CakeIcon';

<Icon as={CakeIcon} />
```

**Comment by mririgoyen** [comment]
That MDI package is not a first-party package, so we cannot offer support for it. Our official stance for React consumption is our official React library, coupled with the JS library.

I'm glad you were able to find a solution for your use case, but it's not something we wish to document and imply support for.
