### ISSUE TITLE
pencil-ruler-outline

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#6817]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

outline version of [pencil-ruler](https://materialdesignicons.com/icon/pencil-ruler) 

Material reference: https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Adesign_services%3A

### Share a preview of your contribution.

Several variations. Happy to tweak, let me know.

A:
![image](https://user-images.githubusercontent.com/55925048/198234686-cb6c343d-29d9-47aa-9de3-3439d043d5bb.png)

B:
![image](https://user-images.githubusercontent.com/55925048/198234784-4319d112-55cc-4fa0-8b48-21ca9c942bfc.png)

C:
![image](https://user-images.githubusercontent.com/55925048/198234910-66828c96-085a-49a8-b96a-63dbf553c53b.png)

### Upload the icon source.

[pencil-ruler-outline.zip](https://github.com/Templarian/MaterialDesign/files/9877501/pencil-ruler-outline.zip)

**Comment by Simran-B** [comment]
I like A because it looks like two different objects, whereas the other two variants kind of look like an outlined X

**Comment by frankgrinaert** [comment]
one more, with a slightly fatter ruler

D:
![image](https://user-images.githubusercontent.com/55925048/198315014-75716f8a-7797-40ec-adf7-916684b1e352.png)

**Comment by mririgoyen** [comment]
[![pencil-ruler-outline](https://materialdesignicons.com/icon/pencil-ruler-outline)](https://materialdesignicons.com/icon/pencil-ruler-outline)
