### ISSUE TITLE
Locked percentage

### ISSUE THREAD

**Issue by mocking-mike** [Templarian/MaterialDesign#6818]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I was looking for an icon to visualise fixed (locked) rate in context of a loan. 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/50829720/198297136-19a236c6-4dcc-4900-b73f-b4e4bb1806fe.png)
![image](https://user-images.githubusercontent.com/50829720/198297438-b9190c77-c452-4538-bf26-7d54f0d5320f.png)
![image](https://user-images.githubusercontent.com/50829720/198301689-eabe3c4c-d29c-4f94-99d1-759e21449294.png)
![image](https://user-images.githubusercontent.com/50829720/198299389-4da54cc0-1b5b-44ef-8888-7c9fca8f9785.png)
![image](https://user-images.githubusercontent.com/50829720/198299500-5473747d-253f-460e-af87-af0bd71db4ad.png)
![image](https://user-images.githubusercontent.com/50829720/198299848-ca5dc1ed-1361-4bb8-a849-3e37013dd80b.png)

### Upload the icon source.

[lock-percent-variants.zip](https://github.com/Templarian/MaterialDesign/files/9879946/lock-percent-variants.zip)

**Comment by mocking-mike** [comment]
I had a problem with generating previews this time. Very unpredictable behaviour, i tried different of creating one path but some parts random parts were not displaying (e.g. only one dot, even doth both were united). I tried to flatten, compound path, substracting, excluding and some worked for one preview and not on the other. Finally I managed through trial to export good previews but I forgot to switch off work in progress for last 3... Hope it's not a problem cause the same settings are not working again...

**Comment by Simran-B** [comment]
@mocking-mike Does the SVG contain any transforms (on the path element or a parent group)? SVGO does not remove these, but I had some good results with https://lean-svg.netlify.app/ and its Flatten SVG option.

**Comment by mocking-mike** [comment]
@Simran-B If by transforms you mean flipped, skewed etc. than not. If you mean combined shaped I tired with and without with various results. I tried to flatten as well (before) in Affinity Designer but now I tried in lean-svg you suggested but same problem:
<img width="348" alt="Zrzut ekranu 2022-10-28 o 14 04 24" src="https://user-images.githubusercontent.com/50829720/198582840-5e812fe3-6cd4-4a4a-a44f-397d7937f004.png">

**Comment by mocking-mike** [comment]
What bugs me the most is why the bar is ok and two dots vanishes...

**Comment by mririgoyen** [comment]
[![lock-percent](https://materialdesignicons.com/icon/lock-percent)](https://materialdesignicons.com/icon/lock-percent)[![lock-percent-outline](https://materialdesignicons.com/icon/lock-percent-outline)](https://materialdesignicons.com/icon/lock-percent-outline)
[![lock-percent-open](https://materialdesignicons.com/icon/lock-percent-open)](https://materialdesignicons.com/icon/lock-percent-open)[![lock-percent-open-outline](https://materialdesignicons.com/icon/lock-percent-open-outline)](https://materialdesignicons.com/icon/lock-percent-open-outline)
[![lock-percent-open-variant](https://materialdesignicons.com/icon/lock-percent-open-variant)](https://materialdesignicons.com/icon/lock-percent-open-variant)[![lock-percent-open-variant-outline](https://materialdesignicons.com/icon/lock-percent-open-variant-outline)](https://materialdesignicons.com/icon/lock-percent-open-variant-outline)
