### ISSUE TITLE
icon name

### ISSUE THREAD

**Issue by bliveinhack** [Templarian/MaterialDesign#682]
It would be great if i can change actual name before downloading. [SITE FEATURE]

**Comment by Templarian** [comment]
This is included in the advanced export screen releasing this week. Few things to rework on the UI before it goes live.

**Comment by Templarian** [comment]
This feature half went live today, but only for singular icons. I'm not going to close it out just yet as one will be able to very shortly rename the icon in the package download options also.

<img width="768" alt="advancedexport" src="https://cloud.githubusercontent.com/assets/338885/9870248/f774dd74-5b4f-11e5-8fab-48bbd3bfb7ef.png">

Almost have the backend code done, but seeing as it is past 2am and I have a meeting in 6 hours I'm going to pass out. Not much needs to be added on the front end to support this.
