### ISSUE TITLE
Proposed tweak: tray-arrow-down & tray-arrow-up

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#6822]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I really love the alternative download/upload icons [tray-arrow-down](https://materialdesignicons.com/icon/tray-arrow-down) and [tray-arrow-up](https://materialdesignicons.com/icon/tray-arrow-down); they are more contemporary and stylistically closer to the latest [Material Symbols](https://fonts.google.com/icons?selected=Material%20Symbols%20Outlined%3Afile_download%3AFILL%400%3Bwght%40400%3BGRAD%400%3Bopsz%4048).

However, I believe they look a bit _off-center_ vertically:

![tray](https://user-images.githubusercontent.com/55925048/198903061-cbdb3c66-0c86-44d4-b6ae-11171a0532fe.png)

Attached are slightly tweaked versions which I think look a bit more balanced.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/55925048/198903188-64b46d18-372c-479c-8c05-02e4a75a3c29.png)

![image](https://user-images.githubusercontent.com/55925048/198903197-7ad363fa-1856-4c44-b057-fe3393b989dd.png)

### Upload the icon source.

[tray-arrow.zip](https://github.com/Templarian/MaterialDesign/files/9896895/tray-arrow.zip)

**Comment by mririgoyen** [comment]
The proposed change versus our current:

![image](https://user-images.githubusercontent.com/1015040/198909114-d7997d50-5c02-4158-9eaa-beb37f4897ad.png)

While I understand your rationale, our current are intentionally this way to match all other `tray` variants. When it comes to modifiers on a base icon, we try not to move the base icon unless there is no other way the modifier would fit (for example, some `-alert` modifiers might shift the base to the left to make room for the `!`). In this case, there is no spacial reasoning to move the base.

Thanks for the suggestion, but we're going to keep our existing icons.
