### ISSUE TITLE
camera-unlock

### ISSUE THREAD

**Issue by TomAnderson** [Templarian/MaterialDesign#6824]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Need this icon for a toggle button that switches between camera-lock and camera-unlock

### Give us an example of what this icon might look like.

same as camera-lock but with an open lock

**Comment by TomAnderson** [comment]
For consistency with how other icons are named, perhaps this should be named "camera-lock-open"?

**Comment by mririgoyen** [comment]
[![camera-lock-open](https://materialdesignicons.com/icon/camera-lock-open)](https://materialdesignicons.com/icon/camera-lock-open)[![camera-lock-open-outline](https://materialdesignicons.com/icon/camera-lock-open-outline)](https://materialdesignicons.com/icon/camera-lock-open-outline)
