### ISSUE TITLE
file-document-move

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#6826]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

The library already has an [file-move](https://materialdesignicons.com/icon/file-move) icon, but it's already used to upload empty files. Now you need to do the same option, only with the content filled.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/44722574/199474164-8d081b00-eaf4-4634-bacf-f5dbcb088cd0.png)![image](https://user-images.githubusercontent.com/44722574/199474218-2ba87913-0c0e-4cfa-aa9b-254ff0e441fc.png)

### Upload the icon source.

[file-document-move.zip](https://github.com/Templarian/MaterialDesign/files/9919710/file-document-move.zip)

**Comment by mririgoyen** [comment]
[![file-document-arrow-right](https://materialdesignicons.com/icon/file-document-arrow-right)](https://materialdesignicons.com/icon/file-document-arrow-right)[![file-document-arrow-right-outline](https://materialdesignicons.com/icon/file-document-arrow-right-outline)](https://materialdesignicons.com/icon/file-document-arrow-right-outline)
