### ISSUE TITLE
Google Icon: Quiz

### ISSUE THREAD

**Issue by mpoqq** [Templarian/MaterialDesign#6827]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

We would use it in combination with the other *-box-multiple icons.

### Give us an example of what this icon might look like.

https://fonts.google.com/icons?icon.query=quiz
![quiz_black_24dp](https://user-images.githubusercontent.com/20458956/199492617-cc287268-d9f6-452f-961a-2911fed907a6.svg)

I would recommend not naming it Quiz, but rather question-box-multiple.

**Comment by andrejsharapov** [comment]
i think it might fit

![image](https://user-images.githubusercontent.com/44722574/199522374-d7d9f489-f805-49bb-b8b6-7ddeea5c964b.png)![image](https://user-images.githubusercontent.com/44722574/199522412-619d5b5c-cf24-4810-b7ac-5074ddeb3e01.png)
[question-multiple.zip](https://github.com/Templarian/MaterialDesign/files/9921507/question-multiple.zip)

**Comment by mririgoyen** [comment]
[![help-box-outline](https://materialdesignicons.com/icon/help-box-outline)](https://materialdesignicons.com/icon/help-box-outline)

[![help-box-multiple](https://materialdesignicons.com/icon/help-box-multiple)](https://materialdesignicons.com/icon/help-box-multiple)[![help-box-multiple-outline](https://materialdesignicons.com/icon/help-box-multiple-outline)](https://materialdesignicons.com/icon/help-box-multiple-outline)
