### ISSUE TITLE
eye-lock + eye-lock-open

### ISSUE THREAD

**Issue by TomAnderson** [Templarian/MaterialDesign#6828]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Need this for toggling the visibility settings to be synchronized between two viewports (eye-lock) or independently controlled (eye-lock-open)

### Give us an example of what this icon might look like.

Similar to eye-plus and eye-minus but with closed / open lock symbols instead of + / -

**Comment by mririgoyen** [comment]
[![eye-lock](https://materialdesignicons.com/icon/eye-lock)](https://materialdesignicons.com/icon/eye-lock)[![eye-lock-outline](https://materialdesignicons.com/icon/eye-lock-outline)](https://materialdesignicons.com/icon/eye-lock-outline)
[![eye-lock-open](https://materialdesignicons.com/icon/eye-lock-open)](https://materialdesignicons.com/icon/eye-lock-open)[![eye-lock-open-outline](https://materialdesignicons.com/icon/eye-lock-open-outline)](https://materialdesignicons.com/icon/eye-lock-open-outline)
