### ISSUE TITLE
API 

### ISSUE THREAD

**Issue by Giildo** [Templarian/MaterialDesign#6829]
### What is your question?

Hello,

For a project, I need the list of the icons name. I would like the user can select an icon from the list to display it on a form. Do you have an API to get this list ?

**Comment by Templarian** [comment]
@Giildo You want the `meta.json` file. It is shipped alongside the `@mdi/svg` package or through the CDN.

- Docs: https://dev.materialdesignicons.com/contribute/third-party-guide
- CDN: https://www.jsdelivr.com/package/npm/@mdi/svg
