### ISSUE TITLE
Vegan

### ISSUE THREAD

**Issue by zs-jakob** [Templarian/MaterialDesign#6834]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Communicate that a menu item is vegan

### Give us an example of what this icon might look like.

https://www.google.com/search?q=vegan+symbol&tbm=isch
![ezgif-3-52e59aa914](https://user-images.githubusercontent.com/23041734/200558116-556d2a44-ca32-4b9d-8a93-c3ac8c0bb022.png)

**Comment by zs-jakob** [comment]
Similar request: https://github.com/Templarian/MaterialDesign/issues/3220

**Comment by mririgoyen** [comment]
Unfortunately, this is some artist's interpretation of how to indicate vegetarian or vegan and is not some standardized and universally recognizable symbol. At this time, we're not interested in adding it for that reason. We have plenty of different food and allergen icons that can be used within the proper context to hit your use case. If and when a standard is created, we'll gladly add it.
