### ISSUE TITLE
UAC - User Account Control icon (aka: "administrator privileges required" icon)

### ISSUE THREAD

**Issue by tarockx** [Templarian/MaterialDesign#6835]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I don't know if I've just missed it, but I couldn't find the Windows "administrator privileges required" shield icon, also known as the UAC (User Account Control) icon. Here's what I'm talking about:

![image](https://user-images.githubusercontent.com/10919460/200792122-1583c1a4-0529-4b18-a5c5-8cb0e4bd62b3.png)

Did I just not search for the right name, or is it missing? Can it be added?

It would be quite useful for people developing Windows applications, since it is the standard symbol that is displayed in Windows near every button/link that triggers a request for admin privileges, as shown for example here:

![image](https://user-images.githubusercontent.com/10919460/200793436-a64a8c44-7b5e-44f7-ba08-894305a95f72.png)

Thanks

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/10919460/200792501-f74822f0-52c7-4e9c-8d18-868ee1f9c68d.png)

**Comment by mririgoyen** [comment]
You're looking for 'security'. We should probably add some aliases to this one.

**Comment by tarockx** [comment]
@mririgoyen thank you, that's exactly what I was looking for.
I agree some aliases would be nice, I searched for "shield", "uac", "administrator", "windows" and "elevate" before posting but didn't find it.

**Comment by mririgoyen** [comment]
Aliases added.
