### ISSUE TITLE
Thai Baht currency symbol

### ISSUE THREAD

**Issue by jnjnthomas** [Templarian/MaterialDesign#6836]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For identifying numerical values as Thai Baht currency amounts.

### Give us an example of what this icon might look like.

The Unicode character is: ฿

SYMBOL | ฿
-- | --
NAME | Baht Sign
CATEGORY | Currency Symbols
ALT CODE | 3647
SHORTCUT 1 (MS WORD) | Alt + 3647
SHORTCUT 2 (MS WORD) | 00E3F, Alt X
UNICODE | U+00E3F
HTML CODE | &#3647;
HEX CODE | &#x0E3F;
HTML ENTITY | –
CSS CODE | \0E3F

SYMBOL	฿
NAME	Baht Sign
CATEGORY	[Currency Symbols](https://symbolhippo.com/copy-paste-currency-symbols)
ALT CODE	3647
SHORTCUT 1 (MS WORD)	Alt + 3647
SHORTCUT 2 (MS WORD)	00E3F, Alt X
UNICODE	U+00E3F
HTML CODE	&#3647;
HEX CODE	&#x0E3F;
HTML ENTITY	–
CSS CODE	\0E3F

**Comment by mririgoyen** [comment]
[![currency-thb](https://materialdesignicons.com/icon/currency-thb)](https://materialdesignicons.com/icon/currency-thb)
