### ISSUE TITLE
feature: permalink per icon

### ISSUE THREAD

**Issue by justinlawrence** [Templarian/MaterialDesign#684]
As seen on icons8.com, it would be cool to be able to copy a permalink for each icon, within that icon.

![screen shot 2015-09-14 at 10 14 12 pm](https://cloud.githubusercontent.com/assets/1521183/9862034/1427c98a-5b2e-11e5-9738-e2228c705253.png)

This would be useful in allowing me to spec tasks up-front and link to which icon I want to use.

I like the way they automatically select the whole permalink if I click on it, so that I can just hit cmd-c.

**Comment by Templarian** [comment]
You can do that sort of. It's a little broken at the moment, but works pretty well:

![image](https://cloud.githubusercontent.com/assets/338885/9862235/17071772-5afd-11e5-9664-e9d77ad72e1d.png)

**Comment by justinlawrence** [comment]
Wow, thanks, that was quick Templarian!

I've just seen and tried it now, but it didn't reveal anything nor copy anything to clipboard. See below:

![permalink](https://cloud.githubusercontent.com/assets/1521183/9862455/e25a0f32-5b30-11e5-9688-7a6598a88b80.gif)

Thanks!

**Comment by Templarian** [comment]
It changes the address in the address bar. If it doesn't work let me know the browser. I'm doing large site updates at the moment.

`https://materialdesignicons.com/icon/pulse` format

**Comment by Templarian** [comment]
I'll rework it to copy to the clipboard when I fix the bad redirect at the moment.

**Comment by CoDEmanX** [comment]
Copy to clipboard is a big issue especially in Firefox. It's only possible with a special flag or flash. I would recommend to add a read-only text box to the icon dialog and bind an on-click event that selects the entire text. Users can copy it to clipboard by LMB click + Ctrl+C this way and no change of the address / reload is required.

**Comment by Templarian** [comment]
Oh, firefox the IE of the browser world now-a-days. I've got a nice way to solve this that looks clean on both browsers. It will open a sort of drop down with a button (for chrome) or a readonly input box (no copy api detected).

**Comment by justinlawrence** [comment]
Thanks guys. I use Chrome.

**Comment by Templarian** [comment]
Good. :smiling_imp:

**Comment by Templarian** [comment]
http://codepen.io/templarian/pen/EVyVyN Is the code that will be going in. Just needs to be cleaned up before it is placed into production this week.

**Comment by justinlawrence** [comment]
Very nice!!
