### ISSUE TITLE
bank-circle

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6840]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Would like to use this to let a generic bank icons conform to how Plaid presents icons (as a circle graphic).

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/201835465-a64ac3c4-f90f-4138-8d81-a900bee3b3d9.png)

This is based on `bank` and `bank-transfer`, getting progressively more compressed each time.

![bank](https://user-images.githubusercontent.com/2228347/201835612-0c442fa0-45c6-4063-abaa-a168dc211b5a.png)
![bank-transfer](https://user-images.githubusercontent.com/2228347/201835616-93683924-0d10-4a91-899d-7dcbddca4a11.png)

### Upload the icon source.

[bank-circle.svg.zip](https://github.com/Templarian/MaterialDesign/files/10009655/bank-circle.svg.zip)

**Comment by mririgoyen** [comment]
[![bank-circle](https://materialdesignicons.com/icon/bank-circle)](https://materialdesignicons.com/icon/bank-circle)[![bank-circle-outline](https://materialdesignicons.com/icon/bank-circle-outline)](https://materialdesignicons.com/icon/bank-circle-outline)
