### ISSUE TITLE
cash-check

### ISSUE THREAD

**Issue by kanders2002** [Templarian/MaterialDesign#6842]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would like to use this icon specifically for price related functions, specifically for the "Price Check" section in our point-of-sale software.

### Give us an example of what this icon might look like.

<img width="92" alt="Screen Shot 2022-11-18 at 2 05 08 PM" src="https://user-images.githubusercontent.com/77994465/202783210-eef4477b-36f2-4e27-893a-b0ea7ab94fca.png">

**Comment by mririgoyen** [comment]
This would have to use our `cash` icon as the base; we cannot use the dollar sign for i18n reasons.

**Comment by mririgoyen** [comment]
Actually, this already exists!

[![cash-check](https://materialdesignicons.com/icon/cash-check)](https://materialdesignicons.com/icon/cash-check)
