### ISSUE TITLE
Cancel Vacuum Icon

### ISSUE THREAD

**Issue by masman69** [Templarian/MaterialDesign#6843]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would love to have an icon to suit a vacuum cancel and return to dock button.

### Give us an example of what this icon might look like.

Perhaps just the standard vacuum with the diagonal line thru it, or a vacuum on a dock, or the standard vacuum with a stop sign in the corner.

**Comment by mririgoyen** [comment]
[![robot-vacuum-off](https://materialdesignicons.com/icon/robot-vacuum-off)](https://materialdesignicons.com/icon/robot-vacuum-off)[![robot-vacuum-variant-off](https://materialdesignicons.com/icon/robot-vacuum-variant-off)](https://materialdesignicons.com/icon/robot-vacuum-variant-off)

**Comment by masman69** [comment]
Awesome and super fast!  Thankyou!
