### ISSUE TITLE
keyboard-close-outline

### ISSUE THREAD

**Issue by mpardieck** [Templarian/MaterialDesign#6844]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

There exists a keyboard-close icon from Google, but not one with the keyboard outlined.

### Share a preview of your contribution.

![ic_keyboard_close](https://user-images.githubusercontent.com/60376755/202871530-af0b2e80-13ef-4276-837a-b93ced650bb4.svg)

### Upload the icon source.

[keyboard_close_outline.zip](https://github.com/Templarian/MaterialDesign/files/10047938/keyboard_close_outline.zip)

**Comment by mririgoyen** [comment]
[![keyboard-close-outline](https://materialdesignicons.com/icon/keyboard-close-outline)](https://materialdesignicons.com/icon/keyboard-close-outline)
