### ISSUE TITLE
keyboard-shift-off

### ISSUE THREAD

**Issue by mpardieck** [Templarian/MaterialDesign#6846]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Although there are many arrows available, and an Apple shift, they all look somewhat out of place when used for a shift key. I wanted to have a more standard shift available. This one is hollow to show that shift is currently off.

### Share a preview of your contribution.

![ic_shift](https://user-images.githubusercontent.com/60376755/202954647-a31408c6-e4a8-47ca-83c6-616ac750bc0e.svg)

### Upload the icon source.

[keyboard-shift-off.zip](https://github.com/Templarian/MaterialDesign/files/10052641/keyboard-shift-off.zip)

**Comment by mririgoyen** [comment]
See #6845, we're consolidating this issue into that one.
