### ISSUE TITLE
decimal-percent-increase

### ISSUE THREAD

**Issue by mpardieck** [Templarian/MaterialDesign#6847]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

This is my variant of the decimal-increase icon by Simram. A usage example is in an application that is displaying percent data, this could be a button to increase precision or calculate to more decimal places. It might find its home in a program like Excel.

### Share a preview of your contribution.

![ic_percent_decimal](https://user-images.githubusercontent.com/60376755/202955055-ece034a1-d8df-4072-a981-9341ccca0747.svg)

### Upload the icon source.

[decimal-percent-increase.zip](https://github.com/Templarian/MaterialDesign/files/10052663/decimal-percent-increase.zip)

**Comment by mririgoyen** [comment]
I honestly don't see how adding the percent symbol adds anymore meaning over the current one.

[![decimal-increase](https://materialdesignicons.com/icon/decimal-increase)](https://materialdesignicons.com/icon/decimal-increase)

I feel this is too specific and too niche and our current icon solves the use case being presented.
