### ISSUE TITLE
Convert icon (convert lead)

### ISSUE THREAD

**Issue by osidsoft** [Templarian/MaterialDesign#685]

**Comment by CoDEmanX** [comment]
Please add an example

**Comment by osidsoft** [comment]
in most CRMs they have a feature to convert a lead or potential customer into a real customer (contact or account) for further communications and sales.

PS: I've attached a screenshot with the wanted icon marked under RED circle. I have intentionally attached the whole UI for better understanding the situation and the job behind the convert button.

![screenshot_2015-09-17-17-20-34](https://cloud.githubusercontent.com/assets/3314433/9947675/faffe22c-5d93-11e5-9bb9-718a1cb8c312.jpg)

**Comment by CoDEmanX** [comment]
Ah well, doesn't look good...
![account-convert](https://cloud.githubusercontent.com/assets/1309249/9963571/225966c0-5e2c-11e5-848e-1437ca2d2a4b.png)
![convert-lead](https://cloud.githubusercontent.com/assets/1309249/9963575/27cb5866-5e2c-11e5-8a17-a4c7803766ae.png)

**Comment by augustin32** [comment]
Done
![convert](https://cloud.githubusercontent.com/assets/14167196/10045396/dbb7dffe-61ae-11e5-8dea-2319353f8e88.png)

**Comment by osidsoft** [comment]
yeah this is great, but one thing, this is not material design inspired as it has 3D dimension.
what do you say?

**Comment by Templarian** [comment]
Yea, it won't fit in the Material Design style due to the 3D. Maybe a arrow going from a solid box to an outline box.

**Comment by osidsoft** [comment]
any new suggestions here??//
I might try to design few icons, on weekend :)

**Comment by osidsoft** [comment]
![convert lead 02](https://cloud.githubusercontent.com/assets/3314433/10345237/1891429a-6d20-11e5-8c84-906c0eb7472e.png)
![convert lead](https://cloud.githubusercontent.com/assets/3314433/10345238/18a0285a-6d20-11e5-92ec-40beec95491e.png)
![convert lead 03](https://cloud.githubusercontent.com/assets/3314433/10345236/18598d14-6d20-11e5-9fd9-5ea79acddc56.png)

**Comment by Templarian** [comment]
[![account-convert](https://materialdesignicons.com/icon/account-convert)](https://materialdesignicons.com/icon/account-convert)

2nd icon idea looked the nicest. Thanks!

**Comment by CoDEmanX** [comment]
Brilliant, I totally forgot about that rotate thing

**Comment by CoDEmanX** [comment]
It doesn't look centered at small sizes, I think it would be better to move the human shape 1 pixel up, and perhaps extend the torso 1 pixel.
