### ISSUE TITLE
dice-d6-random

### ISSUE THREAD

**Issue by mpardieck** [Templarian/MaterialDesign#6851]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

This is a die with a question mark. It is an icon to denote the action of getting a random number, such as when you roll a die.

### Share a preview of your contribution.

![ic_random_source](https://user-images.githubusercontent.com/60376755/202960680-1dcec6eb-a55f-40a4-85a9-abe29dec7ef8.svg)

### Upload the icon source.

[dice-d6-random.zip](https://github.com/Templarian/MaterialDesign/files/10053215/dice-d6-random.zip)

**Comment by mririgoyen** [comment]
This was just added in https://github.com/Templarian/MaterialDesign/issues/6827 as `help-box-outline`.
