### ISSUE TITLE
Strike any icon by stacking

### ISSUE THREAD

**Issue by btxtiger** [Templarian/MaterialDesign#6859]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

A simple line that can be used to strike any icon by stacking.

### Give us an example of what this icon might look like.

Suggestion: `M 20.84 22.73 L 11.11 13 L 6.11 8 L 1.11 3 L 2.39 1.73 L 22.11 21.46 L 20.84 22.73 Z`

<img width="50" alt="image" src="https://user-images.githubusercontent.com/15804690/204265213-3548833b-4585-403f-86e3-675b7abb5381.png">

<img width="48" alt="image" src="https://user-images.githubusercontent.com/15804690/204265080-9c123753-cc71-4056-a80b-593f7fbe1321.png">

**Comment by Templarian** [comment]
The MD guidelines want a removed cutout to the right of the `off` slash. Due to this requirement and most icons needing the line to be slightly different icon-to-icon we've decided not to include a strike through. This may be something you need to roll your own.

**Comment by btxtiger** [comment]
@Templarian In this case I would suggest this just as line icon. We can add more variants `vertical`, `horizontal`, and `top-right-bottom-left`. Currently there is only a forward-slash icon available.
