### ISSUE TITLE
Home Assistant Icon Request

### ISSUE THREAD

**Issue by stamandr** [Templarian/MaterialDesign#6860]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Home Assistant Icon

![image](https://user-images.githubusercontent.com/51379504/204610000-9595c82a-aef7-4c01-bb8f-388361a16d9a.png)

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/51379504/204610781-a6e93c72-c443-43c7-a9b4-bd943c71b596.png)

**Comment by mririgoyen** [comment]
This is the SmartThings logo and we do not add brand icons to this library.

**Comment by stamandr** [comment]
What about something similar ?
