### ISSUE TITLE
inconsistency between home icons (width/chimney)

### ISSUE THREAD

**Issue by Mariusthvdb** [Templarian/MaterialDesign#6864]
### What is your question?

        Yeah, the `home-assistant` icon is also the only home icon with a chimney. That might be worth a separate issue.

_Originally posted by @terreng in https://github.com/Templarian/MaterialDesign/issues/6863#issuecomment-1332803511_

in creating some new home icons, we noticed the home-assistant icon to be different from the others:
- it has a chimney
- it seems to be wider

My issue isn't as much with the chimney, its kind of a nice touch, but more so with the width. 
In using the various icons, the narrower home icons are just that bit more difficult to spot details on than the wider home-assistant icon.

<img width="244" alt="Scherm­afbeelding 2022-11-30 om 22 48 45" src="https://user-images.githubusercontent.com/33354141/204921438-6a97d28d-2dfc-4eb1-a33f-6428ad13dd24.png">

if anything, would it be possible to widen those (homes), to the same size as home-assistant?

**Comment by mririgoyen** [comment]
The Home Assistant icon is a Brand Icon. Our home icons, while similar, do not relate to it at all. We won't be changing this.

It's also important to note that all brand icons are being removed in v8.

**Comment by Mariusthvdb** [comment]
aware the home-assistant icon is brand and will be removed.

I guess my question was, whether the other home icons could be given that same amount of more space, given the fact it is possible in the available canvas? 
Asking because on such a tiny size, even the smallest amounts matter ;-)

**Comment by terreng** [comment]
> I guess my question was, whether the other home icons could be given that same amount of more space, given the fact it is possible in the available canvas?

Icons typically try to maintain a 2dp border around the perimeter for consistency.
