### ISSUE TITLE
Box Drawing Characters

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#6871]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Drawing grids, but the unicodes wouldn't match up with the wiki reference.

There are 112 glyphs in the spec, but there are more combinations not included in the spec.

- [ ] Verify naming first with guidelines: https://dev.materialdesignicons.com/contribute/icon-naming
- [ ] `2500` - `drawing-light-horizontal`
- [ ] `2501` - `drawing-heavy-horizontal`
- [ ] `2502` - `drawing-light-vertical`
- [ ] `2503` - `drawing-heavy-vertical`
- [ ] `2504` - `drawing-light-triple-dash-horizontal`
- [ ] `2505` - `drawing-heavy-triple-dash-horizontal`
- [ ] `2506` - `drawing-light-triple-dash-vertical`
- [ ] `2507` - `drawing-heavy-triple-dash-vertical`
- [ ] `2508` - `drawing-light-quadruple-dash-horizontal`
- [ ] `2509` - `drawing-heavy-quadruple-dash-horizontal`
- [ ] `250A` - `drawing-light-quadruple-dash-vertical`
- [ ] `250B` - `drawing-heavy-quadruple-dash-vertical`
- [ ] `250C` - `drawing-light-down-and-right`
- [ ] `250D` - `drawing-down-light-and-right-heavy`
- [ ] `250E` - `drawing-down-heavy-and-right-light`
- [ ] `250F` - `drawing-heavy-down-and-right`
- [ ] `2510` - `drawing-light-down-and-left`
- [ ] `2511` - `drawing-down-light-and-left-heavy`
- [ ] `2512` - `drawing-down-heavy-and-left-light`
- [ ] `2513` - `drawing-heavy-down-and-left`
- [ ] `2514` - `drawing-light-up-and-right`
- [ ] `2515` - `drawing-up-light-and-right-heavy`
- [ ] `2516` - `drawing-up-heavy-and-right-light`
- [ ] `2517` - `drawing-heavy-up-and-right`
- [ ] `2518` - `drawing-light-up-and-left`
- [ ] `2519` - `drawing-up-light-and-left-heavy`
- [ ] `251A` - `drawing-up-heavy-and-left-light`
- [ ] `251B` - `drawing-heavy-up-and-left`
- [ ] `251C` - `drawing-light-vertical-and-right`
- [ ] `251D` - `drawing-vertical-light-and-right-heavy`
- [ ] `251E` - `drawing-up-heavy-and-right-down-light`
- [ ] `251F` - `drawing-down-heavy-and-right-up-light`
- [ ] `2520` - `drawing-vertical-heavy-and-right-light`
- [ ] `2521` - `drawing-down-light-and-right-up-heavy`
- [ ] `2522` - `drawing-up-light-and-right-down-heavy`
- [ ] `2523` - `drawing-heavy-vertical-and-right`
- [ ] `2524` - `drawing-light-vertical-and-left`
- [ ] `2525` - `drawing-vertical-light-and-left-heavy`
- [ ] `2526` - `drawing-up-heavy-and-left-down-light`
- [ ] `2527` - `drawing-down-heavy-and-left-up-light`
- [ ] `2528` - `drawing-vertical-heavy-and-left-light`
- [ ] `2529` - `drawing-down-light-and-left-up-heavy`
- [ ] `252A` - `drawing-up-light-and-left-down-heavy`
- [ ] `252B` - `drawing-heavy-vertical-and-left`
- [ ] `252C` - `drawing-light-down-and-horizontal`
- [ ] `252D` - `drawing-left-heavy-and-right-down-light`
- [ ] `252E` - `drawing-right-heavy-and-left-down-light`
- [ ] `252F` - `drawing-down-light-and-horizontal-heavy`
- [ ] `2530` - `drawing-down-heavy-and-horizontal-light`
- [ ] `2531` - `drawing-right-light-and-left-down-heavy`
- [ ] `2532` - `drawing-left-light-and-right-down-heavy`
- [ ] `2533` - `drawing-heavy-down-and-horizontal`
- [ ] `2534` - `drawing-light-up-and-horizontal`
- [ ] `2535` - `drawing-left-heavy-and-right-up-light`
- [ ] `2536` - `drawing-right-heavy-and-left-up-light`
- [ ] `2537` - `drawing-up-light-and-horizontal-heavy`
- [ ] `2538` - `drawing-up-heavy-and-horizontal-light`
- [ ] `2539` - `drawing-right-light-and-left-up-heavy`
- [ ] `253A` - `drawing-left-light-and-right-up-heavy`
- [ ] `253B` - `drawing-heavy-up-and-horizontal`
- [ ] `253C` - `drawing-light-vertical-and-horizontal`
- [ ] `253D` - `drawing-left-heavy-and-right-vertical-light`
- [ ] `253E` - `drawing-right-heavy-and-left-vertical-light`
- [ ] `253F` - `drawing-vertical-light-and-horizontal-heavy`
- [ ] `2540` - `drawing-up-heavy-and-down-horizontal-light`
- [ ] `2541` - `drawing-down-heavy-and-up-horizontal-light`
- [ ] `2542` - `drawing-vertical-heavy-and-horizontal-light`
- [ ] `2543` - `drawing-left-up-heavy-and-right-down-light`
- [ ] `2544` - `drawing-right-up-heavy-and-left-down-light`
- [ ] `2545` - `drawing-left-down-heavy-and-right-up-light`
- [ ] `2546` - `drawing-right-down-heavy-and-left-up-light`
- [ ] `2547` - `drawing-down-light-and-up-horizontal-heavy`
- [ ] `2548` - `drawing-up-light-and-down-horizontal-heavy`
- [ ] `2549` - `drawing-right-light-and-left-vertical-heavy`
- [ ] `254A` - `drawing-left-light-and-right-vertical-heavy`
- [ ] `254B` - `drawing-heavy-vertical-and-horizontal`
- [ ] `254C` - `drawing-light-double-dash-horizontal`
- [ ] `254D` - `drawing-heavy-double-dash-horizontal`
- [ ] `254E` - `drawing-light-double-dash-vertical`
- [ ] `254F` - `drawing-heavy-double-dash-vertical`
- [ ] `2550` - `drawing-double-horizontal`
- [ ] `2551` - `drawing-double-vertical`
- [ ] `2552` - `drawing-down-single-and-right-double`
- [ ] `2553` - `drawing-down-double-and-right-single`
- [ ] `2554` - `drawing-double-down-and-right`
- [ ] `2555` - `drawing-down-single-and-left-double`
- [ ] `2556` - `drawing-down-double-and-left-single`
- [ ] `2557` - `drawing-double-down-and-left`
- [ ] `2558` - `drawing-up-single-and-right-double`
- [ ] `2559` - `drawing-up-double-and-right-single`
- [ ] `255A` - `drawing-double-up-and-right`
- [ ] `255B` - `drawing-up-single-and-left-double`
- [ ] `255C` - `drawing-up-double-and-left-single`
- [ ] `255D` - `drawing-double-up-and-left`
- [ ] `255E` - `drawing-vertical-single-and-right-double`
- [ ] `255F` - `drawing-vertical-double-and-right-single`
- [ ] `2560` - `drawing-double-vertical-and-right`
- [ ] `2561` - `drawing-vertical-single-and-left-double`
- [ ] `2562` - `drawing-vertical-double-and-left-single`
- [ ] `2563` - `drawing-double-vertical-and-left`
- [ ] `2564` - `drawing-down-single-and-horizontal-double`
- [ ] `2565` - `drawing-down-double-and-horizontal-single`
- [ ] `2566` - `drawing-double-down-and-horizontal`
- [ ] `2567` - `drawing-up-single-and-horizontal-double`
- [ ] `2568` - `drawing-up-double-and-horizontal-single`
- [ ] `2569` - `drawing-double-up-and-horizontal`
- [ ] `256A` - `drawing-vertical-single-and-horizontal-double`
- [ ] `256B` - `drawing-vertical-double-and-horizontal-single`
- [ ] `256C` - `drawing-double-vertical-and-horizontal`
- [ ] `256D` - `drawing-light-arc-down-and-right`
- [ ] `256E` - `drawing-light-arc-down-and-left`
- [ ] `256F` - `drawing-light-arc-up-and-left`
- [ ] `2570` - `drawing-light-arc-up-and-right`
- [ ] `2571` - `drawing-light-diagonal-upper-right-to-lower-left`
- [ ] `2572` - `drawing-light-diagonal-upper-left-to-lower-right`
- [ ] `2573` - `drawing-light-diagonal-cross`
- [ ] `2574` - `drawing-light-left`
- [ ] `2575` - `drawing-light-up`
- [ ] `2576` - `drawing-light-right`
- [ ] `2577` - `drawing-light-down`
- [ ] `2578` - `drawing-heavy-left`
- [ ] `2579` - `drawing-heavy-up`
- [ ] `257A` - `drawing-heavy-right`
- [ ] `257B` - `drawing-heavy-down`
- [ ] `257C` - `drawing-light-left-and-heavy-right`
- [ ] `257D` - `drawing-light-up-and-heavy-down`
- [ ] `257E` - `drawing-heavy-left-and-light-right`
- [ ] `257F` - `drawing-heavy-up-and-light-down`

### Give us an example of what this icon might look like.

https://en.wikipedia.org/wiki/Box-drawing_character

**Comment by mririgoyen** [comment]
I'm not sure I see the need for these.

- They're not Material.
- They're available in pretty much every other font-face.
- They are extremely niche and extraneous.
- No one's using Material Design Icons as their font in a terminal.
- Adding them all encompasses more than one icon release cycle.

I think these are noise and I'd like to voice my opposition to adding them to MDI. 🫣

**Comment by Templarian** [comment]
I was kind of going back and forth on this and agree. I added them to the `Jun Mono` set so had the list already. Adding these to the `Memory` icon set, but here they don't make sense.
