### ISSUE TITLE
lightning-bolt-0 lightning-bolt-10 ... lightning-bolt-90 lightning-bolt-100

### ISSUE THREAD

**Issue by jlpouffier** [Templarian/MaterialDesign#6872]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I am controlling the power drawn from the main electrical grid at home.
I'd like to quickly represent it with an icon that shows the percentage of what I am consuming vs what is available.
(like like the icons available for batteries) 

### Give us an example of what this icon might look like.

Versions of this icon filled at 10, 20, 30, 40, 50, 60, 70, 80 and 90% (like for batteries or ligths)

![lightning-bolt-outline](https://user-images.githubusercontent.com/5878296/205491905-e1bfb182-5b6f-4eac-a679-775ffbb9a83e.png) >>>>>> ![lightning-bolt](https://user-images.githubusercontent.com/5878296/205491893-8fe612f5-f409-4113-8ed0-a35eb076e317.png)

**Comment by jlpouffier** [comment]
Yeah. As such you are correct.
Anyway, the need is here. My idea was a very poor execution idea 😂

**Comment by mririgoyen** [comment]
Thanks for the suggestion, but we don't feel these work in a capacity that fits within the library.
