### ISSUE TITLE
Category Icon

### ISSUE THREAD

**Issue by pngtduy** [Templarian/MaterialDesign#6883]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

category icons help me add to the menu of my existing website

### Give us an example of what this icon might look like.

I do not request. You can design according to your own personal ideas

**Comment by Simran-B** [comment]
How about the shape icons?

![image](https://user-images.githubusercontent.com/7819991/208210453-aa1a769f-6b9a-48be-80f7-4b749d39e953.png)

**Comment by pngtduy** [comment]
Yes. that's it
