### ISSUE TITLE
Bike Pedals Icon

### ISSUE THREAD

**Issue by lauraabra** [Templarian/MaterialDesign#6884]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

We would use this Icon to depicture the categorie pedals in our webshop. 

### Give us an example of what this icon might look like.

We thought either a single pedal or an icon with to pedals (alike the Icons attached) would look good. 
![image](https://user-images.githubusercontent.com/112858125/207282772-57eec154-ef42-4c4b-97d3-020151709ea7.png)
![image](https://user-images.githubusercontent.com/112858125/207283152-0cfef7b9-400f-4457-bb5c-de8756e60178.png)

**Comment by jhil** [comment]
How are these? We could even have different variants, like pedal, pedal-mountain, pedal-clipless. Maybe they should be bike-pedal-.

![image](https://user-images.githubusercontent.com/2228347/212859763-b188889a-f686-4f5d-bccb-0a88c6b8ac0c.png)
![image](https://user-images.githubusercontent.com/2228347/212859840-019d2a7e-8e59-4be4-9523-19d1e0c59b2c.png)
![image](https://user-images.githubusercontent.com/2228347/212859699-8d2c0c2b-55b3-469c-9aa3-e110c51f1bfd.png)

[pedals.zip](https://github.com/Templarian/MaterialDesign/files/10433376/pedals.zip)

**Comment by lauraabra** [comment]
Hey jhil, these are awesome! Great, thank you so much! I do like all three of them, we can use them all :) 
I think its a good idea to use the prefix "bike", then they are even easier to find.

**Comment by jhil** [comment]
[![bike-pedal](https://materialdesignicons.com/icon/bike-pedal)](https://materialdesignicons.com/icon/bike-pedal)

[![bike-pedal-mountain](https://materialdesignicons.com/icon/bike-pedal-mountain)](https://materialdesignicons.com/icon/bike-pedal-mountain)

[![bike-pedal-clipless](https://materialdesignicons.com/icon/bike-pedal-clipless)](https://materialdesignicons.com/icon/bike-pedal-clipless)
