### ISSUE TITLE
Tiktok

### ISSUE THREAD

**Issue by lukmanade** [Templarian/MaterialDesign#6887]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Social Media

### Give us an example of what this icon might look like.

data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAABEVBMVEX///8AAAAl9O7+LFX+AEEA8+2iKkAm+PL/LFWq+vel+fYCDQz/LVj+I1Dd/fv+boYm/PbnLFCQHzT+Gkv+Ekj+fJD/9ff+B0SZ+fX+IE5Y9vHP/PoSaWYDFhYABABw9/Lr/v3+QGMk6uQSc3D+VnNPGCL/7fD/vce/KET+kqP/3uOC+PS4+/j+eIxp9/Ig087/z9b+S2vZLU4YnJgViYX/q7f/1NoNVVMaqKT+h5n+nq1wHSwdvLjHH0H+ADs5FRt9HjCsJkBYABXNo6p+t7UPPTsi3Ncex8KUsLKPACQcEBP+YnxkGyjq0NWDFyxeISznEUIGISAIMzIUfnuaJDojEhYLRkUEHBsxEhgAJyX/tcCqPx1pAAAJV0lEQVR4nO2d/VvaOBzAKYVrlVQLFGvBF3SoKDiVTadDT7k79fZyuk1v2/n//yHXFvpCk7QpRZK4fH7a82z0+X6W5Js0b83lBAKBQCAQCAQCgUAgEAgEAoFAIBAIBAKBQPBMNBdwNGmHNiXmizjmaYc2JeaKeTS/gOEy7dCmBNYw36Ed2pTAG9ZphzYlPEMdhnZoU2JkqLxagTirOSzSjjArnqEEc6E5/E47wqx4hquwYQXINuYS7RAzEmN4OTTcph1iRmIMpbJqGxontEPMSJzhwClEY4d2iBnxDEsIQ7eaWu9ph5iROEOpZxtqn2iHmJFYwyu7EFWNdogZiTV0c425RzvGbMQbOoVYPaYdYzbiDaWy3RBbtGPMRoLhll2IBb77/ARDqQ3kKt/9RZLhWllVZdpBZiLJ0K6nKt/DmkRDO59qG7SjzEKyoT085boQCQyltsxzSyQxlNrWLu04J4fIUBoY/A7dyAylCr/JhtBQ+qNGO9JJITWUpD9phzoh5IbSX7RjnYwUhtI5l8tRaQylc51Dx1SG0qle7CzQDjkl6QylB10p5juNJu2wU5DSULre1PPFYjG/vtxt8LHWn9bQqamK8wt3rZ+HdeL0htL1wdCRk5XwCQwlaeVmVI4v1lCS3t3qtuRLNpSk1bcHuv6iDW1Kr/7eY3/9NIuhJH0wqqC1f8b0e0c2wwqQVU2zmF7rz2zoUKBtEYcwfDmGEwkKQyb4lQ2vLl+64W+g8uINQS+pGHkwnI8xlGUwiO9F+DeUgfy4xrxhszHXWa/XbY16fb0TnQ5MMJRVIFfwjvQNG8t1dz4l71EsNsf/RZKhrMoaGHxk07D7OuzmKTbH/1GioZn7ZMqg/Zk5w8Y6bDeRoR39U9WSARhssWTYrWMPikxgmFuqFTQVANDuf2TDsJvH+SnKRIa53F7L1OwmCUC5fbdVomzYQJaf4pyg2Lw5uP3n8GRvO5hdITTM5Q6PbEfZtQTlXntQuevfb/0mUzBch/1su/ztm1fXbuBfDMMwjep+WkPbsWVa6ii/Op428uwNG1B+UXTl9u23IPCyG5PmHRRJYWjX1ZpR1WSYGRp2on66fvswHngWQzvnPB0VYMmZGTajGUbPn36NBp7N0Gb7uGUYlkbDcAHyewvHnd3QZulw98g0q5amqrM07I4LKsobhN90DF32nnYXNzTDNA1jNvOl44KKfo7f1zwdwyFL23snh4fPbpeLCuqb79B+UzecGRHBc5wft4aNsKCiv8ILcmrYHBPc/AaHy7vhWA29ifPj1DA8FNVv4wW5NOymEeTRsJlKkEfD16Ekc5AoyKFhqKNQNpMFOTQM9xP/vUTD0L0W+gqBIH+GoSxzipMq9QcX5fLGRrnXvirxZhgUoYLr6fs9d0JFVVV3ekXmzDBUhNdIvyvbSZUhuDEMOnt0Hb0sA4QeT4b1oAxRghWA1OPIMBjO6A9wiM4J1wjOFi3L0lRuDOc9Q2RffwEidoaptfbPzmqLG0bh0/gjWDX0KynqnXe8BNWqsbjjH8peOnwa/Yltw2ZcET6GBVVDPkbvBGXb0M+kOjwxuhUW1PD3IrBt6M/hI+IrhwSNFn4nL9uG/nAGnloL9xNm3BFXpg39ZqhDk6NroY6+8BT3EKYN/TdDOM/cBUVoxgqybeiNuhV4wNYL2mDCpRZMG3qJBn4v/NcvQivpDiSmDb0JGh1fSVUr6TwE04ajEQ1i+qnt19H4Rphj3DCPb4ajTEpwZQfThl4zhMek3jsvwY0dXBhCL/ero95QVZMfwoMhHFxplGiss+SHcGCIeK/wDA2C1WceDOFUWhq1Q4PgIctYw4HMiiFiRXvYDrUjgod0sG8nbfpliH2xGA3aNJJjgXW8If0yrOO6w+HFozLRxUDYdOWNbWkarg87C8TGoL5rSHLh4QLesDzT/U5IhkkCZVhyGyKJ4TLW0HvFpGnYxRpKF6RlmPeAHuG9n5jPL4JlWMNQ7VD6DMjaYbC8iqnpslqdgQmWIi6XDieitP3EJ3gTroiFK++4BZiBSHx8CnJzwr2znpb4ZuEXIeK/aZRKiTrVZ8NNE5h1Q6c3M5Jef/1WCE+4eomG7kXJwyJAb09w0mnSy1OwZ1qHNoptpRi9PyPDZIo0dG7lTBjUBGkGUQ8GI0PKtwi7MzX6d7TiFVBjh96hTdOIHsebMyd5P3lG3B4RuXQ4VIwrgPCucPg0/qU3l0X7wwFFXIfo8hngbxsP70hFrJB7lZRuZ5Eb5grsJgxJ+vkFNx+8HBJErZB7qwIa7U+UuFUNk2pcPiAr2cLY0SjEVFbfq6T0ryuvoyMM+NqFfrMwfjQKtSncXxWgf+W805zQ4zaPFb3TCP2gORc52oaq5P7yKvVmmBuN3OIMpQe9WKx35ruN7tzyej568gu5x8EvQhZu13UKMWHL3oM+uj8OcW5Wv0EcPLkH7FTSnNvrowffAe/yCqQ2EkT+0l8hpzvs9nBWgvWE+3NKtzrKUUEPFq78IqSfSV3mi+j3/DFWNiFH3NGokr/TL37UN0PqSblm6Hig64pnqSh6/hRz8ORCZinPuNj1FLGhBubHw/mme+BZyR+cYpNTUEdVdj7X5QzACQxdvl1/v/4R8/c/g10cVVaKMOcMT5NbIhlrwU4jtcpMEdrUi8iPbqUntJ/RYCOReiQM3UgZBIKsfdSiSXgWIZ7wfkYmhjNhmuTJBkt4MxxLaWZEM2nslqoE2RivRSHqFPGE2qCdR9n8xtNr7AHuZNbGdoUX6M6w4VkmOdqF5Gc5LGiy1VGEWZhQsB/2kw32skzAdn8Cv1J77GSNwfS1wLnti9SCV2MFyLqgrQhib8mD2OqNH42K3RXOBktH2h2x42X0YE2B3SQTYt8Aj0T3At/3IiejNMoLMcQcF1TcLXkBHx/LET+5usFmR49gb8OQgS2JLcnLSg9EjyaqBbqroSnZNTXnarXeoH8ZaZSrW5V2GUSLzx6oAc6+T73t3ZIH5HJvMBhUKpXHwaDdc69Zgw+WWiaH3+I83DDcG7lU/wI5p+CQp2Yts8bSlAU5O8ObABNQq2aNmwwDcbJoIm/JC/QsE7zns/w8lo5bBcNC1k1Vs4xqjZMeMJalnRowDecCucBNs6pmtfWes/QZx/bhce0TMAtDrKPF3SfWppoEAoFAIBAIBAKBQCAQCAQCgUAgEAgEAoFAwBv/A+tn4+sooO0TAAAAAElFTkSuQmCC

**Comment by Templarian** [comment]
3rd item in that check list. 🤨
