### ISSUE TITLE
triangle-down

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6888]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Triangle, but down.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/208226518-691bde16-89a5-41ee-bc38-4aaf6f47c783.png)

![image](https://user-images.githubusercontent.com/2228347/208226508-6111b578-315b-4db2-95c2-b8c814b8b9ee.png)

### Upload the icon source.

[triangle-down.zip](https://github.com/Templarian/MaterialDesign/files/10250959/triangle-down.zip)

**Comment by mririgoyen** [comment]
We don't typically allow icons that have simply been rotated, with the except of arrow icons, which this could be considered. 🤔 I dunno what to do here. 😆

**Comment by jhil** [comment]
🤷 don't feel strongly. We have triangle-small-down so this was for parity. I think there are enough uses for up/down triangles representing semantically different things, especially in data visualization, that it's worth having variants so developers don't need to use one-off rotations.

**Comment by jhil** [comment]
[![triangle-down](https://materialdesignicons.com/icon/triangle-down)](https://materialdesignicons.com/icon/triangle-down)
[![triangle-down-variant](https://materialdesignicons.com/icon/triangle-down-variant)](https://materialdesignicons.com/icon/triangle-down-variant)
