### ISSUE TITLE
Visual Impared 

### ISSUE THREAD

**Issue by victor-radulescu** [Templarian/MaterialDesign#689]
Visual impared material design icons.

**Comment by CoDEmanX** [comment]
It seems to be quite common to use an icon similar to 
https://materialdesignicons.com/icon/eye-off

or something like
![eye-impaired](https://cloud.githubusercontent.com/assets/1309249/9990716/b7b7278c-6063-11e5-8b8b-d0b7d293490c.png) but I find it not very recognizable at that size.

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback.
