### ISSUE TITLE
battery-plug icon

### ISSUE THREAD

**Issue by mmiller7** [Templarian/MaterialDesign#6891]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Icon for battery plug.  Could be used for indicating battery-backed plug-in power (like a UPS or inverter source)

### Give us an example of what this icon might look like.

A plug icon next to/on a battery icon

Something like `mdi:power-plug` next to `mdi:battery` or `mdi:car-battery`.

**Comment by jhil** [comment]
Here you go!

[![power-plug-battery](https://materialdesignicons.com/icon/power-plug-battery)](https://materialdesignicons.com/icon/power-plug-battery)
[![power-plug-battery-outline](https://materialdesignicons.com/icon/power-plug-battery-outline)](https://materialdesignicons.com/icon/power-plug-battery-outline)
