### ISSUE TITLE
auto-mode

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6896]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Inspired by the "Material Symbol" icon, but conformed to MDI standards. Not sure if we'd attribute that to Google or not. https://fonts.google.com/icons?icon.query=auto+mode

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/209262203-23e34136-f395-4b6b-aee6-3c665c7699f6.png)

### Upload the icon source.

[auto-mode.svg.zip](https://github.com/Templarian/MaterialDesign/files/10291747/auto-mode.svg.zip)

**Comment by Simran-B** [comment]
What would it be used for?

**Comment by jhil** [comment]
I'd like to use it for an automation that repeats. The four-point stars
have been used in other icons to represent auto or magic.

**Comment by jhil** [comment]
Forgot to copy the GitHub preview, but the new icon is here! https://materialdesignicons.com/icon/auto-mode

**Comment by Templarian** [comment]
@jhil I think it's an okay icon to have, but question, is that arrow circle with the cut up sections a standard modifier we have elsewhere? Thinking we may need to make this a standard modifier as it could possibly be used elsewhere.

**Comment by jhil** [comment]
It's used in the progress icons, but nowhere else I know of. I would have made this a solid circle except that Google used this dash pattern in their version. Thoughts?

**Comment by Templarian** [comment]
Nah this is fine for now, in the future we if more icons get this as a modifier then we'll look into renaming it possibly.
