### ISSUE TITLE
payment

### ISSUE THREAD

**Issue by proloveholic** [Templarian/MaterialDesign#69]
Can icons for payment added?

**Comment by matthew2402** [comment]
Yeah, icons for credit card logos would be nice ;-)
Like American Express, Mastercard, VISA...

**Comment by Templarian** [comment]
So, the goal right now is for every icon to be recognizable at 24x24. For larger icons please look into using an outside vector file.

http://materialdesignicons.com/icon/credit-card
http://materialdesignicons.com/icon/cash
http://materialdesignicons.com/icon/coin

(and the various currency symbols).
