### ISSUE TITLE
Fingerprint Icon

### ISSUE THREAD

**Issue by KiengKnot** [Templarian/MaterialDesign#690]
Due to now, Google has release new Fingerprint API, so maybe in my future work will be related on that API. so there is a need of the fingerprint icon for my future work recently. but for now i am looking for an Android official fingerprint icon for my presentation

**Comment by CoDEmanX** [comment]
Google hasn't released the official icon it seems, but you can find it in the MD guidelines already:

![https://material-design.storage.googleapis.com/publish/material_v_4/material_ext_publish/0B0iWdZjcphyMWEF1RlBXZnZKbWc/components_fp_11_state2.png]

**Comment by KiengKnot** [comment]
Thank you for your fast respond and suggestion, i wil use this icon include in my powerpoint for presenting at my university.

**Comment by CoDEmanX** [comment]
You can find couple more images and videos here:
http://www.google.com/design/spec/patterns/fingerprint.html#fingerprint-enrollment

A rough re-creation:
![fingerprint](https://cloud.githubusercontent.com/assets/1309249/10005311/c8a2faaa-60b6-11e5-887f-1cf706aa4058.png) https://www.dropbox.com/s/egznv6jgepvpfcx/fingerprint.svg?dl=0

Strokes + reference image: https://www.dropbox.com/s/hykormuo2qkrxw2/fingerprint.design.svg?dl=0

**Comment by Templarian** [comment]
[![fingerprint](https://materialdesignicons.com/icon/fingerprint)](https://materialdesignicons.com/icon/fingerprint)

Awesome work recreating it assigned under Google.
