### ISSUE TITLE
Missing schedule alias

### ISSUE THREAD

**Issue by noherczeg** [Templarian/MaterialDesign#6900]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

The `clock-outline` icon should have an alias of `schedule` according to the docs, but it's not showing up.

_Haven't checked the sources yet..._

**Comment by Templarian** [comment]
- Aliases are not unique per icon.
- If they were it would still bloat the `.css` file size dramatically (some icons have like 10 aliases).
- https://dev.materialdesignicons.com/guide/webfont-alternatives Great alternative other than the webfont.

Use the `clock-outline` and not the alias to uniquely identify the icon.
