### ISSUE TITLE
Peppol Logo

### ISSUE THREAD

**Issue by modula-ai** [Templarian/MaterialDesign#6906]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Peppol is a EU originated global standard for data interchange and an icon would be useful for applications that support peppol

### Give us an example of what this icon might look like.

https://www.google.com/imgres?imgurl=https%3A%2F%2Fpbs.twimg.com%2Fprofile_images%2F1192019761921740800%2FP-J9wVW1_400x400.jpg&imgrefurl=https%3A%2F%2Ftwitter.com%2Fpeppol_eu&tbnid=FEyqaDFSVA_aeM&vet=12ahUKEwj7jOXm26_8AhWVpukKHfdDDTcQMygAegUIARCtAQ..i&docid=mJpcRLM64CmWzM&w=375&h=375&q=peppol%20logo%20icon&hl=en&ved=2ahUKEwj7jOXm26_8AhWVpukKHfdDDTcQMygAegUIARCtAQ

**Comment by mririgoyen** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
