### ISSUE TITLE
Bench

### ISSUE THREAD

**Issue by KrisLau** [Templarian/MaterialDesign#6908]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I want to differentiate between playing members and benched players in my sports app. There seems to be a couple seat icons (`seat`, `chair`, `chair-school`, etc) but none that communicate benching. 

There was a previously closed request for something similar that was closed for not following the template (#5641) so I think there might be some use for it outside of sports as well (maybe to indicate rest spots in a park or sth like that)

### Give us an example of what this icon might look like.

Personally I like this kind of design for the bench icon with the single piece for the back vs the multiple pieces as it looks simpler and less cluttered 
- https://thenounproject.com/icon/bench-2071367/
  ![image](https://user-images.githubusercontent.com/46275463/210810358-ee6ee247-8931-42d3-9ce5-dd69d65998cb.png)

**Comment by jhil** [comment]
How are these? 

![image](https://user-images.githubusercontent.com/2228347/212851287-0dbc073f-ef21-4856-a216-b5cae151ba6a.png)
![image](https://user-images.githubusercontent.com/2228347/212851506-3d4a8527-c4f3-4d93-84a1-0584ffc883cf.png)


Made it so it lines up with table-furniture.

**Comment by jhil** [comment]
[bench.zip](https://github.com/Templarian/MaterialDesign/files/10432976/bench.zip)

**Comment by KrisLau** [comment]
@jhil I like them both but I'm partial to the second cause I feel like when the icon is used in small sizes the second one would be more easily seen.

**Comment by jhil** [comment]
[![bench](https://materialdesignicons.com/icon/bench)](https://materialdesignicons.com/icon/bench)[![bench-back](https://materialdesignicons.com/icon/bench-back)](https://materialdesignicons.com/icon/bench-back)

**Comment by KrisLau** [comment]
@jhil Thanks for the help!
