### ISSUE TITLE
memory-arrow-down: New icon

### ISSUE THREAD

**Issue by patrickelectric** [Templarian/MaterialDesign#6909]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

The idea is to have an icon for firmware update, or installing a new firmware to the device, or something more abstract related to an embedded application.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/1215497/210856450-83ee2640-67f2-44e3-adb2-4017453f4d6e.png)

### Upload the icon source.

[memory-arrow-down.zip](https://github.com/Templarian/MaterialDesign/files/10354886/memory-arrow-down.zip)

**Comment by patrickelectric** [comment]
ping @jhil

**Comment by patrickelectric** [comment]
or ping @Templarian @mririgoyen

**Comment by mririgoyen** [comment]
Thanks, we'll get to it when we get to it. We're in the process of launching the new site and that is taking up most of our time currently.

**Comment by patrickelectric** [comment]
Np, thanks @mririgoyen for the reply!

**Comment by patrickelectric** [comment]
ping @mririgoyen

**Comment by patrickelectric** [comment]
ping @jhil, @Templarian, @mririgoyen.

Is there something ? Is there a way of getting the icon merged ?

**Comment by mririgoyen** [comment]
When we get to it. Pinging us repeatedly is not a way to fast track a request. This is an open-source and volunteer-based project.

**Comment by mririgoyen** [comment]
[![memory-arrow-down](https://pictogrammers.com/library/mdi/icon/memory-arrow-down)](https://pictogrammers.com/library/mdi/icon/memory-arrow-down)
