### ISSUE TITLE
Quill Icon

### ISSUE THREAD

**Issue by crimsonclyde** [Templarian/MaterialDesign#691]
It would be awesome to have an icon for the Apache/Apache2 http server service.
I know that there is already an icon for the web, but it would be really great to have one explicit for the service.

Only an idea :) so feel free to give it a go!

Sorry did not know which licence the Apache Foundation used for their feather:
http://apache.org/

**Comment by crimsonclyde** [comment]
Mhm, maybe that could be a show-stopper...

Copyright © 1997-2015 The Apache Software Foundation.
Apache HTTP Server, Apache, and the Apache feather logo are trademarks of The Apache Software Foundation.

**Comment by Templarian** [comment]
I don't think their logo really works in the monochrome material design style. The license isn't really an issue. I assume you mean the feather right?

**Comment by crimsonclyde** [comment]
Yes right the feather.
I yes Templarian you could be right - was just an idea.
Currently I use the HTML5 logo in my application. It´s not really important. I just thought "Hey why not give it a try" :)

**Comment by CoDEmanX** [comment]
Maybe a general purpose feather?
![feather](https://cloud.githubusercontent.com/assets/1309249/10031632/b2ff3ea2-617e-11e5-9383-0776006ece07.png) https://www.dropbox.com/s/gujy523ry2a3flf/feather.svg?dl=0

**Comment by crimsonclyde** [comment]
Hi CoDEmanX the feather looks great - i have tried to manipulate it in Pixelmator.

1st try: Circle with the feather in it rotated like the one from apache
2nd try: Circle with the feather but feathers on both sides rotated like the apache one
3rd try: Grayscaling the feather from the apache site shrink it to fit into the circle

That all looks not really great :(
At a first glance it's absolutely impossible that anyone can identify this as the Apache HTTP Server. Never mind, this was only an idea and now I see this is not really possible. Maybe it is better to take a server and a web icon.

**Comment by Templarian** [comment]
[![feather](https://materialdesignicons.com/icon/feather)](https://materialdesignicons.com/icon/feather)
