### ISSUE TITLE
Vertical monitor

### ISSUE THREAD

**Issue by breti** [Templarian/MaterialDesign#6910]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I use one horizontal and one vertical (rotated) monitor.

### Give us an example of what this icon might look like.

https://i.rtings.com/assets/pages/VheikA4p/best-vertical-monitors-202111-medium.jpg

**Comment by jhil** [comment]
Here's an option that works fine in isolation, but looks small compared to the normal `monitor` icon. I think that's ok, and conformance to the base icon is more important than proportional accuracy.

![image](https://user-images.githubusercontent.com/2228347/212561274-2774455c-4830-437d-a0dd-1d545886a855.png)
[monitor-vertical.svg.zip](https://github.com/Templarian/MaterialDesign/files/10420950/monitor-vertical.svg.zip)

**Comment by jhil** [comment]
[![monitor-vertical](https://materialdesignicons.com/icon/monitor-vertical)](https://materialdesignicons.com/icon/monitor-vertical)
