### ISSUE TITLE
facade shutter + tilt (lamels) positions

### ISSUE THREAD

**Issue by Murcin86** [Templarian/MaterialDesign#6911]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

there is no icon for facade shutter - only shutter or blind so combination is only open or close ... but for facade shutter there is need to have open/close + lamels (tilt) open / close like in picture below.

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/95655881/210998621-9ea7cfb1-d293-40cd-a581-fdee4bf0a937.png)
![image](https://user-images.githubusercontent.com/95655881/210999334-33639cbb-03a7-4485-853c-81948b947556.png)

**Comment by mririgoyen** [comment]
This is going to be extremely difficult, if not impossible, to do while maintain Material guidelines. We've rejected other icons in the past dealing with window tilts. I'll leave this open a little while long to see if anyone has another idea.

**Comment by Murcin86** [comment]
unfortunately I know :( - but this is one icon missing in whole system... this is very need it to have one icon for facade shutter - like for example battery... we have level of battery + sign (charging, wireless, Bluetooth, etc) 
maybe this is something what could be done ?

**Comment by mririgoyen** [comment]
Once again, we can't add icons that convey perspective. Tilt/angle icons have been repeatedly requested. We understand their use case from a Home Automation point-of-view, but we simply cannot add them and maintain Material guidelines. We're once again going to have to say no.
