### ISSUE TITLE
touch-text

### ISSUE THREAD

**Issue by valkjsaaa** [Templarian/MaterialDesign#6919]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Added a new icon for touching text

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/5488815/211424631-a61301a2-25ad-4157-8bfd-f3238c3e2089.png)

### Upload the icon source.

[touch text.svg.zip](https://github.com/Templarian/MaterialDesign/files/10377510/touch.text.svg.zip)

**Comment by mririgoyen** [comment]
[![touch-text-outline](https://pictogrammers.com/library/mdi/icon/touch-text-outline)](https://pictogrammers.com/library/mdi/icon/touch-text-outline)
