### ISSUE TITLE
Website Icon

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#692]
The standard Google web icon is just a globe. I think that many users won't recognize this as a website, if it is used as a large icon instead of just a small link decoration.

For larger icons, I would prefer some kind of additional decoration, like in these samples:
[Hand](http://flogixtech.org/flogix/images/icon/internet_marketing.png)
[Arrow](http://images.clipartof.com/thumbnails/1098753-Black-And-White-Grid-Internet-Globe-And-Computer-Cursor.jpg)
[Magnifier](http://nesit.org/wp-content/uploads/searchatlas-512.png)

Also, for these large use cases, the stroke of the standard globe is too fat, in my opinion. I would prefer something lighter.

**Comment by augustin32** [comment]
![browser](https://cloud.githubusercontent.com/assets/14167196/10027838/a0e03366-6115-11e5-8e57-8a71266a06a2.png)
You mean something like that?

**Comment by derwaldgeist** [comment]
Yes!

**Comment by PeterShaggyNoble** [comment]
Does this fulfill your request?

![](https://materialdesignicons.com/icon/search-web)
