### ISSUE TITLE
Home with a dollar sign inside of it

### ISSUE THREAD

**Issue by GrapeJuice787** [Templarian/MaterialDesign#6922]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://materialdesignicons.com/) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](http://dev.materialdesignicons.com/roadmap/brand-icons) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Primary billing address for a customer

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/36643484/211586724-00cfb8c6-9d88-4011-9450-e5af8cc1ddd9.png)

**Comment by mririgoyen** [comment]
We don't put currency symbols in other icons due to language conflicts. Thanks for the suggestion.
