### ISSUE TITLE
Change color of icons?

### ISSUE THREAD

**Issue by onedevteam** [Templarian/MaterialDesign#693]
Hi, i can't find troubleshooting section, so i will ask here. Is it, and how, posible to change a color of an icon in html/bootstrap?

I'm using something like [i class="mdi mdi-48px mdi-account"></i], and get black icon, and instead i need it blue, or yellow, or any other color...

**Comment by Templarian** [comment]
It's just regular HTML... so, `<i class="mdi mdi-48px mdi-account" style="color:blue"></i>'. If you're using bootstrap you can use the built in colors.

```
<i class="mdi mdi-48px mdi-account text-danger"></i>'
```

http://getbootstrap.com/css/#helper-classes-colors

**Comment by onedevteam** [comment]
Great. Thanks :+1:
