### ISSUE TITLE
C.9 command in SVG should be C0.9 for Android drawables

### ISSUE THREAD

**Issue by penn5** [Templarian/MaterialDesign#6931]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

https://github.com/Templarian/MaterialDesign/blob/master/svg/folder-multiple-plus-outline.svg contains `6V20H20V22H2C.9`. The last three characters should be changed to `C0.9`. This should remain valid for SVGs and also fix the Android warning:
![image](https://user-images.githubusercontent.com/5600962/213252324-6a786fb8-540d-4cc8-ae1a-9a462bc15a4b.png)

I didn't submit a pull request as this file appears to be generated automatically.

**Comment by mririgoyen** [comment]
Are you actually experiencing a crash? AFAIK, this doesn't actually cause a crash on new versions of Android and the warning is only there to avoid affecting legacy Android. The path data shared is _valid_ SVG, so we're not eager to make changes to support legacy applications.

**Comment by penn5** [comment]
I didn't end up using this icon, so I don't know whether it actually causes crashes.

**Comment by mririgoyen** [comment]
Until we have confirmed cases of crashes, there's really nothing for us to do here. As I stated previously, we're provided standards-compliant SVG code, so there really shouldn't be any issue.
