### ISSUE TITLE
circle-slash

### ISSUE THREAD

**Issue by moraltolpy** [Templarian/MaterialDesign#6934]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To show rejected status of messages

### Give us an example of what this icon might look like.

octicons has good example as 'oi-circle-slash'

**Comment by jhil** [comment]
Hey! This is called `cancel` in the library. Did you need something different? https://materialdesignicons.com/icon/cancel

**Comment by mririgoyen** [comment]
Yep, this is already in the pack as `cancel`.

[![cancel](https://pictogrammers.com/library/mdi/icon/cancel)](https://pictogrammers.com/library/mdi/icon/cancel)
