### ISSUE TITLE
tennis-ball-outline

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6936]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

tennis ball outline

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/213617648-3e3a154d-d500-4216-b122-bbaa218ee7c2.png)

### Upload the icon source.

[tennis-ball-outline.svg.zip](https://github.com/Templarian/MaterialDesign/files/10463180/tennis-ball-outline.svg.zip)

**Comment by mririgoyen** [comment]
Could we get a `baseball-outline` too since they're very similar? 😄

**Comment by jhil** [comment]
[![tennis-ball-outline](https://materialdesignicons.com/icon/tennis-ball-outline)](https://materialdesignicons.com/icon/tennis-ball-outline)

**Comment by jhil** [comment]
> Could we get a `baseball-outline` too since they're very similar? 😄

[![baseball-outline](https://materialdesignicons.com/icon/baseball-outline)](https://materialdesignicons.com/icon/baseball-outline)
