### ISSUE TITLE
radiobox-indeterminate-variant

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6937]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

For parity with `checkbox-intermediate-variant`. See #6897 for discussion that may need to resolve before adding this.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/213619088-aef158ef-c699-44a5-8d3e-0e392c32aecb.png)

### Upload the icon source.

[radiobox-indeterminate-variant.svg.zip](https://github.com/Templarian/MaterialDesign/files/10463255/radiobox-indeterminate-variant.svg.zip)

**Comment by mririgoyen** [comment]
We'll definitely be doing renaming in #6897, but that doesn't hold this up from going in now.

**Comment by jhil** [comment]
[![radiobox-indeterminate-variant](https://materialdesignicons.com/icon/radiobox-indeterminate-variant)](https://materialdesignicons.com/icon/radiobox-indeterminate-variant)
