### ISSUE TITLE
`link-edit` and `link-variant-edit`

### ISSUE THREAD

**Issue by DamianGlowala** [Templarian/MaterialDesign#6938]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I'd like to change the `link-variant-plus` whenever a user focuses a cursor on a link in a rich text editor, to make it more clear they can change the URL.

![image](https://user-images.githubusercontent.com/48835293/213863873-bf1572dc-f8d7-404a-a5f9-dbfeda483578.png)

### Give us an example of what this icon might look like.

Combining a link symbol with a pencil.

**Comment by mririgoyen** [comment]
We can give this a try, but my feeling is the angle of the chain and the pencil are going to interfere with each other.

In your use-case, you say "whenever a user focuses a cursor on a link". At that point, a simple `pencil` should be all you need. The context is already there by the user interacting with the link. I think you are trying to be overly literal with your icon depiction. 😄

**Comment by DamianGlowala** [comment]
I do agree it could be visually unappealing. I don't have any opinion on whether that's certainly the case without seeing one, so I will leave this decision up to you. In the meantime, pencil on its own seems to (more or less) do the job. Thank you!

![image](https://user-images.githubusercontent.com/48835293/214390172-f1581221-2d4f-47eb-a294-26d4c0e491df.png)

**Comment by jhil** [comment]
It looks pretty bad as the variant, but I did add it for the standard version which cuts out more cleanly.

<img width="643" alt="Screen Shot 2023-06-08 at 5 03 45 PM" src="https://github.com/Templarian/MaterialDesign/assets/2228347/0ddf9452-c7aa-4692-abbe-dceb4a723379">

![image](https://github.com/Templarian/MaterialDesign/assets/2228347/27431fd6-ef2b-4dd5-8d7e-97bb9e8468d1)

**Comment by jhil** [comment]
[![link-edit](https://pictogrammers.com/library/mdi/icon/link-edit)](https://pictogrammers.com/library/mdi/icon/link-edit)
