### ISSUE TITLE
Zapier service icon

### ISSUE THREAD

**Issue by mlazzari-tribecube** [Templarian/MaterialDesign#694]
Icon for Zapier service https://zapier.com, like the following

![zapier_48](https://cloud.githubusercontent.com/assets/10433712/10044974/26b1d38e-61ff-11e5-80c0-71ccdec8dd22.png)

**Comment by augustin32** [comment]
Like This?
![zapier](https://cloud.githubusercontent.com/assets/14167196/10045288/02c9e6ce-61ae-11e5-9485-e72822ca5e6e.png)

**Comment by mlazzari-tribecube** [comment]
yup

**Comment by PeterShaggyNoble** [comment]
Closing this out as beyond the current scope of the project.
