### ISSUE TITLE
The white icons are missing from website

### ISSUE THREAD

**Issue by Pethical** [Templarian/MaterialDesign#6942]
### Where are you experiencing this bug?

pictogrammers.com

### What is the issue you are experiencing?

On the old website I could select black and white variant of any icon. Now only the black is available and the old website is unreacheable.

**Comment by mririgoyen** [comment]
Thanks for the report. This is not a bug, we just haven't built on advanced export functionality yet.

In the future, please direct website-related issues in the website repo here: https://github.com/Pictogrammers/pictogrammers.com/issues

There is already an open issue for color export: https://github.com/Pictogrammers/pictogrammers.com/issues/21
