### ISSUE TITLE
feature phone

### ISSUE THREAD

**Issue by PhillipMwaniki** [Templarian/MaterialDesign#695]
Can we have feature phone icon e.g.a nokia 3310 kind of icon

**Comment by CoDEmanX** [comment]
![cellphone2](https://cloud.githubusercontent.com/assets/1309249/10124495/8ac827ec-6556-11e5-90ad-ee40e10e3c61.png) tiny details, but easily recognizable
https://www.dropbox.com/s/gmhoq4u1cmiokdv/cellphone2.svg?dl=0

![cellphone](https://cloud.githubusercontent.com/assets/1309249/10124496/8ae21706-6556-11e5-873e-10eca25380d8.png) abstract classic cellphone, looks a bit odd
https://www.dropbox.com/s/gxvrj7pyr9pb30j/cellphone.svg?dl=0

![radio-device](https://cloud.githubusercontent.com/assets/1309249/10124497/8aee47ce-6556-11e5-9a96-ad15e5442109.png) looks more like a radio device than a cellphone
https://www.dropbox.com/s/wtewh9uh8ipcwgb/radio-device.svg?dl=0

**Comment by PhillipMwaniki** [comment]
The first one is lovely, thank you.

**Comment by Templarian** [comment]
Added `cellphone-basic` and `radio-handheld`.

[![radio-handheld](https://materialdesignicons.com/icon/radio-handheld)](https://materialdesignicons.com/icon/radio-handheld) [![cellphone-basic](https://materialdesignicons.com/icon/cellphone-basic)](https://materialdesignicons.com/icon/cellphone-basic)
