### ISSUE TITLE
Android friendly download format

### ISSUE THREAD

**Issue by adam-rankn** [Templarian/MaterialDesign#6952]
### What is your question?

the old version of this website had a useful download format for icons with a zip containing all required variants (mdpi, hdpi, xhdpi, xxhdpi, xxxhdpi with 16/24/36/48 dp). Is there a reason that this feature was removed?

**Comment by mririgoyen** [comment]
We've dropped support for the legacy Android formats. We recommend using the SVG or XML Vector Drawable versions moving forward.

https://developer.android.com/training/multiscreen/screendensities#vector-graphics
