### ISSUE TITLE
email-heart / love-letter

### ISSUE THREAD

**Issue by jhil** [Templarian/MaterialDesign#6958]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Matching `love-letter` 💌 emoji.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/2228347/216425005-ad91001c-7c66-40cd-ae63-5b271aa2e035.png)
![image](https://user-images.githubusercontent.com/2228347/216425083-22e00845-7a79-481d-8ffb-593e5571a837.png)

### Upload the icon source.

[email-heart.zip](https://github.com/Templarian/MaterialDesign/files/10572459/email-heart.zip)

**Comment by mririgoyen** [comment]
Kinda related to #3106.

**Comment by mririgoyen** [comment]
Should we put the modifier in the bottom right corner for this? I wonder if it being in the middle, especially for the closed envelope, makes it lose meaning. 🤔

**Comment by jhil** [comment]
I thought about that, but decided conformance with the very popular emoji was more important. Thoughts?

**Comment by mririgoyen** [comment]
💌

I guess that's not much better. I see your reasoning. Okay, I'm sold. Nice work.

**Comment by jhil** [comment]
[![email-heart-outline](https://materialdesignicons.com/icon/email-heart-outline)](https://materialdesignicons.com/icon/email-heart-outline) [![email-open-heart-outline](https://materialdesignicons.com/icon/email-open-heart-outline)](https://materialdesignicons.com/icon/email-open-heart-outline)
