### ISSUE TITLE
Remove all title tag inside SVG files

### ISSUE THREAD

**Issue by davideas** [Templarian/MaterialDesign#6959]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

When mouse overs the icon, the filename is shown as tooltip. This cannot happen.

**Comment by mririgoyen** [comment]
Are you talking about when you download from the website? If so, we've pushed a hotfix for it. If not, where are you seeing it?

Just FYI, website issues should be posted in https://github.com/Pictogrammers/pictogrammers.com/issues.

**Comment by davideas** [comment]
Oh yes it's when SVG is downloaded from the site. I didn't know that was the cause, I thought all SVGs were affected.
