### ISSUE TITLE
comment-search

### ISSUE THREAD

**Issue by The0x539** [Templarian/MaterialDesign#696]
Just a comment with a magnifying glass, likely with outline and solid versions.

**Comment by CoDEmanX** [comment]
The loupe at the bottom obfuscates the base shape a lot. How about moving it to the top instead?

**Comment by GreenTurtwig** [comment]
I blame being tired yesterday. :-P

![](https://user-images.githubusercontent.com/15905797/42625676-4251b586-85c0-11e8-959b-a92ac801a660.png)![](https://user-images.githubusercontent.com/15905797/42625704-55807e6c-85c0-11e8-853a-e4b8e40fa525.png)
[comment-search.zip](https://github.com/Templarian/MaterialDesign/files/2188019/comment-search.zip)

**Comment by Templarian** [comment]
Added. 😃
