### ISSUE TITLE
eye-closed

### ISSUE THREAD

**Issue by joshua-maros** [Templarian/MaterialDesign#6965]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I have an application where I would like to have a button allowing a node to be previewed, additionally communicating which node is currently being previewed. [eye-off](https://pictogrammers.com/library/mdi/icon/eye-off/) is too similar to [eye](https://pictogrammers.com/library/mdi/icon/eye/) to use them to communicate this. The suggested icon offers a clear location to click to show a preview while cleanly communicating which nodes are not being previewed. It was made by removing portions of the existing eye-outline icon.

### Share a preview of your contribution.

![Screenshot_20230207_161645](https://user-images.githubusercontent.com/60271685/217396461-7e6a4aca-88a3-412e-8257-daf8378637c9.png)

### Upload the icon source.

[eye-closed.zip](https://github.com/Templarian/MaterialDesign/files/10680503/eye-closed.zip)

**Comment by Templarian** [comment]
I like this one in context it could be very useful to include. 👍

**Comment by mririgoyen** [comment]
[![eye-closed](https://pictogrammers.com/library/mdi/icon/eye-closed)](https://pictogrammers.com/library/mdi/icon/eye-closed)
