### ISSUE TITLE
Advanced Export highlighted download button incorrect corners. 

### ISSUE THREAD

**Issue by popovychenko** [Templarian/MaterialDesign#697]
While using Advanced Export, when point cursor on icon download button, it changes layout to button with incorrect right corners. See screenshot.
Safari - Version 8.0.8 (10600.8.9)
Chrome - Version 45.0.2454.99 (64-bit)

![error](https://cloud.githubusercontent.com/assets/1732308/10085479/3efac63e-62be-11e5-861b-015175baf4af.png)

**Comment by Templarian** [comment]
Fixed. Thanks!
