### ISSUE TITLE
Add My Logo and icon

### ISSUE THREAD

**Issue by pejmangholami** [Templarian/MaterialDesign#6970]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I own a company that sells clothes (especially big size) , named KingSize, I want to put my logo and FavIcon in your repository.
if possible in the Brabd category.
I have attached that files here.

Thanks a lot

![Asset 1@3x](https://user-images.githubusercontent.com/58599740/218073155-02ba184b-63c7-4534-9e28-69b426dad952.png)
![Logo Kingsize](https://user-images.githubusercontent.com/58599740/218073169-8c0a57a0-0552-4c90-bf0c-f34e4361c8ef.png)

### Give us an example of what this icon might look like.

I want to use that File on my website(in the menu, etc.)
so I want to look like "shopping-outline"

**Comment by mririgoyen** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
