### ISSUE TITLE
Telegram

### ISSUE THREAD

**Issue by goodluckbuzz** [Templarian/MaterialDesign#6972]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

it was also useful if we arranged on the site

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/125126280/218253597-992495cd-5d5a-4f8d-af83-32dd87593139.png)

### Upload the icon source.

![image](https://user-images.githubusercontent.com/125126280/218253608-5d6804f9-3f6a-4a99-a5c3-17f37d5d5856.png)

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue+telegram+is%3Aclosed 😆
