### ISSUE TITLE
Play button with rounded corners

### ISSUE THREAD

**Issue by sampath-bandara** [Templarian/MaterialDesign#6973]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Hi,
I need to use this icon for the web site I'm currently working on to indicate videos. 

### Give us an example of what this icon might look like.

![play@2x](https://user-images.githubusercontent.com/121969434/218582935-497f0580-8890-4755-8939-b54c9348c454.png)

play icon in SF symbols.

**Comment by sampath-bandara** [comment]
and if you can please add this too.

![square filled on square@2x](https://user-images.githubusercontent.com/121969434/218583273-a7640698-8270-4048-ba4b-a995eed9a7cd.png)

square.filled.on.square  icon on SF symbols

**Comment by mririgoyen** [comment]
We do not provide other variants, such as rounded, in this library at this time. Thanks for the suggesiton.
