### ISSUE TITLE
file-document-refresh-outline

### ISSUE THREAD

**Issue by gabrielpastori1** [Templarian/MaterialDesign#6975]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Document outline refresh  icon

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/58153955/218827011-2e4e831b-3541-4eb1-ba1f-432e4a534bb2.png)

### Upload the icon source.

[file-document-refresh-outline.zip](https://github.com/Templarian/MaterialDesign/files/10735757/file-document-refresh-outline.zip)

**Comment by jhil** [comment]
The spacing is a little off, but I can help tune it!

**Comment by jhil** [comment]
[![file-document-refresh-outline](https://pictogrammers.com/library/mdi/icon/file-document-refresh-outline)](https://pictogrammers.com/library/mdi/icon/file-document-refresh-outline)
