### ISSUE TITLE
radioactive

### ISSUE THREAD

**Issue by mpardieck** [Templarian/MaterialDesign#6976]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

We already have a radioactive icon, but it does not match the real radioactive symbol. Each blade of the "propeller" and space between should be 60 degrees, but if you look at the current one, you can see the spacing is uneven (hint: look at the space on top, it's too small). I created a radially symmetrical version that matches the real symbol.

### Share a preview of your contribution.
![download](https://user-images.githubusercontent.com/60376755/219123533-cb76b7a9-d63b-441d-8bfe-3900cc019d05.png)
![download (3)](https://user-images.githubusercontent.com/60376755/219123536-20c659da-0015-4a1b-916d-91c4fadb29ac.png)
![download (1)](https://user-images.githubusercontent.com/60376755/219123538-f31a8a29-5d2e-40f3-8ef7-b67ff6b5a4bc.png)
![download (2)](https://user-images.githubusercontent.com/60376755/219123539-7ecf23e1-6621-4951-9bf4-44052e37a415.png)

### Upload the icon source.
[radioactive.zip](https://github.com/Templarian/MaterialDesign/files/10746290/radioactive.zip)

**Comment by mririgoyen** [comment]
For us to update this, we'll need to update all variants of it as well. Can you create and provide those?

**Comment by Simran-B** [comment]
The circle doesn't look like it's on the grid?

**Comment by mpardieck** [comment]
I've updated with the variants and put the circle on the grid

**Comment by mririgoyen** [comment]
Thanks for these @mpardieck. I still had to recreate all four of them because the angles were still not perfect, but it was a good call out and now they are all perfect. 👍🏼

**Comment by mririgoyen** [comment]
[![radioactive](https://pictogrammers.com/library/mdi/icon/radioactive)](https://pictogrammers.com/library/mdi/icon/radioactive)[![radioactive-off](https://pictogrammers.com/library/mdi/icon/radioactive-off)](https://pictogrammers.com/library/mdi/icon/radioactive-off)
[![radioactive-circle](https://pictogrammers.com/library/mdi/icon/radioactive-circle)](https://pictogrammers.com/library/mdi/icon/radioactive-circle)[![radioactive-circle-outline](https://pictogrammers.com/library/mdi/icon/radioactive-circle-outline)](https://pictogrammers.com/library/mdi/icon/radioactive-circle-outline)
