### ISSUE TITLE
GitHub preview generator doesn't work on Firefox

### ISSUE THREAD

**Issue by mpardieck** [Templarian/MaterialDesign#6977]
### Where are you experiencing this bug?

Somewhere else

### What is the issue you are experiencing?

The preview generator (https://pictogrammers.com/tools/github/) doesn't seem to work on Firefox, or at least not on my machine. It worked in Edge when I tested it.

**Comment by mririgoyen** [comment]
Thanks for the report. This will be addressed in https://github.com/Pictogrammers/pictogrammers.com/pull/63.

In the future, please open an issue there. This repo is specifically for Material Design Icons issues. 😄
