### ISSUE TITLE
Network-attached storage icon

### ISSUE THREAD

**Issue by Tonza** [Templarian/MaterialDesign#698]
We already have harddisk icon, but it would be great to have network-attached harddisk / storage icon too.

**Comment by CoDEmanX** [comment]
There's little space for that, so I had to violate a couple guideline rules for:

![nas](https://cloud.githubusercontent.com/assets/1309249/10096182/d34072f6-636f-11e5-91bc-6c42644f7215.png) https://www.dropbox.com/s/9lerugxlyv0hw4n/nas.svg?dl=0

**Comment by Tonza** [comment]
Great looking icons, thank you!

**Comment by CoDEmanX** [comment]
@Templarian: what do you think about the 2nd?

**Comment by Templarian** [comment]
I think the 2nd one with just 2 discs would be the best.

**Comment by CoDEmanX** [comment]
You mean like this?

![nas4](https://cloud.githubusercontent.com/assets/1309249/10835089/3bb5cf26-7e9f-11e5-9ba5-8ee62aaebc86.png) https://www.dropbox.com/s/nt8q66un8accr5y/nas4.svg?dl=0

**Comment by PeterShaggyNoble** [comment]
This was added as `server-network` a while ago so closing this out.

[![server-network](https://user-images.githubusercontent.com/15157491/33939545-8a61173a-e003-11e7-8cbd-2bde250fa26b.png)](https://materialdesignicons.com/icon/server-network)
