### ISSUE TITLE
thermostat-cog 

### ISSUE THREAD

**Issue by martinmoravek** [Templarian/MaterialDesign#6985]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

to adjust temperature in the room (on thermostat)

### Give us an example of what this icon might look like.

similar to e.g. window-shutter-cog but instead shutter there might be thermostat of thermometer or riadiator icon (or all options)

**Comment by jhil** [comment]
[![thermostat-cog](https://pictogrammers.com/library/mdi/icon/thermostat-cog)](https://pictogrammers.com/library/mdi/icon/thermostat-cog)
