### ISSUE TITLE
Olympic Rings

### ISSUE THREAD

**Issue by hoyamike** [Templarian/MaterialDesign#699]
Olympic Rings icon would be nice.

**Comment by CoDEmanX** [comment]
They are not monochromatic, and way too thin for this icon pack.

**Comment by Templarian** [comment]
![small](https://cloud.githubusercontent.com/assets/338885/10211897/d3db06a2-67bd-11e5-9d47-40f4f7fbc31d.png) ![larger](https://cloud.githubusercontent.com/assets/338885/10211902/df5df57a-67bd-11e5-8b2c-eb5c4fe905d6.png)

Yea, it's kind of hard to see the reference to Olympic rings.

**Comment by CoDEmanX** [comment]
Could be confused with brass knuckled, ouch. But it's not too bad actually. In a sporty context it would work I guess.

**Comment by hoyamike** [comment]
Haha - this looks good- thanks

On Sunday, October 4, 2015, CoDEmanX <notifications@github.com> wrote:

> Could be confused with brass knuckled, ouch. But it's not too bad
> actually. In a sporty context it would work I guess.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/699#issuecomment-145376156>
> .
>


-- 


Mike Stahr
Founder and CEO

[image: Running2win]

*Athletic Performance Tools LLC.*
507 South College Ave. | Building F, Room 5 | Oxford, OH 45056
tel (513) RUNNING <(513)+786-6464>
*Email <mike@running2win.com> | Running2Win.com <http://running2win.com/> *

**Comment by JamesCoyle** [comment]
Gonna close this as it's better suited to inline vectors with colors.
