### ISSUE TITLE
cloud-key

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#6990]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

cloud + key icon

example use case: single sign-on

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/55925048/221593912-752a325f-6e61-4d31-a0fa-854caed65ffa.png)
![image](https://user-images.githubusercontent.com/55925048/221594002-aa39cba5-3955-4ce1-a467-c745c42e5a77.png)

### Upload the icon source.

[cloud-key.zip](https://github.com/Templarian/MaterialDesign/files/10840748/cloud-key.zip)

**Comment by mririgoyen** [comment]
[![cloud-key](https://pictogrammers.com/library/mdi/icon/cloud-key)](https://pictogrammers.com/library/mdi/icon/cloud-key)[![cloud-key-outline](https://pictogrammers.com/library/mdi/icon/cloud-key-outline)](https://pictogrammers.com/library/mdi/icon/cloud-key-outline)
