### ISSUE TITLE
turbine icon not centered

### ISSUE THREAD

**Issue by fwedler** [Templarian/MaterialDesign#6991]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

When animating the `turbine` icon top spin, the icon wobbles while spinning showing that the art is not properly centered. The frame center is at 4.25 x 4.25mm but the art is at 4.233 x 4.233mm.
Re-centered svg attached.

![turbine](https://user-images.githubusercontent.com/6677331/221659339-93449764-8cfb-4d87-a0b8-89829b5ce12f.svg)

**Comment by mririgoyen** [comment]
Updated.
