### ISSUE TITLE
Set operation icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#700]
Sets:
![sets-union2](https://cloud.githubusercontent.com/assets/1309249/10124159/4e172166-654e-11e5-9856-5bc10d9de813.png) union
![sets-intersection2](https://cloud.githubusercontent.com/assets/1309249/10124156/4e0d35a2-654e-11e5-9732-72ab62108ce8.png) intersection
![sets-diff5](https://cloud.githubusercontent.com/assets/1309249/10124153/4dfe6d4c-654e-11e5-8f8d-1c4c039979aa.png) difference (A - B)
![sets-diff5-alt2](https://cloud.githubusercontent.com/assets/1309249/10124201/99b229b2-654f-11e5-9fb9-1a6f6376ca3e.png) difference (B - A)
![sets-symmetric-diff5](https://cloud.githubusercontent.com/assets/1309249/10124158/4e0e2336-654e-11e5-9ed9-0e1e70cf7542.png) symmetric difference
Misc:
![sets-above](https://cloud.githubusercontent.com/assets/1309249/10124157/4e0d5bae-654e-11e5-958d-359ebda326a9.png) above
![sets-below](https://cloud.githubusercontent.com/assets/1309249/10124154/4dfeb216-654e-11e5-8ede-c3357db2a7b8.png) below
![sets-combine](https://cloud.githubusercontent.com/assets/1309249/10124155/4e0cecbe-654e-11e5-9596-f994ef23edd0.png) combine

Different dash style, equally sized rectangles, 1px margin on the top left:
![sets-union](https://cloud.githubusercontent.com/assets/1309249/10124233/8ee71032-6550-11e5-9360-81be49e43095.png) union
![sets-intersection](https://cloud.githubusercontent.com/assets/1309249/10124231/8ee4eabe-6550-11e5-8ad8-cf5134999f7c.png) intersection
![sets-diff2](https://cloud.githubusercontent.com/assets/1309249/10124234/8ee764e2-6550-11e5-80a9-2c1a404f48ee.png) difference (A - B)
![sets-diff2-alt](https://cloud.githubusercontent.com/assets/1309249/10124235/8ee83b74-6550-11e5-88d8-83b2e6f44e37.png) difference (B - A)
![sets-symmetric-diff](https://cloud.githubusercontent.com/assets/1309249/10124262/62ea949e-6551-11e5-988c-d49c8b9959cd.png) symmetric difference
Misc:
![sets-above-alt](https://cloud.githubusercontent.com/assets/1309249/10124321/994cf0e4-6552-11e5-95d6-e7a94fe91703.png) above
![sets-below-alt](https://cloud.githubusercontent.com/assets/1309249/10124320/994c0706-6552-11e5-977f-593825bc1467.png) below
![sets-combine1](https://cloud.githubusercontent.com/assets/1309249/10124310/567dd666-6552-11e5-9448-2bb46c1e5059.png) combine

SVGs: https://www.dropbox.com/sh/pe15x4yvroqd7ma/AADuseUqrauPXm6fMhZarHBWa?dl=0

**Comment by Templarian** [comment]
Liking the second batch section since the dash looks cleaner.

**Comment by Templarian** [comment]
What do you think about putting these under the

* `vector-` naming
 * `vector-union`
 * `vector-intersection`
 * `vector-difference-ab`
 * `vector-difference-ba`
 * `vector-difference`
 * `vector-arrange-above`
 * `vector-arrange-below`
 * `vector-combine`

**Comment by derwaldgeist** [comment]
I have to agree that the second batch section is much better.

**Comment by CoDEmanX** [comment]
I think the naming scheme is fine, despite "vector-difference" not being fully correct. "vector-difference-symmetric" would be quite lengthy.

Not sure if above/below icons of the 2nd batch should be more like in the 1st batch (rectangles not touching due to 2px whitespace at contact point)

**Comment by Templarian** [comment]
https://materialdesignicons.com/history All 9 added.
