### ISSUE TITLE
hub

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#7003]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

The "hub" icon from Google. Generic enough to represent many concepts related to 'connectivity'

original: https://fonts.google.com/icons?selected=Material%20Icons%3Ahub%3A

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/55925048/222106456-c30154ce-0cd3-4baa-a4f4-71ebdcbc802b.png)
![image](https://user-images.githubusercontent.com/55925048/222107829-df169fc8-9015-4c16-bfbb-1fe328f13f0f.png)

### Upload the icon source.

[hub.zip](https://github.com/Templarian/MaterialDesign/files/10859634/hub.zip)

**Comment by mririgoyen** [comment]
[![hub](https://pictogrammers.com/library/mdi/icon/hub)](https://pictogrammers.com/library/mdi/icon/hub)[![hub-outline](https://pictogrammers.com/library/mdi/icon/hub-outline)](https://pictogrammers.com/library/mdi/icon/hub-outline)
