### ISSUE TITLE
account-injury should have person-injury alias

### ISSUE THREAD

**Issue by ClimberJ** [Templarian/MaterialDesign#7006]
### What icon would you like to alias?

account-injury

### What alias(es) should be added to the above icon?

person-injury

**Comment by Ben-Heel** [comment]
I will make any name there is no problem


هيكل

في الجمعة، ٣ مارس ٢٠٢٣ ٢:١٠ م ClimberJ ***@***.***> كتب:

**Comment by Ben-Heel** [comment]
Hidden ambition is the alias poison
