### ISSUE TITLE
bag-personal-plus-circle (outline)

### ISSUE THREAD

**Issue by mterry2718** [Templarian/MaterialDesign#7007]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Customs and border patrol wants an icon for adding personal baggage

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/123651989/222762392-986f09bd-29e8-4843-bd0e-fc5af576c6f1.png)
![image](https://user-images.githubusercontent.com/123651989/222762490-2e26d54f-22f1-4201-8c6f-7705205673a4.png)

### Upload the icon source.

[bag-personal-plus-circle.zip](https://github.com/Templarian/MaterialDesign/files/10883581/bag-personal-plus-circle.zip)

**Comment by mririgoyen** [comment]
This will need to use our standard plus modifier.

**Comment by mterry2718** [comment]
you are completely right. sorry about that. 

![image](https://user-images.githubusercontent.com/123651989/222773710-c5f7f1c2-f2ce-456a-ad72-1c2e39f051a2.png)
![image](https://user-images.githubusercontent.com/123651989/222773775-da5d5e64-0028-453a-aa51-10f27f52ef88.png)

[bag-personal-plus-circle.zip](https://github.com/Templarian/MaterialDesign/files/10884124/bag-personal-plus-circle.zip)

**Comment by mterry2718** [comment]
... just realized i used the regular plus rather than the thick plus..

![image](https://user-images.githubusercontent.com/123651989/222782476-4d596819-cb4f-4dc6-a198-9fcc4c229351.png)
![image](https://user-images.githubusercontent.com/123651989/222782561-fa01bc21-f6b9-44c1-9ecf-ec482941f673.png)

[bag-personal-plus-circle.zip](https://github.com/Templarian/MaterialDesign/files/10884511/bag-personal-plus-circle.zip)

**Comment by mterry2718** [comment]
also can i have this count for the account mat2718 rather than mterry2718?

**Comment by mat2718** [comment]
here is the same icon as above but with a bit smaller modifier in case you think the one above is to big :)

![image](https://user-images.githubusercontent.com/22265388/222788561-079cf30d-a793-4b83-9e4d-a6c786aa8e33.png)
![image](https://user-images.githubusercontent.com/22265388/222788638-9cfa3afb-ef2a-4fd1-98ee-cf5898f7865c.png)

[bag-personal-plus-outline.zip](https://github.com/Templarian/MaterialDesign/files/10884802/bag-personal-plus-outline.zip)

**Comment by mririgoyen** [comment]
[![bag-personal-plus](https://pictogrammers.com/library/mdi/icon/bag-personal-plus)](https://pictogrammers.com/library/mdi/icon/bag-personal-plus)[![bag-personal-plus-outline](https://pictogrammers.com/library/mdi/icon/bag-personal-plus-outline)](https://pictogrammers.com/library/mdi/icon/bag-personal-plus-outline)
