### ISSUE TITLE
Ciggarete icon please

### ISSUE THREAD

**Issue by stasbar** [Templarian/MaterialDesign#701]
Please ciggarete icon

**Comment by Templarian** [comment]
This icon is called `smoking` in the icon pack. There is also a `smoking-off`.

[![smoking](https://materialdesignicons.com/icon/smoking)](https://materialdesignicons.com/icon/smoking) [![smoking-off](https://materialdesignicons.com/icon/smoking-off)](https://materialdesignicons.com/icon/smoking-off)
