### ISSUE TITLE
server-info

### ISSUE THREAD

**Issue by xxredxpandaxx** [Templarian/MaterialDesign#7015]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I'm making a wiki with wiki.js and need a server info icon. Saw that there wasn't one so I use the other server icons you do have as a template.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/8936095/224219060-70232305-8fec-459b-8905-c76bc5b77902.png)

### Upload the icon source.

[server-info.zip](https://github.com/Templarian/MaterialDesign/files/10938288/server-info.zip)

**Comment by xxredxpandaxx** [comment]
First time looking through the material design info. I think I got it all, but sorry if I missed something.

**Comment by mririgoyen** [comment]
This doesn't really work and we're usually very hesitant on adding "information" variants. In this specific case, I don't think we're interested in adding this variant. You can simply use `server` or `server-outline` in the proper context.
