### ISSUE TITLE
edit-box

### ISSUE THREAD

**Issue by elmcapp** [Templarian/MaterialDesign#7017]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have a few apps that have features to allow users to edit things throughout the app. There is an edit icon but it would be nice to have an icon that is easy for users to understand. Text based icon. Example there is an icon called new-box. when looking at the app you understand what it is for. we need the same thing for edit

### Give us an example of what this icon might look like.

A good example would be and icon that is text based. For example a solid color icon that has the word EDIT.  We could call it edit-box. A good example to look at is a icon that already existed called new-box

**Comment by Templarian** [comment]
Icons cannot have text as it's not possible for us to translate them. `pencil-box` exists.
