### ISSUE TITLE
Polymer iconset is outdated

### ISSUE THREAD

**Issue by alberthier** [Templarian/MaterialDesign#702]
Hi,

You provide Polymer iconset containing all of 'Material Design Icons' (mdi.html)
But this iconset uses the old 0.5 Polymer syntax. With Polymer 1.0, some tags have changed:

`core-iconset-svg` becomes `iron-iconset-svg` and the iconset identifier must be defined in the `name` attribute, no longer `id`

So, for me, it becomes:
```
<link rel="import" href="../../bower_components/iron-iconset-svg/iron-iconset-svg.html">
<iron-iconset-svg name="mdi" size="24">
  ...
</iron-iconset-svg>
```

**Comment by Templarian** [comment]
https://materialdesignicons.com/getting-started

Next to v0.5 is now a link for v1.0. Let me know if this works.

Thanks for letting me know.

**Comment by Templarian** [comment]
Added a documentation link for `iron-iconset-svg` also.

**Comment by alberthier** [comment]
I tested your 1.0 version, it works perfectly, thanks !
