### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by sinsedrix** [Templarian/MaterialDesign#7023]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

An icon for a cash machine, order terminal or other

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/596459/225569771-b0916543-45c1-4b54-b4a6-e13e770fb7b1.png)

### Upload the icon source.

![terminal](https://user-images.githubusercontent.com/596459/225568978-1eb0392d-7b14-49b1-beae-c85714bba762.svg)

**Comment by mririgoyen** [comment]
This already exists.

[![monitor-vertical](https://pictogrammers.com/library/mdi/icon/monitor-vertical)](https://pictogrammers.com/library/mdi/icon/monitor-vertical)
