### ISSUE TITLE
Server-Outline

### ISSUE THREAD

**Issue by Kadensvw** [Templarian/MaterialDesign#7024]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

We only use outline icons at the place I work and we needed a icon for server. There is several versions of server but they are all filled. The filled icons are smaller than I was able to get the outlined version so there is only 2 shapes when the filled version has 3.
 

### Share a preview of your contribution.

![server-outline-preview](https://user-images.githubusercontent.com/105304911/225720215-23d1a562-19ea-478d-bd55-6f28a47947e6.png)

### Upload the icon source.

[server-outline.zip](https://github.com/Templarian/MaterialDesign/files/10994700/server-outline.zip)

**Comment by mririgoyen** [comment]
[![server-outline](https://pictogrammers.com/library/mdi/icon/server-outline)](https://pictogrammers.com/library/mdi/icon/server-outline)
