### ISSUE TITLE
Server-Minus-Outline

### ISSUE THREAD

**Issue by Kadensvw** [Templarian/MaterialDesign#7025]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Variant on server minus but outlined. 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/105304911/225723067-ade92e18-ba47-4207-99c1-0026c4a4cdfe.png)

### Upload the icon source.

[server-minus-outline.zip](https://github.com/Templarian/MaterialDesign/files/10994816/server-minus-outline.zip)

**Comment by suterma** [comment]
This looks nice for a server. 

I suggest having the minus sign in the lower right corner, like most icons do. Here is an example: https://pictogrammers.com/library/mdi/icon/book-minus/

**Comment by Kadensvw** [comment]
I tried keeping it similar to server minus so that it would just serve as a outline variant 
https://pictogrammers.com/library/mdi/icon/server-minus/

**Comment by mririgoyen** [comment]
[![server-minus-outline](https://pictogrammers.com/library/mdi/icon/server-minus-outline)](https://pictogrammers.com/library/mdi/icon/server-minus-outline)
