### ISSUE TITLE
Server-Pluse-Outline

### ISSUE THREAD

**Issue by Kadensvw** [Templarian/MaterialDesign#7026]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Variant on server minus but outlined. 

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/105304911/225726598-b9d6ec96-bf40-4925-82cc-c814cd629f5f.png)

### Upload the icon source.

[server-plus-outline.zip](https://github.com/Templarian/MaterialDesign/files/10994925/server-plus-outline.zip)

**Comment by suterma** [comment]
This looks nice for a server. 

I suggest having the plus sign in the lower right corner, like most icons do. Here is an example: https://pictogrammers.com/library/mdi/icon/web-plus/

**Comment by Kadensvw** [comment]
I wanted it to be just a variant of the server icons already in so I tried to keep it like server plus https://pictogrammers.com/library/mdi/icon/server-plus/

**Comment by mririgoyen** [comment]
[![server-plus-outline](https://pictogrammers.com/library/mdi/icon/server-plus-outline)](https://pictogrammers.com/library/mdi/icon/server-plus-outline)
