### ISSUE TITLE
Server-Network-Outline

### ISSUE THREAD

**Issue by Kadensvw** [Templarian/MaterialDesign#7027]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

outline variant of server network

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/105304911/225729249-9140537e-6423-4061-a7e8-5e9fa019f699.png)

### Upload the icon source.

[server-network-outline.zip](https://github.com/Templarian/MaterialDesign/files/10995044/server-network-outline.zip)

**Comment by mririgoyen** [comment]
[![server-network-outline](https://pictogrammers.com/library/mdi/icon/server-network-outline)](https://pictogrammers.com/library/mdi/icon/server-network-outline)
