### ISSUE TITLE
live broadcast icon. 

### ISSUE THREAD

**Issue by ch-muhammad-adil** [Templarian/MaterialDesign#703]
![screen shot 2015-09-28 at 12 16 18](https://cloud.githubusercontent.com/assets/8264639/10129724/d5f569bc-65da-11e5-9fcb-206cedcc86ac.png)

**Comment by CoDEmanX** [comment]
There's already a satellite icon:
[![sat](https://materialdesignicons.com/icon/satellite-variant)](https://materialdesignicons.com/icon/satellite-variant)

The [AP icon I posted](https://github.com/Templarian/MaterialDesign/issues/369#issuecomment-142259863) would also work.

**Comment by ch-muhammad-adil** [comment]
yes i knew this .. but i was looking for something like that.. can't u add that ?

**Comment by CoDEmanX** [comment]
By "something like that", are you referring to the AP icon? I hope @Templarian adds it soon.

**Comment by CoDEmanX** [comment]
There's also this really nice radio tower icon:

[![radio-tower](https://materialdesignicons.com/icon/radio-tower)](https://materialdesignicons.com/icon/radio-tower)

**Comment by ch-muhammad-adil** [comment]
no last one is the most similar I have required. Thank you .. :)

**Comment by Templarian** [comment]
Just added `access-point` and `access-point-network` if you had planned to use either of those.

**Comment by ch-muhammad-adil** [comment]
one thing please if you can do at the website. Please add searching feature in your website, it is really a hard work to find an icon from the list.

**Comment by Templarian** [comment]
There is a giant search box at the very top that filters the icons.

**Comment by ch-muhammad-adil** [comment]
Oh yes there is a white space beside tag dropdown with no search icon, no
hint that user have to search here. I really found it today . (Mysterious)

Regards,
Muhammad Adil

**Comment by Templarian** [comment]
Added a placeholder text of "Search...". It's more obvious in the redesign. A lot more work until that redesign goes live though to production.

**Comment by ch-muhammad-adil** [comment]
(y)  :)

**Comment by ch-muhammad-adil** [comment]
I am using mac there is no placeholder when I open in chrome using mac. 
but in windows I can see it using chrome.
