### ISSUE TITLE
Molecules

### ISSUE THREAD

**Issue by Juffle74** [Templarian/MaterialDesign#7031]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Air quality sensor in Home Assistant, weather air quality informations...

### Give us an example of what this icon might look like.

Similar to the Material Design Icons "molecule-co2"...

CH20
Pm1
Pm2.5
Pm10

**Comment by MrGrigri** [comment]
As discussed in #2475, we're not going to add every chemical compound as that could get crazy.
