### ISSUE TITLE
Warehouse have no filled state

### ISSUE THREAD

**Issue by QusayNaser** [Templarian/MaterialDesign#7037]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [x] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

it has no filled state, its only the outline
it's needed when using bottom bar tabs.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/50047122/227189185-d2e6d820-f63e-42de-bb7e-3383eeb01f9b.png)

### Upload the icon source.

[warehouse-filled.zip](https://github.com/Templarian/MaterialDesign/files/11050153/warehouse-filled.zip)

**Comment by suterma** [comment]
Are the upper rectangles windows? Warehouses typically don't have these.

**Comment by MrGrigri** [comment]
The current warehouse icon represents an open bay with boxes, so there isn't enough space.

**Comment by QusayNaser** [comment]
> Are the upper rectangles windows? Warehouses typically don't have these.

there is outlined version have those, so I just flipped few colors to be more suitable

**Comment by mririgoyen** [comment]
The current icon does not lend itself to an outlined version. Thanks for the suggestion.
