### ISSUE TITLE
tag-edit Icon

### ISSUE THREAD

**Issue by DrCQ** [Templarian/MaterialDesign#7038]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I suggest creating an "edit tag" icon. This should look like tag-arrow-... icons and tag-plus or tag-minus icon, but with the pencil in the left-down corner. I would use this icon to indicate a possibility of editing for the image metatags.

### Give us an example of what this icon might look like.

 

![EditTag](https://user-images.githubusercontent.com/49019093/227232616-2800207f-f828-42b9-8979-6b2161671117.png)

**Comment by MrGrigri** [comment]
I believe the circle cut-out will bee too much. 

![tag-edit](https://user-images.githubusercontent.com/4528551/228608097-e0d47ec7-b810-4459-94a0-fb0638146cb9.png) ![tag-edit-outline](https://user-images.githubusercontent.com/4528551/228608203-f0db695b-c468-4ef3-be4f-153d8b0bfc08.png)

---

![tag-edit-outline](https://user-images.githubusercontent.com/4528551/228608982-36045c73-4b20-4e5a-85ce-2b63f59eb3f5.svg) ![tag-edit](https://user-images.githubusercontent.com/4528551/228608983-c8356904-3317-4ff2-ab10-4ca52fc4187d.svg)

**Comment by mririgoyen** [comment]
[![tag-edit](https://pictogrammers.com/library/mdi/icon/tag-edit)](https://pictogrammers.com/library/mdi/icon/tag-edit)[![tag-edit-outline](https://pictogrammers.com/library/mdi/icon/tag-edit-outline)](https://pictogrammers.com/library/mdi/icon/tag-edit-outline)
