### ISSUE TITLE
Oscillating

### ISSUE THREAD

**Issue by matthiasdebaat** [Templarian/MaterialDesign#7039]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

In Home Assistant you can have an oscillating fan. We don't have an arrow icon that correspondent this feature. A request has been submitted previously https://github.com/Templarian/MaterialDesign/issues/5677.

I've used `mdi:cached` as base for this design.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/20203284/227253343-b952399c-f661-4daa-8a2f-d87ca9ecccd6.png)

### Upload the icon source.

[Affinity Designer 2 and SVG files ](https://github.com/Templarian/MaterialDesign/files/11052673/oscillating.zip)

**Comment by matthiasdebaat** [comment]
That could work too, see below. I've also added a off variant, based on other off icons. This breaks the right arrow, not sure if this is the way to go?

![oscillating](https://user-images.githubusercontent.com/20203284/231756563-b49bb0ba-341c-44c6-9312-9df9b7db3358.svg)
![oscillating-off](https://user-images.githubusercontent.com/20203284/231756592-db2b1e52-bfac-4d7a-a192-50dd8bd10347.svg)

**Comment by mririgoyen** [comment]
[![arrow-oscillating](https://pictogrammers.com/library/mdi/icon/arrow-oscillating)](https://pictogrammers.com/library/mdi/icon/arrow-oscillating)[![arrow-oscillating-off](https://pictogrammers.com/library/mdi/icon/arrow-oscillating-off)](https://pictogrammers.com/library/mdi/icon/arrow-oscillating-off)
