### ISSUE TITLE
A 'file-lock' icon (Contribution attached)

### ISSUE THREAD

**Issue by alberthier** [Templarian/MaterialDesign#704]
I needed a 'file-lock' icon similar to 'folder-lock'
It wasn't available, so I made it, here is the file.
Feel free to integrate it in the library.

https://www.dropbox.com/s/q1fem0rdlgz5vou/file-lock.svg?dl=0

**Comment by Templarian** [comment]
[![file-lock](https://materialdesignicons.com/icon/file-lock)](https://materialdesignicons.com/icon/file-lock)

Thanks!
