### ISSUE TITLE
hours-12

### ISSUE THREAD

**Issue by circa1665** [Templarian/MaterialDesign#7053]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To illustrate a period of 12 hours / 12 hour clock.

The 12 hour variant of this existing 24 hours icon: 
![hours-24](https://user-images.githubusercontent.com/33236082/229311011-7b41f08c-e113-4b6c-a4d3-1fadf8c829a5.png)

### Give us an example of what this icon might look like.

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" style="enable-background:new 0 0 24 24" xml:space="preserve"><path d="M13 2v2c4 .5 7 3.8 7 7.9 0 3.2-1.9 6-4.7 7.3L13 17v5h5l-1.2-1.2c3.1-1.7 5.2-5 5.2-8.8 0-5.2-4-9.5-9-10m-2 0c-1.9.2-3.8 1-5.3 2.2l1.4 1.4C8.2 4.8 9.6 4.2 11 4V2M4.2 5.7C3 7.2 2.2 9.1 2 11h2c.2-1.4.8-2.8 1.6-3.9L4.2 5.7M2 13c.2 1.9 1 3.8 2.2 5.3l1.4-1.4C4.8 15.8 4.2 14.4 4 13H2m5.1 5.4-1.4 1.4c1.5 1.2 3.4 2 5.3 2.2v-2c-1.4-.2-2.8-.8-3.9-1.6zM11 8v2h3v1h-1c-1.1 0-2 .9-2 2v3h5v-2h-3v-1h1c1.1 0 2-.9 2-2v-1c0-1.1-.9-2-2-2h-3m-3 2v6h2V8H9c-1.1 0-2 .9-2 2h1z"/></svg>`

![Layer 1@4x](https://user-images.githubusercontent.com/33236082/229311164-f3eda41a-6206-44ae-9e4f-803046c817ce.png)

**Comment by MrGrigri** [comment]
You can use our helpful preview generator found [here](https://pictogrammers.com/tools/github/).

![hours-12](https://user-images.githubusercontent.com/4528551/230449282-846b3b4e-fca3-472e-b885-9a62365c2ddd.png)

**Comment by mririgoyen** [comment]
[![hours-12](https://pictogrammers.com/library/mdi/icon/hours-12)](https://pictogrammers.com/library/mdi/icon/hours-12)
