### ISSUE TITLE
A volume + vibrate icon

### ISSUE THREAD

**Issue by guil18** [Templarian/MaterialDesign#706]
We have a "vibrate" icon, and a "volume" icon.
It would be nice to have a "volume + vibrate" icon like when you setup an alarm with a ringtone and vribate settings.
Thanks!

**Comment by CoDEmanX** [comment]
![vibrator](https://cloud.githubusercontent.com/assets/1309249/10141528/4a6b0806-660d-11e5-9799-f729ad8ab381.png) It vibrates and I'm pretty sure there's also some noise involved.

**Comment by guil18** [comment]
Well, how to put this.
thanks ! :+1: 
Not sure if I can use it though.

**Comment by CoDEmanX** [comment]
Was just kidding. Do you have an actual example of how it would look like?

**Comment by guil18** [comment]
Yeah I know.
Needless to say I laughed hard! Even showed it to my wife ;)
Well, this one is a "vibrate without sound" icon from a samsung phone.
![vibrate_without_sound](https://cloud.githubusercontent.com/assets/5067308/10145848/dfb97a10-6625-11e5-9693-82824eae179f.png)
which is equivalent of the following one (taken from google material design icons library) :
![ic_vibration_black_24dp](https://cloud.githubusercontent.com/assets/5067308/10145867/00f0f640-6626-11e5-93da-c459a155fb54.png)

But, I cannot find an icon which mixes the vibrations and the "volume up" as below :
![ic_volume_up_black_24dp](https://cloud.githubusercontent.com/assets/5067308/10145955/86a5121c-6626-11e5-9db3-d69205b17eee.png)
or, even one which mixes the vibrations with the "no volume" as below, which would be more consistent than the one from google:
![ic_volume_off_black_24dp](https://cloud.githubusercontent.com/assets/5067308/10145964/9426555e-6626-11e5-905f-93c50b3bfc78.png)

Again, thanks for your help !

**Comment by CoDEmanX** [comment]
There's really little space, and it looks odd to combine the speaker shape with a zig-zag pattern:
![volume-vibrate3](https://cloud.githubusercontent.com/assets/1309249/10147767/4d3b1878-6630-11e5-9c2c-8fd2b673295c.png)
![volume-vibrate2](https://cloud.githubusercontent.com/assets/1309249/10147768/4d51999a-6630-11e5-9899-6aa3f6669390.png)

A more abstract variant, which is way cleaner:
![volume-vibrate](https://cloud.githubusercontent.com/assets/1309249/10147776/5e1cde42-6630-11e5-92de-3ce4cedb0f1d.png)

**Comment by guil18** [comment]
Indeed, you're right!
The third one looks great!
Thanks for your help!

**Comment by CoDEmanX** [comment]
The 3rd one looks actually like the icon they use in Chrome, to indicate which which tabs have sound output:
![chrome](https://cloud.githubusercontent.com/assets/1309249/10836875/2dc3e038-7eb3-11e5-8111-fbddb4cbb1a8.PNG)

**Comment by CoDEmanX** [comment]
@Templarian: would you be okay with adding my 3rd attempt? It could be a variant of `volume-high`. People may use it to represent different things, it's quite generic.

**Comment by CoDEmanX** [comment]
Oh, and I can also provide the sex toy icon if you want ;)

**Comment by goyney** [comment]
Removing Contribution label since no source SVG was provided.

**Comment by CoDEmanX** [comment]
Do we want to include either of the icons? I can search for the source files then.

**Comment by PeterShaggyNoble** [comment]
How does it look using `volume-low` as the base icon?

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/61859241-090c3d00-aec8-11e9-81dc-3c7ea1904175.png)

Flipping the zig-zag line makes it look as something is coming from the speaker. With zig-zags on both sides it becomes really noisy. Not sure about the placement however, should everything be centered?

**Comment by goyney** [comment]
[![volume-source](https://materialdesignicons.com/icon/volume-source)](https://materialdesignicons.com/icon/volume-source)[![volume-vibrate](https://materialdesignicons.com/icon/volume-vibrate)](https://materialdesignicons.com/icon/volume-vibrate)
