### ISSUE TITLE
offroad\road-off

### ISSUE THREAD

**Issue by mazedesign** [Templarian/MaterialDesign#7061]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

car rental app, users can flag if they intend to take the car off-road to better select the car for their requirement.

### Give us an example of what this icon might look like.

mdi-road with a bar across or a snaking road without markings, I'd prefer the latter which could be also used in navigation to signify a rugged road, but the former is straightforward and would also work for our use-case.

**Comment by MrGrigri** [comment]
What about these?

![image](https://user-images.githubusercontent.com/4528551/230443363-498b05ab-70ca-4398-bdc5-2eae58bd2d37.png) ![image](https://user-images.githubusercontent.com/4528551/230443302-c249eda8-9fca-4ec9-920f-d957a9d28547.png)

---

![truck-offroad](https://user-images.githubusercontent.com/4528551/230443507-818e8dc4-e2f0-4d58-811e-eea18522a5cd.svg) ![truck-offroad-off](https://user-images.githubusercontent.com/4528551/230443505-2f4e5a60-2f76-4c25-be42-81437e0da5d0.svg)

**Comment by mazedesign** [comment]
They are indicating a specific vehicle category in my context,
for example, i may ask the "off-road" question to a client that is booking an SUV or a different vehicle category, so using the pickup truck icon (which i already use for the vehicle category) would be confusing.

**Comment by MrGrigri** [comment]
I doubt that we will make an off road icon for each vehicle type. Since off roading is generally done with a truck or Jeep, then that is what makes the most sense.

**Comment by MrGrigri** [comment]
Also, off roading is more depicted as going up hill. So here's a small change. 

![image](https://user-images.githubusercontent.com/4528551/230645473-c87e9ed8-c57f-4333-ae63-4a763ca02360.png) ![image](https://user-images.githubusercontent.com/4528551/230645449-d038631e-9635-4fbd-800b-ecce8d38b5d7.png)

---

![truck-off-road](https://user-images.githubusercontent.com/4528551/230645607-01d18ced-c0d0-400b-bbfc-91008bba6f02.svg) ![truck-off-road-off](https://user-images.githubusercontent.com/4528551/230645604-a433ea09-cf8d-43a3-a8bf-99db3d200c59.svg)

**Comment by mazedesign** [comment]
> I doubt that we will make an off road icon for each vehicle type. Since off roading is generally done with a truck or Jeep, then that is what makes the most sense.

that's why I'd emphasize the road over the vehicle, you can also go off the asphalt on foot :)

**Comment by MrGrigri** [comment]
`mdi-road` with a slash would represent a road closure, and not off road. and a windy road without marking would not look like a road, but a squiggly line. The best representation of off road would the something akin to the icon above.

**Comment by mririgoyen** [comment]
[![truck-off-road](https://pictogrammers.com/library/mdi/icon/truck-off-road)](https://pictogrammers.com/library/mdi/icon/truck-off-road)[![truck-off-road-off](https://pictogrammers.com/library/mdi/icon/truck-off-road-off)](https://pictogrammers.com/library/mdi/icon/truck-off-road-off)
