### ISSUE TITLE
door-closed-cancel

### ISSUE THREAD

**Issue by gbettinazzi** [Templarian/MaterialDesign#7062]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To indicate that a door or meeting room is not available

### Give us an example of what this icon might look like.

The icon will looks like the "door" or "door-closed" icon but with a "forbidden" or "crossed-out" signal. 
Thanks for the support and the amazing library

**Comment by MrGrigri** [comment]
What about something like this?

![door-closed-cancel](https://user-images.githubusercontent.com/4528551/230656730-59b85d58-b1da-4b1e-a69d-55864a27553f.png)

---
![door-closed-cancel](https://user-images.githubusercontent.com/4528551/230656758-1d825dc0-6df7-43cf-99f6-e4303713d0fb.svg)

**Comment by gbettinazzi** [comment]
yes that will be perfect to indicate that the door is forbidden somehow!

**Comment by mririgoyen** [comment]
[![door-closed-cancel](https://pictogrammers.com/library/mdi/icon/door-closed-cancel)](https://pictogrammers.com/library/mdi/icon/door-closed-cancel)
