### ISSUE TITLE
router-network-wireless

### ISSUE THREAD

**Issue by martinmoravek** [Templarian/MaterialDesign#7067]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

network router with wifi connect to lan

there is icon router-wireless but withous connection to LAN like router network ... the other LAN elements have link to lan ... just as variant

### Give us an example of what this icon might look like.

combination of these 2 icons

![image](https://user-images.githubusercontent.com/14981833/230766951-157154e9-2cf1-4cba-93d4-63073e9b2375.png)

**Comment by MrGrigri** [comment]
![router-network-wireless](https://user-images.githubusercontent.com/4528551/230939942-175965c9-f1d1-4ac4-b3e9-15bc6e304bec.png)

---

![router-network-wireless](https://user-images.githubusercontent.com/4528551/230940026-757b263f-0e64-4ad5-bba2-63b4693eb85d.svg)

**Comment by mririgoyen** [comment]
[![router-network-wireless](https://pictogrammers.com/library/mdi/icon/router-network-wireless)](https://pictogrammers.com/library/mdi/icon/router-network-wireless)
