### ISSUE TITLE
Log icons for Verbose, Debug, Info, Warning and Error.

### ISSUE THREAD

**Issue by TheEggi** [Templarian/MaterialDesign#707]
Would use something like "message-alert" with something different than the exclamation mark.

**Comment by CoDEmanX** [comment]
Level | Symbol
---|---
Error / Fatal | `x` (usually in a circle though, not a triangle)
Warning | `!`
Info | `i` (rather in a circle than a triangle)
Trace | ??? Maybe an arrow pointing down? Or `...`?
Debug | ???
All | `*`?

**Comment by TheEggi** [comment]
Maybe something like

Level | Symbol
------------ | -------------
Trace | Magnifying glass in a circle
Debug | Bug in a circle
All | * or + in a circle

**Comment by IgnaciodeNuevo** [comment]
It also would be great to have an outline something like this

![alert](https://cloud.githubusercontent.com/assets/10051329/10877255/e207f848-8144-11e5-83aa-76a93f32a09c.jpg)

**Comment by CoDEmanX** [comment]
Error/Fatal, Warning and Info are fulfilled:

[![close-octagon](https://materialdesignicons.com/icon/close-octagon)](https://materialdesignicons.com/icon/close-octagon)
[![close-octagon-outline](https://materialdesignicons.com/icon/close-octagon-outline)](https://materialdesignicons.com/icon/close-octagon-outline)
[![alert](https://materialdesignicons.com/icon/alert)](https://materialdesignicons.com/icon/alert)
[![alert-outline](https://materialdesignicons.com/icon/alert-outline)](https://materialdesignicons.com/icon/alert-outline)
[![information](https://materialdesignicons.com/icon/information)](https://materialdesignicons.com/icon/information)
[![information-outline](https://materialdesignicons.com/icon/information-outline)](https://materialdesignicons.com/icon/information-outline)

As for trace, https://design.google.com/icons/#ic_list should work (needs to be added to MDI as part of #420).

I don't think the bug icon fits in a circle...

"All" is not a real debug level, is it? It's more like all levels from Debug/Trace through Error/Fatal.

**Comment by CoDEmanX** [comment]
#755 would probably fulfill "trace".

A simplified version of the following would also work:

![Imgur](http://i.imgur.com/6CNQzNc.jpg?1)

**Comment by PeterShaggyNoble** [comment]
`bug` has since been added and, as Cody said, #755 could fulfill the trace request so closing this out.

[![bug](https://user-images.githubusercontent.com/15157491/33939402-f4c8684a-e002-11e7-90c5-23129d1f4d28.png)](https://materialdesignicons.com/icon/bug)
