### ISSUE TITLE
Menu Open/Close

### ISSUE THREAD

**Issue by brylee123** [Templarian/MaterialDesign#7071]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

So I see that there is a menu open icon but it would be great if there was one that was the opposite of it. I am using it for a horizontally collapsible navbar where it goes from Icon+Text to just Icon. It would be great to toggle left and right and have the icons reflect it.

Thank you!

### Give us an example of what this icon might look like.

Hamburger Menu Icon with a right facing chevron. Exactly like this one but the arrow pointing right.
https://pictogrammers.com/library/mdi/icon/menu-open/

**Comment by MrGrigri** [comment]
Something like this?

![menu-close](https://user-images.githubusercontent.com/4528551/230988431-9f877694-251a-4f92-b3ac-31780bf7bcbf.png) ![menu-open](https://user-images.githubusercontent.com/4528551/230988568-e0c2fd2f-b3b4-471e-b7cf-4ab1fdac856e.png)


---

![menu-close](https://user-images.githubusercontent.com/4528551/230988479-2aea8421-1c11-4670-a7db-8d9eb48e199b.svg)

**Comment by brylee123** [comment]
Yes! That is perfect! Exactly what I was thinking. Thank you!

**Comment by mririgoyen** [comment]
[![menu-open](https://pictogrammers.com/library/mdi/icon/menu-open)](https://pictogrammers.com/library/mdi/icon/menu-open)[![menu-close](https://pictogrammers.com/library/mdi/icon/menu-close)](https://pictogrammers.com/library/mdi/icon/menu-close)
