### ISSUE TITLE
profile icon

### ISSUE THREAD

**Issue by TahirRida** [Templarian/MaterialDesign#7073]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

this icon is used for a user profile. when clicked, it takes the user to its own profile

### Give us an example of what this icon might look like.

For example, on a mobile/Web App, this may be used to show the user its own profile when he clicks on it

**Comment by MrGrigri** [comment]
From a UI/UX perspective, this is best and most commonly handled by the user clicking on their own profile picture. However, in the absence of a picture, it is common to use the `account` or `account-settings` icon. 

![account](https://user-images.githubusercontent.com/4528551/231262073-0b69b4f7-8cbe-49e1-b1a2-4ee7361fe97e.png) 
![account-settings](https://user-images.githubusercontent.com/4528551/231262205-6eb559a9-237d-4d46-998d-9bc41519da70.png)
