### ISSUE TITLE
I have a DuoTone version of Material Design Icons

### ISSUE THREAD

**Issue by ramoneeza** [Templarian/MaterialDesign#7074]
### What is your question?

I have a DuoTone version of Material Design Icons. May I publish it or doing something with those icons?

**Comment by ramoneeza** [comment]
![image](https://user-images.githubusercontent.com/891592/232753547-6363206f-d8ba-45b7-a639-dbd24e9da436.png)

**Comment by Templarian** [comment]
Closing this as DuoTone is outside of the scope of the project at the moment, but you can do anything as long as you're following the license.

https://pictogrammers.com/docs/general/license/
