### ISSUE TITLE
Charity Search

### ISSUE THREAD

**Issue by RyanD** [Templarian/MaterialDesign#7076]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The icon would be for locating a charity

### Give us an example of what this icon might look like.

The current charity icon inlaid with a magnifying glass.. it's a little rough with the charity icon but I mean it gets the job done.
![charity (5)](https://user-images.githubusercontent.com/163866/232163320-84d9cb7c-e106-4286-8fe7-83c5c2a02e39.svg)

**Comment by RyanD** [comment]
please forgive any bad or inefficient svg pathing, I just cobbled it in illustrator based on the car-search magnifying glass and the charity icon :)

**Comment by MrGrigri** [comment]
We do have a tool to help with generating presentation of the icon. At 1x, it may bee too complicated.

![image](https://user-images.githubusercontent.com/4528551/232255401-85ae3bb8-25d6-4474-8cf8-b9ed4cf07d52.png)

---

![charity-search](https://user-images.githubusercontent.com/4528551/232255410-cd6efde0-b658-4dae-a5eb-7b07e265ea75.svg)

**Comment by MrGrigri** [comment]
Contribution should go to @RyanD

**Comment by RyanD** [comment]
I don't disagree with your observation at all @MrGrigri ... and I'd be thrilled to have a better idea... I was just sort of following the convention of other search variants.  I'll look around and see if I can spot another concept that may play better with the charity icon base :)

**Comment by RyanD** [comment]
Maybe it looks better with the magnifying glass on the other side?  Sorry I don't see how to use the WIP presentation tool which look pretty slick :) 

![charity-search-alt](https://user-images.githubusercontent.com/163866/232256497-fd03971d-271f-4254-9f0d-93f627fd1906.svg)

**Comment by mririgoyen** [comment]
[![charity-search](https://pictogrammers.com/library/mdi/icon/charity-search)](https://pictogrammers.com/library/mdi/icon/charity-search)[![heart-search](https://pictogrammers.com/library/mdi/icon/heart-search)](https://pictogrammers.com/library/mdi/icon/heart-search)

**Comment by mririgoyen** [comment]
Welcome to the community, @RyanD!
