### ISSUE TITLE
Roon

### ISSUE THREAD

**Issue by gimgel** [Templarian/MaterialDesign#7077]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Hi
i want use this icon to distinguish my displays controlled by ROON vs those controlled by SONOS.
Ty

### Give us an example of what this icon might look like.

this icon might be the "circle" used by Roon

**Comment by mririgoyen** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
