### ISSUE TITLE
rutube.ru icon needed

### ISSUE THREAD

**Issue by ildaroit** [Templarian/MaterialDesign#708]
Hi! rutube.ru icon is needed!

**Comment by Templarian** [comment]
Never heard of it. Will have to do some research. Looks like a youtube clone, so probably not?

The new guidelines being retroactively put into place are removing icons that have brands that do not fall in social media "area".

**Comment by ildaroit** [comment]
Hi! Ea, this is russian youtube analog )
Hmm :(

**Comment by Templarian** [comment]
That will work, do they have an icon? All I'm seeing is the text for their logo.

**Comment by ildaroit** [comment]
Yes, iconhttp://www.google.ru/imgres?imgurl=http://img.over-blog-kiwi.com/0/85/50/45/20150126/ob_c82bc8_rutube-logo.png&imgrefurl=http://www.iconshut.com/kiwi-logopng-icons/dT1hSFIwY0RvdkwzZDNkeTVyYVhkcFptbDBibVZ6YzJsdVpIa3VZMjl0TDJ0cGQybGZiRzluYnk1d2JtY3x1cj1odHRwOi8va2l3aWZpdG5lc3NpbmR5LmNvbXx3PTMxODF8aD0xOTgwfHQ9cG5nfA/&h=421&w=1000&tbnid=Glq-oGgvUm-fuM:&docid=konUHkpF3TTQ5M&ei=stEOVobeHejlywPan7uwAg&tbm=isch&client=ms-android-om-lge&ved=0CB8QMygFMAVqFQoTCIb_5vm5pMgCFejycgod2s8OJg

**Comment by Templarian** [comment]
Circle with an RU in it? Would people even know what that was?
