### ISSUE TITLE
car-door-unlocked

### ISSUE THREAD

**Issue by Vitani** [Templarian/MaterialDesign#7080]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To show the status of a car door lock; we can currently show that a car door is locked, but not (at least obviously) *un*locked

### Give us an example of what this icon might look like.

![image](https://user-images.githubusercontent.com/5907401/232456364-7c1e9ed9-08df-4a0c-9578-1d577f888081.png)

**Comment by MrGrigri** [comment]
We don't really do the lock's shackle swiveled open, just open. There are only a couple of instances with that variant. 

![car-door-lock-open](https://user-images.githubusercontent.com/4528551/232535084-337ab0e7-f648-4ee0-b30d-b42344014b0e.png)

---

![car-door-lock-open](https://user-images.githubusercontent.com/4528551/232535379-3fbc8ff5-a99e-4abe-b3e7-a2c6a2a0ebc7.svg)

**Comment by mririgoyen** [comment]
[![car-door-lock-open](https://pictogrammers.com/library/mdi/icon/car-door-lock-open)](https://pictogrammers.com/library/mdi/icon/car-door-lock-open)

**Comment by MrGrigri** [comment]
Yes please. Create a new issue for each icon. So please open one for `car-hood(-lock && -lock-open)` and `car-trunk(-lock && -lock-open)`
