### ISSUE TITLE
Power generator icon

### ISSUE THREAD

**Issue by tamato27** [Templarian/MaterialDesign#7083]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Power

### Give us an example of what this icon might look like.

Generator Icon

**Comment by MrGrigri** [comment]
![generator-stationary](https://user-images.githubusercontent.com/4528551/233701637-31dcb5e3-6e5c-4757-bfed-2642b9f58bc6.png) ![generator-mobile](https://user-images.githubusercontent.com/4528551/233702722-a9648fda-fc00-4ed0-8478-e3dabdac3151.png) ![generator-portable](https://user-images.githubusercontent.com/4528551/233701861-c0bda679-c084-4cfd-98ab-7332d0de07d3.png)

---

![generator-mobile](https://user-images.githubusercontent.com/4528551/233702985-e35986a9-7f5a-4001-af18-664dfa024fb1.svg) ![generator-portable](https://user-images.githubusercontent.com/4528551/233702986-730c2a02-3d33-4f9a-8680-aba04bb838c2.svg) ![generator-stationary](https://user-images.githubusercontent.com/4528551/233702987-8c5844f5-3384-461c-bc0b-101b11e9785b.svg)

**Comment by tamato27** [comment]
Oh wow thats awesome! Thx man

**Comment by mririgoyen** [comment]
[![generator-stationary](https://pictogrammers.com/library/mdi/icon/generator-stationary)](https://pictogrammers.com/library/mdi/icon/generator-stationary)[![generator-portable](https://pictogrammers.com/library/mdi/icon/generator-portable)](https://pictogrammers.com/library/mdi/icon/generator-portable)[![generator-mobile](https://pictogrammers.com/library/mdi/icon/generator-mobile)](https://pictogrammers.com/library/mdi/icon/generator-mobile)
