### ISSUE TITLE
Gay Families (Variation(s) on Human-Male-Female-Child)

### ISSUE THREAD

**Issue by DarthElle13** [Templarian/MaterialDesign#7087]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I was planning on using some variation(s) of family icons for Home Assistant. However, when searching _family._ in the current library, the **only** icon picturing any actual imagery of family is of an apparent heterosexual couple with a child. Some closed issues mention this but it doesn't seem to be actually addressed in anything I could find. I am a bit surprised that this is still a gap considering the sheer size (740 forks, > 10K stars) of the project.

### Give us an example of what this icon might look like.

As human-male-female-child exists, I request a variation (or a couple) which more accurately represent the spectrum of families. There are human-male-male-child, human-female-female-child, etc families which should be represented.

**Comment by mririgoyen** [comment]
[![human-male-female-child](https://pictogrammers.com/library/mdi/icon/human-male-female-child)](https://pictogrammers.com/library/mdi/icon/human-male-female-child)[![human-male-male-child](https://pictogrammers.com/library/mdi/icon/human-male-male-child)](https://pictogrammers.com/library/mdi/icon/human-male-male-child)[![human-female-female-child](https://pictogrammers.com/library/mdi/icon/human-female-female-child)](https://pictogrammers.com/library/mdi/icon/human-female-female-child)
