### ISSUE TITLE
format-strikethrough-variant tweak

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#7088]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

The current [format-strikethrough-variant](https://pictogrammers.com/library/mdi/icon/format-strikethrough-variant/) is proportionally much bigger than the other text formatting icons, resulting in an unbalanced-looking toolbar:

![image](https://user-images.githubusercontent.com/55925048/234669346-98a00428-4ff5-4271-999e-39487c8ecf9c.png)

I propose to update this icon with the [official Google one](https://fonts.google.com/icons?selected=Material%20Icons%3Astrikethrough_s%3A), which is slightly smaller.

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/55925048/234670023-670617f0-6e4d-4e16-8dfd-457770e73951.png)

### Upload the icon source.

[strikethrough_s_black_24dp.svg.zip](https://github.com/Templarian/MaterialDesign/files/11336240/strikethrough_s_black_24dp.svg.zip)

**Comment by frankgrinaert** [comment]
It is the Google one, I was also surprised. But then when I took a closer look at the other text formatting icons (bold, italic, …), they're all a little “off-center” like this one. Maybe to accommodate some kind of decoration below it? Although I couldn't imagine what. 🤷

**Comment by mririgoyen** [comment]
This has been updated and will ship in v7.3.
