### ISSUE TITLE
code-block-angle (-square; -curly; -parentheses)

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#7089]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

"code block" icon, similar to Slack:

<img width="65" alt="image" src="https://user-images.githubusercontent.com/55925048/234678098-777d532a-4e6b-4a7d-ba44-fc35e8a26b00.png">

we have [code-not-equal-variant](https://pictogrammers.com/library/mdi/icon/code-not-equal-variant/) but I feel it doesn't look _quite_ right for this use case

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/55925048/234677883-d0fb9e5a-1895-4ffb-a082-d3fb0c79ce2e.png)

### Upload the icon source.

[code-block.svg.zip](https://github.com/Templarian/MaterialDesign/files/11336467/code-block.svg.zip)

**Comment by MrGrigri** [comment]
I actually really enjoy this one. The only downside, is now there may be requests to change the angle brackets `<>` to square `[]`, curly `{}`, or round `()`. If you fill up to the task, could you provide one for each of these then that would be best.

**Comment by frankgrinaert** [comment]
@MrGrigri thanks for the feedback, good ideas! Here's my attempt at a set:



![image](https://user-images.githubusercontent.com/55925048/235199505-c1c0fb18-0a77-4417-8248-bf5109d58842.png)
![image](https://user-images.githubusercontent.com/55925048/235199570-2beded2e-e2b0-4eca-8413-24988b47554a.png)
![image](https://user-images.githubusercontent.com/55925048/235199642-c870a2e7-679f-4a79-90be-0e910737eba9.png)
![image](https://user-images.githubusercontent.com/55925048/235199813-7c2ce721-ad3f-4b04-8ad7-5357e5f0fb5f.png)

[code-block.zip](https://github.com/Templarian/MaterialDesign/files/11355402/code-block.zip)

**Comment by MrGrigri** [comment]
Perfect thanks

**Comment by mririgoyen** [comment]
Naming was chosen to fit our current patterns.

[![code-block-tags](https://pictogrammers.com/library/mdi/icon/code-block-tags)](https://pictogrammers.com/library/mdi/icon/code-block-tags)[![code-block-braces](https://pictogrammers.com/library/mdi/icon/code-block-braces)](https://pictogrammers.com/library/mdi/icon/code-block-braces)[![code-block-brackets](https://pictogrammers.com/library/mdi/icon/code-block-brackets)](https://pictogrammers.com/library/mdi/icon/code-block-brackets)[![code-block-parentheses](https://pictogrammers.com/library/mdi/icon/code-block-parentheses)](https://pictogrammers.com/library/mdi/icon/code-block-parentheses)
