### ISSUE TITLE
Alphabet and digits icons is needed!

### ISSUE THREAD

**Issue by ildaroit** [Templarian/MaterialDesign#709]
Alphabet and digits icons is needed!
It maybe very useful for services and sites which icons are not listed in you bundle!

**Comment by CoDEmanX** [comment]
Why not just use a web font?

**Comment by Templarian** [comment]
I'm not really sure I understand the issue exactly.

**Comment by Templarian** [comment]
Oh, this icon request was for a-z. The pack has 0-9. I have no plans to add a-z as icons. It would add a lot of extra weight to the icon set.
