### ISSUE TITLE
طبخات بيتوتي 

### ISSUE THREAD

**Issue by shabeeeb** [Templarian/MaterialDesign#7095]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

اريد ان يكون رمز لتطبيقي 

### Give us an example of what this icon might look like.

https://Shots.com

**Comment by Simran-B** [comment]
Please write your request in English so that we can understand it, and attach an image as a visual example.
I tried Google Translate but it says the headline means "Betoti cooking", which I can't make sense of.
