### ISSUE TITLE
earth-arrow-up / -down / -left

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#7096]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Give [earth-arrow-right](https://pictogrammers.com/library/mdi/icon/earth-arrow-right/) the family it deserves.

I personally only need "earth-arrow-up" (as an alternative for [publish](https://pictogrammers.com/library/mdi/icon/publish)), but I figured, while we’re at it…

![image](https://user-images.githubusercontent.com/55925048/236199415-555d633a-7fde-4414-8e97-4a96a356b3b0.png)
![image](https://user-images.githubusercontent.com/55925048/236199114-9e2922d7-8359-4edc-ab78-c6d4205f9e04.png)
![image](https://user-images.githubusercontent.com/55925048/236199336-ce71194c-c385-4bf0-8c06-0f3381420d77.png)

### Give us an example of what this icon might look like.

[earth-arrow.zip](https://github.com/Templarian/MaterialDesign/files/11397258/earth-arrow.zip)

**Comment by mririgoyen** [comment]
[![earth-arrow-down](https://pictogrammers.com/library/mdi/icon/earth-arrow-down)](https://pictogrammers.com/library/mdi/icon/earth-arrow-down)[![earth-arrow-left](https://pictogrammers.com/library/mdi/icon/earth-arrow-left)](https://pictogrammers.com/library/mdi/icon/earth-arrow-left)[![earth-arrow-up](https://pictogrammers.com/library/mdi/icon/earth-arrow-up)](https://pictogrammers.com/library/mdi/icon/earth-arrow-up)[![earth-arrow-right](https://pictogrammers.com/library/mdi/icon/earth-arrow-right)](https://pictogrammers.com/library/mdi/icon/earth-arrow-right)
