### ISSUE TITLE
ev battery icons

### ISSUE THREAD

**Issue by rchiileea** [Templarian/MaterialDesign#7099]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

slight rework of the battery icons for ev-charging due to android automotive developments

### Share a preview of your contribution.

![image](https://user-images.githubusercontent.com/87599807/236922985-27db83e4-3028-4565-aff6-be90308f8460.png)
![image](https://user-images.githubusercontent.com/87599807/236923013-efe458a5-5eb7-41ea-bb18-15fb427e582f.png)
![image](https://user-images.githubusercontent.com/87599807/236924637-d9feba28-00bc-46a0-a0e0-4da8f5e03171.png)
![image](https://user-images.githubusercontent.com/87599807/236923079-028d5e92-d47b-4b83-a2ca-ceafb727398d.png)
![image](https://user-images.githubusercontent.com/87599807/236923110-31342f97-7fea-4845-9ecc-46547a82e374.png)
![image](https://user-images.githubusercontent.com/87599807/236923184-305e4892-9330-4fa1-9d0f-82588ccea92d.png)
![image](https://user-images.githubusercontent.com/87599807/236923224-0e666283-f81e-402d-b723-79542e0f315b.png)
![image](https://user-images.githubusercontent.com/87599807/236923256-124f97d8-93f1-41dc-8d1e-97e44080f365.png)
![image](https://user-images.githubusercontent.com/87599807/236923315-2ca90d71-a06a-4c58-a61e-c32241374703.png)
![image](https://user-images.githubusercontent.com/87599807/236923341-8676ae7a-5245-44c4-9fde-87c9d6ed1f32.png)

### Upload the icon source.

[ev-charging-10.zip](https://github.com/Templarian/MaterialDesign/files/11424816/ev-charging-10.zip)

**Comment by MrGrigri** [comment]
Thanks for these contributions. However, there are some inconsistencies with the Guidelines. All thicknesses are 2dp, and most importantly, the points are on-grid. There are a few exceptions for 1dp thick strokes or gaps.

**Comment by mririgoyen** [comment]
In addition to the guideline issues brought up by @MrGrigri, I feel these are overly specific. We have a handful of generic battery icons that already solve these use cases. Being very niche, these are not something we're interested in adding to the library at this time. Thank you for you suggestion!
