### ISSUE TITLE
Checklist icon

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#710]
Something like

```
1
 2
  3
```

or something like [this](http://www.clker.com/cliparts/Z/K/t/v/5/o/check-list-hi.png) or [this](http://www.clker.com/cliparts/e/v/c/q/L/i/gray-checklist-md.png)

**Comment by CoDEmanX** [comment]
Quite a tough one,
![checklist](https://cloud.githubusercontent.com/assets/1309249/10209995/f0380e48-67e1-11e5-8d3e-2576d7805469.png) not enough space to make a variant of the existing list icons
![checklist2](https://cloud.githubusercontent.com/assets/1309249/10209996/f039fd52-67e1-11e5-8735-bb40f4599068.png) but two lines actually work.

Still, I prefer

[![clipboard-check](https://materialdesignicons.com/icon/clipboard-check)](https://materialdesignicons.com/icon/clipboard-check)

**Comment by Templarian** [comment]
I prefer the clipboard check also, but I like the 2nd one you posted @CoDEmanX. That could definitely work for a check list or something.

**Comment by derwaldgeist** [comment]
I wasn't aware of clipboard-check. That's not bad. The two-lines variant of the samples above IMHO won't work for larger sizes. Here, the first variant would be better. But I understand it's not easy to make this work for smaller sizes. What about the 1-2-3 icon idea? Could be useful for step-instructions as well (this is actually what I need it for).

**Comment by CoDEmanX** [comment]
@derwaldgeist: Wouldn't the existing icon work for that?

[![format-list-numbers](https://materialdesignicons.com/icon/format-list-numbers)](https://materialdesignicons.com/icon/format-list-numbers)

Otherwise, two experiments:
![1-2-3](https://cloud.githubusercontent.com/assets/1309249/11018308/1778a9e0-85c4-11e5-92e3-c5b951bbe5d1.png) ![1-2-3_rounded](https://cloud.githubusercontent.com/assets/1309249/11018309/17790c46-85c4-11e5-90b1-a4b67dba0ab5.png)

**Comment by derwaldgeist** [comment]
Yes, you're right, I could use format-list-numbers instead. But I think adding the second one of your "experiments" would be a good alternative!

**Comment by PeterShaggyNoble** [comment]
`format-list-checks` has since been added so closing this issue out.

[![format-list-checks](https://user-images.githubusercontent.com/15157491/33938580-e9c5fbae-dfff-11e7-8520-1154fd076aec.png)](https://materialdesignicons.com/icon/format-list-checks)

**Comment by CoDEmanX** [comment]
Is there any interest in the 1-2-3 experimental icons?

![1-2-3](https://cloud.githubusercontent.com/assets/1309249/11018308/1778a9e0-85c4-11e5-92e3-c5b951bbe5d1.png) ![1-2-3_rounded](https://cloud.githubusercontent.com/assets/1309249/11018309/17790c46-85c4-11e5-90b1-a4b67dba0ab5.png)

**Comment by derwaldgeist** [comment]
Sure!
