### ISSUE TITLE
Incorrect cross positioning on image-remove and image-remove-outline icons

### ISSUE THREAD

**Issue by ozgurg** [Templarian/MaterialDesign#7101]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

Hi.
The cross icon's positioning does not fit when [image-remove](https://pictogrammers.com/library/mdi/icon/image-remove/) and [image-remove-outline](https://pictogrammers.com/library/mdi/icon/image-remove-outline/) overlap.

https://github.com/Templarian/MaterialDesign/assets/6717356/9c5526f9-47ce-4cbf-82dd-9e4cda43a3b3

**Comment by mririgoyen** [comment]
Thanks, this will be fixed in v7.3.
