### ISSUE TITLE
Icons for the days of the week

### ISSUE THREAD

**Issue by moat335a** [Templarian/MaterialDesign#7103]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

My app and i belive it can be used in several other works of others.

### Give us an example of what this icon might look like.

icons for the days of the week from monday till sunday. it can be shaped as as a filled calendar with "Mo" "Tu" ..... curved out of it. 
example for monday: 
![computer-icons-calendar-date-clip-art-black-monday-6fee5a452cd599058b68c2caf5421e7a](https://github.com/Templarian/MaterialDesign/assets/67653067/9ccafa10-e1bd-4089-950a-ba727b4d9165)

Thank you.

**Comment by mririgoyen** [comment]
This is a language conflict, so we will not be adding them.
