### ISSUE TITLE
PWM icon

### ISSUE THREAD

**Issue by antonverburg** [Templarian/MaterialDesign#7104]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

For homeassistant I created the slow_pwm integration. For now there is no icon yet that describes such a function.

### Share a preview of your contribution.

![pwm](https://github.com/Templarian/MaterialDesign/assets/47820045/99a9f476-bc18-48f2-a16c-e542f1b4957c)

### Upload the icon source.

[pwm.zip](https://github.com/Templarian/MaterialDesign/files/11465369/pwm.zip)

**Comment by mririgoyen** [comment]
I'm honestly not sure what I'm even looking at here. This is obviously a very niche use case and it doesn't follow Material guidelines. It is also borderline "brand icon." Unfortunately, we're not going to be adding this at this time.

**Comment by antonverburg** [comment]
Is this more in-line with your guidelines? PWM icons are widely used (just try a google on 'pwm icon'), so I think it would add value to have it...
![image](https://github.com/Templarian/MaterialDesign/assets/47820045/9a180553-04e2-4a36-9395-039f5c9ce4d8)

**Comment by mririgoyen** [comment]
I'm not seeing these typically being on an axis'ed chart. We have `sqaure-wave` which seems like a good fit for this, no?

[![square-wave](https://pictogrammers.com/library/mdi/icon/square-wave)](https://pictogrammers.com/library/mdi/icon/square-wave)

**Comment by antonverburg** [comment]
Hm, comes close but does not really show the idea of PWM. Pulse width modulation generates an analog signal or semi-analog signal by influencing the width of pulses in a pulse train. For that reason I put two different pulse lengths in one train. Or do you mean that I should create a PWM icon based uppon the idea above?

**Comment by antonverburg** [comment]
Something like this? Or do you prefer straight corners?

![image](https://github.com/Templarian/MaterialDesign/assets/47820045/7e842091-52bd-438d-b004-6f831d3abd91)
