### ISSUE TITLE
PID thermostat

### ISSUE THREAD

**Issue by antonverburg** [Templarian/MaterialDesign#7106]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I wrote a PID thermostat integration for Homeassistant and this is an icon for it. It re-uses the HA generic thermostat icon, adding a PID-like regulation graph line.

### Share a preview of your contribution.

![afbeelding](https://github.com/Templarian/MaterialDesign/assets/47820045/42c875b3-b3e9-4ee3-aa57-f749fe766c4e)

### Upload the icon source.

[pid_thermostat.zip](https://github.com/Templarian/MaterialDesign/files/11465458/pid_thermostat.zip)

**Comment by mririgoyen** [comment]
This breaks all kinds of guidelines and is indistinguishable at native resolution. I don't feel this adds any value over the normal `thermostat` icon when used in context. Regardless, a chart-like modifier is not something we currently offer or wish to. Thanks for the suggestion, but we're going to pass on this.
