### ISSUE TITLE
ev-plug-ccs* icons do not match real proportions

### ISSUE THREAD

**Issue by johan12345** [Templarian/MaterialDesign#7107]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

When the `ev-plug-*` icons were updated as described in #6199, the lower part (the part that contains the DC pins) of the CCS connectors has been changed - now the proportions don't look quite right compared to the actual CCS connectors.

For example, in this picture of a CCS2 socket, you can see that the two DC pins are closer together horizontally than the two outermost pins of the top part:
<img src="https://github.com/Templarian/MaterialDesign/assets/5310424/df3e7b73-c0dd-42b9-a917-60aeecb72200" width="400px"/>
(source: https://commons.wikimedia.org/wiki/File:VW_eGolf_2014_(13058674474).jpg)

while they are a lot further apart and less tall in the MDI icon:
<img src="https://raw.githubusercontent.com/Templarian/MaterialDesign/e607d030c555e05f8ee911538e2761c0d0e8cf26/svg/ev-plug-ccs2.svg" width="400px"/>

Another issue with the CCS2 plug is that while the socket on the car always has all 9 pins, the plugs on charging stations usually omit some pins which are not needed for DC fast charging: 
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/2015-12-23_CCS-Stecker_50_kW.jpg/539px-2015-12-23_CCS-Stecker_50_kW.jpg" width="400px"/>
you might also want to reflect this in the plug icon.

For the CCS1 plug, you could look e.g. at [this picture](https://de.wikipedia.org/wiki/Combined_Charging_System#/media/Datei:2015-12-23_CCS-Stecker_50_kW.jpg) for reference - the proportions of the MDI icon for this one are better, but still not quite correct.

I have a collection of plug icons in the [EVMap](https://github.com/ev-map/EVMap/tree/master/_img/connectors) project, feel free to use those as inspiration.

**Comment by mririgoyen** [comment]
Icons are not 1:1 depictions of real things. We're happy with how these (rather complex) icons are as-is. They're actually not dissimilar to the versions Google uses in Google Maps. We're not going to make any changes or updates to these at this time. Thanks for the effort put in to this post.
