### ISSUE TITLE
rental or Rent of any item

### ISSUE THREAD

**Issue by vinoth-pd** [Templarian/MaterialDesign#7109]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In web apps

### Give us an example of what this icon might look like.

[![image](https://github.com/Templarian/MaterialDesign/assets/74234451/747de4f3-aa11-4df9-b931-763f15c873ac)](https://www.shutterstock.com/image-vector/house-rent-icon-on-white-260nw-1607047972.jpg)

**Comment by MrGrigri** [comment]
We cannot include the word "RENT" as we are a multi-lingual icon pack. There are a few exceptions that revolve around standards, but we'll have to find a way to represent this without words or specific currencies (e.g. dollar sign)
