### ISSUE TITLE
gate_50

### ISSUE THREAD

**Issue by CiniBN** [Templarian/MaterialDesign#7111]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In the case of a gate, there is a condition where only one side of the double-sided gate is open.

### Give us an example of what this icon might look like.

![gate_50](https://github.com/Templarian/MaterialDesign/assets/48511852/9f14a7ea-16c1-4131-a9cc-e394fa84e758)

**Comment by mririgoyen** [comment]
This doesn't work within the space available to us. It's virtually indistinguishable at native resolution with `gate-open`. Thanks for the suggestion, but we're going to pass on this one.
