### ISSUE TITLE
License Plate icon

### ISSUE THREAD

**Issue by smileapplications** [Templarian/MaterialDesign#712]
License Plate icon

**Comment by GreenTurtwig** [comment]
This could be really difficult to do. Countries have different shapes, some are a lot wider, mostly Europe,  than they are in the US, Australia, Japan, e.t.c. This would cause issues with the limited amount of space available for icons.

**Comment by percula** [comment]
I needed this icon for a project I'm working on and created one. This is the best I could do, as @GreenTurtwig mentioned, there are quite a few considerations to account for so I figured simple is best. This is my first contribution, so if the svg is poorly formatted please let me know. I created it with Inkscape.

[license_plate_outline_simplified.svg.zip](https://github.com/Templarian/MaterialDesign/files/1946962/license_plate_outline_simplified.svg.zip)

**Comment by percula** [comment]
I also made a slightly different solid version. The solid version allows for more room to put a dot in the middle of the numbers, typical of many license plates.

[license_plate_solid_simplified.svg.zip](https://github.com/Templarian/MaterialDesign/files/1946999/license_plate_solid_simplified.svg.zip)

**Comment by PeterShaggyNoble** [comment]
Previews:

![license-plate-outline](https://user-images.githubusercontent.com/15157491/39249768-4dac4dee-4897-11e8-93d1-7dd74ad76eee.png) ![license-plate](https://user-images.githubusercontent.com/15157491/39249952-bfef2f02-4897-11e8-8f32-221bfc1b6185.png)

**Comment by CoDEmanX** [comment]
@PeterShaggyNoble Maybe increase the (inner) size by 1px and move the outer part in the outline version 0.5px into the margin? The border looks kinda thick.

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX, I think you meant to tag @percula there.

**Comment by CoDEmanX** [comment]
Indeed, but my idea doesn't really work out:

![grafik](https://user-images.githubusercontent.com/1309249/39385555-389526e8-4a71-11e8-8186-0c0a7b9f65f8.png)

This is meh too, despite being sharper:

![grafik](https://user-images.githubusercontent.com/1309249/39386583-a33788ca-4a75-11e8-8280-d5265859e362.png)

The filled one by percula is not legible on a normal density screen:

![grafik](https://user-images.githubusercontent.com/1309249/39386644-e5751f54-4a75-11e8-8c3e-a04f716216bf.png)

**Comment by CoDEmanX** [comment]
Tried to tweak it a little, but still not great:

![grafik](https://user-images.githubusercontent.com/1309249/39386980-5e17596c-4a77-11e8-8404-853d73fa16d5.png)

![grafik](https://user-images.githubusercontent.com/1309249/39386961-432b97a8-4a77-11e8-8349-3542ee78bcc9.png)

**Comment by percula** [comment]
I like the sharper font you used, much more legible on a small icon.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.

**Comment by goyney** [comment]
Because this was just requested again recently, I'd like to add some comments for anyone who comes across this again in the future.

We are not going to be adding this as an icon. We have already taken the stance that we will not add arbitrary letter-based icons anymore (such as rejected request to add an "IP" icon), which means we aren't going to add one with random letters/numbers. Additionally, from the examples above, it is not possible to create something meaningful and identifiable within the confines of Material's guidelines.
