### ISSUE TITLE
Needs to have an F-Droid icon.

### ISSUE THREAD

**Issue by LegacyHardware** [Templarian/MaterialDesign#713]
Can't believe I hasn't been asked for before.

**Comment by CoDEmanX** [comment]
I would consider that a brand icon, which has also a lot of fine details. Doesn't fit in the pack IMO.

**Comment by Templarian** [comment]
Yea, looks like a brand. We're currently in the process of retroactively only allowing social media related services into the pack.

Sorry about that.

**Comment by LegacyHardware** [comment]
Sorry to bother you guys again. What do you mean by "brand icon". It's a FOSS app repo. Also, the icon looks pretty simple to me.
![screenshot_2015-10-02-06-41-10](https://cloud.githubusercontent.com/assets/10489449/10245016/acecb8e6-68d1-11e5-8a3a-ed4306abd69a.png)

**Comment by connyduck** [comment]
Can this decision please be reconsidered? There are icons for Google Play and Amazon as well and I would really like to have an F-Droid icon alongside them. https://tuskyapp.github.io/

**Comment by PeterShaggyNoble** [comment]
@connyduck, the icon on the site you linked to already exists as `android`.

**Comment by connyduck** [comment]
lol yes of course, I used it because there is no fdroid icon in this icon set 🙄

**Comment by goyney** [comment]
This is F-Droid: https://f-droid.org/en/

I believe this is too niche to add to the library.

**Comment by JapanYoshi** [comment]
F-Droid is actually one of the biggest non-corporate repositories of Android apps. I don't think it's "too niche" by any means!
