### ISSUE TITLE
Icons are not showing origional icons

### ISSUE THREAD

**Issue by asiflhr** [Templarian/MaterialDesign#7139]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

I'm using this icons with wix/react-native-navigation, react-native-paper. But Icons are not showing origional icons,

![Screenshot 2023-06-19 153824](https://github.com/Templarian/MaterialDesign/assets/26629776/1417db16-1e40-4dc0-adac-13abdc59cf0b)
I'm using this close Icon.

![Screenshot 2023-06-19 153800](https://github.com/Templarian/MaterialDesign/assets/26629776/0296045f-7d6d-4738-9f83-f17d09f1d7dc)
But getting this Buffalo Icon.

**Comment by mririgoyen** [comment]
How are you using this library? Because we sure don't have a buffalo icon. Additionaly, we're not affiliated with wix/react-native-navigation or react-native-paper. Please provide us with a full example of how you're using one of the `@mdi` libraries, and we can look into this.
