### ISSUE TITLE
Pocket

### ISSUE THREAD

**Issue by omsrivastava** [Templarian/MaterialDesign#7144]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

It's a pocket icon 

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/46325414/106e383f-b77c-4a41-8d9f-f210bf41434c)

### Upload the icon source.

<svg width="14" height="16" viewBox="0 0 14 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<path d="M0 0V13.3084L7 16L14 13.3084V0H0ZM1.55556 1.59502H12.4444V3.19003H1.55556V1.59502ZM1.55556 4.78505H12.4444V12.2118L7 14.3053L1.55556 12.2118V4.78505ZM7 6.38006C5.28342 6.38006 3.88889 7.81308 3.88889 9.57009C3.88889 11.3271 5.28342 12.7601 7 12.7601C8.71658 12.7601 10.1111 11.3271 10.1111 9.57009C10.1111 7.81308 8.71354 6.38006 7 6.38006ZM7.12153 7.67601C7.99349 7.67601 8.69531 8.20249 8.72569 8.2243L8.26389 8.87227C8.25781 8.86916 7.7322 8.47352 7.12153 8.47352C6.74783 8.47352 6.10069 8.58255 6.10069 8.97196C6.23741 9.13396 6.79036 9.1433 7.02431 9.14642H7.12153C8.13629 9.14642 8.79861 9.52648 8.79861 10.1682C8.79861 10.7632 8.34288 11.4642 7.07292 11.4642C6.11589 11.4642 5.30773 10.9377 5.27431 10.9159L5.71181 10.2679C5.71788 10.2741 6.34983 10.6667 7.07292 10.6667C7.50738 10.6667 8.02083 10.5327 8.02083 10.1682C8.02083 10.0654 7.63194 9.94392 7.12153 9.94392H7.02431C6.55035 9.94081 5.92448 9.91277 5.56597 9.54517C5.41102 9.38941 5.32292 9.20249 5.32292 8.97196C5.32292 8.18692 6.03689 7.67601 7.12153 7.67601Z" fill="#424242"/>
</svg>

**Comment by Templarian** [comment]
@omsrivastava What is the "s" for? It might be a goo idea for a pants pocket to have a stitch so it isn't confused with a badge or banner. Dotted line or something to make it look more like a pocket.

**Comment by Templarian** [comment]
[![pocket](https://pictogrammers.com/library/mdi/icon/pocket/)](https://pictogrammers.com/library/mdi/icon/pocket/)
