### ISSUE TITLE
Add a couple more of wave-arrow icons for underwater direction

### ISSUE THREAD

**Issue by patrickelectric** [Templarian/MaterialDesign#7145]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

This icon is useful to indicate submarine direction or depth underwater 

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/1215497/f02f31dc-b5f8-420e-8271-82ba9b3109f8)
![image](https://github.com/Templarian/MaterialDesign/assets/1215497/20575639-703c-4991-8127-f766d8477dea)

### Upload the icon source.

[wave-arrow.zip](https://github.com/Templarian/MaterialDesign/files/11848785/wave-arrow.zip)

**Comment by Templarian** [comment]
[![wave-arrow-up](https://pictogrammers.com/library/mdi/icon/wave-arrow-up/)](https://pictogrammers.com/library/mdi/icon/wave-arrow-up/) [![wave-arrow-down](https://pictogrammers.com/library/mdi/icon/wave-arrow-down/)](https://pictogrammers.com/library/mdi/icon/wave-arrow-down/)

With minor tweaks added.
