### ISSUE TITLE
Icon for Recent Items

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#715]
I am looking for a good icon symbolizing "recent items", i.e. items that have been recently added to a collection of items. I have to admin that I don't have a clear idea how this icons should loook like. I thought about something like a clock with a circled arrow arround it, but I'm sure you have much better ideas.

**Comment by derwaldgeist** [comment]
Just saw there's already 'history'.

**Comment by Sjennon** [comment]
Ran into the same question. Maybe add the tag: _recent_ or _latest_ to it to improve findability.

**Comment by Templarian** [comment]
@Sjennon added aliases for `recent`/`latest`
