### ISSUE TITLE
emoticon-plus

### ISSUE THREAD

**Issue by vegarda** [Templarian/MaterialDesign#7155]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

open a panel with many emojis to select

### Give us an example of what this icon might look like.

https://fonts.google.com/icons?selected=Material+Symbols+Outlined:add_reaction:FILL@1;wght@400;GRAD@0;opsz@48&icon.query=add+reaction&icon.style=Outlined

**Comment by bakotamas** [comment]
Hello!
I created a filled and an outlined version, maybe a better idea to place the plus sign at the bottom right.
![image](https://github.com/Templarian/MaterialDesign/assets/83959759/aeb14600-ee7b-42d3-8d48-7dc75b51c9bf)
[emoticon-plus.zip](https://github.com/Templarian/MaterialDesign/files/12000789/emoticon-plus.zip)
![image](https://github.com/Templarian/MaterialDesign/assets/83959759/6cdac3d9-a4f2-49b4-a426-ad569d9ecb4e)
[emoticon-plus-outline.zip](https://github.com/Templarian/MaterialDesign/files/12000790/emoticon-plus-outline.zip)

**Comment by Templarian** [comment]
[![emoticon-plus](https://pictogrammers.com/library/mdi/icon/emoticon-plus/)](https://pictogrammers.com/library/mdi/icon/emoticon-plus/) [![emoticon-plus-outline](https://pictogrammers.com/library/mdi/icon/emoticon-plus-outline/)](https://pictogrammers.com/library/mdi/icon/emoticon-plus-outline/)

**Comment by Templarian** [comment]
[![emoticon-minus](https://pictogrammers.com/library/mdi/icon/emoticon-minus/)](https://pictogrammers.com/library/mdi/icon/emoticon-minus/) [![emoticon-minus-outline](https://pictogrammers.com/library/mdi/icon/emoticon-minus-outline/)](https://pictogrammers.com/library/mdi/icon/emoticon-minus-outline/)
[![emoticon-remove](https://pictogrammers.com/library/mdi/icon/emoticon-remove/)](https://pictogrammers.com/library/mdi/icon/emoticon-remove/) [![emoticon-remove-outline](https://pictogrammers.com/library/mdi/icon/emoticon-remove-outline/)](https://pictogrammers.com/library/mdi/icon/emoticon-remove-outline/)
