### ISSUE TITLE
USB-C Port

### ISSUE THREAD

**Issue by avdvlpr** [Templarian/MaterialDesign#7158]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

AV system control panels

### Give us an example of what this icon might look like.

![image](https://github.com/Templarian/MaterialDesign/assets/139325705/a8e609b2-0a08-4fc4-b71c-4f1df18d012c)

**Comment by Templarian** [comment]
[![usb-c-port](https://pictogrammers.com/library/mdi/icon/usb-c-port/)](https://pictogrammers.com/library/mdi/icon/usb-c-port/)
