### ISSUE TITLE
Add Nest-Display icone

### ISSUE THREAD

**Issue by sirmeili** [Templarian/MaterialDesign#7159]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would use this to identify my nest displays, specifically in Home Assisatnt

### Give us an example of what this icon might look like.

The icon can be found in Google's MDI icon font found here: https://fonts.google.com/icons?selected=Material+Symbols+Outlined:nest_display:FILL@0;wght@400;GRAD@0;opsz@48&icon.style=Outlined&icon.query=nest+display

**Comment by mririgoyen** [comment]
We don't add icons for specific devices anymore and have recently removed all device-specific icons. We won't be adding this, even though Google provides it in their library.
