### ISSUE TITLE
radar-dish

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#716]
Something like [this](https://cdn0.iconfinder.com/data/icons/the-wars/450/radar-128.png) or [this](http://simpleicon.com/wp-content/uploads/radar.png). Would be handy for location-based services, if you want to symbolize scanning the neighborhood.

**Comment by CoDEmanX** [comment]
Google has an icon that somewhat looks like a radar (I believe on purpose):
https://www.google.com/design/icons/#ic_track_changes

**Comment by derwaldgeist** [comment]
Thanks for this info. But I don't think that radar would fit my needs. It's just not very clear that this should be a radar.

**Comment by CoDEmanX** [comment]
I guess it could be slightly tweaked to make a bit more recognizable, but there's not much room for more details without transparency and obeying the MD rules.

**Comment by Templarian** [comment]
[![radar](https://materialdesignicons.com/icon/radar)](https://materialdesignicons.com/icon/radar)

**Comment by derwaldgeist** [comment]
Thanks!
