### ISSUE TITLE
Account with shield modifier

### ISSUE THREAD

**Issue by dpeter99** [Templarian/MaterialDesign#7162]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The account base icon with the shield and shield half as a modifier in the corner.
The use could be for account security settings or to symbolize a person who protects (like moderators in a community)

### Give us an example of what this icon might look like.

Just the shield as a modifer

**Comment by MrGrigri** [comment]
Why doesn't [`shield-account`](https://pictogrammers.com/library/mdi/icon/shield-account/) work? 

[![shield-account](https://github.com/Templarian/MaterialDesign/assets/4528551/a37951bc-0de7-47aa-914c-d8dc1c155d42)](https://pictogrammers.com/library/mdi/icon/shield-account/)

**Comment by dpeter99** [comment]
Yes, that could work. Thanks for the suggestion. I was too focused on what I had in mind.
