### ISSUE TITLE
account-file and account-document-file

### ISSUE THREAD

**Issue by andrejsharapov** [Templarian/MaterialDesign#7166]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

To develop crm, you need to add contract curators and payment curators. For curator-payment I use [account-credit-card](https://pictogrammers.com/library/mdi/icon/account-credit-card/), but for the contract, the icon [file-account](https://pictogrammers.com/library/mdi/icon/file-account/) is not suitable (style is different).

There is a nuance here:
1. icon `file-account` already exists
2. which is that the `account-credit-card` and my icons violate the MDI style (2dp).

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/44722574/8cde9ca8-afc8-4333-b932-079075e2f902) ![image](https://github.com/Templarian/MaterialDesign/assets/44722574/eda4d167-a112-4b6d-a2db-284eef3ab509)

![image](https://github.com/Templarian/MaterialDesign/assets/44722574/ff49b439-2ce0-447a-bdf4-f09d1d65e3d3) ![image](https://github.com/Templarian/MaterialDesign/assets/44722574/22b6aead-0a92-4951-860d-6adb518c59f5)

### Upload the icon source.

[account-file.zip](https://github.com/Templarian/MaterialDesign/files/12081178/account-file.zip)

**Comment by Templarian** [comment]
Added (with some modifications).

[![account-file](https://pictogrammers.com/library/mdi/icon/account-file/)](https://pictogrammers.com/library/mdi/icon/account-file/) [![account-file-outline](https://pictogrammers.com/library/mdi/icon/account-file-outline/)](https://pictogrammers.com/library/mdi/icon/account-file-outline/)
[![account-file-text](https://pictogrammers.com/library/mdi/icon/account-file-text/)](https://pictogrammers.com/library/mdi/icon/account-file-text/) [![account-file-text-outline](https://pictogrammers.com/library/mdi/icon/account-file-text-outline/)](https://pictogrammers.com/library/mdi/icon/account-file-text-outline/)
