### ISSUE TITLE
Combined icon for Barcode and QR code

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#717]
Many scan applications allow to scan for both Bardcodes and QR codes. For these scenarios, it would be handy to have a combined icon for both. For instance, the upper left triangle of the icon is a QR code, whereas the lower right triangle is a barcode.

**Comment by JamesCoyle** [comment]
Some inspiration:

![image](https://user-images.githubusercontent.com/10384436/45600332-f47f2e80-b9f2-11e8-8b92-575c097721bd.png)
![image](https://user-images.githubusercontent.com/10384436/45600339-0c56b280-b9f3-11e8-8e3d-e9283a4964ca.png)

**Comment by MrGrigri** [comment]
Closing this as there is no further demand.
