### ISSUE TITLE
Wrong encoding after project build

### ISSUE THREAD

**Issue by PLG-LeiN** [Templarian/MaterialDesign#7170]
### What is your question?

I use Vite in my project. I have installed @mdi via npm and I use its icons. The problem is that after building the project, the artifacts in index.css contain broken encoding for the mdi codepoint. For example, in the materialdesignicons.css source file, the content is as follows:
`
.mdi-ab-testing::before {
  content: "\F01C9";
}
`

In the built version, it looks like this:
`
.mdi-ab-testing:before{content:"󰇉"}
`

I couldn't find any solutions in the Vite community or similar issues. Has anyone encountered a similar problem? Thank you in advance.

**Comment by Templarian** [comment]
@PLG-LeiN Were you able to find a solution for this? I think this might be outside of our team to answer (not sure we have anyone in the core team that uses Vite).

**Comment by Templarian** [comment]
@PLG-LeiN As we have not seen a reply I'm going to close this out. Hoping you were able to find a solution.
