### ISSUE TITLE
passport-plus

### ISSUE THREAD

**Issue by marriott5299** [Templarian/MaterialDesign#7173]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To indicate additional travel documents in an Aviation system

### Give us an example of what this icon might look like.

![passport-plus](https://github.com/Templarian/MaterialDesign/assets/71550197/ed3cfa97-fd79-48bc-bfee-92c99565cbd8)

**Comment by MrGrigri** [comment]
![passport-alert](https://github.com/Templarian/MaterialDesign/assets/4528551/855303fa-0221-4d81-a88d-e6a95ae1b6d9) ![passport-cancel](https://github.com/Templarian/MaterialDesign/assets/4528551/2e4b7a14-e84c-4ecf-ad75-088d4e275aff) ![passport-check](https://github.com/Templarian/MaterialDesign/assets/4528551/90d13145-69ba-4617-9636-01c585252119)  ![passport-minus](https://github.com/Templarian/MaterialDesign/assets/4528551/5ef45e96-1539-481e-a36a-6b486d71443f) ![passport-plus](https://github.com/Templarian/MaterialDesign/assets/4528551/34c96a36-09a9-4428-9301-3f3b16d80b4f) ![passport-remove](https://github.com/Templarian/MaterialDesign/assets/4528551/953cf57e-5248-4a6e-b51f-4add479f9154)   

---

![passport-alert](https://github.com/Templarian/MaterialDesign/assets/4528551/15b51ecb-3a44-4370-ba18-8d8a97666920) ![passport-cancel](https://github.com/Templarian/MaterialDesign/assets/4528551/03539007-b617-4f7a-8d39-79c4af00452c) ![passport-check](https://github.com/Templarian/MaterialDesign/assets/4528551/9ec61efb-f53c-4ba1-b171-e4d716020331) ![passport-minus](https://github.com/Templarian/MaterialDesign/assets/4528551/f8c1682f-7099-4a6d-a3fe-054f8c8c4942) ![passport-plus](https://github.com/Templarian/MaterialDesign/assets/4528551/5f617a18-3c50-4ea4-9308-e1775beabb50) ![passport-remove](https://github.com/Templarian/MaterialDesign/assets/4528551/9222ccab-dace-448c-b2c9-b8b5aeb20692)

**Comment by Templarian** [comment]
@MrGrigri Feel free to add all of these once you have time. 👍

**Comment by MrGrigri** [comment]
[![passport-alert](https://pictogrammers.com/library/mdi/icon/passport-alert)](https://pictogrammers.com/library/mdi/icon/passport-alert) [![passport-cancel](https://pictogrammers.com/library/mdi/icon/passport-cancel)](https://pictogrammers.com/library/mdi/icon/passport-cancel) [![passport-check](https://pictogrammers.com/library/mdi/icon/passport-check)](https://pictogrammers.com/library/mdi/icon/passport-check) [![passport-minus](https://pictogrammers.com/library/mdi/icon/passport-minus)](https://pictogrammers.com/library/mdi/icon/passport-minus) [![passport-plus](https://pictogrammers.com/library/mdi/icon/passport-plus)](https://pictogrammers.com/library/mdi/icon/passport-plus)

---

`passport-remove` was also generated but I forgot to copy the image.
