### ISSUE TITLE
Fire Station

### ISSUE THREAD

**Issue by NeuzNL** [Templarian/MaterialDesign#7175]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To put on a google map to show the location

### Give us an example of what this icon might look like.

Like the police station icon but with a fire indicator at the roof

**Comment by MrGrigri** [comment]
![fire-station](https://github.com/Templarian/MaterialDesign/assets/4528551/b2f7986f-efee-4ea9-b5ab-8ebd3d537b06)

---

![fire-station](https://github.com/Templarian/MaterialDesign/assets/4528551/338ccbf8-cbe4-4fca-8517-99c0eaf44d23)

**Comment by NeuzNL** [comment]
That's a fast response. Looking great. Is it useable yet?

**Comment by MrGrigri** [comment]
Sadly, that process take a bit longer. I'm glad you like it. Once this issue is marked with a milestone, then it'll be added to the next release.

**Comment by NeuzNL** [comment]
Great to hear. Thanks again for the fast respons

**Comment by MrGrigri** [comment]
[![fire-station](https://pictogrammers.com/library/mdi/icon/fire-station)](https://pictogrammers.com/library/mdi/icon/fire-station)
