### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by mschutti** [Templarian/MaterialDesign#7177]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Icon to symbolize a job queue or task queue. I know there's an icon for a human queue but quite often you can't refer to humans waiting because you have to deal with a technical context. Given icons for trays or a stack can't be used either because they do not convey the first-in first-out character of a queue. I hope you like the proposal attached.  

### Share a preview of your contribution.

<img width="334" alt="Screenshot 2023-07-27 at 16 20 26" src="https://github.com/Templarian/MaterialDesign/assets/140617438/8e141b67-ca5a-4751-a198-9ecc7b340417">

### Upload the icon source.

![Queue](https://github.com/Templarian/MaterialDesign/assets/140617438/f7ac4aa7-70f8-4899-bc1b-0cec78335c7b)

**Comment by MrGrigri** [comment]
I feel like those arrows are too squished and unrecognizable at 1x.

**Comment by mschutti** [comment]
<img width="336" alt="Screenshot 2023-07-28 at 09 36 11" src="https://github.com/Templarian/MaterialDesign/a
<img width="329" alt="Screenshot 2023-07-28 at 09 40 11" src="https://github.com/Templarian/MaterialDesign/assets
<img width="332" alt="Screenshot 2023-07-28 at 09 36 25" src="https://github.com/Templarian/MaterialDesign/assets/140617438/de3dad73-f02e-4801-9753-803da34e4576">
/140617438/bdf483bf-cd77-4bb6-ad58-821cc5850faf">
ssets/140617438/8ac6d945-75cf-4052-9988-8a68087e2daa">
Agree, please find improved proposal attached

**Comment by mschutti** [comment]
<img width="329" alt="Screenshot 2023-07-28 at 09 40 11" src="https://github.com/Templarian/MaterialDesign/assets/140617438/c039b7e8-2bb4-4b53-ba1f-73f3b1ad02f4">

**Comment by MrGrigri** [comment]
@mschutti I believe the `Queue-4` is by far the best!

**Comment by MrGrigri** [comment]
Make sure to add the actual SVG for that one.

**Comment by mschutti** [comment]
![Queue-4](https://github.com/Templarian/MaterialDesign/assets/140617438/6a4746bf-a3d6-4ebd-bdec-6fcc93d96ecb)
I'm glad you like proposal number 4; please find attached the SVG format. 
I'm so sorry for delay in my response; I'm just back from vacation.

**Comment by mschutti** [comment]
[Queue-4.zip](https://github.com/Templarian/MaterialDesign/files/12273595/Queue-4.zip)

**Comment by Templarian** [comment]
[![queue-first-in-last-out](https://pictogrammers.com/library/mdi/icon/queue-first-in-last-out/)](https://pictogrammers.com/library/mdi/icon/queue-first-in-last-out/)

**Comment by mschutti** [comment]
Hi, Could you please help me understand what's the current status of this request? I hope it's not rejected (because it has been moved to Closed). Please let me know if anything is missing on my end, thanks!

**Comment by MrGrigri** [comment]
Good catch. This is slated for our next release of 7.3.0. We wait until we have 100 icons queued up, then we creat a release.
