### ISSUE TITLE
Color and alpha for VectorDrawable are not set when using Advanced Export

### ISSUE THREAD

**Issue by bogdanzurac** [Templarian/MaterialDesign#718]
Hey there.

As far as I can tell, if you try to use the Advanced Export feature for an icon, then try to export as a VectorDrawable XML, the color and alpha settings are not exported. Instead, the default #000 fillColor is present and the alpha is not set at all.

**Comment by Templarian** [comment]
Yep, the text in the bottom right corner explains that on the modal. Advanced Export is still a relatively recent feature addition to the site. All vector previews / downloads will eventually reflect the various inputs.

I'll use this issue to track the progress.

**Comment by bogdanzurac** [comment]
You mean this text ("Only single icon downloads for 'Advanced Export' are supported at this time.")? If so, yes, I've read it, but it doesn't really explain why colors and alphas don't work. At least I, for one, can't deduce that from the text. Hence I've reported the issue.

Any ETA on the subject? At least a general one, ex. days, weeks, months?
