### ISSUE TITLE
garage-open-variant-50%

### ISSUE THREAD

**Issue by wanfr** [Templarian/MaterialDesign#7180]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

partial door opening

### Share a preview of your contribution.

![Sans titre](https://github.com/Templarian/MaterialDesign/assets/62714660/c99cd455-3271-44d3-bf98-fbbe5942dd15)

### Upload the icon source.

[garage-variant-50%.svg.zip](https://github.com/Templarian/MaterialDesign/files/12195052/garage-variant-50.svg.zip)

**Comment by mririgoyen** [comment]
This won't be added for the same reasoning as given on the window shutters. See https://github.com/Templarian/MaterialDesign/issues/5733 for more context.
