### ISSUE TITLE
gas-pump in use

### ISSUE THREAD

**Issue by dannytsang** [Templarian/MaterialDesign#7184]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would like a gas pump icon to show when it's in use. In this case when it's being used to fill up something like a car, a boat, motorcycle, etc. I don't want to show the object it's filling so it's agnostic to what it's filling up.

The existing set of icons are sufficient to show a fuel fill up is there or not available (mdiGasStationOff) and I would like the new icon to convey the action of being used.

### Give us an example of what this icon might look like.

Maybe where the hose is turned and tipped 45 degrees outwards with a droplet.

**Comment by MrGrigri** [comment]
Thanks for this request. Your suggestion of how to create this icon will not work as there isn't enough space. Have you considered representing a stall that is in-use as a disabled state of the same icon?

**Comment by dannytsang** [comment]
Thanks for coming back to me.

What do you mean by a stall?

**Comment by MrGrigri** [comment]
Sorry, I assumed that this icon would represent a gas stall. I'm using stall as a word to describe the location the vehicle parks and uses a pump at that stall or location.  Usually, in the United States each pump is numbered so I guess you could use the word pump, but pump also refers to the actual gas pump. So I elected to use the word stall. 

Either way, the icons are only 24 x 24 pixels so there isn't much room. The pump already takes up most of the free space.

![gas-pump](https://github.com/Templarian/MaterialDesign/assets/4528551/242f9399-02a7-4df0-9682-c6043c0f50d3)

**Comment by MrGrigri** [comment]
I don't know if I like the name...but is this what you were asking for? It does shift the pump to the left 2 pixels, so if someone were to toggle between the two icons it would look weird. 

![gas-pump-in-use](https://github.com/Templarian/MaterialDesign/assets/4528551/d56807db-3f9a-466e-bf01-4c3ab247f1db) ![gas-pump-in-use-outline](https://github.com/Templarian/MaterialDesign/assets/4528551/fe7af604-9b1a-47cd-91ad-551dceacc5b9)

![difference](https://github.com/Templarian/MaterialDesign/assets/4528551/3a5da546-b973-4aa6-8940-986d43f897c0)

---

![gas-pump-in-use](https://github.com/Templarian/MaterialDesign/assets/4528551/036bf551-69af-4dba-b86f-be597f7e81a2) ![gas-pump-in-use-outline](https://github.com/Templarian/MaterialDesign/assets/4528551/c858d90a-525c-4e66-89b4-72063655e516)

**Comment by dannytsang** [comment]
Great illustration of the pixel shift. Would slimming the main ?body? on all icons make it work? Maybe outside the scope of this request.

Personally, I would use your new icon if it was published.

**Comment by MrGrigri** [comment]
Shifting the existing pumps is not a solution we are willing to make. The SVGs are there if you need them for the mean time.

**Comment by MrGrigri** [comment]
[![gas-station-in-use](https://pictogrammers.com/library/mdi/icon/gas-station-in-use)](https://pictogrammers.com/library/mdi/icon/gas-station-in-use) [![gas-station-in-use-outline](https://pictogrammers.com/library/mdi/icon/gas-station-in-use-outline)](https://pictogrammers.com/library/mdi/icon/gas-station-in-use-outline)
