### ISSUE TITLE
marcello

### ISSUE THREAD

**Issue by marcello852** [Templarian/MaterialDesign#7186]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

estudo

### Give us an example of what this icon might look like.

tudo

**Comment by MrGrigri** [comment]
I'm sorry, but I believe you have filled this request our incorrectly. The title is supposed to be the icon that you are requesting and not your name. We are also an English-first repo. Please fill it out in English.

Eu sinto muito, mas eu creio que você encheu esse requerido errado. O título tem que ser o icon que você quer requerer e não o seu nome. Esse repositório somente está em inglês. Por favor preencha em inglês.
