### ISSUE TITLE
currency conversion

### ISSUE THREAD

**Issue by AmirahAdnan** [Templarian/MaterialDesign#7187]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Mobile Application

### Give us an example of what this icon might look like.

https://as2.ftcdn.net/v2/jpg/02/45/92/65/1000_F_245926559_Q7r3Eer64zFePz5GANKTWoVipkLiiWoz.jpg

**Comment by MrGrigri** [comment]
We do have `cash-sync` that could work. 

![cash-sync](https://github.com/Templarian/MaterialDesign/assets/4528551/c3617d69-c58e-4a8f-adb2-cbcdd5c56643)

But if not, we could add `currency-usd-rotate` or `currency-usd-sync`. I believe `currency-usd-rotate` would work best and be more recognizable at 1x. But the `rotate` modifier wouldn't work on all of the currency types.

![currency-usd-rotate](https://github.com/Templarian/MaterialDesign/assets/4528551/7a72bb79-8e74-4658-bd07-2d0e4832254a) ![currency-usd-sync](https://github.com/Templarian/MaterialDesign/assets/4528551/d787f77e-68fb-4a41-b070-b5af85dabcc9)

---

![currency-usd-rotate](https://github.com/Templarian/MaterialDesign/assets/4528551/ed91580e-e251-4905-ab8a-6d323c4279ea) ![currency-usd-sync](https://github.com/Templarian/MaterialDesign/assets/4528551/93504acd-500d-4b8f-8d99-7d3b1417478c)

**Comment by mririgoyen** [comment]
Any options would have to exclude the USD symbol. We don't add icons with country-specific currency markers.

I believe `cash-sync` is going to be the best bet for this use case. However, we'll leave this issue open a little longer to brainstorm other ideas.

**Comment by MrGrigri** [comment]
Like I said, the `sync` modifier could be used on other currencies and would work...but it can cut off quite a bit. Again, I agree with you @mririgoyen, the `cash-sync` would probably be best.

**Comment by mririgoyen** [comment]
Yeah, we currently have 26 individual currency icons. We're not going to add the `sync` modifier to them all. 😄

**Comment by Templarian** [comment]
@AmirahAdnan I agree with the others `cash-sync` is probably going to be the best option here. Would this work for your use case or do you have any other ideas?

**Comment by Templarian** [comment]
Closing this one out. Please reply if you think this should be re-opened.
