### ISSUE TITLE
add pixiv outline icon

### ISSUE THREAD

**Issue by nodegin** [Templarian/MaterialDesign#719]
like this one (but only the white area), thanks a lot

![pixiv_icon_by_medmael-d8rhj7r](https://cloud.githubusercontent.com/assets/8536244/10219771/5cf6e5bc-6874-11e5-93f7-86600fbd0103.png)

**Comment by CoDEmanX** [comment]
Does it have a strong affinity to social media?

**Comment by pntrivedy** [comment]
:)

![pixiv-filled](https://cloud.githubusercontent.com/assets/848537/10270180/92244d8e-6b07-11e5-9a25-feb4679379a2.png)
![pixiv-outlined](https://cloud.githubusercontent.com/assets/848537/10270181/9228e9fc-6b07-11e5-9895-b85431601d8e.png)

**Comment by Templarian** [comment]
Yea, sorry but this might be too specific for the icon pack at this time.

In the future there may be a brand only pack that this would fit, but right now we're refocusing the included brand icons to only include social media related icons. If this pack is started we'll use the tag to see which ones were rejected.

**Comment by CoDEmanX** [comment]
Label ping-pong :smile:

**Comment by nodegin** [comment]
I assume somebody got a pixiv profile and want to post on their website, just like linkedin, github etc

**Comment by Quiple** [comment]
Really need this...

**Comment by goyney** [comment]
@Quiple We're not really adding many brand icons anymore. Instead, we recommend checking out [SimpleIcons](https://simpleicons.org/). They may be a better fit for this brand.
