### ISSUE TITLE
Broken down bus icon

### ISSUE THREAD

**Issue by mulderpf** [Templarian/MaterialDesign#7190]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I have a transport app specifically related to buses.  Sometimes a bus breaks down and I would like to have an icon which depicts this.

### Give us an example of what this icon might look like.

Some possible ideas:

- A bus with a plume of smoke coming out of it
- A bus which looks like it crashed into something
- A bus icon with a cross indicating it is broken
- A bus icon with a wrench indicating it might need repair

**Comment by MrGrigri** [comment]
Would `bus-alert` suffice?

![bus-alert](https://github.com/Templarian/MaterialDesign/assets/4528551/31c6a47c-65ae-4674-975b-bb84efedb8c6)

**Comment by mulderpf** [comment]
Unfortunately not - as I have indicated, I have searched the library and came across this, but it isn't suitable as this is an icon which I use if there's a scheduling issue or a bus is running late to alert a user.  A bus which is out of service or broken down is a status, rather than an alert (this icon is an alert one).

**Comment by mririgoyen** [comment]
`bus-wrench` would be the only one of the suggested options that I think would work.

**Comment by MrGrigri** [comment]
![bus-wrench](https://github.com/Templarian/MaterialDesign/assets/4528551/f9560355-59b2-4bf2-a155-e13d280d6a01)

---

![bus-wrench](https://github.com/Templarian/MaterialDesign/assets/4528551/043ed31b-e48b-448c-bb29-8f1df8152b0e)

**Comment by MrGrigri** [comment]
[![bus-wrench](https://pictogrammers.com/library/mdi/icon/bus-wrench)](https://pictogrammers.com/library/mdi/icon/bus-wrench)
