### ISSUE TITLE
Non-tropical island icon

### ISSUE THREAD

**Issue by Springvar** [Templarian/MaterialDesign#7191]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

There should be an island icon for islands that aren't tropical. I suggest one with a pine tree instead of the palm tree, and perhaps one with a little house to indicate an inhabited island.

### Give us an example of what this icon might look like.

Identical to current island icon, but with the palm-tree swapped with pine-tree, tree or house

**Comment by MrGrigri** [comment]
What about this?

![island-variant](https://github.com/Templarian/MaterialDesign/assets/4528551/f69a0fe1-7db8-4c3c-b9f2-b2697ba94a8d)

**Comment by MrGrigri** [comment]
[![island-variant](https://pictogrammers.com/library/mdi/icon/island-variant)](https://pictogrammers.com/library/mdi/icon/island-variant)
