### ISSUE TITLE
Paragraph icon

### ISSUE THREAD

**Issue by f-g-s** [Templarian/MaterialDesign#7194]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

for imprint

### Give us an example of what this icon might look like.

![images](https://github.com/Templarian/MaterialDesign/assets/7393703/52cdd0a4-f195-4990-95c1-9ec1a0eaa26b)

**Comment by MrGrigri** [comment]
We already have that icon. That is a section icon. The paragraph icon is called a pilcrow, which we too have.

[![format-section](https://github.com/Templarian/MaterialDesign/assets/4528551/abecd71a-ace6-4298-8ef7-8d4d6c125fea)](https://pictogrammers.com/library/mdi/icon/format-section/) [![format-pilcrow](https://github.com/Templarian/MaterialDesign/assets/4528551/dd3b1b57-24d4-4989-b76a-7c73b3fc2f8c)](https://pictogrammers.com/library/mdi/icon/format-pilcrow/)
