### ISSUE TITLE
Common fruits

### ISSUE THREAD

**Issue by donparlor** [Templarian/MaterialDesign#7198]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Build different cards in Home Assistant where I could definitely use it.
The fruits that I would personally need are the following:
-Strawberry
-Raspberry
-Banana
-Haskap
-Blueberry
-Pineapple (I used your icon)
-Dragon fruit
-Peach
-Cranberry

### Give us an example of what this icon might look like.

Nothing fancy, just a quick look that gives an idea of the fruit we're talking about.

**Comment by mririgoyen** [comment]
Some of these requests already exist.

- Strawberry - #4491
- Raspberry - #3378
- Banana - #5898
- Haskap
- Blueberry
- Pineapple - Already exists
- Dragon fruit
- Peach
- Cranberry

Things like Cranberry and Blueberry would be very hard to distinguish a difference in an icon, so perhaps those can be combined.

Can you please open individual requests for the following icons? While they are all fruits, they are all pretty different.

- Haskap
- Blueberry/Cranberry
- Peach
- Dragonfruit

**Comment by mririgoyen** [comment]
We're a community of volunteers. There's always a possibility they could be acted upon quickly, but there's never a guarantee.

**Comment by donparlor** [comment]
I understand. Thank you for bringing me here so I can suggest new icons. Wish you the best
