### ISSUE TITLE
Relational icons needed (one-to-many, many-to-one)

### ISSUE THREAD

**Issue by mdingena** [Templarian/MaterialDesign#720]
I need icons that represent a relation between rows. I need it to represent one-to-many and many-to-one relations.

Witness my awesome MS Paint skills:
![image](https://cloud.githubusercontent.com/assets/13388489/10220868/bb9dd078-684a-11e5-87cf-188c7c3aff1a.png)
- [ ] `database-one-to-one`
- [ ] `database-one-to-many`
- [ ] `database-many-to-one`
- [ ] `database-many-to-many`

**Comment by CoDEmanX** [comment]
Possibly one-to-one and many-to-many as well from a data modelling perspective.

**Comment by Templarian** [comment]
Updated the issue description above with tasks to include @CoDEmanX's suggestion.

These would be very useful icons to have.

**Comment by mdingena** [comment]
Possible designs for one-to-one and many-to-many:

![image](https://cloud.githubusercontent.com/assets/13388489/10338642/6f4fb512-6d07-11e5-9d49-5632a98a95a2.png)

**Comment by MrGrigri** [comment]
Here are probably the four most common.

![image](https://user-images.githubusercontent.com/4528551/62888956-9c81a280-bcfd-11e9-943f-4674d959de0e.png) ![image](https://user-images.githubusercontent.com/4528551/62888995-adcaaf00-bcfd-11e9-89ab-0308db27ab50.png) ![image](https://user-images.githubusercontent.com/4528551/62889050-cfc43180-bcfd-11e9-84b4-b169c769369e.png) ![image](https://user-images.githubusercontent.com/4528551/62889098-dfdc1100-bcfd-11e9-9c51-ef9c8821ff62.png)

---

#### Files

[data-relation.zip](https://github.com/Templarian/MaterialDesign/files/3493852/data-relation.zip)

**Comment by CoDEmanX** [comment]
Is your work inspired by some visualization standard like UML? Haven't seen it before and it does not seem very intuitive.

**Comment by MrGrigri** [comment]
I got these from a UML of sorts from [Lucidchart](https://www.lucidchart.com/pages/ER-diagram-symbols-and-meaning).

**Comment by goyney** [comment]
Lucidchart makes some funny videos, but they do not make good icons obviously.

**Comment by JapanYoshi** [comment]
While I recognized the UML symbols, I don't think they're suited to graphically represent relations, at least for people who aren't CS majors.
I made some icons based on `format-list-bulleted-square`:
![image](https://user-images.githubusercontent.com/8707990/63320862-64fca100-c362-11e9-9355-f42e0731c5ed.png)
![image](https://user-images.githubusercontent.com/8707990/63320881-72b22680-c362-11e9-9f71-0facf8dacd54.png)
![image](https://user-images.githubusercontent.com/8707990/63320894-7e055200-c362-11e9-9db5-7b054e6b28fb.png)

**Comment by mariovials** [comment]
I need these icons too. 
I think these symbols are the standard.

![image](https://user-images.githubusercontent.com/1584766/63353631-0539d200-c331-11e9-9c45-bc17e59266f5.png)

If they could make icons it would be great!
Thank you!

**Comment by MrGrigri** [comment]
@mariovials, that is what I based mine off of. I didn't do the zero ones though. Are those needed as well?

**Comment by mariovials** [comment]
I don't need them now. 
Although perhaps you could take advantage of adding that too before they ask for it.
Thanks for your work, it's great!

**Comment by MrGrigri** [comment]
I believe we should add the UML standard endings as icons as I've done above. There are a couple that could be added, but adding these would add 36 total icons and that's why I left them out in the first place.  These are the different terminators and each one would be paired with the other. I will make them and put them up here (hopefully get me some more icons)

- One
- Many
- One (and only one)
- Zero or one
- One or many
- Zero or many

Example
---

![image](https://user-images.githubusercontent.com/4528551/63354884-758d2700-c322-11e9-9073-c39c7cc55f79.png)

**Comment by goyney** [comment]
@MrGrigri If those are the standard, I say we just add them all. What you prepared above looks good, so if you make them in that style, just go add them. 😄

**Comment by MrGrigri** [comment]
I'm only showing the icons `relation-one-to-*`. All 36 icons are in the single SVG. Each path is pre-optimized with an ID for its icon name. I've also included the Illustrator file just in case something is screwed up. 

![image](https://user-images.githubusercontent.com/4528551/63365900-cce8c280-c335-11e9-91ab-0917f743e89b.png) ![image](https://user-images.githubusercontent.com/4528551/63365914-d540fd80-c335-11e9-8435-4d660f47f15e.png) ![image](https://user-images.githubusercontent.com/4528551/63365932-df62fc00-c335-11e9-9996-de7903fe7e81.png) ![image](https://user-images.githubusercontent.com/4528551/63365949-ea1d9100-c335-11e9-9f8e-5bda48d8b0b4.png) ![image](https://user-images.githubusercontent.com/4528551/63365965-f30e6280-c335-11e9-9bca-794931768536.png) ![image](https://user-images.githubusercontent.com/4528551/63365979-f99cda00-c335-11e9-835a-11eca0ade6ae.png)

---
#### Files

[relation.zip](https://github.com/Templarian/MaterialDesign/files/3521660/relation.zip)

**Comment by mariovials** [comment]
Sorry for my work, I didn't have the Illustrator at hand, but I tried to do something with an image editor.
It's a variant.
![one-to-only-one](https://user-images.githubusercontent.com/1584766/63376587-2b289c00-c35c-11e9-95f5-dd3aa46bbdb8.png)
![one-to-zero-or-one](https://user-images.githubusercontent.com/1584766/63376605-37145e00-c35c-11e9-8551-0d561a77f464.png)
![one-to-one-or-many](https://user-images.githubusercontent.com/1584766/63376618-409dc600-c35c-11e9-936a-ee4a9fe98b39.png)
![one-to-zero-or-many](https://user-images.githubusercontent.com/1584766/63376626-44314d00-c35c-11e9-9dfd-118627f93dd8.png)

It might be useful to have a variant

**Comment by MrGrigri** [comment]
I believe we should just stick to the UML standard. Those can get confusing.

**Comment by CoDEmanX** [comment]
To follow the UML standard we would need to use their "many" terminal though: `⪪`

**Comment by MrGrigri** [comment]
That is too much detail at 1x. That's why I used a triangle. Plus, I've seen a triangle before...I believe Access uses it. By standard, I mean it's concept

**Comment by CoDEmanX** [comment]
Probably, but it has "many" ends (3), which is somewhat intuitive. A triangle doesn't really convey this meaning.

Why do we need both ends in a single icon BTW? Why not icons for each UML terminal?

**Comment by JapanYoshi** [comment]
I implemented some of @mariovials' suggestions. Thank you!
![image](https://user-images.githubusercontent.com/8707990/63417704-20960180-c445-11e9-8d5e-93cd3dc2e67a.png)![image](https://user-images.githubusercontent.com/8707990/63417788-4de2af80-c445-11e9-829c-dfe6511d2bf2.png)![image](https://user-images.githubusercontent.com/8707990/63417871-6fdc3200-c445-11e9-9ae7-79fe364bda1a.png)![image](https://user-images.githubusercontent.com/8707990/63417903-81253e80-c445-11e9-8ef8-fbc44563f3e7.png)![image](https://user-images.githubusercontent.com/8707990/63418024-ba5dae80-c445-11e9-81c2-8e1c3f6b9465.png)
I also made primary key and foreign key icons, but I'll post them on another thread.

**Comment by MrGrigri** [comment]
@CoDEmanX, We could do singles as well. But the reasoning behind the two terminals on one icon is to represent the relation between two records.

Also, I tried the tree lines, but it didn't work well; too small.

**Comment by Templarian** [comment]
Feel like these are pretty close to being added. If someone can finalize and add them. ✔️

**Comment by goyney** [comment]
All 36 of @MrGrigri's icons have been added. See `relation-*` set.
