### ISSUE TITLE
dots-spiral

### ISSUE THREAD

**Issue by SnowMB** [Templarian/MaterialDesign#7207]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Dots on a spiral path.

### Share a preview of your contribution.

![Untitled](https://github.com/Templarian/MaterialDesign/assets/7050959/415570b4-42f4-4462-a96e-cb2c2891616f)

### Upload the icon source.

[dots-spiral.zip](https://github.com/Templarian/MaterialDesign/files/12334332/dots-spiral.zip)

**Comment by MrGrigri** [comment]
First off, the circles would need to be a whole-numbered radius and they need to be on-grid. What is the purpose of this icon? Why is it needed?
