### ISSUE TITLE
Request: PRO Icon

### ISSUE THREAD

**Issue by ritdaw** [Templarian/MaterialDesign#721]
I'd like to request an icon that suggests a pro upgrade for example and in-app purchase to get additional app features. Something similar to the below but perhaps a rectangle.

![image](https://cloud.githubusercontent.com/assets/2089152/10225004/a74562b8-6858-11e5-9077-d66a18a6a8d6.png)

**Comment by Templarian** [comment]
[![professional-hexagon](https://materialdesignicons.com/icon/professional-hexagon)](https://materialdesignicons.com/icon/professional-hexagon)

1.25 character width looked nicest. Although we try not to use text in the icons I think this looks okay.

**Comment by ritdaw** [comment]
Perfect thanks!
