### ISSUE TITLE
bus-sign

### ISSUE THREAD

**Issue by MrGrigri** [Templarian/MaterialDesign#7210]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

This icon could be used to represent a bus detour (due to construction) or an alternative to our already-existing `bus-stop`.

### Give us an example of what this icon might look like.

![bus-sign](https://github.com/Templarian/MaterialDesign/assets/4528551/cde9bff6-d55c-40ae-81fa-903ce8c55325)

---

![bus-sign](https://github.com/Templarian/MaterialDesign/assets/4528551/9a1ab056-2bf7-42d8-8982-e6710c495052)

**Comment by MrGrigri** [comment]
[![bus-sign](https://pictogrammers.com/library/mdi/icon/bus-sign)](https://pictogrammers.com/library/mdi/icon/bus-sign)

**Comment by mririgoyen** [comment]
I'm not sure I like this one. And it's not a standard modifier. 😕
