### ISSUE TITLE
game console control

### ISSUE THREAD

**Issue by TheRealPixelGuy** [Templarian/MaterialDesign#7211]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

game console control

### Give us an example of what this icon might look like.

![13282](https://github.com/Templarian/MaterialDesign/assets/142334536/8318b35c-dca5-4082-a6ae-2ea70735b1ab)

**Comment by MrGrigri** [comment]
Please search our library before requesting an icon. We currently have four different controller types. With each of those having an outlined variant

![controller](https://github.com/Templarian/MaterialDesign/assets/4528551/c239c8c1-0610-499f-9d33-7f42863e5a3e) ![controller-classic](https://github.com/Templarian/MaterialDesign/assets/4528551/ae93dad0-8aba-499c-9110-8f39b9945cbb)

![gamepad-square](https://github.com/Templarian/MaterialDesign/assets/4528551/e3ce9eb0-7e1f-4b17-940b-e13cd86e373e) ![gamepad-variant](https://github.com/Templarian/MaterialDesign/assets/4528551/486fca57-d1a7-412e-9301-474e54270f67)
