### ISSUE TITLE
Missing icon from material icons

### ISSUE THREAD

**Issue by skjnldsv** [Templarian/MaterialDesign#7218]
### Where are you experiencing this bug?

@mdi/svg

### What is the issue you are experiencing?

Some icons are missing from this repository

https://fonts.google.com/icons?icon.query=copy&selected=Material+Icons+Round:file_copy:&icon.style=Rounded&icon.set=Material+Icons

Example:
| File Copy | Folder Copy |
|:---------:|:------:|
|![round_file_copy_black_24dp](https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/14975046/3afc7aeb-ebdf-4e77-8027-f8d76f309f61)|![round_folder_copy_black_24dp](https://github.com/nextcloud-libraries/nextcloud-dialogs/assets/14975046/7b122911-1777-408f-8d9e-b9af8f2f7e45)|

### Additional comments

Is there no auto sync from the google ones?

**Comment by mririgoyen** [comment]
Both exist, though file goes the opposite direction to show multiple, following our standard.
[![file-multiple](https://pictogrammers.com/library/mdi/icon/file-multiple)](https://pictogrammers.com/library/mdi/icon/file-multiple)
[![folder-multiple](https://pictogrammers.com/library/mdi/icon/folder-multiple)](https://pictogrammers.com/library/mdi/icon/folder-multiple)

**Comment by skjnldsv** [comment]
Thanks, searching for multiple did not occurred to me :)

- https://github.com/Templarian/MaterialDesign/issues/7220
- https://github.com/Templarian/MaterialDesign/issues/7219
