### ISSUE TITLE
materialdesignicons.com export size limitation

### ISSUE THREAD

**Issue by seanmcne** [Templarian/MaterialDesign#722]
Love the new editor, however I was able to export icons as 16px square - it appears anything under 18px is blocked.  Is it possible to put the min at 16 (or whatever the lowest you'd be comfortable with).

**Comment by Templarian** [comment]
They are going to come out pretty blurry at 16x16. I would actually suggest using another icon pack that is more pixel perfect at that resolution. There is no technical limitation I simply hard coded the min at 18.

**Comment by CoDEmanX** [comment]
Good point, would be funny to export to half the size still (12px).

**Comment by Templarian** [comment]
That was a lot of work but it's fixed. At first I thought I would have to replace 18 with 12, then it dawned on me I could just change the 8 to a 2. Really cut down on the work.

**Comment by seanmcne** [comment]
Fantastic, thanks!  I realize they may be a little blurry, but the system we're using requires a 16x16 icon for a quick view/tiny icon to represent the data.  Very helpful, as always, gents!
