### ISSUE TITLE
Waze Icon

### ISSUE THREAD

**Issue by mikimn** [Templarian/MaterialDesign#723]
I've found no icon for the waze navigation app but I think one would really be of use!

**Comment by PeterShaggyNoble** [comment]
Brand assets can be found [here](https://brandfolder.com/waze).

**Comment by MrGrigri** [comment]
![image](https://user-images.githubusercontent.com/4528551/46355171-8acf6900-c61d-11e8-95e3-b4a1659bf06d.png)

[waze.zip](https://github.com/Templarian/MaterialDesign/files/2438292/waze.zip)

**Comment by Templarian** [comment]
[![waze](https://materialdesignicons.com/icon/waze)](https://materialdesignicons.com/icon/waze)
