### ISSUE TITLE
Bitly, url shortener icon

### ISSUE THREAD

**Issue by joecks** [Templarian/MaterialDesign#724]
![shortener](https://cloud.githubusercontent.com/assets/180698/10263413/77ab7474-69ee-11e5-905a-cee324f3564b.png)

Will be used in clipboard actions 
http://joecks.github.io/clipboard-actions/

**Comment by CoDEmanX** [comment]
Some more inspiration:

![Imgur](http://i.imgur.com/ous6h1f.png?1)

![shortlink](https://pilotmoon.com/popclip/extensions/icon/shortlink.png)

![compress](http://cdn.makeuseof.com/wp-content/uploads/2012/10/compression-icon.jpg?e9577d)

**Comment by joecks** [comment]
I like the first one, the second one looks like a broken link.

**Comment by PeterShaggyNoble** [comment]
Per the last comment, [`format-horizontal-align-center`](https://materialdesignicons.com/icon/format-horizontal-align-center) fulfils this request.
