### ISSUE TITLE
HOMEd Icon

### ISSUE THREAD

**Issue by DGMiron** [Templarian/MaterialDesign#7247]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

HOMEd is the name of a set of applications and smart home hardware that work together.
HOMEd ZigBee - The application is a bridge between the ZigBee network and the MQTT broker.
HOMEd Automation - This is a service for automation.
HOMEd Web - Self-hosted web interface for HOMEd ZigBee and HOMEd Automation

https://wiki.homed.dev/page/HOMEd

https://github.com/u236/homed-service-zigbee
https://github.com/u236/homed-service-automation
https://github.com/u236/homed-service-web

I really like the software Home Assistant. It is used to create smart home. Home Assistant uses Material Design Icons. HOMEd has Home Assistant MQTT Discovery for all supported devices and integrates into the Home Assistant control panel. But it doesn't have its own icon.

### Give us an example of what this icon might look like.

![homed](https://github.com/Templarian/MaterialDesign/assets/88690230/66baabea-259f-4377-b193-f04fd8d4a60d)
![homed](https://github.com/Templarian/MaterialDesign/assets/88690230/42e9ff4f-e7c2-4be2-9dba-2adad9688d1b)

**Comment by u236** [comment]
There is svg image:
https://github.com/u236/homed-service-web/blob/master/deploy/data/usr/share/homed-web/img/homed.svg

**Comment by mririgoyen** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
