### ISSUE TITLE
Icons for various food types

### ISSUE THREAD

**Issue by Sereri** [Templarian/MaterialDesign#725]
For example:
- Beef (cow)
- Pork (pig)
- Poultry (chicken / bird)
- Venison (deer)
- Lamb
- Fish
- Seafood (shrimp)
- Vegetarian (milk carton + egg + leaf)
- Vegan (leaf / carrot)

**Comment by CoDEmanX** [comment]
Do vegetarians really eat milk cartons? :tongue:

We already have cow and pig, and there's an owl if you stretch poultry a bit. Will check next week if I can create some of them.

**Comment by Sereri** [comment]
I noticed there is actually a "leaf" icon already. That's what you get for looking too narrowly.

So whats actually left is:

- Poultry (chicken / bird)
- Venison (deer)
- Lamb
- Seafood (shrimp)
- Vegetarian (milk carton + egg + leaf)

**Comment by JamesCoyle** [comment]
Gonna close this one out. If anyone still needs these icons, please open a new issue for each one individually so we can track them better.
