### ISSUE TITLE
Loading icon

### ISSUE THREAD

**Issue by pxm11** [Templarian/MaterialDesign#7257]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

It could be used to show a process being loaded

### Give us an example of what this icon might look like.

![image](https://github.com/Templarian/MaterialDesign/assets/96004728/0b75dd4d-c387-4209-acb6-8a802279362e)

imagelink: 

https://www.google.com/url?sa=i&url=https%3A%2F%2Fpngtree.com%2Fso%2Floading-icon&psig=AOvVaw1aZQL82IC9jLt8GMnD9lAl&ust=1697622737332000&source=images&cd=vfe&ved=0CBEQjRxqFwoTCLjAxdPn_IEDFQAAAAAdAAAAABAE

**Comment by mririgoyen** [comment]
We already have a loading icon in the library.

[![loading](https://pictogrammers.com/library/mdi/icon/loading)](https://pictogrammers.com/library/mdi/icon/loading)
