### ISSUE TITLE
'logout': update path?

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#7269]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

Very grateful for the updated login & logout icons in `v7.3.67`!

Just one minor OCD trigger… [logout](https://pictogrammers.com/library/mdi/icon/logout/)'s arrow doesn't match the others:

<img width="624" alt="image" src="https://github.com/Templarian/MaterialDesign/assets/55925048/3e01a63f-0976-40bd-a091-fb64fef936e7">

### Suggested tweak

Use Google's **Filled** variant of the icon:
https://fonts.google.com/icons?selected=Material%20Icons%3Alogout%3A

Which (mysteriously) is different from the **Outlined** variant:
https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Alogout%3A

### Preview

![image](https://github.com/Templarian/MaterialDesign/assets/55925048/1b7196e3-cbdd-45ad-b0c5-b67da4f269a6)

### SVG file
Downloaded from [Material Icons](https://fonts.google.com/icons?selected=Material%20Icons%3Alogout%3A)

![login_black_24dp](https://github.com/Templarian/MaterialDesign/assets/55925048/3a81faae-ab70-4879-96dc-520910a5f082)

**Comment by Templarian** [comment]
Good find. Fixed.
