### ISSUE TITLE
Can't use mdi-cash-edit in v7.3.67.

### ISSUE THREAD

**Issue by HuanVo** [Templarian/MaterialDesign#7271]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

Im can't  use mdi-cash-edit in v7.3.67. This is a bug?

**Comment by Templarian** [comment]
- https://pictogrammers.github.io/@mdi/font/7.3.67/
- https://www.npmjs.com/package/@mdi/font?activeTab=code
- https://github.com/Templarian/MaterialDesign-Webfont 

@HuanVo Have to ask did you run `npm install` after updating? It looks like everything should be there.

**Comment by Templarian** [comment]
Going to close this issue out. If you're still having an issue please let us know.
