### ISSUE TITLE
Missing icon

### ISSUE THREAD

**Issue by Bruskyer** [Templarian/MaterialDesign#7275]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

hello,
after I passed  to from 4.7.x to 6.2.x  my hamburger menu icon is gone content:'獵' and my drodown arrow is gone also.
any help/solutions?
thanks regards

**Comment by gtjamesa** [comment]
Did you check to see if any icons were renamed? https://pictogrammers.com/docs/library/mdi/releases/upgrade/

**Comment by Simran-B** [comment]
The codepoints have been reassigned in 5.0.x: https://github.com/Templarian/MaterialDesign/issues/4901
