### ISSUE TITLE
numeric-1-hexagon, numeric-2-hexagon, etc.

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#728]

**Comment by CoDEmanX** [comment]
You mean like this?
![hexagon-1](https://cloud.githubusercontent.com/assets/1309249/10308759/43dfa182-6c38-11e5-86a2-53b0248a5b20.png)

Wouldn't it be easier to do this with inline SVGs? You could put anything inside the hexagon that way.

**Comment by metalla030** [comment]
yes

**Comment by metalla030** [comment]
mit svg kemnne ich mich nicht aus

**Comment by goyney** [comment]
We've discussed this internally and have decided we don't want to add yet another variation on all the numeric icons. Thank you for your suggestion.

**Comment by PeterShaggyNoble** [comment]
With the recent addition of the `alpha-*` and `numeric-*` icons, it is now easy to create your own icons of this type by combining the path fo the base shape with the path of the character you want. For example, `numeric-8` on top of `hexagon-outline`:

![numeirc-8-hexagon-outline](https://user-images.githubusercontent.com/15157491/48717026-83d1d980-ec10-11e8-8485-9d1aa9faa7b8.png)

**Comment by goyney** [comment]
Also, if you're using `@mdi/react`, using the `Stack` component makes what @PeterShaggyNoble mentioned trivial.
