### ISSUE TITLE
moonrise / moonset

### ISSUE THREAD

**Issue by cyberfly79** [Templarian/MaterialDesign#7285]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The moonrise and moonset icon would be very useful...

### Give us an example of what this icon might look like.

In a similar form as the sunrise, sunset icon.

**Comment by jhil** [comment]
[![weather-moonset](https://pictogrammers.com/library/mdi/icon/weather-moonset)](https://pictogrammers.com/library/mdi/icon/weather-moonset)
[![weather-moonset-down](https://pictogrammers.com/library/mdi/icon/weather-moonset-down)](https://pictogrammers.com/library/mdi/icon/weather-moonset-down)
[![weather-moonset-up](https://pictogrammers.com/library/mdi/icon/weather-moonset-up)](https://pictogrammers.com/library/mdi/icon/weather-moonset-up)
