### ISSUE TITLE
Hen

### ISSUE THREAD

**Issue by Pierikku** [Templarian/MaterialDesign#7288]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For Hen or Livestock Carriers

### Give us an example of what this icon might look like.

![chicken-clipart-silhouette-3](https://github.com/Templarian/MaterialDesign/assets/136022593/b6d67afe-a67d-412e-bd84-fd4ed7a5cc37)

**Comment by mririgoyen** [comment]
Also a duplicate.
