### ISSUE TITLE
spider

### ISSUE THREAD

**Issue by metalla030** [Templarian/MaterialDesign#729]
![pumpkin](http://2.bp.blogspot.com/-1sngLLRcFVM/Um86GFP0RJI/AAAAAAAAMWc/Xnu96nc_cnQ/s1600/pumpkin+with+faces.png)

![spider](http://i.imgur.com/g7odVx4.png?1)

**Comment by CoDEmanX** [comment]
You are looking for Halloween icons, aren't you?

**Comment by Templarian** [comment]
Lets try and get these in for the next release which should be around Halloween.

**Comment by Templarian** [comment]
Still need spider, the others were added. 😄

**Comment by MrGrigri** [comment]
It'll make it this year.

![image](https://user-images.githubusercontent.com/4528551/66237669-e7db8000-e6b2-11e9-8eef-453563d0021f.png)

--- 
#### Files

[spider.zip](https://github.com/Templarian/MaterialDesign/files/3692217/spider.zip)

**Comment by MrGrigri** [comment]
Optionally we could add it without the hourglass

![image](https://user-images.githubusercontent.com/4528551/66238818-98e31a00-e6b5-11e9-9a35-9d06f12a83b5.png)

**Comment by MrGrigri** [comment]
Also a `spider-web` one.

![image](https://user-images.githubusercontent.com/4528551/66239272-acdb4b80-e6b6-11e9-8f55-baf61f127c5c.png)

[spider-thread.zip](https://github.com/Templarian/MaterialDesign/files/3692307/spider-thread.zip)

**Comment by Templarian** [comment]
Added. ✅
