### ISSUE TITLE
file-document-alert-outline not aligned properly

### ISSUE THREAD

**Issue by JoniLieh** [Templarian/MaterialDesign#7291]
### Where are you experiencing this bug?

@mdi/font

### What is the issue you are experiencing?

I'm using multiple `file-document-outline` icons and `file-document-alert-outline` has an offset to the left.

![asd](https://github.com/Templarian/MaterialDesign/assets/57151672/9c1bb2d1-79a2-4f50-9643-0112afffecb1)

**Comment by mririgoyen** [comment]
This isn't a bug, but how the icon was designed. The ! must be 2dp from the edge of the base icon.

**Comment by JoniLieh** [comment]
Thanks for clarifying that, just looks soo odd compared to the others.
