### ISSUE TITLE
chart-box-multiple & chart-box-multiple-outline

### ISSUE THREAD

**Issue by konstantinsaller** [Templarian/MaterialDesign#7296]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I propose to add a chart-box-multiple Icon (chart-box-multiple-outline). As there already is a chart box icon, it would be nice to have a '-multiple' version of it. For example, in projects that need an icon for multiple datasets, these icons could be useful. (That's where I will use it)

### Share a preview of your contribution.

![chart-box-multiple](https://github.com/Templarian/MaterialDesign/assets/31797403/54486ce9-9774-4bd7-8365-2a8eeb04f5ba)
![chart-box-multiple-outline](https://github.com/Templarian/MaterialDesign/assets/31797403/2df918e1-7090-4945-9434-33d8ca7b7eaf)

### Upload the icon source.

[chart-box-multiple.zip](https://github.com/Templarian/MaterialDesign/files/13376790/chart-box-multiple.zip)

**Comment by jhil** [comment]
Added!

[![chart-box-multiple](https://pictogrammers.com/library/mdi/icon/chart-box-multiple)](https://pictogrammers.com/library/mdi/icon/chart-box-multiple)
