### ISSUE TITLE
Changelog for 7.3.67

### ISSUE THREAD

**Issue by marriott5299** [Templarian/MaterialDesign#7297]
### What is your question?

Hi, is there a change log available for 7.3.67? I would like to upgrade from 7.2.97, but there are often name changes that are breaking for my application so would like to make sure I don't hit any breaking changes. 

Thanks

**Comment by Templarian** [comment]
@marriott5299 oh, looks like I never pushed those changes to the website. There were no breaking changes, but the icons that got updates visually are:

- `format-strikethrough-variant`
- `human-male-female-child`
- `image-remove`
- `login`
- `logout`
- `radioactive-circle-outline`
- `radioactive-circle`
- `radioactive-off`
- `radioactive`
- `turbine`
