### ISSUE TITLE
Outlook Icon

### ISSUE THREAD

**Issue by Shahrukhinamdar** [Templarian/MaterialDesign#730]
Please Attach Outlook icon

**Comment by CoDEmanX** [comment]
That's a product icon as opposed to Word / Excel / PowerPoint, which are also applications, but icons of them are commonly used for files these applications create. So not sure it fits in the pack according to the new rule "no brand icons".

**Comment by JamesCoyle** [comment]
Need's a bit of work I think.
![image](https://user-images.githubusercontent.com/10384436/45600495-8a1bbd80-b9f5-11e8-9575-e6ba674689e4.png)

```
M 14 2 L 2 4 L 2 20 L 14 22 Z M 15 7 L 15 9.25 L 17 10.40625 L 21 8.09375 L 21 9.6875 L 17 12 L 15 10.84375 L 15 17 H21 c1 0 1 -1 1 -1  L 22 8 C 22 7.398438 21.601563 7 21 7 Z M 7.59375 8 C 8.613281 8 9.425781 8.371094 10.0625 9.09375 C 10.691406 9.816406 11 10.757813 11 11.9375 C 11 13.148438 10.691406 14.164063 10.03125 14.90625 C 9.382813 15.648438 8.519531 16 7.46875 16 C 6.441406 16 5.605469 15.628906 4.96875 14.90625 C 4.320313 14.183594 4 13.253906 4 12.09375 C 4 10.871094 4.308594 9.878906 4.96875 9.125 C 5.628906 8.371094 6.511719 8 7.59375 8 Z M 7.53125 9.5 C 6.964844 9.5 6.515625 9.730469 6.1875 10.1875 C 5.859375 10.644531 5.6875 11.246094 5.6875 12 C 5.6875 12.773438 5.859375 13.394531 6.1875 13.84375 C 6.515625 14.292969 6.953125 14.5 7.5 14.5 C 8.054688 14.5 8.492188 14.269531 8.8125 13.84375 C 9.140625 13.40625 9.3125 12.804688 9.3125 12.03125 C 9.3125 11.238281 9.152344 10.625 8.84375 10.1875 C 8.527344 9.738281 8.078125 9.5 7.53125 9.5 Z M 19.5 14   Z  ```

**Comment by goyney** [comment]
I believe we should match the style of our existing `onenote` icon.
![image](https://user-images.githubusercontent.com/1015040/48989182-1bdf2f80-f0f7-11e8-8108-2698c38dcd9d.png)
[outlook.svg.zip](https://github.com/Templarian/MaterialDesign/files/2613849/outlook.svg.zip)


---

OneNote icon for reference:
![image](https://user-images.githubusercontent.com/1015040/48988898-f43b9780-f0f5-11e8-9df2-21b48721024e.png)

**Comment by Templarian** [comment]
Added, but we may have to go back and revise these eventually.
