### ISSUE TITLE
Invoice icon

### ISSUE THREAD

**Issue by AlfonsoML** [Templarian/MaterialDesign#7304]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

The library suggest the "Receipt-*" icons when I search for Invoice, but a ticket is not exactly the same.

### Give us an example of what this icon might look like.

A paper sheet with lines and a $ sign. 
Similar to receipt-text-outline, without jagged borders and something that shouts money (the $)
Also an icon "new Invoice" by overlaying a + sign at the bottom right like receipt-text-plus-outline

**Comment by MrGrigri** [comment]
We are an international icon pack and we refrain from using the US currency symbol.

**Comment by AlfonsoML** [comment]
Indeed I would prefer if it isn't a dollar sign, I was suggesting just an idea to represent money or payment. I am not a designer at all and I don't know what are the best practices, I leave that to the experts.

**Comment by jhil** [comment]
I have been working on a set of invoice icons that's more suitable and recognizable than `receipt-` or `ticket-` for these use cases. Please let me know if this set works for you, too.

![Screenshot 2023-11-30 at 22 20 19](https://github.com/Templarian/MaterialDesign/assets/2228347/80b4d5f3-0256-42bf-92e0-7e3fdb3d7ce8)

I can get these added this weekend.

**Comment by jhil** [comment]
[![invoice](https://pictogrammers.com/library/mdi/icon/invoice)](https://pictogrammers.com/library/mdi/icon/invoice)
[![invoice-outline](https://pictogrammers.com/library/mdi/icon/invoice-outline)](https://pictogrammers.com/library/mdi/icon/invoice-outline)

[![invoice-text](https://pictogrammers.com/library/mdi/icon/invoice-text)](https://pictogrammers.com/library/mdi/icon/invoice-text)
[![invoice-text-outline](https://pictogrammers.com/library/mdi/icon/invoice-text-outline)](https://pictogrammers.com/library/mdi/icon/invoice-text-outline)

[![invoice-plus](https://pictogrammers.com/library/mdi/icon/invoice-plus)](https://pictogrammers.com/library/mdi/icon/invoice-plus)
[![invoice-plus-outline](https://pictogrammers.com/library/mdi/icon/invoice-plus-outline)](https://pictogrammers.com/library/mdi/icon/invoice-plus-outline)

[![invoice-text-plus](https://pictogrammers.com/library/mdi/icon/invoice-text-plus)](https://pictogrammers.com/library/mdi/icon/invoice-text-plus)
[![invoice-text-plus-outline](https://pictogrammers.com/library/mdi/icon/invoice-text-plus-outline)](https://pictogrammers.com/library/mdi/icon/invoice-text-plus-outline)

[![invoice-send](https://pictogrammers.com/library/mdi/icon/invoice-send)](https://pictogrammers.com/library/mdi/icon/invoice-send)
[![invoice-send-outline](https://pictogrammers.com/library/mdi/icon/invoice-send-outline)](https://pictogrammers.com/library/mdi/icon/invoice-send-outline)

[![invoice-text-send](https://pictogrammers.com/library/mdi/icon/invoice-text-send)](https://pictogrammers.com/library/mdi/icon/invoice-text-send)
[![invoice-text-send-outline](https://pictogrammers.com/library/mdi/icon/invoice-text-send-outline)](https://pictogrammers.com/library/mdi/icon/invoice-text-send-outline)

[![invoice-fast](https://pictogrammers.com/library/mdi/icon/invoice-fast)](https://pictogrammers.com/library/mdi/icon/invoice-fast)
[![invoice-fast-outline](https://pictogrammers.com/library/mdi/icon/invoice-fast-outline)](https://pictogrammers.com/library/mdi/icon/invoice-fast-outline)
