### ISSUE TITLE
Cookie Icon

### ISSUE THREAD

**Issue by ritdaw** [Templarian/MaterialDesign#731]
Something like this perhaps?

![icon__cookie](https://cloud.githubusercontent.com/assets/2089152/10307356/2917e1dc-6c26-11e5-81d0-fc0353e18671.png)

**Comment by CoDEmanX** [comment]
I like!

**Comment by CoDEmanX** [comment]
I posted an SVG over here:

https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-152785830

**Comment by CoDEmanX** [comment]
It has been added, release pending.
