### ISSUE TITLE
Use of icons in pseudo elements

### ISSUE THREAD

**Issue by naresh515** [Templarian/MaterialDesign#7317]
### What is your question?

I want use search icon in pseudo element but whenever i write the code for the element i didn't get the icon.  This was my code

div.dataTables_wrapper div.dataTables_filter::after {
  position: absolute;
  top: 0;
  right: 0;
  z-index: 99;
  font-family: 'Material Icons';
  content: "\F0349";
  -webkit-font-feature-settings: 'liga';
}

**Comment by Templarian** [comment]
The font name looks incorrect unless you modified the `@font-face` definition. It should be: `font-family: "Material Design Icons"`.

You should see the `magnify` glyph after that typo is fixed assuming the parent has `position: relative` etc.

**Comment by naresh515** [comment]
Thank you for your responsive and i find out my mistake in this code and done the changes and get the icon which i want
