### ISSUE TITLE
misising tiktok icon

### ISSUE THREAD

**Issue by PanoSpent** [Templarian/MaterialDesign#7318]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] #7319
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

for social media links

### Give us an example of what this icon might look like.

https://iconduck.com/icons/81292/tiktok

**Comment by jhil** [comment]
This library doesn't have brand icons!

>  I understand that brand icons are no longer being added and I can use SimpleIcons for my brand icon needs.

We suggest using https://simpleicons.org/
