### ISSUE TITLE
Repair icon

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#732]
e.g. a hammer, or like the road signs for garages

**Comment by CoDEmanX** [comment]
There's a wrench icon, anything wrong with that?

I tried to create a screw driver over here: https://github.com/Templarian/MaterialDesign/issues/574#issuecomment-128134075
Not sure if a combination of both would still be recognizable, but I doubt it. The screw driver is already not very legible.

**Comment by derwaldgeist** [comment]
I like your screwdriver. And I also like the Octicons tool icon linked in the other thread - this is exactly what I need. Would be great to have such an icon in MDI as well. I my use-case, the icon will be large enough to be recognizable even if wrench and screwdriver are combined.

**Comment by Templarian** [comment]
[![wrench](https://materialdesignicons.com/icon/wrench)](https://materialdesignicons.com/icon/wrench)

Issue #574 was also closed.

**Comment by derwaldgeist** [comment]
Thanks!

**Comment by CoDEmanX** [comment]
We are actually still missing a combination of two tools, which has been requested a few times.

**Comment by derwaldgeist** [comment]
+1 for such a combination

**Comment by PeterShaggyNoble** [comment]
Closing here; we can track the icon with 2 tools in #574
