### ISSUE TITLE
Emergency Icon

### ISSUE THREAD

**Issue by BastiFantasti83** [Templarian/MaterialDesign#733]
I need an icon for an emergency event.

Special for an emergency surgery.

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/plus-box but with wider strokes for the +?

**Comment by BastiFantasti83** [comment]
I think more like a ambulances car or an emergency light combined width a +!

**Comment by CoDEmanX** [comment]
There's actually
https://materialdesignicons.com/icon/hospital

and also https://materialdesignicons.com/icon/hospital

We lack a warning light though
![Imgur](http://i.imgur.com/3pydaCi.png?2)

**Comment by BastiFantasti83** [comment]
OK sorry i don't know why i don't notice the ambulance, i think that is ok for me.
