### ISSUE TITLE
change "litecoin" into a filled variant

### ISSUE THREAD

**Issue by ondrejnedoma** [Templarian/MaterialDesign#7331]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

The "litecoin" icon exists, but is currently just a simple outline. Trying to match the bitcoin icon, I created this, which I think could replace the current litecoin. Closing #7330 by creating this issue (I thought this repo works on pull requests :D)

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/117393974/aa82fd76-166c-42b7-a25e-ed528e0b016a)

### Upload the icon source.

![litecoin](https://github.com/Templarian/MaterialDesign/assets/117393974/c8c9e098-d8d9-418e-9732-77e67871d810)

**Comment by Templarian** [comment]
@ondrejnedoma That icon is deprecated and being removed in 8.0. All brand icons are being removed from the icon pack as Simple Icons is a much better alternative. See #6602 for more details on this decision.

https://pictogrammers.com/library/mdi/icon/litecoin/
