### ISSUE TITLE
Pix

### ISSUE THREAD

**Issue by gabrielpastori1** [Templarian/MaterialDesign#7338]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

"Pix" is a instante payment method in Brazil

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/58153955/3b6f34c9-b000-4b44-b341-8f29b8f6c7a3)

### Upload the icon source.

![Pix](https://github.com/Templarian/MaterialDesign/assets/58153955/b6031813-faad-4d90-8238-c2848eaa88c4)

**Comment by Templarian** [comment]
3rd item in the checklist. 🤦
