### ISSUE TITLE
Weapon Crosshair

### ISSUE THREAD

**Issue by Lampjaw** [Templarian/MaterialDesign#734]
I know there's a google created crosshairs and crosshairs-gps icon but neither really look a whole lot like actual crosshairs. Specifically I'd like an icon where the lines enter the inside of the circle whether like this

![crosshairs-480](https://cloud.githubusercontent.com/assets/1153840/10312927/2db882ba-6c1b-11e5-8c1c-4ed743ce7b4d.png)

Or where the lines intersect in the middle. Both would be nice.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/target Already exists?

**Comment by Lampjaw** [comment]
Perfect! Perhaps the site needs to have alises or tags for icons that could be defined with different words in the search :)

**Comment by CoDEmanX** [comment]
@Templarian: when will the tagging backend go live for contributers?
