### ISSUE TITLE
The official page is down since the last update

### ISSUE THREAD

**Issue by balage1551** [Templarian/MaterialDesign#7344]
### Where are you experiencing this bug?

Somewhere else

### What is the issue you are experiencing?

The official page is down since the last (7.4.47) update on 27th of December:

![image](https://github.com/Templarian/MaterialDesign/assets/11457054/c9a62c89-b1ee-4eac-ba5d-9701328dab54)

**Comment by Templarian** [comment]
@balage1551 The page is cached. If you hard refresh (ctrl+shift+r) it will work. Most should see it fine after a day.

Track how we're resolving this for future releases here: https://github.com/Pictogrammers/pictogrammers.com/issues/106
