### ISSUE TITLE
Coffee bean

### ISSUE THREAD

**Issue by Dominic-070** [Templarian/MaterialDesign#7347]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Home  Assistant

### Give us an example of what this icon might look like.

![image](https://github.com/Templarian/MaterialDesign/assets/62623885/fb18da91-8049-4b08-bc17-30dfa959f3d4)

**Comment by Templarian** [comment]
Added `coffee-bean`
