### ISSUE TITLE
Import Contacts icon

### ISSUE THREAD

**Issue by bsinc** [Templarian/MaterialDesign#735]
I've made this myself already, but figured I'd suggest it as well. An import contacts icon.

![import-contact](https://cloud.githubusercontent.com/assets/5923661/10319713/8c6ab4f0-6c24-11e5-840e-1a3a1499f3ff.png)

**Comment by CoDEmanX** [comment]
I think an arrow pointing straight down would be a bit cleaner.
Can you provide an SVG anyway?

**Comment by PeterShaggyNoble** [comment]
Google use [`book-open-variant`](https://materialdesignicons.com/icon/book-open-variant) for importing contacts and there's also [`account-multiple-plus`](https://materialdesignicons.com/icon/account-multiple-plus) & [`account-multiple-plus-outline`](https://materialdesignicons.com/icon/account-multiple-plus-outline).
