### ISSUE TITLE
Dog Icon

### ISSUE THREAD

**Issue by teddhuff** [Templarian/MaterialDesign#736]

**Comment by darlanmendonca** [comment]
+1

**Comment by JamesCoyle** [comment]
@darlanmendonca If you click on the face icon in the gray bar above a comment you can thumb up that post to +1 rather than creating a new comment.

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/42588387-b826144c-850b-11e8-9a15-feb44b9b3886.png)
[dog.zip](https://github.com/Templarian/MaterialDesign/files/2185507/dog.zip)

**Comment by PeterShaggyNoble** [comment]
I like it but I also still like @Croutonix's 3rd option.

**Comment by Templarian** [comment]
[![dog](https://materialdesignicons.com/icon/dog)](https://materialdesignicons.com/icon/dog) [![dog-side](https://materialdesignicons.com/icon/dog-side)](https://materialdesignicons.com/icon/dog-side)
