### ISSUE TITLE
Adding Matter icon

### ISSUE THREAD

**Issue by Mukhammadjon-Jalolov** [Templarian/MaterialDesign#7360]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I'm learning and developing Matter. So now I need it's icon

### Share a preview of your contribution.

Here is the link for the icon: [https://seeklogo.com/vector-logo/477960/matter-icon](https://seeklogo.com/vector-logo/477960/matter-icon)

### Upload the icon source.

![matter-icon-logo-105B56921E-seeklogo com](https://github.com/Templarian/MaterialDesign/assets/38403832/9b9cf3ed-21ac-44a4-8cd1-3fc37a5cf613)

**Comment by Simran-B** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
