### ISSUE TITLE
Radiant panel and floor

### ISSUE THREAD

**Issue by Padanian** [Templarian/MaterialDesign#7365]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Suggestion for icon dedicated for radiant heating systems

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/7769348/f82d6809-d0bc-41a9-8ef5-b07392dd6eec)

### Upload the icon source.

[radiant2.zip](https://github.com/Templarian/MaterialDesign/files/14054203/radiant2.zip)

**Comment by Templarian** [comment]
`radiant-heat` added.
