### ISSUE TITLE
Fingerbot

### ISSUE THREAD

**Issue by appsfinder2** [Templarian/MaterialDesign#7373]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

hi i would like the figerbot icon for home assistant thanks

### Give us an example of what this icon might look like.

![fingerbot](https://github.com/Templarian/MaterialDesign/assets/31155587/84fba45d-e55e-4498-acee-04a3616a12be)

**Comment by mririgoyen** [comment]
We don't add device specific icons or brand icons to the Material Design Icons library.
