### ISSUE TITLE
Meshtastic

### ISSUE THREAD

**Issue by djvdberg** [Templarian/MaterialDesign#7375]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

I use various Meshtastic sensors in home assistant and would like to use these icons.

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/26028817/c15fb79f-1481-40aa-bfaa-878bacef82e0)

### Upload the icon source.

![Meshtastic](https://github.com/Templarian/MaterialDesign/assets/26028817/2fd7be96-ecbd-4f7f-84a7-53e07fcb1c1f)

**Comment by mririgoyen** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
