### ISSUE TITLE
google-tag-manager icon

### ISSUE THREAD

**Issue by digitalniweb** [Templarian/MaterialDesign#7381]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

There is no google-tag-manager icon yet and i need it.

### Share a preview of your contribution.

![canvas](https://github.com/Templarian/MaterialDesign/assets/84039023/206fb7d5-2619-4b96-9807-a320907d59f0)

### Upload the icon source.

[google-tag-manager.zip](https://github.com/Templarian/MaterialDesign/files/14319911/google-tag-manager.zip)

**Comment by PeterShaggyNoble** [comment]
### [**We're no longer accepting new brand icons into MDI.**][1]

We recommend checking out [SimpleIcons][2]. SimpleIcons is a library specific to brand and product icons like the one suggested above. If they do not currently have your requested icon, [you can request it on their GitHub page][3].

Thank you for your suggestion.

[1]: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/
[2]: https://simpleicons.org/
[3]: https://github.com/simple-icons/simple-icons/issues
