### ISSUE TITLE
window-shutter icons missing

### ISSUE THREAD

**Issue by schneich** [Templarian/MaterialDesign#7382]
### What is your question?

Hi,

I am using a lot of your icons in HomeAssistant. Your library is great. Thank you very much!

After the latest update of HomeAssistant, some of my window-shutter-icons are gone. I checked your library online and I could not find them anymore. Have they been removed?!

I had icons for window-shutters _open 33%_, _open 50%_, _open 66%_ and _fully open_. The icon for _fully closed_ is still there.

Is there a chance to get those icons back?

Thank you very much and best regards,
Chris

![grafik](https://github.com/Templarian/MaterialDesign/assets/84641760/b9838792-4718-406f-add8-65d44105386c)

**Comment by mririgoyen** [comment]
We have never offered these icons. You likely were/are using a custom icon package. We have repeatedly rejected requests (https://github.com/Templarian/MaterialDesign/issues/5733, https://github.com/Templarian/MaterialDesign/issues/5872, https://github.com/Templarian/MaterialDesign/issues/6277, https://github.com/Templarian/MaterialDesign/issues/6740, https://github.com/Templarian/MaterialDesign/issues/6754, https://github.com/Templarian/MaterialDesign/issues/7129, https://github.com/Templarian/MaterialDesign/issues/7152, https://github.com/Templarian/MaterialDesign/issues/7178) to add intermediate states of these icons.
