### ISSUE TITLE
car-trunk-open

### ISSUE THREAD

**Issue by SaveFerrisVote4Pedro** [Templarian/MaterialDesign#7383]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

To show the truck / boot / hatchback open - there is no suitable alternative at the moment that shows a trunk that is open. 

This would be very useful for automations to open trunks

### Share a preview of your contribution.

![car-trunk-open-final](https://github.com/Templarian/MaterialDesign/assets/155284855/f60fd752-2cb8-457a-932f-a85f673887c1)

### Upload the icon source.

[car-trunk-open-final.zip](https://github.com/Templarian/MaterialDesign/files/14354370/car-trunk-open-final.zip)

**Comment by SaveFerrisVote4Pedro** [comment]
![car-trunk-open-final](https://github.com/Templarian/MaterialDesign/assets/155284855/f0fe856b-83c7-4a5e-aaea-23da9a34ba8e)

**Comment by Templarian** [comment]
Added. Modified a little different to keep the general look closer to MD guidelines. `car-trunk`.
