### ISSUE TITLE
Wishlist: "proportional" variant of the icon font

### ISSUE THREAD

**Issue by callegar** [Templarian/MaterialDesign#7384]
### What is your question?

Currently, the Material Design Icons fonts appears to be a "monospaced" font, where all the glyphs have the same size and fit in the same "box". Even if the icon appears to be centered in the box in the pictogram browser (e.g., https://pictogrammers.com/library/mdi/icon/cellphone-basic/), when you use the font in applications like libreoffice, the icons end up being left-aligned in their box. This seems to be in contrast with other popular icon fonts (e.g. fontawesome) where the font is "proportional" so that each glyph has a width corresponding to its actual content.
This makes it difficult to use the material design icon font a direct replacement for other icon fonts.
I wonder if it would be hard to build a "proportional" version of the material design icon font.

**Comment by mririgoyen** [comment]
This is not something we are interesting in supporting.
