### ISSUE TITLE
domain-arrow-right

### ISSUE THREAD

**Issue by tijn** [Templarian/MaterialDesign#7397]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

We're using account-arrow-right in our app to indicate a transfer of people (trainees getting another mentor). We also have a need to transfer businesses (to new account managers).

I simply removed the plus-sign from domain-plus and then I pasted the arrow from account-arrow-right in its place using Inkscape. I am not 100% sure about the alignment. It looks okay to my eyes though.

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/18674/c9f0cb6e-5856-4d83-b534-2d867d707efe)

### Upload the icon source.

[domain-arrow-right.svg.zip](https://github.com/Templarian/MaterialDesign/files/14512116/domain-arrow-right.svg.zip)

**Comment by Templarian** [comment]
Added.

**Comment by tijn** [comment]
Hello @Templarian , I just found out that this icon is not included in the icon set. That is, I cannot see it [here](https://pictogrammers.com/library/mdi/?q=domain), nor is it visible in the commits in this repository.

It is however visible on the [history page](https://pictogrammers.com/library/mdi/history/) under **Changes on March 31st, 2024**

I assume something must have gone wrong in one of those sync commits, but it's hard to found out which one. But I guess that's besides the point; I think it simply should be added again. Could you do that? Or is there something that I can do?
