### ISSUE TITLE
Cinema stuff

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#74]
- Popcorn bucket
- Cinema ticket
- Cinema icon (maybe a building with lettering)
- Users tickets (similar account-check)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/popcorn
(I don't know what to make for this one)
http://materialdesignicons.com/icon/theater
http://materialdesignicons.com/icon/ticket-account

I'll reopen if you provide some more info on what cinema icon should be.

**Comment by matthew2402** [comment]
All icons are great!
For the cinema icon something like http://materialdesignicons.com/icon/hospital-building. Just with a 'cinema' lettering.

**Comment by Templarian** [comment]
I'm redoing the popcorn icon, got some feedback from the other contributors for that one. Many thought it looked like a face.

Cinema in text in the icon is too specific for the size. I'll think of something.

**Comment by REJack** [comment]
a projector wall as cinema icon would be nice too ^^

**Comment by Templarian** [comment]
I tried to make a variant to the theater icon, due to the size nothing is looking right or readable.

I would suggest using the film strip, ticket, or the theater icon for a cinema.
