### ISSUE TITLE
Clear All notification Icon

### ISSUE THREAD

**Issue by philippeBchn** [Templarian/MaterialDesign#740]
Google clear all icon is pretty usefull.

https://www.google.com/design/icons/#ic_clear_all 
![ic_clear_all_black_24dp](https://cloud.githubusercontent.com/assets/6814372/10363308/19aec99c-6db4-11e5-8aab-65ea42703570.png)

**Comment by CoDEmanX** [comment]
Closing this as duplicate of #420
