### ISSUE TITLE
Rocket-Launch icon with spurious path

### ISSUE THREAD

**Issue by Finii** [Templarian/MaterialDesign#7401]
### Where are you experiencing this bug?

A specific icon glyph

### What is the issue you are experiencing?

The icons
* **`rocket-launch.svg`**
* **`rocket-launch-outline.svg`**

have a two-point path that is most certainly a leftover and with it's zero width should be removed.

Here the icon without fill:

![image](https://github.com/Templarian/MaterialDesign/assets/16012374/89ef2d60-fd82-4560-9640-5ed2072f07cd)

zoomed in, the marked points are not on the main outline:

![image](https://github.com/Templarian/MaterialDesign/assets/16012374/85b837c4-a5b3-4670-bbbb-87574f1b010c)

moved the points a bit down-left to make it more obvious. This is not even a closed path? :thinking: 

![image](https://github.com/Templarian/MaterialDesign/assets/16012374/42e4d99a-d5f1-4e2a-baba-bff01e2492d6)

Icon has been introduced in
* #5152

**Comment by Templarian** [comment]
Fixed both. Thanks for filing this bug.
