### ISSUE TITLE
Cartão de crédito

### ISSUE THREAD

**Issue by hsbtenorius** [Templarian/MaterialDesign#7403]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Para minha conciliação TEF (Pagamentos de cartão).

### Give us an example of what this icon might look like.

exatamente como este: https://fontawesome.com/v6/icons/credit-card?f=classic&s=solid

**Comment by Simran-B** [comment]
There are various credit card icons using a base shape by Google, following the Material Design guidelines. We won't add a slightly different variant, in particular not from other icon sets that don't follow the same specifications.

![image](https://github.com/Templarian/MaterialDesign/assets/7819991/c3589005-48e8-4e0c-bccd-a58536ac2d2a)
