### ISSUE TITLE
Street View Pegman Icon

### ISSUE THREAD

**Issue by jicecold** [Templarian/MaterialDesign#741]

**Comment by CoDEmanX** [comment]
Based on the latest app logo:
![Imgur](http://i.imgur.com/8li6q1t.png?1)

... it appears to be of this shape:
![Imgur](http://i.imgur.com/AmeBBNn.png)

**Comment by CoDEmanX** [comment]
Man in a suite:
![human-suite](https://cloud.githubusercontent.com/assets/1309249/10388183/0a466168-6e68-11e5-8198-0900f5f40c51.png)

Streetview?! It's actually really tough without adding perspective...
![streetview](https://cloud.githubusercontent.com/assets/1309249/10388185/0c1e45c8-6e68-11e5-804e-15f6a9750360.png)

**Comment by Templarian** [comment]
I like the 1st one. 2nd not so much. 3rd one looks like a heart with a dot.

**Comment by CoDEmanX** [comment]
Google released a streetview icon: https://design.google.com/icons/#ic_streetview

**Comment by Templarian** [comment]
That is a weird icon... not sure I'm going to add this one as it is very specific.

**Comment by snuuve** [comment]
Are you planning to add this icon ? :)

**Comment by PeterShaggyNoble** [comment]
Found this one on Google Earth the other day.

[street-view.zip](https://github.com/Templarian/MaterialDesign/files/1467270/street-view.zip)

**Comment by GreenTurtwig** [comment]
And here's a preview:
[![image](https://user-images.githubusercontent.com/15905797/38928436-c1945860-4300-11e8-9e8c-8fabdf8c54f8.png)](https://github.com/Templarian/MaterialDesign/files/1923690/google-street-view.zip)

**Comment by Templarian** [comment]
[![google-street-view](https://materialdesignicons.com/icon/google-street-view)](https://materialdesignicons.com/icon/google-street-view)

**Comment by simon-ocsi** [comment]
> This icon has been deprecated and will be removed in an upcoming release. New use of this icon is highly discouraged. If you are currently using this icon, please make plans to replace it before upgrading to a newer version of the library.

Is there a close alternative that can be safely used? 

![image](https://github.com/user-attachments/assets/848da61d-72d7-4257-b63e-990a7c511109)
