### ISSUE TITLE
Only 1 icon about "Android" logo, and main draw area focus on top part

### ISSUE THREAD

**Issue by boybeak** [Templarian/MaterialDesign#7410]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

Use the icon to display different type and operate systems

### Give us an example of what this icon might look like.

the old logo for android is good enough:https://miro.medium.com/v2/resize:fit:720/format:webp/1*6B0hnPejERl2D768U4vb1w.jpeg

**Comment by Templarian** [comment]
We're removing all brands / logos. See: #6602
