### ISSUE TITLE
account-voice-outline

### ISSUE THREAD

**Issue by frankgrinaert** [Templarian/MaterialDesign#7414]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

outline versions of [account-voice](https://pictogrammers.com/library/mdi/icon/account-voice/) and [account-voice-off](https://pictogrammers.com/library/mdi/icon/account-voice-off/)

I've included 2 variations for the "off" variant, where the "off" line is offset by 1px.

### Share a preview of your contribution.

![image](https://github.com/Templarian/MaterialDesign/assets/55925048/309bda97-f67d-4343-857e-afc2ef15a1c8)
![image](https://github.com/Templarian/MaterialDesign/assets/55925048/91d1dffa-7281-4743-8dc9-58b419bcce95)
![image](https://github.com/Templarian/MaterialDesign/assets/55925048/5649b6cf-597c-4243-b721-702fb1373092)

### Upload the icon source.

[account-voice-outline.zip](https://github.com/Templarian/MaterialDesign/files/14815894/account-voice-outline.zip)

**Comment by Templarian** [comment]
Added both. I went with the first `off` to be consistent, but either would have probably worked.
