### ISSUE TITLE
calendar-remove-multiple

### ISSUE THREAD

**Issue by a-leithner** [Templarian/MaterialDesign#7415]
### Before submitting a new icon contribution, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I have followed the [Material guidelines](https://material.io/design/iconography/system-icons.html) for system icons.

### Tell us about your contribution.

Analogous to `calendar-multiple-check` I needed an icon for cancelling multiple events at once and have arrived at this proposed design, by grabbing the stroke width of the checkmark in `calendar-multiple-check` and centering it inside the calendar sheet of `calendar-blank-multiple`. It could be used to depict cancelling/removing multiple events at once or removing multiple calendar accounts at once.

I'm unsure about the name though, as `calendar-multiple-check` has a different order of name parts than `calendar-blank-multiple`.

### Share a preview of your contribution.

![`calendar-remove-multiple` preview](https://github.com/Templarian/MaterialDesign/assets/16526917/b50bf842-053b-4e0b-98e1-9ee3cbbb201c)

### Upload the icon source.

[calendar-remove-multiple.zip](https://github.com/Templarian/MaterialDesign/files/14816457/calendar-remove-multiple.zip)

**Comment by Templarian** [comment]
Need to open a bug for `calendar-multiple-check` being named wrong. 🤦 

Added the icon. Thanks!

**Comment by a-leithner** [comment]
@Templarian, while looking for the icon in the library, I couldn't help to notice that there's no attribution for the icon on the [history page](https://pictogrammers.com/library/mdi/history/):
![image](https://github.com/Templarian/MaterialDesign/assets/16526917/d2369767-72a7-481d-b593-84e32fdc03e7)

Would it be possible to change that?
