### ISSUE TITLE
X Icon (New Twitter)

### ISSUE THREAD

**Issue by jmartindg** [Templarian/MaterialDesign#7422]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

For a project that needs the latest icons for social media

### Give us an example of what this icon might look like.

![image](https://github.com/Templarian/MaterialDesign/assets/77723907/4f613d50-ca2e-4c26-acdc-7968a341239b)

**Comment by DrakoniusRex** [comment]
Has this been added yet? Do we need to use Material UI icons instead? As of 12 OCT 2024, I cannot find the X.com icon in MDI.

**Comment by Templarian** [comment]
@DrakoniusRex For legal reasons we've stopped adding any brand logos. Simple Icons and other packs handle this better.
