### ISSUE TITLE
Dial pad icon

### ISSUE THREAD

**Issue by Bramengton** [Templarian/MaterialDesign#744]
I searched dialpad icon but found nothing.
How about adding something like this:
![1102901](https://cloud.githubusercontent.com/assets/10059205/10418388/15706f60-7062-11e5-8195-d6588055220d.gif)
in a circle:
![basic-icon-dialpad](https://cloud.githubusercontent.com/assets/10059205/10418415/e1848316-7062-11e5-9fc8-60cc5c8bf5aa.png)

thank..

**Comment by CoDEmanX** [comment]
https://www.google.com/design/icons/#ic_dialpad is yet to be added, see #420
