### ISSUE TITLE
What is the current status of the project?

### ISSUE THREAD

**Issue by PavelTurk** [Templarian/MaterialDesign#7446]
Hello everyone. I noticed that only 15 icons have been added in 2024. Does this mean that the active development phase of the project is behind us? At the same time, there are 690 open issues. Could someone clarify the situation?

**Comment by mririgoyen** [comment]
We are all volunteers and life and work come before hobbies. This project, nor any of the other Pictogrammers projects, are dead. We are all just busy.

Most of the open requests are just that, requests. We tend to still handle and close contributions that others create, so long as they follow all the Material guidelines and are appropriate for the library.
