### ISSUE TITLE
Add go to line icon

### ISSUE THREAD

**Issue by PavelTurk** [Templarian/MaterialDesign#7447]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I need this icon for editor, where user can navigate to necessary line using go to line dialog.

### Give us an example of what this icon might look like.

This is an example from https://download.mikroe.com/documents/compilers/mikroc/pic/help/edit.htm :

![Screenshot from 2024-05-12 19-32-40](https://github.com/Templarian/MaterialDesign/assets/10261361/23390455-28cb-4764-80f8-5ab92a837a1e)

**Comment by andrejsharapov** [comment]
You can use [file-document-arrow-right](https://pictogrammers.com/library/mdi/icon/file-document-arrow-right/) if you need the file with arrow

**Comment by andrejsharapov** [comment]
> @andrejsharapov I think the icon you suggested is a good variant. Thank you very much. Should I close this issue?

If the problem is solved, then yes.
