### ISSUE TITLE
New releases icon

### ISSUE THREAD

**Issue by sunshinetpu** [Templarian/MaterialDesign#745]
Please create the "new releases" icon.

**Comment by Templarian** [comment]
Do you have an example?

**Comment by fabreax** [comment]
Something to see the latest icons added (or a newsletter !)

**Comment by CoDEmanX** [comment]
A bullhorn?

**Comment by PeterShaggyNoble** [comment]
[`new-box`](https://materialdesignicons.com/icon/new-box) can be used to highlight new releases and, recently, I've noticed [`alert-decagram`](https://materialdesignicons.com/icon/alert-decagram) being used too.

For a newsletter, you could try the [`newspaper`](https://materialdesignicons.com/icon/newspaper) icon.
