### ISSUE TITLE
European window icon for Home Assistant

### ISSUE THREAD

**Issue by Nordlicht-13** [Templarian/MaterialDesign#7466]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

I would like to have a European window icon for an open and closed window,
that I want to use for my Home Assistant.
Something like the attached open window icon.

### Give us an example of what this icon might look like.

![window_open](https://github.com/Templarian/MaterialDesign/assets/4716828/b96cf459-8c7e-4d0d-aa46-d40afb7b5a83)

**Comment by mririgoyen** [comment]
We cannot add icons the show perspective. This has been suggested and requested multiple times in the past. I'm sorry we are unable to fulfill this request in this library.

Related: https://github.com/Templarian/MaterialDesign/issues/7064
