### ISSUE TITLE
Location "Enter" and "Exit" icon

### ISSUE THREAD

**Issue by chrisonline** [Templarian/MaterialDesign#747]
I need a location "enter" and "exit" icon for geolocation.

Something like a circle with an arrow in and one with an arrow out.

For example:
![ic_action_arriving_holo_light](https://cloud.githubusercontent.com/assets/2077218/10450154/b7583bf0-7198-11e5-9559-9f35f123c0e6.png)

**Comment by CoDEmanX** [comment]
Not a circle, but a rounded square:
https://materialdesignicons.com/icon/import
https://materialdesignicons.com/icon/export

**Comment by chrisonline** [comment]
Yeah I know this icons, but a location is always a circle and not a square.
So it is a lot better with a circle I think.

**Comment by chrisonline** [comment]
Any news about this?
Can anybody make such an icon see my first entry. For "enter" arrow right in and for "exit" arrow left out.

**Comment by MrGrigri** [comment]
I quickly put these together. @chrisonline what do you think?

![location-enter](https://cloud.githubusercontent.com/assets/4528551/24617558/780e9a00-1851-11e7-8aee-bcbcf895c832.png) ![location-exit](https://cloud.githubusercontent.com/assets/4528551/24617566/7be38df2-1851-11e7-8d81-093d55d9c595.png)

**Comment by chrisonline** [comment]
@MrGrigri Great, thanks! Looks very good.
Can you add this ?

**Comment by MrGrigri** [comment]
@chrisonline I do not wield said power. I am but only an icon contributor. @Templarian will have to add it, and since he added the `Contribution` label, I'm sure it'll get done.

**Comment by goyney** [comment]
Removing Contribution label since no source SVG was provided.

**Comment by PeterShaggyNoble** [comment]
Would the `login` & `logout` icons or their variants not fulfil this request?

**Comment by goyney** [comment]
[![location-enter](https://materialdesignicons.com/icon/location-enter)](https://materialdesignicons.com/icon/location-enter)[![location-exit](https://materialdesignicons.com/icon/location-exit)](https://materialdesignicons.com/icon/location-exit)
