### ISSUE TITLE
printer-pos

### ISSUE THREAD

**Issue by fredericoregateiro** [Templarian/MaterialDesign#748]
Hello,
Could a icon for pos printers be made?
like the image attached?
Or something indicating a printer that use roll paper.

![pos_tm-t20ii-pos-receipt-printer-3_690x460](https://cloud.githubusercontent.com/assets/6304701/10462048/6469fc44-71d4-11e5-81f2-533996b07487.jpg)

**Comment by Sithdown** [comment]
Something like this?

![printer-pos](https://cloud.githubusercontent.com/assets/430612/10486139/d1954814-728d-11e5-96c4-00afe1eb96e1.png)

**Comment by fredericoregateiro** [comment]
This looks more like a regular inkjet printer.
The icon i'm describing is to differentiate a normal printer of a roll paper printer.

**Comment by Sithdown** [comment]
Sorry, I mistook a continuous form paper printer 
![image](https://cloud.githubusercontent.com/assets/430612/10493032/3132eaa8-72af-11e5-93a3-e238ce893825.png)
with a roll paper printer.

**Comment by MrGrigri** [comment]
Here is my attempt...this might be a bit to niche. 

[![printer-pos](https://user-images.githubusercontent.com/4528551/52226512-6c4ada00-286a-11e9-8f91-6cebcbf1ec8c.png)](https://github.com/Templarian/MaterialDesign/files/2829195/printer-pos.zip)

**Comment by goyney** [comment]
[![printer-pos](https://materialdesignicons.com/icon/printer-pos)](https://materialdesignicons.com/icon/printer-pos)
