### ISSUE TITLE
view-grid icon not in repository

### ISSUE THREAD

**Issue by Frank3K** [Templarian/MaterialDesign#749]
The [view-grid](https://materialdesignicons.com/icon/view-grid) icon is not included in the Git repository, but it is available on the website.

**Comment by Templarian** [comment]
Yea, I don't sync all of the contributor icons back into the repository. Can you just use the SVG from the site?

**Comment by Frank3K** [comment]
Aha I see. I'm currently using this repository as a git `submodule` in my own repository for easy access to the icons.

**Comment by Templarian** [comment]
Those files should not be used in production. All the SVG files in the repo are straight exports from various editors without any optimizations steps ran on them.

I suggest right clicking the icons you need on the site and selecting "Download SVG" option to get the optimal SVG files.
