### ISSUE TITLE
Eyedropper icon

### ISSUE THREAD

**Issue by ZMYaro** [Templarian/MaterialDesign#75]
Has anyone seen a Material-style eyedropper icon?  I can try my hand at designing one, but I thought I would ask.

**Comment by zmyaro** [comment]
I stumbled upon [this icon](https://github.com/google/material-design-icons/blob/master/image/svg/design/ic_colorize_24px.svg) while poking through Google's Material Design Icons repo.  Its official label is “colorize”, but it looks as though it is also meant to be an eyedropper.  It may be worth adding to materialdesignicons.com as well.

**Comment by Templarian** [comment]
It's already there. http://materialdesignicons.com/icon/eyedropper-variant

**Comment by zmyaro** [comment]
Ah, it seems I made the same mistake twice and searched materialdesignicons.com for “colorize”.  My apologies.

**Comment by Templarian** [comment]
I didn't name it colorize. Because I've been trying to keep the icon names obvious for users (a lot of the naming Google used is kind of confusing).

I am adding a feature called alias soon though. If a user searches for an icon it will still match if it finds an alias.

**Comment by zmyaro** [comment]
I completely understand.  I apologize again for the bother.

**Comment by Templarian** [comment]
Ha. It's open source the more you bother me the better the project gets. Keep the suggestions and feedback coming.

I made Issue #90 to track the progress.
