### ISSUE TITLE
football-variant

### ISSUE THREAD

**Issue by GRA0007** [Templarian/MaterialDesign#750]
A football-variant that has rounded corners and a smaller lace bit thing, so it resembles an Australian football.
Like this:
![image](https://cloud.githubusercontent.com/assets/8862273/10477912/a9709c18-72a5-11e5-883d-726df4c95fc9.png)

**Comment by Templarian** [comment]
[![football-australian](https://materialdesignicons.com/icon/football-australian)](https://materialdesignicons.com/icon/football-australian)
