### ISSUE TITLE
Stairs icon

### ISSUE THREAD

**Issue by eNepper** [Templarian/MaterialDesign#751]
I'll like to request a stairs icon, simular to http://www.clipartsfree.net/svg/15761-aiga-stairs-download.svg

**Comment by CoDEmanX** [comment]
Nothing fancy:
![stairs](https://cloud.githubusercontent.com/assets/1309249/10491955/9a7474ba-72a9-11e5-8d36-d94f051bc170.png) https://www.dropbox.com/s/vpojwp4rl9dbotr/stairs.svg?dl=0

**Comment by eNepper** [comment]
It's just what I have been looking for! Thanks

**Comment by CoDEmanX** [comment]
@Templarian: can you add it?

BTW. How about to change label "Contributor" to "Contribution"?

**Comment by Templarian** [comment]
[![stairs](https://materialdesignicons.com/icon/stairs)](https://materialdesignicons.com/icon/stairs)
