### ISSUE TITLE
footsteps

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#755]
![Example](https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Footsteps_icon.svg/1024px-Footsteps_icon.svg.png)
Thanks!

**Comment by CoDEmanX** [comment]
I could swear this has been requested before, but it didn't seem so... Very valid request. Could be used for the debug level request "trace".

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/50928741-74f5ef00-1429-11e9-9da2-5faff908afb5.png)

[footprints.zip](https://github.com/Templarian/MaterialDesign/files/2742632/footprints.zip)

**Comment by goyney** [comment]
Added.

[![shoe-print](https://materialdesignicons.com/icon/shoe-print)](https://materialdesignicons.com/icon/shoe-print)
