### ISSUE TITLE
Twitter - X

### ISSUE THREAD

**Issue by JohnnyFerreiraOfc** [Templarian/MaterialDesign#7554]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

To add to my website, since I'm using vue and importing the icons directly from this library.

### Give us an example of what this icon might look like.

![x](https://github.com/user-attachments/assets/0af74b2a-d061-4a93-94f0-5e8d98cd30cf)

**Comment by steodor** [comment]
This would be a brand icon: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/

**Comment by Templarian** [comment]
@vd3d https://github.com/Templarian/MaterialDesign/issues/6602
