### ISSUE TITLE
Echo Dot and Fire TV icon

### ISSUE THREAD

**Issue by Frazou1** [Templarian/MaterialDesign#7555]
### Before submitting a new icon request, please confirm the following:

- [X] I have [searched all issues](https://github.com/Templarian/MaterialDesign/issues?q=is%3Aissue) to make sure there isn't a request for this icon.
- [X] I have [searched the current library](https://pictogrammers.com/library/mdi) to make sure the icon doesn't already exist.
- [X] I understand that [brand icons are no longer being added](https://pictogrammers.com/docs/library/mdi/guides/brand-icons/) and I can use [SimpleIcons](https://simpleicons.org/) for my brand icon needs.
- [X] I only intend to request a single icon (or a few near-identical ones) in this issue.

### What would you use this icon for?

In home assistant

### Give us an example of what this icon might look like.

![amazon-firetv-icon-1024x549-4v3aja4f](https://github.com/user-attachments/assets/2d4e6ac3-bb65-44fe-a21e-6a722f8547d9)
![1599186](https://github.com/user-attachments/assets/6475504d-f433-42cd-9c41-90fa1574e918)

**Comment by steodor** [comment]
This would be a brand icon: https://pictogrammers.com/docs/library/mdi/guides/brand-icons/

**Comment by Frazou1** [comment]
awesome. Thanks !
