### ISSUE TITLE
A 'pizza-variant' icon

### ISSUE THREAD

**Issue by GRA0007** [Templarian/MaterialDesign#756]
A variant to the pizza icon by Google that maybe looks a bit more like, well, like a pizza :expressionless:

**Comment by CoDEmanX** [comment]
Hardly possible in 20 square pixels, but I agree that Google's pizza icon isn't that great.

**Comment by GRA0007** [comment]
It doesn't need to be super-detailed, in fact one more dot would probably look more like a pizza :stuck_out_tongue_winking_eye:

**Comment by PeterShaggyNoble** [comment]
Going to close this out as it seems very specific.
