### ISSUE TITLE
Weight Lifter

### ISSUE THREAD

**Issue by JakubSteplowski** [Templarian/MaterialDesign#759]
Hi!
Can you add icons with weights, gym, person that raise weigths, etc ?

https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQYz14m-pYku6rt27LXNjMCLSojd8e1yw03OQzHdJfDOW_hxTNN

Thanks! :D

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/dumbbell ?

also...
https://materialdesignicons.com/icon/weight
https://materialdesignicons.com/icon/weight-kilogram

**Comment by JakubSteplowski** [comment]
Oh, Thanks, I didn't see that.
However, it will be cool if you create an icon with a person that raise weigths. :)

**Comment by goyney** [comment]
This is the raw extracted icon from Google Fit.

**_It IS NOT ready for inclusion in the library and needs to be Materialized first._**

![image](https://user-images.githubusercontent.com/1015040/50925876-9a7efa80-1421-11e9-9b3b-3ede886d2021.png)

[ic_crossfit_white_fill.svg.zip](https://github.com/Templarian/MaterialDesign/files/2742468/ic_crossfit_white_fill.svg.zip)

**Comment by goyney** [comment]
Here's my version of it:

![image](https://user-images.githubusercontent.com/1015040/62842903-b5e60880-bc83-11e9-830d-e49c1ea11c5d.png)
[crossfit.svg.zip](https://github.com/Templarian/MaterialDesign/files/3490856/crossfit.svg.zip)

Removing the `Google` label since whatever we come up with will be a new creation.

**Comment by JamesCoyle** [comment]
I feel like `weightlifter` would be a better name and then alias crossfit.

**Comment by goyney** [comment]
[![weight-lifter](https://materialdesignicons.com/icon/weight-lifter)](https://materialdesignicons.com/icon/weight-lifter)
