### ISSUE TITLE
Windows Phone 8.1 - Icons not visible (Cordova)

### ISSUE THREAD

**Issue by graphefruit** [Templarian/MaterialDesign#760]
Hello MDI-Team,

I tried to use the MDI-Icons in Windows Phone 8.1 and it didn't work.
After some research I found the two issues:

### CSS
```css 
url("../fonts/materialdesignicons-webfont.ttf?v=1.2.64") format("truetype")
```
to:
```css 
url("../fonts/materialdesignicons-webfont.ttf") format("truetype")
```
[Reference](http://stackoverflow.com/questions/14558331/getting-a-web-font-to-work-on-an-html5-windows-phone-app/20573678#20573678)

### TTF
The legal-rights need to be changed from actual 5 to 0, otherwise its blocked.

[Reference](http://stackoverflow.com/questions/14558331/getting-a-web-font-to-work-on-an-html5-windows-phone-app/20573678#20573678)
(Same as above)

I tested it, and with this way it works.
Would be awesome if you could change this :)
Greetings

**Comment by Templarian** [comment]
I'm not going to be able to make the first change, this will be something developers may need to do manually.

I will look into the issue with the legal rights flag though for the TTF.

**Comment by graphefruit** [comment]
@Templarian thanks for your feedback and your effort.

So maybe its possible to write this as known "issue" into the readme-section or somewhere else.
Greetings

**Comment by Templarian** [comment]
https://github.com/Templarian/MaterialDesign/ Warning for cordova users.

Also: https://materialdesignicons.com/getting-started

**Comment by derwaldgeist** [comment]
Will this be fixed in the future to avoid manual patching?

**Comment by Templarian** [comment]
@derwaldgeist No idea. Please check the issue tracker for Cordova and see if they have plans to fix the bug, or submit a pull request to strip out the query strings to the Cordova WP project.

**Comment by graphefruit** [comment]
@Templarian I don't think this can be fixed by Cordova. The fix is needed on side of Microsoft, cause they provide the WebView in which the HTML is running, and in this WebView the restriction is done.

**Comment by AladdinElkehhat** [comment]
1637567161
