### ISSUE TITLE
Pram, handshake and tools icons request

### ISSUE THREAD

**Issue by Boglarka** [Templarian/MaterialDesign#762]
Dear MaterialDesignIcons Team,

could you please provide icons for pram, handshake and tools (like a hammer and a ruler in same icon)?

Thank you very much,
Boglarka

**Comment by CoDEmanX** [comment]
All 3 are essentially duplicates. I re-opened #732, which originally asked for a combination of two tools:

- Pram: #655 
- Handshake: #330 
- Tools: #732 / #574

**Comment by Boglarka** [comment]
I would like to see that icons in the font if it is possible.
