### ISSUE TITLE
Whiteboard / Chalkboard icon

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#763]
Would come in handy for desktop sharing / virtual classroom applications.

**Comment by CoDEmanX** [comment]
Maybe like this?
![screen](https://cdn3.iconfinder.com/data/icons/glypho-generic-icons/64/whiteboard-empty-outline-128.png)
Could also be used to symbolize an analog screen used for projectors.

**Comment by derwaldgeist** [comment]
That's very cool for SmartBoards.

But for a whiteboard, I would not expect a projector on top. A whiteboard would rather have a slot for pencils and an eraser on the bottom-left side, like in this photo: https://stocksnap.io/photo/16VYGB9PG5. And typically, a whiteboard does not have a stand.

**Comment by CoDEmanX** [comment]
I can't think of a way to depict a recognizable whiteboard. Board markers can't be much larger than a few pixels, and would thus be just plain lines I assume.

**Comment by JamesCoyle** [comment]
![image](https://user-images.githubusercontent.com/10384436/45600607-707b7580-b9f7-11e8-997e-b2675bb06bfc.png)

This is what Icons8 has. Could maybe base it along those lines.

**Comment by JamesCoyle** [comment]
[![](https://materialdesignicons.com/icon/teach
)](https://materialdesignicons.com/icon/teach)

**Comment by CoDEmanX** [comment]
The previews don't work on my end, this is all I see for above comment:

![grafik](https://user-images.githubusercontent.com/1309249/45949539-7deabe00-bffc-11e8-9901-bbd2a7d02c65.png)
