### ISSUE TITLE
Dashboard icon request

### ISSUE THREAD

**Issue by IlanF** [Templarian/MaterialDesign#764]
I could use a dashboard icon, but for the time being a cog icon (settings) works fine.
http://fortawesome.github.io/Font-Awesome/icon/tachometer/
https://developer.wordpress.org/resource/dashicons/#dashboard

**Comment by CoDEmanX** [comment]
There is https://materialdesignicons.com/icon/view-dashboard and a tachometer / gauge is being contributed in #769.

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/gauge
