### ISSUE TITLE
Send file icon "Icon Request" 

### ISSUE THREAD

**Issue by Alexey1377** [Templarian/MaterialDesign#766]
![untitled-1](https://cloud.githubusercontent.com/assets/13694759/10668811/9ef94932-78e6-11e5-8532-14efdd224cab.jpg)

**Comment by Alexey1377** [comment]
<?xml version="1.0" encoding="utf-8"?>

<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="24px" height="24px" viewBox="0 0 24 24" enable-background="new 0 0 24 24" xml:space="preserve">
<path d="M14,2H6C4.89,2,4,2.89,4,4v16c0,1.1,0.9,2,2,2h12c1.1,0,2-0.9,2-2V8L14,2z M12.54,19.37v-2h-4v-1.99h4v-2l3,3L12.54,19.37z
	 M13,9V3.5L18.5,9H13z"/>
</svg>

**Comment by Alexey1377** [comment]
I already made it

**Comment by CoDEmanX** [comment]
If you really want to post the SVG source code, use code fencing:

    ```
    Code goes here
    ```

It's better to use Dropbox or Google Drive however and just post a link to the file here.

**Comment by Templarian** [comment]
[![file-send](https://materialdesignicons.com/icon/file-send)](https://materialdesignicons.com/icon/file-send)
