### ISSUE TITLE
Some Homeautomation Icons would be nice

### ISSUE THREAD

**Issue by panzaeron** [Templarian/MaterialDesign#767]
Something like:
- [ ] `window-open`
- [ ] `window-close`
- [ ] `window-tilt`
- [ ] `window-shutter-down`
- [ ] `window-shutter-up`
- [ ] `window-shutter-shading`
- [ ] `lightbulb-rgb` (text RGB on lightbulb icon)

**Comment by Templarian** [comment]
Updated the issue with tasks.

**Comment by Templarian** [comment]
Closing this issue as most exist now or have individual issues tracking them. #2766

Trying to keep it ~one icon per issue.
