### ISSUE TITLE
I have some icons to add to the repo. How should I add them since the contributor form is disabled?

### ISSUE THREAD

**Issue by HLVTN** [Templarian/MaterialDesign#769]
![ref](https://cloud.githubusercontent.com/assets/1309249/10836951/48cb4230-7eb4-11e5-8831-3217ecb33fcf.PNG)
https://drive.google.com/file/d/0BxgdaP83FpHgc2dKSUk0SkxENTQ/view?usp=sharing

**Comment by Templarian** [comment]
Zip them and put them somewhere and link it here. Make sure all the SVG files render fine in https://materialdesignicons.com/custom (this doesn't work in Firefox yet).

**Comment by HLVTN** [comment]
[You can download them here.](https://drive.google.com/file/d/0BxgdaP83FpHgc2dKSUk0SkxENTQ/view?usp=sharing)

A note about *ic_gauge*: This one's taken from the Material Design docs ([fifth row, second icon](https://www.google.com/design/icons/static/images/tile-iconfont.svg)), but for whatever reason hasn't been included in the publicly available icons. It should probably be credited to Google instead of me.

**Comment by CoDEmanX** [comment]
We already have a road and a dollar icon:
https://materialdesignicons.com/icon/currency-usd
https://materialdesignicons.com/icon/road

A check sign in a circle is also there, but it's different from yours:
https://materialdesignicons.com/icon/checkbox-marked-circle-outline

Could you provide a dashed version of that stock icon?

The steering and the gauge icons would be great additions! The other ones might be a bit too specific, but will leave that up to @Templarian.

**Comment by CoDEmanX** [comment]
I can't find the bottom left icon: https://www.google.com/design/icons/static/images/tile-iconfont.svg
Is it supposed to represent [letterbox format](https://en.wikipedia.org/wiki/Letterboxing_(filming))?

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/coin exists

[![gauge](https://materialdesignicons.com/icon/gauge)](https://materialdesignicons.com/icon/gauge) [![format-list-bulleted-type](https://materialdesignicons.com/icon/format-list-bulleted-type)](https://materialdesignicons.com/icon/format-list-bulleted-type) [![credit-card-scan](https://materialdesignicons.com/icon/credit-card-scan)](https://materialdesignicons.com/icon/credit-card-scan)

I've added 2 of your icons. If you get 3 more you into the system you'll be a contributor (and I'll transfer the icons over to your account). The rest were too specific. The flag looks more like text next to an image.

`card-add` goes against their guidelines, the plus would have to be separate from the base icon.

**Comment by Templarian** [comment]
@CoDEmanX No idea about that image looking icon, but it may have been deprecated. Can't really tell what it is out of context.

**Comment by Templarian** [comment]
[![road-variant](https://materialdesignicons.com/icon/road-variant)](https://materialdesignicons.com/icon/road-variant)

**Comment by CoDEmanX** [comment]
What about the letterbox-y icon?
![letterbox](https://cloud.githubusercontent.com/assets/1309249/10837202/ee65b872-7eb6-11e5-95c1-0267ab67b8d2.png) https://www.dropbox.com/s/ruf66ybebiy7zfi/letterbox.svg?dl=0

**Comment by Templarian** [comment]
Now in ultra wide cinematic for your viewing pleasure. Yea, agreed, lets just make it Polaroid.

[![polaroid](https://materialdesignicons.com/icon/polaroid)](https://materialdesignicons.com/icon/polaroid)

**Comment by CoDEmanX** [comment]
The white counter-space should actually be a square for a Polaroid:
http://pixel.brit.co/wp-content/uploads/2013/11/Polaroids-3-Hang.jpg

**Comment by Templarian** [comment]
Fixed (image above is cached by github).

**Comment by HLVTN** [comment]
@CoDEmanX From looking at Google's icons, I do think there's room for alternates. (Consider Do Not Disturb [version 1](https://www.google.com/design/icons/#ic_do_not_disturb) and [version 2](https://www.google.com/design/icons/#ic_do_not_disturb_alt).) I was aware that the dollar sign existed; however, [Google's version](https://www.google.com/design/icons/#ic_attach_money) seems inconsistent with their [other use of the dollar sign](https://www.google.com/design/icons/#ic_local_atm).

I didn't see your road icon. I think the one I designed reads a little more as a road, but it also introduces perspective—which, debatably, conflicts with the MD guidelines. Have you considered rounding the corners on your variation?

<hr>

@Templarian In regards to `card_add`, would you mind linking me to the documentation on that? It seems there are numerous icons that indicate otherwise. ([Example 1](https://www.google.com/design/icons/#ic_playlist_add), [example 2](https://www.google.com/design/icons/#ic_signal_wifi_4_bar_lock), [example 3](https://www.google.com/design/icons/#ic_network_locked))

For what it's worth, I don't think the American flag by itself offers much—but as a potential series of country flags, it would be useful.

Last thing: How open are you to improving some of the icons? For instance, I recently designed a motorcycle icon, but there's already one available in materialdesignicons.com. This is subjective, but I think mine registers more as a motorcycle. Is stuff like this worth submitting?

<img width="244" alt="screen shot 2015-10-30 at 9 49 15 am" src="https://cloud.githubusercontent.com/assets/1717867/10848061/6e84d09a-7ef0-11e5-8d4b-5e24cf5a100d.png">

**Comment by CoDEmanX** [comment]
@Templarian: That letterbox icon is actually in the repo, but not on MDI site:
https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/image.svg

**Comment by Templarian** [comment]
I know, I saw it yesterday, I find it a rather ugly icon. I guess I can adding it as "letterbox" though. I just don't like it as an "image".

**Comment by Templarian** [comment]
@HLVTN We're very open to modifying the icons with different versions or replacing them. That's what this project is all about.

I like the icon for a motor cycle, but I also like the original. I think I'm going to setup a way to vote via the new twitter polling system. Kind of a one icon vs the other sort of deal and let people decide.

I'll try this idea out this weekend designing a mockup.

**Comment by CoDEmanX** [comment]
Oh, there is it (the letterbox icon):
https://materialdesignicons.com/icon/file-presentation-box
