### ISSUE TITLE
Number Icons 0-9

### ISSUE THREAD

**Issue by OnePersonCo** [Templarian/MaterialDesign#77]
Numbers 0-9 in the form of icons. I'd assume that these would use a specific font, most likely some form of Roboto.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/numeric-0-box
http://materialdesignicons.com/icon/numeric-1-box
http://materialdesignicons.com/icon/numeric-2-box
http://materialdesignicons.com/icon/numeric-3-box
http://materialdesignicons.com/icon/numeric-4-box
http://materialdesignicons.com/icon/numeric-5-box
http://materialdesignicons.com/icon/numeric-6-box
http://materialdesignicons.com/icon/numeric-7-box
http://materialdesignicons.com/icon/numeric-8-box
http://materialdesignicons.com/icon/numeric-9-box

**Comment by Templarian** [comment]
I replaced all the icons above and added -box-outline and box-multiple-outline for each. There is also a 9+ one.

**Comment by OnePersonCo** [comment]
Thank you, these are even better than I envisioned. Keep up the excellent work.
