### ISSUE TITLE
Icon for Golfing / Leisure activities in general

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#770]
I am looking for an icon for Golfing, or better: leisure activities in general.

**Comment by PeterShaggyNoble** [comment]
`golf` is now available in v2.1.19 so going to close this out. If you'd still like to have an icon for "leisure activities", please provide an example or 2 and we'll reopen this issue.

[![golf](https://user-images.githubusercontent.com/15157491/33830758-5ddbb220-de6d-11e7-913c-149253921bf1.png)](https://materialdesignicons.com/icon/golf)
