### ISSUE TITLE
Icon for math

### ISSUE THREAD

**Issue by Sijmenjeromkok** [Templarian/MaterialDesign#771]
Could some one make a good looking icon resembling math :) Thanks in advance

**Comment by CoDEmanX** [comment]
A sum symbol? https://materialdesignicons.com/icon/sigma

**Comment by Templarian** [comment]
Yea, I'm going to close this out. I think sigma is used by most applications to represent a math operation.

If you can think of an example please link it and I'll reopen the issue. Thanks!
