### ISSUE TITLE
Pram, handshake and tools icons as fonts

### ISSUE THREAD

**Issue by Boglarka** [Templarian/MaterialDesign#774]
Dear MaterialDesignIcons Team,

You closed my issue for request pram, handshake and tools (like a hammer and a ruler in same icon) icons because you have them already.

But how can I use them as fonts?

Thank you very much,
Boglarka

**Comment by Templarian** [comment]
Very formal issue request. Uhh, I'm fixing some bugs in the font build package, assuming you see the icons on the site they will be in the next font release shortly. Once I get the font build system bugs ironed out.

**Comment by CoDEmanX** [comment]
@Templarian: we don't actually have the icons, we have *requests* for them - therefore I closed the issue.

**Comment by Templarian** [comment]
Oh. Makes sense. Make sure it was marked with a duplicate tag if it was not.
