### ISSUE TITLE
Rubbish bin with triple lines

### ISSUE THREAD

**Issue by bardak-dev** [Templarian/MaterialDesign#777]
something like that

https://drive.google.com/file/d/0BzpJ4aq35w0LcFZIVUV6b0NjUVk/view

**Comment by CoDEmanX** [comment]
Are the stripes supposed to improve readability, or just an aesthetical alteration?

**Comment by bardak-dev** [comment]
stripes must to improve readability with a small amount

**Comment by CoDEmanX** [comment]
It's too narrow to make this work. And it looks ugly IMO if you increase the overall size:
![delete](https://cloud.githubusercontent.com/assets/1309249/10778840/e49400d0-7d29-11e5-832f-7288054109f1.png)

Might work better in an outlined variant.
