### ISSUE TITLE
MDI not on materialup.com (PR issue)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#778]
In today's newsletter, they linked to the following tools list regarding material design:

http://www.materialup.com/posts/c/tools?sort=popular

There's an entry called material design icons, but it is not us!

@Templarian: you should kick them and get MDI added.

**Comment by Templarian** [comment]
http://www.materialup.com/posts/material-design-icons It goes off votes.

We just need people to vote for it.

**Comment by CoDEmanX** [comment]
Huh, too bad. Do we need a nicer website maybe? Polymer/Angular MD could look really nice and make things look cleaner. We could use a little speedup as well.
Am 27.10.2015 7:15 nachm. schrieb Austin Andrews <notifications@github.com>:http://www.materialup.com/posts/material-design-icons It goes off votes.

We just need people to vote for it.

**Comment by Templarian** [comment]
Meh, nah the sites fine (it gets tons of traffic a day and thousands of downloads). MaterialUp is just one site out there.

I will be working to make the right click menu on the front page more obvious along with the advanced export feature.
