### ISSUE TITLE
Google Cloud Print Icon

### ISSUE THREAD

**Issue by preraksola** [Templarian/MaterialDesign#780]
Can we have an icon for Google Cloud Print? Something like:

![icon-cloudprint](https://cloud.githubusercontent.com/assets/8655814/10814255/16f3a746-7e25-11e5-8fd4-1b66f0ed1563.png)

**Comment by CoDEmanX** [comment]
Official Google Cloud Print icon:
![Imgur](http://i.imgur.com/nW3Pv1y.png)

It's not a material design icon, but an app icon like many others. They are usually multi-colored, not pixel perfect at 24x24 and so on. The best we can do is probably:

![print-cloud](https://cloud.githubusercontent.com/assets/1309249/10834988/754e9a66-7e9e-11e5-94e5-7bd5103cc658.png) https://www.dropbox.com/s/h4ksxx98bb5a8zv/print-cloud.svg?dl=0

**Comment by Templarian** [comment]
[![cloud-print](https://materialdesignicons.com/icon/cloud-print)](https://materialdesignicons.com/icon/cloud-print) [![cloud-print-outline](https://materialdesignicons.com/icon/cloud-print-outline)](https://materialdesignicons.com/icon/cloud-print-outline)
