### ISSUE TITLE
attachment-add

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#782]
Like https://materialdesignicons.com/icon/attachment but just with a "+"

**Comment by CoDEmanX** [comment]
The attachment icon or [it's rotated variant](https://materialdesignicons.com/icon/paperclip) usually add attachments to an email or whatever. I'm not sure if there really need to be variations of a lot of icons to explicitly depict add, remove and other actions...

**Comment by PeterShaggyNoble** [comment]
Closing for the reasons above.
