### ISSUE TITLE
Music notes (new and updated icons)

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#783]
![music-notes](https://cloud.githubusercontent.com/assets/1309249/10826034/1315e40c-7e68-11e5-8af5-4e3623aca4f3.png)

1. There are several music note icons, but they aren't fully MD
2. Google has two different icons (music-note and audiotrack)
3. Android 6 features additional icons

I created a set of music-notes, which are all based on Google's audiotrack icon. It is not 100% identical however, they had a small kink at pixel (15,7) and I fixed that.

![music-note-on](https://cloud.githubusercontent.com/assets/1309249/10825950/a291daec-7e67-11e5-876a-a852907f41b4.png) ![music-note-off](https://cloud.githubusercontent.com/assets/1309249/10825949/a28f32ec-7e67-11e5-9859-f32a77469d73.png) ![music-note-bluetooth-on](https://cloud.githubusercontent.com/assets/1309249/10825951/a292634a-7e67-11e5-9718-148e92528a66.png) ![music-note-bluetooth-off](https://cloud.githubusercontent.com/assets/1309249/10825948/a28b1fb8-7e67-11e5-8689-df2fa44b33e8.png)

![music-note-full](https://cloud.githubusercontent.com/assets/1309249/10825979/c3e8221e-7e67-11e5-8894-3d3d00e8e8ab.png) ![music-note-half](https://cloud.githubusercontent.com/assets/1309249/10825982/c5e6ab8a-7e67-11e5-9532-488162f7a0ab.png) ![music-note-quarter](https://cloud.githubusercontent.com/assets/1309249/10825987/caf22596-7e67-11e5-8b8f-3e933bec9d26.png) ![music-note-eights](https://cloud.githubusercontent.com/assets/1309249/10825989/cfaadf2e-7e67-11e5-9bb6-cdf3122eb142.png) ![music-note-sixteenths](https://cloud.githubusercontent.com/assets/1309249/10825992/d2c45a0a-7e67-11e5-8629-4ae821e8e33d.png)

Not sure what to do about Google's music-note icon, but I think it's best to leave it out since the audiotrack icon is much cleaner.

The strike-through variants do not use the default placement and length of the diagonal lines, but that's how they did it for the Android Marshmallow icons (I used a high-res reference shot).

The 16th note could be made more minimalist by merging the horizontal lines into one (and 5 pixel tall together), but it might be hard to understand what it's supposed to mean.

https://www.dropbox.com/sh/2tu2d2sicsjn8ra/AAAmtw6VHxAv2KSxTkbqMEZ9a?dl=0

**Comment by Templarian** [comment]
All of these have been updated/inserted.
