### ISSUE TITLE
Generic Social Icon

### ISSUE THREAD

**Issue by marrokin** [Templarian/MaterialDesign#785]
Would be great if a generic icon that identifies a social network or social networking that brings together in a single button something like a spider web or a circle out of the various arms and ultimately create a small circle

[Translated to English]

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/account-multiple Could probably be used for that. I'm not sure if everyone would connect a spider's web with social network (small size loses a lot of details).

https://materialdesignicons.com/icon/google-circles-group Might work also to show adding to a group (or social network).

**Comment by marrokin** [comment]
Gracias me puede servir (y)
