### ISSUE TITLE
Book add/remove

### ISSUE THREAD

**Issue by rtellezi** [Templarian/MaterialDesign#786]
Hello! There is some icon for book sell or buy? I need to include into my book share app.

**Comment by CoDEmanX** [comment]
Perhaps the bookmark icons?
https://materialdesignicons.com/icon/bookmark-plus
https://materialdesignicons.com/icon/bookmark-remove

**Comment by rtellezi** [comment]
Those icons represent the bookmark only, not the full book. I am using a simple add/remove, but the icon should be book centric

**Comment by CoDEmanX** [comment]
Some tests:
![book-plus2](https://cloud.githubusercontent.com/assets/1309249/11191678/c43a5596-8c9c-11e5-9a88-18ea3b62fd09.png)
![book-plus](https://cloud.githubusercontent.com/assets/1309249/11191679/c43b6bca-8c9c-11e5-927e-ac21a13502e1.png)
![book-open-variant-plus](https://cloud.githubusercontent.com/assets/1309249/11191677/c43953b2-8c9c-11e5-8da7-7873e65cf7e6.png)

**Comment by rtellezi** [comment]
The first look more "Material", but I like the third, because it is a book :D Thanks guy

**Comment by Templarian** [comment]
[![book-plus](https://materialdesignicons.com/icon/book-plus)](https://materialdesignicons.com/icon/book-plus) [![book-minus](https://materialdesignicons.com/icon/book-minus)](https://materialdesignicons.com/icon/book-minus)
