### ISSUE TITLE
Transfer money

### ISSUE THREAD

**Issue by micoll12268** [Templarian/MaterialDesign#787]
something similar to this:
![moneytransfer2](https://cloud.githubusercontent.com/assets/13754841/10857724/1c57152c-7f26-11e5-99a1-252f80f790b4.png)

**Comment by CoDEmanX** [comment]
Harder than I anticipated...

![exchange-usd3](https://cloud.githubusercontent.com/assets/1309249/10869158/06f404f2-80a6-11e5-9a70-77dfed2256a2.png) asymmetric
![exchange-usd](https://cloud.githubusercontent.com/assets/1309249/10869159/06f4f2e0-80a6-11e5-97f3-1d79530b385d.png) existing dollar icon is too large
![exchange-usd2](https://cloud.githubusercontent.com/assets/1309249/10869160/06f6138c-80a6-11e5-968d-8cfaf5a1f5d7.png) A very bold Roboto "S" at 13pt looks quite well and is very similar to the existing dollar icon.

**Comment by Templarian** [comment]
Can you link to the source for the 3rd one. I agree it is the best looking one.

**Comment by CoDEmanX** [comment]
Sure, heavy S:
https://www.dropbox.com/s/xl4caynb3uytm8j/exchange-usd2_path.svg?dl=0

And the same but only bold, which may be a bit better, because it doesn't emphasize the $ so much (the arrow things are very thin):
https://www.dropbox.com/s/ku7dsoybtvq112v/exchange-usd2_path2.svg?dl=0

**Comment by mnasyrov** [comment]
It would be nice to have an alternative variant with transferring a coin or a banknote, e.g. the existent 'cash' icon.

**Comment by diegogurgel** [comment]
I created a transfer money icon
![ic_transfer_money_48px](https://cloud.githubusercontent.com/assets/2058439/15190415/2516d5f0-1786-11e6-802b-fcdaacfda150.png)
👍  ?

**Comment by CoDEmanX** [comment]
@diegogurgel: can you provide a vector file please?

**Comment by diegogurgel** [comment]
Here @CoDEmanX  https://www.dropbox.com/s/w1wqqu7va188yx9/ic_transfer_money.svg?dl=0

**Comment by CoDEmanX** [comment]
From my online banking:

![image](https://user-images.githubusercontent.com/1309249/31473016-5790a0c4-aef2-11e7-8579-79d5e1a82863.png)

**Comment by Croutonix** [comment]
Here's the updated version from @diegogurgel, with the updated dollar sign and correct canvas size.
![image](https://user-images.githubusercontent.com/18645219/38904160-d066d582-4276-11e8-9669-04e4a74cab94.png)

**Comment by PeterShaggyNoble** [comment]
Note as well that, other than the `currency-*` icons themselves, we are no longer adding any currency-specific icons. One of the `bank-transfer-*` icons should fulfil this request.

**Comment by goyney** [comment]
We just discussed this and @PeterShaggyNoble is correct, we are no longer adding currency-specific icons. I'm going to close this issue. Thanks for your suggestion.
