### ISSUE TITLE
Medal icon

### ISSUE THREAD

**Issue by jasat90** [Templarian/MaterialDesign#790]
Or any icon idea for something like "most favorite / top viewed" ?

**Comment by CoDEmanX** [comment]
Maybe https://materialdesignicons.com/icon/seal ?

**Comment by MrGrigri** [comment]
Maybe a military medal?

![image](https://user-images.githubusercontent.com/4528551/35448726-58ff7028-0278-11e8-9a94-22705808df34.png)

[medal.zip](https://github.com/Templarian/MaterialDesign/files/1668328/medal.zip)

**Comment by Templarian** [comment]
[![medal](https://materialdesignicons.com/icon/medal)](https://materialdesignicons.com/icon/medal)
