### ISSUE TITLE
Bower package for Polymer component

### ISSUE THREAD

**Issue by balloob** [Templarian/MaterialDesign#791]
I am working on enlighting [Home Assistant](https://home-assistant.io/) with your icons.

Right now the Polymer 1.0 download is offered from the getting-started page. This makes it very difficult to check the version or upgrade to a new version in the future. On top of that, the HTML import makes it necessary to change the file if I don't want to use it from the root of my project.

Both problems could be solved if the Polymer component is either integrated in the existing bower package or published in a separate bower package.

**Comment by Templarian** [comment]
I won't be adding anymore bower packages to maintain (especially for a specific framework), but maybe versioning could be an option.
