### ISSUE TITLE
Fire extinguisher

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#792]
This is more of a reminder for me to create it, I found some good references already ;)

**Comment by CoDEmanX** [comment]
Initial attempt:
![fire-extinguisher](https://cloud.githubusercontent.com/assets/1309249/11072908/617b7bfa-87e8-11e5-8853-25180072f508.png)

**Comment by Sithdown** [comment]
It looks good. Maybe it looks better with a smaller nozzle?

**Comment by CoDEmanX** [comment]
Different style: ![fire-extinguisher2_ 792](https://cloud.githubusercontent.com/assets/1309249/14904481/b6503918-0da8-11e6-8cf5-f10999e0accd.png)

**Comment by Templarian** [comment]
Both are nice, but the nov 10th one is probably the best if you still have the source.

**Comment by goyney** [comment]
Removing the Contribution label as this icon is not ready to be added because no source SVG exists.

CC: @CoDEmanX

**Comment by AndrewJoubert** [comment]
Hi, very new to contributing to material design icons, we have a need for the fire-extinguisher icon and came across this issue. Have SVG'd the second as it seems to fit the https://material.io/design/iconography/system-icons.html# 

> Do.
>
>Use geometric, consistent shapes.

Advice so here it is. Happy to fix if any errors with it or can SVG the first design!

http://assets.showplans.com/fire-extinguisher.svg

As github does not support svg file types! 

Hope this is good, thanks.

**Comment by AndrewJoubert** [comment]
@goyney and @CoDEmanX Would it be possible to review and feedback on my attempt, very happy to learn and help out. Its a really useful project!

**Comment by goyney** [comment]
If you would like to contribute an idea for this (or any icon), make sure you SVG is combined down to a single path. You can use our Preview Generator (http://dev.materialdesignicons.com/contribute/github) to create an image to paste into the GitHub issue. Then attach the SVG (ZIPed up) to the issue as well.

**Comment by Templarian** [comment]
Added. 😃
