### ISSUE TITLE
Folder Edit

### ISSUE THREAD

**Issue by kevlut** [Templarian/MaterialDesign#793]
Take the pencil from `table-edit` and `folder` and combine them to create a `Folder Edit`

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33995826-1b9d4c4a-e0d7-11e7-9be0-2c7784a5280d.png)](https://github.com/Templarian/MaterialDesign/files/1559442/folder-edit.zip)[![](https://user-images.githubusercontent.com/15905797/33995842-240ab62e-e0d7-11e7-917e-b98d05be6dc2.png)](https://github.com/Templarian/MaterialDesign/files/1559443/folder-edit2.zip)

**Comment by Templarian** [comment]
[![folder-edit](https://materialdesignicons.com/icon/folder-edit)](https://materialdesignicons.com/icon/folder-edit)
