### ISSUE TITLE
Add Network

### ISSUE THREAD

**Issue by kevlut** [Templarian/MaterialDesign#794]
Take 'close-network' and rotate the "x" and make it an "Add Network" icon.

**Comment by kevlut** [comment]
This already exists, however the two icons are not by each other.  The name is "plus-network"

**Comment by Templarian** [comment]
Yea, `*-network` is seen as a modifier to an existing icon. The naming seems weird because both `plus` and `network` can both be append to an existing icon.

**Comment by CoDEmanX** [comment]
@Templarian: what do you think of hidden names to be used for grouping internally? Should be easy to implement.

**Comment by kevlut** [comment]
I think CoDEmanX's idea is good.  Would be nice to filter/group by "Category," where "network" would be a category. Others possibly being Brand (or Logo), Folder, Profile, Arrows, Views, etc.  

The deprecated open_icon_library had categories like: actions, animations, apps, devices, emblems, emotes, places, status, symbols, etc.

**Comment by Templarian** [comment]
@CoDEmanX Technically that is what the tag system is for, I just never tag the icons. Eventually a page with icons grouped by tags would probably be nice.

**Comment by kevlut** [comment]
@Templarian is contributor section disabled on purpose?  I can't click "Become a Contributor"

**Comment by Templarian** [comment]
Yea, it's disabled because I broke it and never fixed it. Right now we're managing everything through issues, seems to work okay.

**Comment by CoDEmanX** [comment]
@templarian: I would tag them, I just need access to the db in some way. Would that page with icons grouped by tag replace the current home page?

@kevlut: yes. You can post links to self made icons (SVG) here though.

**Comment by kevlut** [comment]
@Templarian So how can I contribute if pull requests are prohibited?  Fork, add new icons, commit, post link to my repo?

**Comment by Templarian** [comment]
@kevlut Open an issue with the icon and SVG file (make sure it processes in materialdesignicons.com/custom). SVG file can be uploaded anywhere, dropbox etc.

**Comment by Templarian** [comment]
Yea, you could also fork it and do it there, that would be fine.
