### ISSUE TITLE
Electronic on-board recorder (connected car)

### ISSUE THREAD

**Issue by jeanPokou** [Templarian/MaterialDesign#795]
I will be very please if you can have icon related to An electronic on-board recorder (EOBR), 
such as a  'connected car' , truck receiving signal

**Comment by CoDEmanX** [comment]
A "connected car" seems much different from an icon for EOBR, are these actually two requests?

![car-connected](https://cloud.githubusercontent.com/assets/1309249/11158579/836f6618-8a59-11e5-8da2-2efbc4f24fec.png)

**Comment by jeanPokou** [comment]
This a great but If you can make an EOBR icon that would be perfect

**Comment by CoDEmanX** [comment]
Honestly, I have no clue how that could possibly be represented in 24 square pixels.
Maybe it's better to use one of the existing vehicle icons (car, truck, steering wheel...) and put a text label "EOBR" next to it.

**Comment by Templarian** [comment]
I like the connected car icon, lets add that one (need the file).

I agree, it might be best to use text with it as it is fairly specific.

**Comment by CoDEmanX** [comment]
https://www.dropbox.com/s/tuacaf2j9op22fz/car-connected.design?dl=0

**Comment by Templarian** [comment]
[![car-connected](https://materialdesignicons.com/icon/car-connected)](https://materialdesignicons.com/icon/car-connected)

Yea, I think this is the closest we'll get to a connect car. Can't think of any other ideas.
