### ISSUE TITLE
Quit Icon

### ISSUE THREAD

**Issue by SatyaRaj-solivarindia** [Templarian/MaterialDesign#797]
Could you design a 'Quit' icon?
It is not like the cancel (which is a cross symbol) something which is different from it.

Thanks!

**Comment by kevlut** [comment]
@SatyaRaj-solivarindia Quit can be a lot of things.  If its not a cross, then what is it? Is it a cross on a rectangle, is it a cross in a circle.  Other?

**Comment by CoDEmanX** [comment]
There are already the following two:
https://materialdesignicons.com/icon/power
https://materialdesignicons.com/icon/exit

**Comment by Templarian** [comment]
This issue hasn't had a comment for 2 weeks. I'm going to assume it can be closed. Feel free to reopen it with more information.
