### ISSUE TITLE
SVG's can't be loaded using mdIconProvider

### ISSUE THREAD

**Issue by xenit-raven** [Templarian/MaterialDesign#798]
I really want to use this icon set - it's seriously the greatest collection of material design SVG's. My problem is that when using Angular Material's `<md-icon>` I can't figure out how to make the icon set load property in `$mdIconProvider`.

I've provided a simple example here:
http://codepen.io/anon/pen/GpBjWm
Where the first icon is not being loaded by the IconProvider

**Comment by Zorgatone** [comment]
See how I did it here: #854

**Comment by Templarian** [comment]
Can you test this [download](https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B)

**Comment by Zorgatone** [comment]
[**@Templarian**](https://github.com/Templarian) commented on [22 nov 2015, 09:50 CET](https://github.com/Templarian/MaterialDesign/issues/798#issuecomment-158737668 "2015-11-22T08:50:37Z - Replied by Github Comment Enhancer"):
> Can you test this [download](https://materialdesignicons.com/api/download/angularmaterial/38EF63D0-4744-11E4-B3CF-842B2B6CFE1B)

As I read through the SVG code, that I'm 99.99% sure that'll work... I'll try it anyway, the format seems correct.
