### ISSUE TITLE
Folder Cursor (Rename)

### ISSUE THREAD

**Issue by kevlut** [Templarian/MaterialDesign#799]
[Rename a folder](https://github.com/kevlut/MaterialDesign/blob/master/icons/svg/folder-cursor.svg)

I don't like the cursor very much, and I don't know why it doesn't always render sharp edges.  Is it because there are fractional width/heights?  Feel free to pull request on my original or recommend changes I should make.

**Comment by CoDEmanX** [comment]
It's not very legible, because it's very small and it's not pixel-perfect. Please make sure it's on the pixel grid, and if possible, the minimum line width should be 2px.

**Comment by Templarian** [comment]
Removing the contribution label. Is there a reason why one couldn't use the more generic: https://materialdesignicons.com/icon/textbox or https://materialdesignicons.com/icon/rename icon?

**Comment by JamesCoyle** [comment]
In my opinion such an icon is way too specific and hard for a user to actually recognize what it means.

**Comment by Templarian** [comment]
I'm going to close this issue out. If someone thinks of an example that could work nicely for this I'll reconsider it. Thanks!
