### ISSUE TITLE
Foursquare icon

### ISSUE THREAD

**Issue by larikitty** [Templarian/MaterialDesign#80]
This icon above still needed.

![Logo For Reference](https://ss0.4sqi.net/img/homepage/_allNewFoursquare/f-9744b9730c4ff74e4c9b7dbeb24daf32.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/foursquare

Please note it has been modified from the official logo slightly to more accurately match the style.

**Comment by larikitty** [comment]
;)
