### ISSUE TITLE
Cursor Text

### ISSUE THREAD

**Issue by kevlut** [Templarian/MaterialDesign#800]
[cursor-text?](https://github.com/kevlut/MaterialDesign/blob/master/icons/svg/text-cursor.svg)

Feel free to pull request on my original or recommend changes I should make.

**Comment by CoDEmanX** [comment]
Actually a duplicate / fulfillment of #199, and I posted a slightly different icon here: https://github.com/Templarian/MaterialDesign/issues/270#issuecomment-125912536

**Comment by CoDEmanX** [comment]
Does anyone know of the semantic difference between ![text-cursor](https://cloud.githubusercontent.com/assets/1309249/8955352/27db7678-35ec-11e5-9232-ebaa27f18b67.png) and ![cursor-text](https://cloud.githubusercontent.com/assets/1309249/14903597/5a49cc8e-0da2-11e6-8272-1b5a6680c79f.png) ?

We already have the latter, but if the former has a different meaning, we might want to add it as well.

**Comment by Templarian** [comment]
I don't think there is a difference... not sure though. Going to close this, if it ever comes up, we'll add it.
