### ISSUE TITLE
Edit Network

### ISSUE THREAD

**Issue by kevlut** [Templarian/MaterialDesign#801]
[edit-network](https://github.com/kevlut/MaterialDesign/blob/master/icons/svg/edit-network.svg)

Feel free to pull request on my original or recommend any changes you'd like me to make.

**Comment by CoDEmanX** [comment]
It's not recognizable at 24px, there's simply not enough room left in the rectangle for a shrunken version of the pencil icon.

**Comment by Templarian** [comment]
Agreed, it isn't obvious it is a pencil at small size.

**Comment by Templarian** [comment]
Going to close this issue. Probably best to just use the more generic pencil icon.
