### ISSUE TITLE
Nearby icon

### ISSUE THREAD

**Issue by vicmns** [Templarian/MaterialDesign#802]
it will be nice to have a "Nearby Icon" as the Google API library uses: https://developers.google.com/nearby/

**Comment by CoDEmanX** [comment]
Doesn't look very clear to me, and not sure there's anything that could be improved:

![nearby](https://cloud.githubusercontent.com/assets/1309249/10920348/e269141c-826f-11e5-9117-c056961d1da6.png)

**Comment by vicmns** [comment]
Sorry my bad, didn't saw it on the page. What's the name of the icon then?

**Comment by CoDEmanX** [comment]
There's no icon, what I meant is that it doesn't really fit in the font. But I'll leave it up to @Templarian.

**Comment by Templarian** [comment]
It's an ugly icon, but I'm fine calling it `google-nearby`. Can you link the source @CoDEmanX.

**Comment by CoDEmanX** [comment]
![nearby](https://cloud.githubusercontent.com/assets/1309249/10920348/e269141c-826f-11e5-9117-c056961d1da6.png) https://www.dropbox.com/s/aoo22hi6783gfz3/nearby.svg?dl=0
![nearby2](https://cloud.githubusercontent.com/assets/1309249/10950129/9bb62b6e-8336-11e5-813e-945d64b505ec.png) https://www.dropbox.com/s/j3z3gn2anmmjv0w/nearby2.svg?dl=0

The second is slightly different, it was supposed to be more precise in regards to pixel-perfection. Not sure if it's actually better though, both don't have symmetric paths.

**Comment by Templarian** [comment]
[![google-nearby](https://materialdesignicons.com/icon/google-nearby)](https://materialdesignicons.com/icon/google-nearby)
