### ISSUE TITLE
Advanced interface is hard to understand

### ISSUE THREAD

**Issue by RYO-Software** [Templarian/MaterialDesign#803]
Hello,

I've been out for a few months and now I and I see that the advanced download interface has changed.

Now, is difficult to download any icon, and is impossible (or at least I can't do) to download a icon that has a size higher to 256px.

Also, in the past is easy to download the icon in all resolutions (24px, 36px, 48px) with a single click, but I think now I need to download it separately. That's isn't practical.

Can you think on restore the previous version of the download interface.

In any case: thanks for the great work!

**Comment by Templarian** [comment]
Those features will be returning to the basic view eventually. There was a lot of recoding in the background to support future icon sets (I use the backend to manage a handful of icon packs). I removed a lot of the hard coded MDI specific logic. Advanced export is still very much a work in progress.

It is all leading up to allow for more extensive export options (on MDI and other icon sets I bring into the system).

For icons larger than 256 please use the vector svg files and your favorite editor. That limitation is hard coded into the endpoints to prevent excessive CPU usage on the servers.

Thanks. These kind of issues help me gauge interest in certain features outside of the event logging.
