### ISSUE TITLE
Bed icon

### ISSUE THREAD

**Issue by GRA0007** [Templarian/MaterialDesign#804]
Request for a bed icon, like below:

![](https://cdn4.iconfinder.com/data/icons/medical-icons-normal/1000/modules_IP.png)

**Comment by CoDEmanX** [comment]
It already exists under a different name:
https://materialdesignicons.com/icon/hotel

@Templarian: We really need tagging support for contributors!

**Comment by GRA0007** [comment]
I'm not good at designing icons, but if I could help tag them, that would be great, because I've noticed most of the icons are under unexpected names and need tags so people can search for them.

**Comment by Templarian** [comment]
Alias added.
