### ISSUE TITLE
External Link Icon

### ISSUE THREAD

**Issue by IgnaciodeNuevo** [Templarian/MaterialDesign#805]
I will be very please if you can have icon related to an external link, something like this

![external-link](https://cloud.githubusercontent.com/assets/10051329/10947190/f7f01ec2-8326-11e5-847e-bb062c298e8c.jpg)
![external-link](https://cloud.githubusercontent.com/assets/10051329/10947189/f7eed86e-8326-11e5-83ec-c4795003f9cf.png)

**Comment by CoDEmanX** [comment]
Your lucky day: We already have that!
https://materialdesignicons.com/icon/open-in-new

**Comment by Grawl** [comment]
why all these icons have so hard to find names
