### ISSUE TITLE
With IOT in mind - would be nice to have a Kettle!

### ISSUE THREAD

**Issue by pavoni** [Templarian/MaterialDesign#806]

**Comment by CoDEmanX** [comment]
I like this water boiler:
![Imgur](http://i.imgur.com/0qV1BF1.png?1)

**Comment by pavoni** [comment]
Excellent! :+1:

**Comment by CoDEmanX** [comment]
Not happy with the handle yet:
![water-boiler](https://cloud.githubusercontent.com/assets/1309249/10986075/178bf160-8427-11e5-8a33-286ae3efa9a7.png) https://www.dropbox.com/s/r5tedv1o5pj4oop/water-boiler.svg?dl=0

**Comment by pavoni** [comment]
Looks good - although I think the more rounded handle above fir the design better.

Thanks for taking this on so fast!

**Comment by CoDEmanX** [comment]
![water-boiler2](https://cloud.githubusercontent.com/assets/1309249/11080445/fbac4d50-8813-11e5-9095-35e29b1d4f4b.png) ?

**Comment by pavoni** [comment]
Looks great!

**Comment by Sithdown** [comment]
Nice icon!

**Comment by pavoni** [comment]
Would love to use this one if you guys are OK to merge!

**Comment by Templarian** [comment]
Yea, that one looks nice. Do you have the SVG/Design @CoDEmanX?

**Comment by CoDEmanX** [comment]
It's part of the pack here:
https://github.com/Templarian/MaterialDesign/issues/420#issuecomment-154769174

And here's another version I did, not sure which one is better:
![water-boiler3](https://cloud.githubusercontent.com/assets/1309249/11770544/65898cea-a201-11e5-8d81-1bdb82d25292.png) https://www.dropbox.com/s/rfkwve4pf8j4yzz/water-boiler3.svg?dl=0

**Comment by Templarian** [comment]
[![kettle](https://materialdesignicons.com/icon/kettle)](https://materialdesignicons.com/icon/kettle)
