### ISSUE TITLE
Another IoT related idea - a Gate

### ISSUE THREAD

**Issue by pavoni** [Templarian/MaterialDesign#807]

**Comment by CoDEmanX** [comment]
Can you add an example? A Google image search brings up all kinds of gates...

**Comment by pavoni** [comment]
What about:-

![image](https://cloud.githubusercontent.com/assets/4487313/10955339/0b3b1a8a-834b-11e5-8b8d-781d9c859174.png)

![image](https://cloud.githubusercontent.com/assets/4487313/10955355/1a660fb0-834b-11e5-9b1f-976d89f7e4db.png)

or

![image](https://cloud.githubusercontent.com/assets/4487313/10955372/2e902dae-834b-11e5-86ce-b2b0bc17a010.png)

**Comment by CoDEmanX** [comment]
The boundary between gate and fence is fluid...
![gate3](https://cloud.githubusercontent.com/assets/1309249/10985768/788834cc-8424-11e5-9773-14be0bac3c47.png) https://www.dropbox.com/s/bqbd3jxpdocahfd/gate3.svg?dl=0
![gate2](https://cloud.githubusercontent.com/assets/1309249/10985767/788651d4-8424-11e5-80e1-2a8d2d881b7a.png) https://www.dropbox.com/s/tz7ijjl8uf0cr3s/gate2.svg?dl=0
![gate1](https://cloud.githubusercontent.com/assets/1309249/10985769/788974b8-8424-11e5-84f0-983e7700c88e.png) https://www.dropbox.com/s/5w8ejssgcqwim9o/gate1.svg?dl=0

**Comment by pavoni** [comment]
Your right the top two could be mistaken as fences. I think the third is less likely to be confused (it's unusual for a fence to be that shape).

The second is less fence like that the first (IMHO) if you prefer that design.

Thanks again for doing this.

**Comment by Templarian** [comment]
[![gate](https://materialdesignicons.com/icon/gate)](https://materialdesignicons.com/icon/gate)

**Comment by CoDEmanX** [comment]
It's not grid-aligned and thus blurry. The file I uploaded is pixel-perfect however. I've seen this on a few icons now, is there something wrong with your pipeline?
