### ISSUE TITLE
Ghost Icon

### ISSUE THREAD

**Issue by niteshkhatri** [Templarian/MaterialDesign#808]
There should a ghost icon like that of pacman ghost. It will be appreciated.

**Comment by CoDEmanX** [comment]
Good idea, shouldn't be too hard. Although, there are multiple kinds of ghosts: Pacman ghosts, Hui Buh, Ghost Busters...

**Comment by niteshkhatri** [comment]
@CoDEmanX Yeah there should be every type of ghost. When the icon will be available in materialdesignicons.com?

**Comment by niteshkhatri** [comment]
I like this one

![photo](https://cloud.githubusercontent.com/assets/7664984/10974722/6beed31c-8409-11e5-8640-eeee594a3709.jpg)

**Comment by Templarian** [comment]
Yea, material enough, I think that will be the style that gets added. I'll be working to add a lot of these this weekend. Playing catchup now that I have a release out.

**Comment by CoDEmanX** [comment]
Sorry, I had to try on this one :ghost: 
![ghost](https://cloud.githubusercontent.com/assets/1309249/10985574/a5cab588-8422-11e5-8cfd-74d04233b278.png) https://www.dropbox.com/s/kz49w9aj4b95be3/ghost.svg?dl=0

**Comment by Templarian** [comment]
@CoDEmanX Get a twitter account, you're almost at 100 icons (well probably already are, just behind on uploads). This needs to be shared!

[![ghost](https://materialdesignicons.com/icon/ghost)](https://materialdesignicons.com/icon/ghost)

**Comment by CoDEmanX** [comment]
I actually have a twitter account that belongs to my nickname that you can add: @XT3000

**Comment by Templarian** [comment]
Edited it to your account. Probably going to tweet something tomorrow if I get a second.
