### ISSUE TITLE
Umbraco icon

### ISSUE THREAD

**Issue by bjarnef** [Templarian/MaterialDesign#809]
It would be great if the Umbraco CMS icon can be added as well :+1: 

![image](https://cloud.githubusercontent.com/assets/2919859/10962516/23061c48-8399-11e5-92ee-7698fbc8ea95.png)

The icon can be found in high resolution here: http://umbraco.com/follow-us/blog-archive/2010/5/3/new-umbraco-identity

Direct download to the logo type: http://umbraco.com/assets/umbraco_logos.zip

**Comment by Templarian** [comment]
[![umbraco](https://materialdesignicons.com/icon/umbraco)](https://materialdesignicons.com/icon/umbraco)
