### ISSUE TITLE
Firefox SVG Import

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#81]
Firefox has an issue importing icons. Probably the bootstrap file button.

Workaround: Use Chrome / Webkit / IE for now.

**Comment by REJack** [comment]
In Internet Explorer 11 has the issue too

**Comment by CoDEmanX** [comment]
I can confirm that it's broken in latest Firefox 39 and Internet Explorer 11 on Windows 8.1. A click on the upload button just selects another field, like the name field for custom icon  and displays the tooltip.
