### ISSUE TITLE
Custom Emoji or Stickers

### ISSUE THREAD

**Issue by niteshkhatri** [Templarian/MaterialDesign#810]
I want an icon for Sickers or custom emojis for a messaging app.

**Comment by CoDEmanX** [comment]
Does custom mean the users can draw their own, or create new ones from a variety of base elements? Or do you mean your app uses custom, but non-editable emojis?

**Comment by niteshkhatri** [comment]
Custom means i have various stickers in my app. And yes they are non-editable.

**Comment by Templarian** [comment]
I'm not entirely sure how to represent this one. If anyone has any examples that would be great.

**Comment by niteshkhatri** [comment]
Currently I am using this one

![panda 1](https://cloud.githubusercontent.com/assets/7664984/10989991/2a71c33e-8474-11e5-80a5-7b9db955abed.png)

How is it?

**Comment by Templarian** [comment]
Actually that's probably a good icon for stickers. I think I would get the idea if I saw it in an app.

I really can't think of any other thing that might represent it.
