### ISSUE TITLE
File Rename Icon

### ISSUE THREAD

**Issue by CxRes** [Templarian/MaterialDesign#812]
A new Icon Request: Rename pencil superimposed on file

**Comment by CoDEmanX** [comment]
I took the pencil from table-edit icon, shortened it a bit and subtracted it from the file icon and I must say, it's not the most legible icon:

![file-pencil](https://cloud.githubusercontent.com/assets/1309249/11190466/e5b0e8d6-8c95-11e5-90fd-5d646efa5074.png)

**Comment by PeterShaggyNoble** [comment]
There's Google's `rename-box` icon. If it doesn't suit your needs, let us know and we'll reopen this issue.

[![rename-box](https://user-images.githubusercontent.com/15157491/33830889-dc15b014-de6d-11e7-86f4-a1bd22feda8b.png)](https://materialdesignicons.com/icon/rename-box)

**Comment by CxRes** [comment]
@PeterShaggyNoble Having a pencil on a file seems more idiomatic imho. Perhaps making one on the pattern of Google's `file-find` or `file-restore` with the magnifying glass/restore replaced by the pencil may work better than superimposing a shortened pencil on `file`, the later as @CoDEmanX tried being scribbly.

Something like this maybe?
![file_rename](https://user-images.githubusercontent.com/2706227/33838039-480bb12e-deb4-11e7-9b85-a18e39849232.png)
