### ISSUE TITLE
Search keyboard input bug

### ISSUE THREAD

**Issue by jahirfiquitiva** [Templarian/MaterialDesign#813]
I can't use Start or End keys of keyboard when doing an icon search.
Neither Shift + Start nor Shift + End.

**Comment by Templarian** [comment]
Why exactly is this a bug?

**Comment by jahirfiquitiva** [comment]
I consider this a bug because sometimes I prefer to be able to select all the text to search something again, instead of pressing the backspace key many times.

Also, going to start or end, allows me to add or change a missed character in case I did it.

**Comment by Templarian** [comment]
Makes sense. Will be working on some other bugs this weekend. Should get to this one.

**Comment by jahirfiquitiva** [comment]
Hi @Templarian

Sorry for disturbing but it's been more than a year and this hasn't been fixed.

Thanks

**Comment by PeterShaggyNoble** [comment]
Closing this as development focus has shifted to the new site.
