### ISSUE TITLE
CRUD Icons

### ISSUE THREAD

**Issue by lssilveira11** [Templarian/MaterialDesign#815]
Icon request: the common CRUD icons, i.e., icons for create, request, update and delete. They will help when building CRUD applications.

**Comment by CoDEmanX** [comment]
it's actually **r**ead, and I'm not sure how to represent that...

Operation | Possibly icon
---|---
Create | https://materialdesignicons.com/icon/plus
Read | https://materialdesignicons.com/icon/arrow-up ???
Update | https://materialdesignicons.com/icon/close
Delete | https://materialdesignicons.com/icon/close
Replace | ???

**Comment by PeterShaggyNoble** [comment]
[`book-open`](https://materialdesignicons.com/icon/book-open), [`check`](https://materialdesignicons.com/icon/check) and [`read`](https://materialdesignicons.com/icon/read) are some more options for "read".
