### ISSUE TITLE
Icon request: PHP

### ISSUE THREAD

**Issue by oscarCrespo** [Templarian/MaterialDesign#816]

**Comment by CoDEmanX** [comment]
Taken from their official vector logo:
![php](https://cloud.githubusercontent.com/assets/1309249/11018361/3bdc1e82-85c6-11e5-94dc-3685435c4b3d.png) https://www.dropbox.com/s/4hy1flm2dsi1w28/php.svg?dl=0

**Comment by Templarian** [comment]
[![language-php](https://materialdesignicons.com/icon/language-php)](https://materialdesignicons.com/icon/language-php)

**Comment by oscarCrespo** [comment]
Great thanks man
