### ISSUE TITLE
Download entire collection of PNGs

### ISSUE THREAD

**Issue by AGithub457** [Templarian/MaterialDesign#817]
How can I download all of the icons in PNG format for use of my Android App? I would like to store them all locally instead of having to manually download each individual icon set when i need it.

**Comment by Templarian** [comment]
Currently there is no option to do that. It would be a pretty large download; zipped it would be about 134MB if I estimate it. 

Right now it is not on the road map. Trying to keep thing amount of things that have to be done during each release to a minimal.

https://github.com/google/material-design-icons/issues/62#issuecomment-68640868 I shared part of the PHP script I used before to generate the 5x icons.

Eventually it would be really nice to have a NPM package to download / generate all the icons.
