### ISSUE TITLE
Reflection Effect Icon

### ISSUE THREAD

**Issue by mehrdadasgari** [Templarian/MaterialDesign#818]
Something like material design flip icon in Android Studio Vector assets but horizontally.

**Comment by CoDEmanX** [comment]
Like this?
![flip-vertical](https://cloud.githubusercontent.com/assets/1309249/11023472/4dad56da-867a-11e5-8199-12938808f29b.png)
![flip-vertical-x4](https://cloud.githubusercontent.com/assets/1309249/11023473/4dad4622-867a-11e5-82a7-7e905f3ad8cb.png)

**Comment by GreenTurtwig** [comment]
I'm surprised we don't have this.
My vote goes to the second. :tiger2:

**Comment by PeterShaggyNoble** [comment]
Ah-ha! I knew I'd seen this somewhere before. Personally I think it'd look better without the dividing line, as in the examples in #3285.

**Comment by Templarian** [comment]
[![reflect-horizontal](https://materialdesignicons.com/icon/reflect-horizontal)](https://materialdesignicons.com/icon/reflect-horizontal) [![reflect-vertical](https://materialdesignicons.com/icon/reflect-vertical)](https://materialdesignicons.com/icon/reflect-vertical)
