### ISSUE TITLE
Question icon

### ISSUE THREAD

**Issue by Bil0** [Templarian/MaterialDesign#819]
![speech3](https://cloud.githubusercontent.com/assets/10976283/11031387/52502424-86d4-11e5-89d5-57464b7f489b.png)

**Comment by CoDEmanX** [comment]
Probably this with a question mark:
https://materialdesignicons.com/icon/comment-alert-outline

I took the upper part of a Roboto ? in heavy, and streched it to the width of the existing period rect:
![comment-question-outline](https://cloud.githubusercontent.com/assets/1309249/11031786/27c7ce48-86d7-11e5-924d-a7dae5bedbfa.png) https://www.dropbox.com/s/oca14hk09bcmjl3/comment-question-outline.svg?dl=0

**Comment by Bil0** [comment]
https://www.dropbox.com/s/pc5gi03cf6fkas0/ask-question.svg?dl=0

**Comment by CoDEmanX** [comment]
@Bil0: It's not compliant to the MD guidelines, the minimum stroke and margin width should be 2px.

**Comment by Templarian** [comment]
[![comment-question-outline](https://materialdesignicons.com/icon/comment-question-outline)](https://materialdesignicons.com/icon/comment-question-outline)

**Comment by Bil0** [comment]
@Templarian: I'm using //cdn.materialdesignicons.com/1.3.41/css/materialdesignicons.min.css in my website but I get nothing with:  `<span class="mdi mdi-comment-question-outline"></span>` !
what should I do?

**Comment by CoDEmanX** [comment]
It's not released yet, see the blue entries in the history:
https://materialdesignicons.com/history

**Comment by Bil0** [comment]
Ok! thanks!
