### ISSUE TITLE
filmstrip-off

### ISSUE THREAD

**Issue by ezkay** [Templarian/MaterialDesign#82]
Extend the filmstrip with "no-filmstrip". Would be so useful!
something like this:

![no-filmstrip](https://cloud.githubusercontent.com/assets/10404121/5615940/0c108150-9500-11e4-8b76-6a3f4227ea00.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/filmstrip-off

Feel free to submit other icon requests as you notice they are missing. Good luck on your apps!

**Comment by ezkay** [comment]
Hi! Thanks for your quick response! But i am getting in trouble with my customer here. It's a german live-stream provider which has this icon in it's company's logo - so it's copyrighted in this exact look..
I'm really sorry, but i was forced to tell you to delete the icon before this get' serious. It's my bad and i'm really sorry!

**Comment by Templarian** [comment]
@ezkay The icon is based off of the Official Material Design icon set guidelines. I _highly_ doubt they are using the same style in their logo.

Please link the official logo's vector file for comparison. If they are in the same 1:1 look and style I'll remove it.
