### ISSUE TITLE
Afk icon

### ISSUE THREAD

**Issue by Pandakls** [Templarian/MaterialDesign#820]
An afk icon in order to make a button that signal that you're away/busy.
#afk #busy #away

Or when someone is idle for a while, this kind of icon can appear close to his profile picture.

Maybe some zzZ or stuff like that

**Comment by Templarian** [comment]
Could use [keyboard-off](https://materialdesignicons.com/icon/keyboard-off) for that?

**Comment by Templarian** [comment]
Or https://materialdesignicons.com/icon/sleep like you suggested. I can't think of any other ideas that would represent that.

**Comment by CoDEmanX** [comment]
Damn... too slow! was going to suggest the same.

You could also use:
https://materialdesignicons.com/icon/timer-sand
https://materialdesignicons.com/icon/clock

Or possibly account (online) and account-outline (away).

@Templarian: how do you feel about an `account-off` strike-through icon?

This came up in a Google search btw :laughing: 
http://shirta.de/media/catalog/product/cache/1/small_image/295x295/9df78eab33525d08d6e5fb8d27136e95/a/f/afk-d75197878.png

**Comment by Templarian** [comment]
@CoDEmanX Surprised we don't have an account-off icon already. We should add one. I think this issue is closed as there are many icons that could represent an afk mode.

Also, ha.

**Comment by CoDEmanX** [comment]
Hm the positioning of the diagonal line is a bit tricky, what do you think about this?
![account-off](https://cloud.githubusercontent.com/assets/1309249/11071226/f968941a-87df-11e5-9641-6725972bd568.png) https://www.dropbox.com/s/sllstpb53j7yede/account-off.design?dl=0

**Comment by Templarian** [comment]
Looks okay.

**Comment by Templarian** [comment]
[![account-off](https://materialdesignicons.com/icon/account-off)](https://materialdesignicons.com/icon/account-off)
