### ISSUE TITLE
new icons: departure, arrival, en-route

### ISSUE THREAD

**Issue by hasyee** [Templarian/MaterialDesign#821]
Dear Editors,

i suggest three icon ideas:

Thx!

arrival
![arrival](https://cloud.githubusercontent.com/assets/7387621/11067812/a8020b12-87ce-11e5-8c87-3404b06344ae.png)
departure
![departure](https://cloud.githubusercontent.com/assets/7387621/11067813/a82002c0-87ce-11e5-9e5e-dc10cbf6472f.png)
en-route
![enroute](https://cloud.githubusercontent.com/assets/7387621/11067814/a8315dea-87ce-11e5-8abf-5417c94e0211.png)

**Comment by hasyee** [comment]
I can send svg too if you need it.

**Comment by Templarian** [comment]
Dearest Hasyee,

They kind of look like sliders, but yea, not sure I like the naming. They look like they could be useful to show step progress also. `step-start`, `step-end`, `step-???`.

@CoDEmanX any ideas of what we should call these?

**Comment by CoDEmanX** [comment]
step-progressing or in-progress?

Or if you look at the GitHub icon for commit, it would be something like root-commit (tail?), commit, tip.

To avoid the slider look, how about rotating them 90°? Or add arrow heads?

**Comment by Templarian** [comment]
We could just treat them as geometry related rays. `ray-start`, `ray-end`, `ray-vertex`, then have 2 more with arrows. `ray-right`, `ray-left`.

**Comment by hasyee** [comment]
Maybe: route-start, route-end, route-intermediate?

**Comment by Templarian** [comment]
[![ray-start-end](https://materialdesignicons.com/icon/ray-start-end)](https://materialdesignicons.com/icon/ray-start-end) [![ray-start](https://materialdesignicons.com/icon/ray-start)](https://materialdesignicons.com/icon/ray-start) [![ray-end](https://materialdesignicons.com/icon/ray-end)](https://materialdesignicons.com/icon/ray-end) [![ray-vertex](https://materialdesignicons.com/icon/ray-vertex)](https://materialdesignicons.com/icon/ray-vertex) [![ray-start-arrow](https://materialdesignicons.com/icon/ray-start-arrow)](https://materialdesignicons.com/icon/ray-start-arrow) [![ray-end-arrow](https://materialdesignicons.com/icon/ray-end-arrow)](https://materialdesignicons.com/icon/ray-end-arrow)

**Comment by hasyee** [comment]
Oh, thank you very much!
It makes the fontset richer ;)
