### ISSUE TITLE
Anchor

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#822]
![anchor](https://cloud.githubusercontent.com/assets/1309249/11073192/b86818f0-87e9-11e5-8cc2-8fe225f4f406.png) https://www.dropbox.com/s/8xa8ev1qyp8bqgr/anchor.design?dl=0

**Comment by Templarian** [comment]
[![anchor](https://materialdesignicons.com/icon/anchor)](https://materialdesignicons.com/icon/anchor)
