### ISSUE TITLE
Google Cardboard

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#823]
There's an official SVG icon:
https://www.google.com/design/spec-vr/interactive-patterns/setup.html#setup-entering-exiting

But it's not fully pixel-perfect. I slightly changed the scale and repositioned the circles a bit to make it a bit sharper:

![cardboard](https://cloud.githubusercontent.com/assets/1309249/11075141/eb3ab490-87f3-11e5-803c-f1ed8c3e675e.png) Original icon
![cardboard2](https://cloud.githubusercontent.com/assets/1309249/11075139/eb376948-87f3-11e5-94b8-1849275d1114.png) Minor adjustment for better pixel perfection
![cardboard3](https://cloud.githubusercontent.com/assets/1309249/11075140/eb39bbee-87f3-11e5-86bf-826cbfdc2fb0.png) Minor adjustments and 2px corner radius

The 3rd version looks good at 24px, but it actually less recognizable at larger sizes. Thus, I recommend to add the 2nd version.

https://www.dropbox.com/s/9igp11wzg5r805u/cardboard.design?dl=0
https://www.dropbox.com/s/6t2kajt7s9wk70j/cardboard2.design?dl=0
https://www.dropbox.com/s/rd30e5rpcg1lky9/cardboard3.design?dl=0

**Comment by Templarian** [comment]
[![google-cardboard](https://materialdesignicons.com/icon/google-cardboard)](https://materialdesignicons.com/icon/google-cardboard)
