### ISSUE TITLE
xing, -circle, -box

### ISSUE THREAD

**Issue by matthew2402** [Templarian/MaterialDesign#824]

**Comment by Templarian** [comment]
What?

**Comment by CoDEmanX** [comment]
https://www.xing.com/ <-- that

**Comment by CoDEmanX** [comment]
![xing](https://cloud.githubusercontent.com/assets/1309249/11132202/ec1fa090-898e-11e5-8c11-a78511219a66.png)
![xing-box](https://cloud.githubusercontent.com/assets/1309249/11132203/ec390a9e-898e-11e5-89aa-9dcbe8866746.png)
![xing-circle](https://cloud.githubusercontent.com/assets/1309249/11132204/ec4a1b72-898e-11e5-87e1-dc7ff1d13809.png)

The circle version doesn't convince me...

**Comment by matthew2402** [comment]
They look really nice. Thanks!
Yeah I agree the circle version does not look very good.

**Comment by Templarian** [comment]
[![xing](https://materialdesignicons.com/icon/xing)](https://materialdesignicons.com/icon/xing) [![xing-box](https://materialdesignicons.com/icon/xing-box)](https://materialdesignicons.com/icon/xing-box) [![xing-circle](https://materialdesignicons.com/icon/xing-circle)](https://materialdesignicons.com/icon/xing-circle)
