### ISSUE TITLE
Place add/remove

### ISSUE THREAD

**Issue by joeyps** [Templarian/MaterialDesign#825]
Hello! Is there an icon for place add or remove? I need to include into my itinerary app. The icon might look like a marker and a plus sign next to it.
Thank you!

**Comment by CoDEmanX** [comment]
Could be added I guess, but I would consider to use generic add/remove icons and use the map marker icon somewhere else (e.g. in headline).

**Comment by CoDEmanX** [comment]
Looks odd if both elements overlap (even if it's just a bit):
![map-marker-plus-overlapping](https://cloud.githubusercontent.com/assets/1309249/11158925/cd7b3a50-8a5b-11e5-8071-6375b343ae6d.png)

Looks much better without overlap IMO:
![map-marker-plus](https://cloud.githubusercontent.com/assets/1309249/11158930/da7bc576-8a5b-11e5-869b-68d338fa35f1.png) ![map-marker-minus](https://cloud.githubusercontent.com/assets/1309249/11158929/da7b26de-8a5b-11e5-99e2-a88997a4355b.png)

**Comment by joeyps** [comment]
This icon has been added to google material design icons
https://design.google.com/icons/#ic_add_location

**Comment by Templarian** [comment]
Not really a fan of the official one, it kind of doesn't follow the style of the others. Hmm... I wouldn't mind adding @CoDEmanX's +/- ones.

What do you guys think?

**Comment by OlsonDev** [comment]
> it kind of doesn't follow the style of the others

I like all of them (official and @CoDEmanX's non-overlap ones) but I don't know what you mean by this; there are plenty of official icons with the + integrated into the core icon.

**Comment by Templarian** [comment]
[![map-marker-plus](https://materialdesignicons.com/icon/map-marker-plus)](https://materialdesignicons.com/icon/map-marker-plus) [![map-marker-minus](https://materialdesignicons.com/icon/map-marker-minus)](https://materialdesignicons.com/icon/map-marker-minus)

@OlsonDev Yea, you're right looking at them there really isn't any consistency.
