### ISSUE TITLE
Wifi ruim

### ISSUE THREAD

**Issue by leoramosgomes** [Templarian/MaterialDesign#827]
Ajudaria muito se tivesse esse icone!

By: Leonardo Ramos

![wifimodificado fw](https://cloud.githubusercontent.com/assets/15372261/11101775/f320f046-889f-11e5-8563-949b0ae2435a.png)

**Comment by CoDEmanX** [comment]
A strikethrough variant would look like "wifi off", but you actually want "bad wifi" if Google translated that correctly. I actually submitted a set of wifi-related icons as part of #420:

![network](https://cloud.githubusercontent.com/assets/1309249/11103388/6774d9cc-88c2-11e5-9f7a-e36bea8bb34d.PNG)

Will see if @Templarian adds them.

**Comment by CoDEmanX** [comment]
Not a fan...
![wifi-off-variant](https://cloud.githubusercontent.com/assets/1309249/11769207/1f07d9ee-a1e2-11e5-9bec-748ad6f4ff66.png) https://www.dropbox.com/s/yqppfzv9x6yrj7m/wifi-off-variant.design?dl=0

**Comment by Templarian** [comment]
[![wifi-off](https://materialdesignicons.com/icon/wifi-off)](https://materialdesignicons.com/icon/wifi-off)
