### ISSUE TITLE
Bootstrap getting started guide and some accessibility tweaks

### ISSUE THREAD

**Issue by patrickhlauke** [Templarian/MaterialDesign#828]
https://materialdesignicons.com/bootstrap

A few suggestions for the examples, to increase their accessibility...

for button sizes, add `aria-label` if there's no descriptive text in the `<button>` and `aria-hidden` to the icon:

```
<button type="button" class="btn btn-default" aria-label="Profile">
    <i class="mdi mdi-account" aria-hidden="true"></i>
</button>
<button type="button" class="btn btn-default">
    <i class="mdi mdi-beaker" aria-hidden="true"></i>
    btn
</button>
```

for button group and button colors, again add `aria-hidden="true"` to the actual icons.

for tabs, the `role="presentation"` on the `<li>` elements is inappropriate  in isolation like that - either implement all remaining things like `role="tablist"`, `role="tab"` etc - see https://www.marcozehe.de/2013/02/02/advanced-aria-tip-1-tabs-in-web-apps/ - of just remove it for the purposes of the example there. Also, there needs to be some other non-visual way of identifying the current "active" link.

```
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#">
            <i class="mdi mdi-account" aria-hidden="true"></i>
            Home
            <span class="sr-only"> (current)</span>
        </a>
    </li>
</ul>
```

breadcrumbs - needs `aria-hidden`

```
<ol class="breadcrumb">
    <li>
        <a href="#">
            <i class="mdi mdi-home-modern" aria-hidden="true"></i>
            <span>Home</span>
        </a>
    </li>
    ...
</ol>
```

input group - the `<button>` needs some form of text/label like `aria-label`, and again `aria-hidden` on the icon

```
<div class="input-group">
    <input type="text" class="form-control" placeholder="Search...">
    <span class="input-group-btn">
        <button class="btn btn-default" type="button" aria-label="Search">
            <i class="mdi mdi-magnify" aria-hidden="true"></i>
        </button>
    </span>
</div>
```

input group addon - `aria-hidden` on the icon

```
<div class="input-group">
    <span class="input-group-addon">
        <i class="mdi mdi-tag" aria-hidden="true"></i>
    </span>
    <input type="text" class="form-control" aria-label="Tag">
</div>
```

nav - `aria-hidden` and some non-visual indication for the current page

```
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"  
                    data-toggle="collapse" data-target="#ex-navbar">
              <span class="sr-only">Toggle navigation</span>
              <i class="mdi mdi-menu" aria-hidden="true"></i>
          </button>
          <a class="navbar-brand" href="#">
              <i class="mdi mdi-package" aria-hidden="true"></i>
              Brand
            </a>
        </div>
        <div class="collapse navbar-collapse" id="ex-navbar">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home<span class="sr-only"> (current page)</span></a></li>
                ...
            </ul>
        </div>
    </div>
</nav>
```

list - `aria-hidden`

```
<ul class="list-group">
    <li class="list-group-item active">
        <span class="badge">42</span>
        <i class="mdi mdi-account" aria-hidden="true"></i>
        Cras justo odio
    </li>
    ...
</ul>
```

**Comment by Templarian** [comment]
Thanks. Planning to work through some bug fixes and icon stuff this weekend. Will work to get this in.

**Comment by patrickhlauke** [comment]
just a ping ... i see some of the things were addressed, but there's still outstanding ones. need a hand getting the last few issues here resolved?

**Comment by Templarian** [comment]
Yes, thanks for the bump. I'm spending this weekend working on site tweaks so will work to get this in.

**Comment by Templarian** [comment]
Page is now updated with all the changes. Inline and in the examples. Thanks and sorry that took so long to get in.

Definitely let me know if you see any other issues and I'll try and get them in much quicker!

**Comment by patrickhlauke** [comment]
Great stuff. Sorry if i gave the impression that i was hassling you there...just that i did a run through my various open issues/PRs and wondered if you needed any help :+1: 

and to be super nitpicky, one last outstanding tiny issue in your code examples:

> for tabs, the `role="presentation"` on the `<li>` elements is inappropriate in isolation like that

```
<ul class="nav nav-tabs">
    <li class="active">
        <a href="#">
            <i class="mdi mdi-account" aria-hidden="true"></i>
            Home
            <span class="sr-only"> (current)</span>
        </a>
    </li>
</ul>
```
