### ISSUE TITLE
Circle and Polygon vectors

### ISSUE THREAD

**Issue by yoannpe** [Templarian/MaterialDesign#829]
Hi, 

I'm currently using the 'vector-square' icon and would like to know if it would be possible to add 'vector-circle' and 'vector-polygon'. Exactly the same style but in different shapes.

Thanks a lot ;)

**Comment by CoDEmanX** [comment]
I wonder where the small outlined squares would go in case of the circle...

**Comment by yoannpe** [comment]
Maybe: Top - Left - Bottom - Right ?

**Comment by CoDEmanX** [comment]
Opinions, please!
![vector-circle](https://cloud.githubusercontent.com/assets/1309249/11132013/ce415aba-898d-11e5-83b4-a37fdc19b8d4.png) ![vector-circle2](https://cloud.githubusercontent.com/assets/1309249/11132012/ce3e8e7a-898d-11e5-8900-3dca2d4fd0d9.png) ![vector-polygon](https://cloud.githubusercontent.com/assets/1309249/11132014/ce57fd4c-898d-11e5-86ba-221fea749049.png) ![vector-polyline](https://cloud.githubusercontent.com/assets/1309249/11132015/ce5b08c0-898d-11e5-9025-b09e2b5eb229.png) ![vector-triangle](https://cloud.githubusercontent.com/assets/1309249/11132016/ce659510-898d-11e5-94fb-62397a2ff277.png) ![vector-line](https://cloud.githubusercontent.com/assets/1309249/11132135/8a43d472-898e-11e5-8cc2-52418fd65c31.png)

**Comment by yoannpe** [comment]
That's perfect! Thanks :D

**Comment by Templarian** [comment]
These look great, thanks for including 2 version of the circle (rotated it before importing).

[![vector-circle](https://materialdesignicons.com/icon/vector-circle)](https://materialdesignicons.com/icon/vector-circle) [![vector-circle-variant](https://materialdesignicons.com/icon/vector-circle-variant)](https://materialdesignicons.com/icon/vector-circle-variant) [![vector-line](https://materialdesignicons.com/icon/vector-line)](https://materialdesignicons.com/icon/vector-line) [![vector-polygon](https://materialdesignicons.com/icon/vector-polygon)](https://materialdesignicons.com/icon/vector-polygon) [![vector-polyline](https://materialdesignicons.com/icon/vector-polyline)](https://materialdesignicons.com/icon/vector-polyline) [![vector-triangle](https://materialdesignicons.com/icon/vector-triangle)](https://materialdesignicons.com/icon/vector-triangle)

**Comment by skllcrn** [comment]
Digging these @CoDEmanX, I'm struggling to have them render sharp in the browser at @1x though. Is there anything I can do to make them render as sharp as possible besides going larger than 24x24px?

**Comment by CoDEmanX** [comment]
The rectangle outlines should be sharp, so should the vertical and horizontal lines, but the slant lines can never be sharp.
