### ISSUE TITLE
correct attribution

### ISSUE THREAD

**Issue by DEllingsworth** [Templarian/MaterialDesign#83]
There might be an issue with the map-marker-off.  It shows as coming from Google, however, I can't find that icon in the official Google Material Design specs.  Can anyone confirm that it comes from the official Google Material Design? https://github.com/google/material-design-icons

I want to be sure of the license in case I need to provide attribution.

![image](https://cloud.githubusercontent.com/assets/1970713/5649550/bf1274ec-9664-11e4-85e8-14fb9acbb4b3.png)

**Comment by Templarian** [comment]
Interesting... I think I forgot to switch accounts when I imported that one. Probably from me. I'll remove it from theirs and transfer it to mine tonight.

Thanks.

**Comment by Templarian** [comment]
Fixed. Thanks again!
