### ISSUE TITLE
"call-split" icon is not working how it would.

### ISSUE THREAD

**Issue by becarlos** [Templarian/MaterialDesign#830]
After install MDI via bower and trying to include some icons I realize that the *"call-split"* can't be include as others.

*"mdi mdi-account-convert" works.*
*"mdi mdi-ticket" works.*
__*"mdi mdi-call-split" is broken.*__

**Comment by Templarian** [comment]
Not a bug. https://materialdesignicons.com/history

It didn't make it into the last release. It will be in the next release, working this weekend to add more icons.
