### ISSUE TITLE
Create icon AI, Robot, Machine, Machine Learning

### ISSUE THREAD

**Issue by greefeet** [Templarian/MaterialDesign#832]
- [ ] Bot_Wait
- [ ] Bot_Doing
- [ ] Bot_Warning
- [ ] Bot_Error
- [ ] Bot_Thinking

:+1:

**Comment by GreenTurtwig** [comment]
[![](https://materialdesignicons.com/icon/robot)](https://materialdesignicons.com/icon/robot)

**Comment by JamesCoyle** [comment]
Closing this out as I feel it's a bit niche and there hasn't been any ideas yet.
