### ISSUE TITLE
Delivery Icon

### ISSUE THREAD

**Issue by mirabalj** [Templarian/MaterialDesign#833]
I think it may be as "bike" icon with a box behind.

**Comment by CoDEmanX** [comment]
Something more generic:
![packet-send](https://cloud.githubusercontent.com/assets/1309249/11160613/4bfcb86c-8a6c-11e5-8a84-7ed910bd6ce1.png)
![truck-delivery](https://cloud.githubusercontent.com/assets/1309249/11160614/4bfd075e-8a6c-11e5-879c-c22ddb31db75.png)

**Comment by CoDEmanX** [comment]
One more:
![package-send](https://cloud.githubusercontent.com/assets/1309249/11190269/fa6c0720-8c94-11e5-97fc-33c67ee8e778.png)

**Comment by Templarian** [comment]
Not the last one (too many lines), but the top two would be fine for inclusion.

**Comment by CoDEmanX** [comment]
Here you go:
https://www.dropbox.com/s/d88kn5cyfm3jva0/package-send2.design?dl=0
https://www.dropbox.com/s/6l429398kiy6lgp/truck-delivery.design?dl=0

I noticed the Expression Design creates a default layer, and I can't really delete it automatically. I hope that's not a big deal.

**Comment by Templarian** [comment]
[![cube-send](https://materialdesignicons.com/icon/cube-send)](https://materialdesignicons.com/icon/cube-send) [![truck-delivery](https://materialdesignicons.com/icon/truck-delivery)](https://materialdesignicons.com/icon/truck-delivery)

**Comment by CoDEmanX** [comment]
**cube**-send? :smile:
