### ISSUE TITLE
Node.js icon

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#834]
Official logo:

![Node.js](https://upload.wikimedia.org/wikipedia/commons/d/d9/Node.js_logo.svg)

The octagon at the very right seems suitable, although it is very thin.
I tried to make it heavier, but it still doesn't comply to the MD rules and distorts the original logo:

![nodejs2](https://cloud.githubusercontent.com/assets/1309249/11159838/8ed28210-8a63-11e5-91da-8c23616fcb61.png)

**Comment by Templarian** [comment]
Logos are not all going to conform to the MD spec. I think the version you have looks nice enough to be included.

**Comment by CoDEmanX** [comment]
![nodejs](https://cloud.githubusercontent.com/assets/1309249/11166428/45b4a768-8b33-11e5-8887-6ff6cbf4e39f.png) https://www.dropbox.com/s/8od6103qn8ewgtt/nodejs.design?dl=0
![nodejs2](https://cloud.githubusercontent.com/assets/1309249/11159838/8ed28210-8a63-11e5-91da-8c23616fcb61.png) https://www.dropbox.com/s/2rvd8burgfdu9mn/nodejs2.design?dl=0

**Comment by Templarian** [comment]
[![nodejs](https://materialdesignicons.com/icon/nodejs)](https://materialdesignicons.com/icon/nodejs)
