### ISSUE TITLE
dog icon for material design icons

### ISSUE THREAD

**Issue by nikfrank** [Templarian/MaterialDesign#835]
there's:

cat
pig
alien
ghost
fish
bird
php

why no dog?

**Comment by CoDEmanX** [comment]
Not sure if calling aliens animals is discrimination according to the shadows proclamation, but I can't find an alien icon?! Also, php is for sure no animal, neither is the twitter logo IMO. We do have an owl however.

Valid request nonetheless.

**Comment by Templarian** [comment]
I agree.

A dog is an animal.

**Comment by CoDEmanX** [comment]
Actually a duplicate of #736
