### ISSUE TITLE
Humidity Icon

### ISSUE THREAD

**Issue by happyleavesaoc** [Templarian/MaterialDesign#837]
For weather, or for home automation sensors. There are already thermostat and thermometer icons.

**Comment by CoDEmanX** [comment]
Maybe like this?
![water-percent](https://cloud.githubusercontent.com/assets/1309249/11190156/72744b5c-8c94-11e5-8bf2-8b86245b0355.png) https://www.dropbox.com/s/9adn0ppnaon6yl4/water-percent.design?dl=0

**Comment by happyleavesaoc** [comment]
That seems pretty good to me! It evokes the `water` icon but clearly represents a percentage quantity.

**Comment by Templarian** [comment]
[![water-percent](https://materialdesignicons.com/icon/water-percent)](https://materialdesignicons.com/icon/water-percent)
