### ISSUE TITLE
Icons suggestion: "Clock In" and "Clock Out" icons

### ISSUE THREAD

**Issue by AreaNovi** [Templarian/MaterialDesign#838]

**Comment by CoDEmanX** [comment]
Not sure what you mean, please post an example image.

**Comment by AreaNovi** [comment]
Clock In is when someone begins his shift at work
Clock Out is when someone ends his shift at work
Attached an image that can give you the meaning.

This is my first time I suggest an icon. If it will be done, will I be
notified? And under what kind of licence could I use it?
Thank you

[image: example.jpg]

**Comment by CoDEmanX** [comment]
GitHub doesn't support attachments if you use email replies. Please upload it on the website (you can do that with your mobile phone too, if you use the desktop version of the size > link at the very end of the mobile site, right side).

I understand what you want them for. Maybe something generic works, but should have a look at your example first.
License is SIL open font license 1.1:
https://github.com/Templarian/MaterialDesign/blob/master/license.txt

**Comment by AreaNovi** [comment]
![example](https://cloud.githubusercontent.com/assets/13867962/11184999/d93ea522-8c7a-11e5-8cce-8746fc19e3a8.jpg)

**Comment by AreaNovi** [comment]
I hope the picture can help.
Thanks

**Comment by CoDEmanX** [comment]
What do you think about these experiments?

1. ![clock-start](https://cloud.githubusercontent.com/assets/1309249/11189955/7345b6fc-8c93-11e5-9f5c-fc2b34c2e5e0.png) ![clock-end](https://cloud.githubusercontent.com/assets/1309249/11189956/734af81a-8c93-11e5-86de-dd21de0fdb16.png)
2. ![clock-end3](https://cloud.githubusercontent.com/assets/1309249/11189974/878e0768-8c93-11e5-8c28-01ed74fa7482.png) ![clock-start2](https://cloud.githubusercontent.com/assets/1309249/11189975/878f0f96-8c93-11e5-8215-a11794aedcc8.png)
3. ![clock-start3](https://cloud.githubusercontent.com/assets/1309249/11189982/920b187a-8c93-11e5-934f-f3fda80e082a.png) ![clock-end3](https://cloud.githubusercontent.com/assets/1309249/11189983/922a2774-8c93-11e5-96a3-01a448749c1a.png)
4. ![clock-start4](https://cloud.githubusercontent.com/assets/1309249/11189996/9c505598-8c93-11e5-9e2a-c332c0b68483.png) ![clock-end4](https://cloud.githubusercontent.com/assets/1309249/11189997/9c51498a-8c93-11e5-829e-b8784f3a0659.png)

**Comment by AreaNovi** [comment]
They are very nice. I like more this model
![920b187a-8c93-11e5-934f-f3fda80e082a](https://cloud.githubusercontent.com/assets/13867962/11190784/e166c136-8c97-11e5-910e-7cdc8381d6b8.png)
but it would give me a better sense of IN and OUT with vertical arrows.
I would like to use them for making floating buttons. The clock in with a green background and the clock out with a red background.

**Comment by CoDEmanX** [comment]
How about the following? (the positioning is slightly different in both groups)

<span>5.</span> ![clock-in-b](https://cloud.githubusercontent.com/assets/1309249/11191454/a75db2a2-8c9b-11e5-947d-769fc9291319.png) ![clock-out-b](https://cloud.githubusercontent.com/assets/1309249/11191455/a7603f5e-8c9b-11e5-9ea5-0ebb138b3584.png)
6. ![clock-in](https://cloud.githubusercontent.com/assets/1309249/11191465/b3903c0c-8c9b-11e5-8b81-0e763dd3f78c.png) ![clock-out](https://cloud.githubusercontent.com/assets/1309249/11191466/b393c430-8c9b-11e5-8d61-b363c1914799.png)

**Comment by AreaNovi** [comment]
The couple number 5 seems all right! It's very good!
Thanks

**Comment by AreaNovi** [comment]
Are you going to add the icons here (https://materialdesignicons.com/)? Like the others, with the possibility to get them in 48x48?

**Comment by Templarian** [comment]
@AreaNovi Yea, I'll be importing them shortly. @CoDEmanX These look nice. Any ideas on the naming?

**Comment by AreaNovi** [comment]
I'd call them Clock-In and Clock-Out, like what they want to represent.

**Comment by Templarian** [comment]
Makes sense. I'd like to add 3 also from above as `*-variants` @CoDEmanX. So the svg's for those also would be nice.

**Comment by AreaNovi** [comment]
OK. Thank you very much

**Comment by CoDEmanX** [comment]
https://www.dropbox.com/s/pzi5kla6lxhov8l/clock-start3.svg?dl=0
https://www.dropbox.com/s/xdlssy3azzatx22/clock-end3.svg?dl=0
https://www.dropbox.com/s/nw80jgv9l8pj9mq/clock-in-b.svg?dl=0
https://www.dropbox.com/s/oze4s3s9pdkut8c/clock-out-b.svg?dl=0

**Comment by Templarian** [comment]
[![clock-in](https://materialdesignicons.com/icon/clock-in)](https://materialdesignicons.com/icon/clock-in) [![clock-out](https://materialdesignicons.com/icon/clock-out)](https://materialdesignicons.com/icon/clock-out) [![clock-start](https://materialdesignicons.com/icon/clock-start)](https://materialdesignicons.com/icon/clock-start) [![clock-end](https://materialdesignicons.com/icon/clock-end)](https://materialdesignicons.com/icon/clock-end)
