### ISSUE TITLE
Icon suggestion: User settings

### ISSUE THREAD

**Issue by seanmcne** [Templarian/MaterialDesign#841]
Both would be great options to have out there: 
- Person icon with a gear 
- a folder icon with a "person" within the folder, and lines on the folder like 'notes'

**Comment by CoDEmanX** [comment]
I remember from another experiment, that there's very little space if you use the human upper body icon as base for an icon. A cog / gear will probably not fit, but 3 vertical dots would (and they are used to depict "settings" in a couple other stock Google icons).

A folder with a user subtracted seems like another interesting icon, not sure if there's enough space for a legible icon at 24 square pixels...

**Comment by CoDEmanX** [comment]
@seanmcne: Do they work for you?

[![folder-account](https://materialdesignicons.com/icon/folder-account)](https://materialdesignicons.com/icon/folder-account)
[![account-settings](https://materialdesignicons.com/icon/account-settings)](https://materialdesignicons.com/icon/account-settings)
[![account-settings-variant](https://materialdesignicons.com/icon/account-settings-variant)](https://materialdesignicons.com/icon/account-settings-variant)

**Comment by seanmcne** [comment]
These are great, thanks!!!
