### ISSUE TITLE
Edit list

### ISSUE THREAD

**Issue by 4nd3250n** [Templarian/MaterialDesign#842]
Icon to represent that a list will be edited. Actions like add, delete, edit item...
Something like a list with a pencil.

**Comment by visionarycoder** [comment]
+ 1  I need an "edit" icon to go along with the add and delete icons that already exist.

**Comment by GreenTurtwig** [comment]
[![](https://user-images.githubusercontent.com/15905797/33996927-96c95032-e0da-11e7-8431-a3f8e9cfcb4f.png)](https://github.com/Templarian/MaterialDesign/files/1559510/playlist-edit.zip)

**Comment by Templarian** [comment]
[![playlist-edit](https://materialdesignicons.com/icon/playlist-edit)](https://materialdesignicons.com/icon/playlist-edit)
