### ISSUE TITLE
Icon Request - Incoming Shares & Outgoing Shares

### ISSUE THREAD

**Issue by KingSora** [Templarian/MaterialDesign#844]
I thought about something like the "share-variant"-icon with a arrow or something like this.

Explanation: Incoming Shares
Things someone has shares to you.

Explenation: Outgoing Shares
Things you shared to someone.

Best regards,
Sora

**Comment by PeterShaggyNoble** [comment]
I'd suggest using the standard [`share`](https://materialdesignicons.com/icon/share) icon and flipping it  for incoming shares. Other than that, I think this is a bit too specific for inclusion.
