### ISSUE TITLE
Barcode scan

### ISSUE THREAD

**Issue by echthard** [Templarian/MaterialDesign#847]
Just Like the credit-card-scan, but then with a barcode instead of a credit card inside the 'rectangle'.

![psx_20151119_195234](https://cloud.githubusercontent.com/assets/1309249/11280631/2878b5be-8ef7-11e5-86e4-931825591bed.jpg)

**Comment by CoDEmanX** [comment]
![barcode-scan](https://cloud.githubusercontent.com/assets/1309249/11291277/9623a85c-8f3e-11e5-9221-96955fe76e1b.png) https://www.dropbox.com/s/tos2kdp61nqcyqb/barcode-scan.design?dl=0
![qrcode-variant-scan](https://cloud.githubusercontent.com/assets/1309249/11291278/9626525a-8f3e-11e5-8bc8-e3e6b737047d.png) qr code version, but too tiny
![qrcode-variant-scan2](https://cloud.githubusercontent.com/assets/1309249/11291360/7daeb54a-8f3f-11e5-913a-01ce2bcbd980.png) some tweaks... https://www.dropbox.com/s/yzira2qd08ofspc/qrcode-variant-scan2.design?dl=0

**Comment by Templarian** [comment]
[![qrcode-scan](https://materialdesignicons.com/icon/qrcode-scan)](https://materialdesignicons.com/icon/qrcode-scan) [![barcode-scan](https://materialdesignicons.com/icon/barcode-scan)](https://materialdesignicons.com/icon/barcode-scan)

**Comment by echthard** [comment]
Thank you.

May I ask how this icon can be available in Android-Iconics?

I requested an update after these icons were added on https://materialdesignicons.com but they aren't available in the Android-Iconics lib. https://github.com/mikepenz/Android-Iconics/issues/106

**Comment by Templarian** [comment]
The last release was `1.3.41` and did not contain that new icon most likely. You can view the history page to see which icons were added after a release. Other projects that use the webfont won't be updated until after this project does a release.

https://materialdesignicons.com/history

There is no timeline at the moment for the next webfont release.
