### ISSUE TITLE
New Message Icon

### ISSUE THREAD

**Issue by niteshkhatri** [Templarian/MaterialDesign#848]
Hi, I think having a new message icon will be great.

I think below icon with either a plus at the top right of may in the centre 

![image](https://cloud.githubusercontent.com/assets/7664984/11277965/df5d3dc4-8f0e-11e5-9ca0-9787d3034e6b.png)

**Comment by CoDEmanX** [comment]
https://materialdesignicons.com/icon/comment-plus-outline ?

**Comment by niteshkhatri** [comment]
Comment-plus-outline is good but the outer shape is different. The message icon I am using in my app is the one I shared. I will appreciate it if you provide me the new icon in that shape.

**Comment by CoDEmanX** [comment]
![message-plus](https://cloud.githubusercontent.com/assets/1309249/11422070/47f2aae8-9439-11e5-85f2-3bdf83b09796.png) ?

Adding a plus to the existing message icon doesn't really work...
![message-plus2](https://cloud.githubusercontent.com/assets/1309249/11422071/47f304a2-9439-11e5-9abc-dcb6a56be32a.png)

**Comment by Templarian** [comment]
[![message-plus](https://materialdesignicons.com/icon/message-plus)](https://materialdesignicons.com/icon/message-plus)
