### ISSUE TITLE
Chat Icon

### ISSUE THREAD

**Issue by niteshkhatri** [Templarian/MaterialDesign#849]
Hi, I would like to have a chat icon. The icon shape should be like that of hangouts icon but without those double inverted comma symbols at the centre.

The icon may have three variants.
1. Solid icon - full colored icon.
2. Outline icon - just the outline and rest will be transparent.
3. Icon with plus at the centre or at the top right corner for new chat icon.

**Comment by CoDEmanX** [comment]
We do have the following icon:
https://materialdesignicons.com/icon/forum

**Comment by niteshkhatri** [comment]
I saw that too. I want something in hangout shape.

**Comment by CoDEmanX** [comment]
Hangout would be a brand icon, and just the base shape doesn't seem very recognizable. And aside, it's basically a rounded version of the material-y shape we have in the comment icons:
https://materialdesignicons.com/icon/comment

**Comment by PeterShaggyNoble** [comment]
See @CoDEmanX's comment on #1159 for why this wouldn't work.
