### ISSUE TITLE
Queue / Message Queue Icon

### ISSUE THREAD

**Issue by mieliespoor** [Templarian/MaterialDesign#852]
Hello,

I would be super great to have an icon to represent a queue (message/storage).

Apologies for not supplying any samples, but I haven't been able to find any real examples yet.

Thanks,
MS

**Comment by PeterShaggyNoble** [comment]
[`comment-multiple`](https://materialdesignicons.com/icon/comment-multiple) or one of its variants should do the job here, given the correct context. If not, please try to come up with an example and we'll revisit this issue.
