### ISSUE TITLE
Chemical weapon symbol

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#853]
Since we have the symbols for nuclear and biological hazards, there's still the C left in the alphabet of weapons of mass destruction...

1. ![chemical-weapon](https://cloud.githubusercontent.com/assets/1309249/11300691/57c33e1c-8f91-11e5-81c5-6883254b574c.png)
2. ![chemical-weapon2](https://cloud.githubusercontent.com/assets/1309249/11300692/57c429f8-8f91-11e5-82ac-6e828c8fd69a.png)
3. ![chemical-weapon3](https://cloud.githubusercontent.com/assets/1309249/11300693/57c45ae0-8f91-11e5-9a59-6b307ceca61b.png)
4. ![chemical-weapon4](https://cloud.githubusercontent.com/assets/1309249/11300690/57c2bfbe-8f91-11e5-9bab-720186d56dee.png)

I think 3 is the most legible.

**Comment by Templarian** [comment]
Agreed `3` is the best out of the 4.

**Comment by CoDEmanX** [comment]
https://www.dropbox.com/s/vthq7kd5fl6t674/chemical-weapon3.design?dl=0

**Comment by Templarian** [comment]
[![chemical-weapon](https://materialdesignicons.com/icon/chemical-weapon)](https://materialdesignicons.com/icon/chemical-weapon)
