### ISSUE TITLE
Suggestion: musical symbols

### ISSUE THREAD

**Issue by PhilPJL** [Templarian/MaterialDesign#855]
Sharp, double sharp, flat, double flat, natural, etc...

**Comment by Templarian** [comment]
Probably get to these as we update #783.

**Comment by CoDEmanX** [comment]
Hm, I wonder if a sharp should be grid aligned, or if one could just use https://materialdesignicons.com/icon/pound ...

**Comment by PhilPJL** [comment]
the pound (known as hash in UK) looks good for a sharp.  You could add aliases 'hash' and 'sharp'.

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #1036
