### ISSUE TITLE
Request: More Media Playback Icons

### ISSUE THREAD

**Issue by IanSav** [Templarian/MaterialDesign#857]
Hi,

Could we please have some more media transport icons in the same design style as the current PLAY (play), PAUSE (pause), STOP (stop), REW (rewind), FF (fast-forward), PREV (skip-previous), NEXT (skip-next) and EJECT (eject).  I have included a list of the icons I would like added together with some sample images to indicate the type of icon I am requesting.  If there are any I have missed then I would welcome those as well.   ;)

In particular I am looking for...
PLAY/PAUSE:
![play_pause](https://cloud.githubusercontent.com/assets/6904736/11319529/637ab04e-90ce-11e5-9dfb-a52ee52a7567.png)
PLAY REVERSE:
![play_reverse](https://cloud.githubusercontent.com/assets/6904736/11319532/6383fa96-90ce-11e5-9ce4-19381eab8532.png)
STEP FORWARD:
![step_forward](https://cloud.githubusercontent.com/assets/6904736/11319531/63816c40-90ce-11e5-812b-5110ee36b3ea.png)
STEP BACKWARD
![step_backward](https://cloud.githubusercontent.com/assets/6904736/11319530/637f1c4c-90ce-11e5-9046-5fd6e4d196da.png)
PREV TITLE:
![title_back](https://cloud.githubusercontent.com/assets/6904736/11319527/63759172-90ce-11e5-8293-9ce9360586d0.png)
NEXT TITLE:
![title_forward](https://cloud.githubusercontent.com/assets/6904736/11319528/63779db4-90ce-11e5-82a5-8beba7629000.png)
MEDIA SHUFFLE:
![media_shuffle](https://cloud.githubusercontent.com/assets/6904736/11319533/63ab6bb2-90ce-11e5-9cf8-42adda978bf7.png)
RECORD:
![media_record](https://cloud.githubusercontent.com/assets/6904736/11319552/2400e77a-90cf-11e5-9a98-f37d2e97d6bc.png)
(This could also have a variant of "REC" within a circle.)

I also wouldn't mind if we could have the information "i" that is often used on TVs and PVRs/ DVRs remote controls:
![info](https://cloud.githubusercontent.com/assets/6904736/11319561/64f5e9c4-90cf-11e5-932a-ec4d5d85bfae.png)

As you could imagine these extra icons would be most useful for remote control type applications.

Thank you, in advance, for considering this request.

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Good proposal. Regarding Shuffle: the material version of that does exist
https://materialdesignicons.com/icon/shuffle
I wouldn't mind an alternative though.
As for record: does the generic circle icon work? (about the same size like the other media transport icons?)
That i icon would translate to material design line  https://materialdesignicons.com/icon/information-outline without the circle outline... Or we could treat it as a brand icon and keep it as is, hrm...

**Comment by IanSav** [comment]
I requested the alternative shuffle in the belief that it would be more recognisable in a media player context.

As for a RECORD icon I was looking for something that would be immediately recognisable in the same media player context.  If the icons were coloured then all we need is make a circle red and it would probably be recognised.  In a black and white font/icon context I suspect that "REC" in a circle may be the better way to go.  All the versions could be added as alternates for each other and then the app designer can choose the version most appropriate in their context.   ;)

I hope the suggestion is picked up and accepted for inclusion.   ;)

**Comment by CoDEmanX** [comment]
![record](https://cloud.githubusercontent.com/assets/1309249/11321734/9f278e7c-90ca-11e5-94eb-f6d1e0c50a60.png) ![record2](https://cloud.githubusercontent.com/assets/1309249/11321730/6e75e5c6-90ca-11e5-9071-c18b9b5e092f.png) ![record3](https://cloud.githubusercontent.com/assets/1309249/11321729/6e75add6-90ca-11e5-9883-1bf6ed79f8e6.png) ![play](https://cloud.githubusercontent.com/assets/1309249/11321731/6e76fef2-90ca-11e5-9bc4-e0b6a4cfbb37.png) ![stop](https://cloud.githubusercontent.com/assets/1309249/11321728/6e731f4e-90ca-11e5-9604-e0eae72a1477.png) 

I think just the circle in a similar size to the play and stop icons is the best solution here. "REC" doesn't fully fit at that circle size, thus I created a 3rd variant with a 1px greater diameter. It is a bit off-center due the increased sized, but it doesn't seem too bad if put next to the other media transport icons.

**Comment by IanSav** [comment]
Hi CoDEmanX,

I agree that the larger circle with REC does work better.  What happens if you grow the circle by 2px instead?  It should centre better.   ;)

Making all the media control icons a little larger (2px) may have some side benefits.  This extra space could come into play when the larger icons get created.  My requested SHUFFLE, PLAY/PAUSE, PREV TITLE and NEXT TITLE could all benefit from a larger base size.  :)

Thank you for the mock ups, discussion and support.

Regards,
Ian.

**Comment by CoDEmanX** [comment]
If I added another pixel to the diameter, then the text wouldn't be centered anymore (as seen in the 2nd icon, just imagine a larger circle).

The current icons are stock Google icons, they shouldn't be changed. There should be enough room for the other icons you requested, just a labeled record button is a bit of a problem.

![play-previous2](https://cloud.githubusercontent.com/assets/1309249/11321814/5beb3480-90cd-11e5-81d2-1132817eea05.png) non-overlapping, narrower triangles
![play-previous](https://cloud.githubusercontent.com/assets/1309249/11321813/5beaf858-90cd-11e5-98da-b6b433e20cbf.png) overlapping, wider triangles
![step-backward](https://cloud.githubusercontent.com/assets/1309249/11321815/5bebeb96-90cd-11e5-854a-cb1b2d3ddccb.png) bar has same width as the pause icon - is that a good thing?
![play-stop](https://cloud.githubusercontent.com/assets/1309249/11321816/5bec75ac-90cd-11e5-9f81-2e2c908b96f7.png) should the bars be wider and the triangle narrower instead?

**Comment by IanSav** [comment]
Hi CoDEmanX,

The proposed icons already look great.

Given the "rewind" and "fast-forward" icons don't overlap I suspect that the non overlapping version of the PREV TITLE / NEXT TITLE may be more in keeping with the design style.

The STEP BACKWARD icon spacing seems appropriate given that this function normally means step a frame and then pause.  ;)

For the PLAY/PAUSE what do you thing about making the triangle slightly narrower so that you can introduce a small space between the elements?

As for the RECORD icon I will bow to your knowledge of how this all goes together.  I am more or less an end user asking for some icons to be added so that the IR remote control developers out there have some better and more complete image sets with which to work.   :)

My comments are purely suggestions and not requests or demands.  ;)  You guys work with this stuff all the time and know what look will work better in different environments, sizes and colours.  ;)

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Thanks for the feedback.

![play-stop2](https://cloud.githubusercontent.com/assets/1309249/11321883/a841a884-90d0-11e5-9a10-3f1531304cf9.png) like this? Or an even wider gap?

If @Templarian is fine with it, we can probably add both record icons (1 and 3). I would favor the first and color it red if necessary. Material design is about simplification, and the simpler the shape the better - even if it hurts understandability a little. In the right context, it should be self-explanatory again.

Will give the shuffle icon a shot tomorrow.

**Comment by IanSav** [comment]
Hi CoDEmanX,

This new PLAY/PAUSE looks good to me.  I don't think the gap needs to be too wide but can be if you think it would work better.  The gap simply indicates that the two icons are different elements.  If the triangle touches the vertical bar then the icon could mean NEXT (skip-next) and then PAUSE (pause).   :P 

As for play-reverse + pause, I don't know any media player that has this feature but it doesn't mean it isn't possible.  Having the icon ready to go could be a smart move.   ;)

The jump to start / end icons already exist as skip-previous and skip-next.   :)

Regards,
Ian.

**Comment by IanSav** [comment]
Hi CoDEmanX,

If you are looking for more icons to round out the media set then there are some more and new Google icons that could be imported.

From https://www.google.com/design/icons/ AV set for example: 
equalizer (for graphic equalizer controls)
fiber manual record (this is the same as the new solid circle RECORD icon you created above)
forward 10 (skip forward 10 seconds)
forward 30 (skip forward 30 seconds)
forward 5 (other handy skip numbers could be 15, 20, 60, 120, 180, 300 if they fit)
hd (high definition - there could also be a matching sd for standard definition)
high quality (high quality)
loop (loop playback)
replay 10 (skip backward 10 seconds)
replay 30 (skip backward 30 seconds)
replay 5 (other handy skip numbers could be 15, 20, 60, 120, 180, 300 if they fit)
snooze (set the snooze timer)
subtitles (video subtitles)

From the Content section we could also adapt the remove icon to make it a little thicker and then it could be coloured red, green, yellow or blue to represent the four colour buttons on most TV, DVR/PVR remotes.

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Most / all stock Google icons will be added to MDI, see #420.

Thanks for pointing out the fiber manual record icon. I checked the size, and it has 16px diameter. My record buttons have 14 or 15 respectively. Comparison:

![record3](https://cloud.githubusercontent.com/assets/1309249/11324009/39abd4d6-9124-11e5-94d6-dfb2ea2dffde.png) ![play](https://cloud.githubusercontent.com/assets/1309249/11324003/15f1742e-9124-11e5-810b-93e24b90db05.png) ![record](https://cloud.githubusercontent.com/assets/1309249/11324004/15f193d2-9124-11e5-8e98-2dbf51786542.png) ![stop](https://cloud.githubusercontent.com/assets/1309249/11324002/15f104d0-9124-11e5-8919-2fc3bb236e70.png) ![ic_fiber_manual_record_black_24px](https://cloud.githubusercontent.com/assets/1309249/11324007/22b4efc4-9124-11e5-8759-d3a268f0dee6.png)

The fiber icon is noticeably larger and stands out like a sore thumb IMO. Maybe we should add the fiber icon as fiber icon, a 14px diameter circle for as record icon, and another "REC" labeled icon similar to this one: http://www.google.com/design/icons/#ic_fiber_dvr

Maybe the base shape of that DVR icon could be added separately, to be used for the colored buttons of a remote control? Some RCs got circular buttons, so the record icon could actually work as well...

Unfortunately, the forward and replay icons are broken. The digits are heavily distorted, you just can't see it at 24px. I tried to recreate one of them, but it turned out to be almost impossible to read at the native resolution. Not sure how to continue. @Templarian?

**Comment by CoDEmanX** [comment]
Shuffle is tough to get right, the angle is too steep in my try: ![shuffe-variant](https://cloud.githubusercontent.com/assets/1309249/11324377/63298e32-9130-11e5-90e2-a2f2198ab456.png)
Might be better to use 3px stroke width...

**Comment by Templarian** [comment]
I think adding `record`, `record-text`, `play-pause`, `shuffle` (2px),, `play-pause` (with the space), `play-reverse`, `next-title`, `previous-title`.

We also need `play-1x`, `play-1-5x`, `play-2x`, `play-3x`.

Rec needs to be round, the 2nd to last comment before this one has the best one (1 and 3, both). I don't think we need another information icon.

**Comment by CoDEmanX** [comment]
I don't think there should be two versions of play-pause, just the one with the space should be fine. To get it in line with the other icons, one would actually need to move the nose of the triangle 0.5 pixels to the right... But that's not a big difference in the eye of the beholder. Probably not noticeable without a grid.

Shuffle 3px matches the visual weight of the existing media transport icons better than 2px IMO. Either way, I have no ready icon for either variant yet.

Should these play-#x icons be a triangle + label? Or double triangle (fast forward)? Interesting idea, but I'm afraid we would need more than 1-3x, because DVD players etc. usually double speed on every click (1x, 2x, 4x, 8x, 16x, some even 32x).

https://www.dropbox.com/sh/jaxp7rubag9ll18/AAAdsxr0fxqQMc4Ph8_dwKFQa?dl=0

**Comment by CoDEmanX** [comment]
@Templarian: I noticed that the existing media transport SVG icons in the repo aren't aligned to the grid. The design file icons are however...

We don't have a pure "i" icon for info btw., so we could actually add one. Maybe like this without the circle?
![info](https://cdn4.iconfinder.com/data/icons/meBaze-Freebies/128/info.png)

**Comment by IanSav** [comment]
Hi CoDEmanX,

As you have demonstrated, the fiber icon is *not* a good match for the media control buttons.  I withdraw the suggestion.  ;)

The DVR icon is not meant as a media control button so its shape/size doesn't matter.  This was suggested as another icon useful for device selection in remote control apps.

I am not too concerned about the issues with the forward or replay icon sets.  My Enigma2 based player uses the appropriate standard direct media control button together with adjacent text (e.g. >>x2, >>x3, >x1/2 etc).  This appears to be your suggestion as well.  If the icons don't work then don't bother with them.  :)  The alternative proposal could be adopted by those who want the speed indication.  The Google provided icons will probably arrive eventually when a future merge is performed for those people who want them.

The second (heavier) shuffle icon looks okay to me.  If you want to try a tweak then see how it looks if you reduce (just a little) the white spacing at the cross over.

Do the tweaked PREV TITLE, REW and PREV icons have any white space between the component parts?  If so I think there should be no white space.  In my opinion these are single / atomic elements so spacing should not be used.

The non circular RECORD icons look wrong, to me, as a menu control button.  They are useful as a status indicator to show that a recording is currently active.   :)

Regards,
Ian.

**Comment by IanSav** [comment]
Hi Templarian and CoDEmanX,

I would still like to see an additional / alternative INFO icon, as I suggested in the first post, as this image matches the INFO icon used on many remote controls.  (The proposed design is *very* common on TV and similar remote controls.)

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Hey IanSav,
the version I uploaded to my Dropbox is the following with spacing:
![play-previous3_96px](https://cloud.githubusercontent.com/assets/1309249/11328172/72766da6-9185-11e5-98c2-cde96ae04495.png)
I tried to match the style of the Google stock icons. Do you think this is better?
![play-previous2_96px](https://cloud.githubusercontent.com/assets/1309249/11328173/72774762-9185-11e5-84ae-6874ee32d182.png)
I have no strong opinion on the spacing and I'm unsure about the width of the bar.

**Comment by IanSav** [comment]
Hi CoDEmanX,

As a PREV TITLE icon the version with spacing looks wrong to me.  ( Sorry :) )  The second version  seems to have a very bold vertical bar.  Was this intended or an accident?

Regards,
Ian.

**Comment by CoDEmanX** [comment]
No problem. The thick bar was a middle ground between the width of one of the pause icon bars and the 2px bar from the skip icon. But I admit it looks out of place at 3px (see my previous comment, updated it several times in the last minutes).

So no spacing, thin bar is the way to go in your opinion? Seeing it next to the other icons, that's what I would prefer myself.

**Comment by IanSav** [comment]
Hi CoDEmanX,

Yeah, the thinner bar with no spacing looks very much like all the remote controls sitting on my desk (for comparison purposes ;) ).

The thinner bar works on all the icons except PAUSE.  On all my remote controls the PAUSE button lines are a little thicker than the rest.

By the way, I think you or someone suggested a REVERSE PLAY/PAUSE (<||) and PAUSE/PLAY (||>) icons and I didn't think I had ever seen one.  I just picked up my PS3 Blueray Remote control and there they are!  ( http://au.playstation.com/ps3/accessories/detail/item556472/Blu-ray-Disc-Remote-Control/ http://pisces.bbystatic.com/image2/BestBuy_US/images/products/3837/3837168_sa.jpg;canvasHeight=500;canvasWidth=200 )  There are a few other buttons on this remote you may want to consider adding.  :)

Regards,
Ian.

**Comment by CoDEmanX** [comment]
It's easier to see in this manual (vector graphics):
http://au.playstation.com/media/247938/BD%20Remote%20manual%20EN_vf1.pdf

What we miss: triangle (filled and outline) and the slow step icons:

![unbenannt](https://cloud.githubusercontent.com/assets/1309249/11328482/925b6f9e-918b-11e5-823c-511d892b6e9a.PNG)

I actually suggested ||< (as mirrored version of >||), not <||.

Thet step icons I created come with a single bar each (which corresponds to the inner symbols of those RC buttons). We could add a second bar to get the two outer symbols as well.

**Comment by IanSav** [comment]
Hi CoDEmanX,

On the actual remote control none of the buttons are in circles.  The circles in the image appear to represent the physical button on which the icon is printed.  If you don't mind the effort and/or people want all the media control icons in circles then that is okay by me.  I currently only want the plain versions but don't want to limit the options open to others.  :)

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Oh no, I don't want the circles, and also not combinations like two symbols found in one of the circles above. Just the individual symbols:

![unbenannt](https://cloud.githubusercontent.com/assets/1309249/11328646/c80f6d68-918e-11e5-967b-435f57422b93.PNG) ~= ![step-forward](https://cloud.githubusercontent.com/assets/1309249/11328649/d7cb29d6-918e-11e5-82a1-25ed84196925.png)

![unbenannt](https://cloud.githubusercontent.com/assets/1309249/11328652/ee76fbe2-918e-11e5-9de9-7cb26c4a8718.PNG) =? ![slow-step-forward2](https://cloud.githubusercontent.com/assets/1309249/11328673/4e273f98-918f-11e5-9f29-7490be2ab216.png) / ![slow-step-forward](https://cloud.githubusercontent.com/assets/1309249/11328674/4e28cb56-918f-11e5-8f41-e8c2ea1274cc.png)

**Comment by IanSav** [comment]
Hi CoDEmanX,

I didn't think much good about the slanted icon at the top left.   :P  I am happy not to see it in the media control set.

I propose that both <| + <|| and |> + ||> could both be valuable.  An app designer may choose <| or |> to mean slow motion backwards or forwards respectively while <|| or ||> could mean step a frame backwards or forwards respectively.

Also the idea of having all the extra options will allow users to select the icons and their meaning to match the icons used on the original remote control.  That is, the meaning and labels we suggest may not be how the icons actually end up being used.

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Yeah okay, fine with me. Do you have a preference / suggestion, how the <|| and ||> icons should look like? The two variants I posted above don't seem quite right compared to the |> icon... Maybe a little wider space between the bars and the triangle and the triangle a little narrower in turn?

**Comment by IanSav** [comment]
Hi CoDEmanX,

You pose an interesting conundrum,  If we use the frame advance icon on the top right of your recent post as the reference then when we look at the two samples of the alternate frame advance below it there is an obvious conflict in the thickness of the vertical bar elements of the image.

Visually the vertical lines of the bottom right icon are a little too light.  What do you think about thinning the vertical bar on the top icon to better match the left sample of the bottom two icons?

Realistically you have the tools and what appears to be a good eye for details so I don't want to ask / suggest too much in case I sway you in a direction that may not produce the results for which you can be rightfully be proud.

Perhaps, if you don't mind, we can see a sample panel of all the media control icons side-by-side or in a group so we can see how they match / blend with each other.  Perhaps we can have a few sizes to see how the look changes with size.

Hopefully we can soon arrive at something that is acceptable so you can lock the images down and we can move on to other categories,  (My though for the next category could be home automation icons.   ;)   Yeah I am on a remote control binge.  I am making suggestions to a remote control app developer who wants to stick to the Google and this icon library for all the images in the app.)

Regards,
Ian.

**Comment by CoDEmanX** [comment]
I guess I could put together a demo page to see multiple versions side-by-side along with the vanilla icons.

As for now, two more sets of step / step-slow:

![step-forward2b](https://cloud.githubusercontent.com/assets/1309249/11336978/b71e6152-91e9-11e5-8901-83a95480517d.png)
![step-forward-slow2b](https://cloud.githubusercontent.com/assets/1309249/11336980/b71f437e-91e9-11e5-95dc-c3900ec60b65.png)
![step-forward-slow2](https://cloud.githubusercontent.com/assets/1309249/11336977/b71cb9ec-91e9-11e5-9607-15f2f5a44bc5.png)
![step-forward2](https://cloud.githubusercontent.com/assets/1309249/11336979/b71efea0-91e9-11e5-82c1-dfedefce3d34.png)

The main difference between both sets is the space between the bars and the triangle.

I'm not a designer by any means btw., it's just a hobby :wink:

**Comment by IanSav** [comment]
Hi CoDEmanX,

Which do you prefer?

Seeing the samples side by side I think I prefer the version with less space between the elements.  With the larger gap my mind wandered between seeing the icon as a separate PAUSE icon adjacent to a PLAY icon.  With the smaller spacing it seemed more like a single element.

Regards,
Ian.

**Comment by CoDEmanX** [comment]
You're right, the 3rd icon looks like pause & play, but the 2nd more like a single symbol.
The wider distance between bar and triangle in the 4th one works for me though (looks like a single icon, maybe because just the bar doesn't have a special meaning on its own).

How do you feel about combining 2 and 4? Or would it be odd to do that? 4 on its own looks better than 1 IMO (what I expect it to look), 2 and 3 look both a bit alien to me...

**Comment by IanSav** [comment]
Hi CoDEmanX,

Earlier on I though you expressed a desire to make the spacing more uniform.  That said I would be very happy with the 2 and 4 combination.  As you say, the single vertical bar is meaningless on its own so can have a little more space.  Presumably if that approach is applied to all the icons in the set then we should arrive at a final and consistent design.

Lets see how all the icons go together in the proofs.   :)

Thank you for all your efforts on this request.  It really is appreciated.

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Here's a little sandbox:
http://codepen.io/anon/pen/BoezMw

**Comment by IanSav** [comment]
Hi CoDEmanX,

Thank you for the sandbox it is very easy the compare, resize and review the samples you provided.

* record3 - Looks good
* record - Looks good
* step-backward - Looks good
* step-forward - Looks good
* play-previous3 - Not my preferred version (the gap looks wrong)
* play-next3 - Not my preferred version (the gap looks wrong)
* play-stop - Looks good
* play-stop2 - Not my preferred version (the gap looks wrong)
* play-previous4 - Looks good
* play-next4 - Looks good
* pause - Looks good - how could it go wrong ;) - the wider spacing that lines up with the STOP is normal and expected for PAUSE
* stop - Looks good - a trusty old standard  :)
* play - Looks good - another classic  :P 
* skip-previous - Not my preferred version (the gap looks wrong)
* skip-next - Not my preferred version (the gap looks wrong)
* step-backward-slow2 - Not my preferred version (the gap looks wrong)
* step-backward-slow2b - Looks good
* step-backward2b - Looks good
* step-backward2 - Not my preferred version (the gap looks wrong)
* step-forward2 - Not my preferred version (the gap looks wrong)
* step-forward2b - Looks good
* step-forward-slow2b - Looks good
* step-forward-slow2 - Not my preferred version (the gap looks wrong)

It was interesting to note how all the icons look okay in the very small sizes but as the size increases so did my problem with the spacing.  In the remote control application where I hope these icons will be used ( https://play.google.com/store/apps/details?id=org.twinone.irremote&hl=en ) the sizes are large enough to trigger my reservations.

Regards,
Ian.

**Comment by CoDEmanX** [comment]
> skip-previous - Not my preferred version (the gap looks wrong)
> skip-next - Not my preferred version (the gap looks wrong)

Funny you say that, because these two are stock Google icons. The ones that turn red on hover are stock, so play / pause / stop / skip-next / skip-previous. We'll probably not change them.

> play-stop2 - Not my preferred version (the gap looks wrong)

So you changed your mind since https://github.com/Templarian/MaterialDesign/issues/857#issuecomment-158704058 ?

I agree that the 2b versions with a narrower gap look better, especially at larger sizes.

Toggled to a vertical layout, it seems to me like if some custom icons could use a little nudge to the right. The stock icons seem to have their visual center there.

**Comment by IanSav** [comment]
Hi CoDEmanX,

Sorry I am trying not to be inconsistent with my comments.  I also don't want to abuse your time and effort in helping me/us out.  However when using the really helpful sandbox and enlarging the image to the size it may be in the remote app it started to loose its appeal.  As I mentioned, when the icons are small the issues are not readily apparent.   ;)

Regards,
Ian.

**Comment by IanSav** [comment]
Hi,

Where are we on these media playback icons?  Is any more input discussion required?  What happens now?

Regards,
Ian.

**Comment by Templarian** [comment]
You annoy @Templarian and he eventually gets around to adding them.

**Comment by IanSav** [comment]
Hi Templarian,

I would rather not annoy anyone.   :)

I am also not sure if CoDEmanX has finished the development and refining of the new icons.

Hopefully this will come to a successful conclusion soon.  I can't wait to have all the new icons available in my preferred remote control app.

Regards,
Ian.

**Comment by Templarian** [comment]
Ha, yea, I'll have some time tomorrow to get them in ideally. Going to try and close out a bunch of the issues tomorrow. The next webfont release won't be fore a few weeks though.

**Comment by IanSav** [comment]
Hi Templarian,

That's okay.  I appreciate all the efforts of the contributors here.  I will let the IR Remote developer know to keep an eye open for the new icons so he can combine them with his pending update.

Thank you guys for all your efforts.

Regards,
Ian.

**Comment by IanSav** [comment]
Hi Templarian,

Will you bump this thread when the update is made / applied?

It looks like I will need to detect the availability of the new icons and let the IR Remote developer know that the update has been done so that he can access the new icons and deliver the program improvements that I was asking him to make.

Regards,
Ian.

**Comment by IanSav** [comment]
Hi,

Are we any closer to having the new media player icons added to the icon set?

Will all the media player icons be tagged with a tag like "media player" or something similar?

Regards,
Ian.

**Comment by Templarian** [comment]
I'll be working on these tonight. Busy weekend ate up my time.

**Comment by CoDEmanX** [comment]
Would be better if you could work on #420 instead (or some of the other contributions), because I want to tweak placement of the media transport still. Doesn't look quite right yet in vertical layouts.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history

I uploaded a few, we can always overwrite them. I think these ones looked the most consistent. Definitely can swap them out though.

**Comment by IanSav** [comment]
Hi Templarian,

Sorry for the delay in responding.  Things have been a bit hectic here recently.

The icons labelled step-backward and step-forward were not the preferred versions.  The ones with a smaller gap between the elements were preferred.  Also CoDEmanX wanted a little more time to improve the images even more.

To make it easier for users to identify, select and use these new icons may I suggest using more appropriate / common names that better match the icon designs.

* For the icons named step-backward and step-forward I suggest that these be named slow-motion-backward and slow-motion-forward respectively.  (Alternatively try something like slow-mo-back and slow-mo-forward if you want shorter names.)

* The icons named step-backward-2 and step-forward-2 would be better named frame-backward and frame-forward respectively.

* The icons named skip-backward and skip-forward would be better named previous-title and next title.

I look forward to these icons being added to the library.

Regards,
Ian.

**Comment by IanSav** [comment]
Hi Templarian,

When these icons are added to the library would you please let me / us know under what tag you will be associating them.

Regards,
Ian.

**Comment by Templarian** [comment]
I might.

**Comment by IanSav** [comment]
:)

**Comment by IanSav** [comment]
Hi CoDEmanX,

Have you been able to complete the tweaks you wanted to make before submitting and incorporating these media icons?

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Well, I checked them again and I think the positioning is actually okay. What bugs me more is the vertical bar width. Especially in `step-*-slow2b` (3px) compared to the stock `skip-*` icons (2px). But 2px look too narrow and we can't make it 2.5px, because it would look blurry.

Bottom line: the ones I uploaded are probably the best compromise, minus #900 and #901:

https://www.dropbox.com/s/8bjsiolaiq4jba6/step-forward2b.design?dl=0
https://www.dropbox.com/s/6saonxb4c0ecg0h/step-backward2b.design?dl=0

**Comment by IanSav** [comment]
Hi CoDEmanX,

I don't think you need to worry about comparing or matching the new icons to the Google originals.  I would make a new set of *all* the media control icons consistent and matched with each other so that they can be used as a matched set.  If any of the icons become similar but different duplicates from the Google set then simply name the new icons slightly differently or if convention dictates then name them as a -alt.

I agree that a blurry middle ground is not optimal.  The icons work best when they are clean and crisp.  When you looked at the vertical bar widths did you look at the previous-title (|<<), next-title (>>|), previous (|<) and next (>|) icons.  They should all have similar vertical bar widths.  Whether you go with two or three pixels they should all have the same look and feel.

I would like to ask if you could please create a new version of the http://codepen.io/anon/pen/BoezMw web page featuring the preferred versions of *all* the media player icons with their updated names.  Please include all existing media player icons that you don't intend to change but think will go together in the set so that they can all be seen together.  This could be used as the final review sample of the latest versions of all the icons.  (I must admit to becoming a little confused as to what is in the final proposal.)

Thank you so much for all your work on this.  I can't wait until these icons are available in a new icon font library.

Regards,
Ian.

**Comment by IanSav** [comment]
Hi Guys,

Are we getting any closer to having the final versions of these icons published?  I am really looking forward to being able to use them in the remote control app.

Regards,
Ian.

**Comment by Templarian** [comment]
v1.4.57 just went out on NPM/Bower, but I don't think I have all the changes for the media icons in. There are a few issues still opened. Holidays messed with all my free time.

I will not be waiting for another 100+ before the next release. Will try and get these finished up in the next icons. Next release will focus on any issues I marked as high priority.

**Comment by IanSav** [comment]
Hi Templarian,

Happy New Year!

Thanks for the update.  (Anticipation is building  ;) )

Regards,
Ian.

**Comment by CoDEmanX** [comment]
@IanSav: Which of the following would be the best font-wise?

![tv_info](https://cloud.githubusercontent.com/assets/1309249/12405437/6bb05270-be44-11e5-804d-2040216edf20.png)

**Comment by IanSav** [comment]
Hi CoDEmanX,

In the sample size available version 1 and 3 seem very similar to my eye differing only in the spacing of the dot from the body.  Version 2 is bolder and looks a little stronger.  I think I prefer version 2 but would accept version 3 if it rates higher with other users.  Versions 4 and 5 do not look like any of the "i" icons on any of my remote controls.

Teletext has been dropped in Australia so I hadn't given this much thought.  If needed I was going to re-task another icon for the purpose.  I think your proposal is much better!   :)

By the way, what is the "Tag" applied to all the new media player icons?  I was trying to find a way to list *all* the new icons in a simple tag search in the main website icon browser.

Regards,
Ian.

**Comment by CoDEmanX** [comment]
Not sure if there's a tag at all. We really need a contributor backend with tag management to organize the icons better.

Version 1 and 3 are different, mainly the angle of the central stroke. At higher resolutions, many more delicate difference become apparent (circle not perfectly round in version 3 for instance):

![tv_info_96](https://cloud.githubusercontent.com/assets/1309249/12407699/d17d8090-be59-11e5-858d-910ea9e0911e.png)

**Comment by IanSav** [comment]
Hi CoDEmanX,

Okay, the larger versions do make a difference.  I think version 3 with a round dot would be my first preference, next would be version 2 with a round dot.   ;)

(Sorry for the delay in responding.)

Regards,
Ian.

**Comment by CoDEmanX** [comment]
I created a custom path based on the font letter to reduce the number of points to 30% and to avoid any legal concerns. The dot is a perfect 3x3 circle:

![tv_info2](https://cloud.githubusercontent.com/assets/1309249/12446789/6b793c30-bf6c-11e5-8377-ac26ef88ba6b.png) https://www.dropbox.com/s/rcuclsrpy7ukuo7/tv_info2.svg?dl=0

**Comment by IanSav** [comment]
Hi CoDEmanX,

Looks good.   :)

Regards,
Ian.

**Comment by Templarian** [comment]
[![information-variant](https://materialdesignicons.com/icon/information-variant)](https://materialdesignicons.com/icon/information-variant)

**Comment by CoDEmanX** [comment]
So, I think except for the teletext icon, everything has been added?

**Comment by IanSav** [comment]
I am very happy with all the media icon additions.  All the navigation icons I needed have been delivered.  Australia no longer has teletext so I forgot about that one.  :?  If anyone else wants to add to the list then that would be okay too.

The remote control app is being updated to allow access to all the new icons.   :)

Thank you to all involved for making this happen.

**Comment by Templarian** [comment]
Awesome. Long, process, but good to see everyone happy.

Thanks @CoDEmanX for everything to get this issue wrapped up. :smile:
