### ISSUE TITLE
Suggestion: Brain, Logic 

### ISSUE THREAD

**Issue by igorushi** [Templarian/MaterialDesign#859]

**Comment by CoDEmanX** [comment]
I tried to create a brain here: #526 
but it's not very material-y...

Do you have some suitable examples?

**Comment by igorushi** [comment]
I like a concept of [this image](http://us.123rf.com/450wm/vladystock/vladystock1508/vladystock150800276/43818036-brain-cpu-microprocessor-circuit-board-abstract-technology-background-vector-illustration-eps-10.jpg?ver=6), but I'm not sure that such an idea can be simply "materialized".

**Comment by Templarian** [comment]
Marking this as a duplicate of the issue above.
