### ISSUE TITLE
Rename 'cog' to 'settings' Icon and add Import/Export Icon

### ISSUE THREAD

**Issue by csaq7151** [Templarian/MaterialDesign#86]
![ic_action_ic_action_settings](https://cloud.githubusercontent.com/assets/10165699/5731043/ac3f8330-9b7f-11e4-8f28-bf8a20bea1b9.png)
![ic_action_content_import_export](https://cloud.githubusercontent.com/assets/10165699/5731054/c1685cb4-9b7f-11e4-849d-1d1b9e0bc93c.png)

**Comment by csaq7151** [comment]
Can you please make the settings Icon and the Import/Export I think alot of people need them.
The other two are not important but would be great.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/cog

Will have to add the other.

**Comment by Templarian** [comment]
I think in the next font update I'll be changing it to settings to match the regular use of the icon.

**Comment by csaq7151** [comment]
ok thank you.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/swap-vertical Turns out this one was already on the site. Part of the stock Google icons.
