### ISSUE TITLE
Some smarthome icons

### ISSUE THREAD

**Issue by panzaeron** [Templarian/MaterialDesign#861]
I've made some icons for smart home apps:

Door:
https://www.dropbox.com/s/cwoby42n3dtz4hp/door.svg?dl=0

Another window version:
https://www.dropbox.com/s/k180gz3awac4li7/window2.svg?dl=0

EU power socket:
https://www.dropbox.com/s/fsquatw2r0pmc16/power-socket-eu.svg?dl=0

And for the window above a shutter half closed:
https://www.dropbox.com/s/bdluvxi5fajvfbb/shutter.svg?dl=0

shutter fully closed:
https://www.dropbox.com/s/koqdrffqbh86i1f/shutter-down.svg?dl=0

and finally a series of light bulbs with dimmer status:
https://www.dropbox.com/sh/9zfi8tzys852rsg/AABZ0SE1L_wxWmhZ9YaMIC77a?dl=0

**Comment by CoDEmanX** [comment]
Door looks more like a fridge and the window icon is unintelligible IMO.

EU power socket is okay, but needs some work (too delicate details).

The blinds icons look multi-colored, which isn't possible with icon fonts (also not transparency). We do have a blinds icon, maybe there could be a second version to represent another closing state.

I don't think it's a good idea to have 10 icons for different dimming states. You should rather use a single light bulb icon and find some way to represent the dimming state with a system widget, use color or transparency on the icon or draw some indicator (line, circle outline, ...) dynamically.

**Comment by panzaeron** [comment]
Thanks for your response. 
Yes, the door could also be a fridge, but what should I change? A window in the door? Not every door has a window...
What do you mean with multi-colored and not transparency, the icons uses a single path and small gaps to looks like more an shutter or blind. 
I have made the ten different icons, because it is similar to the existing battery icon from google. 
A dynamic Icon would be better, but it is not font compatible.

**Comment by CoDEmanX** [comment]
Maybe there's some way to make the door look more like a door, by making the door handle very recognizable.

I only checked the Dropbox previews, and the thin gaps make it look gray / semi-transparent.

The MD guidelines state, that the minimum stroke width and margin should be 2px. There are a few exceptions (couple Google and MDI icons), where it's 1px. But it shouldn't be less in any icon. Every icon should also be legible at the native size of 24x24 pixels.

**Comment by CoDEmanX** [comment]
I like the dimmer concept, but the tiny circles are not legible at normal size:

![image](https://user-images.githubusercontent.com/1309249/38773561-eedb5da4-404f-11e8-8e77-e5a06f3d9400.png)

We meanwhile added window, door and power socket icons.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
