### ISSUE TITLE
Shuffle off icon for consistency

### ISSUE THREAD

**Issue by icarapovic** [Templarian/MaterialDesign#862]
I would like to suggest a "shuffle off" icon, as the shuffle usually goes in pair with repeat which has icons for all states.
Currently, repeat has icons for: off, one, all. Shuffle has only "on" icon, but no off.

Consistency wise is this icon needed because otherwise you need to give feedback about on/off state by tinting the icon or making it more transparent, whereas the repeat can be just replaced by the appropriate state icon.

I'd love to contribute it myself but im a programmer so my Photoshop/Illustrator skills are very limited :)

**Comment by CoDEmanX** [comment]
It probably doesn't exist because this comes out:
![shuffle-off](https://cloud.githubusercontent.com/assets/1309249/11381215/15e32008-92fb-11e5-9688-2fdf70ff57dd.png)

**Comment by icarapovic** [comment]
I agree, the above solution popped into my mind but visually its almost identical to the "on" version. Two vertical lines pointing to right would be the solution.

**Comment by CoDEmanX** [comment]
How is this?
![shuffle-off](https://cloud.githubusercontent.com/assets/1309249/11393273/12791986-935f-11e5-8800-c9eb33721a58.png)

**Comment by icarapovic** [comment]
I prefer the above one because the 2nd example would leave to much blank space over and under while the other playback icons keep most of the space filled. Thanks!

**Comment by Templarian** [comment]
Yea, I think that first one will work, but probably best to call it `shuffle-disabled` due to it not using the standard slash.

**Comment by CoDEmanX** [comment]
True!
https://www.dropbox.com/s/eexoepxu3zo4hfh/shuffle-off.design?dl=0

**Comment by icarapovic** [comment]
I actually used the available shuffle icon, removed the arrow in the back, rotated the front one, pulled it up, and copied it to the bottom. Heres my result, its a 256x256 white on transparent version.

![shuffle_off](https://cloud.githubusercontent.com/assets/6676759/11426853/2017c15e-945f-11e5-981a-05a7c33ff5e8.png)

**Comment by Templarian** [comment]
[![shuffle-disabled](https://materialdesignicons.com/icon/shuffle-disabled)](https://materialdesignicons.com/icon/shuffle-disabled)
