### ISSUE TITLE
Dropzone

### ISSUE THREAD

**Issue by derwaldgeist** [Templarian/MaterialDesign#863]
I could not find an icon symbolizing a drop-zone. I need this to indicate where a user might drop an image file onto my app.

**Comment by CoDEmanX** [comment]
That's usually not something you visualize with an icon. There's usually a rectangular area for the drop, which changes its color as the user enters it while dragging. On the Dropbox website, the entire viewport is the dropzone. A green border lights up on drag and an info text tells you that you can drop it anywhere.

**Comment by PeterShaggyNoble** [comment]
Any of these should work but let us know if they don't suit your needs and provide an example of what you're looking for and we'll reopen this issue.

[![select](https://user-images.githubusercontent.com/15157491/33828102-a2dfc164-de62-11e7-84c9-f7f513675991.png)](https://materialdesignicons.com/icon/select) [![selection](https://user-images.githubusercontent.com/15157491/33828128-c6435558-de62-11e7-97fd-c8478c40d3e9.png)](https://materialdesignicons.com/icon/selection) [![bullseye](https://user-images.githubusercontent.com/15157491/33828162-e9842c4a-de62-11e7-90b1-2b3786a28b38.png)](https://materialdesignicons.com/icon/bullseye)

**Comment by derwaldgeist** [comment]
Yes, the first one makes sense. Thanks.
