### ISSUE TITLE
network icons

### ISSUE THREAD

**Issue by aerypton** [Templarian/MaterialDesign#868]
I would like to have some icons for router, modem, switch,...

**Comment by CoDEmanX** [comment]
Wifi router is part of #420. Not sure how one would represent a modem or switch...

![networking_icons-09](https://cloud.githubusercontent.com/assets/1309249/11419182/f93afa94-9425-11e5-9f92-9fcf6823a198.png)
![multilayer-switch-icon](https://cloud.githubusercontent.com/assets/1309249/11419181/f9396300-9425-11e5-9280-ad6745f0cc78.png)
?

Or use:
https://materialdesignicons.com/icon/lan
https://materialdesignicons.com/icon/ethernet

**Comment by aerypton** [comment]
I used https://materialdesignicons.com/icon/sitemap for switch and https://materialdesignicons.com/icon/ethernet as router (as you suggested)

**Comment by Templarian** [comment]
[![switch](https://materialdesignicons.com/icon/switch)](https://materialdesignicons.com/icon/switch) [![router-wireless](https://materialdesignicons.com/icon/router-wireless)](https://materialdesignicons.com/icon/router-wireless)

**Comment by CoDEmanX** [comment]
Won't router-wireless conflict with http://www.google.com/design/icons/#ic_router ?

**Comment by rstudner** [comment]
@CoDEmanX - I was just coming here about this.  It appears the google material icon for router is different than this one.
