### ISSUE TITLE
Suggestion: ctrl + alt + del icon

### ISSUE THREAD

**Issue by unwlelt** [Templarian/MaterialDesign#870]
![ctrl_alt_del](https://cloud.githubusercontent.com/assets/8713194/11427936/1427b680-9467-11e5-902b-dba541328b83.gif)

**Comment by Templarian** [comment]
I think this is too specific of an icon for this set. Maybe a generic keyboard key?

**Comment by CoDEmanX** [comment]
I don't find it very recognizable, maybe three separate icons with text ctrl, alt and del?

**Comment by unwlelt** [comment]
On Windows people use ctrl+alt+del, but there are other similar shortcuts like cmd+alt+del or cmd+options+escape on mac, so we can't use text. The action is very common for people working with computers and the icon is often required by our customers. How can you design it in a single small icon width no text? This is a big challenge for a designer.

**Comment by CoDEmanX** [comment]
Well, you would usually not use an icon for this I guess, but write out the full key names specific to the OS (and ideally, the keyboard in use, think Apple keyboard + Windows with Bootcamp).

**Comment by PeterShaggyNoble** [comment]
Closing for the reasons above. Using text (providing all options for all systems) is going to communicate this a lot clearer than an icon could; you'd end up having to include a label to clarify the meaning.
