### ISSUE TITLE
Missing icon - mdi-comment-question-outline

### ISSUE THREAD

**Issue by tadejongithub** [Templarian/MaterialDesign#871]
I think there is a missing icon - "mdi-comment-question-outline" in version 1.3.41. Or am I missing something?

On official page the icon is shown, but in bower distribution, there is no icon definition. You can easily check this if you run preview.html.

**Comment by Templarian** [comment]
https://materialdesignicons.com/history Looks like it was added after the last release. A new release isn't planned for a few weeks.
