### ISSUE TITLE
errors & warnings

### ISSUE THREAD

**Issue by aerypton** [Templarian/MaterialDesign#872]
I need icons for errors & warnings. Thx.

**Comment by CoDEmanX** [comment]
What about these?
https://materialdesignicons.com/icon/alert
https://materialdesignicons.com/icon/alert-octagon
https://materialdesignicons.com/icon/close-circle
https://materialdesignicons.com/icon/exclamation

There's also a request for log level icons: #707 

I guess we could add a new `close-octagon` icon, would that help?

**Comment by CoDEmanX** [comment]
![alert-outline-variant](https://cloud.githubusercontent.com/assets/1309249/11769053/0f8d1414-a1df-11e5-9649-df62a291d96d.png) https://www.dropbox.com/s/gh65dj0uyl8ul69/alert-outline-variant.design?dl=0
![triangle](https://cloud.githubusercontent.com/assets/1309249/11769061/27830eb6-a1df-11e5-881a-5aa2ac056a22.png) https://www.dropbox.com/s/26592u1r2cvwqx9/triangle.design?dl=0
![triangle-outline](https://cloud.githubusercontent.com/assets/1309249/11769063/278613c2-a1df-11e5-89b4-7b75bd462642.png) https://www.dropbox.com/s/chtxls068ybp4f1/triangle-outline.design?dl=0
![octagon](https://cloud.githubusercontent.com/assets/1309249/11769060/27824d64-a1df-11e5-82cf-27c7feae44a0.png) https://www.dropbox.com/s/zpu284o94hmxtyn/octagon.design?dl=0
![octagon-close](https://cloud.githubusercontent.com/assets/1309249/11769059/27824594-a1df-11e5-92b7-e7250a1f4766.png) https://www.dropbox.com/s/f8ljq2cfwszj5da/octagon-close.design?dl=0
![octagon-close-outline](https://cloud.githubusercontent.com/assets/1309249/11769058/278172a4-a1df-11e5-9f71-6e03e258040d.png) https://www.dropbox.com/s/ssbvbetolgq58dc/octagon-close-outline.design?dl=0
![octagon-outline](https://cloud.githubusercontent.com/assets/1309249/11769062/278574bc-a1df-11e5-8381-6c85f62b8167.png) https://www.dropbox.com/s/0fp4w2083zmlf4s/octagon-outline.design?dl=0

Probably also relevant to #707

**Comment by Templarian** [comment]
[![octagon](https://materialdesignicons.com/icon/octagon)](https://materialdesignicons.com/icon/octagon) [![octagon-outline](https://materialdesignicons.com/icon/octagon-outline)](https://materialdesignicons.com/icon/octagon-outline) [![close-octagon](https://materialdesignicons.com/icon/close-octagon)](https://materialdesignicons.com/icon/close-octagon) [![close-octagon-outline](https://materialdesignicons.com/icon/close-octagon-outline)](https://materialdesignicons.com/icon/close-octagon-outline) [![triangle](https://materialdesignicons.com/icon/triangle)](https://materialdesignicons.com/icon/triangle) [![triangle-outline](https://materialdesignicons.com/icon/triangle-outline)](https://materialdesignicons.com/icon/triangle-outline) [![alert-outline](https://materialdesignicons.com/icon/alert-outline)](https://materialdesignicons.com/icon/alert-outline)
