### ISSUE TITLE
Car related icons

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#874]
- [x] dimmed beam - #3711
- [x] high beam - #3711
- [x] fog lamp - #3711
- [ ] air circulation
- [x] airbag - #3714
- [x] seat belt - #3713 
- [x] windshield wiper
- [ ] screen wash
- [ ] rear window heating
- [x] hand break - #3720
- [x] hazard flasher - #3712
- [x] ABS - #3720
- [x] ESP - #3720
- [ ] air jet
- [ ] doors open
- [ ] ignition
- [x] blinker / indicator
- [x] tire pressue - #3719
- [x] power steering

![2223253_auto-symbole-einfache-drop-motor-taste](https://cloud.githubusercontent.com/assets/1309249/11448614/fdccaeea-955b-11e5-905d-18e8f8407a79.jpg)

(light gray: already available or already tracked)

**Comment by Alekhen** [comment]
How about these for the three light types

![image](https://user-images.githubusercontent.com/1837101/39606526-1f2fcbf0-4ef3-11e8-8954-f59176104030.png)

![image](https://user-images.githubusercontent.com/1837101/39606558-3cd1370c-4ef3-11e8-800e-11856e3f19ea.png)

![image](https://user-images.githubusercontent.com/1837101/39606578-4bf0bdb6-4ef3-11e8-963f-b6b589df9e97.png)

[beam-dimmed.svg.zip](https://github.com/Templarian/MaterialDesign/files/1972906/beam-dimmed.svg.zip)
[beam-high.svg.zip](https://github.com/Templarian/MaterialDesign/files/1972908/beam-high.svg.zip)
[fog-lamp.svg.zip](https://github.com/Templarian/MaterialDesign/files/1972909/fog-lamp.svg.zip)

**Comment by CoDEmanX** [comment]
Nice! Have you tried straight line terminals as well?

**Comment by Alekhen** [comment]
I was copying the rounded style of [run-fast](https://materialdesignicons.com/icon/run-fast) and [clock-fast](https://materialdesignicons.com/icon/clock-fast), but I don't mind the square ends. I think it works either way. The square ends are crisper which helps the icon hold up better at smaller sizes.

Might be good to cross reference these with the tags _automotive_, _car_, and _headlight_.

![image](https://user-images.githubusercontent.com/1837101/39639762-b50eedca-4f86-11e8-811f-5011bed8d954.png)

![image](https://user-images.githubusercontent.com/1837101/39640030-ee51f7d0-4f86-11e8-98f6-6b7adb7e7281.png)

![image](https://user-images.githubusercontent.com/1837101/39640041-fb41fa94-4f86-11e8-90d3-e7b262ce5fce.png)

[fog-lamp.svg.zip](https://github.com/Templarian/MaterialDesign/files/1975197/fog-lamp.svg.zip)
[beam-dimmed.svg.zip](https://github.com/Templarian/MaterialDesign/files/1975195/beam-dimmed.svg.zip)
[beam-high.svg.zip](https://github.com/Templarian/MaterialDesign/files/1975196/beam-high.svg.zip)

**Comment by PeterShaggyNoble** [comment]
We should probably give them all the same prefix; `headlight-fog`, `headlight-dimmed` & `headlight-high`.

**Comment by goyney** [comment]
Windshield wiper may be added in this request: https://github.com/Templarian/MaterialDesign/issues/3361

**Comment by goyney** [comment]
![image](https://user-images.githubusercontent.com/1015040/43732018-5fb9de24-997e-11e8-9959-ccd2c7e4bb85.png)

[hazard-lights.zip](https://github.com/Templarian/MaterialDesign/files/2263512/hazard-lights.zip)

**Comment by goyney** [comment]
`arrow-left-bold` and `arrow-right-bold` and their `outline` variants can be used for turn signal markers and are already available, so I've checked that one off the light.

**Comment by JamesCoyle** [comment]
Need to split this into multiple issues to track these better.

**Comment by goyney** [comment]
@CoDEmanX I've filed a few issues for some of the items from your list. Can you break the rest out into  new issues so we can close this messy issue?

**Comment by antembmip** [comment]
Maybe more explicit for esp icon 
![image](https://user-images.githubusercontent.com/45227578/48848839-494d7580-eda5-11e8-9a69-42a3318629f7.png)

Reference : https://www.iso.org/obp/ui/#iso:grs:7000:2630

**Comment by PeterShaggyNoble** [comment]
@antembmip, see #3720 where work is currently being done on an EPS icon.

**Comment by goyney** [comment]
A bunch of these were added recently. We've created a new Automotive tag to group them together: https://materialdesignicons.com/tag/automotive.

**Comment by goyney** [comment]
Closing this issue as the majority of icons have been added. If you still wish to see any of the other car-related icons created, please create a new issue for each icon. Thanks!
