### ISSUE TITLE
Suggestion: Password icon

### ISSUE THREAD

**Issue by smuellerus** [Templarian/MaterialDesign#876]
I need an icon for a password text field... thanks

**Comment by CoDEmanX** [comment]
You would commonly use a [lock icon](https://materialdesignicons.com/icon/lock) for this, or a [key](https://materialdesignicons.com/icon/key-variant). Do you have something different in mind?

**Comment by smuellerus** [comment]
That's cool, I actually chose the lock icon. Thanks!
