### ISSUE TITLE
Icons for accounting 

### ISSUE THREAD

**Issue by naveedjamali** [Templarian/MaterialDesign#878]
Hi Developers and Everyone,

I am searching **icons for accounting** which can present accounting terms like **Account, Accounts, Credit , Debit, Report, Account list, Ledger, Add Credit, Add Debit, Add expense, Add Revenue, Assets, Liability, Budget, Add Budget** or whatever comes in mind when thinking in accounting context. I am sure you'll help me.

Lot of Thanks.
Naveed Jamali

**Comment by PeterShaggyNoble** [comment]
If you're still in need of these, please open a new issue for each icon required and include examples. Don't forget to search the existing icons and issues first, though. Be advised, though, that some of these would be too specific for inclusion.
