### ISSUE TITLE
Make svg consumable from angular material $mdIconProvider part of the bower/npm packages

### ISSUE THREAD

**Issue by sarod** [Templarian/MaterialDesign#879]
The [getting started](https://materialdesignicons.com/getting-started) provides a link to a mdi.svg consumable inside $mdIconProvider.

However the npm packages contain only the svg font but not the svg consumable by ng material. Is it available somewhere else?

**Comment by emps** [comment]
was about to ask that too :+1:

**Comment by Templarian** [comment]
First of all it will never be ever included into the main `mdi` bower/npm packages. Maybe a `mdi-angular` or something (is there a naming convention here?).

There is one small issue right now, I don't version the `mdi.svg` at the moment. What you're seeing is a direct database output to a file for all published icons. Every download is the very latest.

I version the font very selectively for quality control because of the large usage rates. For mdi.svg would you guys be fine if I just push the latest out and incremented with a build number. So the release wouldn't be the number of icons, but simply whatever was published to the site at that moment. This will result in a lot of releases, but you'll always have the latest and not wait for the font release which is more bi-monthly at this point. It would also keep me from managing another dependency.

Let me know.

**Comment by sarod** [comment]
A separate package would be fine.
Having the latest as an npm package would be an real improvement over downloading it manually.

Having version and content that follow mdi npm package would be great but can come later from my point of view. 
I'm wondering though if it wouldn't be possible to automate the build of mdi-angular package from the mdi package content. Can't we derive the mdi-angular mdi.svg from mdi/fonts/materialdesignicons-webfont.svg?

**Comment by gligoran** [comment]
I'd really like this too, so I'd know there's new icons when I'm checking bower updates and don't have to check and download the SVG manually. I'd call id ```mdMdi```/```md-mdi```, as most angular material seems to use that prefix. A separate package would actually be preferred from my point of view as I only intend to use that. You could also add a ```.js``` file where the ```$mdIconProvider``` registration happens, so it just ends up being simply plug&play. But I'd be happy just having the SVG as part of bower to start with.

**Comment by Templarian** [comment]
Okay, this weekend I'll try and get this in.

@gligoran Can you explain what you mean by add a `.js` file (might be best if you tell me exactly what would be best in the repo/file structure, @sarod insight might help also). I'm going to be scripting this out as a button in my admin panel to make the deploy as streamlined as possible.

**Comment by gligoran** [comment]
When I was typing that I think I meant something like:

```
angular
    .module("mdMdi", ["ngMaterial"])
    .config(["$mdIconProvider", function mdMdiConfig($mdIconProvider) {
    $mdIconProvider.defaultIconSet("bower_components/md-mdi/mdi.svg");
}]);
```

But looking at this now, the actual path is different for each project, so it doesn't make any sense.

**Comment by gligoran** [comment]
Just a note from me. Over the weekend I ported my application from using [```angular-material-icons```](https://klarsys.github.io/angular-material-icons/) to ```mdi.svg```. I've got some 100+ item lists where each item has 4 or 5 icons (mostly icon buttons). I've noticed a considerable performance problems rendering these kinds of lists. There weren't any with ```angular-material-icons```.

Today I switched from the ```mdi.svg``` to using the web font. ```$mdIconProvider``` supports using web fonts, so the switch was quite simple. The performance boost was enormous though.

I'm not sure if this is ```mdi.svg``` itself or ```$mdIconProvider``` but in my case it rendered the whole app barely usable.

**Comment by Templarian** [comment]
This has to do with how SVGs are rendered. They are considerably more CPU intensive than the webfont I believe. I'm not sure how your list works, but make sure it isn't doing any unnessary re-rendering of the dom elements.

This might not be the best place to ask, the angular-material community might have a more technical answer.

**Comment by patrickmichalina** [comment]
Anyone working on this?

**Comment by jaoued** [comment]
Hi @Templarian ,

Thanks for your awesome work!

So, any update to this issue?

Regards.

**Comment by SuperITMan** [comment]
Hello @Templarian ,
Thank you for your work, it's really great !
I would like to know if the idea of npm package with a bundle like "mdi-angular" is still relevant. 

Thanks again.
Regards.

**Comment by Templarian** [comment]
We're working on this right now and are planning to back publish 2.1.99, just working through a small issue that is out of our hands right now.

**Comment by SuperITMan** [comment]
Good news ! :)
While waiting for a solution from you, I did a small package with your mdi-svg file. 
It's available on [NationalBankBelgium/angular-mdi-svg](https://github.com/NationalBankBelgium/angular-mdi-svg). 
Let me know when your implementation is ready. 

Thanks.

**Comment by Templarian** [comment]
@SuperITMan That helps a lot, I'll look into this and make sure it's very similar (will probably just assign you as a contributor to the distribution repo once it's up also). The goal of bringing these under "our" umbrella is just to make sure we remove delays in the updating of support libraries.

😄 🎉

**Comment by Templarian** [comment]
I'm coding it still, but have to head out will hopefully commit something shortly. The solution I'm going with will use the `@mdi/svg` as a dependency and a simple node script to write the file. Moving away from my server for dependencies if we can generate them from first party npm packages.

https://github.com/Templarian/MaterialDesign-Angular-Material

**Comment by Templarian** [comment]
Build script is done. Will publish to `@mdi/angular-material` soon.

**Comment by SuperITMan** [comment]
Great! 😃
Hope it will be available soon. Thanks 😊

**Comment by Templarian** [comment]
Done, it is now an officially maintained package under https://www.npmjs.com/org/mdi

**Comment by Templarian** [comment]
I forgot to add that we will not be supporting bower on any supporting packages, but we are tagging releases so you can still use `bower` with the version tags.
