### ISSUE TITLE
Fridge filled variant (as opposed to existing outline version)

### ISSUE THREAD

**Issue by Mihai258** [Templarian/MaterialDesign#880]
Hi,
I suggest to improve the fridge icon by adding two more fridge icons similar with the existing one + coloring upper or down part of it. It could be used for temperature monitoring into each part of it.
Thank you

**Comment by CoDEmanX** [comment]
Coloring is only possible if the webfont is used, using CSS. Seems a bit too specific for the font, I suggest you split it up yourself (very easy with InkScape ) and perhaps inline the SVG code.

**Comment by Mihai258** [comment]
Sorry, I do not express clear my proposal: I was thinking actually of fulfill the upper/lower part, like icons cloud vs. cloud-outline.

**Comment by CoDEmanX** [comment]
Ah, so what you want is a filled version of the fridge. We would need to rename the existing icon to fridge-outline then...

**Comment by Mihai258** [comment]
Yes, this is! If possible, two or three variants: upper part filled, down part filled, whole filled, it will be nicer for monitoring each part of the fridge with its own icon. I saw the icon edit program is for Windows and I am using Linux, so I can't use it for design.

**Comment by CoDEmanX** [comment]
InkScape is Java-based, so it should run on all major platforms: https://inkscape.org/en/download/linux/
Do you mean Expression Design by any chance? That is indeed Windows only, but InkScape will work just fine (and is more powerful IMO), as there are SVG files for every icon just as there are .design files for Expression Design. Let me know if you need more help.

**Comment by Mihai258** [comment]
I have edited the current fridge icon with InkSkape (thank you!), the SVG variant. Unfortunately I am not able to attach the SVG files, so I convert them to PNG (useless for further editing...).
![fridge_down](https://cloud.githubusercontent.com/assets/16061924/11539280/ff09b8d0-992e-11e5-96e9-24e3ba82d7c1.png)
![fridge_up](https://cloud.githubusercontent.com/assets/16061924/11539281/ff0ad166-992e-11e5-8597-7fe365ccb58c.png)
![fridge_filled](https://cloud.githubusercontent.com/assets/16061924/11539282/ff127ca4-992e-11e5-9a54-a0647bec5d08.png)

**Comment by CoDEmanX** [comment]
I would actually tweak it a little more for a clean, all-filled version:
![fridge-filled](https://cloud.githubusercontent.com/assets/1309249/11539775/3d5992dc-9929-11e5-8100-118517237a5a.png)

Or if you want the combinations:
![fridge6](https://cloud.githubusercontent.com/assets/1309249/11540050/da31c704-992a-11e5-9e7a-9c97dcb363f8.png) ![fridge5](https://cloud.githubusercontent.com/assets/1309249/11540049/da30ee56-992a-11e5-8d68-e0c981ce5c6c.png) ![fridge3](https://cloud.githubusercontent.com/assets/1309249/11540047/da2f4ede-992a-11e5-9732-18c1e950de26.png) ![fridge2](https://cloud.githubusercontent.com/assets/1309249/11540051/da325700-992a-11e5-91ea-855348af92af.png)

Variants I don't like:
![fridge7](https://cloud.githubusercontent.com/assets/1309249/11540063/f033df92-992a-11e5-8b5c-fe924b3df2b7.png) ![fridge4](https://cloud.githubusercontent.com/assets/1309249/11540064/f0345684-992a-11e5-9e4e-09f45428d005.png)

**Comment by Mihai258** [comment]
I personally prefer the combination, they will be more useful and clear for apps that check the temperature in each compartment, I will use them in Home-Assistant exactly for this purpose.
Thank you

**Comment by CoDEmanX** [comment]
What one could also do is to use the outline version, but add triangles that point at the compartments...

BTW: do you want my SVGs? Not sure if @Templarian wants them in MDI.

**Comment by Mihai258** [comment]
Yes, please, I would like to include the "half" versions in my home automation. How to get them? If not possible, I got the idea and I will redesign mine almost the same.

**Comment by CoDEmanX** [comment]
Here you go:
https://www.dropbox.com/s/h3jmqlmlqevj76p/fridge-filled-none.svg?dl=0
https://www.dropbox.com/s/arz5bwc7a7kyu83/fridge-filled-top.svg?dl=0
https://www.dropbox.com/s/90yqxga3vs0l8ts/fridge-filled-bottom.svg?dl=0
https://www.dropbox.com/s/rsohy8t3enrfpwm/fridge-filled-both.svg?dl=0

**Comment by Mihai258** [comment]
Thank you, I have downloaded them and I hope they will be added into MDI to become available for everybody.

**Comment by Templarian** [comment]
[![fridge-filled](https://materialdesignicons.com/icon/fridge-filled)](https://materialdesignicons.com/icon/fridge-filled) [![fridge-filled-top](https://materialdesignicons.com/icon/fridge-filled-top)](https://materialdesignicons.com/icon/fridge-filled-top) [![fridge-filled-bottom](https://materialdesignicons.com/icon/fridge-filled-bottom)](https://materialdesignicons.com/icon/fridge-filled-bottom)

@CoDEmanX I modified them to 14px width instead of 13px before uploading.
