### ISSUE TITLE
Rename file_image_box to image

### ISSUE THREAD

**Issue by xsorifc28** [Templarian/MaterialDesign#881]
The [image](https://materialdesignicons.com/icon/image) icon seems to be called file_image_box in the font file. Just requesting to have this renamed so the two names are consistent.

Thank you!

**Comment by Templarian** [comment]
This is one of the breaking changes in the next release. It should have never been called file-image-box. That was a mistake.

**Comment by xsorifc28** [comment]
Great, thank you!
