### ISSUE TITLE
Sprinkler

### ISSUE THREAD

**Issue by Mihai258** [Templarian/MaterialDesign#882]
I suggest to add a sprinkler icon. For the garden it could be like this:
https://www.facebook.com/728294017256914/photos/728322970587352/
If you find useful, me or somebody else may built a ceiling sprinkler icon.

**Comment by dethpickle** [comment]
+1

**Comment by jjanderson** [comment]
Last commebt a year ago... hmm, think i will look into becoming a contributor and do it myself...

**Comment by GreenTurtwig** [comment]
You're more than welcome too. :heart:
Might be difficult because of the thinness, but that hasn't stopped some great designs.

**Comment by goyney** [comment]
Perhaps something like:
![image](https://user-images.githubusercontent.com/1015040/51008619-8ff45c00-151a-11e9-9c2a-3fa1b99defb2.png)
[sprinkler.svg.zip](https://github.com/Templarian/MaterialDesign/files/2747789/sprinkler.svg.zip)

**Comment by jjanderson** [comment]
That looks great!

**Comment by PeterShaggyNoble** [comment]
My first though on seeing that was that it was an aerosol can. Context would probably help to define it, though.

**Comment by GreenTurtwig** [comment]
Yeah I haven't personally seen a sprinkler that looks like that before. But then again ours tend to be plugged into a hose, not a part of the lawn.

**Comment by goyney** [comment]
I based it off of the ones in my own yard, look like this:
![image](https://user-images.githubusercontent.com/1015040/51050138-cd4dfd80-159d-11e9-931e-31408f22d933.png)

Could be aliased as an aerosol can too! :P

**Comment by cyclemycity** [comment]
I'd really like to se some irrigation icons added, like this. Perhaps the sprinkler could be more central with water on both sides? 

Where can I cat the template/tool to make these suggested/draft icons?

**Comment by Templarian** [comment]
@cyclemycity https://github.com/Templarian/MaterialDesign/tree/master/templates/icon We keep the templates here. Guidelines: https://material.io/design/iconography/system-icons.html

**Comment by cyclemycity** [comment]
![screen shot 2019-02-25 at 2 54 13 pm](https://user-images.githubusercontent.com/4979156/53314251-49fa2880-390d-11e9-84b5-ee4491801974.png)
???

**Comment by cyclemycity** [comment]
It didn't turn out like I wanted at all! Oh well, my artistic ability was never my strong point!

**Comment by cyclemycity** [comment]
Path data for the above if you're interested in adopting the icon:
M 13,22 13,10 11,10 11,22 Z M 2,4 4,4 4,6 2,6 Z M 2,8 4,8 4,10 2,10 Z M 2,12 4,12 4,14 2,14 Z M 20,4 22,4 22,6 20,6 Z M 20,8 22,8 22,10 20,10 Z M 20,12 22,12 22,14 20,14 Z M 5,10 7,10 7,12 5,12 Z M 5,6 7,6 7,8 5,8 Z M 17,10 19,10 19,12 17,12 Z M 17,6 19,6 19,8 17,8 Z M 8,8 8,10 10,10 10,8 Z M 14,8 16,8 16,10 14,10 Z M 11,8 13,8 12,9 Z

**Comment by goyney** [comment]
[![sprinkler](https://materialdesignicons.com/icon/sprinkler)](https://materialdesignicons.com/icon/sprinkler)[![sprinkler-variant](https://materialdesignicons.com/icon/sprinkler-variant)](https://materialdesignicons.com/icon/sprinkler-variant)

**Comment by fsaris** [comment]
Is this now part of the official icon set? (From what version?)

**Comment by goyney** [comment]
They're available from the website now. They'll be released to NPM in v4.1, which will likely be a couple weeks. After that, if you intended to use them in Home Assistant, HASS will need to include the correct version in their update, so probably looking at 2-4 weeks depending on timing (HASS just released, so its possible to be sooner rather than later.)

**Comment by insippo** [comment]
+1

**Comment by frieduser** [comment]
Hi all; newbie here! I've seen there's already open a issue [https://github.com/Templarian/MaterialDesign/issues/5881](url), but it seems it's still open. I'd propose this icon (I did it removing from mdi:splinker some characters one attempt after another)
![image](https://github.com/Templarian/MaterialDesign/assets/156363838/b91ad54a-b874-4bcd-aff4-88b1b7ef0fcc)

code (to be checked):
`M11 7H139H11V7M5 22H9V10H5V22M14 11H169H14V11M17 10H198H17V10M17 5V719V5H17M14 8H166H14V8M1 13H19V1117V13M5 7H5.33L6 9H8L8.67 7H9V6H5V7Z`

I'd nice to create status (run/off) with different icon (sprinkler/sprinkler-off)
Thx
