### ISSUE TITLE
icon media player

### ISSUE THREAD

**Issue by donpadre** [Templarian/MaterialDesign#884]
Hi

I am searching icons for media player (kodi, plex, emby)

- [x] kodi
- [x] plex
- [x] emby

thx

**Comment by infanf** [comment]
KODI:
![kodi](https://cloud.githubusercontent.com/assets/8826710/12019840/a15d5d26-ad75-11e5-9701-27ed67093508.png)
![kodi-48](https://cloud.githubusercontent.com/assets/8826710/12019841/a30a9422-ad75-11e5-9e4f-72c7d81a6197.png)
![kodi-96](https://cloud.githubusercontent.com/assets/8826710/12019842/a475a73e-ad75-11e5-96fc-b6451bd3df3a.png)
zipped SVG
[kodi.zip](https://github.com/Templarian/MaterialDesign/files/73250/kodi.zip)

**Comment by Templarian** [comment]
[![kodi](https://materialdesignicons.com/icon/kodi)](https://materialdesignicons.com/icon/kodi)

**Comment by infanf** [comment]
Four options for PLEX, I'd prefer the last one:
![plex](https://cloud.githubusercontent.com/assets/8826710/12246314/22f66e48-b8ae-11e5-9ee8-188b03f5fd94.png)
![plex-48](https://cloud.githubusercontent.com/assets/8826710/12246315/23114f1a-b8ae-11e5-9d3a-50540537cb40.png)
![plex-96](https://cloud.githubusercontent.com/assets/8826710/12246316/2323af8e-b8ae-11e5-8f4e-e1fc49ac7983.png)
![plex-circ](https://cloud.githubusercontent.com/assets/8826710/12246317/2324d72e-b8ae-11e5-8775-8f3e3b73b7c7.png)
![plex-circ-48](https://cloud.githubusercontent.com/assets/8826710/12246318/2326f7c0-b8ae-11e5-8714-708cbf73f23a.png)
![plex-circ-96](https://cloud.githubusercontent.com/assets/8826710/12246319/23299188-b8ae-11e5-8ee4-0bd40561e3ad.png)
![plex-outline](https://cloud.githubusercontent.com/assets/8826710/12246320/232b438e-b8ae-11e5-8e3c-8b93aeef0414.png)
![plex-outline-48](https://cloud.githubusercontent.com/assets/8826710/12246321/23337c3e-b8ae-11e5-85ce-0a714aacdd15.png)
![plex-outline-96](https://cloud.githubusercontent.com/assets/8826710/12246322/233e0af0-b8ae-11e5-94c4-fd1eed96700a.png)
![plex-simple](https://cloud.githubusercontent.com/assets/8826710/12246323/233e5686-b8ae-11e5-89c2-cd722216ddc1.png)
![plex-simple-48](https://cloud.githubusercontent.com/assets/8826710/12246325/2345aa4e-b8ae-11e5-816b-40703383f0e9.png)
![plex-simple-96](https://cloud.githubusercontent.com/assets/8826710/12246324/23440a40-b8ae-11e5-961e-170ec358d0ab.png)
[plex.zip](https://github.com/Templarian/MaterialDesign/files/86372/plex.zip)

EMBY:
![emby](https://cloud.githubusercontent.com/assets/8826710/12246350/4a5232d8-b8ae-11e5-98b4-196b19c0ffc0.png)
![emby-48](https://cloud.githubusercontent.com/assets/8826710/12246352/4a543c54-b8ae-11e5-8c0e-7845b9974ffd.png)
![emby-96](https://cloud.githubusercontent.com/assets/8826710/12246351/4a530ee2-b8ae-11e5-9fb9-fbd132132c4b.png)
[emby.svg.zip](https://github.com/Templarian/MaterialDesign/files/86374/emby.svg.zip)

**Comment by Templarian** [comment]
[![plex](https://materialdesignicons.com/icon/plex)](https://materialdesignicons.com/icon/plex) [![emby](https://materialdesignicons.com/icon/emby)](https://materialdesignicons.com/icon/emby)
