### ISSUE TITLE
Vivaldi Icon

### ISSUE THREAD

**Issue by theatomickiwi** [Templarian/MaterialDesign#885]
I would love to see the [Vivaldi Browser](https://vivaldi.com/) icon in the site. There are other browsers and even tor, so why not?

Here is a sample of the logo:
![Vivaldi Logo](https://vivaldi.com/press/highres/icons/viv_icon.png)

**Comment by Templarian** [comment]
Right now the we're only adding brand related icons for social media and the mainstream applications.
