### ISSUE TITLE
Bread / Bakery

### ISSUE THREAD

**Issue by mactopus** [Templarian/MaterialDesign#889]
Good bread icon, nice croissant icon, so something connected with bakery

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37571686-59468874-2ad6-11e8-8b31-63a3934cd788.png)![image](https://user-images.githubusercontent.com/18645219/37571691-6b517646-2ad6-11e8-98e3-89f76cf0f158.png)
First one probably doesn't work because of the perspective. The second one is kind of bumpy when you look at the biggest size but still looks very good I think.

[Download link](https://github.com/Templarian/MaterialDesign/files/1823166/icons.zip)

**Comment by CoDEmanX** [comment]
Saw a bread icon today in a shopping center:

![image](https://user-images.githubusercontent.com/1309249/37627526-1be2a314-2bd5-11e8-9651-9e440c5d28a5.png)

**Comment by JamesCoyle** [comment]
First one should just be the front face of it and could be bread-sliced and the second one looks great.

**Comment by PeterShaggyNoble** [comment]
Agreed with @JamesCoyle, on both points. We also already have a `food-croissant` icon:

[![](https://user-images.githubusercontent.com/15157491/37648727-a80c78cc-2c27-11e8-8144-b810fbc244ac.png)](https://materialdesignicons.com/icon/food-croissant)

**Comment by Croutonix** [comment]
Something like this?
![image](https://user-images.githubusercontent.com/18645219/37688951-d6d680ac-2c78-11e8-940b-19259e63ea1b.png)
[Download link](https://github.com/Templarian/MaterialDesign/files/1831631/icons.zip)

**Comment by PeterShaggyNoble** [comment]
How would it look with one slice?

**Comment by Croutonix** [comment]
![image](https://user-images.githubusercontent.com/18645219/37745209-f4f9e0f2-2d49-11e8-9a7e-6aefdf899106.png)
[Download link](https://github.com/Templarian/MaterialDesign/files/1835683/icon.zip)

**Comment by CoDEmanX** [comment]
Really nice work @Croutonix !

Tried to recreate the one I've seen:

![image](https://user-images.githubusercontent.com/1309249/37745658-51dbb152-2d76-11e8-8224-8cb1718330fb.png)

A nice and clean icon, but it doesn't work at 24px:

![bread](https://user-images.githubusercontent.com/1309249/37745647-3e7c984c-2d76-11e8-8e3e-271e31e07ab4.png)

**Comment by CoDEmanX** [comment]
Another toast icon:

![grafik](https://user-images.githubusercontent.com/1309249/39676264-e407c268-5167-11e8-9753-0692341b980c.png)

**Comment by augustin32** [comment]
![39673599-0c87d31a-5148-11e8-97ff-b33b65d87fce](https://user-images.githubusercontent.com/14167196/39779438-d87ef62c-5311-11e8-86d2-5f090cf06ff5.png)
![39673600-0d4e5d0a-5148-11e8-8ede-f293e2621902](https://user-images.githubusercontent.com/14167196/39779439-d8ae5d5e-5311-11e8-8a5a-ec791f87ac9a.png)
![39673602-0eb6f760-5148-11e8-9fbe-1d2246d29fa5](https://user-images.githubusercontent.com/14167196/39779442-d9e6425e-5311-11e8-84d1-9437b235eba3.png)
[bread.zip](https://github.com/Templarian/MaterialDesign/files/1985430/bread.zip)

**Comment by Templarian** [comment]
[![bread-slice](https://materialdesignicons.com/icon/bread-slice)](https://materialdesignicons.com/icon/bread-slice) [![bread-slice-outline](https://materialdesignicons.com/icon/bread-slice-outline)](https://materialdesignicons.com/icon/bread-slice-outline)

**Comment by Templarian** [comment]
Moving this to the next milestone. Still not sure about the bread loaf designs.

**Comment by goyney** [comment]
[![baguette](https://materialdesignicons.com/icon/baguette)](https://materialdesignicons.com/icon/baguette)
