### ISSUE TITLE
font-size

### ISSUE THREAD

**Issue by jan-vandorpe** [Templarian/MaterialDesign#89]
webfont: the CSS rule

.mdi:before{font-size:24px!important}

prevents me from sizing the font. or what I am doing wrong?

cheers

**Comment by Templarian** [comment]
That would be a bad copy and paste on my part. That was only suppose to be in the `preview.html`.

I'll fix it tonight and do a bower update. For now just delete that style out.

Thanks for letting me know!

**Comment by Templarian** [comment]
v0.7.22 was just released. It included this fix and is updated to the current 722 icons.

Sorry about that, and thanks again for letting me know!

**Comment by jan-vandorpe** [comment]
Hi Austin, thanks for the reply, but now I have another issue with the new
download. I'm not sure what causes it:

the font seems to be very 'chunky' compared to yesterday's. It seems as if
the stylesheet is not using the a true TTF?
I don't know how I can check what the browser is using: eot, woff, ttf or
svg?

I attached a screenshot in Chrome (same in FF) of ht mid-lock-outline
symbol     [image: Inline afbeelding 2]

Jan

Jan Vandorpe,

instructeur informatica vdab Oostende

2015-01-15 8:13 GMT+01:00 Austin Andrews <notifications@github.com>:

**Comment by jan-vandorpe** [comment]
Austin, is the svg font missing from the download?

Jan

Jan Vandorpe,

instructeur informatica vdab Oostende

2015-01-15 9:54 GMT+01:00 Jan Vandorpe <jan.vandorpe@vdab.be>:

**Comment by Templarian** [comment]
SVG fonts were removed I believe and should not be used in any modern browser going forward.

Your images do not show up, you need to paste them or attach them in GitHub, not an email reply.

I did just notice that [preview.html](https://raw.githubusercontent.com/Templarian/MaterialDesign-Webfont/master/preview.html) is not included in the `bower install mdi`. That will be fixed tonight.

Ensure that you are setting the icons at an appropriate size. 1x or 2x size.

```css
p .mdi:before {
    font-size: 24px;
}
h1 .mdi:before {
    font-size: 48px;
}

**Comment by Templarian** [comment]
Oh, I just noticed what you were talking about. It looks like there may be a pretty serious bug in the font generation at the moment.

I might have to revert back that last commit from earlier.

**Comment by Templarian** [comment]
Okay... turns out the library I'm using to create fonts does not support SVG arcs... so give me a bit to write a fancy method to convert this.

The irony is that I wrote a method to convert all the curves to arcs because the file size save was 20% across all the SVG's. :-/ This will just slow down the font build process, nbd.

**Comment by Templarian** [comment]
I've fixed it, and will be building out the new font tomorrow. It's almost 3AM here. Completely recoded the font creation. While fixing it I figured I would fix it one last time for good the right way.

On the plus side I'll be writing up how users can build the font or subsets of the font locally. It can all be done through the `grunt-webfont` package (using only node).

**Comment by Templarian** [comment]
Okay, fixed. Rewrote the font creation process for v0.7.33-alpha. 

Going forward I expect this font package to be much more stable.
