### ISSUE TITLE
12dp bounding boxes for narrow icons

### ISSUE THREAD

**Issue by imogennnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn** [Templarian/MaterialDesign#890]
Google's spec shows some icons, such as dots-vertical and menu-down, as having 12dp bounding boxes instead of 24dp

**Comment by Templarian** [comment]
Can you link to this?

**Comment by imogenic** [comment]
You can see it in Google's sticker sheet for Sketch:

![screen shot 2016-01-18 at 12 47 23 pm](https://cloud.githubusercontent.com/assets/1940038/12398419/a4a3c25a-bde1-11e5-89c8-6be493a428c2.png)

**Comment by Templarian** [comment]
I think we might have hit a limitation in the backend code that will prevent this until there are large code changes. You see the font system I use in the background sets fixed size for every glyph (with validation and export tooling built around that fixed size).

- [ ] Add per icon bounding box overrides.

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
