### ISSUE TITLE
Easy way to use offline (in Photoshop)?

### ISSUE THREAD

**Issue by shane-imi** [Templarian/MaterialDesign#891]
Seems like I'm missing something major here, but I can't find an easy way to use these icons in the design process, in Photoshop.

With Fontawesome, I simply install the font locally, then copy and paste the icons from the cheat sheet to insert them in my design. With the Material Design icons I can't find any direct way to get the icons into Photoshop.

What do you suggest?

**Comment by Templarian** [comment]
Photoshop imports SVG's as smart objects when you drag and drop them in. They will stay as vector. If you double click the icon in the layer panel it should open in illustrator also.

Right click any icon and select SVG Compressed (webfont will work too probably). Then drag and drop it over.

**Comment by Templarian** [comment]
If I find some time I'll add this to the getting started page, but I feel like it might be kind of obvious. If you need pixel perfect just use the advanced export option and pick a size for the .png.

**Comment by shane-imi** [comment]
Thanks for the quick reply! I'm getting an error when I do this, so maybe I need to get a newer version of PS? I'll work with PNG files for now.

**Comment by Templarian** [comment]
Yea, I think this is a Photoshop CC only feature. You might be stuck with PNG's for now.

Don't worry this feature is coming one of these days. #127

Probably won't be for a while out though, there are like 400 other features first.

**Comment by shane-imi** [comment]
Yeah, no worries. Just wanted to make sure I wasn't missing something obvious. :)

Thanks for your help!

**Comment by CoDEmanX** [comment]
Fixed code points need to come first, otherwise the icons would change after every update of the font.

**Comment by Templarian** [comment]
Yep, that's near the very top of the 400 other features. :sweat_smile:
