### ISSUE TITLE
Little Ghost not accessible with SCSS

### ISSUE THREAD

**Issue by renaudkaczmarek** [Templarian/MaterialDesign#893]
Hi there !

great work with your Material Icon Lib.
I use it on our project > www.cosplay-it.com

I'm on the "mdi": "~1.3.41"
Today I wanted to use the "ghost" icon but It seams it's not included in the scss. Can you update the lib to make it available ?

Thanks by advance
Renaud

**Comment by Templarian** [comment]
Yea, I need to make a release timeline for the next webfont release. Really busy with the backlog of icons to add at the moment and busy.

I might add a few more icons then call 1450 a good number to release the next batch (little over 100 new icons and numerous other changes).

**Comment by renaudkaczmarek** [comment]
Nice ! Thank you very much for your work.

**Comment by Templarian** [comment]
Cool website by the way, I'm going to leave this issue opened to remind myself to release a new version.

**Comment by Templarian** [comment]
v1.4.57 just went out on NPM/Bower.

Preview: http://cdn.materialdesignicons.com/1.4.57/
