### ISSUE TITLE
Open Source and Proprietary Icons

### ISSUE THREAD

**Issue by AWMooreCO** [Templarian/MaterialDesign#894]
Requesting:
- An icon representing _something_ that is **Open Source** (code/product)
- An icon representing _something_ that is **Closed Source** or **Proprietary**

Thanks!

**Comment by CoDEmanX** [comment]
There is actually an icon for open source, but it's not well known i suppose:

![open source](http://entermediadb.org/wp-content/uploads/2015/02/Open-Source-Icon.png)

No idea about proprietary software.

**Comment by PeterShaggyNoble** [comment]
+1 for the Open Source logo. The single colour version is just the outline of the icon. SVG [here](https://commons.wikimedia.org/wiki/File:Opensource.svg)

![](https://opensource.org/files/osi_black_and_white_light_backgrounds_logo.png)

**Comment by MrGrigri** [comment]
I believe we should only add the outline, but I've contributed both just in case.

![image](https://user-images.githubusercontent.com/4528551/46356169-6d9b9a00-c61f-11e8-8b83-f820ee9fd76f.png) ![image](https://user-images.githubusercontent.com/4528551/46356211-8015d380-c61f-11e8-8ef7-eacd75c7a27c.png)

[open-source-initiative.zip](https://github.com/Templarian/MaterialDesign/files/2438350/open-source-initiative.zip)

**Comment by Templarian** [comment]
[![open-source-source](https://materialdesignicons.com/icon/open-source-initiative)](https://materialdesignicons.com/icon/open-source-initiative)
