### ISSUE TITLE
Bird

### ISSUE THREAD

**Issue by SuicSoft** [Templarian/MaterialDesign#895]
We already have a cat so why not add a dog and a bird

**Comment by Templarian** [comment]
Dog is already requested #736. Renaming this issue to just bird.

**Comment by CoDEmanX** [comment]
For the time being, maybe the Twitter icon is of some use.

**Comment by JamesCoyle** [comment]
Can we get some example images or icons?

**Comment by KTibow** [comment]
@JamesCoyle Here's some icons:
https://www.google.com/search?q=bird+icon

**Comment by Templarian** [comment]
@KTibow Paste images into the github comment box. Generally we're looking for icons that match the material style to go off of. 👍

**Comment by KTibow** [comment]
Bird by Jens Tärning from the Noun Project
![Bird icon](https://user-images.githubusercontent.com/10727862/83950014-69eced00-a7dc-11ea-9aa7-cfff2dd66508.png)

**Comment by goyney** [comment]
Here is a Materialized version of the supplied sample. I also made the beak bigger as it wasn't discernible at native resolution.
![image](https://user-images.githubusercontent.com/1015040/89344664-38758e00-d674-11ea-9ea4-52422669ec70.png)
[bird.svg.zip](https://github.com/Templarian/MaterialDesign/files/5024575/bird.svg.zip)

**Comment by goyney** [comment]
[![bird](https://materialdesignicons.com/icon/bird)](https://materialdesignicons.com/icon/bird)
