### ISSUE TITLE
database icon

### ISSUE THREAD

**Issue by Tallyb** [Templarian/MaterialDesign#9]

**Comment by CoDEmanX** [comment]
Some variant I tried out:
![database](https://cloud.githubusercontent.com/assets/1309249/10835284/1384d20c-7ea1-11e5-9dd1-0a8dcb042eba.png)

Yes, it does have perspective, but so do other stock MD icons such as layers, school / mortarboard, archive...

**Comment by Templarian** [comment]
I like yours more, can you link to the .svg. I'll use that as the style and replace the other database icons.

**Comment by CoDEmanX** [comment]
Here you go: https://www.dropbox.com/s/f5m4uh25z438ok1/database.svg?dl=0

I'm not sure if it needs to be made narrower to allow for plus, minus, "x" and possibly other variants. A networked version could also be handy, but not sure if the icon isn't too tall...

**Comment by Tallyb** [comment]
WOW! thanks.

**Comment by Templarian** [comment]
These were all replaced before the release yesterday. Forgot to close the issue. :smile:

**Comment by Templarian** [comment]
Oh, one thing database-outline was deprecated. I don't feel it was that useful and didn't fit with the new style.

**Comment by CoDEmanX** [comment]
Hm, they don't show in the history?

I feel the plus and minus versions can be slightly improved by removing some of the fine details caused by the margin. Maybe a rectangular margin to avoid the small kinks?

**Comment by Templarian** [comment]
Yea, the way I updated them didn't update the history table. It's an issue if it's for another user and I update from my account. I have this fixed need to deploy it with my other changes.

I can replace them if you want to make modified versions. Really a just a quick fix at 1am since I use these icons in our client's app.

**Comment by CoDEmanX** [comment]
Here you go:
https://www.dropbox.com/s/kiejfzokh5a3c68/database-minus.design?dl=0
https://www.dropbox.com/s/0c4vf9h0bz5h4ml/database-plus.design?dl=0

**Comment by CoDEmanX** [comment]
Plus and minus variants got updated, no more kinks.
