### ISSUE TITLE
Alias Icon Names (for Search).

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#90]
Aliasing icons would allow icons to be searched under alternative names. For instance...

``` text
eyedropper, colorize, pipet
```

This will allow icons to keep relatively standard naming while allowing easier lookup by users.

**Comment by danielhickman** [comment]
Original Name | Proposed Name(s) / Tag(s)
--------------------|--------------------------
appnet | alpha
arrow-down-bold-circle(outline) | download-alt
arrow-up-bold-circle(outline) | upload-alt
arrow-expand | fullscreen, popout
arrow-collapse | exit-fullscreen, poopin
attachment | paperclip, attach
auto-fix | enhance
account-remove | contact-block
blinds | backdrop
camera-timer | self-timer
camera-iris | shutter (camera-shutter)
folder-plus | folder-add, folder-new

Just some ideas, adding some of that to the tags could be helpful

**Comment by Templarian** [comment]
Awesome. Feel free to keep editing your comment with others, this feature is still being coded in.

**Comment by danielhickman** [comment]
Updated with other ideas

**Comment by Templarian** [comment]
Awesome, keep them coming. I'm spending all day coding out a lot more features for the History (aka Changelog), but after this feature is done this issue will be next.

I'm going to be adding a special thanks section for "non icon" contributors in the future. Definitely couldn't manage all these issues/features myself.

**Comment by samosfator** [comment]
@Templarian tried to find question icon today and after manual scrolling discovered it under `help` alias.

| **Original name** | **Proposed name**      |
| ---------------------- | ---------------------------- |
| help, help circle    |  question, *feedback?*|

**Comment by Templarian** [comment]
I just started putting the database changes in to support this feature. Going out for drinks tonight, so there won't be any progress, but I hope to have it coded this week.

**Comment by Templarian** [comment]
This feature has been added. I've only added aliases for the ones @samosfator suggested so far.

If you click on an icon and it has aliases it will list them similar to how tags are listed.

Middle of playing Assassin's Creed Unity. I'll close the issue once I add the aliases in the list above.

**Comment by CoDEmanX** [comment]
There are a lot of possible aliases for icons, although I would rather think of them as "associations".
`hotel` for instance could be aliased with `bed`, `sleep`, and maybe even `night` (although I would rather use that term for a moon icon).

Is there a preferred way to contribute @Templarian? Just a markdown table like the ones above, or would a certain format make your work easier? (e.g. JSON in a certain structure, CSV, ...)

**Comment by Templarian** [comment]
Make a markdown chart similar to how it was done above and add it to a comment. I'll go through and add a checkmark to them once I add them. This is actually the next big issue I have after this new export feature.

I have tracking on all the search results that show this is a needed feature.

**Comment by Templarian** [comment]
Closing this issue, the new site will have a more streamlined way to managing aliases (and related icons).
