### ISSUE TITLE
Update step-forward icon with different contributed version (aka step-forward2b), rename to slow-forward

### ISSUE THREAD

**Issue by IanSav** [Templarian/MaterialDesign#901]
The icon is not the preferred version. The one with a smaller gap between the elements was preferred. The better version is named step-forward2b on CoDEmanX's design review page.

Also this icon should be named slow-forward to better differentiate and reflect the meaning of the icon.

**Comment by CoDEmanX** [comment]
@IanSav: icons are updated, not renamed though.

**Comment by Templarian** [comment]
I don't think I'm going to be renaming them because when I search online for the names the images that come up match what they currently are called.
