### ISSUE TITLE
Video edit icon

### ISSUE THREAD

**Issue by sunshinetpu** [Templarian/MaterialDesign#902]
I want a video edit icon

**Comment by CoDEmanX** [comment]
Would Google's new movie filter icon work for you?
http://www.google.com/design/icons/#ic_movie_filter

**Comment by infanf** [comment]
![movie-edit](https://cloud.githubusercontent.com/assets/8826710/12019960/e07c289c-ad76-11e5-9189-9a7e86ec73ab.png)
![movie-edit-48](https://cloud.githubusercontent.com/assets/8826710/12019961/e1fd10a0-ad76-11e5-9fbd-e19ef16a4e07.png)
![movie-edit-96](https://cloud.githubusercontent.com/assets/8826710/12019962/e32a40ec-ad76-11e5-8646-6d7c2165aa0f.png)
zipped SVG:
[movie-edit.zip](https://github.com/Templarian/MaterialDesign/files/73257/movie-edit.zip)

**Comment by sunshinetpu** [comment]
Yes, it's great. Thank you very much

**Comment by Templarian** [comment]
Removing the contribution label. This needs a different cut out.

**Comment by JamesCoyle** [comment]
Need to fix the cutout on this and also add the movie-filter icon from google.

**Comment by goyney** [comment]
[![movie-filter](https://materialdesignicons.com/icon/movie-filter)](https://materialdesignicons.com/icon/movie-filter)[![movie-outline](https://materialdesignicons.com/icon/movie-outline)](https://materialdesignicons.com/icon/movie-outline)

**Comment by goyney** [comment]
[![movie-edit](https://materialdesignicons.com/icon/movie-edit)](https://materialdesignicons.com/icon/movie-edit)[![movie-edit-outline](https://materialdesignicons.com/icon/movie-edit-outline)](https://materialdesignicons.com/icon/movie-edit-outline)
