### ISSUE TITLE
CD icon

### ISSUE THREAD

**Issue by vykintazo** [Templarian/MaterialDesign#905]
I think compact disk icon would be useful.

**Comment by CoDEmanX** [comment]
We do have an album icon, but it resembles an LP if I read it correctly:
https://materialdesignicons.com/icon/album

**Comment by CoDEmanX** [comment]
![disk](https://cloud.githubusercontent.com/assets/1309249/11769038/ad7f3ee6-a1de-11e5-874c-6124269fc7cb.png) derived from disk error icon https://www.dropbox.com/s/28f8fxv4rmzjgs0/disk.design?dl=0
![cd2](https://cloud.githubusercontent.com/assets/1309249/11769037/ad7da176-a1de-11e5-8cc9-dbfd4bd3444d.png) more specific https://www.dropbox.com/s/7hvwyw94gxyjh3d/cd2.design?dl=0

**Comment by vykintazo** [comment]
Thank you!
2015 gruod. 13 22:30 "CoDEmanX" <notifications@github.com> rašė:

**Comment by CoDEmanX** [comment]
Two experimental variants:

![cd5](https://cloud.githubusercontent.com/assets/1309249/12306474/49ff5102-ba3a-11e5-98a9-956eee8ff5db.png) Could be used as icon for "album"
![cd4](https://cloud.githubusercontent.com/assets/1309249/12306475/4a04de10-ba3a-11e5-9294-f2e5927d3be4.png) Looks a bit like a life belt...

**Comment by Templarian** [comment]
Little late replying, but I added the disk icon. It would be useful to add a `compact-disk` icon as well as the `album-box`.

[![disk](https://materialdesignicons.com/icon/disk)](https://materialdesignicons.com/icon/disk)

**Comment by CoDEmanX** [comment]
You mean these two? ![cd2](https://cloud.githubusercontent.com/assets/1309249/11769037/ad7da176-a1de-11e5-8cc9-dbfd4bd3444d.png) ![cd5](https://cloud.githubusercontent.com/assets/1309249/12306474/49ff5102-ba3a-11e5-98a9-956eee8ff5db.png) Could be used as icon for "album"

I'll add them to an icon pack and post them in #420.

**Comment by goyney** [comment]
Removing the Contribution label since no source SVG was provided.

**Comment by JamesCoyle** [comment]
I'm gonna close this out as we have the `disc` icon which should cover most cases. If there is need to differentiate between disc types then I'd recommend using the official format logo such as CD ROM or DVD. It may be worth requesting them over at [simple icons](https://simpleicons.org/).
