### ISSUE TITLE
Graph

### ISSUE THREAD

**Issue by mantenie** [Templarian/MaterialDesign#910]
Can you create an icon that shows a graph?
Something like a network or a tree graph?

**Comment by CoDEmanX** [comment]
How would you describe the following icon? It's graphy, yet very symmetric, which not all graphs are:
![web2](https://cloud.githubusercontent.com/assets/1309249/11847500/19dd6b6c-a41e-11e5-8fca-3261c584bbdb.png)

**Comment by mantenie** [comment]
It looks nice. But it is a graph, where all icons are connected to each other.
That does unfortunately not fit to my case.

**Comment by Templarian** [comment]
@mantenie Do you have an example of what this would look like. I think we may be stuck on ideas.

**Comment by zorkin82** [comment]
I'm looking for such a icon too.

Example:
https://www.iconfinder.com/icons/523303/connection_mesh_network_network_node_network_topology_web_web_mesh_icon#size=128

**Comment by CoDEmanX** [comment]
The closest I got:

![graph](https://cloud.githubusercontent.com/assets/1309249/15396849/2f1990e8-1dde-11e6-975b-e768952d6261.png)

![graph-tree](https://cloud.githubusercontent.com/assets/1309249/15397137/44dfe1e2-1ddf-11e6-9cb6-d9b538ad14b3.png) ![graph-tree3](https://cloud.githubusercontent.com/assets/1309249/15397302/f449a6a4-1ddf-11e6-98d4-07b92b0c3313.png)

**Comment by mantenie** [comment]
@CoDEmanX Yeah! That's great.

**Comment by CoDEmanX** [comment]
![grafik](https://user-images.githubusercontent.com/1309249/38639490-ab0e297e-3dd1-11e8-8163-043012d6a9e1.png) Google Cloud networking icon

Maybe make it slightly bigger?

![grafik](https://user-images.githubusercontent.com/1309249/38639966-26ffa994-3dd3-11e8-90f8-33ea7e4a5430.png)

**Comment by mridulpj** [comment]
Here's a solid version of @CoDEmanX graph-tree that I used for my project.
![genealogy](https://user-images.githubusercontent.com/26104747/41532523-fe90f2ac-7314-11e8-843f-78a3a9ebf7dd.png)

**Comment by goyney** [comment]
Removing the Contribution label since no source SVG was provided.

**Comment by mridulpj** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 509 511"><defs><style>.a,.b{stroke:#000;stroke-width:12px;}.b{fill:none;}</style></defs><title>tree</title><circle cx="444" cy="446" r="65"/><circle cx="349" cy="258" r="65"/><circle cx="250" cy="65" r="65"/><circle cx="153" cy="254" r="65"/><circle cx="65" cy="446" r="65"/><circle cx="251" cy="446" r="65"/><line class="a" x1="250" y1="65" x2="65" y2="446"/><line class="b" x1="251" y1="446" x2="158.23" y2="254"/><line class="b" x1="444" y1="446" x2="250" y2="65"/></svg>`[](url)

[tree.zip](https://github.com/Templarian/MaterialDesign/files/2614687/tree.zip)

**Comment by HassanMehmood1992** [comment]
![image](https://user-images.githubusercontent.com/17563392/60976300-7bb0e080-a33e-11e9-812d-99199d605fe2.png)
something along this line.

**Comment by CoDEmanX** [comment]
Looks like a UML or BPM diagram to me. Is that your purpose, or what kind of graph do you mean?

**Comment by HassanMehmood1992** [comment]
Hi,

I work in aviation field and we are integrating different sources like
email, data sources, services so it is like all sort of integration. I
couldn't find any specific type of icon which might fit to our need.
I couldn't come up with something integrating in to a single source. that
was a general idea behind it .

Regards

**Comment by goyney** [comment]
@CoDEmanX @HassanMehmood1992 I believe you are meaning to have this conversation in #4236.

**Comment by CoDEmanX** [comment]
Oh yeah, strange... In my email client the "integration" request showed with the title of this issue...

**Comment by goyney** [comment]
[![graph](https://materialdesignicons.com/icon/graph)](https://materialdesignicons.com/icon/graph)[![graph-outline](https://materialdesignicons.com/icon/graph-outline)](https://materialdesignicons.com/icon/graph-outline)
