### ISSUE TITLE
Letters

### ISSUE THREAD

**Issue by amfp** [Templarian/MaterialDesign#911]
Single letters
A
B
C
D
.....

**Comment by amfp** [comment]
uppp

**Comment by amfp** [comment]
http://1.bp.blogspot.com/-f51kGA8ZOPI/UWZ80U4kRWI/AAAAAAAAATQ/_4teYxcT2-M/s1600/Sin+t%C3%ADtulo.png

**Comment by CoDEmanX** [comment]
Can you please explain why you can't use just text for that?

**Comment by amfp** [comment]
In some cases I have to create the ImagenIcon icon to JFrame and JDialog . With text is not possible .

**Comment by amfp** [comment]
You can make a B as an example?

**Comment by MrGrigri** [comment]
I've already got each letter in one file. However, they are just the capital letters, no lower case, or punctuation. [alphabet.zip](https://github.com/Templarian/MaterialDesign/files/448210/alphabet.zip)

![l](https://cloud.githubusercontent.com/assets/4528551/18145216/72147f70-6f87-11e6-90d3-b16c16758a3a.png) ![e](https://cloud.githubusercontent.com/assets/4528551/18145224/79e0e46e-6f87-11e6-9e4f-32e88a2b7701.png) ![t](https://cloud.githubusercontent.com/assets/4528551/18145229/834f3744-6f87-11e6-94af-80399bfad4bc.png) ![t](https://cloud.githubusercontent.com/assets/4528551/18145229/834f3744-6f87-11e6-94af-80399bfad4bc.png) ![e](https://cloud.githubusercontent.com/assets/4528551/18145234/8fe265e4-6f87-11e6-83a8-890d6a162a7c.png) ![r](https://cloud.githubusercontent.com/assets/4528551/18145243/9784c4a4-6f87-11e6-980e-dcfc2baddbd2.png) ![s](https://cloud.githubusercontent.com/assets/4528551/18145250/a16d4d88-6f87-11e6-9c94-5733b22f0c67.png)

**Comment by PeterShaggyNoble** [comment]
Closing in favour of #1299
