### ISSUE TITLE
T-Rex

### ISSUE THREAD

**Issue by AdrielChonq** [Templarian/MaterialDesign#913]
A dinosaur icon like Google Dinosaur

**Comment by CoDEmanX** [comment]
You mean this one?

![Imgur](http://i.imgur.com/ZkN38gA.jpg)

It's not quite the style we have in MDI...

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback.

**Comment by CoDEmanX** [comment]
Materialized Chrome Downasaur:

![grafik](https://user-images.githubusercontent.com/1309249/72946020-f347d980-3d7d-11ea-9f4e-3dcdcdfde76e.png)

[dinosaur-chrome.zip](https://github.com/Templarian/MaterialDesign/files/4100695/dinosaur-chrome.zip)

Suggested name: `google-downasaur` with alias `pixel-dinosaur`

**Comment by CoDEmanX** [comment]
Went with `dinosaur-pixel` as alias, as we might add additional dinosaurs which would probably follow the convention `dinosaur-<subtype>`.
