### ISSUE TITLE
Incognito Icon

### ISSUE THREAD

**Issue by dietrichg** [Templarian/MaterialDesign#914]
Would be nice to have an incognito icon. To let the user know stealth mode is active.

**Comment by infanf** [comment]
![incognito](https://cloud.githubusercontent.com/assets/8826710/12035030/8d4a2f30-ae38-11e5-8b30-c3e9f60ad6ab.png)
![incognito-48](https://cloud.githubusercontent.com/assets/8826710/12035031/8f91404e-ae38-11e5-8b40-c47338a511be.png)
![incognito-96](https://cloud.githubusercontent.com/assets/8826710/12035034/91f00ac8-ae38-11e5-9928-3c445d061dcf.png)
zipped SVG
[incognito.zip](https://github.com/Templarian/MaterialDesign/files/73956/incognito.zip)

**Comment by Templarian** [comment]
[![incognito](https://materialdesignicons.com/icon/incognito)](https://materialdesignicons.com/icon/incognito)
