### ISSUE TITLE
Status bar

### ISSUE THREAD

**Issue by SalimMahdAlmas** [Templarian/MaterialDesign#915]
we want systemui icon

**Comment by CoDEmanX** [comment]
Please post an example

**Comment by AndroidFire** [comment]
i am not good at photo editing
i want like this
 
------
------
  \/

**Comment by CoDEmanX** [comment]
I don't know what you mean, but guessing from your ASCII art, it should look like

![system-menu](https://cloud.githubusercontent.com/assets/1309249/11914638/1e0fc6ac-a686-11e5-864d-ecc71a09cac9.png)

**Comment by PeterShaggyNoble** [comment]
Closing due to lack of feedback. @SalimMahdAlmas, if you can provide an example, we'll revisit this issue. You can attach image files to comments by following the instructions below the `textarea`.
