### ISSUE TITLE
Using MDI alongside Bootstrap's Glyphicons CSS override

### ISSUE THREAD

**Issue by dagjomar** [Templarian/MaterialDesign#916]
In a current project, I am running with default Bootstrap's Glyphicons.

I tried the "Getting started" guide to add MDI to the project, but found that the extra css that needed to be specified did not work for me. I have a lot of custom font-sizing on elements to adjust the glyphicon  here and there, and so the explicit font-size specification of the .mdi classes messed things up.

I found that by removing all the "Additional Bootstrap Specific CSS" overrides and replacing it with a simple

```
/* Bootstrap Custom MDI-specific override */
.mdi{
  -webkit-transform: scale(1.4); 
      -ms-transform: scale(1.4); 
          transform: scale(1.4); 
}
```

worked just fine!

I checked by using the CodePen example (http://codepen.io/templarian/pen/bdgoVQ) and adding some side-by-side glyphicons vs mdi examples (which is another idea to consider)

EDIT:

Actually, this also worked fine:

```
    .mdi {
      font-size: 1.4em;
      vertical-align: sub;
      margin-bottom: -0.4em;
    }
```

**Comment by Templarian** [comment]
Marking this a question/bug. On vacation at the moment. When I get back I'll look into this change.

Need to test it in the codepen below, if it looks better I'll update the CSS.
http://codepen.io/templarian/pen/bdgoVQ?editors=110

**Comment by Templarian** [comment]
Closing this if it's still an issue let me know. The docs for the new site are in Bootstrap 4.

http://dev.materialdesignicons.com/getting-started/bootstrap
