### ISSUE TITLE
Sticker Icon

### ISSUE THREAD

**Issue by andrew-codechimp** [Templarian/MaterialDesign#918]
Like Trello's sticker icon, a circle with the bottom right quarter folded into the circle.

**Comment by CoDEmanX** [comment]
This one?
![sticker](https://cloud.githubusercontent.com/assets/1309249/11957897/cd377676-a8c4-11e5-89d6-516c70e3b8bb.png)

Related: #810

**Comment by andrew-codechimp** [comment]
That's the one!

**Comment by infanf** [comment]
![sticker](https://cloud.githubusercontent.com/assets/8826710/12019786/1cbf9d5e-ad75-11e5-8a4c-52aaf5a55c6f.png)
![sticker-48](https://cloud.githubusercontent.com/assets/8826710/12019787/1e4eca50-ad75-11e5-94a0-5693c4fcf692.png)
![sticker-96](https://cloud.githubusercontent.com/assets/8826710/12019789/1f9ed6c0-ad75-11e5-9e97-d8829a6cb4dc.png)
zipped SVG:
[sticker.zip](https://github.com/Templarian/MaterialDesign/files/73243/sticker.zip)

**Comment by andrew-codechimp** [comment]
Nice, thanks for that :)

**Comment by infanf** [comment]
Alternative:
![sticker-alt](https://cloud.githubusercontent.com/assets/8826710/12034833/9bf3dace-ae36-11e5-8bad-90256b5d21f8.png)
![sticker-alt-48](https://cloud.githubusercontent.com/assets/8826710/12034835/9dffacd0-ae36-11e5-8d4b-54873f43e935.png)
![sticker-alt-96](https://cloud.githubusercontent.com/assets/8826710/12034836/9f8ce388-ae36-11e5-827c-4d975d7df846.png)
[sticker-alt.zip](https://github.com/Templarian/MaterialDesign/files/73952/sticker-alt.zip)

**Comment by Templarian** [comment]
[![sticker](https://materialdesignicons.com/icon/sticker)](https://materialdesignicons.com/icon/sticker)

(cleaned up the vector paths to remove a bunch of points).
