### ISSUE TITLE
"Explore/Community" icon

### ISSUE THREAD

**Issue by ompemi** [Templarian/MaterialDesign#92]
Would be good to have an icon for the action of discover or explore. Similar to the one attached, or a "world" icon.

![screen shot 2015-01-15 at 11 35 17 am](https://cloud.githubusercontent.com/assets/120906/5761660/d333e45a-9caa-11e4-9917-f7f0e3b76f62.png)

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/airballoon

Let me know if this looks right.

**Comment by ompemi** [comment]
It's perfect, thanks
