### ISSUE TITLE
Child pick-up and drop off icon

### ISSUE THREAD

**Issue by peterhav** [Templarian/MaterialDesign#922]
I'm looking for an icon that indicates a child pick up and a icon for child drop-off. This icons for use in a child daycare app.
Attached a first try (it's a XML vector drawable stored as *.txt)

Best regards,
Peter

[kid_pickup.txt](https://github.com/Templarian/MaterialDesign/files/71217/kid_pickup.txt)

**Comment by CoDEmanX** [comment]
That's a nice icon, but it's hardly recognizable at 24 pixels:

![kid_pickup](https://cloud.githubusercontent.com/assets/1309249/12312870/4c748866-ba63-11e5-9c36-4cb9b2f8ac31.png)
![kid_pickup_96](https://cloud.githubusercontent.com/assets/1309249/12312871/4c74db68-ba63-11e5-85a2-442c3059b558.png)

Maybe Google's new generic child care icon works too?
https://design.google.com/icons/#ic_child_care

**Comment by Templarian** [comment]
I think this is too detailed and not material enough. Also, the child care icon looks more like a monkey. :laughing:

**Comment by PeterShaggyNoble** [comment]
Given that this is within the context of a childcare app, wouldn't `car` suffice to communicate the act of dropping off/collecting a child or the location where to do so? Or, as it's not clear exactly what you *are* trying to communicate, one of the `clock` icons for the drop off/collection times?

**Comment by MrGrigri** [comment]
Closing because the `Consider Closing` label was added more than 10 days ago.
