### ISSUE TITLE
Tooth icon

### ISSUE THREAD

**Issue by SeidiJr** [Templarian/MaterialDesign#923]

**Comment by infanf** [comment]
![tooth](https://cloud.githubusercontent.com/assets/8826710/12203427/3c2fd72c-b62f-11e5-837b-8fc1fa99573c.png)
![tooth-48](https://cloud.githubusercontent.com/assets/8826710/12203428/3c3118ee-b62f-11e5-8191-85aefdc84815.png)
![tooth-96](https://cloud.githubusercontent.com/assets/8826710/12203429/3c37232e-b62f-11e5-969d-4868d541d366.png)
[tooth.zip](https://github.com/Templarian/MaterialDesign/files/82975/tooth.zip)

**Comment by Templarian** [comment]
[![tooth](https://materialdesignicons.com/icon/tooth)](https://materialdesignicons.com/icon/tooth)
