### ISSUE TITLE
Gnome Shell

### ISSUE THREAD

**Issue by flipflop97** [Templarian/MaterialDesign#924]
Can we have an icon for gnome-shell for linux?

It looks like this:
https://www.gnome.org/wp-content/themes/gnome-grass/images/gnome-logo.png (official website)
https://cdn2.iconfinder.com/data/icons/system-flat-buttons/512/gnome-128.png (flat)

**Comment by infanf** [comment]
![gnome](https://cloud.githubusercontent.com/assets/8826710/12019814/584bac28-ad75-11e5-80fa-d1f855a26fdd.png)
![gnome-48](https://cloud.githubusercontent.com/assets/8826710/12019816/5b0ac458-ad75-11e5-860b-aa023640c855.png)
![gnome-96](https://cloud.githubusercontent.com/assets/8826710/12019817/5cede7e6-ad75-11e5-8674-2ec9e0b20137.png)
zipped SVG:
[gnome.zip](https://github.com/Templarian/MaterialDesign/files/73247/gnome.zip)

**Comment by Templarian** [comment]
[![gnome](https://materialdesignicons.com/icon/gnome)](https://materialdesignicons.com/icon/gnome)
