### ISSUE TITLE
Google Translate Icon

### ISSUE THREAD

**Issue by dGorod** [Templarian/MaterialDesign#928]
Could you, please, add icon of "translation"? It's useful in app to indicate multilingual support of something.
Examples:
![google-translate-icon](https://cloud.githubusercontent.com/assets/1834315/12007604/2c8f0a6a-ac14-11e5-9f4a-f346d50d20e5.png)
![google_translate_icon](https://cloud.githubusercontent.com/assets/1834315/12007607/3481ed1e-ac14-11e5-962d-be728153e672.png)

**Comment by infanf** [comment]
![google-translate](https://cloud.githubusercontent.com/assets/8826710/12019756/b7512438-ad74-11e5-9f7c-b93405a6df9e.png)
![google-translate-48](https://cloud.githubusercontent.com/assets/8826710/12019758/bee69066-ad74-11e5-8cc2-7bbbbc88e579.png)
![google-translate-96](https://cloud.githubusercontent.com/assets/8826710/12019760/c0eb025c-ad74-11e5-90ee-346ac33a29ae.png)

SVG zipped:

[google-translate.zip](https://github.com/Templarian/MaterialDesign/files/73237/google-translate.zip)

**Comment by dGorod** [comment]
Thank you.

**Comment by Templarian** [comment]
[![google-translate](https://materialdesignicons.com/icon/google-translate)](https://materialdesignicons.com/icon/google-translate)
