### ISSUE TITLE
Jeepney icon

### ISSUE THREAD

**Issue by anjocerdena** [Templarian/MaterialDesign#929]
I'm contributing this jeepney icon. GitHub doesn't allow SVG or AI file uploads in issues though so I attached a PDF instead with Illustrator editing capabilities preserved.

[jeepney.pdf](https://github.com/Templarian/MaterialDesign/files/72964/jeepney.pdf)

**Comment by Templarian** [comment]
[![jeepney](https://materialdesignicons.com/icon/jeepney)](https://materialdesignicons.com/icon/jeepney)
