### ISSUE TITLE
how to contribute icons?

### ISSUE THREAD

**Issue by REJack** [Templarian/MaterialDesign#93]
Hi Templarian,

i've created 7 account icons how i can give it to you?

**Comment by Templarian** [comment]
If you attach a PNG to a reply in github, I'll look them over and just give you a contributor invite.

Just need to make sure they fit the Material Design style.

**Comment by Templarian** [comment]
http://materialdesignicons.com/custom Use this to test your SVG files also (contributor portal uses a similar import).

**Comment by REJack** [comment]
![account-close](https://cloud.githubusercontent.com/assets/1554582/5768226/03f2996a-9d0f-11e4-8d31-b3f9a1686b96.png) ![account-key](https://cloud.githubusercontent.com/assets/1554582/5768228/03f630d4-9d0f-11e4-888b-36f7993a2f81.png) ![account-key-variant](https://cloud.githubusercontent.com/assets/1554582/5768225/03f25202-9d0f-11e4-9fc4-9c3565f54276.png) ![account-minus](https://cloud.githubusercontent.com/assets/1554582/5768229/03f641b4-9d0f-11e4-90fe-8946c9b32479.png) ![account-search](https://cloud.githubusercontent.com/assets/1554582/5768227/03f6146e-9d0f-11e4-8712-e9c4041d26f6.png) ![account-star](https://cloud.githubusercontent.com/assets/1554582/5768230/03f7f130-9d0f-11e4-8838-b64422981245.png) ![account-star-variant](https://cloud.githubusercontent.com/assets/1554582/5768231/0408d9b4-9d0f-11e4-8977-f0583f80c7fd.png)

thats the 7 account icons 
account-close
account-key
account-key-variant
account-minus
account-search
account-star
account-star-variant

**Comment by REJack** [comment]
i cant upload an svg on the button to test my SVG files

**Comment by Templarian** [comment]
Can you do me a favor and cleanup the key icon so it is more pixel perfect. (and leave off the key variant, it loses too much detail at that size).

Share your email and I'll send an invite (I'll delete it out of the comment once the invite is sent).

**Comment by REJack** [comment]
info@rejack.de

**Comment by REJack** [comment]
i need to look how it works with the Expression Design 4 ^^
i'm a PS user

**Comment by Templarian** [comment]
Wait, are these in SVG vector files?

**Comment by REJack** [comment]
i created all of these icons with Expression Desgin 4
i've exported SVG's with inkscape too 
the PNG's are export from Expression Design 4

**Comment by Templarian** [comment]
I would suggest exporting the SVG's with Expression Design / Adobe Illustrator. I haven't tested Inkscape exports yet (they may work, they may not).

**Comment by REJack** [comment]
How i can export SVG's in Expression Design?

**Comment by Templarian** [comment]
CTRL+E, Select SVG on the drop down

![image](https://cloud.githubusercontent.com/assets/338885/5768657/64994412-9cd8-11e4-97d4-edbd18111f65.png)

**Comment by REJack** [comment]
i have it not there :sweat_smile: do you use the free version of Expression Design?

**Comment by Templarian** [comment]
Expression Design 4 is Free. It's the only version.

**Comment by REJack** [comment]
i have an older version of Expression Design 4 ^^ i uploaded the account-key now in Contributor Portal you can take a look over it :smile: 

in the next minutes i upload the other 5 icons

**Comment by Templarian** [comment]
Looks good, Please set a name and some info in the profile section at the right of contributor portal.

**Comment by REJack** [comment]
i cant press the update button for the infos in the profile section

**Comment by Templarian** [comment]
Did you upload a 100x100 avatar, input a name and a bio? I think those are the fields required for that form. I should go back and put error messages.

**Comment by REJack** [comment]
i cant upload an avatar too

**Comment by Templarian** [comment]
I just tried on my user and it worked. A 100x100 PNG (Exactly, since didn't code resize)?

Haven't really touched those API calls in forever, should still work like it did for the others.

**Comment by REJack** [comment]
if i click on the "Import Avatar" button nothing happens

**Comment by REJack** [comment]
i use Firefox and Internet Explorer both nothing happens

**Comment by REJack** [comment]
in Chrome it works i updated the infos

**Comment by Templarian** [comment]
Oh yea, Issue #81 someone told me about the other day, forgot.

If you could use a photo or company logo that would be great. Thanks.

Welcome aboard! Be sure to reference the other icons as you add more. Stay very consistent with the style guidelines/naming (2px width for all lines and all that).

**Comment by REJack** [comment]
i need to make new pics then i change the avatar
i commented on the issue 81

**Comment by Templarian** [comment]
I want to go over the changes I made to your icons... pretty only affected 3 of them.

* account-close renamed to account-remove
* account-key pixel perfect 2px wide lines. This is very important for consistency.
* account-search same as account key.

Thanks again for joining the contributor team. One thing I always have to remind myself when making these is if it doesn't fit the style it probably needs to look different than the first iteration. There is almost always a way to keep the 2px radius / 2px width rules while getting the icon to be instantly recognizable.
