### ISSUE TITLE
3DS Icon

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#930]

**Comment by Pyroglyph** [comment]
There is one being ported over from http://modernuiicons.com/ that you could use.

**Comment by REJack** [comment]
But ModernUIIcons and MaterialDesign don't have the same icon styles.
ModernUIIcons is in Windows 8 / Windows 8 Phone Icon Style
MaterialDesign is in Andoid 5 Icon Style with a predefined Guide from Google

**Comment by REJack** [comment]
@GreenTurtwig do you mean "Nintendo 3DS" or "3DS File Format"?

**Comment by GreenTurtwig** [comment]
As in the Nintendo 3DS, forgot there were other things with the same name. :-P

**Comment by REJack** [comment]
@GreenTurtwig  xD i created fast a [Nintendo-3DS](https://www.rejack.us/MDI/nintendo-3ds.svg) and [Nintendo-3DS-Variant](https://www.rejack.us/MDI/nintendo-3ds-variant.svg) icon. 
PNG Example: ![Nintedo-3DS](https://www.rejack.us/MDI/nintendo-3ds.png)
PNG Example Variant: ![Nintedo-3DS-Variant](https://www.rejack.us/MDI/nintendo-3ds-variant.png)

It should fit in the MDI Package.
If Templarian accept it for the Package, i can add the .design-File

**Comment by Templarian** [comment]
I don't think those will work well for a 3DS icon. There might be too much detail required to represent the device (meaning it may not be possible to include it).

**Comment by REJack** [comment]
I knew its too detailed for the MDI Package, but he can use it if its ok for him :smile:

**Comment by GreenTurtwig** [comment]
It's fine for the moment, although it is more of a DS icon. :-)

**Comment by REJack** [comment]
@GreenTurtwig they are all pretty the same. :smiley: 
An other way would only take the "3DS"-Font as icon, but i think it would too much detailed.
![Nintedo DS Logos](http://i.imgur.com/EhDPvFB.png)

**Comment by GreenTurtwig** [comment]
What I was thinking of was the console itself, like the icon for a controller. :-)

**Comment by REJack** [comment]
i would say its detailed for a icon. on 24p you couldn't recognize it right.

**Comment by GreenTurtwig** [comment]
I guess it would, would be a similar design to [this](https://materialdesignicons.com/icon/google-controller) if anything.

**Comment by GreenTurtwig** [comment]
Another possibility is just having text like this.
![image](https://cloud.githubusercontent.com/assets/15905797/12128214/cb2df500-b3f3-11e5-8ca3-8ab0dfccba7b.png)

**Comment by GreenTurtwig** [comment]
After reading through my old "requests" I don't think this is easily transferable to an icon. So I'm going to close it. :cat2:
