### ISSUE TITLE
Music Icon Request

### ISSUE THREAD

**Issue by niteshkhatri** [Templarian/MaterialDesign#932]
Hi, I appreciate your effort of providing material icons to everyone for free.

I think should be a music icon like below

![music](https://cloud.githubusercontent.com/assets/7664984/12032620/22989de0-ae40-11e5-978d-390dd8022aa5.jpg)

Thanks.

**Comment by PeterShaggyNoble** [comment]
[![music](https://user-images.githubusercontent.com/15157491/33828379-c6bf669c-de63-11e7-9161-f754699448ed.png)](https://materialdesignicons.com/icon/music)
