### ISSUE TITLE
Money icon

### ISSUE THREAD

**Issue by KingSora** [Templarian/MaterialDesign#934]

**Comment by infanf** [comment]
![money](https://cloud.githubusercontent.com/assets/8826710/12039569/d6a37b90-ae61-11e5-8185-03477bb98e8b.png)
![money-48](https://cloud.githubusercontent.com/assets/8826710/12039571/d7ffed70-ae61-11e5-9a9a-fb52605b75a7.png)
![money-96](https://cloud.githubusercontent.com/assets/8826710/12039575/d939e2ae-ae61-11e5-9aea-0c463c8b16a6.png)
![money-multi](https://cloud.githubusercontent.com/assets/8826710/12039578/daf20f5e-ae61-11e5-838b-f7a71758de16.png)
![money-multi-48](https://cloud.githubusercontent.com/assets/8826710/12039580/dbcf51b6-ae61-11e5-87b5-9a14aaa53933.png)
![money-multi-96](https://cloud.githubusercontent.com/assets/8826710/12039581/dd57bc94-ae61-11e5-83e5-db726ad81634.png)
zipped SVGs
[money.zip](https://github.com/Templarian/MaterialDesign/files/74243/money.zip)

**Comment by infanf** [comment]
Alternative Euro
![money-euro-multiple](https://cloud.githubusercontent.com/assets/8826710/12039709/e90807c8-ae62-11e5-8f50-6ab0a0a09b09.png)
![money-euro-multiple-48](https://cloud.githubusercontent.com/assets/8826710/12039710/ea77d6e2-ae62-11e5-9547-510a23cabd87.png)
![money-euro-multiple-96](https://cloud.githubusercontent.com/assets/8826710/12039712/ecc9a092-ae62-11e5-83d9-03b84ac7a142.png)
[money-euro.zip](https://github.com/Templarian/MaterialDesign/files/74248/money-euro.zip)

**Comment by infanf** [comment]
https://materialdesignicons.com/icon/cash
