### ISSUE TITLE
set custom name and padding

### ISSUE THREAD

**Issue by aratj** [Templarian/MaterialDesign#935]
set custom name and set any padding value no effect for icon package export (

**Comment by Templarian** [comment]
@aratj How would custom padding work for the package export? It exports tons of icons and sizes at various sizes. Color/name are definitely coming (and are partially coded).

**Comment by aratj** [comment]
set padding size for test 50

1) save single icon, it work.
2) but select "icon package" -> androis 4.x action bar . extract from zip.  padding ignored, set default size
