### ISSUE TITLE
Glassdoor icon

### ISSUE THREAD

**Issue by mindnuts** [Templarian/MaterialDesign#937]
Hi, Would it be possible for you to add a new icon for "glassdoor.com" website. We incorporate reviews from glassdoor and would like an icon for it. Below is the image of the icon from their website.

Regards
M

![](https://press-content.glassdoor.com/app/uploads/files_mf/icon1024x1024.jpg)

**Comment by infanf** [comment]
![glassdoor](https://cloud.githubusercontent.com/assets/8826710/12063500/255fd0f4-afb0-11e5-94fc-dfc665b20e63.png)
![glassdoor-48](https://cloud.githubusercontent.com/assets/8826710/12063501/26e6c72a-afb0-11e5-9e80-217da42559e5.png)
![glassdoor-96](https://cloud.githubusercontent.com/assets/8826710/12063502/28f67e8e-afb0-11e5-98b5-59aa6e55f673.png)
zipped SVG:
[glassdoor.zip](https://github.com/Templarian/MaterialDesign/files/75486/glassdoor.zip)

**Comment by Templarian** [comment]
This is borderline social media, but I think it is widely used enough to be included.

**Comment by Templarian** [comment]
[![glassdoor](https://materialdesignicons.com/icon/glassdoor)](https://materialdesignicons.com/icon/glassdoor)

**Comment by mindnuts** [comment]
@Templarian  Thanks!!

**Comment by mindnuts** [comment]
@Templarian  We upgraded to V1.4.57 yet the glassdoor icon is not visible.

**Comment by Templarian** [comment]
@mindnuts https://materialdesignicons.com/history To see what was included in the last release. I usually build the icon pack every month. Use an inline vector until it is included.
