### ISSUE TITLE
Blender Icon?

### ISSUE THREAD

**Issue by Pyroglyph** [Templarian/MaterialDesign#938]
Icon for the Blender 3D modelling software.
http://blender.org/

**Comment by infanf** [comment]
![blender](https://cloud.githubusercontent.com/assets/8826710/12071528/0f997ed0-b0b1-11e5-9020-98681e17774a.png)
![blender-48](https://cloud.githubusercontent.com/assets/8826710/12071529/0f9d7328-b0b1-11e5-9f95-09aa43a5d7b1.png)
![blender-96](https://cloud.githubusercontent.com/assets/8826710/12071530/0fb1990c-b0b1-11e5-91a4-d382b1b8f1f2.png)
[blender.svg.zip](https://github.com/Templarian/MaterialDesign/files/75968/blender.svg.zip)

**Comment by CoDEmanX** [comment]
It's not allowed to alter the Blender logo:

> The logo is used unaltered, without fancy enhancements, in original colors, original typography, and always complete (logo + text blender).

http://www.blender.org/about/logo/

**Comment by Templarian** [comment]
Yea, as this goes against their guidelines directly and is a rather specific icon request that doesn't fall into social media branding I think it will be easier to simply not include it.

**Comment by Templarian** [comment]
I added it anyway since I think it could be useful for files etc.

[![blender](https://materialdesignicons.com/icon/blender)](https://materialdesignicons.com/icon/blender)
