### ISSUE TITLE
Microsoft logo

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#940]
There's a Windows logo but no Microsoft logo, Apple and Google both have one.

**Comment by REJack** [comment]
the Microsoft Logo are only 4 Tiles with different colors, there is no Monochrom variant. 
And the Logo need "Microsoft" everytime there. [M$ Logo Guidelines](https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx?2dae0d7c-896b-40d1-93ad-f9ac82ab7d05=True)

**Comment by Templarian** [comment]
Yea, we've ran into the limitation with a lot of company logos. Realistically there are very few times you will need to use the MS logo directly, most will use the Windows logo when referencing the OS.

I've included it, but I would highly recommend following the [guidelines](https://www.microsoft.com/en-us/legal/intellectualproperty/trademarks/usage/logo.aspx) (which I link to in the description for this icon also).

[![Microsoft](https://materialdesignicons.com/icon/microsoft)](https://materialdesignicons.com/icon/microsoft)

**Comment by GreenTurtwig** [comment]
Mainly for a Microsoft account in a password manager.
