### ISSUE TITLE
Amplifier icon

### ISSUE THREAD

**Issue by ericlindesvard** [Templarian/MaterialDesign#942]
Type Marshall stack.

**Comment by infanf** [comment]
![amplifier](https://cloud.githubusercontent.com/assets/8826710/12159008/396d610e-b4df-11e5-9ede-96c1547a0005.png)
![amplifier-48](https://cloud.githubusercontent.com/assets/8826710/12159006/396ae078-b4df-11e5-8c85-6a8d017c55f7.png)
![amplifier-96](https://cloud.githubusercontent.com/assets/8826710/12159007/396c56f6-b4df-11e5-81db-87b0fda2769f.png)
[amplifier.svg.zip](https://github.com/Templarian/MaterialDesign/files/80581/amplifier.svg.zip)

**Comment by Templarian** [comment]
@infanf Added, but slightly modified to be inside of the 20x20 area.

[![amplifier](https://materialdesignicons.com/icon/amplifier)](https://materialdesignicons.com/icon/amplifier)
