### ISSUE TITLE
Discord icon

### ISSUE THREAD

**Issue by Chris92de** [Templarian/MaterialDesign#944]
Discord is a new voice- and text communication app that's starting to grow quickly, especially in the gaming community.

Can we have an icon for this in the font please? 
![discord-logo-color](https://cloud.githubusercontent.com/assets/5523125/12078465/0683650e-b214-11e5-9e0f-e65772f13ef4.png)

**Comment by Templarian** [comment]
[![discord](https://materialdesignicons.com/icon/discord)](https://materialdesignicons.com/icon/discord)

Got this icon down to 85 points. Their official one is very messy, tons of unnecessary points. This will be in Sunday's release.
