### ISSUE TITLE
Add infanf as contributor

### ISSUE THREAD

**Issue by Templarian** [Templarian/MaterialDesign#945]
Add @infanf as a contributor.

- 100x100 photo, twitter, email (will delete from comment once added), name, github (assuming this one). 

Reply to this with the above to get added. Still fixing bugs in the backend, so you won't be able to login just yet, but I can assign the various icons that you added to the account (sorry to ask, but let me know which once you added so far, I never really kept track, sorry).

**Comment by infanf** [comment]
I'm honered :smile: Thank You

Choose Your favourite :wink: 
![pp100](https://cloud.githubusercontent.com/assets/8826710/12087129/cdbdd782-b2d0-11e5-8533-4dfd93ce25c6.jpg)![8826710-100](https://cloud.githubusercontent.com/assets/8826710/12087154/f9ebca1c-b2d0-11e5-9af2-7710c085c757.jpg)

* @infanf
* christopher@infanf.de
* Christopher Schreiner
* @infanf

**Comment by infanf** [comment]
* blender
* google-translate

The others are not part of the icon set yet

**Comment by Templarian** [comment]
https://materialdesignicons.com/contributor/Christopher-Schreiner

The google one is assigned to Google (it's how the Google ones are tracked).

**Comment by Templarian** [comment]
Your a contributor on the repo now. Don't do a commits please, but this will let you manage the issues and label. Please use the icon request / contribution tags on any you add. :smile:
