### ISSUE TITLE
tick mark Icon was missing 

### ISSUE THREAD

**Issue by sarudsgnr** [Templarian/MaterialDesign#946]

**Comment by Templarian** [comment]
Do you mean the [check](https://materialdesignicons.com/icon/check) icon?

**Comment by sarudsgnr** [comment]
Thank you very much I have searched for tick mark, sorry to bother you



On Mon, Jan 4, 2016 at 9:12 PM, Austin Andrews <notifications@github.com>
wrote:

> Do you mean the check <https://materialdesignicons.com/icon/check> icon?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Templarian/MaterialDesign/issues/946#issuecomment-168710765>
> .
>



-- 
*Sarath Kumar*
*UI/UX designer *
*www.sstudios.org <http://www.sstudios.org>*
Mob : *+917204536153*
Skype : *saru_sarath*
