### ISSUE TITLE
Animal and gender icons

### ISSUE THREAD

**Issue by MartijnLindeboom** [Templarian/MaterialDesign#947]
Hi I would like some general icons for animals and persons
- [ ] ~~dog~~ (duplicate of #736)
- [ ] tiger
- [ ] ~~bird~~ (duplicate of #895)
- [x] pig
- [ ] rabbit
- [ ] mouse
- [ ] snake
- [ ] mammals
- [ ] reptiles
- [x] fish
- [x] female
- [x] male

**Comment by Templarian** [comment]
`pig` and `fish` exist. Do you have an example of `mammals`, `reptiles`?

**Comment by CoDEmanX** [comment]
Mammals... well if PEGI 16 is acceptable maybe:

( . )( . )

**Comment by MartijnLindeboom** [comment]
haha yes well clearly i didn't think this through, mammals and reptiles are more a class so a bit difficult to sum up in one icon. No example found so just skip.  

Extra note: 
Female and male icons: i know there are gender icons for them. I would like to see icons like the ones we see on toilet doors etc. Or just split the human-male-female icon

**Comment by omarmallat** [comment]
well, sorry for interruption again. I am looking also for human male and female icons to be used in xaml. is there any option to split them in the xaml from the existing combined icon? then we can solve at least that problem rather than waiting for new icons?

**Comment by CoDEmanX** [comment]
A bit off-topic, but FontAwesome has the following symbols:

- genderless
- neuter
- mars-stroke-h
- mars-stroke-v
- mars-stroke
- venus-mars
- mars-double
- venus-double
- transgender-alt
- transgender
- mercury
- mars
- venus

We already have mars (gender-male), venus (gender-female), transgender (gender-male-female) and transgender-alt (gender-transgender) in MDI. We should probably add at least neuter, or maybe all of the remaining.

**Comment by NikoKrause** [comment]
I suggest a bee or a bumblebee icon.

I want to use it for this application: http://bumblebee-project.org/

**Comment by Templarian** [comment]
Closing this issue (cleaning up the backlog).

Please open individual icon requests for each of these if they are still needed (with examples). A lot of these already have individual requests I believe.
