### ISSUE TITLE
icon "new"

### ISSUE THREAD

**Issue by Islamov** [Templarian/MaterialDesign#948]
text label [new], when we have notified about new:
- new product
- new partner
- new anything else.

some like this, http://www.flaticon.com/free-icon/mark-as-unread-envelope-button_61047
but with text in [new]

**Comment by CoDEmanX** [comment]
Like this?
https://design.google.com/icons/#ic_fiber_new

**Comment by Templarian** [comment]
[![new-box](https://materialdesignicons.com/icon/new-box)](https://materialdesignicons.com/icon/new-box)
