### ISSUE TITLE
VLC icon

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#949]
![image](https://cloud.githubusercontent.com/assets/15905797/12121812/3492f4b6-b3cf-11e5-986b-10b5d0a73c40.png)

**Comment by CoDEmanX** [comment]
Should be added as generic pylon, not as brand icon IMO.

**Comment by Templarian** [comment]
Yea, kind of agreed. Could be used as their logo, but it's essentially just a construction cone.

**Comment by GreenTurtwig** [comment]
Yep, having a traffic cone seems reasonable

**Comment by infanf** [comment]
![cone](https://cloud.githubusercontent.com/assets/8826710/12158576/6c5bb146-b4db-11e5-8666-7d55507342e3.png)
![cone-48](https://cloud.githubusercontent.com/assets/8826710/12158577/6c5c16d6-b4db-11e5-8618-23dc52cc249e.png)
![cone-96](https://cloud.githubusercontent.com/assets/8826710/12158578/6c5f8a6e-b4db-11e5-9934-921ba65adb9c.png)
[cone.svg.zip](https://github.com/Templarian/MaterialDesign/files/80554/cone.svg.zip)

**Comment by Templarian** [comment]
[![vlc](https://materialdesignicons.com/icon/vlc)](https://materialdesignicons.com/icon/vlc)

@infanf In the future try to keep it inside of the 20x20 area.

**Comment by Templarian** [comment]
Unless it doesn't look nice, then outside of 20x20 is fine.
