### ISSUE TITLE
Icon for zipcode or pincode

### ISSUE THREAD

**Issue by muditagarwal** [Templarian/MaterialDesign#951]

**Comment by infanf** [comment]
![pin](https://cloud.githubusercontent.com/assets/8826710/12170845/e492a87c-b544-11e5-8dd9-8e23c5db7fb3.png)
![pin-48](https://cloud.githubusercontent.com/assets/8826710/12170846/e4955a54-b544-11e5-9681-14c9d629558a.png)
![pin-96](https://cloud.githubusercontent.com/assets/8826710/12170847/e49646d0-b544-11e5-894c-998d2f2049fd.png)
[pin.svg.zip](https://github.com/Templarian/MaterialDesign/files/81151/pin.svg.zip)

**Comment by muditagarwal** [comment]
@infanf : Thanks for the icon but this is for PIN (password). I am looking for zipcode / pincode / postal code.

**Comment by infanf** [comment]
makes sense -.-

**Comment by CoDEmanX** [comment]
I don't think there's any common icon that depicts "zipcode". A pure text version doesn't work either, because it's not international enough - in German it's Postleitzahl (PLZ) for instance - and it can be confused with ZIP compressed archives. I can only think of a letter icon with a pound on it.

**Comment by nileshmax** [comment]
Hello, even I'm looking for similar icon.
![untitled-2](https://cloud.githubusercontent.com/assets/18612757/14739119/239023ea-08a3-11e6-88a8-0b994ea8f6ae.png)

**Comment by CoDEmanX** [comment]
Looks like a hydrant to me... I guess mailboxes look very different in everywhere.

**Comment by Templarian** [comment]
Going to close this issue out. I don't think there is an ideal icon for this.
