### ISSUE TITLE
File Types

### ISSUE THREAD

**Issue by secretgspot** [Templarian/MaterialDesign#953]
pdf, html, flash, zip and so on

**Comment by Templarian** [comment]
Do you mean like `file-*` icons (pdf exists by the way)?

**Comment by yannick9906** [comment]
Maybe some icons which has the extesion as text in it, like the alphabetical icons looks like

**Comment by JamesCoyle** [comment]
The issue with text is that it is illegible with small icon size. You can only really fit two characters maximum which wouldn't work well for file extensions. Personally I use the most appropriate icon for the file type content. 

I find `file-xml` works great for markup languages and there are several media format icons available too. In #1240 I'm suggesting some more additions such as curly braces for languages such as javascript, actionscript, c++ etc. I'm working on a file icon package for atom and I'm finding it is actually better to have one icon for multiple file types as it gets to a point where there are too many different icons and it is just as hard to differentiate them.
