### ISSUE TITLE
OpenID icon for Websites

### ISSUE THREAD

**Issue by ensarman** [Templarian/MaterialDesign#954]
may you put a OpenID icon to build websites with that icon... thanks!!!

**Comment by infanf** [comment]
![openid](https://cloud.githubusercontent.com/assets/8826710/12158751/20410c50-b4dd-11e5-91bb-a14fa2cb4d5e.png)
![openid-48](https://cloud.githubusercontent.com/assets/8826710/12158752/20584da2-b4dd-11e5-9331-70d27d6a3eec.png)
![openid-96](https://cloud.githubusercontent.com/assets/8826710/12158753/20671058-b4dd-11e5-897a-cbd95057f896.png)
[openid.svg.zip](https://github.com/Templarian/MaterialDesign/files/80566/openid.svg.zip)

**Comment by ensarman** [comment]
thanks!!!!

**Comment by Templarian** [comment]
[![openid](https://materialdesignicons.com/icon/openid)](https://materialdesignicons.com/icon/openid)
