### ISSUE TITLE
bible

### ISSUE THREAD

**Issue by TarcisoTorres** [Templarian/MaterialDesign#955]
- [x] `church-bible`
- [x] `check-list`

**Comment by infanf** [comment]
Bible:
![bible](https://cloud.githubusercontent.com/assets/8826710/12202732/9f96a95c-b62b-11e5-8a98-23cf11244c53.png)
![bible-48](https://cloud.githubusercontent.com/assets/8826710/12202733/9f982e26-b62b-11e5-9cec-0019ddba20b0.png)
![bible-96](https://cloud.githubusercontent.com/assets/8826710/12202734/9fc274c4-b62b-11e5-8c8f-e3f3bfff7419.png)
[bible.zip](https://github.com/Templarian/MaterialDesign/files/82928/bible.zip)

**Comment by infanf** [comment]
Checklist is the same request as in #814

**Comment by Templarian** [comment]
@infanf Wait for me to add them to the site before closing. Thanks. :+1:

**Comment by Templarian** [comment]
[![bible](https://materialdesignicons.com/icon/bible)](https://materialdesignicons.com/icon/bible)
