### ISSUE TITLE
Variant of an already available icon "mdi-arrow-bottom-drop-circle" outline ?

### ISSUE THREAD

**Issue by enieff** [Templarian/MaterialDesign#956]
Hi, 

I'll need the "mdi-arrow-bottom-drop-circle" in outline version if this is possible ?
I made it to show what I want.
![mdi-arrow-bottom-drop-circle-outline](https://cloud.githubusercontent.com/assets/16595195/12186292/9db88ca2-b5a1-11e5-9683-02879e476f3b.png)

Thanks a lot, 

Enieff

**Comment by enieff** [comment]
I don't know how i can put this icon (i have made in Illustrator) to the 3 size svg file.
and is that it is possible to add it in the font tag noon to enjoy the tag mdi mdi-name

Thanks a lot

**Comment by infanf** [comment]
![arrow-bottom-drop-circle-outline - kopie 3](https://cloud.githubusercontent.com/assets/8826710/12202529/a90df536-b62a-11e5-8b25-a73efe0a7329.png) ![arrow-bottom-drop-circle-outline - kopie](https://cloud.githubusercontent.com/assets/8826710/12202528/a909bc0a-b62a-11e5-9957-eb3b6198aaa4.png) ![arrow-bottom-drop-circle-outline 2](https://cloud.githubusercontent.com/assets/8826710/12202531/a910e980-b62a-11e5-8dbe-f80d9904209f.png) ![arrow-bottom-drop-circle-outline](https://cloud.githubusercontent.com/assets/8826710/12202530/a90fa930-b62a-11e5-9b02-d63c8288ec26.png)
![arrow-bottom-drop-circle-outline-48](https://cloud.githubusercontent.com/assets/8826710/12202539/b601053a-b62a-11e5-9b85-fe6be6acac15.png)
![arrow-bottom-drop-circle-outline-96](https://cloud.githubusercontent.com/assets/8826710/12202538/b5fff096-b62a-11e5-9c41-cb3130dd4bcb.png)
[arrow-bottom-drop-circle-outline.zip](https://github.com/Templarian/MaterialDesign/files/82919/arrow-bottom-drop-circle-outline.zip)

**Comment by CoDEmanX** [comment]
The triangles look off-center, do they use the exact same positioning as in the filled versions? If so, then I wouldn't change anything, because some users might want to use filled and outline variants together (e.g. hover effect), hence positioning should be identical

**Comment by infanf** [comment]
Yes it is the same Position. The original also looks off center.

**Comment by Templarian** [comment]
Yea, I think we should change the stock Google icon. to make it look nice in an outline variant. This can be done by either making the arrow taller or moving it 1px down. Might take a few tries to get it visually correct to the eye.

**Comment by infanf** [comment]
I already tried. Best result when moving the arrow down 0.5px.

**Comment by CoDEmanX** [comment]
It should stay on the grid. How about changing the circle size?

**Comment by enieff** [comment]
At what point do the icons required, once created, are added to the font ?

**Comment by enieff** [comment]
At what point do the icons required, once created, are added to the font?

**Comment by Templarian** [comment]
@enieff I do the font builds monthly'ish. More random than anything. Probably in a month though.

**Comment by enieff** [comment]
is a lot of work for making the font?

**Comment by Templarian** [comment]
Yea, I have to click a button and wait 30 seconds.

**Comment by enieff** [comment]
I understand better now why this is 1X by month ^^

**Comment by Templarian** [comment]
[![arrow-left-drop-circle-outline](https://materialdesignicons.com/icon/arrow-left-drop-circle-outline)](https://materialdesignicons.com/icon/arrow-left-drop-circle-outline) [![arrow-right-drop-circle-outline](https://materialdesignicons.com/icon/arrow-right-drop-circle-outline)](https://materialdesignicons.com/icon/arrow-right-drop-circle-outline) [![arrow-up-drop-circle-outline](https://materialdesignicons.com/icon/arrow-up-drop-circle-outline)](https://materialdesignicons.com/icon/arrow-up-drop-circle-outline) [![arrow-down-drop-circle-outline](https://materialdesignicons.com/icon/arrow-down-drop-circle-outline)](https://materialdesignicons.com/icon/arrow-down-drop-circle-outline)

And (renamed from `bottom` to `down`)...

[![arrow-left-drop-circle](https://materialdesignicons.com/icon/arrow-left-drop-circle)](https://materialdesignicons.com/icon/arrow-left-drop-circle) [![arrow-right-drop-circle](https://materialdesignicons.com/icon/arrow-right-drop-circle)](https://materialdesignicons.com/icon/arrow-right-drop-circle) [![arrow-up-drop-circle](https://materialdesignicons.com/icon/arrow-up-drop-circle)](https://materialdesignicons.com/icon/arrow-up-drop-circle) [![arrow-down-drop-circle](https://materialdesignicons.com/icon/arrow-down-drop-circle)](https://materialdesignicons.com/icon/arrow-down-drop-circle)
