### ISSUE TITLE
Counter

### ISSUE THREAD

**Issue by Mirandadevs** [Templarian/MaterialDesign#957]
http://g01.a.alicdn.com/kf/HTB1LnCYJFXXXXbzXpXXq6xXFXXX6/Hand-Tally-font-b-Click-b-font-font-b-Counter-b-font-with-4-Digital-Number.jpg

**Comment by infanf** [comment]
![counter](https://cloud.githubusercontent.com/assets/8826710/12199372/f4b767aa-b617-11e5-8957-bcab6a69e704.png)
![counter-48](https://cloud.githubusercontent.com/assets/8826710/12199373/f4d1a6a6-b617-11e5-8815-7bb483a7223c.png)
![counter-96](https://cloud.githubusercontent.com/assets/8826710/12199374/f4d78832-b617-11e5-9310-48ee49a60da6.png)
[counter.zip](https://github.com/Templarian/MaterialDesign/files/82753/counter.zip)

**Comment by Templarian** [comment]
That's a really nice icon @infanf!

**Comment by infanf** [comment]
I also tried white-on-black alternatives, but the outline version is better in my opinion:
![counter-alt2](https://cloud.githubusercontent.com/assets/8826710/12202291/64b7fcd4-b629-11e5-8eb4-935a9756c0a5.png)
![counter-alt2-48](https://cloud.githubusercontent.com/assets/8826710/12202292/64bdb002-b629-11e5-887e-e599264ab4f2.png)
![counter-alt2-96](https://cloud.githubusercontent.com/assets/8826710/12202293/64bdbfd4-b629-11e5-8a03-eae1aba2d39b.png)
![counter-alt](https://cloud.githubusercontent.com/assets/8826710/12202295/66fddf72-b629-11e5-85a2-fe59659f0972.png)
![counter-alt-48](https://cloud.githubusercontent.com/assets/8826710/12202296/670026ba-b629-11e5-91f2-721350543bf5.png)
![counter-alt-96](https://cloud.githubusercontent.com/assets/8826710/12202297/6706c9de-b629-11e5-9dae-14a76b70623f.png)
[counter-alt.zip](https://github.com/Templarian/MaterialDesign/files/82898/counter-alt.zip)

**Comment by CoDEmanX** [comment]
Hm, the digits don't feel quite material, maybe use bold Roboto letters instead? Or the 2px pseudo font we have for some text icons?

**Comment by Templarian** [comment]
Replaced the font with roboto.

[![counter](https://materialdesignicons.com/icon/counter)](https://materialdesignicons.com/icon/counter)
