### ISSUE TITLE
Icon for "german Autobahn"

### ISSUE THREAD

**Issue by cinemarene** [Templarian/MaterialDesign#958]
Can someone create an icon for the "german Autobahn" (Highway/Freeway) ?
That would be great, thanks.

![ic_highway](https://cloud.githubusercontent.com/assets/9309569/12219223/201cf338-b73a-11e5-9e2a-bb8ef9fa497a.png)

**Comment by GreenTurtwig** [comment]
It's also the same for motorways in the UK :-)

**Comment by REJack** [comment]
austria and hungary motorways has the same icon ^^ i would say whole EU has it. 

Von meinem iPhone gesendet

**Comment by Templarian** [comment]
So what should I call it (should it be more `highway` or something less specific than `autobahn`)?

**Comment by cinemarene** [comment]
I think Highway is better but you can decide.

**Comment by GreenTurtwig** [comment]
I agree with highway. Even though we call them motorways in the UK, the term "public highway" is used for motorways, dual carriageways and other types of roads.

**Comment by REJack** [comment]
:+1:

**Comment by infanf** [comment]
![highway](https://cloud.githubusercontent.com/assets/8826710/12237252/1bf26136-b87e-11e5-8051-b60bfa0c9a46.png)
![highway-48](https://cloud.githubusercontent.com/assets/8826710/12237253/1c0beb24-b87e-11e5-8994-603cc202e8b1.png)
![highway-96](https://cloud.githubusercontent.com/assets/8826710/12237254/1c17bc42-b87e-11e5-8684-9ddf0452c313.png)
[highway.zip](https://github.com/Templarian/MaterialDesign/files/85922/highway.zip)

**Comment by cinemarene** [comment]
Awesome, thank you :)

**Comment by CoDEmanX** [comment]
Some fun associations:

- weird church building
- somewhat broken metronome
- limbo street

**Comment by Templarian** [comment]
[![highway](https://materialdesignicons.com/icon/highway)](https://materialdesignicons.com/icon/highway)

There is also an alias for `autobahn`.

**Comment by REJack** [comment]
nice :+1:
