### ISSUE TITLE
"Presentation" icon request

### ISSUE THREAD

**Issue by kyleparker** [Templarian/MaterialDesign#96]
Would love to have a "presentation" icon - I have one for 4.x, but it needs a material make-over...

http://www.androidicons.com/assets/images/ai-mdpi-black/ic_action_present.png

Thanks - the other icons are amazing.

**Comment by Templarian** [comment]
http://materialdesignicons.com/icon/presentation

**Comment by kyleparker** [comment]
Thank you!
