### ISSUE TITLE
Riot Games icon

### ISSUE THREAD

**Issue by HBillaud** [Templarian/MaterialDesign#960]
I think the Riot Games icon should be added

![](https://p2.zdassets.com/hc/theme_assets/43400/200033224/footer-riotfist.png)

**Comment by Templarian** [comment]
Far too specific to add a video game company. The icon pack also only includes social media or chat application iconography.

Sorry.

**Comment by HBillaud** [comment]
But how about the Xbox, Playstation, and Steam icon that were added

**Comment by CoDEmanX** [comment]
Those are well known platforms, which makes them relevant.

**Comment by HBillaud** [comment]
Riot Games created the most played PC game

![screenshot 4](https://cloud.githubusercontent.com/assets/13498916/12225095/427c1e68-b7d0-11e5-9562-c0f9a8742ec8.png)

**Comment by Templarian** [comment]
That's nice for them, but I can't include just every company logo or the pack would be half company logos and that isn't helpful for 99% of users of the pack.

**Comment by HBillaud** [comment]
oh ok I understand
