### ISSUE TITLE
Icon classes without .mdi- prefix

### ISSUE THREAD

**Issue by gligoran** [Templarian/MaterialDesign#961]
I'd like to have icon classes follow the pattern ```.mdi.<icon-name>``` instead of ```.mdi-<icon-name>```. Currently the only solution of doing this is to manually modify the ```@for``` loop in ```_icons.scss```, but that would get overwritten on next update or reinstall of the bower component.

I see a few possible solutions for this.

1) Add a separator variable to be used in the ```@for``` loop instead of a hardcoded ```-```.

2) Split the ```@for``` loop out of ```_icons.scss``` (leave the original arrays ```$hexes``` and ```$names```, and two functions in there), so one can include those, but not run the loop automatically.

Hope this wouldn't be too much of a problem to implement.

**Comment by CoDEmanX** [comment]
`.mdi.<icon-name>` is actually not a naming pattern, but two CSS classes. In an HTML attribute, they would be assigned like `foo="mdi someicon"`. Since some icons have very short and generic names, you would easily run into name conflicts and thus I dislike the idea.

**Comment by Templarian** [comment]
Yea, I definetly would advise against because of what @CoDEmanX said, but I'm not opposed to splitting out the icon list and the for loop. That would probably make future integration easier for instance if someone wanted to use a `.mdi.mdiAccount` naming scheme.

**Comment by gligoran** [comment]
I get it and have actually thought of it. In my own app, I'm willing to accept any possible issues that would arise.

The split would be appreciate, so devs like me can pick and choose which parts we take. Also the ```.mdi.mdi-account``` is better fitted if you want to use the web-font with angular material's ```mdIcon``` directive.

**Comment by Templarian** [comment]
This was resolved in the `v1.6.50` release. Thanks!
