### ISSUE TITLE
New icon design late for medication

### ISSUE THREAD

**Issue by hlinkpt** [Templarian/MaterialDesign#962]
I find it extremely hard to find an icon that can convey the idea that you are late and should hurry up. Example I'm designing an app for pill reminder and im trying to play around with the concept of a snail or a turtle to let the user know that that medication is already due and he is late. Cheers to all of you and thanks for maintaining this awesome project.

**Comment by REJack** [comment]
a pill with a clock for already due and a strikethroughed clock for to late would be able

**Comment by infanf** [comment]
Maybe a more general icon would be better than clock with pill. Strikethrough clock doesn't look like a clock anymore:
![template](https://cloud.githubusercontent.com/assets/8826710/12242221/0ea99b4c-b898-11e5-991f-372789b57005.png)
How about this?
![clock-urgent](https://cloud.githubusercontent.com/assets/8826710/12242099/5a325212-b897-11e5-9966-bfcace55711b.png)
![clock-urgent-48](https://cloud.githubusercontent.com/assets/8826710/12242098/5a2de880-b897-11e5-8217-9c346b1f8677.png)
![clock-urgent-96](https://cloud.githubusercontent.com/assets/8826710/12242100/5a36919c-b897-11e5-9189-839975aa30e8.png)
[clock-urgent.zip](https://github.com/Templarian/MaterialDesign/files/86162/clock-urgent.zip)

**Comment by CoDEmanX** [comment]
2px margin, exclamation mark aligned with clock borders:
![clock-alert](https://cloud.githubusercontent.com/assets/1309249/12245200/96812224-b8a7-11e5-9fcf-8755b0f48ee9.png)
![clock-alert_96](https://cloud.githubusercontent.com/assets/1309249/12245201/9683e572-b8a7-11e5-8abf-e99160bd2d9f.png)
https://www.dropbox.com/s/pp6tvnjz6gp79v9/clock-alert.svg?dl=0

**Comment by hlinkpt** [comment]
Thanks guys for your help :+1:

**Comment by Templarian** [comment]
[![clock-alert](https://materialdesignicons.com/icon/clock-alert)](https://materialdesignicons.com/icon/clock-alert)

Thanks @infanf, but I think the basic structure of @CoDEmanX fits the Material Design style more cleanly.
