### ISSUE TITLE
Minecraft icon

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#964]
Similar in style to the Pocket Edition icon or the desktop icon

**Comment by Templarian** [comment]
Meh, just went with the creeper, not sure the block would have worked.

[![minecraft](https://materialdesignicons.com/icon/minecraft)](https://materialdesignicons.com/icon/minecraft)

**Comment by GreenTurtwig** [comment]
Ooh, looks better than a block anyway :-P
