### ISSUE TITLE
Visual Studio icon

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#965]

**Comment by infanf** [comment]
![visualstudio](https://cloud.githubusercontent.com/assets/8826710/12262445/4c4bb35a-b928-11e5-8ca0-576caf592eb5.png)
![visualstudio-48](https://cloud.githubusercontent.com/assets/8826710/12262447/4c4edc42-b928-11e5-93b3-a3737c8ee85a.png)
![visualstudio-96](https://cloud.githubusercontent.com/assets/8826710/12262446/4c4c3672-b928-11e5-859b-677a4f21731f.png)
[visualstudio.zip](https://github.com/Templarian/MaterialDesign/files/87176/visualstudio.zip)

**Comment by GreenTurtwig** [comment]
Yep that looks perfect. :-)

**Comment by Templarian** [comment]
[![visualstudio](https://materialdesignicons.com/icon/visualstudio)](https://materialdesignicons.com/icon/visualstudio)
