### ISSUE TITLE
icon for graph

### ISSUE THREAD

**Issue by gndps** [Templarian/MaterialDesign#966]
there should be an icon for graph / stocks
Here's the sample:

![graph](https://cloud.githubusercontent.com/assets/2575880/12262105/a0589760-b94b-11e5-8c7c-72f835fd58ea.png)

[graph.svg.zip](https://github.com/Templarian/MaterialDesign/files/87142/graph.svg.zip)

**Comment by JamesCoyle** [comment]
What about these? Search for chart to find them.

![image](https://cloud.githubusercontent.com/assets/10384436/12948528/88d4fab4-cffa-11e5-8ca5-b19e5113efaa.png)

**Comment by CoDEmanX** [comment]
There's also https://materialdesignicons.com/icon/trending-up, not sure if it's possible to combine the bar chart icon with the trending arrow in terms of space

**Comment by Templarian** [comment]
[![finance](https://materialdesignicons.com/icon/finance)](https://materialdesignicons.com/icon/finance)
