### ISSUE TITLE
Icon Help.svg

### ISSUE THREAD

**Issue by aljachimiak** [Templarian/MaterialDesign#967]
I noticed the help.svg looks a bit weird at larger sizes.

I'm happy to make a pull request with a cleaned up svg.  However, your contribution guidelines say *not* to.

Let me know if you'd like the pull request.  Or, just close this issue.

Thanks,

Al

**Comment by Templarian** [comment]
Yea, you're right, looks like the curve got messed up somehow. You can just attach the SVG here if you have a fixed version or one of the contributors will look into it.

**Comment by aljachimiak** [comment]
Ok - Attaching improved help.svg to this issue.  Unfortunatly, github wouldn't let me attach a .svg.  So I changed the file extension to .txt.   Just change it back and you'll have the svg that inkscape spit out.

Also, I've attached a .gif showing the difference.

-Al
![help_svg_edits](https://cloud.githubusercontent.com/assets/1467678/12295749/0ecf19f0-b9d1-11e5-8078-6687292f4434.gif)


[help.txt](https://github.com/Templarian/MaterialDesign/files/88907/help.txt)

**Comment by Templarian** [comment]
Nice fix, will get it in tonight. Thanks!

**Comment by Templarian** [comment]
Thanks! Fixed on the site.

[![help](https://materialdesignicons.com/icon/help)](https://materialdesignicons.com/icon/help)
