### ISSUE TITLE
Suggestion: Swift icon

### ISSUE THREAD

**Issue by hwesol13** [Templarian/MaterialDesign#969]
There is no Swift lang icon and it would be nice to have one.

**Comment by GreenTurtwig** [comment]
[swift.zip](https://github.com/Templarian/MaterialDesign/files/441133/swift.zip)
Actually surprised nobody has done this yet.

**Comment by Templarian** [comment]
[![language-swift](https://materialdesignicons.com/icon/language-swift)](https://materialdesignicons.com/icon/language-swift)
