### ISSUE TITLE
Classic phone with rotary dial

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#970]
Useful to represent an oldschool phone, or to distinguish between telephone connection and phone device (phone/deskphone). Not 100% happy with either though:

![phone-classic](https://cloud.githubusercontent.com/assets/1309249/12297923/c1aa633e-ba0f-11e5-95da-ede97864c77b.png)
![phone-classic2](https://cloud.githubusercontent.com/assets/1309249/12297924/c1c53c18-ba0f-11e5-8cbf-3b4589c8f606.png)

I also tried a dialpad version, but it would be off center.

**Comment by Templarian** [comment]
The first one is probably the better of the two. More material look to it.

**Comment by Templarian** [comment]
I think using the first 1 would be fine, if you eventually make a better one we can replace it.

**Comment by CoDEmanX** [comment]
Okay, although I can't think of a more material way to do this one. I tried rectangle + upper half of a circle but it doesn't look anything like a phone like that.

https://www.dropbox.com/s/am6d948fqwrvna5/phone-classic.svg?dl=0

**Comment by Templarian** [comment]
[![phone-classic](https://materialdesignicons.com/icon/phone-classic)](https://materialdesignicons.com/icon/phone-classic)
