### ISSUE TITLE
Fill opacity of desktop-tower icon not 1 in repository

### ISSUE THREAD

**Issue by CoDEmanX** [Templarian/MaterialDesign#972]
It's partially transparent, but should be solid black:

https://github.com/Templarian/MaterialDesign/blob/master/icons/svg/desktop-tower.svg?short_path=e0d1633#L4

The website version is okay.

**Comment by Templarian** [comment]
Fixed.

The icon import step just uses the path data. The repo icons are simply just the raw exports.

**Comment by CoDEmanX** [comment]
Right, I was just confused when I used the icon from repo for an illustration.
