### ISSUE TITLE
Icon for weight balance

### ISSUE THREAD

**Issue by FadwaRebhi** [Templarian/MaterialDesign#973]

**Comment by CoDEmanX** [comment]
I tried to do one a while ago, but wasn't fully satisfied. What's your opinion?

![balance-scale](https://cloud.githubusercontent.com/assets/1309249/12311919/1dc17ca2-ba5b-11e5-84f2-f2fee2b0428b.png)

**Comment by Templarian** [comment]
That actually looks pretty nice. Would connecting the scales make it look odd?

**Comment by CoDEmanX** [comment]
Not sure which one I prefer...

![balance-scale3](https://cloud.githubusercontent.com/assets/1309249/12355183/52fbfd02-bb9b-11e5-9157-b90ec9e33224.png)

**Comment by Templarian** [comment]
[![scale-balance](https://materialdesignicons.com/icon/scale-balance)](https://materialdesignicons.com/icon/scale-balance)
