### ISSUE TITLE
Are the css Content: values set in stone?

### ISSUE THREAD

**Issue by mydudechris** [Templarian/MaterialDesign#975]
I installed this library in a project a few weeks ago and have to manually overwrite the content value of other icon fonts with those from this library. For example, I'm using tinymce and in order to use these icons I replace the existing content:'' values with those used in this one.

Are you changing the values as you add new icons? Last time I checked mdi-cart was \f206 and now it's \f222. Sad to say but if that's the case then we're gonna have to see other people :-1:

**Comment by Templarian** [comment]
Duplicate #644.

Short answer yes, long answer, I have a code fix that is coming that will address this. When? No idea, but until it is fixed I would advise if you need fixed code points to use the official icon pack.
