### ISSUE TITLE
Minecraft icon is not accurate

### ISSUE THREAD

**Issue by SLembas** [Templarian/MaterialDesign#978]
The creeper's mouth is a bit not like it should be. I think you'll understand me, if you see this picture: http://minecraftfaces.com/wp-content/bigfaces/big-creeper-face.png

**Comment by Templarian** [comment]
Yea, you're right. Was off by a pixel on the height. Fixed.

[![minecraft](https://materialdesignicons.com/icon/minecraft)](https://materialdesignicons.com/icon/minecraft)
