### ISSUE TITLE
Podium

### ISSUE THREAD

**Issue by cpalosrejano** [Templarian/MaterialDesign#979]
like this one, but without trophy:
http://77.93.210.139/icon/games-podium-with-trophy-for-number-one.html

**Comment by CoDEmanX** [comment]
Here you go:

![podium](https://cloud.githubusercontent.com/assets/1309249/12451178/1c1205ca-bf88-11e5-88a6-79747c669941.png) https://www.dropbox.com/s/si343ihw62h8axy/podium.svg?dl=0

The digit is similar to a Roboto "1", but pixel-perfect. 

Roboto can be tweaked though, to have most points on the grid as well. I also shortened the foot by 1 pixel:

![podium_roboto](https://cloud.githubusercontent.com/assets/1309249/12451386/6031cce4-bf89-11e5-898e-b31ff5839469.png) https://www.dropbox.com/s/e0h5ltyervom3j8/podium_roboto.svg?dl=0

Comparison (pixel font / Roboto):

![podium](https://cloud.githubusercontent.com/assets/1309249/12451178/1c1205ca-bf88-11e5-88a6-79747c669941.png) ![podium_roboto](https://cloud.githubusercontent.com/assets/1309249/12451386/6031cce4-bf89-11e5-898e-b31ff5839469.png)

![podium_96](https://cloud.githubusercontent.com/assets/1309249/12451406/8482f9a6-bf89-11e5-855c-735b16955a3d.png) ![podium_roboto_96](https://cloud.githubusercontent.com/assets/1309249/12451407/8483eff0-bf89-11e5-9ce0-38b25eef66c0.png)

**Comment by cpalosrejano** [comment]
Many thank you!!

**Comment by CoDEmanX** [comment]
It's not added yet, re-opening so it doesn't get lost.

**Comment by cpalosrejano** [comment]
Sorry! I don't know it.

**Comment by goyney** [comment]
@CoDEmanX This should probably be updated to use the `numeric-1` icon.

**Comment by MrGrigri** [comment]
I may be biased, but I prefer #3656.

**Comment by CoDEmanX** [comment]
I also prefer the other one. We could improve this one and add it as a variant still if someone really wants it.

**Comment by Templarian** [comment]
Closing this one infavor of 3656 and change it to this milestone.
