### ISSUE TITLE
New Bing icon for 2016

### ISSUE THREAD

**Issue by anjocerdena** [Templarian/MaterialDesign#980]
<a href="http://adage.com/article/digital/microsoft-s-bing-grows-updates-logo/302133/?linkId=20349303">Bing has a new logo</a> so I made an updated version for Material Design Icons:
https://drive.google.com/file/d/0B9gitS_t4vJPSThkdFJUVm9GOEU/view?usp=sharing
This version has a few tweaks to align the points onto the grid.

If you'd prefer the original (not pixel perfect) version, I also <a href="https://drive.google.com/file/d/0B9gitS_t4vJPWFhnaXF0LVh5ZWM/view?usp=sharing">made that available</a>.

**Comment by Templarian** [comment]
Fixed. Thanks!

[![bing](https://materialdesignicons.com/icon/bing)](https://materialdesignicons.com/icon/bing)
