### ISSUE TITLE
Add an icon for wechat

### ISSUE THREAD

**Issue by sunnyfish** [Templarian/MaterialDesign#981]
Add an icon for wechat

**Comment by infanf** [comment]
![wechat](https://cloud.githubusercontent.com/assets/8826710/12391847/f51d5152-bdea-11e5-871d-53a8c5f3ceec.png)
![wechat-48](https://cloud.githubusercontent.com/assets/8826710/12391848/f539d26e-bdea-11e5-9600-d6396525dae6.png)
![wechat-96](https://cloud.githubusercontent.com/assets/8826710/12391849/f54e2d86-bdea-11e5-9619-242bd053d9e8.png)
[wechat.zip](https://github.com/Templarian/MaterialDesign/files/94329/wechat.zip)

**Comment by Templarian** [comment]
[![wechat](https://materialdesignicons.com/icon/wechat)](https://materialdesignicons.com/icon/wechat)
