### ISSUE TITLE
Google Play's "Similar" Icon

### ISSUE THREAD

**Issue by mimani** [Templarian/MaterialDesign#982]
![documents](https://cloud.githubusercontent.com/assets/1386899/12385721/f267ab70-bde4-11e5-8add-434cda4181a0.png)

**Comment by infanf** [comment]
https://materialdesignicons.com/icon/file-multiple
https://materialdesignicons.com/icon/file

**Comment by mimani** [comment]
@infanf I am not sure about the philosophy of adding new icons, But the ones you have mentioned are quire different, What is the criteria on which a new icon is added?

**Comment by Templarian** [comment]
The icon you linked is more playing cards than documents. Material Design usually aims at using the more literal representation.

It could be added as "cards".

**Comment by CoDEmanX** [comment]
How about this Google icon?

![similar](https://cloud.githubusercontent.com/assets/1309249/12396464/e5b20998-be07-11e5-8f00-90a73a3e694b.png)

They use it in the Play Store app ("similar").

Re-creation attempt:

![similar](https://cloud.githubusercontent.com/assets/1309249/12396766/7ec4c2be-be09-11e5-984f-4b264cb28d9a.png) https://www.dropbox.com/s/gpzkpltor6ljt5m/similar.svg?dl=0

**Comment by mimani** [comment]
Yes, May be I got the name wring, Please see if these can be added, These are also displayed in some devices to display no messages or no documents in a folder.

**Comment by CoDEmanX** [comment]
Or flip this icon and remove the small circle?

https://design.google.com/icons/#ic_style

**Comment by PeterShaggyNoble** [comment]
See also the recently added [`cards`](https://materialdesignicons.com/icon/cards) and [`cards-outline`](https://materialdesignicons.com/icon/cards-outline) icons, which should work here.
