### ISSUE TITLE
Add Icon for text selection

### ISSUE THREAD

**Issue by phiwut** [Templarian/MaterialDesign#983]
something like this:

![image](https://cloud.githubusercontent.com/assets/11327288/12386914/12639b80-bdc9-11e5-992e-7ab1c7ad5fdb.png)

**Comment by anjocerdena** [comment]
I'm on it, working on remaking the icons from Google Keep.

**Comment by CoDEmanX** [comment]
I re-created them myself meanwhile, will provide them soon: https://github.com/Templarian/MaterialDesign/issues/505#issuecomment-188516176

**Comment by PeterShaggyNoble** [comment]
[`marker`](https://materialdesignicons.com/icon/marker)+[`color-helper`](https://materialdesignicons.com/icon/color-helper) should fulfil this request.
