### ISSUE TITLE
Play symbol on playlist-play icon is in the wrong place

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#984]
The "play" symbol on the [playlist-play](https://materialdesignicons.com/icon/playlist-play) icon is in the wrong place. Should be in the bottom right like how the rest of the playlist icons are and in Chrome OS' [audio player](https://d13yacurqjgara.cloudfront.net/users/21258/screenshots/2444234/audio-player.png).
Also it appears Google already has an official icon for it, [here](https://design.google.com/icons/#ic_playlist_play), so it could be updated.

**Comment by GreenTurtwig** [comment]
Although Google's inconsistency strikes again with the "bars" on the icon being longer than the rest of the playlist icons. :-)

**Comment by CoDEmanX** [comment]
They added it very recently, but yeah, we should update ours.

**Comment by Templarian** [comment]
Fixed and assigned `playlist-play` to Google.

Thanks!
