### ISSUE TITLE
Globe and Globe Search Icon Request

### ISSUE THREAD

**Issue by niteshkhatri** [Templarian/MaterialDesign#985]
I request you to kindly provide a globe icon and a globe search icon in material design.

I will be thankful.

Below are a few ideas i have in mind

![image](https://cloud.githubusercontent.com/assets/7664984/12412615/00140bf0-beae-11e5-9aee-159a4e9b1c6a.png)

![image](https://cloud.githubusercontent.com/assets/7664984/12412618/06a84634-beae-11e5-84e7-72d7da693f4f.png)

![image](https://cloud.githubusercontent.com/assets/7664984/12412621/0daa851e-beae-11e5-834a-8b78831f315f.png)

Thank you.

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/earth = globe

There is no globe search, but it may be too much detail.

**Comment by niteshkhatri** [comment]
@Templarian Thank you.

**Comment by CoDEmanX** [comment]
Alternative globes (two variants):

![globe](https://cloud.githubusercontent.com/assets/1309249/12497794/4ab32c08-c09e-11e5-8b63-f4eb41211bd3.png) ![globe2](https://cloud.githubusercontent.com/assets/1309249/12497799/4dcfbd66-c09e-11e5-9b42-050523932938.png)

https://www.dropbox.com/s/hepnm6ab9ghlt0z/globe.design?dl=0
https://www.dropbox.com/s/4ihu5r5knfmfl39/globe2.design?dl=0

**Comment by PeterShaggyNoble** [comment]
@CoDEmanX's contribution above has since been added.
