### ISSUE TITLE
Grunt with MDI

### ISSUE THREAD

**Issue by stephenycchang** [Templarian/MaterialDesign#986]
Having an issue simliar to #562 

I'm having a similar problem with Grunt. 
Using the mdi bower package with Yeoman Angular.

Development, everything shows. However, on production (the dist folder), I'll get 404s on the files since it's looking for file in the specifc "styles/fonts/materialdesignicons-webfont....?v=1.2.64"". It makes sense since Grunt will minify the files to a vendor.css file.

Is there a workaround to get this to work with Grunt?

**Comment by Templarian** [comment]
Good question. I have absolutely no idea how to best handle this.

For now (and this is workaround), write a simple replace task and replace `styles/fonts/` with the correct path. Let me tweet this and see if anyone knows.

**Comment by Templarian** [comment]
How does Font Awesome handle this?

**Comment by stephenycchang** [comment]
Actually you're right. I took the Font Awesome approach. 

The Gruntfile that fixed it for me at least. 

copy: {
    dist: {
        files: [{
            expand: true,
            dot: true,
            cwd: '<%= config.app %>',
            dest: '<%= config.dist %>',
            src: [
                '*.{ico,png,txt}',
                '.htaccess',
                'images/{,*/}*.webp',
                '{,*/}*.html',
                'styles/fonts/{,*/}*.*'
            ]
        },{
            expand: true,
          dot: true,
          cwd: 'bower_components/mdi/fonts/',
          src: ['*.*'],
          dest: '<%= yeoman.dist %>/styles/fonts'
        }]
    }
}

That's the most straightforward setup I could find. The icons show up beautifully.

It's not as elegant since the console still throws a 404 on some of the icon file sources. 

If a Grunt expert has a more elegant solution that's be great as well!

Thanks!

**Comment by Templarian** [comment]
I'm going to find a way to document this on the getting started, so opening this issue back up until I do that.

**Comment by Templarian** [comment]
Closing this out we'll be tracking this in the new site.

https://github.com/Templarian/MaterialDesign-Site
