### ISSUE TITLE
Power / Reboot / Recovery

### ISSUE THREAD

**Issue by Efreak** [Templarian/MaterialDesign#987]
I'm looking for some extra icons for a program, and I was directed here. I'm not much of a designer, so the icons aren't terribly good; if anyone can do better, I'm just as happy with that.

I'm attaching them here because the form on the main page says that it's disabled, and it says not to submit pull requests.

Variant for power settings, puts the 3 dots in the top:

![power-settings-variant](https://cloud.githubusercontent.com/assets/749751/12470662/eba7aed0-bfaa-11e5-8c26-a1a0fbdd538c.png)

Reboot icon, distinct from reload/refresh.
![reboot](https://cloud.githubusercontent.com/assets/749751/12470670/fb5ab39a-bfaa-11e5-9ae4-fdd7f3abb2a9.png)

Soft reboot icon. I have no idea how to distinguish soft reset from hard reset, so I just blurred it. I know this isn't material design, but I haven't got any better ideas.
![soft-reboot](https://cloud.githubusercontent.com/assets/749751/12470708/48e28e44-bfab-11e5-847e-71527a32890e.png)

Recovery icon - I pulled this from a TWRP beta app on the play store; it seems to be their old icon. [TWRP is GPL3](https://github.com/TeamWin/Team-Win-Recovery-Project/blob/android-6.0/twrp.cpp), and I don't see any mention of their logo being under a separate license. I don't know much about licensing, though.
![recovery](https://cloud.githubusercontent.com/assets/749751/12470714/55bafeda-bfab-11e5-83ec-618918812c8c.png)

[icons.zip](https://github.com/Templarian/MaterialDesign/files/98605/icons.zip) (github won't let me embed the SVG files directly)

**Comment by CoDEmanX** [comment]
I would actually prefer https://design.google.com/icons/#ic_settings_power to bring up a list which contains (text-only) buttons to shutdown / reboot / recover...

**Comment by CoDEmanX** [comment]
These should work nicely: https://github.com/Templarian/MaterialDesign/issues/2304#issuecomment-319775203

**Comment by JamesCoyle** [comment]
Closing in favor of #2304
