### ISSUE TITLE
Wii U icon

### ISSUE THREAD

**Issue by GreenTurtwig** [Templarian/MaterialDesign#988]
Could just use the normal Wii icon but a Wii U icon might be better for certain uses.

![image](https://cloud.githubusercontent.com/assets/15905797/12476729/101ad5bc-c023-11e5-8b07-4a091364e8f9.png)
Here's an example. :-)

**Comment by GreenTurtwig** [comment]
Now that I can make icons. ;-)  
[wiiu.zip](https://github.com/Templarian/MaterialDesign/files/430539/wiiu.zip)

**Comment by Templarian** [comment]
[![wiiu](https://materialdesignicons.com/icon/wiiu)](https://materialdesignicons.com/icon/wiiu)

Left it non pixel perfect since it's a branding logo.
