### ISSUE TITLE
Table join icons

### ISSUE THREAD

**Issue by hudsonb** [Templarian/MaterialDesign#989]
Table join icons consisting of two overlapping circles.

Inner join: overlapping section filled
Left join: left circle filled
Right join: right circle filled
Full outer: both circles filled

Similar to the images found here: http://www.codeproject.com/Articles/33052/Visual-Representation-of-SQL-Joins

**Comment by CoDEmanX** [comment]
We sort of have icons for this already, but they are rectangular in shape. Search for vector or diff / intersection on the page.

I'll check though how well this works with circles.

**Comment by Templarian** [comment]
I think these would be a good solution to have for uses in DB related applications.

`join-*` naming style, unless there is something more generic.

**Comment by hudsonb** [comment]
The vector/diff icons are similar, but I don't think they cover all the joins. Right join for example is not represented (with vector-difference-ab is closest).

Additionally, I think the overlapping filled/unfilled circles is what users/devs are used to seeing.

**Comment by CoDEmanX** [comment]
Well, these are set operations: https://en.wikipedia.org/wiki/Set_theory

I agree that we should have these as circles. The existing icons have a slightly different meaning, they are meant for 2D vector graphic operations.

**Comment by CoDEmanX** [comment]
![set_all](https://cloud.githubusercontent.com/assets/1309249/12497324/6f654282-c09b-11e5-90cf-eb4ed322f579.png) not really looking like circles anymore
![set_all_variant](https://cloud.githubusercontent.com/assets/1309249/12497320/6f62ac16-c09b-11e5-8fe9-88f95540db27.png) not much better actually...
![set_center_right](https://cloud.githubusercontent.com/assets/1309249/12497325/6f689e1e-c09b-11e5-8b50-a4184c1955cd.png) more like two stacked circles
![set_center_right_variant](https://cloud.githubusercontent.com/assets/1309249/12497322/6f635a44-c09b-11e5-9919-eaf248278853.png) ok
![set_intersection](https://cloud.githubusercontent.com/assets/1309249/12497321/6f62d95c-c09b-11e5-851e-42233e4241cd.png) ok
![set_left](https://cloud.githubusercontent.com/assets/1309249/12497323/6f640228-c09b-11e5-92f3-a884e23a3498.png) could be mistaken for a switch
![set_left_center](https://cloud.githubusercontent.com/assets/1309249/12497327/6f7afb36-c09b-11e5-89a4-7de22f58b4c2.png) flicker logo, anyone?
![set_left_center_variant](https://cloud.githubusercontent.com/assets/1309249/12497328/6f7c1eb2-c09b-11e5-8ef6-2fb23c5c50e3.png) ok
![set_left_right](https://cloud.githubusercontent.com/assets/1309249/12497330/6f7cee96-c09b-11e5-9fcb-8964d78ee108.png) meh
![set_left_right_variant](https://cloud.githubusercontent.com/assets/1309249/12497329/6f7ce31a-c09b-11e5-94a6-1b83f3019bf8.png) ...
![set_none](https://cloud.githubusercontent.com/assets/1309249/12497326/6f7a7076-c09b-11e5-8925-b20a9ad2d996.png) ok
![set_none_variant](https://cloud.githubusercontent.com/assets/1309249/12497331/6f82535e-c09b-11e5-90b4-220fd4150f1b.png) not much like two circles

https://www.dropbox.com/s/95alpiwnm17g5hi/2016-01-22_set_theory.zip?dl=0

**Comment by hudsonb** [comment]
Wow that was quick! Maybe they'd be more distinguishable if the circles overlapped less?

**Comment by CoDEmanX** [comment]
Yeah, probably, but it's a tricky business because we need to stay on the pixel grid...

**Comment by Templarian** [comment]
I think the overlap amount is good, considering the limitations put in place for a material icon. Will be working to get these in this weekend.

**Comment by CoDEmanX** [comment]
😴 💤

**Comment by hudsonb** [comment]
I'd still love to see these included!

**Comment by Templarian** [comment]
Marked as high priority. We need to get these added.

**Comment by Templarian** [comment]
Added these with a "odd" one pixel line to separate the circles. This visually at 24x24 looks the best while scaling up. Looked a little too bold using the full 2dp line.

[![set-all](https://materialdesignicons.com/icon/set-all)](https://materialdesignicons.com/icon/set-all) [![set-center](https://materialdesignicons.com/icon/set-center)](https://materialdesignicons.com/icon/set-center) [![set-center-right](https://materialdesignicons.com/icon/set-center-right)](https://materialdesignicons.com/icon/set-center-right) [![set-left](https://materialdesignicons.com/icon/set-left)](https://materialdesignicons.com/icon/set-left) [![set-left-center](https://materialdesignicons.com/icon/set-left-center)](https://materialdesignicons.com/icon/set-left-center) [![set-left-right](https://materialdesignicons.com/icon/set-left-right)](https://materialdesignicons.com/icon/set-left-right) [![set-none](https://materialdesignicons.com/icon/set-none)](https://materialdesignicons.com/icon/set-none) [![set-right](https://materialdesignicons.com/icon/set-right)](https://materialdesignicons.com/icon/set-right)

**Comment by JamesCoyle** [comment]
It's a tough one to fit into the spec but I think those are the best we're gonna get.
