### ISSUE TITLE
Search person icon

### ISSUE THREAD

**Issue by niteshkhatri** [Templarian/MaterialDesign#990]
Hi I need an icon for searching a person.

I looked at https://materialdesignicons.com/icon/account-search. But didn't liked it.

Below are a few ideas I had in mind. You can suggest some other icon as well.

![image](https://cloud.githubusercontent.com/assets/7664984/12489711/a0557c4e-c097-11e5-9a6a-9e6fe055270f.png)

**Comment by Templarian** [comment]
There may be a way to include a single account into https://materialdesignicons.com/icon/magnify similar to the https://design.google.com/icons/#ic_person_pin_circle

**Comment by niteshkhatri** [comment]
@Templarian Thank you. I had similar idea in mind. Can you please provide such an icon on material design website?

**Comment by Templarian** [comment]
Eventually probably. Takes a bit sometimes, but one of the contributors or myself will make one.

**Comment by CoDEmanX** [comment]
Hm... it could be mistaken for a magnifier with a light reflex on it...

![human_search3](https://cloud.githubusercontent.com/assets/1309249/12497641/55b3fd4a-c09d-11e5-8230-2fd124d8d6be.png)
![human_search2](https://cloud.githubusercontent.com/assets/1309249/12497640/55b270ba-c09d-11e5-985a-465dc3d64be5.png)
![human_search](https://cloud.githubusercontent.com/assets/1309249/12497639/55b0b52c-c09d-11e5-87a9-a347c417c5d6.png)

**Comment by niteshkhatri** [comment]
@CoDEmanX Are these available on www.materialdesignicons.com ? I wanna see their bigger image.

**Comment by CoDEmanX** [comment]
No, maybe never will. I can give you the SVGs though. Here are 96x96 pixel renders:

![human_search3_96](https://cloud.githubusercontent.com/assets/1309249/12506655/f69a1502-c0f0-11e5-95d8-bc6539004ab0.png) ![human_search2_96](https://cloud.githubusercontent.com/assets/1309249/12506657/f69dcfc6-c0f0-11e5-893c-3fd0012bc75c.png) ![human_search_96](https://cloud.githubusercontent.com/assets/1309249/12506656/f69c624e-c0f0-11e5-9700-1bc41fc63c28.png)

**Comment by niteshkhatri** [comment]
@CoDEmanX Thanks. I liked your icons. Can you please provide me the svg for both the icons? I will be thankful.

**Comment by niteshkhatri** [comment]
@CoDEmanX Please provide me the icon's svg file.

**Comment by CoDEmanX** [comment]
Here you go:
https://www.dropbox.com/s/3th7aejhyhcbcjp/human_search.svg?dl=0
https://www.dropbox.com/s/7i4qjsklfg5kd6f/human_search2.svg?dl=0
https://www.dropbox.com/s/tb5dc0v4skwchx4/human_search3.svg?dl=0
https://www.dropbox.com/s/hfdbvhg9z96hrm7/human_search4.svg?dl=0

**Comment by niteshkhatri** [comment]
@CoDEmanX Thank man. However I am having some trouble. When I am creating icons from your svg file via https://materialdesignicons.com/custom , below is the icon I am getting.

![image](https://cloud.githubusercontent.com/assets/7664984/12543989/6df99624-c35b-11e5-9df2-ff7fc350e487.png)
 There is no user in the centre.

Can you please provide me the pngs in these sizes: 24, 36, 48, 72 ?

I will be thankful.

**Comment by Templarian** [comment]
This will be added sometime this week. TBH, I'm not 100% sure if I want to keep the `account-search` we currently have. It's kind of a ugly icon. May be best to replace it.

**Comment by niteshkhatri** [comment]
@Templarian Sounds cool. It will be great if this icon will be available in materialdesignicons site.

**Comment by CoDEmanX** [comment]
@niteshkhatri: human_search3.svg wasn't combined into a single object. I updated it, please re-download and try again. Aside from that, they look perfectly fine to me.

**Comment by Templarian** [comment]
[![account-search](https://materialdesignicons.com/icon/account-search)](https://materialdesignicons.com/icon/account-search)
