### ISSUE TITLE
Produtct

### ISSUE THREAD

**Issue by nsbrno** [Templarian/MaterialDesign#991]
New icon for product

![Image of Yaktocat](http://icons.iconarchive.com/icons/custom-icon-design/flatastic-2/256/product-icon.png)

![Image of Yaktocat](//az177188.vo.msecnd.net/static/customermantra/images/inventory_big_icon.png?ver=2)

**Comment by Templarian** [comment]
This exists already as https://materialdesignicons.com/icon/package

If you search `package` there are a few variations that represent a box/product.
