### ISSUE TITLE
materialdesignicons show different icon what was placed

### ISSUE THREAD

**Issue by edelCustodio** [Templarian/MaterialDesign#993]
Hi all,

I hope someone can help me, when I set the mdi-bell icon, in the browser appears battery-charging-90 icon.... that's a bit crazy, please, can someone help me?

**Comment by Templarian** [comment]
http://cdn.materialdesignicons.com/1.4.57/ Looking here it looks fine, the CSS is matching the icon.

Did you recently update and forget to overwrite the font files and css? Could be a cache issue.

The next release of MDI will contain fixed code points, so there will be no shifting icon, but that doesn't really explain your issue.

**Comment by edelCustodio** [comment]
Hi Templarian for your answer, so, I already solved, the thing is you have to place first lumx.css and later materialdesignicons.css reference....
