### ISSUE TITLE
Check for Updates icon

### ISSUE THREAD

**Issue by xaviergonz** [Templarian/MaterialDesign#994]
An icon for a button used to check for new software updates.
Maybe something like this? I don't know...

https://www.iconfinder.com/icons/181288/cloud_refresh_reload_renew_sync_update_icon

**Comment by CoDEmanX** [comment]
A cloud-sync icon would be nice indeed.

But you may also use this icon:

[![sync](https://materialdesignicons.com/icon/sync)](https://materialdesignicons.com/icon/sync)

**Comment by CoDEmanX** [comment]
Not much space for the reload thingy, but it kinda works:

![cloud-sync](https://cloud.githubusercontent.com/assets/1309249/14770901/97c86aae-0a7b-11e6-9ac7-ccdbcabc99da.png) ![cloud-sync2](https://cloud.githubusercontent.com/assets/1309249/14770902/97c89812-0a7b-11e6-8d4b-f7af5b2bf657.png) ![cloud-sync3](https://cloud.githubusercontent.com/assets/1309249/14770903/97c8e97a-0a7b-11e6-8ee2-1eaf177c5135.png)

**Comment by Templarian** [comment]
These look good, I think the 3rd is probably the best for consistency.

**Comment by CoDEmanX** [comment]
`sync-alert` and `sync-off` are actually rotated like the arrows in 1 and 2, but I also think that 3 is the best (arrows look centered without being too close to each other):

https://www.dropbox.com/s/c5j93hk2e8liuud/cloud-sync3.design?dl=0

**Comment by Templarian** [comment]
I was actually 50/50 between 2/3, just went with 3 because it matches the base `sync`.

[![cloud-sync](https://materialdesignicons.com/icon/cloud-sync)](https://materialdesignicons.com/icon/cloud-sync)

**Comment by xaviergonz** [comment]
Nice!
