### ISSUE TITLE
Add icon for "humid" 

### ISSUE THREAD

**Issue by dgngulcan** [Templarian/MaterialDesign#995]

**Comment by Templarian** [comment]
https://materialdesignicons.com/icon/water-percent I think you mean this icon?

**Comment by dgngulcan** [comment]
Exactly, thank you for pointing it out. I probably missed it and couldn't find it via searching "humid" :)

**Comment by CoDEmanX** [comment]
We should have it tagged accordingly.

**Comment by Templarian** [comment]
Done. `humidity`, but searching `humid` will pull it up also.

**Comment by CoDEmanX** [comment]
Obviously :smile: Works most of the time English, not so much in other languages. Although "half" wouldn't match "halves" either. Anyway, thank you!

**Comment by dgngulcan** [comment]
Awesome!!
