### ISSUE TITLE
icon request: exclamation-circle

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#997]
Just like Google made the [Info](https://design.google.com/icons/#ic_info) icon, it would be great to have an exclamation mark in a circle

**Comment by CoDEmanX** [comment]
We do have https://materialdesignicons.com/icon/alert-circle, but I guess you refer to https://design.google.com/icons/#ic_error_outline. It's on the TODO (#420, row 199 in the spreadsheet).

**Comment by keunes** [comment]
Thanks for the quick reply. Actually I was looking for the alert-circle by Google, but didn't use the right search term. If this is the right place to ask for the addition of an alias, I'd hereby like to do so (exclamation-mark-circle for alert-circle).

Thanks anyway for your work guys! :)

**Comment by Templarian** [comment]
[![alert-circle-outline](https://materialdesignicons.com/icon/alert-circle-outline)](https://materialdesignicons.com/icon/alert-circle-outline)
