### ISSUE TITLE
icon request: sleep-timer

### ISSUE THREAD

**Issue by keunes** [Templarian/MaterialDesign#998]
[AntennaPod](https://github.com/AntennaPod/AntennaPod) uses Google's '[sleep](https://materialdesignicons.com/icon/sleep)' icon for it's sleep timer function (allowing users to set time-to-fade-out for playback when going to sleep). Would love to see a different icon which indicates also the 'timer' part of the function. Something like [this](http://de.123rf.com/photo_32916436_sleep-well-icons.html): 
![32916436-sleep-well-icons-lizenzfreie-bilder](https://cloud.githubusercontent.com/assets/11229646/12536097/370ace92-c29a-11e5-827d-6330d101f89a.jpg)

But then nicer, I guess combined with Google's '[clock](https://materialdesignicons.com/icon/clock)' or '[alarm](https://materialdesignicons.com/icon/alarm)' icon.

**Comment by SLembas** [comment]
Tried myself: http://slembas.esy.es/sleep.svg

**Comment by SLembas** [comment]
Uh, I found [these](https://materialdesignicons.com/icon/sleep) Z's. I used modified Roboto contours.

**Comment by keunes** [comment]
Tot be honest I like the gap in the clock but think it's kinda 'necessary' to have multiple z's to make it clear it's about sleeping.

**Comment by SLembas** [comment]
Found an icon on the official repisitory called Snooze. Use search to find it. https://design.google.com/icons/

**Comment by CoDEmanX** [comment]
Tracked in #420, row 246 in the spreadsheet.

**Comment by keunes** [comment]
Sorry to come back to this after such a long time. I just saw that someone in the AntennaPod project referred to another app that also has a sleep timer icon:
![screenshot_2016-05-20-02-48-15](https://cloud.githubusercontent.com/assets/11229646/17076613/45f09cd8-50b7-11e6-8252-ac0543b513cb.png)

I haven't proposed to use Google's 'snooze' icon (which was suggested here) to the AntennaPod project because 'snooze' is about an alarm (and indeed the icon looks much like an alarm clock, rather than a regular clock). Snooze is quite the opposite of what a sleep timer aims at (the application will _stop_ playing after x minutes rather than _starting_ again in x minutes) and using this icon for a sleep timer function may be confusing.

So if someone still would like to devote time to create a specific sleep timer icon that'd be great :)

<sub>@codemanx Could you reopen this issue? :)</sub>

**Comment by CoDEmanX** [comment]
I see what you mean. I don't think we can fit a clock and 3x Z in one icon...

Instead of a clock, maybe combine the power off icon with zzZ?

**Comment by keunes** [comment]
> I see what you mean. I don't think we can fit a clock and 3x Z in one icon...

I guess a small clock and one or two z's would do ;)

> Instead of a clock, maybe combine the power off icon with zzZ?

What is the 'power off' icon? Can't find anything which I imagine could work on Material Icons (Google) or Material Design Icons (community).

AntennaPod now just has thee z's (which works, but some visual link to 'timer' would be nice):
![screenshot_2016-07-23-10-16-18](https://cloud.githubusercontent.com/assets/11229646/17076940/75bcdbcc-50bf-11e6-9f17-fffcfdbcf3d9.png)

**Comment by Templarian** [comment]
[![alarm-snooze](https://materialdesignicons.com/icon/alarm-snooze)](https://materialdesignicons.com/icon/alarm-snooze)
