### ISSUE TITLE
Idea for a new RSS icon

### ISSUE THREAD

**Issue by SLembas** [Templarian/MaterialDesign#999]
It would look perfect if it looked like [Wi-Fi](https://materialdesignicons.com/icon/wifi) icon, but formed 90 degree angle.

**Comment by SLembas** [comment]
Tried myself.

![tank-24](https://cloud.githubusercontent.com/assets/5235533/12538556/1ddfdade-c2e5-11e5-859e-8bc0beba3906.png)
![tank-48](https://cloud.githubusercontent.com/assets/5235533/12538555/1ddc0a4e-c2e5-11e5-9d04-57118ce6b608.png)
![tank-192](https://cloud.githubusercontent.com/assets/5235533/12538554/1ddbacb6-c2e5-11e5-9f4c-56b2ac5405b1.png)

**Comment by CoDEmanX** [comment]
Like #548?

**Comment by SLembas** [comment]
No, the central dot should be not round.

**Comment by SLembas** [comment]
There you go: http://slembas.esy.es/rss.svg

![rss](https://cloud.githubusercontent.com/assets/5235533/12539087/63dcc00c-c2f3-11e5-8344-00490155ab5c.png)

**Comment by CoDEmanX** [comment]
That doesn't look like an RSS icon... all RSS icons on the web seem to use a circle and two circle segments: https://www.google.com/search?q=rss&tbm=isch

**Comment by SLembas** [comment]
I mean it could be separate icon. But will be very useful and keeps 100% material look.

**Comment by Templarian** [comment]
I'm going to swap out the RSS icon currently for @CoDEmanX's in #548.

The RSS icon is pretty standard circle with two lines as said. Can you guys think of a name for this icon? `signal`, `radio-signal`, etc?

**Comment by SLembas** [comment]
Yep, `signal` could be the default one.

**Comment by CoDEmanX** [comment]
I came across such an icon today by incident. It is used in an ad, as symbol for mobile network quality (top left corner, "radio telephone network C quality"):

![Imgur](http://i.imgur.com/tIyAVke.png?1)

**Comment by Templarian** [comment]
Fixed the RSS icon.

[![signal-variant](https://materialdesignicons.com/icon/signal-variant)](https://materialdesignicons.com/icon/signal-variant)
